### ISSUE TITLE
SMTP Properties does not allow blank User Name/Password

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#1006]
If the User Name or Password fields are set to blank, after clicking "Save" these fields are reset to the default values: Admin/<somepassword>.

This is confusing if the SMTP Server does not actually require username/password authentication - in this case, it would be better if these fields remained blank to indicate that they are not used.

**Comment by azturner** [comment]
@MrUpsideDown , I'm not able to reproduce this. Are you referring to the SMTP Communicaiton Transport settings? Do you see this behavior on the demo site: http://rock.rocksolidchurchdemo.com/page/170?

**Comment by MrUpsideDown** [comment]
Yep, just tried it on the demo site - to repro:
1 Open the SMTP properties page
2. Clear the User Name field.
3. Save.

If you re-open the page, the User Name has been reset to "Admin" whereas it should be empty.

**Comment by azturner** [comment]
Yeah that's exactly what I'm doing and it leaves the values as blank ( and when I first viewed the settings after your last post, they were blank) . Is it possible you have a browser extension that might be filling those values in for you when they're empty?

**Comment by MrUpsideDown** [comment]
Yep, good catch!
I am using Chrome and it is populating the User Name and Password fields automatically as soon as I open the Properties window.
I tried the same thing in IE, and the fields remained blank as expected.

Seems like this is a Chrome behaviour that needs a work-around:
http://stackoverflow.com/questions/15738259/disabling-chrome-autofill

Is it ok to disable autofill for these fields? I'm happy to try to fix and test this if you like?

**Comment by edmistj** [comment]
Disabling autofill is fine. Can you do a pull request?

**Comment by MrUpsideDown** [comment]
Actually, this seems to be working as expected in v45.0.2454.
According to the stackoverflow issue referenced above, the problem randomly comes and goes with various Chrome updates, and there is no definitive fix. So I think it's best to close this issue.
