### ISSUE TITLE
Check-in Label Print Order is not consistent

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#1007]
From #831: Is there any way I can change the order that the check-in labels are being sent to the printer? @nairdo 's idea is right on, but without being able to change the order, the cut command usually comes at the beginning of the print instead of the end, and that's no good!

**Comment by bwitting** [comment]
@azturner  Thanks!

**Comment by azturner** [comment]
@bwitting , while the check-in configurator does not specifically allow the ordering of labels, they are stored as group-type attributes, so if you edit the group types in the General -> Group Types, you can set the order of those "attributes". The v3.2 update will include an update to actually then print them in the correct configured order.
