### ISSUE TITLE
Family GroupMembers are getting added with GroupMemberStatus of Inactive

### ISSUE THREAD

**Issue by mikepetersonccv** [SparkDevNetwork/Rock#1013]

**Comment by ccofnow** [comment]
@mikepetersonccv will this go back and re-activate the people who have been added to their families as inactive in the meantime?

**Comment by mikepetersonccv** [comment]
@ccofnow the next update will go back and fix up families.  (see https://github.com/SparkDevNetwork/Rock/commit/769dd04370a7561f9dd06fc3ff2669f59d8e0e70#diff-c6776c97f8fc989227f023ec1a8818baR89)
