### ISSUE TITLE
Inactive Groups Show Up In Group Finder

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1019]
There isn't an option to exclude groups from the finder.  Marking them Inactive doesn't remove them from the map or the list.

**Comment by MrUpsideDown** [comment]
The Group Viewer has been modified to add "Active/All" buttons to toggle the visibility of Inactive Groups. This change will be available in the next update.

**Comment by mikepetersonccv** [comment]
yep, that option will be available in v4

**Comment by nairdo** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/686abf50200ef1de800388ff06db79fede7a9072

**Comment by nairdo** [comment]
Oops, we'll do something similar in the Group Finder.
