### ISSUE TITLE
Groups don't inherit the top level group's permission

### ISSUE THREAD

**Issue by dsmallman** [SparkDevNetwork/Rock#1020]
If you give edit permissions to a user at top level of a Group, the permissions show as being inherited on the lower level groups, but the inherited permissions do not work.

If you go to one of the lower groups and add the edit permissions there, then the user can edit that sub group.

Please see the following question: http://www.rockrms.com/Rock/Ask/Using/Questions/576

**Comment by MrUpsideDown** [comment]
It would be very useful to have a "Show Auth" feature for the Group Viewer that operates in a similar way to the Page Map. This would make configuring (and troubleshooting) permissions for branches of the Group Tree much easier.

**Comment by arranf** [comment]
Working as of 1.5.2
