### ISSUE TITLE
Workflow Assigns Random Worker

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1023]
A number of our workflows seem to be picking workers randomly out of our database.  Even when I manually specify who the work should be, it still randomly assigns a new person.  This workflow has specific people already assigned to certain activities inside the workflow which are getting ignored.

![image](https://cloud.githubusercontent.com/assets/7409839/7499126/728a08a0-f3da-11e4-8bac-d46eb2978fe3.png)

![image](https://cloud.githubusercontent.com/assets/7409839/7499138/8038b5dc-f3da-11e4-9a71-36fb952aa484.png)

**Comment by BelAirIT** [comment]
Tracked down this issue.  It seems to occur when I add an Activity to a workflow after it's already started.  It scrambles the assigned person from there.  The alpha 3.3 doesn't appear to exhibit this behavior but I'll keep checking.

**Comment by azturner** [comment]
This looks like it is an issue when manually assigning an activity to a person. The selected person's id was being saved instead of their person alias id so if those id's were different, it would assign to wrong person.
