### ISSUE TITLE
Bulk Update Add to Group not working in 3.2 in Firefox 

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1030]
3.2
Data view, select multiple people to add, Truck update, Group.

Group section no longer displays the Members Status field.
![grpadd1](https://cloud.githubusercontent.com/assets/4658177/7562481/dd12c034-f828-11e4-8d27-e17ef9f82222.JPG)

Selecting  Next, Confirm does not add the selected individuals to the group.

**Comment by arranf** [comment]
Hey Ken,
I have used this feature frequently in 3.2 and it is working for me. Have
you tried selecting a group and then adding?

Arran

On 11 May 2015 at 11:07, Ken Roach <notifications@github.com> wrote:

> 3.2
> Data view, select multiple people to add, Truck update, Group.
>
> Group section no longer displays the Members Status field.
> [image: grpadd1]
> <https://cloud.githubusercontent.com/assets/4658177/7562481/dd12c034-f828-11e4-8d27-e17ef9f82222.JPG>
>
> Selecting Next, Confirm does not add the selected individuals to the group.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkDevNetwork/Rock/issues/1030>.
>



-- 
*Arran France*
Communications, Youth Work, and Administration
*T*. 07425 159471

*Hope Church Corby*
Registered UK Charity 251549
The Hope Centre
8 Princewood Road
Corby
NN174AP

**Comment by ElimAdmin** [comment]
Hi Arran.  Yes, I selected a group.  You can't get past this screen unless you select a group.  Have just tried it on another PC using Explorer, and as soon as I selected a group the Role and Member Status fields appear correctly.  Will check later if see if this is a Firefox issue.

**Comment by ElimAdmin** [comment]
May be a Fifefox issue.
Firefox v37.0.2 - fails on more than one PC: one running XP, the other running Windows 7.
Opera running on the XP machine does not fail: it correctly displays the Role and Member Status fields.
@arranf: what browser are you using?

Here's a vid clip showing these fields not displaying:
![grpadd1](https://cloud.githubusercontent.com/assets/4658177/7585950/c8240204-f8fb-11e4-8386-d62f7c026a6d.JPG)

**Comment by arranf** [comment]
I'm a Chrome user.

**Comment by ElimAdmin** [comment]
Got Firefox that you can try it on?

**Comment by arranf** [comment]
Just tried in FF. Experiencing the same behaviour as you.

**Comment by tommyprater** [comment]
Im still running 3.1 and noticed the same issue. With chrome it works great.

**Comment by arranf** [comment]
Works in 1.5.2 and Firefox 48.0
