### ISSUE TITLE
Person Search Page Description is incorrect.

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#1033]
The Description of the Person Search Page incorrectly reads "Screen to administrate campuses."

**Comment by nairdo** [comment]
What version of Rock are you seeing this on? I just noticed this too on mine in the 'develop' branch last night.

**Comment by MrUpsideDown** [comment]
I'm seeing it in the develop branch, but it's also wrong on the demo site.
The difference is that the Page Description is now visible in develop whereas it's not displayed in 3.2.

**Comment by edmistj** [comment]
We added the page description to show on the internal template. There is a migration coming that will blank out the current descriptions. This will allow admins to create report pages that describe the purpose for the report at the top of the page.

**Comment by MrUpsideDown** [comment]
Does that mean all of the Page Descriptions will disappear completely?
I liked this feature, thought it was a useful addition to the existing pages (where the description was correct!)

**Comment by edmistj** [comment]
Yes, the plan was to remove all the descriptions from the internal site. A majority of the current descriptions seem to be a restatement of the page title with not much to add.

**Comment by MrUpsideDown** [comment]
I'm sure that's true in a lot of cases. But I noticed it was very helpful in areas like the "System Settings" pages where the names of some categories do not sufficiently describe their purpose. eg. "File Storage Providers", "Data Transformations", "Data Selects", etc. So maybe it would be good to leave/add descriptions for pages where the function is not immediately obvious?

**Comment by edmistj** [comment]
Would you be willing to provide the page ids of the page you think we should keep? I could then exclude those from the delete.

**Comment by MrUpsideDown** [comment]
Yep, will do.

**Comment by nairdo** [comment]
@MrUpsideDown you'll have to update us on how your move to Rock went (also let us know if we're welcome to tweet/blog about it too.)

**Comment by edmistj** [comment]
@MrUpsideDown Have you had a chance to get the page id's of the pages with helpful descriptions?

**Comment by MrUpsideDown** [comment]
Not really, sorry. This has been a case of "out of sight, out of mind"... since we went live with Rock, I have spent all of my time working with 3.4, where the Page Descriptions are not visible. I went so far as to start a list of page descriptions, but it is woefully incomplete so not much use at the moment. I still think it would be good to have a description for every page, but perhaps you could remove them all for 4.0 and reinstate them in a later release when the list is complete?

**Comment by FrankGrand** [comment]
searched this topic because I still see this description on the Person Search Page....is that because we are using develop branch code?

**Comment by edmistj** [comment]
I haven't run the script to delete the page descriptions yet. I plan to soon though.
