### ISSUE TITLE
Schedule Builder not retaining PM time setting

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1035]
When maintaining a schedule in Metric/Edit Metric/Edit Schedule, if the time is set to PM, the next time you open the schedule the time is shown as AM.
![sched1](https://cloud.githubusercontent.com/assets/4658177/7664150/ce83b272-fbce-11e4-97ba-e61a783e3448.JPG)
![sched2](https://cloud.githubusercontent.com/assets/4658177/7664149/ce7fdbde-fbce-11e4-8c43-aca73e7c3481.JPG)

**Comment by mikepetersonccv** [comment]
this is fixed in v4.0
