### ISSUE TITLE
Restrict access to Benevolence Tab to Benevolence/Finance Roles?

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#1036]
The Benevolence tab of the Person Profile is currently viewable by All Users.

Is this intentional? It seems to me that the default security for this page should be restricted to Users with the Benevolence or Finance Worker Roles.

**Comment by tcavaletto** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/d8cce8f8c965a4dce2402143e90e6dd289ec3996
