### ISSUE TITLE
Metrics being sorted in the right order?

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1044]
This will not normally be an issue if there is only one metric per metricvaluedatetime, but if there is...

If the [order] field in the metricvalue table is for the purposes of sorting metric values correctly:

the display of values on the graph, and in the metric value table are not respecting 
order by metricid,matricvaluedatetime,[order]

The values:
![metric1](https://cloud.githubusercontent.com/assets/4658177/7688844/2a6d4196-fdfc-11e4-9522-6a1ce3152c3d.jpg)

The graph (showing the 51 after the 5 for the date  )
![metric2](https://cloud.githubusercontent.com/assets/4658177/7688850/30243ee6-fdfc-11e4-9c85-e53222f08d98.jpg)

The metric values showing the values not sorted in the right order:
![metric3](https://cloud.githubusercontent.com/assets/4658177/7688852/33d74c72-fdfc-11e4-8ce0-d2bb5467756b.jpg)

**Comment by nairdo** [comment]
@ElimAdmin , I agree that the MetricValueList is not ordering them as you stated, but are you sure the 5 and the 51 is not pictured on that chart/graph?  When I set up some similar data (a 28 & 33 on the same day), I see both appear on the same day when I carefully hover over the line (as seen in these two screenshots).
![image](https://cloud.githubusercontent.com/assets/383807/7716721/dafccbaa-fe4a-11e4-92f3-cc01e1697622.png)

**Comment by ElimAdmin** [comment]
@nairdo - yes you are right: both values are shown on the graph, but not in the [order] order.

**Comment by arranf** [comment]
I'll fix this one.

**Comment by arranf** [comment]
@ElimAdmin I've finally gotten around to taking a look at this and I'm struggling to find where you can actually view the fields listed in your first screenshot. Could you point me in the right direction?

**Comment by cabal95** [comment]
Closing as there is no longer an `Order` column for MetricValues.
