### ISSUE TITLE
Batch List shows a roll-up for all accounts?

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1046]
I used the new RowLimit filter option (see PR #1045) to limit my results to 2.  However, the roll-up shows detail from all accounts (active + inactive), not just those selected or filtered by campus:
![screenshot 2015-05-18 16 54 46](https://cloud.githubusercontent.com/assets/1210933/7690151/9ae052a6-fd7f-11e4-9c2e-1b05146551ba.png)

Is this expected behavior? We have 134 accounts so that roll-up slows the page down considerably.

**Comment by tcavaletto** [comment]
There's been several changes in the BatchList block since May 18th (https://github.com/SparkDevNetwork/Rock/commit/8f68f933162e59ff3b88fa16629fe4c1d1240542), and I was wondering if you're still seeing this bug.

**Comment by dcs619** [comment]
@tcavaletto It's not slow anymore but the roll-up is still half the page height.  
![image](https://cloud.githubusercontent.com/assets/1210933/8943069/c173befe-3546-11e5-8253-4e9d907ba43b.png)

**Comment by tcavaletto** [comment]
We haven't been able to replicate the problem. Could you send a screenshot that shows the filters you have on your batch list and a screenshot of your account list?

**Comment by edmistj** [comment]
This appears to be working and with the row limit filter not existing any longer since adding grid paging it seems moot. Please re-open and clarify if I'm missing something.
