### ISSUE TITLE
Simple Communication Mode Emails Use Global Attribute From Address as Opposed to Input From Address

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1049]
We've given access to our leaders to a simple communication entry block. Emails that are sent by people who aren't a part of any security role have their "From Address" as our global setting (admin@....) as opposed to their own email address.

The reply to address is set correctly.

**Comment by azturner** [comment]
This is actually a feature: http://www.rockrms.com/Rock/BookContent/8/48#safesenderdomains

**Comment by arranf** [comment]
Thanks for flagging that up, that makes way more sense.

On 19 May 2015 at 12:35, David Turner <notifications@github.com> wrote:

> This is actually a feature:
> http://www.rockrms.com/Rock/BookContent/8/48#safesenderdomains
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkDevNetwork/Rock/issues/1049#issuecomment-103453510>
> .
>



-- 
*Arran France*
Communications, Youth Work, and Administration
*T*. 07425 159471

*Hope Church Corby*
Registered UK Charity 251549
The Hope Centre
8 Princewood Road
Corby
NN174AP
