### ISSUE TITLE
Errors in Check Scan App?

### ISSUE THREAD

**Issue by FrankGrand** [SparkDevNetwork/Rock#1059]
When creating a new batch I get a popup that just says one or more errors have occurred.  The batch does get created, I have to click reload on the left hand side to see it.

Also when I try to save scans, I always get an error, sometimes one transaction saves, but nothing gets shown.

I've tried uninstalling and reinstalling the app and the same thing happens.

**Comment by edmistj** [comment]
@FrankGrand can you confirm that the update app has fixed these?

**Comment by edmistj** [comment]
Closing as I think this has been fixed. Please re-open if problem persists.
