### ISSUE TITLE
Report exported to Excel shows people's names as HTML

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#1063]
When using the FieldType "Person Name" with a Display Order of "LastName, FirstName" the data in Excel shows up like this:

     <a href='/person/451282'>Allen, Mona</a>

![image](https://cloud.githubusercontent.com/assets/383807/7866043/a3c22ce2-0521-11e5-91c2-0cd7bf4ef7b4.png)

**Comment by nairdo** [comment]
I'm considering something crafty like @MrUpsideDown  did in Grid.cs via https://github.com/MrUpsideDown/Rock/commit/f356d4268aa413755362f6cacb8c49d716b3362c , but I'm wondering if there's a better way to detect the PersonLinkSelect field rather than checking for "<a href=" in the string...

```csharp
private string GetExportValue( PropertyInfo prop, object propValue, bool isDefinedValueField, ExcelRange cell )
{
    // ...
    else
    {
        // Is the value a single link field? (such as a PersonLinkSelect field)
        if ( propValue.ToString().Split(new string[]{"<a href="}, StringSplitOptions.None).Length - 1 == 1 )
        {
            try
            {
                System.Xml.XmlDocument htmlSnippet = new System.Xml.XmlDocument();
                htmlSnippet.Load( new StringReader( propValue.ToString() ) );
                // Select the hyperlink tag
                var aNode = htmlSnippet.GetElementsByTagName( "a" ).Item( 0 );
                string url = string.Format( "{0}{1}", this.RockBlock().RootPath, aNode.Attributes["href"].Value );
                cell.Hyperlink = new Uri( url );
                value = aNode.InnerText;
            }
            catch ( System.Xml.XmlException )
            {
                value = propValue.ToString();
            }
        }
        else
        {
            value = propValue.ToString();
        }
    }
}

return value;
}
```

**Comment by MrUpsideDown** [comment]
@nairdo, It might be simpler/quicker just to try if (propValue.StartsWith("<!--"), and if True, extract the  HTML comment as the literal value of the field? My whole approach to this was a band-aid solution that needs re-work anyway, so probably no need to make your fix too clever!

**Comment by mikepetersonccv** [comment]
@nairdo @MrUpsideDown  we changed it so that it isn't prepended with the <!-- anymore.  See https://github.com/SparkDevNetwork/Rock/commit/07bcb3a79e11cbf815ef28e8f36dc015e65d9a99

**Comment by nairdo** [comment]
@mikepetersonccv after your change the data shows up as `<a href='/Person/3'>Decker, Ted</a>` in the exported excel spreadsheet, so I just submitted the 17014656fa1adb3da6f9fc2a67ae1fa01ffd807c change to handle and display the exported data correctly.

**Comment by mikepetersonccv** [comment]
cool! Looks good
