### ISSUE TITLE
Report Export to Excel Doesn't Respect Field Order

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1064]
**Steps to Reproduce:**
1. Add several fields to a report
2. Adjust the order of the fields
3. Export the Excel document 

**Expected Behaviour**
Excel would display columns in the order displayed in the report

**Actual Behaviour**
Excel displays the columns in the order they were added

**Comment by MrUpsideDown** [comment]
Arran,

I have already submitted a fix for this here:
https://github.com/SparkDevNetwork/Rock/issues/935

It will be released in 4.0.

**Comment by arranf** [comment]
Fantastic.
