### ISSUE TITLE
Photo Request Upload Failing on Some Mobile Devices

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1065]

**Comment by edmistj** [comment]
Do you have any specifics on which devices/versions?

**Comment by arranf** [comment]
I'm really sorry for the vague issue. It seemed to involve multiple devices
but I don't have specifics other than I've personally see it fail on a
Samsung using the AOSP stock browser. I'll see if I can get the
administrator to email me a list of people who struggled to upload but no
promises.

There's a separate issue I've raised about the responsiveness of the crop
(which I've seen on a iPhone 4) but this is specifically about the select
photo button.

On 29 May 2015 at 14:45, Jon Edmiston <notifications@github.com> wrote:

> Do you have any specifics on which devices/versions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkDevNetwork/Rock/issues/1065#issuecomment-106805663>
> .
>



-- 
*Arran France*
Communications, Youth Work, and Administration
*T*. 07425 159471

*Hope Church Corby*
Registered UK Charity 251549
The Hope Centre
8 Princewood Road
Corby
NN174AP

**Comment by tommyprater** [comment]
If im late to this and its been resolved or just a known fact forgive me but when I try to use the request photo and click the link on a mobile device, example iPhone 6 Plus and a Samsung android phone we get the same issue where we load the photo and it stretches it long but width is compressed almost together so we cant crop the photo and save it. If we hit save it saves the photo but seems like it randomly just cropped an area.

**Comment by arranf** [comment]
Closing due to inability to reproduce.
