### ISSUE TITLE
api/PersonBadges/FamilyAttendance Times Out

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#1069]
For some testing with Rock I have imported most of our Person, Family and Ministry Tag records. To test the Attendance reporting stuff I also imported the last 6 months of attendance data. It is roughly 35,000 rows of attendance data.

As soon as I import the attendance data the "attendance bar graph" stops working. The one on the left that shows just a numerical 4/16 still works fine.

When I hit the API called directly It waits for 20 (or maybe its 30) seconds and then comes back with a massive XML error stack trace saying the Time period elapsed.

Doing a SQL trace I saw that the sproc being run, and timing out was 'EXEC spCheckin_BadgeAttendance @PersonId=6394,@MonthCount=24'. Running that manually inside SSMS it comes back nearly instantly with the data.  I tried lowering the month count (in the API request so it still went through .NET) to 4 and got the same timeout error.

Any ideas on further troubleshooting I can do?  I would suspect the way I'm importing the data is causing issues, except that it works if I run the sproc directly.

IIS and SQL on are different VMs, so I suppose it could be network related, but watching Task Manager I see no spikes in network traffic, and CPU for SQL Server pegs for the duration of the run so it does seem to be stuck in SQL somewhere.

**Comment by azturner** [comment]
@cabal95 ,
Hey Daniel, good to see you here! Have you tried opening up SQL's Activity Monitor to see if there's any locks ( or other type of waits) that are preventing that query from executing from within Rock? We have about 2.2 million rows in our Rock db and not experiencing any issues (I know... the infamous "Works on my machine" response :) ). You also might try posting this question to the [Rock site](http://www.rockrms.com/Rock/Ask/Troubleshooting) ( the audience there is a little larger ).

**Comment by cabal95** [comment]
Hey David. So yea, even better this morning it is suddenly working just fine. I guess it just needed one of the developers to scare it into submission. I will head over to the main site and post a different attendance question.  Maybe the issue was related to the fact I bulk imported so many attendance records, but not sure why it worked in SSMS but not the website. *shrug*.
