### ISSUE TITLE
Send Attendance Job Running Multiple Times

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1070]
I've configured the send attendance job to send a reminder email on the second and fourth day using `2,4` however leaders are receiving three emails in a row.

We're using Mandrill and I can see three identical API calls occurring at the same time.

**Comment by arranf** [comment]
Removing the configured reminders on day 2 and 4 has had an impact. Now only two emails are being sent.

**Comment by ccofnow** [comment]
Arran, We're not actually sending our e-mails out yet (summer break), but I ran the task manually several times yesterday and only received a single e-mail each time. Have you tried running the job manually to see whether the issue is the job being run three times or if the job sends three e-mails?

**Comment by arranf** [comment]
@ccofnow. That's a great call. I just looked back through the audit log and
I can see that the job is firing multiple times which makes sense as, like
you, when I was testing the features I ran the job manually and only
received one email.

On 4 June 2015 at 23:16, ccofnow <notifications@github.com> wrote:

> Arran, We're not actually sending our e-mails out yet (summer break), but
> I ran the task manually several times yesterday and only received a single
> e-mail each time. Have you tried running the job manually to see whether
> the issue is the job being run three times or if the job sends three
> e-mails?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkDevNetwork/Rock/issues/1070#issuecomment-109071027>
> .
>



-- 
*Arran France*
Communications, Youth Work, and Administration
*T*. 07425 159471

*Hope Church Corby*
Registered UK Charity 251549
The Hope Centre
8 Princewood Road
Corby
NN174AP

**Comment by arranf** [comment]
I suspect this is an issue with shared hosting servers and/or Plesk. I've reports of this occurring there but when I migrated this installation to Azure the problem was solved.

**Comment by cabal95** [comment]
@arranf Do you feel good about this being closed since it is so old and was (it sounds like) never reliably reproduced?
