### ISSUE TITLE
Group Tree confusing with only inactive child groups

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#1075]
If the group tree Active/All option is set to Active, and a particular group in the tree has only inactive child groups, the collapse/expand triangle is still displayed next to the parent group, but doesn't do anything since all the child groups are inactive.

**Comment by arranf** [comment]
Confirmed as of 1.6.0 (in develop)

**Comment by nairdo** [comment]
I've prototype'd a solution, but I'm not sure it's good enough. The main problem is -- in rockTree.js we may know a node has children (expander triangle is open/right), but they aren't loaded until the user clicks on the triangle.  In my prototype, once they are loaded -- if there are NO active children, I remove the triangle icon. I believe I've seen this approach taken in another foldering environment.

![20161214-115641_capture](https://cloud.githubusercontent.com/assets/383807/21196396/b705a72a-c1f4-11e6-8188-9b5e462b377f.gif)

Thoughts?

**Comment by edmistj** [comment]
Seems reasonable to me.
