### ISSUE TITLE
Small Group leader logging attendance again causes exception

### ISSUE THREAD

**Issue by ccofnow** [SparkDevNetwork/Rock#1076]
If the leader of a Small Group clicks on the button they are sent to store attendance for their meeting, and then later clicks on the button again and clicks the Save button again, an exception is thrown. It would be nice if this would fail more gracefully- let them know they should edit the attendance in Group Toolbox (with a link) instead of trying to start over from scratch (or ideally, redirect them there automatically instead of loading the attendance form with all unchecked boxes), etc, so I don't get an e-mail.

When this happened to us, the leader thought they had to go through that process in order to get to the group toolbox- a simple training issue, but the e-mail reports seemed a little extreme =)

**Comment by arranf** [comment]
@ccofnow Is this exception still occurring on 1.5?

**Comment by ccofnow** [comment]
It does not seem to be

**Comment by arranf** [comment]
Done

**Comment by ccofnow** [comment]
One more observation- it's probably "working as intended" but if I do this, it will create records (marking an absence, naturally) for anyone who is NOW in the group that wasn't at the time. Like it's doing an INSERT OR UPDATE operation (not sure if that exists in Sql Server).

In my case I think it would be ideal to have it see if attendance for the event was stored and if so ONLY do an update for existing, but modified, statuses, rather than inserting missing statuses. But...I can also see when it would be desirable to have this behavior and programming for that condition, (rather than **expecting** it to be a group leader using a link from a year ago) is probably the best choice.
