### ISSUE TITLE
Duplicate SMS Messages Using Twilio

### ISSUE THREAD

**Issue by dsmallman** [SparkDevNetwork/Rock#1077]
Hi,

 We are experiencing duplicate and some triplicate SMS messages and it is starting to add up. Can you please look into this please? 

I see that a lot of work has been done on the Twilio API, so I thought I would as if this is a RockRMS issue or Twilio.  I also submitted a ticket to Twilio, but they say they are rarely the cause.

**Comment by azturner** [comment]
The Twilio transport needs to be updated to use the communications threadsafe 'GetNextPending' method similar to how the SMTPComponent transport does ( See [this question](http://www.rockrms.com/Rock/Ask/Using/Questions/602) for more details ).

**Comment by arranf** [comment]
I just had a chat with @MrUpsideDown and it seems like this issue may potentially be linked to #1070.

**Comment by arranf** [comment]
@azturner I'm not sure what the criteria for this is but would it be possible to add this to the 3.5 release? We're reluctant to use Twillio knowing that messages fire twice.
