### ISSUE TITLE
Flat Theme Padding

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1083]
There are a few instances where the padding for the Flat Theme causes text to be truncated (across multiple devices and OSs).  Changing the padding from 15px to 10px appears to solve this. 

![screenshot 2015-06-09 18 24 46 2](https://cloud.githubusercontent.com/assets/8703222/8064884/7c043dcc-0ed5-11e5-9197-1a6b98d75101.png)
![screenshot 2015-06-09 18 24 45](https://cloud.githubusercontent.com/assets/8703222/8064883/7c0395f2-0ed5-11e5-83f1-b5d473401665.png)

**Comment by sheck** [comment]
Hey @arranf, what page and modules are you using here? I'm having trouble reproducing this.

**Comment by arranf** [comment]
Custom page and it was the group detail lava block.

**Comment by arranf** [comment]
Reproduced [here](http://rock.rocksolidchurchdemo.com/page/5314?GroupId=59) for you on the demo site

**Comment by sheck** [comment]
@arranf sorry I never followed back up with you on this! Been crazy busy lately.

Can you confirm this issue is still occurring with the latest from develop?

**Comment by arranf** [comment]
@sheck Seems like it's been resolved!

**Comment by sheck** [comment]
![yes_napoleon_dynamite](https://cloud.githubusercontent.com/assets/3035506/10008239/6e8911ec-6081-11e5-9635-3404baff6541.gif)

**Comment by arranf** [comment]
That was a swift gif!
