### ISSUE TITLE
Lastest Version of Rock Source Code

### ISSUE THREAD

**Issue by bacsrlette** [SparkDevNetwork/Rock#1085]
Hi, I am new to this hub. Where can I find a link to download the latest version of the Rock source code?

**Comment by arranf** [comment]
Hey @bacsrlette. The latest (read: not ready for use in a production system) is in the develop branch here on Github. If you're wanting to download a copy of Rock to develop from, that's what you want. Otherwise you'll want to take a look at the [getting started page](http://www.rockrms.com/Rock/GetStarted) on rockrms.com

**Comment by bacsrlette** [comment]
Thanks for the reply. Yes, I want the latest version from the Develop branch, however I am not familiar very with GitHub and how to navigate around this system. I am not a developer, just passing information to our developer. What is the path to get to the develop branch to download the Rock source code?

**Comment by bacsrlette** [comment]
To be specific, there are alot of folders inside branch:develop. What folder contains the source code?

**Comment by nairdo** [comment]
The source is in many/most of those folders.  Several of the folders are VS projects (.csproj) that are part of the solution (.sln). If you aren't using a tool like Git to clone the source, you can use the Download ZIP button on the main repo page:
![image](https://cloud.githubusercontent.com/assets/383807/8071318/b6efa51a-0ebd-11e5-9fc1-4175bd8d1c57.png)

**Comment by nairdo** [comment]
Also, once you get rolling, you can post your dev questions over on our developer Q&A: http://www.rockrms.com/Rock/Ask/Developing

**Comment by nairdo** [comment]
@bacsrlette , One more thing... You should have your developer build a custom Rock SDK here: http://www.rockrms.com/Rock/Developer/Rockit (for developing custom Rock stuff) and then read/follow the developer guides here: http://www.rockrms.com/Developer

**Comment by bacsrlette** [comment]
Hi Nick,

Thanks for the info.

At this time we are only looking at the source code to see how RockRMS may
integrate with another application that we have.

I am not the technical person. Would it just be simpler and  faster to
download the Version 3.3 source code from here
http://www.rockrms.com/Rock/GetStarted?

**Comment by nairdo** [comment]
No, I don't think it would. The install release includes the compiled assemblies but not the complete source code.
