### ISSUE TITLE
HOW DO I INSTALL ROCKRMS ON MY LAPTOP

### ISSUE THREAD

**Issue by demurel** [SparkDevNetwork/Rock#1089]
Hello please i'm a newbie when its comes to asp.net.

Can someone guide me on how to install ROCKRMS on my Laptop.

**Comment by azturner** [comment]
Would suggest taking a look at the [documentation](http://www.rockrms.com/Learn/Documentation). There is a 'Rock Solid Internal Hosting' guide that describes how to install Rock on your own server (or laptop) . If you then still have questions, you can post them on the [community Q&A](http://www.rockrms.com/Rock/Ask) site.
