### ISSUE TITLE
Default select conditions for Homepage - Rotator doesn't pick up Secondary Audience

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1090]
This might have already been fixed, but just in case...

I just noticed that the select conditions on the Homepage - Rotator block on the main page were not picking up ads where the Secondary Audience was 'Homepage - Rotator.'  I had to change the select conditions to the following.  Does this need to be changed in the default install?

![mpgrotator](https://cloud.githubusercontent.com/assets/4658177/8158414/0cb0fbd2-13b1-11e5-9082-5bdf972be6cb.JPG)

**Comment by azturner** [comment]
This will be fixed with a migration.
