### ISSUE TITLE
RockRMS forums: Default organization URL being prepended 

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1094]
It looks like the default link for organization URL's is being prepended with "http://www.rockrms.com/Rock/Organization/[www.site.com]"

Our link is fixed but I've clicked on a few other organizations that are all like that.

**Comment by edmistj** [comment]
@dcs619 Do you have some samples you could provide?

**Comment by dcs619** [comment]
Just clicked through a few, it seems to be resolved.  You'd have to check the db to find links that are still broken.
