### ISSUE TITLE
UI: Fixed Width Font Awesome Icons in Lists

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#1095]
Hey Guys!

As we've begun working on theme development, one of the things I've noticed is that there are places where we are using font awesome icons in the context of a list. In that scenario, the alignment is kind of all over the place as every icon is a different width. This can be fixed by adding a class of fa-fw, which uses a fixed width version of each icon.

Before:
![image](https://cloud.githubusercontent.com/assets/2465823/8210276/47b2bf02-14df-11e5-9bc4-31e6ba8dba27.png)

After:
![image](https://cloud.githubusercontent.com/assets/2465823/8210291/5ac8dd60-14df-11e5-8c90-ef0acaf721b4.png)

Also, I'm not sure if other icons/libraries are being used – but if they are not – I wanted to suggest adding the initial fa and fa-fw (when necessary) classes to the blocks themselves to save users from having to re-type those classes repetitively in the control panel.

Let me know what you think! Thanks so much!

**Comment by edmistj** [comment]
Cool great tip!  We can add the fa-fw to the lists like you've shown. Do you think the fa-fw should be used in all cases where we use the font (like block titles)?  Seems like there wouldn't be a reason not to use it.

We did want to allow people to use alternative css fonts which is why we didn't prepend the fa.

Thanks for the tip!

**Comment by briankalwat** [comment]
I don't think it would be a great idea to use it in cases where it's a single icon (such as page titles), as it will make the spacing between the edges of the block and the icon inconsistent. I think it makes sense to use it when the context is a list where the icons are stacked vertically.

Thoughts on adding the fa and fa-fw (when necessary) classes to the blocks ascx.cs files?

**Comment by arranf** [comment]
If this was done how hard would it be to add a different custom icon font?

**Comment by briankalwat** [comment]
If we want to leave the option open for other icon fonts, it'd be better to leave the blocks files clean and just add all icon styles in the database. If we're going to use font-awesome as part of the system exclusively, it'd be helpful for users to include as much as possible to avoid the burden of repeating and maintaining consistency (less chance for user error).

**Comment by briankalwat** [comment]
@edmistj Would it be possible to add the fa-fw class to all instances of icons within rock tree elements?

It would make instances like this (below) look much cleaner. Thanks!

![image](https://cloud.githubusercontent.com/assets/2465823/8703195/0f665188-2aea-11e5-8999-ff7eec4d2051.png)

**Comment by edmistj** [comment]
@briankalwat I'm all for it and have changed a couple of them I've run across. It would be helpful if I could get a list of places you've found were they're needed. I created an abstract class called icon-fw to use.

**Comment by briankalwat** [comment]
@edmistj I've found an example of instances where fa-fw added. Anytime a dropdown menu is generated with this markup, where icons are present, the fa-fw class should be added. (https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Crm/PersonDetail/Bio.ascx.cs#L231) Also, I'm not sure if there's a way to add a class to the ul parent of the dropdown for style modifications, but if so, these classes should be added to even out the spacing in the dropdown items.

```css
.dropdown-menu li a {
   padding: 4px 10px 4px 4px;
}

.dropdown-menu li a i {
   margin-right: 3px;
}
```

Before: 
![image](https://cloud.githubusercontent.com/assets/2465823/9183473/3c838b70-3f7d-11e5-97d4-ce8ce2cc6286.png)

After:
![image](https://cloud.githubusercontent.com/assets/2465823/9183463/2f5ccfd8-3f7d-11e5-88c7-3dae91c7edce.png)

**Comment by edmistj** [comment]
Just pushed a changed to make the icons fixed width. I left the other styles as is as they are the standard bootstrap. The icons look much nicer.

**Comment by edmistj** [comment]
I'm thinking we got most of the icon lists. Let me know if you find more in the future.
