### ISSUE TITLE
Enabling Caching on Dynamic Data Block Causes Block Icons to Always Show

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1096]
On McKinley 3.4 (not sure about earlier, this is the first time I've enabled this), setting the Cache Duration to anything other than 0 causes the block option icons to show at the top of a Dynamic Data block:

![cache](https://cloud.githubusercontent.com/assets/1859094/8234786/1d18a158-15ac-11e5-9384-c7235af8db4d.png)

Also, the data in the block doesn't appear after changing the Cache duration until you clear the cache (and the icons are still there after clearing the cache)

**Comment by azturner** [comment]
This occurs when using the Output Cache Duration option which has not yet been fully implemented. Because of that we're actually removing that option for now.  Some of the blocks (HTML, Content Channel blocks, etc. ) implement their own caching which does work.
