### ISSUE TITLE
Question - 

### ISSUE THREAD

**Issue by bacsrlette** [SparkDevNetwork/Rock#1097]
Does the Rock use any SQL Server 2012 or 2014 specific features?

We are needing to change our RockRMS database compatibility setting to SQL Server 2008 (100)! and need to confirm. Thanks!

**Comment by edmistj** [comment]
Timely question. We're about to put a blog post out on this topic. Rock v3 does support SQL Server 2008, but v4.0 will require SQL Server 2012+
