### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by reed130** [SparkDevNetwork/Rock#1100]
I get this error during installation and I have confirmed I have the latest version of dot net framework installed. Am I missing something?

"The server does not have the correct .Net runtime. You have .Net version 4.4.0.30319.0 Rock requires version 4.5.1."

**Comment by edmistj** [comment]
I would recommend that you post this as a question in the Community Troubleshooting section of our Ask page (http://www.rockrms.com/Rock/Ask). You'll get a faster response there. This issue list is more for known bugs in the code.

Sorry for the confusion.
