### ISSUE TITLE
Inactive Families Still Display In Data Views

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1103]
When marking a family as inactive, they still show up in an active family report.  Searching in SQL shows that even if every member of the family and the family itself are marked inactive, the IsActive value for that family under the Group table is still 1.

Refer to http://www.rockrms.com/Rock/Ask/Using/Questions/668 as the original issue.

**Comment by arranf** [comment]
Confirmed as of 1.6.0 (in develop)
