### ISSUE TITLE
3 Column Page Layout problem

### ISSUE THREAD

**Issue by dcagnetta** [SparkDevNetwork/Rock#1104]
The three column layout does not show the header and footer

I tried it on the demo as well

**Comment by nairdo** [comment]
Do you have a sample page showing this? I'm not able to reproduce the issue.  Here's an example 3 col layout on the internal demo site: http://rock.rocksolidchurchdemo.com/page/5316

**Comment by dcagnetta** [comment]
Hi Nick
It only does that on the external site
I changed the layout of this page
http://rock.rocksolidchurchdemo.com/page/211
 
| Thank you very much!
 |
| 
  | DILLAN CAGNETTA Pastor, Christ Embassy 
... giving your life a meaning
  |

**Comment by nairdo** [comment]
Thanks Dillan.  The External Sites's Three Column layout has no blocks by default (except the one I just added on the demo site to test): http://rock.rocksolidchurchdemo.com/page/226?layoutId=24

If you add blocks to it, they will show up appropriately.
