### ISSUE TITLE
ENTER on search field on https://www.rockrms.com/Rock/Ask/Using, IE11, does nothing

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1105]
The search field on the General Use form ask page, in IE11, does nothing when I type a search term and press Enter.
This does not happening on Chrome on my phone.

**Comment by edmistj** [comment]
@ElimAdmin This is working for me. Can you confirm that it's working on your end?

**Comment by ElimAdmin** [comment]
@edmistj I confirm this does work OK on my home PC.  I logged this issue on an office PC.  I'll check it there on Monday.

**Comment by ElimAdmin** [comment]
@edmistj  Resolved thanks. Closing.
