### ISSUE TITLE
Interactive map and map on External Small Groups page not showing for international (NZ) site

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1106]
I am in New Zealand.
Our address format is
![maploc7](https://cloud.githubusercontent.com/assets/4658177/8278567/baa72d28-1920-11e5-9719-8aaf34afe056.JPG)

I have a group leader with an address that looks like this:  
![maploc2](https://cloud.githubusercontent.com/assets/4658177/8278580/d19cde9c-1920-11e5-87c0-266450ad4125.JPG)

The map picker on the Person Profile page will correctly link to a googlle map that shows the address.
![maploc8](https://cloud.githubusercontent.com/assets/4658177/8278977/263f600c-1924-11e5-868a-156e8a639c70.JPG)

But if this address is used as a group's location (either as the Group address, or from a person's location) - it will not display in the Group's header.  And the External page that lists Small Groups will not find the address and will not correctly show the Small Groups map for the right area.
![maploc6](https://cloud.githubusercontent.com/assets/4658177/8278693/aeb81df0-1921-11e5-96d1-ae1f28e855f1.JPG)

In the demo web site, I set up a group (Section B, aaMap Locator Test), set Support International Addresses to Yes, added one member with a new zealand address (Temp Orary), and added him to the group.  I set the group location to his address.  The same thing happens: no map will display.  
![maploc5](https://cloud.githubusercontent.com/assets/4658177/8278596/e6d05af0-1920-11e5-95a2-dbc3d118961b.JPG)

If a person with a US map is added to the group, the group's map will show for that person's address.  And in the Group maintenance page, the map in the group header will show this person's address.
![maploc4](https://cloud.githubusercontent.com/assets/4658177/8278590/e0bc4a70-1920-11e5-898e-ce65d7e61748.JPG)

Are international addresses being passed to the map display in the right format?

**Comment by treyhendon** [comment]
Hey @ElimAdmin ,

I was about to turn in a similar (but slightly different bug) and wondered if we have the same issue.  Could you test something to see if we're seeing the same thing?

First, I'm using Bing as our Location Service, so incoming address are not be standardized before searching the DB.

I'm finding that when searching for addresses, it is case sensitive (and +4 dependent if that's in the DB -- or not).  Can you look in your SQL DB and see exactly how it has the address saved (on the Location table), then see if that is exactly how it's entered on the person or group?

Additionally, the Map Picker from the person page will "always" work even if it's not geocoded.  (I learned this one the hard way too.)  The reason it will work is that it's passing the address to Google Maps and Google Maps is instantly geocoding and placing the pin.  In my experience Google Maps will ignore the lat/long in the query string and just do the address lookup.

Thanks,
Trey

**Comment by edmistj** [comment]
@ElimAdmin Is this still an issue?

**Comment by ElimAdmin** [comment]
@edmistj I'll check...

**Comment by ElimAdmin** [comment]
@edmistj   I still have groups that have locations set that do not have location maps showing up in the group viewer.  I'll see if I can work out the conditions for when they do or don't. Will check the external page later today.

**Comment by ElimAdmin** [comment]
I have 2 issues with maps:

1. GROUPS LOCATION NOT DISPLAYING MAP on Group Detail Header page.
A group with a location of type 'Other' Barbs shows the location map in the Group Header, where Barbs is a named Location of type Building.
Changing the Group's location to Member Location for the leader member drops the map.
Going back to Other Location, Location, Address (with the leaders address entered) does not show the map.
Going back to Other Location, Location, Location, 'Barbs' re-displays the map.
Barbs is a Location with Location Type 'Building'
Roach Family Home is Location with type Address.


2. THE MAP LOCATOR SEARCHES BASED ON SAVED LOCATION NAME, NOT ACTUAL ADDRESS
Clicking the map icon next to my personal address ....
![admap1](https://cloud.githubusercontent.com/assets/4658177/9991469/6120f06e-60be-11e5-9f09-316da69de324.jpg)

....searches based on location name (The 'Roach Family Home' is a named location of building type.)
![addmap2](https://cloud.githubusercontent.com/assets/4658177/9991483/8310f1ec-60be-11e5-8f03-e4358142f767.jpg)

Clicking on the map icon for someone who does not have a named location,...
![addmap3](https://cloud.githubusercontent.com/assets/4658177/9991496/92642952-60be-11e5-9bcb-dd627837b196.jpg)

 correctly searches based on the address (and displays the location correctly).
![addmap4](https://cloud.githubusercontent.com/assets/4658177/9991504/a10a3302-60be-11e5-8b9b-1f2df6797830.jpg)

It seems that if an address is also saved as a location the map search URL is being set from the location name, not the actual address.

**Comment by arranf** [comment]
@ElimAdmin Is this still an issue?
