### ISSUE TITLE
External Site Images not working Gmail

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#1107]
It looks like having the space in the folder name "External Site" is causing problems with images going to Gmail.  Google is replacing the space with a "+" not "%20".  Can those folders be renamed to not include a space or have an underscore by default installer?  (Also, I have two External Site and two Internal Site folders.)

**Comment by mikepetersonccv** [comment]
@treyhendon It looks like the v1.3.1 installer now creates these folders without a space, but the old v1.1 installer had them with the space.  Is that why you have two of them?

**Comment by treyhendon** [comment]
Hey @mikepetersonccv that's it!  I didn't notice the difference, sorry.  Good to know about the new folder, I'll make sure and move things over and update accordingly.  Thanks!
