### ISSUE TITLE
Duplicate SMS & Email messages

### ISSUE THREAD

**Issue by dsmallman** [SparkDevNetwork/Rock#1109]
If two people use the same Mobile Number and/or Email Address, multiple messages go out.

Suggest filtering Mobile Numbers and Email address before adding to a mail merge, in order to remove any duplicates prior to sending the message.  That will eliminate and duplicate SMS & Email messages from being sent.

I have been going in to RockRMS and disabling SMS on one person or the other, but it would be easier to filter them out when sending.

Thanks!

**Comment by edmistj** [comment]
It's a bit harder than that since the contents of the email will often times be personalized for each individual using Lava. We customize every email we send with the person's nick name. The same is true for SMS.  Also, bulk emails have an unsubscribe option attached to them that is specific to the individual.

**Comment by dsmallman** [comment]
Thanks for the reply John.
 
The emails I am not concerned about, because it does not cost anything to send emails :-)
 
I made a request a while back to have the capability of creating a Data View based on cell phone numbers.  So, that I could only pull in people that have cell numbers.  If I could get that, then that would solve the problem, as long as could summarize the View to tell it not to give me duplicates....  What are the chances of getting this?  Or, the ability to create views based on an SQL query that we write?
 
Not sure how that would work either, since it would be different names with the same cell number.  Do you have any suggestions?

Regards,
Don Smallman
 
 
Date: Mon, 22 Jun 2015 16:13:16 -0700

**Comment by edmistj** [comment]
You could write SQL and put it in a dynamic data block and then send the communication from there. If you send me what your filters would be (every active person with certain connection status that opted into SMS) I'd be happy to give you the SQL.

**Comment by dsmallman** [comment]
Record Status is 'Active' AND Connection Status is 'Member' or 'Attendee' or 'Visitor' AND In group of group type: Family, with role(s): Adult AND Is Deceased is False AND Mobile Number is NOT NULL and  opted into SMS is true.
 
Something like this.  Just not sure how to eliminate either the husband or wife that are using the same Cell Number.
 
Thanks John!

Regards,
Don Smallman
 
 
Date: Mon, 22 Jun 2015 17:21:37 -0700

**Comment by dsmallman** [comment]
Also, I would need to create a new page to house the Dynamic Data Block correct?  Or is there a way to limit the number of records in the block so it does not take up and entire page?

Regards,
Don Smallman
 
 
From: d5mallman@outlook.com
To: reply@reply.github.com
Subject: RE: [Rock] Duplicate SMS & Email messages (#1109)
Date: Mon, 22 Jun 2015 18:11:56 -0700




Record Status is 'Active' AND Connection Status is 'Member' or 'Attendee' or 'Visitor' AND In group of group type: Family, with role(s): Adult AND Is Deceased is False AND Mobile Number is NOT NULL and  opted into SMS is true.
 
Something like this.  Just not sure how to eliminate either the husband or wife that are using the same Cell Number.
 
Thanks John!

Regards,
Don Smallman
 

 
Date: Mon, 22 Jun 2015 17:21:37 -0700

**Comment by edmistj** [comment]
Intended behavior.
