### ISSUE TITLE
Unable to Delete a user account in the UserLoginList block

### ISSUE THREAD

**Issue by FrankGrand** [SparkDevNetwork/Rock#1111]
With the code out of develop, I'm not able to delete user accounts.  Clicking the red X pops up a confirmation window, but the account never gets deleted.

**Comment by tcavaletto** [comment]
@FrankGrand  I tried to replicate your problem, but seem to be unable to. What browser / Rock version are you using, and is it still happening today?

**Comment by FrankGrand** [comment]
@tcavaletto I'm using Chrome with develop branch code (last pulled Wednesday or Thursday last week).  Yes, it's still happening.  From a user's profile page, I'm clicking on the security tab, and under the user accounts list I'm clicking the red X by a username.  It doesn't seem to do anything.

**Comment by azturner** [comment]
@FrankGrand I couldn't reproduce this either, so I took a look at your system and noticed that you have a pre-delete workflow trigger configured for user logins, and an exception was occurring on every delete of a user login when trying to launch the workflow.

I pushed a [fix for the exception](https://github.com/SparkDevNetwork/Rock/commit/1da998fd9bda5403c4178331a2bcfd905bba5d67) this morning that should resolve the issue.

**Comment by edmistj** [comment]
I'm assuming this is now working. If not please re-open.
