### ISSUE TITLE
CheckInBySpecialNeeds check-in filter missing attribute

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1125]
@nairdo The FilterBySpecialNeeds action requires a Group to have a boolean attribute IsSpecialNeeds:
https://github.com/NewSpring/Rock/blob/develop/Rock/Workflow/Action/CheckIn/FilterGroupsBySpecialNeeds.cs#L73

However, the CheckInBySpecialNeeds filter (grouptype) that ships with core doesn't include that Group attribute.  Is that an oversight or are we supposed to add that manually?

![image](https://cloud.githubusercontent.com/assets/1210933/8438807/2eb7eb74-1f36-11e5-83dd-083035d6c921.png)

**Comment by azturner** [comment]
It's an oversight. We'll get it added in an upcoming migration.

**Comment by dcs619** [comment]
@azturner I just built a new database for testing and that check-in filter doesn't exist....I could've sworn @nairdo or myself added it to core months ago.
