### ISSUE TITLE
Removing Blocks From Page Zones Mode

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#1133]
Hey Guys!

Found this one today while working on some styling. If I go into the page zone mode and remove a block from a zone, the block is not removed visually until a new block is added to the zone. However, removing blocks from the block config mode works fine.

I've recorded a video that shows the behavior. Let me know if you have more questions!

Thanks!

https://www.dropbox.com/s/0mr3imh562oqbuq/blocks-removal-from-sections-issue.mov?dl=0

**Comment by azturner** [comment]
This was fixed in develop branch here: https://github.com/SparkDevNetwork/Rock/commit/9a3f853535727d19f3e6102ef89825dc62a7bab4
