### ISSUE TITLE
Enhancement: Include Filters in Group Detail Lava 

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1134]

**Comment by edmistj** [comment]
@arranf Do you have more details on this?

**Comment by arranf** [comment]
@jedminston Sure. This originally was not something I was planning on
implementing (it was before we were tagging potential enhancements we were
working on ourselves).
The enhancement I'm thinking of would allow people to filter the group
detail lava query in the same way as the group detail block allows -- I
imagine this would be use of churches who want to provide access to leaders
to manage their groups via an external block.

This may be best off as a black book suggestion.
