### ISSUE TITLE
Clearances don't update if PMM sends a revision

### ISSUE THREAD

**Issue by kcirgjd** [SparkDevNetwork/Rock#1143]
With some of PA's crazy laws we have several extra searches we are required to do. PMM is running them for us and adding links to the extra forms we need to have on file but sometimes sends one or two reports before they are all back. When that happens if they try sending a revised report it does not update in Rock. 

They are being great and just e-mailing me the revised copies but I wanted to report the issue.

**Comment by arranf** [comment]
@kcirgjd Is this still an issue for you?

**Comment by kcirgjd** [comment]
No. My memory isn't working well but I think I re-did our workflow to download a new copy of the report when we pass someone.

**Comment by nairdo** [comment]
Also, is the ProtectMyMinistry.ashx webhook specified in the Return URL of your background check provider's configuration (found under System Settings > Backgound Check Providers > [YOUR BC PROVIDER]) correct and publicly accessible?

![image](https://cloud.githubusercontent.com/assets/383807/17614121/7f8516e8-6018-11e6-8b03-a0255cddf9e7.png)

**Comment by cabal95** [comment]
I'm not sure this is still an issue. From what I understand between the original issue and the duplicate issue, the problem was that if you do two background checks for a person, the workflow would not update the person attributes on the second later run. In our experience it does. I would tend to think if nobody else has run into this it was a fluke or a configuration error.

I've never heard of PMM sending more than one response for a background check.

**Comment by kcirgjd** [comment]
In PA we have to have people complete multiple background checks but if they don't finish everything within 7 days PMM closes the account and send back what they have. Then when the rest is finished they send an update. 

The flow is:
1. Submit a background check in Rock
2. Rock sends to PMM
3. PMM sends us an e-mail/confirmation code to send to the person getting checked
4. The person getting checked completes a second application (If not completed in 7 days they fail until completed and PMM continues to step 5. 
5. PMM send the report back to us. 

Because PA is goofy and we have to hunt people down for that Compass check and PA waived all clearance fees through the state system for volunteers we have stopped using PMM and just submit the two applications manually our-self again.  It's the same work but keeps us from getting PMM fees.

**Comment by cabal95** [comment]
Hmm. I'm not sure how to fix that, but that clarifies what is going on. The core issue then is that the Workflow has received a response from PMM (even though it's incomplete) and has processed everything. The workflow is then no longer looking for a response from PMM so it never notices that PMM sent a second response.

**Comment by kcirgjd** [comment]
Exactly. So for us the solution was to have the workflow download the file from PMM a second time when we passed someone. So the people who had not gotten their PA check back yet would just sit waiting for a review. I would open each individually, e-mail them another reminder, and then let them sit until the next week.

**Comment by jonedmiston** [comment]
@kcirgjd is this still an issue or should we close?

**Comment by TheArkChurch** [comment]
Closing this issue due to age or no response. Also of note there is a newer PMM 2.0 integration that more than likely addresses this issue.
