### ISSUE TITLE
Recurring giving schedules out of date

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1145]
On both internal and external pages, giving schedules aren't updated until you refresh it (internal page) or click edit (external page).  This is causing confusion for our givers.  Is this a bug, or does some kind of job need to be created that updates this on a regular basis?

![2015-07-10 15_33_41-my schedules _ my newpointe](https://cloud.githubusercontent.com/assets/1859094/8627431/0c109bbc-2719-11e5-9dfd-7ac839ef22d1.png)

This happens on rockrms.com too on the donation schedules.

**Comment by matthewmeekins** [comment]
We've experienced this as well.

**Comment by edmistj** [comment]
@bwitting Can you provide more steps to reproduce this. I'm not following.

**Comment by edmistj** [comment]
@bwitting Nevermind we're now able to reproduce.
