### ISSUE TITLE
Editing Workflow Types is very slow

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1146]
When editing workflow types, editing activities or attributes can be very slow.  Editing an attribute can take up to 45 seconds for the modal to appear, and adding a new action usually takes just as long.    (It's not a capacity issue, and everything else is very snappy).  What other info can I give to help troubleshoot this?

**Comment by ElimAdmin** [comment]
I know you are working on this, and that there are plans to improve the efficiency of workflow editing.  Just adding my agreement that this is important.  Creating and debugging even a fairly simple workflow with adding and changing attributes has taken a long time.  Workflow is flipping awesome.  We can see how powerful it is! But the time taken to edit and maintain the workflows is a detractor.  My (+1) vote for any efforts to improve responsiveness.

**Comment by arranf** [comment]
This happened in v5.
