### ISSUE TITLE
Boolean Inconsistency

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1155]
In Lava if a boolean is true it's value is 'Yes' or 'No'.
In Rock boolean fields are either 'True' or 'False'.

**Comment by dcs619** [comment]
You can set the default text value of an Attribute when you create it.

If you're developing in Rock, the .AsBoolean() method is the best way to
check boolean attribute values.

David Stevens

*Web Developer*NewSpring Church
www.newspring.cc

**Comment by arranf** [comment]
You're completely right, I completely forgot that you can customise the default text value of an Attribute.
I'll close this.

**Comment by arranf** [comment]
Thinking about it it might still make sense to have the boolean fieldtype default to True and False rather than Yes or No so that it's consistent.

Thoughts?

**Comment by dcs619** [comment]
@arranf is this fixed with the PR for #1179?

**Comment by arranf** [comment]
@dcs619, this issue is more related to consistency of boolean language i.e. using true/false in one area and yes/no in another. 

#1179 seems to refer to be an additional feature rather than touching the boolean field type unless there's something I'm missing.

**Comment by arranf** [comment]
At this point this would be a breaking change. Closing.
