### ISSUE TITLE
Date Range Starts The Week on Monday

### ISSUE THREAD

**Issue by edolyne** [SparkDevNetwork/Rock#1156]
![](https://s3.amazonaws.com/uploads.hipchat.com/21097/778089/crsIDGTRfINT9xq/upload.png)

Steps to Reproduce
---
Open a block with a date range selector
Select Current Week
Date range that appears above the select starts on Monday

Buggy Behavior
---
Date range starts on Monday and ends on Sunday

Expected Behavior
---
Date range starts on Sunday and ends on Saturday

**Comment by bwitting** [comment]
I disagree that this is a bug.   ISO 2105 and 8601 (https://en.wikipedia.org/wiki/ISO_8601) both state that weeks start on Monday. 

Plus, in the use-case of Rock in churches, I would think we want to follow the standard and have the entire weekend grouped together - you want Saturday services and Sunday services (the next day) to be in the same week number.

**Comment by edolyne** [comment]
@bwitting As this may not be viewed as a bug, could an option be added to core where you are able to choose what day to start your week within the system settings?

**Comment by edmistj** [comment]
This would be a difficult feature to add. Basic on the limited benefit I'm going to mark this closed. If it keeps coming up we may decide to re-visit it.
