### ISSUE TITLE
Problems with Inactive:Deceased Status and Known Relationships / New Households

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1164]
We had some trouble with the statement generator printing the names of deceased spouses on some statements - then we realized we didn't follow the directions (http://www.rockrms.com/Rock/BookContent/5/46#recommendationsforlifeevents) and left deceased individuals in households.

However, you can't really follow the directions as written.  Once you mark a person as Inactive:Deceased, you can't move them to a new household (you just have to do that first).  

You can't make a Known Relationship with a person set to Inactive:Deceased to link them back to the household.   If you make the relationship before setting the person to inactive, the relationship stops showing up after the person has been marked inactive.  (This is the most important one - we needed to move individuals out of households so they didn't show up on statements, but we don't have any relationships linking them back to the original family now)

**Comment by tcavaletto** [comment]
The problem is fixed now. You can now remove a deceased member from the household into a new one as well as add new Known Relationships, and they'll show up on the KnownRelationship block.
