### ISSUE TITLE
Calculate Metrics Job Doesn't Work when using the Rock Jobs Scheduler Service

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1168]
In 3.4 when setting RunJobsInIISContext to false in web.config and using the Windows Job Scheduler Service instead, the Calculate Metrics Job shows "Error Loading Job" as a status and won't run - the error is: ```Error loading the job: Calculate Metrics. Ensure that the correct version of the job's assembly (.dll) in the websites App_Code directory. Job class cannot be null.```

**Comment by mikepetersonccv** [comment]
fixed with new build and installer in v1.4
