### ISSUE TITLE
Virtual directories not supported in Rock

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1181]
We have over 200k documents and profile images that should be accessible to Rock, but we don't want to store them on our IIS servers.  (We have multiple IIS servers set up behind a load balancer)

After creating a virtual directory in IIS, Rock doesn't recognize the virtual directory and instead creates a folder by that name at the root of the IIS server it's currently connected to.

Seems to be an issue [here](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Storage/Provider/FileSystem.cs#L48) where the StorageProvider isn't checking to see if the path is virtual.

**Comment by dcs619** [comment]
Putting this here for reference
 
HostingEnvironment.MapPath:
https://msdn.microsoft.com/en-us/library/system.web.hosting.hostingenvironment.mappath(v=vs.110).aspx

Server.MapPath:
https://msdn.microsoft.com/en-us/library/ms524632(v=VS.90).aspx

Maybe instead of doing a [manual combine](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Storage/Provider/FileSystem.cs#L131) we should use one of those methods.

**Comment by dcs619** [comment]
Looks like GetFile has to be updated as well; requesting a file stored on the virtual directory results in this error:

![image](https://cloud.githubusercontent.com/assets/1210933/9090906/26052d9c-3b6b-11e5-8bbf-87945fc6feb5.png)

**Comment by mikepetersonccv** [comment]
@dcs619 Let me know if this takes care of it :)

**Comment by dcs619** [comment]
Confirmed this works (sorry for the late response :)

**Comment by mikepetersonccv** [comment]
@dcs619 Awesome, I can finally sleep at night ;)
