### ISSUE TITLE
Rock Conference Registration Wizard issue

### ISSUE THREAD

**Issue by swedd** [SparkDevNetwork/Rock#1182]
BROWSER: Firefox v39.0
OS: Win7

I was registering for two people for the Rock Conference in October. I entered my data on the 'First Person' page and clicked next. Then I entered the other person's data on the 'Second Person' page and clicked next. I was then taken back to the 'How many people are you registering?' page.

Selecting '2' again repeated the steps above. The data I had entered was persisted on these pages. But, I was not able to 'Next' past the second registrant's data entry page.

I switched to Chrome and was able to register without issue. So, the problem seems to be with Firefox.

**Comment by azturner** [comment]
Fixed with this commit: https://github.com/SparkDevNetwork/Rock/commit/c61cd29e37e4797dac635b14ce42314eb54b60cf
