### ISSUE TITLE
Person history shows all group meetings, but not when the person attended

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1184]
This might be a enhancement request.

In the person history there is no way to see if a person did or did not attend a group meeting.  The dates of each meeting, for which attendance records are entered in group attendance, are listed.  But this implies that the person attended on that date.  If a person is not checked as having attended, the group meeting still shows in their history.  I want to be able to use this screen to review a person's attendance at particular meetings, especially leadership meetings.  This is an important input to their performance reviews.  I would still like to see each meeting listed in their history, but would also like to see if they did or did not attend.

John did not attend on the 22/07.
![att1](https://cloud.githubusercontent.com/assets/4658177/9149168/8f0cb33c-3df0-11e5-84c2-8813f1624909.jpg)

But the meeting shows in history with no indication of attendance or absence.
![att2](https://cloud.githubusercontent.com/assets/4658177/9149169/964e9700-3df0-11e5-91fe-5675be2c40f2.jpg)

(Related to this: it would be good if the filter on history could filter on 'not attended'.)

**Comment by edmistj** [comment]
Nice catch. Todos:

+ Add a 'Did Attend' column
+ Add a filter as noted in request

**Comment by arranf** [comment]
#claimed
