### ISSUE TITLE
Location of Edit Individual/Family Buttons

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#1185]
Currently on the person detail page, the "Edit Individual" and "Edit Family" buttons are in different sections, and at mobile breakpoints, there is some inconsistency on where those buttons show up depending on the amount of data stored for the individual. I wanted to suggest potentially moving both individual and family editing buttons into the "actions" dropdown menu for a little more consistency.

**Comment by edmistj** [comment]
@briankalwat We're still considering this. The difficulty is that a person could have multiple edit family buttons if they are in more than one family.

**Comment by arranf** [comment]
I think this is dealt with in v6
