### ISSUE TITLE
Time Picker behavior not consistent with Date Picker

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1189]
When using the DatePicker I have to click inside the input for the JS to fire a calendar popup.

When using the TimePicker I have to click the icon (not the input) for the JS to fire a popup.

This gets really confusing when using the DateTimePicker:

![screenshot 2015-08-12 12 28 51](https://cloud.githubusercontent.com/assets/1210933/9229965/bdc15570-40ed-11e5-8d42-c97f36d0111f.png)

Ideally clicking the input OR the icon would pop up the control.

**Comment by edmistj** [comment]
Agreed. These are two different controls from two different open-source projects. It's on the list of things to fix, but we don't have an ETA.

**Comment by edmistj** [comment]
Looking into this more the date picker actually supported this open but we didn't enable it. 

Modified date picker to work more like the time picker. You can now click on the calendar icon and it will open. Also added logic that if you click the calendar icon it will select the text of the date which allows you to start typing right away to change the date. This should now be consistent with the time picker. Changing the time picker to open when you click into the input field would actually be confusing as you probably want to simply type into this field.

**Comment by arranf** [comment]
Thanks! This has caused a **lot** of confusion with staff on our end!
