### ISSUE TITLE
[EN] Optionally disable Results output for Data Views and Reports

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#1191]
Working with complex Data Views and Reports can be cumbersome because each time they are viewed or saved the Results are generated automatically, resulting in lengthy pauses when selecting, updating, etc.

The purpose of this change is to add a toggle to enable/disable automatic execution, for those situations where you want to browse/update these items quickly.
The toggle will be stored as a per-user/block setting, and will be presented in the same way as the Attendance Analysis "Show/Hide Data" button.

@azturner OK to start work on this?

**Comment by azturner** [comment]
@MrUpsideDown Yes!

**Comment by MrUpsideDown** [comment]
Closed via #1198
