### ISSUE TITLE
Rock Donation page adding US prefix to non-US phone number

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1195]
If you are interested in recording correct phone numbers on the Rock donation page...

I'm trying to make a donation.  :)  https://www.rockrms.com/page/485
I notice that my phone number has a 1 added to the front of the number.  This is incorrect if the country is not US.  The phone number should be +64272778800 not +1 64... Country was set to New Zealand.  Might this also be happening for other non-US countries?

![donatephone](https://cloud.githubusercontent.com/assets/4658177/9291913/906f7530-442f-11e5-92de-8cf55670ee16.jpg)

I also noticed that on https://www.rockrms.com/page/575 the Create New Gift button does nothing.  But this may be because I have no prior gifts.

**Comment by azturner** [comment]
Configured block not to prompt for phone and updated pages/settings to allow adding and editing profiles from the scheduled transaction list (page 575).

@ElimAdmin, you should be good to go :).
