### ISSUE TITLE
Manually editing Worker on workflow does not give worker access

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1196]
This is probably an enhancement.
Clicking the Edit button on a workflow row on page/288 (the one that lists the workflows), then clicking Edit to manually change a workflow setting, and changing the Worker correctly changes and saves the Worker.

But then that Worker cannot open the workflow - only the person who was previously assigned can.  I expected that it would reassign the workflow to the new worker.  The newly assigned worker is listed as the worker on the list of workflows.

This relates to my earlier suggestion that entering a value for Reassign worker on this page would also reassign the workflow.  (But I have subsequently found how to re-run the assign workflow action, so you can probably ignore that suggestion.)

**Comment by edmistj** [comment]
Not sure this is fixable. The 'Worker' is a person attribute. It requires actions to run to set the value of this attribute to the assigned person for the activity. 

You can though manually change who is assigned to the activity from the same set of screens under the 'Activities' tab.

![screenshot](https://cloud.githubusercontent.com/assets/548178/9608771/dda8f7ca-5084-11e5-969c-a935e4b66419.png)
.

**Comment by ElimAdmin** [comment]
@edmistj  Thanks Jon. That's fine.
