### ISSUE TITLE
[EN] Add Copy Workflow Action method

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1197]
Following the pattern @MrUpsideDown used with #1192, add a "Copy Workflow Action" and "Copy Workflow Activity" method so ministries can more easily create complex workflows.

For example, the following "[XYZ] Details" are the same action but applied to different areas of the form:
![screenshot 2015-08-17 11 38 30](https://cloud.githubusercontent.com/assets/1210933/9308888/82131f8c-44d4-11e5-9888-f7eecde05a1a.png)

**Comment by ElimAdmin** [comment]
Ah!  We're thinking alike.  In an 'idea' I submitted today I suggested that the copy function also allow the Activity or Action to be copied across to another workflow, not just within the same workflow.

**Comment by dcs619** [comment]
@ElimAdmin Yea, this would just be copying within the same workflow.   There's probably a way to do what you're asking, but copying an entire workflow and adjusting the actions works well for us so far.

**Comment by ElimAdmin** [comment]
@dcs619 Yes, agreed. Copying across workflows probably not warranted.

**Comment by ElimAdmin** [comment]
@dcs619 Would be helpful if this could also include copying attributes.

**Comment by dcs619** [comment]
With the workflow ViewState being minimized, it's no longer a pain point to add new actions.  Also most workflows can be simplified to re-run actions with a different parameter.
