### ISSUE TITLE
[EN] Add Report Field "Group/Related Group Members"

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#1201]
This field returns the name of one or more people that hold a specified Group Role in a Group that is in some way related to the target Group.

The relationship to the target Group can be Parent or Child, with the option to set the number of levels of the tree to navigate during the search.

The immediate purpose of this field is to show the person(s) responsible for overseeing a Group where those overseers are defined as members of a parent Group in the reporting structure.

@azturner ok to proceed?

**Comment by MrUpsideDown** [comment]
Calculation of this field is too complex/expensive to perform during the initial querying of the database. I think the best approach here is to calculate this field after the initial data retrieval. I'm proposing adding a callback method such as DataSelectComponent.OnQueryResultRetrieved(List<object> dataRows) that allows individual DataSelectComponents to post-process the result set after the data retrieval is complete.

@azturner @mikepetersonccv I see you have both worked in this area - does this seem like a reasonable solution or is there a better way?

**Comment by mikepetersonccv** [comment]
@MrUpsideDown You might consider using the Rock.Grid.CallbackField for this type of thing.  Here is example of a using it in a DataSelect:

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Reporting/DataSelect/Person/ChildNamesSelect.cs#L99

**Comment by MrUpsideDown** [comment]
@mikepetersonccv Thanks Mike. I did see that implementation, and I was wondering if there was a reason to prefer it? If possible, I would like to try and avoid tying the creation of base report data to a UI component (where the formatting is not UI-related), because it would be good to be able to re-use the report data creation code in non-UI areas like data export and retrieval of report output via REST services. Your thoughts?

**Comment by mikepetersonccv** [comment]
@MrUpsideDown Yep, CallbackField is more of a UI formatting thing is isn't handy for what you are proposing :).  So, as far as DataSelectComponent.OnQueryResultRetrieved(List dataRows), that sounds like a nice thing to add. Go ahead and give it a try. I bet it will come in handy for other things that need to process the List after the data is fetched. However, I'm not sure what you'll run into when you try to make it work with the Grid.SetLinqDataSource

**Comment by MrUpsideDown** [comment]
@mikepetersonccv Just had a look at SetLinqDataSource, and yes, it does complicate things considerably. My (rather drastic!) solution to this would be to refactor the Grid so that it only makes use of a (new) IGridDataSource component to retrieve its data. IGridDataSource would indicate if the source supported pagination, ordering, requerying, etc. and the implementation used in this case would execute post-processing for the requested page of data before passing the data back to the Grid for presentation. This would also make functions like Grid.DataSourceAsDataTable / Grid.DataSourceAsList unnecessary, because the implementation details could be confined to the data source component supplied to the Grid as an IGridDataSource. Too ambitious perhaps?

**Comment by mikepetersonccv** [comment]
Yep, sounds too ambitious :)  @azturner, thoughts?

**Comment by azturner** [comment]
Yeah, this sounds like more that we'd be comfortable pulling in this late in the 4.0 cycle. we're rapidly trying to get things wrapped up and trying to minimize any architectural changes. If you add a new data view filter or report field, we can merge those in, but this sounds like much more than that.

**Comment by cabal95** [comment]
I think the best way to do this now would be with Lava since you can do full entity commands and sql queries.
