### ISSUE TITLE
Workflow Lava compare of two integers fails, and conditional logic compare fails

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1205]
@edmistj  Hi Jon.  Does #1203 also solve this issue?  Note the impact on an action's conditional logic check.

Two integer type workflow variables: 
1. GivingNumberNew (entered in form, defined as an integer), 
2. GivingNumberCounter (set from SQL read from an integer Global Variable).

This Lava:
New Giving Number: {{ Workflow.GivingNumberNew }}
Giving Number Counter: {{ Workflow.GivingNumberCounter }}
{% if Workflow.GivingNumberNew > Workflow.GivingNumberCounter %}
  Workflow.GivingNumberNew > Workflow.GivingNumberCounter is TRUE 
{% else %}
  Workflow.GivingNumberNew > Workflow.GivingNumberCounter is FALSE
{% endif %}

Gives this result:
![greater3](https://cloud.githubusercontent.com/assets/4658177/9397181/48ea76f2-47ee-11e5-8796-ad1b73239774.jpg)

This causes the following action's conditional logic check to fail:
![greater2](https://cloud.githubusercontent.com/assets/4658177/9397037/07c417ec-47ed-11e5-9753-0e84337ecf09.jpg)

This action should have updated the GivingNumberCounter, but because the comparison fails, it doesn't.

**Comment by edmistj** [comment]
@ElimAdmin This is a similar, but different issue. We see this problem. @azturner is on the fix.
