### ISSUE TITLE
[EN] Add All Pages Option When Adding Blocks To Zone

### ISSUE THREAD

**Issue by edolyne** [SparkDevNetwork/Rock#1211]
### Current Behavior

When adding blocks to a Rock Zone there is currently an option to add the block to current page that I am on, or all pages using the current layout.
### Proposed Behavior

When adding blocks to a Rock Zone there is an option to add the block to the current page, pages using the current layout, or all pages where the current zone exists.

![screenshot 2015-08-23 12 44 29](https://cloud.githubusercontent.com/assets/3417857/9429743/c294ed40-49a9-11e5-93b8-a7b0368af2ec.png)

In the above example, a user would be able to specify both the "My Workflows Alerts" and "Login Status" to be displayed on all pages using the current theme that has a Login Zone.

Ideally it would also be nice to be able to move these blocks from one option to another freely.
### Advantages
- Blocks that are used across the site in the same zone are consistent from page to page 
- Settings for a block that is displayed on all pages can be updated in one place, and applied to all instances of the block
- Reduces the opportunity for errors in updating the block on individual layouts
### Additional Example

Site Wide Menu

![screenshot 2015-08-23 16 03 48](https://cloud.githubusercontent.com/assets/3417857/9430002/22d71572-49b2-11e5-84aa-941b66116b1a.png)

Currently the menu is set per layout, however with the updated system this menu can be added using the all pages option, and is then displayed in the zone across all pages using the navigation zone.  This means you set your menu once, and it's consistent across pages and updates.

@edmistj What would your thoughts be about adding this option to core?

**Comment by edmistj** [comment]
@edolyne I like it. David and I will talk about the timing. Worse case it's v5, but we can make it soon after branching v4 so you could pull it in after that.

**Comment by arranf** [comment]
:thumbsup: This would make life infinitely easier.

**Comment by cabal95** [comment]
@edmistj What was the general implementation plan for this, since different layouts can have different zones (e.g. `Sidebar 1` does not exist in all layouts). Also, would this require a new column in the database for Block of something like `SiteId`?

Also making sure this isn't half done in some branch somewhere before I put a "claim it" tag on here.

**Comment by edmistj** [comment]
Your concerns are the reason this hasn't moved forward though I think about it every time I make a new site. Will think about it more and post ideas soon.

**Comment by edmistj** [comment]
Here's our proposed solution. Not on the road map yet, but we're definitely in need of this.
[Blocks on Site.pptx](https://github.com/SparkDevNetwork/Rock/files/926625/Blocks.on.Site.pptx)

**Comment by cabal95** [comment]
This should now be implemented via c95012e7c4aaf6d6e5703ed3edfbd3acb3f2a90d
