### ISSUE TITLE
File field attributes missing in data views

### ISSUE THREAD

**Issue by jezhailwood** [SparkDevNetwork/Rock#1212]
Since updating to 3.3 (I think that's when it happened), I'm no longer able to filter data views by file field attributes. They're not available in the drop-down, and in data views that previously used them I now see 'Person Property'.

**Comment by mikepetersonccv** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/da367053b99c2f2f94c5cbc0d8995355134d34fc
