### ISSUE TITLE
Strange formatting in Exception Count chart (v3.4)

### ISSUE THREAD

**Issue by pufferdude** [SparkDevNetwork/Rock#1215]
I'm seeing this formatting when I view the Exceptions List.

![image](https://cloud.githubusercontent.com/assets/3903408/9529746/a84f653a-4cc1-11e5-8597-b4635d5ee7b6.png)

**Comment by mikepetersonccv** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/634229045576ab20751f060cf3ac0a5f249001a8
