### ISSUE TITLE
[EN] Add Queryable.WhereGradeRange filter to Rock Person

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1217]
@azturner I'd like to add a method WhereGradeRange into develop before the split to 4.0.  It would follow the pattern for [WhereAgeRange](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/Person.cs#L1951)

It's not in our sprint for this week so I'll get to it after hours.

We use this at check-in to search/add people, but we have to either calculate their graduation year (to use the LINQ queryable), or call ToList and filter by grade afterwards.

**Comment by arranf** [comment]
@dsc619, I can tackle this in the next 24 hrs if that makes your life easier.

**Comment by dcs619** [comment]
@arranf that would be awesome!

**Comment by arranf** [comment]
@dcs619 No worries, I know how tight things can get

**Comment by arranf** [comment]
@dcs619 Are you wanting to pass a grade offset or a grade guid?

**Comment by dcs619** [comment]
@arranf I can do either, grade offset would probably be cleaner.

[Here's the code](https://github.com/NewSpring/Rock-Plugins/blob/bb7e1a49b60ebcf632a0556978eed056cd59f4c3/RockWeb/Plugins/cc_newspring/AttendedCheckIn/FamilySelect.ascx.cs#L924) where I would use it.

**Comment by dcs619** [comment]
Thanks @arranf!
