### ISSUE TITLE
TransactionImage file type not being used in UI for check upload

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1218]
@edmistj @mikepetersonccv This seems like a consistency issue to me, but I may not understand it completely.  

When you add a batch and upload a check image for a transaction, the BinaryFileType used is "Default" instead of "TransactionImage".  This would create problems where we've set TransactionImages to go to the file system but Default images can live in the database.

Looking at the Check Scan app, all checks are being uploaded with [the TransactionImage type](https://github.com/SparkDevNetwork/Rock/blob/develop/Applications/Wpf/CheckScannerUtility/CheckScannerUtility/ScanningPage.xaml.cs#L835).

![screenshot 2015-08-31 14 56 38](https://cloud.githubusercontent.com/assets/1210933/9587423/823fd424-4ff0-11e5-8086-b763e9050843.png)

![screenshot 2015-08-31 15 01 33](https://cloud.githubusercontent.com/assets/1210933/9587582/3fd9df66-4ff1-11e5-9e7b-d56e27842f46.png)

**Comment by edmistj** [comment]
@dcs619 Yes, that would be an issue. We'll get it assigned and fixed.

**Comment by mikepetersonccv** [comment]
A migration will go thru and fix up any Transaction Images that have the wrong binaryfiletype
