### ISSUE TITLE
Inactive Funds on Statements

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1223]
When we want to stop a fund from being available for giving online (a capital campaign, for instance - we don't it appearing online after the campaign is complete), we set the fund to inactive.  

However, inactive funds don't appear in statements from the Statement Generator.  So if someone gave to one of those funds during the period of the statements but we have set it to inactive, no gifts appear for those funds and they don't show as part of the total.

For a workaround, we could have an extra boolean option on funds to be available online instead of just using active/inactive status for making that fund appear.  Or, we can we have an option in the statement generator to include inactive funds.

**Comment by dcs619** [comment]
@bwitting We ran into something similar and requested an [IsPublic](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/FinancialAccount.cs#L174) field that will be a part of 4.0 (@azturner?).  

That way your fund can still be active but won't show online as a giving option.

**Comment by jeremyhoff** [comment]
I'd propose the statement generator selected funds to report based on giving for the date range, regardless of whether the fund were active when the statements are generated.

**Comment by azturner** [comment]
Yes, for v4.0 we updated the transaction entry blocks to only consider accounts that have the 'Is Public' option, and are updating the statement generator to include all accounts (including inactive accounts)

**Comment by jeremyhoff** [comment]
Thanks David!
