### ISSUE TITLE
Adding nickname breaks search

### ISSUE THREAD

**Issue by eddyboat** [SparkDevNetwork/Rock#1224]
On version 3.4, whenever we add a nickname to a person's profile, we are no longer able to find the person using the quick search bar. The person's profile is found in the drop-down, but clicking it leads to a "No Person Found" search results.
I've confirmed this behavior also on the rock.rocksolidchurchdemo.com demo instance.

Has anyone experienced this issue?

Thanks
Eddy

**Comment by edmistj** [comment]
I'm not able to reproduce this in develop or the demo site. Can you provide detailed steps to reproduce?

**Comment by coptechteam** [comment]
Sure.
To reproduce, using the rocksolidchurch demo, edit Ted Decker's profile and add a nickname, such as "Elder Ted". Then save this update.
In the quick search bar, you can now try to search for Ted, and this leads to the "No People Found" screen.
It seems to happen when there is a space in between the nicknames.

**Comment by edmistj** [comment]
OK, that makes sense. The search starts from the left in the search (i.e. it's not full-text). In your example I would not put the 'Elder' in the nick name. You could create a custom Title (Admin Tools > General Settings > Defined Types > Titles) of Elder.  

Hope that makes sense.

**Comment by eddyboat** [comment]
That definately makes sense. Our main use case was to get the title also
reflected on the profile page, which setting the title doesn't do.
Is there an easier way of achieving that?

Thanks again.
