### ISSUE TITLE
[EN] Rock Theme Change to distinguish between Live and Test environments

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#1225]
We run both a live and test environment, and it is necessary (critical!) to be able to easily distinguish between the two when the same operator is using both. At present, I am manually changing the navbar background color in the theme.css file each time I publish the test site, but I would like to automate this process (or do something similar that visually distinguishes the site) by using a setting in the web.config instead (because this is much easier to automate in the deployment process).

@edmistj Do you have any suggestions on how this might best be implemented?

**Comment by edmistj** [comment]
We've added a block to each layout that contains styles that render the page differently. There are some options when we get to v5 that could help but for now the additional block might work if your dev database persists. You could script the addition of the blocks if it gets refreshed. We have a script we run on our dev database when we refresh it weekly.

**Comment by MrUpsideDown** [comment]
@edmistj  I'm looking for something a bit simpler that I can implement using only web.config changes, because I  refresh our test database from live fairly regularly. I have an idea that involves replacing the hard-coded references to "theme.css" with a helper method that reads the filename from web.config. I could then just change the web.config value to point to a different file for our test site (ie. "theme_test.css"). Does this sound like a workable solution to you?

**Comment by nairdo** [comment]
It sounds close to what we at CentralAZ.  One of the last steps in our script does is this: it moves theme.css to theme.orig.css and copies our custom theme.css over it (which includes/imports the theme.orig.css and some overrides to change some header colors to bright orange).

This has been working well for us.

**Comment by MrUpsideDown** [comment]
@nairdo Thanks, that approach would definitely solve my problem. I guess the only drawback is that every site needs to implement the same script as part of their deployment. The changes I am suggesting would build this into the core product, which might make it easier for others to deploy this type of setup in a simpler build environment?

**Comment by MrUpsideDown** [comment]
@nairdo Any chance you could share your modified theme.css that imports the original? I'm sure you've done a better job at restyling than I have!

**Comment by nairdo** [comment]
@MrUpsideDown I'm not so sure about that (just wait til you see it - you'll laugh!) but it's getting the job done for now.

```
@import url("theme_orig.css");

#content-wrapper header .navbar-default {
    background-color: orange;
  }

body {	
    border: 3px dashed orange;
}
```

![image](https://cloud.githubusercontent.com/assets/383807/9647519/aecfd982-5192-11e5-9100-755289079878.png)

**Comment by arranf** [comment]
@nairdo You're not going to miss that ;)

**Comment by MrUpsideDown** [comment]
@arranf It's not so much about style as about making sure people don't conduct experiments on our live data! :-)
@nairdo I had recolored the navbar as you have, but I like the idea of the border change because the header isn't always in view once you scroll down the page. So I'll steal that, thanks!

**Comment by edmistj** [comment]
Closing as a solution is provided. I don't think we want to add code for this scenario at this point. That could possibly change in v5 when some of the new CMS tools are ready.
