### ISSUE TITLE
[EN] Statement Generator - Set Minimum Contribution Amount and Sort Order

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1229]
To save time and postage, we don't typically send statements for total contributions less than $100 (If I recall correctly, the IRS minimum is $250)  I'd love to see a minimum amount option added to the statement generator. (We just ran statements and pitched about a ream of paper - it's crazy how many $1 and $2 totals we have...)

Also, I see the default sort order is based on zip code, but according to our local post office at least, statements don't qualify as bulk mail.  To help find a needle in a haystack, our finance department really wants to be able to sort by campus then name (or at least name) in case they need to pull one out of the giant stack for some reason - it would be great if that was an option too.

I submitted these (along with more Statement Generator stuff) to the Black Book - I just thought @mikepetersonccv would want to get more features done for v4! ... :+1:

**Comment by edmistj** [comment]
One of the features we'd like to add is allowing you to filter the list by a data view. Not sure this will make it into v4.0 though.

**Comment by mikepetersonccv** [comment]
done with https://github.com/SparkDevNetwork/Rock/commit/e002e7805cacafd6ae88cbc5e26755caa1eb33fa and https://github.com/SparkDevNetwork/Rock/commit/123d8ecab3eaf0a1ac30001057a5de22fa007708

**Comment by bwitting** [comment]
@mikepetersonccv you are the best!  :+1:
