### ISSUE TITLE
Business Names with Ampersands Don't Appear in Person Picker

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1230]
On McKinley 3.5:  When working with contributions, a Business Name with an & in the name doesn't appear in the the Person Picker.  (We are just changing &s to the word and as a workaround, but we would like to keep actual business names)

**Comment by nairdo** [comment]
I'm pretty sure this is a dup of #1047 which is fixed via 0918e8a, but please reopen if you think otherwise.

**Comment by mikepetersonccv** [comment]
yep, the encodeURIComponent fixed it :)

**Comment by bwitting** [comment]
Sorry guys, that's a dupe. I guess searching for a '&' on GitHub doesn't work correctly either... :)

Thanks!
