### ISSUE TITLE
There is no way to hide/show second 'Id' column in Dynamic Block Hide/Show columns

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1240]
If a query used in a Dynamic Block has multiple fields with the same name (e.g. 'Id') there seems to be no way to hide any columns other than the first one with the name.  

E.g., in the query:

SELECT w.[Id], wt.[Id],w.[WorkflowTypeId], w.[Name], w.[Description], w.[Status],w.[CreatedDateTime], wt.[Name]
FROM [Workflow] w, [WorkflowType] wt
WHERE [WorkFlowTypeId] = 24
AND   w.[WorkflowTypeId]=wt.[Id]
ORDER BY w.[Name]

I only seem to be able to hide the first Id.  
This query doesn't need to list wt.[Id] - so it is not needed and can be removed.
So I'm not really sure if/when this would be an issue.  But I'm noting it in case you can foresee a problem.

**Comment by dcs619** [comment]
@ElimAdmin Curious why you would include a query column that you'd then hide?  I can understand the need for multiple columns in testing, but in production this seems like a non-issue.

**Comment by arranf** [comment]
@ElimAdmin Seems like you could just drop `wt.[Id]` from your SELECT?

**Comment by ElimAdmin** [comment]
Yes, I can, and I did.  That's why I acknowledged, "I'm not really sure if/when this would be an issue. But I'm noting it in case you can foresee a problem."  :) 
@dcs619.  If this is a non-issue and raises no concerns then this can be closed.

**Comment by edmistj** [comment]
Another tip... You should ensure that all your result columns have unique names by providing aliases in your SQL statement. You can then hide based on these aliases.

SELECT 
     w.[Id] AS [WorkflowId], 
     wt.[Id] AS [WorkflowTypeId],
....

**Comment by ElimAdmin** [comment]
Brilliant. That's great.
