### ISSUE TITLE
Lava | Remove can not remove '

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1241]
The lava code | Remove ''' fails.  I can't see any way to remove an ' from a string.

Same applies to other lava functions that are surround by ', e.g. Replace.

There's nothing obvious in the Lava doc that explains how to get around this.

(I've run into problems because my attribute options have 's in the option text.)

**Comment by edmistj** [comment]
You can optionally use double quotes with the filters like so:

{{ "Ted's Car" | Replace:"'", "" }} 

would output

Teds Car

I'll update the Lava pages with these details.

**Comment by ElimAdmin** [comment]
Thanks.
