### ISSUE TITLE
Dynamic Block page slider only shown at bottom of result set 

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1242]
I'm using a dynamic block to report all my workflow details.  The result set goes off the right of the page, and off the bottom of the screen.  There is a window page slider, but it only appears right at the bottom of the result set.  So there is no way to slide to the right to view the details of rows if you can't see the bottom of the result set and the slider.
If I click in a row, the right arrow moves the page over.  This would be great, except that I've got the block set up so that clicking the row links through to a detailed edit page.
Is there any way the page slider can be appear at the bottom of the screen not the bottom of the result set?

(I can work around this by having two pages/dynamic blocks.  One where I reduce the columns in the dynamic block so it fits on one page.  I can use this as the 'link through to the details' block.  The other page I could list everything *without* the row click going to a URL link, and then the right arrow would  allow me to browse to the right to see everything.)

**Comment by edmistj** [comment]
The behavior you see today is from the Bootstrap responsive grid. If you disable the responsiveness you get something like the screenshot below. We could add a setting to enable/disable the responsiveness, but I'm not sure that the result would be too pleasing.

Let me know what you think.

![2015-09-08_08-30-20](https://cloud.githubusercontent.com/assets/548178/9739346/28f5d412-5604-11e5-8c6b-abf7ea644c88.png)

**Comment by ElimAdmin** [comment]
@edmistj  Thanks Ed.  We can work around it okay.
