### ISSUE TITLE
Status not showing for new items for new content channels 

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1244]
The Status field is not showing correctly for new items of new content chanenels.  It does show correctly for existing channels.

Add a new content channel.  E.g. create a new content channel of type 'Website Ads'.
Tick 'Items require approval.'
http://rock.rocksolidchurchdemo.com/page/1309

Add a new item.
http://rock.rocksolidchurchdemo.com/page/1311?contentItemId=0&contentChannelId=1002

The word 'Status' is displayed, but the fields for maintaining the status of the item do not display.
![channel1](https://cloud.githubusercontent.com/assets/4658177/9759147/31111ab2-573f-11e5-968a-706e699bb3d3.JPG)

Any saved items are saved with Pending approval status but there is no way to change the status. 
This happens for any type of new item for new channels.

**Comment by edmistj** [comment]
@ElimAdmin This happens when the current user does not have 'Approve' access to the content channel. Having the 'hanging' label is confusing so I hid it when they don't have 'Approve' access.

**Comment by ElimAdmin** [comment]
@edmistj  Ah!  I get it.  Thanks.
