### ISSUE TITLE
Default Organization Email Template Organization Website Hyperlink

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#1251]
It's a small thing.  I noticed that in the Default Organization Email Footer (both Global Attributes and Communication Template) the hyperlink on the Lava field for {{ GlobalAttribute.OrganizationWebsite }} is actually linking to {{ GlobalAttribute.PublicApplicationRoot }} instead of the OrganizationWebsite.

**Comment by mikepetersonccv** [comment]
fixed
