### ISSUE TITLE
SMS box box NOT ticked for mobile phones

### ISSUE THREAD

**Issue by dsmallman** [SparkDevNetwork/Rock#1252]
Hi,

It seems that the Mobile SMS Box on the Contact Info section of the person profile is not automatically ticked anymore.  Is this by design?  It would be nice if we did not have to go to this screen every time we add a person.  Thanks!

**Comment by edmistj** [comment]
I'm pretty sure the Edit Person block has always been that way. Either way though the current state is the preferred as allowing SMS is something people need to opt-in for by law.

**Comment by arranf** [comment]
There's a block option.

**Comment by edmistj** [comment]
Yes or that... ;)
