### ISSUE TITLE
Credit card expiry date should only list current year and beyond

### ISSUE THREAD

**Issue by jonhorton** [SparkDevNetwork/Rock#1254]
**Steps to Reproduce**
Visit an event registration page and begin registering for an event.
When entering payment details, attempt to set the credit card expiry date

**Buggy Behavior**
It's impossible to pay with a card that has an expiration date before the current year
Screenshot: https://www.dropbox.com/s/nwm56835ovfj7qu/Screenshot%202015-09-23%2017.00.14.png?dl=0

**Expected Behavior**
All credit card expiry dates should start with the current year.

**Comment by azturner** [comment]
@jonhorton, I can't actually reproduce this. Rock sets the minimum year to the current year as long as it gets a valid financial gateway. It also sets the visibility of the first/last name vs full name fields (for name on card) at the same time, and from your screenshot I noticed that neither of these fields are visible either. Leads me to think that somehow you have a registration template with a cost, but no gateway configured, which the UI should not allow. Can you confirm if this is the case, and if so any thoughts on the steps you might have taken to reproduce that?
