### ISSUE TITLE
Blank Emails Still Display

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1258]
When running a Data View on people who have addresses (Email = Not Blank) there are hundreds of blanks that still show up.  I went into SQL to test this and pulled up a test family (Gunning) and 2 have emails and 2 don't.  The two that don't have an email of NULL.  When running the following command, none of the family members show up.

SELECT *
FROM Person
WHERE LastName = 'Gunning'
AND Email = NULL

A similar problem happens on the rock.rocksolidchurchdemo.com site when using the Decker family.

**Comment by dcs619** [comment]
Is it possible that Email defaults to an empty string ('')?

For instance:
SELECT *
FROM Person
WHERE LastName = 'Gunning'
AND (Email = NULL OR Email = '')

**Comment by MrUpsideDown** [comment]
@BelAirIT Is this the same issue as #948?

**Comment by azturner** [comment]
We'll look into this, but FYI, when querying for NULL you need to use "IS" vs. using the equal sign...

    SELECT *
    FROM Person
    WHERE LastName = 'Gunning'
    AND Email IS NULL

**Comment by cabal95** [comment]
@BelAirIT Can you verify if this is still an issue? I was unable to replicate on the demo site.

I setup a DataView on Person to filter for Email Is Not Blank and did not get any person records showing with a blank email. I checked the database (using power tools) to see if there were people with a NULL email (7 found) as well as people with an empty string for email (2 found).

I think switched the filter to Email Is Blank` and got the expected 9 total records.

**Comment by BelAirIT** [comment]
I believe the issue ended up being records imported using Excavator (several years ago) that put blank data into the email cell. Used SQL to resolve it and Rock now displays the data correctly.
