### ISSUE TITLE
Data View filters on Attribute Fields having a default value do not return all matching Entities.

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#1259]
Data View conditions that should return Entities having a specified Attribute Value do not return any records if the search value matches the default value.

Attribute Value records are not created for Entities unless the value for the attribute is different from the default value, so filtering to match the default value returns no records.

For example, applying the condition "equals 'test'" to a Text Attribute field with a default value of 'test' will not return any Entities.

**Comment by MrUpsideDown** [comment]
Initial discussion of this issue can be found here:
http://www.rockrms.com/page/278?question=808

**Comment by arranf** [comment]
This is no longer the case. I can do the following on 6.8 successfully:

* Create a text Person Attribute with a default value of `Arran`
* Go to the person's profile, click on the AttributeValue block, and press save without changing the attribute's value
* The AttributeValue is saved in the database

I'm going to go ahead and close this now.
