### ISSUE TITLE
[EN] Schedule model doesn't support ordering

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1260]
I'm adding service and weekday schedules for our ministries, but there's not an Order column for the Schedule model.

I'd like to order these schedules chronologically, not alphabetically:
![](https://cloud.githubusercontent.com/assets/1210933/10318436/75433988-6c37-11e5-8238-5ce97d300d49.png)

**Comment by cabal95** [comment]
Related to issue #626, ordering of schedules on the Schedule Builder block.

**Comment by nairdo** [comment]
Hello amazing community member! We've recently moved 'feature requests' over to our own "Ideas" system on our Community site over at: http://community.rockrms.com/ideas 

If you'd like to re-propose your idea and put it up to the vote, **please re-submit your idea there**.  Thanks!
