### ISSUE TITLE
Pickers: html element Id collision

### ISSUE THREAD

**Issue by demersus** [SparkDevNetwork/Rock#1261]
We created a custom workflow action that uses a Workflow Type attribute.  Unfortunately, the way the ItemPicker class is coded, we cannot have multiple of these in the same workflow editor.  

I will post a merge request to here. 

 I discovered that the PersonPicker does not inherit from ItemPicker.  It uses this.ClientID for the element & javascript picker call.  However, the WorkflowTypePicker does inherit from ItemPicker.  

The ItemPIcker code makes the html element use the ID of the c# class instead of ClientID.  This was causing issues because the jquery ui widget would only initialize on one of the picker elements.  (all html elements had the same html id attribute).

Anyway,  you'll see what I mean from my merge request.

**Comment by azturner** [comment]
Fixed with this commit: https://github.com/RealLifeMinistries/Rock/commit/ab79ca88ab56a5804b4326f077b8d8c01f0794d0
