### ISSUE TITLE
Does Rock db user stored procedures, views or triggers?

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1264]
This is a question.  I need help moving the Rock db to 3essentials.  

The 3essentials Windows backup instructions includes this comment:
Important: Plesk does not back up stored procedures, views, and triggers. The backup utility ignores them and, therefore, they cannot be restored.

Does the Rock database use these?  

If so, then this suggests that I cannot use a .bak to restore the db when moving the database from one server to another.  (I'm trying to move from Arvixe to 3essentials after they dropped my site a week ago.)

If I do a new install of Rock in 3essentials, and THEN restore a .bak file - will everything be there, or must I use a script file to do the restore?

**Comment by edmistj** [comment]
Rock does have stored procedures and may have views in the future. You might wait to move. There's other hosting options coming soon. To be announced at the conference. Also there is Managed Missions today.
