### ISSUE TITLE
[EN] Add Quick Search for Data Views and Reports

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#1269]
The intention is to add separate quick search filters for Data Views and Reports, so that they can be located quickly by Name.

With a lot of data views/reports organized in nested categories, sometimes they get lost!

@azturner Ok to proceed?

**Comment by MrUpsideDown** [comment]
@arranf Do you have a solution for this ready to go? If yes, feel free to claim it!

**Comment by arranf** [comment]
I do but I think @edmistj wanted to think about this. I suppose I could pull it in for review?

**Comment by MrUpsideDown** [comment]
@edmistj is there a problem with this proposed enhancement?

**Comment by edmistj** [comment]
I ran it past a few staff users and I don' think most of them would use it. I think we should do one of two things:
+ Add it to core but ensure that by default they are inactive in Search Services
+ Distribute it as a plugin.

I recognize the some organizations would see this as valuable, but I'm not sure all would and it would be more clutter for them.

Thoughts?

**Comment by MrUpsideDown** [comment]
Yes, I think Option 1 would work fine for a start.

To reduce the potential for clutter as a future enhancement, how about this:
1. Add an Attribute to each Search Component "Show as Smart Search" to indicate if the component is shown in the smart search drop-down.
2. Add an  "Advanced..." option to the smartsearch drop-down, which opens up a new search page where you can select any of the available Search Components, enter the search phrase and perform a search. This also lays the groundwork for allowing Search Components to provide an Advanced Search filter, similar to the filters used in Grids.

**Comment by edmistj** [comment]
OK how about you submit the components via pull request. We can circle back to the other enhancements when things settle down a bit and v4.0 is out the door.

**Comment by MrUpsideDown** [comment]
@edmistj I have a solution for this and I'm putting together a PR. This change involves a migration (to add new Pages/Routes, so I guess it's best to submit it on the develop branch rather than the 1.4 release branch?

**Comment by edmistj** [comment]
Yes 'develop' please, v4.0 is getting packaged for pre-alpha in the next day or two.

**Comment by cabal95** [comment]
Closed for inactivity. Feel free to re-open if needed. Also it's possible that with Universal search this may not even be an issue anymore.
