### ISSUE TITLE
System.StackOverflowException on Attendance Analysis Page

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1271]
On the Attendance Analysis Page, I'm getting a System.StackOverflowException on page load. The error is occurring on this line: ```foreach ( var group in groupType.Groups.OrderBy( a => a.Order ).ThenBy( a => a.Name ).Select( a => new { a.Id, a.Name } ).ToList() ) ```

**Comment by bwitting** [comment]
A little more info on this - I think it has to do with Volunteer Groups.  When I remove that Group Type from check-in configuration, the Attendance Analysis Page works just fine.  But I don't want to remove volunteers from check-in in my production environment.  I went through every volunteer team and there isn't anything troubling that I can see (like a parent group set to itself).  Any ideas?

**Comment by mikepetersonccv** [comment]
@bwitting It could be that a grouptype is a child grouptype of multiple grouptypes.  If so, https://github.com/SparkDevNetwork/Rock/commit/c775605468b1eefcd8b7991e8485239956dcd012 would have fixed it

**Comment by bwitting** [comment]
@mikepetersonccv Yes, I think that might be the case.  Thanks for the info (and the fix)!
