### ISSUE TITLE
Group's GroupTypeRole MaxCount not honored

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#1275]
As mentioned here http://www.rockrms.com/Rock/Ask/Troubleshooting/Questions/809 
* perhaps the GroupFinder block should not show groups that are at their max member (active) count
* the externally facing GroupRegistration block is not checking the group's MaxCount (active members) before adding the new person.

(The GroupDetail block _does_ check the MaxCount).

**Comment by nateh777** [comment]
Any update on this issue? I just noticed it in my questions months later and see that it has not been resolved yet. Haven't tried it yet but I am going to be starting on this area again in June.

**Comment by edmistj** [comment]
As a proposal then we should:

+ GroupFinder Block: Add a block setting 'Hide Overcapacity Groups' (default true?)

+ Group Registration Block: Add a block setting 'Prevent Overcapacity Registrations' - The difficult part about this is there may be room for one individual but I believe you can also register a spouse. What to do in that case? Show a warning "Group near capacity. Only one individual can register."?

Note we now have a group capacity setting on groups to consider also.

Give me your thoughts and we can see about getting this in for v5 (though we're very close to wrapping that up).

**Comment by nateh777** [comment]
I think your suggestions sound great. I would default to true on hiding overcapacity groups because that is what I expected to happen. For the with spouse registration I think the warning is acceptable.
