### ISSUE TITLE
Apostrophe in Schedule Description Breaks Check-in

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1279]
When there is a schedule that has an apostrophe in its description, and that schedule is used in check-in, there is a Null Reference Exception that occurs on the /welcome page.

**Comment by DerekMangrum** [comment]
I tried confirming this in Rock v4.2 and was unable to. Not 100% that I accurately replicated the environment, though. I made sure a Schedule had an apostrophe in the description, then assigned it to a Check-In Configuration, making sure it was checked in the Schedule Builder. Visiting the /welcome page gave me a correct countdown.

**Comment by bwitting** [comment]
@DerekMangrum we would have been on 3.5 at this point, so this issue may have been fixed since then.  I'll try it again in our environment and see if I can reproduce.

**Comment by DerekMangrum** [comment]
That was my thought. Hopefully that is the case. Let us know what you see.  :-)
