### ISSUE TITLE
Cache or script problem after moving to new server

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1280]
I'm trying to move from Arvixe to 3essentials to get up and running again. 
I have copied my database to 3essentials. I performed a clean install of Rock while pointing at a temporary database, then upgraded to 3.4, then I changed the webconfig settings to point to my production data.

I am now get these errors:

![cache1](https://cloud.githubusercontent.com/assets/4658177/10671771/0012a83c-7949-11e5-91d1-ac06a7113157.jpg)

![cache2](https://cloud.githubusercontent.com/assets/4658177/10671779/05b4315c-7949-11e5-8853-82e33ef765ab.jpg)

I tried clearing cache and got this error:
![cache3](https://cloud.githubusercontent.com/assets/4658177/10671789/0c781b02-7949-11e5-9e91-24f1633a8330.jpg)

Here are my diagnostic details:
![cache4](https://cloud.githubusercontent.com/assets/4658177/10671792/11ce7e8e-7949-11e5-9112-ee1db0c8cdc0.jpg)

Is this a simple setting somewhere, or something more serious?  Please advise what I should do next.  Should I FTP my old web site files across?  Thanks.  (There are others following in my footsteps...)

**Comment by nairdo** [comment]
@ElimAdmin Are you able to login on the new system once it points to your production copy database?

FTP copying your entire folder from one server to the other might not be a bad idea, but before you do anything, if you are NOT able to login to the new system, have you also copied over the important data (PasswordKey, DataEncryptionKey) from the actual web.config on Arvixe to your new web.config on 3Essentials?

**Comment by ElimAdmin** [comment]
@nairdo Yes, I can log in and do most things.  I'm seeing this error when I'm editing Workflow variables.
I haven't copied anything from any of the web.config files. Should I?

**Comment by ElimAdmin** [comment]
@nairdo I copied over those values.  I am still getting the same script errors when trying to edit Workflow variables.  And the same error on clearing cache.

**Comment by ElimAdmin** [comment]
@nairdo This may be a browser issue with the length of time Rock is taking to return results?

**Comment by nairdo** [comment]
Basically those web.config settings are for encryption / login stuff, but since you're able to login I wouldn't worry about that at the moment.  I'm trying to find what we have that's referencing those items (mutation-summary.js, jquery-2.1.0...) but I haven't had any luck.  Are those from something custom you've added to your Rock?

Beyond that, it appears that either your Rock does not have a App_Data/Cache folder or it doesn't have permission to that folder.  Are you able to file-browse your App_Data folder to check for its existence?

**Comment by arranf** [comment]
I remember when I did some moving around I had to change the permissions on
that folder. Perhaps that's it?

**Comment by ElimAdmin** [comment]
@nairdo @arranf  Thanks for your help.  I had to go into Advanced in 3essentials to set full control on all subdirectories in httpdocs.  This has resolved the cache error, but not the mutation error.  Debugging on the page has given these hints:
![scripterr1](https://cloud.githubusercontent.com/assets/4658177/10681261/d80a2744-7983-11e5-8836-174fe49f67cf.jpg)

Perhaps this is a Workflow editing issue, nothing to do with the web site move.  
Perhaps this is related to why editing workflows takes so long?
I get this error when opening a workflow, opening the workflow variables, and changing an attribute
and saving the attribute.  The rest of the site seems to function fine.

**Comment by ElimAdmin** [comment]
This problem may be related to add ons in my Firefox (I'll check later):
https://support.mozilla.org/en-US/questions/1066388

But its not just this - the same problem happens (locking at the same place) when using Explorer on another PC with no Skype installed.  
![scripterr2](https://cloud.githubusercontent.com/assets/4658177/10681795/9823a9e2-7989-11e5-87b5-cd84ad41de48.jpg)

Perhaps there are two different conditions.

**Comment by nairdo** [comment]
@ElimAdmin, Rock is not using jquery-2.X so I would agree that it may be a browser add-on. Have you also tried using Chrome? -- just curious. (Re: speed when editing Workflows... some decent performance improvements have been made in the upcoming 4.0 release, so you'll find it's much nicer when your working with large ones.)

**Comment by ElimAdmin** [comment]
@nairdo I'll try Chrome.
This from Explorer 10:
![scripterr3](https://cloud.githubusercontent.com/assets/4658177/10684595/82e2dfea-79ab-11e5-86eb-7872712ad67d.jpg)

**Comment by ElimAdmin** [comment]
@nairdo @arranf  This was three issues:
1. The //gre script issues were caused by the Skype Click to Call add on in Firefox.  Removing this add on by uninstalling it has removed the //gre script errors and allowed me to edit Workflow variables again.  
2. The cache issue was resolved by setting permissions in 3essentials by using the Advanced button.  
3. There is still a problem editing Workflow variables using Explorer 10 on PCs without Skype.  The page times out and the blob freezes.  Given the upcoming changes to Workflow in v4 this is not worth resolving.

I'm confident now that this issue was not caused by moving servers or reinstalling Rock.
Thanks for your help.
