### ISSUE TITLE
Lava Field for Phone not Hydrating

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#1282]
The lava field for phone description is in the "debug mode" but not populating to Lava.

```<ul>
{% for phone in CurrentPerson.PhoneNumbers %}
<li>{{ phone.NumberFormatted }} {{ phone.Description | Default:'(none)' }} {{ phone.NumberTypeValueId }}</li>
{% endfor %}
</ul>
```

**Comment by azturner** [comment]
@treyhendon , There is probably not a value to populate? The Rock UI does not display or provide a way to update this field. We'll update it to be excluded from the Lava debug info. If you're looking for the type, you could use {{ phone.NumberTypeValue.Value }}

**Comment by treyhendon** [comment]
But description is in the lava debug info...
![image](https://cloud.githubusercontent.com/assets/3513589/10900054/23e863ce-81a9-11e5-9f7e-76092ec50113.png)

**Comment by azturner** [comment]
Right, so that's the Description on the NumberTypeValue property vs. the Description on the phone number. So you can reference that by {{ phone.NumberTypeValue.Description }}.

**Comment by treyhendon** [comment]
Oh, duh Trey.  Sorry man!  Thanks!
