### ISSUE TITLE
Family Attendance Badge only showing Checked-In Attendance (not Group Toolbox marked)

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#1283]
I think this function is limiting the scope of the badge results to only count attendance which came in from a kiosk and not including group leader attendance.

I think this is the function that is causing the limiting:
https://github.com/SparkDevNetwork/Rock/blob/2a952baabc59febf80167fa958cef2fdc3f79b5e/Rock.Migrations/Migrations/Version 0.1 (Pre Beta)/Version 0.1.5/201402050535388_CreateFunctionsAndSpForAttendanceBadge.cs#L57

**Comment by cabal95** [comment]
Did a little investigating. It isn't that it limits to kiosk check-in. It limits to group types that are marked as a Weekend Service attendance. So probably documentation/tooltips need to be updated to note that this badge is only for weekend related attendance.

**Comment by arranf** [comment]
Updated the family field guide to specify that the attendance is weekend attendance as this seems like the desired behaviour.
