### ISSUE TITLE
Multiline Text Fields and iPad Bluetooth Keyboards

### ISSUE THREAD

**Issue by jhawkzz** [SparkDevNetwork/Rock#1284]
If a text field is being typed in with a bluetooth iPad keyboard, when 'return' is pressed, it returns to the beginning of the line, but doesn't create a newline. It's as if the carriage return is being sent, but not the newline.

This doesn't occur with the software keyboard.

**Comment by cabal95** [comment]
I tried various multiline field types (Memo, Html, Code) as well as the standard multi-line Description field of groups and could not reproduce.
