### ISSUE TITLE
Web site: all Learn/videos are playing 'Setting Up Your Development Environment'

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1293]
For example,

Intro to Rock
http://www.rockrms.com/page/513?Item=68

Intro to Building Blocks
http://www.rockrms.com/page/513?Item=74

all play the Setting Up Your Development Environment video (item 67)

Go Nick!
(Could we have the others back, please?)

Have tried this on two different laptops running IE, Firefox and Chrome.

**Comment by edmistj** [comment]
This is fixed.

**Comment by ElimAdmin** [comment]
Thanks Jon.
