### ISSUE TITLE
Excel export throws exception on table columns with duplicate display names.

### ISSUE THREAD

**Issue by jhawkzz** [SparkDevNetwork/Rock#1294]
If you export a table from Rock that has duplicate column display names, the Excel exporter will throw an exception. This happens even if the values have unique keys.

**Comment by garrettjohnson** [comment]
Not sure when this was fixed but Rock now appends a number for each duplicate column title name after the first. 🎉 

**Example Report**
![screenshot 2017-03-24 10 56 01](https://cloud.githubusercontent.com/assets/374209/24307243/99de6b20-1080-11e7-81e5-4c5d7761538b.png)

**Resulting Excel File**
![screenshot 2017-03-24 10 55 31](https://cloud.githubusercontent.com/assets/374209/24307222/8549caf6-1080-11e7-8dc9-36e58ef53dab.png)
