### ISSUE TITLE
[EN] Add Data Filter "Group/Location Data View"

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#1297]
...to select Groups associated with Locations from a specified Data View.

The intention is to implement this using the same pattern as #1202.

**Comment by arranf** [comment]
@MrUpsideDown Have you written this? If so, do you want to pull it in or send me the files so I can commit it to core?

**Comment by cabal95** [comment]
I believe what is being requested / suggested is a DataView filter on Entity Type `Group` that would let you filter by associated locations.

**Comment by drychlik76** [comment]
This is exactly what we need for one of our requirements!

**Comment by arranf** [comment]
@mrupsidedown Did you do this in your fork?

**Comment by MrUpsideDown** [comment]
@arranf Yes, I have. I could create a PR for it if you like.

**Comment by arranf** [comment]
@MrUpsideDown That'd be great

**Comment by jonedmiston** [comment]
Opened as internal task
