### ISSUE TITLE
Cannot Save Block Properties

### ISSUE THREAD

**Issue by dcagnetta** [SparkDevNetwork/Rock#1298]
Hi all, in certain blocks properties the save button doesnt work.

I have tried numerous browsers.

e.g. the EMAIL PREFERENCES BLOCK

**Comment by arranf** [comment]
I can reproduce this using the Rockit but I am unable to reproduce using
the latest version of develop.

**Comment by ElimAdmin** [comment]
I think this occurs when <> is included in a field.
