### ISSUE TITLE
[EN] Expose a way to return only the ImageUrl (in FormatValue of ImageFieldType) for use with Lava

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#1299]
Our web guy, Kreston, is looking to get only the image's ImageUrl property of an Image fieldtype attribute of a content channel item (when working in Lava).  I think this is where we would want to make the logic insertion:

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Field/Types/ImageFieldType.cs#L156

I'm just not clear about the implications at this point without further research.

**Comment by azturner** [comment]
@nairdo Can't he just use the 'RawValue' attribute filter qualifier to get just the guid and then build the url himself?

**Comment by arranf** [comment]
@nairdo I have an example of what azturner just described if Kreston needs it

**Comment by bwitting** [comment]
+1 @azturner. We're doing that already too @nairdo

**Comment by nairdo** [comment]
@azturner I guess as long as he knows (and uses) the local/blob storage... unless all storage providers still let you retrieve the image via Rock's GetImage handler -- in that case it would not matter and he could always use GetImage.

**Comment by nairdo** [comment]
Ok, closing.
