### ISSUE TITLE
[EN] ? Don't include group type in Group List options if not set to show in group lists

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1302]
If a group type is flagged to NOT show in group lists... 
![dispalgroup1](https://cloud.githubusercontent.com/assets/4658177/11086839/dbffd160-88b9-11e5-99bf-24c2fe63f0ea.jpg)

... does it make sense to include this group in the list of possible options for the Group List block?

![displaygroup2](https://cloud.githubusercontent.com/assets/4658177/11086846/f36d2c3a-88b9-11e5-8b5e-ea2630fefcc9.jpg)

If you select this group type, no groups will list.  
It might be more consistent to NOT include this group in the list of options.

**Comment by arranf** [comment]
I think from a UX perspective it may be confusing having them hidden. If we
don't want to populate those group types on the list perhaps we should make
them appear disabled? If we could have a tooltip that could explain why.

**Comment by cabal95** [comment]
I think I'm with Arran on this one about it being confusing. I think the intention is "hide it from things a normal user would see". Whereas the example you gave is for something the Admin would see. But I'll leave this open for a core dev to make a final decision on.
