### ISSUE TITLE
Phone Lava Filter Doesn't Display

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1303]
We're trying to pull a specific phone number from a record but currently only {% for PhoneNumber in CurrentPerson.PhoneNumbers %} {{ PhoneNumber.NumberFormatted }} {% endfor %} exists as far as I know.  The 4.0 Lava documentation mentions {{ CurrentPerson | Number:'Home' }} as an option but on the alpha.rockrms.com site, this doesn't seem to function.

**Comment by arranf** [comment]
The alpha rock site isn't the latest version of 1.4.

**Comment by edmistj** [comment]
I'm updating it right now. Should be done in 20mins. The documentation notes the following syntax:

Work Number: {{ CurrentPerson | Number:'Home' }}

Should 'Number' be 'PhoneNumber'?

**Comment by BelAirIT** [comment]
I'm no coder but I'd say shorter is better.

**Comment by arranf** [comment]
Good catch Jon. Yes that should be PhoneNumber.

**Comment by edmistj** [comment]
I think you're right though the the code doesn't have the latest. Even when I tried it it didn't work. Will have the latest soon.

**Comment by arranf** [comment]
Updated the Lava docs. Are you saying this doesn't work locally? Booting up my Rock project to test.

**Comment by edmistj** [comment]
The problem was an old version of v4 on the alpha. It's now updated and working. http://alpha.rockrms.com/page/19

**Comment by arranf** [comment]
Phew I thought I'd written broke code!
