### ISSUE TITLE
Radio Button field types flagged as required can't have a blank default value. 

### ISSUE THREAD

**Issue by jhawkzz** [SparkDevNetwork/Rock#1305]
If you create an attribute value as a Radio Button, setting its default value to 'blank' doesn't save if you also check the 'required' field.

This makes it impossible to have a required Radio Button field that the user MUST enter a value for.

**Comment by cabal95** [comment]
This has been fixed at some point. I am able to create a Person Attribute of type Single Select with the display style set to Radio Buttons. I gave it two values (`Value1`, `Value2`) and marked it as Required. I did not set a default value and saved. On the person detail page it shows as expected (screenshot is after I tried to click Save without setting a value).

![image](https://cloud.githubusercontent.com/assets/1119863/24809276/db6b0be0-1b73-11e7-8e60-242e79cb3f0f.png)
