### ISSUE TITLE
[EN] Add "Is In" Comparison Type for Text Data Filter

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#1306]
The purpose of this comparison is to allow multiple "Equal To" comparisons to be combined using a logical OR into a single filter.

For Example:
[Location].[Postal Code] Is In (3000,3001,3002)
is equivalent to 
[Location].[Postal Code] Equal To "3000"
OR [Location].[Postal Code] Equal To "3001"
OR [Location].[Postal Code] Equal To "3002"

**Comment by MrUpsideDown** [comment]
@azturner Ok to add this?

**Comment by azturner** [comment]
Yep, but develop branch.

**Comment by MrUpsideDown** [comment]
Will do, thanks.
