### ISSUE TITLE
Install error? Default page on external site throws "Object reference not set to instance of an object"

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1307]
I ran the RockRMS install on a new Azure host and got/am getting this error on the external site:

![image](https://cloud.githubusercontent.com/assets/1210933/11212703/558054ca-8d05-11e5-9704-f1589d0f3225.png)

Browsing the internal site works correctly with no issues:

![image](https://cloud.githubusercontent.com/assets/1210933/11212826/41f2e3e0-8d06-11e5-80f0-607b2f1b9ee2.png)

**Comment by azturner** [comment]
Anything in the exception log with more details?

**Comment by dcs619** [comment]
Just the same error:

![image](https://cloud.githubusercontent.com/assets/1210933/11214537/d218ea1a-8d0f-11e5-90b4-01a46e42a0ba.png)

Let me disable custom errors in the web.config and see what that gives me.

**Comment by azturner** [comment]
If you click into the details does it give you a stack trace?

**Comment by dcs619** [comment]
@azturner 
![image](https://cloud.githubusercontent.com/assets/1210933/11214642/6c7a9766-8d10-11e5-9b5e-a867e5cd0910.png)

**Comment by azturner** [comment]
I had to ask. :)

**Comment by azturner** [comment]
we'll try to reproduce it (and we'll rename that method).

**Comment by dcs619** [comment]
@azturner I restarted Azure and I'm not getting the exceptions, but images aren't loading:

![image](https://cloud.githubusercontent.com/assets/1210933/11215126/baa47d92-8d12-11e5-983f-9c2178f8186d.png)

I'm gonna close this issue, let me know if you need any more info.
