### ISSUE TITLE
From Textbox on Communication Entry Block Doesn't Validate Email

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1312]
When sending an email with the Communication Entry block, the From box doesn't validate that the text in it is an email, only that there is something there.  We have staff and volunteers putting text that isn't a email in that box, and then the Send Communication job fails because the From address isn't valid.

**Comment by azturner** [comment]
This was fixed here: https://github.com/SparkDevNetwork/Rock/commit/c66f0f325d7536001d2affa9651cfe4393dd2359.
The Reply To has also been updated for v4.0 to only allow email addresses.

**Comment by bwitting** [comment]
Great, thanks @azturner
