### ISSUE TITLE
Adding person photo in Firefox

### ISSUE THREAD

**Issue by pufferdude** [SparkDevNetwork/Rock#1315]
Seeing a minor issue when adding a person photo in FireFox (42.0) After choosing the file to upload you get the "waiting" image and never see the uploaded image, even though it is there if you go ahead and save the record. 
![edit person _ rock rms - mozilla firefox 2015-11-20 09 23 28](https://cloud.githubusercontent.com/assets/3903408/11303619/7343fb4a-8f69-11e5-8ba7-7ec186d13a8a.png)

This is on McKinley 3.4

**Comment by mikepetersonccv** [comment]
fixed in https://github.com/SparkDevNetwork/Rock/commit/55c156da2572f9f348bdecd8cd6a4f0643e9d61c
