### ISSUE TITLE
SMS communication not fully responsive

### ISSUE THREAD

**Issue by kcirgjd** [SparkDevNetwork/Rock#1316]
The merge field is off the screen on an iphone... 
![image 1](https://cloud.githubusercontent.com/assets/7595345/11305872/cef9111a-8f7c-11e5-9093-bb9bd7e54bb1.png)

The calendar shows up under the keyboard. If you try to scroll it disappears before you can select a date. 
![image](https://cloud.githubusercontent.com/assets/7595345/11305873/cef9dea6-8f7c-11e5-8da9-4eb1733e51b0.png)

Time selector seemed to work as needed.

**Comment by edmistj** [comment]
What do you think about us hiding the merge field picker on mobile? Wondering too if we should convert to the Rock date/time pickers to mobile controls when on a mobile phone. 

Feedback welcome/desired.

**Comment by arranf** [comment]
@edmistj The time/date pickers work quite well on my phone (Nexus 4)

**Comment by edmistj** [comment]
@arranf OK, that's good to know.

**Comment by arranf** [comment]
@edmistj I've just had a quick browse around Rock on my phone to see if I could spot any mobile unfriendly controls the only one I could find was the person picker.

**Comment by edmistj** [comment]
@arranf Thanks, you Rock!

**Comment by kcirgjd** [comment]
The reason I noticed was because I went to use it last night and it didn't work but in over a year this was my first time trying to send an SMS to a group of people from my phone so it's not a high demand feature to me.
