### ISSUE TITLE
Page Loading Hangs (v4.0 Alpha)

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1321]
There was an issue listed as resolved in the patch notes but doesn't seem to be resolved yet.  Navigating seemingly random pages or trying to add blocks or view page layouts causes a long load time of already cached content.

<img width="320" alt="loading" src="https://cloud.githubusercontent.com/assets/7409839/11446375/bb80b372-94ea-11e5-9bcf-48192ec1917c.png">

**Comment by cabal95** [comment]
I haven't experienced this or heard of this happening since we have been running 5.x, so I believe this is safe to consider fixed. Please request to re-open if this is still a bug.
