### ISSUE TITLE
Submitted Connections Don't Add Members

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1322]
When going to the external site and submitting a connection request, it should add the person to the group specified in the Placement Group section.  Instead, it doesn't add them or notify the Connector Group members of any changes.

**Comment by nairdo** [comment]
Adding the requestor to one of the configured placement groups is the job of someone from the Connector Group... And they would really only do that once they've qualified the requestor and verified their credentials (background check, reference checks, etc.).

I suspect this workflow will be quite different from church to church which is one of the reasons why it doesn't come with one out of the box.

Of course you could just configure your workflow to just put a requestor into the first placement groups it finds, but that seems to short circuit the spirit of the Connections system.
