### ISSUE TITLE
Can't save Austria as organization country

### ISSUE THREAD

**Issue by AlBeeNo** [SparkDevNetwork/Rock#1323]
Hi all,
am trying to set up our church in Rock which is based in Austria, Europe. While Austria is listed in the list of countries to chose from, the page where I set up my organization won't save the content if Austria is the selected country. I've tried Germany now, and it works just fine :-I . Afterwards I tried editing my organization country to Austria in the settings and again it won't save the change. Can someone help? 
Thanks,
AlBeeNo

**Comment by azturner** [comment]
Do you mind sharing the exact address you are attempting to enter. You can email it to me if your not comfortable posting it here.

**Comment by AlBeeNo** [comment]
thank you for replying so quickly, I've emailed you the details.

**Comment by cabal95** [comment]
@azturner Is it safe to assume this has been dealt with 18 months later? :)

**Comment by cabal95** [comment]
Just tested with azturner's help and this appears to be working as intended.
