### ISSUE TITLE
[v4 Update] Can't edit existing notes, new notes added as a different type

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1327]
After updating to v4.0 Alpha, I'm unable to edit or delete any existing notes (as an admin)

v3.5:
![2015-12-03 11_04_47-start](https://cloud.githubusercontent.com/assets/1859094/11565822/ca6cf8ec-99ad-11e5-83b9-97df9a1c54b7.png)

v4:
![2015-12-03 11_04_35-start](https://cloud.githubusercontent.com/assets/1859094/11565826/ce165902-99ad-11e5-8410-1ec0fd4d439e.png)

When I added a new note in v4 (above), it was saved as a new note type (Id 5, a Volunteer note)  All old notes before the update were type id 4, Notes:

![2015-12-03 11_05_53-sqlquery1 sql - 10 1 10 210 rock-production rock 59 _ - microsoft sql server](https://cloud.githubusercontent.com/assets/1859094/11565846/e66a1e6c-99ad-11e5-82bb-a9518fc51939.png)

I looked at note types, and it looks like Administrators have correct permissions on all note types. Why can't I edit old notes? And why are new notes being saved as a different type?

**Comment by bwitting** [comment]
When editing the Notes note type, checking User Selectable adds the edit and delete options back.  However, new notes are still being saved as an incorrect type.

**Comment by azturner** [comment]
@bwitting can you paste (or email me) the contents of your notetype table

**Comment by bwitting** [comment]
@azturner I sent them via email. Thanks!

**Comment by azturner** [comment]
Fixed Here: https://github.com/SparkDevNetwork/Rock/commit/061291b94c8a0ae5750584d0a8ca3e4fb8c96dbf
