### ISSUE TITLE
[4.0 Alpha] Group Leader Pending Notifications

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1329]
This isn't really a 'bug', but when initiating this job it sends to all people even if they've been Pending, for example, for weeks or months.  So, if we wanted it to notify the group leader of people that join his group with a status of Member and Pending then it searches the database for ALL people meeting those criteria even if they were put in that status a long time ago.  Perhaps only kick off email notifications AFTER the job is setup?

**Comment by edmistj** [comment]
Yeah good point. Maybe we add a job setting to limit the duration defaulted to 1 day?

**Comment by BelAirIT** [comment]
That makes sense.

**Comment by edmistj** [comment]
Will be in the beta
