### ISSUE TITLE
Exception count graph incorrect?

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1330]
While trying to track down a recurring exception, I noticed that the total number of exceptions is about 2x the number reflected in the graph for the affected time period. Is this a bug, or am I interpreting the graph/counts incorrectly?

![exception list _ rock rms - mozilla firefox 2015-12-04 09 22 55](https://cloud.githubusercontent.com/assets/3903408/11593251/e44551fe-9a68-11e5-8653-f86fa93f2414.png)

**Comment by pufferdude** [comment]
Also, this is on 4.0 alpha

**Comment by cabal95** [comment]
@JimMichael I would suspect the difference you are (were) seeing is expected. If you were to expand that "exception type" and look at the dates of specific exception you would probably see that the actual number of exceptions on that specific day to be around 300. Looking at your grpah (which covers around 7 days), it looks like you had around 200 on Dec 1; 280 on Dec 2; and another 200ish on Dec 3. Which is around 680 and that appears to be correct based on the list below.
