### ISSUE TITLE
Date format in metrics graph doesn't respect browser settings

### ISSUE THREAD

**Issue by jezhailwood** [SparkDevNetwork/Rock#1336]
Most dates in Rock are formatted according to my browser settings (DD/MM/YYYY), but dates displayed when hovering over data points on a metrics graph use MM/DD/YYYY.

**Comment by joshmooresound** [comment]
On both the Mac and Windows computers, the computer keyboard and language settings are set to English (United Kingdom).

In Safari 8.0.8 (Mac OS 10.10.5), the date on the graph is formatted as DD m YYYY (e.g. 31 May 2015) and the corresponding date on the table is MM/DD/YYYY 

Firefox 41.0.1 (Mac OS 10.10.5) displays the date on the graph and in the table as DD/MM/YYYY.

Chrome 46.0.2490.86 (Mac OS 10.10.5) - with the browser set to English (United Kingdom), the date on the graph is MM/DD/YYYY and in the table as DD/MM/YYYY

Chrome 47.0.2526.106 (Windows 7 Professional, Service Pack 1) - set to English (United Kingdom) displays the date in both the graph and the table as DD/MM/YYYY, however changing the language setting to English (United States) changes the date in the table to MM/DD/YYYY, but the graph is still displaying DD/MM/YYYY

Internet Explorer 11.0.9600.18124 (Windows 7 Professional, Service Pack 1) displays the date on the graph as DD m YYYY (e.g. 31 May 2015) and in the table as DD/MM/YYYY

**Comment by arranf** [comment]
Fixed
