### ISSUE TITLE
Some photos missing only on iOS. 

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1337]
I'm seeing an issue on 3.4 where certain people with photos are not viewable on iOS. Here's an example. If the person had no photo at all you would see the default gender avatar, but here the photo is there on desktop but missing in mobile. I think this has to do with the size or proportions of the source image as some do work fine while others don't, but I haven't figured out what triggers a bad view on mobile.  

![image](https://cloud.githubusercontent.com/assets/3903408/11887994/d7f91ad4-a4fe-11e5-9477-7345538f6dc7.png)

**Comment by edmistj** [comment]
Is there any way we could get access to see this record? Or perhaps the source and the image with the issue?

**Comment by JimMichael** [comment]
This was a false alarm. Ended up discovering that "someone" (no one will fess up so far) disabled BOTH File System and Database storage providers in production instance of Rock. The random good images I was seeing were apparently cached in the browser.
