### ISSUE TITLE
Numbers

### ISSUE THREAD

**Issue by kaHoffmann** [SparkDevNetwork/Rock#1342]
00/08/2014,   Dates show 00 randomly

**Comment by azturner** [comment]
@kaHoffmann , we need more details about where you are seeing these dates.

**Comment by kaHoffmann** [comment]
Sorry,  I was able to find the problem and it is resolved.

**Comment by kaHoffmann** [comment]
I am trying to create a report on a list of those that have passed away this past year.  We would like to send cards to their loved ones on the one year anniversary date of those who have passed.  Since we have Known relationships I thought that would be a great way to get the names of their loved ones still living.  The issue I have is once we make the deceased in the system the known relationship doesn't connect.  I get it that since the person has passed the relationship has ended but is there away that I can pull this information easy?

**Comment by azturner** [comment]
@kaHoffmann When a person is marked as deceased, there shouldn't be any change automatically being made to known relationships. But... you will probably have more luck getting some help by posting a question in Slack rather than commenting on this closed issue :).

**Comment by kaHoffmann** [comment]
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>




On Sun, Nov 13, 2016 at 6:58 AM -0700, "David Turner" <notifications@github.com<mailto:notifications@github.com>> wrote:


@kaHoffmann<https://github.com/kaHoffmann> When a person is marked as deceased, there shouldn't be any change automatically being made to known relationships. But... you will probably have more luck getting some help by posting a question in Slack rather than commenting on this closed issue :).

-
