### ISSUE TITLE
File Manager in 4.0 odd behavior

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1343]
I'm seeing some strange behavior with the File Manager tool under CMS Configuration menu in 4.0 beta. It will not show any non-image documents on the file system. Uploading a non-image document works (it gets saved to the file system) but also doesn't show. Uploading an image file DOES show as expected. This behavior is exclusive to the File Manager block and does not occur when viewing the file system via an HTML block's uploader tool. I have verified that the Browser Mode in the File Manager block is set to doc (it was defaulted to that) and also tried toggling to image mode and back to doc with no effect.

File Manager:
![file manager view](https://cloud.githubusercontent.com/assets/3903408/12178415/ec32a18a-b536-11e5-89d0-2f17c1b965fa.png)

HTML Block:
![html block view](https://cloud.githubusercontent.com/assets/3903408/12178449/1f954dac-b537-11e5-88bb-47ea62f13591.png)

**Comment by DerekMangrum** [comment]
Confirmed issue with File Manager behavior in Rock v4.2
