### ISSUE TITLE
Merge Templates from Reports Doesn't Keep Sorting

### ISSUE THREAD

**Issue by matthewmeekins** [SparkDevNetwork/Rock#1345]
When using the mailing labels merge template that comes with 4.0, if "Combine Families" is checked then the generated document doesn't keep the **sorting from the report**. If unchecked, it uses the correct sorting. Not sure if this is a bug or not. I used multiple sorting methods.

This is a problem because we just printed our giving statements using the statement generator. The statement generator sorts based on postal code (zip). The person stuffing the envelopes is having to sort through an unsorted pile of address labels to find the correct label.

**Comment by nathanp** [comment]
We are having this same issue. Any help?

**Comment by hillsideassembly** [comment]
Can confirm this is still a problem.

**Comment by jacjacwil** [comment]
We are having the same issue as well.

**Comment by sarahile** [comment]
We are having this same issue.  Is there a timeline on this fix?

**Comment by HansenGrace** [comment]
Coming soon - the core team is working on a solution.
