### ISSUE TITLE
Email form block won't accept multiple recipients

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1347]
Using the Email Form block, the recipients field says you can enter a comma-delimited list of addresses, but this does not work (at least not in 4.0beta). When entering more than a single address I get the following:
![creative request _ rock rms - mozilla firefox 2016-01-12 15 47 41](https://cloud.githubusercontent.com/assets/3903408/12278014/3ef75512-b944-11e5-8265-45c7ea3956a3.png)
I also tried playing with adding comma+space, a semicolon instead of comma, etc but anything beyond a single address causes that error here.

Also, recipient is misspelled "Receipient" in the block properties.

**Comment by edmistj** [comment]
Yeah that's probably the validation on the email field. I'll look into that. Might need to make it a regular text field.

**Comment by azturner** [comment]
Was fixed in v4.1 here: https://github.com/SparkDevNetwork/Rock/commit/c93357e7
