### ISSUE TITLE
Block Attribute set to a blank value gets reset to the default value

### ISSUE THREAD

**Issue by tcavaletto** [SparkDevNetwork/Rock#1352]
On the New Family page, we're trying to set the Default Connection Status attribute on the AddGroup block to be blank. However, when we hit save, the default connection status gets set to 'Visitor'. Incidentally, this is the attribute's default value. Is this because Rock automatically fills in an attribute with no value with the default value for that attribute?

**Comment by azturner** [comment]
Yes, that is because it has a default value and whenever an attribute value is null or blank it uses the attribute's default value. Curious why you would want to set the connection status for new people to be blank though?

**Comment by azturner** [comment]
@tcavaletto , Closing this. Feel free to re-open if you feel this is still an issue.
