### ISSUE TITLE
[EN] Rename IsSpecialNeeds to HasSpecialNeeds

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1355]
Our kids ministry would prefer marking children with "Has Special Needs" instead of "Is Special Needs".  

If this change won't break any custom code (@nairdo?), I can submit a PR to change [FilterGroupsBySpecialNeeds](https://github.com/SparkDevNetwork/Rock/blob/1974c937c8219ba311565440faad4bf6dde7176a/Rock/Workflow/Action/CheckIn/FilterGroupsBySpecialNeeds.cs) and a migration to update the Attribute name/key in the database.

**Comment by nairdo** [comment]
I think it would be a great time to also change that filter to use a configurable setting instead of hard coding the attribute key. Then, also, if it's a core attribute it should be prefixed with the new "core." naming convention.

**Comment by nairdo** [comment]
@dcs619 Here is the write-up that would be added to the Rock v5 check-in guide.  I'll modify it after you make the needed changes and add it to the book.
[Checkin - Advanced Feature - Special Needs Handling.docx](https://github.com/SparkDevNetwork/Rock/files/100861/Checkin.-.Advanced.Feature.-.Special.Needs.Handling.docx)

**Comment by dcs619** [comment]
@edmistj Any preference re adding a HasSpecialNeeds person attribute to core?  Based on the documentation @nairdo posted, users need to add that attribute themselves.

**Comment by edmistj** [comment]
I'm open if you think it would be better to have it exist in core.

**Comment by dcs619** [comment]
It sounds like @nairdo and I are the only ones using it, so ¯\_(ツ)_/¯

It does seem weird to have a core check-in filter (see PR) that's dependent on a non-core attribute.

**Comment by edmistj** [comment]
@nairdo Can you add a migration to add this person attribute. No hurry as this will be a v5 feature.

**Comment by dcs619** [comment]
@nairdo Here are the settings we're using:

![screenshot 2016-02-03 11 19 35](https://cloud.githubusercontent.com/assets/1210933/12788645/48b4ea44-ca68-11e5-932a-437453ce90e7.png)

We changed from a Boolean data type to Single-Select as `No` means the same thing as nothing selected.

**Comment by dcs619** [comment]
@nairdo I have an updated version of this workflow action that allows you to select the Person/Group Special Needs attribute on the action, instead of depending on matching key string.

Did you ever add a migration for the person attribute?  If so, I can set the default GUID for the action before I push it.
