### ISSUE TITLE
Windows check-in client in v.4 does not close with the 5 sec hold

### ISSUE THREAD

**Issue by gsleininger** [SparkDevNetwork/Rock#1358]
I have a Surface 3 (not pro) running Windows 10. When I go to close the windows check-in client by tap and holding the top left corner as usual, it does not close. I also tried using a mouse with a click to hold. Nothing happens.

**Comment by edmistj** [comment]
Ah yes... sorry this changed.  You must now tap 6 times in a row instead of a single loooooooong tap.  Will make sure that the documentation is updated.

**Comment by gsleininger** [comment]
That did it. Thank you!
