### ISSUE TITLE
Transaction Matching Block not showing account filtering options

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1361]
in v4.1:

In the block settings for transaction matching, I have selected accounts that I want to be available:
![2016-01-26 09_38_14-transaction matching _ rock rms](https://cloud.githubusercontent.com/assets/1859094/12583394/96d19168-c410-11e5-9123-cbe5aed1ea6b.png)

But those don't show up in the filter options for the block (and the one that does show up isn't one I selected):
![2016-01-26 09_38_53-transaction matching _ rock rms](https://cloud.githubusercontent.com/assets/1859094/12583404/a41e6f9e-c410-11e5-96cb-348ce7dcd31e.png)

If I don't select anything in the filter options, I can see all the accounts that I have selected in the block options.

Possibly related: some of the account names had characters like parenthesis and apostrophes. The transaction matching block wouldn't let me save if I chose an account name with those characters in it. I removed those characters from the account name and it saved. (These characters worked in v3.5)

**Comment by bwitting** [comment]
@azturner I figured out something else: the account filter will only show that Event Registration account if it has a NULL ParentAccountId.  If not, nothing shows. 

Here's the weird part: the query is returning all 43 accounts, they just don't seem to be getting bound to that drop down for some reason?
![2016-02-05 10_16_22-rockit debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/1859094/12850178/74f72b96-cbf1-11e5-94f7-a2123877c236.png)

**Comment by bwitting** [comment]
By changing ```DisplayActiveOnly="true"``` to ```DisplayActiveOnly="false"``` in  ```<Rock:AccountPicker ID="apPersonalAccounts" runat="server" AllowMultiSelect="true" Label="Select Account(s)" DisplayActiveOnly="true" />```,  the correct accounts now appear (and all of the not active ones...).  Maybe something is wrong in the AccountPicker.cs control?

So by doing that it's working better - at least I can see all accounts.  But the AccountPicker in the Accounts Filter options don't respect the block settings (no matter what is in the block settings, all accounts (including inactive) show up there).

**Comment by bwitting** [comment]
One more thing, on other places where the AccountPicker control is being used (like TransactionDetail), it doesn't look like it's respecting the ```DisplayActiveOnly="true" ``` option - all accounts display no matter if this is set to true, false, or doesn't exist.

**Comment by azturner** [comment]
@bwitting Setting the DisplayActiveOnly="false" should display all of the inactive accounts right? (somewhat of a double negative I suppose).  Setting it to "true" would hide all the inactive accounts. Looked at your data and it looks like all of your root-level accounts are inactive which is why you don't get any options in your filter list. Make sense? Do you still think there's an issue?

**Comment by bwitting** [comment]
D'oh... I never thought about the top level accounts being inactive. I think this behavior changed from v3 to v4 because they've always been inactive (finance just uses them for organization) So no, no issue -  it makes sense that if a top-level account is inactive child accounts are too. Thanks!
