### ISSUE TITLE
Group Sync Error

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1363]
Receive the following exception when syncing a group with a dataview and starting the Job.

![image](https://cloud.githubusercontent.com/assets/7409839/12598238/d00b0a9a-c43d-11e5-9f04-3691e618fb5b.png)

**Comment by DerekMangrum** [comment]
Could not confirm in Rock v4.2. Looks to work as intended there.

**Comment by edmistj** [comment]
Per Jeremy: It looks like the error only happens when using a Named Location for the Group Details location. If you manually draw the geo-fence from the group details it works.

**Comment by Kronos11** [comment]
I have also gotten a similar error to this on the group sync job. After debugging it looks like there were a number of people that were trying to be added that already existed, but they were deceased. Does this job properly handle the case in which the groupmember is deceased?

**Comment by arranf** [comment]
@BelAirIT Are you still running into this issue?
@Kronos11 Are you still running into your issue with deceased individuals?
