### ISSUE TITLE
Content Channel Meta Description Attribute Broken

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1367]
After the update from 3.5 to 4.1, the Content Channel Meta Description Attribute is broken.  Instead of displaying the actual content, it displays Rock.Web.Cache.AttributeValueCache:

```
<link type="application/rss+xml" rel="alternate" title="The Daily" href="http://newpointe.org/GetChannelFeed.ashx?ChannelId=20" /><meta name="description" content="Rock.Web.Cache.AttributeValueCache" />
```

![2016-01-27 14_20_07-the daily _ newpointe community church](https://cloud.githubusercontent.com/assets/1859094/12625233/e31dbb46-c500-11e5-8341-6db878401158.png)

**Comment by azturner** [comment]
This has been fixed here: https://github.com/SparkDevNetwork/Rock/commit/4deb1ef0d18b2f4f0147d3af2f757187d6c035fa and then really fixed here: https://github.com/SparkDevNetwork/Rock/commit/32a384153c836ca5e2b5407eab459a92c67a9916. and will be included in 4.2.
