### ISSUE TITLE
Organization Address Not Editable

### ISSUE THREAD

**Issue by tavon** [SparkDevNetwork/Rock#1369]
Clicking on the "x" icon or the dropdown button on the default location does nothing.

![screen shot 2016-01-28 at 1 43 27 am](https://cloud.githubusercontent.com/assets/3383/12637093/9ea51440-c560-11e5-984f-b1b42a432a0b.png)

**Comment by edmistj** [comment]
Yeah that’s probably a bit confusing.  Using the edit button you’re actually editing the attribute itself. Since this is a system attribute you are not allowed to change its properties.  If you click the row you can edit the attributes value (which is what you really want to do).

-Jon



[jon]

**Comment by tavon** [comment]
Thank you for the clarification.  I see that this is a global attribute default.  To change this value we should go to: General Settings > Global Attributes
