### ISSUE TITLE
[EN] Search By Name documentation is overly complicated

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1372]
This section of the Check-in -> Walkthroughs documentation is overly complicated.

![screenshot 2016-02-01 09 54 46](https://cloud.githubusercontent.com/assets/1210933/12720715/09da3efe-c8ca-11e5-8dd4-4d602fb33194.png)

You can easily go into CMS Config -> Page Map -> Check-in and edit the Search block settings there.

![screenshot 2016-02-01 10 00 53](https://cloud.githubusercontent.com/assets/1210933/12720856/d61cfff6-c8ca-11e5-9ce8-e0c608627323.png)

**Comment by edmistj** [comment]
Thanks that is much easier. I updated the v4 and v5 docs.
