### ISSUE TITLE
Set Page Title

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1373]
When using the Set Page Title feature on the Event Item Occurrence block, it sets the page title to 'Event' no matter what event is listed. http://alpha.rockrms.com/page/5358?EventOccurrenceId=2

**Comment by JayGreentree** [comment]
This is in the setting for the calendar block

**Comment by JayGreentree** [comment]
I am also seeing this now that I've looked deeper into the original issue.
