### ISSUE TITLE
Calendar Lava files missing in Rock theme

### ISSUE THREAD

**Issue by JayGreentree** [SparkDevNetwork/Rock#1374]
It appears that the lava files are missing in the Rock dashboard theme. I copied them from Stark into  
         /Themes/Rock/assets/lava 
but still get 

```
    Liquid error: LavaFileSystem Template Not Found 
```

**Comment by azturner** [comment]
@JayGreentree The DashboardStark theme is intended for a very specific set of blocks/pages/layouts, and not really as as a theme to use with normal Rock or public web functionality. It has limited layouts, etc. Closing this for now, but if you feel this is still an issue, can you give more details on the use case you are using and which blocks you are trying to use. Thanks.
