### ISSUE TITLE
Block Settings Require Selection Unnecessarily

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1376]
When using a number of blocks, such as 'Login', there are fields that are listed as required but, in fact, are not. They have a default setting if left blank that will kick in automatically. But when making changes to the block they force the user to select a page.

![image](https://cloud.githubusercontent.com/assets/7409839/12765931/ce2aceae-c9b5-11e5-954b-4da4ead49ca4.png)

**Comment by azturner** [comment]
Additional block fixed here: https://github.com/SparkDevNetwork/Rock/commit/b6acb13dc78a7120b63de00e7b30d2159a6a27c4
