### ISSUE TITLE
Check-In Configuration Schedule Category Selection

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#1379]
In 4.1 all Check-In Group Categories are sharing the same Schedule Category.

I.e. I'm not able to select a different Schedule Category per Check-In Group Category.

**Comment by bwitting** [comment]
I'm seeing this behavior too

**Comment by azturner** [comment]
@treyhendon @bwitting  I'm not sure I understand exactly what the issue is. Can you provide more details (i.e. which screens/options, etc). This is a short video of what I tried to do to reproduce what I thought you might be referring to...
https://drive.google.com/file/d/0B2ElKd3uDxuIU05xTXE5bVhKaFU/view

**Comment by treyhendon** [comment]
Sorry about that!  Here's a video explaining.
Thanks!
https://www.dropbox.com/s/mhe3p0z0h2cqjxu/check-in_schedule_issue.mov?dl=0

**Comment by azturner** [comment]
@treyhendon The Schedule category at the top of page is really just a current view filter, it's not something that is "saved" with the checkin category.  So when you go to the different check-in groups, it's just remembering the last view, but if you switch to the other schedule category view, the selection should still be there. Does that make sense.

**Comment by treyhendon** [comment]
Oooo.  It does.  So sorry to waste your time!

**Comment by bwitting** [comment]
Ah, my issue is different then. I'll post info tomorrow. Thanks

**Comment by bwitting** [comment]
I was trying to figure out how to describe my issue, but @azturner fixed it in a0b6bfd.
