### ISSUE TITLE
4.0+ Update Group Members Deny Group View

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1381]
There are at least two records I've found of people that cause any group they are in to become inaccessible. Viewing the group provides this error until they are removed.
![image](https://cloud.githubusercontent.com/assets/7409839/12855038/f9f1daa8-cbf1-11e5-97eb-6c2fcf36ed7a.png)

**Comment by bwitting** [comment]
@BelAirIT We've seen this too, Make sure the records who cause this have a Non-NULL ConnectionStatusValueId

**Comment by BelAirIT** [comment]
Thanks @bwitting updating all the records with NULL values fixed the issue.
