### ISSUE TITLE
HTML in Email Template Text Version

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1384]
If you attempt to save an Email Template with a HTML tag in the text version of the message the template will not save but no error message will be produced.

**Comment by azturner** [comment]
@arranf , I couldn't reproduce this. Any time I enter HTML into any of the fields, it shows this message...
![image](https://cloud.githubusercontent.com/assets/548180/13078949/f334f85e-d47e-11e5-88ad-0db6e984fc84.png)

**Comment by nairdo** [comment]
@arranf are we OK to close this issue now?

**Comment by azturner** [comment]
@arranf , Closing this. If it's still an issue, please re-open.
