### ISSUE TITLE
Image / File API Design

### ISSUE THREAD

**Issue by jbaxleyiii** [SparkDevNetwork/Rock#1386]
After a few days of toying around with some ideas and test, I've determined using ~/ImageUploader and ~/FileUploader aren't possible from remote applications.

All in all, I think thats a great thing. Since they aren't part of the API, if they worked from remote locations, anyone could hijack your application and start uploading whatever they wanted which would be awful. We still want the benefit of users being able to choose their file / image storage methods so here is what I'm thinking might work. I'm 1000% open to ideas, this may be the wrong direction.

# Use Case
#### Client
An application (native or web), that posts an image or file to update a users avatar, add a file, upload a video (in the future), etc.

#### Server
An application with image / file manipulation abilities (like resizing, bluring, etc) uploads corresponding binary as a spoofed client side multipart form

## Endpoint
| Method | Relative Path |
|:---------- |:------------------ |
| POST | `/api/BinaryFiles/Upload?fileTypeGuid={fileTypeGuid}&fileId={fileId}` |

## Sample Client Post
```javascript
var input = document.querySelector('input[type="file"]')

var data = new FormData()
data.append('file', input.files[0])

fetch('https://rock.newspring.cc/api/BinaryFiles/Upload?fileTypeGuid={guid}&fileId={currentUsersPhotoId}', {
  method: 'post',
  headers: { "Authorization-Token": "client-token" },
  body: data
})
  .then((response) => {
    return response.json()
   })
  .then((id) => {
    console.log(id)
  })
```

## Sample Server Post
```javascript
// this would look the same as the client on Rock's end, but can be done using the methods explored here https://github.com/rfrench/poster
var poster = require('poster');

var options = {
  uploadUrl: 'https://rock.newspring.cc/api/BinaryFiles/Upload?fileTypeGuid={guid}&fileId={currentUsersPhotoId}',
  method: 'POST'
};

poster.post('file.jpg', options, function(err, data) {
  if (!err) {
    console.log(data);
  }
});
```

cc @dcs619 @benwiley @edmistj @azturner @mikepetersonccv

**Comment by dcs619** [comment]
@edmistj Any feedback on this?  We're going to look at implementing a solution next week.

**Comment by edmistj** [comment]
@dcs619  Looks good to me.

**Comment by dcs619** [comment]
@jbaxleyiii you should be able to close this issue now :boom:

**Comment by edmistj** [comment]
Thanks for the great addition to the API!

**Comment by jbaxleyiii** [comment]
@dcs619 @edmistj im going to run a few tests of this with our app and then I'll close this out!

**Comment by jbaxleyiii** [comment]
@edmistj @benwiley was able to confirm this works great!
