### ISSUE TITLE
Group Requirements Job Failing: Exception when calculating group requirement (Nullable object must have a value.)

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1389]
When the Group Requirements job runs, it fails with a few hundred exceptions like this: 

```
Exception when calculating group requirement: Sexual Abuse Policy Required|The Collective Production Team (Nullable object must have a value.)
```

This requirement (Sexual Abuse Policy Required) is almost an exact copy of Background Check Still Valid, it just uses a dataview filtered on a different attribute. I looked in the AttributeValue table to make sure that there were no NULLs for this attribute (which shouldn't matter with the DataView anyways). There were not any NULLs, but there were a lot of '' - removing those didn't fix the error either.

(@azturner -if you want to troubleshoot on our system:
Requirement: https://rock.newpointe.org/page/973?GroupRequirementTypeId=3
Dataview: https://rock.newpointe.org/page/145?DataViewId=1181&ExpandedIds=C714
Exception: https://rock.newpointe.org/page/182?ExceptionId=118837)

**Comment by azturner** [comment]
@bwitting, this looks like it is probably an issue with the _Expire In Days_ setting being null (even though it's not set to expire). If you temporarily update that requirement so that it can expire, set the _Expire in Days_ setting to zero, save it, edit again and unselect the _Can Expire_ I think it will resolve the issue.
We'll also fix that issue in the 4.3 update.

**Comment by bwitting** [comment]
Great, thanks @azturner!

**Comment by bwitting** [comment]
@azturner: Setting to 0 and saving it, then un-checking Can Expire didn't work. (and when I went back in and re-selected Can Expire, the text field was blank, not 0, so I think the 0 didn't get saved)

I just set Can Expire in 1000 days and I'll change it back after the fix. Thanks!
