### ISSUE TITLE
Parent Lava Doesn't Display Phone Number

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1390]
Created a new check-in merge field to display parent's cell phone numbers on the child's labels that print out. For some reason it only showed one parent's number. After deleting and re-adding the other parent's number it began working. Here's the lava code used:

 {% assign parents = Person | Parents %} {% for person in parents %} {{ person | PhoneNumber:'Mobile' }} {% endfor %}

**Comment by arranf** [comment]
@BelAirIT Hey, I can't reproduce this. Can you give me any more hints?

**Comment by BelAirIT** [comment]
Not sure what other information I can provide. Just had two parents with the same issue earlier this week, though. Both had mobile numbers in Rock but neither would print on the labels until I deleted their mobile number and then re-saved it. Couldn't find anything about their records that would explain the issue as other parents with seemingly the same information worked correctly.

**Comment by tommyprater** [comment]
I don't know if this would make any difference or if it's a completely different issue but I noticed after we imported our data that the phone numbers are in Rock and show up if I open the persons record but any where else in Rock when you have select a person and you get the little drop down of address and so forth the phone numbers do not show however the people keyed directly into Rock they show just fine.

**Comment by arranf** [comment]
@tommyprater If you used Excavator for that I think that's actually a bug with that. I've experienced it!

**Comment by BelAirIT** [comment]
Just checked in SQL and both parents that I found with the issue this week were imported using Excavator.

**Comment by tommyprater** [comment]
Well I can say this Im glad its not just me. @arranf do you happen to know a fix that I could run against the db to help resolve this? :)

**Comment by arranf** [comment]
@tommyprater I sure do, I've got it saved as a Github Gist somewhere. Do you mind @ing me here or in Slack in an hour or two so I don't forget to send it to you? I'm in the middle of something right now.

**Comment by arranf** [comment]
@BelAirIT Could you try testing with another family that have been imported with Excavator?

**Comment by arranf** [comment]
@BelAirIT I've recently written a blog post on [Shoulder the Boulder](http://shouldertheboulder.com/fixing-phone-numbers-post-excavator-import/) which outlines how to fix imported Excavator numbers. 

Could you do this and report back? I'll see if I can change the Lava here to be more verbose about what happens when a formatted number is missing.

**Comment by BelAirIT** [comment]
I had to get it fixed right away yesterday and ended up wandering the Internet until I found something similar to the article you mentioned. The SQL code on Shoulder the Boulder is exactly what I used to fix the problem!
