### ISSUE TITLE
Corrupted Excel Exports on some Grids w/ Person Entities

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1391]
On grids that export Person entities (like Tags), there is an error in Excel:

![2016-02-10 13_34_48-microsoft excel](https://cloud.githubusercontent.com/assets/1859094/12957615/96016d66-cffb-11e5-9e22-6c66355bf97d.png)

If Protected View is enabled in Excel (on the 2016 Win version anyways), the workbook won't open at all.  If Protected View is turned off, Excel will "repair" the workbook and show the following results:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error163440_01.xml</logFileName><summary>Errors were detected in file 'C:\Users\bwitting\Downloads\RockExport (2).xlsx'</summary><repairedRecords><repairedRecord>Repaired Records: Table from /xl/tables/table1.xml part (Table)</repairedRecord></repairedRecords></recoveryLog>
```

**Comment by swedd** [comment]
Excel 2010 reported:
![capture000101](https://cloud.githubusercontent.com/assets/1100235/13089757/655240e2-d4af-11e5-8c5e-eff30cfc75c3.PNG)
Excel said 'opening in protected view'. The Excel workbook then opened with the following window:
![capture000102](https://cloud.githubusercontent.com/assets/1100235/13089828/c9b8c72c-d4af-11e5-8264-c0d099b3ac80.PNG)
Clicking on the 'log file listing repairs' gave me:
-------------
<?xml version="1.0" encoding="UTF-8" standalone="true"?>
-<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<logFileName>error071960_01.xml</logFileName>
<summary>Errors were detected in file 'D:\Users\derekm\AppData\Local\Temp\RockExport.xlsx'</summary>
-<additionalInfo>
<info>Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.</info>
</additionalInfo>
-<repairedRecords summary="Following is a list of repairs:">
<repairedRecord>Repaired Records: Table from /xl/tables/table1.xml part (Table)</repairedRecord>
</repairedRecords>
</recoveryLog>
----------------

**Comment by edmistj** [comment]
Updating to EPPlus v 4.0.5 did not solve issue.

**Comment by TheCoreyHall** [comment]
I have a client on 9.4 who is receiving this error when attempting to export Dynamic Data block results to excel. This issue is the only reference to it that I can find here. Has this been reintroduced?
