### ISSUE TITLE
Merge Templates Glitch when using Tables in Word

### ISSUE THREAD

**Issue by hillsideassembly** [SparkDevNetwork/Rock#1396]
In this example, my dataset from Rock has 24 rows.  If I set up a merge template in Word and add some Lava at the beginning such as:
{{ Row.Campus.Name }}
{{ 'Now' | Date:' MMMM d, yyyy ' }} 

Then I create a table and put my lava rows in there to merge, the Lava I put before the table will not merge if the table in your template has either **less, more, or the same** amount of rows as the amount of rows I have of data in Rock.  In the template pictured, the {{ Row.Campus.Name }} and the date below that will not merge but will stay as they are written now.  I only have 20 rows of lava in my table.
![notwork](https://cloud.githubusercontent.com/assets/6493158/13023928/ae96eb80-d1b3-11e5-82c9-f16694eb34f4.png)

If the table in my template has **less** rows than the amount of rows in Rock that I'm trying to merge AND I put another row of lava below the table in regular text (I separated the columns with tabs), then the lava I put above my table WILL merge.  In this template below, the {{ Row.Campus.Name }} and the lava date below that merge fine.  This table has 23 rows of lava.
![work](https://cloud.githubusercontent.com/assets/6493158/13023929/b38e0b32-d1b3-11e5-92d0-f9237b6ab4ca.png)

If I put the **exact** number of rows in my template as I have in my report in Rock, and still have that row of text below the table, I will get a completely blank document, other than the table.  Below is the output of this kind of template. This table has 24 rows of lava (there is an additional row for the title).
![blank](https://cloud.githubusercontent.com/assets/6493158/13023999/7aa12344-d1b4-11e5-991b-a991dcf8f748.png)
 
Ideally, it would be good to be able to put more than enough rows of data below the table so that they are all merged into one table.  The only way I've found to get Lava to merge when using a table in Word and putting more rows than the amount of data I'm trying to pull from Rock, is to include the lava I want to merge, in this case {{ Row.Campus.Name }}, in a row of the table that has other lava in it already.

**Comment by mikepetersonccv** [comment]
@hillsideassembly I was able to fix most of this.  It will now work to have Lava fields outside of the table as long as they are Global merge fields ("Row" merge fields can't reliably get merged when they are both in a table and outside of a table).  You might want to consider using an HTML Merge Template if you need to do a mix of tables and other elements in the same doc :)
