### ISSUE TITLE
Placing admin toolbar as top most layer.

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1397]
When Page Zones are displayed they appear on top of the Admin toolbar. Depending on where the page zones are on the page this could keep the admin from selecting an option from the admin toolbar (they would have to scroll to the very bottom of the page to get outside the page zone or refresh the page). If the admin toolbar can be the top most layer when it appears this would correct it.

![screen shot 2016-02-13 at 11 03 04 am](https://cloud.githubusercontent.com/assets/5738650/13028868/614499b6-d241-11e5-99b1-36ac37066781.png)

**Comment by JayGreentree** [comment]
I have noticed this as well. It has to do with css but I can't figure it out at the moment.

**Comment by BEGamache** [comment]
It is the z-index in the css. Under theme.css the Z-Index for .zone-instance.outline (1049) and zone-configuration (1000) are greater than the z-index of #cms-admin-footer (999). When you set the admin footer to 1049 or 1050 it will be placed on top of the page zones.
