### ISSUE TITLE
Tag deletion bug - wrong record gets deleted

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1398]
I'm able to replicate this reliably on 4.1:
1. Go to People | Tags | Organizational Tags and click on an org tag.
2. People are by default displayed in the order they were added to the tag. Deleting a record from this state works as expected.
3. Sort the list by Last Name and delete the first record. 
4. Instead of deleting the record you clicked, the record originally in its place (step 2) is the one that gets deleted.
I haven't tested but assume this happens no matter what column you sort on... the deletion appears to happen in the original list order, not the sorted one.

**Comment by swedd** [comment]
Confirmed. Sorted on multiple columns and was able to confirm. Happens in both Org Tags and Personal Tags.
