### ISSUE TITLE
Group Finder Deletes Details Setting

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1403]
When specifying a details or registration page under Linked Pages, the block resets back to blank after a page refresh.http://alpha.rockrms.com/page/5384

**Comment by BelAirIT** [comment]
Logged in users seem to still be directed to the correct pages while non-authenticated users get a 404 error page. Another strange behavior is that deleting the Group Detail block from the page specified in the Group Detail setting of the Group Finder block causes it to send the user on correctly.

**Comment by matthewmeekins** [comment]
I've seen this behavior as well on 4.3. However, I had a page already setup before the update and it still works even though the page settings are blank.
