### ISSUE TITLE
[EN] Campus Picker includes inactive campuses

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1413]
Campus Picker and Campuses Picker both include campuses that are inactive.  This presents an issue for Registration instances where an upcoming/inactive Campus launch would show as an option.

**Comment by bwitting** [comment]
We just did this in all places where we need a campus picker: 
``` ... var campusi = CampusCache.All().Where(c => c.IsActive ?? false); ... ```
New family block, registration, campus context selector, etc.  I've never done a pull request to the Rock project, time to figure that out I guess

**Comment by azturner** [comment]
Updated the Registration Entry block to only display active campuses ( https://github.com/SparkDevNetwork/Rock/commit/d44963aac3b535dd63fc1e2038f390011df2c50b ). Still need to update the Campus and Campuses field types & attributes to include optional setting for specifying if inactive campuses should be included.
