### ISSUE TITLE
The "Add Comment" hyperlink is missing from Rock Ask answer block when viewed on Chrome browser on iPad

### ISSUE THREAD

**Issue by leehockhin** [SparkDevNetwork/Rock#1430]
Sample of missing "Add Comment" hyperlink

![img_1129](https://cloud.githubusercontent.com/assets/17799991/13723812/33f759b4-e8ab-11e5-8669-c5bf840301a3.PNG)

**Comment by nairdo** [comment]
I can't see it from your screenshot, but are you certain you are logged in on the iPad?

**Comment by JayGreentree** [comment]
I can see it on windows with firefox just fine

**Comment by nairdo** [comment]
The comments button will not show up until you've acquired enough community points.  This is done in order to keep people from making incorrect guesses which would tend to clutter the community Q & A (which a small problem we're beginning to see in the Slack channel).

**Comment by leehockhin** [comment]
Thanks Nairdo, you are right.  I was a bit confused, as earlier I could not find a way to add comments to the answers given.  Then later, when I have sufficient community points, I did not log in at my iPad.  Everything explained.

**Comment by nairdo** [comment]
You're welcome. I'm glad I could help!
