### ISSUE TITLE
Cannot Select Group to make block work

### ISSUE THREAD

**Issue by dcagnetta** [SparkDevNetwork/Rock#1431]
Hi

I setup a group viewer page but i cant set the Group property below to blank. I am forced to select an option which then only displays members of that one specific group.

The help says :...or choose to have group determined by groupId ...."

but this is not listed in any of the options.

![index](https://cloud.githubusercontent.com/assets/12990665/13726574/2ef6659c-e8d6-11e5-88b0-ddeb4c4b4a8e.png)

**Comment by azturner** [comment]
@dcagnetta , This was fixed in v4.2. If you are on v4.2 or later ( v4.4 has been released ), please re-open
