### ISSUE TITLE
Liquid Dashboard Widget GOAL not Displaying

### ISSUE THREAD

**Issue by dcagnetta** [SparkDevNetwork/Rock#1433]
Hi 

It also does not display my GOAL measures even though they are entered in

Thanks

**Comment by mikejed** [comment]
It's not perfectly clear from the interface, but the `Goal`, like the measure itself, is designed to be a series (a line), not just a "point in time".

Possibly this is new behavior (I'm confirming in v8 prealpha) but if you set one goal value in the past, and one goal value in the future, loading the `Liquid Dashboard Widget` will indeed show "today's" calculated value between the two, in addition to the most recent value in the past.

Here is how the metric entry page looks in my test:
![image](https://user-images.githubusercontent.com/6932047/38001418-882e4df4-31e1-11e8-888d-c012f3ac8009.png)

And here is the default output from the `Liquid Dashboard Widget`:
![image](https://user-images.githubusercontent.com/6932047/38001440-a5436226-31e1-11e8-8bc4-0dfe57cf9b73.png)

(it's useful to note that today's date is 3/27, so those values make sense).

I believe the metrics, and this block, are working as intended. Please let us know and reopen the issue if you disagree.
