### ISSUE TITLE
Misspelled Copy

### ISSUE THREAD

**Issue by SaraBaker** [SparkDevNetwork/Rock#1434]
One of our volunteers noticed that some copy wasn't correct. It seems like "can" should be "can't". Here is the linking page: http://www.rockrms.com/Rock/Features and a screenshot: 
![unnamed](https://cloud.githubusercontent.com/assets/7659455/13751188/5de1b35c-e9df-11e5-9b37-1945a9f09582.png)

**Comment by edmistj** [comment]
Thanks! Fixed now.
