### ISSUE TITLE
Connection Request Refused If Not Logged In

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1440]
When signing up for a connection opportunity the request will just pinwheel or do nothing if the user isn't logged into the site.

**Comment by bwitting** [comment]
Hey Jeremy, we are in the process of setting up connections right now and are testing extensively - and we have never had this issue.  What version of Rock are you running?  Do you see any exceptions in the Exception Log?

**Comment by BelAirIT** [comment]
Seems to happen on our version (4.3) and the alpha.rockrms.com site (4.0). Tried it on Firefox and Chrome.

**Comment by bwitting** [comment]
I see there is a ```Nullable object must have a value. ``` in the exception long on alpha.rocksms.com. I wonder if that has been fixed in 4.4 (We're running 4.4, but I don't see anything about it in the Release Notes)

**Comment by BelAirIT** [comment]
Yep. I see the error message too. Just updated to v4.4 and stilling getting the error in the exception log and no progress on the page.

**Comment by bwitting** [comment]
Wow, interesting.  I'll keep trying to reproduce it here too.

**Comment by azturner** [comment]
This was occurring prior to v4.5 if organization only had one campus. Was fixed here: https://github.com/SparkDevNetwork/Rock/commit/9a4aa811e1eafff2f7fdd2e01bc2fb354cda8d41
