### ISSUE TITLE
Merging records it looses the Bank Account tied to the individual

### ISSUE THREAD

**Issue by tommyprater** [SparkDevNetwork/Rock#1445]
When I merged some individuals it looses the bank account tied to them. I went in the database and see the bank account still there but when the records were merged it didn't update the PersonAliasId in the FinancialPersonBankAccount.

**Comment by azturner** [comment]
@tommyprater, PersonAliasIds shouldn't actually get updated after a merge. In fact, the Person Alias concept was created primary for the purpose of making merging much more streamlined. After a merge, there is only one person record, but there are still two person alias records that now both point to the same person record.  But all of the other tables that have a foreign key reference to person alias don't need to be updated. I'm closing this for now, but if you think there's still an issue with bank accounts after the merge, please feel free to re-open.
