### ISSUE TITLE
Template fails when logged out of website

### ISSUE THREAD

**Issue by jmorrissette** [SparkDevNetwork/Rock#1449]
Perhaps this is a user error or configuration, but when we log out of our rock website the template doesn't apply.  When we log in, the template appears.  

**LOGGED IN (IMAGE)**
![loggedin](https://cloud.githubusercontent.com/assets/17603185/13992213/3bbd49d8-f0e9-11e5-902c-938b504f0a2d.PNG)

**LOGGED OUT (IMAGE)**
![loggedout](https://cloud.githubusercontent.com/assets/17603185/13992212/3bbd138c-f0e9-11e5-8208-50310384803d.PNG)

**Comment by JayGreentree** [comment]
When I try to look at your css it redirects back to the login page so it seems there is a permissions issue.

(note: I am not an official rock dev)

**Comment by jmorrissette** [comment]
We gave IUSR read access to the themes folder.  Not sure that is a 100% accurate fix, but it worked so I'm not arguing with the results.
