### ISSUE TITLE
Adding People with a Birthday in the Future Creates Centenarians 

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1458]
**Steps to Reproduce:**
1) Edit a family
2) Add a child with a birthdate of tomorrow using the datepicker

**Expected Result**
The child would have a birthdate of tomorrow or an error message would appear informing the user they've picked a birthdate in the future

**Result**
The child is added with a birthdate from a hundred years in the past and consequently an age of 99.

**Comment by arranf** [comment]
Looks like this is by design. What's the reasoning?
https://github.com/SparkDevNetwork/Rock/blob/55a8ddecb88a2047dc373b4d96d933441e46688c/RockWeb/Blocks/Crm/PersonDetail/EditGroup.ascx.cs#L559

**Comment by azturner** [comment]
I'm curious how often you know the dates that children will be born in the future?
:)

**Comment by arranf** [comment]
I guess you don't get much Dr. Who over in the states? ;)
Just kidding. I figure it'd better to be provide some sort of error message
to the user rather than adding rogue definitely incorrect information to
the system.

**Comment by garrettjohnson** [comment]
Any plans for getting birthday validation going? The feature has been super helpful in development, but we've already had staff add a few 99 year olds to our test environment when they're adding children 😄

**Comment by bdeneal** [comment]
That would be helpful! I found one kid whose birthday ended being the year 0208... So needless to say he was to old to check into his class.

Brian


On Aug 2, 2016, at 12:04 AM, Garrett Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Any plans for getting birthday validation going? The feature has been super helpful in development, but we've already had staff add a few 99 year olds to our test environment when they're adding children ?

-

**Comment by nairdo** [comment]
Internal note: similar logic currently exists in these blocks: PublicProfileEdit, AddGroup, EditPerson, EditGroup, AccountEdit.
