### ISSUE TITLE
Post-save workflow triggers not working

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#1463]
I have post-save workflow triggers set up that when one metric gets updated, another one adds a new value with the sum of a couple metrics. (Auditorium Attendance per campus and weekend totals) The triggers stopped working somewhere in the 3.5>4.0>4.1 updates. I tried duplicating it on the demo site and had the same results. There is nothing in the exception logs and the workflows work fine if I manually run them.

**Comment by arranf** [comment]
@KelleyLangkamp Is this still an issue for you?

**Comment by KelleyLangkamp** [comment]
Honestly, I'm not sure. Most of those workflows had to do with updating metric values. I changed them all over to schedule metrics running SQL queries. So I haven't tried them recently.

**Comment by cabal95** [comment]
I'll close for now then as I haven't heard of a report on this lately and it's been a few versions. If the problem comes up again feel free to re-open. We are trying to get better about not letting issue reports get stale for this long in the future.
