### ISSUE TITLE
[EN] Filesystem provider attempts to create null directory

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1471]
Problematic code [here](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Storage/Provider/FileSystem.cs#L50).  In theory, directoryName should *never* be NULL since the default subfolder is set [here](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Storage/Provider/FileSystem.cs#L151).

However, when using the FileSystem provider outside an IIS context, [this call](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Storage/Provider/FileSystem.cs#L122)  to HostingEnvironment.MapPath will always return null. 

@mikepetersonccv any thoughts?  Should we set the default subfolder in the `SaveContent` method as well as `GetRelativePath`?

[Here's](http://stackoverflow.com/questions/8740498/how-to-unit-test-code-that-uses-hostingenvironment-mappath) one suggested solution but I don't think it needs to be complicated.

**Comment by mikepetersonccv** [comment]
It looks like there were some changes here to address something, but not necessarily the issue of using it outside of an IIS Context
https://github.com/SparkDevNetwork/Rock/commit/3e0266fcd2a42a9914b886ebb92972af5601bdac

This solution might work http://stackoverflow.com/a/485836

@azturner any thoughts?

**Comment by dcs619** [comment]
@mikepetersonccv I can't verify this, but I don't think that solution would work for Virtual Directories (#1181), which is why we're calling HostingEnvironment.MapPath.  I think I have a simpler fix, testing it now.
