### ISSUE TITLE
Manage Workflows Available to Everyone

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1473]
Users without Edit permissions to a workflow are still able to see and interact with the Manage icon on the Workflows page.

**Comment by azturner** [comment]
@BelAirIT , Not exactly sure which icon you are referring to as the "Manage Icon". On the Workflow Navigation block (Workflows page), there is a "list" icon to the right of workflow type that is used to list all of the workflows for that type. This icon is only displayed for users that have "View List" security to that workflow type.

Once they are viewing the list, there are two action icons on the right of grid. First icon is used to view the details, second is to delete. If user has "View" access to workflow type, they can view the details, but they need "Edit" access to delete. Once they are viewing the details they can only edit/save if they have "Edit" rights to the workflow type.

Is there still an issue with how this is working?

**Comment by BelAirIT** [comment]
![image](https://cloud.githubusercontent.com/assets/7409839/14769927/aee09e0e-0a18-11e6-9c9d-45c304feb4d4.png)

**Comment by azturner** [comment]
@BelAirIT That is the "List" icon I mentioned. It is displayed for users' that are authorized for "View List" access to the workflow type. If you don't want users to see that, make sure they are not authorized to "View List". This is an additional action that can be secured on workflow types, just like View, Edit, and Administrate.

**Comment by BelAirIT** [comment]
Ah, I see. Then it looks like the Workflow Type is inheriting permissions to all workflows below it of Allow to All Users. 
![image](https://cloud.githubusercontent.com/assets/7409839/14827720/8c92aa5a-0b98-11e6-8b3d-82c0aa7cde48.png)

This is odd because the Workflow Type, in this case Requests, doesn't have a ViewList option.
![image](https://cloud.githubusercontent.com/assets/7409839/14827737/a2865104-0b98-11e6-9fe6-938b11e0d3a3.png)

**Comment by azturner** [comment]
@BelAirIT The "Requests" is actually a category and categories don't have the "View List" action. The Workflow Types don't inherit permissions from their category, but they do all inherit from the base WorkflowType entity. So if you want to set permissions for all worktypes to inherit, you can do it there... `Admin Tools > Security > Entity Administration` and edit security for the `Rock.Model.WorkflowType` entity. This will have the "View List" action.

**Comment by BelAirIT** [comment]
Well, that does make sense. It's a rather hidden option though. It also begs the question of why All Users would or should have ViewList permissions. Maybe I missed it but I don't think that was the default in older versions of Rock.
