### ISSUE TITLE
New migrations being stored in a separate folder

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1474]
There are several migrations in [rock.migrations](https://github.com/SparkDevNetwork/Rock/tree/develop/rock.migrations/Migrations) that are being tracked separately from [Rock.Migrations](https://github.com/SparkDevNetwork/Rock/tree/develop/Rock.Migrations/Migrations).

Capitalization matters :smiley_cat:

**Comment by dcs619** [comment]
Just noticed the same issue with [rock.payflowpro](https://github.com/SparkDevNetwork/Rock/tree/develop/rock.payflowpro/bin/Release), [rock.rest](https://github.com/SparkDevNetwork/Rock/tree/develop/rock.rest/bin/Release), and [rock/Financial](https://github.com/SparkDevNetwork/Rock/tree/develop/rock/Financial). @azturner @mikepetersonccv

**Comment by azturner** [comment]
Yeah, I noticed a couple days ago that somehow the casing on some of my project names had gotten changed to lower case (when I couldn't find a migration on Github), not sure how/where that happened and haven't had time to figure out how to fix it in github yet. I have fixed the casing on all my local folder names though.

**Comment by dcs619** [comment]
See https://github.com/NewSpring/Rock/commit/dd3354bdeb2f3e41621bdaabe9b8296d1a7b6795.  I looked for a way to move the files while preserving history, but those files only have one commit so it didn't seem necessary.  Removing them and re-committing to the repo made it show up on the correct place.

**Comment by azturner** [comment]
Thanks @dcs619. I've removed and re-added them all.
