### ISSUE TITLE
Person Attributes (/page/71) does not wrap long attribute names

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1475]
Discovered a usability/cosmetic issue where very long attribute names do not wrap in the UI on the configuration page and it blows the Attribute Category and delete button off the screen, necessitating a horizontal scroll.
![person attributes _ rock rms](https://cloud.githubusercontent.com/assets/3903408/14333658/7c9b571a-fc15-11e5-95df-f92fd857a1d9.png)

**Comment by dcs619** [comment]
Sounds similar to #1401, removing the ItemStyleWrap in that case fixed the issue.
