### ISSUE TITLE
Don't redirect to top Check-in Configuration after adding a Check-in area

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1481]
After adding a check in area to a check-in configuration, rock redirects to the top level Check-in configurations list page. It would make sense to refresh the page to show the newly created check-in area after the save instead.

**Comment by azturner** [comment]
@garrettjohnson , Not really sure I understand what this issue is? Sounds like after saving a check-in configuration, you'd like to see some sort of read-only/view-mode display of the configuration you just saved rather than returning to the list. If that's the case, that block doesn't really provide that view. It is only used to edit the values. Can you provide any more details?

**Comment by garrettjohnson** [comment]
@azturner I don't think it should be a separate view block, but I think nested data edits might warrant different "after save" UI treatment from other record types.

When a user edits a single person, family, or group, it redirects back to the show page after save, and that page reflects the changed data. But, if a user is modifying nested data, like check-in areas and sub areas, it's jarring to be sent back to the list page after the save because there's no indication that the change was successful, or why you ended back at the top level edit screen. 

I'm thinking mentally a user isn't modifying that top level item, they're working with that deeper level checkin area/group/record/etc.

**Comment by azturner** [comment]
@garrettjohnson Makes sense. Just wasn't sure if there was an issue or bug that you were reporting. 

We're actually updating the check-in configuration blocks quite a bit for v5 of Rock and one of the new features will be exactly what you mention.. much more granular editing/saving of configuration information: https://github.com/SparkDevNetwork/Rock/commits/feature-dt-checkin

Closing this as an issue, as the enhancement request is being addressed in new feature.
