### ISSUE TITLE
[EN] Toggle-able, auto-generated disallow/allow Robot.txt file for external website.

### ISSUE THREAD

**Issue by RyannosaurusRex** [SparkDevNetwork/Rock#1482]
There are several scenarios where organizations may want to have Rock's external website (or other generated sites) publicly available on the internet, yet be able to show/hide those to search engines.  Similar to Wordpress and other CMSes, it would be great to have the ability to toggle allow/disallow for the site from the Rock back-end.

Use Case: Initial move to rock where you have beta.ourchurch.org that you want hidden until you're ready to make the move, then you want the site allowed once changed to www.ourchurch.org.

**Comment by edmistj** [comment]
Not quite the same as a robot.txt file there is a new feature in v5 that adds a 'Allow Indexing' flag to the site. When disabled it adds a <meta name="robots" content="noindex, nofollow"> tag the the HEAD of each page. There is a similar feature on each page also.

The robot.txt file would be applied to the entire Rock instance.

**Comment by edmistj** [comment]
Similar feature exists in upcoming v5.0
