### ISSUE TITLE
Add button not working on Business List Block on new another page

### ISSUE THREAD

**Issue by dcagnetta** [SparkDevNetwork/Rock#1489]
Hi
I added the Business List Block to the homepage but the add button does nothing when clicked.

It does however work on the on the default page where the block already is

Thanks

**Comment by JayGreentree** [comment]
You have to edit the block settings and point it to the business details page for the button to work.

**Comment by azturner** [comment]
@dcagnetta , As @JayGreentree mentions, this should just be a matter of setting the block property. If there is still another issue, please re-open.
