### ISSUE TITLE
Report Total Giving Date Ranges - To Date must be outside selection range 

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1490]
In Reports, on the field Total Giving, the date range is from the start date up to but not including the to date.  The to or end date must be OUTSIDE the selection range.  Is this intended functionality?  Maybe this is the way it's done in the States?  It works and is fine if you know it works that way, **but when I first used this I expected to enter the start and end dates as INCLUSIVE dates, with anything outside those dates not to be included.**

So the date range (dates in New Zealand format) of 1/4/15 (1 April) to 31/3/16 (31 Mar) I expected to INCLUDE all of 31 Mar transactions.  But it doesn't.  The end date has to be set as OUTSIDE the desired range, as 1/4/16 (1 Apr) to pick up 31 Mar transactions.  

I think the end date should be inclusive.  This is more consistent with every other financial and accounting program I've used, and with date ranges on all reports I've ever written (a lot).

The same applies to the Giving Amount Person field (why the different name?) in Data Views.

**Report with end date set to 31/3/2016 does not pick up a transaction dated 31/3/16 11:59PM.**

![totalgiving1](https://cloud.githubusercontent.com/assets/4658177/14487100/ceea30d2-01b4-11e6-89d2-87c12b739250.jpg)

![totalgiving2](https://cloud.githubusercontent.com/assets/4658177/14487099/cee88ee4-01b4-11e6-800e-b09cb8834f2c.jpg)

![totalgiving3](https://cloud.githubusercontent.com/assets/4658177/14487104/d0626e48-01b4-11e6-9ea1-1dd86ee666c3.jpg)

**Report with end date set to 1/4/2016 DOES pick up the transaction dated 31/3/16 11:59PM.**

![totalgiving4](https://cloud.githubusercontent.com/assets/4658177/14487107/d415ef1a-01b4-11e6-88d1-ec9b68330bc9.jpg)

![totalgiving5](https://cloud.githubusercontent.com/assets/4658177/14487110/d7922636-01b4-11e6-8cc9-e37f261102a2.jpg)

**Comment by arranf** [comment]
@ElimAdmin I think this is intentional. [Here](http://www.rockrms.com/Rock/Developer/BookContent/16/16#datesandtimes) in the developer guide it describes the general pattern as inclusive start dates inclusive and exclusive end dates just as you described. 

A potential way to 'fix' this issue would be to add a hint to the date range explaining how the filtering works.
