### ISSUE TITLE
Downloading a Merge Doc does not retain doc name

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1493]
Editing a Merge Document entry, and clicking inside the Template File box to download the file, correctly downloads the file, but does not correctly retain the doc name.

I have a doc named 'Donations Receipt 2016.docx'.
It downloads as just 'Donations.'
Not a biggie but would be nice if the download had the correct file name.

![docdownload1](https://cloud.githubusercontent.com/assets/4658177/14492502/bd14b0fc-01d3-11e6-846a-f108f1ac92e8.jpg)

**Comment by azturner** [comment]
@ElimAdmin , I wasn't able to reproduce this in v4.5 (tried in IE and Chrome)...

![image](https://cloud.githubusercontent.com/assets/548180/14761868/386dc14a-0921-11e6-834f-c5fae648b95b.png)

Is this the same place you are trying?

**Comment by azturner** [comment]
@ElimAdmin , Closing this issue for now as we wern't able to reproduce. Feel free to re-open if it's still an issue for you.
