### ISSUE TITLE
Twilio Code in Rock Documentation - Boxes will not scroll

### ISSUE THREAD

**Issue by pastakeith** [SparkDevNetwork/Rock#1495]
My tech guy is telling me he can't access the whole code for the twilio php or asp (unsure) code to install it. He can see the code, but the scroll bars aren't working. Help?

**Comment by arranf** [comment]
Hey @pastakeith. You shouldn't need to install any code to get Twilio working if you have a Rock instance already setup. Rock doesn't use any PHP and is a ASP.NET based project.

Could you share what code you are referring to?

I've taken a screenshot of the part of the documentation related to Twilio. You can find a live copy of this [here](http://www.rockrms.com/Rock/BookContent/8/62#integrations).
![Twilio with Rock RMS](https://cloud.githubusercontent.com/assets/8703222/14527082/76257c82-023f-11e6-915f-aefea68eaa1e.png)

**Comment by azturner** [comment]
@pastakeith , Closing for now, but if you have any more details on an issue, please feel free to re-open.
