### ISSUE TITLE
Database optimization of known/implied groups

### ISSUE THREAD

**Issue by bradbamford** [SparkDevNetwork/Rock#1502]
Currently, for every **Person** in the database there are 4 additional records created unnecessarily. 
A Known Relationship **Group** and a **GroupMember** record with the person as the owner.
An Implied Relationship **Group** and a **GroupMember** record with the person as the owner.

After importing 250K Persons with no known or implied relationships there are 1 million extra records added for essentially nothing.

This should be optimized, these records shouldn't be required to exist until there are known or implied relationships.

**Comment by nairdo** [comment]
This is the correct behavior and it's by design. (Sorry Brad, it's just because you just don't have a clear understanding of how these relational records work.)

**Comment by bradbamford** [comment]
Thank you Nick for responding. I understand it's the correct behavior by design, and you are correct that I don't have a clear understanding. Can you elaborate why the Groups can't be created the first time someone other than themselves are in the Groups?

**Comment by nairdo** [comment]
Sorry for being so terse initially. We just we don't have any spare time to justify design decisions here, and we want to keep this issues list for actual bugs.

Think of the Known Relationship and Implied Relationship group types just like the Family group type. All three 'expensive' (relatively speaking) operations are done at create time because a person is only created once. We do not want to have to check if each of the three groups are missing (i.e., needing to be created) after every person-group operation since that would be even more costly.

**Comment by edmistj** [comment]
Adding to Nick's comment having to check for a 'Known Relationship' group every time you wanted to add a new relationship via SQL would be a bit of a pain.

**Comment by bradbamford** [comment]
**Thanks for explaining the thought process, I can respect that and this certainly isn't a bug**. 

My thoughts were looking at the percentages of Person records that would have known or implied relationships. Currently, in our case over 95% of people would not have GroupMembers in either. So for us (with 250K Person Records), that's 1 million+ records in the database that provide no value to the system other than taking up resources for a coding convenience. For us, that's more expensive than checking for null after a .FirstOrDefault() query or similar. 
Also I'm new to Rock, so I could very well be completely wrong here, but it seems that most of the queries would be while viewing the the individual's Person page. Currently, you have to query across 2 tables to determine if any GroupMembers of known/implied persons (Group and GroupMember). If the groups didn't exist there would be no need to query GroupMembers table to determine if anyone 'else'  is in the group.

**Thanks again, for taking time to share your thought process above, that goes a long way in any open source community we are all together are apart of.**
