### ISSUE TITLE
Built in workflows improperly persist

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1509]
I've noticed that most if not all of the built in workflows -- Person Data Error, Photo Request, DISC Request, Backgroung Check -- seem to persist even when the user aborts the request. On any of these, if you simply start the workflow (eg via the actions menu on a user) and then when presented with the workflow UI navigate away, the expectation is that the person did not intend to complete or process the workflow. However, in each case an active workflow is created and over time you can get hundreds of "abandoned" yet active workflows cluttering up the system.

I think the issue might be that in the workflows I've looked at, they're being persisted too early... in each case, prior to any UI (user entry form) and thus they persist when they should not. Perhaps just moving the persist action to be post-Entry form like the documentation suggests would fix this issue?

**Comment by azturner** [comment]
It's not quite as simple as persisting it later as they are getting and need to save the person entity from the person profile page before displaying the first form. 

A "Clean-up" activity could be added that is also activated on start that has a delay action, a workflow delete action with a filter that causes it to only run if a certain field is blank (i.e. not filed out), and a complete workflow action. (Spark Documentation Suggestion workflow does this).

**Comment by JimMichael** [comment]
Ok, thanks for the additional detail. In this case, I think the default workflows that ship with rock need to be modified by core with these "clean-up activities" as the out-of-box experience creates all sorts of orphaned workflows just by visiting (example) Person Data Error and then navigating away from the page. For a noobie poking around in Rock for the first time, this happens a LOT and it's then really confusing to find all of these work orders sitting in the system doing nothing, serving no purpose.
