### ISSUE TITLE
Person search doesn't work properly on people with blank spaces in their last name.

### ISSUE THREAD

**Issue by jreciomoreno** [SparkDevNetwork/Rock#1518]
The search doesn't work for people that have blank spaces in their last name if the search is performed only using the last name.

i.e. for a person called: Lara-Lyn Van Heerden  where:
First Name: Lara-Lyn
Last Name: Van Heerden

Searching only by last name Rock won't return any possible candidates.

**Comment by edmistj** [comment]
@jreciomoreno After talking on the phone Monday I couldn't stop thinking of how to fix this. Think this change will solve the issue (without causing any others)
