### ISSUE TITLE
Exception thrown in GroupListPersonalizedLava class

### ISSUE THREAD

**Issue by jreciomoreno** [SparkDevNetwork/Rock#1521]
Hi,

When saving a person profile and argument exception with the following message "An item with the same key has already been added" its being thrown in  GroupListPersonalizedLava.ascx.cs Ln: 115. located in the  RockWeb/Blocks/Groups.

Line 115 its no longer needed as in line 113 the current person its already being added to the mergeFields dictionary.

**Comment by mikepetersonccv** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/d493b852f3acc6b7d66d481f7ad56a36c89397e6
