### ISSUE TITLE
KeyValueList displaying wrong value

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#1522]
When displaying a KeyValueList attribute, the value always shows a defined value even when no defined type is set for the attribute.

**Comment by Tschrock** [comment]
To be clear, this is what I'm expecting;

Materials Needed:
Books: 7, Pencils: 4, Pens: 3

And this is what I get;

Materials Needed:
Books: Visa, Pencils: Inactive, Pens: Active

**Comment by edmistj** [comment]
How are you displaying the results? Workflow form, lava, etc? I'm a bit lost.

**Comment by Tschrock** [comment]
Anywhere the attribute is shown (not editable)

I set up an attribute without a defined type:
![capture5](https://cloud.githubusercontent.com/assets/2406499/15159110/dfe898f8-16c0-11e6-817a-b04ae74477ba.PNG)

And put numbers in for the value:
![capture6](https://cloud.githubusercontent.com/assets/2406499/15159117/ed5286a2-16c0-11e6-815d-93110dc621a0.PNG)

But it's showing the values as defined values instead of numbers:
![capture7](https://cloud.githubusercontent.com/assets/2406499/15159162/3188e438-16c1-11e6-97f7-bdaf55905713.PNG)
