### ISSUE TITLE
Delay Send Until is delaying by an additional 30min

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1523]
Have tested this on two different VMs, 4.5 and 4.6beta. If I create a communication and delay the send, the email "counts down" to the correct send time as expected, then just sits there pending until 30min after the future send time, at which point it is sent/delivered. I can observe my Send Communication job fire every 10min and it only seems to pick up the delayed message after 30min. This is repeatable and consistent across all of my Rock instances.

**Comment by nairdo** [comment]
@JimMichael, is your Send Communication job's "**Delay Period**" setting also 30 minutes or is it less?

**Comment by JimMichael** [comment]
Doh, yes it is! I guess I don't understand the purpose of that setting, though that certainly appears to be the culprit.

**Comment by azturner** [comment]
@JimMichael , this might help explain that setting. http://www.rockrms.com/Rock/Ask/Troubleshooting/Questions/602#a1219 It probably doesn't make sense though for the job to do the additional delay if communication was created in first place with a future send date/time.

**Comment by nairdo** [comment]
@JimMichael But thanks for testing that feature!  Keep up the great beta testing work!
