### ISSUE TITLE
Attendance History filter

### ISSUE THREAD

**Issue by ccofnow** [SparkDevNetwork/Rock#1524]
Both manually-entered (group toolbox or group viewer) attendance records AND check-in kiosk attendance records leave [EndDateTime] null.

On the "Attendance History" block, if you set any end date in the date range filter, it appears to exclude all records with no end time. If you leave the end date field blank, it will filter appropriately using [StartDateTime].

I don't know if it's a bug in the filter block, or if the attendance records should actually be logging an [EndDateTime], but there appears to be a bug somewhere between these two items.

**Comment by dcs619** [comment]
I can't speak for the date range filter block, but the EndDateTime field is there to provide (future) checkout capability.  We implemented that in [our version](https://github.com/NewSpring/rock-attended-checkin/issues/2) of check-in.
