### ISSUE TITLE
Group List Block Column Behavior

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1525]
I'm attempting to add a Group List block to a page to display only Serving Team type groups. The block works correctly on the person profile Groups tab and displays all the correct name, group type, role, etc. information. But when adding the same block below the original one (for testing), it hides necessary columns. Selecting a group from Include Group Types and the Display Group Path to Yes options causes the Name column to be hidden and no path displayed. But excluding all unwanted groups makes it show correctly.

![image](https://cloud.githubusercontent.com/assets/7409839/15225495/8def04f0-1833-11e6-9e66-14b65d215a97.png)

Also, checking any group in the Include Group Types causes the block to no longer honor the 'Name' field in the block settings and use 'Groups' as the title.
![image](https://cloud.githubusercontent.com/assets/7409839/15225477/77699010-1833-11e6-93a6-594eda0b412c.png)

**Comment by azturner** [comment]
@BelAirIT We fixed the first issue. For the second item, when you select a specific group type, the block will use the "Group Term" value of that group type. This is a value you can set in the Group Type Detail page (under Display Settings). If you select more than one specific group type, or just use the Exclude Group Type settings, it uses the name of the block.
