### ISSUE TITLE
Export to Excel- Children on dataview

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#1526]
When exporting to excel and you have a list of children's names on a data view it does not export them. 

![image](https://cloud.githubusercontent.com/assets/657005/15234647/823a2586-1879-11e6-8598-6960dad671a2.png)

**Comment by BEGamache** [comment]
Ran into this problem today as well. Any update on this bug?

**Comment by noahsbird** [comment]
We are having the same problem. To avoid the view above, we have to list children as though they were adults. Will someone please look in to this?
