### ISSUE TITLE
Plugin Migration does not extend DbMigration

### ISSUE THREAD

**Issue by cbump** [SparkDevNetwork/Rock#1528]
The Plugin Migration class should extend DbMigration so a lot of the standard functions are available such as CreateTable, AddForeignKey etc.

**Comment by dcs619** [comment]
@cbump have you tested this in multiple environments?  I'm fairly certain Entity Framework requires DbMigrations to be in order, which means you couldn't install a plugin at a later date (once other DbMigrations have been applied).

**Comment by cbump** [comment]
@dcs619 It doesn't change anything about the way the order of the plugins are installed.  It just allows the SQL that is applied by the migration to be generated from the base DbMigration functionality.  The plugin migration is actually still applied and tracked the same way.
