### ISSUE TITLE
Incomplete “pay dirt” confirmation message

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#1533]
From Trey: I just noticed something kinda small, but a bug I guess.  The “pay dirt” confirmation message was incomplete after running 4.5 installer.

![eureka](https://cloud.githubusercontent.com/assets/383807/15442818/5b4729c2-1e98-11e6-8001-139964fec5cf.png)

It simply says:  “Update completed successfully… You’re not running  .”  So it’s missing the version number confirmation.

**Comment by nairdo** [comment]
I took a quick look at this and confirmed the problem (I also didn't see any obvious reason as to how/why this was happening). The block is expecting to use the "Title" field in the 1.4.5 nuget package and it appears that field does have a value.

**Comment by arranf** [comment]
:+1: for the use of 'Claim It'

**Comment by azturner** [comment]
Fixed here: https://github.com/SparkDevNetwork/Rock/commit/f58c31778a195317ea959aa9b7a5c0e2b2ae46c2

The update will be included in v5.0 which means first time fix will be evident is next update (after v5.0).
