### ISSUE TITLE
Group Participation field type

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#1537]
When making a report - and using the Group Participation field type - and selecting the top level group - it shows inactive groups under it.

**Comment by azturner** [comment]
@austinspooner The GroupParticipation report field asks for a Group dataview and then simply lists any groups from that dataview that the person belongs to (with a given status). If inactive groups are appearing, you should just be able to modify the group dataview (or use a different group dataview) that does not include inactive groups.

If you think there is still an issue, feel free to re-open.
