### ISSUE TITLE
[EN] Limit ConnectionOpportunity and ConnectionActivities lists in Workflows by Type

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1541]
It would be nice to be able to limit ConnectionOpportunity and ConnectionActivities attributes in a workflow by Connection Type.  (For example, we have a workflow that deals only with the Volunteer connection type, but if we put ConnectionActivities on a form, the user can select an activity from any type of connection in the system, not just volunteers)

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1126098519063343">image.png</a>

**Comment by edmistj** [comment]
So something like this when defining the attribute. Makes a lot of sense!

![image](https://cloud.githubusercontent.com/assets/548178/15547936/fac78242-225a-11e6-9045-f5dff801f4f9.png)

**Comment by edmistj** [comment]
Probably should do the same with:

+ Connection Status

**Comment by bwitting** [comment]
Yes, that would be perfect! :+1:

**Comment by nairdo** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/37600a8e4c952d278a1803b0bda28172226dc2ce  and https://github.com/SparkDevNetwork/Rock/commit/00e3293b96c2517e8bfa218ae3d634157b4725cc.
