### ISSUE TITLE
Editing a profile with a caption deletes the caption

### ISSUE THREAD

**Issue by ccofnow** [SparkDevNetwork/Rock#1544]
Run "Person Note Add" from a workflow, with a textual caption specified.

From the person profile, click the "Edit" icon associated with the note created above.

Edit the text and click Save. [Caption] is set to null, resulting in loss of the caption and rendering of the note author's name as the caption instead.

![notecaptionbug](https://cloud.githubusercontent.com/assets/6932047/15558835/13b60cb0-2292-11e6-94cf-dbc997c753bb.jpg)

**Comment by azturner** [comment]
@ccofnow Thanks for the detailed screenshot!
