### ISSUE TITLE
Rock Updates Are Not Limited to Sequential Progression

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#1546]
Not sure if this is intentional or not, but it appears I have the ability to install the `v4.6` update _before_ the `v4.4` and `v4.5` updates. I wasn't sure if running the latest includes the previous 2, and I didn't want to find out the hard way. If this is unintentional, we probably should disable the other buttons. If it is intentional, and you can skip to the latest and it includes everything, there's probably room for adding clarity to that.

![image](https://cloud.githubusercontent.com/assets/2465823/15583227/f74d5de2-2342-11e6-866c-73c550475573.png)

**Comment by arranf** [comment]
I believe this is working as intended :)

**Comment by briankalwat** [comment]
@arranf So, in that case, I just thought it might be helpful to note that running the `v4.6` update will also include the changes from `v4.4` and `v4.5`. That's all.

**Comment by nairdo** [comment]
This was a new feature introduced at some point shortly after 4.0.  (But thanks for the precautious warning.)

**Comment by briankalwat** [comment]
Honestly, I just don't think you can assume anything when it comes to things like this. Yeah, it might be overkill. Sure, it might be inferred by 90% of people. But I don't ever think there's a reason to leave an opportunity to add clarity on the table. Just my 2 cents.

**Comment by treyhendon** [comment]
@nairdo  This might need to be revisited.  I went directly from 1.4.1 to 1.4.5 and the Login Status Block was not applied to all pages.

**Comment by nairdo** [comment]
@treyhendon I don't think 1.4.1 is supposed to have the changes that would allow that to happen.  Are you sure you A) didn't have a custom block and B) you really started at 1.4.1?

**Comment by treyhendon** [comment]
Hmm.  I did the first update after a fresh install of McKinley, then jumped to 1.4.5 after that single update.  So I only had to click update twice to get to 1.4.5.  I assumed that path would have been 1.4.0 -> 1.4.1 -> 1.4.5.  Or, does the Installer start on 1.4.1?

Admittedly, I didn't write down what sequence I was doing, and didn't even realize it was a problem for a day until the missing settings were pointed out to me (thankfully I happened to remember reading this thread).  I will try a fresh install of McKinley to replicate and this time pay attention to when/how/what happens.  It is possible this was just a fluke on my install.

**Comment by nairdo** [comment]
I believe the installer starts at 1.4.1 and the new update-to-whichever 'feature' came in at 1.4.2.

**Comment by treyhendon** [comment]
Ah, yes, you're correct, which means I did 1.4.1 -> 1.4.2 -> 1.4.5.
So this could have been an install error, but the Block settings for Login Status on the admin portal are all blank.

**Comment by nairdo** [comment]
@treyhendon Since the Login Status block is applied to the layout on Site 1, can you clarify which settings were blank?   This query should return the block setting values (~18 records) for each instance of that block:

```
SELECT A.Name, AV.* FROM [BlockType] BT
INNER JOIN [Attribute] A ON A.EntityTypeQualifierValue = CAST( BT.Id AS VarChar ) AND A.EntityTypeQualifierColumn = 'BlockTypeId'
INNER JOIN [AttributeValue] AV ON AV.AttributeId =  A.Id
WHERE
 BT.Name = 'Login Status'
```

**Comment by azturner** [comment]
FYI, we have updated the descriptions to include note about updates including changes from previous updates: 
![image](https://cloud.githubusercontent.com/assets/548180/15862860/d8a6f0a0-2c85-11e6-8eaf-20589d302abb.png)
