### ISSUE TITLE
[EN] Add Pluggable Security Roles

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#1548]
### Problem
For our external site, we have a need to determine user access to various pages/blocks/entities dynamically, based on the current context in which the user is operating - that is, which Campus or Group or Person, etc. is currently being viewed.

At present, Rock offers a limited set of in-built dynamic security roles, such as [All Users] and [All Authenticated Users], and some other implementations that are block-specific, such as Group Leader access in the Group Toolbox. 

We need a way of defining additional dynamic Security Roles, so that user permissions can be determined by taking into account a number of different elements of the current context.

### Proposed Solution
The proposed solution is to create a pluggable Security Provider component to extend the functionality of the existing in-built security roles. The advantage of a pluggable approach is that we could also write our own Security Roles for site-specific requirements that may not be generally applicable to other organizations.

A Security Provider component would define one or more Security Roles that can be evaluated dynamically during runtime, and can take into account the current context in which the user is operating.

Some examples of new context-aware Security Roles that could be implemented (RSC = "Rock Security Context"):
RSC - Person Parent or Guardian
Checks if the user is a Parent or Guardian of the Context Person.
RSC - Campus Member
Checks if the user is a member of the Context Campus.
RSC - Group Leader
Checks if the user is a Leader of the Context Group
(Note that this role would simply re-implement the existing Group Toolbox functionality in a re-usable component).
RSC - Group Supervisor
Checks if the user is a Supervisor/Manager of the Context Group.
(In our site implementation, a supervisor is a person who is a leader of a group that has child groups)

Please feel free to add your thoughts and ideas - all suggestions welcome!

**Comment by dcagnetta** [comment]
This is also something we are looking at implementing. Security by campus. This added feature would be extremely helpful. 

In the meantime

I understand every entity has an IsAuthorized method. 

would I need to extend this method in the Person model to check the logged in persons campus ?

Am I on the right track?

**Comment by MrUpsideDown** [comment]
@dcagnetta: Sorry, I got a bit carried away with this idea... I've updated my answer on the forum to address the question you actually asked in the first place!

**Comment by arranf** [comment]
@MrUpsideDown Did you make headway here? If so is this something that can be PR'd in from your fork?

**Comment by nairdo** [comment]
Hello amazing community member! We've recently moved 'feature requests' over to our own "Ideas" system on our Community site over at: http://community.rockrms.com/ideas 

If you'd like to re-propose your idea and put it up to the vote, **please re-submit your idea there**.  Thanks!
