### ISSUE TITLE
Develop branch: SiteDetail.ascx Advanced Settings missing a label

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1550]
The [Page Header Content](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Cms/SiteDetail.ascx#L79) control doesn't have a label set, so it just shows up blank on the page:

![screenshot 2016-06-01 10 10 08](https://cloud.githubusercontent.com/assets/1210933/15712622/1547fb7a-27e1-11e6-8780-ccfc2b0a5b48.png)

**Comment by edmistj** [comment]
Thanks, that was on my list of things to do before v5 alpha.
