### ISSUE TITLE
"Pending Approval" Tag Should be Hidden if "Items Require Approval" is Disabled

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#1553]
Just my opinion, but I feel like if there's the ability to disable the approval process on a content channel, then the "Pending Approval" tag should not be visible for items within said channel.

Thoughts?

![image](https://cloud.githubusercontent.com/assets/2465823/15750056/e3309926-28b2-11e6-826f-054a9e602152.png)

**Comment by edmistj** [comment]
That was fixed a couple of weeks ago in develop via: https://github.com/SparkDevNetwork/Rock/commit/2061c3fb9ca1ad793d15c0e2f8c77f5d47a53b46

Thanks for reporting it though. Constant polishing is always required.
