### ISSUE TITLE
Summary not added to contribution statement

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#1554]
The summary is not added to the contribution statement. 

https://github.com/SparkDevNetwork/Rock/blob/develop/Applications/Wpf/StatementGenerator/ContributionReport.cs#L307 - that chunk of code should add Summary if it exists.

**Comment by azturner** [comment]
@mikepetersonccv , have you had a chance to look at this?

**Comment by mikepetersonccv** [comment]
@azturner yep, working on it today

**Comment by mikepetersonccv** [comment]
This was actually a bug in the rest controller.  I had originally thought there was in the StatementGenerator itself, but that is actually already able to display Summary.  The code at L307 looks like it isn't but that chuck of code is for the Account Summary part of the statement, not the individual transactions.

**Comment by mikepetersonccv** [comment]
Here is a layout file you can use that will show the summary of the transaction as well as the summary of each Account of the transaction.

[show-summary.zip](https://github.com/SparkDevNetwork/Rock/files/309779/show-summary.zip)
