### ISSUE TITLE
Unhandled .NET exception in w3wp.exe when "flip the switch"

### ISSUE THREAD

**Issue by leehockhin** [SparkDevNetwork/Rock#1559]
Installing Rock on Windows Server 2012 R2 Essentials with SQL Express 2014.
Rock install went all the way till the last screen to flip the switch
![flip the switch](https://cloud.githubusercontent.com/assets/17799991/15767122/41c4589a-2978-11e6-8c3b-03a72094574b.PNG)
then hit the error " An unhandled Microsoft .NET Framework exception occured in w3w.exe [2568]
![error 2568](https://cloud.githubusercontent.com/assets/17799991/15767176/8f1dd2f6-2978-11e6-8741-f7116195aff0.PNG)
So downloaded and installed all the available updates, re-run the install and hit a similar error.  Error code now [7024]
![error 7024](https://cloud.githubusercontent.com/assets/17799991/15767220/db9f1086-2978-11e6-91ae-ae17b9ecba9d.PNG)

**Comment by edmistj** [comment]
I don't believe this is an issue with code, but rather your environment so I'm closing this issue. I notice you have this in the Rock Q&A which is the right place for it. The community should be able to help you there.

**Comment by leehockhin** [comment]
Understood
