### ISSUE TITLE
Arvixe Installation Run Time Error

### ISSUE THREAD

**Issue by davidmmcgrew** [SparkDevNetwork/Rock#1565]
Fresh install on Arvixe.  All went well, but when site starts, I get :

Server Error in '/' Application.

Runtime Error

Description: An exception occurred while processing your request. Additionally, another exception occurred while executing the custom error page for the first exception. The request has been terminated.

**Comment by davidmmcgrew** [comment]
Further info - I set the custom erros to off in the web.config file, and got :+1: 
Server Error in '/' Application.

Compilation Error

Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately. 

Compiler Error Message: The compiler failed with error code 1.


Show Detailed Compiler Output:


C:\Windows\SysWOW64\inetsrv> "C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe" /t:library /utf8output /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\7611a8c6\0045de5a_cd54d101\Rock.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\90367eef\0004e149_cc54d101\Twilio.Api.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\f5e9f1e7\00d7af48_cc54d101\Microsoft.Web.XmlTransform.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\a3cff190\00fc311a_cc54d101\Microsoft.Owin.Host.SystemWeb.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Caching\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Caching.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\278670cc\00fc311a_cc54d101\Owin.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\1d13477c\00d7af48_cc54d101\Newtonsoft.Json.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Activation\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Activation.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.ApplicationServices\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.ApplicationServices.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\5df9c465\009c5740_cc54d101\EntityFramework.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\47205180\0023eb43_cc54d101\System.Web.Http.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\befabf33\0026d460_cd54d101\Rock.Rest.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Web.Infrastructure\v4.0_1.0.0.0__31bf3856ad364e35\Microsoft.Web.Infrastructure.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.IO.Compression\v4.0_4.0.0.0__b77a5c561934e089\System.IO.Compression.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.IO.Compression.FileSystem\v4.0_4.0.0.0__b77a5c561934e089\System.IO.Compression.FileSystem.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\a10a00d4\00d7af48_cc54d101\RestSharp.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Services\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ComponentModel.Composition\v4.0_4.0.0.0__b77a5c561934e089\System.ComponentModel.Composition.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\75cb56e4\009c5740_cc54d101\EntityFramework.SqlServer.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\34e9bc7b\00cf0019_cc54d101\Antlr3.Runtime.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\00ad2dae\0023eb43_cc54d101\Microsoft.Data.Edm.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\3dff5ba9\0031124b_cc54d101\UAParser.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\d6008a07\00c98841_cc54d101\HtmlAgilityPack.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\75c1bef5\00fc311a_cc54d101\Microsoft.Owin.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_32\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\a0f558ce\00be4a57_cd54d101\Rock.Version.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\3cf3ddcf\00d7af48_cc54d101\NuGet.Core.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\318d0b5d\0004e149_cc54d101\System.Spatial.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\54b56435\00fc311a_cc54d101\Microsoft.AspNet.SignalR.Core.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\e8a34650\00fc311a_cc54d101\Microsoft.Owin.Security.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\74179a84\0061ff37_cc54d101\Payflow_dotNET.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\766fe992\007d4d46_cc54d101\Microsoft.Data.OData.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\cd6fccb0\0029631b_cc54d101\System.Web.Optimization.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\a23b3b9c\0029631b_cc54d101\WebGrease.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\e369db12\00f6b942_cc54d101\ImageResizer.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\929333bb\0023eb43_cc54d101\System.Web.Http.OData.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http.WebRequest\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.WebRequest.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\9ad768d8\00cf0019_cc54d101\EXIFextractor.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Web\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Web.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\e4b7761b\0023eb43_cc54d101\System.Net.Http.Formatting.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\ac1e4d8d\006f263f_cc54d101\DDay.iCal.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\fe32328c\006f263f_cc54d101\DocumentFormat.OpenXml.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\651d3c2d\00d7af48_cc54d101\OpenXmlPowerTools.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Activities\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Activities.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\48b3d364\0034ce36_cc54d101\EPPlus.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\658fd44f\0061ff37_cc54d101\C5.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\408a22ae\00c98841_cc54d101\Humanizer.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\eb534f02\0007ca66_cd54d101\Rock.PayFlowPro.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Activities\v4.0_4.0.0.0__31bf3856ad364e35\System.Activities.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\dee24a1d\0007ca66_cd54d101\Rock.Migrations.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\4a103d7c\006f263f_cc54d101\CronExpressionDescriptor.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.WebPages.Deployment\v4.0_1.0.0.0__31bf3856ad364e35\System.Web.WebPages.Deployment.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.DynamicData\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.DynamicData.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\784176a1\0023eb43_cc54d101\System.Web.Http.Cors.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.IdentityModel\v4.0_4.0.0.0__b77a5c561934e089\System.IdentityModel.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\a04e414e\00fc311a_cc54d101\Microsoft.AspNet.SignalR.SystemWeb.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\ecdfb258\00f6b942_cc54d101\System.Web.Cors.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\63e9dac3\0023eb43_cc54d101\System.Web.Http.WebHost.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\11a0d6b2\008e3039_cc54d101\Quartz.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\v4.0_4.0.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\41913b27\0029631b_cc54d101\WebActivatorEx.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\assembly\dl3\172afad3\00be4a57_cd54d101\DotLiquid.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.WorkflowServices\v4.0_4.0.0.0__31bf3856ad364e35\System.WorkflowServices.dll" /R:"C:\Windows\assembly\GAC_MSIL\Microsoft.SqlServer.Types\11.0.0.0__89845dcd8080cc91\Microsoft.SqlServer.Types.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.WebPages.Deployment\v4.0_2.0.0.0__31bf3856ad364e35\System.Web.WebPages.Deployment.dll" /out:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\App_Code.7c4xk1_d.dll" /D:DEBUG /debug+ /optimize- /w:4 /nowarn:1659;1699;1701;612;618 /warnaserror-  "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\App_Code.7c4xk1_d.2.cs" "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\App_Code.7c4xk1_d.9.cs" "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\App_Code.7c4xk1_d.10.cs" "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\App_Code.7c4xk1_d.0.cs" "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\App_Code.7c4xk1_d.7.cs" "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\App_Code.7c4xk1_d.5.cs" "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\App_Code.7c4xk1_d.12.cs" "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\App_Code.7c4xk1_d.3.cs" "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\App_Code.7c4xk1_d.1.cs" "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\App_Code.7c4xk1_d.8.cs" "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\App_Code.7c4xk1_d.11.cs" "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\App_Code.7c4xk1_d.6.cs" "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bc2ec2ec\62db7657\App_Code.7c4xk1_d.4.cs"

**Comment by azturner** [comment]
@davidmmcgrew Because of the way Arvixe restricts their AppPool settings, we do not recommend using them to host Rock. See these questions/answers for more details...
http://www.rockrms.com/Rock/Ask/Troubleshooting/Questions/815
http://www.rockrms.com/Rock/Ask/Troubleshooting/Questions/819
http://www.rockrms.com/Rock/Ask/Troubleshooting/Questions/820

We recommend using 3Essentials or WinHost, and have steps in documentation on how to setup using those providers: http://www.rockrms.com/Rock/BookContent/3/87#rockpartners

**Comment by davidmmcgrew** [comment]
LOL!

 

Do you realize that the sample install video uses Arvixe?  This is the reason I chose this hot!!

 

 

David M. McGrew, MD, FAAHPM, HMDC

President - Hospice & Palliative Physician Services, LLC 

Lead Physician – Aspire Healthcare, Inc, Tampa Bay Market

2014-5 President – Hospice Medical Director Certification Board

2003 President - American Academy of Hospice and Palliative Medicine

 

 

"Men occasionally stumble over the truth, but most pick themselves up and hurry off as if nothing ever happened." Winston Churchill

 

"The significant problems we face cannot be solved at the same level of thinking we were at when we created them." Albert Einstein

**Comment by azturner** [comment]
Wow, yeah that is an old page. Not even sure how you found it :). We'll remove it. This is the video we have now: http://www.rockrms.com/Download. (and noticed that it still has Arvixe in the URL, but we removed the beginning where it shows setting up Arvixe). Sorry about the confusion.
