### ISSUE TITLE
Group Finder Settings Conflict

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1567]
When creating a new Group Finder block and trying to put in a page setting for Register Page under Linked Pages, the Show Grid checkbox as well as the Register Page do not retain their settings. This will often cause the block to disappear until manually rechecking Show Grid and not specifying a Register Page. 

Confirmed in both 4.6 and 5.0 alpha.

**Comment by azturner** [comment]
@BelAirIT I couldn't reproduce in V5. Here are the steps I took: https://drive.google.com/file/d/0B2ElKd3uDxuIYzFOT2tyMUxWVE0/view

Am I doing anything different than you?

**Comment by azturner** [comment]
@BelAirIT , perhaps this was fixed here: https://github.com/SparkDevNetwork/Rock/pull/1454

**Comment by BelAirIT** [comment]
Looks like it is working in 5.0.
