### ISSUE TITLE
[EN] Enhancement for Check-in Config section v5

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1571]
If you have a really long list of check-in areas and groups and you click on an area or group quite a ways down, you have to scroll all the way back up to the top of the page to make any changes. If it is possible could the edit/input section stay in view on the page no matter how far down you scroll.

**Comment by BEGamache** [comment]
I noticed with the new enhancement when I click on an area or a group, I get brought to the top, however, the page refreshes with that area's/group's info and the page scrolls back down to group or area instead of remaining at top of the page for detail editing.

**Comment by nairdo** [comment]
Yeah, I see that now too.  That's a new behavior / problem.  I'm not sure what changed, but it's now performing a full page reload after clicking on a area/group.

**Comment by nairdo** [comment]
Ok, it's not a full post-back issue, it's actually a race condition between a slower server response vs the scroll-to animation.  I've got a new solution but need to check with @azturner to see if I should commit it to the 1.5.1 or 1.5.2 hotfix.
