### ISSUE TITLE
Connection Requests - Default Connector not being selected on Transfer

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1573]
On 4.6 - When a connection request is transferred to a new opportunity, the connector becomes blank, even when there is a default connector set for that opportunity.

**Comment by sparkdevnetwork-service** [comment]
➤ Nick Airdo commented:
https://app.asana.com/0/20866866924296/20866866924296 is this you or is it some automation that closed it because the issue was just closed in Github?

**Comment by edmistj** [comment]
I setup Asana automation this afternoon. If you close it there it's closes the Github issue.
