### ISSUE TITLE
Can't Find Block Configuration

### ISSUE THREAD

**Issue by ToxicFume** [SparkDevNetwork/Rock#1575]
We just got started with Rock RMS and I am currently going through the check list of things to do. I am at the "Update Welcome Message" section. It says "Click the 'Block Configuration' button  in the administrators toolbar at the bottom of your browser's window.".

I do not see that button.

I am using Windows 10 and the Chrome Browser.

**Comment by ToxicFume** [comment]
Oh I found the problem. The problem is you have to shrink your web browser for it to go into "mobile mode" Once you get your web browser small enough it will show up. That's a little bit confusing.

**Comment by JimMichael** [comment]
This is not quit accurate. In normal (non mobile-sized) mode, you simply need to hover your mouse at the bottom of the Rock window and the Admin toolbar will appear. At mobile sizes, the Admin bar is always present. FYI this area is for reporting found bugs in the software. To just ask questions or get help you should use the Ask section of rockrms.com or the Rock slack channel.

**Comment by ToxicFume** [comment]
Ok, sorry. Very new at this and just figuring it out. Thanks for the tip! :)

**Comment by JimMichael** [comment]
No worries! Glad to have you here checking out Rock, and welcome!  Hope to see you in the forums or slack channel.
