### ISSUE TITLE
WorkFlow Email - File path incorrect

### ISSUE THREAD

**Issue by dcagnetta** [SparkDevNetwork/Rock#1582]
Hi
I created a File attribute on a User Entry Action.

When the email is sent the link is set as
`/GetFile.ashx?guid=e6972846-ddf4-4e3d-bcbb-109efce1a620`

which cannot be found as it doesnt include the domain. All other links do include the domain however.

**Comment by tcavaletto** [comment]
Hi,
How are you sending the email in the workflow? Is there a particular template you're using? How is the link generated?

**Comment by dcagnetta** [comment]
Hi @tcavaletto , I used the standard workflow notification template
