### ISSUE TITLE
[Obsolete] Remove Populate Three Families script

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1601]
The [Dev Tools\Populate Three Families](https://github.com/SparkDevNetwork/Rock/blob/develop/Dev%20Tools/Sql/Populate_Three_Families.sql) script is quite a bit out of date and should be removed to avoid confusion.  The PopulatePlethoraRandom script or SampleData block can be used instead.

**Comment by arranf** [comment]
So is the script that creates attendance groups and quite a few others :)

**Comment by mikepetersonccv** [comment]
Would you say we have a plethora of obsolete scripts?

**Comment by arranf** [comment]
Fixed in pull request #1696
