### ISSUE TITLE
Smart Search moving out of position when using block configuration from admin toolbar

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1602]
I don't know if this is a beta issue, but when I click the block configuration button in the admin toolbar, the search box at the top of the page drops down. I may just be the arrow for smart search configuration isn't being placed next to the smart search box.

![screen shot 2016-06-29 at 10 05 09 am](https://cloud.githubusercontent.com/assets/5738650/16457583/ad2e18f0-3de1-11e6-826c-c251cd606a5c.png)

**Comment by BEGamache** [comment]
Same thing happens on the external site to the Page Menu block at the top.

**Comment by arranf** [comment]
This has been around for a while so it's not just beta.

**Comment by edmistj** [comment]
When editing zones and blocks we need to inject markup to allow for editing. This can cause the styling to shift a bit. This is necessary and there's not much that can be done to prevent it.
