### ISSUE TITLE
Add Rock.SystemGuid.Layout

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1603]
Useful for plugin migrations

**Comment by arranf** [comment]
Additional context. If you want to add something to a page in a plugin migration you need to be able to specify the page layout and site using GUIDs. Whilst you can use the codegen I think it'd be helpful in other contexts if you could reference those GUIDs from a const.

**Comment by nairdo** [comment]
Hello amazing community member! We've recently moved 'feature requests' to our own "Ideas" system on our Community site at: http://community.rockrms.com/ideas 

If you'd like to re-propose your idea and put it up to the vote, **please re-submit your idea there**.  Thanks!
