### ISSUE TITLE
Duplicate Attendance Rows

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1604]
After importing attendance records in Rock for small groups, when a weekly schedule is set up in a small group, duplicate rows appear for records already present. One row has the imported attendance while the other is empty. Will upload screenshots in the morning to better explain. I'm able to view this when going to group viewer > group > clicking the attendance button in the group detail block.

**Comment by arranf** [comment]
How did you import?

**Comment by BEGamache** [comment]
Through SQL insert: 
insert [Attendance] ( GroupId, StartDateTime, DidAttend, DidNotOccur, Note, [Guid], CreatedDateTime, PersonAliasId, RSVP)
			select @RockGroupId, ISNULL(@F1CreatedDate,GetDate()), @DidAttend, @DidNotOccur, @F1Comments, NEWID(), @F1CreatedDate, @PersonAliasId, @False 

![screen shot 2016-07-01 at 10 40 55 am](https://cloud.githubusercontent.com/assets/5738650/16526808/a7ebe1fe-3f78-11e6-88ac-18dfaf94d6c9.png)

**Comment by azturner** [comment]
@BEGamache , can you select one of the "occurrence" rows that does not have any attendance, mark someone as having attended, and then compare the record that gets created for that with the records you imported to determine the difference.

**Comment by BEGamache** [comment]
It looks like the differences are, ScheduleId,ModifiedDateTime,CreatedByPersonAliasId, ModifiedByPersonAliasId are the only additional fields that are added. Looks like ScheduleId being absent in the other records may be the culprit.

**Comment by arranf** [comment]
@BEGamache I'm going to go ahead and close this as I think this was a configuration issue rather than a bug. Let me know if I'm wrong though.
