### ISSUE TITLE
[EN] Add Currency Code to PaymentInfo model

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1605]
We just finished working with a UK church in our other CMS, and converting back and forth between USD, EUR, and GBP was relatively simple.  

Rock currently supports displaying a custom CurrencySymbol but would be nice to also have the currency code used / changed by the user.  With a couple tweaks, it would also allow users outside your normal region to give (without having a card from a bank in your culture).  

Adding this field to the [PaymentInfo](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Financial/PaymentInfo.cs) model seems like the best place for it, but I may have overlooked a better place.  

The list of Currency Codes is available [here](https://msdn.microsoft.com/en-us/library/system.globalization.regioninfo.isocurrencysymbol%28v=vs.110%29.aspx) and should be accessible via `RegionInfo.CurrentRegion.ISOCurrencySymbol`.  Keep in mind that some countries support multiple currencies, so the user needs to pick one instead of assuming a 1:1 match with the culture.

**Comment by arranf** [comment]
+1 It may be worth doing this along with some other broader changes to
culture. Me and @MrUpsideDown had a discussion a long time ago that I've
saved about some potential changes to internationalisation that would
prevent some assumptions being made that don't necessarily add up.

Let me know if you guys want to see that.

**Comment by edmistj** [comment]
Sounds interesting but we might need to table it until later in the year after we get the v5 and v6 features ready. If you have further specifics though add them hear so we can start crock-potting the work.

**Comment by saconger** [comment]
I definitely think something like this would be helpful.  I am also working with an organization that would need to operate in multiple currencies and languages.  I can't tell from David's description if this is covered but... wouldn't it need to handle exchange rates?

For example, if the organization operates out of Germany, they would want to see Euros on every screen and reports; which is fine if every donor is from Germany.  But if a USA donor give money, they would need to give USA dollars and have their bank account / credit card affected accordingly; as well as, receive a USA dollars contribution statement.  BUT the Germany organization would need to see it all in Euros.

**Comment by dcs619** [comment]
Exchange rates are handled at the merchant processor level (at least the processors I've worked with).  You might be able to save the current exchange rate in Rock at the time of the gift, but if it doesn't match the merchant's rate your fund amounts would be off.

Once implemented, giving would look like this (simplified):
1. Organization enables USD and EUR (or whatever supported currencies) for their processor
2. User chooses via UI which currency they're giving in
3. Gift sent to the processor, which converts currency at the current exchange rate
4. Rock saves the currency selected to the user's payment account
5. Organization bank receives funds from the merchant processor

**Comment by saconger** [comment]
Could you explain what you mean by "4. Rock saves the currency selected to
the user's payment account"?  If your internal organization is working off
of EUR but the donor gives USD.. what saves back to Rock, EUR?

**Comment by dcs619** [comment]
The PaymentInfo model is tied to a specific user's CC or ACH account.  So if we added a `PaymentInfo.CurrencyCode` field, you'd want to save the currency that the user gave in (USD), not the organization's preference.

If you have to handle both user and organizational currency preferences, you'd need more fields besides just `PaymentInfo.CurrencyCode`.  

Alternatively, you could implement an entirely new data structure, like a Currency Code field type that you can apply as an attribute to anything.

**Comment by saconger** [comment]
If I'm understanding correctly, you are proposing only the currency giving
is saved in it's original form.  That solves payment processing but
confuses any page, report, or graph that has totals.  You can not add 1 USD
to 1 EUR and say it's 2.  It's actually 1.9 EUR.

I can't help to think the other way around would be a better option.
Process EUR as a EUR.  Process a USD as a USD.  But save it to Rock as the
currency the staff is familiar with.  Then all reports, pages, graphs with
totals would be correct.  You'd only have too worry about converting in on
select contribution statement or select users contribution profile.  Not
every single page, report and graph.

You follow what my concern is?

**Comment by saconger** [comment]
Had a couple more thoughts on this. Hope they're helpful.  I think it just depends on what problem makes the most sense to solve.  If you store USD for a staff only familiar with EUR, it make the transaction and contribution statement easier but all other internal reports, graphs, totals would need to be update to support multiple currencies.  If you store the EUR amount when USD is given, then the staff will not be confused and have correct reports, totals, graphs but the transaction and contribution statement would need a conversion of the exchange rate.

However, I'm thinking either way you go, you probably need to track the exchange rate from the deposit, right?  For accounting reasons, you'd need to know the EUR value and for contribution statement you'd need to know the USD value.  So, you'd either have to store both currencies or the exchange rate, correct?

**Comment by dcs619** [comment]
Closing, won't fix
