### ISSUE TITLE
v5 Family Check-in prompts for blank "Select Area" screen

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1606]
We are seeing a bug in v5's Family check-in where you end up on a blank "Select Area" screen. In our case, we have two services sat (4:30/6:30) and two Sunday (9:00/11:00). On both days, the second service is open to check-in during the first, to handle our "two service" kids. We had no trouble checking-in kids into the first service both days, but once the second service came around (and the first was no longer available for check-in) we got the blank "Area" screen Austin mentions. This was happening on every attempted check-in... even kids who have only one place to go and meet all qualifications to go there. Also, when both services are check-in-able (during first service check-in), we can select both times and check-in to both services without issue. Seems to be only when the second service is the only option that it breaks here. This issue has been mentioned by at least two other churches trying out v5 Family checkin.
![img_1814](https://cloud.githubusercontent.com/assets/3903408/16589685/d0023d40-4299-11e6-8a80-84f24e914282.JPG)

**Comment by azturner** [comment]
Should be fixed here: https://github.com/SparkDevNetwork/Rock/commit/43d317cb866b45a3e972b4880e3f4889a00dc3f1
