### ISSUE TITLE
Check-in Schedule locations not showing group path

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1610]
The schedule table in admin > check-in manager isn't displaying the group type path and i think it is isn't being set before it is added to the row--i could be wrong though.
[https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/CheckIn/CheckinScheduledLocations.ascx.cs#L199](
https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/CheckIn/CheckinScheduledLocations.ascx.cs#L199)

**Comment by azturner** [comment]
Fixed here: https://github.com/SparkDevNetwork/Rock/commit/89ffbb4f59efe09e9806b732359ad6a85893b728
