### ISSUE TITLE
Check scanner and Statement Generator not compatible with TLS 1.2?

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1611]
As part of a PCI compliance scan, we noticed TLS 1.0 was still enabled and [is no longer PCI compliant](https://blog.varonis.com/ssl-and-tls-1-0-no-longer-acceptable-for-pci-compliance/).  When we turned it off, the Check Scan and Statement Generator apps would no longer connect: `Unable to read data from the transport connection: an existing connection was forcibly closed by the remote host.`

We turned TLS 1.0 back on and the apps were able to connect without issues.

**Comment by edmistj** [comment]
I fixed the same issue with the Document Scanner app with:

```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;
RockRestClient rockRestClient = new RockRestClient( txtRockUrl.Text );
```	

@mikepetersonccv would you be available to make these changes and re-compile the apps?

**Comment by mikepetersonccv** [comment]
@edmistj yep, I'll fix it
