### ISSUE TITLE
Default Campus in Workflow Action

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1612]
The Person Attribute From Fields action requires a Default Campus but doesn't pull in any existing campuses.

**Comment by garrettjohnson** [comment]
A default campus can be set by adding a workflow attribute of Campus and setting the default campus on the attribute.

**Campus Workflow Attribute with Default**
![screenshot 2017-03-24 12 02 42](https://cloud.githubusercontent.com/assets/374209/24309681/072565cc-108a-11e7-9aeb-d8200b602925.png)

**Person Attribute From Fields with Default set Via Workflow Attribute**
![screenshot 2017-03-24 12 04 12](https://cloud.githubusercontent.com/assets/374209/24309697/16952416-108a-11e7-89e6-20008eb30692.png)
