### ISSUE TITLE
Check-in App: Can't View Start and Cancel buttons

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1613]
This is similar to an old [issue](https://github.com/SparkDevNetwork/Rock/issues/505). I downloaded the check-in client to my laptop but I have been unable to visibly select the start button. 
![image](https://cloud.githubusercontent.com/assets/5738650/16674496/544ba56a-447e-11e6-91e8-c17ac608c306.png)

**Comment by arranf** [comment]
@BEGamache Is this still an issue?

**Comment by mikejed** [comment]
This is old enough and I haven't heard of others running into this issue. I'm going to close this issue- please let us know if it's not actually resolved and we'll open it back up.
