### ISSUE TITLE
Pledge Analytics does not respect date range

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#1617]
When you put in a date range for analyzing pledge data - it does not respect the date range for the information that is reported. The report always shows ALL GIVING to the pledged fund and not just the giving that happened in the date range.

**Comment by austinspooner** [comment]
Giving analytics is doing the same thing.

**Comment by edmistj** [comment]
I believe the Giving Analytics is different per the Slack conversation. Does it make more sense after that clarification?

**Comment by austinspooner** [comment]
Yes agreed I will remove the comment this evening

**Comment by arranf** [comment]
@austinspooner Can this be closed?

**Comment by raufrecht** [comment]
I am curious why this got closed. I am having this issue and don't have access to the "slack conversation" referred to. Can this be reopened?

**Comment by nairdo** [comment]
This issue may also be related to this recent fix: https://github.com/sparkdevnetwork/rock/commit/6b5e311b8a6e7e3db76abe6c3901f6521e748d19
