### ISSUE TITLE
Document Scanner App Error Windows 10 Pro

### ISSUE THREAD

**Issue by willpolley** [SparkDevNetwork/Rock#1618]
I'm having an issue with the Document Scanner app on a Windows 10 Pro install. The curious thing is the app works on a Windows 10 Enterprise VM installation.

Windows 10 Pro was installed from official download Microsoft source. All updates have been run and the issue persists. I confirmed all .NET Frameworks were installed and updated.

Here's the [error gist ](https://gist.github.com/willpolley/69b18b1d869f40a23b783fa4705c3d9b).

**Comment by willpolley** [comment]
I swapped the hard drive of the machine and did another fresh install to make sure it wasn't weird hardware issues, but the error persisted.

**Comment by edmistj** [comment]
Just curious, do you get the exception if you run the app as administrator. We've been running the app on Windows 10 Pro and Enterprise as well as Windows 8 & 7.

**Comment by willpolley** [comment]
Same result. I made a flash drive installer for Win 10 Pro directly from the MS app.

**Comment by edmistj** [comment]
Could you try installing the C++ redistro per this note: http://www.atalasoft.com/KB/article.aspx?id=10318

**Comment by willpolley** [comment]
Installed the x86 distribution, that fixed the issue.

The Canon driver installers only installs the current platform redist which happens to be x64 in my case.

Could we add the x86 redist into the installer package?

**Comment by edmistj** [comment]
Yes, I'll look into that. Thanks for your patience helping us figure this out.

**Comment by edmistj** [comment]
Looks like the free version of InstallShield that we've been using does not support bundling the C++ redistro. I'll have to look at other options. When we get a solution would you be able to test it for us?

**Comment by willpolley** [comment]
I'd be happy to!

**Comment by jonedmiston** [comment]
Closing as we are no longer supporting the current applications from 2016. If there is strong demand from the community we will consider an updated version. The current version requires an expensive closed-source control. Current interest doesn't warrant the on-going expense of the component.
