### ISSUE TITLE
WYSIWYG Safari Issue

### ISSUE THREAD

**Issue by hbcfw** [SparkDevNetwork/Rock#1619]
In the WYSIWYG editor for communications, there is a bug that so far I’ve seen only in Safari - when you hit Return to create a new paragraph/line, the cursor jumps to the top of the template.
This does not happen in Google Chrome.
![xdfpyn8wpu](https://cloud.githubusercontent.com/assets/18169051/16736296/fcec2e26-4751-11e6-8e0b-e9929d4c34bd.gif)

**Comment by mikepetersonccv** [comment]
this is fixed in https://github.com/SparkDevNetwork/Rock/commit/79d4c6ac2936c9894676c344270176027ac72474
