### ISSUE TITLE
Could not load file or assembly 'msvcr100.dll' or one of its dependencies.

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#1621]
When Jobs are running, some of them run into this error.

"Last Status Message
Could not load file or assembly 'msvcr100.dll' or one of its dependencies. The module was expected to contain an assembly manifest. (Could not load file or assembly 'msvcr100.dll' or one of its dependencies. The module was expected to contain an assembly manifest.)"

They work just fine afterward when I run them manually.

**Comment by dcs619** [comment]
Can you check that `RockWeb\SqlServerTypes\x64` has files in it?  (or the
x86 folder if it's an older server)

**Comment by NuclearTacos** [comment]
Both folders have files called msvcr100.dll and SqlServerSpatial110.dll

**Comment by NuclearTacos** [comment]
Per suggestion, I switched jobs to IIS context.  Haven't seen the issue again.

**Comment by edmistj** [comment]
I'm going to close this. I believe the issues you're seeing are fixed in the v5 jobs service, but we still recommend using IIS.
