### ISSUE TITLE
Family check in does not work for multiple services with multiple kids

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#1626]
When using family checkin - it does not print or finish checking in people at times when they are checking into multiple services and multiple groups (where the groups in each service are different) The families this happens to are consistent for us but it does not happen to every family.

**Comment by austinspooner** [comment]
Basically this is the best example I can come up with. Jack, Suzy and Bob Smith  are all checking in.

The family enters their phone number


They select 9:30 AM and 11:00 AM for their service time.

Then parent selects Sunday School for each kid at 9:30 AM and Church Service for each Kid at 11:00 AM each kid is a different age so is checking into a different location once the classes are selected check-in sits for about 10 seconds, and then goes back to the phone entry screen and check-in never completes the check-in or prints labels.

**Comment by austinspooner** [comment]
This video will show the bug as it happens:
https://vimeo.com/174706350/432f1607a3

**Comment by austinspooner** [comment]
This video will show that each kid has an option to check in for each service. This video also shows that if only 1 service is selected for the family at a time all kids can check-in. 
https://vimeo.com/174707217/621b563c4c

**Comment by austinspooner** [comment]
This video will show that if you only select (1) kid at a time to check-in - they can check-in to both services. But as soon as you add a second kid the check-in does not complete and returns to the main screen. 
https://vimeo.com/174707810/8c77be5b62

**Comment by azturner** [comment]
Fixed Here: https://github.com/SparkDevNetwork/Rock/commit/a4a0ffa16b8d4df0fb984f2352b98a0f8fec8aa6
