### ISSUE TITLE
RockPage.SetContextCookie only takes a single entity

### ISSUE THREAD

**Issue by ghost** [SparkDevNetwork/Rock#1633]
Does anyone have any thoughts how to implement a GroupsContextSetter (plural)?  The current GroupContextSetter (singular) sets a single group from a list, but we’d like to select multiple groups - combining the functionality of the GroupPicker control and the Context functionality of GroupContextSetter.

The biggest issue seems to be that RockPage.SetContextCookie only takes a single IEntity

**Comment by benwiley** [comment]
@azturner I'm starting this soon... any thoughts or guidance? :smile:

**Comment by edmistj** [comment]
Can you give more of the use case for this? That might help coming up with options.

**Comment by dcs619** [comment]
We're building out dashboards for ministries and they're accustomed to being able to selecting 2+ groups on Attendance Analytics.  The current dashboard only allows them to select 1 group at a time (using the GroupContextSetter),

So if I'm a staff member in charge of Parking, Greeting, and Usher Volunteers, I'd like my dashboard/context to always show attendance and ratio #'s for those three groups.

**Comment by arranf** [comment]
I'm going to go ahead and close this as this doesn't seem relevant at this point in time.
