### ISSUE TITLE
When using a Defined Value field type, Allow Multiple Values renders a dropdown

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1634]
When using a Defined Value field type (in this example, as a Connections attribute), Allow Multiple Values renders a dropdown instead of checkboxes, meaning that it really won't accept multiple values:

![2016-07-22 12_50_36-connection type detail _ rock rms](https://cloud.githubusercontent.com/assets/1859094/17064527/eb862a6c-500a-11e6-83ba-a8b7288e8d5a.png)

![2016-07-22 12_47_19-volunteer opportunities _ newpointe community church](https://cloud.githubusercontent.com/assets/1859094/17064517/d934ca30-500a-11e6-8807-a7fb820753f3.png)

**Comment by dcs619** [comment]
This seems like it might be related; if not I can create a separate issue.  

When using a DefinedValue with the new MetricPartition structure, I get an empty dropdown choice even though the value/partition is required:
![image](https://cloud.githubusercontent.com/assets/1210933/17106410/34e5d2d4-5259-11e6-9205-27014b7e9b84.png)

DefinedType and Metric Partition configuration:
![image](https://cloud.githubusercontent.com/assets/1210933/17106488/912cd63c-5259-11e6-91e3-d715171fec5e.png)

![image](https://cloud.githubusercontent.com/assets/1210933/17106485/8b0ab080-5259-11e6-8f2a-dca66047f714.png)

**Comment by bwitting** [comment]
FWIW, this happens in other areas too.  For example, we have an attribute for a Serving Team called Typical Serving Time that is driven from a Defined Value.  Even though it is multi-select, it appears as a drop-down in the filters.  But if I make an attribute of type multi-select, that appears correctly as checkboxes: 

![2016-09-12 17_00_00-volunteer teams _ rock rms](https://cloud.githubusercontent.com/assets/1859094/18452863/a8414f42-790a-11e6-915a-9ba54e577b94.png)

**Comment by garrettjohnson** [comment]
Fixed in v6.1 via #1796
