### ISSUE TITLE
History point creation exception on event registration.

### ISSUE THREAD

**Issue by jreciomoreno** [SparkDevNetwork/Rock#1639]
We have been experiencing an issue with one medium to large registration template that has 2 forms, basically when someone tries to register for the event it throws the following exception: "A history point can only be created during an asynchronous postback". The code raising the exception is in Rock\Web\UI\RockPage.cs in the AddHistory method.  
From what I have been able to find, when clicking the Next button to go to the second form in the registration, the page does a postback but is not doing an asynchronous call thus causing the AddHistoryPoint method to throw an exception as it only supports asyncrhonous post backs.

I was wondering if there is any cons of placing a checks to see if the event is a Page.IsAsync and Page.IsPostBack such as:

```
if ( ScriptManager.GetCurrent( Page ) != null && (Page.IsAsync && Page.IsPostBack))
           {
               ScriptManager sManager = ScriptManager.GetCurrent( Page ); ...
```

**Comment by arranf** [comment]
@jreciomoreno Is this still an issue?

**Comment by nairdo** [comment]
I also recently saw this in a v7 pre-alpha-release branch (1.7.0.39).  I had to add `_saveNavigationHistory = false;` just before the `ShowSumary()` call in the `ShowRegistrant()` method of the RegistrationEntry.ascx.cs to temporarily work around this issue.  In our case, it seemed to be happening on a template that did NOT allow multiple registrants.

I'm trying to reproduce it now on the prealpha demo site (1.8.0.10).

**Comment by cbump** [comment]
I've found that this seems to be specific to specific browsers or internet security or router configurations.  A specific member of our church consistently has this error.  I think it might be a browser extension or some sort of proxy software that is stripping the "X-Requested-With" header from the XHR/AJAX Request.

**Comment by nairdo** [comment]
I am able to reproduce this again on our recently updated production server (v 1.8.0.9).

**Comment by nairdo** [comment]
Also... @cbump++ thanks for your 35eeaed fix. It's successfully dealing with this issue on our system now too.
