### ISSUE TITLE
Help Text / Required Field Mismatch: Login Status Block

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#1640]
The Login Status Block (like a few other blocks in Rock) has a mismatch between the help text and the required fields.

![image](https://cloud.githubusercontent.com/assets/19762670/17117324/4116a466-5281-11e6-8492-c256eadd9304.png)

Pictured is what I'm talking about.  It comes configured this way stock.  If you change the name of the block, it won't allow you to save without filling the My Profile Page and the My Settings Page.  If you save both of these fields, you can't clear them later.

Often times the functionality described by the help text is preferable.  In this circumstance, I prefer not having the bottom two fields required.

**Comment by arranf** [comment]
@NuclearTacos Hey, what version are you on? I'm looking at the code and this isn't the behaviour I'm seeing. All the fields you show above are listed as *not* required.

**Comment by NuclearTacos** [comment]
It was 4.6

**Comment by azturner** [comment]
Fixed in 1.5 here: https://github.com/SparkDevNetwork/Rock/commit/b6acb13dc78a7120b63de00e7b30d2159a6a27c4
