### ISSUE TITLE
Exception: Multiple controls with the same ID 'gfFilter' were found

### ISSUE THREAD

**Issue by ccofnow** [SparkDevNetwork/Rock#1642]
I have a rather complicated multi-query DynamicData Block that I've found no longer works under 5.1 (it did function under 4.6).

To duplicate the error, I've trimmed the queries down substantially. The first three lines of the following query work and do not throw an error. When I add the fourth line, I see the correct result initially. But upon refreshing or navigating to the page anew, the page throws an exception.

Here's the query:
``SELECT * INTO #temp10s FROM (SELECT TOP 10 [Id] FROM [Person]) AS x;``
``SELECT count(*) AS "Total '10's (First attending Active Adults from zip code 860xx)", '100%' AS "Percent" FROM #temp10s;``
``SELECT * INTO #temp4s FROM (SELECT TOP 3 [Id] FROM [#temp10s]) AS x;``
``SELECT count(*) AS "Total '4's (second visit)", LEFT(CONVERT(VARCHAR(50),CAST(count(*) AS DECIMAL)/(SELECT count(*) FROM #temp10s)*100),4)+'%' AS "Percent" FROM #temp4s``

And here is the exception:

> HttpException in System.Web
> 
> Message
> Multiple controls with the same ID 'gfFilter' were found. FindControl requires that controls have unique IDs.
> 
> Stack Trace
> 
>    at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
>    at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
>    at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
>    at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
>    at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
>    at System.Web.UI.Control.FillNamedControlsTable(Control namingContainer, ControlCollection controls)
>    at System.Web.UI.Control.FindControl(String id, Int32 pathOffset)
>    at System.Web.UI.ControlUtil.FindTargetControl(String controlID, Control control, Boolean searchNamingContainers)
>    at System.Web.UI.UpdatePanelControlTrigger.FindTargetControl(Boolean searchNamingContainers)
>    at System.Web.UI.AsyncPostBackTrigger.Initialize()
>    at System.Web.UI.UpdatePanelTriggerCollection.Initialize()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by edmistj** [comment]
@dcs619 I applied this fix for when there are more than 2 grids showing. Feel free to refactor to enable support for more that 1 grid if you'd like (it's probably rare).
