### ISSUE TITLE
Event registration not validating all required fields

### ISSUE THREAD

**Issue by jreciomoreno** [SparkDevNetwork/Rock#1643]
The event registration page does not validates all Person Fields properly such as Address, Birthday and Gender to name some. 
The First Name, Last Name and Email fields do validate properly.
Also I think address line 2 should not be marked as required as most of the addresses only require the first line.

![image](https://cloud.githubusercontent.com/assets/18447151/17151141/299a6ef0-5338-11e6-8bda-547676984951.png)

**Comment by hillsideassembly** [comment]
I can confirm that "gender" and "birthdate" are not being required from the user even when they are set to require input.

**Comment by garrettjohnson** [comment]
We can confirm this issue, and that the address can be short-circuited just by adding characters to address line 1.

**Comment by cabal95** [comment]
Address is for sure related to #1705. Probably the Birthday picker too.
