### ISSUE TITLE
[EN] Make metric partitions accessible in Lava 

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1644]
Welcome to Advanced Metrics 405!

If a metric generates values via SourceSQL and also has a partition for GroupId, you can't filter by GroupType.  You'd have to hardcode the grouptype inside the SQL (oversimplified):
```
SELECT COUNT(*), A.[GroupId]
FROM [Attendance] A
WHERE DidAttend = 1
  AND Group.GroupType = 'Student Volunteer'
GROUP BY A.[GroupId]
```

However, if we add MetricPartition to the Metric Lava object, then the GroupType doesn't have to be hardcoded:
```
SELECT COUNT(*), [GroupId]
FROM [Attendance] 
WHERE DidAttend = 1
  AND Group.GroupType = {{Metric.MetricPartition.EntityTypeQualifierValue}}
GROUP BY [GroupId]
```

Either of the following solutions would work:
`[LavaInclude]` on [MetricPartition](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/Metric.cs#L189) 
or
 `mergeObjects.Add( "MetricPartitions", this.MetricPartitions );` in [GetMergeObjects](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/Metric.cs#L271)

**Comment by dcs619** [comment]
@azturner Any thoughts on the proposed solution?  

I can do a PR with this enhancement that also adds a GroupType filter for the GroupPicker control.  That way the UI for editing a MetricPartitionValue is limited to the same GroupType that the SourceSQL is limited by.

**Comment by azturner** [comment]
@dcs619 Adding the [LavaInclude] is fine. Not sure I'm following how adding GroupType filter to GroupPicker helps, but I'll add that to our weekly dev discussion for this week (@mikepetersonccv will be there and he's a bit more familiar with how the multi-partitions UI works).
