### ISSUE TITLE
Exception when using Action: Create Connection Request

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#1645]
When creating a Connection Request from the Workflow Action, by my testing, it seems to require a Campus attribute otherwise the workflow throws an exception.

I've experienced this with multiple connections, connection types, and workflows.  Tyler Schrock experienced the same issue.

**Comment by arranf** [comment]
@Tschrock Do you have any exceptions or further details to add to this?

**Comment by arranf** [comment]
@NuclearTacos Can you provide steps to reproduce this? I'm marking this for cleanup until I get some more details. I'll take a look when you do!

**Comment by Tschrock** [comment]
I believe this was fixed with https://github.com/SparkDevNetwork/Rock/commit/2a73100f117a8e1f622caec8e438e48c4c837381#diff-439e9c54fa48d0599b18ba4da6ceb0c7L145 and just hasnt been released yet.
