### ISSUE TITLE
v5.1 Match Transactions exceptions thrown

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#1646]
We upgraded from v4.6 to v5.1 on Monday. This morning (Tuesday) our accounting team did the following:
- Created a new batch, scanned checks into it, matched the transactions and closed the batch
- Created a second batch, scanned cash envelopes into it and matched the transactions
- Scanned checks into the second batch

When they then clicked the "Match Transactions" button, the following exception was thrown:

> Message
> Collection was modified; enumeration operation may not execute.
> Stack Trace
> at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
> at RockWeb.Blocks.Finance.TransactionMatching.btnNext_Click(Object sender, EventArgs e)
> at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
> at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Further attempts to match transactions on the batch resulted in the following exception:

> Message
> Failed to load viewstate. The control tree into which viewstate is being loaded must match the control tree that was used to save viewstate during the previous request. For example, when adding controls dynamically, the controls added during a post-back must match the type and position of the controls added during the initial request.
> Stack Trace
> at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
> at System.Web.UI.Control.AddedControl(Control control, Int32 index)
> at Rock.Web.UI.Controls.GridFilter.CreateChildControls()
> at System.Web.UI.Control.EnsureChildControls()
> at System.Web.UI.Control.FindControl(String id, Int32 pathOffset)
> at System.Web.UI.Page.ProcessPostData(NameValueCollection postData, Boolean fBeforeLoad)
> at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

I was not able to get to a computer for about 20 minutes. Once I did, I logged on as our Rock Administrator (Person.Id=1), found the batch and clicked "Match Transactions". It took me to the appropriate screen, so I had our staff try again. This time it worked for them.

They have had no further issues, so unfortunately I can't suggest what might have caused the error. Thought it was worth mentioning though. I'll report back in again next week if it happens again.

**Comment by ccofnow** [comment]
Pretty much the same thing happened again this week- cash envelope scanning and matching worked fine, but clicking "Match Transactions" on the check scanning job threw the second error each time. (I did not see the first error repeated this week). The user was able to resolve the error by closing their browser and coming back into Rock.

David Stevens mentioned in Slack that they kept getting the same error last week during workflow entry, as well.

**Comment by dcs619** [comment]
I have some stack traces of this in our System Exceptions log if that would be helpful:

![screenshot 2016-08-01 17 15 08](https://cloud.githubusercontent.com/assets/1210933/17309173/9331a9be-580b-11e6-8fbe-cad08f4312ca.png)

**Comment by arranf** [comment]
@dcs619 @mikejed Did this ever get resolved? Are you experiencing issues still?

**Comment by dcs619** [comment]
I don't have access to the logs, but I think the ViewState compression Daniel introduced may have alleviated it. There was definitely an issue with the size of ViewState in earlier Rock versions that would barf for any unstable/slow network connections.

**Comment by arranf** [comment]
I'm going to close this and assume you're right @dcs619. If this bug ever resurfaces we can reopen this,
