### ISSUE TITLE
Family Manager

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#1659]
Family Manager crashes (Rock version 5.1- Family Manager Version 1.0.4) when you select a child that does not have a photo already on their record.

**Comment by ElimAdmin** [comment]
@arranf Hi Arran. Has this been resolved in 5.3 with the fixes that resolved #1702?

**Comment by edmistj** [comment]
The iPad Family Manager was never officially supported. Based on some changes in direction to the Rock mobile strategy it's not able to be moved forward to release. Based on that I'm going to close this issue. We hope to have a alternative family entry at some point in the future.
