### ISSUE TITLE
Check-in Scrolling

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#1660]
Check-in scrolling does not work on Windows 10 devices that have a multi-touch touch screen. This is both for family and individual check-in.

**Comment by edmistj** [comment]
Is this using the Windows Checkin app or straight browser. If browser I.E. Or Edge? Is it all screens?

**Comment by austinspooner** [comment]
This is using the Windows app- on Windows 10 specifically. On a previous system we had to add arrows on the page the user could hit to scroll as we had the same issue with touch. I believe we also added an indicator on the scroll that some one could drag as well.

Note - this does work fine on the iPad app as well as non Windows 10 devices.

**Comment by edmistj** [comment]
This will be hard to test/debug. What's your hardware setup?

**Comment by austinspooner** [comment]
I can replicate this on all Dell Windows 10 touch screen all in one systems. Multiple models. I can also replicate this on all laptops with touch screens we have.

**Comment by Tschrock** [comment]
Try adding
```
body {
    -ms-content-zooming: none;
    -ms-touch-action: none;
}
```
to your css. This should disable any weird touch behavior IE has by default and allow scrolling to work properly.
