### ISSUE TITLE
[EN] CalculateMetrics limits the MetricValueDate to the current schedule instance

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1666]
We've worked around this limitation for a while, but I figured someone else might have some feedback (or @mikepetersonccv might think of a better way 😄 ).

When [CalculateMetrics](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Jobs/CalculateMetrics.cs#L147) runs, it sets the MetricValueDate to the current Schedule Date.  So a metric `Sunday Attendance` has to be scheduled to run every Sunday night for the MetricValueDate to be correct.  

_Issue:_
This functionality breaks down with volunteer/class rosters where attendance is posted after the fact (sometimes 1-3 days later, depending on class size and staff or volunteer margin).

_Solution:_
When using Source: SQL, return the ValueDate as the first parameter and assign that instead of the Schedule Date.  If the first parameter isn't a Date, then set ValueDate to the Schedule Date and  MetricValue to the first parameter.  

This is how CalculateMetrics currently works in our fork -- but I'm open to other ideas.

**Comment by mikepetersonccv** [comment]
@dcs619 As discussed in Slack, here is what I'm thinking.  For a DataSource of type SQL, update it to deal with an optional MetricValueDate return field, for example: "SELECT Count(*), MetricValueDate, Partion0EntityId, Partion1EntityId, Partion2EntityId,.. FROM ..."  Then, in the case of a supplied MetricValueDate, it would update the existing value for the MetricValueDate if it is already there
