### ISSUE TITLE
[EN] Add WorkflowLogs to the Rock Cleanup Job

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1670]
The [RockCleanup](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Jobs/RockCleanup.cs) job checks and removes old pageviews, audits, temporary registrations, etc.  However, the WorkflowLog table gets fairly massive and the admin-specified parameters on the Cleanup job could be used to clean up past (completed) workflows.

**Comment by arranf** [comment]
:+1: I think Bronson has forked the cleanup job to do this

**Comment by bwitting** [comment]
@arranf, not as elegant - I just have a RunSQL job that does a `TRUNCATE TABLE WorkflowLog`  :)  This probably should be part of the cleanup job though (with some settings to customize timeframe, etc)

**Comment by dcs619** [comment]
Here's the query I'm working with so far - it deletes logs for completed entries over 3 months old:

    SELECT @@rowcount
    WHILE @@rowcount > 0
    BEGIN
	SET ROWCOUNT 100
	DELETE FROM workflowlog WITH(ROWLOCK) WHERE workflowid in (	
		SELECT id FROM workflow
		WHERE status = 'completed'
		AND ModifiedDateTime < DATEADD(month, -3, GETDATE())	
	)
    END

**Comment by edmistj** [comment]
I'm wondering if the settings should be added to the WorkflowType model to all for customizing by workflow type.  Settings to delete both the Logs and optionally Completed Workflows.

**Comment by bwitting** [comment]
@edmistj I like that idea.  In our usage, we lean heavy on the workflow log when we are developing a workflow, then it's nice to have when we first launch it (to sort out bugs), then after that we don't care.  It would be nice if we could keep adjusting that by type during/after the workflow development cycle.

**Comment by dcs619** [comment]
@edmistj Any thoughts on this?  I've been running the above query manually, but it'd be nice to include it in the cleanup job. If you provide clarification for the settings you want, I can do a PR.

**Comment by edmistj** [comment]
@dcs619 That would be perfect. I added the two fields to the workflow type model (since adding fields through a pull-request is messy). If you could add the UI to the workflow type editor and cleanup job that would be awesome!
