### ISSUE TITLE
Upgrading to 5.2 changes internal site theme to external theme

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1689]
I've just upgraded to 5.2.  Was working on the internal site creating a new event registration.  This was working fine.  Then I started to work on an external page for the event.  But when I returned to an internal site page, the theme of the internal site has changed to that of the external site.  I had both internal and external pages open at the same time.   How can I get back to the right theme for the internal site?  I now can't get to the internal menu options.  Is this a consequence of the upgrade, or something I've done?  Thanks.

This is my http://porirua.elim.org.nz/page/12 page:  (main page, named Birthdays)
![theme52](https://cloud.githubusercontent.com/assets/4658177/17518888/cc1bd608-5e9d-11e6-9317-9406ab228f18.JPG)

Looks like the Rock theme for the Rock RMS internal site is not being used?
![theme52-2](https://cloud.githubusercontent.com/assets/4658177/17519294/687cb9b2-5e9f-11e6-8dea-dd5e99e93320.JPG)

I tried to backup the /Themes/Rock directory, but somehow lost it.  I copied the Rock theme directory from my backup.  No change.

Clicking the Rock RMS line in the above page shows:
![theme52-3](https://cloud.githubusercontent.com/assets/4658177/17520170/cfbc6912-5ea2-11e6-87f9-53056ebf6d52.JPG)

Clicking Edit shows that the Rock theme is specified for the porirua.elim.org.nz site.
![theme52-4](https://cloud.githubusercontent.com/assets/4658177/17520416/c8ea3cf8-5ea3-11e6-8e9c-81c0151b0d97.JPG)

**Comment by edmistj** [comment]
You can change a theme by adding ?Theme=<ThemeName> to the query string. The internal theme would be ?Theme=Rock. If both your internal and external site run on the same host.domain then there can be some theme confusion when no page id is provided in the query string. Try setting it back on the internal site and follow back up if you continue to have the problem.

**Comment by ElimAdmin** [comment]
Thanks for the quick reply, that worked.  I am now seeing the Rock theme again.

**Comment by ElimAdmin** [comment]
Yep - that's looking fine now.  Thanks Jon.  You can close this.
