### ISSUE TITLE
Content Channel feed Item Attributes debug typo

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#1692]
I believe that the debug output on a content channel's feed (when appending 'enabledebug=true' to the end of the URL) has a typo-  it says I should use `Items | Attribute:'[AttributeKey]'` where I believe it should be `item | Attribute:'[AttributeKey]'` since it's all supposed to be within the `{% for item in Items %}` loop.

**Comment by nairdo** [comment]
Which block are you referring to?

**Comment by nairdo** [comment]
@ccofnow Thanks for sending me some additional details.  Using that I've pinpointed the location where it's happening: https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Utility/ExtensionMethods/LavaExtensions.cs#L256

I'm checking if I can change the `parentElement` to `parentElement.Singularize().ToLower()` without causing an additional problem.
