### ISSUE TITLE
Validation doesn't fire for missing amount when using 3 step gateway

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1700]
# Context

Using the [give page](http://rock.rocksolidchurchdemo.com/page/186), enter a valid amount and click Next when using a 3 step gateway.  Then click Previous, and remove the amount (or make it invalid), then click Next again.  The page will allow you to give as the SelectedAccount.Amount is still the value of the previous gift amount.

Note: I don't see a Previous button unless you're using a 3 step gateway, so you won't be able to reproduce this behavior otherwise.
# Expected Behaviour

An error message should be added to the page from ProcessPaymentInfo saying `Make sure you've entered an amount for at least one account`.  This happens the first time you try to give, as SelectedAccount.Amount isn't set yet.
# Environment and Diagnostics Information

Rock 5.2

**Comment by dcs619** [comment]
Something else that flagged during code review: 

the [jQuery selector `$('a[id$=""btnNext""]')` ](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Finance/TransactionEntry.ascx.cs#L2215) won't match anything as those controls were updated to handle 3 step gateways.

**Comment by dcs619** [comment]
Adding an else condition to [L307](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Finance/TransactionEntry.ascx.cs#L307) forces the account to validate when the amount isn't valid.  Haven't followed up with the jQuery selector yet.

    else                            
    {
    SelectedAccounts[item.ItemIndex].Amount = 0;
    }

**Comment by garrettjohnson** [comment]
Not sure when it was fixed, but this is no longer an issue in 6.8.
