### ISSUE TITLE
Background check "Required" discrepancy

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#1701]
# Context

Attempting to send Background Check Request with the stock BGC request.

![image](https://cloud.githubusercontent.com/assets/19762670/17639592/36e8b998-60b9-11e6-9a69-78b64d877822.png)

TLDR, My Rock's default BGC workflow had an inconsistency with the requirement of the Campus attribute.  Not hearbreaking, but confusing coming to it.

Our Rock install was 4.0 to start and has been upgraded from there to 5.2

My resolution was to just uncheck the Required box for Campus because it's not listed as required by the BGC request action.

BONUS: when I click cancel...
![image](https://cloud.githubusercontent.com/assets/19762670/17639636/a2b8eb3e-60b9-11e6-9fb5-7c15f0012961.png)
Making "Cancel" not a very helpful button if the form's SSN box is empty isn't at least partially filled in.

**Comment by arranf** [comment]
@NuclearTacos Could you split these into two separate issues and use the template? Thanks!
