### ISSUE TITLE
Wait operation time out errors - adding or saving  Person v5.2

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1702]
# Context
Saving a new person when adding via the New Family page with no birth date. 
And saving changes to an already existing person with no photo.  (Same as #1659 ?)

# Expected Behaviour
Save with no errors.

# Actual Behaviour
Save fails with 'Wait operation timed out' error message.  Complete text of error message appears below.  Cannot add a person without a birthdate, and cannot edit a person with no photo.

# Steps to Reproduce
Can't reproduce on the demo site.  Only observed since upgrade to 5.2.  (#1659 suggest 5.1.)

I am seeing two conditions:
Adding a new person where I do not enter a BirthDate.  Address and phone numbers are irrelevant. I get a Wait Time Out Error and an Exception Error.  Text below.  Note "Error getting value from 'PhotouUrl' on Rock.Model.Person."

Saving a person with no photo gives the same, but slightly different error text due to save, not add, and an exception error.  Note "Error getting value from 'PhotoUrl' on 'System.Data.Entity.Dynamic.Proxies.Person_  .... "

# Environment and Diagnostics Information
[RockDiagnostics-VSERVER576.txt](https://github.com/SparkDevNetwork/Rock/files/416395/RockDiagnostics-VSERVER576.txt)

* **Rock Version**:   Rock McKinley 5.2
* **Client Culture Settinng**:   en-NZ

# Screenshots
_Provide us some screenshots of the problem (if appropiate) to help us identify what's occurring. Arrows and labels are helpful._

# Wait Time Out Text on Add
[Adding.txt](https://github.com/SparkDevNetwork/Rock/files/416407/Adding.txt)

# Exception Email on Add
[Exception-add.txt](https://github.com/SparkDevNetwork/Rock/files/416410/Exception-add.txt)

# Wait Time Out Text on Edit
[Editing.txt](https://github.com/SparkDevNetwork/Rock/files/416411/Editing.txt)

# Exception Email on Edit
[Exception-edit.txt](https://github.com/SparkDevNetwork/Rock/files/416413/Exception-edit.txt)

**Comment by arranf** [comment]
:+1: For filling this all out, it really helps.

**Comment by ElimAdmin** [comment]
Hi Arran.  I wonder if both these problems are related to 'Error getting value from PhotoUrl.'

**Comment by ElimAdmin** [comment]
Note that to reproduce the Edit error, I had to make a change to at least one field prior to saving. Clicking Edit on Person, then save with no changes is not a problem.

**Comment by ElimAdmin** [comment]
This is consistently reproducible for us.  Let me know if there's anything else I can do to help or any other info I can provide, or if you'd like login details.  The only things I can think to do are to try to debug this myself and follow it through to where it errors.  I also wonder if this is because of the number of Person attributes we have.

**Comment by BEGamache** [comment]
Noticed the same error in our v5.2 dev site when I was using it to train our staff on adding new families everyone at the training was experiencing the same error.

**Comment by azturner** [comment]
@ElimAdmin & @BEGamache Do you know what version (and service pack ) of SQL you are using? Ken, I can see you are using 2012, but what Service Pack?

**Comment by ElimAdmin** [comment]
@azturner We're hosted on 3essentials.  
Select @@version
results in
Microsoft SQL Server 2012 - 11.0.2218.0 (X64) Jun 12 2012 13:05:25 Copyright (c) Microsoft Corporation Express Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor) 

Here are the Wait Time and Exception Errors for Edit Family if they are any use.
[EditFamilyException.txt](https://github.com/SparkDevNetwork/Rock/files/419552/EditFamilyException.txt)
[EditFamilyWaitOperationTimeOut.txt](https://github.com/SparkDevNetwork/Rock/files/419551/EditFamilyWaitOperationTimeOut.txt)

**Comment by BEGamache** [comment]
@azturner 

Microsoft SQL Server 2014 - 12.0.2269.0 (X64) 
Jun 10 2015 03:35:45 
Copyright (c) Microsoft Corporation
Web Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by azturner** [comment]
FYI, This is due to a combination of using a Person workflow trigger, The person object incorrectly including photoURL when being serialized to JSON, and a refactor of the GetPersonPhotoURL in V5. We will update the person object to not include photoUrl when being serialized.

**Comment by ElimAdmin** [comment]
@azturner Thanks David.  You are amazing.  How far away is 6.0?  We are running 5.2 in production so need to decide whether we wait or wind back...

**Comment by azturner** [comment]
You'd actually have to wind back to 4.x. We'll try to get this fix in v5.3 which is coming soon (not sure how long for v6).

**Comment by ElimAdmin** [comment]
@azturner.  Thank you.  Appreciate your help always.  Wish I could come to RX.
