### ISSUE TITLE
Full credit card info is exposed in Exception Log

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1708]
# Context

While tracking down some exceptions from event registration payments, I observed the full credit card info (number, exp date, cvvc) are visible in the Form Data of the exception.
# Expected Behaviour

I expect that credit card info wouldn't be exposed in plain text anywhere.
# Actual Behaviour

Full credit card info is visible within an exception.
# Steps to Reproduce
1. Make an event registration payment with a bad credit card number
2. An exception of type: "[23] Invalid account number: Unsupported Credit Card type" should show up in the exceptions log.
3. Click on the exception, then click Show Form Data. Full credit card info will be visible in the form data.

I think an argument could be made that these exceptions are the result of a bad card number, so the actual data exposed is useless, but I'm not sure that's a valid argument as the number entered could only be off by one digit, and similar exceptions for other (non-bad-card-number) reasons probably also expose the same info in the form data. 

Not sure there's any mitigation for this, just wanted to bring it to someone's attention.
- **Rock Version**: 5.1

![exception detail _ rock rms - mozilla firefox 2016-08-16 10 39 08](https://cloud.githubusercontent.com/assets/3903408/17705416/dfe7f176-639d-11e6-899f-daced957c5da.png)

**Comment by JimMichael** [comment]
I forgot to mention that this is using the Payflow Pro gateway.

**Comment by JimMichael** [comment]
Upon further investigation, it looks like these exceptions are the result of valid credit card numbers being entered with spaces (either manually or due to copy/paste). The form doesn't seem to validate the input and (at least with the Payflow Pro gateway) allows the form to be submitted with spaces in the cc number and it throws the exception. Let me know if I need to open a different issue for this.

**Comment by tom-powers** [comment]
Jim, thanks for mentioning the spaces issue as well.  One of our staffers was registering for an event yesterday and generated this same error, so I wasn't sure if the spaces were the issue until now.

**Comment by JimMichael** [comment]
Just mentioning that this is still an issue as of Rock 6.1

**Comment by edmistj** [comment]
At the very least we should wrap this so an exception is always caught even if a generic message needs to be shown. But we should also remove spaces from cards that are inputted for Payflow Pro.

**Comment by JimMichael** [comment]
I have a vague recollection that the spaces issue was fixed around the time I opened this request, but I can't find a PR for it. Just mentioning that in case David looks at the code and is confused that that particular part of this issue is already fixed ;-)

**Comment by azturner** [comment]
The space issue was reported/fixed on another issue (#1728)

**Comment by azturner** [comment]
After v7:
![image](https://cloud.githubusercontent.com/assets/548180/24314880/2a2cc440-10a1-11e7-8e2a-97a9e184ccb6.png)

**Comment by taylorbrooks** [comment]
Not to be an alarmist...

IMHO, this should be a hotfix. If unencrypted card data is leaked into logs and Rock keeps those logs around; then those organizations are not complying with PCI-DSS and probably doing so unknowingly.

The minimum fine for simply being out of compliance (no breach) is $5,000 per month (up to $100k depending upon your volume). These fines can also be levied retroactively.

This is a good guide on PCI compliance: https://squareup.com/townsquare/pci-compliance-checklist

b1e1987 The commit looks pretty simple, any chance it can be included in 6.10?

**Comment by azturner** [comment]
@taylorbrooks Thanks for catching that. We've added it to v6.10.

**Comment by taylorbrooks** [comment]
👍
