### ISSUE TITLE
Cursor defaults to text on datepicker

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1710]
# Context
When hovering over labels, or the previous/advance arrows the cursor turns to a text selection cursor

# Expected Behaviour
Cursor to default to pointer

# Actual Behaviour
Cursor changes to text selection

* **Rock Version**: 5.2

# Screenshots
Can't show the cursor on OS X, but the month name and arrows default to text selection...
<img width="329" alt="screen shot 2016-08-16 at 9 49 02 pm" src="https://cloud.githubusercontent.com/assets/374209/17725002/e2652dfc-63fb-11e6-9fa7-7628a8df8181.png">

**Comment by arranf** [comment]
Fixed in #1739
