### ISSUE TITLE
Thank-you and on-going Are Hyphenated Unnecessarily 

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1711]
# Context

In the system emails "[thank-you](https://github.com/SparkDevNetwork/Rock/search?utf8=%E2%9C%93&q=thank-you)" and "[on-going](https://github.com/SparkDevNetwork/Rock/search?utf8=%E2%9C%93&q=on-going)" are hyphenated when they [shouldn't](http://www.future-perfect.co.uk/grammar-tip/is-it-thank-you-thankyou-or-thank-you/) [be](http://www.future-perfect.co.uk/grammar-tip/is-it-on-going-or-ongoing/).
# Steps to Reproduce

See search links above; found in multiple Rock system emails.

**Comment by dcs619** [comment]
:heart: :see_no_evil:

**Comment by johnthepink** [comment]
I think I can handle this 😸

**Comment by ethan-sparkdevnetwork** [comment]
A new migration will correct the spelling for SystemEmails and Attribute/Value that were automatically created by Rock. If any user edits were done then the data will not be changed.
