### ISSUE TITLE
Phone Number Field Type bug in Group Member Attributes 

### ISSUE THREAD

**Issue by tbice** [SparkDevNetwork/Rock#1713]
# Context
We noticed that some people were missing from groups after we converted.  

# Expected Behavior
We expected all the people as well as their custom field info to be displayed in the Rock groups after conversion.  Only the people that did not have a phone number entered in the group member attribute were showing up.

# Actual Behavior
Anyone that had a phone number entered in the group member attribute was missing from the list of group members.

# Steps to Reproduce
1. Step 1 - Add a group member attribute with field type "Phone Number"
2. Step 2 - Enter a phone number on someone in the group
3. Step 3 - That person will disappear from the list of group members
4. Step 4 - Changing the field type to 'Text' will make the missing people display again. 

# Environment and Diagnostics Information
* **Rock Version**: Rock McKinley 5.0
* **Client Culture Settinng**: en-US
[RockDiagnostics-ROCK-WEB01.txt](https://github.com/SparkDevNetwork/Rock/files/422927/RockDiagnostics-ROCK-WEB01.txt)

**Comment by azturner** [comment]
This is fixed in v5.3 (currently in Beta) by this commit: https://github.com/SparkDevNetwork/Rock/commit/e1287ef76f03a8cf52110556180b069616230d3d
