### ISSUE TITLE
Event Registration: Credit Card type not saved or recalculated

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1717]
### Prerequisites
* [x] Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?
### Description

Clicking `Previous` and `Next` between pages in Event Registration retains the Credit Card #, Expiration Date, and Card Security Code.  However, it doesn't retain the card type that was set by the `card-logos` JS .

See http://rock.rocksolidchurchdemo.com/Registration/test for a current example.  You need a paid event for this to be reproduced.

**Expected behavior:** [What you expected to happen]

I would expect the card type to be saved between page navigation since all other fields are saved.  Alternatively, I could see all card-relevant data be wiped out when clicking `Previous`, as this performs a postback to the server.

**Actual behavior:** [What actually happened]

All data is retained except the card type.

-----
Assigned to ChuckB for Solution Proposal

**Comment by cbump** [comment]
I propose this solution: We can just manually trigger the keyup event as soon as we bind the CreditCardTypeDetector to the credit-card input.  We can just add this line to https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/RegistrationEntry.ascx.cs around line 4294:

`    $('.credit-card').keyup();`
