### ISSUE TITLE
Check-in Configuration shows inactive groups

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#1719]
This maybe be "as designed" - or it might be a feature request - or even a bug- but Check-in Configuration shows inactive groups. This makes the list extremely long for some of us that have a ton of historical groups. Could this be a block setting? Or just have it not display inactive groups. I cannot think of why you would want to enable checkin on an inactive group.

**Comment by JimMichael** [comment]
We've noticed this too and it will become a problem over time.

**Comment by arranf** [comment]
@austinspooner Could you use the template (or a variant that makes sense for non-bugs) next time round. It makes everyone's life easier.

**Comment by edmistj** [comment]
This will be implemented in this pull request. https://github.com/SparkDevNetwork/Rock/pull/2066
