### ISSUE TITLE
Add a contributor guide

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1720]
### Prerequisites
- [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
- [x] Did you include your Rock version number and client culture setting?
- [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

I'd like to propose adding a contributor guide file to the Rock project. 

[View here](https://gist.github.com/garrettjohnson/1e1036264733c1dd65ceb06d6a4425af). 

I'm fairly new to the Rock community, and incredibly inexperienced with C#... so I put together the best copy/paste remix of the GitHub wiki info I could find and best practices from [other](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) [open](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md) source projects.
#### Open Questions
- [ ] Does the Spark Development Network need a signed contributor agreement ([mentioned here](https://github.com/SparkDevNetwork/Rock/wiki/Creating-Pull-Requests))?
- [ ] Are enhancement requests appropriate for GitHub issues?
- [ ] Are styleguides current and in line with established coding standards?
- [ ] Are Issue and Pull Request Labels correct?
### Versions
- **Rock Version:** 5.2
- **Client Culture Setting** en-US

**Comment by arranf** [comment]
@garrettjohnson I think some of this can be talked about at the developer discussion meeting this Friday

**Comment by arranf** [comment]
@garrettjohnson A quick update. This has been discussed and @nairdo is going to go away and read this, make changes if necessary, and pull this in.

**Comment by nairdo** [comment]
This is now linked to the wiki home page.
