### ISSUE TITLE
Process New Payment /Add Manual Payment buttons not appearing on Registration View / Edit Payments

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1724]
### Prerequisites
- [X] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
- [X] Did you include your Rock version number and client culture setting?
- [X] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

On v1.5.2, the Process New Payment and Add Manual Payment buttons are not appearing when on Registration Details > View / Edit Payments, so we can't manually add a payment for a registration.
### Steps to Reproduce

On the demo site, add a registration that has a cost. 
Manually add a registrant, and then Edit Registration.
Click View / Edit Payments.  

**Expected behavior:** Process New Payment and Add Manual Payment buttons should appear, like in the documentation: 
![registration-payments-add](https://cloud.githubusercontent.com/assets/1859094/18067127/69f87dc0-6e09-11e6-83d4-d5da75f5fe7a.png)

**Actual behavior:** Those buttons don't appear
![2016-08-29 13_47_47-registration _ rock rms](https://cloud.githubusercontent.com/assets/1859094/18067117/61c5e71e-6e09-11e6-835c-8f6412985554.png)
### Versions
- **Rock Version:** 1.5.2
- **Client Culture Setting**en-us

**Comment by azturner** [comment]
@bwitting I wasn't able to reproduce this on demo site: http://rock.rocksolidchurchdemo.com/page/5349?RegistrationId=4

Is that template, instance, or registration configured differently than yours somehow?

**Comment by arranf** [comment]
@Tschrock Is this still an issue for you guys?

**Comment by garrettjohnson** [comment]
Looks like this one got fixed
