### ISSUE TITLE
Demo Site

### ISSUE THREAD

**Issue by michellemoena** [SparkDevNetwork/Rock#1729]
I cannot get the demo site to work

Michelle Moena
michelle@gracebellingham.org

**Comment by JayGreentree** [comment]
Do you mean: http://www.rocksolidchurchdemo.com/
Its working here. If you are trying to get a self hosted demo working jump on the Rock slack and someone can assist you there. http://www.rockrms.com/slack

**Comment by michellemoena** [comment]
I am trying to check out the church management software, how do I do that?

**Comment by JayGreentree** [comment]
The first link is the demo of the rock external site the back-end can be found here: http://rock.rocksolidchurchdemo.com you can login with the info provided on the login page for both

**Comment by michellemoena** [comment]
I cannot get it to let me log in. Oh well

**Comment by edmistj** [comment]
Appears to be working, can't reproduce.

**Comment by michellemoena** [comment]
I just figured it out, it won't work on Chrome but does with
internet explorer!


*Michelle Moena*
*360-303-1593*
*michellemoena@gmail.com <michellemoena@gmail.com>*

**Comment by arranf** [comment]
Hey Michelle,
It definitely works with Chrome for me. You might want to take a look at
your browser

**Comment by edmistj** [comment]
Might be a chrome extension you have installed?
