### ISSUE TITLE
Complex conditionals in lava do not work

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#1730]
### Description

According to the Lava documentation (http://www.rockrms.com/page/459), complex conditionals such as `true and (false or true)` can be used, however this doesn't look to have ever been implimented.

As it stands right now, it looks like everything is evaluated Left-to-Right - Unless you put parenthesis around the beginning, in which case it only evaluates that beginning part. 

### Steps to Reproduce

Try to use complex conditionals inside of lava. (The example in the docs is broken too)
For Ex: `{% true and (false or true) %} true {% else %} false {% endif %}`

**Expected behavior:** The statement is evaluated logically. In the given example I would expect a `true` result.

**Actual behavior:** The statement is evaluated left-to-right. In the given example I get a `false` result.

### Versions

* **Rock Version:** Rock McKinley 5.2
* **Client Culture Setting** en-US

**Comment by edmistj** [comment]
I see that your syntax doesn't work, but I'm not sure Liquid (Lava) supports that type of evaluation (comparisons without operators). The code below works for me.

```
{% assign var1 = "apples" %}
{% assign var2 = "oranges" %}
{% assign var3 = "grapes" %}

{% if var1 == "apples" and (var2 == "oranges" or var3 == "grapes") %} 
    true 
{% else %} 
    false 
{% endif %}
```

This seems more like what would be a typical use case. Am I missing something? You might check the DotLiquid project for more insight http://dotliquidmarkup.org/

**Comment by Tschrock** [comment]
Looked at dotliquid and it never mentions anything about parentheses, and shopify's docs say it isn't supported.

As far as using comparisons without operators, it seems to work properly in other cases when there's only 1 or 2 conditions. Even using your format, there's still an issue when the parenthesis are at the beginning:
`(var1 == "apples" or var2 == "oranges") and var3 == "grapes"` -> `true`
`(var1 == "apples" or var2 == "oranges") and var3 == "notgrapes"` -> `true`

I also checked this on DotLiquid's 'try it online' tool and got the same issue.

**Comment by edmistj** [comment]
I read through the issue log at dotLiquid and found the following: https://github.com/dotliquid/dotliquid/issues/92

We'll remove the nested conditions from the docs.
