### ISSUE TITLE
Group scroller doesn't work on touch devices

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1731]
### Prerequisites
- [ x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
- [ x] Did you include your Rock version number and client culture setting?
- [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
- [x ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

The group tree "horizontal scroll" control does not work for us on touch-enabled devices.
![slack - rock rms 2016-09-01 13 50 58](https://cloud.githubusercontent.com/assets/3903408/18180219/887bb5f2-704b-11e6-8f41-9e428d2de993.png)
### Steps to Reproduce
1. Go to the Group Viewer
2. Adjust browser narrow-enough to cause the horizontal scroll control in the Groups list to appear
3. On touch-enabled devices (Thinkpad 440T laptop and iPads are two we've tried) we are unable to grab the control and move it, unable to "two finger horizontal scroll", or anything else. Nothing we've tried gets the scroll to work on these devices, and their only commonality is they are touch-enabled.

**Expected behavior:** [What you expected to happen]

The horizontal scroll control would work as it does on non-touch-enabled devices.

**Actual behavior:** [What actually happened]

It don't work ;-) This makes the Group Viewer very difficult to use as many of our groups have long names that start out with identical text and are unique only towards the end.
### Versions
- **Rock Version:** 5.1 and 5.3beta
- **Client Culture Setting** [Enter Client Culture here]  
  [Included from your Rock installation](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information)

**Comment by edmistj** [comment]
Still issue in v6.x
