### ISSUE TITLE
Event Registration Instance Not Secured

### ISSUE THREAD

**Issue by tbice** [SparkDevNetwork/Rock#1732]
### Prerequisites

* [ x ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [ x ] Did you include your Rock version number and client culture setting?
* [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [ x ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We have our event registration security set up so that only a few people should be able to do any editing.  Staff Workers should be able to view the list of registrations and registrants, but not be able to add, change or delete them.  However, while logged in as a 'Staff Worker', I am able to make changes to the instance and the registrations/registrants.

### Steps to Reproduce

1. Set security on all event pages and blocks to give Staff Workers View access only
2. Go to an event instance while logged in as a Staff worker and edit away!

**Expected behavior:** 
Staff Workers should be able to view but not change anything

**Actual behavior:** 
Staff Workers can Edit instances, registrations, and registrants.

### Versions

* **Rock Version:** [Rock McKinley 5.0
[RockDiagnostics-ROCK-WEB01(1).txt](https://github.com/SparkDevNetwork/Rock/files/450742/RockDiagnostics-ROCK-WEB01.1.txt)
]  
* **Client Culture Setting** [Enter Client Culture here]  
[Included from your Rock installation](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information)

**Comment by JimMichael** [comment]
I can also verify that this behavior exists in 5.3beta. I don't believe this is an issue with the Staff Role per-se... but any role that's allowed to view the Registration Instances block can edit it.

**Comment by edmistj** [comment]
@tbice Looking into this a bit tonight. Can you clarify a couple of other settings for me?  Security on the registrations is a combination of block security and entity security. Sounds like you have the block security nailed down. Can you confirm the security on the Registration Template. Also you can set the default security for all Registration Templates and Instances under 'Admin Tools > Security > Entity Administration'.

Let me know what you find.

**Comment by JimMichael** [comment]
Both my Rock.Model.RegistrationInstance and Rock.Model.RegistrationTemplate entities have default security of All users - View and Rock Administrator - Edit. All of the other Registration-related entities have the same. On the events page/blocks, Staff Workers - View, Event Admin / Rock Admin - Edit. 

So with only View rights for a Staff Worker, I get add/delete functions on a registration Instance, but not on the template.

**Comment by tbice** [comment]
I just double-checked all of my registration-related entities and mine are set up similar to what Jim describes: All Users have View, and only Rock Admins have Edit and Administrate

**Comment by edmistj** [comment]
Is there any way I could get a login to one of your systems to look at it? I think I have it working correctly on the demo site. If you login as Ted Decker (tdecker/password) he can view the event registration instance but can't edit it.

**Comment by tbice** [comment]
I just logged in as Ted Decker and found that he does not have the edit button on the instance which is good.  I also found that he can't add, change or delete current registrants.  But one thing is confusing and I would suggest be changed to be more consistent with how Groups work/look.  In Groups, the red 'x' is more pale so you can tell that you don't have access to delete people.  Also the '+' is removed so you can easily see that you can't add new people.  In Registrations you don't know until after you click the 'x' or the '+' that you actually don't have access to those items.  When I tried all of these things in our live environment as a Staff Worker I found that I do have the edit button and can make changes to the instance.  I can add and change registrants, but not delete them.
