### ISSUE TITLE
External Site Group Finder - Enhancements

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1733]
### Prerequisites
* [x] Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [ ] Have you attached your [environment and diagnostics information ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?
### Description

A couple things for the group finder on the external site.

The time of day filter seems a little more complex than what it should be for guests or members who are searching for a connect group/small group. If there is a better way to ask for time of day without asking or requiring them to select less than, greater than, equal to etc. that would be great. I understand what it does and thinks it works fine but for a normal or casual user it could be complex. So if there is a way to simply filtering time of day I think that would be better.

Second, I don't know if it is possible but could the group attributes that appear in the grid word wrap if it is a multi-select attribute. We had some attributes we wanted to show but because some attributes extended the column wide the user would have to scroll to the right to see other details and the register button. If it isn't possible to word wrap multi-select attribute columns maybe place the register button as the first column?

**Expected behavior:** [What you expected to happen]
More simple way of selecting a time or time range for the filter than having to select conditional logic, which may not be simple or intuitive from a normal user's standpoint.

with multiple columns displaying on grid, equalizing the spacing of the columns would be nice in order having to limit the need to scroll to the right to see other columns and/or the register button.

**Actual behavior:** [What actually happened]
Having to select desired logic for desired time range.

multi-select columns don't word wrap because it is one string without spaces which causes columns to become wider than desired.

### Versions
* **Rock Version:** v5.2

**Comment by edmistj** [comment]
Could you add a screenshot?

**Comment by BEGamache** [comment]
Sure. You can also look at it here: https://my.crossroadschristian.org/ConnectGroups
Tomorrow I will remove the description and possibly the Age Range to make the register button visible without scrolling but I know in the future we may let our leaders edit their group descriptions and at that time we would like to display it again and I would like to display age ranges but some of our general groups aren't limited by age so those are the ones that make the column wider.

![screen shot 2016-09-01 at 5 55 34 pm](https://cloud.githubusercontent.com/assets/5738650/18187321/176788dc-706e-11e6-8390-ce40bc279e0b.png)
![screen shot 2016-09-01 at 5 56 02 pm](https://cloud.githubusercontent.com/assets/5738650/18187322/1769554a-706e-11e6-89dc-92164830a591.png)

**Comment by NuclearTacos** [comment]
I share the sentiment regarding the Time of Day filter being confusing to the average user.  Definitely though, it's confusing that there's a Between option and it only presents one box.  I think a better implementation would be only using between, so the end user only chooses X to Y time. Ideally, if you only entered the first parameter, it would assume the last is the end of the day and vice versa.

@BEGamache I used defined types instead of multi-select.  What you're seeing seems to be a bug to me, but if you need something to work today, try defined types instead of multi-select.

**Comment by nairdo** [comment]
Hello amazing community member! We've recently moved 'feature requests' to our own "Ideas" system on our Community site at: http://community.rockrms.com/ideas 

If you'd like to re-propose your idea and put it up to the vote, **please re-submit your idea there**.  Thanks!
