### ISSUE TITLE
Group Finder (External Site) - Map drop pin showing View Group button when linked detail page is blank

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1735]
### Prerequisites
- [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
- [x] Did you include your Rock version number and client culture setting?
- [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

In Group Finder on the External site when the block has an empty Linked Group Details page attribute/field the View Group button is visible when you click on a drop pin even though the lava used is suppose to check and make sure only to show that button when Group Details linked page isn't empty.
### Steps to Reproduce

http://rock.rocksolidchurchdemo.com/page/236
Hit search.
Click on a drop pin. View Group button visible.
Edit block settings. Linked pages tab should have Group Details Linked Page empty. 
Lava for the map should have a condition to only show that button when a details page is linked.

**Expected behavior:** [What you expected to happen]
No View Group button if no linked detail page

**Actual behavior:** [What actually happened]
View Group button visible.
### Versions
- **Rock Version:** v5.2

**Comment by garrettjohnson** [comment]
Related to #2172, will need the migration mentioned on PR #2449 to close

**Comment by arranf** [comment]
Fixed.
