### ISSUE TITLE
Server Error in '/' Application.

### ISSUE THREAD

**Issue by gladsonj** [SparkDevNetwork/Rock#1741]
### Prerequisites
* [ N] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [ Y] Did you include your Rock version number and client culture setting?
* [ N] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [ Y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
I had installed rockrms at https://admin.paravila.com
This is a External shared hosting. No issues. No Challenges with Installation or Administration,
I was still learning the CMS and Security setup. So, wanted to keep this current setup as a backup and perform a fresh installation. Logged in as admin, cleared the cache and then copied the DB to a new DB and modified the file "web.ConnectionStrings.config" to point to the copied DB.

I was unable to stop the IIS service before doing this, as I don't have access to IIS settings. I only have Plesk CP to the Windows Hosting.

After that, I am getting the following Error:
Server Error in '/' Application.
Runtime Error
Description: An exception occurred while processing your request. Additionally, another exception occurred while executing the custom error page for the first exception. The request has been terminated. 

### Steps to Reproduce

1. cleared Cache
2. copied the DB
3. Modified the file web.ConnectionStrings.config to point to the copied DB.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
Server Error in '/' Application.

Runtime Error

Description: An exception occurred while processing your request. Additionally, another exception occurred while executing the custom error page for the first exception. The request has been terminated. 

### Versions

* **Rock Version:** [5.2]  
* **Client Culture Setting** [Sorry, unable to generate]

**Comment by edmistj** [comment]
If you find the line below in your web.config file. Change the mode="On" to "Off". This should give you a better error message. Be sure to turn it back on when done.

<customErrors mode="On" defaultRedirect="/Error.aspx" redirectMode="ResponseRewrite" />

**Comment by edmistj** [comment]
Closing as this isn't an issue with the software. If you need additional help please post again on our Q&A. 
http://rockrms.com/Ask
