### ISSUE TITLE
Workflow Entry is not displaying the proper icon/name

### ISSUE THREAD

**Issue by cbump** [SparkDevNetwork/Rock#1748]
### Prerequisites

* [ Y] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [Y ] Did you include your Rock version number and client culture setting?
* [ N] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [Y ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using the WorkflowEntry block with a workflow type that is configured as a block setting (not dynamic) the icon and workflow name are not populating properly.

### Steps to Reproduce

1. Create a new page.
2. Add the workflow entry block.
3. Configure the block by selecting a workflow type so it only handles that workflow.
4. Load the page.  

**Expected behavior:** The icon and work name from the Workflow Type should be displayed.
![good](https://cloud.githubusercontent.com/assets/1248118/18315048/864d07ee-74e3-11e6-8a95-d29443a59695.PNG)

**Actual behavior:** The block header will show a gear icon (default) and the text "Workflow Entry" every time regardless of the settings on the workflow type.
![bad](https://cloud.githubusercontent.com/assets/1248118/18315058/8f825b16-74e3-11e6-95f7-07d916ceeeba.PNG)

### Versions

* **Rock Version:** Rock-6.0  
* **Client Culture Setting** en-US
[Included from your Rock installation](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information)

**Comment by arranf** [comment]
Fixed in #1749
