### ISSUE TITLE
Labels print more than once per person

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#1755]
When a label is setup to print once per individual using family check-in- and the individual checks into more than one check-in area the label prints once for each check-in area.

1.  Setup a label print once per person
2.  Assign the label to a group in Weekly Service Check-in Area as well as volunteer check-in area.
3. Check a person into 1 class in Weekly Service Check-in area and another in the volunteer check-in area.
4. You will get to labels for that person instead of just one.

**Expected behavior:** 
I would expect that even though there are two check-in areas being used (1 primary and one additional area) that you would still only get one label. 

**Actual behavior:** [What actually happened]
You get 2 labels.

**Comment by arranf** [comment]
Hey Austin,
You're missing a few details here that'd help this issue get resolved.

Could you include the following information:

   1. Can you reproduce this on another Rock installation?
   2. Your diagnostics information, Rock version, and culture settings.
   3. Screenshots of your check-in configuration?

**Comment by austinspooner** [comment]
Here are screen shots: https://www.evernote.com/l/AAL080tGQLBBzaCn1G4C3ogrRMp1M0jBo_E

Rock Version: Rock McKinley 5.2

Client Culture Setting: en-US

[RockDiagnostics-NCBCSVRRMS01.txt](https://github.com/SparkDevNetwork/Rock/files/462462/RockDiagnostics-NCBCSVRRMS01.txt)
