### ISSUE TITLE
Error in Group Viewer Menu

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1758]
When navigating to the Group Viewer, the following error occurs.
![image](https://cloud.githubusercontent.com/assets/7409839/18443985/324fa664-78cc-11e6-9e20-9a03d756ac19.png)

The Rock version is 6.0 alpha and client culture setting is en-US.

[RockDiagnostics-RIFT.txt](https://github.com/SparkDevNetwork/Rock/files/467824/RockDiagnostics-RIFT.txt)

**Comment by DerekMangrum** [comment]
There was just a discussion about this in the #alpha-testers channel on Slack. The quick-fix is there and a permanent fix will be in the next alpha.

**Comment by nairdo** [comment]
I have not tracked it down yet, but somewhere the System.Runtime was removed from the web.config during one of the recent updates.  @BelAirIT If you add the line back in manually, can you also confirm that it corrects the problem?

I would recommend you just make a copy-paste of your "System.Runtime.Caching" line and just remove the ".Caching" from it so it looks similar to this:

Example:
```
      <assemblies>
        <add assembly="System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A"/>
        <add assembly="System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A"/>
...
```

**Comment by BelAirIT** [comment]
@nairdo That seems to have done the trick.

**Comment by arranf** [comment]
@nairdo I'm going to assign this to you to close when this fix or a workaround gets pushed back in

**Comment by nairdo** [comment]
As far as I can tell, the web.config.rock.xdt that was [checked in on Nov 9th, 2016](https://github.com/SparkDevNetwork/Rock-UpdatePackageBuilder/commits/master/NuGetLocal/artifacts/1.6.0/web.config.rock.xdt) has the necessary reference.  Closing this ticket.
