### ISSUE TITLE
Ability Level Hint Redirect

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1760]
In 6.0 alpha, when adding a new family member who is a child, clicking the blue question mark hint doesn't display a result. In only brings you back to the top of the screen.
![image](https://cloud.githubusercontent.com/assets/7409839/18456406/85f89a76-7905-11e6-907d-51dc05bb25e2.png)

**Comment by edmistj** [comment]
@tcavaletto can you look at this? Feel free to submit the fix the release-6.0 branch

**Comment by tcavaletto** [comment]
Fixed in https://github.com/SparkDevNetwork/Rock/commit/bdd11a35cc1fb4b4d4ab56140b1d098bcc509102
