### ISSUE TITLE
Unable to Edit 'Group and Role' Attributes

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1761]
In the alpha 6.0 build, adding a group and role attribute, saving, and then trying to edit the attribute sends up the following error.

![image](https://cloud.githubusercontent.com/assets/7409839/18485061/0e57507a-79a0-11e6-82b9-03a5240517b6.png)

**Comment by arranf** [comment]
**Steps to Reproduce**:
1. Add a `Group and Role` attribute to a workflow
2. Save the workflow
3. Edit the workflow 
4. Attempt to edit the attribute

**Comment by arranf** [comment]
Duplicate of #1687

**Comment by cabal95** [comment]
I'll add that this isn't limited to Workflows. I experienced this the other day as a Global Attribute when testing something unrelated. I figured it was because I was making lots of changes to the attribute type but looks like this is just a bug with the `Group and Role` attribute in general.

**Comment by cabal95** [comment]
This should now be fixed in the develop branch.
