### ISSUE TITLE
Canceling Scheduled Giving in Rock doesn't cancel it in Transnational

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1762]
### Prerequisites
- [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
- [x] Did you include your Rock version number and client culture setting?
- [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

A contributor was able to setup a weekly giving schedule in Rock. He decided to switch to Push Pay and canceled the schedule in Rock. For some reason that didn't sync with Transnational. I don't know the date that he canceled the schedule but it has been a few days and he still got charged for the one he setup in Rock. Rock doesn't show the schedule but when logging into Transnational he appears under scheduled transactions. We canceled it in Transnational but it doesn't look like it syncs from Rock to Transnational for canceling scheduled transactions. We are on v5.2 and I know the monthly schedule bug has been fixed in 5.3 but not certain if this is fixed in 5.3 as well. 
### Steps to Reproduce
1. Create Schedule Transaction in Rock
2. Delete Schedule 
3. Log into Transnational and schedule still present.

**Expected behavior:** 

Schedule removed from Transnational

**Actual behavior:**

Schedule removed from Rock but not Transnational which leads to continued giving based on the schedule.
### Versions

v5.2
- **Rock Version:** v5.2

**Comment by arranf** [comment]
@azturner Is this fixed in 5.3/5.4?

**Comment by azturner** [comment]
@BEGamache , I tried to reproduce this and haven't been able to. Whenever I select to delete a giving profile from the "Manage Giving Profiles" list, Rock successfully deletes the profile in Transnational. Does this happen whenever you try to delete a profile? i.e. did you try to reproduce as well with your own profile(s)? I am using a test NMI/Transnational account and wonder if there could be something different between test and production gateway setups.  But to answer @arranf 's question, there is not a fix for this in v5.3 or v5.4.

**Comment by arranf** [comment]
@BEGamache Is this fixed? Did you ever encounter this issue again?

**Comment by edmistj** [comment]
Closing issue from lack of response.
