### ISSUE TITLE
Event Registration Phone Type Attribute filter not working properly.

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1765]
### Prerequisites
- [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
- [x] Did you include your Rock version number and client culture setting?
- [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

Created an Event Registration with a Registration Attribute and the type is Phone Number. This causes an issue when trying to view the list of registrants in the event registration instance. The issue is with the filter. Even though no filter is set, Rock still tries to apply a filter on the phone field which keeps all registrants from being visible. If you unselect the Show in Grid option for the attribute all registrants will appear since it can't filter on the phone field. We have a 3-5 templates with this type of attribute and the same issues occurs so it looks like it may be reproducible but I haven't tested it on demo site yet.
### Steps to Reproduce
1. Registration Attribute > Phone Number Type
2. Show in Grid selected
3. sign up a registration and view the registrant tab.

**Expected behavior:** [What you expected to happen]
If no entry set in the phone attribute filter, do not filter on phone attribute.

**Actual behavior:** [What actually happened]
It is filtering where the attribute is blank--which can't happen in our forms because the attribute is set as required.
### Versions
- **Rock Version:** v5.2
  ![screen shot 2016-09-14 at 11 24 16 am](https://cloud.githubusercontent.com/assets/5738650/18522036/0c592724-7a74-11e6-9315-ce9dce8c5a3d.png)
  ![screen shot 2016-09-14 at 11 24 26 am](https://cloud.githubusercontent.com/assets/5738650/18522042/10b636c2-7a74-11e6-92a1-8a61d2f16b7c.png)

**Comment by arranf** [comment]
@BEGamache Is this still an issue? Can you reproduce on the demo site for us?

**Comment by garrettjohnson** [comment]
Just tested on the prealpha; Rock no longer attempts to filter on a blank phone number.
