### ISSUE TITLE
Related Transactions section of Transaction Detail should only display transactions from the same person

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#1766]
### Description

On the Transaction Detail screen, the Related Transaction section displays all transactions in the system that share the same Transaction Code value. According to David Turner this is meant to only show matching Transaction Codes for transactions from the same person.
### Steps to Reproduce
1. Create three transactions with the same transaction code. Two of them assign to User A and one to User B.

**Expected behavior:** 
View one of User A's transactions and only his other transaction should display. View User B's transaction and no related transactions should display.

**Actual behavior:** 
Two related transactions display on all three transaction details.
### Versions
- **Rock Version:** Rock McKinley 5.3
- **Client Culture Setting** en-US
  [RockDiagnostics-WC516147.txt](https://github.com/SparkDevNetwork/Rock/files/474823/RockDiagnostics-WC516147.txt)

**Comment by nairdo** [comment]
@chrismcgrath @arranf, If three transactions have the same "Transaction Code", how are they **_not_** related?

**Comment by chrismcgrath** [comment]
@nairdo As far as I understand, Check Number is meant to be stored in Transaction Code, and Check Numbers are quite common.
