### ISSUE TITLE
Google Maps mobile version does not find address

### ISSUE THREAD

**Issue by hbcfw** [SparkDevNetwork/Rock#1767]
### Prerequisites
- [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
- [x] Did you include your Rock version number and client culture setting? - Running version 5.2 but also does the same thing on the Rock demo site.
- [x] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue? [RockDiagnostics-WIN-JKICE3MLQSJ.txt](https://github.com/SparkDevNetwork/Rock/files/474980/RockDiagnostics-WIN-JKICE3MLQSJ.txt)
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

When clicking on the location pin, google maps will find location on a desktop computer, however it will not find the location on a mobile device.
The disruption looks to be caused by the person's profile name being added to the end of the location address. Once the name is deleted on the mobile version it is able to find the location. Can we the name be removed from the address search?
### Steps to Reproduce
1. Open person profile on mobile device.
2. Click the location pin by the family address

**Expected behavior:** Open the correct map

**Actual behavior:** Google Maps says "No address found" because the name is appended to the address.
### Versions
- **Rock Version:** 5.2
- **Client Culture Setting**
  [RockDiagnostics-WIN-JKICE3MLQSJ.txt](https://github.com/SparkDevNetwork/Rock/files/474980/RockDiagnostics-WIN-JKICE3MLQSJ.txt)

**Comment by garrettjohnson** [comment]
Fixed in PR #1763, looks like it's set to be in the V6 release.
