### ISSUE TITLE
Communication Approval is Broken for New Communications

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#1768]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The CheckApprovalRequired(...) check in the btnSubmit_Click event of the CommunicationEntry.ascx.cs block returns false because the communication.GetRecipientCount( rockContext ) call always returns 0 on new messages.

https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Communication/CommunicationEntry.ascx.cs#L570

### Steps to Reproduce

1. Create a new message with a greater number of recipients than the configured block's settings.
2. Press the Submit Communications button.

However, if you first save as draft and then go press Submit Communication, the communication.GetRecipientCount( rockContext ) call will correctly get the number of recipients and the email will be queued for approval.

**Expected behavior:**
Expect email not to send.

**Actual behavior:** 
Message is sent.

### Versions

* **Rock Version:** v6 alpha
* **Client Culture Setting** unknown

**Comment by treyhendon** [comment]
Seeing same behavior in 5.2. Thanks @nairdo

**Comment by azturner** [comment]
This seems to only occur when creating a new communication and then adding recipients manually. If you create a new communication from a grid, the count is calculated correctly and approval works.
