### ISSUE TITLE
DropDown controls not triggering validation

### ISSUE THREAD

**Issue by jreciomoreno** [SparkDevNetwork/Rock#1770]
### Prerequisites
- [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
- [x] Did you include your Rock version number and client culture setting?
- [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

DropDown controls such as  BirthdayPicker and RockDropDownList are not triggering validation when marked as required for Registration Person Fields.

![image](https://cloud.githubusercontent.com/assets/18447151/18596783/8c84f188-7c10-11e6-80da-fe62bd79ac67.png)

**Expected behavior:** No selection from dropdown must trigger the required validator to display an error message and prevent the user from submitting the form with empty values on required fields.

**Actual behavior:** No selection on dropdown controls marked as required are not triggering the required validator; this is allowing registration forms to come with empty required fields.  
### Versions
- **Rock Version:** Rock McKinley 5.3  
- **Client Culture Setting** en-US

**Comment by cabal95** [comment]
Birthday picker is probably related to #1705.

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in commit 60dea4fa. Thanks Daniel!
