### ISSUE TITLE
Business: Null Reference during Registration

### ISSUE THREAD

**Issue by cbump** [SparkDevNetwork/Rock#1772]
### Prerequisites
- [N/A ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
- [Y ] Did you include your Rock version number and client culture setting?
- [N ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
- [ Y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

We migrated a few user logins that are tied to business records.  When people attempt to register for an event using one of these logins, they get a Null Reference:

System.NullReferenceException   Object reference not set to an instance of an object.
   at RockWeb.Blocks.Event.RegistrationEntry.SaveRegistration(RockContext rockContext, Boolean hasPayment) in c:\Rock\Blocks\Event\RegistrationEntry.ascx.cs:line 1724
   at RockWeb.Blocks.Event.RegistrationEntry.SaveChanges() in c:\Rock\Blocks\Event\RegistrationEntry.ascx.cs:line 1457
### Steps to Reproduce
1. Create a UserLogin on a business (Probably need to do it in the database)
2. Login as that user and register for an event.
3. On the final page, the registration will throw a null reference.

**Expected behavior:** 
The registration should complete successfully creating a web prospect for the person registering.

**Actual behavior:**
Null Reference
### Versions
- **Rock Version:** Rock 1.5.0
- **Client Culture Setting** en-US

**Comment by edmistj** [comment]
Probably should have the registration block check to ensure that the record is a person and not allow registration if not.
