### ISSUE TITLE
Defined Type extra blank row when listing defined values

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#1774]
### Prerequisites
- [X] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  -- Yes, w/o any edits
- [X] Did you include your Rock version number and client culture setting?
  -- 5.4, en-US
- [X] Have you attached your [environment and diagnostics information
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
  -- Yes, not that I found.  I even browsed through closed reports
### Description

![image](https://cloud.githubusercontent.com/assets/19762670/18653230/2151e6e2-7e9e-11e6-8bc7-e95ccfbd09bb.png)
![image](https://cloud.githubusercontent.com/assets/19762670/18653294/8c817612-7e9e-11e6-9fdc-439c1b1a3bdd.png)
Defined Types display an additional blank row.
### Steps to Reproduce
1. Edit any Defined Type field. (ex. Source of Visit on demo site.)

**Expected behavior:** [What you expected to happen]
I expected only one blank row for the default blank option at the top of the list.

**Actual behavior:** [What actually happened]
There are two blank rows. in the list of defined values. One at the top, and one at the bottom of any Defined Type's list of Values when you're editing the value of that Defined Type's field on a person record, or in a Workflow.
### Versions
- **Rock Version:** [5.4]  Also, exists in 5.2
- **Client Culture Setting** [en-US]  

Attached is the rocksolidchurchdemo instance diagnostics since the issue exists there too.
[RockDiagnostics-EZRS8J.txt](https://github.com/SparkDevNetwork/Rock/files/481379/RockDiagnostics-EZRS8J.txt)

**Comment by azturner** [comment]
Fixed in 1.6 here: https://github.com/SparkDevNetwork/Rock/commit/efdff69b3f0940e522600fe7e7bcdd2c27548a82
