### ISSUE TITLE
[EN] Rock Cleanup job for orphaned Attribute Values

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1776]
As our database is growing, I've been monitoring the largest tables and looking for ways to clean them up (see #1670).  Our 3rd largest table is `AttributeValue` and I don't see anything set to clean that automatically.  

My thought is to create a job to JOIN any Attribute with the Entity that _should_ exist according to  Attribute.EntityTypeId, Attribute.EntityTypeQualifierColumn and Attribute.EntityTypeQualifierValue.  If that Entity doesn't exist, then any AttributeValues for that Attribute can be deleted.

One use case for this is a Group that's been deleted, but has been given custom/inherited attributes and those attributes are never deleted.  The GroupMembers are deleted, but the attribute values for the members aren't.  I'm sure there are other situations with orphaned AttributeValues too.

**Comment by cabal95** [comment]
Can anybody think of a reason this wouldn't work?  It seems a pretty straight forward process. I don't think we even need to check the EntityTypeQualifierColumn and EntityTypeQualifierValue.  If the EntityType of the Attribute does not have an entity table row whose Id matched EntityId it should be safe to delete.  The Qualifiers just limit which _attributes_ apply to an entity, not so much the attribute values (though indirectly they do).

So, if Attribute.EntityType + AttributeValue.EntityId does not match to a record, it should be safe to delete the AttributeValue - correct?

**Comment by azturner** [comment]
@cabal95 Yes, as long you are only looking at attribute values that are associated to an attribute that has an entity type that is an actual entity (IsEntity=1) that is a safe assumption.

**Comment by dcs619** [comment]
I thought there was a case where the EntityTypeQualifierValue was needed  -- something to do with Group Member attribute values that were inherited from a parent grouptype?  

There are a lot of IsSystem (core) attributes that reference non-entities, maybe anything marked `IsSystem` should be excluded as well?

```
select 
    a.Name Attribute, a.IsSystem SystemAttribute, av.value Value, av.IsSystem SystemAttributeValue, e.name EntityType
from attribute a
inner join entitytype e
    on a.entitytypeid = e.id
inner join attributevalue av
    on av.attributeid = a.id
where 
    e.isentity = 0
```

**Comment by MikeDPeterson** [comment]
RockCleanup has a new method that was added a couple of months ago that might take care of this.  https://github.com/SparkDevNetwork/Rock/blob/52465968229e027f42e3048a2ff2c7606261de37/Rock/Jobs/RockCleanup.cs#L1

**Comment by dcs619** [comment]
@MikeDPeterson++ for that helper
