### ISSUE TITLE
Missing Person Fields in Events

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1781]
### Prerequisites
- [x ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
- [x ] Did you include your Rock version number and client culture setting?
- [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
- [x ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

The drop down of Person Fields in an Event Registration form is only a subset of the available person fields/properties.
### Steps to Reproduce
1. Create a Event Registration Template
2. Create a form in the template with a 'Person Field' Form Field

**Expected behavior:** All available Person Fields (person properties) would be exposed, just like the Person Property Update workflow action does.

**Actual behavior:** You see a limited subset of person fields/properties
### Versions
- **Rock Version:** 5.3, 6.0alpha 

![event registration](https://cloud.githubusercontent.com/assets/3903408/18800337/10424886-81a2-11e6-9cd3-8a4841a378eb.png)

**Comment by nairdo** [comment]
This is not a bug.  This is by design.

**Comment by JimMichael** [comment]
Well that's a bummer. Can you shed some light on the design decision? If the idea is that there are some things you don't want changeable from the public site, realize that often the desire to have a specific person field exposed in an event is NOT for the user changing it, but to have extra info about the person visible to staff on the registrant grid... so in my humble opinion it should be up to us if we want to expose those or not.

**Comment by edmistj** [comment]
The design decision was centered more around the fact that each person property requires custom code to implement. For instance Work Phone is stored in a separate table and has unique code for formatting than something like Gender which is on the person table but stored as an enum.

Based on that we selected the most commonly used. We could add more, but adding 'All' would be a lot of resource time.  If you want to list out the most needed we can see about adding them into v7.

**Comment by JimMichael** [comment]
Thanks Jon, that helps me understand. The two missing things that give us grief are 1. Anniversary Date - we do a lot of marriage events and would like to solicit the Anniversary Date from the user to update their records directly, but can't, and 2. Age, which I now realize is a slightly different issue where we really want the calculation from birthdate intto age to be exposed as a column in the registrants grid. But making that a Person Field probably doesn't make sense since Age is not really stored anywhere, it's just calculated. Maybe for this there just needs to be an option in the form fields "source" drop down for Age... or age could just *pretend* to be a person field for the sake of display ;-) Ultimately for #2 our admins really need to know someone's age when looking at the grid vs. their birthdate. Oooh... maybe a lava field option?

**Comment by watermarkgeek** [comment]
We would add that the Membership status is a huge need for us.  We have people register for events but we make internal decisions based on their membership status.  (Membership DOES have it's privileges).  This would be something we would put as an internal field on registration reports all the time.

**Comment by edmistj** [comment]
Noted

**Comment by winmastr** [comment]
I posted in Slack this morning, that todays traveling requirements include having a Middle Name as a part of Airline tickets (matching Drivers License and Passport information). The event registration forms we use for participating in our 58 trips a year include the Fname, Mname and Lname fields up to this point. I hate to add an additional attribute to accommodate a field that is already a part of the person table (not requiring additional coding). Is there anyway that can be added to the default list of person fields?

**Comment by ethan-sparkdevnetwork** [comment]
Added MiddleName and AnniversaryDate. ConnectionStatus was already added by DH but not showing on the internal registration pages, so I fixed that as well.

**Comment by cabal95** [comment]
Oops. :)

**Comment by ethan-sparkdevnetwork** [comment]
Age in years is already displayed in the grid next to birthday.
I added sorting to the person fields so they are in alpha asc order, previously they were in enum order.
