### ISSUE TITLE
Can't Sort by Group Participation Column in reports

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1784]
### Prerequisites
- [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
- [x] Did you include your Rock version number and client culture setting?
- [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

Unable to sort by report column Group Participation. I think this also happened on a couple other field types but I don't recall which ones.
### Steps to Reproduce
1. In a report add the field type Group Participation
2. Once saved, in the report of people select the group participation column to sort.

**Expected behavior:** 
Sort based on the name of the group

**Actual behavior:** 
Doesn't sort but presents and error message:

WARNING: There was a problem with one or more of the report's data components...

DbSortClause expressions must have a type that is order comparable. Parameter name: key
### Versions
- **Rock Version:** v5.3

**Comment by BEGamache** [comment]
Tested it on demo site and same result, so it is also present in v5.4

**Comment by garrettjohnson** [comment]
Would it be possible to reopen this to sort by the first result in the enumerated list of groups? I don't know how Rock is querying to build the group participation column, but in TSQL it's possible to sort by FIRST_VALUE; which would probably cover most use cases.
