### ISSUE TITLE
Giving Block Unlisted Phone Number Issue

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#1803]
### Prerequisites
- [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  Not on demo site because of payment gateways, don't have time yet to reproduce on a clean install
- [x] Did you include your Rock version number and client culture setting?
- [x] Have you attached your [environment and diagnostics information]
  parkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

When submitting a contribution, if the "Personal Information" section includes the Phone Number box, and the person is signed in and has an Unlisted phone number, the contribution won't submit, and throws an exception.
### Steps to Reproduce
1. Stock install
2.  (We're using Pay Flow Pro for the CC Gateway and PDS ACH for our ACH Gateway)
3. Unlist phone number
4. Sign in to give online
5. Note that Phone number box fills with "Unlisted" (minus quotes)
6. Click next
7. The confirmation page before submitting says "Phone Number: +1" and no actual areacode+7 afterwards
8. Click Submit, then exceptions start happening, and the payment won't go through.

**Expected behavior:** [What you expected to happen]
I hoped that Unlisted if an unlisted number was being used, then phone numbers as a whole would be dropped from consideration when the first "submit" button is hit.

**Actual behavior:** [What actually happened]
It seems Unlisted skips the phone number field validation because it wasn't modified after the page loaded.  But the value of the field seems to be blank because "Unlisted" doesn't pass phone number validation.
### Versions
- **Rock Version:** 5.2
- **Client Culture Setting** en-US
  [Included from your Rock installation]
  [RockDiagnostics-ROCKPRODUCTION.txt](https://github.com/SparkDevNetwork/Rock/files/516314/RockDiagnostics-ROCKPRODUCTION.txt)

**Comment by arranf** [comment]
@NuclearTacos Is this still an issue?

**Comment by NuclearTacos** [comment]
@arranf I disabled Phone Numbers on the giving form so I don't know if it's still an issue.  I'm not comfortable enough with any of my financial gateways to potentially generate bogus transactions.  If we can get gateway signed in, I'll reproduce the issue wherever you want :grin:

**Comment by NuclearTacos** [comment]
From Slack user `@eholeman`
On my person record in Rock, for testing purposes, I had my home phone marked as unlisted.  I was doing a test contribution today and found that Unlisted comes into the Personal Information section.  When I clicked Finish, the transaction never completed.  It just spins.  The exception log shows this "Entity Validation Error: 

> PhoneNumber_CDEA37FBD6F5E4572653A968BAEDEEED6F573B5824FE855AFF9AC683C5A27ADD (Number): The Number field is required."  So, I realized that unlisted in the phone field was the problem.  Should an unlisted number populate the Personal Information section like this?  Clearly a user would never know why their contribution wasn't going through.

Seems to be the same problem.  I forwarded him my workaround to this issue.
