### ISSUE TITLE
Cannot set default of location field type on workflow attribute

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1804]
### Prerequisites
- [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
- [x] Did you include your Rock version number and client culture setting?
- [x] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

When adding a field type of location, the picker created to set the default location shows the incorrect icon (Person instead of location) and will not allow a default to be set.

<img width="1177" alt="screen shot 2016-10-09 at 11 40 14 pm" src="https://cloud.githubusercontent.com/assets/374209/19228449/46aa05fa-8e7a-11e6-9211-892dbec8d65b.png">
### Steps to Reproduce
1. Create a workflow
2. Add an attribute with a type of "Location"

**Expected behavior:** Clickable dropdown to set default location.

**Actual behavior:** The div IDs included in the onclick call are incorrect, so clicking doesn't return anything.
### Versions
- **Rock Version:** 5.4
- **Client Culture Setting** en-US

**Comment by nairdo** [comment]
Able to reproduce on 5.4 but unable to repro in 6.X.
