### ISSUE TITLE
Empty datetime attribute is included in "Less Than" dataview filters

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#1808]
### Prerequisites ###

(mostly unnecessary due to this being an alpha bug)

### Description ###

Empty datetime fields always qualify for inclusion in a dataview where a "Less Than" or "Less Than or Equal To" filter is tested against it- presumably an empty field resolves to 0 or null, which are considered less than the timestamp value. Possibly this is intended and we just need to also include an "is not blank" filter, but this doesn't seem obvious to an end user.

### Steps to Reproduce ###

1. Verify that a person datetime attribute is blank
1. Create a dataview that requests all people where that attribute is less than any arbitrary date
1. Check the dataview list, the person with the blank value in the datetime attribute is included

**Expected behavior:** I do not expect a "date is less than 1/1/2016" filter to include someone with NO date in the attribute

**Actual behavior:** The person with no date in the attribute is included in the dataview

### Versions ###

* **Rock Version:** V6 alpha 2
* **Client Culture Setting** en-us

**Comment by garrettjohnson** [comment]
This bug appears to effect the "In groups" filter as well. Leaves a "added to group in Date Range:" even when blank.

![screenshot 2016-11-22 19 45 17](https://cloud.githubusercontent.com/assets/374209/20550596/36b48cb2-b0ec-11e6-8fe7-79ea69087f1e.png)

**Comment by arranf** [comment]
Still confirmed as of 2018-06-13

**Comment by mikejed** [comment]
Here is a better example of this behavior (still present in v16.0) - this is a data view on the demo server selecting people with a baptism date Attribute Value before 2020-01-01. You can see that people with no baptism date value are included, such as anonymous giver and Aisha Admin.
![7E125FD3-DFA0-4F72-94E3-C4F939455130](https://github.com/SparkDevNetwork/Rock/assets/6932047/a6fe6638-4723-4617-acd2-333ed10dcfc6)

As noted in the original report, you can add an “is not blank” filter to the data view to get the list you expect, but for data views it’s not clear to me that blank values should ever be included in “Date is before” filters, so ideally this second filter shouldn’t be required.
![45576DCB-B466-4C44-B4F6-6898219B508E](https://github.com/SparkDevNetwork/Rock/assets/6932047/a325406e-acf7-4bbe-a30c-4de247601144)

However, if this is indeed “working as intended” this report can be closed. This is not insurmountable by any means, it’s just less intuitive for administrators creating reports as it is.

**Comment by jonedmiston** [comment]
This is being actively worked on.
