### ISSUE TITLE
New Address on existing family- address input is not marked as required

### ISSUE THREAD

**Issue by ccofnow** [SparkDevNetwork/Rock#1809]
### Prerequisites
- [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? No- this is a change in behavior between v5.4 and v6 Alpha 2
### Description

Creating a new address for a person, "address" is no longer marked as required (the red dot).

The first time I found this, attempting to save returned an error in red text saying only "is required", with no identification or visual clue as to which field is required. I am no longer able to get that error, and the field highlights in red, which is fine, but the field should be marked as required
### Steps to Reproduce
1. Click "Edit Family" on an existing profile
2. Click (+) button under addresses
3. Provide city, state and zip but no street number or name
4. Click the green checkmark
5. Action fails even though the field is not marked as required

**Expected behavior:** Field should be marked as required. If the error message I saw the first time wasn't a fluke, it should say "Address is required" rather than just "is required"

**Actual behavior:** Action fails
### Versions
- **Rock Version:** v6 Alpha 2
- **Client Culture Setting** en-us

**Comment by nairdo** [comment]
This issue was introduced via https://github.com/SparkDevNetwork/Rock/commit/72ac91c8163a4c4959f9409828affacae46c113e but I'm investigating a possible solution since there are no labels for which to mark the field as 'required'.
