### ISSUE TITLE
HTML editor (non Code Editor mode) issues

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#1810]
### Description

I added an HTML block to my v6 alpha 2 installation's front page on the internal site and set the block properties to disable editor, but it still uses the editor.

And it seems to break on tables separated with lava-

&lt;table&gt;&lt;thead&gt;&lt;tr&gt;&lt;th&gt;header&lt;/th&gt;&lt;/tr&gt;&lt;/thead&gt;&lt;tbody&gt;
{% for x in y %}
  &lt;tr&gt;{{ x.lava }}&lt;/tr&gt;
{% endfor %}
&lt;/tbody&gt;&lt;/table&gt;

saves as 

{% for x in y %}
{% endfor %}
&lt;table&gt;&lt;thead&gt;&lt;tr&gt;&lt;th&gt;header&lt;/th&gt;&lt;/tr&gt;&lt;/thead&gt;&lt;tbody&gt;
  &lt;tr&gt;{{ x.lava }}&lt;/tr&gt;
&lt;/tbody&gt;&lt;/table&gt;
### Versions
- **Rock Version:** v6 Alpha 2  
- **Client Culture Setting** en-us

**Comment by nairdo** [comment]
When using the Code Editor mode this does not occur.  It only happens if you're not using the Code Editor mode of the HTML editor.  In that case the example input content is saved and presented back as:
```
{% for x in y %}
{{ x.lava }}
{% endfor %}
<table><thead><tr><th>header</th></tr></thead><tbody><tr></tr></tbody></table>
```

**Comment by mikejed** [comment]
Tested this issue again to verify it's still valid.

I concur with Nick's findings on all fronts, using v.7.3 and v8 prealpha. Here's a reproducible sample of HTML that demonstrates the issue:
1. Create an `HTML Content` block with `Rock Entity` enabled, and `Use Code Editor` set to `No`
2. Switch to code editor mode and paste in the following data:
```
<table>
    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        {% person where:'LastName == "Decker"' %}
            {% for p in personItems %}
                <tr><td>{{ p.FullName }}</td></tr>
            {% endfor %}
        {% endperson %}
    </tbody>
</table>
```

3. Save. Note the content shows correctly
4. Get back into the `Edit HTML` dialogue. Note scrambled text. Switch back to Code Editor mode and note contents are now:

```

        {% person where:'LastName == "Decker"' %}
            {% for p in personItems %}
                
            {% endfor %}
        {% endperson %}
    <table>
    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>
    <tbody><tr><td>{{ p.FullName }}</td></tr></tbody>
</table>
```

I would add to this issue a recommendation that the help text for `Use Code Editor?` should be reconsidered. The present text
>Use the code editor instead of the WYSIWYG editor
seems to imply that setting it to "Yes" would disable the WYSIWYG interface. Perhaps it should read,
>Open the Edit HTML dialogue in code editor mode by default instead of in WYSIWYG mode
