### ISSUE TITLE
[Discussion] Unit Testing

### ISSUE THREAD

**Issue by johnthepink** [SparkDevNetwork/Rock#1811]
We want to start the process of adding unit tests to Rock! This will definitely need to be a community effort, as there are lots of things we need to get covered. Our goal for this week is to:
1. Document the types of things that need to be tested
2. Research and select a testing framework
3. Provide some examples
4. Get feedback from everyone

At the end of the week, @dcs619 and I hope to have some documentation to easily onboard people willing to help out.
## Things To Test

Here are things we initially want to cover with unit testing:
1. Entities
2. API controllers
3. Stored procedures
4. UI
5. Workflow actions

Surely this will be an evolving list. What are we missing?
## Testing Frameworks

I've done some reading on NUnit, xUnit, and MSTest. I'm starting to develop my own opinion, but I wanted to hear feedback from people with experience unit testing in .NET.
1. What do you like?
2. What is appropriate for this project?
3. Why?

**Comment by arranf** [comment]
I think it'd also be good as part of this effort to identify repeated logic in places such as Workflow Actions, Blocks, and other places that could be pulled in reusable static methods, that could then be tested

**Comment by johnthepink** [comment]
@arranf that sounds like a good ongoing plan. Our hope was that we could get some initial work merged, and then slowly chip away at all the things. That way we won't have a long-running branch.

**Comment by dcs619** [comment]
@mikepetersonccv Any thoughts?  We're looking at your NUnit models as a potential starting point.  Model testing seems easy enough to implement, but I'm curious about workflow actions.

**Comment by arranf** [comment]
I think @mrupsidedown has done some testing of check-in, and consequently
workflow actions. I don't know if he's got any strategies he can share.

**Comment by mikepetersonccv** [comment]
@dcs619 I'm not sure NUnit models you are referring to.  Anyways, I don't have an opinion quite yet

**Comment by dcs619** [comment]
@mikepetersonccv I was looking at the tests started [here](https://github.com/SparkDevNetwork/Rock/tree/develop/Rock.Tests), but just realized that was @nairdo's work...you had last modified it to update the license 😸

**Comment by johnthepink** [comment]
## Mocking

One interesting problem we spent some time researching is mocking. Mocking will be necessary to maintain true unit tests by not making any requests to the database. Tests that do hit the database may become necessary later, but those will be integration tests.

However, mocking the static extension methods in the Rock code base is going to be a little bit trickier than I hoped. None of the free mocking frameworks, like Moq, support mocking extension methods. JustMock and Typemock supposedly do, but cost money to get there.

The creator of Xunit wrote a good article about [how to test extension methods](http://blogs.clariusconsulting.net/kzu/how-to-mock-extension-methods/), but I'm not sure how applicable it is to our situation.

I started writing tests for the background check request workflow action, and it contains a good example. [Line 59](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Workflow/Action/BackgroundCheck/BackgroundCheckRequest.cs#L59) attempts to get the `providerGuid`, which under certain circustances eventually calls `LoadAttributes` on the `actionType` [here](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Workflow/ActionComponent.cs#L169). It would be great to be able to mock that method, and just test that the method gets called. But, it doesn't exist on ActionType, it is an extenstion method.

Maybe it would be possible to mock the [helper method](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Utility/ExtensionMethods/AttributesExtensions.cs#L45) that actually does the work here, but I'm not sure how to go about doing that.

Any thoughts?

**Comment by dcs619** [comment]
@azturner Do you think we could leverage partial classes to provide the mock versions of the static methods (`LoadAttributes`, `SetValue`, etc)?

The example posted above implements mock versions using an interface:

    public static class UtilityExtensions
    {
        // mocked function call
        internal static Func<IPerson, ISecurity> SecurityFactory = person => new Security(person);
    
        // original function call
        public static ISecurity Security(this IPerson person)
        {
            return SecurityFactory(person);        
        }
    }

**Comment by MrUpsideDown** [comment]
@johnthepink As @arranf mentioned, I have been trying to implement some unit tests for check-in, and have run into the same problem as you have encountered with LoadAttributes.

So far the best solution I have thought of so far goes something like this:
1. Create a new IAttributesProvider interface which represents a source for loading Attributes, and defines a "LoadAttributes" method.
2. Extend the IHasAttributes interface to add an "AttributesProvider" property, which returns an IAttributesProvider object.

The default implementation of the AttributesProvider would simply mirror existing behavior by calling the Rock.Attribute.Helper.LoadAttributes static method. However, for testing purposes, a mock AttributesProvider that returns a set of known values could be injected.

I think the additional benefit of this approach is that it would make the LoadAttributes function more extensible. The current implementation contains specific processing for a variety of types (Group, GroupType, Registration) which would be better implemented in a separate AttributesProvider that specifically handles those types. This also means that plugins could define different attribute loading strategies for their own entities without having to modify any core code.

**Comment by johnthepink** [comment]
@MrUpsideDown awesome! Thanks for the info. Would you be up for PRing an example after we get our PR going?

**Comment by MrUpsideDown** [comment]
@johnthepink Yes, I'd be happy to do that if the consensus is that this would be a workable solution.

**Comment by arranf** [comment]
Closing this as there isn't an actionable item here.
