### ISSUE TITLE
Login issues.

### ISSUE THREAD

**Issue by imajprop** [SparkDevNetwork/Rock#1812]
I have created a login at Rockrms.com and have no trouble logging in there, but I cannot login on our rock site with the same credentials.  Any suggestions?

**Comment by arranf** [comment]
Hey @imajprop 
You should have a completely different set of credentials for your Rock installation than rockrms.com.

Rock isn't sold as a service by rockrms.com, rather you either have your own installation maintained by your organisation or provided by a partner. You should contact whoever set your Rock installation up for support!

**Comment by imajprop** [comment]
Arran,
 
Your statement isn’t quite accurate. Although Rock is not “sold” by Rockrms, it is definitely distributed and downloaded by Rockrms and the creditials ARE the same. 
 
 
 
James Trow
 
church 863.859.6444 | mobile 813.731.3770
email james@fuel.church 
 
7355 US Hwy 98 North | Lakeland, FL 33809
www.fuel.church
 
cid:DFCD887E-512B-4568-9169-1266FEEEF649

**Comment by arranf** [comment]
@imajprop Hey James,
Your rockrms.com credentials will only work for downloading plugins to your own Rock instance. To log in to your own Rock instance you'll need to us the credentials set up for you by whoever installed it.

**Comment by imajprop** [comment]
How can I delete this registration?
 
 
James Trow
 
church 863.859.6444 | mobile 813.731.3770
email james@fuel.church 
 
7355 US Hwy 98 North | Lakeland, FL 33809
www.fuel.church
 
cid:DFCD887E-512B-4568-9169-1266FEEEF649
