### ISSUE TITLE
[EN] Inconsistent constructor visibility for AttributeCache and AttributeValueCache

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1819]
The constructors for [AttributeValueCache](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Web/Cache/AttributeValueCache.cs#L59) are all marked public.  The constructors for [AttributeCache](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Web/Cache/AttributeCache.cs#L56) are all marked private.

I would expect the visibility for those types to match. That 
1) simplifies creating a Model that has those properties added, and
2) allows for unit testing the AttributeCache and AttributeValueCache functionality.  

If there's a reason visibility is limited on AttributeCache I'd love to learn that too.

**Comment by azturner** [comment]
The AttributeCache class is a designed to only ever have one instance for each attribute. It (just like most of the other ...Cache classes) should never be instantiated by external code. The Read() method should always be used to get an instance of the class. AttributeValueCache, on the other hand, is more of a helper class with public constructors. Attribute Values are not actually cached.

**Comment by dcs619** [comment]
@azturner 👍  This was to ensure models that depend on AttributeCache are getting an instance, but maybe there's a way to mock it for testing.  Since the tests run in a headless space, there's never an actual ...Cache to call Read on.
