### ISSUE TITLE
Attendance Reporting - Feature Request [EN]

### ISSUE THREAD

**Issue by ToxicFume** [SparkDevNetwork/Rock#1820]
My Small Group Pastor is requesting a way to be able to pull up reports about the attendance percentages for all the Small Groups in each of our locations. It would be nice if we could filter it out via campus, date range, and/or age group.

Thanks,
Gordon-

**Comment by nairdo** [comment]
Hello amazing community member! We've recently moved 'feature requests' to our own "Ideas" system on our Community site at: http://community.rockrms.com/ideas

If you'd like to re-propose your idea and put it up to the vote, please re-submit your idea there. Thanks!
