### ISSUE TITLE
Attendance Proc Syntax Error

### ISSUE THREAD

**Issue by tom-powers** [SparkDevNetwork/Rock#1832]
### Prerequisites
- [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
- [x] Did you include your Rock version number and client culture setting?
- [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

spCheckin_AttendanceAnalyticsQuery_AttendeeLastAttendance
parameter @EndDate has invalid default value of NULL@CampusIds

[Description of the bug or feature. Include screenshots if applicable.]
### Steps to Reproduce

it is obviously just a typo when sproc was created

**Expected behavior:** [What you expected to happen]

default parameter value should be NULL

**Actual behavior:** [What actually happened]
### Versions
- **Rock Version:** Rock McKinley 5.0
- **Client Culture Setting** en-US
  [Included from your Rock installation](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information)

**Comment by nairdo** [comment]
@tom-powers I cannot reproduce this using the develop branch and I _think_ [this bug was fixed here](https://github.com/SparkDevNetwork/Rock/commit/3398e1bdd7b3aed91accf7f2958f8663605b3048#diff-b846995371d131121e75615f79eac6f2R38).  

Can you confirm?

**Comment by arranf** [comment]
@tom-powers Can you confirm this was fixed?

**Comment by mikejed** [comment]
Line 29 of https://github.com/SparkDevNetwork/Rock/commit/3398e1bdd7b3aed91accf7f2958f8663605b3048#diff-2f3183c55a2ca8592550916c6f4144f8R29 , as Nick identified, is almost certainly the fix. @tom-powers please let us know if this is still an issue and we'll reopen. Otherwise I think this can safely be closed.
