### ISSUE TITLE
Attendance Analytics first/second visit bug

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1835]
### Prerequisites
- [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
- [X] Did you include your Rock version number and client culture setting?
- [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

There appears to be a bug in Attendance Analytics where first/second visit dates are not displayed for any group who's parent area is a child of another parent area. Said another way, check-in groups within sub-areas do not display first or second visit dates. Groups that are a child of a "top level" check-in area display these dates as expected.
### Steps to Reproduce
1. Create a check-in configuration with a top level area
2. Create a sub area within the above area
3. Add groups to the sub area
4. Run some check-ins for the group(s)
5. In Attendance Analytics, run a query for a date range that returns check-ins for the group(s)
6. Notice there are no first visit or second visit dates returned.
7. If you have other groups that are NOT in a sub area, they DO return first/second visit dates

**Expected behavior:** 
Groups within sub areas show valid first/second visit dates in Attendance Analytics

**Actual behavior:**
Attendance Analytics appears to break for groups within sub areas and while valid check-in dates ARE returned, the first/second visit dates are not. I have no idea if these dates are calculated on-the fly every time and are just missing from analytics, or if they are permanently "gone."
### Versions
- **Rock Version:** 5.3, 5.4, 6.0alpha2
  ![nested check-in config1](https://cloud.githubusercontent.com/assets/3903408/19772771/dcf17de4-9c2c-11e6-84e4-3524d6e0cde6.png)
  ![attendance analytics1](https://cloud.githubusercontent.com/assets/3903408/19773228/68396ae6-9c2e-11e6-9531-bd9f76062fb8.png)

**Comment by BEGamache** [comment]
We are experiencing the same bug as well.

**Comment by nairdo** [comment]
@JimMichael @BEGamache are you guys saying the other check-in groups?  I ask because this seems very related to #1833 which was preventing any first/second visit dates from being calculated by the analytics job.

**Comment by JimMichael** [comment]
Correct... check-in groups that have a parent area off the "root" show first/second visit dates just fine, but any group that is a child of an area that is in turn a child of another area (aka "sub areas", per my screen grabs) do not show these dates. Note that this has nothing to do with #1833 as that is dealing with the first/second visit *person attributes*. This issue is referring to the first/second visit dates related to attendance, which are not attributes but are part of *attendance analytics*.

**Comment by JimMichael** [comment]
Woohoo! This is great! However, it was just brought to my attention that a similar issue exists on both Family Attendance badges on Person Details. What we're seeing is that kids who have checked-into a group that is in a sub-area (exactly like the groups in this original issue) do not show on the attendance badges, but kids that have checked into groups that are not in a sub-area have attendance in their badges. 

Is this a similar bug that needs to be fixed in a different place (if so I'll open a new case) or will this fix _also_ fix the attendance badges?

**Comment by nairdo** [comment]
It's probably a similar bug but definitely will require a fix to the badge code. I'll get started on it -- can you proceed and open a second issue? Thanks!

**Comment by JimMichael** [comment]
Unfortunately this doesn't seem to be fixed in v7alpha. I have a v7alpha server running a copy of our production database as of October. Running this query still results in no first/second visit dates being shown, but groups that aren't in sub-areas (like our Youth, not shown) show them just fine.
![image](https://user-images.githubusercontent.com/3903408/34007532-c10cce90-e0c7-11e7-8b0f-70dc307f9fac.png)
