### ISSUE TITLE
RockCheckBox UI Control can get out of sync

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#1840]
### Prerequisites ###

* [ ] Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
* [x] Did you include your Rock version number and client culture setting?
* [ ] Have you attached your [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) environment and diagnostics information ]() to this issue?
* [x] Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?
### Description

When using the SelectedIconCssClass  and UnSelectedIconCssClass properties the UI can get out of sync with the actual checkbox. This happens because the onclick handler simply toggles the state of the checkbox and then toggles the state of the CSS classes. There are a few ways this can happen but I have outlined a couple below.

### Steps to Reproduce ###

1. When using a RockCheckBox configured for IconCssClass support, tic the box so it has a check mark in it and then reload the page (as in CTRL-R) in Firefox. The UI will no longer show a tic but the underlying checkbox will still be checked. If you tic the UI box then it get a check but the underlying checkbox becomes unchecked.
1. When using a RockCheckBox configured for IconCssClass support, have a javascript function call the checkboxes click() handler to instruct the checkbox to toggle it's state (this is a somewhat common situation, for example when you want a table row to be clickable to toggle the state of a checkbox in that row). The underlying checkbox will now be out of sync with the UI.
1. When using a RockCheckBox configured for IconCssClass support, use javascript to disable the checkbox so the user cannot change it. Common example would be property checkboxes some of which being mutually exclusive. When 'A' is checked, 'C' must be disabled and vice-versa. The underlying checkbox will be disabled but the UI will still let you toggle the state. This is not directly an out-of-sync error but can cause UI problems. I would suggest the javascript perform a check on the checkbox to see if it is disabled as well as providing a 'disabled' class that would make the checkbox appear disabled.

**Expected behavior:** UI should remain in sync with the actual state reported at postback whenever possible. Not all possibilities can be avoided but I think it can be cleaned up to limit those possibilities, and we can hopefully use Intellisense to document those cases that can cause it to go out of sync and warn the developer.

**Actual behavior:** Visual UI to show wether the checkbox is ticked or not can become out of sync with the underlying checkbox control and what is reported to the C# code during postback.

### Comments ###

I think the onclick handler should be replaced with, pseudo-code, onclick="$('#realControlId').click()" so that the disabled state of the checkbox is preserved. Additionally if we use a jQuery onReady and asp.net endRequest event to set the current UI classes based on the actual state that will resolve the "on reload" issues. Finally, if we also install an onChange handler during onReady and endRequest events inside of the "set UI" code that checks the actual state of the checkbox and then sets the CSS classes as needed, that should resolve most cases where javascript interacts with the checkbox.

It will not fix outside javascript that does $('#control').prop('checked', true) as that does not fire an onChange event (frustratingly so), but that can be documented for developers who wish to interact with the checkbox. If they check the state of the checkbox first and then call the click() jQuery method IF it needs to be toggled then that will keep things in sync.

### Versions ###

* **Rock Version:** 1.5.0
* **Client Culture Setting** en-US

**Comment by nairdo** [comment]
@cabal95 I've not been able to reproduce this in my Rock v6 environment.  I tried adding a RockCheckBox to a block...
```
<Rock:RockCheckBox UnSelectedIconCssClass="fa fa-circle-o" Checked="true" SelectedIconCssClass="fa fa-check-circle" runat="server" Label="Test Checkbox" ID="testcheckbox" />
```

...and added some extra javascript to record/show whether or not the underlying checkbox is checked:

```
<script>
function VerifyCheckbox(){
    var now = new Date();
    if ( $("input[id$='testcheckbox']").is(':checked') ) {
        $("#message").append( "<p>it is checked " + now.toLocaleTimeString() + "</p>" );
    }
    else {
        $("#message").append( "<p>it is NOT checked " + now.toLocaleTimeString() + "</p>" );
    }
}

$(document).ready(function() {
    VerifyCheckbox();
});

var prm = Sys.WebForms.PageRequestManager.getInstance();

prm.add_endRequest(function() {
    VerifyCheckbox();
});
</script>
```

Do you have some sample somewhere that I can use to verify what you're seeing?

**Comment by cabal95** [comment]
@nairdo 

Sample page: https://rock.shepherdchurch.net/page/490

Okay, Case 1 seems to be Firefox specific (not 100% sure how to solve it). On PC + Mac Firefox, if I view the sample page, click the checkbox so it is checked and then hit CTRL-R to reload the page the check mark goes away. If you then click Submit you will see in the status that it was actually checked (and it indeed becomes checked after the page reloads after clicking submit). Safari works fine with this scenario.

Case 2, click the Method 2 link button and then click Submit. The status will show that the checkbox was actually checked, even though it showed not checked. After postback the proper state of the checkbox is indicated in the UI.

Case 3, Click the MEthod 3 link so that the checkbox becomes disabled. Then click the checkbox to make it checked. Finally click Submit and notice that the true state of the checkbox was actually unchecked and the UI updates to properly pick up that change after postback.

```
<%@ Control Language="C#" AutoEventWireup="true" CodeFile="Test.ascx.cs" Inherits="Plugins_com_shepherdchurch_SampleProject_Test" %>

<Rock:RockCheckBox ID="cbTest" runat="server" Label="Check me" SelectedIconCssClass="fa fa-check-circle" UnSelectedIconCssClass="fa fa-circle-o" />
<asp:Button ID="btnTest" runat="server" OnClick="btnTest_Click" Text="Submit" />
Status: <asp:Label ID="lbTest" runat="server" /><br />
Method 2: Clicking <a href="#" onclick="$('#<%= cbTest.ClientID %>').click(); return false;">me</a> will send a click() event to the checkbox.<br />
Method 3: Clicking <a href="#" onclick="$('#<%= cbTest.ClientID %>').prop('disabled', true); return false;">me</a> will disable the checkbox.<br />
```

```
using System;
using System.ComponentModel;

[DisplayName( "Test" )]
[Category( "com_shepherdchurch > Sample Project" )]
[Description( "Test" )]
public partial class Plugins_com_shepherdchurch_SampleProject_Test : Rock.Web.UI.RockBlock
{
    protected void btnTest_Click( object sender, EventArgs e )
    {
        lbTest.Text = cbTest.Checked.ToString();
    }
}
```

**Comment by sparkdevnetwork-service** [comment]
➤ Jon Edmiston commented:
test comment from asana

**Comment by jonedmiston** [comment]
Closing as this is only a problem in Firefox (< 4% of browsers) and will be address in NextGen.
