### ISSUE TITLE
Registration Attribute Changes can change actual Person Attributes.

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1856]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We setup a registration with a person attribute (T-Shirt Size). The T-Shirt Size attribute used defined values. After the registration was setup we were told it just needed to have Adult sizes and not all sizes. We changed the source from Person Attribute to Registration Attribute. Filled out the info and told it to be a single select Field Type with adult sizes and saved the attribute and saved the template. Edit the template again and the source remained Registration Attribute but the Field Type reverted back to Defined Value. If you edit the field type once more and save it, it will save properly. 

But that's not the only bug. Go back to a persons extended attribute and look for the category the original T-Shirt Size attribute was saved to...no longer there. If you go to General Settings > Person Attribute it won't be listed there any more. I had to search the database and realized the attribute got update and set as a registration attribute and no longer as a Person Attribute. I don't know if this is the result of the keys being the same (something I thought it checked for so it wouldn't create duplicate keys).

I would think if you decided to delete the modified registration attribute it would fully delete the attribute and all of the original person attribute values with it. Haven't tested it, just a thought. 

This could also allow a person with Registration Template access but not Person Attribute edit access to bypass the security settings and modify Person Attributes.

### Steps to Reproduce
I have only tested this with a defined value attribute but it may work with other field types.

Create Defined Type.
Create Values for Defined Type.
Create Person Attribute that uses Defined Values.
Select the Defined Type.
Give it a category.
Go to a person's profile and select a value for that person's attribute and save.
Create Registration Template.
Add form attribute. Source = Person Attribute: The attribute you created.
Select whatever settings you want and save.
Save Registration Template.
Create Instance.
Test Instance if you want.
Edit Registration Template.
Switch the Attribute's source from Person Attribute to Registration Attribute. Fill out the settings however you want. I kept the key the same as the original Person Attribute's Key.
Try setting field type as single select with any values you want.
Save the attribute.
Save the form.
Test registration if you want.
Edit the template again. 
Edit the attribute. The source remained Registration Attribute but the Field Type reverted back to Defined Value (or didn't update at all). Switch it to Single Select again and any values you want.
Save attribute.
Save Form.
Test registration if you want.
Go back to the Person Profile you went to earlier. Look to see if their attribute is still in extended attributes. It shouldn't be listed anymore.
Go to General Settings > Person Attributes. You won't find the original attribute listed there anymore.
It is still in the database but now only tied to that one registration.

I tested this on the demo server with same results. The attribute I tested was t-shirt sizes and the registration I created was called Test Registration (Id 5).

**Expected behavior:** [What you expected to happen]
When switching to Registration Attribute create new attribute not update original. 
Check to see if key is already present in the database (unless it doesn't matter since it is now tied to the one registration instead).

**Actual behavior:** [What actually happened]
Updates the Person Attribute to a registration attribute and it is no longer accessible in general settings or extended attribute. Update the original's field type and values to the new one...which could potentially remove/delete previous attribute values from when it was originally a person attribute.

### Versions
v5.3

* **Rock Version:** 5.3

**Comment by nairdo** [comment]
This same, unfortunate behavior exists in v6.
