### ISSUE TITLE
Member List Field Type for Reports does not export member's name just a line of code

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1858]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When creating a Group Report with a Member List Field, when the report is exported the member list data isn't properly exported:
"Rock.Reporting.DataSelect.Group.MemberListSelect+MemberInfo, Rock.Reporting.DataSelect.Group.MemberListSelect+MemberInfo"

Test on demo site with the report called Testing Member List Export.

### Steps to Reproduce

Create Data View. Applies to Group. Assign the Group Id to equal a current group's Id. Save
Create Report. Applies to Group. Select the save data view. Add Field. Select Member List. Select any of the three radio buttons. Select the Group Type of the group. Save.

Member List properly displays on the site but when exported it doesn't.

**Expected behavior:** 
List the group members

**Actual behavior:** 
lists code.

### Versions
v5.3

* **Rock Version:** v5.3

**Comment by dcs619** [comment]
This is confirmed fixed in v7.  I think @chrismcgrath may have fixed it a while back.

![screen shot 2017-03-24 at 11 17 38 am](https://cloud.githubusercontent.com/assets/1210933/24300655/88d87df4-1083-11e7-9b0e-4d2a3ca65eeb.png)

![screen shot 2017-03-24 at 11 15 58 am](https://cloud.githubusercontent.com/assets/1210933/24300623/718b7d04-1083-11e7-91d3-37fe9a6e9bfe.png)
