### ISSUE TITLE
Registration Payment Page doesn't support NMI gateway

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1869]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Unable to process payment on the internal side for a registrant when using the NMI gateway. External payment page works fine just the internal page doesn't support NMI.

### Steps to Reproduce

Make sure you are using the NMI Gateway
 Open the registration details page for the registrant/registration you are want to add payment to on the staff side. 
Click Process New Payment button.
Enter card information. 
Submit. 
Error thrown saying it isn't a 3-step process so it couldn't process the payment.

**Expected behavior:** 
Staff side to successfully submit payment for a registrant/registration.

**Actual behavior:** 
Unable to do so because the page doesn't support the 3-step process.

### Versions

* **Rock Version:** v5.3

**Comment by nairdo** [comment]
We understand the issue and are going to address it.

**Comment by tommyprater** [comment]
Just curious is there a time frame on this bug fix?

**Comment by edmistj** [comment]
This will be in v7.0 (still a ways out for release). This only effects internal entry of credit cards to a registration. As a work around the staff person could use the complete payment link on the external website to process the transaction.

**Comment by tommyprater** [comment]
@edmistj thanks for sharing this. What is the best way to set up that link for the staff person to access it? Just want to make sure Im doing this right.

**Comment by edmistj** [comment]
Here's a quick video on how to accomplish this. It's by no means perfect as the transaction will be recorded as coming from the individual (not as entered by the staff person) but hopefully it helps in the meantime. http://www.rockrms.com/Registration?RegistrationId=1483&rckipid=EAAAAIqZAiDvFQI6HicJz2KcSalJoTOEODJWGZgx8oduv0BOXHibRnlcAhxwEcNLMWYI6rRSyua8Jz2!2bE!2f2AZmT51zU!3d

**Comment by tommyprater** [comment]
Thanks @edmistj but when I use the send payment reminders it only brings up 1 of the payments and I can't select individually. Does that make sense?

**Comment by edmistj** [comment]
Not sure I understand

**Comment by colobren** [comment]
When you use this method, the link I copy from the email only allows me to process a payment for the first individual on the list.  If I'm trying to apply a payment for someone further down the list, I cannot select that individual.  Hopefully that makes sense.

**Comment by tommyprater** [comment]
@colobren yeah you actually can't do this.

Sent from my iPhone

On Apr 25, 2017, at 9:31 AM, colobren <notifications@github.com<mailto:notifications@github.com>> wrote:


When you use this method, the link I copy from the email only allows me to process a payment for the first individual on the list. If I'm trying to apply a payment for someone further down the list, I cannot select that individual. Hopefully that makes sense.

**Comment by eddieholeman** [comment]
@edmistj does this bug the use of NMI gateway in external website?  When the Next button is clicked for the payment information screen to come up, nothing happens on mine.  No error.  Just stalls.  When I change the event registration to use Payflow, it seems to work fine.

**Comment by tommyprater** [comment]
@eddieholeman the external website part works great for us using NMI. I will have to look but you should just have to select it in the template or instance.

**Comment by eddieholeman** [comment]
@tommyprater Thanks Tommy.  Obviously we are doing something wrong.  I just logged into our gateway manually to check security and it is wide open.  So, I don't think that is the direction to head.  But at this point, I am not sure which direction.  I can't find a problem except that it doesn't work.  :-)

**Comment by eddieholeman** [comment]
@tommyprater what are the chances that you could take some financial gateway screens shots, redacting what is necessary, and send those to me at eholeman@fellowshipgreenville.org.  Maybe something will stand out that we have in error.  I would really appreciate it.

**Comment by edmistj** [comment]
@eddieholeman  This missing feature should not impact the external site.

**Comment by eddieholeman** [comment]
David Turner found the answer for me, I hope.  Looks like my TransNational
account is not setup to Customer Vault


*Eddie Holeman | Director of Information Technology*
*Fellowship Greenville*Greenville, SC

*office* 864.234.7033 x1202

**Comment by treyhendon** [comment]
A slightly easier work around for finance would be to add this HTML/Lava to an HTML block on the Registration Details page.  Make sure to set cache = 0 and enable Rock Entity on the block.

Warn them to always open the link an an Incognito Window - otherwise they'll have to close browser and log in again.

```
{% assign registrationid = PageParameter['RegistrationId'] %}

{% registration Id:'{{ registrationid }}' %}
    <a href="{{ externalSite }}/Registration?RegistrationId={{ registration.Id }}&rckipid={{ registration.PersonAlias.Person.UrlEncodedKey }}" target="_blank" class="btn btn-primary pull-right">RIGHT-CLICK AND SELECT 'OPEN LINK IN INCOGNITO WINDOW'</a>
{% endregistration %}
```

**Comment by azturner** [comment]
This was fixed for v7 here: https://github.com/SparkDevNetwork/Rock/commit/301bf68b
