### ISSUE TITLE
Benevolence workers cannot upload files to requests in V6

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1877]
### Prerequisites

* [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [x] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Benevolence workers can upload documents in Rock V6, but because they do not have security access to the BinaryFile REST controllers, uploads will fail.

### Steps to Reproduce

1. Create a user with a RSR - Staff Worker and RSR - Benevolence Worker security membership
2. Attempt to upload a document to a benevolence request with that user.
3. Error thrown immediately, "Not authorized to upload this type of file"

**Expected behavior:** Upload succeeds since the form is visible

**Actual behavior:** Rock throws a "Not authorized to upload this type of file" for non-admin level users

### Versions

* **Rock Version:** 6.0
* **Client Culture Setting** en-US

**Comment by edmistj** [comment]
Great find!
