### ISSUE TITLE
v6beta Summernote Pastes into wrong location with FireFox

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1878]
* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The summernote editor in v6 beta, when running on Firefox (Win) doesn't paste at the insertion point (cursor position). It instead inserts the pasted text (or image) at the top of the editor.

### Steps to Reproduce

1. Using Firefox (49.0.2 here) open a Summernote editor
2. Type some text, then copy some text from some other app and attempt to paste it to the end of your existing text. 
3. Instead of being inserted where your cursor is, it inserts at the top

**Expected behavior:** Inserts occur where the cursor is location

**Actual behavior:** Inserts happen at the top of the editor regardless of cursor position. I have been able to replicate this on both the demo site, the rockrms QA, and our own Rock server running v6Beta.

### Versions

* **Rock Version:** v6beta
* **Client Culture Setting** en-US

**Comment by nairdo** [comment]
I have confirmed this is only happening in Firefox.  Neither Chrome or IE have this issue.

We are using Summernote version v0.8.1 and the seemingly closest related issue was https://github.com/summernote/summernote/issues/1382 which is said to have been fixed in v0.7.0.

**Comment by MikeDPeterson** [comment]
fixed in v7 with https://github.com/SparkDevNetwork/Rock/commit/a805d489a9bf92e6b0cfa5262b7c1eff3ad70bce

**Comment by joshuahenninger** [comment]
We have confirmed that this is not an issue in the Obsidian HTML Editor control in the Next Generation framework.
