### ISSUE TITLE
CSS from Rock New Communication leaks into App

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1879]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [x] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

CSS embedded inside a email template will effect the entire new communication page. Not just the message, which can produce undesirable appearance changes.

### Steps to Reproduce

1. Visit http://rock.rocksolidchurchdemo.com/Communication

**Expected behavior:** CSS found in template only effects the message, not the Rock app.

**Actual behavior:** CSS effects the entire app.

### Possible Solutions

- Iframes, not perfect, but used by most email vendors to scope email styles
- [Scoped CSS style tags](https://css-tricks.com/saving-the-day-with-scoped-css/). Rock could inject a scoped tag onto emails before render, and remove it before saving.

### Versions

* **Rock Version:** 5.1 - 6.0 Beta
* **Client Culture Setting** en-US

**Comment by nairdo** [comment]
Just an FYI.  There are plans to rebuild the New Communication block into a much more capable system (allowing for template content areas that can be restricted, etc.). I don't think there is much that can be done with this until then.

**Comment by nairdo** [comment]
Since this is going to be addressed with v7's new communication editor/system, I'm closing this in an effort to clean up.  Thanks again for reporting this.
