### ISSUE TITLE
v6 public facing "Workflow Entry" page is poorly named

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1881]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
In v6 there is a new page on the external site for editing your account, with an option to request additional changes that aren't allowed to be performed by the user. This page is named "Workflow Entry" which seems poorly named and user un-friendly.

[Description of the bug or feature. Include screenshots if applicable.]

### Steps to Reproduce

1. On the external Rock site log in and navigate to My Account
2. Click the Request Additional Changes button
3. Observe that the page you're now on is named "Workflow Entry"

**Expected behavior:** Page would be named something like Request Changes or similar, not "Workflow Entry"

**Actual behavior:** Page is named Workflow Entry, which likely has no meaning to a public user and seems out of context in this UI. The user has no clue they are initiating a workflow and shouldn't need to know that. Yes I realize this is a trivial fix by just renaming the page but in my opinion out of the box it should be named something more user friendly, like "Request Changes" or similar.

### Versions

* **Rock Version:** v6 beta
* **Client Culture Setting** en-US

![workflow entry external website](https://cloud.githubusercontent.com/assets/3903408/20453190/3e6538a6-ade2-11e6-8253-ab469b599a8c.png)

**Comment by edmistj** [comment]
The workflow entry block should probably change the page title to be something like Workflow Type Name

**Comment by nairdo** [comment]
Hmmm, that would make the http://rock.rocksolidchurchdemo.com/ContactUs page become "External Inquiry" 
![image](https://cloud.githubusercontent.com/assets/383807/20505865/1b324572-b00d-11e6-8111-9fcb7a5a133d.png)
