### ISSUE TITLE
GroupMemberService.GetKnownRelationship() Returns No One for Deceased People

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1882]
### Prerequisites

* [ x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x ] Did you include your Rock version number and client culture setting? 5.4 and N/A
* [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [ x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

`GetKnownRelationship()` fails to return any group members if the personId belongs to a deceased person. This is because the `.Queryable()` is not `.Queryable(true)`.

### Steps to Reproduce

1. Make Ted Decker Deceased
2. Call .GetKnownRelationship()

**Expected behavior:**
The function should return a list of group members that belong to Ted Decker's known relationship group.

**Actual behavior:**
`knownRelationshipGroupId` is set to 0 as the query fails and and so the function fails to find any group members in the group.

### Versions

* **Rock Version:** 5.4
* **Client Culture Setting** N/A
[Included from your Rock installation](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information)
N/A

I'll submit a pull request for this.

**Comment by arranf** [comment]
This was first found in the comments of #1342

**Comment by nairdo** [comment]
@arranf, If you're fixing this for 6.1, remember to commit it to the hotfix-1.6.1 branch within the next 3 days.  Otherwise just assign it to me.
