### ISSUE TITLE
Changing family record status removes deceased attribute

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1887]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [x] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

While not ideal, if a deceased family member is temporarily left in a family and the family record status is set to active, the deceased status is removed.

### Steps to Reproduce

1. Make a family member inactive with a reason deceased
2. Go to the edit family screen, change the record status dropdown to active

**Expected behavior:** Family becomes active aside from deceased family member

**Actual behavior:** Deceased attribute is removed

### Versions

* **Rock Version:** 6.0
* **Client Culture Setting** en-US

**Comment by nairdo** [comment]
This came up during the design of this feature. When the situation occurs, there is a small warning icon shown.  If you click the icon for more details it explains that the family members have different statuses & reasons.  Changing all family members record status this way will change all members record statuses.

![image](https://cloud.githubusercontent.com/assets/383807/20768307/aa4d1978-b6fa-11e6-94c8-3f3111ef80bc.png)

**Comment by garrettjohnson** [comment]
I love the warning icon! Since Rock treats the deceased status with a different level of care, and it's unlikely that a staff member would knowingly want to remove the deceased attribute using family edit... Would it make sense to exclude deceased family members from the record status update?

**Comment by arranf** [comment]
The use case for this, I imagine, is to either inactivate a family when they all stop attending or activate a family when they all start attending again. If that's the case it makes sense to ignore deceased from my perspective.
