### ISSUE TITLE
Registration Confirmation Email Not Honoring Lava Entity Command

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#1888]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Lava Entity Command is not working in Registration Confirmation Emails.
* Liquid error: Object reference not set to an instance of an object.

### Steps to Reproduce

1. Use following Lava in Registration Confirmation Email.  Note: Lava works properly in the Central Lava Tester (once Global Attribute is enabled).

```
<div class="occurrence-details">
{% registrationinstance where:'Id == "{{ RegistrationInstance.Id }}"' limit:'1' %}
        {% assign registrationInstanceName = registrationinstance.Name %}
        {% eventitemoccurrencegroupmap where:'RegistrationInstanceId == {{ registrationinstance.Id }}' %}
            {% eventitemoccurrence where:'Id == {{ eventitemoccurrencegroupmap.EventItemOccurrenceId }}' %}
                {% campus id:'{{ eventitemoccurrence.CampusId }}' %}
                    {% assign eventitemoccurrenceCampus = campus.Name %}
                {% endcampus %}
                
                {% schedule id:'{{ eventitemoccurrence.ScheduleId }}' %}
                    {% assign eventitemoccurrenceStart = schedule.iCalendarContent | DatesFromICal %}
                {% endschedule %}
                
                {% assign eventitemoccurrenceLocation = eventitemoccurrence.Location %}
                {% assign eventitemoccurrenceContact = eventitemoccurrence.ContactPersonAliasId | PersonByAliasId %}
                {% assign eventitemoccurrenceContactEmail = eventitemoccurrence.ContactEmail %}
            {% endeventitemoccurrence %}
        {% endeventitemoccurrencegroupmap %}
{% endregistrationinstance %}

<ul>
<li>TEST: {{ RegistrationInstance.Id }} - {{ RegistrationInstance.Name }}</li>
<li>{{ registrationInstanceName }}</li>
<li>{{ eventitemoccurrenceCampus }}</li>
<li>{{ eventitemoccurrenceStart }}</li>
<li>{{ eventitemoccurrenceLocation }}</li>
<li>{{ eventitemoccurrenceContact.FullName }}</li>
<li>{{ eventitemoccurrenceContactEmail }}</li>
</ul>

</div>
```

**Expected behavior:** Lava should render.

**Actual behavior:** Lava returns error.

### Versions

* **Rock Version:** Rock McKinley 6.0  
* **Client Culture Setting** en-US

**Comment by nairdo** [comment]
@treyhendon I am able to reproduce this issue but I've got some questions/concerns about your Lava:

1) Your first entity-command should be using the "id" parameter like this:
`{% registrationinstance id:'{{ RegistrationInstance.Id }}' %}` 

2) The eventitemoccurrencegroupmap "where" could return a collection, so you would be safer to iterate over the results... something like this:
```
{% for eiogm in eventitemoccurrencegroupmapItems %}
{{ eiogm.EventItemOccurrenceId }} ...
{% endfor %}
```

The actual issue is caused by the fact that [no person object is being passed to the ResolveMergeFields of the SendRegistrationConfirmationTransaction](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Transactions/SendRegistrationConfirmationTransaction.cs#L89) (which is basically required when you're using Entity commands due to the need to implement security).  I'm looking into a fix for this now.

**Comment by treyhendon** [comment]
Thanks @nairdo !

I think when I was first testing the id parameter, I was missing the single-quote and that's why it didn't work for me.

Additionally, I didn't realize there could be more than one Group in that list, thanks!

**Comment by treyhendon** [comment]
This appears to have reoccured in 7.3.

**Comment by treyhendon** [comment]
Well, I was a few days early.  This is working again in 7.4.  Sorry for the false alarm.
