### ISSUE TITLE
V6 Summernote broken for HTML email

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1891]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [x] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Summernote uses contenteditable, which makes it difficult to use for HTML email because the element forces removal of both the head, html, and body tags.

See:
https://github.com/summernote/summernote/issues/2027
https://github.com/summernote/summernote/issues/349

### Steps to Reproduce

1. Paste full HTML code in the source element of a email or other Summernote form
2. Return to WYSIWYG mode. (Tags are already removed)
3. Go back to code editing mode and tags are removed

**Expected behavior:** Pasted source is kept in tact

**Actual behavior:** Source is heavily modified, removing html/head/body tags, for emails the modified code is no longer valid HTML.

### Versions

* **Rock Version:** 6.0
* **Client Culture Setting** en-US

**Comment by edmistj** [comment]
The head, html, and body tags were also stripped out from CK Editor in Rock v1.0-5.x. There doesn't seem to be much we can do about that in the current Email authoring block. We have plans to provide a completely different authoring tool in v7 (work is in progress on that).

**Comment by JimMichael** [comment]
I will just chime in that we are also getting complaints from users that emails they used to construct (usually containing tables) now break in v6, so while CK editor might have done similar destruction of HTML, SummerNote seems to be doing it "worse." Looking forward to v7 fixes for communications, for sure!

**Comment by garrettjohnson** [comment]
What if there was a global attribute called `EmailHead` used on the default template, and it contained everything up to the body element of the email? 

There would probably need to be a way to hide the lava tag from rendering in the visual editor using JS so that users don't mistakenly delete it.

**Comment by arranf** [comment]
@garrettjohnson How are you getting around this now? Is this still an issue?

**Comment by arranf** [comment]
This is still an issue however it looks like summernote/summernote#2027 has been closed as a won't fix so I'm going to close this too given email authoring is way better now!
