### ISSUE TITLE
Various Workflow Actions have duplicate allowed field types in WorkflowAttribute

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#1894]
### Prerequisites ###

* [ ] Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
* [ ] Did you include your Rock version number and client culture setting?
* [ ] Have you attached your [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) environment and diagnostics information ]() to this issue?
* [x] Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

In a number of Group related Workflow Actions (possibly other similar actions as well) there exists this style of WorkflowAttribute definition:

```
[ WorkflowAttribute("Group", "The attribute containing the group to get the leader for.", true, "", "", 0, null,
        new string[] { "Rock.Field.Types.GroupFieldType", "Rock.Field.Types.GroupFieldType" }) ]
```

For example, here is one instance: [https://github.com/SparkDevNetwork/Rock/blob/1928822b6a4e92ff327b6a070b18f7f80fca7717/Rock/Workflow/Action/Groups/SetGroupAttribute.cs#L41](https://github.com/SparkDevNetwork/Rock/blob/1928822b6a4e92ff327b6a070b18f7f80fca7717/Rock/Workflow/Action/Groups/SetGroupAttribute.cs#L41)

Based on the code in the Execute method it just needs a GUID value. Are these supposed to be defined as TextFieldType and GroupFieldType rather than doubling down on the GroupFieldType? I can hunt through for these and submit a pull request, but wanted to make sure it was the correct change.

### Versions ###

* **Rock Version:** Trunk

**Comment by nairdo** [comment]
> Are these supposed to be defined as TextFieldType and GroupFieldType?

The action's Group attribute has the "Rock.Field.Types.GroupFieldType" to _constrain_ which Workflow attributes can be chosen.  I don't think I originally intended someone to use a text field to designate the attribute manually by its Guid.  I think it's just a typo/bug that I propagated when I created this and the SetGroupMemberAttribute actions which was modeled after the  [`SetAttributeToGroupLeader`](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Workflow/Action/WorkflowAttributes/SetAttributeToGroupLeader.cs#L42) action.

Based on which workflow attribute (of type group field) the admin selected at config-time/runtime, the execute method uses the group stored in there to find the group and save the value to the group's attribute that is specified by the key stored in `GroupAttributeKey`.

**Comment by cabal95** [comment]
So which would be the proper fix? :)  I can't think of a reason not allow a text field type to be used on the "Get" versions.  A number of the "Set" functions (like SetAttributeToGroupLeader) allow you to use either a Group/Person attribute and a Text attribute on the target attribute.

I have a couple ideas on how I could use the various actions if they could convert GUIDs to actual object attributes.  Like getting the leader PersonField attribute from a group's GUID value.

So I'm happy to submit a pull request for either solution, just need to know which way to change the code.
