### ISSUE TITLE
"Date Time" Attribute in Workflow User Entry Form Doesn't Honor "Required"

### ISSUE THREAD

**Issue by matthewmeekins** [SparkDevNetwork/Rock#1898]
### PLEASE READ

If the nature of your issue relates to the security of Rock please do not post your
issue here in the public issues.

### Prerequisites

* [X] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [ ] Did you include your Rock version number and client culture setting?
* [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If a user entry form in a workflow has the "date time" attribute and "required" is checked, the workflow will still process with nothing in the "date time" field. This is also true if "require a value" is checked in the attribute itself. 

### Steps to Reproduce

1. Create a workflow with a user entry form and a "date time" attribute.
2. Set the attribute on the form to Visible, Editable, and Required.
3. Set the workflow to complete after clicking "Submit".
4. Click "Submit"

**Expected behavior:** I expect that when clicking submit with nothing in the "date time" field, that the field would be highlighted red with a message to enter a value. 

**Actual behavior:** Clicking submit processes the workflow without a value in the "date time" field. 

### Versions

* **Rock Version:** Rock McKinley 6.0  
* **Client Culture Setting** [Enter Client Culture here]  
[Included from your Rock installation](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information)

**Comment by cabal95** [comment]
I believe this is related to #1705.

**Comment by arranf** [comment]
Closing as this does appear to be a duplicate of #1705. We'll keep all duplicate workflow attributes there and we can reopen this if this is not related.
