### ISSUE TITLE
Attribute Set Value cannot set Defined Value attribute using Text Value

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#1902]
### PLEASE READ

If the nature of your issue relates to the security of Rock please do not post your
issue here in the public issues.

### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [x] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you have a workflow attribute of field type Defined Value, you cannot set it using the Text Value field of the Attribute Set Value action.

### Steps to Reproduce

1. Create a new workflow type
2. Add an attribute called Location of Field Type = Defined Value, Defined Type = Location Type, Default Value = Work
3. Add an Attribute Set Value action to the default activity where Attribute = Location and Text Value = 8C52E53C-2A66-435A-AE6E-5EE307D9A0DC
4. Run the workflow
5. Look at the workflow attributes

**Expected behavior:** 

The attribute would be set to Home

**Actual behavior:**

The attribute is blank

**Note**

I also tried setting the text value to Home and to 19 (the ID) but neither worked.  We were able to determine, however, that this action does work if, instead of using Text Value, you populate a new text attribute with the desired guid and use the Attribute Value field of Attribute Set Value, this does properly set the attribute. So it's just Text Value that is not working.

### Versions

* **Rock Version:** Rock McKinley 6.0
* **Client Culture Setting** en-US
[RockDiagnostics-ROCK2.txt](https://github.com/SparkDevNetwork/Rock/files/628104/RockDiagnostics-ROCK2.txt)

**Comment by cabal95** [comment]
It appears that the Text Value, being a GUID, is assumed to be a reference to a Workflow Attribute. It then tries to retrieve a value for that (non existent) attribute and ends up with an empty string for some reason instead of null.

**Comment by chrismcgrath** [comment]
Fixed by @edmistj a while back.
