### ISSUE TITLE
Metrics-Partition NO SCHEDULE issue

### ISSUE THREAD

**Issue by winmastr** [SparkDevNetwork/Rock#1908]
### PLEASE READ ###

If the nature of your issue relates to the security of Rock please do not post your

issue here in the public issues.

### Prerequisites ###

* [ ] Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
* [x] Did you include your Rock version number and client culture setting? Yes
* [ ] Have you attached your [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) environment and diagnostics information ]() to this issue?
* [x] Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

[After creating partitions for Campus and schedule, all correctly reflected in the dropdown on the metrics page. the Metric values area show NO SCHEDULE even when a schedule has been selected and is reflected when you open the metric values individually.]

![<a href="https://cloud.githubusercontent.com/assets/24417039/20937453/ab24cf88-bbac-11e6-9a9d-254f5b62c8ee.png">https://cloud.githubusercontent.com/assets/24417039/20937453/ab24cf88-bbac-11e6-9a9d-254f5b62c8ee.png</a> image]()

### Steps to Reproduce ###

1. [First Step]
1. [Second Step]
1. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

###  ###

![<a href="https://cloud.githubusercontent.com/assets/24417039/20937347/327beb70-bbac-11e6-9fd9-8135ccce763f.png">https://cloud.githubusercontent.com/assets/24417039/20937347/327beb70-bbac-11e6-9fd9-8135ccce763f.png</a> image]()

* **Rock Version:** 6 beta
* **Client Culture Setting** [Enter Client Culture here]

[[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) Included from your Rock installation ]()

**Comment by treyhendon** [comment]
Also seeing this same issue with one of our clients.  Additionally, when trying to view metrics that have a schedule set (even though "no schedule" in grid), the filter is not able to locate the metric values either.

**Comment by arranf** [comment]
@winmastr Could you please edit your issue to include the steps to reproduce this? It helps others solve your problem.

**Comment by jonedmiston** [comment]
Closing due to no reproduction steps.
