### ISSUE TITLE
v6beta check-in config settings don't stick

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1910]
* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
v6beta has several new check-in configuration enhancements: Hide Photos, Hide Inactive People, Prevent Duplicate Check-in. These can be set at the Check-in configuration level, or at the individual Area level. When set at the check-in configuration level (e.g. Weekly Service Check-in Area) they seem to work fine, but when you try to set them from "no" to "yes" at any Area level, they fail to stay set.

### Steps to Reproduce

1. Go to Admin | Check-In | Weekly Service Check-in Area
2. Click on any check-in area and change one or all of the new settings from No to Yes. 
3. Click save, then refresh the page and click on the same Area you just modified.
4. Observe that the settings you changed are now back to "No."
5. Edit the check-in configuration itself and set one or all of the new settings to Yes.
6. Click Save, then edit again and observe that the settings here have been saved.

**Expected behavior:** Check-in config settings done per-area are saved and operate correctly.

**Actual behavior:** The settings are not saved and thus cannot be used per-Area. Only the check-in configuration itself can save these settings, which is not the design.

![check in configuration1](https://cloud.githubusercontent.com/assets/3903408/20954361/43321d96-bc00-11e6-8d8e-3ea6d043fb29.png)
![check in configuration2](https://cloud.githubusercontent.com/assets/3903408/20954364/4736be92-bc00-11e6-8a2c-49d8454bf06e.png)

### Versions

* **Rock Version:** v6 beta
* **Client Culture Setting** en-US

**Comment by azturner** [comment]
This actually represents two issues...

First issue is that those attributes should only apply to the group type with "check-in" purpose which are edited in the config section above areas and groups. That is fixed here: https://github.com/SparkDevNetwork/Rock/commit/c2039cf8324c1961bbd3addd66569b610ed79b21.

Second is that if an attribute does apply to the area group type, it can't be saved. That is fixed here: https://github.com/SparkDevNetwork/Rock/commit/1b17fa3aa50fb3bb9de4402239b46d54e2bc57a2
