### ISSUE TITLE
v6 PodcastMessageDetail.lava has wrong comparison operator in lava

### ISSUE THREAD

**Issue by gonemob** [SparkDevNetwork/Rock#1912]
### PLEASE READ

If the nature of your issue relates to the security of Rock please do not post your
issue here in the public issues.

### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

PodcastMessageDetail.lava in v6 beta: When evaluating items.videoLink and audioLink, there are  **ampersands** as comparison operators rather than **and** and I think the evaluation should be _**or**_ instead.

### Steps to Reproduce

1. CMS Config > Podcast Content Channels > Series > Item
2. Edit an item so there is no video link, only audio
3. External Site > Watch > Series Detail

**Expected behavior:** Expect the **Downloads & Resources** to display with the link to the Audio Download

**Actual behavior:** The section does not display.  If video link present, **always** evaluates to true.
![screen shot 2016-12-07 at 1 46 32 pm](https://cloud.githubusercontent.com/assets/13141251/20984206/e5cd6a7c-bc84-11e6-8cd9-97c0743cea2c.png)
![screen shot 2016-12-07 at 1 47 25 pm copy](https://cloud.githubusercontent.com/assets/13141251/20984208/e9b1e2bc-bc84-11e6-89b2-d5118ea0ee3a.png)
<img width="656" alt="screen shot 2016-12-07 at 1 47 53 pm" src="https://cloud.githubusercontent.com/assets/13141251/20984218/f06f805a-bc84-11e6-835d-d65862edff9e.png">

### Versions

* **Rock Version:** v6beta  
* **Client Culture Setting** en-US 
[Included from your Rock installation](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information)

**Comment by azturner** [comment]
Lava needs to use 'and' or 'or' (not '&&' or '||')
