### ISSUE TITLE
Background Check Result Attribute has duplicate permissions

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1914]
### Description
The background check result attribute has multiple duplicates of each role type. On the demo site all roles are stored three times, on my development and production environment the All Users role is the only role shown incorrectly (3x)

![<a href="https://cloud.githubusercontent.com/assets/374209/20989425/75644f76-bc89-11e6-9501-87c979a01751.png">https://cloud.githubusercontent.com/assets/374209/20989425/75644f76-bc89-11e6-9501-87c979a01751.png</a> screenshot 2016-12-07 14 25 53]()
 ^^^ From [[http://rock.rocksolidchurchdemo.com/page/71](http://rock.rocksolidchurchdemo.com/page/71) Demo Site ]()

### Steps to Reproduce
1. [http://rock.rocksolidchurchdemo.com/page/71](http://rock.rocksolidchurchdemo.com/page/71)
1. Select the security settings for `Background Check Result`

**Expected behavior:** Roles shown once per entry

**Actual behavior:** Security roles are shown (and stored) 3x per role.

### Versions
* **Rock Version:** 5.3-6.0 Beta
* **Client Culture Setting** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1168948836978384">image.png</a>

**Comment by crayzd92** [comment]
Fixed via migration in https://github.com/SparkDevNetwork/Rock/commit/32a382e2efa5ab23c40c564ed87c32d38a05cc2f
