### ISSUE TITLE
Lava Breaks User Entry Form Response Text

### ISSUE THREAD

**Issue by matthewmeekins** [SparkDevNetwork/Rock#1915]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [ ] Did you include your Rock version number and client culture setting?
* [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Using Lava in the response text of a button on a user entry form in a workflow will strangely break the buttons. Here is an example:

Before saving:
<img width="933" alt="screen shot 2016-12-08 at 4 04 05 pm" src="https://cloud.githubusercontent.com/assets/10676326/21027771/5954b000-bd60-11e6-8885-7c454ba165eb.png">

After saving:
<img width="938" alt="screen shot 2016-12-08 at 4 04 33 pm" src="https://cloud.githubusercontent.com/assets/10676326/21027790/677587a4-bd60-11e6-889f-87579136107a.png">

Workflow in use:
<img width="530" alt="screen shot 2016-12-08 at 4 04 49 pm" src="https://cloud.githubusercontent.com/assets/10676326/21027802/78ea28fa-bd60-11e6-9561-4835b1f24598.png">

The old Lava notation seems to still work in the field, but the new notation breaks at the pipe and adds a button with the text that came after it. 

### Steps to Reproduce

1. Create a workflow with an attribute and a user entry form.
2. Use lava to show the value of an attribute in the response text of a button on the user entry form using the {{ Workflow | Attribute:'[AttributeKey]' }} format. 
3. Click save.
4. Click edit.
5. You can see that the lava added a new button.

**Expected behavior:** I expect that when using lava to display a value in the response text of a button on the user entry form that it will output the value as text. 

**Actual behavior:** Using lava in the response text will add a button with half of the lava notation from the response text before it. 
### Versions

* **Rock Version:** 6.0 (also tested on the demo site on 5.3)

**Comment by Tschrock** [comment]
I believe this is related to #1512
The issue being the use of `|` as a delimiter for the backend list.

**Comment by cabal95** [comment]
Closed as Duplicate, will be tracked in original #1512.
