### ISSUE TITLE
Date Picker To-Date Field Selecting Today's Date

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#1922]
### PLEASE READ

If the nature of your issue relates to the security of Rock, please do not post it here in the public issues.

### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using keyboard to enter date filters on the batch list, the "to date" field will always set todays date after one keypress.  Then, after using the backspace key to remove the date, the auto-formatting does not apply to the entered date.  i.e.  12/7/16 is not conditioned properly.  

### Steps to Reproduce

See video for example.
https://www.dropbox.com/s/sil0i8vlqgu54tf/date_filter_bug.mov?dl=0  
  
1. Type-in or use date picker to select the "from date".
2. Tab to the "to date" box.
3. Press the number "1".  [Current date should then populate in box.]

**Expected behavior:** 

The "to date" box should behave as the "from date" box.

**Actual behavior:** 

Forcing users to delete the autofilled date and then retype desired "to date" without the benefit of the auto-formatting.

### Versions

* **Rock Version:** 6.1 (reproducible in demo site 5.3)  
* **Client Culture Setting:** en-US

**Comment by arranf** [comment]
Fixed

**Comment by nairdo** [comment]
@arranf is there a commit that goes with this fix?

**Comment by arranf** [comment]
@nairdo Someone else willed it to be fixed at some point in the past 9 months!
