### ISSUE TITLE
Merge Template does not work with Dynamic Data Person Report

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#1923]
### Prerequisites

* [X] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Using a Dynamic Data block, the Merge Template feature does not properly read the data if the Person Report option is set on the Dynamic Data.  Unchecking the Person Report option fixes the problem.

### Steps to Reproduce

1. Create a Dynamic Data block that populates with ID and Name from the Person table
2. Select the Person Report option in the Dynamic Data block configuration
3. Click the Merge Template button on the report
4. Click Show Data Rows on the Merge Template screen
5. Select a merge template and click the Merge button

**Expected behavior:** 

Show Data Rows would display 15 rows of data, and the merge template would be populated with data

**Actual behavior:** 

Despite the info box saying that there are X rows of data, Show Data Rows shows nothing and the merge template is not populated.

![image](https://cloud.githubusercontent.com/assets/18447084/21147077/65cf9a72-c119-11e6-997f-79c87c5af430.png)

### Versions

* **Rock Version:** 5.3 & 6.1
* **Client Culture Setting** en-US

**Comment by mikepetersonccv** [comment]
this was fixed with https://github.com/SparkDevNetwork/Rock/commit/297d3c6338878c45434dc33033b47018712ff6c9 

I double-checked and wasn't able to reproduce it on 1.7
