### ISSUE TITLE
Email subjects with Lava over 100 characters

### ISSUE THREAD

**Issue by cbump** [SparkDevNetwork/Rock#1928]
### PLEASE READ

If the nature of your issue relates to the security of Rock, please do not post it here in the public issues.

### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When lava in the subject of an email generates a subject over 100 characters, EF throws an error since the subject can't be saved.

### Steps to Reproduce

1. Go create a communication on http://rock.rocksolidchurchdemo.com/
2. Set the person to receive the email to Alisha Marble
3. Set the subject to: {{ Person.Email}} This is a test. This is a test. This is a test. This is a test. This is a test. This is a test. This is a test. This is a test. This is a test.
4. Attempting to send the email causes an exception.

**Expected behavior:** 
It should probably throw a warning that the lava will generate a subject over 100 characters long.

**Actual behavior:** 
An exception is thrown.

### Versions

* **Rock Version:** 1.6.0 & 1.5.3
* **Client Culture Setting** en-US

**Comment by nairdo** [comment]
@cbump I just rechecked this issue and can now report that the UI now prevents someone from entering more than 100 characters.  Can you confirm that this addresses your original issue?

**Comment by arranf** [comment]
Closing as fixed, at some point in the past.
