### ISSUE TITLE
Photo request template uses a missing attribute

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1930]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The photo request template uses the `{{ 'Global' | Attribute:'EmailStyles' }}` attribute, which does not exist.

### Steps to Reproduce

1. Go to Admin Tools / Communications / Communication Templates / Photo Request Template ([link via Demo Site](http://rock.rocksolidchurchdemo.com/page/275?TemplateId=2))

### Versions

* **Rock Version:** 5.1-6.0
* **Client Culture Setting** en-US

**Comment by edmistj** [comment]
We should remove this.

**Comment by JimMichael** [comment]
Was the reference above made to point out that Photo Request has legacy lava, too? (it does). Just trying to figure out if this is sufficient, or if I need to open an issue specific to that.

**Comment by edmistj** [comment]
I did add this one to the list. Is that what you're asking?

**Comment by JimMichael** [comment]
No, I was asking about Garret’s reference above to my legacy lava issue. I couldn’t tell if he was pointing out that the photo request WF had legacy lava as well, or something else, since THIS issue is about a missing attribute. I guess I’m easily confused :-)

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in 3e21ed58.
