### ISSUE TITLE
Rock Error after migration to Azure

### ISSUE THREAD

**Issue by gladsonj** [SparkDevNetwork/Rock#1936]
### PLEASE READ

If the nature of your issue relates to the security of Rock, please do not post it here in the public issues.

### Prerequisites

* [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? Sorry, no
* [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting? Rock 5.5
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
Hi, We had a working Rock installation hosted on a shared hosting server.
I imported the DB and copied the files to wwwroot folder.
I do get the login page.
But, once I enter the username and password, it redirects me to /page/3?returnurl=%252f with the message:
That Wasn't Supposed To Happen... An error has occurred while processing your request. Your organization's administrators have been notified of this problem.
I am on Rock 5.5
The Application Event Log has been attached:

### Steps to Reproduce

1. Used SQL Import and Export Tool to copy the DB to Azure
2. Used FTP to copy the files over to wwwroot
3. Modified web.ConnectionStrings.config to point to the azure Data Source and Initial Catalog
4. Accessed the root URL.
5. Was able to see the login page.
6. After entering the admin credentials, received the attached error. Also attached the Application Event Log from the Azure webserver.

**Expected behavior:** 

Login successfully

**Actual behavior:** 

Redirected to Error screen: /page/3?returnurl=%252f with the message:
That Wasn't Supposed To Happen... An error has occurred while processing your request. Your organization's administrators have been notified of this problem.

### Versions

* **Rock Version:** [5.5]  
* **Client Culture Setting** [Unable to fetch
[application_event_log.txt](https://github.com/SparkDevNetwork/Rock/files/661481/application_event_log.txt)
![application_error](https://cloud.githubusercontent.com/assets/21976051/21318898/1798cf30-c5d9-11e6-9b5d-028dd10ddb85.png)

]

**Comment by azturner** [comment]
Not clear on how you imported the database, but it appears your database table(s) are not configured correctly. The [Id] column on all Rock tables should be an 'Identity' column (in other words the id's should be getting generated automatically), but the reported error indicates that it is expecting the [Id] to be included on an insert which Rock does not do. You may want to seek some help in the Slack community on how best to copy your data from one hosting provider to another. Typically this would be done by creating a SQL Backup and then restoring that backup on your new host. A restore would not change the identity column setting.

**Comment by azturner** [comment]
Reread you steps.  You can't use the SQL Import/Export. That does not preserve settings like foreign keys, identity column settings, etc. You really need to take a backup of the database on your old server, and then restore that database on your new server.

**Comment by gladsonj** [comment]
I had to use a combination of SQL Database Migration wizard and SQL Server 2016 Import and Export. It's fine now. Thank you.
