### ISSUE TITLE
Registration Enhancement - Grade showing up as graduation year instead of grade

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1946]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When a registrant signs up and their grade is an attribute for the registration, it shows up as Graduation Year instead of Grade. But you can add a filter and select the grade or go into the actual registration and see the registrants grade. If there is a way to have the grade display I think that would be more practical or maybe an option on the attribute to display as Graduation Year or Grade.

### Steps to Reproduce

1. Create a Registration with a Grade Attribute (Person Field)
2. Add a registrant that has a Grade attribute.
3. View Registrant tab on the registration instance.

**Expected behavior:** 

Display the child's grade

**Actual behavior:** 

Displayed the child's graduation year.

### Versions

* **Rock Version:** v6.1

**Comment by BEGamache** [comment]
Also, Grade for a report shows up as the graduation date when the report is exported. Not sure if you want me to open another issue for this or if it may be closely related should be just 1 issue.

**Comment by nairdo** [comment]
@BEGamache No need to open a second issue regarding the export. They are directly tied together.  

I'm curious -- do you think the grade should only be shown or is there a case you where you'd want to see the grade as the graduation year?

**Comment by BEGamache** [comment]
@nairdo Thanks. I think the majority of the time our staff and volunteers are only interested in their grade and not their graduation year--especially our Children's Ministry. I think maybe our Youth Ministry may, on a rare occasion, want to see a graduation date but the majority of the time they would just want the grade.
