### ISSUE TITLE
Blog post detail view displays incorrect content

### ISSUE THREAD

**Issue by bengoshow** [SparkDevNetwork/Rock#1950]
If you click on any blog post link on the demo site (http://rock.rocksolidchurchdemo.com/page/2306) it takes you to a blog post detail page, passing the post ID in the URL parameter.

However, the content on the detail page displays only the most recent blog post's content, regardless of the URL or "Item" parameter.

**Comment by nairdo** [comment]
This is actually just a block setting that needs to be adjusted on the ContentChannelView block.  I've called out two items shown here.  Item 1 is actually the flag you'd want to enable if you're passing item parameters in and item 2 is also something you'd want to change so the content does not get cached by the block with the wrong item's content:

![image](https://cloud.githubusercontent.com/assets/383807/21645577/dc49115a-d24f-11e6-8c38-d1a301b35bf3.png)

**Comment by bengoshow** [comment]
Thanks Nick! Jim Michael pointed me to the same solution on Slack.
