### ISSUE TITLE
PublicProfileEdit block does not save address changes

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1951]
* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The v6 PublicProfileEdit block does not save postal address

### Steps to Reproduce

1. Log on to External site on rock.rocksolidchurchdemo.com and go to /MyAccount
2. Click Update button
3. Add or change existing Home Address information and click save

**Expected behavior:** 

New or modified address information would be saved

**Actual behavior:** 

All address changes are lost after you click save, though no error or exception is thrown.

### Versions

* **Rock Version:** 6.1

**Comment by azturner** [comment]
Fixed here: https://github.com/SparkDevNetwork/Rock/commit/696cf32afd0b3daf57cf26bbe43f8b866bdf1034
