### ISSUE TITLE
Excessive Metaphone exceptions being thrown for long names

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1955]
* [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We're seeing almost 1k of these exceptions every week:
```
Exception in Global.DrainTransactionQueue(): SaveMetaphoneTransaction

Entity Validation Error: Metaphone (Name): The field Name must be a string or array type with a maximum length of '50'.  
```

![screen shot 2017-01-04 at 7 09 38 pm](https://cloud.githubusercontent.com/assets/1210933/21664079/51ba3894-d2b2-11e6-8ff4-b63dddc5e44d.png)

### Steps to Reproduce

1. Try to save a Metaphone.Name with a string longer than 50 characters.

**Expected behavior:** 

The [Metaphone.Name](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/Metaphone.cs#L46) field should either be expanded to more than 50 characters or the Metaphone algorithm set to trim at 50 characters.  

Of note: 90% of the names in our current Metaphone table are under 12 characters.  Of the long names, almost all of them are for Business names.

### Versions

Rock Version: Rock McKinley 6.0
Client Culture Setting: en-US

**Comment by edmistj** [comment]
Let's expand this field to 100 but also trim it so even super long ones don't throw exceptions.
