### ISSUE TITLE
Icon labels printing incorrectly when using iPad app

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1971]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Icon labels printing incorrectly when using the specific combination of iPad app and client printing.

### Steps to Reproduce

1. Set an iPad kiosk device in Rock to server printing

2. Make sure you have the default Child Label (Icon) set as the label to print on your Check-in test area

3. Using the iPad app, check in with a child that has no allergy or legal situation attributes set

4. Observe that the label correctly prints with no Allergy or Legal icon. As another test, add an allergy to the same kid and check in again. Observe that the "med kit" allergy icon is correctly printed.

5. Now configure the same iPad kiosk device in Rock to do client printing.

6. Check in with the same kid, and you should observe that 1) Both the Allergy and Legal icons print (when they should not), and 2) Both icons are not the correct icon image. The default icon labels should print character A (medkit) and L (asterisk) respectively for Allergy and Legal, but instead they print as characters 7 (gear) and 8 (wrench). 

**Expected behavior:** 

Icon labels would print correctly when using the iPad app and client printing (this issue does NOT happen when using iPad app and *server* printing)

**Actual behavior:** 

When using iPad app on a kiosk set up for client printing, icons are incorrectly printed and they are the wrong icons, too. Weirdly, the characters 7 & 8 are what are embedded in the label itself for the Allergy and Legal fields and are associated with the Merge Fields 'Allergy Icon' and 'Legal Icon', and somehow THOSE characters are being printed instead of what is defined in the merge fields, which in this case are characters A and L.

Note this is also not an issue with the labels themselves, it's instead some weird interaction with the iPad app, client printing mode, and label merge fields. Our 100% custom labels (but using the same merge fields as the Rock labels) exhibit identical behavior. We have also heard from another Rock org that they do not see this behavior when using the Windows client and client printing. This is also not an issue of label caching in the iPad app, as it occurs when caching is disabled completely via Settings. Finally, this only seems to be an issue with these icons and not the Birthday or First Visit ones, perhaps because the Allergy and Legal ones are doing checks for !='' in the attribute while the other icons are not.

### Versions

* **Rock Version:** 6.1  
* **Client Culture Setting** en-US
![image](https://cloud.githubusercontent.com/assets/3903408/21870816/e962a692-d823-11e6-81e4-0dddc664eb46.png)

**Comment by ccofnow** [comment]
Based on discussion in Slack, we think we may be seeing 4 identifiable issues, ONLY when using the iPad app and client printing:
- Black boxes on text labels (sometimes inverted fields, sometimes not)
- Some icons always printing on icon labels even when they shouldn't (unidentified pattern to date)
- Icons printing the field titles instead of the intended lava string (sometimes blank, sometimes not)
- Labels for family checkin grouping by child instead of label type

Reference http://www.rockrms.com/page/278?question=1400 for some more details

**Comment by azturner** [comment]
Icons may print incorrectly when they shouldn't if there are spaces or line breaks in the label merge field. Wrong icon will print if a line in the label content does not match the regex that is being used to replace the key with the value (needs to match `^FT*^FD[code]^FS` where `*` is any characters and `[code]` is the code
