### ISSUE TITLE
My Connections Request Block Ignores Permissions

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1973]
### Description
If a user or role is given permission to edit the My Connections Request Block and opens the "All Requests" tab, they are only able to see connections assigned to them. The block will only show all connection requests to RSR - Rock Administration and RSR - Connection Administration, ignoring block settings.

### Steps to Reproduce
1. Add RSR - Staff Worker to have edit capabilities on the connections block (People > Connections)
1. Go to all requests tab as staff worker (Returns "There are no current connection requests.")

**Expected behavior:**

Show all connection requests the user has permission for through connection type detail permissions (http://rock.rocksolidchurchdemo.com/page/5354?ConnectionTypeId=1).

(From RSR - Rock Administration User)
![screenshot 2017-01-11 17 00 53](https://cloud.githubusercontent.com/assets/374209/21872818/8f8ad044-d81f-11e6-81bc-a4f288ff057b.png)

**Actual behavior:**

No requests are visible under all requests without being an administrator of the block.

![screenshot 2017-01-11 17 07 53](https://cloud.githubusercontent.com/assets/374209/21873006/851807a2-d820-11e6-91e7-f57e95732c92.png)

### Versions
* **Rock Version:** 5.1-6.2
* **Client Culture Setting** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1132572180385520">image.png</a>

**Comment by garrettjohnson** [comment]
@nairdo Do you think it would be appropriate to reclassify this as a bug? The security feature is visible on the Connection Type Detail, but adjusting permissions has no effect.
![screenshot 2017-06-01 11 55 23](https://cloud.githubusercontent.com/assets/374209/26695863/4c28bf58-46c1-11e7-97e1-aacb54bc7c8b.png)

**Comment by edmistj** [comment]
@garrettjohnson Nick is out for a bit. Sounds like this may be a bug. I'll remove the enhancement tag.

**Comment by kld3207** [comment]
I am having the exact opposite issue (access is not being restricted), but from the same cause of the security settings being ignored.  Is there a fix coming for this?

**Comment by jennifertroeger** [comment]
I am confirming the same behavior as @kld3207, where restrictive security permissions are ignored. We are on 8.7 but I also tested on pre-alpha by creating a new connection type and restricting permission of that type to Rock Administration. Then impersonate a staff role (Ted Decker) and he can still see, edit and manage the new connection.

**Comment by debbiethurston** [comment]
The rights are overwritten by the connector groups.  If a connection group
contains a person who does not have rights, Connections is allowing that
person to have access.  It took a while to see where it was overriding so
thought I would share since we found it.

**Comment by ethan-sparkdevnetwork** [comment]
The original issue described has been resolved. The scenario that Debbie describes is working as designed. There are multiple levels of security that can be assigned. Keep these things in mind:

1. If user has access to a connection Opportunity, but not the connection type the opportunity belongs to, the user will see the opportunity. i.e. denying access to a connection type will not deny access to all opportunities in that type if specific opportunities grant rights.
2. Order matters. If a user is affected by more than one security setting on a block the first one wins.
3. Edit permission also grants view permission but that will not show in security settings
4. Administrate does not grant view or edit permission. Granting admin access to the type will allow to view the type so it can be administered but any connections.
