### ISSUE TITLE
Make it harder to clone an entire Page Tree

### ISSUE THREAD

**Issue by bengoshow** [SparkDevNetwork/Rock#1974]
This isn't really a bug, more a request. From the Page Map view, the "Clone Page and Descendants" icon is right between the link to go to the page, and the gear icon to edit the Page Properties. It's easy to click accidentally, and there is no prompt to verify that you actually want to duplicate this page and all its descendants. Especially if that page tree contains system pages, it's very time-consuming to then traverse the entire tree to delete every child page. :(

I'd ask that a prompt is included to verify the duplication before it happens. Thanks!

**Comment by edmistj** [comment]
This has been fixed in v7.0.
