### ISSUE TITLE
Workflows triggered from Connection Request cannot set group

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1976]
### Prerequisites ###

* [x] Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
* [x] Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
* [x] Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

When attempting to set a group through either run lava or Set Attribute through entity nothing is set when the workflow is triggered through settings on the Connection Opportunity Detail.

For example: 

A workflow with a single group attribute, works when fired manually

![<a href="https://cloud.githubusercontent.com/assets/374209/21948185/542d1c0c-d99e-11e6-9f81-85f43b14231f.png">https://cloud.githubusercontent.com/assets/374209/21948185/542d1c0c-d99e-11e6-9f81-85f43b14231f.png</a> screenshot 2017-01-13 14 20 00]()

But fails to set any value when triggered from a workflow:

![<a href="https://cloud.githubusercontent.com/assets/374209/21948208/7bf9aff2-d99e-11e6-9074-92c0fb866dd4.png">https://cloud.githubusercontent.com/assets/374209/21948208/7bf9aff2-d99e-11e6-9074-92c0fb866dd4.png</a> screenshot 2017-01-13 14 41 56]()

Simplified testing code below. Replace 50 with any valid group Id.

```
{% group id:'50' -%}
{% assign GroupGuid = group | Property:'Guid' -%}
{% endgroup -%}
{{ GroupGuid }}
```

### Steps to Reproduce ###

1. Use workflow triggers set inside Connection Opportunity Detail.
1. [Use test methodology above]

**Expected behavior:**

The workflow sets the group regardless of what method is used to trigger the workflow.

**Actual behavior:**

No group is set when triggered. (Other entity values can be set) Also attempted to set group via entity, no error is triggered, but no value is set using `{{ Entity.ConnectionOpportunity.ConnectionOpportunityConnectorGroups | First | Property:'Guid' }}`)

### Versions ###

* **Rock Version:** 5.1-6.1 
* **Client Culture Setting** en-US

**Comment by TheArkChurch** [comment]
Using the parameter securityenabled:'false' resolves this issue and is now common practice. Closing issue.
