### ISSUE TITLE
[EN] Workflow Attributes are orphaned when workflow is deleted

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1979]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

I'm not sure if this is a bug, an architectural defect, or Working As Designed, but we've discovered that Workflow Attributes don't seem to be deleted when a Workflow is deleted (at least when those attributes are files), and instead "hang around" (orphaned) and we are concerned that over time the db (or file system) will be bloated with many attributes no longer used but are still taking up space. 

### Steps to Reproduce

1. Create a new File Type with File System storage type.
2. Create a simple workflow with a File attribute (of your new file type) along with a User Entry Form that exposes this attribute
3. Run the workflow and upload a file to the WF attribute. Observe that it is now sitting on the file system (~/App_Data/Files unless you changed that in the File Type)
4. Delete the workflow and observe that the file remains on the file system, thus "orphaned" from the workflow that created it and not referenced by anything else in Rock.

**Expected behavior:** 

Workflow attributes would be deleted when the WF that owns them is deleted. Person attributes do work correctly in this regard, but Workflow Attributes do not.

**Actual behavior:** 

Workflow attributes are orphaned. We have only tested this with WF attributes stored on the file system but assume it happens to db-stored attributes as well. Does some sort of cleanup job need to be created to search for such attributes and remove them when there are in this orphaned state? Or are we mis-interpreting what we're seeing?

### Versions

* **Rock Version:** 6.1
* **Client Culture Setting** en-US

**Comment by dcs619** [comment]
I think this is a known issue, see #1776.  The files are at least cleaned up but Attribute Values aren't.

**Comment by JimMichael** [comment]
Thanks David, sorry I missed that one in my search. Are you saying that (attribute) files ARE eventually cleaned up? I've had test attributes/files sitting out there 4+ days and they haven't gone away (yet.) What process would "eventually" clean them? I do like the idea in #1776 of a job that tries to join attributes to their entity and whack them if it can't.

**Comment by dcs619** [comment]
The RockCleanup job has [a section](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Jobs/RockCleanup.cs#L206) to delete cached or temporary files (and workflow files seem like they would be).

**Comment by JimMichael** [comment]
Makes sense, but I'm guessing they're not treated as cache/temporary as no amount of manually running the cleanup job deletes the file attributes for me... unless there's some sort of loooong time horizon before cleanup built into the job for these types of attributes.
