### ISSUE TITLE
I cannot get the statement generator to run with out a error? we have about 300 giving units and need to pull the statements from 7/1/16 to 12/31/16  gives me a connection error.  Help please. 

### ISSUE THREAD

**Issue by kaHoffmann** [SparkDevNetwork/Rock#1981]
### PLEASE READ

If the nature of your issue relates to the security of Rock, please do not post it here in the public issues.

### Prerequisites

* [ ] Can you reproduce the problem on a fresh install or the [demo site]  I am not sure how to get to demo site.
(http://rock.rocksolidchurchdemo.com/)?
* [ ] Did you include your Rock version number and [client culture]  running latest rev. 
(https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [ ] Did you [perform a cursory search](https://github.com/issues?  tried to. q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

[Description of the bug or feature. Include screenshots if applicable.] 
![image](https://cloud.githubusercontent.com/assets/16584306/22085993/e2ce0b3a-dd93-11e6-9809-e86c5f1f64d2.png)

### Steps to Reproduce

1. I have uninstalled and reinstalled
2. I can run single reports just not all of them at once
3. [and so on...]

**Expected behavior:** 

[What you expected to happen]  to run the report

**Actual behavior:** 

[What actually happened]

### Versions

* **Rock Version:** [Enter Rock version here]  
* **Client Culture Setting** [Enter Client Culture here]

**Comment by garrettjohnson** [comment]
@kaHoffmann Sorry for the slow response! Generally issues on github relate to developers and their interaction with Rock.  The Rock community can probably best help you with troubleshooting on [Slack](http://www.rockrms.com/slack) or on http://www.rockrms.com/Rock/Ask

I'd experiment with adding a data view to limit what is returned. If you're on a slow internet connection and your server is remote, it might be worthwhile to run the app from the server.
