### ISSUE TITLE
Cannot add new Package on rockrms.com site

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#1982]
### Prerequisites

* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Cannot add a new plug-in/package to the rockrms.com site. When you expand the Primary Category or Secondary Category drop downs you can an 'Error Unauthorized' message and cannot select a category.

### Steps to Reproduce

1. Open the 'New Package' page to begin adding a new package.
2. Click the 'Primary Category' drop down.
3. Enjoy the error

**Expected behavior:** 

I should be able to add packages to the store :)

**Actual behavior:** 

Error is presented saying I am not authorized to view the category list.

**Comment by azturner** [comment]
This has been fixed.
