### ISSUE TITLE
Deceased individuals can become eRA

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1985]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Deceased adults can attain eRA status because of the giving of their spouse or attendance of children. Following the recommendation of removing deceased individuals from their family can prevent the behavior.

It would still probably be a good idea to modify the eRA calculation to remove the ability for deceased individuals to gain eRA status. 

### Steps to Reproduce

1. Create a couple with a deceased spouse
2. Have the living spouse become an eRA
3. The deceased spouse also gains eRA

**Expected behavior:** 

No eRA is gained for deceased individuals. Perhaps it would be worthwhile to immediately wipe the values.

**Actual behavior:** 

Deceased can become eRAs

### Versions

* **Rock Version:** 6.1
* **Client Culture Setting** en-US

**Comment by nairdo** [comment]
We're also thinking we are going to exclude anyone who's been given an **inactive** status.  Then eRA will only be possible for _non_-inactive people.  This gives control to the admin to 'fix bad data' (if someone is inactive but shouldn't be) but it also means eRA cannot detect the bad data situation.

**Comment by garrettjohnson** [comment]
@nairdo I think the inactive status eRA assignment raises some interesting questions. If an inactive family becomes an eRA, it makes sense to re-activate them. (We're using dataviews to do just that) On the flip side, if you had a inactive spouse, that was deactivated because staff knew they did not attend, it would make sense to not give them eRA.

In the case of the inactive spouse, would it make sense for Rock to ship with a workflow trigger or job that reactivates someone upon attending?

**Comment by nairdo** [comment]
I don't see how that would be possible because, for example, if a husband stops attending and is marked inactive by staff while the wife continues to attend and give - the eRA (aka _Family_ Analytics) logic treats everyone in the family equally.  So, it shouldn't change a person's eRA values or Connect Status if one of the member's has been previously marked inactive.

At least this approach gives staff control of a person's status vs fighting automation that thinks it knows better.

**Comment by edmistj** [comment]
Just thinking out loud here. It seems pretty common that an active family could have an inactive member (the husband who doesn't attend). Wonder if it would make sense to add a new Inactive reason of 'Inactive Family Member'. 

The eRA could auto activate people unless they were Deceased or 'Inactive Family Member'. This would all need to go into the next full release.

Thoughts?

**Comment by garrettjohnson** [comment]
@edmistj That's a really interesting idea, I think it could work really well. The only thing I can think of would be to remove the "Inactive Family Member" from the list of options when someone self-inactivates.

**Comment by edmistj** [comment]
Yes, that would be an awkward response to show. Good catch.

**Comment by nairdo** [comment]
I've fixed the initial request and will address the new requested features as a separate issue.
