### ISSUE TITLE
Login not created during Group Sync although Create Login During Sync has been enabled

### ISSUE THREAD

**Issue by gladsonj** [SparkDevNetwork/Rock#1986]
### PLEASE READ

If the nature of your issue relates to the security of Rock, please do not post it here in the public issues.

### Prerequisites

* [X] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
Login not created during Group Sync although Create Login During Sync has been enabled

### Steps to Reproduce
1. Created a Data View
2. Created a Group
3. Assigned the Data View to the Group Sync
4. Users filtered by the Data View has been added to the Group

**Expected behavior:** 
1. In Person's Security Tab, under User Account List, there should be a new Login.
2. In Admin Tools -> Security -> User Accounts, there should be a New User Accounts.

**Actual behavior:** 
1. In Person's Security Tab, under User Account List, there is No Logins found.
2. In Admin Tools -> Security -> User Accounts, there are no New User Accounts.

### Versions
* **Rock Version:** Rock McKinley 6.1  
* **Client Culture Setting** en-US
[RockDiagnostics-RD0003FF71983C.txt](https://github.com/SparkDevNetwork/Rock/files/722153/RockDiagnostics-RD0003FF71983C.txt)

**Comment by edmistj** [comment]
Looking through the code, I'm assuming that perhaps you don't have a welcome email configured. Could you confirm that? If no welcome email is selected then the new login will not be created. If we did create the account without sending an email it would have a password that no one knows.

Could you confirm that setting for me. Sounds like we should document that in the help tip of 'Create Login During Sync' to make it more obvious.

**Comment by gladsonj** [comment]
Absolutely!!! You are right, @edmistj 
Once I added Welcome Email, it started working.
Yes, you are right, Sounds like it should be documented in help.
