### ISSUE TITLE
Missing Giving Statement for Businesses

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1988]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The default Rock business page does not have the ability to access a giving statement for a business. When the Contribution Statement List Lava block is modified to link to a business, the resulting contribution statement is missing the business address.

### Steps to Reproduce

1. Go to a business from Finance > Businesses (Contributions are visible, but no statement)
2. Go to `ContributionStatementURL/?PersonGuid={{ AnyBusinessGuid }}&StatementYear=2017` (Address is blank)

**Expected behavior:** 

Contribution statements are accessible for businesses, and display proper address.

**Actual behavior:** 

No contribution statements are accessible by default, and included contribution statement leaves address blank for businesses.

### Versions

* **Rock Version:** 6.1
* **Client Culture Setting** en-US

**Comment by edmistj** [comment]
We'll add the contributions list block in v7. In the meantime everything will work if you pass the PersonGuid in the URL. Like:

{{ DetailPage }}?StatementYear={{ statementyear.Year }}&PersonGuid={{ PersonGuid }}

**Comment by garrettjohnson** [comment]
Sounds good, I've got it working for us with a lava patch that checks for a blank address. 

Without modification the current lava block leaves the address blank for businesses (See http://rock.rocksolidchurchdemo.com/page/5406?PersonGuid=860a6cea-858f-46c3-b765-7c67762a2033&StatementYear=2017)

**Comment by edmistj** [comment]
If you paste in your blank address patch I'll add it to the update.

**Comment by garrettjohnson** [comment]
There must be a more efficient way of selecting the business/person object, but this gets the job done.

```
<h4>
{{ Salutation }} <br />
{% if StreetAddress1 != '' %}
{{ StreetAddress1 }} <br />
{% if StreetAddress2 != '' %}
    {{ StreetAddress2 }} <br />
{% endif %}
{{ City }}, {{ State }} {{ PostalCode }}
{% else %}
{% assign businessid = TransactionDetails | First | Property:'Transaction','Object' | Property:'AuthorizedPersonAliasId' | PersonByAliasId %}
{{ businessid | Address:'Mailing','[[Street1]]' }}<br />
{{ businessid | Address:'Mailing','[[City]], [[State]] [[PostalCode]]' }}
{% endif %}
</h4>
```

**Comment by mikejed** [comment]
@edmistj will the forthcoming v7 block understand the "Known Relationship" that the business owner has with the business record? In other words, if they're logged in as themselves and we add the business contribution statement to a page, would they see the statements for (any) businesses they have that relationship with, in order to keep the pages secure to their login?

**Comment by edmistj** [comment]
@mikejed Yes that will be in v7.

**Comment by edmistj** [comment]
I believe this is complete.
