### ISSUE TITLE
Person column empty in excel export of Communication Detail open/delivered/etc export

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#1989]
### Prerequisites

* [] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? - NOT POSSIBLE ON DEMO SITE.
* [ x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [x ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When you export from the Communication Detail block to see who has opened a communications, the Person column is blank:

![image](https://cloud.githubusercontent.com/assets/383807/22341971/1980d9a6-e3b0-11e6-9257-4bfbdf5dd5c3.png)

### Steps to Reproduce

1. Send communication
2. View communication detail
3. Click export

**Expected behavior:** 

Expected to see names of people in the column.

**Actual behavior:** 

Person column was empty.

### Versions

* **Rock Version:** v6-v7

**Comment by chrismcgrath** [comment]
Don't know how to fix this, but the issue is that the BoundField is a Person but the PropertyInfo says it's a CommunicationRecipientId, which is why that ID is being added to the right of the results.
