### ISSUE TITLE
Google Maps requires Key parameter for Static Maps

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#1991]
### Prerequisites

* [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? **NO**
* [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Google Maps seems to now require a **&key=API_KEY** when using static maps. Some people have not run into issues, some of us have. I am assuming they are grandfathering in people so that their sites do not break if they generate a small amount of traffic.

Copying the current URL of a broken image (for example on the Group Details page) and pasting it into a new window produces a valid image. This seems to be related to Google tracking the Referer header and allowing the keyless request to work if it does not have a Referer header (guessing).

Appending the **&key=API_KEY** to the URL generated by Rock instantly makes it work correctly.

The fix seems to be to append the **Google API Key** Global Attribute value to the <img> tag URLs. A search of the repository turns up these locations it needs to be done.

### Places To Be Fixed

These locations generate an <img> tag directly:

* Blocks/Core/LocationDetail.ascx.cs
* Themes/Flat/Assets/Lava/GroupDetail.lava
* Themes/Rock/Assets/Lava/GroupDetail.lava
* Themes/Stark/Assets/Lava/GroupDetail.lava

These locations use the **Map Style** Defined Type and would need to in code append **&key=** Google API Key Global Attribute:

* ~~Blocks/Core/DeviceDetail.ascx.cs~~ (I believe this only uses the style for the picker and not a static map)
* Blocks/Core/LocationDetail.ascx.cs
* ~~Blocks/Examples/RockControlGallery.ascx.cs~~ (I believe this only uses the style for the picker and not a static map)
* Blocks/Groups/GroupDetail.ascx.cs

### Workaround

There is currently a workaround for both the Group Leader Toolbox and the Group Detail staff page.

The Toolbox you must edit the GroupDetail.lava file for your theme and add in the **&key=API_KEY** to the <img> tag.

For the Group Detail staff page, there is a defined type of **Map Styles** that defines the URLs and formatting to use for various map types in Rock. You can edit the Value of the one being used (or all to make sure you don't miss anything) and append **&key=API_KEY** to the URLs.

### Versions

* **Rock Version:** 5.4
* **Client Culture Setting** en-US

**Comment by cabal95** [comment]
Chris Rea reported the same symptoms on Rock 6.1

**Comment by gladsonj** [comment]
Even, I have the same issue on Rock 6.1

**Comment by ffunky** [comment]
Same - 6.1

**Comment by gladsonj** [comment]
Will this be fixed in any release?

**Comment by edmistj** [comment]
Yes, planned for 6.3. Didn't make it in time for v6.2 testing.

**Comment by nairdo** [comment]
@cabal95 I wonder if it might require more than just appending the key.  It seems as though the entire Google Static Maps API v1 has been deprecated: https://developers.google.com/maps/documentation/static-maps/upgrade

> The Google Static Maps API v1 API deprecation period has ended. If you are a developer that already has a website using the Google Static Maps API version 1, these upgrade tips should help you port your current site's functionality to the Google Static Maps API version 2.

And if you're a "premium plan" user you also have to _digitally sign_ the requests.:

> > Important: Google Maps APIs Premium Plan customers will have to sign their requests. Information on how to sign your request is available in the Google Maps APIs Premium Plan documentation.

https://developers.google.com/maps/documentation/static-maps/get-api-key#digital-signature

> Note: If you have enabled pay-as-you-go billing, the digital signature is required. 

To make matters worse, as soon as you try generating a URL signature "24 hours after you do so, URLs with just an API key will stop working."  So I'll need to sign up with one of my test systems to be the guinea pig.

**Comment by andrewkmetz** [comment]
Looks like my rock site is suffering from this same problem... v6.9 & Google API Global attribute set. No map image for groups detail.

**Comment by cabal95** [comment]
@andrewkmetz Some of these are generated by Lava files in your theme. If you are using a custom theme you might need to manually update the Lava files to include the fix (or copy the stock ones over).
