### ISSUE TITLE
PayFlowPro CheckTender

### ISSUE THREAD

**Issue by aaronjones8** [SparkDevNetwork/Rock#1997]
### PLEASE READ

PayFlow processing ACH transactions is failing due to invalid tender type. Is passing A for ACH and the client needs it to pass K for CheckTender

### Prerequisites

* [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [ Yes] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [Yes ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

[Description of the bug or feature. Include screenshots if applicable.]

### Steps to Reproduce

1. Attempt to process an ACH transaction using PayFlow Payment Gateway
2. Receive error that not signed up for this tender type

**Expected behavior:** 

ACH transaction to process

**Actual behavior:** 

The transaction fails due to provider looking for CheckTender instead of ACHTender

### Versions

* **Rock Version:** 6.1  
* **Client Culture Setting** Client Culture Setting: en-US

**Comment by JimMichael** [comment]
I would add that in chatting with Aaron, we seem to have different ACH processors. In our case it's Norwest, and we have none of the issues he describes with Payflow (and have had this working for 5+ years prior to Rock). His processor for ACH is instead "Telecheck" and Payflow is apparently saying that for this, the tender type is being set incorrectly.

**Comment by aaronjones8** [comment]
[2-9-2017 - 2-15-2017 - Standard-- (3).pdf](https://github.com/SparkDevNetwork/Rock/files/740789/2-9-2017.-.2-15-2017.-.Standard--.3.pdf)

Here is a snippet from the developer documentation from PayFlow that I was referred to

**Comment by aaronjones8** [comment]
<img width="1413" alt="screen shot 2017-01-30 at 6 54 22 pm" src="https://cloud.githubusercontent.com/assets/13666106/22446987/b48e363a-e71d-11e6-86b7-299f5a5c6bb0.png">

Here is a snippet from the developer documentation from PayFlow that I was referred to

**Comment by edmistj** [comment]
@azturner thoughts on this?

**Comment by aaronjones8** [comment]
Has there been any update on this? When I last talked to David Turner when I submitted this request he mentioned that it would be in 6.3. The staff and the church our company works with were going through the release notes for 6.4 and didn't see the fix and were asking about it.

**Comment by azturner** [comment]
@aaronjones8 sorry there hasn't been any update until now. I did look at this further, and this required more than just changing the tender type of an existing ACH transaction. It appears to be a completely different type of payment method and requires different field values. For example, a MICR value is required, and that's not something the Rock interface or code supports. 

See this doucmentation (page 91): https://www.paypalobjects.com/webstatic/en_US/developer/docs/pdf/pp_payflowpro_guide.pdf

**Comment by aaronjones8** [comment]
@azturner Thanks for your response. How should they go about setting up their Rock install for ACH transactions. From what they can tell it works fine with Norwest but Norwest is no longer accepting new clients.

**Comment by azturner** [comment]
@aaronjones8 I'm not familiar with all of the ACH processors that work with PayFlowPro, but I would think that PayPal can help them find an ACH processor. Their other option would be to use NMI and Transnational for their ACH processing.

**Comment by aaronjones8** [comment]
Thank you
