### ISSUE TITLE
Communication Still Sends Even When Backdated

### ISSUE THREAD

**Issue by nathanp** [SparkDevNetwork/Rock#1999]
### Description

When scheduling a communication, if a user accidentally selects a previous date instead of a future date, the communication immediately sends. It would be helpful instead if the communication did not send and there was some type of notification to the user to please select a future date/time in order to properly schedule the message.

* **Rock Version:** [6.1]

**Comment by JimMichael** [comment]
I would also add a similar issue... if you leave the date blank and just enter a future *time*, it sends immediately. Since the UI doesn't force you to enter a date, it's possible someone assumes just entering a *time* (with no date) means "today", which is not the case.
