### ISSUE TITLE
Cropping image on /MyAccount causes exception

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2001]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Uploading an image and then attempting to crop it on the /MyAccount page causes an exception. Cropping an existing image causes the same exception. Also, deleting an existing image does not work and the existing image remains.

### Steps to Reproduce

1. Log in to the /MyAccount page on Rock external site
2. Click Update
3. Click the edit pencil on the photo to edit an existing photo or upload one if none exists.
4. Click the Crop button
5. The crop does not happen and an exception is thrown

**Expected behavior:** 

Cropping would work like it does in Rock versions < 6.0

**Actual behavior:** 

Crop causes an exception in v6, 6.1 and 6.2 beta. Was UNABLE to reproduce on demo site, which is at 5.3, but got confirmation from one other that their v6.x site fails in the same way as ours. The exception thrown is 
![image](https://cloud.githubusercontent.com/assets/3903408/22522466/43a0a6d2-e881-11e6-9f5b-4f888edea14d.png)

![image](https://cloud.githubusercontent.com/assets/3903408/22522402/14515e80-e881-11e6-910b-2e0132c5330b.png)

### Versions

* **Rock Version:** 6.0, 6.1, 6.2beta
* **Client Culture Setting** en-US

**Comment by cabal95** [comment]
Currently on 6.2, including on the rock demo site, trying to crop a photo on the public site causing an exception every single time. Tested on Firefox 51.0.1 on Windows 10.

**Comment by NuclearTacos** [comment]
Currently on 6.1 also consistently causes an exception in Chrome on Android
