### ISSUE TITLE
Group Finder displays no results if Show Distance = off and Sort By Distance = on

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2007]
### Prerequisites

* [X] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Group Finder shows no results if you turn on `Sort by Distance` and turn off `Show Distance`.

### Steps to Reproduce

1. Turn off `Show Distance`
2. Turn on `Sort by Distance`

**Expected behavior:** 

Results should be sorted by distance (if an address has been given, if not ignored) but distance should not be displayed. This would be my expected results. At the very least it should throw an "misconfigured" error to alert the Admin that it is not configured correctly.

**Actual behavior:** 

Empty result set is returned, even though no filters have been applied.

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting** en-US

**Comment by JimMichael** [comment]
Confirmed on demo site

**Comment by chrismcgrath** [comment]
Seems to work fine if "Map" is not checked.
