### ISSUE TITLE
GoDaddy should be removed from all documentation and install procedures

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2021]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

GoDaddy on the virtual private servers limits your MS SQL databases to 200MB, even on the Unlimited plan (you get unlimited number of databases, but each database is limited to 200MB). The details can be seen here: https://www.godaddy.com/help/which-components-does-my-hosting-support-5614 as well as this recent Q&A where somebody ran into the problem during install: https://www.rockrms.com/page/278?Question=1488

There are a few pages on rockrms.com that mention GoDaddy so each of them should probably be updated to either remove GoDaddy completely or specifically mention the 200MB limit. I would vote for the former and possibly even a stern recommendation against using it since they do not list this limitation anywhere on their server details page when you are buying a VPS. It is only in the KB articles that you can find this.

**Comment by JimMichael** [comment]
I agree GoDaddy is probably not a great Rock host, but be aware they also sell a "dedicated server" where you get your own Win server and can install SQL express or full SQL server.  So any instructions to not use it need to be specific to VPS.

**Comment by edmistj** [comment]
Are there any specific pages we should look at. Looking at Google I only see some old versions of documents and Q&A questions.

**Comment by cabal95** [comment]
Hmm. It would seem the "Planning for Rock" page I was finding was an older version, though no indication that it is older shows. Maybe a better request is a way to banner the top of those pages to indicate that it is not the latest version?  If I wanted to find out if Rock worked with GoDaddy I would search "rockrms godaddy" and the first hit is to that older document which says that it has been tested and works on GoDaddy.

**Comment by Tschrock** [comment]
There are many times when I've googled something only to be directed to v1 docs, etc. A banner or something indicating outdated documentation would be great.

**Comment by edmistj** [comment]
Added warning message when viewing older versions of the books.
![chrome_2017-03-24_16-13-16](https://cloud.githubusercontent.com/assets/548178/24316641/eaa8885c-10ac-11e7-9678-4d7c8781c573.png)
