### ISSUE TITLE
Content Channel Item Attributes Missing If Defined on the Content Channel

### ISSUE THREAD

**Issue by edmistj** [SparkDevNetwork/Rock#2028]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When attempting to write a data view for a content channel you can only select attributes defined on the channel type. Attributes on the channel are not listed.

### Steps to Reproduce

Create dataview on a content channel item.

**Expected behavior:** 

I should be able to see/select attributes defined on the content channel.

**Actual behavior:** 

Attributes defined on the content channel are not listed

### Versions

* **Rock Version:** 1.6.x
* **Client Culture Setting** d

**Comment by azturner** [comment]
Fixed here: https://github.com/SparkDevNetwork/Rock/commit/73bdddc7ad823bf0e581d915c21245cd2959dc6d
