### ISSUE TITLE
Emergency numbers can cause sms replies to bounce/loop back

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#2036]
### Description

If Bob has Tom's cell number as their emergency contact, and Tom has a rock number, any replies that Tom makes to that number "bounce" back to him as though Bob had sent him a message.

It seems that when trying to match the sender of a message, Rock is matching on people's emergency numbers. If the person with the emergency number has a smaller personId, they will get matched instead of the person with the actual cell number.

### Steps to Reproduce

1. Give Person 1 the phone number of Person 2 as an emergency number.
2. Have Person 2 send an sms communication from rock to Person 3.
3. Person 3 gets the message on their device and responds.
4. Person 2 gets the response on their device and responds to Person 3 using their @ code

**Expected behavior:** 

Person 3 gets Person 2's response

**Actual behavior:** 

Person 2 gets a message as though Person 1 sent a message to Person 2's rock number.

### Versions

* **Rock Version:** 6.1
* **Client Culture Setting** en-US

**Comment by edmistj** [comment]
Hey Tyler! What do you mean by 'emergency number'? Is that a custom phone type?

**Comment by cabal95** [comment]
We had a brief discussion in the random channel. This could be a custom/imported phone type as we couldn't find it on other systems, but it was a phone type he was talking about.  I'm not sure where the code is that handles matching incoming SMS numbers to check myself, but if this code does not already validate against the SMS flag then doing so should resolve his issue as he could just make sure the SMS flag is not set on the Emergency Numbers.

**Comment by Tschrock** [comment]
Sorry, It looks like it came over in our original import, which is why it looked like it was built-in.

@cabal95 It's my understanding that the SMS flag is more of a communication preference (*should* this number get sms, instead of *can* this number get sms), since you can only set one number with it.

In light of that, I am thinking of moving it into a person attribute, so it doesn't get interpreted as being the person's own number.

**Comment by edmistj** [comment]
@Tschrock I think storing the emergency contact as a person attribute is the way to go. Does that mean this can be closed?
