### ISSUE TITLE
Person Profile Security tab (GroupList block) shows member-inactive security roles

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2041]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

On the Person Profile screen under the `Security` tab, the default out-of-the-box configuration gives no indication that a person is `Inactive` in the list of security roles. A person who is a member of the `RSR - Rock Administration` role with a status of `Inactive` does not get those permissions but they still appear to have those permissions if you just look at the person's profile page. This is due to a combination of four items:

* User cannot filter manually (disabled in block settings)
* Block does not filter automatically (disabled in block settings)
* Block does not show Active column (disabled in block settings)
* Block does not show row grayed out like the Roles page does.

### Steps to Reproduce

1. Create new person on Rock demo site.
2. Create login for person.
3. Add person to the RSR - Rock Administration role as Inactive status.
4. View person's profile security page and notice they appear to be in the RSR - Rock Administration role.
5. Try to login as this new person.

**Expected behavior:** 

Role should either be not listed, Active column shown, or row grayed out if Inactive.

**Actual behavior:** 

I get very confused why this poor fool can't log in.

### Versions

* **Rock Version:** 6.2  
* **Client Culture Setting** en-US

**Comment by nairdo** [comment]
I'd say ghost out row like the GroupMemberList block does.
