### ISSUE TITLE
Discussion: Enhance Lava with new filters to activate workflows and activities

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2044]
# Overview

This is a discussion about adding two new filters to Rock to provide interaction with Workflows. The first new filters would allow for a new Workflow to be activated by it's WorkflowType Id number (or Guid). The second new filter would allow for a new Workflow Activity in an existing Workflow instance to be activated based on it's WorkflowActivityType Id, Guid or Name.

### Basic Syntax

Activates a new instance of the workflow type.
The workflow type identifier can be either it’s integer ID or it’s Guid ID. Example:

`{{ 24 | WorkflowActivate }}`

### Workflow Attributes

There are a couple ways we can potentially pass attribute values into the workflow.

~~Simple list of key/value pairs.{{ 24 | WorkflowActivate:'AttributeA','ValueA','AttributeB','ValueB' }}~~ This method cannot be used, Liquid filters do not support variable count arguments.

~~Condensed key/value pairs: `{{ 24 | WorkflowActivate:'AttributeA=ValueA','AttributeB=ValueB' }}`~~ This method cannot be used, Liquid filters do not support variable count arguments.

Option 1 would be all as one string: `{{ 24 | WorkflowActivate:'AttributeA=ValueA|AttributeB=ValueB'}}`

Second option would be to pass in an associative array (dictionary) object that has the key/value pairs defined (extra filters required, but kind of want to make them anyway):
```
{% assign attributes = '' | AddKeyValue:'AttributeA','ValueA' %}
{% assign attributes = attributes | AddKeyValue:'AttributeB','ValueB' %}
{{ 24 | WorkflowActivate:attributes }}
```

Third option, support both options one and two in code.

I prefer the second or third options. The first option means the we cannot pass in any values that contain a `|`.

### Return Value

If the workflow is persistent then the text returned by the filter is the Id number of the workflow instance.
Otherwise an empty string is returned.

```
{% assign workflowId = 24 | WorkflowActivate %}
{% if workflowId != '' %}
    Workflow Started with Id #{{ workflowId }}.
{% else %}
    Workflow failed to start.
{% endif %}
```

### Other Examples

```
{{ '24' | WorkflowActivate }}
{{ 'a3f17904-be2d-4dc9-a93b-0942869d39be' | WorkflowActivate }}
{% assign workflowId = 24 | WorkflowActivate %}

{% assign attributes = '' | AddKeyValue:'PersonId',personId %}
{% assign workflowId = 24 | WorkflowActivate:attributes %}

{% assign attributes = 'PersonId=' | Append:personId %}
{% assign workflowId = 24 | WorkflowActivate:personId %}
```

### Basic Syntax

Activates a new instance of the workflow activity type.
The Workflow instance Id is passed as the source value while the Activity Type Id is passed as the parameter.The Workflow Instance Id can be either it's Id or Guid.
The Workflow Activity Type can be either it’s integer ID, it’s Guid or it's name.
In the case of using the activity type name when there are multiple activities with the same name, the first match will be used.
Examples:

```
{{ 1234 | WorkflowActivityActivate:'Enter Resolution' }}
{{ 1234 | WorkflowActivityActivate:'35f094bc-814f-477f-923e-67fe2c2f1883' }}
```

### Activity Attributes

Attributes can optionally be passed to the activity the same way they can in the `WorkflowActivate` filter.
As such please see above discussion.
Attribute information will be passed as an optional second parameter to the filter. Example:

`{{ 1234 | WorkflowActivityActivate:'Enter Resolution','AttributeA=ValueA' }}`

**Comment by edmistj** [comment]
I like this concept! What if you used Lava commands instead of a filter. They would allow a variable number of inputs.

```{% workflow WorkflowTypeId:'12' AttributeKey1:'AttributeValue' AttributeKey2:'AttributeValue' ... %}```

The code would assume that everything other than `WorkflowTypeId` was an attribute. It would be cool if persisted the full workflow object was returned inside the block.

```
{% workflow WorkflowTypeId:'12' AttributeKey1:'AttributeValue' %}
       {{ Workflow.Id }} - {{ Workflow | Attribute:'SelectedGroup' }}
{% endworkflow %}
```
Be neat if the workflow was at a input action a merge field could be provided for the form to allow either linking to it or redirecting to it.

Perhaps another 'reserved parm' would be `WorkflowId` which could load a current workflow instance and hydrate the object for inspection. This could also merge in your other Filter concept...

```{% workflow WorkflowId:'1232' ActivityTypeId:'12' <activity attribute/value list> %}```

Thoughts???

**Comment by cabal95** [comment]
I like it. We had discussed wether to do a Filter or Command but were not sure which was better. Would the command of "workflow" conflict with the entity command of `{% workflow where:'Id == 43' %}`?

I do like the idea of the command especially if it allows variable number of arguments. And seeing how you used it to pass the persisted workflow object into the body makes me want this even more. :) I would think reserve the following parameter words:
* WorkflowTypeId (int/guid)
* WorkflowId (int/guid)
  * ActivityTypeId (int/guid)
  * ActivityTypeName (name)

Or possibly simplified (not sure how I feel about this in terms of consistency with other things in Rock)

* WorkflowType (int/guid)
* WorkflowId (int/guid)
  * ActivityType (int/guid/name)

I assume doing this by command would still allow something like the following if we needed to capture the workflow Id for use later, but wanted it outside the block:
```
{% capture workflowId %}
    {% workflow WorkflowTypeId:'42' %}
    {% endworkflow %}
{% endcapture %}

{{ workflowId }}
```

**Comment by edmistj** [comment]
You're right we would have a clash with `workflow` something like `workflowlaunch` or `workflowactivate` might be better. Your simplified notation would be better if you wanted to support both id/guid (which would be nice). 

The capture might be something like:
```
{% capture workflowId %}
    {% workflow WorkflowTypeId:'42' %}
        {{ Workflow.Id }}
    {% endworkflow %}
{% endcapture %}

{{ workflowId }}
```

**Comment by cabal95** [comment]
Err, good catch on the `capture`. Totally forgot to put in the `{{ Workflow.Id }}` when I was typing that up. :)

I like the idea of supporting, at the very least, Id and Guid both. There are times with various things I want to use the Guid (because thats what I have in a variable) and times I want to use just the Id (because thats what I have by looking at the URL).  Supporting name for the activity I think is important because there is no way to get the activity type Id or Guid without looking at the database (as far as I know).

I really want to try creating an entity called `if` and see what happens to Lava :)

**Comment by edmistj** [comment]
Supporting `ActivityName` is fine, I just worry that if people change the name it could have unintended consequences. We can add the Activity Id to the blocks in a small subtle way also. We've done that other places like DefinedValues and Pages.

**Comment by cabal95** [comment]
@edmistj I think if we add the Activity (Type) Id to the blocks that would be great. I personally like the idea of using the name of the activity for self-documentation but you are right there could be unintended consequences. It is probably better that it fails than activates the wrong activity.

Some final syntax for anybody to comment on and I'll start working on implementation. Activate a new workflow syntax samples:
```
{% workflowactivate WorkflowType:'1232' %}
{% endworkflowactivate %}
-or-
{% workflowactivate WorkflowType:'a3f17904-be2d-4dc9-a93b-0942869d39be' MyAttribute:'abc' %}
{% endworkflowactivate %}
```

Activate a new activity in an existing workflow:
```
{% workflowactivate WorkflowId:'41' ActivityType:'7283' MyAttribute:'abc' %}
{% endworkflowactivate %}
-or-
{% workflowactivate WorkflowId:'41' ActivityType:'35f094bc-814f-477f-923e-67fe2c2f1883' %}
{% endworkflowactivate %}
```

Unless I run into something that would prevent it, the "activate workflow" action would produce a `Workflow` variable either null or the persisted Workflow. The "activate action" action would produce both a `Workflow` variable and a `Activity` variable (or null if not persisted). I _think_ I will have access to the Activity instance in the C# code, just not 100% positive yet.

**Comment by edmistj** [comment]
@cabal95 I like it. You should have access to all the items in you need in C#. There's sample code around that does this. 

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Workflow/Action/WorkflowControl/ActivateWorkflow.cs

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Workflow/Action/WorkflowControl/ActivateActivity.cs

**Comment by cabal95** [comment]
@edmistj Working on the code for this now. I notice in the ActivateActivity action that it (the workflow0 does not process right away so it won't necessarily process until the next time the job runs. Is it safe to call workflow.Process() on the owning workflow, or is there no code to detect a workflow being processed in two places at once?

**Comment by edmistj** [comment]
@cabal95 Yes, you should call workflow.Process() .

**Comment by cabal95** [comment]
Okay. This is working except for one problem. During an activate activity command, if you activate an activity in the workflow that is already running it causes an infinite recursion. Is there any way to detect if a given Workflow is currently being Process()'ed and only call workflow.Process() if it isn't already in the middle of being processed?

**Comment by edmistj** [comment]
There is an .IsProcessing property on the workflow to determine if it's currently processing.

**Comment by cabal95** [comment]
👍 I had seen that property but didn't notice until just after posting that it was a DataMember (existed in database) property. That should work, though I just tested and it doesn't get set correctly when calling the `Workflow Persist` action so I will have to patch that too but that should work.

**Comment by cabal95** [comment]
Okay sorry for all the questions - and thanks for all the feedback.  Everything seems to be working except for the following case:

* If you try to activate an activity in a workflow that is currently being processed, the activity will (probably) never be activated. This happens because the in-memory Workflow object that is being processed runs until it has no more activities and then marks the workflow as completed. Since the changes only exist in the database and not in-memory it doesn't know about the new activity and thus marks itself as complete. For the moment I have caused an error to occur if trying to activate an activity in a workflow that is `IsProcessing`.

Seeing this is easy by having the Lava try to activate a new activity in it's own Workflow (for example, say I want to loop through a bunch of personIds and trigger an activity for each of those personIds to do some work).

This seems to be a deeper issue because I believe the existing "Activate Activity in Another Workflow" has this issue too. I think it is just far more unlikely to run into that problem because, in general, I believe workflows only process single threaded. i.e. the Job runner is only single threaded (afaik).

I may submit this as is and then look at a second Issue/PR to discuss how to solve this correctly. I can think of a few ways but not sure which is best without further thought. At the same time this code can be modified to re-enable activating an activity in a currently processing Workflow. The only major time this would be an issue is the example I mentioned above, where I want to use Lava to activate an activity in the currently running workflow.

**Comment by edmistj** [comment]
@azturner thoughts on Daniel's last comment.

**Comment by cabal95** [comment]
@edmistj Thoughts on submitting a PR for the current functionality?  i.e. display an error if you try to activate an activity in the currently executing workflow (until the deeper issues are resolved).

I'm fine leaving this open / pending too until we can find a solution for that issue, just didn't want this to sit so long that I forget what the code was doing.

**Comment by edmistj** [comment]
@cabal95 sorry for the delay. Yes, I think you're good to submit as is.  Looking forward to this functionality. Might be nice to have a new job type that runs lava (like the current SQL one). Before that would not have made much sense, but with this new command it could make a very powerful way of running workflows on a specific set of records.

**Comment by cabal95** [comment]
Submitted pull request.

**Comment by azturner** [comment]
I added an issue for what you mentioned about activity not getting processed if added to a currently running workflow: #2198
