### ISSUE TITLE
General SummerNote issue collection

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2045]
### Description

This is meant to be a general place to collect issues about Summer Note so that we have a central list to discuss items and provide the core developers with the issues our end-users have run into. The final purpose of this will be to improve the functionality so that our end-users are happy with the product. Discussions should ideally be had on Slack so that we don't fill up the log and then a summary should be posted to this issue as a comment.

Myself or an admin can keep this main body text up to date with the summarized list of issues noted in the comments. Confirmed issues are those that have been confirmed by more than one site. Please try to provide as many details as you can, including browser and operating system.

### Reported Issues

* When pasting text from Safari on Mac the text appears without line breaks.
* When inserting image from Firefox on PC the img tag includes a style width of 25% which cannot be edited except by going into code editor mode.

### Confirmed Issues

* When pasting text from Firefox the text appears at the top of the content box, disregarding the insertion point of the text cursor. (Firefox on Win 10, possibly other combinations)

**Comment by Tschrock** [comment]
Did some testing:

| OS         | Coppied From | Pasted Into                | Method | Correct Location? | Correct Formatting? |
| ---------- | ------------ | -------------------------- | ------ | ----------------- | ------------------- |
| Windows 10 | Word 2016    | Chrome (57.0.2987.74 Beta) | Direct | Yes               | Yes                 |
| Windows 10 | Word 2016    | Firefox (51.0.1)           | Direct | No, inserted at top | No, inserted in reverse paragraph order |
| Windows 10 | Word 2016    | Chrome (57.0.2987.74 Beta) | "From Word" Button | Yes | Yes |
| Windows 10 | Word 2016    | Firefox (51.0.1)           | "From Word" Button | Yes | Yes |
| Windows 10 | Word 2016    | Chrome (57.0.2987.74 Beta) | "From Text" Button | Yes | No, Inserts all paragraphs as a single paragraph with spaces |
| Windows 10 | Word 2016    | Firefox (51.0.1)           | "From Text" Button | Yes | No, Inserts all paragraphs as a single paragraph with spaces |
| Windows 10 | Notepad      | Chrome (57.0.2987.74 Beta) | Direct | Yes | No, Inserts all paragraphs as a single paragraph with spaces |
| Windows 10 | Notepad      | Firefox (51.0.1)           | Direct | No, inserted at top | No, Inserts all paragraphs as a single paragraph with spaces |
| Windows 10 | Notepad      | Chrome (57.0.2987.74 Beta) | "From Word" Button | Yes | No, Inserts an extra empty paragraph between each pasted paragraph |
| Windows 10 | Notepad      | Firefox (51.0.1)           | "From Word" Button | Yes | Yes |
| Windows 10 | Notepad      | Chrome (57.0.2987.74 Beta) | "From Text" Button | Yes | No, Inserts all paragraphs as a single paragraph without spaces |
| Windows 10 | Notepad      | Firefox (51.0.1)           | "From Text" Button | Yes | No, Inserts all paragraphs as a single paragraph without spaces |

**Comment by mikejed** [comment]
One of our front desk workers direct pasted a prayer request message from Word into a communication (Windows 10, Google Chrome) in Rock. She sent a test of the communication (because sometimes in this configuration the sentences get scrambled), and it came through correctly. So then she scheduled the communication and saved it. When it sent out on schedule, (some) paragraphs were scrambled. She says she thinks it's the first time that's happened AFTER sending a test.

This shows what came through on the text (above) and what was actually sent to everyone else as scheduled (below)

Oddly the grid above indicates that this scenario has been found to work correctly - which tracks with my inability to reproduce the error whenever it's come up in the past.
![summernotescrambling](https://cloud.githubusercontent.com/assets/6932047/24374232/f414a9a0-12e8-11e7-9d72-609795204e9d.png)

**Comment by jeremyhoff** [comment]
The WYSIWYG editor doesn't allow end users to make images clickable with a URL.  HTML coding strictly required. :-(

**Comment by MikeDPeterson** [comment]
@jeremyhoff,  the image url feature is now available with https://github.com/SparkDevNetwork/Rock/commit/ae7b8f258b95ce06d329f98dcb2775c36c761f94

**Comment by edmistj** [comment]
Mike has addressed many of these and the updates should be on the prealpha.rockrms.com site. Could you please check that and let us know what still needs attention?

**Comment by cabal95** [comment]
It's much better for sure.  Couple results (all tests conducted on a Mac, Safari = 11.0 High Sierra, FireFox = 49.0.2):

## Paste from Text Edit

Original text:
```
This is a test
Of another line

And a final line.
```

In Safari 11.0 results in (extra lines after paragraphs):
```
This is a test
Of another line


And a final line.

```

FireFox pastes correctly.

## Paste from Safari copy

Original text comes from selecting and copying the original details in this issue post.

Both Safari and FireFox behave the same. The text generally pastes correctly (H3 tags, bullets, etc. all show up). There are some new-line issues, but they are minor. A few examples:

* Extra blank line before the `Description` header
* No blank line between the two paragraphs of the `Description` content
* Extra line blank before and after `Reported Issues` header.

## Paste from Word

Source text:
```
This is a test
Of another line

And a final line.
```

Both Safari and FireFox result in (extra line feed at end, no big deal):
```
This is a test
Of another line

And a final line.

```

Overall I would say all the mods @MikeDPeterson has made have been a **huge** improvement, so thumbs up to all the work he has done!!!  The remaining issues I feel are minor.

**Comment by cabal95** [comment]
I'm going to close this issue in favor of starting a new thread if anybody continues to have problems. I think Mike nailed down most of the problems, if not all of them.
