### ISSUE TITLE
[EN] Workflow Attributes in Single/Multi-Select Attributes

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2049]
### Description
I think that making Single/Multi-Select Attributes able to reach Workflow Attributes would be highly beneficial to making some high-level Workflows.

I tried to make a Group Picker that would filter Groups by their Attributes in regards to the options selected in the Workflow, but then realized the Lava couldn't reach those Attributes.

### Proposed Enhancement
I am proposing that some access to Workflow-Level Attributes be made available in some way.

For my specific case, having the attributes being pre-pended to the query as their RawValue in a parameter when the attribute is being rendered should do the trick.  But otherwise, the obvious option, but possibly more difficult (?) way, would be making all Lava (in line with global restrictions) being able to run.

### Proposed Allowances
I think it's more than acceptable to require SQL to be written in a fault-tolerant manner such that it doesn't error when being rendered regardless of the expected parameters or Attribute values.

**Comment by edmistj** [comment]
@NuclearTacos Instead of using Single/Multi-Select Attributes you might use defined value(s). This allows the values to be accessible in several places. Would that solve your need (not sure I fully understand it).

**Comment by NuclearTacos** [comment]
Don't worry, at the end I'm including what I put in the Single-Select to help clear this up.

@edmistj I understand what you're saying, but it's not exactly what I'm requesting.  Like you recommended, I'm using defined values to bring over the same values to what they filled out on their form,
![workflow entry _ rock rms - google chrome 2017-03-24 10 16 33](https://cloud.githubusercontent.com/assets/19762670/24300858/d528d224-107b-11e7-9caf-b98aaefd48f5.png)

But when I try to filter the list of groups by their set interests (referencing the Workflow Attributes in the Single-Select, they're evaluated as blank strings.
![workflow entry _ rock rms - google chrome 2017-03-24 10 18 00 2017-03-24 10 20 25](https://cloud.githubusercontent.com/assets/19762670/24300984/416b2306-107c-11e7-8619-3924a5f400c2.png)

The dropdown (in this case up) box is the single select that should be filtered, and the part below it is an Entity Command driven Lava to bridge the gap.

I was hoping that I could refer to Workflow Attributes in Single/Multi-Selects so that I could do things like a workflow for a Connection Request that can do things like knowing all of the Placement Groups for that Connection Opportunity.

```Select GroupData.Id as 'Value', GroupData.Name as 'Text'
From (
	Select 
		g.Id
		, g.Name
		, LGT.[Value] as 'LifeGroupType'
		, KFriend.[Value] as 'KidFriendly'
		, AAS.[Value] as 'AgeAndStage'
	From [Group] g
		Left Join (
			Select g.Id, av.[Value]
			From [Group] g
				Left Join [AttributeValue] av on g.Id = av.EntityId
			Where 
				av.AttributeId = 3811 --Life Group Type
		) as LGT on g.Id = LGT.Id
		Left Join (
			Select g.Id, Case When av.[Value] = 'True' Then 'True' Else 'False' End as 'Value'
			From [Group] g
				Left Join [AttributeValue] av on g.Id = av.EntityId
			Where 
				av.AttributeId = 3812 --Kid Friendly
		) as KFriend on KFriend.Id = g.Id
		Left Join (
			Select g.Id, av.[Value]
			From [Group] g
				Left Join [AttributeValue] av on g.Id = av.EntityId
			Where 
				av.AttributeId = 3813 --Age and Stage
		) as AAS on AAS.Id = g.Id
	Where g.GroupTypeId = 26
		and g.IsActive = 1
		and g.Id != 60 --Global Conenctor Group
) as GroupData
Where
	(Len('{{ Workflow | Attribute:'LifeGroupType','RawValue' }}') = 0 or GroupData.LifeGroupType = '{{ Workflow | Attribute:'LifeGroupType','RawValue' }}')
	and (Len('{{ Workflow | Attribute:'KidFriendly','RawValue' }}') = 0 or GroupData.KidFriendly = '{{ Workflow | Attribute:'KidFriendly','RawValue' }}')
	and (Len('{{ Workflow | Attribute:'AgeandStage','RawValue' }}') = 0 or GroupData.AgeAndStage = '{{ Workflow | Attribute:'AgeandStage','RawValue' }}')```

**Comment by edmistj** [comment]
Not sure having access to workflow attributes inside of a single select would be an option.

**Comment by NuclearTacos** [comment]
@edmistj On that note, I have a proposition based on my relatively limited understanding of Rock's inner workings.  I get how Attributes wouldn't have access to that kind of information, but is there any opportunity for a new kind of attribute?

My thought is that a User Entry Form has a header and footer (and others if I'm not mistaken) where Lava is rendered.  Is there any way that a new kind of attribute could be made?  The idea is that it would only render it's dropdown values when shown in a user entry form, and when it's being displayed elsewhere, it is just the raw text of the values they selected.

It's use would be pretty specific, but it would be VERY beneficial to those of us who continue to push the boundaries of what Workflows can do. I am completely able to find other applications for this outside of the originally posted one.

I'm sure that there's trickery you could do with lava in pre-HTML with JQuery feeding the value to the hidden workflow box, but nobody wants that to be the answer to this question.

**Comment by edmistj** [comment]
So are you wanting a way to filter drop-down lists inside of a workflow entry?

**Comment by NuclearTacos** [comment]
That would _also_ work, but it's less powerful than what I'm asking for :+1:

**Comment by NuclearTacos** [comment]
(which is OK if it's what happens as long as that has the ability to interact with Workflow Attributes.)
