### ISSUE TITLE
[EN] DDay.iCal package has been deprecated

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2050]
### Description

Per the documentation on [DDay.iCal](https://www.nuget.org/packages/DDay.iCal/), this package has been deprecated in favor of [iCal.net](https://www.nuget.org/packages/ical.net).  In addition, the non-standard license DDay.iCal used was [relinquished](https://github.com/rianjs/ical.net/blob/master/history.md) in favor of an MIT license.

The latest version of iCal.net has a [guide to transition](https://github.com/rianjs/ical.net/wiki/Migrating-from-dday.ical) as well as a bugfix for equality checking on child schedules.

**Comment by nairdo** [comment]
This is not a problem for us.  In the event that we find an issue we need to fix, we'll probably just take over a copy of iCal and maintain/extend as needed (similar to what we did with dotliquid).

**Comment by arranf** [comment]
@nairdo @azturner  Are you sure about this? Migrating to ICal.Net seems pretty straightforward and comes with what appears to be significant performance improvements. I'd be happy to start a branch for this and do any required work.

**Comment by edmistj** [comment]
@arranf I'd view Nick's response as not a no, but a not now. We're working super hard on getting traction on v7 features while still having to do consulting work to offset the funding gaps. This could be something to look at for v8 or v9. If you'd like to start playing with it that would be good, but at the end of the day I think it would take a core team member's time before it could be rolled in to core (to review it, understand it and ensure it has been properly tested).

**Comment by nairdo** [comment]
[For reference: With Rock v12, we are [cutting core over to the iCal.net](https://github.com/SparkDevNetwork/Rock/commit/8a68e96c7c8280e32736c38a2053463d06d2212f) library.]
