### ISSUE TITLE
Group Type - Group Member Workflows - Not Active, but being triggered

### ISSUE THREAD

**Issue by gladsonj** [SparkDevNetwork/Rock#2051]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

In Group Type, under Group Member Workflows, I have 2 Workflows. However, one of them is marked inactive here itself. (Workflow itself is active, but Active checkbox is unmarked inside Group Member Workflows inside Group Type). Still when a Member is added, both the Workflows are being triggered.

### Steps to Reproduce

1. Open Group Type
2. Inside Group Member Workflows, assign 2 Workflows
3. Mark one of them as Inactive
4. Perform a step to trigger the workflows (For Ex: add a member, to the Group, if the workflow was set to be triggered on adding a member. )
5. Open Tools -> Workflows and you will see that there is a Workflow Instance for each of the Workflows, including the one marked Inactive.

**Expected behavior:** 

Workflow Instance should be triggered only for the ones marked Active.

**Actual behavior:** 

Workflow Instance is being triggered for all the Workflows in the list.

### Versions

* **Rock Version:** [Rock McKinley 6.2]  
* **Client Culture Setting** [en-US]

**Comment by cabal95** [comment]
This bug actually still exists. The commit fixes when the _Workflow Type_ is set to inactive. But I it does not address the issue originally reported which is that the GroupMemberWorkflowTrigger will still have it's workflow launched even if GroupMemberWorkflowTrigger.IsActive == false.

Verified on pre-alpha 8.0.

**Comment by arranf** [comment]
Nick partially fixed this here 6044605b45b0795279dad432b811679d347c43ec.
