### ISSUE TITLE
Applying discount code deselects registrar's family association

### ISSUE THREAD

**Issue by bengoshow** [SparkDevNetwork/Rock#2054]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When completing a paid registration, applying a discount code deselects the Family association radio button, even if it was selected before applying the discount code. This is confusing and annoying.

<img width="1174" alt="screen shot 2017-03-07 at 3 03 31 pm" src="https://cloud.githubusercontent.com/assets/1636930/23675610/d99e9960-0347-11e7-96b7-783838a4f375.png">

<img width="1174" alt="screen shot 2017-03-07 at 3 03 43 pm" src="https://cloud.githubusercontent.com/assets/1636930/23675619/e0c43236-0347-11e7-9691-0185a0d33c5e.png">

### Steps to Reproduce

1. Register for an Event
2. Complete the registrar information, including family association
3. Apply a discount code
4. Attempt to finalize registration
5. Notice that the family association is no longer selected, resulting in an error message.

### Versions

* **Rock Version:** 6.2 
* **Client Culture Setting** en-US

**Comment by azturner** [comment]
Fixed here: https://github.com/SparkDevNetwork/Rock/commit/d0fbaab8
