### ISSUE TITLE
Event Registration maximum attendee cap can be bypassed

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2059]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If a registration has more than one registrant, the maximum attendee cap is bypassed, which allows registrations beyond the maximum attendee number set on the event instance. 

### Steps to Reproduce

1. Create an event instance with a Maximum Attendee count of 4 
2. Register 5 people on a single registration.
3. 😳

**Expected behavior:** 

Error message stating how many spaces are available. 

**Actual behavior:** 

Successful registration without errors being generated.

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting** en-US

**Comment by edmistj** [comment]
Just a confirmation note.

1. This is an issue in 6.x 
2. It's fixed in v7 (mostly)
3. In v7 it will stop you from increasing the registrant number in the picker but it doesn't tell you why you can't register more. A message should be shown to notify the person registering that there is no more space.

**Comment by gladsonj** [comment]
@garrettjohnson This is not possible from the External Site, right? I am assuming, this is from the Internal Site only. Is my understanding correct?

**Comment by garrettjohnson** [comment]
@gladsonj This is currently possible on the internal and external site.

**Comment by garrettjohnson** [comment]
Fixed in V7. Thanks @edmistj @azturner 🎉
