### ISSUE TITLE
Person Get Spouse Workflow Action is Not Setting Activity Attributes from Workflow Attribute Person

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#2062]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The `Person Get Spouse` workflow action doesn't properly set an **Activity Attribute**. It works fine when setting a **Workflow Attribute**. Also, setting a **Workflow Attribute** to the spouse, and then trying to set **Activity Attributes** based off of that does not appear to be working either.

### Steps to Reproduce

1. Set up a **Workflow Attribute** to be a person.
2. Set up an **Activity Attribute** for the person's spouse.
3. Attempt to use the `Person Get Spouse` action to set the **Activity Attribute** to the spouse of the person stored in the **Workflow Attribute** you set up in step 1.

**Expected Behavior:** 

- **Activity Attribute** should be set to the spouse of the **Workflow Attribute**, if a spouse exists.

**Actual Behavior:** 

- **Activity Attribute** is not be set, ever.

### Versions

* **Rock Version:** Rock McKinley 7.0
* **Client Culture Setting** en-US

**Comment by azturner** [comment]
Fixed Here: https://github.com/SparkDevNetwork/Rock/commit/ddfe49519fed38b53d21abef675b5a506d44c786?diff=split
