### ISSUE TITLE
Contribution Statement Pledge Progress Incorrect

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2070]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Pledges section of the contribution statement incorrectly uses the total amount given by everyone to a fund to calculate the amount given. The same number is used to calculate the pledge progress. 

(Total Given by All Contributors / Amount Giving Group Pledged) = Pledge Progress

Amount remaining is also based on Total Given by all contributors.

### Steps to Reproduce

1. Create a pledge to an existing fund from a individual with no giving

**Expected behavior:** 

Pledge progress shows a giving group's pledge progress relative to their own giving.

**Actual behavior:** 

Pledge progress uses total organization wide giving to gauge pledge progress, amount remaining, and pledge progress.

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting** en-US

**Comment by mikepetersonccv** [comment]
This was fixed a while ago with https://github.com/SparkDevNetwork/Rock/commit/20ab491e53ca7d35a51b624e46dfdd0c07f4bacd, but I updated it a bit to be more consistent https://github.com/SparkDevNetwork/Rock/commit/c0054a42c838a2b73786219e791bbeba78c362a1

I also pulled this in 1.6.5 using https://github.com/SparkDevNetwork/Rock/commit/6f6f7f96ebb4de87c9ac99b14e034f15eb4a09f7
