### ISSUE TITLE
Smart Search not gracefully handling "potentially dangerous route" type exceptions

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2077]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using a search term that has a < in it, you get a visit from our friendly neighborhood Server Error in '/' Application.
![runtime error - google chrome 2017-03-20 17 06 27](https://cloud.githubusercontent.com/assets/19762670/24124138/495d6ff4-0d90-11e7-9f27-695cf408bf1a.png)

This is not an issue with the person picker box.

### Steps to Reproduce

1. Login to internal site
2. Use Smart Search box to search for something starting with "<" (without quotes}

**Expected behavior:** 

I either expected the box to search with the "<" attached or have a more graceful handling.

**Actual behavior:** 

You get a Server Error in '/' Application until you navigate away from the page.

### Versions

* **Rock Version:** [6.1, 6.2]  
* **Client Culture Setting** [en-US]

**Comment by cabal95** [comment]
Already fixed by @mikepetersonccv when he added birthdate to the search field.

Commit: d4f2b1ee7b885b79def54d3865f60d323791e9cc
