### ISSUE TITLE
User Entry Form required field indicators missing when attribute label is hidden

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#2080]
### Description
On a workflow, when a User Entry Form has required fields that have their labels hidden, the warning message hides part or all of the indicator for which fields have not been filled out.

### Steps to Reproduce
1. Create a Workflow
1. Add a Text Attribute
1. Add a Multi-Select Attribute with at least one option
1. Create a User Entry Form action and mark both attributes visible, editable, required, and hide label
1. Run an instance of the workflow
1. Click submit without populating the attributes

**Expected behavior:**

The message at the top would show this for both attributes:

* [Label Name] is required.

Even though the label is hidden, there should still be an indicator using the label stored in the attribute for which fields are missing.

**Actual behavior:**

The text attribute displays a line that just says "is required."  The mutli-select line does not display anything at all.

![https://cloud.githubusercontent.com/assets/18447084/24154187/7ca4f0ec-0e1e-11e7-9350-d1bb94410a9a.png](https://cloud.githubusercontent.com/assets/18447084/24154187/7ca4f0ec-0e1e-11e7-9350-d1bb94410a9a.png)

![https://cloud.githubusercontent.com/assets/18447084/24154354/ede36b9e-0e1e-11e7-9a9f-409201423bcb.png](https://cloud.githubusercontent.com/assets/18447084/24154354/ede36b9e-0e1e-11e7-9a9f-409201423bcb.png)

### Versions
* **Rock Version:** Rock McKinley 6.2
* **Client Culture Setting** en-US

[ub issue](https://github.com/SparkDevNetwork/Rock/issues/2080)

**Comment by jennifertroeger** [comment]
When following the steps to reproduce In my 13.4 testing the text attribute label does appear as it should, however the multi-select label does not.
![Screen Shot 2022-05-19 at 2 37 54 PM](https://user-images.githubusercontent.com/36419045/169375963-69d6a4cd-f541-48b3-a3fa-294f91f7b2f5.png)
.

**Comment by nairdo** [comment]
With this additional change (https://github.com/SparkDevNetwork/Rock/commit/271cbfd0e4df41d5c41dc5e3e658105e1fe73b02) both of these cases are working in my tests.
![image](https://user-images.githubusercontent.com/383807/172406773-79e3f6d2-9909-4645-b916-8a74d2d62f2f.png)
