### ISSUE TITLE
SignNowSDK missing from distribution

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2081]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The SignNowSDK.dll file is missing from the distribution, thus causing the RockIt SDK to not build/run and causing errors when trying to use digital signatures (presumably).

### Steps to Reproduce

1. Browse to http://rock.rocksolidchurchdemo.com/Webhooks/SignNow.ashx
2. Witness error stating the dll is missing.

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting** en-US

**Comment by azturner** [comment]
Fixed here: https://github.com/SparkDevNetwork/Rock-UpdatePackageBuilder/commit/3367206dd0d198b4270c24728c71572d5a4d3f1c
