### ISSUE TITLE
Workflow view details does not honor expected security

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2098]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We are looking for a way to allow users to run a workflow but not view the details. Specific example is the background check workflow. It contains sensitive data and with the current Security model if they can Run the workflow they can also view the details.

There is already a "View List" security class on Workflows that will hide the "List" button from the Workflows page. But, the block to actually view the list of workflows (Workflow List) does not honor this security class. This feels like a bug to me since they can just view the list of another workflow type and change the ID number. Granted the average user doesn't know the right ID number, but that still feels like a bug when it comes to security.

Additionally, the block to view the details of an existing workflow (Workflow Detail) does not honor that security class either. I wouldn't necessarily consider this a bug, but to me it defeats the purpose of denying somebody the ability to view the list of workflows. They can still put in the workflow Id numbers to view the actual details and bypass the "View List" security.

So, I'd like to get feedback from one of the core developers on the best way to approach this (and if either would be acceptable).

1. Make both `Workflow List` and `Workflow Details` honor the "View List" security class.
2. Make `Workflow List` honor the "View List" security class. Make a new security class called "View Details" that the `Workflow Details` block will honor.

The only use-case I can think of where I would want somebody to be able to view the details of a workflow item but not view the list is if I wanted to generate a direct link for them so they could see that one specific workflow but not others. I suppose we could handle that with a block setting on `Workflow Details` that allows a Guid to be passed and bypasses the "View List" portion of the security check.

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting** en-US

**Comment by edmistj** [comment]
@cabal95 Option #1 seems prudent. I agree that the lack of implementation is more of a bug than a feature. When we implemented that security right it was more for the Workflow Navigation block which is more of a public block than the others.

**Comment by cabal95** [comment]
Sounds good, and fairly straight forward. I can work on a PR for this as this is something we want for ourselves as soon as we can (and it will save me a stink load of time trying to lock down Workflows with other methods).

**Comment by edmistj** [comment]
👍

**Comment by nairdo** [comment]
I think some of this was already addressed via this @azturner change here https://github.com/SparkDevNetwork/Rock/commit/8c16ccd2d4b8582488c05bc18ee224bf765380c7#diff-3fbd40a31af9fc85aaa04ead81476779R204 which looks like this when Ted Decker is trying to view a Background Check -- he now only sees the **Summary** tab content:

![image](https://cloud.githubusercontent.com/assets/383807/24813404/b8a6f614-1b82-11e7-975f-56b5114619c0.png)

where formerly, in v6.2 Ted would see the **Details** tab content:
![image](https://cloud.githubusercontent.com/assets/383807/24813463/ee707fc2-1b82-11e7-8370-a693974c0972.png)

Based on the conversation between you and Jon, I'll proceed with merging in the related PR anyhow.
