### ISSUE TITLE
[Docs] Allowed Frame Domains needs updated

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2103]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The document at https://www.rockrms.com/Rock/BookContent/14/110#creatinganewsite currently says:

`If you need to allow an external site/domain to be able to embed your site (such as in an iframe) just enter each domain as a whitespace delimited list. Rock will then take care of sending the correct page headers that block all other sites.`

Users also need to be made aware that the Rock URL also needs to be present otherwise you can lock yourself out of any modal popups on your own site, such as editing a block. So if you wanted to allow rock.rocksolidchurchdemo.com to be embedded on www.example.com you would have to have something like the following in your list:

`http://rock.rocksolidchurchdemo.com https://rock.rocksolidchurchdemo.com http://www.example.com https://www.example.com`

Otherwise you get errors when you are browsing on rock.rocksolidchurchdemo.com and try to edit a block.

This might be considered a bug, as maybe Rock should automatically include it's own domains in the CSP.

**Comment by NuclearTacos** [comment]
Also, it would be helpful if the help text said space delimited instead of whitespace delimited (since it won't work if you put newlines in there) or if the box is made to allow other forms of whitespace too.

**Comment by nairdo** [comment]
Link to updated docs: https://www.rockrms.com/Rock/BookContent/14/110#creatinganewsite
