### ISSUE TITLE
[Enhancement] Update Attribute Lava Tag

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2104]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Back Story (Optional)

As I continue to use Workflows, and make systems that work beyond a singular linear workflow, I find myself in need of being able to set Attributes for Entities that aren't supported by an Activity or UI.

The use-case that brought this to my attention the most was making a Workflow/Connection system to help shepherd people into a Small Group when they don't know which specific group they want, just the parameters they want (like age range, day of week, etc).

I had Workflow A be a form Workflow to take the traits they were looking for, then it created a Connection Request.  That Connection Request started Workflow B (so that the workflow would be accessible from the Connections page) and that Workflow would access those Attributes that we entered into Workflow A and filter the available Small Groups by that criteria.

The hitch was there wasn't a direct way to pass the Attributes from Workflow A to B **because** Workflow B wasn't _started_ by Workflow A, but rather the Connection Request.  I handled this by including the ID of Workflow A in the Connection Request Comment, then using an entity command to access Workflow A and it's attributes from Workflow B.

This is obviously far from ideal, and what would be amazing is to be able to set the attributes of the Connection request in Workflow A.  I mean, I can create the Attributes through the UI, I can retrieve their values in Lava, but I can _only_ set them in SQL and then I have to clear the cache to make sure everything works the way I'd expect it to.

### Proposed Enhancement

I think this is a ripe target for a Lava Tag.  The main goal would be to have a tag that allows you to update a target Attribute's value for an Entity. I think that it warrants its own security setting in line with how Lava SQL and Entity Commands have to be turned on.  I also think that it should adhere to the security settings of the one who saves it (e.g. You can't use it to edit an attribute that you couldn't edit otherwise due to security settings).
#### Example Implementation
Even though these examples are using a Person entity (which is supported with Workflow actions and the UI, I can produce as many use-cases as you'd like to make your decision.
`{% updateattribute CurrentPerson 'AttributeKey' attributeValue  %}`
```{% assign person = CurrentPerson %}
{% assign emphone = person.PhoneNumbers | First | Property:'NumberFormatted' %}
{% updateattribute person 'EmergencyPhoneNumber' emphone %}
```
Bonus points if the AttributeKey can be fed a string variable containing the attribute key

(I also think setattribute is a good name)

I firmly believe in the value behind this kind of Tag.  I will gladly answer any questions on it, and I'm always up for discussion on the best way to make something like this happen.

**Comment by gladsonj** [comment]
Highly useful requirement

**Comment by garrettjohnson** [comment]
It would probably be much easier and safer to continue to extend what's possible in workflows. Lava is all about loading and displaying dynamic content, with it's ability to run anywhere in Rock there's too much to go wrong. It would take lava from a ultra-powerful templating language to a sort of pseudo-code that would be very difficult to implement and exclusive to Rock.

@NuclearTacos Are there any entities that cannot be updated from workflows that would be most beneficial?

**Comment by cabal95** [comment]
Additionally, some (all?) of this can now be achieved via the Lava short codes since the short code can run the SQL required to perform the update.

**Comment by NuclearTacos** [comment]
With lava short codes and `workflowactivate`  to perform updates to a Person, you're set.

AFAIK, there's no Workflow Actions to change Group Attributes and Connection Attributes, plus, with the new Entity Attribute Values block on prealpha, you'll have much more access to editing those entities.

I guess that a Workflow Action that can take a Person, Entity Type, Entity Id, Key, and value to set that Attribute Value but checking that Person's Security first would be nice.  An option to skip the security check would be nice.

That Action could let you choose more or less freedom for the Lava writer.

@cabal95 I guess you could use SQL for updating those Attribute Values, but it wouldn't refresh the cached version of the Attribute, so I think you'd need to use `{% execute %}` or something like that to have it work more reliably.

**Comment by cabal95** [comment]
@NuclearTacos The Attribute Values themselves aren't cached, just the Attributes. So as long as you are not editing the Attribute itself the cache won't be an issue.

And I think a generic "Set Entity Attribute Value" workflow action would be good.  I don't think it should check security as that would be up to the Workflow logic. So it just needs a Guid/Id, Entity Type, Key and Value.

**Comment by NuclearTacos** [comment]
@cabal95 
:thinking: I have been tiptoeing around editing Attribute Values in SQL for months :laughing: But it's probably for the best.

I'll give a big :+1: to "Set Entity Attribute Value"

I'm unfamiliar with a good way to check security on an Attribute.  I know you could check for Group Membership, but I feel like it would be an unnecessary pain to keep your Workflow security check in line with your Attribute security check (as infrequent as changes to that would be) when the methods for checking that should be just a few lines of C# away.

That's the reason I think it'd be nice to build in an optional security check into the action (you know, since I'm lazy).  Do you think it would make sense from a UI and expandability standpoint to have part where it checks a person's security for Attribute editing to be its own Action that returns a boolean?

**Comment by cabal95** [comment]
I know there is a `HasRightsTo` (I think thats what it's called) Lava Filter. Now that you mention it I'm not 100% sure if that can be used to check permissions to Attributes. If not I think we should expand it to support that (or if need be a new `HasRightsToAttribute` filter).

I wouldn't be against making the `Person` attribute optional in the `Set Entity Attribute Value` - but I think it would almost always be left blank.  I'm not sure there has ever been a time I've wanted to check security before setting the value. Usually it would be far earlier in the workflow process that I would check permissions and not even fire off the activity if they didn't have permission to set the value. i.e. rather than say "enter new value" next page "oops, looks like you don't have access to do that"; just say "sorry you don't have access to do that" from the start.

**Comment by Tschrock** [comment]
I've already messed around with a few different versions of a "Set Entity Property" action for some of our projects. It wouldn't be to hard to convert that into an action that works with attributes instead. I'd be happy to tidy some of it up and make a PR if we're heading that way. The current version of what I have for properties looks like this: 
![Set Entity Property action](https://user-images.githubusercontent.com/2406499/30285851-8786a980-96ed-11e7-83d8-14ff5bacd59a.png)
This would allow setting a property (or for version we're talking about here, an attribute) on any entity without needing a specific action for that entity or resorting to SQL.

As for security, I think you have to have the AttributeValue entity itself to be able to use the `HasRightsTo` filter on it. A `HasRightsToAttribute` filter would simplify that a lot. I don't normally find myself wanting to check security for individual actions happening inside my workflows, but that may be useful for other, more lava-focused things.

**Comment by cabal95** [comment]
@Tschrock I love it. Would it make sense to make the `Entity Guid` to `Entity Guid or Id`?  Sometimes I have a Guid, and sometimes I have an Id.

Can you describe a bit what that `Empty Value Handling` is for?

**Comment by Tschrock** [comment]
@cabal95 I think that would be fine, and wouldn't be too hard to make happen.

The `Empty Value Handling` tells it what to do if the value is blank, i.e. an empty string or whitespace. I don't think it would have a use for Attributes, but for Properties it has three options:
 - `Ignore empty values` - If the Value is blank, it will leave everything alone and skip setting the property.
 - `Set to empty` - If the Value is blank, it will set the property to an empty value. For example, a string property would get set to an empty string `""`. Maybe type conversions could use default values? (Otherwise you'd get a FormatException for things like ints)
 - `Set to NULL` - If the Value is blank, it will try to set the property to NULL. If the property isn't nullable, it acts like `Set to empty`.

**Comment by NuclearTacos** [comment]
@cabal95 Then a filter like `| HasRightsToAttribute:` would fill my last concern for this issue.

@Tschrock cool action!  How does it handle people trying to write to Properties that they can't?  (like Guid and Id) Or for that matter, is there any properties it won't let you overwrite, like CreatedDateTime?

**Comment by edmistj** [comment]
@Tschrock Having an action like that for Entity Attributes would be awesome in core. Are you able to do a PR for that? The current action for updating properties would also be a good addition.

**Comment by Tschrock** [comment]
@NuclearTacos For properties, Entity Framework and SQL Server will validate things before it saves, so email addresses still have to look like email addresses, Ids can't be changed, database constraints can't be broken, etc (CreatedDateTime is still fair game). Errors will stop the workflow just like in any other action.

@edmistj I can have a PR ready soon:tm:. I'll put them both in the same one, if that's alright.

**Comment by edmistj** [comment]
One PR for both is great. Looking forward to seeing how long your trademarked 'soon' is ;)

**Comment by arranf** [comment]
Looks like it was one day!
