### ISSUE TITLE
Group list block on person profile page doesn't respect security on group

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#2112]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The group list on the person profile shows group membership even when the users has been denied view for both the group itself and the group type. The user can't click on the group and get to the group viewer but they can see that the person belongs to the group.

I was expecting either deny view on the individual group or the group type to make the group not appear on the group list.

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting** en-us

**Comment by gladsonj** [comment]
@KelleyLangkamp Could you please List the steps to Reproduce? I assume, there is a lack of clarity here.

**Comment by garrettjohnson** [comment]
Steps to Reproduce

1. Deny a user view access to a group
2. Open groups tab on a profile as the user
3. All Group Memberships are visible

Confirmed in 6.8
