### ISSUE TITLE
External Site - Event Registration - Family Picker should show only Active Family Members

### ISSUE THREAD

**Issue by gladsonj** [SparkDevNetwork/Rock#2114]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
On the External Site, during Event Registration, which has "Registrants in same Family" = Yes and "Show Family Members", Family Dropdown should show only Active Family Members (Person Record Status = Active). It is not filtering out Inactive / Pending Family Members.

**Expected behavior:**

Only Active Family Members to be shown (Person Record Status = Active).

**Actual behavior:**

All Family members are shown, ignoring Person Record Status.

### Versions
* **Rock Version:** [6.2]
* **Client Culture Setting** [en-US]

**Comment by edmistj** [comment]
I'm not sure inactive and pending family members (as group members) are a supported thing. How are those group member statuses being set?

**Comment by garrettjohnson** [comment]
It looks like the record status for the person record, (rather than the family group membership), is being ignored. 

I think excluding pending family members might cause a lot of duplicates because you'll end up with people creating family members from the my account page, and then not being able to register them.

**Comment by gladsonj** [comment]
@garrettjohnson is right. It is not the Family Membership Status, but rather the Person Record Status.

**Comment by jrockman13** [comment]
I don't consider this a bug...for example, we have many families where family members are marked as inactive. For example, Dad never comes..but then maybe they want to come to the Men's kickoff? Or maybe they are registering the same new kid for multiple events at the same time...if it doesn't show the pending record, they might add the new kids multiple times. Maybe a block setting to allow churches to decide?

**Comment by jonedmiston** [comment]
Posted in the community and it seems like there is a majority that would prefer to have inactive people in the family shown. This is a good opportunity though to post an Idea to have a setting to have it either way though.
https://community.rockrms.com/Ideas
