### ISSUE TITLE
Reassign Transactions button does not support businesses

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#2118]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When selecting transaction(s) on a person's "Contributions" page, if you click "Reassign Transactions" and try to type in a business name, it will not auto-complete the business name the way the "Edit Transaction" page does to reassign the transaction to a business. Since a business is just a person record, it seems that it should work. It would be a benefit for it to work as well, in the case where transactions have been assigned to an owner and should have been assigned to their business instead.

### Steps to Reproduce

1. Ensure a business has been added to Rock (necessary on the demo site)
2. Add a person as a business contact (just to be sure). I added Alisha Admin as the contact.
3. Visit Alisha Admin's profile and click on the "Contributions" tab. Select a transaction from her list and click "Reassign Transactions".
4. Type in the name of the business.

**Expected behavior:** 

The business name should auto-populate in the dropdown and allow you to select it. Note that if you visit the batch and find the transaction (provided the batch is "Open", you can edit the transaction - a business name does auto-complete and allow itself to be assigned in that dialogue.

**Actual behavior:** 

The auto-complete dropdown box remains blank so you can't reassign the transactions

### Versions

* **Rock Version:** 1.6.2  
* **Client Culture Setting** EN-US

**Comment by mikejed** [comment]
It should be noted that https://github.com/SparkDevNetwork/Rock/blob/36cf12cefeca76573c21968fcf1ac09d5ea2fa6b/RockWeb/Blocks/Finance/TransactionList.ascx#L128 includes the parameter IncludeBusinesses="true"

**Comment by edmistj** [comment]
Looks like this feature was added a few weeks ago via this commit: https://github.com/SparkDevNetwork/Rock/commit/33f1857303fdc10658c939b9154a5d6020d24a7b

**Comment by mikejed** [comment]
Ha, very good. Sorry, I thought I'd done enough research

**Comment by edmistj** [comment]
No problem. It's difficult to determine when you only have the code on Github. We hope to add a 'pre-alpha-release' demo at some point. They you can check issues against the latest code.
