### ISSUE TITLE
Add Metric Value button vanishes after Postback

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2119]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When viewing the details of a Metric, that is the graph and the list of metric values, on page 1 by default the Add Value button shows up. After postback, for example moving to the second page, the Add Value button vanishes.

### Steps to Reproduce

1. View a Metric that has enough values to cause multiple pages of value results.
2. Click a page tab button to move to another page of results.
3. Add button magically vanishes.

**Expected behavior:** 

I should be able to add new values even after the postback.

**Actual behavior:** 

Rock performs some kind of incantation to make the button go invisible.

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
I was unable to reproduce the problem on the demo site because there was insufficient metric data to work with. Needs to be reproduced by somebody else to verify it is not an issue with just our server.

**Comment by mikejed** [comment]
I created a new metric in the demo site and used a DynamicData block to insert more than 50 values. When I go to the second page I can confirm that the "add" button disappears. It is missing from the HTML, not just hidden.
![missingaddbutton](https://cloud.githubusercontent.com/assets/6932047/24689650/c7872d50-197c-11e7-9ce4-740fee66ad2f.JPG)

<details>
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 3, 3, '2017-04-03', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 4, 3, '2017-04-04', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 5, 3, '2017-04-05', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 6, 3, '2017-04-06', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 7, 3, '2017-04-07', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 8, 3, '2017-04-08', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 9, 3, '2017-04-09', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 10, 3, '2017-04-10', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 11, 3, '2017-04-11', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 12, 3, '2017-04-12', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 13, 3, '2017-04-13', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 14, 3, '2017-04-14', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 15, 3, '2017-04-15', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 16, 3, '2017-04-16', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 17, 3, '2017-04-17', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 18, 3, '2017-04-18', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 19, 3, '2017-04-19', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 20, 3, '2017-04-20', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 21, 3, '2017-04-21', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 22, 3, '2017-04-22', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 23, 3, '2017-04-23', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 24, 3, '2017-04-24', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 25, 3, '2017-04-25', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 26, 3, '2017-04-26', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 27, 3, '2017-04-27', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 28, 3, '2017-04-28', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 29, 3, '2017-04-29', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 30, 3, '2017-04-30', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 31, 3, '2017-05-01', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 32, 3, '2017-05-02', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 33, 3, '2017-05-03', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 34, 3, '2017-05-04', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 35, 3, '2017-05-05', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 36, 3, '2017-05-06', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 37, 3, '2017-05-07', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 38, 3, '2017-05-08', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 39, 3, '2017-05-09', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 40, 3, '2017-05-10', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 41, 3, '2017-05-11', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 42, 3, '2017-05-12', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 43, 3, '2017-05-13', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 44, 3, '2017-05-14', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 45, 3, '2017-05-15', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 46, 3, '2017-05-16', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 47, 3, '2017-05-17', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 48, 3, '2017-05-18', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 49, 3, '2017-05-19', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 50, 3, '2017-05-20', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 51, 3, '2017-05-21', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
INSERT INTO MetricValue (MetricValueType, YValue, MetricId, MetricValueDateTime, CreatedDateTime, ModifiedDateTime, CreatedByPersonAliasId, ModifiedByPersonAliasId, Guid)
VALUES (0, 52, 3, '2017-05-22', '2017-04-04', '2017-04-04', 1, 1, NEWID() );
</details>
