### ISSUE TITLE
Missing Address Line 2 Field on New Families and Edit Family

### ISSUE THREAD

**Issue by jdschrack** [SparkDevNetwork/Rock#2121]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When editing existing families without a second address line the line is not visible, and when creating new families there is no way to add a second address line.

### Steps to Reproduce

New Family
1.  Go to New Family
2.  Look at the address section Street, City, State, and Zip appear.
 
Existing Family
1.  Open an existing member that does not currently have a second address line
2.  Click to edit the family.
3.  Notice the address street 2 is missing.

**Expected behavior:** 

The ability to modify the second line of the street address.

**Actual behavior:** 

Only presented with the first line of the street address.

### Versions

Rock Version 6.2
EN-US

**Comment by arranf** [comment]
I'm going to close this for now as altering this behaviour would require a significant investment in time and there are other priorities at the moment.
