### ISSUE TITLE
ConnectionRequestActivities Not Always Working Like Other Properties

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2126]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
![lava tester _ rock rms - google chrome 2017-04-05 18 14 04](https://cloud.githubusercontent.com/assets/19762670/24730956/781086b2-1a2c-11e7-9957-d6e84570c9ae.png)

### Steps to Reproduce

From Demo Site
1. Add Activities to one of those Connection Requests
2. Make new Workflow Type with a Connection Request Attribute defaulted to the CR that you made the Activities for.
3. Run that Workflow, note it's ID
4. Go to HTML Content block with Rock Entity commands enabled.
5. Paste the following and use the appropriate ID in the first line.
```{% workflow Id:'8' %}
<h3>{{ workflow | Attribute:'SCR','Id' }}</h3>
{{ workflow | Attribute:'SCR','ConnectionRequestActivities' | ToJSON }}
<hr>
<h3>{{ workflow | Attribute:'SCR','Object' | Property:'Id' }}</h3>
{{ workflow | Attribute:'SCR','Object' | Property:'ConnectionRequestActivities' | ToJSON }}
{% endworkflow %}
```

**Expected behavior:** 

I expected all properties to behave like other properties.  I would have expected the two "ConnectionRequestActivities' lines to behave the same.

**Actual behavior:** 

This property (and others that I can't recall) don't behave like other properties all the time.
### Versions

* **Rock Version:** 6.1 here, 6.2 on demo  
* **Client Culture Setting** en-US

**Comment by cabal95** [comment]
In particular, this property is a `virtual` property as it is filled in on the fly by Entity Framework. But unlike most other EF `virtual` properties it does not have the `LavaInclude` attribute tagged on it. There are a few times I have run into this. Each time I have been able to circumvent by using the `Property` filter but it would be nice if we got all these properties fixed up so they are available in Lava through native access.

**Comment by arranf** [comment]
@NuclearTacos Could you test this on the [prealpha site](http://prealpha.rockrms.com/)?

**Comment by NuclearTacos** [comment]
@arranf 
AFAIK, this means it's confirmed on prealpha.  BTW, prealpha.rockrms.com makes me super excited! :tada: 
![image](https://user-images.githubusercontent.com/19762670/30250477-aebb14ca-9614-11e7-904e-6f87bdae1e0b.png)

**Comment by nairdo** [comment]
As per the documentation, without the 'Object' qualifier, the Attribute filter will only "...return a string representation of the attribute."

**Comment by NuclearTacos** [comment]
@nairdo 
> This will return a string representation of the attribute. Sometimes you may want more from attributes though; especially if the attribute is a type like "Person," which has several more properties. To gain access to these properties you can add an optional filter qualifier, where the qualifier value maps to the property you want to display.
> Mentor: {{ CurrentPerson | Attribute:'Mentor','LastName' }}

That block of text and the example doesn't specify that the Properties of the Attribute are to be returned as text instead of their object forms.

**Comment by NuclearTacos** [comment]
A revision to the documentation is likely fine.  If you want to make it where I can do stuff like `{{ Workflow | Attribute:'SCR','ConnectionRequestActivites','Object' }}` to get the Object version of the Properties of the Attribute, I'd be glad to write up concise documentation for https://www.rockrms.com/page/524 :+1:

**Comment by edmistj** [comment]
@NuclearTacos I'm not sure where you'd suggest the documentation edit go. If you could attache a link to where the documentation needs to be edited and the updated verbiage we'll make the change.

**Comment by arranf** [comment]
I'm going to close this for now.

**Comment by NuclearTacos** [comment]
@edmistj Man, it has been sooo long 😆 Idk what I did or didn't see in the documentation back then. But reading it again, I don't see the problem it looks like I saw.

Closing this is a good call.
