### ISSUE TITLE
Disabling TLS 1.0 causes check-in labels not to print

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#2127]
<Details>
Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

</Details>

### Description

When you disable TLS 1.0 to be PCI compliant on your Rock instance in IIS it causes check-in labels not to print. 

### Steps to Reproduce

1. Login to your web server
2. Download IIS Crypto (makes this easy) - https://www.nartac.com/Products/IISCrypto
3. Disable TLS 1.0
4. Reboot
5. Open WIndow's check-in application
6. Check some one in.
7. Label will not print.

**Expected behavior:** 

Label still needs to print with out needing TLS 1.0 support.

**Actual behavior:** 

Label does not print. 

### Versions

* **Rock Version:** 
6.2

**Comment by edmistj** [comment]
@austinspooner When you say "Open check-in application" that's the Windows Check-in App?

**Comment by austinspooner** [comment]
@edmistj  - correct. I will check the iPad one tomorrow.

**Comment by cabal95** [comment]
Just heard from Austin that the iPad works fine, so it is just a Windows App issue.

**Comment by edmistj** [comment]
This is fixed https://rockrms.blob.core.windows.net/externalapplications/sparkdevnetwork/windowscheckin/1.6.0/checkinclient.exe
