### ISSUE TITLE
Icon disappears on Relationships.ascx block

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#2128]
<details>
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
</details>

### Description

When you add the Relationships.ascx block to the Extended Attributes person page- the font awesome icon disappears when you edit the block. 

Notice on this video it happens at the 7 second mark.
https://www.screencast.com/t/uvQUR34FQz6

### Steps to Reproduce

1. Add block to extended attributes page
2. Add relationship using block
3. Notice icon goes away until page refresh.

**Expected behavior:** 

Icon should stay constant on the page. 

**Actual behavior:** 

Icon goes away until page refresh.

### Versions

* **Rock Version:** 6.2

**Comment by edmistj** [comment]
@mikepetersonccv  can you get this into v6.3?

**Comment by mikepetersonccv** [comment]
fixed with 62de16fb18a2b25cacc5c2465363b2703a00e1ee
