### ISSUE TITLE
Enhancement: Adding a Group Registration Max Cost

### ISSUE THREAD

**Issue by rutledgek** [SparkDevNetwork/Rock#2132]
This is an enhancement Request

The ability to add a max cost to registrations when a person registers more than one person.  We charge 25.00/person but only a max of 50.00 per family/group.  If the registration value is over this, it would default to the value entered in the max/group.

**Comment by rutledgek** [comment]
To do this manually for one event that cost 25.00/person and 50.00/group,  I created discount codes:

Child3:25
Child4:50
Child5:75
Child6:100

The parents can figure out their own code, but I figured partial payments was cleaner.  Both have UX issues. 

If technically possible, one way to accomplish this would be to have a system discount code(GroupRate) that can have a variable amount(Total Reigstration Cost - Group Rate).

**Comment by arranf** [comment]
This would require significant changes to how Event Registration is done so I'm going to close this for now.
