### ISSUE TITLE
EventItemOccurrenceListByAudience.lava contains bad image link

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2135]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you add a EventItemOccurrenceListByAudienceLava block to a page, you see a broken image. Examining the associated Lava file shows a link to `<img src="/Themes/NewCovenant_v1/Assets/Images/icon_calendar.png" />` which is not a path on a default Rock install, nor does the icon_calendar.png image exist on a Rock install.

### Steps to Reproduce

1. Open EventItemOccurrenceListByAudience.lava
2. Observe the bad href

**Expected behavior:** 

No broken image. Looks like this might have been left in there from some custom dev work and the entire href should be removed from the file.

**Actual behavior:** 

Broken image link exists in the lava

### Versions

* **Rock Version:** [6.2]  
![image](https://cloud.githubusercontent.com/assets/3903408/24776710/a0c540a0-1ae7-11e7-8ebb-70944e8a22b4.png)

**Comment by cabal95** [comment]
Looks like this has been fixed by b4cc6fed0c68e12dc15920efe1bde2b6f4444bfa back in January already - though this will probably not fix existing installs it should fix any new installs.
