### ISSUE TITLE
Enhancement - Allow ACH for Event Registrations

### ISSUE THREAD

**Issue by rutledgek** [SparkDevNetwork/Rock#2137]
I honestly don't know the technical issues that might be preventing using ACH for event registrations, but given that ACH is much cheaper for us, we would always want people to use it as an option whenever they want.

**Comment by nairdo** [comment]
Hello amazing community member! We've recently moved 'feature requests' to our own "Ideas" system on our Community site at: http://community.rockrms.com/ideas

If you'd like to re-propose your idea and put it up to the vote, please re-submit your idea there. Thanks!

**Comment by taylorbrooks** [comment]
We had someone ask about this yesterday. And it is the number one feature request people have for us.

I created the idea here: https://community.rockrms.com/Ideas
