### ISSUE TITLE
Many model properties are not available in Lava

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2140]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

There are many (126) model properties that are not available directly to Lava in dot-syntax, but are available via the `Property` filter. Below should be an exhaustive list of all model properties that are not available in Lava. Some of these probably make sense to not have available but I think many could have the `LavaInclude` attribute safely applied to make things more consistent to what the end-user writing Lava expects (e.g. `Category.ParentCategory`).

List is in the format of `Model`.`Property`.

### List of properties

<details>
<pre>AttributeQualifier.Attribute
Audit.PersonAlias
AuditDetail.Audit
Auth.Group
Auth.PersonAlias
Auth.EntityType
BackgroundCheck.PersonAlias
BackgroundCheck.Workflow
BackgroundCheck.ResponseDocument
BenevolenceRequestDocument.BenevolenceRequest
BinaryFile.DatabaseData
BinaryFile.StorageProvider
Block.Page
Block.Layout
Category.ParentCategory
CommunicationRecipient.Communication
ConnectionActivityType.ConnectionType
ConnectionOpportunity.ConnectionType
ConnectionOpportunity.Photo
ConnectionOpportunityCampus.ConnectionOpportunity
ConnectionOpportunityCampus.Campus
ConnectionOpportunityCampus.DefaultConnectorPersonAlias
ConnectionOpportunityConnectorGroup.ConnectionOpportunity
ConnectionOpportunityGroup.ConnectionOpportunity
ConnectionOpportunityGroupConfig.ConnectionOpportunity
ConnectionOpportunityGroupConfig.GroupType
ConnectionOpportunityGroupConfig.GroupMemberRole
ConnectionRequestWorkflow.ConnectionRequest
ConnectionRequestWorkflow.ConnectionWorkflow
ConnectionRequestWorkflow.Workflow
ConnectionStatus.ConnectionType
ConnectionType.OwnerPersonAlias
ConnectionWorkflow.ConnectionType
ConnectionWorkflow.ConnectionOpportunity
ContentChannel.Items
ContentChannelItem.ApprovedByPersonAlias
ContentChannelItemAssociation.ContentChannelItem
ContentChannelType.Channels
DataViewFilter.Parent
DefinedValue.DefinedType
Device.Location
Device.PrinterDevice
EntitySet.ParentEntitySet
EntitySetItem.EntitySet
EntityType.SingleValueFieldType
EntityType.MultiValueFieldType
EventItemOccurrenceChannelItem.EventItemOccurrence
EventItemOccurrenceGroupMap.EventItemOccurrence
ExceptionLog.Site
ExceptionLog.Page
FinancialAccount.ParentAccount
FinancialAccount.Campus
FinancialPersonBankAccount.PersonAlias
FinancialPersonSavedAccount.PersonAlias
FinancialPersonSavedAccount.Group
FinancialScheduledTransaction.AuthorizedPersonAlias
FinancialScheduledTransactionDetail.ScheduledTransaction
FinancialScheduledTransactionDetail.Account
FinancialTransaction.Batch
FinancialTransaction.RefundDetails
FinancialTransaction.ScheduledTransaction
FinancialTransaction.ProcessedByPersonAlias
FinancialTransactionImage.Transaction
FinancialTransactionImage.BinaryFile
Group.ParentGroup
GroupLocation.Group
GroupMemberRequirement.GroupMember
GroupMemberRequirement.GroupRequirement
GroupMemberWorkflowTrigger.GroupType
GroupMemberWorkflowTrigger.Group
GroupRequirement.Group
GroupRequirement.GroupRole
GroupRequirementType.DataView
GroupRequirementType.WarningDataView
GroupType.InheritedGroupType
GroupTypeRole.GroupType
HtmlContent.Block
HtmlContent.ApprovedByPersonAlias
InteractionSession.DeviceType
Layout.Site
Location.ParentLocation
MergeTemplate.TemplateBinaryFile
MergeTemplate.MergeTemplateTypeEntityType
Metric.MetricValues
Metric.DataView
Metric.MetricChampionPersonAlias
Metric.AdminPersonAlias
Metric.Schedule
MetricPartition.Metric
MetricValue.Metric
MetricValuePartition.MetricPartition
MetricValuePartition.MetricValue
Page.ParentPage
Page.Layout
PageContext.Page
PageRoute.Page
Person.GivingGroup
PersonDuplicate.PersonAlias
PersonDuplicate.DuplicatePersonAlias
PersonPreviousName.PersonAlias
PersonViewed.ViewerPersonAlias
PersonViewed.TargetPersonAlias
PhoneNumber.Person
PrayerRequest.Group
RegistrationRegistrant.Registration
RegistrationRegistrantFee.RegistrationRegistrant
RegistrationTemplate.Category
RegistrationTemplate.GroupType
RegistrationTemplateDiscount.RegistrationTemplate
RegistrationTemplateFee.RegistrationTemplate
RegistrationTemplateForm.RegistrationTemplate
RegistrationTemplateFormField.RegistrationTemplateForm
ReportField.Report
RestAction.Controller
ScheduleCategoryExclusion.Category
Site.ChangePasswordPage
SiteDomain.Site
Tag.OwnerPersonAlias
Tag.TaggedItems
UserLogin.Person
WorkflowActionForm.NotificationSystemEmail
WorkflowActionFormAttribute.WorkflowActionForm
WorkflowActionType.ActivityType
WorkflowActivity.ActivatedByActivity
WorkflowActivityType.WorkflowType
WorkflowLog.Workflow</pre>
</details>

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting:** en-US

**Comment by azturner** [comment]
@cabal95 , Thanks for going through these. To be consistent, I say just add the [LavaInclude] to all of the virtual properties that don't already have it (or the [DataMember] attribute). There's not really any downside to having the [LavaInclude] that I can think of (we do need to be careful about what properties get the [DataMember] attribute so that we don't end up with circular serialization issues). Feel free to add those and submit a pull request.
