### ISSUE TITLE
Make event registration "registered by" optional

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2145]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When a event registration template is set to only allow a single registrant it would be great if it was possible to disable the registered by / "This Registration Was Completed By" block in the registration template. We've noticed a significant increase in errors and duplicates being created when a person is only registering themselves. 

I'd propose a "Hide Registration Completed By for single registration" checkbox, by checking the box Rock would use the person info collected on the registration form, unless the person is logged in. I don't think it's practical to allow this option for multiple registrants.

**Expected behavior:** 

Optionally hide the final page "This Registration Was Completed By" block when forcing single registrations.

**Actual behavior:** 

"This Registration Was Completed By" always shows.

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting** en-US

**Comment by tbice** [comment]
We are experiencing issues with the 'this registration was completed by' section as well.  We always require a login for event registrations, and the person's name is pre-filled in that section.  However, we have found that some people will use their spouses login, and then enter their own name in that section.  It ends up creating a new record, and the 'registered by' is no longer associated with the login that was used.  We have several large events with the option to make multiple payments - and this has caused a lot of heartburn for us when folks can no longer see the event they registered for.

**Comment by arranf** [comment]
This has been implemented in the past.
