### ISSUE TITLE
Common registration attributes use first name for all fields

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2146]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When an event registration template is set to Registrants in the same Family, and Show Family Members is selected, the first name of the logged in user is filled in for all form fields set to use a common value. 

### Steps to Reproduce

1. Create an event template with Registrants in the Same Family, and show family members
![screenshot 2017-04-11 13 44 34](https://cloud.githubusercontent.com/assets/374209/24930060/11718ea2-1ebd-11e7-8d81-eb52db66e0ef.png)

2. Add a field with common value enabled.
![screenshot 2017-04-11 13 48 48](https://cloud.githubusercontent.com/assets/374209/24930220/99afc6b2-1ebd-11e7-952a-060365044e53.png)

**Expected behavior:** 

Common value is set by the values provided for the first registrant.

**Actual behavior:** 

The first name is populated on all fields set with a common value.
![screenshot 2017-04-11 13 46 25](https://cloud.githubusercontent.com/assets/374209/24930125/44985bc6-1ebd-11e7-9e07-81df99f7f906.png)

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting** en-US

**Comment by gladsonj** [comment]
This is already reported in #2040 and #2009 and has been fixed
