### ISSUE TITLE
Registration's Show Family Members Issue

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#2147]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When Show Family Members is selected, everything that is a text field in the registration gets filled with the first name of the person selected (phone, email, text, memo). This happens at the start when a person is auto-selected--I assume the first person in the list. If you unselect the person and select the blank field then choose a person, it clears out the issue and removes the first name from all those fields where they shouldn't be. If there are multiple people in the family, selecting a different person corrects this issue as well.  

Maybe the block needs to start on the blank field instead of the first person in the list.

I thought it might be an issue with Common Value or Current Value but I alternated between those and an attribute that doesn't use either of them and it still occurs so it looks like it is something with the block when it is first loaded.

rock.rocksolidchurchdemo.com/registration/sp

### Steps to Reproduce

1. Create registration using Show Family Members option.
2. Add some attributes to test (I've only noticed it on text-based ones)
3. Go to the registration's link and register. The attributes added will be auto-filled with the first name of the person who is auto-selected.

**Expected behavior:** 

Either the Show Family Member drop down to be blank, or not to auto-fill all text-based attributes with information unless it is a person attribute with a current value.

**Actual behavior:** 

All text-based attributes are auto-filled with selected person's first name.

### Versions

* **Rock Version:** 6.1 and 6.2

**Comment by gladsonj** [comment]
This was reported multiple times and this has been Fixed.
#2146 #2040 #2009
