### ISSUE TITLE
Connection Opportunity Attribute Display Incorrect on Grids

### ISSUE THREAD

**Issue by edmistj** [SparkDevNetwork/Rock#2149]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The attributes on connection opportunities show on the wrong side of the delete button. 

### Steps to Reproduce

1. Add attributes to a connection opportunity and have them 'show on grid'
2. View them in incorrect order

**Expected behavior:** 

Should be in correct order.

**Actual behavior:** 

Wrong order
![chrome_2017-04-13_12-48-07](https://cloud.githubusercontent.com/assets/548178/25021654/ce10d8e8-2047-11e7-990e-a2e1c6e666c6.png)

### Versions

* **Rock Version:** [Enter Rock version here]  
* **Client Culture Setting** [Enter Client Culture here]

**Comment by arranf** [comment]
Fixed at some point in the past.
