### ISSUE TITLE
Statement Generator Credential error

### ISSUE THREAD

**Issue by jdavidnewell** [SparkDevNetwork/Rock#2151]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
I keep getting the Ooops error The User Name or Password is incorrect when trying to proceed after step 3 of selecting the date range. I can choose data views, individual records, I can see all accounts so i know it is logging in just fine. I have Run As Admin but that made no difference. I have tried on other computers(all running Windows 10) but same result. The only thing that has worked was doing a remote login to my azure server and installing and running it there successfully. Unfortunately those that need use of the generator don't get access to the server for the same reasons they are not the ones trying to figure out a solution. 

### Steps to Reproduce

1. Log in to Statement Generator on a workstation(not server)
2. Proceed through steps 1-3 and click Next
3. Window stops responding briefly 
4. Commence Ooops message: The User Name or Password is incorrect
5. Bang head against wall

**Expected behavior:** 

Continue on to step 4 of choosing layout without injury to head.

**Actual behavior:** 

Window gives message (Not Responding) then Oops message pops up with incorrect User Name or Password

### Versions

* **Rock Version:** [6.2]  
* **Client Culture Setting** [en-US]

**Comment by cabal95** [comment]
@jdavidnewell I'm not entirely sure, but I would suspect some kind of firewall issue. I just tested the statement generator against the demo site and our own server (off site to both) and it worked fine on both of them.

URL: http://rock.rocksolidchurchdemo.com
Username: admin
Password: admin

I was able to proceed to the very end where it tried to generate the statements (it gave a warning saying no records matched my criteria). If the above settings do not work for you then something on your network/workstation might be blocking the connection past step 3. I don't know where the source code is just yet to see if it is doing anything different at that step. Step 4 is just selecting the local statement layout file. Possibly this file is corrupt / missing?

**Comment by cabal95** [comment]
@jdavidnewell Can you also post a screenshot of the exact error message you get?  I'm assuming what you typed is paraphrased because I can't find it in the code anywhere.

**Comment by jdavidnewell** [comment]
Update. I took my laptop home and was able to successfully go through the process without the same error. Then when I went back to work it worked on my computer but still was not working on our finance directors computer. The Oops error is what it says above word for word.

**Comment by jdavidnewell** [comment]
I will post a screen shot next week when I am back in the office.

**Comment by arranf** [comment]
@jdavidnewell Sounds like a configuration issue for you rather than an issue with the app. I'm going to close this for now but feel free to comment here again with more details if you have reasons to suspect otherwise.
