### ISSUE TITLE
Connection Opportunity attributes show on right of delete colum when shown on grid

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2154]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Configuring a Connection Opportunity attribute to Show on Grid makes it show up to the RIGHT of the delete column on the grid.

### Steps to Reproduce

1. Configure any connection opportunity attribute to show on grid
2. Observe the attribute(s) are on the right of the delete column

**Expected behavior:** 

Attributes on grid would show to the left of the delete column like all other grids.

**Actual behavior:** 

It's on the right.

### Versions

* **Rock Version:** [6.2]  
![image](https://cloud.githubusercontent.com/assets/3903408/25059560/4e9bf3f6-214e-11e7-8c9f-3b65bccaa74d.png)

**Comment by edmistj** [comment]
This is the same issue as #2149
