### ISSUE TITLE
SMS check-box won't stay enabled if Add Group block contains 'Visit Information' attribute category

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/Rock#2160]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * [X] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/page/5408)?
    * [X] Did you include your Rock version number and [client culture]
    * [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

This _could_ be related to #1252 or #1011 but I think this is separate and new, in part because those issues are older and have been closed

If you select an 'Attribute Category' of 'Visit Information' for display during 'Add New Family' the 'SMS' check-box will not keep it's setting when the family is added. This picture highlights the issue....Sally Bobbie and Bobbo Bobbo Bobbie were entered using a 'stock' Block Properties configuration. Shawn Huff and Michelle Huff were entered using a 'Visit Information' Attribute Cateogry configured block.
![testguestfollow-up _ rock rms - google chrome 2017-04-24 13 03 24](https://cloud.githubusercontent.com/assets/8688424/25352507/d70971dc-28f1-11e7-90ba-92b0e51bc81d.png)

<ul><strong>Resources used for testing on demo site:</strong>
<li>'Add New Family' page that has 'Visit Information' enabled: [Example Page](http://rock.rocksolidchurchdemo.com/page/5408)</li>
<li>Persons added using stock/out-of-box add new family config:
<ul><li>[Bobbo Bobbie](http://rock.rocksolidchurchdemo.com/person/121)</li>
<li>[Sally Bobbie](http://rock.rocksolidchurchdemo.com/person/122)</li></ul>
<li>Persons added using the 'Add New Family' with 'Visit Information' enabled:
<ul><li>[Shawn Huff](http://rock.rocksolidchurchdemo.com/person/127)</li>
<li>[Michelle Huff](http://rock.rocksolidchurchdemo.com/person/128)</li></ul></ul>
Dynamic Data Block SQL used so I could spot-check recent entries:
SELECT p.Id
      , p.NickName + ' ' + p.LastName AS 'Name'
      , pn.NumberFormatted
      , pn.IsMessagingEnabled
      , p.Email
      , p.CreatedDateTime
      , pn.NumberTypeValueId
 FROM Person AS p
 LEFT JOIN PhoneNumber AS pn
     ON pn.PersonId = p.Id
 WHERE p.CreatedDateTime >= DATEADD( dd, -4, GETDATE());

### Steps to Reproduce

<ol>
<li>Create a new page. (http://rock.rocksolidchurchdemo.com/page/5408)</li>
<li>Add the 'Add to Group' block to the page</li>
<li>Change the 'Block Properties' and under 'Attribute Categories' select the "Visit Information" item</li>
<li>Add a new family (tested with one or two family members), making sure to
<ul>
<li>enter a mobile number</li>
<li>check-marking the 'SMS' box</li>
<li>select a data for the 'First Visit Date'</li>
</ul>
</ol>

**Expected behavior:** 

<ul>
<li>Person added to Rock as they were entered into the 'Add to group' block</li>
<li>'Visit information' saved</li>
<li>SMS check-box enabled for the person(s)</li>
</ul>

**Actual behavior:** 

The person(s) are added to Rock, but the 'SMS' check-box is not enabled on their record

### Versions

* **Rock Version:** [6.2]  
* **Client Culture Setting** [en-US]

**Comment by cabal95** [comment]
Confirmed. Since selecting any attribute category causes this problem, I suspect it is an issue with the SMS checkbox not being "re-checked" on postback for the extra screen that comes up.
