### ISSUE TITLE
Contribution Statement Lava block does not show Public name of accounts.

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2164]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Contribution Statement Lava block allows transaction.account.Name (internal name) or PublicName to be grabbed, but the _account summary_ only supports accountsummary.AccountName, which is the internal account name. There is no way to get the PublicName of an account via accountsummary.

**Expected behavior:** 

Block would support both AccountName and PublicName in accountsummary

**Actual behavior:** 

Only the internal account name can be retrieved in accountsummary

### Versions

* **Rock Version:** [6.3]  

![image](https://cloud.githubusercontent.com/assets/3903408/25512775/d7d3d0d4-2b95-11e7-8ec9-ea1078006a3c.png)

**Comment by azturner** [comment]
Fixed here: https://github.com/SparkDevNetwork/Rock/commit/5afbb771c56acdb537abd8a7dad06df50e5ae519
