### ISSUE TITLE
Ability to flag Accounts for Event Registration use

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2165]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We currently have 87 Financial Accounts and need to add another 15-20 accounts for Event Registration (for GL code tracking). Currently when a staff person sets up an Event Registration Instance they are presented with the entire list of accounts (which in our case will be over 100). We would like to limit them to just "event registration" accounts for two reasons.

1) It makes their life easier trying to find the right account.
2) We really really really REALLY do not want somebody to accidentally select the wrong account and have event registrations get flagged as going to a contribution related account.

We would like to propose adding a new "Is" flag to financial accounts, `IsEvent`. Then on the block for setting up a Registration Instance have it filter the list of accounts to only accounts flagged with IsEvent. This would probably be done by modifying the Account Picker to support some form of "Show Only Event Accounts" setting that would be turned on by the block.

Other blocks, such as public facing transaction detail, _could_ be updated to filter out IsEvent accounts, but we think it would be better to leave those as is. Public facing blocks should already be filtering on the IsPublic flag. Leaving public facing blocks unchanged would still allow the finance team to prevent those accounts from showing up OR allowing them to show up if they desired.

To provide for backwards compatibility the migration would need to add the IsEvent flag and update all existing Financial Account entities to `IsEvent = 1` so that all existing accounts still show up in the account list.

The other option to provide this functionality would be a new block setting on the Registration Instance Detail block to select the accounts that are available for selection - but that puts the burden on the finance person to create the account and then _wait_ for I.T. to go in and modify the block to include that new account. In general we think it better to put the entirety of the ownership on the financial admin.

We are more than happy to write the code needed to support this (other than the migration since I don't know how to do that part) but would like to get some feedback from the devs (both core and general developers) on if this is the best way to go about solving this.

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting** en-US

**Comment by edmistj** [comment]
Many people aren't aware that Financial Accounts are actually hierarchical. Would it fill the need to Create a Parent Account called 'Event Accounts' and then put the events under that? You could even add sub-parents for the year '2017'. Seems like that would make the selection process super easy.

If a filter was needed we should make it more extensible. Something like 'Account Purpose' which would be a defined value so it could also support 'Giving', 'Fundraising', etc.

Hoping though that the parent would work as it would require no additional code. Always prefer to innovate on ministry than administration.

**Comment by jeremyhoff** [comment]
>  Always prefer to innovate on ministry than administration.
I concur 100%!

>  Many people aren't aware that Financial Accounts are actually hierarchical. 
I saw that, but didn't understand the implications of setting up accounts with a parent.  Sounds like a feature for organizing Accounts.

>  Seems like that would make the selection process super easy.
Indeed.  What we're trying to avoid a situation where someone will [IndianaJonesLastCrusade] choose poorly [/IndianaJonesLastCrusade].

**Comment by cabal95** [comment]
This does seem like it would fill our need. It might be a week before we can go over this in detail but I'll chat with Hoff in greater detail about this, though it seems like it should work. It doesn't 100% "solve" the second item (them picking the wrong account) but it moves that into more of a "they just were not paying attention, totally their fault" situation rather than they just clicked the wrong thing because the name was similar to what they were looking for.

After we talk through the process I'll come back and close this issue out if that does indeed resolve it as I think it will.

**Comment by rutledgek** [comment]
I do think a way of filtering accounts through a defined value could be helpful, especially if available in areas other than event registrations(like giving blocks).  I'm still looking for a way to show only accounts belonging to a particular campus in the giving block dropdown. 

There are still too many to only show the accounts and not allow the dropdown, but I don't want all of the accounts created and active to show up in the drop-down either. So either a defined type or a filterable hierarchy.

**Comment by edmistj** [comment]
There is a hierarchy today. We'll add a filter to the grid in v7 and improve the UI to show the heirarchy under "Finances > Accounts" in v8.

**Comment by edmistj** [comment]
@cabal95 are we good to close this now?

**Comment by cabal95** [comment]
Down the road I think it will make sense to provide some sort of defined type for account purpose would be good, but after talking through it with a few people the hierarchy will be good for now. I'll go ahead and close this.

@rutledgek If you end up opening a new enhancement request for the transaction entry block you should probably reference this one (even though it's closed) to keep track of the previous discussion.

**Comment by edmistj** [comment]
I added the idea to an internal 'future features' list.
