### ISSUE TITLE
Encrypted Text Workflow Attribute Type

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#2167]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Storing a value to an "Encrypted Text" type Workflow Attribute results in the value being stored in plaintext in the database
![encryptedtextbug](https://cloud.githubusercontent.com/assets/6932047/25541207/ad993e5e-2c02-11e7-88c8-d1b585c8a6cd.JPG)

### Steps to Reproduce

1. Create a workflow with a single attribute of type "Encrypted Text"
2. Create a single `Attribute Set Value` action in the default activity, to set the value of your attribute to "Don't read this"
3. Save and run the workflow
4. Run the SQL query `SELECT TOP 10 * FROM [AttributeValue] ORDER BY [Id] DESC`
5. Observe the plaintext value "Don't read this" in the database (twice)

**Expected behavior:** 

The value in AttributeValue should be encrypted

**Actual behavior:** 

The value in AttributeValue is not encrypted

### Versions

* **Rock Version:** 1.6.2 
* **Client Culture Setting** EN-US

**Comment by cabal95** [comment]
One possible solution would be to have the `Attribute Set Value` action specifically check if the target attribute type is an Encrypted Text field and if so encrypt the text.  That is normally done by the EncryptedTextField UI portion. Since `Attribute Set Value` sets raw values the encryption is being bypassed.

Another solution would be to add Lava Filters for `EncryptText` and `DecryptText` - though I'm not sure off the top of my head if there are security concerns to `DecryptText`.

**Comment by mikejed** [comment]
With further experimentation, we also found that using the dropdown on the `Attribute Set Value` to copy the value of an `Encrypted Text` attribute to another plain `Text` attribute, uses the raw value of the encrypted attribute, whereas using `{{ Workflow | Attribute:'Encrypted' }}` in the input tries to decrypt the value.

So if you set the value of an `Encrypted Text` attribute using Attribute Set Value, (which won't be encrypted), using the dropdown on a second Attribute Set Value action to copy the value to a `Text` attribute results in the text attribute being legible (since it copied the non-encrypted value right over) but using Lava in the input results in an error (rendered as an apparent blank) since it's trying to decrypt text which it believes is encrypted, but in fact is not.
