### ISSUE TITLE
[Feature] New block for viewing effective security for entities

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2171]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

It is not uncommon for new users, or even us experienced users, to click things in the wrong order and lock ourselves out of a page, group, or whatever. When that happens currently the only way to fix it is to go into SQL and hunt down the offending record and delete it by hand.

While this is something those knowledge in SQL can do, new users are not so readily able to figure this out on their own. It can also be difficult to walk them through the process, especially if a mis-typed DELETE statement is entered and wipes out their entire Auth table. And to be honest I think most of us are hesitant to start throwing out DELETE statements at our own production database even if we have experience. We've probably all accidentally hit enter too soon or something and cried.

### Proposal

A new block that could be installed in Power Tools that allows `RSR - Rock Administration` users to see the effective permissions for either themselves or a specific person. This is a generic use block that the user would select the entity type to be inspected and enter the entity Id (as either an integer or Guid). This means it would still be a somewhat advanced usage block that brand new users would probably not know exactly what to enter, but after using it once or twice (with guidance from the community or documentation) they should be able to make use of it on future issues.

<img width="468" alt="trace security" src="https://cloud.githubusercontent.com/assets/1119863/25597037/4db9a77c-2e81-11e7-957b-80b1d6050cc4.png">

The block offers three elements of functionality.

1. It allows you to view effective permissions of any person in the database, not just yourself. This comes in handy when somebody that should have access does not and you don't see the obvious reason. You can view the effective permissions that person has to the entity in question to figure out where the Deny rule is coming from.
2. Shows only the effective permissions rather than all inherited and explicit permissions. Sometimes I miss the fact that somebody is denied access to something because they are in a group that is Deny access due to ordering. Additionally, the source entity where the explicit permission is defined is displayed.
3. Ability to "pop the trunk" if you have locked yourself out of something. Clicking the unlock button will add (or update if one exists) an explicit Authorization record on the entity in question that allows the selected person access.

The screenshot is from a sample of a common scenario. I was changing permissions on the public website homepage and accidentally set `All Users` to `Deny` forgetting that I need to give myself permissions first. Leaving `Person` blank means the block will work off of my currently logged in Person. Entity Type is set to `Page` as that is what I am locked out of. The `Entity Id` is set to `1` as that is the Page Id of the external homepage.

The permissions show that `View` and `Edit` are set to `Allow` and have been inherited from the `External Website` Site. `Administrate` shows `Deny` because of the All Users role I added. In this case since there is already an explicit rule on Page 1 for Deny clicking the Unlock button will simply switch it to `Allow`, thus granting me permissions.

The Actions are automatically detected from the entity type. So if an entity has defined the `Approve` action then it will show up as well.

There is one caveat to this block, though I believe the cases are extremely few. This block looks at the Auth records from the database. This means there are two cases where it might show different than what is actually allowed.

1) The database has become out of sync with the Auth cache in memory. This is fixed by simply doing an `Empty Cache`.
2) A few entities override the `IsAuthorized` method to do additional checks. There are only about 6 entities that do this. One example is the Note entity type. It first checks if the user is the creator of the note and if so grants them full access. Otherwise it calls the standard `IsAuthorized` method. In this case the block might show that the user is Denied access when really they do have access.

Feedback requested and welcome. I spoke briefly with Jon on this and he said to post some details and we'll see what everybody thinks of this being core vs. a plugin.

### Versions

* **Rock Version:** 6.2 
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Wonder if you could read the values out of the cache and compare them to the database. This would allow you to alert the person that the cache needs to be flushed. Could also allow them to flush just the security cache.

**Comment by cabal95** [comment]
There is no public method to access the internal auth cache to comparison purposes. To be fair, the only time I've ever run into this case is when I'm manipulating the Auth table directly in SQL anyway. A "Flush Auth Cache" button would be easy to add, as that is a public method that can be called. If we added a public method to the Authorization class to retrieve the contents of the in-memory cache then we could indeed check the in-memory cache and the database values as we traverse the tree and look for discrepancies.

Another thought I had was to also call the entity's `IsAuthorized` method for each Action and compare the final Allow/Deny result with what we found. It wouldn't tell us that the same Auth rule we found is the same one the Authorization system found, but would tell us if the Authorization system says they are Denied but we found they were Authorized.  This would help with item 1, but item 2 there is not much we can do about - though those are usually hard-coded checks anyway (like in the example of the Note).

**Comment by edmistj** [comment]
I think we could add a way to get the cached auth for an entity through a new public method. I'm fine though with a flush auth cache though for now as if you used SQL to get yourself into the mess you should be able to use it to get yourself out, or at the very least should know to flush the cache.
