### ISSUE TITLE
Signature request from registration throws an error.

### ISSUE THREAD

**Issue by cbump** [SparkDevNetwork/Rock#2177]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When trying to send a signature request from a registration, an entity error is thrown. 

### Steps to Reproduce

1. Load a registration for a template that requires a signature document.
2. Make sure the person doesn't have the signature document already.
3. Click the button to send a signature request.

**Expected behavior:** 

The signature request should be sent.

**Actual behavior:** 

An exception is thrown: An entity object cannot be referenced by multiple instances of IEntityChangeTracker.

### Versions

* **Rock Version:** Rock McKinley 6.2
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Patch already submitted, but confirmed on our install.
