### ISSUE TITLE
Cannot update account image on front end

### ISSUE THREAD

**Issue by bengoshow** [SparkDevNetwork/Rock#2187]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When a logged-in front-end user attempts to replace or add their avatar image, the system seems to get hung up at the "crop" step.

### Steps to Reproduce

1. Go to http://rock.rocksolidchurchdemo.com/MyAccount
2. Click the "Update" button next to the profile image
3. Click the "pencil" icon to edit or replace the thumbnail image.
4. Select a new image
5. Select an area of the image and click the "Crop" button

**Expected behavior:** 

The Rock animation spins, but never closes the "Crop" dialog window, and doesn't update the account image.

**Actual behavior:** 

After the animation spins and disappears, the "Crop" dialog window remains visible, with no apparent action to complete the process.

### Versions

* **Rock Version:** 6.2

**Comment by arranf** [comment]
Fixed on the prealpha site, possibly hotfixed before this.
