### ISSUE TITLE
Cannot logout when URL contains Url Encoded Key

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2202]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When a user has loaded a Rock URL using a Url Encoded Key, they're unable to logout because the page URL automatically signs them back in.

### Steps to Reproduce

1. Go to any page with a encoded key i.e. `http://www.rocksolidchurchdemo.com/?rckipid={{ CurrentPerson.UrlEncodedKey }}`
2. Click Logout

**Expected behavior:** 

User is logged out of the current session.

**Actual behavior:** 

User remains logged in because the page reloads with the `rckipid` query variable.

### Versions

* **Rock Version:** 6.3  
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Suggest that the logout is smart enough to remove the `rckipid` from the return URL
