### ISSUE TITLE
[Feature] Site Icons

### ISSUE THREAD

**Issue by edmistj** [SparkDevNetwork/Rock#2210]
For a long time we've been wanting to add a property to the Site model to allow for the easy configuration of a site icon (aka favicon). There's a lot of different ways to do this so I thought before we implemented it we should get some input. 

I've played with a few WordPress themes and this is what they typically do.

1. Allow you to upload a square image.
2. They then use that image to insert this markup into the head <link rel="icon" href="http://server.com/wp-content/uploads/2017/05/cropped-image-32x32.jpg" sizes="32x32">

I was thinking we'd do the same but add several different sizes using Rock's image resizing capabilities. Planning on supporting:

- 16x16
- 32x32
- 57x57
- 144x144
- 152x152

Having this markup seems to override the presence of the favicon.ico in the webserver root (in my testing on Chrome and IE)

@garrettjohnson @cabal95

**Comment by cabal95** [comment]
Just to throw some extra information in: https://github.com/audreyr/favicon-cheat-sheet

It isn't well formatted reading, but it does mention quite a few extra sizes and configurations that might be helpful (specifically the tiles for Windows Tile icons).

Also this site might be useful to help people generate (or re-generate) their icons, possibly a simple integration in Rock with it's API to help get things put in the right place. http://realfavicongenerator.net

Because there is a lot of stuff to configure for _full_ support of everything, perhaps a Defined Type that has all the required information (including file contents even) and the Site property could be a reference to the Defined Value.  That would also make it easy to allow multiple sites to share the same favicon and update all of them at once.

Even if the default UI is to just upload a PNG that is resized and placed into the Defined Value, if the other attributes exist then an admin could manually populate them and/or a plug-in could be written to help the admin set things up.  Or this could be far more complicated and we just stick with a single file. :)

**Comment by arranf** [comment]
Just to throw in I agree with @cabal95 in my experience the favicon cheat sheet is the authoritative resource on this stuff.

**Comment by edmistj** [comment]
I did use that same cheatsheet to select which sizes to support. To support all seems a bit overkill. Theme developers could of course configure their own settings. My experience with WordPress was that it used just 32x32 so I thought we were being generous to support the top 5 sizes.

**Comment by JimMichael** [comment]
I like the idea. I'll second a vote for the realfavicon site. Aside from giving lots of formats it has like 10 different aliasing algorithms for the favicon itself, and for a complex logo like ours there was s huge difference in the range of quality the different options gave. Having only a single generic algorithm to generate the favicon might not give the best results.

**Comment by garrettjohnson** [comment]
I'd go the route of a simple and advanced uploader found on Wordpress themes. Upload one file and do scaling automatically in simple mode, and allow direct upload of defined sizes in advanced.

While I'm a fan of realfavicon, adding the API dependency (which would require users to get another API key) is probably unnecessary; their recommendations add too much cruft to markup IMO.

For the default sizing I'd drop 57x57 for iOS, and add 180x180. Most top major sites are specifying a single 180x180 image for all apple touch devices and forcing iOS to downsample.

- 16x16 
- 32x32
- 144x144 (Windows)
- 180x180 (All iOS)
- 192x192 (Android)

**Comment by cabal95** [comment]
True, I would only go with the realfavicon API if we could get one to use with all Rock installs. Does anybody know if Windows will automatically use the favicon for the Tile image, or does it need that extra xml file to actually work?

P.S., most of the extra resolutions I was thinking of anyway were to support Tile images on Windows. The image sizes you already specified should work fine until Apple creates a 4x retina screen.

**Comment by garrettjohnson** [comment]
@cabal95 Without extra markup IE/Edge will just use the default favicon and color. With the msapplication markup you can force a tile image and color (Used by large sites: Vox, Pinterest, etc.). I haven't seen any large sites going with the browserconfig xml file. 
```
<meta name="msapplication-TileImage" content="...">
<meta name="msapplication-TileColor" content="#FFFFFF">
```

**Comment by edmistj** [comment]
I did some playing with the scaling algorithm used by Rock. As a sample I took Jim's church logo (agree that it's a complex shape) and used it to create the various sizes. The version from their website is 180px. The rescaling looks pretty good. 

![chrome_2017-05-21_14-50-59](https://cloud.githubusercontent.com/assets/548178/26287673/54f9ead8-3e35-11e7-9a1e-f8b3535601a1.png)

As a note... the GetImage.ashx supports quite a few transformations using the ImageResizing package (documented here https://imageresizing.net/docs/v4/docs/basics). It can also ensure that the format is png which is nice as we don't need to worry if the user provides a jpg. (I did fix an bug where if you changed the formats the mime-type wasn't be adjusted after the transform).

Based on this discussion I'd say we should allow for an upload of a single image (recommended to be square of size 192x192) and we'll add meta tags for the following sizes squared and formatted to a png using GetImage.ashx.

- 16x16
- 32x32
- 144x144 (Windows)
- 180x180 (All iOS)
- 192x192 (Android)

I hesitate to add the options for Windows Tiles as we'd need more attributes from the user for the tile color to be helpful.

I'd also a bit worried about adding a API dependency on another site that we must track and maintain.

Note, these features are meant to be the 'simple' option. A theme developer can support any/all options using their templates. I've been wanting an easy way to change the favicon by site which this solves, but what pushed this into action was an interaction with a member of the Master Class. They needed to get a quick site launched for that weekend. I was able to help them style up something simple, but when they asked how to change the favicon for their new site I had to admit that wasn't going to be easy (especially since they did not have immediate access to the file system of their site to edit the templates).

Any other thoughts before I write up a feature spec?

**Comment by JimMichael** [comment]
I totally agree on the simple option concept. It will cover 95% of the need. Anyone who wants different sizes or options (like a different color to use as background for transparent logos on the iOS icons) will likely already known how to do it the manual way and just stuff them in the site.master.

**Comment by edmistj** [comment]
Closing as this is complete. Good collaboration!
