### ISSUE TITLE
Feature: Per-block timings in page load time footer

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2217]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Collect per-block timings to help track down high page load times. Normally this is easy to do as there are only 1 or 2 blocks on a page (not including layout blocks and site blocks). But when working with end-user dashboard pages you often have many blocks on the page. Often they work fine when initially setup and then suddenly later the page slows down and you don't know exactly why.

### Concept Image

![image](https://cloud.githubusercontent.com/assets/1119863/26366125/c1a8a5ce-3f9e-11e7-9217-d7d6438c5264.png)

Tooltip would be triggered by a click on the page timing text so as to not clutter the screen with accidental tooltips (especially since they can be large on some pages).

### Timing Data

Per-block timing data would be collected from the `OnInit` and `OnLoad` methods of RockBlock. This would encompass any child-block's `Page_Load` and `Page_Init` methods. For non-postback loads this should cover all the expensive block operations. Postback timings might be off unless there is a way to time that, but I'm not sure how critical that is.

Edit: Postback timing issues would be because the `OnInit` and `OnLoad` methods are called and then the event handler method (such as a button click, grid rebind, etc.) methods are called. I don't know if there is a way yet to capture how long those take. For my use normally I don't care about postback as much as initial page load time. And to be honest I'm not sure if the current `Page Load Time` reflects postback timings, does anybody know?

**Comment by cabal95** [comment]
Found a way to track PostBack event handler timing via the RaisePostBackEvent() method of the RockPage. That can be overridden to track the time taken for actual processing and trace up the tree to the RockBlock it relates to.

That is assuming the Page Load Time updates for postbacks. Not sure if it does.

**Comment by mikepetersonccv** [comment]
@cabal95 there already is a ShowDebugTimings Parameter that you can put in the URL to see some of this.  For example, ?ShowDebugTimings=true.  Does that help?

**Comment by cabal95** [comment]
It helps, and much of the logic could probably be re-used. To be honest I had looked at the output before but didn't notice that the "bottom half" was related to the OnLoad timings of the blocks due to the way it was phrased until looking at it a second time just now (basically I was speed reading and missed it).

The output isn't as "user friendly", in that I still need to pull out a calculator to determine how long a single block took to load since all it shows is start times.  That and I'm probably never going to remember to use the `?ShowDebugTimings=true` option. Would there be complaints against re-working the existing ShowDebugTimings code to do the math for the OnLoad timings and change up the formatting to maybe something like a dynamically generated bootstrap modal on click of the "page load time" text?
