### ISSUE TITLE
Mailing address update

### ISSUE THREAD

**Issue by bdeneal** [SparkDevNetwork/Rock#2218]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [6.4] (https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

[Description of the bug or feature. Include screenshots if applicable.]

### Steps to Reproduce

1. Under Edit Family, Add a new address to a family (not a move request)
2. Mark sure Mailing Address has a Checkmark
3. Click Green checkmark to confirm

**Expected behavior:** 

Mailing address checkmark moves to the new address. (This is what happens when you select Map Address)

**Actual behavior:** 

Check mark does not move. Multiple addresses for the family have a mailing address checkmark.

### Versions

* **Rock Version:** [6.4]  
* **Client Culture Setting:** [Enter Client Culture here]  BETA

**Comment by arranf** [comment]
This is no longer the current behaviour. Fixed.
