### ISSUE TITLE
Public Profile Edit Block does not Save Cropped Photo

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#2219]
### Prerequisites
* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Cropping tool does not pass the image back to Public Profile Edit Block.  Additionally, the required field validators stop the cropping popup when adding a new family member.

### Steps to Reproduce

Crop not saving:
1. Go to My Account.
2. Edit record and remove photo.
3. Save.
4. Edit record again and try to add photo.

New Photo Hitting Validators:
1. Got to My Account
2. Add New Family Member
3. Prior to selecting Role and Entering Name, Upload photo.  (I found that if name was there, but not Role the photo attached as-is without the cropping tool even appearing.)

**Expected behavior:** 

Option to crop image.

**Actual behavior:** 

When presented with cropping window, the working animation appears and then goes away with the popup still in place and no image in the placeholder.

### Versions

* **Rock Version:** 1.6.4  
* **Client Culture Setting:** en-US

**Comment by treyhendon** [comment]
I forgot to mention that the photo cropper works as expected on the staff side when editing an Individual's record.

**Comment by JimMichael** [comment]
Is this the same issue? Not fixed until v7 https://github.com/SparkDevNetwork/Rock/issues/2001

**Comment by treyhendon** [comment]
Possibly, but I didn't see an exception on screen like that. I did get an email later that said out of bounds. I assumed that it was new to 6.4 beta.

**Comment by JimMichael** [comment]
We're still on 6.2 and while we don't get an exception on the page anymore when cropping/saving, it is still throwing "Index was outside the bounds of the array" exceptions in the log.. and assumed the v7 fix would fix it.

**Comment by edmistj** [comment]
@mikepetersonccv can you quickly look at this to determine if it's still an issue and fix it if so.

**Comment by mikepetersonccv** [comment]
@edmistj I double-checked and this is fixed in v7, and I also looked in the Exception Log and didn't see any errors there either.
