### ISSUE TITLE
Allow Rock to set cookies globally

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2221]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Currently Rock sets cookies to respect the scope of a fully qualified domain name. I'd like to propose adding a option to the site configuration to add the option of a global cookie. A global cookie would be set using the domain name of the requested site i.e. `domain.tld` (Taking advantage of [RFC 6265](https://tools.ietf.org/html/rfc6265)). This would allow a signin or signout to the Rock RMS administration site work for the External Website simultaneously if they use the same domain.

Configuration would be a single checkbox to `Enable Global Cookie` on the site configuration control panel. Proposed help text, "Allow cookies to be accessed by all subdomains of requested domain (Not Recommended)". The default setting would be to use the current behavior.

#### Default Rock
www.domain.tld — External Website  
rock.domain.tld — Rock RMS administration site

- **Default Behavior** - Login cookie is set for full domain/subdomain, allowing user to be signed into internal site, but not external site.
- **Global Cookie Behavior** - Login cookie is set using `.domain.tld` which would allow simultaneous login to internal/external site. Unfortunate side effect is that the Rock cookie would be included with CDN and other asset requests on the same domain (i.e. `cdn.domain.tld`). In the standard configuration, the global cookie would need to be enabled on both the external website, and Rock RMS administration sites.

#### Fancy Multi-site

www.domain.tld — External Website  
www.domain.church — External Vanity Marketing Website  
rockdomain.tld — Rock RMS administration site  

- **Default Behavior** - Login cookie is set for full domain/subdomain
- **Global Cookie Behavior** - Login cookie is set using `.domain.tld`, `.domain.church`, or `.rockdomain.tld`, any subdomain of the requested domains would receive the `.ROCK` cookie.

#### Considerations

If a site is assigned to multiple domains subdomains, and global cookies are enabled, Rock will always set the cookie using the domain requested by the user. 

#### Example UI
![screenshot 2017-05-25 14 25 35](https://cloud.githubusercontent.com/assets/374209/26472981/a5906d2a-415d-11e7-8f62-a957ca5d2171.png)

**Comment by edmistj** [comment]
👍

**Comment by cabal95** [comment]
This would also help us. Sometimes people create and post URLs that are "not quite correct" (i.e. include www when they shouldn't or vice-versa) which occasionally causes weird login problems (they login, then they have to login again, then it works).

**Comment by edmistj** [comment]
This work has been completed and will be v7. The implementation was a Defined Type that allowed you to add domains that should allow global cookies for the auth cookie. 

![image](https://user-images.githubusercontent.com/548178/31212773-568947bc-a957-11e7-947f-a602bf87c215.png)
