### ISSUE TITLE
Checkin Search - Cursor Not Set in Search Field

### ISSUE THREAD

**Issue by edmistj** [SparkDevNetwork/Rock#2222]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When name search is enabled in check-in the cursor is not placed in the search field when starting the search process

### Steps to Reproduce

1. Enable Name Search
2. Try to check-in someone

**Expected behavior:** 

When entering the search page the cursor should be placed in the search field.

**Actual behavior:** 

Cursor is not set in field and the user must first select it.

### Versions

* **Rock Version:** [1.6.*

* **Client Culture Setting:** [Enter Client Culture here]  
![chrome_2017-05-26_07-10-24](https://cloud.githubusercontent.com/assets/548178/26498037/7c777f3e-41e2-11e7-8722-2052e0e21c9d.png)

**Comment by garrettjohnson** [comment]
@azturner @edmistj I could take this one. Semantically I'd just set both fields to include the `search-input` class to use for the JS hook to focus

**Comment by edmistj** [comment]
@garrettjohnson go for it!
