### ISSUE TITLE
File uploader allows invalid characters in filename

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2227]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The built-in file manager / uploader allows filenames which contain characters that IIS deems invalid. For example the character `&` is not allowed by IIS to be downloaded.  Meaning Rock will let me upload a file called `Shake & Bake.txt` but if I then try to download that file an error is generated.

Reference https://msdn.microsoft.com/en-us/library/system.web.configuration.httpruntimesection.requestpathinvalidcharacters(v=vs.110).aspx for other characters that are not allowed by default: `<,>,*,%,&,:,\`

Oddly enough I guess you can use a `?` in a filename, but not a `&`.

### Steps to Reproduce

1. Rename file on your computer `Shake & Bake.txt`
2. Upload said file to Rock.
3. Try to download file by manually using URL `http://rock.yourdomain.org/Content/Shake & Bake.txt` -> Fail
4. Try to download file by manually using URL `http://rock.yourdomain.org/Content/Shake%20&%20Bake.txt` -> Fail
5. Try to download file by manually using URL `http://rock.yourdomain.org/Content/Shake%20%26%20Bake.txt` -> Fail

**Expected behavior:** 

The file manager should probably have the same "character not allowed" list that IIS has out of the box, or possibly dynamically pull that setting from IIS and throw an error.

**Actual behavior:** 

I can upload and delete a file but download.

### Versions

* **Rock Version:** 6.3
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
What if we stripped the unsupported characters out so no error was thrown?

**Comment by cabal95** [comment]
I would be generally okay with that. I'd be 100% okay with it if a bootstrap alert div could be shown or something to state what happened. I could see users getting frustrated and trying to re-upload a file multiple times before calling I.T. because when they upload `John & Suzy.png` it becomes `John Suzy.png`.

I think `<,>,*,\,%` are probably pretty rare use. But I could see `&,:` being fairly common.  `:` probably getting less so, but even Mac until just a couple years ago used that character in their screenshot filenames as the time separator.  And since `&` is valid on Mac/Windows it's probably pretty common for users to use it instead of `and`.

And by "throw an error" I was meaning do the same thing as when you try to upload a Content File Blacklist file, not specifically throw a full error and blow up. :)

**Comment by edmistj** [comment]
@arranf Are you still working on a fix for this?

**Comment by arranf** [comment]
@edmistj Sorry, didn't get far with this. I got to tracking the filename replace needing to occur to `Rock\Web\UI\Controls\FileUploader.cs` but not much further.
