### ISSUE TITLE
Inconsistent Help & error msg on block Groups Context Setter, Clear Selection Text  

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#2229]
On the Groups Context Setter block, 
the field 'Clear Selection Text' help reads 'The text dispalyed when a group can be unselected. This will not display when the text is empty.'
But if you leave the field empty the page gives an error message 'Please correct the follow *Clear Selection Text is Required.'

Either correct the wording of the Help comment, or allow the field to be empty.

![cleartextmsg](https://cloud.githubusercontent.com/assets/4658177/26652637/a432c512-46a4-11e7-863d-7b4a22f687c6.jpg)

**Comment by mikejed** [comment]
Confirmed this is still present in v8 prealpha
