### ISSUE TITLE
Exception when editing familes since upgrading to 6.4.

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2232]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We are getting exceptions when adding people to families and setting the campus, since moving to 6.4. When saving the family after making changes, the user sees:

Error
94|error|500|An error occurred while executing the command definition. See the inner exception for details.| 

And in the exceptions log there is a corresponding "The wait operation timed out" entry.

### Steps to Reproduce

1. Go to a person and edit the family
2. Add an existing person to the family and tell it to removed them from original family
3. Set or change campus for family
4. Click save, wait, get the error.

Not sure if all of those exact steps are necessary to dupe it but I can reliably reproduce it here doing that.

**Expected behavior:** 

No error is thrown when editing family

**Actual behavior:** 

Can't edit family because of exception.

### Versions

* **Rock Version:** 6.4 (technically it's 6.4beta)
* **Client Culture Setting:** [en-US
![image](https://cloud.githubusercontent.com/assets/3903408/26696391/0bf782e4-46d4-11e7-815f-1512a98688e5.png)

**Comment by JimMichael** [comment]
Could not reproduce on demo site since it's at 6.2

**Comment by edmistj** [comment]
If it helps you're welcome to update the demo server (it'll only last the day though). Appreciate you Jim!!!

**Comment by JimMichael** [comment]
Duh, that never occurred to me. Unfortunately, could not dupe it on demo :-( We're definitely seeing it enough here for end users to notice, so something has changed... but looks like it's gonna be hard to pin down.

**Comment by JimMichael** [comment]
I have been able to verify that it only happens when we try to do multiple changes on the family in one pass, like adding a new person to the family AND changing their campus. We can do either operation by itself, then the other operation by itself without issue.
