### ISSUE TITLE
Content Channel Query Parameter Filtering Fails 

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#2241]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

I was trying to filter Content Items by title, `?Title=Car%20Show` as documented in the CMS guide. 

### Steps to Reproduce

1. Have an install with sample data
2. Enable query parameter filtering for the Content Channel View blocks on the External Site 
3. Add the query string `?Title=Car%20Show` to your URL

**Expected behavior:** 

Only the Car Show content channel item would be shown. 

**Actual behavior:** 

No content channel items are shown.

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting:** en-GB

**Comment by garrettjohnson** [comment]
I tried on the demo site with http://www.rocksolidchurchdemo.com/page/2305?title=SAMPLE:%20Car%20Show and http://www.rocksolidchurchdemo.com/page/2305?title=SAMPLE:%20Warrior%20Youth%20Event and both seem to work. Is it failing with a specific content type?

**Comment by arranf** [comment]
@garrettjohnson You're right that's actually working. I forgot the full title included `SAMPLE:`. I was testing with the campuses attribute and didn't get very far and thought I could reproduce the issue with title. I'll change my original issue to reflect that.
