### ISSUE TITLE
EN: Add functionality in Bulk Update to blank out Giving Group 

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2242]
### Description
As part of a discussion around giving statements, some churches prefer children's giving to not be included with their parent's statement.

While you can create a custom Lava/merge doc to list the child's name with their gift, modifying the Bulk Update tool to blank out a child's Giving Group is an easier option.  Since Bulk Update already prompts multiple times about the risk of changing data, this seems like the best place for this feature.

I think this should only have an option to blank out the Giving Group, although it would be possible (albeit slow) to go the other way - look up and set the giving group to the person's family for everyone in the data set.

I'm welcome to discussion for other options.

**Comment by garrettjohnson** [comment]
We'd be interested in this; our accounting department likes to split kids out after they cross a certain threshold of giving. @dcs619 What do you think should happen with the giving group if a person is in multiple families?

**Comment by dcs619** [comment]
@garrettjohnson The schema only supports one Giving Group per Person, so you/bulk update has to pick one.  That's probably another reason to only enable blanking out the Giving Group via Bulk Update.

**Comment by edmistj** [comment]
@dcs619 To implement this we'd probably want to see the following:

1. A new section (at the bottom) with the title of Financial (fa fa-money)
2. New item labeled 'Mark Individuals as Giving Individually'
3. A new Security Verb on the block of 'Edit Financials' (migration to set 'RSR Financial Administration' and 'RSR Financial Worker' to have access.

**Comment by arranf** [comment]
@dcs619 Are you still tackling this?

**Comment by nairdo** [comment]
Hello amazing community member! We've recently moved 'feature requests' to our own "Ideas" system on our Community site at: http://community.rockrms.com/ideas

If you'd like to re-propose your idea and put it up to the vote, please re-submit your idea there. Thanks!
