### ISSUE TITLE
Workflow attribute of type Data View does not pick up list of Data Views

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#2246]
We send a daily devotion to members of the 'DevotionEmail' group with member status 'Member'.  I don't want to send it to group members with Pending status.  Using a dataview will pick up the right people.  I can create a workflow that emails to everyone in the group if I use a Group attribute type field in the To of the email.  But I can't create a workflow attribute that picks up the dataview in the same way.

1. When adding a Workflow attribute of type Data View, the list of data views does not get picked up, so you cannot select a default.
![dataview](https://user-images.githubusercontent.com/4658177/27029011-b73f58ea-4fba-11e7-96d2-3bd0c4dae24a.jpg)

2. When the Data View attribute displays on a user entry form the drop down does not list any of the data views.

3. The Data View attribute cannot be used as an Email To Attribute Value, in the same way that a Group attribute can be.  It would be great if either a Group or a Dataview could be used to set the recipients of the email.

v6.5

**Comment by garrettjohnson** [comment]
Looks like 7.0 Includes a improved Data View field that allows you to select the Entity Type which filters the list of Data Views. It's live at http://prealpha.rockrms.com
