### ISSUE TITLE
Paste Text button drops line feeds from the text

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#2247]
**Pasting text into a new communication using the Paste Text button drops line feeds.**

So text like this:
"This is line one of text followed by a blank line.

This is line two of text.
This is line three."

...is pasted like this:
"This is line one of text followed by a blank line.This is line two of text.This is line three."

This behavior is consistent with different browsers.

v6.5

**Comment by cabal95** [comment]
Related to #2045

**Comment by ElimAdmin** [comment]
Close this as it duplicates #2045.
