### ISSUE TITLE
[Feature] URL Lava Filter

### ISSUE THREAD

**Issue by edmistj** [SparkDevNetwork/Rock#2252]
Proposing a new Url Lava filter that would take a URL and allow you to get segments back. Internally this would use the URI class to do the heavy lifting.

{{ 'https://www.rockrms.com/registration/RegistrationInstanceId=2' Url:'host' }}

Parms:
host = www.rockrms.com
port = 80
segments = Array['registration']
scheme = https
localpath = /registration
pathandquery = /registration/RegistrationInstanceId=2

One additional parm would take an extra parm
{{ 'https://www.rockrms.com/registration/RegistrationInstanceId=2' Url:'queryparm','RegistrationInstanceId' }}

This would return the value of the querystring key

Open to ideas/suggestions.

**Comment by edmistj** [comment]
@garrettjohnson @cabal95 FYI, open to suggestions.

**Comment by garrettjohnson** [comment]
@edmistj Would it be possible to add a full URL? It would return the full URL, minus the port number if it's using a standard port 80/443.

**Comment by edmistj** [comment]
@garrettjohnson fine with me. In sample lava what would it return? Would it be the same thing passed in?

**Comment by cabal95** [comment]
If I understand what @garrettjohnson was meaning:
http://www.rockrms.com:80/page/122 => http://www.rockrms.com/page/122
http://www.rockrms.com:8000/page/122 => http://www.rockrms.com:8000/page/122
http://www.rockrms.com/page/122 => http://www.rockrms.com/page/122

The specific follow up question for me would that "full url" also include the ?query parameters (I would think so, but making sure).

**Comment by briankalwat** [comment]
@edmistj what were your thoughts on using "scheme" for the param instead of "protocol" (http/https/etc)?

**Comment by edmistj** [comment]
That's just the name the .net runtime calls it. Technically if you are describing a URI it's called a scheme (file:///...)

In the end it's a bit of semantics. I'm open either way.

**Comment by cabal95** [comment]
Okay, so here is some output from the filter. These values are all from the Uri helper. I noticed there were some "oddities" that the average user may not expect that we might want to filter, such as the segments including a trailing `/` if it is not the last segment.

I used `url` as the filter argument to get the "full url". I didn't use `fullurl` as I thought that might lead to confusion about it stripping out the port number when it's not needed. But i'm fine making it `fullurl` if that is a better choice.  `'' | Url:'url'` does look a bit odd.

```
Testing URL https://www.rockrms.com/WorkflowEntry/35?PersonId=2
host - www.rockrms.com
port - 443
segments - [ "/", "WorkflowEntry/", "35" ]
scheme - https
protocol - https
localpath - /WorkflowEntry/35
pathandquery - /WorkflowEntry/35?PersonId=2
queryparam no key -
queryparam with key - 2
url - https://www.rockrms.com/WorkflowEntry/35?PersonId=2

Testing URL https://www.rockrms.com:443/
url - https://www.rockrms.com/

Testing URL http://www.rockrms.com:8000/
url - http://www.rockrms.com:8000/
port - 8000
```

Also @edmistj your example used `queryparm` instead of `queryparam`. Was that intentional or a missed character? I did it with the extra `a` but not sure if that is the way it should be done. I've always spelled as `param` but that might just be personal preference.

**Comment by edmistj** [comment]
@cabal95  Looks good. Let me get back to you on `parm` vs `param`. I always use `parm` but I should get input from the full team on a standard. After doing a little searching I've found that I'm a ['scourge of society'](http://discuss.fogcreek.com/joelonsoftware4/default.asp?cmd=show&ixPost=129178) according to Joel Spolsky.  I do feel better though that the Apple II Applesoft Basic manual also uses `parm`.

**Comment by cabal95** [comment]
You must have worked at IBM in a past life ;)

**Comment by arranf** [comment]
@edmistj I always thought you just used parm because of some keyword conflict. Didn't realise there was an actual debate raging!

**Comment by edmistj** [comment]
@arranf I didn't know of any debate, just what I always did. Not sure where it came from (guess I'm too old to remember).

**Comment by edmistj** [comment]
@cabal95 let's solve this by not abbreviating it. So `queryparameter`. That allows the debate to continue.
