### ISSUE TITLE
Rock shop shows no purchases

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2253]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When we browse to the Rock shop and click the Purchases link, it says there are no purchases for this org.

### Steps to Reproduce

1. Go to Rock shop from my Rock instance
2. Click the Purchases link
3. Get incorrect message there are no purchases for this org, when we have at least 3, one as recent as 6/6/2017

**Expected behavior:** 

Accurately show past purchases

**Actual behavior:** 

It lies

### Versions

* **Rock Version:** 6.5
* **Client Culture Setting:** en-us

**Comment by azturner** [comment]
@JimMichael , this should be resolved. Do your purchases now show correctly?

**Comment by JimMichael** [comment]
Yes, thank you!
