### ISSUE TITLE
Prayer Request Detail Block - Prayer Category does not show selected default

### ISSUE THREAD

**Issue by alyssa-pathway** [SparkDevNetwork/Rock#2254]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

I have a Prayer Request Detail block, in the block settings I select a default category (top level or child) but when I save and refresh there is no default category selected and in fact I see all categories in the drop-down selector.

### Steps to Reproduce

1. Create new page
2. add "Prayer Request Detail" block
3. Edit Block Settings
4. Select "Default Category"
5. Save and Refresh

**Expected behavior:** 

I expected to have the selected default category populate the category field in the block upon each prayer entry.

**Actual behavior:** 

Even though I have a default category selected, nothing is auto-populated in the category field on entry.

### Versions

* **Rock Version:** 6.3
* **Client Culture Setting:** en-us

**Comment by garrettjohnson** [comment]
Confirmed in 6.8

**Comment by arranf** [comment]
Digging into this it looks like there was an intention change as to what a default category would should do at some point. Currently if the category is not set by the requester the default category will be set during the save step but the category picker is set as required.

I'm going to fix this to follow the pattern used by other blocks of auto-populating the field using the block setting.
