### ISSUE TITLE
[EN] Add BatchId to Move Transactions to Batch drop down list

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2256]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When dealing with a larger number of open batches it can be confusing to find the correct batch. Including the Batch Id number would be helpful. Additionally, when entering batches for checks from the weekend we often have many batches with the same name / date.

Currently it displays the batches as `Event Registration VMD (6/8/2017)`. Proposing it be changed to show using this syntax: `Event Registration VMD (6/8/2017, #1234)`

### Versions

* **Rock Version:** 6.3
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
This sounds like a good idea, but I think the number should be first:
#1234 Event Registration VMD (6/8/2017)

**Comment by cabal95** [comment]
@edmistj Currently this drop down list is ordered by Name (ascending). Would it make sense to change the ordering to the batch Id (ascending) as well, since that would then be first in the text?

**Comment by edmistj** [comment]
@cabal95 That would be the way I'd prefer it. The start of batch names are pretty common. Having them in order by Batch ID would seem to make sense.
