### ISSUE TITLE
Check-in Manager keeps redirecting back to type selection

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#2258]
If check-in groups have a parent group that is not the same type, the check-in configuration will still show the groups for editing, however, the check-in manager app will not display the groups. If all the groups have parents with a different group type, the check-in manager will just redirect back to the check-in type selection page.

This is only possible if editing the group structure outside of the check-in configuration (i.e. group tree)

**Comment by arranf** [comment]
Still confirmed as of 2018-06-18

**Comment by azturner** [comment]
Closing this because it's so old and haven't encountered this issue since.
