### ISSUE TITLE
Core check-in displays the address of a Location instead of its name

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2259]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you have a Location with an address and check-in to that Location, the app will display the Location's address instead of its name. 

### Steps to Reproduce

1. Check in to a location that has an address (eg. a Campus)
2. Observe that the checked-in page shows the full address of the location instead of "Location Name"

**Expected behavior:** 

Name of Location checked-into would be shown

**Actual behavior:** 

Address of location is shown

### Versions

* **Rock Version:** 6.5 and all prior
* **Client Culture Setting:** en-US
![image](https://user-images.githubusercontent.com/3903408/27189095-eda9e6be-51b5-11e7-885f-39e300468328.png)

**Comment by mr9802** [comment]
Any Update on this issue or a fix to test?

**Comment by arranf** [comment]
Still confirmed as of 7.4
