### ISSUE TITLE
All blog page 'Read more' links go to one article

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#2262]
All 'Read More' links from items on the blog page (http://rock.rocksolidchurchdemo.com/page/2306) go through to the same article.  The links should go through to the unique blog article for each link.

This also happens on our site (v6.5).

**Comment by edmistj** [comment]
Hey Ken! This is caused by in invalid setting on the details page. It's caching the block contents so it doesn't read the new value from the database. We'll put in a migration to change that block setting for the external site.

**Comment by azturner** [comment]
Fixed here: https://github.com/SparkDevNetwork/Rock/commit/17b9f7315e621b57aaf86d696c58d317da37d90d

**Comment by arranf** [comment]
Fixed as above.
