### ISSUE TITLE
Pledges on contribution lava statement display incorrectly

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2263]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The ContributionStatementLava block currently only displays a pledge summary if the pledge start year is equal to the statement year or if the pledge end year is equal to the statement year.  In other words, If I have a 3 year pledge (1/1/2016 - 12/31/2018), then when I run the statement for 2016 or 2018 the pledge summary will show. But when I run the statement for 2017 it will *not* show the pledge summary.

Additionally, when calculating the amount given towards a pledge, any gifts after the pledge start date are considered. Including gifts after the statement year ends (or the current date, in case something has been recorded in the future). This means that, for example, when running contribution statements in late January or into February, the pledge summary may not be accurate as it could include gifts in January even though they do not show up on the statement. Suggestion is to limit the gifts considered for pledge `Amount Given` calculation to be only those after the pledge start date AND before the statementYear end date. Also to reduce confusion for the end-user update the text of the pledge summary to say "as of {date}".

These things have been fixed in our local version but want to verify the fix with others before creating a pull request. Also not sure how this impacts the statement generator. A number of changes have been made to the Lava version recently and I don't know if the fat-app generator is up to date.

@JimMichael @jeremyhoff

<img alt="sample contrib statement" src="https://user-images.githubusercontent.com/1119863/27235435-b484b89e-5275-11e7-8edd-a098f84b4066.png">

### Steps to Reproduce

1. Create a pledge that spans at least 3 years.
2. Put gifts in all three years.
3. Run the statement for all 3 years (one at a time).
4. Observe the differences.

**Expected behavior:** 

Pledge summary should show up all statement years the pledge is active.

**Actual behavior:** 

Pledge vanishes in a puff of green tinged smoke on in-between years.

### Versions

* **Rock Version:** 6.3
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@cabal95 the statement generator does not show pledge info. If you have a fix for this send over the PR.

**Comment by cabal95** [comment]
Thanks for the reminder. I'll see if I can get to this this week. If memory serves the fix wasn't too complex.
