### ISSUE TITLE
Sortable/Alphabetical Order for Group Types

### ISSUE THREAD

**Issue by mrskatiewalters** [SparkDevNetwork/Rock#2266]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Allow Group Types to be viewed alphabetically. This is an ongoing issue. Our list is substantially long and is not sortable. We have 98 Group Types already and we need this to be viewed alphabetically.

**Expected behavior:** 

We expect a way to sort the Group Type list in order to find the correct Group Type from the list.

**Actual behavior:** 

We have a large list of Group Types that are in random order.

**Comment by edmistj** [comment]
Note, group types have an implied (and changeable) order. We'd want to return them in this order and it may have logic to it. If you'd like you could put them in alpha order.
