### ISSUE TITLE
Deleting a Registrant record doesn't delete attribute value

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#2272]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Not exactly a bug or issue but I noticed when a registrant is deleted from a registration the registration attribute(s) for that registrant aren't removed from the AttributeValue table. Not certain if removing the registrant's attribute values when the registrant is removed should occur or if leaving it the way it is is fine.

Just thought I'd mention it.

### Versions

* **Rock Version:** 6.5

**Comment by dcs619** [comment]
Think this is a known issue (#1776), any attributes added to entities won't be deleted when the entity is deleted.
