### ISSUE TITLE
Check-In Admin screen does not show OK button on most android devices

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#2283]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
We are using android tablets as our check-in kiosks. When we go to the admin screen, the OK button is not displayed anywhere. Only the Flat theme shows it. On an android phone the button does show up half-cut-off at the bottom, but when request the desktop site (on both android phones and tablets) it does not display at all.

It does look fine on iPads and chromebases.

### Versions
* **Rock Version:** Rock McKinley 7.0
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@chrismcgrath I think these can all be solved with a custom check-in theme for Willow that is styled to work with your specific device. While we can work to make the core ones more flexible in the future we've found that each Android device type is different so it's hard to get them all styled correctly.

**Comment by jonedmiston** [comment]
Closing based on age. Have not heard any other reports of this. Please re-open if you think this is still an issue.
