### ISSUE TITLE
Cannot use the default date of "current" when creating a Group Attribute with a type of datetime.

### ISSUE THREAD

**Issue by mrskatiewalters** [SparkDevNetwork/Rock#2285]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When we created the ‘group start date’ group attribute, we set the start date to be “current” by default. The Rock UI lists “current” as a checkbox, but does not populate an actual date. This threw an error. The workaround for now is to leave the “current” box unchecked and simply select “today” as the value when creating a group.

### Steps to Reproduce

1. Create the ‘group start date’ group attribute, set the start date to be “current” by default
2. Rock UI lists “current” as a checkbox, but does not populate an actual date
3. This threw an error.

**Expected behavior:** 

When you choose current as default it would automatically choose today's date.

**Actual behavior:** 

Does not populate an actual date and throws an error.

**Work around:**

The workaround for now is to leave the “current” box unchecked and simply select “today” as the value when creating a group.

### Versions

* **Rock Version:** 6.5

**Comment by MikeDPeterson** [comment]
Note: to reproduce this, the Attribute needs to be marked as Required.  Then when you attempt to edit and save the group, a validation error will be displayed even though you have 'current date' selected
