### ISSUE TITLE
No 'Pending' identification when viewing person records

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2289]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When viewing a person record, there is no indication that the record is Pending. I believe we should have a label similar to the `Inactive` label that shows up. Perhaps a warning label instead? Mockup screenshot attached.

<img width="648" alt="screen shot 2017-06-29 at 3 12 39 pm" src="https://user-images.githubusercontent.com/1119863/27712810-8b4f39f0-5cdd-11e7-844b-eaea3ed4bcc5.png">

### Steps to Reproduce

1. Make Ted Decker Pending
2. View Ted Decker.

**Expected behavior:** 

I should be able to tell the status of a person's record without having to edit the record.

**Actual behavior:** 

I must edit the record to know if it is Active or Pending.

### Versions

* **Rock Version:** 6.3
* **Client Culture Setting:** en-US

**Comment by azturner** [comment]
Updated here: https://github.com/SparkDevNetwork/Rock/commit/45addce0b1d27fe8fe043719305902448f484215#diff-f9dd190cd073670d98388ea34b69a496R62
