### ISSUE TITLE
Defined Type list shows as id instead of friendly names on report or dynamic report

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#2295]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

I have created a list of staff and created a defined type list of teams staff serve on. When showing those teams on data report or dynamic report it shows the id numbers of those team instead of a friendly name. Only when there is more than one team though. See screenshot: https://www.evernote.com/l/AAJI0n0jzzhJSYjKyFMzH0yA5MwLLRoag-E

### Steps to Reproduce

1. create person attribute of ministry teams
2. add as defined type list of a few different ministry teams
3. Check multiple teams for a person
4. create a data view showing anyone on those teams
5. create a report with that column displaying
6. Report should be showing id's instead of friendly names

**Expected behavior:** 

the team names would be displayed such as: pastor, communications team, Leadership team.

**Actual behavior:** 

instead of "friendly names" it shows, 7eaacf84-3dd6-476a-9c51-78fc4f8fcae8,499fa357-c229-4e85-b4a9-179b1ea302d4,cdf6e938-a13f-4a64-9de7-05b29acc42b4

### Versions

* **Rock Version:** Rock McKinley 6.6 
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
@timlem Could you attach a screenshot of how you setup the Attribute in steps 1 and 2? There are a number of options in there and it will help tracking this down if we are 100% sure we have set it up the same way you did.

**Comment by timlem** [comment]
- https://www.dropbox.com/s/rewssqkan01pr44/Screenshot%202017-07-03%2022.15.02.png?dl=0

- https://www.dropbox.com/s/jbpnatunkbhtenv/Screenshot%202017-07-03%2022.15.31.png?dl=0

- https://www.dropbox.com/s/8p06lp1voah200j/Screenshot%202017-07-03%2022.16.33.png?dl=0

Do these three cover it or did I miss something?

**Comment by cabal95** [comment]
That should work. Thanks.

BTW you can also just drag the images into the github text editor and it will embed/attach them that way too.

**Comment by timlem** [comment]
Should I do something to *Bump* this? Coming up on a year now. :)

**Comment by edmistj** [comment]
I set the milestone to v8
