### ISSUE TITLE
Unhandled Date filter formats

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#2296]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

rockrms.com/lava implies that date filters at https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings should work in Lava.

However, even though milliseconds can be retrieved using SQL, the 'f' and 'F' formats do not resolve correctly in Lava.

### Steps to Reproduce

In an HTML block, add the following content:
```
{{ 'Now' | Date:'HH:mm:ss.fff' }}<br />
{{ 'Now' | Date:'HH:mm:ss.FFF' }}
```

**Expected behavior:** 

It should output something similar to
```
13:34:49.120
13:34:49.12
```
**Actual behavior:** 

It outputs something similar to
```
13:34:49.000
13:34:49
```
So it appears to understand what it's supposed to display (F truncates trailing zeros), but perhaps the precise timestamp is not actually provided to Lava to interpret. This is an issue because you can't use Lava in SQL to compare something like `WHERE [StartDateTime]= {{ LavaTimestamp | Date: 'yyyy-MM-dd HH:mm:ss.fff' }}` since the output wouldn't match the value in SQL (which stores thousandths of a second)

### Versions

* **Rock Version:** 6.6  
* **Client Culture Setting:** EN-US

**Comment by cabal95** [comment]
Just to add a comment, I would actually not use milliseconds as part of your comparison at all (not saying this shouldn't be fixed too).  Entity Framework seems to create SQL datetime values as `datetime`, even though `datetime2` is the "new" format that it should use (so says Microsoft). If EF is updated in the future to create `datetime2` like it is supposed to, _or_ somebody manually changes the precision, then you will suddenly end up with 7 digit precision in SQL.  Also a future SQL update could just decide to change the default precision of `datetime`.
