### ISSUE TITLE
[EN] Add capability to inactivate a device

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2297]
### Prerequisites

As devices reach end of life, it would be nice to distinguish those that are being phased out. 
 However, once a device has attendance attached to it, we don't want to lose that attendance.

### Description

Add an `IsActive` column to the Device table and a Filter option to display [All, Active, Inactive].  

I can do a PR for the code change but would require a migration rollup since correct EF migrations through PR's are virtually impossible.

┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;826629834724535">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;829309600715981">DeviceList.JPG</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;829309600715983">DeviceDetail.JPG</a>

**Comment by edmistj** [comment]
@dcs619 Adding this field is good. If you could make a PR with the edited blocks and a text file containing the contents of the Migration we'll create a new core migration from it. The block changes should include:

Device List 
+ Filter to show/hide inactive devices. The default should be to hide inactive devices

Device Details
+ Ability to activate/inactivate devices. The inactive checkbox should be in the standard location to the right of the name field (column 2).
+ Also inactive devices should have a label in the heading much like an inactive group would.

**Comment by nairdo** [comment]
Fixed via bfef67d4901b89d85c26ea94598457bd7d683042 and via c5ebdc6a54630b9bf98cf4c503734a36ac00fc9e.
