### ISSUE TITLE
Enhancement - Registration Instance Details Block - Fees Column

### ISSUE THREAD

**Issue by rutledgek** [SparkDevNetwork/Rock#2299]
An enhancement to the Registration Instance Details Block Fees Column under Registrants. If there is a fee with options it would be more helpful to see the option selected than the fee name.  

I.e.  I am less interested in knowing they chose a T-Shirt and more interested in seeing at a glance what t-shirt size they selected.  Right now I had to create a merge document listing the same information already in the columns but listing the option instead of the name.

**Comment by arranf** [comment]
These are now visible from the 'Fees' tab on a registration detail.
