### ISSUE TITLE
Page routes with a forward slash act... weird

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2300]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Page Routes UI on Page Properties lets you enter a route like /myroute, but this results in a non-functional route, even though the database shows a valid route in the SQL record.

### Steps to Reproduce

1. Open the properties of a page and create a route to /myroute, then save.
2. Navigate to yourrockserver/myroute and you will get a 404.
3. Edit the route and observe that it now shows _myroute_ sans slash. Save it, try to get to yourrockserver/myroute again, and it still fails.
4. Edit the route again and REMOVE it, then save, then re-add a correct route of _myroute_ (no slash).
5. Browse to yourrockserver/myroute and it works as expected.

**Expected behavior:** 

UI should either prevent use of preceding slash, or strip them appropriately so the route works.

**Actual behavior:** 

Adding a route with a preceding slash causes weird behavior. Observing two routes (one added without a slash, the other added with) create identical-looking records in the db, but the one that was created with the slash is non-functional. In the attached image, _danieltest_ was added without a slash, and works. _danieltest2_ was added with a preceding slash, and fails, though the slash is nowhere to be seen in the record. Furthermore, once a route is added with a slash via the UI and saved, editing it again shows NO slash, yet you have a non-functional route that _looks_ correct and the only way to fix is to remove it, save, then re-add it.

### Versions

* **Rock Version:** 6.5

<img width="1212" alt="screen shot 2017-07-06 at 10 13 49 am" src="https://user-images.githubusercontent.com/3903408/27932309-f44b4dba-6262-11e7-82e6-6544d998be32.png">

**Comment by cabal95** [comment]
Just to add clarity to the image (I gave it to Jim) since I just realized I never named that `Column `. That column is basically a Hex representation of the `Route` column.  I think it must have converted it as a UTF-16 string, hence all the extra zero's.  But that was to show that there weren't any non-printable characters present in the non working route.

**Comment by arranf** [comment]
This seems to have been fixed in the past at some point. 🙌
