### ISSUE TITLE
NMI Gateway does not set card type

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2303]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When creating a transaction with the NMI gateway the card type is never set. 

**Proposed Solution**
Card type could be set using the RegEx from the Credit Card Type defined values. This would require modifying the RegEx to allow for `*` values in the place of digits 7-12 i.e. `424242******4242` or replacing the `*` characters with `0`s before running the existing RegEx.

### Steps to Reproduce

1. Create a contribution/scheduled transaction with the NMI gateway

**Expected behavior:** 

Card type is set using the partial returned credit card number 

**Actual behavior:** 

No card type is set

### Versions

* **Rock Version:** 6.7  
* **Client Culture Setting:** en-US

**Comment by taylorbrooks** [comment]
Was this fixed in v7?

I see this in the [release notes](https://www.rockrms.com/releasenotes#v7.0)

> Fixed an issue with NMI transactions being saved without a credit card type.

**Comment by garrettjohnson** [comment]
Can confirm it's fixed in v7. Nice catch
