### ISSUE TITLE
Cannot disable existing signature documents to cancel existing invites

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2309]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The current Process Signature Documents job re-sends invites based on the document having an `InviteCount < MaxInviteCount` and `Status != Signed`. This means the only way to cancel a document signing invite is to use SQL to set the `InviteCount` to be > `MaxInviteCount`.

Use case: We had an event on July 4th that we had volunteers sign a document for. Some people (many) signed up just a few days before the event and never signed the document. Now that the event is passed the system is still sending them requests to sign a document for an event that is already past.

### Steps to Reproduce

1. Create Signature Document template.
2. Invite someone to sign the document via e-mail.
3. Try and cancel the invite.

**Expected behavior:** 

I should be able to "expire" or "cancel" an invite via the GUI. In our case I would like to do this in bulk since we had over 200 invites to cancel. Currently the only way to do this in the GUI is to delete them, but I would rather have the historic data in there that people did not sign the documents.

**Actual behavior:** 

Rock re-enables the documents even if you manually set them to expired or cancelled in the GUI.

### Versions

* **Rock Version:** 6.3
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Closing this as we are re-writing the digital signatures features to be core to Rock. The feature set will be rewritten from scratch at that time.
