### ISSUE TITLE
Typo in eRA badge Tooltip (stock Rock install)

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2311]
### Description

The tooltip in the eRA badge says "become" when it should say "became"

### Steps to Reproduce

https://github.com/SparkDevNetwork/Rock/blob/1928822b6a4e92ff327b6a070b18f7f80fca7717/Rock.Migrations/Migrations/Version%205.0/Version%201.5.0/201603142139542_FamilyAnalytics.cs#L102

Can verify on demo site, but no need since it's in source code.
http://rock.rocksolidchurchdemo.com/page/265?PersonBadgeId=1014

**Comment by edmistj** [comment]
A migration has been added to correct this. Will be fixed in v6.10.
