### ISSUE TITLE
Content Channel Detail block shows extra item columns

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2312]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The columns displayed for listing a content channel's items contains extra columns that should not be there.

1) Two `Expire` columns are visible. One looks like it is supposed to only show up when times are not included.
2) Priority still shows even if the content channel type has been set to disable priority.

![image](https://user-images.githubusercontent.com/1119863/28043302-1fa789a8-6586-11e7-91b8-80fc77d7c100.png)

### Steps to Reproduce

1. Create new Content Channel Type with `Date Range Type == Date Range` and `Include Time == Yes` and `Disable Priority == Yes`.
2. Create Content Channel of that type.
3. Create Content Channel Item in channel, then view list of items.

**Expected behavior:** 

Priority should be hidden since it is disabled. Also the extra expire column should be hidden.

**Actual behavior:** 

_I see dead columns._

### Versions

* **Rock Version:** 6.3 (production) and 6.7 (demo site)
* **Client Culture Setting:** en-US

**Comment by azturner** [comment]
Fixed here: https://github.com/SparkDevNetwork/Rock/commit/bd506d07
