### ISSUE TITLE
Truncate masked credit card numbers to last 4 digits

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2319]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

While Rock's storage of the first 6 and last 4 digits of cards in the clear is allowed per PCI, we've been informed that "printing" the first six digits of the card on receipts and confirmations actually breaks [FACTA](https://en.wikipedia.org/wiki/Fair_and_Accurate_Credit_Transactions_Act). A federal law which only allows for printing of the last 5 digits of a card. 

While cases for ecommerce have never resulted in a consistent legal decision, we've been advised that any page our staff might use as a printed receipt should mask everything but the last four.

**Expected behavior:** 

Rock should continue to store the PCI compliant expanded card number. But lava calls and all locations where AccountNumberMasked is returned should default to masking everything but the last four. 

**Actual behavior:** 

First 6 digits and last 4 digits are displayed.

### Versions

* **Rock Version:** 6.7  
* **Client Culture Setting:** en-US

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/8f475a5a90e3f2acfa6aa48a52ddf66b42faa691, and there will be a migration to re-mask any accountnumbermask values that have already been stored
