### ISSUE TITLE
[EN] Streamline Fundraising Donation Entry

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2327]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We would like to streamline the Fundraising Donation Entry block a little bit. When the GroupId is passed in via the QueryString the only thing you do on this block is pick the participant to donate to, and then get redirected to another page. For opportunities that have a single (active) participant and are _not_ linked to a registration instance, we would like for this block to automatically redirect the user as if they had selected the participant.

In programming terms:
If `GroupId Is Set` and `Group.RegistrationInstance Is Null` and `Group.Participants.Count == 1` and `Group.Members[0].RecordStatus = Active` then Redirect.

Cases that would cause the block _not_ to redirect:
* GroupId not set in QueryString (user has to pick, original functionality remains)
* More than one Group Member with the `Participant` role
* Single `Participant` is not `Active`
* Probably others, just some specific examples.

To ensure 100% backwards compatibility this should probably be made into a block setting called `Allow Automatic Selection` or something.

Edit: totally forgot the screenshot.

![image](https://user-images.githubusercontent.com/1119863/28232033-6977d310-68a3-11e7-9243-6b0fc1d1b254.png)

### Versions

* **Rock Version:** 6.3
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
I think this is a good addition. I see how it could be of value.
