### ISSUE TITLE
[EN] Add a "Donate Button Text" attribute to Opportunity Type Defined Values

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2328]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Will add new Attribute to the Opportunity Type Defined Values of `Donate Button Text`. This will allow the admin to override the text on the contribute button as some opportunities need different text. If not set then the default value of `Donate to a Participant` is used.

For example, when working with a Project opportunity type, you are probably not donating to any "participants" (per say) but to the project as a whole.

![image](https://user-images.githubusercontent.com/1119863/28231990-2f0e6d9c-68a3-11e7-8cf7-826c4ccb7668.png)

### Versions

* **Rock Version:** 6.3
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
👍
