### ISSUE TITLE
[Consistency] FinancialTransactionDetails Patch Requires Strict JSON, Other Endpoints Don't

### ISSUE THREAD

**Issue by taylorbrooks** [SparkDevNetwork/Rock#2329]
### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

Any patch request to `FinancialTransactionDetails/{id}` returns a 400 response with "No values were sent in the body" message.

### Steps to Reproduce ###

1. Make a PATCH request with {"AccountId": 2} as the body to: [http://rock.rocksolidchurchdemo.com/api/FinancialTransactionDetails/356](http://rock.rocksolidchurchdemo.com/api/FinancialTransactionDetails/356)

**Expected behavior:**

204 No content response with the an updated AccountId on that resource

**Actual behavior:**

400 response with "No values were sent in the body" as a message.

### Versions ###

* **Rock Version:** Rock McKinley 6.2
* **Client Culture Setting:** en-US

**Comment by dcs619** [comment]
You might need to send it with strict JSON:  `{ "AccountId" : "2" }`.  I just tried it and Rock patched successfully.

**Comment by taylorbrooks** [comment]
Yep, that worked for me too. 

In that case, I think the `FinancialTransactions/{id}` PATCH behaves differently.

**Comment by arranf** [comment]
@taylorbrooks Is this a consistency issue?

**Comment by taylorbrooks** [comment]
Yep, consistency is the issue.

**Comment by arranf** [comment]
This seems to be an issue in codegenerated code.

**Comment by jonedmiston** [comment]
@taylorbrooks can you update this issue with more details on the consistency issue now that the original issue has been addressed.

**Comment by taylorbrooks** [comment]
I'm good to close this if the original issue has been addressed.
