### ISSUE TITLE
Check-in completely breaks and chews up CPU when attendance codes are exhausted.

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2330]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

HDC discovered this little nugget. They had changed their attendance code length to 2 characters, alpha only. To an average user that would mean 676 (26 * 26) possible codes. But since only 17 characters are available for alpha use, that limits them to 289 possible codes.

What visually happened is that after selecting the people to check-in and tapping the Next button, the screen would sit there for awhile and then eventually go back to the welcome screen. What was happening behind the scenes is that IIS would spike to 100% CPU and stay that way until the request timed out and killed off the thread.

Now for the bug. There are two places in AttendanceCodeService that use a `while` loop with no last-resort escape.

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/AttendanceCodeService.Partial.cs#L122
https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/AttendanceCodeService.Partial.cs#L136

Both of these while loops can go on forever if all possible codes have been used. Suggested fix would be a Stopwatch that throws an error after say 5 seconds. At the very least this way an exception would be recorded in the exception log saying what the problem is.

### Steps to Reproduce

1. Set check-in code length/type to alpha only 1 character length.
2. Check-in 17 kids.
3. Try to check-in number 18 and watch IIS twitch uncontrollably.

**Expected behavior:** 

An error should be reported rather than silently breaking.

**Actual behavior:** 

People state dumbfounded at the screen while staff scrambles to start manually check-in kids in.

### Versions

* **Rock Version:** 6.6
* **Client Culture Setting:** en-US

**Comment by arranf** [comment]
I think a long term fix for this could include some sort of warning about the number of possible attendance codes.

**Comment by arranf** [comment]
@dcs619 Is this something you're still working on?

**Comment by chrismcgrath** [comment]
This issue was addressed and possibly fixed by @nairdo in https://github.com/SparkDevNetwork/Rock/commit/7d864d706756ab9deb17249a871e337d73b0bb49
