### ISSUE TITLE
Payment Info Block Disappears When switching to NMI

### ISSUE THREAD

**Issue by DaveRiner** [SparkDevNetwork/Rock#2338]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? No
    * Did you include your Rock version number and [client culture] Yes (https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues? Yes q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

[Description of the bug or feature. Include screenshots if applicable.]

On the Give Now screen, when the Gateway is set to Test, the Payment Information shows up and you can enter credit card info.  However, when the Gateway is changed to our new NMI account, the Payment Information portion of the form disappears.

![image](https://user-images.githubusercontent.com/30246151/28291833-cb6ab1b2-6b11-11e7-9d93-974c33776aef.png)

### Steps to Reproduce

1. [First Step]  Go to Settings on Contribution Block of Give Now page.  Set Credit Card Gateway and ACH Gateway on Contribution Block of Give Now page to Test Gateway.  
2. [Second Step]  Go to Give Now page.  See Payment Information portion of form, including text box to enter credit card info.
3. [Third Step]  Go to Settings on Contribution Block of Give Now page.  Set Credit Card Gateway and ACH Gateway on Contribution Block of Give Now page to Network Merchants (NMI). 
4. [Fourth Step] Go to Give Now page.  Payment Information portion of form (at the bottom) has disappeared,

**Expected behavior:** 

I expect to be able to use the NMI gateway by seeing the Payment Information part of the form.

**Actual behavior:** 

The Payment Information part of the form is unavailable because it is missing.  I did View Source, and it seems to be there.  But it is not visible.

### Versions

* **Rock Version:** 6.5
* **Client Culture Setting:** neutral

**Comment by garrettjohnson** [comment]
@DaveRiner The page break is due to the way Rock Validates and NMI requests credit card numbers, the payment block is visible on the next screen.

**Comment by DaveRiner** [comment]
Wow Garrett that's pretty easy.  I should have been more curious.  Thanks so much for helping me.  I really appreciate it!

I'm new to Rock and wondered if there is a set of screens that would allow one screen plus a confirmation box instead of three screens to make a gift?  A little worried that the double first screen and the third confirmations screen might discourage or confuse following thru.  I know this is off topic.

Thanks for your help, Garrett!  Dave

**Comment by garrettjohnson** [comment]
@DaveRiner Glad to help! I'm working on some code that might get NMI back down to two pages. The user experience is something we're all keenly aware of, and I'm inclined to agree the fewer pages the better! 

And Welcome to Rock! 🎉 Feel free to join the community on [Slack](https://www.rockrms.com/slack) and on [Ask Rock](https://www.rockrms.com/Rock/Ask)
