### ISSUE TITLE
Rename Credit Card # to Card Number on payment forms

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2342]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Currently Rock uses the label "Credit Card #" and "Credit Card" for debit/credit card based transactions. To encourage people to give and pay with other means, as well as accommodate  organizations that only accept debit cards switching the labels from "Credit Card #" => "Card Number" and selection labels from "Credit Card" => "Card" would improve the payment experience.

**Expected behavior:** 

<img width="863" alt="screen shot 2017-07-18 at 11 52 51 am" src="https://user-images.githubusercontent.com/374209/28334339-aca7b998-6baf-11e7-888b-8d10039c64af.png">

**Actual behavior:** 

<img width="858" alt="screen shot 2017-07-18 at 11 53 45 am" src="https://user-images.githubusercontent.com/374209/28334380-c8f101a4-6baf-11e7-9d13-96f99f30dae3.png">

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@garrettjohnson we're good with this if you want to make a PR.

**Comment by garrettjohnson** [comment]
@edmistj Will do. While I'm at it, what do you think of going from "Routing #" to "Routing Number" and "Account #" to "Account Number"?

**Comment by edmistj** [comment]
Sounds consistent.
