### ISSUE TITLE
Rock:ButtonDropDownList always renders icon space

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2344]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The `Rock:ButtonDropDownList` always renders a blank icon `<i>` even when the SelectionStyle is not Checkmark. This ends up offsetting the label even on the title.

### Steps to Reproduce

1. Find a page with the `Rock:ButtonDropDownList` Component ([Giving Page](www.rocksolidchurchdemo.com/page/186) Frequency and Add Another Account)

**Expected behavior:** 
Should be:
![screenshot 2017-07-18 14 36 11](https://user-images.githubusercontent.com/374209/28341010-bcd1c13a-6bc6-11e7-8e6e-6594fbeadaa4.png)

**Actual behavior:** 

From the Rock Control Gallery, the offset is caused by `<i class="js-selectionicon fa fa-fw "></i>` in the dropdown
![screenshot 2017-07-18 14 35 13](https://user-images.githubusercontent.com/374209/28340921-591de33a-6bc6-11e7-926f-7fb3bd0c5f82.png)

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Just to add a note related to this control, this control also ignores `Enabled="false"`.
