### ISSUE TITLE
[EN] Registrant count related event registration improvements

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2346]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
**Add a minimum registrants to registration template.** For couples events, like a marriage retreat, you need to force a minimum number to prevent people from underpaying or forcing two names into the first/last name field. When the max and min values equal each other, the registration would automatically skip the `HowMany` screen.

**Add a registrant count query variable** When the query variable is specified, it would skip the `HowMany` screen.

**Discount Code Query Variable** With improvements coming in V7, the ability to set a discount code via query variable (and then distribute via shortlink) would be awesome.

### Versions
* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Hello amazing community member! We've recently moved 'feature requests' to our own "Ideas" system on our Community site at: http://community.rockrms.com/ideas

If you'd like to re-propose your idea and put it up to the vote, please re-submit your idea there. Thanks!
