### ISSUE TITLE
Tag Categories in Bulk Update are reversed

### ISSUE THREAD

**Issue by kyeschung** [SparkDevNetwork/Rock#2347]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When you go bulk update in a group and try to add a Tag, the Tag Categories (Personal and Organizational) are reversed. The first should be labeled "Organizational Tags" and the second should be labeled "Personal Tags".

### Steps to Reproduce

1. Go to a group
2. Hit the bulk update icon
3. Scroll to bottom to add a tag

**Expected behavior:** 

The first should be labeled "Organizational Tags" and the second should be labeled "Personal Tags".

**Actual behavior:** 

The first is labeled "Personal Tags" and the second should be labeled "Organizational Tags".

### Versions

* **Rock Version:** Rock McKinley 6.8
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
![image](https://user-images.githubusercontent.com/1119863/28344962-de477a98-6bdb-11e7-9923-0d8d08aaf662.png)

**Comment by edmistj** [comment]
Christ Fellowship found this too. Ironic that it's been there for so long and then every finds it at once.

**Comment by garrettjohnson** [comment]
Looks like it's fixed in 6.9. https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.6.9/RockWeb/Blocks/Crm/BulkUpdate.ascx.cs#L94
