### ISSUE TITLE
Cannot sort on Person Attribute in Entity Command

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2356]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Lava docs state 

_The 'sort' parameter does exactly what you'd think it would do. It orders the results by the fields you define (fields are delimited by a comma). These fields can consist of either entity properties or attributes._
 
but all attempts to sort by an *attribute* fail for me (properties work just fine.)

### Steps to Reproduce

1. Enter this simple Lava into the tester or a html block with entity commands enabled (using _Position_ attribute here to limit results and because it exists on all Rock installs)

```
{% person where:'Position _! ""' sort:'Position' %}
    {% for person in personItems %}
        {{ person.FullName }}<br />
    {% endfor %}
{% endperson %}
```

2. Observe the error thrown: `Liquid error: The specified LINQ expression contains references to queries that are associated with different contexts.`

3. Switch the sort to a property (like NickName or Email), and it works. 

**Expected behavior:** 

Sorting would work for attributes

**Actual behavior:** 

Sorting by attributes It bloweth upeth, regardless of which attribute you choose to sort by.

### Versions

* **Rock Version:** 6.8

**Comment by NuclearTacos** [comment]
Replicated on 6.5.  I understood the command to work the way Jim does.

**Comment by briankalwat** [comment]
Replicated on 7.0 (1.7.0.33).
