### ISSUE TITLE
[EN] Pre-population of data in TransactionEntry block

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2359]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Recently the ability was added to TransactionEntry block to be able to specify the accounts via the URL. We would like to expand this ability to specify a default amount for each account as well. Use case would be pre-filled in donation form from another page that has various "donation tiers" that they can click to to give at that tier. The values from the URL would not be enforced but would be the default value if the user does not change.

Plan to add functionality to both the `AccountIds` and `AccountCodes` parameters. New delimiter would be `^` unless somebody has a better idea. Example: `?AccountIds=5^100,6^12.75` to pre-populate account 5 with $100 and account 6 with $12.75.

Also new related feature to allow default selection of the frequency as well. I believe this is specified by a DefinedValueId so that would be allowed to be passed via the query string as well.  Example: `&frequency=123`.

### Versions

* **Rock Version:** 6.3
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
This is good to implement. While I know that they are not case sensitive let's keep all the parm names Pascal case. So `frequency=123` should be `Frequency=123`. We have not been super consistent with that, but we're trying to be better.

**Comment by edmistj** [comment]
While you're in there, what do you think about adding a third option on `AccountIds` to make it so the amount could not be changed? `?AccountIds=5^100^false`. I suppose the easiest way to achieve this is to mark the field as disabled. It would be better UI to show it as as `form-control-static`, but that would make reading the value when complete difficult.

Thoughts?

**Comment by cabal95** [comment]
Sounds good to me. I can see the use for that too.  For now I'll probably mark it disabled as changing it to a static control would require a much more invasive change. We can leave that for a later time.

And yes, I'll tweak the param naming. It's sometimes hard to remember (as a programmer) since they are actually not case sensitive. So when we do it wrong we don't notice. :)

**Comment by edmistj** [comment]
Thanks Daniel!
