### ISSUE TITLE
"Recieved" is misspelled in Communication History log

### ISSUE THREAD

**Issue by kyeschung** [SparkDevNetwork/Rock#2365]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

In the Communication History log after an email is delivered, when clicking "Delivered" to see the log, the word "received" is misspelled.

### Steps to Reproduce

1. Open Communication History
2. Click on "Delivered"
3. Note shows "Email was **recieved** for delivery by Mailgun." 

**Expected behavior:** 

"Received"

**Actual behavior:** 

"Recieved"

<img width="360" alt="screen_shot_2017-07-20_at_5 35 04_pm_720" src="https://user-images.githubusercontent.com/25948194/28468265-54066228-6de7-11e7-948c-f41906e20c80.png">

### Versions

* **Rock Version:** Rock McKinley 6.8
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Thanks for the heads up. This was fixed with this commit and will be in v7.
https://github.com/SparkDevNetwork/Rock/commit/fc675cc08675374a464b95e5f7555f3eed35a82c
