### ISSUE TITLE
[EN] Workflow Triggers should allow for "did value change in any way" check

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2369]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

https://github.com/SparkDevNetwork/Rock/blob/52465968229e027f42e3048a2ff2c7606261de37/Rock/Data/DbContext.cs#L525

Currently when checking if a workflow trigger is a match and a qualifier column was specified, the user must specify either an old value or a new value otherwise it is considered a non-match. Proposing that if neither is specified it is treated as a "did the value change in any way" check. In other words, `match = previousValue != currentValue`.

This would allow for workflows to trigger based on a column value changing to/from anything in addition to from a specific value and to a specific value.

The only way this should have an effect on backwards compatibility is if a workflow trigger is currently not setup correctly (both values blank) then it may cause the workflow to fire when it didn't before.

### Versions

* **Rock Version:** git-2017-07-23
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@cabal95 are you thinking this would only be for the 'Pre-Save'? That's the only option that has both a "from" and "to".

**Comment by cabal95** [comment]
If that is the only place where it is available right now, then yes.  I'm sure there is probably some odd EF reason why it's not available as a post-save.

**Comment by cabal95** [comment]
I've started working on implementing this. About a whopping 1 line of code. At the same time, I am working on implementing "Post-Add" trigger type (completed) that functions just like post-save, but only executes if this is a newly added entity.

Finally, also working to implement the "change from/to" functionality on the Post-Save triggers. I have the logic for detecting the original value working fine, but ran into a logic conundrum with the current code and would appreciate some insight.

* On ImmediatePostSave and PostSave checks, it is a match if `Entity.CurrentValue == Trigger.CurrentValueSetting`.
* In PreSave checks, it is a match if `Entity.CurrentValue == Trigger.CurrentValueSetting && Entity.CurrentValue != Entity.PreviousValue`.

So the matching logic is different based on a PreSave or PostSave. I get there was originally a reason - original values were not available on PostSave. But, if I configure a PreSave and a PostSave trigger on `CurrentValue = Bob` then PostSave will execute every time I save, while PreSave will only trigger the first time I save, when the value changes to Bob from something else.

Hopefully I'm making sense so far. My plan was to just use the same logic that PreSave uses for original/current value checks, but that would change existing functionality and triggers. But the current way it works feels like a bug to me.

I can implement by duplicating the PreSave logic completely and possibly breaking existing PostSave workflow triggers in that they would now only fire if there was a change vs always; or I can implement the PreSave logic BUT leave the current logic in place in the case of no previous value - but we would continue with this weird "they don't operate the same way".

**Comment by azturner** [comment]
@cabal95, My understanding is that In PostSave, since the context has already been saved, the original value is not available (the dbPropertyEntry.OriginalValue would be equal to the new value at that point). That is why the UI for adding Post-Save triggers is different than the Pre-Save. Is there a different way that you are able to get the original value in Post-Save?

**Comment by cabal95** [comment]
@azturner Short answer, Yes.

Long answer: The helper class `ContextItem` is initialized during PreSave. If the EntityState is `Modified` and there are any Post-type triggers for the entity type then I create a `Dictionary<string, object>` that contains the values of the `OriginalValues` and use those during the PostSave processing.

Benchmarking that change, if there are no Post-type triggers for that entity type then the extra code only takes an extra 0.001ms to execute. If there are Post-type triggers then the extra code takes about 0.1ms to execute (tested with `Note` entity type, 16 properties).

Or in other words, during a Save operation where we modify entities that have triggers, it would take modifying 1,000 entities at once to delay processing by 0.1 seconds.

**Comment by edmistj** [comment]
@cabal95 Circling back to this. We're OK if you want to PR this for a v8 roll-out.
