### ISSUE TITLE
Misspelled word in description of field in Check-in Label

### ISSUE THREAD

**Issue by kyeschung** [SparkDevNetwork/Rock#2370]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

<img width="1303" alt="screen shot 2017-07-23 at 6 40 26 pm" src="https://user-images.githubusercontent.com/25948194/28505227-ae9c20d8-6fd6-11e7-97e9-7d1e2d184b9c.png">

The word "applies" is mispelled as "applyes" in the Description for the "Print for Each" field in the Check-In Label (i.e. http://rock.rocksolidchurchdemo.com/page/157?BinaryFileId=54).

### Steps to Reproduce

1. Go to Check-in Label
2. Click Question Mark for description on "Print for Each"

**Expected behavior:** 

Should be spelled **applies**.

**Actual behavior:** 

It's spelled **applys". 

### Versions

* **Rock Version:** Rock McKinley 6.8
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@kyeschung Thanks! I added a migration fix for v6.9.
