### ISSUE TITLE
Log in issue

### ISSUE THREAD

**Issue by Sandra5238686** [SparkDevNetwork/Rock#2378]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

[Description of the bug or feature. Include screenshots if applicable.]

### Steps to Reproduce

1. [installed via winhost]
2. [flip the switch]
3. [at log in screen, receive a message "That wasn't suppose to happen" "An error has occurred while processing your request. Your organization's administrators have been notified of this problem" I have not been notified as what is the problem]

**Expected behavior:** 

[at log in screen, receive a message "That wasn't suppose to happen" "An error has occurred while processing your request. Your organization's administrators have been notified of this problem" I have not been notified as what is the problem]

**Actual behavior:** 

[received issue]

### Versions

![not](https://user-images.githubusercontent.com/30355081/28679471-28c893fe-72a8-11e7-8902-0b802d2a841d.PNG)
![log in](https://user-images.githubusercontent.com/30355081/28679470-28c47f8a-72a8-11e7-8598-ed8599f02081.PNG)

* **Rock Version:** [? downloaded version]  
* **Client Culture Setting:** [?]

**Comment by edmistj** [comment]
@Sandra5238686 this issue list is for bugs in the code of Rock. You'll get better troubleshooting advice either on our Slack community (rockrms.com/slack) or our Q&A site (rockrms.com/ask)
