### ISSUE TITLE
| Index Filter Broken

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2379]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

[Description of the bug or feature. Include screenshots if applicable.]

### Steps to Reproduce

1. Create HTML Content Block
2. Paste the following into the block
```
{% assign fruits = "orange apple banana orange" | Split:' ' %}
{{ fruits | Index:2 }}<hr>
{{ CurrentPerson.PhoneNumbers[0] | Property:'NumberFormatted' }} - 0<hr>
{{ CurrentPerson.PhoneNumbers[1] | Property:'NumberFormatted' }} - 1<hr>
{{ CurrentPerson.PhoneNumbers[2] | Property:'NumberFormatted' }} - 2<hr>

{{ CurrentPerson.PhoneNumbers | Index:0 | Property:'NumberFormatted' }} - 0 index<hr>
{{ CurrentPerson.PhoneNumbers | Index:1 | Property:'NumberFormatted' }} - 1 index<hr>
{{ CurrentPerson.PhoneNumbers | Index:2 | Property:'NumberFormatted' }} - 2 index
```

**Expected behavior:** 

I expected `| Index` to behave like the other `[x]` Index syntax

**Actual behavior:** 

The `| Index` filter is broken in ways I can't exactly put my finger on.

### Versions

* **Rock Version:** [6.5 my install, 6.2 demo]  
* **Client Culture Setting:** [en-US]

**Comment by cabal95** [comment]
Filter works correctly, but documentation is wrong. It's actually a v7 filter not a v1. When you try to use an undefined filter the original data is returned (i.e. it behaves like the filter just wasn't in your markup).

@edmistj Can you update the docs?

**Comment by edmistj** [comment]
Done

**Comment by NuclearTacos** [comment]
Well that makes WAYYYY too much sense :laughing: I didn't check to see what the array looks like without a filter and I just assumed it would look more JSON'y / joined with commas.  Thanks guys!
