### ISSUE TITLE
[EN] Image Field Type should support restricting preview-size

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2381]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When creating a custom attribute of type `Image` I believe we should be able to specify a maximum preview size in view-mode. Currently the view-mode rendering uses all available width, which on some pages can chew up a _lot_ of space for what should really be more of a thumbnail view.

Example:

![image](https://user-images.githubusercontent.com/1119863/28784465-61b8d19c-75c8-11e7-8103-f8ce3d8adce0.png)

Suggesting the field type be given two extra attributes: `Maximum Preview Width` and `Maximum Preview Height` that, if set, will constrain the view-mode dimensions to something more manageable.

With `max-width: 320px; max-height: 320px` applied:

![image](https://user-images.githubusercontent.com/1119863/28784604-bf1f1ddc-75c8-11e7-8f79-da3232c54464.png)

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
I've run into this several times also. In v7 we added a setting to allow you to format the formatted value of an attribute of type image. This allows you to have complete control of how the image gets formatted (could even add lightbox support). Does this fit the bill?

![31-07-2017_10-33-26-chrome](https://user-images.githubusercontent.com/548178/28789849-e545fbbc-75db-11e7-8637-3a09b5773d9e.png)

**Comment by cabal95** [comment]
Yes, I think that will work. It's not as user friendly, but I think the user-friendliness can be solved by (later) adding a new class of `img-responsive-small` that also limits the size - or something like that.

Love this change BTW!
