### ISSUE TITLE
[EN] "Dependent" Fields

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2383]
### Description
We've run into a limitation with a lot of our forms where we want to have two separate options on a form, but have the choice of the early options influence your options of the latter options.

I know this is a substantial request, but I have an idea that should be able to make the implementation much easier. :grin: 

Example:
We have campuses 1 and 2.  Campus 1 meets at service times A and B.  Campus 2 meets at service times C, D, and E.  I would love to have someone select their Campus, then that allows the person to select their service time from just the valid options.

Quick terminology glossary (since I'll probably use words wrong)
I'm going to call each box represented on the Workflow's UEF (generated by including an Attribute of this type) a "Field".
The last field is the "Value" and the Field in front of it is a Filter

I apologize in advance if I'm difficult to understand on this, I would be glad to elaborate!  (I believe very strongly in the implementation I'm detailing and think it would be helpful and intuitive for Admins!)

### Recommended Implementation
I think this can best be solved by a Defined Type!  Each Defined Value in the Defined Type would be one of the possible "Values" (similar to how Defined Values are implemented currently in Workflows).  You could then define Attributes for the Defined Type.

The Names of these attributes would be the title above the fields that this Attribute connect to.  The type of Attribute on the Defined Type would act like that kind of Attribute being placed in a User Entry Form.  The Value of that Attribute for each Defined Value would decide if the underlying value will be available in the last field.

Bonus points: One of those Attributes could be a Dependent Fields Defined Value, so that Field C depends on Field B, depends on Field A (inception sound)

You should be able to determine which values are used in the filtering fields by using Lava on the Workflow Attribute.  Example: `{{ Workflow | Attribute:'ServiceTime','Object' | Attribute:'Location' }}` would get the Campus of the Service Time selected on the last field.

![dependant fields](https://user-images.githubusercontent.com/19762670/28843864-4302a6e6-76c8-11e7-9a90-f4dce282b525.png)

I hope the graphic makes more sense :+1:

**Comment by cabal95** [comment]
While there isn't anything now that allows for this, I think the "template" set forth by the upcoming Matrix Attribute type would allow for this.  If a similar field type, lets call it "Conditional Attribute Type", was created that let you add Attributes to it (just like you can with matrix) but also provided a sort of "qualifier" like the EntityQualifierColumn/Value functionality, to make those attributes conditional on the values of other attributes _also embedded in this conditional attribute type_; I think that might achieve the desired results.

I think the biggest trick would be figuring out how to make it's configuration simple for the administrator.

**Comment by edmistj** [comment]
We do have a plan to add Conditional Fields to entry forms. This was a mockup we did for the feature.

![01-08-2017_16-44-51-balsamiq mockups 3](https://user-images.githubusercontent.com/548178/28851632-d4739044-76d8-11e7-834c-06e8371afc96.png)

**Comment by NuclearTacos** [comment]
Nice!  I definitely see the power in that.

On my 2nd look, I realize that in my example of Campus to Service Time, using your solution would require me to have an Attribute for every campus (since we would only be able to reveal full fields according to the logic).

The advantage to something like this defined value is that you would only need to generate one stack of values, rather a Workflow Attribute for each possible set of Service times, then using a big string of `| WithFallback` to display the actual value.

For example, your plan:
3 campuses with 2, 2, and 3 service times.  Workflow Attribute for Campus, 3 Workflow attributes with a single select with the respective campus service times (named ServiceTimeCamp#).
Lava to Generate <campus> at <service time> is
```{% assign servCamp1 = Workflow | Attribute:'ServiceTimeCamp1'  %}
{% assign servCamp2 = Workflow | Attribute:'ServiceTimeCamp2' %}
{% assign servCamp3 Workflow | Attribute:'ServiceTimeCamp3' %}
{{ Workflow | Attribute:'Campus' }} at {{ servCamp3 | WithFallback:'',servCamp2 | WithFallback:'',serveCamp1 }}```

For example, my plan:
3 campuses with 2, 2, and 3 service times.  1 Defined Value of each of the unique Service Time/Campus combinations (7 total), with their attributes configured to the Campus.  1 Workflow Attribute of the Filtered Values.
Lava to Generate <campus> at <service time> is 
`{{ Workflow | Attribute:'ServiceTime','Object' | Attribute:'Campus' }} at {{ Workflow | Attribute:'ServiceTime' }}`  (or really close, I'm rusty with Lava and Defined Types.

**Comment by NuclearTacos** [comment]
oops, didn't mean to add an additional comment

**Comment by NuclearTacos** [comment]
The biggest core difference between the two solutions seems to be that your solution seems to allow one option of a UEF to allow multiple different kinds of forms.  Where the goal of my solution is to allow a single Attribute that is multi-faceted.  This could even extend beyond UEFs to be used as Person or Group Attributes!

**Comment by edmistj** [comment]
I do think that your solution is creative.  You're second point would be solved by matrix attributes. They're pretty powerful, though there will be some limitations (limited reportability).

**Comment by NuclearTacos** [comment]
All I ask is to keep it on the table.  Although I feel like this arrangement is a silver bullet for the issue that made me think up this solution, I haven't though up enough problem-cases that necessitate the introduction of a feature like this.

Although, it does give me something to work towards in my own development journey :grin:

**Comment by kyeschung** [comment]
If conditional logic is on the roadmap, that's good enough for me. Hard to go completely Rock with forms without it.

**Comment by mikejed** [comment]
I love this idea as well. Missed the thread until just now though. Was "required" considered as part of this? That is, allow us to specify that if an input is shown it can be required, but if it's hidden, then don't break the form =)
If those logic select boxes are Workflow/Activity Attributes though, I know the first thing that's going to be requested will be allowing the admin to show/hide an input based on another attribute on that same form (that is, before the attribute values from this form are actually stored). Short of allowing javascript to be provided to check values onBlur() though (barf), I'm not sure what kind of interface to even ask for...

**Comment by edmistj** [comment]
Yes there would be logic where if a field was marked 'required' but not visible by a condition not being met then it would not be 'required'.

**Comment by NuclearTacos** [comment]
If you had an item like Phone Number and Phone Type, are you able to make it so Phone Type is only require if a value has been entered for Phone Number on the same entry form?

**Comment by edmistj** [comment]
The thinking above is that conditionals would only work on fields with a limited option range. Like single selects, multi-selects, etc. They would not be enabled for text boxes. This is patterned after Forms Stack. This plan could be adjusted but the goal would be to fill the most used need.

**Comment by mikejed** [comment]
So standing Chris' logic on it's head, you could have someone select the type of phone number they wanted to enter, and then you could show the textbox to take the actual number on the same form once that "Phone Type" single-select was changed from, say, none?

**Comment by NuclearTacos** [comment]
I see the work around, but think that would likely be confusing for people using the form.  Is it feasible to allow Blank / Not Blank options for fields like that?

I do like that this makes it possible to require Campus / Service times (while having service times be different for campuses, which matters to us since we're in two time zones 🙄 ).  I think I can get over the bulky Lava that our odd campus/times arrangement would require.

**Comment by jonedmiston** [comment]
This feature is in v9
