### ISSUE TITLE
Page View Retention Period no longer persists and stays blank

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2384]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Setting the Page View Retention Period does not persist, and always reverts to a blank state.

### Steps to Reproduce

1. Go to Admin | CMS Config and edit any site
2. Open the Advanced tab and enter a Page View Retention Period
3. Save the site, the edit it again and observe the Retention Period is blank again.

**Expected behavior:** 

Page View Retention Period would be settable to desired timeframe and would persist.

**Actual behavior:** 

It doesn't appear to be saved and is blank, though I have no easy way to know if this is just a visual glitch (not showing the current setting) or if it really _is_ blank and thus set to log indefinitely. I know this used to work and it seems like it broke around the 6.3 timeframe, when Page Attributes were introduced.

### Versions

* **Rock Version:** [6.8]  
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by cabal95** [comment]
I'm not sure it ever worked.  It doesn't exist on my 6.2 RockIt install, and it doesn't work on our 6.3 production install.

**Comment by JimMichael** [comment]
Hmm.. you're saying the setting isn't even THERE in 6.2? I could swear it worked at some point as I "remember" changing the settings several times, but I guess I could have imagined it.
