### ISSUE TITLE
[EN] Allow Naming of Filters in Dynamic Report Block

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2385]
### Description

I've pinned down Dynamic Report Blocks as the best way to accommodate people that have had trouble learning how to use Data Views and Reports.  I think it would be very helpful to these people if we were able to write the title of a filter (sort of like how you can name a column in a Report to be more specific to the end user).

### Solution

I think it would be **extremely** helpful to end-users if we could configure the Title that shows on the Dynamic Data Block.  This would also eliminate the problem of having two filters of the same type.  Like upper and lower bounds of an age would both have the same title "Age".

![image](https://user-images.githubusercontent.com/19762670/28880758-a1187b68-776b-11e7-9e58-679cf0e0c1ef.png)

![image](https://user-images.githubusercontent.com/19762670/28880766-a4d0af46-776b-11e7-9165-e8f4389644e0.png)

**Comment by kyeschung** [comment]
Yes! I love this suggestion. It would also be helpful to order the filters, as there is no way to order the Dataview Filters when creating/editing a Dataview and so I have to delete and add again in the order I want them to show in the Dynamic Report.

**Comment by arranf** [comment]
It looks like this has been implemented at some point between this issue and the current development version. 🙌
