### ISSUE TITLE
[EN] Add Plivo as SMS Communication Transport

### ISSUE THREAD

**Issue by chrisgo** [SparkDevNetwork/Rock#2387]
Consider adding Plivo as an alternative to Twilio as SMS Communication Transport

If sending a lot of SMS communications, could reduce cost by 50% or more at current rates.  

Twilio Pricing https://www.twilio.com/sms/pricing
* Phone # $1.00/mo
* Receive $0.0075
* Send $0.0075* (I think the asterisk means extra charge for short codes)

Plivo Pricing https://www.plivo.com/pricing/#!sms
* Phone # $0.80/mo
* Receive: FREE (100% less)
* Send: $0.035 (50% less)
* API Docs: https://www.plivo.com/sms-api/

I have used Plivo for other projects and it seems to work well

**Comment by cabal95** [comment]
I'm kind of confused by their pricing. In the link you provided it gives one price and then below it gives per-carrier prices. The way I read Plivo's pricing is that _they_ charge $0.0035 outgoing and $0.00 incoming, but then you have to pay the carrier pricing on top of that, which equates to an average of $0.004 outgoing and $0.003125 incoming. For a total of $0.0075 outgoing and $0.003125 incoming.  So it is a little bit cheaper per incoming message than Twilio, but not "free" like they say (unless your bill is showing different).

Also, just to clarify the Twilio pricing. They give 25% discount non-profit pricing to churches (plus a $500 credit) which brings their pricing down to $0.75/mo for phone numbers and $0.005625 per message. This price difference also puts Twilio on the cheaper side if you are mostly sending vs receiving.

And that free credit equates to a little over 85,000 free SMS messages.

**Comment by arranf** [comment]
@cabal95 Those are shortcode prices.

**Comment by arranf** [comment]
Hey @chrisgo, this is worth looking at. This is probably better suited as a plugin rather than a core integration though.
