### ISSUE TITLE
[EN] Sending System Emails should resolve FromAddress/FromName per-recipient

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2388]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Currently, the `From Address` and `From Name` fields in a system e-mail are Lava aware, but they are resolved too early in the process and do not have access to the recipient merge data. Suggesting that this be moved later in the process of `SMTPComponent` so that we have access to the recipient merge fields as well. For performance we can do an initial check to see if those fields have lava so that we only resolve the lava (in the loop) if it actually exists.

Specific use case, I want to be able to send a system e-mail to a group of staff members and have the from address come out like `pod-12345@mg.sheph...rch.com` and then setup a rule in Mailgun to catch `pod-####@` addresses and send them to a special handler that will parse the number and do a specific task on that entity along with the body of the e-mail message.

Example: `pod-{{ MyEntity.Id }}@mg.shep...rch.com`

### Versions
* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
This is low priority for sure, but would love to get this on the roadmap for v8 at least (possibly sooner, but I know I'm asking a lot). Re-reading my original comment I realize I was a bit vague about my use case. This is essentially giving me the ability to add a new comment to something (by id) via e-mail.  e.g. system e-mail headers:

![image](https://user-images.githubusercontent.com/1119863/38167294-dbaccc2c-34e7-11e8-9f75-19f2e8f104c4.png)

So the idea is it would generate a unique "From" address for each recipient. When a reply comes back to that address, I can parse the "to" field to pull out the Id of the project to attach the new comment to and the alias Id of the person who is replying and mark them as the owner of the comment.

**Comment by edmistj** [comment]
@cabal95  I get what your trying to do and it sounds pretty cool. My hesitation is that by pushing this down the stack to the SMTPComponent we make more transports have to implement this code. For instance the new MailgunHttp transport does not inherit from SMTPComponent.

Is there anyway that this could be implemented higher up the chain while still giving your the functionality you want?

**Comment by cabal95** [comment]
All the leg-work is currently done in the SMTPComponent and MailgunHttp classes currently, so I'm not sure if it would be possible to move it further up. Possibly further up we could merge the Communication.AdditionalMergeFields into the CommunicationRecipient.AdditionalMergeValues, but even that would still require the two classes just mentioned to make use of it - though maybe this is already being done since when merging the body content it seems to _only_ utilize the CommunicationRecipient.AdditionalMergeValues and ignore the Communication.AdditionalMergeFields.

Currently both those classes lava-resolve `fromAddress` and `fromName` one time, and using only the Communication.AdditionalMergeFields (completely ignoring the recipient merge values). In theory, the only change that would be needed is to move those two lines of code _inside_ the `foreach recipient` loop and merge using the recipient data instead of the communication fields.

I'll see if I can verify that by setting a breakpoint in there and see if the CommunicationRecipient.AdditionalMergeValues do indeed contain the Communication.AdditionalMergeFields as well. I should be able to get to this sometime this week.

**Comment by cabal95** [comment]
P.S., I did just find a way to do this via the Subject for now, so this isn't super critical anymore, but would certainly clean up how the messages look in the future. Encoding this information in the subject isn't very pretty to the end-user.

**Comment by arranf** [comment]
@cabal95 This is out of scope of the SendGrid plugin as the plugin relies on the underlying implementation of the SMTPComponent (until I see if it's worth switching to HTTP for performance reasons).

**Comment by edmistj** [comment]
@arranf We switch the Mailgun to use HTTP, we should have some data on whether that increases the speed noticeably when it's released in v8.

**Comment by arranf** [comment]
@cabal95 Just wanted to check, is this something you're actively working on?

**Comment by cabal95** [comment]
Mostly waiting to hear from @edmistj. We might be able to move this up the class-chain to TransportComponent, but that class is so abstract I don't know how we could implement without a substantial change to how the components work.

**Comment by edmistj** [comment]
Since this is low priority (edge case need) I have it on the back burner while we work to get v8 out.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
