### ISSUE TITLE
Lava | ToCssClass not stripping or escaping special characters

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#2393]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Unescaped special characters are not valid in CSS Classnames. Yet `{{ 'T&T | ToCssClass }}` returns `t&t`.

### Steps to Reproduce

1. Use the following code in an HTML block (set your cache duration to 0):
```
{% assign className = 'This&That' %}
<div class="{{ className | ToCssClass }}">A test div</div>
<script>$('div.{{ className | ToCssClass }}').hide();</script>
```
Save and reload the page: the test div remains visible.
Edit the assignment of className to 'ThisAndThat', save and reload and note that the test div correctly is hidden.

View source and see that the class is assigned using `class="this&that"`

![image](https://user-images.githubusercontent.com/6932047/29196635-7e78a0bc-7dea-11e7-9f8f-df3f9ae73df7.png)

**Expected behavior:** 

A CSS class should have special characters ~stripped~ _replaced with a dash_ (ideally) or escaped.

**Actual behavior:** 

Special characters persist in the class name

### Versions

* **Rock Version:** 6.9  
* **Client Culture Setting:** EN-US

**Comment by cabal95** [comment]
I would say replaced with `-` as that seems to be sort of the "common practice".  i.e. `this-that`.

**Comment by mikejed** [comment]
I was just thinking the same thing. I agree, thanks

**Comment by mikejed** [comment]
Nice and clean Jon, thanks
________________________________
