### ISSUE TITLE
Cannot run specific county background checks

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2396]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When running a background check (we are using PMM), we sometimes need to run extra checks on various counties based on the results of the first check (which counties they have lived in). Currently I can not find any way to enter "custom" state/county names for these followup checks.

### Steps to Reproduce
1. Run background check
1. Try to set custom state/county for check to run on.

**Expected behavior:**

Should be able to run a custom state/county check.

**Actual behavior:**

Cannot.

### Versions
* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
@edmistj Any general thoughts on how to accomplish this?  Should an additional method be added to the BackgroundCheckComponent that accepts attribute keys for County and State and if provided use those rather than the current logic?

**Comment by edmistj** [comment]
@cabal95 I'm thinking we'd need to research a bit with the PMM API to determine what would need to be done. I was thinking it might be good to have a way to submit these requests outside of the workflow action. So if a response came back and you wanted to dig in more you could run them out of band and update the person attributes manually. 

What do you think of this solution.

**Comment by cabal95** [comment]
I would probably need more details on exactly what you are thinking.

Out of band is what we have to do now. They get a check back then have to login to PMM and manually run the extra checks, then remember to go into Rock and update everything. This seems like a common scenario (run a background check with county search, it comes back clean but reports previous counties that need to be searched as well) so it seems like a simple solution should be provided to the end-user. And an out-of-band solution feels like a step backwards from what we had in our old ChMS.

I don't think the user should ever have to "manually update the attributes" with something like this as there is plenty of room for user error with something that is pretty cricital. But I could see some kind of "helper page" that looks at all background checks that have been returned on a person and "pick" the one they want to use in the person attributes.

Example:

1. Run initial BG check (A)
2. First results come back clean, but notice 2 extra counties and run two additional checks (B and C).
3. B and C come back.
4. User can now view all 3 results on a page and notice that C has reported records.
5. User picks `C` to use for updating the person attributes.

**Comment by edmistj** [comment]
@cabal95 that sounds good. I think it's very achievable as long as all that's not having to work within the workflow. When I say 'out of band' I mean outside of the workflow.

**Comment by cabal95** [comment]
Okay. I'll see if I can talk with Hoff some more about a more specific plan.  I think we might need to modify the existing workflow to not store the document and date on the person until after the admin user selects either Approve/Deny.

I just noticed that it stores immediately upon receiving it. Even unrelated to this specific issue discussion; if we have a BGC that shows records and then run another one that shows no records, we have just overwritten the original BGC document on the person record.

Example:

1. Run criminal BGC and deny serving because of records found.
2. Later they want to serve by driving the trailer with the church equipment for mobile campus each week since they couldn't serve previously in 1.
3. MVR BGC is done and comes back clean - but the document on the person has been overwritten now.

I might need (should) file this as a separate issue, but just noting it for now.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
