### ISSUE TITLE
Contribution Statement Lava Needs Additional CSS for Pledge Progress Bar

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#2397]
https://github.com/SparkDevNetwork/Rock/blob/5a6798a61043d6d77d585adf6ad0655001fc5136/RockWeb/Blocks/Finance/ContributionStatementLava.ascx.cs#L152

Needs `max-width: 100%; min-width: 2em;` added to the progress bar in-line CSS.

* `max-width: 100%;` will keep the percentage label centered when >100% has been received.
* `min-width: 2em;` will keep enough of the bar graph in place to display `0%` in the bar ( https://getbootstrap.com/docs/3.3/components/#progress-label ).

Not sure the preferred method for resolving since it's in a Block Setting default value.

**Comment by arranf** [comment]
@garrettjohnson This is your realm.
