### ISSUE TITLE
Metrics do not inherit security from categories

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2399]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you set security on a category that contains a Metric the security is not inherited. This means to enable editing a metric for staff you have to set the security on each. and. every. single. metric. you. have. created.

### Steps to Reproduce

1. Create 50 metrics
2. Grant Edit permissions on the category containing the metrics.
3. Notice the permissions have not been applied to the metrics in the category.
4. Weep for the time you will spend applying permissions to each metric one at a time.

**Expected behavior:** 

Permissions should be inherited.

**Actual behavior:** 

Permissions are inherited from Global Default.

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Did this commit ever get merged?

**Comment by azturner** [comment]
It did get merged here: https://github.com/SparkDevNetwork/Rock/commit/581aa4f2, but now realize I used the wrong # for "fixed". I also still have a task to finish testing/confirming the change.
