### ISSUE TITLE
[EN] Handle multiple phone number types?

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2405]
### Description

As churches convert their data, they often have multiple phone numbers listed of the same type that they want to keep.  Rock's data model and Read-only view allows for this capacity, but the Edit view does not.  This seems inconsistent and the Edit UI should display multiple numbers of the same type if they exist.

The most important requirement for PhoneNumbers is that only one number can be marked SMS at a time.  The UI already enforces this requirement, so any UI changes need to verify this doesn't break.

### Steps to Reproduce

1.  Add a Mobile phone number 
2. Add a second Mobile phone number via db
3. The read-only view displays both numbers
4. The edit view only displays one number

**Expected behavior:** 

The edit view would display both numbers.

### Versions

* **Rock Version:** v6.9
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
There are potential issues with things like the Lava filter `PhoneNumber` which expects there to be only one phone of the given type.  Additionally, I think many other parts of the system (including most custom blocks I have written) assume only one phone number of a given type. One example is the GroupRegistration block, which assumes only one phone number of each type.

**Comment by NuclearTacos** [comment]
This might need to be a separate issue, but I also think there should be view/edit control on phone number types.  This way you can have pastoral phone numbers that can't exposed to volunteers who need to be able to edit people's phone numbers for check-in.  Unlisting is nice, but it loses its value immediately when a person you can't 100% trust is able to edit people.

**Comment by edmistj** [comment]
Like email I think we need to keep a single record of truth for things like mobile phones. There are cases where we need to report a single mobile phone. In these cases we wouldn't know which to pick. Also, much of the features we'd like to add in the future will need to be able to query a person by their mobile number (e.g. Text-To-Workflow). Having people put multiple cell phones on a person (like a parents cell phone on a child with their own mobile phone) would eliminate the ability to do this type of matching (both the parent and the child would have the same number). 

Is there anything we're missing with this thinking? Not sure I understand the use case of having multiple phones of a single type other than they'd like to keep the data. Import tools could be written to append these other phone numbers into other phone types (Other Phone #1, Other Phone #2) if required or they could be summarized in a person attribute. Would that work?

**Comment by dcs619** [comment]
@edmistj Works perfect - just wanted to fix the UI inconsistency once I saw it exists.  

Can we add a PhoneNumber constraint that enforces a unique PersonId and NumberValueTypeId?  And by `we` I mean `y'all` since it would require a migration 🙂
