### ISSUE TITLE
[EN] Add Event Occurrence-Specific Attribute Values

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#2407]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Currently, there is the ability to add custom attribute values to events on a calendar, but from what I can tell, different occurances of the same event type cannot have variying attribute values.

For instance, a church might have membership classes at multiple campuses at different times, but an individual class may or may not include lunch/dinner depending on what time it is at.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** 

[What you expected to happen]

**Actual behavior:** 

[What actually happened]

### Versions

* **Rock Version:** [Enter Rock version here]  
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by cabal95** [comment]
This is also something we recently discussed in-house as a "need" (meaning it would be very useful). Especially with graphics for annual events. e.g. we would expect to re-use the "4th of July" event each year with new occurrences, but the graphic is tied to the "main" event, not the occurrence.

**Comment by briankalwat** [comment]
@cabal95 yes, and right now to accomplish that, you'd have to have the same description, etc copied across multiple events just so a single attribute value can be different - which means if the description changes, you're having to go update all of them which is less than ideal.

**Comment by edmistj** [comment]
@cabal95 @briankalwat 
Were you guys seeing the attributes for the occurrence being defined on the Event or the Calendar?

**Comment by cabal95** [comment]
Both would be great.  But I would think defined at the Calendar would be the primary use. I think it's more likely that I would define an (occurrence) attribute at the Calendar level so that it applies to all occurrences on the calendar. Defined **at** the Event level **for** the occurrence seems more of a special case thing.

**Comment by briankalwat** [comment]
On the Event would be extremely useful – although I agree both would be ideal.

**Comment by edmistj** [comment]
This is currently in development.

**Comment by edmistj** [comment]
This is complete, but the the attributes have to be configured globally for all calendars. There wasn't a way to make them available on a per calendar basis because there is no model to tie to.

**Comment by briankalwat** [comment]
@edmistj are you saying there is no model to add attributes to an individual Event Item? I don't think it's a special case to think that different "types" of events would have different attributes tied to them. It's just unfortunate that if you need an attribute for one Event Item, you have to have it for _all Event Items_ going forward... unless I'm understanding this incorrectly, which is entirely possible.

**Comment by edmistj** [comment]
We could augment it to add an attribute for a single event item. You just could not add an attribute for event items on a specific calendar. If you think you'd want the ability to add an attribute to a _specific_ calendar item let me know.

**Comment by briankalwat** [comment]
@edmistj That would be fine if the attributes weren't calendar specific. We'd just like the ability to have attributes that are unique to an event item, so we don't end up with 20 attributes on each item and most of them don't apply to a given event type.

I've mentioned this to Frank and Matthew and y'all can talk specifics. Thank you! 👍
