### ISSUE TITLE
Content Channel View isn't returning Items from channel after upgrade

### ISSUE THREAD

**Issue by bengoshow** [SparkDevNetwork/Rock#2408]
### Description

Upgraded Rock from 6.2 to 6.8. Now it seems that our Content Channel View block isn't returning any items for the "Podcast Message" channel. I have debugging enabled, and there is nothing returned in the "Items" object.

### Versions

* **Rock Version:** 6.8 
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
You might check the settings of that block to ensure that the Content Channel Type is not blank. Let me know.

**Comment by bengoshow** [comment]
It's not blank (although that setting is blank on the Rock demo site)

**Comment by edmistj** [comment]
Did you try flushing the cache?

**Comment by bengoshow** [comment]
I did.

**Comment by aaronjones8** [comment]
There error is happening in the file ContentChannelView.ascx.cs when trying to set the list to the podcast message. It is looping through 4 times from the different content channels on the page. 

line is 860. It is setting the items = itemQry.ToList()

The last time it loops through, it sets the items = itemQry.ToList() which is setting the items to 0

**Comment by aaronjones8** [comment]
My church's website is on 6.8 and the podcast messages do work fine on it so I don't believe it is an issue with the block but I also don't see any issues on the Content Channel settings when looking at it.

**Comment by aaronjones8** [comment]
I found that the entityField is being set on line 830 based on the PageId which doesn't seem to be correct. I'm not sure if something isn't clearing from there being 4 Content Channels on that page. With the podcast on my church website, there is only 1 Content Channel on the page.

Ben, I implemented a quick fix on the server for now so that it works on the live and dev sites

**Comment by bengoshow** [comment]
Seems weird that the Content Channels in the Footer are still working as expected though.

**Comment by aaronjones8** [comment]
I believe that is because they don't have the option as being filtered by querystring. That is when that code is hit

**Comment by cabal95** [comment]
I'm not positive, but I think the "filter by query string" is only meant to be used on the content item detail page to view a single item as passed in the query string.

**Comment by aaronjones8** [comment]
Yeah it looks like it isn't playing nice because there are 3 other content channels on the page (Header links, social links and footer links) and then the Podcast Message content channel that is being filtered by the query string

**Comment by bengoshow** [comment]
Hi Daniel! Yep, that's the page we're seeing the issue on. The Podcast Message page, where the query string contains the Item value.

**Comment by cabal95** [comment]
Can you post a link that should be working but isn't?

**Comment by bengoshow** [comment]
Yep. I'll find you on Slack

**Comment by cabal95** [comment]
@aaronjones8 The line of code you mentioned should only be a problem if a parameter on the query string matches an entity field and adds a new filter point.  Can you verify which entity field / attribute that is happening on?  No match would mean that `items = itemQry.ToList()` would simply set items back to it's original value of 1 item.

**Comment by azturner** [comment]
@aaronjones8 Can you describe what you changed in the block?

**Comment by aaronjones8** [comment]
I originally just added a fix so that the block of code wasn't hit.

I found that actual issue was the it was grabbing the first entity with the key of PageId. They had a content channel with an attribute of that key. I changed the key name to be SOSPageId and that resolved the issue

**Comment by bengoshow** [comment]
Thank you, Aaron! Will that key name change need to be updated in our theme elsewhere?

**Comment by cabal95** [comment]
@aaronjones8 Just to clarify - so a key in a _different_ content channel was causing the issue?  If so that I would consider a bug, especially since that block requires you to select the content channel you are working with in the block settings.

**Comment by aaronjones8** [comment]
@bengoshow I didn't see what lava template that content channel was using. If you were calling PageId for the key, just change it to SOSPageId

@cabal95 Yes that is correct. It was a different content channel that wasn't even on the page.

**Comment by aaronjones8** [comment]
@cabal95 I changed that key name back to PageId for the other content channel and modified the code locally to 

var entityField = entityFields.FirstOrDefault( f => f.Name.Equals( key, StringComparison.OrdinalIgnoreCase ) && f.AttributeEntityTypeQualifierName.Equals(contentChannel.ContentChannelType.Name, StringComparison.OrdinalIgnoreCase));

so that it compares the Content Channel name to make sure that it is an entity from the some content channel. 

That should be a fix so long as it isn't supposed to pull entities from another content channel. I unfortunately don't have the core rock project forked on my machine

:(
