### ISSUE TITLE
Update Groups Save Address API to use JSON

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2411]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### UPDATE
API works as expected with `~api/Groups/SaveAddress/{groupId}/{locationTypeId}?street1={street1}&city={city}&state={state}&postalCode={postalCode}&country={country}`. However the spec for `PUT` requests expects the contents in the body to update the record. Since the querystring update method isn't used anywhere else in Rock with a `PUT` request, I propose changing it to use a JSON encoded location in the body of the request.

===

### Description
The Groups Save Address API endpoint located at `api/Groups/SaveAddress/{groupId}/{locationTypeId}` and found in [GroupsController.Partial.cs#L536 ](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Rest/Controllers/GroupsController.Partial.cs#L536) fails to create/update a group address while responding with a `204` status.

### Steps to Reproduce
1. Submit a `PUT` request to `api/Groups/SaveAddress/{groupId}/{locationTypeId}` with a well formed JSON body 

```
{ "street1": "...","street2": "...","city": "...","state": "...","postalCode": "...","country": "..." }
```

1. View the group/family submitted in the request. Nothing has changed.

**Expected behavior:**

Address is changed. Based on the `AddNewGroupAddress` call, it should add a new location with the given locationTypeId while moving any existing locations with the same locationTypeId to previous.

**Actual behavior:**

Nothing happens, API responds with `204`.

### Versions
* **Rock Version:** 6.9
* **Client Culture Setting:** en-US

**Comment by garrettjohnson** [comment]
[Found a removed note](https://github.com/SparkDevNetwork/Rock/blob/430fdabe689608df074207e9dd0ab6bc79d21c69/Rock.Rest/Controllers/GroupsController.Partial.cs#L411) that mentions the solution. `Use ~api/Groups/SaveAddress/{groupId}/{locationTypeId}?street1={street1}&city={city}&state={state}&postalCode={postalCode}&country={country}`

While this works as expected, I'm hesitant to close the issue since this appears to be the only API call using query strings for user input.

**Comment by cabal95** [comment]
Just to note, the WorkflowEntry API endpoints also use query strings to pass data into the Workflow via workflow attributes.

**Comment by garrettjohnson** [comment]
Querystrings are great in workflow requests since it's a `GET` request often triggered by links. It just feels weird/[off-spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6) to use querystrings to update a record in a `PUT` request.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
