### ISSUE TITLE
Security Mismatch on Edit Page button in Admin toolbar

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2412]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

So, I'm not sure where the bug is - or more specifically - which is the bug. But here is the skinny. To view the "Edit Page" button in the admin toolbar you must be an administrator of the page. But, in order to actually edit the the page you only need Edit permissions.  Examples, you can manually load the URL that goes into the modal window and as long as you have Edit it lets you make changes and save. Also if you have Edit you can make changes via the Site Map block.

To us, it makes sense to allow users with Edit permission on the page to view the Edit Page button. However, the problem becomes that since that isn't how it works now we might suddenly be giving people access to the Edit Button that didn't have it before based on existing page permissions. So I can't really say which way this should be fixed, but it's there and should be fixed I think.

### Steps to Reproduce

1. Give user Edit permission to a page.
2. Give user View permission to the Site Map page (so they can get to it).
3. Try to edit the page settings, such as page title, via the admin bar - FAIL.
4. Try to edit the page settings, such as the page title, via the Site Map block - SUCCESS.
5. Manually plug in the URL for the edit page modal popup and edit that way - SUCCESS.

**Expected behavior:** 

All three methods should either succeed or fail.

**Actual behavior:** 

Only had a 66% success rate. While that may be a passing grade in the USA, I don't think the rest of the world would agree.

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
This has bugged us, too, and I think edit rights on the page should expose the Edit button in admin toolbar. I had to make someone an Administrator on a page just so she could edit page attributes (which, with our theme, can be considered a "content manager" task) Giving her the alternate pagemap/modal url workaround isn't really viable. So now she has way more rights than she needs _just_ to see the edit button in Admin toolbar.

**Comment by JimMichael** [comment]
Tommy P. just noticed that in 6.10+, Finance roles now have page edit rights on their finance pages and see the Admin Toolbar with only the gear (a potential scenario @cabal95 mentioned in his initial issue). 

The only work around I can think of is remove edit from all Finance pages and grant edit for the Finance roles to every (appropriate) block on all Finance child pages... ugh. Is this a "thing" that needs to be discussed, or do we just live with doing that, or just let finance people have access to edit the pages themselves and potentially Really Mess Things Up? (not to mention the "what the heck is this new thing at the bottom of my pages?!" issue.) Just commenting here to make everyone aware...

**Comment by edmistj** [comment]
Seems like with this fix we got what we wanted. I would say though that out of the box it seems like the Finance users should not have edit access to these pages. That should be a Rock Administrator's job to configure the page. 

I would propose that we remove edit rights to the 'Finance' page (and the permissions would trickle down). Anyone see an issue with this?

**Comment by JimMichael** [comment]
The problem is that out of the box, inheritance isn't used much and (at least on my systems) just about every Finance page has explicit rights for the two Finance roles, which override any inheritance. By default, the page-level edit rights are what allow the finance roles to do *anything* useful beyond looking at stuff. 

Also, if we take away edit from all finance pages on a new out-of-box Rock install, there will need to be significant instructions for how to add the Finance roles (edit rights) to almost every single block on the finance child pages, as nothing would work (except for Admin) out of box. Said another way, you'd have a system that can't perform finance functions out of box like it does now.

**Comment by cabal95** [comment]
Unfortunately that would break a number of blocks. For example, the Batch List block uses `Edit` permissions on the Block to determine if the Add button should show up to add a new batch. A list of Finance blocks that would likely be impacted:

* AccountList
* BatchDetail
* BusinessDetail
* PledgeDetail
* PledgeList
* ScheduledTransactionList

So I think Jim is right, we would need to remove the EDIT permission from the Page and add it to instances of the above blocks.

**Comment by edmistj** [comment]
The problem is that security for editing the data should come from the Entity not the UI (blocks). We realized that a while back but it would be a big change. Perhaps though we need to bite the bullet and update the blocks to get the Data security from the Entity and not the block (at least starting in the Finance Area). Having 'Edit' rights to a block would mean you could edit it's settings not the data that it has access to.

This would break some peoples custom configs, but would be a good long-term change.

**Comment by cabal95** [comment]
Would the proper security checks then be (pseudo code):

Add New Batch -> EntityTypeCache.Read("Rock.Model.FinancialBatch").IsAuthorized(EDIT, CurrentPerson)
Edit Batch -> batch.IsAuthorized(EDIT, CurrentPerson)

**Comment by edmistj** [comment]
Yes, Financial Batches are a good example. If you look at the security the logic to Edit, Reopen or Delete a batch is actually on the Entity.  We'd need to sweep through and make sure the other Financial Blocks operate the same way.

The external blocks would need to be a bit different as they in a sense allow people who don't have View access to say Transactions to see their own transactions. We'll need a bit more internal dialog before we finalize the plan, but I think this makes more sense and provides better protection of financial data (fewer places to go wrong).

**Comment by JimMichael** [comment]
I like that idea. We’ll likely go ahead and make the block level rights mods until then, but just to clarify... nothing will change (edit rights as they are out of the box) until this correct fix happens, right? I think an admin toolbar (that isn’t terribly dangerous) for Finance pages is better than breaking Financial edit functions out of box without Admin intervention, for sure.

**Comment by edmistj** [comment]
The plan is to look at each Financial block to determine what security changes are necessary. In general we'll change security to respect the Entity. There are a few exceptions (public facing blocks and blocks also used on the Person Profile page).

We plan to get this done for v7.2. The question is should we temporarily roll-back the change that makes the Admin Tool bar appear (and put it back in v7.2) or leave as is.

**Comment by JimMichael** [comment]
Hmm... good question, I could go either way. We weren't "bleeding" from the annoying "need administrate to get admin toolbar" issue (though we acknowledge it's a necessary fix) and the new behavior _will_ be confusing to our Finance types (one of them told us her calculator was now adding wrong since we put her equipment on a UPS... yup) ;-) so rolling back would be easier for us, but not critical. Daniel probably has opinions since it's his issue.

**Comment by cabal95** [comment]
@JimMichael How does this change make her calculator add wrong?

I'm not sure it's going to affect us either way. As it stands now we have to make all CMS changes for our web peeps since they can't unless we give them full administrative privs on those pages. I don't know if rolling back really matters in terms of timing between 6.11 that would "fix" it and 7.2 that would really fix it, but I'm game either way.

**Comment by edmistj** [comment]
If we did roll it back it would be v7.1. Kind of depends on the length of time between v7.1 and v7.2.

**Comment by JimMichael** [comment]
@cabal95 The change wouldn't affect her calc... I was using it as a (real) example of how this particular person handles changes of any kind... like an admin toolbar suddenly showing up on her pages :-D

**Comment by cabal95** [comment]
There might be a few more places this is having the same problem, the following pages have explicit Edit or Administrate privileges on them (other than RSR - Rock Administrators, page Id numbers from rock demo site):

* 43 - Finance (Edit = RSR - Finance Administration)
* 76 - CMS Configuration (Edit = RSR - Communication Administration)
* 76 - CMS Configuration (Admin = RSR - Communication Administration)
* 79 - CMS Configuration (Edit = RSR - Communication Administration)
* 79 - CMS Configuration (Admin = RSR - Communication Administration)
* 142 - Prayer (Edit = RSR - Prayer Administration)
* 162 - Batches (Edit = RSR - Finance Worker)
* 238 - Prayer Team (Edit = RSR - Prayer Administration)
* 5338 - Calendars (Edit = RSR - Calendar Administration)
* 5338 - Calendars (Admin = RSR - Communication Administration)
* 5338 - Calendars (Admin = RSR - Calendar Administration)
* 5338 - Calendars (Edit = RSR - Staff Workers)
* 5338 - Calendars (Edit = RSR - Staff Like Workers)  <--- scary
* 5347 - Event Registration (Edit = RSR - Event Registration Administration)
* 5348 - Registration Instance (Action = RSR - Staff Workers)
* 5348 - Registration Instance (Action = RSR - Staff Like Workers)
* 5351 - Connections (Edit = RSR - Connection Administration)

I think those two on page 5348 with an `Action` column of "Action" are an error in the migration that created them. They don't show up in the UI for the page security or the block security so I'm guessing they were put in as a placeholder and somebody didn't update them before saving the code.

```
SELECT
	A.Id,A.[Action],A.AllowOrDeny,G.Id AS [GroupId],G.[Name],P.Id AS [PageId],P.[InternalName]
	FROM [Auth] AS A
	LEFT JOIN [EntityType] AS ET ON ET.Id = A.EntityTypeId
	LEFT JOIN [Group] AS G ON G.Id = A.GroupId
	LEFT JOIN [Page] AS P ON P.Id = A.EntityId
	WHERE ET.[Name] = 'Rock.Model.Page'
	  AND G.Id IS NOT NULL
	  AND G.IsSystem = 1
	  AND A.[Action] != 'View'
	  AND G.Id != 2
	  AND G.[Name] NOT LIKE 'WEB - %'
```
