### ISSUE TITLE
Ability to attach binary files to e-mail via Lava

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2414]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

E-mails send by Rock can already contain attachments. It would be helpful if Lava (specifically system e-mail templates and workflow actions) could attach binary files to the e-mail message.

One possible implementation route would be to pass in an empty string as `Attachments` and then check the value of that on exit and load/attach all binary files with those Id numbers. This would allow something as simple as `{% assign Attachments = '123,456' %}` to work. Realistically a slightly nicer method would be nice, like a custom lava Filter that handles all the work behind the scenes so you can just do something like `{{ binaryFile | AttachToEmail }}`.

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by garrettjohnson** [comment]
This is an awesome idea, making it medium agnostic could be helpful for future development efforts, especially considering the buzz a vcard created at RX2017 😄

**Comment by edmistj** [comment]
Part of the rearchitecting of core framework is to simplify the API for sending emails (especially attachments). Adding the ability for attachments on System Emails and as a Workflow Action is planned through the UI. If that's the case is the ability to do this in Lava needed?

The ability of doing it in Lava concerns me for two reasons. 

1. It feels a bit inelegant to have Lava filters that only work in specific contexts. For instance the AttachToEmail filter would only work in specific cases (when sending a communication).
2. Having the Lava filter but not being able to actually provide the content of the file (instead it must already exist as a binary file) seems limiting. For instance if you wanted to make a dynamic PDF you'd have to already have it as a binary file for it to work. With the proper UI dynamic attachments would be possible using workflow actions as actions exist to create dynamic PDFs and store them as workflow attributes that could then be used as the attachments.

So if we add the UI for attachments would that meet the requirements? Thoughts?

**Comment by arranf** [comment]
@edmistj I agree with you on this. Lava, to me, should feel like it works the same universally. The more caveats that are added the harder it becomes to debug and learn. A UI is much more user friendly.

**Comment by cabal95** [comment]
The Lava filter's intention was specifically when you want to _conditionally attach something that already exists in the database_, so the limitations you mention were more/less intentional. Being able to add attachments via Workflow does take care of many of these use cases. The one use case it does not cover would be System E-mails where we don't have the logic of Workflows to handle it.

For example, a system e-mail in response to a giving receipt. If they belong to a certain group we might want to attach a binary file that was uploaded into a group attribute. Having said that, I'm also game to see how much of this is an issue once Workflows have the ability to add attachments conditionally via there own logic. With more and more things moving to Workflows instead of selecting a System e-mail this may become a moot point after those new features are implemented that you mentioned.

Just to note in regards to number 1, we already have many Lava filters that only work in specific contexts. `AddLinkTagToHead`, `Postback`, `Page`, `Client`, `AddScriptLink` to name a few. Not saying a new Lava filter for this functionality is the way to go. Just that it would probably make more sense to the end user rather than `{% assign Attachments = '123,456' %}`.
