### ISSUE TITLE
Remote lava endpoint will not render group data

### ISSUE THREAD

**Issue by danielmilner** [SparkDevNetwork/Rock#2416]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using the `/api/Lava/RenderTemplate` REST endpoint to attempt to render Group data, an empty string is returned and no error is thrown.

### Steps to Reproduce

1. Post the following Lava to the REST endpoint:

```
{% group where:'GroupTypeId == 25' %}
    {% for group in groupItems %}
        {{ group.Name }} <br />
    {% endfor %}
{% endgroup %}
```

**Expected behavior:** 

I expect it to return a list of group names with the `GroupTypeId` of `25`

**Actual behavior:** 

The following is returned: `"\n    \n"`

### Versions

* **Rock Version:** 6.9 
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
@danielmilner I'm pretty sure this is a security feature.  I think you need to enable entity commands globally to use them in the Rock API.  But the problem is that then anybody who has a login to your database (such as small group leaders) can run entity commands themselves and get to all your data, including sensitive data like finances.

There is a feature in Rock v7 coming that should make this doable in a safe manner via a Webhook to Lava feature that will let you do the above put place the lava code on the server-side so the user calling the API can't submit their own (potentially dangerous) lava.

**Comment by danielmilner** [comment]
@cabal95 Thanks, I will look in to that. I thought that it was odd though that People and Content Channels were working, but Groups were not.

**Comment by cabal95** [comment]
So if you do `{% person ... %}` into the API that works?  Those should be tied together with the same security setting(s).

**Comment by danielmilner** [comment]
Yes. For example, if I take the following example from the Lava documentation:

```
{% person where:'LastName == "Decker"' %}
        {% for person in personItems %}
                {{ person.FullName }} <br />
        {% endfor %}
{% endperson %}
```
It will return a list of names.

**Comment by cabal95** [comment]
Confirmed on our production rock 6.8 install. `{% person %}` entity commands work, `{% group %}` entity commands do not. Even tried just `{% group id:1234 %}` and that doesn't work either. Don't see anything obvious in the code for the API handler (it's pretty straight forward).

**Comment by edmistj** [comment]
@danielmilner Can you try one more thing? Could you check the security for your REST user for the Rock.Model.Group model security under "Admin Tools -> Security -> Entity Administration".

**Comment by danielmilner** [comment]
@edmistj I gave my REST user Allow access for View/Edit/Administrate on that model, but am still getting the same results.

**Comment by edmistj** [comment]
OK, thanks for checking that.
