### ISSUE TITLE
[EN] Ability to make event registration fees required

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#2420]
### Description

We have a number of event registrations every year where they need to choose an option for each registrant. 

Example: For our Women's Conference, each registrant needs to choose if they are getting a Full Conference ticket - $50, Friday Only ticket - $20, Saturday Only ticket - $30, or a Student ticket - $30

With the current out of the box options, there is no way for us to make them choose a fee option so we end up with people that register but don't pay. Our only other option is to make multiple instances of the same event and different costs but then it is more difficult to get a participant list with all the form fields because data views don't play nice with registrations.

### Versions

* **Rock Version:** [6.9]  
* **Client Culture Setting:** [en-US]

**Comment by edmistj** [comment]
This has been completed for v8.
