### ISSUE TITLE
SQL Requirement for GroupType doesn't resolve Group Lava merge field

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2422]
### Description

Using the develop branch + a custom SQL requirement that uses Lava, a GroupType requirement doesn't resolve Group merge fields.  I'm still working on a fix but narrowed it down to [GroupRequirement.GetMergeObjects( this.Group )](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/GroupRequirement.cs#L259).  

If the Requirement is added to a Group instead of a GroupType, the Requirement resolves correctly.

### Steps to Reproduce

1. Add a custom group requirement of check type SQL 
2. Enter a SQL query that uses Lava:
```
select personid 
from groupmember
where groupid = {{ Group.Id }}
```
3. Save and apply to a GroupType
4. Open a Group of that GroupType, add a new member and Save
5. Set a breakpoint, the formattedSql will resolve as:
```
select personid 
from groupmember
where groupid = 
```

**Expected behavior:** 

The Group Requirement to trigger with a helpful message.

**Actual behavior:** 

The Group is NULL and not included in the MergeObject. An error is thrown in the UI.

Screenshots:

![screen shot 2017-08-31 at 6 24 19 pm](https://user-images.githubusercontent.com/1210933/29948159-572aa856-8e7b-11e7-804b-b1f2b433bdee.png)

![screen shot 2017-08-31 at 6 32 55 pm](https://user-images.githubusercontent.com/1210933/29948163-587d8ba6-8e7b-11e7-94d3-38c72269e550.png)

![screen shot 2017-08-31 at 6 35 42 pm](https://user-images.githubusercontent.com/1210933/29948166-5a2ba64a-8e7b-11e7-9e4a-41e697aa26d5.png)

**Comment by NuclearTacos** [comment]
If the `Group` was included in the Lava, you should replace `{{ Group.[Id] }}` with `{{ Group.Id }}`.  Not sure how to help you outside of that, but I'd like to think I know my Lava :wink:

**Comment by dcs619** [comment]
I double-checked per Chris's suggestion, and the Lava needed non-bracketed notation.

Unfortunately, it only works when the SQL Requirement is added to a Group. When the SQL Requirement is added to a GroupType, I get the same error.
