### ISSUE TITLE
[EN] Time Zone Support :upside_down_face: 

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2428]
### The Problem

My church, in Illinois, recently merged with a church in Florida.  Aside from being a weird look from the outside, it has caused me to start rethinking some things are handled in Rock.

It seems a time we wished would never come is upon us, and I believe we need to look for a solution to time zones :shudder:

### Specific Problems (off the top of my head)

- Small Group Finder
- Small Group Toolbox
- System Emails
- Lava
- Check-In
- Events (but I'm not familiar enough with Rock events to speak into how to handle this one)

### Recommended Changes

- I think that a Lava filter for Adjusting "Rock time" to visiting client's time zone should be implemented.  - System Emails for _new Rock installs_ should be updated to include the Rock time zone alongside any timestamp that they have.
- Campuses (and possibly) Locations should have time zones associated with them in Rock
- Group Schedules should be **presented and edited** in the native time zone of the Location the Schedule is configured for, if not, then the Campus of the Group.
- Check-In adjusting may just need display changes for when it's being presented to the user in places like Check-In Manager.

If anyone thinks of some other need or recommendation, I'll be glad to edit/add to this post.

**Comment by edmistj** [comment]
Without significant funding specifically for this feature we won't be able to commit to it.
