### ISSUE TITLE
[EN] Adjust Financial Gateway Interface To Know If Transaction is Event or Donation

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#2433]
## Description
Rock has a natural divide between payments for events and gifts that are donations and some Financial Gateways would like to process the payments differently depending on which type the payment is.

## Strategy
A relatively non-invasive and non-breaking change would be to add a `PaymentType` enum as a property to the PaymentInfo object to give some context to the gateway.

I'll take the lead on PRing this if you guys agree.

**Comment by edmistj** [comment]
There is a Defined Type called 'Transaction Type' that is used for that purpose. The two default values (Contribution and Events) have system guids. You might have everything you need with this (it's tied to the Financial Transaction model). 

I would note that some churches have more than 2 types. The Transaction Entry block has been extended in several ways to allow for it to act as a 'check-out' function. You'd probably want to have some fallback logic for cases when the Transaction Type isn't Contribution or Event.

**Comment by arranf** [comment]
@edmistj The problem with `Transaction Type`  is that it's only added to the transaction after the payment is processed by the gateway. Perhaps moving be that information to the `PaymentInfo` class would be a better route?

**Comment by mcnoodles** [comment]
This would also be helpful for us. our finance people currently rely on the simple donation dashboard as we're transitioning."

**Comment by dcs619** [comment]
I'm working with an international Rock church that could use this change as well.  

For the gateway to know what type of transaction it's processing, you have to modify core functionality in TransactionEntry, RegistrationEntry, and ScheduledTransactions to add prefix or specific GLCode support.  The PR @arranf submitted would be a much cleaner approach.

**Comment by nairdo** [comment]
@MikeDPeterson  resolved for v10 via https://github.com/SparkDevNetwork/Rock/commit/e8340eaeafe9387a69c1be8d92c8b3490c162ba2

**Comment by taylorbrooks** [comment]
Thank you!!!
