### ISSUE TITLE
[EN/Discuss] Generic Entity Attribute/Field Type

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2434]
Discussion welcome and requested. Curious what others think about this idea and also if they feel it should be fully a core feature rather than part in core and part in a plug-in. This would be a "high level" attribute, meaning it takes tinkering and effort to make it work. This isn't just a "select and go" item.

### Overview

This is a theoretical feature discussion. It has been marinating in my brain for a while, but some of the new features in v7 I think will make this actually possible. I think it would work, but curious what others think. Currently there are a number of Attribute/Field types for various entities. Group, Person, Campus, etc. But there are also a number of entities that do not have an Attribute/Field type, such as GroupMember.

### Implementation

Currently, the only way to "store" these in, for example, a Workflow is to store the Guid as text attribute and then use Entity commands to load that entity up later for use. Suggesting a `Generic Entity Attribute` type that would have a few configuration options:

1. Entity Type
2. Search URL
3. Detail URL

Once we have the Guid stored as the attribute value we can easily retrieve the actual entity object using existing (and one extra) Reflection methods defined in Rock to get the DbContext and the Service for that entity. The extra method would be to check for a `Get(Guid)` method and call it. This would allow us to use standard Lava such as `Workflow | Attribute:'Member','Object'`.

Now the hard part. How do you allow the user to "pick" these generic entities in Edit mode? For the Project Management plug-in I have been working on I took the Person Picker control and javascript and trimmed it down to a more generic system. You tell it what IconCssClass to use, what Search URL and what Detail URL. It then performs a very similar functionality to the Person Picker. When you type in a term it calls the Search URL and displays results. When you click (or hover) over an result item it calls the Detail URL to pull the HTML formatted detail results to display.

Okay great. We can have a generalized C# control that saves us some time, but we still have to write REST handlers for all those entity types so they support Search and Get Detail.  Enter Lava REST APIs. The `Search URL` and `Detail URL` could be configured to point to a Lava Webhook API that handles the Search and Detail building for that entity type. This also means you can apply custom security checking and/or even have different API handlers for different attributes you have defined of the same Entity Type.

### Examples

First off, there are other ways to do some of these but it's an example of usage. :)

- Workflow Attribute that is a GroupMember picker but the Lava API only allows them to search in specific Group Types.
- Workflow Attribute that is a Person picker but limits the search to people of the same campus as the logged in person.
- Benevolence Request picker.
- Device picker.
- Registration Picker.

### But we have SQL in Single Select

That works in cases where you only expect to have a few results. Once you have more than 25 or so results, it gets cumbersome to the user. How often have you wished for a Search feature in the Block Type picker when adding a block to a page?

Something like even a Device picker, a church could easily have over 100 devices registered between check-in devices, kiosks, digital signs, printers, etc.

### Target

I'm thinking this would be a good plug-in as not everybody would use it. But I think the "generalized Person picker" modifications would be best suited for core as that also allows for "true picker controls" to be more easily created in plug-ins and future core features when we want a nice search interface rather than a giant list of results.

I would think targeting Rock v8 makes sense for the core additions. The plug-in could be developed and released for v7 and when v8 drops updated to use the core controls rather than the ones bundled with the plug-in.

**Comment by edmistj** [comment]
I like you're idea of making this a plugin. Also don't forget about the Chosen plugin in v7 that allows you to search on long lists. This might make the SQL option workable.
![chosen](https://user-images.githubusercontent.com/548178/30243919-68b1fd38-9568-11e7-818a-6e6a1ecb2b89.gif)

**Comment by edmistj** [comment]
This sounds interesting. How about you keep piloting it in your current work and we look at it as a possible core addition in the future.
