### ISSUE TITLE
[EN/Discuss] Multiple Value Attribute

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2435]
### Description

Discussion about possibility of using the same concepts as the Matrix Attribute for creating multi-values attributes.

### User Interface

The new Attribute Matrix essentially gives us a way to store multi-valued arrays as attribute values. I'm thinking a new field called `Attribute Array` that behaves almost identical to the Attribute Matrix from a UI perspective with the exception that it only deals with a single attribute type (i.e. one column, many rows).

There are two options for storing the data under the hood.

### Option 1 - Entity objects

The first option is to store data very similar to how the Attribute Matrix stores data. That is the primary Attribute Value would be a GUID referencing the `AttributeArray` entity, which then has `AttributeArrayItem` entities pointing back to it. This provides for a simpler data storage model but complicates things like Lava. You can't simply use a Workflow and Lava to set the multi-valued array. We would need extra workflow actions and such to work with these multi-valued attributes.

This method also slightly complicates the Lava required to access. You end up having to do something along the lines of `{{ Workflow | Attribute:'MyArray','Object' | Property:'Items' | First }}`, but is functional.

### Option 2 - Delimited Values

The second option is some form of delimited values. This works great for GUID values (such as an array of Background Check Documents). The problem comes with Text attribute arrays. If the text to be stored includes the delimited value, things get weird (as an example, try using a `|` in the result text in a Workflow UEF button).

We have two ways for delimiting values. First is to just use a standard `,`, `^`, or whatever other seldom used character. This makes it super easy to assign multiple values with existing Workflow actions. Just create a comma delimited string in Lava of all the values you want to store. The second option is to store the data as a JSON encoded array (e.g. `['My First String','My Second String']`). This means a little more work on the encoding side of Lava and also complicates SQL queries (though I'm not sure much more than as a regular delimited string).

However, using option 2 means a far easier method of accessing and storing the data in Lava. We don't need extra actions. A slight tweak to the underlying C# code would allow the following. `{{ Workflow | Attribute:'MyArray','Object' | First }}`. The `Object` qualifier would properly deal with field types that handle arrays and return a `List<object>` for all the values defined. On the flip side, saving these values can be done with existing actions by just, for example, building a comma delimited string and using the `Set Attribute Value` workflow action.

**Comment by edmistj** [comment]
What would be the benefit of this over a single column matrix attribute?

**Comment by cabal95** [comment]
Primarily option 2 would provide the most benefit. However one other benefit is that this wouldn't need anything defined ahead of time in General Settings. I think we could do it on the fly when they define an Attribute since they only need to select an Entity Type as the configuration option for the Attribute.

**Comment by edmistj** [comment]
Since this is so close to matrix attributes, from a core perspective I think it would be best to stay with what's already there. The one thing where matrix attributes fall apart, and would be a challenge here to, is reportability. Getting the data filters to work with this would be very challenging and a possible performance issue.
