### ISSUE TITLE
Group Placement function of Event Registration includes Inactive states

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2437]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using the Group Placement feature of Event Registrations to place people into groups, there are two issues.

1. If the person is a member of an `Inactive` group in the selected tree, they will not be displayed for re-placement. We consider this purely a bug.
2. If the person is a member of an `Active` group but is `Inactive` or `Pending` in that group, they will not be displayed for re-placement. We consider this a configuration item.

So, we are suggesting that the first item simply be fixed. If a group is itself Inactive, it is completely ignored by the Placement system. On the Placement screen, we are suggesting that checkboxes be added to select which group membership status are considered "already placed". Verbiage is long and could use some help, but we were unsure how to shorten it without causing confusion to the end-user.

<img width="821" alt="screen shot 2017-09-07 at 10 26 37 am" src="https://user-images.githubusercontent.com/1119863/30176831-96d93d7c-93b8-11e7-90e3-85ab00fcde95.png">

Default settings for check boxes should probably be `Active` and `Pending` (i.e. if they are Active or Pending, do not show on the placement list).

### Steps to Reproduce

1. Create group tree with parent and 3 child groups.
2. Put `Person A` in one of the child groups and mark the group as inactive.
3. Register `Person A` for an event.
4. Go into Placement for that event and select the Parent group.
5. Note that `Person A` does not show up for placement.

**Expected behavior:** 

Inactive groups should not be considered as placed in a group. Other group member status should be picked by the user to verify that people are getting placed the way they wish. (In some cases, it could be correct to consider a person placed if they are Pending, in other cases only if they are Active).

**Actual behavior:** 

People do not show up to be placed that we expect to be placed.

Example: Parent group of "Youth Small Groups". Child groups of all the youth groups that exist. Some of which are in-active because the leader moved away. Registration for youth groups happens via Event Registration. Each year we go through an inactivate all the members of the groups so we can re-place them properly. Kids who register but were previously in one of the now-inactive groups do not show up. Also kids who register but were previously in a still-active group do not show up (because they already exist in the group, but are marked inactive).

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Agree #1 is a bug.

Regarding #2 I believe we should show them if they are not Active in the group. Since the placement process only allows you to add an Active group member those that are not active should be valid options. This would be different if we allowed users to add group members as Pending or Inactive, but that's not currently an option.

**Comment by cabal95** [comment]
Okay so just to clarify on #2 and make sure I'm on the same page...

When doing Placement, the only time registrants should be hidden is if they are an `Active` member of an `Active` group that is in the selected tree - correct?

**Comment by edmistj** [comment]
That sounds great.
