### ISSUE TITLE
[EN] Allow Group Type to Make Campus Required

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2438]
### Problem

People can pretty easily forget to set a Campus for a new Small Group that is created.

### Recommendation

I think it would be really helpful if you could configure a Group Type to require Groups of its type to be saved with a Campus (this is good for when you use Campus filters on the Small Group Search block and you don't want to let a small error keep a group from never being found).

**Comment by dcs619** [comment]
@NuclearTacos This is already a feature 🐱 

![screen shot 2017-09-07 at 3 45 58 pm](https://user-images.githubusercontent.com/1210933/30182114-aecac916-93e3-11e7-988d-9f34c90f21f7.png)
