### ISSUE TITLE
[EN] Link existing Content Channel Items to Event Occurrences

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2439]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Currently, if you(r staff) creates a Content Channel Item first and then creates the Event Occurrence they have to either re-create the Content Channel Item or use a carefully crafted URL to link them together.

Recommending that a new grid action button be added that allows you to select an existing content channel item. Need to come up with the proper filter, but probably not expired and not already linked to anything. Maybe other filters need to be applied too?

Display would be as a drop down list to pick from. Mockup only shows name but should probably be something like `Name (Start Date - End Date)` and sorted by Name.

We need this, so happy to write the code for this (shouldn't actually be too much to do).

### Screenshot

<img width="1255" alt="screen shot 2017-09-07 at 4 34 40 pm" src="https://user-images.githubusercontent.com/1119863/30189840-592c1cb4-93eb-11e7-9331-1c4917bc2a41.png">

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Go ahead and submit a PR. Can you make the tooltip for the button be "Link Existing Item". Might be nice if it was to the right of the Add button. 

Also could you use the new 'Chosen Picker' as it has a nice search UI built in. 

Having the Name (Start Date - End Date) is fine, but difference channels may not support End Dates or Dates at all. As long as these are gracefully supported (i.e. not shown if not configured) that would be great. If that's too much trouble then just the Name is fine.

**Examples**

If the channel does not support end dates
My Item Name (3/4/2017)

If the channel does not support start OR end dates
My Item Name

**Comment by cabal95** [comment]
1) Tooltip, yes. It's actually set to "Link Existing" now but thats easy to change.

2) I don't think I have control over the position of it. I'm using the `AddCustomActionControl()` method of the Grid and it just puts it there, not sure if there is another way to add a custom button?

3) I'll take a look at Chosen Picker, I'm assuming by "new" you mean that is a v7 thing.

4) Unless it's a new option in v7, content channels items are required to have at least a Start Date, but the End Date is optional (at least everywhere I have seen).  My plan was to check if end dates are supported and if so include the end date in the display title. Also to process the fact that Time is also optional.  But either way, yes, I need to make sure it handles the various configuration options gracefully.

**Comment by cabal95** [comment]
Ah, yes I see in v7 that it now allows a "No Dates" option. I will account for that in the PR.

**Comment by edmistj** [comment]
The order of the buttons isn't critical.

**Comment by cabal95** [comment]
@edmistj It looks like the database allows a single Content Channel Item to be linked to more than one Event Occurrence, but I don't think there is a UI to actually do that.  Should the "link existing" picker filter out Content Channel Items that are linked to ANY Event Occurrence or just linked to THIS event occurrence?

i.e. should this new functionality allow an Content Channel Item to become linked to multiple Event Occurrences.

**Comment by edmistj** [comment]
@cabal95 I'd say filter out just those already on the Event Occurrence which would allow for a single Content Channel Item to be linked to multiple Event Occurrences.
