### ISSUE TITLE
Merge Documents Fail To Download When Unsecured File Type Is Set to File System

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#2441]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Merge Documents fail to download after merging if the `Unsecured` File Type is set to `File System`.

### Steps to Reproduce

1. `General Settings > File Types > Unsecured`
2. Set the `Storage` to `File System`
3. Merge a report/data view

**Expected behavior:** 

The file would download

**Actual behavior:** 

You get redirected to the following path `http://rock.rocksolidchurchdemo.com/App_Data/Files/7946d01e-a87a-458c-bc8c-f1a894758fe3_MergeTemplateOutput.docx?attachment=True` which displays the Rock 404 page.

### Versions

* **Rock Version:** 6.9 and 6.8
* **Client Culture Setting:** en-GB

**Comment by luke-b-taylor** [comment]
Present in 7.2 as well

**Comment by TheArkChurch** [comment]
@MikeDPeterson should I open a new issue? Last week I found that we were having this issue. We are on 13.7, and it can be duplicated on the demo alpha server. The issue is with the Group Attendance Detail block. When the unsecured file type is changed from DB to FileSystem this block will not render merge templates.
