### ISSUE TITLE
ShareWorkflow discussion and collaboration

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2448]
## Topic

I have a Block built that is designed for exporting and importing Workflows. It's actually meant to be used with _any_ entity type, but Workflows was the initial itch that needed to be scratched.

## Status

A number of people have used this block successfully. A few have reported minor issues. A few have reported errors that I think have all been fixed. But it still needs lots of testing and needs some abstraction finished to be sure that there are no hard coded "Workflow" elements in there. Meaning it needs some testing on non-Workflow entities.

## Goal

The goal is to make something robust that allows for the export and import of Workflows and other information out of and into Rock. The "other information" might be things like Defined Types+Values, Lava Shortcodes, or even entire Page Structures (anybody want to try exporting their entire external website???).

As a personal note, I feel we need two levels of functionality.  "Quick" and "Packaged". Quick would be for just quickly getting something exported. Maybe to move it from Dev/Test box to Production box. Or you have a workflow that somebody else has asked for so you just do a quick export for them.

A Packaged export would be one that is intended to be shared with the community. You will spend a bit more time on the export so that things are easier for them on the import. As an example, if you are exporting a Workflow that has an Attribute Value with a default Campus, you could describe in the documentation how to go in, find that attribute, change the default to whatever campus they want. Or you could set a flag on that "campus" that says "ask the user what to replace this value with when they import". Now when the user imports they get a short list of things to pick so that when the import is done the Workflow is 100% ready for use.

The Rock Shop is a good place to find fully baked plug-ins, but sometimes you just want to make a workflow available that people keep asking you about. Or you've built a nice set of pages for accomplishing something and people keep asking you for screenshots so they can implement that on their server. This would be a first step towards getting a repository of sorts for these type of things.

## Help Needed

This started as a Shepherd project because we needed it. That need has passed so I don't have a lot of "on the clock" time to work on this. I have some "on the side" time to work on it, but I also think this would be a better community project.

If you would be interested in discussing or collaborating on this project leave a comment. Eventually this discussion will move somewhere else, but for now we wanted to get this public so it wasn't sitting stagnant any longer.

## Learn More

This wiki page has some developer-type writeup on what the export and import process is like.

https://github.com/ShepherdDev/rock-misc/wiki/Export-and-Import

**Comment by edmistj** [comment]
I'm interested in helping. I think this would be incredible to have in core when it's fully tested. I've head of some workflows where it didn't work. I'll track down those conversations and test it with the latest code.

**Comment by cabal95** [comment]
Forgot to mention, for the moment any bugs or whatever can be posted here https://github.com/ShepherdDev/rock-misc/issues so we don't pollute the main Rock issue tracker too much.

**Comment by edmistj** [comment]
When attempting to import a complex workflow I get this exception:
```The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.WorkflowActionType_dbo.EntityType_EntityTypeId". The conflict occurred in database "RockRMS-UniversalFresh", table "dbo.EntityType", column 'Id'.
The statement has been terminated.```

Here's a link to the import file.
https://www.dropbox.com/s/6913weo2adeewcs/Dev%20CFKids%20app.json?dl=0
