### ISSUE TITLE
Enhancement To Notes

### ISSUE THREAD

**Issue by edmistj** [SparkDevNetwork/Rock#2451]
Recent conversations about allowing replies to notes spurred us to share some of the other features we've been wanting to add to notes since their creation. 

# Solution Goals
1. Allow replies to notes
2. Allow for the approving of notes 
3. Allow for the sending of notifications when notes are added

Below is a rough ER highlighting the new fields being considered.

![09-09-2017_15-03-17-ssms](https://user-images.githubusercontent.com/548178/30244329-b83100f4-9570-11e7-80bc-570b34af3625.png)

## Replies
Note types would determine if replies were allowed. If allowed they could also determine the level of depth these replies could go to (default 1 level)

## Approvals
Note types would also determine if approvals were needed. If enabled a new security verb would be used (Approve) to determine who was allowed to approve these notes.

## Notifications
Note types could also determine if notifications should be sent. If enabled another security verb ('Follow') would be used to determine who was allowed to Follow either a note type (managed under user settings) or a specific note. 

When notifications were being sent the system would look to see who was following a note type/note and check to see if they were still allowed to be a follower. This would solve the use case of a pastor who left staff and should no longer be getting pastoral care notes. 

# UI Considerations
There's still some work needed in crafting the UI. We'd like to find a way of allowing admins to design the note view themselves via a Lava template. Perhaps one template for the root note and another for replies. We think this is achievable, but the challenge would be that we do need some edit controls to call postbacks to enable edit/delete. We've done this in the group toolbox, but since this is a server control that might make it a little harder.

Would like some feedback the direction. At this point we probably will need to push this to v8.

**Comment by nairdo** [comment]
Regarding Notifications, does the creator of the reply and the owner of the original note (being replied to) have to be in the security verb/role to receive the notification (once approved, if approval is required)?

**Comment by edmistj** [comment]
I would think that notification of approvals would be outside of the notification of new replies or new notes. That said I hadn't thought of notifications to approved notes. In some cases like approving prayer comments I would think no notification would be required, but in other use cases it may. Perhaps another configuration property on the note type is needed to configure the logic.

**Comment by NuclearTacos** [comment]
At the least, giving us Workflow Trigger hooks (Actions are kind of optional as long as Lava/SQL lets us do what we need) would be enough to DIY approval notifications and such.

I don't have any skin in the game yet for notes since we've buried them due to security issues on our migrated notes.

**Comment by cabal95** [comment]
### Notifications

I would think _only_ people who are `Following` the conversation would be notified. However, this brings up some questions that I dealt with in my project. I ended up creating a new `Watching` entity that is _nearly_ identical to `Following`. The classic example is I post a comment/note that sparks a massive discussion that I don't care about. I want to be able to unsubscribe from that discussion.

1. What exactly is followed to trigger the notifications? If the entity pointed to by `EntityId` then that could cause issues with wanting to follow the entity but not receive note notifications (example: Follow a group, but not receive notifications of notes posted on the group). If you are following the `Note` itself, then there is no way to receive all posts on a topic (EntityId), only specific threads.
2. It is extremely common for systems to auto-subscribe you to the discussion when you first post a comment/note. The issue with Following is that when you un-follow something the record is completely deleted. So the next time you post a comment you would be re-subscribed.

Two solutions I can see (assuming what is Followed is the original EntityId):

1. Create a new `Watching` entity like I did.
2. Add a new column to `Following` that allows for setting what kind of "following" this is. A Defined Value reference would be ideal, as that would allow for easily customized "followings" by the administrator (i.e. for use in Workflows and such).

### Approvals

I'm not sure how to handle approvals. Defining them at the NoteType doesn't seem correct as that would I believe make it far to broad. Again thinking of adding a discussion system to Groups, you wouldn't want the same list of people to be able to approve comments across all groups.

It feels like Approvals should be handled at the Block / UI level where the block that is displaying all the notes determines who is allowed to approve (e.g. in case A, "IsLeader in group discussion is attached to"). The same problem would arise if a `Topic` entity was created to be the main topics of discussion. You might want discussion comments in topic `A` to be approved by pastors only; and discussions in topic `B` could be approved by any staff member.

### UI

I like the idea of using two levels of Lava formatting. I'm torn on if this should be defined on the NoteType or defined by the block displaying the notes. The former adds some nice level of customization to notes, but feels like it would be very rarely used and might actually be harder to configure if those notes are displayed on different website interfaces (with different styles already).

**Comment by edmistj** [comment]
Back with some updates. Some good feedback above. We took all of it and made a next round of updates. 
# Watching/Following
The biggest change was around following/watching. Using the following tables was not going to give us everything we’d need. Instead there is a specific table just for this purpose. 
This will be stored using the NoteWatch table below. 

![image](https://user-images.githubusercontent.com/548178/34392772-89beeff6-eb0b-11e7-8d94-59e3531ed63f.png)

Note items in green are updated from the original ER. The requirements for watching a note include:

- I want to watch all notes of a specific type (just store the NoteTypeId).
- I want to watch all notes for a specific entity (store the EntityTypeId and EntityId).
- I want to watch all notes of a specific type as it relates to a specific entity (store the NoteTypeId and EntityId)
- I want to watch just this specific note (store the NoteId).
- When I say I, I mean me as a person OR a group (can store a PersonAliasId OR GroupId).
- I want to optionally Unwatch an item. (IsWacthing allows us to disable a watch. This could mean 

that you ARE watching as a group member, but have specifically Unwatch as an individual. In this case we would respect that you Unwatched the item).
As it relates to a watching, we would not send you a watch notification if you did not have view access to the note type. Perhaps you did have view access at one point, set a watch, but then had your view access removed. In this case we would not send you watch notifications.
There are also settings to allow the authors of the notes to auto watch their notes. If the note is a top-level note (not a child note) the watch will be on the note itself. If the note is a child note the watch would be on the parent note (perhaps this should be a setting?)
# Mentions
If enabled we would allow you to mention people. The list of people you could mention would be limited to people who can view the Entity you are adding the note to. This would add a record to the NoteWatch table with IsMentioned. This allows us to plugin to the Watch system.
# Scheduling 
Mentions would always be sent immediately.
Approvals and watch notifications can be configured to send based on the schedule of the new note watch job. This job will also determine the communication template. 
Hopefully, I’ve included all the details we discussed as a team. Let me know if you see anything missing.

**Comment by edmistj** [comment]
Oh, meant to ask too. How important is having a WorkflowTypeId on the NoteType model to launch when notes get added? Technically you can do this with the current Triggers, but they are a bit more complex to setup.

**Comment by cabal95** [comment]
Looks good to me.

I think the workflow triggers would work, especially with the coming lava shortcodes to augment loading extra data as needed. I like the simplicity of just setting the workflow to fire on the note type, but I feel like it would be a seldom used feature (useful, just seldom used), so I would vote for triggers.

**Comment by cabal95** [comment]
Hey Jon,
Just wanted to circle back on this and check if there was a concrete plan on this. Specifically if there was a target version planned.

**Comment by edmistj** [comment]
Yes mostly done in a feature branch. Will be v8. We may push mentions back to a future version.

**Comment by arranf** [comment]
Closing this due to v8 enhancements.
