### ISSUE TITLE
[EN] Change default "Download Payments" schedule

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2454]
### Description

The default schedule for the "Download Payments" scheduled job is `0 0 5 ? * MON-FRI *` or 5am Monday through Friday. Since transactions can be scheduled on the weekend, and givers are aware of transactions immediately through apps, it would be helpful to provide givers with an updated record in Rock as well as a transaction receipt before Monday.

Proposed Cron: `0 0 5 1/1 * ? *` 5am every day

http://prealpha.rockrms.com/page/115?serviceJobId=2019

* **Rock Version:** Git 9-10-2017  
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
We had to make this change on our production server. The batch totals were not matching the deposits until we did so.

**Comment by edmistj** [comment]
I submitted a roll-up migration for this for the v6.10 patch. Closing this as it will be rolled up into the final migration for that patch release.
