### ISSUE TITLE
Shortcodes Don't Support Multiple Enabled Lava Commands

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#2460]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When creating a shortcode, the "Enabled Lava Commands" section will not allow you to select and save more than one command type.

### Steps to Reproduce

1. Create a new lava shortcode
2. Select any two (or more) options under "Enabled Lava Commands"
3. Save the shortcode
4. Edit the shortcode

**Expected behavior:** 

All previously selected lava commands should be selected and saved.

**Actual behavior:** 

Only one of the selected lava commands are saved.

### Versions

* **Rock Version:** 7.0 (1.7.0.39)
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Thanks @briankalwat, this should be in pre-alpha build 1.7.0.39
