### ISSUE TITLE
Person "Giving Amount" data view filter equal to $0 returns no results

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2461]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
If the "Giving Amount" data view filter is set to be equal to $0, no results are returned.
![<a href="https://user-images.githubusercontent.com/374209/30404330-1d14cf3c-989b-11e7-9941-0a5e14cbde1b.png">https://user-images.githubusercontent.com/374209/30404330-1d14cf3c-989b-11e7-9941-0a5e14cbde1b.png</a>]()

Creating two data views, one with criteria of a "Giving Amount" value of greater than $0, and another "not in data view" will return the expected result.

### Steps to Reproduce
1. Create a "Giving Amount" filter for a Person data view equal to $0.
1. Save

**Expected behavior:**

People with $0 giving are returned.

**Actual behavior:**

No results are returned.

### Versions
* **Rock Version:** 6.10
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Implementation Note:
We'd need to translate $0 into a query where there are no transactions or the sum is $0 (gift with a refund).

**Comment by jsw-austin** [comment]
looked at and classified in bugapalooza

**Comment by jonedmiston** [comment]
@garrettjohnson  can you verify this is still an issue. In my testing it appears to be working now.

**Comment by garrettjohnson** [comment]
Fixed in V11 via https://github.com/SparkDevNetwork/Rock/commit/64fd7a5761d60940aa301acef264c8a0f2e2531c
