### ISSUE TITLE
Add bulk communication default on Communication Entry Block

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2468]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

tl;dr: Rock will not allow sending to anyone with the "No Mass Email" option from the simple email editor. Enhancement: Add a block setting.

When sending an email using the `Communication Entry` block while it's set to "Simple" mode, the communication always behaves as a bulk communication. This prevents group leaders from being able to email group members who have opted out of mass communication. Adding a default to the block settings would allow us to customize send behavior around small groups, so that leaders can still contact people in their group, while preventing other less direct communication.

### Steps to Reproduce

1. Send an email to a person with "No Mass Email" from the simple email editor.

**Expected behavior:** 

Optionally allow communication to behave as if it's not a bulk communication

**Actual behavior:** 

Always sends as a bulk communication.

### Versions

* **Rock Version:** 6.10  
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Sounds good. Should default to current behavior.
