### ISSUE TITLE
Dynamic Data Blocks Supporting Local Lava Permissions

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2474]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

TBH, I thought that DD blocks already supported localized lava permissions, but I was mistaken. :sweat_smile: 

Although I know you can accomplish the same level of control with lava shortcodes, I think it's important that using workarounds shouldn't be the prescribed norm.

### Recommendation/Reason

I think that it's not unreasonable for someone to use more complex Lava (like entity commands) in a DD block.  Also, it allows the DD block to be used to format your Lava results into a grid without requiring a special block or knowing the formatting template to make the grids you see in Rock..  I also sometimes use this for when My knowledge of lava surpasses my understanding of SQL (which is most of the time).

This is a shot of what I've done with a DD block, but required me to enable `{% sql %}` and Entity Commands Globally.   It allows me to view a serving teams attendance over the last 8 weeks and even filter down to people who have attended or not.  This is something that I couldn't have pulled off with just a pure SQL block or just pure Lava.
![image](https://user-images.githubusercontent.com/19762670/30550649-a20cd89a-9c5d-11e7-9d9c-dcf713432818.png)

**Comment by cabal95** [comment]
Implementation note: This should be done in the Block Properties (gear), not the Edit Criteria (pencil).

**Comment by edmistj** [comment]
➤ Daniel Hazelbaker commented:

PR should already be ready here: https://github.com/SparkDevNetwork/Rock/pull/3118 (in case it was missed)
