### ISSUE TITLE
Family Attendance bar graph not always reporting family attendance

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2476]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

I'm not sure what category this is. It's probably by design, but the help text is misleading if that is the case. Anyway. The (by default) 24-month bar-graph showing family attendance when viewing a person record. When viewing an Adult, it shows _family_ attendance. But when viewing a child it shows only _personal_ attendance.

Example:

Ted and Cindy Decker have no attendance data because they don't fill out welcome forms. Those lazy slobs.

Alex Decker attends kids church every weekend for the past 8 weeks.

Noah Decker has been living with grand parents for a few months so hasn't been at church.

When viewing Ted, Cindy and Alex it will reflect in the graph attendance for the last 8 weeks AND the little x/16 family attendance badge will also show 8/16 - This is expected.

When viewing Noah, it will show 8/16 in the badge, but nothing in the graph. This is not expected since the tooltip explicitly state **family** attendance for both.

Either the functionality should be updated to reflect the tooltip or the tooltip should be updated to reflect the functionality.

I would vote for updating the functionality. The Rest API calls, the badge title, etc. all say `Family` but then it isn't actually (always) family attendance.

**Expected behavior:** 

Help text and functionality should match.

**Actual behavior:** 

I stare at a kid with 9/16 family attendance but an empty family attendance bar graph and get very confused.

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
I believe the functionality is correct. When viewing a child we'd want to see they're specific attendance on the bar chart. On adults (since they don't usually have attendance) we'd want to see the aggregate of the family. We can update the tooltip on the 24 month bar chart to reflect the Individual attendance when viewing a child.

Implementation Notes
On a child's record the note should read.

"Noah's attendance for the last 24 months. Each bar is a month."

Where Noah's is the child's nick name.
