### ISSUE TITLE
Member 'OriginalValue' cannot be called for property 'IsActive' on entity of type 'Workflow' because the property is not part of the Entity Data Model

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#2477]
### Prerequisites ###

* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

I'm not sure how I would reproduce the problem on the demo site. @azturner asked me to file an issue for this error.

### Description ###

We get this error many times in a row but I cannot yet identify which workflow is causing the problem.

![<a href="https://user-images.githubusercontent.com/18447084/30560256-f3e2e7a8-9c7c-11e7-9d27-e7c3114cab86.png">https://user-images.githubusercontent.com/18447084/30560256-f3e2e7a8-9c7c-11e7-9d27-e7c3114cab86.png</a> image]()

This is the line that it's failing on: [https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Data/DbContext.cs#L570](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Data/DbContext.cs#L570)

* **Rock Version:** Rock McKinley 7.0 (pre-alpha, not recently updated) 
* **Client Culture Setting:** en-US

**Comment by azturner** [comment]
This is occurring in the Auditing of workflowaction record, so Auditing would need to be enabled for this error to occur.

**Comment by jonedmiston** [comment]
Unable to reproduce. Chris is no longer in the community and the missing image does not help. :)
