### ISSUE TITLE
Multiple Check ins for Same person with Also Select Group and Prevent duplicate checkin configured

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#2478]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When the *Auto Select Options* setting is set to *People and their Area/Group/Location* and the *Prevent Duplicate Check-in* checkbox is checked on a Check In Type, Rock check in is still allowing a person to check in multiple times.

### Steps to Reproduce
** Steps are based on the Weekly Service Check-in Area Check in type and having the test data set installed ** 
1. Set a check in type's *Auto Select Options* setting to *People and their Area/Group/Location*.
2. Check the *Prevent Duplicate Check-in* checkbox.
3. Save Changes if necessary
4. Load `(your host)/checkin` and select * Main Campus: Central Kiosk * kiosk type and * Weekly Service Check-in Area*  and select all available Check in areas and click OK
5. Click Check In on welcome screen
6. Use Ted Decker's phone number to check in Alex 623-555-2444 and click Search
7. Select the Decker family on the family Select screen
8. Select Alex Decker on the person select screen to check her record, uncheck the rest
9. Click Next
10. The confirmation screen will display click done
11. Repeat steps 5-10.

**Expected behavior:** 

You would receive an error stating that Alex was already checked in.

**Actual behavior:** 

Alex was checked in a second time and issued a new security code

### Versions

* **Rock Version:** Rock McKinley 6.9
* **Client Culture Setting:** en-us

**Comment by timlem** [comment]
I am experiencing this same bug - we are on 6.9 as well

**Comment by watermarkgeek** [comment]
Verified.  If "People Only" is selected, Prevent Duplicated Checkin works as expected, but fails as stated above on "People and their Area/Group/Location"

**Comment by edmistj** [comment]
Planning to address in v7.1 (which ships at the time v7 goes to production)
