### ISSUE TITLE
Content Channel Add from Calendar

### ISSUE THREAD

**Issue by AmyNichols** [SparkDevNetwork/Rock#2479]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When adding a content channel from a calendar event, if you click cancel, Rock sends you to the wrong screen. Please see the image below. 

![calendar issue](https://user-images.githubusercontent.com/32079117/30566642-b31a21d2-9c81-11e7-9d5f-f89d0b4e2f83.gif)

### Steps to Reproduce
1. Go to demo site and click on an calendar item occurrence. 
1. Click to add a content channel.
1. Click Cancel.

**Expected behavior:**

Clicking Cancel should return you to the Even Item Occurrence screen. 

**Actual behavior:**

You're lost. 

### Versions
* **Rock Version:** 1.6.9
* **Client Culture Setting:** English

**Comment by arranf** [comment]
Reproduced on 8.0 (pre-alpha).
