### ISSUE TITLE
Adding to Event Reg internally does not honor Event Template's Group Member Status

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2482]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Adding someone manually to an Event Registration via the internal Rock portal does not honor the Group Member Status type set on the template. This is the same bug that was fixed in 6.2 for the public facing registration pages with this description in the release notes: _Fixed the registration entry block to set the person's group member status to that of the registration template even if they are already in the group (previously it only set it when adding a new group member). _  

### Steps to Reproduce

1. Via the Rock portal, manually add someone to the registration that already exists in the linked check-in group, but is inactive.

2. Observe that the existing person remains inactive, though a new event instance is added to the group member.

**Expected behavior:** 

Group Member Status of a person manually added to an Event Registration would honor the setting on the template, regardless if the person is already in the group or not.

**Actual behavior:** 

Person's Group Member status does not get changed to Active when they already exist in the group. This issue was fixed in 6.2 on the public side, but remains an issue when adding people manually on the internal side.

### Versions

* **Rock Version:** 6.9 and prior

**Comment by cabal95** [comment]
Mentioned commit is here 07a1c6cde

**Comment by JimMichael** [comment]
Is this fix in any released version? Haven't verified 100% but on 7.4 we're not seeing it fixed.
