### ISSUE TITLE
[EN] Update Data View Picker to Show Categories

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2483]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When two (or more) Data Views have identical names, it becomes difficult to know which is which when creating a Report.  The source of duplicate names could be multiple departments that have Data Views in different categories, or even same department across multiple campuses.  The only "real" solution to this is enforcing a clunky naming structure.

Also, the current system for picking Data Views for Reports isn't very friendly to enabling non-admins to do their own Data Views/Reports.

### Recommendation
I think that it would be an **enormous** improvement to have a picker similar to the Group picker or like is on the left side of the Data View page for selecting the Data View you want to work with for a given Report.  And of course, we'd want the picker to respect the view security of the Data Views and Data View Categories.

In my opinion, it's worth losing the entity selecting box to get this.  Especially considering that 85%+ of Data Views that I work with are for People.  What I currently end up with is a huge list of Data Views of people, and a single (or just a few) of any other entity when making a Report.

**Comment by nairdo** [comment]
Hello amazing community member! We've recently moved 'feature requests' to our own "Ideas" system on our Community site at: http://community.rockrms.com/ideas

If you'd like to re-propose your idea and put it up to the vote, please re-submit your idea there. Thanks!
