### ISSUE TITLE
Truncate stored credit card numbers

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2485]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Stored credit cards show the first 6 digits of the card when selecting a payment. This is likely only an issue with NMI, as it's very closely related to #2319  ...

<img width="881" alt="screen shot 2017-09-20 at 3 53 56 pm" src="https://user-images.githubusercontent.com/374209/30671577-90fec002-9e1c-11e7-9d4c-c671671dbe3e.png">
**Proposed Solution**

- Remove/Mask first 6 digits and store card type
- Add card type, and expiration to the selection. Based on what people have stored as their card name in our install the card type might end up being more meaningful.
	- Adding a visible expiration date will also prevent cards that were declined because they were expired.
- Add card type css to the `<label>` to allow for styling i.e. `<label class="card-visa"><input ...`

### Steps to Reproduce

1. Store a payment card with NMI
2. Return to pay with saved card

**Expected behavior:** 

Don't show first 6 digits of card.

**Actual behavior:** 

Shows first 6 and last 4 of card number

### Versions

* **Rock Version:** 6.9  
* **Client Culture Setting:** en-US

**Comment by chrisfunk** [comment]
Just a side note, last 4 numbers is obviously preferred, but first 6 and last 4 is allowed according to PCI

**Comment by garrettjohnson** [comment]
Fixed with 8f475a5

@chrisfunk This seems to be a case where US federal law supersedes PCI with [FACTA](https://en.wikipedia.org/wiki/Fair_and_Accurate_Credit_Transactions_Act) which limits what can be "printed" to the last 4 digits
