### ISSUE TITLE
Rename "Giving Analysis" Block, "Giving Analytics"

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2486]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Giving Analytics block is named "Giving Analysis" in block menus. It should be changed to reflect it's name. 😄 

### Steps to Reproduce

1. Add a "Giving Analysis" Block

### Versions

* **Rock Version:** Pre-Alpha
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Added a migration roll-up to v6.10
