### ISSUE TITLE
[EN] Add length limitation to Text FieldType

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2488]
### Description

This should be a quick PR the next chance I have but wanted to get it here for any discussion.  It would be nice to be able to set a max length on the Text FieldType.

### Steps to Reproduce

1. Create a Person attribute of Text field type
2. Add a core category and Save
3. Go to the attribute and add a wall of Lorem Ipsum text
4. Groan with agony as you didn't want someone's life story stored in that attribute.

**Expected behavior:** 

Be able to set a max length for a text field, as this functionality is supported on all TextBox controls.

**Actual behavior:** 

Not able to set a max length for a text field.  Confirmed functionality not available in pre-alpha.

**Comment by edmistj** [comment]
Sounds good, go for it.

**Comment by dcs619** [comment]
Fixed in v8
