### ISSUE TITLE
Allow Group List Block Default Sort

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2491]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

In situations where a church was running on multiple ChMS products, (or admins were using excel 😄 ), group memberships may have been imported an order that differs from the order they were created in. Rock should allow setting a default sort column on the `Group List` block that sorts by the `DateTimeAdded` rather than the GroupMember ID, this would help keep the list in a logical order on the Groups/Person Profile tab.

### Steps to Reproduce

1. Change the `DateTimeAdded` to a date before other group memberships.

**Expected behavior:** 

Sort follows the date that members were added to the group. 

**Actual behavior:** 

Sort follow the ID of the GroupMembers table.

### Versions

* **Rock Version:** Git  
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@garrettjohnson I'd be fine if that was the default and we didn't add the block setting. There are some groups with null values for DateTimeAdded but those should be the exception not the rule.
