### ISSUE TITLE
v7 Support for FontAwesome

### ISSUE THREAD

**Issue by edmistj** [SparkDevNetwork/Rock#2492]
### Initial Plan
Trying to guess how FontAwesome Pro is going to work is a little tricky especially with our deadline for v7 looming. Here’s some thoughts…

1. 1.V7 will ship with the Free FontAwesome v5.

2. We will add a block under CMS Settings to Upgrade to Pro

   - This will contain instructions and links on how to purchase the update.
   - Allow you to enter your Pro Key (to be stored as a Global Attribute) and a Font Awesome Pro zip bundle. Technically the key won’t be used for anything, just provided to keep it around to display proof that the community member did purchase a license.
   - The upload will unzip and modify the files needed by Rock (fonts/less/svg javascripts)
   - In the future this block will also support uploading custom subsets.

3. FontAwesome support 4 weights (Solid, Regular, Light, Thin (thin is coming later?)) – We’ll add a new property to the site model to allow you to pick which weight to use for each site.

4. We’ll also create a defined type of other icon packs to optionally load for each site (brands, etc). This will also allow the Rock administrator to define their own custom subset.

5. A new site property will be added to the site to track which packs to load for the site.

6. We would convert the internal Rock theme and the other core themes to use the SVG framework.

### How to handle the new SVG Framework
**Option 1:**
A new site property will be added to track which FontAwesome framework type to use. The options will be ‘Web Fonts’ or ‘SVG Framework’. Since many of the current themes load the webfonts today this would allow the site administrator to determine which technology to use. New sites would default to ‘SVG’ but the current sites would be migrated to use ‘Web Fonts’ (except the core themes which would be updated to use the SVG Framework.)

**Option 2:**
The other option would be to not create this property and have ALL sites use the SVG. The theme would load the webfonts like normal AND the SVG framework would work too. Not sure if there would be contention on this or not. This would be a bit inefficient to load both, but it would be simpler to configure. 

### Icon Packs
There’s not a lot of information out there on how the icon packs are going to work. I did email them to ask and this was their response.

> The plan right now is that the packs will be separate files, npm modules, etc. We also plan on building a subsetter where you can mix and match icons from Pro proper and icon packs to pick just the ones you need.

 Still not sure if the icons in the packs will have multiple weights for each (I’m assuming so). I did ask that as a clarifying question, but have not heard back.

@garrettjohnson

**Comment by edmistj** [comment]
Update from FontAwesome guys
> yes, the plan is for each pack to be created in each style. There may be some that this might not work but our original thinking is that all icons we develop would be in each style.

**Comment by cabal95** [comment]
Is there a reason _not_ to use the SVG framework if that is the new way? FontAwesome already has SVG font file(s) - or is this something very different than just which font file to load?

**Comment by edmistj** [comment]
Many of the custom themes are wired up to load the web fonts. Also, the SVG framework is new, still working through testing it. It also doesn't support IE9 (not a huge deal, but there are still some people using it).

**Comment by arranf** [comment]
Option 1 seems like the sensible and safe route!

**Comment by garrettjohnson** [comment]
I'll be contrarian and go for option 3 😄 , just the just the web font.

Conceptually, I really like the idea of the SVG framework, it opens up a lot of possibilities that are really interesting for design; plus web fonts aren’t the best option for icons.

Based on the stated goal of expanding the number of icons available, Font Awesome 5 is going to have issues with file size bloat due to the sheer number of icons being offered. With the code currently in the repo the SVG framework option is over twice the size of the webfont. 

### File Size with Gzip
**SVG**  
127kB regular.min.js  
10.1kB fontawesome.min.js  
**137.1 kB**

**WebFont**  
8.15kB  fontawesome-pro-core.css  
220 B  fontawesome-pro-regular.css  
52.4 kB fontawesome-pro.regular-400.woff2   
**60.77kB**

Font Awesome is planning on offering a subsetting service, but it would require DEEEEP integration for an average user to take advantage of in Rock.

Since so many Wordpress themes use Font Awesome, I’m sure the file size with themes will be addressed. I just don’t think it’s worth the hassle for Rock to get SVG into v7 rather than a point update.

**Comment by edmistj** [comment]
@garrettjohnson great insight. Thanks for not only sharing your thoughts but backing up up with the numbers. I think your option 3 makes sense. We can always add SVG in the future, we'll know more then.

**Comment by garrettjohnson** [comment]
@edmistj The Font Awesome devs are definitely aware of this, found a few issues that we might want to track:
https://github.com/FortAwesome/Font-Awesome-Pro/issues/584 Most Performant/Speedy FA5 Implementation Method?
https://github.com/FortAwesome/Font-Awesome-Pro/issues/434 Loading speed of different types?

**Comment by edmistj** [comment]
I'm going to close this as I think we have a final plan for v7. Not sure what we're going to do if it's not ready  before we're ready to package v7. Looks like the free version will be ready, but the Pro likely will not. I'm thinking we'll add the fields on the model to support Pro but not include the block until Pro is released. We should be able to include that in a point release.
