### ISSUE TITLE
Shoulder the Boulder approval/publishing process

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#2494]
@arranf asked me to think through how the approval process could be improved for posting to Shoulder the Boulder, and post here with my suggestions.

**The realistic start** _(want)_
It seems to me that if we added a single-select attribute to the content channel called "Post Status", it could offer options as basic as "In progress" or "Ready to publish". That attribute should be displayed on the grid. That way the author could indicate whether the post was still being worked on, or if it's ready to be approved.

A workflow trigger could be set up to look for posts being saved with that attribute set to "Ready to publish". The triggered workflow would simply send an e-mail to people in a specific group, alerting them that a post was ready to publish.

**May be possible** _(wish)_
I haven't tried to approve content from a workflow before, but in theory it should be possible, even if it took SQL. If so, the e-mail could even include a button using the ?command parameter in the URL to approve the post via a User Entry Form action, presuming the WorkflowEntry block utilized was locked down to a group of people with permissions to do so.

**May also be possible** _(wish2)_
If a separate "Edit" form were provided for already-published articles (probably accessed via a button on the grid which linked the author to a workflow provided with the contentItemId), you could put up an Entry Form pre-filled with the existing content and take edits that way. In this way, you could leave the existing article "published" until the changes were approved  (via another Entry Form presented to the approver), at which point the workflow would push the new content from the workflow into the article in the content channel itself.

**Pie in the sky** _(dream)_
If a post was edited, and re-saved still marked "Ready to publish", it would be nice to have the workflow calculate the amount of change. If it was a very small change (0.5%?), then assume it was a typo fix or the like, and automatically re-publish the post. Otherwise, send out the notification that a post needs review just like the first time it was published. And while we're dreaming, larger edits for previously-published posts might include a diff in their email notification, making quick review possible. That might take versioning on content channel items though...

**Comment by cabal95** [comment]
Wish 1 security should be handled already by assigning the activity to a group of people authorized to approve.  If we want one-click approve, I'm assuming the e-mail would include the content of the post. Would that display correctly in an e-mail?

**Comment by mikejed** [comment]
This never got much traction for comments. For now, it's just as easy for people to ping us in the STB Slack Channel when an article needs publishing, and I'm in there frequently enough I try to keep tabs on what's being drafted. Now that I see the back end, I really think the first option would be 90% of what we need, to help distinguish articles which the authors wish to be published from real drafts. The notification e-mail, if that were also executed, would probably simply link to the article for review there, rather than being copied to the e-mail.

Any reason we shouldn't close this issue @arranf @cabal95 ?

**Comment by cabal95** [comment]
I'm good to close. We have it here for historical reasons if we need it.
