### ISSUE TITLE
Missing single quote in .lava file

### ISSUE THREAD

**Issue by luke-b-taylor** [SparkDevNetwork/Rock#2495]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

In /RockWeb/Themes/Stark/Assets/Lava/PageListAsBlocks.lava, line 7, there's a missing single quote that's present in that .lava file in other themes.  Since it's in a != ' statement, seems like not completing the quote mark would make the rest of the lava not work.

### Steps to Reproduce

Check out https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Themes/Stark/Assets/Lava/PageListAsBlocks.lava#L7 
Or insert a page menu block using PageListAsBlocks.lava and view source on a page that has child pages.

**Expected behavior:** 

Quotation Marks to be completed
Further, for {% if childPage.IconCssClass != ' %}
                            <i class="{{ childPage.IconCssClass }} fa-lg"></i>
                        {% endif %}
To work on pages that don't have Icons, and not give <i class=" fa-lg"> where there's no page icon
**Actual behavior:** 

Quotation Marks not completed
For pages that don't have icons, an <i class=" fa-lg></i> entry is given.
![2017-09-26 16_28_03-view-source_rock rocksolidchurchdemo com_page_229]
(https://user-images.githubusercontent.com/32314302/30888962-4eadb986-a2d8-11e7-84b6-fd425ec24f8c.png)

Suggestion: add a single quote to complete the clause, making line 7 the following:
{% if childPage.IconCssClass != '' %}
### Versions

* **Rock Version:** [6.2 on rocksolidchurchdemo site, 6.9 for sure]  
* **Client Culture Setting:** [en-US]

**Comment by edmistj** [comment]
If someone attaches a SQL to update it via a migration I can take it from there to get it into a migration.

**Comment by cabal95** [comment]
@edmistj Unless I missed something, this is just a file on disk in the repo that needs a single quote typed in. I can do a PR but wanted to make sure I wasn't missing something.

**Comment by edmistj** [comment]
Right! I didn’t check hustled added the note real quick while I waited for a compile. Sounds good.

**Comment by luke-b-taylor** [comment]
I have an edit done and can submit a PR, @cabal95 suggested I submit an issue instead.

**Comment by edmistj** [comment]
Send over a PR :)

**Comment by edmistj** [comment]
Fixed via PR
