### ISSUE TITLE
Adding a page route to a page with children breaks PageListAsBlocks.lava

### ISSUE THREAD

**Issue by luke-b-taylor** [SparkDevNetwork/Rock#2498]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
Adding a page route to a page that has children which would be displayed in a Page Menu, which uses PageListAsBlocks.lava, breaks the links generated by PageListAsBlocks.lava.  Links are generated ~/330 rather than ~/page/330

### Steps to Reproduce

1. Add a route to a page which uses PageListAsBlocks.lava in a PageMenu block.
2. Reload the page and attempt to follow a link in the Page Menu block to, e.g. reports, which is ~/page/330
3. Get the Rock 'page not found error' because the actual link generated is ~/330, as though 330 is a route to the page

**Expected behavior:** 

Adding a route to a page doesn't affect PageMenuAsBlocks.lava, following the normal naming convention of ~/page/### 
PageSubNav.lava menus are not affected.

**Actual behavior:** 

Adding a route to a page causes PageMenuAsBlocks.lava (in the Rock and Stark themes at least) to omit the /page/ from the address, leading to links using the naming convention of ~/###

### Versions

* **Rock Version:** [6.2 (demo site) 6.9]  
* **Client Culture Setting:** [en-US]

**Comment by luke-b-taylor** [comment]
I figured out the issue.  Since I'm new, should I tell someone else to fix, or just fix and do a PR?  it's swapping a childPage.Id for a childpage.Url on line 6 in the lava file

**Comment by edmistj** [comment]
Just submitting the PR is fine. Thanks Luke!
