### ISSUE TITLE
PersonPicker JavaScript permanently modifies autocomplete UI plugin.

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2518]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Currently, the way the personPicker.js script initializes, it overrides the default implementation of `_renderItem`. This means that any other uses of the jQuery UI autocomplete gets that functionality. There are a few posts that show how to accomplish the same functionality but not extend the prototype, rather they set it per-instance.

I will look at a patch for making this change, but would like to get a thumbs up first to make sure there is not a specific reason it was done this way.

### Steps to Reproduce

1. Create a custom Control that intends to use autocomplete
2. Notice that the person picker JS runs during autocomplete on your custom control.

**Expected behavior:** 

Do not pollute prototype declaration of standard library.

**Actual behavior:** 

Standard library is modified.

### Versions

* **Rock Version:** git
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Sounds good. I think it might be something that we'd pull in post v7. That way we could test it more in the pre-alpha phases of v8.
