### ISSUE TITLE
Storing Lava in KeyValue attribute will break when Lava contains '|' filters

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2519]
### Description

When adding an attribute of type KeyValueList, saving a snippet of Lava in the Value field will render an additional attribute when the Lava contains a '|' character.  

before save:
![screenshot 2017-10-06 10 52 12](https://user-images.githubusercontent.com/1210933/31284149-c13f1922-aa85-11e7-83df-02df5a22eaf4.png)

after save and refresh:
![screenshot 2017-10-06 10 52 23](https://user-images.githubusercontent.com/1210933/31284148-c13c3a04-aa85-11e7-87dd-12bbb2cf6072.png)

This is due to the way KeyValue pairs are stored in the AttributeValue table with the pipe as the pairing delimiter:
`Name^{{ Person.FullName | Capitalize }} | HomePhone^{{ Person | PhoneNumber:'Home' }}`

I can look into this further, but it seems like a quick fix would be using HtmlEncode and HtmlDecode with a KeyValueList's Values.  If anyone has other suggestions before a PR is started, I'm welcome to discuss.

### Steps to Reproduce

1. Add an [Entity] Attribute of type KeyValue List
2. Add an AttributeValue containing Lava with a filter
3. Click Save and refresh

**Expected behavior:** 

The Lava to be rendered as what's stored in the database

**Actual behavior:** 

The Lava is broken up, and a a non-existent Attribute Value Pair is rendered

### Versions

* **Rock Version:** tested on v6.9 and v7.0
* **Client Culture Setting:** [en-us]

**Comment by cabal95** [comment]
For the record, it also means things go wonky if you do this in Lava: `{{ Person.Age }}^3`

**Comment by edmistj** [comment]
Encoding the value seems like a good enhancement. You'd probably want to URLEncode it though instead of HTMLEncoding since HTML Encoding would still return the |. Thanks for the heads up on the PR.

**Comment by chrisfunk** [comment]
@dcs619 I am am probably stating the obvious here, but we would probably need to unencode it before displaying or processing the value.

**Comment by edmistj** [comment]
Updated this in the v6.9 hotfix to allow a church to pull in the change. It will be in v6.10.
