### ISSUE TITLE
Attribute of type Page Reference cannot be used in Lava

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2520]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you create an Attribute on something, for example a Content Channel Item, of type `Page Reference`, there is no clean way to use the value in Lava without SQL - unless we are missing something very obvious.

When accessing the value via `{{ item | Attribute:'Page' }}` you get the title of the page. When accessing via `{{ item | Attribute:'RawValue' }}` you get the Guid of the page (or `Guid,Guid` if it has a route defined). This means the only way to actually get a usable link is to use the `{% sql %}` command to get the PageId from the Guid.

Not sure the best fix, possibly modify the PageReferenceFieldType to be an IEntityField so it can return the Page object, but that doesn't work properly when there is a route to the page. Another option is a lava filter that accepts the raw value and returns a link to the page (in the format of `/page/#id#` or `/route`).

### Steps to Reproduce

1. Create attribute of type Page Reference
2. Try to construct a clickable link in Lava.
3. Weep

**Expected behavior:** 

Ability to generate link from attribute.

**Actual behavior:** 

No can do.

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
If `{{ item | Attribute:'Page','Object' }}` doesn't get you what you need I think a new Lava filter would be the best solution.

**Comment by cabal95** [comment]
Just verified, and the `,'Object'` syntax also returns just the name of the page.

**Comment by cabal95** [comment]
Available as plugin in the Rock Shop.
