### ISSUE TITLE
Giving Analytics error with dataview

### ISSUE THREAD

**Issue by jbgarrett12** [SparkDevNetwork/Rock#2523]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

I am getting an error with giving analytics when I try the 'include all people from dataview' option. 
<img width="861" alt="capture13" src="https://user-images.githubusercontent.com/27223144/31406196-7f9604ee-adce-11e7-9126-e9601027a846.PNG">

### Steps to Reproduce

1. Use band giving report dataview in Giving analytics
2. Use 'Include all people from dataview' option.

**Expected behavior:** 

To see all people that are in the dataview even if they do not have any giving data for that specified date range in giving analytics. 

**Actual behavior:** 

Error code.

### Versions

* **Rock Version:** [Rock McKinley 6.9]  
* **Client Culture Setting:** [ en-US]

**Comment by dcs619** [comment]
@jbgarrett12 Can you post the parameters you're using for the Band Dataview?  

This looks like a larger issue with Giving Analytics and Dataviews.  If I try something similar on the [demo site](http://rock.rocksolidchurchdemo.com/page/5342) using the Members Data View, Giving Analytics goes into infinite "working" mode and eventually errors out. 

<img width="1135" alt="screenshot 2017-10-12 16 12 46" src="https://user-images.githubusercontent.com/1210933/31516977-5dbfc580-af68-11e7-9ee5-b04e1415d214.png">

<img width="1150" alt="screenshot 2017-10-12 16 15 21" src="https://user-images.githubusercontent.com/1210933/31517029-92249f08-af68-11e7-8cc5-53988ab7a62a.png">

**Comment by jbgarrett12** [comment]
![capture15](https://user-images.githubusercontent.com/27223144/31517956-98d14b14-af6b-11e7-875c-11adff79be37.PNG)
Is this what you're looking for?

**Comment by drychlik76** [comment]
Guys, I can confirm this same issue.  I was just about to open this as a bug.  Thank you confirming it.  We are using version 7.2.

**Comment by jbgarrett12** [comment]
We have found that giving analytics is generally buggy overall. 

Jonathan Garrett
Systems Coordinator
5 Point Church
5point.tv
864-850-0580

**Comment by edmistj** [comment]
@jbgarrett12 If you find a bug(s) in the analytics block we'd love a report of it so we can address.

**Comment by jbgarrett12** [comment]
When we select a dataview to limit the results and also select a specific account we get a long error and I also duplicated this on the demo site. 

Jonathan Garrett
Systems Coordinator
5 Point Church
5point.tv
864-850-0580

**Comment by jbgarrett12** [comment]
You also have to click details. It works fine in chart I believe. 

Jonathan Garrett
Systems Coordinator
5 Point Church
5point.tv
864-850-0580
