### ISSUE TITLE
Add Support for "Include Page List" in pageNav & pageSubNav Lava Templates

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#2530]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
The out-of-the-box lava templates for `pageNav` and `pageSubNav` do not support the "Include Page List" function of the PageMenu block (from what I could tell). The lava below appends the "Include Page List" pages below the child pages. I'm not sure if this is the best way to add support, or which lava templates need it added to them, but I thought i'd start the conversation. @edmistj do you have thoughts?

```
<section class="nav-sub">

{% if Page.DisplayChildPages == 'true' and Page.Pages != empty %}
    <div class="list-group">

        {% for childPage in Page.Pages %}
            <a href="{{ childPage.Url }}" class="list-group-item {% if childPage.Current == 'true' %}active{% endif%}">
                {{ childPage.Title }}
            </a>
        {% endfor %}

        {% for includedPage in IncludePageList  %}
            {% assign path = 'Global' | Page:'Path' %}
            {% assign attributeParts = includedPage | PropertyToKeyValue %}
            <a href="{{ attributeParts.Value }}" class="list-group-item {% if path == attributeParts.Value %}active{% endif%}">
                {{ attributeParts.Key }}
            </a>
        {% endfor %}

    </div>
{% endif %}

</section>
```

### Steps to Reproduce
1. Add PageMenu block to a page.
1. Use pageNav.lava or pageSubNav.lava
1. Add Pages to the "Include in Page List" field

**Expected behavior:**

Include Page List should be output in the block.

**Actual behavior:**

Include Page List is ignored.

### Versions
* **Rock Version:** 6.9
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1122450646587021">image.png</a>

**Comment by edmistj** [comment]
@briankalwat when doing the PR could you add this to all the themes with this Lava asset?

**Comment by cabal95** [comment]
@briankalwat I see that you added a commit but not a pull request yet. Is there more code work that you need to do or does it just need the PR created?

**Comment by briankalwat** [comment]
@cabal95 honestly I've been having trouble figuring out how to open the PR as our fork of the repo isn't in sync + not being familiar with which branch to open the PR to, etc. I tried to figure it out but should have just asked for help when I got stuck.

**Comment by cabal95** [comment]
No worries. I'll see if I can get with you on Slack to either help you get a PR going yourself or maybe pulling the change and submitting one myself. (I'm out for the rest of the date)

**Comment by briankalwat** [comment]
I'd love to learn the process so I can contribute more in the future!

**Comment by bilkie1** [comment]
In version 13.7 this implementation is missing from the PageSubNav.lava in the Stark Theme after the first {% endfor %}

         {% for includedPage in IncludePageList %}
            {% assign path = 'Global' | Page:'Path' %}
            {% assign attributeParts = includedPage | PropertyToKeyValue %}
            <li{% if path == attributeParts.Value %} class="active"{% endif %}>
                <a href="{{ attributeParts.Value }}">{{ attributeParts.Key }}</a>
            </li>
        {% endfor %}
