### ISSUE TITLE
Lava filters GroupById and GroupByGuid

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2533]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

In Lava, we often have Group Guids and, to a lesser need, Group Id numbers stored in Attribute values but need to get data about the Group. Currently the only way to do this is to enable Entity commands or Sql commands. When working in workflows this is usually not feasible.

I have had for a while a pair of Lava filters `GroupByGuid` and `GroupById` that function similar to their Person counterparts.  Would these be worth including in core?  I have hesitated for a while submitting a PR because I think it's possible to abuse these more than the Person counterparts. But I have also found myself sending them to more and more people individually to solve problems for them.

Should I submit a PR to include these?

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
This seems to make good sense to me.
