### ISSUE TITLE
Recurring Payments Cannot Start on the Same Day

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2534]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When setting up a recurring charge Rock should allow the first charge to be the same day it's created. Rock currently requires a recurring transaction to be the following day. If a gateway is unable to support same day transactions, Rock should automatically change the date to the following day in the date selector.

See here: https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Finance/TransactionEntry.ascx.cs#L2129

### Steps to Reproduce
1. Create a recurring transaction with a start date of today

**Expected behavior:**

Transaction is successfully processed

**Actual behavior:**

Requires changing date to next day

### Versions
* **Rock Version:** Git
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
This is what I'm seeing on the demo site. Am I missing something?
![giving](https://user-images.githubusercontent.com/548178/31632475-e17f36ec-b271-11e7-8daf-a156efd10da3.gif)

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
