### ISSUE TITLE
Make inline validation help optional

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2540]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Currently, Rock will always remove form feedback, favoring requiring the validation control summary instead of displaying the error inline. (https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Scripts/Rock/Validate/validation.js#L42 (JS Clears all inline help) ) 

Making inline errors an option would help improve UX since it's valuable to provide feedback within the context of an action. When forms get longer, providing clear info on why validation failed without scrolling to the top or bottom of a page will be valuable. Making inline optional also allows [real-time feedback ](https://alistapart.com/article/inline-validation-in-web-forms)

**Expected behavior:**

Optionally display inline validation label.

**Actual behavior:**

Inline validation is cleared in favor of validation summary.

### Versions
* **Rock Version:** Git Oct 15, 2017
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
We should probably discuss implementation notes before coding.

**Comment by garrettjohnson** [comment]
@edmistj How about `data-inline-validation="true"`? It potentially gets messy for controls with children (addresses), but children make everything harder 😂

**Comment by garrettjohnson** [comment]
@cabal95 Yeah, remove L42&70. It works in a lot of places, and it doesn't work in a lot of places. There are areas where validation doesn't use the [.NET validation controls](https://msdn.microsoft.com/en-us/library/debza5t0.aspx), like the transaction entry block found on the give page, which complicates a wholesale change.

I haven't figured out how to force Rock to inject the jQuery Unobtrusive markup... the jQuery plugin would/will be a drop-in replacement for the controls currently using the WebUI client side validation. [This article](http://www.blinkingcaret.com/2016/03/23/manually-use-mvc-client-side-validation/  )shows a lot of possibilities on expanding messaging on the client side.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
