### ISSUE TITLE
SQL Lockup with too many incoming SMS messages

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2552]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Okay, so awhile ago we found an infinite loop with generating check-in security codes. We just found another. There is an infinite loop that happens to generate an SMS Response Code. There are 898 possible code numbers (100 - 999, subtract out `666`). And if all of those have been used in the past 30 days then the `while` loop never exits and SQL starts chewing up CPU cycles like crazy - and those messages never get passed on to the final person.

https://github.com/SparkDevNetwork/Rock/blob/8142b5fc1cbefa1545079df7c13fa6da0204dd17/Rock/Communication/Medium/Sms.cs#L195

I think a good solution would be to forget the random number generator and just go sequential until we find an available number. I'm not sure there is a reason to use a random number in this case.

If we do need random, I would say we use a loop counter and after X (say 2,000?) loops, increase the max random number by 1,000 as well.

This also means there are a few places with ResponseCode that, I think, use a 3-digit regex to find a response code that would need to be modified to look for a 3+ digit code instead.

### Steps to Reproduce

Send 898 message to a Twilio number that sends to a staff member. Then try to send one more.

### Versions

* **Rock Version:** 6.9
* **Client Culture Setting:** en-US

**Comment by MikeDPeterson** [comment]
If it needs to be random, and with no risk of spins, perhaps Rock could pre-generate a List of response codes in memory, and sort them in random order. Then anytime it needs a new one, just take the next one from the list, and start from the beginning each time it gets to the end.  The pre-generated list could be something of reasonable size, perhaps as large as 1 to 9999999, or maybe as small as 100-999. If this solution works, maybe a similar approach could be used for checkin labels

**Comment by cabal95** [comment]
There hasn't been any comments on this about it needing to remain random. So I am going to propose the following algorithm:

* System generates a list of sequential numbers that are available, between 100 and 10,000 and skipping 666, and have not been used in the past 30 days. This list will probably be cached in some way to help deal with a large influx of new responses to a large outgoing text.
* The `GenerateResponseCode` method will then be wrapped in a mutex and loop through the list of in-memory available response codes.
  * If still available it is removed from the list and returned to the caller.
  * If not available, it is removed from the list and the next number is checked.
  * If the list is exhausted then a new list is generated by increasing the maximum number to 20,000 (and continue adding 10,000 if the new list is empty).

Any regular expressions that look for 3-digit @codes would also be updated to look for 3+ digits.

If there are no objections then I will work on this and submit a PR. If later we decide it should still be random then I would say the "cached list" could be order-randomized after it is generated.

**Comment by edmistj** [comment]
Random would seem to be desirable as with sequential you would be able to know for certain which previous codes would work. Since this code only get's generated on responses would lowering the period from 30 to 5 days help (and adding loop prevention).  Otherwise I'd say we add the possiblity of 4 digits if there aren't any remaining 3 digit codes.

**Comment by cabal95** [comment]
Okay, I'll setup a PR for the "loop prevention" plan of trying 100-999 first and if nothing is available in that range then move the top-end limit up by 1,000 at a time (i.e. so we don't jump from running out of 3-digit codes all the way to a randomly picked @9827 code).

As for the number of days, 5 days might be a bit short. Maybe 14 days (2 weeks) would be a good in-between.
