### ISSUE TITLE
Duplicate Finder should consider Suffix

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2558]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We have a lot of people in our area with the same first name in the family. Having a "Jr" or even "3rd" is not unusual. We are seeing a lot of possible duplicate records in the 60-70% range but are actually Sr and Jr records. We would like to suggest the following enhancements to the duplicate finder:

* If _both_ records have a suffix, and they differ (Jr. vs. Sr.) then the confidence should drop considerably
* If records have the same suffix, confidence should rise considerably
* If one of the records have no suffix, the confidence shouldn’t be adjusted (since it means one of the records may simply be missed a suffix)

The same might also be valid for `Title`.

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Sounds good. I'd not do that for title since they are not as meaningful as suffix (Ms Mrs, etc)

**Comment by cabal95** [comment]
Okay so since all the logic for this is inside a stored procedure, is the best way to handle a PR on this to modify the stored procedure SQL so that it works and then post the fully modified SQL for one of you guys to implement? I'm happy to do more than that but don't know where to start with a stored procedure update for Rock.

**Comment by edmistj** [comment]
A new SQL change would be great. You could also write the migration and just send us the file where we'd just copy/paste in the guts.

**Comment by azturner** [comment]
Added a migration roll-up with this change.
