### ISSUE TITLE
CMS Site Configuration Edit domains tooltip/help

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/Rock#2561]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When modifying a site in CMS configuration the help tooltip is innacurate as to 'Domain(s)' formatting
![site detail _ rock rms - google chrome 2017-10-26 10 18 14](https://user-images.githubusercontent.com/8688424/32061381-0b881734-ba37-11e7-93fa-bf67f53ca005.png)

### Steps to Reproduce

1. Navigate to a Site Detail page (in edit mode, typically under Admin Tools -> CMS Configuration -> Sites -> Edit a site
2. Click the tooltip/help for the 'Domain(s)' setting
3. Change the contents of the 'Domain(s)' field to be comma-separated (as the tooltip says). For example, when adding another domain
4. Click Save

**Expected behavior:** 

I expect the tooltip/help to be accurate re: proper formatting in the text box

**Actual behavior:** 

When you hit save it changes the formatting to carriage return/separate lines for each domain

### Versions

* **Rock Version:** 6.9, 6.8, 6.6, 6.7  
* **Client Culture Setting:** EN-us

**Comment by edmistj** [comment]
Fixed in hotfix branch.
