### ISSUE TITLE
Required fields with default values not populating on registration forms. 

### ISSUE THREAD

**Issue by mrskatiewalters** [SparkDevNetwork/Rock#2564]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Required fields with default values not populating on registration forms. v6.9

### Steps to Reproduce

1. Registration form
2. Require a field
3. Add default value
4. View form
5. Does not populate...

**Expected behavior:** 

Populates the required field with default value.

**Actual behavior:** 

Does not populate with default value.

### Versions

* **Rock Version:** [v6.9]

**Comment by garrettjohnson** [comment]
Confirmed on 6.9, if left blank the default is populated when the form is submitted, but there's never any indication of the default value.

**Comment by tstephens17** [comment]
Do we have a target on when this will be fixed?

**Comment by edmistj** [comment]
We'll milestone this for v8.4.

**Comment by ethan-sparkdevnetwork** [comment]
Changed logic to populate a registration attribute under two scenarios:
1. If the current value is null and and Set Values is true
2. If the current value is null or empty and required is true.

**Comment by tstephens17** [comment]
Thanks guys. I updated my RegistrationEntry.ascx.cs in 7.4 and it is now working for me.
