### ISSUE TITLE
Marking Workflow Activity as Inactive does not prevent it from running

### ISSUE THREAD

**Issue by theundecided** [SparkDevNetwork/Rock#2566]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

(im new to github bug reporting....so bare with me. )

I suspect that inactivating a workflow activity does NOT prevent (at the least) a *Send Email* action from occuring/processing.   

### Steps to Reproduce

[Large screenshot](https://www.screencast.com/t/je81313qZ0)

**Expected behavior:** 

the entire activity be disabled

**Actual behavior:** 

emails sent to group (which I had set to the groups I wanted to be set to when I finished and launched the wf) with all content that had at that point been setup. 

### Versions

* **Rock Version:** Rock McKinley 6.9 
* **Client Culture Setting:** *[Sorry not sure what im supposed to put here]*

**Comment by edmistj** [comment]
On your screenshot, is your callout balloon pointing to the wrong checkbox? The "Activated with Workflow" checkbox is only available at design time and can't be changed from within your workflow.

When you say "inactivating a workflow activity" do you mean at design time or during the workflow runtime?

**Comment by theundecided** [comment]
I should have changed the color of the callout. that was a extra piece of data wasn't sure it was relevant.....kinda new to this type of bug reporting ;P I had at one point checked `Activated with Workflow` in addition to `inactivated` accidentally. realized my mistake and deactivated `activated with workflow` however actions from that activity still triggered.

**Comment by edmistj** [comment]
I'm still not quite certain I understand the issue. Could you layout steps to reproduce?

**Comment by rutledgek** [comment]
I had a workflow that I added a delayed Delete activity that activated with workflow.  I ran into some issues that the workflow was deleting with the delay set to Wednesday and it was wednesday(I assumed it would wait until the next wednesday).  All that is to say when I realized that it was deleting right away, I made the activity inactive.  However, is still ran when the workflow was triggered.

**Comment by theundecided** [comment]
im unsure how best to validate this. but I don't know if `inactivate` switch .... is working..... thats the basis. I will have to replicate this on my sandbox. however I dont have a good  _communication that doesn't actually send out a communication_ ... thing.

**Comment by cabal95** [comment]
I don't know if this is exactly what @theundecided is referring to, but I was able to replicate @rutledgek's issue on the demo site. Workflow setup as thus:

![screenshot-2017-11-8 workflow configuration rock rms](https://user-images.githubusercontent.com/1119863/32564707-f838e0fe-c469-11e7-8c07-2d222af58cfd.png)

Executing the workflow results in all three activities being run.

**Comment by theundecided** [comment]
I wasn't sure where exactly something went wrong....thats what I figured it was.... wan't sure lingo / how best to describe  or  how to test. thanks
