### ISSUE TITLE
[Discussion] Enhance Event Registration for Kiosk use

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2568]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We have been discussing how to get the ability to allow people to do event registration on kiosks, with swipe-to-pay like they can for giving. We think it would be do-able, but want to get some feedback before we start digging in too deep to determine true feasibility, but we _think_ we can achieve what I am outlining below.

## Needs/Wants

* To allow the individual to walk up to the kiosk and select themselves via phone number ala Children's Checkin. (We have this built already)
* To avoid display of personal information - email, phone, and address. (Masked email or phone may be okay -- i.e. (818) 555-1234 could be (**8) ***-**34
* To permit the payment of initial fees .
* To be able to "e-sign" using inline signing (in theory should work as is, though a keyboard on the kiosk would be required).

## Planned implementation

* A block setting to enable the use of "masking fields" instead of standard fields for sensitive information (phone numbers, email, address, possibly birth date).
* Ability to pass in the "Current Person" via a URL parameter, such as PersonGuid=xyz. (dial-by-number to find yourself in another block, gets passed to this one as person Guid)
* Potentially, ability to use inline signing if it can be done at a kiosk.
* Support for "swipe-to-pay" instead of manual entry via some sort of block setting.

The "masking fields" would be special use (though they could be made available as general use fields too) subclasses of the main fields that would mask the display.  I.e. MaskedPhoneNumber would inherit from PhoneNumber but mask the output. The real data would probably be stored in ViewState and if they don't make changes to the masked data in the textbox then the "real" value is returned, otherwise the textbox value is returned. This would probably only apply to Person fields and not any attribute fields - though we might look at that too.

### Versions

* **Rock Version:** 6.9
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Here's a couple of thoughts/questions:

There are some kiosks block available today to do many of these parts (the phone -> person match).

**A block setting to enable the use of "masking fields" instead of standard fields for sensitive information (phone numbers, email, address, possibly birth date).**

How do you see this implemented. One could add a setting to FieldTypes to have a 'masked formatted value' but that would be a larger change.

**Ability to pass in the "Current Person" via a URL parameter, such as PersonGuid=xyz. (dial-by-number to find yourself in another block, gets passed to this one as person Guid)**

I'd recommend using the new one-time use person tokens

**Potentially, ability to use inline signing if it can be done at a kiosk.**

Not changes would be needed for this right?

**Support for "swipe-to-pay" instead of manual entry via some sort of block setting.**

The giving functionality on the Kiosk blocks already does this. It would only be usable on the older payment processors (Payflow Pro). Would be tricky to get this to work with NMI and would increase the PCI risk.

**Comment by cabal95** [comment]
> How do you see (masking fields) implemented.

I was thinking new field types, such as `MaskedPhoneNumberFieldType` that inherits from `PhoneNumberFieldType` but overrides how it is displayed. Another option would be to modify the originals to add a "mask value" setting. As far as I can tell from looking at the RegistrationEntry code, these are all generated on the fly so either method would work as we would just modify the code to either use the new field type or set the configuration value.

> I'd recommend using the new one-time use person tokens

That might work too, I haven't had a chance to play with them yet to see exactly how they work, but same implementation concept. Just some way to ensure the user isn't _actually_ logged in so there is no (minimal?) risk of the next person "being them".

> Inline Signing

As far as I know, no major changes would be needed. Possibly just some CSS formatting as they will likely need to scroll to see everything so we might need to implement some CSS/JS to make that more user friendly.

> Swipe to Pay...

That was our thought - lift the existing Kiosk giving functionality. Does that block currently not work with NMI (and other theoretical 3-step gateways) ?

In our internal discussions on this we came up with only two _major_ roadblocks to using kiosk-event registration. There were a few minor one (such as the login thing), but there are fairly simple ways around those more minor items. The two major items were:

1. Not showing personal contact information on a public display as sometimes people stand uncomfortably close to the person using the kiosk.
2. Ability to swipe to pay vs trying to key in the CC info for the same reason above.

Obviously, if you have a massive multi-form registration it's not going to work great on a touch-based kiosk device, but that would be an implementation decision of the Rock admin, not a design decision of the block. Though I think some things we can, down the road, make work better on kiosk devices (such as check box fields, radio buttons, boolean, etc.) with CSS - but that would be a separate discussion.

**Comment by edmistj** [comment]
So this would be a new registration block?

**Comment by cabal95** [comment]
Seeing as the RegistrationEntry block is 5,000 lines of code; ideally this would be a simple enough modification to just be a block setting for "kiosk mode". In the future if #2601 goes anywhere it could become it's own block that re-uses the major components without having to keep two code-sets up to date.

**Comment by cabal95** [comment]
For the moment, we will run this as a forked version of the stock block. After playing around with the internals of Event Reg more I don't see it viable to make this two separate blocks until we can make it less monolithic of a process.
