### ISSUE TITLE
Checkin Countdown Not Working

### ISSUE THREAD

**Issue by debbiethurston** [SparkDevNetwork/Rock#2570]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

[Checkin Countdown is not showing on Kiosk]

### Steps to Reproduce

1. [The only way to reproduce is to look at it at each instance and it is not there]

**Expected behavior:** 

[When a kiosk is active but the schedule has not yet triggered the ability to checkin we would expect that the time would count down as it has before.]

**Actual behavior:** 

[The countdown is no longer visible]

### Versions

* **Rock Version:** [6.9]  
* **Client Culture Setting:** [Church fully utilizing Rock for all aspects of ministry]

**Comment by JayGreentree** [comment]
Have you checked to make sure your kiosk devices have valid IPs listed on the devices page in Rock? I have 6.9 running and have checked this and that resolved this issue for me.

**Comment by debbiethurston** [comment]
That is fine except that once we indicate the IP, then we no longer get the checkin configuration.  Because we use the same kiosk at different times for different areas, we need the ability to configure it.  The IP skips past the configuration.  So my question is, if we need to have the IP address, how do we "force" it to go to the checkin configuration screen.

**Comment by debbiethurston** [comment]
Thank you
