### ISSUE TITLE
[EN] Add Account Type filtering to Finance Blocks

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2574]
### Description

As part of giving features I built out for River Valley, upcoming PR to add Account Type filtering support to the Account List and Giving Analytics blocks.  If there are other blocks that need Account Type filtering I can add them too.

The Account Type field is already available on creation, but filtering by that type is missing in both v6 and v7 versions.  The v7 interface will look different as this filter would sit under the Advanced Options list of Giving Analytics. 

### Screenshots

![screenshot 2017-11-06 13 44 05](https://user-images.githubusercontent.com/1210933/32458007-e789d096-c2f8-11e7-983f-ef58017d0e04.png)

![image](https://user-images.githubusercontent.com/1210933/32457763-2b7e3c84-c2f8-11e7-8cba-be0a63289466.png)

![image](https://user-images.githubusercontent.com/1210933/32457798-40b73c2c-c2f8-11e7-9497-6112d9aace46.png)

**Comment by edmistj** [comment]
@dcs619 Updating the Account Detail block is good. 

Bit worried about the Giving Analytics. That is a very complex block with a lot of moving parts. Below are some implementation considerations:

* Since most people would not need this it should be implemented as a block setting to enable (default hidden)
* If selected the account list above would update.
* The trick comes when they select a type filter the account list but don't actually pick an account. This would mean that all accounts of that type would be valid. Seems like this would be a deep change as you may need to update the stored procs behind the scenes. These procs have been worked and re-worked to ensure the best performance. If you do want to make this change we probably should talk further when you have a detailed implementation plan. Also, it would require significant testing and we'd want to make sure you were available if any issues arise.

**Comment by dcs619** [comment]
@edmistj The v7 block already has a section for `Advanced Options` and I was planning to add it under that:

![screenshot 2017-11-07 11 33 56](https://user-images.githubusercontent.com/1210933/32505309-dee1694c-c3af-11e7-967e-7439234ea6cc.png)

When a filter is selected as well as after Update/Postback, the Account List filters according to the selected Account Type.  

![video-to-gif](https://user-images.githubusercontent.com/1210933/32505660-c024f310-c3b0-11e7-8142-d14463847fc5.gif)


If an Account isn't selected after selecting an Account Type, you're correct, all accounts are considered valid for the SP.  I wouldn't consider that a bug as that's consistent with currently clicking `Update` with no accounts selected. 

I agree on _not_ changing the SP's, so an alternative would be to preselect all filtered accounts when the Account Type filter changes.  However, that feels inconsistent as none of the other filters cause automatic preselections.

**Comment by edmistj** [comment]
>If an Account isn't selected after selecting an Account Type, you're correct, all accounts are considered valid for the SP. I wouldn't consider that a bug as that's consistent with currently clicking Update with no accounts selected.

The logic would then be "All Accounts" but by selecting a value for "Account Type" it would seem that the user would expect it to be "All Accounts" of the selected "Account Type" which would not be the case. So this would seem to be a bug to me.

>I agree on not changing the SP's, so an alternative would be to preselect all filtered accounts when the Account Type filter changes. However, that feels inconsistent as none of the other filters cause automatic preselections.

That would solve the issue, but would seem to be different than the rest.

<hr>

Overall I'm not seeing a clean way to add this feature without significant changes to the stored procedures. Which we all agree is not something we want to do.

**Comment by dcs619** [comment]
>The logic would then be "All Accounts" but by selecting a value for "Account Type" it would seem that the user would expect it to be "All Accounts" of the selected "Account Type" which would not be the case. So this would seem to be a bug to me.

@edmistj here's some feedback to your point, how do you feel about those expectations?

>The intent was to only filter on any funds in that category. We would still require the user to click and select the funds they want to be a part of the analysis.  It seems the concern is that someone would use the category filter and then NOT actually click the individual funds. That is not expected behavior.

**Comment by edmistj** [comment]
@dcs619 We discussed it again as a team and all feel that if someone selected an 'Account Type' but did not select and account they would expect it to filter for all accounts of the selected type (all the accounts listed on the screen). This is the behavior today. To change that would seem to us to be adding a perceived bug.

**Comment by dcs619** [comment]
Closing, won't fix
