### ISSUE TITLE
Feature Request - Batch Id in Transaction Entity Matching Block

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#2581]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
My finance team would like to have the Batch Id display in the Transaction Entity Matching Batch drop down list so that they would be able to more quickly select the batch that they are matching transactions for 

### Steps to Reproduce
1. Open Fundraising Matching Block
1. Select batch from batch list

**Expected behavior:**

Would like to see the Batch Id and Batch Name on each list item i.e. `123456 - Missions Contributions`

**Actual behavior:**

Only Batch Name is displayed

![fundrasing1](https://user-images.githubusercontent.com/2363131/32500873-38f041e2-c39c-11e7-920d-efd5ecd34f29.PNG)

### Versions
* **Rock Version:** 6.9
* **Client Culture Setting:** en-us

**Comment by cabal95** [comment]
Implementation note, should probably be implemented to match style from this related change: https://github.com/SparkDevNetwork/Rock/pull/2260

**Comment by edmistj** [comment]
@chrisfunk  We're good with this change, should we expect a pull-request?

**Comment by chrisfunk** [comment]
@edmistj I completely forgot about submitting this back in. Would you still want this feature?

**Comment by edmistj** [comment]
@chrisfunk sure

**Comment by arranf** [comment]
@chrisfunk Still up for doing the PR?

**Comment by treyhendon** [comment]
I just hot fixed this on Trader's Point using the style @cabal95 recommended.  Am I okay to submit a PR on their behalf?

**Comment by jonedmiston** [comment]
@treyhendon can you provide a screenshot here?

**Comment by treyhendon** [comment]
Sure thing!

![image](https://user-images.githubusercontent.com/3513589/58601691-fb379400-8257-11e9-85d4-61337a5d95f3.png)

**Comment by jonedmiston** [comment]
@treyhendon  can you provide a screenshot of the entire block?

**Comment by treyhendon** [comment]
![image](https://user-images.githubusercontent.com/3513589/58636163-aaf31d00-82bd-11e9-87f8-41fb2bec056a.png)
