### ISSUE TITLE
[EN] Member portal multi-site support

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2582]
### Description
As part of requirements for several new multi-site churches, the public facing member portal in Rock does not provide campus selections.  This creates difficulty as churches transition away from paper signup sheets (or requires them to continue to use them).  As Campus in Rock is set on the Family, I'd like to create a PR that adds a `Family Campus` field on the PublicProfileEdit and AccountEdit blocks.

This functionality does not yet exist in either v6 or v7 versions.  This could possibly be combined with the work on #2573.

![screenshot 2017-11-07 11 47 12](https://user-images.githubusercontent.com/1210933/32506442-98e2ad9a-c3b2-11e7-8262-0abf0d87758a.png)

![screenshot 2017-11-07 11 47 32](https://user-images.githubusercontent.com/1210933/32506443-98f21460-c3b2-11e7-9fe1-c8c6cf134158.png)

### Steps to Reproduce
1. Add/edit your public-facing account for a multi-site church 
1. Expect a campus selection, but find out it's missing
1. Come up with hacky workflow forms or texts to ask people what their Family Campus is

**Comment by cabal95** [comment]
I'm not sure how to handle it, just throwing out the item to make sure it gets discussed: How to handle multi-family situation.  i.e. person record is in more than one family. Couple extra complications (in terms of UI), those families might have the same last name (divorced/separated), so there might be no clear way to inform the user which family they are changing the Campus for.

**Comment by JimMichael** [comment]
Does v7's "primary family" ability help here?

**Comment by dcs619** [comment]
@cabal95 I would assume those questions have already been discussed for the `Home Address` field that's part of the MyAccount section, but maybe that's a bad assumption.  I'm following the pattern established there to pull the family group and set the group Campus.

**Comment by cabal95** [comment]
@dcs619 heh, good point. Hadn't considered that address is also tied to family.  I guess maybe take a look at MyAccount and see what logic it applies.

In general, it probably isn't a huge issue as most of the time the person logged into this page will be an adult, and adults probably would not often be a member of more than one family. Just wanted to bring it up, but you are right the same applies to the address.

**Comment by dcs619** [comment]
@cabal95 I was in the middle of editing to add the : [relevant code section](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Security/AccountEdit.ascx.cs#L341) of AccountEdit that pulls the family Home Address.   

S P O I L E R
P
O
I
L
E
R

It's `FirstOrDefault`.

**Comment by edmistj** [comment]
@dcs619 Sounds good. If they were in multiple families we should list each using the family name (aka group name) and then a dropdown for the campus.

**Comment by nairdo** [comment]
I don't recall off-hand when this got implemented but as least as of v9, you can now enable editing the campus selection in the Person Profile Edit block settings.

![image](https://user-images.githubusercontent.com/383807/61502879-7e3cb700-a98a-11e9-84d7-a7c9c840a26a.png)
