### ISSUE TITLE
[EN] Modify Image Uploader to encode/remove filename spaces for Gmail compatibility

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2586]
### Prerequisites

✅  Can you reproduce the problem on a fresh install or the [demo site]
✅  Did you include your Rock version number and [client culture] setting?
✅  Did you [perform a cursory search] to see if your bug or enhancement is already reported?

### Description

Thanks to Gmail's restrictions on image formatting, any new Communication with an inline image won't properly display even when images are allowed from that sender.  The "alt text" is inserted where the image should be, but you have no recourse to display the image.

Confirmed on v6.9 that removing spaces from an uploaded file's name will properly load the image when sending to Gmail recipients.  Gmail support and [others] (https://www.campaignmonitor.com/blog/email-marketing/2014/02/image-cache-display-issues-in-gmail/#comment-2233236787) recommend removing or encoding the space:

![image](https://user-images.githubusercontent.com/1210933/32566663-9f3ecf5a-c486-11e7-8bf8-c919a9a84bfe.png)

### Steps to Reproduce

1. Start a new Communication
2. Insert a photo with space in the filename (`/Content/person photo.jpg`) using Image Uploader
3. View Code, verify the path is correct and opens in an incognito window without login
4. Send to a Gmail address and any other email
5. Smash a dozen doughnuts on your desk when Gmail silently fails

**Expected behavior:** 

![screenshot 2017-11-08 11 31 00](https://user-images.githubusercontent.com/1210933/32566726-d0df9364-c486-11e7-930f-1f3d50cc3bec.png)

**Actual behavior:** 

![image](https://user-images.githubusercontent.com/1210933/32566751-e998fbfc-c486-11e7-9236-c231f60686e1.png)
person photo.jpg

**Comment by edmistj** [comment]
Thanks for the heads up. We did get this fixed for v7 via: https://github.com/SparkDevNetwork/Rock/commit/253dad16

**Comment by dcs619** [comment]
@MikeDPeterson+++++++++++++
