### ISSUE TITLE
'Email Send' Workflow Action not triggering Mailgun feedback

### ISSUE THREAD

**Issue by DerekMangrum** [SparkDevNetwork/Rock#2598]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
Nick and I have looked in to this and have come up with the following...

When an email is sent through the Communication tool, header information is added that allows Mailgun to feed data back in to Rock (opened, clicked, etc.). In the Mailgun logs, you will see an entry on the communication (sent via the communication tool) similar to the following:
`    "user-variables": {
        "communication_recipient_guid": "dd719bc0-980d-4067-ba9c-c0dc7217bba5"
    },
`
But, when you look at an email sent via the "Email Send" workflow Action, this line looks like:
`"user-variables": {},`

I believe this lack of a 'user-variable' is essentially disabling the Mailgun feedback loop. Rock shows the communication as 'delivered', but there is no other data available (opened, clicked, etc.).

The 'Email Send' Workflow Action allows you to 'Save Communication History'. It would be great if it also allowed Mailgun to feed its valuable data back in to Rock, like actual Communications do.

### Steps to Reproduce

1. Send an email to a parson via a workflow 'Email Send' Action (with Save Communication History set).
2. Have that person open the email.
3. Verify that Communication History only shows 'Delivered', and not 'Opened'.
4. In your Mailgun Console, find the email under Logs and check the "user-variables" property.

**Expected behavior:** 

The Communication History to reflect Opens/Clicks/etc.

**Actual behavior:** 

:(

### Versions

* **Rock Version:** Rock McKinley 7.0 (1.7.0.39)
* **Client Culture Setting:** ??? Umm...

**Comment by cabal95** [comment]
In the workflow action, are you sending to a Person variable or just an e-mail address?

**Comment by DerekMangrum** [comment]
It's being sent to an Attribute of type Person.

**Comment by DerekMangrum** [comment]
Nick and looked at the code, and it looks like the 'Email Send' Action sends its emails a bit differently... without adding the Mailgun mojo...  (Nick will correct me if I am not stating that right)

**Comment by cabal95** [comment]
This looks like it is caused by the fact that the Email Send action sends to an e-mail address (even if you specify a Person attribute) rather than creating a Communication and sending that way. After the e-mail is sent, a background transaction is run to create the CommunicationRecipient record (as far as I can tell), which is the GUId that is needed.

Possible solution would be to make the actual "smtp client" send portion happen after the communication recipient is created so we can stuff the GUID in.

**Comment by azturner** [comment]
The sending to an email address has been updated to create a guid first to use in the header, and then use that guid when creating the recipient. This will only work if the email address is unique to just one person. If multiple people share the same email address, even though only one email is sent, multiple recipient records still get created for each person, so the tracking guid can't be added.
