### ISSUE TITLE
Summernote drag and drop image upload fails

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2600]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When uploading an image using SummerNote, the image is encoded in base64 in v6 and will cause an email to send with "Error! Filename not specified." where the image was placed. In V7 Summernote still invites the image via drag and drop, but never inserts the image.

![imageuploadfailure](https://user-images.githubusercontent.com/374209/32913991-e30df560-cac8-11e7-9748-7651861a37be.gif)

### Steps to Reproduce
1. Drag an image onto a Summernote field
1. Save/Send

**Expected behavior:**

Image to be saved to Rock uploads folder and work for sending/saving.

**Actual behavior:**

Causes problems with email sending, causes unpredictable problems in other areas.

### Versions
* **Rock Version:** 6.9 - Prealpha
* **Client Culture Setting:** en-US

**Comment by brownbg** [comment]
![StarsDanceCo-Logo](https://user-images.githubusercontent.com/40185895/68533557-839f8200-032a-11ea-9aa6-6d4af24f498f.png)
