### ISSUE TITLE
Break RegistrationEntry block into components

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2601]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The current RegistrationEntry block is over 5,000 lines long. This can make it rather daunting to try and trouble shoot problems or look to make small tweaks. I would like to break this out into smaller pieces. This would **not** turn it into a multi-page process, the end-user experience would be unchanged. Instead the plan would be to compartmentalize certain pieces into their own Rock.Web.UI.Control.Event.xyz classes that are mostly self-contained.

Suggested controls and what they take care of:

1. HowManyRegistrants - asks user how many registrants and does proper checking and display of "over capacity" messages.
2. Registrant - Handles displaying forms and controls for getting registration information, including (but not limited to), fields, optional fees, document signing, "in same family", etc.
3. Summary - Displays summary information to the user about their registration, also asks the "who completed by" information.
4. Payment - Processes any payment related aspects, such as asking how much they are going to do for down payment, offer to pay everything, discount codes(?), etc. as well as running the actual payment.

I believe this would allow for more easily making future modifications; such as Kiosk event registration and workflow based event registration.

I would be doing most(all?) of the work and have already started to get far enough to know if this is even possible and it appears to be. I have controls 1 and 2 working (not done, long way to go in code cleanup to be done, but they work). This part alone has already reduced the RegistrationEntry block by 1,500 lines of code.

**Comment by edmistj** [comment]
I'll add this to the core dev meeting review. You might want to hold off putting more time into this until we've had a chance to discuss this.

**Comment by edmistj** [comment]
We talked about this today. We're not sure now is the time to tackle this. We understand you'd be doing most of the development, but it would take on quite a bit of testing and code review (this block is critical for most organizations). It would be better to tackle this the next time major work is required. Would kill several birds...
