### ISSUE TITLE
Inherited Group Type member attributes do not appear in group filter or group grid.

### ISSUE THREAD

**Issue by tstephens17** [SparkDevNetwork/Rock#2602]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Group type member attributes that are set to "Show in grid", do not show in grid for groups types that inherited that member attribute. But the attribute is seen when you click on a member to edit. It does not show in grid or filter.

### Steps to Reproduce

1. Create a group type with member attributes that show in grid.
2. Create a group type that inherits the group type from step#1
3. Create a group with the group type from step#2.
4. Add a member.
6. Notice that the inherited attribute isn't shown in the grid or filter but can be edited when editing a member.

**Expected behavior:** 

I expected inherited member attributes to both be in the filter and grid

**Actual behavior:** 

Inherited member attributes are not shown in grid or filter.

### Versions

* **Rock Version:** [6.9]  
* **Client Culture Setting:** [en-US]

**Comment by cabal95** [comment]
Confirmed against pre-alpha as well.
