### ISSUE TITLE
Attendance Analytics block group picker does not show all groups correctly.

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#2606]
### Description

When testing the 6.10 beta in our enviornment - and switching to the group picker in attendance analytics - it does not seem to show all our groups correctly.

### Steps to Reproduce

1. Select Group Type
2. Group listing is blank

**Expected behavior:** 
Groups would be shown.

**Actual behavior:** 

Groups not shown.

Here is a video showing that it does not show the Groups for our ABF group type.
https://www.screencast.com/t/8JXuine2sfh

**Comment by edmistj** [comment]
Great question, and thanks for the screen capture. I believe this is because the group type selected does not have a group at the root level of the tree. The group picker then can not navigate to the child groups.
