### ISSUE TITLE
Google reCAPTCHA support

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2607]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

I was looking at using Google's reCAPTCHA API for a side project. Upon looking at it, it seems like it is about as simple as can be and would be extremely simple to include in core with a small web control that includes the JS file, renders the "captcha" and validates the captcha when requested by the containing Block. The validation is a simple API request.

Possible use cases would be optional settings for User Entry Forms, Prayer Requests, Email Forms, possibly others. If the captcha is enabled, it would likely only make sense to _actually_ show it if there is not a logged in user.

While spam is not a major issue yet for most of us, I'd rather stay ahead of the curve and have something ready to implement in various blocks as the need arises.

Since this is something I have a use-case for, I'm happy to develop the pull request. Knowing it would probably not be widely available until v8 I would likely duplicate the code into my own project until it reaches core and then switch the functionality over to core code.

#### General Implementation Goals

1. API Key configuration (Either two global attributes or dedicated block)
2. Rock.Web.UI.Controls.ReCaptcha control provide the validation services.

> Note: Google reCaptcha is free, but requires you to activate it and provide two API keys to the implementation. It is similar in concept to Google Maps usage, but in my opinion easier to setup. Documentation would need to be written for how to set it up, which might make the dedicated block for configuration a better choice as it can (probably) verify that the API keys are valid and also have a link to the documentation for how to configure in Google. I can write a general overview of the configuration and include it if Amy or somebody else can do final formatting and screenshots.

### Versions

* **Rock Version:** git
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Sounds great. Creating the key seems pretty easy. I'm torn on the new configuration page. It would make it easier, but would add a new page to the settings that are already getting a bit long. We have plans to start grouping the child pages on each page so maybe that solves that.

**Comment by cabal95** [comment]
For the moment I'll pursue two Global Attributes. Going from that to a dedicated config block would be easy enough if we make that decision.

Maybe a single block for all Google things, or more generally various API keys?  Google Maps API, Captcha API, Sign Now Access Token, Store Organization Key.  We have a few of those floating around.

**Comment by JayGreentree** [comment]
I'd love this feature especially with registration and contact forms.

**Comment by cabal95** [comment]
@JayGreentree @mikejed (and anybody else), if there are any specific blocks you think make sense to have this as a feature please leave a comment. I'm not sure how many I'll do on the first PR, but it will be good to have a list.
