### ISSUE TITLE
[EN] Data Selects "Last Contribution" and "First Contribution" Need "Combine Giving" option

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2608]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
The Giving Amount Person Data Select allows you to choose whether or not you want to combine giving, and I think Last Contribution and First Contribution deserve similar treatment.

This came up because someone was doing a Data View on their own and found it wasn't matching what giving analytics said.

Alternatively, there is access to "First Gave" and "Last Gave" in Family Analytics, but those aren't as live as "First Contribution" and "Last Contribution"

### Versions
* **Rock Version:** 6.5 Production, 7.0ish prealpha.rockrms.com
* **Client Culture Setting:** en-us

**Comment by nairdo** [comment]
Hello amazing community member! We've recently moved 'feature requests' to our own "Ideas" system on our Community site at: http://community.rockrms.com/ideas

If you'd like to re-propose your idea and put it up to the vote, please re-submit your idea there. Thanks!
