### ISSUE TITLE
Group linkage not working for event registrations

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#2609]
### Description

When linking a group to an event registration - people are not put in the group when they register for the event.

### Steps to Reproduce

1. Link group to event registration
2. Register on website for event
3. Look at group / event registration - individual is not placed.

**Expected behavior:** 

Individual placed in group or option to place individual in group should exist.

**Actual behavior:** 

Do not see option to place individual in the group.

### Versions

* **Rock Version:** 6.10

**Comment by austinspooner** [comment]
Actually - this is working. We used the incorrect url

**Comment by MikeDPeterson** [comment]
This was just an issue in the custom lava that was written. It isn't a core issue.  The custom lava is fixed up now.
