### ISSUE TITLE
v7alpha Bio Block custom content weirdness

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2610]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
When playing around with the Custom Content feature in v7alpha Bio Block, I noticed the content moves depending on which person is displayed. See images.

### Steps to Reproduce

1. Add some custom content to the Bio Block
2. Start looking at random people and notice the content sometimes appears below the person's bio info, and on others it appears to the right, below their phone numbers. I have not been able to see a difference/pattern with the people that determines why it appears one way for some and another way for others.

**Expected behavior:** 

Custom Content would appear in same place for all people

**Actual behavior:** 

It jumpeth aroundeth.

### Versions

* **Rock Version:**0 1.7.0.50
![image](https://user-images.githubusercontent.com/3903408/33446564-140f8d42-d5c6-11e7-8194-c43c7f14a18b.png)
![image](https://user-images.githubusercontent.com/3903408/33446603-30a58fc4-d5c6-11e7-9e5e-a2ac62edba75.png)

**Comment by garrettjohnson** [comment]
@JimMichael Looks like the custom content is moving around because of the height of the other content in the block. If you add a `<div class="clearfix"></div>` at the beginning of the custom content, the rest of the code in the block will respond as you would expect.

**Comment by JimMichael** [comment]
Cool! But is that something that should be fixed in the block itself, or should the end user be expected to know that and how to work around it?

**Comment by garrettjohnson** [comment]
Adding a `clearfix` to the `.summary` div would fix it too... I think that's the best route; I'll submit a PR

**Comment by edmistj** [comment]
Thanks Garrett!

**Comment by edmistj** [comment]
Closing as this will be in v7 Beta
