### ISSUE TITLE
UI does not identify MetricId number to the user

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#2611]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When clicking on what we think of as a Metric, we're actually clicking on what Rock considers a Metric Category, which is why the URL uses `?MetricCategoryId=`. But with Entity Commands being so accessible and a common item to want to display in a custom format (using an HTML block), it would be extremely useful to identify the actual MetricId to the user. This would be similar to how DataViews display their ID in the top right of their block:
![image](https://user-images.githubusercontent.com/6932047/33581368-d7b91034-d90d-11e7-9416-26b6e43e9c87.png)

### Versions

* **Rock Version:** 1.6.10, 1.7.0 Alpha
* **Client Culture Setting:** EN-US

**Comment by NuclearTacos** [comment]
@mikejed Thanks for posting this!  This is one of those things that I mentioned and totally forgot to post 🙃 I 100% agree with this request
