### ISSUE TITLE
Enable RouteExistingFiles in Route Service

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2613]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The PageRouteService has a property called RouteExistingFiles. Enabling this allows for routes to match the names of existing files / directories. Suggesting this be enabled at the end of the `RegisterRoutes` method in Global.asax.cs. I have run in this configuration for 2 months without any issues.

### Reason for change

Currently, the Route system will not honor a route that matches an existing file or directory. For example, if you want to have a route of `Plugins`, `Content`, or `Blocks` you cannot because it will match the existing directories and give an error because directory listing is disabled.

With the RouteExistingFiles set to true, then it will match any registered routes first and then, if none is found, attempt to serve up static files.

### Possible Implications

Somebody could override the content of an existing .JS or .CSS file (or an image) by registering a route for that file. I'm not sure this is a major issue.

This does **not** allow them to override a server-side file, such as replacing the content of a `.ascx.cs` file or anything, this is only for files that the browser explicitly requests.

### Versions

* **Rock Version:** 6.8, git
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@cabal95 sounds reasonable, but will bring this up at our next dev meeting to ensure a wider consensus.

**Comment by edmistj** [comment]
@cabal95 There's some concern that this could break installs. What is the use case you are trying to achieve.

**Comment by cabal95** [comment]
In my specific use case at the moment, I have Rock powering my website listing the plugins available for Rock. Since I am listing "plugins" I named the route "plugins" so people see in the URL `http://.../plugins`. The same issue would happen if somebody wanted to create a route called `Content` or `bin` or any other directory name.

I'm happy to research further if there are specific "breakage" examples, but I can't think of any way this could break an existing install. Currently if you go to `http://www.rocksolidchurchdemo.com/plugins/` you get a 403 error because IIS does not allow browsing directories by default. Turning this setting on would still render the same result because there is no `plugins` route on the demo site. Functionality would remain the same until somebody created a `plugins` route at which point the route would take priority.

So the only two scenarios I can think of that would break something on existing installs is:
1. If somebody enabled directory browsing in IIS **and** previously created a `plugins` route (which wouldn't function) **and** wanted the end-user to still be able to browse the /plugins directory.
2. If somebody previously created a route of `Themes/Stark/Styles/Bootstrap.css` then it would start serving up that Rock page instead of the CSS file.

Again, I am happy to do more research to test/verify specific examples, I just can't think of any others. :) I'm also happy to have this go into v8 only so that it gets the full-blown pre-alpha, alpha and beta testing procedures rather than patch-only procedures. Since it's a single line of code it's easy enough for me to patch my server after updates - I just have to remember to do it.

**Comment by edmistj** [comment]
At this point I don't think this is worth the time for us to continue research and dialogue on. If there is a use case in the future that makes it worth discussing again we're open to this. In the meantime I'm going to close the issue.

**Comment by cabal95** [comment]
Okay, I'll start working on some redirect rules on my existing routes so I can switch them to a different URL. Manually re-applying this patch each release long term will not work for me.

Should I open a new issue then for a bugfix/enhancement to the route "editor" to provide a blacklist of known routes that will not work? Without this change there are a number of route names that can be entered but will not be honored, and I don't think the average user will understand why "this one route just isn't working".
