### ISSUE TITLE
Worflow Attribute - Field Type Dataview

### ISSUE THREAD

**Issue by winmastr** [SparkDevNetwork/Rock#2614]
Using The Create a workflow Attribute form in version 6.10 and selecting the FIELD TYPE of Dataview, it does not provide the needed  Entity Type Dropdown box, only a non functioning Default Value box so the Dataview functionality is not available

### Versions 6.10

* **Rock Version:** [Ent6.10
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by cabal95** [comment]
@winmastr A work around for now would be to create a Single Select attribute and use this SQL as the source (you can replace `Person` with `Group` if that is the type of DataViews you are looking for):

```
SELECT DV.Id AS [Value],DV.[Name] AS [Text] FROM DataView AS DV INNER JOIN EntityType AS ET ON ET.Id = DV.EntityTypeId WHERE ET.FriendlyName = 'Person' ORDER BY DV.[Name]
```

**Comment by edmistj** [comment]
Closing as this is resolved in v7.
