### ISSUE TITLE
Prevent duplicate phone numbers for a person

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2616]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Users will often enter the same phone number repeatedly because the field is available. Resulting in something like this:

<img width="512" alt="screen shot 2017-12-06 at 6 03 23 pm" src="https://user-images.githubusercontent.com/374209/33694989-d40a8ff0-daaf-11e7-8ca1-072810087e97.png">

Instead of allowing duplicates, it would be amazing if Rock automatically and silently de-duplicated on save. Which would result in a single record prioritized in the display order. (By default Mobile/Home/Work) So, if `(555) 555-5555` is entered on both the mobile and work number, Rock would remove the work number automatically.

By having Rock automatically clear duplicates it should prevent data integrity errors when staff receives a phone number change (and only updates one number, leaving two incorrect numbers) and generally result in cleaner data in Rock.

### Versions

* **Rock Version:** Prealpha
* **Client Culture Setting:** en-US

**Comment by dcs619** [comment]
Related to #2405, some sort of key constraint is likely needed on the PhoneNumber table.

**Comment by edmistj** [comment]
@garrettjohnson makes sense. I think we'd add logic to the PreSave on the PhoneNumber model to remove duplicate numbers. Since the phone number types are orderable by the administrator we could use the order as the priority.
