### ISSUE TITLE
Adding a session for page views when a person is not logged in.

### ISSUE THREAD

**Issue by rutledgek** [SparkDevNetwork/Rock#2621]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
Upon exploring the PageView table to put together some basic analytics for a Facebook Ad Campaign, I noticed that a new Page View Session Id is generated for each page view a person makes when they are not logged in.   This makes it impossible to see what other pages a person is visiting during a single site visit when they are not logged in.

**Expected behavior:**

I expected a session to be created for users, even when not logged in, to group their page views together under one Page View Session Id.

**Actual behavior:**

A New Session Id is created with each page view.

### Versions
* **Rock Version:** 1.6.10
* **Client Culture Setting:** To be honest, I don't know what this is.

**Comment by mkinyon** [comment]
@edmistj @nairdo I believe this feature was added sometime after Rock moved to the Interactions system.  I did a test by browsing the external site in incognito mode with one browser and then did the same test again in another browser.  In the pic below you can see that Rock is grouping these sessions together.

Note: This was tested on the pre-alpha site.
![image](https://user-images.githubusercontent.com/2349102/45502511-0a61ca80-b739-11e8-909f-949c8e94d389.png)

**Comment by ethan-sparkdevnetwork** [comment]
![ssms_2018-09-14_14-31-02](https://user-images.githubusercontent.com/35315117/45576255-51c88380-b82b-11e8-9307-036bcf4b0cd7.png)

I am not able to reproduce the problem. I get a consistent session ID for each browser. This could be an IIS issue or the browser rejecting cookies.

**Comment by ethan-sparkdevnetwork** [comment]
Verified on 7.4, 8.4, and 9.0; sessions are grouped for users regardless of login status.
