### ISSUE TITLE
Check-in auto-configuration does not match IP/hostname as expected

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2625]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

There are two issues, both happen if the block is configured to do reverse DNS lookup **and** the server successfully resolves the IP address into a hostname.

1. The Device will only be searched for by UI Name == hostname.
2. The Device will no longer be searched by IP address if hostname search fails.

### Steps to Reproduce

n/a

**Expected behavior:** 

1. We would expect to keep the UI name a user-friendly name and put the Hostname in the IP Address field.
2. We would expect it to fallback to searching the database for the device IP address if one that matches the hostname could not be found.

**Actual behavior:** 

Our device is not found and auto-configuration for check-in does not happen.

### Suggested fix

1. When searching by hostname, search the Device.Name and Device.IPAddress for matching hostname.
2. If no match is found, fallback to search by IP address.

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Took me a while to figure out which block you were discussing. Matching by the 'Name' property seems confusing to me. Should we not rename the 'IP Address' field (at least in the UI) to be 'IP Address / Hostname'. We could then even change the lookup logic to auto detect the type (IP is only numbers and dots). The would simplify the configuration also.

If the feature was mentioned to me I'd not expect the Device.Name to be the field that would be used in the reverse name lookup.

Thoughts?

**Comment by cabal95** [comment]
Sorry should have been more clear, was trying to get this issue written up quickly before a meeting. The current functionality is to check for DNS name against the Device.Name field, so I think for backwards compatibility we should check (DNS Name == Device.Name || DNS Name == Device.IPAddress || ClientIPAddress == Device.IPAddress).

If we just switch to checking Device.IPAddress only then existing systems using this functionality would stop working.

I do like the idea of changing the UI to say `IP Address / Hostname` to clarify that field.

**Comment by edmistj** [comment]
Are you the only church using this? If so would it be OK to change it? If not (others are using it) I guess I'm OK to keep it, but we'd want the order to be:

1. ClientIPAddress == Device.IPAddress (if it matches an IP pattern)
2. DNS Name == Device.IPAddress
3. DNS Name == Device.Name

Using the Device.Name doesn't seem to make sense but if several people are using it that way then I would not want to break it.

**Comment by cabal95** [comment]
We are not actually using it yet. We would like to use it so we don't have complex URLs to deal with anymore. I'm not sure if others are using it or not. Dunno how to find out other than just ask in Slack and hope those using it see the inquiry.

**Comment by edmistj** [comment]
We haven't publicly talked about it and I doubt anyone has found the setting. Also if they did I doubt they would have understood it to mean the Device.Name. I think it's safe to change.

**Comment by arranf** [comment]
@edmistj Is it worth us trying to do some sort of anonymous analytics on block usage? I can see this being useful going forward. It'd be relatively easy to do this in the SparkLink.

**Comment by FrankGrand** [comment]
@edmistj I'd want to look and see if this is what we were using in our attended check in.  @dcs619 Can you confirm?

**Comment by dcs619** [comment]
Attended Check-in uses the underlying method `DeviceService.GetByIPAddress`, so yes, that would need to be tested if the functionality changes.  Also, your check-in Chromebooks don't return a DNS name (only Windows and Macs) so it depends on IP matching.

Are there any security concerns with changing this since a spoofed name (easy) or spoofed IP (harder) would now match?

**Comment by cabal95** [comment]
If you are currently matching by IP then there would be no difference.  And there are no security concerns since you can accomplish the exact same thing by passing `?KioskId=123` in the URL.

**Comment by nairdo** [comment]
Yes, we use the device Name field to store the fully qualified devices and ran into this issue.  So, I'll add item 3 (from Jon's ordered list) back in to fix it.

**Comment by cabal95** [comment]
Thanks Nick, sorry for the trouble!
