### ISSUE TITLE
Exclude self from following notices

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2628]
### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

When a user follows a group with themselves in it they'll receive notices about themselves. It would make sense to exclude sending notices about yourself. 

### Steps to Reproduce ###

1. Follow yourself or a group where you are a member
1. Receive following notices about yourself

**Expected behavior:**

Rock excludes your own record from following notices.

**Actual behavior:**

You're sent following notices for yourself

### Versions ###

* **Rock Version:** 6.10
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
While reviewing this, we do not categorize it as a bug, as the individual intentionally configured their account to follow themselves.
