### ISSUE TITLE
Issue with dataviews /reports

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#2629]
### Description

In Rock 6.10 and higher (confirmed on v7 alpha) - there is an issue with the dynamic report block working correctly when its tied to multiple dataviews. 

### Steps to Reproduce

1. Create a dataview of adult members and attendees (http://prealpha.rockrms.com/page/145?DataViewId=1&ExpandedIds=C131)

2. Create a dataview of children of adult members and attenders (http://prealpha.rockrms.com/page/145?DataViewId=13)

3. Crate a dataview that filters on Kids birthdays and attendance data (http://prealpha.rockrms.com/page/145?DataViewId=14)

4. Create a report linked to this dynamic data view

5. Create a new page with a dynamic report block on it - choose the report you created above with birthdays of kids.http://prealpha.rockrms.com/page/6436

6. Run with these filters - and see no results returned.
![image](https://user-images.githubusercontent.com/657005/34054249-a5314aca-e18f-11e7-9012-7988b2c36476.png)

**Expected behavior:** 

Same results as in dataview would be returned.

**Actual behavior:** 

No results returned.

**Comment by MikeDPeterson** [comment]
The issue seems to be that if any of the DataViews have Transforms, the transforms are processed. So, we'll figure out something to fix that

**Comment by austinspooner** [comment]
@MikeDPeterson  - thanks. It was working find prior to 6.10

**Comment by austinspooner** [comment]
Mike, any update on this issue?

**Comment by MikeDPeterson** [comment]
@austinspooner Sorry. Yep, this is fixed with https://github.com/SparkDevNetwork/Rock/commit/1f0a94fc7e55ae536bc426ad279a7d406f2de806 and https://github.com/SparkDevNetwork/Rock/commit/4901a4db56373da1d33bfd19a7be9569a48c779a

So it's fixed in v6.11 and v7.1
