### ISSUE TITLE
Packaging Documentation shows wrong Icon Template

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2632]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The developer documentation at https://www.rockrms.com/Rock/Developer/BookContent/26/26#packageiconspecifications shows the wrong template for package icons. Specifically it says that the red area (center third) of the image will be used as an icon for lists of packages. The Rock Shop instead simply centers the image to fit in the space, which could be square, or could be 16x9, or could be wider depending on the device.

Blocks should be updated to show a specific hard-coded section of the image instead letting it change depending on browser window size as this often cuts off important parts of the images, such as the package name.

Documentation may need to be updated as well if the shaded red section is not what is going to be used when displaying packages.

### Versions

* **Rock Version:** n/a
* **Client Culture Setting:** n/a

**Comment by edmistj** [comment]
@cabal95 To keep a nice responsive design that red area is more of a target (keep this space available to be used as the icon) that a precise section (this is the icon). To make it exact would lead to either not making the items responsive or having to make the height of the image responsive. I'll update the docs to clarify this.

**Comment by cabal95** [comment]
Just trying to clarify my understanding, is making the height of the image responsive something you are specifically trying to avoid?

If you are open to it I'm happy to make a patch to the block(s?) and submit a screenshot with the images being responsive to the red shaded area. I already do this on my own site for listing my plugins and haven't seen any issues with the resizing on the various browsers and windows sizes I've tried.

The issue with the code as it is now is that it is virtually impossible to make an image that looks good as an icon because some people will have thin browser windows and some will have wide so we never know what is actually going to show up.

**Comment by edmistj** [comment]
Yes, we'd prefer to not have responsive heights. The current icons look quite nice. It's pretty easy if you add a icon square in the middle with plenty of room on both sides. If you drag the window across two monitors it will show some of the other content, but I don't think that's a huge deal at this point. Future plans are to have a dedicated icon image at some point.
