### ISSUE TITLE
Scanned ID/Barcodes not working as expected

### ISSUE THREAD

**Issue by atorrance** [SparkDevNetwork/Rock#2633]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Barcode or Scanned ID field does not appear to be working correctly in Check-in Configuration and/or the Window's Check-in Application.

### Steps to Reproduce

1. Set Search Type to 'Scanned ID' in Check-In Configuration/Search Settings for any available group.
2. When Scanned ID is selected, the information for phone still remains (min, max and phone search type) and does not give any options for the bar code length,
3. With this option selected and saved, the check-in screen does not ask for bar code but instead a Phone and Name.

**Expected behavior:** 

I expect the options to change based on Scanned ID being selected and it giving me and option in the check in screen to input a bar code. 

**Actual behavior:** 

 The check-in screen does not ask for bar code with the setting changed to Scanned ID but instead a Phone and Name and the selections in the config screen do not change when Scanned ID is selected, 

### Versions

* **Rock Version:** Rock McKinley 6.10
* **Client Culture Setting:** en-US
![untitled](https://user-images.githubusercontent.com/34725020/34233379-0eccf430-e5b3-11e7-9f51-b32f15f39412.png)

**Comment by edmistj** [comment]
I think this might be a misunderstanding of how the scanning works. When enabled you should be able to scan from the welcome screen. You won't see any fields, but the barcode scanner will read the code into a hidden field and then proceed with the family search.
