### ISSUE TITLE
[EN] Schedules Excluding Schedules

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2636]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
There are a few limitations to schedules that could be improved by allowing a schedule to exclude a different schedule.

### Recommended implementation
For simplicity's sake, Schedule A should not be active any calendar date that Schedule B would be active (not worrying about time of day at all).  Also, I think it'd be a helpful limitation to prevent Schedule B (that has a excluded Schedule C) from being used as an exclusion for Schedule A.

Aside from the code adjustments, it would probably only need another column on the Schedule table to accommodate the change (but I don't know the finer parts of Rock).  I also don't think there would be any concerns about it affecting anyone's Lava/SQL

### Value Added Cases
* You could exclude Christmas/Easter Schedules from your other Sunday Schedules so that you don't need to update any Sunday Schedules when you get around to those times of year.
* You would also be able to make new kinds of schedules not currently available
  * (like Group A meets in a location every Wednesday except the 2nd Wednesday of the month.  On that Wednesday, Group B uses the same location.  Groups I have configured inspired this issue.  I just made 2 years of exceptions to Group A's schedule, but that's not a very transparent or flexible solution.)

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
