### ISSUE TITLE
Ability to override attribute name / label on Workflow Entry Form

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2640]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Often I am asked to build User Entry Forms on workflows with long labels, such as "Please describe any other allergies your child may have?". Right now I have to name the attribute with such a long name, which gets tedious and annoying when later working with those attributes via drop downs. It would be nice if the User Entry Form action allowed for overriding the Label used with the attribute.

I think the same can be achieved now by hiding the label and using pre/post HTML, but that is tedious and I seem to recall some issues with the Required flag when doing it that way. It would be nice to name said attribute "Other Allergies" but then override the label on the Entry Form to a more end-user-friendly text.

### Versions
* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@cabal95 I would hold on this. Changes may be coming to entry forms in 2018. Would be worth adding this at the same time.

**Comment by cabal95** [comment]
Sounds good, was very low on my list of things to look into. For now I'll just be using the pre/post methods I think.  If you are already tracking this on your internal todo list feel free to close it.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
