### ISSUE TITLE
Group History

### ISSUE THREAD

**Issue by edmistj** [SparkDevNetwork/Rock#2641]
The group history feature will keep snapshots of group and group member data as it changes in the system. This will allow you to see the make-up of a group at any point in time (even after it is deleted). It will also allow you to see what groups a person has been a part of even after they are removed from the group or the group is deleted.

# Implementation Details

Group history would be enabled on a Group Type level. Some group types would not need/want history. This could be the case for groups representing events like a starting point class. You may (or may not) want to see the history of a person in these groups as they are often added but never updated or removed from the group.

_Note: The mock-ups shown are sketches of the features and are not meant to show the final design._

# Group Details
If history is enabled on the group type, an button will be shown to view the group history. This button will be in a disabled state if no history is available (it was just created).

![image](https://user-images.githubusercontent.com/548178/34393784-46ef6726-eb12-11e7-8496-76d674fd853d.png)

![image](https://user-images.githubusercontent.com/548178/34393789-52bf4e04-eb12-11e7-9595-00f314a5c7ce.png)

# Group History Members

![image](https://user-images.githubusercontent.com/548178/34393811-66c065dc-eb12-11e7-9214-eda7cefd2e1f.png)

![image](https://user-images.githubusercontent.com/548178/34393817-7727a746-eb12-11e7-86c8-b1f4deb1a097.png)

# Group History on Person Profile

![image](https://user-images.githubusercontent.com/548178/34393824-8884c7d0-eb12-11e7-872b-e013e9305101.png)

![image](https://user-images.githubusercontent.com/548178/34393831-94aa67cc-eb12-11e7-98e3-4da1f0866524.png)

# Proposed ER
This ER is likely to change based on further fleshing out of the details of the code.

![image](https://user-images.githubusercontent.com/548178/34393842-a94e4c48-eb12-11e7-8761-8de7deeb1b65.png)

**Comment by drychlik76** [comment]
@edmistj This is perfect.  We are seeing request for this very enhancement on the person profile page.

**Comment by edmistj** [comment]
@drychlik76 This should be on pre-alpha to play with next week.

**Comment by arranf** [comment]
Closing this as GroupHistory is on its way in v8.
