### ISSUE TITLE
Add support for SQL User Defined Functions in plugins

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2642]
### Description

Rock's data model supports User Defined Functions defined in SQL to be used in .Where() queries. However, there is currently no way (that I can find) for plugins to register their own user defined functions to be used in their own .Where() queries.

Currently, these are defined by manually calling the internal classes that define these functions during the OnModelCreating. Suggest that we instead use reflection to find all classes that implement `IStoreModelConvention<EdmModel>` and add instantiate them and add them to the data model.

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
I added this to the developer discuss (for our next meeting). What is the intent of the question? Are you looking for a green light to do a PR, or are you requesting that we make the change? Just want to make sure I understand the ask.

**Comment by cabal95** [comment]
It seems like a pretty trivial (in terms of code) addition so I would probably do it myself unless you wanted to do it internally. In my particular use case I still have some other things to iron out even once that is in, but seemed like a potentially useful item for future plugins whether I end up using it for this particular project or not.

Biggest concern would be accidentally adding in some `IStoreModelConvention<EdmModel>` from random DLLs that shouldn't be, so maybe a new Rock interface would be needed to tag them for inclusion. So if you green light the concept I might ping back with a few implementation follow up ideas just to make sure it's well thought out for future uses.

**Comment by edmistj** [comment]
This is good to go, but could you use `IRockStoreModelConvention<EdmModel>`.
