### ISSUE TITLE
Registration with capacity of 0 and Wait List enabled does not place on wait list

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2643]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

On pre-alpha, if you create a registration template with wait list enabled and then set the instance capacity to 0 it should place everybody on the wait list. On the first screen it informs them as such but then doesn't actually put them on the wait list.

Original discussion https://github.com/SparkDevNetwork/Rock/issues/2510#issuecomment-354474525

### Steps to Reproduce

1. Create Registration Template with Wait List enabled.
2. Create Registration Instance with Capacity set to 0.
3. Register a person
4. Person sees initial "wait list" message on the "how many" screen, but never again during the registration.
5. Person is registered instead of put on the wait list.

Confirmed by @edmistj 

**Expected behavior:** 

Person should be placed on wait list.

**Actual behavior:** 

Person is registered fully.

### Versions

* **Rock Version:** pre-alpha v7
* **Client Culture Setting:** en-US

**Comment by arranf** [comment]
It seems like it's impossible to create an event with a maximum capacity of 0 now which should prevent this from occurring.
