### ISSUE TITLE
Redirect Sandwiched between User Entry Forms doesn't Fire

### ISSUE THREAD

**Issue by cbump** [SparkDevNetwork/Rock#2645]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using a User Entry Form followed by a Redirect with another User Entry Form down the line somewhere (allowing for redirecting away and then coming back later to finish) the Redirect will not run.

### Steps to Reproduce

1. Build a workflow like this:
![image](https://user-images.githubusercontent.com/1248118/34501886-edc5db9a-efde-11e7-9326-0675c613a80e.png)

2. Execute the workflow
3. The Redirect action will not fire.

**Expected behavior:** 

I expected the redirect to actually happen.

**Actual behavior:** 

The 2nd user entry form is loaded instead of the redirect being fired.

### Versions

* **Rock Version:** 1.7.0 (Rock McKinley 7.0)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
There was just a few days ago a commit in `develop` that may fix this. There was already a bug with two User Entry Forms in the same activity. Can you verify if merged PR #2597 fixes this?

**Comment by cbump** [comment]
@cabal95 I'm pretty sure this is a separate issue from #2597.
