### ISSUE TITLE
Perform bulk updates in Parallel to improve performance

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2650]
### Description

Currently the bulk update process runs sequentially. In theory it should be able to run multiple updates in parallel by processing chunks of people records at the same time. For example, if we are doing a bulk update on 10,000 people, currently that happens one after another. Person 1, then person 2, then person 3, and so on.

There should be no reason we can't operate in parallel, for example, running two tasks at the same time we would concurrently process:
* Person 1, Person 2, Person 3, ...
* Person 5001, Person 5002, Person 5003, ...

This should improve performance. Because we don't know how many CPUs the server has or what performance ability the server has there would be a new block setting (in Advanced) to set the number of parallel tasks, which would default to 0 to indicate "best safe guess". For example, if 4 CPUs are available then the default might be 4 parallel tasks. The admin can increase or decrease this by setting a value other than 0. For example, a value of 1 would revert to the current behavior. (@edmistj This is a change from what we discussed)

Some testing will need to be done to determine a safe default formula. Because of "waiting on the database" there is likely to be a lot of extra CPU cycles available per task. We don't want to go too low and leave the CPU idle and we don't want to go too high and max out the CPU for a long-running bulk update.

Also, some testing will need to be done to make sure no bulk update tasks could be modifying the same entity at the same time (for example, a group that the person is in). I don't believe any individual update options could do that but we will need to double check just to be sure and if so introduce locks on those type of updates so they don't happen at the same time.

**Expected behavior:** 

Bulk updates should be enjoyable.

**Actual behavior:** 

Bulk updates are like watching paint dry.

### Versions

* **Rock Version:** v7 alpha
* **Client Culture Setting:** en-US

**Comment by arranf** [comment]
@cabal95 Is this something you're still working on?

**Comment by cabal95** [comment]
Not actively, but it is still something I would like to hit at some point. If somebody else wants to take a stab before me I'd be happy to let them. I'll remove myself for the time being until I'm actively working on it.
