### ISSUE TITLE
Schedules FieldType Editing Issue

### ISSUE THREAD

**Issue by tom-powers** [SparkDevNetwork/Rock#2651]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Default Value dropdown on Group Member Attributes don't show user's selection of Schedules with nested Categories (upon reopening Group Member Attribute after full save)

### Steps to Reproduce

1. Add a Member Attribute to any Group:  Field Type should be set to Schedules
2. In the Default Value drop down, select 1 or more schedules that live at least 2 Categories deep
3. Click Select
4. Click Save (to close out the Group Member Attributes window)
5. Click Save (to close out the Group window)
6. Edit the group
7. Click on Member Attributes, and edit the Member Attribute that you just saved
8. Click the down arrow on Default Value, and the previously selected values aren't showing as highlighted

**Expected behavior:** 

When you click the down arrow, the Schedules hierarchial tree should be expanded to the Category level where your previously selected Schedules are showing (and be highlighted).

**Actual behavior:** 

Schedules tree doesn't expand at all and nothing is showing as selected

### Versions

* **Rock Version:** 6.9, 7.0
* **Client Culture Setting:** en-US

-- setting list of Schedules (first time-around)
![screenshot1](https://user-images.githubusercontent.com/2584284/34623921-2c6caee8-f221-11e7-937d-e4e1cf92d64a.PNG)

-- coming back to edit list of Schedules at a later point
![screenshot2](https://user-images.githubusercontent.com/2584284/34623922-2c78467c-f221-11e7-9e7c-c5e4124307e2.PNG)

**Comment by cabal95** [comment]
Could be same issue as #2529 that @MikeDPeterson fixed recently for some other controls.

**Comment by arranf** [comment]
I've tried to reproduce this and I can't. It looks like this has been fixed at some point between this issue and the current development version.
