### ISSUE TITLE
Improve clarify of Pledge Frequency documentation

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2653]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The `Pledge Frequency` can be a little confusing to some users. It does not seem to be explicitly stated anywhere that the frequency is informational only and is not used when calculating the grand total of the pledge.

Additionally, the C# source code comments for `TotalAmount` actually state the exact opposite of the current functionality.

### Suggested Resolution

* Update C# comments to match current functionality.
* Add HelpText to the `Total Amount` and `Payment Schedule` fields on the Pledge Details screen to more clearly state that the frequency (payment schedule) is "your info" only and the `Total Amount` should be the grand total of the pledge.
* Edit: Possibly add a sentence to the finance documentation book stating the same as well.

### Versions

* **Rock Version:** git
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Jim Michael: "I like Intended Frequency as the label. At least it adds a bit of clarification." Capturing this here to keep in one place.
