### ISSUE TITLE
Group Sync breaks on people with no name

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2654]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you setup a group to sync to a DataView and also set it to generate logins, then if the person has no First Name the job will fail to run. This is due to the way the new login is generated as it tries to Substring the FirstName without checking if it's long enough.

![image](https://user-images.githubusercontent.com/1119863/34687574-fccb0a3c-f463-11e7-9347-09b7f51eb6ce.png)

The actual issue is in the login generation method, but I don't know what the proper fix would be. In this case, it would not work well no matter what as the particular people causing this issue have a blank FirstName and a blank LastName so there is really no way to generate a login for them at all.

### Steps to Reproduce

1. Setup a group to sync to a DataView and also set to generate logins.
2. Add a person to the database with no FirstName and make sure they are in the DataView.
3. Run the Sync Group job.

**Expected behavior:** 

Group sync should happen successfully.

**Actual behavior:** 

Group sync aborts and groups stay out of sync.

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
@edmistj Any thoughts on the best way to implement a fix for this? Should we just try {} catch {} around processing each person, or maybe just around the "add login" portion?

**Comment by edmistj** [comment]
I think we should add some checking so that we only create the username/password if they have both a first name and last name.
