### ISSUE TITLE
New Statement Generator ignores DataView option

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2655]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Posting this at @MikeDPeterson 's request to track this issue. It appears that the new Statement Generator ignores the DataView option when used. If you try to filter by a DataView it still returns everybody who gave even if they are not in the DataView.

This is 2nd hand information as I do not have 6.10 to test but have heard two reports thus far. If somebody on 6.10 can verify that would be great.

**Expected behavior:** 

DataView filter should work.

**Actual behavior:** 

DataView filter no workie.

### Versions

* **Rock Version:** 6.10
* **Client Culture Setting:** en-US

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/046fb5a4847b339bb1a6e759a1b7605e5886a21b

**Comment by MikeDPeterson** [comment]
NOTE: for v6, update the Statement Generator using the Rock Shop
