### ISSUE TITLE
SAVE button on BADGE Bar does not operate

### ISSUE THREAD

**Issue by winmastr** [SparkDevNetwork/Rock#2658]
If you go to Block Properties of any BADGE BAR on person detail pages, make an edit, the SAVE button does not operate.  I was not able to accomplish the EDIT from the PAGES area unless i made my edit and then clicked on the Advanced Setting Tab. That save button worked.

* **Rock Version:** [Versions 7 and on the Prealpha version 8]

**Comment by mikejed** [comment]
on prealpha, switching to Advanced tab and **back** to "Basic Settings" tab also caused the save button to start working again. @winmastr had originally noted in Slack that the same was happening from the `CMS Settings -> Pages` when you access the block settings for the badge block also.

As further confirmation, creating an entirely new blank page and adding the badge bar block to that page exhibits the same behavior, so it doesn't appear to be anything else on the profile page causing a conflict.
