### ISSUE TITLE
Database Maintenance Job fails on Azure - v7 beta

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#2662]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The MSForEachtable stored procedure is not part of the Azure master database so the job fails each time.

### Steps to Reproduce

1. Allow database maintenance job to run
2. Job fails with status of Could not find stored procedure 'sp_MSForEachtable'.

**Expected behavior:** 

Job completes

**Actual behavior:** 

Job fails

### Versions

* **Rock Version:** [7.0 (1.7.0.51)]  
* **Client Culture Setting:** [en-US]

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/be23803980fb9fb56c655e6fc5c49843f290c0e8
