### ISSUE TITLE
SMS Wrong Recipient Name Bug

### ISSUE THREAD

**Issue by drychlik76** [SparkDevNetwork/Rock#2663]
Thank you guys so much for taking the time to look at this bug report.  It's a minor thing but it's proving to be a challenge to get around.  I am hoping this can be addressed in the next release.

### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

I am seeing an issue with reply names in the SMS communications history where the person replying is showing up as a different name in Rock.  For example, Cindi is replying to a SMS message, but the reply name is showing up as another member of her family.  Double checking the setup of phone numbers in Rock, I see the mobile cell number being used for the children in a family in this case.  The mobile cell number is configured correctly for the adult (Cindi), with SMS enabled, but for the children, it is being used as a home number.  I see the SMS is enabled for a blank phone number for the child.  Unchecking the SMS enabled on a blank or empty phone number, does nothing.  The SMS stills shows enabled.  If I changed the phone type for the same number from home to cell and uncheck SMS enabled, the unchecked state works as expected however SMS communications still show the Childs name as the sender.  

### Steps to Reproduce

1. Create a Family with 1 adult and 1 child.
2. Enable an SMS number for the adult.
3. Add the same mobile number from the adult to the child record as a home number type.
4. Enable Twillio, (do all of that stuff that it requires)
5. Initiate a communication to the adult from step number 1
--------------------------------
1. Uncheck the SMS enabled for the child.
2. Click save
3. Edit the Phone number records for the child.  You should see the SMS is still showing enabled but with a blank Mobile/Cell number. 

**Expected behavior:** 

I expected for Rock to ignore the phone number for the child if SMS was turned off and not use the name of the Person record as the sender.  The SMS communication appears to not be matching on the Person id but rather on the phone number and ordering on the PersonId.  

**Actual behavior:** 

It appears that the SMS history is using the first person id with a matching phone in Rock; maybe a part of secondary lookup to get the senders name.

This image below is the Parent in the family that has a mobile number that is configured correctly to be used for SMS communications.
![1](https://user-images.githubusercontent.com/20803057/34896360-24521e6c-f7af-11e7-9467-38890d2aaf39.png)

This image below is the child of the parent that uses the same mobile number but configured as a home number.  If you uncheck SMS, click save, you will see that it does not save.  The SMS enabled will still show checked.
![2](https://user-images.githubusercontent.com/20803057/34896363-26a5b7b4-f7af-11e7-91f6-54b645a57d7b.png)

### Versions

* **Rock Version:** 6.10
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Hm. I'm not sure what you are seeing, but can you re-test in 8.1+? The logic for incoming text messages and phone number matching was updated in 8.1  Prior to that, it would _completely ignore_ any phone numbers except the Mobile/Cell.  So even if the Home number was marked as SMS it wouldn't match and reject the message. This was our constant experience and a pain point so we submitted a PR to change that so that it would match against non-Cell numbers (lots of people put their cell in Home field because they don't have a home number).

The logic was updated to accept ANY matching number, BUT prioritize SMS enabled numbers first.  So in your example above, it would match BOTH the parent and child, but it would order them with the parent first since the number matches AND SMS is enabled, so they would be the one tagged for the incoming message.

**Comment by drychlik76** [comment]
Yes sir will do.
