### ISSUE TITLE
Parent Page "Select Current Page" Bug

### ISSUE THREAD

**Issue by matthewmeekins** [SparkDevNetwork/Rock#2664]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you’re in the page settings on any page, choosing “Select Current Page” on the “Parent Page” drop down chooses the “Page Properties” page under System Dialogs. Also, System Dialogs doesn’t normally show up in that list, but after clicking “Select Current Page”, it does.

### Steps to Reproduce

1. Click "Page Properties" on the admin bar.
2. Click the "Parent Page" drop down menu.
3. Click "Select Current Page"

**Expected behavior:** 

It might make more sense to remove this option from here since you can't make a page its own parent. 

**Actual behavior:** 

[What actually happened]

### Versions

* **Rock Version:** 1.7.0.51 
* **Client Culture Setting:** en-US

**Comment by arranf** [comment]
Confirmed in 8.0
