### ISSUE TITLE
Label Merge Fields (/page/325) formatting broken - v7beta

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2665]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The formatting/CSS on /page/325 is bad in v7beta... all sorts of weird ^ characters, wrong font on grid, etc.

### Steps to Reproduce

1. Go to /page/325
2. Say "ugh!"

**Expected behavior:** 

Normal looking page

**Actual behavior:** 

Looks like Andy Warhol made it. Also verified it looks like this on prealpha.

### Versions

* **Rock Version:** 7.0 beta 

![label merge fields v7](https://user-images.githubusercontent.com/3903408/34918187-58a42d2a-f914-11e7-9cc1-b15b38cf1db4.png)

**Comment by arranf** [comment]
I've tried to reproduce this and I can't. It looks like this has been fixed at some point between this issue and the current development version.
