### ISSUE TITLE
Workflow Trigger qualifier checks are not consistent

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2671]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

> TL;DR: PreSave and PostSave logic does not match in workflow triggers. We can either try to fix the logic so it matches, leave them not matching, scrap the new feature of tracking changes in PostSave and ImmediatePostSave.

As I was working on implementing part of #2369 I can into a logic snag. I think this will end up needing to be an executive decision by the core team, but here is my findings.

The logic in the PreSave and PostSave calculations is not the same.

1. In PreSave, if you specify a blank Old value and a valid New value then it checks only the New value of the entity - BUT it requires that `NewEntityValue == EntityQualifierValue && NewEntityValue != OldEntityValue`.
2. In PostSave, if you specify a single value it translates as blank Old value and valid New value, same as above. However, it only checks that `NewEntityValue == EntityQualifierValue`
3. Additionally, in the PreSave, if you simply put a value in the `Or Value Is` field, it sets both EntityQualifierValue and EntityQualifierValuePrevious to the same value, which translates in the logic as `NewEntityValue == EntityQualifierValue && OldEntityValue == EntityQualifierValuePrevious`, that is to say `Does the new entity value match our qualifier value and has the value not actually changed`. 

The first image below is the logic map for the PreSave, and the second image is the logic map for the PostSave. I have highlighted the rows that equate to points 1 and 2 above.

<img alt="presave" src="https://user-images.githubusercontent.com/1119863/35020692-27986ef6-fae2-11e7-86bc-d699fe04003c.png">

<img alt="postsave" src="https://user-images.githubusercontent.com/1119863/35020695-2b465c84-fae2-11e7-874e-59a3e66c910c.png">

As you can see, the issue is in the case where an entity is saved but the monitored property has not actually changed. For example, if we setup a PreSave trigger on Group with the EntityQualifierColumn = Name (filter on group name); then we will get different results in a PreSave trigger and a PostSave trigger if we want to match Group's whose Name is "Frank". The PostSave trigger will always trigger, while the PreSave trigger will only match if it has actually changed.

I also mentioned in item 3 that it operates in a "does it match BUT did not change value" logic, which is shown in the first row of the PreSave image. I sort of think this logic is a bug, but I could see an argument for leaving it as is.

### Possible Resolutions

1. Change PreSave logic to match the PostSave logic. That is do not require the value to actually change.
2. Change PostSave logic to match PreSave logic.
3. Change the logic of `EntityQualifierValue` and `EntityQualifierValuePrevious` being the same (but not blank) to match either the PreSave or PostSave logic.
4. Use a filter akin to DataViews to let the user design a filter to match any logic they want. This would be a major undertaking.
5. When implementing the "did value change" logic for the PostSave and ImmediatePostSave triggers, simply use the existing logic and have the logic remain out of sync between PreSave and PostSave.
6. Scrap the new feature of tracking changes in PostSave and ImmediatePostSave.

Items 1-3 would be breaking changes, though I think item 3 would be the least likely to be actually in-use.

Item 4 would be the most powerful as it would allow for more complex checks such as `Entity.New_Name == "Frank" and Entity.New_GroupTypeId == 13 and Entity.New_IsActive == true` or `Entity.OldName != "Frank" and Entity.NewName == "Frank"`.

5 would obviously be the easiest "fix" to implement and may be the best solution until a new system can be devised to give the user better control of trigger logic (like item 4).

Lastly, 6 is certainly the truly easiest as we just scrap this new feature.

### Comments

If nothing is changed in the logic, I would suggest we change the UI wording a bit to make it clearer that the `Or value is` means `Or value has not changed and is`.

### Steps to Reproduce

1. Create two "no operation" workflow types, one called "Post-Save" and the other called "Pre-Save".
2. Create Workflow Trigger on Trigger Type = Pre-Save; Entity Type = Group; Workflow Type = Pre-Save; Workflow Name = pre-save; Entity Type Qualifier Column = Name; Or value is = Frank
3. Create Workflow Trigger on Trigger Type = Post-Save; Entity Type = Group; Workflow Type = Post-Save; WorkflowName = post-save; Entity Type Qualifier Column = Name; Value is = Frank.
4. Rename an existing group to have the name "Frank".
5. Wait a minute or two to let the Workflows (in theory) run.
6. Check both workflow types for any instances. The Pre-Save will not have an instance but the Post-Save will have an instance.

### Expected Results

I would expect either both workflows to execute or neither workflow to execute.

### Actual Results

One workflow executes, one does not.

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
I think the solution would be #2. Make the PostSave operate the same as PreSave. 

The 'Value is' field on the current PostSave would become the 'Or Value Is' field (like the PreSave). You want to make sure that this all translated well so that currently configured triggers still worked correctly. 

![pre-post-save](https://user-images.githubusercontent.com/548178/35051567-c6a86066-fb62-11e7-9f7f-78b8fe8c1db4.jpg)

**Comment by cabal95** [comment]
@edmistj Thanks for your time on this. I know this whole trigger thing has ballooned since I started working on it. Just to restate in different wording to make sure I'm on the same page about "still work correctly":

The logic of PostSave will be changed to work the same way PreSave does, meaning the trigger will not execute unless the value has _actually_ changed. Also move any database values around that might be needed to make sure that existing PostSave triggers continue to function (in the confines of the new logic).

Correct?

**Comment by edmistj** [comment]
@cabal95 That is correct.
