### ISSUE TITLE
Campus does not display in Registrants List

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2673]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you add a Registrant field of Campus and set it to Show On Grid, it will always show a blank value when viewing the list of registrants. This appears to be a bug caused by 8be4d01dd09a7c6dcaf33282779f6dc563cf2673 that @MikeDPeterson did a few months ago. Just pulling you into the conversation, not calling you out on it ;).

It looks like the value is actually filled in by the gRegistrants_RowDataBound method, and it looks for a control named `lCampus`, but that control was renamed by the above commit.

### Steps to Reproduce

1. Create registration with person field of Campus set to Show On Grid.
2. Register someone.
3. View list of registrants

**Expected behavior:** 

See a campus.

**Actual behavior:** 

void, null, blank, empty space, fear that all your data are belong to us.

### Versions

* **Rock Version:** 6.10
* **Client Culture Setting:** en-US

**Comment by drychlik76** [comment]
I confirm this issue exists in V7 from prealpha.rocksolidchurchdemo.com.  Thank you @cabal95 for filing an issue.
