### ISSUE TITLE
Communication Lists not displaying in Email Preference Entry block - v7

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#2675]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

According to the v7 docs, if a person is logged in on the public site and goes to the email preference page any communication lists they are part of will be displayed under the I'm still involved and wish to get all emails option. That is not happening. Same thing happens on pre-alpha

### Steps to Reproduce

1. Add myself to the Members and Attenders and the Parents of Youth communication lists
2. Verify that the lists have the public category on them
3. Check the block settings on the email preferences entry block to make sure it is set to show lists in the public category.
4. Login on the public site and go to the email preferences page

**Expected behavior:** 

Under the I'm still involved and with to get all emails option, there should be a list of communication lists I am included in

**Actual behavior:** 

Lists are not shown in the block

### Versions

* **Rock Version:** [7.0]  
* **Client Culture Setting:** [en-us]

**Comment by JimMichael** [comment]
I see same on my v7beta server

**Comment by edmistj** [comment]
There is a block setting on this page that will filter what lists to show. Can you confirm this setting? It may be that we need to add this to the docs.

**Comment by KelleyLangkamp** [comment]
![image](https://user-images.githubusercontent.com/12735965/35110023-79d2ad60-fc3d-11e7-8b57-ab1cec29eb5c.png)

**Comment by edmistj** [comment]
OK, and the communication lists are configured under that category?

**Comment by KelleyLangkamp** [comment]
![image](https://user-images.githubusercontent.com/12735965/35110423-63438f5a-fc3e-11e7-9947-d03e66858c99.png)
