### ISSUE TITLE
v1.7 REST API documentation page error

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#2691]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* Put an X between the brackets on this line if you have done all of the following:
    * [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

After updating to v1.7.1, when I click on the new `API Docs` page in `Power Tools`, I get the following error (confirmed by @JimMichael )
![image](https://user-images.githubusercontent.com/6932047/35247393-72f3e7b4-ff87-11e7-8f1c-758ad3d2d6b5.png)

Unable to reproduce on prealpha site; perhaps a file was manually added to that site which is not included in the migration?

### Steps to Reproduce

1. Install v7.x (confirmed on 7.1 alpha, untested in v7.0
2. Navigate to `Admin tools -> Power Tools -> API Docs`

**Expected behavior:** 

No errors, just a pretty page such as prealpha shows

**Actual behavior:** 

Errors and non-responsive links down the left side

### Versions

* **Rock Version:** v1.7.1  
* **Client Culture Setting:** EN-US 
* **Hosting:** Azure

**Comment by MikeDPeterson** [comment]
Fixed in update of v7.1 Alpha
