### ISSUE TITLE
Registration Instance Active List does not show all active

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2701]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The V7 `Registration Instance Active List` block does not show events without a set start and end date.

### Steps to Reproduce

1. Create an active registration instance without a start date and end date

**Expected behavior:** 

Show the event since it's active.

**Actual behavior:** 

Registration instance Not shown on the block

### Versions

* **Rock Version:** 7.0  
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Fixed in v7.2
