### ISSUE TITLE
Registration Instance List Details column always blank

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2702]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The registration instance list block always displays a blank `Details` column. Caused by [/RockWeb/Blocks/Event/RegistrationInstanceList.ascx.cs#L335](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/RegistrationInstanceList.ascx.cs#L335)

```
Details = string.Empty
```

### Steps to Reproduce

1. Visit an event registration page

**Expected behavior:** 

Something in the details column? Maybe remove the details column?

**Actual behavior:** 

Nothing 

### Versions

* **Rock Version:** 7.0  
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Fixed Registration Instance List Block by removing unused field from the grid (Fixes #2702)  // Internal Note: Not sure what a empty string was being put into the grid. The model does have a 'Details' property but it is unused in the UI and looking at several databases there is no value stored there. Removing it from the grid until this field is actually used.
