### ISSUE TITLE
Lava Report Field Type

### ISSUE THREAD

**Issue by mkinyon** [SparkDevNetwork/Rock#2703]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using the Lava Field Type in reporting, the lava is not rendering the rows.
![image](https://user-images.githubusercontent.com/2349102/35403963-9fc8ebfc-01be-11e8-886f-22b1a4ceb1d7.png)

### Steps to Reproduce

1. Create a new report.
2. Add an "Id" field and a Lava field.
3. Add the lava code `{{ Id }} {{ 'Lava' | 'Debug' }}`
4. Save report. 

**Expected behavior:** 

Row lava to render.

**Actual behavior:** 

Row lava is not rendered.

### Versions

* **Rock Version:** 7.1 (1.7.1.52), Latest code in develop branch
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
@MikeDPeterson I'm going to guess this is related to this recent commit: https://github.com/SparkDevNetwork/Rock/commit/8c8bde6ed0670e75494e8c8d42952a93ab3780ef#diff-a0ec88979db1cf9395827c183dc663ef

**Comment by MikeDPeterson** [comment]
@cabal95 Oh, yep, definitely related. I had meant to default ConvertToItemDictionary to true.  So, I'll fix that. It is also related to the CustomGridColumns feature, so I'll make sure there aren't any other things that could go wrong
