### ISSUE TITLE
Cannot change top level finance account order - v7

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2707]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

In V7 it is not possible to change the order of top level accounts because there is no UI provided. It is possible to set the order of child accounts through the account list block.

### Steps to Reproduce

1. Try to change financial account order

**Expected behavior:** 

Block to display and change the order of top level accounts.

**Actual behavior:** 

No block or control provided

### Versions

* **Rock Version:** 7.0  
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@garrettjohnson  that's a good point. We could add a small button to the config slide down labeled "Order Top-Level Accounts" that would take you to a new page where you could reorder them in the grid. What do you think? Is that evident enough?

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/6d041f20c90fc11bdb12b3852c93d3a76de25434
