### ISSUE TITLE
Delete column disappears from transaction list after deleting transaction

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2709]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

After deleting a transaction in the transaction list block the delete column disappears. It reappears on reload of the page.

### Steps to Reproduce

1. Delete a transaction from the transaction list block (i.e. the person contribution tab)

**Expected behavior:** 

The column stays after delete.

**Actual behavior:** 

The column disappears after performing the delete of a transaction.

### Versions

* **Rock Version:** 7.0  
* **Client Culture Setting:** en-US

**Comment by garrettjohnson** [comment]
Also, when adding and clearing filters on the transaction list the Person Column, Currency Type, Batch Id, and Accounts all appear blank

**Comment by MikeDPeterson** [comment]
@garrettjohnson Thanks for reporting this bug.  In this case, the bug was that the delete column was *visible* on the first load. It should only be visible when showing transactions in the context of an open batch.
