### ISSUE TITLE
Cannot use } in Output-style Lava

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2712]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using Lava, you cannot use the `}` character without causing an error when you are using `{{ }}` syntax. Using `{% %}` syntax, however, works.

Use case is trying to use a regular expression in a filter, such as `(abc){3}`.

### Steps to Reproduce

1. `{{ 'Test' }}` -> `Test`
2. `{% assign c = '}' %}{{ c }}` -> `}`
3. `{{ 'Test}' }}` -> `Error resolving Lava merge fields: Variable '{{ 'Test}' was not properly terminated with regexp: (?-mix:\}\})`

**Expected behavior:** 

I should be able to use `}` in lava.

**Actual behavior:** 

I have a sad panda face and cannot use `}`.

### Versions

* **Rock Version:** 6.3,7.1,8.0
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
This limitation comes from the base library dotLiquid. I don't see us fixing this in their code in the near future since it's very much an edge case. If using a capture then passing the expression in does not work (as noted on the documentation) let us know. Perhaps there is another workaround.
