### ISSUE TITLE
Person Has Note dataview filter returns nothing without selecting note type

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2714]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The [Has Note Filter](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Reporting/DataFilter/Person/HasNoteFilter.cs) person data view returns no results unless a Note Type is selected.

### Steps to Reproduce

1. Create a Person "Has Note" data view filter on a Person entity
2. Leave the Note Type dropdown empty
3. Set Contains to a known note (i.e. "The")

**Expected behavior:** 

Return all notes since the note type is not required

**Actual behavior:** 

Nothing is ever returned.

### Versions

* **Rock Version:** 7.0  
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
To properly fix this, the query would probably need to be changed. The Note Type is what is used to determine that the Note.EntityId is referring to a Person entity. So if a Note Type is not specified we need a different way to limit to notes that are related to the Person entity. Probably something like `noteQuery.Where(n => n.NoteType.EntityTypeId == personEntityTypeId)`.
