### ISSUE TITLE
Security Roles block allows delete on Data View sync'd groups

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2715]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Rock will allow deleting membership in a security role, even if the group is set to sync with a data view. Which results in the membership being temporarily removed until the group sync job runs.

### Steps to Reproduce

1. Delete a security role that's sync'd to a data view

**Expected behavior:** 

Do not allow delete, since the removal from the security role will only stay until the Data View sync runs.

**Actual behavior:** 

Deletes security role.

### Versions

* **Rock Version:** 7.0  
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Closing this as it's the same block/code as https://github.com/SparkDevNetwork/Rock/issues/2716
