### ISSUE TITLE
Group List block allows delete on Data View sync'd groups

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2716]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Directly related to #2715 (Security Roles)

Rock will allow deleting membership in a group, even if the group is set to sync with a data view. Which results in the membership being temporarily removed until the group sync job runs.

### Steps to Reproduce

1. Delete a group membership from a group list block that's sync'd to a data view

**Expected behavior:** 

Do not allow delete, since the removal from the group will only stay until the Data View sync runs.

**Actual behavior:** 

Deletes group membership.

### Versions

* **Rock Version:** 7.0  
* **Client Culture Setting:** en-US

**Comment by MikeDPeterson** [comment]
@garrettjohnson  I'm not able to reproduce this.  I tried locally on a v7 branch and I also tried updating the demo site to v7 and couldn't reproduce it either http://rock.rocksolidchurchdemo.com/page/113?GroupId=3191&ExpandedIds=40.

**Comment by garrettjohnson** [comment]
To replicate the issue drill into the profile page and groups tab on any person in the group. Rock allows the delete from there.
