### ISSUE TITLE
Attributes of type Attribute Matrix display nothing but their label in 'View-Only' mode on the Person Profile Page

### ISSUE THREAD

**Issue by tcavaletto** [SparkDevNetwork/Rock#2721]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Tested on the Prealpha site:
Formatted Values of Attribute Matrix Templates are not being shown in the AttributeValues blocks on a person's profile. While inspecting the elements on the page, removing the Css Class 'matrix-attribute' causes the formatted value to be displayed. It looks like this commit https://github.com/SparkDevNetwork/Rock/pull/2569/commits/9ebc54e17d95af8898eb5fd747f10c6b33f16378 is setting the div containing the table to have the 'display:none' style.

### Steps to Reproduce

1. Create an Attribute Matrix Template
2. Create a Person Attribute of type Attribute Matrix
3. Add an AttributeMatrixItem to the Person Attribute
4. Refresh the page to see the 'view-only' version of the attribute

**Expected behavior:** 
I expect to see a table with rows detailing the AttributeMatrixItems I have added.

**Actual behavior:** 

I see nothing but the Person Attribute's label

### Versions

* **Rock Version:** Rock McKinley 8.0 (1.8.0.8)
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Fixed in v7.3
