### ISSUE TITLE
Export Report On Post Transformation Data View

### ISSUE THREAD

**Issue by drychlik76** [SparkDevNetwork/Rock#2723]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Exporting a report, from a data view, that uses a post transformation (applied to the data view), causes the object reference as a string to be exported in Excel.  
The report displays the Childs name just fine, however on export to excel, the object reference is displayed as a string value.

`Rock.Reporting.DataSelect.Person.ChildNamesSelect+KidInfo, Rock.Reporting.DataSelect.Person.ChildNamesSelect+KidInfo, Rock.Reporting.DataSelect.Person.ChildNamesSelect+KidInfo, Rock.Reporting.DataSelect.Person.ChildNamesSelect+KidInfo`

### Steps to Reproduce

1. Create a data view that applies to a person.  Set the Post-filter Transformation to Parents.  Apply an advanced filter `In Group(s)(Advanced)`.
2. Create a report that applies to Person and use the data view, created in step 1.  Set some fields, and include an advanced filter type called `Children's Names`.  Select show in Grid, Included Gender and Include Age.
3. Click export to excel to see the bug.

**Expected behavior:** 

I expected to see the children, age and gender printed normally in this field.

**Actual behavior:** 

Object reference to KidInfo displayed as a string value.  
<img width="1279" alt="screen shot 2018-01-31 at 8 26 25 am" src="https://user-images.githubusercontent.com/20803057/35630302-ae640d7a-0666-11e8-9fa4-6fa48ffa2e26.png">

### Versions

* **Rock Version:** 6.10
* **Client Culture Setting:** English

**Comment by MikeDPeterson** [comment]
@drychlik76 This is fixed in v7.0
