### ISSUE TITLE
Gender not triggering Required field validator

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2725]
See prior reported issue at #1643, this was (and is) an issue with version 6.  I can confirm that other fields are working correctly in version 7+, except for the Gender field.

### Description

Create an [event registration](http://prealpha.rockrms.com/page/5347?RegistrationTemplateId=1) with multiple fields marked required, including Gender:

![screenshot 2018-02-01 13 33 17](https://user-images.githubusercontent.com/1210933/35696109-7c3d6190-0754-11e8-8289-871f24d74099.png)

All fields show a required indicator, except Gender does not throw a Required error:

Local / Version 7:

![screenshot 2018-02-01 13 26 25](https://user-images.githubusercontent.com/1210933/35696064-559ccb84-0754-11e8-939f-fc4968014c39.png)

[Prealpha](http://prealpha.rockrms.com/Registration?RegistrationInstanceId=2) / Version 8:

![screenshot 2018-02-01 13 16 25](https://user-images.githubusercontent.com/1210933/35696051-448c669c-0754-11e8-88f7-bb910dcc47c1.png)

You can continue through registration without entering a Gender.

![screenshot 2018-02-01 13 16 36](https://user-images.githubusercontent.com/1210933/35696091-65a1b4b8-0754-11e8-889b-3b133df12a7e.png)

**Expected behavior:** 

Gender would be required.

**Actual behavior:** 

Gender is not required.

### Versions

* **Rock Version:** v7 and v8
* **Client Culture Setting:** en-us

**Comment by dcs619** [comment]
This is still an issue in v7.3

**Comment by edmistj** [comment]
I do that all the time.

**Comment by arranf** [comment]
I can reproduce this in v8
