### ISSUE TITLE
Reports do not save Communication Recipient Fields

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2727]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When creating a report Rock will not save any values entered into the `Communication Recipient Fields` field. 

### Steps to Reproduce

1. Enter a value in the `Communication Recipient Fields`field in advanced settings on a report
2. Save
3. Attempt communication using the recipient field

**Expected behavior:** 

Rock saves the `Communication Recipient Fields` value and uses that for communication.

**Actual behavior:** 

Nothing is saved and the Id is used for communication.

### Versions

* **Rock Version:** 7.2  
* **Client Culture Setting:** en-US

**Comment by MikeDPeterson** [comment]
@garrettjohnson  I think what was happening is it was letting you enter incompatible communication recipient fields by manually keying them in.  The way it is *supposed* to work is that only certain fields can be used a Recipient Fields (for example Parent's Name or Kid's Names), and then those would be pickable from a dropdown when adding Communication Recipient Fields.  So, we updated the UI to only enable the Add button for Communication Recipient Fields if there were any fields in the report that could be used.  The HelpText was also updated to help explain it better.  Does that seem to be what you were experiencing?
