### ISSUE TITLE
Attributes disappear when creating a new EventItemOccurrence

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#2729]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When creating a new occurrence using the Event Item Occurrences Details block, any postback will cause the attribute fields to disappear.

@cbump You mentioned in #2505 that you copied the functionality from a different block. Do you remember which one that was? It's possible something didn't get fully replicated (or that block may have a similar issue).

### Steps to Reproduce

1. Set up Attributes for event item occurrences.
2. Go to create a new event occurrence.
3. Change any field that would cause a postback (adding a schedule, setting a contact, etc)

**Expected behavior:** 

The attribute fields stay showing and hold their values.

**Actual behavior:** 

The attribute fields disappear and their values aren't saved.

### Versions

* **Rock Version:** PreAlpha  
* **Client Culture Setting:** en-us

**Comment by edmistj** [comment]
@cbump We're hoping to package v7.3 on Wednesday (Feb 7). Would you be able to submit a PR by then?

**Comment by arranf** [comment]
I've tried to reproduce this and I can't. It looks like this has been fixed at some point between this issue and the current development version. 🎉
