### ISSUE TITLE
Communication Approvers cannot access communications pending approval

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2730]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Users who are members of `RSR - Communication Approvers` and/or `RSR - Communication Administration` cannot view pending approval communications in the "Communication List" block on the communications history page or view the block to approve messages on the communication detail page. When they load a pending communication detail page they get a page with the title, but the `Communication Detail` block does not load.

### Steps to Reproduce

1. Login as a `RSR - Communication Approvers and/or RSR - Communication Administration` user
2. Try to access a pending communication.

**Expected behavior:** 

Ability to view pending communications

**Actual behavior:** 

Pending communications do not show in grid list and cannot be accessed for approval.

### Versions

* **Rock Version:** 7.2  
* **Client Culture Setting:** en-US

**Comment by garrettjohnson** [comment]
@MikeDPeterson In testing the hotfix it doesn't appear to solve the issue. When directly linking to the simple editor `https://rock.churchname.org/page/540?CommunicationId=8815&edit=true` the page is blank for communication approvers and communication administrators.

**Comment by alyssa-pathway** [comment]
Is there a fix to this in 7.4? We're still experiencing this issue in 7.3.

**Comment by cabal95** [comment]
@alyssa-pathway Can you be more specific about the problem? Is it that you cannot access pending communications, or communications that should be pending are sent immediately? The latter is a different bug that has just been fixed so it should be in 7.4.

**Comment by alyssa-pathway** [comment]
@cabal95 - The members of the 2 security roles mentioned in the issue's description cannot view pending communication. They receive the notification email, they can open the page, but they cannot view the block in order to see and approve/deny communications.

**Comment by cabal95** [comment]
@azturner It looks like your second commit 02313e4 finished fixing this, is that commit going to land in 7.4 or should it already be in 7.3?

**Comment by azturner** [comment]
That commit looks like it was included in v7.3

**Comment by garrettjohnson** [comment]
At NorthPointe we had the same issue in 7.3 where the blocks do not show

**Comment by cabal95** [comment]
I talked to @alyssa-pathway  on Slack and she tried to replicate it on the demo site but, I believe, wasn't able to. So it may be something that only crops up in certain configurations. We just did the 7.3 upgrade tonight so I'll see we can get that tested tomorrow or Friday.

**Comment by cabal95** [comment]
Tested on my new 7.3 install. We are seeing a different issue than what Alyssa has report (still investigating her exact issue). Here is what I am seeing. When the e-mail comes in telling me a communication needs to be approved, the URL link to view that communication is wrong. It doesn't include the communication Id or anything, so the page I am linked to starts creating a new communication. This is when sending a communication requiring approval from the old Simple communication page. I believe the line in question is this:

https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Communication/CommunicationEntry.ascx.cs#L679

When that ApprovalPageUrl is supplied, it us used as the URL for the e-mail, which does not include the communication Id. Which in this case, is the URL to the page but no parameters supplied to indicate which communication it is.
