### ISSUE TITLE
[EN] Require or warn when Event Registration Confirmation Email is blank

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2731]
### Description

If an admin is manually entering event registrations via [RegistrantDetail](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/RegistrationDetail.ascx.cs#L1769) and they haven't entered a confirmation email, none of the manual payments will go through.  This is already required on the user-facing side, but not the admin-facing one.  

Email is required by CyberSource, NMI and Simple Donation gateways to process a transaction - possibly PayFlow Pro too:

![screenshot 2018-02-01 17 18 49](https://user-images.githubusercontent.com/1210933/35706857-65cacfd0-0775-11e8-9b7c-1c07f3f2cb75.png)

![screenshot 2018-02-01 17 19 48](https://user-images.githubusercontent.com/1210933/35706860-67b2b59c-0775-11e8-96bd-6c38b57f149f.png)

Once fixed I believe this fixes issue #1869 as well.

### Steps to Reproduce

1. Get a call from a user trying to register for an event
2. Enter their credit card detail and submit
3. Try to figure out why it didn't go through

**Expected behavior:** 

Warning or required field validator on Confirmation Email

**Actual behavior:** 

No warning or field validator

### Versions

* **Rock Version:** v6.10-v7  
* **Client Culture Setting:** en-us

**Comment by azturner** [comment]
The confirmation email is not actually required when using NMI or PayFlowPro. Seems like making that field required might cause some frustration, as the only time it would be blank is when selecting a person who does not have an email on record. In those cases, what would the admin type in? Today, they can still add registrations without knowing the person's email. This change would mean they couldn't.  Seems like better solution would be that if a Gateway requires the confirmation email (CyberSource? and Simple Donation?) that it returns an error message indicating that an email address is required. The block will already display any error message that the gateway returns.

**Comment by dcs619** [comment]
@azturner You're correct, I assumed email was required for NMI based on the custom gateway for NS.  I'll close this and let the gateway return an error.
