### ISSUE TITLE
ExceptionLogService should always log to RockExceptions.csv during initialization

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2733]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If an exception occurs during Application Initialization, it is logged to the ExceptionLog table. But sometimes that exception also causes Rock to completely fail to load, including the Error.aspx page. This puts the user in a state where the only way they can determine the true error is by somehow logging into SQL. In a hosted environment this can be very difficult.

Suggesting that we have a global variable (or something equivalent) so that the ExceptionLogService.LogException method can check if Rock is fully initialized and if not attempt to log the exception in SQL, but then ALWAYS log the exception in the csv file as well. Once initialization is done and Rock is fully up and running it would revert to current behavior.

* **Rock Version:** 7.0
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@cabal95 Green light if you want to work on it.
