### ISSUE TITLE
Transaction Matching Page - Batch Detail Page setting is blank by default

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#2738]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

[In version 7.2 (possibly sooner 7.0 or 7.1) when doing transaction matching and you get to the end and click DONE - nothing was happening and Daniel Hazelbaker pointed out that there was no detail page selected on the block settings. Same on my production server and same on demo site.  So apparently it removes that detail page for some reason when updating. ]

### Steps to Reproduce

1. [Go to transaction matching page: /page/311?BatchId=xxxx and edit block setting and add "batch detail page"]

**Expected behavior:** 

[When you click DONE it should go to another page and if there is no detail page it just sits there]

**Actual behavior:** 

[When you click DONE it should go to another page and if there is no detail page it just sits there]

### Versions

* **Rock Version:** [7.2]  
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by cabal95** [comment]
Just to note, I checked on our production which is still 6.8 so this isn't a v7 related issue. It's probably been like this since day one. Rock demo site has the same issue.

Suggested fix would be a migration to populate that setting.

**Comment by MikeDPeterson** [comment]
Fixed in v7.3 with https://github.com/SparkDevNetwork/Rock/commit/12d2c515240bac321e15120e1713e1cc4486bee7#diff-4363c0c55be3867024e558576ba93709R59
