### ISSUE TITLE
Model Map block would benefit from filters and query string parsing

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2739]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Having just used the Model Map block for the first time (I know I know), it is very handy but can be difficult to understand in the current way it displays things.

I would suggest that we add more Rock-style filters to the block. Specifically, the following:

* Required - [Yes/No/Blank]
* Database Property - [Yes/No/Blank]
* Lava Supported - [Yes/No/Blank]

Secondly, I think a `fa-link` icon should be included that provides a link back to the page with the current configuration. This would make it easier to share links with others that take them directly to the entity and with the correct filters applied. This would be handled via query string parameters, probably akin to `?EntityTypeId=10&Database=True&Inherited=True`

Use Case: for documentation on some plugins it would be nice to include a link to the Rock demo site model map page with the filters applies so that it shows the entity and also automatically filters to "include inherited, show only database properties".

### Versions

* **Rock Version:** 7.2
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Marked available.

**Comment by nairdo** [comment]
@cabal95 the querystring/linking-to features got removed when it got that major refactoring but you can see it in action on this old Rock install here: http://churchitnetwork.com/modelmap

I avoided using EntityTypeId at the time and used guids instead.

**Comment by cabal95** [comment]
Would love some feedback on this implementation before I submit a PR. I have left the "show inherited" as existing functionality for now. I'm on the fence if that should be part of the filters or not. Filter expands and collapses like a normal grid filter.

The "fa-link" embeds the EntityType guid into the query string which will bring the user back to that entity (and it's category) automatically later.

I have not included the following in the "fa-link" url, but the following are also available in the query string:

* Category - pre-select a category by name
* IsRequired - Initial value of the Is Required filter
* IsDatabase - Initial value of the Is Database filter
* IsLava - Inital Value of the Lava Suported filter

This should allow for more useful linking from documentation to the model map (on the demo site for example) to bring up very specific information, but not clutter the average user's copying and pasting of links back to the entity they were viewing.

![screenshot-2018-2-21 model map rock rms 1](https://user-images.githubusercontent.com/1119863/36511814-052d9862-171d-11e8-84d4-8be124c3473f.png)

![screenshot-2018-2-21 model map rock rms 2](https://user-images.githubusercontent.com/1119863/36511865-3bd2115e-171d-11e8-8d93-b4afc1964ee5.png)

**Comment by edmistj** [comment]
Looks great!
