### ISSUE TITLE
New "Page Menu" Blocks Broken in V7

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2741]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

In V7 creating a new `Page Menu` block creates a block that does not render child pages. Adding `{{ Page.Pages | ToJSON }}` as a diagnostic on the new block renders `null` even if there are child pages.

### Steps to Reproduce

1. Create a page and a child page.
2. On the Parent page add a Page Menu Block

**Expected behavior:** 

Page menu should be populated with child pages

**Actual behavior:** 

No child pages shown, `{{ Page.Pages | ToJSON }}` returns `null`

### Versions

* **Rock Version:** 7.2  
* **Client Culture Setting:** en-US

**Comment by MikeDPeterson** [comment]
@garrettjohnson This was caused by 'Show Child Pages' not defaulting to true when a new page was adding using the new Pages UI.  This fixes this issue.  To fix any pages that were added in v7 (and need the Page Menu Block), you'll have to manually enable 'Show Child Pages' on the parent page.
