### ISSUE TITLE
Simple Communication block missing "Copy" feature

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#2742]
In Rock v6 and prior there was a "Copy Communication" feature as seen below - this feature is not shown to anyone accept Rock Administrators in V7 for some reason.

Version 6: 
![image](https://user-images.githubusercontent.com/657005/35882830-0f0344e6-0b4b-11e8-9ebe-3ebd91552e26.png)

Version 7:

![image](https://user-images.githubusercontent.com/657005/35882945-55b60a2c-0b4b-11e8-91f3-49e874392172.png)

What I would expect:
That this would still be an option in V7 for the Staff role and Staff Like Access roles.

**Comment by MikeDPeterson** [comment]
@austinspooner  This is due to the same bug as #2730, so it'll be fixed in v7.3
