### ISSUE TITLE
Calculate Person Duplicates job takes a long time - v7

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2748]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Calculate Person Duplicates job in v7 is much slower than the same job in v6. What took under 20 seconds on my v6 db now takes 18+ minutes on my v7 (same db) server.

### Steps to Reproduce

1. Run Calculate Person Duplicates job
2. Wait
3. It will likely time out as the default of 5min for the job is insufficient to let it run.
4. Increase to 1500 seconds and (at least on my system) that's enough to let it complete.

**Expected behavior:** 

Similar performance to v6 job, unless improvements/changes to the find duplicates algorithm in v7 now demand such a long run time... in which case, you can ignore and close. I also ran the database maintenance job again to eliminate bad indexing, etc as the culprit... exact same result.

**Actual behavior:** 

It's sloooow, and likely times out on most default Rock installs.

### Versions

* **Rock Version:** 7.2

**Comment by dcs619** [comment]
For a database with 76k people, the v7 job consistently takes 20-22 minutes.  I can provide more detail if it would be helpful.

**Comment by MikeDPeterson** [comment]
thanks @dcs619 for helping us fix and troubleshoot this!

**Comment by MikeDPeterson** [comment]
for anybody curious, we think that some databases were slow because the plan optimizer didn't know that most of the values would be null for SuffixId, so adding an explicit where IS NOT NULL clause helped
