### ISSUE TITLE
Splitting Transactions for Events Shows Incorrect Balance

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#2751]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

#### Scenario
Church ABC is hosting an event. The event cost $1,000 to attend. The cost to the church for hosting the event is $400 per person, and $600 is put into contributions. Church ABC would like for the $600 piece to be transferred to a tax deductible account so attendees can add it as a deduction.

#### Issue
When one of the account staff at Church ABC move the $600 piece to the tax deductible account, the balance due changes because part of the transaction lives in a separate account. In addition to this, you can only have a single account tied to an event.

### Steps to Reproduce
1. Create an event
1. Set cost (We will set this to $1000)
1. Set account (We will set this to Event Registration)
1. Create Registration Instance for event
1. Add registrant and take payment for full amount due
1. Go into Finance -> Transactions and select transaction
1. Edit transaction
1. Update Financial Transaction Detail item to cost of event (in our case that would be $400)
1. Create new Financial Transaction Detail item for the contribution amount (this would be $600)
1. Save and go back to Registration -> Registrant

**Expected behavior:**
Paid amount should not change based on the account

**Actual behavior:**
If paid amount is modified, this is reflected in the Cost Summary.

### Versions
* **Rock Version:** 6.10, 7.2
* **Client Culture Setting:** en-US

**Comment by jsw-austin** [comment]
This is something that we see many churches express that they'd like to see handled differently in Rock.  Several churches have requested the ability to set the Financial Account on the fee level and there are multiple ideas posted around this on the idea board (which ends up causing people to think this idea is less popular than it is unless you count the votes for all the various ideas around this).

**Comment by jonedmiston** [comment]
@jsw-austin  if you can send me the ideas that represent this one concept I can merge them (and their votes). 

The difficulty with this is that it's much more complex that it sounds. When you consider fees and the numerous forms of discounts it would be very difficult to know the best way to calculate the split. It would be good if the ideas provided suggestions, that the community could validate, on how they'd like the logic handled (especially considering fees and discounts).

**Comment by jsw-austin** [comment]
well, I swear I looked a couple weeks back and there were 3, but I only see 1 now.  https://community.rockrms.com/ideas/1285/allow-for-separate-funds-for-registration-and-fees

I do think this will become more important if "Cover the Fee" is rolled out for event registrations (I've seen work on this functionality but not sure if it's only for transaction entry) as many churches will want to consider the covered fee as a contribution.

**Comment by chead4** [comment]
@tscrip HI Tyler, thank you for submitting your first issue.  After reviewing the issue, this is an enhancement to allow Registration/Fee transactions to be posted to multiple Financial Accounts.  This idea is on our Ideas board and if you want to use your voting points on it, I’d ask you to jump over to the idea and vote it up.  https://community.rockrms.com/ideas/1285/allow-for-separate-funds-for-registration-and-fees.  Thank you for the detailed submission and for helping to make Rock better!
