### ISSUE TITLE
HTML Version History doesn't work since v7 update

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#2756]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

[Version history on html block does not work. If I click to go to an older version nothing changes.]

### Steps to Reproduce

1. [Edit HTML block with versioning enabled and click save]
2. [Go back to edit and click version 1 or older one and nothing changes]

**Expected behavior:** 

Before v7 if I went to prior version it would show me prior version

**Actual behavior:** 

when clicking old version nothing happens

### Versions

* **Rock Version:** [7.2]  
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by cabal95** [comment]
Tested on pre-alpha (v8) and saw the same problem.

**Comment by taylorbrooks** [comment]
Not sure if this is related, but if you set the ending "display from" to a past date, it will delete the HTML content.

![block](https://user-images.githubusercontent.com/117657/36875290-f31239f4-1d74-11e8-8e35-197300af9ddd.gif)

**Comment by timlem** [comment]
Just double checking on this as I didn’t see it referenced in the release notes?

**Comment by cabal95** [comment]
It should be there. The commit was marked as a minor change (probably because of how much code was changed), so it didn't show up in the release notes.
