### ISSUE TITLE
Cannot delete benevolence documents

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2758]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Benevolence documents cannot be deleted by any user after upload.

### Steps to Reproduce

1. Upload a benevolence document
2. Try to delete the document.

**Expected behavior:** 

Benevolence workers or admins can delete benevolence documents

**Actual behavior:** 

Documents cannot be deleted by anyone

### Versions

* **Rock Version:** 7.3 - Prealpha  
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
+ Fixed FileUploader to pass correct arguments when using a grid to store the control.
