### ISSUE TITLE
Separate Attributes for different Background Check Document types / Background Check workflow update

### ISSUE THREAD

**Issue by luke-infoministry** [SparkDevNetwork/Rock#2760]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers ](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When running background checks of different types, the document from the last run check is saved as the only background check document.  This causes an issue when running concurrent multiple types of background checks, e.g.  a State check and a Driving record check.  Often times these will be run at the same time, so the over-writing leaves safety and security staff unable to effectively review all the necessary information.

Request: Adjust SaveReport Workflow Action in the Process Report Workflow Activity to be aware of background check type (PackageType attribute in the workflow)[Probably multiple SaveReport actions with filters] , provide document type attribute for each type of check, store documents accordingly.

### Steps to Reproduce
1. Perform Criminal Background check on individual
1. Perform Driving Record check on individual
1. Discover that you can't view Criminal Background check document :disappointed:

**Expected behavior:**

Ability to view all background check information

**Actual behavior:**

Later background checks, regardless of background check type, overwrite earlier checks

### Versions
* **Rock Version:** 6.2-7.2
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
