### ISSUE TITLE
Include Age with BirthDate on Event Registrants list

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2763]
### Description

Some of our ministries have a need to know the age of the person that has signed up for an event. Not a "we want to make sure they are the right age" kind of thing where they can just look them up, but a "we need to see all the ages in the list so we can assign them to the right team, group, etc." kind of thing.

Our thought was to make use of the BirthDate field as an Internal field. That would show the BirthDate but not calculate the age. So our thought was to extend the display of the BirthDate column value on the Registration Instance Detail block to be formatted like `1/31/1981 (37 yo)`, and for ages < 1 year probably `1/31/2018 (2 mo)`.

To do this, we would update the Rock.Web.UI.Controls.DateField to add property called `IncludeAge`. When set to true the format above would be used, when false the current format would be used.

In the case that both `FormatAsElapsedTime` and `IncludeAge` were used, `FormatAsElapsedTime` would take precedence.

### Versions

* **Rock Version:** 6.8,7.2,8.0,etc
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@cabal95 sounds good.

**Comment by cabal95** [comment]
Sample

<img width="886" alt="2018-02-13 13_59_17-registration instance _ rock rms" src="https://user-images.githubusercontent.com/1119863/36176017-2b57360e-10c6-11e8-8bec-18027446742c.png">
