### ISSUE TITLE
Viewstate Error on Registration Template Editing "Registration Attributes"

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#2764]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Rock throws Error when trying to add two Registration Attributes onto a Registration Template:

```
Error

Failed to load viewstate. The control tree into which viewstate is being loaded must match the control tree that was used to save viewstate during the previous request. For example, when adding controls dynamically, the controls added during a post-back must match the type and position of the controls added during the initial request.
   at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
```

### Steps to Reproduce

1. Edit a registration template
2. Add a new "Registration Attribute" field to the Default form.
3. Try to add another "Registration Attribute" field to the Default form.   It will show the loading spinner for a few minutes and then Error out with the error shown above.

**Expected behavior:** 

No error.

**Actual behavior:** 

Error is thrown and you must start over because the save doesn't work either.

### Versions

* **Rock Version:** Rock McKinley 8.0 (1.8.0.10)
* **Client Culture Setting:**en-US

**Comment by edmistj** [comment]
I think @MikeDPeterson  may have fixed that Friday via: https://github.com/SparkDevNetwork/Rock/commit/022a76d61a78d2cd6406ca3e1a9422596d3c964f

@nairdo  can you confirm?

**Comment by nairdo** [comment]
this is a duplicate of #2750
