### ISSUE TITLE
Emails being sent with incorrectly formatted From Address, v7.2

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#2772]
### Description

Emails are being sent with the From Address formatted incorrectly.

This is happening for test emails and actual sent emails.
This is happening from simple communication and from the new communication pages.

If From Address is entered as my.name@url, and organisation address is Url.Organization, then the From Address is formatted as  my.name=url@Url.Organization.

Examples:  
![email1](https://user-images.githubusercontent.com/4658177/36241405-f6c28b3a-127a-11e8-8ea2-6c8ad27e203b.jpg)

![email2](https://user-images.githubusercontent.com/4658177/36241409-fbbbe168-127a-11e8-978b-fbaacaaa9c47.jpg)

It looks like the Sender field in the email header is the only field wrong.  Refer to a copy of an email header attached below.

Because of this, emails are being flagged as spam and in some cases are not being delivered.

### Steps to Reproduce

Send an Email communication using the New Communication or New Communication Simple screens.
version:

**Expected behavior:** 

Email sender formatted as per what is entered in the email communication Sent From field, not modified in any way.

**Actual behavior:** 

The email Sender value is being corrupted.

### Versions

Rock Version: Rock McKinley 7.2 (1.7.2.53)
Client Culture Setting: en-US

### Email Header text:
Incorrect email highlighted in bold.

![email3](https://user-images.githubusercontent.com/4658177/36242247-a225d578-127f-11e8-9454-b6a43766a39b.jpg)

**Comment by mikejed** [comment]
Ken,
Does this happen if you send an email from an address within your safe senders domain(s) or only when sending from an email address in an independent domain?

**Comment by nairdo** [comment]
As mentioned by @mikejed: https://www.rockrms.com/Rock/BookContent/9/113#safesenderdomains

**Comment by ElimAdmin** [comment]
Ah!  Ok, thanks @mikejed and @nairdo.  
This does not happen if I use the full domain name @porirua.elim.org.nz in the from address.
This issue can be closed.

I do note, however, that I had both porirua.elim.org.nz, pe.org.nz, and gmail.com are all listed in our Communications/Safe Sender Domains.

Given that pe.org.nz is listed as a 'safe sender domain' - I'm wondering why it was still changed?
If I used a From with @pe.org.nz, even though this is the list of Safe Sending Domains, the address is still 'fixed.'

The text on the Safe Sender Domains screen reads, "Safe Sender Domains are the domains that can be used to safely send outgoing emails. If an email communication is created with a From Address that is not from one of these domains, Rock will change the From Address to the Organization Email global attribute value instead, and the original From Address will be used as the Reply To address. Rock will not change the from address if the email is from one of these safe domains, ...  This is to help reduce the likelihood of communications being rejected by the receiving email servers due to the email having a different sending domain than the server sending the email. "

This did not happen: the From address WAS in the list, but it was still changed to the Organization global attribute.

And I'm wondering if this text is not quite precise (or not clear enough for newbie emailers like me)?  It is not that I have these domains LISTED on my Safe Sender Domains page that makes them 'safe' from being assessed as spam, but that they ARE ACTUALLY being sent from that domain.   This was a misunderstanding on my part.

This is probably not a problem for most.  We are unusual in that we have an email alias domain:  @pe.org.nz.

I am deleting pe.org.nz and gmail.com from our Safe Sender Domains, and leaving only the real domain name we email from: porirua.elim.org.nz.

I also wonder if some sort of warning might be useful on the Email sending page so that if a user enters a 'From' address that is not on Safe Sender Domain list they are alerted to this.

**Comment by edmistj** [comment]
Closing per request to close.
