### ISSUE TITLE
Ace editor incorrectly reports doctype and html errors on blocks

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2774]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The default `EditorMode` for Ace Editor is `Html` in on many blocks that are html, but are effectively partials. 

### Steps to Reproduce

1. Search source code for `EditorMode="html"` to find a relevant block location.
2. Type code you'd use in the block
3. Observe nonsensical validation errors

**Expected behavior:** 

Set all Html fields to lava, unless they're actually declaring a doctype (i.e. communication templates)

**Actual behavior:** 

Ace expects a full well formed html document.

### Versions

* **Rock Version:** 7.2  
* **Client Culture Setting:** en-US

**Comment by azturner** [comment]
@garrettjohnson, where would the validation errors be displayed? For example the Admin Checklist on the default Rock internal home page has HTML in the pre and post HTML properties, and I don't see any validation errors when saving that content.
