### ISSUE TITLE
Fundraising Participant "Share" Links aren't passed correctly to Twitter or Email

### ISSUE THREAD

**Issue by bengoshow** [SparkDevNetwork/Rock#2775]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The share buttons on the Fundraising Participant page won't work with multiple URL query variables. The Twitter and Email share links interpret those additional query vars as part of the "sharer" URL and not part of the "shared page" URL being passed.

### Steps to Reproduce

1. Visit a fundraising participant page with multiple URL query variables, like http://vineyardrms.rmrdevelopment.com/page/3351?GroupId=106789&GroupMemberId=558734
2. Click on the Twitter or Email share links
3. Notice that the link being shared drops the GroupMemberID variable

Incidentally, the Facebook share button works because it uses a script to pass the full URL instead of a href link.

### Versions

**Rock Version:** Rock McKinley 6.8
**Client Culture Setting:** en-US

**Comment by bengoshow** [comment]
Fixed it using | EscapeDataString, but I don't know how to create a PR

**Comment by edmistj** [comment]
@bengoshow not problem. Could you paste in here the line(s) you updated?

**Comment by garrettjohnson** [comment]
@edmistj I'm on it.
