### ISSUE TITLE
v8 still uses legacy Lava in Background Check workflow

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2776]
### Description

The Set Warning action in the Initial Request activity still uses legacy Lava syntax. 

### Steps to Reproduce

1. Edit BGC workflow
2. Observe {{ Workflow.DateAttribute_unformatted }} and {{ Workflow.Person_unformatted }} being used in the Warn of Recent action.

**Expected behavior:** 

New versions of Rock should eliminate Legacy Lava in core places.

**Actual behavior:** 

Old Lava exists in new versions of Rock, preventing the user from switching to No Legacy mode for performance/correctness reasons without modifying these areas themselves. That said, in my opinion fixing the SQL in this workflow is not worth the trouble... it seems overly complex and unnecessary. Eliminating the Warn of Recent action (and its associated attribute) altogether and doing the "recent BGC" check within the User Form itself seems like a cleaner option. For example:

{% assign personObject = Workflow | Attribute:'Person','Object' %}
{% assign daysSinceBGC = personObject | Attribute: 'BackgroundCheckDate','RawValue' | DateDiff: 'Now', 'd' %}
{% if daysSinceBGC < 365 %}
    <div class='alert alert-warning'>
        Notice: It's been less than a year since this person's last background check was processed.
        Please make sure you want to continue with this Background Check!
    </div>
{% endif %}

### Versions

* **Rock Version:** [Enter Rock version here]  
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by edmistj** [comment]
@JimMichael thanks Jim. Keep reporting these as you find them. Our goal is to get rid of this in v8.

**Comment by JimMichael** [comment]
DISC Request also uses Legacy Lava in the Check for Opt Out action. I won't enter a new issue as it's already been reported here https://github.com/SparkDevNetwork/Rock/issues/2018 

Just mentioning here that it's still an issue in v8.

**Comment by garrettjohnson** [comment]
The Photo Request template uses a non-existent lava attribute in v8 #1930

**Comment by JimMichael** [comment]
I'm finding more.. @edmistj would you prefer I mention them here, or open separate issues?

**Comment by edmistj** [comment]
@JimMichael separate issues would be best.

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in 3e21ed58.
