### ISSUE TITLE
v8 still uses Legacy Lava in Person Data Error workflow

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2779]
### Description

The Notify Originator action in the Complete activity still uses legacy Lava syntax.

**Expected behavior:** 

New versions of Rock should eliminate Legacy Lava in core areas. 

**Actual behavior:** 

Email send action references several WF attributes with legacy syntax, preventing the enabling of No Legacy mode without users manually fixing this up.

### Versions

* **Rock Version:** all

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in 3e21ed58.
