### ISSUE TITLE
v8 still uses legacy Lava in Facilities Request workflow

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2781]
### Description

The Capture Notes action in the Open activity uses legacy Lava syntax

**Expected behavior:** 

New versions of Rock should eliminate Legacy Lava in core areas

**Actual behavior:** 

User form action references a WF attribute with legacy syntax, preventing the enabling of No Legacy mode without users manually fixing this up.

### Versions

* **Rock Version:** all

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in 3e21ed58.
