### ISSUE TITLE
Copies of Blank communication template cannot be deleted, deactivated or edited

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#2783]
### Description

Copies of Blank communication template cannot be deleted, deactivated or edited

### Steps to Reproduce

Click 'Copy' on the Blank template line.  This creates Copy of Blank communication template.
Attempt to delete or deactive this template.
Opening the template shows that the fields are all still locked like the basic Blank template.

**Expected behavior:** 
Should be able to delete and deactive.
Should be able to rename, and edit the basic fields.

**Actual behavior:** 
Can't delete, deactive or edit fields.
There's no way to get rid of the copies.

### Versions
Rock Version: Rock McKinley 7.2 (1.7.2.53)
Client Culture Setting: en-US

**Comment by cabal95** [comment]
Specifically, the `IsSystem` flag is being copied over.
