### ISSUE TITLE
v8 still uses legacy Lava in IT support workflow

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2784]
### Description
The _Capture Notes_ action in the _Open_ activity, _Notify Worker_ action in the _Assign Worker_ activity, _Enter Resolution_ action in the _Enter Resolution_ activity, and _Notify Requester_ action in the _Complete_ activity use legacy Lava syntax.

**Expected behavior:**

New versions of Rock should eliminate Legacy Lava in core areas

**Actual behavior:**

User Form and Email Send actions reference WF attributes with legacy syntax, preventing the enabling of No Legacy mode without users manually fixing this up.

### Versions
* **Rock Version:** all

**Comment by nairdo** [comment]
Thanks @JimMichael I found the remaining 6 cases the attribute 'Title' (w/key 'Summary') was being used in the Header column of the WorkflowActionForm table.  I created a data migration to fix these for v9.
