### ISSUE TITLE
v8 still uses legacy Lava in Profile Change Request workflow

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2785]
### Description

The _Capture Notes_ action in the _Open_ activity, _Enter Resolution_ action in the _Enter Resolution_ activity, and _Notify Requester_ in the _Complete_ action use legacy Lava syntax.

New versions of Rock should eliminate Legacy Lava in core areas

**Actual behavior:** 

User Form and Email Send actions reference WF attributes with legacy syntax, preventing the enabling of No Legacy mode without users manually fixing this up.

### Versions

* **Rock Version:** all

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in 3e21ed58.
