### ISSUE TITLE
v8 still uses legacy Lava in the Position Approval workflow

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2786]
### Description

The _HR Entry_ action in the _HR Entry_ activity, _Approval Entry_ action in the _Approval Process_ activity,  and _Email Requester_  / _Email HR_ actions in the _Approved_ / _Denied_ activities  use legacy Lava syntax.

**Expected behavior:** 

New versions of Rock should eliminate Legacy Lava in core areas.

**Actual behavior:** 

User Form and Email Send actions reference WF attributes with legacy syntax, preventing the enabling of No Legacy mode without users manually fixing this up. (don't forget subject fields in email forms... they are easy to miss!)

### Versions

* **Rock Version:** all

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in 3e21ed58.
