### ISSUE TITLE
Transaction List Campus Filter Issue

### ISSUE THREAD

**Issue by nateh777** [SparkDevNetwork/Rock#2787]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Issue with "Campus (of Batch)" and "Campus (of Account)" filters on Transaction list not working. Batches are not showing though they have campuses assigned to them. This was working in v6.10 prior to upgrade to v7. 

I tracked it down to this code change causing the issue: https://github.com/SparkDevNetwork/Rock/commit/3271a6948050ec8425856ca6e617c9400e88a5b5#diff-84907db2adfdeb4be9431a5f5822c3f8R1280
From what I can tell the code is loading a list of Batch Id's or Account Id's and then checking to see if Transaction Id's are in each respective list, but technically they aren't because they are different ids altogether.

### Steps to Reproduce

1. Add/Assign campus to batch with transactions
2. Attempt to find transactions with the "Campus (of Batch)" filter
3. Can't find transactions. Generally the list appears empty or completely unrelated data.

**Expected behavior:** 

Transaction list to be filtered down to batches with the assigned campus. Or accounts with that campus.

**Actual behavior:** 

Either no results or sporadic data, some valid, some not.

### Versions

* **Rock Version:** Rock McKinley 7.2 (1.7.2.53)
* **Client Culture Setting:** en-US

**Comment by timlem** [comment]
Here's a video showing details if helpful.

https://youtu.be/xWHaERwlSco

**Comment by azturner** [comment]
Thanks @timlem, the video is helpful. We'll take a look.
