### ISSUE TITLE
Person Note Retains "You - Private Note" Caption after private box unchecked

### ISSUE THREAD

**Issue by mwbellah** [SparkDevNetwork/Rock#2789]
### Description
Person note saved as private, then updated to uncheck private, not applying name of who created note

### Steps to Reproduce
1. Create person note, check private, save note 
1. edit note, uncheck private, save
1. note is no longer private, but retains the "You - Personal Note" caption

**Expected behavior:**

"You - Personal Note" caption replaced with name of user who created note

**Actual behavior:**

You - Personal Note caption retained instead of displaying user who created the note

### Versions
* **Rock Version:** 6.10,7.2
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Re-confirmed this is no longer happening in on the pre-alpha release demo server.
