### ISSUE TITLE
My Account page Birth Date and Age incorrectly formatted

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#2790]
### Description

The age/birthdate on the My Account page (http://www.organizationUrl/MyAccount) is incorrectly formatted.

![mydetailsbirthdate](https://user-images.githubusercontent.com/4658177/36331401-8ed721f8-13d2-11e8-9201-2605badf1f02.jpg)

### Steps to Reproduce
Logon to the external web site, click the down arrow next to User name in top right corner, select My Account.

**Expected behavior:** 

Should appear as: 17 yrs old  (birthdate)  

**Actual behavior:** 

Appears as : 17 yrs(birthdate old)  

### Versions

Rock Version: Rock McKinley 7.2 (1.7.2.53)
Client Culture Setting: en-NZ

**Comment by JimMichael** [comment]
I see the same on 7.3alpha with en-US.
