### ISSUE TITLE
Head cannot access lava variables in V7 email templates

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2794]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

In V7 the `lava-fields` variables cannot be accessed by `<style>` elements in the `<head>` because by default they're injected directly into the body. I'd propose moving the injection point to the beginning of the `<head>` and then wrapping the lava variables in a semantically correct `<noscript>` 

```
<noscript id="lava-fields">
    {% comment %} Lava Fields: Code-Generated from Template Editor {% endcomment %}
    {% assign logoWidth = '60' %}
    {% assign logoHeight = '60' %}
    {% assign pageBackgroundUrl = 'https://cdn.rawgit.com/garrettjohnson/rockmail/d098ddd3/assets/bg.jpg' %}
    {% assign pageBackgroundColor = '#3b4a69' %}
    {% assign textColor = '#999999' %}
    {% assign footerTextColor = '#ffffff' %}
  </noscript>
```

### Steps to Reproduce

1. Add lava variables to a email template.

**Expected behavior:** 

Add tag to a location where variables can be accessed by the entire document.

**Actual behavior:** 

Lava variables are added to the body.

### Versions

* **Rock Version:** 7.2  
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
➤ Mike Peterson commented:

[Jon Edmiston](https://app.asana.com/0/20866866924296/list) I have another Asana task that is the same as this [Issue 2794: Head cannot access lava variables in V7 email templates](https://app.asana.com/0/21565934390830/655782701769621)
