### ISSUE TITLE
Communication List membership on public Subscribe page over ridden in rare circumstances

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#2796]
### Description
This is a rare event, but I flag it anyway.  Maybe it is a simple fix.

Membership in communication lists can be corrupted on the public Subscribe page when new Communication List groups are added to the list of Public groups to be displayed, while the user is still on the page, and the user refreshes the page before navigating away.

**Expected behavior:**

Membership in Communication Lists should be displayed accurately on the Subscribe page, and any changes to groups should not affect membership in other groups.

**Actual behavior:**

If user deselects membership from a group, and a new Communication Group is added as Public, while the user is still on the page, and the user refreshes without leaving the page, then the membership in the new group is corrupted (e.g. turned off without user action).

### Steps to Reproduce
1. Add user to two communication list groups Group A and Group B as active members.  Group B is in the Public group of Communication Lists, Group A is not.  A and B names are in alphabetical order.
![comlist9](https://user-images.githubusercontent.com/4658177/36336530-68e29bba-13ed-11e8-9516-a1b4701fe24c.jpg)
1. User logs on and navigates to Subscribe page, and views their membership in group B.  Group B is showing as ticked.
![comlist6](https://user-images.githubusercontent.com/4658177/36336383-234df762-13ec-11e8-94c0-4b5db6a22ba3.jpg)
1. Untick membership in Group B.
![comlist4](https://user-images.githubusercontent.com/4658177/36336415-6f2373a6-13ec-11e8-8ce7-4a7bc3147a35.jpg)
1. In the backend, add Group A to the Public list of groups that will display on this page and save changes.
![comlist7](https://user-images.githubusercontent.com/4658177/36336433-9bdb0710-13ec-11e8-9616-499ee1e82681.jpg)
1. Return to the external page as the user and refresh the page.   Now Group A is showing as unticked, and Group B is showing on the next line as still ticked.  This is incorrect.  Group A should be ticked, and Group B should be unticked.  If user navigates away from the page at this point, the incorrect membership is saved.
![comlist8](https://user-images.githubusercontent.com/4658177/36336467-db4720d2-13ec-11e8-9477-b22eb5e8ec2b.jpg)

If you refresh between steps 3 and 4, then both lines will be show as unticked.
If you navigate away from the page between steps 3 and 4 things work correctly.

### Versions
Rock Version: Rock McKinley 7.2 (1.7.2.53)
Client Culture Setting: en-NZ

**Comment by cabal95** [comment]
@ElimAdmin I think you may be running into an issue I have seen in Firefox before (other browsers may have similar problems). When using the CTRL-R reload method, verses just clicking the URL bar and pressing enter, the browser will sometimes try to be helpful and override what the server told it to do and instead apply changes you made on the previous page. In general I think they do this so if you accidentally hit the reload button while filling out a form you don't lose everything you already typed in.

I cannot exactly replicate your issue, but if I use the CTRL-R method it will show the wrong check boxes checked (though my subscription hasn't actually changed). If I just go to the URL bar and hit enter again to do a "normal" page load, everything is correct.

If that is what you are seeing, I don't know if that is something we can fix as it's actually the browser causing the issue.

**Comment by chead4** [comment]
@ElimAdmin We are unable to recreate this issue.  This issue will be closed.
