### ISSUE TITLE
HTML Editor doesn't save content after it is pasted into code-editor view

### ISSUE THREAD

**Issue by jmorrissette** [SparkDevNetwork/Rock#2798]
### Description

The HTML Editor doesn't save content when it is pasted into CODE-editor view.  

### Steps to Reproduce

1. Create a new content channel item that uses the HTML editor mode as a default.
2. On the toolbar, switch to CODE editor view.
3. Paste some text from a your clipboard (I was copying/pasting html code)
4. Without switching back to the HTML Editor mode, SAVE your content channel item
5. Open the item you just created and the content will be missing.

The content does save if, after you paste your content into CODE editor view, you switch back to the HTML view mode [before] saving.  Essentially, nothing in CODE editor view is getting stored for save unless the end user remembers to switch back to the HTML view mode.  

I expect that whether I edit something in HTML or CODE view it would save my record without me remembering to switch back from CODE back to HTML view.

### Versions
* **Rock Version:** [ Rock McKinley 7.2]  
* **Client Culture Setting:** [Windows IIS Installation]

**Comment by cabal95** [comment]
Confirmed on prealpha and my own site. This only happens if the `Summary` Content Channel Item Attribute field type is set to `HTML`. On my own system it was by default `Memo` which did not cause the problem. Upon switching it to `HTML` I could replicate the problem.
