### ISSUE TITLE
Child content channels are not sortable (i.e. Podcast Series/ Podcast Messages)

### ISSUE THREAD

**Issue by jmorrissette** [SparkDevNetwork/Rock#2804]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The content channels module "sorting" functionality only works on the parent item, and not the children items.  The relevant example is the "Podcast Series" and "Podcast Messages" content channels.  If an end user doesn't create child content items in chronological order, you cannot sort them by StartDate (or Active Date).  Instead, the children items are only display by the CreatedDate and/or ContentItemID in the order they are entered into the database.  This issue is mentioned in numerous places on slack community.  To circumvent this issue, I create a LAVA SQL routine that grabs and then sorts the children Message Podcast items.  But this is a core feature and this isn't desirable for larger community IMHO.   

### Steps to Reproduce

1. Create a Podcast Series (parent) content channel item using the preconfigured Rock RMS channel.
2. Create a Podcast Message (child) content channel item as normal but set the date to (02/10/2018)
3. Create another Podcast Message (child) but set the date to (02/08/2018)
4. View the items on the front end website.  The second item with date 2/8 appears second in the enumerated list instead of first in the enumerated list.

**Expected behavior:** 

I would expect the podcast message (child) items to sort according to whatever criteria or filtering I set within the Content Channel module.  The filtering/sorting only works on the parent item (Podcast Series).

**Actual behavior:** 
See description above.  The child items does sort.

[What actually happened]
See description above.  The child items does sort.

### Versions

* **Rock Version:** [7.2]  
* **Client Culture Setting:** [En-US]

**Comment by edmistj** [comment]
Because of the way the data is retrieved the child items can not be sorted on the initial query. Also, it's likely that one would want to sort them in the different order than the parent items. We could add additional UI for sorting child items and then iterate over the parents to sort the children, but that would be difficult and would not be too performante.

Luckily this is easily don't within your lava ala:

```
{% assign childItems = item.ChildItems | Sort:'Id' %}
{% for message in childItems %}
...
{% endfor %}
```

See: https://www.rockrms.com/page/443#sort 
for more information on sorting.

**Comment by bengoshow** [comment]
@edmistj Is it possible to sort the ChildItems by their own Start ("Active") Date? I added some test sermons to the demo site and I don't see a way to reorganize them. Using Lava debug on my own site, it doesn't look like the StartDateTime field is exposed to Lava for Child Items.

**Comment by edmistj** [comment]
You'd have to sort it using Lava. StartDateTime should be a property on the child items.
