### ISSUE TITLE
Code editor doesn't apply word wrap

### ISSUE THREAD

**Issue by jmorrissette** [SparkDevNetwork/Rock#2806]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
When an end user pastes content into the HTML editor (i.e. using Word Import), the editor properly receives the [p]lorem epsum lorem epsum[/p] content.  But when you switch to the CODE editor view, the entire pasted document displays as one long string.  Essentially you have to horizontally scroll in the CODE editor view, and the CODE editor view doesn't utilize the more desirable vertical space for editing.  (i.e. it doesn't word wrap your document in code view).

1) Sentence 1 Sentence 2 Sentence 3 Sentence 4
[I have to scroll horizontally even if there are 1000 sentences)

vs.

1) Sentence 1
2) Sentence 2
3) Sentence 3
4) Sentence 4
[i.e. I can't scroll vertically perhaps 1000 lines or whatever to see/edit whole document]
etc.

### Steps to Reproduce

1. Create a Content Channel Item
2. Paste in a large document using the Word paste feature.  Or alternately, paste any large HTML coded document with number [p][/p] tags.
3. Switch to code editor view.  Observe that you have to scroll to the right to edit this document's html.  The vertical editor space isn't utilized at all.  

**Expected behavior:** 
If I were a programmer, I would want the current behavior to occur.  I would want to have to manually hit enter to force a new line of code.  I would not want each line of code to wrap necessarily.

If I were an end user, I would expect both the HTML/CODE Editor to behave like code editors on other major blogging or CMS platforms (i.e. Dotnetnuke).  I would expect the document tin Code Editor View to perhaps text wrap.  Or perhaps intuitively break elements ( Div, P, Span across the numbered lines) for ease of editing.

**Actual behavior:** 

All content appears on one line in EDITOR view mode.

### Versions

* **Rock Version:** [7.2]  
* **Client Culture Setting:** [En-Us]

**Comment by garrettjohnson** [comment]
@jmorrissette Just submitted a PR to add a word wrap by default. Since line breaks can effect the rendering of your HTML they aren't added by [Ace Editor](https://ace.c9.io/) which is the same code editor used by DotNetNuke.

**Comment by jmorrissette** [comment]
Is there any wisdom creating an html config option for admins to toggle these kind of features for optimal use in their organization?

**Comment by jmorrissette** [comment]
Also, I'm new to this GitHub, should I close this now?

**Comment by garrettjohnson** [comment]
@jmorrissette No need to close. I think setting word wrap is a reasonable default; most power users that would be bothered by the wrap are probably copy/pasting from a code editor.
