### ISSUE TITLE
Unable to refund ACH/CC Event Registration Transactions when batch is closed

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#2808]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

A user with access to process credit card or ACH refunds is unable to do so when the batch is closed. I confirmed with @edmistj  that this is not intended functionality

### Steps to Reproduce

1. Create a payment for an event registration
2. Close the associated batch
3. Load the financial transaction from the event registration and Refund button is not visibile

**Expected behavior:** 

I expected to be able to refund a transaction after the batch has been closed

**Actual behavior:** 

The Refund button was not available to me and I was unable to refund the transaction. I had to find the original batch and open it to refund the transaction

### Versions

* **Rock Version:** 6.10 I also confirmed on prealpha
* **Client Culture Setting:** en-us

**Comment by cabal95** [comment]
Duplicate  of #2243
