### ISSUE TITLE
Attribute Matrix Template with Required Attributes Not Working

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#2810]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When creating a Attribute Matrix Template that contains attributes that are required:

![image](https://user-images.githubusercontent.com/383807/36456076-50e27ba0-1660-11e8-9dc1-73268dc31c9e.png)

... when using that template for a Person Attribute, in edit mode, the attribute value is not being required allowing users to create empty attribute matrix records as seen here:

![image](https://user-images.githubusercontent.com/383807/36456113-912555f2-1660-11e8-9d85-f28823fcfc25.png)

This can become a big problem if the admin doesn't notice that they haven't attached the document (attribute value) and then they press save, thinking everything's dandy.

### Steps to Reproduce

1. Create Attribute Matrix Template with one or more required attributes
2. Create Person Attribute using the Matrix created in step 1
3. Try editing the person attribute values on the Extended Attributes tab of a Person's profile
4. Press the new (+) button to create a new matrix record/row but don't fill out the required values
5. Press Save, and then Press Save on the entire edit

**Expected behavior:** 

Expected the first Save operation to complain and not allow the user to create an empty row.

**Actual behavior:** 

Empty record/row is saved and no error/warning message is shown. 

> (I discussed this with Rock team lead on Asana who confirmed this is not correct.)

### Versions

* **Rock Version:** 7.2, current 7.4 hotfix branch, as well as 1.8.0.8, and 1.8.0.10
* **Client Culture Setting:** en-us

**Comment by ajfick** [comment]
This same issue applies if you were to use an Attribute Matrix as a field on an Event Registration, the field can be marked as required but you are able to just ignore it and continue.
