### ISSUE TITLE
[EN] Event Registration support for fee filtering

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2822]
### Description

Currently there isn't a way to filter by Fees within the Registrants list on RegistrationInstanceDetail:

<img width="1321" alt="screenshot 2018-02-23 08 43 52" src="https://user-images.githubusercontent.com/1210933/36597067-f5a181d8-1875-11e8-9366-4240df0ec9d6.png">

I have code to filter by fees but wanted to check for discussion before creating the PR.  If issue #2299 is high priority I can try to implement that functionality as well.

### Steps to Reproduce

1. Configure an event registration with Fees
2. Expect to filter the Registrants grid by those with Fees
3. No filter exists for the Fee column

### Proposed Change

<img width="459" alt="screenshot 2018-02-23 09 06 24" src="https://user-images.githubusercontent.com/1210933/36598099-14c9740a-1879-11e8-8724-1f2afc59e72b.png">

### Versions

* **Rock Version:** v7.2
* **Client Culture Setting:** en-us

**Comment by edmistj** [comment]
We’re currently working on a new tab that will allow for filtering and listing fees. I think this will cover the need.
