### ISSUE TITLE
Communication Recipient Fields Not Working with Dynamic Report Block 

### ISSUE THREAD

**Issue by mkinyon** [SparkDevNetwork/Rock#2823]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you build a report that uses the new Communication Recipient Field and then add that to a Dynamic Report block, the communication button doesn't work.
![image](https://user-images.githubusercontent.com/2349102/36602452-550b2e86-1875-11e8-989a-06ebfe720b98.png)

However, the communication button works fine on the Report Detail page.

### Steps to Reproduce

1. Create a report that uses a data view of children.
2. In the report, add a "Parent's Names" report field and set that as the Communication Recipient Field. 
3. Add the report to a Dynamic Report block.
4. Click the communication button.

**Expected behavior:** 

To see a new communication with the parents as the recipients.

**Actual behavior:** 

Get a warning that says "Grid has no recipients"
![image](https://user-images.githubusercontent.com/2349102/36602656-c765e5de-1875-11e8-938e-8f53180e0c6b.png)

### Versions

* **Rock Version:** 7.2
* **Client Culture Setting:** en-US

**Comment by azturner** [comment]
This was fixed here: https://github.com/SparkDevNetwork/Rock/commit/fda0551d12d3c8bf48f5911f8d29ec4cbf7a0530
