### ISSUE TITLE
Filter by PrimaryAliasId on /People REST endpoint fails

### ISSUE THREAD

**Issue by taylorbrooks** [SparkDevNetwork/Rock#2828]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
Both of these requests fail:
`http://rock.rocksolidchurchdemo.com/api/People?$select=Id, PrimaryAliasId`
`http://rock.rocksolidchurchdemo.com/api/People?$filter=PrimaryAliasId eq 1`

The error return is:
```json
{
  "Message": "The query specified in the URI is not valid. Could not find a property named 'PrimaryAliasId' on type 'Rock.Model.Person'."
}
```
![person](https://user-images.githubusercontent.com/117657/36694828-252c3574-1b05-11e8-8096-e56e0631f993.gif)
[Description of the bug or feature. Include screenshots if applicable.]

### Steps to Reproduce

1. Run the cURL command below
```curl
curl --request GET \
  --url 'http://rock.rocksolidchurchdemo.com/api/People?%24select=Id%2C%20PrimaryAliasId' \
  --cookie .ROCK=48E0C9392BC25C49090A5C446E32619AEC4A186010FAF7839FAB33AB9A5B841A939A4C93BFFABC22879C5499375E92BB7BA3A37372E8D22809344E61D7D784FE0E7DD28AB21C0D4C5DE0BE6DE35E159D1794CFC3CB960CC61BEF15F35B6999F8
```

**Expected behavior:** 

It should return the correct Person resource data should be returned.

**Actual behavior:** 

Errors

### Versions

* **Rock Version:** 7.2
* **Client Culture Setting:** ?

**Comment by cabal95** [comment]
@taylorbrooks I think you want the `api/People/GetByPersonAliasId/{personAliasId}` endpoint. That should let you retrieve a person object given their alias id.

The reason the PrimaryAliasId filter does not work is because it is a calculated field, which means it is not stored in the database directly, but determined once the Person object has been loaded into memory (along with it's associated PersonAlias records).

**Comment by taylorbrooks** [comment]
Confirmed. Closing.
