### ISSUE TITLE
Label Merge Field Lava Parent not working

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#2829]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The label merge fields are not printing parent name and phone number based on a lava call.  It was working v6.10 but on our staging environment it does not work.  The lava works in lava tester on our staging environment.

I also tried moving the lava to on line instead of broken out over multiple lines with returns just to make sure.

### Steps to Reproduce

1. Create/Use a Label merge field to print parent name and phone numbers on a checkin label
2.Check child in
3. Parent name and phone number are blank
Lava used on merge field
{%- assign parents = Person | Parents -%}
{%- for parent in parents -%}
{{ parent.NickName }} - {{ parent | PhoneNumber:'Mobile' }}
{%- endfor -%}

**Expected behavior:** 

Parent Name - Parent Phone Number Parent Name - Parent Phone Number

**Actual behavior:** 

Blank space on name tag

### Versions

* **Rock Version:** Rock McKinley 7.2 (1.7.2.53)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Reported with some more details in #2830.

Temporary fix is to use `{%- assign parents = Person.Id | Parents -%}`.
