### ISSUE TITLE
EventItemOccurrenceList.Lava file not providing results in Event Item Occurrence List Lava block

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#2833]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Adding a Calendar Item Occurrence List Lava block (~/Blocks/Event/EventItemOccurrenceListLava.ascx) to a page and providing an event, results in the title being displayed but no content

### Steps to Reproduce

1. Add the EventItemOccurrenceListLava block to a page and point it to an event with upcoming occurrences
2. Refresh the page. Note the title displays, but no events.

**Expected behavior:** 

Occurrence items should show up

**Actual behavior:** 

Occurrence items do not show up

### Versions

* **Rock Version:** 7.2  
* **Client Culture Setting:** EN-US

**Comment by mikejed** [comment]
It appears this block has been renamed to `Calendar Item Occurrence List Lava` now.

I've finally had a chance to test on 7.4, and the same issue is still presenting. When I configure an event, I *have* to choose a campus, and "all campuses" is not an option in the block settings. The output thus gives a blank line for every event that *should* be appearing, but there is no content.

The settings:
![image](https://user-images.githubusercontent.com/6932047/40955860-a596105c-6841-11e8-84a9-42268a0f7b19.png)

The result:
![image](https://user-images.githubusercontent.com/6932047/40955872-be7ec4d8-6841-11e8-8536-78f628b62ece.png)

So, I still can't say that my PR is the proper fix, but it does not appear to me that this issue has been fixed.

**Comment by mikejed** [comment]
Additionally, with further investigations, I'm finding that setting events to a campus selected in the list block settings brings to light a different issue.

When changing the campus on two test events from "All" to a specific campus:
![image](https://user-images.githubusercontent.com/6932047/40955963-69d69306-6842-11e8-8b74-8a43c39e870e.png)

The output now lists the campus name, not the event name
![image](https://user-images.githubusercontent.com/6932047/40955991-9055da32-6842-11e8-96b0-9a1adbd49492.png)

**Comment by ethan-sparkdevnetwork** [comment]
I have made the Campuses block setting optional in "Event Item Occurrence List Lava", if campuses are not selected then it means "All". MikeDPeterson had already done the work we just needed to make the field optional. (Fixes #2833)

I was not able to reproduce the second issue no matter what I did with campus settings in the list and the event occurrence.
