### ISSUE TITLE
Workflow action buttons are broken... again :)

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2834]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

It seems those darn action buttons when embedded in the e-mail are broken again. The url in the default template is written to include an `&ActionId={{ Action.Id }}` so that the Workflow Entry block knows exactly which action form to trigger.

Makes sense.

Except Action.Id will always be 0 because it hasn't been saved to database yet.  Thus causing `&ActionId=0` to be a static value, thus causing the workflow entry block to never find the right action and resulting in an error.

### Steps to Reproduce

1. Create a workflow with a user entry form.
2. Populate the form with a few buttons
3. Run the workflow
4. Try to click the button and notice &ActionId=0

**Expected behavior:** 

Buttons should work. Not sure how to make this work correctly though since the action hasn't been saved and thus it's Id is not yet available.

**Actual behavior:** 

We borked it.

### Versions

* **Rock Version:** 7.2
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
This can be solved in the current code by adding a "Workflow Persist" action before the "User Entry Form".

**Comment by ethan-sparkdevnetwork** [comment]
To make things easier I added WorkflowService.PersistImmediately(). This will save the workflow in the same  manner as if the "Workflow Persist" action was run. I added a check in the user form to run this method if the workflow type is set to persist.

**Comment by cabal95** [comment]
@ethan-sparkdevnetwork Does that mean this will only work if the workflow type is set to persist immediatly, or will this still force a persist/save if the workflow type is _not_ set to persist immediately?

**Comment by ethan-sparkdevnetwork** [comment]
@cabal95 The fix will force a workflow to persist immediately before creating an email if the workflow type is set to automatically persist.

**Comment by cabal95** [comment]
>The fix will force a workflow to persist immediately before creating an email **if the workflow type is set to automatically persist.**

I guess I'm saying, the bug still exists then. IF the workflow type is set to NOT persist automatically, then the User Entry Form will not work correctly and send out links that don't work.

I'm of the opinion that if the workflow action requires the workflow to persist to function correctly it should automatically persist. Meaning if the User Entry Form is set to send an e-mail then it should always persist the workflow, regardless of the "automatically persist" setting. If that is not how we want it to function then we need to update documentation to tell people that they need to set the workflow to automatically persist to use this action.

**Comment by ethan-sparkdevnetwork** [comment]
We have taken Hazelbaker's solution. The workflow will persist immediately just prior to sending an email regardless of the automatically persist setting for the workflow.
