### ISSUE TITLE
Registration Payments - Incorrect Email on Payment Info

### ISSUE THREAD

**Issue by taylorbrooks** [SparkDevNetwork/Rock#2838]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
When registering for a paid event, there is an input field for "confirmation email". That email is sent to the gateway along with the First/Last Name from the card.

We are seeing unexpected consequences as a result.

<img width="1219" alt="registration-entry" src="https://user-images.githubusercontent.com/117657/36813980-dd9812d0-1c9b-11e8-9658-ff15d2329061.png">

This is where is happens in the code:
https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/RegistrationEntry.ascx.cs#L3005
<img width="1053" alt="screen shot 2018-02-28 at 3 32 53 pm" src="https://user-images.githubusercontent.com/117657/36814280-add06b32-1c9c-11e8-9587-b8cb96cbd211.png">

Perhaps a simple label change would fix this.

The text says "This Registration Was Completed By" and it says "Send Confirmation Emails To", those can be conflicting people and should be clarified.

Perhaps it's better for the text to say "Send Payment Email To"

**Comment by edmistj** [comment]
I think the primary use for the email provided for event communication (confirmation, reminders, wait lists etc). I think changing it to describe payment would negate the context. 

What is are the unexpected consequences?

**Comment by taylorbrooks** [comment]
Crossing wires. Cards are being added to the wrong person's accounts.

The `Charge` method on Simple Donation's gateway makes a `POST` request to our `/charges` endpoint with this as the body:
```txt
{
  "type": "event",
  "payment_source_id": "token_12345",
  "amount": 10000,           // amount in pennies
  "person": {
    "id": "person_12345",    // used when a person is logged in
    "first_name": "Taylor",
    "last_name": "Brooks",
    "email": "taylor@simpledonation.com"
  }
}
```
We use email as a unique identifier, when a request comes through we lookup that person by email in our system then add the payment source to that person.

**Comment by edmistj** [comment]
Using email as a unique identifier probably isn't the best option when you're integrating with other systems. In Rock it's common for the same email to be used for multiple people and they change quite often. 

I'm not sure how to proceed with this request as we can't change the context of the label to make it 'payment' nor do I think adding another email field is a good solution. 

You might consider adding some sort of integration key for the systems that you link to. In that case a person's PersonAliasId would be a good field to use for Rock.

**Comment by taylorbrooks** [comment]
I'm using email as a unique identifier because that's all I've got -- unless I'm completely missing something.

Whenever `gateway.Charge` is called from registration entry or transaction entry, we only have the `PaymentInfo` object to work with.

https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/RegistrationEntry.ascx.cs#L2765
https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Finance/TransactionEntry.ascx.cs#L2589

**Comment by dcs619** [comment]
@taylorbrooks Not sure I follow.  [PaymentInfo](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Financial/PaymentInfo.cs#L46) includes FirstName, LastName, Email, Phone, and Address so you would probably use a combo of those as a unique identifier.  Rock uses FirstName + LastName + Email to determine uniqueness for account registration.

**Comment by arranf** [comment]
@taylorbrooks I'm going to close this as it looks like there are no Rock changes to be made here.

**Comment by taylorbrooks** [comment]
@arranf I still think it is weird to send the gateway an email that has no association with the payment method details. Seems wrong and it should be fixed.
