### ISSUE TITLE
HTML Content Disappears

### ISSUE THREAD

**Issue by taylorbrooks** [SparkDevNetwork/Rock#2840]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When you set the ending "Display From" date to a past date, it clears out the WYSIWYG and deletes the content.

![block](https://user-images.githubusercontent.com/117657/36875811-5bb9a238-1d77-11e8-9ed5-0f7274514537.gif)

### Steps to Reproduce

1. Create a block with the type as HTML Content
2. Write text in the WYSIWYG
3. Set the Ending date to a date in the past
4. Save
5. Open up the editor and voila -- no text!

**Expected behavior:** 

I would expect the content of the WYSIWYG to be saved, but the block to be hidden from the screen

**Actual behavior:** 

No content.

### Versions

* **Rock Version:** 7.2

**Comment by taylorbrooks** [comment]
could be related to #2756

**Comment by MikeDPeterson** [comment]
still investigating, but confirmed that this is not related to #2756
