### ISSUE TITLE
Invalid path in metrics

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#2846]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

One of the instances I work with has been getting an `Illegal Characters in Path` error since about when we updated to v7.2. The paths are all similar to `/api/MetricValues/GetSeriesPartitionName/1/16|1758` so I assume it's the pipe causing the issue. I'm not calling the API myself anywhere, but we have some graphs based on metrics on the internal home page - it could be that, but a vast majority of the error source pages are the stock check-in pages.

### Steps to Reproduce

~Unknown, sorry~
_Edit: Found to be reproducible, see below_

**Expected behavior:** 

No exceptions 

**Actual behavior:** 

Exceptions are generated with nearly every page load. Not from my computer, which makes it difficult to track down, but it sounds like mostly from the  owners mobile devices (and sometimes from his desktop as well)

### Versions

* **Rock Version:** 7.2-7.3
* **Client Culture Setting:** EN-US

**Comment by cabal95** [comment]
Hmm. You mention Rock 7.3, is this for sure verified on 7.3?  I just tried the following URL on the demo site (currently 7.3) and it works:
`http://rock.rocksolidchurchdemo.com/api/MetricValues/GetSeriesPartitionName/1/16|1758`
`http://prealpha.rocksolidchurchdemo.com/api/MetricValues/GetSeriesPartitionName/1/16|1758`

(Note: these return "nil" since we don't have a matching entity, but I tried with ones that exist and they return valid values).

Can you post the `httpRuntime` directive line from you web.config? There is an option in there to specify which characters to now allow. My system is using the defaults but I am wondering if yours has overridden that list.

**Comment by mikejed** [comment]
Definitely still happening on 7.3
`<httpRuntime targetFramework="4.5.2" requestValidationMode="4.5" requestValidationType="Rock.Web.RequestValidator" relaxedUrlToFileSystemMapping="true" maxRequestLength="102400" />`

**Comment by mikejed** [comment]
I've been able to reproduce this on prealpha. It is appearing to be an iOS issue, for some reason.

Steps to reproduce:
1) Verify there is a metric with (presumably) more than one value entered
2) Add a LineChartDashboardWidget.ascx block to the main internal page
3) Log in to the internal site using an iOS device

**Comment by cabal95** [comment]
Confirmed on my phone as well. Strangely enough, when I hit the URL on my iPhone it takes about 30 seconds before it errors. When I airdrop that URL to my desktop browser (meaning it is the exact same URL for sure) it doesn't error AND the response comes back instantly. Tried a couple times to verify it wasn't a caching issue.

**Comment by MikeDPeterson** [comment]
@mikejed @cabal95 I changed it to do a POST instead of GET which should avoid the problem of having pipes in the URL.
