### ISSUE TITLE
Update replaced custom logo in CheckinBlueCrystal theme

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#2851]
### Prerequisites
* Put an X between the brackets on this line if you have done all of the following:
    * [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
        _(unable to do so; no filesystem access)_
    * [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The _Checking Out Check-In_ documentation notes that the CheckinBlueCrystal theme has a Rock logo file that is designed to be replaced with the church's logo, "with one simple file change". But upgrading to ~v7~ _(edit: some version of 6.x later than 6.8)_ replaced the file with the stock default again. Churches should probably be advised how to change the logo by pointing to a different file in the CSS if that's easy, or a backup of the existing file should be made in migrations before overwriting it with a new version.

### Steps to Reproduce

1. Edit or replace ~\Themes\CheckinBlueCrystal\Assets\Images\logo.png and logo@2x.png under <6.8
2. Update Rock to 6.9 or v7 (unknown when the change actually happened)
3. Observe the files are overwritten with the original versions

**Expected behavior:** 

Custom logo to be retained

**Actual behavior:** 

Files are overwritten

### Versions

* **Rock Version:** 7.0  
* **Client Culture Setting:** EN-US

_edit: I went looking for the change after I posted this. It's very probably https://github.com/SparkDevNetwork/Rock/commit/7141e400d580ae70b318061657a0f7b5987f00f8 which wasn't a tweak to this theme per-se, but an en-masse edit of all graphic assets. So perhaps this is more of a "discussion" than a "bug" - is there a better process we can advise churches to utilize to change out this asset, rather than overwriting a stock file (which, after all, is generally ill-advised)? After all, changing the CSS would *also* be a change to a stock file and susceptible to overwriting_

**Comment by edmistj** [comment]
You're correct these files were overwritten on the v7 update. I'll update our build documentation to ensure this doesn't happen again.
