### ISSUE TITLE
[EN] Display Parent Rosters in Group Toolbox for Children's Groups

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2854]
### Description
I have code that I can PR and tweak for core that adds support for Children's Groups.  Group leaders can access parental information, not just information about the child they lead.

The "Parent Roster" tab and "Email Parents" button will display when the following criteria are met:
1) Enable Parent Support is turned on (turned off by default)
2) Parent Roster page block setting is set 
3) One or more of the group members are designated as a Child in their Family group
4) One or more of those Children have a designated Adult in their Family group.  If the Child's Family does not have an Adult, that Child's name will not display on the Parent Roster tab.

Attached are screenshots of the proposed functionality.  This is sponsored by [Fellowship Greenville ](https://www.fellowshipgreenville.org/).

New "Parents Roster" tab and "Email Parents" button on the Group Toolbox page:

![screenshot 2018-03-08 09 48 38](https://user-images.githubusercontent.com/1210933/37157979-38962394-22b8-11e8-9409-8575490c2bad.png)

New "Parents Roster" tab displaying a basic list of parents and their contact information (nothing can be edited):

![screenshot 2018-03-08 09 49 05](https://user-images.githubusercontent.com/1210933/37157978-38888144-22b8-11e8-9ae5-b6cdbd305324.png)

New GroupDetailLava.ascx.cs block settings:

![screenshot 2018-03-08 09 55 40](https://user-images.githubusercontent.com/1210933/37157977-3879c41a-22b8-11e8-898d-51b413e91360.png)

The Parent Roster page is a copy of External Site\Support Pages\My Account\Group Toolbox as a new page:

![screenshot 2018-03-13 12 56 08](https://user-images.githubusercontent.com/1210933/37357158-0d00f7cc-26be-11e8-9b3b-3b2e0895b051.png)

This has to be a separate page in order for the Lava to correctly calculate the content display.

### Affected Files
* Blocks\Groups\GroupDetailLava.ascx.cs
* Stark\Assets\Lava\GroupDetail.lava

### Versions
* **Rock Version:** v7.3
* **Client Culture Setting:** en-us

**Comment by edmistj** [comment]
Looks good based on showing if "Enabled Parent Support" = true and any group member is a child. 

v8 has an age classification on the Person model that tells you if they are a child. It would be very efficient to use that.

**Comment by dcs619** [comment]
@edmistj I thought about targeting a global Age ( <= 18), but someone could lead a small group of special needs "children" that are over 18.  I'll submit a PR and tag you for review if I need to use Person.AgeClassification.

**Comment by dcs619** [comment]
@edmistj I clarified the description with a list of criteria.  I targeted Family.ChildRole instead of Person.AgeClassification in case there was a Special Needs group of "children" over 18.

**Comment by edmistj** [comment]
@dcs619 for consistency sake I think we should use Person.AgeClassification. We can add an override to "LockIndividualAsChild" from the person profile page. I'll make an internal task for adding that logic if you update the PR to use Age Classification.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
