### ISSUE TITLE
[EN] Add Member ability on Group Attendance Detail Block

### ISSUE THREAD

**Issue by nateh777** [SparkDevNetwork/Rock#2857]
## Description
I have code for a PR that adds a new button for "Adding a Member" from the group attendance detail block, not just an attendee as is currently built in.

Attached are screenshots of the proposed functionality. This is sponsored by [River Valley Church](https://www.rivervalley.org/).

New "+ Add Member" button on the attendance detail page:

screenshot
![image](https://user-images.githubusercontent.com/2990519/37169769-14b219d4-22c6-11e8-86de-c3b390d0163f.png)

New GroupAttendanceDetail.ascx.cs block settings:

![image](https://user-images.githubusercontent.com/2990519/37169731-f180014c-22c5-11e8-8d7c-bb6d646b9428.png)

Add Member Function is a copy of ability from the GroupDetailLava block:

![image](https://user-images.githubusercontent.com/2990519/37169818-3f21185a-22c6-11e8-90f1-dc9dea9de6e2.png)

If you set the _Group Add Member Page_ block setting it will instead navigate to that page with the `GroupId`, `GroupName` and a `returnUrl` saving the attendance before navigating to that other page.

## Affected Files

- Blocks\Groups\GroupAttendanceDetail.ascx
- Blocks\Groups\GroupAttendanceDetail.ascx.cs

**Versions**
**Rock Version:** v7.3
**Client Culture Setting:** en-us

**Comment by edmistj** [comment]
@nateh777 I think we'd prefer that an additional block setting was added entitled: "Add Person As" with the options of "Attendee" or "Group Member". 

Based on what they picked the label would change to "Add Attendee" or "Add Group Member".

If that doesn't fill the use case perhaps adding a checkbox next to the "Add Attendee" that would say "Add as Group Member".

**Comment by nateh777** [comment]
@edmistj That sounds good as long as the main function can stay the same I think the first idea will fill the use case just fine. I think I will still leave the different buttons/functions and just display or hide them based on the setting. I should have shown them together in a screenshot as well but I don't think many people will use them that way. Though I will need to confirm that with the sponsor.

**Comment by edmistj** [comment]
The screenshots you show have the 'Add Member' working different. It goes to a member add screen. Seems like that should just add the person to the group without the additional screen using the default group role. That would better match the pattern of Rock.

**Comment by edmistj** [comment]
OK, but let's not let them add both an Attendee and Member at the same time. That would be pretty confusing and the UI controls don't match. Having a checkbox to "Add as Group Member" when adding an Attendee would be ok though.

**Comment by nateh777** [comment]
I'll post updated screenshot(s) of different modes here shortly. If it doesn't work how you want then switching to a checkbox shouldn't be an issue.

**Comment by nateh777** [comment]
Add as Attendee:
![image](https://user-images.githubusercontent.com/2990519/37179416-c3db1e58-22e2-11e8-8acb-94b9125e0fee.png)

Add As Group Member:
![image](https://user-images.githubusercontent.com/2990519/37179593-5371eb32-22e3-11e8-9501-34d5ed4e590f.png)

Add Group Member page set:
![image](https://user-images.githubusercontent.com/2990519/37179642-88c13036-22e3-11e8-8ffa-bff7aa069465.png)

Block settings:
![image](https://user-images.githubusercontent.com/2990519/37179668-9ee82fa4-22e3-11e8-8e44-9e8c66621f71.png)

If you want me to go with the checkbox instead can you point me to an example by chance so I can match the pattern of rock with a picker and checkbox with each other?

**Comment by edmistj** [comment]
What would it look like if both Add Attendee AND Add Member was selected with the Add Member Page configured.

**Comment by nateh777** [comment]
I made it a single select so you could only be in one of the 3 modes above, I did miscalculate adding a linked page setting technically overrides the "Add Person As" setting and only honors it. 

So for screenshots settings were as follows:

**Screenshot 1:** 
- _Allow Adding Person:_ Yes
- _Add Person As:_ Attendee
- _Group Member Add Page:_ empty

**Screenshot 2:** 
- _Allow Adding Person:_ Yes
- _Add Person As:_ Group Member
- _Group Member Add Page:_ empty

**Screenshot 3:** 
- _Allow Adding Person:_ Yes
- _Add Person As:_ Attendee or Group Member
- _Group Member Add Page:_ set to sub page

I could have it honor _Attendee_ and _Group Member Add Page_ being set with adding both buttons but I thought you didn't like them both being on the page?

**Comment by nateh777** [comment]
Updated to honor Add Person As "Attendee" and have a Group Member Add Page set and it will appear as such:
![image](https://user-images.githubusercontent.com/2990519/37235582-ef71fee4-23bc-11e8-88e7-b22aa39a7dbb.png)

It will still only appear as the single button if Add Person as "Group Member" and Group Member Add Page is set. Submitting PR, if you still want it different let me know and I'll tweak again.

**Comment by edmistj** [comment]
Closing this as there's now a PR for this.
