### ISSUE TITLE
SMS Send workflow action fails with a multi-member group as the recipient

### ISSUE THREAD

**Issue by ricsrock** [SparkDevNetwork/Rock#2858]
### Description

The SMS Send Workflow Action fails when the Recipient is set to a group that has more than one member.

### Steps to Reproduce

1. Create a workflow with the following attributes: To Group (set the default to a group with multiple members), SMS Message (a memo with some text)
2. Create an activity with a single action (SMS Send) and choose a From Number, set the recipient to "To Group", and set the message to "SMS Message"
3. Run the Workflow

**Expected behavior:** 
Should send a text message to each member of the group.

**Actual behavior:** 

<img width="1323" alt="screenshot 2018-03-09 10 25 59" src="https://user-images.githubusercontent.com/99489/37217856-52f1415c-2384-11e8-9268-c82399025aa0.png">

### Versions

![image](https://user-images.githubusercontent.com/99489/37217903-7b9e7f0c-2384-11e8-8efb-89fc8b7bfed6.png)

**Comment by cabal95** [comment]
Gah, sorry finally found the pre-existing issue. This should be fixed in 7.3.  reference #2747.

**Comment by JimMichael** [comment]
Gah, I searched for "SMS group" and all sorts of permutations and never got a hit (because I thought there WAS an existing issue), but never tried "SendSMS" so assumed I imagined it :-/
