### ISSUE TITLE
Emailing from Person Profile does not populate Simple Email recipient list.

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2859]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Clicking the email link on the Person Profile page takes you to the Simple Email editor, but the person has not been added as a recipient. Verified on prealpha.

### Steps to Reproduce

1. Go to a person
2. Click the email link
3. You end up on the simple editor for a new communication, but there are no recipients.

**Expected behavior:** 

Person/email you click from would be populated as a recipient.

**Actual behavior:** 

Communication contains no recipient, even though ?person=xxx is being passed. Note that if you edit the Bio block to point at the New Communication wizard instead of the Simple Communication page, the person IS populated as a recipient as expected.

### Versions

* **Rock Version:** 7.2+

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/1f885cd9d3817017b74b6582ee7c2a5c08e6f293
