### ISSUE TITLE
Enhancement Request: Connection Opportunity Sign-up Block

### ISSUE THREAD

**Issue by rutledgek** [SparkDevNetwork/Rock#2860]
Add a field in the block settings to choose a specific Opportunity for the block context.  The current workaround is a page redirect that detects the presence of the page parameter and redirects back to the page with the OpportunityId in the parameter.

**Comment by edmistj** [comment]
So if I understand this correctly you'd like the ability to hard code the page for a specific opportunity. Correct?

**Comment by rutledgek** [comment]
Yes.  Utilizing connections rather than having to create a workflow that basically replicated connections. Targeting a specific opportunity on the page instead of relying on the page parameter

**Comment by rutledgek** [comment]
Hey, thanks!
