### ISSUE TITLE
[EN] Prayer Requests solicit email address but never expose it

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2863]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The public-facing Prayer Request Entry block asks for a person's email, but never exposes this email in the internal UI, which means it's impossible to respond back to the sender. IF the person entering the request happens to be logged in, I believe it associates the prayer request Requested By attribute with the submitter (and you can then look up that person in Rock to get their email), but if the person is NOT logged in (the majority of the use-case for us), the email is captured in the form and completely hidden from the end user in any of the prayer request internal blocks.

### Steps to Reproduce

1. Enter a prayer request on the public site, including email
2. Observe on the internal Prayer Request Detail page that the email is not exposed anywhere
3. We KNOW it's being captured, though, because if you try to add an attribute to the prayer request with 'Email' as the key, it changes your new key to 'Email1'. 

**Expected behavior:** 

The internal prayer request block would expose the submitter's email address either as a mailto: or New Communication link, so they can be communicated-with.

**Actual behavior:** 

You cannot contact a person who has submitted a prayer request because you are never shown their email address. If I'm completely missing the point of the email functionality as it related to the prayer request system, please educate me and then disregard.

### Versions

* **Rock Version:** All
![image](https://user-images.githubusercontent.com/3903408/37307331-9a561cf8-2608-11e8-89c8-17b87cb0ce6b.png)

**Comment by cabal95** [comment]
I'd be tempted to call this a bug, but I'll let Jon or somebody else elevate to bug status if they want.

**Comment by JimMichael** [comment]
Thanks! Which version will this fix likely show up in?

**Comment by edmistj** [comment]
v7.4
