### ISSUE TITLE
Add Parameterized SQL support to Lava and Workflows

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2866]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Currently, the `{% sql %}` command in Lava and the workflow action `SQL Run` do not support SQL parameters. This means we must manually sanitize the data before providing it. Using Parameterized SQL statements is general best practice so I think it would be smart to add support for these.

Willing to submit a PR for this.

### Lava Implementation

The Lava implementation would be fairly straight forward. Syntax would be:

```SQL
{% sql return:'mylist' safe:'{{ unsafeVariable }}' %}
    SELECT * FROM [Person] WHERE [LastName] = @safe
{% endsql %}
```

The sql command already parses the line for parameters so this would be a very minor change to implement. However, it currently resolves merge fields on the entire line. In the above example, this would cause a problem if `unsafeVariable` contained a single quote because the regex parser would stop at the second single quote instead of the third (final) single quote.

The change would be to move the merge field resolution to _after_ the regex matching and we have extracted the value for that parameter name. This should have little, if any, impact to the end-user as it would still work as expected and documented to them.

### Workflow Implementation

Suggesting that we add a KeyValueList field to the `SQL Run` action that resolves Lava fields on the values before adding them to a dictionary of parameters to pass to the SQL statement.

<img alt="workflowsample" src="https://user-images.githubusercontent.com/1119863/37357318-5dea79b0-26a5-11e8-86a0-eb68d6220e2d.png">

### Versions

* **Rock Version:** 8.0
* **Client Culture Setting:** klingon-us

**Comment by edmistj** [comment]
Sounds good. Can you make this 2 different PRs though?
