### ISSUE TITLE
CategoryTreeView prevents scrolling on touch screens

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#2867]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using a touch screen to navigate Rock, the user is not able to scroll up and down on the page if attempting to do so by touching the CategoryTreeView control. This becomes problematic when the expanded list of categories is larger than the screen, making it impossible to scroll to the bottom of the list of categories to reach the desired page.

On my phone, I do have a small area to the far right of the screen where I can still scroll, but this is not intuitive and could be because the category names are small; if they were longer, or my phone was lower resolution, then I would not have the option to scroll at all.

I have tested on two different Android phones and an iPhone, and experienced the same behavior on all three.

### Steps to Reproduce

1. Open the Event Registration page on a smartphone
2. Expand the Category tree
3. Put your finger on the tree and try scrolling the page up and down

**Expected behavior:** 

The page scrolls as normal

**Actual behavior:** 

The page does not move.

### Versions

* **Rock Version:** Rock McKinley 7.3 (1.7.3.55)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
While not related in that it is the same issue, these related issues should be re-verified after this is fixed to make sure we don't create a regression: #1062, #1731.
