### ISSUE TITLE
[EN] SMS - Add option to receive SMS response via email

### ISSUE THREAD

**Issue by randyjreed** [SparkDevNetwork/Rock#2876]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers ](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When sending SMS messages the replies are sent to the cell phone number of a staff member.  Often this has been a Part Time staff member and we do not want them to be receiving these messages after hours. The option to specify the destination to be either email or sms would resolve this. I understand that if they need to reply they would need to initiate a new SMS message via Rock.

Thank you!

**Comment by cabal95** [comment]
I think you could do this for now by tying the Twilio number to a Text-To-Workflow instead and using a workflow action to send an e-mail to them. But I think this would be a good checkbox option to simplify the process for users.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
