### ISSUE TITLE
Prevent noGood Security Code Strings from being contained in valid Security Codes

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2877]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

So if you're using Numeric-only nametags, and you have a paging system that doesn't allow leading 0's then when you page a kid with the code 0666, it doesn't come across right :/

@lee_peterson from Slack has this issue.  And they use sequential codes, so they get this issue frequently.  (I'm filing this on his behalf)

The way I _thought_ the security code rejection worked, and how I'd recommend it, is to not allow any security code that contains a noGood string.

@cabal95 Can probably give more context than I can 🙃 

### Versions

* **Rock Version:** 6.10  
* **Client Culture Setting:** en-us

**Comment by cabal95** [comment]
Adding a tiny bit more context, it looked like the alphanumeric matching does sub-string search while the numeric only matching does full-string match.

I'm marking this as a bug since the matching is not consistent between the different algorithms.

**Comment by NuclearTacos** [comment]
Sounds good to me!  I wasn't 100% sure on the details and I didn't want to start calling things bugs so flippantly 😉

**Comment by nairdo** [comment]
Are we talking about this code when you say "security code rejection"? https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/AttendanceCodeService.Partial.cs#L136

And are you saying their problem is that the four digit numeric code has a leading zero?

**Comment by cabal95** [comment]
@nairdo correct on both counts. In their case they are I believe doing sequential 4 digit so they routinely hit “0666”. But even with random 4 digit numeric it should be possible to hit a random “0666”. Or 1666, 6660, etc.

**Comment by lpeterson1** [comment]
![img_2869](https://user-images.githubusercontent.com/37701239/38461994-fe5383e2-3a9b-11e8-92b6-0c1c22a4b48f.JPG)
Thought I'd mention this again. It is true that we hit 0666 twice a weekend, and since our pager displays don't support a leading zero we occasionally have to page 666.

Our internal systems prevent us from using random codes, which I suppose would lower the odds of this code being assigned.

I think that 0666 is the only code that concerns us. I don't believe that other combinations that include 666 (1666, 6661, etc.) would be a concern from our perspective.
