### ISSUE TITLE
Statement generator always includes all accounts

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2881]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The 7.0 statement generator always includes all accounts on printed statements, even when only one is selected.

### Steps to Reproduce

1. Select one tax deductible account on "Step 4: Account Selection" in v7.0 of the Statement Generator
2. Run report

**Expected behavior:** 

Only return transactions for the selected account.

**Actual behavior:** 

All giving to tax deductible accounts are included

### Versions

* **Rock Version:** 7.2  
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Can you confirm you're using the latest external app from the store. There have been several updates to the app in the last 30-60 days.

**Comment by garrettjohnson** [comment]
Appears to be, downloaded from `http://storage.rockrms.com/externalapplications/sparkdevnetwork/statementgenerator/1.7.0/statementgenerator.exe` on Tuesday.

**Comment by MikeDPeterson** [comment]
@garrettjohnson So, looking at the code, this could happen if they gave to 'Fund A, B, and C' in the same transaction, but only wanted to see 'Fund A'.  Since Fund A was selected, it would include any transactions that involved Fund A, but would also show B and C since they were in the same transaction (which is a bug).  Could you confirm that is what you are seeing?

**Comment by garrettjohnson** [comment]
@MikeDPeterson That appears to be the case, multiple funds in a single transaction.

**Comment by MikeDPeterson** [comment]
Note that this fix only requires that Rock be updated to v7.4. The statement generator app doesn't need to be updated.
