### ISSUE TITLE
Group Attendance Reminder Link Broken

### ISSUE THREAD

**Issue by ajfick** [SparkDevNetwork/Rock#2884]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

(v6.10) Group Attendance reminders email link takes users to a page with an error saying "Sorry
You're not authorized to update the attendance for the selected group." incorrectly. User can still navigate to group under "Groups" in My account page and create attendance.

![screen shot 2018-03-18 at 12 02 17 pm](https://user-images.githubusercontent.com/19314419/37567937-81cb327c-2aa4-11e8-89b9-7fb7ad539092.png)

![screen shot 2018-03-18 at 12 02 41 pm](https://user-images.githubusercontent.com/19314419/37567942-8c6f1cde-2aa4-11e8-961a-7abbe01e20a8.png)

After the update to version 7.3 the Group leader is now immediately taken to the login page with a message that reads "The login token you provided is no longer valid. Please login below.". After successfully logging in, they are then shown the "Sorry, You're not authorized to update the attendance for the selected group" error. 

![screen shot 2018-03-18 at 12 02 33 pm](https://user-images.githubusercontent.com/19314419/37567939-84d8dc94-2aa4-11e8-8a97-9e4dac1175c7.png)

### Steps to Reproduce

1. Occurs any time a Group Attendance Reminder is sent. 

**Expected behavior:** 

Group leader should receive the Group Attendance Reminder Email, click the given link, and be taken directly to the attendance occurrence. 

**Actual behavior:** 

Group leader receives the Group Attendance Reminder Email, clicks the link, and is taken to a page with an error message claiming that they are not authorized to add attendance. They then need to navigate to the Group manually to add attendance. 

### Versions

* **Rock Version:**  6.10 & 7.3  
* **Client Culture Setting:** ?

**Comment by edmistj** [comment]
@ajfick were you able to confirm that this was being caused by the IIS redirect rule?

**Comment by ajfick** [comment]
@edmistj I believe it was.
