### ISSUE TITLE
 V7 when a template is selected, it clears the "from name", "from address", and "reply to address".

### ISSUE THREAD

**Issue by watermarkgeek** [SparkDevNetwork/Rock#2888]
Prerequisites
[X]  Put an X between the brackets on this line if you have done all of the following:
Can you reproduce the problem on a fresh install or the demo site?
Did you include your Rock version number and client culture setting?
Did you perform a cursory search to see if your bug or enhancement is already reported?
Description
When a template is selected from the simple editor, the "from name", "from address" and "reply to address" are cleared out

Expected behavior:

The "from" information is prepopulated when the form loads, and should stay the same after the template is created

Actual behavior:

It clears the info

Versions
Rock Version: 7.0.3
Client Culture Setting: en-US

**Comment by edmistj** [comment]
This happens as the Template defines not only the Message Body, but also the From Fields, Subject etc. I'd guess your Template does not define these fields so it wipes out what you have. 

We could probably change this to say if there is data entered AND the template doesn't have any content in these fields then leave the existing content.

In some cases 'no value' is a value and should be treated that way, in other use cases it's not.

**Comment by cabal95** [comment]
In the case of e-mail communications, From Name, From Email and Subject are all required fields, so setting them to 'no value' doesn't seem to make sense in this case.  I would say your comment on "If there is data entered in the field AND the template does not have any content for that field, then leave existing content untouched" makes the most sense here.

**Comment by JimMichael** [comment]
And I think this was fixed once before https://github.com/SparkDevNetwork/Rock/issues/1511

**Comment by MikeDPeterson** [comment]
updated the fix to keep the existing value instead of overwriting with CurrentPerson https://github.com/SparkDevNetwork/Rock/commit/cb090aea96cb3ac1bb1c24e8459d34fade08b7a2

**Comment by tstephens17** [comment]
I was about to put in a bug about this. To me it doesn't make any sense. My situation.

Two email templates. Template A has a From Address defined. Template B does not b/c we want the current person's email address to get fill there.

If you pick template A first, then template B, template As from email is there. And Staff don't pay attention, expecting it to be there's or complain about having to type it in.

This could be solved if I could use lava in the email template from address. {{CurrentPerson.Email}}
