### ISSUE TITLE
Actions Menu workflows display in random order

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2889]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Actions menu on profile page seems to display enabled workflows in completely random order. They do not appear to be displayed by WorkflowTypeID, WF Category ID, alphabetically, or any other obvious order. This is causes problems when you have multiple workflows in the same category, but they are displayed apart in the Actions menu... not a great user experience.

### Steps to Reproduce

1. View Actions menu
2. Observe the workflows are in no discernible order
3. Observe there is no mechanism to order them in a way that makes sense.

**Expected behavior:** 

Actions menu would allow manual ordering for desired placement, or at the very least sort them alphabetically.

**Actual behavior:** 

They appear to be random.

### Versions

* **Rock Version:** All  

![image](https://user-images.githubusercontent.com/3903408/37724137-1a23da3c-2cfe-11e8-9361-87268dc91c0c.png)

**Comment by edmistj** [comment]
Definitely see the need, but the implementation could be tricky. The simple easy approach would be to add a block setting that allowed you to sort them though a comma delimited string of workflow ids. But the user experience on that would be a pain. 

Providing a better experience (perhaps dragging the select workflows in order) would mean writing a custom settings panel for this block. Not rocket science, but definitely not a quick task.

I'd lean towards the better user experience, but it would mean not being available until v8. Feedback?

**Comment by JimMichael** [comment]
I don't have a strong opinion one way or the other, but there is already a precedent of allowing attributes to be "sorted" via the "Attribute Order" setting on the Attribute Values block using the format 714|174|1618|893 etc, so I wouldn't have a problem if that's the same mechanism used to sort the Actions menu... especially as it likely doesn't change *all* that often in most shops. I'm not sure a cool drag-drop block for that minor function is worth it.

**Comment by JimMichael** [comment]
Another wrinkle might be how to handle items on that list that we (as Rock admins) have no control over (like Download vCard) as well as any _Additional Custom Actions_

**Comment by edmistj** [comment]
@JimMichael That's a good point, but I'm not certain how to enable that level of orderings. Seems like it would be best to order them by:

1. Embeded Coded Items (v-card, impersonation)
2. Custom Items added through the block settings
3. Configured workflows in the order defined by the user through block settings.

Does that sound good?

**Comment by edmistj** [comment]
Item #1 could be, #2 is HTML markup so the admin could order them any way they want. Not sure it matters too much to order #1 alphabetically as the rest of the items would not be (and there currently are only 2 of them).

**Comment by JimMichael** [comment]
I think that's a good solution.

**Comment by ethan-sparkdevnetwork** [comment]
This is the approach we settled on:
1. Hard-coded Rock items (v-vard & impersonation)
2. Manually entered custom items added using the code editor in the block settings.
3. Configured workflows in alphabetical order.

Each of the three categories above is separated by a line.
![applicationframehost_2018-06-12_14-29-24](https://user-images.githubusercontent.com/35315117/41318475-45fe0c00-6e4d-11e8-9752-ef6727424a2d.png)
