### ISSUE TITLE
Registration Template Single-Select Attribute bug

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#2890]
### Prerequisites
* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    *[x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * [x]Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When you create a single select registration attribute on a Registration Template and then try and create another registration attribute it causes and error and will not let you save or create more attributes.

Error message at the top of the screen on failure.
Error
338|error|500|Failed to load viewstate. The control tree into which viewstate is being loaded must match the control tree that was used to save viewstate during the previous request. For example, when adding controls dynamically, the controls added during a post-back must match the type and position of the controls added during the initial request.|

### Steps to Reproduce

1. Create/Edit a registration Template
2. Go to forms and create a new registration attribute with a single select type and give it a couple of values
3. create a new attribute and change from person field to registration attribute.  It will cause the system to spin and then eventually stop working and throw an error/exception.

**Expected behavior:** 

Create the next attribute.

**Actual behavior:** 

The template is shot until you reload it.  You can't save or modify it anymore.  I am currently able to do a workaround by creating one attribute at a time and saving after each attribute.

### Versions

* **Rock Version:** 7.3 
* **Client Culture Setting:** EN-US

**Comment by markewampler** [comment]
I recreated the issue on prealpha v8 as the demo site is on v6.2 currently.

**Comment by nairdo** [comment]
Hmm, sounds similar to #2750

**Comment by markewampler** [comment]
Yup.  It throws the same error.  It works fine with other attribute selections, but something about single select throws it off.

**Comment by MikeDPeterson** [comment]
So, eventually figured out that it is any fieldtype that has configuration controls (especially ones that have more than one). For example Single Select as options for 'Values' and 'Control Type'.
