### ISSUE TITLE
v7+Group List block on Profile page (groups tab) does not honor security

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2891]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Group List on the Groups tab of the Profile page does not appear to honor the CurrentPerson's security rights, which exhibit as multiple issues:
1. When adding a group to the person, you can see every group in the tree, regardless of your view rights.
2. If you choose a group you do not have View rights to, the person will be added to the group, but it will NOT be visible in the group list. (It seems the this is the one place that rights are honored on this block)
3. You can delete any group from the list regardless of your Edit rights to the group.

### Steps to Reproduce

1. Edit the rights on any existing group so ONLY Rock admin has View rights, and All users are denied.
2. Log in as a Staff worker (not Rock admin) and go to the Groups tab on any person profile.
3. Click the add button and observe you can see the group you modified, even though you have no view rights to it (and you can also see all other groups you don't have rights to in the list)
4. Choose a group from the list you do not have view rights to, submit, and observe it does not show up in the group viewer.
5. Log in as Rock admin and go to the same profile and observe the group is really there.
6. Observe than you can delete any/all groups in the list regardless of your Edit or Manage Members rights.

**Expected behavior:** 

1. The block would only let you see/add groups you have view rights to.
2. You would not be able to delete groups you don't have Edit or Manage Members rights to.

**Actual behavior:** 

Rights are not honored. It would be helpful if someone else could verify these results, but I'm seeing it on my 7.3 as well as prealpha.

### Versions

* **Rock Version:** 7.0+

**Comment by tscrip** [comment]
I don't know if this points to a larger issue, but I just opened another Issue for a **Staff User Permission** not being respected. https://github.com/SparkDevNetwork/Rock/issues/2931

**Comment by MikeDPeterson** [comment]
@tscrip This issue is fixed.  It was just an issue with the GroupList block, so it isn't related to #2931
