### ISSUE TITLE
Registrant Filters on attributes are not specific to the registration

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#2892]
The RegistrationInstanceDetail block is saving the filters selected as a user preferences. This preference though is not specific to the registration template. So if a user sets a filter for an attribute that one registration has, and then tries to view a different registration with a template that does not use that person attribute, the grid is still trying to filter on that value and does not display an indication that it is being filters.

The saving/reading of user preferences in this block should really be specific to the registration template being used (similiar to how the GroupMember list block saves preferences specific to the Group that is being viewed).

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/3a1729a8b7ce8397b8318112d65b3050f6e86f2b
