### ISSUE TITLE
NavigateToLinkedPage and LinkedPageUrl resolve to default route when parameters passed

### ISSUE THREAD

**Issue by maurice-ellis** [SparkDevNetwork/Rock#2894]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

NavigateToLinkedPage and LinkedPageUrl resolves to the default page route (Login, Register), howerver, when query parameters are passed, both of these functions resolve to page/(number) instead of the pretty url.

**Expected behavior:** 

Expect NavigateToLinkedPage and LinkedPageUrl to resolve to a pretty url whether params were passed or not.

**Actual behavior:** 

NavigateToLinkedPage and LinkedPageUrl resolve to  default route when params are passed in.

### Versions

* **Rock Version:** Rock McKinley 7.3 (1.7.3.55) 
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
@maurice-ellis This is actually working correctly.

If you look at the Login page, the only route it has is `Login`. Since that route has no parameters defined, it cannot be matched when parameters are passed to the two mentioned methods. So if you pass `Id=1` as the query parameters, it will end up like `/page/815?Id=1` because there is no `Id` parameter in the route.

However, if you define a route on that page like `Login/{Id}`, then it can match that parameter and you end up with a Url of `/Login/1`.

**Comment by maurice-ellis** [comment]
Aaah, okay.

**Comment by maurice-ellis** [comment]
@cabal95 is there a way that it can remain a query? Specifically for dealing with the redirecturl?

**Comment by cabal95** [comment]
Not sure what you mean by "remain a query"?  Can you give an example?

**Comment by maurice-ellis** [comment]
if I want it to remain as Login?Id=1 (query parameter) instead of Login/{Id}

**Comment by cabal95** [comment]
Ah, Not really. You would have to do that manually by building the custom URL.

**Comment by maurice-ellis** [comment]
Okay, just want to make sure it wasnt possible before making a custom solution

**Comment by mikejed** [comment]
Isn't this what you're asking for @maurice-ellis ?
http://rock.rocksolidchurchdemo.com/myroute?Test=This+works!
Additionally, the Login page DOES take additional parameters - `returnurl` is a common stock example where one is used...
