### ISSUE TITLE
Rock icon font doesn't work properly with Zebra printers

### ISSUE THREAD

**Issue by lpeterson1** [SparkDevNetwork/Rock#2895]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
The icon font for label printing doesn't work properly. When the font is installed in its entirety the ZPL ^FT  command doesn't place the text correctly (the y coordinate doesn't work), always placing the icon at the top of the label. This necessitates the established workaround of creating a non-scalable, bitmapped 26-point subset for use on the printer.

### Steps to Reproduce

1. Download the entire rockcheckin.ttf font to a printer (don't select characters)
2. Print any icon on a label

**Expected behavior:** 
The icon should be positioned correctly

**Actual behavior:** 
The icon is placed at the top of the label regardless of its y-coordinate

It turns out that this seems to be a problem with the way Fontello generates TrueType fonts. I was able to convert the stock icon font to an SVG font using TransType4, then back to TrueType, and it worked properly, except that some of the characters in the 26-point font weren't rasterized properly. 

I then used icomoon to create a font from scratch using the same FontAwesome icons (although some have apparently been updated since the original font was created). It works properly. It can be installed complete or as a 26-point bitmap using the current instructions. It works correctly with the existing icon label, characters are rescalable, and creating labels works correctly with ZebraDesigner.

Switching to a font that works correctly would enhance the user experience, especially for new users setting up to use the icon label. A font that scales correctly would make designing custom icon labels easier. The complete font is also half the size when installed on a printer.

### Versions

* **Rock Version:** N/A
* **Client Culture Setting:** N/A

**Comment by edmistj** [comment]
@lpeterson1 Sounds like you have a font that works. Is that correct? If so could you email or DM it to me in Slack? I could get it replaced.

**Comment by edmistj** [comment]
Updated the custom Rock check-in font. If you've installed this on your printers you may want to updated it. In some cases the icons on this font would not accept the proper placement information from the label. See the related Github issue for more details.
