### ISSUE TITLE
Enhance Notification List Block to make use of all table columns

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2896]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

1. The Notification List supports displaying HTML, but it wraps the content inside a `<p>` tag, which causes quirks when trying to display lists (ol and ul cannot be inside a p tag) as well as issues when trying to display a notification with multiple paragraphs (example, custom notifications to our staff).
2. The Notification table defines `Read` and `ReadDateTime` columns but they are never used. Instead when a user clicks the "x" the NotificationRecipient row is completely deleted.
3. The Notification table also defines an `IconCssClass` column, which is not used to display an icon in the notification list block.

### Suggested Enhancements

1. Change the `<p>` to ` <div>`.
2. When clicking the "x", instead of deleting the row update `Read = true` and `ReadDateTime = Now`.
3. If `IconCssClass` is not empty, display the icon to the left of the title (example below).

![image](https://user-images.githubusercontent.com/1119863/37839552-f5adf680-2e77-11e8-96f5-57458839ec19.png)

I can make a pull request for these changes.

### Possible future enhancements

1. Lava Template setting that allows for custom formatting of the notifications. Because of the postback link, it would probably need to work akin to the Group Detail Lava block where we pass in a postback parameter to be used to mark as read.
2. Category assignments so we can have different notifications displayed on different pages?

These would not be included in the above PR unless it was specifically requested - it's just an idea for making it a little more customization and a little more useful in other places.

### Versions

* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Additional enhancement/bug just found. The delete buttons need to be marked as RequiresValidation=false, otherwise if there is another block on the page with required fields it will not postback because validation fails.

**Comment by edmistj** [comment]
Sounds good. Can you ensure though that changing the <p> to a <div> does not change the spacing of the text (i.e. smash it up under the heading). I don't think it will, but if you could look at it it would be nice.

**Comment by cabal95** [comment]
It actually spaced it out a few pixels more. I’ll include side by side screenshots with PR.
