### ISSUE TITLE
Outdated Workflow Attribute information

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#2899]
### The issue:
The list of available Workflow Attribute Types and the RawValue format to write to those data types appears to be out-of-date, both on [https://www.rockrms.com/page/736](https://www.rockrms.com/page/736) and on [https://www.rockrms.com/Rock/BookContent/12/111#afewtechnicaldetails](https://www.rockrms.com/Rock/BookContent/12/111#afewtechnicaldetails)

I recommend that the "A Few Technical Details" section should contain only sampling of the most common attribute types (FinancialTransaction, Group, GroupMember and Person would be my recommendation), and then link to the full list at /page/736. That way there aren't two lists to keep up-to-date with future revisions.

### A recommendation:
It also seems that it would be helpful to indicate whether an attribute of a given type can be used to query for properties and attributes. For instance, you can use
`{{ Workflow | Attribute:'PersonAttribute','FirstName' }}`
since that attribute type represents a full entity. But you can't do something like
`{{ Workflow | Attribute:'ContentChannelTypesAttribute','Id' }}`
since that attribute type only contains a list of GUIDs, and no full entities. It would be nice to have something that made this explicit to new users.

### A proposed solution to take care of both of these:
To this end, and _**in an effort to crowd-source this effort**_ rather than asking the Core Team to spend time on this, I have extracted a current list of Workflow Attribute Types from PreAlpha and copied over the RawValue descriptions from the existing table where the Field Types match.

An editable version of the document I created is available at [https://1drv.ms/x/s!At5N-9iJ3NUMkrEf5Yu1z9eqr9fWiw](https://1drv.ms/x/s!At5N-9iJ3NUMkrEf5Yu1z9eqr9fWiw) . Please take a look and see if you can help fill in some blanks off the top of your head! _(There are some items I'm "fairly" sure I could fill in without verification, but since this is intended to become a reference document, I only filled in items I was quite confident in - please follow suit for QA purposes!)_

Once we fill in all the easy stuff, we'll be able to go through and ascertain values by actually assigning some sample Workflow Attributes on the prealpha server to complete the list.

There are a number of entries which are presently listed, but which do not appear to be available as a type of Workflow Attribute any longer. Some of these appear to be from pre-1.0, while others may have simply been renamed sufficiently that I don't know for sure that the description is still accurate. I have listed these entries at the bottom of the spreadsheet, in a section of their own. Feel free to consult that list, and if you see an item which was simply renamed, pull that description up where it belongs and remove it from that "to be removed" list.

Also, some of the RawValue descriptions are a little ... confusing. If you can clarify an obtuse description, please do so.

Hopefully if we can pull together and complete this list, it will be nearly as easy as copy-and-paste into the docs!

**Comment by mikejed** [comment]
FYI, I'll start trying to get people to help out with this effort mid-week next week, AFTER everyone's recovered from Easter ;-)

**Comment by jonedmiston** [comment]
Closing based on confirmation from Michael that this appears fixed.
