### ISSUE TITLE
"Right" Lava Filter throws error if string is shorter than requested length

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2902]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

On v8.0 at least, possibly 7.x, if you do use the `Right` lava filter and request `n` characters, where `n` is ~less~ more than the total length of the string, then an exception is thrown. This does not seem to affect the `Left` filter.

### Steps to Reproduce

1. `{{ '123' | Right:4 }}`

**Expected behavior:** 

I should get the original string back.

**Actual behavior:** 

I get an exception.

### Versions

* **Rock Version:** 8.x
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
Confirmed on 7.3. I think you mean "where n is MORE than the total length of the string...", though?
