### ISSUE TITLE
NullReferenceException in DDay.iCal

### ISSUE THREAD

**Issue by maurice-ellis** [SparkDevNetwork/Rock#2905]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Im not sure what is going on, I never had an issue before. Ive tried this on the Rock Demo (even though it is outdated) and was working on our production server up until this morning. When I click on an event calendar (Public or Internal) it now shows this error.

![screen shot 2018-03-26 at 11 57 51 am](https://user-images.githubusercontent.com/7678232/37926815-37933552-30ed-11e8-912e-0a656030d581.png)

**Expected behavior:** 

Expecting to pull up event information

**Actual behavior:** 

Runs into an error

### Versions

* **Rock Version:** 7.3
* **Client Culture Setting:** en-US

**Comment by maurice-ellis** [comment]
It was one of our events, Im not sure exactly what happened because we haven't touched that specific event in a while, but it wasnt able to generate the friendly text. I was able to get back in and resave it (didnt even make any changes) and it works.

**Comment by cabal95** [comment]
@maurice-ellis I'm going to close this as it seems like it was a data error. If it happens again and you are able to quantify what is making the data somehow invalid please re-open with those details and we can try to replicate it.
