### ISSUE TITLE
Enhance notifications with categories and manual entry

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2909]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
I'm listing this separately as this is much more of a new feature than a bug/enhancement fix, but the original thinking started in #2896.

The enhancement would be two-fold.

### 1. Update Notifications to support Categories
* Notification entity would get a new column for CategoryId. This should probably be optional to not break backwards compatibility with other things that might create Notifications already.
* An initial category of "Administration Notices" would be created and all current notifications would be updated to this category Id.
* The Notification List block type would be updated to include an optional setting for which category to filter to. If none set, show all notifications.
* Any existing notification list blocks instances would be updated to use the "Administration Notices" category.
* Update the Spark Link job to have a block setting for which category to assign notifications to, update existing instances to use the "Administration Notices" category.

This would keep current functionality as is but allow expanded use of notifications. For example, you might create a category of "Life Group Leaders" and put the notification list block on the small group leader toolbox so that you can post notifications to life group leaders.

### 2. New block for entering notifications
This is a block we have already created but it would need to be updated for categories. It also needs the editor replaced with the full HTML editor (toolbar etc).

The block allows you to enter people manually via the person picker:

![image](https://user-images.githubusercontent.com/1119863/37985933-fbad701c-31ae-11e8-8588-fec761c30d88.png)

The other two options allow you to select a Group or DataView to post the notification to:

![image](https://user-images.githubusercontent.com/1119863/37985976-1edc229a-31af-11e8-93f2-647aeef0d31c.png)

![image](https://user-images.githubusercontent.com/1119863/37985991-2bcc6e88-31af-11e8-822f-cefc6cbecf8a.png)

There are some other minor tweaks that should probably be made, such as changing the text of the "Save" button to "Post", though I'm not sure which makes more sense.

Additionally, I'm not sure where this block should be installed by default.

Since much of the work is already done I can work on the PR if this sounds good, though I may have some follow up questions on exact implementation to make sure I'm covering all the bases.

### Versions
* **Rock Version:** 8.x
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
