### ISSUE TITLE
New Workflow Action: Process Incoming SMS

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2910]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

This was discussed briefly on Slack but wanted to get it here for better tracking. I have a custom Workflow Action that "injects" a text string into the two-way SMS system. You provide the From Number, To Number and Message body and it sends it off to the SMS handler to be treated like a normal incoming SMS, as if it just came in from Twilio to the standard handler. This allows you to have a phone number handled by the Text To Workflow processing, and then still pass the message on to the two-way system.

![image](https://user-images.githubusercontent.com/1119863/37998761-cc198cc0-31d4-11e8-81d2-12a3236cc5b0.png)

All 3 fields support Lava. I would expect this to land in the 8.0 release, but until then it is available as a plugin.

@edmistj had recommended the action be renamed to `Process SMS as Communication Response`. I'm going to tweak that a bit to be `Process as SMS Communication Response` as I think that is clearer to what it is actually doing. It's verbose, but gets the point across.

### Versions

* **Rock Version:** 8.0?
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Sounds good. I'm good with the name tweak.
