### ISSUE TITLE
New Workflow Action: Entity Attributes Set

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2911]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

This was originally discussed on Slack, moving here to keep better track of it for historical purposes with the upcoming pull request.

This workflow action exists now as a plugin but will be moved into core, probably in v8.0. You can specify the Entity Type whose attribute(s) will be updated. You can then specify the "Entity" itself by either Guid or Id value. This functions nearly the same as the `Entity Attribute Set` except that it allows you to set multiple attributes at once.

~Implementation question: Should this be added as a new action, or should the existing action be updated to support the Key Value List style and a migration to convert any existing values to the new format? (I think that would be possible, just take some work). The current block is a bit easier to work with if you are setting it to an existing workflow attribute value.~ On second thought, unless there is a strong desire to do it this way, I think I'd rather add this as a new action rather than try to modify the old (as I look at the set entity properties version I think that one would be much harder to migrate).

![image](https://user-images.githubusercontent.com/1119863/37999209-b0844f66-31d6-11e8-9cbe-ad96d877cb50.png)

> Note: The screenshot uses a custom Key Value List field type which would not be included. This is why the width is 100% instead of the standard smaller width of a normal Key Value List field.

### Versions

* **Rock Version:** 8.0?
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Is the sole benefit of this block that it does more than one attribute at a time?  If so I think we should update the current block or not add this one. We don't want to have too many actions that basically do the same thing.

**Comment by cabal95** [comment]
In the case of this specific block, yes. It primarily came up when automating the creation of fundraising groups and the prospect of having to create a dozen (or more) Set Entity Attribute actions to set all the attributes for a single group.

**Comment by cabal95** [comment]
I'll pause the discussion on this one for the moment until we come to a conclusion on the properties version at #2912, I just noticed you updated your comment which didn't reflect in Slack. Once we have a decision there we can figure out what the best course of action is on this one too.
