### ISSUE TITLE
New Workflow Action: Entity Properties Set

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2912]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

This was originally discussed on Slack, moving here to keep better track of it for historical purposes with the upcoming pull request.

This workflow action exists now as a plugin but will be moved into core, probably in v8.0. You can specify the Entity Type whose properties will be updated. You can then specify the "Entity" itself by either Guid or Id value. This functions nearly the same as the `Entity Property Set` except that it allows you to set multiple attributes at once.

The primary difference between the two, beyond the fact that this can set multiple properties at the same time, is that this action can also _create_ new entities in the database. If the "Existing Entity" is left blank, then a new entity will be created and it's Id/Guid stored in the "Entity Attribute" output attribute.

@Tschrock You wrote the original single-property implementation. Can you give me some insight on the use case to the null value handling option? I can sort of see the use of the `Ignore` option (though that could be done by an action filter), but I'm not understanding the use case for the for `Set To Empty` vs `Set To Null`. The only time I can see that mattering is if you are setting a string property and you specifically want to set it as null instead of an empty string. And the way most Rock string checks, there is no distinction between the two.

I'm trying to decide if it needs to be implemented as I don't currently implement anything like that. It's just automatic. If the property is of type string then it gets a blank string set. If it's any other type (say int) and nullable, then it gets a null value set. If it's a non-nullable property and non-string, then an error is logged and the action fails.

![image](https://user-images.githubusercontent.com/1119863/37999585-5f41550c-31d8-11e8-90a8-28f6216773a8.png)

> Note: The screenshot uses a custom Key Value List field type which would not be included. This is why the width is 100% instead of the standard smaller width of a normal Key Value List field.

### Versions

* **Rock Version:** 8.0?
* **Client Culture Setting:** en-US

**Comment by Tschrock** [comment]
I don't fully recall why we needed the null value handling, but I left it there to give more options to the user. If you think it can handled automatically without causing issues with anything I don't have an argument for or against it. 

Side note: if you use the built-in Key Value List field, you'll probably run into #1512 which is why I didn't build it like this originally.

**Comment by cabal95** [comment]
That has actually been fixed in 7.0. I'll go find the related commit and close that issue.

Thanks for responding. I'll go with the code I have for now then unless somebody else chimes in with a specific need.

That bug is actually half the reason I implemented with my own custom Key Value List field. I needed this pre-7. (The custom field also lets you have values of any field type, not just text, but that is another plugin entirely).

**Comment by cabal95** [comment]
I take it back, those haven't been fixed. The Key Value List one was fixed, but the Value List one isn't fixed. Since this uses Key Value List though it should be okay.

**Comment by edmistj** [comment]
Sounds good.

**Comment by cabal95** [comment]
Potentially. The tricky part is the "null behavior" of the existing one. Having a single setting for that with multiple properties being set could be tricky. And i'm not sure what removing that attribute would do to existing functionality. Let me poke into that part a bit more and post some more information on the topic for review.
