### ISSUE TITLE
[EN] Group's Security Role option limited to Administrate privilege

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2913]
I'm 100% aware that this is an extremely minor request 😉 

### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

I don't think that it is necessary or helpful to allow people with edit, but not Administration rights for a Group to toggle whether or not a Group should count as a Security Role.

When my staff have been making groups, they're **totally** unaware of what Security Role means, so they will check it if the volunteer position acts as security, or if the role requires that the person has a background check.  Since they really don't have any context for what it actually means, it's really a toss-up for how they actually interpret it.

### Desired Behavior

I would prefer if staff non-admin members weren't allowed to toggle the Security Role option on a Group.  This helps avoid confusion/frustration from admins and staff alike. Admins don't have to worry about security roles changing without reason or warning, and staffers don't have to act with confusion when it comes to setting up a Group.

**Comment by cabal95** [comment]
We have the exact same problem.

**Comment by edmistj** [comment]
We can make the security role edit require admin rights to the group.
