### ISSUE TITLE
Key Value List does not display correctly with ^ in key or value.

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2916]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If a Key or Value contains `^` then when the Key Value List is displayed, it does not display correctly. The Edit view is correct, but the "text version" is not.

![image](https://user-images.githubusercontent.com/1119863/38000550-ec88decc-31dc-11e8-9b72-c6cd81007ede.png)

![image](https://user-images.githubusercontent.com/1119863/38000559-f6846a86-31dc-11e8-893a-e88742de953b.png)

**Expected behavior:** 

`key1: value1, key|2: value|2, key^3: value^3`

**Actual behavior:** 

`key1: value1, key|2: value|2, key^3^value^3`

### Versions

* **Rock Version:** 8.0, 7.x?
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in commit 830621024a3d258f2058514cffc721670d54d0d1.
