### ISSUE TITLE
Error in WorkFlow Adding Person to New Family.

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#2917]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

(I'm new to Rock development and this is my first bug report.)
In a Workflow, trying to add a second person to a new family generates an exception.

### Steps to Reproduce

1. Create a workflow with two Person attributes and one Group attribute.
2. Use Person Attribute From Fields to create a Person1 in Rock.
3. Use a Lava Run workflow with 
{{ Workflow | Attribute:'Person1','Object' | Groups:'10','All' | First | Property:'Group.Guid' }}
to get the newly created Family.
4. Use Person Attribute From Fields to create Person2 in Rock.
5. Use Group Member Add from Attribute to add second person to Family.
6. Error!

**Expected behavior:** 

Successful add.

**Actual behavior:** 

Error dump at top of page.

The error occurs in AddPersonToGroupAttributeTo.cs public class AddPersonToGroupWFAttribute.  
                    if ( groupGuid.HasValue )
                    {
                        group = new GroupService( rockContext ).Get( groupGuid.Value );
                        if ( group != null )
                        {
                            // use the group's grouptype's default group role if a group role wasn't specified
                            groupRoleId = group.GroupType.DefaultGroupRoleId;
                        }
                    }

The issue is that group is not null but group.GroupType is null so it can't get the default role.  Adding the lines below fixes the issue but I don't know if that is the proper fix because it seems like GroupService should not be returning a null GroupType object.

                            if (group.GroupType == null)
                            {
                                group.GroupType = new GroupTypeService(rockContext).Get(group.GroupTypeId);
                            }

### Versions

* **Rock Version:** 7.3 
* **Client Culture Setting:** Azure servers

**Comment by ethan-sparkdevnetwork** [comment]
Lazy loading was not working for some reason. I used different methods and was able to get it to work calling GroupService.GetByGuid, .Queryable(), or by using .Get but using a new rockcontext instead of the one being passed into the method. Decided to fetch it from the GroupTypeCache since that will save us a DB hit.

groupRoleId = GroupTypeCache.Read( group.GroupTypeId ).DefaultGroupRoleId;
