### ISSUE TITLE
Url Redirect Workflow Action loses values due to Attribute Key Collision

### ISSUE THREAD

**Issue by jhawkzz** [SparkDevNetwork/Rock#2920]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
On Rock start up, Rock.Workflow.ActionContainer.Instance.UpdateAttributes() is called,
and can cause the values of all Url Redirect workflow actions to be deleted.

This is due to the Url Redirect action having two Workflow Action Attributes with the same key.

During startup, Rock updates all Workflow Action Attributes to make sure they match the latest definition defined in code files. 

Because the Url Redirect action has two attributes with the same key, Rock updates this attribute every time a reboot occurs, causing the attribute and all values to occasionally be deleted. 

### Steps to Reproduce

1. Go to Rock\Workflow\Action\WorkflowControl\Redirect.cs
Note lines 37 and 38. 
[UrlLinkField] has no explicit key defined, but has a name of "Url". (This results in the key being called "Url")

[WorkflowTextOrAttribute] has an explicit key defined of "Url". This results in both attributes having the same key.

2. Find the Attribute row in the Attributes table that represents the [UrlLinkField], and observe the "ModifiedDateTime." 

3. Reboot Rock, and observe the new "ModifiedDateTime". It will be the time of the reboot.

4. The fix is to simply update [WorkflowTextOrAttribute] to use a key name other than "Url". However, I cannot create a pull request without doing a migration to prevent workflows with values set from being lost.

**Expected behavior:** 
The [UrlLinkField] Attribute should only ever be updated if the actual code is updated.

**Actual behavior:** 
The [UrlLinkField] Attribute is updated every time Rock is run. (And takes on all the properties of the [WorkflowTextOrAttribute] field

### Versions
* **Rock Version:** Rock McKinley 6.1 (alpha branch)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Those should definitely not have the same Key as that is an unsupported configuration.

I feel like maybe the `UrlLinkField` should just be deleted as it is being handled by the WorkflowTextOrAttribute (you can either enter a Url value or select an attribute that contains the Url value).

**Comment by jhawkzz** [comment]
That might work! Yes, it causes major issues that you don't notice until you discover your workflow isn't redirecting properly--Then you go "Uh, where'd the values for these redirects go??" lol.

**Comment by jhawkzz** [comment]
Just to follow up--

I tested @cabal95's proposed solution of removing UrlLinkField. This works better.
Not only does it simplify code, but its migration-safe, because the UI for it was never exposed in the Workflow Editor. Users only used to WorkflowTextOrAttribute whether that was their intention or not.

So simply removing UrlLinkField fixes this issue!
