### ISSUE TITLE
[EN] New dataview filter for Attendance at Campus

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2924]
### Description

I have code that adds a new reporting option for Attendance at Campus.  This is helpful for setting up dataviews that match Attendance Analytics reports where the Attendance Campus is the desired filter, not the Person Campus.

This filter can also be used for multi-site churches to determine if someone's primary campus has changed based on their recent attendance.  

Posting here for UI and category feedback.  The current category is `Group Attendance > Attendance at Campus`.  This code is sponsored by [New Hope Church](https://www.newhopechurch.tv/).

**Proposed PR:** 

**Filter Name and Tooltip:**
<img width="824" alt="screenshot 2018-04-05 09 59 24" src="https://user-images.githubusercontent.com/1210933/38370556-6050cc48-38b8-11e8-9006-3b24bee2e46b.png">

**Filter UI:**
<img width="820" alt="screenshot 2018-04-05 10 01 22" src="https://user-images.githubusercontent.com/1210933/38370560-650a1e7e-38b8-11e8-919d-a0f4b7a644b1.png">

**Post-Edit Filter Description:**
<img width="845" alt="screenshot 2018-04-05 09 59 03" src="https://user-images.githubusercontent.com/1210933/38370570-68c26d50-38b8-11e8-989e-d44521b49f43.png">

### Versions

* **Rock Version:** v7.3
* **Client Culture Setting:** en-us

**Comment by edmistj** [comment]
@dcs619 looks good. Do you mind moving it to `Group Attendance > Attendance at Campus`. I think you're right that it makes sense there. I can see in the future someone adding some additional filters to it to filter by area/group type. Those changes would make it more of a fit there.

Thanks!

**Comment by dcs619** [comment]
@edmistj Fixed and pushed
