### ISSUE TITLE
Typos on Google Map Lava Shortcode Description

### ISSUE THREAD

**Issue by BrentPirolli** [SparkDevNetwork/Rock#2928]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

There are a couple of typos on the Home/CMS Configuration/Lava Shortcodes section. In the description of the Google Map shortcode it says:

> Note: Do to this javascript requirements of this shortcode you will need to do a full page reload before changes to the shortcode appear on your page.

### Steps to Reproduce

1. Read the description for the Google Map lava shortcode.

**Expected behavior:** 

Due not Do
the not this
add a comma after shortcode

> Note: Due to the javascript requirements of this shortcode, you will need to do a full page reload before changes to the shortcode appear on your page.

**Actual behavior:** 

> Note: Do to this javascript requirements of this shortcode you will need to do a full page reload before changes to the shortcode appear on your page.

### Versions

Rock Version: Rock McKinley 7.3 (1.7.3.55)
Client Culture Setting: en-US

**Comment by ethan-sparkdevnetwork** [comment]
Created a migration to update the documentation with corrected grammar.
