### ISSUE TITLE
Help text on Lava Webhook Defined Type has incorrect URL

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2929]
### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

The help text for the Lava Webhook Defined Type incorrectly has an example URL that contains `LavaApi.ashx` instead of `Lava.ashx`. This is a holdover from when it was implemented as a plugin before going into core.

Since this is an IsSystem Defined Type and the user is not allowed to edit it, we should be able to just update this help text in a migration to fix it.

I can submit a PR for this, but since it will be a migration only change it might be faster to just copy & paste the original migration code from here [https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Migrations/Migrations/Version 7.0/Version 1.7.0/201707171725146_UniversalSearchPages.cs#L148](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Migrations/Migrations/Version 7.0/Version 1.7.0/201707171725146_UniversalSearchPages.cs#L148) and modify the help text.

Also suggest the full URL be changed to [http://rock.rocksolidchurchdemo.com/WebHooks/Lava.ashx/test?queryParameter=true](http://rock.rocksolidchurchdemo.com/WebHooks/Lava.ashx/test?queryParameter=true)

Let me know if you want me to do this as a PR.

**Expected behavior:**

Sample URL should be correct.

**Actual behavior:**

Sample URL is not correct.

![image](https://user-images.githubusercontent.com/1119863/38439709-987e0442-3993-11e8-8d95-e6714a4a4d0e.png)

### Versions ###

* **Rock Version:** 7.0
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
I think we need to make this a PR since many people have run it. I like the idea of using rocksolidchurchdemo too.

**Comment by MrUpsideDown** [comment]
Fixed with this commit:
https://github.com/SparkDevNetwork/Rock/commit/e930941bf9b14aaec515c33d2ce4d3da583d9adf
