### ISSUE TITLE
Communications Approval Does Not Respect Role Staff Worker

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#2931]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
If a person is in the Staff Worker role, their communication is always sent without needing approval. I have tried explicitly denying the role and myself, but I can still send emails without needing access.

### Steps to Reproduce

1. Add yourself to the Staff Users role
2. Open Communication Entry Block security, and add Staff Users to the Approve (with a value of deny).
3. Go through the process of sending an email.
4. Notice it is automatically Approved.

**Expected behavior:** 
If a user is not in the Approve list, they should not be able to send emails without approval.
If a user is denied Approval security, they **FOR SURE** shouldn't be able to approve communications.

**Actual behavior:** 
Communications seem to always be approved if the user entering communications is in the Staff Users role.
### Versions

* **Rock Version:** 7.3
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
I think this is the same issue as #2930.
