### ISSUE TITLE
Person detail changes via Registrations not logged in Person History

### ISSUE THREAD

**Issue by watermarkgeek** [SparkDevNetwork/Rock#2939]
Prerequisites
 {x}Put an X between the brackets on this line if you have done all of the following:
Can you reproduce the problem on a fresh install or the demo site?
Did you include your Rock version number and client culture setting?
Did you perform a cursory search to see if your bug or enhancement is already reported?
**Description**
It would be great if modifying user profile information during a registration were logged to person history, to facilitate troubleshooting and leaving a paper trail of any changes.

**Expected behavior**:

When a user fills out a registration, and has the option of updating some of their person details, the fact that those details changed, and how they were changed (Registration) should be visible in the person history for that person.

**Actual behavior:**

Currently, a user can make changes to their personal information during a registration process and none of those changes show up in person history.  For example, if a registration allowed (mistakenly) for a mobile number to be left blank, it would erase the mobile number on the profile and leave no record that it was due to the registration.

Versions
Rock Version: All

**Comment by ethan-sparkdevnetwork** [comment]
This was added in 8.0 as part of the Group History changes. Verified functionality, changes are recorded in the history table for the person entity and are displayed on the Person History grid.
