### ISSUE TITLE
Anonymous fundraising donations show address

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#2942]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When someone anonymously donates to a Fundraising Participant, the donation shows on their participant page with Anonymous for the name but shows their address. That makes the gift not really anonymous.

![image](https://user-images.githubusercontent.com/12735965/38944057-835a555c-42f8-11e8-8242-e1fcfe2fa70a.png)

### Steps to Reproduce

1. Donate to a fundraising participant and check the give anonymously box
2. Log in as the trip participant
3. Go to the participant page
4. See the address of the person who donated to the trip

**Expected behavior:** 

The address field should also say anonymous or be blank

**Actual behavior:** 

The giver's address shows in the grid

### Versions

* **Rock Version:** [7.3]  
* **Client Culture Setting:** [us-en]

**Comment by ethan-sparkdevnetwork** [comment]
Address for anonymous donors will be blank.

**Comment by treyhendon** [comment]
Just looking at this issue with Kensington and in comparing the 1.7.4 branch to the 1.7.5 branch ( https://github.com/SparkDevNetwork/Rock/compare/hotfix-1.7.4...hotfix-1.7.5 ), this does not appear to be included in 7.5 as tagged.

**Comment by JimMichael** [comment]
Several things that got tagged as 7.5 a while back actually ended up in v8, because they weren’t sure if there was going to be a 7.5... and there wasn’t, until that single API issue 2 weeks ago.... thus the confusion.
