### ISSUE TITLE
Accordion Lava shortcode doesn't work with multiple accordions on the same page

### ISSUE THREAD

**Issue by bengoshow** [SparkDevNetwork/Rock#2944]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Accordion Lava shortcode doesn't work with multiple accordions on the same page.

When clicking on items in the second accordion, items in the first accordion are activated.

You can see a demo of the issue here: https://rock.sojournchurch.com/page/479

### Versions

* **Rock Version:** [7.0]  
* **Client Culture Setting:** [en-US]

**Comment by garrettjohnson** [comment]
Fixed in v7.4

**Comment by bengoshow** [comment]
Hey Garret - is just this fix something I can pull into our site running on v7.0? Can you point me to the code?

**Comment by bengoshow** [comment]
Hi @garrettjohnson @edmistj  
We're running 7.4 on this beta site, and I can see that your change has been applied to the short code, creating a unique ID for each accordion on the page. However, the individual item IDs within the accordion are still duplicated, so clicking on "collapse1" on the second accordion still opens the panel on the first accordion.
https://beta.newpointe.org/page/3579

**Comment by bengoshow** [comment]
p.s. Should I start a new issue for this, or continue the conversation here in the original issue?

**Comment by garrettjohnson** [comment]
@bengoshow Here's the new markup https://gist.github.com/garrettjohnson/43c711a25253bd240c75c9d0771aee6a, to update you'll need to fix it at the database level since system snippets aren't editable via the UI. Ping me on Slack if you need anything!

**Comment by garrettjohnson** [comment]
@bengoshow Here's a fix if you need. I'll get it into the next migration https://gist.github.com/garrettjohnson/d0c2c75affdab6d31c46a406276f88d1

**Comment by timlem** [comment]
Hey @garrettjohnson - where do i put that code? I haven't done anything with lava shortcodes
