### ISSUE TITLE
Grade Auto-Fill From Graduation Year on Person Edit Page is Incorrect

### ISSUE THREAD

**Issue by beejjacobs** [SparkDevNetwork/Rock#2947]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When choosing a Graduation Year on the Edit Person page, the Grade is auto-filled incorrectly - it is one grade too high. The value then displayed on the person's page after saving is correct.

Edit page:
![image](https://user-images.githubusercontent.com/5353497/39100608-f66ebd1a-4683-11e8-89a3-6a2ad344b778.png)

Profile page:
![image](https://user-images.githubusercontent.com/5353497/39100611-01e43850-4684-11e8-9085-dd2ec0a540ac.png)

### Steps to Reproduce

1. Edit a child, e.g. [Noah Decker](http://rock.rocksolidchurchdemo.com/Person/74/Edit) on the demo site
2. Select a new graduation year
3. Note the auto-filled Grade is incorrect
4. Save the changes
5. View the profile and note the Grade is correct

**OR**

1. Edit a child, e.g. [Noah Decker](http://rock.rocksolidchurchdemo.com/Person/74/Edit) on the demo site
2. Select a new Grade
3. Note the auto-filled Graduation Year is incorrect
4. Save the changes
5. View the profile and note the Grade doesn't match what was selected (Graduation Year takes precedence)

**Expected behavior:** 

For the auto-filled Grade value to match the actual calculated Grade, based off the Graduation Year

**Actual behavior:** 

The auto-filled Grade value is one higher than it should be

### Versions

* **Rock Version:** McKinley 6.10 (Church site) & McKinley 7.3 (demo site)
* **Client Culture Setting:** en-GB (briefly tested on en-US, appeared to show the same behaviour)

**Comment by cabal95** [comment]
@beejjacobs I just tested on the demo site and it seems to be working correctly for me. I am using Windows 10 64-bit with Firefox 59.0.2.  Can you report what OS + browser you are using and possibly try a different browser and see if you have the same problem?

Also, possibly post a screenshot of the Grade drop down when it's expanded so we can see all the choices visible. Maybe somehow a choice is getting added on your browser that shouldn't be there.

**Comment by beejjacobs** [comment]
Sure, I am also on Windows 10 64-bit. That was tested on Chrome Version 66.0.3359.117 (Official Build) (64-bit). 

It appears to match the School Grades defined type values:
![image](https://user-images.githubusercontent.com/5353497/39100798-845f68ec-4687-11e8-9a96-ad519be1f646.png)

Firefox 41.0.2
![image](https://user-images.githubusercontent.com/5353497/39100803-905b10ec-4687-11e8-95a2-fee34f74f159.png)

IE 11 & Edge were the same.

Perhaps it is a regional setting of some sort since it doesn't appear to be browser related?

**Comment by JimMichael** [comment]
Looks like it's either this issue that's not actually fixed, or a side-effect of the fix?

https://github.com/SparkDevNetwork/Rock/issues/2079

**Comment by beejjacobs** [comment]
I did find that issue in my search before hand; maybe it is related. To be clear though the profile page does show the correct grade.

**Comment by beejjacobs** [comment]
If I swap `Grade Transition Date` to be `dd/mm` then the auto-fill is correct, but the profile page is wrong. Is one assuming it is `dd/mm`, the other `mm/dd`, based on some regional setting perhaps?

**Comment by cabal95** [comment]
That seems likely. The issue Jim mentioned was probably to fix the C# side (when in view-only mode). There is probably a similar change that needs to happen on the JavaScript side (when in edit mode) causing it to have `dd/mm` or `mm/dd` to be swapped when determining the grade to auto-select the item in the drop down list.

**Comment by beejjacobs** [comment]
I'm still learning how it all works; but if someone can point me to the JavaScript in question I am happy to try and fix it.

**Comment by beejjacobs** [comment]
I think this is causing issues elsewhere too, I am having similar out-by-one issues on data views based on school year. Happy to provide details if helpful.

**Comment by arranf** [comment]
This is potentially related to #2722 which did not require a JS fix.

**Comment by MikeDPeterson** [comment]
yep, this is related to #2722, which is now fixed with https://github.com/SparkDevNetwork/Rock/commit/e6f3f8f7f658a59b310e454e53a1bdadbce089a2
