### ISSUE TITLE
Anniversary Date can cause confusion when Marital Status changes

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2948]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If a person has a Marital Status of _Married_ and a Anniversary Date is entered, Rock displays this as _Married 8 yrs (2/19)_ and it all looks fine. But if the marital status is changed (eg to Divorced or Single), AND the anniversary date is not manually cleared, Rock now displays a confusing _Divorced 8 yrs (2/19)_ and gives the impression that the date is associated with the status, which is untrue.

**Expected behavior:** 

Some sort of logic would come into play when changing marital status... perhaps auto-clearing the anniversary date if status is changed from married to something else. Or perhaps only displaying anniversary date when the Marital Status is Married?

**Actual behavior:** 

You see a potentially misleading Status+Date.

### Versions

* **Rock Version:** All

**Comment by ethan-sparkdevnetwork** [comment]
Edit Person UI:
If the marital status is not married then the anniversary date picker will not be visible.
If the marital status is not married and the person has an anniversary date it will update to null on save.

Person Model:
If the anniversary date has a value and the marital status is not married then set the anniversary date to null.

**Comment by dataCollegechurch** [comment]
I was noticing this issue as well but it was the result of anniversary dates imported into the system during migration. I setup a data view to isolate the records and a workflow to delete the anniversary dates. It looks like bulk update will not let you update this property at this time.
