### ISSUE TITLE
Group entity commands don't work in Lava metrics

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#2950]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
When using Lava as the source of an automatic metric, it appears that Group entity commands do not work. Interestingly, a nearly identical Person entity command does work, so it's not universal to all Entity Commands. Nathan Parikh found this issue (nathanp in Slack) and I tried to help troubleshoot it to no avail.

### Steps to Reproduce
1. Create a new metric of type `Lava` (with no partitions)
1. First, verify that entity commands work. Use the following `Source Lava`:

```
{%- assign previousSunday = 'Now' | SundayDate | DateAdd:-7 | Date:'MM-dd-yyyy' -%}
{%- assign measure = 5 -%}
{%- person id:'1' -%}
    {%- for item in personItems -%}
        {%- assign measure = measure | Plus:1 -%}
    {%- endfor -%}
{%- endperson -%}
{{ measure }},{{ previousSunday }}
```

1. Schedule the metric for a one-time schedule a few minutes ago, then manually run the job.
1. Observe that the value is correctly recorded as 6
1. Change the `Source Lava` to:

```
{%- assign measure = 5 -%}
{%- group id:'3189' -%}
    {%- for item in groupItems -%}
        {%- assign measure = measure | Plus:1 -%}
    {%- endfor -%}
{%- endgroup -%}
{{ measure }},{{ previousSunday }}
```

(use a groupId which exists. 3189 exists on demo, so it's what I used here)

1. Change the metric to a more recent time, then manually run the job again

**Expected behavior:**

The metric should again get recorded with a value of 6

**Actual behavior:**

The metric gets recorded with a value of 5

Note that storing a value of `{{- groupItems | Count -}}` results in 0, and that doing a non-mathematic operation such as `{%- assign measure = 4 -%}` inside the for loop still results in the metric getting recorded as 5. So it's like the Group command does not return any results. We also used `count:'true'` in the group command and tried returning `{{ count }}` and alternatively running `{% assign measure = measure | Plus:count %}` in the group command. Again, the output acted as though no results from the Group command were returned (storing 0 and 5 respectively in these examples)

The Lava returns the correct results when run in an HTML block, by the way.

### Versions
* **Rock Version:** 1.7.3 
* **Client Culture Setting:** EN-US

**Comment by mikejed** [comment]
@cabal95 pointed out that the issue was one of security. Groups have "All Users - Deny" permissions set (unlike person entities) so it was respecting security and not returning any results.

I'm going to add "Discussion" to this- it seems that hampering metrics in this manner may not be ideal...

**Comment by markewampler** [comment]
I can confirm this is a security issue.  Once we added "All Users" to allow the command worked fine.

**Comment by jonedmiston** [comment]
Closing as this appears to be intended behavior.

**Comment by mikejed** [comment]
Note for anyone that comes across this issue in the future, at the time of original posting, Entity commands ALWAYS respected security. Since then however we have added the `securityenabled:false` optional parameter to entity commands which would allow the metric designer to bypass this behavior if needed, so there is NO reason that any core change, enhancement, or exception needs to be added for this now.
