### ISSUE TITLE
In Registration DataView excludes anyone who registered more than once.

### ISSUE THREAD

**Issue by cbump** [SparkDevNetwork/Rock#2957]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When the In Registration DataView is used, anyone who is in the registrant list more than once is not included in the resulting query.

### Steps to Reproduce

1. Create a dataview that uses the "In Registration" filter.
2. Register the same person more than once.
3. That person won't be included.

**Expected behavior:** 

The person should be included.

**Actual behavior:** 

The person is not included.

### Versions

* **Rock Version:** Rock McKinley 7.3
* **Client Culture Setting:** en_US

**Comment by cabal95** [comment]
An unfortunate use of `== 1` instead of `> 0`.

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Reporting/DataFilter/Person/InRegistrationInstanceFilter.cs#L365

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Reporting/DataFilter/Person/InRegistrationInstanceFilter.cs#L379
