### ISSUE TITLE
Registration Attribute Error

### ISSUE THREAD

**Issue by robblehead** [SparkDevNetwork/Rock#2963]
When adding a single select, multi select, and or boolean on a registration attribute that is required the form errors with failed viewstate when trying to add another registration attribute immediately after.  

Workaround is saving in between adding another attribute to the form.

This was reproduced on the demo server.

Running version 7.3 same as demo server.

**Comment by cabal95** [comment]
I think this might already be fixed in #2890, @MikeDPeterson is this likely the same bug that you already fixed? And if so, would that fix already be on prealpha to verify against?

**Comment by robblehead** [comment]
When I did a search I did not see his specifically, am interested to know if it's the same.

**Comment by ethan-sparkdevnetwork** [comment]
It looks like this is the same issue as 2890. I checked in pre-alpha and am able to add the registration attributes without getting any errors.
