### ISSUE TITLE
[EN] Set a Known Relationship when moving people to new family

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2968]
### Description
For children in families that were originally added (as visitor), it would be helpful to automatically set the `Can Check In` relationship between that child and the original family parents.  For an adult who's moved, maybe the `Invited By` relationship would be set.

For children, I assume this would follow similar behavor as #2003, where the Family Role is changed when moving people over 18.  In general, it's much easier to delete a Known Relationship than it is to add one.

### Steps to Reproduce
1. Have a family with a visitor
1. Move the visitor to a new family
1. Expect a Known Relationship between the family
1. No relationships are created

### Versions
* **Rock Version:** v7.3
* **Client Culture Setting:** [en-us]

**Comment by edmistj** [comment]
@dcs619 how do you know that the person on the family is a visitor?

**Comment by dcs619** [comment]
That's the issue: they won't be marked as visitors and can't be targeted by a dataview.  They're just entered incorrectly from family registration or misleading info cards.

Data integrity would be the most common case to move an <18 child to another family, followed by a split/broken household situation.  In both cases it'd make sense to create a Can Check In relationship.

Rock staff would still need to manually click the "Move child" button and be responsible for final data integrity.  The code change would eliminate the extra step to add Known Relationship.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
