### ISSUE TITLE
Partially Completed SignNow Agreements showing as signed

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#2969]
Before completing your first issue we highly recommend reading this post on [[https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers) Effective Ways To Get Help from Maintainers ]().

### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

When a user fills out a SignNow agreement/waiver on an iOS device, they have the option to save a partially completed form. Since this triggers an Updated callback event, Rock is seeing this as an agreement being signed.  Rock is listening for the document.update event and if it is received with a document attached it is assuming that the document has been signed.  Rock should instead be subscribing to and listening for the document.complete event instead.

### Steps to Reproduce ###

1. Setup a signature document with multiple fields in SignNow
1. Configure the signature document in Rock
1. Send yourself a signature request through Rock for that document
1. Open SignNow email on iOS device and follow prompts to download SignNow application
1. Complete one field on the agreement and click the save button (I think it is the arrow)
1. Rock will receive the update event and will mark the agreement as signed.

**Expected behavior:**

Rock will not mark the agreement as being signed

**Actual behavior:**

Agreement is marked as being signed

### Versions ###

* **Rock Version:** 7.3
* **Client Culture Setting:** en-us

**Comment by jonedmiston** [comment]
Closing as we no longer are supporting the Sign Now integration.
