### ISSUE TITLE
Bulk update does not save tag

### ISSUE THREAD

**Issue by BemaDavidBensen** [SparkDevNetwork/Rock#2971]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    *  [ X ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * [ X ] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * [ X ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

After selecting people to bulk update, selecting a tag from the bulkupdate options menu. Nothing happens. no exceptions our thrown.

Tested on 2 clients on 7.3 and demo site.

### Steps to Reproduce

1. Bulkupdate 
2. Choose tag
3. save

**Expected behavior:** 

The person to have the tag added to their record

**Actual behavior:** 

Nothing happens 

### Versions

* **Rock Version:** 7.3
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Confirmed on Demo as well. Seems to only affect Organizational tags. I was able to apply a Personal tag without issue.

I suspect maybe this line should be `Tag` instead of `TAG`?

https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.7.3/RockWeb/Blocks/Crm/BulkUpdate.ascx.cs#L1319

**Comment by ethan-sparkdevnetwork** [comment]
Daniel was correct. Auth uses string.Contains for entity keys which is case sensitive.
