### ISSUE TITLE
Merge Field for Medical Icon has Legal Icon description

### ISSUE THREAD

**Issue by BrentPirolli** [SparkDevNetwork/Rock#2972]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Merge Field for "Medical Icon" has the same description as the "Legal Icon" description.

Displays 'L' if legal notes exist.
Displays 'M' if legal notes exist.

### Steps to Reproduce

1. Look at the Merge Field description for the Medical Icon and see it talks about Legal notes.

**Expected behavior:** 

Displays 'M' if medical notes exist.

**Actual behavior:** 

Displays 'M' if legal notes exist.

### Versions

* **Rock Version:** Rock McKinley 7.3 (1.7.3.55)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
@BrentPirolli I don't see a "Medical Icon" (or any other "Medical" fields) in the check-in merge fields list on Rock Demo, Pre-Alpha Demo or my own rock install. Is that something you added yourself maybe?

**Comment by BrentPirolli** [comment]
Well there's a good chance someone on the team before me made that then! Disregard! Thanks.
