### ISSUE TITLE
Adding/Removing of Group Meeting Detail schedule doesn't add/remove group from check-in schedule

### ISSUE THREAD

**Issue by TheArkChurch** [SparkDevNetwork/Rock#2975]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers ](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
Adding/removing a named schedule to the Meeting Details of a Group in group viewer does not auto-update the check-in configuration schedule related to that group until navigating to the particular check-in configuration, clicking the schedule button and clicking Save.
Version 7.3, tested on 3 clients (macOS, iOS, Windows 10)

### Steps to Reproduce
1. Edit Group in Group Viewer, expand Meeting Details and set Meeting Location and select/deselect schedule, then Save.
1. Open check-in via app or web and select Check-in Configuration that is configured for check-in for said group. Group is still there/not there based on removing/adding the schedule
1. Navigate to Admin Tools > Check-in > Check-in Configuration, select the Check-in Configuration that is configured for check-in for said group, then click the Schedule button.
1. In Schedule Builder page, just click the Save button.
1. Adding/Removing of group in check-in takes effect.

**Expected behavior:**

1. Edit Group in Group Viewer, expand Meeting Details and set Meeting Location and select/deselect schedule, then Save.
1. Open check-in via app or web and select Check-in Configuration that is configured for check-in for said group & group appears/disappears based on edit of schedule.

**Actual behavior:**

1. Edit Group in Group Viewer, expand Meeting Details and set Meeting Location and select/deselect schedule, then Save.
1. Open check-in via app or web and select Check-in Configuration that is configured for check-in for said group. Group is still there/not there based on removing/adding the schedule
1. Navigate to Admin Tools > Check-in > Check-in Configuration, select the Check-in Configuration that is configured for check-in for said group, then click the Schedule button.
1. In Schedule Builder page, just click the Save button.
1. Adding/Removing of group in check-in takes effect.

### Versions
* **Rock Version:** [7.3]
* **Client Culture Setting:** [Windows 10, macOS, iOS]

**Comment by TheArkChurch** [comment]
Any date on getting this fixed? It's really annoying to have to always go and save this just because Adult ministries changes a schedule on a small group.

**Comment by cabal95** [comment]
@TheArkChurch Can you test something to help narrow down the root cause?  In a Group that has this issue, edit the group and make the schedule change like normal. Then, instead of doing anything in check-in, clear the Rock cache and then see if everything is now working as expected.

When saving things in check-in there are some cache items that get cleared so it could be a simple matter of needing to clear the related cache items when saving the group as well.

**Comment by TheArkChurch** [comment]
@cabal95 I gave this a try and that worked but that still wouldn't be a solution. I guessing your just trying to pinpoint the problem?

**Comment by cabal95** [comment]
Yep. I'll take a look at this and see what cache items are being cleared.
