### ISSUE TITLE
PodcastSeriesList.lava file - changes in code breaks the lava and results in error message

### ISSUE THREAD

**Issue by hillsideassembly** [SparkDevNetwork/Rock#2976]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Something changed in the code of the PodcastSeriesList.lava file, which results in an error message on the bottom of the block, rather than the "Prev" and "Next" buttons you expect to go to the next page. From what I can tell, the only change is that spaces were added in the lava. This file can be found under \Themes\Stark\Assets\Lava but may be located in other themes as well.  I had a backup copy of this file from an older version of Rock, so I replaced the new one with that one, and the "Prev" and "Next" buttons came back and error message went away.

### Steps to Reproduce

This can be seen on the Watch page of the demo site.  At the bottom, there aren't any "Next" or "Previous" buttons but instead an error message. I had this on my site too. 
 http://rock.rocksolidchurchdemo.com/watch

**Old code:** This is at the bottom of the file, and produces the Prev and Next buttons as expected.

{% if Pagination.TotalPages > 1 %}
<div class="margin-t-lg">
  {% assign nextPageString = Pagination.NextPage | ToString %}
  {% assign prevPageString = Pagination.PreviousPage | ToString %}

  {% if {{Pagination.PreviousPage == -1 }} %}
  <div class="btn btn-default pull-left">
    <i class="fa fa-chevron-left"></i> Prev
  </div>
  {% else %}
  <a class="btn btn-primary pull-left" href="{{Pagination.UrlTemplate | Replace:'PageNum', prevPageString}}">
    <i class="fa fa-chevron-left"></i> Prev
  </a>
  {% endif %}

  {% if {{Pagination.NextPage == -1 }} %}
  <div class="btn btn-default pull-right">
    Next <i class="fa fa-chevron-right"></i>
  </div>
  {% else %}
  <a class="btn btn-primary pull-right" href="{{Pagination.UrlTemplate | Replace:'PageNum', nextPageString}}">
    Next <i class="fa fa-chevron-right"></i>
  </a>
  {% endif %}
</div>
{% endif %}

**New code:** This code has extra spaces added after and/or before some of the double curly brackets: {{  }} which may be causing the error.

{% if Pagination.TotalPages > 1 %}
<div class="margin-t-lg">
  {% assign nextPageString = Pagination.NextPage | ToString %}
  {% assign prevPageString = Pagination.PreviousPage | ToString %}

  {% if {{ Pagination.PreviousPage == -1 }} %}
  <div class="btn btn-default pull-left">
    <i class="fa fa-chevron-left"></i> Prev
  </div>
  {% else %}
  <a class="btn btn-primary pull-left" href="{{ Pagination.UrlTemplate | Replace:'PageNum', prevPageString }}">
    <i class="fa fa-chevron-left"></i> Prev
  </a>
  {% endif %}

  {% if {{ Pagination.NextPage == -1 }} %}
  <div class="btn btn-default pull-right">
    Next <i class="fa fa-chevron-right"></i>
  </div>
  {% else %}
  <a class="btn btn-primary pull-right" href="{{ Pagination.UrlTemplate | Replace:'PageNum', nextPageString }}">
    Next <i class="fa fa-chevron-right"></i>
  </a>
  {% endif %}
</div>
{% endif %}

### Versions

* **Rock Version:** 7.3
* **Client Culture Setting:** en-US

**Comment by hillsideassembly** [comment]
This is the error shown: 
Liquid error: Value cannot be null. Parameter name: input Liquid error: Value cannot be null. Parameter name: input

**Comment by garrettjohnson** [comment]
Fixed in v7.4 by https://github.com/SparkDevNetwork/Rock/commit/bd31791e757e6991e2973b82831643a279bcb00d
