### ISSUE TITLE
Cannot close batches

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#2977]
### Description

Finance batches cannot be closed in version 7.4 from the Finace / Batch screen.

### Steps to Reproduce

1. Create new Open batch
2. Try to close the batch using the drop down menu.
3. Batch does not close

**Expected behavior:** 

Batch would close.

**Actual behavior:** 

Batch does not close
https://www.screencast.com/t/sIxok45lwN

### Versions

* **Rock Version:**  7.4 Alpha

**Comment by ethan-sparkdevnetwork** [comment]
I am not able to reproduce this locally yet. In the Austin's video I noticed the "Are you sure" box did not show for either the open or close actions.

**Comment by ethan-sparkdevnetwork** [comment]
Reproduced on Chrome. Edge worked fine.
