### ISSUE TITLE
Remove Bing as a geolocation provider

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2978]
### Description
Since v7 is released to the general public and includes free geocoding through SmartyStreets, please disable the Bing geolocation provider.   Bing consistently strips apartment numbers and anything it doesn't recognize, rendering the address unusable.

### Steps to Reproduce
1. Add an address with street1 and street2
1. Bing runs
1. Address no longer has street2

**Expected behavior:**

Not have 30+ emails asking if I can restore addresses after Bing destroys them.

**Actual behavior:**

:frowning_face:

### Versions
* **Rock Version:** v7.3
* **Client Culture Setting:** en-us

**Comment by arranf** [comment]
I disagree about removing this. SmartyStreet works effectively within the US only - removing Bing removes the only free international service. That said I do think Bing _sucks_ (internationally as well) and should come with some kind of warning before enabling it

**Comment by dcs619** [comment]
@arranf Can you confirm if Bing removes flat numbers when processing international addresses?

**Comment by edmistj** [comment]
It is deactivated by default.

**Comment by chrisfunk** [comment]
I support keeping Bing as an option especially for International use, but I do believe that there is an issue with address standardization for US address.  For example Southeast Christian's address is 920 Blankenbaker Pkwy, but Bing will update to KY Hwy 913 which is not acceptable by USPS.
