### ISSUE TITLE
PublicProfileEdit assumes HoH Connection Status 

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#2986]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When adding a new family member through the Public Profile Edit block, the head of household's membership status is assumed instead of using a "WebProspsect" or other connection status instead of assuming that they inherit HoH's 

### Steps to Reproduce
_based on RockSolidDemo site_
1. Log in to public website with the _admin_  username (Alisha)
2. Browse to the My Account Page
3. Click Add New Family Member
4. Enter New Family Member
5. The new family member will have Alisha's connection status

**Expected behavior:** 

Connection status will be set to a "default" connection status that is configured in the block settings.

**Actual behavior:** 

Connection status is inherited from Head of Household.

### Versions

* **Rock Version:** 7.3
* **Client Culture Setting:** en-us

**Comment by chrisfunk** [comment]
@edmistj I have to fix it for LPC so might as well assign to me

**Comment by chrisfunk** [comment]
@edmistj  so do you think block setting? and if so should it be required or optional?  If optional should it then keep original functionality

**Comment by edmistj** [comment]
Yes I think a new Block Setting is good, "Default Connection Status" Help Text: "The connection status to use when adding new individuals to the family. If one is not provided then use the connection status of the currently logged in individual."

Does that sounds about right?

**Comment by chrisfunk** [comment]
Sounds good. Instead of keeping with the current HoH  logic use the current person's status

**Comment by ethan-sparkdevnetwork** [comment]
Added this behavior. Note there is not default for the default connection status block setting, so if it's not set the logged in person's connection status is used.
