### ISSUE TITLE
Scheduled Transactions Batch Name

### ISSUE THREAD

**Issue by BemaDavidBensen** [SparkDevNetwork/Rock#2987]
### Prerequisites
* [] Put an X between the brackets on this line if you have done all of the following:
    * [] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * [ X ] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * [ X ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

New scheduled transactions use the new defined type (Credit Card Type - Batch Name Suffix). Any scheduled transactions  that where created before 7.0 upgrade are still showing up with old batch names (Online Giving Credit Card). 

Network Merchants (NMI) 

Batch Names:
Online Giving ALL (using new suffix)
Online Giving Credit Card (old)

**Expected behavior:** 

All credit card - scheduled transactions should be created in the same batch 

**Actual behavior:** 

Scheduled transactions are split between two batches depending on when they where originally created. Pre or post Rock 7.0

### Versions

* **Rock Version:** [7.3]  
* **Client Culture Setting:** [en-US]

**Comment by edmistj** [comment]
We're pretty sure what's happening is that the newer scheduled transactions have a valid CreditCard type value, so they can get the configured "batchnamesuffix" for that CC type (which in your case is set to "All"). 

The older scheduled transactions don't have a CreditCardType, so they are getting the CurrencyType of "Credit Card" (which is what the batch creation logic does if if there is no credit card type). As far as fixing it, not sure there would be a way in code to do that unless we added a way to specify batch suffixes for currency type like we do credit card type, but that would get confusing.

If you agree, could you please close this issue, or if you have another thought feel free to share it here.

**Comment by BemaDavidBensen** [comment]
@edmistj is the CreditCardType being set by a value that NMI has? Its not something currently in Rock right? I checked all the tables but i didn't see it for scheduled transactions.
