### ISSUE TITLE
Enhancement - PublicProfileEdit Record Status

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#2988]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers ](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When adding a new person to a family through the Edit Public Profile block a person's record status is automatically set to active.  Would like to add an enhancement to the block that would allow a default record status be configured for the block, and if none is provided to use Head of Household's or the current person's status. See similar issue for connection status #2986

### Steps to Reproduce
based on RockSolidDemo site

1. Log in to public website with the admin username (Alisha)
1. Browse to the My Account Page
1. Click Add New Family Member
1. Enter New Family Member
1. The new family member will have Alisha's record  status

**Expected behavior:**

New record would use the Record Status that was configured in block settings.

**Actual behavior:**

New record using the Head of Household's record status

### Versions
* **Rock Version:** 7.3
* **Client Culture Setting:** en-us

**Comment by chrisfunk** [comment]
@edmistj if the core team approves this, i can include it with my other profile edit updates.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
