### ISSUE TITLE
Name Search fails when there are two spaces instead of one

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#2990]
### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

When a First or Last name has two spaces where there should be one, searching by Name and clicking on the tooltip that pops up fails to find the person.

### Steps to Reproduce ###

1. Create a person with a last name like "John Smith[space][space]Jones"
1. Use the Name search and search for John Smith
1. Click the John Smith Jones tooltip

**Expected behavior:**

Should go directly to the person's profile (or to a search results with all the available results if more than one person with that name exists).

**Actual behavior:**

No results are found because the search parameter in the url only has one space character where there should be two.

### Versions ###

* **Rock Version:** Rock McKinley 7.3 (1.7.3.55)
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@chrismcgrath would you be comfortable with us ensuring the last names (and first names) don't have more than one space between parts?

**Comment by cabal95** [comment]
Confirmed. Just to add a little more clarity (step one was a bit unclear).  I created a person with First Name = `Daniel` and Last Name = `Hazel<space space>Baker`.

If I search for `Dan Hazel` and hit enter, I go to the search results page and can see the target person (this works).

If I search for `Dan Hazel` and click the matched name in the drop down to take that full name, it does not work.

For reference, if the last name is `Hazel<space>ba<space>ker` the search works as expected. I would suspect that somewhere it's doing a string split by ` ` and then joining them back, thus losing the extra space.

**Comment by jonedmiston** [comment]
Would an acceptable fix for this be to:
1.) Update the person save to convert double spaces to single spaces
2.) Update the clean-up job to do the same.

Seems like this is a case of 'bad data' so it would be best to keep it from occurring.

**Comment by chrismcgrath** [comment]
Seems reasonable to me!

**Comment by jonedmiston** [comment]
Solution:

Would an acceptable fix for this be to:
1.) Update the person save to convert double spaces to single spaces
2.) Update the clean-up job to do the same.
