### ISSUE TITLE
Bizarre image issue when pasting from (Mac) Word into Chrome

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2994]
### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

Under very specific circumstances, copying text from the OSX version of Word and pasting it into Chrome will cause an _image_ of the pasted text to be generated and inserted into any File/Image attributes on the same form. This is most easily seen when pasting into an item in the default Website Blog content channel as it already has a single Image attribute.

### Steps to Reproduce ###

1. Open a document in Word on OSX. (both 15.37 and 16.13 are what I tried, and both had same behavior) and copy the text to clipboard.
1. Using Chrome, Go to Utility | Content | Website Blog on a default Rock install, or any other content channel that has an Image attribute. 
1. Add a new content channel item, and paste your copied text into the Content box. Observe that your Image attribute now has an _IMAGE_ of the content you just pasted uploaded into it?!?
1. If you happen to have multiple image attributes, observe that ALL of them get an image of the content.
1. Observe the Twilight Zone music playing in your head.

**Expected behavior:**

Pasting any text into a content channel item would not create an image of that content and place it into all Image attributes on the item.

**Actual behavior:**

Weird stuff happens. As far as I've been able to determine, this ONLY occurs when copying from Word on OSX (couldn't induce it when copying from Word 16.0.9126 on Win10, or from any other non-Word text source) and pasting into Chrome (couldn't induce it on FF or Safari). 

Even stranger, since I'm in a virtual environment I _could_ induce the problem when copying from Word on OSX and pasting into Chrome _on Win10_. So the sole trigger seems to be copying from Word (on OSX) and pasting into Chrome (on any OS). Also note that this happens regardless of just pasting into the Content box vs. using the "Paste from Word" function.

This is a growing problem for us because we use content channels with images all over the place, and the people in charge of that content are generally on Macs, often getting copy via Word they need to copy/paste. 

As for Rock versions, I was able to reproduce it on our 6.9 prod, Rock demo, and prealpha sites.

### Versions ###

* **Rock Version:** v6.9 through v8prealpha

**Comment by JimMichael** [comment]
![paste from word](https://user-images.githubusercontent.com/3903408/40129635-68ee45f8-58fa-11e8-868b-dc59a5ac2c91.jpg)

**Comment by nairdo** [comment]
@MikeDPeterson Here is a animated gif showing the problem using Excel on the person edit page (via the prealpha server).  We (here at Central) were able to finally reproduce on demand when one of our users did it while we were watching.

![20180625-153752_capture](https://user-images.githubusercontent.com/383807/41879356-24a069c2-788e-11e8-83d8-8d66ad555694.gif)

If the user presses save, then the photo of the person they are editing is replaced with a very small square version of part of the email text-as-an-image.

**Comment by JimMichael** [comment]
Just wanted to confirm this still happens as of 8.3

**Comment by bmurphy-dev** [comment]
I've also seen this issue on several instances. It also happens when pasting in a new Email type Search Key value and it wipes out the current person's profile photo even if you cancel the weird image crop dialog. I can upload a video of a similar process that Jim was showing but with the search key. I wouldn't mind it if it didn't wipe out the existing photo on the record. I've seen this in a wide range of instances but recently in the v11 era when pasting from excel on windows.
I do find that this won't occur if you copy/paste the data from the formula bar itself and not copy/paste the cell that the information is in.
