### ISSUE TITLE
Desire ability to schedule group attendance reminders (on and off)

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2995]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Enhancement request. Our Life Groups take breaks throughout the year between series, as well as over the summer. Currently we (the admins) have to turn the job off an on multiple times through the year. We would like to offload this to the Life Groups team. Below is a concept for how to do this without giving them admin access to the job listing.

Add a job setting for "Schedule" (name TBD). If set, this schedule determines when the job does it's real processing. Pseudo logic would be:

```
If Has Schedule Then
    If Schedule Is Active Then
        Process
    Else
        Set status message = "Disabled by schedule"
        Exit
    End If
Else
    Process
End If
```

The Schedule itself would be setup something like:

* Start Date Time = 1/1/2018 00:00 AM
* Duration = 24 hours
* Recurrence = Daily every 1 days
* Continue Until = No End
* Exclusions
* * 7/1/2018 - 7/30/2018

From this, we could give them access to edit that schedule without giving them access to the entire job list, and they could schedule ahead of time when the breaks are.

Thoughts? Feedback?

### Versions

* **Rock Version:** 7.3
* **Client Culture Setting:** en-US

**Comment by dcs619** [comment]
Instead of a Job scheduling change, would it be easier to let Group Leaders set their own schedule exclusions from GroupDetailLava?

**Comment by cabal95** [comment]
I don't think so. We don't want them to be able to turn off reminders themselves, otherwise they'll turn them off just so they stop getting e-mailed to take attendance.

**Comment by edmistj** [comment]
The Jobs system runs on Quartz which uses cron syntax. Changing that seems dangerous. Schedule categories also allow for creating exclusions (add to support just this use-case). Would setting the exclusions on the category fill the need?

**Comment by cabal95** [comment]
Sorry I probably wasn't very clear. We wouldn't be changing the actual "cron schedule syntax" or anything. The job would still _run_, but then check an optional secondary attribute value (setting) that contains a Schedule Guid. The job would lookup the Rock schedule associated with that Guid and then determine that schedule is active.

Not sure if setting an exclusion on the schedule category would help here, as the job would still need to be tied to a Rock schedule for it to take effect?

**Comment by edmistj** [comment]
Researched this a bit more. Each group type has the ability to set exclusions. The job has logic to respect these exclusions. That should work, right?

![image](https://user-images.githubusercontent.com/548178/40150689-09182834-5930-11e8-8328-442c14a19bec.png)

**Comment by cabal95** [comment]
Does the Job currently honor that setting, or would that need to be added?

That might do what we need. I would need to find someway to allow the Life Group team to edit just that one group type so they could put in the schedule exclusions, but that should be doable (Administrate security on that group type I think?).

Thanks for looking into it further.

**Comment by edmistj** [comment]
The job does honor that setting.

**Comment by cabal95** [comment]
Great, I think that will do it. I'll research a bit more tomorrow and close this if we are all set. Wish I would have asked sooner. This has been bugging us for a year. 🤦‍♂️
