### ISSUE TITLE
&copy; and &trade; get converted when they shouldn't

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2996]
### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

When crafting an e-mail (or anything else using the WYSIWYG editor), if you enter `&copy;` or `&trade;` in the code editor, then switch to the "preview" editor and then back, the text is replaced with the actual symbols instead remaining as the HTML codes.

### Steps to Reproduce ###

1. Create HTML block
1. Make sure you are in code editor mode
1. Enter `&trade; &copy; &amp;`
1. Switch out of code editor
1. Text has become "&trade; &copy; &amp;" (correct)
1. Switch back to code editor.
1. Text becomes "&trade; &copy; &amp;amp;" (incorrect)

**Expected behavior:**

HTML codes should remain.

**Actual behavior:**

HTML codes get replaced with actual characters.

### Versions ###

* **Rock Version:** 7.3
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Adding additional note on this...

The reverse happens with `&amp;`.  So if you are in the code editor and put `<a href="http://.../GetFile.ashx?id=123&attachment=true`, then switch to the WYSIWYG editor and back to code, the `&` has become `&amp;` in the code editor (which is not correct), and you end up with: `<a href="http://.../GetFile.ashx?id=123&amp;attachment=true`

**Comment by cbump** [comment]
This same issue can be reproduced on the summernote demo on their website https://summernote.org/ and it is reported here: https://github.com/summernote/summernote/issues/1937

I'm not sure it makes sense to keep this open unless we are planning to fix it and PR it back to summernote . . .

**Comment by jonedmiston** [comment]
Confirmed this is still an issue on Summernote's website. Not much we can do to fix. Will be switching WYSIWYG editors for NextGen.

**Comment by joshuahenninger** [comment]
We have confirmed that this issue is resolved in the Obsidian HTML Editor control in the Next Generation framework. 

Regarding the second point:
> The reverse happens with &amp;. So if you are in the code editor and put <a href="http://.../GetFile.ashx?id=123&attachment=true, then switch to the WYSIWYG editor and back to code, the & has become &amp; in the code editor (which is not correct), and you end up with: <a href="http://.../GetFile.ashx?id=123&amp;attachment=true

The new WYSIWYG editor also escapes & in the href, and that is valid HTML. Clicking a link with an escaped & works in browsers and email clients.
