### ISSUE TITLE
Add additional options to DateAdd filter

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3001]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The `DateAdd` filter allows you to modify a date by a number of seconds, minutes, hours or days. However, if you need to adjust a date by a number of months or years, you are kind of out of luck and must roll your own custom logic. Enhancement would be to add options for:

* Week (might as well)
* Month
* Year

Currently, the qualifier letters for what kind of adjustment to make are case sensitive. So we can either:

1. Add the above as `w`, `M` and `y` respectively. This would give us the following qualifier letters (case sensitive): `s`, `m`, `h`, `d`, `w`, `M`, `y`.
2. Move towards full word names, case insensitive, and keeping aliases for the current ones. This would give us `s/second`, `m/minute`, `h/hour`, `d/day`, `week`, `month`, `year`.

I can submit the PR for this, as long as somebody gives me guidance on which method to implement. I'm not sure I'm really partial to either, they both have pluses and minuses.

### Use Case

I was trying to modify a date in Lava to be the "end of this month" (i.e. 5/31/2018). Since I don't know how many days are in each month, my easy solution was going to be to do something like `{% assign endOfMonth = 'Now' | Date:'yyyy-M-01' | DateAdd:'month',1 | DateAdd:'d',-1 %}` but then found I couldn't add a full month.

I'm doing the logic by hand now, but it's a bit tricky dealing with year rollovers (if month > 12, month -= 12, year++ etc.)

### Versions

* **Rock Version:** 7.3
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
For consistency, I think option #1 would be best.

**Comment by cabal95** [comment]
Sounds good. I'll work on this today. Do you want me to update the docs now too? And if so would this be a v8 item?

**Comment by edmistj** [comment]
Yes, please update the docs. You might also note the use case that 5/31/2018 +1 month = 6/30/2018. That was my first question.

This would be for v8 (so you might also document the new items are starting at v8).
