### ISSUE TITLE
WorkflowActivate Lava command requires lowercase attribute keys

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3003]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The `{% workflowactivate %}` command requires that any attribute values it sets be all lower-case keys. The reason for this is the `ParseMarkup` method it uses converts all key names to lower case before returning them, thus the case is lost when we try to find an attribute that matches that key name.

### Steps to Reproduce

1. Create a workflow with 2 attribute key names: `Value1` and `value2`
2. Activate the workflow with `{% workflowactivate workflowtype:1 workflowname:'test' Value1:'one' value2:'two'
3. Go look at the workflow and notice that only `value2` got set.

**Expected behavior:** 

Command should not modify the case of the returned parameters. Instead, if a parameter needs to be checked without regard to case, the check statement should handle that.

**Actual behavior:** 

key capitalization is modified and attributes cannot be set.

### Versions

* **Rock Version:** 7.3, 8.0
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
So if we internally did a case-insensitive compare to find the attribute via the key that would be an acceptable solution. Correct?

**Comment by cabal95** [comment]
I'm not sure it would. You can have two attributes with the same key as long as the case is different. For example, it's perfectly legal to have the following two attribute keys in a single workflow:
* Type
* type

Users are already expecting attribute keys to be case sensitive, since they are. So I think it makes sense to just take the user's input as is instead of doing a `.ToLower()` on it. Looking at the code, I don't see any specific reason for it to do a `.ToLower()` inside the `ParseMarkup` method. We just need to do a `.ToLower()` when checking for the specific keys like `workflowtype` (which are not attribute keys, but rather identifier for which workflow type to instantiate).

**Comment by edmistj** [comment]
We discussed this and would like to make attribute keys case insensitive. I'm not sure people are expecting that behavior, even though it exists. For now we can remove the `.ToLower()` on the parse markup to get this working (partially).  We'll also add an item to the technical debt project list to see if we can refactor to allow for case-insensitive key matching.

**Comment by arranf** [comment]
@edmistj I agree, people expect keys to be insensitive based on my experience.

**Comment by tikool17** [comment]
@jonedmiston @cabal95 digging this back up as it seems v16 has changed some behavior here. Our workflowactivates with uppercase attributes stopped passing values when we upgraded to v16. Broke quite a few things for us.

This doesn't pass a value for Person:
{% workflowactivate workflowtype:'389' Person:'{{CurrentPerson.PrimaryAlias.Guid}}' %} {% endworkflowactivate %}

This does:
{% workflowactivate workflowtype:'389' person:'{{CurrentPerson.PrimaryAlias.Guid}}' %} {% endworkflowactivate %}

Confirmed on the demo site (which is still on 15.1 as of today) that uppercase does still work. I was pulling my hair out and then found this recent release note from a Room Management plugin we use:
<img width="867" alt="Screen Shot 2023-10-24 at 1 59 19 PM" src="https://github.com/SparkDevNetwork/Rock/assets/32227063/5f7fd3d7-5a78-4c24-9713-903a3b8650ec">

If this is a feature and not a bug, where would I find info on breaking changes like this? I just don't want to miss them in the future. Thank you

**Comment by OnlyByGrace** [comment]
@jonedmiston @cabal95 I echo that this seems to have resurfaced in v16.

**Comment by MichaelAllen** [comment]
I think [this commit](https://github.com/SparkDevNetwork/Rock/commit/97b925ed37096e9a52371c77a0a5b2f14e7885c6) reintroduced this issue. Specifically [this change](https://github.com/SparkDevNetwork/Rock/blame/97b925ed37096e9a52371c77a0a5b2f14e7885c6/Rock/Lava/LavaElementAttributes.cs#L451) in ParseFromMarkup that is forcing all keys to be lowercase.
