### ISSUE TITLE
[EN] Service Metric Entry Block Support Metrics With Fewer Partitions

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#3005]
### Description

[River Valley Church](http://rivervalley.org/)  requested a modification the Weekly Metric Entry block to support metrics with single or no partitions so weekend metrics not associated to a schedule or campus could be recorded in the same UI.

I've adjusted the EF to have conditions for fewer than two metric partitions.

In the end, the metric entry tool works as before, with the added ability to support any metrics without a campus or a service partition.

### Affected Files

* `RockWeb/Blocks/Reporting/ServiceMetricsEntry.ascx.cs`

**Comment by nairdo** [comment]
Jon and I talked about this today.  The current block (named ServiceMetricsEntry) is specifically intended for entering metrics for a service (schedule).

Feel free to create a custom/plugin block for your customers/churches that have a need for non-partitioned metric entry (although that's basically what the regular, Blocks/Reporting/MetricValueDetail, block does already).
