### ISSUE TITLE
[EN] Locations Check-In Manager Enhancements

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#3006]
### Description
Several churches have requested a series of modification the Locations Check-In Manager.  The search by code was accepted last year.  In addition, I've added Move, Check-Out, Reprint Label, and Only Show Active Locations.

There are block settings to accommodate all these features as well as ability to adjust the lookback window for the graph (and Active Location setting).

#### Move
Provides a location picker and option to change the location associated to the check-in.

#### Check-Out
Sets the EndDatTime of the attendance. (Note, not tags are auto-printed.)

#### Reprint Label
Presents a drop down list with labels for the current group and a view button which returns a Labelary PDF for printing via local print queue.

#### Only Show Active Locations
To clean up the list of Locations for churches with large facilities, this option will only show Locations which have a current (or in the lookback window) schedule associated with them.

### Affected Files
* `Rock/RockWeb/Blocks/CheckIn/Manager/Locations.ascx`
* `Rock/RockWeb/Blocks/CheckIn/Manager/Locations.ascx.cs`

**Comment by nairdo** [comment]
@treyhendon If you haven't already written the code, can you provide some mockups so we can get an idea of what it would look like.  In general the more detail you can give up front the better this will be.

![image](https://user-images.githubusercontent.com/383807/40793772-28e2301e-64b2-11e8-93b7-abdd9532cb4f.png)

**Comment by nairdo** [comment]
Hey @treyhendon I realize Label Reprinting is now in v9, but you might consider breaking the other items up into individual "Ideas" over at the new- _ish_ community ideas site here: http://community.rockrms.com/ideas

That way it can be put it up to the voting process.  Thanks!
