### ISSUE TITLE
[EN] Fundraising Toolbox Enhancements

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#3008]
### Description
Several churches requested modifications to the Fundraising Toolbox.

* Ability for Fundraising Donation Entry block (drop down picker before Transaction Entry) to support Group Types which inherit from the Fundraising Group Type. 
* Additional Lava Items for the Leader to return the total amounts needed and outstanding for the group as a whole.
* Additional Column options for the Leader to see Funding Goal and Funding Total Columns in addition to the Funding Remaining column (with settings to show/hide each).
* Ability to show the person attributes referenced in #3007 
* The ability to hide the donation amount in the grid for the Fundraising Participant.

### Affected Files
* `Rock/RockWeb/Blocks/Fundraising/FundraisingDonationEntry.ascx.cs`
* `Rock/RockWeb/Blocks/Fundraising/FundraisingLeaderToolbox.ascx`
* `Rock/RockWeb/Blocks/Fundraising/FundraisingLeaderToolbox.ascx.cs`
* `Rock/RockWeb/Blocks/Fundraising/FundraisingParticipant.ascx.cs`

**Comment by nairdo** [comment]
We haven't heard of these requested modifications from several churches yet.  (We recommend individuals submit their ideas using the _Submit Ideas_ link on the footer of the rockrms.com as they come along.)
![image](https://user-images.githubusercontent.com/383807/40800717-ff2a9130-64c5-11e8-9193-e6f67689e42d.png)

Please provide details on the first three items (and screenshots if you have them).

**Comment by treyhendon** [comment]
With the adding of `ICustomGridColumns` some of the needs of this enhancement has shifted (person attributes).  Would it be better to close this and start a new thread or to restate and include the proposed PR screenshots and pieces here?

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
