### ISSUE TITLE
[EN] GroupDetailLava enhancement - Edit Group Capacity

### ISSUE THREAD

**Issue by nateh777** [SparkDevNetwork/Rock#3010]
**Description**
Venture Christian Church requested a modification to the Group Detail Lava block to be able to have the group leaders have the ability to edit the Group Capacity.

I have added an additional setting to enable/disable it the same as every other field in that block and added the new field. It was already accessible in the Lava so no need to add that unless desired.

**Affected Files**
RockWeb/Blocks/Groups/GroupDetailLava.ascx  
RockWeb/Blocks/Groups/GroupDetailLava.ascx.cs

**Comment by nairdo** [comment]
Sounds good. Thanks for the write-up.  Default the new block setting to _disabled_ to match current functionality.  

Also remember... when block settings are added to a block type, code for the migration should be included which adds the new block attribute (ie, [RockMigrationHelper.UpdateBlockTypeAttribute](https://www.rockrms.com/Rock/Developer/BookContent/17/17#datamigrationhelpermethods)). Example: the [AllowGroupMemberDelete](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Migrations/Migrations/Version%207.0/Version%201.7.1/201801121251097_InteractionBlocks.cs#L505) setting migration.
