### ISSUE TITLE
Following Suggestion | In Group Together | Suggests Inactive Group Participants

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#3011]
### Description

The following suggestion type "In Group Together" suggests that individuals follow people who are both inactive and active in a group type / group - instead of just those that are active. 

**Expected behavior:** 

You would be able to pick what group status options are included in following suggestions (inactive, pending, active, etc)  

OR

It would just not suggest you follow people who are inactive in a group.

**Actual behavior:** 

Suggests you follow people who are both active and inactive in a group type. 

### Versions

* **Rock Version:** 7.3 and 7.4

**Comment by austinspooner** [comment]
Link to code: https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Follow/Suggestion/InGroupTogether.cs

**Comment by ethan-sparkdevnetwork** [comment]
Inactive group members will not be included in the following suggestions.
