### ISSUE TITLE
Person Follow Add Action Bug

### ISSUE THREAD

**Issue by matthewalanwhite** [SparkDevNetwork/Rock#3012]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
We are unable to follow a person entity from the **Person Follow Add** action. These are the fields we’ve set:

* "Volunteer" being a **Person** field type of the person who wants to follow.
* "Person" from the list of entity types.
* "Guest Name" being a **Person** field type of the entity to follow

![image](https://user-images.githubusercontent.com/24526905/40362254-049bb528-5d9a-11e8-9165-8573b2afa9ec.png)

We also tested using Lava getting the **Person Id** in the Entity to Follow box, and setting an attribute with the Person Id, we still were not able to follow.

### Steps to Reproduce
1. Create a Person Follow Add action
1. Set a person to do the following
1. Set the entity type
1. Set the entity to follow

**Expected behavior:**

A person to follow another person

**Actual behavior:**

Nothing. We did not receive any errors, and the workflow continued processing, but the volunteer did not follow the guest.

![image](https://user-images.githubusercontent.com/24526905/40362507-b35a4e76-5d9a-11e8-8348-05866a9860f1.png)

### Versions
* **Rock Version:** Rock McKinley 8.0 (1.8.0.15)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Fixed via https://github.com/sparkdevnetwork/rock/commit/94d9687dfa22df15779dcb355f7071130dffd775
