### ISSUE TITLE
Enhance RockPage Search Related Settings

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3016]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

> **TL;DR** I think Rock could provide some additional Page settings to help CMS admins have more control over SEO.

With the addition of Universal Search and the built-in Site Crawler (not to mention external crawlers like Google), I think the RockPages could use some TLC with providing some additional search settings. I can/will provide a more specific recommendation in a comment later, but to start with want to get feedback on initial thoughts and see if anybody has any other additional recommendations.

1. New Tab in Page Settings (`Search Settings`)
2. Move `Allow Indexing` to this tab.
3. Change `Allow Indexing` to only set the `noindex` option in the `<meta name="robot" content="...">` tag.
4. Add new `Follow Links` setting that, if disabled, sets the `nofollow` option in the `<meta name="robot" content="...">` tag. (To keep current functionality, a migration would run that sets `Page.FollowLinks=Page.AllowIndexing`)
5. Add new `Keywords` text field setting that sets the `<meta name="keywords" content="...">` tag.
6. Provide a way for admins to add keywords via Lava. (See note 1 below)

This should provide much greater flexibility without, I hope, adding too much complexity to customizing the Search Engine Optimization settings for a page. We don't necessarily need a new tab for this, I'm just assuming a couple more options would be added down the road.

I think most of these changes would be pretty straight forward to add - with the exception of the migration, and even that shouldn't be too bad. So I would be willing to submit a PR if this gets a green light and we get a consensus on exactly what pieces to add.

Note 1: Currently, the `AddMetaTagToPage` filter _always_ adds a new tag. I'm assuming we shouldn't be adding multiple tags with the same `name=` attribute. i.e. I'm assuming it's not valid for a page to have two `<meta name="keywords" content="...">` tags in the page. If that is indeed the case, then I think `AddMetaTagToPage` should do one of:
1. Always look for an existing matching tag and append the content with `AddMetaTagToPage`
2. Add a parameter ` AddMetaTagToPage` that instructs it to append the content to an existing tag if found.
3. Add a new Lava filter to add keywords to the page (by doing the above automagically), `AddKeywordsToPage`.

Thoughts? Suggestions? Criticisms? 

### Versions

* **Rock Version:** 8.0, 9.0?
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@cabal95 we have a lot of CMS updates we'd like to add. I think it would be best to incorporate all of the ideas into one collaboration so we're strategic in their implementation. We're heads down right now pushing to get v8 out to alpha. I recommend we circle back in 3-4 weeks to re-engage this topic.

**Comment by cabal95** [comment]
I'm good with that. Do you want to leave this open for re-circling, or close it and just search it up later?

**Comment by edmistj** [comment]
Let's close it so we can reduce the count of open issues and we'll create a wider scope one in a few weeks.
