### ISSUE TITLE
Hiding Attribute Label in User Entry Form does not hide help text

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3018]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
There is an option to hide an attribute's label in a Workflow User Entry Form action, but the helptext (blue ? icon) is not hidden as well.

### Steps to Reproduce
1. Go to a workflow with a User Entry Form action
1. Check the _Hide Label_ box on an attribute (must be one that has a description, to ensure the helptext ? icon appears)
1. Observe that while the attribute label is hidden, the helptext icon is not.

**Expected behavior:**

The helptext icon would be hidden when an attribute label is set to be hidden.

**Actual behavior:**

You get the helptext icon showing, and in a weird place.

### Versions
* **Rock Version:** 6.9 - 8.0

![image](https://user-images.githubusercontent.com/3903408/40433376-81587fe2-5e71-11e8-80ea-4e7cc8a7b319.png)

**Comment by JimMichael** [comment]
Grrr.. I just realized this is probably working as designed behavior. It just looked so weird I assumed it was wrong. Go ahead and close if that's the case.

**Comment by edmistj** [comment]
Open to input on this. If one hides the label would you also want the help text hidden? If you do want it displayed is this where you'd want it to appear?

**Comment by cabal95** [comment]
Is the `Description` of a workflow attribute used anywhere else? If not it seems like leaving functionality as is would make the most sense since you could just remove the Description.

**Comment by JimMichael** [comment]
I can see an argument for leaving the help text (after all, the setting is only "hide label"), but what threw me is the _placement_ of the help text, which goes below the input when the label is hidden. I think at the very least that should stay above the input, like a normal (non-hidden-label) field does.
