### ISSUE TITLE
Death/Relashionship

### ISSUE THREAD

**Issue by kaHoffmann** [SparkDevNetwork/Rock#3019]
I have created a report that pulls all persons that have passed away with in the past year.  On this report I wanted to list Spouses name in one column and than related people in another.  Nothing appears in either of these columns.  I am really focused on those who are related.  Purpose and need is that we offer a bereavement class and I would like to know who is related to the deceased person.  it seems once I make them inactive due to death the relationships end.  Running Rock McKinley 7.3. 

-->

### Prerequisites
[ X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [Rock McKinley 7.3](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

[Description of the bug or feature. Include screenshots if applicable.]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** 

[What you expected to happen]

**Actual behavior:** 

[What actually happened]

### Versions

* **Rock Version:** [Enter Rock version here]  
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by edmistj** [comment]
@kaHoffmann You might ask this in our Slack community (http://rockrms.com/slack). Issues here are for bugs or specific feature requests.
