### ISSUE TITLE
Stock parent label name/code columns are too narrow

### ISSUE THREAD

**Issue by lpeterson1** [SparkDevNetwork/Rock#3020]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The columns for names (or ages) and codes on the parent label are too narrow, so data that should be on one line wraps unnecessarily and doesn't take advantage of all the space.

### Steps to Reproduce

1. Check at least three family members (with long first names) in at once, using the stock parent label.
2. Note that the columns are narrow and wrap when they don't need to.

**Expected behavior:** 

The lines take advantage of all the space and don't wrap.

**Actual behavior:** 

The lines are narrow and wrap when they don't need to.

In the picture the right labels were printed with the existing label code, and the left after widening the columns to 300 dots.

These two lines in the label need to be changed:
^FB200,7,0,L^FT30,390^A0N,39,38^FD1^FS
^FB200,7,0,L^FT415,390^A0N,39,38^FD2^FS

Both ^FB commands should be changed to ^FB350,7,0,L

I tested 350 dots wide and they work fine.

### Versions

* **Rock Version:** All
* **Client Culture Setting:** en-US
![image uploaded from ios](https://user-images.githubusercontent.com/37701239/40555064-219bfd78-6005-11e8-88e3-a6a9b40fb33c.jpg)

**Comment by cabal95** [comment]
You can also see the issue on the demo site by using the "preview" function when editing a label contents, as seen below:

![image 1](https://user-images.githubusercontent.com/1119863/40555788-0f8142d4-5fff-11e8-8674-f772951f5a49.png)

A migration would probably be needed to apply this fix.

**Comment by lpeterson1** [comment]
I have one more label fix to request (and I know I'm being picky). Since the new icon font is scalable, and the icon size parameters in the child icon label are "73,64", the icons are compressed horizontally a little. The star is quite obvious. I'd like to see the four icon lines (that start with "CWZ..." changed to "^AZN,73,73". This doesn't change how the icons print with the old font, since it's not scalable. I'm happy to start a new issue if you need me to. Or let it go. :-)
![img_2931](https://user-images.githubusercontent.com/37701239/40567538-fd6ff4f8-6032-11e8-91b1-d6bb3708046b.jpg)

**Comment by edmistj** [comment]
Good catch! I think a separate issue would help ensure we don't miss this second item.

Appreciate all your efforts!!!

**Comment by ethan-sparkdevnetwork** [comment]
Created migration to increase the column size.
