### ISSUE TITLE
Icon sizes on child icon label need adjusting

### ISSUE THREAD

**Issue by lpeterson1** [SparkDevNetwork/Rock#3025]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Since the new icon font is scalable, and the icon size parameters in the child icon label are "73,64", the icons are compressed horizontally a little. The star especially is quite obvious. See picture below.

### Steps to Reproduce

1. Install the new updated Rock icon font
2. Print a child icon label
3. Notice that the star isn't proportioned correctly. It's narrower when printed with the new font.

**Expected behavior:** 

Print a nice-looking star (and other icons).

**Actual behavior:** 

The icons appear to have been squeezed in a font vise.

The four icon lines (that start with "CWZ...") should be changed from "AZN,73,64" to "^AZN,73,73" so the icons print correctly. This is a result of the new icon font being scalable, and the old font was not. Icons will still print correctly with the old font after the label is changed. 

![img_2931](https://user-images.githubusercontent.com/37701239/40579435-5b1d49a0-60e4-11e8-967f-ef2b7232e54b.jpg)

### Versions

* **Rock Version:** all
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
Created migration to adjust icon size to 73,73.
