### ISSUE TITLE
Universal Search Crawler should (probably) respect Site Domains settings

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3029]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Currently, when the Index Site job runs, the crawler will only follow URLs that _exactly_ match the hostname of the starting point URL. So if you set your starting index location to `http://www.rocksolidchurchdemo.com/` and then one of your links is `http://rocksolidchurchdemo.com/page/123`, that link will not be followed even though both are listed as allowed domains in the Site configuration.

Most of our links are correct, but in troubleshooting why our 4th of July page did not show up in search results I found that it had been linked to as `http://shepherdchurch.com/4th` instead of `http://www.shepherdchurch.com/4th`. I have fixed this, but I think the crawler should still see that those two domains are for the same site.

Suggested fix:

1. Crawler should make a list of all allowed domains from the Site configuration and allow all of those to be followed in links.
1. (Optional?) Job should have a True/False setting to rewrite URLs before they are followed to match the primary domain (that is, the domain used with the starting URL link entered in the job).

As for the second item, my thinking is that the logic would be this:

1. Make list of allowed domains (`www.shepherdchurch.com` and `shepherdchurch.com`)
1. Start on page `http://www.shepherdchurch.com/`; from that set the _PrimaryDomain_ to `www.shepherdchurch.com`
1. See a link for `http://shepherdchurch.com/4th`, check to see if it is in allowed domains (yes).
1. Rewrite the URL as `http://www.shepherdchurch.com/4th` to match _PrimaryDomain_.
1. Add URL to the queue to be indexed (this ensures that we can reach the page at the re-written URL before indexing it).

### Steps to Reproduce
1. Configure external site with `www.rocksolidchurchdemo.com` and `rocksolidchurchemo.com`
1. Create link on homepage of external site to `http://rocksolidchurchdemo.com/page/123`
1. Setup Site Index job to use `http://www.rocksolidchurchdemo.com/` as the starting url.

**Expected behavior:**

Page `123` to be indexed as it's on the same site.

**Actual behavior:**

Page is not indexed because the crawler thinks its a different site.

### Versions
* **Rock Version:** 7.3
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Just noticed it also requires the scheme (`http` vs `https`) to be the same. I'm not sure I can think of a reason to not also use the same scheme as the original url.

**Comment by edmistj** [comment]
I think adding support for #1 is good. I'd not implement #2 as I don't think we should re-write the URL. Ignoring the difference in the scheme (http / https) is also a good change.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
