### ISSUE TITLE
Batch Control Amount Cannot Be Negative

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#3030]
### Description
In 7.4 beta the control amount of a batch cannot be set to a negative.

### Steps to Reproduce
1. Use the UI to refund a transaction
1. Go to the refund batch and attempt to close/save
1. The batch control amount is changed to a negative number the batch will not close

**Expected behavior:**

The batch should close.

**Actual behavior:**

The control amount is changed from negative to positive and the status will not change to closed.

### Versions
* **Rock Version:** Rock McKinley 7.4 (1.7.4.57)
* **Client Culture Setting:** en-US

**Comment by KelleyLangkamp** [comment]
I think these are related. If not, I can open a new issue. We also can't enter a new transaction with a negative amount. We are trying to do a manual refund by creating a new transaction, entering the negative amount and checking the "This is a refund" box. The negative gets stripped off the transaction amount when it is saved.

**Comment by edmistj** [comment]
@KelleyLangkamp I think that would be separate code so it would be best to have a different issue to help manage the process. Do you mind opening one?

**Comment by KelleyLangkamp** [comment]
@edmistj I opened a separate issue https://github.com/SparkDevNetwork/Rock/issues/3040

**Comment by edmistj** [comment]
Thanks @KelleyLangkamp !

**Comment by jsw-austin** [comment]
seems this is no longer an issue. tested on demo site and it allows me to close the batch and keeps the control amount negative. Can be closed?

**Comment by nairdo** [comment]
Reported as resolved (in v9.x) in the #bugapalooza channel.

```
Jeff Ward 2:45 PM
#3030 apparently has been fixed since reported.
```

Please let us know by reopening if you feel this is closed in error.
