### ISSUE TITLE
[EN] Add Lava filter for calculating distance between locations

### ISSUE THREAD

**Issue by johnellmore** [SparkDevNetwork/Rock#3033]
It'd be helpful to have a simple Lava filter that allows calculating the distance between two locations in Rock.

**Steps which explain the enhancement**

Adding a new filter to the `Rock.Lava.RockFilters` class which calculates the euclidean (as-the-crow-flies) distance between two `DbGeography` objects. This can leverage the existing `DbGeography.distance` method.

**Current and suggested behavior**

Currently, there's no easy way to get a distance between two locations without using inline C# in Lava. I'd suggest the following behavior:

Usage:

```
{{ Location1 | DistanceTo:Location2 }}
```

Example (finding a person's distance to their primary campus):

```
{{ Person | Address:'Home','[[ GeoPoint ]]' | DistanceTo: Person.Campus.Location.GeoPoint }}
```

`DbGeography.distance` [returns the distance in meters ](https://stackoverflow.com/a/13934863/5651536) by default. I'd probably stick to meters because of that. But considering that many/most Rock churches are US-based, it may make more sense to return a value in miles.

This would return a `double?`. If one or both of the arguments are are null or not `DbGeography` instances, the filter would return null.

**Why would the enhancement be useful to most users**

Some usage examples:

* A "new visitor" workflow could determine how far away someone is from their visited campus, and use that to determine follow-up strategies. This is actually my primary reason for the request.
* A report could identify lawn-mowing volunteers nearby to people who have recently suffered a loss.
* A report could target people nearby to a block party for so they can be mailed flyers.

**Next steps**

I've written some very poor-quality C# which does this. I'm happy to clean it up and submit a pull request. I'm new to C# in particular, but this seems like as good a starting point as any. 

Props to @mikejed for the suggestions and pointers on Slack.

**Comment by mikejed** [comment]
Note that sample uses 2 and 3 can actually be done already, since `Distance From` is an existing filter in DataViews. But I do think that being able to calculate distance in Lava could be beneficial.

**Comment by cabal95** [comment]
I would suggest using the term `DistanceBetween` as the filter name, since the returned value doesn't care if it's "from" or "to", the distance is the same.

**Comment by edmistj** [comment]
Sounds good. Would also be nice if you could pass in just the LocationIds.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
