### ISSUE TITLE
Report truncating long text/memo fields

### ISSUE THREAD

**Issue by DerekMangrum** [SparkDevNetwork/Rock#3034]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
I have created a Dataview/Report for a workflow. There are multiple workflow attributes of type memo. I noticed on the report that a number of these memo attribute values were being truncated (with ...). This was true even on 'export to excel'. NickA and I looked at the code, and it looks like this is being automatically done after 100 characters. There is no place in the UI to edit/override this.

The only way to get the full attribute values is to use a Lava field. This works, but is not optimal. My understanding is that (using lava entity commands) this is not performant. 

It seems the UI would benefit form a checkbox that let the user enable/disable truncation.

### Steps to Reproduce
1. Create workflow with Memo Attribute.
1. Put a lot of data into memo attribute.
1. Create Dataview/Report displaying the Memo attribute.
1. Also display the memo attribute value using a Lava Report Field.

**Expected behavior:**
I would expect that referencing a Memo Workflow Attribute in a Report would return the full value, not a truncated-at-100-characters version. Or, give the user the option to turn truncation on/off. Maybe even give them the option to determine the truncation length (rather than hard-coded at 100 chars).

**Actual behavior:**

Had truncated at 100 chars.

### Versions
* **Rock Version:** CentralAZ version 1.8.0.9
* **Client Culture Setting:** Windows/Firefox 
![image](https://user-images.githubusercontent.com/1100235/40740368-7fe48476-63fd-11e8-9375-f7d511a651c1.png)

--------
Assigned to TaylorC for Solutioning

**Comment by edmistj** [comment]
Agree this is needed.

**Comment by tcavaletto** [comment]
I propose this solution: The easiest thing to do would be to display the value uncondensed by changing [bool condensed = true](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Reporting/ReportingHelper.cs#L205) on the Reporting Helper to false.

A better option would be to allow users to decide whether the attribute should be condensed or not. This would require:

1. Adding a ShowCondensed field to the ReportField model
2. Adding the following code onto the [btnSave_Click](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Reporting/ReportDetail.ascx.cs#L558) method on the ReportDetail block:
```
if ( reportFieldType == ReportFieldType.Attribute )
                {
                    string showCondensedCheckBoxId = string.Format( "{0}_showCondensedCheckBox", panelWidget.ID );
                    RockCheckBox showCondensedCheckBox = phReportFields.ControlsOfTypeRecursive<RockCheckBox>().First( a => a.ID == showCondensedCheckBoxId );
                    reportField.ShowCondensed = showCondensedCheckBox.Checked;
                }
```
3. Adding the following code onto the [CreateFieldTypeSpecificControls](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Reporting/ReportDetail.ascx.cs#L1279) method on the ReportDetail block:
```
            if ( reportFieldType == ReportFieldType.DataSelectComponent )
            {
                var dataSelectComponent = GetDataSelectComponent( rockContext, fieldSelection.AsInteger() );
                if ( dataSelectComponent != null )
                {
                    Control[] dataSelectControls = dataSelectComponent.CreateChildControls( phDataSelectControls );
                    SetDataSelectControlsValidationGroup( dataSelectControls, this.BlockValidationGroup );
                }
            }
            else if ( reportFieldType == ReportFieldType.Attribute )
            {
                Guid? attributeGuid = fieldSelection.AsGuidOrNull();
                if ( attributeGuid.HasValue )
                {
                    var attribute = AttributeCache.Get( attributeGuid.Value, rockContext );
                    if ( attribute != null && attribute.IsActive )
                    {
                        if ( !attribute.FieldType.Guid.Equals( Rock.SystemGuid.FieldType.DEFINED_VALUE.AsGuid() ) && !attribute.FieldType.Guid.Equals( Rock.SystemGuid.FieldType.BOOLEAN.AsGuid() ) )
                        {
                            RockCheckBox showCondensedCheckBox = new RockCheckBox();
                            showCondensedCheckBox.ID = panelWidget.ID + "_showCondensedCheckBox";
                            showCondensedCheckBox.Text = "Show Condensed";

                            phDataSelectControls.Controls.Add( showCondensedCheckBox );
                        }
                    }
                }
            }
```
4. Adding the following code onto the end of the [PopulateFieldPanelWidget](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Reporting/ReportDetail.ascx.cs#L1452) method on the ReportDetail block:
```
            if ( reportField.ReportFieldType == ReportFieldType.Attribute )
            {
                RockCheckBox showCondensedCheckBox = panelWidget.ControlsOfTypeRecursive<RockCheckBox>().FirstOrDefault( a => a.ID == panelWidget.ID + "_showCondensedCheckBox" );
                showCondensedCheckBox.Checked = reportField.ShowCondensed;
            }
```
5. Update ReportingHelper.cs's [Bind Grid](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Reporting/ReportingHelper.cs#L205) method to read:
```
 bool condensed = reportField.ShowCondensed ?? true;
```
