### ISSUE TITLE
Creating Data View on Person Alias causes exception

### ISSUE THREAD

**Issue by drychlik76** [SparkDevNetwork/Rock#3035]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Attempting to create a series of data views to display a history of background checks from the Background Check Entity.  Realizing that I would need to create a data view to reference the Person Alias entity, to weave together with Background Check Entity, I am getting an error when attempting to do so.  

### Steps to Reproduce

1. Create a Data View and Apply To "Person Alias"
2. Get Error.

Expected to see person alias entity output from data view.

**Actual behavior:** 

Receive error.
Error

Object reference not set to an instance of an object.

<img width="1623" alt="screen shot 2018-05-30 at 1 40 36 pm" src="https://user-images.githubusercontent.com/20803057/40740721-3261a230-640f-11e8-908e-8817c346b2ae.png">

### Versions

* **Rock Version:** 7.3
* **Client Culture Setting:** English

**Comment by cabal95** [comment]
Confirmed error on demo site.
