### ISSUE TITLE
Error with ContentChannelView block on first use after install

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#3036]
### Description
After installing Rock, the ContentChannelView blocks on the external site's home page  shows this error:

![image](https://user-images.githubusercontent.com/383807/40793053-48c01042-64b0-11e8-89d3-c6a7919b53cd.png)

See other reports here: [https://www.rockrms.com/Rock/Ask/Using/Questions/1527](https://www.rockrms.com/Rock/Ask/Using/Questions/1527)

### Steps to Reproduce
1. Install Rock
1. Go to external site home page

**Expected behavior:**

Expected to show content channel items without an error.

**Actual behavior:**

```
ERROR: There was a problem getting content...
Unterminated string. Expected delimiter: Path'[1]', line 5, position 1.
```

### Versions
* **Rock Version:** v7.0
* **Client Culture Setting:** en-us

**Comment by JimMichael** [comment]
Confirmed

**Comment by JayGreentree** [comment]
Also seeing this. After clicking the Edit block and then saving the contents are displayed correctly.
