### ISSUE TITLE
Rock SSN Field Type does not respect "Required" 

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#3037]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

SSN Field type in not respecting "required" setting in both Workflow Attribute or in Workflow User Entry.

### Steps to Reproduce

1. Create a workflow
2. Create an attribute that is of type SSN
3. Create activity with type of User Entry 
4. Make SSN required
5. Run workflow and click the next button (notice how it didn't require a value?)

**Expected behavior:** 
Ideally, it should say that the field is required

**Actual behavior:** 
It is ignoring the "required" flag

### Versions

* **Rock Version:** 7.3, 7.4
* **Client Culture Setting:** en-US

**Comment by tscrip** [comment]
I have come up with a bit of a workaround in the mean time.

All you have to do is create a new Workflow Attribute called SSN. You should set the field type to Text, the description to "This is a workaround for requiring SSNs", and the Key to something like SSNWorkaround.

Add your new attribute to the bottom of your User Entry Action and wrap it in the following div:
`<div id="ssn-workaround" class="hide">`

In the footer of your User Entry Action, add the following:
```
<script>
    // This is a workaround to REQUIRE SSN to be entered
    $('.ssn-box :text').focusout(function() {
        var count = 0;
        $('.ssn-box .ssn-part').each(function( index, element ) {
            var maxLength = $(this).attr('maxLength');
            if(element.value.length == maxLength){
                count++;
            }
        });
        if(count >= 3){
            $('#ssn-workaround input').val("User Entered Valid Information");
        }
    });
</script>
```

What this will do is on losing focus of the last SSN field, it will validate that all the SSNs are the proper length. If they are, it will update your SSNWorkaround Attribute to some text making your form valid.

**Comment by tscrip** [comment]
I don't think this should have been closed. The solution above is a total bandaid and should be fixed.

**Comment by mikejed** [comment]
@tscrip check the #3bff055 link in the closure note- I don't know c# enough to say absolutely, but I think you'll find that Shivam did create an actual fix that's unrelated to the workaround you mentioned

**Comment by edmistj** [comment]
Followed up with @tscrip . All good now.
