### ISSUE TITLE
PersonDuplicateDetail.ascx  Times out Exception

### ISSUE THREAD

**Issue by winmastr** [SparkDevNetwork/Rock#3039]
Selecting Duplicate Finder and using the default settings in the block, creates an exception to fire about 20 seconds in so no page results return.

I have considered the viewstate issue of it having been set at 5000 (I don't know what my user had) so I let a user that I know did not have access or permission to access the page to eliminate that. With Rock admin permission, same results. 
I then tried the same steps from the rock server for both users with same time out exception results.

I restarted Rock with no change. I have viewed the personduplicate table and it contains 106,000 records.
I wasn't sure if i wiped that table and reran the Rock Job, if it would clear the issue, Assuming the quantity in the table was the issue.

* **Rock Version:** [7.4]  

[duperror.txt](https://github.com/SparkDevNetwork/Rock/files/2065267/duperror.txt)

**Comment by winmastr** [comment]
I did Truncate an reseed the personduplicates table to se if it would help. As you probably know, it didn't. After running the Person Duplicate Job, the table rebuilt to the same number of entries.

**Comment by edmistj** [comment]
At this point, the next release (barring some emergency bug) will be v8.0. We're very close (2-3 weeks) from having this to alpha.
