### ISSUE TITLE
7.4 Beta Transaction amount can not be negative

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#3040]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When creating a manual refund transaction, the negative gets stripped from the number. This causes an error when trying to save the transaction.  

![2018-06-04_09h24_02](https://user-images.githubusercontent.com/12735965/40922899-0ba9f066-67d9-11e8-8a29-292c6ccfd295.png)

### Steps to Reproduce

1. Add a new transaction to a batch
2. Check the this is a refund box
3. Enter the negative amount
4. Try to save the transaction

**Expected behavior:** 

The transaction should be saved as a negative amount

**Actual behavior:** 

The above error message with the negative having been stripped from the amount field. The transaction can not be saved as a refund.

### Versions

* **Rock Version:** 7.4 (1.7.4.57) 
* **Client Culture Setting:** en-US

**Comment by winmastr** [comment]
Would this control box be global in its fix? in v7.4 the same issue existed when using an entry form in a workflow.
