### ISSUE TITLE
Event Registration: Field descriptions not appearing for end users

### ISSUE THREAD

**Issue by ajfick** [SparkDevNetwork/Rock#3041]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When creating fields in an event registration, adding text in the "Description" box does not display on the external webpage for the end user. 
Field with description: 
<img width="1166" alt="screen shot 2018-06-04 at 9 50 02 pm" src="https://user-images.githubusercontent.com/19314419/40950688-cabe2eaa-6841-11e8-8ee7-71c9eef6ecf2.png">

Field on External Form:
<img width="1190" alt="screen shot 2018-06-04 at 9 51 33 pm" src="https://user-images.githubusercontent.com/19314419/40950697-d12688be-6841-11e8-9d97-4e76b7447804.png">

It would be incredibly helpful to have the blue "?" icon next to a field and allow the end user to see an explanation of the field itself, why it is being asked for, or an example of the expected input. 

### Steps to Reproduce

1. Create an Event Registration that will appear on the external website
2. Create a field in the Event Registration form and add a Description to this field
3. View the registration on your front facing website and note that there is no description, or blue "?" for the user to click on to see information about that field.

**Expected behavior:** 

When a description is created for a field it will appear either as a tooltip, a sub-label, or a blue "?" that the user can click on like in other areas of Rock. 

**Actual behavior:** 

No description is displayed for the field. 

### Versions

* **Rock Version:** v7.3, v7.4, v8.0
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by ajfick** [comment]
It would also be great to have the option to name and give a description to Person Fields on external registrations. For example, when you create a form with Phone Number Person Fields, the names that show on an external form for the fields are just "Home" and "Mobile" but I am unable to make it say "Home Phone Number" or "Mobile Phone Number". It would just be nice to customize that stuff.

**Comment by ethan-sparkdevnetwork** [comment]
Added help text on the registration attributes for the external and internal site. The help text can be turned on and off for the external site using block settings.

**Comment by ethan-sparkdevnetwork** [comment]
We are going to discuss adding the ability of custom labeling and help text for the other form field sources.

**Comment by ethan-sparkdevnetwork** [comment]
We are not going to add custom labeling and help text for the other form field sources at this time.
