### ISSUE TITLE
Bad Lava in Communication Queue Alert system email

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3044]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Lava that formats the href back to the communication in the _Communication Queue Alert_ system email is broken. There is an errant space in the path right before `{{ comm.Id }}` that breaks the link.

`{{ 'Global' | Attribute:'InternalApplicationRoot' }}Communication/ {{ comm.Id }}">{{ comm.Subject }}</a> from {{ comm.SenderPersonAlias.Person.FullName }}`

### Versions

* **Rock Version:** 7.0-8.0

**Comment by ethan-sparkdevnetwork** [comment]
Body text will be corrected in the next migration.
