### ISSUE TITLE
Submit button appearing twice on manual payment option of event registrations

### ISSUE THREAD

**Issue by USCBigRed** [SparkDevNetwork/Rock#3045]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When you go in to process a manual payment on an Event Registration.  The submit button is there twice.  If I click the Submit button on the left, everything works as normal.  If I click the button on the right, it throws an exception.

### Steps to Reproduce

1. Goto an event registration and click Manual Payment
2. There are two buttons on the screen that both say submit.
<img width="475" alt="screen shot 2018-06-06 at 6 20 30 pm" src="https://user-images.githubusercontent.com/5194936/41073286-7622bd80-69b7-11e8-9ba5-1c5c2c5c1db0.png">

**Expected behavior:** 

For there to be just one Submit button

**Actual behavior:** 

There are two submit buttons

### Versions

* **Rock Version:** [ 7.4 (1.7.4.57) ]  
* **Client Culture Setting:** [ en-US ]

**Comment by ethan-sparkdevnetwork** [comment]
This has already been fixed for v8.0 in pull request 2967.
