### ISSUE TITLE
Inconsistent results when texting to 'Home' numbers marked as SMS Enabled

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3046]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Basically, If I don't have a home phone, I might have written my cell phone in the "home phone" field and enabled SMS. When sending an SMS, it will send to that number.

However, if I then reply to that message, Rock will send back an error stating my number could not be found in the system. This is because the code for processing a response looks specifically at phone numbers of type `Mobile`.

### Steps to Reproduce

1. Set your home phone to your mobile number and enable SMS
2. Blank out your mobile number
3. Have somebody send you a text message from a Person-To-Person enabled Twilio number
4. Try to respond to SMS

**Expected behavior:** 

System should process the message since it indeed does know about the phone number. If we can send to it, they should be able to respond from it.

**Actual behavior:** 

Incorrect error message about my phone number not existing.

### Suggested Fix

Suggesting that we remove the check for phone number type and instead just check if the number itself matches, and then sort by the following to try and pick the best match.

First sort by SMS Enabled, then sort by Phone Type == Mobile.

That is, if two people have the same phone number, but only one has "SMS Enabled" turned on, they will be picked.

If two people have the same phone number, but one has it listed as Home and the other as Mobile, the person who has it listed as Mobile will be picked.

### Versions

* **Rock Version:** 7.3
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Sounds good.
