### ISSUE TITLE
[EN] Make DefaultCountry behavior consistent between SmartyStreets and DataViews

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#3047]
### Description

When importing thousands of locations from another system, the Country could be blank. This means a DataView filter targeting a specific state returns no records because it's filtering for a DefaultCountry of `US`.  

International addresses are not turned on so there's no indication that `US` is being required:

<img width="695" alt="screenshot 2018-06-07 15 40 21" src="https://user-images.githubusercontent.com/1210933/41122712-6d6b50ae-6a6a-11e8-8469-df277acdc12a.png">

<img width="755" alt="screenshot 2018-06-07 15 28 00" src="https://user-images.githubusercontent.com/1210933/41122715-6f695ff4-6a6a-11e8-80b8-38f1408d16e2.png">

Looking at the location in question, SmartyStreets verified the address but never set the Country field:

<img width="747" alt="screenshot 2018-06-07 15 51 19" src="https://user-images.githubusercontent.com/1210933/41122810-bc8395a2-6a6a-11e8-9353-3681ed3c7ef3.png">

Proposed behavior change:
1) SmartyStreets could set the Country field during verification. 
2) Rock could set Country fields to DefaultCountry as part of the cleanup job
3) Rock could assume DefaultCountry when Location.Country isn't set

### Steps to Reproduce

1. Import an address with Slingshot
2. Create a person dataview with Location filter
3. Select a state that you know is in the system

**Expected behavior:** 

The dataview should return results.

**Actual behavior:** 

Dataviews do not return results.

### Versions

* **Rock Version:** v7.3
* **Client Culture Setting:** en-us

**Comment by edmistj** [comment]
I'd propose some of all your suggestions:

1. The clean up job should look for addresses with no country. If a state exists set the country to be the states country.
2. Update the DV filter to not consider country unless they are specifically provide a country to filter on.

**Comment by GerhardPowell** [comment]
Solution applied at:
https://github.com/SparkDevNetwork/Rock/commit/c63d76cda3b854f367573bafda44b37f900c6240

**Comment by GerhardPowell** [comment]
I updated the DV filter (LocationFilter) at:
https://github.com/SparkDevNetwork/Rock/commit/e283367538a4ba95990a2335a527e88a02929581
https://github.com/SparkDevNetwork/Rock/commit/26d99ea7bdea207130bbd7e8b85a9b96cf8dfd1e
