### ISSUE TITLE
Exporting Tag grid to Excel is broken

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3051]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Exporting a Tag to Excel creates a corrupt file. This occurs on both personal and org tags.

### Steps to Reproduce

1. Go to People | Tags and find a tag with people in it.
2. Export to Excel (in my case version 2016 on Win10)
3. Observe the error message about a problem with the file asking if you want to recover it.
4. Observe that when you say "yes" to recovery, you end up with a file that contains none of the expected columns, and a Entity Guid instead.

**Expected behavior:** 

Export to Excel from a tag would work like it does on other grids.

**Actual behavior:** 

It don't. I verified same behavior on demo and prealpha.

### Versions

* **Rock Version:** 7.3-8.0  It may occur on 7.0-7.2 as well but I can't test that. All we know is it worked fine in 6.9 before we upgraded to 7.3.

![image](https://user-images.githubusercontent.com/3903408/41163720-1155c282-6aff-11e8-84e6-17dcdf78184d.png)
![image](https://user-images.githubusercontent.com/3903408/41163732-166bd234-6aff-11e8-85ed-e6599bc28bb2.png)

**Comment by JimMichael** [comment]
I also verified identical behavior on the MacOS version of Excel (also v2016)

**Comment by cassisca** [comment]
I have experienced the same issue and error message as mentioned through this conversation for 7.4 revision, with most of my organizational tags, however one of my tags errors out with a ROCK notification error message before it create the corrupted Excel file. Please attached file for error message.

I see this error issue has been resolved for upcoming 8.0 revision, but when is that scheduled to be released?  I hope we are jumping from 7.4 to 8.0 revision.

[Rock Error.pdf](https://github.com/SparkDevNetwork/Rock/files/2267595/Rock.Error.pdf)

**Comment by cabal95** [comment]
@cassisca 8.0 is in beta now. I think the hope is to release it for early adopter access shortly after the RX conference at the end of the month. But that depends on how many bugs the beta tester team finds that need to be fixed. After that I believe it hits everybody else 3 months later.

**Comment by cassisca** [comment]
Thank you for the heads up!!!

On Tue, Aug 7, 2018 at 11:35 AM, Daniel Hazelbaker <notifications@github.com
