### ISSUE TITLE
[Enhancement] Add rock version to sub-headings in release notes.

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3052]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

As the rockrms.com/releasenotes page gets longer and longer, it's becoming more difficult to know what version an item applies to. Example: Say you know there was a Lava filter added but you don't remember which version it's in... so you tell your browser to search for "Lava filter" and you get scrolled deep into the page with the first hit, but you have no idea what version you're "on" without scrolling BACK up to the version header, which can be quite far away. This gets really frustrating when you're rapidly searching for different keywords to zero in on The Thing You Know Is There But Can't Remember Where.

A simple fix would simply be to repeat the version number next to each sub-heading, so it would always be _obvious_ "where" you are on the page.
![image](https://user-images.githubusercontent.com/3903408/41174925-0f43330e-6b21-11e8-90b1-75169f37b43e.png)

**Comment by garrettjohnson** [comment]
Added! 🎉
