### ISSUE TITLE
Event Registration: Minimum Initial Payment does not account for Fees

### ISSUE THREAD

**Issue by ajfick** [SparkDevNetwork/Rock#3053]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
If a number of Fees are set up for an event registration with no "Cost", along with a Minimum Initial Payment, the minimum initial payment is not enforced, but the user can choose to pay nothing at the time of registration. 

The following photo is of a registration where the Cost = $0. The Fees add up to $699, The registrations Minimum initial payment is set to $99 but displays as $0 and allows the user to pay $0 initially. 

![screen shot 2018-06-11 at 12 35 03 pm](https://user-images.githubusercontent.com/19314419/41244818-3f53b208-6d74-11e8-97d0-e738f08118d9.png)

### Steps to Reproduce
1. Create Event Registration with Fees
1. Charge $0 for the Event and set minimum initial payment to $1 or more
1. Attempt to complete the form and notice that Minimum initial payment is set to $0 and you are able to pay $0 at time of registration.

**Expected behavior:**

The minimum initial payment should take into account that there is money owed even if not from the "Cost" field and force that initial payment based on the cost of the Fees alone.

**Actual behavior:**

User is able to register without payment when Cost is $0. Even if total fees are greater than the minimum initial payment amount. 

### Versions
* **Rock Version:** 7.3
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by edmistj** [comment]
Currently fees are not considered when it comes to minimum initial payment. The problem would be if you have a free event with an optional fee and a minimum payment of $20. That would make the free event require $20.

We have some new features we'd like to add in this area that would help address this. Like making fee costs required or not. We can tackle this at the same time.

**Comment by ajfick** [comment]
@edmistj Got it. That would be great. We were just setting up our School Of Ministry registration today and happened on this that hindered us. Our solution was just to set a cost of 1$ on the registration itself and then set the costs for the Fees. So it still worked fine, just not as I expected it to.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
