### ISSUE TITLE
Person Attribute From Fields WF Action - Creates a duplicate record if the email addresses are the same but have different casing.

### ISSUE THREAD

**Issue by mkinyon** [SparkDevNetwork/Rock#3057]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using the Person Attribute From Fields workflow action, the action will create a duplicate record if the email addresses have different casing:
![image](https://user-images.githubusercontent.com/2349102/41307423-f7c6f2f0-6e2d-11e8-8b22-465f100a2936.png)

You can see by the picture below that another record was created because the first letter of the email address is a different case:
![image](https://user-images.githubusercontent.com/2349102/41307324-b87c4b04-6e2d-11e8-8dbc-24ccad4fbd39.png)

### Steps to Reproduce

1. Create a workflow with a form that collects information and a Person Attribute From Fields action that will find a matching person.
2. Run the workflow once to create the first person record.
3. Run the workflow again and create the same person except change the casing of the email address.

**Expected behavior:** 
I would expect the action to match the person even though the email address was cased differently.

**Actual behavior:** 
A duplicate record gets created.

### Versions
* **Rock Version:** 7.3, develop

**Comment by ethan-sparkdevnetwork** [comment]
This was fixed in commit 590f6c9f.
