### ISSUE TITLE
Enhancement to speed up check scanning

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#3058]
I'm posting this here because I see it come up relatively frequently on Slack, not because I have extensive personal knowledge.

From what I understand, the check scanning Windows app uploads each check as soon as it's scanned, waiting for the upload to complete before scanning the next check. The result is that the scanning speed is extremely dependent on the network connection speed, and in all cases is slower than the scanner's ability to scan checks.

The enhancement request is thus to rework the process in the windows app, so that it scans a batch of checks at a time (at the scanner's maximum speed) and uploads them all at once - either at the end or in batches of, say, 50 checks. Or could it upload the checks asynchronously with the scanning, getting an upload "queue" going so that it's not doing just one of these tasks at a time?

Many churches feel this would speed up their inputting process - if that's not the case, an explanation we can pass along as to why that's not the case would also be helpful. Thanks!

**Comment by edmistj** [comment]
We're open to this. We originally set it to the current behavior so that if there was a mis-feed you could recover from it easier. But, changing that is fine.

**Comment by chrisfunk** [comment]
A solution to this would make my finance team very happy

**Comment by nairdo** [comment]
Hi @mikejed  or @chrisfunk   With the advent of our newish "Ideas" system (http://community.rockrms.com/ideas) I think it would be best if one of you added it as an idea over there so it can be put up to the voting process.
