### ISSUE TITLE
Enhancement to print special characters correctly on Zebra printers

### ISSUE THREAD

**Issue by lpeterson1** [SparkDevNetwork/Rock#3060]
### Prerequisites
* [ x] Put an X between the brackets on this line if you have done all of the following:
  
### Description

Special characters in names don't currently print correctly on Zebra labels. A workaround was added in 2015 to the check-in success block to correctly print the accented e ( é ), but other special characters are substituted with nonsense characters.

One solution would be to change the `CI0` commands in the configuration line of all the stock labels to `CI27`, which changes the code page printed by the printer to 1252. This prints standard and special Windows and Mac characters correctly.

The code added to the success block here: https://github.com/SparkDevNetwork/Rock/commit/6a4ef87913206300cb48f583c3f993901c6fb6d5#diff-999dc387a1225de2fda75bc71becf249
would need to be removed, because an incorrect (comma) character prints instead of the "é" with this change.

The ZPL Guide seems to indicate that this code page has always been (and still is) a part of the Zebra firmware, but since I was only able to test on a GX420d, it would be good to test on a newer printer. All icons and other text print as now.

In the middle picture (printed after changing the code page) the first character should be the "é" (not a comma), demonstrating what would happen if the workaround code is left in the success block.

The bottom picture shows how the same characters print currently.

I assume that users must have been removing special characters; this would make that unnecessary (and print some names more accurately).

![screen shot 2018-06-12 at 3 12 32 pm](https://user-images.githubusercontent.com/37701239/41317777-76862302-6e53-11e8-9d2f-c149fd22fcd8.png)

![img_2952](https://user-images.githubusercontent.com/37701239/41315879-07eb1c90-6e4e-11e8-9d8c-5c6c529f3821.jpg)
![img_2953](https://user-images.githubusercontent.com/37701239/41317292-ff00fe48-6e51-11e8-9732-7e268d05eef8.jpg)

**Comment by edmistj** [comment]
Nice! This is something I've wanted to research for a while, but never had a chance. Really appreciate the info!

**Comment by lpeterson1** [comment]
FYI, apparently the Windows and iPad apps won't print extended ASCII characters to a network printer. The labels above were printed over USB from the Windows app, but when printing to a network printer with either app the extended characters don't print correctly, so unfortunately there would be more to this than just modifying labels. I checked the data sent to the printer and for sure it's the apps, not the printer. I didn't test printing from server.

**Comment by chrisfunk** [comment]
@edmistj We ran into a similar issue at Lake Pointe as well.  I had just hardcoded a list of Spanish character codes in our `success.ascx.cs` block.  I hadn't submitted it as a pull request because I didn't like the architecture of my solution.  I would be willing to submit it if there is a better design than just a list of hard coded characters.

**Comment by edmistj** [comment]
@lpeterson1 so would changing the characters in the success block be the best course of action?

**Comment by lpeterson1** [comment]
I'd think it'd be better to fix the apps. Hardcoding would fix a few characters, but fixing the apps would print all extended characters. Never know when you might need an umlaut or "a with a circle thing over it".

It seems surprising that the Win app would print fine to USB printers, but not to network printers (BTW, the Win app prints question marks, but the iPad app prints bogus characters).

**Comment by garrettjohnson** [comment]
Related to #2450

**Comment by lpeterson1** [comment]
Just to clarify (because the StackOverflow articles referenced in 2450 point to fixing by encoding differently), the _Windows app is sending_ question marks, not incorrect characters (when printing via network). In this screenshot from a packet sniffer, The \82 is the Rock-converted accented e, but the following two question marks are generated by the app (and not just incorrectly encoded). These characters all print correctly when printed via USB from the Win app (when the label is set to ^CI27).


![screen shot 2018-06-13 at 8 11 51 am](https://user-images.githubusercontent.com/37701239/41458346-971d17a0-7043-11e8-8c76-3b0fd9112b4e.png)

![screen shot 2018-06-13 at 8 13 48 am](https://user-images.githubusercontent.com/37701239/41458700-931433fe-7044-11e8-8853-4ac4fda6b846.png)

**Comment by lpeterson1** [comment]
To add one more piece to the puzzle, the iPad app sends extended characters as UTF-8 encoded Unicode. Changing the encoding on the printer to `CI28` allows the iPad to print special characters correctly. Using UTF-8 encoding for both Win and iPad apps would likely break old printers (pre-GX420 models) because it appears that their firmware predates Unicode capability.

**Comment by lpeterson1** [comment]
I'll wrap this up and explain the current situation and possible solutions.

I tested four configurations:

- Printing from the Windows app over USB
- Printing from the WIndows app over Ethernet
- Printing from the current iPad app
- Printing from the (unreleased) updated iPad app (that fixes the backslash/line feed problem)

As it is now, only extended characters printed using the `FH\` mechanism print, although that is not working on the current iPad client (it prints the code, not the character). The only character that currently prints on WIndows is the é, which is hardcoded in the check-in success block. Other special characters currently print as question marks when network printing, or bogus characters printing from the Win app/USB.

Win/USB users can, without doing anything else, change the `^CI0` label command to `^CI27` (code page 1252) and all special characters _except_ the é print correctly. The é will print as a comma until the hard code is removed.

iPad users can also, without doing anything else, change the `^CI0` command to `^CI28` (UTF-8 encoding) and all special characters except the é print correctly. "é" prints as "82" using the old app, and blank using the new one.

Win/network printer users can only print special characters using the `^FH\` mechanism. meaning that the only one they can currently print (without custom mods) is the é. All other special characters print as question marks.

One solution is to hard code all the desired special characters in the success block, like the é is currently. This would work on both platforms (but not the iPad until the updated app is released). This seems less than desireable, especially with Rock going international, plus it doesn't seem like a very efficient way to approach this.

A better solution would be to fix  the Windows client, preferably so it encodes data as UTF-8 for both USB and network printing. If so, the stock labels can be changed to `^CI28` (and the "é" handling code removed) and everything will work correctly for both platforms. If it's fixed so it encodes as ASCII (like USB printing is now) it would mean that the `^CI` command would have to be different between iPad and Windows labels.

More information is is the [ZPL Programming Guide](https://www.zebra.com/content/dam/zebra/manuals/printers/common/zpl-zbi2-pm-en.pdf), pages 132 and 1317.

**Comment by edmistj** [comment]
Played with this quite a bit this morning. Found where the encoding we set to ASCII. I changed that to UTF-8 (and updated the labels) and got different but not good results. After trying different types of encoding it seems like it liked ISO-8859-1. 

![1](https://user-images.githubusercontent.com/548178/41555301-20d389c0-72ec-11e8-8ff8-d00b0029beb5.jpg)

Here's the specific labels.

![2](https://user-images.githubusercontent.com/548178/41555605-1890eed2-72ed-11e8-90d0-69d3f855275d.jpg)

So I think that looks right. My only thought is how do we ensure that the labels being uploaded have `^CI28` vs `CI0`. I'm assuming ZebraDesigner is spitting the labels out with `CI0`. Do you think it's safe for Rock to modify that when they upload/edit the labels?

**Comment by ethan-sparkdevnetwork** [comment]
Created a migration to change the five system labels to use ^CI28.
Added code to the label upload process to change ^CI0 to ^CI28.
Added checkbox to EditLabel called "Force Expanded Character set (UTF-8)". The block will change ^CI0 to ^CI28 on save unless it is unchecked. The box is checked by default.

Code change done in commit ddce81f2.
