### ISSUE TITLE
Person Detail's Connection Request Only Displays Active Request as of v7.4

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3065]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

In the 7.4 update, the Person Detail Connection Request block will only show connection requests that are active. It will no longer display connected/inactive/future follow-up requests. I didn't see anything about this in the release notes so I believe it may be a bug. We noticed it in our production server. To verify if it may be a bug or not I have scanned through the release notes from the other v7 updates to make sure it wasn't a new update. I have also updated our dev server from 6.9, and with each minor update I would check to see if the requests remained on the person detail page--they did until the v7.4 update.

[Edit] So I checked out the hot-fix branch for 1.7.4 and noticed it was intentionally updated to leave out inactive/closed requests and future request more than a day out. Since that is the case, I'd like change this to an Enhancement for having a block setting where you have a choice to display all requests or just active requests.

The nice thing about having all requests displayed is it provides a shortcut to the request if you are already reviewing the person's record. Otherwise, you'll have to go through the connection's menu and update your filter settings each time.

### Steps to Reproduce

1. Create a new connection request with either an inactive, connected, or future follow-up date with a future date.
2. View the requester's profile and the connection request block. It will just list the Connection Opportunity but not the request unless it is an active request.

The Demo site is on v7.3 so I couldn't replicate it there but I did add some requests to Alisha Admin should the core team want to update to v7.4 to test it.

**Expected behavior:** 

Display both active and inactive/closed/future requests (faded text color for completed requests).

**Actual behavior:** 

Only active connection requests will be displayed. Once it is completed or set for a future follow up it will no longer be visible in the block.

### Versions

7.4 (1.7.4.58)

**Comment by edmistj** [comment]
Sorry that change missed the release notes, I added it. The previous behavior (showing all) was reported as a bug, I guess though I could see it both ways. Looking for feedback:

1. Leave it as is (only active)
2. Put it back to showing all, but provide better categorization (group inactive under the actives and gray out the future follow-up)
3. Add a block setting to determine what to show.

I guess you could vote for 2 & 3 if you'd like.

**Comment by BEGamache** [comment]
No worries. I went back and reviewed the hot-fix branch and noticed it was intentional after submitting this request. 

I believe Option 3 would be the best option since some churches may want only active shown and other may want all. Combining it with Option 2, if displaying all, would be nice as well. Hate to add more work to your plate though.

**Comment by tstephens17** [comment]
We would love option number 3 as well. Our staff got used to the behavior.

**Comment by edmistj** [comment]
Good feedback. Option 3 has been implemented.
