### ISSUE TITLE
Static Html Attribute Field Type

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3066]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
I don't know if this would be useful to others and if it should go into core, but I'll post the details here and see what people think.

Imagine some entity (say a Survey, Group, etc) that has around 30 attributes defined. Don't laugh. We have a few of those. You want to make the list of attributes a bit cleaner and easier to read so you want to include an `<hr />` or something like that between a few of the attributes to make it more obvious that they are entering a new section. Unfortunately the only place you can do that right now is in a Workflow User Entry Form (because of the Pre-HTML).

So the thought was to have an Attribute type that would be Static Html. In the attribute configuration you define the HTML that is used when rendering in Edit mode (View mode always returns an empty string which hides the attribute in most cases).

A picture might be worth a thousand words.

Defining the attribute:

![](https://user-images.githubusercontent.com/1119863/41382051-4aa45d86-6f1f-11e8-9db2-c99181c7694f.png)

As seen in Edit mode:

![](https://user-images.githubusercontent.com/1119863/41382059-51c7b5a4-6f1f-11e8-97ea-23af8a9bf84f.png)

As seen in View mode:

![](https://user-images.githubusercontent.com/1119863/41381901-8b7a30c0-6f1e-11e8-9497-908c6d2645e8.png)

## Method of implementation
The way I have implemented this is with a new Field Type. The Field Type uses a Code Editor in it's configuration to allow the user to enter HTML value. The Field always returns a blank string for `FormatValue`. The `EditControl` method uses a new UI control of `StaticRockControl`.

The StaticRockControl implements the `IRockControl` interface but pretty much hard codes everything to blank (Label, Help, etc.). This causes the Label (attribute name) to not display, nor any help text or required indicators or anything. This class is also a subclass of LiteralControl, so at render time it just writes out whatever HTML value was configured.

**Comment by Tschrock** [comment]
I'd be interested in something like this as well, though I think it would be cooler if you could have Post/Pre-html on the attributes themselves instead of a separate attribute type.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
