### ISSUE TITLE
Validation confusing on pre-registration when no redirect page configured.

### ISSUE THREAD

**Issue by edmistj** [SparkDevNetwork/Rock#3068]
### Description

Pre-registration block shows invalid validation.

### Steps to Reproduce

1. Enter in details for one adult
2. Submit form
3. Notice that there are validation errors for the second adult.

This is only show if no redirect page is configured.

**Expected behavior:** 

Should not show validation messages if a second adult is not added.

**Actual behavior:** 

Validation message causes confusion.

![image](https://user-images.githubusercontent.com/548178/41393291-e78009ae-6f59-11e8-9b2d-2717d008e477.png)

### Versions

* **Rock Version:** v7.4  
* **Client Culture Setting:** en-US

### Proposed fix:
**Plan A:**
If no redirect page configured:
After submitting show a dismiss-able alert saying "Ted Decker [& Cindy Decker] has/have been added." and clear out the fields.

**Plan B:**
If plan A is deemed to complex, at the very least require a redirection page in the block settings. This will at least encourage individuals to configure the page in a way that best works.

**Comment by cabal95** [comment]
I'm a fan of `Plan A`. I would also be okay with completely hiding the details panel and just displaying the alert only. I think this would provide the least confusion to a new family.

**Comment by ethan-sparkdevnetwork** [comment]
This was fixed in commit 46bd438. We had to go with Plan B for now, the block was designed to use a redirect.
