### ISSUE TITLE
Statement Generator shows Inactive individuals even with "Exclude Inactive Individuals" checked

### ISSUE THREAD

**Issue by ajfick** [SparkDevNetwork/Rock#3069]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers ](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When running the statement generator on v7.4 or 7.3 checking the box "Exclude Inactive Individuals" still displays the inactive Individual's name in the header of the page regardless of whether the inactive user made a transaction in the timeframe of the statement being made. When checking statements online however, this displays correctly and doesn't show the name of the inactive person. 

In the images below, the Red block represents someone who is inactive, blue represents someone who is currently active and who all the family's transactions are assigned to.

![screen shot 2018-06-14 at 10 26 51 am](https://user-images.githubusercontent.com/19314419/41420007-6a945e78-6fc1-11e8-9def-99da58636f61.png)

Generated from Statement Generator App: 
![screen shot 2018-06-14 at 10 44 49 am](https://user-images.githubusercontent.com/19314419/41420011-6e584146-6fc1-11e8-9876-05a9729212f1.png)

Online view of a statement: 
![screen shot 2018-06-14 at 10 45 04 am](https://user-images.githubusercontent.com/19314419/41420015-73c7dd44-6fc1-11e8-8b17-b2966b405b9e.png)

### Steps to Reproduce
1. Create or find a family with an Inactive user or Inactive and Deceased user who has combined giving with other family members
1. Open the Rock Statement Generator and check the box that says "Exclude Inactive Individuals" 
1. Run the statement Generator
1. View the resulting statement PDF and you will be able to find the inactive individual regardless of whether or not they have given during the timeframe (if a family member in the Giving Group gave, their name will appear on the statement)

**Expected behavior:**

When the "Exclude Inactive Individuals" box is checked on the giving statement generator, the names of individuals who are marked "Inactive" should not be displayed in the family name.

**Actual behavior:**

When the "Exclude Inactive Individuals" box is checked on the giving statement generator, the names of inactive individuals are still displayed in the "Family Name" in the upper left hand corner of the page. 

### Versions
* **Rock Version:** 7.3 & 7.4
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/cc5d2631675717cd399cc14ef5595ce985e3585c
