### ISSUE TITLE
Unattended Check-In workflow has Action-level logging enabled

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3072]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

It looks like at some point in time, the unattended check-in workflow got Action logging enabled. Jesse M in Slack noticed this on his WF, but when I looked at mine, logging was set to None. I then checked demo, prealpha, and a new instance of Rock I'd installed a couple of weeks ,and all had Action logging enabled.

### Steps to Reproduce

1. Go to Admin | General | Workflow Config and edit the Unattended Check-in WF.
2. Observe that Action-level logging is enabled.

**Expected behavior:** 

Unless there's some reason this is _supposed_ to be enabled, it shouldn't be... and will bloat workflow log tables quickly. 

**Actual behavior:** 

On new installs and other observed installs, logging is enabled on this WF... except on my production instance. Since I have NO recollection of ever turning that off, I'm wondering if a migration to update the unattended check-in WF happened at some point, but ours was not touched because we had modified it (swapped out two filter actions for the single _FilterByAgeAndGrade_ action). Either that, or it's always been enabled and I just don't remember turning it off on ours.

### Versions

* **Rock Version:** v7/8, maybe all?

**Comment by ethan-sparkdevnetwork** [comment]
The logging level for the Unattended Check-in workflow type has been set to activity (3) since version 0.2 however it is set to not persist. I ran a few tests and with and without automatically persist. It works as expected, rows are inserted if set to persist, and are not if set to not persist.

**Comment by ethan-sparkdevnetwork** [comment]
Created a migration to set the logging level to none for unattended check-in.
