### ISSUE TITLE
BUG - Cannot reorder Form Sections

### ISSUE THREAD

**Issue by TheVillageChurch** [SparkDevNetwork/Rock#3073]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

On any page where we are using the Person Attribute Form block, we are unable to use the hamburger menu to reorder the form sections. We have tested this on the Rock Demo site and had others test it on their installs as well.

### Steps to Reproduce

1. Create a page and add the block Person Attribute Forms.
2. Edit the block and add two form sections.
3. Click on the hamburger menu icon in the upper-right corner of one of the form sections and try to move it above the section above.

**Expected behavior:** 

We expect to be able to reorder sections within a form.

**Actual behavior:** 

The hamburger icon only triggers expand/collapse

### Versions

* **Rock Version:** 7.3
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by cabal95** [comment]
It looks like the server-side code to do the re-ordering is present, but the client-side javascript to trigger the event is not present/working.
