### ISSUE TITLE
Enhancement: Allow exclusions to "Move Adult Children" data automation process

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#3079]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

For the vast majority of cases, the new Data Automation Job moving children out of existing famili(ies) and into their own family as an adult, is going to be a huge benefit. However, there are always the edge cases, right?

I'm thinking specifically of special needs individuals who, although they are over 18, should be left as a "child" member of their family, regardless of their age. However, there may be other situations where churches may wish to exclude lists of people from this job.

It would be nice to either provide a field where a person attribute or, more ideally, a dataview can be selected which would allow people to be excluded from the process.

As it is, we could design a workflow which looks for the attribute and puts them back in `OldFamily`, but that would create unnecessary churn in the database since that process will be repeated every week (since they would be constantly being moved out, and then back in to the original families)

### Versions

* **Rock Version:** 1.7.4, 1.8.0 prealpha  
* **Client Culture Setting:** EN-US

**Comment by edmistj** [comment]
v8 has a field on the person edit screen (under 'Advanced') that allows you to lock an individual as a child. This individual would then be excluded from the process.

![image](https://user-images.githubusercontent.com/548178/41614500-840b9a8e-73ad-11e8-82e3-b414cf6d4478.png)

**Comment by mikejed** [comment]
Perfect. I hadn't looked there, thanks
