### ISSUE TITLE
Event Payment on Registration Details is showing Registrar's name, not Cardholder's name

### ISSUE THREAD

**Issue by alyssa-pathway** [SparkDevNetwork/Rock#3080]
### Description
Sorry for the subjective description, it's hard to describe the issue without be subjective.
We had a family register for camp. Dad has a username/password. Mom used that username/password to register two kids for camp. Mom used her own credit card (in her name) to pay. 
When looking at event payments within our internal site, the "Details" has the registrar's name (dad's name) as if the payment card is owned by the registrar (Dad). When we click on the date/time stamp to open up the transaction detail, we can see that it was actually the Mom's credit card.
In registration, under view/edit payments:
![image](https://user-images.githubusercontent.com/29411182/41623903-c7103822-73d9-11e8-8389-d3750b87d39d.png)
Transaction Detail page for same payment:
![image 2](https://user-images.githubusercontent.com/29411182/41623869-ad02b0e0-73d9-11e8-91fe-0d9071f16595.png)
### Steps to Reproduce
1. Register someone for an event that costs money.
1. Use a different Registrars name than the name of the payment cardholder.
1. Check the view/edit payments within the registration. Registrar's name should show up as if it was their card.
1. Click on the time stamp of the payment to get to the transaction detail page.
1. Correct cardholder's name will be present on the transaction detail page.

**Expected behavior:**

I should see the cardholder's name on the view/edit payments page, under "Details" of the payment.

**Actual behavior:**

I am seeing the registrar's name, even though they didn't pay the event cost.

### Versions
* **Rock Version:** 7.3
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
@alyssa-pathway This does not appear to be an issue after the overhaul of the payment tab. Let me know if you still see an issue.
