### ISSUE TITLE
SendEmail Workflow Action does not convert relative urls.

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3082]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

After upgrading to v7, emails sent through a workflow no longer automatically convert relative urls in links and images (like `/Content/image.png` => `https://example.com/Content/image.png`

Technical:  
It looks like after 3fa546142a the appRoot is no longer passed to the new communication in all email-related workflow actions.

### Steps to Reproduce

Add an action that sends an email with a relative url in an image or link.

**Expected behavior:** 

Urls are converted to full urls using the PublicApplicationRoot like they are with normal communications.

**Actual behavior:** 

Urls are unchanged.

### Versions

* **Rock Version:** 7.4  
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Likely related to #2946, which was reported as fixed in 7.4. Similar fix is probably needed here.
