### ISSUE TITLE
Allow Image Uploads While In Code Editor - Discussion

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3084]
### Description
A recent change I noticed while editing a post on ShoulderTheBoulder.com -- which I presume is due to a change in v8 -- is that the editor will now prevent you from going into WYSIWYG mode if certain HTML exists in the editor (like `&lt;` and similar). This is a nice feature to prevent WYSIWYG mode from trashing hand-entered code, but it has also created a problem... there is now no easy way in such an editing mode to upload an image, since the file/image browser buttons are only enabled when in WYSIWYG mode.

The Easy Button, I think, would be to enable these File/Image Browser buttons even when in code mode, but I don't know if that's doable or would cause other issues. That's why I'm creating this issue for discussion. As it stands, at least in regards to STB, you have to create a fake post (or open an existing one you created) that has no special HTML so that you can use WYSIWYG mode just to upload an image.

### Versions
* **Rock Version:** [8.0]

**Comment by jonedmiston** [comment]
Closing as this is more of a feature request. Please open on our Ideas page (which admittedly did not exist when this was opened 😊).
