### ISSUE TITLE
Batch Detail Merge/Export Missing Fields

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#3085]
### Description

On the Financial Batches screen (Batch List Block), when Exporting to Excel or Using a Merge Template the Transaction Count, Transaction Amount and Accounts fields are empty.  The Merge fields are also missing when I try to use an existing Merge Template.

### Steps to Reproduce

1. On the Demo site, go to Batches under Finance Functions.
2. Click the Export to Excel button.
3. Open in Excel and the columns D through I are empty, but I only know that Transaction Count, Transaction Amount and Accounts use to be populated and now are not.
4. Also if you click on Merge Template and look at the Merge Fields, those columns are also missing from the Merge Fields.

**Expected behavior:** 

Expect Excel to look like the grid on the screen.  Expect {{ row.TransactionCount }}, {{ row.TransactionAmount }} and {{ row.AccountSummaryHtml }}

**Actual behavior:** 

Columns and Merge Fields are not populated.

### Versions

* **Rock Version:** 7.4
* **Client Culture Setting:** Azure Servers

**Comment by cabal95** [comment]
This bug also exists in prealpha site.

<img width="880" alt="2018-06-22 08_27_14-batches _ rock rms" src="https://user-images.githubusercontent.com/1119863/41785064-4d628e52-75f6-11e8-9a4c-e14878e2e984.png">

<img width="1210" alt="2018-06-22 08_27_01-" src="https://user-images.githubusercontent.com/1119863/41785073-4f86911a-75f6-11e8-914d-36276d86bf67.png">

**Comment by ajfick** [comment]
@bobrufenacht @cabal95 Is there any sort of workaround for this at the moment? We had a Merge Document based on the {{Row.AccountSummaryList}} that is now broken...

**Comment by cabal95** [comment]
I don't have a workaround as we never used the export. We just the browser page and it includes all the info needed for us.
