### ISSUE TITLE
Email Clicks not being displayed in analytics

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#3086]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site] - **I cannot due to sending emails not enabled**
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

[Clicks are not being recorded in email analytics. They were at some point, maybe prior to v7? Not sure exactly when it stopped.  Myself and Morgan Woods and Alyssa Winegar have seen this happen. As noted above I'm unable to reproduce on demo site since we can't send emails. Also FYI - Alyssa and I are both using sendgrid, I haven't heard back yet from Morgan if she is using Sendgrid or not.]

### Steps to Reproduce

1. Send an email
2. Click on email stats
3. clicks always show as 0. see screenshot
![email_analytics___rock_rms](https://user-images.githubusercontent.com/1486523/41740105-099fd86e-7565-11e8-9f18-d012bb5c075d.png)

**Expected behavior:** 

Numbers to show up

**Actual behavior:** 

Numbers don't show up. 

### Versions

* **Rock Version:** 7.4 Alyssa told me she is on 7.3 
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by JimMichael** [comment]
We are also on SendGrid, and I can confirm that clicks on individual sent communications are not showing on 7.4, but Email Analytics shows overall clicks.

**Comment by cabal95** [comment]
We are using Mailgun and ours seem to be working, we are on 7.3 - unless I am misunderstanding.

![image](https://user-images.githubusercontent.com/1119863/41742480-f5ce3054-7552-11e8-97e1-dc1978e4dd0d.png)

**Comment by timlem** [comment]
So possibly a sendgrid only thing?

**Comment by JimMichael** [comment]
@cabal95 That looks like your overall Analytics. If you open a single email in communication history and click the analytics icon at the far right, do you see clicks? (assuming that email had links that could be clicked)

**Comment by cabal95** [comment]
Oh wow, @JimMichael is right. I never knew you could view that for individual communications because I always clicked on the *row* for to view the communication and then would look for a way to view analytics and never saw one. Whole new world baby!

Okay, so yes when looking at an individual communication analytics I see the same problem on Mailgun, so the problem is transport agnostic.

**Comment by timlem** [comment]
oops. I should have been more specific in the details above.

**Comment by ethan-sparkdevnetwork** [comment]
I am not able to reproduce the issue in 7.4 or 8.0. Steps to reproduce:
1. Created a communication (tried one recipient and multiple recipients)
2. Waited for email(s) to arrive
3. Opened emails and clicked on 0 to 3 links
4. Went to Communication History in Rock
5. Clicked the Email Analytics button in the far right column
6. View activity details, click numbers were correct.

In 7.4 I used mailgun SMTP and in 8.0 mailgun HTTP. I will try SendGrid next.

**Comment by morganw93** [comment]
We are using Mandrill and have the same issue!

**Comment by JimMichael** [comment]
@ethan-sparkdevnetwork I just reproduced this on v8alpha (and can produce it in 7.3), so I'm not sure why we're seeing differing behavior, other than the fact that we're using SendGrid. I followed your same steps, and while ON the sent communication I can see the clicks registered in the Activity list, but when I click on the Analytics button at the far right of the communication history list it shows no clicks. 
![image](https://user-images.githubusercontent.com/3903408/42108462-3365350e-7ba0-11e8-9de8-59f14575f179.png)

**Comment by arranf** [comment]
Just to add, I've gone through the SendGrid code and didn't see anything differing in the webhook between MailGun and SendGrid

**Comment by ethan-sparkdevnetwork** [comment]
For some reason the count for clicks is also checking the InteractionData column for not null or empty. This is usually where the clicked URL would go. I am guessing the webhook isn't parsing the data sendgrid isn't sending it. I can't think of a good reason for the check so I'll talk to a few people and probably remove it.

`DECLARE @ChannelId Int = ( select id from InteractionChannel where [Guid] = 'C88A187F-0343-4E7C-AF3F-79A8989DFA65')
DECLARE @CommunicationId Int = 160458

-- If InteractionData is null or empty then this will return 0 rows.
SELECT 
    i.[InteractionComponentId] AS [InteractionComponentId], 
    i.[InteractionDateTime] AS [InteractionDateTime], 
    i.[Operation] AS [Operation], 
    i.[InteractionData] AS [InteractionData], 
    i.[EntityId] AS [EntityId]
    FROM  [dbo].[Interaction] AS i
    INNER JOIN [dbo].[InteractionComponent] AS ic ON i.[InteractionComponentId] = ic.[Id]
    WHERE 
		ic.[ChannelId] = @ChannelId
		AND ic.[EntityId] = @CommunicationId
		AND ic.[EntityId] IS NOT NULL
		AND i.[InteractionData] IS NOT NULL
		AND LEN(i.[InteractionData]) > 0
	
-- This will give you the click counts for a communication regardless of the value in InteractionData
SELECT 
    i.[InteractionComponentId] AS [InteractionComponentId], 
    i.[InteractionDateTime] AS [InteractionDateTime], 
    i.[Operation] AS [Operation], 
    i.[InteractionData] AS [InteractionData], 
    i.[EntityId] AS [EntityId]
    FROM  [dbo].[Interaction] AS i
    INNER JOIN [dbo].[InteractionComponent] AS ic ON i.[InteractionComponentId] = ic.[Id]
    WHERE 
		ic.[ChannelId] = @ChannelId
		AND ic.[EntityId] = @CommunicationId
		AND ic.[EntityId] IS NOT NULL
		AND i.[Operation] = 'Click'`

**Comment by FrankGrand** [comment]
@MikeDPeterson @ethan-sparkdevnetwork  I've 'hot-fixed' this into our environments and confirmed that the clicks are now being reported, but the 'Popular Links' are still not.  Would this be a separate issue?

**Comment by ethan-sparkdevnetwork** [comment]
We are doing a NullOrEmpty check on the popular links also, but that is the field where the EmailAnalytics block gets the URL. I pinged Arran about the plug-in and he will take a look at it. At this point this seems to be an issue with the plugin or the data that SendGrid is sending to it.

**Comment by FrankGrand** [comment]
@ethan-sparkdevnetwork 
As per requested here are the numbers from our production db:
EmailClicksWithData: 40604
EmailClicksWithNullData: 26293
EmailClicksWithBlankData:75257

This is all with the Mandrill email transport
