### ISSUE TITLE
Communications: Simple Editor broken for most templates in v7.4

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#3087]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
Most (now "legacy") simple editor templates have at least some Lava in them.

The fix for #1810 however disallows the WYSIWYG editor for some of these templates, forcing staff into the HTML editor mode

### Steps to Reproduce
1. Verify Rock is on v7.4
1. Start a new communication
1. Click "Use Simple Mode"
1. Set the template to, for instance, `Sidebar`

**Expected behavior:**

The visual editor should show up like it always has, so Staff can simply enter the desired text

**Actual behavior:**

The code editor shows up and cannot be switched out of, so Staff has to navigate HTML
![<a href="https://user-images.githubusercontent.com/6932047/41784993-224555ec-75f6-11e8-9385-741f170bb821.png">https://user-images.githubusercontent.com/6932047/41784993-224555ec-75f6-11e8-9385-741f170bb821.png</a> image]()

### Versions
* **Rock Version:** v7.4
* **Client Culture Setting:** EN-US

**Comment by BEGamache** [comment]
Experiencing the same thing with some of our templates. The error goes away when I remove any of the lava that begins with {%. Regular merge tags work fine but the logic/conditional lava is what is throwing it off.

Although, once I've cut out the logic/conditional lava, and switch to the WYSIWYG, I can paste that lava back in and it works fine from there with the WYSIWYG editor.

**Comment by edmistj** [comment]
The problem here is that the WYSIWYG editor is corrupting the Lava in many cases. This isn't a specific issue with Summernote, but has been confirmed on TinyMCE and CKEditor. I don't think we can support 'Advanced Lava' (anything with a {%) in the WYSIWYG editor.

Comments and suggestions welcome. Otherwise I don't see an option but to close this.

**Comment by cabal95** [comment]
The corruption issue is the fact that it turns `<` into `&lt;` correct?  I realize this probably wouldn't be a quick fix (i.e. would take some time), but would a long term solution be to somehow modify the editor to only do that encoding if it's not inside a `{% %}` block?  Assuming that is even possible...

**Comment by edmistj** [comment]
The logic that does the encoding is built into the WYSIWYG editor, a place we don't have control over (unless we modify their source which would be a pretty deep rabbit hole).

**Comment by mikejed** [comment]
@cabal95 it's a different issue, I believe. See https://github.com/SparkDevNetwork/Rock/issues/1810

I wonder if there's a way to allow some advanced lava `{% assign %}` for instance, but not flow breaking tags like loops. I just really hate to see staff thrown into HTML editing where they weren't before.

I wonder if the cure for the above-linked issue isn't worse than the disease; between this and the image uploading issue Jim Michael brought up, and it seems like I remember one other issue that has come up as a result of disabling WYSIWYG when the input contains lava...

**Comment by jonedmiston** [comment]
I don't believe we'll be able to fix this behavior.
