### ISSUE TITLE
Location check-in threshold isn't respected

### ISSUE THREAD

**Issue by lpeterson1** [SparkDevNetwork/Rock#3088]
### Description
In prealpha site check-in, the location threshold isn't respected. The location is still available for normal check-in until the absolute threshold is reached.

### Steps to Reproduce
1. Set a threshold and (different) absolute threshold on a location
1. Check people in while watching checkin manager
1. Notice that even though the indicator in checkin manager has turned red (which should mean no further check-ins unless overridden) the location is available for new check-ins until the absolute threshold is reached. The indicator in checkin manager displays an accurate number.

**Expected behavior:**

The location should not be available for check-in once the threshold is reached

**Actual behavior:**

The location is available until the _absolute_ threshold is reached.

### Versions
* **Rock Version:** 8.0 (~~pretty sure this is working on 7.4, but can't test at the moment~~) also not working correctly on 7.3
* **Client Culture Setting:** en-US

**Comment by lpeterson1** [comment]
Let me do more testing before you dig into this. I can duplicate the behavior on 7.4 and 8.0 using the check-in test area, but not the normal schedules and location setup. I'll see if I can narrow it down some.

**Comment by lpeterson1** [comment]
This problem only seems to happen if there is more than one location assigned to a group in check-in configuration, which is why it happens in the test area. It can be duplicated on the demo site by adding another location to one of the existing groups, then checking kids into that group. Anytime a selected person is presented with a choice of locations it seems to ignore the "soft" limit for the chosen location.

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in 8.7 via commit 5df5c5a. To get strict enforcement use the "Enforce Strict Location Threshold" option in the Save Attendance workflow action.

![Enforce Strict Location Threshold](https://user-images.githubusercontent.com/35315117/229634092-ef5b722a-9fed-4e50-b1b8-88abbc2cf6a1.png)
