### ISSUE TITLE
Checkin manager threshold indicator is confusing

### ISSUE THREAD

**Issue by lpeterson1** [SparkDevNetwork/Rock#3089]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
The threshold indicator(s) in checkin manager only apply to the "soft" threshold, not the absolute threshold. This is how a location displays when the absolute limit is set to 5, and there is no soft limit. There is no indication that the room has hit the limit (actually, there's no indication that there _is_ a limit), other than that it is no longer available for check-in (and no one knows why). Also, when you drill down to the location, the "threshold" indicator says "none".
![screen shot 2018-06-22 at 2 17 33 pm](https://user-images.githubusercontent.com/37701239/41797514-8da8c18a-7627-11e8-8f73-9f7f5f936c8f.png)
![screen shot 2018-06-22 at 2 15 09 pm](https://user-images.githubusercontent.com/37701239/41797518-91374b32-7627-11e8-9b19-a2e105cdac89.png)

### Steps to Reproduce
1. Set an absolute threshold on a location (with no "soft" threshold)
1. Check people in until the threshold is reached
1. Notice that there is no indication in checkin manager that the location is full (or has a limit)

**Expected behavior:**

There should be some indication in checkin manager that the location is full. People suddenly can't check in, and it's not obvious why.

**Actual behavior:**

There isn't, and volunteers lose their minds.

One possible solution might be to make the absolute threshold field available only if a "soft" threshold is set (they can be the same); this seems to make the indication logical. Another solution might be to make the display different: something like green for "below the soft threshold", yellow for "has reached the soft threshold", and red for "has reached the absolute threshold". In any case, the threshold value on the location itself (drilled down in checkin manager) shouldn't say "none" when there _is_ a threshold.

### Versions
* **Rock Version:** 7.4, 8.0
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
