### ISSUE TITLE
Add Data Layer support for notes to have attachments

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3090]
# Feature Request

## Describe the Feature Request

The new functionality in v8 for notes makes them more useful. During a brief discussion with Jon we discussed the need for Notes to have a way to have file attachments. While nothing prevents a Note from including the `<a href="../GetFile.ashx?id=123>Attachment 1</a>` style code to link to and display an attachment, there would be no actual database references to the BinaryFile entity. Since there are plans to clean up orphaned BinaryFiles in the future, we need some way for notes to reference a BinaryFile so it doesn't get flagged for deletion.

## Describe Preferred Solution

Following the pattern of the FinancialTransactionImage, suggest creation of a `NoteAttachment` table/entity. This would be a bare bones table that would simply link a note with one or more attachments. When a NoteAttachment is deleted from Entity Framework it will update the BinaryFile.IsTemporary to true so that it will be cleaned up later by the rock cleanup job.

### NoteAttachment

The NoteAttachment would include the following columns/properties in addition to the standard entity properties:

* NoteId (INT, NOT NULL)
* BinaryFileId (INT, NOT NULL)
* Order (INT, NOT NULL - Is this needed?)

The `NoteId` column would be marked for ON DELETE CASCADE. This ensures that if a note is deleted via SQL that the NoteAttachment is also deleted. This would in turn cause the BinaryFile to be orphaned which could then later be detected and cleaned up by the (future) binary file cleanup process.

The `BinaryFileId` column would _not_ be marked for cascade deletion. This would ensure that a user cannot delete via SQL a BinaryFile that is currently in use by a Note without first deleting the Note (or the NoteAttachment).

I'm not sure if the `Order` column is needed? It's part of the FinancialTransactionImage table/entity. I'm guessing on that table it is used to know which image is the front and which is the back. In this use case it might be used if the attachments are displayed in a list, but such a list would probably be sorted by either name or upload time rather than sorted by a user-defined `Order`.

> The addition of the NoteAttachment would be a Data Layer implementation *only*. No support would be added directly to any Note editor UI for uploading and attaching files to notes. I do have some code for doing that type of thing which I use in the Project Management plugin that I would be willing to share as a starting point, but the functionality is different enough I don't think it would be a simple drop-in code addition.

### NoteType (Jon: This isn't something we discussed already)

The existing NoteType entity would get a new column:

* BinaryFileTypeId (INT, NULL)

This would specify if the note type allows attachments, and if so what binary file type to used for storing those attachments.

The existing UI for editing NoteTypes would be modified to include this field, with the help text indicating that this is only for those user interfaces that support it. For example, the functionality of adding a note to a Person may specifically not allow uploading attachments; while new functionality to use notes with a forum discussion plugin may allow attachments.

The hope is that the help text would grant us that "wiggle room" of time to implement attachment functionality in the various places notes are used. AND at the same time give us the room to say "attachments for this use case just don't make sense, we aren't going to support them even if the user flags the note type as allowing attachments". These could later be entered as feature requests - but I can certainly see times when attachments on notes just doesn't make sense for the _intended_ use of the note.

## Describe Alternatives

I considered building my own note attachment table for my current use-case, but after talking to Jon and knowing there was a plan to eventually put something similar into core, decided it would be better to build and submit a PR for core functionality.

## Providing Code

I will provide code if feature request is approved: **Yes**

# Feedback Needed

1. Proceed / Don't Proceed
2. Is the `Order` column needed?

**Comment by edmistj** [comment]
Please proceed. I don't think the Order is needed. 

Read though your `BinaryFileTypeId` on the NoteType. I think we should also add a 'AllowsAttachments' to the NoteType. I think you're idea of allowing the block to enable and disable attachments is also good, but that can act as an override to the setting on the NoteType. Otherwise if you had several note types on the person profile they'd all have to operate on the same settings. So perhaps the block could have a 'Disable Attachments' setting.

**Comment by cabal95** [comment]
Would you want an `AllowsAttachments` specifically, or would `BinaryFileTypeId == NULL` be good enough indication for that?

i.e. if BinaryFileTypeId == NULL, do not allow attachments. If NON-NULL, allow attachments and use the indicated binary file type.

**Comment by edmistj** [comment]
I was tossing that around in my mind and I think specific configuration values are better than implied. In this case we should use `AllowsAttachments` and if checked require a `BinaryFileType` to be selected.
