### ISSUE TITLE
Communication Set Image Link Not Keeping Value

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#3094]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
Once an image link has been set, when adding another response recipient (in simple) or when changing to a new content zone (wizard) the image link is lost.

### Steps to Reproduce
1. Go to New Communication
1. Click on Use Simple Editor
1. Insert an Image
1. Set a Link on the Image
1. Add a recipient to the Communication

**Expected behavior:**

That link should persist on the image.

**Actual behavior:**

That link is lost.

### Versions
* **Rock Version:** Rock McKinley 7.4 (1.7.4.58)
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
Updated the RockImageLink summernote to set the changed event after creating the image link.
