### ISSUE TITLE
Documentation on NewlineToBr is incorrect

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3095]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The documentation for NewlineToBr states that it `Convert all new line characters to HTML <br/> tags.`. But that is not the case. Looking at the code what actually happens is the ADDS a `<br />` tag before the newline characters.

For HTML display this is fine, but when using it for other uses (such as JSON encoding) it causes issues since the newline character is still present. Documentation should be updated to reflect what the filter actually does.

### Versions

* **Rock Version:** Latest Docs
* **Client Culture Setting:** en-US

**Comment by garrettjohnson** [comment]
Changed documentation to `Add <br /> tags in front of all newlines in the string`
