### ISSUE TITLE
Auto Login for iPad for checkin purposes

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#3096]
# Feature Request

**Describe the Feature Request**
We use iPads for a lot of our checkins for adults.  They work great... until apple autoupdates (can't turn it off yay Apple) and forgets the username/password for our checkin kiosks.  When that happens it boots to the Rock login screen instead of to the Rock checkin screen on the Rock Application.

**Describe Preferred Solution**
We currently use short links to pass our URL config to the iPads.  

Have it built into the Rock App via a config entry

Or: If we could either build in a URL key like /checkin/2/4/18,19/username/password but with login credentials

Or: put it as a config option in the shortlink setup to pass credentials so it isn't necessarily visible via html.

**Describe Alternatives**
The only other alternatives we have heard of to alleviate this is to put our iPads on a subnet/vlan that does not have access to Apple's Push Notification server which is a no go since we manage them via JAMF which requires that.

**Providing Code**
I will provide code if feature request is approved: [Yes/No]

**Comment by garrettjohnson** [comment]
@markewampler Have you experimented with the [PersonTokenCreate lava filter](https://www.rockrms.com/lava/filters/person-filters#persontokencreate)? That would provide to build the URL key with login credentials. `http://[...]/checkin?rckipid=GENERATEDKEY`

**Comment by markewampler** [comment]
Nope.  I'll see if that will work.

**Comment by markewampler** [comment]
ha that worked!

**Comment by JimMichael** [comment]
@ajfick You can pass the filter the a minutes parameter https://www.rockrms.com/lava/filters/person-filters#persontokencreate So something like 2628000 would be 5yr.

**Comment by edmistj** [comment]
@ajfick Thoughts on the solutions provided?

**Comment by ajfick** [comment]
@edmistj what @JimMichael pointed out makes perfect sense to me! I just didn’t know if there was some sort of upper limit to the ‘PersonTokenCreate’ lava filter.

**Comment by edmistj** [comment]
@ajfick doesn't look like there is a limit. I like Daniel's idea of supporting basic auth, but if this get's you by then let's close the issue and I'll add basic auth to the future feature list.

**Comment by ajfick** [comment]
@edmistj I'm totally satisfied with the person token option.
