### ISSUE TITLE
Changes to adding Known Relationships

### ISSUE THREAD

**Issue by ajfick** [SparkDevNetwork/Rock#3101]
# Feature Request #

**Describe the Feature Request**

The modal for adding known relationships should include options to quickly connect people who are already in the person's family. It would also be great to see some slightly changed wording for this section to be clearer about who is related in what way.

**Describe Preferred Solution**

Show an image and the name of each person in person's family in the modal along with a person picker for adding relationships with people outside the current family (like shown currently). Also change the verbiage to read clearer and more like a statement with fill in the blanks.. "`Johnny` is Person's `child`"

![relationships](https://user-images.githubusercontent.com/19314419/42169334-67099826-7de1-11e8-8ed5-b318070caa41.jpg)

**Describe Alternatives**

If adding people from the current family to the modal is not possible, a change in verbiage would be really great due to some users confusion when selecting things like "Child", or "Can Check In" they are not sure if they are selecting that the selected person is the Child, or if the person that they choose in the modal is the Child and the same goes for "Can Check In" and other "One way" relationships. 

Finding a way to highlight which people are in the current family on the person picker would also be a great option. For example if I am adding a "Previous Spouse" relationship to John Doe but we have 20 Jane Doe's it becomes hard to tell which one is correct when you can't see enough info about the Jane Doe in the current family while the Modal is open. 

**Providing Code**

I will provide code if feature request is approved: No

**Comment by chead4** [comment]
@ajfick   Hi AJ, this is an oldie but goodie enhancement request.  It appears a similar request is on the Rock Ideas board - https://community.rockrms.com/ideas/187/enter-multiple-known-relationships-at-the-same-time .  If this is an enhancement you want to use your voting points on, I’d ask you to jump over to the idea and vote it up.
