### ISSUE TITLE
On 7.4 Checkin Client does not auto start on the field for entering name/number

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#3102]
### Prerequisites
* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### After upgrading to v7.4 our windows client Checkin devices do not automatically highlight the text field for entering name/number. I tested on prealpha as well and got the same results. So basically on the check in screen on windows app when you hit start it goes to the screen to enter name/number but the field is not selected like it was previously. So our non-computer savvy people are struggling.  

A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce

1. Open Windows Checkin Client
2. Go through checkin setup
3. Click Start
4. Try to enter name/number and the field is not automatically highlighted to receive the data from the keyboard like it was prior to v7.4

**Expected behavior:**

1. Open Windows Checkin Client
2. Go through checkin setup
3. Click Start
4. Enter name/number and search without having to click the form field to activate it.

**Actual behavior:**

See above

### Versions

* **Rock Version:** [7.4]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by garrettjohnson** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/3ee9138d9c88c2aacf6645246f0f910c1fc08255
