### ISSUE TITLE
Add example Crons to the Scheduled Job Detail block.

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3103]
# Feature Request

**Describe the Feature Request**

Update HelpText of the Scheduled Job Detail block to provide two examples that the user can start from. Usually I am building either a daily job or a weekly job. Providing these two examples will save time of having to swap over to the CronMaker site to build one.

**Describe Preferred Solution**

Update HelpText as follows:

<img width="341" alt="2018-07-02 13_48_00-scheduled job detail _ rock rms" src="https://user-images.githubusercontent.com/1119863/42185711-c699e738-7dfe-11e8-8873-b7cd47d5fca3.png">

**Describe Alternatives**

None.

**Providing Code**
I will provide code if feature request is approved: **Yes**

**Comment by edmistj** [comment]
This is fine as a PR as long as Monday and Friday are capitalized in the help text.
