### ISSUE TITLE
Event Registration Security on Instance (7.4 only) and Payments (8.0/7.4)

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#3120]
### Description

In 7.4 there is a bug with checking Edit security on RegistrationInstance that's been fixed in v8.  The Staff Worker role is allowed to Edit the instance when the security role is not defined to do so.  I searched but couldn't find an issue reporting this.

In both 7.4 and v8, the Staff Worker role can view the Payment section of a registration, with no configurable setting to limit that view.  Staff Workers also have a clickable View/Edit Payments button, but it doesn't do anything (only roles with Edit rights get the Process Payment buttons).  This button should be hidden unless you have Edit rights.

### Steps to Reproduce

1. Log in to [v8 Demo](http://prealpha.rocksolidchurchdemo.com/RegistrationInstance/1) as tdecker / tdecker (account with Staff Worker role)
2. Click on a Registrant
3. Click View/Edit Payments
4. Open tickets about broken Payment functionality

![screenshot 2018-07-10 14 07 46](https://user-images.githubusercontent.com/1210933/42529092-844bbb1a-844b-11e8-81bb-bc75866491b7.png)

![screenshot 2018-07-10 14 13 48](https://user-images.githubusercontent.com/1210933/42529105-8baa7ce8-844b-11e8-82da-c09c576227c0.png)

**Expected behavior:**

`View/Edit Payments` does not show unless you had Edit rights.  

**Actual behavior:**

You can click View/Edit Payments as a Staff Worker.

### Versions

* **Rock Version:** 7.4-8.0
* **Client Culture Setting:** en-us

**Comment by edmistj** [comment]
I'm not sure it makes sense to have to have `Edit` rights to `View` payments. I agree the link button text is a little misleading, but the block does not allow you to edit payments unless you have `Edit` rights.

We'll rename the link button from `View/Edit Payments` > `Payment Details`.

**Comment by ethan-sparkdevnetwork** [comment]
Renamed the button to Payment Details to accurately describe its function.
