### ISSUE TITLE
Transaction Detail block displays the Financial Gateway component rather than name

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#3128]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
If you are going to import a bunch of Financial Transactions, it is probably a good idea to create a new Gateway to avoid potentially matching on Transaction Codes. Being that this is really just a placeholder, you _should_ be able to use the Test Gateway gateway type.

Problems is, when you go to view the transactions, they all show to be tied to the gateway called TestGateway. If you click edit and actually view the detail, it shows the correct gateway.

### Steps to Reproduce
1. Create a new Financial Gateway of type Test Gateway
2. Create a transaction and attach it to the new gateway
3. View your transaction, notice that your Gateway is TestGateway
4. Click Edit and notice that your Gateway is now displayed correctly.

**Expected behavior:**
I believe the actual Gateway name should be displayed. https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.7.4/RockWeb/Blocks/Finance/TransactionDetail.ascx.cs#L1341

This should probably be: `txn.FinancialGateway.Name`
Not: `Rock.Financial.GatewayContainer.GetComponentName( txn.FinancialGateway.EntityType.Name )`

**Actual behavior:**
Component Name is being used.

### Versions

* **Rock Version:** 7.4
* **Client Culture Setting:** en-US

**Comment by mikejed** [comment]
Confirmed on 7.4 and prealpha demo server. I feel it should also be noted that when a transaction is added to a batch, you can go in and out of the transaction several times while `transactionId=0` remains in the URL. While that's the case, "Payment Gateway" is not visible on the transaction. It's not until you go back to view the batch and then come back in to the transaction record, that the URL indicates the actual transactionId and the "Payment Gateway" option shows up.

Is there a reason that "Payment Gateway", alone of all of the transaction properties, cannot be set when creating a new transaction?

**Comment by ethan-sparkdevnetwork** [comment]
Changed the detail to display the Gateway name instead of the type. Added logic to display the type only if the name is null or empty.

The payment gateway is not shown for new transactions because if it being entered manually then it is not coming from a gateway (or so I am told).
