### ISSUE TITLE
Fundraising Participant Page lists incorrect donation amount next to donors.

### ISSUE THREAD

**Issue by hbcfw** [SparkDevNetwork/Rock#3133]
### Description

We have noticed on the Fundraising Matching, that when a contributor gives to a Fundraising Opportunity and tithes on the **same** check, even though the tithe goes to a tithe account and the missions trip goes to a trip account, the trip participant can see the **entire** amount combined on their participant page.
The Fundraising Progress "progress bar" calculates everything correctly.  But in the list of donors below, it gives the entire check amount, rather than just the trip donated amount.
E.g. if I give $1,000 to the church but only give $100 to the Fundraising Opportunity, my entire $1,000 tithe is listed on the participant's page.

### Steps to Reproduce

1. Create fundraising opportunity
2. Person writes a check, designating a portion of the check to Fundraising opportunity
3. We assign the funds to the appropriate accounts.

**Expected behavior:**

Participants would only see portion that was designated on their list of Financial Transactions
**Actual behavior:**

Participants see the entire gift of the donor.

### Versions

* **Rock Version:** Rock 7.4 (1.7.4.58)

* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
I believe this was already fixed and will be available in the future 8.0 release. See original issue here: #3009. Once 8.0 is released if the problem persists please re-open this issue.

**Comment by treyhendon** [comment]
Unfortunately I don't think this is fully resolved @cabal95 .

https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Fundraising/FundraisingParticipant.ascx#L62

That's the Transaction Total Amount, not Transaction Details Amount.

I just wrote a fix for RVC that I'm happy to write a pull request for.  Just used a literal in the grid and then used the logic that was updated in the Transaction Entry block to populate the value of the literal.

**Comment by nairdo** [comment]
Just for clarity sake, as I've just walked through in an attempt to reproduce the problem, this is what Trey's pull-request should be resolving.  Although "Ted" donated $500 on a check, only $50 was appropriated/matched to the Admin Admin's China trip.  Although the fundraising progress is correct (10 previous + 50 from Ted - 200 goal = 140 remaining) the $500 shown below in the details section should be $50.
 
![image](https://user-images.githubusercontent.com/383807/47860405-ae690900-ddad-11e8-8642-359f3066b2a2.png)
