### ISSUE TITLE
Enhancement: Interaction Component Internal Name

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/Rock#3134]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
Add an option to reference a page's alternate Names. Specifically the pages `Internal Name`
Currently, when referencing data from the `InteractionComponent` table, you can query based on the `Name`. This can be confusing if you have more than one page with the same name. I'm not sure _how_ the `InteractionComponent.Name` field is populated (as it doesn't seemed to be linked to the `Name` field of the pages table).

### Steps to Reproduce

1. Create 2 pages with the same Page Title and Browser Title. They should have different _Internal Name_ values
2. Go to the Interactions page
3. Browse to the channel that contains the pages you created in step 1
4. Examine the list of 'Components' (pages in this case)

**Expected behavior:** 

The 'Name' functionality is based on the pages `Internal Name`, or for further improvement also make the page's Internal Name, Page Title, and Browser Title all available for the Lava used.

**Actual behavior:** 

The page (and stock lava) references the column `InteractionComponent.Name'. Using the SQL Map I can find no option to reference a name column besides 'Name'
Example: I have 2 pages with the Page Title & Browser Title of 'Give' .... they both show as 'give' in the interactions components list
![image](https://user-images.githubusercontent.com/8688424/42854737-eee72100-8a02-11e8-9387-496448de9e1c.png)

### Versions

* **Rock Version:** [7.3]  
* **Client Culture Setting:** [en-US]

**Comment by mikejed** [comment]
It looks like this will be improved by https://github.com/SparkDevNetwork/Rock/commit/1dd3dba79a08752a44bf83bfd927ef72469ca96a , but that still picks "one" of the possible page names to store in Interactions. This new behavior will probably be what's desired a vast majority of time, but this enhancement request would be to give the admins the option of which title is stored. Since there may be times you want to use one of the titles besides what is actually sent to the browser, this may still be considered.

**Comment by smross** [comment]
So, I'm not a dev, but with my little knowledge of SQL and Lava, why wouldn't the 'Name' function in interactions be linked to a column in a different table? For example, from my viewpoint the Person table links to the PersonAlias table, and many things link back to the personalias table. Does a _flow_ like that make sense for this kind of situation?

That may be over simplifying a complicated question, but I didn't know if it was worth considering from that angle.

**Comment by edmistj** [comment]
In the latest version the `InteractionComponent` name comes from the browser title. This allows a single page to have multiple components if the browser title is different. This is nice on a page that shows content channel item details (like a blog). In this case the component would represent the detail for each item.

Having this be configurable by site would be possible, but it seems like the current behavior would be desired by a majority of users.

Going to close this now. We can re-open if there is more interest in the future.
