### ISSUE TITLE
Family Pre-Registration Indicates Required Fields For Second Adult Incorrectly

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3136]
### Description

The Family pre-registration block lets you define which fields are required (.e.g Gender). When viewing the form, _both_ First and Second adults show red dot indicators for required fields, but this is misleading if you're only entering one adult.

### Steps to Reproduce

1. Go to http://prealpha.rocksolidchurchdemo.com/FamilyPreRegistration
2. Observe that Gender shows as Required for both First and Second adults.
3. Enter info for only First Adult and the form will submit fine (even though Second Adult is indicating those fields are required to submit the form.)
4. Enter a first of last name for Second Adult (e.g. First Name) and now the required fields are enforced there, too.

**Expected behavior:**

Second Adult wouldn't show required fields until they are actually required (meaning, you started entering info on Second Adult.)

**Actual behavior:**

The UI is confusing because it's implying that you must enter info for both adults in order to submit the form. I looked back through an email exchange I had with @azturner when this block was being tested (as we sponsored it) and in one of his replies he said 

_We’ll update the ‘First Adult’ fields so that the required fields do have the indicator. For the ‘Second Adult’ field, we’ll make it so that the required fields won’t initially be required, but as soon as a value is entered into the first or last name, they would then change to be required (with the red dot)_ 

It looks like this is mostly working that way, except that the red dots are always indicated on second adult when they are not required.

### Versions

* **Rock Version:** 7.4-8.0

![image](https://user-images.githubusercontent.com/3903408/42904507-e8169a84-8a9a-11e8-8ec5-66179d3e2f26.png)

**Comment by edmistj** [comment]
Got it Jim! Sorry it was missed we'll get this addressed in v8.1.

**Comment by ethan-sparkdevnetwork** [comment]
Added some js to show the required dots on Adult 2 if the first and last name have values. The change happens on blur.
