### ISSUE TITLE
Editing Comments on Q&A Is Broken

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3137]
### Description

Editing a _comment_ on the QA (rockrms.com/ask) does not work. It results in a blank editor with no existing content.

### Steps to Reproduce

1. Go to any post on the QA or make a new one.
2. Add a comment to an exiting post
3. Edit your comment and observe an empty editor

**Expected behavior:**

You'd be able to edit your comments.

**Actual behavior:**

You can't. Note this only seems to be an issue with _comments_ as editing a question or answer works fine. This was with Chrome 67 on Win10.
![qa](https://user-images.githubusercontent.com/3903408/42959045-0a042974-8b4d-11e8-978d-f020f3c5bac0.gif)

**Comment by JimMichael** [comment]
Ah, I didn't notice this before posting, but it looks like clicking Edit on a comment just brings up NO UI to edit... the "Your Answer" editor is supposed to be empty in this case. Duh.

**Comment by mikejed** [comment]
Jim, I'm not being able to reproduce this yet. Also Chrome 67 on Windows 10 🤔 Can you try a few other threads/configurations/computers to see if it's consistent for you, and I'll do likewise?

**Comment by JimMichael** [comment]
I've now tried it on various threads, different browser (Firefox) and a different computer... all have identical results. I notice the _Add Comment_ really seems to be a note... is it possible you have rights to edit notes via you being with Spark vs. a normal user like me?

**Comment by cabal95** [comment]
I can't find one of my existing posts with a comment that I left, but I have permissions to edit other people's comments and I see the same UI issues as Jim. I get an empty editor at the bottom of the screen.

**Comment by JimMichael** [comment]
Just to clarify... the empty editor at the bottom is supposed to be there... it's the editor to ADD a new answer to the original question... it's just confusing-looking because it jumps up into view when you click Edit on a comment, because the space the comment took goes away... so what I'm seeing is no editor at all when clicking Edit on a comment.

**Comment by cabal95** [comment]
Gotcha. Then I'm also seeing the same. :)

**Comment by mikejed** [comment]
I wonder if it's a permissions thing now. Here's what I see when I click "Edit" on one of my previous comments:
![image](https://user-images.githubusercontent.com/6932047/42972294-d466ad0c-8b63-11e8-9b47-ba1f50811a3e.png)

**Comment by mikejed** [comment]
Feel free to use https://www.rockrms.com/Rock/Ask/Using/Questions/1996 to freely test if needed. I'm able to edit all of my comments; at the bottom of the page, in the middle of a page, on accepted and unaccepted answers alike. I do see that line breaks in comments are lost now, however.

**Comment by JimMichael** [comment]
Yup, same behavior. Clicking edit on any of your comments causes it to disappear until I refresh the page again.

**Comment by mikejed** [comment]
(hmm, I never knew we could edit others' comments, ha! regardless, I can still edit yours in other threads). I'll suggest to Nick that it could be a permission issue.

**Comment by JimMichael** [comment]
Also note that the original poster where I found this issue says he doesn't see the "Add Comment" link at all, so it does appear to be rights.

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/1b47c7cfaa2cb1ff123f13a6ec6396fe3528ae4e
