### ISSUE TITLE
Giving and Pledge Analytics Names Inconsistent

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#3139]
# Feature Request
**Describe the Feature Request**
Currently Giving Analytics has the persons name as Last, First.  Pledge Analytics has the name as First Last.  So some text gymnastics in Excel is needed to match up giving and pledges in one spreadsheet.  Names have a variety of formats, so while it's easy to handle the basic case, there are always goofy exceptions. **It would be nice if they were consistent** and therefore easy to match.

**Describe Preferred Solution**
Personally, I'd prefer a Full Name including suffix (like George W. Smith, Jr.) because we are large enough we have a bunch of Jr and III in the congregation.  But consistent is the main thing.

**Describe Alternatives**
Another option that would resolve duplicate names would be to include something like the Giving Leader Id or a Person Id field that would link between the two.  But I'm not sure that would be intuitive to most.

**Providing Code**
I will provide code if feature request is approved: No - not that skilled yet.

**Comment by nairdo** [comment]
Solution:
Change the Pledge Analytics block to be Last, First.
