### ISSUE TITLE
Event Registration Form Registration Attributes do not display

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/Rock#3142]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When you create a Registration Attribute for an Event Registration Form, and populate the description of the Registration Attribute, the description is not exposed/used as part of the UI, and not used/available as 'helper text' for the attribute the registrar is choosing.

### Steps to Reproduce

1. Create an Event Registration Template
2. As part of the form, add a Registration Attribute
3. Fill in a description for the Registration Attribute
![event registration _ rock rms - google chrome 2018-07-23 12 12 36](https://user-images.githubusercontent.com/8688424/43092213-05cf680a-8e72-11e8-9bff-494659d74fb9.png)

**Expected behavior:**

If populating the `Description` field for the Event Registration Registration Attribute, it should be possible to expose/display the description to the registrar. Preferably as a 'helper text' toggle, ala other UI elements in Rock, such as the process used on Workflow Forms.

**Actual behavior:**

The `Description` is not used/exposed to the registrar
![smr registration attribute test 1 _ external website - google chrome 2018-07-23 12 13 40](https://user-images.githubusercontent.com/8688424/43092204-00444b1c-8e72-11e8-87e6-112a20c5ce00.png)

### Note/To Consider:

I don't know if the following upcoming changes to v8 make this a moot issue/request. Here are the portions of the v8 Alpha release notes that may apply to this:
* Added a new Registration Instruction field to Registrations that will be displayed on the first page of a new registration.
* Added the ability to provide instructions on Event Registrations.

### Versions

* **Rock Version:** 7.3, 7.4
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by smross** [comment]
I may have gotten lucky (I'm not familiar w/ how coding and Github works in detail) and found where this _has_ already been addressed.

Does [commit 06a68e9](https://github.com/SparkDevNetwork/Rock/commit/06a68e96b02f720fe4b9d52b39042f5003a733d3#diff-ea102c78c5690f2b20a19a6d27b0c46b) handle this functionality?

**Comment by cabal95** [comment]
I believe that will address this issue (though you will have to remember to enable it in the block settings).

**Comment by edmistj** [comment]
We'll change that to be defaulted to true as that would seem to make the most sense.
