### ISSUE TITLE
ScheduleBuilderPopupContents cannot be used directly

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3144]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
I am trying to build a control to let me build a "schedule collection" entity, i.e. a single entity that contains multiple schedules so we can build complex scheduling needs.

Example of a single complex schedule: Every Saturday from 4pm - 8pm AND every Sunday from 7am - 1pm AND every Wednesday from 5pm - 8pm.

The basic implementation is a grid that shows the "friendly name" of each individual iCal schedule content. You can click the row to edit, click the X to remove, or click the Add button to add an additional schedule component. When you save, all that schedule data would be stored in a single entity. The reason I am doing it this way is to make it simpler for the user so they don't have to go to the standard Schedule editor, create a schedule, then come back to my page and add it into the "complex schedule" entity.

While the ScheduleBuilderPopupContents  class itself is public and works perfectly fine, the public `iCalendarContent` getter doesn't actually return anything useful, it simply returns what you initially set. the method to get the _actual_ contents, `GetCalendarContentFromControls` is marked as internal.

Currently, I am using Reflection to call the `GetCalendarContentFromControls` method and it is working perfectly(1), but it would be nice if that method were either made public OR if the `iCalendarContent` getter called the `GetCalendarContentFromControls`.

Note 1: For the purposes of this feature request, it's working correctly. There is a minor bug that is somehow making the text boxes not clear correctly when you try to re-use the control without a full page reload. I've worked around it as I can't figure out what the core problem is.

I'm willing to provide code changes: **Yes**

### Versions
* **Rock Version:** 7.4
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
