### ISSUE TITLE
PMM background check (Seven Year Automatic) incorrectly marked for review

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3147]
### Description

We just started using the Seven Year Automatic package for PMM, and our requests are being marked as needing review even though there were no records found. Looking at the logs, the response contains orders with either a `<Status>NO RECORD</Status>` or `<Status>COMPLETE</Status>`. The current code seems to only check for "NO RECORD" and assumes anything else is an alert ([ProtectMyMinistry.cs#L592](https://github.com/SparkDevNetwork/Rock/blob/5cb24200bff66000d81480df93f2c70b722da50f/Rock/Security/BackgroundCheck/ProtectMyMinistry.cs#L592)).

### Steps to Reproduce

1. Request a background check with the "Seven Year Automatic" package.

**Expected behavior:**

Clean reports don't need reviewed.

**Actual behavior:**

All reports need reviewed.

### Versions

* **Rock Version:** 7.4  
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@Tschrock I'm reviewing your solution for this issue, but I need to verify that the a PMM status of NO RECORD **_and_** COMPLETE should both mean a status of "Pass".  If so, as our admin guide states, this would mean no one will be notified to review the results:

```
If the check comes back with a status other than 'Pass' the workflow will notify the
individuals in the 'Background Check Administrators' application group to review the
results and determine if the background check should be passed or failed. The results 
will then be emailed to the requester.
```

I'm having a hard time tracking down details about what the various PMM statuses should indicate.  How did you reach your conclusion about the "COMPLETE" status?

**Comment by nairdo** [comment]
Ok, but now I'm not in favor of taking that pull request.

**Comment by nairdo** [comment]
Ok, after further review -- it's confirmed that we can't just automatically "pass" something that's "COMPLETE" because it depends on what is actually in that report. So, unless PMM changes their internal flagging process, a human will need to review and decide if it is a pass.

**Comment by Tschrock** [comment]
Agreed, though I still don't like that it means all reports using the Seven Year Automatic package - which we use for all of our volunteers (~50 reports a month) - would need manually reviewed. We don't currently use any of the other services, so our modifications are fine for our use-case, but it would be nice to have a better, more universal solution.

**Comment by MicahO** [comment]
I've confirmed with PMM that the exact same "SSNTrace" is taking place in *ALL* PMM background checks, but it's only being marked as "COMPLETE" in SOME of them. In others it's just being ignored. There's not really a way to "fail" a SSNTrace, it just says where the person has lived.
