### ISSUE TITLE
Workflow changes are not implemented until cache is cleared

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#3151]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

There is a situation where you create a workflow, run it, and then edit it -- adding in a new action, however the new action is not executed until the cache is cleared.

### Steps to Reproduce

1. Create a custom workflow with two actions.
2. Enable full logging.
3. Run the workflow.
4. Examine the log.  Note all actions are run.
5. Edit workflow and add a third action.
6. Save and run workflow, then examine log.

**Expected behavior:**

The new action added in step 5 should be showing as executed but it does not.

**Actual behavior:**

The new action is skipped until you clear the system cache.

![image](https://user-images.githubusercontent.com/383807/43471955-209b95ca-94a1-11e8-86a2-48292de78b9e.png)

Once you clear the cache and run the workflow, you see the third action executes:
![image](https://user-images.githubusercontent.com/383807/43472056-599c93a6-94a1-11e8-95c6-0e748e033886.png)

### Versions

* **Rock Version:** v8.0
* **Client Culture Setting:** en-us

**Comment by mikejed** [comment]
Plausibly related, if you make any changes to a User Entry Form action (such as showing or hiding a control, adding or changing any pre- or post-html to a field or the form itself, the changes will not take effect until the cache is cleared as well.

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/c5801104e4007337c65570f6fbea2c7043c117d7
