### ISSUE TITLE
First Contribution Date dataview filter does not filter Dates correctly

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#3155]
### Description

The First Contribution Date dataview filter is unreliable when compared to Giving Analytics using the same accounts, date range, and First Time partition.  After checking the [code](https://github.com/SparkDevNetwork/Rock/blob/1.8.0/Rock/Reporting/DataFilter/Person/FirstContributionDateFilter.cs#L318), the DV filter ignores Transaction.TransactionDateTime and uses the Transaction's FirstSundayDate instead.

This is a serious disconnect between a user's expectations and actual behavior when setting up a First Time Givers DataView targeting a specific date range.  I've confirmed this on v7.4 as well as v9.0 demo.

#### Find a user (Alisha Admin) who's given for the first time to an account:

![screenshot 2018-08-01 10 34 41](https://user-images.githubusercontent.com/1210933/43528908-0c9529c4-9578-11e8-883d-99ce913152bc.png)

#### Confirm that the Transaction posted during on 7/20:

![screenshot 2018-08-01 10 34 28](https://user-images.githubusercontent.com/1210933/43528972-2ebb59a6-9578-11e8-9df7-7a92547caff0.png)

#### Set up a dataview filter for First Contribution Date between 7/14 and 7/21:

![screenshot 2018-08-01 10 36 15](https://user-images.githubusercontent.com/1210933/43529016-4cac4c54-9578-11e8-9c17-f3358c8cd0e2.png)

#### Confirm that Alisha's first time gift is not included:

![screenshot 2018-08-01 10 35 02](https://user-images.githubusercontent.com/1210933/43529066-6eee34ee-9578-11e8-839a-5a814a4c16f7.png)

**Expected behavior:**

The First Contribution Date filter would filter by the First Contribution Date.

**Actual behavior:**

The First Contribution Date filter filters by the Sunday following the First Contribution Date.

### Versions

* **Rock Version:** v7-v9
* **Client Culture Setting:** en-us

**Comment by edmistj** [comment]
Dev Note: The report select has similar usage of the Sunday Date.

**Comment by ethan-sparkdevnetwork** [comment]
Added a "Use Sunday Date" option to the "First Contribution Date" Data View filter. If the option is selected then the SundayDate property is used, if not then the actual TransactionDateTime property is used. For data views that were created prior to this option SundayDate is used to maintain current functionality. To use TransactionDateTime simply open and save the data view.

**Comment by dcs619** [comment]
Thanks @ethan-sparkdevnetwork, will this be available in 1.8.4 or soon after?

**Comment by ethan-sparkdevnetwork** [comment]
Sorry I forgot to add the label. This was changed in v9.0.
