### ISSUE TITLE
Group Sync can add person to security role multiple times

### ISSUE THREAD

**Issue by stevelipinski** [SparkDevNetwork/Rock#3156]
### Description
People are allowed to be doubly-included in a Group if the group is synced from a data view.  Secondary issue is that the group sync Job can apparently run multiple instances simultaneously (causing duplicate group membership)

(Tested with Security Role, but would assume this applies to groups in general.)

### Steps to Reproduce
1. Create a DV including a large number of people (~1800 in my instance)
1. Create a Security Role synced from the DV
1. Manually start the Group Sync job a few seconds before the next automatic run.

(In my case, job runs every 15 min.  I manually ran job roughly 15 sec before the quarter-hour, knowing that the sync of this initial large DV takes over a min)

**Expected behavior:**

\# Members in new Security Role  == \# People in DV

**Actual behavior:**

\# Members in new Security Role > \# People in DV
(because many people are in Security Role/Group twice - confirmed in Person's profile page)
In my case, I had 1800 people in DV, and 3200 people in new Security Role.

### Versions
* **Rock Version:** Rock McKinley 7.4 (1.7.4.58)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1107317347851852">image.png</a>

**Comment by mikejed** [comment]
Confirmed on 8.0 alpha 2 also

**Comment by edmistj** [comment]
Dev Note: Should confirm manual running respects the [DisallowConcurrentExecution] and that Quartz counts jobs run manually as running.

**Comment by bdeneal** [comment]
I can confirm that this applies to groups in General. Had a group that was linked to a data view and the Dataview showed quantity of 4010 and the Group showed quantity of 6130.
