### ISSUE TITLE
Many workflow actions don't properly handle encrypted attribute types

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3159]
### Description
After some testing and looking through the code, it appears that many of the attribute-handling workflow actions don't properly encrypt the value when saving them.

These actions seem to properly save both `Encrypted Text` and `SSN` attributes:

* Attribute Set Value

These actions only properly save `Encrypted Text` attributes:

* Person Attribute Set

These actions don't properly save any encrypted attribute types:

* Benevolence Request Set Attribute
* Group Attribute Set
* Group Member Attribute Set
* Entity Attribute Set
* Lava Run
* SQL Run

### Steps to Reproduce
1. Create a workflow that uses any of the above actions to save a value to an encrypted attribute.

**Expected behavior:**

The value is saved encrypted.

**Actual behavior:**

The value is saved in plaintext.

### Versions
* **Rock Version:** 7.4
* **Client Culture Setting:** en-US

**Comment by EthanW96** [comment]
Confirmed in production instance of Rock v9.2. I checked a couple actions with the UI and then inspected the code in release v9.

Only the two actions mentioned above by @Tschrock have Security.Encryption.EncryptString method calls according to the Find in Files in Visual Studio.
![image](https://user-images.githubusercontent.com/8846891/67503537-680b5a80-f64d-11e9-8f81-914db15475ff.png)

The remaining six actions mentioned above have no such logic to encrypt the appropriate attributes.
