### ISSUE TITLE
[EN] General Enhancements to Checkin Manger Person Profile

### ISSUE THREAD

**Issue by ajfick** [SparkDevNetwork/Rock#3161]
# Feature Request
**Describe the Feature Request**
We would love to see the Person Profile page of the checkin manager `/page/301?Person=GUID` be more like the standard Person Profile page `/Person/{Id}`. As it is now the Check In Manager Profile Page does not pass the Person Context to blocks on the page. 

For example if you wanted to add the Childhood Information `Attribute Value` block to the page to quickly be able to view allergies/legal notes etc you would have to add `&personId={Id}` to the query string manually or via redirect because those blocks require the `&personId={Id}` query string parameter.

**Describe Preferred Solution**
Honestly I think it would be great for the Check In Manager Person Profile Page to be nearly identical to the Person Profile page. It would give users the most ability to customize that page with whatever information they feel is important for Kids Min workers, or Security to have access to during the day. 

It would allow for easy implementation of "Attribute Value" blocks as well as any other blocks that need the Person Context. 

**Describe Alternatives**
An alternative to this would be just to extend the settings/configurability of the Person Profile block that is already on the page by default. Adding options like an attribute selector to display person attributes selected by administrators, Number of Check In History Entries to display, Which Known relationship types to display etc. 

**Providing Code**
I will provide code if feature request is approved: No

**Comment by jrockman13** [comment]
I think I would prefer the alternative solution. We typical use Check-In manager on smartphones, and it would introduce a lot more scrolling down if the whole person profile was displayed.

**Comment by ajfick** [comment]
@jrockman13 Yeah, I don't necessarily think that it needs to be an exact replica of the Person Profile. However, it should have access to all the same context as a person profile page does. That way it would be fully customizable. So if you value a few pieces of information on that page, you can just add those few things, or if you want a ton of information on it, you could add a ton of information. As it stands you really can't add much of anything or tell the main block which attributes you need to see.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
