### ISSUE TITLE
Problems accessing Learn Videos. I'm new to the Rock software and having problems

### ISSUE THREAD

**Issue by gjmtx49** [SparkDevNetwork/Rock#3162]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

[Description of the bug or feature. Include screenshots if applicable.]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** 

[What you expected to happen]

**Actual behavior:** 

[What actually happened]

### Versions

* **Rock Version:** [Enter Rock version here]  
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by cabal95** [comment]
@gjmtx49 I was able to play a few of the RockU videos here: https://www.rockrms.com/rocku

If you are having issues, please post a question in either Slack or the Ask (https://www.rockrms.com/Rock/Ask) page with more details about specifically which video(s) you can't access and what the errors you are getting are.

Thank you.

**Comment by gjmtx49** [comment]
Sir: Still having problems. Your link works fine. When I go to the RMS website RockU I get a blank black screen. I click on the start icon and the screen remains black and is trying to be trying to access the videos but nothing happens. Upper left hand corner reads Video Thumbnail. Please help

**Comment by cabal95** [comment]
I would suggest trying a different browser. The videos I tested work fine for me.  If they are not working for you then you would need to provide more details about specifically which video(s) are not working, including information such as the URL that you are trying that is not working. But again, this is not really the correct place to seek help as github is primarily for code related issues. Slack or the Ask site would be a better place to seek assistance on the RockU videos.

**Comment by gjmtx49** [comment]
Using same wifi mobile phone and desktop at home. The link works fine from the phone. I even see the instructor before running the video. When I access RMS Learn U from the desktop and click on a topic I get a black screen with no picture.
I hit play and it begins to work but the video never comes up. I have Windows 7.0 Home premium OS and use the latest version of Firefox. It sounds like something on my machine is blocking the videos. How do I correct?
