### ISSUE TITLE
v8 beta Migrate History Summary Data job won't run

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3163]
### Description

After upgrading a v7.4 db to v8, the Migrate History Summary Data job fails like so:
![image](https://user-images.githubusercontent.com/3903408/43655013-ea82bec2-9712-11e8-8941-ad74e54f5f5e.png)

This is on a db that's a copy of production with 68k people records that's only a day old. The first time I test-upgraded to v7 on this db, I let the job run on its own schedule and it fired off at 3am the next morning (and failed). Today I rolled back, upgraded again (which went smooth, no errors or exceptions) then ran the job manually with the same error.

What are the implications if this job cannot run on my db, for whatever reason? Is it a bug, or a problem with my data?

**Comment by brendanyost** [comment]
I'm seeing the same issue.  I'm also seeing the issue with the 7.4 migration job.
