### ISSUE TITLE
Group Capacity should not allow <0 values

### ISSUE THREAD

**Issue by darringraham** [SparkDevNetwork/Rock#3167]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When Capacity is enabled for a Group Type, negative numbers are allowed. I believe numbers <0 should be errors trapped when Group info is saved.

### Steps to Reproduce

1. On the demo site go to General Settings | Group Types | Small Group | General (http://rock.rocksolidchurchdemo.com/page/117?groupTypeId=25)
2. Select Hard from the Group Capacity Rule (to enable Capacity for this group type
3. Save
4. Go to Group Viewer | Small Groups | Adults Group | Edit | General tab
5. Click on Group Capacity and enter a negative number (or scroll down unintentionally as my users do)
6. See error "This group is over capacity by X individuals." Where X = 0 - [capacity you entered]

**Expected behavior:**

I would expect Rock to trap negative values in the Group Capacity field and not allow editing of that Group Type to be saved until a number >=0 is entered.

**Actual behavior:**

Rock allows the user to enter and save a negative value in the Group Capacity field of a Group Type.

### Versions

Rock Version: Rock McKinley 7.4 (1.7.4.58)
Client Culture Setting: en-US

![image](https://user-images.githubusercontent.com/38145549/43669976-8999d802-9744-11e8-93a9-d1efea8d1dac.png)

**Comment by cabal95** [comment]
Implemention Note: This should probably allow for values >= 0, as I can see 0 being a valid value (i.e. a quick way to make sure that no additional members get added to any of these groups).
