### ISSUE TITLE
An error has occurred while generating the page menu. Error details:Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by gjmtx49** [SparkDevNetwork/Rock#3168]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce
1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior:**

**Actual behavior:**

A description of what actually happened.

### Versions
* **Rock Version:** [Enter Rock version here]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by gjmtx49** [comment]
Gentlemen trying to access Learn Videos, new to Rock. I received the following message:
An error has occurred while generating the page menu. Error details:Object reference not set to an instance of an object.

**Comment by mikejed** [comment]
There was a temporary issue with the rockrms.com menu this morning, but I believe it's been cleared up now. Please let us know at rockrms.com/ask if you continue experiencing issues; GitHub issues such as this one are for reporting issues with Rock code, not the website. Thanks!
