### ISSUE TITLE
Slingshot: Optionally match imported attribute by name and fieldtype

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#3169]
### Description

When importing attributes from other systems, [Rock looks up the new attribute](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Slingshot/SlingshotImport/SlingshotImporter.cs#L1593) by its AttributeKey.  Since Slingshot currently exports that Key as the other system's ForeignKey, core person attributes such as Baptism Date (`udf_date_5`) and Legal Notes (`udf_text_2`) are imported as additional person attributes.

### Steps to Reproduce

1. Export from a system using Slingshot
2. Expect that the person attribute of Baptism Date will be mapped to the Rock person attribute Baptism Date
3. (External) Baptism Date is mapped to a new person attribute 
4. Set up specific dataviews and bulk update each person attribute

**Expected behavior:**

The core code could check by Attribute Name and FieldType as well as by Attribute Key.

Alternatively, the Slingshot export could export the Name and Key (without whitespace) as the same value so the Key lookup would match in Rock.

**Actual behavior:**

See above.

**Comment by edmistj** [comment]
@dcs619 This is a solid idea, but I think it should be up to the Slingshot exporters to create the correct export formats for each specific system. So in this case it would seem like the CCB exporter should take it's system specific knowledge and make a Slingshot export file with the correct attribute keys.

Can you add this to the Slingshot repo issues as an enhancement request?
