### ISSUE TITLE
Batches

### ISSUE THREAD

**Issue by HeatherWinkelman** [SparkDevNetwork/Rock#3175]
Our financial admin exports batches to Excel and there are three columns that show info when viewing in Rock but do not have any info in the cells when exported to Excel. The columns that don't show info in Excel are Transaction Count, Transaction Total, and Accounts.  These all used to export just fine into Excel but haven't been working now for some time.  

![picture1](https://user-images.githubusercontent.com/42219261/43859622-c3ee8536-9b16-11e8-9e6f-bdf5adef4b8c.png)

**Comment by HeatherWinkelman** [comment]
Here's what it looks like in Excel:

![image](https://user-images.githubusercontent.com/42219261/43860055-25061d88-9b18-11e8-89ec-87b3b41ce8f9.png)

**Comment by ajfick** [comment]
@HeatherWinkelman This is a known issue that you can see [here](https://github.com/SparkDevNetwork/Rock/issues/3085) and is resolved in v8.1 . 
We have been having issues with this as well so I created a workaround with a Dynamic Data Block that our Finance Team actually seems to prefer over the existing excel document. If you would like that code I can get it to you!

**Comment by HeatherWinkelman** [comment]
Yes, please get the code to me.  However, I honestly have no idea what to do with that code – we don’t have an IT person on staff here…it’s just me and I am not well versed in this.  Could I also get step-by-step help as to what to do with the code?

Thanks!

Heather

**Comment by edmistj** [comment]
Duplicate to: https://github.com/SparkDevNetwork/Rock/issues/3085
