### ISSUE TITLE
Editing a Group Type can cause timeouts due to indexing

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3176]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When editing a Group Type and clicking save, if indexing is enabled it causes the index to be immediately rebuilt. This can cause a timeout and appears to be related to this line:

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/GroupType.cs#L900

in the PreSaveChanges() method.

This issue was initially reported on the Q&A site.  I'm not sure if there is a specific reason we re-index the entire group type on the spot instead of letting the index job do it later.

Original Q&A: https://www.rockrms.com/page/278?question=2017

I will post additional details on reproducing, but this appears to be caused by either a group type with lots of groups, or maybe lots of group / groupmember attributes. Will try to get more specifics and update.

### Steps to Reproduce

1. Edit a Group Type with lots of _somethings_ and try to save
2. Maybe get a timeout error.

**Expected behavior:**

Editing a group type should not timeout due to an indexing issue.

**Actual behavior:**

A timeout and exception occurs and your changes are not actually saved.

### Versions

* **Rock Version:** 7.x
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Additional details that came in regarding the GroupType in question:

Groups: 644
Group Attributes: 36
Member Attributes: 3
Any super big groups? None that large, they average about 14 per group.

**Comment by edmistj** [comment]
I think we need to move the reindex to a transaction.

**Comment by MikeDPeterson** [comment]
@cabal95 I also noticed a potential issue if Snapshot isolation is disabled. I'll make sure it works in either case. Snapshot isolation and/or long running indexing operation.
