### ISSUE TITLE
Additional Columns created in the group viewer when selecting the clear filter button

### ISSUE THREAD

**Issue by TheCoreyHall** [SparkDevNetwork/Rock#3181]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When viewing a group in the Group Member List block, if you expand the filter view and select the 'Clear Filter' button, every additional press after the first one adds a blank column to the member list. This issue dissappears on refresh, but it is still a bug.

![capture](https://user-images.githubusercontent.com/38293092/44037000-dd77af62-9ed8-11e8-85b4-f3492497c3ee.PNG)

### Steps to Reproduce
1. Go to the group member list of any group
1. Expand the Filter Options
1. Click on 'Clear Filter' several times
1. See error

**Expected behavior:**

Nothing should happen after the filter is cleared and you continue selecting the button

**Actual behavior:**

New columns are added with each additional press of the button

### Versions
* **Rock Version:** [7.3]
* **Client Culture Setting:** [en-us]

**Comment by cabal95** [comment]
This appears to already be fixed in 8.0. I was able to replicate the problem on the rock demo site, but not the pre-alpha site nor on my beta v8 site.
