### ISSUE TITLE
Family Pre-Registration Create New Child Every Time

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#3185]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
Whenever you use the new Pre-Registration block and specify a child, it creates a new child every time. I think this is probably due to the fact that email is not required for the child.

### Steps to Reproduce
1. Open Family Pre-Reg
2. Enter a parent
3. Enter a child
4. Save
5. Look at family (notice parent and child)
6. Run through Family Pre-Reg with exact same people
7. Look at family again (notice there are two children named the same thing)

**Expected behavior:**
I am expecting the process to match the children on First Name, Last Name, Birthday, and Family Id.

**Actual behavior:**
It is probably trying to use the standard match fields (First Name, Last Name, Email), but children do not necessarily have an email.

### Versions

* **Rock Version:** 7.4
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
I believe this is fixed in v8.1 with this commit. https://github.com/SparkDevNetwork/Rock/commit/191dfa7e92712fa753c5c8b72d0895a4f51af8fc
