### ISSUE TITLE
Registrants on a Wait List receive multiple payment reminders

### ISSUE THREAD

**Issue by mkinyon** [SparkDevNetwork/Rock#3193]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
It's possible for a registrar to receive two payment reminders within 24-72 hours after the registrant has been moved off of the wait list.  The first payment reminder comes in the form of the Wait List Transition Email which includes payment info.  The second reminder comes from the SendRegistrationPaymentReminders job.

I think the solution is to set the LastPaymentReminderDateTime to the current date when moving someone off of the wait list.  The only issue I can see with this is if someone modified the Wait List Transition Email template not to include payment information.  

I can submit a pull request if needed.

### Steps to Reproduce
1. Setup a registrant instance with a cost and then add a registrant to the wait list.
2. Take the registrant off of the wait list.  The registrant will receive the Wait List Transition Email which includes payment information.
3. The next time the SendRegistrationPaymentReminders job runs, the registrar will receive a second payment reminder.

**Expected behavior:**
Since the registrar already received a reminder, they should not receive another until some time has passed.

**Actual behavior:**
Registrar receives two payment reminders within 24 hrs (if it was during a weekday).

### Versions
* **Rock Version:** 7.4, latest develop (8.2)
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@mkinyon that logic makes sense. Feel free to submit a PR.

**Comment by mkinyon** [comment]
Thank you.  I will submit a PR tomorrow.
