### ISSUE TITLE
Group member holding multiple Roles 

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#3194]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
If you have multiple member roles in your small group section, all marked as leader. (Leader, Coach, Hub Leader) and each have requirements (Leader Agreement, Complete Training etc) AND you have 1 person filling more than 1 role.  If that person has completed the listed requirements, it will show completed on one of their roles, but not the other. 

### Steps to Reproduce
1. Go to 'Group Types'
1. Add Multiple roles under the Small Group Group Type
1. Mark them as 'Leader'
1. Add requirements for those roles (the same requirements)
1. Go to 1 person in your database and give them those two requirements
1. Go to a group in your group viewer with the small group type
1. Add the same person for two different 'leader' roles.
1. The warning symbol will appear for one of them

**Expected behavior:**

I would love for rock to detect that they met the requirements on both instances of the same person added to the group.

**Actual behavior:**

The warning symbol will appear for one of their instances.

### Versions
* **Rock Version:** [Rock McKinley 7.4 (1.7.4.58)]
* **Client Culture Setting:** [en-US]

**Comment by mikejed** [comment]
Confirmed on Prealpha

Requirements for both roles were 'SELECT [Id] FROM [Person] WHERE [NickName] == "Ted"', and requirements must be met before adding the person to the role.

![image](https://user-images.githubusercontent.com/6932047/44820762-25640480-aba7-11e8-9506-285373a2bf7f.png)

**Comment by matthewalanwhite** [comment]
We can confirm this is still an issue affecting in Rock McKinley 9.0 (1.9.0.15). Are there future plans to get this updated.

**Comment by melzs0627** [comment]
@jcjones37  Hi Jason, I know this is an older issue, but we have been trying to clean up the issue list. Thank you for your patience and understanding as we acknowledge that some of these older issues have not been updated in a while. This issue has been resolved in v10.0 of Rock. The commit this issue was fixed in can be found [here (3db35d5)](https://github.com/SparkDevNetwork/Rock/commit/3db35d537560e6ee5d2b4e8e0dea391d236d8589). I will now be closing this issue. Please leave a comment or reopen if you believe there is still a bug.
