### ISSUE TITLE
Defined Types List block has Category as a required filter

### ISSUE THREAD

**Issue by BrentPirolli** [SparkDevNetwork/Rock#3196]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
If you edit the Defined Types List block on https://yoursitehere/page/103?Page=84&ExpandedIds= it has the "Category" filter as a required filter. This shouldn't be the case. Leaving it blank shows all Defined Types, but once you save it with something filtered, you are stuck always having to use filters and while you can select all categories, any new categories are excluded from the Defined Types page until you go edit the filter to include them.

### Steps to Reproduce
1. Go to https://yoursitehere/page/103?Page=84&ExpandedIds= and edit the Defined Types List to see the required "Category" field.

**Expected behavior:**

Category filter would be optional.

**Actual behavior:**

Category field is required.

### Versions
* **Rock Version:** 1.7.5 (also seen on 1.7.3 and 1.7.4)
* **Client Culture Setting:** EN-US

**Comment by cabal95** [comment]
just to clarify, this is talking about the Category block setting, not the category filter in the standard grid filter area.
