### ISSUE TITLE
Ipad Check-In App touch lag on phone number

### ISSUE THREAD

**Issue by jrockman13** [SparkDevNetwork/Rock#3198]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
Users are experiencing issues when trying to type in their phone numbers on iPads. We have tried new 2018 ipads, older 2015 iPad Air, and old-school 2011 iPads (iOS 9.x). They type, and the screen shows the touch registering (by shading darker grey), but not all the number appear on screen. This same issue DOES NOT occur on Windows 10 App using a Surface Pro

### Steps to Reproduce
1. Open Check-In App
1. Login and selection options (we use Family Check-in with preselected person+schedule/group/location)
1. Tap the Red Check-In button
1. Try tapping in phone number at the pace of a mom who walked in 2 minutes into service.

**Expected behavior:**

All the numbers appear

**Actual behavior:**

0-7 digits appear (7 required)

See video: https://youtu.be/U7WFAgDc0_s

### Versions
* **Rock Version:** [7.4]
* **Client Culture Setting:** [en-us]

**Comment by JimMichael** [comment]
Do you by-chance have Safari restricted in Settings? We've seen major performance issues when you try to restrict the use of Safari via Restrictions, and the fix is to not restrict it.

**Comment by jrockman13** [comment]
@JimMichael Hmm. I can test allowing safari and see if the issue stops, but that isn't really a "Fix". It's a workaround...Managing iPads is pretty standard and in a school/church environment where kids will have access to the ipads, having safari restricted is a best practice.

**Comment by JimMichael** [comment]
Actually, it’s an Apple problem. Prior to iOS 10 Rock app worked fine with restricted Safari, but Apple ha ged the way things worknunder the hood and now apps that use webbiew (like Checkin) noonger work properly when Safari is restricted. If your iPads are not dedicated to check-in use, you might reconsider that.

**Comment by jrockman13** [comment]
Ok. In that case, has Spark reported this as a bug to Apple as the iOS dev of the app? Has apple responded?


I'm not trying to be critical of Spark or Rock here...I "just make it work" for a living too. I'm just trying to figure out where the problem lies and who is ultimately responsible to fix it. Bottom line is that Apple designed the ecosystem and the MDM tools to allow exactly the scenario we are running.


In the meantime, I'll test and see if removing restrictions makes it work, and if so I can see if Meraki or Apple School Manager will let me schedule restrictions...

________________________________

**Comment by Tschrock** [comment]
We've had a similar issue, where after sitting for a while the on-screen keypad seems to stop working (You have to hit a key and then wait a few seconds before you can actually type). I'm not 100% sure but we may also have some restrictions set up.

**Comment by JimMichael** [comment]
I think @cabal95 said there's a new webview control introduced iOS9 that's preferred over the deprecated control the Rock app is still using, and it was kept that way to allow iPad1/2 units to run check-in, but I think it's worth a discussion if it's finally time to ditch compatibility with those ancient devices and update the app to use the new control (or maybe do a second app and keep the legacy one around for those still trying to run on ipad2 units?), which in all likelihood will also fix this restricted Safari issue.  I say that with zero knowledge of what updating the app involves and how difficult it is. ;-)

**Comment by jrockman13** [comment]
From what I read Tuesday, there's another update to webview in iOS 11...

Get Outlook for Android<https://aka.ms/ghei36>




On Thu, Aug 23, 2018 at 11:06 AM -0500, "JimMichael" <notifications@github.com<mailto:notifications@github.com>> wrote:


I think @cabal95<https://github.com/cabal95> said there's a new webview control introduced iOS9 that's preferred over the deprecated control the Rock app is still using, and it was kept that way to allow iPad1/2 units to run check-in, but I think it's worth a discussion if it's finally time to ditch compatibility with those ancient devices and update the app to use the new control (or maybe do a second app and keep the legacy one around for those still trying to run on ipad2 units?), which in all likelihood will also fix this restricted Safari issue. I say that with zero knowledge of what updating the app involves and how difficult it is. ;-)

**Comment by cabal95** [comment]
It looks like switching to the new WebKit based view fixes the tap delay issue as well. (Because the double tap is used to detect zooming, WebKit disables it if the page specifies no zooming, which we do).

A quick test on my iPad Mini running iOS 11.4.1 seems to fix the delay. I know what version of WebKit fixed that issue, so I'll see if I can figure out the minimum iOS version required to get that fix.

I will be working on submitting a new app for testing with Jim, so hopefully we'll get a new version out in the next month or so.

**Comment by jrockman13** [comment]
Awesome! Let me know if I you need help with user testing. I have ipads on 9.x and 11.x, ranging from brand new to 1st model with lightning (ipad air) to really old (not sure how old, but locked to 9.4). I can also deploy custom apps with my MDM server.

**Comment by cabal95** [comment]
Will do. I might need some testing done on pre-iOS 11. Looks like the new WebKit view did not support one feature we need until iOS 11 so I may have to put in special code to use the old view if pre-iOS11 and the new view on iOS 11+.

**Comment by cabal95** [comment]
This should now be fixed in version 1.5 of the iPad Check-in app if you are running iOS 11 or later.
