### ISSUE TITLE
ByLatLong Requires Security at Controller and Endpoint

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#3199]
### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

If you are going to use the GetLatLong REST EndPoint, you have to provide right to the controller for the endpoint to not get a 401.

This is been tested on a local dev environment and on rocksolid.

### Steps to Reproduce ###

1. Create API Key
1. Give access to the endpoint under /Groups/GetLatLong
1. Attempt to authenticate via Header: Authorization-Token
1. Notice you get a 401
1. Give the Groups controller Access
1. Notice you now don't get a 401

**Expected behavior:**

When given access to an endpoint, you shouldn't have to give access to the Controller as well.

**Actual behavior:**

Have to give access to the Controller for the endpoint to have access.

### Versions ###

* **Rock Version:** [7.4]
* **Client Culture Setting:** [en-US]

**Comment by jonedmiston** [comment]
I'm able to test locally with a call to `/api/Groups/ByLatLong?groupTypeId=12&latitude=38.8951&longitude=-77.0364` and I get a 200 OK when I have permission to just the endpoint and a 401 when I don't.

Since Tyler is no longer in the community I'm going to close. But by all means if someone can confirm this is still an issue with updated reproduction steps please re-open.
