### ISSUE TITLE
Family Pre Registration Person Attributes 

### ISSUE THREAD

**Issue by BemaDavidBensen** [SparkDevNetwork/Rock#3200]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce

1. Go to Family Pre Registration
2. Add Attribute Categories For Children Or Adults
3. Refresh Page
4. See error "Multiple controls with the same ID '_rfv' were found. FindControl requires that controls have unique IDs."

**Expected behavior:**

The page to reload and the attribute categories will be shown

**Actual behavior:**

An exception is thrown.

### Versions

* **Rock Version:** [7.3,7.4,7.5]
* **Client Culture Setting:** [en-US]

**Comment by mikejed** [comment]
Confirmed on prealpha also. Childhood information didn't appear to trigger it on Child Categories, but the DISC category on the adults category selection definitely does.

**Comment by ethan-sparkdevnetwork** [comment]
Fixed.

Issue was in trying to assign an ID after creating the control. This was done to differentiate the adult 1 and 2 controls. However when creating composite controls, (e.g. RequiredFieldValidators), the descendant controls wouldn't get a unique ID and would then cause the error.

- Added overload to AttributeCache.AddControl to specify the ID for the control.
- Added POCO object to hold AttributeCache.AddControl options.
- Added overload to AttributeCacheAddControl to use options obj.
- Changed the logic of the FamilyPreRegistration block to create and specify the control ID.
