### ISSUE TITLE
Email Columns on Small Screens

### ISSUE THREAD

**Issue by slhilbert** [SparkDevNetwork/Rock#3201]
When using columns in emails, specifically the Two Column Dropzone, the classes Large-6 and Small-6 are added.  I believe this isn't desirable.  On small devices all columns should stack as no one wants to see columns in an email on their phone.  

I would suggest that the classes be changed to Large-6 Small-12

**Comment by garrettjohnson** [comment]
Fixed via e346705. Made all columns `small-12` on mobile.
