### ISSUE TITLE
Response Code query on Person To Person SMS takes too long

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3209]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The current query used to find existing response codes when looking for the next available is taking too long, in same cases it's taking upwards of 45 seconds which is causing timeout exceptions anytime an SMS message is received.

The current EF generated query equates to roughly:

```
SELECT COUNT(*) FROM [CommunicationRecipient]
WHERE [ResponseCode] LIKE '@%' AND [CreatedDateTime] > DATEADD(DAY, -30, GETDATE())
```

Which, on one system that was testing for me, takes 11.354s to run.

The more optimized query (written by hand, so need to find a way to translate to EF) filters additionally by the medium type (SMS only) and then changes from a LIKE comparison to a single character comparison and takes only 0.313s on the same system:

```
SELECT
	COUNT(*)
FROM [CommunicationRecipient] AS CR
INNER JOIN [EntityType] AS ET ON ET.[Id] = CR.[MediumEntityTypeId]
WHERE LEFT(CR.[ResponseCode], 1) = '@' AND CR.[CreatedDateTime] > DATEADD(DAY, -30, GETDATE()) AND ET.[Name] = 'Rock.Communication.Medium.Sms'
```

So we need to do some work to get the EF query to be optimized a bit more.  I can work on this and submit a PR.

**Expected behavior:**

An incoming SMS message should not cause a SQL timeout.

**Actual behavior:**

An incoming SMS message can severely tax the SQL server in some situations.

### Versions

* **Rock Version:** 7.4
* **Client Culture Setting:** en-US

**Comment by tstephens17** [comment]
Thanks for working on this Daniel. Please let me know if you need any testing done along the way.

**Comment by edmistj** [comment]
@cabal95 were you thinking of doing a PR, or do you want us to look at this?

**Comment by cabal95** [comment]
Yes, I will be happy to look at this. Just wanted to make sure I got a thumbs up first.
