### ISSUE TITLE
Value List field type always searches defined values

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3211]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you create a `Value List` attribute and do NOT link it to a Defined Type, and then happen to enter a numerical value that matches a Defined Value Id, it will display the Defined Value instead of the value you entered.

### Steps to Reproduce

1. Add new person attribute: Name = Value List Test; Category = Employement; Field Type = Value List
2. Go to Alisha Admin's record and to her Extended Attributes.
3. Edit the Employment section and enter `ABC` for the first value and `42` for the second value.
4. Save
5. Notice the displayed values are `ABC, Self-Service Kiosk`
6. Edit again, notice the actual saved value is still `ABC` and `42`.

**Expected behavior:**

Defined Value lookup should not happen if a Defined Type is not selected.

**Actual behavior:**

Defined Value lookup always happens if the value is a numerical format.

### Versions

* **Rock Version:** 7.3, 8.x
* **Client Culture Setting:** en-US

**Comment by shivambareria** [comment]
Fixed in https://github.com/SparkDevNetwork/Rock/commit/5043261d5ef5e5c6a8f75a5b270f3465ebf05afe.
