### ISSUE TITLE
8.1 beta Serving Teams Attribute/Filter issue

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3212]
### Description

Multiple 8.1beta users including myself report that Serving Teams stop showing group members immediately after upgrade. I was also able to dupe this in demo by upgrading it to 8.1beta.

### Steps to Reproduce

1. Upgrade a 8.0 beta instance to 8.1beta
2. Using Group Viewer, observe that many Serving Team groups no longer show members (though they still show a _count_ of members)
3. Edit the Serving Team group type and disable _Show In Grid_ on _Hours Serving_ member attribute
4. Observe group members now show.

**Expected behavior:**

Group members would show on all Serving Team groups regardless of the _Show in Grid_ setting on member attributes.

**Actual behavior:**

Something broke between 8.0 and 8.1. @cabal95 further adds: "For extra info, it looks like it's maybe trying to apply some filter even though it doesn't show it. If I set the filter to `Hours Serving Greater Than 0` then it correctly shows the people in the list."

### Versions

* **Rock Version:** 8.1beta

┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;791255729496940">image.png</a>

**Comment by matthewmeekins** [comment]
I’ll also throw out there “Show in Grid” only hides people if they don’t have a selection for that custom attribute.

This is also affecting Event Registration form attributes.
