### ISSUE TITLE
Check-in Manager Scheduled Locations Displays Inactive Schedules

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#3221]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The "Scheduled Locations" page of the check-in manager currently displays ALL schedules - regardless of whether or not they are active. It also displays the frequency/date of the schedule, rather than the name of it - which in most cases takes up a lot more space.

### Steps to Reproduce

1. Go to '/checkin/scheduledlocations'
2. See error

**Expected behavior:**

This could be considered preference, but personally if a schedule is set to "Inactive" - I would not expect it to show up in check-in manager.

Also, it would be great for the sake of clarity if the schedule name could be displayed instead of the date/frequency, or at least in addition to it.

**Actual behavior:**

Check-in manager displays inactive schedules along with active ones, and does not display schedule names.

### Versions

Rock Version: Rock McKinley 7.5 (1.7.5.59)
Client Culture Setting: en-US

**Comment by lpeterson1** [comment]
Just to add clarification, this is the PIN-authenticated "manager" inside check-in.

![screen shot 2018-08-27 at 6 56 34 am](https://user-images.githubusercontent.com/37701239/44661010-93050a80-a9c6-11e8-83a7-23d2719d1f94.png)

**Comment by briankalwat** [comment]
@nairdo 🚀
