### ISSUE TITLE
Unit Testing AttendanceCodeService

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#3225]
# Context
While working on pull request https://github.com/SparkDevNetwork/Rock/pull/3071 to fix scenarios where banned codes may get supplied. I was instructed to apply my changes to the latest codebase and make sure the necessary unit/integration tests existed and were passing.

# The Problem
* Non-deterministic - Because many of the tests simply generate many codes and test to make sure that all of the codes are valid, they can produce false positives if none of the codes tested are invalid. 
* They cannot be made to fail in order to assure that they properly test what they are meant to test. 
* Due to the random nature of code generation, tests that pass one time may fail the next time without any changes to the code or environment
* The integration tests unnecessarily include the database into the mix, which was not only causing me problems when the db cleanup code would time out, but the db is also not necessary in order to test code generation.

# Methodology
I want to help define a solid set of tests, not only for this module, but also to help set a precedent for what Rock unit tests should be.  This project is now more about defining good unit test practices than fixing one particular bug.

* Tests should each apply to one very specific test case and will pass or fail under specific circumstances
* These particular tests should be able to provide a static code or set of codes to be "generated" so I can make sure that they are handled properly, rather than randomly generating them
* Ability to test that the randomly generated codes are producing what they are meant to produce. This is separate logic from whether duplicates or banned codes are skipped.
* Tests should not involve the database if they are not testing any database functionality. This will make the tests more specific, more reliable, much faster, and do not require cleaning up any records generated.  In a more general sense, the test should be self-sufficient.

# My Solution
I needed to refactor AttendanceCodeService so I could choose whether it would use the random generation code or take a supplied set of codes and return those in order. 

* I created an Interface called IAttendanceCodeProvider that has a string GetCode() function. 
* I extracted the portion of the service that handles the generation of random codes (and incrementing numeric codes) into a new class called AttendanceCodeGenerator which implements IAttendanceCodeProvider. This class takes alphaNumericLength, alphaLength, numericLength, isRandomized, bannedCodes, and todaysCodes as parameters in its constructor, and then the GetCode() function is called to retrieve a value.
* I created a mock class called MockAttendanceCodeProvider that takes a set of code strings as a parameter in its constructor, and then the GetCode() function returns this supplied list of codes one at a time.

This now allows me to test the following scenarios, among others:

* Verify that a banned code is skipped in many different circumstances
* Verify that a previously used code is skipped
* Verify that incremental numeric codes will skip codes that contain a banned value

I was able to take all of the different cases that were meant to be tested with Integration tests and refactor them as unit tests that do not require any database interaction, and make them more reliable.

# The Code
* [AttendanceCodeService.Partial.cs ](https://github.com/WillowCreekCC/Rock/blob/AttendanceCodeTests/Rock/Model/AttendanceCodeService.Partial.cs) now also contains the above mentioned interface and generator class, but these should most likely be moved to their own file.
* [AttendanceCodeTests.cs ](https://github.com/WillowCreekCC/Rock/blob/AttendanceCodeTests/Rock.Tests/Rock/Model/AttendanceCodeTests.cs) contains tests for the service, the generator, and a couple cases where they need to work in tandem a certain way. More tests may be necessary but this is a good start.

# Conclusion
I am definitely open to feedback on this method and all the code in it. This is just my attempt at producing a testable structure for this module and only want the best for the codebase. Now is an important time to get some clarity about what kind of unit tests we expect and what standards we will put in place for making sure that the tests are as robust and efficient as possible.

I look forward to feedback!

# Related Issues
In the process of developing this I got hung up a bit on the incrementing logic, because I'm not sure exactly what the expected behavior is in all cases. I have made some assumptions in the tests, such as if 666 is banned then 6660-6669 are also banned, or that if A55 is generated then it is OK to increment to ?56 rather than try to generate another ?55 code.

One problem scenario I see is when using incremental code, it grabs all of today's codes of the specified length from the database, gets the highest number generated, and then starts incrementing there. This will work fine if there is only one configuration running in a day, or all the configurations use incremental numbers, but if a code such as A98 is generated randomly by one config, the incremental config will start at ?99 and then run out of codes. I did write it so that it would cycle back to ?00 at that point, but I would like to discuss further the various possible cases and expected behavior. This does not have to be discussed here but I wanted to mention it because it is a potential existing bug in code that I am submitting.

**Comment by jonedmiston** [comment]
@chrismcgrath are you still working on this?

**Comment by chrismcgrath** [comment]
Hey @jonedmiston, I opened this up for discussion but didn't get any response. I read over it and I definitely still think it's important for establishing meaningful test cases throughout Rock, and have left the branch open for that reason. 

If I remember correctly, I left the code in a state that was ready to be merged if approved so I'd be happy to discuss that issues I raised here so you can decide if it's worth pursuing. I think I submitted as a PR first (or planned to) and you or Nick suggested I create the discussion thread first.

I have time this week if you'd like to get on a call or anything.

**Comment by jonedmiston** [comment]
Not sure we have time right now to dive into another project. In an effort to keep these issues just 'Issues' we created a new repo for collaborations like this. Could you move it over to https://github.com/SparkDevNetwork/Rock-Collaboration to keep it going.
