### ISSUE TITLE
New Groups not accepting a custom schedule

### ISSUE THREAD

**Issue by rheneb3** [SparkDevNetwork/Rock#3226]
When we attempt to create a new small group, and we save it with a custom schedule, it forgets the scheduling portion. It does create the group, just not with a schedule. This also prevents us from publishing them to the groups directory. We are in beta 8.1

In v7.x the Custom schedule is retained on save and can be seen correctly when editing at a later time:

![image](https://user-images.githubusercontent.com/383807/44754591-5248e680-aad7-11e8-9e07-0b9793a239b2.png)

![image](https://user-images.githubusercontent.com/383807/44754601-570d9a80-aad7-11e8-9899-d352eec9b309.png)

┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;795994085990104">image.png</a>

**Comment by JimMichael** [comment]
I am able to dupe on prealpha. I change Small Group type to allow custom schedule, then added a custom schedule to a small group and after saving, then editing it again, the schedule was not there.
