### ISSUE TITLE
v8.1 beta: "Is Refund" checkbox can't be unchecked

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#3229]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Once a contribution is marked as "Is Refund", editing it later and removing that checkbox won't "take" - that is, when editing the transactions again, the box comes in checked again

### Steps to Reproduce

1. Add a transaction to an open batch
2. Provide a negative amount, then check the "Is Refund" box
3. Save the transaction
4. Edit the transaction, setting the amount to a positive amount, and unchecking "Is Refund".
5. Save
6. Edit the transaction again

**Expected behavior:**

The "Is Refund" button should still be un-checked

**Actual behavior:**

The "Is Refund" button is checked again

### Versions

* **Rock Version:** 8.1 beta, v9.? prealpha
* **Client Culture Setting:** EN-US

**Comment by ethan-sparkdevnetwork** [comment]
Verified behavior in 8.3 but 9.0 appears to be okay.

**Comment by ethan-sparkdevnetwork** [comment]
Verified issue in all versions. Refund row is not deleted when the transaction is saved. So the View and Edit for the TransactionDetail block show it as being a refund. Other info is updated.

**Comment by ethan-sparkdevnetwork** [comment]
Added logic to remove the refund if the box is not checked and a refund exists.
