### ISSUE TITLE
Add Group Member

### ISSUE THREAD

**Issue by ckehayias** [SparkDevNetwork/Rock#323]
Two things:
1. You have to put a space in before the Ajax fires to find matches to your search.  This was not entirely intuitive.  Not a big deal, but I didn't quickly get it.
1. It _might_ be nice to not show people who are already in the group.  This might not be feasible for other reasons, but it occurred to me as I was adding multiple Jasons, that after I added one, it might be nice User Experience to not see people already in the group.  Again...very nit picky.
2. Adding Multiple people at once would be nice too.  Nick mentioned this is already open somewhere, please consider this a +1

**Comment by nairdo** [comment]
Greetings. Hooray - Rock now has a feature to enable searching by only first name: http://www.rockrms.com/Rock/BookContent/5/74#searchingbyname

Regarding 2 and 3, at this time we've decided to not make these requested changes to the person picker control.
