### ISSUE TITLE
Metrics created in v8.0 beta - v8.2 alpha are not running as scheduled

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#3232]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce

1. Install version 8
2. Observe that the new "Homepage Metrics" (3 of them) have "Never Run"
3. Wait overnight for the 1am time to pass, or else change their schedule to run a short interval of time in the future (1 minute from now, for instance).
4. Ensure that the Calculate Metrics job has run
5. Observe that the metrics were not updated

ALSO/ALTERNATELY:

1. Inside of version 8, create a new metric. Provide a schedule for it to run soon (ie one minute from now)
2. Save the metric. When the timestamp has passed, manually run the Calculate Metrics job
3. Observe that "0 metrics updated" and observe that the metric was not given a value

###Workaround

It does appear that if you clear Rock's cache _after_ you set the new schedule, the metric will run as scheduled.

### Versions

* **Rock Version:** 8.2alpha
* **Client Culture Setting:** EN-US

**Comment by nairdo** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/589195586123cf59380c07ec343df4f32502c34c.
