### ISSUE TITLE
Add the ability to adjust map persicion on the Group Finder block.

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3233]
# Feature Request
We're starting to have concerns about how precisely the Group Finder map can pinpoint a group's meeting location, especially in the context of small groups for younger adults who may be meeting at a member's home. As it currently stands, you'd be able to find the exact location a group is meeting, and in most cases can even get a Street View of the location. 

**Describe the Feature Request**
We'd like to have some functionality to restrict how precise the markers on the map can be. For our use, we'd like to be able to restrict it to a zip-code sized area.

**Describe Preferred Solution**
A drop-down style option in the map settings that allows choosing an area size (block, zip code, city, etc) to restrict the map to. This would adjust the coordinates of pins appropriately, and possibly restrict the zoom level of the map as well.

**Describe Alternatives** / **Providing Code**
I currently have a work-in-progress alternative solution which simply adds a "Marker Precision" number to the map. This number is used reduce the number of decimal places in a location's coordinates, effectively limiting their precision. For this setup, two decimal places is a little over half a mile (enough to identify a town or suburb), three decimal places is about the length of an American Football field (enough to identify a city block), and four decimal places is about 12 yards (enough to identify a house). It works but doesn't end up looking that great because it's just snapping markers onto a larger coordinate grid instead of them being centered on a zip code/suburb/city. Any additional ideas or comments would be appreciated.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
