### ISSUE TITLE
Duplicate Delete Columns on Group Member Grid

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#3236]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

![2018-08-31_11-34-18](https://user-images.githubusercontent.com/19762670/44924722-dab2cb80-ad11-11e8-9b04-5132b22ed7c3.gif)

When in Group Viewer, if, in filter options, you click Clear Filter, then Apply Filter, it duplicates the last two columns.

### Steps to Reproduce

1. Go to Group Viewer
2. Find a Group with people in it
3. Expand Filter Options
4. Click on Clear Filter
5. Click on Apply Filter
6. Repeat 2-4 for fun

**Expected behavior:**

I didn't expect the last two columns to duplicate

**Actual behavior:**

They multiplied like rabbits

### Versions

* **Rock Version:** 7.3, 7.5
* **Client Culture Setting:** en-US

┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;802917569718113">image.png</a>

**Comment by cabal95** [comment]
Can you test against 8.x beta?  I believe this is already fixed as mentioned in #3181.

**Comment by NuclearTacos** [comment]
It's working as intended on prealpha.rockrms.com (Sorry, forgot to check prealpha, and my searches were too specific since he triggered it differently).  Good catch!

**Comment by nairdo** [comment]
Thanks for double checking.
