### ISSUE TITLE
Facebook Profile Links

### ISSUE THREAD

**Issue by mkinyon** [SparkDevNetwork/Rock#3239]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
Facebook links that were automatically added to a person profile via Facebook authentication are no longer working.
![image](https://user-images.githubusercontent.com/2349102/44936843-35a4ec80-ad2b-11e8-9e85-0293a18e312e.png)

Clicking on the link will show an error on Facebook's site:
![image](https://user-images.githubusercontent.com/2349102/44936728-bd3e2b80-ad2a-11e8-80d6-1519451f51bf.png)

This only affects links that were added via Facebook authentication.  Links that were manually added by staff will continue to work fine.  The affected links look a bit like this:
https://www.facebook.com/app_scoped_user_id/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

I'm not sure what the solution is.  It seems that Facebook will longer allow us to use links from the API.   In my client's case, they decided to disable the hyperlink since only a handful of those links still worked.

Additional Information:
https://stackoverflow.com/questions/49958029/getting-facebook-page-with-app-scoped-user-id-is-not-possible-anymore
https://developers.facebook.com/blog/post/2018/04/19/facebook-login-changes-address-abuse/

### Steps to Reproduce
Note: This requires the Facebook authentication provider enabled and configured on a login page.
1. Have someone log into Rock with their Facebook account. (This will update their Facebook person attribute with their login link.)
2. Navigate to their profile and click on the Facebook icon underneath their profile photo.
3. The link will lead to an error on the Facebook site.
![image](https://user-images.githubusercontent.com/2349102/44936728-bd3e2b80-ad2a-11e8-80d6-1519451f51bf.png)

### Versions
* **Rock Version:** latest develop
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Thinking we should update the Facebook plugin to stop adding the links since there will eventually expire.
