### ISSUE TITLE
Family Pre-Registration not auto-selecting Attribute Default Value

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#3243]
### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

When adding an attribute to a child on Family Pre-Registration, the default value is not being selected.

### Steps to Reproduce ###

1. Create new Person Attribute Called: **Likes Turtles**
1. Set the Field Type to Bool and set the default value to **Yes** (_because who doesn't like turtles_)
1. Modify your Family Pre-Registration and add the category your attribute lives in
1. Launch your Family Pre-Reg and add a child. (Notice **Likes Turtles** does not have value)

One thing to note. I have also tried a Field Type of single select, and this also didn't work.

**Expected behavior:**

I would expect the Attribute to pull the default value.

**Actual behavior:**

The attribute does not pull a value.

### Versions ###

* **Rock Version:** 7.4, 9
* **Client Culture Setting:** en-US

**Comment by joshuahenninger** [comment]
Hello @tscrip. This issue has been fixed in the new Obsidian Family Pre-Registration block available in the upcoming v15.2 and v16.0 releases via https://github.com/SparkDevNetwork/Rock/commit/357fd0914f00a730bfdf58152fee0b03cd39b65c
