### ISSUE TITLE
Attribute type Attributes do not return objects upon request

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#3245]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you create an attribute of type `Attribute`, then use Lava to request a property of the attribute stored in the attribute, only the "Name" property is ever returned. The second parameter of the `| Attribute` filter appears to be ignored entirely.

### Steps to Reproduce (example 1)

1. Create a Global Attribute, with field type Attribute. Specify Person as the entity type. For this example, I used "Current Opt in Attribute" as the name.
2. Edit the value - it's essentially an attribute picker. Choose "Currently An eRA" or another attribute with spaces in the name. Save
3. Run the following Lava:
```
{{ 'Global' | Attribute:'CurrentOptinAttribute','Key' }}
```
This returns "Currently An eRA" (the name) rather than "CurrentlyAneRA" (the key, as requested)

Likewise,
```
{{ 'Global' | Attribute:'CurrentOptInAttribute','Object' | ToJSON }}
```
returns `"Currently An eRA"`

### Steps to Reproduce (example 2)

1. Create a Person Attribute, with field type Attribute. Specify Person as the entity type. For this example, I used "Favorite Attribute" as the name. Assign it to a category, such as "Membership"
2. Visit a person's profile and on the Extended Attributes tab, edit Favorite Attribute by selecting "Baptized Here" or another attribute with spaces in the name. Save.
3. On their profile page, provide a block with the following Lava:
```
{{ Context.Person | Attribute:'FavoriteAttribute','Key' }}<br />
{{ Context.Person | Attribute:'FavoriteAttribute','Object' | ToJSON }}
```
This returns
>Baptized Here
>"Baptized Here"

rather than the Key (BaptizedHere) or the object properties enumerated in JSON.

### Additional notes:

Other attributes, when provided with a bad value for the second attribute filter parameter, will return an empty string. For instance, assume you created a Person type Global attribute: `{{ 'Global' | Attribute:'SeniorPastor','NotAValidProperty' }}` returns "". But in example 1 above, `{{  'Global' | Attribute:'CurrentOptinAttribute','NotAValidProperty' }}` still returns `Currently An eRA`.

### Versions

* **Rock Version:** 7.5-8.2
* **Client Culture Setting:** EN-US

**Comment by ElimAdmin** [comment]
@edmistj, @MikeDPeterson - will this also fix a problem I'm having where a report based on a view of Person is giving me the following error:  'WARNING: There was a problem with one or more of the report's data components... Object reference not set to an instance of an object.' when I try to include phone numbers (mobile, home or work) in the report?  in Version 8.3?  Or is this a different problem?

**Comment by MikeDPeterson** [comment]
@ElimAdmin I looks like #3338 would be due to a different issue, so we'll keep #3338 open and look into it.
