### ISSUE TITLE
Support for pages to require hard logins

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3248]
# Feature Request
**Describe the Feature Request**

Currently, Rock operates on the idea of a Soft Login. Meaning, you have entered your username and password in the past so you have the authentication cookie, therefore we trust that it is still you sitting at the keyboard. For most things this is fine.

A Hard Login would mean, even though you are logged in, it has been a while since we asked for your password so we are going to ask you again to make sure it's _still_ you.

An example of a page that might require a hard login, would be a person's giving history. Before letting somebody view their own giving history, we might require them to typed their password recently.

On the admin side of things, maybe we require a hard login before editing Global Attributes, or getting to the SQL Command page.

**Describe Preferred Solution**

We already have a record of when they last typed in their password (the `FormsAuthenticationTicket.IssueDate`). It's encrypted so we don't have to worry about the user editing it.

1. So we would add a flag on the Page that indicates the page requires Hard Login. This would only be enforced on initial page load. This would prevent somebody from being in the middle of working on something and getting kicked out because they went past their hard login window.
1. The Login block would get an additional parameter that tells if this login is for a hard login request. This parameter would simply be used to show an additional message to the user so they know whats going on.
1. A new helper method would be added to RockPage, `RequireHardLogin()` which would perform the same check. An example use of this method would be the public site person profile block. The block might allow a user to view their profile, but as soon as they click the Edit button it would require a hard login to be in place first. _To provide the best user experience, we might want to find a way to allow an extra parameter be added to the return url to indicate to the page/block to automatically go to into edit mode_
1. A global attribute would probably be added that allows the admin to override the default time limit for a hard login. For the default, I'm thinking maybe 30 minutes?

**Requirements to implement (same items as above)**

1. This would be a pretty easy change. Small migration to add the column and possibly set the flag on a few pages.
1. Very easy to add (screenshot below).
1. This shouldn't be too hard, other than the modification to the return url. Overall a fairly easy change, just needs some testing to ensure it's working correctly.
1. Easy to add, again a small migration.

_Edit: One thing that still needs to be figured out is how to handle `rckipid` URLs. Do we consider that a hard login? If not, we need to somehow handle that. Perhaps by subtracting the "hard login window" from the IssueDate when creating the cookie._

## Developer notes
The `UserLogin` class would get a new method called `GetCurrentTicketAge()` that returns a TimeSpan object indicating the age of the current ticket (or MaxValue if no current ticket).

The `SiteCache` class would get a new overload method of `RedirectToLoginPage( includeReturnUrl, isHardLogin )` which adds the `hardlogin` parameter to the URL on the login page.

The `RockPage` class gets a small addition to the `OnInit()` method. After we check if the user is authorized, we then check if IsPostBack == false && page.RequiresHardLogin == true && UserLogin.GetCurrentTicketAge().TotalMinutes > 30. If all is true (need hard login performed) then we set a flag which is used in the redirect code a few lines below.

The `Login` block gets a small tweak to add support for that `hardlogin` parameter to show the message to the user.

![](https://user-images.githubusercontent.com/1119863/45063126-3a3a0f80-b061-11e8-9b0d-85f5c1a80e09.png)

**Providing Code**
I will provide code if feature request is approved: **Yes** (some already written)

**Comment by edmistj** [comment]
Sounds like a good feature. Could we switch the new page parameter to be an integer so when present it would determine the hard login trust duration. This would eliminate the need for the global attribute and also allow for pages to have their own custom limits.

We'd probably also want to add a setting to he login block to allow for customizing the hard login message. What you've provided is a good starting point but maybe switch 'extra' to 'improved'.

**Comment by cabal95** [comment]
So an `int? LoginTrustDuration` on the page (and page cache). If `null` or `0`, behave normally like we do now. If `> 0` then the page requires a hard login of less than or equal to the specified age in minutes. (A value of 0 would lock you out of the page since even a few milliseconds between login and page load would cause a hard login request again)

I was thinking a block setting on login block to customize the message would be good.

**Comment by cabal95** [comment]
1) Do you think it makes sense to also provide a similar per-site setting so an admin could easily lock down an entire site?  example use case setting the Rock Internal site to require a hard login every 24 hours. Not sure if this would be super useful or not.

2) Some notes on property / method names for feedback:

* Added `public int? LoginTrustDuration` to Model.Page
* Added `public int? LoginTrustDuration` to Cache.PageCache
* Added `public static TimeSpan GetCurrentTicketAge()` to Model.UserLogin
* Added `public void RedirectToLoginPage( bool includeReturnUrl, bool isRelogin, Dictionary<string, string> returnParameters = null` to Cache.SiteCache
  * Note: Anything in returnParameters are appended to the returnUrl (or replace existing). Allows blocks to request a relogin and have a `Edit=true` parameter added to the Url so they can go directly into Edit mode. It should be used with careful testing, but allows for a much cleaner UX. I'll include a gif demo of this in PR.
* Added `public bool NavigateToLoginIfTrustIsExpired( int duration, Dictionary<string, string> returnParameters )` to RockBlock

3) Here is a screenshot of the page settings dialog:

![image](https://user-images.githubusercontent.com/1119863/45192066-098ddd80-b1fb-11e8-85c0-8be0c800acce.png)

If all looks initially good with property and method names and such, then I'll work on submitting the PR for final checks and approval.

**Comment by cabal95** [comment]
Also, one last thing that needs to be figured out is `rckipid` type logins. Currently, they are considered hard logins. I'm not sure if that is good or not. I can see arguments for both cases.

**Comment by cabal95** [comment]
@edmistj I've implemented the `rckipid` logic to consider those to be soft logins. Beyond that this is ready to go for a PR.  If you don't have any pushback on the screenshot or method names then I'll squash all my commits down and submit the PR. Thanks.

**Comment by edmistj** [comment]
Looks good to me. @nairdo you see any problem?

**Comment by cabal95** [comment]
Just a follow up ping to @nairdo on the above `rckipid` logic and screenshots before I submit the PR.

**Comment by nairdo** [comment]
Yes, I agree @cabal95 I would also consider those rckipid's as soft logins.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
