### ISSUE TITLE
API: Interface properties get filtered out when serializing to json.

### ISSUE THREAD

**Issue by lancelotdaemion** [SparkDevNetwork/Rock#3249]
### Description ###

If you make a GET request to the FinancialTransactionDetail endpoint with an expand (e.g. $expand=Account), the 3 properties in ITransactionDetail are removed. These properties are AccountId, Amount, and Summary.

The offender is here:

[https://github.com/SparkDevNetwork/Rock/blob/5d65e86df9750914735e837dc4deb214df09b76e/Rock/Data/Entity.cs#L316](https://github.com/SparkDevNetwork/Rock/blob/5d65e86df9750914735e837dc4deb214df09b76e/Rock/Data/Entity.cs#L316)

Interface properties are always virtual, so that ToDictionary() call filters them out.

This is being called here due to the inclusion of the $expand:

[https://github.com/SparkDevNetwork/Rock/blob/5d65e86df9750914735e837dc4deb214df09b76e/Rock/Utility/RockJsonMediaTypeFormatter.cs#L216](https://github.com/SparkDevNetwork/Rock/blob/5d65e86df9750914735e837dc4deb214df09b76e/Rock/Utility/RockJsonMediaTypeFormatter.cs#L216)

### Steps to Reproduce ###

Make a GET request to [api_url]/financialtransactiondetails?$expand=Account

You'll see that those 3 properties are not retrieved. The workaround I've been using is to explicitly add each property I need in a $select list:

[api_url]/financialtransactiondetails?$expand=Account&$select=Amount,Account,AccountId

### Versions ###

* **Rock Version:** 7.4
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
Since there is a workaround and we're starting work on our v2 API we're going to close this out.
