### ISSUE TITLE
Fundraising Opportunity Participant block displays Anonymous donors' information

### ISSUE THREAD

**Issue by ajfick** [SparkDevNetwork/Rock#3250]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When a Fundraising Opportunity Participant is given money for a trip/project through an anonymous donation, the page on which they can see their donations does not honor the "Anonymous" flag. It displays the name of the giver as "Anonymous", but the Address does appear as the Anonymous Users address. This means the Participant can look up the address or may already know the address and recognize the anonymous giver. 

![screen shot 2018-09-05 at 2 18 58 pm](https://user-images.githubusercontent.com/19314419/45162626-674f0500-b1bc-11e8-9109-f6fb2fe89191.png)

### Steps to Reproduce
1. Donate to a Fundraising Opportunity Participant as an anonymous user. 
1. Impersonate that user, and navigate to the trip page where the user will be able to see the list of donations to their cause. 

**Expected behavior:**
Anonymous givers should not have any information shared with the trip Participant other than the total amount of the gift. 

**Actual behavior:**
Fundraising Participants cannot see the name, but CAN see the address of the anonymous giver making it easy for them to determine who the gift was from. 

### Versions
* **Rock Version:** 7.4
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by shivambareria** [comment]
Fixed in https://github.com/SparkDevNetwork/Rock/issues/2942
