### ISSUE TITLE
Password Managers can't auto-login (takes you to forgot account page instead)

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3252]
### Description
Someone mentioned this in the Rock Slack when using Dashlane, and I can confirm it using LastPass - somewhere in the theme changes for v8, the login page was changed in a way that prevents password managers from recognizing the [Log In] button and causes them to hit the [Forgot Account] link instead. Looking at the page source, it looks like the login button is just a link, while the forgot account link is an actual submit button.

### Steps to Reproduce
1. Have a password manager such as Dashlane or LastPass set to automatically log you into Rock.
1. Go to the login page.

**Expected behavior:**

You're automatically logged in.

**Actual behavior:**

You're taken to the forgot account page.

### Versions
* **Rock Version:** 8.2/prealpha
* **Client Culture Setting:** en-US

**Comment by mcnoodles** [comment]
Could we move this priority up on this one?  It's started happening with Apple/iOS keychain.

**Comment by JimMichael** [comment]
Yes! This has just started to bite us big time, too. Either an iOS update or v10 made this start happening with Safari saved passwords on iOS, and we're getting lots of complaints about it.

**Comment by jonedmiston** [comment]
We'll move this up. Just missed the v10.3 alpha.

**Comment by JRichmond27** [comment]
One workaround that I found is as soon as you choose to autofill your username/password, immediately start spamming the escape key. The result is that it aborts the redirect, brings up the "loading" animation, and allows you to manually click the log in button.

I don't know if it will work for all password managers, but it at least works for Dashlane.
