### ISSUE TITLE
Rapid Attendance Entry - Check-In Group Issue

### ISSUE THREAD

**Issue by randyjreed** [SparkDevNetwork/Rock#3254]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When using the Rapid Attendance Entry Block you cannot see the Current Attendees when using a group used for check-in. When the block matches the date picker to the StartDateTime it doesn't match because the check-in group will have a time set on the record. When using a generic group this is not an issue because the time is entered into the record as 00:00.00. 
Because of not being able to view the current attendees this produces duplicate attendance entries. for that group.

I hope I explained this clearly enough.

### Steps to Reproduce
1. Enable a check-in GroupType to show in Navigation (One that has attendance in it)
1. Create a page and add the Rapid Attendance Entry Block to it.
1. Use the block settings to select the Check-In Group. Also Select Include Parent Group
1. Select the date that has attendance and you will not see the existing attendees.

**Expected behavior:**

I expected to see the attendees that were already in the data. So that I would not be entering duplicate attendance records. I'm not sure the best way to solve this since you will have to account for the service time in some way.

**Actual behavior:**

I did not see the existing Attendees. You are able to input duplicate attendance records.

### Versions
* **Rock Version:** [7.5]
* **Client Culture Setting:** [en-US]

**Comment by cabal95** [comment]
Was fixed by side-effect of the change to split out the AttendanceOccurrence table.
