### ISSUE TITLE
PDF Merge Template Fatal Error

### ISSUE THREAD

**Issue by drychlik76** [SparkDevNetwork/Rock#3256]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
Fatal error when attempting to print a document, from a grid, using PDF merge template document.

This error could be related to another reported issue.  https://github.com/SparkDevNetwork/Rock/issues/3195 

### Steps to Reproduce
1. Create a PDF merge template document and upload to the server.
1. Create a Report from a data view
1. Scroll down to the merge document button at the bottom of the bound grid.
1. Choose merge template document.
1. See error

**Expected behavior:**

A nice formatted document that is printable using Lava.

**Actual behavior:**

Server Error in '/' Application.  Uncaught exception at line 373.
![](https://user-images.githubusercontent.com/20803057/45227560-6f737700-b286-11e8-8f9c-1ffe590cf8cd.png)

### Versions
7.4

* **Rock Version:** 7.4
* **Client Culture Setting:** English

**Comment by drychlik76** [comment]
Yes, It is targeting Group Member entity.  #3210 does appear to be what I am bumping up against.

**Comment by edmistj** [comment]
Closing as it appears to be a duplicate.
