### ISSUE TITLE
SendAttendanceReminder Job Sends Reminds After Attendance is Entered

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#3257]
### Description

Even after entering attendance for a group in Rock - the small group leaders get a reminder email to enter attendance. 

**Expected behavior:**

After the first reminder email is sent, and the group leader enters attendance they should not recieve another reminder email until the next time their group is scheduled to meet.

**Actual behavior:**

Even after attendance is entered for a group the group leader continues to receive email reminders to enter attendance. 

### Versions

* **Rock Version:** Rock McKinley 8.2 (1.8.2.31)

**Comment by nairdo** [comment]
Thanks @austinspooner .  Can you attach a screenshot of that group's meeting schedule? And, are the people reporting this leaders of multiple groups?
