### ISSUE TITLE
Configuring Checkin for Geo Lookup disables IP lookup

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3259]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Currently, the way the code is written, when you turn on `Enable Location Sharing` in the block settings, it bypasses IP lookup.

I think the process for doing Kiosk setup should be:

1. Match by IP (or DNS if enabled)
1. Match by Geo (if enabled)
1. Manual Setup (if enabled)
1. Display "can't configure" message

Currently steps 1 and 2 are exclusive from each other.

As a bonus, the Geo-related messages are currently javascript `alert()` calls and modal popups. This means if we want to enable Geo lookup as an _option_, then before manual setup can occur they must acknowledge the "lookup error" message. I believe it would be more user-friendly to make these `<div class="alert">` style messages - space permitting.

In our use case, we would like to enable geo-location based checkin for our high school ministry, but not impact the rest of the weekend services by displaying extra dialogs that will just annoy or worse freak people out.

### Steps to Reproduce
1. Go to the CMS Pages tree
1. Go to the Checkin > Admin page
1. Edit the Admin block and turn `Enable Location Sharing` on.
1. Configure a Kiosk device to match by your IP address.
1. Go to the checkin page, and deny the lookup.
1. See the manual configuration screen instead of it matching by IP.

**Expected behavior:**

The reason I believe IP lookup should go first is because that is a manual configuration. You are explicitly stating that "this IP address should have this configuration". Geolocation matching should come next as it may not work AND requires user interaction to approve the lookup. Thus to reduce the number of prompts the user must interact with, Geolocation should be performed after IP matching.

**Actual behavior:**

When the Geo-location lookup is enabled, devices will no longer automatically configure by IP address.

### Versions
* **Rock Version:** 7.4
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
I'm assuming this is for mobile check-in?

I get the order change you are proposing, but can you add screenshots of the current behavior dealing with modals and a proposed screenshot showing alerts?

**Comment by cabal95** [comment]
Primarily for mobile check-in - though there is nothing preventing you from doing the same with a desktop browser that supports passing geo-location (pretty sure all browsers do now).

## Current Screens

This screen is currently displayed if there was no match to geo-location but manual configuration IS allowed. After you tap/click OK you would then be allowed to perform manual configuration:

<img width="758" alt="2018-09-10 10_42_11-admin _ rock check-in" src="https://user-images.githubusercontent.com/1119863/45314674-35ed7680-b4e7-11e8-9db1-7fe3568554b5.png">

This screen is currently displayed if there was no match to geo-location and manual configuration is NOT allowed:

<img width="744" alt="2018-09-10 10_47_31-admin _ rock check-in" src="https://user-images.githubusercontent.com/1119863/45314682-3dad1b00-b4e7-11e8-90fa-442b9cd9d971.png">

## Proposed Screens

This is the proposed "manual configuration is allowed" screen. I mocked the Theme and Device drop downs in two columns to save vertical space (set as `col-sm-6`), but I can easily make that still single column. Just means we are potentially using a lot of vertical space. This alert message would **only** be displayed if geo-lookup is enabled and both it **and** IP lookup failed.

<img width="756" alt="2018-09-10 10_46_21-admin _ rock check-in" src="https://user-images.githubusercontent.com/1119863/45314691-456cbf80-b4e7-11e8-8a62-409b77a084ab.png">

This is the proposed "automatic failed and you aren't allowed to manually configure" - though I also suggest changing the text to something more user friendly, such as `We could not automatically determine your configuration and manual configuration is not enabled.`

<img width="760" alt="2018-09-10 10_48_19-admin _ rock check-in" src="https://user-images.githubusercontent.com/1119863/45314708-4f8ebe00-b4e7-11e8-8488-f6a9d19a175c.png">

**Comment by cabal95** [comment]
I'm also good to submit a PR without the UI changes. Just seemed to make sense to do it all at once.

**Comment by nairdo** [comment]
@cabal95 , Are you OK if you put this into v9 (develop) instead of 8.8?  With a change like this, I'd rather wait for a release with a long test cycle by the community.

**Comment by cabal95** [comment]
Yep, I'll look this over and refresh my memory on everything that needed to change.
