### ISSUE TITLE
Excel Export using conditional formatting to produce banded rows

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#3267]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When exporting a grid to Excel, the rows all have conditional formatting on them that sets the background color to gray for every other row. This can be nice to look at, but is not the intent of conditional formatting. The proper way to do this is to set a table style that has banded rows.

The primary reason that this is important is that it is very common to edit these exported sheets, and the formatting quickly gets messed up and is very hard to make uniform if new rows or columns are added, which will not have the conditional formatting.  Using a table style will keep all the formatting consistent and easily removable or changeable if the user wants a different style.

### Steps to Reproduce
1. Go to a grid that has data in it
1. Click the export button
1. Open the sheet
1. Insert a column in the middle of the sheet and see that the formatting is not applied to this column
1. Click Conditional Formatting in the toolbar, select Clear Rules -> Clear Rules from Entire Sheet to erase the formatting
1. Use the Format as Table button (or the tools on the Design menu) to alter the look of the whole table.

**Expected behavior:**

Table formatting to be used to style the rows.

**Actual behavior:**

Conditional formatting is used to style the rows.

### Versions
* **Rock Version:** 1.7.3.55 thru 1.9.0.3
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
The code here:
https://github.com/SparkDevNetwork/Rock/blob/6df48dc45fde27e54fdb5e4464629662e40c9287/Rock/Utility/ExcelHelper.cs#L163

Should use table styles as discussed here:
https://www.c-sharpcorner.com/blogs/how-to-format-excel-table-using-epplus-net-library-c-sharp-part-fifteen
