### ISSUE TITLE
Copied Communication Template is transferring security rights instead of copying.

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3271]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Not a big deal but I did notice when copying a communication the new copy receives all the security rights that were placed on the template it was copied from, however, the original template loses those security settings and reverts to the default settings of a new communication (all users can view). We are running on v7.4 and I tested it on the RockRMS demo site (7.5) and saw the same issue.

I have not tested this in a v8 instance.

### Steps to Reproduce

1. Go to Admin Tools > Communications > Communication Templates
2. Add a new security role/setting to any template and save. 
3. Copy the template you just made the security setting change(s) to.
4. Compare the security settings of the copied one to the original. The copy will have the custom security settings while the original will use the default settings.

**Expected behavior:**

Custom security settings should remain on the original template and either the copied template receives the same custom settings or it receives the default security settings.

**Actual behavior:**

Custom security settings are transferred from the original to the copied template, causing the original template to revert back to default security settings.

### Versions

* **Rock Version:** 7.4 (1.7.4.58), 7.5 (1.7.5.59)
* **Client Culture Setting:** en_US

**Comment by ethan-sparkdevnetwork** [comment]
Already fixed in 8.0 on commit c0daf56e. What was actually happening was the original was getting its name changed instead of the new copy.
