### ISSUE TITLE
Disable Name Edit Prevents New Family Members

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#3272]
### Description
I added the logic to disable name edit in the wrong place when submitted to core.  Rather than after the person not null check, it should be in the else case of the person id equal 0 logic.

### Steps to Reproduce
1. Go to My Account
1. Set Block Setting to disable Name Edit
1. Refresh page and add new Family member
1. See error

**Expected behavior:**

When adding new family members, the First/Last name fields should be editable.

**Actual behavior:**

The name fields are disabled and required which does not allow a user to save.

### Versions
* **Rock Version:** 1.7.5.59
* **Client Culture Setting:** en-US

**Comment by TheCoreyHall** [comment]
I have a client who is on 9.4 who just noticed they still have this issue. If Name Edit is Disabled, they are unable to add new family members. Was this fix removed from Core?

**Comment by nairdo** [comment]
@TheCoreyHall I'm going to reopen this for an investigation.  It does **_sort of_** looks like something _may_ have gone wrong with [one of the hotfix merges](https://github.com/SparkDevNetwork/Rock/commit/987e261d47208b7b6071da7bfda6a3af64006169).
