### ISSUE TITLE
System.NullReferenceException on Account Confirmation page

### ISSUE THREAD

**Issue by maurice-ellis** [SparkDevNetwork/Rock#3274]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?     [x] Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?     [x] Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
I'm not sure what is going on because Im not experiencing any issues, but now that we are having people login more often, this error keeps appearing. Sorry for the lack of details, but here is the stack trace.

System.NullReferenceException: Object reference not set to an instance of an object.

![screen shot 2018-09-14 at 10 05 30 am](https://user-images.githubusercontent.com/7678232/45564615-daccc400-b805-11e8-8af7-bf7c303c9a63.png)

### Steps to Reproduce
Not sure

**Expected behavior:**

For an error not to occurring

**Actual behavior:**

An error is occurring

### Versions
* **Rock Version:** Rock McKinley 7.5 (1.7.5.59)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
This appears to be caused by people using incorrect confirmation codes. For your concern, it can be ignored.

For our concern, we need to catch when DecryptString returns a null and handle it more gracefully than throwing an error.
