### ISSUE TITLE
Location Select Block Sort by Order Instead of Name

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#3278]
# Feature Request

**Describe the Feature Request**
Would like for the Location Select block to sorts the returned Locations by Orders rather than Name ( https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.8.3/RockWeb/Blocks/CheckIn/LocationSelect.ascx.cs#L210 ).

**Describe Preferred Solution**
The `DataSource` would be ordered by `l.Order` instead of `l.Location.Name`

**Describe Alternatives**
Add a block setting to switch been Name or Order sorting.

**Providing Code**
I will provide code if feature request is approved: [Yes]

**Comment by edmistj** [comment]
This is approved. Please make the block setting default to `Name` to keep current feature.

**Comment by treyhendon** [comment]
Should I write a migration for the block setting?  (I've not done that for core submits, but would be happy to if there are any guidance points.)

**Comment by cabal95** [comment]
I think as long as you add a new block setting in the `.ascx.cs` whose default value provides the current functionality that would take care of it.
