### ISSUE TITLE
Issue with HTML block on pledge page

### ISSUE THREAD

**Issue by jrockman13** [SparkDevNetwork/Rock#3282]
### Description
When editing the html block on the pledge page, the example text reappears in the HTML editor even though the edited text displays on screen.

### Steps to Reproduce
1. Go to the demo site, external site, Give -> pledge
1. Click on block settings and open the html editor.
1. Add an image and the text above the HR tag. Add some text below the HR tag. Save
1. Review changes on page
1. Click on block settings and edit again. Note that although your previous changes are displaying on screen, the html editor only displays the sample code.

**Expected behavior:**

See steps above

**Actual behavior:**

Ditto

### Versions
* **Rock Version:** 8.3
* **Client Culture Setting:** en-us ![display](https://user-images.githubusercontent.com/22159658/45728311-fed53000-bb8c-11e8-9f17-c64ed8cfea3b.jpg) ![example-code](https://user-images.githubusercontent.com/22159658/45728312-fed53000-bb8c-11e8-9a23-b7649aa9592a.jpg)

**Comment by Tschrock** [comment]
I've tested this on the latest release (8.8) and can't reproduce the issue. If you're still seeing this problem in the latest release please let us know.
