### ISSUE TITLE
Attendance Analytics includes all child group types

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#3284]
### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

Using the Group Types checkboxes in the block settings for Attendance Analytics includes all groups that are allowed child group types of the selected group.

### Steps to Reproduce ###

1. Make Serving Team child group type of the Small Group group type.
![<a href="](https://user-images.githubusercontent.com/12735965/45758947-6cfd0f80-bbec-11e8-93ae-f150f9e18663.png)
1. On the Attendance Analytics block, select the Small Group group type.
![<a href="](https://user-images.githubusercontent.com/12735965/45759050-a9c90680-bbec-11e8-8c1a-727f97b9cbf3.png)
1. All the Serving Teams will be listed on the Attendance Analytics block even though the group type is not selected.
![<a href="](https://user-images.githubusercontent.com/12735965/45759133-dda42c00-bbec-11e8-8c4d-30920709d93b.png)

**Expected behavior:**

Expected only Small Group and Small Group Section groups to be listed

**Actual behavior:**

All Serving Teams are listed along with Small Group and Small Group Sections.

### Versions ###

* **Rock Version:** [7.5]
* **Client Culture Setting:** [us-en]

**Comment by karenn-ccbc** [comment]
Also the Attendance Analytics does not honor Active Groups

**Comment by SteveSwaringen** [comment]
I think Karenn-ccbc's comment represents a different bug, but one that I'm also seeing. I'm going to submit that as a separate ticket as I think I know what's causing it.

**Comment by tikool17** [comment]
I think this might also fix and issue we're having. We have groups organized by campus. So different groups/types as children of another group type is common for us.

What we found in our investigation was that if there is a group type of a different type above the group type that you're looking to report on, it severs the connection and you are no longer able to see the child group types of the group type you're looking at in Attendance Analytics.

**Comment by nairdo** [comment]
This is the current behavior of the _Attendance Analytics_ block.  If you configure a group type's **Allowed Child Group Types** to include _another_ group type, any child groups of _that_ type will also appear in the Attendance Analytics list of Groups.

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/14e5b843-9b67-4668-bad0-1c97fa7f584a)

If you want to request a new block setting to control whether or not child group types should be excluded, please feel free to request this over at the [Ideas](https://community.rockrms.com/Ideas) board.
