### ISSUE TITLE
FA Icons Don't Show When Set On Page

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3286]
### Description

I'm noticing that pages that had a FontAwesome Icon set on the page properties (Icon CSS Class on Basic tab) no longer show the icon on v8+

### Steps to Reproduce

1. Go to any page and edit the page properties
2. Enter a common FA icon like fa fa-bar-chart in the Icon CSS Class field.
3. Save and observe the icon does not show up in the upper left (next to the page name, if you have that enabled) as it does in v7 and prior

**Expected behavior:**

FA icons would show if defined on a page.

**Actual behavior:**

They do not. Also verified on prealpha.

### Versions

* **Rock Version:** 8.0+

**Comment by edmistj** [comment]
This is actually by design to help de-clutter the header. I'll leave this open for a few days in case there's any further discussion.

**Comment by JimMichael** [comment]
Ah, ok. Maybe the ability to put an icon on a page should be removed (or the field disabled), then?

**Comment by JimMichael** [comment]
Oh wait... I just realized you probably meant this was a design decision for the Rock theme... but there still make be other sites/themes where you want it, so disabling it would be bad. I don't have a problem with it being gone, was just surprising ;-)
