### ISSUE TITLE
Google Auth dropping authentication

### ISSUE THREAD

**Issue by theundecided** [SparkDevNetwork/Rock#3288]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site] (http://rock.rocksolidchurchdemo.com/)? - Not easily accomplished for this issue
 *[X] Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
 *[X] Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
Google Auth appears to drop requests, returning users back to login page. 

![Steps to Reproduce](https://thumbs.gfycat.com/GreenLittleJavalina-size_restricted.gif)

#### Tested Failure platforms
* Windows 10 Pro Version 1803 (OS Build 17134.285)
* Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
* Microsoft Edge Version 42.17134.1.0
* Apple iPad [MP242LL/A ](https://www.apple.com/shop/buy-ipad/ipad-9-7/32gb-space-gray-wifi-cellular)
* Google Chrome (for ios) Version 69.0.3497.91
* Safari (for ios) Version 11
* Samsung Galaxy S8 Active ( [SM-G892A ](https://www.samsung.com/us/mobile/phones/galaxy-s/galaxy-s8-active-64gb--at-t--meteor-gray-sm-g892azaaatt/) Build/R16NW ) 
* Google Chrome (for android) Version 69.0.3497.100

Not positive if it is a Rock issue or a Google issue....but posting this here to help answer that question. 

### Steps to Reproduce
1. Start at a Rock login prompt
1. Sign in with google credentials 

**Expected behavior:**

Returning to the pre-login page

**Actual behavior:**

Returned to the login page. 

### Versions
* **Rock Version:** Rock McKinley 8.3 (1.8.3.36)
* **Client Culture Setting:** en-US

**Comment by wmsheeler** [comment]
We are experiencing the same issue on 7.4 and 8.3 using different OS's and browsers too

**Comment by FaithA-Admin** [comment]
We are experiencing the same issue on both 7.5 and 8.3 using different OS's and browsers

**Comment by nairdo** [comment]
Fixed via 66e4ef012efea45afe9a2a4a83eb9f6fdb147f74.
