### ISSUE TITLE
Lava Shortcode Parallax not working in 8.3

### ISSUE THREAD

**Issue by kcirgjd** [SparkDevNetwork/Rock#3289]
### Prerequisites
* [x (prealpha ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Lave shortcode is not loading the background image. 
### Steps to Reproduce

Use the shortcode on a page. 

**Expected behavior:**

The background image would load. 
**Actual behavior:**

No background image. 
### Versions

* **Rock Version:** [8.3]
* **Client Culture Setting:** [en-US]

**Comment by roblaughter** [comment]
I'm experiencing this as well. Not only does the background image fail to load, and the content inside of the parallax tag isn't rendered on the page.

**Comment by JimMichael** [comment]
Verified it's broken on prealpha using the example shortcode

**Comment by mikejed** [comment]
Confirmed. Works on 8.2 and breaks once upgraded

**Comment by JimMichael** [comment]
Unfortunately that means no one in the beta cycle actually ran the process street test list, as that's one of the tests (verify all shortcodes work). I feel bad I wasn't able to put 8.3beta through its paces :-/

**Comment by kcirgjd** [comment]
@JimMichael I wasn't either. I just today got to updating. I have used this all over our public site. Fortunately, if your content was inside of a div it still shows up. So at least I don't just have blank spaces.

**Comment by kcirgjd** [comment]
This seems to be fixed in 8.4 but is still not marked closed.

**Comment by edmistj** [comment]
@kcirgjd thanks!
