### ISSUE TITLE
Alternate Id's pre-filled with SearchValue in New Group block

### ISSUE THREAD

**Issue by atorrance** [SparkDevNetwork/Rock#3295]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
The Alternate Id fields are being pre-populated in the New Group block with the SearchValue from dbo.PersonSearchKey. Currently users have to delete this number before adding a barcode which is potentially confusing for users, especially in a check-in/volunteer setting.

### Steps to Reproduce
1. Go to http://prealpha.rockrms.com/NewFamily
1. Edit the block and enable 'Alternate ID's at the bottom
1. Add a new family, go to the Alternate ID page and see that the fields are pre-filled with the SearchValue from dbo.PersonSearchKey which users need to delete before adding a barcode or other ID

**Expected behavior:**

The fields should be blank on this block so barcodes can be added quickly. The fields should also not be required for any person.

**Actual behavior:**

The fields are pre-filled and need to be deleted before adding a relevant Id. Currently the fields cannot be blank for any new person.

### Versions
* **Rock Version:** [8.3 & 9.0]
* **Client Culture Setting:** [en-US]

┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;822913852769841">image.png</a>

**Comment by Adroken** [comment]
Just a note, you don't *need* to delete these pre-filled IDs, you can simply add a new one.

However as I will never use this, a feature for turning this functionality (auto-generation of ID) would be appreciated.  Will speed queries against this table as I will only have IDs for users that actually have a barcode instead of having to query every person.

**Comment by atorrance** [comment]
In the New Family block the pre-made codes currently need to be cleared out before scanning/entering a code if you’re planning on using barcodes from existing tags on site. There is no option to add a new one as there is inside ‘edit profile’.
