### ISSUE TITLE
Typo ? on DISC Request error message

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3298]
Text on page   Home > Workflows > DISC Request (when requested from the list of Workflows with no person set)

(http://  {our URL } /WorkflowEntry/20

reads:

"The entity is null or not a Rock IEntity."

Should that be "IEntity" or "Entity"?

Rock Version: Rock McKinley 8.3 (1.8.3.36)

**Comment by nairdo** [comment]
The term IEntity is actually correct but we'll see if we can handle that with a nicer error message.
