### ISSUE TITLE
Subscribe page does not respect Active status or Private status of Communication List

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3300]
### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

Not sure if this is intended behaviour?

1. Making a Communication List inactive in the Communication List detail screen
(Home>Communications>Communication Lists>Communication List Detail)
does not stop the Communication List from being displayed on the external Subscribe page.

![&lt;a href=&quot;https://user-images.githubusercontent.com/4658177/46060931-ee3e3e80-c1b8-11e8-9369-90395f27e1c7.jpg&quot;&gt;https://user-images.githubusercontent.com/4658177/46060931-ee3e3e80-c1b8-11e8-9369-90395f27e1c7.jpg&lt;/a&gt; clist1](https://user-images.githubusercontent.com/4658177/46060931-ee3e3e80-c1b8-11e8-9369-90395f27e1c7.jpg)

![&lt;a href=&quot;https://user-images.githubusercontent.com/4658177/46060932-ee3e3e80-c1b8-11e8-93c3-cdcb8df21827.jpg&quot;&gt;https://user-images.githubusercontent.com/4658177/46060932-ee3e3e80-c1b8-11e8-93c3-cdcb8df21827.jpg&lt;/a&gt; clist2](https://user-images.githubusercontent.com/4658177/46060932-ee3e3e80-c1b8-11e8-93c3-cdcb8df21827.jpg)

1. Making a Communication List Private in the Communication List Detail screen does not stop the Communication List from being displayed on the external Subscribe page.

The only way to stop a list from being displayed is to take it out of the Public category (or whatever is selected as the category to display).

### Steps to Reproduce ###

1. Logon to the external site.
1. View Connect / Subscribe - see the Communication Lists displayed.
1. Maintain the Active status of the Communication List in Home>Communications>Communication Lists>Communication List Detail.  Make the list inactive.
1. Return to the external site - the list is still displayed.  Even if you logoff and log on, even if you clear cache, and even if the person is not actually in the Communication List.

Repeat the same steps, but make the list Private - the list is still displayed.

**Expected behavior:**

Making a Communication List inactive should stop the list from being shown in the external Subscribe page.

Making a Communication List private should stop the list from being shown in the external Subscribe page.

**Actual behavior:**

The list is displayed, regardless of the Active or Private status of the list.

### Versions ###

Rock Version: Rock McKinley 8.3 (1.8.3.36)

Client Culture Setting: en-NZ

**Comment by KelleyLangkamp** [comment]
Confirmed on both v9.1 demo site and prealpha v11.0

**Comment by JimMichael** [comment]
Just bumping this to confirm that it's still an issue as of 12.1

**Comment by mikedotmundy** [comment]
This is still any issue as of v15.1 (and v16.0 alpha).

**Comment by chead4** [comment]
@ElimAdmin This issue has been fixed via https://github.com/SparkDevNetwork/Rock/issues/4650 in Rock v12.4.
