### ISSUE TITLE
[EN] Making inactive Person active again does not reset member status in Communication Lists

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3301]
### Prerequisites
* [ x ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
If a Person has an Active status, and they are included in a Communication List that has a Group Sync Setting rule active, and the Person is then made Inactive, then made Active again (they come back to church after a period of time), the 'Active status' of the Person in the Communication Lists (and all other groups they were active in?) is left as inactive (by design?).

I bet users will miss this, thinking that setting the person to active will just turn them back to active in all the groups they used to be active in.  This is what I expected to happen.  As a result these people will miss out on communications, and the user won't be aware that this is happening.

Maybe a message could be displayed to alert the user, when changing an inactive personal back to active, that they will need to manually reset the person's active status in all the groups that they are in, including Communication Lists?

The only problem with this is that THERE IS NO WAY to change the Active status in a Communication List that is controlled by a Group Sync Setting.  If you try to maintain a member of a Communication List controlled by a Group Sync Setting, no (Recipient) role is displayed, and even if you change the status (from Inactive to Active) you cannot save the user, because no role is set.  So there is no way to get the person active again in the Communication List.  If the list is a generic list, like 'Members and Atttenders' - they will continue to miss out on communications.

The Group Sync pulse does not refresh the Person's status in the Communication List.
Sending an email does cause the Person's status in the Communication List to be refreshed.

NOTE that if a Communication List is Group Sync Setting control - the list does not appear on the External subscribe page, so the Person can never manually change their subscription to that list anyway.

### Steps to Reproduce
Steps to recreate the problem of Active > Inactive > Active status changes does not reset Communication List member status:

1. Create a Communication List, and set the Group Sync Settings to populate the list from a Data View.

![comms2](https://user-images.githubusercontent.com/4658177/46069231-2a7c9980-c1cf-11e8-9e09-10159a1ceb9e.jpg)

1. Change the Person status of someone on the list from Active to Inactive.  This will set the status of the Person in the Communication List to Inactive.

![comms1](https://user-images.githubusercontent.com/4658177/46069220-2486b880-c1cf-11e8-9ed8-9e700094e0a4.jpg)

1. Change the Person status back to Active.  This will not change the Communication List status of the person back to Active - they remain as Inactive in the Communication List.

Steps to recreate the problem where you cannot change a Communication List member's status for a Group Sync Setting controlled group:

1. Confirm that 'Recipient' is a valid role for the Communication List group type:  Go to Home>General Settings>Group Types>Communication List, and expand Role.  'Recipient' is listed as is the only, and the default role.
1. Maintain a member of a Communication List controlled by a Group Sync Setting, e.g.:  go to Home>Communications>Communication Lists>Communication List Detail>Members and Attendees>Group Member Detail>Cindy Chang
1. Change the status of the member, e.g. Active to Inactive, and click Save.  Screen errors - "Role is required."
1. Click on Role.  No role is listed, and no role can be set.  There is no was to save the change to the person's status.

![roles2](https://user-images.githubusercontent.com/4658177/46069252-3bc5a600-c1cf-11e8-8019-4cb7da8cca39.jpg)

**Expected behavior:**

Display a message to alert the user, when changing an inactive personal back to active, that they will need to manually reset the person's active status in all the groups that they are in, including Communication Lists.

EITHER

1. A Communication List controlled by a Group Sync Setting should allow a user to save a status change back to Active status so the person can receive communications again.
OR
1. When a Person is set back to ACTIVE status from Inactive, this should also set their status to Active in all Communication Lists that they were in (this assumes that if the Group Sync put them in the group in the first place they should be active) - (??? Should this only happen for synced lists, but not for manually set lists???)
OR
1. The Group Sync job, or sending an email for the Communication List, should delete and recreate the entire Communication List if the list is controlled by a Group Sync Setting.  (Because the status of the members cannot be maintained manually anyway.)

In the end, there must be a way to get a re-activated Person back into the Group Sync Setting controlled Communication Lists.  ( Currently the only way to do it is to delete the Communication List Group Sync Settings, change the status, then reapply the Group Sync Settings.  Most staff workers won't be able to do that.)

**Actual behavior:**

See above.

### Versions
Rock Version: Rock McKinley 8.3 (1.8.3.36)
Client Culture Setting: en-NZ

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
