### ISSUE TITLE
Multiple values of a Defined Value Person Attribute display GUIDs not values in a report

### ISSUE THREAD

**Issue by darringraham** [SparkDevNetwork/Rock#3305]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? Yes, Demo Site
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting? Yes
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported? Yes

### Description

In a report If you have a Person Attribute (Department for instance) that is a Defined Value that contains more than 1 value for a person ("Human Resources" and "IT" for instance), the values for that attribute will be long strings (GUIDs?) comma separated instead of the values ("Human Resources, IT" for instance). If a specific person only has one value for that attrbute ("IT" for instance), it will display "IT", not a GUID.

### Steps to Reproduce

1. Create a Defined Value called Department
2. Add values: "Human Resources" and "IT"
3. Create a Person Attribute called Department tied to the Defined Value Department
4. Edit a person and select "Human Resources" for the Department Attribute
5. Create a DV that pulls just that person.
6. Create a report based on the DV you just created that includes Name and Department
7. You should see the Department "Human Resources"
8. Add "IT" to the person's record so they are in both departments.
9. Go back to the report and you'll see two GUIDs separated by a comma instead of "Human Resources, IT"

**Expected behavior:**

We should see the actual values for a Person Attribute based off of a Defined Value. ("Human Resources, IT" not "e07cce31-f973-4dff-b5d6-ead5a49180c1,f1babd34-c59e-436a-b2cd-900a35e60fec"

**Actual behavior:**

The output of a report that has a field with multiple values based off of a Defined Value shows like "e07cce31-f973-4dff-b5d6-ead5a49180c1,f1babd34-c59e-436a-b2cd-900a35e60fec" instead of the values (like "Human Resoures, IT") 

### Versions
* **Rock Version:** [Rock McKinley 7.4 (1.7.4.58)
* **Client Culture Setting:** [en-US]

Attachments:
![sshot1](https://user-images.githubusercontent.com/38145549/46157192-6d268c00-c238-11e8-8492-73f8fa14bdc4.jpg)
![sshot2](https://user-images.githubusercontent.com/38145549/46157193-6d268c00-c238-11e8-819c-bfb4f931cbd7.jpg)
[RockDiagnostics-ProductionRock.txt](https://github.com/SparkDevNetwork/Rock/files/2424758/RockDiagnostics-ProductionRock.txt)

**Comment by cabal95** [comment]
Just to note, I don't think this is limited to Defined Values attribute type.  Pretty much any "multi-value" attribute (such as Categories) does the same thing.

**Comment by darringraham** [comment]
Just updated as I realize I typed Defined Type originally instead of Defined Value. May be a moot point according to Daniel.

**Comment by tscrip** [comment]
I believe the problem exists here: https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Web/UI/Controls/Grid/Grid.cs#L1168

The query that is getting passed is not being parsed as two different items. As a result, the GUIDs for both items are being displayed.

**Comment by darringraham** [comment]
FYI, this problem started in v8.3, and still exists in 8.4. Is this something we can see fixed in 8.5?

**Comment by timlem** [comment]
Looks like this bug I submitted a year ago and was fixed in v8: https://github.com/SparkDevNetwork/Rock/issues/2295

Now it's back?
