### ISSUE TITLE
FontAwesome pro "solid" icons won't render

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3309]
### Description

A FontAwesome Pro icon that renders fine in v7.x as solid breaks on v8.x

### Steps to Reproduce

1. On v7, upload FA pro and get the latest supported on v7, which I think is 5.0.13. Make sure theme is using "Solid" as the FA weight.
2. Use a pro icon like `fa fa-comments-alt` and it should render as solid
3. Upgrade same Rock instance to v8 and your icon is now broken
4. Upgrade to latest FA 5.3.1 and it makes no change
5. Edit theme and make sure _Regular_ and _Light_ fonts are also enabled
6. Change the icon to `far fa-comments-alt` and it renders as regular (outlined), and forcing `fal` also results in a light version, but trying to force `fas` again fails to render it as solid.

**Expected behavior:**

FA Pro icons would render solid fonts the same on v8 as they do on v7

**Actual behavior:**

Seeing some really weird things after upgrading to v8 on pro icons that worked fine on v7 via `fa fa-`  (which should be the equivalent of `fas fa-` assuming you have the theme set to use Solid weight) but now break, and the only way to get ANY version of said icon to render on v8 is via `far fa-` or `fal fa-`

### Versions

* **Rock Version:** v8

**Comment by JimMichael** [comment]
Curiously, this spontaneously started working... I noticed after I upgraded our production instance to 8.3, then uploaded FA Pro 5.4.1, the `fa fa-comments-alt` that we'd been using fine on 7.4 looked (unexpectedly) normal. Thinking it was 5.4.1 that "fixed" it, I wen BACK to my 8.3 test instance where I first saw the issue (but was till on 5.3.something) to upgrade _it_ to 5.4.1, but before I did that I changed back to fa fa-comments alt instead of fal fa-comments-alt, and... it worked. So... I got nothin'. For weeks this has been broken, and now it suddenly works. Go figure.

**Comment by JimMichael** [comment]
Something is still wacky with FA pro... I tried upgrading from 8.4 (which somehow had `fa fa-comments-alt` working fine) to 8.5 alpha and ended up with this
![image](https://user-images.githubusercontent.com/3903408/48223664-43937100-e35d-11e8-9b6f-389c11934864.png)

I recompiled theme, restarted Rock, no change. Then I downloaded FA Pro 5.5 and installed it, and got this:
![image](https://user-images.githubusercontent.com/3903408/48223691-5c9c2200-e35d-11e8-9624-6f09fb957929.png)

Again, recompiling/restarting didn't fix the rendering of `fa fa-comments-alt`. However, I CAN now do `fas fa-comments-alt` as well as `far` and `fal` variants and all render fine... so it just seems to be an issue with using the old `fa` syntax, which if I remember correctly has to do some weird mapping magic to make things work? Anyway, I don't have trouble using `fas` to get a solid icon.. just mentioning it in case you think it needs fixing. If not, just close this again.

**Comment by garrettjohnson** [comment]
There's a fix coming in v8.6, when initially upgrading a theme from Free to FontAwesome Pro you'll need to edit and save the theme to set the font family to pro. After the initial save, the standard recompile button will work to update the font.
