### ISSUE TITLE
Registration Exception 'Given key not present in dictionary'

### ISSUE THREAD

**Issue by JesseM-PC** [SparkDevNetwork/Rock#3311]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * [ ] Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * [x] Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * [x] Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When there is an issue with a credit card on an event registration it lets the user know the error, maybe an incorrect expiration, then the user corrects the mistake and tries to process the payment again but they are presented with another error "The Given key was not present in the dictionary". **We use payflow pro as our gateway. Our gateway is set to accept all credit card types.**

### Steps to Reproduce
1. Sign up for an event registration that requires payment.
1. When entering the credit card information intentionally put in an incorrect number, expiration, etc.
1. Click submit and get the appropriate error.
1. Fix the error you made earlier and submit the payment again. This time you will be presented with the "Given Key..." error.

**Expected behavior:**

You should not receive the given key error when resubmitting and the payment should go through successfully.

**Actual behavior:**

"The given key was not present in the dictionary." Error is shown and the only way to fix it is to start the registration over again and submit the payment correctly the first time.

### Versions
* **Rock Version:** 7.5 (1.7.5.59)
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
We, too, use Payflow Pro and see this exception regularly.

**Comment by nairdo** [comment]
We spent some time on this today and we'd like to investigate this further but we would need to get some details from someone who's experiencing this issue on a v8 system.  @JimMichael are you on v8?

**Comment by JimMichael** [comment]
No, we’re not on v8 yet. This has been happening to us since 6.x. I’m out of town this week and can’t dice into exceptions but I’ll get one as soon as I can. They are hit and miss, and it might also depend on having other event attributes in the form.

**Comment by JimMichael** [comment]
Sorry for an image, but the stack trace is short and I took a screen shot in case there's any other useful info on the page. Let me know if you want any other info from it. In this example, I can see in my log the same exception for the same user four times in a row, once for each attempt to submit the registration after initially submitting bad CC info.
![exception detail rock rms](https://user-images.githubusercontent.com/3903408/46566507-686f7100-c8e5-11e8-8105-0ae82e276cc9.png)

**Comment by ajfick** [comment]
We would like to update to v8 soon, but we are not using Payflow Pro. Does this issue exist for other gateways or just Payflow?

**Comment by JimMichael** [comment]
This is not a v8-specific issue. It's been happening since at least 6.5... so don't use it as a reason to NOT upgrade to v8. It should be easy to see if you're getting that exception, though.

**Comment by ajfick** [comment]
@JimMichael Thanks!
