### ISSUE TITLE
Enhanced security for Event Calendar and Event Items

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#3313]
### Description
In 8.3, Staff and Staff Like Workers roles (in addition to others) have Edit permission to the Event Calendar and Event Calendar Items.  Edit permission is necessary to Add an item, however it also gives those users access to Delete.  There is not a way to restrict this from Admin Tools > Security > Entity Administration because the underlying code models only support View, Edit, Approve, and Administrate permissions.  We've been tasked with multiple staff or volunteers deleting calendar items that they shouldn't have.

I've looked through the code and I'd like to open a PR with the following changes:
1) Add Delete as a supported action on the EventCalendar and CalendarItem models.
2) Add a migration to restrict Delete by default to Calendar Administration and Rock Administration.
3) Add a column and filter for CreatedBy to improve visibility of your own Calendar Items

Current:

![screenshot 2018-10-02 11 36 17](https://user-images.githubusercontent.com/1210933/46360132-d2172300-c638-11e8-9830-2a020f755f8b.png)

New:

![screenshot 2018-10-02 11 30 05](https://user-images.githubusercontent.com/1210933/46360142-d5aaaa00-c638-11e8-8ce6-e0e8a290d428.png)

### Versions
* **Rock Version:** v8.3
* **Client Culture Setting:** en-us

**Comment by andrewsohc** [comment]
Curious if there is any update on this?  OHC requested this change from KFS and would prefer if it can get rolled into Core.  This has been an increasing concern as more campuses add similar events.

**Comment by edmistj** [comment]
@dcs619 I think the feature request is ok. We see the need, but are a little worried that this might be wanted everywhere, which could be hard to implement/maintain. But it does already exist. A couple of points.

- We need to make sure that the security logic is in the service layer. Blocks should not be impacted.
- The migration will need to ensure that EVERYONE who currently has EDIT access also will have DELETE access. This will be more tricky than just adding the two roles. We don't want all churches to have different usage after the update.
- Not I know where the new column for # 3 would be. Could you provide a screenshot?

Assuming these changes, I think we are a go.

**Comment by dcs619** [comment]
@edmistj CreatedBy is the final databound column before the dynamic attribute columns are added, with a corresponding filter property:

<img width="1131" alt="screenshot 2018-11-29 15 57 42" src="https://user-images.githubusercontent.com/1210933/49251523-98bc2300-f3ef-11e8-99a3-9a0435359c6a.png">

Can you clarify what you mean by security logic in the service layer?  Currently the service layer only enforces foreign key constraints (see GroupService and PageService partials) and doesn't have access to CurrentPerson to check permissions.   

EventItemList already has a method to check permissions so I'd update it to follow the same pattern as FinancialBatchList:
```
protected void gBatchList_Delete( object sender, RowEventArgs e )
{
...
  if ( batch.IsAuthorized( Rock.Security.Authorization.DELETE, CurrentPerson ) )
  {
      // delete batch
  }
  else
  {
      mdGridWarning.Show( "You are not authorized to delete the selected batch.", ModalAlertType.Warning);
  }
}```

EventItemDetail doesn't check for security (just the JS popup) so I would update that too.

**Comment by edmistj** [comment]
@dcs619 we can circle back to making the delete on the service later in the future.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
