### ISSUE TITLE
Group Filter options running together

### ISSUE THREAD

**Issue by tstephens17** [SparkDevNetwork/Rock#3314]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
 *[No, maybe it is the number of attributes we have?] Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * [x] Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * [x] Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
The group filter attributes are blending together.

![image](https://user-images.githubusercontent.com/548178/46366519-2669d500-c630-11e8-9cc5-aba26070fd41.png)

### Steps to Reproduce
1. Expand the group filter and notice even gender runs together. Same with status.
1. We had a lot of attributes being filter-able. So, maybe the crammed space exposed the error.

**Expected behavior:**

Text not to run into other objects.

**Actual behavior:**

Text running into other objects on screen.

### Versions
* **Rock Version:** [Rock McKinley 8.3 (1.8.3.36)]
* **Client Culture Setting:** [en-US]

**Comment by luke-b-taylor** [comment]
I can confirm other instances of inline checkbox element texts being crammed together or overflowing their boundaries.  I believe there was some change made to the css styling for checkboxes in 8.x, as other methods I've used in the past to style multi-select using pre/post html in User Entry Forms are no longer functioning as expected.

Attached is an example from our 8.3 person extended attributes page:
<img width="309" alt="2018-10-02 10_50_52-luke taylor _ rock rms" src="https://user-images.githubusercontent.com/32314302/46367179-ca07b500-c631-11e8-9e29-ea81d6a135b7.png">

**Comment by megilee** [comment]
It appears this issue has been fixed in subsequent versions of Rock. I could not replicate the issue on the Demo Site running 9.2. The role attributes now format dynamically with window size.

<img width="1150" alt="Screenshot 2019-10-24 12 15 29" src="https://user-images.githubusercontent.com/45012163/67509195-11efe480-f658-11e9-9e78-07a4b4cdeff6.png">

<img width="789" alt="Screenshot 2019-10-24 12 17 54" src="https://user-images.githubusercontent.com/45012163/67509306-53808f80-f658-11e9-947a-16f4bcf2b5e2.png">

**Comment by nairdo** [comment]
Reported as resolved by the #bugapalooza event team.

@tstephens17 If you test this and find it is still not working on v9.2 or later, please let us know by reopening this issue with any additional details you can provide to help us pin point what we might have missed.
