### ISSUE TITLE
Universal Search not indexing result for calendar item detail

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#3316]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

In testing both ElasticSearch and Lucene in 8.3, the indexer does not return a result for calendar event details.  On the Calendar page (EventCalendarLava block), I have Horseback Riding set to recur every week with View Details going to the Item Detail page (CalendarEventItemOccurrenceLava block).  

![screenshot 2018-10-03 09 22 28](https://user-images.githubusercontent.com/1210933/46412932-ecf79f00-c6ed-11e8-90f9-2592ef15404b.png)

![screenshot 2018-10-03 09 19 05](https://user-images.githubusercontent.com/1210933/46412941-f123bc80-c6ed-11e8-827b-c4fe75b0e7aa.png)

![screenshot 2018-10-03 09 22 01](https://user-images.githubusercontent.com/1210933/46412969-fb45bb00-c6ed-11e8-99a3-02edc9a2acc0.png)

### Issue
Searching for "horseback" returns a result for the Calendar Event List page, but not the Event Item Detail page:

![screenshot 2018-10-03 09 22 45](https://user-images.githubusercontent.com/1210933/46412927-e79a5480-c6ed-11e8-825a-762a2431697f.png)

 

## Steps to Reproduce

This is currently set up on the demo site:
[Search](http://rock.rocksolidchurchdemo.com/page/6476?Q=horseback&siteName=)
[Calendar Event List](http://rock.rocksolidchurchdemo.com/page/5341)
[Event Item Detail](http://rock.rocksolidchurchdemo.com/page/5358?EventOccurrenceId=5)
[Event Config](http://rock.rocksolidchurchdemo.com/page/5340?EventCalendarId=1&EventItemId=5)

1) Enable Lucene on 8.3
2) Enable site indexing with start URL on external website
3) Create Index Rock Site job targeting external website 
4) Add Universal Search to a block and page on external site
5) Manually run index job several times
6) Check for active calendar items displaying on the calendar page
7) Search for active calendar items
8) Confirm search returns a result for event list but not event detail

**Comment by GerhardPowell** [comment]
Universal Search Engines does not support indexing webpages with a question mark in the URL.
So a URL like http://rock.rocksolidchurchdemo.com/page/5358?EventOccurrenceId=5 will not be indexed.

One can use page routes as a workaround to get it to work:
•	On the “Event Details” page, open the page properties.
•	Click “Advanced Settings”
•	Update “Page Routes” to “Event/{EventOccurrenceId}”.
Note: ‘Event’ can be replaced with any other page name.
 
•	In Calendar.lava (for the theme being used by the website):
Replace:
`<a href="{{ DetailsPage }}/?EventOccurrenceId={{ eventItemOccurrence.EventItemOccurrence.Id }}">`
With:
`<a href="/Event/{{ eventItemOccurrence.EventItemOccurrence.Id }}">`
Note: Update “Event” to match the Page Route.

**Comment by edmistj** [comment]
We’ll look into getting the universal search to work with urls with question marks.

**Comment by ethan-sparkdevnetwork** [comment]
Code Changes:
Crawler.CrawlSite()
- When creating the URL escape the question mark.

Crawler.IsValidUrl()
- Removed question mark check

Example Testing validation:
- Setup Lucene search on external site
- Setup search block on external site
- Setup index job for external site.
- Created registration for car show event
- Ran index job
- Searched for car show
- Expected results appear, including URLs with parmeters (e.g. http://localhost:6229/page/414/?eventoccurrenceid=2)
