### ISSUE TITLE
Feature Request - Set Campus of Batch Created by Transaction Entry

### ISSUE THREAD

**Issue by rutledgek** [SparkDevNetwork/Rock#3317]
# Feature Request
**Describe the Feature Request**
In a transaction entry block, you can set prefix names and other settings for the batch created, but you cannot set the campus id of the batch.  Request a setting in the transaction entry settings to set the campus id of the batch created.

**Describe Preferred Solution**

A setting in the transaction entry block to set the campus id of the batches created by a transaction entry block on a page.
**Describe Alternatives**

**Providing Code**
I will provide code if feature request is approved: [No]

**Comment by jonedmiston** [comment]
This is a request for an enhancement. Please open as an Idea so that the community has better access to it with the ability to vote it up.
