### ISSUE TITLE
Home Button Missing on small screen devices in v8

### ISSUE THREAD

**Issue by DrArmus** [SparkDevNetwork/Rock#3319]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When viewing Rock's new internal theme introduced in v8 from a small-screen device the home button is missing from the menu. I believe it's being covered by the hamburger menu button.

### Steps to Reproduce
1. Go to Rock's Internal Webpage from a tablet, phone, or small web browser window.
1. Click on the hamburger menu button to display the side menu. 

**Expected behavior:**

The home menu icon (Rock logo by default) to appear on the top of the side page menu block.

**Actual behavior:**

Home button appears to be hidden or blocked by the hamburger menu button, making it difficult for users to go to the homepage. 

### Versions
* **Rock Version:** 8.3 (1.8.3.36)
* **Client Culture Setting:** en-US

![capture](https://user-images.githubusercontent.com/4846426/46501096-bd29c380-c7e1-11e8-84b3-dfd31c55cb0f.PNG)

**Comment by chrismcgrath** [comment]
Note that the Rock logo and home link do show up on a mobile device screen, or in Chrome when the mobile device setting is enabled in the Inspect screen. It only disappears if you shrink a normal non-mobile browser down enough to hide the menu.

**Comment by JimMichael** [comment]
The above comment is true only on 8.4... 8.3 and prior had no logo at any small size. I think the confusion is that it was never tagged as `fixed-in *.x`

**Comment by DrArmus** [comment]
Just updated to 8.4 and things seem peachy. Thank you!
