### ISSUE TITLE
Prayer Request Entry Block Shows Category

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3322]
### Description
The Prayer Request Entry block shows the "prayer category" itself in the drop down list of categories, when (I believe) it should not.

### Steps to Reproduce
1. On a default install, verify that Admin | General | Prayer Request Categories has the default _All Church_ category, with multiple prayer request categories within.
1. Verify the _Prayer Request Entry_ block on the public site is configured to use the _All Church_ category.
1. Observe in the _Category_ drop-down that _All Church_ is one of the options in addition to the _actual_ prayer categories within that category.

**Expected behavior:**

The drop-down should not show the _configured_ top-level category as a selectable option in the category drop-down. In this example, _All Church_ is just a top-level category used to contain the _actual_ categories you wish to expose on the form, and it makes no sense to have _it_ be an option to choose, and in this example "All Church" leads to a confusing choice in the drop-down.

**Actual behavior:**

The prayer request top-level category chosen in the block settings is exposed in the drop-down as a prayer category.

### Versions
* **Rock Version:** All
![image](https://user-images.githubusercontent.com/3903408/46677982-3b52e500-cba9-11e8-864d-9f9dfb1a3412.png)

**Comment by robbiefunderburk** [comment]
We are on 8.4 and are seeing the same thing.  Demo site does not have the problem.

**Comment by JimMichael** [comment]
Demo does indeed have the same issue. The only difference is that it does not have a _Category Selection_ selected by default
![image](https://user-images.githubusercontent.com/3903408/46970546-0c43e400-d07f-11e8-94ea-b8af4d6d3ed1.png)

But as soon as you select All church (the only top-level category by default) you get the exact same result
![image](https://user-images.githubusercontent.com/3903408/46970590-28478580-d07f-11e8-9369-bbd151ae23f0.png)

**Comment by DrArmus** [comment]
We have this as well on our 8.4, though the issue has been around for longer. Our "lazy" fix was to name the general category "Addictive Behavior" so it would look normal to the end user. 

However, a new issue occurred for us on 8.4 that prevents selecting a child category from the drop-down menu on the internal Prayer Request Detail block. #3390

**Comment by jcjones37** [comment]
Same here - this appears to still be an issue in Rock McKinley 9.0 (1.9.0.26)
