### ISSUE TITLE
Typo on "Shared Documents" page/19

### ISSUE THREAD

**Issue by luke-b-taylor** [SparkDevNetwork/Rock#3323]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)? Demo site and prealpha
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
On the default pages, in the Intranet > Office Information > Shared Documents page, bullet #2 says "Refferal Lists" and should say "Referral Lists"

### Steps to Reproduce
1. Go to 'rockserver/page/19'
1. Look at the words
1. Notice one is a typo.

**Expected behavior:**

Expect to see actual dictionary words

**Actual behavior:**

See "Refferal" instead of "Referral"

### Versions
* **Rock Version:** (1.8.3.36), (1.9.0.5)[prealpha.rocksolidchurchdemo.com]
* **Client Culture Setting:** en-US

**Comment by GerhardPowell** [comment]
Added fix to Hotfix Migration Rollup 1.8.5
