### ISSUE TITLE
URL slugs for main page ads are showing on main external page

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3328]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
The URL slugs for main page ads is showing on the main page.  This is happening on our page, and on the demo site.

![slug1](https://user-images.githubusercontent.com/4658177/46766812-a33b3400-cd3f-11e8-914e-225bd3e6d399.jpg)

### Steps to Reproduce
View the main external page of the demo site.
View the slugs at Tools > Content > view one of the External Website Ads.

**Expected behavior:**

There should be no slug text line.

**Actual behavior:**

A line of text with incorrect slug reference shows on the main page.

### Versions
Rock Version: Rock McKinley 8.4 (1.8.4.38)
Client Culture Setting: en-NZ

**Comment by megilee** [comment]
This appears to be fixed now on both the demo site and our site running Rock 9.1/9.2

**Comment by nairdo** [comment]
I've been trying to spot what might have fixed this issue and my best guess is possible either https://github.com/SparkDevNetwork/Rock/commit/31ad60328bc87638ec28a42aff3d09e31a38ece2#diff-c5b7f19b2f6f1be2385ea986be336b3f or https://github.com/SparkDevNetwork/Rock/commit/62358bed209722a0732978372528d1d56bb8a478#diff-c5b7f19b2f6f1be2385ea986be336b3f or https://github.com/SparkDevNetwork/Rock/commit/6194a8025cc4f4829904f37c8fcb3bc4e880583a#diff-c5b7f19b2f6f1be2385ea986be336b3f or https://github.com/SparkDevNetwork/Rock/commit/f45051593c0bbd2e9ff98bfcd623859e6482e8b3#diff-c5b7f19b2f6f1be2385ea986be336b3f

Please re-open if you're still seeing this in any v9 Rock instance.  If so, please attach the adlist.lava file you're using and/or compare it with the latest stock one here: https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Themes/Stark/Assets/Lava/AdList.lava
