### ISSUE TITLE
[EN] Default Unsubscribe link should give option to unsubscribe from Communication Lists

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3330]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

I can't test this in the demo.

### Description
We have a communiction list - Devotions.  I want recipients of the devotion email to be able to unsubscribe from just this communication list, but when they click the Unsubscribe link added by default to the builk email, the non-logged on version of the Unsubscribe page is shown without the option "Only unsubscribe me from the following lists."

The default Unsubscribe link is maintained in /Home/Communications/Communication Mediums/Email.

If this link is changed from .../Unsubscribe  to .../Subscribe - the link WILL log on the user, and take them to the Connect/Subscribe page.

So why won't the /Unsubscribe link take the user to the logged on version of the UNsubscribe page??

The un-logged in version of the page forces Person to either accept ALL emails, not bulk emails, or no emails.  But I want them to see the option to deselect from just the Devotions Communication List.

The alternative instruction "If you want to unsubscribe to the Devotions communication list then log on, go to /Connect/Subscribe, and untick the Devotions Communications List" is clumsy - and possibly unnecessary?

### Steps to Reproduce
1. Create a Communication List, and add yourself to it, so that you are in at least one valid, active Communication List that you can unsubscribe/subscribe to.
1. Send a bulk email with the default [[ Unsubscribe ]] link.

2a.  Make sure you are not logged on.
2b. Click the Unsubscribe link in the email - takes you to the non-logged in version of the Unsubscribe page, with no option to "Only subscribe me from the following lists"

1. Edit the default Unsubscribe HTML in /Home/Communications/Communication Mediums/Email.  Change /Unsubscribe to /Subscribe, so it looks like this:

href='{{ 'Global' | Attribute:'PublicApplicationRoot' }}Subscribe/{{ Person.UrlEncodedKey }}'>SUBscribe

1. Send a bulk email with the default (modified) [[ Unsubscribe ]] link.

5a.  Make sure you are not logged on.
5b. Click the SUBscribe link in the email - takes you to the **logged in** version of the /Connect/Subscribe page.   So exactly the same link HTML CAN log the user on.

**Expected behavior:**

I want users who are on a Communicatoin Lists to be shown the lists they can unsubscribe from, by clicking the default Unsubscribe link in emails.

**Actual behavior:**

Users are not shown the Communication Lists they are in, and hence can not opt out of specific lists, by clicking the default Unsubscribe option.

Users can log on, and maintain these lists by going to /Connect/Subscribe.  But they should be able to do this straight from the default Unsubscribe link. 

If the equivalent /Subscribe link can log the user on and show the subscribe options, why can't the /Unsubscribe link also log the user on and show the "Only unsubscribe from these lists" option in the Unsubscribe page?

Or am I missing something obvious?

### Versions
Rock Version: Rock McKinley 8.3 (1.8.3.36)
Client Culture Setting: en-NZ

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
