### ISSUE TITLE
Main Menu Scrolling Issue on Mobile

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3331]
### Description

The way the Internal site menu scrolls changed between v7 & v8. On a small screen device, it is now no longer possible to get to menu items at the bottom if you've added more top-level menus that extend beyond your devices initial view.

### Steps to Reproduce

1. Add several top level menus (pages) to the Internal site
2. Access the site via a mobile device (I have only tested on iOS) and observe that you cannot get to menus below the ones you can see, as the sidebar menu no longer scrolls with the page content.

**Expected behavior:**

You would be able to scroll the sidebar menu on a mobile device, regardless of how many items you've added

**Actual behavior:**

You cannot get to menu items below your devices view.

### Versions

* **Rock Version:** 8.3
![20181012_225615000_ios](https://user-images.githubusercontent.com/3903408/46897735-2b0d6500-ce4a-11e8-9283-9466a7aaa396.jpg)

**Comment by NuclearTacos** [comment]
Can confirm, this happens even on non-mobile devices too when you're zoomed in too much (or have too many icons)

**Comment by JimMichael** [comment]
Will this be in 8.5?
