### ISSUE TITLE
Changes to "Person Attribute From Fields" Workflow Action

### ISSUE THREAD

**Issue by ajfick** [SparkDevNetwork/Rock#3332]
# Feature Request

**Describe the Feature Request**
The "Person Attribute From Fields" workflow action is an incredibly powerful workflow feature, but could be made much more robust with some small tweaks.. 

1. When the action searches for an existing person, rather than looking for an exact name match, it should be looking for match that is case insensitive. We have noticed that if someone fills forms that use this action, and do not capitalize their name, it can cause a duplicate to be created even when all other information matches (like email address).

 The below image shows this though the email address field is not displayed. All information but the name "AJ" v "Aj" was the same. 

![screen shot 2018-10-13 at 11 17 08 pm](https://user-images.githubusercontent.com/19314419/46912318-30e57200-cf40-11e8-9729-6ffa88d6fbd1.png)

2. It would be great to have a way to set an attribute if a new person was created and there was no existing match. For example, we have an online connect card that uses the Person Attribute from Fields action, and it would be great to serve ONLY newly created people a page asking a few more questions about them, or giving them a chance to let us know about their experience, or to add them to a connection. As it stands now we have to include a single select asking if they are new, and they would have to select yes for us to know. We will also end up with people telling us they are new when they really are not.

**Describe Preferred Solution**
In the case of the first suggestions, I would transform the person's attribute fields to lower case and compare those to lowercase search results. 

In the case of the second suggestion, I would add an option called "Set Attribute if a New Person Is Created" which could toggle a Boolean workflow Attribute to let the workflow know if a new person was created during the process or not. That would then be actionable later in the workflow and allow for further customization for a new user's experience.

**Describe Alternatives**
There may be a very valid reason that these features have not been implemented so obviously one alternative would be to not make these changes. 

**Providing Code**
I will provide code if feature request is approved: [Yes/No] No

**Comment by edmistj** [comment]
@ajfick great suggestions.
