### ISSUE TITLE
Null Reference Exception on Event Registration

### ISSUE THREAD

**Issue by dylan-gregory** [SparkDevNetwork/Rock#3333]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?    [X] * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?    [X] * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When registering for an event as an unauthenticated user, I get an ambiguous null reference exception.

### Steps to Reproduce
1. Attempt to register for an event anonymously
1. Fill out information, click "Finish"
1. If there is a first name/last name/email match for the registrar, registration completes successfully. If there isn't a match, it throws an exception:

![](https://user-images.githubusercontent.com/22873277/46973416-27b6eb00-d08f-11e8-8f19-68e99813e89f.png)

And this is from the exception log:

![](https://user-images.githubusercontent.com/22873277/46973519-7ebcc000-d08f-11e8-9cd4-9232c603e75a.png)

**Expected behavior:**

If there isn't a first name/last name/email match, it should create a new record and complete registration.

**Actual behavior:**

Null reference exception and failed registration.

### Versions
* **Rock Version:** 8.3
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
Unable to reproduce the error on 8.3 or 8.5. Each test creates new user(s) if one does not exist already. If the Registrant and Registrar are selected as being in the same family they are put into the same family group, otherwise two groups are created.

Are there any other messages on the exception detail block? A stack trace which includes a line number would be helpful. We can also check App_Data/Logs/RockExceptions.csv.

**Comment by nairdo** [comment]
@dylan-gregory are you still able to reproduce this problem in your current 8.5 (or 8.6) Rock system?  If so can you provide some detailed screenshots showing your event template configuration so we can figure out why you are able to reproduce this while we cannot?  Thanks!
