### ISSUE TITLE
Reports using Phone Number Person field give "Object reference not set" error, v8.3

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3338]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

I haven't been able to reproduce this in the demo account yet, so I don't know if it's been fixed in v8.4?  I can't see any other issues related to this, so I raise it just in case.

### Description
Reports in version 8.3 (1.8.3.36) that include PhoneNumber (home, mobile, work) as a field are failing to return the complete list of entries in the data set, and give the following error msg:

WARNING: There was a problem with one or more of the report's data components...
Object reference not set to an instance of an object.

**_Data View_**
Data View showing that there are more than 3 lines in the data view:
![phone2](https://user-images.githubusercontent.com/4658177/47012606-0e9e5f00-d1a1-11e8-80d0-96f7cb761da6.jpg)

**_Report showing incomplete results and error message_**

![phone1](https://user-images.githubusercontent.com/4658177/47012619-152cd680-d1a1-11e8-9c19-69b2fbcb1b87.jpg)

Removing the PhoneNumber fields removes the warning, and the report lists the complete result set.

### Steps to Reproduce
In version 8.3

1. Create a Data View of Person.
1. Create a report based on the Data View, and include one or more Phone Number fields.
![phone3](https://user-images.githubusercontent.com/4658177/47013039-5b366a00-d1a2-11e8-8ed5-1f79ccf4c882.jpg)

1. Run the report.

**Expected behavior:**

The report should list all the rows that are in the data set, and any phone numbers should correctly show.  Any rows without phone numbers should also correctly show.

**Actual behavior:**

The report gives an error, and only lists a few lines of the data set.

### Versions
Rock Version: Rock McKinley 8.3 (1.8.3.36)
Client Culture Setting: en-NZ

**Comment by ethan-sparkdevnetwork** [comment]
I was not able to reproduce this locally in 8.3 or 8.5. It sounds like invalid or missing data. Perhaps a number type was deleted? Probable that the error is in the 3rd or 4th record (David or Venu) and possibly more after that. Can you put the message from the exception log here?

**Comment by ethan-sparkdevnetwork** [comment]
Was not able to reproduce the error with person reports that include phone numbers in all versions of Rock tested (v8.3  & v9.*).

**Comment by ElimAdmin** [comment]
@ethan-sparkdevnetwork 
This occurs if the field NumberFormatted in the table PhoneNumber is NULL, and you try to include that number in a report using a Person, Phone Number field.  
Not sure why, but we had a lot of records in our PhoneNumbers table like this.
Reset them all as follows:
UPDATE PhoneNumber SET NumberFormatted = CONCAT('(',LEFT(Number,2),') ',SUBSTRING(Number,3,3),'-',RTRIM(SUBSTRING(Number,6,7))) ;
This resolved this issue.

**Comment by ethan-sparkdevnetwork** [comment]
I'll take another look at this and see what we can do to handle that more gracefully.
