### ISSUE TITLE
Timeout Exception when adding multiple people to family

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#3340]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When adding multiple people to family a "Wait Operation Timed Out" exception is occurring.  Note, this occurs when adding multiple people, I was not able to reproduce this when adding a single individual.

I have tested this in our live environment (8.3), the demo site (8.3) and a local copy of beta (8.4). Screen shots and stack trace from 8.4 attached

[stacktrace.txt ](https://github.com/SparkDevNetwork/Rock/files/2484195/stacktrace.txt)
![timeout1](https://user-images.githubusercontent.com/2363131/47034230-6060ce00-d13c-11e8-96d7-59b87e4a44b8.PNG)
![timeout2](https://user-images.githubusercontent.com/2363131/47034231-6060ce00-d13c-11e8-83fb-7618cddd9999.PNG)

### Steps to Reproduce
1. Load "Ted Decker's" person profile
1. Click the Edit Family button
1. Add two children to his family
1. Save the family
1. Exception will occur, transaction will rollback.

**Expected behavior:**

All family members will be successfully saved and added to the Decker family.

**Actual behavior:**

Wait Operation Timeout exception occurs and add transaction is rolled back.

### Versions
* **Rock Version:** 8.3 and 8.4
* **Client Culture Setting:** en-us

**Comment by nairdo** [comment]
@chrisfunk, can you tell me what your db settings are for these two items:
Allow Snapshot Isolation: ___
Is Read Committed Snapshot On: ___

_You can find your values by looking at the System Information's Diagnostics tab._

**Comment by chrisfunk** [comment]
@nairdo both are set to no in our production environment (8.3)

**Comment by JimMichael** [comment]
@nairdo... I see that this says it's fixed in 8.5, but @chrisfunk  says enabling those settings "fixed" it for him. We are seeing this issue, too... SHOULD we have those db settings set to Yes? Ours are no as Chris's were.

**Comment by dcs619** [comment]
@JimMichael Yes, those settings have been recommended in the internal hosting guide since Rock 1.4. Not sure if they were announced for the release notes or not.

**Comment by JimMichael** [comment]
Interesting. I would have followed the guide when we initially installed Rock (5.x), but maybe when we upgraded from SQL 2014 to 2017 it reset them?

**Comment by cabal95** [comment]
I don't think `Allow Snapshot Isolation` actually does anything. It just enables the feature in the database, but the individual queries have to request that it be enabled via `SET TRANSACTION ISOLATION LEVEL SNAPSHOT`. And if they run that command without the support, the queries fail.

Also, it should be noted that enabling RCSI on production (happens on dev too, but we don't care so much about dev) means that any delete or update operations basically filter through `tempdb` first. So if your main database is on fast SSD storage but your tempdb is still on slow HDD storage, you are basically bottlenecking yourself.

Finally, it looks like on Azure the default is Snapshot Isolation = false and Read Commit Snapshot = true
