### ISSUE TITLE
Defined Value field type throws an error in Event Registration

### ISSUE THREAD

**Issue by wmsheeler** [SparkDevNetwork/Rock#3342]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When using a "Defined Value" field type in an event registration, if that field is set to allow multiple values, enhance for long list, and show in grid, an error will be throw when attempting to view registrants of the event.

### Steps to Reproduce
1. Create a defined type with multiple defined values
1. add a form field to an event registration with field type of defined value and select your newly created defined type
1. Check the boxes for "allow multiple values", "enhance for long lists", and "show in grid"
1. Save registration form
1. Open an instance of that registration template
1. Click to view registrants tab
1. Receive an error ![screen shot 2018-10-16 at 5 03 24 pm](https://user-images.githubusercontent.com/18121367/47047402-79ca4000-d165-11e8-8363-b2479b5ede02.png)

**Expected behavior:**
Viewing the registrants tab should allow you to view the registrants without an error

**Actual behavior:**
Clicking the registrants tab, throws an error when show in grid is turned on for that specific field type of "defined value"

### Versions
* **Rock Version:** [8.3]
* **Client Culture Setting:** [EN-US]

**Comment by GerhardPowell** [comment]
Already fixed in https://github.com/SparkDevNetwork/Rock/commit/7a030603d2885eb7a0dab0c95f99bb51c2c8a156
