### ISSUE TITLE
Lava To PDF Header Template

### ISSUE THREAD

**Issue by drychlik76** [SparkDevNetwork/Rock#3345]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

Lava to PDF isn't installed on the demo site.  I tried 2 different systems, and could not get it to work.

### Description
A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce
1. Create a Page with Lava to PDF block
1. Flip the `Enable Header` template to `Yes`
1. Add header template content 
1. Save and Refresh.

**Expected behavior:**

Expected to see Header content display when rendering a lava to pdf report.

**Actual behavior:**

header template does not render

### Versions
* **Rock Version:** 8.3
* **Client Culture Setting:** English
![screen shot 2018-10-18 at 4 45 00 pm](https://user-images.githubusercontent.com/20803057/47186162-4dddc480-d2f5-11e8-86fc-e3da0b906009.png)

**Comment by drychlik76** [comment]
I just tried something else, and I see it working.  I am wandering if this is something to do with including bootstrap...  I may close this.

**Comment by edmistj** [comment]
@drychlik76 this is a plugin. Can you please email the developer?
