### ISSUE TITLE
Schedule Builder Recurrence for Specific Date only adds current date

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3346]
Is this intended functionality?

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When maintaining the schedule for a metric, selecting Recurrence, Specific Dates - it is only possible to add the current date; it is not possible to add specific future dates, and only one date can be added.

![sched1](https://user-images.githubusercontent.com/4658177/47209611-3e41a700-d3ed-11e8-831d-78998aa16a42.jpg)

Very minor:
The "X" to delete the specific scheduled date is right up against the date with no spaces - it would look better with more space between the date and the X.
![sched2](https://user-images.githubusercontent.com/4658177/47209856-ed7e7e00-d3ed-11e8-8827-beccdb8245d8.jpg)

### Steps to Reproduce

1. Go to Metrics, add a new metric.
2. Click Edit Schedule
3. Select Recurring, Specific Dates, and try to add multiple dates.
4. The only date shown will be the current date.

**Expected behavior:**

I expected to be able to add a list of multiple specific dates other than the current date.

**Actual behavior:**

Only the current date will 'stick' - no other dates can be added.

### Versions

Rock Version: Rock McKinley 8.4 (1.8.4.40)
Client Culture Setting: en-NZ

**Comment by edmistj** [comment]
I was able to add specific dates on this test metric:
http://rock.rocksolidchurchdemo.com/page/280?MetricCategoryId=7&ExpandedIds=C184
(will be gone in 24 hrs)

![image](https://user-images.githubusercontent.com/548178/47221310-e2cdd580-d368-11e8-9118-4c9425e52d52.png)

Wonder if it's an issue with internationalization? Can you check your javascript console as you attempt to add the dates?

**Comment by ElimAdmin** [comment]
@edmistj  Yes, Jon, this in an internationalization issue.  If I set the browser to English (US) I can add multiple dates.  If I set it back to English (NZ) I can't.

**Comment by vpgalon16** [comment]
Hi Jon,
Seems to me a browser issue.  It works on chrome and firefox except IE..
But are you able to save it? 

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 20, 2018 at 2:35 AM, Jon Edmiston<notifications@github.com> wrote:   
I was able to add specific dates on this test metric:
http://rock.rocksolidchurchdemo.com/page/280?MetricCategoryId=7&ExpandedIds=C184
(will be gone in 24 hrs)



Wonder if it's an issue with internationalization? Can you check your javascript console as you attempt to add the dates?
