### ISSUE TITLE
Stucked at "Preparing to run sql-install.sql" Step

### ISSUE THREAD

**Issue by GitenAR** [SparkDevNetwork/Rock#3348]
Hi, I'm trying to Instal Rock RMS on "Winhost Ultimate". I've downloaded my installer from http://storage.rockrms.com/install/installer/rockrms-install.zip. I've thoroughtly followed the documentation steps but once installation starts, it get's stucked at "Preparing to run sql-install.sql" Step. 

Is there any other way to install the application or to run this script?
Can you help me? 
Thank you in advance.

**Comment by jonedmiston** [comment]
@GitenAR hopefully you've been able to push through your problem. I'm closing this as this area is for known bugs in Rock. You might post this in the Rock Q&A area or in Chat if you still have issues.
