### ISSUE TITLE
Typo in Content Channel View Detail block in the Lava Template 

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3350]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Not sure if this is significant?

The content Channel Item Configuration lava template opens with 
actcile> and closes with 
/article>

### Steps to Reproduce
On demo site:
1. Go to http://rock.rocksolidchurchdemo.com/page/461?Item=33
2. Open the Content Channel View Detail block settings.
3. View the Lava Template code.

	artcile class="message-detail">
        ....
        /article>

**Expected behavior:**

**Actual behavior:**

### Versions

Rock Version: Rock McKinley 8.4 (1.8.4.40)
Client Culture Setting: en-NZ

**Comment by nairdo** [comment]
dev note: here is the original migration with the typo that needs to be fixed: https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Migrations/Migrations/Version%208.0/Version%201.8.0/201806111950515_ContentChannelViewDetail.sql
