### ISSUE TITLE
Custom Grid on the Communication List Block not enabled

### ISSUE THREAD

**Issue by TheCoreyHall** [SparkDevNetwork/Rock#3352]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Custom Grid Options for the Communication List Block is not setup or not allowed. Any attempt to enter Lava into the field there results in this error: 
![image](https://user-images.githubusercontent.com/38293092/47301457-8b3b9e00-d5e4-11e8-9e9b-35da2a4d3c53.png)

I have tested this on the demo site and this remains there as well as on the v9 site

### Steps to Reproduce

1. Go to Communication History from the Sidebar
2. Confirm that there is a communication on the list, if not send a test one
3. Go to the block settings and then to Custom Grid Options
4. Add a column with Header "Id" and attempt to enter any valid Lava such as {{Row.Id}} to the field
5. Click Save and reload the page to see an error in your new column.

**Expected behavior:**

The Row should display the Id of the communication.

**Actual behavior:**

Each row displays the error in the image above.

### Versions

* **Rock Version:** 8.3
* **Client Culture Setting:** en-us

**Comment by TheCoreyHall** [comment]
@nairdo Ive just found the same bug exists on the Communication Recipient List block.

**Comment by nairdo** [comment]
Thanks @TheCoreyHall.  I just fixed it in that block too.
