### ISSUE TITLE
Unable to Download Payments

### ISSUE THREAD

**Issue by mkinyon** [SparkDevNetwork/Rock#3353]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
The download payments page is not working.  Selecting dates or clicking the Download Transaction button will generate JS errors behind the scenes and prevent the user from downloading payments.  This seems to only happen in v8 or newer.  It works fine in v7.

![image](https://user-images.githubusercontent.com/2349102/47308699-364d5700-d5e7-11e8-88aa-10b7e0b69ae8.png)

### Steps to Reproduce

1. Go to Finance > Download Payments.
2. Open up your web browser's console. 
3. Choose a Payment Gateway and date range.
4. See the JS errors.

**Expected behavior:**
Not to do that.

### Versions

* **Rock Version:** 8.4, Pre-alpha Server
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
Corrected issues with the date range picker with input from @garrettjohnson , and simplified server-side script creation.

**Comment by nairdo** [comment]
Although it's not currently in the 8.5 alpha, after some additional discussion, this will be included in the 8.5 release (and beta).

**Comment by ethan-sparkdevnetwork** [comment]
We cherry-picked this fix into v8.5.
