### ISSUE TITLE
Category Picker does not show sub-categories

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#3357]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
The Category Picker control only shows the top-level categories. No sub-categories can be viewed or selected.

![image](https://user-images.githubusercontent.com/18447084/47370369-3747bc80-d6ab-11e8-929d-a960cf44c670.png)

### Steps to Reproduce
1. Go to Tools -> Event Registration
1. Make sure there are some sub-categories under the top-level categories.
1. Add or Edit a Template
1. Click on the Categories control

**Expected behavior:**

The top-level categories can be expanded to show sub-categories down through multiple levels.

**Actual behavior:**

Categories cannot be expanded, only top-level categories can be selected.

### Versions
* **Rock Version:** McKinley 8.4
* **Client Culture Setting:** en-US

**Comment by chrisfunk** [comment]
@ethan-sparkdevnetwork or @nairdo  shouldn't this https://github.com/SparkDevNetwork/Rock/blob/ccc4b0d768dd8833dd1c904cf0e54dd405576f35/Rock.Rest/Controllers/CategoriesController.Partial.cs#L252 be at line 199?

**Comment by karenn-ccbc** [comment]
This appears to be fixed in 8.5? when can we expect the update?

**Comment by edmistj** [comment]
8.5 was released for Alpha testing earlier this week. Should be in Beta in 2 weeks and production 2 weeks after that.
