### ISSUE TITLE
Custom logo not used in mobile menu

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#3358]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
Mobile devices show the Rock logo in the menu instead of the custom logo.

PC Browser:

![image](https://user-images.githubusercontent.com/18447084/47373536-ade7b880-d6b1-11e8-9742-8e4beb629e8b.png)

Mobile Browser:

![image](https://user-images.githubusercontent.com/18447084/47373569-bdff9800-d6b1-11e8-9aab-2dff33d834d8.png)

Note that #3319 is related, if you shrink your PC browser down small enough, neither logo appears.

### Steps to Reproduce
1. Add a custom site logo in the Site page.
1. Load the homepage on a mobile device.
1. Press the menu button

**Expected behavior:**

The custom logo would display at the top.

**Actual behavior:**

The Rock logo displays at the top.

### Versions
* **Rock Version:** McKinley 8.4
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
Just to add what I see... on 8.4, if I shrink the window just to the point that the logo disappears, it does NOT show in the hamburger menu, but if I continue to shrink down further to true "mobile" size, the logo DOES appear in the hamburger menu. (I'm only referring to the logo showing/not showing, not to the issue that it's the wrong logo)
