### ISSUE TITLE
[EN] Better reporting for registrations and registrant attributes

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#3359]
# Feature Request
For Registrations and custom Registration Attributes, the average user does not have a good way to create custom reports.  An export can be created from the Registration or Registrant list, but requires manual reconciliation to create a custom report.

For example, to create a Person report for anyone registered with a custom attribute `Additional Comments`, you would create a DataView on Registrants in a Registration Instance (so far so good).  Next up, a report to display the person's Name (exists), Cell Phone (exists), Registration Balance (??), and Additional Comments (??).

The lava necessary to pull Additional Comments looks something like this (it breaks for more than one returned value):

```
{% capture registrationId %}
{% registrationregistrant where:'PersonAliasId == {{PersonAliasId | Select:"Id"}}' iterator:'registrants' %}
    {% for reg in registrants %}
        {{ reg.RegistrationId }}
    {% endfor %}
{% endregistrationregistrant %}
{% endcapture %}

{% capture instanceId %}
{% registration id:'{{registrationId}}' iterator:'registrations' %}
    {% for reg in registrations %}
        {{ reg.RegistrationInstanceId }}
    {% endfor %}
{% endregistration %}
{% endcapture %}

{% capture templateId %}
{% registrationinstance id:'{{instanceId}}' iterator:'instances' %}
    {% for inst in instances %}
        {{ inst.RegistrationTemplateId }}
    {% endfor %}
{% endregistrationinstance %}
{% endcapture %}

{% capture attributeId %}
{% attribute where:'Name == "Additional Comments" && EntityTypeId == 297 && EntityTypeQualifierValue == {{templateId}}' iterator:'attributes' %}
    {% for att in attributes %}
        {{ att.Id }}
    {% endfor %}
{% endattribute %}
{% endcapture %}

{% attributevalue where:'AttributeId == {{attributeId}} && EntityId == {{PersonId}} && Value != ""' iterator:'values' %}
    {% for val in values %}
        {{ val.Value }}
    {% endfor %}
{% endattributevalue %}

```

**Describe the Feature Request**
In the spirit of Rock innovation, this could be a lot simpler (especially for the non-dev community).

**Describe Preferred Solution**
I'm open to anything better than custom Lava, but a new Person Reporting field called `Attribute in Registration Type` seems like the best solution. `Current Balance in Registration Type` would also be fantastic.

**Describe Alternatives**
A better Lava filter designed to pull Registration attributes.

**Providing Code**
I will provide code if feature request is approved: TBD

**Comment by edmistj** [comment]
Agree that this would be a nice feature. With the proposed reporting fields, how would you handle cases where a person was in two registration instances of the same type?  Would creating a new Report Page on the registration instance work?

**Comment by chead4** [comment]
We are doing some housekeeping and came across this oldie but goodie enhancement request.  If this is still a feature that others are interested in we’d recommend submitting an idea on the Rock Community Ideas board via http://community.rockrms.com/ideas.
