### ISSUE TITLE
Grid control requires horizontal scrolling to use actions when results are too wide for screen

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#3361]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When a grid has many columns which cause the results to be wider than the screen (particularly on reports and Event Registrants when the registration has many questions), the action buttons at the top and bottom of the grid are not visible. In order to see them, you must scroll to the bottom of the grid to find the horizontal scrollbar, then scroll all the way to the right. This is particularly frustrating now that the buttons are finally at the top of the grid, but can't be reached without scrolling down.

![image](https://user-images.githubusercontent.com/18447084/47381712-48ea8d80-d6c6-11e8-9f4c-15e4966e7943.png)

The pagination controls also scroll off the screen when the grid is scrolled over to find the action buttons.

![image](https://user-images.githubusercontent.com/18447084/47381745-556ee600-d6c6-11e8-84cb-1e14a748e050.png)

The filter button does not scroll off the screen, as it seems this was given an absolute positioning style, though there are times when this positioning causes other odd behavior.

Ideally all of the controls above and below the grid results would be outside the scrollable window area and only the data would be moved around with those scroll bars.

### Steps to Reproduce
1. Find a grid with many columns and some action buttons, such as http://prealpha.rocksolidchurchdemo.com/RegistrationInstance/2
1. Resize the window to be very narrow (to mimic a grid with many columns).

**Expected behavior:**

The controls on the top and bottom of the grid would be visible at all times, regardless of the width of the data.

**Actual behavior:**

All controls at the top and bottom of the grid except the Filter button disappear off the side of the screen when scrolling to the left or right.

### Versions
* **Rock Version:** McKinley 8.4 - 9.0
* **Client Culture Setting:** en-US

┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;893880776290498">image.png</a>

**Comment by edmistj** [comment]
@chrismcgrath we'll look into a solution for this.

**Comment by edmistj** [comment]
We don't see a simple issue for this that doesn't not require a lot of javascript.
