### ISSUE TITLE
Add ICustomGridColumns to PersonDuplicateDetail block

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3362]
# Feature Request

**Describe the Feature Request**

We want to add custom columns to the Person Duplicate Detail block to help staff prioritize which records need to be merged. I believe we can do this with a custom column, but the block does not have those enabled by default. I added it to our block and it seems to work fine without issue.

**Describe Preferred Solution**

Add the `ICustomGridColumns` interface to the block so that admins can add custom columns.

End goal:

![image](https://user-images.githubusercontent.com/1119863/47393281-e5675c80-d6d3-11e8-95fb-b5171aa5908d.png)

**Describe Alternatives**

Discussed a "stock column" to achieve this, but since space is already limited on that grid making it up to the admin to decide what extra details they want seems preferable.

**Providing Code**
I will provide code if feature request is approved: **Yes** (all 14 characters of it)

**Comment by cabal95** [comment]
Most Person Duplicates that I looked at are fairly low row count. So compared to the Group Member block this should be exceedingly performant. :)

**Comment by JimMichael** [comment]
Did you end up using Entity commands for sql for that column, or did you find some easier way? (just curious)

**Comment by cabal95** [comment]
Just for reference for the couple people that asked how I achieved the screenshot, **Once this addition to core has been applied**, you can do the following.

Setup a lava shortcode with the tag `personfinancialtransactioncount` as Inline. The lava template is:
```
{%- sql -%}
SELECT
COUNT(*) AS [count]
FROM [PersonAlias] AS PA
INNER JOIN [FinancialTransaction] AS FT ON FT.[AuthorizedPersonAliasId] = PA.[Id]
INNER JOIN [FinancialTransactionDetail] AS FTD ON FTD.[TransactionId] = FT.[Id]
INNER JOIN [FinancialAccount] AS FA ON FA.[Id] = FTD.[AccountId]
WHERE PA.[PersonId] = {{ personid | AsInteger }} AND FA.[IsTaxDeductible] = 1
{%- endsql -%}
{{- results[0].count -}}
```

Then on your Person Duplicate Detail block, you can add a custom column with the following lava:
```
{%- capture count -%}
    {[- personfinancialtransactioncount personid:'{{ Row.PersonId }}' -]}
{%- endcapture -%}
{%- if count > 0 -%}
  <div class="text-center"><i class="fa fa-2x fa-money"></i></div>
{%- endif -%}
```
