### ISSUE TITLE
[EN] Profile link from Connection Request Detail opens blank page if opened in new tab

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3363]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When viewing a Connection Request Detail page there is an option to open the person's profile.  Clicking this link within the same page opens the person profile page successfully.  Right clicking the Profile link, and selecting 'Open in new tab' opens a blank page: about:blank.  It would be helpful if the Profile could be opened alongside the Connection Request Detail in stead of over the top of it.

### Steps to Reproduce
On the demo site:

1. Go to People,Connections.
1. Select 'All Connections' and click Childrens.
1. Open the Evens, Helen connection.
1. Right click the Profile link, and select Open in new tab.

**Expected behavior:**

The Profile should open alongside the Connection Request Detail page.

**Actual behavior:**

A blank page is opened.

### Versions
Rock Version: Rock McKinley 8.4 (1.8.4.40)
Client Culture Setting: en-NZ

**Comment by morganw93** [comment]
What browser was this in? 
When I right click on the profile button in safari I don't see an option to open in new tab or window.

**Comment by morganw93** [comment]
I was able to duplicate in Chrome!
