### ISSUE TITLE
Kiosk blocks not working in 8.x

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3367]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

It looks like the jQuery update that was done awhile ago broke a couple of the `.Kiosk.ascx` blocks. Specifically the `PersonUpdate.Kiosk.ascx` block and the `TransactionEntry.Kiosk.ascx` block are affected for sure.

Our quick local fix was to wrap the entire javascript initialization inside a `setTimeout(..., 10)` statement so that it initializes 10ms after the page loads, which gives time for jQuery to make things visible.

### Steps to Reproduce

1. Go to http://www.rocksolidchurchdemo.com/kiosk
2. Click the `Give` button or the `Update Info` button
3. Try to click any of the phone entry buttons.
4. See that nothing happens.

**Expected behavior:**

The buttons should function.

**Actual behavior:**

The buttons don't do anything.

### Versions

* **Rock Version:** 8.4 (possibly back to 7.4)
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Looks to be in v1.8.5
