### ISSUE TITLE
Complete the table UI updates

### ISSUE THREAD

**Issue by luke-b-taylor** [SparkDevNetwork/Rock#3371]
# Feature Request

**Describe the Feature Request**
The redesign on tables to move the control elements to exist both above and below the table is great. It would be terrific if the table size selector, total entry counter, and page selector was also above the table entries.

**Describe Preferred Solution**
Copy the number selections and displays up top please.
Current View:
![Current view](https://user-images.githubusercontent.com/32314302/47467250-511bf900-d7aa-11e8-8939-6f1097aff381.png)

Proposed View:
![Proposed look](https://user-images.githubusercontent.com/32314302/47467258-6133d880-d7aa-11e8-8085-8bdeebbff677.png)

**Describe Alternatives**
Can't think of anything more useful

**Providing Code**
I will provide code if feature request is approved: [No]

**Comment by edmistj** [comment]
In an attempt to keep from adding additional weight to the grids we don't want to move the paging to the top of the grid. This feels like something that should remain at the bottom.
