### ISSUE TITLE
[EN] Rock 'New Question' with titles too long are not saved and no explanation is given

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3375]
### Description

When Asking a question on the Rock New Question pages, if the title of the question is too long, when you click Ask Question, the page does not save, and no warning or explanation is given as to why not. 

### Steps to Reproduce

1. Ask a Question on the Rock New Question page and enter a really long title.  
2. Click Ask Question.  
3. The page will not save with no explanation.

**Expected behavior:**

Give an explanation or warning that the title is too long.

**Actual behavior:**

The page does not save and there is no expalantion.

### Versions

??

**Comment by GerhardPowell** [comment]
Fixed applied in https://github.com/SparkDevNetwork/Rock-SparkSite/commit/f27c6d6620a13a42867df6705b7451246a7726db
