### ISSUE TITLE
Changing the key of a Global Attribute

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#3376]
### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

Someone intended to change the value of the PublicApplicationRoot global attribute and instead edited the attribute and changed the key. It broke a number of things! I'm not thinking of any situation where editing the actual attribute should be allowed. Yes, values need to be changed but that should be all that is editable.

Also, the PublicApplicationRoot and InternalApplicationRoot should be URL types to ensure they are properly formatted.

### Steps to Reproduce ###

1. Go to General Settings > Global Attributes
1. Click on the edit button
1. Change the key to any attribute and break Rock in new and exciting ways!

**Expected behavior:**

Admins to not be able to change keys for Global Attributes

**Actual behavior:**

Admin changes the key and all manner of things break

### Versions ###

* **Rock Version:** [7.4 and 8.3]
* **Client Culture Setting:** [en-us]

**Comment by jonedmiston** [comment]
Solution:
Update the AttributeEditor control to disable editing when an attribute is marked `IsSystem = true`. Should also add a label warning at the top `'Editing is not enabled on system attributes.`

**Comment by jonedmiston** [comment]
Closing this as it looks to be solved. The Attribute Editor no longer allows you to edit the key of a `IsSystem` attribute.
