### ISSUE TITLE
Prayer Request adds phone number of request to Prayer Comments

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3377]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Submitting a prayer request with a phone number puts the phone number into the Prayer Comments.  

### Steps to Reproduce

1. Submit a prayer request through the external page and enter a phone number.
2. View the Prayer Request. Home > Prayer > Prayer Request > the request you entered.
3. The phone number is not shown alongside the email, but in the comments.
4. View the list of Prayer Comments.  Home > Prayer > Prayer Comments.
5. You will see all the phone numbers from all submitted prayer requests.

**Expected behavior:**

The phone number should show next to the email on the prayer request detail, not as a Prayer Comment.

**Actual behavior:**

Phone numbers from prayer requests are being added to prayer comments.
![prayercomment1](https://user-images.githubusercontent.com/4658177/47590723-af72f280-d9c9-11e8-85e7-bde2152519be.jpg)

### Versions

Rock Version: Rock McKinley 8.4 (1.8.4.40)
Client Culture Setting: en-NZ

**Comment by GerhardPowell** [comment]
The phone number was written as a note in 8.4
The behavior is changed in 8.5. Now it only use the phone number to lookup / create a person. 

The change can be seen in:
https://github.com/SparkDevNetwork/Rock/commit/90858fba130f7bfd0407a8a7d1ad438591fe8b79
