### ISSUE TITLE
Communication Delivery Page (Wizard) Does Not Allow Selection of Medium

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3378]
### Description

The Communication Delivery page of the Communication Wizard lost the ability to choose the medium (User Preference/ Email / SMS).

### Steps to Reproduce

1. People | New Communication
2. Add someone to the communication or choose a list and click Next.
3. Observe that on the Communication Delivery page you no longer have a choice for the communication Medium.

**Expected behavior:**

You would be able to choose the Communication Medium

**Actual behavior:**

You can't.
![image](https://user-images.githubusercontent.com/3903408/47592346-9110e680-d938-11e8-8588-bde79673d9d6.png)

### Versions

***Rock Version:** 8.4 / Prealpha

**Comment by ethan-sparkdevnetwork** [comment]
I was not able to replicate the issue.
The communication medium selection will only show if the allowed types is more than 1.
These are set in block settings. If none are selected then rock will show them all, otherwise only show the ones selected.

**Comment by JimMichael** [comment]
I do not understand your comment. Can you help me understand what an "allowed type" is and where I set it? My production 8.3 server shows communication medium option, but my 8.4 test instance on the same (copy) db does not, with the exact same (as far as my old eyes can tell) block settings. It also doesn't show on demo or prealpha for me, again with default block settings. 

I DO see the "communication types" section in block settings (if that's what you're meaning), but they have no effect. Checking just Email or SMS ,or all of them, or none of them has no effect on 8.4 for me.

Finally, in addition to not being able to get the Communication Medium option to show AT ALL regardless of the type settings, if I edit the block settings and check ONLY _Recipient Preference_, it throws an exception... which I also duplicated on demo.

**Comment by JimMichael** [comment]
AH, found it. It doesn't show options when SMS transport is disabled... which is how my test server is set up. And explains why demo and prealpha don't work, either. Just a funny coincidence that the only 8.4 server I have had Twilio disabled, and I could "dupe" it on demo. Sigh. Sorry for the false alarm!
