### ISSUE TITLE
Rock is using deprecated webhooks for Mailgun

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3379]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Apparently Mailgun has deprecated the version of Webhooks that Rock uses. This is causing confusion for end-users. When they try to follow the guide and set the webhook URL it fails because that is now the "new version" of the webhook.

Deprecated version: https://documentation.mailgun.com/en/latest/api-webhooks-deprecated.html#webhooks-deprecated

New version: https://documentation.mailgun.com/en/latest/api-webhooks.html#webhooks

I haven't had a chance to dig into what has actually changed, but trying to use the current web handler for Mailgun with the new Webhook results in a 406 wrong mime type response.

**Expected behavior:**

Mailgun webhooks should work

**Actual behavior:**

Mailgun webhooks do not work unless configured for legacy mode (which could be removed in the future).

### Versions

* **Rock Version:** 8.4+
* **Client Culture Setting:** en-US

┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;876761498807661">mailgun webhooks.png</a>

**Comment by nairdo** [comment]
It looks like we (thanks @mikejed) [updated this in the documentation ](https://www.rockrms.com/Rock/BookContent/8/130#emailmailgun) about a month ago, but we'll work out the webhook to handle the new format as well for an upcoming release.

**Comment by cabal95** [comment]
Awesome. The person I was talking to was probably going off an old PDF version of the guide or something. I hadn't checked the docs myself. :( @cabal95--
