### ISSUE TITLE
Calendar Feeds Should Observe Regional Setting

### ISSUE THREAD

**Issue by ricsrock** [SparkDevNetwork/Rock#3389]
### Description ###

The calendar feed displays event start/end times in UTC rather than honoring the regional setting System Settings > System Configuration > Web.Config Settings.

When the iCal feed from Calendars > Public > Export Calendar Feed (for example) is displayed in OSX Calendar (for example), the event start/end times are incorrect. They appear in UTC rather than following the regional settings. 

### Steps to Reproduce ###

1. Go to Calendars > Public
1. Click on Export Calendar Feed
1. Open Calendar in Mac OS (or any other app that supports iCal)
1. In Calendar, choose File > New Calendar Subscription
1. Paste in the Calendar Feed url from the Rock calendar.

**Expected behavior:**

The Rock calendar feed should display event start/end times that are consistent with how they are displayed in Rock, according to the regional setting in the Rock portal.

**Actual behavior:**

The Rock calendar feed displays event start/end times in UTC rather than respecting the regional setting.

### Versions ###

* **Rock Version:** [8.4]
* **Client Culture Setting:** [en-US]

**Comment by ethan-sparkdevnetwork** [comment]
This was fixed in 12.1 with the update from DDay to ical.net. Verified functionality in 16.1.
