### ISSUE TITLE
Prayer Request Detail Block Category field can't select child categories.

### ISSUE THREAD

**Issue by DrArmus** [SparkDevNetwork/Rock#3390]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When a Prayer Request is entered from http://rock.rocksolidchurchdemo.com/page/430 or edited you are unable to select a child category from the Category field. 

### Steps to Reproduce

1. On the Demo Site: Go to General Settings -> Prayer Request Categories
2. Verify that the All Church Prayer Category has 19 child categories
2. Go to Prayer -> Add Prayer Request
3. Open the Category field drop-down menu
4. Only the parent category (or categories) are available.

**Expected behavior:**

This drop down should show all categories for Prayer Requests.

**Actual behavior:**

Only the top parent categories are available. 

### Versions

* **Rock Version:** [8.4 (1.8.4.40)]
* **Client Culture Setting:** [en-US]

![capture](https://user-images.githubusercontent.com/4846426/47736629-ad609c00-dc34-11e8-8e52-39a10051b7f0.PNG)

**Comment by cabal95** [comment]
Thanks for the report, this was just fixed the other day. See #3357. Fix should be in 8.5
