### ISSUE TITLE
Group Member Attribute Lava does not work in report field

### ISSUE THREAD

**Issue by thewesleyjones** [SparkDevNetwork/Rock#3394]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When creating a report from a Group Member Dataview, specifically added group member attributes (those added to the specific group, not added to the group type) do not populate the field with LAVA like {{ Member | Attribute: 'key' }}

### Steps to Reproduce
1. Go to Dataviews and create a group member dataview for the group in question
1. Create a new report
1. Add a field for a group member attribute for the group type (this works)
1. Add a LAVA field {{ Member | Attribute: 'key' }} (this does not pull the key for s group member attribute added to the group)

**Expected behavior:**

The LAVA {{ Member | Attribute: 'key' }} should pull the attribute into the report

**Actual behavior:**

The LAVA {{ Member | Attribute: 'key' }} shows in the report as a blank field.

### Versions
* **Rock Version:** [Rock McKinley 8.4 (1.8.4.40)]
* **Client Culture Setting:** [en-US]

**Comment by cabal95** [comment]
Try using `{{ Row | Attribute:'key' }}` instead. Reporting and other "generic use" areas of Rock often use "Row" as the lava variable for the object since they don't know what what kind of object it is.

**Comment by cabal95** [comment]
Actually, it looks like that syntax was just added 29 days ago in commit 19e370945db5b7868bbd8583894159ec9338c877. You will probably need to wait until 8.5 or maybe 9.0 for that syntax to become available.
