### ISSUE TITLE
Security Model within Reports doesn't properly use inheritance.

### ISSUE THREAD

**Issue by krallsm** [SparkDevNetwork/Rock#3396]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce
1. Go to CMS Configuration
1. Go to Pages
1. Go to Internal Homepage > Go to Reports
1. Set a Security Role to Edit/Administrate
1. Go to Tools/Reports
1. Impersonate someone of the Security Role to Edit/Administrate the Reports
1. The security role cannot edit/administrate the reports unless they are the creator or rock administrator

**Expected behavior:**

That when editing the security permission for the reports page that the roles would be inherited all the way down to the specific reports. If this is not the intended idea for the security model within reports. I'd expect that at least by editing the Reports Entity security and applying Edit/Administration privileges that those privileges would leak down into all the reports as well.

**Actual behavior:**

When applying edit/administrate privileges to the Report Tree and Report Entities, the permissions are not inherited by the all Reports ever created

### Versions
* **Rock Version:** [8.3]
* **Client Culture Setting:** [en-US [[https://github.com/SparkDevNetwork/Rock/files/2539108/RockDiagnostics-TBCROCKWEB.txt](https://github.com/SparkDevNetwork/Rock/files/2539108/RockDiagnostics-TBCROCKWEB.txt) RockDiagnostics-TBCROCKWEB.txt ]()

**Comment by JimMichael** [comment]
Per Slack discussion, any non-Admin role that needs "global" edit rights to reports/dataviews needs Edit ro Rock.Model.Category entity.

**Comment by smross** [comment]
I do not think this is really a bug. I think it's more of an issue of understanding Rock's security model, the out of box 'Reports' page, and the stated goal @krallsm has. The description and steps to reproduce are not specific enough to know for sure. The term _entity_ is used when referencing a page but in the context of a specific page holding report blocks. I do not believe entity is the proper term there per Rock's definition of what an entity is.
I have tried replicating this issue on Demo (9.x) and Prealpha (11.x) without finding a problem.
As @JimMichael mentioned, you _can_ give specific rights for an entity (such as report) by going to Admin Tools > Security > Entity Administration and modifying the _entity permissions_ 

For reference, here's how Rock's security model works when managing security for the _Reports_ page (the page that this issue references):

- Create a _category_ on the standard _Reports_ page
- The _category_ will have permissions configured to allow "All Users" view access _to the category and it's children (reports or categories)_ by default. These can be modified, either at the category level, or at the entity level

To give a security role permissions to Edit any report or category that is it's child. Keep in mind that if an _item level_ permission is defined for a child, it will take precedence over the inherited permission:

1. Select a top-level category and select the permissions modal button (the padlock)
2. Add an _Item Permission_ and select the _Add Role_ button.
3. Select the security role you would like to use, select the _Edit_ checkbox, and select the _Add_ button
4. Done! (but do examine and make sure that your Item and Inherited permissions are both now set appropriately)

**Comment by jonedmiston** [comment]
Agree with @JimMichael and @smross assessment.
