### ISSUE TITLE
Connection Request Timeout With Large Amount of Data

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#3397]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

My Connection Opportunities block will cause the page to time out when there is a ton of Connection Requests.

### Steps to Reproduce

In my case, there was 250k+ Connection Requests.
1. Go to Connections page
2. Wait for server timeout

It's the only block on the page that is different than other pages, so I feel comfortable saying it's the MyConnectionOpportunities block.

**Expected behavior:**

The page should load in a reasonable amount of time.  By reducing the number of Connection Requests drastically, I could get the page to load.

**Actual behavior:**

The page timed out trying to load.

### Versions

* **Rock Version:** 8.3
* **Client Culture Setting:** en-us

**Comment by nairdo** [comment]
@NuclearTacos Chris, Thanks for this fix!
