### ISSUE TITLE
Merge Templates from Communication Fails

### ISSUE THREAD

**Issue by cbump** [SparkDevNetwork/Rock#3400]
### Prerequisites
* [  X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
We aren't sure if other people use this functionality but it seems like it would be a very common process.

We often send emails to large groups or lists even if they don't have email addresses.  For anyone that did not have an email on file or that fail, we would like to output mailing labels. However, when outputting from the failed list within the communications detail, we only get blanks.

The icon is available, but when when try to do the merge, no info comes out in the labels.

### Steps to Reproduce
1. Go to an existing sent communication that has some failures.
1. Click on the red box that says "Failed"
1. Scroll down to the grid that shows all the communication recipient failures.
1. Click the merge button to create a merge template.
1. Since the output are communication recipients, this would require a special merge template.  All standard person merge templates will output blank.

**Expected behavior:**

The output of the labels should be populated

**Actual behavior:**

The output of the labels is blank

### Versions
* **Rock Version:** 1.8.4
* **Client Culture Setting:** en_US

**Comment by cbump** [comment]
@edmistj We can PR a change to the MergeTemplateClick for the Fail grid which will convert the communication recipients to people if you feel that is the correct approach.  Alternatively, we can create special merge templates for this use case.

**Comment by edmistj** [comment]
@cbumb sounds good
