### ISSUE TITLE
Group finder day filter does not find custom schedules

### ISSUE THREAD

**Issue by tstephens17** [SparkDevNetwork/Rock#3405]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * [x] Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * [x] Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * [x] Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
If custom schedules is enabled for the group type, the group finder day filter does not find them. Example, a group with a custom schedule of every 2 weeks on Thursday will not be found by the group finder if Thursday is selected. Even if the schedule was every 1 week on Thursday, no dice.

A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce
1. Set a regular weekly schedule of a day, let's say Thursday.
1. Use the group finder and day filter set to Thursday. 
1. Notice the group is there.
1. Change to a custom schedule of every 1 week on Thursday.
1. Search again.
1. Group is gone.

**Expected behavior:**

1. I expected the group to be there.

**Actual behavior:**

1. Group is not shown.

### Versions
* **Rock Version:** [Rock McKinley 8.3 (1.8.3.36)]
* **Client Culture Setting:** [en-US]

**Comment by cabal95** [comment]
Unfortunately I don't think this can be fixed. For a custom schedule, the schedule data is stored as an iCal string (which is long and cannot be parsed in SQL). Because it can't be parsed in SQL, where the DataView filtering happens, I don't think this can happen.

The only way I could think to do this would be to load ALL groups into memory and then process their schedules. That could add a decent delay to the load. Custom schedules also present other issues, such as a group that meets on multiple days of the week, or on odd weeks, etc.

**Comment by tstephens17** [comment]
I will say that a major percentage of our groups meet every other week or on a 1st/3rd or 2nd/4th rotation. So, this really hurts our group finder. I understand the difficulty but I think we all can agree that the group finder should be able to find custom schedules.

**Comment by jrockman13** [comment]
What about the idea of persistence? So, once per day/hour/etc a calc is made and then when a userfilters for groups based on a specific day of the week, it returns the stored results?

**Comment by chead4** [comment]
@tstephens17  We are doing some housekeeping and came across this oldie but goodie enhancement request.  In regards to the Block Configuration/Group Finder Configuration - Day of Week filter not displaying custom schedules, I'd recommend submitting this as an idea on the Rock Community Ideas board via http://community.rockrms.com/ideas. This allows the full community to speak into it and help us determine it's priority.
Thank you for the detailed submission and for helping to make Rock better!
