### ISSUE TITLE
Rock Cleanup Job Timeout

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#3409]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

_I have not been able to reproduce on the demo site because of the smaller dataset_

### Description
The Rock Cleanup job is throwing a run time exception on the Person Cleanup step.  When I step through it manually I find that it is throwing a SQL Execution timeout (see stack trace below).  The job is failing probably about 60% of the time.  There have also been reports of other users seeing this behavior in the Troubleshooting channel in Slack.

I have been able to step through and completely run the job in Visual Studio by adjusting the command timeout on several of the RockContext instances. 

### Steps to Reproduce
1. Run the Rock Cleanup job on a larger database

**Expected behavior:**

Job will complete successfully.

**Actual behavior:**

A description of what actually happened.

### Versions
* **Rock Version:** 8.4 (1.8.4)
* **Client Culture Setting:** en-us

**Comment by nairdo** [comment]
Thanks @chrisfunk. I don't see a stack trace attached here, can you attach one? Also, can you attach a screenshot showing your job's settings?

I just verified -- this job is running successfully on rock systems with over 419,000 people records and millions of table rows:

![image](https://user-images.githubusercontent.com/383807/48288417-4360a780-e429-11e8-803f-944633374615.png)

Here's an example output from a recent job run on one of those systems:
> Rock Cleanup cleaned up 361 Exception Logs, 12055 Expired Entity Sets, 67398 Old Interactions, 170106 Workflow Logs, 39 Orphaned Attribute Values, 3 Transient Communications and 4483 Person Tokens

**Comment by chrisfunk** [comment]
Rock Clean-up exception

[personcleanup.txt](https://github.com/SparkDevNetwork/Rock/files/2573519/personcleanup.txt)


Screen Shot
![rock cleanup settings](https://user-images.githubusercontent.com/2363131/48373866-b6b42480-e688-11e8-842e-71ba623ee438.PNG)

**Comment by nairdo** [comment]
From the stack trace, it appears to be having trouble with the `UpdatePrimaryFamilyAll()` method.  On the system where you are seeing this problem, are you able to run this manually?  If so, how long does it take?

```
-- lookup Family Group Type Id for use in stock query below...
DECLARE @GROUPTYPEID INT = (SELECT Id FROM GroupType WHERE [Guid] = '790E3215-3B10-442B-AF69-616C0DCB998E' )

UPDATE x
SET x.PrimaryFamilyId = x.CalculatedPrimaryFamilyId
FROM (
    SELECT p.Id
        ,p.NickName
        ,p.LastName
        ,p.PrimaryFamilyId
        ,pf.CalculatedPrimaryFamilyId
    FROM Person p
    OUTER APPLY (
        SELECT TOP 1 g.Id [CalculatedPrimaryFamilyId]
        FROM GroupMember gm
        JOIN [Group] g ON g.Id = gm.GroupId
        WHERE g.GroupTypeId = @GROUPTYPEID
            AND gm.PersonId = p.Id
        ORDER BY gm.GroupOrder
            ,gm.GroupId
        ) pf
    WHERE (
            p.PrimaryFamilyId IS NULL
            OR (p.PrimaryFamilyId != pf.CalculatedPrimaryFamilyId)
            )
) x 
```

**Comment by chrisfunk** [comment]
It took about 32 seconds. I have also seen it throw the same exception in either of the AddMissionRelationshipGroups functions

**Comment by nairdo** [comment]
Fixed by additional timeout job setting for use in the PersonCleanup() and methods via AddMissingRelationshipGroups() via commit 9addc155a3227ea4b395835cee7e3f25c3d58096
