### ISSUE TITLE
Person Attribute Type Rating not visible in normal view

### ISSUE THREAD

**Issue by jrockman13** [SparkDevNetwork/Rock#3411]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
A person attribute of field type "rating" does not display the stored value unless the edit "pencil" is clicked.

### Steps to Reproduce
1. Go to Rock Demo
1. Add a new person attribute with type of "rating" and assign to a visible category on extended attributes
1. Go to a person's record and add a star rating value to the attribute
1. Click Save. Note the star rating does not display
1. Click the Pencil. Note the start rating DOES display

**Expected behavior:**
Rating value should be visible in "normal" view

**Actual behavior:**

Rating value only displays in "Pencil"view (edit)

### Versions
* **Rock Version:** [8.4]
* **Client Culture Setting:** [en-us]

**Comment by garrettjohnson** [comment]
Fixed in 8.5 via c27264ca5c270ec5fa9b12313ee9ee61d32479a5
