### ISSUE TITLE
Check-In Detail attendance not keeping Campus from location entered

### ISSUE THREAD

**Issue by atorrance** [SparkDevNetwork/Rock#3412]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When adding attendance via Check-In Detail with a location and schedule it is showing the campus as 'null' on the attendance analytics page when viewed instead of the campus for that location entered.

![check-in detail](https://user-images.githubusercontent.com/34725020/48284725-401bea80-e42e-11e8-92c4-a0ff5c5a9619.gif)

### Steps to Reproduce
1. Go to 'Attendance Analytics' and choose your group.
1. Click on 'Check-In Detail'
1. Select a group and Add attendance with a Location and Schedule. 
1. Go back to attendance analytics and look up the attendance just added, you will see the campus is null instead of the campus for the location entered. 

**Expected behavior:**

The Campus for the attendance entered should show the campus as the campus for the location entered in Check-In Detail instead of 'null'

**Actual behavior:**

The Campus shows as 'null'.

### Versions
* **Rock Version:** [8.4 & 9.0]
* **Client Culture Setting:** [en-US]

┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;908497591219223">image.png</a>

**Comment by ethan-sparkdevnetwork** [comment]
Fixed error caused by fix in 2940.
LocationService.GetCampusIdForLocation() returns a null if the location ID passed in has a campus.
Issue did not occur if the location is a descendant of a location with a campus.
