### ISSUE TITLE
Dynamic Report timing out on a persisted DV

### ISSUE THREAD

**Issue by karenn-ccbc** [SparkDevNetwork/Rock#3418]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
Dynamic Report times out on a complex  persisted DV

### Steps to Reproduce
1. Created a complex dataview based on other dataviews. (Cannot reproduce the complex dataview on Demo.) Had to increase timeout to 8 min for it to run. 
1. Set it to Persisted for a day 1440 minutes. It now loads quickly as well as the report built off of it. 
1. I reference that report in a Dynamic Report with a campus filter only.  The Dynamic Report times out before loading and being able to select the filter. Tried recreating the Dynamic Report after the DV is persisted and still timed out.

**Expected behavior:**

To run

**Actual behavior:**

Page Times out

### Versions
* **Rock Version:** 8.4
* **Client Culture Setting:** Azure hosted

**Comment by karenn-ccbc** [comment]
Created a complex dataview based on other dataviews. (Cannot reproduce the complex dataview on Demo.) Had to increase timeout to 8 min for it to run. Set it to Persisted for a day 1440 minutes. It now loads quickly as well as the report built off of it. I reference that report in a Dynamic Report with a campus filter only. The Dynamic Report times out before loading and being able to select the filter. 
Tried recreating the Dynamic Report after the DV is persisted and still timed out.

V 8.4 hosted in Azure

**Comment by nairdo** [comment]
This is a known situation when attempting to use a long running Data View in a Dynamic Report.  It's really not possible (supported) to use a **long running** data view in a dynamic report -- since the Dynamic Report will attempt to load the data view, and attempting to configure Dynamic Report block  will also take as long as the data view takes to run... but of course it will time out before you can configure it.

**Comment by cabal95** [comment]
@nairdo, wouldn't the fact that the Data View is persisted (cached) mean that shouldn't happen though?  I thought that was sort of the whole point to allowing them to be persisted - to improve performance for long-running Data Views.

Or is there something special about the Dynamic Report block that makes it unable to used the cached version of the Data View?

**Comment by jonedmiston** [comment]
This has been fixed in v10.
