### ISSUE TITLE
Sticky headers on grid block do not scroll horizontally

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#3420]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Scrolling horizontally while sticky grid headers are showing does not scroll the headers.

![image](https://user-images.githubusercontent.com/18447084/48438463-a3b55900-e749-11e8-9c52-546b05cccb5f.png)

### Steps to Reproduce
1. Go to the Batches screen
1. Turn on sticky headers on the block settings
1. Reduce the width of the browser window until the data is cut off on the right
1. Scroll to the bottom of the grid
1. Scroll the grid to the right

**Expected behavior:**

The headers scroll along with the grid.

**Actual behavior:**

The headers do not change and become out of sync with the data.  Scrolling the page vertically updates the headers so they display properly.

### Versions
* **Rock Version:** Rock McKinley 8.4 (1.8.4.40)
* **Client Culture Setting:** en-US

**Comment by garrettjohnson** [comment]
Added horizontal scrolling with 1e8aef2

**Comment by megilee** [comment]
This bug appears to have been fixed per comment above. Cannot replicate.
