### ISSUE TITLE
[EN] Attributes on Connection Requests

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#3421]
# Feature Request
**Describe the Feature Request**
I would like to be able to use Attributes on Connection Requests and have them neatly displayed and editable.  My use case is for storing information related to Follow-up requests from guest families.  It can be stored as person attributes but then requires additional clicks to find.

**Describe Preferred Solution**
I would prefer to be able to add attributes and have them show up in the Connection Request Detail block and be editable.  They should also be accessible via lava particularly within related workflows.

**Describe Alternatives**
The Entity Attribute Value block can support this but it is not positioned well and requires two edit buttons.

**Providing Code**
I will provide code if feature request is approved: working on it, so hopefully.

**Comment by edmistj** [comment]
We're fine with this as a feature.

**Comment by nairdo** [comment]
See also https://github.com/SparkDevNetwork/Rock/commit/a39741bc8c34aae39cc1af8eb03e542d6e8b9087 which was a re-implementation but using our Attribute Editor described in our[ draft Developer 303 guide](https://community.rockrms.com/Developer/draft303).
