### ISSUE TITLE
Pledge 'Payment Schedule' shows blank on Pledge List if no 'Date Range' entered

### ISSUE THREAD

**Issue by atorrance** [SparkDevNetwork/Rock#3423]
### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

When adding Pledges, If a 'Payment Schedule' is added to the Pledge Detail block _and_ no Date Range is added, the 'Payment Schedule' will not show on the Pledge List block (either in the Pledge page or in a person's profile). The user has to open the pledge detail to see the 'Payment Schedule'. 

![<a href="https://user-images.githubusercontent.com/34725020/48490478-8b9a1400-e7f3-11e8-867d-02832ae34534.gif">https://user-images.githubusercontent.com/34725020/48490478-8b9a1400-e7f3-11e8-867d-02832ae34534.gif</a> pledges]()

### Steps to Reproduce ###

1. Go to [[http://prealpha.rocksolidchurchdemo.com/page/159?pledgeId=0](http://prealpha.rocksolidchurchdemo.com/page/159?pledgeId=0) ]() and add a brand new pledge, leave the Date Range blank but add a Payment Schedule of any kind. 
1. Click Save and return to the Pledge List.
1. You will see the the Payment Schedule shows blank on this list even though one was entered. 

**Expected behavior:**

The Payment Schedule should show on the Pledge List even without a Date Range added.

**Actual behavior:**

If a Payment Schedule is added without a Date Range, the Payment Schedule does not show on the Pledge List. 

### Versions ###

* **Rock Version:** [8.4 & 9.0]
* **Client Culture Setting:** [en-US]

**Comment by jsw-austin** [comment]
confirmed in Demo site
