### ISSUE TITLE
Copy function on Calendar Event Occurrences not functioning properly

### ISSUE THREAD

**Issue by megilee** [SparkDevNetwork/Rock#3427]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
The copy function on Calendar Event Occurrences is not functioning properly (it has in previous versions of Rock).

### Steps to Reproduce
On the Rock Solid Church Demo site:

1. Go to 'Tools'
1. Click on 'Calendar'
1. Click on 'Public'
1. Click on 'Rock Solid Finances Class'
1. Under 'Event Occurrences' click 'Copy' icon of existing all-campus event.
1. Blank event occurrence opens up

**Expected behavior:**

When I click the copy icon I expect an Add Event Occurrence page with all the fields pre-filled with the same information as the event occurrence that was copied (i.e. Campus/Location/Contact/Schedule/Occurrence Note). This was happening properly in previous versions of Rock

**Actual behavior:**

After clicking the 'Copy' button the Add Event Occurrence page is blank.

### Versions
* **Rock Version:** [Rock McKinley 8.4 (1.8.4.40)]
* **Client Culture Setting:** [en-US]
* [RockDiagnostics-OrchardHillRock.txt ](https://github.com/SparkDevNetwork/Rock/files/2582968/RockDiagnostics-OrchardHillRock.txt)

**Comment by shivambareria** [comment]
Fixed in https://github.com/SparkDevNetwork/Rock/commit/98ab466.
