### ISSUE TITLE
Cannot resize images to 4K resolution

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3430]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When trying to use the ImageResizer to resize an image to a 4K resolution (3,840 x 2,160) I get an error. This is due to a web.config setting which limits resized images to 3,600 x 3,600 max.

Since having devices (TVs and monitors) that are 4K resolution is becoming normal, I think it would be wise to support resizing images to that size.

Suggested fix is up the limits to 4,000 x 4,000.

### Steps to Reproduce

1. Go to `http://rock.rocksolidchurchdemo.com/GetImage.ashx?Guid=3839721c-856d-42e4-bdc3-8dfc11b93fe9&w=3840&scale=both`
2. See broken image link.

**Expected behavior:**

I think we should be able to resize to 4K resolutions.

**Actual behavior:**

Error.

### Versions

* **Rock Version:** 8.4
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
We're fine with upping the limit

**Comment by cabal95** [comment]
I'm happy to write a PR for this - but I honestly have no idea how to modify the web.config (other than opening it, reading it, modifying it with regex and saving it, which I'm guessing is the wrong way). Is there a previous commit you could point me at that I could use as a reference?

**Comment by edmistj** [comment]
If you submit the PR with the web.config change we'll make the transform when we do the release.

**Comment by nairdo** [comment]
Right. Daniel, you don't need to do anything special. All you need to do is edit the config and commit it like a normal change.

**Comment by cabal95** [comment]
Sorry for the delay on this, stupid holidays. 😆 Working on it now.
