### ISSUE TITLE
Attendance Summary Email sending old or blank data after attendance is entered

### ISSUE THREAD

**Issue by hillsideassembly** [SparkDevNetwork/Rock#3432]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers ](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
After entering attendance on the "Group Attendance Detail" block (and having previously turned on the Summary Email under the block settings), the email that is sent out contains old or blank data.  It seems like Rock is sending out the email too early before the new data is fully saved.  If you are creating a new attendance occurrence, it will send an email with blank data.  If you are editing a previously saved attendance occurrence, it will send an email with the previous data.

### Steps to Reproduce
1. Create a group where you are the group leader and you have other members.
1. Turn on the summary email setting under the "Group Attendance Detail" block for the Group Leader.
1. Click Attendance and add an Attendance Occurrence and mark some people present.  Click Save.
1. Check your email.

**Expected behavior:**

The email should list the people who you marked as present, along with any notes you put.

**Actual behavior:**

The email contains blank or previous data.

### Versions
* **Rock Version:** Rock McKinley 8.4 (1.8.4.40)
* **Client Culture Setting:** en-US

**Comment by jrockman13** [comment]
I believe this only happens if the block is on the public site. In my testing, the email works fine if attendance is entered on the internal site.

![external-attendance](https://user-images.githubusercontent.com/22159658/48632405-6f7aac00-e986-11e8-80b5-b494f5686e0b.JPG)
![internal-attendance](https://user-images.githubusercontent.com/22159658/48632406-6f7aac00-e986-11e8-995c-8c48806e2c9c.JPG)

**Comment by hillsideassembly** [comment]
I just entered attendance on the internal site and received a blank email.  It did not seem to work any differently from the external site for me.

**Comment by jrockman13** [comment]
I can confirm that this issue occurs on the public and internal sites with different group types HOWEVER, it does not ALWAYS occur. Sometimes the emails are correct. I haven't detected a pattern as to why it will occasionally work. And it's not one group vs another group. sometimes it works for a group but the next time it will not work for that same group.

**Comment by MicahO** [comment]
I can confirm we're seeing the same behavior on 8.5-en, except that I've never actually seen it work. I've only ever gotten blank emails.

**Comment by nairdo** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/5ba8ae96ca5f68df2e54a238397faa7722236005.
