### ISSUE TITLE
'LastAttendedOfGroupType' lava filter not working in 8.x

### ISSUE THREAD

**Issue by JesseM-PC** [SparkDevNetwork/Rock#3434]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
The 'LastAttendedOfGroupType' lava filter is not working any more. It throws an exception that seems to indicate it is not looking at the new AttendanceOccurrence entity/table, but the old Attendance entity/table.

### Steps to Reproduce
1. Attempt to use the filter {% assign lastAttended = CurrentPerson |LastAttendedGroupOfType:"25" %}
1. An error will be displayed: _Liquid error: A specified Include path is not valid. The EntityType 'Rock.Data.Attendance' does not declare a navigation property with the name 'Group'. Last attended '' on_

**Expected behavior:**

The last attendance date will be displayed of the specified group type.

**Actual behavior:**

The error is displayed instead.

### Versions
* **Rock Version:** 8.3, 8.4
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
The Queryable had an include of "Group" which is no longer valid. Ran some speed tests with and with out includes and best performance is without one.

No includes 76ms
"Occurrence" 165ms
"Occurrence.Group" 275ms

Also did some minor refactoring of RockFilters.LastAttendedGroupOfType().
