### ISSUE TITLE
Allow Fundraising Donations past Trip End Date

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3438]
# Feature Request
**Describe the Feature Request**

When we do mission trips, we sometimes have people want to donate to the participant after the trip has ended. This happens for various reasons - but we've been asked to find a way to accommodate this.

**Describe Preferred Solution**

A new Group Attribute for Fundraising group types of `Allow Donations Until` which would be a Date attribute. If blank, the current behavior would be used. If non-blank, then it would be used as the cutoff date for contributions rather than the trip end date. This would allow for churches to cutoff donations either _before_ a trip or _after_ a trip depending on their own culture.

**Describe Alternatives**

A simpler, but less configurable option, would be a `Allow Post-dated Contributions` option to the Fundraising Donation Entry block that would simply disable the date check and rely entirely on the `Active` flag for the group.

**Providing Code**
I will provide code if feature request is approved: **Yes**

**Comment by edmistj** [comment]
Sounds good, though I would say if you add 'Allow Donations Until' that it becomes the only factor for determining when to cut off donations. If it doesn't exist perhaps it is allowed indefinitely. A migration could set this new field to the current logics date.

**Comment by karenn-ccbc** [comment]
Yes Please! Needed now.

**Comment by karenn-ccbc** [comment]
Could it be based on Active Status of the group instead of a date field? What is the work around for this in the meantime? Change the date of the trip?

**Comment by cabal95** [comment]
Yes, the only current workaround is to extend the trip dates.

**Comment by cabal95** [comment]
@edmistj I've been thinking about this and wanted to run one slight change past you before I start working on it. Above you had said:

> ... if you add 'Allow Donations Until' that it becomes the only factor for determining when to cut off donations. If it doesn't exist perhaps it is allowed indefinitely.

I think if we are going this route it would be best to either 1) make the field required so people don't accidentally leave it blank not realizing they need to fill it in; or 2) go with it being optional but instead of that meaning "forever" it means "until the trip ends". There are a lot of attributes to fill in with fundraising groups so it would be easy to miss if it's not required.

This third option is of course what you said above. I don't have strong feelings either way, I'm just trying to think from the side of "what is the most common scenario" when setting up a fundraising group. I think that most common scenario would be that once the trip/event/whatever is done, no more money comes in so that they can "close the books" as it were. But maybe that is not actually the case for most churches.

**Comment by jeremyhoff** [comment]
> 1) make the field required so people don't accidentally leave it blank not realizing they need to fill it in
FWIW I consider this to be the preferred option.

**Comment by edmistj** [comment]
I'm fine with making it required. Having it based on the trip date seems to make it difficult to infer the logic. I do think we have a lot of required fields already on fundraising groups, but this seems to be the best option.

**Comment by cabal95** [comment]
@jonedmiston Okay sooooo... sorry to keep revisiting this. :) I just started writing the migration for this, and realized that the `Opportunity Date Range` is not required - I thought it was. So for the migration I may not have a valid date value to take and stuff into the new _required_ `Allow Donations Until` attribute. So I think we have three options on that front:

1. Make the `Allow Donations Until` attribute not-required, and go back to the idea of it being an optional override of the Opportunity Date Range.
2. Go with the currently agreed to plan, but for the migration have it stuff `12/31/9999` into the `Allow Donations Until` if there is no Opportunity Date Range _End Date_ value set.
3. The attribute can be marked required but left blank, meaning anybody who first tries to edit an existing fundraising opportunity would be required to fill in the value - and have the code that enforces the value assume DateTime.Max if there is no value.

**Comment by jonedmiston** [comment]
I'd be ok with option #2, but we could limit it to 12/31/2025.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
