### ISSUE TITLE
Error When Exporting Filter Group Data

### ISSUE THREAD

**Issue by matthewalanwhite** [SparkDevNetwork/Rock#3443]
### Prerequisites

* [X] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
After sorting a grid on a group, you receive an error when trying to export the data.

### Steps to Reproduce

1. Go to any group
2. Set a filter (we did active)
3. Click on a column with a member attribute to sort the grid
4. Click on the export icon
5. See error

**Expected behavior:**

To dowload an export of the group data

**Actual behavior:**

Receive an "Server Error in '/' Application" error

### Versions

* **Rock Version:** [Rock McKinley 9.0 (1.9.0.7)]
* **Client Culture Setting:** [en-US]

![image](https://user-images.githubusercontent.com/24526905/49025609-0ce59500-f16a-11e8-8ce5-2e65dc74c026.png)

**Comment by ethan-sparkdevnetwork** [comment]
Verified issue in v9.0.7. Does not occur in v8.*
