### ISSUE TITLE
[EN] Reprint Check-In Label Using Manager Override

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#3444]
# Feature Request
**Describe the Feature Request**
Need the ability to reprint check-in labels for lost labels and printer jams. Currently available solutions generate a new security code which doesn't match original which is problematic if parent label is lost.  #3006 also addresses this issue in a different way (which I would like to see implemented as well).

**Describe Preferred Solution**
Would like the ability to use the check-in manager Override option to re-check-in and use the current security code.  This would handle jams, lost parent labels and also kids checked-in to a wrong room that are changed using override.  The issue with this solution is that it prints all labels even if only one is needed, but the benefit is that it doesn't require an additional manager station or changing applications.  #3006 works better if you can have a separate check-in manager station available and are trying to reprint only one label.  But #3006 doesn't handle all the Rock check-in printing options the same way Unattended Check-In does.

This proposed change would add an attribute on the Save Attendance workflow action (something like "Reprint on Override") which, when enabled and the Check-In Manager login is used to override, would query the database for the security code used on the same active schedule the same day and re-use that security code if present, otherwise generate a new code.

**Describe Alternatives**

#3006 is a great alternative if it were available.

Note that this is not a major change to the Save Attendance action.  It's about 15 lines of code.  Alternatively, it could be an additional action like "Save Attendance With Reprint" if that is preferred since check-in is central to everyone.  Both actions could remain available.  It could become a replacement later.

**Providing Code**
I will provide code if feature request is approved: Yes

**Comment by edmistj** [comment]
Seems like we'd need to discuss more edge cases. Like when 're-checking in' what if different rooms/times/family members were selected? Should the old attendance records be deleted? But that could be problematic if the 're-check in' was meant to add a schedule/location and not substitute. How would you see that working?

Seems like it might be best to be able to search for the individual then re-create the labels. Much like it sounds like #3006 does.

**Comment by bobrufenacht** [comment]
Override already allows people to be put into two rooms for the same time schedule and actually would generate two different security codes for them in the process.  It is treated as an "add" in the current implementation. This would not change the existing functionality, just keep the security code consistent for the current day (whether doing something smart or dumb with the override feature).  But I agree that there are some issues that could be cleaner.  Override is a forceful way of doing things.

The check-in manager reprint I have and the one Trey is proposing have other issues when it comes to printing devices and printing configurations.  This one would support the core Rock printing options and the client application.

I'm ok if this is a "no." Trying to figure out how to fill the gap.

**Comment by nairdo** [comment]
@bobrufenacht I didn't realize this feature request was also open here as an issue... v9 will have a label reprint feature which was mostly implemented (here https://github.com/sparkdevnetwork/rock/commit/cb632a633e053d7fdaac88838e89956bce858beb) and patched (here https://github.com/sparkdevnetwork/rock/commit/3973bd4dc365782ee601dbd6e31a226c67b7f39e).  There is some beta documentation the feature if you want to review it to see if it satisfies what you were looking for: https://community.rockrms.com/documentation/book/10/163/content#reprinting

**Comment by bobrufenacht** [comment]
The new reprint will suffice.  It’s fine to closed 3444.
