### ISSUE TITLE
Registration Ignoring 12th Grade Selection

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#3445]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When a registration requires the Person Field of Grade  and 12th Grade is selected (login required), it is not updated on the person record as it is with other grade choices and it is not shown in the Registration Registrants fields.

### Steps to Reproduce
1. Create an Event Registration requiring login and add Person Field -> Grade to the form as required.
1. Create an instance of the registration.
1. Create a URL slug for the registration (probably not required but easier).
1. Go to the slug URL.
1. Register a person (I used an existing person with no current grade) and select 12th grade.
1. The Registrants tab will have blank for the grade.
1. The person's profile will still show blank for the grade.

Other grades chosen will update the person profile and the registrant attribute.

**Expected behavior:**

Update the profile and save the selection on the registration.

**Actual behavior:**

It behaves as if there was no selection even though it was required.

### Versions
* **Rock Version:** 8.4 but also tested on demo and prealpha and failed on all.
* **Client Culture Setting:** Azure

**Comment by ethan-sparkdevnetwork** [comment]
Corrected GradePicker parse logic on the RegistrationEntry block.
