### ISSUE TITLE
Rock Reflection should ignore internal types

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3447]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Rock Type Reflection (for example, determining available FieldTypes and other things) will include private and internal classes. I think this would be considered a bug since Rock should not be trying to instantiate private nor internal classes from plugins.

Specifically, here: https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Utility/Reflection.cs#L85, it is using `assembly.GetTypes()` to retrieve the types in the assembly. This method includes private and internal types. Instead, I think it should be using `assembly.GetExportedTypes()` so that only public types are returned.

Discussion on difference here: https://stackoverflow.com/questions/7712223/assembly-gettypes-why-use-this-if-getexportedtypes-is-available

This came up when I was trying to create a custom Block setting attribute which requires me to create a Field Type. This field type doesn't make sense to make available to the user but I was unable to keep it hidden from the user even if I marked it `internal`.

### Steps to Reproduce

1. Create a sublcass of FieldType in a plugin assembly and mark the type as `internal`.
2. Reboot Rock, notice the field type shows up in the database.

### Possible Concerns

There is a slight change this could cause issues with existing plugins if the classes had been created private by accident. Not sure if there is an easy way to scan all plugin assemblies to see if this would impact them?

A different method to achieve the same would be a new class attribute `IgnoreWhenReflectingAttribute` that could be applied to classes in our plugins that we want the Rock reflection system to ignore.

### Versions

* **Rock Version:** 8.x
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@cabal95 Interesting. Added it to the internal discussion list

**Comment by cabal95** [comment]
As I'm working on different parts of a plugin (migrations) I'm thinking the second option of a new "ignore me" attribute might be better. Since classes are created private by default, especially migrations, might be likely to have not been updated to be public.

**Comment by edmistj** [comment]
We met to discuss dev topics. We're going to not go forward with this as it's benefit to the community is very small and we're not sure we'd have unintended consequences.
