### ISSUE TITLE
JavaScript error with Group Member HTML Attribute, cannot add/change content in field

### ISSUE THREAD

**Issue by bengoshow** [SparkDevNetwork/Rock#3448]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

I've created a Group Member Attribute of "HTML" Type. When I try to edit a Member of that Group Type, I get a JavaScript console error. The HTML field does not display the WYSIWYG toolbar, and I cannot save any changes to the contents of the field.

The error says `Uncaught ReferenceError: RockFileBrowser is not defined`

### Steps to Reproduce

1. Under General -> Group Types, edit any Group Type (I chose "Small Groups")
2. Add a Member Attribute of Type HTML. Leave the default settings.
3. Edit a Member of any Small Group
4. Verify that the HTML toolbar does not appear
5. Enter some text in the HTML field and click "Save"
6. Edit the Member again and verify that your changes do not appear.

I followed these steps on the Rock Demo site

### Versions

* **Rock Version:** 8.5
* **Client Culture Setting:** en-US

**Comment by bengoshow** [comment]
@garrettjohnson I was able to reproduce this on the current demo site.

**Comment by bengoshow** [comment]
@ethan-sparkdevnetwork any idea why this is happening? There is text and HTML in my custom member attribute field, so at one point it was working.

**Comment by ethan-sparkdevnetwork** [comment]
HtmlEditor has a dependency on being visible when it is created. The GroupMemberDetail block created the edit controls before making them visible. Corrected the order of operations.
