### ISSUE TITLE
Registratio2n Email Fallback

### ISSUE THREAD

**Issue by rutledgek** [SparkDevNetwork/Rock#3453]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
For reasons, a registration has a separate email field that is separate from the person who registered current email address.  This usually populates at the time of registration or is filled in as a part of the registration.

I suggest a fallback that if this field is left blank it tries to send an email to the email address attached to that person’a record.

The problem is made worse because even after filling in the email by removing the person and adding them again, the registration doesn’t get caught up in future registration reminder job runs.

### Steps to Reproduce
Create a registration
Leave email address blank in registration process.
Reminder and confirmation emails are not sent
Clear person and refresh and an email address is filled in if we have it.
Trigger email reminder job after filling in email and reminder email not sent to new email addresses.

### Versions
Rock Version: Rock McKinley 8.3 (1.8.3.36)

Client Culture Setting: en-US

**Comment by jonedmiston** [comment]
Please add to the Ideas board for community voting on this enhancement.
