### ISSUE TITLE
Schedule Exclusion does not work when attempting to set on Schedule Category

### ISSUE THREAD

**Issue by jgrabrian** [SparkDevNetwork/Rock#3461]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
Schedule exclusions cannot be created on the schedule category or the exclusions propogate to the schedules beneath.

### Steps to Reproduce
1. Go to Admin Tools > Check-In > Schedules
1. Select the "Service Times" Or create a new schedule category
1. click the "+" to add a new schedule exclusion
1. Enter the require information
1. Click the Save button

**Expected behavior:**

The schedule exclusion modal should save and close. The exclusion should be set for all schedules under the category.

**Actual behavior:**

Nothing happens. The exclusion is not saved. The modal does not close.

### Versions
* **Rock Version:** [8.4]
* **Client Culture Setting:** [EN-US]

**Comment by nairdo** [comment]
I'm sorry. This expectation is not correct. Schedule settings are not inherited by schedules based on the category folder they reside in.
