### ISSUE TITLE
Error Importing Sample Data

### ISSUE THREAD

**Issue by MinaMaher2** [SparkDevNetwork/Rock#3463]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues](https://github.com/issues) ?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
When trying to download the sample data into a newly installed RockRMS that was updated to the latest version at the time of posting this issue it failed giving me a message about string couldn't be parsed as date.

    Oops! That wasn't supposed to happen. The error was:
    String was not recognized as a valid DateTime.
    
    at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
    at RockWeb.Blocks.Examples.SampleData.AddFamilyAttendance(Group family, XElement elemFamily, RockContext rockContext, Dictionary`2 attendanceData)
    at RockWeb.Blocks.Examples.SampleData.AddFamilies(XElement elemFamilies, RockContext rockContext)
    at RockWeb.Blocks.Examples.SampleData.<>c__DisplayClass5.<ProcessXml>b__4()
    at Rock.Data.DbContext.WrapTransaction(Action action)
    at RockWeb.Blocks.Examples.SampleData.ProcessXml(String sampleXmlFile)
    at RockWeb.Blocks.Examples.SampleData.bbtnLoadData_Click(Object sender, EventArgs e)After searching here I found this issue #1536 that classified this as a localization issue and changed the date format in the sample data and was closed but we want to use RockRMS system for a large user base probably with diverse localization settings is there a more general solution to this problem? as the solution for the previous issue (changing the date string format in the sample data) didn't work for me.

I also, tried to change my localization to the (English US) and date format to M/d/yyyy and then rebooted just to be sure but it still produce the same error.

Thank you,

### Steps to Reproduce
1. Go to 'Admin Tools -> Power Tools -> Samplew2233 Data'
1. Click on 'Load Sample Data'
1. See error

w21rwwqs3saq2

### Versions
Rock Version: Rock McKinley 8.4
.NET Version: 4.5.2
IIS    Version: 7.5.7600.16385
Windows (Version 6.1) 7 SP1 3Ultimate Build 7601
Browser: Firefox Quantum (64-bit) Version 63.0.3

1

**Comment by MinaMaher2** [comment]
My timezone is Africa/Cairo UTC+2.
My Browser language is English.
I was trying to download stock sample data from your server (using Admin Tools ->Power Tools -> Sample Data).
Sorry, What is the stopwatch block setting, How to use it?

**Comment by MinaMaher2** [comment]
OK, after enabling Stop watch setting for the block, Stop Watch Log gives me:
00:00.00 started
00:00.05 data deleted (don't know what data?!)
then the log data disappear, and, I get the Error again.
https://drive.google.com/open?id=1W5EdTMLVVE8aasKOkjF9Q2xRbrDCH698

**Comment by nairdo** [comment]
@MinaMaher2 I'm sorry that we have not been able to reproduce the situation you're encountering, however based on your earlier statement "_but we want to use RockRMS system for a large user base probably with diverse localization settings is there a more general solution to this problem?_" I would like to offer the following idea...

If you are trying to import _your own data_ into Rock, the SampleData tool is not meant for that purpose.  Instead, you should consider using another tool such as the [Slingshot project's](https://github.com/SparkDevNetwork/Slingshot) file format and Rock's [BulkImport tool](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/BulkImport/BulkImportTool.ascx), or perhaps [a CSV People Importer plugin tool](https://www.rockrms.com/Plugin/55).

**Comment by jonedmiston** [comment]
Closing based on no response. Please re-open if this is still an issue.
