### ISSUE TITLE
Error Editing Reply to Person Notes

### ISSUE THREAD

**Issue by matthewalanwhite** [SparkDevNetwork/Rock#3468]
### Prerequisites
* [X] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When editing a reply to a person note, it doesn't allow you to do so. It also prevents it from being visible.

### Steps to Reproduce

1. Go to a person profile and add a note. Then add a reply to that note.
2. Click on edit to edit the reply. 
3. The note is no longer visible, and doesn't allow you to edit the reply.

**Expected behavior:**

We expect to be able to edit the reply to the note

**Actual behavior:**

The reply to the note is no longer visible and we can't edit the reply.

https://drive.google.com/file/d/1WiJMtVoILoHtyjh95MmbMa4QCBMtrn3y/view?usp=sharing

### Versions

* **Rock Version:** [Rock McKinley 9.0 (1.9.0.7)]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Fixed via 490aac7389cbfcbb8cc6b14bae92c671929d507b
