### ISSUE TITLE
Contribution Statement Error

### ISSUE THREAD

**Issue by traveljen** [SparkDevNetwork/Rock#3469]
-Cannot recreate issue on Rock Demo
-Rock Version: Rock McKinley 8.4 (1.8.4.40)
-Client Culture Setting: en-US
-[RockDiagnostics-RTTN-ROCK-WEB.txt ](https://github.com/SparkDevNetwork/Rock/files/2663756/RockDiagnostics-RTTN-ROCK-WEB.txt)
-No results on cursory search.
-cleared cache and restarted rock
-cleared browser cache, cookies, and history
-tried in different browser
-tried with different security settings/logins

ISSUE: 

### Description
Cannot generate, print, or email individual contribution statements from Rock internal profile page.

### Steps to Reproduce
1. Go to 'Individual's Profile'
1. Click on 'Contributions Tab'
1. Scroll down to 'Available Statements and 2018YTD'
1. I've tried this under Administrator role and Financial Administrator role and three separate user accounts and two different computers and two different browsers with the same result listed below.

**Expected behavior:**

When you go to an individual's profile, and select Contributions, and select any tab under Available Contributions, it should generate their giving statement for the year selected

**Actual behavior:**

When we click on the button for the individual's contribution statement, it produces the person's statement who is logged in instead. (I'm logged in as myself, I go to someone else's profile/contributions, I select "2018YTD," it generates my contribution statement, not the person's profile whom I am viewing)

### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)? 
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;1104683400778752">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;1104683400778754">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;1104683400778756">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;1104683400778758">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;1104683400778760">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;1104683400778762">image.png</a>

**Comment by mikejed** [comment]
Please check the block settings for that block:
1) Log in using an account belonging to the `RSR - Rock Administration` security group
2) Go to another person's 2018YTD Contribution Statement page
3) Hover your mouse at the bottom of the browser window so the Admin Toolbar appears, then click the first button that looks like four boxes:
![image](https://user-images.githubusercontent.com/6932047/49746189-e6d9ed80-fc5d-11e8-9424-797edc9b0262.png)
4) A fly-out menu appears at the top left of the contribution statement block (it looks like an arrow in a circle pointing right). Hover over that, then click the "Block Settings" button (it looks like a cog):
![image](https://user-images.githubusercontent.com/6932047/49746282-1d176d00-fc5e-11e8-81a8-8777cacab99d.png)
5) Scroll to the bottom of the settings and ensure that "Allow Person Querystring" is set to "Yes", then click Save
![image](https://user-images.githubusercontent.com/6932047/49746350-3b7d6880-fc5e-11e8-96e0-641ee7b75981.png)

Please let us know whether this problem continues once this setting is verified. If necessary, you might set it to "No", save, refresh, then set it to "Yes", save and refresh again, just to make sure.

**Comment by traveljen** [comment]
Thank you SOOOO much! This worked perfectly!

Blessings,

Jennifer Keylon
jkeylon@gmail.com
