### ISSUE TITLE
Cannot check if Schedule is active in Lava anymore

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3471]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
> I'm marking this as a bug because it's existing functionality that seems like it's going to be removed in the future. Core team feel free to re-classify.

The title is slightly misleading. We can still do it at the moment, but the `IsScheduleActive` and `IsCheckinActive` properties are marked deprecated which I read as "will eventually be removed". Because they were replaced with method calls, Lava will lose the ability to test if a schedule is active once those properties go away.

This is a feature we use now so we can display certain information during service and different information during the week. For example, displaying the live stream during scheduled services and displaying a "service times" slide otherwise.

I'm not sure what the best solution would be. The two options I can think of now would be:

1) Change the deprecation notice on the two properties to say that they should only be used in Lava and not in C# code.
2) Add a Lava filter of some kind to check these two states of a Schedule entity.
2.5) Perhaps add a new general Lava filter that lets us call "marked safe" methods on objects.  example:

```
public class Schedule : Model<Schedule>
{
    ...
    [LavaSafeMethod]
    public bool WasScheduleActive( DateTime when )
    { ... }
}
```

```
{% assign now = 'Now' | DateAdd:0 %}
{% assign isActive = schedule | CallMethod:'WasScheduleActive',now %}
{% if isActive == true %}
    ...
{% endif %}
```

If option 2.5 is chosen, I would be happy to work on some code for that. Sounds like a fun project.

### Versions
* **Rock Version:** 8.x
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
We recently added this shortcode to v9. Would this fill the need? It's on the pre-alpha server if you want to play with it.

![image](https://user-images.githubusercontent.com/548178/56328499-1e890280-6134-11e9-9bff-b2ae94c5a0a3.png)

**Comment by cabal95** [comment]
I think so.... If I recall they execute in their own scope so I can't just do:
```
{[ scheduledcontent scheduleid:'15' ]}
    {% assign isScheduleActive = true %}
{[ endscheduledcontent ]}
```

But it should work if I did it the following way, correct?

```
{%- capture isScheduleActive -%}
{[- scheduledcontent scheduleid:'15' -]}true{[- endscheduledcontent -]}
{%- endcapture -%}
```

(I use that variable a number of times repeatedly, so would prefer to not have the entire shortcode duplicated throughout the lava).  If that should work to assign the variable, then yes that shortcode should do what we need.

**Comment by edmistj** [comment]
Yes, the capture should work the way you have it. Except I'm not sure of the dashes would be supported. You might need to put it all in one line.

**Comment by cabal95** [comment]
I'm not sure I ever noticed this was closed. I think I was assuming what you posted as a workaround was a temporary one, not a permanent way to recommend that people do this from now on.

So are we saying that anytime somebody in Lava wants to check if a Schedule is active, when they already have the Schedule object loaded, they need to use this shortcode which loads the schedule a second time?  It's also not a very user friendly way to do something.

**Comment by JimMichael** [comment]
I agree that losing access to this property via Lava with only this shortcode as a hacky workaround will be a problem for us. We rely on checking if schedules are active via Lava in several key places in our environment (live stream countdown on homepage, Roku/ATV apps, mobile app, etc). Is there a _technical_ reason this perfectly useful property must be deprecated, or is it just a "design stance" thing?

**Comment by jonedmiston** [comment]
I looked back into why this was deprecated. It was for performance. Determining the `IsScheduleActive` and `IsCheckInActive` is expensive. In places where the schedule was being serialized this would add overhead.

If you'd like we could add the two new Lava filters that take a schedule then determine if they are active or check-in.

**Comment by JimMichael** [comment]
Lava filters for this would be awesome!

**Comment by jonedmiston** [comment]
Would two for `IsScheduleActive` and `IsCheckInActive` cover it?

**Comment by cabal95** [comment]
I'm fine with the two filters, but wouldn't just marking the property with `[JsonIgnore]` work too?

**Comment by cabal95** [comment]
Also, thanks for looking into this again even though it's old!

**Comment by jonedmiston** [comment]
> I'm fine with the two filters, but wouldn't just marking the property with `[JsonIgnore]` work too?

Yeah, I'm not sure of all the reasoning since this was done a while ago.

**Comment by OnlyByGrace** [comment]
I'd like to contribute to the conversation here, if I could, as we just ran up against this. We were trying to use these functions in a digital signage context; to determine whether any schedules assigned to a screen were currently active. This required polling these functions pretty frequently (minimum of 4 schedules per screen x 10 screens, every 10 minutes). But it turned out to look very expensive to do in Rock. It took 2-3 seconds to check each schedule, so it could take 12+ seconds to check each screen. I didn't do any extensive performance testing on this, but opted for client side processing of the iCals instead to take the load off of Rock.

Just putting that out there.

**Comment by JimMichael** [comment]
@jonedmiston Is there still a plan to add these `IsScheduleActive`, etc Lava filters? With v12 around the corner I'm assuming the IsScheduleActive _property_ we've been relying on will finally go away, and lots of places we use it will break without a good solution (other than perhaps the shortcode mentioned above).

**Comment by nairdo** [comment]
@JimMichael Jon asked me to review this and, after some [investigating](https://github.com/SparkDevNetwork/Rock/commit/7af455e1e4baa595b964a50a3070c7c7b9bf35d8#diff-79b9e5d1a75dd183abd53ed32acbfcd3347307069e4c2b284f8907c12811df6dR180) and testing, it looks like we're going to be able to _remove_ the [Obsolete] and _add_ a [LavaInclude] from the Schedule's `IsScheduleActive` and `IsCheckInActive` properties since both of those are just simplified ways to call the underlying, non-obsoleted `WasScheduleActive` and `WasCheckInActive` methods without passing a 'now' datetime.

@JimMichael, @cabal95 and @OnlyByGrace  Can you send me your Lava so I can verify your particular usages?

**Comment by JimMichael** [comment]
Here's an example of where we're using isScheduleActive within a Lava Webhook.
```{%- assign IsLiveNow = false -%}
{%- schedule where:'CategoryId == "318"' -%}
    {%- for s in scheduleItems -%}
        {%- assign isSchedActive = s | Property:'IsScheduleActive' -%}
        {%- if isSchedActive == true and s.IsActive == true -%}
            {%- assign IsLiveNow = true -%}
        {%- endif -%}
    {%- endfor -%}
{%- endschedule -%}```

**Comment by cabal95** [comment]
Ours was the same. We used the above logic in a few places as a way to check if "any schedule in the category is currently active" then display X, otherwise display Y.

**Comment by gonemob** [comment]
Just to add to what @JimMichael stated, for the most part we've been able to use the `{[ scheduledcontent showwhen:'both' ]}` plugin.

That being said, there are few places where we need that `IsActive` bool outside of the shortcode's scope.  It looks like `{% capture %}` would work, but seems like there should be a better way.

Like Jimmy and Daniel's, here's an example where we use it for a countdown timer:
```
{%- schedule where:'CategoryId == "{{ category.Id }}" && IsActive == true' -%}   
    {%- for s in scheduleItems -%}
        {% assign nextStartDateTime = null %}
        {% assign nextStartDateTime = s.NextStartDateTime %}
        {% comment %} is the service live right now {% endcomment %}
        {%- assign isSchedActive = s | Property:'IsScheduleActive' -%}
        {%- if isSchedActive == true -%}
            {%- assign IsLiveNow = true -%}
            {% break %}
        {% elseif nextStartDateTime and nextStartDateTime != empty %}
            {% if nextServiceStartDateTime and nextServiceStartDateTime != empty %}
                {% comment %} compare the times {% endcomment %}
                {% assign timeDifference = nextServiceStartDateTime | DateDiff:nextStartDateTime, 's' %}
                {% if timeDifference < 0 %}
                    {% assign nextServiceStartDateTime = nextStartDateTime | Date:'yyyy-MM-dd HH:mm:ss' %}
                {% endif %}
            {% else %}
                {% assign nextServiceStartDateTime = nextStartDateTime | Date:'yyyy-MM-dd HH:mm:ss' %}
            {% endif %}
        {%- endif -%}
    {%- endfor -%}
{%- endschedule -%}
<script>
    var isLive = '{{ IsLiveNow }}';
    var nextServiceStartDateTime = '{{ nextServiceStartDateTime }}';
</script>
```

**Comment by nairdo** [comment]
@JimMichael  I verified your code will work and will also be able to be simplified (removing the `assign isSchedActive = s | Property:'IsScheduleActive'` unless you need it for something else) like so:

```
{%- schedule where:'CategoryId == "318"' -%}
    {%- for s in scheduleItems -%}
        {%- if s.IsScheduleActive == true and s.IsActive == true -%}
            {%- assign IsLiveNow = true -%}
        {%- endif -%}
    {%- endfor -%}
{%- endschedule -%}
```

**Comment by JimMichael** [comment]
Thanks, Nick! Just so I'm clear (because I don't understand some code jargon), is the whole premise of this thread now moot, and going forward we WILL be able to keep using IsScheduleActive property of a schedule?

**Comment by nairdo** [comment]
> ..going forward we WILL be able to keep using IsScheduleActive property of a schedule?

Yes, this will be the plan.

**Comment by cabal95** [comment]
I had been planning to add a new Lava filter to my lava additions plugin to help deal with this: `BBM_WasScheduleActive`. It would basically work just like the C# method. It would take a datetime parameter (or if not specified, default to "now") and return a boolean value indicating if the schedule was/will be active at the specified date time. A few examples:

```liquid
{% date = '2020-11-26 17:20:00' | AsDateTime %}
{% assign isActive = 30 | BBM_WasScheduleActive:date %}

{% assign isActive = '4d52f810-bee0-4533-b172-41d6104d9fea' | BBM_WasScheduleActive %}

{% assign group = 88 | GroupById %}
{% assign isActive = group.Schedule | BBM_WasScheduleActive:'2020-12-25 09:00:00' %}
```

Would that still be beneficial to have available?

**Comment by cabal95** [comment]
![image](https://i.pinimg.com/originals/be/3a/30/be3a30f2686c34c1366b2ad68bd11846.gif)

**Comment by JimMichael** [comment]
What Daniel said!
