### ISSUE TITLE
Merge from tag issue

### ISSUE THREAD

**Issue by JoshLeVeque** [SparkDevNetwork/Rock#3473]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Merge template from a tag links to the wrong person when selecting names

### Steps to Reproduce

1. Select People>Tags
2. Click on any tag
3. Check the boxes next to one or more names in the tag
4. Click Merge templates (bottom right corner of grid/table) 
![image](https://user-images.githubusercontent.com/383807/50597308-42b22380-0e64-11e9-821b-26d2e3fdf8e9.png)
5. Clicking "Show Data Rows" will either show values for people other than the ones you selected or you may see no rows (even though it shows you selected some rows). 
![image](https://user-images.githubusercontent.com/383807/50597427-a50b2400-0e64-11e9-8f59-c38d27a07d28.png)

**Expected behavior:**

It should show the names you selected, it seems to pull other people values.

**Actual behavior:**

A description of what actually happened.

### Versions

* **Rock Version:** [8.4, 8.5]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by nairdo** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/52894220c47872b45a21b32ab81fd59fd159e223
