### ISSUE TITLE
Prevent an synced group (archived) from causing a sync failure

### ISSUE THREAD

**Issue by tstephens17** [SparkDevNetwork/Rock#3475]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When you archive a synced group the group sync job fails.

### Steps to Reproduce

1. Setup a group with history enabled to be synced.
2. Archive it.
3. Run the group sync job.

**Expected behavior:**

My end goal is to not have the group sync fail. However that is prevented would be okay with me.

**Actual behavior:**

Group sync job fails

### Versions

* **Rock Version:** [Rock McKinley 8.3 (1.8.3.36)]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
We corrected the group sync job to ignore groups that have been archived.  This was done via 9bbef9f858c1eecf66dc80d866a4c11bef3b02ed for hotfix-1.8.6.
