### ISSUE TITLE
UserLogin PUT API Request with REST Key Returns Unathorized

### ISSUE THREAD

**Issue by OnlyByGrace** [SparkDevNetwork/Rock#3483]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
Making a PUT Request to the api/UserLogins/{id} endpoint with a REST Key always returns a 401 Unauthorized response, even when edit permissions have been given to the Key for that endpoint in Security->REST Controllers.

The same PUT body/request will work when using Cookie authentication with a Rock administrator account.

### Steps to Reproduce
1. Go to 'Admin Tools->Security->REST Keys' and create a new key
1. Go to 'Admin Tools->Security->Rest Controllers'
1. Click the Lock on the User Logins endpoint and add the new REST Key as an VIEW and EDIT user.
1. Make a GET request to the api/UserLogins (see attached postman file)
1. Copy one of the returned UserLogin objects
1. Make a PUT request to api/UserLogins/{id} with the copied UserLogin object id and body, with an Authorization-Token header with the proper REST Key
1. You'll get a 401 response

Additional Details

1. Go to 'Admin Tools->Security->User Accounts'
1. Click on the Person column link for the new REST Key
1. Assign the 'RSR - Rock Administration' role to the REST Key
1. Retry the same exact PUT request as step 6 as above
1. You'll get a 204 response, and the changes will have been made

**Expected behavior:**

A 204 response, with the UserLogin reflecting the changes, as when using Cookie authentication.

**Actual behavior:**

401 response.
[Rock UserLogin Put Bug.postman_collection.json.zip ](https://github.com/SparkDevNetwork/Rock/files/2692443/Rock.UserLogin.Put.Bug.postman_collection.json.zip)

### Versions
* **Rock Version:** 8.5.2
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
The user is given access to the UserLoginRestController but does not have access to the UserLogin Model, so an unauthorized error is returned. After adding the REST key to the UserLogin model an error does not occur.

**Comment by ethan-sparkdevnetwork** [comment]
Go to Security > Entity Administration and edit the security for Rock.Model.Userlogin.
