### ISSUE TITLE
ProcessPayments can incorrectly match transactions on a blank ScheduleId

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#3484]
### Description

This is a non-critical bug but logging here for discovery and possible fix. The code for [ProcessPayments](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/FinancialScheduledTransactionService.Partial.cs#L85) will pick the first available schedule (active or inactive) if a payment token is blank, then assign payments to that schedule.  99.9% of the time a FinancialScheduledTransaction always has a valid GatewayScheduleId and this behavior should not occur.  

I'm not sure the best fix since this is such an edge case.  Probably a IsNotNullOrWhitespace() call either on ProcessPayments.payment.GatewayScheduleId or GetByScheduleId.scheduleId.  

### Steps to Reproduce

1. Church changes giving systems
2. Verify giving schedules transferred in Rock
3. Request and wait for new GatewayScheduleIds
4. Notice that Rock is assigning transactions to an inactive schedule
5. Trace the code to FirstOrDefault returning the First or Default schedule

**Expected behavior:**

Rock should only match schedules by a valid GatewayScheduleId

**Actual behavior:**

Rock matches schedules on a blank string

### Versions

* **Rock Version:** 8.5
* **Client Culture Setting:** en-us

**Comment by dcs619** [comment]
To clarify this, ProcessPayments is being passed an empty string for the GatewayScheduleId parameter.  

ScheduledTransaction.GatewayScheduleId defaults to blank so when ProcessPayments executes the queryable filter, it returns the first available ScheduledTransaction without a GatewayScheduleId.

The best fix seems to be excluding blank GatewayScheduleIds from ProcessPayments.  Adding a constraint is also an option, but would limit the ScheduledTransaction feature's usability during transition and testing phases.

**Comment by ethan-sparkdevnetwork** [comment]
Added NULL and Blank checks to FinancialScheduledTransactionService.ProcessPayments() for the TransactionCode and GatewayScheduleId provided by the gateway. If that value is null or whitespace then it will not be used to get existing transactions.

We are kind of curious on how that kind of data is introduced.
