### ISSUE TITLE
Sorting First Attended / Last Attended

### ISSUE THREAD

**Issue by matthewalanwhite** [SparkDevNetwork/Rock#3491]
* [X] Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
* [X] Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [X] Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
The "First Attended" and "Last Attended" columns aren't able to be sorted by clicking on the label. This was previously available.

### Steps to Reproduce
1. Navigate to Group Viewer
1. Verify the Group Member List block has the "First Attended" and "Last Attended" columns visible in the block settings.
1. Click on the column heading for "First Attended" and "Last Attended". It does not sort as expected.

![](https://user-images.githubusercontent.com/24526905/50693412-dde1ff00-1004-11e9-9e89-c6e3707de1bc.png)

_(note: the screenshot accidentally has the wrong two columns circled.)_

### Versions
* **Rock Version:** [Rock McKinley 9.0 (1.9.0.9)]
* **Client Culture Setting:** [en-US]

**Comment by cabal95** [comment]
https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Groups/GroupMemberList.ascx#L74

(Note mentioning it used to support sorting, but that was removed due to performance issues)

**Comment by chrisfunk** [comment]
@cabal95  I noticed that, I am wondering if there could either be a block setting to allow sorting on those columns (give me the option to shoot myself in my foot kind of thing) or if there is a way to take an additional look at it to see if it could be given a second look.  I have had multiple members of our staff ask me about it since we have deployed 9.1

**Comment by JimMichael** [comment]
We too are really disappointed by this removal of a (for us) key feature. Our admins relied on it pretty heavily for some use cases.

**Comment by TheArkChurch** [comment]
Same, we utilize this feature heavily.
