### ISSUE TITLE
Contribution Statement Generator reduces size of text/elements on PDF when monitor scaling is raised

### ISSUE THREAD

**Issue by hillsideassembly** [SparkDevNetwork/Rock#3494]
### Description
The Contribution Statement Generator changes the look and sizing of PDFs when the Scale setting for your monitor is anything other than 100%.  The higher you raise the scale for your display settings, the smaller the text, logo, etc. are on the PDF the Statement Generator creates.  It doesn't matter what template is selected.

### Steps to Reproduce
1. Go to the Display Settings on your Windows 10 computer.  Under "Scale and layout" there is a box for "Change the size of text, apps, and other items".  Change it to 200% or higher.
1. Use the newest version of Statement Generator to create a statement.  The resulting PDF will display and print very small.  The text and logos are all shrunk down.
1. Compare to a PDF created when the scale is set to 100%, and you can see the difference, especially when the PDFs are printed out.

**Expected behavior:**

The text and graphics on the PDF should display and print the same size no matter what you set your monitor scale to.

**Actual behavior:**

The resulting PDF is dependent on the display settings of your monitor, and it affects the hard copy that you print, to the point that the elements become illegible.  For someone who is not aware of this issue, it could be very difficult to figure out how to make their statements print bigger.

### Versions
* **Rock Version:** 8.5
* **Client Culture Setting:** en-US In case it helps, I'm using Windows 10 Home Version 1809

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1109331799660515">contribution-statements.pdf</a>

**Comment by luke-b-taylor** [comment]
I confirm that rendered .pdf font size responds to windows font scaling percentage.

**Comment by jsw-austin** [comment]
This doesn't happen on a mac.

**Comment by JRichmond27** [comment]
Just pulled my hair out for a few hours trying to figure this one out. If this doesn't end up being fixed, it might be nice to at least include a note in somewhere in the Statement Generator application that lets people know that their display scaling should be set to 100%. Could save a lot of debugging time.

**Comment by nairdo** [comment]
@JRichmond27 and @hillsideassembly The issue does lay within the computer the statements are being generated on.  To help others avoid the frustration you went through we've updated the documentation with this note: https://community.rockrms.com/documentation/BookContent/15#usingthestatementgeneratorsoftware

![image](https://user-images.githubusercontent.com/383807/97931161-421d9900-1d2a-11eb-9149-c3ad3091aaa0.png)

Sorry about that.
