### ISSUE TITLE
Adding or editing a business causes exception on 8.5

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3497]
### Description
On my 8.5 instance, adding or editing a business causes an exception. I have seen at least two other people report this in Rocket.Chat recently, so I'm opening an issue as it doesn't look like it's something specific to our data.

### Steps to Reproduce
1. Go to Finance | Businesses
1. Add a Business or edit an existing one
1. Save, and an exception occurs.

**Expected behavior:**

Businesses could be added or edited without error as they were prior to 8.5. 

**Actual behavior:**

On mine and others' systems, it blows up. Unfortunately, I cannot dupe this on demo or prealpha, but it's happening to enough people that it can't be attributed to a one-off data problem at one organization.

### Versions
* **Rock Version:** 8.5
![image](https://user-images.githubusercontent.com/3903408/51003192-6c6de900-14fb-11e9-9bb5-f35ee13f224d.png)

**Comment by JimMichael** [comment]
Note that I also verified it's not the _Allow Snapshot Isolation_
or _Is Read Committed Snapshot On_ SQL Server settings... mine were both No, but I changed them to Yes and rebooted and it didn't make a difference.

**Comment by stevelipinski** [comment]
Encountering the same issue in converting a person to business.

**Comment by OnlyByGrace** [comment]
In addition to getting this when trying to create/edit a business, as Jim mentions above, I'm also getting the same error, with the same top 3 lines of the stack trace, when I either
1) Try to create an Rest Key
2) Try to register someone for an event from the external site (haven't tried the internal site)

**Comment by BrentPirolli** [comment]
We tried our 8.5 dev server and had no issues. Perhaps it is related to sql environment or other plugins? We are Azure SQL and VM based if that helps narrow it down.

**Comment by stevelipinski** [comment]
We are on Azure as well.
Just a hunch - I would guess it is related to upgrade.  e.g., may only happen on systems upgraded from v7, or something like that...
@BrentPirolli - was your system an upgrade or fresh install?

**Comment by JimMichael** [comment]
We are self-hosted, so it's not Azure-related. Win2016 IIS VM and Win2016/SQL 2017 db VM.

**Comment by BrentPirolli** [comment]
We have upgraded since 6.something.... so this was an upgrade without the issue.  Do you have any specific plugins in common?

**Comment by stevelipinski** [comment]
Looking at the Rock Shop, Purchases,
I have the following plugins installed:
Acme Certificate 
Group Type Change Tool
Lava Tester
Attended Check-In
SQL Map
Project Management
Rock Shop Notifications
Signup Wizard
Workflow Launcher

**Comment by BrentPirolli** [comment]
We are hosting all on Azure, and are NOT having this issue and we have:

- Attended Check-In (v 1.6 - tested on 1.5 also)
- PushPay Integration (v 4.4)
- PCO Sync (v 2.2.2)
- Group Type Change Tool (v 1.0)
- Pastoral Care (v 2.0)
- Open Connections Digest (v 2.0)
- Lava Tester (v 1.6.0)
- SQL Map (v 1.0)
- Prayer Email Digest (v 1.2)
- Signup Wizard (v 1.2)
- Rock Shop Notifications (v 2.0.0)
- Mine Pass (v 1.0)
- Church Analytics Report (v 2.0)

So I'd guess you can rule out those we have in common... Group Type Change Tool, Lava Tester, SQL Map, Attended Check-In, Rock Shop Notifications, and Signup Wizard... leaving potential culprits:

- Acme Certificate
- Project Management
- Workflow Launcher

**Comment by JimMichael** [comment]
The only one I have of those bottom three are Acme Certs, but I highly doubt that could be causing this issue since it has nothing to do with People records. I'm in the process of getting a new copy of production (8.3) onto my test VM to verify it happens on a "clean" upgrade, since my current broken 8.5 VM has had alpha/beta installed on it, rolled back, re-installed, etc... so I can't really trust it 100%

**Comment by BrentPirolli** [comment]
I installed Acme Certificate on our Alpha 8.5 build that doesn't have the issue... I didn't link it to Let'sEncrypt as I already have a cert on the server, but the file structure and any DB changes the plugin made are in place... and no issues noted. So that probably rules that out anyway.  Seems like it has to be environmental then.

**Comment by nairdo** [comment]
@JimMichael , does your environment have an empty value in the Record Status dropdown?  Here's what it should look like:

https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Utility/StarkDetail.ascx.cs#L68

**Comment by nairdo** [comment]
Also @JimMichael , when you run this query against your db, do you get one row returned?

`SELECT * FROM [DefinedValue] WHERE [Guid] = 'E071472A-F805-4FC4-917A-D5E3C095C35C'`

**Comment by stevelipinski** [comment]
We are encountering the same issue - and have the standard, default recordtypes only.

**Comment by stevelipinski** [comment]
Not sure if this helps, but I noticed that this occurs when editing a business name or email address.  The exception does not occur if I change the address or phone number.
Also, not sure if relevant, but in Lava Tester, a dump of the "Person" via ToJSON shows a handful of null fields, like ConnectionStatusValue, MaritalStatusValue, etc. - could the code be expecting one of these be to be set?

**Comment by JimMichael** [comment]
Ours have null ConnectionStatusValue as well

**Comment by stevelipinski** [comment]
We don't have a Visitor connection status.  I don't recall our history there, so I'm not sure if we deleted it, or renamed it.  But, starting to think that's hard-coded somewhere.

Tried to delete Visitor Connection Status on demo site, and it doesn't error, but doesn't delete.

**Comment by stevelipinski** [comment]
Yep, need to add back in the Visitor Connection Status.  I'm guessing only the Guid matters, but the following SQL fixed our instance:

INSERT INTO [DefinedValue] (IsSystem, DefinedTypeId, [Order], Value, Description, Guid, IsActive)
VALUES (0, '4','30','Visitor','Used when a person first enters through your first-time visitor process. As they continue to attend they will become an attendee and possibly a member.','b91ba046-bc1e-400c-b85d-638c1f4e0ce2', 1)

**Comment by JimMichael** [comment]
@stevelipinski We too have no Visitor connection status... In the other issue I link to above, I mention that I couldn't remember if we'd deleted it or just renamed it, but whatever it was, it was over 3yr ago and it never caused a problem until 8.5. But it looks like you found the culprit, and would explain why only a small subset of Rock users are seeing issues. Thank you!

**Comment by nairdo** [comment]
We'll be adding a migration to re-add this 'system' connection status in 1.8.6 (if it's not there).  In the mean time, a small correction to Steve's SQL would be to mark it as [IsSystem] = 1 with an [Order] = 2 and [IsActive] = 1:

```
IF NOT EXISTS (SELECT [Id] FROM [DefinedValue] WHERE [Guid] = 'b91ba046-bc1e-400c-b85d-638c1f4e0ce2' )
INSERT INTO [dbo].[DefinedValue] ([IsSystem], [DefinedTypeId], [Order], [Value], [Description], [Guid], [IsActive] ) VALUES (1, 4, 2, N'Visitor', N'Used when a person first enters through your first-time visitor process. As they continue to attend they will become an attendee and possibly a member.', N'b91ba046-bc1e-400c-b85d-638c1f4e0ce2', 1)
```

I'll also look into some changes that should prevent someone from deleting these 'system' defined values.

**Comment by smross** [comment]
@nairdo the SQL you posted (which creates the defined value, etc.) seems to also fix the following Exception that we are seeing when we attempt a merge on v8.5
**Occurs when:**: `Merging persons`
**Page/URL**: `Merge People`
**Exception**: `Object reference not set to an instance of an object`
**Exception Type**: `System.NullReferenceException`
**Source**: `Rock`
**Description**: `Object reference not set to an instance of an object`
**Stack Trace**:
```
 at Rock.Model.Person.PreSaveChanges(DbContext dbContext, DbEntityEntry entry)
   at Rock.Data.DbContext.RockPreSave(DbContext dbContext, PersonAlias personAlias, Boolean enableAuditing)
   at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing)
   at RockWeb.Blocks.Crm.PersonMerge.<>c__DisplayClass2c.b__15() in c:\inetpub\wwwroot\Blocks\CRM\PersonMerge.ascx.cs:line 620
   at Rock.Data.DbContext.WrapTransaction(Action action)
   at RockWeb.Blocks.Crm.PersonMerge.lbMerge_Click(Object sender, EventArgs e) in c:\inetpub\wwwroot\Blocks\CRM\PersonMerge.ascx.cs:line 373
```

***I'm happy to open a new issue if needed***

**Comment by JimMichael** [comment]
The fix fixes any place in Rock that creates (or saves) a person record and doesn’t have a default connection status configured/passed. 

It’s a simple issue of assuming that the default Visitor Connection Status (specifically, its GUID) exists, and only affects orgs that deleted said connection status. I doubt there’s any value in re-reporting the same issue in all the places it occurs since it fixes all of them.

**Comment by nairdo** [comment]
Yes, Jim's right.  There are various places that require the Visitor connection status -- it's a system level option and it should not have allowed you to delete it.  In 1.8.6 it will be marked as IsSystem again and so it won't let you delete it.

**Comment by islandross** [comment]
Thanks everyone for the fix. I am about to apply the fix since our church also removed Visitor and is having this issue, however I noticed that we are running 8.7 but the system was still allowing us to remove Visitor. Also the latest demo on rock.rocksolidchurchdemo.com also allow Visitor to be removed (IsSystem false). May I ask if Visitor is no longer a required field? 

Thanks

**Comment by nairdo** [comment]
The connection status of "Visitor" (PERSON_CONNECTION_STATUS_VISITOR) is a system level status that is used in variety of places in Rock.  It is considered required.

**Comment by cabal95** [comment]
@islandross I just checked on the demo site and it did _not_ allow me to delete the `Visitor` status. I think you might be misunderstanding what this conversation was about (being able to delete the Defined Value called `Visitor`). It sounds like you are referring to being able to edit a block setting and "remove" the Visitor status - which is perfectly fine and valid.

**Comment by nairdo** [comment]
Update:  I am investigating why this appears to have been skipped in the v8.8 update.  To Daniel's point -- I found the same problem on the demo site and then manually ran the fix there to see if it works properly.

**Comment by cabal95** [comment]
Aha, okay thanks for the clarification Nick!
