### ISSUE TITLE
Unable to remove a group's location when Enable Group History checked

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3499]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When you want to delete a location from a Group that has Group History enabled you encounter an error:
`The DELETE statement conflicted with the REFERENCE constraint "FK_dbo.GroupLocationHistorical_dbo.GroupLocation_GroupLocationId". The conflict occurred in database "Rock", table "dbo.GroupLocationHistorical", column 'GroupLocationId'. The statement has been terminated. `

Unchecking Enable Group History doesn't resolve the issue because the location information remains in the GroupLocationHistorical table.

I have tested this on Serving Teams, Small Groups and Family Groups. I have also tested it on v8.3 and v8.5.

### Steps to Reproduce

1. Add a location to a Group whose Group Type has 'Enable Group History' checked.
2. Run the Group History Job
3. Try to delete the location.

Unchecking Enable Group History doesn't fix the issue since the location remains in the Group Location History table. 

**Expected behavior:**

Deleting the location without error while maintaining a history of what the locations previously were. Not certain if that means GroupLocationHistorical table should remove the GroupLocationId and LocationId since it maintains the address in the LocationName field.

**Actual behavior:**

Unable to delete locations. If it happens to be a family group you at least have the ability to change it to Previous or another option but makes it complicated for Serving Teams and Small Groups.

### Versions

* **Rock Version:** v8.3 and v8.5
* **Client Culture Setting:** en-US

┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;990571838034653">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;990571838034659">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;990571838034661">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;990571838034663">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;990571838034665">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;990571838034667">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;990571838034669">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;990571838034671">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;990571838034673">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;990571838034675">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;990571838034677">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;990571838034679">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;990571838034681">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;990571838034683">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;990571838034685">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;1102666200080767">image.png</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;1102666200080769">image.png</a>

**Comment by nairdo** [comment]
Due to the the need for a tiny model change for this fix, it is only fixed in v9.
