### ISSUE TITLE
Event Registration creates duplicate address

### ISSUE THREAD

**Issue by stevelipinski** [SparkDevNetwork/Rock#3500]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
Yes
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
 Yes
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
Yes

### Description

Issue equivalent to [1860](https://github.com/SparkDevNetwork/Rock/issues/1680 ) occurs on v8.5, however, apparently only occurring when not logged in:

When asking for address on an event registration, the address entered becomes "Home" and whatever was in home becomes "Previous" even if the two are identical ~~and even when the address was pre-populated when the user is logged in~~.

If the address on the registration matches the Home address on the person's family, no update or addition should be made to addresses.

### Steps to Reproduce

1. Create Registration Template including Address, and necessary Instance
2. As existing user, not logged-in, register for event, using exact address from record.  Complete registration
3. View person record - 2 identical addresses exist.  One for Home, and one for Home-Previous

**Expected behavior:**

Same address should be detected and not replicated as new Home/Previous.

**Actual behavior:**

Address duplicated for Home.

### Versions

* **Rock Version:** Rock McKinley 8.5 (1.8.5.2)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Hi @stevelipinski , We had several people here try to reproduce this issue on Rock version 8.6 but none of them was able to cause this to happen.  If you have any additional details on what you're seeing and how to reproduce this issue -- we'll gladly take another look at this.
