### ISSUE TITLE
DDay.iCal schedule recurrence does not override the effective end date

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#3502]
### Description
The current DDay.iCal package appears to be setting DTEnd ~incorrectly~ [to the first instance of the recurrence], ~which~ however [Rock ](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/CalendarLava.ascx.cs#L402) then sets to the Schedule.EffectiveEndDate as [seen here ](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/Schedule.cs#L390) even though it seems that property should hold the "[date that this Schedule expires and becomes inactive. ](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/Schedule.cs#L116)".  This code could be "fixed" to include a check for `iCal.Until` instead of just `iCal.DTEnd`. However, with this library also having issues with setting StartDate (#1147) ~and EffectiveStartDate (#1350)~, it may be time to revisit #2050.

If the resulting conclusion is `Won't Fix`, is there a suggested Lava alternative to getting the true Effective End Date?

### Steps to Reproduce
1. Create new schedule on Rock demo
1. Use schedule builder to create a recurring schedule
1. Confirm schedule is set 
1. Confirm via SQL that DTEnd is set to the same as DTStart
1. Output upcoming schedules via Lava and some schedules do not appear 

![screen shot 2019-01-17 at 12 52 21 pm](https://user-images.githubusercontent.com/1210933/51338954-3085d700-1a59-11e9-9b4c-0aba4346a682.png)

![screen shot 2019-01-17 at 12 52 30 pm](https://user-images.githubusercontent.com/1210933/51338958-34195e00-1a59-11e9-8bdb-51dce250cfa1.png)

![screen shot 2019-01-17 at 12 53 07 pm](https://user-images.githubusercontent.com/1210933/51338963-38457b80-1a59-11e9-85ee-f9f013b07f3d.png)

**Expected behavior:**

Schedule.EffectiveEndDate would be set to the End Date of the recurrence.

**Actual behavior:**

Schedule.EffectiveEndDate is set to the Start Date of the recurrence.

### Versions
* **Rock Version:** 8.5
* **Client Culture Setting:** en-us

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1116730867919351">image.png</a>

**Comment by nairdo** [comment]
Just for clarification, I updated the description of this issue to note that the DTEnd is to be set to the first instance of the recurrence (as per the [iCal spec](https://www.kanzaki.com/docs/ical/rrule.html)) but we're investigating the use of our custom EffectiveEndDate property to hold the final date of the final recurrence set ([as defined here in the spec](https://www.kanzaki.com/docs/ical/rdate.html)).
