### ISSUE TITLE
Text Formatting Issues in 8.5 on Various Pages

### ISSUE THREAD

**Issue by edcylam** [SparkDevNetwork/Rock#3503]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
I found various places in Rock 8.5 that the formatting of text is off:

* Group Member Filters
* Check-in Manager Login
* Search Reservations of the Room Management plugin

### Steps to Reproduce
Use screenshots

![screen shot 2019-01-10 at 4 28 59 pm](https://user-images.githubusercontent.com/24534451/51355604-8748dc00-1a6c-11e9-9026-6e982ff8863e.png)
![](https://user-images.githubusercontent.com/24534451/51355612-8c0d9000-1a6c-11e9-85f0-d0f79f43f1e5.png)
![](https://user-images.githubusercontent.com/24534451/51355619-9039ad80-1a6c-11e9-9800-c70e4a1dc141.png)

**Expected behavior:**
There should be enough space between check boxes to display text. 
The Manager Options page should display a 3x4 numeric pad.

**Actual behavior:**

The text is simply clumped together. 
The digits of the numeric pad on the Manager Options page are displayed as two columns of digits.

### Versions
* **Rock Version:** 8.5
* **Client Culture Setting:** en-US

**Comment by garrettjohnson** [comment]
It looks like the checkin issue is caused by modifications to your theme, there appears to be additional padding added to the tenkey buttons causing the undesired breaks. 

We added a fix in 8.7 (b06a32abe6016c529ec20cffc8cb8670d6917132) will allow your browser to decide the number of columns that will fit in a area. This should take care of the overlapping text. ![checkbox-reflow](https://user-images.githubusercontent.com/374209/51868987-96514900-230c-11e9-8e0f-737b5da8ed9a.gif)

**Comment by edcylam** [comment]
Wonderful. Thank you.

<http://www.venturechristian.org/>
*Edmund*Lam
Technology & Analytics MANAGER
edmund@venture.cc | 408.997.4600
*16845 Hicks Road, Los Gatos, CA 95032
<https://www.google.com/maps/place/16845+Hicks+Rd,+Los+Gatos,+CA+95032/data=!4m2!3m1!1s0x808e36b3fcbbf1c9:0x1d7da23ee96c622?sa=X&ved=0ahUKEwjwtMDK-qrOAhUMwmMKHW8vDNIQ8gEIHDAA>*
