### ISSUE TITLE
Group Requirement Type Error

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#3504]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
I am receiving an error message upon hitting the save button when adding a new Group Requirement Type. See attached images from both MY instance of Rock and the RockRMS demo site.

### Steps to Reproduce
1: Create a 'person' data view that shows all people who have a note of a specific type in your database. (for example we have an "alert note" type. I have a data view that shows me a list of those people (92 in total)
2: Create a Group Requirement Type that shows that data view as the "warning".
3: Hit Save
4: Receive Error

**Expected behavior:**

I was expecting that upon hitting save... the Group requirement type would save and become operational.

**Actual behavior:**

Error is received upon hitting save. Please see attached images.

### Versions
* **Rock Version:** [Rock McKinley 8.5 (1.8.5.2)]
* **Client Culture Setting:** [en-US ![my rock instance](https://user-images.githubusercontent.com/41912840/51510079-a37cae00-1dc9-11e9-97b7-266d4866dcc4.png) ![demo site](https://user-images.githubusercontent.com/41912840/51510080-a37cae00-1dc9-11e9-9d60-a9188dca30e7.png)

]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1102666200080775">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1102666200080777">image.png</a>

**Comment by TheArkChurch** [comment]
Can confirm that this also happens when using Dataviews with no optional warning indicated and cannot edit existing Group Requirement types that use Dataviews. Not sure if that helps.

**Comment by cabal95** [comment]
Confirmed on our 8.4 system as well. Based on the error, I'm guessing the `DataViewId` property isn't getting set for some reason.

**Comment by karenn-ccbc** [comment]
I had this happen in 8.4 with group requirements I had set when I went in to edit then I received the error. When I added in both a meets dataview and a warning dataview then it saved with no error.

**Comment by jcjones37** [comment]
Confirmed... if you have a "Meets Dataview" and a "Warning Dataview" it will allow you to add the Group Requirement without an error

**Comment by TheArkChurch** [comment]
Also confirmed. Clarity is needed on this behaviour. If this is now intended the help text should be updated from Optional to Required. In our case we've never used failed dataview, just the failed message that the dataview returns.

**Comment by ethan-sparkdevnetwork** [comment]
Reproduced by selecting a Data View category instead of a Data View.

Added Property "AllowCategorySelection" to ItemPicker with the default set to false. If this is false then the category is not select-able.
