### ISSUE TITLE
Single quotes break Lava Fields in Email Templates

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3505]
### Description
When creating an email template that uses Lava Fields, using a single quote inside the value breaks the lava (It generates invalid lava and only the part before the single quote is recognized)

<img alt="Screen Shot 1" src="https://user-images.githubusercontent.com/2406499/51540901-88d82280-1e25-11e9-8a75-ef820916e26a.png">
<img alt="Screen Shot 2" src="https://user-images.githubusercontent.com/2406499/51540913-8c6ba980-1e25-11e9-93d2-372fc9778926.png">

### Steps to Reproduce
1. Create an Email Template that uses Lava Fields
1. Set a value that has a single quote in it

**Expected behavior:**

The entire value is available in the email.

**Actual behavior:**

Only the first part of the value is available.

### Versions
* **Rock Version:** 1.8.5.2, 1.9.0.11 (pre-alpha)
* **Client Culture Setting:** en-US

**Comment by kcirgjd** [comment]
In my opinion, this isn't a bug because ' is needed for lava. The majority of people developing Lava/HTML templates will just look up the ASCII code "&#39" and use that which works. 

"It&#39s a great day"

**Comment by nairdo** [comment]
Yes, when using a hard-coded raw single quote, you should encode it as `&#39`.  In other cases where the value is not raw (inline) but is coming from a value, you can use the `Escape` filter where needed.
