### ISSUE TITLE
[EN] Lava Filter DateDiff Year factors in month and day to determine years between

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3509]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
I'm creating an email template and a piece of it looks at the Person's background check date and is suppose to inform the Person if they need to fill out a new background check or not based on their check date and a specific event's date (2/8/2019). 

When I use DateDiff with the Year option I think it is only subtracting the years and not factoring the month and day. If I set my background check date to 1/1/2019 the result is 0. When I set the date to 12/31/2018 the result is 1

{% assign PersonBGC = Person | Attribute:'BackgroundCheckDate' %}{% assign BGC = PersonBGC | DateDiff:'2/8/2019', 'Y' %} {% if BGC != 0 %} This is the code piece I am using. I would love to do days but the issue with days is  '>' gets escaped from the email template, which breaks the condition. 

~~Not certain if it is related to this issue (Age miscalculated in Registrant list): https://github.com/SparkDevNetwork/Rock/issues/3489#issue-395768198~~

### [EDIT]
After looking at the Lava Filter file (https://github.com/SparkDevNetwork/Rock/blob/5937d321d5d888b35267052dcd5211cf854700c6/Rock/Lava/RockFilters.cs#L1447) the filter is just subtracting the years and not accounting for months and days. 

As an enhancement, would it be possible to change the Year option to account for the difference in the month and day so it isn't simply subtracting the years, or could another year option be added to do the enhanced functionality? 

### Steps to Reproduce
1. Either in an email, HTML block, or Lava Tester use the code above or any other attribute with a date and the DateDiff lava filter.
2.Play with different dates to see the result.

**Expected behavior:**

DateDiff with Year option should factor in month and day to determine the year difference. 

**Actual behavior:**

Looks like it may just be subtracting the two year values.

### Versions
* **Rock Version:** v8.5
* **Client Culture Setting:** en_US

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
