### ISSUE TITLE
Statement Generator includes wrong names on giving statements

### ISSUE THREAD

**Issue by rogersjd14** [SparkDevNetwork/Rock#3510]
### Description

hi everyone... I think this may be a bug in the Statement Generator?

We figured out how to separate an individual's giving from the rest of the family in Rock (i.e. a child who gives wants their own statement to file taxes separately). If you go to that person's profile in rock and generate a statement, everything looks fine. Only his/her name is on the statement. In addition, if you go to the parents, only the parents name is on their statement when generated directly out of Rock.  All giving numbers are accurate.

When using the statement generator, however, **the child's name appears on the parents statement, even though their giving is supposed to be separated.**  The giving numbers are accurate on the statement, but the wrong names appear.  Again, everything looks fine when generating statements out of Rock.  The statement generator is where the issue occurs.

Is there a way to fix this? We are trying to bulk generate statements for the entire church! Thanks

### Versions

* **Rock Version:** 8.5
Statement Generator version: as of 1/14/19

**Comment by rutledgek** [comment]
I believe this is an issue with the statement generator's use of the ufnCrm_GetFamilyTitle function.  I am pretty sure that that function is using the person's family group id rather than the giving group id.  So it is pulling in people in the family even when they are marked give alone(can't remember the name of the setting).  

This can be found in the generator on line 427.

https://github.com/SparkDevNetwork/Rock/blob/d0ead908ceac5e6141e285689854bfbbda98fa0a/Rock.StatementGenerator/Rest/StatementGeneratorFinancialTransactionsController.cs

I am not sure if this is the same function as the {{FamilySalutation }} lava filter, which you would want to include everyone in the same family. However, this does not work with the giving group where people might give alone or in a group and still be in the same family.

**Comment by rutledgek** [comment]
Not sure if I can include this here or need to open another support issue for the statement generator rest endpoint, but line 561 and 562 "AcccountSummary" both return the account.Name rather than account.PublicName.  I would assume public name is expected behavior as it is the name use in public facing operations.

**Comment by nairdo** [comment]
@rogersjd14 We have not been able to reproduce the issue you are encountering.  So we may be missing something about your data. 

I set up a contribution for Noah Decker (who's record is set to _not combine giving_ with his family) and then I pointed my Statement Generator application at the demo site.  It generated the contribution statement which included a separate statement for Noah and a separate statement for Ted & Cindy Decker:

![image](https://user-images.githubusercontent.com/383807/52130948-d2302b00-25f8-11e9-91bb-43f88fc99d32.png)

![image](https://user-images.githubusercontent.com/383807/52130923-c6dcff80-25f8-11e9-863f-4af13b48bed9.png)

Have you updated uninstalled the old v7 Rock Statement Generator and reinstalled the new one for v8?  There is a possibility you may be running an older version of the generator.  If that is not the issue, can you include some screenshots of the two people in question and the advanced settings in their profile? (see example below).

![image](https://user-images.githubusercontent.com/383807/52131156-54205400-25f9-11e9-992a-117cba14a308.png)

**Comment by rogersjd14** [comment]
Yes, I am running the latest version of Rock and the latest version of the Statement Generator (downloaded today from the external applications section under Power Tools in Rock)

Here is an example of one person (Eric) being incorrectly grouped with his parents (Dennis and Melisa):

![image](https://user-images.githubusercontent.com/47148400/52137223-1848b700-2618-11e9-9be0-ccf7fed45175.png)


His statement immediately follows after:
![image](https://user-images.githubusercontent.com/47148400/52137414-7aa1b780-2618-11e9-9d8f-5ecf30a88a8d.png)


In the above examples, the giving numbers are accurate.  It's the names that shouldn't be grouped together.  The first statement above should only be Dennis and Melisa.
Here are all users Advanced Settings:

Dennis:
![image](https://user-images.githubusercontent.com/47148400/52137499-ae7cdd00-2618-11e9-9c93-fe53fca291ed.png)


Eric:
![image](https://user-images.githubusercontent.com/47148400/52137526-c0f71680-2618-11e9-9d8c-c6da6d3db0e0.png)

Melisa:
![image](https://user-images.githubusercontent.com/47148400/52137557-d5d3aa00-2618-11e9-9783-262f263ffc4e.png)

**Comment by nairdo** [comment]
@rogersjd14 We were able to confirm that it will appear that way if the person is an adult in the family.  Can you confirm that the child in your example (Eric) is actually set as an adult?  If so, change him back to a child and re-create the statement to verify that that resolves the issue.

**Comment by rogersjd14** [comment]
I enabled 'Lock as Child' and the Statements still look incorrect (Eric is grouped with Melisa and Dennis as before).  I also changed his birth date to show he is 10 years old (i.e. a child) and it still doesn't work properly.

**Comment by nairdo** [comment]
I was not referring to the birth date, just the family role: 
![image](https://user-images.githubusercontent.com/383807/52306958-882baa00-2956-11e9-9d82-58b1837015b6.png)

**Comment by rogersjd14** [comment]
Yes, that appears to have fixed it.  But Eric is not a child, he is an adult.  Even the system automatically converts him to an adult after 18 years of age.  Is this still considered a bug?  Thanks

**Comment by rutledgek** [comment]
More than 2 adults in a household will always cause problems.  The keep as child prevents the automatic data management from converting them to an adult.  If they are an adult moving them to their own household even at the same address will fix it.

**Comment by cabal95** [comment]
@rogersjd14 FYI, under Tools > Data Integrity is a page called Data Automation. In there you can configure the system to automatically move "children" when they turn 18 to their own family - and it sets up the proper relationships automatically.
