### ISSUE TITLE
Prayer Category and Campus

### ISSUE THREAD

**Issue by charlottedean** [SparkDevNetwork/Rock#3513]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When exporting prayer requests, campus and catergory are left blank in the excel document.

### Steps to Reproduce
1. Go to Prayer Requests
1. Click on Export to Exccel
1. Open document
1. See blank columns for category and campus

**Expected behavior:**

Columns for campus and category should be populated

**Actual behavior:**

The columns for campus and category don't populate, they are left blank

### Versions
* **Rock Version: 8.5
* **Client Culture Setting: en-us

**Comment by nairdo** [comment]
Confirmed fixed in v9 via various grid changes.  You can see the fixed behavior here: https://prealpha.rocksolidchurchdemo.com/page/431
