### ISSUE TITLE
8.6alpha Switching Templates in Comm Wizard Retains From: Address

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3516]
### Description

Using the Communication Wizard, if you choose a template that has a pre-defined FROM: address, then go back and choose a different template, the FROM: address remains from the first template chosen. 

### Steps to Reproduce

1. Go to People | New Communication
2. Choose a template that has a baked-in FROM: address
3. Click `Previous` button and choose a template that does NOT have a baked in FROM: address
4. Observe that the FROM: address from the first template remains and is not blanked-out.

**Expected behavior:**

Switching between templates in the wizard mode would reset the FROM address

**Actual behavior:**

FROM address is retained when choosing a different template. This could cause a message to go out with the wrong from address if the sender doesn't happen to notice it's wrong.

### Versions

* **Rock Version:** 8.6alpha
![image](https://user-images.githubusercontent.com/3903408/52083632-97c97e00-2565-11e9-88b7-ccb910918de4.png)

![image](https://user-images.githubusercontent.com/3903408/52083718-d6f7cf00-2565-11e9-9460-dd4045cf7bb8.png)

**Comment by nairdo** [comment]
This requested change appears to be a collision with the opposite request here https://github.com/SparkDevNetwork/Rock/issues/2888.

**Comment by nairdo** [comment]
We will retain the current functionality on the _Simple Editor_ (CommunicationEntry block) but we'll change the _Wizard_ (CommunicationEntryWizard block) to clear From Name/Email if they are blank on the template.

**Comment by cabal95** [comment]
Just a note for whomever implements, since this will probably come up in the future, probably worth leaving a comment in the C# code stating explicitly that is is function the way it is by design. Maybe reference this issue too.
