### ISSUE TITLE
Not Required Comment Field in Transaction Entry

### ISSUE THREAD

**Issue by craigmash** [SparkDevNetwork/Rock#3517]
# Feature Request

**Describe the Feature Request**
When you turn on the Comment field in the Transaction Entry block, it is a required field and the user must put something in it. This type of field really needs to be optional.

**Describe Preferred Solution**
Comment field in the Transaction Entry block is made to be not required.
 
**Describe Alternatives**
Add a second notes type field that is not required.

**Providing Code**
No

**Comment by craigmash** [comment]
Someone on Rocket.Chat gave a workaround for this. Open the TransactionEntry.ascx found in \Blocks\Finance
Change this line...
<Rock:RockTextBox ID="txtCommentEntry" runat="server" Required="true" Label="Comment" />
Change the "true" to "false" and it is no longer required.

**Comment by taylorbrooks** [comment]
The challenge with the workaround is that if you update to a new version of Rock, the code reverts back to its original behavior and comments would be required again.

@nairdo We added a block setting in our forked version of the `TransactionEntry` block with a boolean for making comments required/optional. Is this something that would be welcomed in core? Happy to submit a PR.

**Comment by taylorbrooks** [comment]
@nairdo This is one of the enhancements we would be happy to contribute back to core. 

Should we open a new issue or can you re-open this one?

**Comment by nairdo** [comment]
@taylorbrooks After a recent internal discussion, I'd say to open this one as an "Idea" at the Community site at: http://community.rockrms.com/ideas  (Mention that you'd provide the PR and that may speed it along.)

**Comment by nathanp** [comment]
+1 for this. We have had to make our own custom block just to have this feature.
