### ISSUE TITLE
IRockStartups inside ~/App_Code no longer called in 8

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3518]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Concrete use-case is putting custom lava filters in a `.cs` file in the `~/App_Code` folder so that we don't need to build a custom DLL. In 7.x this worked fine. In 8.x (for sure 8.3 - 8.5) this no longer works. Using Visual Studio debugger, the class is never loaded or initialized.

I see that there were a number of changes made to the `Rock.Reflection` about 7 months ago and I am wondering if those changes somehow caused any classes inside the `~/App_Code` to be ignored during reflection.

The `RunStartups()` method in the `Global.asax.cs` file uses the `Rock.Reflection.FindTypes()` method to find any `IRockStartup` classes.

### Steps to Reproduce
1. Add a custom `IRockStartup` class to the `~/App_Code` folder that provides a custom Lava filter.
1. Restart Rock
1. Attempt to use custom Lava filter
1. Notice filter does not work.
1. Put that same `.cs` file in a DLL and place inside the `~/bin` folder and lava filter works.

**Expected behavior:**

Custom code inside the `~/App_Code` folder should work.

**Actual behavior:**

It doesn't.

### Sample custom lava file
```
using DotLiquid;
using Rock.Utility;

namespace com_shepherdchurch
{
    public class LavaAdditions : IRockStartup
    {
        public int StartupOrder { get { return 0; } }

        public virtual void OnStartup()
        {
            Template.RegisterFilter( GetType() );
        }

        public static string CustomToUpper( object input )
        {
            if ( input == null )
            {
                return null;
            }

            return input.ToString().ToUpper();
        }
    }
}
```

### Versions
* **Rock Version:** 8.3 - 8.5
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
fixed via https://github.com/sparkdevnetwork/rock/commit/f798176d5fbf7cf15aee94c551b904d908a91e73
