### ISSUE TITLE
Statement Generator ignores "custom settings" (like page size)

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3524]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

All the custom settings on the statement generator seem to be ignored for some reason. We took a quick look at the code and went "oh yea, thats the problem" but I forget what it was. It was a few weeks ago when we were running statements and I thought I had already reported it but apparently didn't.

It's easy to verify the bug. Despite the fact that it's supposed to generate `letter` size pages it is actually generating `A4` size (which is the default size for the PDF library).

Additionally, I think the `size.pageSize` is the wrong configuration so a migration might be needed to adjust those in existing templates.

### Steps to Reproduce

1. Open statement generator
2. Run statements and select a template that is configured for letter size.
3. Generate statements
4. Open PDF and view details to see that page size is _not_ 8.5x11 but rather 8.27 x 11.69 (A4).

**Expected behavior:**

Custom settings should be honored - especially page size.

**Actual behavior:**

They are ignored and you have to "shrink to fit" to get letter size pages.

### Versions

* **Rock Version:** 8.4
* **Client Culture Setting:** en-US

**Comment by MikeDPeterson** [comment]
this is fixed with https://github.com/sparkdevnetwork/rock/commit/72eb242a869c8a5de4b9ec85f3558c0f85fca2a6

**Comment by cabal95** [comment]
@MikeDPeterson Are you sure that is the correct commit? It doesn't seem to have anything to do with the statement generator, other than updating the URL to download it from.

**Comment by MikeDPeterson** [comment]
This is the commit that added the feature, https://github.com/sparkdevnetwork/rock/commit/c0b58fe063113bba7d6d8a1696088c1ddf666a8c.  The problem was that there was no migration to update to link to the newer statementgenerater.exe. That is fixed with https://github.com/SparkDevNetwork/Rock/commit/72eb242a869c8a5de4b9ec85f3558c0f85fca2a6#diff-70673dc37f9b610c88f341180503e343R35
