### ISSUE TITLE
Warn the user when about to delete First and Last Name

### ISSUE THREAD

**Issue by TheCoreyHall** [SparkDevNetwork/Rock#3525]
# Feature Request

**Describe the Feature Request**
We have had an issue with staff who have deleted the first and last name from church members, thus making them unsearchable in Rock. We would like to request a pop up that lists the issue with this and requires the user to confirm when they attempt to do so.

**Describe Preferred Solution**
Whenever a user clears out the first and last name of a profile in Rock and attempts to save, a warning appears telling them the danger of doing so and asks them to confirm before they can save the changes.

**Describe Alternatives**
Not letting the user save a profile edit if they first and last name are now blank.

**Providing Code**
I will provide code if feature request is approved: [No]

**Comment by edmistj** [comment]
You might submit this here:
https://www.rockrms.com/ideas

This is a new area for ideas.
