### ISSUE TITLE
Enable Filter Control for the Schedules Field Type

### ISSUE THREAD

**Issue by tcavaletto** [SparkDevNetwork/Rock#3526]
# Feature Request

**Describe the Feature Request**
We have several volunteer groups with member attributes of type Schedules that we want to be able to filter on when in the Group Viewer. This change would enable a filter control for these types to be displayed.

**Describe Preferred Solution**
This code would enable a filter control for Schedules that matches results that contain one of the selected schedules, drawing from the Schedule and Categories (for the 'contains' feature) Field Types

**Providing Code**
I will provide code if feature request is approved: Yes

**Comment by edmistj** [comment]
DM'ed

**Comment by nairdo** [comment]
ref https://github.com/SparkDevNetwork/Rock/commit/e16ed07ad18d9abcabf48c79ed577db023f053a6
