### ISSUE TITLE
8.5+ 404 Pages Are Not Returned

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3528]
### Description

Requesting a nonexistent page returns the homepage instead of the 404 page defined for that site. This appears to be a re-appearance of the same bug that was fixed in #2816. It's strange because it appears to have been fixed in 7.4+ (our 8.3 production box doesn't have the issue) then broken again somewhere along the line after 8.3. I did NOT have the ability to test on 8.4, but for sure it's broken in 8.5 through prealpha.

### Steps to Reproduce

1. On 8.5 or later, go to a bad (nonexistent) page
2. Observe you are taken to the homepage of the site you're on

**Expected behavior:**

Nonexistent pages would return the site's 404 page

**Actual behavior:**

You get the homepage instead

### Versions

* **Rock Version:** 8.5-prealpha

**Comment by briankalwat** [comment]
Confirmed in `9.0 (1.9.0.11)`. Thanks @JimMichael!

**Comment by jweather** [comment]
My 404 page used to receive the original URL in Request.RawUrl.  Now it always receives /page/undefined as the URL regardless of the original entry.  How can I get the original URL that caused the 404 so I can redirect it appropriately?
