### ISSUE TITLE
Members can view their groups in My Account

### ISSUE THREAD

**Issue by edcylam** [SparkDevNetwork/Rock#3529]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Group members of the Small Group group type can view their groups on their My Account page although the "Can View" option in the Group Type settings is unchecked.

### Steps to Reproduce
1. Go to Admin Tools > Settings > Group Types
1. Go to the Small Group group type
1. Edit the Member role
1. Uncheck "Can View" and save
1. Go to My Account of the profile of a person who is a member of a group of the Small Group group type
1. The group is viewable in the Group List Personalized Lava block of the account.

**Expected behavior:**

If the member role of the Small Group type has the "Can View" option unchecked, members of groups of this group type should be unable to see their groups in My Account.

**Actual behavior:**

I unchecked the “Can View" option in the member role of the Small Group type. However, I found out members of groups of this group type can see their groups listed in the Group List Personalized Lava block in My Account. The reason I don’t want Members to see their groups is that we want the contact info of group members only viewable by leaders and assistant leaders only.

I checked with KFS, and they suspected that the default lava template for the Group List block doesn't make sure they have permission to the group before giving them the link and the group toolbox page doesn't respect the can view group role security.

### Versions
* **Rock Version:** 8.5
* **Client Culture Setting:** en-us

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1119940998244399">image.png</a>

**Comment by dylan-gregory** [comment]
This appears to happen to both core instantiated group roles - Leader and Member. In an attempt to hide/show some content with Lava based off of the CanView property, it always returns as false despite what it says in the UI of the group type role setting. Custom group roles work correctly, though.
