### ISSUE TITLE
Event Registration - Auto Apply discount code overriding existing discount on a registration

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#3532]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When a registrant has previous registered for an event and goes back to make a payment or edit their existing registration their previously applied discounts will be ignored if there is currently an active automatically applied discount in effect on the registration template.

### Steps to Reproduce
1. Create an registration template and instance that has a cost
1. Add a discount code that should be automatically applied to registrations
1. Add a discount code that is expired or is not automatically added (should be a different amount or percentage as the one created in step 2)
1. Register a person for the event through the admin/internal  portal and apply the discount code that you created in step 3 and optionally make a partial payment on the registration.
1. Load the registration through the external website portal
1. Rock will override the discount (step 3) that you previously applied and try to apply the automatic discount (step 2) to the registration

**Expected behavior:**

The registrant's previous discount will remain applied to their registration. 

**Actual behavior:**

The registrant's previous discount is overwritten with the auto applied discount. (see example below from Rock Solid Church Demo site)

### Versions
* **Rock Version:** 8.4
* **Client Culture Setting:** en-us

#### Screen Shots
* Internal Registration Detail Screen
![](https://user-images.githubusercontent.com/2363131/52376739-7fa3a400-2a28-11e9-8ff6-36130c77639c.PNG)
* External Registration Payment Screen
![](https://user-images.githubusercontent.com/2363131/52376793-a661da80-2a28-11e9-8320-8b1208f1c648.PNG)

**Comment by mikejed** [comment]
In case someone else runs into this issue before the fix is available, I want to note that this also fixes the issue of auto-applied date-dependent discounts ("early bird discounts") from being removed when payments are made after the discount expires.
