### ISSUE TITLE
Metrics legend can cover up part of the chart and prevent viewing details

### ISSUE THREAD

**Issue by debbiethurston** [SparkDevNetwork/Rock#3533]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) yes...Beta 8.6 ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) en-us ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
We are currently using V8.5 but also have this issue in Beta 8.6.  In the Weekly Metrics, our Adult Attendance graph will allow a user to hover over the values and see the information.  But the legend for the graph is over the information preventing the entire right hand side of the graph to be of no use.

### Steps to Reproduce
1. Go to 'Metrics'
1. Click on 'Weekly Metrics'
1. Scroll down to 'Adult Attendance'
1. See error

**Expected behavior:**

Expect that the legend would be placed in such a way that it would NOT prevent user from seeing the results when hovering over the graph lines.

**Actual behavior:**

Unable to see the results when hovering over the graph lines as the legend is preventing.

### Versions
* **Rock Version:** [8.5 but also verified it on our Sandbox Beta 8.6]
* **Client Culture Setting:** [en-us]

**Comment by Tschrock** [comment]
Confirmed on 8.8 - The legend can cover up part of the chart (and then some) which prevents hovering over parts of the lines.
![firefox_2019-07-17_16-02-25](https://user-images.githubusercontent.com/2406499/61407723-64c53d80-a8ac-11e9-8a11-072f1d0b4028.png)

**Comment by megilee** [comment]
I can confirm that this is still an issue in v12.1. This screenshot was created on the Rock Demo site:
![Screen Shot 2021-02-26 at 3 02 45 PM](https://user-images.githubusercontent.com/45012163/110843963-7ff97380-826e-11eb-9715-c53ffebc80ad.png)
This is our Rock instance:
![Screen Shot 2021-02-08 at 9 48 07 AM](https://user-images.githubusercontent.com/45012163/110844035-91db1680-826e-11eb-9a5a-9bc8b4bcfe1d.png)
