### ISSUE TITLE
Entity Command does not support sorting by date

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#3534]
### Description
A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce
1. Use Entity Command to retrieve items that have a date property/attribute.

```
{% contentchannelitem ids:'31,32,33,34' sort:'CreatedDateTime desc' iterator:'items' %}
    {% for item in items %}
        {{ item.Title }}<br>
    {% endfor %}
{% endcontentchannelitem %}
```

**Expected behavior:**

Items should be returned, correctly sorted by date in either ascending/descending order, depending on what is specified in the sort parameter.

**Actual behavior:**

No items are returned, only the following error: `Liquid error: No generic method 'OrderByDescending' on type 'System.Linq.Queryable' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic.`

### Versions
* **Rock Version:** 9.0 (1.9.0.13)
* **Client Culture Setting:** en-US

**Comment by roblaughter** [comment]
I'm also experiencing this on Rock Version 8.5 (1.8.5.2). 

`{% contentchannelitem ids:'87,447,448' sort:'StartDateTime' %}
    {% for item in contentchannelitemItems %}
        {{ item.Title }}<br />
    {% endfor %}
{% endcontentchannelitem %}`

**Returns the following:**

`Liquid error: No generic method 'OrderBy' on type 'System.Linq.Queryable' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic.`

**Comment by edmistj** [comment]
Oddly this is only an issue when using `ids`, using a `where` works as expected.

```
{% contentchannelitem where:'Id == 1 || Id == 2' sort:'CreatedDateTime desc' iterator:'items' %}
    {% for item in items %}
        {{ item.Title }} - {{ item.CreatedDateTime }}<br>
    {% endfor %}
{% endcontentchannelitem %}
```

We'll address this, but in the meantime try a `where`.

**Comment by bengoshow** [comment]
I'm having a similar issue with the following Lava, on the Rock Demo site, currently v1.8.7.3

`<ol class="messages">
{% capture childIds %}
	{% for child in Item.ChildItems %}
		{{ child.ChildContentChannelItem.Id }}{% unless forloop.last %},{% endunless %}
	{% endfor %}
{% endcapture %}
{% contentchannelitem ids:'{{ childIds }}' %}
	{% assign sortedItems = contentchannelitemItems | Sort:'StartDateTime desc' %}
	{% for message in sortedItems %}
		<li>
		<a href="/page/461?Item={{ message.Id }}">
		{{ message.Title }}
		</a> - {{ message.StartDateTime }}
		</li>
	{% endfor %}
{% endcontentchannelitem %}
</ol>`

**Comment by briankalwat** [comment]
@edmistj I tried the method you suggested above for sorting groups by name, and it works, but only for ordering `desc`. The only way I was able to sort `asc` was to use `desc` and then use the `reversed` parameter on the for loop. Hopefully this is helpful whenever we start debugging.
