### ISSUE TITLE
Modify Rock to allow for custom Lava Filters

### ISSUE THREAD

**Issue by tcavaletto** [SparkDevNetwork/Rock#3538]
# Feature Request

**Describe the Feature Request**
Currently, the only lava filters available are those in the RockFilters.cs class, and are added to the liquid template system [here](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/App_Code/Global.asax.cs#L310).

This prevents developers from creating custom Rock Filters either to support existing plugins or as their own standalone plugins.

**Describe Preferred Solution**
We should replicate the work done to integrate custom entities into the [RockContext](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Data/RockContext.cs#L1728), and create a new empty interface IRockFilter that both RockFilters and any custom filter classes can inherit from. Then we can modify the Global.ascx.cs to register all those classes as filters, i.e.:
`var rockFilterList = Reflection.FindTypes( typeof( Rock.Lava.IRockFilter ) ).Select( a => a.Value );
                    foreach ( var rockFilter in rockFilterList )
                    {
                        Template.RegisterFilter( rockFilter );
                    }`

The main thing that this would effect is changing RockFilters.cs from a static class to a non-static one

**Providing Code**
I will provide code if feature request is approved: [Yes]

**Comment by cabal95** [comment]
This comes up from time to time, so here is a sample of how to add custom filters for anybody who finds this issue later:

```
using System;
using System.Collections.Generic;
using System.Data.Entity;

using Rock;

namespace com.rocksolidchurchdemo.CustomProject
{
    public class LavaFilters : IRockStartup
    {
        /// <summary>
        /// All IRockStartup classes will be run in order by this value. If class does not depend on an order, return zero.
        /// </summary>
        public int StartupOrder => 0;

        /// <summary>
        /// Method that will be run at Rock startup
        /// </summary>
        public virtual void OnStartup()
        {
            //
            // Register the "public static" methods in this class as lava filters.
            //
            Template.RegisterFilter( GetType() );
        }

        /// <summary>
        /// A silly sample of a Lava filter.
        /// Usage: {{ 'Hello World' | BoldText }}
        /// </summary>
        /// <param name="input">The text to be bolded.</param>
        /// <returns>An HTML string of bolded text..</returns>
        public static string BoldText( object input )
        {
            string text = input.ToStringSafe();

            return $"<b>{ text }</b>";
        }
    }
}
```

The `IRockStartup` interface is used by Rock to allow custom plugins to run initialization code during Rock startup, before the system starts accepting web requests. This can be used for many things, but here we use it to register our custom lava filters.
