### ISSUE TITLE
[EN] GetDate doesn't report correct time

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#3546]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
This is not technically a bug with Rock, but rather a bug in the way we are using SQL.

Azure DBs are all set to UTC Time. As a result, if you run the GetDate command from SQL, you are going to get a time that is several hours in the future. If you are running this to get the current date, normally this is not a huge problem. The two huge problems you are going to run into are:

1. If it is past 4PM in America, it is potentially the next day in UTC. This could create a lot of problems for any jobs that are SQL.
1. If you have SQL that is trying to get the current time, you are never going to get the correct time.

### Steps to Reproduce
1. Go to RockSolid Demo Site > SQL Command: `https://rock.rocksolidchurchdemo.com/page/147`
1. Get the Current Date via `SELECT GETDATE()`
1. Call yourself [Marty McFly ](https://tenor.com/view/back-to-the-future-michael-jfox-heavy-marty-mc-fly-gif-4584334)cause you have just time traveled.

**Expected behavior:**
This behavior is expected. To resolve this issue, we should import the following Function into all Rock environments.

```
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
<doc>
    <summary>
         This function returns the current time regardless if the DB is in Azure or not
    </summary>
    <returns>
        Current Date Time
    </returns>
    <remarks>
		Azure Databases are in the UTC timezone. As a result, if you attempt to do GETDATE(), you
		are going to be off be 5 - 9 hours. This function checks to see if the DB is in UTC, and if
		it is, it will convert the time to your configured Time Zone.
		If you would like to find your timezone identifier, use the following query:
		select * from sys.time_zone_info
    </remarks>
    <code>
        SELECT [dbo].[ufnUtility_GetDate]( GETDATE() )
		SELECT [dbo].[ufnUtility_GetDate]( DATEADD( DAY, 1, GETDATE() ) )
		SELECT [dbo].[ufnUtility_GetDate]( SELECT DATEADD( YEAR, -1, GETDATE() ) )

    </code>
</doc>
*/
CREATE FUNCTION ufnUtility_GetDate (@DateTime datetime)
RETURNS datetime
AS
BEGIN
	DECLARE @ReturnValue datetime

	IF GETDATE() = GETUTCDATE()
	BEGIN

		DECLARE @TimeZone varchar(255) = 'Central Standard Time'
		DECLARE @Offset AS datetimeoffset
		SET @Offset = CONVERT(datetimeoffset, @DateTime) AT TIME ZONE @TimeZone
		SET @ReturnValue = CONVERT(datetime, @Offset);
	END
	ELSE
		BEGIN
			SET @ReturnValue = @DateTime
		END

	RETURN @ReturnValue
END
GO
```

After this has been imported, you can get your actual time via: `SELECT dbo.ufnUtility_GetDate(GETDATE())`

**Actual behavior:**
GetDate is returning time in UTC

### Versions
* **Rock Version:** ALL
* **Client Culture Setting:** ALL

**Comment by tscrip** [comment]
It also looks like there might be a few Stored Procedures that are using GetDate.
https://github.com/SparkDevNetwork/Rock/search?q=GetDate%28%29&unscoped_q=GetDate%28%29

**Comment by cabal95** [comment]
The function would have to be modified, I'm guessing, to use a Time Zone global attribute or something, correct?

**Comment by tscrip** [comment]
Yes. That would probably make more sense. I was thinking you just hardcode it in the Function, but pulling from an attribute would definitely make it easier to work with.
