### ISSUE TITLE
Family Attendance Badge Show Incorrect Count

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#3547]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
When viewing the Family Attendance badge, you will notice that the data is a little off. After digging into the code, I found that it is using a REST API: `/api/PersonBadges/FamilyAttendance/` which is calling a Stored Procedure: `spCheckin_BadgeAttendance`

Looking at the code in the Stored Procedure, it appears to be giving someone credit if the group met. It doesn't look like it is checking to see if the `DidAttend` bit is flipped.

I think the fix is going to be updating the following line in the stored procedure above.
**Stored Procedure**: `spCheckin_BadgeAttendance`
**Line Number**: 94
`INNER JOIN [AttendanceOccurrence] O ON O.[Id] = A.[OccurrenceId]`
to
`INNER JOIN [AttendanceOccurrence] O ON O.[Id] = A.[OccurrenceId] AND A.[DidAttend] = 1`

### Steps to Reproduce

1. Add a person to a group
2. Add an attendance record for the group (but don't add attendance for person)
3. Run the stored procedure and notice they are getting credit

**Expected behavior:**
They should not be given credit for any group they are a member of. The stored procedure needs to be updated to look for attendance records with the `DidAttend = 1` flag.

**Actual behavior:**
Stored Procedure is looking at Group Attendance. If the group met, all group members are getting credit.

### Versions

* **Rock Version:** 8.5
* **Client Culture Setting:** en-US

**Comment by aaronjones8** [comment]
Found the same issue. This can be fixed by adding a DidAttend = 1 to the where clause on line 99 of the spCheckin_BadgeAttendance stored procedure

**Comment by nairdo** [comment]
NOTE: Tom has submitted a PR https://github.com/SparkDevNetwork/Rock/pull/3558 to address this or other issues with this item.

**Comment by karenn-ccbc** [comment]
Is it ok to correct this on our end before version 9? This is driving me crazy on data integrity clean up. when do we expect version 9 to release? I am thinking around the Rock conference in Sept is that a correct assumption?
