### ISSUE TITLE
StripHtml Lava Filter does not remove multi-line HTML comments

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3548]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Recommend adding `<!--(.|\n)*?-->` to the StripHtml lava filter. As standard HTML tags cannot be multi-line, but html comments can.

This will prevent issues where comments are included in search results and then trimmed mid-comment, causing the page to not render properly.

### Steps to Reproduce

**Expected behavior:**

HTML comments should not be included.

**Actual behavior:**

HTML comments are included.

### Versions

* **Rock Version:** n/a
* **Client Culture Setting:** n/a

**Comment by Tschrock** [comment]
I'd just like to mention that standard HTML tags **CAN** be multi-line, so the tag part of `StripHtml` should be updated as well.
