### ISSUE TITLE
Multiple Locations not printing on Labels if the locations are different

### ISSUE THREAD

**Issue by MCoulterFBCN** [SparkDevNetwork/Rock#3551]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
~A clear and concise description of what the bug is, include screenshots if applicable.~

### Steps to Reproduce
1. Setup Schedules for back to back events, like a Sunday School class followed by a Worship service.
1. Setup two locations for a single group to be able to check into.
1. Setup the Check-in Schedule so that group checks into one of those locations in one Schedule time and the other location in the other available time.
1. Make sure that a field for Schedules and/or Locations is mapped on a badge that will print for this Group.
1. Check in the child and select both Schedule time options.
1. The Label will print with only the first Schedule Location.  It makes it appear that the child was not checked into another location.  The database has recorded both locations properly.

Note: If you repeat the same steps with the same Location for both Schedules, the Label will print both Schedules and their Locations.

**Expected behavior:**

All Scheduled Locations a child checked into at the check-in station should be able to be printed on a single Label.

We utilize this information so teachers know for sure whether to move a child to another location or whether a parent will be picking them up and also for younger kids to help know which room they are supposed to be in without a system lookup.

**Actual behavior:**

Only the first Location prints on a Label when a child is checked into Schedules with different locations.

### Versions
* **Rock Version:** 8.5
* **Client Culture Setting:** en-US

**Comment by charlottedean** [comment]
If the child doesn't move locations, it prints fine, it's only when the child has to move locations between services.  We use this as we have multiple kids that stay for multiple services because their parents serve.

**Comment by MCoulterFBCN** [comment]
Working with Lee Peterson, it appears that this issue is actually occurring when the student checks into two different groups that are of two different group types.  If that is the case then only the first group checked into displays in the Lava code for the printed label.  The multiple rooms do not seem to have any impact on the issue.

**Comment by nairdo** [comment]
@MCoulterFBCN Each 'group type' has its own check-in labels, and a check-in label currently only knows the one group type from where it came.  And in your case, I understand you have a person checking into a location(s) and schedule(s) that are on two different group types....

So, although you can't get the locations from two different group types on one single label, you could get a label to print twice -- once for each location.  To do that you would change the label in question to **Print For Each** to "Location": 
![image](https://user-images.githubusercontent.com/383807/55369943-817c6780-54ad-11e9-9523-9f3af589cf1e.png)

Doing that should let you get the same kind of label for the same person for each location:
![image](https://user-images.githubusercontent.com/383807/55370460-63b00200-54af-11e9-96bf-0baf3e74e02f.png)

Does that seem like it would work for you?

**Comment by charlottedean** [comment]
This is how we have been working around this.  We love the functionality of only one sticker printing if they are in one location of the same group type though.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
