### ISSUE TITLE
Cannot delete schedules

### ISSUE THREAD

**Issue by dsmallman** [SparkDevNetwork/Rock#3552]
### Description
An error occurs when trying to delete a schedule that has attendance data related to it.

### Steps to Reproduce
1. Goto Admin Tools  > Check-in  > Schedules
2. Add a test schedule called "Thursday"
3. Go to a serving team.
4. Add that schedule to a serving team's meeting details
5. Add an attendance record for that meeting location and schedule.
6. Goto Admin Tools  > Check-in  > Schedules
7. Find the Thursday schedule and click Delete.
8. Click "OK" when asked "Are you sure you want to delete this schedule?"
9. Click "OK" when asked "This schedule has attendance history. Are you sure that you want to delete this schedule and all of its attendance history?"
10. Get error

**Expected behavior:**

The expected behavior is that the Schedule and Attendance data should have been removed.

**Actual behavior:**

An error occurs:
![image](https://user-images.githubusercontent.com/383807/82278593-739ed580-993f-11ea-88b9-23bb0a7e00e3.png)

### Versions
* **Rock Version:** Rock McKinley 8.5 (1.8.5.2)
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@dsmallman we need more information. Where are you trying to delete the schedule?

**Comment by dsmallman** [comment]
I will try to add my description as a comment as it will not let me edit the original very well.
When I try to remove/delete a check-in schedule, I get an error:
**Error**
The DELETE statement conflicted with the REFERENCE constraint "FK_dbo.Attendance_dbo.AttendanceOccurrence_OccurrenceId". The conflict occurred in database "rockdemo", table "dbo.Attendance", column 'OccurrenceId'. The statement has been terminated.
![image](https://user-images.githubusercontent.com/9287272/53127367-7da90d00-351f-11e9-897b-c2ff7ad44f76.png)
1) Goto Admin Tools >> Checkin >> Schedules
2) Select a schedule that has attendance data
3) Click Delete >> OK >> OK 
4) Get error

**Comment by dsmallman** [comment]
Hi Jon,

I must have been doing something wrong, because it was not taking me description.

I have since added a comment, did that help?

Don

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
