### ISSUE TITLE
Copying page tree can eventually cause deletion of binary files

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3554]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When a page or tree of pages is duplicated, all the attribute values for the pages and blocks are duplicated as well. This is good.

However, I have a block with an `Image` attribute. When I duplicated the page, that attribute value was duplicated. So now I have two blocks that both point to the same Binary File Guid. When I updated the duplicated block and uploaded a new file, I checked the database and it had marked the original Binary File as IsTemporary=true (to be deleted) - even though the original block still referenced that file.

This would probably have the same problem with page attributes as well.

As I think about it, this might have the same problem with matrix attributes. I think it would keep a reference to the original matrix attribute so you would end up editing the same thing no matter which page you were editing.

### Steps to Reproduce

1. With a block or page that has an Image or File attribute (the kind with the uploader), put an image in the original page's attribute value.
2. Duplicate the page.
3. Edit the duplicate page/block and upload a new file.
4. Check both pages and both show their respective images.
5. Check the database and notice that the original file is now marked as temporary.
5. Wait until the next day and then notice your original image is gone.

**Expected behavior:**

I'm not sure honestly.

**Actual behavior:**

Data vanishes without warning and I freak out.

### Versions

* **Rock Version:** 8.4
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
So just clarifying, we aren't actually fixing the problem, we're just informing people that their data **will** get corrupted if they copy a page?

**Comment by nairdo** [comment]
We decided that we were unwilling to make copies of certain data (such as the case attributes  file/image data).

**Comment by cabal95** [comment]
👍 Just wanted to make sure. I'll rethink all our usage of those attribute types on our pages/blocks since there isn't really a work around.
