### ISSUE TITLE
Landing Page missing If/Then statement for secondary image. 

### ISSUE THREAD

**Issue by kcirgjd** [SparkDevNetwork/Rock#3561]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
I beleive all of the layouts that have a "secondary image" on the rock landing pages are missing the If/then satement. This prevents people from changing the image away from what comes stock. 

### Steps to Reproduce

1. Upload a new "secondary image" to page attributes
2. Load landing page. 

**Expected behavior:**

The image I uploaded to show up. 

**Actual behavior:**

The stock image still stays. 
### Versions

* **Rock Version:** 8.5 & 9.0 (pre-alpha site)
* **Client Culture Setting:** Note applicalble

**Comment by mikejed** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/8fa3317120677e905c347b9903c6478e05cd49e1
