### ISSUE TITLE
Event Registration Address Blank

### ISSUE THREAD

**Issue by BemaDavidBensen** [SparkDevNetwork/Rock#3562]
### Description
If a non logged in person signs up for an event with an address that is being used somewhere else in the DB it will not save the address to thier account. This does not happen if the person is logged in, or if the address is a new address in the DB. I tested this heavily and it appears to be happening on 8.0 - 8.5. existingLocation on line 2674 appears to be throwing false positives. 

### Steps to Reproduce
1. Create a new event that allows people who are not logged in to register 
1. Create a new person with an email and no address 
1. Register for the event with matching information 
1. The address will be saved (assuming someone else in the DB doesn't already have the address)
1. Remove the address from the person record and re-sign up for the event
1. The address will not be saved. 

**Expected behavior:**

When a non logged in person registers for an event with no address it should save the new address

**Actual behavior:**

If the address already exists or has been on the person record in the past, it will not save the address. 

### Versions
* **Rock Version:** 8.0 - 8.2 - 8.5
* **Client Culture Setting:** En-US

**Comment by Tschrock** [comment]
I can confirm this is still happening in 8.8 (1.8.8.3) as well as on the prealpha server (10.0 (1.10.0.2)):
![firefox_2019-07-17_15-35-20](https://user-images.githubusercontent.com/2406499/61405760-95a37380-a8a8-11e9-9504-ee63f47c511c.png)

Link to the relevant code as mentioned by David:
https://github.com/SparkDevNetwork/Rock/blob/c287f14f76b84dbc75518352a942e90ff50591ff/RockWeb/Blocks/Event/RegistrationEntry.ascx.cs#L3025-L3044

Looks like it's only saving the address to the family when the address doesn't exist in the database.

**Comment by ethan-sparkdevnetwork** [comment]
The LocationService.Get( ... ) does not constrain the result to the provided Group, it searches the Group's locations first before searching all locations. The code Tyler points out assumes that the result would be for just the group.

Updated the block to add the found location to the family Group if the family Group does not have a location.

**Comment by ethan-sparkdevnetwork** [comment]
Updated the comments on the service method to remove any confusion on the group parameter's functionality.
