### ISSUE TITLE
New Line characters when doing xml path in stored procedure to html block

### ISSUE THREAD

**Issue by bobbrown** [SparkDevNetwork/Rock#3563]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
_no description given_

### Steps to Reproduce
I have included an SQL file with a sample stored procedure, a txt with the contents of the HTML block, and a txt with results and changes made to get around the issue
[RockRMSStoredProcedureIssue.zip ](https://github.com/SparkDevNetwork/Rock/files/2902108/RockRMSStoredProcedureIssue.zip)
Note: the problem happened in 8.5 and 8.6 but I had not done it with any earlier versions as I am new to RockRMS

1. Create an html block on the Person page with the following content {% sql  %} exec org_domain_sp_Person_Detail {{ Context.Person.Id }} {% endsql %} {% for item in results %} {{ item.html }} {% endfor %}
1.  Create stored procedure included in .ZIP file

1. Run the page

**Expected behavior:**

It is expected to have each line of the styling show up without extra characters

**Actual behavior:**

View source of the page where that shows and each new line from the xml will have the new line &#x0D; character in it in addition to the new line. It appears to only happen when the <style type="text/css"> is in there. If it isn't then it works as expected.

I modified my stored procedure to remove &#x0D; when doing the xml, so what I am trying to do is working with that little extra workaround.
#csstest_24 {&#x0D;
color: red;&#x0D;
}&#x0D;
#csstest_25 {&#x0D;
color: red;&#x0D;
}&#x0D;
#csstest_34 {&#x0D;
color: red;&#x0D;
}&#x0D;
#csstest_35 {&#x0D;
color: red;
&#x0D;
}&#x0D;

### Versions
Rock Version: Rock McKinley 8.6 (1.8.6.2)

Client Culture Setting: en-US

**Comment by nairdo** [comment]
Greetings @bobbrown, I think a screenshot is needed here.  I'm not sure I'm seeing what you might be seeing.

**Comment by tom-powers** [comment]
I tested this on the prealpha site and the extra characters are not there anymore, so I am saying that this is no longer a bug.

**Comment by nairdo** [comment]
Reported as resolved (somewhere between v9 and v11) in the #bugapalooza channel.
