### ISSUE TITLE
Rock Still Has a "Enable Run Jobs In IIS Context" Setting

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3564]
### Description

As of 8.6 (and prealpha) Rock still has a _Enable Run Jobs In IIS Context_ setting, which to my knowledge has been deprecated as it is no longer possible to run Rock Jobs as a Windows Service.

### Steps to Reproduce

1. Admin | System Settings | System Configuration | web.config settings
2. Observe there is a _Enable Run Jobs In IIS Context_ setting and the helptext references running the jobs as a service if you disable the setting, but (I think) this is no longer possible or supported.

**Expected behavior:**

Setting would not be an option as there is no longer an alternative to running jobs in IIS. Alternatively, if this is now meant to be a "disable jobs" master switch, the wording and helptext should be modified to reflect that.

**Actual behavior:**

The setting and helptext are misleading.

### Versions

* **Rock Version:** All
![image](https://user-images.githubusercontent.com/3903408/53373712-e0cde180-391b-11e9-947e-779e587e12a4.png)

**Comment by nairdo** [comment]
@JimMichael To be clear, we're definitely keeping this setting because anyone using multiple Rock web server instances needs to be able control this and have the Jobs run on only one instance.
