### ISSUE TITLE
Interacting With Matrix Attributes on Content Channel Item Publish Page De-Selects Status UI

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#3565]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
While editing a content channel item with a matrix attribute, interacting (adding/editing/deleting a row) with any matrix item removes the active classes from the item status UI.

Before interacting with matrix attribute:
![<a href](https://user-images.githubusercontent.com/2465823/53437549-c94e3180-39cb-11e9-99c4-f3210686f358.png)

After interacting with matrix attribute:
![<a href="](https://user-images.githubusercontent.com/2465823/53437526-c05d6000-39cb-11e9-8cb9-08180de0fa76.png) 

### Steps to Reproduce
1. Edit any content channel item that has a matrix attribute
1. View status UI correctly set
1. Add/Edit/Delete a row on any matrix attribute
1. View status UI with no active classes.

**Expected behavior:**

Visual state of content channel item status UI could stay consistent unless if it changed by the user.

**Actual behavior:**

Visual state of content channel item status UI isn't consistent when interacting with a matrix attribute.

### Versions
* **Rock Version:** 9.0 (1.9.0.14)
* **Client Culture Setting:** en-US

**Comment by chead4** [comment]
@briankalwat I am closing this issue as I am unable to recreate this issue on rocksolidchurchdemo.com.  Please feel free to reopen.

**Comment by briankalwat** [comment]
@chead4 Hey Colleen, I just double-checked this on the pre-alpha Rock instance (currently on 17.0.3), and this is still happening. I've created a screen recording showing it happening: https://drive.google.com/file/d/1NzmrAPwGy6uyFCja7d3T0ZNNtNVB2lqu/view?usp=sharing

**Comment by chead4** [comment]
@briankalwat Thank you for getting back to me Brian.  We have recreated the issue and looking into it.
