### ISSUE TITLE
Registration Campus Value does not populate to person record

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#3566]
### Description
Create a Form Field on a registration template and use a Person Field and do Campus.

### Steps to Reproduce
1. create a new registration template
1. Add a "question" that is a Person Field of Campus
1. Add a registration instance.
1.  Fill out the registration as a Person who does not exist in Rock.
1. No Campus is assigned to that new family/person record

**Expected behavior:**

The campus value should be applied to the family that is created for the new person

**Actual behavior:**

The new person is created without a campus

### Versions
* **Rock Version:** [8.3]
* **Client Culture Setting:** [en-us]

**Comment by ToxicFume** [comment]
I can confirm that I am experiencing the same issue.

**Comment by nairdo** [comment]
Hi @markewampler and @ToxicFume ... Our bugapalooza event team is reporting this issue is resolved (possibly in v9-v9.1)  If you want to challenge this and re-test yourself in a v9.1 environment, please re-open this issue and include as many new details as possible.

**Comment by jcjones37** [comment]
@nairdo I am experiencing this in v10.2 on my local instance as well as the demo site.  What are the chances this bug has been revived?

**Comment by MichaelAllen** [comment]
I am able to duplicate this on both v9.4 and v10.2, but only if I set the option "Registrants in the same family" to "Yes". Otherwise, the campus assignment works as expected.

**Comment by treusch** [comment]
We are experiencing this issue. We are still on v9.2 and we have our option set to ask if people are in the same family.
