### ISSUE TITLE
Scripturize Lava Shortcode Generates Broken URLs to Chapter Range References

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#3567]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Using the Scripturize lava shortcode with a reference to a chapter range generates a broken link.

### Steps to Reproduce

1. Wrap the Scripturize shortcode tags around a scripture reference chapter range (ex Exodus 1-16).
2. Visit generated link. (Not Found)

**Expected behavior:**

Scripturize shortcode should either generate a valid link for chapter ranges, or not generate a link at all.

**Actual behavior:**

Scripturize shortcode generates a broken link.

### Versions

* **Rock Version:** 9.0 (1.9.0.14)
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
We'll probably need to not render them at all as many services don't allow for multiple chapters and those that due have limits to how many you can show.

**Comment by briankalwat** [comment]
@edmistj would it be possible to link the book and chapter on each end of the range? For example, Exodus 1-5 would link `Exodus 1` and the `5` to the corresponding chapters?

**Comment by edmistj** [comment]
That would be tricky, but I think people would be frustrated that 2-4 were not available. Think we'd get another issue opened for that.

**Comment by briankalwat** [comment]
@edmistj honestly just even linking the first chapter of the range would be helpful, because it would get people to the right starting point, but I trust you and what you think is best!
