### ISSUE TITLE
Inactive Attributes Showing up as Report Fields

### ISSUE THREAD

**Issue by cj-walk** [SparkDevNetwork/Rock#3568]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it at https://www.rockrms.com/Rock/Ask or via Slack https://www.rockrms.com/slack

If you're looking for support for Rock there are a lot of options, check out:

* User Documentation &mdash; [Rock Manuals](https://www.rockrms.com/Learn/Documentation)
* Q&A Message Boards &mdash; [Ask Rock, Q&A](https://www.rockrms.com/Rock/Ask)
* Chat &mdash; [Join the Rock Community on Slack](https://www.rockrms.com/slack)
* Developer Documentation &mdash; [Rock Developer Documentation](https://www.rockrms.com/Developer)
* FAQ &mdash; [Rock FAQs](https://www.rockrms.com/faq)
* Full Service, Paid Support &mdash; [Rock Partners](https://www.rockrms.com/Partners?Category=13)

**Comment by nairdo** [comment]
I'm assuming this was a test. :)
