### ISSUE TITLE
Group Detail Lava block allows editing attributes even with no security access

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3569]
### Description
If your Small Groups `Group Type` has a Group Attribute defined on it that is meant to internal use only, that is security is set to deny all users but allow staff to view, it will still show up and be editable on the Group Detail Lava block.

### Steps to Reproduce
1. Edit `Small Groups` group type
1. Add a Group Attribute
1. Lock security to staff view only
1. Login to group leader toolbox as a regular, non-staff user, and notice you can edit the attribute.

**Expected behavior:**

End users should not be able to edit group attributes that have been explicitly locked down.

**Actual behavior:**

Small group leaders can see internal attributes.

### Versions
* **Rock Version:** ~6.4~ 8.4
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1202800247519720">image.png</a>

**Comment by nairdo** [comment]
@cabal95 Are you saying this is only happening in Rock v6.4 or have you confirmed it's been happening since v6.4 and is still happening.

**Comment by cabal95** [comment]
hah, sorry that was supposed to be 8.4 😆

**Comment by jennifertroeger** [comment]
We are on 8.5 and noticed this with group member attributes as well (not group attribute)... If you are a fundraising group participant and log in to edit your opportunity introduction, you will see (and can edit) other internal-only group member attribute fields as well.

**Comment by sam-crisp** [comment]
on 8.5 and 8.6 using the regular Group Details block, we can see all group attributes regardless of IsActive status or security settings in the lava detail (set by Group Type)

**Comment by nairdo** [comment]
This issue should now be resolved in v13.7 via https://github.com/SparkDevNetwork/Rock/commit/6f14c1401903489f7d0c55a22d7fa996c7f303e3 

...which can now be seen on the PreAlpha site:

![image](https://user-images.githubusercontent.com/383807/185515688-ca553217-e182-43c6-9862-0e3d0044b162.png)

Please note however that the Attributes/AttributeValues that are displayed for view via the block's Lava Template setting (`{% include '~~/Assets/Lava/GroupDetail.lava' %}`) are still the responsibility of the Lava editor/administrator to decide how they want to handle them.  This was noted a few versions back in the [Lava docs section on Attribute Filters](https://community.rockrms.com/lava/filters/attribute-filters):

![image](https://user-images.githubusercontent.com/383807/185515938-8471a191-6a60-4a59-9293-b93baeb8db47.png)
