### ISSUE TITLE
Merge documents does not honor selected people from data views

### ISSUE THREAD

**Issue by BemaDavidBensen** [SparkDevNetwork/Rock#3573]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When a merge document is created from a data view, all people in the data view are pulled. 

### Steps to Reproduce
1. Go to a data view
1. Checkmark a few people 
1. Hit "Merge Records into Merge Template" 

**Expected behavior:**

Only the people selected in the data view or report should be shown in the  Merge Template

**Actual behavior:**

All people in the data view or report are shown in the merge template 

### Versions
* **Rock Version:** 8.6
* **Client Culture Setting:** en-us

**Comment by luke-infoministry** [comment]
We're seeing the same behavior. 
Merge templates seem to behave as expected from the group viewer and the event registrations - registrants tab

Merge templates are applying to all rows on reports, data views and tagged people grid of the tags page.

**Comment by mkinyon** [comment]
We're also seeing the same thing when selecting rows on a Report.
Version: v8.7

**Comment by MicahO** [comment]
We are also seeing this in Reports and Data Views in 8.7.

**Comment by HansenGrace** [comment]
Thanks for your input. We will add this into our pipeline for next steps.

**Comment by nairdo** [comment]
Looks like this was related to #3593 and was recently fixed for the upcomign v8.8 release https://github.com/SparkDevNetwork/Rock/commit/0b0e491605e972ae882e901781229f9eaf28afeb
