### ISSUE TITLE
Signal note viewable by users without view permissions

### ISSUE THREAD

**Issue by sichiriu** [SparkDevNetwork/Rock#3576]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * [x] Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * [x] Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * [x] Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
Users without view permissions to a signal can see the note created by the signal owner.

### Steps to Reproduce
1. Create a signal and restrict its View permissions to certain roles
1. View the Signal List block as a user without one of those roles

**Expected behavior:**

Signal Name, Owner, and possibly Expiration Date are shown. Note field is not shown.

**Actual behavior:**

All signal fields, including note, are visible.

### Versions
* **Rock Version:** 1.8.6.2
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
I just checked the code, and indeed the `Note` column is supposed to be blank when they don't have `View` permission to the signal.

I'll see if I can replicate this on my dev environment to see why it's allowing access.
