### ISSUE TITLE
8.7alpha Breaks FontAwesome Pro

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3583]
### Description
On my test copy of prod, upgrading from 8.6 to 8.7alpha breaks FontAwesome Pro icons. I cannot try to dupe this on demo without entering my FA Pro key, which I'm not willing to do. Furthermore, when I then tried to install the FA Pro 5.7.2 zip it timed out (and presumably didn't install)

### Steps to Reproduce
1. Upgrade from 8.6 to 8.7alpha
1. Observe that FA Pro icons no longer render
1. Try to install FA Pro 5.7.2
1. Observe that it times out. Installing the exact same zip file on 8.6 (on the same exact VM) takes only seconds for me.

**Expected behavior:**

FA Pro icons would render and installing a new copy of FA pro would not time out.

**Actual behavior:**

It breaks. This is what my 8.6 server menu looks like:
![image](https://user-images.githubusercontent.com/3903408/54241565-59719800-44ef-11e9-9c4c-5aa02f7085d3.png)

And this is what it looks like immediately after applying 8.7alpha:
![image](https://user-images.githubusercontent.com/3903408/54241586-71e1b280-44ef-11e9-9459-dfd5a0c03ccc.png)

And after a minute and a few page reloads it then goes to this:
![image](https://user-images.githubusercontent.com/3903408/54241608-845bec00-44ef-11e9-9a28-10f572306571.png)

Finally, after trying to re-install FA Pro 5.7.2 zip I get this:
![image](https://user-images.githubusercontent.com/3903408/54241627-9473cb80-44ef-11e9-9916-5f72a3cb058e.png)

Note this if after uploading the file and clicking Update. IIS runs at 50% for 5min and times out.

### Versions
* **Rock Version:** 8.7alpha

**Comment by JimMichael** [comment]
Note also that I tried saving/compiling the Rock theme multiple times with no effect.

**Comment by JimMichael** [comment]
Argh! This appears to be yet-another browser caching issue. It works fine on the same browser in an incognito window, and on other browsers. Only the one I was testing on had this broken icon.

HOWEVER, the upload issue is still happening... I cannot get FA 5.7.2 zip to apply to 8.7alpha via any browser.

**Comment by shivambareria** [comment]
Fixed in https://github.com/SparkDevNetwork/Rock/commit/153ed851f132c3ece3b2a53df1a3ad3ab1799f97

**Comment by nairdo** [comment]
@JimMichael We're still looking into this to figure out why the .css file timestamping is not working to signal the client browser to re-fetch the latest assets.  This may miss the 8.7 deadline beta deadline -- but I'm going to try my best.

**Comment by JimMichael** [comment]
Thanks Nick! I'm actually more concerned about the 5.7.2 zip file not completing to update on 8.7alpha... I don't see that Shivam's fix above addresses that in any way, but maybe I'm missing something?

**Comment by nairdo** [comment]
We _were_ attempting to automatically recompile *all* themes however that can take a very long time. That's why this line (`RockTheme.CompileAll()`) was removed here: https://github.com/SparkDevNetwork/Rock/commit/153ed851f132c3ece3b2a53df1a3ad3ab1799f97#diff-7cdc023f1bdb15859e67a64de8ac800fL105

I have not yet been able to get to the bottom of why the browser / server has aggressively cached the file incorrectly.  Here's the dev tools showing the same file, coming from the same server, each with different response details (left is incorrect, right/incognito is correct):
![image](https://user-images.githubusercontent.com/383807/54311273-79f22e80-4591-11e9-99d2-f06b8ded0cb6.png)

**Comment by JimMichael** [comment]
Ok, but just for clarity... was that "attempting to recompile all themes" a new 8.7 feature? The reason I ask is that the same file on 8.6 takes mere seconds to update after uploading the zip... so is the new fix just reverting back to original behavior, instead of trying to be fancy and recompile them automatically?

**Comment by nairdo** [comment]
Not quite.  A different commit (28 days ago; https://github.com/SparkDevNetwork/Rock/commit/e629a67d04758e11d566708f94a4bb3e51923ce0#diff-7cdc023f1bdb15859e67a64de8ac800f), was an attempt to fix the 'icons not showing up'.

**Comment by nairdo** [comment]
Reported as resolved (in v9.x) in the #bugapalooza channel.
```
Josiah Rocke 10:46 AM
https://github.com/SparkDevNetwork/Rock/issues/3583 is no longer an issue (tested on demo)
```

@JimMichael Please let us know by reopening if you feel this is closed in error.
