### ISSUE TITLE
Event Registration browser back button updates registration

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#3584]
### Description
If a registration is completed and the user uses the back button to start over and complete a new registration, the original registration gets overwritten. Even if modify existing registration is not allowed. 

### Steps to Reproduce
1. Complete an event registration and get the confirmation message
1. The person you just registered will be in the Registrants list on the registration instance.
1. Use your browser's back button to return to the first registration page
1. Update the fields
1. Complete the registration
1. Refresh the Registrants list and the original person is gone updated to the new person. 

**Expected behavior:**

Since they are not allowed to update a registration, I would expect some kind of warning. Or that if they used back, it would start a new registration instead of modifying the existing one.

**Actual behavior:**

The registration just keeps updating.

### Versions
* **Rock Version:** [8.6]
* **Client Culture Setting:** [en-us]

**Comment by JimMichael** [comment]
I wonder if it makes sense to simply disable browser back during the event registration steps. We've had to do that on complex multi-form workflows for similar reasons.

**Comment by KelleyLangkamp** [comment]
Further testing yesterday showed that this is only an issue on free registrations. If the event has a cost and they hit the back button, they get a message that they have already completed the registration.
