### ISSUE TITLE
Fundraising Matching Block Settings

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#3586]
### Prerequisites
* [ x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?

### Description
Fundraising Matching does not respect the block setting of "Transaction Type"
![image](https://user-images.githubusercontent.com/657005/54310949-97c78f80-45a1-11e9-96c7-924fccb38873.png)

### Steps to Reproduce
1. Go to Fundraising Matching
1. Click on block settings
1. Restrict it to just Contributions
1. Select a batch that has Event Registrations in it.
1. Event Transactions are still shown.

**Expected behavior:**

Only Contributions are shown.

**Actual behavior:**

Contributions and Event Transactions are shown.

![image](https://user-images.githubusercontent.com/657005/54311052-ce9da580-45a1-11e9-84f7-6bf6111a3452.png)

### Versions
Rock Version: Rock McKinley 8.6 (1.8.6.2)

Client Culture Setting: en-US

**Comment by kyeschung** [comment]
I don't think that is what that "Transaction Type" is for. 
![this is what that is for    not a filter](https://user-images.githubusercontent.com/25948194/54733607-b4db0000-4b57-11e9-9f2c-ffe2001a8b4c.png)

**Comment by cabal95** [comment]
The code seems to agree with @kyeschung 's screenshot. The `Transaction Type` is not a filter, but rather what to change the Transaction Type _to_ when you match a transaction. Though the Help text should probably be updated to make this more clear.

**Comment by nairdo** [comment]
I am updating the Help text in that block to the following: "This is the Transaction Type that the financial transaction detail record will be set to when a match is made. If you do not wish to change the original value, leave this setting blank."
