### ISSUE TITLE
Rock Job Schedule Service External Application Still Exists

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3588]
### Description

The _Rock Job Scheduler Service_ external application still exists in Rock installs, even though it was long ago deprecated and is no longer supported.

### Steps to Reproduce

1. Go to Admin | Power Tools | External Applications
2. Observe you can still download the _Rock Job Scheduler Service_

![image](https://user-images.githubusercontent.com/3903408/54314702-55ef1700-45aa-11e9-8041-51d358348b06.png)

**Expected behavior:**
The Rock Job Scheduler service installer would no longer be available, because it's no longer supported or enhanced.

**Actual behavior:**

It is still available, which is misleading.

### Versions

* **Rock Version:** All

**Comment by edmistj** [comment]
@JimMichael good catch Jim. We'll get this removed.
