### ISSUE TITLE
8.7beta Communication Wizard Change Discussion

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3591]
### Description
I just noticed that on 8.7beta, creating a new Wizard-based Communication now forces you to enter From Name and Email, as well as Subject (they are all blank now, if you pick a template where they are blank). I know this is a result of my issue https://github.com/SparkDevNetwork/Rock/issues/3516 but I think this is an unintended consequence many are going to complain about vs. the default of always pre-populating From Name and Address as the sender creating the communication (unless you pick a template that overrides them) 

I THOUGHT I was asking to fix the issue where you start a new comm, switch to a template that HAPPENS to have pre-populated from Name, Address, and Subject, and then when switch back to another template (with blank From Name/Email) and it keeping the info from the first template that you chose... but it looks like **we should have made from Name and Email the _sender_ if they are blank on the template** instead of just blanking everything outright.

Thoughts? Do you think the typical Rock org is going to have a fit about this new behavior, since they have to enter their name AND email (and get it right) every time they use the Wizard? 

### Steps to Reproduce
1. Go to People | New Communication
1. Pick a template that doesn't have any baked-in From Name and Email
1. Observe that you now have to enter these yourself, whereas before the From Name/Email were always you (the sender) UNLESS the template had them baked-in.

**Expected behavior:**

From Name and Email would be "me" unless I pick a template that has baked-in From Name/Email.

**Actual behavior:**

It's always blank if you pick a template without baked-in info.

### Versions
* **Rock Version:** 8.7beta

**Comment by timlem** [comment]
Just FYI I've had 4 staff members complain about this since updating. :) Just throwing my 2 cents in since it's labeled as discussion. 

Thank you Spark Team!

**Comment by edmistj** [comment]
We'll move up the discussion on this.

**Comment by craigmash** [comment]
I will add my voice that this is a bit disruptive. Would really prefer to have it auto populate again.

**Comment by nairdo** [comment]
We are going to do something someone suggested elsewhere.  We're going to change it so that you can place lava in the field so it can be rendered during the wizard steps.  That will allow an admin to use something like {{ CurrentPerson.FirstName }} and {{ CurrentPerson.Email }} to use the current person's details when they deem appropriate on certain templates.

**Comment by TheCoreyHall** [comment]
Any idea what version a fix for this would be implemented in?

**Comment by HansenGrace** [comment]
Coming soon, the fix is currently in process.
