### ISSUE TITLE
Group History continues for Inactive Groups

### ISSUE THREAD

**Issue by MicahO** [SparkDevNetwork/Rock#3592]
### Description
**Groups that are marked "Inactive" continue to accumulate Group History while inactive.** The only way to make the group show as ended on an individual's Group History tab is to **archive every member of the inactive group.** This is not optimal, because it becomes difficult to record their membership in the now-completed group. While this is possibly intended behavior, it seems more likely that this is a bug. 

For example, consider a person who attended a 12-week group that met weekly with attendance recorded every week. If the class was moved to "Inactive" when it completed, we'd expect a participant to show 12 weeks of group membership. Instead, we show group membership up until the present day, even if the 12-week group was years ago.

### Steps to Reproduce
1. Go to any group that has a group type with history enabled (ie, Small Groups or Serving Groups).
1. Uncheck "Is Active" in the group details.
1. Wait a month.
1. Go to the profile for a person in that group, click the "Groups" tab, and see that their membership is still current.

**Expected behavior:**

Group membership should not show as current if the group is not currently active.

**Actual behavior:**

Group member shows as current unless/until a person is removed from the group.

### Versions
* **Rock Version:** [8.6]
* **Client Culture Setting:** [en-us]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1118162893213481">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1118162893213483">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1118162893213485">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1118162893213487">image.png</a>

**Comment by nairdo** [comment]
Oops. It looks like we may have missed referencing this issue number when we made adjustments to the code today: https://github.com/sparkdevnetwork/rock/commit/b811ea3566278e360a7ee5c92f5968548042e0c4

**Comment by MikeDPeterson** [comment]
Fixed in 1.9.1 with https://github.com/sparkdevnetwork/rock/commit/597fb1ee25d228b33548411c44b17a1290f2b3d3
