### ISSUE TITLE
Google Maps Icons Broken

### ISSUE THREAD

**Issue by andrewsohc** [SparkDevNetwork/Rock#3596]
Map icons have disappeared from the Group Finder block.  According to Google Developer docs this feature was cut off March 18

https://developers.google.com/chart/image/docs/gallery/dynamic_icons
Warning: This API is deprecated in 2012 and was turned off on March 18, 2019. Please use the actively maintained Google Charts API instead. 

### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce
1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior:**

**Actual behavior:**

A description of what actually happened.

### Versions
* **Rock Version:** [Enter Rock version here]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by nairdo** [comment]
Hi @andrewsohc or @Tschrock , would you two be able to paste in a screenshot of what you're seeing so we can get a better idea of what 'Maps Icons' you're saying are broken and perhaps the steps to reproduce this issue?

From the [prealpha demo server](https://prealpha.rocksolidchurchdemo.com/page/236), this is what I see:
![image](https://user-images.githubusercontent.com/383807/54774788-c2c96900-4bc9-11e9-9772-f4f441c750ad.png)

**Comment by Tschrock** [comment]
As of the time of this comment, Google has temporarily re-enabled the API - that's why things are working. There's no timeline on how long that will last.

For the full discussion, see https://groups.google.com/forum/#!topic/google-chart-api/rZtHTyYgyXI:
