### ISSUE TITLE
Permission Error GetEventCalendarFeed.ashx

### ISSUE THREAD

**Issue by randyjreed** [SparkDevNetwork/Rock#3597]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
GetEventCalendarFeed.ashx throws a 403 error when accessing the page.

### Steps to Reproduce
1. Go to 'https://rock.rocksolidchurchdemo.com/page/395?EventCalendarId=1'
1. Click on 'Export Calendar Feed'
1. Access the copied link
1. See 403 error

![Screen Shot 2019-03-19 at 2 38 14 PM](https://user-images.githubusercontent.com/22873346/54643672-b66fcf80-4a54-11e9-9971-b4dc93ae5e74.png)

**Expected behavior:**

This should produce an ics file and allow a user access.

**Actual behavior:**

403 Error is returned and file is not accessible.

### Versions
* **Rock Version:** [8.6]
* **Client Culture Setting:** [en-US]

**Comment by cabal95** [comment]
Confirmed on rock demo site and my own server. I don't see what specifically is causing this in the code, it seems to be properly checking and security on the calendar looks correct.

**Comment by ethan-sparkdevnetwork** [comment]
Fixed to allow unauthenticated users to access public calendars (e.g. Allow View permission for "All Users" without Deny View for "Unauthenticated Users").

Ensure security settings for internal calendars.

**Comment by nairdo** [comment]
@randyjreed This commit above (619c6878ecc8dbb7b3ebde3d376b261cf3c0c13d) addresses making existing calendar feed URLs work for _public_ calendars (that is calendars with VIEW for 'All Users').  You could grab that file if you wanted to do an immediate test of that fix.

We have not addressed trying to make a non-public calendar (a calendar that does _not_ have VIEW for 'All Users') work under situations where the person is not logged in -- in other words, in situations where that calendar feed is being fetched by some third-party agent/software.
