### ISSUE TITLE
Fundraising Matching - Removes Event Registration association from transaction

### ISSUE THREAD

**Issue by kyeschung** [SparkDevNetwork/Rock#3599]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
After you use the Fundraising Matching block, any of the transactions that are in that open batch will all removed from the Event Registration transactions. 

### Steps to Reproduce
1. Go to Fundraising Matching 
1. Select an Open Batch
1. Assign a Group Member for the transaction 
1. Go to Event Registration of any person that was in that open batch and see that all their payments to that specific event has been zero'ed out. 

**Expected behavior:**

Fundraising Matching should not cause the transactions to be disassociated from the event registration. And it's for all of the transaction that are in the open batch that was used for the fundraising matching. So if there was ONE transaction that we needed to match to fundraising in an open batch that had 10 transactions and 9 transaction were associated to a camp that was an event registration that people made payments toward, as soon, as you hit save on the Fundraising Matching page, all 9 of those payments will be zeroed out.

**Actual behavior:**

Event Payments in the same open batch shouldn't be affected by Fundraising Matching.

### Versions
* **Rock Version:** 8.6
* **Client Culture Setting:** en-US

**Comment by kyeschung** [comment]
Austin Spooner has had the same problem. This has been so frustrating for the last year and I couldn't figure out what was triggering it, but figured it out and reporting the issue to hopefully be fixed asap.

**Comment by kyeschung** [comment]
Would it be ok for me to get somebody to fix and submit a PR for it? We need this more urgently as this has been a major issue.

**Comment by austinspooner** [comment]
Hey guys, we are seeing this same issue. The sooner the better on a fix for it. We can stop using fundraising matching until its fixed though.

**Comment by ricsrock** [comment]
Just chiming in here. We are experiencing the same issue. Thanks!
