### ISSUE TITLE
Title Covered Up on Left Menu Bar when Using Safari (Mac OS X)

### ISSUE THREAD

**Issue by sam-crisp** [SparkDevNetwork/Rock#3600]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Left Menu Bar does not show Nav-Page Title on Top in Safari (Mac OS X)

### Steps to Reproduce
1. Using a Mac, open Safari and navigate to Rock.
1. Sign In
1. Hover over any Left Menu Navigation Item to display page links in panel.
1. There is no title being displayed on the top of the Item List panel.

**Expected behavior:**

A Title should appear above the list of page links showing the name of the navigation item
![Screen Shot 2019-03-21 at 1 52 52 PM](https://user-images.githubusercontent.com/44408754/54777894-56f2fa80-4be1-11e9-9172-645eb67f57a7.png)

**Actual behavior:**

The Title is covered up by the horizontal header bar when using Safari browser. 
![Screen Shot 2019-03-21 at 1 52 02 PM](https://user-images.githubusercontent.com/44408754/54777889-5195b000-4be1-11e9-9920-63e3efb15e23.png)

### Versions
* **Rock Version:** [Rock McKinley 8.6 (1.8.6.2)]
* **Client Culture Setting:** [en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1116369284286456">image.png</a>

**Comment by cabal95** [comment]
Confirmed on Mac OS X 10.14.3 using Safari 12.0.3.

Tested on Mac with Firefox and Chrome, they both worked fine.

**Comment by garrettjohnson** [comment]
Looks like this bug is directly related to a webkit issue stemming from the ability to scroll the navigation bar https://bugs.webkit.org/show_bug.cgi?id=160953.

Will commit a Safari targeted fix to offset the secondary nav so that it displays below the top navbar. The browser targeting is very brittle so hopefully the webkit team fixes the bug soon.
