### ISSUE TITLE
Giving Analytics Account Selector not allowing multiple selections

### ISSUE THREAD

**Issue by atorrance** [SparkDevNetwork/Rock#3601]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
The Account Selector on the Giving Analytics page on 8.7 only allows one account to be selected or all accounts can be selected **if the Filter Column Direction is set to horizontal**, users can no longer multi-select a variety of accounts at their choosing. If the Filter Column Direction is set to Vertical, users can select multiple accounts. 
![givinganalytics](https://user-images.githubusercontent.com/34725020/54779938-dfc46300-4bee-11e9-9139-9f40d54d30e9.gif)

### Steps to Reproduce
1. Go to the Giving Analytics page
1. Click on a Account and then click on another account, it will de-select your first option selected.

**Expected behavior:**

Users should be able to select multiple accounts in any order. 

**Actual behavior:**

Only one giving account or all accounts can be selected at a time, users can no longer multi-select a variety of accounts. 

### Versions
* **Rock Version:** [8.7 & 9.0]
* **Client Culture Setting:** [en-US]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1115785169794073">givingAnalyticsMultiSelect.gif</a>

**Comment by timlem** [comment]
Can this get high priority or a quick fix until a new feature is out? This is really messing up our finance teams weekly tasks

**Comment by JimMichael** [comment]
You do realize you can fix it just by changing the display from horizontal to vertical, right? It's only a problem in one display mode.

**Comment by timlem** [comment]
@JimMichael Thanks Jim - missed that ;)
