### ISSUE TITLE
"Is Archived" Groups Data View Filter Results in Blank Data View

### ISSUE THREAD

**Issue by shelbysubia** [SparkDevNetwork/Rock#3615]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers ](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [ X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
[Description of the bug or feature. Include screenshots if applicable.]

### Steps to Reproduce
1. Archive a Group if no groups are archived yet on your Rock instance
1. Create a New Groups Data View Titled "Archived Groups"
1. Create the Data View Filter: "Is Archived Equal To Yes"
1. Click Save

**Expected behavior:**

You expect the Data View to result in a list of all the groups (of any group type) that have been archived.

Jim Michael and I determined that using SQL command ```SELECT
 *
FROM
 [Group]
Where IsArchived = 'True'``` _does_ work correctly, though.

**Actual behavior:**

The Data View found 0 results

### Versions
* **Rock Version:** 8.6 & 8.7 (I produced this problem on my church's instance as well as the demo site)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
I'll check on this, but I don't believe that field (nor the _Archived Date Time_ or _Archived By Person Alias Id_) was intended to show up for selection in a Data View.  Archived groups can only be seen using very specific, specialized methods.  If I'm correct, that field (and the other two related ones) will probably need to be removed from the list of fields to choose from.

**Comment by shelbysubia** [comment]
No problem at all! That makes sense to me 😊 I figured it was either supposed to display and wasn’t working because of a bug, or wasn’t supposed to be displayed but was visible due to a bug.

Thanks for the update!


Shelby Subia
Rock Database Manager
The Father’s House | TFH.org
E: Shelby.Subia@tfh.org<mailto:Shelby.Evans@tfh.org>
P: (707) 205-1575
