### ISSUE TITLE
Archiving Group Doesn't Archive GroupMembers

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#3619]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When a Group Is Archived, the GroupMembers are left Unarchived. If Archival is supposed to be an in-place replacement for deleting, I believe that GroupMembers should be Archived at the same time.

### Steps to Reproduce

1. Create, or use an Existing Group of a GroupType with Group History enabled.
2. If no one in the Group has the archival option in their row, then run the Group History job.
3. Archive the Group
4. Query for GroupMembers of the person that aren't archived, and find the GroupMember of the Group you just archived.
5. Watch the group history continue to be recorded for the Group that has been Archived.

**Expected behavior:**

I expected that everyone who isn't yet archived within a Group would be Archived at the same time of the Group.  I also expected that Unarchiving a Group would restore everyone who was not yet Archived at the time the Group was Archived.

**Actual behavior:**

Unarchived members of a Group will remain Unarchived indefinitely, and continue to record Group History.  As far as I have checked in Lava, they don't show up there, but still in Group History, and in SQL.

**I'm willing to submit a PR for this change!**

And would like to know how you guys would prefer determining if a GroupMember of should be Unarchvied when its Group is Unarchived.  You could use GroupMembers of the Group being unarchived that were archived at the same time as the Group, or you could include extra information on the GroupMember record that lets Rock know that it was archived with the Group..  Also, there could be an option to Unarchive them with the Group or not.  I've though of a few options, and I'm looking for your thoughts and feedback.  Thanks!

### Versions

* **Rock Version:** 8.6 (Demo Site)
* **Client Culture Setting:** en-us

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1115997772534831">Clipboard - March 27, 2019 9_51 AM.png</a>

**Comment by nairdo** [comment]
Hi @NuclearTacos , this topic did come up during the initial design of the Group History feature and it was intentionally decided that archiving a group would not automatically archive the group membership.  When you say "and [they] continue to record Group History." are  you saying you are having a situation that is causing history **to be written** for those group members?

**Comment by NuclearTacos** [comment]
To elaborate a little, on the demo site, I made the following changes and ran the Process Group History job after each change.

1. Added a Group Member (noted it's Id for query)
2. Archived the Group
3. Unarchived the Group
4. Archived the GroupMember

![image](https://user-images.githubusercontent.com/19762670/55089142-f3524c80-507a-11e9-9b9a-2cea5ab9a4a2.png)

The bottom row was created when the member was added (and then the history was processed).  The top row was created when the GroupMember was archived (and the history was processed).

---

From my (admittedly limited) perspective, it looks like the goal behind not archiving the GroupMembers with their Group being archived is so that when the Group is unarchived, the GroupMembers can be restored with it.  Which I'm all for!

---

And again, with my limited perspective, I see the `| Groups` filter was updated to check if the GroupMembers being returned are a part of an Archived Group.  And, if I understand what I'm reading correctly, that check wouldn't need to be performed if the GroupMembers would be archived with their Groups. 

And that was one of the beautiful things I saw with the introduction of Archiving with the GroupService and GroupMemberService didn't require you to update your code to make it ignored Archived entities.

So that's why I thought this behavior was a bug.  I'm fine with it either way.  This is my 2 cents.

**Comment by NuclearTacos** [comment]
And here's how I discovered the issue.

The In Group of GroupType filter was returning a Person being in an Active Group of The GroupType, but the Group was Archived.  The only non-sql way I could see why they were was that they still had Person history running for that Archived Group, so that's why I started digging around in the database.

![image](https://user-images.githubusercontent.com/19762670/55092650-ea647980-5080-11e9-9dba-555d2cb922df.png)

**Comment by nairdo** [comment]
Thanks @NuclearTacos, we did find and fix (https://github.com/SparkDevNetwork/Rock/commit/47f62e1465805729d9420e236bbc09b764e205ec#diff-dfe3cfbf23126c584204dbba9125ef67) that **In Group of Group Type** filter issue a few weeks ago, but as you've already identified, the framework applies a filter ([seen here](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/GroupMember.cs#L960)) to all the group member queries to automatically exclude IsArchived members.
