### ISSUE TITLE
Excel Export of Event Registration Registrants produces HTML

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3621]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you have a Registration Attribute on a Form of type Boolean, and set it to Show On Grid so that you can export it, then use the Export to Excel feature on the grid it shows the HTML `<i class="fa fa-check"></i>` instead of a Yes/True/Whatever.

### Steps to Reproduce

1. Create a new registration template
2. Add a Registration Attribute form field of type Boolean and tic Show on Grid
3. Add somebody to the registration and select "Yes" for that attribute.
4. Go to the Registrants tab of the Registration Instance Details
5. Notice a check-mark shows for that column.
6. Export to Excel.
7. Notice you now see HTML.

**Expected behavior:**

The formatted Text value of the boolean attribute should be displayed (Yes/No).

**Actual behavior:**

HTML is presented to the user in their Excel file which makes no sense to them.

### Versions

* **Rock Version:** 8.6
* **Client Culture Setting:** en-US

**Comment by shivambareria** [comment]
Fixed in https://github.com/SparkDevNetwork/Rock/commit/3e62ba91dc21efe4b277c8903921e1f86f986ee5
