### ISSUE TITLE
Event Registration Registrations tab should allow sorting on Registered By

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3622]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The `Registered By` column should allow sorting, unless somebody knows of a reason it can't be sorted.

Will provide PR if approved.

**Expected behavior:**

To be able to sort by a text column

**Actual behavior:**

Cannot sort.

### Versions

* **Rock Version:** 8.6
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Sounds good.
