### ISSUE TITLE
Event Registration Wait List + Inline Signing causes exception

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3623]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you setup an Event Registration Template to have a Wait List and also use Inline Document Signing then an exception occurrs anytime somebody tries to sign up when they will be placed on the wait list.

PR incoming.

### Steps to Reproduce

1. Create an Event Registration with an inline Document to sign and also Wait List.
2. Create an instance of the Template with maximum attendees of 1.
3. Register one person, everything works.
4. Attempt to register second person, it will inform you they go on the waitlist.
5. When clicking Next to go to the Inline document sign screen, you see an error instead.

**Expected behavior:**

@edmistj Can you confirm if the person going on the waitlist should see the inline document signing screen? I believe the answer is "yes" as that would be a pre-requisite to signing up to the event.

So for a person on the waiting list, they should see any forms that have fields marked as "Show on Waiting List" and then see the screen asking them to sign the e-signature document.

**Actual behavior:**

You see an Index Out of Rang exception.

### Versions

* **Rock Version:** 8.6
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
@cabal95 yeah it makes sense I guess to get the signed docs ahead of time. Getting them later would be difficult.
