### ISSUE TITLE
Group Member Attributes not filterable on Dataviews/Reports

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#3624]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
Not sure it's a bug or just not a planned function. I would expect to be able to filter member attributes on groups in dataviews. 

A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce

1. Go to `children's serving team` on demo site. Edit. Add `member attribute` and save.
2. Create a person dataview and choose 'Groups Advanced'
3. Filters that are created as group type member attribute are available but if they are created at the group level.

**Expected behavior:**

I would expect to see the member attributes at the group level as a filter

**Actual behavior:**

Filters that are created as group type member attribute are available but if they are created at the group level.

### Versions

* **Rock Version:** [8.6]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by edmistj** [comment]
I think you'd want to make a data view on groups members first, then create a person data view that uses the group member data view.

**Comment by nairdo** [comment]
Hi @timlem, that's right -- the In Group(s) Advanced filter type on a person data view does not have functionality to filter by group member attributes.
![image](https://user-images.githubusercontent.com/383807/55176901-48579680-513f-11e9-8586-17cc4b1b8fed.png)

**Comment by nairdo** [comment]
I should have probably restated this with my last response -- you will need to do as Jon suggests and use a Group Member Data View to first filter the members.
