### ISSUE TITLE
Checkin Schedule Selections

### ISSUE THREAD

**Issue by TheArkChurch** [SparkDevNetwork/Rock#3626]
### Description
When checking in with multiple schedules available, if a person selects the wrong schedule and doesn't realize it until they are looking at the area selection(adult classes, volunteer positions...) and see that their class\area isn't there, if they click the **back** button then select the correct time and click next Rock doesn't show the classes.

1. Set up 2 groups with 2 different schedules available for checkin.
1. Go to checkin, start the process of checking in and select one of the schedules then next.
1. Without selecting an area to check into(because you forgot it was at the other time) click the back button to change your time.
1. Select the other schedule that you didn't select before and click next. See the message. 

**Expected behavior:**

The new selected schedule's activities should be displayed. 
This was the behavior previous to 8.6.

**Actual behavior:**

You get the message "Sorry, there are currently not any available areas that (Person Name) can check into at (Schedule Name)" when in fact there are areas available.

### Versions
* **Rock Version:** 8.6(1.8.6.2)
* **Client Culture Setting:** en-US

**Comment by briankalwat** [comment]
Confirmed in `11.0.2`. 

![image](https://user-images.githubusercontent.com/2465823/67497425-f383ec00-f64b-11e9-88ff-84fd0bfa22d9.png)

**Comment by nairdo** [comment]
With the establishment of a new "check-in 2.0" project for next-gen, we're going to put this issue on that project's requirements to see if it can be addressed there).  That said we are we going to close this issue publicly and label it as "Will Fix in Next Gen".
