### ISSUE TITLE
Multi-Select on an entry Form in a workflow not respecting Required setting

### ISSUE THREAD

**Issue by tstephens17** [SparkDevNetwork/Rock#3629]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Using a defined type as a multi-select in a workflow does not respect the 'Required' setting in the User Entry Form action.

### Steps to Reproduce

1. Create Attribute of field type ~"Defined Type"~ [Defined Value] and select a ~Defined Value~ [Defined Type from the] list then check Allow Multiple Values and mark it "Required".
2. Mark it as required in the user entry form action too.
3. Try to submit the form, it allows it and if you have other required fields, the warning does not inform you of the multi-select.

Can see behavior here -> Select Life Group as the group type. No person will be created or data saved until after the 2nd form. So, please just go to the second form and don't fill anything out and try to save.
https://preview.northviewchurch.us/JoinAGroup

![image](https://user-images.githubusercontent.com/32707751/55238404-d2b8fc80-520a-11e9-85f7-443d0d5d5985.png)

**Expected behavior:**

A required field to be required.

**Actual behavior:**

A required field isn't required.

### Versions

* **Rock Version:** [Rock McKinley 8.7 (1.8.7.5)]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
@tstephens17 do you mean that an attribute of field type "Defined Type" or of type "Defined Value" with _Allow Multiple Values_ checked? Can you include a screenshot of your attribute's configuration here.

**Comment by tstephens17** [comment]
@nairdo yes, sorry about that.
![image](https://user-images.githubusercontent.com/32707751/55241160-e1a2ad80-5210-11e9-94c0-cd885cf1fac1.png)
