### ISSUE TITLE
Fundraising Matching no showing correct amount from donor

### ISSUE THREAD

**Issue by tbunney** [SparkDevNetwork/Rock#3630]
### Description
This was a previous issue, but so far we have not seen the fix in any of the releases.

We have noticed on the Fundraising Matching, that when a contributor gives to a Fundraising Opportunity and tithes on the same check, even though the tithe goes to a tithe account and the missions trip goes to a trip account, the trip participant can see the entire amount combined on their participant page.
The Fundraising Progress "progress bar" calculates everything correctly. But in the list of donors below, it gives the entire check amount, rather than just the trip donated amount.
E.g. if I give $180 to the church but only give $35 to the Fundraising Opportunity, my entire $180 tithe is listed on the participant's page.

### Steps to Reproduce
* Create fundraising opportunity
* Person writes a check, designating a portion of the check to Fundraising opportunity
* We assign the funds to the appropriate accounts.
* See error

**Expected behavior:**
Participants would only see portion that was designated on their list of Financial Transactions.

**Actual behavior:**
Participants see the entire gift of the donor.
![FundraisingMatching](https://user-images.githubusercontent.com/37702418/55250040-c55c3c00-5223-11e9-9976-45cbcb868b38.JPG)

### Versions
Rock Version: Rock McKinley 8.7 (1.8.7.5)

Client Culture Setting: en-US

**Comment by tbunney** [comment]
All my description was lost when posted this first. Here is it again:
 
This was a previous issue, but we have not seen the issue fixed and I could not reopen the old request.

We have noticed on the Fundraising Matching, that when a contributor gives to a Fundraising Opportunity and tithes on the same check, even though the tithe goes to a tithe account and the missions trip goes to a trip account, the trip participant can see the entire amount combined on their participant page.
The Fundraising Progress "progress bar" calculates everything correctly. But in the list of donors below, it gives the entire check amount, rather than just the trip donated amount.
E.g. if I give $180to the church but only give $35 to the Fundraising Opportunity, my entire $180
 tithe is listed on the participant's page.

Steps to Reproduce

- Create fundraising opportunity
- Person writes a check, designating a portion of the check to Fundraising opportunity
- We assign the funds to the appropriate accounts.
- See error

Expected behavior:
Participants would only see portion that was designated on their list of Financial Transactions
Actual behavior:
Participants see the entire gift of the donor.
![FundraisingMatching](https://user-images.githubusercontent.com/37702418/55250442-8e3a5a80-5224-11e9-9f55-a3e5f9695c53.JPG)

Versions
Rock McKinley 8.7 (1.8.7.5)

Client Culture Setting: en-US

**Comment by tbunney** [comment]
Just tested this in v8.8 and it is not fixed. I applied $35.00 out of $185.00 to a participant, and it showed the whole $185.00 in the list of contributors. In the fundraising progress, it only shows $35.00, it is the bottom grid that has been the problem.

**Comment by nairdo** [comment]
@tbunney are you seeing two "Amount" columns in yours like this?
![image](https://user-images.githubusercontent.com/383807/58581551-a585cc00-8204-11e9-895c-8ae308e50cd4.png)

**Comment by tbunney** [comment]
Yes, I do see it now, but did not see it yesterday when I tested. Not sure
why it looks different today.

We really don't want the first amount showing, as those attending mission
trips really don't need to see the total giving from a person. That is
confidential information. They only need to see the amount given to them.

**Comment by nairdo** [comment]
Ok, and is the second "Amount" column showing the correct value?

I'm still investigating why that first Amount column is in there (it should have been removed with the fix)...  If you answered Yes to the above question, although this will be corrected in the next release, the line that looks like this in the `RockWeb\Blocks\Fundraising\FundraisingParticipant.ascx` file can be safely deleted from that file:

```html
                            <Rock:CurrencyField DataField="TotalAmount" HeaderText="Amount" HeaderStyle-HorizontalAlign="Right" ItemStyle-HorizontalAlign="Right" />
```

I can also tell you that in Rock v9 there is also a new block setting called "Show Amount" which controls if that column is shown at all.

**Comment by tbunney** [comment]
Yes, the second column is the correct amount donated towards the
fundraising opportunity.

**Comment by nairdo** [comment]
Just for completeness, these are the fixes for this issue: https://github.com/SparkDevNetwork/Rock/commit/9d3449290dcedf4e46b327f0e305370fed048f34 and https://github.com/SparkDevNetwork/Rock/commit/925e6b624429680372f28599d4c92c10825cccf2 .
