### ISSUE TITLE
Block Controls not accessible for Internal Site Left Menu

### ISSUE THREAD

**Issue by bjacky** [SparkDevNetwork/Rock#3634]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

A clear and concise description of what the bug is, include screenshots if applicable.

The block controls are not accessible for the Rock Internal Site Left Menu.

<img width="252" alt="Screen Shot 2019-04-01 at 3 10 03 PM" src="https://user-images.githubusercontent.com/22566379/55353521-7f0c1480-5491-11e9-9b8d-4a1ec11ca438.png">

### Steps to Reproduce

1. Go to Demo Site
2. Click on Block Configuration
3. See error

**Expected behavior:**

It would appear in front of neighboring content, not behind.

**Actual behavior:**

Block controls are hidden behind the main content to the right of the menu.
Perhaps this is a z-index numbering issue or a limitation of the current design?

### Versions

* **Rock Version:** [Rock McKinley 8.6 (1.8.6.2)]
* **Client Culture Setting:** [en-US]

**Comment by garrettjohnson** [comment]
The fix in 8.8 will hide the configuration bars in the side navigation. Due to the nature of the menu we have to hide the overflow of that section, which hides the configuration bar.

Page Menus on the Rock theme can be modified inside `CMS Configuration > Pages`
![image](https://user-images.githubusercontent.com/374209/55596127-f47b1d80-56fb-11e9-924e-d9e37e84cef2.png)
