### ISSUE TITLE
Internal API Error Issue with Sign Now (Manual Requests Through Document Templates Page)

### ISSUE THREAD

**Issue by shelbysubia** [SparkDevNetwork/Rock#3645]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()? (Demo site doesn't have a Sign Now account to test with -- I reached out to the community for confirmation that this is a widespread bug, but didn't get a response)
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is](https://github.com/issues?q=is) %3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce
1. Go to Admin Tools > General Settings > Signature Documents > Select a Template > Click the + button to manually send a new digital signature document / request

![<a href="https://user-images.githubusercontent.com/45953896/55923890-81bae800-5bbc-11e9-9dcf-d7ecbbb170d6.png">https://user-images.githubusercontent.com/45953896/55923890-81bae800-5bbc-11e9-9dcf-d7ecbbb170d6.png</a> image]()

1. Fill in the details

![<a href="https://user-images.githubusercontent.com/45953896/55923943-afa02c80-5bbc-11e9-93ee-d79a68b25e2a.png">https://user-images.githubusercontent.com/45953896/55923943-afa02c80-5bbc-11e9-93ee-d79a68b25e2a.png</a> image]()

1. Click "Save"
1. Find and edit the row of the new document request.
1. Click "Send Invite"
1. See error "Error Sending Signature invite" -- Internal API Error

![<a href="https://user-images.githubusercontent.com/45953896/55923967-cfcfeb80-5bbc-11e9-8ecd-5e53967ee592.png">https://user-images.githubusercontent.com/45953896/55923967-cfcfeb80-5bbc-11e9-8ecd-5e53967ee592.png</a> image]()

**Expected behavior:**

Normally, the signature document sends without any problem -- you get a green success div at the top informing you that the document has been sent, and you click Save. I sent close to 400 documents on 3/5/19 and those were all sent successfully. I have not updated my Rock server between the last time this functionality worked and now.

(Please note that signature documents being sent automatically through Registrations / Groups, etc. ARE working as expected.) 

**Actual behavior:**

I first noticed this issue on 3/21/19, so I've already spent a lot of time trying to troubleshoot this with Sign Now between then and now. I have assumed that this issue was related to Sign Now and not Rock, because I got this exact error message when following these same steps at the time we first started using their API (shortly before 3/1/19), and they resolved the issue. 

However, one of their API techs today said that the detailed error message they are seeing on their end states that the document is not being generated correctly, because the document ID is missing when the API is called. He said this error is occurring within Rock. Once that is resolved, everything should be golden. The API support tech that I spoke with gave me the call back number of (800) 366-0593 should it be needed.

### Versions
* **Rock Version:** 8.6
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Confirmed on our installation.  Also updated the steps to reproduce slightly.

**Comment by jonedmiston** [comment]
Closing as we no longer support the Sign Now integration.
