### ISSUE TITLE
Attendance records start time incorrectly

### ISSUE THREAD

**Issue by SteveSwaringen** [SparkDevNetwork/Rock#3647]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When recording attendance, a change introduced in 8.5 (commit 971d067257f6cce0e8675e07b18e0cde4d354ff0) adds the time of day of the event to the date _and_time_ of the event, resulting in an incorrect time noted in the person's attendance history.

### Steps to Reproduce

1. Go to RockSolidChurchDemo.com. Group Viewer. Section A->Alisha Marble's Group.
2. Click on the "attendance" checkbox icon to edit attendance. Note the scheduled date and time (4/10/2019, 7pm in my case). Click on that entry to edit the attendance for that event.
3. Check one or more members. (Alisha Marble, for reference.) Save the attendance.
4. Search for Alisha Marble and go to the history tab on her person page. Note in the Attendance History block that attendance was recorded as 4/11/2019, 2PM. (This is 19 hours (7 + 12) after the scheduled event.)

**Expected behavior:**

Recorded attendance in step 4 above should have been 4/10/2019, 7pm.

**Actual behavior:**

Recorded attendance was 4/11/2019, 2pm.

### Versions

* **Rock Version:** 8.6 (1.8.6.2)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Hi Steve, I think you may be reporting an issue that was recently reported and corrected in the upcoming 8.8 release.  Do you agree this is the same issue? https://github.com/SparkDevNetwork/Rock/issues/3602

**Comment by cabal95** [comment]
I also tested this on the `develop` branch and it recorded correctly - but I was able to replicate the problem on the demo site, so I believe this has been indeed fixed by the mentioned patch.

**Comment by SteveSwaringen** [comment]
Yes. I agree that’s the issue. Thanks for the note on the resolution, and my apologies for not seeing that it had already been reported and addressed.

**Comment by nairdo** [comment]
Great. (No need to apologize.)
