### ISSUE TITLE
Content Channel Item View block should not list Content Component Type Channels in Block Settings

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#3653]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using the `Content Channel Item View` block, choosing a channel reveals all of the channels that are created from use of the `Content Component` block. In my opinion, expected functionality would be that these "channels" would be hidden from this block.

### Steps to Reproduce

1. Place any number of Content Component blocks on any page.
2. Place the Content Channel Item View block on to a page.
3. Edit the settings of the Content Channel Item View block.
4. Select a content channel in the block settings.
5. See every channel created by content component blocks, along with your _actual_ content channels.

![image](https://user-images.githubusercontent.com/2465823/56237940-40628680-605b-11e9-9e3e-c6b78cd99c3d.png)

**Expected behavior:**

Content Component block channels should not be listed in the channel dropdown on the Content Channel Item View block.

**Actual behavior:**

Content Component block channels are listed in the channel dropdown on the Content Channel Item View block.

### Versions

* **Rock Version:** 1.9.0.15
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
