### ISSUE TITLE
Named Location Editor not saving custom attribute values when adding new location

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#3657]
Submitted on behalf of https://www.thecrossingchurch.com/

### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When adding a new location, any attribute values that are entered do not get saved. If you edit an existing location and enter the attribute values again, they do save. ([Here is a short video of this on the demo site](https://drive.google.com/file/d/1czT_jVHsg9_EaPVWclGNWPGEPVk3D3I_/view)) 

### Steps to Reproduce

1. Create a new Entity Attribute for locations
2. From the Named Locations, select option to add a new location
3. Set the Location type so that attributes appear
4. Add a value for the attribute
5. Save the new location

**Expected behavior:**

Attribute value is saved with the location

**Actual behavior:**

The attribute value is not saved. If you edit the location after adding it, there will not be any value displayed, but if you then set the value again and save. It does get saved then.

### Versions

* **Rock Version:** Rock McKinley 8.6 (1.8.6.2)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
(edited title to make it clearer that this is about an attribute on a Location entity, not a Location Attribute)

Confirmed on my own install too.  Additionally, probably related, I had setup the attribute to have no qualifiers which means it should have shown up right away. It did not. I had to switch the Location Type to something to make it show up - when I switched the location type drop down back to the default/blank value the custom attribute remained. But as David pointed out it didn't actually save the value.
