### ISSUE TITLE
Facebook Authentication Provider 'Sync Friends' Property ignored

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/Rock#3661]
### Prerequisites
* [] Put an X between the brackets on this line if you have done all of the following:
    * **NO** Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? *I have not verified on demo, not possible to recreate on Demo*
    * **YES** Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * **YES** Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you set the 'Sync Friends' Facbook Authentication Provider property to `No` it still asks for the `user_friends` scope in the URI

### Steps to Reproduce

1. Configure a Facebook app for Rock linking according to the Rock Admin documentation
2. *DO NOT* setup 'sync friends' permission on the Facebook side
3. Setup Rock's _Facebook_ Authentication Provider, including the App ID, App Secret, and *set 'Sync Friends' to no*
4. Configure your login blocks, etc.
5. Attempt to login with Facebook

**Expected behavior:**

Rock should not include `user_friends` in the scope of it's request to Facebook if 'Sync Friends' is set to 'No'

**Actual behavior:**

If logging into Facebook using the OAuth function you setup and the Facebook account that is the administrator of the app, you will receive an error message. `Invalid Scopes: user_friends. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions`
<img width="532" alt="(85) 2019-04-24 09-39-30" src="https://user-images.githubusercontent.com/8688424/56668306-ea9e6780-6674-11e9-82b8-06b4099abc83.png">
An example URL of an OAuth request (I replaced some of the URL with hashes as I wasn't sure if the API key etc. were a security risk):
 `https://www.facebook.com/login.php?skip_api_login=1&api_key=######&kid_directed_site=0&app_id=######&signed_next=1&next=https%3A%2F%2Fwww.facebook.com%2Fdialog%2Foauth%3Fclient_id%3D########%26redirect_uri%3Dhttps%253A%252F%252Fmy.calvary.church%253A443%252Fpage%252F625%26state%3D%25252fcalendar%26scope%3Dpublic_profile%252Cemail%252Cuser_friends%26ret%3Dlogin%26fallback_redirect_uri%3Dea8e9a16-56e5-d4ec-7f0f-5b2aaa05d404&cancel_url=https%3A%2F%2Fmy.calvary.church%3A443%2Fpage%2F625%3Ferror%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%26state%3D%25252fcalendar%23_%3D_&display=page&locale=en_US`

**This error message only appears to administrators of the FB App.** It silently does not pass user friends data for non-FB-App administrators (doesn't send the data to Rock)

### Versions

* **Rock Version:** 7.5, 8.3, 8.4, 8.5, 8.6
* **Client Culture Setting:** en-US

**Comment by chrismcgrath** [comment]
I don't understand all the technical details of this, but I can confirm that I turned off the friend sync option but Facebook still requested friends list permissions when I tried to use Facebook login.
