### ISSUE TITLE
Update the Send Birthday Email job to exclude people without a Birth Year

### ISSUE THREAD

**Issue by TheCoreyHall** [SparkDevNetwork/Rock#3662]
# Feature Request

**Describe the Feature Request**
Currently the Send Birthday Email job will send the email to all people that dont have a birth year but do have a birth day and month, in addition to those that fit within the programmed age range. This is even explained in the tooltip.
https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Jobs/SendBirthdayEmail.cs
![image](https://user-images.githubusercontent.com/38293092/56749300-1427c380-6747-11e9-94c3-7f06e0342cca.png)

**Describe Preferred Solution**
Update the job to exclude those without a birth year.

**Describe Alternatives**
A patchwork solution we have been considering is giving all people with an existing birth day and month but no year a default year of 1900 so that they dont get picked up by the job, but we would prefer it if the job didnt find them already.

**Providing Code**
I will provide code if feature request is approved: [No]

**Comment by cabal95** [comment]
A more future-proof solution might be to add a new configuration option to the job that allows you to pick a DataView that will be used (in addition to the Connection Statuses) for filtering who receives the e-mail. Then each church can create a DataView to fit their needs.

**Comment by nairdo** [comment]
Although we wouldn't change the job to exclude those without a birth year, we will consider either a configuration switch/setting or Daniel's suggestion down the road when we work on core enhancements.

**Comment by jonedmiston** [comment]
We should go with @cabal95 solution as it handles this use case and an infinite other possibilities.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
