### ISSUE TITLE
Page Title Lava Filter Pulls Browser Title Instead of Page Title

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#3667]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using the Page lava filter to pull the page title (`{{ 'Global' | Page:'Title' }}`) it actually pulls the page's _browser_ title instead of the _page_ title.

### Steps to Reproduce

1. Go to any page.
2. Set different values for the Page's `Page Title` and `Browser Title` attributes.
3. Use the Page Title lava filter `{{ 'Global' | Page:'Title' }}` anywhere on the page to pull the page's title.

**Expected behavior:**

Page Title lava filter should pull the page's Page Title attribute value.

**Actual behavior:**

Page Title lava filter pulls the page's Browser Title attribute value.

### Versions

* **Rock Version:** 1.9.0.18
* **Client Culture Setting:** en-US

**Comment by briankalwat** [comment]
Wondering if it would be possible to have both `{{ 'Global' | Page:'PageTitle' }}` and `{{ 'Global' | Page:'BrowserTitle' }}`?

**Comment by nairdo** [comment]
This is currently working as designed (https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Lava/RockFilters.cs#L4003) but I'll add this to our next discussion.

**Comment by nairdo** [comment]
@briankalwat We changed the Page:'Title' to return the actual Page's Title and then added a Page:'BrowserTitle' to return the browser title property.  You're all set now!

**Comment by briankalwat** [comment]
@nairdo does this give us the ability to _set only the browser_ title property or just to retrieve it?

**Comment by jonedmiston** [comment]
@briankalwat the filter above retrieves the title. You can set the page title using `SetPageTitle`
https://community.rockrms.com/lava/filters/other-filters#setpagetitle

**Comment by briankalwat** [comment]
@jonedmiston how difficult is it to duplicate `SetPageTitle` and make it work for `SetBrowserTitle`? 👍

**Comment by jonedmiston** [comment]
@briankalwat looking at the code it should be doing that currently. 
![image](https://user-images.githubusercontent.com/548178/57886173-75d8cc00-77e1-11e9-9a4d-554eb8d4ad5f.png)

**Comment by briankalwat** [comment]
@jonedmiston Yes, it sets both to the same value. We’d like to be able to set the browser title without modifying the page title.

**Comment by jonedmiston** [comment]
@briankalwat Ahhhh... got it. I added that via this commit: https://github.com/SparkDevNetwork/Rock/commit/6c3f15b851877c8189df784c52dfee5b3e59eb32

Here's the updated docs:
https://community.rockrms.com/lava/filters/other-filters#setpagetitle

**Comment by briankalwat** [comment]
Thank you so much!!
