### ISSUE TITLE
Dynamic data Block "Communication Recipient Field" not working as desribed

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#3668]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
Dynamic Data Block "Communication Recipient Fields" does not work as described in the description bubble.  It gives an error message expecting an 'Id' field instead of respecting any text you put into the field.

### Steps to Reproduce
1. Create a dynamic data block
1. Use a simple sql select and change the column name for the PersonId to anything else
1. reference the column name in the Communication Recipient Field
1. See error

**Expected behavior:**

It should reference whatever Column Name you give it.

**Actual behavior:**

Error Message

Error
Column 'Id' does not belong to table Table.

at System.Data.DataRow.GetDataColumn(String columnName)
 at System.Data.DataRow.get_Item(String columnName)
 at Rock.Web.UI.Controls.Grid.GetPersonData(Boolean isForCommunication, Dictionary`2 communicationMergeFields)
 at Rock.Web.UI.Controls.Grid.Actions_CommunicateClick(Object sender, EventArgs e)
 at Rock.Web.UI.Controls.GridActions.lbCommunicate_Click(Object sender, EventArgs e)
 at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
 at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
 at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

### Versions
* **Rock Version:** [8.6]
* **Client Culture Setting:** [EN-US]

**Comment by markewampler** [comment]
It seems to only allow the column to be called Id and if you try and reference anything else it doesn't work.  A workaround is to just do an "PersonId as 'Id'" and it works fine as it is looking for an Id column

**Comment by Tschrock** [comment]
Confirmed on 8.8 & the prealpha server (10.0 (1.10.0.2)). Clicking the "Communicate" button in the grid throws the error.

Block settings used: [firefox_2019-07-17_16-28-04](https://user-images.githubusercontent.com/2406499/61409283-e8345e00-a8af-11e9-8336-4116500f516f.png)
Result: [firefox_2019-07-17_16-32-44](https://user-images.githubusercontent.com/2406499/61409608-98a26200-a8b0-11e9-8a44-d914af59ad6b.png)
