### ISSUE TITLE
Check-in Search Text Field Title Change

### ISSUE THREAD

**Issue by Adroken** [SparkDevNetwork/Rock#3673]
# Feature Request

**Describe the Feature Request**
Inside Check-in, the label for searching by Name or Phone number is `Name or Phone`.  This leads people to search first by Name, and then by Phone as we are suggesting that search order by the label text.  Phone number searches are much quicker and lighter on the database than text searches vs name.

**Describe Preferred Solution**
Preferred solution would be to have the label read `Phone or Name` instead.  This would have no effect on existing users that are set in their habits, however new users would see the title and use their phone number first (hopefully!).
The file to be changed is in `Rock / RockWeb / Blocks / CheckIn / Search.ascx.cs`

**Describe Alternatives**
Possible alternatives would be having an option to set this to whatever text you want instead.  

**Providing Code**
I will provide code if feature request is approved: [No]

**Comment by nairdo** [comment]
I missed mentioning this issue # when we worked on the check-in label reprint feature for v9.  So, this one got implemented during this commit: https://github.com/SparkDevNetwork/Rock/commit/cb632a633e053d7fdaac88838e89956bce858beb#diff-8adafc318a77a5bf0586779ed4f13138R86 .

**Comment by Adroken** [comment]
Thanks so much!  This is such a tiny thing but will have a big impact!
