### ISSUE TITLE
Key Not In Dictionary Error during Bulk Import

### ISSUE THREAD

**Issue by JoshuaMaiorino** [SparkDevNetwork/Rock#3675]
### Description
When doing a Slingshot Bulk Import from a system that doesn't have defined lists for Title and Suffix, the import tool will often throw a Key not in dictionary issue.  This is due to how the import tool adds those values to the list.  When comparing to see if Titles are already in Rock, it ignores case.  The importer then adds any new Items not in Rock, and creates a dictionary with a string for the look up key.  When using a string as a key to look up, it is case sensitive.

So, for example, the Data import could contain the following title, 'mr.'  When looking to see if that title is in Rock, it will match to Rocks defined value, 'Mr.', and build the look up.  However, no key of 'mr.' will be added to the look up.  When it tries to set that defined value, it throws the Key not present in dictionary error.

### Steps to Reproduce
See Description

**Expected behavior:**

Code for matching to the lookup should also ignore case.

**Actual behavior:**

Code for matching is case sensitive, so it throws a Key not in dictionary error.

### Versions
* **Rock Version:** [All]
* **Client Culture Setting:** [Any]

I've created a fix for this, and will submit a PR.

**Comment by MrUpsideDown** [comment]
This issue has been fixed with this commit:
https://github.com/SparkDevNetwork/Rock/commit/90c69415601b1e661a4234ff0f3f5cd6cfd0c34d
