### ISSUE TITLE
[EN] Family-style check-in doesn't instantly print with a single person with no additional group/location/time options.

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3676]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Not certain if this is an issue or an enhancement--I think it can go either way. 

When checking in a person with the configuration set to Family Check-in Type, if only a single individual is available to check in (and they can only check in to one group, one time, one location) I believe the check in process should skip to the Success page and print the tag(s) instead of requiring the user to click Next. This would mirror the same process that is used when Individual Check-in Type is used.

For context, I stumbled across this when testing barcode scanning with check in for a single event. 

### Steps to Reproduce

1. Schedule a Group for check in with only one location and for only one time. 
2. Set Check In Configuration to Family.
3. Pull up a family with only one person in it (or where only one person is eligible for the group)
4. On the Person Select page you'll only have one person listed and will need to hit Next or Back/Cancel. If you were using the Individual Check-in Type, in this situation it goes straight to the Success page and prints out the tag(s). 

**Expected behavior:**

I would expect Family Check-in Type to work the same way Individual Check-in Type does in this situation but I'm not certain if the current way it works is intentional or not.

**Actual behavior:**

You can unselect the single person in the list, click Back or Cancel, or press Next to proceed to the Success page.

### Versions

* **Rock Version:** v8.7, also tested in v8.8.2 alpha
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
