### ISSUE TITLE
/api/Auth/Login does not set required Access-Control-Allow-Credentials CORS header in response

### ISSUE THREAD

**Issue by JordanOsterberg** [SparkDevNetwork/Rock#3678]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When POSTing to ```/api/Auth/Login``` with the REST API, no .ROCK cookie is returned in the headers when using Ajax (jQuery)

### Steps to Reproduce
1. Add "null" as a CORS domain on the demo site
1. Create a new html file with this content:

```html
<html>
    <head>
        <script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
    </head>

    <body>

        <script>
            let url = "https://prealpha.rocksolidchurchdemo.com";

            $.ajax({
                type: "POST",
                url: url + "/api/Auth/Login/",
                data: JSON.stringify({
                    "Username": "admin",
                    "Password": "admin"
                }),
                processData: false,
                xhrFields: {
                    withCredentials: true
                },
                crossDomain: true,
                beforeSend: (xhr) => {
                    xhr.setRequestHeader("Content-Type", "application/json")
                },
                success: (val, status, xhr) => {
                    console.log(xhr.status);
                    console.log(xhr.getAllResponseHeaders());

                    console.log(xhr.getResponseHeader('Set-Cookie'));

                    console.log("\n\n");

                    $.ajax({
                        type: "GET",
                        url: url + "/api/Workflows",
                        success: (val, status, xhr) => {
                            console.log(val);
                        },
                        error: (xhr, status, error) => {
                            console.log("Workflow GET error code:", xhr.status);
                        }
                    })

                },
                error: (xhr, status, error) => {
                    console.error(error);
                }
            })
        </script>
    </body>

</html>
```

1. Open the HTML file
1. Open the web inspector
1. Notice that the ```Set-Cookie``` header is absent from the console log, and notice that the HTTP status code is 204
1. If using chrome, you can verify that the cookie is missing by going to ```Application -> Cookies -> file://```

**Expected behavior:**

The .ROCK cookie should appear in the list.

**Actual behavior:**

The .ROCK cookie is missing.

### Versions
* **Rock Version:** ```Rock McKinley 8.7 (1.8.7.6)```
* **Client Culture Setting:** ```en-US```

**Comment by cabal95** [comment]
Rock is actually including the `Set-Cookie` header correctly. However, for a web browser to _accept_ a cookie (and certain other secure items) from a CORS request, the server must also send back the `Access-Control-Allow-Credentials: true` header in the response. Note in the screenshot below that Rock is indeed returning the cookie, but it doesn't include the required header so the browser is ignoring it.

<img width="1159" alt="Screen Shot 2019-05-04 at 8 03 41 PM" src="https://user-images.githubusercontent.com/1119863/57187693-ca0db300-6ea7-11e9-8685-870a95fdefb8.png">

Also, it appears that in your AJAX request you need to tell the browser that this is a credentials request (see discussion at SO below).

https://stackoverflow.com/questions/2054316/sending-credentials-with-cross-domain-posts

Implementation Reference: https://stackoverflow.com/questions/33269488/credentials-flag-is-true-but-the-access-control-allow-credentials

**Comment by JordanOsterberg** [comment]
@cabal95 Is the ```Access-Control-Allow-Credentials``` flag something that I have to implement into my own flavor of Rock?

Updating the example page's implementation to use the fields from the first stackoverflow link throws an error:

<img width="1680" alt="Screen Shot 2019-05-05 at 9 56 20 AM" src="https://user-images.githubusercontent.com/20231652/57197438-21e60180-6f1c-11e9-8560-9c7b43d7561e.png">

**Comment by cabal95** [comment]
The `Access-Control-Allow-Credentials` flag is something that would still need to be implemented in Rock core. I was primarily posting it so that somebody else didn't do a quick test and see the cookie in the response headers and figure it was actually working correctly.

**Comment by nairdo** [comment]
@JordanOsterberg  If I'm not mistaken, I believe this is being addressed by a change that's coming in v9: https://github.com/SparkDevNetwork/Rock/commit/e9e6a246b7b9d5f51e4710c438ed16b6f1a4f415#diff-e32173d12e0d593ceb8bdb5fa1af8da0R52  . 

![image](https://user-images.githubusercontent.com/383807/57253687-2dacf300-7004-11e9-913c-e49168db8998.png)

Feel free to give it a try on the `prealpha.rocksolidchurchdemo.com` (v9) system and update (or close) this issue based on your findings.

**Comment by JordanOsterberg** [comment]
Unfortunately, it doesn't look like the prealpha site resolves this issue either. While the ```Access-Control-Allow-Credentials``` header is present, the ```Set-Cookie``` header does not appear using the test webpage.

I have updated the test webpage to include a subsequent GET request to ```/api/Workflows``` after the POST request to ```/api/Auth/Login``` to validate that the ```.ROCK``` cookie is not being set correctly.

I ran some additional tests using a different HTTP client for NodeJS, and the results were the same. Using Postman to manually test works as intended, and I am able to GET ```/apli/Workflows```.

**Comment by cabal95** [comment]
@JordanOsterberg I tweaked your original/updated example to work. You had forgotten to set the
`xhrFields: { withCredentials: true }` in the second Workflow request to tell the browser to send the authentication cookies in the CORS request.

The `withCredentials: true` flag tells the browser to _send_ any cookies/auth information as well as to accept it back from the server - so you need it on both.

I tested on Mac/Safari. Your updated sample page above did not work as you noted, with the tweak I made below it works fine. Please let us know if this sample below does not work for you:

```
<html>
    <head>
        <script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
    </head>

    <body>

        <script>
            let url = "https://prealpha.rocksolidchurchdemo.com";

            $.ajax({
                type: "POST",
                url: url + "/api/Auth/Login/",
                data: JSON.stringify({
                    "Username": "admin",
                    "Password": "admin"
                }),
                processData: false,
                xhrFields: {
                    withCredentials: true
                },
                crossDomain: true,
                beforeSend: (xhr) => {
                    xhr.setRequestHeader("Content-Type", "application/json")
                },
                success: (val, status, xhr) => {
                    console.log(xhr.status);
                    console.log(xhr.getAllResponseHeaders());

                    console.log(xhr.getResponseHeader('Set-Cookie'));

                    console.log("\n\n");

                    $.ajax({
                        type: "GET",
                        url: url + "/api/Workflows",
	                xhrFields: {
	                    withCredentials: true
	                },
                        success: (val, status, xhr) => {
                            console.log(val);
                        },
                        error: (xhr, status, error) => {
                            console.log("Workflow GET error code:", xhr.status);
                        }
                    })

                },
                error: (xhr, status, error) => {
                    console.error(error);
                }
            })
        </script>
    </body>

</html>
```

**Comment by JordanOsterberg** [comment]
@cabal95 The tweak worked correctly, thank you.

@nairdo, is threre any chance of a release earlier than v9 to push the e9e6a24#diff-e32173d12e0d593ceb8bdb5fa1af8da0R52 fix into production?

**Comment by nairdo** [comment]
Hi @JordanOsterberg , Since we've run into an additional bug (#3683) we also want fixed in the v8,8 hotfix, we'll include this v9 change into v8.8 as well: https://github.com/SparkDevNetwork/Rock/commit/a13eff5b6b91fe53a5b60080e7aca8d40078c533
