### ISSUE TITLE
Correct the currency formatting in Contribution Statement lava and .cs

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3679]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
In the Contribution Receipt lava (Giving History page, click a year and run a Contribution Statement, edit Contribution Statement Lava block)

and in the Donation Receipt .cs file (ContributionStatementLava.ascx.cs)
(and maybe in other places (ContributionStatementLava.ascx?) but I haven't checked,)

the formatting for the amounts listed is 
{{ 'Global' | Attribute:'CurrencySymbol' }}{{ accountsummary.Total }}, 
e.g.
 Amt Pledged: {{ 'Global' | Attribute:'CurrencySymbol' }}{{ pledge.AmountPledged }} <br />

This shows an amount as $15000.00.

It would be better to use {{ accountsummary.Total | FormatAsCurrency }} 
{{ transaction.Amount | FormatAsCurrency }}
{{ pledge.AmountPledged | FormatAsCurrency }}

Which correctly displays the amount as $15,000.00

(I presume that FormatAsCurrency takes into account the correct CurrencySymbol for the given culture.

### Steps to Reproduce
1. Go to external page, Give.
1. Click on 'Giving History' for a person that has a financial giving history.
1. Click a year to display a Contribution Statement.
1. Edit the block Contribution Statement Lava.
1. Edit also the Financial block file ContributionStatementLava.ascx.cs

May also be in other areas.

**Expected behavior:**

Financial amounts should correctly display in the culture's Currency Format.
$15,000.00 not $15000.00 for en-NZ.

**Actual behavior:**

Amounts were displayed as $15000.00 - The currency symbol is simply tacked on the front of an un-formatted number.

### Versions
Rock Version: Rock McKinley 8.6 (1.8.6.2)
Client Culture Setting: en-NZ

**Comment by nairdo** [comment]
Ken @ElimAdmin, Thanks again!  We've implemented your suggestion for Rock v9, but you will need to wipe out the saved, custom Lava Template block setting to pick up the change once you install v9.

**Comment by ElimAdmin** [comment]
Thanks Nick!  @nairdo 

I had to make changes to our code I will need to keep.  I have copies of the lava and .cs which I will end up re-applying because of the changes we need to get the right transactions for our tax year in New Zealand (1 April to 31 March). 

If I can learn how to pick up a global attribute in the .cs - I will suggest what needs to be changed to accommodate international tax years for donation receipts.  (It's not hard.)

Ken

**Comment by nairdo** [comment]
Ok, then since you already have custom Lava (with your suggested changes), you can just keep it like that and your custom code should not be adversely effected by the change or the database migration.

**Comment by nairdo** [comment]
FYI: We updated a few other .lava files with the same approach: https://github.com/SparkDevNetwork/Rock/commit/a8900c4a9cb0fb60d3fc39cae6de0c641fbfb74f
