### ISSUE TITLE
[EN] Align Communication Preference options on My Account page

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3680]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Communication Preference options on the My Account page are not aligned.
As a result user cannot select different options.

### Steps to Reproduce

1. Login to external page.
2. Click "Hello {yourname}"
3. Click Update under your profile.  

![Comprefs](https://user-images.githubusercontent.com/4658177/57206968-f8150380-701d-11e9-9ac5-5bb2f8595022.jpg)

**Expected behavior:**

radio buttons should be aligned.
user should be able to select options.

**Actual behavior:**

radio buttons are unaligned.
user cannot select options.

### Versions

Version 74.0.3729.131 (Official Build) (64-bit)
Rock Version: Rock McKinley 8.6 (1.8.6.2)
Client Culture Setting: en-NZ

**Comment by JimMichael** [comment]
Note that this appears broken in Chrome and Safari for me, but FireFox looks normal.

**Comment by smross** [comment]
I can confirm that on my systems the same happens.
- Safari is broken
- Chrome is broken
- Firefox is ok

MacOS 10.14.4, Safari 12.1, Firefox 66.03, Chrome 73.0.3683.103, Rock v8.6 en-US

**The _Gender_ section also appears to have some formatting alignment issues**
<img width="231" alt="MyAccount-Gender" src="https://user-images.githubusercontent.com/8688424/57235445-7f478480-6fe8-11e9-9dbf-bad9c964f6fe.png">

**Comment by JimMichael** [comment]
@smross I believe the radio button alignment issue is this, fixed in v9 (or with a simple CSS mod) 
https://github.com/SparkDevNetwork/Rock/issues/3577

**Comment by cabal95** [comment]
Yes, that should be fixed in v9. If it is still showing that way in v9 please re-open and let us know!

**Comment by nairdo** [comment]
Here's the link for the commit that Garrett made in that fix that Jim referenced: https://github.com/SparkDevNetwork/Rock/commit/2993aa5c84fb188b9365b6ed72c153e354a9fb2f
