### ISSUE TITLE
Discount Codes ignore Maximum # of registrants it can apply to when navigating away from and back to the summary page

### ISSUE THREAD

**Issue by tcavaletto** [SparkDevNetwork/Rock#3681]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Registration Entry page will mark all registrants as 'Discount Applies' when a user navigates away from and back to the summary page. This poses an issue for manually entered discount codes that have a Maximum Registrant setting.

### Steps to Reproduce

1. Go to Demo Site
2. Add a Registration Template with a discount code (tested with a % code) that requires at least 2 registrants and applies to a max of one
3. Create an instance using the template
4. Go to the Registration Entry Page
5. Create a registration with 2 registrants
6. Once you get to the summary page, go back a page, and then forward to the summary.

**Expected behavior:**

The discount code to remain applied to a single person

**Actual behavior:**

The discount code is applied to all people. This is due to this line: https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/RegistrationEntry.ascx.cs#L5432. Can we just remove line? Looks like it's getting overridden anyways here: https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/RegistrationEntry.ascx.cs#L5484

A partial fix was introduced here, but only works for existing registrations: https://github.com/SparkDevNetwork/Rock/commit/7fcfe7f6ad3be3a26e0f8d1e7d8132887e14dac7

### Versions

* **Rock Version:** 8.6
* **Client Culture Setting:** En-US

**Comment by nairdo** [comment]
Fixed in https://github.com/SparkDevNetwork/Rock/commit/6db90bf54a67663cfb95c689bbce4e325bec0e2d
