### ISSUE TITLE
InactiveDateTime fields not populated

### ISSUE THREAD

**Issue by kenmulford** [SparkDevNetwork/Rock#3684]
### Description

When GroupMember records are inactivated via Rock, the `InactiveDateTime` field is not populated. This has been tested via Rock's Data Automation and via the UI.

### Steps to Reproduce

Inactivating a group member via the built-in data automation feature in Rock:
1. Run the Data Automation job
2. check group member records that were just inactivated. The `InactiveDateTime` field will still be NULL.

Inactivating a Group Member via the UI
1. Navigate to a Group record in the group viewer (/page/113)
2. Inactivate a group member.
3. Check the database to confirm that member's `InactiveDateTime` value is still NULL.

**Expected behavior:** 

In both cases I expect to see the `InactiveDateTime` field populated with a timestamp.

**Actual behavior:** 

The field was never populated.

### Versions

* **Rock Version:** 8.5
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Confirmed on pre-alpha on 5/7/2019.
