### ISSUE TITLE
On My Account page, updates to immediate Person Fields requires a manual page refresh after saving to display updated fields. Alpha v8.8

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3687]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

This is minor but noticed when updating a person's record from the external site on the My Account page, the immediate person fields do not update on save (name fields and suffix, age, gender, grade, email, and photo). The page requires a full refresh to display these updated person fields. All editable attributes and address update on postback and do not require a refresh. 

### Steps to Reproduce

1. Log in to a profile account on the external website and navigate to the the My Account page.
2. Click Update and update photo, name fields, age, grade, gender
3. Click Save. Screenshot the page or first section. These fields remain unchanged until a page refresh.
4. Refresh the page and compare the differences.

**Expected behavior:**

Expected behavior is new or changed fields would be reflected once saved. Additional attributes and contact info does but the immediate person fields require a page refresh.

**Actual behavior:**

Additional attributes and contact info does reflect the saved updates but the immediate person fields require a page refresh.

### Versions

* **Rock Version:** ALPHA v1.8.8.2, v8.7.6, v8.6 (demo server)
* **Client Culture Setting:** [en-US]

**Comment by JimMichael** [comment]
Confirmed
