### ISSUE TITLE
Shortcode: Googlemap Example -- <code> needs to be updated/corrected Alpha v8.8

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3688]
### Description
Minor documentation-type issue. Not certain what was intended but if you copy the example you'll get a warning before saving concerning the `<code>` tags (they are out of order and it's missing a closing `</p>` tag). Again, not certain what was intended but you could replace these three tags with a `<br>` unless a different UI look was intended.

```
{[ googlemap ]}
    [[ marker location:'33.640705,-112.280198' title:'Spark Global Headquarters']]
        <strong>Spark Global Headquarters</strong></code><p><code>
        It's not as grand as it sounds.<br>
        <img src="https://rockrms.blob.core.windows.net/misc/spark-logo.png" width="179" height="47">
    [[ endmarker ]]
    [[ marker location:'33.52764, -112.262571']][[ endmarker ]]
{[ endgooglemap ]}
```

### Steps to Reproduce
1. Go to CMS Configuration > Lava Shortcodes. 
1. Expand Google Map
1. Copy the Example code and place it in an HTML block.
1. See error

**Expected behavior:**

Not really sure what was intended.

**Actual behavior:**

The block provides a warning before saving about the missing tags.

### Versions
* **Rock Version:** ALPHA v1.8.8.2, v8.7, v8.6 (demo server)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1122843557006293">image.png</a>

**Comment by nairdo** [comment]
We tracked this one down to a fix that was made recently here: https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Migrations/Migrations/Version%209.0/Version%201.9.0/201906051958565_Rollup_0605.cs#L396
