### ISSUE TITLE
Connection State can manually be set to "connected" when configured to require placement group

### ISSUE THREAD

**Issue by gregdavis79** [SparkDevNetwork/Rock#3690]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
If you have a connection opportunity set to require a placement group to connect, the connection request should not allow for a state of "connected" to be set.

### Steps to Reproduce
1. Go to the connections page.  You must configure the connection group to require placement group to connect.
1. Click on an active connection request, then click on edit.
1. Select the state of "connected" and save the request.
1. The connection request is now in a state of connected.

**Expected behavior:**

The state of connected shouldn't be an option if the configuration is set to require a placement group to connect.  If a placement group is required, the user shouldn't be able to accidentally "connect" the request by simply changing the state.

**Actual behavior:**

The connection state behaves the same regardless of the require placement group setting.

### Versions
* **Rock Version:** Rock McKinley 8.7 (1.8.7)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
We've discussed this internally and are considering a change that could impact the staff currently using Rock -- but perhaps the impact would be seen as a very positive one.  Let me explain...

The "Connect" button and the "Connected" state are seen by some as the same (or similar), when in fact they are rather different.  When pressed, the Connect button will take the request's Requestor and put them into the group specified by the Placement Group (barring any "group member requirements") and then it sets the state to connected.  However, setting the **State** to "Connected" (and then pressing Save) really does nothing more.

## Connect Button
![image](https://user-images.githubusercontent.com/383807/181658456-91150765-d82a-40bf-bff9-f6fec6f63779.png)

(**Side Note:** If the connection type has the "Requires Placement Group to Connect" checked, then the Connect button is not enabled.)

![image](https://user-images.githubusercontent.com/383807/181658556-2975a52f-52d0-4759-b2d5-a026c08740c4.png)


## Connected State
![image](https://user-images.githubusercontent.com/383807/181658507-535c96f8-d798-4add-96a0-6d21556baab6.png)

A connector staff member could simply edit the request and set the state to Connected, but that does not add the person to any potential placement group.  Only the "Connect" button currently does that.


# Proposal
We're considering removing the "Connected" **State** as a selectable option from within the edit view (for all cases).  If we did that, the only way to put a request into the Connected state would be to press the Connect button.  We feel the operation of potentially putting a person into a group warrants the weight behind pressing a button.

**Comment by markewampler** [comment]
I think our view that we have to always double click on with our staff is that you do NOT put them in a "connected" state because we use connection requests ONLY for group placement currently.  So if they put them in a connected state it will "Fall off" their list of to do's even though they did not get put into a group.  The goal is to put a placement group and leave it as active then save, then click connect.  It is confusing to them so I would approve this change as it makes it less confusing for them as the only way to "Connect" someone is to use a placement group and then hit connect.

**Comment by asdf1nit** [comment]
I agree with this change. I have had the same experience with staff setting the state when they should have used the connect button. I think this would be a good change.

**Comment by mikedotmundy** [comment]
I like this change. It would eliminate confusion for our staff.

**Comment by nairdo** [comment]
## Resolved
Thanks everyone!  We've also been collecting some feedback from another channel and it's official: 
**We will be implementing this change for v14.**
