### ISSUE TITLE
Add Campus Filter block setting to Service Metrics Entry block

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3692]
# Feature Request

**Describe the Feature Request**

The block already has block settings for which schedule categories and which Metrics show up. We would like to add an additional option for selecting which Campus(es) show up. This would allow for additional security / sanity checks to ensure that people do not accidentally enter attendance on the wrong campus. We could have multiple pages, one for each campus, and set security correctly.

**Describe Preferred Solution**

* New block setting called `Campuses` that will be a multi-select.
* If no values are selected then it defaults to all campuses (current behavior).

**Describe Alternatives**

We could do the same with JavaScript, but that seems like an error-prone solution.

**Providing Code**
I will provide code if feature request is approved: **Yes**

**Comment by jonedmiston** [comment]
Approved
