### ISSUE TITLE
Location Field Type Doesn't Save Named Locations within a Matrix Attribute

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#3693]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When trying to select a named location in a Location field type within a Matrix attribute, the value selected is not retained on save.

### Steps to Reproduce

1. Create an Attribute Matrix Template and add a "Location" attribute to it.
2. Create a Matrix Attribute on the Campus entity (/page/193)
3. Edit a campus and select a named location in a row of the matrix attribute.
4. Save matrix attribute row.

![image](https://user-images.githubusercontent.com/2465823/57662613-3a11ec80-75be-11e9-9455-2bfec6ed1b56.png)

**Expected behavior:**

Selected named location should be saved within the matrix row it was selected in.

**Actual behavior:**

Selected named location is not saved within the matrix row it was selected in.

### Versions

* **Rock Version:** 1.9.0.16
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@briankalwat , I think I've replicated this issue, but want to verify you're seeing the same behavior.  Does yours behave like this (after the first attempt to pick a named location fails, you choose Location and try a second time it then works): 
   https://screencast-o-matic.com/embed?sc=cqhuo2TFQy&v=5&ff=1

**Comment by briankalwat** [comment]
@nairdo yes, that's exactly the behavior we were seeing.

**Comment by ethan-sparkdevnetwork** [comment]
For an immediate work-around you can click on the Location radio button (even though it is already selected) before selecting a named location.

**Comment by ethan-sparkdevnetwork** [comment]
The initial UI for the LocationPicker was showing Named location, but it was looking for an Address. Manually clicking the radio buttons would update the control and put them into agreement and it would work fine. I updated the LocationPicker to use Address as the default location type.

Also added configuration options to the LocationPickerFieldType. "Available Location Types" will filter the location types for the picker. "Default Location Type" will specify the initial picker type to load. This will simplify location selection using the field type in most cases.
