### ISSUE TITLE
EN - Align SMS and Unlisted options on Person bio page

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3697]
![SMS-Unlisted](https://user-images.githubusercontent.com/4658177/57752391-e1198580-769d-11e9-9dbe-65e3c13795d3.jpg)

### Versions
* **Rock Version:** [Enter Rock version here]
Rock Version: Rock McKinley 8.6 (1.8.6.2)

**Comment by nairdo** [comment]
Checks out ok on v8.8 over at https://rock.rocksolidchurchdemo.com/Person/4/Edit
