### ISSUE TITLE
Workflow Complete Action is not honoring the status the user is setting

### ISSUE THREAD

**Issue by JoshuaMaiorino** [SparkDevNetwork/Rock#3699]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using the `Complete Workflow` action, and supplying a status, The Workflow status isn't set.  It's set to the default, "Completed".

### Steps to Reproduce

1. Create a workflow action and update the Status text to something other than completed
2. Run the workflow

**Expected behavior:**

The final status of the workflow should be what ever status is given in the workflow action. i.e.  If the workflow has some type of approval process, the user may want the final status to be approved or denied.  The state already tells you that the it's complete, so forcing the status to also be complete upon completion of the workflow seems redundant.  ( Also, having a status inside the complete workflow action would be completely useless, because once it's run, the workflow would immediately change it any way, so that status will never be seen ).

**Actual behavior:**

The status is always completed.  Regardless of setting a different one in the action.

A description of what actually happened.

### Versions

* **Rock Version:** [8.6]
* **Client Culture Setting:** [en-us]

**Comment by Tschrock** [comment]
Hey Joshua, I've tested this on the demo site by creating a workflow with a "Complete Workflow" action with the Status field set to "Something Fancy", and when running the workflow the status appears to be set properly:

![firefox_2019-07-17_13-57-38](https://user-images.githubusercontent.com/2406499/61399153-8c5fda00-a89b-11e9-847f-60e52a7e9ea9.png)
![firefox_2019-07-17_13-58-03](https://user-images.githubusercontent.com/2406499/61399163-908bf780-a89b-11e9-9232-41428110a648.png)

Can you confirm if this is still an issue for you in the latest version of Rock (8.8)? Or if there are any additional steps I might need to try to replicate this?

**Comment by matthewalanwhite** [comment]
This is a not bug. 

<img width="839" alt="Manage_Workflows___Rock_RMS" src="https://user-images.githubusercontent.com/24526905/67490933-114c5380-f642-11e9-82bb-e199421c8999.png">

**Comment by nairdo** [comment]
Reported as resolved in the #bugapalooza channel.
