### ISSUE TITLE
Enable the Use of Lava Includes Within Defined Values

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#3703]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
We would love to be able to use lava includes within a defined value for the specific context of the Lava Templates defined type that generates RSS feeds, for a couple of reasons.

1. We would like to store the code that generates our feeds in a flat file under version control.
2. We would like to be able to use shortcodes that use a lava include to point back to a flat file within the context of defined values.

### Steps to Reproduce

1. Go to the Lava Templates defined type (/page/119?definedTypeId=48)
2. Update a defined value to include a lava include that points to a flat file `{% include '~~/Assets/Lava/OurFeed.lava' %}`
3. Visit the url for loading a feed using the template Id of the defined value you just updated `/GetChannelFeed.ashx?ChannelId=5&TemplateId=523`

**Expected behavior:**

The lava in the file that is linked in the lava include would be evaluated and the results served as the RSS feed.

**Actual behavior:**

The lava include is ignored and the page returns nothing.

### Versions

* **Rock Version:** [1.9.0.19]
* **Client Culture Setting:** [en-US]

**Comment by cabal95** [comment]
@briankalwat Can you try using the single tilde syntax?  i.e. base the path off the root instead of the theme?  The double tilde means "theme root", which doesn't make sense in this context because there is no page (and thus no theme) being loaded.  I'm not sure if this works, but it would be worth a shot. e.g.

```
{% include  '~/Themes/OurCustomTheme/Assets/Lava/OurFeed.lava' %}
```

and see if that by chance works.

**Comment by briankalwat** [comment]
@cabal95 this works perfectly. Thanks so much!
