### ISSUE TITLE
EN  - Person.PhoneNumbers lists numbers with no space between

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3705]
### Description

This is a nice to have.

{{ CurrentPerson | PhoneNumber:'Mobile' }} etc allows PhoneNumbers to be listed one by one (mobile, home, work).
I'm wondering if a another attribute could be added so they don't have to be listed one by one?  Person.PhoneNumbersAll ?
-----------------------

I set a text variable in a workflow, PhoneNumbers, using the 'Attribute Set From Entity' action, with Lava template: {{ Entity.Person.PhoneNumbers }}  (from a GroupMember entity).

When I use the variable in an email it lists the numbers without any space or separator: 

(04) 267-5057(21) 776-249(04) 269-0451

I would like to see (04) 267-5057 (21) 776-249 (04) 269-0451
or (04) 267-5057, (21) 776-249, (04) 269-0451
or Hm (04) 267-5057, Mob (21) 776-249, Wk (04) 269-0451

### Steps to Reproduce

Set a workflow variable to equal Person.PhoneNumbers, then use that variable in an email to view output format.

**Expected behavior:**

A list of phone numbers separated by a space, or a comma and a space.

**Actual behavior:**

The phone numbers are joined together with no separator.

### Versions
Rock Version: Rock McKinley 8.6 (1.8.6.2)
Client Culture Setting: en-NZ

**Comment by jonedmiston** [comment]
{{ Entity.Person.PhoneNumbers }} is an array of phone numbers. You might try using the Join filter. 

https://community.rockrms.com/lava/filters/array-filters#join

I quickly tested it with the Lava below and it appears to work well.

{{ CurrentPerson.PhoneNumbers | Join:', ' }}

**Comment by ElimAdmin** [comment]
Awesome!  Thanks Jon.
