### ISSUE TITLE
Signals cannot be assigned to different owner

### ISSUE THREAD

**Issue by jbeveland27** [SparkDevNetwork/Rock#3707]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * [x] Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * [x] Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * [x] Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When creating a Signal on a person, there's an option to select an `Owner`. Selecting an owner (that's different than the user creating the signal) has no effect when creating or editing the signal. 

### Steps to Reproduce
1. Go to `Security > Person Signal Types` and create a Signal type
1. Go to any person's profile
1. Click the `Security` tab, then click to add a new Signal.
1. Select a different Owner from the dropdown

**Expected behavior:**

The selected owner has ownership of the signal

**Actual behavior:**

The user creating the signal has ownership. Editing and selecting a different owner and re-saving the signal results in the same thing.

### Versions
* **Rock Version:** v8.7 [1.8.7.6] - latest [1.9.0.19] (happens on preAlpha currently)
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Thanks for the fix @jbeveland27 !
