### ISSUE TITLE
Matrix attributes not fillable or editable via Person Attribute Forms block

### ISSUE THREAD

**Issue by luke-infoministry** [SparkDevNetwork/Rock#3710]
### Description
On a Person Attribute Form on the external site, it is not possible to enter Attribute Matrix Items - clicking the + button initially is unresponsive, and after multiple attempts, the following error message appears.
<pre>
Error
Invalid postback or callback argument. Event validation is enabled using <pages enableEventValidation="true"/> in configuration or <%@ Page EnableEventValidation="true" %> in a page. For security purposes, this feature verifies that arguments to postback or callback events originate from the server control that originally rendered them. If the data is valid and expected, use the ClientScriptManager.RegisterForEventValidation method in order to register the postback or callback data for validation.

at System.Web.UI.ClientScriptManager.ValidateEvent(String uniqueId, String argument)
 at System.Web.UI.Control.ValidateEvent(String uniqueID, String eventArgument)
 at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
 at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
</pre>

Adding the '<%@ Page EnableEventValidation="true" %>' value in the page header doesn't affect the issue.

### Steps to Reproduce
1. Create an Attribute Matrix with some item attributes (Favorite Foods)
1. Create a Person Attribute with field type Matrix, select the newly created Attribute Matrix Template (Favorite Foods)
1. Add a Person Attribute Form block to a page, and add the Person Attribute to the form.
1. Attempt to add an item to the matrix attribute - on first click of the + button, nothing happens. On subsequent 'frustration' clicks, the above pasted error appears.

![<a href="https://user-images.githubusercontent.com/32314302/58111812-0bd87200-7ba7-11e9-8def-ef23076c9579.png">https://user-images.githubusercontent.com/32314302/58111812-0bd87200-7ba7-11e9-8def-ef23076c9579.png</a>]()

**Expected behavior:**

I would expect that, with sufficient permissions, (tested with alicia admin on demo site who has RSR - Rock Admin permissions) that the user would be able to add/edit/remove entries within the attribute matrix from the person attribute forms block.

**Actual behavior:**

The block is unresponsive to entry, edit, or removal attempts, before displaying an error message. 
If items already exist within the Person Attribute, they are shown on the Person Attribute Forms block, but may not be edited or deleted.

Tested on both internal and external sites on the demo site.

### Versions
* **Rock Version:** [Rock McKinley 8.6 (1.8.6.2), ]
* **Client Culture Setting:** [en-US]

**Comment by luke-infoministry** [comment]
Update with an observation: Matrix attribute entry works just fine in event registration forms.

**Comment by JRichmond27** [comment]
I just ran into this same issue on version 10.2
