### ISSUE TITLE
Workflow Lava Docs missing example code

### ISSUE THREAD

**Issue by milescarmany** [SparkDevNetwork/Rock#3711]
### Description
The introductory paragraph in the documention on [Workflows & Lava ](https://community.rockrms.com/lava/workflows) seems to reference inline code that is not present.

> For example, using a merge field of would return a GUID since that is how the Person type attribute stores its value.

Could be changed to 

> For example, using a merge field of `example code` would return a GUID since that is how the Person type attribute stores its value.

Documentation accessed on 21 May 2019.

**Comment by nairdo** [comment]
Thanks! Updated: https://community.rockrms.com/lava/workflows
