### ISSUE TITLE
Check-in Group Type Schedule Exclusion not followed when used in check-in with named schedules

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3712]
### Description
Setting a Schedule Exclusion on a Group Type doesn't remove that Group Type from Check-in when it is scheduled using Named Schedules. The Schedule Exclusions work great for our Connect Groups, which use Custom schedules and doesn't use check-in, but we have Kid Connect Groups that use our Sunday Service schedules and the Group Type Schedule Exclusion doesn't work or isn't processed in the workflow filter. When a Schedule Exclusion is added on the Group Type, check-in doesn't follow the exclusion(s) and still displays the groups as active to check in.

### Steps to Reproduce
1. Select a check-in group type from General Settings > Group Types and in the Attendance / Check-in area settings set Schedule Exclusions to today's date (in the demo server I updated the Elementary Area Group Type). Save
1. Modify a Schedule to be active today and make sure that a group from the modified Group Type is set to be active on today's schedule.
1. Check in an eligible person for the group (any of the Elementary Area groups).

**Expected behavior:**

The expected behavior is not to be able to check in anyone for the Elementary Area groups if today's date is within the exclusion time period on the Group Type. 

**Actual behavior:**

The person(s) is able to check into groups that have schedule exclusions on the Group Type. So from the example above, the Decker family is able to check in the kids to their elementary groups despite the schedule exclusion.

### Versions
* **Rock Version:** v8.7 v8.6 (demo server)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1127459201798687">image.png</a>

**Comment by nairdo** [comment]
Greetings @BEGamache, the original intent of that **Schedule Exclusions** setting was to provide the entire set of groups a way to 'go on a season break' and signal the attendance **reminder job** so it wouldn't continue sending attendance reminders to group leaders.  However, since we didn't label that field all so great, we see how it could be construed as you have.  

Therefore, we're going to add it to the work list -- and make the check-in system's workflow actions (namely LoadGroupTypes) are aware of group type schedule exclusions.

**Comment by BEGamache** [comment]
Thanks @nairdo! That makes sense. Thanks for adding it to the work list. I appreciate it.

**Comment by karenn-ccbc** [comment]
Thank you for adding this.  I am pretty sure that it previously worked to exclude checkin but we noticed this year after updating to 15.2 that it did not work on Christmas eve when it fell on a sunday. We have used it previously for Easter services.
