### ISSUE TITLE
Fundraising Matching - Replacing matched transactions in batch

### ISSUE THREAD

**Issue by lizrose20** [SparkDevNetwork/Rock#3714]
### Description
When matching funds for 2 group types, the first will be replaced with any matching/non-matching that is done in the 2nd group type within the same batch.

### Steps to Reproduce
1. Set up 2 fundraising group types
  1. a. Internship Matching
  1. b. Fundraising Matching
1. Go to Fundraising Matching
1. Match a fund in a batch.
1. Hit save
1. Go into Internship Matching 
1. Match a fund from the same batch as step 3.
1. Hit save
1. Go to the Group Viewer
1. Select the fundraising group that you had changed in step 3.
1. You will see that the funds are not there. 

**Expected behavior:**

We expected that if a fund had been matched it would stay matched unless selected not to be.

**Actual behavior:**

The fund was replaced by the 2nd group type being matched within the same batch.

### Versions
* **Rock Version:** Rock McKinley 8.7 (1.8.7.6)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@lizrose20  In step 1, are you really suggesting that one would set up a second "group type" like the _Fundraising Opportunity_ group type?  Or did you just mean set up two _groups_ that are of type Fundraising Opportunity?

**Comment by cabal95** [comment]
@lizrose20 I'm also a little vague on the exact issue you are seeing, but it sounds like it might be related to (or the same as) this issue that was fixed in 8.8. Since you are on 8.7 it might have already been fixed: https://github.com/SparkDevNetwork/Rock/issues/3599

**Comment by lizrose20** [comment]
> @lizrose20 In step 1, are you really suggesting that one would set up a second "group type" like the _Fundraising Opportunity_ group type? Or did you just mean set up two _groups_ that are of type Fundraising Opportunity?

Yes, we have 2 group types.  One for our mission groups and one for our intern group.

**Comment by lizrose20** [comment]
> @lizrose20 I'm also a little vague on the exact issue you are seeing, but it sounds like it might be related to (or the same as) this issue that was fixed in 8.8. Since you are on 8.7 it might have already been fixed: #3599

I don't believe this is the same.  We also had that issue, but this is when we had 2 different group types in the same batch that have fundraise matching. If we match for one group type, it would overwrite the other group types matching. We are currently just pulling these aside and creating a batch for each type, which then allows to match as it should.  This work around is working for us.

**Comment by nairdo** [comment]
> Yes, we have 2 group types.

Ok, this would be the issue.  The way the Fundraising system works, it depends on that particular system group type called "Fundraising Opportunity" (4BE7FC44-332D-40A8-978E-47B7035D7A0C).  It's not possible to have a second group **_type_** -- all the groups must be based of that single "Fundraising Opportunity" group type.

**Comment by nairdo** [comment]
I did confirm that the Fundraising Donation List, Fundraising List, and Fundraising Progress blocks are only designed to work with the special system "Fundraising Opportunity" group type (seen here https://rock.rocksolidchurchdemo.com/page/117?groupTypeId=31).  So, it would have been expected that you would set up various groups, and some would have the "Trip" opportunity type and some would have the "Internship" opportunity type:

![image](https://user-images.githubusercontent.com/383807/62794684-94213180-ba89-11e9-99d8-066812a2d041.png)

In this case, the Fundraising Matching block (aka Transaction Entity Matching) works correctly.  And you would be able to see those funds show up on the Group Details block like so:

![image](https://user-images.githubusercontent.com/383807/62796392-ff6d0280-ba8d-11e9-9260-1e2c1dd14b0e.png)


Having said that, I did find the spot in the code where -- if you:

1. use the same batch...
2. change the block setting to use a different group type...
3. did not specify any selection for a particular transaction that is shown...

...it would unset the previously matched transaction (to reflect what is shown on screen):
![image](https://user-images.githubusercontent.com/383807/62796834-07797200-ba8f-11e9-9140-4da907f970f4.png)

I don't think it was ever expected that you would change the block settings between different group types and use the same batch as well.

Regardless, I'm changing that block such that it only sets the transactions for the rows that have a selected item (group member in this particular case).

**Comment by jcjones37** [comment]
@nairdo question - If someone wanted to set up a Group Tree (viewer) on its own page with one specific fundraising type... that would not be possible with the fundraising opportunity correct?  Therefor one would need to create a different group type for that specific Fundraising Opportunity in order for that opportunity to appear in its own tree.  right?  I may need to process more offline...

**Comment by jeremyhoff** [comment]
@jcjones37 If I understand your question correctly, you can use Security to show/hide groups in a tree regardless of Group Type. Couple that with the Block Config "Root Group" you should be able to setup a tree viewer to suit your needs.

Until the site is refreshed, you can review the following links to two different Fundraising Opportunity Group Trees:
https://rock.rocksolidchurchdemo.com/page/1571?GroupId=1215&ExpandedIds=
https://rock.rocksolidchurchdemo.com/page/1580?GroupId=1214

Both Trees visible here:
https://rock.rocksolidchurchdemo.com/page/113?GroupId=1212

And of course, also visible in NAV.

Hope that helps,
