### ISSUE TITLE
Addresses entered on Internal Edit Family page/block displays on one line after save

### ISSUE THREAD

**Issue by alyssa-pathway** [SparkDevNetwork/Rock#3716]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When we add an address to a family, we are seeing that there are no breaks in the address between the street address and city/state/zip. it displays on one line. It also displays on one line in an address label merge template.
![image](https://user-images.githubusercontent.com/29411182/58284169-ac798e00-7d6f-11e9-8c77-72e8388855f4.png)

### Steps to Reproduce
1. Go to a person's profile
1. Click on the edit family pencil
1. Add a valid address
1. Click Save
1. See that the address you entered is on one line.

**Expected behavior:**

Address should have breaks.

Street Address 1
Street Address 2
City, State, Zip

**Actual behavior:**

Address is on one line:
Street Address 1 Street Address 2 City, State Zip

### Versions
* **Rock Version:** [8.7]
* **Client Culture Setting:** [ENG - US]

**Comment by ElimAdmin** [comment]
I have seen this once, but haven't recreated.

**Comment by nairdo** [comment]
Based on some quick testing, I believe this issue has been corrected in v9.  @ElimAdmin or @alyssa-pathway , are you able to confirm this with me by trying to reproduce this issue on the pre-alpha site? https://prealpha.rocksolidchurchdemo.com/Person/1

**Comment by alyssa-pathway** [comment]
@nairdo - It looks fixed to me in pre-alpha!

**Comment by nairdo** [comment]
Reported as resolved in the #bugapalooza channel.
