### ISSUE TITLE
Custom Grid Option on Batch List page doesn't pull Id

### ISSUE THREAD

**Issue by eddieholeman** [SparkDevNetwork/Rock#3717]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When I add a Column in Custom Grid Options on the Batch List page, I attempt to place `{{ Row.Id }}` in the lava template and am returned the following error: "Liquid syntax error: Object 'RockWeb.Blocks.Finance.BatchList+BatchRow' is invalid because it is neither a built-in type nor implements ILiquidizable". If I change that to `{{ row.Id }}`, I get no error, but no data.  I am doing this to ultimately provide a link to a dynamic data block report and passing the BatchId parameter to this report.

### Steps to Reproduce
1. Go to Finance > Batches
1. Go to the Block Settings of the Batch List and move to the Custom Grid Options.
1. Click Add Column and type {{ Row.Id }} in the Lava Template.
1. Click Save and see error

### Versions
* **Rock Version:** [8.7]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Hi Eddie, that block uses a trick to improve its performance... which _basically_ only gives the grid a handful of items to work with (and doesn't expose them to the Lava).  If you had access to just the batch Id and a few of the other basic properties of the batch, would that suffice?
