### ISSUE TITLE
Adding a Range option/condition to the Birth Month Data View Filter 

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3718]
# Feature Request

**Describe the Feature Request**
We were trying to pull a report of kids (1s, 2s, and 3 year olds) with birthdays in the upcoming month. We don't want kids from this month so Days Until Birthday won't work. Birth Month would work well but it doesn't have conditionals for a Range like upcoming, last, next, past, previous, etc.

**Describe Preferred Solution**
I believe Birth Month is stored and treated as an integer. Since that is the case, would it be possible to add the Range option and treat the time frame as integer math operations? ( I suppose the same could apply for the Birth Day filter ). I don't know how the Range option is currently set up in the code so it may already work as such, and if that is the case could it be easily included in the Birth Month filter?

**Describe Alternatives**
For the time being we are using Birth Month but specifying the month we want, unfortunately, they will have to go in every month to update the data view.

**Providing Code**
I will provide code if feature request is approved: No

**Comment by JimMichael** [comment]
Is there a reason filtering on Birthdate with Range = Upcoming 1 Month won't work?
![image](https://user-images.githubusercontent.com/3903408/58292016-531c5980-7d85-11e9-8ba0-59da6d9bab4c.png)

**Comment by BEGamache** [comment]
We definitely tried that filter option and hoped it would work but it doesn’t work since the year is included. I tested it on our servers and the demo server. I could only pull people when I did less than today’s date but couldn’t do upcoming. Upcoming would be pulling those not born yet essentially—from what I understand since the year is included.

**Comment by jonedmiston** [comment]
@BEGamache we're trying to keep issue just for bugs. Can you add your suggestion to our Idea board?

https://community.rockrms.com/Ideas
