### ISSUE TITLE
Merge Issue: Creates thousands of recipients instead of ones selected

### ISSUE THREAD

**Issue by TerriBorchardt** [SparkDevNetwork/Rock#3719]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)? I didn't try a demo site.
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting? Rock version is 8.7. I don't know what "client culture" is.
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported? Yes

### Description
A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce
1. Go to 'Reports'
1. Click on 'Membership YTD' or any other report that you would normally want to use a merge template for
1. Select two people to merge, or 10 or 20
1. Merge records
1. You get the total number of people (50, 500, etc. that are being viewed on the screen), not the two people you want to send a letter to - see snapshot examples below.

![image](https://user-images.githubusercontent.com/44209657/58292579-b3f06580-7d76-11e9-9a0f-8938ae0c5f7b.png)

![image](https://user-images.githubusercontent.com/44209657/58292781-8821af80-7d77-11e9-90c7-ca6dfa8973c4.png)

**I expect to get two people or the number of people I have checked off, not the entire list of people on the report:**

* **Rock Version:** [Rock McKinley 8.7]

**Comment by nairdo** [comment]
@TerriBorchardt  I was able to confirm this is related-to/duplicate-of #3593 and [confirmed it is fixed ](https://github.com/SparkDevNetwork/Rock/commit/125f6ae432720be540fa4402e65058edd016829c#diff-c1e3cf0109163046d12304f8b0a40540) on the demo site which I just updated to v8.8 beta.

**Comment by TerriBorchardt** [comment]
Thanks so much! Looking forward to the update to v8.8 as soon as it’s available to me.
