### ISSUE TITLE
LandingPage Theme Not Editable

### ISSUE THREAD

**Issue by morganw93** [SparkDevNetwork/Rock#3721]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Rock Version 8.7
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When going to Admin Tools->CMS Configuration->Themes->LandingPages, the theme displays the following error. 
![Screen Shot 2019-05-28 at 10 53 52 AM](https://user-images.githubusercontent.com/30188136/58501476-20d67780-814a-11e9-89da-d9e911e52101.png)

The demo has the same error when trying to edit the theme. 
In the server files the _variable-override.less file is missing from our instance. I was able to get this file off of GitHub and upload it to our server and this resolved the issue. After doing this editing the logo width attributes on the theme did not work (got the error: Unable to Compile) but everything else seemed to be working. 

### Steps to Reproduce

1. Go to Admin Tools->CMS Configuration->Themes->LandingPages,
2. Click on the LandingPage Theme
3. See error

### Versions

* **Rock Version:** 8.7
* **Client Culture Setting:**[en-US]

**Comment by morganw93** [comment]
If possible could the ability to edit the text(fonts) be added to the landing page theme. This is all I can see when editing the Landing Page Theme.
![Screen Shot 2019-05-28 at 1 25 15 PM](https://user-images.githubusercontent.com/30188136/58502420-174e0f00-814c-11e9-9e38-c036a96f6be3.png)
![Screen Shot 2019-05-28 at 1 25 23 PM](https://user-images.githubusercontent.com/30188136/58502421-174e0f00-814c-11e9-8ae4-26a924818b2d.png)

**Comment by morganw93** [comment]
Also the _css-overrides.less file is missing.

**Comment by JayGreentree** [comment]
> Also the _css-overrides.less file is missing.

You can grab thos from the repo https://github.com/SparkDevNetwork/Rock/tree/develop/RockWeb/Themes/LandingPage/Styles this should fix your issue
