### ISSUE TITLE
Event Registration Group Member Attribute Show On Grid Broken

### ISSUE THREAD

**Issue by BemaDavidBensen** [SparkDevNetwork/Rock#3725]
### Description
Event Registration, Group Member Attributes Field, show on grid check mark, hides all registrants from showing up on the registrants tab 

### Steps to Reproduce
1. Add a Group Attribute to the registration form and check mark show on grid
1. Go to the registrants tab
1. See that no registrants now show up

**Expected behavior:**

The show on grid features should not hide all registrants

**Actual behavior:**

All registrants in the registrants tab are no longer visible

### Versions
* **Rock Version:** Test on 8.5 and prealpha build 
* **Client Culture Setting:** en-us

**Comment by cabal95** [comment]
Can you provide a screenshot of how you have configured the  attribute? We  haven't run into this and I wonder if it is related to a specific type of attribute or specific attribute configuration.  We use the "Show on Grid" all the time with event registration and have never run into this yet.

**Comment by JimMichael** [comment]
I cannot dupe this on 8.8, either. I added a Registration Attribute of type Group to an existing registration with Show On Grid enabled. It shows on the Registrants tab (along with all registrants) just fine.

**Comment by BemaDavidBensen** [comment]
This is only for Group Member Attributes, all other attributes appear to be fine, see my screenshots for how I set it up

<img width="1019" alt="Screen Shot 2019-05-30 at 11 06 04 AM" src="https://user-images.githubusercontent.com/29557172/58646538-3921d000-82cb-11e9-84da-4a831f42c6b5.png">

<img width="973" alt="Screen Shot 2019-05-30 at 11 06 09 AM" src="https://user-images.githubusercontent.com/29557172/58646555-3e7f1a80-82cb-11e9-8602-088b8a925008.png">

<img width="1205" alt="Screen Shot 2019-05-30 at 11 06 47 AM" src="https://user-images.githubusercontent.com/29557172/58646565-43dc6500-82cb-11e9-8d31-e63fc7845e53.png">

Link to the event on the pre-alpha site as well. This is tested on the normal demo site too. 
https://prealpha.rocksolidchurchdemo.com/RegistrationInstance/5

**Comment by JimMichael** [comment]
Ah, ok... the title and initial description probably should be updated then, as I took "Group Attribute" to mean "registration attribute of type group" :-D

**Comment by nairdo** [comment]
I was able to reproduce.  The issue appears to be with the filterControl in thsi section. https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/RegistrationInstanceDetail.ascx.cs#L3560

**Comment by nairdo** [comment]
I'm sorry! I was incorrect. After further discussion, it turns out that the "Show on Grid" field is not supposed to be showing for Group Member attributes on the Registrant Form Field panel.

So, the plan is: That checkbox will be hidden on on that panel for Group Member Attributes.

Also, similar to the way you would go to person profile (internally) to edit fields on the person, you would also go the to Group Member details which you can do by clicking on their group link as seen in this screenshot:
![image](https://user-images.githubusercontent.com/383807/60473515-3d227400-9c22-11e9-814b-b9d7d4abbb38.png)
