### ISSUE TITLE
Typo in Message Detail - Channel Item Configuration - Lava Template for 'Item | Speaker'

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3731]
### Prerequisites
* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The speaker for a Podcast is not showing up due to a type in the Channel Item Configuration Lava Template.

### Steps to Reproduce

1. Go to
Home > Watch > Series Detail > Message Detail
https://rock.rocksolidchurchdemo.com/page/461?Item=33 in the demo site.

Note that the speaker does not appear under title, just the message date:

] Of Faith and Firsts
]  - 6/26/2016

2. Open the Content Channel View Detail block.
3. View line 14 of the Lava Template:
		<strong> {{ item | Attribute:'Speaker' }} - {{ Item.StartDateTime | Date:'M/d/yyyy' }}</strong>

**item I Attribute:'Speaker'** 
should read
**Item | Attribute:'Speaker'**  (capital I on Item).

**Expected behavior:**

Speaker should show on the sample Podast Message Channel Item.

**Actual behavior:**

Typo in the lava prevents Speaker from correctly showing.

### Versions

Rock Version: Rock McKinley 8.8 (1.8.8.3)  (demo site)
Client Culture Setting: en-NZ

**Comment by nairdo** [comment]
Thanks.  I created the needed data migration and added it to our internal migration-rollup list for the next pre-alpha in two weeks.  This will be fixed in v9.

**Comment by ElimAdmin** [comment]
@nairdo  Cool stuff!
