### ISSUE TITLE
Add an entry field for Deceased Date on person profile

### ISSUE THREAD

**Issue by TheCoreyHall** [SparkDevNetwork/Rock#3734]
# Feature Request
**Describe the Feature Request**
DeceasedDate was added as a column in the person table as a field, but as far as I can tell, it is unused in Rock. One of my clients uses a Deceased Date person attribute to store this information because of that. However, since the DeceasedDate field exists, it still shows up as selection options in dataviews/reports, confusing staff members who dont know the difference between the two fields.

![image](https://user-images.githubusercontent.com/38293092/59121924-f7be9f80-891e-11e9-8d83-d0cdbb514a99.png)

**Describe Preferred Solution**
Inside the Edit Person block, add another field for Deceased Date entry, as well as display the field in person profile Bio bar if it exists like the other person fields. This would allow us to use the built in DeceasedDate field without having to rely on extra attributes.

**Describe Alternatives**
Hide the DeceasedDate property from selection in reports/data views.

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1127838690812476">image.png</a>

**Comment by cabal95** [comment]
For some extra context, this could be considered a bug.

Specifically, if this column/property has been deprecated and had it's UI removed, then it needs to be marked as such and be hidden from reporting. (Issue here is if you add an attribute to store the Deceased Date then in reporting you get two choices and have to hope your users pick the correct one).

If this column/property was recently added but the UI never built, then it needs to be built or at least documented somewhere why there is no UI and how it is supposed to be used.

**Comment by nairdo** [comment]
`DeceasedDate` was added on 5/17/2018 (for v8).  I believe it was to store data that was being imported from another system.  Although not here now, I _believe_ there will be UI for setting that field.  I will verify this and put a plan in place.  Once the UI happens, you may want to assist your client with a script move of all their custom DeceasedDate attribute-based data to the property data.
