### ISSUE TITLE
[EN] Groups API get request doesn't return archived groups

### ISSUE THREAD

**Issue by ickyfeet** [SparkDevNetwork/Rock#3743]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When making an API GET request for on the Groups endpoint archived groups are not returned.  All groups should be returned, let the user filter results please.

### Steps to Reproduce

Make an http get request 

```https://rock.rocksolidchurchdemo.com/api/Groups?$filter=Id eq 58``` returns empty 
```https://rock.rocksolidchurchdemo.com/api/Groups?$filter=Id eq 58 and IsArchived eq true``` returns empty 
```https://rock.rocksolidchurchdemo.com/api/Groups?$filter=GroupTypeId eq 23``` returns all groups except the archived groups 
```https://rock.rocksolidchurchdemo.com/api/Groups?$filter=GroupTypeId eq 23 and IsArchived eq true``` returns empty 

**Expected behavior:**

Archived groups should be included in the results
When requesting data ALL the data should be returned and the user should filter the data

**Actual behavior:**

Archived groups are not returned in the results

### Versions

Rock Version: Rock McKinley 8.7 (1.8.7.6)

Client Culture Setting: en-US

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
