### ISSUE TITLE
Exception Occurs Trying To Delete Content Item from Detail Block

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#3744]
Submitted on behalf of https://www.thecrossingchurch.com/

### Description
The Content Item Detail block has a "Show Delete Button" setting that can be used to display a Delete button. If you enable this option and then try to use the button to delete the content item, an exception occurs due to a foreign key restraint with Content Channel Item Slug:

> The DELETE statement conflicted with the REFERENCE constraint "FK_dbo.ContentChannelItemSlug_dbo.ContentChannelItem_ContentChannelItemId". The conflict occurred in database "rockdemo", table "dbo.ContentChannelItemSlug", column 'ContentChannelItemId'. The statement has been terminated.

A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce
1. Go to a content item detail block page (https://rock.rocksolidchurchdemo.com/page/344?contentItemId=9)
1. Edit the block settings and set "Show Delete Button" to "Yes"
1. Click the Delete option that is now displayed

**Expected behavior:**

The Content Item (and it's slugs) are deleted.

**Actual behavior:**

An exception occurs

### Versions
* **Rock Version:** Rock McKinley 8.8 (1.8.8.3)
* **Client Culture Setting:** en-US

**Comment by azturner** [comment]
This exception also occurs if you try to delete a child content item. For example, If you try to delete one of the child items on this page: https://rock.rocksolidchurchdemo.com/page/344?contentItemId=21, you will get the same exception.

**Comment by nairdo** [comment]
The fix above is only a partial fix regarding the content channel slugs.  An additional fix will come in release 1.9.1 to deal with the rest of this issue.
