### ISSUE TITLE
Follow Person from Person Detail Fails with Impersonation On

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#3746]
### Description
When attempting to follow a person from their Person Detail page while you are impersonating another user, the action will fail with a 500 error logged in the Java Script console.  I believe that this issue may have a broader scope because it is throwing the exception on the POST method of the base API controller, but I have only confirmed it with the Follow Person feature.

### Steps to Reproduce
1. Log in as a Rock Administration 
1. Ensure that the Enable Impersonation feature is enabled on the Bio block
1. Load a Person's profile that has access to the Person Detail page (i.e. on the demo site I used Ted Decker)
1.  Impersonate the person
1. Click on the Following Icon on their picture. No change will occur
1. Check your JS console for the 500 status code/error (Chrome says: Failed to load resource: The server responded with a status of 500 (). and references api/followings as the source of the error).

**Expected behavior:**

The star icon is illuminated indicating that the person has been added to your following list.

**Actual behavior:**

No changes happen on the Bio Rock Block and a 500 error is logged in the Java Script console.

### Versions
* **Rock Version:** 1.8.8.3 (v 8.8)
* **Client Culture Setting:** en-us

**Comment by ethan-sparkdevnetwork** [comment]
It looks like the updates and fixes done to the Following REST controller, Impersonation, and the Person Bio block have fixed the issue. Verified this is no longer occurring in v16.1. Let us know if you are still encountering this issue.
