### ISSUE TITLE
Process Signature Documents Error with Azure Storage Provider

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#3747]
### Description
We attempted to offload the storage of our Signature Documents to an Azure Blob Container using Pillar's Blob Storage provider plugin. After doing this, we started receiving error messages when the Process Signature Documents job downloaded the signature files.  We are getting errors that after downloading and processing the signature document that the file is in use by another process when the job attempts to delete the temporary file from the cache folder and causing the job to fail after downloading the first signed document. ( exception happens at https://github.com/SparkDevNetwork/Rock/blob/074fa4ffcca387a15c3f7f2903296b5a4388f659/Rock/Model/SignatureDocumentTemplateService.Partial.cs#L320)

I am going to cross post this issue with the storage provider's vendor because I am not sure where the bug actually lies.

### Steps to Reproduce
1. Ensure that you have the Azure Storage provider installed and configured in your Rock Instance
1. Update the file provider for the Digitally Signed Documents file type to use the Azure provider and provide the necessary information
1. Create a signature request in Rock and send it to sign now
1. Sign the document 
1. Attempt to run job to retrieve the signed document

**Expected behavior:**

I expected the digitally signed documents to be downloaded from Sign Now and saved to storage provider, with the temporary files removed from the cache folder.

**Actual behavior:**

First signed document is downloaded and job fails when removing file from the cache folder.

### Versions
* **Rock Version:** 1.8.8.3
* **Client Culture Setting:** en-us

**Comment by azturner** [comment]
This was an issue with the Azure Storage Provider. When saving a new file, it was not closing the stream that was provided. It has been fixed in version 1.5 of the plugin.
