### ISSUE TITLE
Workflow WebRequest Action creates invalid Content-Type header for JSON

### ISSUE THREAD

**Issue by garyholeman** [SparkDevNetwork/Rock#3749]
**Reproduced on my own RockRMS installation and on the demo site.**

Diagnostics File Attached**

### Description
As best I can tell, the Workflow Action WebReqest for JSON content cannot be made to work. 
 There appears to me to be a bug in the code that sets the Content-Type header to "JSON" rather than to "application/json".  This does not seem to be a supported value from my reading and in my debugging steps is the source of the problem.  I have attached web packets from the Workflow WebRequest action (highlighting the invalid header) and web packets from a successful HTTP POST from another tool doing the same RESTAPI call, highlighting the correct header used.  Unfortunately, the Workflow WebRequest Action does not let me override the Content-Type header by creating my own header. If it helps to understand what I'm trying to do, this HTTP POST is a RestAPI login request to a Rocket.Chat server.

### Steps to Reproduce
1. Create Workflow with a WebRequest Action using POST and a JSON body
1. Execute Workflow
1. Observe a 401 return

**Expected behavior:**

Should receive a 200 response with a JSON response with "status" : "success" in it.

**Actual behavior:**

Receive a 401 error

### Versions
* **Rock Version:** [Rock McKinley 8.6 (1.8.6.2)]   and Rock McKinley 8.8 (1.8.8.3) (demo site)
* **Client Culture Setting:** [en-US] 

[RockRMSDiagnostics.pdf ](https://github.com/SparkDevNetwork/Rock/files/3291857/RockRMSDiagnostics.pdf)
[RockRMSWorkflowActionWebRequestIssue.pdf ](https://github.com/SparkDevNetwork/Rock/files/3291858/RockRMSWorkflowActionWebRequestIssue.pdf)

**Comment by eddieholeman** [comment]
I just tested this from my instance of Rock at Fellowship Greenville and got the same results "{"status":"error","message":"API endpoint does not exist"}". Really need to get this web call to work.

**Comment by garyholeman** [comment]
I did some further testing, creating a workflow with a webrequest action to login to the rocksolidchurchdemo.com site, which I've successfully done using POSTMAN.  I also installed Fiddler on my Azure VM that is hosting the RockRMS site in which I'm creating the workflows so that I can watch the traffic as it leaves the machine hosting RockRMS rather than at the endpoint site.  The result I get is the same, though RockRMS gives back a more specific error that makes the issue very clear.  It gives back a 415 Unsupported Media Type and you can see in the below screenshot that it is JSON rather than application/json in the Content-Type.  I've been going through the source code for RockRMS to try to find the issue.  It would appear to me that the RequestContentType is being set to Dataformat.Json, which should be defined by the RestSharp library.  Is it possible that you're using an old version of the RestSharp library that had a bug in it?  I've downloaded the RestSharp library and am looking, but haven't yet found the source of the invalid Content-Type.  I'll keep looking.

<img width="348" alt="WorkflowWebRequest-RockRMS" src="https://user-images.githubusercontent.com/1134587/59577108-4e9b4600-9090-11e9-9027-ef280189f7e4.png">

**Comment by garyholeman** [comment]
Wow.  Thanks, @nairdo, for your quick response.  I reviewed the code change you made and can clearly see what was happening.  I will work in a sandbox environment to make this change in our current 8.x environment so that we can continue on with our development.  This will be my first opportunity to understand the process of building this in our environment.

**Comment by garyholeman** [comment]
If you don't mind, I'll keep this open until I confirm the fix in our 8.x environment and then I'll close it, just to close the loop cleanly.

**Comment by garyholeman** [comment]
I thought I could figure out how to deploy a hotfix to my sandbox server, but I haven't been able to determine on my own or by reading documentation how to do it.  The source code changes made using Visual Studio Community 2019 (is that OK?  I can't see how to get 2017) produced 3 new .dll files, 3 associated .pdb files, and an .xml file.  I haven't developed in the ASP.NET environment.  I tried just copying the .dll and .xml files to the /bin directory on the IIS server, restarting the server.  But then rock won't run. Any chance you could point me to something that explains how to build a hotfix deployment for this?  Sorry for asking.

**Comment by garyholeman** [comment]
I was able to make the source code changes from this commit into a local copy of 8.8 and test it successfully.  These changes do fix this bug.
