### ISSUE TITLE
Universal Search Error Using Specific Characters

### ISSUE THREAD

**Issue by matthewalanwhite** [SparkDevNetwork/Rock#3753]
### Description
When typing in a character into Universal Search it errors out, specifically a question mark (?).

### Steps to Reproduce
1. Go to the search bar, using Universal Search, and search using only ?
1. Click on 'Clear Filter'

**Expected behavior:**

Some sort of message indicating that is not an allowed character.

**Actual behavior:**

Returns the "That Wasn't Supposed to Happen..." page. [and an exception was logged "A potentially dangerous Request.Path value was detected from the client (?)."]

### Versions
* **Rock Version:** [Rock McKinley 9.0 (1.9.0.19)]
* **Client Culture Setting:** [en-US]

**Comment by MrUpsideDown** [comment]
Fixed with this commit: https://github.com/SparkDevNetwork/Rock/commit/a50be22fdef916bc5914de7e6a8a7f2746ef1781
