### ISSUE TITLE
Including a Quotation Mark in The Name of a Dataview prevents the Permissions Modal from Opening

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/Rock#3754]
### Description
If a dataview contains a quotation mark (") the permissions modal will not open.

### Steps to Reproduce
1. Go to the dataview page (https://rock.rocksolidchurchdemo.com/page/145?CategoryId=131&ExpandedIds=C131%2CC166)
1. Create a dataview with a quotation mark (") in the name of the dataview
1. Attempt to open the Permissions Modal by clicking the padlock icon
1. Observe that the modal does not open

**Expected behavior:**

Expected the Permissions modal to open.

**Actual behavior:**

Permissions modal does not open.

### Versions
Tested on Demo Site:

* **Rock Version:** Rock McKinley 8.8 (1.8.8.3)
* **Client Culture Setting:** en-US

Tested on Church's Production Server:

* **Rock Version:** Rock McKinley 8.7 (1.8.7.5)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
This looks like it would be a problem with Reports too. Possibly other entity types.  The name of the DataView/Report is put in the URL string for the dialog, but it isn't escaped properly so it causes an error.
