### ISSUE TITLE
Lava Execute Command can't use system types in class mode

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3765]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using a Lava Execute Command with type:'class', system classes like `String`, `Byte`, and `DateTime` are not directly available.

----------

#### Example 1
The current lava documentation states "don't import System ... The way the script is run you will not need it."
Given that description, I would expect the following to work:
```liquid
{% execute type:'class' %}
    public class TestScript 
    {
        public string Execute() {
            return DateTime.Now.ToString();
        }
    }
{% endexecute %}
```
Actual output:
```
Liquid error: (5,20): error CS0103: The name `DateTime' does not exist in the current context
```

----------

#### Example 2
Ignoring the lava documentation, we can try to add a System import, but that seems to get filtered out:
```liquid
{% execute type:'class' %}
    using System;
    public class TestScript 
    {
        public string Execute() {
            return DateTime.Now.ToString();
        }
    }
{% endexecute %}
```
Output:
```
Liquid error: (5,20): error CS0103: The name `DateTime' does not exist in the current context
```

----------

#### Workaround 1
We can use the full type name to avoid needing to import System:
```liquid
{% execute type:'class' %}
    public class TestScript 
    {
        public string Execute() {
            return System.DateTime.Now.ToString();
        }
    }
{% endexecute %}
```
```
6/25/2019 4:50:39 PM 
```

----------

#### Workaround 1.5
If we're using a primitive type, we can use the lowercase primitive instead of the system type:
```liquid
{% execute type:'class' %}
    public class TestScript 
    {
        public string Execute() {
            return string.Concat("Hello", "World");
        }
    }
{% endexecute %}
```
```
HelloWorld
```

----------

#### Workaround 2
We can also add whitespace to bypass the filtering of `using System;`. The Lava documentation says "This can cause some issues for you and we recommend that you don't", but I haven't discovered any issues with it so far.
```liquid
{% execute type:'class' %}
    using System    ;
    public class TestScript 
    {
        public string Execute() {
            return DateTime.Now.ToString();
        }
    }
{% endexecute %}
```
```
6/25/2019 4:52:13 PM
```

----------

**Expected behavior:**

We can use system types like `DateTime`, `Guid`, etc without having to bypass the filtering of `import System;` or reference them directly as `System.<Type>`.

**Actual behavior:**

We can't use system types like `DateTime`, `Guid`, etc without having to bypass the filtering of `import System;` or reference them directly as `System.<Type>`.

### Versions

* **Rock Version:** 8.8 (1.8.8.3), PreAphla - 10.0 (1.10.0.1)
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
I updated this in v9. With classes you do need to provide all imports. I updated that information in the documentation as well as removing the note about not importing System. That is needed.
