### ISSUE TITLE
v9 Migration Helper UpdateBlockTypeByGuid

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#3767]
### Description
It appears that a string.Format was updated to a newer syntax which introduced a bug.  https://github.com/SparkDevNetwork/Rock/blob/release-1.9.0/Rock/Data/MigrationHelper.cs#L305

I believe WHERE [Path] = '**{1}**' AND [Guid] != '{guid}'; should be `WHERE [Path] = '{path}' AND [Guid] != '{guid}';`

### Versions
`develop` and `release-1.9.0` branches

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/sparkdevnetwork/rock/commit/c5aafdf5a518af01ba93408348a79168aa909d4b
