### ISSUE TITLE
Attribute Matrixes Become Linked When Copying a Group

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/Rock#3768]
### Description
When copying a group, any attribute that is the Attribute Type of Matrix becomes "linked" between the groups.

Rather than creating a duplicate of the original matrix and associating the new group with the new matrix, the copy feature copies the Guid reference of the original matrix to the new group. The result is that if the user modifies the items in the matrix attribute of either group they are also editing the matrix of the other group since both groups refer to the same matrix.

### Steps to Reproduce
1. Create a group attribute in [a Group Type with the attribute type of "Matrix" ](https://rock.rocksolidchurchdemo.com/page/117?groupTypeId=1037)
1. Create a group ([Group A ](https://rock.rocksolidchurchdemo.com/page/113?GroupId=1225&amp;ExpandedIds=)) with this newly created Group Type
1. Add Items to the Matrix of Group A
1. Copy Group A using the Group Detail Block
1. Add an item or edit an existing item in the Matrix of the newly created group ([Group B ](https://rock.rocksolidchurchdemo.com/page/113?GroupId=1226&amp;ExpandedIds=))
1. View Group A and notice that the edits made in Group B are now applied to the matrix in Group A

**Expected behavior:**

Copying a group creates a group with an attribute matrix that is unique to that group.

**Actual behavior:**

Copying a group creates a group with an attribute matrix that is shared between the original group and the copied group.

### Versions
https://rock.rocksolidchurchdemo.com

* **Rock Version:** Rock McKinley 8.8 (1.8.8.3)
* **Client Culture Setting:** en-US

https://admin.ccvsocal.com/

* **Rock Version:** Rock McKinley 8.7 (1.8.7.5)
* **Client Culture Setting:** en-US

ref: https://github.com/SparkDevNetwork/Rock/issues/3554

**Comment by cabal95** [comment]
This is a similar issue to https://github.com/SparkDevNetwork/Rock/issues/3554 which was decided to be essentially not fixable.

The issue you are seeing will also happen with other things that can be copied (pages and blocks for example, even workflows) and also happens with other field types, such as a binary file.

The core team can weigh in, but I'm assuming they would also close this one the same way as not fixable.

**Comment by bscottdavis** [comment]
Gotcha Daniel, totally makes sense.

If it is deemed to be unrealistic to make a duplicate of the referenced matrix (or binary file) and associate the new matrix with the copy of the group, it would be an improvement in my use case to have the newly created duplicate group have a blank matrix attribute. (Essentially do not even attempt to copy these types of attributes that are problematic.)

If the attribute were left blank in the newly created group I would then be able to add new matrix items to the new group, rather than having the attributes linked. 

The other benefit of creating the newly created group with blank attribute values for matrixes is that it removes the possibility of the user unknowingly changing the values in the "linked" group. In my use case it is better to have the no value in the group rather than having a value in the group that may confuse the user and have unintended consequences.

I realize that this may just be the best solution in my use case and may cause more issues for others, but wanted to throw my two cents in there. :)

Thanks for the amazing work that you and your team do!

**Comment by nairdo** [comment]
Quick update.  Our near term plan is to make changes to attributes in order to _flag_ ones that hold references to other entities (something like IHoldsEntityReferenceValues) and then [avoid copying those attribute values](https://github.com/SparkDevNetwork/Rock/commit/f7b5da113a14edb14a1bc6c81e2b49338b43a4e8#diff-ba8a45ea6876f569022279a727fc2b15R873) during a 'copy' operation.

Longer term -- and this is still sketchy -- we _might possibly_ allow the user to choose which of those values should be copied along into the new cloned/copied group.

**Comment by bscottdavis** [comment]
Sounds like a great solution.  Thanks again for the work that you and your team do!

**Comment by cabal95** [comment]
@matthewbronkema Do you know if this fix that you just applied also fixes #3802 (copying pages with Binary File fields or Matrix Fields), or for the moment does this only apply to copied Groups? (The previous fix on #3802 just displayed a warning that they might screw up their system if they copy pages).

**Comment by matthewbronkema** [comment]
@cabal95 this is currently only implemented in the group copy block, but the implementation was done in such a way that it should be easily reused in other areas or can be overridden by custom implementations.
