### ISSUE TITLE
SMS Only Communication Entry won't Add Person or Search

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#3769]
### Description
If you change the block settings on the Communication Entry block (such as on the New Communication -> Use Simple Editor page) to be only SMS, the Add Person picker no longer works and the Search in the header (by Name) no longer works either.

### Steps to Reproduce
1. Go to New Communications page.
1. Click on Use Simpler Editor.
1. Change the block settings to only have SMS enabled and use Full mode.
1. Save and reload the page.
1. The Add Person drop down no longer works and the search in the upper right no longer works.

**Expected behavior:**

I would expect them to operate the way they do for Email only or with both enabled.

**Actual behavior:**

Clicking on the Add Person drop down does nothing.  The Search in the upper right allows entry of data, but does not search and enter does nothing,  It looks like the class on the Add Person is "person-picker-none" instead of the normal class.

### Versions
* **Rock Version:** 8.8 (duplicated on rocksolidchurchdemo.com and prealpha)
* **Client Culture Setting:** Azure

**Comment by cabal95** [comment]
@bobrufenacht Would it be possible for you to fill in the rest of the bug report? Specifically, the exact steps (click for click) required to reproduce and the Rock version number are a bare minimum.

**Comment by bobrufenacht** [comment]
Sorry - laptop wend dead just as I was typing.
