### ISSUE TITLE
Check-in Search page not respecting Check-in Search Type only on our site

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3771]
### Prerequisites
* [  x  ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?  **NO**
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Changing the Check-in Search Type (Name, Phone Number, Name and Phone) in the Check-in Configuration page has no effect on the search type shown on the **/checkin/search** Page.  I only get the option (label) 'Name or Phone'.  This happens from both the client check-in application and from the web check-in page (http://mysite/checkin/search).

THIS DOES NOT HAPPEN IN THE DEMO SITE, BUT IS HAPPENING ON OUR SITE (both running same version: 8.8(1.8.8.3).  AM I MISSING A SETTING OR DOING SOMETHING WRONG OR HAS AN UPGRADE NOT BEEN APPLIED?

This is not a problem for me - but the behavior is inconsistent with the demo site and with the documentation.

### Steps to Reproduce

1. Go to Home > Check-in > Check-in Configuration > Edit > Search Settings > Search Type
2. Change the search type.
3. Go to yoursite/checkin > START.
4. You will see that the search option has changed and the page shows the correct heading, and if Phone is the search type then the keyboard is displayed.
5. Repeat steps 1-4, changing the search type, and refreshing the /check-in/search page - the change is immediate.

But not for me, I only ever see 'Name or Phone.'  Doesn't matter what Search Type I select, I only see the Name or Phone option on the check-in search page.  Have tried clearing cache, and restarting, but these have no effect.

**Expected behavior:**

My site should change the check-in search option like the demo site does.

**Actual behavior:**

I only ever see 'Name or Phone' regardless of check-in search type selected.

### Versions

Rock Version: Rock McKinley 8.8 (1.8.8.3)
Client Culture Setting: en-NZ

**Comment by lpeterson1** [comment]
I suspect this is because your device(s) are set to registration mode. In your check-in kiosk device(s) make sure that registration mode isn't turned on.
![Screen Shot 2019-06-29 at 5 04 03 AM](https://user-images.githubusercontent.com/37701239/60383228-8eb4de00-9a2b-11e9-89f0-53b1d0d8487d.png)

**Comment by ElimAdmin** [comment]
Thank you, @lpeterson1 !  Yes, that was it.  
Perhaps modify the help on the Search Setting, Search Type field to include "The search setting will be set to Name and Number if the check-in kiosk device used has a Registration Mode of Yes."
And I will recommend a documentation change to clarify this.
