### ISSUE TITLE
Exception thrown when trying to delete item from Content Channel

### ISSUE THREAD

**Issue by USCBigRed** [SparkDevNetwork/Rock#3774]
### Description
When trying to delete a content item Content List an exeception is thrown.  This is happening on my alpha site and on the pre-alpha rock site.

### Steps to Reproduce
1. Go to 'https://prealpha.rocksolidchurchdemo.com/page/343'
1. Click on 'External Website Ads'
1. Scroll down to 'Any of the content ads and click the red x'
1. See error

**Expected behavior:**

Content item should be deleted

**Actual behavior:**

Exception is thrown

### Versions
* **Rock Version:** [Rock McKinley 9.0 (1.9.0.21)]
* **Client Culture Setting:** [en-US] ![Screenshot!UNITO-UNDERSCORE!7](https://user-images.githubusercontent.com/5194936/60636051-e9ab5400-9de2-11e9-9a5d-e5be1242632a.png)

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in 9.0 branch. https://github.com/SparkDevNetwork/Rock/commit/85b5008c5ff45fd75a1dfa8b9705bdad331ef55a

**Comment by USCBigRed** [comment]
this is still not working in the v9 beta

**Comment by jonedmiston** [comment]
@USCBigRed we'll look into this asap.

**Comment by ethan-sparkdevnetwork** [comment]
This was a problem on three blocks: ContentChannelItemList, ContentChannelNavigation, and ContentComponent. In v9.0 only ContentChannelItemList was fix. The other two are fixed in 9.1.
