### ISSUE TITLE
v9 alpha update issue

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#3776]
### Description

Updating a fork of a church's production data to v9 alpha failed during the restart with message "Server Error in '/' Application"

### Steps to Reproduce

I tried updating the server several times, always with the same result. I used Windows Steps Recorder to capture these steps to document the SQL Server CPU (top graph) and the IIS Server CPU (bottom graph) and timings.

**Step 1: (‎7/‎4/‎2019 12:05:41 PM) User left click on "Chrome Legacy Window (pane)" in "Roc"**
![image](https://user-images.githubusercontent.com/6932047/60745880-1cfbf900-9f31-11e9-8009-d6181647276f.png)

**Step 2: (‎7/‎4/‎2019 12:07:23 PM) User left click on "Restart (button)" in "Roc"**
![image](https://user-images.githubusercontent.com/6932047/60745895-2edd9c00-9f31-11e9-989f-c29044d3b59d.png)

**Step 3: (‎7/‎4/‎2019 12:09:12 PM) User Comment: "Failed at this point"**
![image](https://user-images.githubusercontent.com/6932047/60745919-46b52000-9f31-11e9-95e2-efc36d86e65e.png)

The servers are dedicated VMs in Azure. The database is listed as 5,157.06 MB in SSMS.

Windows Updates recently installed and servers restarted.

I checked _MigrationHistory after two of the failures and it appears to have stopped at a different place each of those times. With the attempt documented in the screenshots, these were the last 10 migrations listed:

201905081957016_GroupScheduling
201905082317243_Rollup_0508
201905142021095_AddDescriptionToRegistrationTemplate1
201905150435321_Assessments
201905291549561_UpdateSubjectLength
201905291554185_Assessments2
201905291556006_UpdateMaxRegistrantsToNull
201905291845488_Assessments3
201905300056053_GroupSchedulingUpdates
201906032320193_AssessmentBadges

In an earlier attempt, these were the most recent 10:

201901241553484_GroupLocationDeleteFix
201901251419032_UpdateDiscRequestWorkflow
201901282220368_Rollup_0128
201901291632252_OptionalFees
201902051933512_Rollup_0205
201902061535567_RemovePersonicxLifestage
201902111543316_AddOldRawValueAndNewRawValueToHistory
201902192016143_Rollup_0219
201902201848155_UpdateComponent
201902272058547_PersonGivingLeaderIdUpdate

Since attempting to update, the server has been throwing triplets of errors several times a minute (this is from RockExceptions.csv):
![image](https://user-images.githubusercontent.com/6932047/60746786-d066ec80-9f35-11e9-8baa-2bcbe86405f1.png)

**Comment by JimMichael** [comment]
I reported a similar problem in chat, but I'll repeat here for posterity. In my case the upgrade goes "fine" and gets the the "Eureka" prompt, but then the UI won't restart and I see:
![image](https://user-images.githubusercontent.com/3903408/60747275-bf27db00-9f49-11e9-925d-eee29408fb67.png)

If I then look at RockExceptions.csv I see
![image](https://user-images.githubusercontent.com/3903408/60747305-ec748900-9f49-11e9-86b2-a0e6ff72ee15.png)

And the only 2019xxx record in __MigrationHistory is
![image](https://user-images.githubusercontent.com/3903408/60747321-fe562c00-9f49-11e9-985b-3533e244a242.png)

This is on a test instance running a fresh copy of 8.8prod and trying to upgrade to v9alpha.

**Comment by nairdo** [comment]
@mikejed I'm a little concerned with the fact that your first attempt seemed to die out in one spot -- and then made it further along, until it ran into this 'migration helper' bug Ethan fixed above.

So, even though we're going to close this one and call it fixed, I'd still like you to try this all again when the v9.0 alpha round #2 starts tonight/tomorrow.  If anything goes wrong then, please open a new issue with the details.
