### ISSUE TITLE
Children not Saving in Families

### ISSUE THREAD

**Issue by charlottedean** [SparkDevNetwork/Rock#3778]
When adding children to a family via registration mode for check-in with the relationship of "can check-in", it does not save the children in the original family that 'Add Person' was clicked from. 

1. Go to a registration mode for check-in.  
2. Search for a family.  
3. Select family, and then click edit.
4. Add person.  
5. Make the person have the relationship of 'Can Check-in'. Save.
6.  Search for them, and they will be in their own family, not the original family clicked 'Add Person' from. 

**Expected behavior:**
It should save the children into the original family.

**Actual behavior:**
It makes the child/children into their own family. 

A description of what actually happened.

### Versions

* **Rock Version:** 8.6
* **Client Culture Setting:** en-us

**Comment by JimMichael** [comment]
Bug or not, I'm curious why you're choosing a relationship at all for a child being added to the same family? No relationship to the adults is necessary for children _in_ that same family.

**Comment by charlottedean** [comment]
I only change it if the kids are not the children of the adults, aka, grandchildren.

**Comment by JimMichael** [comment]
Ah, got it. Here we wouldn't (intentionally) put kids into the same family as the adults unless they are truly the children of those adults. We always put them in their own fam with relationship back.

**Comment by nairdo** [comment]
@charlottedean Unless I'm misunderstanding something here, as Jim stated above, in that scenario the child would _not_ be put into the same family. Please let me know if I'm missing something.

**Comment by charlottedean** [comment]
I think I'm misunderstanding the use of that option then in check-in.  Let me do some further digging.
