### ISSUE TITLE
v9alpha Rock Theme Won't Compile

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3779]
### Description

After upgrading to v9alpha, I noticed my FontAwesome Pro icons were not rendering. After going to Admin | CMS Config | Themes and clicking the _Compile_ button on the Rock theme, I get the following error
![image](https://user-images.githubusercontent.com/3903408/60845594-7585fd00-a1a2-11e9-85f7-ce28708a2a6b.png)

**Expected behavior:**
Theme would compile

**Actual behavior:**

It throws a compile error.

### Versions

* **Rock Version:** 1.9.0.21 alpha1

**Comment by JimMichael** [comment]
I will add that even with the compile issue above, after uploading a new FA Pro Zip and _attempting_ the recompile, my FA Pro icons started rendering fine.

**Comment by nairdo** [comment]
Jim, although Garrett made a fix here https://github.com/SparkDevNetwork/Rock/commit/8616d847cb02aa0cc5e94056aefc4afe444166d7 to help with this problem, we are also concluding that (at least for v9 -- until we have more time to find a better approach) the Rock administrator is going to have to re-add their FontAwesome Pro package after the v9 update.

We just added this note to the [Release Notes](https://community.rockrms.com/releasenotes#v9.0) as:
> Updated to FontAwesome 5.9.0. IMPORTANT: If using FontAwesome Pro, you will need to re-upload your Font Awesome Pro Package after the update.
