### ISSUE TITLE
[EN] - Set New Communication-Email Subject set from Communication Name if blank

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3784]
# Enhancement Request

**Describe the Enhancement Request**
**Describe Preferred Solution**

Not sure if this was covered under the discussions here: https://github.com/SparkDevNetwork/Rock/issues/3591

When an email template does not have a subject set, and
when stepping through the New Communication workflow,
default the Email Subject from the Communication Name.

This saves re-entering the email subject (which in most cases for us is the same).

**Describe Alternatives**

Allow the Email template to include Lava for the Subject field that sets the Email Subject to the Communication Name, and specify the Lava to do this in the help text on the Email Subject field (which currently just reads {{Lava}} which is not very instructional as to what Lava can be used). 

**Providing Code**
I will provide code if feature request is approved:   No

**Comment by JimMichael** [comment]
I'm pretty sure enhancement requests are now expected via https://community.rockrms.com/ideas and not Github.

**Comment by jonedmiston** [comment]
Yes this should probably go under ideas. In general though we want to encourage people to not use the same text for the Communication name and subject, but the community can vote for it under ideas.
