### ISSUE TITLE
v9alpha Visibility Issue when Adding Blocks

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3785]
### Description

A clear and concise description of what the bug is, include screenshots if applicable.

I notice when adding new blocks in v9alpha, the keyword highlighting in the "chosen" box is very difficult to read. Here's an example
![image](https://user-images.githubusercontent.com/3903408/60916998-83488a80-a255-11e9-8137-c5f08503c511.png)

I tried multiple browsers and all produce the same illegible highlighting. This does not happen on v8.8 here with same browsers and same db. However, when I tried it on _prealpha_ it looks normal, too... but prealpha is on v10 now, so maybe this is fixed already?

**Expected behavior:**

Legible highlighting in "chosen" select boxes.

**Actual behavior:**

It's ugly. Not sure if this is only happening when adding a block, or anywhere the same type of control is used.

### Versions

* **Rock Version:** v9alpha1

**Comment by garrettjohnson** [comment]
Fixed in 9.0 via https://github.com/SparkDevNetwork/Rock/commit/edabbc377a57a6312d368034d2b10ee907d8464e
