### ISSUE TITLE
[EN] API requests that use the `$expand` and have `loadAttributes` `simple` or `expanded  do not load attributes on the expanded entities.

### ISSUE THREAD

**Issue by vinnyjth** [SparkDevNetwork/Rock#3787]
### Description
API requests that use the `$expand` and have `loadAttributes``simple` or `expanded  do not load attributes on the expanded entities. 

### Steps to Reproduce
1. Send a request that has `loadAttributes` and `expanded` Example: `/api/ContentChannelItemAssociations?$expand=ChildContentChannelItem&$filter=Id eq 1&loadAttributes=expanded`

**Expected behavior:**

I would like to have access to the attributes and attribute values on the `ChildContentChannelItem` and the `ContentChannelItemAssociations`. 

**Actual behavior:**

I only see the attributes and attributeValues for the `ContentChannelItemAssociations`

This might actually be a "new feature" instead of a bug. Having this functionality will be huge for the ApollosProject and allow us to consolidate a variety of N+1 queries or queries that have a likelihood of hitting the OData node limits. Right now we tend to query for the associations, grab the IDs of the children, and then query for all the children with something like `(Id eq 1) or (Id eq 2)` or by doing multiple queries. If we could access the attributes on expanded entities, we could eliminate those queries.

### Versions
* **Rock Version:** 8.7
* **Client Culture Setting:** en-US [RockDiagnostics-RD00155D96FD24.txt ](https://github.com/SparkDevNetwork/Rock/files/3377696/RockDiagnostics-RD00155D96FD24.txt)

**Comment by nairdo** [comment]
Hi Vincent @vinnyjth -- we've looked at this a bit in the past and are a little uneasy about expanding the attributes/values for the related/child properties due to probable performance implications (as there's granular security checking, etc. that's happening behind the scenes).  As a result, the caller needs to make an additional/separate REST call to get the attribute values on a child item.

We've previously asked the Apollos team for their specific use-cases so we could help with the creation of custom REST endpoints that could provide efficient, high-speed data retrieval.  We're still open to this, so let us know if they want to go down that path.

**Comment by vinnyjth** [comment]
Thanks @nairdo! 

> We've previously asked the Apollos team for their specific use-cases so we could help with the creation of custom REST endpoints that could provide efficient, high-speed data retrieval. We're still open to this, so let us know if they want to go down that path.

I think the solution to our most critical needs at this point would be one of two things.
- A way to make the query we described above, either through something like `customAttributes=AllEntites` or similar. 
- A way to fetch a list of entities, by their IDs and EntityTypes. We do this most often with `ContentItems`, where we fetch a list of 30+ `ContentItems` by their ids. This is currently impossible to do in a single query without hitting OData node limits. 

Should I make a new github issue for one or both of these issues, or should we further this conversation in an Apollos specific context? 

Thanks much! Solving this will be super helpful for the Apollos Project.

**Comment by jonedmiston** [comment]
@vinnyjth Would adding an endpoints to the `ContentChannelItem` controller that returns `ContentChannelItems` whose:

- Parents of a provided `ContentChannelItemId`
- Are children of a provided `ContentChannelItemId`

**Comment by vinnyjth** [comment]
> Would adding an endpoints to the ContentChannelItem controller that returns ContentChannelItems whose:
> - Parents of a provided ContentChannelItemId (_I think we already have a good query for this_)
> - *Are children of a provided ContentChannelItemId*

Absolutely! This would definitely solve one of our most problematic endpoints. 

We dp have a few other places that won't be solved by these new endpoints. For example, we query for `Following` entities and then query for the `ContentItems` attached to the `Followings` by Id. So we may need a more general solution, eventually.

**Comment by jonedmiston** [comment]
@vinnyjth can you write the user story for that following need. I think I understand, but I'm afraid I might be assuming I understand the use case and not fully knowing the user need.

**Comment by vinnyjth** [comment]
End user story:
- As a user, I should be able to "Like" a piece of content and see a feed of all content I have liked

Developer user story: 
- As a developer, I should be able to create a `Followings` associated with a `ContentChannelItem` and a `Person`, and the fetch all `ContentChannelItems` for a specific `Person`, using `Followings` as a sort of join table.

**Comment by jonedmiston** [comment]
@vinnyjth thanks for that. I would propose a few new endpoints.

1. A simple Follow endpoint that creates a following record passing: PersonId, EntityTypeId, EntityId (we'd also add an additional override that would take a PersonAliasId)
2. A simple UnFollow endpoint that unfollows a record taking the same options above
3. An endpoint that returns FollowedContent. This would take a PersonId/PersonAliasId, ContentChannelId and return a IQueryable (for OData) of Content Channel Items that are being followed.

Would that meet the need described above?

**Comment by cabal95** [comment]
@jonedmiston I think we already have endpoints written for items 1 and 2. I also have a version of them written that only take EntityTypeId and EntityId and create/delete for the currently authenticated user.

**Comment by vinnyjth** [comment]
@jonedmiston @cabal95 is right, I do believe we already have good endpoints for 1 and 2 that we are currently using in production. Number three is the major concern, because right now we hit OData Node limits if someone likes more than 20 content items. 

The endpoint you are suggesting sounds great! Would there be a way we could generalize it to `FollowedEntities` so it wouldn't necessarily be "ContentItems" that would be returned? I'm assuming you would have to pass an `EntityTypeId` to the endpoint.

**Comment by jonedmiston** [comment]
@vinnyjth we could use `EntityTypeId` but it might be better to put this action in the base `ApiController` that every entity inherits from using generics. That would make for more natural OData filters. I'm assuming you'd definitely want to filter by `ContentChannelId` which is why a specific endpoint for might also make sense as it's easier for many API developers to know what do to.

**Comment by vinnyjth** [comment]
> we could use EntityTypeId but it might be better to put this action in the base ApiController that every entity inherits from using generics

This sounds even better from an API usage standpoint than the `EntityTypeId`!
