### ISSUE TITLE
PowerBI Report Viewer Block Full Screen Not Working

### ISSUE THREAD

**Issue by JesseM-PC** [SparkDevNetwork/Rock#3792]
### Prerequisites
* Put an X between the brackets on this line if you have done all of the following:
  * [ ] Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * [X] Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * [X] Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When clicking the full screen button on the PowerBI Report Viewer block, you are given a very thin line of what used to be your report instead of seeing the report in full screen.

### Steps to Reproduce
1. Create a PowerBI report and add the Report Viewer block to a page.
1. View the report and click the full screen button in the upper left corner.
1. Report seems to disappear but is actually just crunched up in a really tiny line.
1. I have tested this on multiple browsers with the same result.

**Expected behavior:**

When the full screen button is clicked the report should be in a full screen.

**Actual behavior:**

Thin line of report is shown at the top of where the report was visible previously.

**Proposed Fix:**

I was able to fix the problem by changing line 79 on [PowerBiReportViewer.ascx ](https://github.com/SparkDevNetwork/Rock/blob/67780b6b24f3aa22848bab6230ebc83ab7baf9d1/RockWeb/Blocks/Reporting/PowerBiReportViewer.ascx#L79) from:
`reportWrapper.css("position", "absolute");` to `reportWrapper.css("position", "fixed");`

### Versions
* **Rock Version:** Rock McKinley 8.7 (1.8.7.6)
* **Client Culture Setting:** en-US

**Comment by debbiethurston** [comment]
Fellowship Greenville does have the same issue.  We are on v8.8.
