### ISSUE TITLE
v9alpha Chart Shortcode Does Not Render

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3794]
### Description

I cannot get the _Chart_ Lava Shortcode demo code to render on my v9alpha2 instance. 

### Steps to Reproduce

1. Put this code in a HTML block
```
{[ chart type:'bar' ]}
    [[ dataitem label:'Small Groups' value:'45' ]] [[ enddataitem ]]
    [[ dataitem label:'Serving Groups' value:'38' ]] [[ enddataitem ]]
    [[ dataitem label:'General Groups' value:'34' ]] [[ enddataitem ]]
    [[ dataitem label:'Fundraising Groups' value:'12' ]] [[ enddataitem ]]
{[ endchart ]}
```

2. Refresh the page, observe no chart renders.

**Expected behavior:**

Chart would render.

**Actual behavior:**

On my system, the space for the chart is "taken up" on screen, but no items appear within it. Verified same Shortcode still works on 8.8 here, and my v9alpha instance is a copy of that. I also tried it on prealpha and it DID work there, so this may be something specific to my system, but I have no idea what, if so.

### Versions

* **Rock Version:** v9alpha2

**Comment by cabal95** [comment]
![image](https://user-images.githubusercontent.com/1119863/61160376-17179200-a4b4-11e9-989c-d7cc067a3677.png)

Jim and I took a look at this in chat and it looks like `linear` is supposed to be in quotes. This was the error message in the JavaScript console. Why it works in 8.x and pre-alpha but not 9.x I'm not sure.

**Comment by JimMichael** [comment]
Maybe this line in the release notes is a clue? _Updated Chart.js to 2.7.2._
