### ISSUE TITLE
v9 Migration 201906051958565_Rollup_0605 - Timeout Expired exception

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#3796]
### Description
When installing the v9 migrations in our test environment (a clone of our production environment) we are seeing a "Timeout Expired" exception occur in the `201906051958565_Rollup_0605` migration.  It will fail the first time and then will work if we run migrations a second time.  I am doing this migration through Package Manager in VS not through the Rock update process.

### Steps to Reproduce
1. Perform Update-Database in the Package Manager Console of Visual Studio.
1. Migrations will begin to process
1. Package Manager will eventually attempt to run the `201906051958565_Rollup_0605.` migration and will throw a Timeout Exception.
1. Restart the process and then migrations will complete

**Expected behavior:**
Migrations will successfully complete on first run.

**Actual behavior:**

Migrations do not complete successfully.

### Versions
* **Rock Version:** 9.0
* **Client Culture Setting:** en-us

**Comment by chrisfunk** [comment]
I have reproduced this behavior on several occurrences

**Comment by nairdo** [comment]
@chrisfunk Can you see the method name where the exception is occurring?  Since they're all named it should help us pin point the offender: https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Migrations/Migrations/Version%209.0/Version%201.9.0/201906051958565_Rollup_0605.cs#L30

**Comment by chrisfunk** [comment]
@nairdo Will do, I have to run through the migrations again to find it.

**Comment by chrisfunk** [comment]
@nairdo  i think it was in the `UpdateAttributeValueValueAsNumericUp` method on Ln262.  That was the last query that showed up in -Verbose mode before the timeout.

**Comment by nairdo** [comment]
Fixed (by Mike) by changing that section of the migration to a 'run once' job via this commit: https://github.com/sparkdevnetwork/rock/commit/47277e5a8c052ef271c4eec83f090a1818560378

**Comment by nairdo** [comment]
@chrisfunk And thanks for testing v9 against a copy of a system with real data! (and for finding that issue.)
