### ISSUE TITLE
First Merge Field Can't Be Saved to Label

### ISSUE THREAD

**Issue by SteveSwaringen** [SparkDevNetwork/Rock#3799]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
When selecting the first Label Merge Field (order = 0) for a label merge code, the corresponding defined value ID does not save to the attributeValue record in the database. When printing the label, the field doesn't merge and the original merge code prints.

### Steps to Reproduce
1. Go to Check-in Labels and select a label with merge fields defined. Reload Merge Fields if necessary, and for any defined Merge Code, pick the first merge field from the top of the drop-down list.
1. Save the label. Print the label. 

**Expected behavior:**

The content of the selected Merge Field should be incorporated into the printed label.

**Actual behavior:**

No content is merged. Instead, the original Merge Code prints.

This is probably (theory) caused by failing to insert a blank option at the top of the MergeTemplateFieldType picker. The base class for the picker assumes the first element in the list is an "I don't want to select anything" option, so when this first item is picked, the code that gets the selected value thinks the user is asking for nothing to be selected.

I haven't traced through the code to confirm this theory, but I've queried the database and found that the AttributeValue is "CODE^", (where it should be something like "CODE^3567"). By moving a Merge Field that we don't use to the top of the list, I was able to get the attribute to save correctly and work around the problem.

### Versions
* **Rock Version:** 8.8 (1.8.8.3)
* **Client Culture Setting:** en-US

**Comment by Tschrock** [comment]
Hey Steve,
I've checked on both my own site and the rock demo site and I haven't been able to reproduce this issue using the steps you've provided (Open Label -> Click Reload Merge Fields -> Change a Merge code to the topmost option -> Save). I tried it a couple different ways, but changing a merge code to use the topmost option always saved the value to the database properly. 

That said, I did find one specific scenario where I was able to get an empty merge field id saved in the database: Open Label -> Delete a merge code -> Save -> Open Label -> Click Reload Merge Fields (Don't click save or change anything else after that). In that case, the deleted merge code is put back and shows as if it has the topmost option already selected, but it has a blank id when you check the database. Changing any of the merge codes after that fixes the values again.

Can you clarify if this is the issue you're seeing?

**Comment by SteveSwaringen** [comment]
Thanks for following up.

That isn’t what I see. Unfortunately, I can’t print labels from the RockSolidChurchDemo site, nor can I query that database directly, so I can’t say whether this happens in a stock build or not. With that said, I don’t believe there’s anything in our customizations that would affect this particular behavior.

We’re good with our work-around, so feel free to close the ticket as unable to reproduce. The only reason I reported the bug was that it took me several hours to track down and another user without access to a Visual Studio debugger might never figure out why their field merges were failing. If the problem is unique to us, consider it solved.

**Comment by nairdo** [comment]
@SteveSwaringen I know this is a bit old but a few of us have tried to reproduce this recently but were unable.   I'm going to close this out, but if you find a way for us to reproduce this issue, please feel free to re-open with more details.
