### ISSUE TITLE
Alpha v9 Assessment Charts not diplaying

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3800]
### Description
Charts for the assessments will not display. It could be related to #3794 and be fixed with the fix for that issue but just in case it isn't I wanted to post an issue on it. 

When I look at the page's source code I see the chart's coding and Chrome's Inspector shows and "Uncaught ReferenceError: linear is not defined" message--referring to the borderDash item in the chart's datasets.

I noticed this for the Emotional Intelligence, Conflict, and Motivators assessments. DISC's chart was visible, however, the DISC number results (v9) were much more different than the production numbers so I don't know if that is a different issue or the assessment was revised and the results also revised (v8: 21, 13, 33, 33; v9: 27, 1, 96, 96)

### Steps to Reproduce
1. Take Assessment
1. On Results page, there is a blank area where the chart should be.

**Expected behavior:**

Charts visible

**Actual behavior:**

Not visible

### Versions
* **Rock Version:** Alpha v9.0.22
* **Client Culture Setting:** en-US

![screencapture-mydev-crossroadschristian-org-ConflictProfile-2019-07-16-14!UNITO-UNDERSCORE!01!UNITO-UNDERSCORE!51](https://user-images.githubusercontent.com/5738650/61327851-7ee51a00-a7df-11e9-9d31-04ee9a7ac6b2.png)
![Screen Shot 2019-07-16 at 2 03 58 PM](https://user-images.githubusercontent.com/5738650/61327926-a0de9c80-a7df-11e9-915e-c0c50923bc2b.png)
![](https://user-images.githubusercontent.com/5738650/61327927-a0de9c80-a7df-11e9-9801-c33a02565236.png)

**Comment by nairdo** [comment]
We also found and fixed that shortcode issue.  It is being included in the v9 beta.
