### ISSUE TITLE
Preview image disappears from copied communication templates

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3802]
### Description
After copying a communication template and changing the preview image for the copy, the preview image for the original template disappears after a day or two.

![firefox!UNITO-UNDERSCORE!2019-07-17!UNITO-UNDERSCORE!11-06-44](https://user-images.githubusercontent.com/2406499/61386895-13ed1f00-a883-11e9-8fb2-9b986f8bda9f.png)

I've checked the database, and it looks like the original template's preview image is being marked "IsTemporary" when the preview image on it's copy is changed. Then whenever the Rock Cleanup job runs, that original image is deleted.

Before changing the copy:
![firefox!UNITO-UNDERSCORE!2019-07-17!UNITO-UNDERSCORE!11-08-40](https://user-images.githubusercontent.com/2406499/61387024-4eef5280-a883-11e9-96a9-2686079b5d9a.png)

After changing the copy:
![firefox!UNITO-UNDERSCORE!2019-07-17!UNITO-UNDERSCORE!11-09-02](https://user-images.githubusercontent.com/2406499/61387028-50207f80-a883-11e9-8ddc-ad93bd6b0d79.png)

### Steps to Reproduce
1. Create a communication template and upload a preview image for it.
1. Copy the communication template.
1. Change the preview image in the copy.
1. Wait a day or two.

**Expected behavior:**

The preview image for the original template stays.

**Actual behavior:**

The preview image for the original template disappears.

### Versions
* **Rock Version:** 8.8 (1.8.8.3), prealpha 10.0 (1.10.0.2)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Related to #3768 and #3554

**Comment by cabal95** [comment]
Just for reference @Tschrock, what is happening is that the binary file in the database isn't being duplicated. So the new template and the old template both use the same BinaryFileId. Thus, when you replace the image on one the old image is marked as IsTemporary so it can be cleaned up. Then, as you noted, it will vanish (usually that night) when the Rock cleanup job runs.
