### ISSUE TITLE
Alpha v9 Exceptions Thrown for StatusMessageAsHtml

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3803]
### Description
I was looking through the exception list and noticed 19k, in the last 7 days, thrown for "Member 'OriginalValue' cannot be called for property 'StatusMessageAsHtml' on entity of type 'ServiceJobHistory' because the property is not part of the Entity Data Model."

I'm not too certain what the issue is or what History Job is triggering it but figured I should submit it. I'll play with turning off some of the jobs and see if I can track down which one(s) it may be.

Stack Trace:

```
     at System.Data.Entity.Internal.InternalPropertyEntry.ValidateNotDetachedAndInModel(String method)
     at System.Data.Entity.Internal.InternalPropertyEntry.get_OriginalValue()
     at Rock.Data.DbContext.GetAuditDetails(DbContext dbContext, ContextItem item, Nullable`1 personAliasId)
     at Rock.Data.DbContext.RockPreSave(DbContext dbContext, PersonAlias personAlias, Boolean enableAuditing)
```
![](https://user-images.githubusercontent.com/5738650/61397403-72b89580-a88f-11e9-8562-13105eb864f6.png)
![](https://user-images.githubusercontent.com/5738650/61397425-7f3cee00-a88f-11e9-966c-59de03e1fff3.png)

### Versions
* **Rock Version:** Alpha v9.0.22
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
Just chiming in that I don't see such exceptions on 1.9.0.22, and my job history (new functionality in v9) seems to be working as expected. That 19k seems like it would have to be the Job Pulse or something... but as far as I can tell that job is excluded from job history.

**Comment by BEGamache** [comment]
Interesting. Okay I'll hunt around and see what I can find. Thanks @JimMichael

**Comment by nairdo** [comment]
@BEGamache  This looks like another issue that is (partially) related to having Auditing enabled (which will bring your system to a crawl).  I'd recommend turning auditing on only briefly when absolutely necessary for some event you're trying to capture.

**Comment by BEGamache** [comment]
Good to know that. I've turned it off. I think I did turn it on for a reason but forgot to turn it off, so it has been running for a while.

**Comment by nairdo** [comment]
This seems to be something not too critical so we opted to fix in in the develop (v10) branch.  Thanks @BEGamache !!

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/sparkdevnetwork/rock/commit/3997a10b6a33cab832b077319c460e1334049b75

**Comment by nairdo** [comment]
Fixed in v10 via https://github.com/sparkdevnetwork/rock/commit/3997a10b6a33cab832b077319c460e1334049b75
