### ISSUE TITLE
Exceptions Thrown for "Input string was not in a correct format" (especially when Auditing is enabled)

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3804]
### Description
When checking the Exception List I noticed 19k exceptions for "Input string was not in a correct format."

Not certain what is causing or throwing this error. I after the update to v9 alpha I removed all email addresses from the system except mine so I don't know if that would contribute to this issue, I don't think it would though.

![](https://user-images.githubusercontent.com/5738650/61397878-77ca1480-a890-11e9-9506-e29f454f0225.png)
![](https://user-images.githubusercontent.com/5738650/61397882-7b5d9b80-a890-11e9-91b9-778c26d6a8d9.png)

### Versions
* **Rock Version:** Alpha v9.0.22
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@BEGamache Can you confirm that the system has or does not have "Enable Auditing" set to "No" under Global Attributes?

**Comment by BEGamache** [comment]
Enable Auditing is set to Yes

**Comment by nairdo** [comment]
Thanks again @BEGamache.  As I mentioned in the other issue, I'll mention it here for the sake of others... Enabling Auditing will cause a _**substantial**_ performance degradation so you should probably only enable it for a brief period of time when you're trying to track down some condition/event.

We've also decided that this particular situation isn't critical to try to tackle this late in the v9.0 release cycle, so we're targetting v9.x or v10.

**Comment by nairdo** [comment]
And addressed in v10 via https://github.com/SparkDevNetwork/Rock/commit/3997a10b
