### ISSUE TITLE
Registration Instructions does not show when "Allow Multiple Registrants = false"

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3805]
### Description
If the registration is set to not allow multiple registrants, then the screen that shows the registration instructions is skipped.

Originally culled from https://community.rockrms.com/ideas/1278

Jeff says:
> I'm not sure it's necessarily a "bug" since the help text on the Registration Instructions says that it displays on the page where they choose how many they're registering.

### Steps to Reproduce
n/a

**Expected behavior:**

Registration instructions should be shown on all registration entry forms.

**Actual behavior:**

They only show if allow multiple is true.

### Versions
* **Rock Version:** Rock McKinley 8.8 (1.8.8.3)
* **Client Culture Setting:** ??

**Comment by JRichmond27** [comment]
### Steps to Reproduce
1. Create an Event Registration Template with the Allow Multiple Registrants left unchecked
2. Add content to the Registration Instructions field on the template
3. Create an instance of the new template
4. Go to the registration instance on the public website and notice that the instructions are not shown

### Versions
* **Client Culture Setting:** en-US


The current help tooltip on the Registration Instructions field currently says:
> These instructions will appear at the beginning of the registration process when selecting how many registrants for the registration.

...so this may be working as intended.

**Comment by cabal95** [comment]
Was able to reproduce this on the demo site, so marking it as confirmed. But also marking it for the core team to review. As @JRichmond27 says, it _may_ be working as intended, although that may have just been the wording chosen as that happened to be where the text showed up during development/testing not realizing it wouldn't show up if the registration only allows single registrants.  Core team can make the call on that.

Thanks Jeff for getting the reproduction steps in!

**Comment by ethan-sparkdevnetwork** [comment]
The instructions will now display on the initial screen regardless of the "Allow Multiple Registrants" setting. If allow multiple is selected then the instructions appear next to the number selector control as usual, if not then the instructions display by themselves. If there are no instructions and allow multiple is not enabled the it registration skips to the Registrant screen as normal. Also removed the allow multiple caveat from the Instructions help text.

All other functionality has not changed.

**Comment by cabal95** [comment]
Thanks @ethan-sparkdevnetwork, I'm assuming by "display by themselves" means there is a "Continue" or "Start" or whatever button as well so the user can move to the next (initial) screen?
