### ISSUE TITLE
Alpha v9 Exceptions Thrown for Missing Less File in LandingPage theme

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3806]
### Description
When looking through the Exception List one of the errors  was "You are importing a file ending in .less that cannot be found [_css-overrides.less]." 

I compared the alpha theme folders to the production theme folders (8.7) and didn't see anything missing. The themes that don't have a _css-overrides.less file are Landing Page, Dashboard, and Kiosk. 

When doing a search for _css-overrides.less in the Github repository it looks like LandingPage makes an import call in its theme.less file which could be causing the exceptions since it doesn't have that file in its folder. 
[https://github.com/SparkDevNetwork/Rock/blob/71499896de3c0abe10c0d422fff23a99e60f0329/RockWeb/Themes/LandingPage/Styles/theme.less#L401 ](url)

![](https://user-images.githubusercontent.com/5738650/61406276-20807000-a8a1-11e9-82b8-77ede63d37e4.png)
![](https://user-images.githubusercontent.com/5738650/61406307-342bd680-a8a1-11e9-87dc-886d71e5b385.png)

### Versions
* **Rock Version:** Alpha v9.0.22
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
This has been fixed for the DashboardStark/Styles/_css-overrides.less and the KioskStark/Styles/_css-overrides.less issue(#3789) which will be in the v9 beta -- but I'll check to verify it is fixed for the LandingPage theme too.

**Comment by nairdo** [comment]
Although not mentioned in #3789, we did catch and fix the _LandingPage_ theme's `_css-overrides.less` issue too via https://github.com/SparkDevNetwork/Rock-UpdatePackageBuilder/commit/bf1339326a86716723f403f35632af3a98e67a39
