### ISSUE TITLE
[EN] Update Payment Method for Recurring Donations

### ISSUE THREAD

**Issue by taylorbrooks** [SparkDevNetwork/Rock#3808]
### Description
If you have a recurring donation that uses a credit card and you want to add a new payment method, you can only add a new card.

If you have a recurring donation that uses a bank account and want to add a new payment method, you can only add a new bank account.

In short, if you have a bank account, you can’t add a new card -- and vice versa.

### Steps to Reproduce
1. Setup a recurring donation on a Rock form (test gateway is fine)
1. Use a test credit card
1. Complete the transaction
1. Go to "Manage Giving Profiles"
1. Edit the recurring gift
1. Notice that you cannot add a bank account

![](https://user-images.githubusercontent.com/117657/61480152-2e3e0000-a94a-11e9-9443-d59f99338645.png)

![sched](https://user-images.githubusercontent.com/117657/61480364-b2908300-a94a-11e9-85c6-a7d96e2bd69a.gif)

**Expected behavior:**
As a donor, when I want to update my recurring donation with a new payment method, I expect to be able to add either a new card a new bank account or select any of my previously saved payment methods.

**Actual behavior:**
As a donor, I can update my recurring donation but only with a payment method that is the same type as the original payment method (bank account => bank account or card => card)

### Versions
* **Rock Version:** 8.8
* **Client Culture Setting:** en-us

**Comment by taylorbrooks** [comment]
We are working on a fix for this in our own instances of Rock. Would a PR that fixes this behavior be welcomed back into core?

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
