### ISSUE TITLE
Dynamic Heat Map Breaks When Campus Name Has Apostrophe

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3811]
### Description

I'm no longer able to get the Dynamic Heat Map block to work. It either renders a map with no points, or a completely blank block.

### Steps to Reproduce

1. Put Dynamic Heat Map block on a page.
2. Pick a dataview
3. Observe it shows no results (points on map)
4. Refresh page, observe blank block (no map shows)
5. Browser console shows `Uncaught SyntaxError: Unexpected identifier`

The exact steps above are not 100% reproducible (it's "flaky")... sometimes it renders a map, sometimes it shows a blank block, but in no case does it actually show points on a map from the dataview like it should.

**Expected behavior:**

Heat Map block would render a usable map

**Actual behavior:**

It's broken for me. Tried on 8.8 and v9. I see this issue about heat map but it was closed with no details, and I cannot find the issue it's supposedly a duplicate-of. https://github.com/SparkDevNetwork/Rock/issues/3611

### Versions

* **Rock Version:** [Enter Rock version here]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by JimMichael** [comment]
Alas...I can't dupe it on demo or prealpha, so unless someone else can dupe it must be something with our environment.

**Comment by JimMichael** [comment]
Ok, looks like this is an issue when you have a campus name with an apostrophe... in our case, we have a campus named "Grant's Trail" and this causes the JS exception above. I temporarily renamed the campus to Grants Trail and the block then rendered fine.

**Comment by Tschrock** [comment]
I can replicate this when the "Show Campus Locations On Map" option is checked.

Relevant generated code:
![firefox_2019-07-22_13-37-47](https://user-images.githubusercontent.com/2406499/61652655-72047280-ac86-11e9-864d-f6dc598316ad.png)
