### ISSUE TITLE
Text-to-workflow showing update available 

### ISSUE THREAD

**Issue by kcirgjd** [SparkDevNetwork/Rock#3813]
### Prerequisites
* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you had installed Text-to-workflow as a pluggin it still shows in purchases. With v9 you can now "updated" this plugin. I don't think that's intended.  On the PreAlpha site it will allow you to install tis plugin 
### Steps to Reproduce

1. Go to 'rockshop'
2. Click on 'purchases'
3. Scroll down to 'Text-to-Workflow'

**Expected behavior:**

The install/update button unavalible. 

**Actual behavior:**

On preAlpha=Install, on my beta=update
### Versions

* **Rock Version:** V9

**Comment by jonedmiston** [comment]
@kcirgjd  I think I fixed this. Can you confirm on your install and close if it worked?
