### ISSUE TITLE
Full Screen group scheduler-modals do not load until exit

### ISSUE THREAD

**Issue by kcirgjd** [SparkDevNetwork/Rock#3814]
### Description
If you enter full screen from the group scheduler and then click "send now" or "Auto Schedule" you do not see the modals that should load until you exit full screen mode. This could allow you to have many popping up on exit. 

### Steps to Reproduce
1. Go to 'group scheduler'
1. Click on 'full screen'
1. Click on 'Send Now'
1. exit full screen
1. see error

**Expected behavior:**
See modal in full screen or exit full screen immediately to modal. 

**Actual behavior:**

The modal's do not load until exit. 

### Versions
* **Rock Version:** v9
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by garrettjohnson** [comment]
Due to technical limitations, we're removing the fullscreen capability in v9.1. It should return in a later version.
