### ISSUE TITLE
lava error in badge for assessments- tooltip

### ISSUE THREAD

**Issue by kcirgjd** [SparkDevNetwork/Rock#3815]
### Description
If someone took the spiritual gifts assessment and then hovers over the results on their profile the tool-tip that pops up have a lava error rather then results. 

### Steps to Reproduce
1. Take Spiritual Gifts assessment
1. Go to person profile
1. hover over badge for assessments
1. See error

**Expected behavior:**

show results

**Actual behavior:**

Lava Error

### Versions
* **Rock Version:** [V9]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by nairdo** [comment]
@kcirgjd I've not been able to reproduce this yet. Can you attach a screenshot and perhaps the results of this query (assuming no one else has taken that assessment yet):

```Sql
SELECT PersonAliasId, Status, AssessmentResultData FROM [Assessment] WHERE AssessmentTypeId = 2
```

**Comment by Tschrock** [comment]
I just completed the Spiritual Gifts survey for Ted Decker on the pre-alpha server and this is the result:

![firefox_2019-07-23_10-22-42](https://user-images.githubusercontent.com/2406499/61720002-fd880d00-ad33-11e9-86cb-1708e35a9430.png)

I focused on getting him "Evangelism" for the dominant gift but I don't think the gift itself is the cause.

----------
**Assessment Result**

![firefox_2019-07-23_10-34-02](https://user-images.githubusercontent.com/2406499/61720814-7b98e380-ad35-11e9-9ad3-74c0d22aff7a.png)

----------

**Assessment Data**
```sql
SELECT PersonAliasId, Status, AssessmentResultData FROM [Assessment] WHERE AssessmentTypeId = 2
```
Person Alias Id | Status | Assessment Result Data
-- | -- | --
16 | 1 | {"Result":{"C111":0,"C39":0,"C65":0,"C85":0,"C105":0,"C114":4,"C18":0,"C30":4,"C112":4,"C76":0,"C81":0,"C87":0,"C72":0,"C77":4,"C8":4,"C29":4,"C66":4,"C45":0,"C80":4,"C57":0,"C68":4,"C101":0,"C89":4,"C103":0,"C31":0,"C35":0,"C69":0,"C3":0,"C78":4,"C119":0,"C6":0,"C56":0,"C90":0,"C4":0,"C25":0,"C60":0,"C58":0,"C67":0,"C94":0,"C42":0,"C1":4,"C96":0,"C13":0,"C70":0,"C20":0,"C88":0,"C75":4,"C14":4,"C19":4,"C21":0,"C41":0,"C12":4,"C64":4,"C7":4,"C106":4,"C99":0,"C51":0,"C5":0,"C26":0,"C50":0,"C83":0,"C116":0,"C59":4,"C63":4,"C109":4,"C117":4,"C92":0,"C113":0,"C118":4,"C61":0,"C86":0,"C22":0,"C71":0,"C47":0,"C62":0,"C102":0,"C17":0,"C37":4,"C9":0,"C15":0,"C74":0,"C100":4,"C16":0,"C108":0,"C33":0},"TimeToTake":233.9843396}

----------

**Badge Lava**
```sql
SELECT Title, BadgeSummaryLava FROM [AssessmentType] WHERE Id = 2
```
Title | Badge Summary Lava
-- | --
Spiritual Gifts | {% assign gifts = Person \| Attribute:'core_DominantGifts','Object' %}                 {{ gifts \| Map:'Value' \| Join:', ' \| ReplaceLast:',',' and' }}

----------

**Attribute Value**
```sql
SELECT EntityId AS PersonId, Value FROM [AttributeValue] WHERE AttributeId = 3874 -- core_DominantGifts
```
Person Id | Value
-- | --
4 | 0f8d41aa-7236-40bf-aa37-980bccf4a881

----------

**Defined Value**
```sql
SELECT Value, Description, Guid FROM [DefinedValue] WHERE Guid = '0f8d41aa-7236-40bf-aa37-980bccf4a881'
```
Value | Description | Guid
-- | -- | --
Evangelism | The gift  of evangelism assists you in sharing the Good News of Christ in a  relevant manner with people far from Christ so they respond positively  to become disciples of Jesus Christ. | 0f8d41aa-7236-40bf-aa37-980bccf4a881
