### ISSUE TITLE
Batch Name Too Long - Event Reg Duplicate Payments

### ISSUE THREAD

**Issue by taylorbrooks** [SparkDevNetwork/Rock#3816]
### Description
When someone goes to register for an event and make a payment, Rock creates a new batch. It uses the registration name as part of the batch name. If the batch name is longer than 50 characters, the registration is NOT saved. This is problematic for a couple reasons, but mainly because the batch gets created _after_ the card is charged. 

Sometimes people think the registration didn't go through, so they click the button and their card is charged multiple times

### Steps to Reproduce
1. Create a registration with longer than 50 characters
1. Try to register for that paid event
1. See that an exception was created under the Exceptions List in the admin area.

**Expected behavior:**
When someone registers for a paid event, their card is charged successfully and the registration and transaction are saved in Rock.

**Actual behavior:**
When someone registers for an event and the registration name is a long string, transactions will successfully process, but the registration and transaction will not be saved in Rock.

### Versions
* **Rock Version:** [8.7]
* **Client Culture Setting:** [en-US]

**Comment by jennifertroeger** [comment]
I can attest to the misconception that the transactions didn't process, as this just happened to us and we are working with refunding 10 extra transactions between 2 people.

**Comment by taylorbrooks** [comment]
Yay, thanks @MikeDPeterson
