### ISSUE TITLE
Stuck Grid Tooltips

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/Rock#3817]
### Description
Occasionally the ID tooltip on a grid row will fail to hide when the mouse cursor moves away from the row. The tooltip remains on the screen above all other page elements, and doesn't go away until you completely leave the page and come back.

**Screenshots:**
http://i.jrichmonds.com/images/190722-1749-B9P8SZ.jpg
http://i.jrichmonds.com/images/190722-1750-Pcb2Gh.jpg

It's very hard to reproduce consistently, but appears to have something to do with moving the cursor from one row to another and clicking at the right moment in the tooltip's show/hide animation. I have experienced this issue many times over the past couple months, but can't say for sure that it only happens when I clicking a row. It might also happen when just scrolling/moving quickly.

### Steps to Reproduce
I was able to reproduce the issue on the demo server with these steps:

1. Go to a page with a grid of data that opens a modal dialog box when a record is clicked (Defined Type Details for example)
1. Hover over a record, move to another record and click
1. Re-try step 2 with varying mouse speeds and delays between movement/clicking until the tooltip gets "stuck"

**Expected behavior:**

The tooltip should disappear when the cursor leaves the row, or when something is clicked

**Actual behavior:**

The tooltip remains visible on the screen in front of all other page elements until the page is reloaded

### Versions
* **Rock Version:** McKinley 8.8 (1.8.8.3)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1142113391388320">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1142113391388322">GridTooltips.xlsx</a>

**Comment by JRichmond27** [comment]
Forgot to mention that I'm using Chrome 75.0.3770.142 on Windows 10.

**Comment by cabal95** [comment]
I have also experienced this in Firefox and Safari. Best steps to reproduce I've found are "going to fast".

**Comment by nairdo** [comment]
ref https://github.com/SparkDevNetwork/Rock/commit/2d0aa86dcf2cf6cbe1e781f0f8bdaf99bd128dbf
