### ISSUE TITLE
Dataview Person filter "Campus" filters out deceased

### ISSUE THREAD

**Issue by TheCoreyHall** [SparkDevNetwork/Rock#3821]
### Description
First I am unsure if this is a bug or the intended design. But if you have a person marked deceased and created a Person data view with a campus filter, that person will not be reported it in. I have even tested a data view that first looks for people marked deceased, confirmed they are there, then added the campus filter for their campus and they dissapear

### Steps to Reproduce
1. Go to the rock demo site.
1. Mark Ted Decker as inactive with reason Deceased
1. Create a Person Data view with filter of Campus only: ![image](https://user-images.githubusercontent.com/38293092/61909459-d2e6b180-aef7-11e9-8dfe-c180550ea750.png)
1. Observe that Ted Decker is not in the returned list of people

**Expected behavior:**

Since its only filtering on campus, and Ted's family is in Main Campus, he should be returned

**Actual behavior:**

Ted Decker is not returned in the data view

### Versions
* **Rock Version:** [8.8]
* **Client Culture Setting:** [en-us]

**Comment by JimMichael** [comment]
This seems like Working As Designed to me... wouldn't you _never_ want to return a deceased person unless you specifically query on IsDeceased = Yes? Filtering on _only_ campus (per the example above), I wouldn't expect deceased people to be in the results. But the fact that you can filter on IsDeceased=Yes AND Campus within the same DV and Ted is not returned seems like the bug to me.

**Comment by JimMichael** [comment]
Oh, sorry... I now realize in the description above you say just that... but the steps describe adding a campus (only) filter and expect to get Ted back, which is wrong IMO.

**Comment by nairdo** [comment]
I'll be discussing this with the team this week, but I believe filtering out situations like deceased people is something that should be done in a "base" data view that other data views would/should use (be based on)...

So, I think I agree that a data view with _only_ a Campus filter should only be concerned with filtering out people with non matching campuses using all possible people.

**Comment by nairdo** [comment]
We eventually decided that we're adding a new "Include Deceased" [ ] checkbox on the main panel for any data view that applies to Person. That way someone will be able to check that to build a dv/report that needs to refer to deceased (there are known use-cases for that).
