### ISSUE TITLE
Inactive people cannot exit eRA

### ISSUE THREAD

**Issue by stevelipinski** [SparkDevNetwork/Rock#3824]
### Description
Code for eRA apparently skips Inactive people.  In the case of people Entering eRA, this seems acceptable.  However, for Exiting eRA, Inactive people should still be processed, otherwise they can remain in eRA state indefinitely, even while meeting all the criteria for eRA-exit.

### Steps to Reproduce
1. Person is Active and eRA
1. Mark Person Inactive
1. Wait/simulate them meeting eRA exit criteria
1. They never exit eRA

Former staff member with very active family.  Became eRA on 7/3/2018 (around the time we migrated to Rock).  Family moved out of state, and was marked Inactive - Moved on 7/25/2018.  Still an eRA to this date:

Person still eRA:
![image](https://user-images.githubusercontent.com/7024856/62053224-2c472d00-b1e5-11e9-99d5-04da9978bd53.png)

Person set Inactive on 7/25/2018:
![image](https://user-images.githubusercontent.com/7024856/62053019-c3f84b80-b1e4-11e9-9465-b48bf3da9459.png)

No Giving for over a year:
![image](https://user-images.githubusercontent.com/7024856/62053827-636a0e00-b1e6-11e9-8a32-7a395df8f786.png)

**Expected behavior:**

Person should either:

1. Immediately be marked for Exit eRA when set to Inactive. or
1. Inactive Person should still exit eRA when exit criteria reached (being an Active record should not be a criteria for exit)

**Actual behavior:**

Inactive Person remains eRA seemingly indefinitely.

### Versions
Rock Version: Rock McKinley 8.8 (1.8.8.3)
Client Culture Setting: en-US

**Comment by stevelipinski** [comment]
My example person had some recent family attendance, which may be misleading.  Rest assured, they should have exited eRA.  Another person in our db:
![image](https://user-images.githubusercontent.com/7024856/62055615-f9ebfe80-b1e9-11e9-8e42-f721e4666225.png)

**Comment by jrockman13** [comment]
![image](https://user-images.githubusercontent.com/22159658/62253218-c3191280-b3ba-11e9-8c8d-3b68f0ae16b0.png)

I can confirm we have the same issue. It would be difficult to replicate on demo since historical data is needed.

**Comment by stevelipinski** [comment]
Here is a Workflow (that can be unzipped and imported on v9+) that given a Person entity will check that they are Inactive with eRA of Yes.  If so, it will set the eRA End Date and eRA=No.
I ran this against a DV of Inactive People with eRA==Yes as a one-time cleanup.

I also added a WF Trigger for this on a Person Post-Save with Entity Type Qualifier Column of RecordStatusValueId and Changing To of 4 (which is Invalid).
The effect being, going forward, when a Person is changed to Inactive, they will also be set to not eRA.

Personally, I'm currently going to use this as a workaround until this issue is fixed.  Just sharing here for anyone following or discovering this issue.

[Set eRA End on Inactive_201910171738.zip](https://github.com/SparkDevNetwork/Rock/files/3741415/Set.eRA.End.on.Inactive_201910171738.zip)
