### ISSUE TITLE
Profile Placeholder Images are zero width on Firefox

### ISSUE THREAD

**Issue by BrentPirolli** [SparkDevNetwork/Rock#3826]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The user profile placeholder image for those without uploaded photos doesn't display on Firefox 68.0.1 (latest) for PC (I haven't tested on a Mac). Setting the width in CSS to be any value or setting a min-width will resolve this. This is the default Rock back-end theme and I replicated it on the demo server.

Before editing CSS:
![Capture2](https://user-images.githubusercontent.com/38138194/62079402-a47d1500-b21c-11e9-8b82-bfa7ddfc3e84.PNG)

After editing CSS:
![Capture1](https://user-images.githubusercontent.com/38138194/62079403-a646d880-b21c-11e9-8cbf-9b6f5042dc22.PNG)

### Steps to Reproduce
1. Using FF on PC, open the demo server and create a new user without a profile image.
2. View their profile and see the missing image.
3. Edit the CSS property `.personprofilebar-bio .photo` and add a min-width or a width of 180px and the image will appear.

**Expected behavior:**

Placeholder image would display.

**Actual behavior:**

Placeholder image does not display.

### Versions

* **Rock Version:** McKinley 8.8 (1.8.8.3
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Confirmed on Mac Firefox (Safari is OK).
