### ISSUE TITLE
Allow selection of English and Spanish language for DISC Assessment

### ISSUE THREAD

**Issue by jsandersrocks** [SparkDevNetwork/Rock#3829]
### Description
We need the ability to select different Languages on the DISC assessment.  This can easily be accomplished by localization, however we should have the ability to select from a supported language choice field.  I can do the work (C# developer Microsoft Employee specializing in ASP.Net).  I am at a bilingual Church and can provide the translation as well.

### Steps to Reproduce
N/A

**Expected behavior:**

Allow selection of English and Spanish language for DISC Assessment

**Actual behavior:**

New Feature

### Versions
* **Rock Version:** Rock McKinley 9.0 (1.9.0.23)
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
Hi @jsandersrocks, did you have a plan for how to store the localized strings? Support for multiple languages was a feature that we have not been able to support with our small development community. The difficulty of storing localized strings of text for values in code, databases and scripts was something that we could not take on. There are some Javascript solutions that may be the easiest (though perhaps not the cleanest) way forward for you.

We don't have any resources to put to this, but if you have a plan that doesn't require core changes we'd be interesting in hearing about them.

**Comment by jsandersrocks** [comment]
I do.  This is a bit different from full localization of the app however.  In this case we would want the ability only for this component and not the entire site so that native Spanish speakers can Take the test and see the results.  The idea is to start a resources dll with those constants and use them initially from this component only.  It would be trivial to do this for only this one component and then simply add a switch in the page we kick off to allow the component to run in the es-US context so it pulls those resources.  Later, if/when you localize Rock, you could simply add resources to this resource dll and turn on localization.  I decompiled and checked out your source and see you are just storing the question part as a static array.  The UI changes would pretty easy as well.    I can actually do the work for this particular ask.  Then you can review and push the changes if you want.  I am a developer and support Internet Explorer, Azure, Entity Framework, ASP.Net and work for Microsoft so I'll do a good job :-)

**Comment by jonedmiston** [comment]
@jsandersrocks sounds great we'd love to see what you come up with!

**Comment by jsandersrocks** [comment]
Jon, I am having trouble with the new definitions in the Code that are not in the DB.  Which Build should I be using?  Stuff like CampusStatusValueId, and ShowOnBulk, AttributesSupportShowOnBulk.  They all seem to come from Commit f90a0516.  Shouldn't the corresponding db changes be there to automigrate the database as well?

**Comment by cabal95** [comment]
Not sure if this is the issue or if there is actually a missing migration, but one note is that there is no automatic migration. You either need to run the `Update-Database` powershell command or create a `Run.Migrations` (I think it's plural, maybe it's singular) file in the ~/App_Data/ folder.

That said, they are also in the middle of the v9 beta release and making last minute fixes so it is possible that a commit got merged in that wasn't supposed to and/or was missing a corresponding commit.

**Comment by jsandersrocks** [comment]
That was it!  With you help I found in global.asax.cs                 if ( !File.Exists( Server.MapPath( "~/App_Data/Run.Migration" ) ) )

I like that technique!

**Comment by jsandersrocks** [comment]
I have finished all but one task.

The DISC assessment personality types are stored in the database and accessed from the cache with Rock.SystemGuid.DefinedType.DISC_RESULTS_TYPE.AsGuid()

Is there a compelling reason to put the Spanish translation of these in the database as well or should I simply use resource strings.  If the former, how should I do that and load these values on the next update?

I designed this so you have to enable the feature to select Spanish or English with a block attribute (hiding the dropdown for the Churches that at not Bi-Lingual.  How shall I document this new feature and would you like to do a formal code review?  

-Jeff

**Comment by jonedmiston** [comment]
@jsandersrocks that's were it got crazy for when we first considered language localization. The code side has nice patterns, but the database side is difficult. The is made even more by the extensibility of Rock. Defined types, attributes, etc are used in many different places in different ways. 

I don't see a great way to add it to the database without a lot of new models. We'd need one for mapping the defined values value and description to a localization string (e.g. `en-US`). But we'd need to do the same for attribute values. That said attribute values are often pointers to other entities. At the end of the day there would need to be 15-20 models that could need localization strings.

**Comment by jsandersrocks** [comment]
Understood, thanks.  I will slip these in as resource string then!
Once done, how do you want to handle review and integration of the changes.  I had forked the repro on my end.

**Comment by jonedmiston** [comment]
@jsandersrocks If you do a PR we can review it from there.

**Comment by jsandersrocks** [comment]
I don't know if you saw it but it is here:
https://github.com/SparkDevNetwork/Rock/issues/3829#

I am going to do the Spiritual assessment too if you approve of this one!

**Comment by jonedmiston** [comment]
This is a large change than we were expecting. It might take us a bit longer to process the PR as we're in the middle of a couple of large releases. 

Since the PR is pushed I'm going to close this issue. We can continue the discussion on the PR.
