### ISSUE TITLE
Home address not visible on family profile page after updating

### ISSUE THREAD

**Issue by TerriBorchardt** [SparkDevNetwork/Rock#3830]
### Home address appears on person profile but not on family profile page. 
A clear and concise description of what the bug is, include screenshots if applicable.

![Family Profile Page after edit](https://user-images.githubusercontent.com/44209657/62162982-46106f00-b2ce-11e9-8213-bc3bd0087f72.png)
![Person Profile](https://user-images.githubusercontent.com/44209657/62162983-46106f00-b2ce-11e9-9bcd-020ece537b37.png)
![Update to Home Address](https://user-images.githubusercontent.com/44209657/62162984-46106f00-b2ce-11e9-843d-d3b22089d44e.png)

### Steps to Reproduce
1. Go to 'family profile page.'
1.  Add new address, save, exit to person profile
1. View address on person profile page
1. Go back to family profile page, address is not visible

**I expect the address to be visible on the family profile page:**

**Address is not visible on family profile page**

### Versions
* **Rock Version:** [McKinley 8.8]
* **Client Culture Setting:** [ENG - US]

**Comment by nairdo** [comment]
@TerriBorchardt Can you confirm you pressed the green checkmark (circled in screenshot below) to save the address before pressing the orange Save button?  

![image](https://user-images.githubusercontent.com/383807/62163606-8c1a0280-b2cf-11e9-928d-88fb7a2b735a.png)

**Comment by TerriBorchardt** [comment]
Yes, I even deleted the address and added it back in again, because I thought maybe I had forgotten to do that. Sometimes I’ll be working in a record that has the same address multiple times (like it gets added every time they register for something). I’ll delete all the duplicates, but the current home address isn’t visible so I have to make one of the duplicates the current one. Does that make sense?

I chatted with Crista Jardine this morning, and she’s having the same problem. She was able to duplicate it on the demo site. The weird thing is that it shows on the person profile page as the current address but just is not visible on the family profile page. I checked with Garrett before submitting the bug. He’s the one who told me to submit it. Hope that helps!

**Comment by JimMichael** [comment]
Trying to dupe this, but I don't understand your statement _The weird thing is that it shows on the person profile page as the current address but just is not visible on the family profile page._

What is a "family profile page?" I'm not aware of an address showing anywhere but on the PERSON profile page, within the family bar. Can you clarify?

**Comment by TerriBorchardt** [comment]
Garrett called it the family profile page. I guess the technical name for it is “Edit Family” Page.


  1.  Edit Family Page (pic #1):  Ben Jones moved. I updated his address to 5152 W Belmont Ave., saved the address and exited back to his person profile page.
  2.  Person Profile Page (pic #2):  You can see his address on Belmont. So I clearly must have saved it on the Edit Family page.
  3.  Edit Family Page w/error (pic #3):  I don’t remember why I went back into the Edit Family page, but when I did, the address is not visible. Why would it show on the person profile page if it wasn’t saved before exiting that screen?


This is not an “all the time” problem. It’s pretty random, but it has happened on more the one occasion. I have just chosen to ignore it in the past since I can still see the address on the Person Profile page. I don’t know if it has to do with the address now appearing on one line instead of two. I did see a bug submitted for that problem. Maybe they’re connected??

Does that help?

**Comment by cabal95** [comment]
@TerriBorchardt Just checking, but when you say "went back", are you talking about hitting the Back button on the browser or clicking the Edit button again?

**Comment by TerriBorchardt** [comment]
I’m sorry! I guess I need to check my terminology before I reply. I actually keyed in the new address, hit the green check button, then the save button which took me back to the person profile page. I don’t actually hit the back browser button. I just tried again to add the address, and I get the same result.

**Comment by cabal95** [comment]
No worries, it didn't sound like that was what you were doing but just wanted to rule out the back button.

**Comment by cj-walk** [comment]
I'm experiencing the exact same thing. I've spoken with someone on 8.7 and everything works fine. I'm on 8.8. I edit the family, clicked either family moved, or just add a new address. After entering the address and checking the green box the address doesn't appear to be there. Save family though, and the address does show up on the family bar. Edit again and you see the address type but no address until you click to edit the actual address then you see that the address is actually still in the boxes. 

It may be only when address standardization is used though. When I enter a fake address it shows up.

**Comment by tscrip** [comment]
I can confirm this is happening at 2 clients (both on Rock 8.9). I can confirm that clearing cache does not resolve the issue. The information displays on the Family Screen, but when you go to the Edit Family screen, the address is missing. If you click the Edit button on the hidden address, it shows the address information.

Here is a solution that fixed both client's issues. In the Location table in the DB, there is a column for Country. When the data was imported for both these clients, United States was brought over as "United States" instead of the Rock standard of "US". As a result, when this block goes to render this text, it does not know how it needs to be displayed, so it doesn't display the text.

There are two potential solutions. 
1. Use SQL to update all of the Locations from a Country of United States to US.
2. Add a Defined Value to the Defined Type of Countries with the Value of United States.

All this being said, I think the following commit needs to be updated to account for this situation:
https://github.com/SparkDevNetwork/Rock/commit/5cf2123c66cd1bb730a8122a5f2983bede6d7ae3

**Comment by nairdo** [comment]
Thanks for everyone's assistance on this.  The underlying issue (incorrectly imported data) is not something that we're going to address with code changes in Rock.
