### ISSUE TITLE
v9 Beta - SMS from Check-in Manager

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#3832]
#3050 # Description

When clicking on a phone number and sending an SMS in Check-in Manager the text message never gets sent. 

### Steps to Reproduce

1. Go to checkin manager
2. Search for a person
3. Click on phone number to text message
4. Enter message text
5. Hit sent

![image](https://user-images.githubusercontent.com/657005/62218358-e9669000-b371-11e9-8c37-8f475b1361e1.png)

**Expected behavior:**

Message gets sent
**Actual behavior:**

Message does not get sent. 

### Versions

* **Rock Version:** Rock McKinley 9.0 (1.9.0.24)

**Comment by JimMichael** [comment]
I'm seeing the same on my v9 beta instance. I can send SMS to a number via New Communication, but texting the same number from Check-in Manager never arrives, though the UI says "Message Sent."
