### ISSUE TITLE
Child's Attribute Categories Missing on Family Pre-registration Form on Mobile Devices

### ISSUE THREAD

**Issue by edcylam** [SparkDevNetwork/Rock#3834]
* 

### Description
Child's attribute categories on the Family Pre-registration form are missing when it is displayed on the iPhone or Chromebook.

### Steps to Reproduce
1. Go to the Family Pre-registration form on a mobile device
1. Click on "Add Child"
1. See the attribute categories missing

**Expected behavior:**

The selected attributes should be displayed in the Child section

**Actual behavior:**

All the selected attributes are missing when the form is displayed on the iPhone or Chromebook.

**On the laptop**
![](https://user-images.githubusercontent.com/24534451/62247150-0d3dcc00-b39a-11e9-8c30-d6408ffb1f08.png)

**On the iPhone**
![Image-1](https://user-images.githubusercontent.com/24534451/62247177-23e42300-b39a-11e9-934e-504b3582211d.jpg)

### Versions
* **Rock Version:** [8.7]
* **Client Culture Setting:** [en-US]

**Comment by JimMichael** [comment]
I cannot duplicate this on iOS against 8.6 or 8.6 (don't have 8.7 running on any instance here). It also renders fine when I shrink a desktop browser down to mobile size. We have only a few attributes and you seem to have many, so maybe that's a factor?
![image](https://user-images.githubusercontent.com/3903408/62249489-294c6800-b3b0-11e9-8ed0-55b7213464e5.png)

**Comment by edcylam** [comment]
I just went to test a bit more on my iPhone. Actually, Safari doesn't have
any issue, and only Chrome does.

<http://www.venturechristian.org/>
*Edmund*Lam
Technology & Analytics MANAGER
edmund@venture.cc | 408.997.4600
*16845 Hicks Road, Los Gatos, CA 95032
<https://www.google.com/maps/place/16845+Hicks+Rd,+Los+Gatos,+CA+95032/data=!4m2!3m1!1s0x808e36b3fcbbf1c9:0x1d7da23ee96c622?sa=X&ved=0ahUKEwjwtMDK-qrOAhUMwmMKHW8vDNIQ8gEIHDAA>*

**Comment by JimMichael** [comment]
Only Mobile Chrome? It's also working fine here on Chrome 76.0.3809.87 on Win 10 (shrunk down to mobile width)

**Comment by edcylam** [comment]
Also the 11” Chromebooks used by the check-in team.

**Comment by nairdo** [comment]
I believe this may be a security/permissions setting issue. @edcylam can you veryify the security on those attributes is "All Users" allow VIEW/EDIT?

**Comment by edcylam** [comment]
@nairdo I think so, but it is still not viewable.

<img width="1191" alt="Screen Shot 2019-08-01 at 3 21 18 PM" src="https://user-images.githubusercontent.com/24534451/62331246-3d579e80-b470-11e9-8b1d-e3a07a45654c.png">

**Comment by nairdo** [comment]
@edcylam Currently it requires EDIT to be able to fill out the attribute value field in that block.

**Comment by nairdo** [comment]
@edcylam  Can you verify that when you add EDIT for "All Users" it works?
