### ISSUE TITLE
"Ignore manual campus" option in Data Automation | Update Family Campus Does Not Work

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3835]
### Description

We have the _Ignore any family that has had a manual campus update in the last_ option of the *Update Family Campus* Data Automation job set to 120 days, yet we are clearly seeing cases where it continues to change the campus even though there are recent manual updates.

### Steps to Reproduce

1. Go to Tools | Data Integrity | Data Automation and edit the Update Family Campus _Ignore any family..._ option to 120 days.
 
2. Find someone who will have their campus moved by the job in the upcoming run due to other parameters defined (attendance or giving at new campus) 

3. Manually change the person's Campus to something other than what the automation job will set.

4. Observe that the Data Automation job still changes the person's campus even though it was "manually set" well within the 120 days defined.

**Expected behavior:**

Campus would not change if it was manually set within the time period defined in the job setup.

**Actual behavior:**

Here's our setting on the Move Family Campus Job
![image](https://user-images.githubusercontent.com/3903408/62263400-ae03aa00-b3e1-11e9-8105-eadfea99cdd9.png)

And here's an example of a person who's campus is being manually changed, then changed by the automation job, then manually changed in a crazy tug-of-war between human and machine.

![image](https://user-images.githubusercontent.com/3903408/62263478-ff139e00-b3e1-11e9-9e15-92c6b78087af.png)

### Versions

* **Rock Version:** 8.8

**Comment by trydyingtolive** [comment]
There is a fix for this in PR #3741

**Comment by JimMichael** [comment]
Can anyone tell me what version this PR will end up in?

**Comment by nairdo** [comment]
@JimMichael  I'm going to cherry-pick this into v9.2.
