### ISSUE TITLE
Bulk Update: Group Member Attribute Single-Select Radio Buttons

### ISSUE THREAD

**Issue by SteveSwaringen** [SparkDevNetwork/Rock#3837]
### Description
When using bulk update to update a group member attribute that is a Single-Select with Radio Button controls, the radio button controls are not clickable.

### Steps to Reproduce
1. Go to RockSolidChurchDemo.com. Create (or modify) a group type that includes a group member attribute that is a Single-Select with Radio Button controls. Create a group of this type and add a couple of group members.

![SingleSelectAttribute](https://user-images.githubusercontent.com/45042927/62317801-0f6a5e00-b460-11e9-99b4-ec2ca892b986.PNG)
![GroupTypeDetail](https://user-images.githubusercontent.com/45042927/62317806-11ccb800-b460-11e9-9d08-d1b7f0b9caa5.PNG)

1. Select one or more of the members and click on the Bulk Update icon. Expand the Group section. Set the Action to "Update in Group", and select the test group. ![GroupView](https://user-images.githubusercontent.com/45042927/62317820-17c29900-b460-11e9-9730-510f322755c2.PNG)
1. Check the circle that enables the attribute to be modified. Note that the radio buttons are present, but not clickable. ![BulkUpdate](https://user-images.githubusercontent.com/45042927/62317828-1d1fe380-b460-11e9-982c-410fab0389d7.PNG)

**Expected behavior:**

The radio buttons should be clickable so the user can set the state they want to bulk change the group attribute to.

**Actual behavior:**

The default radio button is selected and cannot be changed.

This appears to be a problem in BulkUpdate.ascx.cs regarding when or under what circumstances partial postbacks occur. The controls do not enable because the SelectedFields list is empty. This property is loaded from a hidden field in the view state. It appears that no postback occurs after the user clicks the circle to enable the control, so the form is not regenerated with the controls enabled.

A work-around is to check the control to enable it, then change the Action to "Add to Group", then change the Action back to "Update in Group". This will cause the SelectedFields list to be populated and the controls enabled.

### Versions
* **Rock Version:** Rock McKinley 8.8 (1.8.8.3)
* **Client Culture Setting:** en-US

**Comment by pdonlevy** [comment]
I tested this and was able to recreate in the demo site (v9.1) and the alpha site (v11.0).  The work around described works in both environments.

**Comment by billdeitrick** [comment]
Bumped into this today and noted that it is still present in v13.4; can reproduce on Rock Solid Church demo.
