### ISSUE TITLE
"Registration Full" Alert Shows When Waitlist is Enabled and Maximum Attendees value is set to 0

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/Rock#3844]
### Description
I believe this is related to previous close [issue 3617 ](https://github.com/SparkDevNetwork/Rock/issues/3617) but didn't know if it was appropriate to comment on the original issue or create a new issue.

It appears that the recent update in 8.8 described as _Improved RegistrationEntry Max Attendees handling. 0 will continue to mean unlimited. < 0 will put registrations right to the waitlist._ is performing as expected in regards to directing user to the registration process or waitlist process. However if the waitlist is enabled and the maximum is set to 0 it shows the "Registration Full" alert and then allows the user to register normally. So it appears that the alert logic needs to be re-coded.

### Steps to Reproduce
1. Create [a Registration Template ](https://rock.rocksolidchurchdemo.com/page/403?RegistrationTemplateId=3) with the Waitlist Enabled
1. Create [a Registration Instance ](https://rock.rocksolidchurchdemo.com/RegistrationInstance/1) for that template with a Maximum Attendees value of 0
1. View [the registration entry ](https://rock.rocksolidchurchdemo.com/registration/camptest) for the instance and notice that it shows the alert prompt "Registration Full This Registration has reached its capacity. Complete the registration below to be added to the waitlist." but behaves as if it is a normal non-waitlist registration.

**Expected behavior:**

Registration Entry does not show "Registration Full" alert when waitlist is enabled and the Maximum Attendees value is set to "0".

**Actual behavior:**

Registration Entry shows the "Registration Full" alert when waitlist is enabled and the Maximum Attendees value is set to "0".

### Versions
https://admin.ccvsocal.com

* **Rock Version:** Rock McKinley 9.0 (1.9.0.24)
* **Client Culture Setting:** en-US

https://rock.rocksolidchurchdemo.com

* **Rock Version:** Rock McKinley 8.9 (1.8.9.1)
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
The correct behavior of the block concerning Max Attendees:
1. If Max Attendees was not specified in the registration instance that means there is no limit on registrants.
2. If Max Attendees is 0 all registrants will go to the Wait List if one exists.

Fixed logic where the wait list notification could show incorrectly when max attendees was not specified.
