### ISSUE TITLE
Problems with UserLogin history logging when there is no Person Id.

### ISSUE THREAD

**Issue by richarddubay** [SparkDevNetwork/Rock#3845]
**Recommended Resource: Ethan**

We're experiencing this in a couple of different places, but it's probably an issue with any action.

When someone new (they do not have a record in the `UserLogin` table) puts in their phone number to sign in to our app, we create a `UserLogin` record (a `POST` using the API) with their phone number as the `UserName` but with no `personId`. Right now, the `PostSaveChanges()` function is erroring out on trying to save the history changes (https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/UserLogin.cs#L434) and never sends the person a pin number.

The same problem exists on someone who already has a `UserLogin` record (but doesn't have a `personId` on it). If you try to delete that record through the API it errors out. (https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/UserLogin.cs#L407)

![Screenshot 2019-08-07 15 01 47](https://user-images.githubusercontent.com/3229463/62650213-522aab00-b924-11e9-9248-88bc9bb458fa.png)

**Expected behavior:**

I should be able to add or delete (or any action really) a `UserLogin` record via the API without error ... even when that record does not have a person id.

**Actual behavior:**

If a `UserLogin` record does not have a person Id, the API calls fail.

### Versions
* **Rock Version:** 1.10.0.3
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
Changed UserLogin.PreSaveChanges and PostSaveChanges to only save history for a person Id if the person ID is not null. Also added try/catch protection so an exception during a history save will log an error and move on.
