### ISSUE TITLE
Rock v9.0 - Event Registration - Exception when loading Registrations with Fee

### ISSUE THREAD

**Issue by nathanp** [SparkDevNetwork/Rock#3847]
### Description

We have upgraded to Rock v9 and we are experiencing some issues with viewing Registrations that have fees associated with them.

On these registrations, when we click on them, the error page with the `Object reference not set to an instance of an object.` message shows up and we are unable to view the registration.

This is only happening for registrations where the user has opted to pay an optional fee.
This error was not happening when we were on v8.8.

### Steps to Reproduce

1. Upgrade to 9.0 
2. Click on a registration that has a fee associated with it.

I ran the following query which included 266 results: `SELECT * FROM RegistrationRegistrantFee WHERE [RegistrationTemplateFeeItemId] IS NULL`

**Expected behavior:**

View the registration.

**Actual behavior:**
Error page with the following stacktrace:

```C
at Rock.Model.FeeInfo..ctor(RegistrationRegistrantFee fee)
   at Rock.Model.RegistrantInfo..ctor(RegistrationRegistrant registrant, RockContext rockContext)
   at RockWeb.Blocks.Event.RegistrationDetail.<>c__DisplayClass51.b__4a(RegistrationRegistrant r)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at RockWeb.Blocks.Event.RegistrationDetail.ShowReadonlyDetails(Registration registration)
   at RockWeb.Blocks.Event.RegistrationDetail.ShowDetail(Int32 registrationId, Nullable`1 registrationInstanceId)
   at RockWeb.Blocks.Event.RegistrationDetail.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursivi()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

@cabal95 took a look and said that the code that is supposed to migrate that data is missing the part where it actually sets the Id value.

### Versions

* **Rock Version:** 9.0
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
The 9.0 update package will be updated with the fix.
9.1 will also have a fix in it.
The SQL below has been tested internally but not on a live system so please use caution and try it on a test system first. The queries will populate the missing data that is causing the error.

`-- UPDATE for single Fee Types
UPDATE [RegistrationRegistrantFee]
SET [RegistrationRegistrantFee].[RegistrationTemplateFeeItemId] = (
	SELECT [RegistrationTemplateFeeItem].[Id] 
	FROM [RegistrationTemplateFeeItem] 
	WHERE [RegistrationRegistrantFee].[RegistrationTemplateFeeId] = [RegistrationTemplateFeeItem].[RegistrationTemplateFeeId])
WHERE [RegistrationRegistrantFee].[RegistrationTemplateFeeItemId] IS NULL
	AND ( [RegistrationRegistrantFee].[Option] IS NULL
		OR [RegistrationRegistrantFee].[Option] = '')

-- UPDATE for multiple Fee Types
UPDATE [RegistrationRegistrantFee]
SET [RegistrationRegistrantFee].[RegistrationTemplateFeeItemId] = (
	SELECT [RegistrationTemplateFeeItem].[Id] 
	FROM [RegistrationTemplateFeeItem] 
	WHERE [RegistrationRegistrantFee].[RegistrationTemplateFeeId] = [RegistrationTemplateFeeItem].[RegistrationTemplateFeeId]
		AND [RegistrationRegistrantFee].[Option] = [RegistrationTemplateFeeItem].[Name])
WHERE [RegistrationRegistrantFee].[RegistrationTemplateFeeItemId] IS NULL
	AND ( [RegistrationRegistrantFee].[Option] IS NOT NULL
		OR LEN([RegistrationRegistrantFee].[Option]) > 0)
`

**Comment by ethan-sparkdevnetwork** [comment]
These queries will verify the data before and after the fix. 
```
SELECT fi.ID AS FeeItem_RegistrationTemplateFeeItemId
	, rf.RegistrationTemplateFeeItemId AS RegFee_RegistrationTemplateFeeItemId
	, ft.Name
FROM RegistrationRegistrantFee rf
join RegistrationTemplateFeeItem fi on rf.RegistrationTemplateFeeId = fi.RegistrationTemplateFeeId
join RegistrationTemplateFee ft on ft.Id = rf.RegistrationTemplateFeeId
WHERE ( rf.[Option] IS NULL OR rf.[Option] = '')

SELECT fi.ID AS FeeItem_RegistrationTemplateFeeItemId
	, rf.RegistrationTemplateFeeItemId AS RegFee_RegistrationTemplateFeeItemId
	, ft.[Name]
	, rf.[Option] AS RegFee_Option
	, fi.[Name] AS FeeItem_Name
FROM RegistrationRegistrantFee rf
left join RegistrationTemplateFeeItem fi on rf.RegistrationTemplateFeeId = fi.RegistrationTemplateFeeId AND rf.[Option] = fi.[Name]
left join RegistrationTemplateFee ft on ft.Id = rf.RegistrationTemplateFeeId
WHERE rf.[Option] <> ''
```

**Comment by nathanp** [comment]
Thank you @ethan-sparkdevnetwork, these queries have fixed the problem for us!

**Comment by ethan-sparkdevnetwork** [comment]
New 9.0 packages with this issue corrected have been released to alpha, beta, and production. The 9.1 package will also check for and fix this if needed.
