### ISSUE TITLE
Adding Feedback for an installed plug-in does not recognize user

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3849]
# Prerequisites #

* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description ###

I installed the Digital-signage plug in.  Went to add a rating from the Rock Shop Store Item Detail page from our internal site.

The RockShop rate page gives an incorrect error message that I have not downloaded the plug-in because it does not register that I am a valid user, because I am not logged on to www.rockrms.com at the time.

![signage1](https://user-images.githubusercontent.com/4658177/62749251-94311b00-ba10-11e9-86fc-f899820fb040.jpg)

![signage2](https://user-images.githubusercontent.com/4658177/62749259-9a26fc00-ba10-11e9-90df-4440d2719673.jpg)

### Steps to Reproduce ###

1. From within Rock go to the Rock Shop for an installed plug-in.  Home > Rock Shop - find installed plug in.
1. Click 'Add feedback'.  Make sure you are not logged into the www.rockrms.com site at the time.
1. View incorrect and misleading error message that 'Before submitting a rating you need to have downloaded this plug-in.'

**Expected behavior:**

Becuase the link to Add feedback came from a site where the plug-in IS installed, this error message should not display.

**Actual behavior:**

When linking to the external Rock Shop page to add a rating, the site does not recognize that the link has come from a site where the plug-in is installed.

### Versions ###

Rock Version: Rock McKinley 8.8 (1.8.8.3)

Client Culture Setting: en-NZ

**Comment by ethan-sparkdevnetwork** [comment]
The Rock Shop will now display a "login" message to the user.
"You must be logged in to submit a review."
