### ISSUE TITLE
Alpha 9.1 Job Failing 'Runs data updates that need to occur after updating to v9.0'

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3855]
### Description
When I go to the Jobs page, one of the new v9 update jobs is failing.

`The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_dbo.RegistrationRegistrantFee_dbo.RegistrationTemplateFeeItem_RegistrationTemplateFeeItemId". The conflict occurred in database "Rock", table "dbo.RegistrationTemplateFeeItem", column 'Id'. The statement has been terminated.`

Started out on 8.7 and updated to 8.8, 8.9, 9.0, then 9.1 alpha. I did these updates one after another so I don't know if I should have given it time to run in 9.0 before updating to 9.1.

### Steps to Reproduce
Update to 9.1 alpha.
Go to Jobs page and check the status of _Runs data updates that need to occur after updating to v9.0_ (for me it displayed failed)
Tried to manually run the job and it failed again.

**Expected behavior:**

I believe the job should run properly then remove itself from the job list.

**Actual behavior:**

Failed because of a Foreign Key issue.

### Versions
* **Rock Version:** 1.9.1.1
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
This seems to be the same issue that I reported in alpha-testers channel in Rocket.Chat last night regarding upgrading from 8,8 to v9... a couple of weeks ago the v8-v9beta went great, but when I rolled back to 8.8 on my test rig to do a fresh v9 upgrade prior to trying out 9.1alpha, I see the same job issue with an accompanying exception in the log.
