### ISSUE TITLE
.ics event download button doesn't work in Firefox or Safari

### ISSUE THREAD

**Issue by bengoshow** [SparkDevNetwork/Rock#3856]
### Description
When I click the "calendar" icon on an event detail view, nothing happens in Firefox (68.0.1) or Safari (12.1.2), both on macOS Mojave (10.14.6). In the Chrome browser, a download dialog box opens and you can save the .ics file to your computer.

### Steps to Reproduce
1. Visit https://rock.rocksolidchurchdemo.com/page/414?EventOccurrenceId=2
1. Click the red "calendar" icon
1. In Chrome, download and save a .ics file. In Firefox or Safari, nothing happens.

**Expected behavior:**

Download and save a .ics file to my hard drive.

**Actual behavior:**

In Firefox or Safari, nothing happens.

### Versions
macOS Mojave (10.14.6)
Firefox (68.0.1)
Safari (12.1.2)
Chrome (76.0.3809.100)

* **Rock Version:** 1.8.8.3 
* **Client Culture Setting:** en-US

**Comment by briankalwat** [comment]
Confirmed on `9.1.3`. Safari (13.0.2) and Firefox (70.0) just reload the page instead of downloading the ics file.

**Comment by tstephens17** [comment]
Do we have an estimation on when this will get done?

or

Has someone come up with a fix on their own?

**Comment by nairdo** [comment]
@bengoshow @tstephens17 , This fix is actually going to be in the .lava (/Assets/Lava/CalendarItem.lava) that you are using with in your site's theme.  Although we've fixed it in the three stock example themes shipped with Rock, as with all such changes, you'll need to apply that kind of fix manually (unless you're using the stock Stark theme).  The good news is: you can make that change now in your lava.

You can see our fix here (https://github.com/SparkDevNetwork/Rock/commit/e23a37603e6442866290d11f33c219b5e35bcb25) but let me break it down for you real quick...

In the `onclick` event for the calendar's 'Download Event' anchor tag, change the `ics_click()` call to include the event like this:

```
onclick="return ics_click(event);"
```
Then, change the ` ics_click` function that is defined in that file's <script> tag, to include the event (`e`) that is passed in and then add a `e.preventDefault();` as the first thing that function does right before the `text = `:

```
function ics_click(e) { e.preventDefault(); ...
```
