### ISSUE TITLE
Alpha 9.1 GroupMember Merge Field available in communication wizard but not in Simple Editor.

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3858]
### Description
`Added GroupMember as an available merge field for a communication if the communication recipients were created from the Group Member List block`

For this new feature, it is only present when using the communication wizard and not available when switching to simple editor. Not certain if it is intended only for the wizard or for both.

### Steps to Reproduce
1. Create a communication from a group.
1. Test the wizard but following the steps then adding a merge field. In the drop down you'll see Group Member.
1. Click Use Simple Editor and insert a merge field. In the drop down you won't see Group Member

**Expected behavior:**

Not certain if the Group Member field should be available in both editors or only the wizard editor.

**Actual behavior:**

Currently only available in the wizard editor.

### Versions
* **Rock Version:** v9.1.1
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1159897516611147">image.png</a>

**Comment by megilee** [comment]
This is confirmed as true in Demo running 9.2. Not sure if this intentional or not.
