### ISSUE TITLE
Disabled Person Attributes in DataView Filters Continue To Work

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3859]
### Description

Disabled Person Attributes within Dataviews that filter on them (prior to disabling the attribute) continue to filter on that attribute, and when editing the filter the disabled Person Attribute now shows at the top of the list.

### Steps to Reproduce

1. Create a DataView that filters on any Person Attribute
2. Observe that while choosing the attribute in the filter it's within the _Person Attributes_ section of the list.
3. Inactivate the Person Attribute from Admin | General | Person Attributes
4. Edit the Dataview and open the attribute filter and observe this disabled attribute is now showing at the top of the list, and the DV is still returning accurate data based on that filter.
![image](https://user-images.githubusercontent.com/3903408/63105575-b82bb980-bf46-11e9-964e-826e627a2c10.png)

**Expected behavior:**

Not sure, really. Maybe it's just working as designed, but wanted Core Team to weigh in. This is a case where a dataview is still filtering on a _subsequently_ disabled attribute. Should the DV continue returning results for that disabled attribute filter (as it does today), or should the DV throw an error, since this attribute is no longer supposed to be accessible?

**Actual behavior:**

DV's continue to filter on disabled person attributes, and show them at the top of the list when editing the filter.

### Versions

* **Rock Version:** v8+

**Comment by nairdo** [comment]
Thanks for this question. I know this was way back in the v8 days, but the correct behavior should be:

> Should the DV continue returning results for that disabled attribute filter (as it does today)?

Yes. But you should no longer be able to create any new Data Views with that inactive Attribute.  I verified this is happening in v16 and it should be happening in earlier versions too.
