### ISSUE TITLE
Exporting Reports with a field named ID cause duplicate exceptions

### ISSUE THREAD

**Issue by andypullen** [SparkDevNetwork/Rock#3862]
### Description
When trying to generate an XLS file from a Report that is based on a Group, when the Report contains a column labeled "ID" (case sensitive), an exception will be thrown and the generated file will contain the error "An item with the same key has already been added." along with the stack trace.

### Steps to Reproduce
1. Create (or use) a Data View applying to Group
1. Create (or use) a Report pulling from the Data View from Step 1
1. Include a field with a Column Label named "ID"
1. Export the Report to an XLS and view the outputted html file

### Versions
* **Rock Version:** Rock McKinley 8.6 (1.8.6.2)
* **Client Culture Setting:** en-US

![<a href="https://user-images.githubusercontent.com/383807/63476668-d27a0180-c436-11e9-9160-6b7d94b6db7f.png">https://user-images.githubusercontent.com/383807/63476668-d27a0180-c436-11e9-9160-6b7d94b6db7f.png</a> image]()

**Comment by nairdo** [comment]
@andypullen  I'm unable to reproduce on v8.8. Can you verify that this example report meets the conditions of the situation you're encountering: https://rock.rocksolidchurchdemo.com/page/149?ReportId=7

**Comment by andypullen** [comment]
Hi @nairdo you are close — the column label of the Id field is case sensitive and needs to be "ID" (with capital I & D). I've edited it and it now hits the error when trying to generate the XLS file.
