### ISSUE TITLE
DISC link in Assessment Badge on the internal Person Profile page and DISC Results page

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3863]
### Description
Not certain if this needs to be broken up into multiple issues or if one will suffice. When clicking the DISC link in the Assessments Badge on the Person Profile page, it brings me to /DISC (which is page 730 for us). The block on this page is the DISC Assessment block. Prior to v9, clicking the DISC badge would bring us to page/350, which contains the DISC Results block. 

The issue I noticed is /DISC does not contain additional information for staff use. If you switch it to page /350 you'll get the additional information (Under Pressure, Motivation, Team Contribution, Leadership Style, Follower Style).

I noticed this on our dev server, our production is still in v8. I have verified the Sites domains are correct. According to @nairdo, "...each assessment is now supposed to have a single block (not a results block) that manages showing the result and/or taking the assessment." For this reason I can understand why /DISC (page 730) contains the Assessment block, however, it is treating me as if I am the one who took the assessment instead of displaying it for staff use (which provides more information that the assessment taker doesn't see).

If the result block isn't being used should that page be removed or should the block be swapped from the results to the assessment block? 

Second, should the new assessment block then determine if the viewer is on the internal site (staff) and display the extra info while displaying basic info when viewed from the external site?

Lastly, in the v9 update, were DISC numbers recalculated? My number totals differ between v8 and v9 and if they were recalculated, I'm not sure they recalculated properly since my "I" was a 13 but is now 0 and those that were 33 are now 100--which both cause styling issues too since the 0 is over the "I" and 100s runs into the sub-header.

Assessments Badge:
![](https://user-images.githubusercontent.com/5738650/63387895-3a174a80-c36c-11e9-8398-71f365cf4ad7.png)

DISC Routes:
![](https://user-images.githubusercontent.com/5738650/63387905-41d6ef00-c36c-11e9-94bd-42f590570e33.png)

/DISC (page/730) page using DISC Assessment block
![](https://user-images.githubusercontent.com/5738650/63388892-8748eb80-c36f-11e9-96f7-c9629cf96468.png)

page/350 Old DISC Results block for internal site
![](https://user-images.githubusercontent.com/5738650/63388898-8c0d9f80-c36f-11e9-9f49-6f7e81fa84c3.png)

v8 DISC Results using page/350 (showing the number values have changed)
![](https://user-images.githubusercontent.com/5738650/63388123-fa049780-c36c-11e9-9ab0-cb0ef2cddb4c.png)

### Steps to Reproduce
1. Go to your Profile page or a Profile page of someone who has completed the DISC assessment (view in v9)
1. Hover over the Assessments badge and click on the DISC button/link.
1. This should take you to /DISC (in v8 it was page 350, in v9 it is a new page with the Assessment block) but will display the info like you are the assessment taker
1. This page/block doesn't show the additional info staff use to see in v8, also the numerical values for each person has changed

**Expected behavior:**

Display the additional information for staff use as it did in v8.
Not certain if the letter values were suppose to be recalculated, and if so, I'm not sure they recalculated properly. My "I" was 13 before v9, where it is 0 now.

**Actual behavior:**

Displays the basic results as if you were the assessment taker instead of staff.

### Versions
* **Rock Version:** v9.0 and v9.1
* **Client Culture Setting:** en-US

**Comment by timlem** [comment]
I would add that the disc results are broken showing incorrect values since upgrading to v9.
![Screen Shot 2019-09-15 at 11 20 41 AM](https://user-images.githubusercontent.com/1486523/64923735-f7019900-d7aa-11e9-8e04-e26564d242c4.png)

I'm on v9.2

**Comment by nairdo** [comment]
@BEGamache The DISC scores were re-normalized from 0-33 to 0-100 scale as part of the v9 update. A job actually performed the conversion.  To avoid any confusion, lets identify this issue #3863 as related to the missing `additional information (Under Pressure, Motivation, Team Contribution, Leadership Style, Follower Style).` 

Hi @timlem, the issue you're showing (where values have gotten pushed to the 100 value) would be caused if someone runs the "Rock Update Helper v9.0 - DISC" (PostV90DataMigrationsForDISC ) job more than once.  Do you recall possibly attempting to manually run that job after the update?

**Comment by nairdo** [comment]
There will be a few commits to deal with this item.  This first one is to prevent the conversion job from running twice on a system (https://github.com/SparkDevNetwork/Rock/commit/51cd25cd168c202518a4c7fd73acd3e00e7fb6f8; that fix has been put into the v9.0, v9.1, and v9.2 releases).
