### ISSUE TITLE
Checkr Background Check Result should be cleared when starting new background request

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#3864]
### This isn't necessarily a bug. Or maybe it is. You guys decide. :slightly_smiling_face:
I was unable to do this on the demo site since there is no Checkr integration.

We had a person who had previously had a background check and **background check result** was marked as passed. That background check expired so we ran a new one. It came back with the status of consider and in her profile it updated the **background check date** and **background check document** with the new date and new document. As far as Rock is concerned she passed the background check and meets requirements to serve or whatever.

It would be nice if when a new background check is started it clears the **Background check result** or when the results come back when it updates the date and document it changes the status to pending or "consider"

### Steps to Reproduce
1. Have a person with background check status of **pass** and background check date of 2 or 3 years so it's expired.
1. Run new background check and somehow force status of **consider**
1. Look at person history to see that Rock updated the date and document, no change to result so it looks like he/she passed this background check

### Versions
* **Rock Version:** [9.0 (1.9.0.26)]
* **Client Culture Setting:** [en-us]

**Comment by JimMichael** [comment]
We recently moved to Checkr and noticed this confusing behavior, too. We're probably going to add a "Pending" option to the Background Check Result single-select  attribute and modify the workflow to set it to Pending whenever a new check hits the "Waiting for result" status. That way, whether a check is new or a renew the result will show as Pending until it comes back clean, or is manually pass/failed (for ones that come back "Consider")... but it would be nice if this were addressed in Core.

**Comment by jonedmiston** [comment]
Jumping in on this one to try to move it to completion. See the issue and see the need for a change. I'm worried about two things:

1. If we make a change to set the individual's background check status to "Pending" or "in Review" we could break a church's process that would keep the individual from being able to serve. For instance they may not be able to check-in the next week as their status is not "Passed". It could be their current check is good for another few days, weeks or months.

2. It would be pretty easy for use to make a change here, but we could also break other custom changes a church has made to the workflow. We could only make the change if the workflow has not been modified by the organization. 

Any input on these scenarios?

**Comment by jonedmiston** [comment]
Talked with a few community members on this. Based on the fact that many have already updated their workflows to provide work arounds we're going to close this as any adjustments we did would break their changes.
