### ISSUE TITLE
Captive Portal block always creates new person if Phone Number or Email is hidden

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3865]
### Description
In the CaptivePortal block, if you turn off phone number it will always create a new person instead of looking for a match first. If First+Last+Email is entered, it should still look for a match instead of creating a new person.

### Steps to Reproduce
1. Configure Captive Portal block to not ask for phone number
1. Setup Captive Portal to operate with Front Porch
1. Enter portal information for matching person in database.
1. See  new person is created.

**Expected behavior:**

An existing person should be searched for by First+Last+Email before creating a new record.

**Actual behavior:**

A new record is always created.

### Versions
* **Rock Version:** 8.8
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Should be fixed by 0fab108341e649bb878c5f06214a6ebde5a5ecd2 (probably 9.3 or 10.0)

**Comment by nairdo** [comment]
Thanks @cabal95 for catching this reference -- I hadn't seen this issue before.
