### ISSUE TITLE
Install Failing

### ISSUE THREAD

**Issue by sparrowonedev** [SparkDevNetwork/Rock#3870]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
Yes
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
previous release... i cannot find current version # (Aug 20 release)

    * Did you [perform a cursory search](https://github.com/issues?
Yes
q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Failing during install.
getting this error:   That Wasn't Suppose To Happen An error occurred while configuring Rock. Message: Object reference not set to an instance of an object.

### Steps to Reproduce

**Expected behavior:**

**Actual behavior:**

A description of what actually happened.

### Versions

* **Rock Version:** [Enter Rock version here]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by jonedmiston** [comment]
We don't offer support in our Github issues. We would recommend asking this question in our chat community (https://chat.rockrms.com).
