### ISSUE TITLE
Email Wizard two column layout doesn't work on mobile

### ISSUE THREAD

**Issue by dylan-gregory** [SparkDevNetwork/Rock#3871]
### Description
Whenever you build an email with the Email Wizard using the two-column drop-in section, the 50% width is not honored on mobile. It looks correct in a desktop browser on a mobile size, but not on an actual mobile device.

reproduced in 9.3 on iOS

![Image from iOS (1)](https://user-images.githubusercontent.com/22873277/63595917-14668d00-c588-11e9-93ae-d795a0220caa.png)

### Steps to Reproduce
1. Start building a new email
1. Drop in a two-column layout section
1. Drop in text or images into the left and right sides
1. Send the email and view it on a mobile device (currently only tested on iPhones)

**Expected behavior:**

Those columns should respect the styles given to them to make each section 12 columns at the small breakpoint.

**Actual behavior:**

It looks like the left column becomes about 11 cols, the right 1 col (see screenshot above).

### Versions
* **Rock Version:** 8.7
* **Client Culture Setting:** en-US

**Comment by spurgeonbj** [comment]
Tested and found that this is not a bug (on Rock 8.9 production)

**Comment by thimmarajusv** [comment]
![Screenshot_2019-10-24-23-15-18-526_com google android gm](https://user-images.githubusercontent.com/34569384/67511488-a0924f00-f6b4-11e9-833c-541b43767560.png)

**Comment by dylan-gregory** [comment]
It is still an issue in v9.3 on iOS 
![Image from iOS](https://user-images.githubusercontent.com/22873277/67512873-bd546580-f667-11e9-8aad-1a9923c7a22e.png)

**Comment by garrettjohnson** [comment]
Apple Mail and Safari will now ignore certain styles when a document does not have a doctype. With the fix we now inject the html5 doctype automatically.
