### ISSUE TITLE
Registration does not display registration name when using slug link

### ISSUE THREAD

**Issue by craigmash** [SparkDevNetwork/Rock#3872]
### Description
First appears in version 9, also in 9.1.
When going to an open registration using the slug URL, the Page Title is displayed instead of the name of the Registration.

### Steps to Reproduce
1. Go to 'https://rock.rocksolidchurchdemo.com/Registration/camp'
1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior:**

Should display registration name instead of Page Title

**Actual behavior:**

A description of what actually happened.

### Versions
* **Rock Version:** [9.0 & 9.1]
* **Client Culture Setting:** [ en-US]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1140370943272127">ApplicationFrameHost_2019-09-19_15-02-46.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1141631615671325">ApplicationFrameHost_2019-09-25_09-39-48.png</a>

**Comment by randyjreed** [comment]
I have confirmed this error on my v9 sandbox also.

**Comment by craigmash** [comment]
Disagree with making the priority on this low. This has mad the slug links useless for us. I have resorted to having to put the event name in the descriptions when the slug link is required. Was hoping to see this fixed in 9.2.

**Comment by ethan-sparkdevnetwork** [comment]
Fixed the block so the breadcrumbs, title, and the browser tab display the registration name when using a slug.
