### ISSUE TITLE
Registration "Registrants In Same Family" Not Displaying Family Member Drop Down

### ISSUE THREAD

**Issue by morganw93** [SparkDevNetwork/Rock#3874]
### Description
If a registration template for registering multiple people has:

* 'Yes' selected on the Registrants In Same Family attribute selected, 
* the show family members box checked 
* and login is forced on the registration, 

...when you register the first person, the family member drop down is **not** displayed.

If you click the back button on your browser twice it reload the page with the drop down showing. 

### Steps to Reproduce
1. Build a registration template that allows multiple registrants with 'Yes'  selected on registrants in the same family, check the box for show family members, and check the box for login required. 
1. Go to register people.
1. the dropdown to select a family member will not display but the logged in person's info will auto fill the reg form. (so if they aren't registering themselves but another family member they now have to register themselves.)

optional step: double click the back button on the browser and then the drop down appears.

**Expected behavior:**

The family member drop down would appear to select who you are registering. 

**Actual behavior:**
It does not appear.

### Versions
* **Rock Version:** [v9.1]
* **Client Culture Setting:** en-us

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1154211865638939">image.png</a>

**Comment by luke-infoministry** [comment]
Confirmed as well.  If **Registrants In Same Family** is set to 'Ask' rather than 'Yes', then when "Registrant is in the same immediate family as" is selected to the currently logged in person, the drop-down to choose a family member appears.

**Comment by JesseM-PC** [comment]
Can someone confirm that this is fixed? We are on 9.4 and seeing the same issue.

**Comment by nairdo** [comment]
@JesseM-PC We've had two technicians attempt to reproduce the issue you're seeing on a Rock version 9.4 system, but neither of them was able to.  I'm going to re-close this issue out but you are welcome to open a new issue with the details from your environment if you still think this is an issue in Rock v9.4
