### ISSUE TITLE
Marking 'Yes" on Save to Communication History for send SMS workflow action causes texts to not send.

### ISSUE THREAD

**Issue by morganw93** [SparkDevNetwork/Rock#3877]
### Prerequisites
* [can't test on demo because demo won't send texts ] Put an X between the brackets on this line if you have done all of the following:

### Description

 Text to Workflow or any workflows that send SMS, now have a save to communication history setting. If you select yes on that, the texts never get sent. 

### Steps to Reproduce

1. Make a workflow with a send SMS action.
2. select 'yes' save to communication history.
3. Try the workflow.

**Expected behavior:**

Text would send and be added to communication history.

**Actual behavior:**

Texts never send.
### Versions

* **Rock Version:** v.9.1
* **Client Culture Setting:** en-us

**Comment by nairdo** [comment]
@morganw93  By any chance did your workflow SMS action also include an attachment? I recently found and fixed a similar bug regarding SMS that have an attachment with Communication History enabled (via https://github.com/SparkDevNetwork/Rock/commit/c2e1ba6b53f4b636e9006281c00b336a9425c934).

**Comment by nairdo** [comment]
We (Ethan) found the issue.  It happens when the phone number you are trying to text is _not_ in Rock.

**Comment by ethan-sparkdevnetwork** [comment]
The fix will allow the message to send but the a communication record for that recipient will not be created because there is no person for it. Rock v10 will have a feature for sending messages to numbers not associated with a person and saving the history among other things.

**Comment by morganw93** [comment]
I know I'm a little late to the game on this because I was out for the long weekend.

But just as a note, the messages did not have an attachment, they did have a message set in the text box and did have a recipient selected. 
I attached an example of one of the ones that stopped working when I turned on the save to communication history. 
![Screen Shot 2019-09-03 at 9 36 30 AM](https://user-images.githubusercontent.com/30188136/64182791-646a0d00-ce2e-11e9-9a55-a65b8c2fae9c.png)

**Comment by ethan-sparkdevnetwork** [comment]
Hello @morganw93 The fix will cover what you described. The problem was sending to a phone number that did not have a person associated with it in Rock. The fix will allow the message to still be sent, but a communication record will not be created because that requires a person.
