### ISSUE TITLE
Group Toolbox attendance grid doesn't handle custom schedules with specific dates well

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#3878]
### Description
If a group has a custom schedule with recurrence set using specific dates, the schedule column on the attendance tab in group toolbox shows HTML.

### Steps to Reproduce
1. Set up a group with a custom schedule that has recurrence set to specific dates. ![image](https://user-images.githubusercontent.com/12735965/64027074-9ebd6c80-cb05-11e9-8417-258717a34b03.png)
1. Log into Group Leader Toolbox
1. Go to the attendance tab
1. 

![image](https://user-images.githubusercontent.com/12735965/64027189-cf9da180-cb05-11e9-9408-62ad0186c44c.png)

**Expected behavior:**

A unordered list of the dates in the schedule

**Actual behavior:**

HTML displayed instead

### Versions
* **Rock Version:** 9.1 and 8.7
* **Client Culture Setting:** en-US

**Comment by briankalwat** [comment]
Confirmed on `11.0.2`.

![image](https://user-images.githubusercontent.com/2465823/67512707-68b0ea80-f667-11e9-9f80-4b6264f6a4b6.png)

**Comment by nairdo** [comment]
![image](https://user-images.githubusercontent.com/383807/67602264-1c2ee300-f72b-11e9-8042-de6fb2a8caff.png)

...although you'll need to deal with `nowrap` table cells for your theme/style if you want those odd date/times not to wrap like I'm showing in that screenshot.
