### ISSUE TITLE
Check-In Kiosk Saves New People Without FirstName Value

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#3879]
Submitted on behalf of [Sun Valley ](https://www.sunvalleycc.com/)

### Description
Adding a new family member through the check-in kiosk registration mode, creates a person record without a first name. Only Nick Name is saved to record.

### Steps to Reproduce
1. Configure Check-in Kiosk and set Registration Mode to "Yes"
1. Run check-in and add a new person to family... ![image](https://user-images.githubusercontent.com/548180/64077003-a2293300-cc80-11e9-8e6e-928865993058.png)

**Expected behavior:**

Record is saved with a value in the FirstName field.

**Actual behavior:**

Record is saved with a null FirstName value and first name is only stored to the NickName field.
![image](https://user-images.githubusercontent.com/548180/64077032-c9800000-cc80-11e9-9973-0c433a3e1aee.png)

![image](https://user-images.githubusercontent.com/548180/64077035-cf75e100-cc80-11e9-9d03-ac9a2c157ade.png)

### Versions
* **Rock Version:** Rock McKinley 9.1 (1.9.1.3)
* **Client Culture Setting:** en-US

**Comment by tp-code** [comment]
We are on v17.6 and still seeing this issue. Anyone with a nick name and no first name is prevented from doing things like completing a registration.

**Comment by chead4** [comment]
@tp-code We appreciate you bringing this to our attention. Please submit a new GitHub issue including the details below so the team can investigate.

When creating the issue, please clarify:

1. Whether the issue occurs in Classic Check-in, NextGen Check-in or both
2. Whether you're able to reproduce the issue on Pre-Alpha.

Also, Rock is all about community, and a big part of that is knowing who we're collaborating with. Would you mind updating your GitHub profile to include your name and organization? Putting faces to names helps foster a stronger, more connected community and makes collaboration a bit more personal.

**Comment by zackdutra** [comment]
We also experienced this on 17.6 but the fix seems to be mentioned here. https://github.com/SparkDevNetwork/Rock/issues/6464
