### ISSUE TITLE
Age Calculation error - Birthdates without years

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#3881]
### Description
When a user enters a birthdate without the year value (i.e. 4/21), the BirthYear field is set to null as expected but the Birthdate field is being calculated as (0001-04-21).  This causes an error when calculating the person's age because the dbo.ufnCrm_GetAge function accepts a date time causing the birthdate to be converted to a datetime but it will fail because the value is outside of the range of datetime.  This does continue to impact the Rock.Jobs.ProcessBIAnalytics job, because it uses the ufnCRM_GetAge function as part of a SQL Query.

A couple of solutions to this could include:

1. Updating the ufnCRM_GetAge function to accept a date value instead of a datetime.  If the date time conversion is required inside of the function, records with birthdates earlier than 1753 could be kicked out through a Try_Parse or Try_Convert function or maybe even an if statement.
1. Prevent a user entering a birthdate without a year.
1. Update the birthdate calculation logic to set the birthdate to null if the year is null

### Steps to Reproduce
1. Update Ted Decker's birthdate to 2/10 on the Rock Solid Church Demo site. (removing the year)
1. Run the following query using the SQL Command block (these are Ted's values from the Rock Solid Church Demo)  `SELECT     dbo.ufncrm_GetAge([birthdate]) FROM     [Person] WHERE      [GUID] = '8fedc6ee-8630-41ed-9fc5-c7157fd1eaa4'`
1. `Error SQL Error! The conversion of a date data type to a datetime data type resulted in an out-of-range value.` will be returned

**Expected behavior:**

If a person does not have a birthdate the age should be returned as null.  (See possible solutions above)

**Actual behavior:**

SQL error occurs.

### Versions
* **Rock Version:** 1.9.1.3
* **Client Culture Setting:** en-us

**Comment by nairdo** [comment]
Although the RockCleanup job would normally run and update those invalid [Birthdate] values (setting them to NULL when needed), I'll see why it's not doing that immediately when someone removes a birthyear from a person's record.

**Comment by chrisfunk** [comment]
@nairdo  do you know what the negative impacts of updating the `Person.CalculateBirthDate` function to return null instead of 0001 for people with a null BirthYear? So that we don't have to depend on an end of the day cleanup?

**Comment by chrisfunk** [comment]
Disregard this comment... I just tried it and it causes some issues on the Person Profile

> @nairdo do you know what the negative impacts of updating the `Person.CalculateBirthDate` function to return null instead of 0001 for people with a null BirthYear? So that we don't have to depend on an end of the day cleanup?

**Comment by JesseM-PC** [comment]
This also causes the Process BI Analytics to stop working properly. May be related to #3899. I just manually made the BirthDate null.

**Comment by chrisfunk** [comment]
@JesseM-PC, I do something similar, I have a job run 5 minutes before we refresh BI Analytics to clean it up.
