### ISSUE TITLE
Rock Cleanup job does not delete Interaction Sessions

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3885]
### Description
The Rock Cleanup job will delete any old Interactions (as configured by the interaction channel). However, it does not delete the Interaction Session data. I believe this is a bug as I can't see any reason the session data would be useful after the Interactions themselves have been deleted.

We discovered this as our InteractionSession table was around 14 million rows, while the Interaction table was only at 8 million.  After manually deleting all the sessions that were orphaned, that number dropped from 14 million to around 2 million. It also reduced our database size by a few GB.

Most people will probably not see as huge a benefit as we did, but it is still wasted space.

### Steps to Reproduce
1. Configure a web site interaction channel to expire data.
1. Wait for job to expire interactions.
1. Note that the sessions are left behind.

**Expected behavior:**

Job should scan for orphaned interaction sessions and delete them IF the channel is configured with a retention duration.

**Actual behavior:**

It does not and we get tons of orphaned session rows.

### Versions
* **Rock Version:** 9.1
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
Good catch. 7mill rows in our InteractionSession table here

**Comment by tom-powers** [comment]
I was just looking at the codebase from the Rock Cleanup Job yesterday.  There aren’t any cascading deletes on Interactions, so the code deletes from the Interaction table only.

**Comment by JimMichael** [comment]
Was this closed without fixing?

**Comment by cabal95** [comment]
@JimMichael It is fixed, I remember seeing the commit yesterday. I'll see if I can check which version it's in.

**Comment by cabal95** [comment]
At the moment it is in v11, not sure if it will make it's way to a v10 dot release. Looks like it was a pretty hefty change.

**Comment by nairdo** [comment]
This is fixed via https://github.com/sparkdevnetwork/rock/commit/34361f131fce13e747f5cec31866026f26bb36f0 and https://github.com/sparkdevnetwork/rock/commit/e113a01305f2483d9d3ed139f67a9dbb333df7a2
