### ISSUE TITLE
Rare ObjectContext error when editing existing Registration Instances

### ISSUE THREAD

**Issue by tcavaletto** [SparkDevNetwork/Rock#3888]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
On the Registration Instance Block, if the Payment Reminders linked page is set, editing an existing registration will still save it, but an error message (The ObjectContext instance has been disposed and can no longer be used for operations that require a connection) will be thrown and the page needs to be refreshed to see the saved changes.

After doing some research it's caused by this line: https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/RegistrationInstanceDetail.ascx.cs#L530. As far as I can tell it's because Rock is trying to access properties on the _instance_ variable, but the context used to fetch it has already been disposed of. One proposed ( And tested/verified) solution is to move that if check into the using statement.

I wasn't able to reproduce this on the Rock Demo site, but on another system I was able to replicate it multiple times, so I think it's partially caused by the environment. or just how the registration is set up.

### Steps to Reproduce
1. Create a registration
1. Make sure the Payment Reminder linked page is set
1. Edit the existing Registration
1. Hit 'Save'

**Expected behavior:**

The registration should save successfully and the block should change to view mode.

**Actual behavior:**

The registration saves successfully, but an error message appears at the top of the block and it remains in edit mode.

### Versions
* **Rock Version:** Rock McKinley 8.9 (1.8.9.1)
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in 9.3 in commit 3b0db8bbb4ed6ea38272b174e9a368ea8943dd06.
