### ISSUE TITLE
Content Channel Item Detail Block Setting Tag Values to Background Color

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#3889]
### Description
When editing a content channel item that has been previously tagged, upon saving, those tag relationships are changed to a new tag that is named the default background color of tags (I verified that the tagged item rows are changing to different Tag Ids - so the tags are not being renamed).

**We believe this bug was introduced with** [**https://github.com/NewSpring/Rock/commit/f90a05162fb6fbc8244e8892afc0bff90abdddda#diff-91d04989a1fafda2866acfd6343532e5 this commit** ]() **(Rock/Web/UI/Controls/TagList.cs). So either this needs to be fixed, or the Content Channel Item Detail block needs to be updated to account for these changes to the TagList UI control.**

![image](https://user-images.githubusercontent.com/2465823/64561827-99d49600-d319-11e9-86f1-647b6de01d0e.png)

When loading a content channel item that has been previously tagged, this is what the input value is being set to on page load:

![image](https://user-images.githubusercontent.com/2465823/64561884-b53fa100-d319-11e9-8ddb-a42f98949584.png)

And after saving without making changes, this is now what the tags values are:

![image](https://user-images.githubusercontent.com/2465823/64561913-c1c3f980-d319-11e9-859e-8c2899179666.png)

### Steps to Reproduce
1. Edit any content channel item
1. Tag content channel item with an existing organization tag
1. Click save
1. Edit that same content channel item
1. Click save
1. Edit that same content channel item

**Expected behavior:**

Tags that are linked to a content channel item should not change unless changed by the user.

**Actual behavior:**

Tags are being created for the default tag background color, and are being linked to that content channel item in place of the tags that had been previously added to it.

### Versions
* **Rock Version:** 1.10.0.6
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Commit message missed a character, so manually linking this to the commit that should eventually fix this: 3220ae4f3a2b07c53a4572eeab1ae24cfb6981de

**Comment by bjwiley2** [comment]
Fixed by https://github.com/SparkDevNetwork/Rock/commit/3220ae4f3a2b07c53a4572eeab1ae24cfb6981de
