### ISSUE TITLE
Mine Pass - inactive template

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#3891]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
With the MinePass plugin, there is no way to filter active vs inactive templates.  Once you make a template inactive, it will disappear and you can no longer access it.

### Steps to Reproduce
1. Go to Admin Tools
1. Click on Installed Plugins
1. Select Mine Pass Templates
1. Create a Template
1. Save the Template
1. Edit the Template, make it inactive
1. Watch it disappear

**Expected behavior:**

There would/should be a filter option to allow you to filter your templates.

**Actual behavior:**

There is no filter button to allow you to filter your templates to show inactive templates.

### Versions
* **Rock Version:** [Rock McKinley 9.0 (1.9.0.26)]
* **Client Culture Setting:** [en-US
![](https://user-images.githubusercontent.com/41912840/64578494-93601180-d34d-11e9-84cc-c6701ac243ab.png)
]

**Comment by jonedmiston** [comment]
@jcjones37 I'll put this on the next release of Mine Pass.
