### ISSUE TITLE
Cannot Add Transaction to Batch if 'Non-Cash' Currency Type has Been Deleted

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#3894]
Submitted on behalf of [Community Church of Riverside ](http://www.gccriverside.com/)

### Description
If the 'Non-Cash' currency type has been deleted, (even if then re-added), you cannot add any transactions to a batch. When trying to do so, you get an exception.

### Steps to Reproduce
1. Delete the 'Non-Cash' currency type. 
1. (optionally) add a new 'Non-Cash' currency type back
1. Create a new batch
1. Try to add a transaction to the batch

**Expected behavior:**

The transaction is added.

**Actual behavior:**

The following exception occurs:

![image](https://user-images.githubusercontent.com/548180/64826343-36df3b00-d575-11e9-9741-0b062d7f85a5.png)

### Versions
* **Rock Version:** Rock McKinley 9.2 (1.9.2.3)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1140133512283497">image.png</a>

**Comment by cabal95** [comment]
Somebody else ran into this. Popping this SQL here in case anybody else needs it before this gets fixed in core. This restores the Non-Cash type using the same Guid so it can be found by the system.

```sql
DECLARE @DefinedTypeId [int] = (SELECT [Id] FROM [DefinedType] WHERE [Guid] = '1D1304DE-E83A-44AF-B11D-0C66DD600B81')

INSERT INTO [DefinedValue] ([IsSystem], [DefinedTypeId], [Order], [Value], [Description], [Guid], [IsActive])
VALUES (0, @DefinedTypeId, 99, 'Non-Cash', 'Used to track non-cash transactions', '7950FF66-80EE-E8AB-4A77-4A13EDEB7513', 1)
```

**Comment by cabal95** [comment]
I've talked to 3 other churches today that have run into this same problem, so it looks like this is a pretty wide-spread issue.

**Comment by JimMichael** [comment]
Can I get clarification if this fix works without re-adding the original Non-Cash currency type per the SQL Daniel provided? Or are both needed?

**Comment by nairdo** [comment]
@JimMichael  You'll want, at a minimum, the correct Guid on that non-cash currency type.  The block fix is primarily so it will not choke if that particular Guid is not there (but other things in Rock will also require that particular currency type so ultimately you'll want/get both fixes).

**Comment by JimMichael** [comment]
Ok, thanks... so do I just update my existing Non-Cash defined value with a new GUID? Wouldn't that break any existing relationships that use *our* GUID? This seems like a can-o-worms!
![image](https://user-images.githubusercontent.com/3903408/65260381-e82d2600-dacb-11e9-991e-757727f3ba92.png)

**Comment by cabal95** [comment]
@JimMichael It would break any Attribute type references.  Meaning, if you have a Workflow Attribute where somebody has picked Non-Cash then it would show up as not-selected after you change the Guid.  Any transactions that link to the Non-Cash hare doing so via the Defined Value Id, which you aren't changing, so that should be fine.

You also might want to mark that Non-Cash item as IsSystem so it doesn't get accidently deleted again in the future.

**Comment by JimMichael** [comment]
Thanks. We definitely (well, 99.9% sure) don't have any attribute refs (not in workflows, anyway) and as far as I know we just use it within the Transaction UI. So, I _think_ this SQL would update my current Guid (above image) to the correct one...?

UPDATE DefinedValue
SET Guid = '7950FF66-80EE-E8AB-4A77-4A13EDEB7513'
WHERE Id = 765

**Comment by cabal95** [comment]
@JimMichael Yep, that should do it (again in your case, other people will need to replace the `765` with their own Id number)

**Comment by ethan-sparkdevnetwork** [comment]
9.3 will have a migration in it which will do the following:

1. Find the Non-Cash DefinedValue that came with Rock and mark it as a system DefinedValue
2. If that DefinedValue is missing based on GUID
2a. Look for other DefinedValues for DefinedType Currency Type with values "Non-Cash", "Non Cash", or "NonCash" (case insensitive) and append " (Non-Core)" to the value.
2b. Insert a new DefinedValue with the expected GUID.

Here is the SQL:
`-- Known GUID FINANCIAL_CURRENCY_TYPE =  "1D1304DE-E83A-44AF-B11D-0C66DD600B81";
-- Known CURRENCY_TYPE_NONCASH = "7950FF66-80EE-E8AB-4A77-4A13EDEB7513";

-- First get the currency type defined type ID
DECLARE @currencyTypeDefinedTypeId INT = (SELECT [Id] FROM [DefinedType] WHERE [Guid] = '1D1304DE-E83A-44AF-B11D-0C66DD600B81')

-- Check if the Non-Cash DefinedValue exists
IF EXISTS (SELECT * FROM [DefinedValue] WHERE [Guid] = '7950FF66-80EE-E8AB-4A77-4A13EDEB7513')
BEGIN
	-- Make sure this is flagged as a system DefinedValue so it cannot be deleted using the UI
	UPDATE [DefinedValue] SET IsSystem = 1 WHERE [Guid] = '7950FF66-80EE-E8AB-4A77-4A13EDEB7513'
END
ELSE BEGIN
	-- First find non-core Non-Cash currency types and update the value
	UPDATE [DefinedValue]
	SET [Value] = [Value] + ' (Non-Core)'
	WHERE [DefinedTypeId] = @currencyTypeDefinedTypeId
		AND [Value] IN ('Non-Cash', 'Non Cash', 'NonCash')
		AND [Value] NOT LIKE '%(Non-Core)'

	-- Insert the core version of the Non-Cash currency type
	INSERT INTO [DefinedValue] ([IsSystem], [DefinedTypeId], [Order], [Value], [Description], [Guid], [IsActive])
	VALUES(1, @currencyTypeDefinedTypeId, 99, 'Non-Cash', 'Used to track non-cash transactions.', '7950FF66-80EE-E8AB-4A77-4A13EDEB7513', 1)
END`

**Comment by JimMichael** [comment]
Thanks all, really appreciate the help. I tested the updated guid on a copy of prod and the error no longer occurs. As best I can tell, when we migrated from Arena we ended up with two Non-Cash currency types, and since the Arena-migrated one had all the data associated with it, we just deleted the Rock one (or the partner did, no idea). MAN that (deleting of core attributes) has bit us in the rear like three times now :-/

Now I'm wondering if we should go ahead with the simple GUID update (and possibly have issues from doing that), or wait and let 9.3 do its thing and we end up with two non-cash values...

**Comment by nairdo** [comment]
Jim, your existing DefinedValue's GUID could be referenced in places like an Attribute's Value or worse, in a setting somewhere.  I would not advise you to update your existing non-cash guid to the new one.   Instead, I'd put the core "non-cash" one in and then rename the other one "non-cash (non-core)" and then possibly just inactivate it as you see fit.

**Comment by JimMichael** [comment]
Great, thanks for the advice! I trust your judgement and will proceed accordingly!

**Comment by nairdo** [comment]
@azturner , @JimMichael Here's the final plan.  To avoid additional confusion, v9.3 will rename **_our_** original "Non-Cash" currency type (the one with GUID `7950FF66-80EE-E8AB-4A77-4A13EDEB7513`) to "Non-Cash Asset" and make it IsSystem = true, if it exists. 

If that Guid _does not_ exist, we will add it as IsSystem with the name shown above.

You're welcome to run this now if you'd like on any version of Rock **running v8 or greater**.

```Sql
-- First get the currency type defined type ID
DECLARE @currencyTypeDefinedTypeId INT = (SELECT [Id] FROM [DefinedType] WHERE [Guid] = '1D1304DE-E83A-44AF-B11D-0C66DD600B81')

-- Check if the Non-Cash DefinedValue exists
IF EXISTS (SELECT * FROM [DefinedValue] WHERE [Guid] = '7950FF66-80EE-E8AB-4A77-4A13EDEB7513')
BEGIN
 -- Make sure this is flagged as a system DefinedValue so it cannot be deleted using the UI
 UPDATE [DefinedValue] SET [IsSystem] = 1, [IsActive] = 1, [Value] = 'Non-Cash Asset' WHERE [Guid] = '7950FF66-80EE-E8AB-4A77-4A13EDEB7513'
END
ELSE 
BEGIN
 -- Insert the core version of the Non-Cash Asset currency type
 INSERT INTO [DefinedValue] ([IsSystem], [DefinedTypeId], [Order], [Value], [Description], [Guid], [IsActive])
 VALUES(1, @currencyTypeDefinedTypeId, 99, 'Non-Cash Asset', 'Used to track non-cash transactions.', '7950FF66-80EE-E8AB-4A77-4A13EDEB7513', 1)
END
```

**Comment by tommyprater** [comment]
@nairdo So if we are having trouble adding manual transactions to batches selecting any currency type is the fix to run the SQL script you mentioned?
