### ISSUE TITLE
Social Media Profiles not Resolving properly in URL

### ISSUE THREAD

**Issue by jsw-austin** [SparkDevNetwork/Rock#3896]
Let me start by admitting I'm new.  Been on the job only a week.  However, in the spirit of the Rock Community, I've been following Rocket Chat and trying to find an opportunity to help.  Micah Odor reported an issue that I thought I'd learned enough to say something intelligent about.  He and I and Thomas Stephens agreed it's a bug, and Micah asked me to write it up so here I go.

### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
  * Reproduced on rocksolidchurchdemo.com

### Description
When you put in a twitter or instagram link in the social media attributes on a person and then click the instagram or twitter link under a person, the url doesn't properly resolve.

I put in "[https://www.instagram.com/the_jeff_ward/](https://www.instagram.com/the_jeff_ward/)" under Ted Decker and clicking on the instagram link takes me to: [https://www.instagram.com/https://www.instagram.com/the_jeff_ward/](https://www.instagram.com/https://www.instagram.com/the_jeff_ward/)

### Steps to Reproduce
1. Go to 'Person:Extended Attributes"
1. Click on Edit next to Social Media
1. Put in the url for the social media account for twitter or instagram (**the whole url, not just the handle.** If I put in "the_jeff_ward" (just the handle) everything resolves properly.  If I put in "[https://www.instagram.com/the_jeff_ward/](https://www.instagram.com/the_jeff_ward/)" it displays "the_jeff_ward", but navigates to [https://www.instagram.com/https://www.instagram.com/the_jeff_ward/](https://www.instagram.com/https://www.instagram.com/the_jeff_ward/))

**Expected behavior:**
I'd expect that it would navigate to [https://www.instagram.com/the_jeff_ward/](https://www.instagram.com/the_jeff_ward/)

**Actual behavior:**

Navigates to [https://www.instagram.com/https://www.instagram.com/the_jeff_ward/](https://www.instagram.com/https://www.instagram.com/the_jeff_ward/)

### Versions
* **Rock Version:** 9.1
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Hi @jsw-austin You're correct that you are only supposed to put in the account name/handle -- not the whole URL to the platform.

**Comment by jsw-austin** [comment]
If you click on the info it says to put in the url

**Comment by cabal95** [comment]
Hi @jsw-austin, Can you post a screenshot of where you are seeing that it asks for the whole URL? When I look it doesn't, but I'm wondering if you are seeing that somewhere else?

But as Nick says, it is supposed to just be the handle. So it sounds like maybe it's a documentation piece that is out of date.  A screenshot would help track that down, thanks!

<img width="423" alt="Screen Shot 2019-09-13 at 5 26 29 PM" src="https://user-images.githubusercontent.com/1119863/64901212-a7f12200-d64b-11e9-8761-b0e62f415daa.png">

**Comment by jsw-austin** [comment]
you're correct.  I misspoke.  It doesn't ask for the url, just the link to the person's instagram page.  I'd take that to mean the url, but maybe it's just my misunderstanding.  It is interesting that if you put the whole url, that it displays just the handle, but still links to the concatenated base url + the pasted url even though only the handle displays.

**Comment by nairdo** [comment]
After looking at this closer I'm going to say something is not quite right with this field.  We're going to look at this.

**Comment by luke-infoministry** [comment]
Also applies to Twitter and Facebook Links

**Comment by CompassSkelly** [comment]
This has gotten better with v9.x, but still not perfect especially for users not well verse in how URLs work.

These are the results from testing on pre alpha and demo site: 
Facebook: When coping the URL straight from the Facebook profile(https://www.facebook.com/TheRockRMS/) and pasting that right into the Rock facebook handle this result is given: http://www.facebook.com/https://www.facebook.com/TheRockRMS/

Twitter: Similar results for the same steps with Twitter.   The only difference being that Twitter's URLs do not have the / at the end of the URL: http://www.twitter.com/https://twitter.com/therockrms

Instagram: Similar results using Jeff Wards Instagram URL provided: http://www.instagram.com/https://www.instagram.com/the_jeff_ward/

Just for good measure testing on v8.9 results in only applying the last character of the URL entered:

Facebook /
Twitter s
Instagram /

**Comment by jsw-austin** [comment]
At a minimum the help text should be clarified.  It currently says, link to person's twitter page, if it wants the handle only, it should say that.  If it wants the url, it should say that.
