### ISSUE TITLE
Registration Instance excel exports produce HTML columns

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3898]
# Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Similar to #3621, we found a few more places where doing an Excel export produces HTML.

### Registrations Tab

On the `Registrations` tab, the `Total Cost` and `Balance Due` exported columns contain the HTML for the labels instead of just the dollar values.

![image](https://user-images.githubusercontent.com/1119863/64980036-e5cd9080-d86d-11e9-9c82-3ca0316d7009.png)

### Payments Tab

On the `Payments` tab, the `Registrar` exported column contains the HTML for a hyperlink to the person.

![image](https://user-images.githubusercontent.com/1119863/64980294-642a3280-d86e-11e9-8449-cbca86167c4b.png)

**Expected behavior:**

A user readable and functional Excel export.

**Actual behavior:**

Not very readable and difficult to work with in Excel (for example, sorting).

### Versions

* **Rock Version:** 9.1
* **Client Culture Setting:** en-US

**Comment by craigmash** [comment]
I can confirm this. Ran into it yesterday.

**Comment by shauncummings** [comment]
Fixed in https://github.com/sparkdevnetwork/rock/commit/54fc6a151578e5da1b72e928e2e510191a18a43a

**Comment by jrockman13** [comment]
This issue also manifests on the export to Excel from connection requests list view.
