### ISSUE TITLE
Use Current Value form field option has confusing behavior for single registrant event registrations

### ISSUE THREAD

**Issue by sichiriu** [SparkDevNetwork/Rock#3900]
### Description
For single registrant event registrations (Allow Multiple Registrants is FALSE), the Registrants In Same Family option must be set to Yes in order for form fields with the Use Current Value option to be filled with the current person's information. This has caused confusion for several people on Rocket.Chat recently.

### Steps to Reproduce
1. Create a single registrant registration with Allow Multiple Registrants unchecked and Registrants In Same Family set to No.
1. Add form fields with the Use Current Value option set.
1. Test the event registration.
1. Observe blank form fields.

**Expected behavior:**

The expected behavior is unclear. ¯\\\_(ツ)\_/¯ 

I can see the possibility of needing a single registrant registration where the Registered By person is different than the registrant. In this case, it wouldn't make sense to pre-fill those fields with the current person's information. If this is so, I'd suggest updating the manuals and/or tooltips to clarify the conditions under which the Use Current Value form field option will work.

On the other hand, if that use case shouldn't be covered, the fields should be pre-filled and the Registrants In Same Family option should be hidden when Allow Multiple Registrants is FALSE.

**Actual behavior:**

The form fields are not pre-filled.

### Versions
* **Rock Version:** Rock McKinley 9.2 (1.9.2.3)
* **Client Culture Setting:** en-US

**Comment by TheCoreyHall** [comment]
I have run into this issue today on a client, was this bug never addressed?

**Comment by kenmulford** [comment]
Same issue here on version 12.1. OP's steps to reproduce are consistent with my own. I set "Registrants in Same Family" to "Yes" for the workaround. Would be lovely for this to be fixed!
