### ISSUE TITLE
Error Exporting From Fundraising Donation List block

### ISSUE THREAD

**Issue by sanford-rock** [SparkDevNetwork/Rock#3901]
### Description
Updated to v9.0 and have a problem with the Fundraising Donation List block and exporting to Excel...it does not pass the values for the Donor and Participant fields into the Excel file...it creates the column in Excel but with no values

![image](https://user-images.githubusercontent.com/41087137/65058768-cbb1b200-d942-11e9-9f9e-c05f9ead1a61.png)

**Expected behavior:**

One of the basic function of a the Group View is being able to export group member information to Excel. In the Fundraising Opportunity group type group that we use for our Mission Trips, in the past we have been able to export group member info from the Fundraising Donation List block.

**Actual behavior:**

HELP!! Just updated to v9.0 and have a problem with the Fundraising Donation List block and exporting to Excel...it does not pass the values for the Donor and Participant fields into the Excel file...it creates the column in Excel but with no values...I replicated it in the Demo system with Ted Decker...group FR TEST....

### Versions
* **Rock Version:** [9.0]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by cabal95** [comment]
Confirmed. Those two columns contain HTML links to the person records when viewed on the Grid, so I wonder if the entirety of the HTML tags is being stripped on export rather than just the non-text part.

**Comment by sanford-rock** [comment]
Also noticed in a Group Member List block I have a group that has a column of registration links in which that column does not export to Excel...

![image](https://user-images.githubusercontent.com/41087137/65065668-dd01bb00-d950-11e9-8027-c3312a6bd5eb.png)
![image](https://user-images.githubusercontent.com/41087137/65065746-06bae200-d951-11e9-9fa6-4fe783c7cc69.png)

**Comment by sanford-rock** [comment]
sorry hit the wrong button...

**Comment by shauncummings** [comment]
> Also noticed in a Group Member List block I have a group that has a column of registration links in which that column does not export to Excel...

The definition of that field explicitly excludes it from the Excel export:

`<Rock:RockLiteralField ID="lRegistration" HeaderText="Registration" OnRowSelectedEnabled="false" ExcelExportBehavior="NeverInclude" />`

**Comment by shauncummings** [comment]
Fixed in https://github.com/sparkdevnetwork/rock/commit/70992da4ac6175b6c96860104242bbe2c415b8fd
