### ISSUE TITLE
Transaction Matching Block Doesn't Display Fund Accounts

### ISSUE THREAD

**Issue by sanford-rock** [SparkDevNetwork/Rock#3902]
### Description
The Transaction Matching Block does not display the drop down list of fund accounts when viewed at 100% zoom level with multiple addresses. You have to reduce the zoom level to at least 90% to begin to see the fund accounts. The addresses that are displayed should be in a scrolling nav container to allow the fund accounts container to display by default

**Expected behavior:**

I expect that all required controls on the screen page be visible at 100% zoom level.

**Actual behavior:**

The Transaction Matching Block does not display the drop down list of fund accounts when viewed at 100% zoom level with multiple addresses. You have to reduce the zoom level to at least 90% to begin to see the fund accounts. The addresses that are displayed should be in a scrolling nav container to allow the fund accounts container to display by default. There's really no need to see all of the current/previous addresses. My finance people were trying to figure out how to do the Account Split when they couldn't see the accounts. Once you know to reduce your zoom level it's a do-able workaround but an unnecessary one.

![image](https://user-images.githubusercontent.com/41087137/65069255-4c2edd80-d958-11e9-9267-877acc2ae4ae.png)

![image](https://user-images.githubusercontent.com/41087137/65069265-5355eb80-d958-11e9-82fa-55de61fe08c3.png)

### Versions
* **Rock Version:** [9.0]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by nairdo** [comment]
@sanford-rock I might be missing something as I'm trying to reproduce this in Rock v9.1/9.2 (on the demo server here: https://rock.rocksolidchurchdemo.com/page/311?BatchId=276) but I have not been able to do so with my browser (Chrome and Edge) set at 100%.

It's a little hard to see your full browser window with that current screenshot... Can you include a full window screenshot?  Also, what browser are you using?  Lastly, would you be willing to try reproducing the issue on the demo site?

![image](https://user-images.githubusercontent.com/383807/65081766-3ff75000-d959-11e9-87d3-6b229aee3f62.png)

**Comment by cabal95** [comment]
I also tried sizing my window every which way I could imagine and couldn't get the UI to layout like @sanford-rock has in his screenshots. But I did notice that when I shrank the vertical height of the browser window that a second scrollbar did appear inside the panel. So maybe something changed in 9.1 in regards to the layout? Or possibly some custom CSS on his site is interfering with that inner scrollbar from appearing if it should also be in 9.0.

![image](https://user-images.githubusercontent.com/1119863/65082438-d37d5080-d95a-11e9-954c-d2aacb190c8d.png)

**Comment by sanford-rock** [comment]
Hey Nick we use Firefox for browser...i will create similar data conditions in demo tomorrow and we can check it out...



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by sanford-rock** [comment]
Hey Nick I updated the GitHub issue with some new screen shots and  set it up in demo also *  Home<https://rock.rocksolidchurchdemo.com/Admin>
*  Batches<https://rock.rocksolidchurchdemo.com/page/162>
*  SampleData1539475200000<https://rock.rocksolidchurchdemo.com/page/163?batchId=182>
*  Transaction Matching

**Comment by cabal95** [comment]
@sanford-rock I don't see your new screenshots, so it might not have saved your edits.  I followed the link to the sample data and, as pictured in my reply above, I get a second scrollbar that lets me get to the content that (from your description) you are not able to get to.  I tested this on both Firefox and Safari and both worked correctly.

If you could try adding a screenshot of your full browser window again, showing the issue, and add it as a comment instead of trying to edit the original issue description that might help.

**Comment by sanford-rock** [comment]
lets see if this comes through ok...

![image](https://user-images.githubusercontent.com/41087137/65168198-03d3f600-da12-11e9-96cd-755d35099bfd.png)

**Comment by sanford-rock** [comment]
My fault Daniel, there should be a new screen shot now...

**Comment by sanford-rock** [comment]
Hey @nairdo your v9.1 Transaction Matching page does not match my v9.0 page specifically where the address info is being displayed...I would recreate in the Demo system but I don't know how to input an unmatched transaction into the system...

**Comment by ethan-sparkdevnetwork** [comment]
Tested in v16.1 and the accounts are show correctly on the Transaction Matching block.

**Comment by ethan-sparkdevnetwork** [comment]
@sanford-rock Let us know if this is still an issue for you.
