### ISSUE TITLE
Friendly schedule text incomplete for complex schedules in v9

### ISSUE THREAD

**Issue by sichiriu** [SparkDevNetwork/Rock#3906]
### Prerequisites
* [ X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
The friendly schedule text for complex schedules in v9 is incomplete. For schedules like 2nd & 4th Wednesdays at 7pm, the friendly schedule text currently reads "The Second Wednesday of every month at 7:00 PM"

### Steps to Reproduce
1. Add a complex schedule like 1st & 3rd Saturdays to a group
1. View the friendly schedule text

**Expected behavior:**

I'd expect the text to read something like, "The Second and Fourth Wednesdays of every month at 7:00 PM". Even better (for me, at least) would be "The 2nd and 4th Wednesdays of every month at 7:00 PM".

**Actual behavior:**

Only the first occurrence of the schedule within the month is included in the text.

### Versions
* **Rock Version:** Rock McKinley 9.2 (1.9.2.3)
* **Client Culture Setting:** en-US

**Comment by briankalwat** [comment]
Confirmed in `11.0.2`.

![image](https://user-images.githubusercontent.com/2465823/67511235-6bf6a700-f664-11e9-9141-070d4c32bcdf.png)

"The First Saturday of every month at 12:00 AM"
