### ISSUE TITLE
Social Security Number Field Validation Passes Even When Not Full SSN

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#3908]
### Description
![5QbgkDf7ck](https://user-images.githubusercontent.com/19762670/65256950-03953280-dac6-11e9-8f9c-fdf18d10772e.gif)

Entering an invalid SSN like 1-1-1 is possible.  Also, password managers can cram a users password into the first SSN boxes, and those alpha-based parts still pass form validation.

Also, along this line, I found an issue where putting a space in Street1, and City on an Address field makes it pass form validation too.  Would you like a second issue for this?

### Steps to Reproduce
1. Create Workflow with SSN attribute, and a Form that requires that attribute be filled.
1. Launch the Workflow.
1. In the SSN boxes, put a 1 character in each box
1. Hit submit.

**Expected behavior:**

I expect that the form validation would prevent anything not matching a `\d\d\d-\d\d-\d\d\d\d` regex (which, is how I've worked around this issue.  extra form validation built into the Workflow).

**Actual behavior:**

Having any digit, alpha character, or symbol in each of the SSN boxes is accepted by Rock without a fight.

### Versions
* **Rock Version:** our server 9.0, replicated on Demo site 9.1
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
This appears to be a possible regression of #3037.

**Comment by shauncummings** [comment]
Fixed in https://github.com/SparkDevNetwork/Rock/commit/f75c76b985f671fd3dfb710417f81ac6455f8c31
