### ISSUE TITLE
Family Pre-Registration cancel does nothing

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#3909]
### Description
The cancel button on the Family Pre-Registration block does nothing

### Steps to Reproduce
1. Go to Family Pre-Registration
1. Start filling out the form
1. Click cancel

**Expected behavior:**

The form to be cleared and children removed

**Actual behavior:**

Any fields you have completed remain filled out and the children are still there

### Versions
* **Rock Version:** [8.7 - 9.1]
* **Client Culture Setting:** [en-US]

**Comment by cabal95** [comment]
Confirmed. There is not even an event handler installed on the `lbCancel` button in the code. Small oversight :grin:
