### ISSUE TITLE
Unable to set activity attributes in non-persisted workflow

### ISSUE THREAD

**Issue by MichaelAllen** [SparkDevNetwork/Rock#3912]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If I try to set the value of an activity attribute before persisting the workflow, it silently fails. The workflow log records that it was successfully set, but the attribute will still be blank.

If I add a `Persist Workflow` action in the workflow before setting any activity attributes, everything works as expected. "Automatically Persist" also causes everything to work as expected.

I have been able to reproduce this on v9.1, v9.2, and v10 prealpha. I am unsure if the issue is new to v9, or existed in a previous version as well. 

### Steps to Reproduce

1. Create a new workflow with "Automatically Persist" turned off, and action level logging
2. Add a workflow attribute and an activity attribute
3. Add two `Attribute Set Value` actions; One for each of the attributes
4. Add a`Persist Workflow` action to the end so we can see the values in the log
5. Run the workflow and inspect the results in the log

**Expected behavior:**

Both the workflow and the activity attributes will contain the values I set them to.

**Actual behavior:**

The *workflow* attribute is set as expected, but the *activity* attribute is blank.

### Versions

* **Rock Version:** 1.9.2.3 (mine), 1.9.1.3 (demo), 1.10.0.7 (prealpha)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@MichaelAllen  I thought I was able to reproduce this issue, until I discovered the Activity's "Action" attribute value _**was**_ saved and showing under the `Activities` tab as seen here:

![image](https://user-images.githubusercontent.com/383807/65342470-af528700-db87-11e9-8664-0c5613580338.png)

Attached is the zipped JSON of the exported Workflow I set up to recreate your scenario.  Can you show me what I did wrong to reproduce?

[#3912_201909200857.zip](https://github.com/SparkDevNetwork/Rock/files/3636849/3912_201909200857.zip)

**Comment by MichaelAllen** [comment]
When importing your workflow I see the same thing you did, the attribute is saving correctly. 

The difference from when I was testing is that I had a `Form` action  before the persist so I could quickly see the values of the attributes, and that was where I was first seeing the missing values. Then, when I clicked through the form, I was actually overwriting them to blank myself... 🤦‍♂️

It seems the real issue is with the `Workflow Entry` block not pulling in un-persisted activity attributes, and not related to Rock actually saving them.

I will close this issue as user error, and open a new one specifically for the `Workflow Entry` block.
