### ISSUE TITLE
Event Registration payment in 9.2 using NMI

### ISSUE THREAD

**Issue by eddieholeman** [SparkDevNetwork/Rock#3922]
### Description
_no description given_

### Steps to Reproduce
1. Go to a registration and click on the Payments tab.
1. Click Process New Payment, enter a payment amount and click Next.

**Expected behavior:**

Expect to be offered a payment information screen on click next. 

**Actual behavior:**

I am returned to the Payments tab without a payment information entry option.

See the following for a screenshot version of this issue: https://docs.google.com/document/d/1vshu4kNNVNfeVJZR9Gx4-cJQLd5-GpxrKKsVswP2tGQ/edit?usp=sharing

Note that this works fine in 9.2 in demo site, but I am using the NMI gateway on my site instead of Test gateway.

### Versions
* **Rock Version:** Rock McKinley 9.2 (1.9.2.5)
* **Client Culture Setting:**
* **Database Version:** Microsoft SQL Azure (RTM) - 12.0.2000.8 Sep 9 2019 09:35:03 Copyright (C) 2019 Microsoft Corporation 
* **Allow Snapshot Isolation:** Yes 
* **Is Read Committed Snapshot On**: Yes

**Comment by eddieholeman** [comment]
@ethan-sparkdevnetwork just clarifying. This request is closed. Is this because you cannot replicate it or you have already fixed it? If so, in what release will it be fixed?

**Comment by JimMichael** [comment]
@eddieholeman If you look at the last line from Ethan you can see he closed it in "d7666d", which is the commit the fix is in... it's a link that takes you to the code. That said, there's no tag (yet) to tell us what release it's in but it will have to be 9.3 or greater.

**Comment by eddieholeman** [comment]
@JimMichael thanks so much. I realize that I am weak in this area so thanks for pointing it out to me.
