### ISSUE TITLE
DISC Profile attribute not set to a defined type.

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3924]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

DISC Profile appears in the Data View filters, but when selected it doesn't display options to filter on. 

The DISC Profile attribute uses a Defined Type and Value. When I looked at the attribute settings, for some reason it was set to Ability Level (the Defined Type used for Check-in). It looks like the DISC Profile attribute is a new attribute in v9 (the old attribute was Personality Type and was a text field). I'm wondering if the new attribute was not set to a Defined Type in the update, as a result it is selecting Ability Level because it is the first item in the Defined Type list? Setting the Attribute to the Defined Type 'DISC Results' did correct this issue. 

### Steps to Reproduce

1. Go to Data Views and create a new Data View
2. Set it to Person
3. Scroll through the Attribute Filters and select DISC Profile
4. It will say 'DISC Profile is' and then no drop down or options to filter on.
5. Go to Settings > Person Attributes and look at the DISC Profile attribute. It will select the first Defined Type in the list.

**Expected behavior:**

The expected behavior is for the attribute to be connected to the DISC Results Defined Type.

**Actual behavior:**

The DISC Profile attribute isn't connected to a Defined Type and needs to be connected to the Disc Results Defined Type.

### Versions

* **Rock Version:** v9.1 (Demo site) and v9.2
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
This will make it into the 9.3 beta build.
