### ISSUE TITLE
New Document model has incomplete EF configuration

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3925]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The new `Document` model does not follow the same configuration pattern as every other model.

1. Column `BinaryFileId` is declared in the SQL but not in the CLR.
2. `DocumentConfiguration` class is using an unusual notation instead of standard notation.

See: https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/Document.cs#L248

If this is intended behavior, it might be worth adding a comment to the code explaining why `BinaryFileId` is not included.

### Steps to Reproduce

n/a

**Expected behavior:**

Model should include `BinaryFileId` and use standard configuration notation.

**Actual behavior:**

It does not.

### Versions

* **Rock Version:** v10 (I think that is when it is slated for)
* **Client Culture Setting:** en-US

**Comment by bjwiley2** [comment]
The reason that the model is the coded that way is because it is a 1:1 relationship between BinaryFile and Document.  A limitation with EF is that a foreign key (BinaryFileId) cannot be added to the model in this scenario.  See https://stackoverflow.com/a/41847251.  I agree that documenting this in a comment will be helpful.  Thank you @cabal95!

**Comment by cabal95** [comment]
Got it. It seemed like the same setup as BinaryFileData so seemed like it should work but I guess that is technically a slightly different scenario.

Thanks for the link, it also explained why it worked fine when I used the standard notation in the EF Core build.
