### ISSUE TITLE
Bulk Update Progress Bar

### ISSUE THREAD

**Issue by TheDunagans** [SparkDevNetwork/Rock#3927]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Bulk update progress bar isn't functioning as expected.

### Steps to Reproduce
1. Go to any people group.
1. Click on a group and choose the bulk update van.
1. Try to bulk update the people.
1. See progress bar remain unchanged.

**Expected behavior:**

When bulk updating people in a group, upon selecting the bulk update action and clicking next, progress bar displays progress.

**Actual behavior:**

When bulk updating people in a group, upon selecting the bulk update action and clicking next, progress bar remains idle.

### Versions
Rock Version: Rock McKinley 10.0 (1.10.0.6)
Client Culture Setting: en-US

**Comment by nairdo** [comment]
Reported as resolved in the #bugapalooza channel.

```
chris.dunagan 6:41 AM
https://github.com/SparkDevNetwork/Rock/issues/3927 is not a bug and works as expected now.
```
