### ISSUE TITLE
Connection Request Badges Gray Out

### ISSUE THREAD

**Issue by tommyprater** [SparkDevNetwork/Rock#3932]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce
1. Go to 'Connection Request'
1. Click on 'add activity or edit the request'
1. Scroll down to 'badges that are shown gray out'
1. See error 'badges gray out until page is reloaded'

**Expected behavior:**

**Actual behavior:**

When displaying badges on Connection Requests if you manually add an activity to it or edit the request and save the badges gray out, you have to reload the page for them to show properly again. 

### Versions
* **Rock Version:** 9.2 but this happened on 8.8 as well.
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by MichaelAllen** [comment]
I am seeing the same thing on v9.2. It appears to happen after any postback, not just editing.

Additionally, if you hover over a badge thats tooltip should say `Michael last attended...` it shows as ` last attended...`. It seems like it is loosing context of who the badge is for.

**Comment by cwomack** [comment]
@tommyprater and @MichaelAllen, this bug has been confirmed in v9.2 (possibly earlier) through v10.2 and received a fix in v10.3 with this commit https://github.com/SparkDevNetwork/Rock/commit/13a21d510dbdf487d1f7a12bb11e0d349d212c37.  

It looks like any version of Rock running v10.3+ should have this fix, but if someone finds otherwise then feel free to comment back.
