### ISSUE TITLE
Is Archived and Archived DateTime Group Member filter does not display results.

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3933]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When creating a Group Member data view to display group members who have been archived, when 'IsArchived equal to Yes' or 'Archived DateTime in the last 12 months' does not properly display the results. It leads you to think no one has been archived but when searching the Database there have been archived group members 

It sounds the same as this issue: #3615 but applied to group members instead of groups. Not certain if it was meant to be hidden as well or if these filters are suppose to be accessible.

### Steps to Reproduce

1. Create a new Data View. 
2. Set it to Group Member
3. Set a filter to Is Archived or Archived DateTime
4. When set IsArchived to No you will get results but when set to Yes you wont.

**Expected behavior:**

Properly display archived group members by use of IsArchived and/or Archived DateTime

**Actual behavior:**

Does not display archived results.

### Versions

* **Rock Version:** 9.2, 9.1 (Demo)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Decorate the three properties in question with [HideFromReporting]
