### ISSUE TITLE
Person picker in group attendance detail block

### ISSUE THREAD

**Issue by jrockman13** [SparkDevNetwork/Rock#3936]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
When adding people to an attendance instance using the attendance detail block, the person picker does not erase after each lookup.

### Steps to Reproduce
1. Go to rock demo site -> serving team
1. Open attendance and create a new attendance instance
1. Edit the block to allow adding people to the attendance instance from the block
1. Add Ted Decker using add person people picker
1. Try adding another person and notice that the text you tied in to find Ted is still present

![](https://user-images.githubusercontent.com/22159658/66271108-eed3d100-e81f-11e9-9119-a149e8bb2d59.png)

**Expected behavior:**

Person picker search bar text will reset each time

**Actual behavior:**

It does not clear out

### Versions
* **Rock Version:** [9.1 and 9.2]
* **Client Culture Setting:** [en-us]

**Comment by jrockman13** [comment]
And also happens in the simple editor communication tool person picker

**Comment by nairdo** [comment]
Hi @jrockman13 It looks like this bug was also fixed when issue #4216 was corrected via (783f6b18) for Rock v10.3.
