### ISSUE TITLE
Single person registrations show blank page

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3937]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
After updating to 9.2, some our single-person registrations are showing a blank page instead of the registration form. I assume this is connected to the fix for #3805?

### Steps to Reproduce
1. Create a new Registration Template
1. Uncheck "Allow Multiple Registrants"
1. Create a new Registration
1. Start typing into the "Registration Instructions" box, and then delete your text it so it's empty
1. Go to fill out the registration

**Expected behavior:**

The page shows the form

![firefox!UNITO-UNDERSCORE!2019-10-07!UNITO-UNDERSCORE!18-03-48](https://user-images.githubusercontent.com/2406499/66352123-f92fc100-e92c-11e9-8157-15a336ddd366.png)

**Actual behavior:**

The page is blank

![firefox!UNITO-UNDERSCORE!2019-10-07!UNITO-UNDERSCORE!18-03-28](https://user-images.githubusercontent.com/2406499/66352059-e3220080-e92c-11e9-83d4-776172811013.png)

### Versions
* **Rock Version:** 9.2, prealpha (10.0)
* **Client Culture Setting:** en-US

**Comment by jrockman13** [comment]
I can replicate this by doing the following: putting in registration instructions and then deleting them. If I do not put in any registration instructions (on the instance) it works as expected. If I do and then delete them, it shows up.

**Comment by MichaelAllen** [comment]
It appears the problem is with the WYSIWYG editor. If you empty the editor then switch to code view, you will see that is is still storing `<p><br></p>` which causes the instructions page to show since that field is not blank. However, if you empty the editor in code view, it correctly stores an empty string and the instructions page will not show.

**Comment by jrockman13** [comment]
I'm curious how this would be fixed. Some type of process to see if the page contains any non-space characters? Would that be javascript? Lava? SQL? As a non-developer, this one seems not too technical and I could learn something :-)

**Comment by nairdo** [comment]
If one of the community developers wants to give this a shot and test it thoroughly, this proposed solution might suffice for a PR fix:

Solution:
Try using our `SanitizeHtml( w/strict = true )` extension method on the `instructions` in the `IsNullOrEmpty( instructions )` check in the RegistrationEntry block -- right around here: https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/RegistrationEntry.ascx.cs#L3635

**Comment by cabal95** [comment]
I'll take a look. I was thinking along the same lines.

**Comment by cabal95** [comment]
@nairdo Verified solution and submitted PR with the fix.

I had to put the `SanitizeHtml()` call in the return as well so the caller knew whether or not to show the instructions.
