### ISSUE TITLE
Event Registration - Previous Address

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#3938]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is](https://github.com/issues?q=is) %3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
When a person registers for an event using a previous address the address gets updated to the home address however the mailing and mapped checkboxes are not updated

### Steps to Reproduce
1. Update Ted Decker's address to make the current address a previous address.
1. Register Ted for an event using the address that is now his previous.
1. Address types for both addresses get updated properly but the former previous address will not have the mailing and mapped checkboxes updated.

**Expected behavior:**
The previous address gets updated to home address and the mailing and mapped checkbox gets updated.

**Actual behavior:**

Previous address gets updated to home but the mailing and mapped checkboxes are not updated.

Before registration:
![image](https://user-images.githubusercontent.com/383807/67513572-f1239100-f64f-11e9-85a1-32aa6afceb92.png)

After registration:
![image](https://user-images.githubusercontent.com/383807/67513577-f4b71800-f64f-11e9-90ef-3442605a7285.png)

### Versions
* **Rock Version:** 1.9.1.3 and 1.9.2.1
* **Client Culture Setting:** en-us

**Comment by daniellevos** [comment]
No longer a bug on Pre-Alpha site.

**Comment by nairdo** [comment]
I think this might still be happening in v11 but it does require that you set up the event registration with an address field, and that the person registering is matched to the existing person during the registration signup.

On pre-alpha (v11) I set up a template like so:
https://prealpha.rocksolidchurchdemo.com/page/403?RegistrationTemplateId=5
![image](https://user-images.githubusercontent.com/383807/67514946-8e7fc480-f652-11e9-9c10-37706e0ccf56.png)


Here's a before registration on the George Washington address:
![image](https://user-images.githubusercontent.com/383807/67514714-216c2f00-f652-11e9-97b5-9535efb2b4f0.png)

And here's an after registration (where George used his old/previous address when registering) on his record's family address:
![image](https://user-images.githubusercontent.com/383807/67514801-52e4fa80-f652-11e9-951f-6f92b1f7e5ba.png)

Note how the Mailing and Map Location checkmarks are still on the other home address... however I'm not entirely convinced this is a bug.

**Comment by cwomack** [comment]
@chrisfunk, I'm circling back through some of these outstanding issues reported on older versions of Rock to see if they still need a fix.  After trying to reproduce this in v9.2, v11.0 (per Nick's comments), and v12.5, I can't seem to get the originally reported bug to happen.  

Can you confirm if this is no longer an issue or provide screenshots of how your **Registration Template** was configured for an address input (such as @nairdo's screenshot above showing the field type on the form)?

If I don't hear back after a couple weeks, I'll go ahead and close this out.  Howvever if at any point you test this and still see the bug, feel free to comment back with your findings (or close it out yourself if it appears to be fixed).  Thanks!

**Comment by cwomack** [comment]
Closing this issue out as it appears to be fixed/no longer an issue on more recent versions of Rock.  If anyone is able to reproduce the issue further, please feel free to comment and I'll reopen.
