### ISSUE TITLE
Members in Attendance Details Doesn't Uncheck People Checked off

### ISSUE THREAD

**Issue by charlottedean** [SparkDevNetwork/Rock#3939]
### Description
The Members heading in Attendance Details no longer unchecks everyone checked off. 

### Steps to Reproduce
1. Attendance Analytics Check-in Detail or Group Attendance and go to Attendance Details
1. Click on Members
1. Doesn't un-select anyone that is already checked off. 

**Expected behavior:**

When you click on the Members heading it is supposed to uncheck everyone that is already checked off. 

**Actual behavior:**

It doesn't do anything. 

### Versions
* **Rock Version:** 9.2
* **Client Culture Setting:** en-US

**Comment by OnlyByGrace** [comment]
I'm happy to submit a PR for this, but I'd like to propose that we move this "hidden" functionality into the light by adding a "select/deselect all" button next to the Members header. Everyone who stumbles on this feature stumbles on it by accident. I don't know if there's a standard Rock way to do select all outside of a grid.

**Comment by jonedmiston** [comment]
Adding a link that toggled between 'Select All' and 'Deselect All' would be a good PR. Once provided we may do some re-arranging on the page too. The sort control is in a confusing place. We can polish that up though once the PR is submitted. Note though that the label does have a js- class that was used for selecting all. We might want to clean that all up as a part of the PR.

**Comment by lamebrain** [comment]
Might just be that this is a really old issue, but after I get to _Home > Attendance Analytics > Check-in Details_, I do not see a _Members_ link.

**Comment by nairdo** [comment]
Based on our analysis we believe this was probably fixed in v13 via https://github.com/SparkDevNetwork/Rock/commit/2bd05266b0fe831bbe8083ff0ac5ce2b47544d38.

Please let us know if you are still seeing this bug.  Otherwise we'll consider it closed.

![chrome_wykncY68QJ](https://user-images.githubusercontent.com/383807/180862188-8b5b814e-6e3a-40ae-80cb-72a57b31bd59.gif)
