### ISSUE TITLE
Captive Portal creates Blank Persons

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3940]
### Description
We have noticed that we are getting about 2-3 blank Person records each day generated by the captive portal. They are associated with devices but have no name, email or phone number. This appears to be because the CaptivePortal block just checks if the first and last name fields are _visible_, but not if they contain any data.

Granted the client-side JavaScript should be validating and blocking it, but apparently it is somehow bypassing that check in some cases. Server-side validation is going to be necessary.

We have First Name, Last Name and Email all visible and required, yet somehow that is being bypassed and blank person's are being created.

### Steps to Reproduce
n/a

**Expected behavior:**

A blank person record should not be created.

**Actual behavior:**

A blank person record is created.

### Versions
* **Rock Version:** 9.2
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@cabal95 or @DerekMangrum  Can either of you confirm that this issue was corrected in either v9.4 or v10.1?  (I have a vague recollection that we already tracked this down and resolved it.)

**Comment by cabal95** [comment]
@nairdo It is not fixed. I think what you are thinking of was the issue where the block wouldn't attempt to match an existing person unless the phone number was present.

A fairly easy way to replicate this is to inspect the "Accept and Continue" button to find the JavaScript it executes. It will be a `WebForm_DoPostBackWithOptions` call. As a parameter, it receives a WebForm_PostBackOptions. The 3rd parameter of that object is `true` normally (do validation). If you change it to `false` and then execute in the JavaScript Console without entering any information it will submit and create a new person record with no name/email/phone.

I'm not sure why some devices/browsers are apparently doing this automatically, but somehow they are occasionally causing this to happen without the user's knowledge.

I noticed in that block that there is no call to `Page.IsValid`, and it might be as simple as adding that call and checking the return value.
