### ISSUE TITLE
Rockit SDK downloaded with path as filenames

### ISSUE THREAD

**Issue by jsphkm** [SparkDevNetwork/Rock#3944]
### Description
A fresh download of the Rockit SDK from [https://community.rockrms.com/Page/365 ](https://community.rockrms.com/Page/365) with McKinley 9.0 results in files with path as filenames, 

For example

```
RockWeb\App_Code\BundleConfig.cs
RockWeb\.gitignore
```

There are no folders in the SDK.

The issue is probably in the file generator being unable to create actual folders but instead converting the entire path as filenames.

### Steps to Reproduce
1. Go to 'https://community.rockrms.com/Page/365'
1. Type your domain name
1. Select McKinley 9.0 under Rock Version, (same issue with McKinley 6.2, and possibly all others)
1. See in the downloaded folder that there are no folders and that filenames are erroneous

**Comment by jsphkm** [comment]
Where is the code that does the naming?  I think the issue is that it's using backslash instead of the forward slash.

**Comment by nairdo** [comment]
The SDK builder is a plugin that exists in a private repo -- but I'm not able to reproduce the issue you're describing.  It's working fine for me:

![image](https://user-images.githubusercontent.com/383807/66957829-d03db900-f01b-11e9-87a3-e87ad85ca284.png)

**Comment by MichaelAllen** [comment]
I can reproduce the issue when extracting the zip file on my Mac.
<img width="500" src="https://user-images.githubusercontent.com/282879/66960300-2c173a80-f03a-11e9-9c76-4eb11ba2594e.png">

But everything extracts correctly when extracting the same zip file on my Windows VM.
<img width="300" src="https://user-images.githubusercontent.com/282879/66960428-6da7e580-f03a-11e9-883b-3f5ae91be16a.png">

**Comment by cabal95** [comment]
Ah yes, I ran into this with my RockDevBooster @nairdo. I'm not sure how you are building the ZIP file automatically, but I ran into a similar issue when I was generating the `.plugin` files automatically due to the same bug in .NET Framework.

@jsphkm @MichaelAllen That said, Just so you know, the RockIt SDK won't actually work on Mac. You need Visual Studio on Windows to use it.

**Comment by nairdo** [comment]
We're about to make a small change with the Rockit SDK so I'll try this trick during the `ZipFile.CreateFromDirectory` to see if that helps our Mac/Linux friends peek inside the zip file: https://stackoverflow.com/questions/27289115/system-io-compression-zipfile-net-4-5-output-zip-in-not-suitable-for-linux-mac

**Comment by nairdo** [comment]
@jsphkm and @cabal95   I made the change (and another unrelated change**) to the Rockit SDK builder if one of you would like to give it a test: https://community.rockrms.com/developer/rockit

** I'd also appreciate it if you could also verify you can login with the admin account, once you edit your `web.ConnectionStrings.config` and start Rock for the first time in Visual Studio.

**Comment by cabal95** [comment]
I can confirm that the ZIP fix works for Mac. I tested both double-clicking to unzip with Finder as well as using the `unzip` command in Terminal. Both properly created the directory structure.  Windows also properly created the directory structure.

I can also verify that logging in as admin/admin works with this release as well.
