### ISSUE TITLE
Inactive Connection Types still accept requests on external signup block

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#3946]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
The Connection Opportunity Signup block allows a user to sign up for an Opportunity even if the Connection Type is not Active.  The block does correctly disallow signup if the Opportunity itself is not Active.

### Steps to Reproduce
1. Edit a Connection Type
1. Uncheck the Active box and Save
1. Go to the Connection Opportunity Signup page for one of that type's opportunities

**Expected behavior:**

An error message would tell the user that this opportunity cannot be signed up for.

**Actual behavior:**

The form is available and accepts signups.

### Versions
* **Rock Version:** 8.7, 10.0 (tested on prealpha)
* **Client Culture Setting:** en-US

**Comment by TheArkChurch** [comment]
This is also the case on the connection opportunity search block. If you disable a Connection Type, It still shows up with all of the opportunities.
