### ISSUE TITLE
Selecting Single Select Causes Exception

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#3948]
Submitted on behalf of [Northpointe Community Church ](https://www.northpointe.org/)

Note: Could not reproduce due on new install or demo site due to needing to install Room Management Plugin.

### Description
After updating to version 9 of Rock, when trying to add a new question to a Room Management resource, if you select a Single-Select or Multi-Select field type, an exception occurs. 

![image](https://user-images.githubusercontent.com/548180/66940508-e9357280-eff9-11e9-9e4b-44bcabe0a1e3.png)

This appears to be due to a combination of how the Room Management plugin uses field types and this change made to core for version 9: https://github.com/SparkDevNetwork/Rock/commit/204e5f565b0fd92928469e07dd7a618694bfa701. The `ConfigurationValues( List<Control> controls )` method in those field types used to handle incorrect qualifier controls, but they no longer do.

When you change a field type in the Room Manager's attribute editor, it looks like it is first calling that method with the previous field type's qualifier controls (OnLoad), before calling it again with the correct controls.

Let me know if you'd like me to submit this as an issue to the Room Management Plugin repo instead, but figured other plugins (or places in core) might have a similar issue.

### Steps to Reproduce
1. Install the Room Management Plugin
1. Add a resource
1. Start to add a question to the resource
1. Select the Single Select field type

**Expected behavior:**

You are able to add the question

**Actual behavior:**

An exception occurs.

### Versions
* **Rock Version:** Rock McKinley 9.2 (1.9.2.5)
* **Client Culture Setting:** en-US

Note: You can work around this by first changing the field type to one that does not have any qualifier controls (i.e. integer) and then selecting the desired field type.

**Comment by MikeDPeterson** [comment]
Talked to @nairdo  and we agreed to call this a Room Management Issue. Room Management fixes this in 1.5.1 (I suspect you were using 1.4.1-).  Since they fixed it, we'll close this issue.
