### ISSUE TITLE
Assessments Block On Extended Attributes Page Has No Title

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3949]
### Description

After upgrading to v9 (9.0 through 9.3beta) there is an Attribute Values block on the Extended Attributes page of the Person Profile that shows as "Attribute Values"
![image](https://user-images.githubusercontent.com/3903408/66961846-3256e800-f035-11e9-8506-f4d573850894.png)

**Expected behavior:**

Block would show a title of what the attributes are for.

**Actual behavior:**

The Block Title property appears to be empty, causing it to default to _Attribute Values_. What's strange is that I see this on v9.0 through v10.0 alpha in my systems, but on prealpha.rocksolidchurchdemo.com it shows as _Assessments_. Does this mean it will be (or has already been) fixed in a future post-v10 update?, Or that prealpha was just manually updated? Should we just update this ourselves since it's so inconsequential?

### Versions

* **Rock Version:** v9 - v10alpha

**Comment by MrUpsideDown** [comment]
The fix for this issue was added in the update to v10, and has now also been backported to v1.9.5.

**Comment by nairdo** [comment]
> What's strange is that I see this on v9.0 through v10.0 alpha in my systems...

@JimMichael When you get to v10.1 (beta), can you also confirm it is resolved?

**Comment by JimMichael** [comment]
@nairdo That SQL DOES return a record on my 10.1 (1.10.1.2) (alpha) system, yet the block still says _Attribute Values_ 
![image](https://user-images.githubusercontent.com/3903408/69356118-8d898500-0c48-11ea-9072-a12266d726c8.png)
and there is no title
![image](https://user-images.githubusercontent.com/3903408/69356145-97ab8380-0c48-11ea-98b9-a203fd6a5dcb.png)

This is on a copy of 9.3 from production instance. Maybe it's just a problem with _our_ instance/data? As far as I can tell it's just a cosmetic issue.

**Comment by nairdo** [comment]
For the sake of others reading this, Jim and I are working offline to see what might have happened on his test system.

```Sql
-- 1, does the block exist?
SELECT [Id] FROM [Block] WHERE [Guid] = '0C244AA1-2473-4749-8D7E-81CAA415C886'

-- 3, does the block's attribute have a 'block title' value of "Assessments"?
SELECT * FROM [AttributeValue] WHERE [AttributeId] IN ( SELECT [Id] FROM [Attribute] WHERE [Guid] = '6AA30A6D-D5E7-482E-A207-33026070DB42' )

-- 5, does the block's attribute have a 'block icon' value of "fa fa-project-diagram"?
SELECT * FROM [AttributeValue] WHERE [AttributeId] IN ( SELECT [Id] FROM [Attribute] WHERE [Guid] = 'E7704D69-2B48-490A-AC40-80D112E6EE0A' )
```

In his system query 3 and 5 returned a record with nothing in the `Value` column.

**Comment by MrUpsideDown** [comment]
Here's a summary of the notes I made while tracking this down - hopefully it will shed some light on what has happened here. This relates to the "BlockIcon" attribute specifically, but the same is true for the "BlockTitle" attribute...
1. Upgrade to **v1.9** creates new Block Attribute "SetPageIcon" *(DF437D92-FB5A-4625-851A-24F79412A337)* and sets a corresponding value of "fa fa-project-diagram".
2. Upgrade to **v1.9.1** does the following:
2.1. The block code is modified to change the key of the Block Attribute from "SetPageIcon" to "BlockIcon".
2.2. A data migration is added to create a new Block Type Attribute "BlockIcon" *(E7704D69-2B48-490A-AC40-80D112E6EE0A)* to correspond to the code change. However, no corresponding Attribute Value is created, so it has the default value (empty).
2.3. A subsequent data migration is run to change the key of the original Block Type Attribute *(DF437D92-FB5A-4625-851A-24F79412A337)* from "SetPageIcon" to "BlockIcon". Now there are two Attributes named "BlockIcon" for the "Attribute Values" Block, with different Guids.
3. At this point, opening the Bio page reads the "BlockIcon" Attribute by key and gets the (empty) value for the more recently created record *(E7704D69-2B48-490A-AC40-80D112E6EE0A)*. 
4. In **v1.10**, a data migration is added that has the effect of consolidating the duplicate key entries for "BlockIcon" to the Guid *(E7704D69-2B48-490A-AC40-80D112E6EE0A)* and - importantly - prefers the earliest Attribute Value, which is the "fa fa-project-diagram" value first created in Step 1.
Problem disappears!
