### ISSUE TITLE
Check Scanner Utility - MagTek Reader Not Scanning/Displaying Scanned Image when app first loads

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3951]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We updated the check scanner programs to the latest shipped with v9.2.

When the program first loads and you log in and your using a MagTek scanner, if you create a new batch and start scanning in checks, the program doesn't display or recognize that checks are being scanned. It remains on the scan screen awaiting a scanned image.

I first thought it might be a driver issue, thinking the scanner may not be communicating. I updated the drivers but that didn't fix the issue. I found when I first open the program and login, if I click on the gear to access the program's settings and click Save (without making any changes) scanning checks will work properly.

We have two CR-80s and 2 MagTeks and I only noticed this with the MagTeks. I do have Capture Scanned Amount and both total count boxes checked. I also tested it without these options checked and I get the same issue.

### Steps to Reproduce

1. Open the program with the MagTek scanner already configured. If it is not already configured, configure it, save, close the program, then reopen it.
2. Create a new batch and click scan, select checks and click Start.
3. Start scanning. Nothing will appear in the program even though the scanner is scanning
4. Click on the gear for setting and click Save then go back into the batch and start scanning again. It should work this time.

**Expected behavior:**

Scan checks normally.

**Actual behavior:**

Have to enter the Settings page and click save when the program first starts before you can successfully scan.

### Versions

* **Rock Version:** v9.2
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
@BEGamache is this behavior consistent across multiple computers? Or, is it limited to a single computer?  I would think if it was a code issue there would be more reports of this issue. If anyone else is having the issue please comment here.

**Comment by jonedmiston** [comment]
Closing due to no response. Please feel free to re-open if this is still an issue.
