### ISSUE TITLE
Check Scanner Utility - Unauthorized to edit a scanned check amount in the batch after it has been uploaded 

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3952]
### Description
When using Capture Scanned Amount setting, if you enter the wrong amount on a scanned check and save it then go back to the batch (still in the Check Scanner Utility) to edit the scanned you are given an unauthorized to edit error message when you try to save the change. 

The user is in the Financial worker security group. They can successfully log in to the program. They can match transactions on the internal side of Rock. We have tried a Financial Admin user and get the same error. When we tested a Rock Admin user it was successful. 

The issue is with the /api/FinancialTransactionDetail call. I tried looking to see if the security settings for this api were available in Rock but I wasn't able to find it, or I may have overlooked it. The Rest Controller had the correct security settings and the Rock Entity had the correct security settings so I don't know if the api's settings are stored elsewhere or hard coded.

### Steps to Reproduce
1. With Capture Scanned Amount checked in the program's settings. Scan a check or transaction and incorrectly put the wrong amount.
1. Save and close to go back to the main screen.
1. In the batch, go back to the scanned transaction and edit the amount to the correct amount. Click Save.
1. See error (when using Financial Worker or Financial Admin security rights, Rock Admin rights will work correctly)

**Expected behavior:**

If they are able to add the transaction they should be able to edit the transaction if they make a mistake. They also have the ability to edit the transaction on the internal side of Rock so it isn't necessarily a security issue for them not to be able to edit it--as long as they are a Financial Worker/Admin.

**Actual behavior:**

Not authorized to edit error.

### Versions
* **Rock Version:** v9.2
* **Client Culture Setting:** en-US

**Comment by BEGamache** [comment]
Here is a screenshot of the error:
![Screenshot (4)](https://user-images.githubusercontent.com/5738650/75264721-7319f700-57b5-11ea-81cb-9cc2cca495bf.png)

**Comment by nairdo** [comment]
@BEGamache  Thanks for the screenshot.  I've put this on our list to test/reproduce.

**Comment by jasonhendee** [comment]
@BEGamache Thanks again for bringing this to our attention. I was able to reproduce the issue in v9.2, but determined that it was resolved as of v9.3. If you're able to upgrade (the current version is 10.2), this issue should go away. Please let us know if you have any further questions or concerns.

Here is the specific commit where the issue was resolved: https://github.com/SparkDevNetwork/Rock/commit/875c772f787a905bd4db350e83515631494847fa#diff-c625ae01fbc9590c8f4b82820bd59e55R253
