### ISSUE TITLE
Check Scanner - UI issues

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3957]
### Description
We noticed a couple little UI issues when using the latest version of the Check Scanner Utility. On the page where you can select what type of transaction you are scanning (check, cash, etc.), when you select an option it becomes hidden--it's still selected but invisible.

We noticed something similar with entering in the scanned transaction's total. Sometimes the first option (General Fund) will disappear--it's random, I haven't found what may cause this. We can see the other possible accounts we can add totals to but the first one sometime goes invisible. Without clicking on anything, when we type in the amount it will correctly put the total in the invisible text box and we can see the Total label below the options update to what we entered.

These may be more feature requests than issues:
We noticed the Double Feed Detection doesn't scan or or add the scan to the screen and will require the user to rescan the transaction, which is great, but could a warning display on screen saying it detected a duplicate feed? Right now, the only indication is it isn't loading the scanned check and doesn't provide a warning.

When using Capture Scanned Amount, could the Next button be invoked by pressing the Return key or Enter key instead of having to switch from keyboard to mouse after entering in an amount for each scan? Not really an issue just more efficient and quicker.

We are using the latest version of Windows 10 Pro and the Scanner Utility version that comes with v9.2

### Steps to Reproduce
1. Create a batch and click Scan
1. Select a different Transaction type and that type will go invisible.

### Versions
* **Rock Version:** v9.2
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1173104915898714">OrangeBackgroundBlip.gif</a>

**Comment by nairdo** [comment]
Hi @BEGamache Assuming this is still happening for you... I'm just doing a quick follow-up to see if you can attach some photos (or screenshots) that shows the problem you're seeing.

**Comment by BEGamache** [comment]
I should be able to get some on Monday when we do our counts. I used the program this past Monday and had the same issues but I'll definitely see if I can capture some screenshots this coming monday.

**Comment by BEGamache** [comment]
I haven't been able to get the disappearing fund issue to occur this week. It happened to me last week but it is random when it does occur. Attached are the screenshots for the transaction type disappearing when clicking on it. I'll do more testing this week and next Monday to see if I can get the fund issue to occur.

This is the screen when you first click the Scan button.
![Screenshot (1)](https://user-images.githubusercontent.com/5738650/75263719-f9353e00-57b3-11ea-8794-02eef6010d36.png)

This is the issue when you select a different transaction type.
![Screenshot (2)](https://user-images.githubusercontent.com/5738650/75263725-fb979800-57b3-11ea-9d1d-edcc793cfc93.png)

This is when I switched from selecting cash back to check.
![Screenshot (3)](https://user-images.githubusercontent.com/5738650/75263729-fd615b80-57b3-11ea-8945-f4d6b4710e85.png)
