### ISSUE TITLE
Assessments Block On Extended Attributes Page Is Not Displaying Motivators Category Assessment Attributes

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3960]
### Description
Not certain why but for some reason the Assessments block on Extended Attributes is not displaying the Motivators category attributes. I have looked at the block settings and the Motivators category is selected. I have also looked at the person attributes and their category is set to Motivators so I'm not sure why this category isn't displaying. I haven't looked in the database yet to see if there is a different setting set somewhere.

### Steps to Reproduce
1. Go to a person's Profile Page and go to Extended Attributes.
1. Update the Assessments attributes and notice Motivators attributes aren't displaying.
1. Edit the block to make sure the Motivators category is selected
1. See error

**Expected behavior:**

Motivators attribute to display

**Actual behavior:**

Motivators attributes are not displaying in the Assessments block on the extended attributes page.

### Versions
* **Rock Version:** v9.2, v9.1 (demo site) and v10 (Alpha)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1171844927152204">11.0.png</a>

**Comment by ethan-sparkdevnetwork** [comment]
This limitation is by design. In order to display a succinct summary of a persons Motivators, Rock will show the person's ranking (High, Medium, or Low) of each Motivator Theme along with a list of the top five motivators.
