### ISSUE TITLE
Event Wizard Creates Uneditable Event and Points to Wrong Item

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#3961]
### Description
If you have allow create new event turned on in the Event Wizard and create a new event it creates a new event item that doesn't show up on the list of events. It also points you to page/396?EventId=5 which is the wrong link. It should point you to page/396?EventItemId=5. It also blocks you (Rock admin rights) from having access to edit it and it is in approval status of needs approval. Even if you go to the calendar item list and filter to show unapproved items the event doesn't show up on the list.

### Steps to Reproduce
1. go to event wizard
1. Edit the block settings and make sure "Allow Creating New Calendar Events" is turned on
1. Walk through the wizard and make sure to create a new event
1. When finished the summary will show "View Event Detail" and will point to page/396?EventId=x and instead should point to page/396?EventItemId=x
1. If you go to page/396?EventItemId=5 you will notice you cannot edit this event item in anyway.
1. If you go to https://rock.rocksolidchurchdemo.com/page/395?EventCalendarId=1 the item will not show up on the list even if you have show approval status of unapproved

**Expected behavior:**

I would expect to be able to edit the event I just created and also for the summary to point me to the right place.

**Actual behavior:**

It creates an event that I am unable to edit as a Rock Admin and the summary points to the wrong url variable.

### Versions
* **Rock Version:** [9.2]
* **Client Culture Setting:** [en-us]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1153129547742377">image.png</a>

**Comment by briankalwat** [comment]
Confirmed on `11.0.2`. I tried updating `IsApproved`, `ApprovedByPersonAliasId`, and `ApprovedOnDateTime` via SQL and it still never shows up in the Calendar Event Item List block.

**Comment by shauncummings** [comment]
The majority of this issue was resolved in this commit: https://github.com/sparkdevnetwork/rock/commit/940646b7bb57884d4ad9a17cc9344a3e13705b7c
