### ISSUE TITLE
Waitlist Error on Event Registration

### ISSUE THREAD

**Issue by daniellevos** [SparkDevNetwork/Rock#3974]
### Description
When creating an event registration where "Allow Multiple Registrants" is UNCHECKED, and "Waitlist" IS checked an error is received "Please correct the following:
To enable a wait list you must provide a maximum number of registrants." even if the maxiumum number of registrants is set.

### Steps to Reproduce
1. Go to Event Registrations and choose an event registration template.
1. Create a registration instance and set the "Maximum Number of Registrants" to any number. 
1. Then go to that same Registration Template and uncheck "Allow Multiple Registrants" and then check "Enable Waitlist".
1. Upon clicking "Save" see the following error: "Please correct the following: To enable a wait list you must provide a maximum number of registrants."

**Expected behavior:**

No error should be received when clicking save.

**Actual behavior:**

Error occurs even though the Maximum Number of Registrants is set.

### Versions
* **Rock Version:** v 9.2 [en-US] and higher (tested on 9.3 as well as on the Pre-Alpha Demo site)
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by nairdo** [comment]
Hi @daniellevos There are two different "maximum" settings, one for 'maximum number of registrants per registration' on the _template_:

![image](https://user-images.githubusercontent.com/383807/67959912-b45b1b00-fbb6-11e9-8553-6cf541f87467.png)

...and the 'maximum number of attendees' on the registration _instance_:
![image](https://user-images.githubusercontent.com/383807/67960035-ebc9c780-fbb6-11e9-973a-db8614240b76.png)

In your situation, do you have values in both the _template_ and in this later item in the registration _instance_?
