### ISSUE TITLE
Custom Group Schedule not working when choosing number weeks

### ISSUE THREAD

**Issue by craigmash** [SparkDevNetwork/Rock#3975]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
I am trying to have a group meet the first and third Thursday of each month. However, it will only use the first and not show the third.

### Steps to Reproduce
Group Viewer
Edit Small Group
Meeting Details
Choose Custom under Group Schedule
Click Edit Schedule
Choose date and time
Choose Recurring
Choose Monthly
Choose the First & Third Thursday
No End
OK
Save Group
Now the group schedule will only show "The First Thursday of every month at 6:30 PM"

**Expected behavior:**

Actually schedule the first and third Thursday

**Actual behavior:**

Only schedules first choice

### Versions
* **Rock Version:** Rock McKinley 9.3 (1.9.3.2)
* **Client Culture Setting:** en-US

**Comment by craigmash** [comment]
I searched but never found it. Someone else led me to https://github.com/SparkDevNetwork/Rock/issues/3906 which looks to be the same and this is a duplicate.

**Comment by craigmash** [comment]
Is just the display text wrong? Will attendance reminders go out on both choices?

**Comment by nairdo** [comment]
@craigmash It was just a bug displaying the text.  Are you saying you are seeing a problem with attendance reminders?  If so, please supply some details about that.  Otherwise let me know if you are not able to close this issue and I will close it for you.

**Comment by craigmash** [comment]
It looks like the attendance reminders are going out. However, it is still only displaying the first meeting. No where does it say they are meeting the first and third Thursday. So would this not still be a bug?

**Comment by nairdo** [comment]
The display bug was fixed via issue #3906 and would be in v11.
