### ISSUE TITLE
Lava enabled Email Controls don't allow lava commands/shortcodes

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3976]
### Description
Recent updates have added lava support to email fields in multiple places, for example communication templates, however the regex used to validate email fields only allows very simple expressions like `{{ something }}`.

[https://github.com/SparkDevNetwork/Rock/blob/33476f7f7c59c7ce6da47d2a57eca1f76f3db04f/Rock/Web/UI/Controls/EmailBox.cs#L129-L132](https://github.com/SparkDevNetwork/Rock/blob/33476f7f7c59c7ce6da47d2a57eca1f76f3db04f/Rock/Web/UI/Controls/EmailBox.cs#L129-L132)

![<a href="https://user-images.githubusercontent.com/2406499/68049071-5e6e9c00-fcb8-11e9-892e-119545928077.png">https://user-images.githubusercontent.com/2406499/68049071-5e6e9c00-fcb8-11e9-892e-119545928077.png</a> image]()

![<a href="https://user-images.githubusercontent.com/2406499/68049039-4b5bcc00-fcb8-11e9-9cdb-dddb133aeaa1.png">https://user-images.githubusercontent.com/2406499/68049039-4b5bcc00-fcb8-11e9-9cdb-dddb133aeaa1.png</a> image]()

### Steps to Reproduce
1. Create a new email template
1. Enter `{% if CurrentPerson.Email contains 'newpointe.org' %}{{ CurrentPerson.Email }}{% endif %}` as the "From Address"

**Expected behavior:**

The field is valid and I can save the template

**Actual behavior:**

The field is not valid and I can't save the template

### Versions
* **Rock Version:** 1.8.2, prealpha (11.0)
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
Any reason this hasn't gotten any looks in 10mo? Was it because it never got confirmed?

**Comment by nairdo** [comment]
@JimMichael We've looked at it but it's actually an enhancement request which requires a non-trivial (think time-costly) solution.

**Comment by JimMichael** [comment]
Thanks Nick! I guess the Lava-enabled-ness was added in error, then?

**Comment by Tschrock** [comment]
From what I can tell, all that's needed here is a change to the validation regex (NewPointe just changed it to ".*" to allow everything). The lava rendering should already be handling everything else.
