### ISSUE TITLE
Finance - Businesses Exception when there is a business with no address

### ISSUE THREAD

**Issue by darringraham** [SparkDevNetwork/Rock#3984]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If there is a business without an address you get a Rock exception when you roll over the Finance menu and select Businesses.

### Steps to Reproduce

1. Go to 'Finance | Businesses'
2. Add a business without an address
3. Save it
4. Select Businesses from the Finance menu and see error: 
```
NullReferenceException in App_Web_3uszvrdn
Message Object reference not set to an instance of an object.
```

**Expected behavior:**

You should see a list of the businesses even if one of them has a blank address.

**Actual behavior:**

A Rock exception is returned (see above)

### Versions

* **Rock Version:** [Rock McKinley 9.4 (1.9.4.1)]
* **Client Culture Setting:** [en-US]

**Comment by jonedmiston** [comment]
Hi Darrin! This has been reported and fixed here:
https://github.com/SparkDevNetwork/Rock/issues/3954

Should be in v9.5.

**Comment by darringraham** [comment]
Oh wow! I looked for that. Dang. My searching needs to improve.
 
Thanks, John.
 
Darrin
