### ISSUE TITLE
Adding Event Registration Field with Long Name Gets Changed to "First Name"

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#3986]
Submitted on behalf of [Scottsdale Bible Church ](https://scottsdalebible.com/campuses/shea/)

### Description
When editing a registration template and adding a registrant field with a long name, the name of the field is getting changed to "First Name".

### Steps to Reproduce
1. Go to the [Rock demo site ](https://rock.rocksolidchurchdemo.com/)
1. Got to Event Registrations
1. Edit the Summer Camp registration (under General category)
1. In the Registrant Form(s) area, add a new field
1. Set the source as "Registrant Attribute"
1. Set the name to something long. For example: "Please provide text for the confirmation email to go out to the people registering for your event/class"
1. Save the field
1. Save the registration template
1. Re-edit the template

**Expected behavior:**

The new field is saved correctly with the long name

**Actual behavior:**

The new field is saved with a name of "First Name"

[Here's a video ](https://www.dropbox.com/s/qriddrxihxxi4cd/RegistrationField.MP4?dl=0)that also shows this issue being reproduced.

### Versions
* **Rock Version:** Rock McKinley 9.3 (1.9.3.2)
* **Client Culture Setting:** en-US

**Comment by azturner** [comment]
This appears to be an issue with the "Abbreviated Name" field. If you actually enter a shorter name in that field, the issue does not occur.

**Comment by nairdo** [comment]
I'm not able to reproduce this in Rock v10.2 and I remembered seeing a change (https://github.com/SparkDevNetwork/Rock/commit/83bf7c8c2abe2facf2aa0529342574023bef58e5) that might have addressed this issue.

**Comment by nairdo** [comment]
We had a developer test and confirm that this fix (https://github.com/SparkDevNetwork/Rock/commit/83bf7c8c2abe2facf2aa0529342574023bef58e5) did indeed fix this issue as well as #3971 too.
