### ISSUE TITLE
Delete Blackout Date Exception: Group Scheduling

### ISSUE THREAD

**Issue by hbcpn** [SparkDevNetwork/Rock#3989]
### Description
Adding blackout dates for multiple people within the same family and then trying to delete the blackout from the "head" or person profile that the blackout was set on causes an exception unless the family "dependents" have their blackout dates deleted first. No amount of security rights fixes this, it seems to be an order of operations issue. This issue is replicated on the internal person profile page or the external profile schedule toolbox.

### Steps to Reproduce
1. Go to [Ted Decker's Person Profile Groups page ](https://www.rocksolidchurchdemo.com/Person/4/Groups)
1. Scroll down to The Schedule Toolbox - Ted Decker section
1. Click on Preferences Button
1. Click to "+" in the Blackout Date section of the Group Schedule Toolbox
1. Add a blackout date for Ted and some of his family members. ![image](https://user-images.githubusercontent.com/44647719/68636064-61436b00-04c8-11ea-9c30-94d09417b7f5.png)
1. Click Save
1. Click on the "X" to delete a Blackout Date **for Ted**, not one of his family members. You will only see the exception error on the external personal profile; internal person profile page does nothing (but the exception is logged)
1. See error ![image](https://user-images.githubusercontent.com/44647719/68636329-2db51080-04c9-11ea-83e6-26976aa42f00.png) Note: If you delete the blackout dates for Cindy or Noah first, then you can delete the Blackout date for Ted.

**Expected behavior:**
I would expect that Ted's blackout date be deleted regardless of any other family member having a blackout date applied, same or differing from his own.

If you allow setting blackout dates for other members, I would expect a warning to be displayed that deleting the blackout for the family "head" will also remove them for the remaining family members otherwise this relationship needs to be removed and any individual blackout dates must be able to be removed at any time, no dependencies.

**Actual behavior:**

No deletion of Ted's blackout date occurs, an exception error is recorded.
Exception Type | Source | Description |

.Net SqlClient Data Provider 
The DELETE statement conflicted with the SAME TABLE REFERENCE constraint "FK_dbo.PersonScheduleExclusion_dbo.PersonScheduleExclusion_ParentPersonScheduleExclusionId". The conflict occurred in database "rockdemo", table "dbo.PersonScheduleExclusion", column 'ParentPersonScheduleExclusionId'. The statement has been terminated.

This was something replicated on our current 9.4 and the demo server still at and Rock McKinley 9.3 (1.9.3.2)

### Versions
* **Rock Version:** [Rock McKinley 9.4 (1.9.4.1)]
* **Client Culture Setting:** [en-US]

**Comment by hbcpn** [comment]
I think this has existed since Group Scheduling was introduced in v9. It's confusing for the end user when they try to delete a blackout date and they have other dependents with the same blackout yet they want to delete their own and it throws the exception. I didn't realize this was an issue until a volunteer kept getting this exception error.

**Comment by hbcpn** [comment]
@shauncummings is this fix get merged into the v10 code base? Since v10 just went  live

**Comment by nairdo** [comment]
@hbcpn Yes. It will be in 10.2.

** I know it's hard to see this via Github once the commits from the `hotfix` branch get merged into the `develop` branch, but if you specifically change to the 10.2 hotfix branch and then look at the commits you can see it will be in that release:

![image](https://user-images.githubusercontent.com/383807/71110174-061a2d80-2184-11ea-9aea-5b99e7fc705e.png)
