### ISSUE TITLE
[10.1 Alpha] Rebuild Streak Data job fails with exception

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3991]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

After upgrading our production data on a dev system to 10.1, the new Rebuild Streak Data job throws an error when it runs (it is active by default). The error message reported on the job is `A valid streak type is required`.

### Steps to Reproduce

1. Copied production data to dev server
2. Upgraded Rock to 10.1 alpha.
3. Manually ran the job a few times over the past hour, each time failed with same message.

**Expected behavior:**

Job should run successfully, or not be enabled by default if there is some other action I need to take to configure it first.

**Actual behavior:**

Job fails with above error message.

### Versions

* **Rock Version:** 1.10.1.2
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1149362896650976">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1149362896650978">image.png</a>

**Comment by cabal95** [comment]
The job seems to reference an expected job setting, but no  job settings have been defined that I can see.

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Jobs/RebuildStreakMaps.cs#L58

**Comment by cabal95** [comment]
@nairdo Should this be fixed in 10.1 Beta? I still see the job there.

**Comment by bjwiley2** [comment]
@cabal95 This fix was included in the 10.2 branch

**Comment by cabal95** [comment]
Okay thanks for verifying. Just wanted to be sure.
