### ISSUE TITLE
[10.1 Alpha] Group RSVP Detail page "Show Advanced Settings" text does not toggle

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3993]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When editing a groups' RSVP occurrence, there is a text link called `Show Advanced Settings` that shows more settings below. When you click this link the additional settings do show but the text of the link does not change. If you click the link again the additional settings hide as expected. But again, the link text never changes.

### Steps to Reproduce

1. Edit a group's RSVP occurrence
2. Click Edit
3. Click Show Advanced Settings
4. See the text doesn't change.

**Expected behavior:**

Text should change to indicate that the next click will then hide the advanced settings.

**Actual behavior:**

The text never changes.

### Versions

* **Rock Version:** 1.10.1.2
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Fixed in v10.1 beta via https://github.com/sparkdevnetwork/rock/commit/670c87aaaa228790ab81a41ea3c49c571aa6743e
