### ISSUE TITLE
[10.1 Alpha] FontAwesome icons not showing if btn class applied

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3996]
### Description
If a FontAwesome icon in an `i` tag also has the `btn` class applied, it will no longer render correctly. This appears to be because the`btn` class overrides the `font-weight` setting from the `fa` class. I checked on our 9.1 server as well as the Rock 9.4 demo server and they both still render correctly with the two classes used together, but 10.1 alpha as well as the pre-alpha server both show the "missing character" placeholder.

### Steps to Reproduce
(Tested with Firefox on Windows)

1. Go to the Communication Templates
1. Edit the Default template
1. Change one of the colors and click Update
1. Notice what should be the `fa-times` icon just shows the missing placeholder.

**Expected behavior:**

Icon should show correctly.

**Actual behavior:**

It does not.

### Screenshot Sample
![Capture1](https://user-images.githubusercontent.com/1119863/68814708-59054000-062e-11ea-8a14-abf75bbd3615.JPG)

![Capture2](https://user-images.githubusercontent.com/1119863/68814710-5a366d00-062e-11ea-8a5f-d8b88f299e8f.JPG)

Why you be judging my design aesthetics?

### Versions
* **Rock Version:** 1.10.1.2
* **Client Culture Setting:** en-US

**Comment by garrettjohnson** [comment]
Checked, and the problem also existed in 9.4. It's best practice to have icon fonts on their own element so that clashes like this don't happen, so I've moved the icon to be an independent `<i>` tag inside the `.btn` div.
