### ISSUE TITLE
[v11 pre-alpha] Enabling Exclusive Routes Causes Site Detail Page to 404

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#4002]
### Description
While testing the updates to the Enable Exclusive Routes site setting, we found that enabling the setting on a site renders it impossible to further edit site settings from CMS Configuration as the Site Detail page 404s for sites that have Exclusive Routes enabled.

### Steps to Reproduce
1. Go to CMS Config > Sites
1. Click on 'External Website', Click 'Edit'
1. Scroll down to 'Advanced Settings'
1. Check the box for 'Enable Exclusive Routes'
1. Click 'Save'

**Expected behavior:**

Exclusive routes functionality should be working for any site it is enabled for, but editing any site's details should _always_ be possible from the Site Detail page (page/116).

**Actual behavior:**

The exclusive routes functionality for the site are working as expected, but it is impossible to make further changes to the site configuration as the Site Detail page 404s for any site that has `Enable Exclusive Routes` enabled.

### Versions
* **Rock Version:** 1.11.0.4
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
This is now fixed in commit https://github.com/sparkdevnetwork/rock/commit/4389558ce4bae60960a129d11800d95aa48db2df
