### ISSUE TITLE
Several Badge Bar Icons Don't Render Well With FA Pro Regular weight.

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4004]
### Description

Not sure this would be considered a bug but I'm reporting it just in case someone on core does. If you install FontAwesome Pro and choose Regular or Light font weight for the _Internal Site_, several core badges no longer render well (the become illegible) due to an assumed solid color background.

### Steps to Reproduce

1. Upload FA Pro
2. Change Internal Site theme to use Regular weight
3. Search for a person and observe that several core badges like eRA, Attending Duration, and Assessments are no longer usable as they show white-on-white text.

![image](https://user-images.githubusercontent.com/3903408/69096613-651c4380-0a1a-11ea-882a-c1f691ded1f2.png)

**Expected behavior:**

Not sure! For Lava badges this can be worked-around by changing the color of the text with an inline style, but many non-Lava core badges don't have any way to modify the color other than to change the underlying core CSS. 

Maybe the Internal site theme should not let you change FA weight, or put up a warning that it will mess up various badges if you do so? 

Or maybe the Less could become smarter and take into account the font weight when generating the CSS?

Or maybe ALL badges should have the ability to change both text and background color instead of having to go to the CSS? 

Or maybe it's not an issue at all and we just ignore it... just wanted to bring it up.

**Actual behavior:**

Changing the FA weight from Solid makes several badges illegible.

### Versions

* **Rock Version:** All

**Comment by garrettjohnson** [comment]
Fixed, non-core badges may require manual adjustment for proper display.
![image](https://user-images.githubusercontent.com/374209/70348346-bea8ae80-181f-11ea-9a41-172c87c97ede.png)
