### ISSUE TITLE
[EN] Add Cache Entities for Schedules

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4014]
### Description

Posting this here as it's more of a low-level developer item than a feature most people would understand, but I can re-post at the ideas site if necessary.

Rock is doing more and more with schedules. Between check-in, group schedules and various other places where Rock needs to make a round-trip to the database to load a schedule, it seems like it might be time to add a `ScheduleCache` object into Rock.

These would primarily be used in determining if a schedule is active (meaning "now" falls within the scheduled time frame) or if check-in is active - though they could be used when parts of Rock need to display the friendly name of a schedule as well.

### Record Counts

I did a check on our system (Shepherd Church) and we have 1,909 schedules. For comparison, Categories are already cached and we have 2,808 of those.

### Code

I can provide a pull request that adds a new ScheduleCache object to Rock along with migrating a few heavy usage places (such as check-in welcome screen) to use the new cache objects if approved.

**Comment by cabal95** [comment]
@nairdo asked me in chat to clarify something on this so thought I would post that clarification here too. This would be an "on-demand" cache. So as a ScheduleCache was requested it would be loaded from the database the first time and then used from memory after that. It would _not_ be a "eager load everything at launch" type of cache.

**Comment by jonedmiston** [comment]
Closing as this is a feature request.
