### ISSUE TITLE
Cannot cancel Assessment requests

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4015]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Sometimes people accidentally send an Assessment request. It might have gone to the wrong person, it might have been the wrong assessment type selected. They might have sent it twice by mistake. Either way, sometimes it happens.

Currently, we can find no way to cancel these requests other than editing the database directly. The reason we are considering this a bug is that a weekly reminder e-mail continues to be sent to those who have the errant requests, which is not a good user experience.

Requesting: A way for regular staff (meaning not an admin only process) to be able to cancel/delete _pending_ assessments. We don't want them to be able to delete completed ones (that should be an admin task IMHO), but they should be able to delete ones that have not been completed yet.

### Steps to Reproduce

1. Send a DISC assessment request to yourself.
2. Complete it.
3. Send a second DISC assessment request to yourself.
4. Say "oops" and try to find a way to delete it.

**Expected behavior:**

An staff-user should be able to delete a non-complete assessment request that they have errantly sent.

**Actual behavior:**

End-user gets spammed each week to take an assessment they already took.

### Versions

* **Rock Version:** 9.1
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@cabal95  FYI.  We opted to add a new Assessment History block under the person profile "History" tab. If a assessment request is not yet complete, a person with Edit rights to the block can use a delete button on that record to delete it. (_In the future we may allow securing Assessment Types and then change that over._)

**Comment by cabal95** [comment]
Saw that, thanks guys!
