### ISSUE TITLE
Lava Breaks User Entry Form Response Text

### ISSUE THREAD

**Issue by kkiserGH** [SparkDevNetwork/Rock#4018]
### Description
Using Lava with a pipe character "|" in the Response Text of a button on a User Entry Form in a workflow will break the buttons. The pipe character is used as the primary delimiter when splitting the Actions value.  Please see Rock\Web\UI\Controls\Workflow Controls\WorkflowFormActionList.cs - CreateChildControls():
`string[] nameValues = this.Value.Split( new char[] { '|' }, StringSplitOptions.RemoveEmptyEntries );`

The commits in #1512 addressed this in ValueListFieldType and KeyValueListFieldType classes but not in the WorkflowFormActionList class.

### Steps to Reproduce
1. Create a new User Entry Form on a workflow with a valid name.
1. Scroll to the actions at the bottom of the form and change the default Response Text from "Your information has been submitted successfully." to "{{ Workflow | Attribute:'Test' }}".
1. Save the workflow.
1. Edit the same User Entry Form just created on the workflow.
1. Scroll to the actions at the bottom of the form and view the actions.

![image](https://user-images.githubusercontent.com/54817742/70270539-43d18c00-176a-11ea-824b-2c712a18ddc6.png)

**Expected behavior:**

There should be a single action with a Response Text of "{{ Workflow | Attribute:'Test' }}".

**Actual behavior:**

There are two actions now.  The first action has a Response Text of "{{ Workflow ".  The second action has a Command Label of " Attribute:'Test' }}" with no Response Text.

![image](https://user-images.githubusercontent.com/54817742/70270611-68c5ff00-176a-11ea-82f5-4b90c69f342a.png)

### Versions
* **Rock Version:** 9.4 (1.9.4.1)
* **Client Culture Setting:** [en-US]

**Comment by cabal95** [comment]
I'm 99% sure that _was_ fixed at one point as I ran into that exact issue myself and then later was able to do it, so this appears to be a regression at some point.
