### ISSUE TITLE
Send Communication fails when many recipients (SQL timeout)

### ISSUE THREAD

**Issue by andrewsohc** [SparkDevNetwork/Rock#4023]
### Description
We are getting a SQL timeout when sending communications to over 8000 people.  We believe this is occurring during a query which compares the recipient list.  This query takes 5 minutes to run (modified to target the specific communication that was failing).

### Steps to Reproduce
1. Create Communication for over 8000 recipients
1. Send communication
1. Communication Job fails after 30 seconds

**Expected behavior:**

Email send

**Actual behavior:**

Timeout error in Job.

### Versions
Rock Version: Rock McKinley 8.8 (1.8.8.3)

Client Culture Setting: en-US

**Comment by JimMichael** [comment]
We cannot reproduce this on our system. We regularly send out >10,000 recipient emails without issue. We're currently on 9.4. but we didn't have issues with 8.x sending that many, either. Note that we are self-hosted with powerful web and SQL servers, however.

**Comment by andrewsohc** [comment]
We are using Azure DB.  Cranked it up to 400 DTU and still timed out.  Any ideas what we can do to speed things up?

**Comment by andrewsohc** [comment]
We are using a Communication list of Members and Attendees (12,000 records) segmented by Campus.  Not sure if that matters in terms of how process runs.

**Comment by nairdo** [comment]
@andrewsohc I know of several Rock organizations that _regularly_ send 20,000+ communications/emails out from their Rock through MailGun SMTP.

Here are a _few_ things I would check:

- Verify Auditing is **not** enabled under Global Attributes.
- Verify/Examine your System Settings > Exception List. Look for trouble there.
- Check to see if you have too many (unmanaged) workflows that are not complete and still running every N minutes**.
- Verify/Examine your System Settings > Jobs list and look at the Last Run Duration.  Is something taking too long to run?
- Consider migrating from Mailgun SMTP to Mailgun HTTP.
- Under Global Attributes, verify your `Lava Support Level`.  (Ideally you would set it to "NoLegacy" if you are using new, proper lava syntax, but check your exception log first)


** a Dynamic Data block with this query works nicely for that check:

```Sql
SELECT wt.[Id], wt.[Name], Count(1) AS Total 
FROM [Workflow] w 
INNER JOIN [WorkflowType] wt ON wt.[Id] = w.[WorkflowTypeId]
WHERE ( [Status] <> 'Completed' or [CompletedDateTime] is NULL)
GROUP BY wt.[Id], wt.[Name]
ORDER BY Total desc
```

**Comment by nairdo** [comment]
@andrewsohc Once you update to Rock v9.4 or later, if you have any other details please feel free to re-open this issue.
