### ISSUE TITLE
[v10.1 beta] Dynamic Report not updating after changing data view

### ISSUE THREAD

**Issue by jennifertroeger** [SparkDevNetwork/Rock#4024]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? **DID NOT DO THIS BECAUSE OF BETA TESTING**
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Following instructions on beta checklist, we set up a dynamic report block using a report's existing data view. Next item... change the data view and verify changes in the dynamic report results DID NOT UPDATE as it should have, results remained the same.

### Steps to Reproduce

1. Add new internal page and add dynamic report block
2. Select existing data view report, save and view results.
3. Edit the data view behind the report, click save to update results
4. Refresh dynamic report - RESULTS DO NOT UPDATE TO REFLECT UPDATED DV REPORT

**Expected behavior:**

Expected behavior is that results of the dynamic report would match the updated results of the data view report indicated in the block settings. 

**Actual behavior:**

What actually happened is the dynamic report continues to show original report data, not the updated data.

### Versions

* **Rock Version:** Rock McKinley 10.1 (1.10.1.3)
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
I cannot dupe this with a simple dynamic report. If I change the underlying dataview, the results on the report change immediately. Is it possible you're testing with a persisted dataview?

**Comment by nairdo** [comment]
@jennifertroeger I tried to reproduce this on the v10.2 alpha build but I was unable.  

Here is what I tried:

- Changing the criteria on an existing filter
- Adding new filters to the data view
- Removing filters from the data view
- I even changed the data view to persisted and repeated the items above

Each time, after saving the data view, simply refreshing the _Dynamic Report_ block/page displayed the updated/correct results.

If you are still seeing this issue please let us know by re-opening this issue.
