### ISSUE TITLE
[v10.1 Beta] Check In start time not honoring campus in another time zone

### ISSUE THREAD

**Issue by jennifertroeger** [SparkDevNetwork/Rock#4026]
### Description
Testing check in for a campus located in a different time zone. For purposes of beta testing, I created a campus in the Pacific time zone, where as all of our current campuses are in the Eastern time zone. I then set up check in on one group based on that new PST time zone and tested check in against it. Findings were that check in opened on EST settings, not PST and check in was recorded as EST on the record as well.

### Steps to Reproduce
1. Create a campus location with a verified address in another time zone.
1. Add the new campus to a check in group and kiosk device
1. Enable a test check in schedule on this group (if new/different from other groups)
1. Set the check in configuration on the kiosk to the new campus location and group
1. Test check in at a time when check in should not be active at new campus, but active at other time zone campus
1. Test check in at a time when check in should be active
1. After check in is complete, verify check in time on student profile to confirm if recorded as correct time zone for location child was checked in to

**Expected behavior:**

Expected behavior is that check in should not be allowed in new time zone. When testing during active schedule, check in time should be recorded in the correct time zone for that particular location.

**Actual behavior:**

What actually happened is that, while testing for check in at a PST campus, check in should not have been allowed but was, because other campuses in the EST qualified for active check in at that time.

When verifying the check in time for the PST campus, check in was recorded on student profile as EST zone.

### Versions
* **Rock Version:** Rock McKinley 10.1 (1.10.1.3)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
We have not been able to reproduce this issue.  If anyone else can, please let us know.  Otherwise we'll close this issue in about a week.
