### ISSUE TITLE
GivingLeaderId field is not getting set correctly

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4027]
### Description
After updating to version 9, the GivingLeaderId field on the Person record is not getting set correctly for people who do not combine their giving with a family. This includes new child records that are created (Giving Leader Id is set to 0), and any record that is changed from combined to individual Giving (the Giving Leader Id remains what it was prior to the change).

### Steps to Reproduce
1. Go to demo site
1. Add a new family that includes children. i.e. (Dad Test, Mom Test, Child Test)
1. Change Dad and Mom so that they do not combine their giving
1. Run the data cleanup job

**Expected behavior:**

The records are created with the correct GivingLeaderId and the GivingLeaderId is updated when records are changed from combined to individual (or when cleanup job runs).

**Actual behavior:**

After family is created, the Child record has a value of '0' for the Giving Leader Id. It remains 0 even after the Data Cleanup job runs.

![image](https://user-images.githubusercontent.com/548180/70676921-eb5b2c80-1c4a-11ea-9da8-67f96fedf2a0.png)

After changing both Dad and Mom to contribute individually, the GivingLeaderId does not get updated. Mom's record still shows Dad as the Giving Leader Id (even after data cleanup job runs):

![image](https://user-images.githubusercontent.com/548180/70677245-df239f00-1c4b-11ea-8a82-03b5dd4b6aa1.png)

### Versions
* **Rock Version:** Rock McKinley 9.4 (1.9.4.1)
* **Client Culture Setting:** en-US

**Comment by aaronjones8** [comment]
I'm noticing an issue on another rock install where the giving is combined but the Giving Leader ID incorrect (being set to the individuals id instead of the primary giver id). I have a script I run to fix it but it gets reverted. Not sure if it is happening when the cleanup job runs or when the family/individual record is updated. May be related to this issue.

**Comment by tstephens17** [comment]
I believe we are seeing a similar issue with families created from the pre-registration block.
