### ISSUE TITLE
Grid Results Not Showing Time if Seconds = 0

### ISSUE THREAD

**Issue by courtneycooksey** [SparkDevNetwork/Rock#4028]
### Description
When using the dynamic data block with a date time column, when the seconds property is set to "00" the time does not show even if it has an hour and minute

### Steps to Reproduce
1. Go to the demo site
1. Create a new page
1. Add the dynamic data block
1. Set the query to select a date time

```
SELECT
	CAST('2019-12-11 10:45:00' as datetime) AS [DateValue],
	'First Entry' AS [TextValue]
```

1. Save the block 

**Expected behavior:**

The field displays as 12/11/2019 10:45am

**Actual behavior:**

The field displays as 12/11/2019
If the value includes seconds it displays correctly

### Versions
* **Rock Version:** Rock McKinley 11.0 (1.11.0.5)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Just to note, this isn't specific to the Dynamic Data block. You can see the same behavior in the Power Tools SQL page so this is likely something about the Grid itself (will update title to reflect this).

**Comment by cabal95** [comment]
For posterity, it looks like SqlCommand is the only other place that has this same issue/code.
