### ISSUE TITLE
Staff & Staff-Like Roles Get Explicit Rights to Registration Templates

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4031]
### Description

We're seeing an issue (verified on demo) where anyone in Staff Workers or Staff-Like workers roles has the ability to add or delete Event Registration Instances, because Rock automatically adds these rights when the _template_ is created.

### Steps to Reproduce

1. Go to Utility | Event Registration and add a new template.
2. Click on your new template and click the lock symbol to view its rights
3. Observe that both Staff Workers and Staff-Like Workers roles have "Item" (explicit) rights to Edit, which means anyone in those roles can add or delete a registration instance based on that template.

**Expected behavior:**

I expect Rock to add rights to new things based on inheritance (in this case, perhaps inheriting edit rights on the page or Category Tree View block?) so that we are in control of who gets rights to add/edit/delete registration templates & instances.

**Actual behavior:**

Rock adds explicit rights to Staff & Staff like roles, which means you must then remember to go "fix them" if you don't want all staff to be able to edit these (or worse, accidentally delete) a registration instance.

This issue seems similar to https://github.com/SparkDevNetwork/Rock/issues/1732 but I'm not sure it's exactly the same. In any case, it's a problem for us.

### Versions

* **Rock Version:** v9+

**Comment by nairdo** [comment]
Hi @JimMichael  Just a quite note about what I just did with this issue.  I removed the `type: bug` from the label since we're [explicitly doing this in the code on purpose](https://github.com/SparkDevNetwork/Rock/blob/93f5f4fbbda55259e6bdb3bd44cdf686519f05a6/RockWeb/Blocks/Event/RegistrationTemplateDetail.ascx.cs#L1403:).  

I'm looking to see if there is somewhere else in Rock where we handle this sort of thing a different way.  If it turns out there isn't, you'll probably need to turn this into a feature-request / Idea (block setting, copy from Category, etc.) on the Ideas board.

**Comment by nairdo** [comment]
Hi @JimMichael , we finally got around to a full investigation of this one and we've determined two things:

1) This was intentionally done (https://github.com/SparkDevNetwork/Rock/commit/8d4c76416ede05a6daa2aa3129d6b44812647998) in 2015
2) If we remove the code that is granting explicit permission, it will cause a problem.

If you believe this aspect should change, could I ask you to close this and submit a feature request (idea) over at community.rockrms.com/ideas to change the event template security to perhaps inherit from the template category?

**Comment by JimMichael** [comment]
Thanks for running it down. I guess there's a built-in assumption that all staff will be able to deal with Events, which isn't the case for us... Events are highly centralized due to their complexity. We've learned to work around it by just adjusting the rights manually  when we create a new template, which is actually somewhat rare these days.... so we're good.
