### ISSUE TITLE
Simple Communication Entry block has empty From SMS drop down if filter applied

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4040]
### Description
This issue was found while testing #4039. Assuming that issue is fixed, and you edit the block settings and then select any numbers to be made available (e.g. say you have 3 numbers and you tic 2 of the check boxes), then when you are trying to send an SMS, the dropdown for the `From` field will be empty.
![image](https://user-images.githubusercontent.com/383807/72916860-0320d880-3d00-11ea-82eb-308bde9b0aff.png)

![image](https://user-images.githubusercontent.com/383807/72916992-3e230c00-3d00-11ea-9fbf-152c9ef797b9.png)

The issue seems to be here:

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Web/UI/Controls/Communication/Sms.cs#L127

A DefinedValuePicker is used for both use cases (show all numbers, show filtered numbers). But I don't think that is allowed. The DefinedValuePicker will clear any Data Bound items, and then attempt to fill from the DefinedTypeId setting - but since that isn't set, you end up with an empty drop down. And even if that is set, you would end up with all values again.

I think that bit of code needs to be changed to use a DefinedValuePicker if no filter options exist. But if filter options do exist, then instead use the base RockDropDownList instead.

Additionally, I noticed that when using filtered values, the `Description` is used exclusively for the text that would be displayed. I think that is also incorrect. Many of our numbers don't have a Description. I think that part in particular should be changed to use Description if it's `.IsNotNullOrWhiteSpace()`, otherwise use the `Value`.

### Steps to Reproduce
1. Go to the Simple communication Entry on a pre-10 system.
1. Edit the block settings.
1. Select some (not all) options and save.
1. Reload the page.
1. Switch to the SMS panel
1. Notice the From drop down is empty.

**Expected behavior:**

The selected numbers should be available in the Drop Down.

**Actual behavior:**

An empty void is experienced instead thus sucking the will to live from you.

### Versions
* **Rock Version:** 9.4
* **Client Culture Setting:** en-US

**Comment by MrUpsideDown** [comment]
I also ran into this issue while testing the fix for #4039. Fortunately, I survived with my will to live intact, but I did see the "empty void" behavior described by @cabal95! We can't make the DefinedValuePicker.Items collection immutable, so to prevent this kind of problem from occurring elsewhere in the code, I'd suggest that the DefinedValuePicker should be fixed to work correctly with a custom data source.
