### ISSUE TITLE
Total Giving Not Subtracting Refund

### ISSUE THREAD

**Issue by aaronjones8** [SparkDevNetwork/Rock#4042]
### Description
When creating a report with Total Giving, refunded transactions are not being subtracted from the total giving.

### Steps to Reproduce
1. Create a Person Report
1. Choose Total Giving
1. Refund a transaction
1. Total Giving remains the same

**Expected behavior:**

Expected that Total Giving would be total of transaction amounts - refunded amounts

**Actual behavior:**

Total giving is sum of all transaction amounts in date range without factoring in refunds. (may be by design but had a client asking if it should be)

### Versions
* **Rock Version:** [8.9 and 10.1]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
@aaronjones8 Although this advanced (non-simple) report field implies it is filtering by the "Total" amount, it is actually filtering out the individual transactions by the given Amount not the _total_ amount.   (NOTE: If you were to change your Amount to a large negative number, you should find it would not filter out refunds.)  I believe this is a bug.
![image](https://user-images.githubusercontent.com/383807/71688532-36a1c000-2d5d-11ea-84f1-7da7dfc4ab7c.png)
