### ISSUE TITLE
Attribute Matrix Index Lava Issue

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#4045]
### Description
When trying to access an attribute matrix item by the index, it never returns a value.

### Steps to Reproduce
1. Create an Attribute Matrix with any type of Attribute (I encountered the error with Defined Value and MultiSelect, but I believe all field types are broken).
1. Create a simple workflow where you automatically persist and require the attribute
1. Launch the workflow and add three attribute matrix items to the list and save
1. View the workflow in Lava Tester and attempt to fetch the Attribute Matrix via Lava. (You can't.... The Attribute Matrix only returns the Name or the RawValue.)
1. Using Lava Entity, fetch the AttributeMatrix via the RawValue above and attempt to grab AttributeMatrixItem 2 IE: `{% assign attributeMatrixItem = matrix.AttributeMatrixItems | Index: 1 %}`
1. Notice how it returns nothing?

**Expected behavior:**
I would expect for the index to return the correct value, but it returns nothing.

**Actual behavior:**
It returns no value every time.

Now, I will say what is interesting is if you apply a Lava Array filter to your AttributeMatrixItems collection, it works fine. Here is an example:  Note that I went with `Sort:'Order'`

```
{% attributematrix where:'Guid == "{{ matrixGuid }}"' %}
    {% assign attributeMatrix = attributematrixItems | First %}
    {% assign matrixItems = attributeMatrix.AttributeMatrixItems | Sort:'Order' %}
    {% assign matrixItem = matrixItems | Index: count %}
    {{ matrixItem | Attribute:'Type','RawValue' }}
{% endattributematrix %}
```

Working
![<a href="https://user-images.githubusercontent.com/7517351/71383298-52f56e00-25a1-11ea-9d11-3f6156a72e88.png">https://user-images.githubusercontent.com/7517351/71383298-52f56e00-25a1-11ea-9d11-3f6156a72e88.png</a> image]()

Not Working
![<a href="https://user-images.githubusercontent.com/7517351/71383309-61dc2080-25a1-11ea-8bbe-902f31b9326c.png">https://user-images.githubusercontent.com/7517351/71383309-61dc2080-25a1-11ea-8bbe-902f31b9326c.png</a> image]()

Test Case on Demo Site Here: [https://rock.rocksolidchurchdemo.com/page/2598](https://rock.rocksolidchurchdemo.com/page/2598)

### Versions
* **Rock Version:** 1.8.9, 1.10.1
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Looks like the `Index` filter is configured to only support `IList` types. This should probably be changed so that it support `ICollection` as well as `IEnumerable` types as well (though I think `ICollection` might supersede `IList`).
