### ISSUE TITLE
Attendance Analytics Exception when sorting by Campus

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#4051]
### Description
This bug is submitted on behalf of Chase Oaks Church.
When using Attendance Analytics, if you sort by Campus, you get an error. Looking at Exception Log, there is not exception present for this.

![image](https://user-images.githubusercontent.com/7517351/72082498-ddd6a800-32c5-11ea-9d7f-a44709318c02.png)

### Steps to Reproduce
1. Go to Attendance Analytics
1. Select groups to get information
1. Switch to Attendee View
1. Click on the Campus in the grid to sort
1. ERROR

I have been able to reproduce this on the demo site. Here is the report link for replication purposes.
https://rock.rocksolidchurchdemo.com/page/296?TemplateGroupTypeId=14&SlidingDateRange=Current%7c%7cMonth%7c%7c&GroupBy=1&GraphBy=4&CampusIds=null%2c1%2c2&DataView=0&GroupIds=24%2c25%2c26%2c27%2c28%2c29%2c30%2c31%2c32&ShowBy=1&ViewBy=0&AttendeesFilterByType=0&AttendeesFilterByPattern=%7cFalse%7c%7c&ScheduleIds=0&AttendeesFilterByVisit=

**Expected behavior:**
Report is sorted by campus

**Actual behavior:**
Error is encountered

### Versions
* **Rock Version:** 9.4, 10.1
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
Confirmed on 9.4 here. I do get an exception in the log, though it contains the identical information as show in the UI error.

**Comment by nairdo** [comment]
FYI: Just a quick note for anyone who looks at that commit -- there is also a corresponding hotfix 'data migration' (which actually updates the stored procedures in the Rock database) which will be included in the 10.3 release.  That falls outside this process a bit and so it's just not included here in the repo yet.
