### ISSUE TITLE
Communication Fails to Send if Group Member doesn't have CreatedDateTime

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#4057]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
This issue was submitted on behalf of Citizens Church.
This is a very strange bug that is hard to replicate. Essentially, if a person is imported into a group via SQL, there is a chance they are not imported with a CreatedDateTime property. When the Process Communications job runs, it calls the RefreshCommunicationRecipientList method on the Communication model to grab a list of people the communication should be sent to. Here in the code, it filters out all Group Members who do not have a CreatedDateTime. https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.8.9/Rock/Model/Communication.cs#L769-L773. Looking at these few lines of code, I am wondering if the logic needs to be updated to properly account for GroupMembers without CreatedDateTime. 

Looking at this line of code, I don't see how the first condition would ever not be met.
```a.DateTimeAdded.Value < memberAddedCutoffDate```

### Steps to Reproduce

1. Add a group member to a Communication Group
2. Remove their CreatedDateTime
3. Try to send an email to the group
4. Notice how that person mysteriously disappears from the communication.

**Expected behavior:**
If a person is in a communication list, they should get an email.

**Actual behavior:**
Because the person is missing the CreatedDateTime, they get filtered out of the email.

### Versions

* **Rock Version:** 8.9, 9.4, 10.1
* **Client Culture Setting:** en-US

**Comment by MrUpsideDown** [comment]
@tscrip: I am trying to replicate this issue, but I can only do so if the DateTimeAdded field is also null. Setting the CreatedDateTime to null does not exclude the person from receiving the communication if they have a DateTimeAdded value in my testing, so perhaps there is some other contributing factor I need to look for. Can you please confirm that the DateTimeAdded field *does* contain a value in your test record, and it is only the CreatedDateTime field that is set to null?
