### ISSUE TITLE
Send Email Workflow Action error after v10 update

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#4060]
### Description
After updating to v10, a lot of our workflows are throwing a "A From address was not provided." error when trying to send emails

### Example 1
Error Message:
![firefox!UNITO-UNDERSCORE!2020-01-20!UNITO-UNDERSCORE!13-31-06](https://user-images.githubusercontent.com/2406499/72750052-c501a880-3b89-11ea-996f-d86ea4d06e3e.png)

Configuration:
![firefox!UNITO-UNDERSCORE!2020-01-20!UNITO-UNDERSCORE!13-26-47](https://user-images.githubusercontent.com/2406499/72750465-e7e08c80-3b8a-11ea-8e9c-0e05cea0c330.png)

### Example 2
Error Message:
![firefox!UNITO-UNDERSCORE!2020-01-20!UNITO-UNDERSCORE!13-58-43](https://user-images.githubusercontent.com/2406499/72751214-fcbe1f80-3b8c-11ea-9d6a-037a3ee311ac.png)

Configuration:
![firefox!UNITO-UNDERSCORE!2020-01-20!UNITO-UNDERSCORE!13-59-35](https://user-images.githubusercontent.com/2406499/72751242-1c554800-3b8d-11ea-9f8e-427e394cb7b0.png)

Lava:

```
{% assign Leader = Workflow | Attribute:'WorkflowStakeholder','Object' | Property:'Members' | Where:'GroupRoleId',318 | Select:'Person' | First %} {{ Leader.Email }}
```

![firefox!UNITO-UNDERSCORE!2020-01-20!UNITO-UNDERSCORE!14-00-55](https://user-images.githubusercontent.com/2406499/72751333-5b839900-3b8d-11ea-9925-fce9339e56f6.png)

### Versions
* **Rock Version:** 10.1
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
It looks like this is a side-effect of this commit:

https://github.com/SparkDevNetwork/Rock/commit/eb0f4f9b7e953cc589cfea6088a7c4895de4f7c4

It changed the check on the From address from "is not null or blank" to "is a valid e-mail address", meaning it must be an `user@email.org` address exactly, and  not `Bob Smith <user@email.org>`.

@Tschrock A quick work around would be to change your workflow actions to be JUST the e-mail address, that seems like it should resolve it for the moment. It also looks like this  only affects the Mailgun Http transport, so you might be able to switch to that temporarily.

**Comment by JimMichael** [comment]
And in the case of the Lava-rendered from address, you could Lava run action prior to the email send and just send to that attribute (as a workaround)

**Comment by JimMichael** [comment]
While testing 10.2alpha I tried this out, and while it does indeed now **send** the message when you use an address of the form `Jim Michael <jimm@mydomain.com>` it now throws a different exception:
![image](https://user-images.githubusercontent.com/3903408/75197872-dc9df500-5724-11ea-993f-cf9d5fe379df.png)

**Comment by nairdo** [comment]
Ethan dug into this issue, after some analysis, we would say the following: Although the "From Email Address" field (**single** address) now _can_ handle this alternate "_Name Name <email@address>_" format, it would be a much more complicated change to try to allow the "Send To Email Addresses" field (**multiple** addresses) to handle that format too.  

So, since Rock has never supported that, we're going to defer that to a later request and re-close this issue.  Thanks for all your testing @JimMichael!
