### ISSUE TITLE
Email Analytics Page Removed In 10.x Breaks Communication List Analytics

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4063]
### Description

This is a multi-factor issue, but all inter-related.

Issue 1: The Analytics button (a Custom Grid column) on the Communication Lists grid points at a bad URL `<a href='~/EmailAnalytics?...` and causes a 404 because, 

Issue 2: The entire EmailAnalytics page has been removed.

### Steps to Reproduce

1. Go to Admin | Communications | Communications Lists and click the Analytics icon on the right of the row.

2. Observe the 404

3. Observe that People | Email Analytics is no longer a menu item.

**Expected behavior:**

I would expect to see aggregated analytics _for that list_, but I'm guessing you'll say the bug here is simply that the custom grid icon was forgotten to be removed, just like it was (removed) on the People | Communications History grid.

**Actual behavior:**

You get a 404. But beyond that, we lost the very useful ability to see "global" Email Analytics (via People | Email Analytics page) AND -- even worse --  the ability to see aggregated analytics _per Communication Lists_. Now it seems that all we get in v10.x are _per-email_ analytics.

Can we get some clarity on why this useful (and I would say necessary) feature was removed, especially without community input?

### Versions

* **Rock Version:** 10.x

**Comment by JimMichael** [comment]
I verified that this fix indeed now lets the Analytics grid buttons on the Communications Lists work as before, but the **Email Analytics** page was not re-added to the People menu. I just wanted to make sure that was intentional (I can see why it might not be added back, as it only provided the not-terribly-useful "global" email analytics from the beginning of time)

**Comment by nairdo** [comment]
For any other viewers of this issue... As discussed offline, we did verify that the Email Analytics page _is_ now back under the People > Communications menu.  Thanks again for your help @JimMichael.
