### ISSUE TITLE
Sort Connection Requests by Connector not working

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/Rock#4067]
### Description
Sorting by Connector in the Connection Requests grid on the My Connection Opportunities block does not sort by the person's name. The order changes each time the Connector table header is clicked, but the order is not alphabetical.

### Steps to Reproduce
1. Go to People > Connection Requests
1. Select an oportunity that has at least 3 requests, all with different connectors assigned
1. Scroll down to the Connection Requests grid
1. Click on the Connector table header to sort the grid by that column
1. Notice the order of names is not alphabetical

**Expected behavior:**

Clicking on the Connector header should sort the grid alphabetically by connector names.

**Actual behavior:**

The rows are resorted, but they are not alphabetical by connector name.

### Versions
* **Rock Version:** Rock McKinley 9.4 (1.9.4.1)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
fixed via https://github.com/SparkDevNetwork/Rock/commit/3cfc9ae618155e0c3ae9334c35317024e481a469
