### ISSUE TITLE
Event Registration Address Blank

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#4070]
On behalf of First Presbyterian Church - Colorado Springs

### Description

Leaving an optional address field blank on an event registration causes blank addresses to be added to the person record.  If there is a Named Location with a blank address, it matches the blank address to the named location and links it to the person record.

### Steps to Reproduce

1. On rocksolidchurchdemo.com, create an event registration template with first, last, email and address.
2. Create an event registration instance that is active for the template.
3. Add a URL slug like "Test1" to the instance.
4. Go to https://www.rocksolidchurchdemo.com/registration/test1
5. Enter first, last, email but leave address blank.
6. Complete the registration.
7. This will create the person with a blank address.  If it finds a blank address in the Named Locations, the underlying data will actually link the family to the named location id.
8.  If there was a previous location for the person, it will replace the previous location with a blank location.

**Expected behavior:**

I would expect blank addresses to be ignored and not update the person record.

**Actual behavior:**

A blank address is added to the person record.  If there was a previous location it gets replaced with a blank.  If there was a Named Location with a blank address, it will link the family to the named location with a blank address.

### Versions

* **Rock Version:** 9.4 and 10.1
* **Client Culture Setting:** Azure

**Comment by alyssa-pathway** [comment]
We are experiencing this as well. We are noticing that when a person completes a registration with a blank address, they end up with two Home Addresses, one correct and one blank. 
![blankaddress](https://user-images.githubusercontent.com/29411182/73300629-f821e880-41d6-11ea-8f9d-c4998c347e92.PNG)
