### ISSUE TITLE
Group Detail Lava block ignores security on group attributes

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4079]
### Description
When setting up a Group Type, you can add Group Attributes and secure them so only certain staff can see/edit them. This works great.

However, over on the Group Detail Lava block, it ignores those security values and gives access to view/edit them as long as you have edit access to the group (e.g. leader).

I realize the "View" part is handled by Lava, and indeed we have modified our Lava template to only show certain group attributes.

The problem is we cannot hide the values from the Edit screen. We are working around this by using JavaScript to CSS hide those fields, but they still exist. In the past this was just a case of "well we don't want them to get confused and edit the wrong thing so let's hide those". Now we are looking to add some more sensitive information that we don't want them to be able to see, let alone edit. So the JavaScript solution is far less than ideal at this point.

I can build this and provide a pull request if requested.

### Suggested Resolution
Since we can't just wholesale make a change without (likely) breaking everybody's group leader toolbox, I suggest the following steps to resolve this.

1. Add a new Boolean attribute to the Group Detail Lava block called `Enforce Group Attribute Security` with a default value of `True`.
1. In a migration, set the value of this new attribute on all existing blocks to `False` - excluding the "stock/demo" block in the sample External Site. (yes some people may use this, but they aren't really supposed to).
1. Update the `GroupDetail.lava` file in the Stark theme to check security on the attributes before displaying their values (I think this is possible?).

This would let us make the change for all new installs, but not change existing installs (with a few minor exceptions if they are using the sample site for their main site).

### Alternate Resolution
If we want a less intrusive change:

1. Add a new Boolean attribute to the Group Detail Lava block called `Enforce Group Attribute Security` with a default value of `False`

At this point it would be up to individual installs to decide to enable security on the group attributes.

### Steps to Reproduce
1. Login to Rock demo site.
1. Edit the Group Type of `Small Group`, view the `Topic` attribute and note the security only allows Administrators to Edit.
1. Login to the public site as Pete Foster (has staff access, but not admin).
1. Go to My Account
1. Pick `Pete's Group` as the group to work with in the toolbox.
1. Click the Edit button
1. Change the value of the Topic and Save.
1. See the value has changed.

**Expected behavior:**

If security is enforced for staff I would expect it to be enforced for non-staff too.

**Actual behavior:**

Security is not enforced.

### Versions
* **Rock Version:** 10.2
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Apparently I already reported this as a bug some time ago and forgot. I'll leave them both open for now and just link them since this one has a proposed solution attached.

Duplicate of #3569

**Comment by tpcc-myles** [comment]
We are experiencing the same issue on our install (currently v12.6).  Unfortunately, we do not have the CSS/JS workaround mentioned, so a couple of fields are editable for group leaders, even though they cannot be seen in View mode (we modified our Lava to hide them).  We'd love to see resolution on this item.

**Comment by jonedmiston** [comment]
@tpcc-myles raising up the internal priority.
