### ISSUE TITLE
Transaction Detail Page - Object Reference Error.

### ISSUE THREAD

**Issue by JoshuaMaiorino** [SparkDevNetwork/Rock#4083]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When Navigating to the Transaction Detail Page on certain transactions, the page is throwing an object Reference error.  This error is being thrown from the Show Details function on the page.  Upon review the issue is occurring when the .Trim() function is being called on the PaymentDetails.NameCard Field.  Upon reviewing the data in the database, there is an encrypted string on the NameOnCard field.  If it's possible for the virtual property "NameOnCard" to return a null value, the logic in outputting that should have null error handling as to not cause the page to throw an error.

### Versions
* **Rock Version:** [9.4]
* **Client Culture Setting:** [en-us]

**Comment by nairdo** [comment]
@JoshuaMaiorino Thanks for reporting this.  In general, it's always pretty helpful if you can attach/paste the exception that occurred.  (It can often help us find the problem faster.)
