### ISSUE TITLE
Weird Behavior with Lava Includes

### ISSUE THREAD

**Issue by mkinyon** [SparkDevNetwork/Rock#4084]
### Description
_Submitted on behalf of River Valley Church_

We have observed some strange behavior with lava variables within a lava file (using **{% include'' %}** ) where the variable is occasionally returning the wrong results.  This only occurs when the page (containing the lava) is loaded simultaneously from multiple users or from multiple browser tabs.  Here is an example of some lava that was affected by this:

![image](https://user-images.githubusercontent.com/2349102/73379626-d4ff4380-427f-11ea-8d1a-2aa512a84ede.png)

The **TotalAllFunds** variable in this example will occasionally output the wrong total.

Correct Results:
![image](https://user-images.githubusercontent.com/2349102/73380015-87370b00-4280-11ea-9caf-2d4de9a03617.png)

Incorrect Results:
![image](https://user-images.githubusercontent.com/2349102/73380018-8900ce80-4280-11ea-9ba2-ded518798f0f.png)

I'm not sure if this should be classified as a bug or if there should be a note about this in the lava documentation but I thought I would at least bring it to your attention.

### Steps to Reproduce
**_NOTE: I have a working example of this issue on the Rock Demo site located right_** [**_https://rock.rocksolidchurchdemo.com/page/462?PersonGuid=1ea811bb-3118-42d1-b020-32a82bc8081a&StatementYear=2018 HERE_** ]()**_. Just open the link and continue with step 4._**

1. Add this lava file to the Rock themes folder.  (The file extension will need to be changed to .lava first.) This lava file contains the default lava for the Contributions Statement Lava block except there is some additional lava to add a Total to the account summary. [ContributionLava.txt ](https://github.com/SparkDevNetwork/Rock/files/4129221/ContributionLava.txt)
1.  Open the internal [Contribution Statements ](https://rock.rocksolidchurchdemo.com/page/462?PersonGuid=1ea811bb-3118-42d1-b020-32a82bc8081a&amp;StatementYear=2018) page.
1.  Update the lava template to load the file we uploaded in step 1. ![image](https://user-images.githubusercontent.com/2349102/73375881-bd24c100-4279-11ea-8fd3-442a2b5e148d.png)
1. Now open the page in two separate tabs and try refreshing them at the same time.  It will take a couple attempts but it doesn't take long to see incorrect totals.

**Expected behavior:**
The expectation behavior is for the TotalAllFunds lava variable to be accurate.

**Actual behavior:**
The actual behavior is that the TotalAllFunds lava variable is sometimes inaccurate

### Versions
* **Rock Version:** 8.8, 10.1
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
@mkinyon So this **only** happens when using the include statement? Meaning if you move the contents of the file directly into the block configuration it works correctly?

**Comment by mkinyon** [comment]
@cabal95 That is correct.

**Comment by JimMichael** [comment]
Will this fix be in 10.2?

**Comment by nairdo** [comment]
Sorry, Jim @JimMichael We're working out the details** for a fix in that semi-temporary branch... but to answer your question, it will be based on the riskiness of the solution.  At the moment, I'm leaning toward v11 so we can get this on our server for a much longer period of time. 

_** We'll adjust our process so we don't tag the "Fixes ####" in these temporary branches next time._

**Comment by briankalwat** [comment]
This could be completely unrelated, but we're seeing some strange things as of pulling in `11.0.10` & `11.0.11`. Specifically using a lava include in a shortcode that has an entity command in it throws `The Lava command 'rockentity' is not configured for this template.` even though the command is enabled on the shortcode. This is has worked up until merging in those two most recent prealphas.

**Comment by nairdo** [comment]
Brian, we're investigating this.
