### ISSUE TITLE
Schedule doesn't display recurrence properly

### ISSUE THREAD

**Issue by bengoshow** [SparkDevNetwork/Rock#4087]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Scheduling an event occurence to repeat on the "First and Third Tuesday of every Month". The schedule display on both back end and front end only includes "First Tuesday of every Month"

**Expected behavior:**

Scheduling an event occurence to repeat on the "First and Third Tuesday of every Month". 

**Actual behavior:**

The schedule display on both back end and front end only includes "First Tuesday of every Month"

### Versions

* **Rock Version:** 1.9.4.1
* **Client Culture Setting:** en-US

**Comment by tstephens17** [comment]
https://github.com/SparkDevNetwork/Rock/issues/3906

**Comment by bengoshow** [comment]
Already resolved in #3906
