### ISSUE TITLE
[Proposal] New Lava Filter EntityFromCachedObject

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4089]
## Proposal

This proposal is for a new Lava filter that would allow the user to turn a Cached object into a real Entity object.

In v10, a bug was fixed that caused the `Attribute` filter to not return cached objects. While this is a good thing, it does make some things harder to do in Lava. Suppose we have this Lava:

```
{% assign Campus = Workflow | Attribute:'Campus','Object' %}
{{ Campus.Location.FormattedAddress }}
```

On v10 it will not work because the campus object returned is actually a cached object that only has a bare-bones `Location` property. Currently the way around this would be to use Entity commands to load the campus and then traverse it's properties, but that is a rather unfriendly way to do things.

The proposal would be that this new Lava filter would take in an object and if it is an `IEntityCache` object then it would use a little magical Reflection to determine the actual entity type and then load and return that entity from the database.  If the incoming object is not `IEntityCache` then the original object would be returned. In other words, if you pass in a real `IEntity` object then you will get back a real `IEntity object still. But if you pass in an `IEntityCache` object, you will get a real `IEntity` object back.

```
{% assign Campus = Workflow | Attribute:'Campus','Object' | EntityFromCachedObject %}
{{ Campus.Location.FormattedAddress }}
```

## Pull Request

If this proposal is approved, I can build up and submit a pull request for this functionality. Just want to verify the concept before I start coding something.

## Input Needed

I don't really care for the filter name, but haven't come up with a better one yet.

**Comment by jonedmiston** [comment]
Approved.

**Comment by JimMichael** [comment]
I vote for _Objectify_ 🤓

**Comment by cabal95** [comment]
_Objectively_ denied. Jon was good with the filter name as is so I'll go that route.
