### ISSUE TITLE
[10.1] Viewing Communication Details times out on large communications

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4093]
### Description
Since our upgrade to 10.1, which introduced a new Communication Detail block, we get SQL timeout exceptions when attempting to view large communications. In this case, about 8,000 recipients. We have tested this with multiple communications to ensure it wasn't just something odd with a single communication.

I tried upping the database timeout for that query to 600 seconds and it still timed out after 10 minutes.

I also found a communication that went to about 4,000 people and that one loaded - though it did take 107 seconds for the page to load.

Confirmed by Crista on Slack, they are having the problem too with a ~6,000~ 6,500 recipient e-mail (also on 10.1).

### Steps to Reproduce
1. Send (or simulate) sending an e-mail to 8,000 people.
1. Try to view the communication from the history tool after it has sent.
1. See error

**Expected behavior:**

The communication should display, even if the recipients tab is unavailable due to a SQL error.

**Actual behavior:**

I get a big fat error page.

![Screenshot!UNITO-UNDERSCORE!2020-02-04 Rock - Error](https://user-images.githubusercontent.com/1119863/73771154-a5928000-4732-11ea-81e3-c63f3bd71ffb.png)

### Versions
* **Rock Version:** 10.1
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
Confirmed on a 12k email here.

**Comment by jonedmiston** [comment]
This is something we are working on. Our plan is to make the page to support a larger number of records, but we'll also add a block setting of `Max Communications To View`. If the communication has more than that number of recipients it will only show the basic communication details.

**Comment by cabal95** [comment]
Thanks @jonedmiston. Just as an added note since it wasn't stated in the original  issue, we just ran into this again today in a more pressing manner. The original issue was they were trying to look at an old communication so they could send to the same list of people. We worked around that by getting them to do it the right way (DataView or something) anyway.

However, we now have a pending communication of 8,000 recipients waiting to be approved that we cannot send. So this is likely to hit some of us larger churches in a bad way beyond just not being able to look at older communications. For a short term fix, I think i'm going to try to implement the second half of what you mentioned in a quick fix which is skip binding the recipient grid if the number of recipients is >1,000 or so.

**Comment by jonedmiston** [comment]
OK will implement part two as soon as possible

**Comment by JimMichael** [comment]
Just curious... is this problem related to this change https://github.com/SparkDevNetwork/Rock/issues/4063 which got rid of the analytics page altogether and moved them into each communication?

**Comment by cabal95** [comment]
My short-term fix (probably not implemented correctly/safely, but whatever) did work, FYI. So if somebody else hits a brick wall with this I can send over instructions for my quick fix change.

**Comment by charlottedean** [comment]
I also receive timeouts/errors when trying to copy the communication that was sent.  My list is 8,000+
