### ISSUE TITLE
Using event form filter option prohibits display of person attribute current value

### ISSUE THREAD

**Issue by jennifertroeger** [SparkDevNetwork/Rock#4099]
### Description
Using the filter option on an event registration form, combined with the use of a subsequent person attribute question using "current value" results in the current value not displaying as it should. When the filter is removed from the equation, the current value correctly displays in the response field.

(Noteworthy: I confirmed this on the demo site, but my current production is on v9.3. In my production environment the current value will properly display for two subsequent person attribute questions, but not more than that. The demo site will not display current values for any.)

### Steps to Reproduce
1. Populate a specific person attribute on your test profile.
1. Create an event registration template (and instance).
1. In the registrant form, create a question with a boolean response field. (e.g. Do you want to provide more information?)
1. In the registration form, create a subsequent person attribute question using the pre-populated attribute, select "use current value" and then set the filter of that question to display based on a "yes" response from the previous question.
![image](https://user-images.githubusercontent.com/383807/79400225-77070180-7f3a-11ea-9ebe-714437c82113.png)
![image](https://user-images.githubusercontent.com/383807/79400228-7a9a8880-7f3a-11ea-9a83-9c5bc9829835.png)

1. Test the registration and respond with "yes" to the filter question in order to display the subsequent question and corresponding current value on file.
![image](https://user-images.githubusercontent.com/383807/79400237-7f5f3c80-7f3a-11ea-91db-15ab39df98a2.png)

1. Go back to your registration form and remove the filter setting from the person attribute question (keep "use current value"). Save and re-test.

**Expected behavior:**

The expected behavior is that the current value of the person attribute will auto-populate in the response field, regardless of a filter setting on that question.

**Actual behavior:**

The actual behavior is the response field remains empty (not displaying the current value) when the question uses a filter. If the filter setting is removed from the equation, the current person attribute value correctly populates the field.

### Versions
* **Rock Version:** Rock McKinley 10.1 (1.10.1.4)  (demo site)
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
This was fixed v10.4 in commit 60feb6bc07dead18e7fbbb6445f14b528e635a4e.
