### ISSUE TITLE
Registration: "Show Family Members" Not Working for Single Registrant Scenario

### ISSUE THREAD

**Issue by edcylam** [SparkDevNetwork/Rock#4101]
### Description
When a registration template only allows registration for a single registrant and has "Show Family Members' checked, the "Family Member to Register" dropdown doesn't show up.

### Steps to Reproduce 
1. Set up a registration template with these options in the Details section

* Allow Multiple Registrants = unchecked
* Registrants in the Same Family = Yes
* Show Family Members = checked

**Expected behavior:**

The "Family Member to Register" dropdown would appear on the form (example screenshot from v8.9).
![image](https://user-images.githubusercontent.com/383807/75480363-5f5dc480-595e-11ea-941f-413d0784b313.png)

**Actual behavior:**

The dropdown doesn't appear. The workaround is to check "Allow Multiple Registrants."

![image](https://user-images.githubusercontent.com/383807/75480438-8b794580-595e-11ea-9b42-ad7301c471c0.png)

### Versions
* **Rock Version:** 9.4
* **Client Culture Setting:** en-us

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1176598525679247">RegistrationEntry Registrant Paths.xlsx</a>

**Comment by JesseM-PC** [comment]
We are seeing this issue as well. On 9.3, 9.4, and 10.1. Verified it on the demo server. I thought it was related to #3874 but that was using multiple registrants.

**Comment by nairdo** [comment]
I can double check with the product owner team, but I believe it is only supposed to show you someone other than the current person if you set "Registrants In Same Family" to "Ask":

![image](https://user-images.githubusercontent.com/383807/75480898-56b9be00-595f-11ea-9dee-fc692541f6f8.png)


![image](https://user-images.githubusercontent.com/383807/75480797-24a85c00-595f-11ea-9ea4-33da12ba3dee.png)
