### ISSUE TITLE
Days Until Birthday Report Field Fails On Feb 29 Birthdays

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4105]
### Description
The _Days Until Birthday_ field on reports returns inaccurate results when the person's birthday is on Feb 29

### Steps to Reproduce
1. Create a report that shows a person with a birthday on Feb 29
1. Add Days until Birthday column
1. Observe that it appears to add 365 days to the _actual_ days until birthday.

For example, on demo on 2020-02-11 I get:
![image](https://user-images.githubusercontent.com/3903408/74288623-84adca00-4cf2-11ea-954a-368c70afbc00.png)

**Expected behavior:**

Accurate Days Until Birthday would be reported for people with a leap year bday.

**Actual behavior:**

It's wrong.

### Versions
* **Rock Version:** 9.4, 10.1

**Comment by nairdo** [comment]
@JimMichael It looks like the Person's DaysUntilBirthday computed column has a bug for leap day.  And I don't think we can get it fixed in time for this leap year :(

It appears that the _second_ case in the computed column intended to check for the ISDATE to be `= (1)` instead of `= (0)`:

```Sql
...
WHEN [BirthMonth] = (2)
   AND [BirthDay] = (29)
   AND isdate(CONVERT([varchar](4), datepart(year, dateadd(year, (1), sysdatetime()))) + '-02-29') = (1)
   ---  at the end of this line above                                                                ^^^
   THEN datediff(day, sysdatetime(), CONVERT([date], CONVERT([varchar](4), datepart(year, dateadd(year, (1), sysdatetime()))) + '-02-28'))
...
```

**Comment by JimMichael** [comment]
No worries, Nick! A staff person just happened to notice it and I thought it was the perfect time to report it since we’re already in a leap year :-)

**Comment by crayzd92** [comment]
This will be fixed via migration script in v14
