### ISSUE TITLE
Family Attributes in Public Profile Edit Block Does Not Work

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4108]
### Description
The **Public Profile Edit** block has a Family Attributes setting to expose them for editing. This feature does not seem to work.

### Steps to Reproduce
1. Verify the Family Group Type has at least one Group Attribute.
1. Go to /MyAccount on public website
1. Edit the Public Profile Edit block [settings] and try to enter an attribute name into the **Family Attributes** box.
1. Observe that no attributes are found to add.

**Expected behavior:**

Family Attributes would be choose-able in the block settings and editable on the page.

**Actual behavior:**

No family attributes are found. Verified on demo and prealpha. I also verified it's not a rights issue by giving All Users VIew+Edit rights to the family attribute.

### Versions
***Rock Version:** 9.4, 10.1, prealpha

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1162288533054819">image.png</a>

**Comment by JRichmond27** [comment]
I have confirmed the same results in our production install (v9.4) and on the demo site.
