### ISSUE TITLE
"Subject" Used Inconsistently in Communication List Block

### ISSUE THREAD

**Issue by sichiriu** [SparkDevNetwork/Rock#4110]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
The term "subject" appears to be used inconsistently in the Communication List block. In the filters, "subject" refers to the actual subject of the Communication, while in the grid it refers to the Communication Name.

![](https://user-images.githubusercontent.com/10267139/74557387-e9486f00-4f14-11ea-9976-b80eae00af1b.png)

### Steps to Reproduce
1. Go to the Communication History page.
1. Filter by Subject and note that filtering is by subject.
1. View the grid and observe that the Subject column actually shows the Communication Name.

**Expected behavior:**

The term "subject" is used consistently in both spots of the block.

It'd also be great if there were an option to filter by Communication Name, but that fits better as an Idea — I'll add something there. ;)

**Actual behavior:**

The column header in the grid says "Subject" but actually displays the Communication Name.

### Versions
* **Rock Version:** Rock McKinley 9.4 (1.9.4.1)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Hi Steven @sichiriu , Although that column is loosly the "Subject" we made a recent change (https://github.com/SparkDevNetwork/Rock/commit/f5a20728) for the v11 release to use the Subject if available, or PushTitle if available, or communication Name in that order.  Hopefully that resolves this issue for you since we don't really want to change the name of the column.

**Comment by sichiriu** [comment]
Thanks, @nairdo! That change definitely fixes the issue.
