### ISSUE TITLE
iCal events with RDATE but not RRULE (Non-recurring) do not display in Office 365

### ISSUE THREAD

**Issue by OnlyByGrace** [SparkDevNetwork/Rock#4112]
### Description
When the iCal feed is generated for event item occurrences that follow a "Specific Dates" occurrence pattern, those iCal feeds do not display correctly in Office 365 calendars because of the behavior described here:

[https://support.microsoft.com/en-us/help/2643084/outlook-receives-a-message-that-has-an-attachment-that-is-named-not-su](https://support.microsoft.com/en-us/help/2643084/outlook-receives-a-message-that-has-an-attachment-that-is-named-not-su)

(See a suggested fix at the end)

### Steps to Reproduce
1. Create an event item on the public calendar in Rock
1. Create an event item occurrence that has an occurrence pattern as follows:

![<a href="https://user-images.githubusercontent.com/5644394/74683134-f758f280-5195-11ea-90e5-428fa31dd362.png">https://user-images.githubusercontent.com/5644394/74683134-f758f280-5195-11ea-90e5-428fa31dd362.png</a> image]()

1. Click "Export Calendar Feed" on the public calendar and import it into Outlook/Outlook online.
1. The event does not show on the Outlook calendar.

**Expected behavior:**

The event should show.

**Actual behavior:**

It does not.

** Suggested fix **

Adding the following lines around line 147 of GetEventCalendarFeed.cs will add an innocuous RRULE (only if an RDATE rule exists, and no RRULE already exists) that causes Outlook to acknowledge the RDATE rule.

```
if (ievent.RecurrenceRules.Count == 0 && ievent.RecurrenceDates.Count > 0)
{
   ievent.RecurrenceRules.Add(new RecurrencePattern("FREQ=DAILY;COUNT=1"));
}
```

### Versions
* **Rock Version:** Rock McKinley 10.1 (1.10.1.4)
* **Client Culture Setting:** en-US

**Comment by OnlyByGrace** [comment]
Update on this, my proposed fix doesn't seem to have any effect in Outlook online. It does appear to fix the issue on Outlook for desktop.

**Comment by rutledgek** [comment]
Just to add, the appears to be an issue with ICal as well.  I came from the Non-Recurring events issue. If you save the event as a recurring event that ends after once and then save it back to a single event, the event will appear in the feed.
