### ISSUE TITLE
Top Person Signal Badge Ignores Expiration Date

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/Rock#4113]
### Description
Setting an expiration date on a person signal does not cause the Top Signal Badge to go away, even after running the Calculate Person Signals job. 

I don't know how it works under the hood, so not sure if this is a bug with the Badge or with the Job.

### Steps to Reproduce
1. Add a signal without an expiration date to a person
1. Run the Calculate Person Signals job
1. Reload the person's profile to verify the Top Signal Badge shows up
1. Edit the signal and add an expiration date in the past
1. Run the Calculate Person Signals job again
1. Reload the person's profile and notice that the Top Signals Badge is still there

**Expected behavior:**

After adding an expiration date to a signal, I expect the Top Signal Badge to go away (assuming the person doesn't have any other signals.)

**Actual behavior:**

The Top Signal Badge continues to display as if the expired signal was still active.

### Versions
* **Rock Version:** Rock McKinley 9.4 (1.9.4.1)
* **Client Culture Setting:** en-US

**Comment by MichaelAllen** [comment]
The Calculate Signals job is just calling `CalculateSignals()` on each person to do the actual update of the person's `TopSignalId`, `TopSignalIconCssClass`, and `TopSignalColor` so I think the problem is with that method not taking signal expiration dates into account.

**Comment by JRichmond27** [comment]
Posted a possible workaround in Rock Chat: https://chat.rockrms.com/channel/sql?msg=RXokMjjQA8PZ4o8Ac
