### ISSUE TITLE
Assessment Results errors after merging people

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#4114]
### Description
Filed on behalf of Bridgepoint Church

If a person takes an assessment and is then merged with another person, the results are still there as attribute values however the results don't show internally or externally.

Internally, clicking on the icon in the badge bar you get this error:
![image](https://user-images.githubusercontent.com/12735965/74854494-07dbab00-5305-11ea-90ee-20fb5925d842.png)

Externally, if Helen logs into the My Account page, it shows the assessment as taken but when you click the link to view results it starts the assessment over.
![image](https://user-images.githubusercontent.com/12735965/74854617-335e9580-5305-11ea-8fb9-eb854fd2c705.png)
![image](https://user-images.githubusercontent.com/12735965/74854668-42ddde80-5305-11ea-8bab-1720be27fd06.png)

### Steps to Reproduce
1. Created a duplicate person record for Helen Evans
1. Log into the external site as Helen #2 
1. Take an assessment
1. Merge the 2 Helen Evans records
1. Try to view Helen's results while logged in as admin
1. Log into the external site as Helen and try to view her results

**Expected behavior:**

The results from Helen would be visible both internally and externally after a merge

**Actual behavior:**

The attributes are there and appear on the Extended Attributes tab. They are not recognized by the assessment block. I only tested the Spiritual Gifts and the Motivators Assessments.

### Versions
* **Rock Version:** [10.1]
* **Client Culture Setting:** [en-us]

**Comment by jbgarrett12** [comment]
I can confirm this is happening on our rock instance as well.
