### ISSUE TITLE
Registration Fee Required with Quantity Validation Error (Firefox browser)

### ISSUE THREAD

**Issue by aaronjones8** [SparkDevNetwork/Rock#4118]
### Description
_none provided_

### Steps to Reproduce
1. Add Registration Fee and mark as required and enable quantity
1. On Registration, enter value for fee and it fails on validation

**Expected behavior:**

Should pass validation check if quantity is placed in fee (saw bug fix that said this was fixed in 9.2 so it may have been reintroduced in later update)

**Actual behavior:**
Fails to pass validation

### Versions
* **Rock Version:** [10.1]
* **Client Culture Setting:** [en-US

![registrationBug](https://user-images.githubusercontent.com/13666106/74949194-679c8980-53cb-11ea-8d39-a5a4e10877fd.png)

**Comment by ethan-sparkdevnetwork** [comment]
@aaronjones8 I tested this featured in released and unreleased versions higher than 10.0 and was unable to reproduce the behavior. Can you give me the reproduction steps?

**Comment by markewampler** [comment]
@ethan-sparkdevnetwork try on firefox.  We only see this happen on firefox.  Chrome, Safari work great.

**Comment by markewampler** [comment]
@ethan-sparkdevnetwork just updated on our dev environment to the 10.3 Alpha and still experiencing this bug as an FYI

**Comment by ethan-sparkdevnetwork** [comment]
@markewampler The JS might be cached on the browser. Can you clear that out and try again? You can search for this function in the RockUi.js library:
`
clientValidate: function (validator, args)
      {
        var $numberUpDownGroup = $(validator).closest('.js-number-up-down-group');
        var isValid = true;

        if ($numberUpDownGroup.hasClass('required') === true) {
          isValid = false;

          $numberUpDownGroup.find('.js-number-up-down-lbl').each(function (i) {
            if (parseInt(this.innerText, 10) > 0) {
              isValid = true;
            }
          });
        }
`
