### ISSUE TITLE
Reporting on known relationships for deceased individuals

### ISSUE THREAD

**Issue by kraborn** [SparkDevNetwork/Rock#4120]
### Description
I would like to run a report on deceased individuals and display known relationships as a field in the report. The field column "related people" appears in the report but no data is displayed even though the deceased individual has individuals on his/her person record listed under "Known Relationships" with a type of "survived by."

This issue was also identified in Issue #3019 (https://github.com/SparkDevNetwork/Rock/issues/3019) but closed and referred to the Slack community. 

![image](https://user-images.githubusercontent.com/61284969/74983118-10161200-53fb-11ea-9af9-ea107c594583.png)

![image](https://user-images.githubusercontent.com/61284969/74983149-1efcc480-53fb-11ea-9940-d38361433f05.png)

![image](https://user-images.githubusercontent.com/61284969/74983195-2d4ae080-53fb-11ea-924e-d567968d081e.png)

### Steps to Reproduce
1. Go to Tools. 
1. Click on Reports.
1. Click on a Category and click the "+Report" button.
1. Complete the required fields. For "applies to," select person.
1. Choose to filter by a data view that retrieves deceased individuals (who have known relationships of the type "survived by") using the filter "inactive record reason is 'deceased.' " 
1. In the fields section, click the "+ Add Field" button.
1. Click on the Field Type dropdown menu, scroll to the "Relationships" section and select "Related People."
1. Under the "Include Known Relationship Types" section, select "Survived by."
1. Under Output Format, use default "Person Name and Relationship." 
1. .Click "Save" and view report results. 
1. ."Related People" column header displays but results do not appear.

**Expected behavior:**

I expected the report to display in the field column "related people" the names and relationship types of other persons who had known relationships of "survived by" in reference to the deceased individual. 

**Actual behavior:**

The "related people" field column appears in the report but no data is displayed even though the deceased individual has individuals on his/her person record listed under "Known Relationships" with a type of "survived by."

### Versions
* **Rock Version:** [10.1]
* **Client Culture Setting:** [en-us]

**Comment by JimMichael** [comment]
I can confirm that the Related People field type in a report returns no relationships for deceased people, regardless of which relationship it is. We need clarification if this is Working As Intended, or a bug. I'm all for Rock suppressing the accidental/unintended exposing of deceased people, especially in public-facing ways, but I'd *think* that if you query the db for specific information it should return it and not hide it from you.

**Comment by nairdo** [comment]
Until v11 (with the fix mentioned in #3821) you cannot consistently build a data view of deceased people because various data filters will automatically filter them out.  With v11, you will be able to use the new "Include Deceased" option and then you can add a filter to only show deceased people (if that's what you're after).

![image](https://user-images.githubusercontent.com/383807/75059566-7c941e00-549a-11ea-8986-677117b6f53b.png)

The RelatedPeople (report selection) is also being updated so that it will also include deceased people.  With that additional change, a similar report can be made showing deceased people and their parents names as seen in my working example:

![image](https://user-images.githubusercontent.com/383807/75060702-8d459380-549c-11ea-8009-b41598e90fd1.png)

**Comment by kraborn** [comment]
nairdo, thank you for the update!

**Comment by karenn-ccbc** [comment]
The ability to "include deceased" in a dataview works and allows for known relationship of survivor to be used in reports. However, the reverse does not work. Pulling a report of Widows and wanting to show the inverse (deceased records) as a related person/known relationship in a report will not display that related person who is deceased.
![image](https://github.com/SparkDevNetwork/Rock/assets/35667472/e7d52cad-19cf-4931-83b3-c7c7e56fb997)

![image](https://github.com/SparkDevNetwork/Rock/assets/35667472/826ecb7f-21e3-48ca-8333-f9e9aa35bdb5)
