### ISSUE TITLE
Group Member Waivers of minors do not send to Parents

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4122]
### Description
With Event Registration, if you have a required waiver sent by e-mail and the registrant is a minor, it will send the e-mail to the person registering the kid. **Usually** this is the parent, but not always.

With that logic in place, we noticed an issue with **Groups** that have required signature documents. The logic in the GroupMemberEdit block (maybe other related places) when you click the `Send Signature Request` button will just send to the person you are viewing. So in our case, we have a play we are doing with a number of children participating and we need the parents to sign. Since many of these kids don't have an e-mail address we don't have an easy way to send these out.

### Steps to Reproduce
1. Configure a group to have a required signed document.
1. Add a minor without an e-mail address (but whose parent has an e-mail address).
1. Click the `Send Signature Request` button.
1. See error about no e-mail on file.

**Expected behavior:**

To be honest I'm not 100% sure. The functionality should be more consistent across the app, but I'm not sure how to achieve that. But I think we need some kind of setting _somewhere_ that dictates who gets a signed document request by default. Emphasis on _default_, so for example Event Registration could decide to override that logic.

Maybe a Global Attribute that defines options for Signed Waivers For Minors like:

1. Send to Minor only.
1. Send to First-Parent-With-Active-Email only.
1. Send to First-Parent-With-Active-Email if Minor does not have active email.

If the only time this were an issue was with a person at the keyboard, I would say a UI popup that asks how the waiver should be sent (assigned). But since, I'm sure, this happens automatically in the background when a person is synced into a group for example, that makes it difficult.

More difficult because a child can have more than 1 parent... more than 2 if we talk about multiple families... and it might be difficult to figure out which parent to send the waiver to... Send it to "dad" and maybe it never gets signed.

**Actual behavior:**

Waiver no go and we have to manually send out the waivers one at a time.

### Versions
* **Rock Version:** 10.1
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
@nairdo I'm not marking this as a bug yet as I don't know whether to call it a bug or a "required enhancement". When you have a chance to review, please mark accordingly.

**Comment by nairdo** [comment]
[This is more for the community and less for Daniel since @cabal95 is now on the core team.  Therefore, if this feature is desired by you then please read on...]

We discussed this earlier this week and ended up landing on this being a bit too far out of the scope of the original intent of the feature.  What you're suggesting is not outlandish, it's just something we're considering a feature request -- and because of that we would like to have you (if you're still interested in that feature) opened up on the rockrms.com/Ideas board.
