### ISSUE TITLE
Groupmember restore doesn't bring notes over

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#4125]
### Description
If you archive a groupmember in a group and then restore them without a group history job running you lose data about the groupmember.  In our case notes on the groupmember.

If you run group history it does track that data and restores the notes data though.

### Steps to Reproduce
1. Navigate to a group that has history turned on
1. Write a Note
1. Run Group History Job
1. Archive the groupmember
1. restore the groupmember
1. look at notes

**Expected behavior:**

Notes should carry over

**Actual behavior:**

notes go bye-bye

### Versions
* **Rock Version:** [10.2]
* **Client Culture Setting:** [en-us]

**Comment by nairdo** [comment]
We attempted to reproduce this with a developer and with the alpha testing team but were unable.  We then reviewed this this with Mark and we concluded that perhaps they restored the user as a different role in the group (which would not bring back notes from the original member-role record).  Regardless, if you restore the original group member role record all the notes do get restored.
