### ISSUE TITLE
Root Route Issue with Logout Query String and Logout Block

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#4129]
### Description
We currently have the homepage of our website (newspring.cc) set to be the default page of the site. With that setup, visiting something like `https://newspring.cc/account?logout=true` currently returns you to `/page/1400`

* the page id of the homepage, rather than just the root domain `https://newspring.cc`.

See the following thread for discussion revolving around this topic: https://chat.rockrms.com/channel/cms?msg=mJhcCgKG6Zaw2Rcwx

### Steps to Reproduce
1. Go to https://rockrmslatest.com/MyAccount
1. Sign in
1. Go to https://rockrmslatest.com/MyAccount?logout=true
1. Rock redirects to /page/1 instead of just `https://rockrmslatest.com`

**Expected behavior:**

Rock should redirect to the root domain of the site if you have set the default page to be the root page.

**Actual behavior:**

Rock redirects to the page id of the default page, because no explicit route has been set in page properties. There is no way (that I am aware of) to set a page route of `/`.

### Versions
* **Rock Version:** 11.0.10
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
This happens on our production 10.1 instance too.

**Comment by JimMichael** [comment]
We noticed that, too, and gave our homepage a route of /home so it didn't look quite so bad. But it would be great to get it fixed.
