### ISSUE TITLE
SMS Conversations is not saving preferences (and thus times out)

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4131]
Submitted on behalf of [Sun Valley Church ](https://www.sunvalleycc.com/)

### Description
Even though the SMS Conversations block has code to use and set user preferences for the selected "From Number" and the option to view unread vs. all messages, changing those options is not getting saved correctly as a user preference so that the next time a user views the block, the same options are used.

This can render the block unusable if the first From Number happens to be a heavily used number with a lot of messages. Because block always reverts to showing all messages (vs. just the unread messages) the block will frequently time out or take significant time to render. If a specific number and the option to only show unread messages would be remembered, then users could use the block without it timing out.

It does retain settings during the same browser session, but if you close browser and return to page, it reverts back to default of first number and showing all messages.

### Steps to Reproduce
1. Make sure you have more than one SMS From number.
1. Go to the SMS Conversations block.
1. Change the From Number to second option
1. Click the Gear icon and change "Show Read Messages" to "No"
1. Close all browser instances (to start new session)
1. Return to SMS Conversations block

**Expected behavior:**

Page retains the selected From number and "Show Read Messages" option

**Actual behavior:**

Page reverts back to using first From number and showing all messages.

### Versions
* **Rock Version:** 10.1 (1.10.1.4)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1164182888092011">Rocket.Chat_2020-02-28_13-16-01.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1164182888092013">Rocket.Chat_2020-02-28_13-16-15.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1164182888092015">Rocket.Chat_2020-02-28_13-16-28.png</a>

**Comment by azturner** [comment]
This looks like it might be due to the SaveSettings() method setting the user preferences, but never saving them: https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Communication/SmsConversations.ascx.cs#L356

**Comment by ethan-sparkdevnetwork** [comment]
@azturner We can save the preferences but I am wondering about a possible performance issue here. Can you provide some insights on the amount of data?

**Comment by azturner** [comment]
@ethan-sparkdevnetwork, The query created by the [GetCommunicationsAndResponseRecipients()](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/CommunicationResponseService.partial.cs#L577) method for their first number is currently returning 925 records and takes about 30 seconds to run. All of that time appears to be in that grouping statement (the query inside the CTE takes less than a second to run and returns 1880 records). This particular number has a lot of responses because it was used to send a Christmas Service invite to a large number of recipients.

**Comment by ethan-sparkdevnetwork** [comment]
Discussed this with David via Rocket Chat. We did some experimenting with the data and query and I was able to speed it up quite a bit, from 30 sec to 1 sec. So performance when displaying the conversations in the left pane has been improved.
