### ISSUE TITLE
Commented-Out Lava Still Tries to Parse?

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4132]
### Description

Not sure if this is Working As Designed, or a bug, but it's weird and unexpected.

### Steps to Reproduce

1. Go to Lava Tester
2. Enter ```{% comment %}
            {% elseif image != '' %}
              do stuff
{% endcomment %}```

3. Observe the `Error resolving Lava merge fields: Unknown tag 'elseif' ` result

**Expected behavior:**

I was expecting that any of the text/Lava between `{% comment %}` and `{% endcomment %}` would be completely ignored.

**Actual behavior:**

It seems that the Lava engine still tries to parse the tags within the comment/endcomment and in this case fails because there is no `{% if %}` and `{% endif %}` tags. If this is NOT a bug and working as intended, then it really diminishes the utility of commenting-out Lava code, such as in this example where I was trying to remove just one `{% elseif %}` from a long list of them.

### Versions

* **Rock Version:** All

**Comment by nairdo** [comment]
I'm not sure about that @JimMichael...  I'm pretty sure only the raw/endraw ignores Lava. (See https://community.rockrms.com/lava/tags/raw-tags)

**Comment by JimMichael** [comment]
Ah, ok. Maybe the description of **In a sense the comment tag swallows up any content that's inside it so it will never be seen again... ** on https://community.rockrms.com/lava/tags/comment-tags should be updated, then?

**Comment by nairdo** [comment]
I did just double-check the underlying DotLiquid engine to confirm.  I also updated our documentation and mentioned the work-around: https://community.rockrms.com/lava/tags/comment-tags
