### ISSUE TITLE
Event Registrations Do Not Allow Editing When Auto Applying Discount

### ISSUE THREAD

**Issue by bradcerb** [SparkDevNetwork/Rock#4133]
### Description
If you set a discount to auto apply in an event registration, you are unable to edit the discount code field when completing an event registration.

![image](https://user-images.githubusercontent.com/36978982/75353475-7d9dc480-5879-11ea-9a91-3a1ee70d5258.png)

As you can see, the **contenteditable** property is set to _false_. It should be set to _true_.

![image](https://user-images.githubusercontent.com/36978982/75353560-9efeb080-5879-11ea-84ac-1b19252e20f1.png)

### Steps to Reproduce
1. Go to an Event Registration Template
1. Add a Auto-Apply Discount
1. Complete the Event Registration
1. ~~See error~~

**Expected behavior:**

Registrants should be able to edit an auto apply discount and the **contenteditable** property should be set to true. For example, a camp registrant might be given an early-bird discount that is auto-applied if registering within a certain window. However, if we give out a scholarship or promo code, they should be able to override the auto-apply discount.

**Actual behavior:**

Registrants are unable to edit an auto apply discount and the **contenteditable** property is set to false.

### Versions
* **Rock Version:** 10.1
* **Client Culture Setting:** en-us

**Comment by nairdo** [comment]
Hi @bradcerb after doing more research on this item, we can say the original auto-apply discount feature was never editable, nor was it the intent of the original feature.   Your enhancement idea **does have merit**, so we'd like to have you suggest it on the official "ideas" board over at https://community.rockrms.com/ideas where others can vote.  Thanks for helping make Rock better!

**Comment by bradcerb** [comment]
@nairdo Sounds good! Thanks and I'll make sure to add it to the "ideas" board.
