### ISSUE TITLE
Event Wizard missing Default Payment Amount

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4134]
### Description
When using the Event Wizard to create a new Registration Instance, there are fields for `Cost` and `Minimum Initial Payment`, but not for the new `Default Payment Amount` option that is available. This should probably exist.

I'm marking this initially as a bug in that I'm assuming it was meant to be there and just missed when the field was added.

### Steps to Reproduce
1. Create a Registration Template with cost set to be on the Instance.
1. Go to the Event Wizard
1. Select that Registration Template and move to the Instance page.
1. Notice missing field.

**Expected behavior:**

Default Payment Amount should be present.

**Actual behavior:**

It's not.

### Versions
* **Rock Version:** 10.1
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
![Capture](https://user-images.githubusercontent.com/1119863/75372201-00744e80-587d-11ea-867f-dfe946e30fcc.PNG)

**Comment by cabal95** [comment]
We also noticed that if the Registration Template is setup to have the Cost on the Template instead of the instance, the `Account` field does not show up in the Wizard - even though it's a required field when manually adding/editing an instance.

**Comment by shauncummings** [comment]
> We also noticed that if the Registration Template is setup to have the Cost on the Template instead of the instance, the `Account` field does not show up in the Wizard - even though it's a required field when manually adding/editing an instance.

I believe this is a separate issue and will be addressed separately.  I am closing this issue as the primary item has been addressed.
