### ISSUE TITLE
Copying Communication Templates does not honor security

### ISSUE THREAD

**Issue by karenn-ccbc** [SparkDevNetwork/Rock#4138]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When a staff person has edit and administrate rights to communications templates so that they can manage their templates in My Settings. If they Copy a template to rename and make minor changes, the copy of the communication template does not inherit their security and show up in their list of communication templates to be able to edit it. It goes into the primary list of communication templates under COPY.

### Steps to Reproduce
1. Go to https://rock.rocksolidchurchdemo.com/page/274
1. Create a new template and set security to Cindy Decker to edit and administrate.
1. Login as Cindy Decker and view my Settings- Communication Templates.
![image](https://user-images.githubusercontent.com/35667472/75490930-a8bc0d00-597a-11ea-96bf-8564a35ae358.png)
1. Copy the communication.
1. Notice that Cindy cannot see the copied communication that she made. It is in the Communications Templates as a copy, but did not inherit her permissions to edit or administrate it or even view it in her Settings.
![image](https://user-images.githubusercontent.com/35667472/75490945-aeb1ee00-597a-11ea-9f62-eebbcb5508c8.png)

**Expected behavior:**

I would expect if a person has the ability to create and manage their own templates, the security should be inherited if they try to copy the template to be able to edit it.

**Actual behavior:**

Security defaults to Rock Administrator and Communication Administration rather than inheriting security of the original template.

### Versions
* **Rock Version:** [9.4 and 10.1]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by nairdo** [comment]
Hi @karenn-ccbc This is a valid idea which definitely has merit, but I would not call it a bug.  At the moment, the only copy operation which should be copying security is the Page Copy feature (which copies page and block security settings).  

If you still want to get this enhancement into Rock, could you jump over to the https://community.rockrms.com/ideas board to request that all copy operations in Rock retain security (not just Communication Templates :)  Thanks for helping make Rock better!
