### ISSUE TITLE
Progress bar problems when using SignNow with a Registration

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#4143]
### Description
(I was not able to reproduce this on the demo site since it requires a SignNow document.  @jonedmiston asked that I submit as an issue anyway.)

When filling out an event registration that includes a SignNow document, the progress bar doesn't advance properly.

![<a href="https://user-images.githubusercontent.com/18447084/75720327-e7640700-5c9b-11ea-9fbb-e06195960e64.png">https://user-images.githubusercontent.com/18447084/75720327-e7640700-5c9b-11ea-9fbb-e06195960e64.png</a> image]()

![<a href="https://user-images.githubusercontent.com/18447084/75720347-f21e9c00-5c9b-11ea-8323-91f776455bd4.png">https://user-images.githubusercontent.com/18447084/75720347-f21e9c00-5c9b-11ea-8323-91f776455bd4.png</a> image]()

After filling out the document and clicking next, the progress bar does not advance.

![<a href="https://user-images.githubusercontent.com/18447084/75720380-0498d580-5c9c-11ea-9204-1e8faff63894.png">https://user-images.githubusercontent.com/18447084/75720380-0498d580-5c9c-11ea-9204-1e8faff63894.png</a> image]()

After clicking Finish, the bar advances some, but not to the end.

![<a href="https://user-images.githubusercontent.com/18447084/75720293-d6b39100-5c9b-11ea-9fe0-f90309c743c8.png">https://user-images.githubusercontent.com/18447084/75720293-d6b39100-5c9b-11ea-9fe0-f90309c743c8.png</a> image]()

I found that this line of code adds 2 to the total pages when a SignNow document is included, but only 1 page is actually added to the process.

[https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.10.1/RockWeb/Blocks/Event/RegistrationEntry.ascx.cs#L1060](https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.10.1/RockWeb/Blocks/Event/RegistrationEntry.ascx.cs#L1060)

And secondly, throughout the file the count of the current step is using the FormCount variable, which does not include the additional SignNow page, so when you get to the SignNow page the bar doesn't progress, and the more registrants you have, the further behind it gets, resulting in a final page displaying an incomplete progress bar.

Example:
[https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.10.1/RockWeb/Blocks/Event/RegistrationEntry.ascx.cs#L3873](https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.10.1/RockWeb/Blocks/Event/RegistrationEntry.ascx.cs#L3873)

### Steps to Reproduce
1. Create an Event Registration with a SignNow document
1. Fill out the registration

**Expected behavior:**

The progress bar would move forward incrementally each page, and then the final page would have a complete bar.

**Actual behavior:**

The progress bar does not always move forward, and is not at the end when finished.

### Versions
* **Rock Version:** Rock McKinley 10.1 (1.10.1.4)
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
Sign Now is now deprecated.
