### ISSUE TITLE
[10.2 BETA] Send Attendance Reminders job fails

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4149]
### Description
After updating to 10.2 Beta for testing, we ran the Send Attendance Reminders job to verify it works. It does not. We get the following error: `No SMS message found in system communication Group Attendance Reminder`.

### Steps to Reproduce
1. Update dev system to 10.2 beta
1. Run `Send Attendance Reminders` job
1. See error.

**Expected behavior:**

The job should run as it did before the upgrade.

**Actual behavior:**

Email reminders are still sent correctly, but the job itself fails with the SMS error.

### Versions
* **Rock Version:** 10.2
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
The error itself is accurate - as the Group Attendance Reminders does not have a SMS template defined. However, I believe that getting an error "out of the box" is not correct. If I put in a placeholder SMS content, the error goes away.

One of the following (or a combination) should probably be taken.

1) Default the Send Attendance Reminder job to Email and leave it up to the church to decide to enable/allow SMS (they may not even have SMS available to them).
2) Add a default SMS template
3) Modify the job to not throw an error if SMS template/functionality is not available and instead fall back to "Email Only" if that is the case (though probably still include a non-failed message in the status text stating as such).

**Comment by nairdo** [comment]
Thanks Daniel.  We are changing the default to "Email" as you also suggested.  Fixes #4149 https://github.com/sparkdevnetwork/rock/commit/94356cd5ddc2783581ef799cc0e20392db80a0e9
