### ISSUE TITLE
Organizations with one campus are unable to set a default connector in a Connection Opportunity

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#4151]
### Description
This issue is only when an organization has one campus set up. When editing or creating a new Connection Opportunity, the Campus attribute is no longer present. I believe there was an update where if there was only one Campus it would default to that, which is great, however, it isn't allowing a Default Connector to be set and the user is unable to select All or a campus when selecting the connector groups.

There may be another hidden issue that I haven't found a reason for yet. On the Demo site I added a second campus to get a screenshot of the default connector dropdown appearing but it wouldn't display event when I had a campus selected.

### Steps to Reproduce
1. Make sure only one campus is set for the organization.
1. Navigate to the Connection Opportunity and edit or create a new Connection Opportunity.
1. Add a connector group and notice the Campus drop down isn't present and once a group is specified the default connector dropdown does not appear.

![screencapture-rock-rocksolidchurchdemo-page-411-2020-03-11-18!UNITO-UNDERSCORE!02!UNITO-UNDERSCORE!47](https://user-images.githubusercontent.com/5738650/76472456-9783ef00-63c3-11ea-9ee5-0f8156756fa8.png)

The other issue occured when adding back a second campus. I can see the campus selector for the opportunity and for the group but the default connector dropdown does not appear.
![screencapture-rock-rocksolidchurchdemo-page-411-2020-03-11-18!UNITO-UNDERSCORE!21!UNITO-UNDERSCORE!20](https://user-images.githubusercontent.com/5738650/76473072-686e7d00-63c5-11ea-8ca5-fe87bdfd8434.png)

**Expected behavior:**

Either the campus selector should be present, even if it is only one, or if Rock defaults to the only campus it should set the connector group to that campus and, as a result, display the default connector drop down once the group is selected.

**Actual behavior:**

Unable to add a default connector unless the organization has more than one campus.

### Versions
* **Rock Version:** 10.1.4. -I haven't tried the 10.2 beta yet but I'll check and see if it is present in that version too.
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@BEGamache This really feels familiar to me ... I think we did catch and fix this bug during the 10.2 alpha testing.  Can any of our 10.2 beta testers try to reproduce this issue?

**Comment by BEGamache** [comment]
@nairdo Sounds good. Thanks. I'll also look into it on our beta instance tomorrow.

**Comment by nairdo** [comment]
@BEGamache I just confirmed this is working in v10.2.  Although you won't (should not) see any campus checkboxes in that top section, as long as the connector group has people in it, the dropdown should appear with all the people in that Connector Groups section as shown here:

![image](https://user-images.githubusercontent.com/383807/76476591-b97b7280-63bf-11ea-8eaa-e2bde5e8a78d.png)
 
If you confirm, we can close this out.

**Comment by BEGamache** [comment]
This is corrected in 10.2.
