### ISSUE TITLE
Connections Campus filter doesn't hide opportunities for other campuses

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#4152]
### Description
I'm not 100% sure if this is a bug or a feature request. I expected that if I have Opportunities with specific campuses selected in their settings, that the Campus filter would hide Opportunities that do not match that filter.

Related to this issue (and possibly the reason it doesn't work as I expect), even if I set a single Campus for an Opportunity, I am still able to select any campus on each individual Connection Request for that Opportunity (or no campus, which is the default, even when the Opportunity only has a single campus selected). 

The Campus filter does hide Requests by campus, but since requests are created with no campus by default, this is potentially very confusing as well.

(These latter comments could potentially require a separate bug report if this is not how the feature was intended to work.)

![image](https://user-images.githubusercontent.com/18447084/76634442-40416400-6514-11ea-9252-577b66486fde.png)

### Steps to Reproduce
1. Have multiple campuses set up in Rock
1. Create a Connection Opportunity and select one campus ![image](https://user-images.githubusercontent.com/18447084/76636112-7f70b480-6516-11ea-9c46-dc02cb15e2a2.png)
1. Create another Opportunity and select a different campus ![image](https://user-images.githubusercontent.com/18447084/76636151-91eaee00-6516-11ea-9ced-8e853d45d4b9.png)
1. Create a Request in one of these opportunities and save without selecting a Campus. ![image](https://user-images.githubusercontent.com/18447084/76636237-b3e47080-6516-11ea-8c5b-806b281d0558.png)
1. View the Connections Screen with All Campuses selected in the filter ![image](https://user-images.githubusercontent.com/18447084/76634414-34ee3880-6514-11ea-9afd-23b92af81094.png)
1. Change the filter to one of the campuses used above.

**Expected behavior:**

Only the Opportunities for the selected campus would display in the summary section.  All of the connection requests in those Opportunities would display underneath.

**Actual behavior:**

All Opportunities are still displayed. Any requests that do not have a campus set are not displayed.

![image](https://user-images.githubusercontent.com/18447084/76634442-40416400-6514-11ea-9252-577b66486fde.png)

### Versions
* **Rock Version:** Rock McKinley 10.1 (1.10.1.4)
* **Client Culture Setting:** en-US

**Comment by rutledgek** [comment]
The only thing I would add is that I would expect the campus selector to also honor the Is Active campus setting.

**Comment by nairdo** [comment]
@chrismcgrath Hi Chris.  The opportunities shown by the MyConnectionOpportunites block are not _excluded_ based on campus selection, partially for the reasons you described.  It is really meant for filtering the _**request** items_ shown in the lower panel.

> ...but since requests are created with no campus by default...

They should be**, but it will depend if you're using the Campus Context Setter block on the Sign-up page and/or if the user selects a Campus from the drop-down on the signup form:
![image](https://user-images.githubusercontent.com/383807/78410731-066af700-75c2-11ea-95a1-de7a88fd125d.png)

![image](https://user-images.githubusercontent.com/383807/78410869-927d1e80-75c2-11ea-8cb9-14e55dcf5ed5.png)

If that makes sense to you, you can close this bug report -- or if you're looking for a behavior change, I would close this and open a feature request on the http://community.rockrms.com/ideas board so everyone can vote on it.

_** NOTE: I'm testing on v11 and on pre-alpha.  There has been quite a bit of work in the Connections area so it's possible this behavior is different that what you're seeing in v9-v10._


@rutledgek Whether or not you want to inactive campuses to show up on the Connection Opportunity Sign-up block is now controlled by a block setting: 
![image](https://user-images.githubusercontent.com/383807/78410323-c9523500-75c0-11ea-9902-46537cc66d7b.png) but on the internal MyConnectionOpportunity block, the campus filter automatically excludes inactive campuses.

**Comment by chrismcgrath** [comment]
Thanks @nairdo, I will add it to the ideas board.

On that related item, are you saying it's working as intended that you can create an opportunity for one campus and still allow people to sign up and select a different campus?  I would expect that if the opportunity is campus-specific you would only want to let people choose from the campus(es) that the opportunity applies to.

**Comment by nairdo** [comment]
@chrismcgrath Yes, you can do either.  It depends how you've got it set up.  If you want to _not_ show opportunities for other campuses, there are a few ways to do it. One way: If you have a campus context set, and if you filter out (skip) connection opportunities in the `Themes\...\Assets\Lava\OpportunitySearch.lava` that's being used by the ConnectionOpportunitySearch block, you can prevent people from seeing those opportunities like this:

```javascript
{% for opportunity in Opportunities %}
    {% assign matched = opportunity.ConnectionOpportunityCampuses | Where:'CampusId', CampusContext.Id | Select:'ConnectionOpportunityId' %}
    {% if matched == empty %}
        {% continue %}
    {% endif %}
...
```

...and another way (simpler) way is to just let the individual filter out campuses using the campus filter:

![image](https://user-images.githubusercontent.com/383807/79600721-771f1280-809c-11ea-8bcb-f550d1faae73.png)
