### ISSUE TITLE
Editing Scheduled Transaction does not update payment details in Rock

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4155]
Submitted on behalf of [The Crossing Church ](https://www.thecrossingchurch.com/)

Could not reproduce on demo site, since it is not configured with PayFlowPro gateway

### Description
When adding a new card to an existing scheduled transaction, the scheduled transaction's payment details and summary are not updated with the new card's information and the audit log does not show the correct payment information. The details are updated correctly at the gateway though.

This is happening when using the PayFlowPro gateway.

### Steps to Reproduce
1. Go to public giving page that is configured with PayFlowPro gateway.
1. Setup a recurring contribution (In this example using card that ends with 0430).

![image](https://user-images.githubusercontent.com/548180/76994158-3a2ff680-690b-11ea-9c27-3f5b3f322cc2.png)

![image](https://user-images.githubusercontent.com/548180/76994186-41570480-690b-11ea-85e1-9f82fcaae3f5.png)

![image](https://user-images.githubusercontent.com/548180/76994209-47e57c00-690b-11ea-8002-4ce74ab67278.png)

1. Once the recurring transaction has been saved, select the "Manage Giving Profiles" and edit the recurring schedule.

![image](https://user-images.githubusercontent.com/548180/76994280-5fbd0000-690b-11ea-928c-0b03f71337b8.png)

1. Select "New Card" and enter information for a different credit card (now using card that ends with 8690): 

![image](https://user-images.githubusercontent.com/548180/76994333-7400fd00-690b-11ea-99c7-d444859f86c3.png)

![image](https://user-images.githubusercontent.com/548180/76994345-78c5b100-690b-11ea-8bdd-94b96a64d04f.png)

![image](https://user-images.githubusercontent.com/548180/76994371-811dec00-690b-11ea-883e-0fbebcdfc2cb.png)

**Expected behavior:**

When the user edits the transaction again, the summary should not show the old card number, and when viewing the transaction internally, the payment details, summary, and history should show the updated card number (8690).

**Actual behavior:**

The summary still shows old card number (0430): 

![image](https://user-images.githubusercontent.com/548180/76994706-0bfee680-690c-11ea-99a3-290f6ebef170.png)

The internal view still shows old card number in the payment details, summary and history:

![image](https://user-images.githubusercontent.com/548180/76995167-b37c1900-690c-11ea-8d7f-be5c35a2061c.png)

When viewing the scheduled transaction inside the PayFlowPro admin area, it does show the updated card number.

### Versions
* **Rock Version:** Rock McKinley 9.4
* **Client Culture Setting:** en-US

**Comment by taylorbrooks** [comment]
This happens on the Simple Donation gateway as well.

**Comment by azturner** [comment]
Here's screenshot too showing that it does actually update the gateway with the correct card number.

![image](https://user-images.githubusercontent.com/548180/77084895-c64e2680-69bc-11ea-957f-2e78347669a6.png)

**Comment by azturner** [comment]
In addition to not updating the scheduled transaction record, all future transactions that are generated and imported from PayFlowPro also get created with the incorrect card number. 

![image](https://user-images.githubusercontent.com/548180/77584010-4b46ad80-6e9f-11ea-9036-b0b35308d3ab.png)
