### ISSUE TITLE
Group Member Notification System Emails - mobilePhone NumberTypeValueId Incorrectly defined

### ISSUE THREAD

**Issue by hbcpn** [SparkDevNetwork/Rock#4156]
### Description
The following core default shipped System Emails have an incorrectly NumberTypeValueId assigned for the mobilePhone attribute:

* Absence Group Member Notification
 {%- assign mobilePhone =absentMember.PhoneNumbers | Where:'NumberTypeValueId', 136 | Select:'NumberFormatted' -%}
* Pending Group Members Notification
* {%- assign mobilePhone = pendingIndividual.PhoneNumbers | Where:'NumberTypeValueId', 136 | Select:'NumberFormatted' -%}

Both should have a value of **12**

### Steps to Reproduce
1. Go to Admin Tools - Communications - System Emails
1. Edit the default Absence Group Member Notification or Pending Group Members Notification system emails.
1. Scroll down to the {%- assign mobilePhone = line in each
1. See error in the Where:'NumberTypeValueId', 136

**Expected behavior:**

The Where:'NumberTypeValueId', 136 should read Where:'NumberTypeValueId', **12** to properly display the pendingIndividual.PhoneNumbers or absentMember.PhoneNumbers in the system email notification.

**Actual behavior:**

These values are not presented in the current emails.

### Versions
* **Rock Version:** [v10.1]
* **Client Culture Setting:** [en-US]

**Comment by JimMichael** [comment]
I would add that we see the same on 9.4, so I'm guessing it's broken in every version that has those system emails.

**Comment by hbcpn** [comment]
I know that this is closed, but now that I've checked v10.2 this shows in the new Systems Communications area and the Systems Emails (Legacy) pages. I can't see how to check the commit for both of these places that the issue exists.

**Comment by MichaelAllen** [comment]
@hbcpn Here is the commit that fixes the SystemEmails: https://github.com/SparkDevNetwork/Rock/commit/a227066ae629cdcf1fe7374569be4857ab2d2be0  

Based on http://prealpha.rocksolidchurchdemo.com, it looks like the SystemEmails are good, but the SystemCommunications are not yet fixed.

**Comment by nairdo** [comment]
@MichaelAllen ++ for the assist here!  @hbcpn yes, we caught that shortly after the last pre-alpha-release but the corresponding SystemCommunication should also be corrected via this commit https://github.com/SparkDevNetwork/Rock/commit/3783b781d78d8ded453bcaed1b0ac6a672ebb2d4#diff-20aee14345d05db4e66e9919895f6ac2R56 and after tonight's pre-alpha-release build you will also see it on that system too.
