### ISSUE TITLE
Chart Lava Shortcode YValue

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#4157]
### Description
When using the {[chart]} shortcode it has some funny YValue interactions depending on your data.  When using for instance 4 values in a bar chart of (320,380,400,370) the chart will display the beginning YValue at 320 instead of have a scale starting at 0 on the Y axis.  Which causes your lowest bar to not even be present because it is the "floor" of the yaxis.
![](https://user-images.githubusercontent.com/33845027/77327727-a040c300-6ce9-11ea-9f4e-0b0d4dcd7048.png)

### Steps to Reproduce
1. Create a new HTML Block somehwere
1. Type this in the content block: {[ chart type:'bar']} [[ dataitem label:'first' value:'320' ]][[ enddataitem ]] [[ dataitem label:'second' value:'400' ]][[ enddataitem ]] [[ dataitem label:'third' value:'380' ]][[ enddataitem ]] [[ dataitem label:'fourth' value:'370' ]][[ enddataitem ]] {[endchart]}
1. refresh the screen for it to load
1. See that there are only 3 bars.  The lowest value has a space to be displayed but the yaxis starts at the lowest value and does not appear as a bar.  It skews the look of the chart

**Expected behavior:**

Either allow for a YValue scale, or always start at 0 and auto scale your Y increments on the side based on values input.

**Actual behavior:**

yaxis not useable

### Versions
* **Rock Version:** [10.1]
* **Client Culture Setting:** [en-us]

**Comment by garrettjohnson** [comment]
@markewampler We're creating update for the shortcode documentation in 10.3. To apply the fix to your example add yaxismin:'0' to your chart. 

```
{[ chart type:'bar' yaxismin:'0']}
[[ dataitem label:'first' value:'320' ]][[ enddataitem ]]
[[ dataitem label:'second' value:'400' ]][[ enddataitem ]]
[[ dataitem label:'third' value:'380' ]][[ enddataitem ]]
[[ dataitem label:'fourth' value:'370' ]][[ enddataitem ]]
{[endchart]}
```
