### ISSUE TITLE
iCalendar Feed Missing Events

### ISSUE THREAD

**Issue by doflynn** [SparkDevNetwork/Rock#4158]
### Description
The iCalendar feed for the public calendar does not include events.  However, the events are visible on the public calendar.

### Steps to Reproduce
1. Create an Event Item on the Public Calendar
1. Create an Event Occurrence for the Event Item
1. Specify the schedule to be a specific date / time for a 1 hour duration.  (do not make a reoccurring event)
1. Verify that the event is visible on the external website
1. Download the iCalendar feed for that public calendar
1. View the contents of the iCalendar view in a text editor and confirm the event does not exist.

**Expected behavior:**
All current / future events are included in the iCalendar feed.

**Actual behavior:**
The iCalendar feed is missing the one-time events.

### Versions
* **Rock Version:** [10.1]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by doflynn** [comment]
For the events missing in the iCalendar feed, the event occurrence is missing EffectiveEndDate .  Consequently, the event seems to be exclude from the SQL query results.

**Comment by MrUpsideDown** [comment]
This issue has been fixed in v12 with this commit:
https://github.com/SparkDevNetwork/Rock/commit/2cf40f4d8e1396a8add7fd852a0fa4111eee9dd0
