### ISSUE TITLE
Showing inactive campuses on Prayer Team page drop down

### ISSUE THREAD

**Issue by jardine98** [SparkDevNetwork/Rock#4160]
### Description
On the Prayer Team page for the campus drop down all campuses are showing even inactive ones. There is not an option to show only active campuses and on the Prayer Request page which is the parent page it only shows active campuses.

### Steps to Reproduce
![](https://user-images.githubusercontent.com/54868401/77678084-e5652f00-6f4d-11ea-8521-56c73cf5eef3.png)

1. Go to Admin Tools>CMS Configuration>Pages>External Homepage>Connect>Prayer>Prayer Team
1. Click on the URL page.
1. Open the campus drop down.
1. It will show all campuses active and inactive.

**Expected behavior:**

I expected to only see active campuses since the prayer request page only shows active campuses.

**Actual behavior:**

All campuses active and inactive are showing.

### Versions
* **Rock Version:** [Rock McKinley 10.1]
* **Client Culture Setting:** [rock.goldcreek.org]

**Comment by cabal95** [comment]
Bug was confirmed on the pre-alpha.
