### ISSUE TITLE
Workflow Entry Block - title template and css icon required

### ISSUE THREAD

**Issue by tstephens17** [SparkDevNetwork/Rock#4166]
### Description
The workflow block is requiring a CSS icon class and title template.
https://nvclweb.s3.amazonaws.com/Rock/Annotation+2020-04-02+102819.png

### Steps to Reproduce
1. Add the workflow entry block to a page

**Expected behavior:**

I expected the pre-10.2 behavior of not having it required.

**Actual behavior:**

They were required

### Versions
Rock Version: Rock McKinley 10.2 (1.10.2.3)
Client Culture Setting: en-US

**Comment by nairdo** [comment]
@tstephens17 Although this [was fixed for v11](https://github.com/SparkDevNetwork/Rock/commit/b213eeeaba9496ec2e0a0e136609a94e4130162a) (seen [here](https://prealpha.rocksolidchurchdemo.com/ContactUs)), I'll have someone from the team pull this fix into the v10.3 release too.
