### ISSUE TITLE
Error - 403 - Forbidden: Access is denied

### ISSUE THREAD

**Issue by krallsm** [SparkDevNetwork/Rock#4170]
### Description
Nobody except for Rock Admin's can view background checks with proper Security Roles assigned. When viewing the background check a 403 - Forbidden: Access is denied error is displayed.

### Steps to Reproduce
Specifically using Protect My Ministry for Background Checks (not using Checkr), everything is able to be reproduced with an uploaded Background Check File Type on a profile within the demo site.

1. Go to a user profile
1. Assign the Safety and Security Workers Security Role
1. Impersonate User
1. Try to view a background check on another users profile
1. Error occurs

**Expected behavior:**

To be able to view a background check with proper Security Roles applied

**Actual behavior:**

Error - 403 - Forbidden: Access is denied

**Things I've tried to remedy**
I've gone through and played around with permissions across anything I could find with Background checks, allowing Safety and Security Workers to View, Edit, Administrate, anything I could find relating to Background checks. Nothing helped. The only thing that would allow people to view the background check outside of the Rock Admin security role was by getting rid of the All User - Deny Security Permission on the Background Check File Type Security Settings. However when you get rid of the All User - Deny Security, it opens up the Background Checks to being viewed by anybody with a link. Adding the All Users - Deny Security back into the Background Check File Type Security does nothing no matter where you place it into the hierarchy of Security Roles. What I would expect based off watching all the videos I can find on Rock RMS security is that Rock would work down through the Security Permissions and stop when it recognizes that the specific user does indeed have permission to see this. So for example, the Background File Type would see that Safety and Security Workers do have permission to see the Background File Type and therefore wouldn't check to see if the All User's Security Role was present lower down on the list of the Security Role hierarchy. It appears that the block is seeing that Safety and Security Workers can see the Background Check File Type but is still moving on to see that All Users are denied from seeing the Background Check File Type.

### Versions
* **Rock Version:** [9.4 (local site), 10.2 (demo site)]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
@krallsm Hi Sean.  I can confirm that impersonation is not enough to pass the security checking done in this situation, but if you actually were logged in as that person (in the Safety and Security Workers role) it does work**.   There are also other places in Rock where an impersonated user is not treated exactly like an actual logged in person.  This is be design.

In my example, I have Cindy Decker in that role, and while actually logged in she can see the background check document (https://prealpha.rocksolidchurchdemo.com/GetFile.ashx?guid=d7d4c6dd-64ee-434f-b760-eb54751b63af) but when impersonating her, she cannot.

If that makes sense to you, you can close the issue.

**Comment by krallsm** [comment]
@nairdo This worked, thank you.
