### ISSUE TITLE
Image Button in HTML Editor inserts relative path URLs into emails

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#4179]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When editing HTML for email messages such as the event registration confirmation message or the simple email editor, using the Image button to include an image from the file manager inserts an img tag that contains a relative path for the url, such as /Content/... rather than the full url. This causes the images to display properly in the editor but not in the email that's received.

This issue also applies to the File Browser and Asset Manager buttons.

### Steps to Reproduce

1. Go to New Communication
2. Click on Use Simple Editor
3. In the Message box, delete any existing content
4. Press the Image Browser button
5. Select an image
6. Press OK
7. Press the Code Editor button
8. See that the img tag's src starts with / rather than http

**Expected behavior:**

For any editors that are used to create emails or other content that will be displayed anywhere other than in Rock, the full URL should be used for the image tags.  

**Actual behavior:**

A relative URL is inserted instead.

**Notes**

I found that the javascript being used here refers to baseUrl in Rock.settings, which is defined in RockPage.OnInit. My initial idea would be to add another setting that includes the URL from one of the ApplicationRoot global attributes and use that setting when necessary. It may be preferable to still use the relative path in some places.

### Versions

* **Rock Version:** Rock McKinley 10.2
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
@chrismcgrath both the Simple Editor and the Wizard work to resolve the relative paths to absolute paths at the time of sending not at the time of editing. For their intended use cases we think that's the best way to handle them. They weren't really intended to be used as template creation tools, but rather sending tools.

That said... if you took the content from them and used them as templates I would think everything should work fine as the send process would resolve the relative links at the time of sending.

**Comment by chrismcgrath** [comment]
Thanks @jonedmiston, this came up because the image did not display in the delivered email, and I assumed that the HTML in the editor would match the HTML in the message. It turns out that the issue is actually that spaces are being converted to + in the delivered email rather than %20 as it is in the editor. Files with no spaces work fine. I'll dig into that and see if that's an issue I need to report or something unique to us.

**Comment by chrismcgrath** [comment]
@jonedmiston On second look, this issue does exist in event registration confirmation emails. This line sets the appRoot to ResolveRockUrl( "~/" ), which resolves to "/" instead of the true public root that is used when sending a message directly.  

https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/RegistrationEntry.ascx.cs#L2288

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Communication/SMTPComponent.cs#L339

Poking around the code I find more places where AppRoot is set to ResolveRockUrl( "~/" ). Before I go changing a bunch of references I'd like feedback on whether this looks to be the correct solution.

**Comment by jonedmiston** [comment]
@chrismcgrath I think this would be taken care of by the TransportComponent's ResolveText method on send:

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Communication/TransportComponent.cs#L126

It handle's both `~/` and `/` for images and links.

**Comment by chrismcgrath** [comment]
@jonedmiston Correct, that is where the replacements are done, but appRoot gets passed in so if `appRoot = "/"` then this function will just replace `~/` with `/` which doesn't help.  

Confirmation emails all have their AppRoot set to `/` in these 3 places:

https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/RegistrationEntry.ascx.cs#L2288

https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/RegistrationEntry.ascx.cs#L1646

https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/RegistrationDetail.ascx.cs#L840

I see that there's a `RockPage.ResolveRockUrlIncludeRoot` method which I believe would be more correct for these three lines, or alternately, maybe `RockMessage` just needs its `AppRoot` set to the proper place in the constructor and remove anywhere it's being set to `~/`. As far as I can tell in the core code, AppRoot is never set to anything else, and this bug demonstrates that requiring it to be set manually for every message being created is prone to cause mistakes.

Are either of these two solutions acceptable?

**Comment by jonedmiston** [comment]
@chrismcgrath let's start by either closing this issue and creating a new one, or editing it to match the actual problem. The body of the issues no longer matches the problem. 

We'll talk internally as I think the issue is wider than the three links above. There a several places providing `AppRoot` with a value from `ResolveRockUrl("~/")`. It may be best to add code to `ResolveText` method to check for that and append the public app root when that's the case.

**Comment by chrismcgrath** [comment]
Thanks, I'll open a new ticket so the comments aren't confusing when all the information changes.
