### ISSUE TITLE
Workflow Entry Required Fields

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#4182]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When utilizing the 'Workflow Entry' block in 10.2, there are 2 fields in the block settings that are required that feel as though they should not be required.
A: Block Title Template
B: Block Title Icon CSS Class

### Steps to Reproduce

1. Build a new page
2. Add a new block to that page: 'Workflow Entry' of Type [Workflow Entry] of Category [WorkFlow]
3. Go to the block settings of that block
4. Notice the last two editable fields in the block settings are required. A: Block Title Template & B: Block Title Icon CSS Class

**Expected behavior:**

I would expect that neither of these fields would be required. But instead, would expect that they are optional.

**Actual behavior:**

Both fields appear to be required.

### Versions

* **Rock Version:** [10.2]
* **Client Culture Setting:** [en-US]

![Screen Shot 2020-04-10 at 23 16 32](https://user-images.githubusercontent.com/41912840/79034152-f636b700-7b81-11ea-8ee7-01afa652936e.png)

**Comment by MichaelAllen** [comment]
This has been fixed in v10.3. See: https://github.com/SparkDevNetwork/Rock/issues/4166
