### ISSUE TITLE
Times Given not populating in Data View properly when Family Analytics Job runs

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4184]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When trying to pull a Data View for Person Attributes "Times Given (6 wks)" or "Times Given (52 wks)", no one shows up in the Data View unless the information has been manually entered into a Person's Extended Attributes. After manually entering a number for Times Given (number not populated by Family Analytics Job) then the person shows up in the Data View. After running Family Analytics Job, these attributes will be correctly populated by the job, however the person will no longer show in the Data View.

Data View:
Applies To: Person
Filter: Times Given (6 wks) Is Not Blank (can also use "Times Given (52 wks) Is Not Blank")

### Steps to Reproduce

1. Add a Financial Batch (test batch).
2. Add a Cash Transaction to the Batch for Ted Decker. I back-dated it 1 week.
3. Go to Ted Decker's profile > Extended Attributes > Edit Family Analytics and add any number to "Times Given (6 wks)" > Save
4. Create a new Data View, Applies to Person, Filter: Times Given (6wks) Is Not Blank
5. Ted Decker should now show in the Data View
6. Run Family Analytics Job, go back to Data View and Ted Decker is no longer in the Data View
7. On Ted Deckers profile > Extended Attributes, Times Given (6 wks) should show correctly with at least 1 transaction - the Family Analytics job populated this.

**Expected behavior:**

The Data View should show everyone who has a value in "Times Given (6 wks)".

**Actual behavior:**

The Data View only shows people who have had that value manually entered, not values that were calculated by the Family Analytics Job.

Note: the same behavior happens with Times Checked-In (16 weeks)

### Versions

* **Rock Version:** 10.1 (my instance) 10.2 (demo site)
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
I will add that we _cannot_ dupe this here on 9.4 or a 10.1 copy of the same production db. In all cases, filtering on the family analytics attributes and using them as columns in reports works as expected here. 

I'm in no way saying there isn't an issue... several of us worked with Mike (and another person seeing similar issue) in chat and just could not figure out why their systems (and supposedly demo, too) are acting this way, when others (myself included) see expected results.

**Comment by mikedotmundy** [comment]
Update: I am now on 10.2. This did not fix the issue.

**Comment by aaronjones8** [comment]
This seems to be intermittent on different installs. We have it occurring currently on an install on 11.2. We have had it happen on another churches site and it had just started working at one point.

**Comment by mikedotmundy** [comment]
Running this SQL returns 497 results for us, so I would assume that the DV should work:
