### ISSUE TITLE
Copying Pages with Content Component Blocks Doesn't Create Unique Content Channels/Items (Duplicate of 4177)

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#4195]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We've come across a bug when copying pages that have content component blocks on them. When duplicating a page with a content component block on it, rather than also copying the channel/item that the content is stored in, it just creates a new block that _references the existing content channel and item(s)._

This is problematic because when you go to edit the content on the copied page, you're also changing the content on the original page you copied from.

### Steps to Reproduce

1. Go to any existing page that has a content component block on it with content (or create a new one).
2. Copy this page
3. Go to the newly created copy of the original page.
4. Update the content in the content component block.
5. Go to the original page that was copied.
6. See the updated content.

**Expected behavior:**

Copying a page should duplicate all blocks and their values - the new page and it's blocks should in no way be connected to the page it was copied from.

**Actual behavior:**

Content component blocks reference the existing content channel/item values of the page they were copied from.

### Versions

* **Rock Version:** 11.0.13
* **Client Culture Setting:** en-US

**Comment by azturner** [comment]
I think this is same as this issue: https://github.com/SparkDevNetwork/Rock/issues/4177

**Comment by nairdo** [comment]
Yes, that's a duplicate
