### ISSUE TITLE
Communication Recipient filters copy on tab views

### ISSUE THREAD

**Issue by karenn-ccbc** [SparkDevNetwork/Rock#4197]
### Description
When looking at Communication history on Recipient Details tab, if you go to another tab and come back the filters duplicate.
![image](https://user-images.githubusercontent.com/35667472/80006420-75819000-848a-11ea-88f1-a41ed9b5f131.png)
I am unable to test this in Rock Demo since there is no communication history.

### Steps to Reproduce
1. Go to 'Communication History.'
1. Click on a communication
1. Click on Recipient Details Tab
1. Click on Activity Tab
1. Go back to Recipient Details and the filters have duplicated.

**Expected behavior:**

Expect to see the single list of filters.

**Actual behavior:**

The list of filters has duplicated.

### Versions
* **Rock Version:** [10.2]
* **Client Culture Setting:** [(NOT SURE WHAT THIS IS-- but I am on Chrome Browser, also tested in Edge- same thing happened]

**Comment by MrUpsideDown** [comment]
This issue has been fixed with this commit:
https://github.com/SparkDevNetwork/Rock/commit/1fd0faab032ddd90adf7a3971f396b9ac2787c32
