### ISSUE TITLE
Can't delete person from step grid

### ISSUE THREAD

**Issue by theundecided** [SparkDevNetwork/Rock#4200]
### Description
Attempting to delete a person from a step grid causes nothing to happen.

### Steps to Reproduce
1) Go to Home> Steps> Discipleship Path > Baptism
2) delete ted

**Expected behavior:**

Ted to be removed from list

**Actual Result**
![imgur](https://i.imgur.com/wp7KFg7.gif)

### Versions
* **Rock Version:** [1.10.2.3]
* **Client Culture Setting:** [en-us]

**Comment by nairdo** [comment]
@theundecided  It looks like we also recently ran into and fixed (via https://github.com/SparkDevNetwork/Rock/commit/09f8f43f843e89186e43f26e7924dec31898062d ) the issue before it was reported here.  So, I've included the commit reference here and will mark this as fixed in v10.3.

**Comment by TheCoreyHall** [comment]
I believe this might need to be reopened @nairdo. I have a client on 10.3 and they are unable to delete from Grid. In addition, I checked the Rock Demo site thats on 11, and I cant delete the participant from Grid there as well.

**Comment by nairdo** [comment]
@TheCoreyHall  Just FYI. We did find out what went wrong. A later change in v10.3 to [add the campus column](https://github.com/SparkDevNetwork/Rock/commit/0f1c446e00b38b91a76ab99fc5c2415038dfe29c#diff-63c8f4c7b18ae3c76329f8300f2cc469R895) into the grid ended up having a very odd unintended consequence of breaking the delete button (if there was only one campus).  We've got a handle on the fix and are taking steps to avoid the thing** that caused the underlying problem.


<sup><sub>_** programmatically removing columns from the grid that were not added programmatically._</sub></sup>
