### ISSUE TITLE
Lava can't access the 'Object' of a RegistrationInstance attribute.

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#4201]
### Description
Unlike other entity attributes, trying to get the object value of a RegistrationInstance attribute just returns the name of the Registration Instance.

I believe this is due to `RegistrationInstanceFieldType` not implementing `IEntityFieldType`

### Steps to Reproduce
```
{{ Workflow | Attribute:'MyRegistrationInstance','Object' | ToJSON }}
```

**Expected behavior:**

```
{
    "Id": 1,
    ....
}
```

**Actual behavior:**

```
"The instance name"
```

### Versions
* **Rock Version:** 10.2
* **Client Culture Setting:** en-US

**Comment by markewampler** [comment]
I concur.  That is how it works for me too.  Just had this happen on a workflow we were using today on 10.1
