### ISSUE TITLE
Connection Request Export to Excel Clean Up

### ISSUE THREAD

**Issue by heather-spronk** [SparkDevNetwork/Rock#4204]
2 Steps to Reproduce

1. Go to 'Connections'
1. Click on 'Export to Excel'

**Expected behavior:**

Clean data that we can use to filter on in excel fields

**Actual behavior:**

Column F - Last Activity contains HTML
Column G - Last Activity Note is blank even though there is data saved
Column R - State Label contains HTML

### Versions
* **Rock Version:** [Rock McKinley 10.1 (1.10.1.4)]
* **Client Culture Setting:** [en-US]

![image](https://user-images.githubusercontent.com/64169497/80255116-8ae8ec80-8639-11ea-9577-a2e32c5910c4.png)

**Comment by nairdo** [comment]
@heather-spronk A few questions:

- regarding Column G (Last Activity Note) is your block setting set to not display the Last Activity Note?  (Regardless, I think we're going to change this to always show the data in Excel).  
- regarding Column R (State Label) that should just be the same as Column H (called State).  Can you unhide that column in your screenshot and check that for me?  _(That "State Label" column should just be the raw, unmodified value from the State data. )_

**Comment by heather-spronk** [comment]
@nairdo Thanks for getting back to me.  

- Column G was my error in not turning on that block setting.  I didn't realize it was there.  Thank you.  That was my biggest problem. 

- Column H is showing "ID", Column Q is "Connection State".  Connection state is showing the correct info and relates to the State Label raw data.  I think that is all fine.  I'm assuming that raw data field is important or helpful to some people?

In waiting for this to be usable for us I ended up learning more lava and created a sweet html merge document that includes other information about the person like their Health Check Notes and recent Prayer Requests so it all worked out.
