### ISSUE TITLE
Use of Where to select attribute matrix items throws Legacy Exception

### ISSUE THREAD

**Issue by SteveSwaringen** [SparkDevNetwork/Rock#4209]
### Prerequisites
* [ x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
Using the Lava Where filter parameter to select from a list of AttributeMatrixItems throws a Legacy Exception.

### Steps to Reproduce
1. On the RockSolidChurchDemo site, enable legacy lava (make it easier to confirm things are doing what they should).
1. Go to the internal homepage (rocksolidchurchdemo.com/Admin). Edit the block properties for the Staff Updates block.
1. Add insert lines 3 and 4 below in the Body Template at the location shown (line 85 at the time of this report).

```
        {{ Item | Attribute:'Articles' }}
        {% assign article = Item | Attribute:'Articles','Object' | Property:'AttributeMatrixItems' | Where:'ArticleTitle','Superhero Training' | First %}
        {{ article | Attribute:'ArticleTitle'  }}
    </div>
```

1. Save the changes. Observe that the title of the Superhero Training has been reprinted, but also that three exceptions have been logged to the Exception Log.

(Granted this example isn't something you would actually do, but it's a simple example using the only AttributeMatrixTemplate defined on the demo site.)

**Expected behavior:**

The Where documentation indicates that it can be used with both properties and attributes. This should return the title of the article without throwing the exception and without having to enable legacy Lava.

**Actual behavior:**

Logs an exception when legacy lava is enabled. Does not execute when legacy Lava is disabled.

### Versions
* **Rock Version:** 10.2 (1.10.2.3) 
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Confirmed on pre-alpha site too.

**Comment by SteveSwaringen** [comment]
If this bug isn't fixed when legacy Lava support is permanently disabled, the documentation of the Where filter will need to be rewritten. It specifically says this filter can be used with attributes, but that will no longer be the case.

**Comment by jonedmiston** [comment]
@SteveSwaringen we might need some more input on this. The ' | Where' filter (as show in the example) documentation does not seem to indicate the attributes are supported. There 'where:' parameter of entity commands does support however support attributes. I'm thinking that perhaps there is confusion that these two items are the same. 

Matrix attributes are great, but they are not able to be reported on ([docs](https://community.rockrms.com/documentation/bookcontent/9/243#attributematrixtemplates)) based on the way that they are stored.

It's possible that we could create a new filter like:

{% assign article = Item | Attribute:'Articles','Object' | Property:'AttributeMatrixItems' | First | MatrixProperty:'ArticleTitle' %}

but performance would not be great as several database reads would be needed for that single item. 

If I'm missing something please let me know and I'll re-open this.

**Comment by SteveSwaringen** [comment]
@jonedmiston I'm good with closing this. The addition of the TeamGroup to the Campus entity eliminated our primary use case for this and for the other places where we still use it we have a custom Lava filter that does the job. I agree that it is computationally inefficient, but having it in a filter is (intuitively; I haven't actually tested this) much faster than looping through the matrix items in Lava. It certainly makes for cleaner and more concise Lava.
