### ISSUE TITLE
DataView Filter In Group Of Type slow when using two in single DV

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4211]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

This is not a bug report per-se, meaning nothing is broken. But hopefully this gives a good reproducible DV query that can be used to improve performance of the DV system when complex queries are involved.

Basically, as pictured below, we setup a DV that includes people in the group type "Life Group", limiting to Active groups and either Pending or Active members.  If _either_ of the two filters are used by themselves, the DV takes 0.2 seconds to load. When _both_ are used (show if ANY) then the DV takes 15 seconds to load.

The resulting data set if about 2,500 people so this slowdown may only show up on a larger database.

![Screenshot_2020-04-28 Data Views Rock RMS](https://user-images.githubusercontent.com/1119863/80540688-a405dc00-895e-11ea-85ee-e6ffd0703d76.png)

### Steps to Reproduce

1. Configure DV as shown in screenshot.
2. Click Save
3. Wait.

**Expected behavior:**

A roughly linear increase in wait time.

**Actual behavior:**

A 75x increase in wait time.

### Versions

* **Rock Version:** 10.2
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
I tried to reproduce on several large systems but it appears this issue has been resolved.  I also spoke with @cabal95 and he agreed it looks like it's no longer an issue, but I was unable to pin-point which change resolved this.  I asked him to please re-open this if he sees this issue return.
