### ISSUE TITLE
Rapid Attendance Entry does not work with a single group configured or a parent group with one child group

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4212]
Submitted on behalf of [Northpointe Community Church ](https://www.northpointe.org/)

### Description
When configuring the Rapid Attendance Entry block to take attendance for one specific group (or a parent group with only one child), you cannot enter attendance. The group picker/dropdown is hidden and the location picker does not have any values.

### Steps to Reproduce
1. Go to demo site
1. Add a new Group Type that allows taking attendance and supports multiple location/schedules...

![image](https://user-images.githubusercontent.com/548180/80544865-cc91d400-8966-11ea-9dd2-16defa8ade38.png)

1. Go to Group View and add a new root group of this type and configure a location with services...

![image](https://user-images.githubusercontent.com/548180/80544894-e3382b00-8966-11ea-9306-ef08bc998200.png)

1. Configure the Rapid Attendance Entry block to use this new group...

![image](https://user-images.githubusercontent.com/548180/80544934-ffd46300-8966-11ea-8e5d-355cfa16f020.png)

**Expected behavior:**

Should be able to enter attendance for this group.

**Actual behavior:**

Cannot enter attendance because the location picker shows no values...

![image](https://user-images.githubusercontent.com/548180/80544962-15498d00-8967-11ea-86e8-c904040788a1.png)

We first tried to work around this by adding this group to a parent group and configuring the block to use that parent group, but had the same issue. We had to add a second child group called "Don't Use" ...

![image](https://user-images.githubusercontent.com/548180/80545213-a91b5900-8967-11ea-814b-74a50074ce96.png)

And configure block with specific parent group...

![image](https://user-images.githubusercontent.com/548180/80545328-f13a7b80-8967-11ea-9683-a59cdc0e71ba.png)

To get it working.

### Versions
* **Rock Version:** 10.2
* **Client Culture Setting:** en-US

**Comment by adamhann** [comment]
We've been able to reproduce this and just submitted to Spark since this was a project they worked on for us.
