### ISSUE TITLE
Multiple messages when copying communication sent to communication list

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#4215]
### Description
Submitted on behalf of Bridgepoint Church (Whitewater Crossing reported the same behavior in rocket chat. https://chat.rockrms.com/channel/communications?msg=7xDPGd5rdmvmssS6j)

When copying a communication sent to a communication list, any people that were on the communication list twice and later merged still get multiple copies of the communication.

If 2 people were merged, the communication will show up twice in the Person History block on their History tab of the person profile. There are 2 entries in the CommunicationRecipient table that point to 2 different person aliases but both of those aliases point to the same person id.

### Steps to Reproduce
1. Create and send a communication sent to a communication list that has 2 people on that will be merged.
1. Merge the 2 person records
1. Copy the original communication, update some content and send
1. See the person get 2 copies of the message

**Expected behavior:**

The merged person would only receive 1 copy of the message

**Actual behavior:**

The merged person receives 2 or more copies of the message depending how many people were merged and on the first communication.

### Versions
* **Rock Version:** [10.2]
* **Client Culture Setting:** [en-US]

**Comment by MicahO** [comment]
I can confirm that we're seeing the same thing; I know Bridgepoint is on Sendgrid but Whitewater is on Mailgun. Same behavior is happening in both places.
