### ISSUE TITLE
Person Search Box not clearing

### ISSUE THREAD

**Issue by karenn-ccbc** [SparkDevNetwork/Rock#4216]
### Description
The Person search box is not clearing after searching/selecting a person in the Simple Communication and when adding someone through attendance check-in details. 
![image](https://user-images.githubusercontent.com/35667472/80835722-f5110c80-8bb8-11ea-8d72-26ce3e6c5899.png)

### Steps to Reproduce
1. Go to 'Simple Communication'
1. Click on 'Add person'
1. Search for and Select a person
1. Try to add another person (Tested in both Chrome and Edge)

**Expected behavior:**

I would expect the search box to be clear to be able to add another person.

**Actual behavior:**

I have to manually clear out the previous search or if I start typing it types in front of the previous name.

### Versions
* **Rock Version:** [10.2]
* **Client Culture Setting:** [en-US]

**Comment by lizrose20** [comment]
We see this same issue (on 10.2) within Attendance Analytics > Check-in Details as well.  Add a an occurrence, Add Person, Save.  Then Add Person again, the previous name is in the search box.

**Comment by JimMichael** [comment]
Confirmed. I imagine this is happening on person pickers in other places, as well (but not all... as I can NOT dupe it when adding individuals to a Wizard communication, for example)
