### ISSUE TITLE
Group ADD not showing correct Group Types

### ISSUE THREAD

**Issue by karenn-ccbc** [SparkDevNetwork/Rock#4217]
### Description
Go to a Group Tree and select add child to selected. When adding the new group, the Group Types do not display just the allowed group types. All of the group types are displayed in the dropdown. Also I am able to save a group without selecting a group type and the group saves with the correct group type if only one possible.
[Group Type BUG.docx ](https://github.com/SparkDevNetwork/Rock/files/4566047/Group.Type.BUG.docx)

### Steps to Reproduce
1. Go to 'Group Viewer'
1. Click on 'a Parent Group'
1. Click to add child to selected
1. Go to the new group to name it
1. The Group Type dropdown displays all available group types.

**Expected behavior:**

I would expect to see only that group type or child group types available.

**Actual behavior:**

I can leave the group type blank and save the group. The group saves with the correct group type, if there is only one available group type. If there is more than one group type available, a group type must be chosen out of the long list of group types.

### Versions
* **Rock Version:** [10.2]
* **Client Culture Setting:** [ [RockDiagnostics-AZ-ROCKFE01.txt ](https://github.com/SparkDevNetwork/Rock/files/4566045/RockDiagnostics-AZ-ROCKFE01.txt) en-US]

**Comment by cabal95** [comment]
Confirmed on our install as well. I'm not 110% sure that this used to work, but I'm about 98% sure it used to work.

**Comment by karenn-ccbc** [comment]
I can confirm that it used to work. We were in 9.4 until 2 weeks ago and it did work.

**Comment by karenn-ccbc** [comment]
Our Dev box is still in 10.1 and it is working correctly there.
![image](https://user-images.githubusercontent.com/35667472/80843070-f2b6ae80-8bc8-11ea-8242-6d1d35aae506.png)

**Comment by MikeDPeterson** [comment]
Fixed with https://github.com/SparkDevNetwork/Rock/commit/a77c61acc06eb246764b5e2e526a1f3c02440793
