### ISSUE TITLE
History Block causing issue with Room Management Plug-In

### ISSUE THREAD

**Issue by charlottedean** [SparkDevNetwork/Rock#4220]
If you create a new Room Management Reservation and then try and access that created reservation, it times out.  Below are some extra screenshots in regards to the issue.

1. Create a new Room Management Reservation
2. After creation, go back to the reservation you just made and try and access it.  
3. Server will time-out

**Expected behavior:**

You should be able to see the newly created reservation without a problem. 

**Actual behavior:**

You are unable to see it and the server timeout. 

### Versions

* **Rock Version:** 10.2
* **Client Culture Setting:** en-US

![FireShot Capture 112 - Exception Detail - Rock RMS - rock bridgepointfl com (1)](https://user-images.githubusercontent.com/47043721/81001300-85e42400-8e15-11ea-8479-2f892fc653d2.png)
<img width="397" alt="Screen Shot 2020-04-20 at 12 55 14 PM" src="https://user-images.githubusercontent.com/47043721/81001341-92687c80-8e15-11ea-9b41-98172e91469a.png">

**Comment by nairdo** [comment]
@charlottedean I installed the plugin on the demo site here:
https://www.rocksolidchurchdemo.com/page/2617?ReservationId=1

I've not been able to reproduce this, but I'm interested in knowing what your History Log block's settings look like.  Here's what they are set to on the demo site for reference:

![image](https://user-images.githubusercontent.com/383807/81080978-3bf74e80-8ea6-11ea-83c7-cf6a083ca72d.png)

**Comment by charlottedean** [comment]
Nick, I re-added the history block to the page with the above settings you showed from the demo-site.  I went in to create a new reservation and I got this:
![roomreservationtimeout](https://user-images.githubusercontent.com/47043721/81221370-bd3b0800-8fb0-11ea-8663-21090ab6b61d.png)

It gets created:
![Screen Shot 2020-05-06 at 3 46 52 PM](https://user-images.githubusercontent.com/47043721/81221447-d80d7c80-8fb0-11ea-9308-b21f65341b45.png)

And, when I go to click on the reservation I get this: 
![roomreservationtimeout2](https://user-images.githubusercontent.com/47043721/81221579-08edb180-8fb1-11ea-88dd-e6e2b9cad67a.png)

So I'm at a loss as to what is causing the error.  If we take the history log-off, it works AND it was working fine until I added a new reservation type I feel like that shouldn't affect that.

**Comment by charlottedean** [comment]
I'm also starting to see similar timeout issues with items related to finances as well.  Including payments in event registrations, people's contributions, and transaction details.  
![financetimeout](https://user-images.githubusercontent.com/47043721/81437052-809a1880-9138-11ea-80d9-861ee2223612.png)

**Comment by cabal95** [comment]
There is likely some performance work that needs to be done on the server - but my thought is the history block should probably catch that error and display a nice error on page instead of blowing up everything and preventing other parts of the page from working correctly.

**Comment by charlottedean** [comment]
Daniel, do you think it should do something like this instead, this is on my communication history page. 
![Screen Shot 2020-05-08 at 3 43 19 PM](https://user-images.githubusercontent.com/47043721/81443113-cb209280-9142-11ea-90c7-05d023d8c7da.png)

**Comment by cabal95** [comment]
Yea that is my thought, something like that which doesn't blow the entire page out.  That way it's just the history that doesn't work rather than the entire page.

**Comment by charlottedean** [comment]
I think Kelley with KFS ended up getting this fixed.  This is what I got from her recently;. "I rebuilt the primary key on the History table".  I will continue to monitor but I think it's fixed.

**Comment by nairdo** [comment]
@charlottedean  Can you also run this query and report back your results?

```Sql
SELECT COUNT(*) FROM [History]
```

**Comment by cabal95** [comment]
Thanks @nairdo ! I know I'm guilty myself in my own plugins of assuming a query will work when I really should be wrapping it inside a try/catch block and doing proper error handling. Usually prefaced with the thought "pfft, there is no way this query would ever fail."

**Comment by charlottedean** [comment]
Hey, @nairdo Below is what I got: 
![sqlrunresults](https://user-images.githubusercontent.com/47043721/81457830-b9041b80-9165-11ea-99b1-b4a2e7adc3c3.png)
