### ISSUE TITLE
Lava Tester Debug Tooltip

### ISSUE THREAD

**Issue by milescarmany** [SparkDevNetwork/Rock#4222]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

In the Lava Tester, there is an `Enable Debug` option with an (i) tool tip. The tool tip includes a link to the Model Map. The link is hard coded to `http://www.churchitnetwork.com/ModelMap`

### Steps to Reproduce

1. Go to 'Power Tools > Lava Tester'
2. Click on the (i) to expose the tool tip for the Enable Debug option
3. Click on 'Model Map'
4. See error page on ChurchIT Network website

**Expected behavior:**

It would probably be prudent to link to the Model Map of the current instance.

**Actual behavior:**

Attempts to navigate to a non-existant page of someone else' website.

### Versions

* **Rock Version:** Rock McKinley 9.4 (1.9.4.1)
* **Client Culture Setting:** en-US

Also tested on Demo.

**Comment by JimMichael** [comment]
The Lava Tester is a plugin, so I think this would need to be reported to those devs, not core team?

**Comment by jonedmiston** [comment]
Correct Jim. Closing this issue here. @milescarmany you might try the support link on the plugin.

**Comment by nairdo** [comment]
It's reported now here: https://github.com/CentralAZ/Rock-CentralAZ/issues/161

**Comment by milescarmany** [comment]
Thanks! That's slightly embarrassing, but I forgot that was a plugin we've had it so long.
