### ISSUE TITLE
Custom Grid Column Appears twice during export

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#4225]
### Description
Custom Grid Columns appear twice when exported to excel

### Steps to Reproduce
1. Go to the Group Viewer
1. Click on any group
1. Click on the block settings
1. Add a custom column using lava to that group
1. Try to export to Excel
1. notice the custom column exports twice.

See Example: [https://rock.rocksolidchurchdemo.com/page/113?GroupId=110&ExpandedIds=](https://rock.rocksolidchurchdemo.com/page/113?GroupId=110&amp;ExpandedIds=)

**Expected behavior:**

I would expect the custom column to appear once on the export

**Actual behavior:**

The custom column appears twice in the export

### Versions
* **Rock Version:** [10.2]
* **Client Culture Setting:** [en-US]

**Comment by crayzd92** [comment]
@jcjones37 this was fixed in 1.10.3 via https://github.com/SparkDevNetwork/Rock/issues/3950.
