### ISSUE TITLE
Content Channel Item Approval Buttons Not Showing

### ISSUE THREAD

**Issue by tstephens17** [SparkDevNetwork/Rock#4229]
### Description
Any new content channels created that require approval seem to be missing the buttons to set the status.

### Steps to Reproduce
1. Using the Rock Demo site, create a new content channel of the type website ads.
1. Go to add an item under that new content channel
1. Notice right away that the status buttons are not there.

**Expected behavior:**

To have the status buttons

**Actual behavior:**

There seems to be a space for them but they are not there.

### Versions
* **Rock Version:** [Rock McKinley 10.2 (1.10.2.3)]
* **Client Culture Setting:** [en-US]

**Comment by JRichmond27** [comment]
We have the same issue with our v9.4 Rock instance.

I also just tried it out on the v11 demo site with the same results. No status buttons.

**Comment by nairdo** [comment]
Hi @tstephens17 and @JRichmond27 For this item we are updating the block to let you know when** you need to set up some security permissions for the "Approve" role as shown here:
![image](https://user-images.githubusercontent.com/383807/85179345-94f02b80-b235-11ea-8427-573a13d90099.png)

_**when there are no roles/people listed in the Approve security action._

**Comment by JRichmond27** [comment]
So this is an instance where the "Rock Admin" security role doesn't override the permission settings?

**Comment by nairdo** [comment]
@JRichmond27 Are you asking if someone in the `RSR - Rock Administration` role can see the approval status button even if they are not in one of the roles listed under the "Approve" security permission (shown above)?  If that is what you are asking, No, the security checking checks the security.

**Comment by JRichmond27** [comment]
Ok, yeah that makes sense. I think I was picturing most other situations I've come across where `RSR - Rock Administration` is already in the inherited permissions by default.
