### ISSUE TITLE
DateTime Report Fields Only Show Date, No Time

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4230]
### Description

When choosing a "DateTime" field on a report, such as `CreatedDateTime`, the report output shows only the date portion, no time... even though the name of the field implies the time component.

### Steps to Reproduce

1. Create a Person Report based on some person DV
2. Add the `CreatedDateTime` field
3. Observe that the report output only shows the Date, not Date+Time. 

**Expected behavior:**

We debated in chat whether this was a bug or enhancement request, but decided to start with bug since choosing a field _named_ "SomethingDateTime" reasonably implies you'll get back the time as well as the date.

**Actual behavior:**

You get back only a date. The block seems to be hard coded this way, and the only way to get a real DateTime to display is via a Lava field with either person/group filters, or a entity command (for reports based on entities without Person/GroupById filters). But even worse, you then can't sort on that Lava field and have to include the actual SomethingDateTime field anyway (but hidden) just to sort on it.

If you deem this is Working As Designed, let me know and I'll submit it as an Idea instead. I do NOT think the current behavior should simply be changed from showing only Date to Date+Time on such fields, because it's likely that at least some people are _relying_ on the current behavior and would not _want_ the time component suddenly showing up in their report fields. 

It seems like the correct behavior would be a checkbox option on such fields to let the report user determine if they want to see only Date, or Date+Time.

### Versions

* **Rock Version:** 10.2

**Comment by cabal95** [comment]
We confirmed this behavior on our server as well.

**Comment by JimMichael** [comment]
Note the workaround for this behavior is:

1. Have the report return the desired DateTime field (e.g. CreatedDateTime) but hide it on the grid.

2. Add a Lava column that does `{{ CreatedDateTime }}`

The resulting field will show the full Date+Time.
