### ISSUE TITLE
Group Finder "Member count" option includes "inactive" members 

### ISSUE THREAD

**Issue by ambermccoy** [SparkDevNetwork/Rock#4232]
### Description
In the Group finder section, adding the Member count to the grid includes Inactive members as well as Active.  There should be a way to filter Active only. 

### Steps to Reproduce
1. [Go to Small Groups under the Connect area]
1. [Edit the Group Finder Configuration]
1. [Under Grid, Click "Show Member Count]
1. Click Save

**Expected behavior:**

Only the Active and/or pending member count should show

**Actual behavior:**

It counts ALL members in the group, even those who are inactive. 
![Screen Shot 2020-05-20 at 11 48 00 AM](https://user-images.githubusercontent.com/29762314/82468216-8a087680-9a90-11ea-91b8-04b1c30e7552.png)
![Screen Shot 2020-05-20 at 11 48 23 AM](https://user-images.githubusercontent.com/29762314/82468232-8d036700-9a90-11ea-9448-40d352814d27.png)
![Screen Shot 2020-05-20 at 11 48 30 AM](https://user-images.githubusercontent.com/29762314/82468247-91c81b00-9a90-11ea-9c91-0dc0dd82cc92.png)
![Screen Shot 2020-05-20 at 11 50 06 AM](https://user-images.githubusercontent.com/29762314/82468253-94c30b80-9a90-11ea-8de8-2d875909f417.png)

*### Versions

**Rock Version:**Rock McKinley 9.2 (1.9.2.5)

* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
...and additionally (https://github.com/SparkDevNetwork/Rock/commit/eaeff6b47854d5e4bfc7bd1312b729d0fff40207?w=1#diff-a5acca7b8c42d67d74153ab6899d81cfR119) there will also be a setting that the admin/web-admin can control to determine whether or not include pending members in the count.

**Comment by JimMichael** [comment]
Question: When the count is filtered to only active, does that then make the threshold (max members) count against only active? Or will all members (regardless of their status) count towards the group max?

**Comment by nairdo** [comment]
@JimMichael The setting does not effect the **max members capacity/threshold**. It still only considers "active" group members.
