### ISSUE TITLE
ufnCrm_GetAge blows up on people with no birth year

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4233]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If you have a person that has a Birth Month and Birth Day but no Birth Year, then the `ufnCrm_GetAge` SQL function throws a conversion error.

### Steps to Reproduce

1. Login to rock.rocksolidchurchdemo.com
2. Go to Noah Decker's record.
3. Edit Noah and set Birth Year to blank.
4. Run the query below and see error.

```
SELECT P.[Id],P.[BirthDate]
FROM [Person] AS P
WHERE P.[BirthDate] IS NOT NULL
  AND dbo.ufnCrm_GetAge(P.[BirthDate]) < 18
```

**Expected behavior:**

I would think that the SQL function should return NULL in this case. If you pass in a NULL date, you get back a NULL value.

**Actual behavior:**

You get the SQL error: `Error SQL Error! The conversion of a date data type to a datetime data type resulted in an out-of-range value. `

### Versions

* **Rock Version:** 10.2
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
I also noticed that our Process BI Analytics job has been failing for just as long as my custom query job with the above. So it's possible that job is also having a problem with null BirthYear's?

**Comment by JimMichael** [comment]
Is this the same bug as https://github.com/SparkDevNetwork/Rock/issues/3881 ?

**Comment by cabal95** [comment]
#searchfailure
