### ISSUE TITLE
Can't tap check-in areas checkboxes on latest develop branch on iPad

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4235]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

I'm not sure what, but something broke on the iPad with the re-skinning of the check-in setup page (i.e. the page where you select the theme, the kiosk and the check-in areas). The checkboxes no longer work on iPad. I tested with both the iPad client and a plain Safari (mobile) browser and got the same results.

The field will highlight briefly but the checkbox will never turn on (or off if it's already on).

### Steps to Reproduce

1. On iPad, open Safari and go to https://prealpha.rocksolidchurchdemo.com/checkin
2. Login as admin/admin
3. Select the Kiosk Device.
4. Try to tic any of the area check boxes.
5. Achieve frustration that they won't tic.

**Expected behavior:**

Check boxes should be able to be turned on/off.

**Actual behavior:**

I have a kiosk that can't be configured. :sad_panda:

### Versions

* **Rock Version:** `develop` branch as of 5/25/2020
* **Client Culture Setting:** en-US

**Comment by garrettjohnson** [comment]
Fixed by removing FastClick which is no longer needed by using a variety of methods.

- `touch-action: none` for IE & Rock Checkin Client
- Viewport Meta Tag for iOS & Chrome (https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away)

Testing Reference
https://patrickhlauke.github.io/touch/
https://patrickhlauke.github.io/touch/tests/event-listener_touch-action-none.html
