### ISSUE TITLE
The Twitter Share lava on stock Content Channel Item View is broken.

### ISSUE THREAD

**Issue by MicahO** [SparkDevNetwork/Rock#4236]
### Description
The twitter sharing functionality built into the Content Channel Item View is broken. It may have been copied and pasted from another source; it refers to Calendar Items for no apparent reason. 

### Steps to Reproduce
1. Go to https://rocksolidchurchdemo.com/page/460?Item=21.
1. Click the Twitter icon to share on Twitter.
1. Notice that Twitter loads, but nothing is shared.

**Expected behavior:**

When clicking the "Share on Twitter" button, the current page should be shared on Twitter. Ideally it would use a Javascript mini-window similar to the functional Facebook one.

**Actual behavior:**

When clicking the "Share on Twitter" button, Twitter opens but nothing is shared. 

### Versions
* **Rock Version:** 10.2
* **Client Culture Setting:** en-us

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1184327244339414">image.png</a>

**Comment by MicahO** [comment]
The proper URL seems to be:

http://twitter.com/share?text={{ Message }} &url={{url}}

**Comment by nairdo** [comment]
@garrettjohnson  I think this is the commit for this fix, right? https://github.com/sparkdevnetwork/rock/commit/2d6120a130de39b0484d72a581ac09196311e2ac  (If so, I think you mentioned the wrong github issue... which would explain why it never closed this out.)

**Comment by nairdo** [comment]
I re-traced this fix and I believe it is in this migration roll-up commit: https://github.com/SparkDevNetwork/Rock/commit/75b0d46c217293b68262e494c2b27275ac5e652d (v11.1) / https://github.com/SparkDevNetwork/Rock/commit/05573e70bbe8960c2cef449c084385f325b4a0c5 (pre-alpha v12) In there, it will replace the stock "Content Channel Item View" block instance on the stock "Series Detail" page.
