### ISSUE TITLE
Can't remove registration from Event Occurrence page

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4245]
### Description
When you are viewing a Calendar Event Item Occurrence and click Edit, it will show you any linked Registration Instances, along with an Edit and Remove button. The Remove button does not work. It causes a postback and refreshes the page, but doesn't remove the linkage.

### Steps to Reproduce
1. Log onto the demo site.
1. Go to https://rock.rocksolidchurchdemo.com/page/402?EventCalendarId=1&EventItemId=2&EventItemOccurrenceId=2
1. Edit the occurrence.
1. Click Use Existing Registration Instance and select the Summer Camp 2016 instance.
1. Save and reload the page (just so everything is clean).
1. Edit the occurrence again.
1. Click the Remove button.
1. Notice the spinner comes up for a moment and then the page refreshes but the linkage is still there.

**Expected behavior:**

One of two things.

1) The registration instance linkage should be removed.
2) JavaScript confetti should flutter over the screen with a message that reads "you fell for it!".

**Actual behavior:**

No confetti, just me demonstrating Einsteins principal on Insanity by clicking the button over and over again hoping for a different outcome.

### Versions
* **Rock Version:** 10.2, 10.3-alpha
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1197854243701025">image.png</a>

**Comment by melodielange** [comment]
Appears to be fixed
