### ISSUE TITLE
Content Item Detail Block Displays Incorrect Order Values for Child Items

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#4248]
### Description
When editing a content channel item that has children which are manually ordered, the content item view block does not display the correct order index of the child items (they are all listed as 0).

### Steps to Reproduce
1. Create a Content Channel Item within a channel that has "Child Items Manually Ordered" set to `true`.
1. Create multiple items that are children of the first item.
1. View the publish page (/page/342) fo the first item you created.
1. See that the value of `Order` for each item is `0`, rather than the actual order index value (0, 1, 2, 3, etc).
1. See that changing the order of the children does not correctly set the new indexes for children items of the parent.

**Expected behavior:**

Content Item Detail block should correctly display the order index of child items, and those order values should be accurately updated when the child items are re-ordered in the UI.

**Actual behavior:**

All child item Order values are `0`, and reordering them does not update those values.

![image](https://user-images.githubusercontent.com/2465823/84194678-63c07000-aa6b-11ea-9b0f-00d4e7ed4224.png)

![image](https://user-images.githubusercontent.com/2465823/84194906-ba2dae80-aa6b-11ea-8fa6-72ae08e14e86.png)

### Versions
* **Rock Version:** 1.11.0.17
* **Client Culture Setting:** en-US

**Comment by MikeDPeterson** [comment]
Cherry picked into pre-alpha-release with https://github.com/sparkdevnetwork/rock/commit/77abb0ddc35560184bc0ffd857148827c563e9fa
