### ISSUE TITLE
SQL Error "failed to convert varchar to float" on SQL Server 2019 without cumulitive updates

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4251]
### Description
> NOTE: This is mostly for posterity, but it may be worth update the SQL function in question anyway to have a single RETURN statement.

On SQL Server 2019 15.0.2070.41, when the Compatibility Level is also set to 2019, the `ufnCrm_GetAddress` function fails with a `Error converting data type nvarchar to float` message. The cause of this is that SQL 2019 added a feature called UDF Function Inlining (https://docs.microsoft.com/en-us/sql/relational-databases/user-defined-functions/scalar-udf-inlining?view=sql-server-ver15&viewFallbackFrom=sql-server-2017).

Apparently the implementation was slightly bugged with UDF Scalar functions that have multiple RETURN statements. Basically, the final RETURN statement would set the maximum length that could be returned (with a minimum of 1 char). So even though you request Street 1 which is `123 Abby Way`, it only returns `1`. This was verified by updating the function to `RETURN 'ABCDE'` at the end, which then caused it to return `123 A`.

In addition to that error, or maybe because of it, this would cause the function to try to convert the value to a float for some reason, which would fail.

Somewhere between the GDR1 version and CU4 they have fixed this problem. Meaning, SQL Server 2019 CU4 works perfectly fine, but plain SQL Server 2019 throws the exception.

Again, this ONLY applies if your compatibility level is also set to 2019. So if you upgraded from a previous version of SQL Server you won't run into this. But if you do a fresh install you might. Azure SQL also seems to have this problem - though it's possible at this point any new databases get created on servers running CU4. We did run into this with one person in chat and their Azure version number reported it was running the GDR1 version rather than a CU version.

As part of our testing, the ufnCrm_GetAddress function always worked anytime we removed all but one of the RETURN statements.

### Steps to Reproduce
1. Install Rock on a server running SQL Server 15.0.2070.41
1. Set a home address for Admin Admin person.
1. Run the following SQL: `SELECT dbo.ufnCrm_GetAddress(1, 'Home', 'Street1')`
1. See error.
1. You can also see the error from a Report that uses the Address field, as it uses this function under the hood.

**Expected behavior:**

No error, though Microsoft seems to have fixed this internally in later versions.

**Actual behavior:**

User may or may not get weird errors about converting nvarchar to float that make no sense in the context of what they are doing.

### Possible Solution
It may be smart to update the function to declare a local variable that contains the result and instead of using multiple RETURN statements, have them instead set the value of that variable and then at the very end of the function return that variable's contents.

### Versions
* **Rock Version:** 10.2, 10.3 (though any version is affected)
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
Nice troubleshooting!
