### ISSUE TITLE
Compiling Rock theme immediately after restart results in missing LESS file error

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4255]
### Description
After installing the 10.3 beta on a copy of our production system, I edited the Rock theme so I could change the brand color. Upon clicking `Save` it compiles the files but spits out an error message:

```
You are importing a file ending in .less that cannot be found [_root.less].
```

The theme _appears_ to have compiled successfully, as my header and button color has changed (though I did have to reload a couple times, so maybe it was still compiling after the error was displayed).

This appears to only happen during a short window after restarting Rock. I continuing to try recompiling the theme, after a while it eventually completed successfully and would not error again after that. But restarting Rock causes the error again.

![image](https://user-images.githubusercontent.com/1119863/84711398-16d11380-af1b-11ea-9cf1-5e5e2ed4f5f1.png)

### Steps to Reproduce
1. Restart Rock
1. Go CMS Configuration, Themes, Rock Theme
1. Change the Brand Color
1. Click Save
1. See error

**Expected behavior:**

No errors?

**Actual behavior:**

Big badda boom.

### Versions
* **Rock Version:** 10.2
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
I've seen this, too, but it's been happening to me since 9.x, at least. Since I never noticed any actual problem I didn't report it... and immediately recompiling again often resulted in no error for me.

**Comment by cabal95** [comment]
Confirmed on Demo site. This isn't a 10.3 issue but an existing issue. Updated original report with new steps, but TL;DR; it happens during a short window immediately after restarting Rock.
