### ISSUE TITLE
Communication Send did not honor recipient preference (v10.3 beta)

### ISSUE THREAD

**Issue by jennifertroeger** [SparkDevNetwork/Rock#4257]
#3728 # Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? **This was not done, as this was part of 10.3 beta testing.**
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

As part of beta testing v10.3 I discovered that sending a communication via a communication list and segment filter, while selecting "Recipient Preference," did not honor the recipient preference on the profile.

### Steps to Reproduce

1. Set your communication preference as sms
2. Create new communication to a communication list, using a segment filter to narrow the list down to just yourself (or a test group of people)
3. Select "Recipient Preference" as the medium
4. Enter content for both email and SMS
5. Click "Send Test" on sms screen, to ensure that sms is working ([Test] sms is received)
5. Click Send on communication

**Expected behavior:**

Expected behavior is that you (the recipient) will receive an sms communication, and not the email.

**Actual behavior:**

The actual behavior is that an email is received. What's interesting is that I did a comparison of sending an email directly to myself (ie. NOT starting with a communication list and segment filter), and when doing so the sms was received (i.e. expected behavior = actual behavior).

### Versions

* **Rock Version:** Rock McKinley 10.3 (1.10.3.7)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Hi Jennifer @jennifertroeger ,  I've spend a bit of time investigating this one and I wanted to confirm a few things with you...

When someone subscribes to a communication list, their communication preference should be recorded in the associated communication list group. 

For example, Cindy Decker selects SMS for the delivery preference on the "Parents of Children" communication list as seen here:

![image](https://user-images.githubusercontent.com/383807/92833335-97be7080-f38d-11ea-8e24-5b89856286d7.png)

Can you confirm that (in your example) the person's preference is being recorded properly in that group?  For example, if I look at Cindy Decker's group membership in that group, I see her communication preference is "SMS" here:
![image](https://user-images.githubusercontent.com/383807/92833921-3ea30c80-f38e-11ea-85c9-f78005b89edf.png)

When I test this by sending to the "Parents of Children" list and choose "Recipient Preference" as seen here:

![image](https://user-images.githubusercontent.com/383807/92835291-ea992780-f38f-11ea-8816-efe3bdfdfd95.png)


... it is sending her an SMS and not an email.

![image](https://user-images.githubusercontent.com/383807/92834411-da347d00-f38e-11ea-97b1-d5f8ea12a876.png)

I'm wondering if perhaps you're thinking it would be using the 'Communication Preference' on the person's Person Profile:

![image](https://user-images.githubusercontent.com/383807/92834541-018b4a00-f38f-11ea-8e80-ce8829341bd8.png)

If so, that could explain the situation.  If so, that is an interesting idea -- and perhaps you might consider opening a Idea on the http://community.rockrms.com/ideas board to perhaps add a switch on the Communication List group type to disable allowing individual delivery preference for each communication list (group) and instead force Rock to use the person's individual profile Communication Preference.

Let me know what you think.

**Comment by jennifertroeger** [comment]
HI @nairdo, you are correct in that I was referring to the communication preferences set on the person profile. We don't show the communication preference options publicly for the communication lists, so I wasn't even thinking of that as an option. When we ask people if they want to subscribe to texts we actually opt them into a completely separate group because it's easier for us to manually manage the group members and their preferences that way (our communication lists won't load for us, regardless of changing the DTUs to the max allowable).

**Comment by nairdo** [comment]
Thank you @jennifertroeger .  I'll close this issue out.  But please let us know as you move through v11 and v12 if you run into any other complications.  Besides #4428, the only thing that you might notice is that in v12.1 (https://github.com/sparkdevnetwork/rock/commit/03c444656ee617c122837ab0fcff4e8e911a5cc9) we now default a new group members to 'Recipient Preference' instead of defaulting to 'Email'.
