### ISSUE TITLE
Checking Inactive on a site seemingly does nothing

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#4259]
### Description
When going to Admin > CMS > Sites and choosing a site and hitting edit. When you uncheck Active to make the inactive, nothing happens. The site is still active.

### Steps to Reproduce
1. Go to Admin > CMS > Sites and choose a site and hitting edit
1. Uncheck Active
1. Hit save
1. Go visit site and it is still active

**Expected behavior:**

I would expect marking a site as inactive would mean that site is no longer active and therefore the site would not display

**Actual behavior:**

Making a site inactive does nothing

### Versions
* **Rock Version:** [10.2]
* **Client Culture Setting:** [EN-US]

**Comment by nairdo** [comment]
@timlem Greetings Tim, The Active/Inactive checkbox is really only for keeping old sites off the main site list.  You can filter them on the Site List block: 
![image](https://user-images.githubusercontent.com/383807/86376104-601fa380-bc3b-11ea-9dcc-8f8e9acdfbbf.png)

So, although it is currently working as designed, we are open to having a community discussion about the other idea you raised. 
There is some risk with preventing a site (and it's pages) from operating (if marked inactive), but... if you're still interested in suggesting this feature, could you jump over to the http://community.rockrms.com/Ideas board and start the conversation there.

**Comment by timlem** [comment]
Thanks @nairdo will do
