### ISSUE TITLE
Home Phone Number is Deleted if Cell Number is Identical

### ISSUE THREAD

**Issue by alyssa-pathway** [SparkDevNetwork/Rock#4263]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

On a person's profile page, when entering either a Cell number or a Home number, if the numbers are identical (Home and Cell), the Home number will be deleted. 

### Steps to Reproduce

1. Go to a person's profile page where they only have one phone number, and click to edit the person details
2. Type in the phone number that already exists on profile into the phone type that remains (Home and Cell).
3. Hit Save.

**Expected behavior:**

The Home Phone Number and the Cell Phone Number would be identical and visible on the person's profile.

**Actual behavior:**

The Home Phone Number is deleted and the Person History shows that it was deleted by the person logged in.

### Versions

* **Rock Version:** 10.2
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
I'd consider that a feature! I get really frustrated when I see people enter the same number for home and cell ;-) (Oh, and I duped it on 10.2 and 10.3)

**Comment by azturner** [comment]
FYI, The change to this behavior has also caused issues for our Planning Center Sync plugin. When syncing records from Planning Center if a person has same home and cell phone number, the sync is updating those in Rock, but the framework then removes the home number so the sync continually tries to keep syncing it back every time it runs.

**Comment by nairdo** [comment]
Before I close this issue, I wanted to say -- I did indeed double check with team here, and this change was by-design.  It was done in 2018 via https://github.com/SparkDevNetwork/Rock/commit/f1a90052df9d1ed7f7b937fd79efaf218d888609#diff-a7ce184b71f6c44e9ab074b4e5bf1c22 to address issue #2616 (Prevent duplicate phone numbers for a person).
