### ISSUE TITLE
SMS Conversations Block does not allow selection from Multiple SMS Pipelines

### ISSUE THREAD

**Issue by hbcpn** [SparkDevNetwork/Rock#4265]
### Description
Curiosity simply got the best of me with the Alpha release announcement of v11 and I was just poking around the Pre-Alpha site to see how multiple SMS Pipelines work. If you're able to setup more than one SMS Pipeline, I assumed that the SMS Conversations block would be able to handle multiple but quickly realized that it not the case and may be confusing. I know that dips into a Feature Request territory more-so than a bug per-se. But since v11 isn't released adding this selection to the Features Request site doesn't make sense to me either.

### Steps to Reproduce
1. Go to the Communications - SMS Pipeline page
1. Click on "+" and add an additional SMS Pipeline, provide a name, description, enable Is Active, save new pipeline
1. Edit the newly created SMS Pipeline and drag in a SMS Conversations action to the new SMS Pipeline
1. Navigate to People - SMS Conversations page [https://rockrmslatest.com/page/550 ](https://rockrmslatest.com/page/550)
1. Select the Block Configuration and edit the SMS Conversations block
1. Note that this block can only use the original default SMS Pipeline and SMS Conversations action. Even when an additional SMS Conversations block is added to this page or any other page in Rock you cannot select the newly created SMS Pipeline or SMS Conversations action.

**Expected behavior:**

Even though I don't anticipate using this for our small church, I can imagine the larger churches that have wanted multiple SMS Pipelines in the first place will also want the ability to create several SMS Conversation pages (Campus 1, Campus 2, Campus 3, main, internal org, youth, small groups, care, etc.) Not being able to define which pipeline to use within the block seems to be a problem that will likely arise.

**Actual behavior:**

No setting to select the SMS Pipeline / SMS Conversation combination that you'd like the block to display. Only the default SMS Pipeline/SMS Conversation can be used for the SMS Conversations block.

### Versions
* **Rock Version:** [Rock McKinley 11.0 (1.11.0.18)]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Greetings @hbcpn  Let me make sure we're both on the same page and that I'm not missing something.  At a high level, the SMS Pipeline is just a one-way funnel that directs content into various places -- one such place is _to_ the _SMS Conversations_ pipeline action.   That's just to say the data will be recorded as an SMS Conversation.   (_There is only **one** SMS Conversation system/sub-system._)  The filter on that action can be used to help with the decision (if needed):
![image](https://user-images.githubusercontent.com/383807/86301332-7b969a00-bbba-11ea-8a34-469bc30b2657.png)


Also, if you wanted, the SMS Conversations block can be configured to only show conversations for a _particular_ Rock SMS Phone Number (Admin Tools > Communications > SMS Phone Numbers) using the **Allowed SMS Numbers** block setting:

![image](https://user-images.githubusercontent.com/383807/86300681-79cbd700-bbb8-11ea-8d98-9d48ee577179.png)

If that's the sort of thing you were looking for, you can close this issue.  If you're looking for a different kind of feature, can you kindly you close this item and perhaps describe the feature over on the [Community Ideas board](http://community.rockrms.com/ideas)?  Thanks!
