### ISSUE TITLE
[Alpha] Rock Cleanup Old Sessions has badly formed query that takes forever to run.

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4269]
### Description
This query:

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Jobs/RockCleanup.cs#L932

```cs
                    var interactionSessionIdsForInteractionChannel = interactionsToDeleteQuery
                        .Where( i => i.InteractionSessionId != null )
                        .Where( i => !interactionSessionIdsOfDeletedInteractions.Contains( i.Id ) )
                        .Select( i => ( int ) i.InteractionSessionId )
                        .Distinct()
                        .ToList();
```

... is a bad form to use with queries (I have learned myself from having run into this in my own code numerous times). This part:

```cs
.Where( i => !interactionSessionIdsOfDeletedInteractions.Contains( i.Id ) )
```

causes sever slowness in SQL. Because `interactionSessionIdsOfDeletedInteractions` is a C# list of ID number, the query ends up looking like this:

```sql
SELECT
       [Distinct1].[InteractionSessionId] AS [InteractionSessionId]
      FROM ( SELECT DISTINCT
           [Extent1].[InteractionSessionId] AS [InteractionSessionId]
          FROM  [dbo].[Interaction] AS [Extent1]
          INNER JOIN [dbo].[InteractionComponent] AS [Extent2] ON [Extent1].[InteractionComponentId] = [Extent2].[Id]
          WHERE ([Extent2].[InteractionChannelId] = @p__linq__0)
              AND ([Extent1].[InteractionDateTime] < @p__linq__1)
              AND ([Extent1].[InteractionSessionId] IS NOT NULL)
              AND ( NOT ([Extent1].[Id] IN (28854702, 28854744, 28854749, 28854751, 28854769, 28854810, 28854826, 28854844, 28854846, 28854866, 28854869, 28854870, 28854871, 28854928, 28855056, 28855128,
```

And the list of numbers grows. In our case, that list of numbers was over 6,000 long. I saw "over" because I don't know how long it was, I just know it was at least that long. When I captured the running query it only captured 65,535 characters of the query and that would have fit 6,000 Id numbers. That kind of query absolutely kills SQL Server. Anytime a C# list of Ids or Guids (or any value really) is used with a `.Contains()` type query, it should be limited to 100 at most.

In this case, since we are just taking the results and adding them to the `interactionSessionIdsForInteractions` list anyway, we would likely achieve far better performance by just not performing this check to see if we already have that Id and instead just build one giant list, not caring about duplicates. Then after we have then all, we can Distinct() the list in C#.

In our case, the the Old Sessions cleanup part of the job took over 20 minutes to run. By contrast, on 10.2 the entire job normally runs in under 4 minutes.

The data was taken from the previous nights backup, which means it was a normal amount of interactions to be cleaned up. So this wasn't months and months worth of interactions that suddenly had to be cleaned up.

### Steps to Reproduce
1. Have a decent number of interactions to be cleaned up.
1. Run the Rock Cleanup Job.
1. Watch your SQL Server weep tears of shaved metal.

**Expected behavior:**

SQL Query should be performant.

**Actual behavior:**

It's uhh, not?

### Versions
* **Rock Version:** 1.11.0.19
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
The job finally finished (after 1 hour), here are the final results of counts and duration of each segment:

![image](https://user-images.githubusercontent.com/1119863/85804496-a4241d00-b6fe-11ea-9bbe-b3b424c767b7.png)

**Comment by bjwiley2** [comment]
https://github.com/SparkDevNetwork/Rock/commit/3932eca4394faa1f4047f53e0541915e61d252ad
