### ISSUE TITLE
Unable to get to raw Gender value for use in Workflow Fields

### ISSUE THREAD

**Issue by SteveSwaringen** [SparkDevNetwork/Rock#4275]
### Description
When using a Gender field type with Workflow Forms, the form does not correctly preset the Gender drop-down to the current value of the attribute.

### Steps to Reproduce
1. Go to RockSolidChurchDemo.com. Log in as Admin. Go to the Admin's Person Detail Page (Alisha Admin) and set her gender to Female (or Male ... works the same either way).
1. Create a Workflow with a Gender field type attribute. Preset the gender to CurrentUser | Property:'Gender','RawValue'. Display the Gender field in a form. ![Gender Workflow](https://user-images.githubusercontent.com/45042927/86011219-0f613e00-b9e2-11ea-89dc-ff783eee83c3.png)
1. Execute the workflow (as Alisha Admin, whose gender is now female). Note that the gender field on the form is blank. ![Gender Workflow Form](https://user-images.githubusercontent.com/45042927/86011364-34ee4780-b9e2-11ea-8e2c-8fb10df39c0c.png)
1. **Do not submit the form.** (This would overwrite the Gender attribute with what the form thinks is the current value, which is none.) Instead, back out the the Workflow Configuration page, click on Manage Workflows, and open the Workflow Detail for the workflow you just ran. Click on Activities and note that the Gender attribute is correctly set to Female (but was not displayed correctly by the form). (https://user-images.githubusercontent.com/45042927/86012973-40427280-b9e4-11ea-8161-dd1ae5b38feb.png)

**Expected behavior:**

The gender field on the workflow form should be preset to the current value.

**Actual behavior:**

The gender field on the workflow form is set to no value.

** Additional Information **

I spent some time tracing this with the VS debugger. The code is trying to preset the drop-down to "Female" where the drop-down is expecting an integer corresponding to the enumerated type (0, 1, **2**). Since it doesn't recognize "Female" as a valid value, it sets it to blank.

### Versions
* **Rock Version:** [10.2 (1.10.2.3)]
* **Client Culture Setting:** [en-US] ![Gender Workflow Log]

**Comment by cabal95** [comment]
I think this is a by-product of the fact that Rock essentially treats enumerations (like Gender) as string values. This makes sense 99.9% of the time. In this case, the actual numeric value is needed.

The best way to deal with this might be with a minor enhancement to the `AsInteger` filter. I just checked with a breakpoint, and the actual value is indeed still a true Enum value. So the `AsInteger` filter could check if the input is an Enum and if so just cast it to int.  Currently it converts it to a String first (for type safety), which is why using that filter as-is wouldn't work.

@SteveSwaringen Incidentally, the `Property` filter doesn't have any qualifiers, meaning `RawValue` makes no difference to the value returned. I also updated the title to reflect that this isn't a problem with workflows themselves, but rather the inability to get to the raw value of the field.

**Comment by SteveSwaringen** [comment]
Thanks for the pointer about the Property filter and RawValue.

The Lava documentation here (https://community.rockrms.com/lava/workflows) says workflows store Gender as a number (perhaps a string rather than an integer, but string representation of an integer). Based on my experiments, I believe this documentation is correct.

The dropdown list is populated with value/text pairs where the values are, likewise, string representations of integers, and the text is the humanized string value of the enumerated type. But when the workflow form action tries to set the current value of the dropdown, the string it passes is the humanized string (“text”, not “value”).

I associated this with workflow processing because I’ve seen this behavior consistently with workflows and the Gender field type, but not with ordinary blocks that use the Gender field type. (Of course, the code-behind for the blocks accesses the drop-down directly and can pass the correct value. The point is that these blocks are running different code to preset the drop-down than the workflow action.)

**Comment by nairdo** [comment]
Hi @SteveSwaringen 

> The Lava documentation here (https://community.rockrms.com/lava/workflows) says workflows store Gender as a number (perhaps a string rather than an integer, but string representation of an integer). Based on my experiments, I believe this documentation is correct.

Yes, that documentation is for when a Field Type is used in an attribute.  Something more like this:

![image](https://user-images.githubusercontent.com/383807/86156665-29bb1a80-babb-11ea-8bc2-d2ac34f8d80c.png)


In that case, the gender field type's 'RawValue' attribute can be obtained like this:

`{{ Workflow | Attribute:'GenderAttribute','RawValue' }}` --> returns "1"
while this `{{ Workflow | Attribute:'GenderAttribute' }}`  --> returns "Male"

**Comment by SteveSwaringen** [comment]
Thanks for the clarification, Nick. I apologize for not being more clear in the description of the scenario I included in the bug report, but that’s exactly the circumstance I’m describing. I’m trying to use an attribute of the Gender Field Type in a workflow, and trying to preset the value of that attribute before presenting it in a form, and the form is not responding correctly to the preset value.

**Comment by nairdo** [comment]
@SteveSwaringen  Ok, great.  I did confirm that using this Lava in the Lava Run action will work in your situation:

```
{% assign g = CurrentPerson | Property:'Gender' %}
{% if g == 'Male' %}1{% elseif g == 'Female' %}2{% endif %}
```

**Comment by SteveSwaringen** [comment]
In case anyone else comes across this thread, I've found another trick that seems to work reliably.
`{{ person.Gender | ToJSON }}`
returns the numeric value of the enumerated type.
