### ISSUE TITLE
[Alpha v11] Waitlist Send Email Preview is not previewing correctly in Chrome

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#4277]
### Description
I am only noticing this issue on Chrome. I have not experienced this issue on Safari or Firefox. I don't know if there is a UI fix that can be done just for Chrome.

When moving a registrant out of a registration waitlist, after selecting Send Email the waitlist confirmation email preview displays blank. I clicked on the Source tab and could see the code. I switched back to Preview and it was still blank. After toggling these two buttons, the Preview would display correctly. However, if toggled between the two again, it may go blank again. It wasn't constantly visible.

I updated my Chrome browser (Version 83.0.4103.116) to see if that would fix it. This time, the Preview displayed correctly the first time but after toggling the buttons the Preview window went blank again.

![](https://user-images.githubusercontent.com/5738650/86156062-fbddd200-baca-11ea-9b7a-d3939dafabb9.png)

![](https://user-images.githubusercontent.com/5738650/86156181-2a5bad00-bacb-11ea-914d-70bf0295c1bc.png)

### Steps to Reproduce
When using Chrome

1. Place an individual in a registration waitlist.
1. Move the individual out of the waitlist and select Send Email
1. If Preview is blank, toggle between Source and Preview to see if it displays. 
1. See error

**Expected behavior:**

The expected behavior is for Preview to display without issue, even when toggling between Source and Preview.

**Actual behavior:**

In Chrome, it is in consistent but will cause the Preview window to display blank.

### Versions
* **Rock Version:** v11.0.19 Alpha 
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
@BEGamache I am not able to replicate this even when I add invalid markup. Can you attach the source text?

**Comment by BEGamache** [comment]
Good catch @ethan-sparkdevnetwork, I didn't think about it being the message code. The message is the default text but it is something in the global header attribute that is causing the issue. When I went into the template and removed that attribute from the communication I did not notice the issue.
