### ISSUE TITLE
15K calling campaign takes a long time to open self assign dialog

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4282]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We created a DataView that includes all people who are "involved" ("is an eRA" type list) to use in a calling campaign. This DataView contains 17,400 individuals. We then created our calling campaign based off this and set the "Limit to Head of House". We are also using "As Needed" and "365 days recurrence". Settings below.

![image](https://user-images.githubusercontent.com/1119863/86979759-f3bf0b80-c136-11ea-9b05-1f18c415d96d.png)

This nets us 15,300 heads of family to call (apparently we have a lot of single people), as it shows 15,310 pending connection requests.

### Steps to Reproduce

1. Configure a Data View with a ton of people, like around 20,000.
2. Create a Calling Campaign as pictured above, resulting in around 15,000 people to call.
3. Go to the Connections screen and click the "+ Campaign Requests" button.
4. Wait.
5. Wait some more.
6. Consider that it may be broken.
7. Dialog finally shows up.

I also tried a smaller subset of about 3,500 heads of household to call. Even that took about 30 seconds for the dialog to open.

**Expected behavior:**

Dialog should open within a few seconds.

**Actual behavior:**

It feels like an eternity.

### Versions

* **Rock Version:** 10.3
* **Client Culture Setting:** en-US

**Comment by adamhann** [comment]
Thank you Mike!
