### ISSUE TITLE
Rock runs migrations even if previous ones failed.

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4283]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Something changed in recent versions of Rock. In the past, if a plugin migration failed, Rock would not attempt to run the following migrations.  Now, Rock runs all the migrations and records that they all completed successfully even if an earlier migration failed. This basically breaks all plugins if something happens during a migration run. Worse, it now leaves the Rock instance in a frankly broken state that is going to be a major headache to fix.

![image](https://user-images.githubusercontent.com/1119863/87063581-6a094f80-c1c3-11ea-9d28-9af781295e10.png)

All those migrations are from the same plugin. So migration 10 failed, and then for some reason Rock ran the rest of the migrations and recorded in the database that all 39 ran correctly - which they obviously did not.

This was reported by a user on 10.2 and confirmed just now on the Rock demo site which is currently on v11.

Marking as critical since this leaves the database in a very inconsistent state that has to be manually cleaned up with various SQL statements.

### Steps to Reproduce

1. Go to Rock demo site
2. Install Project Management plugin.
3. Go to Exception Log
4. See errors

**Expected behavior:**

Plugin migrations should not run unless all previous migrations successfully ran.

**Actual behavior:**

They run either way.

### Versions

* **Rock Version:** 10.2 (first reported)
* **Client Culture Setting:** en-US

**Comment by MikeDPeterson** [comment]
@cabal95 I wasn't able to reproduce this in v10.2, but was a bug in v11.0

**Comment by cabal95** [comment]
Thanks @MikeDPeterson, that makes me feel better. This originally came up due to a bug report on my plugin from somebody on 10.2. All the migrations ran, but a bunch of stuff that is created by the migrations doesn't exist. When I tested on v11 and saw what was happening I assumed it was doing the same on 10.2 as well. We're still trying to figure out why the migrations claim to have run but the data isn't all there.

**Comment by JimMichael** [comment]
Is this really fixed in v11? What would a site do to get the fix that is already on v11beta?

**Comment by JimMichael** [comment]
Nevermind... just sawl Nick's post in beta channel.
