### ISSUE TITLE
[Beta] Internal Portal Rock logo wrong color

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4285]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

This might be just a bug due to somebody messing with the theme on the demo site, but it's doing it on both the demo site and the pre-alpha site so I think it's legit.  Basically, the Rock logo in the corner is orange, until you hover over one of the side menu's, then it's color changes to match the menu.

![image](https://user-images.githubusercontent.com/1119863/87068055-e43cd280-c1c9-11ea-9ba0-c44d6e165686.png)

![image](https://user-images.githubusercontent.com/1119863/87068175-0afb0900-c1ca-11ea-84f9-1d1111f533a3.png)

Maybe it was intentional, but I found it rather distracting for the color to toggle everytime I hovered over a menu.

### Steps to Reproduce

1. Install v11
2. Mouse over the menu and back a few times.

**Expected behavior:**

As I said, personally I find it distracting so I am expecting it to be a consistent color.

**Actual behavior:**

Color toggles back and forth.

### Versions

* **Rock Version:** v11
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
I can confirm this behavior, but assumed it was an intentional design decision in v11. (top bar goes all the way across page in brand color, logo changes to menu color when it pops out)

**Comment by jonedmiston** [comment]
Yes, this was intentional. When it remained the brand color it stuck out. After reviewing it with both states we decided this was the best course.
