### ISSUE TITLE
Value is Not Saved When Updating `Item URL` for Content Channel RSS

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#4289]
### Description
When editing a Content Channel, the value for `Item Url` is not saved to the database when it is changed in the block.

See this video of the issue (this recording is from 10.3.7, but the issue also exists on the pre-alpha server at 11.0.20): https://drive.google.com/file/d/1s371Wa9_16fFwvCsMB8OnmYNY2S1ii2V/view?usp=sharing

### Steps to Reproduce
1. Go to 'Admin Tools/CMS Config/Content Channels'
1. Click on any content channel
1. Click to edit the content channel properties
1. Enable RSS for the channel, and give any value to the `Item Url` field
1. Click Save
1. Click to edit content channel properties
1. See that the previously entered value was not saved

**Expected behavior:**

Any Item Url value entered into the field should be saved when the user clicks "Save".

**Actual behavior:**

Value for Item Url property is not saved when the user clicks "Save".

### Versions
* **Rock Version:** 11.0.20
* **Client Culture Setting:** en-US

**Comment by briankalwat** [comment]
Also, just came across this - it looks like whatever value you specify for `Content Channel Item Publishing Point` on the channel actually gets saved to the `Item Url` column in the database.

**Comment by nairdo** [comment]
@briankalwat The `contentChannel.ItemUrl = tbContentChannelItemPublishingPoint.Text;` was being overwritten by the empty textbox field (`tbItemUrl`) on that line with the `contentChannel.ItemUrl = tbItemUrl.Text;`  ...so we decided to just do away with the erroneous/extra `tbItemUrl.Text`.
