### ISSUE TITLE
Location GUID not setting state correctly in Address field type

### ISSUE THREAD

**Issue by TheDunagans** [SparkDevNetwork/Rock#4291]
### Description
When setting a workflow attrubute using SQL to select the GUID of the person's family Location, State defaults to AL 
It performs as expected on the demo site, but doesn't perform as expected on https://rockrmslatest.com/

### Steps to Reproduce
1. Build a workflow with an attribute that uses the Address field type
1. Add a form to the workflow and make Address visible and editable
1. Add a SQL run to fill out the address fields
1. State defaults to AL

To test, 

SELECT
 TOP 1 [Location].[Guid]
FROM 
 [Person]
JOIN [GroupMember] ON [GroupMember].[PersonId] = [Person].[Id] 
JOIN [Group] ON [Group].[Id] = [GroupMember].[GroupId] AND [Group].[GroupTypeId] = 10
JOIN [GroupLocation] ON [GroupLocation].[GroupId] = [Group].[Id]
JOIN [Location] ON [Location].[ID] = [GroupLocation].[LocationId]
JOIN [DefinedValue] ON [DefinedValue].[Id] = [GroupLocation].[GroupLocationTypeValueId] 
 AND [DefinedValue].[DefinedTypeId] = 15
 AND [DefinedValue].[Value] = 'Home'
WHERE
 [Person].[Id] = 4 

**Expected behavior:**

State accurately sets the Location 

**Actual behavior:**

State defaults to AL

### Versions
* **Rock Version:** 11.0 (1.11.0.18)
* **Client Culture Setting:** en-US

**Comment by randyjreed** [comment]
I have confirmed this as well. Any work around?

**Comment by calvmann** [comment]
We are experiencing this on V11 as well

**Comment by USCBigRed** [comment]
> I have confirmed this as well. Any work around?

have you figured out a work around for this?
