### ISSUE TITLE
Cannot mark a communication list inactive in v11.

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#4299]
### Description

Create a communication list with 1000 or more (that is what I have tested) individuals and try to mark it as inactive. This times out.

### Steps to Reproduce

1. Go to Communications
2. Click on Communication Lists
3. Create a new list or find an existing list with 1000 + individuals on it
4. Mark list as inactive
5. This times out.

**Expected behavior:**

Should finish and not time out.

**Actual behavior:**

After waiting about 3 minutes in times out. 

### Versions

* **Rock Version:** Rock McKinley 11.0 (1.11.0.3)
* **Client Culture Setting:** EN-US

**Comment by adamhann** [comment]
We are experiencing this same issue in 10.3.
