### ISSUE TITLE
Grid Size Preference higher than the Initial Page Size causes errors (10.3, 11.0)

### ISSUE THREAD

**Issue by tcavaletto** [SparkDevNetwork/Rock#4308]
### Description
When trying to edit detail blocks or click buttons on a page with a grid, if the user has a grid size preference over the initial page size, they will encounter an error. For example, if on the accounts page they have a list of 500+ accounts ( simulated in the screenshot by a list of attribute values ), and have a grid page size preference set to 5000, it will throw the error below when clicking the Edit button on the account detail block. This has been tested on a fresh 10.3 install and the 11.0 demo server.

![image](https://user-images.githubusercontent.com/5482014/88312587-2df7e380-ccc7-11ea-8328-3968bf58fc7f.png)

### Steps to Reproduce
1. Go to Finance > Accounts
1. Add a Dynamic Data Block below the accounts list to simulate 500+ accounts. Set the Query to 'Select Id, EntityId, Value From AttributeValue'
1. Refresh the page. Scroll down and set your page size to 5000. 
1. Once the page loads the rows, refresh it.
1. Click the Edit button on the Account Details block.
1. See error

**Expected behavior:**

The Accounts List block should hide itself as a secondary block and the Account Detail block should switch to edit mode.

**Actual behavior:**

A 'The table must contain row sections in order of header, body, then footer.' Error is thrown. Should you set the page size to 50 and refresh the page, you're able to edit the account again.

### Versions
* **Rock Version:** 10.3, 11.0.3
* **Client Culture Setting:** EN-US

**Comment by MrUpsideDown** [comment]
This issue has been fixed with this commit:
https://github.com/SparkDevNetwork/Rock/commit/ebec76d1f717b51ae27d838a9c83b51345a6894f#diff-c1e3cf0109163046d12304f8b0a40540
