### ISSUE TITLE
GatewayMigrationUtility block has reference to missing DLL

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4310]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

This is only an issue for the Rockit SDK.  The Gateway Migration Utility block has a reference to namespace Rock.MyWell. This appears to be a separate project in the Rock repository.  But a compiled version of it does not seem to ship with Rock. It is not on my production instance or my Rockit dev instance.

This means everytime I update my Rockit instance I have to manually delete this block so that I can get the site to compile (I normally turn off site compilation, but after an upgrade I turn it on to see if any custom blocks have deprecation warnings).

### Steps to Reproduce

1. Open rockit SDK
2. Try to build site.
3. See error.

**Expected behavior:**

Rockit SDK should build without error.

**Actual behavior:**

It has an error.

### Versions

* **Rock Version:** v11
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
This is a known issue and is pending the eventual inclusion of that DLL into a future Rock release.
