### ISSUE TITLE
[Housekeeping] Dynamic Chart Block has Outdated SQL Example

### ISSUE THREAD

**Issue by TheArkChurch** [SparkDevNetwork/Rock#4315]
### Description
In the Dynamic Chart block, on the help text, on the query field, there is outdated SQL which refers to the PageView table which isn't in rock any longer. As a result this example query doesn't work and isn't helpful. There also seems to be a weird css styling issue on that block as well. It's making the help text show as a thin column on the left side of the block and it's not very readable.

### Steps to Reproduce
1. Go to any page with a Dynamic Chart Block or add the block to a page
1. Click on the Block configuration item on the admin bar at the bottom of the page to see the blocks config menu
1. Click on the configuration for the dynamic chart block
1. Scroll down to the sql field and click it's help text to see the invalid query and the weird behavior of the help text. Good luck coping that text.

**Expected behavior:**

The example sql query to be a valid query. And the ability to copy the query easily.

**Actual behavior:**

The query is outdated.

### Versions
* **Rock Version:** [Rock McKinley 10.3 (1.10.3.7)]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Although we updated the outdated SQL (back in v11 via https://github.com/SparkDevNetwork/Rock/commit/13c0be769646127982dcac2b8ef5488e8eec73a6) we're still unsatisfied with having this in the help text formatted the way it currently looks so we're keeping this open.

**Comment by jonedmiston** [comment]
Added the documentation as the default text of the SQL. This makes it easier to read and paints a nice sample chart to start with.
