### ISSUE TITLE
Transaction Matching - Add New Family

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#4316]
### Description

In transaction matching, when you click "Add New Family" - it now requires you to enter the First and Last Name of a spouse - even if the person is not married. It should also auto fill the last name if they are married in my opinion. 

### Steps to Reproduce

1. Go to Finance
2. Click on Batches
3. Click on a batch with checks in it that have not been matched to a record
4. Click on Add New Family
5. Enter family info and notice that Spouse is a required field. 

**Expected behavior:**
Spouse should not be required. Even if they are married you do not always know the spouse info off of a check

**Actual behavior:**

Spouse is always required

### Versions

* **Rock Version:** Rock McKinley 11.0 (1.11.0.3)
* **Client Culture Setting:** en-US

**Comment by jsw-austin** [comment]
Tried on Rock Solid Church Demo and verified that spouse is required.

**Comment by MCoulterFBCN** [comment]
We are only on 10.3 and have noticed this exists there as well.

**Comment by calvmann** [comment]
We have also noticed this.
