### ISSUE TITLE
Add Campaign Requests block error

### ISSUE THREAD

**Issue by tpcc-myles** [SparkDevNetwork/Rock#4318]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

After upgrading from v9.4 to v10.3, we upgraded/reinstalled the Connection Campaigns plugin from the Rock Shop.  Now, whenever we go to our Connections page (People > Connections), the following error is given in the Add Campaign Requests block.

![AddCampaignRequests](https://user-images.githubusercontent.com/68909388/88671652-8dce0000-d0b4-11ea-9c6e-546ff8854771.JPG)

### Steps to Reproduce

1. Start with a Rock v9.4 system
2. Install the Connection Campaigns plugin from the Rock Shop
3. Upgrade Rock to v10.3
4. Upgrade/install the Connection Campaigns plugin again
5. Navigate to the People > Connections page
6. See error from screenshot above

**Expected behavior:**

The Rock Shop would not allow upgrade/install of the Connection Campaigns plugin on a v10.x system, or the upgrade/install of the Connection Campaigns plugin on a v10.x system would not result in the given error.

**Actual behavior:**

The depicted error from above was given.

### Versions

* **Rock Version:** [Rock McKinley 10.3 (1.10.3.7)]
* **Client Culture Setting:** [en-US]

**Comment by tpcc-myles** [comment]
Thread on RocketChat related to this issue: https://chat.rockrms.com/channel/troubleshooting?msg=8TXQ4p36BnA7Sssk4

**Comment by nairdo** [comment]
We worked with Myles to repair his system (removing the extraneous DLL and putting the correct blocks back in place) and we also  deactivated all old versions of that plugin in the RockShop so this should not happen to anyone else.
