### ISSUE TITLE
Migration Helper inserts without checking for conflicts

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#4319]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We occasionally hit migration errors, both with our own custom migrations and with plugins such as Checkr, where the migration fails because it can't insert or update a record that conflicts with an existing record. In the case of a plugin I'm not sure how certain data is being created without coming from the migration, but in any case the migration SQL should be checking for any record that will conflict with existing records before attempting to insert. By not doing so, the entire migration fails and requires manual effort to determine the problem, especially if there are multiple conflicts (since only the first conflict is reported in the error log).

It should be noted that some MigrationHelper functions may check for the existence of a record with a particular guid, and will insert if that guid does not exist or update if it does exist.  But it does not check for records that might conflict with other constraints. AddAttributeQualifier, for example, will attempt to insert a record if the guid is not found even if there is already a record with the same AttributeId and Key.  This is something that happened to us during the first Checkr migration.

Side note, this is not just an issue in MigrationHelper, but in many migrations I have seen throughout core code, inserts are regularly scripted with no check for constraint issues.  It's my opinion that every insert and update should be written with the possibility in mind that the data could already exist to prevent unexpected failures.

### Steps to Reproduce

1. Delete a recent record from PluginMigration where the migration inserted new records
2. Restart Rock so it will attempt to run the migration again
3. See constraint error
(Of course this is a vague process for the sake of this error report and not necessarily the way that the bug happens in real life)

**Expected behavior:**

Migrations would run successfully even if some or all of the records already exist in the database, resulting in a PluginMigration record that prevents the migration from running again in the future.

**Actual behavior:**

Received error messages of constraint conflicts.

### Versions

* **Rock Version:** Rock McKinley 10.2 (1.10.2.3)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
I actually feel the opposite. I _want_ my migrations to fail in these cases because it's a situation that I didn't expect (and shouldn't happen in normal situations). In such unexpected situations, I think that the migration should indeed fail so that we can look into the reason for the failure and then decide whether we need to manually clean up some of the existing data that is in conflict or if we need to adjust the migration to handle the situation.

My 2 cents.

**Comment by chrismcgrath** [comment]
On further review some of the instances I've had trouble with have been modified in v11 so I'm closing this.
