### ISSUE TITLE
Empty Grid Warning when selecting a few people from the tags list to send a communication

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#4322]
### Description
If you go to a tag list where people are listed and you check all and hit communicate bubble it works. If you check a few instead of checking all you get a warning message, "Warning
Grid has no recipients"

### Steps to Reproduce
1. If necessary create a personal tag and tag people with tag.
1. Go to people > tags and select tag. 
1. Check 3 or 4 people
1. Hit the communicate button
1. Receive "Warning Grid has no recipients"

**Expected behavior:**

I would expect a new communication to be created with the selected people.

**Actual behavior:**

You receive the warning that the grid is empty.

![Screen Shot 2020-07-29 at 2 27 16 PM](https://user-images.githubusercontent.com/1486523/88838483-9ce1aa80-d1a7-11ea-8c81-9281b89b1eb7.png)

SIDENOTE - I checked people grid on dataviews and checked a few people and it worked fine. It seems to only be related to tags.

### Versions
* **Rock Version:** [11.0]
* **Client Culture Setting:** [En-US]

**Comment by notGerryMiller** [comment]
We are also seeing the same issue.

**Comment by bdeneal** [comment]
We are also having this issue and we are on 11.1.
