### ISSUE TITLE
Scrolling on iPad Check-In No Longer Works Intuitively

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4330]
### Description

I noticed this while testing v11, but then went back and noticed it on 10.3 as well, so something bad was introduced regarding scrolling check-in search results between 10.2 and 10.3.

The issue is that you can no longer scroll results in a sane way, but must actually use the hard-to-make-work scroll bar.

### Steps to Reproduce

1. On 10.3 or 11.0, using an ipad client for check-in, search for a partial phone number to bring back more results than can fit on the screen.
2. Attempt to scroll the list in a natural way by touching the list itself and moving your finger.
3. Observe that instead of it scrolling, you end up choosing a random family (whichever one ends up under your finger)

**Expected behavior:** 

The list of families would scroll in an intuitive, natural way, just like they do on v10.2 and prior. Prior to 10.3 the scrolling worked just as you would expect it to.

**Actual behavior:** 

Something changed at 10.3 and 11 where the scroll function no longer works as expected, and you end up selecting a family instead (the instant your finger touches the screen). Using the scroll bar itself VERY carefully does make it scroll... however, this cannot be a legitimate solution as it's not natural on a touch device, and is difficult to perform, anyway.... and our (all self-serve) users have been trained to touch the screen and scroll it in an intuitive way and this change makes the experience awful and frustrating.

### Versions

* **Rock Version:** 10.3, 11.0

Here's a video of me using the 1.8 ipad client on 10.2. You can't see my finger, but I'm just touching in the middle of the results list and it scrolls as expected
https://drive.google.com/file/d/1Ca0cJgFRy6v9KWLla7nYGslXLEHsklqx/view?usp=sharing

Here's one of me on v11 (10.3 acts the same) using the exact same ipad/client. When I go to touch the list to scroll it, I instead select the family that was under my finger
https://drive.google.com/file/d/1fme4A5jZF3DKXPiB0gisw_3brmTvtJyE/view?usp=sharing

**Comment by mikedotmundy** [comment]
I tested and confirmed this same behavior. I am on v11, iPad app 1.8.
