### ISSUE TITLE
Registrant List Not Sorting on Person Attribute

### ISSUE THREAD

**Issue by courtneycooksey** [SparkDevNetwork/Rock#4332]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When you have a Person Attribute that is shown in the Registrant Grid and you try to sort by that field the sorting is incorrect. I have spent some time debugging this and it looks like the issue is in Rock.ExtensionMethods.LinqExtensions.cs in the Sort function (Line 386). What is happening is that when it pulls the model to use for the custom sort value it is matching on the attributeValue.EntityId being equal to the model.Id, however the model is a registrant entity so matching on those fields is pulling the incorrect entity, the match when the attribute is a person attribute should actually be on attributeValue.EntityId = model.Person.Id. It seems like the attributeCache.EntityTypeId needs to be checked before the value for model is set. 

### Steps to Reproduce

1. Create a new Registration Template where the Registrant Form has a Person Attribute that will display in the grid
2. Create a Registration Instance
3. Populate the Registration Instance
4. Attempt to sort on the Person Attribute in the Registrant Grid

**Expected behavior:**

The values display in the desired sorted order.

**Actual behavior:**

The values are incorrectly sorted.

### Versions

* **Rock Version:** Rock McKinley 10.2 (1.10.2.3)
* **Client Culture Setting:** en-US

**Comment by courtneycooksey** [comment]
So I have a solution for this, but I'm not confident it's tested well enough to make a Pull Request.

**Comment by jonedmiston** [comment]
Hey @courtneycooksey ! How about make a PR and we'll take a look at it.
