### ISSUE TITLE
Cannot edit communication template header image

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4333]
### Description
Basically, we noticed on our own v11 instance that our communication templates do not let us edit the banner image. More specifically, it shows the wrong image and won't let us edit.  If we create a new communication and select our custom template, it shows our Shepherd logo in the banner image place.  But if we then try to edit the communication template, it shows the default rock placeholder image.  If we edit the source, we also see it's the default rock place holder image URL too.  If we fix that URL to be the correct one and then save or just switch back to preview, it reverts to the default rock place holder url.

### Steps to Reproduce
1. Login to rock demo site.
1. Go to Communication Templates.
1. Duplicate the Default template (this step may not be required, but it's what we have in our case).
1. Edit the Copy of Default template and change the banner url image to something else, for example `https://www.shepherdchurch.com/Content/EmailTemplates/email-logo.png`
1. Click Preview.
1. Notice it's still the old placeholder image.
1. Click back to Advanced.
1. Find the spot you just updated and notice it's also reverted back.
1. Beat your comm team back with a stick since they are clambering for you to make updates to the template.

This appears to be caused by the `id="template-logo" data-instructions="Provide a PNG with a transparent background."` attributes. If I change the id to something else AND remove the data-instructions (both must be done) then it seems like it will let me keep the image I expect to be there.

**Expected behavior:**

I should be able to edit the communication template.

**Actual behavior:**

I cannot edit the communication templates.

### Versions
* **Rock Version:** [Enter Rock version here]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by rutledgek** [comment]
So glad to find this issue.  I thought I was going insane. I see the same behavior on 10.3

**Comment by MikeDPeterson** [comment]
This is working as-intended, but it is confusing, and the help text didn't do a very good job of explaining it.  A img div with an id of 'template-logo' is a special div for the template editor. The 'src' of the 'template-logo' div is set by the image uploader. So, we updated the help text a little so it is a little clearer.
