### ISSUE TITLE
Checkin App Freeze on Unknown QR

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#4339]
### Description
When using the new barcode reading portion of the native Rock App; version 1.8; Upon scanning an unknown QR, the app freezes.  The only want to get the app back to a working state is to kill the app and restart it. This can be difficult when/if the iPads are locked in cases.

### Steps to Reproduce
1. Set the Checkin Device to [Has Camera] under Checkin Devices
1. Open the Checkin Application on the device
1. Set your configuration model and be sure to select the appropriate device.
1. Scan a QR code

**Expected behavior:**

* When scanning a QR code for Mobile Checkin - I would expect the Checkin Application to print tags
* When scanning a QR code that contains the alternate ID for a family - I would expect the Checkin Application to bypass name and phone search and go directly to the person select screen.
* When scanning an unknown QR code, specifically one that contains a link to an outside website (like Seat Reservations) - I would expect the Checkin Application to produce an error message and return you to the welcome screen.

**Actual behavior:**

* When scanning a QR code for Mobile Checkin -The Checkin Application to print tags
* When scanning a QR code that contains the alternate ID for a family - The Checkin Application will bypass name and phone search and go directly to the person select screen.
* When scanning an unknown QR code, specifically one that contains a link to an outside website (like Seat Reservations) - The checkin application freezes.  The only way to recover is to kill the app (double tap home and swipe up on the app). Then restart the app.

### Versions
* **Rock Version:** [11.0]
* **Client Culture Setting:** [en-US]

**Comment by MichaelAllen** [comment]
Can you share the barcode that is causing issues for you? When I scan a QR linking to a [random URL](https://rock.barefootchurch.com/GetQRCode.ashx?data=https%3A%2F%2Fapp.barefootchurch.com&outputType=svg) I get a message saying `"Sorry, there were not any families found with the selected identifier."` (Rock v11.0.1, iOS v13.6, App v1.8)

**Comment by jcjones37** [comment]
So weird… now I am not experiencing it locally or on the demo site. HAHA.

I wonder if it was my local device that I was testing on.  I will keep pushing it through tests. If I experience any changes, I will let you know.

Jason Jones 
Ministries Project Manager
CedarCreek Church

Click HERE<https://calendly.com/jasoncjones37/meeting> to schedule a meeting with me

**Comment by nairdo** [comment]
@jcjones37 Were you able to reproduce the issue again?  If not, I'd say to close this out (or let me know and I can close it for you).

**Comment by jcjones37** [comment]
Good call @nairdo I closed it!

**Comment by carriewhite** [comment]
We have print outs of a QR code that guests can scan with their phone to initiate the mobile check-in process.  We've seen freezing issues when they have taken that and held it to the camera for an iPad that is in mobile check-in mode.

**Comment by jonedmiston** [comment]
@carriewhite can you email (jon(@)sparkdevnetwork.org) or Rocket.Chat me an example of the QR code? Also, is it consistent or only happens occasionally?

**Comment by carriewhite** [comment]
> @carriewhite can you email (jon(@)sparkdevnetwork.org) or Rocket.Chat me an example of the QR code? Also, is it consistent or only happens occasionally?

@jonedmiston sent via chat DM.  Thanks!
