### ISSUE TITLE
Simple Communications Paste  from Word  on Win10, Firefox/Chrome inserts in reverse order

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4340]
### Description
This happens on the simple communication page for sure, possibly others as it's likely an issue with  the editor itself. Some combinations of browser and  OS cause the "Paste from Word" feature to insert text in reverse order. i.e. if you click the button and enter the text:

```
Hello
Line 2
```

Then click the Insert button, it gets inserted into the message as:

```
Line 2

Hello
```

The test was performed on Windows 10 2004, with both Firefox and Chrome.

### Steps to Reproduce
1. Go to the New Communication page
1. Click on Simple Editor
1. Scroll down to  the Message section.
1. Click the Paste from Word button.
1. Type two lines of text
1. Click Insert
1. See text in reverse order.

**Expected behavior:**

Text should be in the same order as it was typed (or pasted from Word).

**Actual behavior:**

Text paragraphs are in reverse order, requiring manually fixing things up.

### Versions
* **Rock Version:** 11.0
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
This might be the same as this really old (and apparently un-reproducible) issue https://github.com/SparkDevNetwork/Rock/issues/1990

If it can be reproduced at will now, that's progress!

**Comment by Tschrock** [comment]
I can reproduce this with both the "Paste Text" and "Paste from Word" buttons on Chrome, Firefox, and Safari on macOS Catalina. It started happening after we upgraded to v11 - I see a commit there about updating summernote, so that's probably what triggered it.

**Comment by tstephens17** [comment]
We can reproduce it in v11 as well.

**Comment by michaeldegnanhbc** [comment]
We can also reproduce After upgrading to V11 on multiple machines and browsers.

**Comment by chrismcgrath** [comment]
Just heard about this from one of our staff members as well, when trying to paste this text:

> We are so excited you registered for a Block Group! Be on the lookout for an email from your Block Leader. In the meantime sign up for our Parent E-news and follow us on Facebook, Instagram and Spotify. We can't wait to rock with you!
> If you missed our Swag Bag hand out, we would love to get a bag in your hands! Email promiseland@willowcreek.org to set up a time on Tuesdays or Thursdays from 1-4:30pm to pick yours up. :)
> PromiselandKids

We get this instead:

> 
> PromiselandKids 
> to set up a time on Tuesdays or Thursdays from 1-4:30pm to pick yours up. :)promiseland@willowcreek.org If you missed our Swag Bag hand out, we would love to get a bag in your hands! Email 
> . We can't wait to rock with you!Spotifyand Instagram,Facebook and follow us onParent E-newsWe are so excited you registered for a Block Group! Be on the lookout for an email from your Block Leader. In the meantime sign up for our

It may be worth noting that "Parent E-news", "Facebook", "Instagram", "Spotify", "promiseland@willowcreek.org" and "PromiselandKids" are all hyperlinks that did seem to paste correctly but did impact the order of words pasted.  Pasting the same text from Word without any of the hyperlinks puts the paragraphs out of order but the words themselves are in the right order within each paragraph.

**Comment by notGerryMiller** [comment]
We are having this same issue also.  We are on 11.1.

**Comment by TheVillageChurch** [comment]
We are also experiencing this issue. Does anyone know where this stands on the priority list?

**Comment by nairdo** [comment]
At the moment, we're leaning toward a full replacement of Summernote (the component that has the underlying WYSIWYG [paste issue](https://github.com/summernote/summernote/issues/2772)) for something simpler than what Summernote provides.  I don't have a timeline for that yet but we're also investigating a possibility of a custom summernote patch to get us some relief until the replacement.

**Comment by joshuahenninger** [comment]
We have confirmed that this issue is resolved in the Communication Entry Obsidian block on the Next Generation framework.
