### ISSUE TITLE
Registration Instructions Image

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#4341]
### Description
When building an Event Registration, if you are displaying an image in the Registration Instructions field; and ONLY an image, the image will not show up on the external page.  If you include text in the Registration Instructions field. The image will also appear.

### Steps to Reproduce
1. Go to 'Event Registrations'
1. Click on 'an instance'
1. Click 'edit'
1. Provide an image (and only an image) in the instructions field.

* https://rock.rocksolidchurchdemo.com/RegistrationInstance/1

1. Go to external site 

* https://rock.rocksolidchurchdemo.com/page/413?RegistrationInstanceId=1

1. Notice that no image appears.
1. Go back to the edit screen.  Add text
1. Go back to the external site
1. Notice the image and the text appear.

**Expected behavior:**

Previously (I would image pre-v.11) the Image would show on the external site with no need for text.

**Actual behavior:**

In order for an image to appear on the event registration instructions, you also need text.

### Versions
* **Rock Version:** [11.0]
* **Client Culture Setting:** [en.US]

**Comment by cabal95** [comment]
This is likely a side effect of this PR https://github.com/SparkDevNetwork/Rock/pull/3970 which was to fix #3937.

Since an image-only content does not have any text content, the method we are using to detect  "blank" instructions thinks there is nothing to display so it doesn't show it.
