### ISSUE TITLE
Enabling Exclusive Routes breaks Admin Toolbar popups

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#4346]
### Description
Enabling Exclusive Routes for a site breaks the settings popups in the admin toolbar (The popups show a 404 page).

![firefox!UNITO-UNDERSCORE!2020-08-14!UNITO-UNDERSCORE!12-18-34](https://user-images.githubusercontent.com/2406499/90270816-d3b2f400-de28-11ea-9310-38183e5f838a.png)

### Steps to Reproduce
1. Go to the Advanced Options for a Site and turn on the "Enable Exclusive Routes" option
1. Go to the site and attempt to open the Page Properties from the Admin Toolbar

**Expected behavior:**

The Page Properties popup opens

**Actual behavior:**

It shows a 404 page

### Versions
* **Rock Version:** 11.0, prealpha
* **Client Culture Setting:** en-US

**Comment by TheArkChurch** [comment]
I can confirm. Turning this flag on breaks the admin toolbar, as well as the lets encrypt plugin.

**Comment by cabal95** [comment]
@TheArkChurch For the Lets Encrypt plugin, can you try going to Admin > CMS Configuraiton > Routes, and look for the route for `.well-known/acme-challenge/{Token}`. Edit that route and enable the Is Global option and see if that fixes the plugin?  If so I will update the plugin to enable that flag for everyone.

**Comment by TheArkChurch** [comment]
> @TheArkChurch For the Lets Encrypt plugin, can you try going to Admin > CMS Configuraiton > Routes, and look for the route for `.well-known/acme-challenge/{Token}`. Edit that route and enable the Is Global option and see if that fixes the plugin? If so I will update the plugin to enable that flag for everyone.

That fixed the plugin issue.
