### ISSUE TITLE
Connection Activities - Inactive

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#4348]
### Description
When you mark an activity as [Inactive] in Connections, the activity still shows up as a selectable option.

### Steps to Reproduce
1. Go to 'Connections'
1. Click on 'Settings'
1. Click on your Connection Opportunity
1. Click Edit
1. Drop down the header for 'Activities'
1. Click Edit on a given Activity
1. Mark that Activity as inactive by unselecting the [Active] checkbox
1. Go to any connection within that opportunity (as if your working the connection)
1. Click the [+] sign in the bottom right corner
1. Notice the inactive activity is still available in the dropdown.

**Expected behavior:**

I would expect that when the activity is no longer active, the activity would not be available for selection.

**Actual behavior:**

The inactive activity is still available for selection and does not honor the active checkbox.

### Versions
* **Rock Version:** [11.0]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
FYI. This fix is not in the 11.1 alpha, but will be in the v11.1 beta.
