### ISSUE TITLE
Minor Typo In Assessment Email URL

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4351]
### Description

Within the Request Assessments workflow, the _Send Assessment Custom Email_ action constructs a URL via `{% capture assessmentsLink %}{{ 'Global' | Attribute:'PublicApplicationRoot' }}/assessments?{{ Person.ImpersonationParameter }}{% endcapture %}`

Because `PublicApplicationRoot` has its own trailing `/`,  the `/` before `assessments` is an error and results in a url that looks like `https://myserver.com//assessments...` 

This doesn't actually seem to prevent the URL from working (at least on Chrome or FF) but it's still an improperly-constructed URL.

The _Assessment Request_ System Communication has the identical error where it constructs the same URL.

* **Rock Version:** 10.2+

**Comment by mikedotmundy** [comment]
I can submit a new issue if needed.
I have noticed this same issue in other places in Rock. 

1. In the file: wwwroot/Themes/Flat/Assets/Lava/RegistrationListSidebar.lava — Line 10
2. In the file: wwwroot/Themes/Stark/Assets/Lava/RegistrationListSidebar.lava — Line 10
3. If you create a new registration template, and show the communication settings, in the Reminder Email, — Line 49. Then in the Payment Reminder — line 43. Then in the Wait List Update - Lines 21 and 29. 
4. Under system communications, in the expiring Credit Card notice — Line 11. (The link is good, but the text that displays has the extra ‘/’ )

**Comment by nairdo** [comment]
> I can submit a new issue if needed.

@mikedotmundy That won't be necessary.  We'll use your list above when we sort out the solution.

@JimMichael  It looks like we're going to change that global attribute to something that will require the trailing slash, append on e if it's missing, and then we'll remove the extra /'s (in Lava) and the code that's double-checking to a `EnsureTrailingForwardslash()`.
