### ISSUE TITLE
Event Registration Filters (Only when coping)

### ISSUE THREAD

**Issue by tstephens17** [SparkDevNetwork/Rock#4352]
### Description
When you copy an event registration instance that has filters. You cannot edit the filters on the copy. The button appears to be there. Your mouse changes icons when you hover over it. If you click, you can even see the filter icon. But nothing happens on the click. This error is present in the console after the click.

![image](https://user-images.githubusercontent.com/32707751/90638861-dd0ed880-e1fb-11ea-9f79-583755c31217.png)
![image](https://user-images.githubusercontent.com/32707751/90639125-42fb6000-e1fc-11ea-943d-0dba8d5ae1e4.png)
![image](https://user-images.githubusercontent.com/32707751/90639165-51e21280-e1fc-11ea-9f6a-89e6065b6e29.png)

### Steps to Reproduce
1. If you go to the demo before it gets refreshed: https://rock.rocksolidchurchdemo.com/page/403?RegistrationTemplateId=5
1. The campus attribute has a filter and experiences the error.
1. If it has been reset, create a event registration with a filter.
1. Make a copy
1. See the error on the filter icon.

**Expected behavior:**

To be able to edit the filter settings after a copy.

**Actual behavior:**

Unable to edit the filter settings.

### Versions
* **Rock Version:** [11.0 (1.11.0.3)]
* **Client Culture Setting:** [en-US]

**Comment by melodielange** [comment]
Appears to be fixed
