### ISSUE TITLE
Event Registration Filtered Question Removes Previous Filled in Answers

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#4354]
### Description
When you have a filtered question on an event registration and a second filtered question when you choose the second filtered question answer it wipes all of the filtered questions answers that you had previously filled in.

Fill out first answers
![Screen Shot 2020-08-19 at 4 14 37 PM](https://user-images.githubusercontent.com/33845027/90690346-27fa1180-e237-11ea-85c9-b5d85a17aee2.png)
Then choose 1 for the 3rd question
![Screen Shot 2020-08-19 at 4 14 46 PM](https://user-images.githubusercontent.com/33845027/90690351-2af50200-e237-11ea-89d5-a77f0af11eb7.png)
Then blanks out first text box.  Fill out 4th answer
![Screen Shot 2020-08-19 at 4 14 52 PM](https://user-images.githubusercontent.com/33845027/90690361-2e888900-e237-11ea-942e-d86ccabaa874.png)
Then choose no on second option and it blanks out 4th answer
![Screen Shot 2020-08-19 at 4 14 56 PM](https://user-images.githubusercontent.com/33845027/90690368-30eae300-e237-11ea-8591-e3af1969950e.png)

As an aside this can get really weird with many filters.  It took a while to figure out what was breaking it as everything was interplaying with everything else and wiping out answers left and right.

### Steps to Reproduce
1. Create a registration template
1. Create a single select question with multiple options
1. create any type of registrant attribute that is filtered based on the single select option above
1. Create a second single select question with options
1. create a second registrant attribute that is filtered on the question above
1. create an instance
1. try and fill out instance
1. when the second single select is chosen it will wipe your answers from previous filtered questions

**Expected behavior:**

Your answers stay recorded

**Actual behavior:**

Wipes your answers

### Versions
* **Rock Version:** [v11]
* **Client Culture Setting:** [EN-US]

**Comment by azturner** [comment]
FYI, Scottsdale Bible Church uses a lot filtered fields in their event registrations and after updating to v11, this issue was affecting a lot of their registrations. We found that if we reverted this change: https://github.com/SparkDevNetwork/Rock/commit/60feb6bc, 
it "fixed" this issue for them.

**Comment by nairdo** [comment]
Thanks for the heads-up @azturner.  We are working on a v11.2 release for a fast turn around that will include several new bugs (like this one) that might not make it into v11.1 (which is going beta next Wed).
