### ISSUE TITLE
ENH: Put event name on next line in confirmation email

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#4364]
### Description
Registration confirmation emails show long event name inconsistently in Outlook and gmail.

Line height correctly spaced in Outlook.  Not correctly spaced in gmail.

Example from user:

![<a href="https://user-images.githubusercontent.com/4658177/90830628-d913b100-e2f6-11ea-89c2-46e19b30b422.jpg">https://user-images.githubusercontent.com/4658177/90830628-d913b100-e2f6-11ea-89c2-46e19b30b422.jpg</a> confirmation-email-outlook]()

### Steps to Reproduce
1. Set up event with a long name. 
1. Register for the event.
1. View the confirmation email in ... Outlook / gmail.
1. See error

**Expected behavior:**

The confirmation email should show the event name with correct line spacing. 

**Actual behavior:**

gmail compresses the heading line spacing based on fixed line height??

**Suggested fix:**

Option 1.
Put the event name on its own new line, e.g. -

**Event Confirmation:
Church - 23 Aug 2020 - 10 AM**

Option 2
Correct the line spacing of the line for Outlook/gmail.

### Versions
* **Rock Version:** Rock McKinley 10.2 (1.10.2.3)
* **Client Culture Setting:** en-NZ

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1200468700813053">image.png</a>

**Comment by garrettjohnson** [comment]
This was fixed in v13.0 when the default setting of the Email medium's "CSS Inlining Enabled" was changed to true. With this setting enabled, the heading receives a line-height of 1.4, which removes the overlapping problem.

![image](https://github.com/SparkDevNetwork/Rock/assets/374209/1ff4ef1e-f351-4016-a205-e23a8418ac22)
