### ISSUE TITLE
Family Members not sorted by age in Public Profile Edit block

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4366]
### Description
On the My Account page, in the Public Profile Edit block, family members are not sorted by age, but rather (I think) by the order they are added to the family. This can make the oldest child appear last. Replicated on Demo site, v11.1.

### Steps to Reproduce
1. On the internal site, go to my account (example: https://rock.rocksolidchurchdemo.com/Person/1) and add 2 kids with different birthdays. Add the youngest kid first, then the older kid. 
1. Notice on the internal site that the kids are sorted by age, even though you added them backwards.
1. Go to the external site, to the MyAccount page. (example: https://rock.rocksolidchurchdemo.com/myaccount) and notice that the kids are sorted in the order they were added. 

**Expected behavior:**

I would expect that children are sorted by age (oldest to youngest).

**Actual behavior:**

They are sorted by (I think) the order they are added to a family.

![](https://user-images.githubusercontent.com/23226974/90939698-6c71e280-e3da-11ea-8b3a-f69acdb5b29f.png)
![](https://user-images.githubusercontent.com/23226974/90939704-6f6cd300-e3da-11ea-89ee-79ee5211d986.png)

### Versions
* **Rock Version:** [11.0]
* **Client Culture Setting:** [en-US]

**Comment by jrockman13** [comment]
This also happens in check-in and our families have expressed confusion or frustration multiple times.

**Comment by mikedotmundy** [comment]
With the addition of a Lava Template to control the view of the /MyAccount page in v12.0, I added this line to the `Assets/Lava/PublicProfile.lava` file, @ line 218: `{% assign FamilyMembers = FamilyMembers | OrderBy:'Person.Age desc' %}`. Adding this Lava sorts the family members properly now.
