### ISSUE TITLE
Simple Communications Paste from Word on OSX 10.15, Chrome triggers attachment upload

### ISSUE THREAD

**Issue by BemaDavidBensen** [SparkDevNetwork/Rock#4372]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

In Chrome on Mac, open the simple communication block, click the paste from word or paste plain text. Watch the attachment show image.png multiple times and the paste does not work. 

![2020-08-26_09-17-52 (1)](https://user-images.githubusercontent.com/29557172/91315736-aa298f00-e77d-11ea-8131-50a8ac29faa8.gif)

### Steps to Reproduce

1. Go to the communication block
2. Click on paste from word or paste plain text
3. Paste text
4. Watch the attachment show image.png

**Expected behavior:**

The paste should att the text and the attachment should not be triggered

**Actual behavior:**

After hitting paste, the attachment upload is triggered and shows multiple image.png

### Versions

Rock McKinley 12.0, Rock McKinley 11.0 
EN US

**Comment by nairdo** [comment]
@BemaDavidBensen Would you say this is similar or the same as issue #2994 (it _seems_ like a duplicate to me)?

**Comment by BemaDavidBensen** [comment]
> @BemaDavidBensen Would you say this is similar or the same as issue #2994 (it _seems_ like a duplicate to me)?

I missed this one. Poor searching on my part. Thank you!
