### ISSUE TITLE
v11 Breaks PFP edit scheduled transaction feature

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4385]
### Description
v11 made a change for NMI that had a side effect of breaking the ability to edit scheduled transactions on PFP.  The specific change seems to be this line:

https://github.com/SparkDevNetwork/Rock/commit/6953aa1986d46c9c84663ce818333425c0807c01#diff-cc906466befdfd7459a8d18dac72318eR1178

We reverted that one line and we can again edit our PFP scheduled transactions.

I am marking this as confirmed because changing that one line back fixed the issue, but if somebody else on PFP and v11 can verify as well by editing an existing recurring transaction that would probably help the core team out.

### Steps to Reproduce
1. Create a scheduled (recurring) PFP transaction
1. Now go back and edit that scheduled transaction.
1. Change the amount but use the "do not change / use existing" feature for the payment details
1. Try to save/submit.

![image](https://user-images.githubusercontent.com/1119863/91888352-00e10e00-ec41-11ea-9430-78e56eecf8a2.png)

The actual NRE error appears to be due to this line https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.PayFlowPro/Gateway.cs#L909 where it expects a valid currency type in the reference transaction, but since the previous mentioned change creates an empty one, we get an NRE.

**Expected behavior:**

Users should be able to edit existing recurring payment profiles and use existing payment details.

**Actual behavior:**

They can't and get a null reference exception.

### Versions
* **Rock Version:** v11.0
* **Client Culture Setting:** en-US

**Comment by taylorbrooks** [comment]
Hey this broke our integration too! 

How do we advise our customers on the fix? Just upgrade to v11.2?

cc @joshcrews @jsw-austin

**Comment by jonedmiston** [comment]
@taylorbrooks I would recommend testing v11.2 for your plugin to ensure the fix also resolved your issue. Might also recommend that you join the alpha testing teams. That would be a great way for you to test you integration against the releases.

**Comment by taylorbrooks** [comment]
@jonedmiston It appears that an upgrade to 11.2 doesn't fix it either. 

Were there any interfaces changes to the `ScheduledTransactionEdit.ProcessConfirmation()` function? I couldn't find anything in the release notes.

**Comment by nairdo** [comment]
@taylorbrooks We would like to dig into the issue you're still seeing in v11.2.  We reviewed the fix and don't see any issues there, but now we're wondering if it was a _different_ issue introduced in a v10.3 fix... Can you reach out to me via Chat with some of the additional details about the problem you're seeing?

**Comment by MikeDPeterson** [comment]
@taylorbrooks We found the issue that probably caused this. The ReferenceNumber wasn't getting included, which I suspect you are using to find the customer record. Let me know if that fixes it. @mkinyon that issue you found was also fixed with this change https://github.com/sparkdevnetwork/rock/commit/2a363451af0285a103a09d72cee48a6da1af815b#diff-cc906466befdfd7459a8d18dac72318eR1144

**Comment by mkinyon** [comment]
Thank you @MikeDPeterson
