### ISSUE TITLE
Group Meeting Details Show Address Instead of Location Name

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4397]
### Description

When editing a Group and adding a _Campus_ to _Group Meeting Details_ , IF the Campus has an address, the address is used for display instead of the Campus Name. 

### Steps to Reproduce

1. Make sure you have a Campus _Named Location_ with an address
2. Edit a group and click Meeting Details and choose the Campus
3. Observe that instead of the Campus name, the address is shown instead.

**Expected behavior:**

Choosing a campus would display the campus name, not its address. This seems like a similar issue to https://github.com/SparkDevNetwork/Rock/issues/2259 but is being exposed in a different place(s).

**Actual behavior:**

Address of Campus is shown instead of Campus Name. This would not really be an issue if the ONLY place this affected was the Meeting Details tab of the group... but it also makes the campus show "as an address" when such a group is exposed to the _Group Scheduler_ functions. 
![image](https://user-images.githubusercontent.com/3903408/92808385-50ca7e00-f381-11ea-8646-995ff81e5db4.png)

Aside from being kinda ugly, some people in charge of group scheduling could conceivably not even know the addresses of campuses, especially in larger orgs with lots of them, leading to confusion and ambiguity.

### Versions

* **Rock Version:** 11.1

**Comment by MikeDPeterson** [comment]
Thanks @JimMichael for letting us know that this fix caused the #4580 issue. https://github.com/sparkdevnetwork/rock/commit/e2970bd68eefa2a182728d0aaa2d2daee19e8f3d, will fix this issue #4397 and also keep #4580 as fixed
