### ISSUE TITLE
Request: Can this field length be increased to 4? 

### ISSUE THREAD

**Issue by spurgeonbj** [SparkDevNetwork/Rock#4404]
https://github.com/SparkDevNetwork/Rock/blob/72c8d4e9333f4810fd064d6288d593f0b98abff0/Rock/Model/PhoneNumber.cs#L69

Hi,

We are using Rock also to manage our contacts from different parts of the world. 

Some countries like Jamaica etc. have a 4 digit Country Code (like 1876) which would be appropriate to be represented as 1-876-xxxxxxx 

We face issues when we import data with 4 digit country codes in phone numbers, and manage to shift the next 3digits like 876 as a part of the phone number, which in my humble opinion, is not the apt solution... 

Request to consider enlarging this field in the next release....

Thanks!

**Comment by cabal95** [comment]
The use of the term "country code" in the model may have been originally incorrect as it is more accurate to call it the dialing prefix, which is limited to 3 digits worldwide.

In this case, the "country code" is actually just `1`. `876` is an area code that is assigned to Jamaica. I don't know why they did this but there are a few cases where this is done. Maybe back in the day when the international dialing plan was drawn up it was just assumed that many of these countries would never have more than a handful of telephones.

For example in Australia, the Christmas Island uses the Australia dialing prefix of `+61`, but then has an area code assigned to it of `89164`. In Rock the Christmas Island would be listed as just `61` for it's "country code" even though that country code is technically associated with Australia.

As another example, both Canada and the United States share `1` as their "country code" (dialing prefix). Canada doesn't actually have a phone number country code associated with it. In the US we tend to think of `+1` as the United States country code but that is obviously not correct. I'm sure in Canada they tend to think the same. I think this lends credence to the idea that this field isn't actually a country code but rather a dialing prefix.

The field could be extended, but it would need to be made much longer than 4 digits. Currently there are country codes of 7 digits and there is nothing preventing them from extending that further. So I think the decision would need to be made if this field is truly meant to be the country code (`1876`) or if it's meant to be the dialing prefix (`1`).

And as I mentioned above, Canada and United States both share `1` as their "country code" so trying to truly make this a country code field might not make sense. If it's kept as-is, we should probably add a remark to the code to say that it is actually the dialing prefix and not an actual country code.

**Comment by spurgeonbj** [comment]
Dear Daniel, 

Thanks for the kind insights into this...  

Just realized that there is a method to get a fullnumber, which is all we need to get a number with which we can communicate correctly with the person...


God bless you!
