### ISSUE TITLE
Event registrations with required birthdate allow for invalid dates

### ISSUE THREAD

**Issue by kkiserGH** [SparkDevNetwork/Rock#4408]
### Prerequisites

Please don't just check the box unless you have done these things...

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Write a clear and concise description and include **full window** (non-partial) screenshots.

### Steps to Reproduce

1. Register for an event that includes a required Person Attribute of Birthdate.
2. Don't enter a birthdate and see that the registration flags the missing required field.
3. Enter a birth month but no birth day or birth year and see that the registration flags the missing required field.
4. Enter a birth month and birth day but no birth year.

**Expected behavior:**

The registration should also flag the missing birth year as an error.

**Actual behavior:**

The registration does not flag an error and allows it to be completed.  The resulting Person record contains a birthdate with a month and day but no year.

![Birthdate](https://user-images.githubusercontent.com/54817742/93216556-8084d780-f72d-11ea-8b03-5791c8cf6009.PNG)

### Versions

* **Rock Version:** 11.0
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
@kkiserGH Unless this is a change in behavior for prior to v11, I think this is expected (though maybe not desired) behavior. In general, person birth dates don't require a year. I think that was done because some people would hesitate to give their real birth year (age). You will notice the same thing if you edit a person's profile directly, it will let you enter a birth day and birth month without the year and save.

That said, the core team would probably need to weigh in to say if that is desired behavior on things like event registrations.

**Comment by kkiserGH** [comment]
Daniel,

Thanks makes sense and we can allow for that.  The strange part for me is
requiring the date value but not a valid date value.  I would expect, maybe
incorrectly, that if a date field is required that it would be a valid date.

A similar example would be an email field that needs to have all the
required components.  It may or may not be a real email address but it does
contain all necessary pieces.  So the birthdate value would have a valid
month, day and year but may not actually represent their real birth date.

Thanks,
Keith

**Comment by jonedmiston** [comment]
I can confirm that the way it's working is as intended. The community asked that the year be optional as many people are not comfortable giving their age. Having just the month/day is still of value as we can still acknowledge their birthday. 

If you would like for a new configuration option to change this to be required I would recommend adding it to our ideas board here: https://community.rockrms.com/ideas
