### ISSUE TITLE
Beta v11.1 Refund for ACH transaction with Transnational Gateway not working

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4411]
### Description

I tried to issue a refund for the $1 charge I tested. I did this via ACH with the Transnational Gateway. The transaction did go through successfully, but when I try to refund, I am getting an error, _Transaction Error
Transaction not found REFID:2456238617_ . Here is an image of the error as well:

<img width="1181" alt="Screen Shot 2020-09-11 at 14 40 19" src="https://user-images.githubusercontent.com/23226974/93253524-ff493700-f764-11ea-838e-e6f93c256b51.png">

I called Transnational. They said they see the error as well, so the error was coming from the Gateway. After they did some troubleshooting this was their response to what caused the error, "The variable `payment=check` is not being defined, so it is defaulting to Credit Card." 

Here is the link they sent me to for me to see what variables are required to be defined in order for a refund to work: https://secure.tnbcigateway.com/merchants/resources/integration/integration_portal.php?tid=817bcbd6242947c1ccb2a75789721ac9#transaction_variables

The transaction has not settled yet, but they told me that even after it does settle, refunding will still not work unless `payment=check` is defined.

**Expected behavior:**

Should be able to refund.

**Actual behavior:**

Trying to refund shows an error.

### Versions

* **Rock Version:** [v11.1]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/bdf8af9091dfc7b8df9f7204bdeec3cd34ba41f9.
