### ISSUE TITLE
Typo on Notes Block

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4413]
### Prerequisites
Please don't just check the box unless you have done these things...

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
The Notes block has a typo in one of the Tooltips. Look at Expand Replies. It seems like it should read "Should replies be automatically expanded?".

![Screen Shot 2020-09-16 at 08 43 46 (2)](https://user-images.githubusercontent.com/23226974/93339270-5e588b80-f7f9-11ea-8be8-61bfe3efd53e.png)

### Steps to Reproduce
1. Go to a Person's profile page
1. Click on Block Settings
1. Edit the Notes Block
1. Scroll to Expand Replies and hover over the tooltip

**Expected behavior:**

Should read something like "Should replies be automatically expanded?"

**Actual behavior:**

Instead reads "Should replies to automatically expanded?"

### Versions
* **Rock Version:** [v11.0]
* **Client Culture Setting:** [en-US]

**Comment by melodielange** [comment]
This has been addressed.
