### ISSUE TITLE
New Windows Checkin App Not showing Start/Cancel Button on lower resolutions

### ISSUE THREAD

**Issue by craigmash** [SparkDevNetwork/Rock#4414]
Using the newest Checkin Windows app, 1.11.1

Monitor resolution is 1024x768
Cannot see the Start/Cancel button and no scrollbar provided
![Clipboard - September 16, 2020 9_27 AM](https://user-images.githubusercontent.com/44239863/93374356-3595bd80-f81c-11ea-8a1d-c7d7c19e9ea1.png)

**Comment by notGerryMiller** [comment]
We are seeing this also.  Our older touch screens that can't go over 1024 * 768 do not dispaly the Start/Cancel Button.

**Comment by nairdo** [comment]
Hi Craig @craigmash and not Gerry @notGerryMiller :) We've updated the check-in app found under the  "External Applications" link.  If you can, would you download this latest version and confirm everything A-OK again?

**Comment by craigmash** [comment]
Yes! That fixed it. Buttons now show at the bottom of the screen.
