### ISSUE TITLE
Metric Categories field not retaining values when edited 

### ISSUE THREAD

**Issue by mkinyon** [SparkDevNetwork/Rock#4416]
Submitted on behalf of **River Valley Church**

### Prerequisites

Please don't just check the box unless you have done these things...

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When editing a block with a Metric Categories field the category picker is not selecting previously selected values.  This makes it possible to accidentally save over existing values.

![image](https://user-images.githubusercontent.com/2349102/93390068-f4081100-f821-11ea-86af-63ccba9b9381.png)

### Steps to Reproduce
Example: [https://prealpha.rocksolidchurchdemo.com/page/451](https://prealpha.rocksolidchurchdemo.com/page/451) 
1. Edit a block attribute of type Metric Categories Field.  (Example blocks would be Service Metric Entry or Pie Chart.)
2. Open the category picker choose a few categories then save.
3. Open the category picker again.

**Expected behavior:**

For previous values to still be selected.

**Actual behavior:**

Previous values are no longer selected.

### Versions

* **Rock Version:** 10.3, prealpha
* **Client Culture Setting:** en-US

**Comment by shauncummings** [comment]
Fixed in https://github.com/sparkdevnetwork/rock/commit/1a255a973f572020501bd021eeb7da666f0a6ab9
