### ISSUE TITLE
Event Wizard template listing issue

### ISSUE THREAD

**Issue by jennimcferron** [SparkDevNetwork/Rock#4417]
### Prerequisites

Please don't just check the box unless you have done these things...

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When selecting a registration template from the "registration template" drop down, the registration templates are not alphabetized. 

![image](https://user-images.githubusercontent.com/62965918/93396403-75fd3780-f82c-11ea-89d3-196a89d6b6e6.png)

### Steps to Reproduce

1. Go to Event Wizard Page
2. Click on Registration Template drop down
3. Look at list to see that templates are not alphabetized
4. It appears they are listed in order of when added to system

**Expected behavior:**

Templates should be listed alphabetically

**Actual behavior:**

Templates are listed randomly according to staff/basic user (appears to be listed based on when entered into Rock). With our numerous templates, our staff has to scroll slowly to find the desired registration template. 

### Versions

* **Rock Version:** 10.2, 11.1 (rock demo)
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
Added fix for this in v11.2.
