### ISSUE TITLE
Inactive Registration Templates Displaying when adding Occurrence of event

### ISSUE THREAD

**Issue by jennimcferron** [SparkDevNetwork/Rock#4418]
### Prerequisites

Please don't just check the box unless you have done these things...

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When adding an event through the calendar, inactive registrations templates are displaying when adding an occurrence of an event. 

![image](https://user-images.githubusercontent.com/62965918/93398928-561c4280-f831-11ea-9415-4b21514af384.png)

### Steps to Reproduce

1. Go to Calendar
2. Click on Public (or Internal)
3. Scroll down to Find a Calendar Event and select it 
4. Add new occurrence of the event
5. Hit "Add New Registration Instance"
6. When "New Registration Instance" loads, use the "registration template" drop down
7. It displays my "inactive" registration I added (added "inactive" to title to show issue)

**Expected behavior:**

Staff shouldn't have to comb through inactive templates or accidentally selecting one. 

**Actual behavior:**

Inactive registration templates are displaying

### Versions

* **Rock Version:** 10.2, 11.1 (rock demo)
* **Client Culture Setting:** en-US

**Comment by timlem** [comment]
I can confirm this on 11.1 and that it happens in the event wizard as well with events that are inactive. See screenshot:

![](https://chat.rockrms.com/file-upload/C9vjSAfdmrDaeiwoS/87zIJ65fgt.gif)

**Comment by timlem** [comment]
@nairdo - any chance this could squeeze into v11.2?

**Comment by nairdo** [comment]
@timlem Someone on our team looked at your request _late_ last night and worked out the fix for you. :)   So, yes, we're going to get that into v11.2 beta (and possibly slipstream that fix into v11.2 alpha later this morning).
