### ISSUE TITLE
Image Resizer doesn't work for resampling or cropping images of .webp format

### ISSUE THREAD

**Issue by bengoshow** [SparkDevNetwork/Rock#4424]
### Description
I noticed that some images weren't being cropped or resized using the documentation at https://community.rockrms.com/Rock/BookContent/14#workingwithimages and  https://imageresizing.net/docs/v4/reference

Here are 2 examples: 

https://rock.rocksolidchurchdemo.com/GetImage.ashx?guid=11d454bd-9c28-4d4c-9ddb-f71a23b583d5&w=360&h=165&mode=crop&scale=both

https://rock.rocksolidchurchdemo.com/GetImage.ashx?guid=e33a43eb-961c-4d54-9cad-00f78f76df08&w=360&h=165&mode=crop&scale=both

When I saved the image to my hard drive I noticed that those files were using the .webp format instead of .jpg or .png

In the screenshot attached you can see the middle image is being cropped properly but the first and third are not.

![Screen Shot 2020-09-23 at 10 17 34 AM](https://user-images.githubusercontent.com/1636930/94025150-32538200-fd86-11ea-9761-1387c5dda731.png)

### Steps to Reproduce
1. Change code at "~~/Assets/Lava/AdList.lava" to include this line: `<a href="{{ itemLink }}"><img src="/GetImage.ashx?guid={{ item | Attribute:'Image','RawValue' }}&w=360&h=165&mode=crop&scale=both" /></a> `
1. Go to https://rock.rocksolidchurchdemo.com/page/343?ContentChannelId=1
1. Click on any Content Channel Item
1. Upload a .webp image
1. See different sized images at https://rock.rocksolidchurchdemo.com/page/1

### Versions
* **Rock Version:** [1.11.0.3]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Hi @bengoshow Ben, I just wanted to let you know that the ImageResizer inside of Rock supports only jpeg, png, gif, tiff, and bmp out-of-the-box.  (There are for-pay ImageResizer plugins but we can't include those in the Rock open source.)  I don't have any experience with those ImageResizer plugins, but you might also use something like the [Cloudinary Storage Provider](https://www.rockrms.com/rockshop/plugin/34) as it handles a wide variety of image types.
