### ISSUE TITLE
Cannot Delete Benevolence Documents

### ISSUE THREAD

**Issue by tstephens17** [SparkDevNetwork/Rock#4426]
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Cannot delete Benevolence Documents once uploaded. I found this in my search: https://github.com/SparkDevNetwork/Rock/issues/2758

### Steps to Reproduce

1. Add a benevolence request in and add a document.
2. There is no way to remove the document.

**Expected behavior:**

To be able to remove documents.

**Actual behavior:**

No way to remove

### Versions

* **Rock Version:** [Rock McKinley 11.0 (1.11.0.3)]
* **Client Culture Setting:** [en-US]

**Comment by cwomack** [comment]
Hello @tstephens17, thanks for your submission of this bug.  I was able to reproduce this issue on v11.0 and verified that there's a fix for it on v11.1.  I'll close the issue out as being fixed on that branch/update, but should you find any other issues with this please feel free to comment back! Thank you for helping to make Rock better.
