### ISSUE TITLE
Editing scheduled transactions changes currency type to Unknown

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#4437]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

This may be related to #4385, and thus may already be fixed, but there could be existing data that is now incorrect so reporting it here to track in case somebody needs the scripts we used to help resolve this.

After upgrading to Rock v11 we noticed the mentioned bug. This week we started noticing that some SCheduled Transactions have their currency as `Unknown`. We've traced this down to when somebody edits a scheduled transaction it changes the currency to Unknown in the scheduled transaction payment details. This then causes all subsequently downloaded payments to have a currency of Unknown.

We went through and fixed all our existing ones and will just have to keep an eye on it after we install the patch to see if it fixes this issue as well.

We used the following SQL to find any scheduled transactions that might affected by this (the date check is based on when we upgraded Rock):

```sql
DECLARE @UnknownCurrencyValueId INT = 6022

SELECT DISTINCT *
FROM
(
SELECT
FT.[ScheduledTransactionId]
FROM [FinancialTransaction] AS FT
INNER JOIN [FinancialPaymentDetail] AS FPD ON FPD.[Id] = FT.[FinancialPaymentDetailId]
WHERE FPD.[CurrencyTypeValueId] = @UnknownCurrencyValueId
  AND FT.[TransactionDateTime] >= '2020-09-01'

UNION

SELECT
FST.[Id]
FROM [FinancialScheduledTransaction] AS FST
INNER JOIN [FinancialPaymentDetail] AS FPD ON FPD.[Id] = FST.[FinancialPaymentDetailId]
WHERE FPD.[CurrencyTypeValueId] = @UnknownCurrencyValueId
  AND FST.[ModifiedDateTime] >= '2020-09-01'
) AS IQ
```

We then used the following SQL to display details and then after verifying it should indeed be fixed set the `@FixErrors` parameter to 1 and run gain to attempt auto fix.

```sql
DECLARE @ScheduledTransactionId INT = 9449
DECLARE @FixErrors INT = 0 -- Set to 1 to attempt to fix errors, otherwise it will just report.
DECLARE @UnknownCurrencyValueId INT = 6022

DECLARE @CurrencyTypeValueId INT
DECLARE @CreditCardTypeValueId INT

SELECT @CurrencyTypeValueId = FPD.CurrencyTypeValueId, @CreditCardTypeValueId = FPD.CreditCardTypeValueId
FROM FinancialScheduledTransaction AS FST
INNER JOIN FinancialPaymentDetail AS FPD ON FPD.[Id] = FST.[FinancialPaymentDetailId]
WHERE FST.[Id] = @ScheduledTransactionId

DECLARE @FixedCurrencyTypeValueId INT
DECLARE @FixedCreditCardTypeValueId INT

SELECT TOP 1 @FixedCurrencyTypeValueId = FPD.[CurrencyTypeValueId]
FROM [FinancialTransaction] AS FT
INNER JOIN [FinancialPaymentDetail] AS FPD ON FPd.[Id] = FT.[FinancialPaymentDetailId]
WHERE FT.[ScheduledTransactionId] = @ScheduledTransactionId AND FPD.[CurrencyTypeValueId] != @UnknownCurrencyValueId
ORDER BY FT.[TransactionDateTime] DESC

SELECT TOP 1 @FixedCreditCardTypeValueId = FPD.[CreditCardTypeValueId]
FROM [FinancialTransaction] AS FT
INNER JOIN [FinancialPaymentDetail] AS FPD ON FPd.[Id] = FT.[FinancialPaymentDetailId]
WHERE FT.[ScheduledTransactionId] = @ScheduledTransactionId AND FPD.[CreditCardTypeValueId] IS NOT NULL
ORDER BY FT.[TransactionDateTime] DESC

IF @FixErrors = 1
BEGIN
	IF @FixedCreditCardTypeValueId IS NULL OR @FixedCurrencyTypeValueId IS NULL
	BEGIN
		PRINT 'Could not automatically determine correct currency type or credit card type.'
		RETURN
	END

	PRINT 'Updating Scheduled Transaction...'

	UPDATE FPD
	SET FPD.[CreditCardTypeValueId] = @FixedCreditCardTypeValueId,
		FPD.[CurrencyTypeValueId] = @FixedCurrencyTypeValueId
	FROM [FinancialScheduledTransaction] AS FST
	INNER JOIN [FinancialPaymentDetail] AS FPD ON FPD.[Id] = FST.[FinancialPaymentDetailId]
	WHERE FST.[Id] = @ScheduledTransactionId

	PRINT ''
	PRINT 'Updating existing Transactions...'

	UPDATE FPD
	SET FPD.[CreditCardTypeValueId] = @FixedCreditCardTypeValueId,
		FPD.[CurrencyTypeValueId] = @FixedCurrencyTypeValueId
	FROM [FinancialTransaction] AS FT
	INNER JOIN [FinancialPaymentDetail] AS FPD ON FPD.[Id] = FT.[FinancialPaymentDetailId]
	WHERE FT.[ScheduledTransactionId] = @ScheduledTransactionId
	  AND (FPD.[CurrencyTypeValueId] != @FixedCurrencyTypeValueId OR FPD.[CreditCardTypeValueId] IS NULL OR FPD.[CreditCardTypeValueId] != @FixedCreditCardTypeValueId)

	PRINT ''
	PRINT 'Fixed errors (hopefully)'
END
ELSE
BEGIN
	SELECT
		@CurrencyTypeValueId AS [Actual Currency Type],
		@FixedCurrencyTypeValueId AS [Expected Currency Type],
		@CreditCardTypeValueId AS [Actual Credit Card Type],
		@FixedCreditCardTypeValueId AS [Expected Credit Card Type]

	SELECT COUNT(*) AS [Transactions to be fixed]
	FROM [FinancialTransaction] AS FT
	INNER JOIN [FinancialPaymentDetail] AS FPD ON FPD.[Id] = FT.[FinancialPaymentDetailId]
	WHERE FT.[ScheduledTransactionId] = @ScheduledTransactionId
	  AND (FPD.[CurrencyTypeValueId] != @FixedCurrencyTypeValueId OR FPD.[CreditCardTypeValueId] IS NULL OR FPD.[CreditCardTypeValueId] != @FixedCreditCardTypeValueId)
END


-- Use below to make transactions or scheduled transactions ACH
--UPDATE FPD
--SET [CurrencyTypeValueId] = 157
--FROM [FinancialTransaction] AS FT
--INNER JOIN [FinancialPaymentDetail] AS FPD ON FPD.[Id] = FT.[FinancialPaymentDetailId]
--WHERE FT.[Id] = 1154330

--UPDATE FPD
--SET [CurrencyTypeValueId] = 157
--FROM [FinancialScheduledTransaction] AS FST
--INNER JOIN [FinancialPaymentDetail] AS FPD ON FPD.[Id] = FST.[FinancialPaymentDetailId]
--WHERE FST.[Id] = 9214
```

Both scripts you will need to set the currency type value Id number to the valid value for your system.

### Steps to Reproduce

1. Edit an existing scheduled transaction
2. Use the "use existing payment details" option
3. Save
4. See that the currency type is now Unknown.

**Expected behavior:**

Payment details should not be lost when editing a scheduled transaction.

**Actual behavior:**

Currency type is lost.

### Versions

* **Rock Version:** 11.0
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@cabal95 It looks like Mason and Mike also discovered this yesterday and I'm told this is the commit that fixes this issue as well: https://github.com/SparkDevNetwork/Rock/commit/2a363451af0285a103a09d72cee48a6da1af815b#diff-cc906466befdfd7459a8d18dac72318eR1144

**Comment by cabal95** [comment]
@nairdo Is this actually fixed in 11.2, since that has been in beta for a week?

**Comment by nairdo** [comment]
It is being put into the beta this morning.  I know it's late, but we really want it in v11.2 for those who are going to get it next week once it goes to early access.  I'll be providing the updated bits in the #beta-testers channel shortly for those who want to get these changes on their beta system.

**Comment by cabal95** [comment]
Okay thanks, just making sure that wasn't a mis-click intended to be 11.3 or something.
