### ISSUE TITLE
Address displays "Mapped Location" even when the value is set to False in the DB

### ISSUE THREAD

**Issue by kenmulford** [SparkDevNetwork/Rock#4439]
### Description
The "Is Mapped Location" value of a home address does not always display correctly when editing a Family's addresses.

![image](https://user-images.githubusercontent.com/1336749/94853002-b649e180-03f8-11eb-8e37-ba81b7d33a95.png)

### Steps to Reproduce
1. Ensure a family has one home address and at least one previous address. 
1. Ensure the home address is active and "mapped location" is set to true.
1. Using SQL, update the GroupLocation record so IsMappedLocation is now false.
1. Refresh the UI and observe that the "Mapped Location" checkmark is still there.

**Expected behavior:**

The checkmark would disappear if the Home Address record is not actually a mapped location.

**Actual behavior:**

The checkmark persisted.

### Versions
* **Rock Version:** 10.3
* **Client Culture Setting:** EN-US

**Comment by nairdo** [comment]
Hi @kenmulford Ken, the **Map Location** flag is used to indicate which of the addresses is for the map -- and Rock business rule is A) there must be one and B) there can only be one.  (The Map Location flag is not an indication of whether or not the location is mappable.)
