### ISSUE TITLE
Lava shortcode for youtube returns a playback error

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#4440]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

The shortcode for youtube returns a playback error.

The youtube Lava Shortcode is described at Admin Tools > CMS Configuration > Lava Shortcodes.

### Steps to Reproduce

1. Add the following code to a HTML block

{[ youtube id:‘FZUH2tFM2Zg’ ]}

<iframe width="560" height="315" src="https://www.youtube.com/embed/FZUH2tFM2Zg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

2. View the page.  

**Expected behavior:**

In this example, the video should display twice, once from the {[ youtube ]} shortcode action, the second time from an alternative way of showing youtube videos.

**Actual behavior:**

The {[ youtube ]} shortcode returns a playback error.  The alternative works showing it is not the video itself.

### Versions

Rock Version: Rock McKinley 11.0 (1.11.0.3)
Client Culture Setting: en-NZ

Also confirmed by US users in Chat on #lava channel.

**Comment by jonedmiston** [comment]
@ElimAdmin I'm not able to reproduce? When I use your shortcode markup above though I did notice that your single quotes aren't true single quotes, but rather the curly quotes. When I changed that everything works fine.

**Comment by ElimAdmin** [comment]
@jonedmiston Haha! You are so right: single quotes not curly quotes!  
I copied the code out of Michael's Masterclass notes...    I'll let him know.
Great to do Masterclass at last.  
Thanks Jon.
