### ISSUE TITLE
Label Preview is broken

### ISSUE THREAD

**Issue by jrockman13** [SparkDevNetwork/Rock#4441]
### Description
V11.0.3 and V11.1 have a broken label preview. You can no longer see the layout when viewing the label contents.

### Steps to Reproduce
1. Go to Admin Tools -> Check-In -> Labels and open a label
1. Click "edit Label Contents" 
1. Observe the "missing image" icon where the label typically appears.

![image](https://user-images.githubusercontent.com/22159658/94981097-1a51d000-04f5-11eb-9bfa-281d7f99b7f6.png)

**Expected behavior:**

A preview of the label will display

**Actual behavior:**

No label preview appears

### Versions
* **Rock Version:** 1.11.0.3 & 1.11.1.
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
I cannot dupe this on my my prod (10.2) , my test (11.2), on demo (11.0), or prealpha (12.0)... maybe the Labelary site/API was just down for a bit?

**Comment by jrockman13** [comment]
Hmm. I believe it's something in chrome. I reproduced on multiple machines and on Demo, but all tests were with Chrome. I tried Edge Version 85.0.564.68 (Official build) (64-bit) (Chromium build), and it worked. Tested on Chrome Version 85.0.4183.121 (Official Build) (64-bit). Tried Chrome in a guest window too (no plug-ins or extensions).
Works on Safari (iOS 14.01).

So its' something in chrome.

**Comment by cabal95** [comment]
I just tried on Chrome 85.0.4183.121 64-bit Windows and it works fine on prealpha (1.11.0.3).

@jrockman13 If you can still replicate, I would check the Web Console in the developer tools and see if it reports any errors. You can also open the Network Tab to see what error might be coming up when the page loads and the image fails.

**Comment by jrockman13** [comment]
I determined the issue is Google’s update to block mixed content by default. Labelary is being called via http. As of now, you can override this setting but the recommendation is to update code as they may not allow this in the future.

**Comment by cabal95** [comment]
Unfortunately Labelary doesn't support SSL so that wouldn't be an easy fix.

**Comment by jrockman13** [comment]
What about a scripted button that launches a popup that loads the url to the preview?

**Comment by jonedmiston** [comment]
I reached out to Labelary to see what the license cost would be to allow us to use their code outside of their webservice.

**Comment by JimMichael** [comment]
@cabal95 Technically they DO support TLS on https://api.labelary.com/ (where Rock gets the renderings from), but they just have a bad cert on it.

**Comment by jonedmiston** [comment]
Update, licensing is out of our price range. I did inquire if they plan to update their certificate to a valid one. Will let you know when I hear back.

**Comment by cabal95** [comment]
I suppose one option would be to add a "proxy" handler in Rock that is passed the ZPL (over HTTPS) and then passes it to labelary over non-SSL, but that feels like a really non-ideal way to solve it :(

**Comment by jonedmiston** [comment]
Update: Had a phone call with Labelary today (they're great people). Looks like we might be able to get a license to run our own API server. Should know soon. They are also looking at the HTTP issue, but that's not something that's on their roadmap in the near future so creating our own instance may be required.

**Comment by jgrabrian** [comment]
<Disclaimer>This method is not ideal or completely secure.</Disclaimer>
If using Chrome, you can change the site settings to allow mixed content. 

- While on your Rock page, click the padlock icon next to your URL
- Select Site Settings
- Scroll down to Insecure Content and change it to "Allow"
- You may need to reload the page if you were viewing your label when you tried this

**Comment by ethan-sparkdevnetwork** [comment]
Updated the EditLabel block with a new attribute for the label preview URL template. This will allow the URL to be adjusted when the Labelary API URL changes. The default value points to base URL https://labelary2.cfapps.io/v1/printers/

**Comment by leahjennings** [comment]
@ethan-sparkdevnetwork the labelary2.cfapps.io domain doesn't work and returns a 404, however changing just the domain to api.labelary.com fixes it. I can create a new issue, but it seemed related to this one so am starting with a comment.

**Comment by nairdo** [comment]
Greetings @leahjennings We've been in contact with the Labelary team again.  They lost that other domain and have advised us to switch back to api.labelary.com (w/HTTPS) so we will be changing that soon in the 12.1 beta.

**Comment by leahjennings** [comment]
Thanks for the update, @nairdo!

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in v12.1 in commit https://github.com/sparkdevnetwork/rock-updatepackagebuilder/commit/86582e4ec0f9daccdf356197bf80f91c6f91da2f. I back ported this to 11.4 but this fix is not included in the 12.0 package.
