### ISSUE TITLE
Typo: Check-in configuration 'Allow Checkout?' help text

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#4443]
On Checkin configuration page 
Home > Check-in > Check-in Configuration, e.g. Weekly Service Check-in, > Edit : General Settings, Allow Checkout field help

help text reads

![AllowCheckout](https://user-images.githubusercontent.com/4658177/94985565-63b52480-05b4-11eb-990e-addabd1ec381.jpg)

Should read
Should there be an option to allow the user to check-out?

### Versions

Rock Version: Rock McKinley 12.0 (1.12.0.6)
Client Culture Setting: en-NZ

**Comment by melodielange** [comment]
This is corrected. Different verbiage, but the sentence is correct.
