### ISSUE TITLE
Cannot select geography data-type fields from Location table in SQL tool.  

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#4444]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

May be related to #4291?

The SQL statement
SELECT * FROM [Location]
in the Home > Power Tools > SQL command
returns an error:
Error SQL Error! DataReader.GetFieldType(5) returned null.

The fields failing in the SQL query are
GeoPoint
GeoFence
which are of DATA-TYPE geography in the table field definitions.
All other fields can be selected and return correctly.

(Might this be why I can't view Group Members on a Group Map even though they have verified addresses?)

### Steps to Reproduce

1. Go to Home > Power Tools > SQL command
2. Enter and run SQL:  SELECT GeoPoint, GeoFence FROM LOCATION  or SELECT * FROM LOCATION
3. See error

SELECT GeoPoint FROM LOCATION 
returns
Error SQL Error! DataReader.GetFieldType(0) returned null.

SELECT * FROM LOCATION
returns
Error SQL Error! DataReader.GetFieldType(5) returned null.

### Versions

Rock Version: Rock McKinley 12.0 (1.12.0.6)
Client Culture Setting: en-NZ

Rock Version: Rock McKinley 10.2 (1.10.2.3)
Client Culture Setting: en-NZ

**Comment by nairdo** [comment]
Hi @ElimAdmin Ken, Since those two fields are 'geography' [complex] datatypes, you'll need to specify what form you want out of the values.  For example, you might want it as a 'point string':

```Sql
SELECT TOP 100 GeoPoint.STAsText(), GeoPoint.STAsText() FROM [Location]
```

or you might want the Latitude and Longitude out of that datatype as separate columns:

```Sql
SELECT TOP 100 GeoPoint.Lat AS [Latitude], GeoPoint.Long AS [Longitude] FROM [Location]
```
