### ISSUE TITLE
ENH: Group map does not display Group Members by default - make toggle intuitive

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#4445]
### Description
If you view the group 'Alisha Marble's Group' in the demo site from the Group Viewer, then click on the Interactive Map icon for the group, the map that is displayed shows the location of the Group itself, but not the Group Members.  Both Group and Group Members options are shown as full dots, suggesting that both are selected and that both are being displayed.  It is confusing to a first time user why Group Members' locations are not showing.

To get the Group Members to display you actually have to click on the 'Group Members' green dot.

This is not intuitive and is not described anywhere.  It has taken me ages to work this out and I only found it by mistake.

I suggest the dots for Group and Group Members be more clearly a user interactive selection.  Empty/full dots?  Toggle?  Checkbox?  Something that is obvious that you have to user select to switch between the two.

![GroupMap1](https://user-images.githubusercontent.com/4658177/95061457-1ec9f300-0758-11eb-8b36-a8eab5700862.jpg)

### Steps to Reproduce
1. On demo site view the group 'Alisha Marble's Group'.
1. View the Interactive Map for the group.
1. The location of group members is not shown on map.

**Expected behavior:**

I expected to see the home address location of all members of the group, who have geo-located addresses, shown on the map.
Make it clear that the user has to select which of Group / Group Members is to be displayed.

**Actual behavior:**

Group member's locations not shown on group map and UI not intuitive.

### Versions
Demo site:
Rock Version: Rock McKinley 11.0 (1.11.0.3)
Client Culture Setting: en-NZ

Out site:
Rock Version: Rock McKinley 10.2 (1.10.2.3)
Client Culture Setting: en-NZ

**Comment by nairdo** [comment]
Greetings Ken @ElimAdmin !  While that's really not a bug, it's an interesting feature request.  If you're still interested in this, go ahead and post the idea over at https://community.rockrms.com/Ideas to let the community chime in and vote.  

Thanks for helping to make RockRMS a better platform.
