### ISSUE TITLE
Phone Lookup button on mobile checkin cannot be hidden

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4447]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

The Mobile Check-in Launcher block has a setting to specify the "Phone Identification Page". The help text says that if it's blank, the "Phone Lookup" button will not be shown.

Clearing this option and pressing save, then refreshing the mobilecheckin page, does not remove the "Phone Lookup" button. But clicking the button doesn't take you anywhere anymore.

Similar to and likely same fix as #4415. Tested on Rock v12 to make sure this wasn't also fixed with #4415.

### Steps to Reproduce

1. Go to Admin Tools > CMS Configuration > Pages
2. Expand External Homepage > Support Pages and click on Mobile Check-in Launcher
3. Click the "Settings" (cog) button on the Mobile Check-in Launcher block
4. Click the "X" that appears when you hover over the "Phone Identification Page" input.
5. Click "Save".
6. Load /mobilecheckin while logged out.

**Expected behavior:**

The "Phone Lookup" button should not be shown.

**Actual behavior:**

The "Phone Lookup" button is shown.

### Versions

* **Rock Version:** [Rock McKinley 12.0 (1.12.0.6)]
* **Client Culture Setting:** [en-us]

**Comment by matthewbronkema** [comment]
Fixed on https://github.com/SparkDevNetwork/Rock/commit/94833f7c8907e937a25ff314fbbfd0093e94987a
