### ISSUE TITLE
Group Viewer Settings - # of Child Groups

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#4449]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When you are Group Tree View block. there is a settings option to [Show Count For] Group Members or Child Groups.
If you select Show Count For - Child Groups, it will show you a count that includes inactive groups.  I would think that this count would be similar to [Group Members] and only show a count for active groups.

### Steps to Reproduce

1. Go to people
2. Click on Group Viewer
3. Mark a group as inactive
4. Change your setting to show count for child groups
5. notice that the count includes the inactive groups

**Expected behavior:**

I would expect that this count would be similar to [Group Members] and only show a count for active child groups. At the very least, if you are only showing [Active] groups the number would reflect those active groups, not inactive.

**Actual behavior:**

If you select show count for Child Groups, the number shown represents active and inactive groups.

### Versions

* **Rock Version:** [11.0]
* **Client Culture Setting:** [en-US
![Screen Shot 2020-10-06 at 11 46 38](https://user-images.githubusercontent.com/41912840/95225841-3c37a500-07ca-11eb-9a6d-79b8c3eef6e0.png)
![Screen Shot 2020-10-06 at 11 46 19](https://user-images.githubusercontent.com/41912840/95225851-3e99ff00-07ca-11eb-9513-8cd10ef2a2a3.png)

]

**Comment by melodielange** [comment]
As I made groups inactive the number of child groups did not change. I am not sure this is in fact fixed.

**Comment by nairdo** [comment]
@melodielange Was your group tree configuration set to show All or show only Active groups?
![image](https://user-images.githubusercontent.com/383807/97644031-6fa2d380-1a06-11eb-8964-f7670627594d.png)
