### ISSUE TITLE
"Group Type Group" Field Type Broken in Page Parameter Filter Block

### ISSUE THREAD

**Issue by MicahO** [SparkDevNetwork/Rock#4451]
### Description
When using the Page Parameter Filter block, setting a new filter as a "Group Type Group" does not allow you to set a group type.

### Steps to Reproduce
1. Go to a blank page (Sandbox link 10/6/20: https://rock.rocksolidchurchdemo.com/page/2625)
1. Click on Page Zones and add a Page Parameter Filter Block to the page.
1. Edit ~~~block settings~~~ the settings and add a new filter at the bottom of the block:
  * Change Field Type to "Group Type Group."
  * Change Group Type to "Serving Team," "Small Group," or similar.
  * Note that the block resets but the group type is not saved.

Tested "Group Type Group" on Person Attributes and Workflow Attributes and it works correctly in both places, just not in this place.

Example: [http://somup.com/cY6Q3blvxQ](http://somup.com/cY6Q3blvxQ)

**Expected behavior:**

The "Group Type Group" value should save and the "Group" box should offer selections from that group type.

**Actual behavior:**

The "Group Type Group" value is not saved, and the "Group" box offers no values to select.

### Versions
* **Rock Version:** [11.1]
* **Client Culture Setting:** [en-US]

**Comment by lamebrain** [comment]
Looks like the "[blank page](https://rock.rocksolidchurchdemo.com/page/2625)" has changed. Can you please update the blank page link so that I can repro?
