### ISSUE TITLE
Universal Search Page Error

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#4453]
### Description
I am starting to test out Universal Search and I'm running into an error when searching using the actual universal search page's search bar. The error I get is the Page Not Found error. I think the issue stems from a '+' being added to the URL parameters when the searched item has a space. When I replace '+' with `%20` all works well again.

Here's what Smart Search passes: 
`https://rock.rocksolidchurchdemo.com/universalsearch/ted%20deck?SmartSearch=true`

When searching the same thing and clicking 'Go' on the Universal Search page, here's what is passed:
`https://rock.rocksolidchurchdemo.com/universalsearch/ted+deck?groupTypeName=`

When you change the plus to `%20` it will properly pull up the page and results.
`https://rock.rocksolidchurchdemo.com/universalsearch/ted%20deck?groupTypeName=`

### Steps to Reproduce
1. With the Smart Search set to Universal Search ("Search"), type in "ted deck" and hit enter.
1. You'll be redirected to the Universal Search page with the results. Leave "ted deck" in the block's search bar and hit 'Go'.
1. You'll encounter a page not found error.
1. Change the plus in the URL to `%20`  and your results will display again.

**Expected behavior:**

No Page Not Found error.

**Actual behavior:**

Encounter a Page Not Found error.

### Versions
* **Rock Version:** v11.0 and v11.2
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
@ethan-sparkdevnetwork Was this commit supposed to reference this issue to close it? https://github.com/SparkDevNetwork/Rock/commit/c338417ca65e507fddc8cee92915f942f6df527a

**Comment by ethan-sparkdevnetwork** [comment]
@cabal95 This came up when I was working on something else. It is the same issue though so I can close it. Thank Daniel!

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in commit: c338417ca65e507fddc8cee92915f942f6df527a
