### ISSUE TITLE
Event Detail Summernote editor buttons disappear in very specific circumstances

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#4456]
### Description
When a calendar event has large Twitter and Facebook images and at least a couple of paragraphs worth of HTML tags in the description, the editor buttons on the Description box disappear.

![image](https://user-images.githubusercontent.com/18447084/95766995-b0b28e00-0c79-11eb-92f9-70ee58805104.png)

### Steps to Reproduce
1. Create or edit a calendar event
1. Add at least two paragraphs to the description
1. Open the Event Attribute Values section
1. Upload a large image to both the twitter and facebook image attributes (unsure of the size threshold but 1920x1080 will do)
1. Click Save
1. Click Edit

**Expected behavior:**

The editor buttons in the Description should be visible as usual.

**Actual behavior:**

The editor buttons in the Description box are missing. I was able to find them by resizing my browser window down to a tablet width and scrolling down, which reveals that the button bar is now positioned to the top of the window, behind the header bar.

Scrolled to the top:
![image](https://user-images.githubusercontent.com/18447084/95767214-0be48080-0c7a-11eb-86eb-5c27cfd70777.png)

Scrolling down: 
![image](https://user-images.githubusercontent.com/18447084/95767249-17d04280-0c7a-11eb-9715-55860a892533.png)

Scrolling further:
![image](https://user-images.githubusercontent.com/18447084/95767294-2880b880-0c7a-11eb-9db1-dab54e1c516e.png)

Deleting either of the two photos, or reducing the content in the Description box down to a single paragraph or no text at all causes the button bar to display normally.

### Versions
* **Rock Version:** v11 and v12
* **Client Culture Setting:** en-US

**Comment by KenyonOzanne** [comment]
I can also replicate this issue on v11.3 along with the temporary solutions @chrismcgrath pointed out.

Looking at the code for the page, the issue seems to be caused due to an inline style on the toolbar. Currently the toolbar has a `position: fixed` inline style followed by `top: 0` which causes the toolbar to fall behind the top menu bar on the page. There does not seem to be a pattern of when the inline styles are added.
