### ISSUE TITLE
URL issue when using Lava in New Communication 

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4460]
#3050 # Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When making a New Communication, and inserting a hyperlink, and that hyperlink uses Lava (example: `{{ 'Global' | Attribute:'PublicApplicationRoot' }}DISC/{{ Person.UrlEncodedKey }}` ), an additional `http://` is added in front of the URL. I am guessing that the Add Link feature checks to see if `http://` or `https://` is in the URL, and if not, adds it for you. Because of using Lava, it does not see that `https://` is already in the `PublicApplicationRoot`. 

Not really sure if this is actually a bug, because it seems that the Add Link feature is working as expected, however building an email like this will cause you to unknowingly send a link in an email that does not work. 

I found this error by helping someone in the community. They stated that this used to work fine before updating to v11.0. Once they updated to 11.0, that is when they began to see the issue. I verified this is correct by testing via Time Machine, v10.1. It did not add `http://` to the beginning of the URL on v10.1. 

![Screen Shot 2020-10-14 at 13 34 30](https://user-images.githubusercontent.com/23226974/96025562-4b020580-0e23-11eb-9565-764936be3801.png)

![Screen Shot 2020-10-14 at 13 34 44](https://user-images.githubusercontent.com/23226974/96025582-505f5000-0e23-11eb-80fe-a8e15e3674e7.png)

### Steps to Reproduce

1. Create a New Communication. 
2. In the Email editor, click the hyperlink button to add a link with Text to display `DISC` and URL `{{ 'Global' | Attribute:'PublicApplicationRoot' }}DISC/{{ Person.UrlEncodedKey }}`.
3. Click Insert Link.
4. Click on link and edit it to see that `http://` was added automatically. 

**Expected behavior:**

It would be nice if it would not automatically add `http://` - at least without you knowing. I do realize that by taking that logic out of the modal, you could possibly create broken links if a person forgot to add that in themselves.

In the v10.1 I tested it on, `http://` was pre-populated in the field, but you could remove it if you wanted to and it would not come back.

**Actual behavior:**

`http://` is added without you knowing if the Insert Link modal does not see it in the URL.

### Versions

* **Rock Version:** [v11.0, v11.2]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Hi Mike @mikedotmundy, a few things here... The Insert Link popup field does not support adding Lava.  It's expecting an actual valid URL.  Also, when using that Lava (`{{ 'Global' | Attribute:'PublicApplicationRoot' }}`) elsewhere, it will simply replace it with whatever value is stored in that global attribute.  _That could possibly explain why you've seen different systems with different values._
![image](https://user-images.githubusercontent.com/383807/96161046-a7206480-0ecb-11eb-9518-f99c325b2c30.png)
