### ISSUE TITLE
Limit to Head of House in Connection Campaign not working

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4461]
### Description
I could not duplicate this on the demo sites (v11.0 and v12.0). I could only reproduce on my production and dev servers, both running v11.2. 

When creating a Connection Campaign and selecting "Limit to Head of House", the campaign does not create a single Connection Request for only the Head of Household. Instead it creates a Connection Request for each person in the household of the person in the Data View. 

I first realized this when my Pending Connections number was higher than the number of people in my Data View.

Here is the thread in chat where another person on v11.2 found the same issue: https://chat.rockrms.com/channel/engagement?msg=h47qEzStW6PBXCa2g

![](https://user-images.githubusercontent.com/23226974/96052142-ebb7eb80-0e4a-11eb-9c5a-bf8146bf07ba.png)

![](https://user-images.githubusercontent.com/23226974/96052150-eeb2dc00-0e4a-11eb-93f6-68c074dbfe40.png)

### Steps to Reproduce
1. Create a new Connection Campaign, looking at a Data View of just adults, but adults who have kids in their families, and then with "Limit to Head of Household" selected, and Create Connection Requests As Needed.
1. See that there are more pending connections than there are people in the Data View.
1. Run the Campaign Manager job.
1. See that kids in the family (not in the original Data View) now have Connection Requests created.

**Expected behavior:**

I would expect that "Limit to Head of Household" only creates 1 Connection Request per household, the head of household.

**Actual behavior:**

A Connection Request is being created for each person in the family of a person in the Data View.

### Versions
* **Rock Version:** [v11.2]
* **Client Culture Setting:** [en-US]

**Comment by mikedotmundy** [comment]
May just want to close this since I could not duplicate in v12.0 and I know connection gets an overhaul. But I did not see an issue created for this so wanted to at least document it.

**Comment by mikedotmundy** [comment]
I will also add that I do not believe the Campaign is respecting the Opt Out Group. In my original Connection Campaign, I also set up an Opt Out Group, with people in the group. A child of one of the people in this opt out group was added to the Campaign also.

**Comment by tommyprater** [comment]
I can concur that this is happening to us as well on v11.2

**Comment by nairdo** [comment]
We discovered this bug last week and fixed it via https://github.com/SparkDevNetwork/Rock/commit/3269cc629bd45fe5a58f7e6878c9bf7ca1cbbaab.   Because of this bug, we're going to push up the v11.3 release and get the alpha testing started asap (probably next week).  We're also going to have a rapid alpha->beta->release cycle so we can get this fix into your hands quickly.

We're also going to verify/fix the Opt Out Group concern also before we go alpha.
