### ISSUE TITLE
Typo: Following Event Detail Block

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4462]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Minor typo on Following Event Detail Block. For Send Weekend Notices on Friday, the help text says "Should any notices that would normally be sent on a weekend be sent of preceding Friday instead?" Should say ..."on preceding Friday instead?"

<img width="1680" alt="Screen Shot 2020-10-15 at 12 45 01" src="https://user-images.githubusercontent.com/23226974/96161079-d7c0c800-0ee4-11eb-8763-a1eacd27b3a2.png">

**Expected behavior:**

Should say "on".

**Actual behavior:**

Actually says "of".

### Versions

* **Rock Version:** [v11.2, v12.0]
* **Client Culture Setting:** [en-US]

**Comment by melodielange** [comment]
Typo has been corrected
