### ISSUE TITLE
Database Maintenance Job attempts to rebuild indexes for tables without an index

### ISSUE THREAD

**Issue by sichiriu** [SparkDevNetwork/Rock#4464]
### Description
After upgrading to 11.2, our Database Maintenance job started issuing warnings about attempts to rebuild indexes on tables that did not have an index. In our case, we had a few unused tables that were created as a part of our migration over 2 years ago. These tables were the ones the job reported errors on.

### Steps to Reproduce
I _think_ this could be a way to reproduce the issue. ¯\_(ツ)_/¯ 

1. Add a new table without an index to the db
1. Change the Database Maintenance job settings so that the job attempts to rebuild indexes for that table
1. Run the job and observe the warning

**Expected behavior:**

The Database Maintenance job should check whether or not an index exists before attempting a rebuild.

**Actual behavior:**

Exceptions are thrown because no index exists.

### Versions
* **Rock Version:** Rock McKinley 11.2 (1.11.2.1)
* **Client Culture Setting:** en-US

**Comment by megilee** [comment]
We are experiencing the same thing. I do not have the knowledge of SQL to troubleshoot or correct the specific table issue.

**Comment by andypullen** [comment]
We had this issue too from a `Families` table that I'm assuming was also from when our church imported from their previous system. @megilee Looking at the job history, it looks like the Database Cleanup job breaks down each needed table in its own task, and failing when it comes across a table without an index for whatever reason. It doesn't look like it keeps it from continuing through the other tables that also need cleaning, so I'm assuming you're safe to disregard these errors when they happen. I hope that helps!
