### ISSUE TITLE
Data automation is inactivating recent event registrants

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4465]
Submitted on behalf of [Sun Valley Church](https://www.sunvalleycc.com/)

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

The Data Automation setting do not have any way to exclude recent registrants on the Inactivate People settings. This is resulting in a large number of people who have recently registered for an event to get inactivated. It does allow for specifying a dataview to ignore, but the core dataview filters don't really have a way to easily filter on recent registrants to any event. 

We were able to work-around this by using the SQL Query filter form SQL Blue Box Moon's Data Toolkit plugin, but seems like the Data Automation settings should provide a way to exclude recent registrants.

![image](https://user-images.githubusercontent.com/548180/96605432-0d7dfc00-12ab-11eb-9c8c-496736d57079.png)

### Steps to Reproduce

1. Configure Data Automation to enable the Inactivate People settings
2. Ensure that you have people who have recently registered for an event and been matched to existing record based on name and email or phone and not logged in (if they log in, the interaction record will prevent them from being inactivated), and that do not have any other activity.
3. Run the data automation job

**Expected behavior:**

Those people would not be inactivated.

**Actual behavior:**

Those people are inactivated

### Versions

* **Rock Version:** 11.2
* **Client Culture Setting:** en-US

**Comment by karenn-ccbc** [comment]
Would an interaction with the external website not take into account event registrations?

**Comment by azturner** [comment]
@karenn-ccbc, if they were logged in, it would, but because they are not logged in an interaction is not created. Rock does still associate the registration with the person though because of a match on name and email or phone.

**Comment by nairdo** [comment]
Hi @azturner David, would you say the `In Registration Template(s)` Data View filter would work for that situation? 

![image](https://user-images.githubusercontent.com/383807/97925727-1fd24e00-1d1f-11eb-9e0b-2cc396131a0d.png)

 If you leave the Registration Template unset, it will look for any registration for any template:

![image](https://user-images.githubusercontent.com/383807/97926073-bdc61880-1d1f-11eb-838b-dec02ef6bbf4.png)

**Comment by azturner** [comment]
Yes that would work. Thanks @nairdo.

**Comment by karenn-ccbc** [comment]
However, you can only have one DV referenced correct in data automation -- so I would have to create a dataview to reference people in multiple other dataviews, since we have one that looks at people in security roles as well.

**Comment by nairdo** [comment]
We _are_ still considering adding something more for a v13 feature.  Something like the below in the Data Automation Setting's _Reactivate People_ and _Inactivate People_ sections:

> "Any family member has been registered for any event in the last" ____ days (or possibly any event of a configurable, optional drop-down list of registration templates) 

> "No family member has registered for any event in the last" ____ days
