### ISSUE TITLE
Page Parameter Filter causes Page Error when using Routes

### ISSUE THREAD

**Issue by tcavaletto** [SparkDevNetwork/Rock#4467]
Submitted on behalf of HFBC

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
If you try to add a page parameter filter block to a page that uses routes, it will cause the page to crash with a 'An item with the same key has already been added.' error thrown when getting page parameters (https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Web/UI/RockPage.cs#L2824). The cause is due to this line (https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Reporting/PageParameterFilter.ascx.cs#L719) not excluding parameters included in the route, so the PageParameters() method is trying to add PersonId twice, once from the route and once from the querystring. The solution is to update the line to read:

`if ( parameter.Key != "PageId" && !Page.RouteData.Values.Keys.Contains( parameter.Key ) )`

This fix has been tested and verified both locally and on HFBC's website.

Screenshots:
![image](https://user-images.githubusercontent.com/5482014/96785213-5913d100-13a3-11eb-8997-567c9b575b8c.png)
![image](https://user-images.githubusercontent.com/5482014/96785222-5b762b00-13a3-11eb-9bc5-ef133a055eec.png)

### Steps to Reproduce

1. Go to https://rock.rocksolidchurchdemo.com/Person/1
2. Add the Page Parameter Filter Block
3. Add any filter field and click 'Save'

**Expected behavior:**

The page should display the filter block with the configured filter fields.

**Actual behavior:**

The page crashes

### Versions

* **Rock Version:** 10.3, 11.1
* **Client Culture Setting:** EN-US

**Comment by cwomack** [comment]
@tcavaletto, it appears this issue was fixed in Rock v12.1 and can be verified on the demo site (currently v12.2). I'll close this issue out but feel free to comment back if you think it should be reopened or you see another bug tied to this. 

Thank you for helping make Rock better.
