### ISSUE TITLE
Groups with Scheduling Disabled are Still Visible in Scheduler Group Picker and Still Allow Scheduling

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#4468]
### Description
When configuring group scheduling for groups, there is a checkbox for disabling scheduling on each individual group. However, disabling scheduling for the group does not prevent it from being visible in the group viewer on the group scheduler page, and you can even schedule people for the group.

### Steps to Reproduce
1. Go to any group that has scheduling enabled for its group type (https://rockrmslatest.com/page/113?GroupId=57)
1. Add any person as a member of the group (so we can test scheduling them)
1. Edit the group
1. Go to "Meeting Details" and add any location/schedule combination.
1. Go to "Scheduling", and click the box that says "Disable Group Scheduling".
1. Go to the Group Scheduler (https://rockrmslatest.com/GroupScheduler)
1. See the group you just disabled scheduling for listed in the group picker (this shouldn't be visible if group scheduling is disabled for the group IMO)
1. Select that group
1. Drag the member we added in step 2 into the schedule (this shouldn't be possible if group scheduling is disabled for the group IMO)

![image](https://user-images.githubusercontent.com/2465823/96884428-7dc58280-144f-11eb-8eaf-5d42379bd1b0.png)
![image](https://user-images.githubusercontent.com/2465823/96884157-2fb07f00-144f-11eb-85cb-810c356ecdaf.png)
![image](https://user-images.githubusercontent.com/2465823/96884211-42c34f00-144f-11eb-8024-43ecd4a3b58c.png)

**Expected behavior:**

Any group that has group scheduling disabled should not be visible in the group scheduler, nor should you be able to schedule people for it.

**Actual behavior:**

Groups that have group scheduling "disabled" are currently visible, and seem to function for scheduling just like groups that have it enabled.

### Versions
* **Rock Version:** 12.0.7
* **Client Culture Setting:** en-US

**Comment by MikeDPeterson** [comment]
Fixed with https://github.com/sparkdevnetwork/rock/commit/8074e1cea0f933e5b8622896b84b5dc4b0d2a782
