### ISSUE TITLE
Checkin Aero Welcome page not showing correctly on Windows Check-In Client

### ISSUE THREAD

**Issue by atorrance** [SparkDevNetwork/Rock#4469]
### Description
The Check-In Aero theme is not showing the correct Welcome Image or Welcome Text in the Windows Check-In Client. Attached is an image of the screen running for the newly downloaded client from prealpha.rockrms.com. You can see that the image is missing and it is saying Welcome instead of Welcome to Rock Solid Church. This also occurred in our instance. 

_[Write a clear and concise description and include **full window** (non-partial) screenshots. FYI: You can just copy and paste an image directly into here and it will magically upload.]_

### Steps to Reproduce
1. Download the Checkin Client
1. Use the address: https://prealpha.rocksolidchurchdemo.com/checkin?theme=checkinaero
1. Start Checkin Test 

Checkin Aero should show Welcome Image and Welcome Text Correctly.

_[A clear and concise description of what you expected to happen.]_

**Actual behavior:**

_[A description of what actually happened.]_

### Versions
* **Rock Version:** [11.2 and 12.0]
* **Client Culture Setting:** [Enter Client Culture here]

[Untitled](https://user-images.githubusercontent.com/34725020/96892043-3ba03f00-1457-11eb-8f40-f92af7c3080c.png)

Expected: 
[image](https://user-images.githubusercontent.com/383807/97635115-12058b80-19f4-11eb-9dda-d7bad0f9a93c.png)

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1198971384860208">image.png</a>

**Comment by garrettjohnson** [comment]
To customize the welcome text on the Aero theme make sure to add quotes to your custom text as noted in the theme styler.
![image](https://user-images.githubusercontent.com/374209/97920208-5c4d7c00-1d16-11eb-84e2-b74d964f4738.png)

To change the welcome text on Internet Explorer and the Windows check-in client, we recommend duplicating the Aero theme, and then modifying line 63 of the Site.Master file with your customized text.
https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Themes/CheckinAero/Layouts/Site.Master#L63
