### ISSUE TITLE
V11 Connection Request - Campus Options Bug

### ISSUE THREAD

**Issue by TheArkChurch** [SparkDevNetwork/Rock#4470]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

In v 11 the campus selector is hidden on everything if your org only has 1 campus. This is causing issues with connection for orgs that have set up their connector groups and connection opportunities for their main(only) campus prior to v11. Since all of our connector groups\connection opportunities are set up for our main(only) campus and the campus selector is now gone, any new connections that are created manually don't have an associated campus which causes the connectors to not be able to edit them.

The main reason this is happening is because we had set everything up with the campus options on all of our connection opportunities and connector groups. Since the options are no longer available to change we're basically locked out of making any changes to resolve it without adding another campus to the system.

It should be noted that for new churches that come onboard this will not be an issue, and for any churches that never set the campus on anything this will not be an issue.

### Steps to Reproduce

Not reproducible unless you had configured your connection opportunities\ connector groups to use the only campus you had. If you did have this set up and upgraded to v11 you could.

1. Manually create a connection on an opportunity that was campus specific.
2. Assign it to a connector who's group was also campus specific and the same campus.
3. Impersonate the connector and try to edit the connection.

**Expected behavior:**

It's expected that if a connection request is created and assigned to a connector that the connector could edit and modify the connection.

**Actual behavior:**

This is a connection created by a workflow which sets the campus so everything works.
![Screen Shot 2020-10-22 at 9 53 48 AM](https://user-images.githubusercontent.com/38021725/96895735-53c18f80-1452-11eb-8c78-cc3ab28bc9bc.png)

This is a connection that was created manually and doesn't have the option to let you choose a campus.
![Screen Shot 2020-10-22 at 9 58 35 AM](https://user-images.githubusercontent.com/38021725/96895919-91261d00-1452-11eb-8c3b-1e1f48633791.png)

### Versions

* **Rock Version:** [11.2 (1.11.2.1)]
* **Client Culture Setting:** [en-US]

**Comment by cabal95** [comment]
I'll just throw out an idea.  What if we add a global attribute setting that controls the campus picker in single-campus installations:

1. Always Show Picker
2. Always Hide Picker
3. Hide Picker if currently empty

The first two are fairly straightforward, the user gets to choose whether to show or hide the picker (this could also provide a way to "quick fix" these types of errors by letting you show the picker to fix the data then hide it again).

The last one would work this way.  If the current value is blank then the picker is hidden. So for example if you are entering a NEW connection request, it wouldn't ask for campus because the current value is blank / doesn't exist. If you are editing an OLD connection request that does have a campus already set, the picker would show up. If you then were to change the value to blank and save, the next time you try to edit the campus picker would be hidden.

**Comment by TheArkChurch** [comment]
I'm not sure if a default fresh install of rock has a campus created or not but if it does I think another option could be to default anything created in the system(groups, connections, people, giving accounts, etc.) to that campus, while keeping it hidden.

My thinking is that if there's ever a second campus created, the work needed to be done to set everything up is greatly reduced because you won't have to go through possibly hundreds of things and set the campus. Since most(if not all) things that were created prior to adding a new campus, probably would be assigned to the main(first) campus.

**Comment by nathanp** [comment]
We are having a similar issue on the latest version of v12.
Certain people are not assigned a campus in the Connection Request, so our staff can't edit or add activities, etc.

As a temporary workaround, I fixed this by using the following SQL query:
```
UPDATE
    [ConnectionRequest]
SET
    CampusId = 1
WHERE
    CampusId IS NULL
```

**Comment by GarriDarter** [comment]
Rock Version: Rock McKinley 12.6 (1.12.6.1)
Client Culture Setting: en-US

Would the above work around also work when there are already multiple campuses?  I am not a developer nor do I know SQL.  Does the above workaround need to be added to all workflows that create connection requests?

**Comment by nathanp** [comment]
@GarriDarter we only have one campus, so I'm not 100% sure.

In our experience, it only happened for some requests, not all, so I don't know that it would need to be added to all workflows.
