### ISSUE TITLE
Aero Theme on iPad Check-in not scrolling people

### ISSUE THREAD

**Issue by MCoulterFBCN** [SparkDevNetwork/Rock#4479]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

If you have 8 or more people you can check-in on a check in list and you are using the Aero theme in v.11.2, you cannot scroll down to the last person(s) on the page.  This was tested on our instance as well as on the Rock Demo site.  It did work when the demo site was at v.11.0 but we the Demo site was upgraded to v.11.2 it no longer worked. 

### Steps to Reproduce

1. On v.11.2, Go to a check-in window (https://rocksite/checkin).  It does not have to be in the check-in app. 
2. Load the CheckinAero theme.
3. Select a family that can log in many kids... I added more to the Greggs Family (last four of phone - 4450).
4. Try to scroll to the bottom of the screen and select the last person but see that they are blocked by the Next button.

![image](https://user-images.githubusercontent.com/383807/98051424-187b7500-1df1-11eb-8c0a-130dd270eb11.png)

**Expected behavior:**

Should be able to scroll all the way down as still possible in version 11.0.

**Actual behavior:**

Can no longer scroll all the way down.

### Versions

* **Rock Version:** v.11.2
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1199091762812112">image.png</a>

**Comment by cabal95** [comment]
This is related to #4401. We saw this as well. Basically the fix in #4401 added this CSS:

```css
.checkin-scroll-panel {
  bottom: 0 !important;
}
```

Which forces the body to go all the way to the bottom of the page - but that is not correct. There are parts of the check-in process that put information at the bottom of the page (such as the admin override buttons, or the setup screen to select your areas).

You can easily see this bug by going to the pre-alpha site and the /checkin link. Then change the theme to Aero and select the main kiosk. Then shrink your window vertically a bit and you will notice the list of areas goes to the bottom of the window and interferes with the buttons.

![image](https://user-images.githubusercontent.com/1119863/98140620-80c26900-1e7a-11eb-992e-9c81efd5b9e4.png)
