### ISSUE TITLE
Order Property of Manually Sorted Child Items is 0 in the Database

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4480]
### Description
When a content channel item is set to have the child items manually ordered, and you rearrange those child items in the web interface, the Order column shows the correct order in the block. However, if you look at the Order column of the ContentChannelItem table, you see that the Order is 0.

I believe this is related to fix #4248.

### Steps to Reproduce
1. On the demo site, go to Admin Tools > CMS Configuration and click on Content Channels
1. Click on Service Bulletin and then click Edit
1. Scroll down and check _Child Items Manually Ordered_
1. Add Service Bulletin as a valid type under "Child Content Channels", then click Save
[image](https://user-images.githubusercontent.com/66277785/97912609-04fdda80-1d1b-11eb-8622-03ea18e1b253.png)
1. Click the + button to add a new Service Bulletin content channel item and name it something
1. Click on the newly created content channel item, and add a few child content channel items to it
1. Click on the parent item created in step 5 and see the Order column is populating as it should be
1. Take note of the Id of the parent item
1. Then in a new tab, go to Rock Settings > Power Tools > SQL Command and run this query, changing `##` to whatever the Id noted in the previous step
`SELECT cci.Title, cci.[Order]
 FROM ContentChannelItemAssociation ccia
 JOIN ContentChannelItem cci ON (ccia.ChildContentChannelItemId = cci.Id)
 WHERE ccia.ContentChannelItemId = ##`

**Expected behavior:**

The Order property of the items stored in the ContentChannelItem table in the database should match what is shown in the UI.

**Actual behavior:**

The Order property of the items in the ContentChannelItem table in the database is 0.

![image](https://user-images.githubusercontent.com/66277785/97912448-d5e76900-1d1a-11eb-9007-7e187aa7bdb9.png)
![image](https://user-images.githubusercontent.com/66277785/97912486-e13a9480-1d1a-11eb-9a8c-8ce7467004d5.png)

### Versions
* **Rock Version:** [Rock McKinley 11.2 (1.11.2.1)]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
@leahjennings Can you add the `ccia.[Order]` of the Content Channel Item Association (ccia) to your query and tell me if it is showing the correct order:

```Sql
                               vvvvvv
SELECT cci.Title, cci.[Order], ccia.[Order]
FROM ContentChannelItemAssociation ccia 
JOIN ContentChannelItem cci ON (ccia.ChildContentChannelItemId = cci.Id)
WHERE ccia.ContentChannelItemId = ##
```

**Comment by leahjennings** [comment]
@nairdo ah, I see. Yeah, adding the ccia.[Order] to the query does show the correct order. Thank you for clarifying that!
