### ISSUE TITLE
Creating a Personal Template from a Sent communication throws error

### ISSUE THREAD

**Issue by karenn-ccbc** [SparkDevNetwork/Rock#4481]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Attempting to save a personal communication template from a previously sent communication saves, but throws an error on save. Cannot confirm in Rock Demo due to no previous communications in there.

### Steps to Reproduce

1. Turn on Enable Personal Templates on the Communication Detail Block
2. Click on Messages on a previous communication 
3. Click on Create Personal Template, name it and SAVE
4. Upon save the page does not go away and appears to have not saved.
5. Scroll to the top and see this exception
![image](https://user-images.githubusercontent.com/35667472/98050094-a27a0c80-1df6-11eb-8016-6094b08ef59b.png)
6. Check in your Personal Templates on My Settings and the Template was saved. Often times, saved twice because you clicked save again thinking it had not saved.

**Expected behavior:**

Create a personal template, name it and save it and the pop up box would go away once the template saved.

**Actual behavior:**

Upon save the page does not go away and appears to have not saved.
Scroll to the top and see this exception
![image](https://user-images.githubusercontent.com/35667472/98050094-a27a0c80-1df6-11eb-8016-6094b08ef59b.png)
Check in your Personal Templates on My Settings and the Template was saved. Often times, saved twice because you clicked save again thinking it had not saved.

### Versions

* **Rock Version:** [Tested in both 10.2 and 11.2]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by cabal95** [comment]
Confirmed on demo site.
