### ISSUE TITLE
Financial Transaction Fee field missing

### ISSUE THREAD

**Issue by DTS-Mike** [SparkDevNetwork/Rock#4490]
### Description
When entering a transaction the Fee will only show up on the first entry of the transaction detail.   It also will not show in the grid of all the transaction details.  On the second transaction the fee field is missing. Following the steps below will show 4 different issues.  I can reproduce this issue on a couple active Rock installs (V11.3), Rock Demo Site (V11.2), and prealpha (V12.0).

### Steps to Reproduce
1. Go to Batch Over and create a new batch
1. Click on add new transaction to the batch
1. Enter all the details about the transaction on the left.
1. Enter 100 dollars to the general fund.
1. Enter 3 dollars to "Fee" Field
1. Hit save.  (Now the transaction screen will be missing the $3 entered above) **Issue 1**
1. Click on "Save Then Add" (The fee field is missing on the new transaction) **Issue 2**
1. Click "Additional Accounts" (Fee field and header are missing from the grid completely) **Issue 3**
1. Click on the edit icon.
1. The fee field is missing on the modal. **Issue 4**

Link to Video: [https://www.screencast.com/t/bg6247oT](https://www.screencast.com/t/bg6247oT)

**Expected behavior:**

I would have expected the fee field to stay on the screen or a block setting to hide the fee entry boxes from showing.

**Actual behavior:**

Fee field is not constant.

### Versions
* **Rock Version:** 11.0 - 12.0
* **Client Culture Setting:** en-US

**Comment by bjwiley2** [comment]
Fixed with https://github.com/SparkDevNetwork/Rock/commit/6afbc0e2aa5589f304116bcebfcaf31ea4e777fa
