### ISSUE TITLE
Geo-Point & Geo-Fence Data Causing Errors with Reports, Lava, & SQL within Rock

### ISSUE THREAD

**Issue by Luke-Potter** [SparkDevNetwork/Rock#4495]
### Description
We encountered a bug that's to do with Rock trying to handle Geo-Points & Geo-Fence data. This is causing errors within Rock's environment only, but can be seen in Reports, Dataviews, Lava, and the SQL Command tool. The error being thrown is _"Error SQL Error! DataReader.GetFieldType(5) returned null."_ This has been verified on the demo site, the prealpha site, my instance, and 3 instances within the community. 

![image](https://user-images.githubusercontent.com/31108929/99582654-49ce7600-2997-11eb-91b0-168f33816c41.png)
![image](https://user-images.githubusercontent.com/31108929/99582743-65d21780-2997-11eb-8d35-66152e0d20e9.png)

### Steps to Reproduce
**1.** Go to the SQL Command Power Tool
**2.** Run the following query: 
_SELECT
 TOP 10 *
FROM
 [Location]_

**3.** To show it's the Geo data run the following:
_SELECT TOP (10) [Id]
 ,[ParentLocationId]
 ,[Name]
 ,[IsActive]
 ,[LocationTypeValueId]
 --,[GeoPoint]
 --,[GeoFence]
 ,[Street1]
 ,[Street2]
 ,[City]
 ,[State]
 ,[Country]
 ,[AssessorParcelId]
 ,[StandardizeAttemptedDateTime]
 ,[StandardizeAttemptedServiceType]
 ,[StandardizeAttemptedResult]
 ,[StandardizedDateTime]
 ,[GeocodeAttemptedDateTime]
 ,[GeocodeAttemptedServiceType]
 ,[GeocodeAttemptedResult]
 ,[GeocodedDateTime]
 ,[PrinterDeviceId]
 ,[Guid]
 ,[CreatedDateTime]
 ,[ModifiedDateTime]
 ,[CreatedByPersonAliasId]
 ,[ModifiedByPersonAliasId]
 ,[IsGeoPointLocked]
 ,[ForeignKey]
 ,[ImageId]
 ,[PostalCode]
 ,[ForeignGuid]
 ,[ForeignId]
 ,[County]
 ,[Barcode]
 ,[SoftRoomThreshold]
 ,[FirmRoomThreshold]
FROM
 [Location]_

**Expected behavior:**
I'd expect the query, lava, and reports to correctly run without throwing errors that are related to the Geo Data.

**Actual behavior:**
The Geo Data throws a error to do with the Geo Data being a Complex Datatype and Rock not parsing it correctly. 

### Versions
* **Rock Version:** [Rock McKinley 11.3 (1.11.3.1)]
* **Client Culture Setting:** [en-US]

ALSO REPLICATED ON:
Rock McKinley 11.1 (1.11.1.1)
Rock McKinley 11.2 (1.11.2.1)
Rock McKinley 12.0 (1.12.0.9)

**Comment by Luke-Potter** [comment]
**Note I forgot to include:**
There are not datatype errors being thrown when in SSMS.

**Comment by JimMichael** [comment]
I didn't repeat all the tests above, but running the SQL in Step 2 in the SQL Power Tool does throw an error on my 11.3 instance, but not on my 10.2 instance.

**Comment by Luke-Potter** [comment]
@JimMichael We first noticed it on a Report we have that returns addresses for our Christmas card. As such we haven't ran it since we were on 10.x last year. So I think it's a bug that was introduced in 11.x & is still there in the current alpha of 12.x

**Comment by nairdo** [comment]
@JimMichael  @Luke-Potter Although this sounds similar to #4444 (because you can't pull the string value out of a 'geography' field** using the SQL Power Tool), I'm willing to dig a bit more on this -- and it should definitely not be broken for DataView Reports.  I just confirmed it is fine on the pre-alpha site:

![image](https://user-images.githubusercontent.com/383807/99599896-8ad78200-29b9-11eb-8180-7ef89fa16f80.png)

![image](https://user-images.githubusercontent.com/383807/99599922-94f98080-29b9-11eb-8661-c674f82661a4.png)

What _Field Type_ are you trying to use in your Rock Report?

Also...

I have a v8.9 server which also throws the same error and it is on a `Microsoft SQL Server 2017` database while my `Microsoft SQL Server 2012` [pre-Rock-version 11](https://community.rockrms.com/developer/changelog#m11.0) instances provide a default format for geography fields like this: `POINT (-112.126459 33.590795)` and `POLYGON ((-111.787077 33.432155, -111.790853 33.426998, -111.784502 33.416539, -111.760641 33.421267, -111.753946 33.430006, -111.771971 33.439461, -111.787077 33.432155))` for geo-fences.

Can you both include the version of SQL server your running on?


<sup>** Since those two fields are 'geography' [complex] datatypes, you'll need to specify what form you want out of the values. For example, you might want it as a 'point string' or 'polygon string' (for the GeoFence column):</sup>
<sup><tt>SELECT TOP 100 GeoPoint.STAsText(), GeoFence.STAsText() FROM [Location]</tt>
or you might just want the Latitude and Longitude out of the GeoPoint datatype as separate columns:</sup>
<sup><tt>SELECT TOP 100 GeoPoint.Lat AS [Latitude], GeoPoint.Long AS [Longitude] FROM [Location]</tt></sup>

**Comment by JimMichael** [comment]
On my production 11.3 db I'm running:
**Database Version: Microsoft SQL Server 2017 (RTM-CU22) (KB4577467) - 14.0.3356.20 (X64) Aug 20 2020 22:33:27 Copyright (C) 2017 Microsoft Corporation Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 (Build 14393: ) (Hypervisor)** 

And on my 10.2 test instance (copy of prod) I'm running :
**Microsoft SQL Server 2019 (RTM-CU8) (KB4577194) - 15.0.4073.23 (X64) Sep 23 2020 16:03:08 Copyright (C) 2019 Microsoft Corporation Standard Edition (64-bit) on Windows Server 2019 Datacenter 10.0 (Build 17763: ) (Hypervisor)** 

However, to make matters more confusing (and I get what you're saying about the "error" in the SQL power tool being expected, THIS is what I get on the 10.2 / SQL 2019 server when I run the query against location:
![image](https://user-images.githubusercontent.com/3903408/99600702-92038d80-29c3-11eb-8990-15bc7fafa935.png)
_It actually returns a grid_  I don't know what that means or if it's even relevant... I just assumed that when I tried it and it worked on that instance, but not the other, it had broken.

**Comment by Luke-Potter** [comment]
We're hosted on Azure, so I guess that'd be Azure SQL. If i'm missing something, I'm happy to follow instructions to find a version number for you. 

So am I understanding that the issue isn't an issue, but an intended function as far as the Power Tool SQL is concerned?

**Comment by nairdo** [comment]
> So am I understanding that the issue isn't an issue, but an intended function as far as the Power Tool SQL is concerned?

Yes mostly, but I'm willing to investigate a bit more.  I just ran an experiment, and if there _is_ a simple ([no-unintended-consequences](https://til.secretgeek.net/sql_spatial/getfieldtype_returned_null.html)) way to signal the app to bind to the correct Microsoft.SqlServer.Types then it _might_ be possible to get it to work in the SQL Command.

@Luke-Potter But more importantly -- what **Field Type** are you trying to use in your Rock Report?  It should not be broken there.

**Comment by Luke-Potter** [comment]
![image](https://user-images.githubusercontent.com/31108929/99602900-261b2800-29b7-11eb-94f8-0c5a71ae3d7c.png)

These are the fields we're using that when removed fix the issue. The issues may not be related like I thought, but the report started throwing errors & then I went to troubleshoot and SQL started throwing errors I hadn't previously encountered on the same table I figured they were linked. I may have linked them by correlation, when the causation was different. 
I put the error the report is throwing in the initial post, but here it is in text form: 
`NullReferenceException in Rock
Message
Object reference not set to an instance of an object.

Stack Trace

   at Rock.Web.UI.Controls.Grid.GetExportValue(PropertyInfo prop, Object propValue, Boolean isDefinedValueField, ExcelRange cell)
   at Rock.Web.UI.Controls.Grid.Actions_ExcelExportClick(Object sender, EventArgs e)
   at Rock.Web.UI.Controls.GridActions.lbExcelExport_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)`


We're getting this error on any report that's reporting on Addresses. It's caused when we try to export the list or put it on a page. 
Like I said if I accidentally correlated these issues unduly, that's my bad. 





Just so I'm understanding, what exactly is the issue with PowerTools SQL & Geodata?

**Comment by nairdo** [comment]
> what exactly is the issue with PowerTools SQL & Geodata?

@Luke-Potter Take a look at my response in https://github.com/SparkDevNetwork/Rock/issues/4444.  I don't know what more I can say...

Without specifying how you want to format the complex geography datatypes, in older SQL Server it would default format the value as I showed above (similar to the `.STAsText()` format).   However, you can just tell SQL server what property of the geography datatype you want.  For example, you can do this to get the `.Lat` and `.Long` property out of the GeoPoint geography field:

```Sql
SELECT TOP 10 GeoPoint.Lat AS [Latitude], GeoPoint.Long AS [Longitude] FROM [Location]
```

or you can use the `.STAsText()` method to show the `GeoFence` or `GeoPoint` similar to the old behavior:

```Sql
SELECT TOP 10 GeoFence.STAsText(), GeoPoint.STAsText() FROM [Location]
```

**Comment by Luke-Potter** [comment]
Gotcha. In our report though it's not referencing a complex geo datatype, just addresses. Is there a link between these two issues or did I match two things up that aren't related? Sorry if that's a stupid question, just trying to make sure there isn't something I'm missing here.

**Comment by nairdo** [comment]
@Luke-Potter I think I'm missing something that you're doing in your system.  I set up a Report on the v11.2 demo site (may or may no longer be there when you read this: https://www.rocksolidchurchdemo.com/page/149?ReportId=5) and a few fields to use Lava to display parts of the Address (Street1 and Latitude):

![image](https://user-images.githubusercontent.com/383807/99687004-64f5c000-2a41-11eb-969a-4762411e1633.png)

...but it's working as I would expect:
![image](https://user-images.githubusercontent.com/383807/99687063-750d9f80-2a41-11eb-98eb-58368197bf09.png)

Can you screen-capture the report field and report output that is not working for you?
