### ISSUE TITLE
Simple Editor Email Template displays only HTML when a Data View with over 5,400 recipients is used

### ISSUE THREAD

**Issue by mswartztex** [SparkDevNetwork/Rock#4499]
### Prerequisites ###

* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported? **YES**
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? **NOT ABLE TO**
  * Did you include your Rock version number and [client culture] **YES**
(https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description ###

Upon sending a new email communication using Simple Editor and a Data View with over 5,400 recipients (rows of people) causes the email template to no longer have a "preview" option and shows only the HTML.  Multiple Data Views and different templates have the same result.  Data Views with less than 5,000 rows works as expected.  Upon creating and testing many different Data Views, I was able to narrow down the threshold tipping point being; a Data View with 5,527 rows worked as expect, but one with 5,647 rows did not.

This issue just started happening during the week of October 19th, one week prior to wrapping up development project with Spark to go live on our first ROCK public website.

Any and all assistance is greatly appreciated!

### Steps to Reproduce ###

1. Create or go to an Data View based upon "Person" with filter settings: Record Status = Active, Age Classification = Adult, and Gender = Male - Total of 8,827
1.  Click New Communication Icon to navigate to the new email communication page
1. Click "Use Simple Editor"
1.  Select any saved template (I have selected a simple generic template)

**Expected behavior:**

Using the same steps as above (with Data Viewing having 5,423 recipients and the same template), the expected behavior is that the selected template will display the graphics, the template greeting and instructions to the user where to insert the message body shown below:

[image](https://user-images.githubusercontent.com/43970752/100159053-b2739200-2e72-11eb-886b-6ebde1ac368d.png)

**Actual behavior:**

Using a Data View with 5,650 recipients and the same template, resulted in the template body **not** displaying the template graphics, template greeting or the editing tools.

This print screen displays the page Before selecting a template:

[image](https://user-images.githubusercontent.com/43970752/100159374-46455e00-2e73-11eb-9258-5f4da1142db1.png)

This one displays the page after selecting the template and shows what the problem is:[image](https://user-images.githubusercontent.com/43970752/100158728-4133df00-2e72-11eb-98a1-c28ee9ca8735.png)

This print screen displays the page with the same template selected that was used above:

Our users that send out bulk email are Church Campus administrative assistants and do not know how to edit or use HTML to add the intended message body and formatting.

_[A description of what actually happened.]_

The results are that the editor tools no longer appear and the message no longer displays our template graphic and greeting.

### Versions ###

* **Rock Version:** [Rock McKinley 9.4 (1.9.4.1)
* **Client Culture Setting:** [en-US]

**Comment by jonedmiston** [comment]
@mswartztex can you confirm this is still an issue. I tested this on v16.0 with a data view of over 17K and it is working for me.

**Comment by mswartztex** [comment]
Hello! I apologize for the delayed reply.  This issue can be closed out. We are no longer experiencing this.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jonedmiston** [comment]
Awesome! @mswartztex thanks for following up!
