### ISSUE TITLE
v12.0 Alpha - Exception log - "You are importing a .less file that cannot be found"

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4501]
### Description

Since updating to v12.0, An exception has been recorded every day. "You are importing a file ending in .less that cannot be found [_variable-overrides.less]."

I did not see this happening on the Pre-Alpha site, however I did confirm with Jim Michael in chat that he is seeing it as well. https://chat.rockrms.com/group/alpha-testers?msg=RZfqeSSk9E3BhcM2T

<img width="1680" alt="Screen Shot 2020-11-25 at 08 03 35" src="https://user-images.githubusercontent.com/23226974/100232043-d330fb80-2ef5-11eb-9ec3-6121fbad39fa.png">

<img width="1680" alt="Screen Shot 2020-11-25 at 08 03 47" src="https://user-images.githubusercontent.com/23226974/100232050-d4fabf00-2ef5-11eb-9b71-69ae319f76f2.png">

### Steps to Reproduce

Unsure? This started happening on day 1 of updating to v12.0.

**Expected behavior:**

No exception being recorded in the log.

**Actual behavior:**

Exception is recorded in the log

### Versions

* **Rock Version:** [v12.0 (1.12.0.9)]
* **Client Culture Setting:** [en-US]

**Comment by JimMichael** [comment]
I, too, am seeing this exception. It seems to happen every time Rock is restarted.

**Comment by nairdo** [comment]
We are getting this addressed for the beta.  Whenever a new theme's new *overrides.less file is established in a release, we have to ship the empty file once _and only once_ in the update package so we do not over-write any custom changes the admin makes later.
