### ISSUE TITLE
v12.0 Alpha - Person Attributes deleted when editing profile on External Site

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4505]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

On the newly redesigned `/MyAccount` page, if the user has been given the ability to edit certain Person Attributes, and those attributes have values in them, they disappear upon editing, and then a save removes the values.

The steps below detail Adult Person attributes, however this is happening for Child Person attributes as well.

### Steps to Reproduce

1. Go to the Extended Attributes page for Alisha Admin (`https://rockrmslatest.com/Person/1/ExtendedAttributes`)
2. Add an attribute for her Facebook (e.g. `Alisha.Admin`) and one for her Employer (e.g. `Rock RMS`)
3. While logged in as Alisha Admin, navigate to `/MyAccount` page.
4. Edit the block settings for the Public Profile Edit block.
5. Add the two Person attributes from above to the `Person Attributes (adults)` field (Facebook and Employer), then Save
6. See that the two attributes are now visible on her external profile page.
7. Click `Update Profile`
8. Notice that those two attributes are now blank.
9. Save
10. Notice that those two attributes have now been removed from her profile.

Set some attribute values:
<img width="1680" alt="Screen Shot 2020-11-25 at 15 39 33" src="https://user-images.githubusercontent.com/23226974/100280392-1ca13b00-2f36-11eb-9184-4b0adc45c44c.png">

Add the attributes on the external site:
<img width="1680" alt="Screen Shot 2020-11-25 at 15 39 10" src="https://user-images.githubusercontent.com/23226974/100280533-51ad8d80-2f36-11eb-9f15-51caeeb7da52.png">

See they display on the external site:
<img width="1680" alt="Screen Shot 2020-11-25 at 15 39 18" src="https://user-images.githubusercontent.com/23226974/100280440-317dce80-2f36-11eb-9fd8-e631ebbe7311.png">

Edit the profile and see the attributes are not in the field:
<img width="1680" alt="Screen Shot 2020-11-25 at 15 39 26" src="https://user-images.githubusercontent.com/23226974/100280582-6853e480-2f36-11eb-81a5-65f53f737438.png">

**Expected behavior:**

I would expect that Person Attributes would appear filled-in when a person edits their profile, so they do not accidentally remove an attribute by not noticing that the value was blank.

**Actual behavior:**

~If they save without re-filling in the value, then the values are removed.~ A save removes the values no matter what.

### Versions

* **Rock Version:** [12.0 (1.12.0.9)]
* **Client Culture Setting:** [en-US]

**Comment by jonedmiston** [comment]
Great testing @mikedotmundy !!!

**Comment by mikedotmundy** [comment]
Adding to this, it looks like even if you put a value in one of these Person Attribute fields and click save, the value is never saved.
