### ISSUE TITLE
Giving kiosk not able to give change amount

### ISSUE THREAD

**Issue by jerm55** [SparkDevNetwork/Rock#4510]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Rock v11.2 maybe in previous version, on the giving kiosk (https://rock.rocksolidchurchdemo.com/kiosk) while giving and trying to put it a period say like giving $5.50 the period doesn't seem to work. In Chrome and Edge it clears the amount completely, but in Firefox it just removes the period  while typing the 50 cents.. Mac Safari and PC Internet Explorer are the only that it seems to work in. Tested on Mac and Windows 10 PC.

![image](https://user-images.githubusercontent.com/24254367/100939508-3b11b400-34ab-11eb-8517-2c4be4122876.png)

### Steps to Reproduce

1. Go to 'https://rock.rocksolidchurchdemo.com/page/385'
2. Click on 'Give Anonymously' in the lower right corner
3. Click the '5' button then '.' then '5' and '0' buttons
4. Depending on the browser the field gets cleared or the period is removed..

**Expected behavior:**
I would expect that the period would be an excepted value in the dollar field..

**Actual behavior:**

People are unable to give a dollar amount and change from the giving kiosk

### Versions

* **Rock Version:** v11.2 (1.11.2.1)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Confirmed on Firefox Win10.  For what it's worth, seems to be related to the on-screen buttons. If I use my keyboard to type in "22.42" it correctly gives me twenty-two dollars and forty-two cents. If I use the on-screen buttons, I get two-thousand two-hundred and forty-two dollars.
