### ISSUE TITLE
Campus Location ImageUrl randomly chooses the domain

### ISSUE THREAD

**Issue by bobbrown** [SparkDevNetwork/Rock#4511]
### Description
When calling the campus ImageUrl in lava it selects a random domain name from the site even if the domain name is not externally accessible. We noticed because the Service Reservation images would sometimes not load and each campus image was from a different URL. 

### Steps to Reproduce
1. Add an image to the location tied to a campus 
1. In an HTML block, add the following Lava
{% for campus in Campuses %}
 Name: {{ campus.Name }}<br/>
 ImageURL:{{ campus.Location.ImageUrl }}<br />
{% endfor %}
1. Load the page and look at the domain name. 
1. Clear the Rock Cache and load the page again. The domain name may change.
On the demo site it used the following: 
 https://rock.rocksolidchurchdemo.com:443
 http://45.76.225.159:80
 https://rocksolidchurchdemo.com:443

**Expected behavior:**

I expect an externally accessible URL for an image so that it does not break when shown to the public. This would be easier when loaded on a site itself, but should probably default to the Public Application Root global variable for messages.

**Actual behavior:**

It does seem more likely to get whatever domain you are loading the image on, but it caches it so that it will sometimes be something else either exposing domain names you don't want for general use or routes that are not externally accessible.

### Versions
* **Rock Version:** 11.2
* **Client Culture Setting:** en-US

**Comment by cwomack** [comment]
@bobbrown are you able to reproduce this issue on the current demo site?  Also, would you mind replying with a screenshot of what is selected for the "**Lava Support Level Value**" if you're able to reproduce again?   This can be found under _Admin Tools > General Settings > Global Attributes > Lava Support Level Value_ (screenshot below). 

![image](https://user-images.githubusercontent.com/67726635/120549606-abd95080-c3a8-11eb-8354-844e32f12f96.png)

**Comment by cwomack** [comment]
@bobbrown should this still be an issue for you on your local environment or if you can reproduce it on Rock v12.2+ on the demo site, please comment back with some screenshots.  I'll close this out for now, but will reopen if needed or the issues persist.
