### ISSUE TITLE
Default/Demo Parallax image no longer works

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4514]
### Description

I'm not sure when this broke, but the _default_ site/image used as an example on the _Parallax_ Lava Shortcode no longer works properly.

### Steps to Reproduce

1. Go to Admin | CMS Config | Lava Shortcodes and copy the Parallax example into a HTML block
2. Observe that the block does not render the (example) background image requested.

**Expected behavior:**

The example for using this shortcode would work

**Actual behavior:**

It has at least two problems:

1. It's using a http:// protocol scheme which modern browsers reject if you've embedded it on a https:// Rock page.

2. Even when changing THIS particular example URL in the shortcode 
<pre>{[ parallax image:'http://cdn.wonderfulengineering.com/wp-content/uploads/2014/09/star-wars-wallpaper-4.jpg' contentpadding:'20px' ]}
    <h1>Hello World</h1>
{[ endparallax ]}</pre>
to httpS, I still cannot get it to run. One time I got a weird message on a page about cross-side something or other when visiting that image directly in a browser, but I can't get that to repeat here. Yet, I still cannot get the example shortcode to run, even on demo.

To be clear, I don't think there's anything wrong with the Short Code *itself*, as it works fine where we're using it... it's just something wrong with the site this *example* image is hosted on that is causing problems, and it should probably be changed to some image ON the rockrms.com site so that it can be guaranteed to be there, and work as expected.

### Versions

* **Rock Version:** All

**Comment by cabal95** [comment]
Agreed w/ Jim, it looks like it's just the image. The site seems to have implemented some security procedures on browser first visit:

![image](https://user-images.githubusercontent.com/1119863/101398246-03c84c00-388b-11eb-87e7-fdc5482dd413.png)
