### ISSUE TITLE
DataViewDetail incorrectly not? setting lastRefreshDateTime

### ISSUE THREAD

**Issue by stevelipinski** [SparkDevNetwork/Rock#4515]
https://github.com/SparkDevNetwork/Rock/blob/92a8d7ed6cb2b609a88c1380638679e735735144/RockWeb/Blocks/Reporting/DataViewDetail.ascx.cs#L916-L919

Appears like this is an incorrect if statement - maybe should be a != instead of ==?

Note: Found through simply reading the code to understand the behavior of newly-added Data View run details, thus not sure of the actual impact of this issue.  Seems like this would result in the status not correct in many situations.

**Comment by nairdo** [comment]
Thanks @stevelipinski We're looking at this too.  (I think you may be right.)
