### ISSUE TITLE
IPAD on IOS 14.2 or 14.3 will not print check in labels

### ISSUE THREAD

**Issue by mikesipps** [SparkDevNetwork/Rock#4537]
Description
I'm actually not sure if this would be considered a bug, IPADS that update to latest IOS version will not print.  It seems the toggle for local network access disappears after update.  The rock check-in app will no longer print to networked printer.  I can print a test page using the zebra utilities from the iPad.  The iPad will check the individual in and then give a network error when attempting to print the labels.

Steps to Reproduce
Check in via iPad on 14.2 +
attempt to print label

Check - Settings - Privacy - local network 

Expected behavior:
Is for application to have access the the local network and print labels.

Actual behavior:

Print error

Versions
Rock Version: 11.0+ and IOS 14.2 and 14.3

**Comment by JimMichael** [comment]
I cannot duplicate this here. I have an ipad that was on 14.2 that worked fine (in fact, did all my v12 testing with it), so I upgraded it to 14.3 and it still functions as expected.
![image](https://user-images.githubusercontent.com/3903408/103685144-52ccd400-4f52-11eb-9cb0-1f90f09ce3fc.png)
![image](https://user-images.githubusercontent.com/3903408/103685180-637d4a00-4f52-11eb-8903-edd5c8eab5e3.png)

Is it possible you have some sort of MDM managing your ipads that could be messing with that setting?

**Comment by mikesipps** [comment]
Thanks for the reply, it is baffling.  I will keep working on it.


Mike

________________________________

**Comment by nairdo** [comment]
I also tested on an iPad (iOS 14.2) using the Rock Check-in (v 1.9.1) app against both the https://www.rocksolidchurchdemo.com/checkin (running v11.2) and my local Rock instance running v12.1 and was able print via the 'Printer Override' IP address (which is on our local network) for both cases.    So, at this point we'll have to wait to see if anyone else has a problem and/or can point us to come other configuration difference that is not being described.  (I'm assuming you've set the IP address in your iPad app's **Printer Override** setting too [as mentioned here](https://community.rockrms.com/documentation/bookcontent/10/208#divingdeeperintoprinting).)

**Comment by DTS-Mike** [comment]
@nairdo This can be closed.  Did a refresh on the network and the issue went away.
