### ISSUE TITLE
Connection Opportunity Workflow Trigger "Future Follow-up Date Reached" will only trigger one time

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4539]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

The Connection Workflow Trigger _Future Follow-up Date Reached_ will only trigger the workflow the _first_ time the job runs after the Follow-up date has been reached. After the Workflow has been triggered, if you then add a new Future Follow-up date to the Connection Request, it will not trigger the workflow again.

 In my scenario, the Workflow attached to this trigger is a simple notification sent to the Connector that the date has been reached. So with no notification sent, it could be several days or more before it is noticed that the request is now Active again.

### Steps to Reproduce

1. Create a Connection Opportunity Workflow Trigger for Future Follow-up Date.
2. Create a Connection Request in the Opportunity, and set a Future Follow-up Date. You can set the date for the current day.
3. Run the _Connection Request Workflow Triggers_ job, and see that the Last Status Message reads `Future follow-up Workflow Triggered: 1 connection request records triggered 1 workflows.`
4. Go back to the Connection Request and see the request is now Active.
5. Give the Connection Request a new Future Follow-up Date (again, it can be the current day).
6. Run the _Connection Request Workflow Triggers_ job again, only this time the Last Status Message reads `Future follow-up Workflow Triggered: 1 connection request records triggered 0 workflows.`
7. Back on the Connection Request, you notice that it has been marked Active again.
8. Notice by looking at the Connection Request Workflows, that it was only triggered 1x, not 2x.

**Note: I also tested this over the span of several days, not just setting the date to the current day and then re-running the job like in the steps above.** 

![Screen Shot 2021-01-06 at 13 17 23](https://user-images.githubusercontent.com/23226974/103807630-b0315580-5024-11eb-8d09-2fdd12365fb4.png)

First run:
![Screen Shot 2021-01-06 at 13 16 47](https://user-images.githubusercontent.com/23226974/103807649-baebea80-5024-11eb-9612-b1d62c4ae3ae.png)

Second run:
![Screen Shot 2021-01-06 at 13 20 25](https://user-images.githubusercontent.com/23226974/103807664-c2ab8f00-5024-11eb-9102-43bc2f18eab6.png)

**Expected behavior:**

I would expect that I am able to set a new Future Follow-up date if needed because not enough time has passed to handle the Connection Request.

**Actual behavior:**

Future Follow-up date is allowed to be set a second, third, etc. time, however the Workflow will only launch the first time.

### Versions

* **Rock Version:** [11.3, 12.0, 13.0]
* **Client Culture Setting:** [en-US]

**Comment by asdf1nit** [comment]
I can confirm this. When you use the future follow up date reached trigger it will fire the workflow exactly once and no more. Changing the state to something else then back to future follow up with a new date does not trigger the workflow again.

For long running connections which might have a future followup date changed many times this would be helpful.
