### ISSUE TITLE
Attendance Analytics Chart and Attendee Counts Sometimes Inconsistent

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4541]
Submitted on behalf of [The Crossing Church](https://www.thecrossingchurch.com/)

### Description
When using attendance analytics, the Chart results are not always consistent with the list of attendees when using the same filter criteria. 

### Steps to Reproduce
_Add some test data_

1. Go to Attendance Analytics
1. Select the "Service Attendance" area
1. Click the "Check -in Detail" button (in top right area of screen)
1. Click the Weekend Service group
1. Add an occurrence for 11/09/2020 and add a few people as attending that occurrence

_Report on attendance_

1. Return to Attendance Analytics
1. Select the "Service Attendance" area
1. Select a data range of 11/09/2020 through 11/09/2020 (the data of occurrence that was just entered)
1. Select the "Weekend Service" group
1. Click "Update"

**Expected behavior:**

The Chart and the Attendees views both show same number of attendees (whatever number was entered when adding test data).

**Actual behavior:**

The Chart shows the correct number of people, but the Attendees view does not show any results.

Here is a video demonstrating the above steps:
https://www.dropbox.com/s/g59cn3o749eoqix/attendance analytics.mp4?dl=0

### Versions
* **Rock Version:** v11.2 and v13 (pre-alpha)
* **Client Culture Setting:** en-US

**Comment by nathanp** [comment]
We are having a similar/related issue. 

If we use the "Date Range" option, then no data is displayed. However, if we use the "Previous" or "Last" option, then the data is displayed.
