### ISSUE TITLE
Invalid URL to Person Profile on Step Participant List Block

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4543]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

The Step Participant List Block (`https://rockrmslatest.com/Steps/Type/1`) has a Person Icon on the right side of the row. When clicking on it, it is supposed to take you to `https://rockrmslatest.com/Person/4/Steps` and instead is an invalid URL `https://rockrmslatest.com/Person/###/Steps`. 

This seems to have appeared on either v11.3 or v12.0. On v11.2, it works correct.

### Steps to Reproduce

1. Go to `https://rockrmslatest.com/Steps/Type/1`
2. Ensure there is a person with a step in the list.
3. Attempt to click on the Person Icon in that row.
4. See error because of invalid URL.

![Screen Shot 2021-01-07 at 15 24 30](https://user-images.githubusercontent.com/23226974/103941863-7da75b80-50fd-11eb-98ba-c5a78a2f53d7.png)

**Expected behavior:**

Should be `https://rockrmslatest.com/Person/4/Steps` (or the Id of that person - 4 is Ted Decker)

**Actual behavior:**

Actually is `https://rockrmslatest.com/Person/###/Steps`

### Versions

* **Rock Version:** [v12.0, v13.0]
* **Client Culture Setting:** [en-US]

**Comment by mikedotmundy** [comment]
I believe this fix is included in the v12.1 release.

**Comment by nairdo** [comment]
Thanks Mike, you're right -- good catch.  I'll update the label.
![image](https://user-images.githubusercontent.com/383807/107236148-a5326200-69e2-11eb-9d8d-4c47c49c69d3.png)
