### ISSUE TITLE
Group Member Delete API Method doesn't check Group Security

### ISSUE THREAD

**Issue by chrisfunk-lpc** [SparkDevNetwork/Rock#4548]
### Description
When using the **delete** method for the /api/GroupMembers controller does not check group security.  If a user has Manage Members/Edit on a group/group type the API will return a 401 status.

### Steps to Reproduce
1. Authenticate to the api with a user who has staff member rights
1. Attempt to remove a group member from a group that the user has access to (on Demo Site use group member 92 https://rock.rocksolidchurchdemo.com/GroupMember/92), using the /api/GroupMembers controller.
1. API will return a 401 status.

**Expected behavior:**

If a user has edit or manage members access on a group they should be able to delete group members from a group

**Actual behavior:**

The user has to have have edit access at the GroupMembers entity level 

### Versions
* **Rock Version:** 1.11.2
* **Client Culture Setting:** en-us

**Comment by MikeDPeterson** [comment]
This was fixed with the same fix as #4549, with https://github.com/SparkDevNetwork/Rock/commit/6b68fdda029dba1ddab395ba5dfa456ae44294a9.
