### ISSUE TITLE
Group Placement - Unable to delete group member

### ISSUE THREAD

**Issue by chrisfunk-lpc** [SparkDevNetwork/Rock#4549]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Related to Issue #4548 (group placement utilizes the api controllers). Unable to remove a group member from a placement group if the current user doesn't have explicit Edit Access on the Group Member entity type

### Steps to Reproduce

1. Setup group placement on a Registration Template
2. Create an instance for template
3. Create a placement group on the registration instance.
4. Register a person for the instance
5. Add registrant to the placement group
6. Attempt to remove the registrant from the placement group.
7. Person may appear to have been removed
8. Refresh page and the person will be in the group.

**Expected behavior:**

If the current user has edit rights to the placement group they should be able to remove a person form the group.

**Actual behavior:**

Person is not removed from the group

### Versions

* **Rock Version:** 1.11.2
* **Client Culture Setting:** en-us

**Comment by TheCoreyHall** [comment]
BEMA has confirmed running into this on a client who is on 11.3 As Chris posted, adding edit rights to the Group Member Entity fixed it for now.

**Comment by cwomack** [comment]
Hello @chrisfunk-lpc, and thanks for your submission of this bug. I was able to reproduce this issue on v11.2 and verified that there was not a fix in place until v12.2 (to cover @TheCoreyHall's finding of the problem in v11.3). 

I'll close the issue out as being fixed in v12.2, but should you find any other issues with this please feel free to comment back! Thank you for helping to make Rock better.
