### ISSUE TITLE
EmailForm Block Throws Exception

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4550]
### Description

While testing our upgrade from 11.3 to v12.0 (in a test environment with a copy of production data) we discovered an issue when sending mail via the Email Form block. It works (the mail is delivered), but simultaneously throws an exception.

### Steps to Reproduce

First, it is highly unlikely that you will be able to dupe this... because I wasn't able to, either (more on that below)... but the steps are simple:
1. Put the Email Form block on a page
2. Configure valid TO and FROM addresses, and give it a subject
3. Reload the page and submit the form
4. Assuming you have an email transport and medium configured properly, you received the communication.
5. On OUR system, and only on v12, we also get a corresponding exception in the log that looks like this:

![image](https://user-images.githubusercontent.com/3903408/104783636-1700ee00-574c-11eb-8bea-93429c8a0df0.png)

**Expected behavior:**

Using this Block would not throw an exception.

**Actual behavior:**

It throws the above exception, but (so far) I've only been able to dupe this on our production database. Here's what I know from testing:

1. This only happens when we upgrade from 11.3 to v12 using our production db. All prior Rock versions going back to 5.0 didn't have this issue, either. 

2. We do NOT have any custom modifications on the EmailForm block and when I diff the EmailForm.ascx.cs file between my 11.3 and 12.0 instances they appear identical.

3. Interestingly, if I inactivate the Email Medium and/or Communication Transport, the email is not delivered (duh) but the exception is also NOT thrown.

4. I've eliminated this having anything to do with the email transport itself, as it happens when I use SendGrid HTTP, SendGrid SMTP, and plain old SMTP transports. 

So, we're in a weird spot where we're seeing a bizarre exception, but (so far) only on a copy of our production instance... so it's like there's something weird with our data, or a bug that's induced with our particular config/data setup.

### Versions

* **Rock Version:** 1.12.0.10

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1199617683865756">image.png</a>

**Comment by matthewbronkema** [comment]
@JimMichael, this issue appears to be coming from the Lava engine. Can you confirm that the Lava code in the email form block between your production and test environment is the same?

**Comment by JimMichael** [comment]
Matthew- I put a brand new EmailForm block in each instance, gave them the same to/from addresses and subject, and didn't touch the HTML/Lava in the block, and the production (11.3) instance delivers without the exception whereas the 12.0 instance delivers, but throws the exception (in the log, no UI indication of an exception.)

I even verified that another 11.3 test instance running a copy of prod data from November was working, then upgraded it to 12.0, and it now throws the same error.. so it doesn't appear to be an issue with different Lava.
