### ISSUE TITLE
Weekly Metrics Null Reference Exception

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4553]
Submitted on behalf of [Cornerstone Church](https://rock.cornerstoneaz.com/)

### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When using the Weekly Metrics entry block and configuring it to use a "Metric Date Determined By" value of "Day from Schedule" it will cause a null reference exception if any of the schedules in the selected category do not have a future date. 

### Steps to Reproduce

1. Go to General Settings > Schedules
2. Add a new "Special Services" category
3. Add a "Christmas Eve" schedule with one date of 12/24/2020
4. Go to the Weekly Metrics page
5. Configure the block to use a Schedule Category of "Special Services" (the new category) and a Metric Date Determined By value of "Day from Schedule". 
6. Save the changes

**Expected behavior:**

You are able to enter metric values for the Christmas Eve service

**Actual behavior:**

A Null reference error occurs due to the fact that the schedule does not have any future dates.

[Here's a video showing the steps also](https://www.dropbox.com/s/lxh1i7de0u1hobs/Weekly%20Metrics.mp4?dl=0)

### Versions

* **Rock Version:** 11.3 (and v13 pre-alpha)
* **Client Culture Setting:** en-US

**Comment by carriewhite** [comment]
I'd love to have a solution before Easter.  Anyone have ideas on how to work around this issue until it is resolved?
