### ISSUE TITLE
Gender cannot be Hidden on Workflow Form via Enable Person Entry

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4555]
### Description
On the `Enable Person Entry` option on the Workflow Form, Gender cannot be set to `Hide`. You can click save, but upon saving, it reverts back to `Required`.

### Steps to Reproduce
1. Create a Workflow Type with a Form.
1. Click `Enable Person Entry`.
1. Set Gender to `Hide`.
1. Save the Workflow Type, then go back into it and see it was changed to `Required`. 

![](https://user-images.githubusercontent.com/23226974/105112647-797e2500-5a91-11eb-9abd-23cb7791dafa.png)

**Expected behavior:**

I would expect you can hide the Gender option.

**Actual behavior:**

You cannot hide the Gender option.

### Versions
* **Rock Version:** [v12.0, v13.0]
* **Client Culture Setting:** [en-US]

**Comment by randyjreed** [comment]
Any workaround for this?

**Comment by mikedotmundy** [comment]
I see this was fixed in v12.4, however the red dot (denoting it is required) on the form still appears. I cannot test if it is actually required or not because it automatically defaults to _Unknown_, unless you are logged in and it defaults to your gender.

I am also not sure that it is desired behavior for the gender "Unknown" to be displayed on the front-facing webpage. It would be ideal if the form just knew it was unknown, unless a person selected their gender.

![Screen Shot 2021-06-16 at 11 56 04](https://user-images.githubusercontent.com/23226974/122253065-d7286900-ce99-11eb-8916-10f9dd070cdc.png)

**Comment by JimMichael** [comment]
Confirmed that the red dot now shows in 12.4 when Gender is set to Optional.

**Comment by cwomack** [comment]
I've also duplicated the remaining bug that the red dot for "required" still shows even when set to optional (however, Gender can be properly hidden when configured as such per original issue). 
![image](https://user-images.githubusercontent.com/67726635/125991993-d78898ed-9f4c-4ae8-9482-77d23192a5d1.png)
