### ISSUE TITLE
"Giving Amount" filter in Data View not returning deceased people with box checked.

### ISSUE THREAD

**Issue by megilee** [SparkDevNetwork/Rock#4557]
### Description
When running a data view using a Giving Amount filter (e.g. Giving amount total greater than or equal to $1.00. Date Range: Previous 4 Years), person records marked as deceased are not included even when the "Include Deceased" box is checked.

Issue seems to be related to the "Deceased" Inactive Reason. Additional issue brought up on Rocket Chat that may be related [here](https://chat.rockrms.com/channel/giving?msg=XT8srHa6L2j7rEih8).

### Steps to Reproduce
1. Go to Demo Site and search for person record "Bill Marble"
1. Go to Contributions tab and enter one-time contribution of $100.
1. Edit Bill Marble's person record and set his record status to Inactive/Deceased.
1. Create Data View that Applies to "Person".
1. Select Filter Type "Giving Amount" set to "Greater than or Equal to $1.00 in current year"
1. Be sure "Include Deceased" box is checked.
1. Click Save.

**Expected behavior:**

Deceased person records are included when "Include Deceased" box is checked. (In this case, Bill Marble)

**Actual behavior:**

Deceased person records are NOT included when "Include Deceased" box is checked. (In this case, no results)

Confirmed on Rocket Chat [here](https://chat.rockrms.com/channel/reporting?msg=iPB9Q89HErLFSaJC3).

_Note: If Bill Marble's person record is set back to "Active" he then shows up in the Data View. In addition, if any other "Inactive Reason" is used besides "Deceased", he shows up on the DV as expected._

### Versions
* **Rock Version:** 11.3
* **Client Culture Setting:** en-US

**Comment by pokes2k** [comment]
Have you heard whether this has been an issue with any recent versions? We're on 12.4, and I'm seeing the exact same behavior as @megilee originally reported. It still looks to be specifically when giving is added as a filter in the same DV with deceased, or even when combined with a separate DV that has giving. For example, we have a DV of current year giving. We had a different DV of married people and had "Include deceased" checked. The deceased individuals show up in the married DV, but when you add a Existing DV filter and add people from the giving DV, the deceased individuals are excluded from the list, even if they have current year giving in their profiles.
