### ISSUE TITLE
Apostrophe in Site Name Causes Javascript Error On /Person Pages

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/Rock#4562]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

If a Site's Name includes an apostrophe it will not be escaped when run through the javascript to load the "Last Visit On Site" badge. This causes and error in the javascript that prevent the badge from loading and may prevent other javascript from loading properly as well. (We had **Formerly known as Christ's Church of the Valley** in our site name which was causing the issue.)

![image](https://user-images.githubusercontent.com/605691/105558685-fabcfe00-5cc3-11eb-8bb3-9737ad912657.png)

### Steps to Reproduce

1. Edit a Site's Name to Include an Apostrophe
2. Load any /Person/{Id} page that includes a "Last Visit On Site" badge for the edited site.
3. See error in console log

**Expected behavior:**

Apostrophes in Site Name are escaped in ordered to avoid errors in javascript.

**Actual behavior:**

Apostrophes in Site Name cause an error resulting in the badge not loading. This error can also cause some other Javascript such as the Tag Editor and the Search Tool on the page to not load correctly. 

### Versions
https://rock.rocksolidchurchdemo.com/
* **Rock Version:** Rock McKinley 11.3 (1.11.3.1)
* **Client Culture Setting:** en-US

https://www.oneandall.church/
* **Rock Version:** Rock McKinley 12.0 (1.12.0.10)
* **Client Culture Setting:** en-US

**Comment by matthewbronkema** [comment]
Fixed with dbd1b4529e1b6df2f25f6df7757adb28caf44865
