### ISSUE TITLE
Connection Board modal doesn't render markdown in comments field

### ISSUE THREAD

**Issue by MichaelAllen** [SparkDevNetwork/Rock#4563]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

The "Connection Request Detail" block renders markdown in the "comments" field, but the modal view on the "Connection Request Board" block shows that field as plain text. We use markdown in that field to add links to other parts of Rock.

### Steps to Reproduce

1. Create a connection request with this markdown in the comments field: `[Link Test](https://google.com)`
2. View the request on the Connection Request Detail page (https://rock.rocksolidchurchdemo.com/page/408?ConnectionRequestId=1) and notice it renders as a clickable link.
3. View the same request by opening it in the connection board block and notice the markdown is not rendered.

**Expected behavior:**

Markdown in the comments should be rendered correctly.
<img width="500" src="https://user-images.githubusercontent.com/282879/105637216-485b7700-5e3a-11eb-9024-770f8f0072c0.png">
^ Connection Detail Page

**Actual behavior:**

Markdown in the comments is rendered as plain text.
<img width="500" src="https://user-images.githubusercontent.com/282879/105637224-50b3b200-5e3a-11eb-9f87-a39dc06a594d.png">
^ Connection Board Modal

### Versions

* **Rock Version:** v1.12.0.10
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/6a4f6e9da8fe0ed4751fdaeca27d9afcf9a3510e.
