### ISSUE TITLE
On Mobile pages, blocks dragged from one zone to another do not save their location.

### ISSUE THREAD

**Issue by MicahO** [SparkDevNetwork/Rock#4566]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Mobile pages not available on the demo site, so cannot reproduce there.

### Steps to Reproduce

1. Go to 'Home > CMS Configuration > Mobile Applications > Application > Page
2. Choose a layout with multiple zones ("Header" and "Main," for example.
3. Add a block to Header zone. Back out of page and return, confirm block is still in Header zone.
4. Drag block from Header to Main. Back out of page and return, see that block has moved back to Header zone.

See YouTube video here:
https://www.youtube.com/watch?v=krzccknz_ok

**Expected behavior:**

If a block can be dragged to a new zone, it should stay in that zone. If the intent is for blocks not to be dragged from zone to zone, the UI should not support that behavior.

**Actual behavior:**

When a block is dragged from one zone to another, it will always return to the original zone after the page is reloaded.

### Versions

Rock Version: Rock McKinley 12.0 (1.12.0.10)
Client Culture Setting: en-US

**Comment by nairdo** [comment]
It is a mostly bug.  The original intent was to only be able to drag blocks from the pallet to a zone — however it appears that the drag widget on the block (once it's in a zone) is only supposed to be used for re-ordering the block in _that_ zone.

**Comment by ethan-sparkdevnetwork** [comment]
Thank you @courtneycooksey!
