### ISSUE TITLE
v12 - Check-in Manager no longer allows you to toggle rooms open and closed from the Live Metrics view

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4569]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

We recently upgraded to v12 and noticed that in the Check-in Manager app, we are no longer able to easily open/close rooms from the Live Metrics view. In v11 and earlier, there was a toggle by each room that allowed you to open/close it without having to navigate to a different page. I'm really not sure if this was designed this way intentionally, but removing that toggle has caused us to go from 1-click access to open/close rooms to roughly 4-click access to open/close rooms one at a time.

### Steps to Reproduce

1. Go to https://prealpha.rocksolidchurchdemo.com/CheckinManager
2. Set the Campus, then click the three lines in the top left to open the menu
3. Switch to the Live Metrics view

**Expected behavior:**

With a list of locations in the Live Metrics view, I'd expect the status listed on the right-hand side of the row (indicating whether it's currently open or closed) would be a toggle to allow you to open/close that room from this view.

**Actual behavior:**

If you click the status in the row, it takes you to the roster but doesn't allow you to open/close the room from this view. In order to open/close the room, I have to go directly to the room in Room Manager and then click Room Settings to toggle the status of the room.

### Versions

* **Rock Version:** [12.0]
* **Client Culture Setting:** [en-us]

**Comment by JimMichael** [comment]
We recently noticed this change as well and it will be a problem for our Kids staff/volunteers. Adding it to the Room Manager is a great enhancement, but taking it away from the Live view is a miss (for us.)

**Comment by calvmann** [comment]
We have not upgraded but noticed this in the test database. It would not go over well with our Kids staff.
