### ISSUE TITLE
Universal Search page route from SmartSearch causes subsequent We Can't Find That Page errors

### ISSUE THREAD

**Issue by sichiriu** [SparkDevNetwork/Rock#4571]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

By default, SmartSearch provides a page route of `universalsearch/{0}?SmartSearch=true` to the Universal Search page. Subsequent searches in the Universal Search block that include spaces (e.g., 'Alisha Marble') create page routes with a '+' character (e.g., `/universalsearch/Alisha+Marble?groupTypeName=`), resulting in a We Can't Find That Page error.

### Steps to Reproduce

1. Enter a search via the Universal Search option in the Smart Search box
2. Enter a search term including one or more spaces in the Universal Search block on the Universal Search page
3. Observe error

**Expected behavior:**

There should be consistency between the handling of spaces via the Smart Search box and the Universal Search block. It appears that Smart Search encodes spaces as '%20' whereas Universal Search encodes them as '+'. I resolved the issue in our system by changing the Result URL for Universal Search in Search Services to `universalsearch?Q={0}&SmartSearch=true`

**Actual behavior:**

An error occurs.

### Versions

* **Rock Version:** Rock McKinley 11.3 (1.11.3.1)
* **Client Culture Setting:** en-US

**Comment by cwomack** [comment]
@sichiriu I was able to reproduce the same outcome of seeing the "We Can't Find That Page" error after setting up Universal Search on my v11.3 when I didn't have **Indexable Entities** set up.  Can you check under **Admin Tools > General Settings > Universal Search Control Panel** and see what you have marked for entities that can be indexed?  Here's a link to the [Documentation on Universal Search](https://community.rockrms.com/Rock/BookContent/32) as an additional resource.

Upon setting these up, my Universal Search seemed to perform as expected.  If you still encounter errors, would you mind taking some screenshots of the configuration as well in a reply? Thanks!

**Comment by sichiriu** [comment]
@cwomack - Here's what I have configured for indexable entities:

<img width="1226" alt="Screen Shot 2021-05-21 at 9 37 53 AM" src="https://user-images.githubusercontent.com/10267139/119170543-3b314c00-ba18-11eb-860f-d8bd5ccbb874.png">

I've since upgraded to 12.3 and am no longer getting the "We Can't Find That Page" error, but now I have a different issue with Universal Search. ¯\_(ツ)_/¯ I'll do some digging in Rocket Chat and may open a new issue about that one, if needed.

**Comment by cwomack** [comment]
@sichiriu Glad to hear the error page isn't happening anymore! If you don't get a resolution for the other issue on the Universal Search you're still experiencing after some Rocket Chat research,  by all means open up a new GH Issue and I'll take a look.  

I'll close this issue out and keep an eye out for any new ones. Thanks for helping to make Rock better!
