### ISSUE TITLE
OpenID Connect Integration does not redirect on New Registration

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4573]
### Description

I could only test this with the ChOP Integration via OpenID Connect.

When navigating from ChOP to Rock, _logging in_, and then back to ChOP, the integration works seamlessly.
When navigating from ChOP to Rock, _creating an account_, and then back to ChOP, you are not redirected back to ChOP. An account is successfully created in Rock, but that account is not sent to ChOP and created there.

I reached out to ChOP first and they said the issue is not on their end and it is something with Rock. They were also able to confirm that when creating an account in Rock via Facebook it will work, but when trying to do it via email, it will not. 

Another church on Rock said in Rocket Chat they are experiencing the same thing. https://chat.rockrms.com/channel/troubleshooting?msg=wGQxBCHTePu8sZhJS

I have experienced each of the following 3 things happening after clicking "Yes" on the "Give Permission" page (`/page/103`):

1. The page acts like it wants to load, but times out and displays a 504 Gateway timeout page.
2. Receive a generic "site cannot be reached" page. 
3. Receive this error:

<img width="1680" alt="Screen Shot 2021-01-29 at 17 59 56" src="https://user-images.githubusercontent.com/23226974/106338527-ff545a00-6261-11eb-8777-b81e2276648a.png">

### Steps to Reproduce

1. Set up OpenID Connect integration with ChOP.
2. In ChOP, click "Login" to navigate from ChOP to Rock to login. 
3. Instead of logging in, click "Register". 
4. Create an account with Rock.
5. End up at "Give Permission" page. (`/page/103`)
6. Click "Yes".
7. See that you are not redirected back to ChOP. 

**Expected behavior:**

I would expect to be redirected back to ChOP.

**Actual behavior:**

You are not redirected to ChOP.

### Versions

* **Rock Version:** [v12.0]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
@mikedotmundy Can you re-try your tests.  We've connected with the ChOP OpenID integration team and discovered a few issues.  The first one was a bit obscure but they've corrected it (it had to do with records that had no photos).  

The second issue is not really correctable, but they are going to adjust the error message to make it clearer.  It involved a situation where two separate login attempts are being made for two different accounts (in Rock) -- where they have the same email address (in Rock).  Since email addresses must be unique in ChOP but not in Rock, it is a situation which you'll need to be aware of.  The plugin documentation is being updated to note this.

**Comment by mikedotmundy** [comment]
Thanks @nairdo! I just retried it again with a completely new name and email that does not exist in my Rock instance. I was able to successfully create the account in Rock, but was then given the same exact error message as in the screenshot above. _(The change you wanted was rejected)._

**Comment by nairdo** [comment]
@mikedotmundy I'm hearing a bit of conflicting news on this issue.  Can you confirm that no one _else_ in the Church Online Platform has that email address you tried during your test two days ago?

**Comment by mikedotmundy** [comment]
@nairdo I have been working with @matthewbronkema on this - I found out that I _had_ used the email in the past when testing. I then deleted the user/email from ChOP so I had forgotten that I had ever used that email. Matt told me he is contacting ChOP to find out if they actually "soft-delete" people - where they can see the profile, but I can not. Sorry for the confusion on this.

**Comment by matthewbronkema** [comment]
@mikedotmundy I did contact ChOP about the email issue. It doesn't sound like they are doing soft deletes, but they didn't respond to my question about why you couldn't see that email in your ChOP user list. I would recommend you connect ChOP support directly to figure out why the user with that email address is not showing up in your ChOP user list.

**Comment by mikedotmundy** [comment]
Thanks @matthewbronkema
