### ISSUE TITLE
Login issue using an iFrame

### ISSUE THREAD

**Issue by tstephens17** [SparkDevNetwork/Rock#4579]
### Prerequisites
* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

While trying to use the Attendance Entry feature in a Church Online Platform moment (as Rock suggests doing in the documentation), it will not login a user.

I also tested this on a webpage inside of an iFrame and got the same results.

### Steps to Reproduce

1. Create a moment in ChOP and select iFrame.
2. Click the login button
3. Login
4. Notice, you are redirected back to the main unauthenticated Attendance Entry page with the login button.

**Expected behavior:** 

Once you login, you are shown members of your family to select for attendance entry.

**Actual behavior:** 

Endless loop of login. If you give up and try to just do attendance, you get an error at the end. 

Nullable object must have a value.

 at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at RockWeb.Blocks.CheckIn.AttendanceSelfEntry.GetLoggedInPerson(RockContext rockContext)
   at RockWeb.Blocks.CheckIn.AttendanceSelfEntry.ShowSuccess()
   at RockWeb.Blocks.CheckIn.AttendanceSelfEntry.btnCheckIn_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

### Versions

* **Rock Version:** [Rock McKinley 11.2 (1.11.2.1)]  
* **Client Culture Setting:** [en-US]

**Comment by matthewbronkema** [comment]
For the iframe to work you will need to add the CHOP domain to the site's "Allowed Frame Domain(s)" setting and set the "Same Site Cookie Setting" global attribute to None. This change will not work for those users who have their browsers setup to block third party cookies.
