### ISSUE TITLE
Org Address Changes to Location Name If Location Has Matching Address

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4580]
### Description

This issue is kind of convoluted, but I'll do my best to describe the problem. Somewhere around v11, we noticed that our _Organization Address_ Global Attribute had changed from "114 N Eatherton..." to "Chesterfield" (the name of our main campus) without us "doing anything" to it. Apparently it changed during an upgrade (perhaps from 10.4 to v11, or one of the v11 dot releases).

At the time, with some "fiddling" (deleting/re-adding) we were able to get the Org Address to show as the _address_ again, and we moved on. Fast forward to today and I'm testing v12.1, and AGAIN I noticed in my 12.1 copy of prod instance, the Organization Address is back to the CAMPUS NAME.

Something appears to be buggy in the area of Org Address (or attributes in general) when a _Named Location_ has the same address you're trying to use for the Org Address attribute. It "short circuits" and instead shows the Location Name instead. I was able to dupe this on prealpha.

### Steps to Reproduce

1. Go to https://prealpha.rocksolidchurchdemo.com/page/51 and observe the address is  showing as "3120 W Cholla St..." as this is the default address for the attribute. 

2. Click on the Organization Address row to edit its value (not the pencil)

3. Click the x next to the address to delete it, then click the drop-down to add a new address, for example
![image](https://user-images.githubusercontent.com/3903408/106924477-b888b900-66d4-11eb-88ac-517d4f49fa2f.png)

4. Save the new address and observe it now shows the new address as the Organization Address value.

5. Go to Admin | General | Named Locations and edit the _Main Campus_ location.

6. Enter the _exact same_ address for this campus that you entered into the Org Address (do not click verify address or it won't match the org address you entered precisely), for example
![image](https://user-images.githubusercontent.com/3903408/106924795-10bfbb00-66d5-11eb-968e-b3c08aa66843.png)

7. Go back to Admin | General | Global Attributes and observe the Organization Address. It MAY show the address or MAY show the campus name. If it's showing the address as expected, click it to edit the value, and click the x next to the address to delete it, then save.

8. That should make the address go back to the default of 3120 W Cholla... NOW edit the Org Address attribute AGAIN and  enter your new address, for example
![image](https://user-images.githubusercontent.com/3903408/106926246-85dfc000-66d6-11eb-8a33-d6d00524da63.png)

9. Save, and observe that the Org Address value now shows as _Main Campus_
![image](https://user-images.githubusercontent.com/3903408/106926350-9f810780-66d6-11eb-98f5-df311e19060e.png)
 
[insert twilight zone theme ]

**Expected behavior:**

Address entered as Org Address would not change to the campus name just because that Named Location has the same address.

**Actual behavior:**

Weird things happen, and your Org address changes to the Campus name. I consider this a high priority bug because when the Org address changes to the Campus Name, EVERYWHERE that global attribute is referenced on the site will show a campus instead of mailing address (for example, the online contribution statement, public website footer, etc)

I am wondering if this fix is v11.3 is the root of the problem https://github.com/SparkDevNetwork/Rock/issues/4397

### Versions

* **Rock Version:** Not sure when it started, but definitely still an issue as of prealpha.

**Comment by mikedotmundy** [comment]
I can confirm that this change happened for us when going from v11.2 to v11.3. I first saw this issue because there are places we display our Organization Address with Lava (`{{ 'Global' | Attribute:'OrganizationAddress' }}`) and it would display our main campus name instead.

**Comment by JimMichael** [comment]
Not that this changes the buggy behavior in any way, but I did find the explanation for why my 12.1 test instance seemed to have re-introduced the problem...
![image](https://user-images.githubusercontent.com/3903408/106944993-e679f780-66ec-11eb-845f-baaafe03e099.png)
It was simply a matter of me using a db copy from November that was a copy of production at 11.3... so the bug was already there, I just hadn't noticed it in my test environment until I started down the 12.1 alpha checklist.

**Comment by JimMichael** [comment]
Do we really have to wait through another patch cycle to get this fix?

**Comment by nairdo** [comment]
Hi Jim, I know we're getting late in the 12.1 alpha -- but I'll revaluate the risk on that https://github.com/SparkDevNetwork/Rock/commit/e2970bd68eefa2a182728d0aaa2d2daee19e8f3d change to see if we can still put it into 12.1.

**Comment by treusch** [comment]
For those not ready to upgrade to 12.1 yet, I was able to get the Global Attribute to accept the physical address I wanted for our Organization by putting a single comma in the Address 2 line. For whatever reason, it accepted and held the address, but didn't print the comma when I use the lava to get the address. A little hokey, I know, but it worked for us and now that it is in there, we won't be changing it any time soon. Hope that helps.
