### ISSUE TITLE
12.1 Alpha - Add New Family Block No Longer Defaults Country/State For Addresses

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4581]
### Description

This may be an issue in 12.0, too, but I'm entering it as a 12.1 bug in the hope it can be fixed before release. The issue is that prior to v12.1 (or maybe 12.0), when we used People  | New Family, the Address portion defaulted to United States as the Country and Missouri as the State, respectively.
![image](https://user-images.githubusercontent.com/3903408/106929666-45824100-66da-11eb-806f-b35174b90b09.png)

As of 12.1, neither the country or state are defaulted (though the state DOES auto-select when I choose United States from the Country drop-down
![image](https://user-images.githubusercontent.com/3903408/106929792-69de1d80-66da-11eb-9e9e-1d05242f78f9.png)

### Steps to Reproduce

1. Add a new family
2. Observe that the country and state are not defaulted and you have to choose them (well, you have to choose the country now, and the state then defaults)

**Expected behavior:**

Country and state would default to appropriate values for the organization. I'm not even sure WHERE these come from in 11.3 and prior (perhaps the org address?) but they auto-default all the same. Or was this an intentional change in behavior in v12?

**Actual behavior:**

In 12.1 (and possibly 12.0) the country and state do not default, which adds to extra clicks and steps when adding 90% of new people for the org.

### Versions

* **Rock Version:** 12.1 (12.0?)

**Comment by mikedotmundy** [comment]
I can confirm this issue in both my v12.0 and v12.1 instance.
