### ISSUE TITLE
12.1 ALPHA - Blocks Added/Deleted on CMS Config | Pages Don't Appear Until Refreshed.

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4584]
### Description

While working through the process.st list for 12.1 alpha, I noticed that when I add a block to a page on Admin | CMS Config | Pages, the new block does not "appear" until I manually refresh the page. 

### Steps to Reproduce

1. Go to Admin | CMS Config | Pages
2. Pick a page and add a HTML block to a zone, and save
3. Observe that the new block is not showing in the Blocks From Page area.
4. Refresh the page, and the block shows up.

**Expected behavior:**

Blocks added/deleted via CMS Config | Pages would show up without manually refreshing, as 12.0 and prior do.

**Actual behavior:**

You have to manually refresh when adding or deleting a block to see the change. I also verified this on prealpha.

### Versions

* **Rock Version:** 12.1 alpha 1

**Comment by JimMichael** [comment]
After further testing, this doesn't seem to be isolated to the EmailForm block. We're seeing some simple workflows that use the Send Email action fail as well. When we use SendGrid HTTP, the emails never arrive. When we use SendGrid SMTP or SMTP, they arrive as expected.

The curious thing is that not ALL workflows that send email are failing... ones that notify on new Connection Requests are failing, but ones activated via the Actions menu are working.

**Comment by crayzd92** [comment]
This was fixed in v12.5 via 5adc3db5f085eea77290da61b4b6394c124f3506
