### ISSUE TITLE
Person Properties in wrong location on MyAccount page

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4585]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

On the `/MyAccount` page in v12.0+, there are a couple minor issues with the locations of some person properties.

1. For the spouse, the Anniversary information is listed under "Contact Info". Should be to the left under their Gender.
2. For a child, their relationship status is listed under "Contact Info". Should be to the left under their Gender.
3. For a child, if they don't have any Contact Info, it may be better to just have "Contact Info" not visible, similar to how Person Attributes are not visible when there is no value for them.

<img width="1680" alt="Screen Shot 2021-02-05 at 21 33 53" src="https://user-images.githubusercontent.com/23226974/107106684-b6b91580-67fa-11eb-9698-f6e1ff5f4dbd.png">

### Versions

* **Rock Version:** [v12.0, v12.1]
* **Client Culture Setting:** [en-US]

**Comment by mikedotmundy** [comment]
In the `PublicProfile.lava` file, moving lines 252 - 265 up to line 248 fixes this issue.

**Comment by MikeDPeterson** [comment]
Thanks @mikedotmundy Your fix was exactly what was needed!
