### ISSUE TITLE
Registration does not update Campus

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4587]
Submitted on behalf of [Grace Church](https://gracechurchsc.org/)

### Description
When an existing person registers for an event that has a "Campus" person field, and they enter a new Campus value (different than their existing campus), the person's campus is not updated on their family's record. This seems like it should behave similar to the "Address" person fields in registrations. If a person updates an address during a registration, that value is updated on their family record.

### Steps to Reproduce
1. Create a new registration template that includes the following fields: First Name, Last Name, Email, Address, Campus
1. Create a valid instance for the template
1. Using an existing person's name and email, register for the event, but use a different address and campus than their existing values.

**Expected behavior:**

The person's family record is updated with the new address and campus values.

**Actual behavior:**

The campus on the person's family is not updated, but the address is.

### Versions
* **Rock Version:** v12.0
* **Client Culture Setting:** en-US

**Comment by milescarmany** [comment]
According to the Model Map, Campus can also be set on the individual person. It might be worth checking to see if it is updating individuals instead of families.

**Comment by GarriDarter** [comment]
I am experiencing the same issue

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in commit 15caaaa8

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in Obsidian and Webforms versions of the RegistrationEntry block.

Obsidian: https://github.com/sparkdevnetwork/rock/commit/2dd509f6b3f43ce6481b5643228cdb3ece2cb405
WebForms: https://github.com/sparkdevnetwork/rock/commit/15caaaa88621dde22abdcc4e35c76f3b3af3161b
