### ISSUE TITLE
Recipient Preference setting on Communication Entry Wizard Block displays Error Message

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4588]
### Description
If you edit the block properties on the `Communication Entry Wizard` block, you can set the Communication Types to `Recipient Preference`. When you do this however, you will get an error message like the screenshot below.

In my testing, I did have a valid Email Transport (Mailgun SMTP) and Twilio SMS both enabled and working. 

There is no error when leaving all the Communication Type options unchecked, when selecting `Recipient Preference` along with another one of the options, or when selecting one or multiple other options.

![Screen Shot 2021-02-09 at 08 12 59](https://user-images.githubusercontent.com/23226974/107368638-c95b7500-6aae-11eb-996b-2bd497eb8264.png)

![Screen Shot 2021-02-09 at 08 13 12](https://user-images.githubusercontent.com/23226974/107368640-cb253880-6aae-11eb-92b8-8bdc7d0a7b0d.png)

### Steps to Reproduce
1. Go to the New Communication (`/Communication`) page.
1. Edit the block properties on the Communication Entry Wizard block.
1. Set Communication Types to `Recipient Preference` and Save.
1. Select either a Communication List _or_ select people from the manual list, then click Next.
1. See error.

**Expected behavior:**

I would expect no error, and that it would honor recipient preference.

**Actual behavior:**

Error message displayed and cannot proceed further with communication.

### Versions
* **Rock Version:** [v12.0, v12.1]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Thanks @mikedotmundy !  We believe is a bit more of a 'feature' request than a bug.  Currently, that block setting represents the items that you want the individual user to be able to choose from on-screen when they are picking the communication options.  So, to that end, choosing `Recipient Preference` really only makes sense if you are going to choose at least two or more other options.

Regardless, we can see how that setting/message is a little awkward, so if you wanted to request that as a change, we'd kindly ask you to pop over to the Ideas board and throw it in as a new idea: http://community.rockrms.com/Ideas

Thanks again Mike -- for all your help.

**Comment by nairdo** [comment]
Hey @mikedotmundy -- small change of plans.  We're going to change the block's behavior so that if `Recipient Preference` is selected, then any/all **active** mediums/transports will be shown during the creation of the communication.  We're planning to get this into the v12.3 release.

**Comment by mikedotmundy** [comment]
Thanks @nairdo!
