### ISSUE TITLE
Registration deletes the previously-existing Email address

### ISSUE THREAD

**Issue by navibean** [SparkDevNetwork/Rock#4591]
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

During Event Registration, if the registrant is not logged in, the Registration process deletes the person-record's previously existing Email address.  

### Steps to Reproduce

1. From the website + URL slug, go to the event's registration.
       Note:  Do not log into Rock.
       Note:  Our registration required:  first name, last name, phone number.
2. For a person who is already existing in the Rock database, provide that person's first name, last name, phone number, as a registrar & registrant.  

**Expected behavior:**

Person would become registered for the event.  No pre-existing information in the Person record would be over-written or deleted. 

**Actual behavior:**

In the Person record, the pre-existing Email address for the person is deleted. 

### Versions

* **Rock Version:** [Rock McKinley 11.3]
* **Client Culture Setting:** [en-US]

**Comment by azmichaelm** [comment]
Is there any way to fix the problem NOW when using 11.3. We have 100's of registrations which means 100's are having their emails deleted from their profiles.

**Comment by JimMichael** [comment]
The quickest workaround would be to put the registrations behind authentication (make people login). Then the issue does not occur. 

You could also consider donating to Spark at the recommended level for your org, so you get Early Access releases.

**Comment by azmichaelm** [comment]
Yea, I just checked and was told we did make our donation but I don't see where 12.2 is even out to early access.

**Comment by JimMichael** [comment]
Yes, sorry... I deleted my comment because I didn't read close enough to realize the fix was in 12.*2*. I just assumed you were running into the issue of not being able to upgrade to 12.x. My apologies. 

So, the only workaround I know of is to put the registration behind authentication.

**Comment by azmichaelm** [comment]
OK, you would think that "forced" authentication would be something we could have been told about. I didn't see anything in the updates that suggested this was coming. Can't believe there is no other option as we can't be the only people on version 11.3.

**Comment by JimMichael** [comment]
I'm not sure what you mean by "forced" authentication. That is a feature in an event registration where it asks a person to login prior to registering. When you do that, email addresses don't get deleted. The bug is only there when you let people register without logging in. If you want to continue chatting, you can find me in Rocket.Chat. Github is not the place to have back/forth discussions.
