### ISSUE TITLE
Benevolence Request started from Person Profile throws incorrect Incomplete Address Error

### ISSUE THREAD

**Issue by jennifertroeger** [SparkDevNetwork/Rock#4592]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When "Support International Addresses" is set to YES and you've verified that a country is showing on a person's profile, you will get an error of `Incomplete Address. The following fields are required: Country.` when you try to create a Benevolence Request originating from the profile. If you navigate to Benevolence (Finance > Benevolence > New Benevolence Request > select person from the person picker) you will NOT get the error, and the Request is correctly created.
![Screen Shot 2021-02-10 at 1 53 25 PM](https://user-images.githubusercontent.com/36419045/107557576-cd1ef280-6ba7-11eb-88c6-f7ac4c5531c4.png)

### Steps to Reproduce

1. Make sure "Support International Addresses" is set to Y under Admin Tools > General Settings > Global Attributes > Support International Addresses
2. Go to a person's profile
3. Click Edit by the address to verify that you see a country and complete address listed in the Country field
4. Exit out of that and Click on the Benevolence Tab
5. Click the "+" sign to create a new Benevolence Request
6. Note that the person's contact information is auto-filled
7. Enter required information (Request Status and Description of Request)
8. Click "Save"
9. See error at the top of the page

**Expected behavior:**

The expected behavior is that the BR will be created.

**Actual behavior:**

The actual behavior is that the BR does not save. 
If you navigate to Finance > Benevolence > and follow steps 5-8 you will see that the request saves as it should.

### Versions

* **Rock Version:** Rock McKinley 12.0 (1.12.0.10)
* **Client Culture Setting:**  en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1200097386303563">image.png</a>

**Comment by WomackCodes** [comment]
Thanks for submitting this issue to us @jennifertroeger Jennifer.  Are you able to confirm if there are any addresses in your database that have a value of Country value "NULL"? You can try running this SQL script to verify: 
```
SELECT
    COUNT(*)
FROM
    [Location]
WHERE [Country] IS NULL
AND [State] IS NOT NULL
```

We believe that's possibly part of the problem, but we're still looking at how we can prevent that error from occurring in that situation.

**Comment by jennifertroeger** [comment]
![Screen Shot 2021-02-15 at 10 57 58 AM](https://user-images.githubusercontent.com/36419045/107968725-b64c1780-6f7c-11eb-9937-90a49a7a6917.png)

Yep, we have a default of United States set for all profiles. The query returned 0 results. Noteworthy – my original screen shot was taken from the demo site, just to show that it was not just occurring in my own environment. Creating the request for the same person produced two different results (one successful, one not), depending on where the request was initiated.

**Comment by nairdo** [comment]
Hi @jennifertroeger when you run that SQL, be sure to change the 'Selection Query' to 'Yes'.  That will report back how many rows it finds. (When set to "No", it expects the query is changing/updating rows -- so it will execute the query and tell you how many rows were changed.)

**Comment by jennifertroeger** [comment]
![Screen Shot 2021-02-15 at 1 21 20 PM](https://user-images.githubusercontent.com/36419045/107981768-bc4bf380-6f90-11eb-8c30-b9ea8497d93a.png)

Hi @nairdo, here you go.

**Comment by cwomack** [comment]
Hey Jennifer (@jennifertroeger),

This was accidently closed out.  We're still looking into it and if there's any other screenshots or issues you have with it, keep sending them our way.

**Comment by cwomack** [comment]
This was reproduced on v12.0 after attempting to **_edit_** an **_existing_** Benevolence Request once the **Support International Addresses** Global Attribute was changed to "Y".  Creating a new Benevolence Request was not an issue.
