### ISSUE TITLE
Giving Analytics Block Does Not Include End Date when considering "and did not give between" range

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/Rock#4593]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

It appears that the "and did not give between" End Date is not being rolled forward to include the full end date in the calculation. In the screenshot below you can see that a giver is being included in the list even though they gave on the end date of the "and did not give between" range.

[Link To Report Below On RockSolidChurchDemo.com](https://rock.rocksolidchurchdemo.com/page/398?SlidingDateRange=Current%7c%7cYear%7c%7c&GroupBy=&AmountRange=%2c&TransactionTypeIds=&CurrencyTypeIds=&SourceIds=&AccountIds=&DataView=0&DataViewAction=&GraphBy=&ShowBy=1&ViewBy=0&GiversFilterByType=2&GiversFilterByPattern=1%7cTrue%7c2021-02-01T00%3a00%3a00.0000000%2c2021-02-10T00%3a00%3a00.0000000)

![image](https://user-images.githubusercontent.com/605691/107572209-cfca1980-6ba0-11eb-9629-2c804e67b30c.png)

### Steps to Reproduce

1. Go to 'Giving Analytics Page'
2. Select the Pattern filter and enter an "and did not give between range"
3. See that givers who gave on the End Date of the range are included on the list

**Expected behavior:**

Givers who give on the End Date of the "and did not give between" range ARE NOT included in the list of givers in the report.

**Actual behavior:**

Givers who give on the End Date of the "and did not give between" range ARE included in the list of givers in the report.

### Versions

* **Rock Version:** Rock McKinley 12.0 (1.12.0.10)
* **Client Culture Setting:** en-US

**Comment by jsw-austin** [comment]
I might be wrong, but it looks to me like it means between in the literal sense (not including on 2/1 or on 2/10, but actually between those dates - only 2/2-2/9)  Seems a simple fix is to bump the date up to 2/11.

**Comment by bscottdavis** [comment]
> I might be wrong, but it looks to me like it means between in the literal sense (not including on 2/1 or on 2/10, but actually between those dates - only 2/2-2/9) Seems a simple fix is to bump the date up to 2/11.

Thanks @jsw-austin! For our current work around we are choosing the date of 2/11/2021 for the end date as you suggested, it just seemed counterintuitive for the average user and did not align with how other date-pickers functioned on the page. (The main date range picker in the upper left of the page is inclusive of both the start and end dates, not just the start date.)

From what I can see in the code it looks like it is using the formula ["Greater Than or Equal to Midnight of StartDate and Less Than Midnight of EndDate"](https://github.com/SparkDevNetwork/Rock/blob/e0272c8d9f7fcdbb49bcf1f19f6f5831130c1a87/RockWeb/Blocks/Finance/GivingAnalytics.ascx.cs#L1639-L1656). So in this case it is excluding those who gave 2/1/2021 12:00 AM - 2/09/2021 11:59 PM. There may be some other manipulations of the end date going on, but this is what I am guessing from the code I understand.
