### ISSUE TITLE
Connection Request Grid Does not include "Show In Grid" Attributes

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4594]
Submitted on behalf of [ITOWN Church](https://itownchurch.com/)

### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When you add Connection Request attributes to either the Connection Type or Connection Opportunity, there is a "Show In Grid" option. However selecting this does not result in the attribute being displayed in the Connection Request grid (list).

### Steps to Reproduce

1. Go to Rock demo or alpha site
2. Go to People > Connections
3. Click the Gear icon to edit the connection type/opportunities
4. Click the "Involvement" connection type
5. Edit the "Involvement" connection type
6. In the "Connection Request Attributes" section add a new attribute and select the "Show in Grid" checkbox
7. Save the changes
3. Navigate back to People > Connections and select one of the Involvement opportunity types

**Expected behavior:**

The list of connection request would have a column for the attribute that was just created

**Actual behavior:**

The list does not include the attribute

### Versions

* **Rock Version:** 13.0 (alpha)
* **Client Culture Setting:** en-US

**Comment by karenn-ccbc** [comment]
This was also posted to Ideas https://community.rockrms.com/ideas/1493/connections-grid-add-columns
