### ISSUE TITLE
Removing Home Phone from Connection Signup causes Formatting Issue

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4597]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

For the Connection Opportunity Signup block (used on the external site), if you edit the block settings and change `Display Home Phone` to "No", the formatting of the Email and Mobile phone now look strange on the page. The home phone field does disappear, however the mobile phone field does not move left like it should. 

Note that this does look correct on mobile, just not on a computer screen.

<img width="1679" alt="Screen Shot 2021-02-14 at 16 49 40" src="https://user-images.githubusercontent.com/23226974/107890200-8c93e180-6ee5-11eb-905b-3dbdd0a8f31c.png">

### Steps to Reproduce

1. Go to `https://rock.rocksolidchurchdemo.com/page/417?OpportunityId=3`
2. Edit the Connection Opportunity Signup block settings and change `Display Home Phone` to "No". Click Save.
3. See mobile phone is alone, all by itself. 

**Expected behavior:**

I would expect that the Mobile Phone field would either move left or jump up next to the email field. 

**Actual behavior:**

Home phone field disappears, and mobile phone field stays where it was.

### Versions

* **Rock Version:** [v12.0, v12.1]
* **Client Culture Setting:** [en-US]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1199977536747499">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1199977536747504">image.png</a>

**Comment by milescarmany** [comment]
What appears to be happening is, the Email field is in a `col-md-6` with an empty `mol-md-6` next to it. Removing the Home Phone does the same to Mobile phone and the two rows do not "collapse" to remove the empty space. On Mobile, the columns are all stacked, so the rows don't have a visible effect.

I'd be curious if there is functionality elsewhere that handles adjusting the HTML more intelligently that could be applied here.
