### ISSUE TITLE
Sending Communication to Recipient Preference Breaks "Send Test" Functionality

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#4601]
### Description
When sending communications, if you choose to send to Recipient Preference, currently an error is thrown when you attempt to send a test (both Email and SMS). We think the test email does actually send despite the error, but the SMS test does not appear to be sent.

![image](https://user-images.githubusercontent.com/2465823/108214147-d35c2400-70fd-11eb-9a63-43027a757bea.png)

### Steps to Reproduce
1. Go to 'People > Communications > New Communication'
1. Click on 'Recipient Preference' for communication medium.
1. Choose any communication template
1. Click 'Send Test' and send a test
1. See error

**Expected behavior:**

Sending a test communication should send a test communication (when communication is to recipient preference, medium could be based on the context of where you clicked it)

**Actual behavior:**

Sending a test throws an error and, in the case of SMS, the test is not sent.

### Versions
* **Rock Version:** 13.0.4
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1199944968359596">image.png</a>

**Comment by nairdo** [comment]
@briankalwat We believe you may be having a problem with that OneSignal plugin.  In [version `1.13.0.1` we changed](https://www.rockrms.com/technicalreleasenotes#m13.0) the Rock.Model.CommunicationRecipient.PersonAliasId to nullable which seems to be the reason for the trouble with the plugin.  We think it would be best if you contacted the plugin developers to have them make sure [their code](https://github.com/NewSpring/apollos-onesignal/blob/master/Communication/Transport/OneSignal.cs#L187) can handle a null PersonAliasId.  

We'll leave this open for a few days until we hear back from you.

**Comment by briankalwat** [comment]
@nairdo Okay, we'll be reaching out to them in the next day or two. Thank you!
