### ISSUE TITLE
Re-Activating Large Communication List Times Out

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4603]
### Description

I noticed that inactivating a large-ish (1,019 recipients in my case) Communications List inactivates all the members, which is expected.... but RE-activating the same list does not complete, and throws a _Request Timed Out_ exception. I think this is similar to https://github.com/SparkDevNetwork/Rock/issues/4299, but happens during RE-activation of the list, not inactivation.

### Steps to Reproduce

1. Find a Communications List with a large number of recipients (1000+)
2. Inactivate the list, which happens almost instantly.
3. Re-activate the list
4. Observe that this times out and the list is left in an inactive state after throwing a timeout exception.

**Expected behavior:**

I'd be able to re-activate communications lists regardless of size

**Actual behavior:**

On my pretty powerful Rock/SQL instance, it times out with a list just over 1000 members

### Versions

* **Rock Version:** 11.3

**Comment by WomackCodes** [comment]
Hey Jim (@JimMichael), thanks for taking the time to submit this issue.  While trying to reproduce this, I was able to see the same error message for a request timeout when attempting to make a 1,503 strong list "inactive" following your steps.  However, I checked my Communication List after refreshing the browser and it still properly made the list "active" despite showing me the request timeout error.  While we work on fixing the error, can you confirm if your list becomes active again upon refreshing the browser after you see the session timeout error?

**Comment by JimMichael** [comment]
@cwomack Sorry, I somehow missed your question to me until today when I revisited this issue. In my case, NO, the list is NOT re-activated after refreshing the browser after getting the timeout. This is also not limited to Communication Lists.. it just happened to me on a Serving Team group of 722 members that someone here accidentally inactivated. We are unable to re-activate it at this time.

**Comment by nairdo** [comment]
After some research and attempt to reproduce, we've uncovered this issue was also corrected when we fixed issue #5112 via https://github.com/SparkDevNetwork/Rock/commit/ec6c152f918350bafca45c1a9b29480ffdd9b10a

**Comment by TheArkChurch** [comment]
We are on 15.1 and just ran into this problem on a communication list with almost 10k people. I was able to make smaller list (< 500 ) inactive and active without issue. Anything above 500ish fails all of the time. I have a 536-person list that both worked and failed at different times.

We are using azure SQL 200 DTU, b4ms VM.
