### ISSUE TITLE
Connection Opportunity Search block does not display Default Value for Attributes

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4604]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

If you set a Connection Opportunity Attribute to have a Default Value, the Value is not selected by default on the external site (**Connection Opportunity Search** block).

The default value is selected automatically on the internal site, on the Opportunity Attributes section of the **Connection Opportunity Detail** block.

<img width="1677" alt="Screen Shot 2021-02-17 at 19 03 08" src="https://user-images.githubusercontent.com/23226974/108285011-442e2b00-7154-11eb-8c33-e7ada5507eba.png">

<img width="1679" alt="Screen Shot 2021-02-17 at 19 03 29" src="https://user-images.githubusercontent.com/23226974/108285014-44c6c180-7154-11eb-9aae-3c2c0301c29c.png">

### Steps to Reproduce

1. Create a Connection Opportunity Attribute, and set a Default Value.
2. Go to **Connection Opportunity Search** block on external site, and see that the default value is not selected.

**Expected behavior:**

The default value should be selected automatically.

**Actual behavior:**

The default value is not selected.

### Versions

* **Rock Version:** [v12.0, v12.1]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Hi @mikedotmundy  We don't typically set 'search filters' with default attribute values (and looking around in the code, we currently don't have a way to do that). But, if this is an enhancement you want to use your voting points on and to let the community vote it up, I'd ask you to jump over to [http://community.rockrms.com/ideas]( http://community.rockrms.com/ideas) to submit the idea there.  Thanks!
