### ISSUE TITLE
Step Completed trigger on Step Type / Program doesn't trigger when "Step Add" workflow action is used

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4606]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When there's a workflow trigger set for Step Completed on either the Step Program or the Step Type, the workflow never fires when the step is completed via the "Step Add" workflow action. The step is added correctly, just the workflow trigger doesn't actually trigger. Manually adding the Completed Step triggers the workflow as expected.

I tested also adding the same workflow to the step program instead of the step type as a "Step Completed" trigger, and it doesn't trigger when set on the step program either.

> The workaround I've found until this bug is fixed is to add Post-Add Workflow Trigger under General Settings. You can't check for status of complete since you can only have one Qualifier Column, but it suits our needs until it's fixed.

### Steps to Reproduce

1. Go to the demo site and create two new workflows
2. Name the first workflow "Add Step to Alisha"
    1. Create an attribute of type `Person`, set default to `Alisha Admin`
    2. Create an attribute of type `Step Program Step Type`, set default to `Baptism`
    3. Create an attribute of type `Date`, set default to today's date
    4. Create an attribute of type `Step Program Step Status`, set default to `Complete`
    5. Add an action of type `Person > Step Add`
    6. Set action fields Person, Step Type Id, Step Status Id, Start Date, and End Date to attributes created
    7. Save
    8. ![image](https://user-images.githubusercontent.com/66277785/108733592-a5f7e780-74fc-11eb-973c-ac02b2f419df.png)
3. Name the second workflow "Workflow Trigger on Step Completion"
    1. Add an action of `Workflow Control > Write to Log`
    2. Add a message
    3. Save
4. Go to People > Steps
5. Click on the Discipleship Path step program
6. Click on the Baptism step type then click Edit
7. Add a workflow trigger for `Step Completed`, set the workflow type to `Workflow Trigger on Step Completion`
8. ![image](https://user-images.githubusercontent.com/66277785/108732467-988e2d80-74fb-11eb-883e-d9e61fa083cf.png)
9. Go to the Workflow Configuration page and find the `Workflow Trigger on Step Completion` workflow, then click on Manage Workflows
10. In a new tab, open up your profile (Alisha Admin), and add the Baptism step manually _(this is to show that the trigger works for manual addition)_
11. Refresh the other Manage Workflows tab and notice that the workflow was triggered successfully
12. Go back to Alisha's profile and delete the step
13. Open a new tab and go to the Workflow Configuration page and find the `Add Step to Alisha` workflow
14. Run that workflow
15. Refresh the tab with Alisha's profile, notice the step was added correctly
16. Refresh the Manage Workflows tab for `Workflow Trigger on Step Completion` and notice the workflow never runs

**Expected behavior:**

I would expect that the workflow trigger for Step Completed would run successfully regardless if the step was completed manually or via the Step Add workflow action.

**Actual behavior:**

When the step is completed through the Step Add workflow action, the Step Completed workflow trigger never runs.

### Versions

* **Rock Version:** [Rock McKinley 12.0 (1.12.0.10)]
* **Client Culture Setting:** [en-us]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1199983279374548">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1199977746268300">image.png</a>

**Comment by rutledgek** [comment]
Does anyone know if this was also an issue with the step automation job adding completed steps and not firing the workflow and if so, has that been fixed as well?

**Comment by TheArkChurch** [comment]
This issue does exist when a person is added by the data view automation. Just tested in prealpha and it is fixed.
