### ISSUE TITLE
API Call People/GetByPersonAliasId Does not return Phone Numbers

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#4610]
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

We have a PersonAliasId for a member and want to retrieve their name,email and phone number to display on an external 3rd party tool.

We can use the API Call for /api/People/GetByEmail/{email} and it returns an array of numbers like it does in the "example" return, but the /api/People/GetByPersonAliasId/{personAliasId} does not return phone numbers in the actual call even though the "example" response does include phone numbers.

### Steps to Reproduce

1. Go to Demo Site rock.rocksolidchurch.com
2. Go to the API Docs on Admin Tools > Power Tools > Api Docs
3. Scroll down and find "People" on the left bar
4. Expand the "GET" call for /api/People/GetByPersonAliasId/{personAliasId}
5. Input the PersonAliasId of '10' for Alisha Admin
6. Make sure Alisha Admin has a Phone Number (She does not by default)
7. Press the Try it now button
8. See that the return shows "PhoneNumbers": [], but nothing under it expanded out

**Expected behavior:**

It should show they array of phone numbers so we can do some selects and pull out the values we want in the query

**Actual behavior:**

It does not return phone numbers

### Versions

* **Rock Version:** [11.3]
* **Client Culture Setting:** [en-us]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1199983279374551">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1199983279374553">image.png</a>

**Comment by nairdo** [comment]
Hi @markewampler I know some of the endpoints are somewhat restricted in what they can return but others which return a _Queryable_  can return expanded items/collections.

For example, the /api/PersonAlias endpoint can be queried to `$filter` on Id, `$expand` the `Person/PhoneNumbers`, and even `$select` only certain items such as the person's `FirstName`, `LastName`, `PhoneNumbers/Number` and `PhoneNumbers/NumberTypeValueId` like this:

![image](https://user-images.githubusercontent.com/383807/109576176-89395200-7ab0-11eb-81a3-ef9e68aaa5ec.png)


```
https://www.rocksolidchurchdemo.com/api/PersonAlias?$expand=Person%2FPhoneNumbers&$filter=Id%20eq%2016&$select=Person%2FFirstName%2CPerson%2FLastName%2CPerson%2FPhoneNumbers%2FNumber%2CPerson%2FPhoneNumbers%2FNumberTypeValueId
```

Do you think this would be an acceptable workaround for your needs?
