### ISSUE TITLE
Tags In Bio Bar Don't Show Color/Sort Until Forced Page Refresh

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4611]
### Description

When adding an existing org tag to a person's profile, the resulting screen does not show the tag in its proper sort order, nor does it show it with its defined background color, until you refresh the page.

### Steps to Reproduce

1. Configure and Org Tag with a background color
2. Go to a person and add the tag
3. Observe that the tag is at the end of the list (not sorted), and shows with the default gray background
4. Refresh the browser (Chrome/Edge work with a simple click of the refresh button, Firefox needs a full shift-refresh)
5. Observe the tag list is now sorted and the new tag shows with its proper color.

**Expected behavior:**

Added tags would be in proper order and color without manually refreshing or leaving/returning to the record.

**Actual behavior:**

They don't.
![image](https://user-images.githubusercontent.com/3903408/109225709-419a8980-7783-11eb-8eac-b512d60ba396.png)
![image](https://user-images.githubusercontent.com/3903408/109225726-48290100-7783-11eb-9327-d8a3a46bada7.png)

I also verified this still happens in prealpha. Maybe this isn't fixable, since it would seem to require a page refresh after adding the tag... but bringing it up for polish in case it is.

### Versions

* **Rock Version:** 11.3+

**Comment by jonedmiston** [comment]
Just adding some notes here. @JimMichael you are correct. This behavior has been there since the beginning. It's going to be a challenge to fix. I'm thinking it will be easier once we move to a new UI framework that's more client-side. 

Let's keep this open as a reminder of the fact that it would be good to clean-up.

**Comment by JRichmond27** [comment]
For what it's worth, if you include icons with your tags, they also don't show up until after a full reload.
