### ISSUE TITLE
TitleCase Lava filter removes special characters

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/Rock#4612]
### Description
The `TitleCase` Lava filter displays some strange behavior in regards to special characters. After some testing, it appears to be dependent whether the dash character is present and it's position relative to whitespace characters.

If the string contains a dash with no whitespace on either side of the dash, then `TitleCase` replaces the dash with a space, but leaves all other special characters alone.

If the string does not contain a dash or contains a dash directly next to a whitespace character, then all special characters are removed.

There are no situations I could find where all special characters were left untouched. 

A very relevant example where this is a problem would be titles with Bible verses. Currently `{{ 'Matthew 24:29-41' | TitleCase }}` outputs `Matthew 24:29 41`.

I tested on Rock v10.3 and v12 with the same results.

### Steps to Reproduce
Add the following Lava code to a page:

```
{%- capture test1 %}aa'aa/aa:aa|aa-aa{% endcapture -%}
{%- capture test2 %}aa'aa/aa:aa|aa aa{% endcapture -%}
{%- capture test3 %}aa'aa/aa:aa|aa -aa{% endcapture -%}
{%- capture test4 %}aa'aa/aa:aa|aa- aa{% endcapture -%}
{%- capture test5 %}aa'aa/aa:aa|aa - aa{% endcapture -%}
{%- capture test6 %}Matthew 24:29-41{% endcapture -%}
{%- capture test7 %}Men's Gathering{% endcapture -%}
1: [{{ test1 | TitleCase }}]<br>
2: [{{ test2 | TitleCase }}]<br>
3: [{{ test3 | TitleCase }}]<br>
4: [{{ test4 | TitleCase }}]<br>
5: [{{ test5 | TitleCase }}]<br>
6: [{{ test6 | TitleCase }}]<br>
7: [{{ test7 | TitleCase }}]
```

**Expected behavior:**

Based on the name of the filter and on what the Lava manual currently says, it seems to me that the filter should only change the case of the alpha characters and all other characters should be left untouched. I would not expect any characters to be replace by whitespace.

**Actual behavior:**

Special characters are replaced with a space, depending on whether a dash is present, and it's position, relative to other whitespace characters.

Actual Output:

```
1: [Aa'aa/aa:aa|aa Aa]
2: [Aa Aa Aa Aa Aa Aa]
3: [Aa Aa Aa Aa Aa Aa]
4: [Aa Aa Aa Aa Aa Aa]
5: [Aa Aa Aa Aa Aa Aa]
6: [Matthew 24:29 41]
7: [Men S Gathering]
```

### Versions
* **Rock Version:** Rock McKinley 10.3 (1.10.3.7)
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
We use the Humanizer library for that filter. Looks like there is an issue there reporting the same behavior. 
https://github.com/Humanizr/Humanizer/issues/599

We may need to consider using `input.ApplyCase(LetterCasing.Title)` instead of the current `input.Titleize()`.

Assuming that works does anyone see an issue with this change of behavior. Seems like the Humanizer team believes:

> this method [Titleize] strips a lot of non-word characters in order to make texts more readable

**Comment by nairdo** [comment]
As we wait for community feedback, if we end up changing to what the Humanizer team suggests, the output (I just tested) would be:
```
1: [Aa'aa/aa:aa|aa-aa]
2: [Aa'aa/aa:aa|aa Aa]
3: [Aa'aa/aa:aa|aa -aa]
4: [Aa'aa/aa:aa|aa- Aa]
5: [Aa'aa/aa:aa|aa - Aa]
6: [Matthew 24:29-41]
7: [Men's Gathering]
```

**Comment by JRichmond27** [comment]
I think that looks much better, and would definitely be superior to the current behavior. 

However, assuming there's anything that can be done about it... according to my wife with the English degree the first letter after each slash or dash would be capitalized. She couldn't think of a situation where a colon would be properly used without a space after, and the pipe character isn't really used in grammatially correct English. So ignoring the colon and pipe situations, the output would be:
```
1: [Aa'aa/Aa:aa|aa-Aa]
2: [Aa'aa/Aa:aa|aa Aa]
3: [Aa'aa/Aa:aa|aa -Aa]
4: [Aa'aa/Aa:aa|aa- Aa]
5: [Aa'aa/Aa:aa|aa - Aa]
6: [Matthew 24:29-41]
7: [Men's Gathering]
```
One other situation that we realised hasn't been tested was opening parenthesis. The first letter after the parenthesis should be capitalized. What would the output of this look like?
```
{%- capture test8 %}aa (aa aa){% endcapture -%}
8: [{{ test8 | TitleCase }}]
```
Of course, all of this ignores rules about conjunctions, prepositions and other short words in titles being lower cased, but I don't think that would be a critical issue.
