### ISSUE TITLE
Registration Instance Registration List Balance Due Does Not Show People Without Any Payments.

### ISSUE THREAD

**Issue by rutledgek** [SparkDevNetwork/Rock#4613]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
When a registration owes money but does not have any payments(owes a full balance) the person is not shown when the balance due filter option is selected.

### Steps to Reproduce

1. Create a registration with fees.
2. Filter Registration List to show the balance due.
3. See that the one without any payments is filtered out even though they owe the full balance.

**Expected behavior:**

View all people who owe money including those who have no payments.

**Actual behavior:**

Only people with payments and who owe money are shown,

### Versions

* **Rock Version:** Rock McKinley 11.3 (1.11.3.1) (Tested on Rock Solid Demo 1.12.0)
* **Client Culture Setting:** en-US

**Comment by rutledgek** [comment]
Replacing        
```
var rPmtSummary = rCosts
                           .Join(
                               rPayments,
                               c => c.Key,
                                p => p.Key,
                                ( c, p ) => new
                                {
                                   RegistrationId = c.Key,
                                   Costs = c.Value,
                                   Payments = p.Value
                                } )
                            .ToList();
```
with the code below appears to solve the issue.
```
var rPmtSummary = from rCost in rCosts
                                          join rPayment in rPayments
                                            on rCost.Key equals rPayment.Key into results
                                          from result in results.DefaultIfEmpty()
                                          select new
                                          {
                                              RegistrationId = rCost.Key,
                                              Costs = rCost.Value,
                                              Payments = result.Value
                                          };

```

**Comment by ethan-sparkdevnetwork** [comment]
@rutledgek I used the Linq GroupJoin() and SelectMany() extension methods instead of the query since that is the preferred method in Rock. But it's the same solution, use an Outer Left join to get all the registrations and any available payments. Thanks for your help!
