### ISSUE TITLE
v12.1 When clicking email on person profile it doesn't add them to the communication wizard

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#4616]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

on v12 and prior when I click on an email address from a person's profile it would open the wizard and have that person selected to send the email to. Now on v12.1 it comes up with an empty list and requires you to click the new "Manual List" button and add the person to the email.

I noticed on the demo site that it goes to the simple communication instead of the wizard. If we need to I guess we could switch to using that instead of the communication wizard.

### Steps to Reproduce

1. Go to a person profiles page
2. Click the email address
3. For us we populate the wizard page and have an empty list requiring us to click "Manual List" and add the person to the list.

**Expected behavior:**

I would expect when clicking the email link from a person's page that it would populate the wizard and have that person on the list already

**Actual behavior:**

Clicking on the email takes us to the email wizard page with nobody on the list.

### Versions

* **Rock Version:** [12.1]
* **Client Culture Setting:** [en-US]

**Comment by randyjreed** [comment]
I have confirmed this also on 12.1. However, the person is on the list they are just not visible. If you click the manual list then proceed without adding them it will show 1 recipient and allow you to proceed.

So the issue may be more that it lands on the wrong communication type. Also when you are on the Recipient List the list only displays the recipients after there are 2 recipients.

![Screen Shot 2021-03-03 at 10 07 50 AM](https://user-images.githubusercontent.com/22873346/109851300-60c46b80-7c08-11eb-9718-ada9972b9881.png)

**Comment by JimMichael** [comment]
The communication type is a choice when you edit the Bio block. Just pick the page you want.
![Uploading image.png…]()

**Comment by randyjreed** [comment]
Yes, that is not the issue though. Pre-12.1 even using the Communication Entry Wizard a single individual would show in the list and you would not have to toggle from Communication List to Manual List to proceed.

**Comment by JimMichael** [comment]
There are two issues referenced in the initial post. I was responding to _I noticed on the demo site that it goes to the simple communication instead of the wizard. If we need to I guess we could switch to using that instead of the communication wizard._ and _So the issue may be more that it lands on the wrong communication type_  both of which are fixed by configuring the block to use the type of communication you wish.

**Comment by matthewbronkema** [comment]
Fixed with 3fb859439e1258a993dd8dc12ddc2e8df47e0f19
