### ISSUE TITLE
Check-In Manager Showing Inactive Rooms

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#4619]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Check-in Manager appears to show Inactive Locations in the dropdown selection on the Room Manager. 

### Steps to Reproduce

1. Go to Checkin Manager
2. https://rock.rocksolidchurchdemo.com/page/2639?LocationId=8
2. Click on Room Manager
3. Select the Room/Location Dropdown
4. Notice that the Bobcats room shows up.
5. Go to Check-in > Locations
6. https://rock.rocksolidchurchdemo.com/page/307?LocationId=8&ExpandedIds=2%2c3
7. Notice that the Bobcats room is 'inactive'

**Expected behavior:**

I would expect that if a Room/Location is 'ACTIVE' it would show up within the Checkin Manager to select from.
I would expect that if a Room/Location is 'INACTIVE' it would not show up within the Checkin Manager.

**Actual behavior:**

Regardless of a room/location being Active or Inactive, the room/location still shows up to select from the Checkin Manager.

### Versions

* **Rock Version:** [12.2]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
@jcjones37  I did verify this is the intended behavior.  The list of locations in the Check-in Manager must show all locations (active and inactive).

**Comment by jcjones37** [comment]
Thank you @nairdo
