### ISSUE TITLE
Connection Request Badges not Showing

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4623]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Some of the Person Badges on the _Connection Request Board_ AND _Connection Request Detail_ blocks are not showing up. In particular from my testing, the **Record Status** and **Campus** badges.

**NOTE:** The steps below are for the _Connection Request Board_ block, but the same is happening for the _Connection Request Detail_ block (`/page/408?ConnectionRequestId=1&ConnectionOpportunityId=3`).

![Screen Shot 2021-03-09 at 13 22 15](https://user-images.githubusercontent.com/23226974/110519878-d5e9e200-80db-11eb-9641-db5f6e6ca18d.png)

![Screen Shot 2021-03-09 at 13 22 30](https://user-images.githubusercontent.com/23226974/110519906-dbdfc300-80db-11eb-89df-a7e5a77af4a4.png)

### Steps to Reproduce

1. Go to `/page/642?ConnectionOpportunityId=3`
2. Edit the block settings for the _Connection Request Board_ block, and turn on the **Connection Status**, **Record Status** and **Campus** badges.
3. Save, then click on a Connection Request, and see that only the **Connection Status** badge is displayed.

**Expected behavior:**

The badges should show.

**Actual behavior:**

The badges do not show.

### Versions

* **Rock Version:** [v12.1, v13.0]
* **Client Culture Setting:** [en-US]

**Comment by cwomack** [comment]
@mikedotmundy I reproduced the same "outcome" you referenced, but got further clarity on the functionality of this block from Nick.  Some of the badges have different logic then simply showing the same way that _Connection Status_ or _Baptism_ do.  For example, _Record Status_ will only populate something for the badges if they are **inactive**.  

Let us know if you find anything else that may look like a bug on this block or others tied to badges, but we'll close this out if not!
