### ISSUE TITLE
Check-In Manager Drawer gets stuck on "refresh"

### ISSUE THREAD

**Issue by milescarmany** [SparkDevNetwork/Rock#4625]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

The Navigation 'drawer' in the Check-In Manager can open and close with the hamburger menu. Once the Live Stats graph has been clicked to refresh/update the view, the navigation drawer will not change state until a browser refresh.

[Screen Capture](https://drive.google.com/file/d/1ggX9a7P8KiiN-3ThnzqPfSA31MiCGiO2/view?usp=sharing)

### Steps to Reproduce

1. Go to 'Check-in Manager'
2. Go to 'Live Stats' View
2. Click on the hamburger menu to open/close the Navigation Drawer
3. Click on the Live Stats Graph and wait for the view to update/refresh
2. Click on the hamburger menu to open/close the Navigation Drawer

**Expected behavior:**

1. Go to 'Check-in Manager'
2. Go to 'Live Stats' View
2. Click on the hamburger menu to open/close the Navigation Drawer
3. Click on the Live Stats Graph and wait for the view to update/refresh
2. Click on the hamburger menu to open/close the Navigation Drawer
3. The Navigation Drawer opens or closes

**Actual behavior:**

1. Go to 'Check-in Manager'
2. Go to 'Live Stats' View
2. Click on the hamburger menu to open/close the Navigation Drawer
3. Click on the Live Stats Graph and wait for the view to update/refresh
2. Click on the hamburger menu to open/close the Navigation Drawer
3. The Navigation Drawer does not open or close

### Versions

* **Rock Version:** [Rock McKinley 12.0 (1.12.0.10)]
* **Client Culture Setting:** [en-US]

Also tested on the Demo Site.

**Comment by cwomack** [comment]
Miles (@milescarmany), 

I was able to reproduce this issue **when using Rock **v12.0****, but we have a fix for it in v12.1.  If you're able to reproduce it on v12.1 or higher, can you reply back with the steps you took?  Usually someone will update the Demo Site throughout the day, and you might have tested it before anyone else got to it.  If it works after updating to the newer version, feel free to close out this issue or I'll circle back to do so within a week.  

Thanks for your submission to make Rock better!

**Comment by cwomack** [comment]
@milescarmany Just wanted to let you know I'll be closing this out.  If there's any further issues seen after updating to v12.1 or later, please feel free to reply back or submit a new issue.

**Comment by milescarmany** [comment]
After updating our instance to 12.2, it appears fixed, thanks!
