### ISSUE TITLE
QR code from mobile check-in contains previous check-in occurrences if checking into multiple services within 8 hours from the same device

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4626]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

On Sundays, we have two identical services, one at 9:45a and one at 11:30a. We have several families / volunteers who serve / check-in their kids for both services. Whenever they scan their QR code for the 11:30a service, the kiosk will print both their labels for the 11:30a service _and_ the 9:45a service (again, only happens if they checked in to the 9:45a service, too). 

Overall it isn't hindering us from doing anything, it's just very inconvenient and confusing for families to filter through the tags printed.

Looking through the code, I found in Rock/RockWeb/Blocks/CheckIn/Success.ascx.cs that the AttendanceSessionGuids cookie expires eight hours after last use:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/66277785/110859293-379b7f00-8289-11eb-8d20-546fef27aa68.png">

By all means I'm not suggesting that this is the best way to fix this, but one possible solution would be to alter the code that sets that cookie to set the expiration of the cookie to the date/time when the current schedule ends. That way the cookie would only be active during the schedule's active period.

### Steps to Reproduce

1. Go to https://rock.rocksolidchurchdemo.com and login as admin
2. Navigate to CMS Configuration > Pages and find the Mobile Check-in Launcher page
3. Configure the block like below:
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/66277785/110852417-59443880-8280-11eb-9ff8-c8884bc93ad3.png">

4. Go to Check-in > Schedules
5. Create two schedules _(these will change depending on when you're reproducing the problem, since the whole issue is based on the premise of having same-day, non-overlapping schedules, the only requirement here is that the schedules do not overlap **and** that they are in the same day)_
6. Go to Check-in > Check-in Configuration and click on the Weekly Service Check-in
7. Click Schedule and add the two new services you created to all areas listed
8. Go to Check-in > Devices > Central Kiosk and create a geo-fence around where you're testing
9. When your first schedule is active, go to https://rock.rocksolidchurchdemo.com/mobilecheckin and follow the check-in process as Alisha Admin
10. When you get your QR code, scan it with a QR code reader to see the contents and notice there's only one value after `PCL+` in the text:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/66277785/110858406-0a020600-8288-11eb-8b26-d14070d5b040.png">

11. After the first schedule is inactive and the second schedule created becomes active, check-in again as Alisha Admin from the same device you used to check-in the first time
12. Scan the new QR code to see the contents and notice there's now two comma-separated values after `PCL+` in the QR code:
<img width="432" alt="image" src="https://user-images.githubusercontent.com/66277785/110858459-18e8b880-8288-11eb-8791-ac586fa98da0.png">

**Expected behavior:**

I would expect when I scan the QR code for the second service I checked into that I would only get labels printed for the service I just checked into, regardless if I checked into an earlier service.

**Actual behavior:**

When scanning the QR code for the current service, if I also checked into last service, labels from both service check-ins get printed.

### Versions

* **Rock Version:** [Rock McKinley 12.1 (1.12.1.5)]
* **Client Culture Setting:** [en-us]

**Comment by cwomack** [comment]
Hello @leahjennings.  As for the default setup of **AttendanceSessionGuidsCookie** expiring eight hours after the last use, I'd recommend submitting any ideas on how to enhance the behavior of the QR code/cookie expiration timeframes on the Rock Community Ideas board via [http://community.rockrms.com/ideas](http://community.rockrms.com/ideas). This allows the full community to speak into it and help us determine it's priority.

Thank you for the detailed submission/screenshots and for helping to make Rock better!
