### ISSUE TITLE
SMS Pipeline Detail - Latency on initial load

### ISSUE THREAD

**Issue by chrisfunk-lpc** [SparkDevNetwork/Rock#4627]
### Description
In an attribute rich environment, the SMS Pipeline Detail block can take over a minute to load on initial load after the cache is cleared or after worker process reloads.  I believe that it is due to the AttributeCache.All() that is being called at [Line 101 of SMSPipelineDetail.ascx.cs](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Communication/SmsPipelineDetail.ascx.cs#L101).

### Steps to Reproduce
* assumes already having SMS Actions in a SMS Pipeline * 

1. Clear Cache
1. Load SMS Pipeline List
1. Select a pipeline
1. Wait for load 

**Expected behavior:**

The SMS Pipeline detail block will load quicker on an attribute rich Rock instance

**Actual behavior:**

Slow load time. 1:00 minute plus on Attribute rich Rock Instance

### Versions
* **Rock Version:** 11.2 (also confirmed in 12.2)
* **Client Culture Setting:** en-us

**Comment by MikeDPeterson** [comment]
@chrisfunk Thanks for letting us know about this issue! We ended up adding a handy new AttributeCache.AllForEntityType in core that'll fix this issue and help prevent developers from using AttributeCache.All() :)
