### ISSUE TITLE
System Communications w/CSS Inlining Enabled Do Not Have Inline Styling

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#4631]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Communication Templates *and* System Communications in Rock have an option to enable CSS inlining on them (see below). We've recently implemented a block lava shortcode that handles the "frame" of all of our email templates, and we are wanting to use this same shortcode for communication templates as well as system communications.

As of (at least) `13.0.5`, it appears the CSS inlining feature for system communications is not working in the same manner that it is for communications sent with the wizard. I'm unsure if this is an issue with CSS inlining for system communications as a whole, or if it's because we're using a shortcode.

## Regular Communication Template Sent w/Communication Wizard
_Notice the style definitions that have been added to the style attributes on the elements in the inspector window on the right._
![image](https://user-images.githubusercontent.com/2465823/111363550-933d8200-8666-11eb-9055-15244df6396a.png)

## System Communication
_Notice the lack of style attributes on the elements in the inspector window on the right._
![image](https://user-images.githubusercontent.com/2465823/111363432-69845b00-8666-11eb-8ce8-6b6f159a9a22.png)

### Steps to Reproduce

1. Add the following [Lava Shortcode](https://gist.github.com/briankalwat/30a3b575d3a673ef19f9f4f7d649f261) to your Rock instance.
2. Create a new communication template using the shortcode, and enable CSS inlining for it.
3. Modify any system communication to use the lava shortcode you created in step 1, and enable CSS inlining for it.
4. Send a communication from the communication wizard using the template you created in step 2.
5. Trigger a send of the system communication you modified in step 3.

**Expected behavior:**

Both methods of sending communications should write the styles from the lava shortcode to the style attributes of the HTML elements themselves.

**Actual behavior:**

Only communications sent with the email wizard have their styles inlined properly.

### Versions

* **Rock Version:** 13.0.5
* **Client Culture Setting:** en-US

**Comment by briankalwat** [comment]
To update this issue - CSS inlining is also not happening when the shortcode is used in the context of the Send Communication workflow action.

**Comment by jonedmiston** [comment]
@briankalwat can you confirm that you had the shortcode working previously in an older version.

**Comment by briankalwat** [comment]
@jonedmiston I was discussing with some other teammates and this is not limited to shortcodes - we were having the issue with static system communications, as well. We started noticing the issue when we switched from Mandrill to Mailgun. From what we've found in researching this, Mandrill has a built-in css inliner that every message gets run through, while Mailgun does not (at least that I am aware of).

**Comment by jonedmiston** [comment]
@briankalwat You are correct the Mandrill did have an option in their API to inline while Mailgun does not. This inlining is done in their backend.  

There's the possibility of adding inlining as a core feature using something like [PreMailer](https://github.com/milkshakesoftware/PreMailer.Net). We'd need to do some research though to see if that is viable. 

Since this isn't a Rock bug I'm going to close this as an issue. Please feel free to open it as a new [Idea ](https://community.rockrms.com/Ideas)(bringing CSS inlining into core) or let us know if it's a feature you'd be interested in funding.

**Comment by briankalwat** [comment]
@jonedmiston so does this mean that the checkbox that states "CSS Inlining Enabled" that is displayed on all communication templates/system communications should be removed, since it doesn't actually do anything when you're using anything other than Mandrill? It being present in those locations gives the impression that it is Rock that is doing the inlining, rather than the communication transport.

**Comment by jonedmiston** [comment]
@briankalwat I don't think we should remove it as there may still be some organizations using Mandrill. We could add a clarification to the help text that says it's dependent upon support in the transport and update the documentation to specify the core transports that support it.

**Comment by briankalwat** [comment]
@jonedmiston It might be good to update [this documentation](https://community.rockrms.com/Rock/BookContent/9#emailconfiguration), as well, as it makes it sound as if Mailgun is the official core-supported transport. Ideally, that "CSS Inlining Enabled" checkbox wouldn't be visible unless you had a transport enabled that supported it, but I trust whatever you think is best. Thanks!
