### ISSUE TITLE
Room Manager Not Displaying People (Check-In Manager)

### ISSUE THREAD

**Issue by adamhann** [SparkDevNetwork/Rock#4637]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    ✅  Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    ❌  I can't find a 12.3 instance to test. ~Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?~ 
    ✅  Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

After checking people into a couple of locations I went to confirm that Check-in Manager was working appropriately to test for bugs. I can see the individuals checked-in under the Live Metrics view but I do not see any people checked in under the Room Manager -> Room Roster view. 

I can go through the Live Metrics view all the way to the Person Profile view, click on the room, for their current check-in, which takes me to a blank Room Roster view again. 

**Live Metric View:**
![Screen Shot 2021-03-26 at 9 20 28 AM](https://user-images.githubusercontent.com/23084345/112638047-33d53400-8e15-11eb-90e1-345016cb70a0.png)

**Room Roster View**
![Screen Shot 2021-03-26 at 9 20 10 AM](https://user-images.githubusercontent.com/23084345/112638100-40f22300-8e15-11eb-95cf-6778be0ac8d0.png)

**Block Settings**
![Screen Shot 2021-03-26 at 9 19 52 AM](https://user-images.githubusercontent.com/23084345/112638139-4b142180-8e15-11eb-958b-7398edccb0bb.png)

### Steps to Reproduce

1. Check some people into different rooms.
2. Go to Check-In Manager -> Room Manager -> Room Roster
3. See blank Room Roster

**Expected behavior:**

The Room Roster should have the same people listed that I see in the Live Metric view.

**Actual behavior:**

The Room Roster is blank. 

### Versions

* **Rock Version:** [12.3 Alpha]
* **Client Culture Setting:** [en-US]

**Comment by JimMichael** [comment]
This is a new bug introduced in 12.3, correct?

**Comment by nairdo** [comment]
@JimMichael Could be, we're attempting to reproduce now.  If we can, we'll also try get that fixed before the alpha starts.

**Comment by cwomack** [comment]
It seems this is all tied to the "Enable Presence" option under the Check-in Configuration.  While running v12.3, if you turn that option **ON**, you should see that the Room Manager/Room Roster properly shows the checked-in individuals accordingly.  It seems they are in a state of "Checked-in" but not considered "Present," which the **Enable Presence** configuration allows you to see/change.  

@JimMichael Can you try this on your local system to confirm?  @adamhann got his working once he changed this.

**Comment by adamhann** [comment]
Correct @cwomack, once I checked "Enable Presense" and went back to check-in manager I was able to see the person who was checked in under Room Roster. 

<img width="1242" alt="Screen Shot 2021-03-26 at 2 35 58 PM" src="https://user-images.githubusercontent.com/23084345/112693916-d31b1b00-8e57-11eb-8235-ee43d6994621.png">

**Comment by JimMichael** [comment]
I can't confirm as I don't have access to 12.3alpha yet, but I can confirm that Room Roster works as expected with Presence disabled in 12.2.

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/sparkdevnetwork/rock/commit/86708cbca3827a5eb4d74846a0dd67493a4c83d9
