### ISSUE TITLE
Phone number validation does not work correctly on event registration

### ISSUE THREAD

**Issue by lauweijie** [SparkDevNetwork/Rock#4638]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When Phone Number is set as a Field Type for an event registration, typing in an invalid phone number does not stop the user from progressing to the next step. In the case where there is more than one registrant, the form proceeds to the next registrant while keeping the phone number and displaying the "The phone number '1' is not a valid phone number." validation error.

### Steps to Reproduce

1. Create a new event registration
2. Enable multiple registrants
3. Add a Registrant Attribute with Field Type as Phone Number
4. Check to make the field a Common Value
5. Save the registration
6. Fill out the event registration form with 2 registrants
7. Enter an invalid phone number for the first registrant and press next

**Expected behavior:**

Validation error shows and the registration does not proceed to the second registrant.

**Actual behavior:**

Validation error shows but the registration proceeds to the second registrant.

### Versions

* **Rock Version:** Rock McKinley 12.0 (1.12.0.10)
* **Client Culture Setting:** en-SG

**Comment by cwomack** [comment]
Hey Jonathan (@lauweijie),

Would you mind submitting some screenshots or further clarity on how you produced you the issue?  In trying to follow your steps, I'm not able to see an error in the registration process on v12.0 despite following your steps.

**Comment by cwomack** [comment]
@lauweijie  I think I may have misinterpreted the wording of this Jonathan.  I believe by "invalid" you meant that if someone inputs a phone number such as "12345," the issue you're reporting is that it will allow you to proceed through registration process despite getting the red font/outline for the input field.  

If so, I'll mark this as confirmed.  Should there be anything else you intended for this issue to address, feel free to leave a reply comment.
