### ISSUE TITLE
Export Calendar Feed Missing Event(s)

### ISSUE THREAD

**Issue by doflynn** [SparkDevNetwork/Rock#4639]
### Description
The Export Calendar Feed does not include all events.  Events that do not have an end date are not included. 

### Steps to Reproduce
I as able to reproduce this issue on https://rock.rocksolidchurchdemo.com/

1. Go to Tools -> Calendar
1. Click on the "Public" calendar
1. Click on "Export Calendar Feed"
1. Paste link to ICS feed in new browser tab (this will download the ics file)
1. Open ICS file in text editor
1. Notice that single day events are missing.
1. Navigate back to Tools -> Calendar and select Public calendar
1. Select "Rock Solid Finances Class" event item
1. Select and Edit the event item occurrence 
1. Modify the schedule  to start today with recurring daily with end by today.
1. Save and return back to Tools -> Calendar and select the "Public" calendar
1. Export and open the ICS file (repeat steps 3-4)
1. Search for and you will now find "Rock Solid Finances" event in ICS

**Expected behavior:**
All approved events that are visible in the event calendar are included in the Export Calendar Feed ics

**Actual behavior:**
Event Item(s) where its Event Item Occurrence schedule is a single date/time (with no end date) are not included in the calendar export.

### Versions
* **Rock Version:** [12.2]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by doflynn** [comment]
Issue is caused by GetEventCalendarFeed.cs.  The method GetEventItems() has an invalid query that does not recognize schedules with no end date.  We updated the source as follows to fix the issue in our production instance...

            var eventQueryable = eventItemService
                .Queryable( "EventItemAudiences, EventItemOccurrences.Schedule" )
                .Where( e => eventIdsForCalendar.Contains( e.Id ) )
                .Where( e => e.EventItemOccurrences.Any( o => o.Schedule.EffectiveStartDate <= calendarProps.EndDate && calendarProps.StartDate <= (o.Schedule.EffectiveEndDate == null ? o.Schedule.EffectiveStartDate : o.Schedule.EffectiveEndDate) ) )
                .Where( e => e.IsActive == true )
                .Where( e => e.IsApproved );

**Comment by cwomack** [comment]
@doflynn thanks for your submission.  It looks like this is similar to Issue #4635 that we're currently working on.  I'll let the team know to review this as well.

**Comment by eddieholeman** [comment]
@cwomack I noticed that on April 6, there is a comment on #4635 that the issue was fixed, but there is nothing to say when the fix will be released. Could you find out timing on that? Also, does that fix correct this issue as well? This issue better describes the problem we are having. We really need a solution to this, so just wondering if it is getting any attention. Thanks.
