### ISSUE TITLE
ALPHA 1.12.3.1 - Mandrill, Mailgun, and SendGrid transports not seen as active by Communication Entry Wizard block

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4643]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

As I was testing to send a communication, I got a warning that `Warning There are no active Email, SMS, or Push communication transports configured.`. In Admin Tools > Communications > Communication Transports, all of the Mandrill / Mailgun / SendGrid transports are active. The block settings of the Communication Entry Wizard block has `Recipient Preference` unchecked. The error doesn't show if `Recipient Preference` is checked, even if none of the transports are active. Both Email and SMS are enabled under Communication Mediums:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/66277785/113011713-0c99a200-9148-11eb-8b32-4f9bb91f80c4.png">

### Steps to Reproduce

1. Go to Admin Tools >  Communications > Communication Transports
2. Edit and activate all of the Mandrill / Mailgun / SendGrid transports (_also make sure no other transports are active_)
3. <img width="1675" alt="image" src="https://user-images.githubusercontent.com/66277785/113011089-6a79ba00-9147-11eb-828e-1ff3c7083a02.png">

4. Go to People > New Communication
5. Edit the block settings
6. Make sure `Recipient Preference` is unchecked and Email / SMS / Push are checked
7. <img width="1673" alt="image" src="https://user-images.githubusercontent.com/66277785/113011284-a3b22a00-9147-11eb-9c19-adad7ae33159.png">

8. After block settings are saved, click Manual List
9. Add someone to the list and click next

**Expected behavior:**

Because I have at least one Email transport configured, I would expect that the wizard would let me continue with my communication creation.

**Actual behavior:**

There is an error on the screen saying there aren't any active transports.
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/66277785/113011586-eecc3d00-9147-11eb-845f-390f90417b3c.png">

### Versions

* **Rock Version:** [12.3 (1.12.3.1)]
* **Client Culture Setting:** [en-US]

**Comment by JimMichael** [comment]
I am unable to dupe this on my 12.3 (1.12.3.1) instance. Regardless of what transports I have active (I tried the exact ones shown) and/or the User Preference setting in the comms block, the wizard never throws an error. Are you sure you're not seeing the issue where the Email Communication Medium gets "cleared" whenever you change to a new active transport (and the transport that *was* selected in the Medium gets inactivated)? That would induce the same error. 

![image](https://user-images.githubusercontent.com/3903408/113015058-c55ce280-9142-11eb-8943-99d57dabd375.png)
