### ISSUE TITLE
oData $count does not seem to be supported

### ISSUE THREAD

**Issue by lancelotdaemion** [SparkDevNetwork/Rock#4644]
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
I've attempted various ways to retrieve just the count of results from an oData query and none seem to be supported. These include `/api/financialtransactions?$count=true`, `/api/financialtransactions/$count`, and `$inlinecount`.

Has support for these query options been added in a later release? Is there another way of retrieving counts through the API without returning all query results?

Thank you!

### Versions

* **Rock Version:** Rock McKinley 9.4 (1.9.4.1)
* **Client Culture Setting:** en-US

**Comment by abpena1979** [comment]
@lancelotdaemion , Thank you for your submission and your patience on this response.  

The current version of oData that we are using (v3) does not support including $count in the payload.  Please note that the oData response only includes the result set, not the oData metadata.  For more information, please check out our documentation at https://community.rockrms.com/developer.  Thank you for your partnership.
