### ISSUE TITLE
Self-Inactivated Inactive Record Type Doesn't "Reset"

### ISSUE THREAD

**Issue by adamhann** [SparkDevNetwork/Rock#4645]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    ✅  Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Not sure how to reproduce since I can't unsubscribe/self-inactivate from an email block on demo. _(Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?)_
  
  ✅  Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When a user unsubscribes from an email list and also self-inactivates their account, Rock sets an Inactive Record Type defined value on their profile. The value gets set to "Self-Inactivated". We have run into some instances where someone inactivates their account on accident or times when someone comes back to our church. When we reactivate their record in Rock it does not remove the Inactive Record Type defined value. This causes issues with some reporting we have built around Inactive records. 

I couldn't find a way to replicate this properly on the Rock Demo site. Mostly because I don't have a way to self-inactivate an account. Below is an example of some SQL we used to find a person who at one point self-inactivated, but is now an active record again. 

| | Id     | Campus | RecordStatusId | RecordStatus | InactiveRecordType |
| ----------- | ----------- | ----------- | ----------- | ----------- |----------- |
|1 | 199578      | BranchCreek (Harleysville)      | 3| Active | Self - Inactivated |

```
SELECT
    --concat (p.[NickName], ' ',p.[LastName]) AS [Person]
    p.[Id]
    , ISNULL(c.[Name],'') AS Campus
    , p.[RecordStatusValueId] AS [RecordStatusId]
    , rsdv.[Value] AS [RecordStatus]
    , ISNULL(rtdv.[Value],'') AS [Inactive Record Type]
FROM 
    [Person] p
    LEFT JOIN [Campus] c ON c.[Id] = p.[PrimaryCampusId]
    LEFT JOIN [AttributeValue] av ON av.[EntityId] = p.[Id] AND av.[AttributeId] = 46066
    LEFT JOIN [DefinedValue] rtdv ON rtdv.[Id] = p.[ReviewReasonValueId] AND rtdv.[DefinedTypeId] = 41
    LEFT JOIN [DefinedValue] rsdv ON rsdv.[Id] = p.[RecordStatusValueId]
WHERE
    p.[Id] = 199578
```

### Steps to Reproduce

1. Facilitate an email communication to a test profile. Unsubscribe through the email and select "I am no longer involved at...."
2. Once the account has been self-inactivated, use the SQL above, replace p.[Id] with the person Id you are testing on. 
3. Confirm that they have an Inactive Record Type of Self-Inactivated. 
4. Make their record Active. 
5. Run the SQL above, confirm that the Record Status is Active. You'll also see their Inactive Record Type is still Self-Inactivated. 

**Expected behavior:**

Once a record is made Active again I would expect this Inactive Record Type to be set to null or "Reactivated" or something like that. 

**Actual behavior:**

Nothing changes. An active record retains the Inactive Record Type value of "Self-Inactivated". 

### Versions

* **Rock Version:** 11.3
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Hi Adam, 

The `RecordStatusReasonValueId` is a qualifier for `RecordStatusValueId`, and it is tied to the "[Inactive Record Reason](https://prealpha.rocksolidchurchdemo.com/page/119?DefinedTypeId=3)" defined type.   So, the inactive reasons really only apply to a person if their Record Status is Inactive.  

In situations like this, we recommend that a query include the base property (`RecordStatusValueId`) in addition to the qualifying property (`RecordStatusReasonValueId`).  For example, if you wanted to find all the "reasons" (per campus) for people who were **inactive**, you could query:

```Sql
SELECT
    ISNULL(c.[Name],'') AS Campus
    , ISNULL(rsrdv.[Value],'') AS [RecordStatusReasonValue]
    , COUNT(1) as [Total Inactive per Campus per Reason]
FROM 
    [Person] p
    LEFT JOIN [Campus] c ON c.[Id] = p.[PrimaryCampusId]
    LEFT JOIN [DefinedValue] rsrdv ON rsrdv.[Id] = p.[RecordStatusReasonValueId]
WHERE
    p.[RecordStatusValueId] = 4 -- inactive records
GROUP BY c.[Name], rsrdv.[Value]
ORDER BY c.[Name], COUNT(1) DESC
```


_Note: In your example, you have a `ReviewReasonValueId` (which is a bit different and not quite related to the person's Record Status)._

Regardless, if you also wanted that in addition to the record status reason, I might include the RecordStatusReasonValue (rsrdv below) as:

```Sql
SELECT
    p.[Id]
    , ISNULL(c.[Name],'') AS Campus
    , p.[RecordStatusValueId] AS [RecordStatusId]
    , ISNULL(rsrdv.[Value],'') AS [RecordStatusReasonValue]
    , rsdv.[Value] AS [RecordStatus]
    , ISNULL(rtdv.[Value],'') AS [Review Reason Value]
FROM 
    [Person] p
    LEFT JOIN [Campus] c ON c.[Id] = p.[PrimaryCampusId]
    LEFT JOIN [DefinedValue] rsrdv ON rsrdv.[Id] = p.[RecordStatusReasonValueId]
    LEFT JOIN [DefinedValue] rtdv ON rtdv.[Id] = p.[ReviewReasonValueId] AND rtdv.[DefinedTypeId] = 41
    LEFT JOIN [DefinedValue] rsdv ON rsdv.[Id] = p.[RecordStatusValueId]
WHERE
    p.[Id] = 199578
```

Having said all that, we _are_ looking at resetting the RecordStatusReasonValueId back to NULL if a person record status was changed from inactive to active.
