### ISSUE TITLE
Nameless Converted to Real Person

### ISSUE THREAD

**Issue by carriewhite** [SparkDevNetwork/Rock#4646]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

We use SMS pipeline, create nameless people and build on their history as they interact with us through workflows.  If we eventually find out their name, we convert them to a "real" person using the Rock link phone number to person function. When we do so, all person attributes are lost.

### Steps to Reproduce

1. implement SMS pipeline 
2. have someone unknown to Rock text in, which creates a nameless person
3. update person attributes such as salvation date or first time visit date
4. use Rock to convert that nameless person to a real person
5. the previous person attributes are lost

**Expected behavior:**

We would like to use the Rock process to convert a nameless person to a real person (new or existing) and the person attributes be retained.

**Actual behavior:**

The person attributes are lost when converted.

### Versions

* **Rock Version:** [Rock McKinley 12.2 (1.12.2.2)]
* **Client Culture Setting:** [ en-US]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1200176162584239">image.png</a>

**Comment by cabal95** [comment]
@carriewhite I'm sure this will come up when somebody tries to reproduce this so to get a head start; could you add detailed steps about the "Use Rock to convert that nameless person to a real person"?  i.e. how exactly you are doing that process.

A screenshot of the before the conversion (showing the attributes) and a screenshot of after conversion (showing that they are missing) would I'm sure be helpful too.

Thanks!

**Comment by cwomack** [comment]
@carriewhite Was there any further details you could provide on what is happening within your workflow per Daniel's (@cabal95 ) comment above?  In trying to reproduce this issue, even a screenshot or two would help us to see what is happening on the backend of this process.

**Comment by carriewhite** [comment]
Thanks for looking into this!

1) nameless person after using the sms pipeline and a triggered workflow, getting a value for person attribute 4808
<img width="773" alt="nameless person" src="https://user-images.githubusercontent.com/70244373/114107267-7ec76080-9885-11eb-93f9-5c6fd8a27901.png">
2) using Rock to convert that nameless person to a "real" person
<img width="1175" alt="convert nameless" src="https://user-images.githubusercontent.com/70244373/114107296-90106d00-9885-11eb-8b77-f3de8fc736d3.png">
3) "real" person after the conversion
<img width="513" alt="converted person" src="https://user-images.githubusercontent.com/70244373/114107329-a3233d00-9885-11eb-8076-8d12b65a43ed.png">

**Comment by carriewhite** [comment]
@cwomack 
Here's the workflow that is initiated from the sms pipeline that sets the person attribute 4808 from the screenshots above.

[I Said 'Yes' - SMS_202104091031.json.zip](https://github.com/SparkDevNetwork/Rock/files/6287555/I.Said.Yes.-.SMS_202104091031.json.zip)
