### ISSUE TITLE
12.3 Alpha - Check-in Exception When One-Time Schedule Exists

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4649]
### Description

This issue has been discussed at length in chat, but to my knowledge no one has taken the step to actually enter an issue for it... so I am, in the hopes that it can be fixed during the 12.3 alpha phase. ;-)  The issue is described in this thread: https://chat.rockrms.com/channel/troubleshooting?msg=if8KPXpdAQazPyrwx and seems to occur when you have multiple check-in stations (or a refresh of the live Check-In Manager) happening at the same time, when a one-time schedule is active.

### Steps to Reproduce

See thread. I don't think this is easy to reproduce unless you have multiple kiosks getting their config at the same time.

**Expected behavior:**

Check-in would not throw this exception.

**Actual behavior:**

And exception is thrown. I believe @azturner is the most familiar with this bug, and in a separate email he wrote: 

```Emmanuel was getting thousands of those exceptions every day. We found that is because there’s a call to the iCal GetOccurrences in the Schedule’s ToFriendlyScheduleText method that  is not thread safe. We were able to recreate the exceptions by configuring a one-time schedule (non-recurring) in check-in config and then load-testing check-in.  If we changed the method to use your existing thread-safe method, it did not get the exception:```

This **seems** like a pretty easy fix??

### Versions

* **Rock Version:** 12.2+

**Comment by azturner** [comment]
We emailed this to core team, but posting it here too. This is the change we made that fixed this issue for Emmanuel:

![image](https://user-images.githubusercontent.com/548180/113895073-74ba3a80-977d-11eb-9052-c10bd44e9ec2.png)

**Comment by ethan-sparkdevnetwork** [comment]
Implemented David's fix and tested.
