### ISSUE TITLE
Making a Communication List inactive doesn't remove it from the list in the Communication List Subscribe block

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4650]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

The `Communication List Subscribe` block shows a list of Communication Lists. Whenever you inactivate a communication list, that list still shows as an available list to subscribe to in that block.

### Steps to Reproduce

1. Go to the [demo](https://rock.rocksolidchurchdemo.com) site and then Admin Tools > Communications > Communication Lists
2. In a separate tab, go to the [Subscribe page ](https://rock.rocksolidchurchdemo.com/Subscribe)of the External Site (if prompted for login, login as admin/admin)
3. Compare the lists available on the Subscribe page to the ones listed on the Communication Lists page (the only one that _shouldn't_ be on the Subscribe page at this point is the `Members and Attendees` since it is not included in the `Public` category)
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/66277785/113885913-3bd69180-978e-11eb-9005-d6990b40e259.png">

4. On the Communication Lists page, click to the Sports Ministry list then click Edit
5. Uncheck the `Active` checkbox to make the list inactive, then click Save 
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/66277785/113886034-5ad52380-978e-11eb-8f1c-d7321443570b.png">

6. Click back to the Communication Lists page and notice how the Sports Ministry list is now showing as inactive
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/66277785/113886115-6b859980-978e-11eb-8732-676fa4fa48b9.png">

7. Click to the Subscribe page on the other tab and refresh the page
8. Notice how the Sports Ministry list is still an option to subscribe to
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/66277785/113886568-ca4b1300-978e-11eb-80d6-3c0ca508f61c.png">

Note: I also tested viewing the Subscribe page as a non-admin and just a regular member (not a part of any security roles) and the list still shows:
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/66277785/113886893-054d4680-978f-11eb-98e8-55ddda4cd0bc.png">

<img width="1667" alt="image" src="https://user-images.githubusercontent.com/66277785/113886935-0da58180-978f-11eb-9701-d80de2149809.png">

**Expected behavior:**

Making a Communication List _inactive_ wouldn't allow it to be an option to subscribe to within the Communication List Subscribe block.

**Actual behavior:**

Inactivated lists are still options to subscribe to in the Communication List Subscribe block.

### Versions

* **Rock Version:** [Rock McKinley 12.0 (1.12.0.10)] _demo site_
* **Rock Version:** [Rock McKinley 12.2 (1.12.2.2)] _our instance_
* **Client Culture Setting:** [en-us]

**Comment by Luke-Potter** [comment]
I'm having the same issue. I can reproduce both in Production & on the Demo site.
Production Site: Rock McKinley 12.1 (1.12.1.5)

**Comment by jhaberm** [comment]
I can duplicate both of the behaviors mentioned above. It seems the ONLY thing that controls whether a list shows up on the Communication List Subscribe block is whether it is inside one of the Categories that the settings are set to show, irrespective of whether it is Public or Active. Logically I would expect at least one of those other tick boxes to affect it.

Rock Version: Rock McKinley 12.2 (1.12.2.2)

**Comment by cwomack** [comment]
@leahjennings Thank you for the exceptionally clear steps and screenshots for the reproduction of this! Also @Luke-Potter and @jhaberm for confirming further with additional input.
