### ISSUE TITLE
As of v12 you can no longer use same slug for multiple registration instances

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4651]
Reported on behalf of [Sun Valley Church](https://www.sunvalleycc.com/), [Cornerstone Church](https://www.cornerstoneaz.com/) and [Emmanual Church](https://www.eclife.org/)

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

After updating to v12 you can no longer re-use the same URL Slug for registration linkages. All three of the churches above use generic registration slugs on their website (i.e. “registration/baptism”) for registrations that have repeating instances during the year. Their practice in the past has been to create new registration instances for a common registration with the same linkage slug as the previous instance, knowing that the link for that slug would automatically direct people to the newest instance. 

### Steps to Reproduce

1. Go to registrations
2. Create a registration instance and a linkage with a slug value
3. Create a new registration instance and try to add a linkage with the same slug value

**Expected behavior:**

Rock allows the linkage to be created.

**Actual behavior:**

Rock reports the following validation message:
"URL Slug must be unique across all events."

### Versions

* **Rock Version:** v12.2
* **Client Culture Setting:** en-US

Note: This appears to be the commit that changes this functionality: https://github.com/SparkDevNetwork/Rock/commit/dd2a6523#diff-5ec3091704e4ad8ae647b7bc1d27bf4dfb2d1b1f7a85098a04c30f4a2bf04167R131

**Comment by nairdo** [comment]
Hi David @azturner.   We talked about this internally.  Slugs are supposed to be unique. The change that was made in v12 was to fix the bug that was allowing duplicate slugs to be created.  The code that finds the matching registration instance only uses the first (no particular order) one that matches -- another reason why the slug is supposed to be unique.  

As a possible approach for using a perma-route (as it sounds like something you are trying to do)... for something like 'BaptismSignup', we might suggest you set up a route to a page to list all the possible registrations that are applicable or redirect to the one that you choose is most applicable.

**Comment by craigmash** [comment]
I sure thought this was a feature of Rock. We do the same thing for recurring events with multiple instances. Seems like it could be written to not allow the same slug to be used in two registrations that are scheduled to be active at the same time, but allow it on instances that are scheduled at different times. Not to mention slugs used years apart and not being able to use the same one over without finding the previous and deleting it. Any way to get this "bug" back?

**Comment by nairdo** [comment]
@craigmash We wouldn't want the bug back ;), but it sounds like you're in agreement that slugs must be unique but want an easy way to take/steal a URL Slug from another event/registration instance.  Would something like this work [if the slug was not unique at the time you press Save] where you see a modal with this option?
![image](https://user-images.githubusercontent.com/383807/115069762-e6defd80-9ea8-11eb-8008-5c93ebcad76e.png)
_(this is just a mockup)_

**Comment by craigmash** [comment]
For us with recurring events, it would be easiest to allow the same slug as long as the open dates do not overlap. I realize that makes it more complicated to program, but it would make recurring events so simple to setup.

The above would also be useful in some situations as well.

**Comment by nairdo** [comment]
Hi @craigmash, just wanted to give you a quick update... Our silence is not us ignoring the request and it's not about being complicated to program.  We've been discussing and brainstorming if/how it might be possible to achieve something that works for all the use-cases that are in play by all Rock organizations.  We can't just do a simple quick fix since it would have consequences for others.  At the moment, the best choice is to let the administrator/admin the ability to 'move' the slug.

We'll update this issue if we determine there is another option we could pursue.

**Comment by craigmash** [comment]
@nairdo No worries. I understand. I have implemented a workaround. It is not as nice as we had it before, but at least it is usable.

Moving the slug in recurring events would also be a pain. You would then have to remember to go in and change it everytime a reg closes and a new one opens.
