### ISSUE TITLE
Connections Security Visibility Preferences are not honored on the external website

### ISSUE THREAD

**Issue by bengoshow** [SparkDevNetwork/Rock#4654]
I added a Security setting to the View tab for the Greeter connection opportunity. It's hidden now on the back-end when you edit the Connection Type https://rock.rocksolidchurchdemo.com/page/410?ConnectionTypeId=1 (because Alisha isn't in the RSR - Connections Admin role), but still visible on the front end at https://rock.rocksolidchurchdemo.com/page/235, and also still visible in the Connections list at https://rock.rocksolidchurchdemo.com/page/2634

![Screen Shot 2021-04-02 at 10 04 47 AM](https://user-images.githubusercontent.com/1636930/113422708-2b43a700-939b-11eb-94b4-5cd2d946978b.png)

![Screen Shot 2021-04-02 at 10 04 19 AM](https://user-images.githubusercontent.com/1636930/113422720-30085b00-939b-11eb-93d6-e8ff09cd81d3.png)

![Screen Shot 2021-04-02 at 10 05 10 AM](https://user-images.githubusercontent.com/1636930/113422724-339be200-939b-11eb-95d2-547062cc53a7.png)

**Comment by milescarmany** [comment]
@bengoshow Can you replicate this and capture a screen of the security settings for that Connection Opportunity?

**Comment by bengoshow** [comment]
Here's the Security setting I used for the issue: 
![Screen Shot 2021-04-08 at 3 33 26 PM](https://user-images.githubusercontent.com/1636930/114085866-ee3a5180-987f-11eb-9d2c-cddff54eefb0.png)

**Comment by matthewbronkema** [comment]
Fixed on 59b7e4108ff66cf05757c71c634c8fed33b87548
