### ISSUE TITLE
Check-in does not always use query string parameters correctly

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4655]
Submitted on behalf of Scottsdale Bible Church, Cornerstone Church, and Grace Church

### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When attempting to start check-in by passing the configuration settings in the URL (area, kiosk, group types) so that the admin screen is bypassed, check-in does not always honor the settings that are passed in. The first time that you start check-in this way, the settings are correct, but if you then attempt to start check-in again on the same machine with different settings, check-in still uses settings from first time. 

This appears to be due to fact that check-in is prioritizing the settings stored in the browser's local storage over the settings passed in on the query string. Because of this, you need to close all browser sessions, or completely exit/restart check-in apps for check-in to read the new settings.

This makes it difficult to configure a navigation page with different links or batch files for starting check-in with different options pre-selected.

Here are some chat conversations about this issue:
https://chat.rockrms.com/channel/check-in?msg=oogYfRc98YdriEANq
https://chat.rockrms.com/channel/check-in?msg=XNsvnXkPJesRGycaG

Here is a video showing the issue:
https://share.vidyard.com/watch/Xua9wmieSBA2PHMLnk1gzN

### Steps to Reproduce

1. Start check-in by passing configuration settings (area, kiosk, group types) in the query string to bypass the admin screen (for example select a kiosk that has the "Registration Mode" set to yes). 
2. Start check-in again but use a different kiosk in the query string (with a kiosk that does not support registration mode).

**Expected behavior:**

The second time you start check-in it uses the settings passed in on query string (i.e. it does not show the Edit Family, Add Family options)

**Actual behavior:**

Check-in is still using settings from first time it was started (i.e. it shows the Edit Family and Add Family options)

### Versions

* **Rock Version:** v11.3, v12.2
* **Client Culture Setting:** en-US

**Comment by sam-crisp** [comment]
I am seeing this issue on 12.2, where existing kiosks set to one Kiosk ID appear to be changed using URL parameters but once you search for family, no groups are available. Browser storage cookies show correct Kiosk ID. Clearing ASP.NET_SessionId resets the kiosk to work properly. 

![image-20210424-173706](https://user-images.githubusercontent.com/44408754/116273923-cab04b80-a747-11eb-866c-a74481baf91b.png)
