### ISSUE TITLE
POST /api/FinancialBatches not creating record, and instead acting like a GET ALL

### ISSUE THREAD

**Issue by reneesubsplash** [SparkDevNetwork/Rock#4663]
[X] Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
[---] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?  NO - seems to work fine on demo!  What the heck is going on?

### Description

I have discovered an issue with one of our VERY large Subsplash clients where new batches are not getting created with the POST /api/FinancialBatches call.  They currently have 6,261 batches defined in their account.   When a new post call is made, instead of returning the new batch ID like the demo site or other test accounts I have, it's returning ALL records - as if a GET call was made.  The results don't even include the new batch, so somehow the batch create failed?

I have a video with postman calls that I can use to demonstrate (available upon private request) - shows it working on a test account we have, but not for the client account.  Can someone explain what's happening?  Or maybe a support person reach out to me at renee@subsplash.com ?

**Expected behavior:**

POST http://staff.thevillagechurch.net/api/FinancialBatches  (with auth token provided) 
with raw JSON postbody of:
`{
    "Name":"Subsplash Transfer 619199",
    "Status":1,
    "IsAutomated":"false",
    "Note":"All transactions in Subsplash transfer # 619199 are presented in this batch.",
    "ForeignKey":"client_id_799_transfer_id_619199",
    "BatchStartDateTime":"2021-04-14T19:52:57+00:00"
}`
would return an ID of the newly created batch

**Actual behavior:**
Returns JSON of ALL batches for the given client (6,261 batches) 

### Versions

* **Rock Version:** 11.3
* **Client Culture Setting:** (don't know this information for the client)

**Comment by cwomack** [comment]
@reneesubsplash I'm not able to reproduce the issue on either our demo site or my local dev environment using v11.3 and a new database.  I even used your exact JSON postbody (above), and saw it had no issues adding records to my "batches" in Rock.  Postman confirms that it's responding with the expected Id of the newly made batch as well (see below image). 

With both the demo site and my local v11.3 working as expected with it, I'm led to believe it's _possibly_ something in the local environment.   

![image](https://user-images.githubusercontent.com/67726635/115615616-0b214c80-a2a4-11eb-8fce-69fc86f2760f.png)

**Comment by reneesubsplash** [comment]
Actually, I think it may have been because I wasn't calling https in our api integration, and the client servers we were calling were requiring it.  Once I found that little needle in the haystack, everything started working again.  An error would have been more helpful.  But I think that was it!

**Comment by jonedmiston** [comment]
I'm thinking they may have a rule that redirects HTTP traffic to HTTPS via a 301 redirect. That might change the POST method to GET. In which case Rock doesn't even see what's going on. Just a guess...

**Comment by andypullen** [comment]
@jonedmiston I believe using a 308 redirect might solve that https://tools.ietf.org/html/rfc7538

**Comment by jonedmiston** [comment]
Circling back to this. The reported issue to this was resolved when using HTTPS instead of HTTP to prevent the redirect. @andypullen brings up a interesting point about the redirect using the newer 308 instead of the traditional 302 which would prevent the method change from POST to GET.

At this point we're not going to make that change. Our consideration was:

* There is a easy and logical work around (in fact the issue is more of an improper configuration than code).
* Not all clients support 308 yet (only 93% support 308, typically for front-end member facing features support we target 98%)
* We also concerned that this change could impact others how have systems relying on the previous behavior (Hyrum’s Law).
