### ISSUE TITLE
Checked-in People panel of Live Metrics page incorrect when having multiple schedules in one day

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4665]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Since upgrading to v12, we noticed that the _Checked-in People_ panel on the _Live Metrics_ page is incorrect during the second service of the day. Our services on a Sunday are 9:45a (one-hour duration, check-in is active from 7:45a-10:30a) and 11:30a (one-hour duration, check-in is active from 10:30a-12:15p). During the first service (9:45a), the _Checked-in People_ panel is correct. However, once the first service schedule ends and the second service schedule begins, the _Checked-in People_ panel count is including those who were checked-in to the first service. Here's a screenshot of what we see during our second service:
![IMG_6604](https://user-images.githubusercontent.com/66277785/115296186-9fff3b00-a128-11eb-876a-81d682c65dda.jpeg)

Note: the numbers in the graph at the top of the page are correct. Based on the screenshot, you may wonder why the panel shows 155 instead of 158 (158 would be the number currently checked-in, _16_, and the total from the previous service, _142_). Well, we have a few kids who check into both services, and the panel is only counting unique individuals.

We do not have _Allow Checkout_ or _Enable Presence_ checked (both features are disabled).

### Steps to Reproduce
_Bear with me on these reproduction steps, any issue with check-in is just more involved to reproduce. :)_
1. Go to the [demo](https://rock.rocksolidchurchdemo.com) site
2. Go to Admin Tools > Check-in and click _Schedules_
3. In the _Service Times_ category, create two new schedules
     - The only requirement is that they are in the same day. For ease of testing, it may be best to create the first to end shortly before the second one starts.
4. Go to Admin Tools > Check-in and click _Check-in Configuration_
5. Click _Weekly Service Check-in_, then click _Schedule_ to edit the schedules for this configuration
6.  Apply the two new schedules created to all of the areas, then click Save (the two I added are 12p ET and 12:15p ET)
![image](https://user-images.githubusercontent.com/66277785/115425902-08ecbe80-a1ce-11eb-9580-d105f39d109e.png)

7. Edit the _Weekly Service Check-in_ Check-in Configuration and uncheck _Enable Presence_ and _Allow Checkout_, then click Save
![image](https://user-images.githubusercontent.com/66277785/115426779-d55e6400-a1ce-11eb-96f0-01bf5e7c77ee.png)

8. In a new window, open up check-in (https://rock.rocksolidchurchdemo.com/checkin) and login as admin/admin
9. Make sure all _Check-in Area(s)_ are checked, and that the _Check-in Configuration_ is set to _Weekly Service Check-in_
![image](https://user-images.githubusercontent.com/66277785/115426244-5537fe80-a1ce-11eb-8c56-9bc19121addc.png)

10. Check in the following kids (it doesn't matter which area they are checked into):
     - Noah Decker (search by 555-3322)
     - Alex Decker (search by 555-3322)
     - Tim Greggs (search by 555-4450)
11. Go to the Check-in Manager and then [Live Metrics](https://rock.rocksolidchurchdemo.com/page/2640) page
12. Notice the _Checked-in People_ count accurately reflects 3 checked-in individuals
![image](https://user-images.githubusercontent.com/66277785/115426940-fd4dc780-a1ce-11eb-885f-7d05cb19d141.png)

13. Wait until the current schedule is inactive, and the next schedule becomes active
     - In-between schedules, refreshing the _Live Metrics_ page still shows three checked-in kids even though that schedule is inactive
     - ![image](https://user-images.githubusercontent.com/66277785/115428184-23c03280-a1d0-11eb-9992-406c1e4b3e13.png)

14. Go to the same window used for check-in earlier and check-in the following kids:
     - Jordan Greggs (search by 555-4450)
15. Back on the Live Metrics page, notice the _Checked-in People_ count
![image](https://user-images.githubusercontent.com/66277785/115428352-4fdbb380-a1d0-11eb-9a8c-6d8d51883e52.png)

**Expected behavior:**

I would expect the _Checked-in People_ count to only show the number of currently checked-in individuals for the current active schedule. In the case of our example reproduction steps, I would expect the total in step 15 to be **one**.

**Actual behavior:**

The _Checked-in People_ box actually shows all checked-in individuals from that day. In the case of our example reproduction steps, the total in step 15 is **four**.

### Versions

* **Rock Version:** [Rock McKinley 12.2 (1.12.2.2)]
* **Client Culture Setting:** [en-us]

**Comment by cwomack** [comment]
@leahjennings Thank you for the thorough reproduction steps!

**Comment by JimMichael** [comment]
This would be a great bugfix to sneak into 12.4! (just sayin') ;-)

**Comment by nairdo** [comment]
> I would expect the Checked-in People count to only show the number of currently checked-in individuals **for the current active** schedule. 

I'll double check, but I believe the design for the box values are the total for the current **day** -- not for any currently active service.

**Comment by nairdo** [comment]
Shivam beat me to the punch. :)  We briefly discussed this, and we are going to adjust the logic back similar to the old approach.  So, once a check-in schedule's check-in is no longer considered active (IsCheckInActive=false) the counts will adjust (and the people formerly seen in the LiveMetrics under the locations drill-down will also vanish from there too).

![image](https://user-images.githubusercontent.com/383807/118320611-5993c680-b4b1-11eb-9de7-71a8685fcccb.png)

We may be making some additional enhancements that may not be ready for v12.4, so you might expect to see some other improvements in v12.5
