### ISSUE TITLE
iPad Air 1st Gen check-in error with Rock 12.3 upgrade

### ISSUE THREAD

**Issue by nathanschindler** [SparkDevNetwork/Rock#4666]
After upgrading to 12.3 the iPad Airs have an issue with checking in. Using a freshly downloaded Rock Check In app, or Safari, or Chrome, or Edge we get to the Families selection page and when you click on the specific Family, nothing happens. I have tested this on multiple iPad Air 1st gen iPads running iOS 12.5.2 with the same result.
There is a chat open about this in Rock Chat #check-in as well.

 I reset the network settings and reset all the settings on the iPad and still had the same result.

I've tried on newer iPads running iOS 14.4 and higher and the check-in works fine.

I tried to replicate this on the Rock Demo site and the check-in works fine there from the 1st Gen iPads, but then I checked and that site is running 12.2... not 12.3

* **Rock Version:** 12.3

**Comment by nathanschindler** [comment]
If I try and use the Windows client I get several errors, even before logging in. If I click "yes" continue, then it will continue until the Family page and then not go any further, just like the iPads.

Here are some screenshots, all in order leading up to the Families page where we get stuck:
![image](https://user-images.githubusercontent.com/80771497/115606339-32c6e380-a2a9-11eb-8948-a4a0d7319c5c.png)
![image](https://user-images.githubusercontent.com/80771497/115606381-3d817880-a2a9-11eb-8522-6730c65770fa.png)
![image](https://user-images.githubusercontent.com/80771497/115606414-470ae080-a2a9-11eb-9778-c032904acfce.png)
![image](https://user-images.githubusercontent.com/80771497/115606449-5427cf80-a2a9-11eb-9578-5383bda23cd8.png)
![image](https://user-images.githubusercontent.com/80771497/115606510-67d33600-a2a9-11eb-8f01-936d5e99a9a3.png)
![image](https://user-images.githubusercontent.com/80771497/115606581-7e798d00-a2a9-11eb-9bd1-017cfeece84d.png)
![image](https://user-images.githubusercontent.com/80771497/115606600-85a09b00-a2a9-11eb-84a5-47bf638c6909.png)
![image](https://user-images.githubusercontent.com/80771497/115606629-9224f380-a2a9-11eb-9b35-340e96376999.png)
![image](https://user-images.githubusercontent.com/80771497/115606653-9a7d2e80-a2a9-11eb-996c-9e22d2522dea.png)
![image](https://user-images.githubusercontent.com/80771497/115606708-a832b400-a2a9-11eb-884d-d68ebec77e97.png)
![image](https://user-images.githubusercontent.com/80771497/115606724-aec12b80-a2a9-11eb-8db8-62ac18a7a292.png)
![image](https://user-images.githubusercontent.com/80771497/115606750-b7b1fd00-a2a9-11eb-93d5-e790d2198060.png)

**Comment by JimMichael** [comment]
I can confirm that this is a problem on devices running iOS 12.5.2 or earlier, and looks like it will bite a lot of users running the older units.

**Comment by nairdo** [comment]
We are investigating.

**Comment by cabal95** [comment]
Hey guys, just letting you know we found the issue on this. I'll talk to Nick this morning about the fix so hopefully we should have some answers for everybody soon.

**Comment by nathanschindler** [comment]
Thank you! This works.
