### ISSUE TITLE
v12 Campus Filter for Connections missing from top level page

### ISSUE THREAD

**Issue by MichelleDyke** [SparkDevNetwork/Rock#4669]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
 Yes   * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
 No, Demo site is single campus, and I'm not sure how to do a fresh install.  I did post this question in chat and was recommended to submit a bug report.   * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
Yes    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

In v11 there was a Campus filter at the top of the Connections page.  In v12 the Campus filter is missing from the Connections page.  You can filter by campus for individual connection opportunities, but the campus filter doesn't stick from one connection opportunity to the next, so every user will have to select their campus for every opportunity that they manage.  Also, the Connection Dashboard shows the critical, idle, etc dots for all campuses to everyone.  We no longer have a way for people to only see the statuses for the campus requests they are responsible for.

v11
![image](https://user-images.githubusercontent.com/79712671/115918313-62aaee00-a445-11eb-8531-4c7b6464fb55.png)

v12
![image](https://user-images.githubusercontent.com/79712671/115918673-ccc39300-a445-11eb-9a92-20cb090f9136.png)

I really like the high level Connections Dashboard.   It helps our leaders and staff at each campus quickly see if they are staying on top of their Connection Requests coming in.  Hopefully, we can get the Campus filter added back.

### Steps to Reproduce

1. Go to People->Connections
2. Campus filter is not there

**Expected behavior:**

A campus filter that works for all Connection Opportunities

**Actual behavior:**

No Connections campus filter.  I can click each Connection Opportunity individually and filter each one, but that's a lot of work for everyone and it doesn't change the top level Connections page.

### Versions
Works in 
* **Rock Version:** Rock McKinley 11.4 (1.11.4.3)
* **Client Culture Setting:** en-US

Missing in
* **Rock Version:** Rock McKinley 12.3 (1.12.3.1)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1201959575541004">image.png</a>

**Comment by SteveSwaringen** [comment]
We would like to see this come back as well. Our campus staff manage most of our connections, so seeing the numbers at the top level across the whole church is not useful for the people doing the follow-up.
