### ISSUE TITLE
Location/Room counts not showing in check in even when option is checked

### ISSUE THREAD

**Issue by pokes2k** [SparkDevNetwork/Rock#4671]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
Depending on the check-in configuration "auto select option", location/room counts may not show even if display location count option is checked under advanced settings. 

In check in configuration -> edit -> "advanced settings," there is a box for displaying location counts - we have it checked for all configurations. If the general settings -> "auto select options" is set to **people only**, the groups show counts (after people have checked in) when there are multiple rooms available. (example - we have 3 rooms available for 2 year-olds and the room counts show for them during check-in as long as we're using people only rule). However, if we use **people and their area/group/location** setting, the room counts do not show anywhere even if the box is checked.
### Steps to Reproduce

1. Go to admin tools, check-in, check-in configuration. 
2. Click on edit to edit the options for whatever configuration is being used. Make sure Check-in type is set to **Family**. Also make sure Advanced settings, display location count box is checked. 
3. Choose People and their area/group/location option from the Auto Select Options dropdown under general settings. 
4. Make sure there are multiple locations or rooms available for the same group that test people are being checked into. 

**Expected behavior:** Expected room counts to show for groups with multiple rooms available when display location count box is checked, no matter if auto select option is set to people only or people and their area/group/location. 

**Actual behavior:** Room counts show for groups with multiple rooms available (with display location count box checked) only when auto select option is set to people only, but not when auto select option is set to people and their area/group/location. 

### Versions

* **Rock Version:** Rock McKinley 12.2 (1.12.2.22)
* **Client Culture Setting:** en-US

**Comment by cwomack** [comment]
@pokes2k Are you able to submit any screenshots of the issue happening as well as the **Check-in Configuration** page? I've attempted to reproduce this following your steps on my local test environment v12.2, but had no issues seeing the room counts on both the **Room List** as well as the **Live Metrics** for people I checked-in.  

I've also tested this on the demo site running version 1.12.2.2 and had the same results.

**Comment by pokes2k** [comment]
@cwomack, thank you for the reply! I will do what I can to clarify. If we use a people only option in the config (as circled below)
![People Only Config_LI](https://user-images.githubusercontent.com/77298612/116605131-a34ab180-a8f4-11eb-9e88-66b32c378718.jpg)
this is the final result in check-in (as circled below) for check-in groups that have multiple locations/rooms. In this example, I have 3 rooms available for our 2 year old group, and we get real time room counts as people check-in. Our nursery staff loves this feature because it helps with room balancing on the fly. 
![People Only Room Counts_LI](https://user-images.githubusercontent.com/77298612/116605232-c9705180-a8f4-11eb-93d3-f4ec1db3dfb6.jpg)

However, if we change the config setting to people and their area/group/location (as circled below)
![People Plus Config_LI](https://user-images.githubusercontent.com/77298612/116605570-308e0600-a8f5-11eb-9e1e-3158678ae9b5.jpg)
our nursery staff gets the location detail (a feature they also love) but there's no room counts (as shown below)
![People Plus - No Room Counts_LI](https://user-images.githubusercontent.com/77298612/116605728-659a5880-a8f5-11eb-934a-2d33b2aabde5.jpg)

In both of these examples, I have checked the box for display location counts (as seen below) in the check-in config settings
![Location Count](https://user-images.githubusercontent.com/77298612/116606471-62539c80-a8f6-11eb-9ca0-6a8840d44983.PNG)

Hope this helps! Let me know if you need anything else from me.

**Comment by cwomack** [comment]
@pokes2k Thank you for the follow up screenshots!  I can reproduce what you're referencing now and see that the count is absent from the room depending on what is selected for the **Auto Select Options**.
