### ISSUE TITLE
Scope In Cache Commands Not Working Properly When Inside an IF Tag

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/Rock#4672]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Variables are not available in a cache command when inside an IF tag.

![image](https://user-images.githubusercontent.com/605691/116741178-d94a6d00-a9aa-11eb-8b03-2412f2540798.png)

Also tested on https://rock.rocksolidchurchdemo.com/page/2652. Not how long this page persists, but thought it wouldn't hurt to send it over.

### Steps to Reproduce

1. Go to a Lava Tester
2. Enter the code
```
<h3>In IF Statement</h3>
{% if 1 == 1 %}
    {% assign color = 'blue' %}
    
    Color 1: {{ color }}<br>
    
    {% cache key:'fav-color-test-1' duration:'0' %}
        Color 2: {{ color }}<br>
        {% assign color = 'red' %}
        Color 3: {{color }}<br>
    {% endcache %}
    
    Color 4: {{ color }}
{% endif %}

<h3>NOT In IF Statement</h3>
{% assign color = 'blue' %}

Color 1: {{ color }}<br>

{% cache key:'fav-color-test-2' duration:'0' %}
    Color 2: {{ color }}<br>
    {% assign color = 'red' %}
    Color 3: {{color }}<br>
{% endcache %}

Color 4: {{ color }}
```

4. See that the Color 2 is blank when run inside and IF Tag, but Color 2 is not blank when not run in an IF Tag

**Expected behavior:**

Variables should be available inside a Cache command when inside and IF tag.

**Actual behavior:**

Variables are not available inside a Cache command when inside and IF tag.

### Versions
Tested on Demo Site and admin.oneandall.church
Rock Version: Rock McKinley 12.2 (1.12.2.2) 
Client Culture Setting: en-US

**Comment by allenprell** [comment]
I believe the bug is not just limited to cache tags within if tags but within any tag that creates a scope.  The same problem can be reproduced using code in an include tag.  The fix that worked for me is to modify the Cache::MergeLava function as below.  I don't know the code well enough to determine if this will have any unintended consequences though.

```
diff --git a/Rock/Lava/Blocks/Cache.cs b/Rock/Lava/Blocks/Cache.cs
index 3a70f29561..3ff7a137c6 100644
--- a/Rock/Lava/Blocks/Cache.cs
+++ b/Rock/Lava/Blocks/Cache.cs
@@ -285,10 +285,14 @@ namespace Rock.Lava.Blocks
             // Add variables in the scope (defined in the lava itself via assign)
             if ( context.Scopes?.Count > 0 )
             {
-                foreach ( var item in context.Scopes[0] )
+                foreach ( var scope in context.Scopes)
                 {
-                    lavaMergeFields.Add( item.Key, item.Value );
+                    foreach (var item in scope)
+                    {
+                        lavaMergeFields.Add(item.Key, item.Value);
+                    }
                 }
+
             }

             return lavaTemplate.ResolveMergeFields( lavaMergeFields, enabledCommands );

```
