### ISSUE TITLE
Lava for Person Alias Id and Connector Person Alias Id

### ISSUE THREAD

**Issue by SusanChorney** [SparkDevNetwork/Rock#4673]
[X] 
    

### Description

Lava for Person Alias Id and Connector Person Alias Id work when viewing report but fail when report is exported. 

Report View
![image](https://user-images.githubusercontent.com/83473566/116909995-f97c6500-ac12-11eb-8028-5426ae2572ab.png)

Excel View After Export
![image](https://user-images.githubusercontent.com/83473566/116910102-1add5100-ac13-11eb-835c-212cb5f492ed.png)

### Steps to Reproduce

1. Add this Lava to get person name rather than Person Alias ID:  {{ PersonAliasId | PersonByAliasId | Property:'FullName' }}

2. Export the report

**Expected behavior:** 

Person name to show in exported report

**Actual behavior:** 

Person Alias Id shows in report

### Versions

* **Rock Version:** [Rock McKinley 12.3 (1.12.3.1)]  
* **Client Culture Setting:** [en-US]

**Comment by EthanW96** [comment]
I've tested this on the Pre-Alpha Demo server (running v13) and it is broken as well. The Lava fields in a Report do not appear at all as columns in the spreadsheet export. 
![image (4)](https://user-images.githubusercontent.com/8846891/116913019-98eb2900-ac0e-11eb-8817-10f86e6cae76.png)

This was not an issue in v10.3
![image (5)_censored](https://user-images.githubusercontent.com/8846891/116913476-2595e700-ac0f-11eb-9c2f-951979f2b79a.jpg)

**Comment by allchannelson** [comment]
Exports are missing any sort of LAVA. Even if you put in a simple static field, it doesn't get exported. Shows up fine in the grid.

**Comment by tbunney** [comment]
@allchannelson we are seeing the same issue. Any lava field is not working when exporting reports.

**Comment by bobrufenacht** [comment]
As a possible work around to this issue, the Formatted Field does work for excel export on Reports and allows lava if the lava only uses a single property of the entity type for the report.

**Comment by ethan-sparkdevnetwork** [comment]
Thanks for all the good info. This is fixed in v12.5.
