### ISSUE TITLE
My Account Phone Update

### ISSUE THREAD

**Issue by carriewhite** [SparkDevNetwork/Rock#4678]
* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
On the external "my account" page, all information is being updated correctly except for phone number. When a phone number is edited, the PhoneNumber record is deleted.  When a phone number is added, the PhoneNumber record is not inserted.

Note: this does work correctly on the demo site, which is at 12.2.

### Steps to Reproduce
1. Go to My Account with block settings that include one or more phone numbers
2. Click on "update profile"
3. Update or enter a phone number

**Expected behavior:**
A new PhoneNumber record should be added or updated when the guest updates their number.

**Actual behavior:**
PhoneNumber records are deleted instead of updated and never inserted.

### Versions
Rock Version: Rock McKinley 12.3 (1.12.3.1)
Client Culture Setting: en-US

**Comment by JimMichael** [comment]
Confirmed this on 12.3. Does not occur on 12.2 or earlier. Was not able to test on prealpha as /myaccount page has a Lava error at present.

**Comment by bdeneal** [comment]
As noted by Jim Michael this issue not only deletes the phone number you are trying to edit, but ALL phone numbers for the individual. I can also confirm this issue with 12.3

**Comment by JimMichael** [comment]
Hopefully this gets assigned high priority as it's a data loss issue.

**Comment by nairdo** [comment]
via https://github.com/SparkDevNetwork/Rock/commit/ea5d4190bcf976da95813d5987183c3cbc7cd9d5

**Comment by JimMichael** [comment]
Will this block work on a 12.3 system, in case those whom are at 12.3 and don't want to encouter the bug want to copy it to their instance before 12.4 arrives?

**Comment by nairdo** [comment]
@JimMichael and others, 

We're going to move v12.4 to alpha as quickly as possible, but in the meantime the file for this block (in this [Fix4678.zip](https://github.com/SparkDevNetwork/Rock/files/6437814/Fix4678.zip)) is compatible with v12.3 and can be deployed immediately as you see fit.  You just need to replace the existing `PublicProfileEdit.ascx.cs` with that one in the zip file.

**Comment by carriewhite** [comment]
The fix worked perfectly.  Thank you!
