### ISSUE TITLE
Entity Administration Bug on viewing security for Step

### ISSUE THREAD

**Issue by radams22** [SparkDevNetwork/Rock#4683]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported? 
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When clicking the lock button within the entity administration for Steps, we receive an error message. 

### Steps to Reproduce

1. Go to 'Security'
2. Click on 'Entity Administraton'
3. Filter by 'Step'
3. Click on the lock on Entity Type 'Rock.Model.Step'
4. See the error message

Video attached on the demo site for 13.0.
https://user-images.githubusercontent.com/72230330/118015346-cc6a3980-b319-11eb-8891-d428cc002bc8.mp4

**Expected behavior:**

We should see who has view/edit/administrate access to Steps

**Actual behavior:**

We receive a "That was not supposed to happen" error message

### Versions

* **Rock Version:** [12.2,12.3,13.0]
* **Client Culture Setting:** [US-EN]

**Comment by cwomack** [comment]
@radams22 I'm able to reproduce the exception you've reported here and it looks like it's been happening since v10.3 of Rock.  While it's no doubt a bug that we see the exception being thrown, I'm curious to know how you ended up finding this in the first place (since it seems no one else did for so long).  

What was the goal of securing the Steps as a whole/entity, rather than certain pages or step types?

**Comment by radams22** [comment]
@cwomack  Funny thing you ask, I'm about to submit another bug issue which is how we found this one. We were attempting to figure out why people couldn't see badges on connections when security showed they could. So we were running down all the different possibilities and checking the steps (which is one badge they can't see) took us to inspect security and finally to entity administration.

**Comment by cwomack** [comment]
Hey @radams22 , just replied back on the Issue #4684 page for the "View Badges Security Bug." As for this one (#4683), we've got the exception you found added to the queue to be fixed.  Thanks for reporting it to make Rock better!
