### ISSUE TITLE
Prayer List export does not include person's name

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4691]
Reported on behalf of [St Luke lutheran Church](https://stlukemesa.com/)

### Description
When exporting the Prayer Request list to Excel, the person's name is not included in the export

### Steps to Reproduce
1. Go to Prayer List
1. Click on grid's Export to Excel button

**Expected behavior:**

The Excel file includes the person name column from the prayer list

**Actual behavior:**

Person name is not included

### Versions
* **Rock Version:** 12.3 & 13.0 (pre-alpha)
* **Client Culture Setting:** en-US

**Comment by cwomack** [comment]
@azturner I've tried to reproduce the issues on v12.3, 12.4 and v13, but cannot get any errors where the "Person's Name" is not populating in the exported Excel spreadsheet.  Just to confirm we're referencing same thing, is the picture below what you're having issues with?

![image](https://user-images.githubusercontent.com/67726635/119907721-be194180-bf05-11eb-8926-1a5f49d0712f.png)

**Comment by azturner** [comment]
That is my bad. Someone reported it to me and I was looking for it to be listed prior to Campus and didn't see that it is in fact included where you pointed it out. Sorry, we wasted your time on this one.
