### ISSUE TITLE
Sparkline shortcode never loads on HTML block with cache duration

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/Rock#4698]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When using the Sparkline Chart Lava shortcode in an HTML Content block that has a non-zero Cache Duration value, it just displays "Loading..." and the chart is never shown. The dev tools console shows this JS error message:

> Uncaught TypeError: $(...).sparkline is not a function

![image](https://user-images.githubusercontent.com/1696714/119541993-e8230600-bd43-11eb-966c-19e61beabdfe.png)

Possibly related to #4693??

### Steps to Reproduce

1. Add a new HTML Content block to any page
2. Edit the block properties and set the Cache Duration to 600
3. Edit the block content and add a Sparkline Chart shortcode
`{[ sparkline type:'line' data:'5,6,7,9,9,5,3,2,2,4,6,7' ]}`
4. Reload the page (might take 2 reloads to get a cached version)
5. Notice that the chart never loads
6. Hit F12 to see the JS error message

**Expected behavior:**

A cached version of the sparkline chart should be displayed.

**Actual behavior:**

The chart is never loaded because of a Javascript error

### Versions

* **Rock Version:** Rock McKinley 11.4 (1.11.4.3)
* **Client Culture Setting:** en-US
* **Also tested on demo site:** Rock McKinley 12.4 (1.12.4.1)

**Comment by garrettjohnson** [comment]
@JRichmond27 Hi Jeff, in order to add the javascript needed to the `<head>` of the page, Rock needs to run this shortcode without block caching. To get around this limitation we recommend either adding the script library JS manually to the page (i.e. `<script src="file.js"></script>`, or implementing the lava cache tag directly within the shortcode.

Pseudo Code Lava Cache Tag Example
```
{[ googlemap ]}
    {% cache key:'map-cache' duration:'3600' %}
        {% for marker in markers %}
            [[ marker location:'{{ marker }}' ]] [[ endmarker ]]  
        {% endfor %}
    {% endcache %}
{[ endgooglemap ]}
```

**Comment by JRichmond27** [comment]
@garrettjohnson, thanks for the explanation!

In that case, I might suggest adding a note to the Sparkline Chart shortcode description that tells people that it won't work with block caching just to avoid any future confusion.
