### ISSUE TITLE
"Future Follow-up Complete" activity is misleading

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4699]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

The version 12.3 update [included a change](https://github.com/SparkDevNetwork/Rock/commit/a4c4966bde38e7e682ef646d92bad899d2ca5bb9#diff-cb50e2a3206318149b8c13f4770478c92aaefabe7aef18f4c355d8d0b878b4c2) to the Connection Request Workflow Trigger job that results in a new activity type of "Future Follow-up Complete" being added whenever a connection request reaches the future follow-up date. This is causing confusion to users since they think that the needed follow-up action has already been completed when in fact it just means that is now time to begin the future follow-up.

![image](https://user-images.githubusercontent.com/548180/119716468-02c7ae80-be1a-11eb-8498-2d0d4d0108ff.png)

### Steps to Reproduce

1. Add a new connection request with a state of future follow-up and specify a follow-up date of today.
2. Run the "Connection Request Workflow Triggers" job.

**Expected behavior:**

Connection request becomes active again and does not show a "Future Follow-up Complete" activity. If an activity needs to be added, perhaps it could say something more like "Re-Activated for Follow-up" or "Future Follow-up Date Reached".

**Actual behavior:**

Connection request becomes active again and does show a "Future Follow-up Complete" activity

### Versions

* **Rock Version:** v12.3
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
We'll take a closer look at this.

**Comment by SteveSwaringen** [comment]
This blew up my inbox this morning too. We updated to 12.3 two days ago and this morning everyone is in a panic.

**Comment by MichelleDyke** [comment]
YES!  This is creating confusion with my staff.  Would love to get the label changed to something that makes sense to our staff like "Future Follow-up Date Reached".
