### ISSUE TITLE
API Call People/GetByEmail/{email} returns 404 when email contains "+" character

### ISSUE THREAD

**Issue by taylorbrooks** [SparkDevNetwork/Rock#4701]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
Emails in Rock can contain "+" characters but the API returns errors when using that email to search Person records.

### Steps to Reproduce

1. Go to Bill Marble's profile on Rock's demo site
2. Update his email from "bill.marble@fakeinbox.com" to "bill.marble+bingbong@fakeinbox.com"
3. Use Postman or a REST client and issue a GET request to `http://rock.rocksolidchurchdemo.com/apiurl/People/GetByEmail/bill.marble+google@fakeinbox.com`
4. See an HTML error page is returned with a 404 response

**Expected behavior:**

I would expect Bill's record to be returned as a valid JSON response with the status of 200.

**Actual behavior:**

An error page is returned as an HTML response is returned with a response of 404.

### Versions

* **Rock Version:** [Enter Rock version here]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by ethan-sparkdevnetwork** [comment]
Hello @taylorbrooks ,

This is a security feature of IIS7 and up. The plus sign is not allowed in the route, but it is allowed in the query string. There are a few ways around this.

You can use the people endpoint and the filter parameter. This will put the encoded plus sign (%2B) in the query string which will make IIS happy. See the API doc one the demo site: https://rock.rocksolidchurchdemo.com/api/docs/index#!/People/GETapi_People
The syntax is case sensitive. the eq is the equality operator. Here is the format and an example:

```
Template: /people?$filter=personProperty eq 'propertyValue'
Raw: http://localhost:6229/api/People?$filter=Email eq 'ted+decker@rocksolidchurchdemo.com'
Encoded: http://localhost:6229/api/People?$filter=Email%20eq%20'ted%2Bdecker%40rocksolidchurchdemo.com'
```

Alternatively you can bypass that security feature by adding the **allowDoubleEscaping="true"** property to the requestFiltering element of your web.config. After making the change the security section should look _similar_ to this:

```
<configuration>
  ...
  <security>
    <requestFiltering allowDoubleEscaping="true">
      <hiddenSegments>
        <add segment="ClearScript.V8" />
      </hiddenSegments>
      <requestLimits maxAllowedContentLength="104857600" maxQueryString="16384" />
    </requestFiltering>
  </security>
  ...
</configuration>
```

**Comment by ethan-sparkdevnetwork** [comment]
@taylorbrooks v12.5 will allow the API call GetByEmail to use a query string to provide the email address.
e.g. /api/People/GetByEmail?email=ted%2Bdecker@rocksolidchurchdemo.com
NOTE: If the plus sign is not encoded it will be changed to a space.
