### ISSUE TITLE
Grade/Graduation Date Calculates Incorrectly on Promotion Date

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4702]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When editing a person's grade on the same day as the configured promotion date (6/1 by default), the Grade/Graduation Year is not showing correctly in the person profile edit. So for example if you change someone's grade to 7th grade and then save your changes, it will then show 6th grade on their profile because the graduation year was set incorrectly.

Here is a video showing the issue: [https://www.dropbox.com/s/9b4guk4u1lf7008/PromotionDate.mp4?dl=0](https://www.dropbox.com/s/9b4guk4u1lf7008/PromotionDate.mp4?dl=0)

### Steps to Reproduce

1. Change the Promotion Date Global Attribute to current day
2. View a person profile of someone who has a grade (i.e. Noah Decker)
3. Note the Grade and Graduation Date
4. Edit the person's record.
5. Change their grade to a different grade
6. Change their grade back to the previous grade. (note that the graduation year will not be the same)
7. Save the changes

**Expected behavior:**

Grade stays the same as it was prior to editing

**Actual behavior:**

Grade is saved differently (it will be one grade lower) than it was previously 

### Versions

* **Rock Version:** v12.3
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
Is this the same issue as https://github.com/SparkDevNetwork/Rock/issues/4533 ?

**Comment by azturner** [comment]
Yes
