### ISSUE TITLE
Font display issues with Firefox 89

### ISSUE THREAD

**Issue by craigmash** [SparkDevNetwork/Rock#4711]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

With the release of Firefox version 89, text is no longer showing on external site when using the default theme font of ""OpenSans", "Helvetica Neue", Helvetica, Arial, sans-serif" WHEN Helvetica is not installed on a computer.

I am unsure if this is a Firefox problem or a Rock problem. Has happened on two users so far that did not have Helvetica installed but did have Arial. All text on the external site would not show. Also effects Communication templates preview since almost the same font stack is the default for those as well.

### Versions

* **Rock Version:** [12.2 (1.12.2.2)]
* **Client Culture Setting:** [ en-US]

**Comment by cwomack** [comment]
Hello @craigmash, is there a specific page or pages that you can reference where this is happening?

**Comment by craigmash** [comment]
Pretty much the entire external site. Specifically, the login or register pages.
