### ISSUE TITLE
Giving Analytics - Data View Options not showing by default

### ISSUE THREAD

**Issue by alyssa-pathway** [SparkDevNetwork/Rock#4712]
### Description
In giving analytics, if filtering by a data view, there are additional filters that should appear once you run the analytics - 

_**Dataview Results**

* Only show people from dataview that have giving data
* Include all people from dataview_

Those additional filters are not showing up automatically, but do show up if you copy the criteria url using the copy/clipboard tool and then paste the link in the url bar.

### Steps to Reproduce
1. Open Giving Analytics
1. Set criteria to however you'd like AND filter by a data view (under advanced options).
1. Click "Update" and run the Details/People portion of the analytics.
1. Notice that the Additional Filters (as described above) do not show.
1. Copy url using clipboard button in giving analytics.
1. Paste url into url bar and go to results page. 
1.  Additional Filters will now show.

**Expected behavior:**

The data view additional filters should show up when I run the analytics, not after copying the criteria and running it through the url.

**Actual behavior:**

Data View additional filters only show if I copy the link and paste.

### Versions
* **Rock Version:** [11.3]
* **Client Culture Setting:** [en-US]

**Comment by shauncummings** [comment]
This fix has been cherry-picked into v12.5.
