### ISSUE TITLE
Send Email With Events Workflow Action - On Failed Activity Broken

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4719]
### Description

While attempting to use the *Send Email With Events* workflow action, I discovered that the *On Failed Activity* option does not seem to work... at least not when using the core SendGrid HTTP email transport.

### Steps to Reproduce

1. Create a workflow and add the Send Email With Events action to the Start activity.

2. Add another activity and call it "Email Bounced" or similar, with an action that does something simple like rename to the workflow to "Bounced!"

3. Configure the Send Email with Events action with a valid From address and a known bad Send To address. 

4. Configure the Email with Events action to point at your Email Bounced activity for the *On Failed Activity* option.

5. Run the workflow and observe that the workflow never activates the Email Bounced activity and renamed the workflow.

**Expected behavior:**

Bounced emails would be detected and handled correctly by the *On Failed Activity* option in the *Send Email with Events* activity when using the SendGrid HTTP transport.

**Actual behavior:**

All options in this workflow action seem to work correctly *except* for the *On Failed Activity* option. I was not able to test this on demo for obvious reasons, nor was I able to test with Mailgun transport to see if it acts the same, but it for sure breaks when using SendGrid HTTP transport. 

As it stands, the *Send Email with Events* workflow action cannot be used to react to bounced emails it sends.

### Versions 

* **Rock Version:** Only tested on 12.3/124.beta

![image](https://user-images.githubusercontent.com/3903408/122097386-3e301a00-cdd5-11eb-986e-b727f6643b95.png)

**Comment by MichaelAllen** [comment]
I think this case statment just needs to be updated from `bounced` to `bounce` but I don't have a SendGrid account to test this on. https://github.com/SparkDevNetwork/Rock/blob/28e6ca03ba98020c7e45d17a057a98ff914be4af/RockWeb/App_Code/TwilioSendGrid.ashx.cs#L338

SendGrid's other delivery events are past tense (delivered, dropped, deferred, etc.) but, for some reason bounce is different. See: https://docs.sendgrid.com/for-developers/tracking-events/event#delivery-events

**Comment by JimMichael** [comment]
I don't think that's it, because the webbook itself is handling bounced emails correctly outside of the Workflow action. If I send to a bad address, the person's email is very quickly inactivated and you get the expected bounce reason note. I vaguely remember @nairdo talking about the bounce vs. "bounced" usage in the webbook, but whatever it is today sure SEEMs to be working correctly... if it was broken we wouldn't see ANY bounced emails, I'd think.

**Comment by matthewbronkema** [comment]
You're both correct. If the email doesn't exists in the suppressions list the SendGrid API returns "bounce", but when the email is in the suppressions list the SendGrid API returns "dropped". The fix is to handle the bounce case in the ProcessForWorkflow function as mentioned above. We implemented this correctly in the ProcessForRecipient function, but missed updating the ProcessForWorkflow function.

**Comment by JimMichael** [comment]
@matthewbronkema Great, thanks for the details!
