### ISSUE TITLE
(Mobile) Users Logged in With An "Unconfirmed" Account Have Inconsistent Experience

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/Rock#4723]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

I recently noticed that users that are logged in with a user account that is not "Confirmed" are able to access their profile in the app, but {{ CurrentPerson }} is not available in Content blocks and the user is not able to save notes in a Structured Content View. The notes appear fillable, but when the user leaves the notes page and returns the notes are blank. I have not tested all of the other blocks that use the CurrentPerson, but I would expect a similar inconsistent experience.

I have attempted to recreate this issue on the Rock Demo Site currently at V12.2 and while it does allow me to log in using an unconfirmed account it does not have an inconsistent experience on the Rock Demo Site, it acts as if I was fully logged in. However I am able to fully recreate the issue on rockrmslatest.com currently at V13 using [a test app](https://rockrmslatest.com/page/586?SiteId=9) and the Rock Mobile Shell. Based on when I noticed the issue my guess was that the inconsistency was introduced in V12.3 or most likely V12.4, which is what I am currently running. The ability to log in using an unconfirmed account has probably existed from the very beginning. I am going to post in the #mobile thread of RocketChat to see if any other V12.3 or V12.4 users are experiencing the same issue.

### Steps to Reproduce

1. Login To App Using User account that is not confirmed.
2. Access page that uses {{ CurrentPerson }} in Content Block
3. See that {{ CurrentPerson }} content is not presented in Content Block
4. Access page with Structured Content Block
5. See that Notes are fillable on Structured Content Block but when you return to the page notes are not presented. (Upon checking via lava or SQL you will see that a Note was not saved for that Person.
6. Access page with Profile Details
7. See that Profile Details are presented for the user

**Expected behavior:**
- In order to mirror functionality of the website a user is not able to log in using a "Unconfirmed" user account.
- In the event that a user is logged in and their account becomes "Unconfirmed" I would expect that the user would have a similar experience as the website where they are fully logged out of the app.
- Similar to the website it would be ideal that the user is informed that their account is unconfirmed and provide a process for confirming their account.

**Actual behavior:**
- The user is able to log in using an "Unconfirmed" user account.
- In the event that a user is logged in to an "Unconfirmed" account they appear to be logged in in some ways (able to access Profile Details, enter notes) but are not logged in in other ways ( CurrentPerson is not available, notes are not saved).

#### Production
* **: Rock Version:** Rock McKinley 12.4 (1.12.4.1)
* **Client Culture Setting:** en-US

#### RockRMSLatest
* **Rock Version:** Rock McKinley 13.0 (1.13.0.15)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1200625877347876">image.png</a>

**Comment by bscottdavis** [comment]
Thanks for your work on this @cabal95 ! In testing I can see that the changes added to 12.5 resolve the ability to login from an unconfirmed account, but it appears that the other two aspect of the "Expected Behavior" still exist:

- In the event that a user is logged in and their account becomes "Unconfirmed" I would expect that the user would have a similar experience as the website where they are fully logged out of the app.
- Similar to the website it would be ideal that the user is informed that their account is unconfirmed and provide a process for confirming their account.

**Unconfirmed Accounts Not Logged Out Of App**
In the process of Onboarding it is not uncommon to create a duplicate user, in the event that these users are created it is not uncommon for these duplicates to be merged into the original, which "un-confirms" their user accounts. From what I am experiencing these users who are previously logged into the app but have unconfirmed accounts are still somewhat in limbo. {{ CurrentPerson }} does not exist for them, however if they view the Login or Profile blocks it treats them as logged in. In the case of the Login block it does not show the login experience and in the case of the Profile block it shows their personal information. The only way out of this limbo is to click "Sign Out" on the Profile block which will successfully log them out of the app.

**A Process For Confirming Their Account**
For those that do log out of the app there is not a clear way to log back into the app if their account is "unconfirmed". On the website, attempting to log in to an unconfirmed account results in a message like "Thank you for logging in, however, we need to confirm the email associated with this account belongs to you. We've sent you an email that contains a link for confirming. Please click the link in your email to continue." In the app however, logging in to an unconfirmed account shows the standard "Unable to login, your username or password may be incorrect." with no prompt related to their account needing confirmation. If the user was not aware that they previously received an email asking them to confirm their account they would need to register for a new account, which would then be merged as a duplicate , which would then create another unconfirmed account. This would result in them having an unconfirmed account logged into the app which would put them back into limbo as mentioned above.

I would suggest one solution would be to log the user out if it is found to be in this "limbo" state and then if the user attempts to log in to an unconfirmed account it would prompt the user to complete the normal confirmation process.

I realize this is no small feat, but I suppose another ideal solution would be than when it detects that the device is logged into an unconfirmed account to immediately send the user an authentication email or SMS  and then provide a means for the user to input the confirmation code directly into the app.

**Comment by cabal95** [comment]
Hi @bscottdavis, We are still looking into those related situations but they will require some coordination between the Rock Web server and the Rock Mobile code bases to get fully rolled out.
