### ISSUE TITLE
Check Scanner App Confusing Check Number as part of Account Number

### ISSUE THREAD

**Issue by jsw-austin** [SparkDevNetwork/Rock#4725]
Submitting this on Behalf of Crossings Community 

Church in Oklahoma City.

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

![sample check](https://user-images.githubusercontent.com/7400184/122793832-4084ef00-d281-11eb-9367-6d742f1917dd.png)
![crossings sample check](https://user-images.githubusercontent.com/7400184/122793026-58a83e80-d280-11eb-96a1-b0f0de4b0150.png)

### Description

Some banks put the check number and a space then the account number on the micr.  The Rock Check Scanner is reading this as part of the account number, which results in it not recognizing the account number and matching that to the appropriate person.

### Steps to Reproduce

1. Go to check scanning app
2. scan a check like the picture above and match it to a person
3. Scan another check from the same person
4. Notice that the second check isn't matched to the person

**Expected behavior:**
When multiple space separated numeric values are found, take the longer one as the account number.

**Actual behavior:**

When multiple space separated numeric values are found, spaces are ignored and the check number is considered part of the account number

### Versions

Rock Version: 12.4
Rock Check Scanner: 1.10.4
Client Culture Setting: en-US

**Comment by adamhann** [comment]
For what it's worth, we took a batch of 20 checks and scanned them into our production environment (v11.4), and then took the same batch and scanned them into our staging environment. We could not replicate this issue described above. All of the checks we scanned we people who were already matched except for one. 

I'm not saying there isn't an issue, but we wanted to test this to see how bad it was before upgrading and frustrating our accounting team. :) In our limited test, things were fine.

**Comment by jsw-austin** [comment]
@adamhann, did any of the 20 have the check number and then the account number rather than account number and then the check number?

**Comment by adamhann** [comment]
@jsw-austin No, I just checked and all of them have some sort of combination of the check number being at the end of the string of routing and account numbers.

**Comment by nairdo** [comment]
@jsw-austin We've received an example check (which appears to not have a separator code between the account and check number in the MICR) and we're going to see if there is anything we can do to possibly detect (and deal with) the situation.  We'll be looking at this in week or to once we wrap up the upcoming 12.5 punch-list.  We'll let you know if we believe there is anything we can do.

**Comment by MikeDPeterson** [comment]
@jsw-austin We are able to reproduce this issue with the Canon CR-50 (and probably the other Canon check scanners).  What type of scanner are you able to reproduce this with?
