### ISSUE TITLE
Check- In Incorrect Name Displayed

### ISSUE THREAD

**Issue by carriewhite** [SparkDevNetwork/Rock#4727]
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When checking in multiple individuals from the same family, one individual's name is displayed when the group selection is displayed for each individual.  This issue was introduced with 12.4. We did not have this issue with 12.3.

### Steps to Reproduce

1. add 2 family members to multiple check in groups
2. check in both of those people 
3. one person's name will be displayed while selecting the group for each person

**Expected behavior:**

Each person's name displayed for the group selection.

**Actual behavior:**

One person's name is displayed for all individuals. 

### Versions

Rock Version: Rock McKinley 12.4 (1.12.4.1)

Client Culture Setting: en-US

https://user-images.githubusercontent.com/70244373/122814149-ab85f400-d288-11eb-9528-6925f05b1946.mov

**Comment by JimMichael** [comment]
I was able to dupe this on 12.4 with two event groups containing me and my wife. My name shows for both people. I think the problem I had duping this in alpha/beta was that I didn't realize it only occurs when there are TWO (or more, presumably) groups to choose from for the same people, which never occurs in our normal check-in scenarios.
