### ISSUE TITLE
Transaction Entry Block Rounds AccountIds Page Parameter Amount to Nearest Integer in V12.4

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/Rock#4730]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/605691/123162284-474c6700-d425-11eb-8657-24ae4b3a6bf3.png)

### Description

The Amount passed into a Transaction Entry Block via the AccountIds page parameter is rounded to the nearest integer in V12.4.  My guess was that this was introduced as part of the new currency support in V12.4. I have double checked to ensure that the Decimal Places attribute of our USD defined value is set to "2" and our Organization Currency Code is set to "USD". I opened and re-saved both to help ensure that both had a saved value rather than just pulling in a default value just to be sure.

Jeff Ward of Simple Donation was kind enough to double check this on his Rock Instance running V12.4 in [this RocketChat thread](https://chat.rockrms.com/channel/troubleshooting?msg=MFEgBgcD82mq3dSGP). The issue does not currently present itself in the Rock Demo Site running V12.3 or RockRMSLatest.com running "V13".

### Steps to Reproduce

1. Go to https://[YourTransactionEntryPage]?AccountIds=1^1234.56 with the "Allow Account Options In URL" option enabled in the Transaction Entry block.
2. See that the amount displayed is "1235" rather than "1234.56"

**Expected behavior:**

Amount shown in the Transaction Entry block is the decimal value rounded based off the currency selected in the Organization Currency Code.

**Actual behavior:**

Amount shown in the Transaction Entry block is rounded to an integer.

### Versions

* **Rock Version:** Rock McKinley 12.4 (1.12.4.1)
* **Client Culture Setting:** en-US

**Comment by bscottdavis** [comment]
I mentioned in the original description and title that this issue only effected V1 of the Transaction Entry Block and not V2. I've now noticed that my Instance of Rock is using an old version of the V2 block that doesn't have the currency support that may have introduced this bug, so the bug may be present in the most recent version of the V2 block that includes currency support.

**Comment by nairdo** [comment]
We were able to track this down to a bug introduced in the CurrencyBox control (used by various Rock blocks) v12.4 and then fixed ([c35f381](https://github.com/SparkDevNetwork/Rock/commit/c35f3b142d2d7c954c6cdf28971e1fbd816ea1c8#diff-3e82115df6b7a2cb54fcd75b44b6bd60f5ecff0d8d0daa2896cc8f54d13a61e1R88)) on June 8th for the upcoming v12.5 hotfix.
