### ISSUE TITLE
File Manager - Ampersand in File Name causes file to be unreadable

### ISSUE THREAD

**Issue by nathanp** [SparkDevNetwork/Rock#4733]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/2023635/123681941-04690580-d810-11eb-83b4-c5f943f8f732.png)

### Description

If a user uploads a file with an ampersand in the file name (e.g. `Sermon1_Look&See_GrowStudents.pdf`), then the file cannot be displayed/read from the server, resulting in the above error screenshot.

### Steps to Reproduce

1. Upload a PDF or JPG file with an ampersand in the file name.
2. Once uploaded, try to download the file.
3. Error will be given.
4. This is happening on our server and the RockSolidDemo server.

**Expected behavior:**

The file can be seen/downloaded.

**Actual behavior:**

Error screen is displayed.

### Versions

* **Rock Version:** Rock McKinley 12.3 (1.12.3.1)
* **Client Culture Setting:** en-US

**Comment by Kwame-Agyei** [comment]
Closed in this [commit](https://github.com/SparkDevNetwork/Rock/commit/67a2b3de3deb82a282048e4f2ff1940bbaeabf95)
