### ISSUE TITLE
Scheduled Content shortcode returns wrong NextOccurrenceDateTime value

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/Rock#4741]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/1696714/125348544-3babdc00-e311-11eb-81b1-a2f1fc325396.png)

### Description

When a recurring schedule is currently live, the Scheduled Content lava shortcode returns the wrong value for `NextOccurrenceDateTime`. Instead of returning the date and time of the *start* of the next occurrence, it returns the date and time of the *end* of the next occurrence instead.

When the schedule is not live, the returned value contains the correct next start time.

### Steps to Reproduce

1. Create a recurring schedule that starts 30 minutes before the current time with a duration of 1 hour
2. Create an HTML block and add the following lava. Replace the `scheduleid` value with the ID of your new schedule.
```
Current Datetime: {{ 'Now' | Date:'M/d/yyyy h:mm tt' }}<br><br>
<strong>Scheduled Content Output:</strong><br>
{[ scheduledcontent scheduleid:'26' showwhen:'both' ]}
    Schedule: {{ Schedule.Name }}<br>
    IsLive: {{ IsLive }}<br>
    OccurrenceEndDateTime: {{ OccurrenceEndDateTime }}<br>
    NextOccurrenceDateTime: {{ NextOccurrenceDateTime }}
{[ endscheduledcontent ]}
```
3. Save the block, reload and notice that the schedule is live and the next occurrence date time actually lists the ending time for the next occurrence

**Expected behavior:**

If I'm understanding the shortcode's documentation correctly, when a schedule is live, the `NextOccurrenceDateTime` value should show the start time of the next occurrence

**Actual behavior:**

The `NextOccurrenceDateTime` value shows the end time of the next occurrence

### Versions

* **Rock Version:** Rock McKinley 12.4 (1.12.4.1)
* **Client Culture Setting:** en-US
* **Also tested on demo site:** Rock McKinley 12.2 (1.12.2.2)

**Comment by cwomack** [comment]
@JRichmond27 Thank you for the clear steps, screenshot, and example shortcode to reproduce the issue.

**Comment by JRichmond27** [comment]
@cwomack Absolutely! Thank you for fixing it so quickly!
