### ISSUE TITLE
Event Registration - When adding a new person and indicate "Person is in the same immediate family as", it adds registrant a new and separate family unit.

### ISSUE THREAD

**Issue by Tbrown175** [SparkDevNetwork/Rock#4743]
![image](https://user-images.githubusercontent.com/87831689/126710969-e3a7efae-3e43-40a5-9fde-5c60803d5ba9.png)

![image](https://user-images.githubusercontent.com/87831689/126711187-93cb0076-59ad-430d-a1ea-6aa54daabe88.png)

![image](https://user-images.githubusercontent.com/87831689/126711255-85052bcb-9788-4e7b-935c-1fd407b2421b.png)

### Description
_[Champion Forest Baptist Church created an Event Registration for Parent Commitment. The first part of the form captures registrant information and requests the user to indicate whether the registrant is part of the immediate family.  Indicating yes does NOT result in the registrant, a new person, to be added to the family.  Instead, the person is added into a new family unit.  Although the CFBC flow collected additional information, the problem was reproduced on the Rock Demo site with the simple form captured above. ]_

### Steps to Reproduce
1. Create the simple Event Registration form shown above
1. Enter registrant detail for a new person
1. Select a radio button indicating the "Child is in the same household as"
1. Click Next, then Finish
1. Check the Profile for the desired family and the child is not present, then search for the Child's profile and you will find a new family unit.

**Expected behavior:**

_[The child should be added to the same household/family unit as the indicated during the event registration flow.]_

**Actual behavior:**

_[A new family unit is created that ONLY contains the new child.]_

### Versions
* **Rock Version:** [Rock Version: Rock McKinley 12.4 (1.12.4.1)] 
* **Client Culture Setting:** [en-US]

**Comment by karenn-ccbc** [comment]
I also just discovered this on v 12.2. It is kind of a pain when we have a lot of new ones being added to a Musikgarten event.

**Comment by karenn-ccbc** [comment]
What version is this corrected in?

**Comment by ethan-sparkdevnetwork** [comment]
@karenn-ccbc I fixed it in v13.0.
