### ISSUE TITLE
Error merging person from multi-person family

### ISSUE THREAD

**Issue by afewkes** [SparkDevNetwork/Rock#4748]
### Description
When merging a person from a family with more then one person in it, you receive the error - "An error occurred while executing the command definition. See the inner exception for details."  If you move the person out of the family so they are in a family by themselves, you can successfully merge them.  However, you cannot successfully merge the last person left in the family even though they are in a one person family. Duplicates created in a one person family do not have this issue.

### Steps to Reproduce
1. Create a new family with at least two people that are duplicates of existing records - Ted and Cindy Decker for example.
1. Merge the new Cindy Decker with the original Cindy Decker, keeping all of the information from the original Cindy Decker. This merge should fail with a Merge Error box at the bottom of the screen.
1. Move the new Cindy Decker out of the family so she is in a new family by herself.
1. Merge the new Cindy Decker with the original Cindy Decker and it should merge successfully.
1. Try to merge the new Ted Decker (now in a family by himself) with the original Ted Decker and it will fail with the same merge error.
1. Move the new Ted Decker to an existing family (like the Marbles) and then move him to a family by himself.
1. Merge the two Ted Deckers and it should now work.

**Expected behavior:**

Merging someone from a multi-person family should work without any errors.

**Actual behavior:**

Merging someone from a multi-person family produces the Merge Error - An error occurred while executing the command definition. See the inner exception for details.

### Versions
* **Rock Version:** 12.4 and 13.0 - I cannot replicate it on the demo server which is currently 12.2.
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
Made David's fix in 12.7 in commit 31cac089.
