### ISSUE TITLE
v12.4 - Dynamic Data Block as a Person Report with "Wrap in Panel" enabled doesn't contain communication recipients

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4749]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

This occurs only on v12.4. It is a bug with the new _Wrap in Panel_ option of the _Dynamic Data_ block, which wasn't introduced until v12.4. I also tested on v13 (rockrmslatest.com) and this _doesn't_ occur. It seems to only be an issue on v12.4.

When there is a _Dynamic Data_ block with the _Person Report_ option enabled, as well as all of the grid actions, the _Communicate_ button works as intended **unless** the _Wrap in Panel_ feature is enabled. If the _Wrap in Panel_ feature is enabled, the communicate button reports an error that _"Warning Grid has no recipients"_.

### Steps to Reproduce

1. Go to an instance running Rock v12.4 (or go to the demo site and install the Rock updates until it reaches v12.4)
2. Create a new page or go to an existing page and add a _Dynamic Data_ block to it
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/66277785/128062889-19cc3239-8881-4a9a-ace3-f4ccb2891322.png">

3. Turn on block configuration editing in the admin toolbar, then edit the criteria of the newly added block
4. Change the following settings of the block

  - For the _Query_ any query that returns a list with an Id column that contains valid Person Ids will do, but for testing I used this one `SELECT TOP 10 p.Id, p.NickName, p.LastName  FROM Person p`
  - Enable the _Person Report_ option
![image](https://user-images.githubusercontent.com/66277785/128064883-40b865bd-1734-4b4c-b9c9-010d96906b82.png)

5. Save the block and with the results listed, click the Communicate icon in the grid
6. Notice how it successfully loads the Persons from the grid in the new communication
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/66277785/128064939-84b8ce73-d09f-46ad-8f1b-2d82cc335e32.png">

7. Go back to the page with the Dynamic Data block
8. Edit the following block settings:
  - Enable the _Wrap in Panel_ option and give the panel a title
![image](https://user-images.githubusercontent.com/66277785/128066905-5eba32fe-78d6-4d4f-a7a8-075be224641e.png)

9. Save the block and with the results listed, click the Communicate icon in the grid
10. Notice how the grid now gives a warning that the grid contains no recipients
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/66277785/128066936-beaaed2e-95ca-44af-9618-aa7806d825d5.png">

**Expected behavior:**

I would expect that the block would load the grid results into a new communication since there is a valid Person _Id_ column and _Person Report_ is enabled, regardless if the grid is wrapped in a panel or not.

**Actual behavior:**

When the grid is wrapped in a panel via the _Wrap in Panel_ block setting, the grid behaves as if there are no valid communication recipients even when there's a valid Person _Id_ column and _Person Report_ is enabled.

### Versions

* **Rock Version:** [Rock McKinley 12.4 (1.12.4.1)]
* **Client Culture Setting:** [en-us]

**Comment by leahjennings** [comment]
I can confirm that this issue is resolved as of Alpha 1.12.5.1 (v12.5).

**Comment by nairdo** [comment]
It's not 100% to tell without more time, but it looks like it was possibly fixed via https://github.com/SparkDevNetwork/Rock/commit/84900b1792c0b12b2072b7e163691104e859533e.
