### ISSUE TITLE
Paste from Word is in reverse (vertical and horizontal order) when 'bold' is enabled on simple communications

### ISSUE THREAD

**Issue by NikkiAZ** [SparkDevNetwork/Rock#4751]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### Description --A Picture Is worth a Thousand Words
Formatted Word Document with content to be pasted into an email. Highlighted portion is what is intended to be copied and paste in the email.
![](https://user-images.githubusercontent.com/88405795/128093256-47207e3a-6fd9-45d3-9cfd-f7519d4c1ac8.png)

Screen shot from Rock Demo site to recreate bug. From the line "start test" and through to the line "end test" all is bolded. I intend to paste my formatted content between 'start test' and 'end test'
![Screen Shot 2021-08-03 at 3 23 07 PM](https://user-images.githubusercontent.com/88405795/128094014-4cc3cccb-4308-4819-9c9c-434ddecec398.png)

When using the 'Paste from Word' functionality the content seems to match formatting as expected.
![Screen Shot 2021-08-03 at 3 25 22 PM](https://user-images.githubusercontent.com/88405795/128094261-e8426004-6147-463b-a763-dcb4bd4f6d52.png)

But..... once I hit 'insert' in the 'Paste from Word' box I get the following...
![Screen Shot 2021-08-03 at 3 25 44 PM](https://user-images.githubusercontent.com/88405795/128094266-5f9e6ad2-bdb7-4b9e-8c6d-8686304d429b.png)
Not only is my content  in reveres (bottom->up) but it's actually also pasting my verses backwards with the references first and then the scriptures second.

Refer to Issue #4340 for similar bug fixed in v12.0

### Versions
* **Rock Version:** 12.4
* **Client Culture Setting:** en-US

[+ (Communication) Fixed 'paste from word' plugin to no longer reverse text when bold is enabled(Fixes #4751).](https://github.com/SparkDevNetwork/Rock/commit/7442f5b9205eceba179b544e5828ea8ece0cb549)

**Comment by JRichmond27** [comment]
I haven't been able to recreate the exact results shown in this issue, but I am seeing some very strange behavior with the Paste From Word feature. 

Depending on the structure of the HTML that's already in the editor, sometimes the Paste From Word feature only pastes a small portion of what I'm trying to paste, sometimes it does nothing at all, and sometimes it erases everything (including whatever was already in the editor. I haven't been able to figure out any predictable patterns yet.

**Comment by nairdo** [comment]
Possible regression of #4340 (which should have been corrected in v12.0 via https://github.com/SparkDevNetwork/Rock/commit/0f430f97c3a8b90cb79f0a047c101242f3fb27d5).

**Comment by NikkiAZ** [comment]
[THE NEW YOU IN CHRIST.docx](https://github.com/SparkDevNetwork/Rock/files/6956720/THE.NEW.YOU.IN.CHRIST.docx)
 This is the word doc that i am pasting from, just for reference. Not sure if that would change your outcome @JRichmond27

**Comment by NikkiAZ** [comment]
[ Here](https://youtu.be/SldHjNa6XUY) is a video of exactly what i did and the results i got. In this video it actually took me 3 tries to get anything to output and when it did give an output i got the exact output that i reported above. Hope this helps :)
