### ISSUE TITLE
Alpha 1.12.5.1 - Multi-Select (checkboxes) field type is not allowed criteria in conditional workflow form

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4754]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [X] Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

Per the documentation [here](https://community.rockrms.com/documentation/bookcontent/12/225#conditionallogic) scrolling to the _Limitations on Conditional Fields_ section, _checkboxes_ (assuming that is a Multi-Select field) should be an allowed criteria field type for a conditional workflow form. However, a Multi-Select field type is not listed in the dropdown of field criteria on the conditional logic modal.

### Steps to Reproduce

1. On a Rock instance running Alpha 1.12.5.1, go to Admin Tools > General Settings > Workflow Configuration
2. Create a new _Workflow Type_ under any category
3. Give the workflow a name
4. Add the following three attributes:

   1. List (Single-Select)
      - Name: List (Single-Select)
      - Type: Single-Select
      - Values: 1,2,3,4,5

   2. Checkboxes (Multi-Select)
      - Name: Checkboxes (Multi-Select)
      - Type: Multi-Select
      - Values: 1,2,3,4,5

   3. Text
       - Name:  Text
       - Type: Text

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/66277785/128758080-3dfeae72-6d3e-4b69-b381-d9cb614bdc86.png">

5. Add a new workflow action of type _Form_ (under _Workflow Control_) to the _Start_ activity and name it
6. Check the _Visible_ and _Editable_  boxes for all three attributes listed under the form
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/66277785/128758313-fed3da63-53c0-4bca-a7ac-05b422c08747.png">

7. Click the _Logic_ funnel on the _Text_ attribute, then click _Add Criteria_
8. Notice that the only field listed for criteria is _List (Single-Select)_
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/66277785/128759575-bcebc615-2133-46ae-9890-68f6c55adcd3.png">

**Expected behavior:**

Just based off the linked documentation, I would expect that a Multi-Select field type would be allowed criteria for the conditional logic. If not, the documentation would need to be updated.

**Actual behavior:**

Multi-Select field types are not listed as available criteria in the conditional logic of a workflow form.

### Versions

* **Rock Version:** [Rock McKinley 12.5 (1.12.5.1)]
* **Client Culture Setting:** [en-us]

**Comment by leahjennings** [comment]
This is similar behavior to issue #4756, you have to save the workflow first in order for the multi-select attribute to be listed in the dropdown for criteria. It's confusing if you haven't saved the workflow first.

**Comment by MikeDPeterson** [comment]
@leahjennings Yep, both #4754 and #4756 were the same root cause. Thanks again for helping test this!
