### ISSUE TITLE
Alpha 1.12.5.1 - Single-Select conditional workflow field doesn't give control to specify criteria value

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4756]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [X] Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

Per the documentation [here](https://community.rockrms.com/documentation/bookcontent/12/225#conditionallogic), using a _Single-Select_ attribute as criteria for a conditional form field would show you checkboxes on the _Conditional Display Logic_ modal 

### Steps to Reproduce

1. On a Rock instance running Alpha 1.12.5.1, go to Admin Tools > General Settings > Workflow Configuration
2. Create a new _Workflow Type_ under any category
3. Give the workflow a name
4. Add the following two attributes:

   1. List (Single-Select)
      - Name: List (Single-Select)
      - Type: Single-Select
      - Values: 1,2,3,4,5

   2. Text
       - Name:  Text
       - Type: Text

<img width="1674" alt="image" src="https://user-images.githubusercontent.com/66277785/128761181-b18bcd3c-8b74-4bb9-b184-1c6b4d56749b.png">

5. Add a new workflow action of type _Form_ (under _Workflow Control_) to the _Start_ activity and name it
6. Check the _Visible_ and _Editable_  boxes for both attributes listed under the form
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/66277785/128761239-da48803e-ce5c-4c14-a3da-f0c3dc0dd0aa.png">

7. Click the _Logic_ funnel on the _Text_ attribute, then click _Add Criteria_
8. The drop-down should auto-populate the _List (Single-Select)_ attribute
9. Notice that I don't have any options to specify what the _List (Single-Select)_ attribute should be:
![image](https://user-images.githubusercontent.com/66277785/128761673-fd5db273-bda5-4874-9a22-4917ff0d39c4.png)

**Expected behavior:**

Since a field of type _Single-Select_ is an allowed attribute type for conditional criteria, I expect to see the values as checkboxes in that row to specify my logic for that conditional field. Based on documentation, this is similar to what I would expect to see:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/66277785/128762058-1cb92cbb-bc88-43f4-93e4-26daa46b780b.png">

**Actual behavior:**

When the attribute chosen for criteria is a _Single-Select_ field type, you aren't given the controls to specify any specific values you want that to be.

### Versions

* **Rock Version:** [Rock McKinley 12.5 (1.12.5.1)]
* **Client Culture Setting:** [en-us]

**Comment by leahjennings** [comment]
Ah, you have to save the workflow first in order for the values to appear as criteria. I understand the attribute values haven't been written to the database yet, but it is confusing if the workflow hasn't been saved and you are trying to add criteria on that field.

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/f71d03f3c2b307fc2032dd8124708e33bbc81939 (same fix as #4754)
