### ISSUE TITLE
Alpha 1.12.5.1 - New Captcha field type doesn't display correctly when added as End of Registration attribute

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4760]
#### A Picture Is worth a Thousand Words
**What it looks like categorized as _End of Registration_ (this is the bug)**
![](https://user-images.githubusercontent.com/66277785/128922557-e4271c2c-d4a5-4730-a6d2-3077a39b5af4.png)

**What it looks like categorized as _Start of Registration_ (this is what I would expect it to look like)**
![](https://user-images.githubusercontent.com/66277785/128929038-eac0a984-318d-4ab8-9927-0907de503d82.png)

### Description
When testing the new _Captcha_ field type, I found that it doesn't display correctly when it's added as a _Registration_ attribute with category _End of Registration_ so it shows up after the _Registrant_ info.  Adding it at the beginning of the _Registration_ with category _Start of Registration_ works correctly, it's just when it's at the end.

### Steps to Reproduce
_**These steps assume that the Google ReCaptcha site key and secret key have been configured under Global Attributes. For reference, we are using Google reCAPTCHA type:v2 Checkbox.**_

1. Go to a Rock instance running Alpha 1.12.5.1
1. Click on Tools > Event Registration
1. Create a new Registration Template and give it a name
1. Add a new _Registration Attribute_ then Save the Registration Template
  * **Name**: Please verify you aren't a robot
  * **Field Type**: Captcha
  * **Categories**: End of Registration
  * **Require a Value**: checked
  * ![](https://user-images.githubusercontent.com/66277785/128929692-c08e3d95-64db-4e2a-99d1-ed9818b98837.png)
1. Create a new instance of the template just created, give it a name, and then click Save
1. Click on the _Linkages_ tab of the new instance created
1. Create a new Linkage and give it a _Public Name_ and _Url Slug_
  * ![](https://user-images.githubusercontent.com/66277785/128928273-15e008a6-3c9c-4f87-89f7-7d4641481936.png)
1. In a new window, navigate to `https://yourrockurl.com/registration/urlslug` where `urlslug` is the slug created in Step 7
1. Enter 1 registrant, then your first and last name in the form and click Next
1. Notice that the Captcha field doesn't display
![](https://user-images.githubusercontent.com/66277785/128929836-eaa2859d-8ea3-4586-8c2d-e9b91a1a4950.png)

**Expected behavior:**

I would expect the Captcha field to display properly regardless of its linear position in the form.

**Actual behavior:**

The Captcha field doesn't display correctly when it's positioned at the end of the form as a _Registration Attribute_.

### Versions
* **Rock Version:** [Rock McKinley 12.5 (1.12.5.1)]
* **Client Culture Setting:** [en-US]

**Comment by MikeDPeterson** [comment]
@leahjennings Thanks for finding this issue and explaining the reproduction steps!
