### ISSUE TITLE
The "Prevent Duplicate Email/SMS" option is unavailable when creating communication from list

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4761]
Submitted on behalf of World Outreach Church

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When creating a communication from the "New Communication" menu option there's an optional checkbox that can be used to prevent duplicate email/SMS addresses. However, when creating a communication from any grid, you cannot select that option because the navigation does not allow you to get back to this screen.

![image](https://user-images.githubusercontent.com/548180/128933474-13320f55-fd66-41f9-8118-979be4c513b4.png)

### Steps to Reproduce

1. Go to Communication Wizard page
2. Edit Block Settings and enable the "Show Duplicate Prevention Option"
3. Go to any list of people (any grid)
4. Create New Communication from that list of people

**Expected behavior:**

You would still be able to select the "Prevent Duplicate Email/SMS" option

**Actual behavior:**

You cannot select the option because the screen is never displayed.

### Versions

* **Rock Version:** v12.4
* **Client Culture Setting:** en-US

**Comment by azturner** [comment]
FYI, William Waterhouse also submitted this as in [enhancement idea](https://community.rockrms.com/ideas/1656/the-prevent-duplicate-email-sms-checkbox-is-not-available-when-creating-communication-from-list) on the Rock community site.

**Comment by nairdo** [comment]
Update: David, thanks for the link to the Enhancement/Idea board. We're looking into this as a possible inclusion for v14, but we'll be tracking it via that [Prevent Duplicate Email/SMS Checkbox](https://community.rockrms.com/ideas/1656/the-prevent-duplicate-email-sms-checkbox-is-not-available-when-creating-communication-from-list) idea, so I'll close this out here.
