### ISSUE TITLE
Alpha 1.12.5.1 - Exception immediately post upgrade, Rock won't start.

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4762]
### Description

I have been unable to upgrade my test copy of production instance from 12.4 to 12.5 alpha1. The upgrade ends up at the "Eureka!" success screen, but pressing Restart results in this exception (I captured as much of the exception that shows... there's nothing I cut off)
![image](https://user-images.githubusercontent.com/3903408/129050588-7a29ffb2-f1c3-4309-b841-bf1ea0f4bd5a.png)

This is what I see in the RockExceptions.csv after the upgrade:
![image](https://user-images.githubusercontent.com/3903408/129050732-f7490794-862a-42fa-81d6-4f3a7ccf846c.png)

We _are_ using the Cloudinary plugin and Rock Shop says I'm on version 2.1. I'm not skilled enough to know if this is somehow related to the Cloudinary plugin, or if that's just a symptom of the apparent "duplicate key" problem in the exceptions log.

**Comment by JimMichael** [comment]
This does appear to be related to my Cloudinary install, because when I look up that Guid in the Attribute table I get back:
![image](https://user-images.githubusercontent.com/3903408/129052406-67bd37f1-889b-43ec-93b0-91c6d7cc5702.png)

**Comment by JimMichael** [comment]
I'll also add the I use the _Storage Mover_ plugin and have in the past moved files )like Person Photos) from db/local to Cloudinary via that plugin. Maybe that has something to do with the conflict?

**Comment by ethan-sparkdevnetwork** [comment]
This was due to an error in the 12.5 update package which interfered with the plugins. I have corrected the problem. Thank you very much for your help @JimMichael!
