### ISSUE TITLE
Connector Duplicated in Drop-Down Selector

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4763]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:
    [X] Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    [ ]Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

I have been unable to duplicate this on demo despite multiple attempts over multiple versions. I am creating a bug report because now several people in the community are experiencing this issue. 

On Connection Opportunities where I am also in the Connector Group, my name appears twice in the Connector drop-down. Even though my name appears twice in the drop-down, only 1 of them actually works as intended. If I select the wrong one, then the blue "dot" does not show as the request is assigned to me. 

I have verified that there is only one of me in our DB and I am only in the Connector Group 1x, with a role of `Member`.

This began with the addition of the `Connection Request Board` block in v12.0. This is happening on the Connection Request Board block (`page/770`). For the Connection Request Detail block (`page/408`), this same problem occurs if I click the Connector to change it on the main view, but it does _not_ occur when I actually edit the request on this page.

Here is a link in chat where other users are experiencing the same thing: https://chat.rockrms.com/channel/engagement?msg=iiY2Eh7pzbTCeYi35

#### A Picture Is worth a Thousand Words

Connection Request Board block:
![Screen Shot 2021-08-12 at 08 15 34](https://user-images.githubusercontent.com/23226974/129195196-1d7f3559-40a0-43c3-aa8a-e974f0e25d87.png)

Connection Request Detail block after clicking the edit button:
![Screen Shot 2021-08-12 at 08 15 01](https://user-images.githubusercontent.com/23226974/129195207-aaf066a4-f77c-41a5-a36b-57a3b35b9c97.png)

Connection Request Detail block by just clicking on "Connector" to change the connector without clicking edit:
![Screen Shot 2021-08-12 at 08 24 05](https://user-images.githubusercontent.com/23226974/129196116-aabd3916-0994-406a-9d73-69e3378547a0.png)

### Steps to Reproduce

Unsure how to duplicate this issue, but it began in v12.0 after the addition of the Connection Request Board block.

**Expected behavior:**

I would expect my name to only appear one time.

**Actual behavior:**

My name appears twice, and one of the selections does not work properly.

### Versions

* **Rock Version:** [v12.0 - v12.5]
* **Client Culture Setting:** [en-US]

**Comment by cwomack** [comment]
Adding comment for reference that this could be similar issues to #4632 and #4752.
