### ISSUE TITLE
Self Attendance Entry Block not honoring location

### ISSUE THREAD

**Issue by MargaretMailhiot** [SparkDevNetwork/Rock#4766]
.![](https://user-images.githubusercontent.com/80711825/129483287-25301aec-ceb5-4e9c-a7b8-9e5cb371c7b9.png)

### Description
[Description of the bug or feature. Include screenshots if applicable.]

### Steps to Reproduce
1. With the Attendance Self Entry Block I have created a separate page for each campus with each location selected, however, the attendance is being recorded for the alpha location no matter which page I check in from. I have a schedule set for each location in check-in. So in this screenshot it is showing our Plainfield location, but on the person record, it is recording it as Aurora. Both Aurora and Plainfield have a 9:00 am schedule set. It will not check in to Plainfield until it is 9:00 am or after.

1. [Second Step]![](https://user-images.githubusercontent.com/80711825/129483287-25301aec-ceb5-4e9c-a7b8-9e5cb371c7b9.png)
1. 

![](https://user-images.githubusercontent.com/80711825/129483301-564adab7-6a14-45b7-825a-66b6bbb13597.png)
![](https://user-images.githubusercontent.com/80711825/129483314-6f3af55f-010d-46bd-a229-e5d902506584.png)

**Expected behavior:**

I would expect that the attendance would record for Plainfield since that is the location designated on the self-attendance entry block and it has the 9am schedule set for it.

**Actual behavior:**

All attendance is being recorded for Aurora since it is alpha

### Versions
* **Rock Version:** 12.3
* **Client Culture Setting:**

**Comment by rutledgek** [comment]
I believe this is related to this bug https://github.com/SparkDevNetwork/Rock/issues/4661 Location parameters can cause the block to fail, but the block also uses the first available check-in group for the configuration.  The only workaround I have found is to end up creating different configurations for the locations.

**Comment by cwomack** [comment]
@MargaretMailhiot are you able to provide a screenshot of your **Named Locations** under _Admin Tools > General Settings Named Locations_?

**Comment by MargaretMailhiot** [comment]
<img width="203" alt="Screen Shot 2021-08-23 at 9 32 22 AM" src="https://user-images.githubusercontent.com/80711825/130465747-e26b9357-29b1-4b23-9451-0c3e99057c63.png">
