### ISSUE TITLE
Registration Conditional Attributes Not Working

### ISSUE THREAD

**Issue by stphnlee** [SparkDevNetwork/Rock#4772]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![show-conditional](https://user-images.githubusercontent.com/902855/129787392-2d745c7a-884b-4ef5-84ff-b413cbd62d82.png)

### Description

When adding a conditional form field filter on registration template registrant form, the conditional field doesn't show up when the condition is met unless you go to another page and then back.

### Steps to Reproduce

1. Create a new registration template
2. Add fields to the Registrant Form 
![registrant-form-fields](https://user-images.githubusercontent.com/902855/129787898-f3492820-471b-4583-9836-aa28c368bb44.png)
3. Set conditional logic using the Form Field Filter
![form-field-filter](https://user-images.githubusercontent.com/902855/129788729-382649de-bb0c-4dfa-88e0-67593da4aa78.png)
4. Create a registration using this registration template

**Expected behavior:**

I expect that the conditional field will be revealed when the condition is met.

**Actual behavior:**

The field is not revealed unless I go to another page on the form and then back to the page with the conditional field.

### Versions

* **Rock Version:** 12.5
* **Client Culture Setting:** en-US

**Comment by mikedotmundy** [comment]
I can confirm this is happening on v12.5 on our dev server, but not on v12.4.

**Comment by cwomack** [comment]
@mikedotmundy and @stphnlee are either of you able to confirm if this is solely tied to using "Toggle" as the _Control Type_? It appears the issue is on v12.4 even, but if the Control Type is changed to checkbox or drop down, then the issue is resolved on both versions.

**Comment by mikedotmundy** [comment]
I can confirm that this is happening on v12.5 after a `Single-Select` field. On our v12.4, it functions normally.

**Comment by mikedotmundy** [comment]
<img width="1075" alt="Screen Shot 2021-08-20 at 15 14 52" src="https://user-images.githubusercontent.com/23226974/130282832-b63729b6-d317-4574-97d1-aaa258ebd529.png">

**Comment by mikedotmundy** [comment]
<img width="1176" alt="Screen Shot 2021-08-20 at 15 15 35" src="https://user-images.githubusercontent.com/23226974/130282967-5eb15065-e59f-4153-adac-d6352dd6bc8e.png">
<img width="1554" alt="Screen Shot 2021-08-20 at 15 15 41" src="https://user-images.githubusercontent.com/23226974/130282968-43e6f303-bf65-47c9-a60d-e2f81022ea55.png">

**Comment by asdf1nit** [comment]
I can confirm that there is an issue with the toggle on 12.5 and 12.4. However selecting another method, dropdown or checkbox, works correctly.

@mikedotmundy Single select works on my system however my system displays different. I have 3 values for a 2 value single select, the 3rd being none. I'm not sure how you hid that value but I thought it was worth a mention.

Single Select Setup
![image](https://user-images.githubusercontent.com/18108765/130286248-397ac2a6-8832-4b28-a1c9-379a018c0bb4.png)

Single Select Display
![image](https://user-images.githubusercontent.com/18108765/130286286-5ef3a4a6-d5f3-4dc4-8c2e-ed145645e954.png)
