### ISSUE TITLE
Step Deletion from profile on list view without permissions

### ISSUE THREAD

**Issue by radams22** [SparkDevNetwork/Rock#4775]
[DeleteStepsonProfileBug.zip](https://github.com/SparkDevNetwork/Rock/files/7025985/DeleteStepsonProfileBug.zip)

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

Anyone can delete a step from a person's profile while on the steps tab and in the "List" view. They do not have to have permission in order to do so. I have tested this in V12.4, and V13 using a test record with only Staff Like access, and the page set to view only. If you go to the actual steps page in Rock, with the same person, they are unable to delete steps there. But again, they can if they are on the person's record. 

### Steps to Reproduce
I recorded a video showing the steps I took. 

1. Go to demo site
2. Find a persons record that you can create a login with
3. Change that person's permissions to only view steps, no edit or administrate permissions. 
4. Go to the steps page and find a program and find a person within the step program. 
5. See if you can delete a step (again, make sure security is set to view access only)
6. Go to the same person's profile (the one you attempted to delete the step from in steps)
7. Go to the step tab
8. Find the step program
9. If in card view, change to list view
10. See if you can delete the step

**Expected behavior:**
I would expect that "View" access would only allow the person to view the step, not delete the step. To me that means I would have "Edit" access, as that is editing the step. Viewing should only be what it says, to view. 

**Actual behavior:**

I am able to delete a person's step from their profile, even though I am unable to delete a step from the step page.

### Versions
V12.4 and V13 are the versions I have tested this on.

* **Rock Version:** [V12.4]
* **Client Culture Setting:** [English]
![image](https://user-images.githubusercontent.com/72230330/130331591-8f7b222a-81af-48a3-9257-16935f41033f.png)
****
![image](https://user-images.githubusercontent.com/72230330/130331597-5c697c47-0cab-4756-b92e-4e9df0f543e7.png)
![image](https://user-images.githubusercontent.com/72230330/130331606-3ddb757f-bbe9-4a3f-b054-42e4ad3e599f.png)
![image](https://user-images.githubusercontent.com/72230330/130331630-dbdacbc4-8e50-4752-acc2-2a226bd44485.png)
![image](https://user-images.githubusercontent.com/72230330/130331635-01816601-9149-4c7b-91a2-4c0749ceaae1.png)
![image](https://user-images.githubusercontent.com/72230330/130331653-b98a5792-c54e-417a-a29d-12a1e2f887e5.png)
[DeleteStepsonProfileBug.zip](https://github.com/SparkDevNetwork/Rock/files/7026004/DeleteStepsonProfileBug.zip)

**Comment by nairdo** [comment]
FYI: For completion sake, we recently added another change https://github.com/SparkDevNetwork/Rock/commit/5750c9e04ef709a0553d2fb866f3322afbbb3976 that will adjust the way Step security is inherited and added another security 'action verb' called "Manage Steps" that will provide more control over who could be allowed to manage (add, edit and delete) step participants.  By default, **Steps** will now inherit security from its **Step Type** and the **Step Type** will inherit security from its **Step Program**.
