### ISSUE TITLE
Event Registration Fee Logic

### ISSUE THREAD

**Issue by tylerberens** [SparkDevNetwork/Rock#4781]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
   
![image](https://user-images.githubusercontent.com/57304560/132571157-33ea36f5-b568-4c47-915e-7142c50b635f.png)
![image](https://user-images.githubusercontent.com/57304560/132571113-28d7b7db-b72d-42af-8647-cba63258adcc.png)
### Description

We are trying to create a registration for childcare where the cost is $5 for one child and $10 max per family. I was trying to accomplish this with fees but the maximum available parameter only works if quantity is enabled.

### Steps to Reproduce

1. Create an event with a fee like the screen shot above
2. When navigating through registration, the maximum available isn't respected

**Expected behavior:**

I would expect the registration to hide the fees after the maximum available fees were hit.

**Actual behavior:**

The fee gets applied per person.

### Versions

All
en-us

**Comment by cwomack** [comment]
Hey @tylerberens.  Hoping I can clarify what you're looking to do with the registration fee before marking this as a bug.  If you're looking to only have a fee within a registration template only be applied per person up to a certain quantity of people (say up to 2 kids per your example above), would the below configuration accomplish your goal?

There's a few other ways to probably set this up, but just a quick example:

![image](https://user-images.githubusercontent.com/67726635/132596690-04b16903-43bc-4e62-8ab8-0343bfbb49dc.png)

![image](https://user-images.githubusercontent.com/67726635/132596802-8c3ffb35-7468-4145-9050-6f2b37597db5.png)

![image](https://user-images.githubusercontent.com/67726635/132597032-3292076e-e9e0-47f5-b898-522feb5ed420.png)

![image](https://user-images.githubusercontent.com/67726635/132597009-00805621-c08d-48a9-8ec8-e7a333e301eb.png)

**Comment by karenn-ccbc** [comment]
@tylerberens we work around this by using Discounts as well. So you can auto apply a discount of a certain amount when there are more than 2 registrants. You could make the cost of the "event" $5 and then auto apply a discount of $5 for any registrant over 2 as one option instead of using fees.
