### ISSUE TITLE
Schedule Toolbox (Signup) Schedules Showing 'Filled' When They Are Not

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4785]
### Description

There seems to be a problem with the way the Schedule Toolbox is determining when a Schedule (under the Sign Up tab) shows as "Filled." It's possible for a schedule to show as filled even when there are 0 people signed up for that group/schedule. This occurs when multiple groups with scheduling enabled _use the same location_ , such as a Campus.

![image](https://user-images.githubusercontent.com/3903408/133473078-c9e8112c-b707-4fec-95e3-d8bd5ae6a02a.png)

### Steps to Reproduce

I set up a scenario on prealpha.rocksolidchurchdemo.com in the hopes it lives there long enough to be seen by core team.

1. Under Group Viewer I added 3 people to Serving Teams | Children's and under Meeting Details of the Group added a location like so: 
![image](https://user-images.githubusercontent.com/3903408/133473519-068798fd-095c-4b72-bccb-601877e9f11e.png)

2.  I added 3 people to the Greeters group and under Meeting Details verified the location looks like so:

![image](https://user-images.githubusercontent.com/3903408/133474307-75439808-c519-4d01-ab5d-8ded77454658.png)

3. Note that both groups are using the Main Campus location and their 4:30 schedules have a max of 2 people. 

4. On the Children's group, I clicked the Group Scheduler icon and added two people to the 9/18 4:30 schedule:
![image](https://user-images.githubusercontent.com/3903408/133474710-4764317c-f143-42e7-b90a-71035fa47a96.png)

5. As Alisha Admin, I went to https://prealpha.rocksolidchurchdemo.com/ScheduleToolbox and observed that the Group Alisa is in (Greeters) now shows "filled" even though there are _no people in that group scheduled for that 9/18 date+time_
![image](https://user-images.githubusercontent.com/3903408/133475019-bd39026b-54c3-4bbc-9d29-bdcac43dd859.png)

6. Go back to Children's group  | Group Scheduler and remove one person from the 9/18 4:30 schedule. Now refresh the Schedule Toolbox as Alisha Admin and observe that the 9/18 4:30 schedule for the _Greeters_ group is no longer "filled", because a slot was freed-up from a completely different group.

**Expected behavior:**

Groups that share the same Location would have independent schedule maximums and no knowledge of each other.

**Actual behavior:**

Groups that share the same Location *seem* to affect how Schedule Toolbox calculates that a schedule is "filled", and anyone scheduled in *any* group at the same location+time "counts toward" the max for every group's individual scheduled maximum.

### Versions

* **Rock Version:** 12.4+

**Comment by JimMichael** [comment]
I'll also add that this has been confirmed by one other person in Rocket.Chat. https://chat.rockrms.com/channel/group-scheduling?msg=dr3jmLdxgNzKwmW3n

**Comment by drew-mcclain** [comment]
Our church ran into a similar but slightly different problem, relating to multiple locations tied to the same group. If the first location is at its maximum for a given location, it ignores all subsequent locations and shows the schedule as "filled" and prevents volunteers for signing up to other locations.

If other locations in the group further down the respective list are at their max number, this behavior does not occur; it is only "filled" and closed off if the first location is at its max. This behavior occurs even if no other group has the given location attached, hence is different from the above description.

**Comment by karenn-ccbc** [comment]
Apparently this also impacts each location during a schedule and only looks at the first location to see if it is full. It is allowing sign ups over the max number for locations.  https://chat.rockrms.com/channel/group-scheduling?msg=m5c7RARiRznPtKfwm
![image](https://user-images.githubusercontent.com/35667472/134234541-531e8acd-827e-4294-bfd8-d17baea35f84.png)
![image](https://user-images.githubusercontent.com/35667472/134234560-51b66f56-a026-473b-9f48-6408300d8ae6.png)
![image](https://user-images.githubusercontent.com/35667472/134234644-81efee4c-6226-46c1-afb6-5533bdc2453e.png)
