### ISSUE TITLE
v12.5 Creating duplicate workflows whenever form is submitted

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4789]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Any workflow with a user entry form action is creating a duplicate workflow whenever the form is submitted. The new workflow is then processed and original workflow remains in running state with the form action not being completed.

We've seen this causing issues with the PMM v2 background checks as that workflow checks for any other running instances of workflow and warns user that a background check is already in process. We've also seen it creating duplicate person records in other workflows as it is running same activity on multiple workflow instances.

If activity with form is assigned to user/group on initial run, that workflow will also still be on their dashboard after initial processing since it is the duplicate workflow that gets processed and the original workflow stays at same state with form being uncompleted. If user selects that workflow from their dashboard the issue does not occur (probably since workflow id is in the query string at that point).

### Steps to Reproduce

Create a new workflow with one "Person" attribute and two activities. 
The first Activity should have three actions.
The first action should set the person attribute to current person. The second action should assign the activity to the person attribute. The third action should display a form (doesn't need any fields), and the submit button should activate the second activity.
The second Activity should just complete the workflow.
![image](https://user-images.githubusercontent.com/548180/134185738-ac81be86-b8d3-4ad9-8510-4a88c835a5fd.png)

2. Run the workflow
3. Click the "Submit" button on the first form

**Expected behavior:**

Only one workflow instance is created and it completes after clicking submit button and workflow does not appear on current user's dashboard.

**Actual behavior:**

There is a duplicate workflow instance created and completed, but the original workflow is still open and processing and still appears on user's dashboard. If they click the item on their dashboard, they will see the original workflow's form but when clicking submit again another workflow is created and completed.

### Versions

* **Rock Version:** v12.5
* **Client Culture Setting:** en-US

**Comment by cwomack** [comment]
@azturner, I greatly appreciate all the research, testing, and screenshots!
