### ISSUE TITLE
Registration Form Filters Changed after 12.5 Upgrade

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#4792]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

This is not a bug I have been able to reproduce reliably, but we have now had two clients whose upgrades from 12.4 to 12.5 have changed the Form Field Filters to different/wrong values.  We have upgraded other clients who had filters with no issues.  The field that the filter is pointing to gets changed.  In one specific case it was changed to the first field on the form instead of the 12th field on the form (from a multi-select to a text field as well).  However, a second filter on the same system but different registration was unchanged.

In case it helps anyone, I'm using this SQL to find which registrations have conditional fields.

Select DISTINCT t.Id As RegistrationTemplate, t.Name, a.Id, a.Name, ff.FieldVisibilityRulesJSON From Attribute a
Inner Join RegistrationTemplateFormField ff on a.Id = ff.AttributeId
Inner Join RegistrationTemplateForm f on f.Id = ff.RegistrationTemplateFormId
Inner Join RegistrationTemplate t on t.Id = f.RegistrationTemplateId
Inner Join AttributeQualifier q on q.AttributeId = a.Id
Where FieldVisibilityRulesJSON Is Not Null and ff.FieldVisibilityRulesJSON != '{"RuleList":[],"FilterExpressionType":1}'

### Steps to Reproduce

1. Check on which registrations have Form Field Filters
2. Upgrade to 12.5 from 12.4
3. Check the Form Field Filters and they have changed

**Expected behavior:** 

The Form Field Filters remain unchanged.

**Actual behavior:** 

Filters changed to unexpected and wrong values

### Versions

* **Rock Version:** 12.5
* **Client Culture Setting:** Azure hosted

**Comment by bobrufenacht** [comment]
It looks like there is a migration issue.  In the RegistrationTemplateFormField table, prior to upgrade the FieldVisibilityRulesJSON field contains
{"RuleList":[{"ComparedToRegistrationTemplateFormFieldGuid":"3b204a50-1195-47c0-9085-a7d60f488fdd","Guid":"39870d24-79e5-4ace-89ef-c99bba32ad0d","ComparisonType":0,"ComparedToValue":"Two Day 3-Year-Old $230 per month or $2&comma;070 per school year"}],"FilterExpressionType":1}

After the upgrade, when you "fix" the problem manually the FieldVisibilityRulesJSON column contains
{"RuleList":[{"ComparedToFormFieldGuid":"3b204a50-1195-47c0-9085-a7d60f488fdd","Guid":"39870d24-79e5-4ace-89ef-c99bba32ad0d","ComparisonType":0,"ComparedToValue":"Two Day 3-Year-Old $230 per month or $2&comma;070 per school year"}],"FilterExpressionType":1}

It looks like the "ComparedToRegistrationTemplateFormFieldGuid" text needs to be changed to "ComparedToFormFieldGuid" but is not being updated.

**Comment by cwomack** [comment]
@bobrufenacht, I tried updating from a Rock environment on v12.4 (that included Registration Templates that contained some various conditional form field filters) to v12.5 per your steps above. 

You mentioned that this is hard to reproduce reliably, but I saw no changes in the database (per the SQL you provided) or unexpected behavior on the Registration Forms.  Is there by chance some screenshots you could share of how your Registration Template is configured and maybe the types of fields you're using within the Registrant Form?

I'm wondering if it's only certain fields that were impacted that I'm just not using in my tests.  Appreciate any follow up comments/screenshots in advance so we can zero in on what the issue is.

**Comment by bobrufenacht** [comment]
The only visible difference is that the field in the filter is the wrong field.  This seems to happen more when there are two field filters in the same form.  Both of them show the same value and it seems to be whichever one comes first on the form.  But it is inconsistent.  Of the 6 upgrades I'm familiar with, 3 had the problem, 2 did not and 1 didn't have any filters.

**Comment by nairdo** [comment]
Since 12.7 does not have a firm release date, if one is in a bind and wants the fix ASAP, this simple SQL will 'correct' the issue too:

```Sql
UPDATE [RegistrationTemplateFormField] 
SET [FieldVisibilityRulesJSON]  =  REPLACE([FieldVisibilityRulesJSON], 'ComparedToRegistrationTemplateFormFieldGuid', 'ComparedToFormFieldGuid') 
WHERE [FieldVisibilityRulesJSON] LIKE  '%ComparedToRegistrationTemplateFormFieldGuid%'
AND [FieldVisibilityRulesJSON] NOT LIKE '%ComparedToFormFieldGuid%'
```
