### ISSUE TITLE
Custom Parlot grammar to extend Fluid?

### ISSUE THREAD

**Issue by sebastienros** [SparkDevNetwork/Rock#4794]
You took the time to understand how it works and customized the grammar to your needs, you made my day, thank you.

**Comment by jonedmiston** [comment]
@sebastienros thanks for the feedback, and thank you for developing this incredible library!

**Comment by MrUpsideDown** [comment]
@sebastienros - As a developer who has worked fairly closely with the Parlot and Fluid libraries, I'd also like to add my appreciation for the amazing work you have done here. You have a gift for designing powerful and accessible frameworks, and we are really blessed by the product of your genius and hard work - thank you!
