### ISSUE TITLE
Truncated Html Column in Attribute Matrix can break Page Layouts

### ISSUE THREAD

**Issue by tcavaletto** [SparkDevNetwork/Rock#4802]
Submitted on behalf of Fellowship Bible Church

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/5482014/136228049-a9163c54-4c37-4378-ad6f-695060dc4f8a.png)
![image](https://user-images.githubusercontent.com/5482014/136228108-10cfee27-6d99-4dad-9f50-4ac477b859cd.png)

### Description

When you go to edit mode on an entity with an attribute matrix, the matrix loads as a series of rows that a user can click on to edit the matrix item. When one of the columns is html with layout code ( divs / tables), that column is truncated off, which excludes any closing tags the html has. This breaks any layouts on the page.

I can think of two solutions:
1) Display the full value if the field type is HTML
2) scrub HTML tags from the value being displayed in the row

### Steps to Reproduce

1. Add an attribute matrix with an html field
2. Add a matrix attribute set to that template onto an entity ( content channel item, group)
3. Go to one of the entities and populate a matrix item with html that includes 'layout' tags (divs, tables)
4. Save the Matrix Item
5. See Error

**Expected behavior:**

The value should be truncated and handled in a way that doesn't break surrounding layouts

**Actual behavior:**

The closing html tags are truncated, breaking the page layout

### Versions

* **Rock Version:** [Enter Rock version here]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by cwomack** [comment]
@tcavaletto, any chance you could specify the Rock Version and share the HTML that was used to produce the bug?

**Comment by jonedmiston** [comment]
@tcavaletto can you confirm this is still an issue on v16. Below is an example on a Content Channel Item edit screen with the HTML from above.

![image](https://github.com/SparkDevNetwork/Rock/assets/548178/c288e8dc-8e9e-407e-8fd0-91b980d368fc)

**Comment by jonedmiston** [comment]
Closing due to no response. Feel free to re-open if you think this is still an issue.
