### ISSUE TITLE
Rock 12.6 - Event occurrences greater than 12 months from today's date show N/A in "next start date" column.

### ISSUE THREAD

**Issue by fousttn** [SparkDevNetwork/Rock#4812]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/25514048/138448143-aa95dd8d-1779-427c-a652-96df16e61794.png)
![image](https://user-images.githubusercontent.com/25514048/138448216-dc404659-318d-4a65-9150-9ecb19e89e2a.png)

good morning!  i posted this in #bugapoolza community chat initially and was recommended to bring it over here instead.  

(Using Rock version 12.6.)....when we create multiple event occurrences of the same calendar event (which we need to do in order to connect a separate event registration for each event occurrence), once the event date is beyond 12 months out, it shows up in the event occurrence list for that event with an N/A in the next start date column instead of the date 13 or 14 months (or more) from now. 

i created an event on the demo rockserver this morning that demonstrates it called "monthly dinner at the cliffs"  you will see 3 of the occurrences that have a start date beyond 12 months from now that show N/A in the Next Start Date column.

### Steps to Reproduce

1. go to calendar.  Create an event.
2. create an event with an event occurrence for this month.
3. copy that event occurrence and change the event date to 13 months from now and save it.
4. See error in the list as shown in the screen shots above - N/A displayed in the next start date field for events greater than 12 months from today's date.

**Expected behavior:**

Show next start date for each event occurrence in the list - no matter if it is greater than 12 months from today's date or not.

**Actual behavior:**

Occurrences that have a start date greater than 12 months from today's date show an N/A in the next start date field.

### Versions

* **Rock Version:** 12.6
* **Client Culture Setting:** Church.

**Comment by ethan-sparkdevnetwork** [comment]
The code was written to search for the next occurrence within the next year. Extended this to two years to catch events that are more than 12 months out.
