### ISSUE TITLE
Rock Cleanup - Match Nameless Person Exception

### ISSUE THREAD

**Issue by cfunkdev** [SparkDevNetwork/Rock#4813]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

An exception is getting thrown on line 1853 of the Rock Cleanup job occasionally when the matched existing record has a null person attribute value that is populated on the nameless person

**Expected behavior:**

Null attribute values would be handled.

**Actual behavior:**

A null reference exception is thrown, and job will continue to produce a nameless person warning until the record is manually merged.

** Exception Message ** 
Quartz.SchedulerException: Job threw an unhandled exception. ---> Rock.Jobs.RockJobWarningException: RockCleanup completed with warnings ---> System.AggregateException: One or more exceptions occurred in RockCleanup. ---> Rock.Jobs.RockCleanup+RockCleanupException: merge nameless to person:Object reference not set to an instance of an object. --- End of inner exception stack trace --- --- End of inner exception stack trace --- at Rock.Jobs.RockCleanup.Execute(IJobExecutionContext context) in C:\_Development\Rock_12\Rock\Jobs\RockCleanup.cs:line 284 at Quartz.Core.JobRunShell.Run() --- End of inner exception stack trace --- [See nested exception: Rock.Jobs.RockJobWarningException: RockCleanup completed with warnings ---> System.AggregateException: One or more exceptions occurred in RockCleanup. ---> Rock.Jobs.RockCleanup+RockCleanupException: merge nameless to person:Object reference not set to an instance of an object. --- End of inner exception stack trace --- --- End of inner exception stack trace --- at Rock.Jobs.RockCleanup.Execute(IJobExecutionContext context) in C:\_Development\Rock_12\Rock\Jobs\RockCleanup.cs:line 284 at Quartz.Core.JobRunShell.Run()]

### Versions

* **Rock Version:** 1.12.6
* **Client Culture Setting:** en-us

**Comment by MikeDPeterson** [comment]
@cfunkdev Do you have the stack trace that includes the mention of line 1853? Or a maybe screenshot? I want to make sure I can reproduce the same thing you are running into.

**Comment by cfunkdev** [comment]
@MikeDPeterson  I don't have a stack trace that mentions 1853 directly, I forgot to grab that when I was stepping through the code and it threw the error.  I have actually transitioned back to the SECC team, so I am not going to be able to reproduce it in  Lakepointe's environment.  @SteveSwaringen  may be able to reproduce and get the stack trace though.

**Comment by MikeDPeterson** [comment]
@cfunkdev OK, no problem, I think I see the problem on 1853, so that it helpful. Thanks!

**Comment by SteveSwaringen** [comment]
@MikeDPeterson , the stack trace didn't have a line number reference in it. (I believe the releases we build for our production server have that level of detail cut out.) It only referenced a NullReferenceException from an Entity Contains method call (I'm going from memory here ... those exceptions have been expired from our logs) in the procedure that comprises line 1853. Chris traced the error to that line by reproducing the exception in a debug environment.

If it helps, the context of the exception was running the Rock Cleanup job and it was while it was trying to merge nameless person records.
