### ISSUE TITLE
TransactionList Filtering By TransactionCode

### ISSUE THREAD

**Issue by taylorbrooks** [SparkDevNetwork/Rock#4815]
Requested on behalf of Bayside Church

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
The Transaction List filter for `TransactionCode` requires an exact match. If your `TransactionCode` has extra spaces or characters you will not be able to find those transactions. If you want to search for Transactions with a partial string, you are unable to do so.

![CleanShot 2021-10-26 at 15 39 12@2x](https://user-images.githubusercontent.com/117657/138957561-95b96a50-90b1-46d4-8dba-2c474b21d37f.png)

This should be a simple change [here](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Finance/TransactionList.ascx.cs#L1806):
![CleanShot 2021-10-26 at 15 45 25](https://user-images.githubusercontent.com/117657/138958303-69a67815-1206-4f51-9519-e6bcfa923e5e.png)

### Steps to Reproduce

1. Go to https://rock.rocksolidchurchdemo.com/page/83
2. Type in a partial term to the `TransactionCode` filter
3. Click "Apply Filter"
4. Notice the transactions you expected to appear, do not.

**Expected behavior:**
If I put in a partial string in the filter box for `TransactionCode`, it should find all the Transactions that contain that string in their `TransactionCode` field.

e.g. "bcd" in the `TransactionCode` filter should find Transactions with TransactionCodes of:
- "abcdef"
- "bcdasdf"
- "1234bcd567"

**Actual behavior:**
If I put in a partial string in the filter box for `TransactionCode`, it finds only the Transactions that have an exact match for the `TransactionCode` field.

e.g. "bcd" in the `TransactionCode` filter finds Transactions with the `TransactionCode` "bcd"

### Versions

* **Rock Version:** develop branch
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Hi @taylorbrooks I saw your PR. We understood where the change would be made, we were just not in agreement over changing that field from an equals (==) to a contains.

**Comment by taylorbrooks** [comment]
Thanks @nairdo, what is your suggestion to us?

**Comment by nairdo** [comment]
Hi Taylor (@taylorbrooks) there are a few concerns, including: was the impact performance tested? (_there are performance implications**_); policy doesn't allow us to accept PRs from partners; this is a feature-change not a bug fix; etc.  If we were going to enhance this block, we would likely create an option to flip from fast search (`==`) to a slow search (`Contains`).  But I'll just suggest you open this as an enhancement request on the Ideas board at https://community.rockrms.com/ideas.

Thanks!

** These are some statistics from running on two real systems:
System YYY (6,167,000+ records): was 6ms → now 8,613ms  -- 1,435 times slower
System ZZZ  (2,557,900+ records): was 6ms → now 243ms -- 40 times slower

(_Side note: We recently came across this [interesting/related tweet](https://twitter.com/dan_abramov/status/1463718359262973953?s=11) that we also think is good reading for future PRs from eligible submitters._)
