### ISSUE TITLE
Page Parameter Filter block doesn't leave Group filter cleared if another filter field has a value

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4816]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![Screen Recording 2021-10-28 at 3 44 47 PM](https://user-images.githubusercontent.com/66277785/139325063-f771ef78-509c-4538-92e6-6d1ec52f9bfa.gif)

### Description

Whenever you have a `Page Parameter Filter` block with a filter of type `Group` that has a value selected and at least one other filter that has a value selected (I used `Single-Select` in my testing), if you click the "x" next to the group to  empty that filter and then click the "Filter" button, the block leaves the `Group` filter populated. The only way to clear that `Group` filter is to click "Reset Filters". If the other filter(s) don't have values and the `Group`  filter is the only one with the value, clicking the "x" and then clicking "Filter" works as expected and the `Group` object stays cleared.

### Steps to Reproduce

1. Go to the demo site
2. Show the Page Zones on the homepage using the admin bar and then edit the _Sidebar 1_ zone
3. Add a `Page Parameter Filter` block to the zone
![image](https://user-images.githubusercontent.com/66277785/139326327-1982534b-e1c9-42cf-a831-ad33c245a28e.png)

4. Edit the block settings of the newly added `Page Parameter Filter` block
5. Add a filter of type `Group` with the default settings
6. Add a second filter, this one type `Single-Select` named `Tag`, then add this as the content: `1^Tag 1,2^Tag 2`
   - The second filter's type I _believe_ is irrelevant, it just needs to have a value. This is how I tested.
![image](https://user-images.githubusercontent.com/66277785/139326776-05bd8793-2295-4f35-b01b-db9178f67436.png)

7.  Click _Save_ on the `Page Parameter Filter` block
8. In the `Group` filter, select the `Global Connector Group`
9. In the `Tag` filter, select `Tag 1`
10. Click _Filter_, notice the block works as expected and the `Group` and `Tag` filters have been passed to the URL
11. Click the "x" next to the `Group` filter to clear its value, leave the `Tag` filter populated
12. Click _Filter_ again

**Expected behavior:**

I would expect the `Group` filter  to remain cleared when the _Filter_ button is clicked after you clear the `Group` filter using the _x_ next to it.

**Actual behavior:**

The `Group` filter is populated with its last value upon hitting the _Filter_  button after it has been cleared with the _x_ next to it. The only way to actually clear the `Group` filter is to click _Reset Filters_ at the bottom of the block.

### Versions

* **Rock Version:** [Rock McKinley 12.6 (1.12.6.1)]
* **Client Culture Setting:** [en-us]

**Comment by JRichmond27** [comment]
I see this has been fixed in v13, so I'm hoping this comment can just be ignored, but just in case... 

This appears to be a problem anytime there's more than one filter of any kind (not just a `Group` filter.) If there are two or more filters and you set values for them, and then try to remove the value for one of the filters, the value will remain. The only way to remove it is to clear all filters.

I just tested using Leah's Steps to Reproduce, but with two `Text` filters instead, and was not able to clear the value from one filter if the other still had a value.
