### ISSUE TITLE
OpenId Connect Integration with ChOP not working

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4817]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
Sometime around the end of September the OpenId Connect integration with ChOP stopped working for us. I have had multiple emails with the ChOP support team to get this issue corrected, however, they are assuring me that it is not something with their system, but instead is something on the Rock side. 

They told me that they (life.church) are running v12.4 and it is working for them. I am on v12.6 which I upgraded to on September 28. However, I know of one other user in the Rock community who is on v12.4 and they are seeing the same error. I also know of one other user in the Rock community who is on v12.6 and is seeing the same issue.

I have this integration setup the same way as the Rock Admin manual describes, but when attempting to login from ChOP, I am greeted with this error message:
![Screen Shot 2021-11-01 at 14 39 46](https://user-images.githubusercontent.com/23226974/139724326-f0ac718b-5504-4062-891f-a66f32b0ff72.png)

Obviously, this error is coming from ChOP before ever being redirected to my Rock site. So that is why I have been troubleshooting with them for over a month now. They did email me back that this was the error message they are seeing in their log:
![Screen Shot 2021-11-01 at 14 47 14](https://user-images.githubusercontent.com/23226974/139724549-368f8922-62ca-4cc3-a76e-6dc162223b5c.png)

We use the Acme Certificate plugin with Let's Encrypt for our SSL, so I am not sure if the change Let's Encrypt made on September 30th had anything to do with this. I did ask the ChOP team to look into that, but they were unable to help me any further with it. (See here: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)

Here are screenshots of my setup:
![Screen Shot 2021-11-01 at 14 56 42](https://user-images.githubusercontent.com/23226974/139726038-9625dccb-f4ef-4118-adfa-4fbebbff0264.png)
![Screen Shot 2021-11-01 at 14 56 59](https://user-images.githubusercontent.com/23226974/139726039-9faad668-df1a-4fd8-b8fd-b9dff48afb7c.png)

I did attempt to setup this integration on the demo site but I was unable to ever get it to work.

### Steps to Reproduce

1. Setup the OpenId Connect Integration between ChOP and Rock. 
2. See the error in the screenshot above when trying to login from the ChOP site.
3. If the error is with Rock v12.5 or v12.6, then make sure that is what you are running. (I am not 100% convinced this is the issue, but that is what ChOP is telling me the issue is.)

**Expected behavior:**

Integration to work.

**Actual behavior:**

Integration does not work.

### Versions

* **Rock Version:** [v12.6]
* **Client Culture Setting:** [en-US]

**Comment by charlottedean** [comment]
We are on v12.4 and can also replicate this issue and have been told that it is something within Rock that's causing the issue.

**Comment by bdaneu01** [comment]
I am the one on 12.6 I am trying to reach out to the acme plug-in too and see if it could be the let’s encrypt side but no response yet.

**Comment by bdaneu01** [comment]
Hello All I have reproduced this on my dev system too running 12.6, en-us

Steps to Reproduce

    Setup the OpenId Connect Integration between ChOP and Rock. "Completed Shows Successful"
    See the error in the screenshot above when trying to login from the ChOP site. "Valid" "Error Instantly at Login button Push internal 503 error from CHoP Server" 
  
Expected behavior:

Integration to work.

Actual behavior:

Integration does not work.

**Comment by nairdo** [comment]
Just to give everyone an update here.  We're working with the Church Online Platform engineering team on this, and it looks like it all _might_ be related to an issue with a library that they are using on their end.  It looks like in late September, that library ran into a bug which can be seen here (https://github.com/nov/openid_connect/issues/63). We'll everyone know once we all know for certain.

**Comment by mikedotmundy** [comment]
Thank you @nairdo!

**Comment by crayzd92** [comment]
ChOP support has informed us that they released a fix around Feb 7, 2022, to address this problem. We have tested it internally and it appears to have solved the issue. Please feel free to reopen the issue if you are still having issues with this. Thanks again for taking the time to help improve the Rock community.

**Comment by notGerryMiller** [comment]
I tried to configure OpenID to work with ChOP yesterday and ran into the same error message. We are running on 13.2.

**Comment by MikeDPeterson** [comment]
@notGerryMiller You probably need to contact their support info@online.church and ask them to reset your Chop login back to the regular login. Then go in with the regular login and setup the OpenID again.   I've had to do that several times when I was trouble shooting this, and I had to do it one more time after they fixed it. After that, it worked again.
