### ISSUE TITLE
Event Registration "Process New Payment" breaks "Add Manual Payment"

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4819]
### Description

When using the internal site to process an Event Registration payment, clicking _Process New Payment_ and then cancelling breaks the UI for the _Add Manual Payment_ function.
![image](https://user-images.githubusercontent.com/3903408/139943217-de0d5835-fa76-4514-a055-bd69942ebda8.png)

### Steps to Reproduce

1. Go to an Event Registration instance that has a cost
2. Add a Registered By and Registrant
3. Click The Payments tab
![image](https://user-images.githubusercontent.com/3903408/139943397-f6e4b9de-0e97-415f-ad49-7f0656a99574.png)

4. Observe that if you click the _Add Manual Payment_ button, you get the expected UI where you can add an amount, summary, currency type etc, and Submitting this form creates a transaction on the Person's record.
![image](https://user-images.githubusercontent.com/3903408/139943627-ec857a79-b4d4-4c39-a0fd-e442460832d7.png)

5. But cancel that form to get back to the Payments form and instead click _Process New Payment_. Now observe a similar form, but this time there is a _Next_ button
![image](https://user-images.githubusercontent.com/3903408/139943804-00715009-b61e-4f9b-8d42-f8c4bebf847e.png)
and clicking that takes you to the expected _Payment Information_ screen where you can enter CC info.
![image](https://user-images.githubusercontent.com/3903408/139943969-5ac2c4ff-aea9-489b-8154-92fdb19052d5.png)

6. Up to this point, everything is normal and as-expected, but now click Cancel on the _Payment Information_ screen to get back to the _Payments_ form. 

7. Now click _Add Manual Payment_ again, and observe that instead of seeing the (exact) UI you saw in Step 4, you see the Expected _Payment Information_ form, but with a _Next_ button instead of _Submit_
![image](https://user-images.githubusercontent.com/3903408/139944278-6effba81-5b6a-45ee-8803-f1bdbddc0420.png)

and even weirder, if you click _Next_ from here, you end up at the credit card entry screen that you should only see when doing Step 5 (Process New Payment) AND the act of clicking _Next_ here actually SAVES the manual transaction, as if in fact it IS the Submit button, but labeled incorrectly... but by doing so you still end up on an unexpected and confusing credit card entry form.

**Expected behavior:**

Clicking _Process New Payment_ on an internal Event Registration payment (and then canceling it) would not interfere with the _Add Manual Payment_ option.

**Actual behavior:**

Both forms seem to share common form controls and interact with each other in unexpected ways when you cancel one and select the other.

### Versions

* **Rock Version:** 12.6

**Comment by cwomack** [comment]
@JimMichael, what payment gateway were you using within this Registration Template?

**Comment by JimMichael** [comment]
NMI

**Comment by dataCollegechurch** [comment]
confirmed using Rock 12.7 and NMI as well.

**Comment by ethan-sparkdevnetwork** [comment]
@JimMichael  I tested this in 16.1 and it is working correctly after the overhaul of the payments tab for hosted gateways in 15.0. I noticed the cancel buttons were missing for the payment options so I added those in 16.1. Let me know if you still see a problem.
