### ISSUE TITLE
Analytics Source Date Missing From Model Map

### ISSUE THREAD

**Issue by jsw-austin** [SparkDevNetwork/Rock#4826]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
  * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![Screen Shot 2021-11-09 at 10 16 26 AM](https://user-images.githubusercontent.com/7400184/140962344-0fb34d13-df59-4c9b-a8d4-fdfc9f8f90a3.png)

### Description
When looking at the Model Map in Rock, under reporting I don't see the entity: Analytics Source Date.  I'd expect that 

### Steps to Reproduce
1. Go to 'Admin Tools:Power Tools'
1. Click on 'Model Map' and then 'Reporting'
1. Scroll down to 'Reporting Models'
1. See error: Notice 'Analytics Source Date' isn't present

**Expected behavior:**
I'd expect 'Analytics Source Date' to be present in the same way 'Analytics Source Giving Unit' is.

**Actual behavior:**

'Analytics Source Date' is absent from the model map.  (I can see it with SQL Map, but shouldn't need a plugin to see this entity.)

### Versions
* **Rock Version: Rock McKinley 12.6 (1.12.6.1) (also checked pre-alpha server running 13.0 and it's not there either)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Although the `AnalyticsSourceDate` model isn't an _actual_ entity** and doesn't implement  `Model<T>` , it is used as a property on other models, so this is an understandable request.  We just don't have a easy solution at the moment without getting too hacky in the Model Map block.  I'll label this as a low priority feature request for now.


** These are the Analytics entities:
```Sql
SELECT * FROM EntityType WHERE [Name] like 'Rock.Model.Analytics%'
```

**Comment by jsw-austin** [comment]
Thanks Nick.  I'm able to work around pretty easy and understand making it a low priority.

**Comment by dynamiclynk** [comment]
Now it's really fixed :)

**Comment by JimMichael** [comment]
Just commenting that we recently upgraded from v12.4 to 13.7 (taking each step slowly, making sure all migrations ran before proceeding, etc) yet do NOT see Analytics Source Date in the model map. Does this issue need to be re-opened?

**Comment by jsw-austin** [comment]
@JimMichael I'm on 13.7 and see it under reporting.

**Comment by JimMichael** [comment]
Yeah, not here.

**Comment by MichaelAllen** [comment]
I am on 13.7 and do not see Analytics Source Date in the model map. 

Looking in the EntityType table on my server it appears that the Assembly Name is NULL: `SELECT * FROM [EntityType] WHERE [Name] = 'Rock.Model.AnalyticsSourceDate'`
<img width="872" alt="Screen Shot 2022-10-31 at 20 50 58" src="https://user-images.githubusercontent.com/282879/199135660-e1d0e870-648f-479a-9f18-f32a34dc0976.png">
Running the same SQL on a server that does show Analytics Source Date in the model map gives a different result:
<img width="1044" alt="Screen Shot 2022-10-31 at 20 51 56" src="https://user-images.githubusercontent.com/282879/199135696-24eb1978-dc44-4557-a872-cb40e778c4d0.png">

**Comment by JimMichael** [comment]
AssemblyName on my Rock.Model.AnalyticsSourceDate is also null

**Comment by bscottdavis** [comment]
I am on 14.0 both my Dev server and my Production Server. 

My production server **does not** have AnalyticSourceDate listed in the model map and **has** a NULL AssemblyName.
My dev server **does** have AnalyticSourceDate  listed in the model map and **does not have** a NULL AssemblyName.

Production Server Null Values:
<img width="992" alt="Clipboard - October 28, 2022 9_02 AM" src="https://user-images.githubusercontent.com/605691/199357311-6b55d39e-0458-4265-8d0e-d05725313ccc.png">

I don't know if it adds any insight, but there is a [thread in RocketChat here](https://chat.rockrms.com/channel/troubleshooting?msg=v8zruETFZzAiC8jhQ) discussing this issue.
