### ISSUE TITLE
Connection List Grid Does Not Show Group Member Status Or Role Next To Group Name

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4830]
### Description

The Current Connections Board (v12.0+), when put into "List" mode, no longer shows the "Group Name **([status] + [role])**  " in the Group column of the grid. Versions prior to v12 that only had the "list" view showed this data in the Group column, which our users came to rely on for certain types of Connections. I am trying to determine if this is a bug, or an intentional design change. 

### Steps to Reproduce

Here is an example of the Connections Board ( _Connection Request Board_ block) in List view  on 12.x:
![image](https://user-images.githubusercontent.com/3903408/142504126-3301bccb-bd98-4096-bede-d4990ba0b5d8.png)

Here is an example of the Connections List (_My Connection Opportunities_ block) pre 12.0:
![image](https://user-images.githubusercontent.com/3903408/142504268-32edeba7-98c8-40fa-a8aa-4dbfbb8ddb83.png)

In either case, if you click into a Connection Request you will see the Status and Role info on the placement group
![image](https://user-images.githubusercontent.com/3903408/142504371-d555fcf6-4578-4fe3-887d-c06fd78d049d.png)

so the information is still there, it's just been removed from the Group column on the grid in 12.x, for some reason.

**Expected behavior:**

For certain types of connection requests, having the group member status and role show on the grid is critical for us... for example, when using the Signup Wizard plugin. In that case, connection requests for multiple teams/ministries appear in the same grid, and the only way to distinguish them easily was to see the role the person is signing up for next to the group name. 

If it's a bug, we'd expect status and role to show on the grid just like it did pre-v12. If it was an intentional change (to save horizontal space?) then I'd expect it should have been made a block setting so orgs could choose the behavior they want on the grid instead of simply removing it.

**Actual behavior:**

Status and Role are now gone from the Group column when in List view, making it impossible to know what role the request is for until you click a request and open it. This is vastly more time-consuming than it used to be where you could see that info at a glance on the grid, and thus know if it was a request you had to deal with in your ministry, or not. Now you have to look at each and every request to get this info.

We've been able to work around this by putting the older _My Connection Opportunities_ block on a different page, only exposing the types of Connections that need this behavior, but we're afraid that block will eventually get out of sync with changes to the back end regarding Connections.

### Versions

* **Rock Version:** 12.0+[Enter Rock version here]

**Comment by nairdo** [comment]
via https://github.com/SparkDevNetwork/Rock/commit/4cf4bfe5a7892296e04915f375901a1216f3de69
