### ISSUE TITLE
Step Program List and Step Type List blocks include / count inactive step types

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4842]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/66277785/143270579-cec563a4-8108-4bd2-ba36-772aeb61e99e.png)

![image](https://user-images.githubusercontent.com/66277785/143271335-ccda1b4d-6062-49cf-a048-5f0cd0271877.png)

### Description
When you inactivate a Step Type within a Step Program, there are a few places it is still included that doesn't seem like it should be.

- The inactive Step Type is listed in the Step Type List block with no capability to filter it out of view
- The inactive Step Type is included in the total number in the Step Types column of the Step Program List block
- Steps taken of an inactive Step Type are included in the Steps Taken column of the Step Program List block

### Steps to Reproduce

1. Go to the demo site
2. Go to People > Steps and click on the _Discipleship Path_  Step Program
3. Click on the _Baptism_ Step Type
4. Add a new Complete Baptism Step for Alisha Admin
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/66277785/143270025-0705636f-6ce8-4412-8c79-0a15ed1f7f8e.png">

5. Edit the _Baptism_ Step Type and uncheck the _Active_ checkbox, then Save
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/66277785/143270146-5ca88a40-fdbd-47bf-b801-5eeed7b47441.png">

6. Click back to the _Discipleship Path_ Step Program using the breadcrumb near the top of the page, notice that the _Baptism_ Step Type is still in the list even though it is not active
![image](https://user-images.githubusercontent.com/66277785/143270588-376bcf8a-1812-428f-9324-72604d11b439.png)

7. Click back to the _Steps_  page using the breadcrumb near the top of the page, notice that the _Step Types_ and _Steps Taken_  columns are including the inactivated Step Type in its numbers
![image](https://user-images.githubusercontent.com/66277785/143271310-613e020a-0b13-4463-803b-78df7f36af2e.png)

**Expected behavior:**

I would expect that when you inactive a Step Type, the following would occur:
  - The inactive Step Type would no longer be listed in the Step Type List block OR there would be an option to filter out inactive Step Types
  - The inactive Step Type would no longer be counted in the total shown in the Step Types column of the Step Program List block
  - The Steps Taken column of the Step Program List block would not count the Steps that are of an inactive Step Type

**Actual behavior:**

- The inactive Step Type is listed in the Step Type List block with no capability to filter it out of view
- The inactive Step Type is included in the total number in the Step Types column of the Step Program List block
- Steps taken of an inactive Step Type are included in the Steps Taken column of the Step Program List block

### Versions

* **Rock Version:** [Rock McKinley 12.6 (1.12.6.1)]
* **Client Culture Setting:** [en-us]

**Comment by Kwame-Agyei** [comment]
Via
