### ISSUE TITLE
NCOA Results data incomplete, Results page throws error

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#4848]
### Prerequisites

* [] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

(Cannot test this on another install without incurring further charges)

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

After running the NCOA process manually on November 1, 2021, the NcoaHistory table was populated with updated addresses but all of the records have 0 for PersonAliasId, FamilyId, and LocationId, which makes it impossible to identify which addresses are supposed to be updated.

### Steps to Reproduce

1. Go to System Settings -> Spark Data Settings
2. Select the following options:
![image](https://user-images.githubusercontent.com/18447084/144118849-f567e2f2-57b9-4e40-ad57-fde1e6051ba8.png)

3. Click Run Manually
4. Wait for NCOA job to complete
5. Go to Tools -> Data Integrity -> NCOA Results

**Expected behavior:**

The page should display the addresses that need attention.

**Actual behavior:**

Received this error:

> InvalidOperationException in System.Core
> Message
> Sequence contains no elements
> 
> Stack Trace
> 
>    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
>    at RockWeb.Blocks.Crm.NcoaResults.ShowView() in C:\websites\Rock\Blocks\Crm\NcoaResults.ascx.cs:line 580
>    at RockWeb.Blocks.Crm.NcoaResults.OnLoad(EventArgs e) in C:\websites\Rock\Blocks\Crm\NcoaResults.ascx.cs:line 87
>    at System.Web.UI.Control.LoadRecursive()
> ...
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolea

This is the point where I looked at the data in the NcoaHistory table and saw that it was incomplete.  I believe the job itself actually threw an error as well but unfortunately the error has been purged since it happened so I can't see the specifics anymore.

We were charged $50 for this run so I have not run further tests on the job itself to see if I could identify the problem.

### Versions

* **Rock Version:** Currently 12.6, NCOA job was run when we were on 12.2
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
This comment is mostly for everyone else who may be looking at this in the future (since Chris and I already spoke via DM to verify this...)

There was an internal issue with the service vendor that provides the NCOA 'Spark Data' service for all the Rock instances.  They have since resolved their API issue and the corresponding Rock NCOA problems have also gone away.  

That vendor has also given us notice that they will be obsoleting their V1 API and asked us to move to their V2 API.  Although we will do that for something like Rock v13 (or possibly even Rock v12.8-or-higher), any organization that does not update to that version of Rock will mean the NCOA service will no longer function (once the vendor performs their final shutdown of that old API).

We'll include an item in the Release Notes and/or a "Heads-up" notice in a future release once all the exact details are settled.

**Comment by nairdo** [comment]
@eddieholeman, I just caught a report that it looks like there was a credential issue with the service on the Spark site. I was just informed it should be working again.

Can you confirm or let us know if you're still seeing a problem?

**Comment by shauncummings** [comment]
@eddieholeman The NCOA service provider had an issue that affected our account.  We believe this has been resolved.  Please let us know if you continue to experience problems (after allowing some time for the job to cycle through the various stages of your report).

**Comment by nairdo** [comment]
FYI: Eddie reported back via another channel that "Looks like it is fixed.".  Thanks @eddieholeman!

**Comment by eddieholeman** [comment]
Thanks so much @nairdo and @shauncummings for your efforts on this. Kentucky Mountain Mission was charged for this service at least 4 times yesterday. Is there a way to nagivate a credit back to them?

**Comment by shauncummings** [comment]
@eddieholeman I believe that is already under investigation, but I have passed this information along to be sure that it gets addressed and appropriate refunds are issued.

**Comment by eddieholeman** [comment]
@shauncummings thanks so much for passing that on. Robbin has already taken care of it.
