### ISSUE TITLE
OpenID /UserInfo Endpoint Doesn't Return any user claims

### ISSUE THREAD

**Issue by vinnyjth** [SparkDevNetwork/Rock#4854]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    *

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

<img width="1123" alt="Screen Shot 2021-12-09 at 3 31 47 PM" src="https://user-images.githubusercontent.com/1637694/145473396-7b4feaa0-744d-44cb-9208-7432595e3c4c.png">

### Description

The OpenID `/Auth/UserInfo` endpoint doesn't appear to return any user info. My assumption was that a user should be able to retrieve any claims they have granted via `UserInfo`, but instead only non-user specific information is returned. I know the user has granted those claims successfully because they appear inside the `id_token`. 

Claims: 
![image](https://user-images.githubusercontent.com/1637694/145473505-89d27e59-0673-4201-855f-96626457dd86.png)

ID Token
![image](https://user-images.githubusercontent.com/1637694/145473866-d58312be-f0cc-4dc5-9b88-e7489bf8e085.png)

UserInfo fetched w/ Access Token
![image](https://user-images.githubusercontent.com/1637694/145474208-f7b43047-5318-46ee-911a-13743eab7057.png)

### Steps to Reproduce

1. Using the OpenID flow, obtain an access_token with all scopes
2. GET `/Auth/UserInfo` with your access_token in the `Authorization` header.

**Expected behavior:**

I receive back a JSON object with all claims included in my token's granted scope

**Actual behavior:**

I receive a JSON object back including only the `sub`, `iss` and `aud` claims. 

### Versions

  ```
Rock Version: Rock McKinley 12.7 (1.12.7.2)

Client Culture Setting: en-US
```

**Comment by bdaneu01** [comment]
> Could this be related? #4817

Yes it is and Thank you @vinnyjth for the more details it's now clearly pointing to a rock for our issue also this is what ChOP was talking about the token is not showing any details just saying there just there if you use the other auth.
