### ISSUE TITLE
Note Notification - View Note Button

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#4857]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
The system email template: Note Watch Notification has a button on line 28 to View the note:

`<p>
 <a href="{{ 'Global' | Attribute:'InternalApplicationRoot' }}{{ note.NoteUrl }}#{{ note.NoteAnchorId }}">View Note</a>
 </p>`

The View Note button currently takes you to the home page of your rock instance and not to the note itself.

### Steps to Reproduce
1 - Create a Note Type
2 - Create a Note Watch Group / Person for that new Note Type
3 - Enter a Note of that type
4 - Receive the email
5 - Click 'View Note'

**Expected behavior:**

I would expect by clicking View Note - you are taken to the note

**Actual behavior:**

You are actually taken to the home page of your rock instance

### Versions
* **Rock Version:** [12.6]
* **Client Culture Setting:** [en-US]

**Comment by cwomack** [comment]
@jcjones37, I was able to reproduce the behavior you described when the URL provided for my "**Internal Application Root**" (under _Admin Tools > General Settings > Global Attributes_) wasn't set properly.  Can you check what yours is set to?  

The Lava within the "Note Watch Notification" email template (under **_Admin Tools > Communications > System Communications_**) leverages the above Global Attribute and might be the culprit.  Once I updated this, I went from being able to reproduce what you're seeing to having the link within the email notification take me right to the Note within the Timeline on a Person Profile. 

Let me know if this helps or if the issue persists!

**Comment by jcjones37** [comment]
Good Afternoon @cwomack Thanks for your help.

My Internal Application Root is set correctly I believe. Here is a screenshot. Is there something I should modify?

![Screen Shot 2021-12-15 at 12 20 31](https://user-images.githubusercontent.com/41912840/146234337-7043bb0f-cef4-4362-a946-32564757b241.png)

**Comment by croske** [comment]
@jcjones37, would you be able to post an example "View Note" link from the Note Notification email that is sent?  I wonder if it is any different than the link I receive when testing this feature.  Thank you!

**Comment by jcjones37** [comment]
@crayzd92 I am so sorry for the delay :( I did some tests and found out... its not doing it on every note type... 

Not sure if this helps or not - 

Working: http://email.rock.cedarcreek.tv/c/eJxlUE1rwzAM_TXJzUG24q9DDh1jt42xw9ityLbSuk2T4iT7_fO20xgI8Xgf4qE0KA866DYPCpQCVEoaADCdY5KYYo_Jh7En1fRQlnjtIicqsTBfu-2zPQ_WGtQIHthqDxikCi6Rd5KDrl7TfohnytNpn8U7lUxh4nVo7EOjVFxut33Okba8zMfCMd8zz9vxtOdU5QYPdY_ejCg5iiQhil4BCCIvhQloJHOIBObbbB_baThv2339yT3V-d_3l3_lsi5zBdJpC9AofFk2fuNRBOPQphFDktg7zYG0NqMFKdm6gL4tw4Vq9lK_8efwFxUmYmY

Not Working:
http://email.rock.cedarcreek.tv/c/eJxlT7tuwzAM_Bp7kyFRD1qDhhZFt3boUHQL9KASJY4dyEq_v2q2ogB5w_HucEwOLNdBj8UBB-Cyr-Gci0kEM0vSIvFoM5owKF63eJkiJV9jJbpM7Xs8uSR80somxTWg1DkICYqyQo2SvE_jF3vzZTneV_bpa_Fhod0N-DwAxO16va8l-la29VAplluhtR2O95L6eZBPHbWcs5kDMi8iMpUNsBC1YQJSRiFIB4u_YnwZF3dq7bY_fK99_vd98PJ9a_RBmfVskyBKqWZSVhobLRmYlUUvCAOM1Z39vq3n_vufmB8V4lyE
