### ISSUE TITLE
FamilySalutation lava broken in v12.7

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#4858]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

Reported on behalf of Mountain Christian Church
### Description

The lava command FamilySalutation is broken in v12.7 (and prealpha).  It always returns "Liquid error: Object reference not set to an instance of an object."

NOTE - This may affect some churches end-of-year giving statements if FamilySalutation is used in the lava template.

### Steps to Reproduce

1. On any html block or in lava tester, put "{{ CurrentPerson | FamilySalutation }}"
2. Run it and it shows the error.

**Expected behavior:**
Return the salutation that includes the adults in the family properly formatted.

**Actual behavior:**
Always gives and error "Liquid error: Object reference not set to an instance of an object."

### Versions

* **Rock Version:** 12.7 and also prealpha.
* **Client Culture Setting:** Azure hosted

**Comment by bobrufenacht** [comment]
It appears this also causes "Combine Family Members" on the Merge Template page to error out when the Merge button is pressed.  It generates an exception with the same error.  So the issue is likely in the underlying C# method.

**Comment by JimMichael** [comment]
Looks like this is the same error https://github.com/SparkDevNetwork/Rock/issues/4849
