### ISSUE TITLE
Registrant deleted on the Registrants tab doesn't get logged

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#4859]
On behalf of Crossings Community Church

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
In this screenshot, there should be another deleted entry at the top. I deleted the registrant from the registration details page and it created the record on row 2. I re-added the registrant and deleted them from the registrants tab and there is no log of it.

![image](https://user-images.githubusercontent.com/12735965/146039570-19890847-016d-4c7f-8e84-70cc1c0b591c.png)

### Steps to Reproduce
1. Register for an event
1. Go to the Registrant tab on the registration instance
1. Delete the registrant
1. Check the Audit log for the registraion

**Expected behavior:**

That the registrant deleted would be logged in the Audit log like it is if the registrant is deleted from the registration details page

**Actual behavior:**

The registrant is deleted with no logging

### Versions
* **Rock Version:** [12.6]
* **Client Culture Setting:** [en-us]

**Comment by crayzd92** [comment]
@KelleyLangkamp We appreciate you taking the time to report this. Unfortunately, we have been unable to reproduce this in v13+ of Rock. We were able to reproduce it once in v12.6 but it would not reproduce again after the first time it happened. If you are able to reliably reproduce this in v13 or prealpha, please reopen the issue with additional steps.
