### ISSUE TITLE
Communication Wizard Email Editor: Block Placements

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#4864]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

When adding column blocks to the email, I have noticed that when adding a multi column block (two, Three, Left or Right) to the end of your wizard, you are unable to add any other blocks below the multi column.  The workaround however, if you place multiple single column blocks in your wizard then drag a multi column block back into your wizard you can place it where you would like. The issue becomes apparent when you are adding blocks in the order you are creating your email and you discover you can not add any other blocks after a multi column block.

This ticket may be related to this ticket: https://github.com/SparkDevNetwork/Rock/issues/4862

### Steps to Reproduce

1. Navigate to People > New Communication
2. Choose Manual List, search for and select Ted Decker, and check the box next to Ted on the list. Click Next.
3. Enter communication name and choose next.
4. Choose the blank template.
5. Enter From Name, From Address, and Email Subject and choose Next.
6. Drag a new single column block into the dropzone.
7. Drag a new multi column block into the dropzone after the single column.
8. Drag a new single column block into the dropzone after the multi column block.

**Expected behavior:**

The newly added single column in step 8 should be able to be added after the multi column block.

**Actual behavior:**

No newly added blocks (single or multi column) can be added after a multi column block has been added.

### Versions

* **Rock Version:** [12.6]
* **Client Culture Setting:** [en-US]

**Comment by crayzd92** [comment]
@jcjones37 Thanks for your input on this one. In troubleshooting this issue we found that using the multi-column layout objects is not quite as intuitive as the single-column layout. When dragging items to appear below a multi-column layout drag them to the far right side of the multi-column item. This will drop a placeholder down below the element indicating it will be placed below. See the screen recording attached here.

![chrome_8ryNgoeRGy](https://user-images.githubusercontent.com/17650211/151058309-a55ebb26-b596-43da-b540-3b952fcc77af.gif)

While this is working, just not as expected, I would invite you to open up an [idea here](https://community.rockrms.com/Ideas) if you'd like to see this enhanced in the future.

Thanks again, and apologies for any inconveniences this may have caused you and your team.

**Comment by jcjones37** [comment]
Understood! Thank you so much!

Jason Jones 
Ministries Project Manager
CedarCreek Church

Need to schedule a meeting? Click HERE<https://calendly.com/jasoncjones37/meeting>.


From: Daniel Vincent ***@***.***>
Date: Tuesday, January 25, 2022 at 15:58
To: SparkDevNetwork/Rock ***@***.***>
Cc: Jason Jones ***@***.***>, Mention ***@***.***>
Subject: Re: [SparkDevNetwork/Rock] Communication Wizard Email Editor: Block Placements (Issue #4864)

@jcjones37<https://github.com/jcjones37> Thanks for your input on this one. In troubleshooting this issue we found that using the multi-column layout objects is not quite as intuitive as the single-column layout. When dragging items to appear below a multi-column layout drag them to the far right side of the multi-column item. This will drop a placeholder down below the element indicating it will be placed below. See the screen recording attached here.

[chrome_8ryNgoeRGy]<https://user-images.githubusercontent.com/17650211/151058309-a55ebb26-b596-43da-b540-3b952fcc77af.gif>

While this is working, just not as expected, I would invite you to open up an idea here<https://community.rockrms.com/Ideas> if you'd like to see this enhanced in the future.

Thanks again, and apologies for any inconveniences this may have caused you and your team.
