### ISSUE TITLE
[Alpha 1.13.0.29] - SMS Conversations block doesn't fail gracefully if I load the page after rights to the selected number are set to deny

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4868]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/66277785/147373534-0ad9760e-2f95-4b17-9806-f5e4a9da3076.png">

### Description

While the circumstances for this to occur may be uncommon, it's still possible. Testing with an administrator account, which by default has access to all SMS numbers in the SMS Conversations block, if I have a phone number selected in the SMS Conversations block and then change the View permissions for that number to be "Deny" for my user account and then reload the SMS Conversations page, I get an exception page.

### Steps to Reproduce

1. On a Rock instance running 1.13.0.29, go to the SMS Conversations page and select an SMS number in the dropdown.
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/66277785/147373470-513701e9-da50-43c7-a041-adac0a4bf319.png">

2. Go to Defined Types, and click the Security button on the same SMS phone number selected in step 1 and change the View permissions to Deny for the user account you are logged in with
![image](https://user-images.githubusercontent.com/66277785/147373514-e2096d64-7694-400f-9b03-d34799c93963.png)

3. Now try to load the SMS Conversations page
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/66277785/147373534-0ad9760e-2f95-4b17-9806-f5e4a9da3076.png">

Here's a screenshot of the exception:
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/66277785/147373552-3069d3d7-6e92-4499-a155-dfb9d254c561.png">

**Expected behavior:**

I would expect that the SMS Conversations block fails gracefully if the CurrentPerson no longer has rights to the last selected number.

**Actual behavior:**

An exception occurs.

### Versions

* **Rock Version:** [Rock McKinley 13.0 (1.13.0.29)]
* **Client Culture Setting:** [en-us]

**Comment by crayzd92** [comment]
@leahjennings Have you seen this again since the initial report?

**Comment by leahjennings** [comment]
@crayzd92 yep, I can reproduce it on our v13.1 production instance.
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/66277785/158372928-99b0c4ca-5045-44b4-91fe-1e1b0a1805b7.png">

**Comment by MikeDPeterson** [comment]
Very like the same issue as https://github.com/SparkDevNetwork/Rock/issues/4919. So this should fix this issue too.
