### ISSUE TITLE
v13 Alpha theme change and save results in bootstrap and less error

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/Rock#4869]
### Prerequisites

* [] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
       *YES*
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
       *NO*
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
       *YES*

#### A Picture Is worth a Thousand Words
![Theme Styler | Rock RMS 2022-01-03 14-18-25](https://user-images.githubusercontent.com/8688424/147976120-3a42ab8d-5bcf-40bc-8ffc-af8dbdcac832.png)

### Description

_When changing the_ Rock _theme an error is thrown, but the process completes (and without an exception)

### Steps to Reproduce

(this was discovered during Alpha testing. I attempted to make a Rock theme change _after_ we upgraded our testing Rock instance to v13 Alpha
1. Go to 'Admin Tools > CMS Configuration > Themes'
2. Click on the 'Rock' theme
3. Change the 'Primary Brand Color' to a different color (I used #ffeb3b )
4. Select the `Save` button
5. See error
6. Examine the exception log... there is no exception

**Expected behavior:**

_When you select save you don't get an error_

**Actual behavior:**

_The change takes effect, but the following error happens:_
![Theme Styler | Rock RMS 2022-01-03 14-18-25](https://user-images.githubusercontent.com/8688424/147976699-dcad7c4b-13f6-420b-abd2-a103aa2600a4.png)

Text form of the error:
```A compile error occurred on bootstrap.less

variable @fa-var-abacus is undefined on line 5 in file '../../../Styles/FontAwesome/_icons.less':
  [4]: .@{fa-css-prefix}-500px:before { content: @fa-var-500px; }
  [5]: .@{fa-css-prefix}-abacus:before { content: @fa-var-abacus; }
       -------------------------------------------^
  [6]: .@{fa-css-prefix}-accessible-icon:before { content: @fa-var-accessible-icon; }
A compile error occurred on connection-request.less

variable @fa-var-abacus is undefined on line 5 in file '../../../Styles/FontAwesome/_icons.less':
  [4]: .@{fa-css-prefix}-500px:before { content: @fa-var-500px; }
  [5]: .@{fa-css-prefix}-abacus:before { content: @fa-var-abacus; }
       -------------------------------------------^
  [6]: .@{fa-css-prefix}-accessible-icon:before { content: @fa-var-accessible-icon; }
A compile error occurred on email-editor.less

variable @fa-var-abacus is undefined on line 5 in file '../../../Styles/FontAwesome/_icons.less':
  [4]: .@{fa-css-prefix}-500px:before { content: @fa-var-500px; }
  [5]: .@{fa-css-prefix}-abacus:before { content: @fa-var-abacus; }
       -------------------------------------------^
  [6]: .@{fa-css-prefix}-accessible-icon:before { content: @fa-var-accessible-icon; }
A compile error occurred on group-placement.less

variable @fa-var-abacus is undefined on line 5 in file '../../../Styles/FontAwesome/_icons.less':
  [4]: .@{fa-css-prefix}-500px:before { content: @fa-var-500px; }
  [5]: .@{fa-css-prefix}-abacus:before { content: @fa-var-abacus; }
       -------------------------------------------^
  [6]: .@{fa-css-prefix}-accessible-icon:before { content: @fa-var-accessible-icon; }
A compile error occurred on group-scheduler.less

variable @fa-var-abacus is undefined on line 5 in file '../../../Styles/FontAwesome/_icons.less':
  [4]: .@{fa-css-prefix}-500px:before { content: @fa-var-500px; }
  [5]: .@{fa-css-prefix}-abacus:before { content: @fa-var-abacus; }
       -------------------------------------------^
  [6]: .@{fa-css-prefix}-accessible-icon:before { content: @fa-var-accessible-icon; }
```

### Versions

* **Rock Version:** 13.0 (1.13.0.30)
* **Client Culture Setting:** en-US

@nate-steil may want to chime in, as he understands CSS, less, etc. better than I

**Comment by smross** [comment]
cc @nate-steil here's the issue I opened. If you have any insight or suggestions on a fix, fire away!

**Comment by nate-steil** [comment]
It looks like the error is happening then the bootstrap.less file id working on imports. There were no differences in the _icons.less file between our production (12.2) and alpha (13) version. 

The files that creates the variables used by the _icons file IS different. I'm not sure whether the abacus icon was deprecated and should be removed from the _icons or if it just needs the variable added back in, but the _variables.less file is different after upgrading to v13 (we went from 12.2 to v13 so it may have been earlier).
From Production (v12.2)
<img width="334" alt="Screen Shot 2022-01-05 at 10 16 18 AM" src="https://user-images.githubusercontent.com/85514054/148252051-47217613-c5f1-4b16-aa9e-9d92c4f8be81.png">

From Alpha (v13)
<img width="362" alt="Screen Shot 2022-01-05 at 10 19 07 AM" src="https://user-images.githubusercontent.com/85514054/148252069-f8032982-2156-4e67-8984-cb172abb3367.png">
