### ISSUE TITLE
v13 Alpha Scheduled Transactions Panel in Contributions Tab Removes Important Functionality

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4871]
### Description

I could not get a response to this in the alpha-test chat channel, so I'm posting it here. If it does not belong, feel free to close. 

The _Scheduled Transactions_ list was moved from a grid in v12 and prior to a "panel" on the right side in v13. While this is visually pleasing, it actually removes important functionality we relied on.

### Steps to Reproduce

1. Go to a person's profile that has inactive scheduled transactions
2. Click on Contributions tab
3. Observe that only Active scheduled transactions show by default, and you have to click _Show Inactive_ to see inactive ones. That's fine.
![image](https://user-images.githubusercontent.com/3903408/148258112-f9bc26a8-3a5e-4384-9030-35dc39abf327.png)

4. However, observe that nothing in the list of inactive scheduled transactions is clickable. What you see is what you get and you cannot get to the _details_ of an inactive transaction anymore.

**Expected behavior:**

Prior to v13, Scheduled Transactions (both active and inactive) were presented in a grid within the Contributions tab
![image](https://user-images.githubusercontent.com/3903408/148258412-6b99d49f-98bf-450d-88b5-d3b8b003c40e.png)

This let them be clicked-on to see the details of the scheduled transaction, which is/was an important forensic tool for us when we needed to track down an issue with someone's giving.

**Actual behavior:**

Now that the Scheduled Transactions have been moved from a grid to a panel, the details (of inactive ones, in particular) are no longer accessible and presumably we'd have to go look up the old scheduled transaction Id under Finance | Scheduled Transactions going forward.

We think this could be addressed by either providing a link on each scheduled transaction back to the details of said transaction, or even make the panel item itself click-able to get to the detail. As it stands, v13 has removed an important usability feature for us and our finance people will not be happy about it. 

I'm posting this during Alpha phase in the hopes it might be addressed before beta, so that we don't have to wait for a future update to fix the problem this has caused. This assumes you agree it's even a problem, though.

Finally, even with no changes to the alpha code, the performance of the _Show Inactive_ (OR _Show Active_) is pretty awful. It takes 8 seconds on my test instance to open a list of 35 inactive scheduled transactions (and _another_ 8 seconds when subsequently clicking _Show Active_ just to get back to the initial view.)

This is in contrast to v12 and prior where the _Entire Contributions tab_ including showing those 35 inactive scheduled transactions takes less than 1sec to render.

### Versions

* **Rock Version:** 1.13.0.29

**Comment by nairdo** [comment]
Although we're still investigating the slow performance when the "Show Inactive" or "Hide Inactive" is clicked, for v13.0 the view-edit button will be visible for active and inactive scheduled transactions.

**Comment by crayzd92** [comment]
Fixed via 837c05caf90739b3adea63dacd6f216c268ee257 in 1.13.1
