### ISSUE TITLE
Universal Search missing results when initiated from Smart Search Block

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#4872]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported? Y
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? Y, Demo site
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting? Y

### Description

When a user submits a universal search for an existing previous last name via the Smart Search block, the expected person result is not returned. When a user submits an similar search directly from the universal block the expected person result is returned.

![Universal Search Inconsistent Results](https://user-images.githubusercontent.com/54962439/148411179-e620a059-f01f-4cef-bcdf-fb818fe14bed.gif)

### Steps to Reproduce

1. Go to the Alisha Admin Person record on the demo site and add a previous last name. I used the name 'Aimes'
2. Manually Rerun the Universal Search Re-Index job
3. Type Aimes into the Smart Search block and hit enter.
Note: the url is (https://rock.rocksolidchurchdemo.com/universalsearch/aimes?SmartSearch=true)
4. See issue
5. Click the Go Button in the Universal Search block. Now the expected result is returned.
Note: the url is not the same as the first search
(https://rock.rocksolidchurchdemo.com/universalsearch/aimes?groupTypeName=)

Temporary Workaround:
If you navigate to the Universal Search Control Panel and adjust the Search Entities to have all boxes checked then universal search executed from the Smart Search block behaves as expected in relation to previous last name searches.
![image](https://user-images.githubusercontent.com/54962439/148413600-883d0cc8-589d-4247-972a-ab391d022ec8.png)

Note: The out of the box Search Entities settings has no value because no boxes are checked. The Search entities info popup indicates that "If no value is selected all entities will be searched." This workaround shouldn't result in any change of behavior in Universal Search results but it does appear to.

### Versions

* **Rock Version:** Rock McKinley 12.7 (1.12.7.2)
* **Client Culture Setting:** en-US

**Comment by dataCollegechurch** [comment]
@croske - can you help me understand what the fix was? Was there a } in the wrong place or something like that?

**Comment by croske** [comment]
@dataCollegechurch - You're right, there was a bracket problem. The search was adding a blank value if there weren't any "Search Entities" checked.
