### ISSUE TITLE
Transaction Entry V2 Campus Selector Does Not Change to Associated Child Campus Account

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/Rock#4882]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When using the Transaction Entry V2 Block changing the Campus Selector does not appear to change the child account used to make the transaction.

**Transaction Entry V2 Block Settings**
![image](https://user-images.githubusercontent.com/605691/150217848-ddb541b5-fa1f-4f4a-932d-cba74e9bc6a2.png)

**Main Campus Account Settings**
![image](https://user-images.githubusercontent.com/605691/150218079-1c2e6316-b2b6-4d7c-81c2-0ad9e67b0ffe.png)

**Second Campus Account Settings**
![image](https://user-images.githubusercontent.com/605691/150218014-690d5d45-61f4-4922-93e8-3ab140125d35.png)

**Listing of Main Campus Fund Account When Second Campus Is Selected**
![image](https://user-images.githubusercontent.com/605691/150218746-169aaa3c-1614-4214-b8ce-918072282d8d.png)

![image](https://user-images.githubusercontent.com/605691/150218685-7efa4284-9f31-4f52-a0fe-c94b94bde852.png)

### Steps to Reproduce

1. Go to a page with a Transaction Entry V2 Block, (Test Page Created At: https://rock.rocksolidchurchdemo.com/page/2678)
2. Change the Campus Selector
3. Click the "Give Now" or "Next" button to view the next page.
4. See that the original account name is listed beside the newly selected Campus selection

**Expected behavior:**

Changing the campus selector on a Transaction Entry V2 Block changes the account used in the transaction to the child account associated with the newly selected campus. 

**Actual behavior:**

Changing the campus selector on a Transaction Entry V2 Block makes no change in the account used to make the transaction. 

### Versions

https://rock.rocksolidchurchdemo.com/
* **Rock Version:** Rock McKinley 13.0 (1.13.0.30)
* **Client Culture Setting:** en-US

https://www.oneandall.church/
* **Rock Version:** Rock McKinley 12.6 (1.12.6.1)
* **Client Culture Setting:** en-US

**Comment by cwomack** [comment]
@bscottdavis can you check to see if the block settings on the **Transaction Entry (V2)** block have the child accounts _under_ the parent _General Fund_ account enabled?  See my screenshot below compared to the first screenshot in this issue submission.  If the child accounts are enabled in the block settings, you **should** see them comma separated in the "Accounts" section of the settings. 

![image](https://user-images.githubusercontent.com/67726635/150570899-e6d7636e-6959-4344-8b6c-d0d14ea0b193.png)

![image](https://user-images.githubusercontent.com/67726635/150571038-ccc7642c-b03c-4447-b531-8b35b4b54385.png)

**Comment by bscottdavis** [comment]
@cwomack Thanks for the quick response.

I originally did not have the child accounts selected. I was under the assumption that the logic worked in such a way that the selector was supposed to be used to select a parent account and then the correct child account would automatically be selected based on the campus chosen.

I tried selecting the child accounts (shown below) and the result was that all of the accounts showed up in the account selector, regardless of their campus.

![image](https://user-images.githubusercontent.com/605691/151625310-d0922d23-d95b-4c12-b5c5-f4700b2af733.png)

![image](https://user-images.githubusercontent.com/605691/151625348-33de8c4c-dcbf-448c-aad7-ec784a49b5a8.png)

I tried recreating this on the [Rock Demo Site](https://rock.rocksolidchurchdemo.com/page/2673) again, but it looks like the file '/Blocks/Finance/TransactionEntryV2.ascx' does not exist in the current version of the demo site running 12.8.

In playing with other options I found that keeping the account only on the single "General Fund" but switching the "Enable Multi-Account" to "Yes" resolved the issue on my site. With these settings the correct General Fund Account is selected based on the Campus selected. I don't know why this fixes the issue, but thought I would bring it up to you just in case it provided any clues.

Thanks again for your help. Let me know if there is any other context  that I can provide.

**Comment by bscottdavis** [comment]
@cwomack I was able to recreate this on https://rockrmslatest.com/page/716

With Multiple Accounts Selected:
![image](https://user-images.githubusercontent.com/605691/151626796-bc924ddf-82fd-4f16-93b3-c5683a1cb9d7.png)

With Only Parent Account Selected:
![image](https://user-images.githubusercontent.com/605691/151626985-7017f2f0-8838-494f-9ffa-ee87e638835f.png)
![image](https://user-images.githubusercontent.com/605691/151627091-3abeb121-f032-4d63-ae83-73f443ed091b.png)
Highlighted portion above should read "South Campus General Fund - South Campus".

With One Parent Account Selected and Multi-Campus Enabled (works correctly for some reason):
![image](https://user-images.githubusercontent.com/605691/151627280-13415727-cf86-4dc0-a3e8-c37b60b41cc4.png)
![image](https://user-images.githubusercontent.com/605691/151627322-6f92f5eb-0c64-4111-aaa9-689fd9b985c9.png)

**Comment by cwomack** [comment]
@bscottdavis appreciate the screenshots and want to further clarify what we're calling a "bug" here.  I think what's happening is that if the "Ask for Campus if Known" set to "Yes", it allows you to select a Campus to show for that second part after the _dash_ between the Account Fund and the Campus selected within that dropdown.  

It will also default to whatever the logged in person's campus is, which may be why it can be made to show the wrong campus after the fund.  Can you change this setting and see if it's still an issue for someone with a known campus on their person record?  If you manually select the proper campus, does it still show improperly on the finalize gift/finish step? 

![image](https://user-images.githubusercontent.com/67726635/159808587-f4e00505-304a-4ebe-a5f7-e9919f76db07.png)

Even if I intentionally made the wrong campus show after the account by selecting the wrong one (or not touching it depending on what it defaults to), the actual gift/transaction appears to go to the proper fund.  

If it's no longer an issue with these steps or can't be reproduced on the demo site, let me know.  If we don't hear back within a week or so, I'll go ahead and close this issue out.  Thanks!

**Comment by bscottdavis** [comment]
I'm not 100% I'm understanding your question fully and I don't want to add any confusion, so I recreated the issue at: https://rockrmslatest.com/page/700

Based on my understanding of how the block should work the user should be able to select the campus that they would like to give to and the associated child account under the Account set in the block settings should be set as the account that will be used for the transaction. For example in this case the General Fund account is selected in the block settings and the General Fund account has a child accounts under it that that are associated with each of the campuses.
![image](https://user-images.githubusercontent.com/605691/159813743-352c77d3-92cc-4dce-914b-870566a36418.png)

On https://rockrmslatest.com/page/700 if you select demo campus:
![image](https://user-images.githubusercontent.com/605691/159813409-b1444c9d-0c44-4881-8311-636153c3f579.png)

The second screen indicates "General Fund - Main Campus - Demo Campus":
![image](https://user-images.githubusercontent.com/605691/159813476-0c0ad1e7-0b92-407a-a4f1-bd18d7a1c60a.png)

And the final indicates that the final payment went to the Main Campus Child Account:
![image](https://user-images.githubusercontent.com/605691/159813572-d1dcb091-777a-4b87-b56d-1bfaafee394b.png)

Transaction As a Result Goes to Main Campus Child Account:
![image](https://user-images.githubusercontent.com/605691/159813648-1b689913-8848-4e44-8096-37c79d129150.png)
https://rockrmslatest.com/page/165?PersonId=1&TransactionId=444

So it appears that selecting Demo Campus on the initial screen has no effect apart from changing the text on the second screen. My assumption is that selecting Demo Campus on the initial screen should cause the transaction to use the child account under General Fund Account associated with the Demo Campus. Is that correct? Or does the Campus selector on the initial page have a different purpose?
