### ISSUE TITLE
Scheduled Transaction Summary Is Not Updated When Transaction Is Edited

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4887]
#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/3903408/151007840-85ff5c4f-2426-47f9-9dfa-b09853c92a34.png)

### Description

When an existing Scheduled Transaction is edited by the end user, the original "Summary" information is not also updated, making the Summary vs. Actual (new) transaction details out of sync and incorrect.

### Steps to Reproduce

1. From the public website, edit the details of a person's existing Scheduled Transaction (amount, frequency, start date)
2. Go to the user's profile | Contributions tab and click the scheduled transaction
3. Observe that the Summary block still has the original transaction details, not the updated information.

**Expected behavior:**

Summary info would get updated on a scheduled transaction when that info changes.

**Actual behavior:**

The Summary info stays as it was when the original scheduled transaction was created. Note I only tested this with NMI gateway.

### Versions

* **Rock Version:**  12.7

**Comment by JimMichael** [comment]
Note that the transaction history action shows the summary being modified, but to the same values it already had.

**Comment by crayzd92** [comment]
Changes in v13.0 from https://github.com/SparkDevNetwork/Rock/commit/f2e7cf420b27e4b2ee4f791f75a95c6724facbc7 and https://github.com/SparkDevNetwork/Rock/commit/61787beadb28f896eed1032dbb461cf03815f78d may have already solved this one.

@JimMichael could you validate on your 13.x system?

**Comment by JimMichael** [comment]
We're not running v13 in production, yet, so I can't think of a way to actually test this without creating a real transaction.

**Comment by crayzd92** [comment]
Fixed with https://github.com/SparkDevNetwork/Rock/commit/f2e7cf420b27e4b2ee4f791f75a95c6724facbc7 and https://github.com/SparkDevNetwork/Rock/commit/61787beadb28f896eed1032dbb461cf03815f78d in v13.0
