### ISSUE TITLE
Updating room threshold in check-in manager causes an error on the page

### ISSUE THREAD

**Issue by TheCoreyHall** [SparkDevNetwork/Rock#4889]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/38293092/151030156-c646013f-cc37-4ed3-8138-5394f74d9ac1.png)
### Description

When you attempt to set a rooms threshold in the "Live Metrics" section of check-in manager, it fails and displays an error on the page. We observed this happening in Citizens Church who is on 12.7, and I was able to reproduce it on Demo.

### Steps to Reproduce

1. Go to Locations in Rock Demo: https://rock.rocksolidchurchdemo.com/page/307?LocationId=7&ExpandedIds=2%2c3
2. Edit and set threshold to 20.
3. Go to Live Metrics in Checkin Manager: https://rock.rocksolidchurchdemo.com/page/2640
4. Find the room you set and attempt to edit the Threshold with the built-in button.
5. Observe the page error.

**Expected behavior:**

The threshold would be updated to the correct number.

**Actual behavior:**

The threshold does not update and an error appears.

### Versions

* **Rock Version:** [12.7]
* **Client Culture Setting:** [en-us]

**Comment by JimMichael** [comment]
While I can observe this error on demo, I can't induce it on our 12.7 instance. I checked a kid and then set the threshold from 10 to 8 and it accepted it just fine. I'm struggling to see what is different about our setup that allows it to work as expected
![image](https://user-images.githubusercontent.com/3903408/151047924-8405b505-6c55-4567-85d5-a45d41787ecb.png)

**Comment by JimMichael** [comment]
Ah, found it. The error only occurs when you do NOT have an _Absolute Threshold_ set on the location. We already used them, so it worked here. When I set one on demo, it started working, too.
![image](https://user-images.githubusercontent.com/3903408/151048420-16d82c62-c1cf-449d-a435-4a557b7759b4.png)

**Comment by TheCoreyHall** [comment]
Well thats good to know, I can just set a high absolute as a workaround for now. Thanks.

**Comment by nairdo** [comment]
Can someone confirm this is (or is not) happening in v13.0?  I'm not able to reproduce that problem in v13.0.

**Comment by JimMichael** [comment]
I cannot dupe it on v13 or prealpha.
