### ISSUE TITLE
Certain "... Types" field types cause an "Object reference not set to an instance of an object." exception

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4905]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/66277785/151811698-18191d04-46f5-4463-a79b-5aa5eb9a3416.png">

### Description
When you add an attribute of a field type that is _Binary File Types_, _Connection Types_, _Content Channel Types_, or _Group Types_, an "Object reference not set to an instance of an object" exception is thrown, which won't let you add that field type. I found the issue in our 12.7 system when I tried to edit an existing workflow attribute of type _Group Types_ and it threw the exception each time. I can reproduce it in our v13 alpha system, as well as the demo site running v12.7. The pre alpha site (v14) does not have this issue.

### Steps to Reproduce

1. Go to Admin Tools > General Settings then click  Workflow Configuration
2. Click on any Workflow Type category, then click to add a new Workflow Type
3. Expand the Attributes section
4. Click to add a new attribute and set the Field Type to _Group Types_

**Expected behavior:**

That I would be presented with a list of Group Types in a multi-select format and would be allowed to continue to add the attribute.

**Actual behavior:**

An "Object reference not set to an instance of an object" exception occurs and I cannot add this attribute with this field type.
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/66277785/151812990-2f64c4b5-382a-4d72-b6f9-5bfac57babd0.png">

### Versions

* **Rock Version:** [Rock McKinley 12.7 (1.12.7.2), Rock McKinley 13.0 (1.13.0.29)]
* **Client Culture Setting:** [en-US]

**Comment by ethan-sparkdevnetwork** [comment]
Thanks @leahjennings. We fixed this in v13.0 in commit https://github.com/sparkdevnetwork/rock/commit/e88e0f4380587e68e6331654a4691634a5088c2e.

**Comment by JimMichael** [comment]
Will this fix also end up in a 12.x release? Now that early access is a year long and I assume some will be running v12 for quite a while longer because of that, trying to know what to tell people who come to chat with such questions.

**Comment by crayzd92** [comment]
> Will this fix also end up in a 12.x release?

We will be addressing this in 12.8
