### ISSUE TITLE
Calendar Event Item Occurrence Linkage Edit

### ISSUE THREAD

**Issue by asdf1nit** [SparkDevNetwork/Rock#4907]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

![image](https://user-images.githubusercontent.com/18108765/151896222-3e22e5e5-49ee-4bde-91a6-ae2da09eef7a.png)

### Description

When editing a Callendar Event Item Occurrence clicking the edit button to edit a Linkage throws an error.

### Steps to Reproduce

1. Go to a Calendar Event Occurrence
 
![image](https://user-images.githubusercontent.com/18108765/151896497-9ccde592-d51e-44eb-9efc-1628d61d266c.png)

2. Click on the edit button to edit the occurrence
3. On the edit occurrence screen click edit on the Event / Registration / Group Linkages section. (If there isn't one, add one, save, save the occurrence then edit again.)

**Expected behavior:**

A user is expecting to see the edit screen with the ability to edit the linkage

**Actual behavior:**

Rock displays an exception message, and you can't edit the linkage.

### Versions

* **Rock Version:** [v13]
* **Client Culture Setting:** [en-US]

**Comment by cwomack** [comment]
Appreciate you reporting this one @asdf1nit.  We found it internally and already have a fix for it in v13.1 https://github.com/SparkDevNetwork/Rock/commit/342459dbe5fd99ca86421d379c96436e5a43b8a5.
