### ISSUE TITLE
Lava (fluid) comparison with enums inconsistent with dotliquid

### ISSUE THREAD

**Issue by MichaelAllen** [SparkDevNetwork/Rock#4910]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

DotLiquid allows comparison with either the raw integer value or the formatted string value of an enum. Fluid appears to only allow comparison with the string value.

I noticed the inconsistency because I was seeing a rendering exception with the `/Themes/Rock/Assets/Lava/MyConnectionOpportunitiesSortable.lava` file. In that file, it is comparing the connection status with an integer value instead of the string value of the enum. This was working fine in DotLiquid, but in Fluid the comparison is always returning false.

### Steps to Reproduce
(Assuming the default sample data)

1. Place the following lava in an HTML block with entity commands enabled:
```
{% connectionrequest id:'1' securityenabled:'false' %}
    {{ connectionrequest.ConnectionState }}:<br>
    - {% if connectionrequest.ConnectionState == 0 %}equals{% else %}doesn't equal{% endif %} 0<br>
    - {% if connectionrequest.ConnectionState == "Active" %}equals{% else %}doesn't equal{% endif %} Active
{% endconnectionrequest %}
<hr>
{% person id:'1' securityenabled:'false' %}
    {{ person.CommunicationPreference }}:<br>
    - {% if person.CommunicationPreference == 1 %}equals{% else %}doesn't equal{% endif %} 1<br>
    - {% if person.CommunicationPreference == "Email" %}equals{% else %}doesn't equal{% endif %} Email
{% endperson %}
```

**Expected behavior:**

Both DotLiquid and Fluid should return the same result. 

Ideally, fluid could be made to return the same result as DotLiquid to preserve backward compatibility with existing lava templates. If not, then a note should be added to this documentation page: https://community.rockrms.com/lava/fluid/differences

**Actual behavior:**

DotLiquid result:
```
Active
- equals 0
- equals Active
----
Email
- equals 1
- equals Email
```

Fluid result:
```
Active
- doesn't equal 0
- equals Active
----
Email
- doesn't equal 1
- equals Email
```

### Versions

* **Rock Version:** 1.13.0.30
* **Client Culture Setting:** en-Us

**Comment by tcavaletto** [comment]
@MrUpsideDown It looks like this is still an issue when using the case command:
`{% person id:'1' securityenabled:'false' %}
    {{ person.CommunicationPreference }}:<br>
    {% case person.CommunicationPreference %}
        {% when 1 %}equals
        {% else %}doesn't equal
    {% endcase %}
    {% case person.CommunicationPreference %}
        {% when "Email" %}equals
        {% else %}doesn't equal
    {% endcase %}
{% endperson %}`

I encountered this on a client system on 16.4 and verified it on RockSolidChuchDemo running 16.2

**Comment by chead4** [comment]
@tcavaletto Hi Taylor  I just wanted to touch base and provide an update to your comment.  The original issue/fix was for an equality operator and didn't include the case tag. We are looking into this issue for the case tag.

**Comment by nairdo** [comment]
@tcavaletto  We were able to deal with the primary `case` statement in v16.6 (see https://github.com/SparkDevNetwork/Rock/commit/00c255c15627da1926629569eb6c3b3af9b3073f) but there are some limitations** to the solution.  

<sub>** The enum property can't be in the `when ***` portion of the statement.  It will only work in the `case ***` portion.  To address that would require us to bend the underlying library, but that's not something we're interested in doing._</sub>
