### ISSUE TITLE
Structured Content Editor not loading due to Javascript error

### ISSUE THREAD

**Issue by MichaelAllen** [SparkDevNetwork/Rock#4916]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

This commit (https://github.com/SparkDevNetwork/Rock/commit/dbe6123696622e30e858cd92be9ff265fe05d21e) changed the namespace of the structured content editor from `StructuredContent` to `StructuredContentEditor`. However, items under the defined type `Structured Content Editor Tools` were not updated to use the new namespace. Therefore the structured content editor will not load due to a javascript error.

This is the error: `Uncaught TypeError: Cannot read properties of undefined (reading 'EditorTools')`. It is trying to access `Rock.UI.StructuredContent.EditorTools.Header` which doesn't exist anymore.

Performing a search/replace across the items in that defined type fixes the error.

### Steps to Reproduce

(Assuming the default sample data)

1. Tools > Content
2. Select the "Message Notes" content channel
3. Add a new item
4. See that the editor doesn't load and check the browser console for the error.

**Expected behavior:**

A working structured content editor

**Actual behavior:**

Javascript error, and a blank editor

### Versions

* **Rock Version:** 1.13.0.30
* **Client Culture Setting:** en-US

**Comment by crayzd92** [comment]
Commit: 111f408f57f47cffcc913b383e8065e9e3e0c06a

Code: https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Migrations/Migrations/Version%2013.0/Version%201.13.2/202202162343093_rollup_20220216.cs#L176
