### ISSUE TITLE
Check-in Pages Not Loading on iOS 12.5.5

### ISSUE THREAD

**Issue by davemast** [SparkDevNetwork/Rock#4918]
### Description

Attempting to use the Check-In app or browse to the Rock Check-In site (via Safari) on version 13.0 results in a blank white screen when using iOS 12.5.5.

### Steps to Reproduce

Reproduction Steps (Safari)
1. Browse to https://rock.domain.com/checkin
2. Log in with valid credentials.

Reproduction Steps (iOS Check-In App)
1. Set https://rock.domain.com/checkin as the check-in URL
2. Log in with valid credentials.

**Expected behavior:**
_I expected to see the Check-In Admin page in all its glory._

**Actual behavior:**
_I was greeted with a blank white page and was left with an Admin page-shaped hole in my heart._

### Versions

* **Rock Version:** 13.0
* **Client Culture Setting:** en-US
* **iOS Version:** 12.5.5
* **iOS Check-In App Version:** 1.10.0

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1201801237636248">MicrosoftTeams-image (5).png</a>

**Comment by JimMichael** [comment]
I can confirm this happens here on a Gen1 iPad Air running iOS 12.5.2, against rock v13.1alpha. 

After login, I see a completely empty (but not white) screen with only the background image of the theme showing. No admin page ever displays. Same ipad works on Rock v12.4 just fine.

**Comment by matthewmeekins** [comment]
I'm also experiencing this on v13.0 with iPad 's (6th Gen) that can only update to iOS 12.5

**Comment by bobrufenacht** [comment]
While this shows fixed in 13.1, it isn't fully fixed in 13.7.  Had a very similar issue.  Found this commit https://github.com/SparkDevNetwork/Rock/commit/8b9446f1432472b6f5ca3f47f214a918eba9288d which further fixes the problem but isn't in a release yet.  Suggest this be reopened until the second fix is pulled in to a release.
