### ISSUE TITLE
Select Lava Filter Does Not See Values In A SQL Results Array

### ISSUE THREAD

**Issue by notGerryMiller** [SparkDevNetwork/Rock#4938]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
<img width="1092" alt="Screen Shot 2022-03-09 at 15 01 55" src="https://user-images.githubusercontent.com/53865308/157524591-4f21f87f-db9c-47ff-a9a2-222a5640817b.png">

![image](https://user-images.githubusercontent.com/53865308/157528235-7994f0a9-effc-4a0d-80c6-c96456cd8347.png)

### Description

When trying to use the select filter on a array containing the results of a SQL query you have to do a results | ToJSON | FromJSON | Select instead of just results | Select. Confirmed in v13.1 and v13.2. It does not seem to be affecting v14.

### Steps to Reproduce

1. Go to lava tester
2. Enter the following lava
`{% sql timeout:'300' %}
SELECT * FROM Campus
{% endsql %}
{% assign CampusTest = results | Select:'Name' | Uniq %}
{% assign CampusTestToFrom = results | ToJSON | FromJSON | Select:'Name' | Uniq %}
<pre>{{ results | Select:'Id' | ToJSON }}</pre>

Raw: {{ CampusTest | Size }}<br>
To/From:{{CampusTestToFrom | Size }}<br>`
3. Press Test
4. See Error

**Expected behavior:**

results | Select should provide results in an array.

**Actual behavior:**

results | Select returns null

### Versions

Looks Good in v13.0: https://rock.rocksolidchurchdemo.com/page/2680
Looks Good in v14: https://rockrmslatest.com/page/693

* **Rock Version:** Rock McKinley 13.1 (1.13.1.3)
* **Client Culture Setting:** en-US

**Comment by notGerryMiller** [comment]
@MichaelAllen was able to reproduce this yesterday.

https://chat.rockrms.com/channel/troubleshooting?msg=s2LSCfMKikAewizrj

**Comment by MichaelAllen** [comment]
After further testing, and have been able to narrow it down to [this commit](https://github.com/SparkDevNetwork/Rock/commit/56d36bda071a82c11b27fa32fd7ea26ee8d08c17) as the source of this issue.
