### ISSUE TITLE
Event Registration URL Slug field doesn't allow uppercase letters

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4940]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/66277785/158254917-73f18fae-ee68-42ae-b58f-fcd3ee37f929.png)

### Description

When adding a URL Slug to an event registration instance, the validation on the field doesn't allow uppercase letters. I believe all that would be needed to fix this is to adjust the regular expression in the following two files to include uppercase letters. This occurs in both the Event Registration Wizard block and the Registration Instance Linkage Detail block. The validation error message implies that there are special characters present, but it is actually failing on the uppercase letter.

Changing from `ValidationExpression="^[a-z0-9]+(?:-[a-z0-9]+)*$" />` to `ValidationExpression="^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$" />` would allow uppercase letters.

https://github.com/SparkDevNetwork/Rock/blob/9364f834d8809629e3d53976b218315ff6b308e4/RockWeb/Blocks/Event/RegistrationInstanceLinkageDetail.ascx#L54
https://github.com/SparkDevNetwork/Rock/blob/9364f834d8809629e3d53976b218315ff6b308e4/RockWeb/Blocks/Event/EventRegistrationWizard.ascx#L254

### Steps to Reproduce

1. On the demo site, go to Tools > Event Wizard
2. Select "Baptism" as the Registration Template, then click Next
3. In the Slug field, type a word with an uppercase letter in it
4. Notice how the validation error implies there is a special character present, but validation is actually failing on the uppercase letter 
![image](https://user-images.githubusercontent.com/66277785/158254917-73f18fae-ee68-42ae-b58f-fcd3ee37f929.png)

**Expected behavior:**

The Url Slug field would accept the slug with uppercase letters in it.

**Actual behavior:**

An entered Url Slug with an uppercase letter and no special characters fails validation.

### Versions

* **Rock Version:** [Rock McKinley 13.0 (1.13.0.30)]
* **Client Culture Setting:** [en-US]

**Comment by crayzd92** [comment]
Hi @leahjennings, the intent here is that the slugs are only lowercase. We are going to work on changing that validation message to more clearly indicate our intent.

**Comment by crayzd92** [comment]
Fixed by updating the validation message to indicate intent
![image](https://user-images.githubusercontent.com/17650211/158273827-bd4681cd-f1b9-40fb-b4b1-d499e79d8ee7.png)
