### ISSUE TITLE
eRA will not get updated for family members

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4941]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

If any member of a family already has the "Currently an eRA" attribute set to "Yes" and the family still meets requirements for being an eRA, the Family Analytics job will not update other family members who's "Currently an eRA" attribute is not "Yes" to be "Yes". 

So if a person who is not an eRA is added to a family (new or existing person), that person's eRA attribute will not get updated to reflect the families eRA status.

### Steps to Reproduce

1. Go to any family with at least one person who has the "Currently an eRA" attribute set to "Yes"
2. Add a person to that family who does not have the "Currently an eRA" attribute set to "Yes"
3. Run the Family Analytics job

**Expected behavior:**

The person added to family has their "Currently an eRA" attribute set to "Yes"

**Actual behavior:**

The person's "Currently an eRA" attribute is not updated

### Versions

* **Rock Version:** v12.8 and v14.0 (alpha site)
* **Client Culture Setting:** en-US

**Comment by crayzd92** [comment]
@azturner is this the same as https://github.com/SparkDevNetwork/Rock/issues/4146?

**Comment by azturner** [comment]
@crayzd92 , No those are different. This issue is due to fact that whenever the Family Analytics job runs, it is calculating if family is currently an eRA and then comparing that to whether family was already marked as an eRA. If they were not, it updates everyone in the family to have the "Currently an eRA". The problem is that it determines if family was already marked as an eRA by getting the max value of "Currently an eRA" of everyone in family. So if anyone in the family has that value, it will assume everyone in family already has it and not update anyone.

The other issue is related to how the job calculates the Times Checked In and Times given attributes and how they could show values that are not reflective of what eRA is using to calculate the eRA status. Attributes will show values that seem to meet requirements of being an eRA but in fact person is not an eRA.

**Comment by crayzd92** [comment]
@azturner thanks for the update, just wanted to be sure on that.

**Comment by JimMichael** [comment]
We have also observed this when there are two adults in the family where one is marked as eRA and the other one is NOT eRA because they are (incorrectly) configured to give as individual. 

After setting that adult to "Combine giving with family", they never become eRA no matter how many times the analytics job runs.

**Comment by crayzd92** [comment]
This will be fixed with a migration in 13.4.

**Comment by crayzd92** [comment]
See https://github.com/SparkDevNetwork/Rock/commit/41197c49444a2a5fc3e0c5781bf06fea75e3e778#diff-7d19c47891c6f2dba5d76cab5956ccb371896f0146b2ff9b0508df5ce74c2ccf
