### ISSUE TITLE
Person First Attended Group Type - Event Type

### ISSUE THREAD

**Issue by asdf1nit** [SparkDevNetwork/Rock#4943]
#### A Picture Is worth a Thousand Words
Exception from Log
![Web capture!UNITO-UNDERSCORE!14-3-2022!UNITO-UNDERSCORE!161127!UNITO-UNDERSCORE!portal ark info](https://user-images.githubusercontent.com/18108765/158919054-e2af5ee4-caa0-4695-a576-4ad07e2508c6.jpeg)

Scheduled Job with Exception Message
![Web capture!UNITO-UNDERSCORE!14-3-2022!UNITO-UNDERSCORE!16734!UNITO-UNDERSCORE!portal ark info](https://user-images.githubusercontent.com/18108765/158919089-df6171f9-503c-418c-81b7-87a96dc9d837.jpeg)

Following Event Configuration
![Web capture!UNITO-UNDERSCORE!14-3-2022!UNITO-UNDERSCORE!1677!UNITO-UNDERSCORE!portal ark info](https://user-images.githubusercontent.com/18108765/158919159-7f02c012-dcc6-4b17-8be6-e7505fad9a05.jpeg)

### Description
I could not reproduce this on the demo server. I did have a community member confirm this on their production server.
[Troubleshooting Chat Channel](https://chat.rockrms.com/channel/troubleshooting?msg=hyyZ8FD93NAYDYE3g)

Configuring a following event of Person First Attended Group Type will cause an error in the Send Following Event Notification Job. The job completes, is reported as successful, and does send notification emails for other event types, however notification for this event type are not sent.

### Steps to Reproduce
1. Go to System Settings > Following Events
1. Add a new Following Event for Person First Joined Group Type(seen in image above)
1. Run the Send Following Events Notification job
1. See error

**Expected behavior:**

Job to run successfully without generating an exception and the person who is following someone to be notified if they attended a group of type for the first time.

**Actual behavior:**

An exception is generated. No email is sent notifying a person of first time attendance.

### Versions
* **Rock Version:** [12.8]
* **Client Culture Setting:** [en_US]

**Comment by dynamiclynk** [comment]
Fix  - https://github.com/SparkDevNetwork/Rock/commit/8d4522e7f68812448dc7bfa93fe225e15f96d239
