### ISSUE TITLE
Registration Nav HTML block always overlaps content

### ISSUE THREAD

**Issue by bmurphy-dev** [SparkDevNetwork/Rock#4949]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/73124289/159792044-edd84450-ba97-473b-9ca9-28c366d2c632.png)
![image](https://user-images.githubusercontent.com/73124289/159792058-11133fa6-9295-4f28-8ef4-b3584593660a.png)
Typical use case for a custom HTML block above this Nav:
![image](https://user-images.githubusercontent.com/73124289/159792077-80396f71-4a78-465d-be1d-cbf330fc3269.png)

### Description

The default Registration Nav HTML block in the Feature Zone of the Event Registration page overlaps all content applied above it.

### Steps to Reproduce

1. Go to the Event Registration page
2. Add a new HTML (or any block) to the Feature Zone which the existing Registration Nav HTML blocks exists
3. Ensure that your new block is above the existing Registration Nav HTML block and then try to edit the block settings. Enjoy fighting the overlap to get to the new blocks settings
4. Add some content to the new HTML block. See the results of the overlap of the Registration Nav HTML block

**Expected behavior:**

I would expect the Registration Nav block to stay in it's place and let other content land on top of it just like any other ordered block.

**Actual behavior:**

The Registration Nav HTML block overlaps all content above it from within the zone. I've had to shove an ugly Pre-HTML/Post-HTML wrap on this block to push it down with some extra margin-top in order for it to behave. `<div class="row" style="margin-top:50px;">`

### Versions

* **Rock Version:** [v11.0, 12.0, 13.0+]
* **Client Culture Setting:** [en-US]

**Comment by garrettjohnson** [comment]
@bmurphy-dev Upon further reflection we are reverting the fix because we'd like the wizard UI to stay pinned to the edge of the interface above the block. Also, since this is a core page, it is risky to add additional code like your example, and is not something we would recommend.
