### ISSUE TITLE
New Structured Content Editor in Rock V13 Creates List Item Structured Content that is not usable in Mobile App 

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/Rock#4955]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
![image](https://user-images.githubusercontent.com/605691/160213091-b247f34b-bb14-42bb-aa13-5fdfde82704c.png)

The new structured content editor creates more complex structured content that is not compatible with the mobile app.  Specifically, the list type creates a more complex object, shown above. In my example manually editing the JSON to match to the simpler object caused the notes to become viewable again. 

### Steps to Reproduce

1. Create a Message Note in V13 that includes a list item.
2. View the created message note in a mobile app.
4. See error below
![image](https://user-images.githubusercontent.com/605691/160213760-98ad3b57-97a4-44d9-bc35-5c01efd36972.png)

**Expected behavior:**

Message notes created with list items show correctly in the mobile app.

**Actual behavior:**

Message notes created with list items do not show correctly in the mobile app.

### Versions

* **Rock Version:** Rock McKinley 13.2 (1.13.2.2)
* **Mobile Shell Version:** v2.0
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
@bscottdavis This was fixed in v3 of the Mobile Shell last week. I don't have a specific time frame for when it will be released, but we are trying to get it buttoned up.
