### ISSUE TITLE
WYSIWYG Editor "Insert Link" button missing - .btn-primary overwritten by .note-btn

### ISSUE THREAD

**Issue by tp-code** [SparkDevNetwork/Rock#4956]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/41316251/160706437-83f9b07a-d4b7-43d6-8944-bf1573ecf700.png)

Here is what happens when you hover your mouse over where the button is located...
![image](https://user-images.githubusercontent.com/41316251/160706601-c1dbd61a-32e2-4260-8a56-62f2b654cd7a.png)

### Description
I have been able to replicate this issue on the following versions:

- Rock McKinley 13.2 (1.13.2.2) / en-US (Our instance on Azure)
- Rock McKinley 13.1 (1.13.1.3) / en-US (Rock Demo site)

I have confirmed that the issue DOES NOT exist on the Pre-alpha site: Rock McKinley 14.0 (1.14.0.7).

When adding a link to text in the WYSIWYG Editor, the "Insert Link" button is not visible. When you over over it, it does become visible.

If you open the browser developer tools, you will see that the button has the class btn-primary. It also has the class note-btn. The css on the class seems to be overwriting the btn-primary formatting.

![image](https://user-images.githubusercontent.com/41316251/160707054-d9b29103-e421-4249-821f-d764d2445e92.png)

### Steps to Reproduce
I am able to replicate this on both Chrome and Firefox (on a Mac).

1. On the Demo site. Go to **Tools** > **Content**
2. Click **Website Blog**
3. Add a **new item**
4. In the Content box, **add a hyperlink**
5. The **Insert Link** should not be visible unless you hover over it

**Expected behavior:**
**Insert Link button** is visible with the standard btn-primary formatting.

**Actual behavior:**
The button is not visible unless you hover over it.

### Versions

* **Rock Version:** Rock McKinley 13.2 (1.13.2.2)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1202046423001697">image.png</a>

**Comment by crayzd92** [comment]
@tp-code thank you for the report, this was fixed with https://github.com/SparkDevNetwork/Rock/issues/4935 in v13.3.
