### ISSUE TITLE
Error when selecting blank type for new person document

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/Rock#4959]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
When adding a new document on the documents tab of a person's profile, there's an "Object reference not set to an instance of an object" exception that is thrown if you select a document type and then select no document type. 

![image](https://user-images.githubusercontent.com/1696714/161108351-abbe3dda-2367-47e8-ad25-dc27203a911f.png)

### Steps to Reproduce

1. Go to the documents tab on a person profile
2. Click on the plus icon to add a new document
3. Select any option under the Document Type dropdown
4. Select the blank option under the Document Type dropdown
5. Notice the error message that shows up at the top of the page

**Expected behavior:**
Either nothing should happen when selecting the blank option, or at most the field should be highlighted as a required field

**Actual behavior:**

The field was highlighted as a required field, but an error message was also displayed at the top of the page

### Versions

* **Rock Version:** 12.8 and 13.0
* **Client Culture Setting:** en-US

**Comment by crayzd92** [comment]
Addressed in v14 https://github.com/SparkDevNetwork/Rock/issues/4377, will cherry-pick fixes to 13.3.
