### ISSUE TITLE
Group Scheduler \ Check-in

### ISSUE THREAD

**Issue by asdf1nit** [SparkDevNetwork/Rock#4966]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Group Options
![Screen Shot 2022-04-04 at 1 38 28 PM](https://user-images.githubusercontent.com/18108765/161610910-b056a527-f33a-4724-bee1-f0f4e674e5f8.png)

Check-in Configuration Options
![Screen Shot 2022-04-04 at 1 36 34 PM](https://user-images.githubusercontent.com/18108765/161611026-d013a15f-a1ff-4da5-874c-0da933727f50.png)

Group Scheduler Scheduled People - Cindy is scheduled for the Bunnies room
![Screen Shot 2022-04-04 at 1 35 49 PM](https://user-images.githubusercontent.com/18108765/161611121-ef8631d4-78ee-4e36-a801-a736bfc505ec.png)

Check-in People Selection - Shows Cindy scheduled in the Bears room which is not correct.
![Screen Shot 2022-04-04 at 1 39 19 PM](https://user-images.githubusercontent.com/18108765/161611277-fb5131fe-3331-4f9d-afd2-869f3a2ba17c.png)

Check-in People selection edit  - The below screenshot should not have the first location - Bears room selected. Cindy was only scheduled in the bunnies room.
![Screen Shot 2022-04-04 at 1 40 58 PM](https://user-images.githubusercontent.com/18108765/161611383-78026182-e33f-4ea8-ac52-7af41c752bd2.png)

### Description

When using group scheduling, and setting scheduling options on the group to "Pre-Select Group if Scheduled", if you have multiple locations on the group(screenshots above), check-in will pre-select and check the person into multiple locations at once if not corrected. If you edit the selection and change options it will only allow you to select( and check-in) one location( as it should).

In the check-in configuration I'm using(screen shot above), I have set General Settings > Auto Select options to "People and their Area\Group\Location".

There should not be 2 pre-selected locations for a given schedule(unless someone can be 2 places at once). Check-in prevents this in every case except this one.

In this configuration, check-in always pre-selects the first location listed in the group and the location that the person is scheduled for. 

If you change the group scheduling options on the group to "schedule required" you do not have this issue as no other locations are presented as options for check-in, only the location you have been scheduled for is available. ( For us this is not desirable since we might have volunteers that weren't scheduled to show up fill in, and we do want them to check-in if they serve.

If you set the group scheduling options to "schedule not required", it is not an issue as no locations are pre-selected - this is how we currently have our check-in set up but would like to change to pre-selecting, since volunteers might not remember what they are scheduled for.

### Steps to Reproduce

Prerequisites: 
- Check-in configuration for the group type with auto select options set to "People and their Area\Group\Location".
- Group configuration with scheduling options set to "pre-Select Group if Scheduled"

1. Go to a group with scheduling enabled and add multiple locations for a given schedule.
2. Go to the group scheduler and schedule a person to any location EXCEPT the first location.
3. Mark the person as confirmed
4. Go to check-in and check the person in to the group
5. notice the person is checked into multiple locations

**Expected behavior:**

The volunteer to be checked into only 1 location.
It's expected that the location that they have been scheduled for to be selected, as it is, but the first listed location should not be selected.

**Actual behavior:**

The volunteer is checked into 2 locations on the same schedule. They have the ability to correct this if they are aware that a change should be made.

### Versions

* **Rock Version:** [12.8 and 13.2]
* **Client Culture Setting:** [en-US]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1202095115294097">chrome_mBjeD5Jfuw.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1202095115294099">chrome_0cPv9UKIrp.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1202095115294101">chrome_WOP4UXG6Tg.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1202095115294103">chrome_QHVfRJrbch.mp4</a>

**Comment by asdf1nit** [comment]
Any chance this one can get some love? Still a bug in 14.2.

**Comment by nairdo** [comment]
> Any chance this one can get some love?

@asdf1nit Jonathan, Yes.  As you probably know, we really want to get this list down to 0 and we are getting closer to investigating this one.  (_For some of the check-in related bugs there is a small chance that we might only be able to address it in the "check-in 2.0" system, but we'll know once we pinpoint the problem._)

As long as I have your attention, can you clarify the end of this sentence taken from your description above:

> In the check-in configuration I'm using(screen shot above), I have set General Settings > Auto Select options to "People and their Area\Group\Location". This issue does not happen if 

[if what?]

**Comment by asdf1nit** [comment]
@nairdo oops, sorry about that. When I edited the description for clarity I moved some things around. That "if" was moved to the 5th paragraph, starting with "If you change the group scheduling options...it doesn't happen"

If there is anything I can do to help let me know.

**Comment by jasonhendee** [comment]
In closing this issue, I wanted to point out that after this fix, there is still a scenario in which a Person can be preselected for multiple Locations for a given Schedule: if the Person has been purposefully scheduled to have conflicts, the Check-in system will honor this conflict and preselect them for all scheduled locations:

![04_CindySchedulingConflict](https://github.com/SparkDevNetwork/Rock/assets/59710095/b9502c37-7d6c-4571-9a15-bc6e113614d1)
![05_CindyPreselectedLocations](https://github.com/SparkDevNetwork/Rock/assets/59710095/361eab84-0c0d-4b5d-a433-5207d0e9fff2)
![06_CindyPreselectedLocations](https://github.com/SparkDevNetwork/Rock/assets/59710095/18ee5845-d822-4f5b-9c81-5a92ec11ee77)

However, if Cindy unselects one of the preselected Locations in this scenario, the standard Check-in behavior will resume, preventing her from selecting more than one Location for a given Schedule:

![07_CindyOnlyOneLocation](https://github.com/SparkDevNetwork/Rock/assets/59710095/8c53745f-3f77-4c05-966a-25a167114a3e)
