### ISSUE TITLE
Adding and Editing Metrics

### ISSUE THREAD

**Issue by asdf1nit** [SparkDevNetwork/Rock#4967]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/18108765/161659072-5d561f48-d6d4-4b68-bf20-05bd6a04e075.png)

### Description

When trying to add a new metric the page times out. When trying to edit an existing metric the page times out.

#### Adding a new Metric
1. Go to Tools > Metrics
2. Click the + button to add a new metric
3. Page shows the loading animation for a while and times out

#### Editing an existing Metric
1. Go to Tools > Metrics
2. Select an existing metric
3. Click Edit
4. page shows loading animation for a while and times out 

**Expected behavior:**

You should be able to add or edit a Metric

**Actual behavior:**

You can neither add nor edit a Metric

### Versions

* **Rock Version:** [13.2]
* **Client Culture Setting:** [en-US]

**Comment by mikedotmundy** [comment]
I am on v13.2 and I am not seeing this issue.

**Comment by asdf1nit** [comment]
I'm having this issue on my dev server and can duplicate it on the demo site.

**Comment by asdf1nit** [comment]
After testing again, it seems to be something in my browser, using a private\incognito window resolved it.

**Comment by JRichmond27** [comment]
@asdf1nit Were you able to narrow down exactly what was causing this? I was running into the same issue, and after some troubleshooting, I found it was caused by my ad blocker browser extension (uBlock Origin). 

While the extention was active, I got a "blocked by client" error message as soon as I clicked Add or Edit:
![image](https://user-images.githubusercontent.com/1696714/203156375-d9709b17-2bd6-43d4-aa44-ad41cdd9344c.png)

After I disabled the extention for our internal Rock site, the error went away and the page loaded right up.

**Comment by asdf1nit** [comment]
I was able to determine the issue and have had the same issue as you in the past. Ad blockers (ubBock Origin and the like), and other programs that can filter traffic, Cloudflare, network-based ad blockers(piHole, pfBlockerNG), network-based ids\ips(bro, suricata, snort) can cause issues with any site if not properly configured.

If you are using any of these things and are experiencing issues with certain functions of rock this is the first place I look. I find it's mostly in post back actions when clicking a save\update button, just depends on where you are in rock.
