### ISSUE TITLE
Checkin Manager Share Person Button Missing

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4970]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

The "Share Person" button is missing on the Check-in Manager Person Profile page (`/page/301`).

#### A Picture Is worth a Thousand Words
![Screen Shot 2022-04-07 at 09 38 51](https://user-images.githubusercontent.com/23226974/162229609-abe7f2dd-ccc3-4c8e-a386-592b555a4be5.png)

![Screen Shot 2022-04-07 at 09 38 39](https://user-images.githubusercontent.com/23226974/162229516-29c0ca83-15f5-448d-955f-96568cc5119c.png)

### Steps to Reproduce

1. Go to `https://rockrmslatest.com/page/301?Person=b71494db-d809-451a-a950-28898d0fd92c`.
2. Edit the block settings of the Person Profile block, and make sure "Show Share Person Button" is set to "Yes".
3. See there is no share person button in the block.

**Expected behavior:**

Share Person button appears.

**Actual behavior:**

Share Person button does not appear.

### Versions

* **Rock Version:** [v13.2, v14.0]
* **Client Culture Setting:** [en-US]

**Comment by crayzd92** [comment]
We have confirmed this issue only reproduces on a Mac running Chrome or Brave browsers. It does not reproduce in Chrome on Windows or in Safari on a Mac.

**Comment by cabal95** [comment]
@mikedotmundy Thanks for reporting. We did a little more digging and found that Chrome and Edge for MacOS do not yet support the "share" feature. Though it looks like effort is currently in the works to implement the support.

Firefox supports the feature, but has it turned off by default (looks like they are in "testing phase" on it).

When those browsers fully implement the feature Rock should automatically start making use of it there too.

You can track the progress of the Chrome and Edge support here, though it's pretty developer focused: https://bugs.chromium.org/p/chromium/issues/detail?id=1144920
