### ISSUE TITLE
Hyperlink Confirmation Button Missing in Communication Wizard Link Editor

### ISSUE THREAD

**Issue by JDShuman** [SparkDevNetwork/Rock#4979]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

When entering a hyperlink in the text editor (specifically in the communication wizard), the confirmation button on the hyperlink dialog box is not visible.  It is there if you hover over where it should be visible, but it seems to be the same color as the background.

### Steps to Reproduce

1. Go to the test Rock site: https://rock.rocksolidchurchdemo.com (and log in)
2. Use the People menu to start a new communication
3. Enter test information to advance until you reach the email editor
4. Enter text into the text box editor, then highlight a portion of text, then click the "link" icon in the tool bar
5. Enter your hyperlink information
6. Try to find the "Ok" or 'Enter" button?
![CommunicationWizard_ConfirmationButton](https://user-images.githubusercontent.com/93220961/163214500-713de71a-93b6-4c01-b418-1157f1fd65ef.png)

**Expected behavior:**

I expect the confirmation button to be a different color than the background of the dialog box.

**Actual behavior:**
The button is not visible, possibly because it is the same color as the background.

### Versions

* **Rock Version:** [13.2]
* **Client Culture Setting:** [EN-US]

**Comment by garrettjohnson** [comment]
Fixed by https://github.com/SparkDevNetwork/Rock/commit/07a08fc226b8958227676d0e1f2dc9a7bda93385 in v13.3
First noted in issue #4935
