### ISSUE TITLE
MediaPlayer Shortcode does not allow src: videos to play on mobile devices

### ISSUE THREAD

**Issue by raufrecht** [SparkDevNetwork/Rock#4982]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

When using the mediaplayer shortcode to watch a video that is not a Media Element (using src:), the video does not play on a mobile device (iphone or android phone).

### Steps to Reproduce

1. In an html Content Block enter: {[ mediaplayer src:'https://vimeo.com/698349874' ]}{[endmediaplayer]}
2. visit the page where the block is on a mobile phone browser.

**Expected behavior:**

The video should play.

**Actual behavior:**

The video play button disappears for a second and then comes back and video doesn't begin.

### Versions

* **Rock Version:** 13.2
* **Client Culture Setting:** Android 12 on Chrome/Edge, iPhone 11 on Safari

**Comment by garrettjohnson** [comment]
@raufrecht We weren't able to reproduce the issue on iOS or Android with the Vimeo link you provided. I recreated the shortcode on this page: https://rocksolidchurchdemo.com/page/2679 and included the browser info under the video. If you're still seeing issues could you screenshot that page from the broken device, the user-agent string will help with additional troubleshooting.

Thanks!

**Comment by raufrecht** [comment]
It worked one time when I was holding my phone landscape.

**Comment by raufrecht** [comment]
Fyi, it looks to be edge. I tried it in Chrome and it works.

**Comment by garrettjohnson** [comment]
@raufrecht We have tested in Edge as well, and could not replicate the issue. If you're still experiencing the issue please [share your browser string](https://www.google.com/search?q=get+user+agent+string) and we will be glad to investigate further.

**Comment by raufrecht** [comment]
Mozilla/5.0 (Linux; Android 12; Pixel 6) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/100.0.4896.127 Mobile Safari/537.36 EdgA/100.0.1185.50

**Comment by raufrecht** [comment]
Here is the site that is not working for my phone https://www.oneandall.church/reengagecurriculum

**Comment by bscottdavis** [comment]
@garrettjohnson I've added a mediaplayer to https://www.oneandall.church/page/2025 and I am able to see the issue on any iOS browser. Are you able to see it at https://www.oneandall.church/page/2025?
![image](https://user-images.githubusercontent.com/605691/177405974-d60988f9-3c83-4d1d-b2ba-a54934e04a6f.png)

**Comment by bscottdavis** [comment]
@garrettjohnson I just retested and noticed that the block that I have placed on https://www.oneandall.church/page/2025 to use the shortcode was hidden from non-Rock Admins. Sorry about that. It should be viewable now.

**Comment by bscottdavis** [comment]
@garrettjohnson I am so sorry, I started commenting on this issue without fully reading the description. I assumed this issue was related to the mediaplayer shortcode not playing properly in fullscreen. I now see that it is related to something totally different. I will check to see if an issue related to the fullscreen issue exists and will create a new issue if necessary.
