### ISSUE TITLE
Assessment Retakes not available

### ISSUE THREAD

**Issue by megilee** [SparkDevNetwork/Rock#4991]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

After a person completes an assessment there is not an option for retaking the test in the Assessment Block even though there is reference to it in the Lava. The behavior is different for different assessments and different Rock versions. We are currently running v12.8. The Retake Assessment option appears for Conflict Profile but not for Spiritual Gifts.

![Screen Shot 2022-04-27 at 9 52 54 AM](https://user-images.githubusercontent.com/45012163/165626638-54ced981-9d6c-42e7-be97-8aa820e4ff57.png)

On the demo site currently running v13.2 the retake link does not appear for any completed assessments.

<img width="1653" alt="Screen Shot 2022-04-27 at 10 10 16 AM" src="https://user-images.githubusercontent.com/45012163/165626831-2a69910f-45d6-48c6-a2fc-e1817d011085.png">

The Lava Template on the block has reference to an AssessmentRetakeLinkButton that works in some instances.

![Screen Shot 2022-04-27 at 3 42 06 PM](https://user-images.githubusercontent.com/45012163/165627789-597901b2-4167-4a01-8260-340041e418c0.png)

### Steps to Reproduce on Demo Site

1. Go to Alisha Admin's account page on the external site.
2. Take some of the assessments
3. Links will appear on the Assessments List block
4. Results links are available but not a retake link

**Expected behavior:**

A link will appear that says 'Retake Assessment'

**Actual behavior:**

The link only appears for certain assessments on our older version of Rock and not at all on the demo site.

### Versions

* **Rock Version:** 12.8
* **Client Culture Setting:** en

**Comment by crayzd92** [comment]
@megilee The assessment retake link is driven by a couple of data points in Rock. The first one is that the assessment was previously completed, the next is that the "Minimum Days to Re-take" has elapsed, and the third is that the test does not require approval to be taken again.

![image](https://user-images.githubusercontent.com/17650211/165646543-14975f8b-e938-4b7b-b074-2fd7517797b8.png)

When the days to retake is set to the default 365 (Spiritual Gifts), then the button does not appear.

![image](https://user-images.githubusercontent.com/17650211/165647074-5965cc8b-7056-49db-92ff-9e3f9166c3bb.png)

![image](https://user-images.githubusercontent.com/17650211/165647044-06f87e06-42d4-472c-85e6-9c705f6ae412.png)

When the days to retake are set to zero (0), then the button should immediately appear on the Person's profile and the test itself.

![image](https://user-images.githubusercontent.com/17650211/165646871-a1506065-ac4d-4eda-b174-1aa192823bf3.png)

![image](https://user-images.githubusercontent.com/17650211/165646904-6d9c87c5-ec42-4df1-a78a-ca37b8680a18.png)

Are you experiencing this problem when the settings should allow the retake but are not? If so, could you provide a screenshot of the assessment configuration? If not, hopefully, this was enlightening.

**Comment by megilee** [comment]
Thank you so much for the info, @crayzd92 ! I had no idea those individual assessment settings were out there as there was no mention in the Assessments manual. This takes care of all my questions and issues!

One follow up question: I see there is a Valid Duration set for 730 (assuming that means 2 years). Is that set in stone? I don't see a place to change it.
