### ISSUE TITLE
Can't update person's location preference from Group Scheduler

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#5008]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![](https://user-images.githubusercontent.com/12735965/167721179-14c1e160-0574-4547-8784-7953b98888db.png)

### Description
If a person signs up for an open serving spot on the Schedule Toolbox page but doesn't select a location preference you can't update their preference on the Group Scheduler page. That causes them to not show up on the Group Schedule Status Board page either.

### Steps to Reproduce
1. Log into https://rocksolidchurchdemo.com/ScheduleToolbox as Ted Decker
1. Go to the Sign Up page and select a serving time.
1. Leave the location as No Location Preference.
1. Go to https://rock.rocksolidchurchdemo.com/GroupScheduler
1. See Ted listed under No Location Preference.
1. Click the 3 dot menu for Ted and choose Update Preference
1. Get the exception shown. 
![](https://user-images.githubusercontent.com/12735965/167721975-ea992b15-33f4-45a5-96b4-49cfbdc456a6.png)

**Expected behavior:**

I would be able to update Ted to the Main Campus location.

**Actual behavior:**

Exception shown in the screenshots above.

### Versions
* **Rock Version:** [12.8-13.2, pre-alpha 1.14.0.10]
* **Client Culture Setting:** [en-us]

**Comment by jennifertroeger** [comment]
Confirming that this error occurs in v13.4 as well.
