### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by JamieSlome** [SparkDevNetwork/Rock#5011]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@deleterepo) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by jonedmiston** [comment]
Policy added

**Comment by JamieSlome** [comment]
@jonedmiston - appreciate your diligence! You should have received an e-mail about 12 hours ago to the elected address 👍 

You can also view the report directly here:
https://huntr.dev/bounties/09d8c54c-ec32-4017-8a53-e77ef28d739e/
