### ISSUE TITLE
Can't save Group Type changes when Scheduling Enabled is true and None selected for Group Schedule Options

### ISSUE THREAD

**Issue by jhawkzz** [SparkDevNetwork/Rock#5012]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When editing a group type, if within 'Scheduling' the 'Scheduling Enabled' option is checked, and within the 'Attendance / Checkin' section 'Group Schedule Options' is left blank (which is an allowable choice), clicking Save will result in an error.

This is due to the underlying `GroupType.cs` model's validation. In `IsValid` it checks for `IsSchedulingEnabled` and if true, expects a value other than `0/None` for `AllowedScheduleTypes`. When `0/None` it returns an error.

![Screen Shot 2022-05-13 at 4 02 07 PM](https://user-images.githubusercontent.com/7613642/168399603-7dc38a7d-94e0-4007-b0d1-e55dc5c02837.png)

### Steps to Reproduce

1. Go to 'https://rock.rocksolidchurchdemo.com/admin/general/group-types/23'
2. Expand the 'Scheduling' section and check 'Scheduling Enabled'
3. Expand the 'Attendance / Check-in' and ensure nothing is checked for 'Group Schedule Options'
4. Click 'Save' at the bottom
5. See that an error is displayed.

**Expected behavior:**

Saving should be allowed, since 'Group Schedule Options' is not a required field.

**Actual behavior:**

An error is thrown because 'Group Schedule Options' is effectively set to `0/None`.

### Versions

* **Rock Version:** 13.2.2
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
If group scheduling is enabled, the 'Group Schedule Options'  field is required.  We've adjusted the code to flag the other item as required if the Scheduling Enabled is checked.
