### ISSUE TITLE
13.4 Alpha1 - Drain Transaction Queue Exception Every Time Communication Is Sent

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5013]
### Description

We're seeing a _Exception in Global.DrainTransactionQueue(): SaveCommunicationTransaction_ exception in the log every time ~Rock~ a 13.4alpha workflow with _Save To Communication History_ set to Yes in a _Send Communication_ action   a communication runs.

It does NOT prevent the communication from actually sending (they arrive just fine), but logs the exception.

Note we are using the SendGrid HTTP transport.

![image](https://user-images.githubusercontent.com/3903408/168632366-e29815b6-bcc9-48f4-86ef-c37106fac283.png)

![image](https://user-images.githubusercontent.com/3903408/168632399-aa6343ad-b3af-4a77-81d7-72e1b01b57d2.png)

1. Identify a workflow with a Send Email action that has Save to Communication History set to True (the core Photo Request is a good test case)

2. Run the workflow from a person's action menu

3. Observe that while the email does arrive, the above exception is recorded in the log, and the communication is not logged to Person history.

### Versions

* **Rock Version:** 13.4 alpha1

**Comment by JimMichael** [comment]
Ok, after further testing... we are indeed seeing a problem, but it is limited to _Workflows_ that have a _Send Email_ action with _Save to Communication History_ set to _Yes_.

Under those conditions, the above exception is thrown when the workflow sends the email. The communication IS delivered, but it is not logged to the recipient Person's history.

Just to be absolutely sure, I then rolled back to 13.3 and ran the same workflow(s), which do NOT throw the exception and DO log to person history. I then re-upgraded that 13.3 back to 13.4alpha and the same workflows again throw the exceptions, and don't log to history.)

**Comment by mikedotmundy** [comment]
Confirmed that we see this as well. We also see the exception when a _Send Email (System Communication)_ Workflow Action is used.

**Comment by shivambareria** [comment]
closed via https://github.com/SparkDevNetwork/Rock/commit/5833116b6ea7212c0070f8850015db38f76d31e1

**Comment by shivambareria** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/5833116b6ea7212c0070f8850015db38f76d31e1

**Comment by nairdo** [comment]
FYI: This last change was discovered after the 13.4 alpha was packaged but it will be in the v13.4 beta next week.
