### ISSUE TITLE
RockCleanup job misses completed workflows

### ISSUE THREAD

**Issue by SteveSwaringen** [SparkDevNetwork/Rock#5015]
### Description
The RockCleanup job does not remove old workflows if the "Status" is other than "Completed", even when the State is Complete (which is to say it has a non-null CompletedDateTime).

### Steps to Reproduce
1. Define a workflow and set the Completed Workflow Retention Period to 0 days and set persistence to automatic.
1. Have the closing action of the workflow set the Status to "Abandoned" (anything other than "Completed").
1. Run the workflow a few times. Verify that persisted workflows are created, that those workflows are tagged with a State of "Complete" and the Status specified in step 2.
1. Run the cleanup job and check the workflow history again.

**Expected behavior:**

Completed workflows should be purged from history.

**Actual behavior:**

Completed workflows persist.

From RockCleanup.cs:

`        private int CleanUpWorkflows( JobDataMap dataMap )
 {
 int totalRowsDeleted = 0;
 var workflowContext = new RockContext();
 workflowContext.Database.CommandTimeout = commandTimeout;

```
        var workflowService = new WorkflowService( workflowContext );
```

```
        var completedWorkflows = workflowService.Queryable().AsNoTracking()
            .Where( w => w.WorkflowType.CompletedWorkflowRetentionPeriod.HasValue && w.Status.Equals( "Completed" )
            && RockDateTime.Now > DbFunctions.AddDays( w.ModifiedDateTime, w.WorkflowType.CompletedWorkflowRetentionPeriod ) )
            .ToList();
```

`
You can see where the query is building a list of workflows with a "Status" of "Completed" instead of a non-null CompletedDateTime.

"Status" is a workflow-defined string that creators can use to track application-specific status about a workflow. It is not a reliable indication of the completion status of a workflow. CompletedDateTime is the mechanism used by Rock to indicate deterministically that a workflow is, in fact, finished.

### Versions
* **Rock Version:** [13.3]
* **Client Culture Setting:** [en-us]

**Comment by dataCollegechurch** [comment]
I am on 16.5 and am seeing completed workflows even with a status of completed being retained beyond their Completed Workflow Retention Period (days). My Rock Clean Up job appears to be running successfully otherwise. After we upgrade to 16.7 I will report back and create a separate bug if we are still experiencing this issue.
