### ISSUE TITLE
13.4 Alpha - Process BI Analytics Job Causes Exception

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5016]
### Description

When testing the _Run the 'Process BI Analytics' job_ step during alpha testing of 13.4, we're seeing the following exception:

![image](https://user-images.githubusercontent.com/3903408/168913490-83aa1491-8cfe-4e6b-8a7e-7f59cb776faa.png)

### Steps to Reproduce

1. Go to Admin | System Settings | Job Admin
2. Run the Process BI Analytics job
3. Observe Exception

Note that my test instance (copy of production) was upgraded from 12.4 through 13.4alpha in succession, so I can't be sure if this was or wasn't happening on any of the v13 versions < 13.4. Let me know if I need to roll back to verify that.

### Versions

* **Rock Version:** 13.4 alpha 1

**Comment by mikedotmundy** [comment]
We are seeing the same exception, and I can verify it was not happening in v13.3.

**Comment by asdf1nit** [comment]
Verified I have the same exception.

**Comment by nairdo** [comment]
We have confirmed that this is an issue that we identified internally and fixed (https://github.com/SparkDevNetwork/Rock/commit/bbdf2fdc6b54b524023ccf2eeb5ef5d94c86c8ce) shortly after v13.4 alpha testing started.  This will be fixed in v13.4 beta.
