### ISSUE TITLE
13.4 alpha Cannot Edit Inactive Schedules

### ISSUE THREAD

**Issue by gonemob** [SparkDevNetwork/Rock#5017]
### Description

Once a schedule is inactive, it's no longer editable from /Schedules.

### Steps to Reproduce

1. Goto https://prealpha.rocksolidchurchdemo.com/Schedules
2. Edit _any_ active schedule and save it
3. Click on _any_ other schedule and get the focus off of the just edited schedule. 
4. Observe the schedule you just edited is no longer reachable5. 
5. Observe via dev tools the classes "is-inactive-not-allowed" has been added to the list item element and "not-allowed" added to the enclosed span element
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/13141251/168922316-aff70ec1-8c9c-409c-9e51-4502c5a89cd4.png">

**Expected behavior:** 

1. Inactive schedules are still editable.

**Actual behavior:** 

Inactive schedules are not editable using the gui.  Not able to reproduce this on Rocksolid running v13.2.

### Versions

* **Rock Version:** [1.13.4.1 & 1.14.0.10]  
* **Client Culture Setting:** [En]

**Comment by JimMichael** [comment]
This doesn't appear to be specific to Schedule trees... I am able to dupe it on a Group Tree, too. Simply by inactivating a group, I can no longer click on it and the pointer turns into a cicle-slash:
![image](https://user-images.githubusercontent.com/3903408/168924168-eae7a4ae-9688-45e7-898b-9827f8d80309.png)

**Comment by nairdo** [comment]
This fix will be in the v13.4 beta.
