### ISSUE TITLE
Key Value List using Defined Type displays Inactive Defined Values

### ISSUE THREAD

**Issue by treusch** [SparkDevNetwork/Rock#5019]
**Description:** Key Value List using Defined Type displays InActive Defined Values on workflow forms. We haven't had a need to use these on Registration Forms, but my assumption is the same thing would likely happen.

(This is my first Issue report through GitHub. My apologies if I did not include everything I should have. Happy to provide any additional info needed or do any other tests that would be helpful.)

### Prerequisites
* Reproduced on demo site [X]
* Experienced this on our current production site [X]
* Experienced this on our current dev site [X]
* Searched github issues and found old issues for Key Value List but none matched what we are seeing [X]

### Steps to Reproduce

1. Create (or edit an existing) defined type and make one of the defined values inactive.

![KeyValueListDefinedType](https://user-images.githubusercontent.com/38530809/169089809-caefbb42-ca00-401e-9f62-9dea1cc8b250.png)
2. Add an attribute to a workflow whose field type is Key Value List and choose the Defined Type from step 1 as the source for the Key Value List values.
3. Display that attribute on a user entry form in the workflow.
4. Run the workflow.

![KeyValueListPic1](https://user-images.githubusercontent.com/38530809/169089831-1fd82a81-ca62-4abb-ad26-62fe0c741331.png)

**Expected behavior:** 

1. Create (or edit an existing) defined type and make one of the defined values inactive.
2. Add an attribute to a workflow whose field type is Key Value List and choose the Defined Type from step 1 as the source for the Key Value List values.
3. Display that attribute on a user entry form in the workflow.
4. Run the workflow and only see active values from the defined type.

**Actual behavior:** 

1. Create (or edit an existing) defined type and make one of the defined values inactive.
2. Add an attribute to a workflow whose field type is Key Value List and choose the Defined Type from step 1 as the source for the Key Value List values.
3. Display that attribute on a user entry form in the workflow.
4. Run the workflow and you see all values from the defined type, even the inactive one(s).

### Versions

Production
* **Rock Version:** Rock McKinley 11.4 (1.11.4.3)
* **Client Culture Setting:** en-US

Dev
* **Rock Version:** Rock McKinley 12.8 (1.12.8.1)
* **Client Culture Setting:** en-US

Demo Site
* **Rock Version:** 13.2 (1.13.2.2)
* **Client Culture Setting:** en-US

**Comment by treusch** [comment]
Thank you so much! Is this something we have to wait for 13.5 for? Or can
we fix our code now?

Tina Reusch
Grace Church Central Staff
***@***.***,-82.2779609,15z/data=!4m5!3m4!1s0x0:0xba6f64cfeb28c491!8m2!3d34.8635019!4d-82.2779609>

864.567.1934 <8645671934>
gracechurchsc.org  <https://gracechurchsc.org/>
[image: Grace Church] <https://gracechurchsc.org/>

**Comment by jonedmiston** [comment]
@treusch  unfortunately since this fix is in the backend code you'll need to wait for the update.
