### ISSUE TITLE
"Disable Access to Schedule Toolbox" is disabling the Toolbox on the Person Profile as well as in their Account

### ISSUE THREAD

**Issue by KCKurz** [SparkDevNetwork/Rock#5020]
**Description**
When "Disable Schedule Toolbox Access" is selected in the Group settings, the "Schedule Toolbox" on the group member's Person Profile page does not display the group to set their preferences. 

**Steps to Reproduce**

1. Log into https://rocksolidchurchdemo.com
1. Go to [Serving Teams > Ushers](https://rock.rocksolidchurchdemo.com/page/113?GroupId=110&amp;ExpandedIds=)
1. Click Edit to edit the Group settings, go to Scheduling, select Disable Schedule Toolbox Access and save
1. Ted Decker is a member of this group, on his[ Person Profile > Groups > Schedule Toolbox](https://rock.rocksolidchurchdemo.com/person/4/groups), you now can now no longer see that he is in the Ushers group and as a result you can not set his preferences. 

**Expected behavior**

When "Disable Schedule Toolbox Access" is selected in the Usher group settings, this should only disable Ted from accessing his Schedule Toolbox from inside of his personal account. A staff member should still be able to access the toolbox from within Ted's Person Profile. 

**Actual behavior**

"Disabling the Schedule Toolbox" disables the toolbox in both the person's profile and the person's account. 

In order for staff members to set the preferences for group members, the Schedule Toolbox needs to be enabled in the Usher group > scheduling settings.  This bug was identified as some teams need to disable the option for team members to access the Schedule Toolbox from their own accounts, but in this case, it's either enabled in both places or disabled in both places. 

**Versions**

**Rock Version:** Rock McKinley 13.3 (1.13.3.1)
**Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1202286363927398">image.png</a>

**Comment by nairdo** [comment]
For this solution we'll be making the changes to the "Group Schedule Toolbox v2" block. We will update the Person Profile > Groups page to use this newer block.  **Note**: There will be a new block setting "Override Hide from Toolbox" - When enabled this setting will show all schedule enabled groups no matter what their "Disable Schedule Toolbox Access" setting is set to.  _(This will be configured automatically once the update happens so it should just start working on the internal Rock site.)_
