### ISSUE TITLE
The Check-in search box input should not allow autocomplete for all search types

### ISSUE THREAD

**Issue by jamrphy-bwd** [SparkDevNetwork/Rock#5021]
**Garrett: Please be sure to also add the "Fixed in v13.5" label to the issue when closed.**

### Description
With Search Type set to _Name_ or _Name & Phone_, the check-in search box input element allows browser autocompletion, meaning that values typed in (e.g. phone numbers and names) may be stored by the browser and shown to others as they complete the check-in process.

### Steps to Reproduce
1. Setup check-in with search type _Name_ or _Name & Phone_
1. Go to the check-in site at /checkin
1. Search successfully a few times. I believe the form must submit.
1. See browser autocomplete

**Expected behavior:**

Since people enter their information and check-in kiosks may be used by many different individuals, it seems like autocomplete should be turned off. (by adding HTML attribute _autocomplete="off"_). It is probably best that autocomplete is off whenever there is a process that foresees a singular machine being used by multiple people.

It is already disabled for _Phone_ search types. I would expect it to be disabled across the board.

**Actual behavior:**

Previously-used values are shown.

### Versions
* **Rock Version:** Rock McKinley 13.2 (1.13.2.2)
* **Client Culture Setting:** en-US

**Comment by FrankGrand** [comment]
We see this issue as well and would love it patched!
