### ISSUE TITLE
[Alpha v1.13.4.1] Planned Visit Date displays as Optional regardless of the "Planned Visit Date" block setting

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5022]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [X] Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![visitDateBug](https://user-images.githubusercontent.com/66277785/169695930-ba09889e-1813-423d-a45f-8e944b36f1f6.gif)

### Description
On the Family Pre-Registration block, there's a _Planned Visit Date_ field with a block setting that allows it to be Hidden, set as Optional, or set as Required. Regardless of the block setting, the _Planned Visit Date_ field always shows as _Optional_. I can confirm this block setting / field behaved as intended in v13.3. 

### Steps to Reproduce

1. Go to your instance's Family Pre-Registration page (usually _rock.domain.com/FamilyPreRegistration_)
2. Click _Block Configuration_ in the admin toolbar
3. Click _Block Properties_ on the Family Pre-Registration block
4. Set _Planned Visit Date_ to _Hide_, then click Save on the Block Properties
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/66277785/169696105-61216f26-0532-4695-a18f-ab63f28a7433.png">

5. Refresh the page, and notice how the _Planned Visit Date_ field under _Visit Information_ is visible and not hidden
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/66277785/169696157-ee0616ae-c4d2-4bca-9b90-c14eeed09f95.png">

**Expected behavior:**

I would expect that the _Planned Visit Date_ field would be optional, required, or hidden based on the block settings.

**Actual behavior:**

The _Planned Visit Date_ field is _always_ optional, regardless of the block settings.

### Versions

* **Rock Version:** [Rock McKinley 13.4 (1.13.4.1)]
* **Client Culture Setting:** [en-US]

**Comment by ethan-sparkdevnetwork** [comment]
@leahjennings Thanks for finding this. It happens if the campus selector is not being shown. This will be fixed for 13.4 Beta.

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in 13.4 commit 7b5fc731
