### ISSUE TITLE
Group Leader Toolbox - Adding Members Bug

### ISSUE THREAD

**Issue by adamhann** [SparkDevNetwork/Rock#5024]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![rockrms](https://user-images.githubusercontent.com/23084345/169828721-f336122f-7ed7-4f7f-876a-3342141d7476.gif)

### Description

When adding multiple pending members to a group in the Group Leader Toolbox, after clicking two in a row, it automatically will add a prompt for anyone after the second member. However, it looks like you are still adding the second member. In the example above, you can see it when I approve Alisha Marble, and I get two modals for approving her. Though, the second modal is actually approving Bill Marble. 

### Steps to Reproduce

1. Have a group with 3 or more pending members that you can approve from the Group Leader Toolbox. 
2. Approve the first two members in the Group Leader Tool Box. 
3. After the second group member approval you will see a second modal for the person you just approved. 
4. If you hit ok again it will add the next member to be approved. 

**Expected behavior:**

I would expect this to work that after each modal pop-up and confirmation, it would go back to the original list to select the next person to approve. 

**Actual behavior:**

After adding the second group member approval, it pops up a modal for the same person that was just approved but is actually approving the third person on the list. We've had issues with this and our Group Leaders who have lots of new people in their groups. Not everyone is ready to be approved and our Group Leaders do not have the ability to fix the mistake by making the member pending again. 

Ideally, we'd have a check box on the Pending member's list where we could select multiple people at once and either approve or deny their membership to the group. (I can put that into the Ideas section on Rock's website)

### Versions

* **Rock Version:** 13.2
* **Client Culture Setting:** en-US

**Comment by adamhann** [comment]
@ethan-sparkdevnetwork Is it correct to assume that if this was fixed in 13.7 that it should also be in v14?

**Comment by ethan-sparkdevnetwork** [comment]
@adamhann Yes, it is also fixed in 14.0.
