### ISSUE TITLE
admin.venuechurch.com  is not working at all. We need to find out what we need to do to get our Rock system back up and working. Please help us resolve this issue.. 

### ISSUE THREAD

**Issue by PMP824** [SparkDevNetwork/Rock#5025]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it at https://community.rockrms.com/ask or via Chat https://community.rockrms.com/chat

If you're looking for support for Rock there are a lot of options, check out:

* User Documentation &mdash; [Rock Manuals](https://community.rockrms.com/documentation)
* Q&A Message Boards &mdash; [Ask Rock, Q&A](https://community.rockrms.com/ask)
* Chat &mdash; [Join the Rock Community in Chat](https://community.rockrms.com/chat)
* Developer Documentation &mdash; [Rock Developer Documentation](https://community.rockrms.com/Developer)
* FAQ &mdash; [Rock FAQs](https://www.rockrms.com/faq)
* Full Service, Paid Support &mdash; [Rock Partners](https://www.rockrms.com/partners)

**Comment by leahjennings** [comment]
@PMP824 these Github issues are only for bugs that are found within Rock, not for questions or one-off issues that arise for the end user. You're best course of action to get help would be to hop onto the [Rock community chat](https://community.rockrms.com/chat) and post your question/issue details in the #troubleshooting channel. There's a ton of people that hang out in chat who love to help others with questions / issues that come up.

**Comment by jonedmiston** [comment]
@PMP824 seconding @leahjennings recommendation to jump into the community chat for help.
