### ISSUE TITLE
Universal Search causes Server Error

### ISSUE THREAD

**Issue by NikkiAZ** [SparkDevNetwork/Rock#5026]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
Alpha Testing v 13.4
Using Universal Search produces the following error page
![Screen Shot 2022-05-23 at 1 08 24 PM](https://user-images.githubusercontent.com/88405795/169899304-a5889e1c-636a-4e67-9b33-c0f3dc87a372.png)

### Steps to Reproduce

1. Select 'search' as method of searching
2. Type in anything to search for (tried llc,ltd to look for businesses but also tried people names and got the same error screen.)
3. Press enter and get the above Server Error Screen

**Expected behavior:** 
The appropriate search tp populate

**Actual behavior:** 
Server Error page

### Versions

* **Rock Version:** 13.4
* **Client Culture Setting:** en-US

**Comment by leahjennings** [comment]
I am unable to reproduce this on our alpha testing instance. Search works as expected.

**Comment by jonedmiston** [comment]
@NikkiAZ I'm wondering if the search index file wasn't copied over somehow when the test environment was created (that file is typically locked by the operating system and sometimes can be difficult). Can you try re-indexing under "General Settings > Universal Search Control Panel". I'm not sure if that will do it, but I'd start there.

**Comment by carriewhite** [comment]
@jonedmiston I'm testing in same environment as Nikki.  I tried to reindex and received missing files error messages.  I ended up copying the entire App_Data/LuceneSearchIndex folder from production 13.3 to test 13.4 and all is well.

**Comment by jonedmiston** [comment]
@carriewhite great thanks for the update!
