### ISSUE TITLE
Inactive Reason and Inactive Reason Note are Greyed-out on Bulk Update

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5027]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When bulk updating the Record Status of a group of people to _Inactive_, the Inactive Reason an Inactive Reason Note appear, however they appear greyed-out. You can still enter information, but it appears as if you will not be able to.

#### A Picture Is worth a Thousand Words
![Screen Shot 2022-05-24 at 11 10 26](https://user-images.githubusercontent.com/23226974/170070665-451dc057-90e1-44f9-b0dc-c8bed025bb1d.png)

### Steps to Reproduce

1. Go to a Group with people in it and click the bulk update button.
2. Expand the Individual Details section.
3. Change _Record Status_ to Inactive and see that the Inactive Reason and Inactive Reason Note are greyed-out.

**Expected behavior:**

Inactive Reason and Inactive Reason Note would not be greyed-out.

**Actual behavior:**

Inactive Reason and Inactive Reason Note are greyed-out.

### Versions

* **Rock Version:** [v13.3, v13.4, v14.0]
* **Client Culture Setting:** [en-US]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1202354847052857">image.png</a>

**Comment by milescarmany** [comment]
@mikedotmundy To add additional clarity, when you enter text into the Reason fields, does it actually save the change too?

**Comment by mikedotmundy** [comment]
@milescarmany Yes, it saves that change too.
