### ISSUE TITLE
Calendar Feeds Export with Incorrect Time Zones

### ISSUE THREAD

**Issue by jacksojourn** [SparkDevNetwork/Rock#5029]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

<img width="1840" alt="Screen Shot 2022-05-26 at 12 14 19 PM" src="https://user-images.githubusercontent.com/44851374/170529423-4b56a6e9-a0df-4e99-b4dc-4cbec4fd29d7.png">

<img width="1840" alt="Screen Shot 2022-05-26 at 11 56 56 AM" src="https://user-images.githubusercontent.com/44851374/170526441-a1b97430-24ba-401d-b8ba-ce90835b27de.png">

<img width="1840" alt="Screen Shot 2022-05-26 at 11 58 31 AM" src="https://user-images.githubusercontent.com/44851374/170526692-353423b8-f7e4-4ecd-a7d1-9f489b2cfdce.png">

<img width="1840" alt="Screen Shot 2022-05-26 at 12 01 59 PM" src="https://user-images.githubusercontent.com/44851374/170527320-6ae3ce51-6d4a-41c1-a9d8-57a2b173c974.png">

### Description

Rock calendar feeds export in Mountain Time even if another time zone is specified in the Rock.

### Steps to Reproduce

1. At Home > System Settings > System Configuration, set the time zone to Eastern Time
2. At Home > Calendars, choose any calendar
3. Choose "Export Calendar Feed"
4. In your calendar app of choice, subscribe to the calendar feed. In my screenshot above, I'm using Apple Calendar on my Mac, but I've reproduced with Fantastical (3rd party calendar app) on my Mac. I actually can't get events to show up at all in Google Calendar!

**Expected behavior:**

Rock calendar events display at same time listed in the Rock.

**Actual behavior:**

Rock events show at a different time than what's listed in the Rock. As you can see in my screenshot above, they're showing in Mountain Time. Despite the fact that the Rock is set in Eastern.

### Versions

Note, the bug is different in my Rock than in the demo Rock. My steps and screenshots above are from the demo Rock, since I don't expect you to want to troubleshoot version 12.

Rock McKinley 12.6 (1.12.6.1)
Client Culture Setting: en-US

**Comment by jacksojourn** [comment]
Possibly related to this issue from the iCal.Net library that I believe you guys are using. https://github.com/rianjs/ical.net/issues/540

**Comment by leahjennings** [comment]
@jacksojourn I was unable to replicate this behavior on our own system (which is running v13.3), but I can replicate it using your provided steps on the demo site running v13.2. Can you verify something on your system for me? In Rock, go to the admin tool bar at the bottom and click on the "i" to access System Information, then click to see the Diagnostics. Is your _System Date Time_ and _Rock Time_ the same? On my v13.3 instance, they are. However on the demo site, they aren't. I'm curious if the calendar generated by the export is using the System Date Time vs the Rock Time.

On my v13.3 system where I _cannot_ reproduce the issue:
<img width="196" alt="image" src="https://user-images.githubusercontent.com/66277785/170541183-30777ea8-2a1b-4b05-8b60-ac7aae3e2a50.png">

On the v13.2 demo site where I _can_ reproduce the issue:
<img width="191" alt="image" src="https://user-images.githubusercontent.com/66277785/170541254-19d66f9e-0fa9-4fb5-93db-a295305a22c5.png">

**Comment by jacksojourn** [comment]
@leahjennings Wow, great call. Nope, they are out of sync.

Hopefully this means it's an easy fix? 😬 

<img width="275" alt="image" src="https://user-images.githubusercontent.com/44851374/170559024-d75e2991-121b-4c3b-b328-b8e8a27c5f26.png">

**Comment by leahjennings** [comment]
Thanks for the follow up! To further test this theory of Rock exporting the calendar feed using the System Date Time vs the Rock Time, would you be able to change the system time of your Rock web server to match the time zone you've set your Rock Time to? Highly recommend this to be done after hours or at a low-use time, as it may need a restart of Rock itself. Then, once you've confirmed that in Diagnostics both the System Date Time + Rock Time match, try recreating your issue again.

**Comment by jacksojourn** [comment]
Yes, definitely! If I make that change (say at midnight), any danger in 
leaving the system time changed? Or should I test and then quickly 
revert?

**Comment by leahjennings** [comment]
@jacksojourn were you able to make the system time change and re-test to see if that fixed your calendar feed export issue?

**Comment by jacksojourn** [comment]
@leahjennings It's working now on Apple Calendar, but on Google Calendar, it still shows events in incorrect times, as if they are set in UTC +0.

**Comment by leahjennings** [comment]
Can you send a screenshot of what that looks like on Google Calendar and how you're subscribing to Rock's calendar feed? I went to https://calendar.google.com and added a new calendar by URL, and when the events were fetched they are in the time zone I would expect.

**Comment by jacksojourn** [comment]
@leahjennings Sure! Thanks for your help with this. I was afraid this was a broken feature but now really hopeful I could get it to work for my staff…

1. In Google Calendar, in the sidebar, by **Other Calendars**, press the **+.**
2. Select **From URL.**
3. Paste in the feed from the Rock. Here is the one I'm using from our Rock: `https://www.sojournmidtown.com/GetEventCalendarFeed.ashx?CalendarId=1`

By the way, I notice that once created, it shows the time zone as GMT+0, which isn't correct:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/44851374/171518947-d576698b-749d-489f-9443-f451dd29d510.png">

This is how it shows up in Google Calendar:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/44851374/171518854-8b592f2e-d787-4d88-9ba7-5feb49516bc1.png">

And for reference, this is how it shows up correctly in Apple Calendar:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/44851374/171518806-562480e8-251c-419e-8582-b94c6391dd5a.png">

**Comment by jacksojourn** [comment]
@leahjennings Thanks! I'll talk to our developer. Really appreciate the guidance. Glad it's not a Rock bug.

**Comment by timlem** [comment]
Is anyone seeing this on v14 still? I created an event after updating to v14 for 10a(est) that lasts 6 hours. It exports to google calendar and mac calendar as 5a-11a
