### ISSUE TITLE
Styling Issue w/Defined Values FieldType

### ISSUE THREAD

**Issue by FrankGrand** [SparkDevNetwork/Rock#5034]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/6911214/171458899-b1bb1b9d-2fb3-4146-9a52-76de2117ce18.png)

### Description

It looks like a recent browser updates have broken styling for the internal Rock theme for the Defined Values field type. Only one checkbox is visible (seems like it's actually the checkbox for the last option in the list.)  Bug exists in Chrome, Edge and at least one other Chromium-based browser, and does not occur in Firefox. Confirmed also that it's visible both in pre-alpha and in 13.2 demo server.

It seems to only occur when "Allow Multiple Values" is set to "Yes" and "Repeat Columns" are set to 1. Any other value (including blank) displays the checkboxes properly.

**Expected behavior:**

To be able to select all values of the Defined Value

**Actual behavior:**

Only have one checkbox for the last item in the list

**Comment by markewampler** [comment]
We have this problem for Radio Buttons as well.  It only happens when you have 1 column on.  If you remove the 1 column it fixes it.

**Comment by tstephens17** [comment]
This is an issue with Chrome. I didn't see the issue and then updated and the issue presented itself.

Chrome is up to date
Version 102.0.5005.63 (Official Build) (64-bit)
