### ISSUE TITLE
FontAwesome Icon Not Working On Panel ShortCode

### ISSUE THREAD

**Issue by GordonArber** [SparkDevNetwork/Rock#5038]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting? 

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.
![Screen Shot 2022-06-08 at 12 28 22 PM](https://user-images.githubusercontent.com/19920780/172679947-b42382d5-2cc7-46ff-9161-bd6d4d242069.png)

![Screen Shot 2022-06-08 at 12 28 33 PM](https://user-images.githubusercontent.com/19920780/172679986-f3dc01d9-9e65-4d2c-87c3-7802449043eb.png)

### Description

_[Write a clear and concise description and include **full window** (non-partial) screenshots. FYI: You can just copy and paste an image directly into here and it will magically upload.]_

When implimenting the system Lava ShortCode: '{[ panel title:'ShortCode' icon:'fa fa-star' ]}' It doesn't actually show the icon on the panel after you save.

### Steps to Reproduce

1. Go to 'Edit HTML Block'
2. Paste: `{[ panel title:'ShortCode' icon:'fa fa-star' ]}
  
This is a super simple panel with the short code.
 
{[ endpanel ]}

<div class="panel panel-default">
  
  <div class="panel-heading"><h1 class="panel-title"><i class="fa fa-star"></i>div</h1></div>

  
  <table class="table">
    This is a super simple panel with divs and a table.
  </table>
</div>` into the code block
3. Click 'Save' button
4. See there is only an icon on the 'div' panel

**Expected behavior:**

_[A clear and concise description of what you expected to happen.]_
There should be an icon included in the Lava ShortCode

**Actual behavior:**

_[A description of what actually happened.]_
The icon area is blank on the panel

### Versions

* **Rock Version:** [Rock McKinley 13.2 (1.13.2.2)]
* **Client Culture Setting:** [en-US]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1202422063369650">image.png</a>

**Comment by jonedmiston** [comment]
This is somewhat by design, but I can see how it could be confusing. Rock typically uses Bootstrap panels with the style class of `panel-block`. We made a design decision in v12 to hide the icons on the internal theme on `panel-block` panels.  (The Stark theme intentionally hides the panel heading and borders too with the thought that these panels are an internal admin construct.)

To make this less opinionated we can change the short-code to use a `panel-default` class instead. This will have the effect of showing the icon internally and showing the panel 'chrome' on the external Stark theme.
