### ISSUE TITLE
Installation Breaks after Download Successful

### ISSUE THREAD

**Issue by jmo3** [SparkDevNetwork/Rock#504]
After "Download Successful", and during the Database Installation page, the installer mysteriously breaks and will not finish.  No tables are created in the MSSQL database.  Database creds were confirmed correctly previously.

Windows Server 2012 R2
SQL Server 2012 Express

I see one Error in App_Data/Logs/RockExceptions.csv:
System.TypeInitializationException,"The type initializer for 'System.Data.Entity.MigrateDatabaseToLatestVersion`2' threw an exception."

**Comment by bradbamford** [comment]
Just ran into this myself; Like @jmo3 said, this should be caught during the Install Wizard.
A simple verification in the wizard would have saved me an hour of work today.
