### ISSUE TITLE
Registration passed as Entity into workflow triggered by each Registrant

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5042]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

![image](https://user-images.githubusercontent.com/66277785/174457588-402bde0f-4974-447d-8ed3-1b0cab0c5e7a.png)

### Description

When a workflow is set on an Event Registration Template to trigger for each Registration Registrant, the `Entity` Lava variable that is passed into the _Set Attribute From Entity_ action is actually the `Registration` and not the `RegistrationRegistrant`.

### Steps to Reproduce

1. On the demo site, navigate to Admin Tools > General Settings and click on _Workflow Configuration_
2. Click on the _Samples_ category and then click the + button to create a new workflow type
3. Add 3 attributes to the workflow type
   - Attribute 1: Registration Registrant Id
      - Key: RegistrationRegistrantId
      - Field Type: Integer
      - Show in Grid: ✅
   - Attribute 2: Registration Id
      - Key: Registration Id
      - Field Type: Integer
      - Show in Grid:  ✅
   - Attribute 3: Entity Id
      - Field Type: Integer
      - Show in Grid:  ✅

<img width="932" alt="image" src="https://user-images.githubusercontent.com/66277785/174457272-57dc2cbd-0c62-44e2-9dd6-e3f5e526f14d.png">

4. Add one action of type _Set Attribute From Entity_ to the _Start_ activity 
5. Set the Attribute in that action to _Entity Id_
6. Set _Use Id instead of Guid_ to `Yes`
<img width="928" alt="image" src="https://user-images.githubusercontent.com/66277785/174457308-9917445a-6662-4b8c-bdec-dc45678cd7e9.png">

7. Save the workflow
8. Navigate to Tools > Event Registration and expand the _Connection_ category
9. Click on the `Baptism` template then click Edit
10. Expand _Details_, then under _Registrant Workflow_ select the workflow created in the earlier steps, then save the template
<img width="929" alt="image" src="https://user-images.githubusercontent.com/66277785/174457341-70e99bde-a068-4130-8569-ee20d5255dd2.png">

11. Create a new instance of `Baptism` (give it a name, you can leave everything else blank)
12. Click on _Linkages_ to give it a URL (I used a slug of `testingtriggers`)
<img width="930" alt="image" src="https://user-images.githubusercontent.com/66277785/174457380-37f6c873-c332-4218-8d51-12ae20886040.png">

13. Navigate to `https://rock.rocksolidchurchdemo.com/registration/testingtriggers`
14. Register 2 people in the same registration (doesn't matter who)
15. Back in Rock, navigate to Admin Tools > General Settings and click on _Workflow Configuration_
16. Expand _Samples_ and click on the workflow created earlier
17. Click on the _Manage Workflows_ button

**Expected behavior:**

Because the workflow is being triggered _for each_ registration, I would expect the `Entity` Lava variable in the _Set Attribute from Entity_ action would represent the `RegistrationRegistrant` that triggered the workflow.

**Actual behavior:**

The `Entity` Lava variable that is being passed into the workflow action actually represents a `Registration`.

### Versions

* **Rock Version:** [Rock McKinley 13.4 (1.13.4.1)]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Oops.  That is our [my] fault.  We will fix this so that the 'registrant' entity is used when launching the workflow associated to the "Registrant Workflow" setting in the template.  Because this change might impact people who have already created a workflow that works around the bug, we will add a "Heads-Up" note to the release package which will read something like:

> We've fixed a bug with the "Registrant Workflow" in the Event Registration Templates.  From now on the Entity that is passed to the workflow will be the **Registration Registrant** — not the _Registration_ entity.  Please verify/change any corresponding workflows that are configured in your registration templates.

**Comment by MatthewKyle22** [comment]
@nairdo any chance this will be released soon?

**Comment by markewampler** [comment]
@nairdo @MikeDPeterson This seems to be functioning in the "old" way for Obsidian blocks.  I just tested it on the Demo site on 15.1 and it still passes in the "Registration" Entity to the "Registrant" workflow instead of the "Registrant" entity.  It works great on the "Non-Obsidian" Event Registration Entry Block, but the Obsidian Event Registration Entry block somehow uses the old code that passes the wrong thing in.

Not sure I need to submit a new bug for this.  Happy to do what would be helpful here.

**Comment by MatthewKyle22** [comment]
@nairdo @MikeDPeterson I've encountered what Mark Describes as well with using the new Obsidian block.

**Comment by chead4** [comment]
@MatthewKyle22 & @markewampler Thanks for letting us know that this is still an issue. I am reopening this issue and and we will investigate further.
