### ISSUE TITLE
Mobile Connections Viewer Filter won't stay selected

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#5044]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

When going to connections in the mobile app, it always defaults to showing all connections. When you click the filter and select "Only show opportunities with requests assigned to me" and leave the page, you have to reapply the filter.
### Steps to Reproduce

1. Go to a connection opportunity list in mobile app.
2. Click on filters and turn on the only show assigned to me
3. Go back a page or down deeper in the page and that filter is turned off.

**Expected behavior:**

I would expect it to remember my choice and apply it to all the pages so I don't have to click only show me mine everytime I go to any of the connection view pages.

**Actual behavior:**

Everytime you go to a connection page you have to reapply the filter

### Versions

* **Rock Version:** [13.3]
* **Client Culture Setting:** [en_US]
Not sure where to find our shell version, but I've been told it's v3 I think

**Comment by bradencohen** [comment]
Although this isn't necessarily a bug, more of a feature, we added support for the ConnectionRequestList & ConnectionOpportunityList blocks to save the selected filter as a BlockUserPreference. Since this is also a mobile update, it will not only require v13.7 of Rock but mobile shell v4. Please note you must be logged in or else the preference saving won't be called.
