### ISSUE TITLE
LINQ Error when using Computed Lava fields in "Select" parameter of an Entity command when security is disabled

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5045]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [X] Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

<img width="772" alt="image" src="https://user-images.githubusercontent.com/66277785/174893084-1ff13afb-3d35-4b00-b838-a209f444bd1a.png">

### Description

In an entity command using the new `select` parameter to get a computed field from the model while also specifying `securityenabled:'false'`, a LINQ-related error is returned. If you specify `securityenabled:'true'` (or just delete that parameter so it is the default behavior), the entity command processes as expected.

Running the following code, as expected, returns a list of names of those belonging to the _RSR - Rock Administration_ group (Id: 2).
_Note: only added `securityenabled:'true'` for clarity, that's not actually needed since that is the default behavior_

```
{% groupmember where:'GroupId == 2' select:'new ( Person.FullName AS FullName )' securityenabled:'true' %}
    {% for gm in groupmemberItems %}
        {{ gm.FullName }}<br>
    {% endfor %}
{% endgroupmember %}
```

![image](https://user-images.githubusercontent.com/66277785/174893834-79f4704a-a719-4f6b-b1f1-0f15f18d1d2c.png)

Running the following code returns the following LINQ error: `The specified type member 'FullName' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported.`
_Note: the only thing that changed is `securityenabled:` is set to `false`_

```
{% groupmember where:'GroupId == 2' select:'new ( Person.FullName AS FullName )' securityenabled:'false' %}
    {% for gm in groupmemberItems %}
        {{ gm.FullName }}<br>
    {% endfor %}
{% endgroupmember %}
```

<img width="769" alt="image" src="https://user-images.githubusercontent.com/66277785/174894507-851204a5-5cfc-41ae-9334-21be3bff5916.png">

What's _really_ fascinating is that `Person` itself is a computed field on the `GroupMember` entity. Navigating down that path, like `Person.Id` works fine. I've also tested with `GradeFormatted`, `Age`, and `CreatedByPersonName`, and they all return the same error.

### Steps to Reproduce

1. On a server running with the Lava engine set to Fluid, go to Lava Tester (or any HTML block with `RockEntity` enabled)
2. Copy/paste the following code into the block and run/save it
```
{% groupmember where:'GroupId == 2' select:'new ( Person.FullName AS FullName )' securityenabled:'false' %}
    {% for gm in groupmemberItems %}
        {{ gm.FullName }}<br>
    {% endfor %}
{% endgroupmember %}
```

**Expected behavior:**

I would expect the results to be the same as when the entity command is ran without specifying `securityenabled:'false'`.

**Actual behavior:**

A LINQ-related error is returned.

### Versions

* **Rock Version:** [Rock McKinley 13.4 (1.13.4.1)]
* **Client Culture Setting:** [en-US]

**Comment by leahjennings** [comment]
@jonedmiston absolutely! I'll get something written up and to you for review this week!

**Comment by jonedmiston** [comment]
Solution: Updating docs to reflect this new insight.

**Comment by nlBayside** [comment]
Just wondering if there has been any updates on documentation for this. As I'm testing out Fluid in one of our environments I also experienced this problem. I think it would be beneficial so that others don't run into the same issue when using the new feature.

For me, it's a bit confusing because the Model Map shows that certain properties *are* accessible through Lava/Fluid; however, that's obviously not the case when using the new select filter on entities. Hopefully something can be written up in the Lava pages for this. Thanks!

**Comment by leahjennings** [comment]
@nlBayside there was an item added to the Lava Entity [_Special Cases_ ](https://community.rockrms.com/lava/commands/entity-commands)section at the bottom that reads:
_With the select parameter, you can specify computed fields as data elements in the anonymous type as long as security is enabled. If you also specify securityenabled:'false', computed fields are not allowed in the anonymous type. Because the person entity by default has security disabled, computed fields can't be specified in a select anonymous type when accessing the person entity._

Does that help clarify what is possible with what you were trying to accomplish? Did you see that documentation and still feel confused?

**Comment by nlBayside** [comment]
@leahjennings thanks for the heads up! I did see that section, but must've missed that part.

I think the documentation would be clearer to the end-user if that were in the "Select" section. I'm guessing this also applies to the "selectmany" parameter too, so that might not be the best solution. However, I do think it would be beneficial for those connected pieces of information to be close together.
