### ISSUE TITLE
Workflow Action of 'Benevolence Request Add' is not working (v13.4)

### ISSUE THREAD

**Issue by jorians** [SparkDevNetwork/Rock#5047]
Workflow Action named 'Benevolence Request Add' is throwing out the following error -
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.BenevolenceRequest_dbo.BenevolenceType_BenevolenceTypeId". The conflict occurred in database "RockUp-SQLMI-061322", table "dbo.BenevolenceType", column 'Id'. The statement has been terminated.

This process has been tested on both v13.2 (Rock Demo) and v14.0 (Rock Pre-Alpha).

On v13.2 the WF Action works as expected.  On v14.0, the WF Action FAILS, as it does on v13.4

**Comment by leahjennings** [comment]
@jorians thanks for submitting this! The team is aware of this one with issue #5046, so I'm going to close this one as a duplicate.
