### ISSUE TITLE
TransactionEntry V2 (RockV13.4):  Making Payment Using A Saved Payment Method Without A GatewayPersonIdentifier Will Fail

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/Rock#5052]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Rock V13.4 introduced and issue with some (but not all) saved payment methods in the TransactionEntryV2 block. From what I can tell this issue presents itself with saved payment methods that do not include a GatewayPersonIdentifier. 

The user sees the following error message if they attempt to make a payment using a saved payment method that does not have a GatewayPersonIdentifier.
![image](https://user-images.githubusercontent.com/605691/175658742-83605a02-a891-429d-b8a8-ca3ec6850249.png)

My temporary workaround is to update the [TransactionEntryV2.ascx.cs file](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Finance/TransactionEntryV2.ascx.cs#L2782) to use the code that was in the pre-13.4 block. I've included a screenshot of the change below, in essence it amounts to adding `  paymentInfo.GatewayPersonIdentifier = financialPersonSavedAccount.ReferenceNumber;` back into the code. This update causes the payments for these saved payment methods to perform normally again.
![Screen Shot 2022-06-23 at 1 45 08 PM](https://user-images.githubusercontent.com/605691/175657020-fe7b2c67-4c5a-4734-b74c-92eb0c0294ff.png)

If it helps to provide any context this is what we received back from NMI when we reached out to them about the issue:

> After investigating this issue,  It looks like you are creating a vault record using source_transaction_id. You will need to pass the transaction ID to pull in the payment data. You're unable to store vault records without this. 

> RESPONSE
> < response=3&responsetext=Billing Information missing REFID:3155626951&authcode=&transactionid=&avsresponse=&cvvresponse=&orderid=&type=&response_code=300

### Steps to Reproduce

1. Go to a page with a TransasctionEntryV2 Block on V13.4
2. Attempt to make a gift using a saved payment method that does not have a GatewayPersonIdentifier.
3. See error shown above

**Expected behavior:**

Payments successfully process successfully when using saved payment methods that do not have a GatewayPersonIdentifier.

**Actual behavior:**

Payments show an error message when using saved payment methods that do not have a GatewayPersonIdentifier.

### Versions

* **Rock Version:** Rock McKinley 13.4 (1.13.4.1)
* **Client Culture Setting:**  en-US

**Comment by asdf1nit** [comment]
I can confirm that the transaction fails without this fix being added. On our server there are 2837 saved accounts and 1152 of them have a null GatewayPersonIdentifier value.

**Comment by dataCollegechurch** [comment]
@bscottdavis - how do saved payments with a null GatewayPersonIdentifier get introduced?

**Comment by bscottdavis** [comment]
@dataCollegechurch Yes, the "older NMI gateway transaction" theory lines up with what I am seeing on my end. It appears that all of the saved payments with a null GatewayPersonIdentifier are from older transactions. Newer saved payment methods do not have the issue.
