### ISSUE TITLE
Scripturize Shortcode Issue with Verses in John

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5053]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
The Scripturize Shortcode is creating an invalid url for all passages in John, when using YouVersion. (1 John, 2 John, and 3 John all work properly.) The link displays `https://www.bible.com/bible/116/JN.3.16.NLT` and it should display `https://www.bible.com/bible/116/JHN.3.16.NLT`.

This is only an issue in the Liquid Engine. It is working properly in the Fluid Engine.

#### A Picture Is worth a Thousand Words
<img width="1173" alt="Screen Shot 2022-06-24 at 17 13 26" src="https://user-images.githubusercontent.com/23226974/175668176-886db8dc-f914-45b3-97f1-a7e07cbe3e8b.png">

### Steps to Reproduce

1. Create an HTML Block.
2. Insert this code:
```
{[ scripturize defaulttranslation:'NLT' landingsite:'YouVersion' cssclass:'scripture' ]}
    John 3:16
{[ endscripturize ]}
```
3. Save, then attempt to click link and see url is invalid, so it redirects you to Genesis 1:1.

**Expected behavior:**

Url would be valid.

**Actual behavior:**

Url is invalid.

### Versions

* **Rock Version:** [v13.3, v13.4]
* **Client Culture Setting:** [en-US]

**Comment by leahjennings** [comment]
@mikedotmundy I just tried reproducing this with the given code on the demo site running v13.5 with both the DotLiquid and the DotLiquid (with Fluid verification) engines, and the URL comes back as expected with the URL ending in `JHN.3.16.NLT`. I also tested on our production instance running v13.4 and the Fluid engine, and it also works as expected (like you said).

Do you have any other steps you may have taken that reproduces it? Are you able to reproduce it on the demo site since it's been upgraded to 13.5?

**Comment by mikedotmundy** [comment]
@leahjennings It seems to be fixed! In my production instance running v13.4, it is still an issue. 

On the demo site and on my dev site both running v13.5, it is fixed.

**Comment by nairdo** [comment]
@mikedotmundy  I know it's rare, but it could also be a transient issue on the bible.com system.  Can you verify once more that is really is still broken on your v13.4 system?  I'm testing on a production v13.4 system running the "DotLiquid (with Fluid verification)" engine and it's also working correctly for me too:

![image](https://user-images.githubusercontent.com/383807/177661811-951907eb-f723-4fd5-954e-727831728493.png)

**Comment by mikedotmundy** [comment]
@nairdo The screenshot in my original post is from when the demo site was at v13.3.

Here is a page on my production site at v13.4:
<img width="1728" alt="Screen Shot 2022-07-06 at 21 58 30" src="https://user-images.githubusercontent.com/23226974/177673868-f05b6e7a-c475-445f-b20c-6a6a9ea5301d.png">

Here is the url so you can see it live: `https://bedfordalliance.church/care/repentance/the-truth-about-confession-and-repentance`

And, oddly, it is no longer working properly on my dev site on this page too, which is on v13.5:
`https://dev.bedfordalliance.church/care/repentance/the-truth-about-confession-and-repentance`

When I tested this about 4 hours ago, it WAS working properly on my dev site - it now is NOT working properly.

**Comment by mikedotmundy** [comment]
@leahjennings Thank you for figuring all that out! I do in fact have 1 John references on the page, although the only difference is I have both the John and 1 John references inside the same `{[ scripzturize ]}` `{[ endscripturize ]}` brackets.
