### ISSUE TITLE
Meeting Details panel disappears after trying to set a schedule if no "Location Selection Mode" is enabled

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5061]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A ~~Picture~~ GIF Is worth a Thousand Words

![issue](https://user-images.githubusercontent.com/66277785/177619258-d227a5ce-45de-48f8-95a5-5f7bf34d3838.gif)

### Description

If a Group Type is set to take attendance and allows the schedule to be changed on a per-group basis, the `Meeting Details` panel on the Edit Group page disappears whenever you click one of the schedule options. This only occurs if there are no _Location Selection Modes_ enabled. Once you set a _Location Selection Mode_ on the group type, the `Meeting Details` panel stays visible as expected.

_Very similar to issue #5055, but it was closed because there were no reproduction steps._ 

### Steps to Reproduce

1. On the demo site, go to Admin Tools > General Settings, then click Group Types
2. Create a new Group Type, name it Staff, and leave everything default except for under _Attendance / Check-In_ check the following
   - Takes Attendance
   - Send Attendance Reminders
   - All the Group Schedule Options
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/66277785/177619722-1371a302-530a-4667-8e8c-015cf50c677a.png">

3. Go to People > Group Viewer
4. Create a new top-level group named Staff of type Staff and hit Save
5. Edit the group just created, expand _Meeting Details_, and click one of the Group Schedule options

**Expected behavior:**

I would expect to be able to set a schedule under Meeting Details without having to specify a location mode as well. The Meeting Details panel should stay visible to allow me to set a schedule.

**Actual behavior:**

The Meeting Details panel disappears when trying to add a schedule to a group.

### Versions

* **Rock Version:** [Rock McKinley 13.4 (1.13.4.1), Rock McKinley 13.5 (1.13.5.1)]
* **Client Culture Setting:** [en-US]

**Comment by notGerryMiller** [comment]
We are experiencing this again. Let me know how we can help.
