### ISSUE TITLE
Filter Locations By Location Selection Strategy Workflow Action Bug: Unreachable Code

### ISSUE THREAD

**Issue by courtneycooksey** [SparkDevNetwork/Rock#5062]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

[This](https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.13.4/Rock/Workflow/Action/CheckIn/FilterLocationsByLocationSelectionStrategy.cs#L162) line of code
```
if ( location.Schedules.Contains( selectedSchedule ) )
```
Is causing an error because the object in selectedSchedule and the ones in location.Schedules are not exactly the same so it is always false even if the schedules within have the same Id. This check should be done on the id instead of the object. I can submit a PR shortly. 

### Steps to Reproduce

1. Configure the Location Selection Strategy attribute on the group type for your check in group
2. Set strategy to "Fill in Order" on check in area 
3. Set up multiple locations on your check-in group
4. Configure the schedules so that no location will match every possible schedule
5. Check in to multiple schedules
6. See prompt to pick location instead of first location being auto-selected

**Expected behavior:**

Location is auto-selected

**Actual behavior:**

Location prompt is displayed

### Versions

* **Rock Version:** 13.4
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
Thanks @courtneycooksey! We had to do a shuffle with the 13.6 version so this will actually be in 13.7.
