### ISSUE TITLE
Filter Locations By Location Selection Strategy Logic Issue: Unexpected Selection Behavior

### ISSUE THREAD

**Issue by courtneycooksey** [SparkDevNetwork/Rock#5064]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

I think there is an issue with the logic in [this](https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.13.4/Rock/Workflow/Action/CheckIn/FilterLocationsByLocationSelectionStrategy.cs#L135) section of code. This is for the Filter Locations By Location Selection Strategy Workflow Action. This section of code looks to see if any of available locations are available for all of the selected schedules and uses that location. This behavior seems okay for the Balance option of the Selection Strategies but not for the Fill in Order option. 

### Steps to Reproduce

1. Set up two schedules for check-in (i.e. 8:30, 9:45)
2. Configure your check-in group type to have the location selection strategy attribute
3. Set strategy to Fill in Order for the group type of the check-in groups you will be using
4. Set up multiple locations for your check-in group
  - Example Group: Kindergarten
  - Example Locations: Kindergarten Room A, Kindergarten Room B, K-1 Overflow Room 
  - Ensure Overflow room is last in the list because it is not the first choice for filling the rooms in order
 5. Configure the first schedule for Kindergarten Room A and K-1 Overflow Room are available 
 6. Configure the second schedule for Kindergarten Room B and K-1 Overflow are available 
 7. Check in to both services
 8. See you are automatically placed in K-1 Overflow for both services. 

**Expected behavior:**

With Fill in Order selected, I would expect that until Kindergarten Room A and Kindergarten Room B are full, kids checking in would be placed there instead of the K-1 Overflow Room. Then once the rooms were full at their respective services we would go to the next available K-1 Overflow

**Actual behavior:**

K-1 Overflow is selected for kids even when Kindergarten A or B Rooms are not full because it is the only location available at all the selected schedules. 

This behavior might make sense for the balance option, but definitely not the Fill in Order seeing as it bypasses the given order. I haven't tested the balance option, because we personally don't need it, the only reason I can think of it not making sense for balance is if this causes it to bypass room counts. Like I said, I haven't tested it so I don't know if it is doing that or not. 

### Proposed Solution

Send the value attributeLocationSelectionStrategy to the FilterLocationSchedules function and check if it is equal to balance before running that section of code line 135 to 153. This is assuming it does make sense for balance and isn't causing any weird behavior for that option...
```
if ( attributeLocationSelectionStrategy == CheckinConfigurationHelper.LocationSelectionStrategy.Balance )
```

### Versions

* **Rock Version:** 13.4
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
We spoke internally and then discussed this a bit with Courtney.  When checking in a child for multiple services, the Location Selection Strategy's 'load balance' and 'fill in order' will put a child in the **_same_** classroom for both services -- and that is by design.  We suggested an Idea be opened (over at http://community.rockrms.com/Ideas) to request a new feature to allow controlling that behavior.  She agreed and will be doing that shortly.
