### ISSUE TITLE
Filter Locations By Location Selection Strategy Logic Issue: Not Excluding Schedules

### ISSUE THREAD

**Issue by courtneycooksey** [SparkDevNetwork/Rock#5067]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
   
### Description

This is all assuming #5062 has been addressed and this section of code runs. 

Lines 157-184 of [FilterLocationsByLocationSeletionStrategy.cs](https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.13.4/Rock/Workflow/Action/CheckIn/FilterLocationsByLocationSelectionStrategy.cs#L157) Workflow Action has some issues in filtering out locations per schedule. 

First is [170](https://github.com/SparkDevNetwork/Rock/blob/438569553845a9add004bb1570963da3bd986f42/Rock/Workflow/Action/CheckIn/FilterLocationsByLocationSelectionStrategy.cs#L170) and [174](https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.13.4/Rock/Workflow/Action/CheckIn/FilterLocationsByLocationSelectionStrategy.cs#L174) both are removing or setting a flag on `selectedSchedule` however this object comes from `person.PossibleSchedules` on [line 89](https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.13.4/Rock/Workflow/Action/CheckIn/FilterLocationsByLocationSelectionStrategy.cs#L89) and is not part of the Person > GroupTypes > Groups > Locations > Schedules list which is what is used for filtering and finding the available groups and locations for the person and remains unaltered after going through this code. 

The second issue is the fact that the [Set Available Schedules](https://github.com/SparkDevNetwork/Rock/blob/438569553845a9add004bb1570963da3bd986f42/Rock/Workflow/Action/CheckIn/SetAvailableSchedules.cs) workflow action, which sets the `AvailableForSchedule` property based on the `ExcludedByFilter` property,  does not run after the Filter Locations By Location Selection Strategy so when the code hits the [GetAvailableLocations](https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.13.4/RockWeb/Blocks/CheckIn/LocationSelect.ascx.cs#L121) function in the LocationSelect Check-in Block, those schedule ids are still listed in the `AvailableForSchedule` property so it pulls all locations instead of auto-selecting the first. This issue can be fixed by adding an additional workflow action for Set Available Schedules after the Filter Locations By Location Selection Strategy Step. 

The third issue, can't really be seen because of the previous issues but basically [line 166](https://github.com/SparkDevNetwork/Rock/blob/438569553845a9add004bb1570963da3bd986f42/Rock/Workflow/Action/CheckIn/FilterLocationsByLocationSelectionStrategy.cs#L166) is looping through every location and attempting to remove the schedule. If successful, it would also remove it for the first location that we intend to auto-select and present the user with an error that there are no locations available to check the person into. 

### Steps to Reproduce

1. Configure the Location Selection Strategy attribute on the group type for your check in group
2. Set strategy to "Fill in Order" on check in area
3. Set up multiple locations on your check-in group
4. Configure the schedules so that no location will match every possible schedule
5. Check in to multiple schedules
6. See prompt to pick location instead of first location being auto-selected

**Expected behavior:**

First location in the list of locations for the group that is scheduled for each schedule and not full should be selected automatically. 

**Actual behavior:**

User is asked to select which location to check in to. 

### Proposed Solution 

I think by modifying the code within the `if(foundFirstMatch)` block to get the current location and schedule that are within the Person > Group Types > Groups > Locations (and Schedules within those locations) and using those values for the removal or flag and also adding another Set Available Schedules action the code will work as intended. If having the Set Available Schedules action run again is not desirable for some reason you would need to remove the schedule Id from the `AvailableForSchedule` property on the check-in location. 

```
if ( foundFirstMatch )
{
    var checkinLocation = checkinGroup.Locations.FirstOrDefault( l => l.Location.Id == location.Location.Id );
    var locationschedule = checkinLocation.Schedules.FirstOrDefault( s => s.Schedule.Id == selectedSchedule.Schedule.Id );
    if ( remove )
    {
        checkinLocation.Schedules.Remove( locationschedule );
    }
    else
    {
        locationschedule.ExcludedByFilter = true;
    }
}
```

### Versions

* **Rock Version:** 13.4
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1203068529628964">Problem Demo.mp4</a>

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in commit 1b4e7b93
