### ISSUE TITLE
Rock RMS describes itself as "open source" but the license is not open source.

### ISSUE THREAD

**Issue by kfogel** [SparkDevNetwork/Rock#5068]
The Rock RMS project describes itself as "open source" (e.g., in `README.md`, and in the "About" section of the project's GitHub home page), but the [Rock Community License](https://www.rockrms.com/license) is not an open source license.

Possible solutions:

1. Change to an open source license -- certainly my preferred solution :-), and I'm happy to chat about open source licenses if you'd like to explore that option -- or
2. Just don't describe the software as "open source".

**Comment by jonedmiston** [comment]
Updated the readme to be more clear about the limitations of our license.

**Comment by kfogel** [comment]
@jonedmiston Well, words only mean things when people agree they do, of course.  If you decide to use "open source" to mean something different from what the rest of the software industry uses that term to mean, no one here can stop you.  But it's guaranteed going to mislead people -- as it misled me -- over and over, just as if you sold bottles of apple juice but labeled them "milk".

For reference, [here](https://github.com/n8n-io/n8n/issues/40#issuecomment-539714634), [here](https://github.com/n8n-io/n8n/issues/40#issuecomment-540283087), and [here](https://news.ycombinator.com/item?id=21195516) describe how this came up in another project (later in that thread you can see that the author of that project fixed the problem).

**Comment by ssddanbrown** [comment]
I would just like to re-iterate @kfogel's consideration since "Open Source" [has an established definition](https://opensource.org/osd) which the "Rock Community License" does not meet. Projects like this would often instead refer to themselves as "source available" or simply just "open".
