### ISSUE TITLE
MediaPlayer Shortcode Does Not Go Fullscreen on iOS Devices

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/Rock#5071]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Essentially it does not seem possible to fully go "full screen" on an iOS device using the MediaPlayer shortcode. When the user clicks full screen it still shows the address bar and other iOS indicators rather than filling the whole screen. 
Test page at: https://www.oneandall.church/page/2025
![image](https://user-images.githubusercontent.com/605691/178320589-b0a0117d-a93c-4f18-a5b9-d060681d706c.png)
Using code:
`{[ mediaplayer media:'{{ mediaElement }}' autoresumeindays:'14' combineplaystatisticsindays:'14' width:'75%' ]}{[ endmediaplayer ]}`
### Steps to Reproduce

1. Set up a page using the mediaplayer shortcode
2. View the page
3. Click on the Full Screen button
4. See that the address bar and iOS indicators show at the top of screen. If the device is rotated to landscape mode a large amount of the video image is not shown.

**Expected behavior:**

Address bar and iOS indicators **are not** shown after clicking on the full screen button. If the device is rotated to landscape orientation the full video **is** viewable.

**Actual behavior:**

Address bar and iOS indicators **are** shown after clicking on the full screen button. If the device is rotated to landscape orientation the full video **is not** viewable.

### Versions

* **Rock Version:** Rock McKinley 13.4 (1.13.4.1)
* **Client Culture Setting:** en-US

**Comment by bscottdavis** [comment]
@cabal95 @garrettjohnson I don't know if either of you currently involved in this portion of the code, and from what I have been able to test it appears that adding the following code [referenced in the player documentation](https://github.com/sampotts/plyr#options) to set  `iosNative: true` in the [plyrOptions here](https://github.com/SparkDevNetwork/Rock/blob/fd5f2df2fc9a118157020c592fb040785298d3f3/RockWeb/Scripts/Rock/UI/mediaplayer/mediaplayer.js#L77) with [.ts file here](https://github.com/SparkDevNetwork/Rock/blob/fd5f2df2fc9a118157020c592fb040785298d3f3/RockWeb/Scripts/Rock/UI/mediaplayer/mediaplayer.ts#L359) appears to resolve the iOS fullscreen playback issue I original mentioned in this issue.

```
fullscreen: {
                        enabled: true, 
                        fallback: true, 
                        iosNative: true, 
                        container: null
                    },
```

**Comment by cabal95** [comment]
Thanks @bscottdavis, we turned that option on and tested in various ways and it does indeed seem to do the trick.
