### ISSUE TITLE
Family Analytics job updates eRA start date to current date

### ISSUE THREAD

**Issue by karenn-ccbc** [SparkDevNetwork/Rock#5072]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/35667472/178792945-879202f3-ab7a-43a4-bc6a-5d798c53d941.png)
Run Family analytics job and eRA is updated to current date:
![image](https://user-images.githubusercontent.com/35667472/178793082-6e56677f-e0e4-4ead-9430-563c46785711.png)

### Description
See Rocket Chat thread https://chat.rockrms.com/channel/general?msg=v4h5TRRKqEuhkd5JP

### Steps to Reproduce

1. Check a person's eRA
2. Update Rock to Version 13.2 or after
3. Run Family Analytics job
4. Check person's eRA
5. See updated date

**Expected behavior:**

Original eRA Start Date to be retained

**Actual behavior:**

eRA start date updated to current date of Family Analytics job run

### Versions

* **Rock Version:** 13.2, 13.4 and 13.5 confirmed
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by MichaelAllen** [comment]
I'm seeing the same issue on our system. 

It appears that the ERA start date is being set to today's date every time the job runs for all current ERAs. If I change my ERA start date to some random date, then run the job, it ends up back on today's date.

The SQL for that stored procedure is a bit complicated, so I could be reading it incorrectly. But it does appear that [this change](https://github.com/SparkDevNetwork/Rock/commit/3b57aa93be2e041056b81427538c1eebf6a29d91#diff-7d19c47891c6f2dba5d76cab5956ccb371896f0146b2ff9b0508df5ce74c2ccfR257) in 13.4 could be causing what I am seeing. 
```sql
MERGE [AttributeValue] AS TARGET
USING @TempIsEraFamilyMembers AS SOURCE
ON (TARGET.EntityId = SOURCE.PersonId AND TARGET.AttributeId = @EraStartDateAttributeId)
WHEN NOT MATCHED BY TARGET
THEN INSERT (EntityId, AttributeId, Value, IsSystem, Guid, CreatedDateTime) VALUES (SOURCE.PersonId, @EraStartDateAttributeId, @StartDate, 0, NEWID(), @StartDate)
WHEN MATCHED THEN UPDATE SET Value = @StartDate; -- << THIS LINE
```

**Comment by nairdo** [comment]
@karenn-ccbc (and @MichaelAllen) We're working on the fix and a SQL script that will run during the update.  It will repair the bad values by setting them back to the last correct value (which happens to be the `ModifiedDateTime` of each person's `core_EraStartDate` attribute value).

**Comment by nairdo** [comment]
We are going to release this very small patch as v13.6 (likely Monday or Tuesday) and push everything originally slated for v13.6 over to 13.7.

**Comment by azturner** [comment]
When updating the eRA SQL Scripts for this, did you happen to consider any of the other eRA issues also: https://github.com/SparkDevNetwork/Rock/issues/4146, https://github.com/SparkDevNetwork/Rock/issues/3828? We are frequently asked about that first one especially.

**Comment by nairdo** [comment]
@azturner Not for this particular fix.  We are solely focused on the fact that some data 'damage' is occurring.  Other eRA fixes will come at a later date.
