### ISSUE TITLE
No longer possible to crop existing person photo

### ISSUE THREAD

**Issue by SteveSwaringen** [SparkDevNetwork/Rock#5074]
### Description
It is no longer possible to crop and existing person profile photo (13.4/13.5).

We find this feature useful and necessary when users upload their own personal photos. We incorporate these images into our check-in and check-out labels as part of our security process to show who is authorized to pick a child up. Sometimes people will upload a group photo or a full-body-shot where we need an image cropped to a clean headshot of a single individual.

Without this feature, we have to do a screen capture of the existing photo and save it locally so we can re-upload it to crop it.

### Steps to Reproduce
1. Log in to rocksolidchurchdemo.com
1. Go to My Profile (Alisha Admin)
1. Click the pencil to Edit Person
1. Click the pencil to edit the photo

**Expected behavior:**

Since there is already an existing photo, this should bring up the image cropping tool for that existing image.

**Actual behavior:**

A file selection dialog is opened asking you to select a new file to upload. That would be the expected behavior if there is no existing image. (If we wanted to replace the existing image we would first delete it and then click the pencil. With no existing image, the file upload dialog would naturally pop up.)

### Versions
* **Rock Version:** [13.4 and 13.5]
* **Client Culture Setting:** [en-us]

**Comment by SteveSwaringen** [comment]
This appears to be the offending commit: https://github.com/SparkDevNetwork/Rock/commit/fa13012e443962ed0f3b85c42f593b3d89c6b018

**Comment by nairdo** [comment]
This might be something that we changed on purpose in version v13.4.  We'll review this with the team and get back to you.

**Comment by SteveSwaringen** [comment]
I suspected as much based on the comments on the commit. You can’t make everyone happy and it’s easy enough for us to maintain a different version of this file. Git will straighten things out when we merge new releases into our code base.

I recognize that this saves one click for many other users. It adds a very complex and inefficient exercise for us in what is our primary use case for the feature, so leaving it as is isn’t really an option for us. But we have a work-around.

**Comment by nairdo** [comment]
@SteveSwaringen No need for you to create a custom block.  We're going to make a block setting that you can control differently for the internal site vs the external site.  We're going to see about getting that into v13.7.

**Comment by nairdo** [comment]
![image](https://user-images.githubusercontent.com/383807/181594698-0823de66-89d9-4afb-a714-928e05fab807.png)
