### ISSUE TITLE
Event Registration

### ISSUE THREAD

**Issue by SandraRob** [SparkDevNetwork/Rock#5078]
When an event registration date has ended, the event is at capacity, and the template and instance have been made inactive, registrations are still coming through. For example, one of our events had a registration end date of 7/1 at 11:59 PM, the event was at capacity, and we made the template and instance inactive, and a registrant came still came through on 7/8 at 10:06 AM without Registration Attributes, but with the payment.

We've been told that it has something to do with Payflow Pro and the registrants not finishing the registration initially and being able to complete it days after. We thought the Registration Session/Timeout Length or Timeout Threshold would resolve the issue, but we were told it doesn’t apply to Payflow Pro. We are on version 13.4.

**Comment by jsw-austin** [comment]
Is it possible that this happens when someone starts the registration before capacity has been reached, doesn't finish the registration, but keeps their browser tab open and comes back to it later and finishes (after others have registered and the event is at capacity)?

**Comment by SandraRob** [comment]
Leah,

Thanks for your prompt response. Please review my answers highlighted below.

I'll take a look at the conversation you provided from the Community.



Thanks,
Sandra
(214) 672-9185

For His Kingdom,


[OCBFlogoemail (2)]

Sandra D. Robinson
Deaconess & Director of Membership Services
Oak Cliff Bible Fellowship
1808 W. Camp Wisdom Road
Dallas, Texas  75232
T: 214-672-9100, ext. 9185
Web:    www.ocbfchurch.org<http://www.ocbfchurch.org/>
Discipling the Church to Impact the World!
