### ISSUE TITLE
ContentChannelItemFieldType.GetEditValue The given key was not present in the dictionary Starting in Rock 13.4

### ISSUE THREAD

**Issue by jyksnw** [SparkDevNetwork/Rock#5083]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When attempting to edit a block that contains a ContentChannelItemField receive the error "The given key was not present in the dictionary." This issue was not observed in Rock 13.3. It appears that the changes in https://github.com/SparkDevNetwork/Rock/commit/ca0341d9e5486d8e904262f3deb2a3adca5b967f might have introduced a bug. A potential solution or fix could be to update https://github.com/SparkDevNetwork/Rock/blob/15a2cbc11f3218f0369bb80fab2ea1304d3ed87e/Rock/Field/Types/ContentChannelItemFieldType.cs#L191 with

```csharp
int? configurationChannelId = null;
if (configurationValues.TryGetValue(CONTENT_CHANNEL_KEY, out ConfigurationValue configurationValue))
{
    configurationChannelId  = configurationValue.Value.AsIntegerOrNull();
}
...
```

![image](https://user-images.githubusercontent.com/3477895/180259251-ef5808a1-4a41-4029-8cfd-97bca40686b6.png)

### Steps to Reproduce

1. Run Rock 1.13.4 or 1.13.5
2. Create a custom block with the field attribute `[ContentChannelItemField(name:"My Conentent Channel Item", key : "MyContentChannelItem")]` (see attached example plugin)
3. Add the block to a page
4. Edit the added block settings
5. Select `Content Channel`
6. Select `Content Channel Item`
7. Click `Save`
8. Observe the error "The given key was not present in the dictionary"

**Expected behavior:**

Should be able to select content channel item

**Actual behavior:**

Receive an error indicating that "The given key was not present in the dictionary"

### Versions

* **Rock Version:** Rock McKinley 13.4 (1.13.4.1)
* **Client Culture Setting:** en-US

### Example Plugin File
[com_dtschurch.zip](https://github.com/SparkDevNetwork/Rock/files/9161557/com_dtschurch.zip)

**Comment by tpcc-myles** [comment]
This is an issue in our v13.4 system.  Prior to v13.4, we had used a custom block which relied on the ContentChannelItemField, on more than 300 pages on our external website.  After upgrading to v13.4, we were no longer able to edit the settings of this custom block on any of our pages, and had to resort to a custom Rock.dll file to make the block operational again.
