### ISSUE TITLE
Calendar Feed from Rock Demo Site not working

### ISSUE THREAD

**Issue by jacksojourn** [SparkDevNetwork/Rock#5085]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Calendar feeds exported from the Rock demo site either show no events (Gmail) or show an error (Apple Calendars):

<img width="372" alt="Screen Shot 2022-07-24 at 6 45 30 PM" src="https://user-images.githubusercontent.com/44851374/180668874-7381a704-d03b-481d-8a5d-d78cdefa2a94.png">

### Steps to Reproduce

1. On the Rock demo site, [on this page,](https://rock.rocksolidchurchdemo.com/web/calendars/2) choose the "Export Calendar Feed" button.
2. Load this calendar feed into a third-party calendar service.

**Expected behavior:** 

Rock events show up.

**Actual behavior:** 

Gmail: no calendar events show up.
Apple Calendar (macOS): error message

### Versions

* **Rock Version:** 1.13.5.1
* **Client Culture Setting:** en-US

**Comment by leahjennings** [comment]
@jacksojourn hey there! In following your reproduction steps, I noticed that the Calendar Id in your screenshot is 2, which on the demo site is the Internal calendar.

The Internal calendar's permissions are restricted to those with Staff, Staff Like, and Administration access:
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/66277785/180794761-ab7e48fd-6fd7-437c-baef-56cd4011a871.png">

Whereas the permissions on the Public calendar are open for all:
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/66277785/180794846-13f03e3f-3fb7-46e2-a5e1-2769ab188950.png">

I was able to change the permissions on the Internal calendar (Id 2) to match the permissions on the Public calendar (Id 1), and the error went away, allowing me to subscribe as intended.

Can you confirm that is the issue you ran into?

**Comment by jacksojourn** [comment]
@leahjennings That's embarrassing! You're right. Thank you!

**Comment by leahjennings** [comment]
@jacksojourn no need for embarrassment, I've done the same thing before and submitted a bug that turned out not to be one. It happens! Maybe someone may have this question later on! Appreciate you taking the time to submit it!
