### ISSUE TITLE
Add Family - block config for "Show Cell Number First" not working as intended.

### ISSUE THREAD

**Issue by jeremyhoff** [SparkDevNetwork/Rock#5092]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

![image](https://user-images.githubusercontent.com/3937813/181939782-2c99616e-af95-4f79-8bc4-84e35984885d.png)

### Description

Under Add Family, if block is configured to "Show Cell Phone Number First = Yes" the field/columns are not reordered correctly. See attached photo for outcome. Confirmed on rock.rocksolidchurchdemo.com

### Steps to Reproduce

1. Go to https://rock.rocksolidchurchdemo.com/NewFamily
2. Click on Block Config
3. Set "Show Cell Phone Number First" = Yes
4. Add Family and notice home/mobile number columns not reordered correctly.

**Expected behavior:**

Phone number columns would be reordered and phone number fields visible.

**Actual behavior:**

Fields not displaying per config.

### Versions

* **Rock Version:** Rock Version: Rock McKinley 13.4 (1.13.4.1)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1202772382866115">image.png</a>

**Comment by nairdo** [comment]
@jeremyhoff  I've also been told the issue only happens when you first change the block setting.  Once you refresh the page (after making a change) the issue does not occur.
