### ISSUE TITLE
{{ Kiosk }} Lava Object Error

### ISSUE THREAD

**Issue by mkinyon** [SparkDevNetwork/Rock#5093]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Using the {{ Kiosk }} lava object on the check-in welcome screen causes an error:
`Liquid syntax error: Object 'Rock.CheckIn.KioskDevice' is invalid because it is neither a built-in type nor implements ILiquidizable`

### Steps to Reproduce

1. Go to Checkin Configuration.
2. Edit an existing configuration and add {{ Kiosk.CampusId }} to the Start Template section:
![image](https://user-images.githubusercontent.com/2349102/182258944-b0b23efb-86f8-406a-be16-459dacdfb430.png)

3. Next, go to check-in, choose the same configuration and go to the welcome screen:
![image](https://user-images.githubusercontent.com/2349102/182259057-23206e16-0fae-44cb-819e-0122c5dda507.png)

### Versions

* **Rock Version:** v13.4, develop
* **Client Culture Setting:** en-US

**Comment by leahjennings** [comment]
This seems to be an issue only when using the DotLiquid framework. When using Fluid, the `Kiosk` object doesn't cause any errors. It also seems like the only way to access `CampusId` in Fluid is with this: `{{ Kiosk | Property:'CampusId' }}`, nothing is shown when using `{{ Kiosk.CampusId }}`.
