### ISSUE TITLE
Variable scope changes inside workflowactivate tag using Fluid

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5102]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Using Fluid:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/66277785/183691219-50134d2d-809d-4020-b270-28260a00eac7.png">

Using DotLiquid:
![image](https://user-images.githubusercontent.com/66277785/183688482-fb5e2433-4181-4f7f-872b-89513a824d07.png)

### Description

While using the Fluid Lava engine, a variable assigned at the "parent" level and then used inside the `{% workflowactivate %}` block seems to establish the variable inside the `{% workflowactivate %}` block as a differently scoped variable. For example, I've used the `{% workflowactivate %}` command inside of a `{% for %}` loop to count records processed. However, the following example code doesn't increment the `counter` variable because Fluid treats the scope differently.

```
{% assign list = "1,2,3,4,5,6,7,8,9,10" | Split: "," %}
{% assign counter = 1 %}

{% for i in list %}
    Loop iteration #{{ forloop.index }}
    
    {% workflowactivate workflowtype:'288' %}
        {% assign counter = counter | Plus:1 %}   
        <br>- Counter inside workflowactivate: {{ counter }}
    {% endworkflowactivate %}
    <br>- Counter outside workflowactivate: {{ counter }} <br><br>
{% endfor %}

```

I don't know if this is just the nature of Fluid or an actual bug, however I've seen it twice now cause issues (once in plugin code and once in my own). If it is just the nature of the engine, it would be great for that to be documented more clearly [here](https://community.rockrms.com/lava/fluid/differences).

### Steps to Reproduce

1. Go to the demo site and add an HTML Content Block to a page
2. Make sure the site is running on the DotLiquid lava engine
3. Add the above code from the _Description_ section and save (be sure to set the block to allow _workflowactivate_ commands)
4. Notice how the output increments the counter variable _outside_ of the _workflowactivate_ command (as I would expect)
5. Now, change the lava engine to Fluid from the Global Attributes setting
6. Go back to the page where you added the code
7. Notice how the counter variable _outside_ of the _workflowactivate_ command never increments

**Expected behavior:**

If a variable is established outside of the _workflowactivate_ command and is subsequently incremented _inside_ that command, I would expect that the variable when used outside of that command shows the incremented value.

**Actual behavior:**

The variable's value inside of the _workflowactivate_ command is scoped only to that command and is not usable outside of that command.

### Versions

* **Rock Version:** [Rock McKinley 13.6 (1.13.6.1)]
* **Client Culture Setting:** [en-US]

**Comment by jonedmiston** [comment]
As a follow-up we're waiting to hear back from this question on the Fluid project:
https://github.com/sebastienros/fluid/issues/553
