### ISSUE TITLE
Add Family Block - Red required dots missing on mobile

### ISSUE THREAD

**Issue by tshivley** [SparkDevNetwork/Rock#5103]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Internal Website: ![internal-web](https://user-images.githubusercontent.com/73906643/183749732-eb9aea11-2549-496a-bf9b-356cea00d806.jpg)
Internal Mobile: 
![internal-mobile](https://user-images.githubusercontent.com/73906643/183749797-888ba2f9-562f-4b06-a4ac-ef559bd69f7d.png)
External Website: 
![external-web](https://user-images.githubusercontent.com/73906643/183749825-4d252e4e-bbf1-476e-adc7-1f56d0ba2e8e.png)
External Mobile: 
![external-mobile](https://user-images.githubusercontent.com/73906643/183749847-1687a0ba-e93c-40a1-b2df-8bd8a0a1877e.png)

### Description

The "Add Family" block shows red dots (required) using a web browser, but using a mobile browser the red dots are not showing. We are having families input their own data and noticed on mobile they are unable to see what is required. Thanks! 

### Steps to Reproduce

1. Go to '/NewFamily'
2. In a web browser you'll see the red (required) dots. On a mobile device, you will not see this.

**Expected behavior:**

I would expect to see red dots in both instances. 

**Actual behavior:**

Red dots while using a computer in a web browser, both internally and externally. See images. 

### Versions

* **Rock Version:** 13.6
* **Client Culture Setting:** en-US

**Comment by tshivley** [comment]
Hi there - I've never put one of these requests in. Will someone get back to me to let me know the status?

**Comment by nairdo** [comment]
Hi @tshivley We use an internal tool (which is synchronized with Github) to track these Github issues, so typically you won't see much activity about the status here.  We do sometimes wait until someone else confirms/classifies the issue (see https://community.rockrms.com/get-involved/role/classify-issues) before we fix it.  However, in this case, we did reproduce it internally and we're targeting v14.x for a fix.

**Comment by tshivley** [comment]
Thanks, @nairdo! This is my first time submitting for a bug so thank you for filling me in. I know you guys are super busy prepping for RX. Thanks again for following up. If there is a better place for me to keep track of this, just let me know. Thanks!
