### ISSUE TITLE
Firefox autofill values are null on the Transaction Entry block

### ISSUE THREAD

**Issue by andypullen** [SparkDevNetwork/Rock#5104]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![Screen Shot 2022-08-10 at 09 10 32@2x](https://user-images.githubusercontent.com/9940032/183960129-2db83f22-ca88-4e6a-9df0-6c3d3d6624da.jpg)

### Description

Firefox's built in autofill values aren't validated on the Transaction Entry block, and seem to be passed along as null.

```
Uncaught Sys.ArgumentNullException: Sys.ArgumentNullException: Value cannot be null.
Parameter name: panelsCreated[1]
    Sys$WebForms$PageLoadedEventArgs https://rocksolidchurchdemo.com/ScriptResource.axd?d=JnUc-DEDOM5KzzVKtsL1tbebi6PpCeYPpxyiQt56XZl8ANlkUDi0UELefh_E8KSybVmrQody5sNStM03VWkP6NrWbQEwHOeHwIn2S_ExDlfq-pSxW7JJs4gnrvIXqXcnMzuWPrWuqFbjckRvcidB_1joksP5xPKmt0yNpjSsCk45Jp6a0&t=49337fe8:154
    Sys$WebForms$PageRequestManager$_getPageLoadedEventArgs https://rocksolidchurchdemo.com/ScriptResource.axd?d=JnUc-DEDOM5KzzVKtsL1tbebi6PpCeYPpxyiQt56XZl8ANlkUDi0UELefh_E8KSybVmrQody5sNStM03VWkP6NrWbQEwHOeHwIn2S_ExDlfq-pSxW7JJs4gnrvIXqXcnMzuWPrWuqFbjckRvcidB_1joksP5xPKmt0yNpjSsCk45Jp6a0&t=49337fe8:977
    Sys$WebForms$PageRequestManager$_pageLoaded https://rocksolidchurchdemo.com/ScriptResource.axd?d=JnUc-DEDOM5KzzVKtsL1tbebi6PpCeYPpxyiQt56XZl8ANlkUDi0UELefh_E8KSybVmrQody5sNStM03VWkP6NrWbQEwHOeHwIn2S_ExDlfq-pSxW7JJs4gnrvIXqXcnMzuWPrWuqFbjckRvcidB_1joksP5xPKmt0yNpjSsCk45Jp6a0&t=49337fe8:1380
    Sys$WebForms$PageRequestManager$_pageLoadedInitialLoad https://rocksolidchurchdemo.com/ScriptResource.axd?d=JnUc-DEDOM5KzzVKtsL1tbebi6PpCeYPpxyiQt56XZl8ANlkUDi0UELefh_E8KSybVmrQody5sNStM03VWkP6NrWbQEwHOeHwIn2S_ExDlfq-pSxW7JJs4gnrvIXqXcnMzuWPrWuqFbjckRvcidB_1joksP5xPKmt0yNpjSsCk45Jp6a0&t=49337fe8:1387
    createDelegate https://rocksolidchurchdemo.com/ScriptResource.axd?d=D9drwtSJ4hBA6O8UhT6CQnXOmMcfXKoknVtHieU3w1Y7Fvfs2O4Kr7dc6DcQ5yp9OTdO_K3668Dyy40FEjfPwMpEMyxuX0zx_N1OIbL56ABvnxb7tQEj6W6GhUlcsXSD43YMivZB4WdsFgEFny3rQSfW4SI1&t=49337fe8:47
    browserHandler https://rocksolidchurchdemo.com/ScriptResource.axd?d=D9drwtSJ4hBA6O8UhT6CQnXOmMcfXKoknVtHieU3w1Y7Fvfs2O4Kr7dc6DcQ5yp9OTdO_K3668Dyy40FEjfPwMpEMyxuX0zx_N1OIbL56ABvnxb7tQEj6W6GhUlcsXSD43YMivZB4WdsFgEFny3rQSfW4SI1&t=49337fe8:4052
ScriptResource.axd:22:15
```

### Steps to Reproduce

1. Open Firefox (Mac or Windows)
2. Add an autofill address if needed (Settings > Forms and Autofill > Autofill addresses)
3. Go to the Give page ([the demo site](https://rocksolidchurchdemo.com/page/186) works fine)
4. Log out if not already
5. Use Firefox's autofill to fill out the Personal Information form, put in a fake credit card number and dollar amount
6. Submit the form

**Expected behavior:**

The autofill values should be valid

**Actual behavior:**

Autofilled values aren't valid or are passed along as empty

### Versions

* **Rock Version:** 13.4 - 13.6 (probably 13.x)
* **Client Culture Setting:** en-US

**Comment by abpena1979** [comment]
Hi @andypullen! 
This issue couldn't be reproduce. It sounds like it may be an issue with Firefox, so we'll close this issue unless anyone else is able to reproduce.

**Comment by jsw-austin** [comment]
I was able to reproduce this on The Villages website.

**Comment by KCKurz** [comment]
A member of our church encountered this same issue. I was also able to reproduce this on the LifeMission site myself using Firefox. The issue can only be reproduced if you are using the "autofill" for your name/address.

**_Steps to Reproduce_**

1. Open Firefox Browser (Mac or Windows)
2. Navigate to a Page with Transaction Entry Block While Unauthenticated
3. Add an autofill address if needed (Settings > Forms and Autofill > Autofill addresses)
4. Use Firefox's autofill to fill out the Personal Information form, click NEXT

**_Expected Results_**
The autofill values would be valid, and the current person would navigate to the payment page.

**_Actual Results_**
Auto filled values are not valid or are passed along as empty to the form. The Current Person receives an error message: "Invalid Form Value"

**Comment by KCKurz** [comment]
> Hi @andypullen! This issue couldn't be reproduce. It sounds like it may be an issue with Firefox, so we'll close this issue unless anyone else is able to reproduce.

Now that three others have been able to reproduce this, can it be reopened for further review and resolution?

**Comment by jsw-austin** [comment]
I also ran into this on the login screen.  FBC Hendersonville is using v.14.  @nairdo can this be re-opened or should we submit it as a new issue?

![Screen Shot 2022-12-02 at 9 17 38 AM](https://user-images.githubusercontent.com/7400184/205325521-572196e0-a95c-4a00-955a-eb5bed51e374.png)
