### ISSUE TITLE
Expiring Credit Card notification is sent to people who have already updated their scheduled transaction with new card.

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#5106]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When editing an existing scheduled transaction, the scheduled transaction's payment details are not updated with the new card's information. This is causing people to get notifications about their card that is about to expire even though they have already updated their scheduled transaction with a new card that is not expiring. 

This is related to this issue: https://github.com/SparkDevNetwork/Rock/issues/4155. The fix for that issue was to add code that cleared the existing payment information. That "ClearPaymentInfo" method no longer clears values though because of how the model is using the obsolete encrypted fields. For example, when it clears the ExpirationMonth field, it does not clear the the _encryptedExpirationMonth value, so ExpirationMonth property will continue to return the value in the _encryptedExpirationMonth field.

### Steps to Reproduce

1. Go to public Transaction Entry page (you can use the Test Gateway).
2. Create a new recurring transaction with a credit card.
3. Go to the public Manage Giving Profiles page and update that recurring transaction with a new card that has a different expiration date.

**Expected behavior:**

The payment details on the scheduled transaction are updated to reflect the new expiration date.

**Actual behavior:**

The payment details still show the expiration date of the original credit card.

### Versions

* **Rock Version:** v12.8, v13.4, v14.0
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
As a non-dev, I’m curious why the two different commits above use slightly different code to fix this issue?
