### ISSUE TITLE
RegistrationRegistrantFee Column Property Name, Option, Causing an Error in SELECT Query

### ISSUE THREAD

**Issue by SkellyRen** [SparkDevNetwork/Rock#5107]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

![image](https://user-images.githubusercontent.com/48486355/184440777-900ba249-0561-4231-86eb-9644b4eec868.png)
![image](https://user-images.githubusercontent.com/48486355/184440843-242c328d-3af1-451c-bbe5-1acbdb415fa6.png)

### Description

When trying to Select the 'Option' column property from the RegistrationRegistrantFee table in a SELECT query SQL will throw an incorrect syntax error.  

This is likely happening because the column name of 'Option' is the same as the SQL 'OPTION' parameter.

### Steps to Reproduce

1. Go to Rocks SQL Command Page or Azure Data Studio/SSMS and run this Select query:
`SELECT
    Option
FROM
    RegistrationRegistrantFee`

**Expected behavior:**

SQL to return the 'Option' Column data

**Actual behavior:**

SQL Throws an Error: 
Error SQL Error! Incorrect syntax near the keyword 'Option'.

### Versions

* **Rock Version:** N/A
* **Client Culture Setting:** N/A

**Comment by jsw-austin** [comment]
@SkellyRen this will work if you write it as
``` SELECT [Option] FROM RegistrationRegistrantFee

**Comment by nairdo** [comment]
Yeah, unfortunately "option" is a keyword in SQL ([see this](https://docs.microsoft.com/en-us/sql/t-sql/queries/option-clause-transact-sql?view=sql-server-ver16)) so you have to 'quote' it as Jeff described.
