### ISSUE TITLE
Transaction List Occasionally Shows Back of Checks instead of Front

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5108]
### Prerequisites

* [X*] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
Yes
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
No, The demo site does not have back images for checks, so it is not possible to reproduce this issue there. 
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
Yes

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

![image](https://user-images.githubusercontent.com/54962439/184452797-4cf7ec4d-8f88-429f-abdc-c24c8e6786a9.png)

### Description

Transaction detail is occasionally showing the back check image instead of the front when you click on Transaction Details and Show Images. 

### Steps to Reproduce

1. Scan checks via Rock Check Scanner Application.
2. Go to the transactions page /finance/transactions. Set filter criteria to return checks from several batches. Here were the criteria I used in my test:
![image](https://user-images.githubusercontent.com/54962439/184453510-af31f938-8866-4cd0-af87-70e339015534.png)

4. Scroll down to and view check images.
5. See error, some checks are showing the back image instead of the front.
![image](https://user-images.githubusercontent.com/54962439/184452797-4cf7ec4d-8f88-429f-abdc-c24c8e6786a9.png)

**Expected behavior:**

Always show the front of the check when review transactions.

**Actual behavior:**

Some checks are showing the back image.

### Versions

* **Rock Version:** 13.5 (1.13.5.1)
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
@dataCollegechurch  can you add screenshots of the transaction detail pages for each of the above transactions. Example shown below.

![image](https://user-images.githubusercontent.com/548178/184455030-2e05e46d-58ca-4688-b25d-62768614d933.png)

**Comment by dataCollegechurch** [comment]
No problem
![image](https://user-images.githubusercontent.com/54962439/184519411-c38e03a6-9a72-4f47-b8b3-717060587747.png)
![image](https://user-images.githubusercontent.com/54962439/184519444-a68ea6d1-eb81-4a82-a437-779bb1213e27.png)

**Comment by abpena1979** [comment]
@dataCollegechurch would you be able to provide a couple more screenshots of the block settings on that Transaction Detail Grid?   (A screenshot with each of these tab's settings should help with reproducing the issue.) 
Thank you! 

![image](https://user-images.githubusercontent.com/108844907/185256208-4adee6a8-dcf9-430b-abbf-4ff174980a45.png)

**Comment by dataCollegechurch** [comment]
Here are the settings in place
![image](https://user-images.githubusercontent.com/54962439/185691250-77815d24-cdee-45b0-ab39-3343f9518e48.png)
![image](https://user-images.githubusercontent.com/54962439/185691302-4782fd31-64c7-4760-82f6-447fdb48351e.png)
![image](https://user-images.githubusercontent.com/54962439/185691342-6fcdde41-2275-4b74-bfa2-da71b6873cdf.png)

**Comment by dataCollegechurch** [comment]
@sparkdevnetwork-service - is there any more information I can send you to help you reproduce the issue?

**Comment by nairdo** [comment]
Thanks Tony @dataCollegechurch -- we were hoping a few others from the Rock community would report on whether they have been able to reproduce this issue, but regardless, it is still in our active issues list.
