### ISSUE TITLE
Remove the Pluralize() function on the Registration Entry fee term field

### ISSUE THREAD

**Issue by andypullen** [SparkDevNetwork/Rock#5110]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![Screen Shot 2022-08-15 at 10 37 28@2x](https://user-images.githubusercontent.com/9940032/184686715-7f824f66-cf88-4d6b-89ad-4af9687726a8.jpg)

### Description

The Fee Term probably shouldn't be automatically pluralized, which limits what is able to be placed in the field. There are times when pluralization doesn't make sense for the section, and it would likely naturally be pluralized when it does.

https://github.com/SparkDevNetwork/Rock/blob/191dd25ee2d26e9f8703dc4b5d680215a3a86145/Rock.Blocks/Event/RegistrationEntry.cs#L2315

### Steps to Reproduce

1. Create an event registration template
2. Change the Fee Term to something that shouldn't be pluralized
3. The Fee Term gets automatically pluralized
4. Shake fist in frustration

### Versions

* **Rock Version:** 13.6
* **Client Culture Setting:** en-US

**Comment by abpena1979** [comment]
Hi @andypullen! 
The Fee Term field in the event template allows for customization of the individual term for the event "fees".  For example: cost, price, rate, or in your case scholarship.  This field was intended as an override for that term, but not intended for full sentence content for customization of that section.  

If you would like to request a feature change, you can post your Idea over on the http://community.rockrms.com/Ideas board.
