### ISSUE TITLE
Child Group Types Not showing When Adding Group

### ISSUE THREAD

**Issue by RufenachtPW** [SparkDevNetwork/Rock#5115]
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.
![Screen Shot 2022-08-18 at 4 25 48 PM](https://user-images.githubusercontent.com/87141140/185488598-d4fb6faf-847c-434f-b27c-8cf06312f670.png)
![Screen Shot 2022-08-18 at 4 25 58 PM](https://user-images.githubusercontent.com/87141140/185488605-ea821315-2172-4825-a2b4-45d2eaaff276.png)

### Description
Not all allowed child group types are displayed when trying to add a new group as a child of another group.

### Steps to Reproduce
1. Go to group types
1. Add a child group type to the allowed child group types.
1. Go to group viewer and try to add a new group as a child to your group type. The allowed group type is not there.

**Expected behavior:**

All Allowed child group types should show when adding a new group as a child to another group.

**Actual behavior:**

Only the same group type is displayed.

### Versions
* **Rock Version:** [13.4,13.6]

**Comment by nairdo** [comment]
@RufenachtPW Can you double check your Group Detail's block setting?  

![image](https://user-images.githubusercontent.com/383807/193297927-c8fdd405-c332-426f-8c87-2d002ecc0a32.png)

It appears that your "**Limit to Group Types that are shown in navigation**" setting it likely set to "Yes" -- and that setting will limit the Group Types to only show the ones that have the "Show in Navigation" checked:

![image](https://user-images.githubusercontent.com/383807/193298567-87a41707-1660-4985-a424-f7394cc9acdf.png)

This was a purposeful change (https://github.com/SparkDevNetwork/Rock/commit/ec6fea124c00a4cda1116b36b0370c3563383604) made way back in the v1.0 days.

**Comment by RufenachtPW** [comment]
Thanks Nick. You can close this. The problem was actually that on the group details block they had selected a couple of group types in the include list that was taking everything else out of the list. Thank you!
