### ISSUE TITLE
No view when metric is created with two defined values

### ISSUE THREAD

**Issue by edmund-lam** [SparkDevNetwork/Rock#5117]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

After a metric is created with two defined types, SQL fails to generate a view.

### Steps to Reproduce

1. Define the first defined type: Fund Type
<img width="1191" alt="Screen Shot 2022-08-18 at 10 34 13 PM" src="https://user-images.githubusercontent.com/111556955/185550219-c85b7fc2-d5c7-48ab-8fd6-6732abd4e683.png">

2. Define the second defined type: Offer Type
<img width="1169" alt="Screen Shot 2022-08-18 at 10 34 27 PM" src="https://user-images.githubusercontent.com/111556955/185550266-13bc9a6a-2d39-402b-b1b9-c410ae903a1b.png">

3. Create a metric named "Sunday Onsite Offerings" with these two defined types added as partitions. Enable Analytics is checked.
<img width="868" alt="Screen Shot 2022-08-18 at 10 33 49 PM" src="https://user-images.githubusercontent.com/111556955/185550124-df2e0d63-b9bc-4163-b6d6-306bed275d55.png">

4. A few sample entries have been added.
<img width="841" alt="Screen Shot 2022-08-18 at 10 33 33 PM" src="https://user-images.githubusercontent.com/111556955/185550143-9d2486be-5679-4a7d-9489-c893433e0ddb.png">

**Expected behavior:**

SQL should create a view.

**Actual behavior:**

SQL doesn't find the view created by the metric.
<img width="1129" alt="Screen Shot 2022-08-18 at 10 33 25 PM" src="https://user-images.githubusercontent.com/111556955/185550153-fc3dd0fd-038d-42ef-94bb-2a092f850a03.png">

When only one of these defined types is added to the metric, SQL can return a view. See below:

<img width="1198" alt="Screen Shot 2022-08-18 at 10 45 58 PM" src="https://user-images.githubusercontent.com/111556955/185551560-574f41a5-9256-4ca1-af8f-e546478c90fb.png">

<img width="1175" alt="Screen Shot 2022-08-18 at 10 46 14 PM" src="https://user-images.githubusercontent.com/111556955/185551563-0fad0c5e-6cbc-40fa-82e3-28c2ce0b8d93.png">

### Versions

* **Rock Version:** [13.4]
* **Client Culture Setting:** [en-US]

**Comment by edmund-lam** [comment]
@PraveenMathew92 When will v15.1 be scheduled for release? Thanks.

**Comment by nairdo** [comment]
@edmund-lam  Sorry about that.  This should actually be slated for v14.1 and someone from our team is checking to verify that the fix is in the correct branch.
