### ISSUE TITLE
[Alpha 1.14.0.17] - Connection Request Bulk Update Allows Transferring to Inactive Opportunities

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5118]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [X] Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

![image](https://user-images.githubusercontent.com/66277785/185681226-7c2339d0-4657-47e2-8959-dfaee9736932.png)

### Description

When using the new bulk update feature for connection requests, the options presented allow you to choose a new opportunity. In that opportunity drop down list is _all_ of the opportunities within the type, _including_ inactive opportunities.

### Steps to Reproduce

1. Go to Connections and click the gear icon to view a list of types
2. Click on one of the types
3. Make sure one of the opportunities listed is inactive
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/66277785/185681291-3d28a8e7-5aaf-43b3-8b6e-afe364cce6d3.png">

4. Go back to the Connections page
5. Click on one of the opportunities that has multiple requests within the type that was edited in step 2
6. Check the boxes on the row for at least two requests
7. Click the bulk update icon
8. On the _Connection Requests Bulk Update_ page, notice in the Opportunity dropdown there are also inactive opportunities listed

**Expected behavior:**

I would expect you could only bulk transfer requests to _active_ connection opportunities.

**Actual behavior:**

You are able to bulk transfer requests to _any_ opportunity within that type, both active and inactive.

### Versions

* **Rock Version:** [Rock McKinley 14.0 (1.14.0.17)]
* **Client Culture Setting:** [en-US]

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in commit https://github.com/sparkdevnetwork/rock/commit/3fc1a96446f6310379a117e10e71e689eb1b3bbf
