### ISSUE TITLE
[Alpha 1.14.0.17] Previewing Signature Document Template Throws Exception

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5119]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [X] Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/66277785/185685943-daf7fc4f-a35e-4e41-bda6-490ae1d854d3.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/66277785/185686783-b0d128a7-6896-491a-88a0-9768a3736d73.png">

### Description

When trying to preview either of the built-in signature document templates, an exception `Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)` is thrown.

### Steps to Reproduce

1. Go to Admin Tools > General Settings, then click on Signature Documents
2. Click on either of the signature document types
3. Click Edit
4. Click Preview on the Lava Template
5. Notice the exception

**Expected behavior:**

I would expect a preview of the Lava template to display with no exception.

**Actual behavior:**

An exception is thrown and the preview is not displayed.

### Versions

* **Rock Version:** [Rock McKinley 14.0 (1.14.0.17)]
* **Client Culture Setting:** [en-US]

**Comment by ethan-sparkdevnetwork** [comment]
There was a missing web.confg transform in the 14.0 alpha package.
