### ISSUE TITLE
[Alpha 1.14.0.17] Obsidian Registration Entry Has Funky Dropdown Styling

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5120]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [X] Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

<img width="1667" alt="image" src="https://user-images.githubusercontent.com/66277785/185689489-7099935d-a789-4129-9062-127fe38952a1.png">

### Description

Most field types that include a dropdown UI element look doubled-up and weird on the Registration Entry (Obsidian) block. I confirmed this is _not_ an issue on this block in v13.6.

Tested and confirmed behavior on the `Single-Select`, `Gender`, and the state dropdown of the `Address` field type. Does not appear to be an issue on the dropdown control of the `Date` field type.

Tested also in three different desktop browsers and one mobile browser, and the behavior didn't change.
- Chrome Version 104.0.5112.101 (Official Build) (x86_64)
- Safari Version 15.4 (17613.1.17.1.13)
- Firefox 102.0.1 (64-bit)
- Mobile Safari 16 on iOS 16

### Steps to Reproduce

1. Go to a page with the `Registration Entry (Obsidian)` block
2. Visit that page and pass a slug of a registration instance configured with a `Single-Select` and `Gender` field types
3. Notice the appearance of the field types

**Expected behavior:**

I would expect the dropdowns to look like a regular, normal dropdown field.

**Actual behavior:**

The dropdown boxes seem duplicated and weirdly overlapped.

### Versions

* **Rock Version:** [Rock McKinley 14.0 (1.14.0.17)]
* **Client Culture Setting:** [en-US]

**Comment by garrettjohnson** [comment]
Fixed by recompiling theme which included the latest fixes.
