### ISSUE TITLE
[Alpha v14.0] - Family Navigation Possible Issue

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5124]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
I am wondering if this was done intentionally and is by design, but figured I would report it just in case. If it is by design, we can just close this issue.

The Family Navigation block sits at the top left of the new person profile pages. I find this navigation very helpful, however, it only appears after you have begun scrolling down the page. Personally, I like that being there to easily switch between family members even when I am sitting at the top of the page.

I did notice that on mobile (smaller screen size < 768 px) it does appear when you are at the top of the page.

#### A Picture Is worth a Thousand Words
<img width="1728" alt="Screen Shot 2022-08-20 at 11 38 10" src="https://user-images.githubusercontent.com/23226974/185755347-71494027-149b-4cae-9c43-e80e098b2f55.png">

<img width="1728" alt="Screen Shot 2022-08-20 at 11 38 20" src="https://user-images.githubusercontent.com/23226974/185755352-728f0c8d-100e-47b8-8ded-d720fcc62cb1.png">

<img width="500" alt="Screen Shot 2022-08-20 at 11 38 32" src="https://user-images.githubusercontent.com/23226974/185755354-a8d1b086-6291-4006-8d08-f967abf04c8e.png">

### Steps to Reproduce

1. Go to new person profile page and see Family Navigation is not viewable until scrolling has begun, or screen size is smaller.

**Expected behavior:**

This may be more of my personal opinion, but I would find it helpful if it was always showing.

**Actual behavior:**

Does not show until you have begun scrolling or are viewing on smaller screen size.

### Versions

* **Rock Version:** [v14.0]
* **Client Culture Setting:** [en-US]

**Comment by abpena1979** [comment]
Hi @mikedotmundy!
Thank you for your feedback.  This was done intentionally, by design.  We've taken your feedback into consideration and the feature is being internally reviewed.

**Comment by JimMichael** [comment]
I tend to agree. I only mentioned the “this seems to be a problem only only lower resolution displays” comment on chat as a way to surmise that’s why it was never an issue for the devs of this new code, because they are presumably on good high-Rez displays.

**Comment by nairdo** [comment]
Sorry I missed responding to this back in April.  I did clarify this with our product owner team and it was by design.  We didn't want to repeat the person's name and photo in such close proximity to the main photo and name:
![image](https://github.com/SparkDevNetwork/Rock/assets/383807/aedbb5b4-692f-4b35-bfc4-787a94a37d83)
