### ISSUE TITLE
[Alpha v14.0] - Social Media Attributes on My Account Page Formatting Issue

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5125]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
The new look of the social media attributes on the `/MyAccount` page create some confusing formatting, as the text a user types in is cut off due to the smaller size of the field. It is even more difficult to see when the window size is just above the XS bootstrap window size.

A possible fix would be to put these inside `col-md-12`'s instead of `col-md-6`'s.

#### A Picture Is worth a Thousand Words
<img width="1728" alt="Screen Shot 2022-08-20 at 20 30 01" src="https://user-images.githubusercontent.com/23226974/185770487-93d65718-5b84-4458-94f9-02f248cc8eaf.png">

Having a smaller window makes it even more difficult to view the text:
<img width="999" alt="Screen Shot 2022-08-20 at 20 36 00" src="https://user-images.githubusercontent.com/23226974/185770617-82df499d-730a-406b-a080-095fa30f19f3.png">

### Steps to Reproduce

1. Go to `/MyAccount`.
2. Edit block settings on the Public Profile Edit block, and add Facebook, Instagram, and Twitter to the Person Attributes (adults) section. Click Save.
3. Click "Update Profile".
4. See the field size to type in your social media handle is very small.

**Expected behavior:**

Field size be larger.

**Actual behavior:**

Field size is small.

### Versions

* **Rock Version:** [v14.0]
* **Client Culture Setting:** [en-US]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1202849925189907">image.png</a>

**Comment by JimMichael** [comment]
I agree this is a less than ideal UI for these fields
