### ISSUE TITLE
[Alpha 1.14.0.17] Strange Block Edit Mode Behavior On Profile Page

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5142]
### Description

I noticed some odd behavior on the Extended Attributes tab of the new Profile page, where (when in block edit mode) you over-shoot the Attribute Values block flyout in the upper left you're intending to edit and instead inadvertently click the profile image above it (they are close and it's easy for me to do, anyway.)

This causes the profile image to pop out full screen. When you then click out of that to close it, and click the *actual* flyout you intended, it again opens the profile image as if you clicked it, but you're no where near it.

### Steps to Reproduce

I realize this is hard to describe, and even pictures are difficult to capture what's happening, so I did a quick screen cap to show the behavior I'm seeing. 

https://user-images.githubusercontent.com/3903408/186529139-38ae8437-9fc3-4111-aa67-3a23e33cf82b.mp4

https://monosnap.com/file/hfKfeQGtdVNL5YtJqXHkeMTu1MQhpt (alternate URL if above doesn't work)

Note the video has narration so un-check the muted speaker on the player.

**Expected behavior:**

The above demonstrated behavior wouldn't happen. 

**Actual behavior:**

I am able to reproduce the demonstrated behavior on Firefox (Win) and Safari (MacOS) but am NOT able to reproduce it on Chrome or new Edge.

### Versions
* **Rock Version:** 1.40.0.17

**Comment by BrentPirolli** [comment]
Yes, I have confirmed this on FF on v14.2, but it has nothing to do with being in editor mode... the profile picture's "hotspot" to click is taller than the image shown. So it happens even out of block edit mode. If you hover your cursor over the area under the profile image on that page, you get a finger cursor to click the image even though you aren't on the image.
