### ISSUE TITLE
[Alpha 1.14.0.17] - Updating Registration from My Profile page gives exception

### ISSUE THREAD

**Issue by tbunney** [SparkDevNetwork/Rock#5144]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? _No, because it is on 13.4_
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![exception-eventregistrations](https://user-images.githubusercontent.com/37702418/186703505-2edb7c30-a68c-47fc-9625-9b5e4a2c3937.PNG)

### Description
When updating a registration with or without payment, I get an exception of "Object not set to a reference" when clicking Next on the confirmation screen.

### Steps to Reproduce

1. Go to My Account
2. Click on an existing registration.
3. Change one or more fields then click Next on the last page.

**Expected behavior:**

The confirmation screen should appear.

**Actual behavior:**

I get an exception of "Object not set to a reference" when clicking Next on the confirmation screen.

### Versions

* **Rock Version:** [Alpha 1.14.0.17]
* **Client Culture Setting:** [en-US]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1202884110758118">image.png</a>

**Comment by abpena1979** [comment]
Fix will be included in update to v14.0 package
