### ISSUE TITLE
Using Safari Back Button Often Shows Loading Animation

### ISSUE THREAD

**Issue by jacksojourn** [SparkDevNetwork/Rock#5148]
### Resubmitting [this issue](https://github.com/SparkDevNetwork/Rock/issues/1987) which was marked as fixed but is not fixed. I commented on it twice on the original thread but got no response.

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Using Safari under certain circumstances pressing the back button on will cause the loading animation to appear and stay on screen.

### Steps to Reproduce

1. Search for Decker
2. Press Enter without selecting an autocomplete
3. On the search results, click a name
4. Once the profile loads, click Back
5. Search results load, but beneath the translucent gray div and with the infinite loading icon6. 

**Expected behavior:**

The page should load and be usable.

**Actual behavior:**

The page loads but is unusable and has the round orange loading animation.

### Versions

* **Rock Version:** Rock McKinley 12.6 (1.12.6.1)
* **Client Culture Setting:** en-US

**Comment by tikool17** [comment]
Can confirm this is still a big issue for us in Safari. Makes Rock unusable there. Other instances of this happening on the demo site for reference:

1. Go to [Transactions page](https://rock.rocksolidchurchdemo.com/finance/transactions)
2. Click any transaction to view the details.
3. Click the browser back button.
4. Get stuck on loading icon

1. Go to [Connections board](https://rock.rocksolidchurchdemo.com/people/connections)
2. Click on any Connection Opportunity, "Greeter" for example.
3. Click the browser back button.
4. Get stuck on loading icon.

**Comment by jacksojourn** [comment]
Hey just wondering if we can get an acknowledgement here. If it's not a priority we get it.

**Comment by leahjennings** [comment]
@jacksojourn I can confirm the same behavior on my Mac running Safari Version 15.4 (17613.1.17.1.13). However it  doesn't occur on Chrome Version 105.0.5195.125 or FireFox Version 104.0.2 (64-bit) on the same Mac. Seems to be just a Safari issue. I can also confirm it's an issue on Mobile Safari on iOS 16.0.

I'll go ahead and mark it as confirmed and as a bug, however I'd recommend updating the title to reflect the actual issue (something like _Using Safari Back Button Often Shows Loading Animation_. The original issue was likely fixed and at some point was reintroduced by OS updates, so this would be considered a new issue vs reopening the original.

**Comment by jacksojourn** [comment]
@leahjennings Thanks! Will od.

**Comment by abpena1979** [comment]
My apologies for the delayed response, @jacksojourn. The core team is looking into this issue and should provide an update soon.

**Comment by jacksojourn** [comment]
@abpena1979 Thanks! No worries—I know you guys are probably slammed. Just wanted to make sure it was seen.
