### ISSUE TITLE
Table buttons can scroll out of view

### ISSUE THREAD

**Issue by jacksojourn** [SparkDevNetwork/Rock#5149]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

![1](https://user-images.githubusercontent.com/44851374/186946919-f320203d-b05a-416c-9a67-de2a4281834c.gif)

### Description

In table row views, the button that appear at the left corners can scroll out of view when the rows are too long.

### Steps to Reproduce

1. Go to any table view such as [this one](https://rock.rocksolidchurchdemo.com/web/calendars/1)
2. Shrink the viewport so that the rows need to scroll horizontally to be visible
3. Buttons can disappear

**Expected behavior:**

Buttons should not scroll. They should be visible at all times, regardless of scroll state of rows below.

**Actual behavior:**

Buttons can scroll out of view.

### Versions

* **Rock Version:** Rock McKinley 12.6 (1.12.6.1)
* **Client Culture Setting:** en-US

**Comment by abpena1979** [comment]
Hi @jacksojourn, 
Thank you for your feedback.  This behavior is something that we have awareness of and are planning to fix in a future release with the Obsidian Grid.  For the moment, I will close this issue and tag this item for review.  Thank you again for your partnership.
