### ISSUE TITLE
Calendar Event Recurrences "by Specific Date" fail to Export

### ISSUE THREAD

**Issue by jacksojourn** [SparkDevNetwork/Rock#5150]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![](https://user-images.githubusercontent.com/44851374/186948682-827acdb3-5815-4c57-8d79-e49c7456ed90.png)

### Description
Calendar events with an occurrence pattern of "specific date" fail to export any but the first event.

### Steps to Reproduce
1. Create a new calendar event
1. Edit the schedule
1. Set it to recurring 
1. Choose "specific dates"
1. Select a few specific dates
1. Load the calendar feed URL in calendar app of choice

**Expected behavior:**

All event occurrences should be visible.

**Actual behavior:**

Only the first event occurrence is visible. The others do not export.

### Versions
* **Rock Version:** Rock McKinley 13.4 (1.13.4.1)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1203092094238579">image.png</a>

**Comment by nairdo** [comment]
Earlier this morning I tried reproducing this on the pre-alpha site but was unable -- so I thought I would paste my screenshot in here for posterity. 
![image](https://user-images.githubusercontent.com/383807/191090870-c0e36d07-899e-4f4c-b8d2-46559e789488.png)

**Comment by jacksojourn** [comment]
@nairdo Thanks, I'll test again and report back.

**Comment by PraveenMathew92** [comment]
Hi @jacksojourn I see that the issue is present only when the time and duration are not provided. 

![image](https://user-images.githubusercontent.com/14316941/193080451-a27ed0f6-e69a-402c-bae4-32f75713d261.png)

**Comment by jacksojourn** [comment]
@PraveenMathew92 @nairdo I am still able to reproduce it on the demo site

<img width="2304" alt="image" src="https://user-images.githubusercontent.com/44851374/193136402-a475ddc2-4844-4207-b3d3-3c8ecfd30a24.png">

**Comment by PraveenMathew92** [comment]
Hi @jacksojourn the demo site runs an older version of Rock. 

Please try it out on the prealpha (https://prealpha.rocksolidchurchdemo.com/web/calendars/1)

**Comment by jacksojourn** [comment]
@PraveenMathew92 Thank you. Still happening for me on the pre-alpha:

<img width="2304" alt="Screen Shot 2022-09-30 at 1 29 46 PM" src="https://user-images.githubusercontent.com/44851374/193325019-dc286191-b525-4709-b2c2-5a21f0dc8dcb.png">

**Comment by tcavaletto** [comment]
@ethan-sparkdevnetwork This is now an issue again as of 12/26/2023. I was able to replicate it using the schedule below on the demo site running 15.1. When trying to import to either Outlook Web or the Outlook desktop app, it failed to add an event with recurring dates, but successfully imported a one-time event.
![image](https://github.com/SparkDevNetwork/Rock/assets/5482014/8092ab81-8852-40be-871c-5f9cc6d8cd87)

**Comment by chead4** [comment]
@tcavaletto Hi Taylor.  I was unable to recreate your issue on RockSolidChurchDemo site (v16.1) and on my local v15.1. After importing the ical.ics to my Outlook on my desktop, the calendar event recurring schedule displayed on all days correctly. If you continue to experience the issue, please share your ical.ics download file.

![image](https://github.com/SparkDevNetwork/Rock/assets/134172019/11e82ca9-844b-40be-9fee-d5efdef50321)

**Comment by thejasonharvey** [comment]
Taylor submitted this on our behalf. I would be curious to learn if you selected the recurring option and then under the Occurance Pattern you selected "Specific Dates"? In our case, the Outlook import works fine if we select the daily/weekly/monthly occurrence patterns, but not when we use the specific dates option. I tested it on the demo site to confirm before sending this message.

**Comment by chead4** [comment]
@thejasonharvey Hi Jason  I provided more screenshots below as I just tried to recreate the issue on the demo site (v15.1).  I did select specific dates and entered a time and duration.  When I imported into my Outlook I selected Open as New and not Import.  I am still not able to recreate.  I tried with specific dates that were one after the other, a month apart, week apart and they all display on the calendar.

![chrome_FDPMtFuRMY](https://github.com/SparkDevNetwork/Rock/assets/134172019/cc34e8bf-89a0-4d70-a19a-948caddba1bd)
![OUTLOOK_jYDzNbLwh2](https://github.com/SparkDevNetwork/Rock/assets/134172019/8be6a356-412a-40b8-80af-d15f30bce0e2)
![image](https://github.com/SparkDevNetwork/Rock/assets/134172019/c8b682f3-fca2-4726-aa4b-ce9b9ac05bbf)

**Comment by thejasonharvey** [comment]
Well, that is interesting... So, I would need Taylor to speak about how they set up ours to work on our instance where we are having the issue. However, I went into the demo site to capture some screenshots of how I am adding this calendar and still experiencing the issue...

1) I grab the export calendar feed link from the calendar page
2) I am using Outlook on web and select add calendar
3) I subscribe from web
4) That is what is showing on my calendar

![1](https://github.com/SparkDevNetwork/Rock/assets/130079417/425eff37-cf7c-402e-8601-e375d4a7ac42)

![2](https://github.com/SparkDevNetwork/Rock/assets/130079417/a3a7c5e3-e5d8-47c1-89cf-b59fe89ea3c8)

![3](https://github.com/SparkDevNetwork/Rock/assets/130079417/a884af32-fc23-4567-bcd5-584c38da1109)

![4](https://github.com/SparkDevNetwork/Rock/assets/130079417/5482fc31-0b3a-4cc1-bfd5-32433204db99)

**Comment by thejasonharvey** [comment]
I don't know how helpful this is, but I went ahead and opened up the Outlook desktop app. It was set to the "new Outlook" and I had the same outcome for the calendar after importing. However, I reverted to the old version, imported the calendar, and I was able to see the events. 

When I went into my calendar online it didn't sync the new calendar over at all. When I switched the desktop app back to the new version, the calendar I had uploaded disappeared - as if I had never imported it. However, if I switch the desktop app back over to the old version the calendar is still there.

**Comment by jacksojourn** [comment]
This may be relevant—

We are also once again experiencing this same issue of events recurring by specific date not exporting. This issue appeared to be fixed for is in 14.1, but then it reappeared in a future release (maybe 15.0?).

We are currently running 15.1. However, when I tried to recreate this issue on the demo site, which is also currently running 15.1, I couldn't do it.

I had kind of just thrown up my hands and was going to wait for 16.1, but the conversation here is making me think something else is going on.

Our issue is occurring in Google Calendar and Apple Calendar.

**Comment by chead4** [comment]
@thejasonharvey Hi Jason - Thanks for your patience and help with this issue.  I was able to recreate your issue using the "New" Outlook on my desktop and although it says my calendar is imported successfully I am not seeing anything populated on the calendar. 

@jacksojourn Thank you for adding more details.  I wanted to let you know that I have included the Google Calendar and Apple Calendar in our internal ticket as well..

**Comment by jacksojourn** [comment]
@MrUpsideDown @chead4 This problem has come back (again) for me in 16.5.

**Comment by chead4** [comment]
@jacksojourn I attempted to recreate the issue on the demo site (v16.6) and wasn't successful.  If you manage to recreate on the demo site, please let me know.

Also, to help us investigate, could you please include screenshots of the issue?  Specifically, a screenshot of the Schedule Builder block, the Event Occurrence block and your calendar showing the date when a calendar event wasn't added. 

Thank you!

**Comment by jacksojourn** [comment]
@chead4 Sure, here you go.

![Screenshot 2024-07-26 at 9 33 59 AM](https://github.com/user-attachments/assets/d7ce7be5-b9d3-4ae8-ac27-43f9ec6f308b)
