### ISSUE TITLE
Group Types Not Sorted Alphabetically in Registration Template Detail Block

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5151]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
Group Types are not sorted alphabetically in the Registration Template Detail block.

I am opening this as an issue because in the idea [here](https://community.rockrms.com/ideas/1666/sort-group-types-alphabetically-in-registration-templates), this was supposed to have been completed as of v13.0, however it is not sorting properly as of _at least_ v13.4+.

In our instance of Rock running v13.6, they are not sorted by their "Order" property, so I am not sure what sort order they are taking in the Registration Template Detail block.

#### A Picture Is worth a Thousand Words
<img width="1728" alt="Screen Shot 2022-08-26 at 14 27 56" src="https://user-images.githubusercontent.com/23226974/186969881-1bfa8545-64fb-4fae-934c-2a653d05a6aa.png">

### Steps to Reproduce

1. Go to `https://rock.rocksolidchurchdemo.com/page/403?RegistrationTemplateId=0&parentCategoryId=174&ExpandedIds=`
2. Click on Group Type.
3. See they are not sorted alphabetically.

**Expected behavior:**

Group Types sort alphabetically.

**Actual behavior:**

Group Types do not sort alphabetically.

### Versions

* **Rock Version:** [At least v13.4+]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
@mikedotmundy  Are you sure they GroupTypes are not being sorted based on their order within the Group Type list?:

Here I ordered Organization Unit to the top:

![image](https://user-images.githubusercontent.com/383807/186997916-71e36ec0-4789-4e31-9345-62dd77c0d693.png)

...and now it appears at the top:
![image](https://user-images.githubusercontent.com/383807/186998025-728e90b3-a8c4-48b9-b554-a48f40d87259.png)

**Comment by mikedotmundy** [comment]
I apologize @nairdo I misspoke. I’m not sure what I was looking at. They are sorted by their Order property.
