### ISSUE TITLE
Connection Campaigns not honoring Number of Days Between Connection

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5158]
### Description
When trying to create a new Connection Campaign, I noticed in both our production (v13.6) and dev (v14.0) instances that the _Number of Days Between Connection_ setting is not functioning properly. 

What I found is that a person will not be included in the Connection Campaign if they have had a Connection Request completed within that Opportunity in the past (even if it was completed outside the value in the _Number of Days Between Connection_ field.)

In my testing, I have the value of _Number of Days Between Connection_ set to "30". People with a Connection Request completed past that 30 day mark were still not included in the Campaign.

However, setting the _Number of Days Between Connection_ value to a lower value, such as 1, 2, 3, 4, etc, then the correct number of people have a Connection Request created for them.

I was unable to duplicate this on the demo site because of the need to have "Connected" Connection Requests in the past. 

In order to test this, here is what I did.
1. Used the same DataView for both Connection Campaigns listed in the next 2 steps.
2. Created a Connection Campaign in a Connection Opportunity we use regularly. Several people in the DataView have had requests completed in the past within this Opportunity (outside 30 days).
3. Created a second Connection Campaign in a different Connection Opportunity where no one in the DataView has ever had a request created for them.

This is the DataView used in both Connection Campaigns:
<img width="1728" alt="Screen Shot 2022-09-04 at 18 26 37" src="https://user-images.githubusercontent.com/23226974/188339034-b248ef40-fa72-4451-bef3-fcf42da4b996.png">

Both Connection Campaigns have the same value for _Number of Days Between Connection_ -- "30"
<img width="1728" alt="Screen Shot 2022-09-04 at 19 29 31" src="https://user-images.githubusercontent.com/23226974/188339048-de068d0a-6337-411d-88e0-44e37525405b.png">

This is now a screenshot of the Campaign List block. 

- The first Campaign called "bus test" is the Opportunity that no one in the DataView has ever been a part of. You will see 19 people are pending, the same amount as the DataView. (This is correct). 
- The second Campaign called "staff" is the Opportunity where several people in the DataView have had Connection Requests before, however it was far outside the 30 day value in the _Number of Days Between Connection_ field. Only 10 people are included. All 19 should have been included (because all 19 are outside the 30 day value in the _Number of Days Between Connection_ field.)
<img width="1728" alt="Screen Shot 2022-09-04 at 18 26 55" src="https://user-images.githubusercontent.com/23226974/188339427-b518d99f-b231-4d0d-a83a-cb9a24f974d8.png">

I happen to be one of the people who, from the second Campaign, have had a Connection Request created for myself. As you can see from the screenshot below, the request was Connected/Completed in May 2021 (over a year ago). 
<img width="1728" alt="Screen Shot 2022-09-04 at 18 26 23" src="https://user-images.githubusercontent.com/23226974/188339673-58bf9693-a04e-41f7-bf57-fe6925adf1ee.png">

So, I should have been included in the campaign and had a new request created for myself, because I was outside the 30 day value in the _Number of Days Between Connection_ field.

This was a rather difficult one for me to write up and explain so if you need me to do further explaining or testing, please let me know.

**Expected behavior:**

_Number of Days Between Connection_ work properly.

**Actual behavior:**

_Number of Days Between Connection_ not working properly.

### Versions

* **Rock Version:** [v13.6, v14.0]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Hi @mikedotmundy, The `Number of Days Between Connection` field currently refers to number of days since the last connection request was **_modified_** (not when it was created).

The date which you referring to in screenshot is date when connection request was created. By any chance is it possible that request in question was modified after the request had been marked as connected?

**Comment by mikedotmundy** [comment]
I was not aware that it refers at _modified_ instead of _completed_. (I never meant _created_ - I apologize if I gave that impression.)

The tooltip for the `Number of Days Between Connection` field says _The number of days since the last connection request was completed..._ 

If the desire is for this field to refer to the modified date, then I would say it is functioning properly. Do you know the reason it is referring to Modified instead of Completed?

**Comment by nairdo** [comment]
@mikedotmundy I meant to hit reply earlier...  I was correct.  There is no other way to determine when the request was changed to a 'completed' state, so we used the ModifiedDateTime property.
