### ISSUE TITLE
Person Picker Long Connection Status Overlaps Family Role and Age

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5159]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/54962439/188716314-b5fd1e5b-4913-43ab-ade2-966b592bdcd9.png)

### Description

When using the person picker longer connection status values can overlap with other content in the search results.

### Steps to Reproduce

1. Add a connection status value to the system that is longer than 20 characters
2. Set Alisha Admin to this new connection status value
3. Pull up Alisha Admin in the person picker

**Expected behavior:**

Styling is in place to handle longer connection status values

**Actual behavior:**

The connection status value starts to overlap other information in the search results.

### Versions

* Rock Version: Rock McKinley 13.5 (1.13.5.1)
* Client Culture Setting: en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1203218818222138">image.png</a>

**Comment by JRichmond27** [comment]
I ran into this a long time ago. My workaround was to add this to the Rock theme CSS overrides:
```
.picker
{
    width: 600px;
    max-width: 100%;
    .picker-label { width: 100%; }
    .picker-menu
    {
        width: 600px;
        min-width: 400px;
        max-width: 100%;
    }
}
```
There are still a few instanstances where there's some overlapping (usually at very specific window widths), but for the most part I've never had a problem with it ever since.

**Comment by dataCollegechurch** [comment]
@JRichmond27 thanks for the workaround. Would you mind marking the issue as confirmed in GitHub to see if we can get a fix of some sort added to Core?

**Comment by garrettjohnson** [comment]
Fixed by truncating longer connection status values in 14.1 via https://github.com/SparkDevNetwork/Rock/commit/bfe266b0e9d70bf5fa4301edbad85b8b74aa8787
