### ISSUE TITLE
Attendance Analytics Exception on Export Caused by Missing Birthdates

### ISSUE THREAD

**Issue by trydyingtolive** [SparkDevNetwork/Rock#5163]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

This one is a little convoluted to describe, but it happened and it caused issues.

Echo.Church was trying to export to excel attendance data from Attendance Analytics, but it kept throwing an exception. This primarily happens with attendances for their online service. It turns out if you try to export from Attendance Analytics and 1. The top most person on the list has no birth day, no birth month and no birth year & 2. the is another person in the list with a birth day and birth month but no birth year an exception will be thrown. 

### Steps to Reproduce

1. Go to the demo site
2. Check in Alex and Noah Decker.
3. Open Attendance Analytics and change the setting so that they appear on the list under the Attendees tab
4. Alex should be the first in the list and Noah second
5. Remove Alex's birth day, month and year
6. Remove Noah's birth year --leaving the day and month.
7. Export the report to Excel

**Expected behavior:**
A nice Excel document is generated

**Actual behavior:**
An exception of "Not a legal OleAut date." is thrown.

### Versions

* **Rock Version:** 1.13.4 & 1.13.6
* **Client Culture Setting:** en-us

**Comment by abpena1979** [comment]
This looks like it was fixed with #4969.
