### ISSUE TITLE
Cannot highlight individual when using Statement Generator Alpha 13.7

### ISSUE THREAD

**Issue by tbunney** [SparkDevNetwork/Rock#5172]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![wonthighlightpersonchosen](https://user-images.githubusercontent.com/37702418/191562169-5b7e8e55-7d6e-48f6-8c39-ee72a862452d.PNG)

### Description

_When clicking on the person from a list of single individuals, it will not highlight the person you chose, so you aren't sure that is the correct person to keep going.

### Steps to Reproduce

1. Go to the Statement Generator
2. Click on Single Individual
3. Find the person you want and click their name
4. See that the name does not highlight.

**Expected behavior:**

The person you select should be highlighted.

**Actual behavior:**

The name does not highlight, even if chosen.

### Versions

* **Rock Version:** Rock McKinley 13.7 (1.13.7.1)
* **Client Culture Setting:** en-US

**Comment by smross** [comment]
@tbunney I'm curious, are you saying that this happened on 13.7 _Alpha_, and the corresponding statement generator application is the latest available version (on the system you have it installed for generating this issue)?

**Comment by MikeDPeterson** [comment]
FYI, I dug into this and it looks like this bug was introduced in v12.5 Statement Generator with this [104f6a240aea77f359309f21f53936775a59a8a1 ](https://github.com/sparkdevnetwork/rock/commit/104f6a240aea77f359309f21f53936775a59a8a1)

**Comment by MikeDPeterson** [comment]
fixed issue with installer with https://github.com/sparkdevnetwork/rock/commit/ff7ca9746fc909837ceca4838567d2044fe23842
