### ISSUE TITLE
Attribute Categories Issue when Applied to Content Components

### ISSUE THREAD

**Issue by asdf1nit** [SparkDevNetwork/Rock#5175]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
New attribute category for managing\organizing Content Component Attributes
![image](https://user-images.githubusercontent.com/18108765/191869950-e4dd6796-f29f-4696-b8db-7bebba6715d2.png)

Added a category to an Entity Attribute for Content Channel Item specific to Content Components ( Id 11 in our system )
![image](https://user-images.githubusercontent.com/18108765/191870245-08b37696-829c-486c-9d61-bf88f64d5f98.png)

Content Component edit screen with attributes, all attributes are not shown.
![image](https://user-images.githubusercontent.com/18108765/191870377-1d57eb54-7557-4cd0-8dce-9e345d75b6b2.png)
 

### Description

The Entity Attributes page can get quite long depending on the entity(in our case it's content channels),and using categories to help filter the list can help manage long lists. We added categories to help deal with this, but If you add an Attribute Category to an Entity Attribute for a Content Component, the attribute will not show on the Content Component edit screen. I propose that an attribute be visible regardless of it having a category.

Additionally, all Attributes added to a Content Channel Item( specific to a content component) are shown on every component, even if that Attribute does not apply to a specific Component (eg. not coded into the template).  While the Attribute description field is handy for calling out which Content Component a given Attribute can work with, I think a better system can be implemented.

For example, we have 6 different Component Templates, some of these templates have specific attributes to control it's characteristics, but those attributes don't apply to other templates. If there is a way we can tie an Attribute Category to a Content Component template, it would be possible to only display the Attributes that are in that category.

So...
If a Content Component Template has an associated Category, only display attributes in the same category. If the Template has no associated category, display all Attributes regardless of the Attribute Category that it could be associated with.  

### Steps to Reproduce

1. Add a new attribute category for the Content Channel Item Entity and name it Content Component Attribute.
2. Add a new Entity Attribute to the Content Channel Item entity and set the Qualifier Field to ContentChannelTypeId and the Qualifier Value to the Id of the Content Component Content Channel in your system(they can be different).
3. Add the newly created Category to the new Attribute.
4. Set up a Content Component block on a page and set the initial values(card, alignment...)
5. Edit the content component block and add an Item.
6. Notice there are no attributes to set.
7. Go back to the Entity Attribute that you added  and remove the Category.
8. Go back to the Content Component block and edit it. You will now notice that the attribute is visible. 

**Expected behavior:**

The attribute to be visible on the blocks edit screen

_[A description of what actually happened.]_

When you add a category to an Attribute the Attribute is no longer visible
### Versions

* **Rock Version:** [13.6]
* **Client Culture Setting:** [en-US]

**Comment by asdf1nit** [comment]
I don't remember reading that before. Thanks Michael! I do agree that it's not intuitive, but it does accomplish what I was wanting to accomplish. If someone from Spark wants to close this, I consider it done, however if it should stay open to track a potential enhancement it would be welcome.

**Comment by nairdo** [comment]
Hi @asdf1nit  Jonathan, it's true that is by design. (We also made quick mention of that in the RockU video around the [10:30 minute mark](https://community.rockrms.com/rocku/cms/content-component)).   So, since this is really just an enhancement request, would you be so kind as to open it as an idea on the [Community Ideas](https://community.rockrms.com/Ideas) board if you really still want to retain that as an official idea/request?

Thanks for all you've done to help us make Rock better together!
