### ISSUE TITLE
Mobile Check-in Phone Lookup verification code paste issue

### ISSUE THREAD

**Issue by radams22** [SparkDevNetwork/Rock#5176]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is Worth a Thousand Words
Did you know you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

When using mobile check-in and you are prompted to enter your phone number for verification, you are sent a text message with a 6-digit code to enter. Typically you can tap the incoming text and it will paste the verification code in for you without you having to type it. Which it does, but it pastes all 6-digits into the first block. 

### Steps to Reproduce

1. Launch Mobile check-in on a mobile device
2. Make sure you are not logged in so you receive the phone number verification screen
3. Enter your phone number
4. Attempt to paste the 6 digit code 
5. See it paste into the first block as shown on the pictures provided.

**Expected behavior:**

The 6-digit code should paste correctly so it does not require the person to erase what is in the first block and then type each number into the respected block.

**Actual behavior:**

When using mobile check-in and you are prompted to enter your phone number for verification, you are sent a text message with a 6-digit code to enter. Typically you can tap the incoming text and it will paste the verification code in for you without you having to type it. Which it does, but it pastes all 6-digits into the first block. 

### Versions

* **Rock Version:** [V13.3] [V13.6] [Pre-Alpha V14]
* **Client Culture Setting:** [English]
![image](https://user-images.githubusercontent.com/72230330/191989488-5cf9fae1-102d-414f-bc84-92e895efe581.png)
![image](https://user-images.githubusercontent.com/72230330/191989555-90159c87-80d4-499a-b20e-56dd1b116b8c.png)

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1203038503828284">image.png</a>

**Comment by abpena1979** [comment]
Thank you, @radams22 for your feedback.  

This number box control is only designed for a single character at a time.  It sounds like your expectation is that pasting the code from the text message validation will parse out automatically, which is not something that it is currently designed to handle.  It is definitely a great idea and one that I would encourage you to submit via the Rock Community Ideas board here https://community.rockrms.com/Ideas.  We appreciate your partnership.  Thanks again for your feedback.

**Comment by abpena1979** [comment]
Hi @radams22  - After some additional thought and due to this being a forward facing feature and an established mobile pattern, I've reopened this as a bug and provide some feedback on a fix shortly.  Thank you for your patience and grace.
