### ISSUE TITLE
Family PreRegistration Won't Save Grade of Senior/12th

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#5182]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

When adding a Child on the Family Pre-Registration page with a grade of Senior, the grade is not stored to the person profile.

### Steps to Reproduce

1. Go to /familypreregistraton page.
2. Enter adult information
3. Add one child and enter a grade of Senior.
4. Save
5. Check the person profile.  The Grade is blank.

**Expected behavior:**
I would expect the grade of Senior to be stored on the person record.

**Actual behavior:**

No grade is stored.  

Line 611 of ControlExtension.cs in SelectedValueAsInt() compares the the Value to Rock.Constants.None.Id.ToString().  In this case, a grade of Senior has a "years to graduation" value of 0 which is interpreted as None and a null is retuned rather than a value of Senior.

### Versions

* **Rock Version:** Found in 12.7 but also exists in 13.6 on rocksolidchurchdemo.com.  It appears to be fixed in PreAlpha.
* **Client Culture Setting:** Azure

**Comment by abpena1979** [comment]
Thanks @mikedotmundy.  You are a quick responder! - This issue was fixed in 14.1 with [ee8e45c](https://github.com/SparkDevNetwork/Rock/commit/ee8e45c7170aa42494ad4b3f83caac4a711a1281) to address #5126.
