### ISSUE TITLE
Contribution Statements

### ISSUE THREAD

**Issue by RufenachtPW** [SparkDevNetwork/Rock#5183]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

![Screen Shot 2022-09-27 at 2 41 24 PM](https://user-images.githubusercontent.com/87141140/192609698-34532b8f-0ebc-41be-ab15-4b6cda4410ac.png)

### Description
Contribution statements do not show up on the Giving Configuration block if there has not been any Tax-Deductible gifts for the year. Example: We need to provide statements to people who have donated non-cash/Soft Credits. If those people have only donated through those means and have not donated to a tax deductible account then contribution statements will not show. 

### Steps to Reproduce

1. Go to a persons contributions tab and add a non-cash donation/ transaction to a non-tax deductible account.
2. Note the contribution statement does not show
3. Add a contribution to a tax deductible account or make the account in step one as tax-deductible and note the contribution statement now shows.

**Expected behavior:**
If contribution statements are set to display non-cash gifts, a contribution statement should be displayed

**Actual behavior:**

Only statements show that include at least one tax deductible gift show up

### Versions

* **Rock Version:**13.7,14.0

**Comment by abpena1979** [comment]
Hi @RufenachtPW 
Thanks for your feedback.  I ran a few tests in the Demo site (13.4) and in our test site (Latest - 1.15.0.3) and I'm unable to reproduce.  The steps I followed are below: 

1.  Go to Finance > Accounts > set one account to Is Tax Deductible = False and one to Is Tax Deductible = True 
![image](https://user-images.githubusercontent.com/108844907/192821709-1024cc21-0eb3-4b69-8865-279c696ee88c.png)
![image](https://user-images.githubusercontent.com/108844907/192821746-8134f9a0-28f4-4188-b814-044e33513b10.png)

2.  I went to a person's contributions page and added one-time (non-cash) contributions. One to each account above. 
![image](https://user-images.githubusercontent.com/108844907/192821920-d094426b-a730-4a88-9062-31e2693aafae.png)
![image](https://user-images.githubusercontent.com/108844907/192821977-7c1c9e5f-e1b4-43f7-bc41-c47f210b1afd.png)
![image](https://user-images.githubusercontent.com/108844907/192822014-f6f07050-abbf-4885-8bc8-bda432f7bbb6.png)

3.  Generated a YTD Contribution Statement - Showed only Non-Taxable contribution (by default) 
![image](https://user-images.githubusercontent.com/108844907/192822224-ce4dd8b0-4918-4447-8871-7e8ece607056.png)

4.  Go to Finance > Financial Settings > Contribution Template Detail and edit option to select all accounts not just tax deductible. 
![image](https://user-images.githubusercontent.com/108844907/192822513-ca04cc59-1421-48af-8a22-8ec57e199d23.png)

5.  Returned to person and re-generated contribution statement and both contributions show now.  
![image](https://user-images.githubusercontent.com/108844907/192822660-56a2ddda-2ea5-4eb6-93a5-58e222243522.png)

Please double check the contribution template detail settings as it may be a setting that is causing the transaction in question to not be included on the statement.   Feel free to reach out to us on Rocket Chat if you have questions. Thanks!
