### ISSUE TITLE
Group Member Triggered Workflow on First Attendance Doesn't Launch When Checking In to Multiple Schedules

### ISSUE THREAD

**Issue by radams22** [SparkDevNetwork/Rock#5184]
[X ] Put an X between the brackets on this line if you have done all of the following:

We have a workflow that is set as a Group Member Workflow on a group type to trigger on first attendance in the group. Our check-in configuration is set to allow people to check into multiple schedules at once. The trigger always fires correctly when the person checks into one (and only one) schedule, but when they check into multiple schedules the workflow trigger usually fires twice, sometimes once, and very occasionally not at all.

Steps to Reproduce

1. On the Rock demo site, create a simple persisted workflow that does something trivial.
1. On the Serving Team group type, create a Group Member Workflow that starts the test workflow on first attendance in the group. Under Attendance/Check-in, choose "Custom" Group Schedule Option.
1. In the Volunteer Check-In configuration, add a Main Campus location to the Greeters group. In Schedule Builder schedule the Greeters group/Main Campus location for the "4:30 (test)" and "6:00 (test)" schedules.
1. Put Ted Decker into the Greeters group in Group Viewer.
1. Run check-in (https://rock.rocksolidchurchdemo.com/checkin) and select Theme = CheckinPark, Kiosk Device = Main Campus: Central Kiosk, Check-in Configuration = Volunteer Check-in, and Check-in Areas = Serving Team (see screenshot).
1. Check to make sure Ted doesn't have any existing attendance records (script below).
1. Check Ted in using phone number "3322", checking him into the Greeters group, choosing both schedules.
1. Check to see how many workflows were launched, delete the attendance records (script below), and check Ted in again.
1. Note that most often two workflow instances are created, but typically every fourth or fifth test only one is created. Very intermittently no workflow is created.
1. Clearing cache sometimes results in no workflow being created, but not always. This is not always the trigger that causes no workflow to fire.

Expected behavior: Logically, one workflow should be triggered, only on the first attendance record added. The worst case for us is when NO workflow is triggered.

Actual behavior: Intermittently two, one or zero workflows are triggered.

Rock Version: 1.13.3.1, but tested on demo, 1.13.4.1, and prealpha, 1.14.xx, and all behaved the same way.

Client Culture Setting: [en-US]

Script to check for attendance records for Ted:

SELECT * FROM [Attendance] a

LEFT OUTER JOIN [PersonAlias] pa ON pa.[Id] = a.[PersonAliasId]

LEFT OUTER JOIN [Person] p ON p.[Id] = pa.[PersonId]

WHERE p.[Id] = 4

Script to delete attendance records for Ted:

DELETE a FROM [Attendance] a

LEFT OUTER JOIN [PersonAlias] pa ON pa.[Id] = a.[PersonAliasId]

LEFT OUTER JOIN [Person] p ON p.[Id] = pa.[PersonId]

WHERE p.[Id] = 4

![image](https://user-images.githubusercontent.com/72230330/192805814-d702af36-7843-4fda-92cb-d901381df56a.png)

![image](https://user-images.githubusercontent.com/72230330/192805871-d8d8b1e0-9c03-4a57-bca2-79d9dde5bac8.png)

![image](https://user-images.githubusercontent.com/72230330/192805916-9cc5128d-6e34-4fef-ab12-cd77988ac14e.png)

![image](https://user-images.githubusercontent.com/72230330/192805987-2d3e612b-1c22-4845-a383-d7a4e0cbdad4.png)

**Comment by chead4** [comment]
Reopening this issue as it has been reported and confirmed that the issue is reoccurring in v16.2.
