### ISSUE TITLE
Chart lava shortcode using the tsgauge type has gridlines

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#5188]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

Using the tsgauge option for the chart lava shortcode, you get a y-axis of 1 and the arrow for the gauge shows a shadow of every tick it made during the animation. IMO, axis gridlines on a gauge chart never make sense and should always be turned off by default. This behavior started somewhere between v13.0 and v13.4. In 13.0 there are no gridlines but there are in 13.4.

### Steps to Reproduce

1. In an HTML block on any page, paste the example code for the gauge type of the chart lava shortcode.
2. Refresh the page to make the chart appear.

**Expected behavior:**

Gauge chart with no axis gridlines and a nice looking arrow marker
![image](https://user-images.githubusercontent.com/12735965/193601029-6c04d589-610e-415d-b971-8ad2a0cea466.png)

**Actual behavior:**

Y-axis of 1 with gridlines and an arrow marker with a weird shadow.
![image](https://user-images.githubusercontent.com/12735965/193600922-852a4810-bf98-49c4-bf34-7f8978c6f2d7.png)

### Versions

* **Rock Version:** [13.4-13.6]
* **Client Culture Setting:** [en-us]

**Comment by garrettjohnson** [comment]
Fixed by https://github.com/SparkDevNetwork/Rock/commit/03300298916111194a6f47d90f41a60e9abfb69a in v13.7 and v14
