### ISSUE TITLE
Communication History Recipient Count Filter is sticky

### ISSUE THREAD

**Issue by stevekleinliquid** [SparkDevNetwork/Rock#5190]
### Description

On the Communication History page, once the recipient count range is set, it cannot be permanently cleared.
<img width="1258" alt="Screen Shot 2022-10-04 at 4 07 07 AM" src="https://user-images.githubusercontent.com/114983828/193767681-be28ff6a-f787-4936-93de-7ce36e52e907.png">

### Steps to Reproduce

1. Go to the Communication History page, open filter options, set the recipient count range (e.g. 100 to 200) and click on Apply Filter to filter.
2. Open filter options and clear the recipient count range (i.e. remove numbers from both fields) and click on Apply Filter to filter.
3. Navigate to another page (e.g. Group Viewer) and then back to Communication History.

**Expected behavior:**

Clearing the recipient count range should remove that part of the filter. Those values should remain cleared until they are set to something else.

**Actual behavior:**

Once set, the recipient count range cannot be permanently cleared. Note that while you are on the Communication History page, you can clear the recipient count range and this setting will be honored, although the last entered range will be displayed at the top of your results.

@leahjennings came up with a clever workaround - by setting the range to from 1 (to blank), you can essentially clear the filter.

### Versions

* **Rock Version:** [12.7]
* **Client Culture Setting:** [en-us]

**Comment by asdf1nit** [comment]
I can confirm, we have the same issue on v13.6
