### ISSUE TITLE
Edit Family Option Missing For Non-Admin Users

### ISSUE THREAD

**Issue by adamhann** [SparkDevNetwork/Rock#5192]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![Screen Shot 2022-10-05 at 2 33 00 PM](https://user-images.githubusercontent.com/23084345/194136372-7cd2947b-da38-4a1a-a774-a6899fa720c7.png)

![Screen Shot 2022-10-05 at 2 32 51 PM](https://user-images.githubusercontent.com/23084345/194136396-9b97537f-2ceb-4dac-ac8b-ab6c20b47555.png)

### Description

It appears that in the latest build of v14 (1.14.0.18) that non-admin users cannot access the edit family button. I've been able to reproduce in our current version of v14 and also on the Pre-Alpha site.

### Steps to Reproduce

1. Login as Admin
2. Go to a person profile and go to edit their family. 
3. You can successfully click on the pencil icon and edit the family. 
4. Login as a non-admin user or impersonate a non-admin, staff account.
5. Go to the same profile and try to edit the family. There is no pencil icon.

**Expected behavior:**

When a staff user (or any user with appropriate security settings) goes to a profile page they should be able to edit the family. 

**Actual behavior:**

Only Rock Admins have the ability to edit a family. 

### Versions

* **Rock Version:** [1.14.0.18]
* **Client Culture Setting:** [en-US]

**Comment by abpena1979** [comment]
@adamhann, Thanks for your feedback. We are taking a look at this now.  

In the meantime, if you want to continue testing, you can compare the edit block security settings of your pre-v14 environment and copy the settings to the v14 environment for Person Bio Block (from previous to v14 - Bio Block) and Family Members block.  That should address the issue and allow you to proceed.

**Comment by adamhann** [comment]
@abpena1979 Maybe I'm misunderstanding you, but that's how it's already set up. Are you saying the Family Member block in v14 is different than v13? Also, for context, we are running v14 in production for a few specific reasons. So we no longer have access to our v13 version of Rock. But, the security settings are the same.

**Comment by adamhann** [comment]
@abpena1979 Nevermind! I didn't realize the Edit on the block needed the security roles. I was just looking at the page the edit button takes you too. Thanks!
