### ISSUE TITLE
Check-In KioskStark theme causing blank white screen

### ISSUE THREAD

**Issue by davidbelk** [SparkDevNetwork/Rock#5196]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

When selecting the Check-In theme KioskStar, a blank white screen appears and you cannot select another theme. 

### Steps to Reproduce

I have tried this on the demo site and FBC Hendersonville has confirmed this as well. 

1. Go to https://rock.rocksolidchurchdemo.com/checkin
2. Click on theme
3. Scroll down to KioskStark

**Expected behavior:**

The KioskStart theme would appear

**Actual behavior:**

A blank white screen appears and I am unable to change the theme even if I change the URL to us another theme. Clearing the cache brings it back to the CheckinPark theme on the browser version. 

### Versions

* **Rock Version:** 13.6 / 14.0 Beta
* **Client Culture Setting:** en-US
![1](https://user-images.githubusercontent.com/43145156/195187305-6efe6f5f-1c30-441d-97b5-d37435ffb32a.png)
![2](https://user-images.githubusercontent.com/43145156/195187307-0a0b184b-7577-4568-9d3e-4fb59d9597d7.png)
![3](https://user-images.githubusercontent.com/43145156/195187309-5dbaf251-a9d3-42cb-ac75-91ae9360d18e.png)
![4](https://user-images.githubusercontent.com/43145156/195187310-4fa214ab-3489-4fe4-bfc1-8fba3a855156.png)

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1203159611459126">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1203162619721615">image.png</a>

**Comment by nairdo** [comment]
We're verifying with @davidbelk to confirm that this last minute beta fix (https://github.com/SparkDevNetwork/Rock/commit/8b9446f1432472b6f5ca3f47f214a918eba9288d) resolved this issue.

**Comment by nairdo** [comment]
@davidbelk  After further investigation, I believe this problem is unique to the KioskStark theme which was never quite intended for use with the Check-in system.  It was intended for use with the 'Self-Service Kiosk' (preview) site and [Prayer Kiosk block](https://prealpha.rocksolidchurchdemo.com/page/384), etc.  Regardless, we're going to address the bad (blank screen) behavior when you select that theme and get stuck until you delete your `Checkin.LocalDeviceConfig` cookie.

**Comment by davidbelk** [comment]
Thank you! we do not use it but have had a person click it when they were scrolling through themes and could not recover on their own.
