### ISSUE TITLE
Editing a schedule on an existing Event Item Occurrence doesn't update the Next Start Date

### ISSUE THREAD

**Issue by mkinyon** [SparkDevNetwork/Rock#5197]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Steps to Reproduce

1. Create a new event item occurrence with a one time schedule set in the future.  
![image](https://user-images.githubusercontent.com/2349102/196497435-0c81a283-ee78-4103-9c13-175d71918a83.png)
![image](https://user-images.githubusercontent.com/2349102/196497477-e156cc2d-0445-487c-8c6d-679496b151fe.png)

2. Next, edit the event item occurrence by changing just the schedule to a different date.
![image](https://user-images.githubusercontent.com/2349102/196497598-fb0ca6c4-d610-43f6-8c33-58bd9a78654b.png)

3. Return to the event item occurrence list and see that the Next Start Date is incorrect.
![image](https://user-images.githubusercontent.com/2349102/196497694-716b591b-d06f-4a29-b83e-f754bbef7bc6.png)

The issue seems to be caused by the fact that editing just the schedule doesn't trigger the event item occurrence PreSaveChanges() to update the NextStartDateTime field since the Event Item Occurrence itself was not modified.

**Expected behavior:**

Expected the Next Start Date to update when changing the schedule on an event item occurrence.

**Actual behavior:**

The Next Start Date does not update.  (Eventually it will fix itself when the Rock Cleanup job runs.)

### Versions

* **Rock Version:** v13.7, latest develop
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
It looks like we found this issue internally and fixed it a few weeks ago for the v14.1 release: https://github.com/SparkDevNetwork/Rock/commit/96f921a8359b99a2f3a4fe8a5e76d645c5b1990c.  @mkinyon  We weren't able to reproduce this on the [prealpha site](https://prealpha.rocksolidchurchdemo.com/) -- but please let us know and re-open this issue if you believe we have not fixed it.
