### ISSUE TITLE
Rock App does not allow Phone/Email login if the Profile Protection level is High or Extreme.

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#5199]
Also reported on Rock.Mobile.

Describe the Issue in Detail

Submitted on behalf of Fellowship Bible Church of Northwest Arkansas

In using the Rock Mobile App, people with a profile protection level of high or extreme (such as church staff) cannot login to the app using Phone Number or Email. They receive a message "It appears you have an account in our system that has security access which requires you to login with a username and password." However, they use Office 365 logins for Rock so they do not have database logins that can be used on the app and the app has no way to change the password if a new login is created (which is not secure).

Even if the profile protection is lowered on staff security groups, the job sets them to High if they have scheduled giving or stored payment methods.
Can reproduce in

Blue App

Steps to Reproduce

    Create a person in the Rock DB with an Extreme Profile Protection level and a mobile phone and email.
    Load the app on the phone with the entered number.
    Try to login using phone or email.
    "It appears you have an account in our system that has security access which requires you to login with a username and password." is displayed.

Expected Behavior

I would expect phone/email code authentication to be able to be used on the app even with profile protection in place. This seems as close to MFA as is available at present and more secure than having separate logins just for the Mobile App (separate from Office 365 used for Rock).
Actual Behavior

Phone and email based authentication is not available to staff members.
Screenshots or Videos

https://user-images.githubusercontent.com/33356643/195931846-52f86f00-57d6-483d-bd61-f9a6c2c70a2a.jpg

Reproduction XAML

No response
Mobile Shell Version

1.4.0.8
Last Known Working Version

Prior to v13.6 Rock Server Upgrade
iOS Device Type(s) and iOS Version(s)

iPhone 12
Android Device Type(s) and Android Version(s)

N/A

**Comment by jonedmiston** [comment]
This is actually intended functionality. Since this login is not using a password it really is one factor authentication and with the ease that some people could change a phone number or email in an organization with lose data integrity rules we felt it would not be secure for use to make the determination that this should be allowed.

We are working on some additional login features for web that will have the same problem. Our solution will be to add an additional security setting to a "Allow Passwordless Logins for the Following Protection Profiles". Out of the box we'll lock down  High and Extreme, but an organization will be able to enable it if they wish.

**Comment by jonedmiston** [comment]
@bobrufenacht can you confirm you are using the Onboarding Block for the login. There is a setting on this block to control what protection profiles are allowed to login. Is this not working for you?

![image](https://user-images.githubusercontent.com/548178/200039887-3ba31156-f110-414b-8091-b7dca738c2fd.png)

**Comment by nairdo** [comment]
For clarity, we're not adding 'passwordless' login (beyond what the Onboard Person block already has in Rock Mobile) but we are going to change the Onboard Person block in v15 to pick up that security setting from the new spot in the "Admin Tools > Security > System Security" page:

![image](https://user-images.githubusercontent.com/383807/219519932-e7a03963-d045-46e9-939d-acfcaa988894.png)

That is what the next commit will be that appears here (and closes this issue).
