### ISSUE TITLE
Check-in Schedule/Group Selection issue

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#5202]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
<img width="1816" alt="Screen Shot 2022-10-20 at 5 49 21 PM" src="https://user-images.githubusercontent.com/5738650/197077868-f015cd5b-1f11-46eb-8afb-885750e7904d.png">
<img width="892" alt="Screen Shot 2022-10-20 at 5 54 24 PM" src="https://user-images.githubusercontent.com/5738650/197077891-b4e045f4-bb8b-4789-896d-ec86c02f10cb.png">
<img width="891" alt="Screen Shot 2022-10-20 at 5 51 35 PM" src="https://user-images.githubusercontent.com/5738650/197077906-9c8aa4e5-224f-4310-95ef-26fc4f68f6f6.png">

Selecting 2 services:
<img width="872" alt="Screen Shot 2022-10-20 at 6 10 50 PM" src="https://user-images.githubusercontent.com/5738650/197078434-f3dd17c9-3958-4ad4-893f-f688fee563db.png">
<img width="2002" alt="Screen Shot 2022-10-20 at 6 29 47 PM" src="https://user-images.githubusercontent.com/5738650/197078465-20399bd3-53e4-4c42-85c3-7fe25e6e31fd.png">

Selecting 1 Service
<img width="884" alt="Screen Shot 2022-10-20 at 6 10 41 PM" src="https://user-images.githubusercontent.com/5738650/197078564-e21fa670-230c-4b70-8f78-e559e2b795fc.png">
<img width="825" alt="Screen Shot 2022-10-20 at 6 32 10 PM" src="https://user-images.githubusercontent.com/5738650/197078602-f50259ba-f08c-4bd5-a5b1-04e304d9c36d.png">

Selecting 1 Service then backing out and selecting a second
<img width="907" alt="Screen Shot 2022-10-20 at 6 11 16 PM" src="https://user-images.githubusercontent.com/5738650/197078652-c7192889-a638-40ab-82dd-9ad6a9f5f9f9.png">

### Description

Around three to four months ago we switched check-in from trying to auto-populate what the individuals were checking into to having them select their service(s) and group(s). We use Family style check-in. About a month to a month and half ago we started up our Kids Art & Theater program that runs during the first service. These groups are under a different group type (but same group area). There is a group for each grade with an age and grade filter set. 

For the first week or two of this program we had no issues with check-in (or at least we were not made aware of the issue if it was occuring). When a 6th grade girl selects the 8:45 am service and then a second service, she gets the option for K-6th Grade Sunday groups or KATs Sunday Groups for the first service and then automatically gets the group she filters into for the second service. This is how it should work. 

The problem we faced was when boys needed to check into KATs but were attending two services. If they only select one service they are presented with the group type option for KATs or for K-6th Grade Sunday groups. When the boy selects 2 services, the option to select KATs or K-6th Grade group type is skipped and the boy is auto-placed into his filtered group for K-6th Grade and doesn't get the option to select KATs for 8:45.

Tangent to this (but may be a different issue): if you only select one service time, you are presented with the two group type options. If you click the back button to go back to the service times page and select the second service option in addition to the first, then click next, Rock will display an error message saying there wasn't anything the individual could be checked into for the second service. At this point you are left with going back and only checking into the first service or starting over. This could be a separate issue but was discovered during the time we were trying to figure out what was going on with the initial problem. I do not run into this issue when the individual is a girl, so far I have only noticed it when it is a boy.

We thought this might be some kind of bug related to genders since the girls appeared to not have any issues but the boys did (I have only heard of one girl who may have had an issue but I haven't been able to replicate it yet with a girl when testing). I looked through our KATs groups and gender is not a filter on those groups, just Age and Grade. For our K-6th Sunday groups, we do have gender filters on our 4th-6th grade groups.

There are only two of us that handle the check-in administration stuff and neither of us made any changes to Rock around the time this issue started happening. We were on 13.3 when we noticed the issue. We updated 13.7 last week and the issue was still present the following Sunday.

By this point all students should be registered for this program, so we did update the group type for KATs to require that they are in the group (Already Belongs) instead of having it be open check-in. So my screenshots will have that new setting. However, the issue is still present for the boys who are members in the group.

I when through the workflow and all its actions and made sure it lined up with how the demo site is set. Only made one minor change to match what the demo site had but that didn't fix or alter the issue.

There are two attribute value records in the database for the gender group type attribute. One was created back in 2018 on the first grade group but has a blank value. The second one is on the 6th grade and was created when I was testing check-in, after being made aware of the issue. The value is also blank.

I will do some more testing to see if this occurs with other Group Types when selecting multiple services but I'm stumped on what to test or try next.

### Steps to Reproduce

I haven't tried reproducing this on the demo site yet but will look into trying. I'm just not certain how to reproduce it since everything appears to be set correctly.

**Expected behavior:**

Boys and girls who select multiple services should be presented with available group and group type options for each service when available. 

**Actual behavior:**

Currently boys who select multiple services to check into do not get the option to choose a group or group type when one is available.

### Versions

* **Rock Version:** 13.3 and 13.7
* **Client Culture Setting:** en-US

**Comment by azturner** [comment]
Not sure, but wonder if this might be related to this issue also: https://github.com/SparkDevNetwork/Rock/issues/5215

**Comment by BEGamache** [comment]
@azturner Possibly related. Was chatting with TJ Peera and they are experiencing something similar and have also messed with that block setting in their tests. We have that block setting set to 'No'. I did test out 'Yes' and ran into issues right away on a Sunday and switched it back to 'No'.
