### ISSUE TITLE
Disallowing $0 transactions creates pain without clear benefit

### ISSUE THREAD

**Issue by SteveSwaringen** [SparkDevNetwork/Rock#5205]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
<img width="851" alt="image" src="https://user-images.githubusercontent.com/45042927/197852363-4deee48d-41be-45ea-b28e-6ab488ac0446.png">

### Description

This commit (https://github.com/SparkDevNetwork/Rock/commit/e00b5a47e4d48476a85e796c6ae5d398ac78da1f), first deployed in V13.7, disallows modifying a transaction amount to $0. The commit message didn't give any indication of why this was added and it isn't clear why a $0 transaction would be problematic. On the contrary, we use this frequently in post-processing of event registrations where scholarships were involved. We create a transaction for the scholarship so the registration will reflect that the amount owed has been paid in full. However, if the registrant doesn't attend the event, we need to go back and zero out the scholarship amount so we can reflect the correct amount of scholarships for the event and balance our books. Without the ability to either delete or zero the transaction, we have to hack the database directly.

### Steps to Reproduce

1. Go to the transaction detail of a registration payment (probably any transaction detail).
2. Edit the transaction.
3. Set the value to 0
4. Save

**Expected behavior:**

The transaction should be updated with a value of 0.

**Actual behavior:**

The save is disallowed with an error saying you have to have a non-zero value.

### Versions

* **Rock Version:** [1.13.7]
* **Client Culture Setting:** [en-US]

**Comment by taylorbrooks** [comment]
I second this. It has affected a lot of churches we work with.

@SteveSwaringen Our "hack" is to input the transaction as $1.00, then update the transaction detail to $0.00 through SQL.

```sql
DECLARE @TransactionId int = YOUR_TRANSACTION_ID_HERE
-----
UPDATE FinancialTransactionDetail
SET Amount = 0
WHERE 
    TransactionId = @TransactionId
```

**Comment by nairdo** [comment]
Thanks @SteveSwaringen.  A church in the community originally considered it a bug/invalid to enter a transaction without an amount, so we made that adjustment.   In their case, they were trying to avoid a data entry error during transaction _creation_.

Can you confirm we're understanding the situation you're describing: 1) Person registers for event, 2) Later, a payment (?) is made  (scholarship) and applied to the registration on behalf of the registrant, 3) Later, if the person did not attend, the transaction amount is zeroed out (no refund is issued).

I just want to understand if your case always starts with an initial (previously saved value) that is later being modified and zeroed out.  Perhaps we can consider allowing a $0 value on modify/update.

**Comment by SteveSwaringen** [comment]
Nick, Yes. That change would address our use case.

**Comment by JimMichael** [comment]
Note that some orgs are used to entering $0 transactions for “non cash” gifts, thus such a proposed fix would not fix the issue for such orgs. 

Example: https://chat.rockrms.com/channel/giving?msg=xmgq5s42eQqeqcB6w

**Comment by nairdo** [comment]
I'm no accountant, but it _seems_ like a refund of the scholarship would be a more traceable change to adjust the amount...
![image](https://user-images.githubusercontent.com/383807/198407983-eb865820-1606-477f-bbf5-bdf63445f2a5.png)
...but I also understand the audit log would still show an amount being zeroed.

For a **Currency Type** of "Non-Cash Asset" it also seems like there would/should be some $ amount assessed for the asset.  Jim, do you know in that case is the dollar value assessment done later?

We just discussed this issue, and we are going to allow zeroing on modify.  We're also considering the impact to these other use-cases.

**Comment by JimMichael** [comment]
I’m not up on the specifics, but it’s my understanding that when stock (a non-cash gift) is given, the church does not assign an amount to it, as it’s value depends on when it’s donated vs sold by the org. In such cases, the broker or whomever is responsible for giving the donator statements / amounts for tax purposes. 

So, the org (church) doesn’t reflect amounts for such non-cash gifts on a contribution statement, yet some orgs at least want them to SHOW (the fact the gift was made) on the statement, thus enter them as $0. 

At least that’s my non-financial-brain understanding. I’m curious why $0 was ever considered a bug, though. $0 is a valid number  :-)

**Comment by jsw-austin** [comment]
There are definitely churches entering $0 amounts on a person's record to reflect their directed giving on their records.  Things could definitely be done to improve recording of financial transactions so that churches don't have to figure out hacky work arounds.  I'd say removing the possibility of entering $0 will likely have a greater impact in the community than you realize.  

From a tax perspective the receiving organization likely shouldn't assign a value to a non-cash item given.  That's the responsibility of the donor to assess, which is one reason a church would want put $0.

**Comment by austinspooner** [comment]
We have this same issue. 3 churches I currently work with enter $0 for asset / stock type gifts to be able to record them on the individuals Rock record.

**Comment by nairdo** [comment]
Thanks everyone!  This is great feedback.  We're going to change that block to simply warn (via modal) the individual that they are entering a $0 transaction (for those cases). That should address everyone's issues.  Thanks again!

**Comment by austinspooner** [comment]
@nairdo What release do you all expect this to be fixed in?

**Comment by nairdo** [comment]
@austinspooner  We expect this in release **v14.1**, but once we've tested the final changes, if someone was on v13.7 (and this was causing them _major_ grief) they would be able to grab the `TransactionDetail.ascx` and `TransactionDetail.ascx.cs` block from the `hotfix-1.13.8` branch to address this sooner than the official v14.1 release.
