### ISSUE TITLE
Link Between Internal Site and File Browser/Image Browser in Edit HTML Block Seems to Be Broken

### ISSUE THREAD

**Issue by jtwong95** [SparkDevNetwork/Rock#5206]
## Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

## A Picture Is worth a Thousand Words
![Screenshot (100)](https://user-images.githubusercontent.com/116765398/198148522-69708010-16d6-4f28-81ca-e2e7f7c1b00f.png)

![Screenshot (98)](https://user-images.githubusercontent.com/116765398/198148613-c187fe94-d807-47f6-95f1-e8e18aaf352a.png)

![Screenshot (104)](https://user-images.githubusercontent.com/116765398/198149690-a746830b-811a-4b16-8b1c-8c1781a9c040.png)

![Screenshot (103)](https://user-images.githubusercontent.com/116765398/198149710-902c7b74-0c14-4b13-9e68-c319715b2b23.png)

## Description
Opening "Image Browser" or "File Browser" in any "Edit HTML" pop-up on the External Site (Second Image) causes the related Internal Site to revert back to what looks like a developmental stage of Rock where all of the child pages on each of the Home page's child pages are hidden (Top Image). The theme is also very basic and poorly formatted. It occurs similarly between Rock Demo Site and my site, though the coloring is different and the formatting is worse (Third and Fourth Image). Clearing browser cache reverses the issue.

## Steps to Reproduce

1. Go to Demo Internal Site
1. Open External Site in separate tab
1. Go to any page where you can Edit HTML content
1. Choose to Edit any of the HTML Content Blocks
1. Switch Code Editor to Preview mode
1. Click on Image or File Browser
1. Click Cancel on the Select Image/File pop-up
1. Click Cancel on the Edit HTML pop-up
1. Go back to Internal Site and hit Refresh

**Expected behavior:**After opening up Image Browser, I expected to see Image content saved on the Internal Site.**Actual behavior:**There was only a few images and icons that were saved directly to the External Site and the Internal Site was empty. The Internal Site did not even have a drop down for any child pages

## Versions

* **Rock Version:** [Rock McKinley 12.8 (1.12.8.1)]
* **Client Culture Setting:** [en-US]

**Comment by BrentPirolli** [comment]
Confirmed in v14.2 on FF as well... CRAZY bug!
