### ISSUE TITLE
Loading API documentation pages consumes GIGS of memory

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#5210]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/19762670/199346339-bc0d4527-a03b-4f34-819f-d0950772a0d2.png)

### Description

When you load documentation, click on one of the entity types, wait for all of the stuff to load, and then expand a few options.

### Steps to Reproduce

(Tested in multiple chromium browsers)
1. Go to https://rock.rocksolidchurchdemo.com/api/docs
2. Go to Step, StepType, StepTypePrerequisites controllers
3. Expand serveral of the options
4. Watch Memory use reach heights of 3-5GB and up.

**Expected behavior:**

Happy API docs

**Actual behavior:**

Sad API docs

### Versions

* **Rock Version:** v14, v13.7
* **Client Culture Setting:** en-US

**Comment by NuclearTacos** [comment]
It seems that many of the endpoints are behaving fine, but Steps, StepTypes, StepTypePrerequisite are all behaving this way for me.

**Comment by NuclearTacos** [comment]
Curiously, the issue is replicatable on the 10.1 time machine.  This is a recent issue (to my awareness), or it's only on some rare EntityTypes.
~/api/docs/index#!/StepTypePrerequisites/GETapi_StepTypePrerequisites_InDataView_dataViewId_entityId

**Comment by MikeDPeterson** [comment]
@NuclearTacos It looks like the problem is that swagger/swashbuckle auto-generates a giant 'Example Value' for models that have lots of nested properties. We can override that behavior and have it just generate a simple example of the class instead. That'll speed up lots of those.

**Comment by NuclearTacos** [comment]
Yeah! If there's a way to make it only do one level of depth into the
properties, that seems like it would be the best option.

But I'm always on board for whatever is best and is the least work to
maintain.
