### ISSUE TITLE
Obsidian Registration Entry Block Displays Narrow Signature Document Viewer

### ISSUE THREAD

**Issue by JDShuman** [SparkDevNetwork/Rock#5216]
* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![Bug-SignatureDocumentWindowFull](https://user-images.githubusercontent.com/93220961/201158883-5940437d-2842-4963-a88a-1c5d4c1b9395.png)

### Description

We are currently running Rock Version 14.0 (1.14.0.18), and I’ve tested this on the demo site which is running the same version.

The new Obsidian Registration Entry block is displaying a very narrow window for the signed document portion of the registration. The standard registration page on the demo site is not currently using the new obsidian block, so I had to create a new page to demonstrate the issue. 

### Steps to Reproduce
1. Log into the demo site (`https://rock.rocksolidchurchdemo.com`) and create a new registration page with the new Obsidian Registration Entry block (I created one under “External Homepage\Calendar” which I named “Obsidian Registration” for ease of reference). Make sure to add appropriate page routes to accept the registration slug (`obsidian_registration,obsidian_registration/{CampusId}/{GroupId},obsidian_registration/{Slug}`)
2. Add the Obsidian Registration Entry block to the new page.
3. Create an event registration that requires a signature document.
    1. I created a registration template under “General” that required a Field Trip Release (Event Registration) Signature Document with no cost on the template). This template was named Field Trip with Waiver.
4. Create New Registration Instance under the new template. Set a linkage on the instance to navigate to the registration entry form on the new registration entry page.
5. Load the registration entry form on the new page (my test used: `https://rock.rocksolidchurchdemo.com/obsidian_registration/test-field-trip`
6. Fill out the first registration form page and click “next” to load the signature document page

 **Expected behavior:**
I would expect the signature document to load in full width under the progress bar. I can add a style tag to the “pre-HTML” in the block advanced settings to accomplish this:
```
<style>
    .signaturedocument-iframe {
        width: 100% !important;
    }
</style>
```

However, I would anticipate it would load full width by default.

**Actual behavior:**

The page loads with a normal width, however the signature document viewer embedded not he page is very narrow (about a quarter of the width of the progress bar above it).

### Versions

Rock Version 14.0 (1.14.0.18)
Client Culture Setting: en-US

**Comment by garrettjohnson** [comment]
@JDShuman, to fix this issue you can go to CMS Configuration > Themes and then recompile any theme where you are seeing the incorrect rendering. Let me know if that doesn't work for you, or if I can be of further assistance.

**Comment by jonedmiston** [comment]
@JDShuman The themes should auto compile. We're working on fixing an issue that's preventing that from happening. In the meantime @garrettjohnson 's recommendation will get you back to normal operation.
