### ISSUE TITLE
Lava Entity command fetches more than expected

### ISSUE THREAD

**Issue by nlBayside** [SparkDevNetwork/Rock#5230]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

![Screen Shot 2022-11-22 at 12 18 32 PM](https://user-images.githubusercontent.com/85907597/203413044-1f227c27-b013-4936-a971-8f405c64fdf7.png)

### Description

When using the Lava Entity command with the "id" filter, I noticed there was a problem with what was being returned from my Lava and what I expected. In the "id" filter, I forgot to type the pair of curly braces around my variable and this led to it fetching *much* more than I anticipated. It ended up fetching every record from the database. This was a bit problematic because it was timing out my request and the thread was being aborted because it was too long.

I'm of the opinion that the command should break here or at least provide a warning. I understand that the main point of this is my typo; however, a simple mistake such as this should not send the server into a grinding halt.

From what I could tell, this issue was caused by the [ExpressionHelper](https://github.com/SparkDevNetwork/Rock/blob/09d6bf161940291983ce8843d47efcef5fb02a80/Rock/Utility/ExpressionHelper.cs#L91) class. It returns ```Expression.Constant( true )```, so that might be the problem when Rock is evaluating the entire Query Expression. I'd love to hear more feedback on this! Maybe this is intended behavior which is totally fine; however, if it is then there should be a warning in the documentation.

### Steps to Reproduce

1. Go to 'rocksolidchurchdemo.com'
2. Create an HTML Content Block
3. Configure the block to use the Entity command
4. Write some Lava using the Entity command with an improper "id" filter.
5. See error

**Expected behavior:**
I would have expected it to break, rather than fetch all records from a specific table.
My anticipated response was: 
1. Return no results at all
2. Or, display a warning that the "id" filter was improperly filled out.

**Actual behavior:**
It fetches **every** record from a table in the database. This can be quite taxing if a server has scarce resources and a large database.

### Versions

* **Rock Version:** [v14]
* **Client Culture Setting:** [en-us]

**Comment by jonedmiston** [comment]
The Entity command does have a limit guard built in. It should be (and in my testing appears to be working) limiting the results to the first 1000 records. Can you test again your finding that it returns every record in the table?

We could add a check to ensure that the Id is an integer which would solve the issue[ here](https://github.com/SparkDevNetwork/Rock/blob/09d6bf161940291983ce8843d47efcef5fb02a80/Rock/Lava/Blocks/RockEntityBlock.cs#L146). But if the rate limiter is working I'm not sure why your thread aborted.

**Comment by nlBayside** [comment]
Thanks for the quick reply, Jon! It is very strange that the request took so long. I think the limit would apply in most cases. From what I could grab in the SQL Profiler, it does not grab a "top 1000" unless I set ```securityenabled:'false'```.

Group with the default securityenabled filter:
![Screen Shot 2022-11-22 at 1 55 17 PM](https://user-images.githubusercontent.com/85907597/203429275-c9e6f8ef-5abb-4848-866d-7671167deab2.png)

Group with securityenabled filter set to "false":
![Screen Shot 2022-11-22 at 2 02 05 PM](https://user-images.githubusercontent.com/85907597/203430401-b134cc2c-821e-434e-aaf8-ee0aa75933ab.png)

My guess is that when it's evaluating the permissions on the entity, it has to evaluate the Queryable which executes the SQL query. This occurs prior to the ```Take()``` operation. This line [here](https://github.com/SparkDevNetwork/Rock/blob/09d6bf161940291983ce8843d47efcef5fb02a80/Rock/Lava/Blocks/RockEntityBlock.cs#L386) evaluates the Queryable before it checks the ```IsAuthorized``` method.

![Screen Shot 2022-11-22 at 2 07 07 PM](https://user-images.githubusercontent.com/85907597/203431162-89780851-c8f6-4275-a31c-049df61d0d63.png)
Hopefully these screenshots help!

**Comment by nlBayside** [comment]
Hi Jon, hoping we can reopen this issue since it can occur in two places. One of those places is already covered by your commit, which is great! Thank you for that. The other area that this occurs is in the "where" filter when a person uses the Id property inside of it. [Here](https://github.com/SparkDevNetwork/Rock/blob/237bf1f0f97dd21b6e4f8e70984f205c8eddf079/Rock/Lava/Blocks/RockEntityBlock.cs#L880) is probably where another check needs to be placed.

I think this could be solved in a few ways:
1. There's [this line](https://github.com/SparkDevNetwork/Rock/blob/237bf1f0f97dd21b6e4f8e70984f205c8eddf079/Rock/Utility/ExpressionHelper.cs#L129) in ```ExpressionHelper.cs```, that could be modified to either check if the propertyType is nullable, or just use ```AsInteger()``` instead of the nullable one.
2. Or it could be validated even higher, such as in ```RockEntityblock.cs```. This would just be checking that the "Id" parameter is actually cast with ```AsInteger()```. This is pretty similar to your solution for the first case, so I think it's the best solution.

Hoping this can be reopened so that this issue can be fully resolved. If not, I can always create a new issue but I think they're so similar that it should be the same ticket. Thanks Jon! Very appreciative of the team's work with wanting to solve this issue.
