### ISSUE TITLE
Case Statement Works Differently in Fluid vs. Liquid

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5232]
### Description

While hunting down Lava errors under the fluid engine on our test copy of production, we (well, Stan Yoder here) came across this surprising behavior of the _Case_ statement under Fluid vs. the way it works in Liquid.

Given this code:

```
{% assign someVar = "B" %}
{% case someVar %}
{% when 'A' or 'B' %}
    First case statement - someVar = {{ someVar }} <br>
{% when 'A' %}
    Second case statement - someVar = {{ someVar }} <br>
{% when 'B' %}
    Third case statement - someVar = {{ someVar }} <br>
{% endcase %}
```

we get very different results depending on the Lava engine in use:

Here's what Liquid returns... both first and third cases, since B applies to both:
![image](https://user-images.githubusercontent.com/3903408/203645067-588e2f00-3948-4554-a0e8-059c47146beb.png)

and here's what Fluid returns.. only the first case, as if there's a break when it hits the first match?
![image](https://user-images.githubusercontent.com/3903408/203645108-3886b23f-7f55-4429-808b-16263fd2c1c9.png)

**Expected behavior:**

We're not sure. We _are_ using such syntax under Liquid and it's worked fine for years, but we're actually not sure if this is "forbidden" syntax and we just got away with it, or if it's a legitimate pattern that Fluid _should_ be handling correctly.

**Actual behavior:**

Very different results between the two Lava engines on certain Case statement syntax.

### Versions

* **Rock Version:** 13.7

**Comment by nairdo** [comment]
After some discussion with the Fluid library team we've all concluded that this is a difference with the official Shopify Liquid so, we're going to pull in the library fix (into Rock) once it's been packaged.
