### ISSUE TITLE
Obsidian Registration Entry Doesn't Update Page Title

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5234]
### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words ####

![](https://user-images.githubusercontent.com/66277785/204140776-09202c21-0faf-4329-912b-13b5679747cc.png)

### Description ###

The original Registration Entry block updates the page's title to reflect the name of the instance. This has been a huge feature for us, since it helps guide the person filling out the form to know what they're registering for. The newer Obsidian Registration Entry block doesn't update the page's title. 

### Steps to Reproduce ###

1. Go to the demo site and navigate to Tools > Event Registration
1. Configure an Event Registration Instance to be active, and ensure it has a slug under Linkages
  * I used the Summer Camp template, and gave it a slug of _camp_. The way the instance is configured has no impact on this particular bug, it just needs to be active. 
1. Navigate to https://rock.rocksolidchurchdemo.com/registration/{slug}, where {slug} is whatever the slug was configured to be in step 2
1. By default, the page only contains the original registration entry block. Notice how the original block updates the page's title to reflect the name of the registration instance.
1. Open the zones configuration on the Registration Entry page, and add the Obsidian registration entry block and delete the original registration entry block
![](https://user-images.githubusercontent.com/66277785/204144293-fc326949-f47a-4993-94c1-8fdd2d220dcb.png)
1. Reload the page to https://rock.rocksolidchurchdemo.com/registration/{slug}
1. Notice how the page title just says "Registration" instead of the name of the instance.

**Expected behavior:**

I expect the Obsidian registration entry block to change the page's title, since that was the behavior of the original block.

**Actual behavior:**

When using the Obsidian registration entry block, the page title doesn't change.

### Versions ###

* **Rock Version:** [Rock McKinley 14.0 (1.14.0.18)]
* **Client Culture Setting:** [en-US]

**Comment by dataCollegechurch** [comment]
@leahjennings - here is a couple temporary workarounds: https://chat.rockrms.com/channel/events-registrations?msg=qpYBEcitKx8BqBzrm

**Comment by KelleyLangkamp** [comment]
Does anyone know if/when this is going to be fixed? I've talked to a couple churches that are struggling with people not knowing what they are registering for, especially if they were on a page with multiple registration links. i.e. student registration and leader registration.

**Comment by nlBayside** [comment]
I'd also like to know when, or if, this issue will be resolved! Yes, there are workarounds but it'd be great to keep the old behavior of the webforms block. 

Losing previous behavior in a refresh of an old block sounds like a bug in my opinion. Keeping consistent behavior doesn't sound like much of an enhancement to me.

**Comment by dataCollegechurch** [comment]
From what I have seen GitHub issues submitted are typically labeled bug when a feature doesn't work as designed. Only the designer of the new block or the documentation can tell us whether or not the block is working as designed and Spark Team is best situated to speak into that. New replacement blocks rarely incorporate all the previous behavior from previous block so missing previous (however frustrating) doesn't necessarily mean this is a bug. I think your best course of action would be to submit this issue as an idea on the ideas board (https://community.rockrms.com/Ideas) and to rally like-minded churches experiencing the issue to vote for it.

**Comment by amiller60** [comment]
Hello. This bug fix seems to have missed registrations with a future date, which still show "Registration" instead of the name of the instance.

**Comment by chead4** [comment]
@amiller60 The issue with regisrations with a future date not displaying the name of the registration has been fixed via [commit](https://github.com/SparkDevNetwork/Rock/commit/0bd8ea04b4d22aaf59a37a7896c2e5d0073261fd) in v16.6

**Comment by amiller60** [comment]
@chead4 this is great news! Thank you!

**Comment by markewampler** [comment]
So this might be back?  We are on v17 about to be on v17.1 and just noticed our /Registration page doesn't have the Registration Instance Title on it anymore again.
