### ISSUE TITLE
Default Campus on Family Preregistration

### ISSUE THREAD

**Issue by Koriganp** [SparkDevNetwork/Rock#5235]
### Prerequisites
 

 
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
 
#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.
 
### Description
 
On the family pre-registration page, if the Default Campus is blank on the block settings, the first campus listed is auto selected on the page. 
 
### Steps to Reproduce
 
1. Go to /familypregistration page
2. Click on Block settings for the Family Pre-Registration block, make the default campus blank, click save.
3. Now the Family PreRegistration block will show the first campus in the list as auto-selected.
 
**Expected behavior:**
 
If there is no Default Campus selected, the Campus field should be blank on the page.
 
**Actual behavior:**
 
The campus field is not blank on the Family Pre-Registration page when the Default Campus in the block settings is blank.
 
### Versions
 
* **Rock Version:** 13.7 & 14.0
* **Client Culture Setting:** en-US
![FamilyRegistrationCampusDefault1](https://user-images.githubusercontent.com/7429351/204556919-edcaa862-767b-403f-baeb-9813ba0805cb.png)
![FamilyRegistrationCampusDefault2](https://user-images.githubusercontent.com/7429351/204556966-a043bec5-bebb-4f20-9cea-c7094670af54.png)

**Comment by ethan-sparkdevnetwork** [comment]
Thanks @Koriganp  Fixed by Kwame in commit 38050025.
