### ISSUE TITLE
Trend Percentages in v14 Contributions tab overlap Dollar Amounts in Firefox (mac or pc)

### ISSUE THREAD

**Issue by BrentPirolli** [SparkDevNetwork/Rock#5240]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

![1](https://user-images.githubusercontent.com/38138194/205702186-6d2fdd1e-f3b5-4ade-a3d1-0fde9175cf89.png) 

![2](https://user-images.githubusercontent.com/38138194/205702210-7ec80da9-49c8-4bfa-9d44-1a09968d867e.png)

![3](https://user-images.githubusercontent.com/38138194/205702220-ede6c5de-8a1b-4033-abf9-9ff1dfb02465.png)

### Description

On v14's new Contributions page, the trend percentage overlaps the "Last 90 Days" dollar amount if you are using Firefox (tested on latest 107.1 on Mac and PC) but it is fine on Chromium based browsers like Chrome and Edge, and it is fine on Webkit based Safari. You also see the overlap issue on "Typical Gift" as well... maybe others that I haven't spotted yet too.

### Steps to Reproduce

1. Using Firefox, go to Ted Decker's profile on the demo site and see his contributions tab... or just click here: https://rock.rocksolidchurchdemo.com/person/4/contributions 

2. If he doesn't have any in the last 90 days, click "add one time gift" on the right and enter a fake one then go back to his profile.

**Expected behavior:**

It should look like this:
![5](https://user-images.githubusercontent.com/38138194/205703256-d0a8f687-e0ae-400c-88c6-d3122626e2b5.png)

**Actual behavior:**
![6](https://user-images.githubusercontent.com/38138194/205703368-142c9436-892c-46f6-a532-42aa27bbee61.png)

### Versions

* **Rock Version:**  Rock McKinley 14.0 (1.14.0.18)
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment]
This is also an issue in 13.7 (and likely back to 13.0 when the new giving layout was introduced)

13.7:
![image](https://user-images.githubusercontent.com/3903408/205714723-ba6af980-d103-4cfc-a509-bf2a38cde5a3.png)
