### ISSUE TITLE
Some Lava Blocks parameters have problems with Lava

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#5242]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
Some "Lava Blocks" (or Lava commands), specifically `{% workflowactivate %}` `{% webrequest %}`, Entity Commands (and potentially others) cannot accept Lava input _if_ the lava input resolves to a value that contains an apostrophe, like the name `O'Neil`.

This issue plays out in an example provided in the WorkflowActivate 
```
{% workflowactivate workflowtype:'21' workflowname:'{{ CurrentPerson.FullName }} Workflow' %}
  Activated new workflow with the id of #{{ Workflow.Id }} and name of {{ Workflow.Name }}.
{% endworkflowactivate %}
```
Let's say the Current Person's name is `O'Neil`

The parameters are being parsed [after the merge fields are being processed](https://github.com/SparkDevNetwork/Rock/blob/59696637c111f2936ca09377e6d0ae29772d0206/Rock/Lava/Blocks/WorkflowActivateBlock.cs#L321).  That means if your lava text results to a value with an apostrophe in it, then the parameters get read incorrectly.

The listed example code with a Current Person's FullName of `Jenna O'Neil` would _hope_ to name the Workflow `Jenna O'Neil Workflow`, but in reality, the Workflow gets named `Jenna O`.

#### Simplified Example Code
```
{% assign name = "O'Neil" %}
{% workflowactivate workflowtype:'36' workflowname:'{{ name }}' %}{% endworkflowactivate %}
```

### Steps to Reproduce

1. Create a dummy WorkflowType
2. Use `{% workflowactivate %}` to start a Workflow of that type, passing any parameter some Lava which resolves to a value that contains an apostrophe.
3. Check on the Workflow that was launched, and check its name, or whichever attribute you passed that value into

This issue exists with every parameter of `{% workflowactivate %}`, and parameters for other commands.

**Expected behavior:**

Each parameter's Lava should evaluate within the `'single-quoted' strings` so `workflowname:'{{ name }}'` should be `O'Neil` instead of `O`.  This behavior should also apply to other parameters and Attributes, and should also address similar issues on webrequest and other Lava Commands

**Actual behavior:**

Lava commands are not consistently processing these parameters, and it's challenging to know which one behaves.

### Versions

* **Rock Version:** 13.7 & present in Develop Branch
* **Client Culture Setting:** en-US

**Comment by nlBayside** [comment]
Hello,
Should this issue be updated with a different label? I was checking on a Rock instance running v15 and it appears this bug still happens. The last commit made looks like it should be labelled as "Fixed in v16.0"

**Comment by NuclearTacos** [comment]
I confirmed what you're saying with testing on the Demo site, and digging into the 3 commits referenced here, it was fixed, reverted, and fixed again.

They compile the patch notes from the Commit messages, and it seems like the revert was not read in that process, so the fix showed in the patch notes despite being reverted in v15.

And yes, the tag on this issue should be updated to reflect that as well 😬

**Comment by MrUpsideDown** [comment]
@nlBayside @NuclearTacos - label updated, apologies for the confusion!
