### ISSUE TITLE
Obsidian Registration: "Fee only" registrations fail with error "Billing Information Missing" (may be NMI Gateway Only

### ISSUE THREAD

**Issue by jeremyhoff** [SparkDevNetwork/Rock#5245]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

![Screen Shot 2022-12-08 at 1 42 29 PM](https://user-images.githubusercontent.com/3937813/206576936-8d29f762-9c8d-4b46-ac09-045e384eaf73.png)

### Description

If an event registration is has no Cost, but has Fees, the Obsidian Event Reg will skip the billing page and will not charge the credit card. This results in the error seen in the above screenshot.

### Steps to Reproduce

1. Set up new Event Registration with no cost; add a required fee;
2. Test event registration... all wizard steps, including the signature document, are presented *except* the step asking for CC info
3. Cannot finish due to being unable to charge the balance to a Debit/CC.

A workaround is to set a cost, and lower the fee to offset that cost.

**Expected behavior:**

If there is any balance, Obsidian presents the CC entry step and pays the bill.

**Actual behavior:**

The CC entry step is skipped, and the registration cannot be completed.

### Versions

* **Rock Version:** 14.0 (1.14.0.18)
* **Client Culture Setting:** en-US

**Comment by leahjennings** [comment]
Can confirm we are also experiencing this issue on v14.0. Using the pre-existing Registration Entry block works without issue.

**Comment by nairdo** [comment]
We're verifying that this might have been something we fixed recently (72bac46, b606d12) in v14.1 when it was reported internally a few months ago.

**Comment by ethan-sparkdevnetwork** [comment]
Confirmed this is now working in v14.1.
