### ISSUE TITLE
Can no longer "Save" progress on a workflow form without entering all required fields.

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#5248]
### Description

[This change](https://github.com/SparkDevNetwork/Rock/commit/70a484a9408cb0c9bfe93c430e572e1dcb7c086a) to fix [this issue ](https://github.com/SparkDevNetwork/Rock/issues/4983 ) has broken the ability to save progress on a workflow form without having to complete all the required fields. We have created many workflows for clients with a lot of required fields on a form and they've wanted the user to have the option of saving their progress on that form before they have actually completed all the required fields. To accomplish this, we've added a "Save" and a "Submit" button to these forms. The "Save" button was using the Cancel type button and then re-activating same activity with the form. This would allow user to save their progress because the Cancel type button would not validate all the "required" fields, but WOULD save the values they entered. This allowed user time to complete long forms without having to complete it in one sitting. Because of this change, the "Save" buttons on these workflows no longer save any values.

It also hasn't just been long forms. There are cases where a user may need to keep returning to a form to fill out additional information. They don't have all the required information when they first start the form, but are gathering/entering information over time, and then once they have all the information and are ready to submit, at that point all of the fields are required. An example of this, is a counseling meeting. Pastor may enter preliminary information before meeting and want to save that information. During the meeting they wish to update some of the fields they previously saved and add additional required notes before finally submitting the form.

### Versions

* **Rock Version:** v13.4+
* **Client Culture Setting:** en-US

**Comment by azturner** [comment]
Another scenario is when workflows are broken up into many form activities so that there is not too many fields on one "page". We would add "Back" and "Next" buttons where the "Back" would use the Cancel type button so that any information user filled out on current form would be saved when they clicked "Back", but they could still navigate to previous page without filling out all the required fields on current page.

**Comment by azturner** [comment]
Mostly for our reference, but this query finds all workflow forms using the "Cancel" type button where the text of the button is not "Cancel". Prior to v13.4 form values would of been saved when these buttons are clicked, after v13.4 form values are not saved when button is clicked.

```
SELECT  
      W.[Id]
    , W.[Name] AS [Workflow]
    , T.[Name] AS [Activity]
    , A.[Name] AS [Action]
    , SS3.[Buttons] AS [Button (Type)]
FROM [WorkflowActionForm] F
INNER JOIN [WorkflowActionType] A ON A.[WorkflowFormId] = F.[Id]
INNER JOIN [WorkflowActivityType]  T ON T.[Id] = A.[ActivityTypeId]
INNER JOIN [WorkflowType] W ON W.[Id] = T.[WorkflowTypeId]
OUTER APPLY (
    SELECT STRING_AGG([Buttons],'; ') AS [Buttons]
    FROM string_split(F.[Actions],'|') SS
    OUTER APPLY (
        SELECT 
            STRING_AGG(SS1.[Value],':') AS [Buttons]
        FROM (
            SELECT TOP 1 BV.[Value] 
            FROM STRING_SPLIT( SS.[Value],'^') BV
            UNION ALL
            SELECT TOP 1 '(' + DV.[Value] + ')'
            FROM STRING_SPLIT( SS.[Value],'^') BV
            INNER JOIN [DefinedValue] DV ON DV.[Guid] = TRY_CAST(BV.[Value] AS [uniqueidentifier])
        ) SS1
    ) SS2
    WHERE ISNULL(SS.[Value],'') <> ''
    AND SS2.[Buttons] <> 'Cancel:(Cancel)'
) SS3
WHERE F.[Actions] LIKE '%5683e775-b9f3-408c-80ac-94de0e51cf3a%'
AND SS3.[Buttons] LIKE '%(Cancel)%'
ORDER BY W.[Order], W.[Name], T.[Order], A.[Order]
```

**Comment by bscottdavis** [comment]
I can confirm that this update effects a couple dozen of our workflows that use the "Cancel" style `onclick="return true;"` code to save the values in the current form without requiring the required fields to be completed. We use this often to allow users to "Save" on a long form.

Allowing the `onclick="return true;"` code to avoid required field validation would be very helpful. 

Other Solutions Might Be:
 - Add a boolean Attribute to the button types that specifically denote whether they respect the required fields.
 - Add a boolean option to the button in the workflow configuration alongside Command Label, Button Type, Activate Activity, and Response Text to denote whether the button respects required fields.

**Comment by ethan-sparkdevnetwork** [comment]
For now we have restored the previous behavior of the cancel button that has an activity attached to it. In a future release this functionality will be moved to a different button type.

**Comment by JimMichael** [comment]
@ethan-sparkdevnetwork Will the reversion cause this issue to happen again? https://github.com/SparkDevNetwork/Rock/issues/4983

**Comment by ethan-sparkdevnetwork** [comment]
@JimMichael No, the fix for the empty person records will remain in place. This change only affects the workflow attributes.

**Comment by azturner** [comment]
@ethan-sparkdevnetwork, Any idea what version(s) your change to restore this functionality will be released in (looks like it's currently just in the develop branch)?
