### ISSUE TITLE
Model Map descriptions for Schedule.IsCheckInActive and Schedule.IsScheduleActive incorrect

### ISSUE THREAD

**Issue by stevekleinliquid** [SparkDevNetwork/Rock#5251]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.
<img width="783" alt="Screen Shot 2022-12-16 at 9 51 28 PM" src="https://user-images.githubusercontent.com/114983828/208220577-78ec5064-f7f8-428b-beb2-497308869f8c.png">
<img width="774" alt="Screen Shot 2022-12-16 at 9 51 44 PM" src="https://user-images.githubusercontent.com/114983828/208220581-026e0af6-ef81-4b06-997a-dd2565a95767.png">

### Description

The descriptions in the Model Map for the Schedule model for properties `IsScheduleActive` and `IsCheckinActive` are incorrect (see images above). I'm not sure what they should be but maybe they are correct in a previous version. 

### Steps to Reproduce

Documentation incorrect.

**Expected behavior:**

Updated documentation.

**Actual behavior:**

Documentation incorrect.

### Versions

* **Rock Version:** [13.6]
* **Client Culture Setting:** [en-US]

**Comment by jonedmiston** [comment]
This is working as expected. It may have been fixed or there may be a CSS issue in your theme (?) as it appears the missing words above happen to be in code tags.

![image](https://github.com/SparkDevNetwork/Rock/assets/548178/1a6eb2ca-3b8b-4ae7-85de-962d7444fc36)
