### ISSUE TITLE
Using an entity commands 'select' parameter to return attributes triggers a LegacyLavaSyntaxDetectedException

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5252]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/66277785/208264885-9874fb7b-ddd3-44af-8d0e-43f7eb35d5af.png">

### Description

I don't know if this is by design, but it feels wrong or at least confusing to me so I am submitting the bug to either confirm it as a bug or gain clarity on how to avoid the exception. When using the select feature of the entity command introduced with v13 and Fluid, if you are selecting attributes from the entity and then reference them with dot notation, Rock thinks you are using legacy lava and throws an exception. Overall this isn't awful, except I've used this in a couple of different forms, so when they are loaded our system gets hit with a lot more seemingly unnecessary exceptions.

### Steps to Reproduce

1. Go to the demo site's home page
2. Add an HTML block to the _Sidebar 1_ zone
3. Edit the block's settings to enable the Rock Entity command
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/66277785/208265340-e33041a7-87ca-4e45-99b2-b4c143b0f330.png">

4. Edit the block's HTML and add the following code. _Note: I understand this code alone has no real effect and makes no sense, however its purpose is to show the bug. I can provide real-world code examples where this occurs if that proves helpful._
```
{% definedvalue where:'DefinedTypeId == 5' select:'new (IsFormal AS IsFormal)' %}
    {% for val in definedvalueItems %}
        {{ val.IsFormal }}<br>
    {% endfor %}
{% enddefinedvalue %}
```

5. Load the home page and make sure you can see the output of the code:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/66277785/208265426-7cff001e-d890-4fcf-b31c-7a4e34e19c90.png">

6. Navigate to Admin Tools > System Settings, then Exception List
7. Notice the recent exception for legacy lava
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/66277785/208265472-21e39545-8df6-41f7-b30c-88317ec4196a.png">

**Expected behavior:**

I would expect to be able to use the select entity parameter with attributes and reference those attributes using dot notation without generating a legacy lava exception, since this isn't legacy lava.

**Actual behavior:**

Anytime you reference an attribute returned using the select parameter, a legacy lava exception is generated.

### Versions

* **Rock Version:** [Rock McKinley 14.0 (1.14.0.18)]
* **Client Culture Setting:** [en-US]

**Comment by jr-peck** [comment]
The code runs and logs an exception because Demo is running with the Lava Support Level at "Legacy with Warning".
If the support level is "No Legacy" the lava wouldn't return results and I don't think it will log an exception.

**Comment by nairdo** [comment]
> If the support level is "No Legacy" the lava wouldn't return results and I don't think it will log an exception.
Yes, that is correct.  @leahjennings  Can you confirm that your system's Lava Support Level is set to "Legacy with Warning" -- and then if you change it to "No Legacy" (and clear the cache) the problem goes away?

**Comment by nairdo** [comment]
We talked with Leah via chat.

We are going to remove support for "Legacy with Warning" option starting in Rock v16.  For now, as long as setting the **Lava Support Level** Global Setting value back to `No Legacy` resolves this issue, we will consider this item resolved.

![image](https://user-images.githubusercontent.com/383807/216162292-4eb47bc4-3fed-451e-bcd3-0839d6cde80e.png)

**Comment by nairdo** [comment]
Before I close this issue, I wanted to share with future viewers of this issue what the Lava would look like without using the Legacy "." syntax for attribute value retrieval.

```Liquid
{% definedvalue where:'DefinedTypeId == 5' %}
    {% for val in definedvalueItems %}
        {{ val | Attribute:'IsFormal ' }}<br>
    {% endfor %}
{% enddefinedvalue %}
```

_Note: The `[new ](select:'new (IsFormal AS IsFormal)')` was also removed._

Also keep in mind that starting with Rock v15, attributes are automatically loaded (🎉) and you can use the new [prefetchattributes](https://community.rockrms.com/lava/commands/entity-commands#prefetchattributes) flag to limit if you only want certain ones back (or disable that feature altogether using the [disableattributeprefetch](https://community.rockrms.com/lava/commands/entity-commands#disableattributeprefetch) ...but why would you want to do that?? ;)
