### ISSUE TITLE
Domain Login Sharing disables Impersonation

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#5253]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
Reported on behalf of North Point Ministries.

Enabling Domain Login Sharing disables Impersonation.

### Steps to Reproduce

1. Go to rocksolidchurchdemo.com and login as Alisha Admin.
2. Go to Brian Jones profile page.
3. Change block settings to allow impersonation and for impersonation to go to the MyAccount page.
4. Verify impersonation works.
5. Go to General Settings -> Defined Types
6. Set Domain Login Sharing to have a value of rocksolidchurchdemo.com
7. Go back to Brian Jones and try to impersonate him.
8. You land on the My Account page but as Alisha Admin not Brian Jones.

**Expected behavior:**

I would expect impersonation to continue to work even if Domain Login Sharing is used.

**Actual behavior:**

All Impersonation ceases to work when a value is entered for Domain Login Sharing.

### Versions

* **Rock Version:** 13.7 and 14.0
* **Client Culture Setting:** Azure and rocksolidchurchdemo.com

**Comment by mkinyon** [comment]
I have seen this same issue at River Valley Church.  Currently on v13.7.

**Comment by chead4** [comment]
@bobrufenacht & @mkinyon As we are reviewing all reported issues, I came across this oldie but goodie.  I have attempted to recreate the impersonation issue on RockSolidChurchDemo site v16.2 but was not successful.  If you manage to recreate on the demo site, sharing a video would be greatly appreciated.

**Comment by chead4** [comment]
@mkinyon & @bobrufenacht We will be closing this issue at this time; but, if you are able to recreate on the demo site we can reopen the issue.  Please keep in mind that if you are able to recreate, we would greatly appreciate if you could share a video of the issue.

**Comment by bobrufenacht** [comment]
We testing this on 15.2 and did not see the issue.  It does seem like it is fixed.

Thanks,
Bob

From: Colleen Head ***@***.***>
Date: Monday, February 5, 2024 at 4:48 PM
To: SparkDevNetwork/Rock ***@***.***>
Cc: Bob Rufenacht ***@***.***>, Mention ***@***.***>
Subject: Re: [SparkDevNetwork/Rock] Domain Login Sharing disables Impersonation (Issue #5253)

@mkinyon<https://github.com/mkinyon> & @bobrufenacht<https://github.com/bobrufenacht> We will be closing this issue at this time; but, if you are able to recreate on the demo site we can reopen the issue. Please keep in mind that if you are able to recreate, we would greatly appreciate if you could share a video of the issue.
