### ISSUE TITLE
User entry forms not honoring user's selections for Multi-select attributes with default value set.

### ISSUE THREAD

**Issue by stanalyst** [SparkDevNetwork/Rock#5254]
### Description

There appears to be a bug in how multi-select attributes with default values are handled by user forms in the system - at least there is for workflows & registrations. If a multi-select has any values selected by default - and the user unselects all values for this attribute - the form/workflow/registration are not honoring this user entry - but instead reverting to the original default values upon submission. I have confirmed this occurs with both workflows attributes and registration attributes.

Also it appears this is an issue with single-select attributes that have a default value - and the user select none on the user form - the value after submission reverts to the original default option.

### Steps to Reproduce

1. Add a Multi-Select attribute to a Workflow - with any options defaulted to selected.
2. Present attribute to user via Form (View & Edit enabled - not required)
3. User unchecks all options and submits
4. Confirm value of attribute

I've attached an export of a test workflow from the demo site below.

**Expected behavior:**

Would expect the value of the attribute to be empty/blank/null - i.e. what the user entered in the form.

**Actual behavior:**

Attribute's value is the original default options that were set for the attribute.

![Workflow Issue](https://user-images.githubusercontent.com/112125627/208762990-b29b54d7-e03f-45c5-a0a3-a654503148c4.jpg)

### Versions

* **Rock Version:** 1.13.7.1 (also confirmed issue on demo site 1.14.0.18)

[Testing Attribute Issue_202212201345.json.zip](https://github.com/SparkDevNetwork/Rock/files/10272567/Testing.Attribute.Issue_202212201345.json.zip)

**Comment by ethan-sparkdevnetwork** [comment]
Hello @stanalyst. Thank you for this detailed issue, it really helped speed up my review.

This is the standard and intended behavior for these controls. If a default value is specified, then it will be used if no value is selected by the user. Think of it as a default value and not as an initial value.

Initial value does seem like it could be a useful feature. You can submit it using [Rock Community Ideas](https://community.rockrms.com/Ideas).
