### ISSUE TITLE
Pledge Analytics

### ISSUE THREAD

**Issue by carriewhite** [SparkDevNetwork/Rock#5260]
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

Verified on demo site.

### Description

Pledge analytics is not respecting the filter in regards to giving.  

### Steps to Reproduce

1. Go to Finance - Pledge analytics
2. Filter on General Fund and Current Year
3. Select Update

**Expected behavior:**

Both the pledge and the giving will be filtered based on the given parameters.

**Actual behavior:**
<img width="1809" alt="Screenshot 2023-01-04 at 11 25 20 PM" src="https://user-images.githubusercontent.com/70244373/210716951-702e1d42-ca12-4eee-a1a3-44d7ea88b05c.png">
<img width="1755" alt="Screenshot 2023-01-04 at 11 25 35 PM" src="https://user-images.githubusercontent.com/70244373/210716956-8bd5fd26-e95f-4396-b81b-171312085965.png">

Pledges respect the filter but giving does not.

### Versions

* **Rock Version:** Rock McKinley 14.0 (1.14.0.18)
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
@carriewhite This is working as designed. The filter applies to the pledge block. If you click on the pledge Rock navigates to the Person Page Contribution tab for that person. This displays all of the contributions for the person but can be filtered separately.

You can suggest a functionality change here: https://community.rockrms.com/Ideas
