### ISSUE TITLE
Registrations Fails with Fee Cost

### ISSUE THREAD

**Issue by carriewhite** [SparkDevNetwork/Rock#5261]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

Verified on demo site

### Description
Registration fails if guest selects a fee with a cost.

### Steps to Reproduce

1. Create registration template with fees that have a cost.
<img width="1290" alt="Screenshot 2023-01-05 at 7 26 12 PM" src="https://user-images.githubusercontent.com/70244373/210917321-689de59e-e385-4a17-897b-48b818acf5e3.png">
2. Register for an instance and select a fee that has a cost.

**Expected behavior:**

Successful registration

**Actual behavior:**

Exception and registration fails.
<img width="2552" alt="Screenshot 2023-01-05 at 7 20 19 PM" src="https://user-images.githubusercontent.com/70244373/210918134-3bb1aa6f-8e33-4a1a-98e4-35f3faaf1c03.png">

<img width="2560" alt="Screenshot 2023-01-05 at 7 16 50 PM" src="https://user-images.githubusercontent.com/70244373/210918054-b27db161-d56b-4c8f-bd4c-69a5078309d1.png">

### Versions

* **Rock Version:**  Rock McKinley 14.0 (1.14.0.18)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1203705094489798">rbFregistrarFamilyOptions.mov</a>

**Comment by ethan-sparkdevnetwork** [comment]
Hello @carriewhite I am not able to reproduce this. The error in your screenshot indicates a problem with the Family Options radio button list. I have tried a bunch of combinations to try and get the error. Can you still get the error? If so can you provide more details on the event registration setup?

**Comment by carriewhite** [comment]
Hi Ethan.
Thank you for looking into this!  I was able to reproduce the error on Friday on the demo site, but not since then.  Is there anything that happened to the site since then?  Any clues that would help me figure out why this is still happening on our site?

Carrie White
Director of Data Systems, Connecting Point
Tel: 
480.726.8000
Fax: 480-569-2238
www.CornerstoneAZ.com
________________________________

**Comment by ethan-sparkdevnetwork** [comment]
@carriewhite Can you add a screenshot of the Registration Details "Details" section and a video of the Registration from start to finish/error? Also did this start occurring right after the update to 14.0 or sometime later?

**Comment by carriewhite** [comment]
Hi @ethan-sparkdevnetwork We did not notice it until after 14.0.  I was able to replicate the error on our site for myself several times with different registration templates on one day but not the next, like something was repaired in my family record??? I was able to replicate the error several times on the demo site one day and not the next.  It only happens on our site for some people. At first I thought this was fee related, but now I'm unclear. 
<img width="1059" alt="Screenshot 2023-01-11 at 11 25 33 PM" src="https://user-images.githubusercontent.com/70244373/211993376-211641ff-b128-4f62-8962-bdd37ec99e31.png">
Please see DM on chat.

**Comment by carriewhite** [comment]
@ethan-sparkdevnetwork Today I was able to reproduce the error on 14.0 by using a card on file (Discover card that HAD EXPIRED). Is this the real issue?

**Comment by jsw-austin** [comment]
I've seen this before, but only for people trying to use saved payments.

**Comment by ethan-sparkdevnetwork** [comment]
Expired cards will no longer be shown in the list.

**Comment by ethan-sparkdevnetwork** [comment]
The initial error was fixed in 14.1 commit: cd758ee4. The message displayed is what is returned by the gateway, which may be purposely vague.
