### ISSUE TITLE
v14 Lava Badges Don't Support HTML In Tooltips

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5263]
### Description

Prior to v14, the tool tips in a Lava badge rendered HTML just fine, allowing you to emphasize words, make the tip multi-line, etc. In v14 the HTML is just rendered as text.

### Steps to Reproduce

1. Create a Lava badge with a tooltip string that contains HTML. 
 A simple example would be:
```
<div class="badge" style="color: #9900cc" data-toggle="tooltip" data-original-title="this is a tooltip with <strong>HTML</strong>">
    <i class="badge-icon fa fa-key"></i>
</div>
```

Which in v13 and prior renders as:
![image](https://user-images.githubusercontent.com/3903408/211106312-210fa570-4d75-4b03-bd76-a5ff40d2e4a8.png)

but on v14 the equivalent badge lava of 
```
<div class="rockbadge rockbadge-icon rockbadge-icon-nobg" style="color: #9900cc" data-toggle="tooltip" data-original-title="this is a tooltip with <strong>HTML</strong>">
    <i class="badge-icon fa fa-key"></i>
</div>
```

renders as:
![image](https://user-images.githubusercontent.com/3903408/211106628-f06f9953-12f5-42ab-a845-7772578adbbb.png)

**Expected behavior:**

HTML would be rendered in Lava Badge tool tips

**Actual behavior:**

We're not sure if this was an intentional change in v14 badges, or an oversight, but it does reduce the flexibility of such badges. Here's another example where we could create a multi-line tooltip in v13, but cannot do so in v14:

v13
![image](https://user-images.githubusercontent.com/3903408/211107055-5212b6f1-114d-4f04-bd11-926f4f0e2431.png)

v14
![image](https://user-images.githubusercontent.com/3903408/211107100-d347e9ef-19a8-4bef-9820-87378eba7bca.png)

### Versions

***Rock Version:** 14.0+

**Comment by mkinyon** [comment]
River Valley Church is experiencing the same challenges.

**Comment by JimMichael** [comment]
I forgot to mention that _Lava_ itself works just fine in tool tips.. that badge above is doing a `{% for` loop with its tooltip ;-) It's only plain-old HTML that doesn't work.

**Comment by MichaelAllen** [comment]
If you replace the `data-original-title=` with `data-html="true" data-title=` then it correctly displays the HTML. 

Maybe that note needs to be added to the [badges documentation page](https://community.rockrms.com/styling/components/badges)? There isn't currently an example with a tooltip, but that would probably be helpful to have.

**Comment by JimMichael** [comment]
Thanks @MichaelAllen ! I agree about the documentation page for badge styling, and think every option these styles provide should be mentioned there if not demonstrated.

**Comment by MichaelAllen** [comment]
If we did want to get back to the pre v14 behavior of enabling HTML in badge tooltips by default, it would be a simple change to the Obsidian badges block. You just need to pass `{ html: true }` as the second argument to the `tooltip()` function on this line:
https://github.com/SparkDevNetwork/Rock/blob/713c8e66d6c3066ba5e2d04f7664764d07c268cf/Rock.JavaScript.Obsidian.Blocks/src/Crm/PersonDetail/badges.ts#L102
(I didn't PR this fix because I'm not sure if it was changed intentionally; maybe for performance reasons.)

**Comment by cabal95** [comment]
@MichaelAllen Feel free to make a PR for that and we'll take a look. I just had a discussion on this this internally and the _intention_ was for them to behave the same in Obsidian as they did in WebForms.

**Comment by garrettjohnson** [comment]
@MichaelAllen Documentation has been updated per your suggestion. Thank you! https://community.rockrms.com/styling/components/badges#tooltips
