### ISSUE TITLE
SMS Conversations block populates "list" with communications where the initial recipient did not send a response

### ISSUE THREAD

**Issue by IzabellaDTS** [SparkDevNetwork/Rock#5264]
#### A Picture Is worth a Thousand Words

Below is an image of a specific individual present in the SMS Conversations Block's list (other people and info has been blackout to keep information as anonymous as possible) ...

![image](https://user-images.githubusercontent.com/84338278/211109288-2c664e10-75ee-4343-9045-ab38b0fb23e1.png)

Below is another image showing the Communication Response Table. The table has been filtered down to only show those responses where the **FromPersonAliasId** contains any of Elijah's Person Alias IDs. As we can see the table yields no results.

![image](https://user-images.githubusercontent.com/84338278/211109639-c19ab616-3ec7-4a00-b9bf-d2e1afcbfc89.png)

### Description

The SMS Conversations block utilizes the Communication Response table on the database to populate the list of conversations that need to be responded to. However, as we can see from the example images above, this "list" contains individuals who do not have a communication response. 

### Steps to Reproduce

This issue doesn't necessarily have an exact step-by-step way it can be reproduced. However, I will list the steps I took that caused me to discover this issue. The first, true step was that I viewed the SMS Conversation block's code to understand how the "list" was populated, and saw that it was populated via the Communication Response table in the database. After I saw this, here are the steps I took

1. Knowing what table populated the list, I was looking at Elijah's text messages and realized via the UI that Elijah never once responded to any of the text messages he received.
2. Wanting to ensure Elijah never responded, I located Elijah's profile in Rock and grabbed his person ID.
3. I then used his person Id to locate his Person Alias ID(s) via the database.
4. Once I had Elijah's Person Alias IDs, I "narrowed down" the results of the Communication Response table to only those Communication Responses where the **FromPersonAliasId** contained any of Elijah's Person Alias IDs. The result set was empty.
5. Upon seeing this, a coworker and myself conducted various tests to determine why Elijah (who had no communication responses) was present in the SMS Conversations list versus myself (who we had sent a test text to) was not present in the SMS Conversations list. We found no discernable reason for why Elijah would be preset in the list

**Expected behavior:**

The SMS Conversations block's list should only populate with SMS communications where the recipient responded to the communication.

**Actual behavior:**

The SMS Conversations block's list populates with SMS communications where the recipient responded to the communication AND communications where the recipient did not respond to the communication.

### Versions

* **Rock Version:** Rock McKinley 14.0 (1.14.0.18)
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
@IzabellaDTS V1.15.0 introduces a filter to choose the communications to view (commit ab3b7ad5). The filter are:

- Show Unread Replies
- Show All Replies
- Show All Messages

Will that accomplish what you need?

**Comment by IzabellaDTS** [comment]
@ethan-sparkdevnetwork I believe this will accomplish what is needed. Thanks!
