### ISSUE TITLE
Duplicate Records That Get Merged Cause Duplicates in Analytics Records

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#5266]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

See thread in Rocket Chat #rockstars channel. 

### Description

The same person is showing up with multiple personIDs on the AnalyticsDimPersonCurrent view. They have two records flagged as "current" on the AnalyticsDimPersonHistorical table. 

**Expected behavior:**

Each person would only have one record marked as "current" in the AnalyticsDimPersonHistorical table. 

One thought included in the channel to handle this was: 
In looking into this on Austin's system this is definitely a bug. Please add it to Github.

But... what's the solution... input needed below.

So the problem comes from duplicate records that eventually get merged. The merge does not address the Analytics records, which we can fix, but how...

One might thing we should just merge these records to the single new PersonId, but that would leave duplicates for a specified time range. So if I wanted to know a value for Ted Decker in a point of time of May 12th of 2019 I could get two records back.

I'm thinking that the solution would be to delete analytics records from the non-primary merge records. This would mean losing some historical data, but much of this data was not correct anyways. For instance the Connection Status for the duplicate would most likely something like 'Guest' when in fact Ted is probably a 'Member'.

**Actual behavior:**

Individuals that have been merged often have more than one record record marked current in the AnalyticsDimPersonHistorical table. 

### Versions

* **Rock Version:** 14
* **Client Culture Setting:** en-us

**Comment by nairdo** [comment]
> I'm thinking that the solution would be to delete analytics records from the non-primary merge records. 

We agree.  This is what we're going to do to resolve this one.

**Comment by austinspooner** [comment]
Do you have an estimated version for resolving this?

**Comment by austinspooner** [comment]
@nairdo just wanted to check in on when we might see this fixed.

**Comment by nairdo** [comment]
@austinspooner The fix is in a fix-branch and was was up for peer review last week.  It should be getting merged in this week.
