### ISSUE TITLE
[Alpha v1.14.1.1] DataView to Workflow Job Failing and Creating Exception

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5269]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
The DataView to Workflow Job is failing and creating an exception in v14.1. I also tested this in v15.0 and found the same issue.

I discovered this after installing v14.1 on my dev server and noticed all of my DataView to Workflow jobs are failing. My production server is running v13.7 where they are all working properly. 

I am not sure, but this may be related to #5270.

#### A Picture Is worth a Thousand Words
<img width="1725" alt="Screenshot 2023-01-10 at 20 27 05" src="https://user-images.githubusercontent.com/23226974/211697159-efc43fa1-bfdb-42b4-acb5-a663e57eb05b.png">

<img width="1723" alt="Screenshot 2023-01-10 at 20 30 38" src="https://user-images.githubusercontent.com/23226974/211697164-42c5417b-01d2-4cf2-aa45-7de851eb0ee6.png">

### Steps to Reproduce

1. Create a DataView to Workflow Job, using the same or similar settings to the screenshot above.
2. Save the Job, then manually run the Job.
3. See error.

**Expected behavior:**

DataView to Workflow Job run properly.

**Actual behavior:**

DataView to Workflow Job does not run.

### Versions

* **Rock Version:** [v14.1, v15.0]
* **Client Culture Setting:** [en-US]

**Comment by shivambareria** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/ae01cce9db2dfc16755d1d179381efff3b09dc8e
