### ISSUE TITLE
[Alpha v1.14.1.1] IsInDataView filter returns "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5275]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/66277785/212098260-cee80ff4-9299-4520-842e-3de11ebf87f1.png">

### Description

When utilizing the new `IsInDataView` filter, I only ever get an error: "Object reference not set to an instance of an object." I also noticed the filter name doesn't turn blue like Lava filters do. I also tested this on Rock's PreAlpha server running v15 and got the same result. That server is running DotLiquid; we are running Fluid. I also copy/pasted the code from the tutorial to ensure syntax was correct. The error/exception also occurs if you just have this line: `{% assign inDataView = CurrentPerson | IsInDataView:'938' %}`.

Stack Trace:
![image](https://user-images.githubusercontent.com/66277785/212100687-dd6e227c-fb06-4712-bc69-e56dd4838c31.png)

### Steps to Reproduce

1. Go to a server running Rock v14.1 or higher
2. In either the Lava Tester or an HTML Content block, copy/paste the following code (note: in case it mattered I ensured that the Dataview Id passed on each server actually existed and belonged to the correct entity type)
```
{% assign inDataView = CurrentPerson | IsInDataView:'938' %}

{% if inDataView %}
   That person is in the 938 data view.
{% endif %}
```
3. Run the code and notice the error

**Expected behavior:**

I would expect the `inDataView` attribute to contain a boolean flag of yes or no, depending on whether the entity exists in the data view.

**Actual behavior:**

An exception is thrown and an error is displayed.

### Versions

* **Rock Version:** [Rock McKinley 14.1 (1.14.1.1)]
* **Client Culture Setting:** [en-US]

**Comment by MrUpsideDown** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/ae01cce9db2dfc16755d1d179381efff3b09dc8e.
