### ISSUE TITLE
Alpha v1.14.1.1 Obsidian Registration Block not Validating telephone numbers

### ISSUE THREAD

**Issue by KarenRossi84** [SparkDevNetwork/Rock#5276]
### Description

Obsidian registration block is not validating telephone numbers.

#### A Picture Is worth a Thousand Words
Regular registration Block error message
![Screenshot (497)](https://user-images.githubusercontent.com/104036471/212197224-5de8ff3c-1bf4-4f08-b410-04fade33e2d8.png)

Obsidian Registration Block with the same info: 
No error and allows you to move onto the next form. 
![Screenshot (503)](https://user-images.githubusercontent.com/104036471/212198128-f192189c-168a-4ae1-9cb6-16a011521f58.png)

### Steps to Reproduce

1. Go to a registration template.
2. Add a phone number person field to one of the forms.
4. Using the Obsidian registration block fill out the registration with a telephone number that is only a few digits long.
5. The form will let you proceed.

**Expected behavior:**

The Error message that populates on the regular event registration block "The phone number '3453' is not a valid phone number" should populate and the form should stop you from proceeding further until fixed. 

**Actual behavior:**

The form does not validate the telephone number and lets you continue. 

### Versions

* **Rock Version:** [Alpha v1.14.1.1]
* **Client Culture Setting:** [en-US]

**Comment by ethan-sparkdevnetwork** [comment]
This Obsidian feature is being added in v15.0.

**Comment by joezimjs** [comment]
Fixed in 7f97f3b04711fbdc8e78db35d4dfe68f1653b585
