### ISSUE TITLE
Adding a Person to a Family in Rapid Attendance Entry Causes a Timeout

### ISSUE THREAD

**Issue by trydyingtolive** [SparkDevNetwork/Rock#5277]
### Prerequisites ###

* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description ###

We had a church report that whenever they add a new person to a family with the Rapid Attendance Entry block, they get a database timeout[v13.6]. We tested this on our demo site and confirmed the issue[v14.0]. However it does not timeout on the Rock demo site [v14], though it is very slow. Additionally, investigating it on a local instance [v13.3] proved the same issue and another instance [v14.0] takes a significant time to complete. 

I was able to track down the issue to this line: https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/CheckIn/RapidAttendanceEntry.ascx.cs#L1532

The creation of a new person is wrapped in a transaction, but save attribute values does not use the same db context. Technically the database shouldn't need to complete the transaction before creating the attribute values, but for some reason it slows down things significantly to the point where some larger systems timeout.

I did some further digging and found that passing the RockContext to SaveAttributeValues --making the attribute values save part of the transaction fixes the timeout and improves performance in all cases.

`person.SaveAttributeValues( rockContext );`

This also has the added benefit that the attribute values should be updated in the transaction and if something goes wrong it should roll back with everything else.

### Versions ###

* **Rock Version:** 1.13.x- 1.14.x
* **Client Culture Setting:** en-US

**Comment by adamhann** [comment]
I can confirm we have this issue as well. When adding a member to an existing family the block times out for us.

**Comment by jonedmiston** [comment]
@trydyingtolive thanks for tracking that down.
