### ISSUE TITLE
[Alpha 14.1] Group Scheduler throws exception when selecting data view as source

### ISSUE THREAD

**Issue by jennifertroeger** [SparkDevNetwork/Rock#5279]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
<img width="1427" alt="Screen Shot 2023-01-13 at 2 03 04 PM" src="https://user-images.githubusercontent.com/36419045/212398811-f8e712a5-281e-4611-9711-40b810a6328a.png">
<img width="1423" alt="Screen Shot 2023-01-13 at 2 12 41 PM" src="https://user-images.githubusercontent.com/36419045/212399999-d7ffc212-f1a5-4056-a92f-eceeb2249dfc.png">

### Description

While Alpha testing 14.1 the Group Scheduler throws and exception at the top of the page when you select a data view as the source. The problem was replicated on rocksolidchurchdemo.com (source of screenshot above).

### Steps to Reproduce

1. Go to a group that allows group scheduling
2. Add a location schedule to the group
3. Click the Group Scheduler button from the Group Details block
4. Change the data source from "Group Members - All" to "Data View"
5. The page re-loads with an exception error at the top, and does not display any people from the data view

**Expected behavior:**

The expected behavior is that the box that displays people to be scheduled would be populated with people in the selected data view.

**Actual behavior:**

What actually happens is that an exception is thrown and the box that should be populated with people remains empty.

### Versions

* **Rock Version:** Rock McKinley 14.1 (1.14.1.1)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@jennifertroeger  Thanks for also finding that!  I also uncovered that on Wednesday and the fix (via https://github.com/SparkDevNetwork/Rock/commit/43d5e62cbc0ad939fcd148a62ee0efa6ebf72c2e) will be in the v14.1 beta (or v14.1 alpha 2 if necessary).
