### ISSUE TITLE
Transaction Detail Navigation within a batch disappears after editing a Transaction

### ISSUE THREAD

**Issue by kenmulford** [SparkDevNetwork/Rock#5286]
### Prerequisites ###

* [ X ] Put an X between the brackets on this line if you have done all of the following:
  * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description ###

When editing an open batch, clicking on a Transaction provides really handy navigation buttons to quickly move through all transactions in a batch. However, when editing a transaction and saving (even if no data was changed), the view state removes all buttons in that navigation area except the "Refund" button.

![image](https://user-images.githubusercontent.com/1336749/213292813-b8b63518-f970-4591-bc12-acd0a5e6619f.png)

![image](https://user-images.githubusercontent.com/1336749/213292908-d525ed6a-e5ba-418f-b613-d8acc7edcfc2.png)

### Steps to Reproduce ###

1. Go to 'Finance > Batches' and select any open batch. If you're in the demo site, choose any closed batch, edit it, and set it to open first. 
1. Click on the first transaction. Below the check image(s) on the right side of the screen you'll see "Refund", Add Transaction", "Back", and "Next" buttons.
1. Edit the selected transaction. 
1. Immediately save.
1. Observe all buttons except "Refund" are now gone.

**Expected behavior:**

I expect the buttons to still be there :)

**Actual behavior:**

The buttons are gone until I return to the Batch page and click on a transaction again.

### Versions ###

* **Rock Version:** 13.7 (also confirmed in Rock Demo which was running 14.0)
* **Client Culture Setting:** EN-US

**Comment by PTLKronk** [comment]
I went into the TransactionDetail.ascx.cs file and updated the code to be:
```
/**
      Changed by Kronk
      var pageRef = new PageReference( CurrentPageReference.PageId, CurrentPageReference.RouteId );
      pageRef.Parameters.Add( "TransactionId", savedTransactionId.ToString() );
       NavigateToPage( pageRef );
**/
                
   Dictionary<string, string> pageParams = new Dictionary<string, string>();
   pageParams.Add( "BatchId", PageParameter( "BatchId" ) );
   pageParams.Add( "TransactionId", savedTransactionId.ToString() );
   NavigateToLinkedPage( "TransactionDetailPage", pageParams );
```

Starting on like 396 in the lbSave_Click() functions.

This seems to have solved the issue. 
This was only made on my Production instance.
