### ISSUE TITLE
Breaking the WYSIWYG email editor with bullet points from Word

### ISSUE THREAD

**Issue by Jchinlcbc** [SparkDevNetwork/Rock#5295]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites ###

* [ X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description ###

When you copy and paste bullet points into the WYSIWYG email editor the page refreshes and resets your email. You lose all progress with your email.

### Steps to Reproduce ###

1 create a new communication

2 select your group

3 enter communication Name

4 Select any template

5 enter all needed information

6 click in the editor block

7 paste bulleted point **From Word** list into the WYSIWYG editor

**Expected behavior:**

pastes item as a <ul></ul> following the templated style

**Actual behavior:**

page reloads The first time this process is done. To replicate again, you need to start a new communication

### Versions ###

* **Rock Version:** [ Rock McKinley 14.0 (1.14.0.18)]
* **Client Culture Setting:** [en-US]

![RockBug](https://user-images.githubusercontent.com/100871349/214671479-bbc02729-52ea-433a-825c-cb8c0c05d4e6.gif)

**Comment by notGerryMiller** [comment]
I was able to replicate this and confirm this on 
https://rockrmslatest.com/ and http://rock.rocksolidchurchdemo.com/
