### ISSUE TITLE
Add Person on tablet narrow view not resizing and cannot be repositioned

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#530]
When adding a person (from Edit Family) on an Android tablet in portrait view the Add Person page is not resized for the narrow screen.  The fields disappear off the left of the screen.  When rotating the screen to landscape, the Edit Family screen in the background still has focus, not the Add Person screen: user can scroll the Edit Family screen, but cannot move the Add Person page.  This means that the user can't see the fields that are being filled in (when they are overlaid by the onscreen keyboard), cannot move down the Add Person page to view lower fields and the OK button cannot be displayed.  Only way to exit is to go back to portrait view to see the OK button.   I suspect that the Add Person screen should have focus so that it can be moved around the screen? (Though I note that the Add Person screen cannot be moved on a PC either.)

**Comment by arranf** [comment]
Modals are responsive in the latest version. Testing in browser this seems fine.
