### ISSUE TITLE
SQL Migration File Breaks 13.7 > 14.0 Upgrade 

### ISSUE THREAD

**Issue by kenmulford** [SparkDevNetwork/Rock#5300]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
  * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/1336749/216153836-ec15c225-f23d-4198-bd5e-eaa4fecc26ed.png)

### Description
Our team was running the Rock Upgrade from 13.7 to 14.0 in a _non production_ environment. When it was in the middle of SQL Migration files it failed due to a loosely constructed SQL statement.

### Steps to Reproduce
1. Go to [https://github.com/SparkDevNetwork/Rock/blob/1.14.1/Rock.Migrations/Migrations/Version 14.0/Version 1.14.0/202208022324441_RemoveMailgunSmtp_Mandrill.cs](https://github.com/SparkDevNetwork/Rock/blob/428e6747d489001fac3be770217a1edc7b8b92f2/Rock.Migrations/Migrations/Version 14.0/Version 1.14.0/202208022324441_RemoveMailgunSmtp_Mandrill.cs#L54)
1. Look at line 54. 
1. Run that SELECT statement with the parameter declarations in SSMS.
1. If you're like us and manage multiple non-production environments, you have safeguards in place to make the environment safe (it won't send emails, texts, etc.). One of our steps is to remove the attribute value of the transport from the communication medium. That breaks this SQL statement.

**Expected behavior:**

SQL essential to upgrades would be wrapped in `TRY_CAST` to ensure a graceful failure in the event, however unlikely, that someone may have introduced the same safeguards as us.

**Actual behavior:**

No safeguard exists. Upgrade failed until we used SQL to insert a GUID back into that attribute value.

### Versions
* **Rock Version:** 13.7, upgrading to 14.0
* **Client Culture Setting:** EN-US

**Comment by ethan-sparkdevnetwork** [comment]
@kenmulford Hello Ken. The problem is SQL Server is trying to convert your updated value of empty string found in AttributeValue.Value to a UNIQUEIDENTIFIER in order to compare it with the declared variables. The bug is declaring the variables as UNIQUEIDENTIFIER instead of VARCHAR(36) in the migration. I will fix this and patch the update package for 14.0.

If you need to bypass the error right now and still be in a "safe mode" you can set AttributeValue.Value to NULL instead of an empty string.
