### ISSUE TITLE
Head of Household Post-Filter Transformation Removes Deceased Records Even When Include Deceased is Checked

### ISSUE THREAD

**Issue by hollyhoke** [SparkDevNetwork/Rock#5302]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
When creating a data view and checking the _Include Deceased_ option, adding a Head of Household post-filter transformation removes the deceased person from the results. This occurs whether the deceased is still part of the same family group or if they've been moved to their own family group.

### Steps to Reproduce
1. Create a Person data view with the *Include deceased* box checked, adding one filter for *Is Deceased* equal to *Yes* to get a data view with some deceased people.
2. Run the data view to confirm there are results.
3. Add the "Head of household" post-filter transformation to the data view.

**Expected behavior:** 

Data view results should return the first non-deceased person in the family, or the deceased person if it's the only family member.

**Actual behavior:** 

 The data view with the head of household post-filter transformation is either empty or contains only the non-deceased person records (for scenarios where the deceased spouse is still part of the family).

### Versions

* **Rock Version:** Rock McKinley 14.1 (1.14.1.1)
* **Client Culture Setting:** en-US

**Comment by theburch** [comment]
Related issue - Using the "Related People" field in a report will not return any related person who is deceased.

**Comment by nairdo** [comment]
Hello @hollyhoke   We've looked into this one, and are not able to call this a bug.  The "post filter" transformations do not use the configuration of the data-view -- other than to take the pre-transformation results of the data view and transform it into another set of 'people' (in this case).  So, checking the "Include deceased" checkbox will allow deceased people to be in the initial set of pre-transformation data, but the post filter transform does not use that setting.  (It simply follows its own internal rule.)

We understand you are looking for a solution to your particular situation, but we might suggest you post your feature request as an idea to the Ideas board at https://community.rockrms.com/Ideas
