### ISSUE TITLE
Person Profile Image Clickable Area

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#5307]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
in v14 and beyond the profile picture "clickable" space extends beyond the picture itself.  I can click my picture to "expand" it and see an enlarged image even outside of the pictures dimensions.  While not a big deal in itself it can actually impact useability because the /Groups page I could not "unfilter" a group because my image overlapped the button to uncheck the grouptype.

### Steps to Reproduce
1. Go to rock.rocksolidchurchdemo site
1. Go to Alisha Admin's profile page and move your mouse over the profile picture.  It turns in to a "hand" or whatever you device shows for a clickable item. (all fine and good)
1. Then move "below" the profile picture where it should turn back into a mouse cursor. It does not do so.
1. Some images are worse than others.  It appears to matter what the height of the image is as to how "far down" the clickable portion extends.
1. 

**Expected behavior:**

Once your mouse moves outside of the visual representation of the profile picture it is no longer clickable

**Actual behavior:**

The image is "clickable" outside of the visual representation of it causing some UI issues depending on the block that is below the profile image.

### Versions
* **Rock Version:** [14.1]
* **Client Culture Setting:** [En-US]

**Comment by PraveenMathew92** [comment]
@markewampler Could you please share the screenshots of the issue. I am unable to reproduce it from my side on the [rock demo site](https://rock.rocksolidchurchdemo.com).

**Comment by markewampler** [comment]
@PraveenMathew92 Sorry about that.  I also realized this is only true on the other tabs. Not the main profile tab.  The extended attributes and all of the other ones where the profile gets scrunched up.

Will try and get a screenshot shortly.  My screen capture is having a hard time leaving the mouse cursor on the window as I am messing with it.  Will try and get a better functioning one to give an example.

**Comment by markewampler** [comment]
https://user-images.githubusercontent.com/33845027/218586445-9f9a4f12-ea46-4d4e-82ae-64e51fe635d6.mov

**Comment by JimMichael** [comment]
Mark, do you happen to be using Firefox? I can reproduce the issue on FF here, but not on Edge/Chrome. And when you look at the way the image renders on the non-profile pages on FF vs. Edge, you can see a big difference here... it's as if FF is masking/handling the image wrong compared to Edge/Chrome.

Here it is on Firefox for me:
![image](https://user-images.githubusercontent.com/3903408/218597875-b8ffe2dd-dee5-4960-9168-af2afc58dac4.png)

And here's the same page on Edge (Chromium)
![image](https://user-images.githubusercontent.com/3903408/218597936-08b57166-a37d-4fb3-b3c5-354e6817835b.png)

**Comment by markewampler** [comment]
You are correct @JimMichael . The demo I did was on edge, but I then updated and that went away.  I was probably behind as I have had some computer back and forth (hardware wise) the past week.  Safari works fine, but firefox does that.  Yay browsers!
