### ISSUE TITLE
Bulk Updating Connection Requests to FFU doesn't allow setting FFU Date

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5310]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Our staff have been using the bulk-updating connection request feature and loving it! However when someone bulk updates connection requests to set the status to _Future Follow-Up_, there is no way for them to set a Future Follow-Up date. I do realize that by definition this would be a feature request. However it feels like a bug because if I set 15 requests to FFU and can't set a date, I'm still having to touch each request to set that follow-up date. The Future Follow-Up date is also required when manually editing a request. Just seems like that's working against the purpose of the bulk update feature.

If it ends up being decided this should be feature request instead, I'd be happy to submit that to the Ideas page.

### Expected Behavior

I would expect when bulk editing connection requests that I could provide a Future Follow-Up date that would be set on each of the requests being updated.

### Actual Behavior

I am not able to provide a Future Follow-Up date when bulk editing connection requests to the State _Future Follow-Up_. The State of the requests is correctly set to Future Follow-Up, but no date is set.

### Steps to Reproduce

1. On the demo site, go to People > Connections
2. Click on one of the connection opportunities (in my testing, I used _Usher_)
3. Switch to _List_ view so you can see the bulk update options
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/66277785/218783434-c4354713-111f-4020-8628-4cdcd84ddf12.png">

4. Check the boxes for the requests in the list and click the Bulk Update icon
5. In the bulk update options, click the _State_ radio button and choose _Future follow up_ from the dropdown
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/66277785/218783699-35aa2026-4302-4846-b8c7-341d97604e68.png">

6. Click _Update_, and _Confirm_
7. Go back to the Usher opportunity (or whatever connection opportunity you used)
8. Notice how all of the requests are set to Future Follow-Up, but there's no FFU date listed

### Rock Version

Rock McKinley 14.0 (1.14.0.18)

### Client Culture Setting

en-US

**Comment by croske** [comment]
Closed with https://github.com/SparkDevNetwork/Rock/commit/6f006e07c8f5e76bf54c9b06fcb7ccc991f31474
