### ISSUE TITLE
Can No Longer Distinguish Private Personal Notes

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5311]
### Please go through all the tasks below ###

* [x] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side. ###

Prior to v14, there was a subtle UI element that let a note-writing Rock user easily distinguish a normal "Personal" note from one that has the _Private_ checkbox enabled. This seems to have been removed in Rock 14+ with the updated profile page. 

I'm reporting it as a bug because it actually removed useful functionality.

### Expected Behavior ###

One would be able to differentiate a normal Personal note from ones that are Private, at a glance.

### Actual Behavior ###

Normal and Private Personal notes now look identical, making them impossible to distinguish without editing the note and observing the state of the _Private_ checkbox.

This is what notes looked like prior to v14: (note the blue bar on the left of the Private note)

![image](https://user-images.githubusercontent.com/3903408/218839936-c637c3ea-f8ed-4055-b6cc-b2254c43a733.png)

And this is what it looks like in 14+ (you can't tell them apart)

![image](https://user-images.githubusercontent.com/3903408/218840069-3776ba04-e230-444b-a2c6-4451dfc3f088.png)

### Steps to Reproduce ###

1. Add a personal note to someone's timeline and check the _Private_ box.
1. Observe that there is nothing that indicates this as a private note when viewed on the timeline.

### Rock Version ###

14+

### Client Culture Setting ###

en-US

**Comment by JimMichael** [comment]
Stan here realized we could so this in the theme's CSS Overrides:

`.is-personal {
    border-left: thick;
    border-left-color: blue;
    border-left-style: solid;
}`

which brings back the blue bar on private notes. Not sure if that's the best way to handle it, but solves the problem for us, for now. If you think this isn't a bug and should be handled the way we did, feel free to close.

**Comment by cabal95** [comment]
I’m not sure yet the exact version this fix will land in yet but I will update once we have that exact version information.
