### ISSUE TITLE
Giving Alerts not filtering by Campus

### ISSUE THREAD

**Issue by MargaretMailhiot** [SparkDevNetwork/Rock#5314]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites ###

* [x ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description ###

[Description of the bug or feature. Include screenshots if applicable.]

We are on v14.0.

I have set configured giving alerts for each of our campuses, however, it does not seem to be taking this in account when creating the alert. All the results are showing as our Aurora campus. This issue is happening for gratitude & follow-up alerts.

![](https://user-images.githubusercontent.com/80711825/219100595-bbbb2479-bf56-4872-84ec-f078056d7fff.png)

![](https://user-images.githubusercontent.com/80711825/219100598-38c0196a-c4d0-4c32-9dba-9998f8d0bbe4.png)

![](https://user-images.githubusercontent.com/80711825/219100599-3543ef8a-d5c1-47a1-9fe2-c9497861a4e9.png)

![](https://user-images.githubusercontent.com/80711825/219100734-87dcdabd-f635-4e1a-b5b6-76792bf42307.png)

![](https://user-images.githubusercontent.com/80711825/219100727-472e1300-cfa2-4fc4-946c-f4fe1589aa6f.png)

![](https://user-images.githubusercontent.com/80711825/219100733-1a0a85a4-5c2d-473c-af24-d64c21efc09c.png)

### Steps to Reproduce ###

1.  Giving Alert configuration is set up to include "Person Campus" filter
![](https://user-images.githubusercontent.com/80711825/219101716-1e720242-9edc-4616-8341-bfc3cf753589.png)

**Expected behavior:**

I would expect the alert to include only individuals for that campus - In this case "Aurora", however this person is a "Naperville" attender. 

![](https://user-images.githubusercontent.com/80711825/219101778-4480a0ec-be7c-47d7-8c72-006d17fe731d.png)

**Actual behavior:**

The person's campus is not matching the filter. This person's campus is "Naperville"

![](https://user-images.githubusercontent.com/80711825/219101890-52fc0634-8714-443a-b0e3-65f347865b8e.png)

### Versions ###

* **Rock Version:** Rock McKinley 14.0 (1.14.0.18)
* **Client Culture Setting:** en-US

**Comment by chead4** [comment]
@MargaretMailhiot Hi Margaret - we are unable to recreate this issue on rocksolidchurchdemo.com (v16).  We are going to close this issue at this time. If you are able to recreate on rocksolidchurchdemo.com please supply a video and we will reopen the issue.
