### ISSUE TITLE
Move Block via CMS Configuration > Pages moves the block to the Header Zone.

### ISSUE THREAD

**Issue by gonemob** [SparkDevNetwork/Rock#5315]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When trying to move a block from one zone to another using the CMS Configuration > Pages > Page/Zones Block Editor, the block will always end up in the Header Zone if you Save.

### Expected Behavior

The block is moved to the zone chosen when saved.

### Actual Behavior

The block is moved to the Header Zone.

### Steps to Reproduce

Go to https://rock.rocksolidchurchdemo.com/admin/cms/pages and 

- either create a new page or select an existing one from the Pages side menu.
- Add a test html block to the Main Zone.
- Click the Move Block button to open a Move Block dialog
- Click the Save button
- Click the Zone dropdown and select the Header Zone
- See that the block has been moved to the Header Zone

### Rock Version

14.1

### Client Culture Setting

en-US

**Comment by dataCollegechurch** [comment]
In my testing it moved to the login zone, in any case something is still not working as expected. My only workaround to get the block back where it belonged was to delete the block and readd it in the desired zone.

**Comment by gonemob** [comment]
The workaround is to visit the live webpage’s uri and move the block using the admin tools from there, rather than the pagemap. Is the login zone in your instance the top/first zone, suggesting it defaults to that block?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dataCollegechurch** [comment]
Yes the login zone in my instance is the top/first zone, at least for the page and layout I did the testing on.

**Comment by nate-steil** [comment]
Can confirm this is happening in my sandbox environment as well. v14.2 and it's falling into the login zone, which is the top one on my list.
