### ISSUE TITLE
Connection Status Order Issue on Connection Request Detail Block

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5322]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Connection Statuses allow for manually setting the order they appear on the Connection Type.

However, the Connection Request Detail Block does not respect order of Connection Statuses set on the Connection Type. This does work properly on the Connection Request Board Block.

### Expected Behavior

Connection Request Detail block should display Statuses in order set on the Connection Type.

### Actual Behavior

Connection Request Detail block does not display Statuses in order set on the Connection Type.

### Steps to Reproduce

- Go to a Connection Type and add a 3rd Status like "Completed". Save.
![Screenshot 2023-02-22 at 08 14 36](https://user-images.githubusercontent.com/23226974/220632547-86195fc7-e447-4af8-9c75-b373c2138cb1.png)

- Edit the Connection Type and drag the statuses to a custom order. I put completed as the third option.
- Go to the Connection Request Board page (`https://rock.rocksolidchurchdemo.com/page/2635?ConnectionOpportunityId=2`), click on a request, and see that the statuses are in the order you set on the Connection Type. 
![Screenshot 2023-02-22 at 08 15 50](https://user-images.githubusercontent.com/23226974/220633568-55bced20-7c73-4c4e-a6e2-0bc402b5de59.png)

- Assign yourself (Alisha Admin) as the Connector on the Request. 
- Go to My Dashboard (`https://rock.rocksolidchurchdemo.com/MyDashboard`).
- Click on the Connection Request and click Edit.
- See that the Statuses are not in the correct order or you set on the Connection Type.
![Screenshot 2023-02-22 at 08 16 17](https://user-images.githubusercontent.com/23226974/220633646-2e13b657-e318-40b7-b0c2-0e5a57dfe0d1.png)

### Rock Version

v14.0, v14.1

### Client Culture Setting

en-US

**Comment by mikedotmundy** [comment]
What version will this be in?

**Comment by croske** [comment]
@mikedotmundy - this change was added to v16 -- I just updated the "fixed in" label.

**Comment by mikedotmundy** [comment]
Thank you!
