### ISSUE TITLE
Communication List Page timing out on large Communication List Groups

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#5324]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Submitted on behalf of North Point Ministries

With Communication Lists over 25,000 recipients the Communication List page is timing out and not loading.  Multiple lists totaling that amount do not have an issue, but large single lists load very slowly.

### Expected Behavior

Handle large Communication Lists without long delays or timeouts.

### Actual Behavior

Depending on the size of the list, pages can take 25+ seconds to load or timeout.

### Steps to Reproduce

- Create a Communication List with 50,000 people.
- Navigate to Admin -> Communications -> Communication Lists
- See slow or timeout behavior

### Rock Version

12.9 and 13.7

### Client Culture Setting

Azure VM & Azure SQL

**Comment by bobrufenacht** [comment]
The issue is in how the count is being loaded.  On GroupList.cs line 874 the Member Count is forcing Rock to load all members into a collection just to count the members.  I suggest the following fix which loads almost instantaneously.

                groupList = qryGroups
                    .AsEnumerable()
                    .Where( g => g.IsAuthorized( Rock.Security.Authorization.VIEW, CurrentPerson ) )
                    .Select( g => new GroupListRowInfo
                    {
                        Id = g.Id,
                        Path = string.Empty,
                        Name = ( ( useRolePrefix && g.GroupType.Id != roleGroupTypeId ) ? "GROUP - " : string.Empty ) + g.Name,
                        GroupType = GroupTypeCache.Get( g.GroupTypeId ),
                        GroupOrder = g.Order,
                        Description = g.Description,
                        IsSystem = g.IsSystem,
                        IsActive = g.IsActive,
                        IsArchived = g.IsArchived,
                        IsActiveOrder = g.IsActive ? 1 : 2,
                        GroupRole = string.Empty,
                        DateAdded = DateTime.MinValue,
                        IsSynced = g.GroupSyncs.Any(),
                        MemberCount = 0 //g.Members.Count()
                    } )
                    .AsQueryable()
                    .Sort( sortProperty )
                    .ToList();

                var groupMemberService = new GroupMemberService ( rockContext ).Queryable ( true );
                foreach ( var group in groupList )
                {
                    group.MemberCount = groupMemberService.Where ( x => x.GroupId == group.Id ).Count ();
                }

**Comment by nlBayside** [comment]
We faced this same problem at our church recently too. The guess that we made was that it was the authorization check on each communication list. I agree it makes more sense that it'd be ```g.Members.Count()```. That line isn't generating a ```COUNT(*)``` in sql, but rather fetching all the group members from the group and counting those records.

This problem happens with the ```g.GroupSyncs.Any()``` as well. I think the LINQ methods aren't acting the same on Queryables as Enumerables. (Group Member count looks roughly the same). Here's what that SQL looks like:
```sql
exec sp_executesql N'SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[GroupId] AS [GroupId], 
    [Extent1].[GroupTypeRoleId] AS [GroupTypeRoleId], 
    [Extent1].[SyncDataViewId] AS [SyncDataViewId], 
    [Extent1].[WelcomeSystemCommunicationId] AS [WelcomeSystemCommunicationId], 
    [Extent1].[WelcomeSystemEmailId] AS [WelcomeSystemEmailId], 
    [Extent1].[ExitSystemCommunicationId] AS [ExitSystemCommunicationId], 
    [Extent1].[ExitSystemEmailId] AS [ExitSystemEmailId], 
    [Extent1].[AddUserAccountsDuringSync] AS [AddUserAccountsDuringSync], 
    [Extent1].[ScheduleIntervalMinutes] AS [ScheduleIntervalMinutes], 
    [Extent1].[LastRefreshDateTime] AS [LastRefreshDateTime], 
    [Extent1].[CreatedDateTime] AS [CreatedDateTime], 
    [Extent1].[ModifiedDateTime] AS [ModifiedDateTime], 
    [Extent1].[CreatedByPersonAliasId] AS [CreatedByPersonAliasId], 
    [Extent1].[ModifiedByPersonAliasId] AS [ModifiedByPersonAliasId], 
    [Extent1].[Guid] AS [Guid], 
    [Extent1].[ForeignId] AS [ForeignId], 
    [Extent1].[ForeignGuid] AS [ForeignGuid], 
    [Extent1].[ForeignKey] AS [ForeignKey]
    FROM [dbo].[GroupSync] AS [Extent1]
    WHERE [Extent1].[GroupId] = @EntityKeyValue1',N'@EntityKeyValue1 int',@EntityKeyValue1=66
```

For the moment, we're using a dynamic data block with the SQL below. It doesn't check permissions but this page for us is scoped through permissions anyways. It also doesn't have the archive/sync buttons, but you can access the Group Detail block by clicking on a row.

```sql
SELECT
    g.Id AS [GroupId]
    ,g.Name AS [GroupName]
    ,g.Description
    ,COUNT(*) AS [MemberCount]
    ,g.IsActive
FROM
    [Group] g
    LEFT JOIN [GroupMember] gm ON gm.GroupId = g.Id
        AND gm.IsArchived != 1 -- Not Archived
        AND gm.GroupMemberStatus != 2 -- Not Pending
WHERE
    g.GroupTypeId = 32 -- Communication List
    AND g.IsArchived = 0
GROUP BY
    g.Id, g.Name, g.Description, g.IsActive
ORDER BY
    g.Name ASC
```

**Comment by adamhann** [comment]
I can confirm we are having these issues in v14.2.
