### ISSUE TITLE
Group Schedule Confirmation Block - Not Sending Decline

### ISSUE THREAD

**Issue by randyjreed** [SparkDevNetwork/Rock#5328]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

After 14.1 update, when a person is scheduled to serve and clicks decline from the email/sms that sends them to the `Group Schedule Confirmation` page. The scheduler is never informed of the decline. Instead, there is an error in the exception list. If the decline is done in the Schedule Toolbox the decline notification is sent.

### Expected Behavior

Pre 14.1 the scheduler would receive a decline email when a person declines the schedule.

### Actual Behavior

No email is sent and an error is produced.

`The ObjectContext instance has been disposed and can no longer be used for operations that require a connection.`

<img width="1810" alt="Screenshot 2023-02-26 at 9 02 11 AM" src="https://user-images.githubusercontent.com/22873346/221425020-d19f3bbf-89fe-4e33-83d3-ecf519a21e75.png">

### Steps to Reproduce

(Be sure to have the decline email enabled on the `Group Scheduling Confirmation` block.)
Schedule a volunteer
Send a Confirmation
Click Decline
Complete the form
Check the Exception List

### Rock Version

Rock McKinley 14.1 (1.14.1.1)

### Client Culture Setting

en-US

**Comment by JimMichael** [comment]
We are seeing this same exception and no decline email (we're on 14.2)

**Comment by brianbeauford** [comment]
We are having the same issue. We're on Rock McKinley 14.1 (1.14.1.1)

**Comment by randyjreed** [comment]
@shauncummings Can this fix be applied manually by overwriting the `RockWeb/Blocks/GroupScheduling/GroupScheduleConfirmation.ascx.cs` file?

**Comment by shauncummings** [comment]
> @shauncummings Can this fix be applied manually by overwriting the `RockWeb/Blocks/GroupScheduling/GroupScheduleConfirmation.ascx.cs` file?

In general, yes, this updated block file is safe to add to a v14.1 instance.  Please be sure to back up your existing files before making such direct modifications.

Also, I incorrectly flagged this fix for v15.1, but it will be in v15.0.

**Comment by tpeera** [comment]
@shauncummings I am on v15.4 and notice that 
1. I get 2 decline emails if someone declines from the /ScheduleConfirmation page AND has the option on the **Group Schedule Confirmation** block selected for **Scheduler Receive Confirmation Emails** = Yes. 
2. In reference to the page and block setting in the above statement, the setting will not send the scheduler a **confirmation** if the person **accepts**. (I can only get accepted confirmation when the person accepts from the group schedule toolbox)
![image](https://github.com/SparkDevNetwork/Rock/assets/92802570/bccdf701-26f5-4b7f-85f5-c733812ee005)

**Comment by nairdo** [comment]
@tpeera  Thanks for letting us know about that.  For item 1, that is the current behavior.  For item 2, that is a bug and it has been resolved with this fix (https://github.com/SparkDevNetwork/Rock/commit/a14493d9485472745add1706aa8706f00e20811b) and it will be in v16.5.

**Comment by tpeera** [comment]
@nairdo why would option 1 have that behavior? If they are already getting a decline confirmation, why would they need a duplicate? Should the block option only be for Accepted responses since by default the scheduler will get declines?
