### ISSUE TITLE
Contribution Statement - Business

### ISSUE THREAD

**Issue by jefforians** [SparkDevNetwork/Rock#5329]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When creating a new financial transaction, for a BUSINESS, an address is required. It appears, especially if the transaction address is different than the profile address, that the contribution statement is using the transaction address and not the profile address when it's created.
<img width="460" alt="Rock Statement - Statement" src="https://user-images.githubusercontent.com/126497306/221613366-55060744-d0be-4e9b-9073-bd7bccd5e3c5.PNG">
The address shown on the statement is not the address on the business profile page.

### Expected Behavior

The contribution statement should be collecting the current business profile address on the address block of the statement.

### Actual Behavior

The statement process is using the address shown on the transaction

### Steps to Reproduce

- Create new business record with address
- Create new transaction (Add One-time Gift) for business
- Add a transaction address different than the business profile address
- View the Contribution Statement

<img width="887" alt="Rock Statement - Create Busines" src="https://user-images.githubusercontent.com/126497306/221614804-b5f4503e-938b-42b9-bfb7-b192acb34cdd.PNG">

<img width="615" alt="Rock Statement - Transaction Address" src="https://user-images.githubusercontent.com/126497306/221615361-2480d4b1-46c7-4e04-95df-fa7b7c5d0d55.PNG">

<img width="460" alt="Rock Statement - Statement" src="https://user-images.githubusercontent.com/126497306/221614830-bf226b21-daca-436b-a674-662aad58711b.PNG">

### Rock Version

v13.4, v14.0, v14.1

### Client Culture Setting

v14.0

**Comment by jonedmiston** [comment]
@jefforians  the Business Detail block only shows the Business' Work Address. In fact a business can only have one type of address, Work, which is always considered the Mailing Location. The best I can guess how your example above was achieved was that someone may have:

1. Converted the business to a person
2. Added a Home Address that was set to the Mailing Location
3. Converted it back to a business

Does that seem likely? The history might show that.

The logic for the statement generator should pull the IsMailingLocation and could be favoring the home over the work. We might consider adding to the clean-up job deleting Home address from businesses and ensuring that their Work address is set to IsMailingLocation = true.

**Comment by jonedmiston** [comment]
Going to close this out as I believe the explanation above solves this. If not please re-open with more info.
