### ISSUE TITLE
Setting 'Root Group' in Group List Block has no effect

### ISSUE THREAD

**Issue by PTLKronk** [SparkDevNetwork/Rock#5331]
### Please go through all the tasks below

- [ ] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When adding a new Group List block, and setting the Root Group. No effect happens, and all groups of designated group types from the highest level are shown.

### Expected Behavior

When choosing a root group the should be where the list begins as the highest level to show from.

### Actual Behavior

When choosing a root group the Group List block still shows the highest level, rather than the chosen root group.

### Steps to Reproduce

- Create new group list block on a page
- Open block properties for the block
- Choose a root group
- Save the settings

### Rock Version

13.7

### Client Culture Setting

en-US

**Comment by unlearnd** [comment]
The original intent of this block setting was specific to adding a new group when using the Group Picker control type. It was meant to set the root node of the tree view for that control. The changes to the group list display filtering have been reverted and the help text has been updated to make the intent clearer. See https://github.com/SparkDevNetwork/Rock/issues/5735 for additional context.
