### ISSUE TITLE
Event Occurrence can be Deleted with no Confirmation Modal

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5336]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When viewing an Event Occurrence via the `Calendar Event Item Occurrence Detail` block, the Delete button is right next to the Edit button. If you accidentally click Delete, there is no warning modal that appears to confirm if you really want to delete the Event Occurrence. It is just gone. 

In most areas of Rock (if not all), when you attempt to delete something, a warning modal will appear confirming you really do want to delete the item. This is not the case in the `Calendar Event Item Occurrence Detail` block.

![Screenshot 2023-03-08 at 08 08 04](https://user-images.githubusercontent.com/23226974/223722838-63ac3962-93bc-4e2e-9156-ea29d681f3ab.png)

Also, upon deleting the Occurrence, you are redirected to this page. I would assume I should be redirected to the Event Item page.

![Screenshot 2023-03-08 at 08 08 46](https://user-images.githubusercontent.com/23226974/223722861-ebfdd9ed-5577-4a14-a366-4e1a22994732.png)

### Expected Behavior

A modal should pop up confirming I want to actually delete the Event Occurrence.

### Actual Behavior

A modal does not pop up confirming I want to actually delete the Event Occurrence.

### Steps to Reproduce

- Go to an Event Occurrence (Example: `https://rock.rocksolidchurchdemo.com/web/calendars/1/event/2/occurrence/2`)
- Click `Delete`
- See the Event Occurrence is deleted with no modal to confirm deleting the Event Occurrence.

### Rock Version

v14.1

### Client Culture Setting

en-US

**Comment by melzs0627** [comment]
This issue has been resolved in v15 of rock. Reference to the update is here: https://github.com/SparkDevNetwork/Rock/commit/bf63d040c05f0ee6fcdc234694cf69890e70e393
I will now close this issue.
