### ISSUE TITLE
Add Separate Report Fields for Address and add comma after Address Line 1 & 2 in Address

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#534]
I've raised this as an 'Ask' - but I can't  think it might be easy to fix?
For both Groups and Person - the only way to list an address gives a one field address.  This makes it difficult to export to Excel for the purposes of mail merging etc.  
Is it possible to add separate address fields as reporting field options 
- for Person
  - Address - Address Line 1
  - Address - Address Line 2
  - Address - City
  - Address - State
  - Address - Zip
- for Group
  - Location - Address Line 1
  - Location - Address Line 2
  - Location - City
  - Location - State
  - Location - Zip

I also think that the Address field currently reported should have a comma separating each field. There is no comma after Address Line 1 or Address Line 2.  This makes it impossible to parse out the Address field into separate fields in Excel.

![addressfields](https://cloud.githubusercontent.com/assets/4658177/4350794/7cf585c8-41f9-11e4-83f2-fcf25d99a346.jpg)

**Comment by arranf** [comment]
@ElimAdmin I think this is fixed in 3.0

**Comment by arranf** [comment]
As far as I can tell this all exists in 1.5.2, as as far as I can recall as of 1.2.0. @ElimAdmin let me know if this isn't the case and needs to be reopened.
