### ISSUE TITLE
Obsidian Event Registration Uncaught JS Error Triggered by None of the Above Selection

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5341]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

![image](https://user-images.githubusercontent.com/54962439/224726288-2dd34154-0c1c-4790-aa3d-c67f62009c72.png)
Selecting none of the above to the "Registrant is in the same immediate family as" during the event registration process caused an uncaught JS error and birth date field to perdisappear.

### Expected Behavior

The user would not be present with an error message and the birthdate field would stay put

### Actual Behavior

The users is presented with an error message and the birthdate field disappears

### Steps to Reproduce

1. Go to the demo site and generate a Starting Point Event Instance
2. Enable the "Show Family Members" Setting on the template
3. ![image](https://user-images.githubusercontent.com/54962439/224728731-5d21a323-0f70-46e2-a240-e2202d55fd4c.png)
4. Add Birthdate to the template as well
5. ![image](https://user-images.githubusercontent.com/54962439/224729154-ce1b8ac6-0655-4711-891e-db5c31b55bb5.png)
6. Navigate to the registration on a page that includes the Obsidian Event Registration block
7. Click "None of the above" to the Registrant is in the same immediate family as question
8. ![image](https://user-images.githubusercontent.com/54962439/224729607-34c76ed6-8d3d-426a-8df7-7bb9ad309737.png)

### Rock Version

14.1

### Client Culture Setting

en-US

**Comment by baynehh** [comment]
Reproducible.

**Comment by dataCollegechurch** [comment]
Hi @baynehh. At this time, you can classify issues as bugs and then reproduced here: https://community.rockrms.com/page/1416

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in commit 63286d09 in 15.0 and cherry picked to 14.3.
