### ISSUE TITLE
Open Ended Date Range Causes Error for Data Views

### ISSUE THREAD

**Issue by melissadrexler** [SparkDevNetwork/Rock#5350]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

A data view that has a filter with a type of date range (such as the Steps Taken option) where the beginning date is set but the end date is blank will cause an error. Previously created data views will show the error when the Edit button is clicked, and new data views will show the error once the Save button is clicked.

### Expected Behavior

Open-ended date ranges would be acceptable filters and would cause no errors.

### Actual Behavior

The error message displays: Error - _34|error|500|Nullable object must have a value.|_

### Steps to Reproduce

- Go to data views
- Create a new data view for a _Person_
- Add the filter for Steps Taken
- Select a step type
- Enter the Completed Date as a date range of 1/1/2022 - empty
- Attempt to save

### Rock Version

14.1

### Client Culture Setting

en-US

**Comment by dataCollegechurch** [comment]
![image](https://user-images.githubusercontent.com/54962439/226653075-5b7f4b97-dec3-41b2-bfe9-e1346893ac1f.png)

**Comment by MichaelAllen** [comment]
This bug also affects the "Last Activity Date Range" filter on the connection board. I have seen a few people in Rocket Chat run into it there.

It looks like it should be fixed in v15 by this commit: https://github.com/SparkDevNetwork/Rock/commit/0afd5faefb065c98a5b400f54782c9ef43c882b0

**Comment by TheArkChurch** [comment]
> This bug also affects the "Last Activity Date Range" filter on the connection board. I have seen a few people in Rocket Chat run into it there.
> 
> It looks like it should be fixed in v15 by this commit: [0afd5fa](https://github.com/SparkDevNetwork/Rock/commit/0afd5faefb065c98a5b400f54782c9ef43c882b0)

We had this issue on the connection board(and posted about it). Clearing the affected persons Rock user preferences ended up fixing it.

**Comment by ethan-sparkdevnetwork** [comment]
This was fixed in commit 0afd5faefb065c98a5b400f54782c9ef43c882b0
