### ISSUE TITLE
Registration List Lava Not Showing All Registrations

### ISSUE THREAD

**Issue by sfdts** [SparkDevNetwork/Rock#5351]
## Please go through all the tasks below

* [x] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
The Registration List Lava block is hiding some registrations unless the LimitToOwed is toggled true. Specifically it is not showing Registrations that may not have a NextStartDate.## Expected Behavior
I would expect to see all registrations regardless of payment owed if that option is set to false.## Actual Behavior
Some registrations are hidden unless toggling LimitToOwed option in block settings.## Steps to Reproduce

* Create Registration and sign up, do not have a date or have it end for testing (as to not have a next start date)
* Add RegsitrationListLava block to any page to test with
* Set the block option for LimitToOwed to false/No
* Your Registration will not show up

It seems to be due to the adjustment in this commit:

https://github.com/SparkDevNetwork/Rock/commit/ff4f5cb7ae4db25646a71e5399e4a48ebf09ee02## Rock Version
1.14.1## Client Culture Setting
en-US

**Comment by tpcc-myles** [comment]
We are experiencing this behavior with the block in v14.1.  Previously, the most recent registrations would display here, but now none show up.  We've had to modify the core block to restore the previous functionality.

**Comment by ctkbellingham** [comment]
@tpcc-myles – We're having the same issue since upgrading to 14.2. _**Can you share the modifications you made to the Core block to restore this functionality?**_

**Comment by leahjennings** [comment]
We also recently ran into this problem. Here's some Lava (v13.0+) that we now use to display recent registrations as a workaround until the block issues are resolved. This Lava can be put into the Lava Output of the Registration List block. We only need to show all the active instances where money is still owed, disregarding any date ranges and start/end dates. Adjust as you see fit:
```
{% registration expression:'PersonAlias.PersonId == "{{ Person.Id }}" && RegistrationInstance.IsActive == true' select:'new ( Id AS RegistrationId, RegistrationInstance.Name AS InstanceName, RegistrationInstance.EndDateTime, RegistrationInstance.RegistrationTemplate.AllowExternalRegistrationUpdates AS ExternalUpdates, BalanceDue, PersonAlias.PersonId, RegistrationInstance.Id AS InstanceId )' sort:'CreatedDateTime desc' %}
    //- Limits to registrations where a balance is owed
    {% assign regSubset = registrationItems | Where:'BalanceDue', 0, 'notequal' %}
    {% assign quantityOfResults = regSubset | Size %}
    
    {% if quantityOfResults > 0 %}
        <div class="panel panel-default">
            <div class="panel-heading">Recent Registrations</div>
            <ul class="list-group list-group-panel">
        {% for reg in regSubset %}
            <li class="list-group-item">
              <a href="{{ 'Global' | Attribute:'PublicApplicationRoot' }}Registration?RegistrationId={{ reg.RegistrationId }}" class="js-group-item" >{{ reg.InstanceName }}</a>
        		{% if reg.BalanceDue > 0 %} <label class='label label-warning'>{{ reg.BalanceDue | FormatAsCurrency }}</label> {% endif %}
            </li>
        {% endfor %}
        	</ul>
        </div>
    {% endif %}
{% endregistration %}
```

**Comment by tpcc-myles** [comment]
> @tpcc-myles – We're having the same issue since upgrading to 14.2. _**Can you share the modifications you made to the Core block to restore this functionality?**_

@ctkbellingham the main change was to move this code from line 156 to line 153 (ie: just above the if-statement that it was currently in).
`registrationList.AddRange( noDates );`
but we also put a try-statement around lines 128-150, followed by an empty catch-statement.
