### ISSUE TITLE
Obsidian Registration Entry - When file required is set on template getting file is required if file has been uploaded

### ISSUE THREAD

**Issue by tmcfall01** [SparkDevNetwork/Rock#5359]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When a Registrant Attribute is set to Field Type of File and Requires a value:
![Screen Shot 2023-03-27 at 4 40 57 PM](https://user-images.githubusercontent.com/33043289/228091044-4a779c70-8f54-4b50-afc6-d61030782eb6.png)

During Registration after the file is uploaded and the Next button is clicked:
![Screen Shot 2023-03-27 at 4 41 59 PM](https://user-images.githubusercontent.com/33043289/228091150-5c3a1800-56bb-42e4-90da-fb5b6775a4ce.png)

The following error message occurs and you can't continue:
![Screen Shot 2023-03-27 at 4 41 48 PM](https://user-images.githubusercontent.com/33043289/228091202-b0094039-2d3d-46ae-8f78-8e3d089f0d01.png)

### Expected Behavior

When the file has uploaded in the registration when you click the next button the "file is required" error message should not appear and allow continuing the registration.

### Actual Behavior

When the file has uploaded in the registration when you click the next button a "file is required" error message appears and you cannot continue with the registration.

### Steps to Reproduce

1. Go to the demo site and navigate to Tools > Event Registration
2. Click on any template
3. Edit the template and add a Registration Attribute to the Registrant form and make the field type file, file type Unsecured, and check the Require a Value check box
4. Go to the registration and click through the first page
5. On the next page fill in required information and then upload any file type to the file attribute
6. You will see the file upload into the attribute file box successfully
7. Click on the Next button
8. You will receive a "file is required" message at the top and it will not let you proceed

This was tested with different file types with the same results.

If not requiring the file type in the attribute on the template, it is possible to continue the registration successfully without receiving the "file is required" message.

---------------------------
In our current environment:
When uploaded before clicking the Next button, we are able to see the file was uploaded into the database, or external storage.

### Rock Version

Rock McKinley 14.2 (1.14.2.1)

### Client Culture Setting

en-US

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in 175be899.
