### ISSUE TITLE
If Statements in Workflows Work Different in Fluid Lava vs. DotLiquid Lava

### ISSUE THREAD

**Issue by kfrazier13** [SparkDevNetwork/Rock#5365]
## Please go through all the tasks below

* [x] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
While creating a workflow, I encountered this error related to the _If_ statement after copying the email code from a built-in system workflow when using the Fliud Lava engine compared to the DotLiquid Lava engine.Code Used:`<p>{{ Workflow | Attribute:'ReportedBy' }},</p>

<p>The data error that you reported for {{ Workflow.Name }} has been completed.<p><h4>Details:</h4>

<p>{{ Workflow | Attribute:'Details' }}</p>{% if Workflow | Attribute:'Resolution' != Empty %}【 code  】

<h4>Resolution:</h4>

<p>{{ Workflow | Attribute:'Resolution' }}</p>

【 end code 】

{% endif %}

`Depending on the lava engine being used, the system workflow code errors and has to be rewritten.Here is the output using the DotLiquid Lava engine:![](https://user-images.githubusercontent.com/129417960/228936134-d88d6f17-29e4-408a-b5e2-f7f3bf90b22e.png)Here is the output using the Fluid Lava engine:![](https://user-images.githubusercontent.com/129417960/228936297-124f2ef9-3fea-40e4-8fb2-5c8210deb42e.png)The only way to prevent the error is to add an _Assign_ Statement before using the _If_ Statement.![](https://user-images.githubusercontent.com/129417960/228937366-72c8049a-7d8e-4367-8083-9f127cc3a7a3.png)## Expected Behavior
With the shift from the DotLiquid Lava engine to the Fluid Lava engine, I would have expected all system workflows and code to continue to function without having to make changes to the code.## Actual Behavior
Lava statements in workflows using an _If_ Statement no longer works unless there is an _Assign_ Statement added before the _If_ Statement.## Steps to Reproduce

* Set your Lava Engine Liquid Framework to "Fluid"
* Use an _If_ Statement in a workflow without using an _Assign_ Statement
* Run the workflow or enter the lava in the Lava Tester
* Receive an error that there is an invalid 'if' tag

## Rock Version
14.1## Client Culture Setting
en-US

**Comment by dataCollegechurch** [comment]
@kfrazier13 - I took a look at the demo site running 14.2 and built in workflow "Person Data Error" and the notifiy originator code now has this code which appears to be fluid compatiable:
![image](https://user-images.githubusercontent.com/54962439/231890150-5b1419ab-ba2f-4f41-b797-a913a4272b34.png)

Is the "Notifiy originator" action within the Core "Person Data Error" workflow where you found this code in your instance?

**Comment by dataCollegechurch** [comment]
@MrUpsideDown - What are some possible reasons Kathryn's lava code in referenced core workflow does not match what is found on the demo site? It seems possible the workflow did not get automatically updated on Kathryn's system when a migration took place.

**Comment by JimMichael** [comment]
I’m not 100% positive, but I _thought_ that a migration of core Lava would be skipped if it determined you’d edited said Lava (they don’t want to overwrite your changes). 

I know I’ve seen that in SOME places in Rock during migrations, but not sure if it happens everywhere and is the culprit here.

**Comment by MrUpsideDown** [comment]
@JimMichael is correct, the policy is that core Lava templates are only updated if they have not been modified in any way. That is the most likely explanation for why this issue was not fixed by a migration.

@dataCollegechurch - there is currently no way of tracking skipped template updates, but I think that adding some method of identifying modified Lava templates is a good idea for a future enhancement.

**Comment by kfrazier13** [comment]
@dataCollegechurch, @JimMichael, @MrUpsideDown - the template was never changed in our system until I found the error when I was working on a new workflow and wanted to use the same code. There were actually several other things I ended up needing to change that were core lava (the locked-out screen message) because they were throwing an error message after changing to Fluid.

**Comment by nairdo** [comment]
@kfrazier13 Thanks for letting us know about this.  It does look like we have a bug in the Body/Lava template of the stock "Person Data Error" workflow type, so we will fix that issue in our stock example.  But to be clear, Rock is not supporting using 'filters' in the conditionals of IF statements such as this:

`{% if Workflow | Attribute:'Resolution' != Empty %}` 

As mentioned in the Lava docs here: https://community.rockrms.com/lava/tags/if-else-tags
![image](https://github.com/SparkDevNetwork/Rock/assets/383807/c1fd1f52-69c4-432f-b56c-b84468b9b99f)

Thanks also to @JimMichael @dataCollegechurch and @MrUpsideDown for your assistance in helping track this one down!

**Comment by Kwame-Agyei** [comment]
We found, and are correcting, 5 places in the Rock core/stock example workflows that were incorrectly using a filter in the `if` conditional for that workflow action.  They are being corrected via a data migration that will be run when updating to Rock v15.2.

**Comment by nairdo** [comment]
Fixed in a hotfix data migration via https://github.com/SparkDevNetwork/Rock/commit/8c2123fbd02fa522670f71efe813cbcfdfda435f
