### ISSUE TITLE
Slow Rock Startup

### ISSUE THREAD

**Issue by SteveSwaringen** [SparkDevNetwork/Rock#5375]
### Please go through all the tasks below

- [ ] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

We're seeing significant performance issues in Rock V14 during startup that are very painful. Prior to V14, a Rock restart typically took less than a minute. Now it is usually more than ten minutes and closer to fifteen in production (and worse in our sandboxes and development environments).

The problem seems to originate with this commit: <https://github.com/SparkDevNetwork/Rock/commit/63c4f0d103976640fae3b20c029a7c180d12c8d7>

Below is a CPU Usage Call Tree from Visual Studio using data captured during this prolonged startup. (These numbers are probably worse than production because of the reduced resources of my development environment and the increased latency between my box and the production SQL server, but the signature is consistent with what we see in production.) 

You can see that most of the time is attributable to loading entity cache (rows 44 and 45). Working back up the tree, this seems to be drivin by an AttributeCache.All() method (row 34) that is endeavoring to load _all_ attributes into cache. That method is called from AttributeCache.GetAttributePropertyDependencies() (row 33), a new method introduced in this commit.

Working further up the call stack, this is driven by AttributeCache.GetDirtyAttributeIdsForPropertyChange() (row 28), another new method in this commit, which is being called from DbContext.RockPostSave() (Row 27) and ultimately from Application_Start() (row 22) by way of EntityTypeService.RegisterEntityTypes() (row 23).

I believe that prior to this change, AttributeCache relied on a lazy load strategy. If it isn't absolutely necessary to preload that cache during startup, we'd really like to see this move back in that direction.

| Row | Function Name                                                                                                                                                        | Total CPU [unit, %] | Self CPU [unit, %] | Module            | Category          |
| --- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------- | ------------------ | ----------------- | ----------------- |
| 1   |  + iisexpress (PID: 788)                                                                                                                                             | 72334 (100.00%)     | 960 (1.33%)        | Multiple modules  |                   |
| 2   | \- + [External Call]                                                                                                                                                 |                     |                    |                   |                   |
| 3   |    (IIS internals omitted for brevity)                                                                                                                               |                     |                    |                   |                   |
| 20  | \------------------ + [External Call]                                                                                                                                |                     |                    |                   |                   |
| 21  | webengine4.dll!0x00007fffc30e543a                                                                                                                                    | 42530 (58.80%)      | 0 (0.00%)          | webengine4        | Database          |
| 22  | \------------------- + RockWeb.Global.Application_Start(object, System.EventArgs)                                                                                    | 42530 (58.80%)      | 0 (0.00%)          | app_code.ftwypmst | Database          |
| 23  | \-------------------- + Rock.Model.EntityTypeService.RegisterEntityTypes()                                                                                           | 42530 (58.80%)      | 0 (0.00%)          | rock              | Database          |
| 24  | \--------------------- + Rock.Data.DbContext.SaveChanges()                                                                                                           | 42530 (58.80%)      | 0 (0.00%)          | rock              | Database          |
| 25  | \---------------------- + Rock.Data.DbContext.SaveChanges(bool)                                                                                                      | 42530 (58.80%)      | 0 (0.00%)          | rock              | Database          |
| 26  | \----------------------- + Rock.Data.DbContext.SaveChanges(Rock.Data.SaveChangesArgs)                                                                                | 42530 (58.80%)      | 0 (0.00%)          | rock              | Database          |
| 27  | \------------------------ + Rock.Data.DbContext.RockPostSave(System.Collections.Generic.List<ContextItem>, Rock.Model.PersonAlias, bool)                             | 42530 (58.80%)      | 0 (0.00%)          | rock              | Database          |
| 28  | \------------------------- + Rock.Web.Cache.AttributeCache.GetDirtyAttributeIdsForPropertyChange(int, System.Func<System.Collections.Generic.IReadOnlyList<string>>) | 42530 (58.80%)      | 0 (0.00%)          | rock              | Database          |
| 29  | \-------------------------- + Rock.Web.Cache.RockCache.GetOrAddExisting(string, System.Func<object>)                                                                 | 42530 (58.80%)      | 0 (0.00%)          | rock              | Database          |
| 30  | \--------------------------- + Rock.Web.Cache.RockCache.GetOrAddExisting(string, string, System.Func<object>)                                                        | 42530 (58.80%)      | 0 (0.00%)          | rock              | Database          |
| 31  | \---------------------------- + Rock.Web.Cache.RockCache.GetOrAddExisting(string, string, System.Func<object>, System.TimeSpan)                                      | 42530 (58.80%)      | 0 (0.00%)          | rock              | Database          |
| 32  | \----------------------------- + Rock.Web.Cache.RockCache.GetOrAddExisting(RockCacheGetOrAddExistingArgs)                                                            | 42530 (58.80%)      | 0 (0.00%)          | rock              | Database          |
| 33  | \------------------------------ + Rock.Web.Cache.AttributeCache.GetAttributePropertyDependencies()                                                                   | 42530 (58.80%)      | 0 (0.00%)          | rock              | Database          |
| 34  | \------------------------------- + Rock.Web.Cache.AttributeCache.All()                                                                                               | 42530 (58.80%)      | 0 (0.00%)          | rock              | Database          |
| 35  | \-------------------------------- + Rock.Web.Cache.AttributeCache.All(Rock.Data.RockContext)                                                                         | 42530 (58.80%)      | 0 (0.00%)          | rock              | Database          |
| 36  | \--------------------------------- + Rock.Web.Cache.EntityCache<T, T>.All(Rock.Data.RockContext)                                                                     | 42530 (58.80%)      | 11 (0.02%)         | rock              | Database          |
| 37  | \---------------------------------- + Rock.Web.Cache.EntityCache<T, T>.Get(int, Rock.Data.RockContext)                                                               | 42468 (58.71%)      | 0 (0.00%)          | rock              | Database          |
| 38  | \----------------------------------- + Rock.Web.Cache.EntityItemCache<T>.GetOrAddExisting(int, System.Func<T>)                                                       | 42465 (58.71%)      | 1 (0.00%)          | rock              | Database          |
| 39  | \------------------------------------ + Rock.Web.Cache.ItemCache<T>.GetOrAddExisting(int, System.Func<T>, System.Func<System.Collections.Generic.List<string>>)      | 42464 (58.71%)      | 3 (0.00%)          | rock              | Database          |
| 40  | \------------------------------------- + Rock.Web.Cache.ItemCache<T>.GetOrAddExisting(string, System.Func<T>, System.Func<System.Collections.Generic.List<string>>)  | 42447 (58.68%)      | 1 (0.00%)          | rock              | Database          |
| 41  | \-------------------------------------- + Rock.Web.Cache.EntityCache<T, T>.Get.AnonymousMethod__0()                                                                  | 39540 (54.66%)      | 5 (0.01%)          | rock              | Database          |
| 42  | \--------------------------------------- + Rock.Web.Cache.EntityCache<T, T>.QueryDb(int, Rock.Data.DbContext)                                                        | 39322 (54.36%)      | 2 (0.00%)          | rock              | Database          |
| 43  | \---------------------------------------- + Rock.Web.Cache.EntityCache<T, T>.QueryDbWithContext(int, Rock.Data.DbContext)                                            | 33664 (46.54%)      | 8 (0.01%)          | rock              | Database          |
| 44  | \----------------------------------------- - Rock.Data.Service<T>.Get(int)                                                                                           | 17307 (23.93%)      | 7 (0.01%)          | rock              | Database          |
| 45  | \----------------------------------------- - Rock.Web.Cache.AttributeCache.SetFromEntity(Rock.Data.IEntity)                                                          | 16245 (22.46%)      | 13 (0.02%)         | rock              | Database          |

### Expected Behavior

Rock IIS server should start up in approximately one minute (on par with previous version).

### Actual Behavior

Rock IIS server takes ten to fifteen minutes to start.

### Steps to Reproduce

Restart Rock (V14).

### Rock Version

14.2

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@SteveSwaringen  Do you have the ability to pull down either the `hotfix-1.14.3` branch or the new `release-1.15.0` (currently in alpha) (or even `develop`) to see if you are seeing the same issue there?  We recently made some significant changes to the code in those branches which some of the team thinks should resolve that issue you're describing.

**Comment by SteveSwaringen** [comment]
Absolutely. I’ll give that a try.

**Comment by SteveSwaringen** [comment]
@nairdo , Yes! I pulled hotfix-1.14.3 and merged it into our code. Running in Visual Studio against a sandbox DB, startup time dropped from 15 minutes to under 2.5. I expect that to drop further when I'm not running in VS (where latency to the SQL server seems to be the major bottleneck) and the IIS side is running on server-grade hardware.

I'll start working on an internal release of this configuration. Is there any word on when the hotfix-1.14.3 branch will be locked down?

In the meantime, consider this resolved.

**Comment by nairdo** [comment]
> Is there any word on when the hotfix-1.14.3 branch will be locked down?

Right now we're really only focusing our efforts on v15.0 which just started Alpha Testing last week (and it has all the v14.3 fixes).  So it's unclear if/when we would release v14.3.  It will depend on other circumstances.  However we will likely lock/freeze `release-1.15.0` as soon as it gets to Beta.
