### ISSUE TITLE
Obsidian Registration forcing Minimum Initial Payment

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#5376]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

While using the Obsidian Registration Block if a guest has a payment that is less than the 'minimum initial payment' (specifically testing when using a discount code)... The guest will see _on screen_ the correct amount but they will be charged the full _minimum initial payment_

**Amount Due Screen**
<img width="1113" alt="Amound Due Screen" src="https://user-images.githubusercontent.com/41912840/230241132-0582c51a-4132-49d5-bcd1-a5fc2d32ead9.png">

**Card Payment Screen**
<img width="1103" alt="Card Payment Screen" src="https://user-images.githubusercontent.com/41912840/230241166-f3b78c78-19f9-47dd-a493-8225cae41922.png">

**Congratulations Screen**
<img width="1293" alt="Congratulations Screen" src="https://user-images.githubusercontent.com/41912840/230241271-6bc385d3-8bba-41be-a59e-0c3b6ad01d85.png">

**Bank Statement**
![Bank Statement](https://user-images.githubusercontent.com/41912840/230241257-d098b77b-c00e-45a2-8432-37f3f19db36a.jpg)

**Registration Instance**
<img width="1129" alt="Registration Instance" src="https://user-images.githubusercontent.com/41912840/230241312-9dc96587-db0e-4891-9348-a0c32254607c.png">

### Expected Behavior

- Minimum Initial Payment is $150
- Registration Cost is $225
- Discount is $200

I would expect the guest is billed $25

### Actual Behavior

- Minimum Initial Payment is $150
- Registration Cost is $225
- Discount is $200

The guest is billed $150

### Steps to Reproduce

1. Build a New Event Registration
2. Set the Minimum Initial Payment to $150
3. Set the Registration Cost at $200
4. Build a Discount Code allowing $175 off the registration
5. Sign into the external site as a guest
6. Start a registration (ensure you are using the Obsidian Block)
7. Use the provided discount code for $175 off your registration
8. Notice the on screen prompts
9. Pay your $25 balance
10. Note your final payment of $150

### Rock Version

1.14.2.1

### Client Culture Setting

en-US

**Comment by ethan-sparkdevnetwork** [comment]
This was fixed in 14.3 with commit fc1e6bc6.
