### ISSUE TITLE
[Alpha v15.0] Sign-Up Finder block ignores "Display Project Filters As" setting

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5382]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

On the new Sign-Up Finder block, if you set the `Display Project Filters As` setting to `Multi-Select Dropdown`, the filters still show as individual checkboxes vs a multi-select dropdown. 
![bugforcheckboxes](https://user-images.githubusercontent.com/66277785/231258179-bc391c33-aaac-4acb-9c08-6af1b5f78c7c.gif)

### Expected Behavior

I would expect that when the block is set to display the project filters as a `Multi-Select Dropdown`, that the filters on the page would be a dropdown control that allows multiple values that is enhanced for long lists.

### Actual Behavior

The filters render as checkboxes regardless of what the `Display Project Filters As` block setting is set to.

### Steps to Reproduce

This can be reproduced on the prelpha site.
- Go to the /Signups page
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/66277785/231258747-f6384122-fe45-4d4d-986a-ba5d5beec1e3.png">

- Edit the block settings, and adjust the following
   - `Display Project Filters As` > set to `Multi-Select Dropdown`
   - `Display Attribute Filters` > `Project Type (Sign-Up Group)` checked
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/66277785/231259081-e067fc71-d03f-4b18-b1d9-d23cfe16939c.png">

- Save the block settings and refresh the page
- Notice the `Project Type` filter is still set for checkboxes

### Rock Version

Rock McKinley 15.0 (1.15.0.16)

### Client Culture Setting

en-US

**Comment by leahjennings** [comment]
After discussion with @nairdo, the intent of that setting just wasn't clear. What I had expected is considered an enhancement. The solution here is to clarify the purpose and function of that block setting in the tooltip and documentation so it isn't misinterpreted moving forward.

**Comment by nairdo** [comment]
We also updated (https://github.com/SparkDevNetwork/Rock/commit/d16df844872791924817fc5b2ca774e4225dae6c) the block to make the help text on that setting more clear  and it now reads:

>  Determines if the "Project Types", "Campus", and "Named Schedule" project filters should be shown as checkboxes or multi-select dropdowns.
