### ISSUE TITLE
ContentChannel.ChildContentChannels Lava property is not available using Fluid

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/Rock#5389]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

The `ChildContentChannels` property of the ContentChannel model is no longer available in the Fluid Lava engine, despite being listed on the Model Map. 

Prior to switching over to Fluid, I was not able to access the property using dot notation, but I was able to access it with the Property filter. After migrating to Fluid, I am no longer to access it using either method.

Brian Davis and I ran some tests (see steps to reproduce) on various Rock configs and found the following:

v7.6 DotLiquid:
- Debug Filter: fail
- Dot Notation: fail
- Property Filter: pass

v12.9 DotLiquid:
- Debug Filter: fail
- Dot Notation: fail
- Property Filter: pass

v13.7 DotLiquid:
- Debug Filter: fail
- Dot Notation: fail
- Property Filter: pass

v13.7 Fluid:
- Debug Filter: fail
- Dot Notation: fail
- Property Filter: fail

v14.0 DotLiquid:
- Debug Filter: fail
- Dot Notation: fail
- Property Filter: pass

v14.0 Fluid:
- Debug Filter: fail
- Dot Notation: fail
- Property Filter: fail

v14.2 DotLiquid:
- Debug Filter: fail
- Dot Notation: fail
- Property Filter: pass

More details can be found in this Rock chat thread: https://chat.rockrms.com/channel/lava?msg=YDTi4cA8GrEnKTtBF

### Expected Behavior

Assuming the Model Map is correct, the `ChildContentChannels` property should be available using either dot notation or the `Properties` filter, and should be listed when using the `Debug` filter on the Content Channel.

### Actual Behavior

The `ChildContentChannels` property is not available using either dot notation or the `Properties` filter, and is not included when using the `Debug` filter on the Content Channel.

### Steps to Reproduce

1. Using a Rock instance that is running the Fluid engine and still has the built in "Messages" and "Message Series" content channels
2. Run the following Lava either in an HTML block or using the Lava Tester: 
```
{% contentchannel id:'4' %}
    {{ contentchannel | Debug }}
    Dot Notation: {{ contentchannel.ChildContentChannels | Size }}<br>
    {% assign childChannels = contentchannel | Property:'ChildContentChannels' %}
    Property Filter: {{ childChannels | Size }}
{% endcontentchannel %}
```
3. Notice that the Debug output does not include `ChildContentChannels` and both of the size outputs are `0`, even though the specified content channel has one child channel.

### Rock Version

13.7 (Fluid)

### Client Culture Setting

en-US

**Comment by nlBayside** [comment]
In regards to the Model Map block, I think this property shows up as accessible via Lava because of this line: https://github.com/SparkDevNetwork/Rock/blob/96551bbf6754c6223d70876235cdba86ffea9e51/RockWeb/Blocks/Examples/ModelMap.ascx.cs#L384

In ContentChannel.cs, the property is tagged with three attributes:
https://github.com/SparkDevNetwork/Rock/blob/96551bbf6754c6223d70876235cdba86ffea9e51/Rock/Model/CMS/ContentChannel/ContentChannel.cs#L279

```csharp
/// <summary>
/// Gets or sets the collection of ContentChannels that this ContentChannel allows as children.
/// </summary>
/// <value>
/// A collection of ContentChannels that this ContentChannel allows as children.
/// </value>
[DataMember, LavaHidden, JsonIgnore]
public virtual ICollection<ContentChannel> ChildContentChannels
{
    get { return _childContentChannels ?? ( _childContentChannels = new Collection<ContentChannel>() ); }
    set { _childContentChannels = value; }
}
```

Since it has the DataMember Attribute, it would be considered Lava accessible. Maybe there should be a change in the Model Map's code to say "Is Data Member and is not LavaHidden"?
