### ISSUE TITLE
[Alpha v15.0] Obsidian Attendance Detail Never Launches a WF When Configured on the Block

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5392]
### Please go through all the tasks below

- [ ] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When a WF is configured on the block setting on the Obsidian Attendance Detail block, the Workflow never actually fires. The tooltip says it launches when the WF is saved, however the attendance seems to be updated in realtime with the new block vs having a "save" button.
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/66277785/231859410-4e55f7ee-bc1e-4d72-9274-7f21881a6242.png">

The workflow is configured on the block, but workflows are never launched:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/66277785/231875382-0679d570-7c6b-422a-b6d2-95d95ff62cfe.png">

### Expected Behavior

This one's tricky...because the attendance is saved in realtime because of the Obsidian capabilities. We've (organizationally) never had a use case before that would require a workflow to be launched there, since the old block sent attendance summary emails to specified individuals. However, since the Obsidian block doesn't have the ability to send attendance summaries, I could see the workflow setting to be used in that way.

I would expect that the workflow be launched once for whenever someone is done taking attendance - which is much harder to know when that is now. Maybe it's possible to know when the connection is closed, i.e. they browse away from that page or they close the window? Otherwise the workflow would be initiated _each time_ someone updates the attendance, which may not be ideal.

Something else I could see expected is for there to be a time delay, i.e. 10 seconds after the last change and last activity to go ahead and launch it then. 

### Actual Behavior

Once a workflow is configured on the block, the workflow never launches:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/66277785/231875382-0679d570-7c6b-422a-b6d2-95d95ff62cfe.png">

### Steps to Reproduce

- On a server running Rock v15, navigate to the Group Toolbox > Group Attendance > Group Attendance Detail page
- Edit the block and add a workflow
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/66277785/231882349-bf9e3290-1279-478c-9f30-01d82edbaa88.png">

- Take attendance on a group from that Obsidian block
- Notice how the workflow is never launched

### Rock Version

Rock McKinley 15.0 (1.15.0.16)

### Client Culture Setting

en-US

**Comment by ethan-sparkdevnetwork** [comment]
The workflow setting was removed from the block in commit d2cbb5e2.
