### ISSUE TITLE
[Alpha 15.0] - Exception log is empty, even though jobs are causing exceptions

### ISSUE THREAD

**Issue by tbunney** [SparkDevNetwork/Rock#5394]
### Description

I upgraded my sandbox environment from 14.3 to 15.0. This is the same environment we always use for testing. After I updated I ran the Rock Cleanup job and it got stopped on Rock Exceptions. The job ran for 2 days, and never moved. I went to the Exception List and there was nothing in there. Needless to say, we stopped the job, but now when I am running other jobs that are giving me messages to "See the inner exception for details", I go to the Exception List and there is nothing there. I compared the settings to our production environment and they are the same. All the blocks are Core.

### Steps to Reproduce

1. Run the Rock Cleanup job.
2. Run something else that causes an inner exception
3. Go to the Exception List to see if it there.

**Expected behavior:** 

An exception will be dropped into the exception list.

**Actual behavior:** 
A job shows an error with an inner exception.
![error](https://user-images.githubusercontent.com/37702418/232047662-376bf270-fd8e-4f1c-8e41-57d10978587d.PNG)

But when you go to the exception list page, it has nothing listed.
![Empty_Exception_List](https://user-images.githubusercontent.com/37702418/232047320-47d92a5d-b0e8-4471-850c-111b205d9546.PNG)

### Versions

* **Rock Version:** Rock McKinley 15.0 (1.15.0.16)
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
This looks to have been environment related as even queries single row select queries were getting the error.
