### ISSUE TITLE
Obsidian Attribute Matrix Control Displaying as Text Box Control

### ISSUE THREAD

**Issue by Jon-Corey** [SparkDevNetwork/Rock#5397]
## Please go through all the tasks below

* [x] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
When adding an Attribute Matrix to a registration and viewing the registration on the Obsidian Registration Entry Block, the Attribute Matrix is displayed as a Text Box Control instead of as an Attribute Matrix Control.When viewed on the C# Registration Entry block, the Attribute Matrix is displayed correctly.Attribute Matrix on the Obsidian Registration Entry block:

![ObsidianMatrixObsidianBlock](https://user-images.githubusercontent.com/110615344/231818298-206c1f89-f683-45f3-9d63-a9df15713d06.png)Attribute Matrix on the C# Registration Entry block for comparison:

![ObsidianMatrixC#Block](https://user-images.githubusercontent.com/110615344/231818329-266b209f-ca8f-4af3-b618-69dd3816d76a.png)## Expected Behavior
Attribute Matrices in Obsidian blocks should be displayed in a similar way to the way they are displayed in C# blocks. Attribute Matrices should be editable in a practical way on Obsidian blocks.## Actual Behavior
Attribute Matrices in Obsidian Blocks are displayed as a Text Box Control. This makes it practically impossible to accurately add a value or modify an existing value.## Steps to Reproduce

1. Create a registration template
1. On the first form of that template, add a registrant attribute with the following configurations:
  * Field Type: Matrix
  * Attribute Matrix Template: Internal Article List (or any other - this is just a good built-in example)
1. Create an instance of the registration
1. Go to a page with the Obsidian Registration Entry block with the registration instance id in the URL as a page parameter
1. Select any number of registrants and hit "Next"
1. Notice how the Attribute Matrix is shown as a Text Box Control

## Rock Version
14.3 (Although this is an issue from v13 - present)## Client Culture Setting
en-US

**Comment by jonedmiston** [comment]
Just adding a note to this. We don't have all of the Rock Field Types converted to Obsidian yet. The Matrix attribute is one of the few left. Once that is complete this will start working.

**Comment by joezimjs** [comment]
Hello @Jon-Corey,

Yes, Jon is right. We're still working our way through Obsidian field types, so this was expected. However, you'll be happy to know that this has been fixed in https://github.com/SparkDevNetwork/Rock/commit/f4be67a31875a953a6d6b46668096e683e7d5294 for v17.
