### ISSUE TITLE
Obsidian Registration Pre/Post HTML is not Hidden when Control is

### ISSUE THREAD

**Issue by Jon-Corey** [SparkDevNetwork/Rock#5399]
## Please go through all the tasks below

* [x] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
Attributes in registrations can have Pre-HTML and Post-HTML. Attributes can also be filtered so that they only show on the form when a condition is met. The Obsidian Registration Entry block does not hide the attribute's Pre/Post HTML when the attribute is hidden. It always shows the Pre/Post HTML. This is inconsistent because both the C# Registration Entry block and the C# Workflow Entry block hide the attribute's Pre/Post HTML when the attribute is hidden.Pre and Post HTML on the Obsidian Registration Entry block (the Pre/Post HTML is shown even though the attribute they are attached to is hidden):

![PrePostHtmlObsidianBlock](https://user-images.githubusercontent.com/110615344/231819542-bdcb294e-8a3f-4327-9264-bea807e50ef8.png)Pre and Post HTML on the C# Registration Entry block for comparison (the Pre/Post HTML is hidden because the attribute they are attached to is hidden):

![PrePostHtmlC#Block](https://user-images.githubusercontent.com/110615344/231819526-57555801-f1c7-4a92-9f1c-a567d0f3ddd1.png)## Expected Behavior
On the Obsidian Registration Entry block, the visiblility of an attribute's Pre/Post HTML should be dependent on the visibility of the attribute itself.## Actual Behavior
On the Obsidian Registration Entry block, all attributes' Pre/Post HTML is always visible, regardless of if the attribute they are attached to is visible.## Steps to Reproduce

1. Create a registration template
1. On the first form of that template, add a registrant attribute with the following configurations:
  * Field Type: Boolean
1. Add another registrant attribute with the following configurations:
  * Field Type: Text
  * Pre-HTML: `<h3>Pre HTML</h3>`
  * Post-HTML: `<h3>Post HTML</h3>`
1. On the text attribute, add a field filter that shows the Text field if the Boolean field is "Yes"
1. Create an instance of the registration
1. Go to a page with the Obsidian Registration Entry block with the registration instance id in the URL as a page parameter
1. Select any number of registrants and hit "Next"
1. Notice how the "Pre HTML" heading and the "Post HTML" heading are shown even when the Text field is not

## Rock Version
14.3 (Although this is an issue from v13 - present)## Client Culture Setting
en-US

**Comment by joezimjs** [comment]
Thanks @Jon-Corey for getting this started.
