### ISSUE TITLE
Group Schedule Toolbox Cancel Confirmation Prompts Are Ambiguous

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5404]
## Please go through all the tasks below

* [x] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
![image](https://user-images.githubusercontent.com/54962439/232624970-1059ec97-65ae-497b-a53d-baa6cf48369e.png)

Users are prompted with two buttons when attempting to cancel a serving confirmation. One button reads "Decline", the other reads "Accept". End users may think the following about each button:Decline Button

1. Yes I decline this commitment, please cancel my confirmation to serve.
1. I didn't mean to click cancel confirmation; I want to decline/undo the action I just took.

Accept Button

1. I didn't mean to click cancel confirmation; I still want to serve.
1. I really did mean to click the cancel confirmation button, please cancel my confirmation to serve.

## Expected Behavior
Button with text that is less ambiguous or no confirmation at all. It already takes two clicks to cancel a confirmation from Group Schedule Toolbox.

## Actual Behavior
Buttons with ambiguous language are presented when after a user clicks "Cancel Confirmation".

## Steps to Reproduce
On the demo site

1. Add Alisha Admin to Ushers Serving Team
1. Sign Alisha up for a Serving Slot
1. ![image](https://user-images.githubusercontent.com/54962439/232624535-2f6827d8-4ad5-42a3-96c1-4d5fd8b6f312.png)
1. Cancel Alisha's commitment to serve via the Cancel Confirmation Link
1. ![image](https://user-images.githubusercontent.com/54962439/232624776-333d35b5-4404-44b4-982d-89add7460d50.png)
1. See Ambiguous Options
1. ![image](https://user-images.githubusercontent.com/54962439/232624945-d501366a-c563-4412-944f-0978ba67056b.png)

## Rock Version
Rock McKinley 14.2 (1.14.2.1)

## Client Culture Setting
en-US

**Comment by dataCollegechurch** [comment]
Rock community members can help classify or confirm this issue here: https://community.rockrms.com/Contribute/Issues
Cheers! TTFN.

**Comment by nairdo** [comment]
@dataCollegechurch  Just FYI... There are plans underway to work on this block with some updated functionality (multiple groups will appear as tabs instead of one giant list), but we've not had no other comments about changing the terms used in the two buttons use to Accept or Decline the serving/scheduling invitation.  So, I would ask that you open this up as an idea on the [Community Ideas Board](http://community.rockrms.com/Ideas) so others can vote on your suggestions.

**Comment by zackdutra** [comment]
I just had a user call me with this issue, the labels were confusing for him and he wasn't sure which to click.

**Comment by chead4** [comment]
@zackdutra Hi Zack - Please reach out to Tony Visconti (dataCollegechurch) regarding the Community Idea URL created for this request, as I couldn't find the idea myself.  Once you have the idea , I'd ask you to jump over to the idea and vote it up.  Additionally, feel free to add any comments for the person who reached out to you.  Voting for an idea allows the community to speak to an idea and helps us determine its priority.

**Comment by dataCollegechurch** [comment]
While this seemed like a bug to me, I didn't feel it rose level of importance of adding an idea to the community board. I have not entered an idea at this point.

**Comment by chead4** [comment]
@zackdutra Hi Zack - Tony commented that he didn't create an idea for this request. I would suggest that you consider opening this up as an idea on the [Community Ideas Board](http://community.rockrms.com/Ideas) so others can vote up your idea.

**Comment by zackdutra** [comment]
@chead4  Similar to Tony, I feel this is a simple issue to fix, but does not warrant an idea. I’ll leave it alone for now. We have bigger issues to use votes on.
