### ISSUE TITLE
When adding a phone number that already exists to a profile,  "Mobile Phone Messaging Enabled" is changed to False

### ISSUE THREAD

**Issue by loganhnry** [SparkDevNetwork/Rock#5405]
## Please go through all the tasks below

* [x] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
If someone signed in updates their account or gives using the Transaction Entry block (with Prompt for Phone enabled) and enters a phone number that already exists on their profile, their profile history immediately records them as deleting the duplicate phone number, as well as changing "Mobile Phone Messaging Enabled" to False. 

## Expected Behavior
I expected the profile to be double-checked and find the account already had that number, and dis-regard it as pre-existing, AND respecting the previous state of the "Mobile Phone Messaging Enabled" value.

## Actual Behavior
The account's profile history immediately records them as deleting their phone number, as well as changing "Mobile Phone Messaging Enabled" to False. The profile history shows it modifying multiple phone values, as well as un-checking the "Mobile Phone Messaging Enabled" box.  I included screenshots from the demo server after a transaction entry was made.

![](https://user-images.githubusercontent.com/26261482/232842371-a3a7c0d8-3335-481b-ba7d-67bd4ce3f06a.png)

![](https://user-images.githubusercontent.com/26261482/232842374-d7a1c6c3-c5ca-4262-8e49-22a6c5c91a8b.png)Thanks to a conversation in chat, I found this bug report that turned out to be a feature to prevent duplicate phone numbers, but I believe this "Mobile Phone Messaging Enabled" setting was overlooked:

https://github.com/SparkDevNetwork/Rock/issues/4263

## Steps to Reproduce
I was able to reproduce on the demo server after enabling phone number entry in block settings. After adding a SMS Enabled phone number to Alisha Admin's profile and browsing the external site logged in as Alisha, the results were reproduced in these ways: 
1) Making a mock donation on the Give page while including the Mobile phone number 
2) Visiting the external "My Account" page and updating Alisha's account with the same Mobile phone number to Home or Work
3) Visiting Alisha's Rock profile page and updating her profile's Home or Work numbers to the Mobile phone number After all of these examples, viewing the profile inside Rock, the History tab now shows Alisha making demographic changes to her phone numbers, and changing "Mobile Phone Messaging Enabled" to false.

1. The SMS box is now un-checked in her profile's settings.

## Rock Version
14.2

## Client Culture Setting
en-US

**Comment by Kwame-Agyei** [comment]
This issue has been fixed by [this commit](https://github.com/SparkDevNetwork/Rock/commit/426387adb162469fe062fe0d452c21a08d169cc1) to the Utility Payment Entry block which replaces the Transaction Entry Block.

**Comment by Kwame-Agyei** [comment]
This issue has been fixed by [this commit](https://github.com/SparkDevNetwork/Rock/commit/426387adb162469fe062fe0d452c21a08d169cc1) to the Utility Payment Entry block which replaces the Transaction Entry Block.
