### ISSUE TITLE
Obsidian Registration Block - External Payment Breaks Group Linkage

### ISSUE THREAD

**Issue by tikool17** [SparkDevNetwork/Rock#5409]
### Prerequisites
* [] Put an X between the brackets on this line if you have done all of the following:
    - Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? (No, an External Payment Processor Required)
    [x] - Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    [x]  -Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
We use Pushpay as payment processor for the Obsidian block. We have linkages set up to add people to groups upon registration. This works fine if payment is not required and they are added to the groups through the linkage. However, when payment is required, the block redirects them to a Pushpay-hosted page to complete payment. Once complete, it redirects back to a Rock registration confirmation page. The person is added to the registration, but NOT added to the group. If you go into the details for the registrant you'll find the Target Group field is blank.

### Steps to Reproduce

1. Create a registration with a Linkage to a Group
<img width="1283" alt="Screen Shot 2023-04-19 at 1 32 33 PM" src="https://user-images.githubusercontent.com/32227063/233161015-58c7b2ed-2ad2-45ec-ad89-89c821e02dba.png">

2. Register for the event on the Obsidian block using the URL slug link
<img width="1215" alt="Screen Shot 2023-04-19 at 1 38 28 PM" src="https://user-images.githubusercontent.com/32227063/233161098-66018b91-2ed2-43ab-a8cc-3bf9a446f7f3.png">

3. For Payment, you're redirected to a Pushpay-hosted payment page. Once complete, you're returned to a Rock confirmation page.
<img width="1114" alt="Screen Shot 2023-04-14 at 10 36 12 AM" src="https://user-images.githubusercontent.com/32227063/233161875-ae99b0d4-9c2a-4e73-a20e-8573113ebdd8.png">

4. The person is registered for the event successfully. But when you check the registrant details, no Target Group is applied. They are not added to the group.
<img width="1270" alt="Screen Shot 2023-04-19 at 2 06 15 PM" src="https://user-images.githubusercontent.com/32227063/233163754-21536c97-c69b-4b94-a405-94572a8eaa8e.png">

**Expected behavior:** 

Registrants are added to groups that are specified in the linkage when payment is required, just like is the case when payment is not required.

**Actual behavior:** 

When payment is required, registrants are not added to the groups.
If no payment: The URL remains the same throughout registration with slug included, like: https://rock.rocksolidchurchdemo.com/regobsidian?RegistrationInstanceId=1&Slug=test-slug

On return from payment on the Pushpay-hosted page, the url changes, like:
https://rock.rocksolidchurchdemo.com/regobsidian?paymentToken=6iGr6dHhGkc_CLiwr0hcBg&sr=sessionGuid%3A4144cdde-5963-4450-ad20-2b12d6715e27

My guess is something in that return URL isn't passing through the needed info for Rock to respect the slug and linkage.

### Versions

Rock Version: Rock McKinley 14.1 (1.14.1.1)
Client Culture Setting: en-US

**Comment by IzabellaDTS** [comment]
Hello @nairdo! Requesting that this bug be re-opened.

My client uses PushPay as their payment processor for Event Registrations, and currently use the Obsidian Registration Entry block. It was brought to my attention that a registration with a linkage was not properly adding registered individuals to the group defined in the linkage.

Upon further investigation I noticed that individuals who were staff who had a 100% discount (and therefore did not have to pay the registration's cost) were the only individuals who were successfully added to the group.

From here I tested various scenarios, and all scenarios where the user **did not** have to pay resulted in the linkage working and all scenarios where the user **did** have to pay (and were consequently redirected outside of Rock to a PushPay-hosted page) resulted in the linkage not working.

Rock Version: Rock McKinley 17.6 
Client Culture Setting: en-US

**Comment by nairdo** [comment]
@IzabellaDTS Thank you for letting us know.  It is now on our list to reinvestigate so I am opening this until we have the chance to verify.

**Comment by azturner** [comment]
@nairdo , We've seen same issue and here's what we found when stepping through code:

When the RegistrationEntry block uses a redirect payment gateway, it stores some values in session before redirecting to the gateway. If the event is accessed via a slug, the slug is saved to session. The block also calls GetRegistrationGroupId, which calculates a GroupId from the slug and saves that to session as well. After the user completes payment and returns, Rock rebuilds an internal query string from session values. At this point, the query string includes both the slug and the GroupId. The block then calls GetRegistrationGroupId again to determine which group to add the registrant to. In v16.13, v17.6, and v18 GetRegistrationGroupId was changed so that if a GroupId exists in the query string, the method returns null. As a result, the first call (slug only) returns a valid GroupId, but the second call (slug + GroupId) returns null. This prevents the GroupId from being saved on the registration, so the registrant is not added to the group.

**Comment by kimlongcr** [comment]
@nairdo This is an issue for Crossroads as well (v17.6.1). We have lots of events right now with 1,000's of people signing up where this is failing. And, another event will be going live at the end of February.

**Comment by nairdo** [comment]
@azturner @kimlongcr Thank you both for this additional information.  We do have it in our list now to address/correct.

**Comment by nairdo** [comment]
@IzabellaDTS, @kimlongcr , @azturner We are including this fix in both v18.2 (currently in alpha) and -- a v17.7 which will _only include this one fix_.  More details will be posted to the RockStars channel, but I wanted to give you a quick notice here too.
