### ISSUE TITLE
CRM > PersonDetail > Groupmember Feature

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#5410]
## Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

## Description
Our organization likes to keep groups around.  We are averse to "Archiving" certain types of groups because we may want to research for pastoral reasons the history of an individual.  So we typically just Inactivate a group.The problem happens on the Person Profile page.  The CRM > PersonDetail > Groupmember Block shows ALL groups of a Grouptype that are not archived.  It also does not distinguish anyway visually an active or inactive group so it can get pretty confusing if you leave inactive groups laying around pretty quickly.Our simple solution is to add a toggle to the block of "Show Inactive Groups" Yes/No. This allows flexibility on the organization's part to choose to show or not show inactive groups for a particular Grouptype.I have written the C# code to make this change already and can send it over as a pull request if we are okay with this concept as a new feature/improvement.

## Steps to Reproduce
1. Create two groups of a group type that is added to the profile page
1. Add the person to both groups as a groupmember
1. Inactivate one group
1. See both groups still on the profile page

**Expected behavior:**
We would show "All" groups if they have "Yes" for show inactive groups, and only show "Active" groups if they have set "No" for show inactive groups.  Default would be "Yes" for the block so that it does not change any current settings baked into the block.

## Versions

* **Rock Version:** [14.1]
* **Client Culture Setting:** [EN-US]

**Comment by markewampler** [comment]
[GroupMember.txt](https://github.com/SparkDevNetwork/Rock/files/11834955/GroupMember.txt)

Added lines:
----
    [BooleanField(\
        "Show Inactive Groups",\
        Key = AttributeKey.ShowInactive,\
        Description = "Should Inactive groups be displayed?",\
        DefaultBooleanValue = true,\
        Order = 1)]\
----
            public const string ShowInactive = "ShowInactive";\

----

      _showInactive = GetAttributeValue(AttributeKey.ShowInactive).AsBoolean();\

----

			m.Group.IsActive == false && _showInactive == true))\

**Comment by nairdo** [comment]
@markewampler  Thanks for letting us know about this.  I hope it's ok, but we'd like to run with your idea.  We will extend to also cover _archived_ groups and inactive/archived group member.  We'll also be flipping the setting to default _false_ with a name of `Hide Inactive/Archived Groups` so as to not break our internal 'default-false' rule.

**Comment by markewampler** [comment]
@nairdo Sounds good to us.  We just had too may people want to dig into history and an archived group is much more painful to look at than an inactive group.

**Comment by nairdo** [comment]
@markewampler Can you confirm the "Limit to Active Status" block setting on your system also resolves this problem?

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/5c0e33e3-4775-4faf-b13b-dfaeb7ff1cb9)

Regardless, we've also adjust the code in v15.2/v16.0 to better handle inactive group members (in addition to inactive groups) and archived groups/groupmembers.

**Comment by markewampler** [comment]
There may have been a misunderstanding of what our issue was.  

Ours is the CRM > Person Detail > GroupMembers was the block we were referencing where we need the flag for Inactive/Active on groupmembers that show up in the block.

The above is helpful too though as it declutters that block be default for us if we want.

<img width="196" alt="Screenshot 2023-08-29 at 8 32 53 AM" src="https://github.com/SparkDevNetwork/Rock/assets/33845027/5e5c5384-0495-4f9f-88e8-5014e320936f">

**Comment by markewampler** [comment]
@nairdo An example on the demo site:

<img width="1615" alt="Screenshot 2023-08-29 at 8 40 44 AM" src="https://github.com/SparkDevNetwork/Rock/assets/33845027/9e31afea-3693-4779-9cf2-897cfaad1724">

**Comment by nairdo** [comment]
@markewampler  Thanks for that important clarification.  That would be a great idea for the [Ideas board](https://community.rockrms.com/Ideas).  I would say it is classified as a 'small' project so do let us know on the form if you guys are open to helping fund that.

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/62d3ecb8-9160-4aef-ba69-c2120b1b3a65)

**Comment by markewampler** [comment]
@nairdo Should I submit it that way even if I have the code to do it?  We implemented it on our staging server successfully.  Just trying to understand what the protocol is for those types of things.

**Comment by bjacky** [comment]
@nairdo I upgraded to Rock 15.5 recently and have encountered this change. I am not seeing a way to get the same listing as before from the Group List block. Is it possible to still see a Group List that includes all groups a person is currently a member of regardless of their current active/inactive group member status while excluding groups they belonged to in the past?
