### ISSUE TITLE
Reverse Lava Filter

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5411]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

This may not be a bug, but I figured I would open one just in case. 

Consider the following Lava:
```
{% assign yearsArray = '2019,2020,2021,2022,2023' | Split:',' | Reverse %}

{{ yearsArray }}
```
The returned results are `20232022202120202019`, which is the array in reverse order (which is correct).

However, I am not sure if `Reverse` is actually valid Lava because a) I cannot find it in the Lava documentation and b) the text color is not light blue like all other Lava Filters. But it does work. 

### Expected Behavior

If `Reverse` is a valid lava filter, I would expect to see it in the Lava Documentation and/or have the text color change to light blue like all other Lava Filters.

### Actual Behavior

It is not in the Lava Documentation and the text color does not change to light blue like all other Lava Filters.

### Steps to Reproduce

Use this code in an HTML block:
```
{% assign yearsArray = '2019,2020,2021,2022,2023' | Split:',' | Reverse %}

{{ yearsArray }}
```

See that it works, but the filter's text color is not light blue.

### Rock Version

v14.2, v15.0

### Client Culture Setting

en-US

**Comment by nlBayside** [comment]
I don't think this is a valid Lava Filter, or at least not one custom made for Rock. I couldn't find any reference to a "Reverse" filter in [LavaFilters.cs](https://github.com/SparkDevNetwork/Rock/blob/2380bf37882086c66616a7352f0a888e4825a373/Rock/Lava/Filters/LavaFilters.cs), except for matching partially in "FullNameReversed", but that's not a filter.

You can loop through a list in reverse order with the keyword "reversed".
So you could type (Straight from the docs):
```
{% for campus in Campuses limit:2 offset:1 reversed %}
    {{ campus.Name }}
{% endfor %}
```
This isn't an assignment operation though. So you could loop through and create a new list from the reversed order, but I don't know if you can just call "reversed" by itself.

**Comment by JimMichael** [comment]
It is however a valid Liquid filter, so maybe Rock just inherits it from there and forgot to document it?

https://shopify.github.io/liquid/filters/reverse/

**Comment by jonedmiston** [comment]
Reverse comes from the liquid libraries (DotLiquid / Fluid). Looks like it was added to DoLiquid 2 years ago and we didn't catch it when we updated. We'll get it added.

**Comment by mikedotmundy** [comment]
Awesome! Thank you @jonedmiston!

**Comment by mikedotmundy** [comment]
Just wanted to add that the Lava Documentation is slightly off on this. 

It is missing the capitalization for `Split`, `Reverse`, and `Join`.

Currently reads:
```
{% assign my_array = "apples, oranges, peaches, plums" | split: ", " %}

{{ my_array | reverse | join: ", " }}
```

Should read:
```
{% assign my_array = "apples, oranges, peaches, plums" | Split: ", " %}

{{ my_array | Reverse | Join: ", " }}
```

**Comment by garrettjohnson** [comment]
@mikedotmundy  Updated [the Lava Documentation](https://community.rockrms.com/lava/filters/array-filters). Thank you
![image](https://github.com/SparkDevNetwork/Rock/assets/374209/86d9ee3c-6ac0-426d-badd-25a99c35b3c2)
