### ISSUE TITLE
Sign-Ups Finder Block settings unavailable on internal website

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/Rock#5412]
## Please go through all the tasks below

* [x] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
The Sign-Ups Finder block settings are unavailable if you want to make changes to the block settings using the internal Rock functionality (for editing block settings)## Expected Behavior
Block settings should be available on both the internal and external scenarios

## External
![Monosnap Signup Finder | JIMROCK The Crossing 2023-04-21 17-31-12](https://user-images.githubusercontent.com/8688424/233744140-34650e87-338d-4e49-b0e6-b55991f4e6e3.png)## Internal
![Monosnap Pages | JIMROCK Rock RMS 2023-04-21 17-33-45](https://user-images.githubusercontent.com/8688424/233744340-0a5073f1-90c5-4a47-a816-941dc80af0a5.png)## Actual Behavior
Block settings are not available on the internal site## External
![Monosnap Signup Finder | JIMROCK The Crossing 2023-04-21 17-31-12](https://user-images.githubusercontent.com/8688424/233744191-999df38f-1db3-415b-bc81-aeb82778f45b.png)## Internal
![Monosnap Pages | JIMROCK Rock RMS 2023-04-21 17-33-45](https://user-images.githubusercontent.com/8688424/233744340-0a5073f1-90c5-4a47-a816-941dc80af0a5.png)## Steps to Reproduce

* Go to 'CMS Configuration > Pages' and navigate to the page the Sign-Ups Finder block is on
* You can't select the _Block Settings_ icon

## Rock Version
15.0 (1.15.0.16)## Client Culture Setting
en-US

**Comment by jonedmiston** [comment]
Just a quick update... The Sign-up Block was written using the new Obsidian framework. These new blocks don't yet have a way to put custom configuration into the internal page configurator. We're working to have that in the future. Just wanted to post that tidbit here.
