### ISSUE TITLE
Alpha 1.15.0.16 - Sign-Ups Finder Can't Remove Registrant

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5413]
## Please go through all the tasks below

* [x] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
This may be more of a feature request, but in the new Sign-Ups Finder, when Registering, it would be more user-friendly to have the option to remove a registrant in the event you accidentally added too many. Currently, the only way to remove a registrant is to refresh the page, which clears all information you had entered on the previous registrant(s).![](https://user-images.githubusercontent.com/23226974/233757925-f6384b08-12bc-4ded-9b7a-74fe856908e8.png)If this is a feature request, let me know and I'll enter it on the ideas page.## Expected Behavior
I would expect a minus or X button allowing me to remove a registrant without refreshing the page.## Actual Behavior
You must refresh the page to remove a registrant.## Steps to Reproduce

* Register for a Sign-up
* Add an additional individual
* See you cannot remove additional individual

## Rock Version
v15.0, v16.0## Client Culture Setting
en-US

**Comment by chead4** [comment]
@mikedotmundy After reviewing, we will be closing this issue as it is an enhancement request. Please submit an idea on the Rock Community Ideas board via http://community.rockrms.com/ideas. This allows the full community to speak into it and help us determine it's priority.
