### ISSUE TITLE
Alpha 1.15.0.16 - Minor Typo on Sign-up finder block

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5414]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

On the new Sign-up Finder block, there is a minor typo on the tooltip for _Display Project Filters As_.

It should either read "...should show as..." or "... should be shown as...".

<img width="1175" alt="Screenshot 2023-04-21 at 22 55 08" src="https://user-images.githubusercontent.com/23226974/233758320-314190d0-480e-4537-b430-2c135d9e0f6b.png">

### Expected Behavior

It should either read "...should show as..." or "... should be shown as...".

### Actual Behavior

It actually reads "... should be show as...".

### Steps to Reproduce

- Go to sign up finder block
- Edit block settings
- See typo on tooltip

### Rock Version

v15.0

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/d16df844872791924817fc5b2ca774e4225dae6c.
