### ISSUE TITLE
Alpha 1.15.0.16 - Sign-ups Schedule not Set in Workflow Properly

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5415]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When using a Workflow with the new Sign-ups feature in v15, the `Schedule` is not assigned to a Workflow Attribute properly after a person registers.

Based on this screenshot below, I would assume Registrar, Group, Location, and Schedule are all passed into the Workflow in the same manner. 
<img width="299" alt="Screenshot 2023-04-22 at 14 30 13" src="https://user-images.githubusercontent.com/23226974/233800817-d131f861-c343-4b84-ac58-42341b1ed5c6.png">

For my example, I created a Workflow with those attributes and keys. 
<img width="1726" alt="Screenshot 2023-04-22 at 14 36 14" src="https://user-images.githubusercontent.com/23226974/233801005-bdd6b474-e3c5-4fef-8ae9-552c6af9fe81.png">

As you can see here, they all set properly except for the Schedule:
<img width="1727" alt="Screenshot 2023-04-22 at 14 26 52" src="https://user-images.githubusercontent.com/23226974/233800851-e4c636e1-c374-4918-83d4-369a754c19e1.png">

In this screenshot, I changed the Workflow's `Schedule` attribute from a Field Type _Schedule_ to a Field Type _Text_. You can see it is passing the Schedule's Guid in properly. 
<img width="1725" alt="Screenshot 2023-04-22 at 14 33 02" src="https://user-images.githubusercontent.com/23226974/233800944-2cbffc62-b8c4-451e-a270-47a85eaac63e.png">

So, the Workflow is being passed the Schedule's Guid, but it will not automatically set the Attribute when the Field Type is Schedule.

### Expected Behavior

I would expect that the Registrar, Group, Location, and Schedule are all passed into the Workflow and set in the same manner, meaning, if the attribute/key exists, it is automatically set.

### Actual Behavior

The Registrar, Group, and Location are all passed into the Workflow and set automatically, but the Schedule is not.

### Steps to Reproduce

- Create a Sign-ups Workflow similar to my screenshot above, or download this one: [Signups_202304221839.json.zip](https://github.com/SparkDevNetwork/Rock/files/11302061/Signups_202304221839.json.zip)
- Set the Workflow to launch when a person registers for a sign-up.
- Register for the Sign-up.
- See that the Workflow Attributes are all set except the Schedule.

### Rock Version

v15.0, v16.0

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@mikedotmundy Even though the schedule _appears_ to be blank, the data is actually there (as you've shown by using a Text field type instead of a Schedule field type).   So, you would be able to use that Schedule attribute value in your code/Lava/etc., but it's not ideal the way it is now (showing a blank value).

Since non-named schedules currently do not display a 'friendly name' when displayed, we're going to change the field type so it will show the Name (if it has one) or fall back to the 'friendly name' (something similar to 'Daily at 8:00 AM' or 'Sundays at 8:00 AM').  We're going to fix that in v15.1.

**Comment by mikedotmundy** [comment]
> ...we're going to change the field type...

What will the Field Type be? Will it be documented on the tooltip?

Thank you @nairdo!

**Comment by jasonhendee** [comment]
@mikedotmundy The Field Type will still be Schedule; we're simply going to ensure a friendly text is actually displayed in the case of non-named Schedules.

**Comment by mikedotmundy** [comment]
Awesome, thank you!
