### ISSUE TITLE
Alpha 1.15.0.16 - Typos on Process Reminders Job

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5417]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

There are several typos on some of the text and tooltips for the Process Reminders Job.

1. Description - not 100% sure, but I believe it should be 'and' not 'the'.
<img width="1726" alt="Screenshot 2023-04-24 at 12 30 00" src="https://user-images.githubusercontent.com/23226974/234059356-90b30aa6-3434-42b8-a666-83c1a5324010.png">

2. Reminder Types Include - Reminder is spelled incorrectly. 
<img width="1726" alt="Screenshot 2023-04-24 at 12 31 43" src="https://user-images.githubusercontent.com/23226974/234059641-a33b57c2-91d9-44aa-83b6-af0e17c3a430.png">

3. Reminder Types Exclude - I believe 'Group Types' should say 'Reminder Types'
<img width="1725" alt="Screenshot 2023-04-24 at 12 33 54" src="https://user-images.githubusercontent.com/23226974/234060163-f416a785-6cf0-44b8-a4cb-eb3f2299dd97.png">

4. Command Timeout - I am not entirely sure, but I don't think this help text applies to this job. It currently talks about metrics and SQL based metrics.
<img width="1725" alt="Screenshot 2023-04-24 at 12 36 06" src="https://user-images.githubusercontent.com/23226974/234060606-6ab8137c-1bf3-4807-a721-7c27237c3b6f.png">

### Expected Behavior

Typos Corrected

### Actual Behavior

Typos

### Steps to Reproduce

- Go to Process Reminders Job
- See typos/errors listed above

### Rock Version

v15.0, v16.0

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Thanks for your keen eyes @mikedotmundy !
