### ISSUE TITLE
Media Player Lava Shortcode Causes Video to Freeze Randomly

### ISSUE THREAD

**Issue by frogydiak** [SparkDevNetwork/Rock#5419]
## Please go through all the tasks below

* [ ] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
The Lava shortcode for Media Player is working perfectly fine but the issue is it freezes the video randomly in a timeline while playing and it doesn't continue playing even refreshing the page. Infact, after refreshing the page, it will freeze in the same timeline where it originally freeze. I am also seeing this issue while watching videos in RockU. Also, freezing does not happen to just 1 video, it does happen to all video that I tried to watch.FYI, I only tested this with Vimeo media only and watching the video directly from Vimeo does not freeze.## Expected Behavior
The video should play without freezing.## Actual Behavior
Video is freezing randomly.## Steps to Reproduce

* I purchased Triumph Tech Vimeo Media sync
* Configure Media and syncing with Vimeo does not have any issue
* Use Media Player lava short code to show vimeo media using the generated id in the media block.
* Play the media

## Rock Version
14.2## Client Culture Setting
en-US

**Comment by frogydiak** [comment]
**Update:**
I just found out that the freezes are happening only with Mac. I tried 2 Mac computers with different OS versions, 1 is with the latest OS X Ventura and the other is Mojave. Both using Chrome with the latest version and Microsoft Edge and both will freeze in the same timeline. But also, both OS X versions and in Safari and Firefox, it will freeze in the same timeline for a second but will continue playing. 

I just happened to assemble a new PC with Windows 11 and just thought of playing the same video with Microsoft Edge, to my surprise, it was playing smoothly, no freezes. So, I tried it with Google Chrome and Firefox, and all 3 browsers are not playing the video smoothly. So, I guess this issue is with Media Player Lava short code is with Mac?

**Comment by timlem** [comment]
We are seeing this happen on iPhones as well.

**Comment by timlem** [comment]
Here's a video screenshot of it happening on the community page: https://share.cleanshot.com/yqRhf2bd

**Comment by austinspooner** [comment]
This issue is the same one: https://github.com/SparkDevNetwork/Rock/issues/5419#issuecomment-1528885725

**Comment by cabal95** [comment]
I believe this has already been fixed when #5445 was fixed (which I think is the issue @austinspooner intended to link to). I tested with a couple videos on the Spark site (sourced from YouTube), including the video @timlem showed in his screen cap, and none of them are experiencing any issues now on either Mac or iOS.
