### ISSUE TITLE
Alpha 1.15.0.16 Reminder Type Workflow not Assigning all Items in Workflow

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5421]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

A Workflow assigned to a Reminder Type is not being assigned all items as documented in the Rock Documentation. Per the documentation, the workflow will launch and will be passed the following items if the workflow has matching keys:

1. Reminder
2. ReminderType
3. Person
4. EntityTypeGuid
5. EntityGuid

In testing these, it seems Reminder and Reminder Type are the only 2 working.

Here is a screenshot of my Workflow Attributes:
<img width="1725" alt="Screenshot 2023-04-25 at 19 53 44" src="https://user-images.githubusercontent.com/23226974/234432934-2e60717b-53d2-4885-8b92-9c57d927936d.png">

I applied this Workflow to both a Reminder Type with an Entity Type `Person` and a Reminder Type with an Entity Type `Group`:
<img width="1173" alt="Screenshot 2023-04-25 at 19 53 04" src="https://user-images.githubusercontent.com/23226974/234433054-6c731f73-88a5-4de7-8541-ffa2e4c436cc.png">

<img width="1172" alt="Screenshot 2023-04-25 at 19 53 11" src="https://user-images.githubusercontent.com/23226974/234433068-7fb258b7-cb23-4f3d-89f5-cb9595be80df.png">

I then added a Reminder to Ted Decker and to a General Group, for today (current date), and then ran the Process Reminders Job. It ran successfully and processed both reminders.

Upon checking both of the Workflow's Details, only the Reminder and Reminder Type were passed into the Workflow and assigned to Workflow Attributes:
<img width="1726" alt="Screenshot 2023-04-25 at 19 52 54" src="https://user-images.githubusercontent.com/23226974/234433276-ae891cfa-f639-43e2-8fee-23464da49023.png">
<img width="1726" alt="Screenshot 2023-04-25 at 19 52 40" src="https://user-images.githubusercontent.com/23226974/234433287-6a770933-50a7-4e0f-9b91-040d026aeb83.png">

### Expected Behavior

All Items be passed into the Workflow properly.

### Actual Behavior

All Items are not passed into the Workflow properly.

### Steps to Reproduce

See steps in above description.

### Rock Version

v15.0, v16.0

### Client Culture Setting

en-US

**Comment by shauncummings** [comment]
@mikedotmundy Thanks for your thorough testing.  The documentation was a bit off on this, and after some discussion we have decided to make a couple minor modifications in how the attributes are handled for these workflows, to use more specific field types instead of expecting you to deal with the raw GUID values.  There isn't a "Reminder" field type, so that one will still be a GUID, if you need to use it.

The documentation is being updated as I type this, but here is how these attributes should be configured after the latest update (which will be in the next v15.0 build):

<img width="811" alt="image" src="https://user-images.githubusercontent.com/46500397/234694666-b8dedc55-25db-447d-9fed-5e31c0548b0b.png">

**Comment by mikedotmundy** [comment]
Awesome thank you @shauncummings! Just to appease my curiosity, why is Reminder not a valid Field Type?

**Comment by shauncummings** [comment]
> Just to appease my curiosity, why is Reminder not a valid Field Type?

Field types have to be built, with a non-trivial amount of code and testing and we don't have them for every entity type in Rock.  There's enough in this case to grab the Reminder in Lava or do any data manipulation you want to within the workflow, so it's a little difficult to justify the effort for this one use case.  If we used Reminder entities in this way in several places, it might be a different story.  It's something that could get added in the future, if there's a better case for doing so down the line.

**Comment by mikedotmundy** [comment]
That makes sense - I appreciate you explaining it to me. Thank you!

**Comment by shauncummings** [comment]
> That makes sense - I appreciate you explaining it to me. Thank you!

No problem.  Thanks again for the great testing on this, Mike, it's a meaningful contribution to the Rock community.

**Comment by mikedotmundy** [comment]
@shauncummings As info, I see in the documentation that the text was updated, but the image does not match what you sent in your original response to me.

**Comment by shauncummings** [comment]
@mikedotmundy I think you got a cached version of the image.
