### ISSUE TITLE
Group Leader Toolbox "Add New Attendee" box unusable on mobile when there are Pending Members

### ISSUE THREAD

**Issue by thejasonharvey** [SparkDevNetwork/Rock#5422]
## Please go through all the tasks below

* [x] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
When attempting to record attendance for a group on a mobile device through the Group Leader Toolbox, if there are 1 or more pending members in the group the "Add New Attendee" box is visible but not selectable. ![Works](https://user-images.githubusercontent.com/130079417/234636530-68569308-11c8-4a59-8b04-73f27eba2196.png)![Works not](https://user-images.githubusercontent.com/130079417/234636569-e9b1c76c-01c6-4747-9ee8-b752c69514e2.png)## Expected Behavior
The "Add New Attendee" box would be usable from a mobile device even if there are pending members.## Actual Behavior
The box is visible but unusable and unresponsive. It seems to be underneath the "Pending Members" Section - when attempting to click/ tap the box, text was highlighted in the "Pending Members" section instead.## Steps to Reproduce

* Go to https://rock.rocksolidchurchdemo.com/page/368?GroupId=113&OccurrenceId=0&Date=2023-04-25T00%3a00%3a00&ScheduleId=17
* Add a pending group member
* Click on the Attendance Tab
* Add or edit an attendance
* On the block settings, set "Allow Adding Person" to "Yes"
* Refresh the page 
* Compress the window size until the "Pending Members" section no longer appears at the top of the right side and instead appears next to the "Add Attendee" box
* Attempt to click on the "Add Attendee' box 

## Rock Version
14.2## Client Culture Setting
en-US

**Comment by chead4** [comment]
@thejasonharvey I am closing this issue as I am not able to recreate on v16.0 (beta release). Feel free to reopen.
