### ISSUE TITLE
Login Block: Cannot Remove Default Text for Remote Authorization Prompt Message

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5423]
## Please go through all the tasks below

* [x] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
In both the **Login (Legacy)** and **Login Obsidian** blocks, the field for `Remote Authorization Prompt Message` cannot be cleared out. The help text does say this field is optional, but upon clearing the text from it and saving the block settings, the original text "Log in with social account" reappears in the block.![Screenshot 2023-04-27 at 07 57 12](https://user-images.githubusercontent.com/23226974/234857124-053aedb9-26a9-4334-b02a-02dce8914a8e.png)![Screenshot 2023-04-27 at 07 55 58](https://user-images.githubusercontent.com/23226974/234857178-1bea80e5-d2ee-4c98-8060-ccabab2a0f84.png)## Expected Behavior
Should be able to remove text from `Remote Authorization Prompt Message` field.## Actual Behavior
Cannot remove text from `Remote Authorization Prompt Message` field.## Steps to Reproduce

* Go to Admin Tools > Security > Authentication Services
* Enable Facebook (just enter some dummy settings)
* Go to both the **Login (Legacy)** and the **Login Obsidian** blocks, enable Facebook as a Secondary Authentication Type, and remove text from `Remote Authorization Prompt Message` field.
* Save
* See that the default text "Log in with social account" reappears in the block.

## Rock Version
en-US## Client Culture Setting
v14.2, v15.0, v16.0

**Comment by BrentPirolli** [comment]
Confirmed. If you use a space in the field, it strips that out as well and puts in the default text. If you use &nbsp; however, it works to clear out the default text.

**Comment by nairdo** [comment]
We're also going to include a data-migration in v16.4 that will add/set any existing block's to use the original default value `Log in with social account` but this change will now allow the Rock admin to clear out those block's default values.
