### ISSUE TITLE
Obsidian Event Registration block doesn't handle PageRedirect lava filters in Registration Confirmation Text

### ISSUE THREAD

**Issue by andypullen** [SparkDevNetwork/Rock#5435]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

If an event registration template includes a PageRedirect filter in the Registration Confirmation Text, the confirmation step won't redirect, and it will display a generic "congratulations" message.
![Screen Shot 2023-05-04 at 17 04 00](https://user-images.githubusercontent.com/9940032/236355774-0f93eef1-fea7-4f1f-bfa9-feea3bea972f.jpg)

### Expected Behavior

The lava should execute as expected, and redirect.

### Actual Behavior

See above.

### Steps to Reproduce

- Create an Event Registration template
- Add `{{ 'http://www.rockrms.com' | PageRedirect }}` in the Registration Confirmation Text field
- Create an Event that uses the template, and get to the final confirmation screen, where it will not redirect or load any of the text from the Registration Confirmation Text, showing a generic message instead.

### Rock Version

14.2

### Client Culture Setting

en-US

**Comment by andypullen** [comment]
I uncovered a bit more on this. The registration process makes a POST request to `/api/v2/BlockActions/.../.../SubmitRegistration` and gets back a json object, including the parsed html to show for the registration confirmation text. When a redirect filter is included, it redirects on the SubmitRegistration script, so then the request sees invalid json and outputs `You have successfully completed this ${this.registrationTerm}` as a result.

If I put this in the Registration Confirmation Text field:
```
Confirmation text content here...

redirect command here: {{ 'http://www.rockrms.com' | PageRedirect }}
```
I get this response back from SubmitRegistration:
```
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="http://www.rockrms.com">here</a>.</h2>
</body></html>
{"titleHtml":"Congratulations Andy","messageHtml":"Confirmation text content here...\n\nredirect command here: ","transactionCode":null,"gatewayPersonIdentifier":null}
```

Side note, I also tried putting a javascript redirect in the confirmation text field, but anything in <script> tags also don't get executed out from the response.

**Comment by ethan-sparkdevnetwork** [comment]
When I try this I get a Cross-Origin Resource Sharing error.

> Access to XMLHttpRequest at 'http://www.rockrms.com/' (redirected from 'http://localhost:6229/api/v2/BlockActions/f7ca6e0f-c319-47ab-9a6d-247c5716d846/e7112bce-f841-49a5-a485-ac7f4618c563/SubmitRegistration') from origin 'http://localhost:6229/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by ethan-sparkdevnetwork** [comment]
@andypullen  I talked this over with the Obsidian architect and the PageRedirect lava filter is not supported on Obsidian blocks yet. Other similar filters affect the http header will also not work. Support for these is in the product map, but not in the very near future.

In the meantime you have a few options, one with user interaction and one without.

**With User Interaction**
1. Put a link for the user to click in this "Registration Confirmation Text". You can use the bootstrap button classes to make it look nice and professional.

**Without User Interaction**
I haven't tested this, but it should work.
1. Put a link for to the external URL and add a unique CSS class to it (e.g. "js-reg-confirmation-url") in the Registration Confirmation Text.
2. Add an HTML Content block to the Registration page.
3. In the HTML Content block add a js script that will check (every 100ms or so) for elements with the "js-reg-confirmation-url" CSS class and trigger a click event on it when found.

**Comment by Jon-Corey** [comment]
In case anyone else stumbles across this and is looking to do something similar to @andypullen, I modified his script to only run when the HTML on the page is changed instead of every 100ms. Besides that, I didn't change anything. Andy's way of doing this was pretty smart.

```html
<script>
    // Variable to track whether the link has been clicked
    let linkClicked = false;

    // Create an observer instance linked to the callback function
    const observer = new MutationObserver(function(mutationsList, observer) {
        // Redirect the user
        const redirectLink = document.getElementById("redirect-confirmation-url");
        if (redirectLink && !linkClicked) {
            redirectLink.click();
            linkClicked = true;
            observer.disconnect();
        }
    });

    // Start observing the document for configured mutations after the HTML is loaded
    window.addEventListener('load', function() {
        observer.observe(document, { childList: true, subtree: true });
    });
</script>
```
