### ISSUE TITLE
Connection Request Navigation

### ISSUE THREAD

**Issue by carriewhite** [SparkDevNetwork/Rock#5436]
### Please go through all the tasks below

- [ ] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When viewing a connection opportunity, we're not always able to successfully navigate to other opportunities using the navigation dropdown. The connection opportunity header changes and you think it's successful, but the data (individual requests) only sometimes changes. Sometimes the id in the url does not change either so anything referencing that parameter doesn't work.
![CR](https://user-images.githubusercontent.com/70244373/236355452-33238ed3-fc43-487d-bcdd-dfff95fae10f.jpg)

### Expected Behavior

The page redisplay as if the connection opportunity was selected from the Connections page with the data displayed for the one requested connection opportunity.

### Actual Behavior

Sometimes when using the dropdown navigation, the page doesn't refresh entirely showing the data for the new connection opportunity.

### Steps to Reproduce

- go to connections page
- select any connection opportunity
- navigate to other connection opportunities
- note if correct requests are displayed and if page url changes

### Rock Version

14.1

### Client Culture Setting

en-US

**Comment by jasonhendee** [comment]
@carriewhite, I have a few questions:

1. Have you noticed this happening when the block is operating in both **Board** and **List** mode, or only one of the two modes?
2. Do the problematic Connection Opportunities (the ones that sometimes don't load) have a lot of Connection Requests?
3. Does the problem become more apparent the longer you use the page within a given sitting, or is it immediately-apparent when you first start using the page?

**Comment by carriewhite** [comment]
@jasonhendee 
1. I would say primarily board mode 
2. possibly a lot of inactive requests.  Those probably should be deleted periodically but we don't.
3. it's random but does seem to happen more frequently when switching from one connection type to another; however, sometimes I can switch between types without issue.
4 I haven't noticed any pattern there. 
5. Maybe not relevant, but the Context.ConnectionOpportunity.Name doesn't change, which is troublesome.

**Comment by chead4** [comment]
@carriewhite Hi Carrie - Unfortunately, we have been unable to recreate this issue.  We will be closing this issue at this time; but, please reopen if you experience this issue again.
