### ISSUE TITLE
Pre-HTML and Post-HTML fields for Registration Attributes not Displaying in Obsidian Registration Entry Block

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5449]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

This is an issue for the _Obsidian Registration Entry_ block NOT the _Registration Entry_ block.

When creating a Registration Attribute, the Pre-HTML and Post-HTML Registration Attribute fields do not appear on the external site. 

Create a _Registration Attribute_ and add some text in the Pre-HTML and Post-HTML fields.
<img width="1728" alt="Screenshot 2023-05-17 at 21 46 08" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/d1d6841c-4f24-4748-8819-6e647713b317">
<img width="1728" alt="Screenshot 2023-05-17 at 21 45 40" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/093bb05c-2fb7-4d54-a501-b3db823bcc45">

Then go to the external site (example: `/Registration?RegistrationInstanceId=1` ... make sure instance Id matches an active one of the same template you just created the Registration Attribute with), add the Obsidian Registration Entry block, and see  that the content you added to the Pre-HTML and Post-HTML fields is missing.
<img width="1173" alt="Screenshot 2023-05-17 at 21 47 11" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/78d77035-0a3b-452e-ab06-82107bdf36d5">

For reference, this is what it should look like, however this is using the original _Registration Entry_ block.
<img width="1189" alt="Screenshot 2023-05-17 at 21 47 06" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/d5a8b330-1f27-4171-980e-8a3eabf64cc6">

### Expected Behavior

Pre-HTML and Post-HTML fields should display in the Obsidian Registration Entry block.

### Actual Behavior

Pre-HTML and Post-HTML fields do not display in the Obsidian Registration Entry block.

### Steps to Reproduce

See above

### Rock Version

v14.2, v15.0, v16.0

### Client Culture Setting

en-US

**Comment by SkellyRen** [comment]
I believe this is related to this Pull Request: #5402
