### ISSUE TITLE
Inactive Registrant Attributes still show if required

### ISSUE THREAD

**Issue by RufenachtPW** [SparkDevNetwork/Rock#5450]
## Please go through all the tasks below

* [x] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
There are 2 things with this issue. The first part is if you have a registrant attribute on a registration that is required and you inactivate the attribute, the attribute will still show on the internal edit page of a registrant. The second part is because it is required you add a value to it. If you go back in to edit them again the value is wiped out and you have to add it again. ## Expected Behavior
Inactive and required attributes should not be displayed and if they are then the value that was entered should be prefilled in.## Actual Behavior
Inactive and required attributes still show and their value is cleared out.## Steps to Reproduce

1. Go to the demo site and add a single select to a registration.
1. Mark the attribute as required and inactive.
![Screenshot 2023-05-19 at 7 08 34 AM](https://github.com/SparkDevNetwork/Rock/assets/87141140/04a339f8-56ed-4a0a-b647-06be9a2cd40b)
1. Go into the registration (Internal) and add a registration and registrant. 
1. On the registrant you will notice you are required to add a value for the inactive attribute. 
![Screenshot 2023-05-19 at 7 08 56 AM](https://github.com/SparkDevNetwork/Rock/assets/87141140/6bd6ade4-322a-457b-916c-38449882f90a)
1. Add a value to the required field so you can save the registrant. 
1. Look at the grid and you will see the value is there.
![Screenshot 2023-05-19 at 7 09 35 AM](https://github.com/SparkDevNetwork/Rock/assets/87141140/82f44dae-7923-477a-bd80-e22a534ce4d8)
1. Now go back into the registrant and notice the value is blank.
![Screenshot 2023-05-19 at 7 17 42 AM](https://github.com/SparkDevNetwork/Rock/assets/87141140/dd4706c2-ce94-46ab-aa56-58d45b7525be)

## Rock Version
14.2## Client Culture Setting
en-US

**Comment by chead4** [comment]
@RufenachtPW I am closing this issue as I am unable to recreate on rocksoliddemochurch.com.  Feel free to reopen if you still experience this issue.
