### ISSUE TITLE
Group Requirements "Publicly Hidden" block setting (Confusion/not intuitive)

### ISSUE THREAD

**Issue by karenn-ccbc** [SparkDevNetwork/Rock#5454]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

In the Group Member Detail block setting, there is a selection for " are Requirements Publicly Hidden"
![image](https://github.com/SparkDevNetwork/Rock/assets/35667472/d5b42ec6-8155-4b82-b947-149cad797d7d)

Not hidden:
![image](https://github.com/SparkDevNetwork/Rock/assets/35667472/da39b5a6-37f8-4da6-8f3e-7890dc3e629d)

This would SEEM to hide the requirements on a public (external site - not Internally). However, when I set it to Yes, it hides the requirements in the group member detail internally, but externally in the Mission Tools/Participant page for instance, they appear. There is no external block setting in the Fundraising Opportunity Participant block to hide this without editing the Lava file.
Hidden = Yes:
![image](https://github.com/SparkDevNetwork/Rock/assets/35667472/71669ca6-7588-44f3-950f-32e1f8b79171)
![image](https://github.com/SparkDevNetwork/Rock/assets/35667472/6974b12a-0c6c-4502-a5de-37a3da5aff61)

### Expected Behavior

To hide the requirements Publicly on the external site, but not internal in the group. The new 15.0 Requirements tab (internal) does help with this somewhat, but it still does not seem intuitive in its description.

### Actual Behavior

Hides them internally, but shows them externally. 
It would be nice to be able to control this in the Group Type rather than the block setting for all group member detail as there may be more granular times we want to show or hide this.

### Steps to Reproduce

- Go to the fundraising group type and set requirements.
- Go to the Group and view the requirements on the group member block.
- Edit the group member detail block setting and set Hide Publicly to yes.
- Notice that the requirements get hidden in the group member detail internally.
- Go to the Mission Trip ( Fundraising) Tools> Participant page and notice that the requirements still appear.

### Rock Version

14.2 and 15.0

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@karenn-ccbc  Thank you for letting us know about this.  It was a bit confusing.  We're updating the block setting title's and help text on the Group Member Detail block (typically used internally) to be clearer.

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/9f362a88-07e6-4328-aa32-7075fb245ee9)

However the Fundraising Opportunity Participant (FundraisingParticipant block) does not have a setting for controlling whether the requirements are shown to the individual (the person would currently always see their own requirements when viewing their participant page). If that is something you would like to see added to that block, we'd just ask that you submit it to the [Ideas board](https://community.rockrms.com/Ideas).
