### ISSUE TITLE
Structured content editor not working

### ISSUE THREAD

**Issue by davidbelk** [SparkDevNetwork/Rock#5455]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

The structured content editor does not seem to give any options for editing the content. Only a blank box is displayed. 

### Expected Behavior

You should be able to edit structured content such as message notes. 

### Actual Behavior

A blank box appears that you cannot edit. 

### Steps to Reproduce

- Go to Tools --> Content --> Message notes      https://rock.rocksolidchurchdemo.com/page/343?ContentChannelGuid=48951e97-0e45-4494-b87c-4eb9fca067eb
- Click on the + to add a content channel item. 
- Scroll down to the content box. 
- See error
![Screenshot 2023-05-25 at 9 42 54 AM](https://github.com/SparkDevNetwork/Rock/assets/43145156/6f58b64a-0ac8-4ca5-bd0f-bd192de6e5e3)

### Rock Version

15.0

### Client Culture Setting

en-US

**Comment by JRichmond27** [comment]
Looks like there are a couple JavaScript files that can't be found: 

![image](https://github.com/SparkDevNetwork/Rock/assets/1696714/cf748613-d3ad-42b3-8749-98dab60a73b0)

**Comment by nairdo** [comment]
We've tracked this down and will include them in the `v15.1` update that is about to go alpha today or tomorrow.  If someone is in a desperate need to resolve this ASAP and is comfortable with adding files to their webserver, these files ([download](https://rockrms.blob.core.windows.net/updates/temp_pre_release_patches/v15.1_Scripts_Rock_UI_structuredcontenteditor.zip)) can be manually added back into a `\structuredcontenteditor\` folder under the `\Scripts\Rock\UI\` folder:

* `\Scripts\Rock\UI\structuredcontenteditor\editor.js`
* `\Scripts\Rock\UI\structuredcontenteditor\editor.js.map`
* `\Scripts\Rock\UI\structuredcontenteditor\editor-tools.js`
* `\Scripts\Rock\UI\structuredcontenteditor\editor-tools.js.map`

**Comment by ethan-sparkdevnetwork** [comment]
Updated the 15.0 installer package to include these files and not delete them.
Ensured the 15.1 installer package will include the files.

**Comment by timlem** [comment]
@ethan-sparkdevnetwork - We updated to 15.1 last night and I am still unable to add any content to the structured content section. Just wanted to share. Randy is looking for the files mentioned to fix it manually. But I thought you might want to know the update didn't fix it for us.

**Comment by nairdo** [comment]
@timlem & @davidbelk Thanks for brining this to our attention again. This is unfortunate.  We did updated the v15.0 package to _not_ remove the files in the first place, but we're tracking down how it was missed to include them in v15.1 (for those who already installed v15.0 prior to June 1st) during the final packaging process.

We just updated the v15.1 package again to include those files again.  If you already installed v15.1, and are comfortable doing this manually, you can ([download](https://rockrms.blob.core.windows.net/updates/temp_pre_release_patches/v15.1_Scripts_Rock_UI_structuredcontenteditor.zip)) those files and manually add them back under a \structuredcontenteditor\ folder under the \Scripts\Rock\UI\ folder:

* \Scripts\Rock\UI\structuredcontenteditor\editor.js
* \Scripts\Rock\UI\structuredcontenteditor\editor.js.map
* \Scripts\Rock\UI\structuredcontenteditor\editor-tools.js
* \Scripts\Rock\UI\structuredcontenteditor\editor-tools.js.map
