### ISSUE TITLE
Can't query Schedules through API.

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#5458]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

/api/schedules returns an exception due to FriendlyScheduleText property not having a setter. Thinking this is because it has the [DataMember] attribute even though it is not a database property. 

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/b9d219ab-63bb-475e-9182-b036b3da1eb9)

### Expected Behavior

Should return list of schedules

### Actual Behavior

Causes Exception

### Steps to Reproduce

Using browser, navigate to [https://prealpha.rocksolidchurchdemo.com/api/schedules](https://prealpha.rocksolidchurchdemo.com/api/schedules)  (be sure to login first)

### Rock Version

v12 - v16

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@azturner If you needed a quicker fix, it looks like that error is happening when the response content type is `application/xml` but it appears to be working when it is `application/json`. Regardless, we're going to try to get that fix into v15.2.
