### ISSUE TITLE
Schedule Toolbox Sign Up tab shows inactive schedules

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/Rock#5459]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

The Schedule Toolbox Sign Up tab is showing inactive and non-public schedules.

![image](https://github.com/SparkDevNetwork/Rock/assets/1696714/762ef918-a563-49bf-bef7-7b264d72e7f4)

![image](https://github.com/SparkDevNetwork/Rock/assets/1696714/37177864-3054-4d42-83fe-088d633a8e54)

![image](https://github.com/SparkDevNetwork/Rock/assets/1696714/921ecadd-b4b6-40a4-a609-5d2c7dae4c67)

### Expected Behavior

At least the inactive schedules should be excluded from the Sign Up tab. I'm not sure if the Is Public option is meant to exclude the schedule from the Schedule Toolbox, so I don't know if non-public schedules should be displayed on the Sign Up tab or not.

### Actual Behavior

Both inactive and non-public schedules are displayed as options on the Sign Up tab of the Schedule Toolbox.

### Steps to Reproduce

1. Add two schedules to a group with scheduling enabled
2. Add yourself to the group
3. Go to the Schedules page and uncheck the Is Active box for one of the schedules and uncheck the Is Public box for the other schedule
4. Go to the Sign Up tab of the Schedule Toolbox
5. Notice that both of the schedules show up as options

### Rock Version

v13.7 & v15.0

### Client Culture Setting

en-US

**Comment by nharmonCOTH** [comment]
Church of the Highlands is also experiencing this issue.  We are on v16.3

**Comment by chead4** [comment]
@nharmonCOTH Hi Nathan  I'm sorry to hear that you are still experiencing an issue.   I was unsuccessful in recreating this issue on the demo site (in both the Obsidian and webform Group Schedule Toolbox block) from v16.2 and then in each release as I upgraded to v16.5.  

Are you able to recreate the issue on the demo site?  If so, we would greatly appreciate if you could provide more details including screenshots of the issue as this will help us out in recreating and investigating.
