### ISSUE TITLE
Browser Language Preference Breaks NMI Gateway on Event Registration

### ISSUE THREAD

**Issue by billdeitrick** [SparkDevNetwork/Rock#5461]
## Please go through all the tasks below

* [x] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
When a user's browser language preference (Accept-Language header) is set to a language that uses a comma decimal separator instead of the period as is standard for the en-us locale, the NMI gateway fails upon payment submission with an error when attempting to register for an event:`Invalid Data Type amount must be a number REFID:##########`It looks like the NMI gateway is sending the localized currency value through, which is does not seem to be accepted by NMI.This appears to affect only the Webforms Registration Entry block, not Obsidian.![Snag!UNITO-UNDERSCORE!70a5c4c](https://github.com/SparkDevNetwork/Rock/assets/4174527/9079f94f-9ed0-4375-973b-0395d9f21b1a)![Snag!UNITO-UNDERSCORE!709113e](https://github.com/SparkDevNetwork/Rock/assets/4174527/85f304d9-2948-4f20-9b07-c82a76a79209)## Expected Behavior
The payment gateway would appropriately format the amount field for submission to NMI regardless of the Accept-Language/Localization settings in the user's browser.## Actual Behavior
The payment submission fails with the following error message: `Invalid Data Type amount must be a number REFID:##########`## Steps to Reproduce
The following steps were used to reproduce this issue on the Rock Solid Demo site.

1. Set the web browser's language preference to Russian. Verify it is set by confirming the browser is transmitting an Accept-Language header with Russian as the first option.
1. Activate the NMI gateway, entering in any string for the required key, username, and password fields.
1. Edit the Summer Camp registration template, setting the financial gateway to NMI.
1. Edit the summer camp registration instance, extending the date so that the registration is still active.
1. Navigate to the Summer Camp registration on the public site.
1. Step through the registration (using the browser with Russian language preference).
1. After filling out the fields on the "Review Registration" step, click "Next".
1. An error message is shown: "An error has occurred while processing your request. Your organization's administrators have been notified of this problem."
1. An exception is logged: "Invalid Data Type amount must be a number REFID:XXXXXXXXXX"

![Snag!UNITO-UNDERSCORE!709720b](https://github.com/SparkDevNetwork/Rock/assets/4174527/c7d64191-e7b1-439c-81c8-affbfbe20d8d)## Rock Version
15.0## Client Culture Setting
ru-RU

**Comment by cabal95** [comment]
@billdeitrick This should be fixed in Rock 15.3 and 16.1 (and later). I was able to replicate the problem by changing the culture setting in my browser and verified the change fixed that scenario. Since web locales are a tricky thing, if this is still a problem after upgrading to 15.3 or 16.1 please re-open this issue.

**Comment by billdeitrick** [comment]
@cabal95 Great--thank you! Will re-open if this crops up again!
