### ISSUE TITLE
Send Group Attendance Reminder Job (v15) fails when there's more than one group leader

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5462]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When a group type is configured to send attendance reminders using the new Send Group Attendance Reminder job available in v15 _AND_ the group has more than one leader, the job fails with an exception. The exception is as follows:
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/16764513-a62b-4ea4-a069-a0ddda467f68">

Looking at the code behind that job, it appears like the code in the job that creates + inserts the attendance occurrence runs for each group leader, not just for each group. The exception is:
`Cannot insert duplicate key row in object 'dbo.AttendanceOccurrence' with unique index 'IX_GroupId_LocationID_ScheduleID_Date'. The duplicate key value is (112, <NULL>, 16, 2023-06-01). The statement has been terminated.`

### Expected Behavior

I would expect that the new `Send Group Attendance Reminder` job would be able to handle sending reminders to groups with more than one leader. 

### Actual Behavior

If a group has more than one group leader, the job will throw an exception because it's trying to create the occurrence again.

### Steps to Reproduce

- Go to the demo server (running v15)
- Go to Admin Tools > General Settings and click on Group Types
- Click on the Group Type `Small Group`
- Expand Attendance / Check-in
   - Check `Send Attendance Reminder`
   - Set an `Attendance Reminder Communication Template`
   - Set an `Attendance Reminder Start Offset Minutes`
   - <img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/e25a6e84-ebdd-4f9c-b61a-1af3f240bd43">
   - Save the changes made to the Group Type
 
_This next step is required, otherwise the job will throw an error that there's no email transport configured_
- Go to Admin Tools > Communications and click on Communication Transports
- Click on SMTP to open its settings
- Change the server to smtp.freesmtpservers.com
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/52350b9d-3dbd-4cb0-afe1-f944207a711e">

- Go to People > Group Viewer
- Expand Section A and click on `Alisha Marble’s Group`
- Edit the group and adjust the meeting date/time to be within the offset configured above when you run the service job
- Save the group

- Go to Admin Tools > System Settings, and click on Jobs Administration
- Manually run the Send Group Attendance Reminders job
- Notice the exception
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/d67aa984-49e2-47bc-948e-00f08a9a13b1">

<img width="1727" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/582ded17-6113-41cd-a304-5c8602f3c6de">

### Rock Version

Rock McKinley 15.0 (1.15.0.16)

### Client Culture Setting

en-US

**Comment by zackdutra** [comment]
@leahjennings, @PraveenMathew92, or @chead4 -we're in 15.1 still. Does this job send to at least the first group leader or does it just fail for both? I'm seeing the exceptions but not sure if it's failing completely or just on the second leader.

**Comment by austinspooner** [comment]
@zackdutra for us, it failed for some groups and for others caused them to be stuck in a loop.
