### ISSUE TITLE
Exception In Metrics When Using Flot Chart Style

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5463]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Trying to view a metric under Tools | Metrics can cause an exception if the Metric Detail block is configured to use _Flot_ chart style instead of _Rock_ style.

### Expected Behavior

Metrics would not throw exception when using Flot chart style

### Actual Behavior

They do

### Steps to Reproduce

1. on rock.rocksolidchurchdemo.com go to Tools | Metrics
2. Click on Homepage Metrics | Active Connection Requests
3. Observe that the metric renders normally as expected.
4. Edit the _Metric Detail_ block on the page and change the chart style from _Rock_ to _Flot_
5. Refresh the page and click Homepage Metrics | Active Connection requests and observer the exception.

Here's the exception with debug enabled:
![image](https://github.com/SparkDevNetwork/Rock/assets/3903408/888fabea-4ac1-493c-b981-a31fd12606a2)

### Rock Version

15.0+

### Client Culture Setting

en-US

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in commit: bcb3a750
