### ISSUE TITLE
Event Registration Fee Item Is Not Required When Set to Required

### ISSUE THREAD

**Issue by jyarrowks** [SparkDevNetwork/Rock#5464]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

In 14.x and 15.0, event registration fee items that are marked as required are not actually required of the user when filling out the registration. In Rock 13 and previous, items marked required were shown as pre-checked and grayed out. In 14.x and 15.0, the check box for the fee items are not checked by default, and the user is able to progress without checking them. In non-Obsidian Registration Entry, the fee is displayed as required, but isn't. In Obsidian, the fee item doesn't display as required. In both instances, the user can progress to the registration review page and register without paying the required fees.

Fee Item marked as required:
<img width="1181" alt="Screenshot 2023-06-05 at 4 52 35 PM" src="https://github.com/SparkDevNetwork/Rock/assets/35508323/a31e31e3-63f5-4429-9515-e8ffbb0d2d5f">

Fee item not checked, even though required:
<img width="1269" alt="Screenshot 2023-06-05 at 4 53 59 PM" src="https://github.com/SparkDevNetwork/Rock/assets/35508323/95f8a19d-ac1c-430f-a00b-56f6c12e37bc">

Review Registration screens showing the the required fee item wasn't enforced:
<img width="1028" alt="Screenshot 2023-06-05 at 4 54 45 PM" src="https://github.com/SparkDevNetwork/Rock/assets/35508323/8fbc995e-91f6-4fea-ae19-ba5bc6c0551b">

### Expected Behavior

Expected Behavior: Any required fee items would be automatically checked and grayed out; the user would not be able to uncheck it. Any required fees would be enforced on the payment screen.

Screenshot example from Rock 13.1:
<img width="205" alt="Screenshot 2023-06-05 at 5 01 04 PM" src="https://github.com/SparkDevNetwork/Rock/assets/35508323/29e2d19b-77f1-4e1b-ad78-3c6daf339739">

### Actual Behavior

Actual Behavior: Required fee items are unchecked by default, letting the user continue to the payment page without paying the required fees. On non-Obsidian Registration Entry, it it shown as required, but not enforced. On Obsidian Registration Entry, it's not shown as required, nor enforced.

### Steps to Reproduce

- Go to Rock Demo Site and navigate to Event Registration
- Create a required fee item under "Summer Camp" test event
- Navigate to Summer Camp registration instance and step through the registration entry form

### Rock Version

14.x and 15.0

### Client Culture Setting

en-US

**Comment by ericfrost56** [comment]
We're experiencing this same issue as well on 14.2
