### ISSUE TITLE
Person Attributes on Registrant form cannot be maintained from Registrant Edit

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#5469]
## Please go through all the tasks below

* [x] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
**Brief Description**

1. When adding a Person Attribute as a field on an event registration form, the field can properly be filled in during the registration process, but when maintaining the Registration details from the back-end, the Person Attribute is displayed on the Registrant's registration (if it has a value, but not if it does not), but is NOT made available for editing when editing the Registrant's registration.

![rego-attributes-9](https://github.com/SparkDevNetwork/Rock/assets/4658177/d3eee53e-0fbc-4c5b-a158-796623315d68)

1. Registration form attributes have the option to maintain the field via Bulk Update, but the field is not made available on the Bulk Update page for edit.

![rego-attributes-A](https://github.com/SparkDevNetwork/Rock/assets/4658177/2cdf05fc-0e94-4f73-acc3-4c4236e36030)**Background Use Case**

We do not have a payment gateway and are not using any payment functionality yet.  This is probably typical for lots of smaller churches.  So we decided to use an attribute on the registration to track whether the Registrant had paid.  First I added a Registration Attribute, but then discovered there was no way to update this field in Bulk.  E.g.,  Here is a list of people from the bank statements that we can see have paid by direct bank credit - update them all to show their payment method is 'Direct Bank' to show they have paid.  The only way to do this is to update them one by one.

So I tried to get around this by adding a Person Attribute.  This CAN be updated via Bulk Update.  But the Registration page does not show the field if it is not yet set, and editing the registration does not make the Person Attribute available to update. So we have no way of using either Person Attribute or Registration Attribute and Bulk Update to quickly update the payment status of lots of registrants.  Our finance admin person needs a quick method to be able to go to the Registration Event, select the list of Registrants, select all those who have paid, and to update their payment status all at once.(Maybe I'm missing something, and there is an easier way to do this.)The following testing has not considered or tested Registration form Group Member Attributes.

## Expected Behavior

1. Existing functionality allows Person Attributes to be added as event registration form fields.
The Person Attribute should be displayed as a valid field of the registration (regardless of whether the Person Attribute has data), and should be available to edit on the Registrant Edit page.
1. Registration Attributes should be made available on Bulk Update if the field is ticked TRUE for 'Show on Bulk.'

## Actual Behavior

1. Person Attributes added to a registration form are not shown on the Registration display page if they contain no data, and are not available on the Registration edit page (regardless of whether they hold data or not).
1. Registration Attributes are not made available for Bulk Update.

## Steps to Reproduce

1. Add a Person Attribute.  Or just use an existing Person Attribute, such as Allergy.
1. Add a new registration event template and registration event instance via Tools > Event Registration.  On the registration event template **add a Person Attribute** as one of the form fields.  For comparison, also add a Registrant Attribute. 
![rego-attributes-1](https://github.com/SparkDevNetwork/Rock/assets/4658177/3eb03deb-c2ef-45b2-a21f-bc7e7ccc7532)
1.  Add a registration instance and a Registration to the registration event.  I used the back-end screens to do this, and selected Ted Decker as the Registering person and the Registrant.  If you do this through the normal registration workflow and add data to the Person Attribute then the field will get populated. If you add the registration from the back-end, the Person Attribute field will not be displayed on the Registration edit page and cannot be populated.

![rego-attributes-2](https://github.com/SparkDevNetwork/Rock/assets/4658177/7fdbe1c1-3728-4b4a-a5aa-2c84e5f12525)The Registrant screen showing the Person Attribute missing.![rego-attributes-3](https://github.com/SparkDevNetwork/Rock/assets/4658177/fda9c573-007e-48f1-9ac7-5d0099bf92e4)

1. Navigate to the Registration page.  View the Registrant's details.  If the Person Attribute field is not populated, it will not display on the Registrants details. 
![rego-attributes-4](https://github.com/SparkDevNetwork/Rock/assets/4658177/2bbde970-18bc-4163-a53e-c071ea11825b)

1. Select Edit for the Registrant.  The Person Attribute is not shown, though it is a defined field on the registration.  It should be displayed, and it should be editable.  The Registration Attribute is correctly displayed.
![rego-attributes-5](https://github.com/SparkDevNetwork/Rock/assets/4658177/6b4a2d2f-e679-4d8a-802c-36decb4f06ea)

- - -
1. Go back to the Test Registration Instance and view all the Registrants.  Select a Registrant by ticking the box and select Bulk Update. 
![rego-attributes-6](https://github.com/SparkDevNetwork/Rock/assets/4658177/b81b680c-c13d-4350-a055-bb13bf7d477f)

1.  The **Registration Attributes** are NOT shown anywhere on the Bulk Update page, despite the Registration Attribute having its 'Bulk Update' field ticked true.  I expected they would be available somewhere - otherwise what is the meaning of the 'Show on Bulk' field on the Registration Attribute?  It would be ideal (best) if the Registration Attribute **could** be update in bulk.  There is no option in the list of Bulk Update Settings > Attribute Category to select 'registration attributes.'
1. Find and update the Person Allergy attribute that was added to the Registration form. Click Next and Confirm.
![rego-attributes-7](https://github.com/SparkDevNetwork/Rock/assets/4658177/4c2fa3b4-0888-41ed-bc85-f93768a9b514)
1. Return and view the list of Registrations. View the Registrants. Select and view the Registrant. You will now see that the Allergy field is displayed because it has data in it.
![rego-attributes-8](https://github.com/SparkDevNetwork/Rock/assets/4658177/d34a2a32-9b27-4d28-8e10-cf4b875690e0)
1. Edit the Registrant's details: click Edit.  The Person Attribute (Allergy) is still not made available for edit. It should be.
![rego-attributes-5](https://github.com/SparkDevNetwork/Rock/assets/4658177/45806de6-1a9b-4814-b380-853f9cfb9320)

This was tested on the demo site.

## Rock Version
Rock McKinley 15.0 (1.15.0.16)

## Client Culture Setting
en-us

**Comment by dataCollegechurch** [comment]
For what it is worth this issue has been added to the idea list in the past:
https://community.rockrms.com/ideas/188/adding-a-registrant-manually-should-allow-editing-of-person-attribute-fields

**Comment by jonedmiston** [comment]
Closing as this is an enhancement that already has an Idea attached.
