### ISSUE TITLE
Birth Date year can be skipped when required

### ISSUE THREAD

**Issue by GordonArber** [SparkDevNetwork/Rock#5470]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

On the family preregistration form, if you require birthdates for children, the year can be skipped. This causes two issues.

1. We expect the year to be there for children so we don't know their actual age.
2. It gives them the year 0001 which Rock then sees as really old.

### Expected Behavior

We expect that every field in the birthdate picker be required when we require the birth date.

### Actual Behavior

The year can be left blank and then rock assumes the year 0001.

### Steps to Reproduce

- Go to [Family Pre-Registration Page](https://rock.rocksolidchurchdemo.com/FamilyPreRegistration)
- Enter Required information except for the child's birth year
- Click Save
- Check the history of the child on the Internal site

### Rock Version

13.7, 14.2, 15.0

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
We're looking into this.   While it may be by design that (for adults) even if the birthdate setting is Required, it allows only a partial Month/Day value (without year), but for children, when the corresponding block setting is set to Required, I think it probably should require a complete value.
