### ISSUE TITLE
[15.1 Alpha] Pickers In Dataviews Are Jerky

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5471]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

I don't know if this is new obsidian behavior since v15 or just the change to a searchable drop-down, and it probably occurs anywhere such a picker is used, but I happened to notice it when editing a Data View during 15.1 testing. Mentioning it because it's an inferior experience compared to Rock v14 and prior.

### Expected Behavior

Picking criteria in a Dataview would not be frustrating due to jerky scrolling.

### Actual Behavior

At least on my system, it's very jerky trying to scroll a list of Person Fields when editing a Data View, for example.

### Steps to Reproduce

When you edit a filter in Rock v14.2 it looks like this:

![image](https://github.com/SparkDevNetwork/Rock/assets/3903408/73f4e728-8d63-4be7-ae7c-0a1a421bd1cf)

and when you click that drop-down you get a large list that is easily scrollable
![image](https://github.com/SparkDevNetwork/Rock/assets/3903408/1ac1cc6d-1106-47c6-8297-c8a55b4e2fe5)

But doing the same in 15.x results in a smaller, searchable drop down that is very jerky when trying to scroll through it. 
![image](https://github.com/SparkDevNetwork/Rock/assets/3903408/64b58efd-8d57-4f09-9bc7-bfe00ec9fde4)

At least on my system, the experience is so offputting that you end up searching for the field rather than scrolling to it.

### Rock Version

15.0+

### Client Culture Setting

us-EN

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1204763088595837">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1204810802048195">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1204811487151085">image.png</a>

**Comment by mikedotmundy** [comment]
I agree with @JimMichael that the user experience was better in v14.2 than it is in v15.0+. I do not mind having the ability to search in the dropdown, however having a larger dropdown field (width and height) would be a much better user experience.

**Comment by garrettjohnson** [comment]
Updated in V15.1 to improve usability with wider field selection fields via https://github.com/SparkDevNetwork/Rock/commit/9dc104c62bf0ef8e215fb8564a8d5457ff1f7c40.
