### ISSUE TITLE
Obsidian Registration Entry does not save registrant fields with same key

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#5472]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Registration Templates will allow you to save multiple registrant fields with same attribute key (first prolem). If you do this without realizing it, the obsidian registration block will then overwrite the first field's values with whatever is entered into the second field and not save a value in the second field. 

In this example, both the "Test Field 1" and "Test Field 2" fields have a key of "TestField":
![image](https://github.com/SparkDevNetwork/Rock/assets/548180/4a5b80b7-8a88-473c-a334-dc9b6b8ea470)

When using the obsidian block, and entering a different value in each field:
![image](https://github.com/SparkDevNetwork/Rock/assets/548180/7889886b-2481-4635-8ed6-473a353d4c0b)

The first field's value is overwritten with second field's value and a value is not saved in the second field:
![image](https://github.com/SparkDevNetwork/Rock/assets/548180/ee6f0ace-c94e-4fce-a459-1d5cd3684df5)

When viewing the details though, it shows second field's value for each field (even though a value is not stored in DB for second field):
![image](https://github.com/SparkDevNetwork/Rock/assets/548180/9dee27eb-5a81-4a9d-a410-d7d5e2498040)

### Expected Behavior

First: would expect that when editing/saving a registration template that it does not allow you to use same key on multiple form fields.

Second: registration entry block should save the values correctly even if fields have same key.  (The legacy registration entry block does this).

### Actual Behavior

Template allows saving multiple fields with same key, and then the obsidian entry block does not save values correctly.

### Steps to Reproduce

Create registration template with multiple fields that have same key
Add registration instance for the template
Use obsidian registration entry block to register someone for that instance and enter different values in the fields with same key.

### Rock Version

v14.2, v15.0

### Client Culture Setting

en-US

**Comment by ethan-sparkdevnetwork** [comment]
The fix will prevent entering in duplicate keys.
