### ISSUE TITLE
v15.1 Alpha - Transaction Entry V2 Block

### ISSUE THREAD

**Issue by asdf1nit** [SparkDevNetwork/Rock#5474]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Un authenticated visitors get an error screen when visiting a page with the Transaction Entry V2 block.
![image](https://github.com/SparkDevNetwork/Rock/assets/18108765/f1be09a1-7df4-4267-9e90-1a644729674b)

![image](https://github.com/SparkDevNetwork/Rock/assets/18108765/2e5c574c-095c-458f-8aa8-24dca499472c)

### Expected Behavior

Unauthenticated users should see the giving block instead of the error screen.

### Actual Behavior

When an unauthenticated person tries to visit a page that has the Transaction Entry V2 block they are greeted with an error screen.

### Steps to Reproduce

- Go to a page with the Transaction Entry V2 block
- See error

### Rock Version

15.1 Alpha

### Client Culture Setting

en-US

**Comment by asdf1nit** [comment]
I just added this bug to rocklatest and confirmed this there. See the transaction entry page in the navigation here https://rockrmslatest.com/Give

**Comment by JimMichael** [comment]
I cannot dupe this on my iPhone using the link
above to rocklatest (and not logged in). Also not seeing it on our test instance of 15.1 configured with NMI gateway. 

Note that the block (in both cases) is actually the new “Utility Payment” block, not “Transaction Entry v2”. 

![IMG_2991](https://github.com/SparkDevNetwork/Rock/assets/3903408/f5d0402a-301b-48ba-86fe-63a674b74fa5)

**Comment by JimMichael** [comment]
Was also able to dupe, but as another data point, the original ("v1") Transaction Entry block does not have this problem on 15.1.
