### ISSUE TITLE
Aero theme's back button does not work with Windows Check-in App

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#5475]
### Please go through all the tasks below

- [x] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

The Aero check-in theme places the back button in the upper-left corner. This is same spot that the windows app is checking for clicks to close the app and thus does not pass click events to browser. Because of this, users cannot click the back button when using the Aero theme inside a windows check-in client.  They will also end up trying several times to click the back button which then closes the check-in app.

### Expected Behavior

User is able to click back button

### Actual Behavior

User cannot click the back button

### Steps to Reproduce

Launch the windows check-in client and point it to "https://rock.rocksolidchurchdemo.com/checkin"
After logging, select these options on admin screen

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/dfb40d1a-fbc0-42ec-a6cb-2396067d10a3)

Click "Start" and enter phone number of 5553322 (T. Decker's phone).  Once the "Decker Family" is displayed, try clicking the back button.

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/5f88fdcb-f5f4-42ab-8335-9cd41b6069a4)

### Rock Version

v13.7, v15

### Client Culture Setting

en-US

**Comment by tcavaletto** [comment]
We can confirm this, Trader's Point is also having issues with this same bug in the Aero theme.
