### ISSUE TITLE
View Reminder Page links to external site rather then internal site

### ISSUE THREAD

**Issue by SixGricksSolutions** [SparkDevNetwork/Rock#5476]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When i went to the new "View Reminders" page and tried clicking on a person's profile the sub-domain changed to match the externally facing site rather then the internal site. I reproduced the same issue on the RockLatest.com site. 

### Expected Behavior

When you click on a person's name that you stay in the Rock internal site and just get directed to their profile. 

### Actual Behavior

When you click on a person's name you are directed to the external site's domain name and receive an error because /person/{{Person.Id}} does not exist on the external site. 

### Steps to Reproduce

- From any page on Rock select the bell icon near the search bar. 
- Click on 'View Reminders'
- Try selecting any person
- See error

### Rock Version

Confirmed on V 15.0 (1.15.0.16) and V16.0 (1.16.0.5) 

### Client Culture Setting

 en-US

**Comment by adamhann** [comment]
I can also confirm that we have this issue as well. Any chance this can get fixed in 15.3/16?

**Comment by chead4** [comment]
@adamhann We have confirmed this is an issue and it is planned for v15.2/16.1
