### ISSUE TITLE
Dataview - Attendance in Group Type not populating

### ISSUE THREAD

**Issue by lizrose20** [SparkDevNetwork/Rock#5479]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When trying to get a data view of people that have attendance in a group type, no one is populating in the data view, even though it can be confirmed in data analytics.  For us, we are trying to get at anyone that has attendance in Group Type Kids Check-in area. 

### Expected Behavior

People would be in the data view that have attended in the last 6 months for the group type and it's child group types.

### Actual Behavior

If child group types are those groups that contain the attendance data, and you do not select each child group type no data will appear. 

### Steps to Reproduce

- Go to Data Views
- Create new data view
- Criteria: Applies to Person, Attendance in Group Types
- Select the group type that has child group types for attendance but not the child group types.
- Select include child group type(s) 
 ![GroupType](https://github.com/SparkDevNetwork/Rock/assets/50717886/2ba9704a-8b1c-4550-b9cd-85bc3077292b)
- Save
- See error - no one in the data view.

### Rock Version

v15

### Client Culture Setting

en-US

**Comment by JimMichael** [comment]
We are seeing the same problem here on 15.1 alpha. I think it's only a problem when you have multiple levels of group types (areas) for check-in, thus it's not possible to dupe on rock demo unless you reconfigure some group types.

Here's what (part of) our Weekly Service Check-In Area looks like
![image](https://github.com/SparkDevNetwork/Rock/assets/3903408/87e9c1d3-8799-4f86-a096-c90146cec7d8)

If I choose _KidsCrossing Area_ (and have _Include Child Group Types_ enabled), 14.2 returns kids, but 15.1 does not. 

If I choose the indivdual sub-areas the Groups are actually in, 15.1 DOES return kids. So it seems like 15.x is not traversing multiple levels of Child Group Types.
