### ISSUE TITLE
Workflow Change Log Addition Hides Workflow's Description

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#5483]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When adding a Change Log note to a Workflow, the description in the workflow block gets stripped from the HTML. Clicking cancel or successfully adding a note doesn't make the description visible again, since it has been removed from the html document. Upon refreshing the page, the description is visible again unless a new note is added.

This is a minor bug. Rock performance is not hindered or affected. Just a UI bug as far as I can tell.

![screencapture-rock-rocksolidchurchdemo-admin-general-workflows-2023-06-15-14_44_11](https://github.com/SparkDevNetwork/Rock/assets/5738650/080b71a2-ad7d-4793-8982-46b03075558a)

![screencapture-rock-rocksolidchurchdemo-admin-general-workflows-2023-06-15-14_44_24](https://github.com/SparkDevNetwork/Rock/assets/5738650/09845659-b28c-47db-b6fb-d9b9c95cf2db)

### Expected Behavior

Workflow's description to remain visible.

### Actual Behavior

Description is removed from the HTML when adding a Change Log note to the workflow. As far as I can tell, this is not affecting the actual data in the DB, only removes the description from the rendered page.

### Steps to Reproduce

- Go to a workflow with a description (or create a temp workflow with a description)
- Click the add button under Change Log
- The rendered description is removed from the HTML code.

### Rock Version

14.2, 15.0, 15.1.1 ALPHA

### Client Culture Setting

en-US

**Comment by JimMichael** [comment]
We've seen this behavior ever since the change log was added, but it only "removes" the description when you add/save the note. Reloading the page immediately after brings it back.

Does reloading the page not bring the description back for you, and it's actually "gone" (not there when you edit the workflow again)?

**Comment by nairdo** [comment]
@BEGamache We _were_ able to reproduce this in an alpha version of v16 (1.16.0.6) but, as of the final release (1.16.0.12), this problem/behavior was fixed.  _I spent some time looking for the change but I couldn't find it and don't want to waste too much time on that._  (If I come across it in the next several days I'll post the commit here.)

https://github.com/SparkDevNetwork/Rock/assets/383807/613178b7-b33d-4099-b100-6e2163d3b907
