### ISSUE TITLE
Registrants Placement bombs don't act independently

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#5484]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

May be fixed by #5051 in 15.1?

If an event registration has two types of placement groups: Tables, BreakoutGroups, and a person is placed into [Table 1] of the Tables placement group, then the Placement Bombs on the Registrants page will show two bombs for two placement groups, but both will be lit green, and the hover over text for both will be the name of the first placement group (Event name Table 1)

The two placement group bombs should, I think, be acting independently.

Registration Template - showing two placement groups.
![placement-1](https://github.com/SparkDevNetwork/Rock/assets/4658177/eb49b16f-ee94-4a07-82cc-144e4a9cf55b)

Darling is placed in Table 1 of the Tables group.
![placement-2](https://github.com/SparkDevNetwork/Rock/assets/4658177/5c8bd5a9-0fc3-4aab-b063-5d470f4b5f48)

But is not in any Breakout placement groups.  (Note list of Registrants doesn't show as per #5051.)
![placement-3](https://github.com/SparkDevNetwork/Rock/assets/4658177/06ca35a0-620d-4b55-a010-ea3ab1e52aa3)

Yet on the list of Registrants - the Placement bombs show both green, and mouse over shows Table 1 for both bombs.

The bombs should act independently for the Placement groups.
![placement-4](https://github.com/SparkDevNetwork/Rock/assets/4658177/7f85310e-4c07-4780-a941-57d52dfc5ad8)

### Expected Behavior

Placement bombs should act independently.

### Actual Behavior

Placement bombs both show the same for the first Placement Group, or the only Placement group a person is in.

### Steps to Reproduce

Add registration event.
Add two placement groups.
Create group options with the placement groups.  (E.g. Tables: Table1, Table2, Table3;  Breakout: Group1, Group2 etc)
Add registration and registrant.
Assign registrant to first placement group - Table 1.
View list of Registrants.
Observer Placement bombs.

### Rock Version

Rock McKinley 15.0 (1.15.0.16)

### Client Culture Setting

en-NZ

**Comment by chead4** [comment]
@ElimAdmin Hi Ken Please provide more clarity on this issue as I was not able to recreate this issue.  A video documenting the issue would be very much appreciated.

**Comment by chead4** [comment]
Closing this issue at this time.  If you experience this issue again please include a video documenting the issue and we can reopen at that time.
