### ISSUE TITLE
Inherited Permissions are displayed incorrectly for Attributes

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#5487]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When viewing security settings on a person attribute, it does not show Inherited Permissions from the Attribute entity even though it enforces that inherited permission. 

### Expected Behavior

If security for person attributes is checking security on the Attribute entity type, it should be reflected when viewing the Security settings for the person attribute.

### Actual Behavior

Security on the Attribute entity is used/enforced even though it does not appear in the Inherited Permissions list

### Steps to Reproduce

- Go to Admin > Security > Entity Administration
- Edit the Security for the 'Rock.Model.Attribute' Entity and add an Item Permission denying all user's Edit access:

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/c8c7fe41-ee94-464f-bdfb-b41f7176d03f)

- Go to Admin > General Settings > Person Attributes
- Edit the Security for any person attribute ("Employer" for example)
- Notice the inherited permissions do not show the item permission we just added to the Attribute Entity and it appears that a Rock Admin should be able to edit this attribute.

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/60124f40-adc1-4073-8e4b-a7af21de71c7)

- Go to a user profile logged in as a Rock Admin
- Try to edit the "Employer" attribute.
- You will not be able to (screenshot is in edit mode for the Employment category)

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/bd812efc-eae1-44d7-9504-9950449e084c)

- If you remove the "All User" Deny item permission from the Attribute Entity's Edit tab, you will be able to edit the attribute on the person profile.

### Rock Version

v14.2, v15.0

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
The upcoming change will indicate if and when security has been applied to the base entity. However, for future reference, we strongly advise against adding security to base-level models/entities. Although there is a location in Rock for adding these, it is generally reserved for very specific cases and typically managed by the core team when new models are introduced. In the situation described, there's a risk of inadvertently granting edit access to **all** attributes if the 'parent authorization' inheritance is not fully understood.
