### ISSUE TITLE
Insights - Object Reference Error

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#5490]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When pulling up the new insights page in v15 I get the following error.

<img width="1440" alt="Screenshot 2023-06-22 at 3 04 20 PM" src="https://github.com/SparkDevNetwork/Rock/assets/1486523/2cf58c1c-5911-444f-98df-9e9d14b9b02c">

I do not see this error when trying to reproduce on demo site. 

Sorry this is the least descriptive I've ever been on a bug report. I just don't know what the insights page does or what's happening. I wasn't too worried about it because I thought it was just laying some groundwork for future stuff, but when mentioned in rocket chat Jon said I should submit a bug. 

https://chat.rockrms.com/group/rock-stars?msg=4Sz3J5bTrotHvvQvi

### Expected Behavior

Not to get the error. Other people in the community are able to pull up the page but I am not. 

### Actual Behavior

I get the error.

### Steps to Reproduce

go to tools > insights. Error occurs. 

### Rock Version

15.0

### Client Culture Setting

en-US

**Comment by leahjennings** [comment]
This also occurs on our instance running v15.0 and dev instance running v15.1.
<img width="1576" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/64dc1c4e-e137-4f95-ab1c-1aca64d98ad8">
