### ISSUE TITLE
Can't bulk update attributes with "Enhanced for Long Lists" dropdowns

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/Rock#5491]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

If a person attribute has a field type that uses a dropdown list and has the "Enhanced for Long Lists" setting checked, it will show up as disabled on Bulk Updates. I have only tested this with Defined Values, but I assume it's true of any dropdown with the enhanced functionality enabled.
![image](https://github.com/SparkDevNetwork/Rock/assets/1696714/ca5b9e79-8ed3-426b-90f9-f05b3a5e12aa)

It looks like the HTML for the options does exist onthe page. It's just not visible or available to be selected because the Chosen control is disabled. My guess is that the Chosen JavaScript just isn't getting initialized when the checkbox is checked for the attribute.
![image](https://github.com/SparkDevNetwork/Rock/assets/1696714/897c156f-198a-448b-a699-7d020634f41d)

### Expected Behavior

Checking the box for attribute on the bulk update form should enable the dropdown and allow you to select from the available options.

### Actual Behavior

The dropdown list remains disabled, so it's impossible to choose any of the options. 

### Steps to Reproduce

1. Initiate a bulk update
2. Go to the Childhood Information section and check the box for Ability Level
3. Notice that the dropdown becomes enabled and you can select an option
4. Go to the Person Attributes management page
5. Edit the Ability Level attribute and check the "Enhanced for Long Lists" checkbox
6. Initiate a new bulk update
7. Go to the Childhood Information section and check the box for Ability Level
8. Notice that the dropdown does NOT become enabled

### Rock Version

14.2 & 15.0

### Client Culture Setting

en-US

**Comment by afewkes** [comment]
We are seeing this same behavior on an attribute with a field type of person.  When trying to do a bulk update on the attribute, the person picker dropdown is not displayed.  In our case we are trying to bulk update a group member attribute.

**Comment by unlearnd** [comment]
Hi @afewkes ! I couldn't reproduce this issue with a field type of Person, but I did see it also affected the Group Member Field Type (see sceenshot). That issue should be resolved as part of this issue.

![image](https://github.com/SparkDevNetwork/Rock/assets/26026279/d971d5a6-d7ce-49b8-a4e1-3fc868ad5e5d)

Additionally, Rock is all about community. A key part of strengthening this bond is knowing who we're engaging with. Could I ask you to include your name, organization, and a photo on your GitHub profile? It's a simple way to put faces to names, fostering a more connected and personal community atmosphere.

**Comment by JRichmond27** [comment]
@unlearnd is it safe to assume that the fix also takes care of Defined Value field types like the Ability Level person attribute?

**Comment by unlearnd** [comment]
@JRichmond27 Yes that's right - this is also fixed for the Defined Value field types that use "Enhanced for Long Lists".
