### ISSUE TITLE
Prayer Card View Block's Prayed Workflow Field not Setting Workflow Attribute Successfully

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5500]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

In the block settings for the Prayer Card View block, there is a "Prayed Workflow" field. The tooltip states _"...Additionally if the workflow type has any of the following attribute keys defined, those attribute values will also be set: PrayerOfferedByPersonId."_ 
![Screenshot 2023-07-05 at 08 34 27](https://github.com/SparkDevNetwork/Rock/assets/23226974/a21974b6-93b5-48d0-aacc-9b0482e9c161)

However this does not seem to be working properly. The workflow is launching successfully but the attribute `PrayerOfferedByPersonId` is not being set.

Attribute defined in the Workflow Type:
![Screenshot 2023-07-05 at 08 34 49](https://github.com/SparkDevNetwork/Rock/assets/23226974/7b5dcda3-3223-4579-a81d-b0244d16efde)

Attribute Value was not set:
![Screenshot 2023-07-05 at 08 34 10](https://github.com/SparkDevNetwork/Rock/assets/23226974/0485e021-1985-4955-b779-03aa508cd102)

### Expected Behavior

`PrayerOfferedByPersonId` be set successfully in the Workflow.

### Actual Behavior

`PrayerOfferedByPersonId` is not set successfully in the Workflow.

### Steps to Reproduce

- Create a Workflow Type with an attribute with the key: `PrayerOfferedByPersonId`.
- Setup the Prayer Card View Block, edit the settings, and add your Workflow to the Prayed Workflow field.
- Click "Pray" in the Prayer Card View block.
- See that the Workflow did launch, but `PrayerOfferedByPersonId` is not set in the Workflow.

### Rock Version

v14.2, v15.1, v16.0

### Client Culture Setting

en-US

**Comment by jonedmiston** [comment]
@mikedotmundy Sorry that help text wasn't correct. The attributes should be: 

1. PrayerOfferedByPersonAliasGuid -> Best for setting into a text field type
2. PrayerOfferedByPerson -> Best for setting into a Person field type

In the end they both return the same data (PrimaryPersonAliasGuid).  

The good news is that it works today with those keys. I'll update the help text for v16.1.

**Comment by mikedotmundy** [comment]
Awesome, thanks @jonedmiston!
