### ISSUE TITLE
Event Registration Digital Signature/Registrar Options Issue

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5506]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

On an Event Registration, when using a Digital Signature Document _and_ setting the Registrar Options to `Use First Registrant`, you are not able to progress forward in the registration past the Registrant Form(s) and on to the Digital Signature page. The `Next` button does nothing. Setting the Registrar Options to any other option and there is no issue - you can move forward to the Digital Signature.

Upon clicking "Next" in the registration, an exception is also created:
<img width="1628" alt="Screenshot 2023-07-06 at 20 48 39" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/c40acc79-9ce3-44b3-a5fd-3807c22e2593">

Stack Trace:
```
at Rock.Blocks.Event.RegistrationEntry.UpdatePersonFromRegistrant(Person person, RegistrantInfo registrantInfo, HistoryChangeList personChanges, RegistrationSettings settings) in \Rock.Blocks\Event\RegistrationEntry.cs:line 1818
   at Rock.Blocks.Event.RegistrationEntry.GetSignatureDocumentData(RegistrationEntryBlockArgs args, Guid registrantGuid) in \Rock.Blocks\Event\RegistrationEntry.cs:line 519
```

### Expected Behavior

Should be able to use a Digital Signature Document _and_ set the Registrar Options to `Use First Registrant`.

### Actual Behavior

You are unable to use a Digital Signature Document _and_ set the Registrar Options to `Use First Registrant`.

### Steps to Reproduce

<img width="1724" alt="Screenshot 2023-07-06 at 20 46 10" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/3812edc1-4223-4f68-a360-1fa4b6b44fb2">

<img width="1726" alt="Screenshot 2023-07-06 at 20 46 20" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/7bc5e2dd-c098-4bd0-a416-c507a8c9a8a5">

<img width="1725" alt="Screenshot 2023-07-06 at 20 47 56" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/102c5404-cad3-443b-80fc-0c0cb4f80f98">

### Rock Version

v14.2, v16.0

### Client Culture Setting

en-US

**Comment by cabal95** [comment]
@mikedotmundy Thanks for the pictures detailing the reproduction steps.
