### ISSUE TITLE
Age filter not working in data views

### ISSUE THREAD

**Issue by lizrose20** [SparkDevNetwork/Rock#5508]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Age filters are not working in data views. 

### Expected Behavior

Person data view would be able to use the age filter.    

### Actual Behavior

When filtering a data view by age, only a few people with an age are showing up, even though they have a birthday.  
On the demo site, if you just look at the Decker family, they have a birthday on their profile 

![Decker_Profile](https://github.com/SparkDevNetwork/Rock/assets/50717886/94f963d5-9d15-4755-a22d-82a0b521d363)

![Under35_Dataview](https://github.com/SparkDevNetwork/Rock/assets/50717886/016c7e62-bb06-4826-90a0-4e6daa5480ff)

### Steps to Reproduce

- Confirm that people have a birthday on their profile.  
- Age shows. 
- Create a data view that uses an age filter
- Not everyone with a birthday will show in the data view.

### Rock Version

v15.1

### Client Culture Setting

en-US

**Comment by jonedmiston** [comment]
@lizrose20 Hi Liz! Can you confirm this is still an issue? Appears to be working now on the demo site. Also, was this issue confirmed only on the demo site. The reason why I ask is that recently Age was calculated (nightly) and added to the Person model in the database (fast). Before this it was calculated every time a data view was run for each person in the datebase (slow).

I'm wondering if the incorrect data that was reported was from the Age not being calculated in the database correctly on the demo site.

Anyways, would appreciate it if you could confirm this is now correct on the demo site and/or v16.0.

**Comment by jonedmiston** [comment]
Closing due to no response. Please feel free to re-open if this is still an issue.

**Comment by lizrose20** [comment]
Sorry, Jon. I was off last week, and am still catching up.  Yes, it looks like this is fixed now from a quick test.



Liz Rhoades
Director of Data & Analytics
CedarCreek Church

Need to schedule a meeting click ***@***.***?anonymous&ep=plink>.

e. ***@***.******@***.***>
o: 419-661-8661 x116
