### ISSUE TITLE
AjaxControlToolkit Exception

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#551]
Hey guys, I've seen similar bugs on the issue tracker, so forgive me if this is a duplicate - but I feel like it's different enough to post details.

After updating to .13, and then .14, I'm still getting sporadic  HttpUnhandledException in System.Web exceptions.  Here's the entire thing:

>HttpUnhandledException in System.Web
>Message
>
>Exception of type 'System.Web.HttpUnhandledException' was thrown.
>Stack Trace
>
>at System.Web.UI.Page.HandleError(Exception e)
>at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean >includeStagesAfterAsyncPoint)
>at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean >includeStagesAfterAsyncPoint)
>at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean >includeStagesAfterAsyncPoint)
>at System.Web.UI.Page.ProcessRequest()
>at System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
>at System.Web.UI.Page.ProcessRequest(HttpContext context)
>at ASP.themes_rock_layouts_rightsidebar_aspx.ProcessRequest(HttpContext context)
>at >System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep>.Execute()
>at >System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep>.Execute()
>at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& >completedSynchronously)
>
>
>-ArgumentException in mscorlib
>
>Message
>An item with the same key has already been added.
>
>Stack Trace
>at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
>at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
>at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
>at AjaxControlToolkit.ToolkitScriptManagerHelper.GetAssembly(String name)
>at AjaxControlToolkit.ToolkitScriptManagerCombiner.ScriptEntry.LoadAssembly()
>at AjaxControlToolkit.ToolkitScriptManagerCombiner.IsScriptCombinable(ScriptEntry scriptEntry, >Boolean enableCdn)
>at AjaxControlToolkit.ToolkitScriptManagerCombiner.WriteScripts(List`1 scriptEntries, TextWriter >outputWriter, Boolean enableCdn)
>at AjaxControlToolkit.ToolkitScriptManagerCombiner.GetCombinedRegisteredScriptContent(Boolean >enableCdn)
>at >AjaxControlToolkit.ToolkitScriptManagerCombiner.GetCombinedScriptContentHash(HttpContextBas>e context, String[] bundles, Boolean enableCdn)
>at AjaxControlToolkit.ToolkitScriptManager.LoadScriptReferences(HttpContextBase context, String[] >bundles, Boolean forCombineAndMinify)
>at AjaxControlToolkit.ToolkitScriptManager.OnLoad(EventArgs e)
>at System.Web.UI.Control.LoadRecursive()
>at System.Web.UI.Control.LoadRecursive()
>at System.Web.UI.Control.LoadRecursive()
>at System.Web.UI.Control.LoadRecursive()
>at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean >includeStagesAfterAsyncPoint)

This happened right after the update, I also get an email about it once every few days.  I don't really have much more information, and I'm not what specifically triggers it (except the update)

If I can provide any more information, please let me know. (Again, I'm on version .14)  Thanks!

**Comment by azturner** [comment]
We're removing the AjaxControlToolkit in v3.0
