### ISSUE TITLE
Grade and Age Check-In Workflow Filter removing ALL Groups. 

### ISSUE THREAD

**Issue by adamhann** [SparkDevNetwork/Rock#5516]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

We've recently learned about a check-in workflow filter called **Filter Groups by Grade & Age**. We decided to implement this filter because we have multiple kid check-in groups where age and grade overlap. We wanted to filter out groups that were age-based if there was a grade. For example, if someone was 5 and could check into pre-K AND they are a Kindergartener, it should only show the Kindergartner check-in group. This works as intended! 

**The problem is it will also filter out every other single group that the child is eligible for. It filters and Data View Filter groups and Group Membership groups.** 

There are times when we have kids who are eligible for age/grade, and a data view check-in for a special room they get to be in. With this filter all groups are removed as an option in check-in, not just the Age groups. 

Here's an example of what the options look like for Alex Decker (based on how I set it up in the demo site) using the standard filters in check-in. Individual filters for Age and Grade. 

**Workflow Filter Setup (Standard)**
![Screenshot 2023-07-17 at 8 27 57 AM](https://github.com/SparkDevNetwork/Rock/assets/23084345/ec82d0e9-6954-4c41-8282-eca5700c2f17)

**Options to check in to**
![Screenshot 2023-07-17 at 8 41 18 AM](https://github.com/SparkDevNetwork/Rock/assets/23084345/ed6f96b3-a3e3-44bc-bf0f-ce5993341f22)

**Workflow Filter Setup - Using Filter by Grade And Age**
![Screenshot 2023-07-17 at 8 27 31 AM](https://github.com/SparkDevNetwork/Rock/assets/23084345/aba6b0a6-3a8a-4b94-821d-f5e4d32a2d86)

**Options to check in to (only the Grade filtered group)**
![Screenshot 2023-07-17 at 8 26 25 AM](https://github.com/SparkDevNetwork/Rock/assets/23084345/00270a3f-362a-4f03-a2a6-cb110b17ea3e)

### Expected Behavior

In this scenario of using the **Filter Groups by Grade and Age**, I'd expect the **Group Membership** and **Data View** filtered groups to show up still and the Grade and Age filter only by filtering out Age-filtered groups. Similar to how it works when using the standard setup. 

### Actual Behavior

The **Filter Groups by Grade and Age** remove ALL groups and only return groups that are eligible by grade. 

There seems to be an inconsistency in how the "Remove" function works in this filter compared to the other filters. Other filters only remove groups that are tied to their filter. Like the **Filter by Age** action, only remove other age-based groups. This **Filter Groups by Grade and Age** is removing all groups. 

### Steps to Reproduce

- Set up check-in groups that use different types of filters. (Grade, Age, Dataview, Group Membership)
![Screenshot 2023-07-17 at 8 28 16 AM](https://github.com/SparkDevNetwork/Rock/assets/23084345/7b291b35-8993-4bdd-b1bc-77773e29e5f0)

- Make sure that one person is able to check into all of those different groups. 
- Turn on a test schedule for those groups, search for that person, and view all of the different groups they can check in to.
- _(Side Note) In the example above, I have the check-in config setup with **Check-in Type** as Family and **Auto Select Options** as People and their Group/Location. It makes it easier to see all the groups, but the problem exists with both setups._ 
- Check in the person eligible for all the groups using the standard check-in workflow setup. You will see all group options as long as you setup check-in correctly. :) 
- After confirming this, go to the Unattended Check-in workflow and make a copy. 
- In the new workflow, remove these two actions in the Person Search Activity. (Filter Groups by Age, Filter Groups by Grade)
- Add in this Activity the Filter Groups by Grade and Age. Move the filter to above the **Filter Groups by Gender** action. 
- It should look like this
![Screenshot 2023-07-17 at 8 27 31 AM](https://github.com/SparkDevNetwork/Rock/assets/23084345/e7f209bb-e922-4e38-94c7-476b3e11712e)

- Go to the **Family Select** page (by default, page 124) in the check-in cms page structure. Select the block settings for the **Family Select Block** and set the Workflow Type to your new workflow copy with the changes. 
![Screenshot 2023-07-17 at 8 29 35 AM](https://github.com/SparkDevNetwork/Rock/assets/23084345/1587a25e-d2af-476a-aa28-13494d27ddf8)

- After you make this change, try checking in the same person again. At this time, you should only get the group that is Filtered by Grade as the only option to check into. 

### Rock Version

15.1, 15.0

### Client Culture Setting

en-US

**Comment by karenn-ccbc** [comment]
We are on 14.2 and experienced this with our Middle School kids who also volunteer in our Kids Min. They were not getting the option to check into the Serve group (membership required) even at a different time schedule than the class that is grade based.

**Comment by chead4** [comment]
@adamhann & @karenn-ccbc Closing this issue as this will be included in the next gen version of Check-In.
