### ISSUE TITLE
Connection Request Board has Exception related to viewable Opportunities/Requests

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#5517]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Viewing a page with a Connection Request Board block from a user that can see the page/block, but not having view rights to any of the Connection Opportunities of Types in the block's settings, and not currently having any assigned Connection Requests of the Types selected in the block settings

![Screenshot 2023-07-17 at 2 09 18 PM](https://github.com/SparkDevNetwork/Rock/assets/19762670/d20d3edb-5a64-40a1-8636-94aacc69cbfb)

### Expected Behavior

The Connection Request Board should show that they have no Connection Requests assigned/visible to them

### Actual Behavior

An exception is thrown, preventing loading the page.  This means the user cannot view the page to positively know that no Connection Requests awaits them.

### Steps to Reproduce

_From Description_
[View] a page with a Connection Request Board block from a user that can see the page/block, but not having view rights to any of the Connection Opportunities of Types in the block's settings, and not currently having any assigned Connection Requests of the Types selected in the block settings.

### Rock Version

1.14.2

### Client Culture Setting

en-US

**Comment by NuclearTacos** [comment]
https://github.com/SparkDevNetwork/Rock/blob/5214f39f54fd4b8fe78041cd5ccf330bad7d8b17/RockWeb/Blocks/Connection/ConnectionRequestBoard.ascx.cs#L5122

As of this comment, the bug is still present in the develop branch.

You can see that the `_connectionTypeViewModels` only gets a value if the person `canView` an opportunty, or has a self-assigned request.  And if `_connectionTypeViewModels` is null by line 5122 (in the link) then `.Where()` will throw an exception like the screenshot.

![image](https://github.com/SparkDevNetwork/Rock/assets/19762670/2b41062f-14bf-4ab0-b1aa-2d50f9847cc3)

**Comment by chead4** [comment]
@NuclearTacos Hi, could you please provide screen shots for the steps to reproduce?
Thanks!

**Comment by NuclearTacos** [comment]
I'm sorry that I didn't originally screenshot the replication process because I was in a hurry, and the code very clearly lines up with the explanation and issue.


# Steps

Create a Connection Type and Connection Opportunity.  Deny someone the rights to view that Connection Type.
[You can do that here](https://rock.rocksolidchurchdemo.com/people/connections/types).
![image](https://github.com/SparkDevNetwork/Rock/assets/19762670/6a5b5f7a-bc02-46c2-b398-f69750214b75)

Set a Connection Request Board to only show that Connection Type
[You can do that here](https://rock.rocksolidchurchdemo.com/page/2635)
![image](https://github.com/SparkDevNetwork/Rock/assets/19762670/38da6801-f14a-42e9-9f4b-d7b74738564c)

View that page as the person that has been denied viewing rights to that Connection Type, get an error
![image](https://github.com/SparkDevNetwork/Rock/assets/19762670/b4f7915a-b9e1-4ef2-b1c5-bd1eaabd5068)
![image](https://github.com/SparkDevNetwork/Rock/assets/19762670/2328e88f-f998-4f01-a997-14d7783e9238)

**Comment by NuclearTacos** [comment]
Hopefully the code more clearly detailed will help too :)

_Lines that begin with `~` are paraphrased_
```
if ( _connectionTypeViewModels == null )
{
    . . .
    ~ foreach ( opportunity )
    {
         . . .
         canView = ~can view the Opportunity or is assigned a Connection Request of the Opportunity
         . . .
         if ( canView )
         {
            _connectionTypeViewModels = _connectionTypeViewModels ?? new List<ConnectionTypeViewModel>();
            . . .
         }
    }
    
    ~// _connectionTypeViewModels will be null if canView was never true.
    ~ _connectionTypeViewModels.Where( . . . 
}
```

And, in the case where the person cannot view any of the Opportunities on the board, nor is assigned any of the Connection Requests (if the opportunity is configured that way), then `_connectionTypeViewModels` will be null when the `.Where(` is called, which is what causes the exception screenshotted in the original post.
