### ISSUE TITLE
Obsidian Registration Entry updates Registrants original cost

### ISSUE THREAD

**Issue by nlBayside** [SparkDevNetwork/Rock#5519]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

In our Rock Instance, we have a few Registration Instances where we adjust the cost after a set period of time. This means that the earlier you register, the lower the cost will be for your registrants. However, since using the new Obsidian Registration Entry block we are experiencing these Registrations go up in price to the up-to-date cost. The registrants should have been locked into their original pricing.

This issue is related to [Obsidian Registration Payments after Registration Price has gone up](https://github.com/SparkDevNetwork/Rock/issues/5373). While this issue does solve the problem when the user sees the Cost Summary Vue component in their Registration. After they submit a payment, the cost increases to the current amount from the Registration Instance/Template.

I think this line is the reason why the Registrant cost is adjusting.
https://github.com/SparkDevNetwork/Rock/blob/5214f39f54fd4b8fe78041cd5ccf330bad7d8b17/Rock.Blocks/Event/RegistrationEntry.cs#L2055

This is the change that has been made to `GetRegistrationCostSummaryInfo()` in RegistrationInstanceService
https://github.com/SparkDevNetwork/Rock/blob/7c6fa37b090065ea58bf61c0aaf0f7fa06416cba/Rock/Model/Event/RegistrationInstance/RegistrationInstanceService.cs#L199

The `SubmitRegistration()` method has access to both the RegistrationEntryBlockArgs and the RegistrationContext, just like `GetRegistrationCostSummaryInfo()`, so this change should be a minor change to fix this.

### Expected Behavior

The Registrant's cost remains their original cost when they first signed up.

### Actual Behavior

The Registrant's original cost changes when they submit their Registration.

### Steps to Reproduce

- Create a Registration with cost set on the Registration Instance.
- Register someone with a base cost down payment, but not the full cost.
- Change the cost on the Registration Instance.
- Go back to the Registration to finish signing up (Original cost should still be there)
- Submit Registration after making full payment
- See that the cost of the Registrant has now changed to the cost on the Registration Instance (not their original cost)

### Rock Version

v15.1

### Client Culture Setting

en-US

**Comment by shauncummings** [comment]
Resolved in https://github.com/SparkDevNetwork/Rock/commit/b970e56fad08756e4ba10edbdfab1495b7ed14ad
