### ISSUE TITLE
Phone number not displaying - Transaction Entry V2

### ISSUE THREAD

**Issue by TheArkChurch** [SparkDevNetwork/Rock#5524]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Tell us what you see

When making a donation using the Giving V2 Block, when logged in, the persons phone number isn't displayed in the number box. This prompts the person to enter a number(already on their profile). Subsequently, Rock records this as a new phone number and disables SMS.

<img width="1362" alt="Screenshot 2023-07-20 at 12 42 53 AM" src="https://github.com/SparkDevNetwork/Rock/assets/38021725/e3890fe9-1e6a-426c-b46d-5642bfd11772">
<img width="1357" alt="Screenshot 2023-07-20 at 12 49 40 AM" src="https://github.com/SparkDevNetwork/Rock/assets/38021725/7d24d855-bd03-4eed-9828-7597437fd4e6">

### Expected Behavior

Expected Behavior

If a person has a phone number, it should be populated. As an admin, I would also expect for the SMS to stay enabled, especially for reoccurring givers.

### Actual Behavior

Actual Behavior

When a phone number is enter in a gift a new number is saved and the sms is set to false.

### Steps to Reproduce

- Make sure the person profile has a phone number with sms enabled.
- Make a gift on a transaction entry v2 block, adding the same phone number in the profile
- Check sms enabled in person history

### Rock Version

14 and 15

### Client Culture Setting

en-US

**Comment by otimoshc** [comment]
@TheArkChurch I can confirm that the phone number isn't being populated when a person has one on file. It looks like the pnbPhoneIndividual isn't being set [here](https://github.com/SparkDevNetwork/Rock/blob/4c708a2a8c181ff18d8895241423d75a154c8f93/RockWeb/Blocks/Finance/TransactionEntryV2.ascx.cs#L2188-L2198) once the target person is populated.

I also confirmed the second issue with a small modification after looking at the code. The issue isn't with sms but with the block not checking the mobile phone attribute after checking the home phone attribute. Instead if a home phone number doesn't exist, it adds a new "Home Phone" duplicating the "Mobile Phone" as seen in your screenshot.

**Comment by TheArkChurch** [comment]
For the home phone number duplication issue, it could be solved by

1.  Change instances of PERSON_PHONE_TYPE_HOME to PERSON_PHONE_TYPE_MOBILE
or
2. Add a Phone Type block setting to be used for this value when "Prompt for Phone" is set to Yes

I'm not sure which way would be the best way to handle this. We rarely use the home phone number type and would not use it in this block or for giving.
