### ISSUE TITLE
Lava does not work in From Name or From Address Fields in Scheduling Confirmation Email

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#5527]
### Please go through all the tasks below

- [x] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When using Lava in the From Name or From Address Fields in the Scheduling Confirmation Email it does not process. The email comes form the system email address instead. 

<img width="1341" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/657005/d9a75ae2-7150-4482-9ad5-c09713bae93d">

### Expected Behavior

Lava wold be processed correctly and the email would come from the individual who scheduled them. The same lava works find in the body of the email. 

### Actual Behavior

Email comes from the system email address.

### Steps to Reproduce

- Go to System Communications
- Update the system communication to come from the person who scheduled them using the lava below:

From Name: {{ Attendance.ScheduledByPersonAlias.Person.FullName  }}
From Address: {{ Attendance.ScheduledByPersonAlias.Person.Email }}

-Go schedule someone to serve
- Email will come from the generic system email address and not the scheduler. 

### Rock Version

15.1

### Client Culture Setting

en-us

**Comment by nathanp** [comment]
+1 for this issue.  Right now if people reply to the scheduling email, the responses are going to our generic admin email. So then we have to forward the email to the corresponding team leader.

**Comment by Kwame-Agyei** [comment]
> This is wonderful, will this fix also be applicable to the Scheduling Reminder Email? It's the same way. Thank you!

Yes @KCKurz This fix should also resolve the issue with the Scheduling Reminder Email
