### ISSUE TITLE
Note Type - File Attachments

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#5530]
### Please go through all the tasks below

- [ ] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

We added a file attachment type to a note type in our Rock instance. It works fine for Rock Administrators but does not work for any other security role. It does not show the file upload option.  

<img width="1435" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/657005/7ccc854c-a5cd-4b5d-af7b-30ff2a82fbdd">

### Expected Behavior

The user should see the file upload box if they have security to upload files of the type used as the note type attachment. 

Should look like this:
<img width="691" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/657005/543aa2ec-f37a-4ca6-b19f-02e9a86e70d3">

### Actual Behavior

End user sees no option to upload file

Looks like this:

<img width="663" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/657005/d2e29260-046c-41e6-a775-0e11705b0bc2">

### Steps to Reproduce

1. Go to System Settings and Note Types.
2. Select any note type that "Staff Workers" security role has edit access to
3. Add a File Attachment Type that "Staff Workers" have access to upload files to.
4. Login as a user in the "Staff Workers" security role. 
5. Try to add a note of the specified note type
6. Notice you have no option to upload a file.
7. Do steps as Rock Administrator  - and you will see the upload file option.

### Rock Version

15.1

### Client Culture Setting

en-us

**Comment by chead4** [comment]
@austinspooner Hi Austin.  The note attachment feature was not fully implemented with the UI and was originally created for plugin requests.  What block are you seeing the ability to upload attachments when logged in as a Rock Administrator?

**Comment by austinspooner** [comment]
This issue is with the timeline block on the person profile page

**Comment by nairdo** [comment]
@austinspooner  We think we've figured out what is happening.  The "attachment" settings on the NoteType really are nothing that core does anything with.  

What you must have is a custom _attribute_ on that custom NoteType, and we suspect it must not have the right edit permissions.

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/396c7582-beac-4b2f-b7c0-719a94f6a919)

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/dd698681-2a4c-4374-93e3-2a495e703575)

Here's a video showing that setup in action -- with Cindy Decker (Staff-Like) creating notes with the ability to use/edit a custom "Incident Report" attribute:


https://github.com/SparkDevNetwork/Rock/assets/383807/6999a33e-6a41-45f5-b6ba-3205d3e02827

We'll close this on the assumption that _this was_ the issue and resolution, but please feel free to re-open if that isn't the situation.
