### ISSUE TITLE
Registration Attribute of Address Throws Error in Obsidian Block

### ISSUE THREAD

**Issue by kfrazier13** [SparkDevNetwork/Rock#5532]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When using the new Obsidian Block for an Event Registration that has a registration attribute using an address field, a **FormatException in mscorlib** error is thrown when a user tries to access the registration instance to view all of the registrations that have been created.

<img width="523" alt="Screenshot 2023-07-26 at 8 51 59 AM" src="https://github.com/SparkDevNetwork/Rock/assets/129417960/5df92205-512b-41bc-9e40-5bee434dc9cf">

### Expected Behavior

When using the new Obsidian Event Registration Block, it would be expected that registrations including an address in the registration attributes, you would be able to access the registrations which could be done using the same registration template using the original Event Registration Block.

### Actual Behavior

When the registrations are submitted and you click on the Registration Instance to view the registrations, you are not able to view any of the registrations because of an error. The only way to view the individuals who have registered for an event is to know the Registration Instance Id and the URL for the Registrants page so the Instance Id can be entered manually into the URL. However, the Registration page cannot be accessed.

<img width="1575" alt="Screenshot 2023-07-26 at 8 52 57 AM" src="https://github.com/SparkDevNetwork/Rock/assets/129417960/b8866902-a9cd-4393-84ce-0067451f6432">

### Steps to Reproduce

1. Create an Event Registration Template, include an address field as a Registration Attribute.

<img width="1201" alt="Screenshot 2023-07-26 at 8 57 12 AM" src="https://github.com/SparkDevNetwork/Rock/assets/129417960/9dcb889b-419f-4142-b09c-c92d5948d901">

2. Create a Registration Instance using the Registration Template you created.

3. Go to the registration page on the external site and change the registration block to the new Obsidian Registration Entry Block.

4. Fill out the registration form.

<img width="1215" alt="Screenshot 2023-07-26 at 8 50 15 AM" src="https://github.com/SparkDevNetwork/Rock/assets/129417960/06c6061c-25e4-4fe3-abab-9a3cd6dce9ef">

<img width="1191" alt="Screenshot 2023-07-26 at 8 50 25 AM" src="https://github.com/SparkDevNetwork/Rock/assets/129417960/f7c10e61-7310-492e-9346-b6e1e8bf2843">

7. Go to the Registration Template and click on the Registration Instance for the event

<img width="1197" alt="Screenshot 2023-07-26 at 8 51 41 AM" src="https://github.com/SparkDevNetwork/Rock/assets/129417960/9df8d116-c038-4ec2-a03e-b60f1e264f3e">

8. See error page.

<img width="523" alt="Screenshot 2023-07-26 at 8 51 59 AM" src="https://github.com/SparkDevNetwork/Rock/assets/129417960/c4328bc7-cfcb-4d25-b731-9fa7b9a125f4">

<img width="459" alt="Screenshot 2023-07-26 at 8 52 06 AM" src="https://github.com/SparkDevNetwork/Rock/assets/129417960/1d95cc42-3eb1-4351-9d36-2c9ce7ab0fcd">

### Rock Version

15.0

### Client Culture Setting

en-US

**Comment by RufenachtPW** [comment]
This is also happening on version 14.3

**Comment by JoshuaMaiorino** [comment]
I've written a SQL Script that will clean up the bad data.  You can add this code to a workflow / job that runs to clean these up as a work around until the bug is fixed.  In case this helps anyone else:
`DECLARE @ForeignKey nvarchar(50) = 'RegistrationAttributeId'

INSERT INTO [Location] (
	IsActive
	, Street1
	, Street2
	, [City]
	, [State]
	, Country
	, County
	, [Guid]
	, ForeignId
	, ForeignKey )
SELECT
	IsActive = 1
	, Street1 = ad.Street1
	, Street2 = ad.Street2
	, [City] = ad.City
	, [State] = ad.[State]
	, Country = ad.Country
	, County = ad.locality
	, [Guid] = NEWID()
	, ForeignId = av.Id
	, ForeignKey = @ForeignKey
FROM
	Attribute a
	JOIN AttributeValue av
		ON av.AttributeId = a.Id
	CROSS APPLY OPENJSON( av.[Value] ) WITH ( 
		street1 nvarchar(50)
		, street2 nvarchar(50)
		, city nvarchar(50)
		, [state] nvarchar(50)
		, [postalCode] nvarchar(50)
		, country nvarchar(50)
		, locality nvarchar(50) ) ad
	LEFT JOIN [Location] l
		ON l.ForeignKey = @ForeignKey
		AND l.ForeignId = av.Id
WHERE
	a.FieldTypeId = 108
	AND IsJson( av.[Value] ) = 1
	AND l.Id is null

UPDATE av SET
	[Value] = LOWER( l.[Guid] )
FROM
	[Location] l
	Join AttributeValue av
		ON av.Id = l.ForeignId
WHERE
	l.ForeignKey = @ForeignKey
	AND av.[Value] != LOWER( l.[Guid] ) `

**Comment by chead4** [comment]
@kfrazier13 I am closing this issue as I am unable to recreate this issue in v16.0 (currently in beta).  Please feel free to reopen.
