### ISSUE TITLE
Obsidian Registration Block Applies Auto Discounts when Criteria Not Met

### ISSUE THREAD

**Issue by david-axelson** [SparkDevNetwork/Rock#5535]
If a registration template is created and auto discounts are created for it, and those discounts have criteria set for Minimum and Maximum registrants, the registration will apply the last discount in the list, regardless of whether or not the registration meets the criteria. The screen shots below show a registration template with 2 discounts set to auto apply, both have a minimum and maximum number of registrants set.

![DiscountList](https://github.com/SparkDevNetwork/Rock/assets/74628512/b7e6a03c-99d1-4a3f-8a24-9e6826694598)
![DiscountDetail](https://github.com/SparkDevNetwork/Rock/assets/74628512/5a6f340a-c8bd-4a86-86d3-0b47b8305b59)

To get a discount the registration would need between 2 and 5 children. When registering a single child the old registration block correctly does not apply a discount.

![OldBlockNoDiscount](https://github.com/SparkDevNetwork/Rock/assets/74628512/1f4ba872-ebb0-47d4-9503-93e69646b4c9)

With the obsidian registration entry block with one child the second discount is applied. It appears to apply whatever the last discount is in the list. If we remove the second discount, the first will be applied for a single registrant.

![ObsidianBlockDiscount](https://github.com/SparkDevNetwork/Rock/assets/74628512/d8d105bb-33de-457d-9473-ecd9b3b14460)

Both blocks above are on the same page being used for the same registration instance.

We have seen the same behavior on our site, the demo site and pre-alpha site.

### Expected Behavior

Discounts should not auto apply unless the requirements are met.

### Actual Behavior

If any auto discounts exist with requirements one will be applied regardless of whether or not the requirements are met.

### Steps to Reproduce

Create a registration template and give it at least one discount that is applied automatically and has settings for Maximum and Minimum registrants.
    Complete a registration that is outside the minimum and maximum and doesn't qualify for the discount. A discount will be applied though the requirements are not met.

### Rock Version

15.0, 15.1, 16.0

### Client Culture Setting

en-US

**Comment by ethan-sparkdevnetwork** [comment]
This was already fixed in commit: 687533a7
