### ISSUE TITLE
Form Builder Does Not Work Unless You Are An Administrator.

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#5537]
### Please go through all the tasks below

- [ ] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Users in the role RSR Staff Workers can create forms using the new form builder blocks but are unable to add fields to them or edit then after being built. 

![2023-08-03_08-10-50 (1)](https://github.com/SparkDevNetwork/Rock/assets/657005/7f85081e-a0fd-45c2-a217-b13a1e8b8f7b)

### Expected Behavior

Expected Behavior

Should work like this

![2023-08-03_08-11-41 (1)](https://github.com/SparkDevNetwork/Rock/assets/657005/d53c36e1-2f25-402b-8e65-63c346431d22)

### Actual Behavior

Actual Behavior!

[2023-08-03_08-10-50 (1)](https://github.com/SparkDevNetwork/Rock/assets/657005/7f85081e-a0fd-45c2-a217-b13a1e8b8f7b)

### Steps to Reproduce

1. Go to form builder
2. Create form with a user is role RSR Staff Works
3. Get results shown above

### Rock Version

15.1

### Client Culture Setting

en_us

**Comment by austinspooner** [comment]
Is there any update on this one?

**Comment by zackdutra** [comment]
Hey @austinspooner we fixed this by adding Edit permissions to the category of the form. In your case, that would be the CG Leader Groups category. It seems to not inherit beyond one parent, so adding Edit permissions to the top category doesn't work, but adding edit permissions to the immediate parent does, in our case.
