### ISSUE TITLE
Workflow Attributes via Liquid in Reports Not Working

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#554]
When designing a report tied to a Workflow Data View, I can't access workflow attributes using Liquid.  For example, `{{ Name }}` DOES return the name of the Workflow; but `{{ Campus }}` or `{{ Workflow.Campus }}` won't return anything, even if there is a defined workflow attribute named campus and value set to it.

**Comment by swedd** [comment]
Here's another vote for this feature! Would be great to have!

**Comment by ElimAdmin** [comment]
And me.  I'm trying to work out how to report on Workflow registration entries.

**Comment by edmistj** [comment]
We can really see the need for this and have a solution in mind. At this point though it probably will be in v5.0.

**Comment by ElimAdmin** [comment]
@bwitting @swedd 
...in the meantime, here's one idea for using Excel's filters and Pivot Tables for reporting on Workflows that might help depending on your reporting requirements.

https://www.rockrms.com/Rock/Ask/Using/Questions/685#a2435

**Comment by edmistj** [comment]
This issue was moved to SparkDevNetwork/Rock-Issues#1

**Comment by arranf** [comment]
This works in 6.8.
