### ISSUE TITLE
Adding more than one dataview filter reverts filter control to previous, non-searchable field type

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5543]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When creating dataviews, only the first filter added by default is the new searchable dropdown field type. Any subsequent filter added to the dataview defaults to the old non-searchable dropdown field type. Once a filter is selected from the non-searchable dropdown, it updates the control to be the searchable kind.

### Expected Behavior

I would expect that any filter added to the dataview would exhibit the same behavior for the filter dropdown, allowing you to type in and search for a filter by name / keyword.

### Actual Behavior

Only the first filter dropdown added by default is searchable. Any other filters added are the old non-searchable type. 

### Steps to Reproduce

1. On the demo site, navigate to Tools > Data Views
2. Click on any category and then click the + button to create a new data view _(I used Communication Segments)_
3. Name the dataview, and set Applies To to Person
4. Set the first filter to "Existing Data View"
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/eb533cf5-e409-4e07-bb49-9a2c8ab401a3">

5. Choose any dataview in the dropdown
6. Add a second filter
7. Click on Person Fields and notice that the filter dropdown is the old, non-searchable style
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/389c15e8-87b5-4f70-97d4-41995dd15000">
 

### Rock Version

Rock McKinley 15.0 (1.15.0.16), Rock McKinley 15.1 (1.15.1.1)

### Client Culture Setting

en-US

**Comment by zackdutra** [comment]
Confirmed with us in 15.1 as well
