### ISSUE TITLE
Confusing message when sending schedule confirmations for a group type without a confirmation email template selected.

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/Rock#5546]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When clicking the Send Now button on the group scheduler for a group type that doesn't have a system communication template selected under "Schedule Confirmation Communication", the only thing that is displayed is a blank "Information" message box.

![image](https://github.com/SparkDevNetwork/Rock/assets/1696714/7f25581f-a069-4911-8a55-f0bb5114792b)

### Expected Behavior

A more informative message should be displayed that lets the user know that an email template isn't selected for that group type, and/or the group type should require a confirmation template when scheduling is enabled.

### Actual Behavior

A blank message box is shown with no indication of what happened.

### Steps to Reproduce

1. Enable group scheduling for a group type, but leave the "Schedule Confirmation Communication" field blank
2. Create a group using that group type 
3. Set up all necessary group scheduling details for the group, including a meeting location and schedule
4. Add at least one person to the group
5. Go to the group scheduler, select the group and schedule at least one person
6. Click the Send Now button
7. Notice the blank "Information" message box that pops up

### Rock Version

14.2 & 15.0

### Client Culture Setting

en-US

**Comment by jasonhendee** [comment]
Thanks for reporting, @JRichmond27! We've fixed this in both the Web Forms and Obsidian versions of this block, to be release in Rock v16.1.
