### ISSUE TITLE
[Alpha v1.16.0.10] Obsidian Notes Block results in error when adding a private note

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5548]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When using the new Obsidian Notes block, anytime you attempt to add a private note (regardless of note type), an error modal pops up that says "Not authorized to edit note." It occurs when you're logged in as someone in the _RSR - Staff Workers_ role and as someone in the _RSR - Rock Administration role.
![image](https://github.com/SparkDevNetwork/Rock/assets/66277785/328bd522-666e-41b9-95f4-9c213d06ceda)

I checked the pre alpha server and this issue _does not_ occur, however pre apha is running v1.16.0.9. I am testing with the built-in note type of _Personal Note_ and verified that the core permissions on that note type have not been altered. I also tested adding a private note using the Legacy Notes block, and I am allowed to as expected.

Here are the _Personal Note_ note type permissions (they are default, but including for clarity):
**View**
<img width="1726" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/c3325025-2a5e-4391-bfae-88ce42a3f068">

**Edit**
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/917213ec-e067-40f8-952e-d7e317ed95bd">

**Administrate**
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/ad80106a-2302-4033-a15c-771e4fd116c1">

### Expected Behavior

I would expect that I can add a private note to a person's profile using the Obsidian Notes block.

### Actual Behavior

I get a "Not authorized to edit note" error when adding a private note to a person's profile using the Obsidian Notes block.

### Steps to Reproduce

- On a Rock system running Alpha v1.16.0.10, navigate to a person's profile
   - _The Notes block visible should already be the new Obsidian block, as it is swapped during the v16 update process_
- Click in the note entry text box to expand the options and type a note
- Type some text, and then make sure the note type is _Personal Note_ and _Private_ is checked
<img width="1726" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/ee81d0d3-0566-4b3a-b296-a9e0eddf8201">

- Click _Save Note_, then notice how you get the error
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/d85720cb-4d05-410e-ae2d-990519a6bd6d">

- In addition, add the Legacy Notes block to the page and repeat the process above
- Notice how the legacy notes block allows you to add a private note

### Rock Version

Rock McKinley 16.0 (1.16.0.10)

### Client Culture Setting

en-US

**Comment by cabal95** [comment]
Thanks @leahjennings. This has been fixed!
