### ISSUE TITLE
Reminder Type with Entity Type Connection Request Causing Exceptions

### ISSUE THREAD

**Issue by zackdutra** [SparkDevNetwork/Rock#5550]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When you create a new Reminder Type and set the Entity Type to Connection Request, and then add a new reminder using the Workflow Action, loading the /reminders page results in an ObjectDisposedException. This has been repeated and confirmed on the demo site.

![Screen Shot 2023-08-22 at 5 31 59 PM](https://github.com/SparkDevNetwork/Rock/assets/96394991/c6792f68-93cc-48c8-8260-e74128d79814)
![Screen Shot 2023-08-22 at 5 39 50 PM](https://github.com/SparkDevNetwork/Rock/assets/96394991/dde773ec-032b-4465-a029-13bade04188f)
![Screen Shot 2023-08-22 at 5 39 44 PM](https://github.com/SparkDevNetwork/Rock/assets/96394991/2f3f306f-ff7a-4986-8ee8-91cb7475a97e)
![Screen Shot 2023-08-22 at 5 39 38 PM](https://github.com/SparkDevNetwork/Rock/assets/96394991/0ed1f0d8-06c2-404c-a563-a7c7051a26ff)

### Expected Behavior

Expected Behavior: The /reminders page loads and includes the newly created connection request reminder.

### Actual Behavior

Actual Behavior: The /reminders page results in an ObjectDisposedException.

### Steps to Reproduce

- Create a new workflow that uses the Create Reminder action with the entity set to a stored Connection Request from the workflow. [Here is a sample workflow export used on the demo site if helpful.](https://www.dropbox.com/scl/fi/okvpp8awwzro5e8fh8ml8/Add-Reminder-for-Follow-Up_202308221719.json?rlkey=g8iiyin2ttkrlyqh5o7eaqq54&dl=0)
![Screen Shot 2023-08-22 at 5 34 25 PM](https://github.com/SparkDevNetwork/Rock/assets/96394991/7568bfed-2018-4684-98b4-6d13a26ad6b5)

-Create a new Reminder Type for Connection Requests with the Entity Type set to Connection Request 
![Screen Shot 2023-08-22 at 5 36 00 PM](https://github.com/SparkDevNetwork/Rock/assets/96394991/c4a5a498-37ce-48a4-9ec7-3a8957e6014f)

-Create a Workflow Trigger that triggers the above workflow.
![Screen Shot 2023-08-22 at 5 36 30 PM](https://github.com/SparkDevNetwork/Rock/assets/96394991/0492d0be-63d0-4581-a711-085695bf96b1)

-Create a new connection request, connector set to yourself (or Alisha Admin if on Demo). Don't set follow up date yet. Save it.

-Edit the connection request and set the follow up date to today.  (The above workflow will only trigger the add reminder step if a follow up date is set). Save it.

-Visit the reminders page. 

### Rock Version

15.1

### Client Culture Setting

en-US

**Comment by nlBayside** [comment]
I would also like to point out that we have had exceptions in the `Process Reminders` job occur since this problem. This appears to be a similar exception to https://github.com/SparkDevNetwork/Rock/issues/5552

<img width="1532" alt="Screen Shot 2023-08-25 at 8 33 15 AM" src="https://github.com/SparkDevNetwork/Rock/assets/85907597/3089807b-c73c-47ca-91ab-7446ce794bf7">

Here's the exception as text if that helps more than the screenshot.
```
at System.ThrowHelper.ThrowKeyNotFoundException()
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at Rock.Jobs.ProcessReminders.SendReminderCommunication(Person recipient, IQueryable`1 reminders, SystemCommunication notificationSystemCommunication, RockContext rockContext, Int32 remindersPerEntityType) in \Rock\Jobs\ProcessReminders.cs:line 451
at Rock.Jobs.ProcessReminders.ProcessCommunicationNotifications(SystemCommunication notificationSystemCommunication, IQueryable`1 activeReminders, RockContext rockContext) in \Rock\Jobs\ProcessReminders.cs:line 332
at Rock.Jobs.ProcessReminders.Execute() in \Rock\Jobs\ProcessReminders.cs:line 182
at Quartz.Core.JobRunShell.Run()
```
