### ISSUE TITLE
Alpha 1.16.0.10 CMS Shortlink Detail Obsidian Update

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#5551]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When we click on our shortlink for our main kids sunday kiosks that gets used at least 5 times a day on average for 5 years, plus an additional 10 times on Sundays every week. It times out. 

### Expected Behavior

Loads the detail page with the link at the top and the detail grid below

### Actual Behavior

Times out with an exception

### Steps to Reproduce

Happy to run some code to show how many rows get returned, but doubt you can replicate this on a test server.

Go to Admin Tools > CMS > Short Links click on a row of a highly used shortlink and see if it loads the detail page.

### Rock Version

16.0

### Client Culture Setting

EN-US

**Comment by chead4** [comment]
@markewampler Thank you Mark.  I am reopening this issue and we will investigate further.

**Comment by markewampler** [comment]
@chead4 If you want some data I can help provide a CSV or something of the rows that we have in there if that would be helpful to see how many rows ours pulls.

We don't use the "history" function on it really as it is useless to how we use it, but we can't use the GUI to edit without pulling up the history based on how the page works.

**Comment by chead4** [comment]
@markewampler Thanks Mark.  That would be great.

**Comment by markewampler** [comment]
I am not sure if this is helpful as I am not sure how that data is conglomerated, but here is the excel export from our page
[Uploading Link.xlsx…]()
