### ISSUE TITLE
Reminder Job fails with "The given key was not present in the dictionary" error when reminder entity has been merged

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5552]
### Please go through all the tasks below

- [x] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

The Process Reminder job fails with a "The given key was not present in the dictionary" error whenever a reminder is being processed for a person who has been merged, and specifically when the merge changes their primary person id. In v16, the error is more specific and says "Reminder 8 is attached to a non-existent entity (Person 73169).", where 8 is the Id of the reminder itself and 73169 is the entity Id associated with that reminder. In our case, the person the reminder was attached to has been merged and the primary selected individual in the merge process changed their person id, resulting in the error for the reminder job. It also causes an exception when you try to open the "View Reminders" page.
<img width="1727" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/bb792f0a-b3cb-4690-8d82-42240587f739">

<img width="1727" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/53f5de9a-017c-4a8b-995b-90b6821cb8c8">

### Expected Behavior

I would expect that reminders attached to people would still process like normal even if the person has been merged and their primary person id has changed.

### Actual Behavior

The job that processes reminders errors out because it cannot find the person id that the reminder is attached to.

### Steps to Reproduce

1. On the demo site, search for `Noah Decker`
2. Note his current person ID from the URL (6)
<img width="1726" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/0c073e1c-c780-4482-8d04-f26142aaf033">

3. Add a Reminder for Noah Decker, due today
<img width="1727" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/e7203dac-255e-436f-8d92-a7f06723e871">

4. Hover over the Person icon in the sidebar and click _New Family_
5. Add a new record, `Noah Decker`, ignoring all the warnings about duplicates (since we are trying to create a duplicate)
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/eb76a9a0-b77f-4226-a483-40ce5ba71138">

6. Go back to the search box, and change the search type dropdown to be _Name_
7. Search for `n decker` (there should be two results)
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/13c06ffa-a7b6-432d-b77e-0721ad6989db">

8. Click on the merge icon to see the merge people page
9. Select the newly created profile as the primary profile, then merge the two
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/24981ef1-8a2f-454f-bb14-564e7082b9f6">

10. Back on the Noah Decker profile page, note that the Id of the person record has changed (id: 55)
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/b1d2da3f-fef9-45c3-8f11-9b945ff73779">

11. Go to Admin Tools > System Settings and click Jobs Administration
12. Find and run the Process Reminders job
13. Once it finishes, note that it finished with an error
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/b6e88053-7426-40a4-8467-39a9c55afab0">

14. If you run the SQL below, you'll see the reminder is still attached to the entity id that existed pre-merge
```
SELECT
    TOP 10 *
FROM
    [Reminder]
```

<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/0bd94fd0-0cf4-4c27-8b79-2fbf42a5bf1c">

### Rock Version

Rock McKinley 15.0 (1.15.0.16)

### Client Culture Setting

en-US

**Comment by shauncummings** [comment]
@leahjennings I see that you have reported this issue as of Rock v15.0 and your screenshots are from the public demo site.

The fix for this involves using the PersonAlias entity instead of the Person entity and that fix is included in v16 (see https://github.com/SparkDevNetwork/Rock/commit/f892f6ac1949eb5df958f89783d9adc3225f248d and https://github.com/SparkDevNetwork/Rock/commit/77a1553090a902980d7fc3281dcd1bac9ee68cf6).
