### ISSUE TITLE
Registration Attribute Public Setting

### ISSUE THREAD

**Issue by juliamullins** [SparkDevNetwork/Rock#5553]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

We run a music academy on Rock through Event Registration. We did not want to delete students that discontinued their lessons. So we added a boolean Registration Attribute of "Is this registration active?" so our admin could "inactivate" students without deleting. It just shows us a simple checkmark on the grid if this is a current student or not. 
However, when we uncheck Public on the attribute settings, the question/attribute still appears on our external registration. I think this is a bug, or I don't understand why you would need that checkbox there to begin with. 
If it's not a bug, a simple "Internal Field" checkbox (like the one on Registrant Forms) would go a long way. 

<img width="937" alt="Screenshot 2023-08-23 at 1 59 07 PM" src="https://github.com/SparkDevNetwork/Rock/assets/143022966/28a7b704-972c-44ad-9482-e579cc4fe311">
<img width="2501" alt="Screenshot 2023-08-23 at 1 59 56 PM" src="https://github.com/SparkDevNetwork/Rock/assets/143022966/55a7bd98-9170-44ea-8e55-aa60611cdda6">
<img width="1403" alt="Screenshot 2023-08-23 at 12 14 03 PM" src="https://github.com/SparkDevNetwork/Rock/assets/143022966/52f7c02e-b977-4db0-95de-1a4753740582">

### Expected Behavior

To be able to switch a registration attribute from Public to Not Public to control the output on the external registration.

### Actual Behavior

Unchecking Public on a registration attribute does seemingly nothing. 

### Steps to Reproduce

- Go to Event Registration
- Select a registration template, click Edit
- Scroll down to Registration Attributes, create a new Attribute
- Uncheck Public
- See that it still outputs to the external registration. 

### Rock Version

14.3

### Client Culture Setting

en-US

**Comment by RufenachtPW** [comment]
In the Registration Entry block the RegistrationAttributesState gets all attributes and checks for view permissions but does not check for IsPublic. Line 2210 Adding a check to only get public attributes should fix the issue.

**Comment by jonedmiston** [comment]
@juliamullins attribute visibility is primarily controlled by security in Rock. The 'Is Public' is more of an override feature for cases where the person may have rights to view an attribute but we want to limit to only showing attributes that have a context of being on public blocks. 

For your use case if you secure the Registration attribute to "Only Staff" you should have the functionality you desire.
