### ISSUE TITLE
Passwordless SMS Code Autofill Issue

### ISSUE THREAD

**Issue by tikool17** [SparkDevNetwork/Rock#5556]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

At least on iOS, the autofill SMS code doesn't autofill correctly. It drops all 6 characters into the 1st box, instead of entering one character per box.

### Expected Behavior

Characters should autofill 1 per box (or there should just be 1 input box that allows all 6 characters for validation)

### Actual Behavior

All six characters from the SMS are autofilled into the first input field, the forms submits with an error because the code is incomplete.

### Steps to Reproduce

-Login Using Obsidian Login Block using Passwordless on an iPhone
-Enter mobile phone number
-Click input boxes to pull up keyboard, click on SMS shortcut above keyboard
-See autofill error

When you click on this shortcut "From Messages S2HM2Z"
![IMG_2565](https://github.com/SparkDevNetwork/Rock/assets/32227063/023e06d6-f757-4ede-84cd-d72b8216c4cd)

All characters are autofilled into the first box
![IMG_2566](https://github.com/SparkDevNetwork/Rock/assets/32227063/1f3a7be0-6319-40e2-8869-2326fc25f219)

### Rock Version

15.1

### Client Culture Setting

en-US

**Comment by joshuahenninger** [comment]
We have confirmed this issue on Safari on iOS. It appears to not be an issue in Chrome but we were not able to get the autofill option in Chrome.
