### ISSUE TITLE
'Add' button/feature to personal or organizational tag view

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#556]
This isn't an issue but would it be possible to have an 'add' person button under the Tag viewer (people>tags)? This way you can add multiple people at once instead of having to go into each of their records.
Thank you guys for all your hard work with Rock.

**Comment by edmistj** [comment]
Probably should add a Add Person to the grid with a block like the Group Member Add with the 'Save Then Add' button.

**Comment by cabal95** [comment]
You mean add an add person _action button_ to the grid, yes?

**Comment by edmistj** [comment]
Yes

**Comment by cabal95** [comment]
@edmistj Since the only thing they would be entering is the Person Picker (the Group Member Add block has various other options that don't apply to Tagged Items), what do you think of using a RockModalDialog instead since it also has the "Save And Add" button?

**Comment by edmistj** [comment]
That's good.
