### ISSUE TITLE
[Alpha 1.16.0.10] Obsidian Family Pre-Registration redirect doesn't include PlannedVisitDate merge field

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5562]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When filling out the new Obsidian Family Pre-Registration block, the Planned Visit Date (when visible) is not passed into the redirect URL as the _When_ page parameter:
![image](https://github.com/SparkDevNetwork/Rock/assets/66277785/6aa08fea-6152-49d7-954d-5ea147aca7bd)

![image](https://github.com/SparkDevNetwork/Rock/assets/66277785/2a615383-01f4-4ff1-bd6c-bd4ead6b781a)

We have not modified the default behavior. For clarity, here's the redirect URL configured on the block:
`~/FamilyPreRegistrationSuccess?FamilyId={{ Family.Id }}&Parents={{ ParentIds }}&Children={{ ChildIds }}&When={{ PlannedVisitDate }}`

### Expected Behavior

I would expect that when the Planned Visit Date is visible, it would be passed into the resulting page as the `PlannedVisitDate` merge field. 

### Actual Behavior

The `PlannedVisitDate` merge field is empty, and therefore not passed into the page you are redirected to.

### Steps to Reproduce

- Go to a Rock instance running at least Alpha 1.16.0.10
- As a logged in user, go to the page where the Obsidian Family Pre-Registration block is located
   - On most instances, it's accessible at /FamilyPreRegistration
   - The v16 upgrade will automatically replace the existing block with the Obsidian version 
- Edit the block settings to confirm that the Planned Visit Date field is Required and the Redirect Url is the following (should be default): `~/FamilyPreRegistrationSuccess?FamilyId={{ Family.Id }}&Parents={{ ParentIds }}&Children={{ ChildIds }}&When={{ PlannedVisitDate }}`
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/629e9dfc-c11b-4b13-b201-d8be866cbeb8">

<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/12914e3e-2b97-4c9b-87f0-8445cd92eb8d">

- Refresh the page and fill in the required fields
![image](https://github.com/SparkDevNetwork/Rock/assets/66277785/e0d58b98-b054-47e9-a81d-d99ff932871c)

- Click Save and notice that the "We're excited to see you on...!" is missing the date. You can also look at the URL and notice that it is missing from the page parameters

### Rock Version

Rock McKinley 16.0 (1.16.0.10), Rock McKinley 17.0 (1.17.0.1)

### Client Culture Setting

en-US

**Comment by joshuahenninger** [comment]
@leahjennings, This issue has been fixed in [commit f1127ffa](https://github.com/SparkDevNetwork/Rock/commit/f1127ffa). It will be included in v1.15.2 and v.1.16.0, and will be in the next 1.17.0.2 Pre-Alpha release.

**Comment by joshuahenninger** [comment]
@leahjennings, This issue has been fixed in [commit f1127ffa](https://github.com/SparkDevNetwork/Rock/commit/f1127ffa). It will be included in v1.15.2 and v.1.16.0, and will be in the next 1.17.0.2 Pre-Alpha release.
