### ISSUE TITLE
Registrant List Not Always Sorting Correctly by Person Attribute

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5566]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When I sort the Registrant grib by a Person Attribute using the RegistrationInstanceRegistrantList block the results will sometimes not show up in the correct order.

Here is an example where I am sorting by the Age Group Person Attribute. You will see that there are two records with the value "Under 35" but these records are not next to one another when sorting. 
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/9d5e3cfb-a45a-4567-bfc6-eff26aad1f12)

This issue does not appear to be affecting sorting by Person Properties.
I have reproduced sort issues with Person Attributes of type defined value and text.

### Expected Behavior

The registrants would be display in the requested sorted order based on the Person Attribute selected for sorting.

### Actual Behavior

The registrants are sometimes not displaying in the correct sort order when you click on a Person Attribute.

### Steps to Reproduce

I have tried to reproduce this issue but have been unsuccessful. This issue is occurring on some Registration Templates but not others.

### Rock Version

15.1

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Thanks @dataCollegechurch Tony.  Can you include a screenshot showing your "Age Group" person attribute.  It would be useful for us to know what field type it is using:

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/f341faa3-123a-4e1e-81e0-155b9ce89ba5)

**Comment by dataCollegechurch** [comment]
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/9b114625-1963-4941-8ccf-07e2b8e65edd)

**Comment by nairdo** [comment]
> I have tried to reproduce this issue but have been unsuccessful. This issue is occurring on some Registration Templates but not others.

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/19f8cc9d-c760-4a09-b066-c24fa18a1925)

We have also tried several different ways (without success) to reproduce this issue or to figure out what _might_ be happening when it fails to sort.  I chatted with Tony and we both agreed that this one could/should be closed until one of us can come up with a reproducible recipe that causes the problem.  If anyone else is able to recreate this problem please re-open this and include your screenshots showing the registration template forms and configuration of the attribute's you are using.  Thanks!
