### ISSUE TITLE
Rock disabling SMS for user profiles when the user messages STOP to a single Twilio number and a 2nd message is attempted

### ISSUE THREAD

**Issue by mcasey-svcc** [SparkDevNetwork/Rock#5581]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

We have noticed a high number of profiles with SMS disabled and have discovered that this is a result of undesired behavior between Rock and Twilio.

### Expected Behavior

If someone texts STOP to ANY Twilio number we have messaged from, Twilio will unsubscribe them from ever getting another SMS from _that_ number.  This is desired; however, from what I can tell, the sender doesn't get any indication this has happened in Rock, which would be nice - but that's a minor issue.

### Actual Behavior

If the sender/individual tries to text that person again (which is very likely as they personally don't know they have unsubscribed), Twilio will error back properly [21610] (https://twilio.com/docs/errors/21610)[ Attempt to send to unsubscribed recipient](https://twilio.com/docs/errors/21610).

When Rock receives that response, it will then disable that person from ALL SMS completely and that should not happen as the unsubscribe should have remained specific to that number which Twilio is already handling.  We see this in History:  SMS Disabled for Mobile (XXX) XXX-XXX. The error received from Twilio is "Attempt to send to unsubscribed recipient" [More info here](https://www.twilio.com/docs/errors/21610)

### Steps to Reproduce

Mentioned above in Actual Behavior.

### Rock Version

15.1

### Client Culture Setting

en-US

**Comment by jonedmiston** [comment]
The stop features were originally written to be at the 'Organization' level. Moving to tracking these at the 'Phone' level makes sense but is more of an enhancement (new models, code and features would be needed). 

We would recommend opening this on the Idea board (https://community.rockrms.com/Ideas) and get the community to prioritize it. Also, if funding is available that could help expedite it also.
