### ISSUE TITLE
[Alpha 1.16.0.11] Can't Disable Show SMS Opt-In On Registration Entry Block

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5582]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

The new `Show SMS Opt-In` option for the _Obsidian Registration Entry_ block is not able to be disabled. By default, this is un-checked on a Registration Template, however the option still appears when registering.

### Expected Behavior

When SMS Opt-In is left un-checked, the SMS option _should not_ appear in the Obsidian Registration Entry block.

### Actual Behavior

When SMS Opt-In is left un-checked, the SMS option _does_ appear in the Obsidian Registration Entry block.

### Steps to Reproduce

Ensure `Show SMS Opt-In` option is un-checked on a Registration Template.
<img width="1723" alt="Screenshot 2023-09-09 at 15 36 56" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/dc12d395-21f9-4796-a1e3-cdb9ca94dfb4">

See that the option is still visible on the Obsidian Registration Entry block.
<img width="1728" alt="Screenshot 2023-09-09 at 15 37 20" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/468c1f7d-f5f3-49b2-ad77-9f908dee11ec">

### Rock Version

v16.0, v17.0

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Thanks @mikedotmundy .  We also ran into this issue recently during our internal testing and were having some trouble tracking it down, but it ended up being odd timing/caching issue which was fixed yesterday via  https://github.com/SparkDevNetwork/Rock/commit/2603bc9e96e651d545c0c1d07a73eaa8d6eecdda which will be in the final v16.0 beta.
