### ISSUE TITLE
[Alpha 1.16.0.11] Error While Replacing Group Registration Block

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5590]
### Please go through all the tasks below

- [ ] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Upon upgrading from 15.1 to 1.16.0.11, Rock throws an exception about being unable to replace the Group Registration block with the new Obsidian version.

### Expected Behavior

Rock would not throw an exception about updating this block

### Actual Behavior

With the initial alpha (1.16.0.10) I noticed a bunch of exceptions immediately after upgrading, that looked similar to this:

![image](https://github.com/SparkDevNetwork/Rock/assets/3903408/73f672e0-3731-4ae1-9738-96cf8a2b1e84)

I assumed these were just a side effect of the various Obsidian block replacements and moved on, because they did NOT return after a Rock restart post-upgrade.

However, with 1.16.0.11 I now see this additional exception

![image](https://github.com/SparkDevNetwork/Rock/assets/3903408/fb37a07c-94b6-4b88-96e1-9b7ce8e0125d)

and this one DOES return after I clear the Exception Log and restart Rock (the others do not.) Furthermore, the Rock Upgrade page now says this on my system, even after multiple restarts:

![image](https://github.com/SparkDevNetwork/Rock/assets/3903408/4e29c38d-7f56-4941-99da-610e02461967)

so it seems to be "stuck" in a bad state regarding this particular block replacement. This DID NOT happen on the exact same DB with 1.16.0.10. All I did was roll back to the same 15.1 instance I did my other testing with, and applied 1.16.0.11 this time.

I also went through the entire process a second time (rolling back again) just to be sure it wasn't a fluke.

### Steps to Reproduce

See above

### Rock Version

1.16.0.11

### Client Culture Setting

en-us

**Comment by nairdo** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/741a4969ba80a73c11c2bdc473c862fe79629522.
