### ISSUE TITLE
[Alpha 1.16.0.11] Legacy Lava Global Attribute Still Exists

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5591]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Per the release notes for v16.0 (and in the Heads Up! notification before updating), Legacy Lava is no longer supported. However, If you navigate to Admin Tools > General Settings > Global Attributes, `Lava Support Level` is still listed as an attribute.

<img width="1725" alt="Screenshot 2023-09-11 at 19 50 57" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/2d88b6e3-a99a-43f2-89c2-0d9c1ccae97e">

### Expected Behavior

If the attribute cannot be removed for some reason, then it would be helpful that the description is updated. Currently, it still states _"the old Lava syntax is supported if set to LegacyWithWarning"_, which is not true.

### Actual Behavior

The Global Attribute for `Lava Support Level` still exists, even though Legacy Lava is no longer supported.

### Steps to Reproduce

See above.

### Rock Version

v16.0, v17.0

### Client Culture Setting

en-US

**Comment by MrUpsideDown** [comment]
The Lava Support Level Global Attribute will be removed in the final release of v16.0.
