### ISSUE TITLE
[Alpha 1.16.0.11] Lava Filters ToIdHash, FromIdHash and AppendWatches Appearance Issue

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5592]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

This is a minor UI issue, but the new Lava Filters `ToIdHash`, `FromIdHash`, and `AppendWatches` do not highlight in light blue like all other Lava filters do. 

<img width="1177" alt="Screenshot 2023-09-11 at 20 08 54" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/d0eede91-6c08-4fee-955a-84c783868848">

### Expected Behavior

Lava Filters should highlight in light blue.

### Actual Behavior

Lava Filters do not highlight in light blue.

### Steps to Reproduce

See above.

### Rock Version

v16.0, v17.0

### Client Culture Setting

en-US

**Comment by mikedotmundy** [comment]
This is not fixed in our v16.0 instance or in the v17.0 `rockrmslatest` site.

**Comment by chead4** [comment]
@mikedotmundy Thanks for letting us know Mike.  I have reopened the issue and we will look into it.

**Comment by jonedmiston** [comment]
@mikedotmundy I believe you may need to clear your browser cache. The new filters appear to be working for me. The ACE editor does not fingerprint it's libraries so when changes are made the old options are often cached locally.

![image](https://github.com/SparkDevNetwork/Rock/assets/548178/000159f0-98c6-48d7-9190-bf1951a60ff3)

**Comment by mikedotmundy** [comment]
Yep that fixed it! Thanks @jonedmiston
