### ISSUE TITLE
[Alpha 1.16.0.11] Workflow Form SMS Opt-In Field Functionality

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5594]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

For the SMS Opt-In setting on a Workflow Form, I could not find the difference of setting it to `Optional` vs `Required`.

My initial thought was that setting it to Required would be used if we wanted to require a person to opt-in in order to submit the form. However, this is not how it is functioning. With this field set to Required, you are able to submit the form without selecting this option (leave it un-checked).

<img width="1723" alt="Screenshot 2023-09-11 at 22 05 25" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/f4385316-eba8-40c9-b53d-a819d202d77c">

### Expected Behavior

I am not 100% sure, but I would think if the intent was to make it Required, then you would have to check the box in order to proceed forward. If not, I would just assume it would be a check-box on the admin side, similar to how it was setup on the Registration Entry block. (see image below)

<img width="1725" alt="Screenshot 2023-09-11 at 22 10 52" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/9ccf1692-9c44-4a7c-8cec-a0f51dfe5e6b">

### Actual Behavior

Selecting `Optional` or `Required` does the same thing (as far as I could tell).

### Steps to Reproduce

- Create a Workflow Type
- Add a Form Action
- Set the SMS Opt-In option to Required 
- Test the form, leaving the SMS option unchecked, and see that you can submit it. 

### Rock Version

v16.0, v17.0

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Similar to the other issue (5582), we also encountered this mistake on the Form action (and the Form Builder) during our testing when it hit alpha.  The options should have been "Show" and "Hide" and that has been fixed in time for the beta via https://github.com/SparkDevNetwork/Rock/commit/65cbbc5222f40c51696f62e5c1bd63bc974f6b8a and https://github.com/SparkDevNetwork/Rock/commit/f13e94394b9fc28db0ef7ee5dfecd9a1747fc6de.
