### ISSUE TITLE
Inactive Phone Numbers still shown and work on Communication pages

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#5597]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Inactive System Phone Numbers are still available for use in communications. (Seems like a similar issue was reported but I could not find it.)

### Expected Behavior

Inactive System Phone Numbers would not show in the selections on the Simple and Wizard Communication editors once they are marked inactive.

### Actual Behavior

All numbers appear in the list of selectable values and continue to work for communications bidirectionally even if marked inactive.

### Steps to Reproduce

- System Phone Number page and inactivate a phone number (or add an inactive number)
- Navigate to either the Communication Wizard or the Simple Communication page.
- Select SMS option
- Open the dripdown of phone numbers and the inactive number will be shown in the list.

### Rock Version

14.3, 15.1

### Client Culture Setting

en-US

**Comment by darringraham** [comment]
I can verify this behavior in v15.1. Both the New Communication and Simple Communication pages show SMS numbers regardless of whether they are Active or Inactive in System Phone Numbers.
