### ISSUE TITLE
Signature Document List block honors File Type security rather than Signature Document's security

### ISSUE THREAD

**Issue by SixGricksSolutions** [SparkDevNetwork/Rock#5599]
### Description

We have a lot of different Digital signature Documents and set security for each document template assuming that would be what's honored on the Signature Document List on someone' profile. Unfortunately the Signature Documents List block seems to only review the File Type rather then the Signature Documents security settings. 

Our goal was to only allow staff to review some documents, but right now if someone can view any signed document they can view them all. 

Looking for a solutions I considered creating a new document type with different security roles to hold HR document, but there is not a native way to move already signed documents from one document type to another meaning once a documents signed it stuck with that security setting basically forever. I also assume moving forward they would not show on someone' profile because the bock is set to just show digital signature document filetype. 

### Actual Behavior

Signed documents can be viewed by anyone that can see the Signature Document Filetype. 

### Expected Behavior

Digitial signature documents would honor the security settings in the template. 

### Steps to Reproduce

- Go to '/admin/general/signature-documents' and set a document type's view secuirity to grant Rock Admin view access and deny all other users. 
- Sign in as a staff member'
- Go to someone's profile who signed the document you change.
- See error: You can still view this document. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.15.0.16 & Demo Site 1.17.0.2

### Client Culture Setting

en-US

**Comment by dataCollegechurch** [comment]
My understanding that the security setup for signature documents is working as designed. That is security for signature documents is based of on its associated binary file types (not document templates or document types). It is important to note that a binary file is created when an electronic signature document is signed, not a person document type.

Our current solution for more granular security is to create different additional binary file types for electronic signature documents based on who needs to view them. Here is one such example:
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/1ce9502b-a86c-4e28-b521-2a0e24138784)

When you create the signature document template you can change the associated file type as desired
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/274a0ceb-55fc-4e25-85f0-0a32fd225529)

**Comment by SixGricksSolutions** [comment]
@dataCollegechurch Thanks for the reply. I tried this and can confirm that any new signature document will be saved as the new binary filetype and honor those security roles. 

Unfortunately that still means that signature documents forever have the security settings given as the time of signing and user's can't see the document, but can see the document's description in the list of signed docs.

**Comment by dataCollegechurch** [comment]
@SixGricksSolutions - the binary file type associated with a signed document could be changed via SQL. Please let me know if you would like assistance with this. I would recommend submitting an idea here (https://community.rockrms.com/Ideas) if you want to see ability to change a signed documents associated file type via the UI implemented as a core/native feature.

I have reported a **_Missing Info_** Issue with this section of the Hero Guide (https://community.rockrms.com/Rock/BookContent/9#electronicsignatures) in hopes that the documentation around view access to signed documents is included.

**Comment by nairdo** [comment]
@SixGricksSolutions DJ & @dataCollegechurch Tony, We actually believe this is likely a bug with the current code, so please standby while we complete the write-up and get this into the queue to fix.

**Comment by dataCollegechurch** [comment]
@nairdo - It is safe to assume the release notes/updated documentation will explain how signature document security will work in 16.1 and beyond?

**Comment by nairdo** [comment]
@dataCollegechurch Yes, the main part of the release note comes from the commit message "Fixed issue with Signature Document blocks not honoring the Template's Security."  Meaning, the signature document gets its security from the Template:

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/c8ada65b-684f-444e-9503-fc6247cac4d3)

...and the SignatureDocumentDetail block will only show details if the viewer/individual (i.e., staff) has view rights for its template.

Additionally, the SignatureDocumentList block will also respect that security and only show the viewer/individual  (i.e., staff) any documents if they have view rights for the template:

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/85628b7a-df59-486e-8601-9af59395549a)

One thing to keep in mind with all of this is: Rock is _not_ preserving a copy of the signed document for the person who signed it.  They should have received their copy through another mechanism (such as an email that was sent once they registered, etc.).  The documents Rock preserves are for the church staff.

**Comment by dataCollegechurch** [comment]
If someone has access to the underlying binary file type but not the template, will they be able to view a electronic signature document in the future?

**Comment by nairdo** [comment]
Hi Tony @dataCollegechurch  From the context of a Electronic Signature Document -- no, the Signature Document Template controls the security.  And there will be a "Heads-Up" note on the v16.1 update package stating something like this to explain that:
> The Signature Document Type Detail, Signature Document Detail and the Signature Document List blocks no longer use block-level security permissions. Security permissions will need to be assigned on the Signature Document Template.

**More Details (how it works)**
This is basically the same way general "Document" security works since v14.1 ([4ea0377](https://github.com/sparkdevnetwork/rock/commit/4ea0377ad335c49a9448b6314f61bfcc303f64ba)).

On the `[BinaryFile]` there are two properties: `ParentEntityTypeId` and `ParentEntityId`.  For 'Signature Document' type binary files, `ParentEntityTypeId` is the Rock.Model.SignatureDocumentTemplate entity type and the `ParentEntityId` is the specific Signature Document Template Id.   (This data was missing and is fixed during the update to v16.1. So after the update, those database columns will also have data for Signature Documents.)

I hope that helps explain it more thoroughly.
