### ISSUE TITLE
Group Scheduler not showing places to drop group members Alpha 1.16.0.11

### ISSUE THREAD

**Issue by tbunney** [SparkDevNetwork/Rock#5600]
### Description

When I pull up a group in Group Scheduler, the placement fields are not showing. You can only see the red, yellow, and blue lines and the beginning of the locations.
![groupschedulingissue](https://github.com/SparkDevNetwork/Rock/assets/37702418/a485a78d-b497-412f-bc1f-9184b312d9fa)

### Actual Behavior

I went to Group Scheduler, chose a group to schedule, and the locations are not showing the spots to fill. See screenshot above.

### Expected Behavior

The group scheduler should show all the spaces below the locations to add people. 
![groupscheduler-correct](https://github.com/SparkDevNetwork/Rock/assets/37702418/a44027d7-afe4-444b-9eba-8558f140079f)

### Steps to Reproduce

- Go to 'Group Scheduler'
- Choose a group to schedule
- See error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Alpha 1.16.0.11

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@tbunney  Can you also check the **_new_** Group Scheduler's styling on your test system to see if that also has odd styling problems?

The new, Obsidian block looks like this:

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/89746c85-dca4-49b6-94a8-91caa616d2b7)

If you are unsure how to add the new Obsidian version of the block to a page...
![image](https://github.com/SparkDevNetwork/Rock/assets/383807/ab546e25-5868-4a08-b3ff-55dfd0356d77)

**Comment by tbunney** [comment]
@nairdo This is what it looks like with the New Group Scheduler. In the email I had, it didn't mark the group scheduler as a new Obsidian block, so I missed it. Sorry about that!
![newgroupscheduler](https://github.com/SparkDevNetwork/Rock/assets/37702418/d76e9270-0a10-4b3b-912f-9927176ffe6d)

**Comment by nairdo** [comment]
> Sorry about that!
@tbunney  No need to apologize!  I was just trying to clarify.  But, the old Group Scheduler block should not be broken like you are seeing in your original screenshot.  I'm not able to reproduce that and it does look to me like there is a CSS/Style issue in there that is the likely cause.    I'll ask the Alpha tester team if anyone else is able to reproduce that problem.
