### ISSUE TITLE
[v16.0] Financial Batch Detail Page - Batch Closed Note Issue

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5601]
### Description

On the Financial Batch Detail Page (`https://rockrmslatest.com/finance/batches/{{ BatchId }}`), when a Batch is closed, there is a note that appears at the top of the Transaction List Block that says, _"Note This batch has been closed and transactions cannot be edited."_

However, if you Edit the Batch, then Open the Batch, then save the Batch, the Note does not disappear until after you have manually refreshed the page. This is not the same behavior as v15.1, with the Webform Batch Detail Block.

<img width="1705" alt="Screenshot 2023-09-14 at 19 11 06" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/0847fb48-b7ba-4db6-894e-9084172b87de">

<img width="1706" alt="Screenshot 2023-09-14 at 19 11 16" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/096916e0-9d26-41ba-ade0-d679ce0c3154">

### Actual Behavior

Note does not disappear until you have manually refreshed the page.

### Expected Behavior

Note should disappear without having to manually refresh the page.

### Steps to Reproduce

See above

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.0, v17.0

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Thanks @mikedotmundy  That feature** doesn't quite exist in Rock's Obsidian world yet, but we've got that on our plate to tackle in the near future.


** <small>_It was related to our `ISecondaryBlock` concept, which would allow one block to effect another block on the same page.  It worked between two WebForms blocks.  But Obsidian can't currently cause that behavior._</small>
