### ISSUE TITLE
Obsidian Required Person Attribute Fields of Type Defined Value Prepopulating

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5604]
### Description

If you setup a Registrant Form Field with the following settings

1. Source: Person Attribute 
2. Type: Defined value 
3. required: Yes
4. Use Current Value: Yes

The user isn't being prompted to select a value initially during registration. Instead, the value is prepopulated.

### Actual Behavior

These values should start off blank to ensure users do not accidentally submit information they didn't specifically supply.

### Expected Behavior

Values are prepopulating because the field is marked as required and there is no blank value in the dropdown.

### Steps to Reproduce

1. Open the Summer Camp Registration on the demo site
2. Add Ability Level as Registrant Form Field and mark it as required
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/c1ab2159-96d4-4158-8e1e-a996155c3bdb)
4. Navigate to a page that has the Obsidian Registration Block for the registration in question
5. See Issue. Alisha Admin does not have an ability level attribute stored on her profile but this field is pre-populating to infant.
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/4d5e0343-0286-43d5-8f06-8cd27d32f095)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.1

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@dataCollegechurch Are referring to this "Use Current Value" checkbox?  The purpose of that option is to 'prepopulate their current value' into the field.

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/3d820267-49ab-4bd9-94c6-be7957d9369c)

**Comment by dataCollegechurch** [comment]
The issue I described above will occur when the Use Current Value checkbox is checked and when it is not checked. The scenario/issue I am attempting to describe is one where the registrant does not have an existing attribute value for the attribute in question.

**Comment by cabal95** [comment]
@dataCollegechurch This ended up being an issue with the Defined Value field type in Obsidian rather than the Event Registration block. The field was configured to _not_ show the blank option, which would then cause it to auto-select the first option. This has been adjusted so it lines up with how the web forms control worked.

It will still work as a required field, so if they leave it on the blank option (or switch it to the blank option) it will still prevent them from moving to the next screen.

**Comment by dataCollegechurch** [comment]
@cabal95 - Thank you for the clarification, perhaps we should change the issue title to something like "Defined Value field type in Obsidian not showing blank option", do you concur?
