### ISSUE TITLE
[Alpha 1.16.0.11] Adding or Editing Metrics Times Out

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5606]
### Description

Attempting to add or edit a metric causes a request timed out error. Error message is given but no exception is recorded.

![Screenshot 2023-09-18 at 07 39 26](https://github.com/SparkDevNetwork/Rock/assets/23226974/8224a3e7-86c4-4030-af07-09930a10bb77)

### Actual Behavior

Cannot add or edit metrics.

### Expected Behavior

Should be able to add or edit metrics.

### Steps to Reproduce

- Go to `https://rockrmslatest.com/reporting/metrics`
- Attempt to add a new metric or edit an existing metric.
- Wait for a long time.
- See error message on page.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.0, v17.0

### Client Culture Setting

en-US

**Comment by jr-peck** [comment]
@mikedotmundy 
Any chance you are running an ad blocker while trying this? They do not like adding/editing metrics for some reason.

**Comment by mikedotmundy** [comment]
Thanks @jr-peck that is the problem. 
1. Do you know why that is a problem for metrics, but not for other blocks (that I have found)? 
2. Did something change for v16.0? I _do not_ have this issue in v15.1.

**Comment by jonedmiston** [comment]
Nice call @jr-peck . @mikedotmundy what ad blocker are you using? Sometimes it's the naming of an input or div that can trigger them.

**Comment by mikedotmundy** [comment]
It's Brave Browser - I believe it's the default "Brave Shields".

![Screenshot 2023-09-18 at 15 16 11](https://github.com/SparkDevNetwork/Rock/assets/23226974/ee3a4db8-83e6-4c5e-b701-0a6efa338fdd)

**Comment by jonedmiston** [comment]
@mikedotmundy I installed Brave and can't reproduce on the pre-alpha server. It's possible you have to have a specific metric configuration. Can you provide more details? Does creating a minimal manual entry metric generate the error?

**Comment by mikedotmundy** [comment]
@jonedmiston See attached video below. The loading icon stays for ~5min before the timeout message appears (in the original issue). 

If I turn off the Brave Shield, then it loads normally.

Also worth noting, this is the only browser I am having an issue with. Just happens to be the one I use the most often. Just don't know why it was fine in v15.1, but not in v16.0.

https://github.com/SparkDevNetwork/Rock/assets/23226974/013b58c6-c436-4a91-824d-e446a4208197

**Comment by jonedmiston** [comment]
That's odd. I don't have an issue with the Brave I just installed. 

![image](https://github.com/SparkDevNetwork/Rock/assets/548178/d8ef1d80-7ffe-45f9-b036-b41c3d3cc6a8)

![image](https://github.com/SparkDevNetwork/Rock/assets/548178/2a6442ea-3474-4cc3-9b7d-7a9a2de606c6)

I'm going to close now that we know that this is not an issue with Rock. If you find any other details though please let us know.

**Comment by mikedotmundy** [comment]
Ah... I was not on the latest version. I am now and that fixed it. Sorry for wasting your time with this one @jonedmiston
