### ISSUE TITLE
Passwordless authentication does not prompt to confirm account

### ISSUE THREAD

**Issue by davidbelk** [SparkDevNetwork/Rock#5614]
### Description

I could not reproduce on a the demo site because of SMS but another church confirmed they are experiencing the same issue. 

When using the passwordless authentication method and an account is not confirmed, it simply goes back to the main password screen after the code is entered and does not prompt the user to confirm the account. 

If we confirm the account manually, then the user can log in with no issue. 

### Actual Behavior

The user should be prompted to confirm the account after entering the code. 

### Expected Behavior

The user is sent in a sign in "loop". 

### Steps to Reproduce

This is our start sign in screen. 
<img width="1095" alt="Screenshot 2023-09-27 at 10 08 27 AM" src="https://github.com/SparkDevNetwork/Rock/assets/43145156/a4211c4a-e158-4732-bb4d-32291d991a67">

We chose sign in with email or phone and enter the phone number. 
<img width="1164" alt="Screenshot 2023-09-27 at 10 07 45 AM" src="https://github.com/SparkDevNetwork/Rock/assets/43145156/f73fabc2-290b-4b6a-a148-79a12f82e3fb">

We get the code and enter it on an account that is not confirmed, enter it and select complete sign in. 
<img width="1043" alt="Screenshot 2023-09-27 at 10 08 09 AM" src="https://github.com/SparkDevNetwork/Rock/assets/43145156/17521bff-e126-4961-957a-3f6f3d308ddd">

We get sent back to this page. 
<img width="1095" alt="Screenshot 2023-09-27 at 10 08 27 AM" src="https://github.com/SparkDevNetwork/Rock/assets/43145156/24965159-341e-4aa2-894b-705449c89278">

These are our block settings. I tried it with and without a confirmation page selected. 
<img width="390" alt="Screenshot 2023-09-27 at 10 11 58 AM" src="https://github.com/SparkDevNetwork/Rock/assets/43145156/251676c9-78b1-44c0-9b06-28647decd1d2">

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.1

### Client Culture Setting

en-US

**Comment by stevekleinliquid** [comment]
@davidbelk thank you for raising. We are seeing the same issue with Passwordless login. So far we haven't been able to isolate what is causing this (it happens relatively infrequently). We did create a workaround which I've posted about in the Rocket Chate #security channel.

**Comment by joshuahenninger** [comment]
@davidbelk @stevekleinliquid This issue has been fixed in v16.1. There were issues with unconfirmed accounts as well as locked out accounts, both of which have been addressed.

With regard to the cause of passwordless accounts being marked as not confirmed, I believe it occurs when people records are merged. That functionality is not changed with this commit.

The solution to this issue is to automatically mark a passwordless account as confirmed if an individual successfully performs a passwordless login; they have to successfully confirm the email/phone to authenticate.
