### ISSUE TITLE
Unable to see/select campus on linkages from Event Occurrence

### ISSUE THREAD

**Issue by stanalyst** [SparkDevNetwork/Rock#5617]
### Description

When adding/editing linkages for an Event Occurrence - the block/form does not include the Campus for viewing/selecting - even though this is part of the linkage. Currently the only way to view/edit the campus is to edit the linkage from a Registration Instance.
![Campus on Linkage](https://github.com/SparkDevNetwork/Rock/assets/112125627/c44c4109-4d2f-430f-90a3-cb677ba25c1e)

### Actual Behavior

The campus is not exposed when editing/viewing the linkage from an Event Occurrence.
![EventOccurrence](https://github.com/SparkDevNetwork/Rock/assets/112125627/50e2de90-c2e9-49be-a136-9028036fd847)
![EventOccur-EditLinkage](https://github.com/SparkDevNetwork/Rock/assets/112125627/5b519d1c-dbfb-46a9-98af-a5b9e5f086df)

### Expected Behavior

When editing/viewing the linkage from an Event Occurrence - should be able to see/select a campus.

### Steps to Reproduce

In a Rock instance that has multiple campuses.
Add a linkage to an Event Occurrence for a Registration Instance
Note that you cannot select campus.
Now go edit that linkage from the Registration Occurrence
Note that you can select a campus.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.14.3.1 (also confirmed in 1.15.2.1)

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@stanalyst Hi Stan - Thanks for this submission.  After careful review, it was determined that Campus was not intended to be included as a selectable option on the Registration Instance.  If this is a feature that you are interested in, we'd recommend submitting an idea on the Rock Community Ideas board via http://community.rockrms.com/ideas.
