### ISSUE TITLE
Sign-Ups Permissions  to Edit Have To Be Set In Sign-Up Overview/Details Block

### ISSUE THREAD

**Issue by frogydiak** [SparkDevNetwork/Rock#5622]
### Description

I don't know if this is intentional or it is a bug but it doesn't make sense since Sign-Up is just a group type. By default, the Staff Workers security group is not able to edit an entry in Sign-Ups. I have to add Staff Workers to Sign-Up Details or Overview Block permissions for it to work:

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/15bc4157-6297-4eb1-901e-cb11947f1266)

Adding permission in the Sign-Up Group Type Edit permission is not enough.

### Actual Behavior

See description or steps to reproduce.

### Expected Behavior

Shouldn't be the permission to edit is set in the group type?

### Steps to Reproduce

- Go to 'Group Types'
- Loop for 'Sign-Up Group'
- Click on the 'Lock Icon'

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/fdf4a229-b9a0-467b-b823-e11452c094cf)

- Add Staff Worker Security Group to 'Edit' and 'Schedule'

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/4cc4b25c-c057-4219-9a52-200b016471e7)

- Login as one of the member of Staff Worker group and go to Sign-Up and try to edit an entry. You'll notice that you don't see the pencil icon to edit.

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/68c16421-59ac-4da2-b690-32bb01359a30)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.1

### Client Culture Setting

en-US

**Comment by jasonhendee** [comment]
**A couple additional things we noted while addressing this issue:**

1. You'll want to grant **Edit** permission to any Group Attributes your Staff Workers should be allowed to set or change when adding/editing Sign-Up projects. For example, the Sign-Ups feature ships with a "Project Type" Group Attribute that non-administrators will not be able to edit unless permission is granted.
![GitHub Issue 5622 - Group Attribute Permissions](https://github.com/SparkDevNetwork/Rock/assets/59710095/65bd85f5-5135-40ca-9999-405f5492bae7)

2. If your Staff Workers should be allowed to add "Top-Level" Sign-Up projects, you'll need to grant them **Edit** permission for the **Group Tree View** blocks on both the main Sign-Ups page + the Sign-Up Detail page.
![GitHub Issue 5622 - Group Tree View Block Permissions](https://github.com/SparkDevNetwork/Rock/assets/59710095/3e8d1098-d901-407a-82f2-0eb38f40f2bd)

**Comment by jasonhendee** [comment]
@frogydiak, after updating to v15.2 or v16.1 of Rock, simply granting "Edit" permission to your **Staff Worker** Security Role at the `Project (Group)` or `Group Type` level should allow individuals belonging to that role to edit these blocks as you've requested above.

I've also put in a request to update our Sign-Ups docs to clarify what permissions are needed for this feature + some fine-tuning that can be accomplished by playing with the various permissions (Mange Members, Edit, Administrate & Schedule). Thank you!
