### ISSUE TITLE
Cannot merge into merge document from Giving Analytics

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#5623]
### Description

When trying to export a grid to a merge document in giving analytics an error is generated. 

![2023-10-04_09-11-21](https://github.com/SparkDevNetwork/Rock/assets/657005/811d3d4e-6ffb-4503-b4bf-43a456f307f7)

### Actual Behavior

An error is generated. See screenshot above.

### Expected Behavior

Expected Behavior

Merge document wizard would pop up like below:
<img width="1336" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/657005/b93a84f9-0419-4a98-b1fe-dffe1a075421">

### Steps to Reproduce

1. Go to Giving Anayltics
2. Enter dates to get gifts to appear in the data grid
3. Click the button to begin merging records into a merge template.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16

### Client Culture Setting

en-US

**Comment by adamhann** [comment]
Can someone confirm if this fix would also fix the same issue in Attendance Analytics?
