### ISSUE TITLE
Notes Entity Attributes Assumes Text For All Attribute Aypes

### ISSUE THREAD

**Issue by SixGricksSolutions** [SparkDevNetwork/Rock#5626]
### Description

We use Entity Attributes tied to notes to track several different types of details about people. Typically we have the attribute type set to HTML with a template for staff to use to get started. This has worked great for the last year. 

As we updated to V16 the notes are no longer showing formatted HTML: 
![image](https://github.com/SparkDevNetwork/Rock/assets/102253846/ab8341e5-0665-4af4-8513-d2574fb6cc78)

On top of that the HTML Entry is showing as a standard text entry:
<img width="1456" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/102253846/f4895bc5-58f6-413e-b7eb-dbae09413cbb">

For example "Financial Stability" should show like this: 
<img width="592" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/102253846/6bbc5741-a155-4b7e-91f6-ff8d9afadc2a">

### Actual Behavior

HTML is shown in Raw value. All attribute types are assumed to be text. 

### Expected Behavior
HTML render and Attribute entry honor the attribute type

### Steps to Reproduce

- Go to 'Admin Tools>System Setting> Entity Attributes'
- Change Entity Type to Notes
- Add an entity Attribute with the qualifier Feild =NoteTypeID and the Qualifier Value 4 (for personal notes - or choose your own). Set your field type to anything other then Text and save.  
- Navigate to anyone's profile and leave a note of the type you chose. See error in entry. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.0 (1.16.0.12)

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Hi @SixGricksSolutions DJ, This was an intentional change in v16. Notes were intended to store simple text or 'structured content' for the eventual usage of that content across more than just web.  With the upcoming "mentions" feature, these notes will be sent to SMS, Mobile, etc. which are not HTML-friendly environments, and that is why you're noticing this change.

**Comment by SixGricksSolutions** [comment]
Thanks for the reply. Now to figure out how to transition 1465 notes to another storage method. 🤣
