### ISSUE TITLE
When Member Added To Group Workflow Missing Group Member Entity

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5627]
### Description

A group member workflow configured to run When "Member Added To Group" is not passing the group member as the entity to the triggered workflow.

### Actual Behavior

Entity Object is Null

### Expected Behavior

Entity Object is set to the Group Member just added

### Steps to Reproduce

1. Create a simple capture entity workflow
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/1e3eb776-bf50-4488-bbb5-a108d5949f33)
2. Configure a group type to run this workflow when a group member is added
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/920491b8-a240-4dbc-9be2-0fcebcfb930a)
3. Add a group member to a group of this group type
4. Review workflow and details to see issu
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/21232e30-120d-4728-9138-7c4bbd94f099)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.1

### Client Culture Setting

en-us

**Comment by chead4** [comment]
@dataCollegechurch Hi Tony When creating your workflow, the Action Type should be Attribute Set from Entity and the value will display in the workflow details.  We are considering update the lava run action in the future.
![image](https://github.com/SparkDevNetwork/Rock/assets/134172019/4b3e0f71-4d7a-4293-8396-97661cbebe8c)
![image](https://github.com/SparkDevNetwork/Rock/assets/134172019/b4a45b69-8545-4120-89ba-b2edb2b773d1)

**Comment by dataCollegechurch** [comment]
@chead4 - Mea culpa, thanks for the feedback
