### ISSUE TITLE
Sign-Ups feature displays inactive schedules when using named schedule filters

### ISSUE THREAD

**Issue by KarenRossi84** [SparkDevNetwork/Rock#5631]
### Description

When utilizing the named schedule filter on the Sign-Up Finder block all schedules are displaying under the root selected, including INACTIVE schedules. I should be only given the option of selecting ACTIVE schedules. 

![active holiday schedules](https://github.com/SparkDevNetwork/Rock/assets/104036471/3604a075-0a27-49ad-8973-a36b97b499f4)

![schedule block settings](https://github.com/SparkDevNetwork/Rock/assets/104036471/373cb35b-d686-47ae-8217-a7c7e76dedd7)

### Actual Behavior

All schedules display including inactive ones. 

![schedules on sign-up finder](https://github.com/SparkDevNetwork/Rock/assets/104036471/d2326b4d-f534-4f15-bd36-62d5003410bd)

### Expected Behavior

I would expect that only the active schedules would display as filter options.

### Steps to Reproduce

- Create a page with the sign-up finder block
- Edit the block settings to enable Display Name Schedule Filter
- Select a Root Schedule Category that has both active and inactive schedules
- See all schedules display on the filter including the inactive ones

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.15.1.1 and [BETA]1.16.0.12

### Client Culture Setting

en-us

**Comment by chead4** [comment]
@KarenRossi84 Hi Karen - Thank you for the submission.  We are closing this issue as sign up opportunities with an inactive schedule do not display in the returned results when searching.  Please feel free to submit an idea for inactive schedules to not appear in the filter by submitting an idea on the Rock Community Ideas board via http://community.rockrms.com/ideas.

**Comment by JimMichael** [comment]
Can we get a little more explanation of the logic of not considering this a bug? Under what circumstances is it considered "right" to allow someone to filter on something that _cannot possibly return results_ (as is the case with showing Inactive Schedules, but results from said Schedules are never returned)

I totally get the desire to use the "this is working as designed" argument as often as possible, but sometimes the design is just... wrong.

**Comment by chead4** [comment]
@JimMichael  Hi Jim Thank you for the feedback.  After taking another look at the issue we agree that inactive schedules should not display in the filtered list on Sign Up Finder page.  We will move forward and fix this issue.
