### ISSUE TITLE
Obsidian Registration Fee options hidden if a "Max Available" is not set and "Hide When None Remaining" is checked

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5635]
### Description

We often have Registration Templates setup to where there is a Fee (set to _Multiple_) that has options with max available quantities and some that don't have a maximum. The ones that don't have a maximum, we just leave the _Max Available_ blank for that option _(see screenshot for example)_.

With the new Obsidian Registration block, if the "_Hide When None Remaining_" is checked, then _any_ option that doesn't have a max available set is _assumed_ to be "none left" and is hidden.
![image](https://github.com/SparkDevNetwork/Rock/assets/66277785/8e07f182-b1c5-4171-922d-d46a4235c9b1)

If _Hide When None Remaining_ is not checked, then the fees without a Max Available set show up as expected and are able to be selected.

I saw bug #5408, but I believe this is different (albeit possibly related).

_Ignore the purple in the screenshots, I promise I was on the demo site - someone else just must've been in there testing, too. 😄_

### Actual Behavior

When there is a fee [Options = Multiple] configured on a template, any option that doesn't have a Max Available set will be hidden if _Hide When None Remaining_ is checked. Rock is assuming that an empty Max Available value should be 0 in that specific circumstance.

<img width="1191" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/a03ec475-074f-486a-a5eb-581442752e24">

### Expected Behavior

 I would expect that Rock would assume that an empty Max Available value means there is no maximum.

### Steps to Reproduce

- On the demo site, navigate to Tools > Event Registration
- Expand the _General_ template category and click on _Summer Camp_
- Edit the template, click to expand Fees, and then click the pencil for the _Camp Shirt_ fee
<img width="1720" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/142edc9b-1272-4295-af46-543453c2ce01">

- Check the box for _Hide When None Remaining_
- Add quantities to two of the sizes' _Max Available_, then click Save
<img width="1727" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/d085c91e-badf-484f-be3e-655313a51b54">

- Save the template
- Click the + button to add a new instance of the template _Summer Camp_
- Name it whatever you'd like, then click to Save
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/dbc1c6c4-97ad-49ce-ba9d-89ea8d20eb62">

- Click on the Linkages tab and create a new linkage
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/4ebeab51-2fef-4046-9f25-5168e2945f8a">

- Navigate to Admin Tools > CMS Configuration, then click on Pages
- Expand _External Website_ > _Calendar_, then click on _Registration_
- Remove the legacy "Registration Entry" block and add the new Obsidian Registration Entry block
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/345c5b97-0c7e-4311-9846-c2b412f85452">

- In a new tab, navigate to http://rock.rocksolidchurchdemo.com/registration/testingobsidianfees
   - Be sure to adjust the URL based on the Rock instance you're testing on and the slug you created in an earlier step
- Notice how the two options that don't have a Max Available set are hidden
<img width="1191" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/a03ec475-074f-486a-a5eb-581442752e24">

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 15.1 (1.15.1.1), 16.0 (1.16.0.12)

### Client Culture Setting

en-US

**Comment by cabal95** [comment]
Hey @leahjennings, thanks for the detailed screenshots and reproduction steps. This got fixed today as part of commit https://github.com/SparkDevNetwork/Rock/commit/d952a1398586b4989ed720fe9a0ebaed0f5f06d7. We found a number of issues internally related with how the new Obsidian Registration Entry block handles fees in commit.

I ran your test against the updated code and I believe it has also fixed the issue you saw.

![image](https://github.com/SparkDevNetwork/Rock/assets/1119863/a7713255-91ea-451b-a7d3-e72b3133d639)

![image](https://github.com/SparkDevNetwork/Rock/assets/1119863/167dce80-c5be-429d-9548-6aed915daea0)
