### ISSUE TITLE
Utility Payment Entry block uses Nick Name not First Name and is not editable

### ISSUE THREAD

**Issue by darringraham** [SparkDevNetwork/Rock#5647]
### Description

When we use the Utility Payment Entry block to create a contribution, the Name field is auto-populated with the Nick Name + Last Name, and the field is not editable. Versions of Rock (previous to 14.1) used the **First Name** + Last Name and allowed editing of the Name field. It's our experience that most credit cards have the person's actual first name, not their nick name.

<img width="1296" alt="Screenshot 2023-10-25 at 3 45 43 PM" src="https://github.com/SparkDevNetwork/Rock/assets/38145549/e6239b7b-2adc-4125-b604-4cf5f75f5008">

### Actual Behavior

The Name field on the Utility Payment Entry block is auto-populated with the Nick Name + Last Name, and the field is not editable.

### Expected Behavior

The Name field on the Utility Payment Entry block should be auto-populated with the First Name + Last Name, and the field should be editable.

### Steps to Reproduce

- Go to a person in Rock
- Click on the Contribution tab, then click the "+" under the Schedule Transactions section on the right side of the page to add a transaction.
- Scroll down to Personal Information
- See that the Name field has the person's Nick Name + Last Name, not their First Name + Last Name, and that field is not editable.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 15.1 (1.15.1.1)

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@darringraham Hi Darrin  This is the expected behavior of the nickname displaying within the Personal Information section on the Contribution Information page. If you'd like to open an enhancement request, we would ask that you do that over on the [Ideas board](https://community.rockrms.com/Ideas).
