### ISSUE TITLE
Tag Report block conflicting Id's

### ISSUE THREAD

**Issue by kevinkrugerCCV** [SparkDevNetwork/Rock#5648]
### Description

The tag report block displays a grid to show all of the objects with the related tag.  Used currently most commonly for a person, we would see a list of people that have the selected tag.  When you select a person in the tag list you will either experience nothing as if the row is not selectable or in some cases you will be redirected to a person profile but it will not match the person selected. 

### Actual Behavior

After looking at the "TagReport.ascx.cs" file, I found that during the OnInit() and the BindGrid() the grid "DataKeyNames" are being initialized with the "EntityId".  During the RowSelected function, the code uses the RowKeyId to look up the TaggedItem to first verify there is a TaggedItem record and would later look up the person tied to that tagged item record.   

<img width="1205" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/91297818/7a67f15c-c1cf-4a46-af26-8d3bb1d8bbfa"> 

Due to the initialization function loading the DataKeyNames with the EntityId, during the row selected function, the RowKeyId on selected is passing the personId (EntityId) in to the function rather than the TaggedItemId.  This is causing two different executions when selected.  

1) If the row selected has a personId that coincidentally matches a TaggedItemId, the row selection will open a person profile but it will not be the person selected.  

2) If the row selected has a personId higher than any taggedItemId record in the DB than no action will happen when selected.  

The initial thought to fix was binding the DataKeyNames with the "Id" rather than the "EntityId" so when the selected row happens, the correct Id is passed in. By initializing with the Id of the taggedItem, the row selection functions as intended when selecting a person but by going this route, the communication functionality in the grid returns an error that there are no person's in the list.  
![image](https://github.com/SparkDevNetwork/Rock/assets/91297818/97768be1-608a-4ad5-9520-a9e145f95731)

The communication expects the Id in the grid to be a personId at that point but is a taggedId.  The grid during bind function is setting the personIdField = "EntityId" but does not seem to be effecting the communication function. 

In summary, if the grid is initialized with the dataKeyNames = "EntityId" than the row selection is broken and if the DataKeyNames  =  "Id" than the row selection works but the communication button does not work. 

### Expected Behavior

The expected behavior of this grid would be, if a row is selected, the browser is redirected to the tagged item (person/group). In addition, if a row is checked (or multiple checked) and the communication button in the upper row of the grid is selected that the browser will redirect to a communication block with the selected people. 

### Steps to Reproduce

- Go to a persons profile (https://rock.rocksolidchurchdemo.com/Person/4) and add a custom tag to their profile.
<img width="269" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/91297818/76231d30-5d3d-4aa8-bc59-69708d9dfd31">
- Go to the tag report page (https://rock.rocksolidchurchdemo.com/people/tags)
- Click on your custom tag created under the tag list available. 
- Select the persons row that you added the tag to.
- See that nothing happens. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

14.2

### Client Culture Setting

en-US

**Comment by kevinkrugerCCV** [comment]
@Kwame-Agyei thank you! I put these changes in and tested locally but I get a null exception for the delete function now.
![image](https://github.com/SparkDevNetwork/Rock/assets/91297818/49f81964-696b-4490-a647-cd031a38a789)

  The two issues that were conflicting between row selection and communication seem to work with your fixes tho.

**Comment by Kwame-Agyei** [comment]
@kevinkrugerCCV The changes [in this commit](https://github.com/SparkDevNetwork/Rock/commit/e9bb8d6d95dba22ba7861be3689b3c26a693b0c4) should fix the issue. Sorry for the inconvenience.

**Comment by kevinkrugerCCV** [comment]
> @kevinkrugerCCV The changes [in this commit](https://github.com/SparkDevNetwork/Rock/commit/e9bb8d6d95dba22ba7861be3689b3c26a693b0c4) should fix the issue. Sorry for the inconvenience.

Great! thank you, that worked perfectly.  I appreciate the fix!
