### ISSUE TITLE
Single Account Picker Box Not Closing After Selection is Made

### ISSUE THREAD

**Issue by hollyhoke** [SparkDevNetwork/Rock#5652]
### Description

After an account is searched for, selected and populated from the single-select account picker box, the account picker dropdown box visibly goes away and comes back and then remains open/expanded rather than closing after the selection is made. In order to get the dropdown box to disappear, the user must select *Cancel*. The same behavior can be observed on multiple blocks where only a single account can be selected: 
- *Pledge Detail* 
- *Transaction Detail*
- *Content Item Detail*

This behavior is occurring after upgrading to version 16 from version 14. 

### Actual Behavior

In the *Account* field, after entering a name in the *Quick Find*, clicking the radio button next to the desired result and clicking the *Select* button, the account picker box refreshes (briefly disappears and then comes back) and remains open, as though it wants the user to make another selection. 

**Note**: If the user does NOT search in the *Quick Find* box and just clicks on the account to select it from the visible list, then the account picker box will automatically close.

![PledgeDetailAccountPicker](https://github.com/SparkDevNetwork/Rock/assets/84025065/d5df2ad8-af71-436d-81b1-ff94a22a4ee4)

### Expected Behavior

After the account is selected by clicking the radio button and then clicking the *Select* button, the account picker box should close so the user does not need to click *Cancel* in order for the account picker box to disappear.

### Steps to Reproduce

1. Go to a person's profile > Contributions > Add Pledge
2. Click in the Account field and enter an account name/partial account name in the *Quick Find* box
3. Click the radio button next to the desired result and click the *Select* button.
4. Account picker box will populate what was selected into the *Account* field, the box will briefly disappear, and then the box will reappear and stay until the *Cancel* button is clicked.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.0 (1.16.0.12)

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@hollyhoke Hi Holly, I was unable to recreate this on rock.rocksolidchurchdemo.com (v16.0). If you are able, can you please try to recreate on rock.rocksolidchurchdemo.com site and supply a video if you are able to recreate the issue.

**Comment by hollyhoke** [comment]
Here’s a video<https://www.loom.com/share/dfe30c2324f047ef903bef560e557477?sid=45c6c088-e7e1-4181-b139-fb799eca8f39> showing the behavior of the account picker box in the rocksolidchurchdemo site. Let me know if you are unable to view it….

Thanks!

***@***.***


Holly Hoke
Data Analyst | Software Projects

t: 717.909.2458
t: 800.901.2293
e: ***@***.******@***.***>
w: www.abwe.org<http://www.abwe.org/>

***@***.***<http://www.abwe.org/>  ***@***.*** <http://www.facebook.com/abweministries>   ***@***.*** <http://www.twitter.com/ABWE_Intl>
CONFIDENTIALITY NOTICE: This e-mail contains ABWE business information which may be confidential and is intended solely for the use of the person identified and intended as the recipient. Do not forward or further distribute this communication without permission of the sender. If you are not the intended recipient, any disclosure, copying, distribution, or taking of any action in reliance on the contents is prohibited. If you receive this message in error, contact the sender immediately and delete it from your computer.  Personal use of business e-mails is restricted by ABWE policy. As such, ABWE specifically disclaims any responsibility of liability for any personal information or opinions of the author expressed in this email.

From: Colleen Head ***@***.***>
Sent: Monday, October 30, 2023 5:27 PM
To: SparkDevNetwork/Rock ***@***.***>
Cc: Holly Hoke ***@***.***>; Mention ***@***.***>
Subject: External - Re: [SparkDevNetwork/Rock] Single Account Picker Box Not Closing After Selection is Made (Issue #5652)


@hollyhoke<https://github.com/hollyhoke> Hi Holly, I was unable to recreate this on rock.rocksolidchurchdemo.com (v16.0). If you are able, can you please try to recreate on rock.rocksolidchurchdemo.com site and supply a video if you are able to recreate the issue.

**Comment by chead4** [comment]
@hollyhoke Thank you Holly.  I was able to recreate and the issue is in our dev queue.
