### ISSUE TITLE
Group Member Attribute with Allow Multiple Values enabled will return a string separated by comma when values are accessed with Object parameter

### ISSUE THREAD

**Issue by frogydiak** [SparkDevNetwork/Rock#5655]
### Description

I created an attribute in a content channel and use Group Member as Type. I also set the group where it should use to get members from.

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/1ef9ed41-393e-4504-9aa7-1e18230d8689)

In my lava, I set it like this with `Object` parameter thinking I will get it as an array:

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/38df3abf-ef61-4fe4-98c8-d229ed95d745)

### Actual Behavior

Please see above screenshots.

But unexpectedly, what I'm getting is just the comma separated string of the group member's name that I selected:

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/758c24e1-011d-4a31-b8b2-cf82c9a039c6)

### Expected Behavior

Shouldn't it return an array object rather than a string?

### Steps to Reproduce

- Create an attribute using Group Member as Type in any content channel
- Set the Group where the attribute will get the group members
- Check the option "Allow Multiple Values"
- Edit or create a content channel item and select multiple group members
- In your public page where you show your content channel items, try to access the group member attribute that you created (See screenshots above)
- You'll get a string value instead of an array.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.2

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Hi @frogydiak Unfortunately that feature only works on certain array/collections.  There is a nuisance with the Attribute lava filter and the <code>'Object'</code> parameter in that it can only return a full object in the collection if the underlying entity is cacheable.  We just updated the [Lava docs](https://www.rockrms.com/lava/filters/attribute-filters) to spell that out a bit more clearly.

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/7b29714f-f7be-4a65-aaf3-a9af0fd669da)

For your situation, you will probably just need to get the raw value, and then fetch the item(s) you need using another approach.
