### ISSUE TITLE
Data Automation Job Causes People to be Reactivated and then Immediately Inactivated

### ISSUE THREAD

**Issue by taylorfagan865** [SparkDevNetwork/Rock#5657]
### Description

We were having a fairly large number of people being reactivated, then immediately inactivated by the Data Automation job on the same job run. We tracked this down to an error in the Data Automation job code. The job handles "Inactivate" and "Reactivate" data views differently.

We have a data view, "Do Not Inactivate", containing our list of people whom the job should not inactivate. It is set as a criteria on both the "Reactivate" and "Inactivate" sections of the job criteria.

The **Reactivate** part of the job https://github.com/SparkDevNetwork/Rock/blob/70fba2e7a15455fd812e18de07243ff2e32a89ca/Rock/Jobs/DataAutomation.cs#L189
checks to see if **any person in the family** is a member of this data view, and, if they are, reactivates those people.

The **Inactivate**  part of the job https://github.com/SparkDevNetwork/Rock/blob/70fba2e7a15455fd812e18de07243ff2e32a89ca/Rock/Jobs/DataAutomation.cs#L391
checks **only the person** to see if he's in the data view, and if not, deactivates him.

This means that if a person should be inactive (according to all the other criteria for deactivation) he will be reactivated if **any family member** is in this data view, but inactivated again immediately because **he** isn't in the data view.

### Actual Behavior

People are "ping-ponged" between active and inactive every time the Data Automation job runs.

### Expected Behavior

People should not be reactivated and then immediately inactivated.

### Steps to Reproduce

1. On a local instance, load the sample data (use a local instance so you don't corrupt a live instance)
2. Create a data view containing a "person to not inactivate"  that only contains Jim Simmons
3. Set this data view as the only criteria for the "Reactivate" and "Inactivate" sections of the Data Automation job (Tools > Data Integrity > Data Automation). Deselect all other criteria.
4. In SQL, set Brian Jones' created and modified datetimes to any day earlier than 180 days ago (because of the job criteria he won't be automatically inactivated unless his record is at least this old, and loading the sample data sets his dates as "today")
5. Manually inactivate Brian Jones. He will be the test person who will be reactivated and inactivated by the job.
6. Run the Data Automation job.
7. Observe in his history that Brian was first reactivated, because Jim Simmons, his stepfather, is in the data view. Then, he's immediately inactivated because he himself is not in the data view.

We think the job should probably be modified to only inactivate people with no family member in the data view. This would prevent these families from being "split" -- some active, some inactive.

The problem in the job happens because:
https://github.com/SparkDevNetwork/Rock/blob/70fba2e7a15455fd812e18de07243ff2e32a89ca/Rock/Jobs/DataAutomation.cs#L254 is where the "Reactivate" part of the job gets people in the data view, and later line 266 expands the list to include family members.

In the "Inactivate" part of the job, the list is expanded to include family members in line 469, before the data view is checked in line 493. This explains why one includes family members and the other doesn't.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v15.1, v16.0

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@taylorfagan865 Hi Taylor Can you include a screen shot of the Inactivate and Reactivate sections of the Data Automation job? (for step 3 above)

**Comment by taylorfagan865** [comment]
@chead4 Sure, Here are the Inactive and Reactive Screenshots:
![Inactivate - 1](https://github.com/SparkDevNetwork/Rock/assets/138168783/efd14752-3e28-4c8a-9ce3-673883542146)
![Inactivate - 2](https://github.com/SparkDevNetwork/Rock/assets/138168783/230ada02-9ed3-4932-adca-0a0df1ba303c)
![Reactivate - 1](https://github.com/SparkDevNetwork/Rock/assets/138168783/a4819860-aef6-4b70-b6f9-c09fdbee6881)
![Reactive - 2](https://github.com/SparkDevNetwork/Rock/assets/138168783/ce8ea83d-0e30-4b82-a88f-160318662f4e)

**Comment by chead4** [comment]
@taylorfagan865 Thanks for getting back to me Taylor.  We are looking into it.
