### ISSUE TITLE
Connection Request Modal Popup Shows Wrong Workflow Status for Triggered Workflows

### ISSUE THREAD

**Issue by treusch** [SparkDevNetwork/Rock#5658]
### Description

On the modal pop up window for connection requests from the connections board and list view, when you expand the Workflows panel, the status displayed for workflows that have been triggered may not always contain the right status.  Even when the workflow has completed, sometimes it will display "Running" as the status of the workflow.

### Actual Behavior

Actual BehaviorIf the workflow action sets the status of the workflow to anything other than "Completed" when the workflow completes, the status displayed on the modal popup window for that workflow will be "Running", even if the workflow is actually complete.

This is what is displayed on the modal popup window.
![image](https://github.com/SparkDevNetwork/Rock/assets/38530809/c2d36dbc-9729-44d2-9246-70e5d9adb257)

The workflow Detail page shows that this workflow is actually complete.
![image](https://github.com/SparkDevNetwork/Rock/assets/38530809/535d2102-4127-4538-8060-db0abea46837)

The line of code causing the issue:
![image](https://github.com/SparkDevNetwork/Rock/assets/38530809/322f34a3-5499-4723-b731-76c7e495fd40)

The fix:
![image](https://github.com/SparkDevNetwork/Rock/assets/38530809/916ac6c1-7845-4d81-ba20-e0482e0318cc)

This would allow the status to be based on whether the workflow has actually completed or not and would show any custom status messages Rock users have used in their workflows.

### Expected Behavior

I would expect that the code would check for a completed date/time and if that is populated, it would show the actual status that was saved on the workflow. 

If the completed date/time is not populated, then "Running" is an acceptable status to show, but even then, if the person who created the workflow writes statuses as the workflow progresses, it would be more helpful to display what that status is, rather than just "Running".

### Steps to Reproduce

Create a connection type.
Create a connection opportunity of that type.
Create a workflow that can be triggered (manually is fine) from the connection opportunity or type.
In the workflow, make sure there is an activity with an action that completes the workflow but sets the status to something other than "Completed". We needed 3 different statuses 1) Completed - Internal 2) Completed - External and 3) Completed - No Source.

Trigger the workflow to run.
View the connection request on which the workflow ran. Expand the "Workflows" panel.
Even though the workflow is complete, the screen will show that the workflow is "Running".

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

13, 14, 15, 16 and 17

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@treusch I haven't been able to recreate the issue mentioned. If you are still having the issue, could you please provide an export of your workflow?  This would help me to better understand your particular use case.

**Comment by treusch** [comment]
@chead4 My apologies. I am not sure why I wasn't getting notified of your comments. I see that the label "Not Yet Reproduced" was removed. Were you able to reproduce the issue or do you still need a workflow example exported?

**Comment by treusch** [comment]
@chead4 In case you still need it, I set up a workflow in the demo site. I ran that workflow from a connection request and you can see the results there.
[Connection Request](https://rocksolidchurchdemo.com/page/2635?ConnectionOpportunityId=3&ConnectionRequestId=1)
[Workflow Type](https://rocksolidchurchdemo.com/page/136?WorkflowTypeId=26)
[Workflow](https://rocksolidchurchdemo.com/Workflow/14)
I have attached the export of that workflow here. 

[GitHub Issue 5658_202401231905.json](https://github.com/SparkDevNetwork/Rock/files/14031745/GitHub.Issue.5658_202401231905.json)

The workflow has 2 actions in one activity. The first action just sets the Connection Request the workflow was launched from and the 2nd action just marks the workflow complete, but instead of using the status "Complete" I change it to "TestComplete" to show you that when you look at the workflows that have run on that connection request, Rock indicates that the workflow is still running, even though it is not.
![WF26](https://github.com/SparkDevNetwork/Rock/assets/38530809/abe623ab-0108-41ea-a292-33440db8a773)

![CR1](https://github.com/SparkDevNetwork/Rock/assets/38530809/d9fa3ada-f82b-4f31-9a11-b4471f576f6c)

Hope this helps. Thanks!

**Comment by chead4** [comment]
@treusch Thank you for the workflow export and additional details.  I was able to recreate the issue and appreciate you getting back to me.
