### ISSUE TITLE
Batch Detail page is missing from BreadCrumbs with new BatchDetail Obsidian block

### ISSUE THREAD

**Issue by OnlyByGrace** [SparkDevNetwork/Rock#5664]
### Description

When clicking through from the Batch Detail page to a sub page such as the Audit Log, Transaction Matching, or Transaction Detail page, the Batch Detail page is missing from the breadcrumbs.

![image](https://github.com/SparkDevNetwork/Rock/assets/5644394/57eeed36-903b-447b-a64b-39231eb168e8)

![image](https://github.com/SparkDevNetwork/Rock/assets/5644394/cc047375-3cc4-4a52-9507-20898f071315)

### Actual Behavior

When clicking through from the Batch Detail page to a sub page such as the Audit Log, Transaction Matching, or Transaction Detail page, the Batch Detail page is missing from the breadcrumbs.

### Expected Behavior

The Batch Detail Page (with the name of the batch) is displayed in the breadcrumbs as it is in v15.

### Steps to Reproduce

- Go to the Batches page and click on a batch
- Click on a transaction in the batch to view the details of the transaction
- Observe the breadcrumbs missing the Batch Detail page

![d52798e8-10b3-4162-8c74-e974c007e0b9](https://github.com/SparkDevNetwork/Rock/assets/5644394/785109b3-100e-4dcb-bb6d-81bf531dc7bc)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 17.0 (1.17.0.5) (from demo site)

### Client Culture Setting

en-US

**Comment by OnlyByGrace** [comment]
IMO this is a relatively minor issue, but I raise it because it appears to be something that will be an issue as more Obsidian blocks are pushed. Our finance team noticed this immediately because it changed their workflow. I suspect other teams would notice with other blocks, as well.

**Comment by jonedmiston** [comment]
@OnlyByGrace The team just completed a major re-work of how breadcrumbs work in Rock to allow for Obsidian to use breadcrumbs and to fix some issues that have been in the original implementation since the beginning. We're on it.
