### ISSUE TITLE
Check In App Configuration Broken

### ISSUE THREAD

**Issue by LordOpiewan** [SparkDevNetwork/Rock#5665]
### Description

Hello,

I am working on configuring the check in app on an iPad. When I enter the wrong address, I am not given a button to edit it. The only way I found to enter in a new address is deleting the app and reinstalling it. See screenshots
![IMG_0009](https://github.com/SparkDevNetwork/Rock/assets/61091009/fa971a6d-0656-4700-9a05-d6539dcd6f33)
![IMG_0010](https://github.com/SparkDevNetwork/Rock/assets/61091009/ddf05547-d081-4d01-ae61-fdd11332de55)
![IMG_0011](https://github.com/SparkDevNetwork/Rock/assets/61091009/89e35390-abd7-4715-af38-89c95fb86546)

### Actual Behavior

IMG 009 is the error I get.

### Expected Behavior

I should be able to fix my mistake when I enter in the wrong information without deleting the app.

### Steps to Reproduce

- Go to 'Checkin App’
- Enter Checkin Address
- When address fails, I get the error ‘Could not load Checkin form”

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock Mckinley 15.0 (1.15.0.12

### Client Culture Setting

en-US

**Comment by jonedmiston** [comment]
Those settings can be updated in the iOS Settings for the app. See here for more details:
https://community.rockrms.com/documentation/bookcontent/10/307#ipadapplication
