### ISSUE TITLE
Nav Bar Scroll event - Desktop Safari

### ISSUE THREAD

**Issue by atamburino** [SparkDevNetwork/Rock#5668]
### Description

On a standard side of rock the nav bar works as intended 
![image](https://github.com/SparkDevNetwork/Rock/assets/57277787/4880eed6-7c94-4ca8-99b8-ffc83cde9396)

Once the Nav bar enters the scroll state the "open" no longer functions 
![image](https://github.com/SparkDevNetwork/Rock/assets/57277787/41a0214d-afc5-40c6-b360-dbf1ec0eeaa8)

### Actual Behavior

Working as intended - 
![Screenshot 2023-11-08 at 11 26 47 AM](https://github.com/SparkDevNetwork/Rock/assets/57277787/4b37c600-1780-44db-a630-06688e272b0f)

Bug created by making screen shorter to activate scroll on navbar - 
![image](https://github.com/SparkDevNetwork/Rock/assets/57277787/f78efa29-45b4-48a4-9d44-d3a9195528e8)

### Expected Behavior

Open should work when the nav bar is on the scroll event. 

### Steps to Reproduce

- Go to 'https://rock.rocksolidchurchdemo.com' using **SAFARI**
- Login as admin admin
- Test Nav bar on standard screen size (this should work) 
- Shorten page to force the nav bar to scroll OR add a ton of icons to the nav bar to force it into a scroll event. 
- See error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.1 & 15.2

### Client Culture Setting

en-US

**Comment by andypullen** [comment]
We've seen this issue as well, on both Safari and Chrome-based browsers on macOS
