### ISSUE TITLE
PageParameter and Page Lava filters do not work in Lava-enabled Obsidian block settings

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5671]
### Description

We are heavily customizing the output of the projects in the Sign-Up Finder block. A lot of the information is powered by a persisted dataset. We need to show / hide certain projects based on a URL parameter that we can check against the persisted dataset. In setting all of this up, I found that the `PageParameter` and `Page` lava filters do not work in the Results Lava Template section of the Sign-Up Finder block. When you assign a variable to the contents of a page parameter, it is an empty string.

I think it's a bug because the `Debug` filter shows the page parameters like I would expect, as well as the `PageParameter` object.

In further testing, the filters _do_ work correctly and output the expected value if used in an HTML Content block on the same page. So the issue seems to be isolated to the Results Lava Template of the Sign-Up Finder Obsidian block.
<img width="1289" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/a8124193-d62d-42e4-bd33-2e18d424b7e0">

<img width="1216" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/75d1e224-2017-439f-bd2c-59b4e602628e">

### Actual Behavior

The `PageParameter` and `Page` lava filters do not return query string / parameter info. The assigned variable ends up being blank/empty.

### Expected Behavior

I would expect to be able to use these filters to get a page parameter from a URL.

### Steps to Reproduce

- On the demo site, go to the /signups page
- Edit the URL to add a page parameter (my edited URL looked like this: `https://rock.rocksolidchurchdemo.com/signups?testingParameter=yes`)
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/ce3b6574-5ace-4510-85ea-f99661b9b997">

- Edit the block and find the `Lava Results Template` section
- Add this code to lines 2-7:
```
{% assign testingparameter = 'Global' | PageParameter:'testingParameter' %}
parameter: {{ testingparameter }}
<hr/>
{{ PageParameter | ToJSON }}
<hr/>
{{ 'Lava' | Debug }}
```
<img width="1264" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/854f675c-5fa3-47e1-8b73-4c3552276f6f">

- Click Save and load the page
- Notice how the assigned variable, using the PageParameter filter, is empty but the Debug and PageParameter variable both have the correct information
<img width="1178" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/2f66cd2f-3bcb-46ab-8cee-a96aec4076c6">

- Alternatively, I tried the `Page` filter and it also did not work
- On the same block, edit the `Lava Results Template` again
- Add this code to lines 3-8 (copied from the [filter page](https://community.rockrms.com/lava/filters/other-filters#page))
```
{% assign queryParms = 'Global' | Page:'QueryString'  %}
Query Parms <br />
{% for item in queryParms %}
    {% assign kvItem = item | PropertyToKeyValue %}
    {{ kvItem.Key }}: {{ kvItem.Value }} <br />
{% endfor %}
```
<img width="1219" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/13863aee-8050-4872-8922-3ef42ff5e602">

- Save the block
- Notice how the parameter output is empty

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 15.1 (1.15.1.1), 16.0 (1.16.0.12)

### Client Culture Setting

en-US

**Comment by jasonhendee** [comment]
Thank, @leahjennings for another great write-up. Your level of detail and added screenshots make it very easy to reproduce most issues.

I found that this is an issue with Obsidian blocks as a whole, and not just the Sign-Ups Finder block in particular; I'm going to change the issue title to reflect this. Here's an example where I've placed a **Legacy HTML Content** block + **Obsidian Group Schedule Toolbox** block on a page. Adding your Lava snippets above to each of these blocks produces the same outcome you've described.

![Reproduce GitHub Issue 5671](https://github.com/SparkDevNetwork/Rock/assets/59710095/2039dffd-e2b4-4cce-a2ab-81feb9e4a762)

**Comment by jasonhendee** [comment]
@leahjennings in order to leverage this bug fix, you'll also need to make sure you've [switched over to use the Fluid engine](https://community.rockrms.com/lava/fluid), as the fix is not able to be easily ported back to the DotLiquid engine.
