### ISSUE TITLE
Giving Alerts do not set Workflow Attributes as stated in documentation

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#5685]
### Description

When a giving alert is configured to launch a workflow, the documentation and help text indicate that the person will be set as the initiator of the workflow and a FinancialTransactionId attribute will be set if it exists. 

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/8e750665-7b6a-468f-a184-263e74f8915d)

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/75923377-df4c-447c-bb80-a34459c1bfb6)

Neither of these values are being set.  Code shows instead, that a Person attribute is trying to be set, however, it's using Person alias instead of PersonAlias guid, and the initiator is not being set when workflow is launched:

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/6d9fcbfa-b876-45f1-90b1-b885409db874)

### Actual Behavior

Neither the initiator or a FinancialTransactionId attribute value are being set when workflow is launched from giving alert like documentation and help text mention.

### Expected Behavior

The initiator is correctly set to the person, or a Person attribute is set correctly and a FinancialTransactionId attribute is set correctly.

### Steps to Reproduce

Configure a workflow and add serveral TEXT attributes with following keys:
Person
FinancialTransactionId
FinancialTransactionAlert
FinancialTransactionAlertType

Configure a giving alert to launch this workflow. 
Make sure there are people that would meet criteria of the giving alert.
Run the Giving Automation job

Evaluate the workflows that were launched by the job.

Person will contain a person guid (and not a personalias guid), FinancialTransactionId will be blank, and the FinancialTransactionAlert and FinancialTransactionAlertType attributes will contain a guid. Also the initiator will be blank.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v14.3 (and code has not change in dev branch yet)

### Client Culture Setting

en-US

**Comment by PraveenMathew92** [comment]
Fixed in [060c14e9](Fixed in https://github.com/sparkdevnetwork/rock/commit/060c14e981cf9846477c2b1cd5603c255694acb7)
