### ISSUE TITLE
15.3 Update adds additional CheckIn folder to wwwroot directory breaking domain/checkin page

### ISSUE THREAD

**Issue by dtswill** [SparkDevNetwork/Rock#5686]
### Description

After updating Rock to version 15.3, an additional Checkin folder is added to the wwwroot directory. The Checkin folder contains only an additional folder labeled Manager. The Manager folder contains only 2 files, LiveMetrics.ascx & LiveMetrics.ascx.cs. Having the Checkin folder in the wwwroot directory breaks the use of "Church Domain"/checkin. The server throws a 403 error.

![CheckInError](https://github.com/SparkDevNetwork/Rock/assets/114791928/4e12f02a-d6a2-44e5-a477-2a68c611181f)

### Actual Behavior

The checkin page is inaccessable and the Server displays a 403 error.

### Expected Behavior

Navigation to the Rock checkin page is expected.

### Steps to Reproduce

After Updating to version 15.3, navigate to "ChurchDomainName"/checkin.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.3

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@dtswill We've uncovered the source of the problem and repaired the v15.3 package (for those who have not yet updated to v15.3).   For the 9 other organizations that have already updated to v15.3, we're going to assist them with the correction.

The correction is to move the `Checkin` folder<sup>**</sup> (incorrectly put directly into the root folder) under the `/Blocks` folder.

Can you let us know if you're able to make this fix on your system? We'll keep this open until we can verify those 9 organizations have the fix in place.

<sub>** In the v15.3 release was a correction to the `Checkin\Manager\LiveMetrics.ascx` and `Checkin\Manager\LiveMetrics.ascx.cs`.  That updated block should have ended up under the `\Blocks\Checkin\Manager\`.</sub>

**Comment by dtswill** [comment]
Thanks Nick,

My fix was to remove the offending Checkin folder from the wwwroot directory, and replace the 2 LiveMetrics files in the existing wwwroot>Blocks>Checkin>Manager folder with the new files.

I think that's the same thing?

Fix has been made and it appears to be working as intended. Thanks for the follow up.

[https://dtschurch.com/Content/EmailTemplates/will-s.png]
Will Scott
Developer

To Schedule a meeting:

calendly.com/willdts<http://calendly.com/willdts>

[https://dtschurch.com/Content/EmailTemplates/blue-location-outline.png]        Cincinnati, OH
[https://dtschurch.com/Content/EmailTemplates/blue-mail-outline.png]    ***@***.******@***.***>
[https://dtschurch.com/Content/EmailTemplates/blue-globe-outline.png]   www.dtschurch.com<https://dtschurch.com/>
[https://dtschurch.com/Content/EmailTemplates/blue-facebook-circle.png]<https://www.facebook.com/divinetechsystems/> [https://dtschurch.com/Content/EmailTemplates/blue-linkedin-circle.png] <https://www.linkedin.com/in/jyksnw>  [https://dtschurch.com/Content/EmailTemplates/blue-twitter-circle.png] <https://twitter.com/dtschurch>  [https://dtschurch.com/Content/EmailTemplates/blue-instagram-circle.png] <https://instagram.com/dtschurch>
[https://dtschurch.com/Content/EmailTemplates/hq2.png]<https://dtschurch.com/>

________________________________

**Comment by nairdo** [comment]
> I think that's the same thing?

Yep, perfect!

**Comment by cmronk** [comment]
Our organization was able to fix as well. It was only our test site thankfully.. Thank you for such a quick fix and the reaching out.

**Comment by nairdo** [comment]
We have been able to reach out to all the effected organizations and are awaiting their response, therefore I'll close this issue tomorrow.
