### ISSUE TITLE
[1.16.1.1 Alpha] Cannot Nest Entity Commands

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5687]
### Description

We noticed that some Lava using nested Entity Commands that ran fine on v16.0 broke when testing v16.1 (1.16.1.1), but only when using the Fluid engine on 16.1. We were able to work around it by refactoring the logic to not need nested Entity commands, but we're curious why they broke.

### Actual Behavior

Nested Entity Commands (at least the one instance we came across in our system) break when using Fluid engine.

### Expected Behavior

Nested Entity Commands would be allowed when using Fluid engine.

### Steps to Reproduce

Run this Lava (sorry I don't have time to reduce it to a minimal test) in Lava tester.
```
{% registration where:'RegistrationInstanceId == "{{ registrationInstanceId }}"' %}
    {% assign currentRegistrantCount = 0 %}
    {% for registration in registrationItems %}
        {% assign registrationId = registration.Id %}
        {% registrationregistrant where:'RegistrationId == "{{ registrationId }}"' %}
            {% for registrationregistrant in registrationregistrantItems %}
                {% assign currentRegistrantCount = currentRegistrantCount | Plus:1 %}
            {% endfor %}
        {% endregistrationregistrant %}
    {% endfor %}
{% endregistration %}
```
On 16.1 alpha running Fluid engine you will get an error like this:
![image](https://github.com/SparkDevNetwork/Rock/assets/3903408/7be52d57-8e68-4183-aae7-a0019534f8a9)

But on 16.1 running DotLiquid you will get nothing returned (because there's no RegistrationInstanceId)... but the point is that it ran and didn't blow up.

Also, on **16.0** the same Lava above runs fine *even on* Fluid, so something changed between 16.0 and 16.1alpha.

I also tested this on prealpha (v17.0) and it breaks there as well, as Fluid is the only engine option in v17.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.16.1.1+

### Client Culture Setting

en-us

**Comment by nairdo** [comment]
Since this bug was introduced after v16.0 (while we were testing v17 features) the fix is in v16.1 but this bug is not actually in a real release so we're not going to label this as Fixed in v16.1.  I hope that makes sense to everyone reading this.
