### ISSUE TITLE
Obsidian Registration Block Total does not match internal registration cost after discount applied.

### ISSUE THREAD

**Issue by rutledgek** [SparkDevNetwork/Rock#5691]
### Description

The Obsidian registration block total does not match the internal registration total when a discount is manually added to the registration.  The Obsidian block shows a green success message that a discount was applied, but the discount is not reflected in the total.
![Registration-Berwyn-UMC-RegistrationCost](https://github.com/SparkDevNetwork/Rock/assets/24379548/08b53139-f6ac-486a-a847-cf2be8e99647)
![Registration-Rock-RMS (1)](https://github.com/SparkDevNetwork/Rock/assets/24379548/b62e0d73-fb1b-45ee-9e04-26b64ed1f0a1)

### Actual Behavior

The total cost the obsidian block is showing for the registrar to pay is the full amount without the discount added manually.

### Expected Behavior

The payment amount should be the same amount as shown on the internal registration

### Steps to Reproduce

1. Create a registration instance that has no cost but has fees. The fees should have a cost and allow for a quantity. Make sure that the fees have Discount Applies checked.
2. Allow someone to register and select fees.  In my instance they were 2 adults and 2 children for a total of 48.00.
3. On the internal Rock Registration Edit page add a per registration discount of 8.00.
4. Edit the registrant to ensure that discount applies is checked.
5. Note that the total due on the registration is now 40.00.
6. Send payment reminder email.
7. When you click the payment reminder email, you will see a success alert that a discount of 8.00 was applied, but the total does not reflect that discount.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.0

### Client Culture Setting

en-US

**Comment by JDShuman** [comment]
I tested this in our system (also running v16.0) and observed the same behavior.

**Comment by nairdo** [comment]
@JDShuman  We've attempted to reproduce this in the upcoming v16.1 without success. We made a number of updates to this block in both v15.3 and v16.1, so we can ask the alpha testers to confirm if they are able to reproduce this in their v16.1 alpha.

**Comment by JDShuman** [comment]
Thanks, @nairdo! We are thankful for the effort you and your team continue to pour into these issues. Thanks for going the extra mile in asking the alpha testers to focus some attention here.

**Comment by nairdo** [comment]
@rutledgek When you say:
> On the internal Rock Registration Edit page add a per registration discount of 8.00.

Do you mean put 8.00 into the "**Discount Amount (per Registrant)**" field?

Assuming this is the spot you are referring to, are you selecting a discount code or just applying a raw discount value without a code?

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/f5521b2c-3ed9-4475-8996-91579401ed70)

**Comment by rutledgek** [comment]
> > add a per registration discount of 8.00.
> 
> Do you mean put 8.00 into the "**Discount Amount (per Registrant)**" field?

Just adding 8.00 discount without a code.

**Comment by kwishard88** [comment]
I'm testing this in 16.4 and still have an issue. When the discount code is assigned to the registration it isn't updating the Total Cost.

**Comment by chead4** [comment]
@kwishard88 This issue has been proven difficult to reproduce.  I have attempted to recreate on the demo site (v16.4) and when a discount code is applied either by the registrant when registering or internally by the admin the total cost is updating correctly. 
It would be greatly appreciated if you could provide steps to recreate (including screenshots) for the issue that you are experiencing and if you could recreate on the demo site that would be even more helpful.

**Comment by rutledgek** [comment]
I’m have not tried it yet, but the issue was when you placed a discount amount and not a discount code.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chead4** [comment]
@rutledgek Thanks for the feedback.  

I've tried to reproduce by applying a discount amount and a discount code internally by an admin and the balance due and total cost amounts displayed are correct.  I was able to recreate the issue in v16.2 but was unable to recreate in v16.3+.
