### ISSUE TITLE
WebForms Group Scheduler Block Handles Schedule Exclusions Unexpectedly

### ISSUE THREAD

**Issue by billdeitrick** [SparkDevNetwork/Rock#5692]
### Description

In certain circumstances, the Webforms group scheduler block incorrectly displays the first occurrence of a schedule after a category exclusion ends when a week during the category exclusion period is selected.

As an example, see the screenshot below. The week ending December 10 is selected, but an occurrence for December 31 on another schedule (with a category exclusion applied) is visible.

![Snag_19812fa](https://github.com/SparkDevNetwork/Rock/assets/4174527/1824d62a-09ed-4d0b-b494-721715d8a472)

### Actual Behavior

A future occurrence, outside of the selected week, is displayed on the scheduler board.

### Expected Behavior

Exclusions should be honored, and only occurrences within the selected week should be visible.

### Steps to Reproduce

These steps were performed on the Rock Solid Demo site and Pre-Alpha.

Navigate to General Settings > Schedules. Create two schedule categories and a schedule within each category that occurs weekly on Sundays.

![Snag_19022ef](https://github.com/SparkDevNetwork/Rock/assets/4174527/6b31f571-2867-4403-9306-ae03b9a82b32)

![Snag_1928c6d](https://github.com/SparkDevNetwork/Rock/assets/4174527/4e493724-57c7-4f42-bb86-63b4826951fc)

![Snag_192a5c2](https://github.com/SparkDevNetwork/Rock/assets/4174527/77441dd9-fa92-42b6-803f-1a351e5d4fb0)

Navigate to the Group Viewer > Serving Teams > A/V team. Delete the current "Main Campus" meeting location. Add locations for "Main Campus" during the two test schedules created in step 1.

![Snag_190dd66](https://github.com/SparkDevNetwork/Rock/assets/4174527/85056967-7ec2-4d16-a968-fc1905d31fc3)

Navigate to the Group Scheduler (Webforms version) and view each of the six weeks available from the week selector dropdown by default. I expect this is creating AttendanceOccurrence records in the background.

![Snag_19c2806](https://github.com/SparkDevNetwork/Rock/assets/4174527/09bba23d-1aad-48a2-a918-3ee07895e6ae)

On one of the schedule categories, add an exclusion over multiple weeks.

![Snag_1939dbe](https://github.com/SparkDevNetwork/Rock/assets/4174527/b9c8fe62-346d-4d8a-af1c-aeb61ab1312b)

Navigate to the Group Scheduler page, view a week prior to the end of the configure exclusion range. An occurrence is unexpectedly visible on the group scheduler board for the first week after the exclusion period ends. This may be visible across multiple different weeks.
![Snag_18edb3d](https://github.com/SparkDevNetwork/Rock/assets/4174527/74253ae7-9cd7-4e8b-a603-fc21a280a779)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

14.3, 16.0, 17.0 pre-alpha

### Client Culture Setting

en-US

**Comment by cjfountain** [comment]
We are on v15.2 and noticed the same issue. I also noticed that not only do I see the wrong date show up in the Group Scheduler, but if someone is placed on the date, it assigns the serving request to the date that had the exception. Here is a quick video of our instance and how it looks - I blurred out any personal information. https://www.youtube.com/watch?v=Xg9G4Pg8rXQ
