### ISSUE TITLE
Missing Update Persisted Dataset Job

### ISSUE THREAD

**Issue by nlBayside** [SparkDevNetwork/Rock#5693]
### Description

Wasn't sure whether this was a bug or intentional, but the demo site appears to be missing the "Update Persisted Datasets" Job. Our church's Rock instance is also missing it in our list, so I wanted to verify the same was happening on the demo site.

I didn't see anything out of the ordinary for the Job class that would prohibit it from being added to the database, but I could be missing something. It'd be very valuable to have it present even though someone could create almost the same job using the Workflow Actions.

## SQL Block
![Screenshot 2023-12-12 at 9 02 11 AM](https://github.com/SparkDevNetwork/Rock/assets/85907597/2aaf38ad-b45f-4b52-82f1-039ef963d849)

## List from Jobs Administration Page
![Screenshot 2023-12-12 at 9 06 22 AM](https://github.com/SparkDevNetwork/Rock/assets/85907597/8361daf9-41b6-416b-b9bf-116beb44066f)

### Actual Behavior

The "Update Persisted Datasets" System job is missing from the database.

### Expected Behavior

Expected the "Update Persisted Datasets" System job to be present in the database.

### Steps to Reproduce

- Go to 'Jobs Administration'
- Filter Name to 'Update'
- View list which is missing "Update Persisted Datasets" job

OR

- Using the SQL block run a query for ServiceJobs
- Filter jobs whose Name property includes 'Update'
- View list which is missing "Update Persisted Datasets" job

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v15.2

### Client Culture Setting

en-US

**Comment by JimMichael** [comment]
Just to clarify, the job is not “missing from the database”, it’s just not a _configured_ job. 

If you add a new job the “Update Persisted Datatsets” job type is available in the list. (Just verified on demo)

**Comment by nlBayside** [comment]
Oh1 Great observation! I knew I must've missed something. That's a non-issue so I'll close this out. Thank you so much for taking the time to investigate it @JimMichael !

**Comment by jonedmiston** [comment]
Just a little more context and a glimpse in to the future... When the feature was created, it was seen as a power user feature and we were uncertain how often an organization would want to run it. Since then it’s become a feature more and more people rely on. We currently have a task to add additional features to persisted datasets. This development task also has a requirement to add it to the jobs list if it’s not already been configured.”
