### ISSUE TITLE
Obsidian Registration Registrant Attribute of Type Check List appears as text box input field

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5701]
### Description

When I create a Registrant Attribute of Type Check List the field shows up as a text box for user input instead of a list of checkboxes.

Unfortunately I was not able to reproduce this issue on the demo site (16.0).

### Actual Behavior

Registrant Attribute of Type Check List appear as a text box for input.

### Expected Behavior

Registrant Attribute of Type Check List appear with a list of specified values as checkboxes.

### Steps to Reproduce

1) Create a New Registration and registration instance
2) Add a Registrant Attribute of type Check List to the Registrant Form
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/773f8d68-e90b-40e0-8e95-5f4fb2176e17)
3) Visit the registration page and see issue
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/0df2e115-fd77-4cac-b032-1301b9fc589f)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.0

### Client Culture Setting

en-US

**Comment by cabal95** [comment]
Hi @dataCollegechurch, this has already been fixed/implemented in v16.1 here: https://github.com/SparkDevNetwork/Rock/commit/e5b720e2a245c9f351e40da89a33ef2314559097

FYI When a field type is not yet supported in Obsidian it displays as a plain text input.

**Comment by dataCollegechurch** [comment]
@cabal95 - thank you for the clarification.
