### ISSUE TITLE
Group Attributes Not Displaying on Registrations in v15.2

### ISSUE THREAD

**Issue by ChristineBema** [SparkDevNetwork/Rock#5703]
### Description

Registration templates allow for placement group configurations. When you navigate to a placement group on an instance, you should be able to display different group attributes. However, in version 15.2, that ability went away. You're still able to select which group attributes you'd like to display, but they just don't appear. Tested on 15.1 on the demo site and it works, upgraded to 15.2 and it stopped working. Also tested on Pre-alpha and it's not fixed there either. See video for evidence. 
https://www.loom.com/share/1be0cb03ff3040d49e94c0871e71a5c0

### Actual Behavior

Actual Behavior: In the placement group screen on a registration instance, you're still able to hit the gear, go into group display and select which attribute you'd like to display, but this no longer actually shows the group attribute. 

### Expected Behavior

Expected Behavior: When you select a group attribute to display, it actually displays. 

### Steps to Reproduce

- Go to a Rock instance on 15.2 and above. 
- Create a group that allows check-in and has group attributes.
- Create a registration template. Allow placement configuration, and add that group as a linked group.
- Create a registration instance
- Navigate to the placement group
- Click the gear
- Select a group attribute to display
- Experience that the attribute does not display

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.2

### Client Culture Setting

en-US

**Comment by TheArkChurch** [comment]
I can confirm this behavior. It is happening for us as well in v15.2
