### ISSUE TITLE
Contribution Statement Generator Block Throws Exception When No Valid Person Is Passed Via Querystring

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5705]
### Description

When the *Contribution Statement Generator* block is configured with *Allow Person QueryString* set to Yes
![image](https://github.com/SparkDevNetwork/Rock/assets/3903408/db8f6f4c-c5e2-4236-bb54-b01c423c0152)

the page that the block is on will throw an exception IF no valid user is passed in the querystring and the page is available to All Users.

### Actual Behavior

You get an "Oops that wasn't supposed to happen" error on the page and Rock throws a Null Reference exception
![image](https://github.com/SparkDevNetwork/Rock/assets/3903408/5604d62f-6572-4c6d-a847-f3ee3c6b8335)

### Expected Behavior

When the page/block is configured to *Allow All Users* AND the visitor is not logged in AND there is no valid PersonActionIdentifier passed to the page, it should present a graceful "not authorized to see this page" or similar message instead of throwing an exception.

### Steps to Reproduce

1. On demo site, go to Admin | CMS Config | Pages | External Homepage | Give | Giving History | Contribution Statement

2. Change the security on the page to *Allow All Users*

3. Edit the block settings and set *Allow Person Querystring* to Yes.

4. Visit https://rock.rocksolidchurchdemo.com/page/444 (in a private browser window so you're not authenticated) and observe exception since there is no Person being passed to the page/block.

I'm entering this as a bug because, well, it's an exception occuring on a valid configuration, but also because block with similar "PersonActionIdenfier" functionality that are open to All Users (such as the Email Preference/Unsubscribe page) present a graceful error message when no person is passed vs. throwing an exception.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v14-v16+

### Client Culture Setting

en-US

**Comment by bmurphy-dev** [comment]
I can confirm this behavior.
![image](https://github.com/SparkDevNetwork/Rock/assets/73124289/42140291-f158-4430-9036-c0fa66d8ba65)

**Comment by unlearnd** [comment]
See also https://github.com/SparkDevNetwork/Rock/commit/4d453fc28c8831e2d3170eed91d737d3a45019a6
