### ISSUE TITLE
Registration Entity Command Not Returning DiscountCode Property

### ISSUE THREAD

**Issue by stevekleinliquid** [SparkDevNetwork/Rock#5707]
### Description

Here's the data:

<img width="552" alt="Screen Shot 2024-01-06 at 12 11 37 PM" src="https://github.com/SparkDevNetwork/Rock/assets/114983828/bd41deae-78fa-4555-9342-fce6cb531b93">

Here's some Lava which should display stuff:

```
{% registration id:'{{ registrationId }}' securityenabled:'false' %}
    {% for r in registrationItems %}
        {% assign discountCode = r.DiscountCode %} Discount code is {{ discountCode }}<br />
        {% assign discountPercentage = r.DiscountPercentage %} Discount percentage is {{ discountPercentage }}<br />
        {% assign discountAmount = r.DiscountAmount %} Discount amount is {{ discountAmount }}<br /><br />
    {% endfor %}
{% endregistration %}
```

Here's what gets displayed:

Discount code is
Discount percentage is 0.00
Discount amount is 349.00

### Actual Behavior

The Registration entity command does not return the DiscountCode property.

### Expected Behavior

The Registration entity command should return the DiscountCode property.

### Steps to Reproduce

- Create a Registration Template with a discount code
- Create a Registration Instance
- Register using the discount code
- Confirm that the Registration.DiscountCode property is updated in the DB
- Confirm that the Registration.DiscountCode property cannot be retrieved using a Lava entity command

I did this on the demo site:

<img width="1440" alt="Screen Shot 2024-01-07 at 2 37 03 PM" src="https://github.com/SparkDevNetwork/Rock/assets/114983828/8ad4d25c-4284-459c-86f3-e8dc39a44dc3">

<img width="1440" alt="Screen Shot 2024-01-07 at 2 39 31 PM" src="https://github.com/SparkDevNetwork/Rock/assets/114983828/0c93d371-d4b2-4a45-98ec-cfd5bd7f3338">

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.2

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@stevekleinliquid Hi Steve - thanks for bringing this to our attention.  After taking a look, it seems that Discount Code isn't currently supported in Lava.  But thanks to you, we are working on adding Discount Code and it will be available soon.  
![chrome_jfaGsauCjJ](https://github.com/SparkDevNetwork/Rock/assets/134172019/e670ba5f-aaeb-4df4-b113-745bddc22e20)
