### ISSUE TITLE
Signature Document Template View Access Doesn't Provide View Access

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5711]
### Description

As of Rock Beta 16.1 (1.16.1.5) permissions for Signature Documents are controlled at the Signature Document Template level instead block level security permissions or File Type security permissions. It appears that a user must have both view and edit template level permissions to view a signature document instead of just view permissions within the Signature Document List block. Even with View and Edit access to the template the user cannot view the file via GetFile.ashx.

Note: At the time of beta testing there is no demo site with Rock 16.1 to test this out on.

### Actual Behavior

Users with just view permissions cannot view instances of a Signature Document Template in the Signature Document List Block. They also need edit permissions to view the document.

### Expected Behavior

Only view access to a Signature Document Template to should be required to view instances of said template in the Signature Document List Block

### Steps to Reproduce

1) Create a new Signature Document template and provide a user/role view access to the document
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/b4324471-1061-4a51-b3e1-5a91deac9b5a)
Do not give them edit access
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/bcee54c4-bab0-473a-b1ee-58e9f04edd12)
2) Have at least one person fill out and sign the document 
For my test I had a person called "Beta Cheese" fill out the document:
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/cfd8db0c-8c07-4c2c-9fdf-ebdbd3f7c236)
3) Impersonate or sign into a user who has view access to the Signature Document template
4) Navigate to 'Beta Cheese's' and click on the Documents Tab
5) See Issue 
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/202c26c0-a80f-474f-8890-21c8ad326679)
6) Change the Signature Document template and provide edit access to the same user/role edit access
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/95689f8d-f836-46cc-a9dd-4c45f0528b26)
7) Now the use can view basic details of the document within the Signature Document List
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/79c40e1e-c9b5-449c-9293-94a9a31e6f17)
8) If they click on the document image they get a 403 forbidden message
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/53f0be04-970f-4267-8b2d-89d762fe9d05)
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/b1191f55-57d2-4332-b619-370d4ac00ea7)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.1 (1.16.1.5)

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
This was fixed last night via https://github.com/SparkDevNetwork/Rock/commit/2de4dcf0feab739fc4c65c0295fb744aa9266cc9 as this issue was being reported here.

**Comment by dataCollegechurch** [comment]
@nairdo - do you want me to open up a different issue specific to the trouble I am seeing with GetFile.ashx?

**Comment by nairdo** [comment]
Well, if you mean the cases where GetFile will show a 403 if the person does not have authorization to view, that's correct behavior.  But anything other than that, sure.

**Comment by nairdo** [comment]
We believe the fix we added to v16.1 does fix this reported issue, but I've asked @dataCollegechurch to confirm this with me via DM.  The system now uses VIEW authorization and not EDIT (EDIT was illustrated in problem description).

https://github.com/SparkDevNetwork/Rock/assets/383807/11724b99-a9ba-4c61-b1e8-9b29d87a1249
