### ISSUE TITLE
Security hole for approvals in prayer requests

### ISSUE THREAD

**Issue by RufenachtPW** [SparkDevNetwork/Rock#5715]
### Description

People who have access to enter/edit prayer requests on the internal site can approve the request and this is set as the default status. The prayer list block has a security option for groups/users who are authorized to approve requests. Only people in that security option will see the approve column to mark requests as approved. However, If staff (Think Prayer Access Role) are allowed to enter prayer requests but are not in the approval groups, they still see the approved/pending status buttons. The default status on the prayer detail block is to approved and no way changing the default status. Scenario 2, a staff member who can edit prayer requests can get around the approval process by clicking the prayer request, clicking edit and setting the request to approved. 

### Actual Behavior

Anyone who has edit rights on the prayer detail block can approve prayer requests.

### Expected Behavior

Only people in a approval security role should have access to approve prayer requests.

### Steps to Reproduce

On the demo site you will need to impersonate someone who has rights to create/edit prayer requests. Then Go to the add prayer page https://rock.rocksolidchurchdemo.com/people/prayer/add and see the status buttons add a pending prayer request. 
Then go to the prayer request list. Notice that they should not see the approved column. 
Click on the pending prayer request. Click edit (will need edit Access) and click approve and save.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.2,16.1

### Client Culture Setting

en-US

**Comment by jonedmiston** [comment]
@RufenachtPW I'm not sure your write-up is clear. 

Are you saying that it's confusing that the "Prayer Request List" block has a special security verb ("Approve") that allows an individual to approve prayer requests, but the "Prayer Request Detail" block does not have a "Approve" security verb and allows approvals for those with "Edit" access?

If so, I believe that this is by design. Having "Edit" access to a prayer request should give you rights to also approve it as this block is an internal use. The is a "Prayer Request Entry" block that is specifically designed for external use.

As I started though, I'm not sure I fully understand your write-up though so please do clarify.

**Comment by RufenachtPW** [comment]
Correct. How the internal prayer section is setup, if you give access to the staff to enter prayer requests (https://rock.rocksolidchurchdemo.com/people/prayer/add, Prayer Detail Block) they have to have edit access on the block to enter the request and because they have edit access they have approval access as well. The Prayer list block you can give edit rights to edit a prayer request but not approvals but the details block is not setup this way. To allow staff to enter prayer request without approving, you must to use the Prayer Entry block and not the prayer detail block.

**Comment by jonedmiston** [comment]
We believe this is working as intended. These are internal administrative blocks so "Edit" does give access to "Approve". Recommended options:

1. Use the "Prayer Entry" block as this gives you the experience you want.
2. Open a new Idea or Fund a Feature to add additional options to the internal admin blocks.
