### ISSUE TITLE
Sign Up Register Block Doesn't Honor Changes

### ISSUE THREAD

**Issue by KCKurz** [SparkDevNetwork/Rock#5722]
### Description

When someone signs up for a sign up opportunity using the sign up register block in Anonymous mode (signed in or not), there is an 'Allow SMS Messages' check box.  If someone submits the sign up registration with that box checked, it doesn't update the person's profile that they want a text message or not (if not checked).  It actually doesn't update any personal profile information when submitted.signup

### Actual Behavior

Nothing gets updated when submitted. 

### Expected Behavior

The person preference for SMS messaging or person profile information should be updated once submitted. 

### Steps to Reproduce

Steps to Reproduce:
Create a basic sign up set up.
Register someone for the opportunity with editing their information and/or checking off they want to have SMS enabled.
Once submitted, go to the person's profile and see that their information has not changed. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.3

### Client Culture Setting

en-US

**Comment by jasonhendee** [comment]
@KCKurz, thank you for reporting this issue. We initially designed the **Sign-Up Register** block to never update existing Person records, when operating in "Anonymous" mode, as there's a risk of maliciously or accidentally overwriting an existing Person's communication records - possibly by someone who's not even logged in. We do see, however, that the presence of the "Allow SMS Messages" checkbox was a little misleading in this case, so we've adjusted the block to allow updating only this value on an existing Person's record, when a Person match is found ([according to this scoring system](https://community.rockrms.com/documentation/bookcontent/5/295#howrockavoidsduplicates)).

Even after this fix, the block will still prevent updating an existing Person's email address or mobile phone number, as the risk described above is too high. If a Person match is not found, a duplicate Person will be created. Note also, that this block can be set to operate in "Family" mode, making it easier for families to sign up their people; the block will fall back to "Anonymous" mode in the case someone isn't logged in at the time of registering.

Please let us know if you have any further questions about this.
