### ISSUE TITLE
Workflow Forms Show Error When Double Clicking Buttons

### ISSUE THREAD

**Issue by Jon-Corey** [SparkDevNetwork/Rock#5723]
### Description

Workflow forms have configurable action buttons at the bottom of the form. When double-clicking any of these action buttons, the workflow advances as expected, but all the user sees is an error message. This means that if there is another form or a confirmation message, the user will not see it. They will only see the error.

Here is a screenshot where I double-clicked the Submit button. Notice that I still see the form and that I also see an error message. I do not see the action button's Response Text.

![WorkflowDoubleClickError](https://github.com/SparkDevNetwork/Rock/assets/110615344/8daedb4b-cbf1-4cef-aaf0-62c35fd1fe9e)

### Actual Behavior

Clicking an action button multiple times causes an error that prevents the user's view from advancing to the next item.

### Expected Behavior

The workflow action buttons should behave the same regardless of if they are clicked once or multiple times. After clicking an action button, the user's view should be advanced to the next item. They should not still see the form.

### Steps to Reproduce

1. Create a new workflow type
2. Add a Form action to the Start activity (Workflow Control > Form)
3. Add an additional Cancel button
4. Save the workflow
5. Click the Launch Workflow button
6. Double-click either the "Submit" or "Cancel" button
7. Notice the "Object reference not set to an instance of an object" error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v15.1, v17.0

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
[_We are in communication with Jon Corey and also let him know about this via his Pull Request._] This is a mission critical block that is rather complex and has been in use for 8+ years.  We're going to defer this 'double click bug' to fix it in the Next Gen WorkflowEntry block.

**Comment by chead4** [comment]
As mentioned above, this is a critical and complex block that will be fixed in the Next Gen Workflow Entry block.  At this time, we're going to close this issue and track internally.
