### ISSUE TITLE
Not able to Run Lava on Event Registration Template Pre-HTML and Post-HTML

### ISSUE THREAD

**Issue by frogydiak** [SparkDevNetwork/Rock#5726]
### Description

I am trying to add a description to the Grade person field in an event registration template form. Since using person fields and/or Person Attributes, there is no way to use a custom field label.

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/d18ab093-5688-44f7-8307-cc19de35c6a0)

In Workflows, Lava is allowed in Pre and Post HTML. This might not be a bug but if it is not, then Rock is not consistent from one feature to another. Registration template does look like more of a Workflows.

### Actual Behavior

The Lava in the Pre and Post HTML is rendered as text.

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/cc20258c-b108-466b-a2f6-55df9ea829c0)

### Expected Behavior

Lava should be able to run and executed in Pre or Post HTML fields in consistency with Workflows

### Steps to Reproduce

Add a Lava Code in the Pre-HTML or Post-HTML in an event registration form field.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.3

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@frogydiak Upon reviewing this issue, Lava is not supported for the Pre-HTML and Post-HTML fields on the Registrant Form Field.  This issue is a great candidate for an Ideas Request. I suggest submitting this as an idea on the Rock Community Ideas board via http://community.rockrms.com/ideas. This allows the full community to speak into it and help us determine it's priority.

Additionally, I'd like to share a tip for identifying Lava Supported fields.  If you select the Info icon and see {{Lava}}, is serves as an indicator that Lava is supported for that field. 
![chrome_KwsPXtSar3](https://github.com/SparkDevNetwork/Rock/assets/134172019/797ead45-062a-41a1-9638-ba6b20727471)

Thank you for helping to make Rock better!

**Comment by frogydiak** [comment]
Fair! I said: "This might not be a bug but if it is not, then Rock is not consistent from one feature to another. Registration template does look like more of a Workflows."

There are tons of ideas already posted, and some are really supported and liked by many people. How much support does an idea so it get developed or added as feature? Personally, the idea thing and voting for it doesn't really help, it always is depends on the core dev team if they agree to it regardless of how the number of votes.

For this one, I am pointing out inconsistency to the feature set of Rock. When you are working on forms like workflows, your brain still thinks the same in another part where you see the similar feature in this case Event Registration Form. Would be nice if the dev team can say something why is Lava not supported in Event Registration? Technically, not possible? Or something not yet implemented? Or just because?

**Comment by jonedmiston** [comment]
The core product team strives to incorporate as many ideas as possible within our resource constraints. Our prioritization is based on:
1. Community support
2. Resources level required (cost)
3. Ministry impact

Regarding Lava's unavailability in Pre/Post form fields, it's a "Something not yet implemented".

Rock is all about community. A key part of strengthening this bond is knowing who we're engaging with. Could I ask you to include your name, organization, and a photo on your GitHub profile? It's a simple way to put faces to names, fostering a more connected and personal community atmosphere.
