### ISSUE TITLE
Connection Board Connection Request card profile thumbnail loading blocks user action until all profile images load

### ISSUE THREAD

**Issue by KennySnow-BEMA** [SparkDevNetwork/Rock#5728]
### Description

When opening a Connection Board with a card view each Connection Request card's person profile thumbnail image must load before the user can take any other action. If the user attempts to open a Connection Request card they will receive a spinning circle until all the CR card profile images load. 

### Actual Behavior

When opening a Connection Board with a card view each Connection Request card's profile image thumbnail loads before the user can take any other action. If the user attempts to open a CR card they will receive a spinning circle until all the card profile images load. This is a frustrating user experience on a connection board with a large number of cards, easily taking 20~30 seconds or more before there is any response to user interaction.

After the first load the Connection Board card view thumbnails appear to be cached which helps load time. Load time is also minimal with default profile images or the user initials as the profile image.

![Connection Board load time](https://github.com/SparkDevNetwork/Rock/assets/157821480/cbf77c45-06ca-4d4c-9296-789ca7ba5c7c)

### Expected Behavior

When selected a Card Detail View should open quickly regardless of the profile image thumbnail loading status. Images could continue loading in the background without causing a poor user experience.

It would be helpful if there was an option to disable thumbnail images or reduce the image size that is being accessed.

### Steps to Reproduce

On a Connection Board with more than 30 or so Connection Requests associated with persons with profile images, open a Connection Opportunity board. Attempt to open a Connection Requests, click a link, or click "Back" before profile image thumbnails load. The Connection Request Detail Card will stall in opening until the profile thumbnails finish loading. On second opening (after the images cache) the response will be much faster.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v13.7,v15.3

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@KennySnow-BEMA Hi Kenny - thanks for submitting your first issue.  We took a look at some other sites that have over 800 connection requests and couldn't replicate the performance issue. It would be helpful if you could provide a video illustrating your experience.  Please keep in mind that after reviewing the video, we may categorize this request as an enhancement rather than a bug.

**Comment by chead4** [comment]
@KennySnow-BEMA Hi Kenny As I haven't received any follow-up from you I will be closing this issue at this time.  If you experience the issue again, please provide a video illustrating the issue and we can reopen and investigate further.
