### ISSUE TITLE
Mobile Style Bugs

### ISSUE THREAD

**Issue by GordonArber** [SparkDevNetwork/Rock#5729]
### Description

When updating from 14.2 to 16.2 we noticed a few visual issues with the mobile version of Rock.

### Actual Behavior

- Mobile Homepage padding
   - 15.3+ there is no padding on the edge of mobile site.
      - ![Screenshot 2024-01-26 at 2 47 14 PM](https://github.com/SparkDevNetwork/Rock/assets/19920780/870b0dd2-daa5-4e92-9346-bbd9b8e646d1)
- Mobile navbar/sidebar issues
   - If the navbar over 9 items in it, when you scroll down the orange bar goes up, but the reminder and bookmark icons scroll with you
   - If the navbar over 9 items in it, the last item can be a bit tricky to click because the admin toolbar covers it a bit.
      - ![Screenshot 2024-01-26 at 2 46 26 PM](https://github.com/SparkDevNetwork/Rock/assets/19920780/5785bcf4-e92f-4bb9-bd8f-b73ceace2472)

### Expected Behavior

- Mobile Homepage padding
   - I expect there to be a little pit of padding on the edges like there was in 14.x
- Mobile navbar/sidebar issues
   - I expect support for 9+ elements on the side navbar
      - I expect the orange bar to be sticky and scroll with the other icons.
      - I expect there to be a little margin between the last item and the admin toolbar

### Steps to Reproduce

- Go to 'the home page on a mobile device'
   - Scroll down 'the home page and see that theres no padding'

- Go to 'the cms page and create enough pages in the internal site to have 9+ icons down the navbar'
   - Visit any page on a mobile device 
   - Click on 'the hamburger button to pull up the menu'
    - Scroll down to 'the bottom of the list and look at the 2 points of interest'

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.3, 16.2

### Client Culture Setting

en-US

**Comment by jonedmiston** [comment]
@GordonArber Fixing the page padding should be easy. What device/browser were you using to show the issue on the menu issue?

**Comment by GordonArber** [comment]
> @GordonArber Fixing the page padding should be easy. What device/browser were you using to show the issue on the menu issue? The pre-alpha site is loaded up with additional menu items if you want to test there.

I am using basic vanilla Chrome. 

I added a couple more items to the menu and have the same issue on pre-alpha. The items need to extend the viewport height 

![Screenshot_20240126-161435.png](https://github.com/SparkDevNetwork/Rock/assets/19920780/40de909d-27d2-4eaf-b93a-3f542ec30c19)

**Comment by jonedmiston** [comment]
@GordonArber  This has been fixed. I rolled out the change to the pre-alpha site if you'd like to test it.

**Comment by GordonArber** [comment]
@jonedmiston That looks fantastic! Thank you for getting that resolved so quickly!
