### ISSUE TITLE
Group leader can not mark requirements as met

### ISSUE THREAD

**Issue by RufenachtPW** [SparkDevNetwork/Rock#5731]
### Description

Group leaders can not mark group member requirements complete if the group requirement is set to allow leader override. The problem is in the Group Member Detail Block. The issue is on line 1043 where a group member Id is being passed in to a getByGroupId call. `var groupMemberQuery = new GroupMemberService( rockContext ).GetByGroupId( hfGroupMemberId.ValueAsInt() );` This is fixed in [Commit 7297554](https://github.com/SparkDevNetwork/Rock/commit/7297554df3193fecb4e751f3bfc7c40adf870811). Do you know what version this will be pulled into? 

### Actual Behavior

Group leaders are not allowed to mark members requirements as complete if the requirement allows leader override. 

### Expected Behavior

Group leaders should be able to override/mark as met group member requirements.

### Steps to Reproduce

- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.3,16.2

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
> The issue is on line 1043...

@RufenachtPW  Although that line does have a bug, I'm not entirely convinced that's the only problem.  Can you update this issue with some screenshots showing the problem you're seeing.

**Comment by RufenachtPW** [comment]
@nairdo Yes I dug a little further and the change in GroupMemberRequirementCard.cs i think is also required. Line 222 originally was looking at only people in the override security authorization and that got updated if the group leader can override.  
![Screenshot 2024-01-30 at 4 15 54 PM](https://github.com/SparkDevNetwork/Rock/assets/87141140/b6f283cb-fa9d-40d6-a2ea-45bdf292b9e8)
![Screenshot 2024-01-30 at 4 16 56 PM](https://github.com/SparkDevNetwork/Rock/assets/87141140/19dab30b-5930-45d6-9526-155c31850de8)

**Comment by nairdo** [comment]
Thanks @RufenachtPW  I already knew where the setting to control the feature was, but wasn't sure what the "leader" was expecting to see.  This (below) was the screenshot I was trying to see, but once I found the other bug, it became apparent: 

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/4dcfb4bc-eb28-41bc-a06e-0ad9b333f5f2)
