### ISSUE TITLE
Group scheduling does not allow group requirements that have an override

### ISSUE THREAD

**Issue by RufenachtPW** [SparkDevNetwork/Rock#5733]
### Description

In Group scheduling you can not schedule a volunteer if you have Scheduling Must Meet Requirements turned on and the group members requirements have been manually marked as complete by an override. If a group leader marks the person as have met the group requirement this sets the override date time field but not the requirement met date time field. Group Scheduler call on Group service.GroupMembersNotMeetingRequirements. This maybe as intended but it is somewhat confusing. If you allow a leader to override the requirement then what is that actually allowing if you still can not schedule a volunteer. If the requirement is overrode, the group member list and the requirements tab does not show any validation errors but on the group scheduler the member shows has having not met the requirement and can not be scheduled.

### Actual Behavior

Group members can not be scheduled if the requirement is marked complete by an override.

### Expected Behavior

Group scheduler should match the group member list in regards to showing who has met a requirement and who has not. 

### Steps to Reproduce

1. Add the background check requirement to serving group on demo server.
2. Add Alisha Admin to the override security on the background group requirement type.
3. Go to a serving group 
4. Add a schedule to the group for scheduling
5. Check Scheduling Must Meet Requirements
6. Add Ted Decker as a member. 
7. Save
8. Go back into Ted decker and mark the requirement as met
![Screenshot 2024-01-31 at 8 09 42 AM](https://github.com/SparkDevNetwork/Rock/assets/87141140/6e5dc3f3-d5c5-4934-a7a8-8c171e34b3c4)
9. Notice on the group member list and requirement tabs that Ted Decker shows no requirement issues.
![Screenshot 2024-01-31 at 8 10 42 AM](https://github.com/SparkDevNetwork/Rock/assets/87141140/9fd98634-ab78-48b9-8707-f9b5b31136fe)
10. Go to Group scheduler
11. Notice that Ted Decker can not be scheduled because of group requirements are not met. 
![Screenshot 2024-01-31 at 8 12 36 AM](https://github.com/SparkDevNetwork/Rock/assets/87141140/11651678-8d4b-4d65-80b0-8cbdb2aa55f2)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.3,16.2

### Client Culture Setting

EN-US

**Comment by chead4** [comment]
@RufenachtPW HI there - To better understand all the details of this issue and your use case, it would be helpful if you could include screenshots and steps to reproduce on how to replicate this issue.  

Additionally, Rock is all about community. A key part of strengthening this bond is knowing who we're engaging with. Could I ask you to include your name, organization, and a photo on your GitHub profile? It's a simple way to put faces to names, fostering a more connected and personal community atmosphere.

**Comment by RufenachtPW** [comment]
Thanks @chead4 A little background this is actually part 3 of group requirement fixes. Part 1 was [age classification fix](https://github.com/SparkDevNetwork/Rock/issues/5564) Part 2 was allowing group leaders to override group requirements. [Bug fix here.](https://github.com/SparkDevNetwork/Rock/issues/5731). For this one specifically, When a requirement (Requirement being a data view or SQL) is marked as met ether by a group leader(after part 2 fix) or from an override person (Security group on the requirement) the overridden Date Time field is set but not the requirement met date time. 
![Screenshot 2024-01-31 at 8 14 13 AM](https://github.com/SparkDevNetwork/Rock/assets/87141140/61ad7b1b-6740-488f-86a4-4ec0732944a0)
I think the issue is in GroupService when we are checking for requirements and only looking at requirements that have a RequirementMetDateTime. GroupScheduler (line 766) gets the group members from AttendanceService. AttendanceService gets group member ids that lack group requirements from GroupService (GroupMembersNotMeetingRequirements). Group Service requirement query on lines 713-726 gets members who do not have a requirementMetDateTime Value which means this will mark people who have an overrideDateTime as failing to met the requirements.

**Comment by chead4** [comment]
@RufenachtPW Thank you for those details and screenshots Paul.  I was able to recreate on the demo site.
