### ISSUE TITLE
Workflow Form with Conditional Display Logic AND Captcha Throws Error

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5737]
### Description

I was unable to reproduce this on the Demo site, as I was unable to successfully setup Captcha support. Screenshots are from our Rock Instance. 

A Workflow is unable to be submitted from the Worklfow Entry Block when your Workflow Form has Conditional Display Logic AND when, in the Workflow Entry Block settings, you have the `Disable Captcha Support` Field set to `No` (meaning Captcha verification will be performed). 

See steps below for details.

### Actual Behavior

Workflow cannot be submitted when using Conditional Display Logic AND Captcha.

### Expected Behavior

Workflow should be able to be submitted when using Conditional Display Logic AND Captcha.

### Steps to Reproduce

- Ensure that you have Rock Captcha setup successfully, as per instructions in the [documentation](https://community.rockrms.com/Rock/BookContent/9#rockcaptcha).
<img width="1570" alt="Screenshot 2024-02-02 at 13 12 01" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/06ce1388-984e-42ff-a0e4-5bedab396d31">

- Create a Workflow Type, with a Form, and make sure to have at least one field in the form use Conditional Display Logic, similar to this image:
<img width="1431" alt="Screenshot 2024-02-02 at 13 14 59" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/853b4465-9093-4a54-b646-4ed81eedf49c">

- I would also recommend making sure the Workflow Type is Persisted and that Logging is set to Action.

- Setup Workflow Type to be used in a Workflow Entry Block. Then, in the Workflow Entry Block Settings, make sure `Disable Captcha Support` is set to `No`.
<img width="1189" alt="Screenshot 2024-02-02 at 12 58 42" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/76636f72-602b-4c27-a17c-3d53f9372c63">

- Try to submit the form, and see this error:
<img width="578" alt="Screenshot 2024-02-02 at 12 59 33" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/61658e7b-53ea-48f9-8fbd-8effe2a35dd2">

- Notice that the Form Action never completed, even though you clicked submit. There is no indication what the error is or why it did not complete.
<img width="1598" alt="Screenshot 2024-02-02 at 13 00 51" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/2b948418-b21d-40ee-b924-a11393a42fb8">

- Go back and set `Disable Captcha Support` to `Yes`. Try to submit the Workflow. See that you are now able to successfully submit it.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.2

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@mikedotmundy Hi Mike - I set up captcha on the demo site (v16.2) to try and recreate your issue.  Unfortunately, I haven't been unable to recreate it. It would be greatly appreciate it if you could export and share your workflow as this would ensure that I understand your specific use case and don't miss anything.

**Comment by dataCollegechurch** [comment]
Are you seeing this behavior on your internal or external site. Also what is the full list of settings you have in place for the workflow entry block?

**Comment by mikedotmundy** [comment]
Here is the WF - I just tested it a bunch again. The only way I can get it to work is by disabling Captcha support:
[Submit Benevolence Request - Test_202402022215.json.zip](https://github.com/SparkDevNetwork/Rock/files/14149494/Submit.Benevolence.Request.-.Test_202402022215.json.zip)

This is happening on the external site. All settings for the Workflow Entry block are default.

**Comment by mikedotmundy** [comment]
Here is what happens when Captcha is _disabled_ (it works successfully):
https://github.com/SparkDevNetwork/Rock/assets/23226974/8e837170-d842-492b-b975-faec96725f27

Here is what happens when Captcha is _enabled_ (it does not work):
https://github.com/SparkDevNetwork/Rock/assets/23226974/db98f077-d563-41c8-a1f4-3053c472c0c0

**Comment by chead4** [comment]
@mikedotmundy Hi Mike - Can you send me a screenshot of your CloudFlare settings so I can make sure I set mine up the same?  I set mine to non-interactive so that I could see CloudFlare widget.
![image](https://github.com/SparkDevNetwork/Rock/assets/134172019/bf0cb6b4-535e-4f6f-9fe6-35d5e05adc69)

**Comment by mikedotmundy** [comment]
<img width="643" alt="Screenshot 2024-02-06 at 17 03 35" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/d54103af-1b5d-4bb2-b789-a70ccc484cfd">

**Comment by mikedotmundy** [comment]
@chead4 Mine is set to managed.

**Comment by chead4** [comment]
@mikedotmundy Hey Mike - Thank you for the CloudFlare details.  I was able to recreate your issue on v16.2 (v16.2 time machine) when Disable Captcha Support is set to No; but, I was not able to recreate on the demo site (v16.3).  I will be closing this issue at this time.  Please reach out if you are able to recreate in v16.3 and I can reopen.

**Comment by mikedotmundy** [comment]
Updated our dev server to v16.3 Alpha (1.16.3.1) and it is working for us too. Thank you @chead4!
