### ISSUE TITLE
New Batch Obsidian Block Doesn't Print Well

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#5740]
### Description

We used the batch page to print reports but the new obsidian block doesn't print well. It doesn't show all the columns.

Prior to Obsidian
![IMG_0681](https://github.com/SparkDevNetwork/Rock/assets/1486523/ffa3e5f3-1da7-4df8-8421-ea95a6a56527)

After Obsidian
![IMG_0683](https://github.com/SparkDevNetwork/Rock/assets/1486523/3c101712-f750-49a9-98e2-3491dc3bdbc8)

### Actual Behavior

The columns that are visible on the screen are not visible when printed

### Expected Behavior

I would like for all the columns on the screen to show like prior. 

### Steps to Reproduce

Go to Finance > Batches.

Filter to show batches you want. Use File > print to print the page.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.2

### Client Culture Setting

en-us

**Comment by jonedmiston** [comment]
This is not in the v16.3 alpha, but will be in beta.
