### ISSUE TITLE
Add Entity Attribute modal jumps on value selection

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/Rock#5741]
### Description

When adding an entity attribute and selecting which defined values are selectable for the defined type, the modal window 'jumps' to the top after selecting each available defined value.
![Add Attribute Screen Scrolls](https://github.com/SparkDevNetwork/Rock/assets/8688424/57ff0fe4-3ed4-4b8e-9df3-7237af16dd36)

### Actual Behavior

After making a defined value selection, the position on the page scrolls to the top

### Expected Behavior

When selecting which defined values will be available, I expect the screen to stay where it is unless I tell it to scroll

### Steps to Reproduce

1. Create a _Defined Type_ with multiple _Defined Values_ (I created 10)
2. Create an Entity Attribute and set the field type to _Defined Value_
3. For the associated _Defined Type_, under _Selectable Values_, select a _Defined Value_ from the list
4. The screen jumps to the top after making your selection

I tested this using the demo site and a Rock Master Class instance

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.2

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@smross We agree, and even though it's a small nuisance to us admins, it was not quite trivial to fix this in the webforms block.  But we do have it working in the experimental Obsidian version of the block so we're going to close this with the https://github.com/SparkDevNetwork/Rock/labels/Will%20Fix%20In%20Next%20Gen label for now.
