### ISSUE TITLE
Summernote cannot use visual editor with formatted lava code

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5742]
### Description

When I attempt to add formatted lava to an html attribute the browser displays this message: "The markup contains content that may not be compatible with the visual editor." This makes it difficult to continue editing the html content as the editor is stuck in Code Editor mode unless you remove the lava.

### Actual Behavior

Summernote HMTL editor cannot use the visual editor and formatted lava code. This issue is present on the community site and Rock.
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/bb5373c3-bcce-4476-89ea-9a3f9bd031c2)

### Expected Behavior

The summernote HTML editor should be able to use the visual editor to display formatted lava as long as the code is surrounded by a `<pre>` tag.

### Steps to Reproduce

1. Create a new HTML Person Attribute or Rock Recipe
2. Go into the Code Editor Mode of any field leveraging SummerNote
3. Add the following code or any formatted lava containing `{%`
`<pre class="">{% if 1=1 %}{% endif %}</pre>`
4. Attempt to switch back to visual editor
5. See Issue
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/2c4b575a-47ec-46c5-9438-1bf4e0fe95c6)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.2

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Hi @dataCollegechurch Tony, We purposely disabled the WYSIWYG (SummerNote) editor when Lava is being used because the HTML editors (such as SummerNote) cannot handle greater than (>) and less than (<) characters without encoding them -- and  when they do encode them, it breaks the Lava.  So, I don't even think this behavior will change in the "Next Gen" solution, but we'll keep in in consideration when we are testing the next gen WYSIWYG editor.

**Comment by dataCollegechurch** [comment]
Thanks for the explanation @nairdo, that helps me understand what is going on better.
