### ISSUE TITLE
SQL Run Workflow Action Parameters Not Saving

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#5743]
### Description

Tell us what you see!

### Actual Behavior

I found a bug tonight where the Workflow Type Detail block will not save parameters on a newly added SQL Run workflow action. It saves the workflow, but anything added to the parameters is just forgotten, and then the action fails to run if the query relies on them. It does not appear to be an issue if the workflow type has been saved since the SQL Run action has been added – it's only when you try to add the action _and_ populate parameters and save it all in one go.

### Expected Behavior

SQL Run workflow action parameters should always be saved when the workflow type is saved.

### Steps to Reproduce

- Add a new SQL Run workflow action to any workflow
- Populate at least one parameter key/value
- Save workflow type
- Edit workflow type
- See that parameters on the SQL Run action were not saved

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

17.0.12

### Client Culture Setting

en-US

**Comment by briankalwat** [comment]
So, it turns out this is also happening with the Key/Value list Defined Value attribute for Text to Workflow. It may be a system-wide bug with Key/Value list field type.

**Comment by chead4** [comment]
@briankalwat Hi Brian - I have added the issue from your comment to our internal ticket and this will be addressed as well.
