### ISSUE TITLE
Registration Triggers not starting

### ISSUE THREAD

**Issue by carriewhite** [SparkDevNetwork/Rock#5746]
### Description

Registrations are not triggering a workflow.  None of the three options for triggering a workflow are working; the workflow isn't started.  The same registration/workflow do work as expected in 16.0.

### Actual Behavior

The workflow is not started.

### Expected Behavior

The workflow would execute.

### Steps to Reproduce

- enter a workflow trigger on a registration template or instance
- note the workflow does not start when the registration is completed

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.4

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@carriewhite Hey Carrie-  I will be closing this issue as not an issue after our discussions and your further investigation that a new workflow had an endless loop that impacted workflows from starting.
