### ISSUE TITLE
Event Registration default Lava Template sends waitlist members 'Additional Confirmation Details' in confirmation email

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/Rock#5747]
### Description

The default lava template for waitlist members sends Event Registration Instance _Additional Confirmation Details_ in the initial registration process, before they have been moved from the waitlist to the registrants.

I will be submitting a Pull Request to fix this.

### Actual Behavior

Waitlist members receive additional confirmation information.

### Expected Behavior

The default lava template for an event registration instance confirmation email should not send waitlist members additional confirmation details until they have been moved off of the waitlist.

### Steps to Reproduce

1. Create an event registration that has waitlist functionality enabled, using the default communication settings.
2. Add registrants to reach the limit and put the registration instance into waitlist mode.
3. Register again (the additional registrant is now on the waitlist).
4. The registrar/registrant that is on the waitlist receives the 'additional confirmation details' information that is incorrect for waitlist recipients.

The confirmation email will send to them _again_ when they are moved from the waitlist to the registration, so there is no reason to send them the additional confirmation details when they are on the waitlist.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

14.4, 16.2

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@smross Hi Shawn - I am unable to recreate your issue in v16.2 and v16.3.  Could you please supply screenshots of the issue that you are experiencing?

**Comment by smross** [comment]
@chead4 yes, I definitely will when I'm next able to. Hopefully this weekend.

**Comment by smross** [comment]
@chead4 Here's screenshots and an example process (sorry I missed that in the original):
### Prerequisites:

- Email setup in the Rock instance
- An Event Registration Template using the default Communication Settings Lava Template for `Confirmation Email`; the default lava is set starting at https://github.com/SparkDevNetwork/Rock/blob/53fde76bf9376b9b7f5c7abb96b39caae03087a7/RockWeb/Blocks/Event/RegistrationTemplateDetail.ascx.cs#L52 and ending at https://github.com/SparkDevNetwork/Rock/blob/53fde76bf9376b9b7f5c7abb96b39caae03087a7/RockWeb/Blocks/Event/RegistrationTemplateDetail.ascx.cs#L137 with the problem being https://github.com/SparkDevNetwork/Rock/blob/53fde76bf9376b9b7f5c7abb96b39caae03087a7/RockWeb/Blocks/Event/RegistrationTemplateDetail.ascx.cs#L130
- Information in the _Additional Confirmation Details_ (not blank)

### Process with screenshots:
1. Create a new Registration Template, with waitlist enabled: <img width="632" alt="Bug5747-01" src="https://github.com/SparkDevNetwork/Rock/assets/8688424/ecea2a2f-7bd7-4de5-b24a-794af20ec406">

2. Accept the default Communication Settings
3. Populate the Registration Instance's _Additional Confirmation Details_: <img width="823" alt="Monosnap Registration Instance | Rock RMS 2024-02-13 09-53-39" src="https://github.com/SparkDevNetwork/Rock/assets/8688424/918181c1-a3da-40fe-98d5-9aadcae59165">

4. Register enough people to get to the _Maximum Attendees_, such as 'Shawn Ross': <img width="841" alt="Bug5747-02" src="https://github.com/SparkDevNetwork/Rock/assets/8688424/03663ea8-b82c-45ff-a82c-a0ccbf3ee62a">

5. They receive a confirmation email, such as this one that includes the _Addtional Confirmation Details_: <img width="386" alt="Bug5747-03" src="https://github.com/SparkDevNetwork/Rock/assets/8688424/38ca5260-e1cc-472d-90cc-684603eb55df">

6. Register an additional person so that they are on the waitlist, such as 'L.... Ross': <img width="565" alt="Monosnap Registration Instance | Rock RMS 2024-02-13 10-01-51" src="https://github.com/SparkDevNetwork/Rock/assets/8688424/42e97f21-65ba-4501-8bea-1134c1623d97">

7. They receive a confirmation email that incorrectly includes the additional confirmation details, such as: <img width="385" alt="Bug5747-04" src="https://github.com/SparkDevNetwork/Rock/assets/8688424/5b922f31-c726-4ae2-836b-4e2585b45cc7"> 

8. Move someone from the waitlist to be a registrant, and they will correctly receive the confirmation email which includes the additional confirmation details, such as: 
![Bug5747-05](https://github.com/SparkDevNetwork/Rock/assets/8688424/f3672480-acad-4098-9b4c-e81a42544c2b) and <img width="382" alt="Bug5747-06" src="https://github.com/SparkDevNetwork/Rock/assets/8688424/d051e459-a9a9-4d51-a931-4dfbb0a10745">

I was able to duplicate this bug in the following systems:

- Our Rock Production instance, running 14.3 (1.14.3.1 en-US)
- Our Rock testing instances, when we were running 16.2 and 16.2 Alpha (We also have history that this has occurred with 15.4, but I don't have prooftests for it, and won't be doing prooftests for 15.4).

**Comment by chead4** [comment]
@smross Thank you for providing all the additional screenshots Shawn.  Very much appreciated!

**Comment by nairdo** [comment]
Just to clarify for anyone else looking at this issue.  There is also a corresponding data-migration that will be in v16.4 as [Rollup_20240315.cs](https://github.com/SparkDevNetwork/Rock/commit/f39a86b49f3f3b0ae5d40f66c29eb0c9c99f8661#diff-ce7d3351f42989aeeb8dd288a3bbd7c986f7e4c06af9be5f2b53194b9ea5c791R62) to correct any existing RegistrationTemplates.
