### ISSUE TITLE
[Alpha 1.16.3.1] Obsidian Email Preference Entry Block Unsubscribe Successful Issue

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5751]
### Description

In the new **Obsidian Email Preference Entry** Block, you are told you have unsubscribed from all mass communications even if you actually did nothing to unsubscribe. See image:
![Screenshot 2024-02-13 at 11 32 26](https://github.com/SparkDevNetwork/Rock/assets/23226974/50ea1151-7cc6-490b-9587-92b996304086)

You will notice in the URL that I navigated to this page by manually entering the person's Id (`/1`). In our instance, we allow users to navigate to this page via `/MyAccount` so they can update their Email Preferences. (We pass the person `Guid`, not `Id` - just used the `Id` in this example for simplicity.) We also include an Email Preferences link in our email footer that navigates a person to this page.

Also,
Even though it says "Unsubscribe Successful", you are not actually unsubscribed from anything. 
Even though it says "...unsubscribed from all mass communications..." the setting on your profile is not changed to reflect this.

**NOTE** 
All of the options under "Other Actions" do work properly.

The Webforms version of this block would also already have your preference selected when you navigated to the page with this block on it. This is not the case in the Obsidian version.
![Screenshot 2024-02-13 at 13 22 04](https://github.com/SparkDevNetwork/Rock/assets/23226974/6b9dd24c-cf2c-4925-9aba-d0b87c41571c)
![Screenshot 2024-02-13 at 13 22 12](https://github.com/SparkDevNetwork/Rock/assets/23226974/6fc20e57-f629-4de4-8be3-329845b9e999)

### Actual Behavior

Navigating to a page with this block will show you "Unsubscribe Successful" even though you may have landed on this page without unsubscribing from anything.

### Expected Behavior

A person should be able to navigate to a page with this block without seeing the Unsubscribe Successful message UNLESS they navigated to this page via the new one-click feature.

### Steps to Reproduce

- On an instance running v16.3 or higher, navigate to `/EmailPreferences/1` (or pick a different PersonId)
- See the Unsubscribe Successful Message
- Navigate to `/person/1` and see that you were not unsubscribed from anything. Also see that you still have all emails allowed.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.3, v17.0

### Client Culture Setting

en-US

**Comment by JimMichael** [comment]
This is interesting, as the first release note under Communications for 16.3 says _"Updated the Email Preference Entry block to auto-unsubscribe on load."_

I assume the change was necessary for the new 1-click unsubscribe stuff, but they just labeled it as a bug. Now curious how it's SUPPOSED to work.

**Comment by mikedotmundy** [comment]
@JimMichael If that is true, and it will _auto-unsubscribe_ on load, then I would hope there is a new/different avenue to allow for updating email preferences. Is there a better way to do it that I am not using?

**Comment by chead4** [comment]
@JimMichael Hi Jim - thanks for pointing out that release note -  as we agree it is confusing.  We will be updating the release note and it should state: Updated The Email Preference Entry block to auto-unsubscribe on load when performing a one-click unsubscribe.
