### ISSUE TITLE
Legacy Connect Button Doesn't Do Anything

### ISSUE THREAD

**Issue by highlandslah** [SparkDevNetwork/Rock#5762]
### Description

When working on the legacy Connection Request Detail block ([ConnectionRequestDetail.ascx](https://github.com/SparkDevNetwork/Rock/blob/bb56268808f202f37f0811c305ebfff1b2a8bbde/RockWeb/Blocks/Connection/ConnectionRequestDetail.ascx) / [ConnectionRequestDetail.ascx.cs](https://github.com/SparkDevNetwork/Rock/blob/bb56268808f202f37f0811c305ebfff1b2a8bbde/RockWeb/Blocks/Connection/ConnectionRequestDetail.ascx.cs)) clicking the Connect button doesn't do anything.  You have to refresh the page in order for the change to be reflected.

https://github.com/SparkDevNetwork/Rock/assets/157643319/e5995b88-3464-482b-858c-4d41055ea7f5

### Actual Behavior

The connect button doesn't do anything on the Connection Request Detail block, you have to refresh the page to see the change. 

### Expected Behavior

When clicking on the connect button on the Connection Request Detail block the change should be reflected immediately and you shouldn't have to refresh the page to see the change. 

### Steps to Reproduce

1. Go to the legacy Connection page (/page/407) to select a request. 
2. Select a request.
3. Click Connect and notice no change.
4. Refresh page and now the change is reflected.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v15.3 / v16.0 / PreAlpha

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@highlandslah Hi there.  Thank you for submitting your first issue.  

Rock is all about community. A key part of strengthening this bond is knowing who we're engaging with. Could I ask you to include your name, organization, and a photo on your GitHub profile? It's a simple way to put faces to names, fostering a more connected and personal community atmosphere.
