### ISSUE TITLE
spCrm_FamilyAnalyticsGiving includes archived membership

### ISSUE THREAD

**Issue by erickpece** [SparkDevNetwork/Rock#5766]
### Description

When trying to pull Family Giving Analytics, like "Last Gave", "First Gave", etc... we're seeing that anyone who started out as a child and was later moved to their own family does not have these attributes updated.

When I dug into the `spCrm_FamilyAnalyticsGiving` procedure, it appears that it's picking the TOP 1 group match, even if the group member has IsArchived set to True.

In the stored procedure where `SELECT TOP 1 gm.[GroupRoleId] AS [FamilyRole]` is used to get the Person's role in the family, their previous family membership is listed first since it has an earlier Id. However, if I add `AND gm.IsArchived = 0` to the WHERE clause, their correct group is returned.

This may be related to https://github.com/SparkDevNetwork/Rock/issues/4994 as it has a similar structure.

I will note that I discovered that `Enable Group History` was turned on for my Family Group Type.

### Actual Behavior

Archived group members are evaluated.

### Expected Behavior

Only non-archived group members should be included.

### Steps to Reproduce

I suspect that having group history enabled is causing this to occur. I don't want to do this on the demo site so it doesn't cause problems for the other users.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.2 (1.16.2.1)

### Client Culture Setting

en-US

**Comment by erickpece** [comment]
We did turn off the Group History for the Family Group Type, but that doesn't appear to clean up the `GroupMembers` table, just `GroupHistorical` and `GroupMemberHistorical`.

**Comment by erickpece** [comment]
Something that feels a little weird... if someone gets married and changes giving groups, their giving attributes change... I suppose that is to be expected since it's based on the family, correct?

**Comment by nairdo** [comment]
> We did turn off the Group History for the Family Group Type, but that doesn't appear to clean up the GroupMembers table...

Yeah, that's true.

> if someone gets married and changes giving groups, their giving attributes change...

That should also be true.  Are you not seeing that happen?
