### ISSUE TITLE
Event Registration Template Group Placement Button Throws exception when clicked

### ISSUE THREAD

**Issue by wiwaterhouse** [SparkDevNetwork/Rock#5768]
### Description

While on a registration template with group placement configured, clicking the placement button throws an exception in Rock v16.2.

### Actual Behavior

On Rock v16.2, using any registration template (existing or new) and adding group placement, clicking the placement button on the template throws an exception. I have tested with and without registration instances added to the template with the exact same exception. I was also able to reproduce this behavior in the Rock demo site. I was unable to reproduce in our v14.3 production environment.

### Expected Behavior

Add group placement to a registration template, then click the placement button. Rock opens the placement page.

### Steps to Reproduce

1. Create new registration template or use existing template
   NOTE: when creating new template, also create new registration instance
![Screenshot 2024-02-27 at 8 42 34 AM](https://github.com/SparkDevNetwork/Rock/assets/114443707/354159ea-a960-48d2-a5e5-1295ceef6a7e)

3. Add group placement with any group type
![Screenshot 2024-02-27 at 8 43 12 AM](https://github.com/SparkDevNetwork/Rock/assets/114443707/9c467873-9176-4622-b0c6-5fbd781f36de)

5. Save then click the placement button
![Screenshot 2024-02-27 at 8 51 45 AM](https://github.com/SparkDevNetwork/Rock/assets/114443707/0f9457db-71a1-4ce8-b883-44401228ed92)

7. Throws Exception
![Screenshot 2024-02-27 at 8 51 10 AM](https://github.com/SparkDevNetwork/Rock/assets/114443707/a31ce081-009d-4051-90d2-b9780dc9f453)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.2

### Client Culture Setting

en-US

**Comment by zackdutra** [comment]
We are seeing this in 15.3 also.

**Comment by nairdo** [comment]
It looks like we also ran into this and recently fixed it in January for v16.3 (via https://github.com/SparkDevNetwork/Rock/commit/5ab5ebf5dfe97853e733a30a0a914a8e6c3c1fb9) .
