### ISSUE TITLE
CampusId Uses Wrong Value For Attendance Entered Through Rapid Attendance Entry Block

### ISSUE THREAD

**Issue by zackdutra** [SparkDevNetwork/Rock#5772]
### Description

When attendance is entered through the Attendance Entry Block, the CampusId uses the Campus from the Group.CampusId rather than the Campus associated with the check in location.  This causes issues for groups that do not have a campus, such as a "9th Grade" check in group that is shared across multiple campuses. If the group does not have a campus, no campus Id will be recorded, and the attendance record will not populate in Attendance Analytics when the campus is running reports.  This deviates from how check is Attendance is normally recorded because standard check in uses CampusId from the Location rather than the group, allowing multiple campuses to use one group. 

Reproduced on demo site. 

### Actual Behavior

The attendance is saved incorrectly using the group campus rather than the location campus, causing a mismatch between normal iPad check in and rapid attendance entry check in.

<img width="1371" alt="Screenshot 2024-02-28 at 12 16 01 PM" src="https://github.com/SparkDevNetwork/Rock/assets/96394991/ef19059f-a016-427b-9849-e13697c7e71e">
<img width="1391" alt="Screenshot 2024-02-28 at 12 00 08 PM1" src="https://github.com/SparkDevNetwork/Rock/assets/96394991/6f8cac1a-ac62-4b09-9286-fa25c6f29700">

### Expected Behavior

All attendance records should have CampusId sourced from the Location provided.

### Steps to Reproduce

- Set up more than one campus
- Set up a group with check in location schedule configs with more than one campus location 
- Either leave the group campus blank, or set it intentionally to a specific campus 
- Go to the Attendance Entry page (People > Rapid Attendance Entry)
- Choose the group, campus, location, and schedule for one campus (different from the campus you set on the group if you set one)
- Take attendance 
- BONUS: Do iPad check in as well for  comparison records.
- Go back to your group and look at the occurrences to get the ID of the one you just did 
- Use the SQL tool to run a query: SELECT * FROM [Attendance] WHERE OccurrenceId = PUT ID HERE
- View the CampusId column. Results for the Attendance Entry block will all show the group's campus Id, but iPad check in will show the location's campus id. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.3

### Client Culture Setting

en-US

**Comment by jasonhendee** [comment]
@zackdutra, thank you for reporting this issue. We agree that Attendance taken here should use the Location's Campus, but only if the Group doesn't have a Campus assigned. If the Group does have a Campus, it will take precedence over the Location's Campus; the above commit changes the block's behavior to do this.

We understand this is different behavior than the way Check-in takes attendance, but this block was designed to take attendance for a Group - outside the context of Check-in - so a Location's Campus should not overrule the Group's Campus here.

**Comment by zackdutra** [comment]
Thanks Jason! I think I would take the opinion that the reverse should happen when a campus is present on the group but you're intentionally doing attendance for a different Location, but since this doesn't interfere with the specific issue we had, and that's a pretty niche scenario, this fix should work for us. Appreciate you working on it!
