### ISSUE TITLE
Enhanced dropdown not working on mobile device

### ISSUE THREAD

**Issue by kevinkrugerCCV** [SparkDevNetwork/Rock#5774]
### Description

On a registration form or site page, we use a defined type (34) also in Demo Rock for a list of available schools in the valley. We the use a person attribute of Defined Type for that school defined type where we can enable the enhanced list. 

![image](https://github.com/SparkDevNetwork/Rock/assets/91297818/d7cb0d56-390b-4a0c-88db-cc49b86ffc59)

Once that person attribute is added a field on a form (registration) for the user to select, if the form is worked from a computer or even if using a computer inspect mobile view window, the user has the option to start typing and see a narrowed list of options from that enhanced list. 
<img width="1367" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/91297818/b98032a5-9276-4fd4-ad55-d258764fd088">

On a mobile device (android or apple) the user will see that same drop down but will not be able to refine the list by typing. 
![55139840-29D2-4800-98CD-8D9D1BA5A92B_4_5005_c](https://github.com/SparkDevNetwork/Rock/assets/91297818/6ffdf30c-8162-43ba-bfee-f402ce393ce9)

![F02F7256-6158-4E36-8B45-5A8F018BE0DD_4_5005_c](https://github.com/SparkDevNetwork/Rock/assets/91297818/63faca51-ecf7-4ed9-b9a5-d24db7cc4a56)

This list is populated using an API and is not alphabetized based on when it was added so finding a school without a search can be difficult. 

### Actual Behavior

Enhanced dropdown list on mobile devices do not allow typing to narrow list results. 

### Expected Behavior

We would expect the enhanaced list functionality that is available on a desktop window display to also be available on a mobile device. 

### Steps to Reproduce

- (if possible) seed school defined type with dummy school data. 
- Enable the "Enhanced List" feature on the person attribute for schools (demo rock person attributeId = 739) 
- Add that attribute to a registration or form 
- visit registration from mobile device
- See unmanageable dropdown

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

14.2

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
> We would expect the enhanced list functionality that is available on a desktop window display to also be available on a mobile device.

Hi @kevinkrugerCCV, we won't be able to change that behavior because it is a limitation in the library we use (called "Chosen", created by Harvest).  They mention that in their FAQ here: https://harvesthq.github.io/chosen/#faqs

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/25d45147-16e8-4d8f-a060-e9d80d88cd7f)


Regarding this:
> This list is populated using an API and is not alphabetized based on when it was added so finding a school without a search can be difficult.

A DefinedType's DefinedValues are orderable, so the Rock pickers should respect this order.  If you are populating them via an API, it should also set the appropriate order as needed.

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/60affd72-2f36-4ba0-b277-911928725427)
