### ISSUE TITLE
Obsidian Page Short Link Detail Block Does Not Honor Token Length

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5775]
### Description

The _Page Short Link Detail_ block defaults to a minimum token length of 7 characters, but via a block setting it can be changed to a length < 7.
![image](https://github.com/SparkDevNetwork/Rock/assets/3903408/8cabb3fe-28c0-43cd-999c-2a3a71ab9886)

However, this setting is ignored and attempting to actually create/save a Short Link with a character length shorter than 7 characters results in an error. 

### Actual Behavior

The block will not save a token less than 7 characters, even if you have the block setting defined to allow tokens shorter than 7 characters.
![image](https://github.com/SparkDevNetwork/Rock/assets/3903408/0fcef72a-f8ff-4528-aa3d-a97fef8dfabb)

### Expected Behavior

Tokens < 7 characters could be created/saved as long as the block settings allow it.

### Steps to Reproduce

I tried this on 16.2, 16.3beta, prealpha, all with the same result.

1. Go to Admin | CMS Config | Short Links
2. Edit the _Short Link Detail_ block and change the Minimum Token Length to 6
3. Create a token of 123456 and click Save
4. Observe error.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.2+

### Client Culture Setting

en-US

**Comment by MatthewKyle22** [comment]
I've ran into this issue as well.
