### ISSUE TITLE
Workflow Action "Reminder Add" - Reminder Date & Notes not honored

### ISSUE THREAD

**Issue by stanalyst** [SparkDevNetwork/Rock#5777]
### Description

Trying to use the workflow action "Reminder Add" to create a reminder for a future date and include a custom note from the user ... the reminder is created - but the reminder date on it is the current (run) date (not the future date) ... and the note field is populated with a GUID (probably for the workflow text attribute that has the custom note.

![image](https://github.com/SparkDevNetwork/Rock/assets/112125627/c416927a-ebe3-420f-9ab0-aa087dd7b2b8)

![image](https://github.com/SparkDevNetwork/Rock/assets/112125627/cc8a1896-bd34-4e4b-858c-8c6fa677f3b0)

### Actual Behavior

The Reminder Date on the reminder created by the workflow action is the current/run date - not the future date stored in the provided workflow attribute.
The Note on the reminder is what looks like a Guid ... and not the custom text from the workflow attribute that was provided to the action.

### Expected Behavior

The created reminder should have reminder date and note that match what was provided by the workflow attributes.

### Steps to Reproduce

- Create a workflow that has 4 attributes: CurrentPerson, TargetPerson, ReminderDate, & ReminderText
- Add following actions:
![image](https://github.com/SparkDevNetwork/Rock/assets/112125627/3ae37096-ef1a-4f6b-8648-b219e4db17fa)

- In the form - allow user to pick the target person, reminder date, & & reminder text.
- Setup the reminder action as shown above.
- Run the workflow and select a target person, a reminder date in the future, and enter reminder text.
- After completion - go to your reminders and confirm values on the newly created reminder ... note that the reminder date is the current date not the one you entered - and the note value is a guid.

I've also included the export of the workflow I setup on the demo site to confirm the bug we were seeing on our site.
[Test Reminder Add action_202403011417.json.zip](https://github.com/SparkDevNetwork/Rock/files/14466221/Test.Reminder.Add.action_202403011417.json.zip)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.16.2.1

### Client Culture Setting

en-US

**Comment by stanalyst** [comment]
Additional side note ... I also tried using Lava in the other setting fields (instead of the attribute value dropdown) - and this was worse. The action step completes without any exceptions or messages in the log - but the reminder was NOT created. As best as I was able to determine it was related to the Reminder Date ... I tried all different variations on the format for the date - but if I provided anything in that field - the reminder would NOT be created - with no indication of why.

![image](https://github.com/SparkDevNetwork/Rock/assets/112125627/37a188e3-e243-4b2c-a9c9-8e32b96b31f1)

I can confirm that you could put static text in the Note field - and that would be saved to the reminder - but that really does us no good as we want the user to be able to put their own text in the reminder.

**Comment by JRichmond27** [comment]
For what it's worth, I just ran into this issue on v15.4. I can confirm @stanalyst's results...

- The Note text field works properly
- The Note attribute results in a guid in the reminder note
- The Reminder Date text field results in no reminder at all
- The Reminder Date attribute results in a reminder with today's date
