### ISSUE TITLE
Launch Workflow Button on a Dynamic Data Block Not Pulling the People Selected

### ISSUE THREAD

**Issue by ChristineBema** [SparkDevNetwork/Rock#5778]
### Description

When using a dynamic data block that is a person report, when I select people in the grid and then select the "Launch Workflow" button, no people are being returned to launch a workflow on.

https://www.loom.com/share/cba0c5bf37ca4395afa598e4d1d374c8

### Actual Behavior

No one is ever selected when clicking the "launch workflow" button on a dynamic data block.

### Expected Behavior

I would expect that when people are selected on a dynamic data block and it is a person report, those people are selected to be able to launch a workflow on.

### Steps to Reproduce

-Go to Rock version 15.2. Add a dynamic data block. Use the code
```
SELECT TOP 50 p.Id
FROM Person p
```
-Turn on "Person Report" in the block setting
-Turn on "Launch Workflow" as an option
-Select a few people in the grid
-Click the "Launch Workflow" gear icon

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.2

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@ChristineBema Hi Christine I've been unable to recreate this issue on v15.2 and on the RockSolidChurchDemo v16.3. Please confirm if you are able to recreate this issue on the demo site.

**Comment by ChristineBema** [comment]
> @ChristineBema Hi Christine I've been unable to recreate this issue on v15.2 and on the RockSolidChurchDemo v16.3. Please confirm if you are able to recreate this issue on the demo site.

Hi Colleen, it wasn't working for me on the demo site either: https://www.loom.com/share/bfe7cd370f434769b91822384a6ebaf9
