### ISSUE TITLE
Group Registration Block Group Capacity Setting Issue

### ISSUE THREAD

**Issue by thejasonharvey** [SparkDevNetwork/Rock#5784]
### Description

When the "Prevent Group Overcapacity Registrations" setting on the Group Registration Block is set to "No" then upon saving the settings and refreshing the page the block will always state the group "is at or exceeds capacity" 

### Actual Behavior

When the "Prevent Group Overcapacity Registrations" setting on the Group Registration Block is set to "No" then upon saving the settings and refreshing the page the block will always state the group "is at or exceeds capacity."

It doesn't seem to matter if a group has a capacity rule of "none" or if there is a group capacity that is not met, it will always display that message and prevent the ability to register for the group. In order to get the message to go away the setting must be set to "blank" or "Yes".

### Expected Behavior

I would expect the message to only appear if a group has a capacity rule that prevents overcapacity and the group is at capacity - and the rule on the block is set to "Yes".

### Steps to Reproduce

- Go to https://rock.rocksolidchurchdemo.com/page/367?GroupGuid=10b60f8d-0f23-4faa-b35f-9a5f19f5f995# (or pick any group from the ones available - https://rock.rocksolidchurchdemo.com/page/236)
- Open the block settings for the Group Registration block
- Scroll down to the "Prevent Overcapacity Registrations" Setting, set it to "No," click save and refresh the page.
![image](https://github.com/SparkDevNetwork/Rock/assets/130079417/f38f44b1-0cfc-47a1-b4bf-5df0af1f33c4)
- See error
![image](https://github.com/SparkDevNetwork/Rock/assets/130079417/a2b7e9ac-2324-4196-8388-04da7467dea3)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.2, 16.3, 17.0

### Client Culture Setting

en-US

**Comment by zackdutra** [comment]
@thejasonharvey did you do anything to temporarily fix this? Put the web forms block back?

**Comment by thejasonharvey** [comment]
@zackdutra I don't think we enforce group capacities very often for our groups. So, I am not sure what happens if a group actually has a cap. However, what we did was change the setting to either "Yes" or "Blank" and it seemed to no longer be an issue. So, the workaround was pretty basic. It was just causing problems in all those places where we explicitly told the block setting to not enforce capacity limits.

**Comment by nlBayside** [comment]
@thejasonharvey Thanks for the suggestion. We also changed the block setting to "Yes" or "Blank" (defaults to true anyways), and that solved our problem.

Looks like the reason it works there is because it will default the OpenSpots property for `box` to 2 if you have the block setting checked; otherwise, OpenSpots initializes as 0 and fails the condition.

Thanks again for the response! We initially were going to put back the older WebForms block in the meantime, but this seems to have solved our issue temporarily while we wait for v16.4
