### ISSUE TITLE
Attendance: Check-in Configuration Streak Type Rebuild does not include all groups

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#5785]
### Description

When rebuilding a streak type that has a linked activity of "Attendance: Check-in Configuration" it only includes groups that have just one (or zero) areas (group types) in their parent hierarchy.

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/Engagement/StreakType/StreakTypeService.cs
![image](https://github.com/SparkDevNetwork/Rock/assets/548180/5f4e9b53-f523-46f7-a427-8a9b38ad64c3)

### Actual Behavior

When rebuilding a streak type that has a linked activity of "Attendance: Check-in Configuration" it only includes groups who have just one group type in their parent hierarchy.

For example, rebuilding this streak type:
![image](https://github.com/SparkDevNetwork/Rock/assets/548180/2407ccfe-ad08-4331-8cd8-cfd42a1c5992)

Only includes people from the last four groups in this screenshot:
![image](https://github.com/SparkDevNetwork/Rock/assets/548180/68a02b15-cf93-4753-b3e5-1bfae083b120)

It does not include people from the other groups, because those groups have more than one parent group type under the check-in configuration area.

### Expected Behavior

People from all the groups are included.

### Steps to Reproduce

- Create check-in config with groups that have more than one parent group type ("Area")
- Add attendance data for people in those groups
- Create a streak type based on the check-in config
- Rebuild the streak type with start date prior to the attendance
- Note that the streak does not include people who checked into groups with more than one parent area.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v15.3 

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@azturner Hi David - I've been unable to recreate this issue on v16.3. Please confirm if you are able to recreate this issue on the demo site.

**Comment by Luke-Potter** [comment]
@chead4 I just confirmed this on the rockrmsdemo.com site.
https://rockrmsdemo.com/people/streaks/type/2
https://rockrmsdemo.com/page/201?CheckinTypeId=1038

![image](https://github.com/SparkDevNetwork/Rock/assets/31108929/f59b8024-5769-4f31-ab49-df2ed2e84931)

I check in the Foster Family into the Parent 1 > Parent 2 ? Checkin Area! group, but they do not show up in the Streak.

I check in Alisha Admin into the One Level Deep > 1 Parent Group group & she appears in the Streak.

![image](https://github.com/SparkDevNetwork/Rock/assets/31108929/99350110-2ed3-4766-8ad5-4d07ecf357b8)

**Comment by chead4** [comment]
@Luke-Potter Thanks for jumping in and helping out to recreate this issue Luke.  I have added the label: Status: Confirmed as well as added your comments to our internal issue.
