### ISSUE TITLE
Connect Button doesn't show any activity or refresh on Connection Requests page

### ISSUE THREAD

**Issue by mattgeorgelc** [SparkDevNetwork/Rock#5787]
### Description

In a Connection Request full page:  https://rock.rocksolidchurchdemo.com/page/408?ConnectionRequestId=3&ConnectionOpportunityId=2

Hitting the Connect button doesn't indicate anything happening or the State changing to Connected.  When you manually refresh the browser, you can see that the State changes to Connected, but otherwise it appears nothing happened when clicking the button.  

### Actual Behavior

Clicking the Connect button from /page/408 doesn't show anything happening until you manually refresh the page. 
<img width="1034" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/158209049/504fc847-69b5-4558-a54d-5e244b3ef328">

### Expected Behavior

I expect the behavior to be the same as the modal that pops up from the connection opportunity page.  When clicking the Connect button, the page loading indicator appears, the state changes to Connected  and the Connected Activity is written.
https://rock.rocksolidchurchdemo.com/page/2635?ConnectionOpportunityId=3&ConnectionRequestId=1

<img width="876" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/158209049/e008b5d4-37c2-4f2d-b3b6-a3433d9ae99e">

### Steps to Reproduce

- Go to (https://rock.rocksolidchurchdemo.com/page/408?ConnectionRequestId=1&ConnectionOpportunityId=3)
- Click on 'Connect'
- Wait
- Refresh Browser

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.2

### Client Culture Setting

en-US

**Comment by marcierempel** [comment]
We noticed the same thing (running v15.3). But we were able to change the page that the block points to. The link from the person profile page points to page 408, but if you look at the Connections page itself, it's page 2635 on the Rock Demo site.
We tried changing the Connection Request Detail page it pointed to in the block settings - Connection Board - with the people/connections/board route, but it wouldn't save. We ended up changing the detail page on the Connection type itself and then setting the Connection Requests block config to use Connection Request Detail from Connection type (and set the correct route on the connection type. I do believe there is a bug with the connection detail block on page 408 though, but there is a work around until it gets fixed.

**Comment by kylehenning** [comment]
This appears to be a duplicate issue to #5762 and was fixed by [this commit](https://github.com/SparkDevNetwork/Rock/commit/651e3a73b7fc9d1609ba3667b278cccb0fadc79d). If you continue to experience this issue after upgrading to Rock Version 16.4 please feel free to reopen this issue.
