### ISSUE TITLE
Note watching notifications do not work unless first note type is configured for watching.

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#5790]
### Description

If a Notes block is configured to display multiple note types and the first note type available to be added is not configured for watching, but other note types are, the watching notifications will never be sent for replies to notes of those types. This is because when replying to a note, the reply note is saved with a NoteTypeId from the first note type that is available to the block and not the note type of the note that is being replied to. The reply is then ignored by the notification job because it's note type is not configured for watching.

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/a36b01ee-ce97-4d2a-891f-c42f5b422964)

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/e4e80bdc-9171-42e8-84bb-5124eb6c3854)

### Actual Behavior

The Send Note Notifications job does not send notifications for all replies (because replies are getting saved with incorrect note type).

### Expected Behavior

The replies get saved with correct note type so that the Send Note Notification job will find them and send the notifications.

### Steps to Reproduce

- Add an a new note type for Person entity that allows replies and watching. Make sure it it would be displayed after the default "Personal Note". i.e. call it "Special Note".
- Add a new note of that type to a person's profile, and select option to Watch the new note
- Login as someone else and reply to that new note on the profile
- Run the Send Note Notification job and notice that it does not send any notifications

- Notice to that the reply was saved with the "Personal Note" note type and not the "Special Note" note type.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.3, 16.2

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@azturner In your situation, when the reply is being created, are you seeing the available NoteTypes listed in the dropdown? Or are you saying they are there, but Rock is _automatically_ selecting the first one.

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/fb5b0465-2eff-430e-ab7f-4fdcfa5bc4f9)
