### ISSUE TITLE
[Alpha 1.16.4.1] Obsidian Persisted Dataset Detail interval unit only changes if quantity is changed too

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5795]
### Description

When editing the time unit (mins / hours / days) of a persisted dataset refresh interval, changing only the time unit does not save. If you change only the time unit and some other setting (like checking or unchecking an enabled lava command) the changes do save as expected.

### Actual Behavior

Changing _only_ the time unit of a refresh interval does not save to the database.

### Expected Behavior

I would expect to be able to change only the time unit of a persisted dataset and it save to the database.

### Steps to Reproduce

- On a Rock instance running v16.4 alpha (1.16.4.1), navigate to Admin Tools > CMS Configuration, then click on Persisted Datasets
- Click on any persisted dataset in the list (or create a dummy one if none exist)
- On the persisted dataset detail page, edit the Main page zone
- Click to add a new block, and add the Obsidian version of the **CMS** block Persisted Dataset Detail 
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/6a1e183a-e9c0-44ec-a9a0-8c96fc84a0f8">

- Delete the other block (or drag the Obsidian version to the top, either way, it doesn't matter)
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/6b2b970d-e5af-4eda-90b6-da5aa4b78ac0">

- Hit Done and refresh the page
- Hit the Edit button on the Obsidian block
- Scroll down and take note of the current interval (in this example, it is every 9 minutes)
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/b36e24c4-e618-4d10-afaf-25eafb55723d">

- Change **just** the Persistence Schedule time _unit_ (i.e. Mins, Hours, or Days) but not the quantity (in this example, I am changing from 9 minutes to 9 hours)
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/34f08880-8149-4d54-854c-634d74075ccf">

- Hit Save
- Refresh the page
- Note how the interval is still every 9 minutes
- If you edit again and change both the quantity and unit, it will save accordingly

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.4 (1.16.4.1)

### Client Culture Setting

en-US

**Comment by ryneld-tcc** [comment]
In testing this one still didn't work for me.

**Comment by chead4** [comment]
@ryneld-tcc Thanks for reaching out to us on this issue. I've tried to recreate this issue on v16.4 but am unable to do so.  When editing the Persistence Schedule Interval time unit from Hours to Days on the Persisted Dataset Detail Obsidian block, the correct Interval time unit was displayed upon refreshing the page.  Can you please let us know what version you are testing on?

**Comment by ryneld-tcc** [comment]
It was on the 16.4 beta, let me look again.
