### ISSUE TITLE
Group Scheduling SMS Confirmations Not Showing In Communication History

### ISSUE THREAD

**Issue by ns-brandonwilson** [SparkDevNetwork/Rock#5799]
### Description

When sending group scheduling confirmations with recipient preference, emails are displayed in communication history and SMS are not which makes it nearly impossible to see which confirmations "failed" as they aren't displayed in the success/failure notification.

### Actual Behavior

When sending group scheduling confirmations with recipient preference, emails are displayed in communication history and SMS are not.

### Expected Behavior

I would expect both email and SMS confirmations to be shown in communication history.

### Steps to Reproduce

- Go to group scheduler
- Select people to schedule
- Send confirmations with recipient preference to both email and sms users
- Communication history will only show the ones sent via email, not sms

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.17.0.11

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@ns-brandonwilson Hi Brandon, can you confirm if you have previously seen text messages for Group Scheduling confirmations displayed in the Communication History?

**Comment by ns-brandonwilson** [comment]
No I haven’t seen it before. It does seem logical that it should
considering the emails for Group Scheduling confirmations are displayed and
all other SMS communication inside of Rock is as well. I wasn’t sure if it
was a bug or an oversight, but I need a way for our ministry leaders to see
if they have failing communications who they are failing to.

Brandon Wilson
Digital Applications Specialist
NewSpring Support Center
NewSpring Church
www.newspring.cc
cell: (864)245-5386

**Comment by chead4** [comment]
@ns-brandonwilson After reviewing the issue, having Group Scheduling SMS confirmations display in Communication History is an enhancement.  I'd recommend submitting an idea for this on the Rock Community Ideas board via http://community.rockrms.com/ideas. This allows the full community to speak into it and help us determine it's priority.
Thank you for the detailed submission and for helping to make Rock better!

**Comment by jasonhendee** [comment]
@ns-brandonwilson, sorry to go back and forth on this, but we spent a bit more time investigating and have ultimately decided to treat this as an issue and provide a fix now. As of Rock v16.5, Group Scheduler SMS confirmations and reminders will be logged as Communication records.
