### ISSUE TITLE
Step "Summary" column always blank 

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#5800]
### Description

When viewing steps in grid mode on a person profile there is a "Summary" column, but this column is always blank. Steps have a "Note" field, but the note is not displayed on the grid. 

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/6fe7a179-f8e9-4fb7-9784-b17f05b84037)

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/cf65d9da-aacb-4df0-9108-02af3c0cc961)

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/4aed85b6-5386-4043-93f6-33247b1010f1)

### Actual Behavior

Summary column is always blank (reviewed code and it seems to just be hard coded to always be set to empty string)
https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Steps/PersonProgramStepList.ascx.cs#L1257

### Expected Behavior

Summary shows something, ideally the note from the step

### Steps to Reproduce

- Go to steps
- Add a step for a person, being sure to add a note to the step.
- Go to that person's profile and select the Steps tab
- Change the steps to grid view
- Note that the summary column is empty and the Note value for the step is not displayed.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v15.4 & v16.4 (demo site)

### Client Culture Setting

en-U

**Comment by nairdo** [comment]
HI @azturner   That Summary field is used to show the Step _attribute_ values such as this below.  If you are also seeing that behavior can you close this one out?

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/4fcf2e4e-a8b8-4ed7-8a81-1c38d2475e29)

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/1dcfd45d-c7ac-48c8-896b-b979a75680a3)

That happens here in the code: 
https://github.com/SparkDevNetwork/Rock/blob/bf47e3a0eba2f28869241088c46e1289e0d3e1c7/RockWeb/Blocks/Steps/PersonProgramStepList.ascx.cs#L393-L395

**Comment by nairdo** [comment]
>  If you are also seeing that behavior can you close this one out?

@azturner  We'll close this out for now, but please do let us know what you find on your system.
