### ISSUE TITLE
Communication Entry Wizard displaying "Move Block" Modal

### ISSUE THREAD

**Issue by MatthewKyle22** [SparkDevNetwork/Rock#5805]
### Description

![Screenshot 2024-03-26 at 1 35 13 PM](https://github.com/SparkDevNetwork/Rock/assets/11671126/7fecfff9-f588-48be-9c2f-6c7bbdefa282)

The attached modal is shown after clicking Next on the editor page and going to the final confirmation page, and then hitting the previous/back button to go back to the editor.

The only way I can get the modal to go away and to return back to a "normal" state is to click into the editor as if I was going to add words to the email.

### Actual Behavior

![Screenshot 2024-03-26 at 1 35 13 PM](https://github.com/SparkDevNetwork/Rock/assets/11671126/8510af4c-77ff-4d0c-a72d-e894fba5fe45)

A move block modal appears. The close and cancel button does not respond.
a new previous / next button appear full width at the bottom of the page.

### Expected Behavior

After clicking "Previous" on the confirm email page, I would expect to be returned to the editor page.

### Steps to Reproduce

- Go to https://rock.rocksolidchurchdemo.com/Communication
- Add Ted Decker via the manual list.
- Click Next
- Give the communication a name
- Enable Bulk
- Communication Medium: Email
- Click Next
- Select Blank Template
- Enter From Name, Email Subject, From address.
- Click Next
- Drag single column into editor.
- Drag Text block into the single column.
- Click the text field.
- Click code editor.
- Delete Content
- Paste the following:
`<!DOCTYPE html>

<html>
	<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
		<title>
		</title>
    <meta charset=utf-8>
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="Content-Type" content="text/html;">
	</head>

  <body class="">
    <title>Plain Template</title>
    <style>
      /* -------------------------------------
          GLOBAL RESETS
      ------------------------------------- */

      /*All the styling goes here*/

      img {
        border: none;
        -ms-interpolation-mode: bicubic;
        max-width: 100%;
      }

      body {
        background-color: #F1F1F1 !important;
        font-family: sans-serif;
        -webkit-font-smoothing: antialiased;
        font-size: 14px;
        line-height: 1.4;
        margin: 0;
        padding: 0;
        -ms-text-size-adjust: 100%;
        -webkit-text-size-adjust: 100%;
      }

      table {
        border-collapse: separate;
        mso-table-lspace: 0pt;
        mso-table-rspace: 0pt;
        width: 100%; }
        table td {
          font-family: 'Avenir Next', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
          font-size: 14px;
          vertical-align: top;
      }

      /* -------------------------------------
          BODY & CONTAINER
      ------------------------------------- */

      .body {
        background-color: #F1F1F1 !important;
        width: 100%;
      }

      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
      .container {
        display: block;
        margin: 0 auto !important;
        /* makes it centered */
        max-width: 580px;
        padding: 10px;
        width: 580px;
      }

      /* This should also be a block element, so that it will fill 100% of the .container */
      .content {
        box-sizing: border-box;
        display: block;
        margin: 0 auto;
        max-width: 580px;
        padding: 10px;
      }

      /* -------------------------------------
          HEADER, FOOTER, MAIN
      ------------------------------------- */
      .main {
        background: #F1F1F1 !important;
        border-radius: 3px;
        width: 100%;
      }

      .headerlogo{
        background: #F1F1F1 !important;
        border-radius: 3px;
        width: 100%;
      }

      .wrapper {
        background: #F1F1F1 !important;
        box-sizing: border-box;
        border-radius: 3px;
        padding: 20px 20px 10px 20px;
      }

      .content-block {
        padding-bottom: 10px;
        padding-top: 10px;
      }

      .footer {
        clear: both;
        margin-top: 10px;
        text-align: center;
        width: 100%;
      }
      .footer td,
      .footer p,
      .footer span,
      .footer a {
        color: #F1F1F1 !important;
        font-size: 12px;
        text-align: center;
      }

      /* -------------------------------------
          TYPOGRAPHY
      ------------------------------------- */
      h1 {
        color: #1d242b !important;
        font-family: 'Avenir Next', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
        font-weight: 800;
        line-height: 1.4;
        margin: 0;
        margin-bottom: 30px;
      }
	  	h2 {
        color: #1d242b !important;
        font-family: 'Avenir Next', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
        font-weight: 700;
        line-height: 1.3;
        margin: 0;
        margin-bottom: 25px;
      }
	  	h3 {
        color: #1d242b !important;
        font-family: 'Avenir Next', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
        font-weight: 600;
        line-height: 1.2;
        margin: 0;
        margin-bottom: 22px;
      }
		  h4 {
        color: #1d242b !important;
        font-family: 'Avenir Next', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
        font-weight: 500;
        font-size: 16px;
        line-height: 1.1;
        margin: 0;
        margin-bottom: 20px;
        margin-top: 20px;
      }
      h5 {
        color: #869098 !important;
        font-family: 'Avenir Next', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
        font-weight: 500;
        font-size: 14px;
        line-height: 1.1;
        margin: 0;
        margin-bottom: 20px;
      }
      p {
        text-decoration: none;
        color: black;
      }
        
      p,
      ul,
      ol {
        font-family: 'Avenir Next', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
        font-size: 14px;
        font-weight: normal;
        margin: 0;
        margin-bottom: 15px;
      }
      
      p li,
      ul li,
      ol li {
        list-style-position: inside;
        margin-left: 5px;
      }
      
      a {
        text-decoration: none;
        color: black;
        font-weight: 600;
      }

      /* -------------------------------------
          BUTTONS
      ------------------------------------- */
      .btn {
        box-sizing: border-box;
        width: 100%; }
        .btn > tbody > tr > td {
          padding-bottom: 15px; }
        .btn table {
          width: auto;
      }
        .btn table td {
          /* background-color: #F1F1F1 !important; */
          border-radius: 5px;
          text-align: center;
      }
      .btn a {
        background-color: #838282 !important; 
        border: solid 1px #F1F1F1 !important;
        border-radius: 5px;
        box-sizing: border-box;
        color: #F1F1F1 !important;
        cursor: pointer;
        display: inline-block;
        font-size: 14px;
        font-weight: bold;
        margin: 0;
        padding: 12px 25px;
        text-decoration: none;
        text-transform: capitalize;
      }

      .btn-primary {
        background-color: #838282 !important;
        border-radius: 30px;
        padding: 1.3em;
        text-decoration: none;
        border: 2px solid #838282;
        padding: 15px 40px 15px 40px;
        font-size: 16px;
      }

      .btn-primary table td {
        background-color: #F1F1F1 !important;
      }

      .btn-primary a {
        background-color: #838282 !important;
        border-color: #F1F1F1 !important;
        color:#F1F1F1;
      }

      /* -------------------------------------
          OTHER STYLES THAT MIGHT BE USEFUL
      ------------------------------------- */
      .last {
        margin-bottom: 0;
      }

      .first {
        margin-top: 0;
      }

      .align-center {
        text-align: center;
      }

      .align-right {
        text-align: right;
      }

      .align-left {
        text-align: left;
      }

      .clear {
        clear: both;
      }

      .mt0 {
        margin-top: 0;
      }

      .mb0 {
        margin-bottom: 0;
      }

      .preheader {
        color: transparent;
        display: none;
        height: 0;
        max-height: 0;
        max-width: 0;
        opacity: 0;
        overflow: hidden;
        mso-hide: all;
        visibility: hidden;
        width: 0;
      }

      .powered-by a {
        text-decoration: none;
      }

      hr {
        border: 0;
        border-bottom: 1px solid #F1F1F1 !important;
        margin: 20px 0;
      }

      /* -------------------------------------
            CUSTOM CLASSES
      ------------------------------------- */

    .app-header {
      margin-top: 25px;
      text-align: center;
    }

    .media-wrapper {
      width: 100%;
    }

    .media {
      text-align: center;
      padding: 0px 10px 0px 10px;
      margin: 0px 20px 0px 20px;
      width: 20px;
    }

    .footerAddress {
      font-weight: 400 !important;
      text-decoration: none !important;
    }

        /* -------------------------------------
         ACTION CLASSES
      ------------------------------------- */

    .actionItem {
      text-align:center;
      word-break: break-word;
      padding: 2px;
    }

    .actionItem div {
      border: solid 2px #CFCECE;
      border-radius: 10px;
      background-color: #e7e7e7;
    }

    .actionItem img {
      padding-top:20px;
    }

    .actionItem a {
      text-decoration: none;
    }

    .actionItem p {
      color: #AFAFAF;
      font-weight: 600;
      padding-top:3px;
    }

    .actionWrapper {
      color:#bdbdbd;
      font-family:Lora,Georgia,Times New Roman,serif;
      font-size: 12px;
      line-height: 15=0%;
      text-align:center;
      width: 100%;
      padding-top: 20px;
    }

      /* -------------------------------------
          RESPONSIVE AND MOBILE FRIENDLY STYLES
      ------------------------------------- */
      @media only screen and (max-width: 620px) {
        table[class=body] h1 {
          font-size: 28px !important;
          margin-bottom: 10px !important;
        }
        table[class=body] p,
        table[class=body] ul,
        table[class=body] ol,
        table[class=body] td,
        table[class=body] span,
        table[class=body] a {
          font-size: 16px;
        }
        table[class=body] .wrapper,
        table[class=body] .article {
          padding: 10px !important;
        }
        table[class=body] .content {
          padding: 0 !important;
        }
        table[class=body] .container {
          padding: 0 !important;
          width: 100% !important;
        }
        table[class=body] .main {
          border-left-width: 0 !important;
          border-radius: 0 !important;
          border-right-width: 0 !important;
        }
        table[class=body] .btn table {
          width: 100% !important;
        }
        table[class=body] .btn a {
          width: 100% !important;
        }
        table[class=body] .img-responsive {
          height: auto !important;
          max-width: 100% !important;
          width: auto !important;
        }
      }

      /* -------------------------------------
          PRESERVE THESE STYLES IN THE HEAD
      ------------------------------------- */
      @media all {
        .ExternalClass {
          width: 100%;
        }
        .ExternalClass,
        .ExternalClass p,
        .ExternalClass span,
        .ExternalClass font,
        .ExternalClass td,
        .ExternalClass div {
          line-height: 100%;
        }
        .apple-link a {
          color: inherit !important;
          font-family: inherit !important;
          font-size: inherit !important;
          font-weight: inherit !important;
          line-height: inherit !important;
          text-decoration: none !important;
        }
        #MessageViewBody a {
          color: inherit;
          text-decoration: none;
          font-size: inherit;
          font-family: inherit;
          font-weight: inherit;
          line-height: inherit;
        }          
      }
    </style>

    <span id="preheader-text" class="preheader">Crossings Community Church</span>
    <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
      <tbody>
	  	  <tr>
          <td>&nbsp;</td>
          <td class="container">
            <div class="content">
              
              <table role="presentation" class="main">
                
                <tbody>
                  <tr>
                    <td class="app-header">
                      <a href="https://crossings.church">
                        <img class= "crossingsLogo" align="center" src="https://crossingscommunitychurch.github.io/EmailAssets/ccc_vert.png" width="150">
                      </a>
                    </td>
                  </tr>
	  			        <tr>
                    <td class="wrapper">
                      <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                        <tbody>
	  					            <tr>
	  						            <td>
	  				                
	  				                  <div class="structure-dropzone">
	  				                  	<div class="dropzone">
                                  <div class="component component-image" data-state="component" data-image-filename="placeholder-600x338.png" data-image-width="" data-image-height="">
                                    <a href="https://crossings.church">
                                      <img src="https://images.crossings.church/Images/Email%20template%20images/email-template-header-image.png" style="width: 100%;" data-imgcsswidth="full" alt="">
                                    </a>
                                  </div>
	  						<table class="component component-text" data-state="component" style="border-collapse: collapse; border-spacing: 0px; display: table; padding: 0px; position: relative; text-align: left; vertical-align: top; width: 100%; background-color: rgba(0, 0, 0, 0);">
	  							<tbody>
	  								<tr>
	  									<td class="js-component-text-wrapper" style="padding-top: 20px;">
                                        {% raw %}
                                          <div class="component component-text" data-content="<h1>Email Title</h1>" data-state="component" style="margin-bottom: 25px;">
                                            <p style="text-align: left; color: #000000">
                                              Hi {{ Person.NickName }}, 
                                              <br>
                                              <br>
                                              Thank you for signing up to serve at the Good Friday Experience during Holy Week! See what you signed up for below:
                                              <br>
                                              <br>
                                                <span style="font-weight: bold;">Location:</span> OKC
                                              <br>
                                              <span style="font-weight: bold;">Chosen Role:</span> {{ GroupMember.GroupRole.Name }}
                                              <br>
                                              <span style="font-weight: bold;">Chosen Time/Times:</span> {{ GroupMember | Attribute:'Times' }}
                                              <br>
                                          </p>
                                          </div>
                                          {% endraw %}

	  								</td>
	  							</tr>
	  						</tbody>
	  					</table>
                                  
                                  
                                  <div class="component component-divider" data-state="component">
                                    <hr style="border: 0px; height: 2px; background-color: #CFCECE !important; margin-top: 40px; margin-bottom: 30px; background-position: initial initial; background-repeat: initial initial;">
                                  </div>
                                  
                                </div>
                              </div>
	  						            </td>
                          </tr>
                        </tbody>
	  			            </table>
                    </td>
                  </tr>
                  
                </tbody>
	  	        </table>
            </div>
          </td>
          <td>&nbsp;</td>
        </tr>
      </tbody>
    </table>
  </body>
</html>
`
- Click Next
- Click Previous
- You should then see the modal as shown in the screenshots above.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.2

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@MatthewKyle22 It would appear this problem is caused by the styles you're including in your email (and have been adjusted in a way that's harmful to Rock's operation).  Once a style has been changed, there's not much Rock can do about it.  This would require implementing a new feature to the block (such as hide preview, encapsulate styles differently, etc.).  We would request you submit this as a change request[^1] or idea on the https://community.rockrms.com/ideas-changes board.

[^1]: Subject to approval and possible design/feature adjustments.
