### ISSUE TITLE
Connection Board - List/Board view error

### ISSUE THREAD

**Issue by Heythere97** [SparkDevNetwork/Rock#5806]
### Description

When I switch between List and Board view I get Error 338.
![Screenshot 2024-03-26 at 3 34 39 PM](https://github.com/SparkDevNetwork/Rock/assets/165096332/61bc369a-3daa-4b99-8768-c5235d936c01)

### Actual Behavior

When I  switch between Board and List view 2 or 3 times an error occurs. After the error is displayed I can't switch views (List or Board) any longer. Instead, when I click the List/Board button the page flashes and I remain on the same view I was on when the error occurred. It does not matter if I start from the List View or the Board View.

Once the error is displayed I can't open any of the Connection Requests.  The only way to clear the error is to start from the People menu to return to the Connections.

I have replicated this error in various Connections types.

### Expected Behavior

I expect to be able to switch between List and Board view as needed without limits.

### Steps to Reproduce

- Open the Rock
- Log In
- Move your mouse to the left menu
- Hover on the Person Icon
- When the menu opens move your mouse left to the menu list
- Move your mouse down to " Connnections "
- Click on " Connections "
- Click on a Connection to open it
- Move your mouse to the right and click on List or Board (the opposite view of what you are currently on)
- When the page refreshes with the new view, click the button (List or Board) again.
- Continue until error appears. ( I only had to change the view 2 or 3 times.  I was always errored by the third click)
- See Error at the top of the page and you will not be able to open a connection request
![Screenshot 2024-03-26 at 3 57 23 PM](https://github.com/SparkDevNetwork/Rock/assets/165096332/18cce77e-251e-405a-b86d-eb7f8b3ef14b)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.4 (1.16.4.1)

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@Heythere97  Thank you for submitting your first issue and helping to make Rock better.  I wanted to mention that Rock is all about community. A key part of strengthening this bond is knowing who we're engaging with. Could I ask you to include your name and organization on your GitHub profile? It's a simple way to put faces to names, fostering a more connected and personal community atmosphere.

**Comment by Heythere97** [comment]
Yes, I will add that in :)

Heather Bautista
Data Specialist
Tel: 
480.726.8000
Fax: 480-569-2238
www.CornerstoneAZ.com
________________________________
