### ISSUE TITLE
System Phone Number Issues with Workflow Entry List

### ISSUE THREAD

**Issue by sfdts** [SparkDevNetwork/Rock#5809]
### Description

When using a field type on a Workflow of type `System Phone Number` and having it visible in the grid - it will cause an exception to bubble up on the Workflow Entries List when viewing even if there are no Workflows.

Attribute in a blank workflow (No actions, and just a default Start activity):
<img width="1166" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/105222994/e675ab18-8002-44da-a113-91cf8f61caf9">

When going to view Workflow Entries:
<img width="210" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/105222994/fb5d6034-67c6-4df6-ae23-7a5dc95db97e">

Exception:
<img width="541" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/105222994/5c6a8959-4073-481e-a7ed-b54b4516c542">

### Actual Behavior

When using a field type on a Workflow of type `System Phone Number` and having it visible in the grid - it will cause an exception to bubble up on the Workflow Entries List when viewing even if there are no Workflows of any status.

It renders fine when viewing the actual detail of a workflow, but not within the Grid view.

### Expected Behavior

No exception to happen. The `System Phone Number` field should be able to be visible within the grid view.

### Steps to Reproduce

- Navigate to Admin Tools > General Settings > Workflow Configuration
- Add a new Workflow
- Add an attribute that must have type `System Phone Number` and have the `Show in Grid` checked
- Try to view the workflows of this Workflow Type by clicking on `Manage Workflows` button

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.2

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@sfdts Hi Steven Thanks for reporting the issue. I was able to successfully recreate the issue in v15.4. However, I was unable to recreate on the demo site (v16.3). I will be closing this issue as it has been resolved.
