### ISSUE TITLE
Can not open a connection request in List view

### ISSUE THREAD

**Issue by Heythere97** [SparkDevNetwork/Rock#5813]
### Description

When I click on a connection request in List view I get Error 75.
![Screenshot 2024-03-28 at 4 05 06 PM](https://github.com/SparkDevNetwork/Rock/assets/165096332/0df33e90-9ef8-4a25-b3a6-1aac4b18f73c)

### Actual Behavior

I opened the connections page and clicked on list to get in List view. From List view when I click on a connection request I get an error and the connection request will not open. 

I have replicated this error in various Connection types.

I get the error when I start on List view. I also get the error when I start from Board view, switch to List view, and click on a connection request.

I do not get the error when I am in Board view.

### Expected Behavior

I expected the Connection Request to open bringing up more information and notes about the request.

### Steps to Reproduce

- Open the Rock
- Log In
- Move your mouse to the left menu
- Hover on the Person Icon
- When the menu opens move your mouse left to the menu list
- Move your mouse down to " Connnections "
- Click on " Connections "
- Click on a Connection to open it
- If currently in List view, click on a connection request
- If currently in Board view, click on List to move to List view.
- Click on a connection request
- See Error at the top of the page and you will not be able to open a connection request
![Screenshot 2024-03-28 at 4 24 42 PM](https://github.com/SparkDevNetwork/Rock/assets/165096332/731c643e-2623-464c-8e3f-16b363a294ae)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.4 (1.16.4.1)

### Client Culture Setting

en-US

**Comment by JimMichael** [comment]
I cannot reproduce this on **1.16.4.2** (alpha2)
