### ISSUE TITLE
System communication send test email

### ISSUE THREAD

**Issue by kevinkrugerCCV** [SparkDevNetwork/Rock#5814]
### Description

While using a system communication, if you use the "Send test" feature, the user selected will have their email changed to the email address used for the test and after the test is sent, the email does not change back as designed. 

### Actual Behavior

Testing a system communication requires you to select a target person but after selecting the "Send Test" and input a different email.  Rock will update the target persons email to be the test email address.  
<img width="1218" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/91297818/251c6ac3-9f5b-4a0b-bbad-604dae85b9f1">

### Expected Behavior

After sending the test email, I would expect the target persons email to be reverted back to the appropriate address.

### Steps to Reproduce

- Go to "admin tools" menu 
- Click on "Communications"
- Select "System Communications" 
- Select the "Preview" option on one of the system communications. 
<img width="1326" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/91297818/e9da0bae-e02e-4d82-b95a-5af651511083">
- Select the "Send Test" on the right side of the communication. 
<img width="1308" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/91297818/46c26d93-9845-4a1c-b3e4-37ccdc2cfb21">
- Use a different email than the one used for the target person
- Visit target persons profile page to see email changed to that used for the test. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

14.2

### Client Culture Setting

en-US

**Comment by JimMichael** [comment]
I cannot duplicate this on 1.16.2 through prealpha.

**Comment by JimMichael** [comment]
Ah, the original steps didn’t specify you had to *change* the target person (it defaults to yourself) and just change the email of the  (defaulted) target person (which works fine for me and doesn’t change the person’s actual email on the profile), so that must be the key.
