### ISSUE TITLE
Group Member Requirement Override: Allow Leaders to Override not functioning.

### ISSUE THREAD

**Issue by nharmonCOTH** [SparkDevNetwork/Rock#5825]
### Description

When attempting to Override a group requirement as a leader or as a person in a role that is allowed to override the requirement, it does not allow the requirement to be overridden. This prevents a person from being added in a role that has group requirements when needing to override the requirement. This was tested in v15.3, v16.2, and v17.0.16. v17.0.16 has a slightly different result explained in the steps to reproduce.
![msedge_SvssV3lHpq](https://github.com/SparkDevNetwork/Rock/assets/166412588/61f4f8de-06b5-4dc8-a09a-e8df1e75cb85)

### Actual Behavior

Leaders or security groups assigned to be able to override are unable to override Group Requirements.

### Expected Behavior

Leaders would be able to override Group Requirements for Group Members.

### Steps to Reproduce

1. Have a Group Requirement Type (Demo: Background Check Required)
2. Assign a security role to the override permissions. (RSR - Rock Administration)
3. Assign the Requirement Type to a Group Type making sure to set "Allow Leaders to Override", "Members must meet this requirement before adding", and assign it to a Role (Leader).
4. Add a person (person must not meet the requirement) to a group (to a Group Type that has the Group Requirement assigned) in a Role that does not have the Group Requirement assigned.
5. Change the Group Member from the current Role to the Role that has the group requirement.
6. You will see that the requirement is not met. It also does not have the option to "Mark as Met"
7. Upon trying to save there is an error presented at the top of the screen. "Cindy Decker must meet the following requirements before being added or made an active member in group 'Greeters': Background Check Required"
8. The Mark as Met is now visible.
9. Click the "Mark as Met", you will be prompted to confirm, then the page will reload and revert the role back to Member and not setting the requirement as met.
10. Changing the Role back to Leader will repeat the same process.
11. We are unable to Override the requirement.

In v17.0.16 after step 5.
When changing a member from a role to another role that has group requirements that are not met, it immediately allows an override without hitting save.
Upon clicking the "Mark as Met" it refreshes the page and reverts the role back to the original.
Upon re-selecting the new role, the requirement is met, but you are still presented with the "Please correct the following:" alert and it will not allow you to save.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.3

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@nharmonCOTH Thank you for submitting your first issue and providing all the details necessary to recreate it.  
I wanted to mention that Rock is all about community and a key part of strengthening this bond is knowing who we're engaging with. Could I ask you to include your name, organization, and a photo on your GitHub profile? It's a simple way to put faces to names, fostering a more connected and personal community atmosphere.
