### ISSUE TITLE
The Communication Simple Editor sends email to removed recipients

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#5829]
### Description

If you copy a previous communication that was sent to a communication list and then click the "Use Simple Editor" so that you can remove specific recipients from the communication, when you send that email, it still sends to the entire communication list.

### Actual Behavior

Email is sent to all recipients in the communication list even though the UI of the simple editor lets you remove recipients

### Expected Behavior

When editing a copied communication using the simple editor, and you add or remove recipients, it should only send to the recipients that remained in the list of recipients.

### Steps to Reproduce

- Go to New Communication
- Select option to send to a communication list
- Send the email
- View the communication (in Rock) that was just sent
- Copy the communication
- Click the 'Use Simple Editor'
- Remove one or more recipients from the list
- Send a new email.

The recipients that you removed will still receive the email.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.3

### Client Culture Setting

en-US

**Comment by JimMichael** [comment]
I can confirm seeing this behavior.
