### ISSUE TITLE
Obsidian Registration Allowing Transactions After Reaching Maximum Attendees

### ISSUE THREAD

**Issue by SkellyRen** [SparkDevNetwork/Rock#5831]
### Description

Hillside Christian Church reached out to us this week and reported that they had a waitlisted camp registration pay the downpayment even though they had been waitlisting registrations for a couple of days at that point.  I found that the Obsidian Registration Entry block will allow a transactions to happen without after reaching the Maximum Attendees if the registration was already in process in an open browser window.

### Actual Behavior

If a registration is in process after hitting the maximum amount of attendees (both with and without a timeout length) it will display the Payment Summary allowing for a payment transaction to be ran.  With testing I have discovered that this will happen with or without a waitlist enabled.

Here is a screen shot of the registrations showing two waitlisted registrations having a negative balance because they were able to make a transaction during their registration:

![image](https://github.com/SparkDevNetwork/Rock/assets/48486355/f8cbb55b-4a5e-4cbc-8e22-67e3533a648c)

### Expected Behavior

When the registration instance hits the maximum attendees with a waitlist the registrar should be presented with the Payment Summary page displaying that they will be added to the waitlist with $0.00 cost if a waitlist is enabled or displaying that the event is full if the registration does not have a waitlist enabled.

![image](https://github.com/SparkDevNetwork/Rock/assets/48486355/284f9cb5-5b85-4e9d-96cc-342f082c090a)

### Steps to Reproduce

- Create a Registration Instance with a maximum amount of attendees set.
- Have a Registration in process to test after hitting the maximum attendees amount and finish the registration.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.4

### Client Culture Setting

en-US

**Comment by mcnoodles** [comment]
Thanks @SkellyRen

**Comment by jdwrhodes** [comment]
We are also experiencing this issue on our system. We are on v16.4 and the en-US Culture Setting.
