### ISSUE TITLE
16.4 Default Contribution Statement Lava Causes Exception

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5833]
### Description

Something is broken in the **default** contribution statement Lava specifically in v16.4 and causes an exception when you try to generate a contribution statement via the public site as well as the Contributions tab on a person Profile. I did not test the statement generator app.

### Actual Behavior

Upgrading to v16.4 breaks contribution statements IF you are running the default Lava shipped with Rock and haven't modified it. The actual exception is:
_Lava Error: Object reference not set to an instance of an object._ (shown on the page)

and internally the exception is a Lava render error:

![image](https://github.com/SparkDevNetwork/Rock/assets/3903408/c961b2cb-e29d-4568-a2af-16514ff9bf65)

### Expected Behavior

Contribution Statements in 16.4 would generate without error

### Steps to Reproduce

1. I went to https://rock.rocksolidchurchdemo.com and added a new transaction for Alisha Admin

2. I observed that the server was at v16.2, and ran a contribution statement from External Site | Giving | Giving History without issue.

3. I upgraded the server to v16.3 and ran a contribution statement again without issue

4. I upgraded the server to v16.4 and ran a contribution statement, which blew up with the above exception.

This implies that something in the Rock Default contribution statement lava is faulty. I'm betting it has something to do with this fix in the 16.4 release notes:

_Fixed an issue where a financial statement's Pledge Percent Completed would try to divide by zero. Fixes: #5721_ 

There is also a thread in chat where a user had this exception after upgrading to 16.4 https://chat.rockrms.com/channel/general?msg=ZGzAZ3jQW7PS36pwC

In that case, copying the Rock Default contribution statement Lava from prealpha.rocksolidchurchdemo.com to his own instance fixed the problem... so whatever is wrong in 16.4 is ONLY in 16.4 and not v17 (yet.)

I believe this was missed in 16.4 alpha testing because most orgs have modified the default template in some way, or are already using their own, thus we didn't see the problem with the buggy 16.4 default template.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.4

### Client Culture Setting

en-US

**Comment by rutledgek** [comment]
I can confirm on 16.4 with a modified version of the base template.

**Comment by rutledgek** [comment]
So a quick fix in the template is to find any | Sum lava and wrap it an if statement to make sure that the item being summed has any items.

In my case, it was wrap the pledge sum with a check to make sure that pledge count is > 0


`{% if pledgeCount > 0 %}
        {% assign pledgeTotal = Pledges | Select:'AmountPledged' | Sum %}
    {% else  %}
            {% assign pledgeTotal = 0 %}
    {% endif %}`
