### ISSUE TITLE
Public Profile Block Showing Campuses of all statuses/types

### ISSUE THREAD

**Issue by atamburino** [SparkDevNetwork/Rock#5837]
### Description

The public profile block on Rock currently displays all campuses, including those of varying statuses/types such as 'pending' or 'online', without any filtering options. This unrestricted display permits users to associate with any campus type when registering or updating their profiles. This poses several operational challenges:

Attendees registering with campuses labeled as 'pending' may not be automatically assigned default connectors, complicating the follow-up process for staff providing a barrier to connect with the attender.

Attempting to remove 'pending' or 'online' campuses from visibility by closing them introduces further issues. These closed campuses continue to impact other administrative functions, such as accounting, due to their lingering presence in system records.

### Actual Behavior

The profile block, both during account creation and information updates, displays all types of campuses, including online ones, and pending ones without any filters.
Users can select any campus, normally campuses can be hidden in many other processes in Rock.

### Expected Behavior

Pending campus would be hidden and Campus types would be able to be filtered on in the block settings like many other blocks with Campus. 

### Steps to Reproduce

1. Navigate to the Rock Solid Church demo site at Rock Demo.
2. Ensure the Campus Selector is enabled in your profile settings.
3. Create a new campus and designate it as an 'online' type that is open. / Can also create a pending campus that is open.
4. Update [your profile](https://rock.rocksolidchurchdemo.com/MyAccount) and observe that the newly created online campus is available in the dropdown menu.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock Version: 15.2 / 16.3

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@atamburino Hi Andrew - After reviewing this issue, we've determined that allowing filtering of campuses on the Public Profile block is an enhancement.  We appreciate your suggestion and agree with you that other blocks within Rock have block settings that allow for filtering on Campus Types. Therefore, we will be moving forward and implementing this enhancement.  

For any future enhancement requests, we encourage you to submit a request/idea on the [Ideas & Core Changes](https://community.rockrms.com/ideas-changes) page. Thanks for helping to make Rock better!

**Comment by KCKurz** [comment]
We know this has been closed, but wanted to add additional information. 

We noticed this same issue on a couple of blocks back in March and because we thought it was related to the actual Campus List block we didn't write down each place we saw it. 

We were going to submit a bug showing what we were seeing in the Account Entry block but saw this was created, it seemed to be the same issue.  Now that we have circled back around to see what was determined, we wanted to give a little more detail for your review. 

Please see the attached document for screenshots of the Account Entry Block in the demo site. 

Thank you!
[Account Entry Block and Active Campus Behavior.pdf](https://github.com/SparkDevNetwork/Rock/files/15490073/Account.Entry.Block.and.Active.Campus.Behavior.pdf)

**Comment by chead4** [comment]
@KCKurz Thanks for the comment and the detailed information in the pdf.  I am happy to share that the Obsidian Account Entry block settings will have new filters for Campus Types and Campus Statuses added in v16.6 which will allow you to filter which campuses display in the Campus Selector.  The new filters are available now on the pre-alpha site if you would like to check them out.  
![image](https://github.com/SparkDevNetwork/Rock/assets/134172019/8d2ee150-1c21-46db-92be-b8a217289c07)
