### ISSUE TITLE
Transaction Count and Batch Id are missing on Obsidian Financial Batch List 

### ISSUE THREAD

**Issue by Senaloraine** [SparkDevNetwork/Rock#5841]
### Description

The Obsidian Financial Batch List block is missing the Transaction Count and the Batch Id columns that were on the previous
block.
![image (11)](https://github.com/SparkDevNetwork/Rock/assets/29980525/dc02b0cd-8b2c-44d6-8398-bce2801ab3fc)

### Actual Behavior

In 16.3 some key columns are missing that help our finance team: Batch id and Transaction Count
![image (12)](https://github.com/SparkDevNetwork/Rock/assets/29980525/2c1082fe-9c88-4965-819b-45d76f0ffbf5)

### Expected Behavior

Batch Id and Transaction count should be in core block. (We added both Batch Id and Transaction Count as custom columns in advanced settings, but this was detrimental to performance, specifically Transaction count. which caused major CPU spikes when page was loaded.)

### Steps to Reproduce

View Batch list.
Note there are no columns for Batch Id or Transaction Count.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.16.3.5

### Client Culture Setting

en-US

**Comment by JimMichael** [comment]
Confirmed and agree this should be added to new block
