### ISSUE TITLE
Transaction matching no longer goes to next transaction when pressing enter

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#5842]
### Description

In v16.3 and prior, when using the "Transaction Matching" block, and you hit the "enter" key it progresses to the next transaction. 

### Actual Behavior

In v16.4 it no longer goes to the next transaction upon hitting enter. You must scroll down to the bottom of the page and hit the "Next' button

### Expected Behavior

In v16.4 it should allow you to go to the next transaction by hitting "enter"

### Steps to Reproduce

1. Go to the transaction matching block
2. Pull up a batch that has 2 or more transactions
3. Hit the enter key on a transaction
4. It will stay on the same transaction 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.4

### Client Culture Setting

en-US

**Comment by timlem** [comment]
We are experiencing this issue as well.

**Comment by tp-code** [comment]
Ditto. We are no longer able to move to the next item by pressing enter after upgrading to v16. We upgraded from v15.4 all the way to v16.4 recently. When we were on 15.4, pressing Enter worked fine.
