### ISSUE TITLE
Family Analytics Job not Properly Calculating eRA in Specific Scenario

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5845]
### Description

In regards to eRA calculation, the Family Analytics job is not correctly handling the following scenario:

1. A student attends and gets checked in every week. The Group (Group Type) they are checked into has the "Weekend Service" option selected, so their attendance record will count towards eRA. This students RecordStatus is set to _Active_.
2. The students parent does not attend - they only drop the student off. Therefore, the parents RecordStatus is set to _Inactive_.

The problem occurs when the Family Analytics job runs. When it runs, it calculates that the student is _not_ an eRA, when in fact they are. So, every time the job runs, it will create 2 rows in the Person's History, like this:

![Screenshot 2024-04-17 at 11 53 43](https://github.com/SparkDevNetwork/Rock/assets/23226974/296c9a04-09cb-4b63-aa7e-04dcfbb43d25)

Not only is it creating these 2 rows, as you can tell it is also updating the persons `eRAStartDate` Attribute to the current date. It will update this attribute every day the job runs - so we don't actually know when the person became an eRA.

The [spCrm_FamilyAnalyticsEraDataset.sql](https://github.com/SparkDevNetwork/Rock/blob/780d3cd6fe32a15766c38988ba18703d10f06624/database/Procedures/spCrm_FamilyAnalyticsEraDataset.sql#L16) stored procedure is returning `Is Era` as False. Running a portion of that SQL returned the following results:
![Screenshot 2024-04-17 at 11 59 42](https://github.com/SparkDevNetwork/Rock/assets/23226974/acc28fa2-cbb5-4867-a627-c5c45f829b41)

I was not able to dive super deep into that procedure, however I believe the issue is that the procedure is looking for an Adult at line 205 - `AND gm.[GroupRoleId] = @AdultRoleId`, and because the Adult is inactive and not an eRA, it is returning False. I could be wrong - again I did not dive deep enough into it.

If you get to it before the demo site refreshes, then you can see I replicated and did all my testing with Bill and Alisha Marble [here](https://rockrmslatest.com/Person/16/history) (I made Alisha a child).

### Actual Behavior

Children who are an eRA and active, with an Adult (Parent) who are not an eRA and are inactive are not being handled properly by the Family Analytics job.

### Expected Behavior

Children who are an eRA and active with an Adult (Parent) who are not an eRA and are inactive should not have their eRA status and eRA Start Date updated every time the Family Analytics job runs.

### Steps to Reproduce

- Start with a family with 1 Adult and 1 Child. Make the Adult inactive.
- Add some attendance records (at least 8) for the child. This must be done in a Group with a Group Type that has the Weekend Service option selected.
- Run the Family Analytics job. 
- Go to the child's profile and ensure they were made an eRA. You can go to their history tab and see that 2 records were created that look similar to this:
![Screenshot 2024-04-17 at 12 06 44](https://github.com/SparkDevNetwork/Rock/assets/23226974/350725f9-5252-4300-8471-6e2639ae215a)
- Verify that the Adult is _not_ an eRA and that their eRA Start Date attribute is blank.
- Go to the child's Extended Attributes and change their eRA Start Date to be yesterday's date.
- Run the Family Analytics job again.
- Back on the child's history, see that there are 2 new rows in their history. 
![Screenshot 2024-04-17 at 12 08 06](https://github.com/SparkDevNetwork/Rock/assets/23226974/077f654b-5a2b-48cd-bc8d-70cfb2848850)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.4, v17.0

### Client Culture Setting

en-US

**Comment by mikedotmundy** [comment]
This is only partially fixed in my Alpha testing (1.16.6.2).

The issue is that the _eRA Entry_ Workflow still launched for this family when the Family Analytics Job ran.

The person's eRA start date did _not_ update to the date the job ran, nor were there any rows created in the person's history. **_This is correct._**

**Comment by nairdo** [comment]
Also fixed in v16.7 via https://github.com/SparkDevNetwork/Rock/commit/a89174bba775f686a51ddf854c671992603ab65e
