### ISSUE TITLE
Event Registration Waitlist Members do Not Show in Waitlist tab if Group Member Attributes are shown in grid

### ISSUE THREAD

**Issue by KarenRossi84** [SparkDevNetwork/Rock#5851]
### Description

Registrations are not displaying those on the waitlist to move them when you have a group member attribute on the template set to show on grid.

### Actual Behavior

If you have a group member attribute set up on a registration template and the show on grid option selected for that attribute as shown below and you have someone on the waitlist, the waitlist tab that allows you move registrants will not display any people.
![Screenshot (926)](https://github.com/SparkDevNetwork/Rock/assets/104036471/f26d9ee0-c65e-43e8-a4ba-81d02a33095a)

![Screenshot (924)](https://github.com/SparkDevNetwork/Rock/assets/104036471/9365c770-4bf7-4d64-a015-6a16f3c47c3b)

![Screenshot (925)](https://github.com/SparkDevNetwork/Rock/assets/104036471/3f1e9250-3052-4dbb-abb5-03fda00f7dca)

If you manually register someone and select the target group in the registrar box, this behavior does not happen.

### Expected Behavior

All people on the waitlist would display in the grid on the waitlist tab of event registration no matter what fields are used and how they are displayed. This is how versions up to 14.2 worked. Was not able to test if this happens on v15.

### Steps to Reproduce

- Create a registration template with Group Member Attributes and have them show on grid.
- Create a new instance and link it to a group using a calendar
- Register enough people to get someone on the waitlist through the calendar page.
- Go to that registration template and click waitlist tab
- Observe no one shows on the list even though at least one of the registrants has the WL icon and should be.

- To make the people appear do one of two things: go to the group member attribute in the template and uncheck the show on grid box OR go to that person's registration details page and click the add to target group link next to the registrant name.
![Screenshot (927)](https://github.com/SparkDevNetwork/Rock/assets/104036471/e8340481-79a6-4727-b25e-126a36e1538e)
    
 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.2, 16.5 Alpha

### Client Culture Setting

en-us

**Comment by KarenRossi84** [comment]
I am alpha testing 16.6 and unfortunately I am still seeing this behavior.

**Comment by chead4** [comment]
@KarenRossi84 Hi Karen - Thanks for letting us know. Unfortunately, I'm not able to recreate on v16.6.  Could you please provide more details with screenshots so that we can investigate further?

**Comment by sparkdevnetwork-service** [comment]
@KarenRossi84 We are reopening this issue and will continue our investigation.  Thank you for allowing us to gather details for your event registration on your test instance.

**Comment by nairdo** [comment]
@KarenRossi84  Thank you for the access/screenshots you provided us with (offline) which showed all the various registration and group member attributes that were involved in this bug.  Using that information we were able to find a _partial_ solution that is going into v16.6 which will further mitigate that bug. (_We also confirmed it does resolve your waitlist registration example in your test system._)   

We are going to keep this issue open while we continue to work out a more complete solution in v16.7 (or possibly v17; depending).

**Comment by shivambareria** [comment]
Fixed by  https://github.com/SparkDevNetwork/Rock/commit/a745f47fef3efb64d4dfe0882579f42a0a4e323a
