### ISSUE TITLE
Registrations Are Updating Registrant's Account Email to Match Registrar’s Email

### ISSUE THREAD

**Issue by strider1212** [SparkDevNetwork/Rock#5853]
### Description

When a Registrar fills out a Registration for a Registrant that is not themself, the Registrant's profile email address is getting updated to whatever email the Registrar entered on the "Prompt for Registrar" block.

### Actual Behavior

When the Registration is submitted, the Registrant’s email address will be whatever was submitted as the Registrar’s email on that last page.

This happens whether or not the Registrar already has an email on their profile. If they have an email already, their email will be replaced by the Registrant email.

If, on the final prompt, you enter an email that is different from the Registrar’s current email, it will update both the Registrar and Registrant emails to the new email. 

We tried removing any Workflows from the Registration and the behavior persists. 

We were able to reproduce this behavior in Rock Solid Demo on v.16.

The behavior did not reproduce in Obsidian.

### Expected Behavior

We would expect that whatever is enter in that Registrar prompt should not affect anything on the Registrar’s profile. It should be restricted to Registrar information. 

### Steps to Reproduce

To reproduce this bug, submit a Registration where the Registrant is different from the Registrar and they are marked as being in the same family.

On the Registration Template, go to Edit -> Details -> Registrar Options, select “Prompt for Registrar”.

On the final Prompt for Registrar screen, fill in the email for the Registrar. 

Before submitting, note the email on the Registrant’s profile. 

Submit.

Observe the Registrant’s profile email.

### Issue Confirmation

- [x] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

13.8

### Client Culture Setting

en_US

**Comment by JimMichael** [comment]
Can we get more detail on how this was confirmed? The fact that it WAS confirmed implies that it affects versions beyond 13.8, but we can't reproduce it in 16.2 or 16.5alpha, here. 

On the other hand, if it IS an issue with only 13.8, why is it being addressed at all as that version is only getting security updates at this point?

**Comment by chead4** [comment]
@JimMichael Hi Jim - Thanks for asking, I'd be happy to share how I recreated the issue. Let me know if you have any questions after reviewing.

I documented my steps to recreate the issue below and I also recreated on the demo site (v16.5) just now on the Registration Entry webform.  (Noah Decker is now updated with Ted Decker's email address.) If you would like to try it out you can use the Spring Break event registration on the demo site.

**Steps to Recreate:**
1. Create an event registration with: 
 Registrants In Same Family - Ask
 Registrar Options: Prompt for Registrar
2. Ted Decker is logged in and registers Alexis Decker for the event. 
3. On the Review Registration block, Ted enters in a different email address in the 'Send Confirmation Emails To' field and deselects 'Should Your Account Be Updated To Use This Email Address?'. 
4. Complete the event registration.
5. Go to Alexis' profile and notice that her email address is updated to Ted's email address.

**Comment by zackdutra** [comment]
@chead4 could you confirm if you've seen this behavior in obsidian or not? The original post said no, so just confirming that you did your testing in webforms.

**Comment by chead4** [comment]
@zackdutra Hi Zack  When I recreated the issue I tested on both the Event Registration webform and obsidian block.  I was only able to recreate on the webform block.  

I have also tested the fix in v16.6 on both blocks.

**Comment by zackdutra** [comment]
Thank you @chead4!
