### ISSUE TITLE
Dragging Connection Request to Status (with Auto-Inactive) Is Extremely Slow

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#5854]
### Description

Submitted on behalf of Fairhaven Church

For some users when viewing connection requests in the board view and then dragging a request to the final status (the status that is configured to auto-inactivate requests), it is extremely slow (takes about 35 secs). However for some other users it doesn't take any time at all. Here's a video from Fairhaven showing this:
https://vimeo.com/877193348/b376c62728?share=copy

We determined that it was completely dependent on whether the user had selected to sort the connection requests. Those users who were sorting by Date Added (newest first) did not see any issues and moving the requests did not take any time. Those users who did not have any sort selected were the ones where it took a LONG time to drag a request to that status. Once users realized that they can just sort the requests, this isn't really an issue any more, but without knowing that, it was very frustrating for them.

This does seem to only affect connection requests configured with a status that has the auto-inactive flag enables.

### Actual Behavior

Dragging connection request from any status to the 'completed' status (the status configured to auto-inactivate) is extremely slow

### Expected Behavior

Should not be slow

### Steps to Reproduce

Reproducing this would require hundreds of connection requests for one opportunity type. But if you have that, configure one of the status to auto-inactivate. Then view this opportunity in the board view and remove any sorting. Then drag requests from any other status to the status configured for auto-inactivate.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.4

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@azturner HI David - I have been working on trying to recreate this performance issue.  Can you check and let me know if Fairhaven Church has Enable Request Security selected on the Connection Type Detail block?
![image](https://github.com/SparkDevNetwork/Rock/assets/134172019/9465be31-d4c8-43fe-8585-25b1d3349b27)

**Comment by azturner** [comment]
@chead4 , They do not have that option selected on the type where they were experiencing this issue.

**Comment by chead4** [comment]
@azturner HI David Thanks for getting back to me on my previous comment.  Can you also check the Connection Type Detail block/Statuses and let me know if there any automations set up for any of the statuses?  If there is an automation set up for a Data View, let me know the Time to Run for the data view.  
-Thanks

**Comment by azturner** [comment]
@chead4 , They do not have any status automations configured. Here's a screenshot of their connection type and opportunity type configurations too:

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/260f42d9-d552-4de4-97d0-22eb753f2f92)

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/574e8ad9-388a-44c6-8fd7-b427ec40c6fe)

As of today, they have 10,301 connection requests under this connection type::

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/af92c42e-8cee-4ec9-99f2-349d61b1a865)

**Comment by azturner** [comment]
@chead4 , and in case you need to see another video of the sort affecting how long it takes to move a connection request. In this example, the difference was only about 5 secs, but their staff often see much longer wait times when a sort is not selected:

[Video](https://9emberscom.sharepoint.com/sites/9Embers/_layouts/15/stream.aspx?id=%2Fsites%2F9Embers%2FShared%20Documents%2FPublic%20Shares%2FSlowConnectionRequest%2Emp4&ga=1&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E4174b1fb%2D42c0%2D45a3%2Dae0c%2Dda87631869fe)

**Comment by chead4** [comment]
@azturner Hi David - I wanted to provide an update, unfortunately, I have been unsuccessful in recreating the Connection performance issue in the v15.4 environment on Time Machine.  

I set up the following on the v15.4 environment:
1. Connection Type has Auto Inactivate State selected for the Completed Status
2. For the Children's Connection Opportunity, I have added 18,269 connection requests within the 3 statuses.  

![image](https://github.com/SparkDevNetwork/Rock/assets/134172019/62306c99-4e3b-45b1-90b7-a7cc41badaf3)

When trying to recreate, I logged in as Admin and Ted Decker (on Chrome and Edge browsers) and when moving a connection request from/to different status columns the loading icon displays between 2-5 seconds.

Can you provide information on the Fairhaven Church hosting environment?  A screenshot of the Diagnostics tab on the System Information block would be appreciated.
