### ISSUE TITLE
Transaction Entry v2 Allows Negative Values

### ISSUE THREAD

**Issue by morganw93** [SparkDevNetwork/Rock#5856]
### Description

When you give a gift in the transaction entry v2 block you can enter a negative value in the dollar amount fields. While gateways can declne negative amounts, if a church has multiple accounts and someone enters 100 in the first field and then tabs down and hits the down arrow, it will allow a negative value to process in that secondary field.

Was able to duplicate on demo site and on a Rock instance with v16.4 and v15.

### Actual Behavior

put your cursor in the dollar amoutn and hit the down arrow, it will go negative. You can also type in a negative value and it will allow it: 
![Screenshot 2024-04-30 at 3 52 28 PM](https://github.com/SparkDevNetwork/Rock/assets/30188136/9438f61b-b5a9-4519-b417-592d17dd7a85)
![Screenshot 2024-04-30 at 3 52 32 PM](https://github.com/SparkDevNetwork/Rock/assets/30188136/d6322800-4106-486d-902e-f049072f6184)

This is fine if there is only one account and the gateway declines negative transactions, but when there are multiple accounts it results in a transaction like this: 
![ben gift](https://github.com/SparkDevNetwork/Rock/assets/30188136/c7637685-38b9-458d-a08b-9f1e6af5d70d)

### Expected Behavior

You cannot enter a negative value for a gift. 

### Steps to Reproduce

- Go to a page with the transaction entry v2 block.
-put your cursor in the dollar amount field.
-use your mouse to mouse down or enter -0.01

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.4

### Client Culture Setting

en-US

**Comment by FrankGrand** [comment]
I think the root cause is that the mouse shouldn't be able to increment or decrement the amount field.  I see this happening in Chrome by accident and it causes major confusion if someone is just scrolling down the page to click 'submit' but accidently moves the mouse into the field while scrolling.

**Comment by chead4** [comment]
@FrankGrand  & @dataCollegechurch Thank you both for the additional comments, I will add them to our internal ticket for our development team.
