### ISSUE TITLE
Leading/Trailing Whitespace Prevents SMS Keyword Matching

### ISSUE THREAD

**Issue by tikool17** [SparkDevNetwork/Rock#5857]
### Description

When users text keywords, their messaging apps often add leading or trailing spaces. For example when typing the keyword "Outreach" it may be sent as "**Outreach** " or " **Outreach**".

![IMG_3404](https://github.com/SparkDevNetwork/Rock/assets/32227063/da9b2d51-a6a1-4684-898d-9e4db6158dfa)

When using an "Equal to" message filter set to "outreach" in the SMS pipeline, this causes a non-match. We don't often use the "Contains" filter often because many of our keywords are common words that could be triggered accidentally as part of normal communication.

<img width="651" alt="Screenshot 2024-05-02 at 10 05 49 AM" src="https://github.com/SparkDevNetwork/Rock/assets/32227063/3da5e408-76e1-49bd-b4bb-85f510ad81c4">

We would expect leading and trailing whitespace of the string to be trimmed before conducting the "Equal to" match comparison. Similar to how the case of the text isn't considered in the "Equal to" match because of the common variance in text messaging, we would put whitespace in that same category. This is how other 3rd party texting platforms treat keywords as well (Gloo, EZtexting, etc)

I can't think of a place in which a leading or trailing whitespace would be used in a keyword match. 

### Actual Behavior

SMS Pipeline's "Equal to" filter considers leading/trailing whitespace in the match of SMS keywords or phrases.

### Expected Behavior

SMS Pipeline would strip out the leading/trailing whitespace in the "Equal to" filter and still match on keywords and whitespace between words only.

Interior spacing should be considered. For example, we would expect "mens outreach" to consider the space in between words.

### Steps to Reproduce

- Create an "Equal to" keyword match **outreach** in the SMS Pipeline
- Text "outeach " or " outreach"
- The keyword is not matched

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.4

### Client Culture Setting

en-us

**Comment by dataCollegechurch** [comment]
Our current workaround is something like this: 
![image](https://github.com/user-attachments/assets/1e8e876c-7053-4a75-ab12-17b4d3ec747e)
