### ISSUE TITLE
When Copying a Security Group the New Security Group Inherits the Permissions of the Original Security Group that was Copied

### ISSUE THREAD

**Issue by thejasonharvey** [SparkDevNetwork/Rock#5862]
### Description

When copying a group that is also set to be used as a security role. If the original group has been given access to parts of Rock, then the new group (the copy of the old one) will also be given those permissions upon creation.

### Actual Behavior

I was working on updating our Org Chart to accommodate some restructuring. We use those groups as security roles as well. In the process of making the updates, I copied one group several times as its settings and naming convention made it convenient and preferable over starting from scratch. When I went to assign the newly created (copied) groups the access they needed in Rock, they all had the same access as the original group.

### Expected Behavior

I would not expect the new groups to be automatically provided the same access as the original groups. Or, I would expect a notification that would let me know the new group would inherit those settings OR I would expect to be given the option (because I could see how that might be convenient under certain circumstances) 

### Steps to Reproduce

- Go to the group viewer and create a new group marking it as a security role.
- Click on any page or block and give access to that group you created.
![Screenshot 2024-05-07 145515](https://github.com/SparkDevNetwork/Rock/assets/130079417/b2b2eb8c-cba1-4cde-b493-9c130c8e30bc)
- Go back to the group viewer and copy the group. (you may need to configure the block settings to provide the Copy icon)
![Screenshot 2024-05-07 145631](https://github.com/SparkDevNetwork/Rock/assets/130079417/aacd62f9-4d58-4ba4-a95a-1ec2653a1bcd)
- Go back to the item you gave the original group access to and notice the new copy of the original group also has access.

![Screenshot 2024-05-07 145618](https://github.com/SparkDevNetwork/Rock/assets/130079417/33a020e7-4518-4d7a-905f-a5358543ee1d)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.3,16.4

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@thejasonharvey Hi Jason  Great timing!  We have a feature enhancement to copying Groups that will be in v17. 

Starting in v17, when the Copy icon is selected for a Group, a new Copy Group block will display.  This block informs the user what items will be copied/not copied and let's you decide if you would like to Include Child Groups.  If you would like, you can try this out now on the pre-alpha site.  

I will be closing this issue at this time, but please let me know if you have any questions.

![image](https://github.com/SparkDevNetwork/Rock/assets/134172019/bb7d98ed-81f1-4319-a466-31639f6af456)

**Comment by thejasonharvey** [comment]
That'll work, thanks!
