### ISSUE TITLE
Obsidian Family Pre-Registration Page Parameters Not Working

### ISSUE THREAD

**Issue by GordonArber** [SparkDevNetwork/Rock#5867]
### Description

The new obsidian family pre-family registration block is not allowing us to pass CampusId or CampusGuid any longer.

### Actual Behavior

When I navigate to the page that has the obsidian family pre-family registration block and add either ?CampusId=1 or ?CampusGuid=76882ae3-1ce8-42a6-a2b6-8c0b29cf8cf8 it doesn't prefill the campus like the legacy block did.

### Expected Behavior

I expected that the obsidian family pre-registration block to update the campus if either the CampusId or the CampusGuid was provided via URL.

### Steps to Reproduce

- Create a new campus on both the demo site.
- Create a new campus on the v14_3.tm site.
- Add new page with the legacy family pre-registration block on the v14_3.tm site.
- Add new page with the obsidian family pre-registartion block on the demo site.
- Add either of the "CampusId" or the "CampusGuid" page parameters to the urls with a valid Campus Id/Guid.
- The demo site won't autofill the campus, while the v14_3.tm will.
![image](https://github.com/SparkDevNetwork/Rock/assets/19920780/b4456c55-4de7-4cd9-84ef-749fe2cc25bd)
![image](https://github.com/SparkDevNetwork/Rock/assets/19920780/caca717a-cd90-473b-864f-af4b81bebee5)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.2 (1.16.2.1)

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@GordonArber  Hi Gordon - Thanks for reporting this issue.  I'm happy to let you know that the issue has been resolved in v16.4 with this [commit](https://github.com/SparkDevNetwork/Rock/commit/644c7d93239c9fe1f2ec8aca3f81cb6cd51827a5).  

I also updated the demo site from v16.2 to v16.5 and the Campus is now being prefilled based on campus parameters provided in the URL. 

![image](https://github.com/SparkDevNetwork/Rock/assets/134172019/627bd3b9-d446-47bb-b813-5468eef64c68)

I will be closing this issue at this time, let me know if you have any questions.
