### ISSUE TITLE
The icontype parameter of KPI shortcode doesn't have any effect

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/Rock#5869]
### Description

Including a value for the `icontype` parameter for an item in the `kpis` shortcode does not seem to have any effect on the resulting HTML output. No matter what, the icon CSS class ends up starting with "fa".

### Actual Behavior

Whether the `icontype` parameter is included or not, the resulting icon CSS class always starts with "fa".

### Expected Behavior

If the `icontype` parameter is omitted, then the icon CSS class should start with "fa". 

If the `icontype` parameter has a value specified, then the resulting icon CSS class should begin with the specified value.

### Steps to Reproduce

1. Add an HTML block to any page
2. Edit the block and add this Lava to the content area:
```
{[ kpis ]}
    [[ kpi value:'1234' color:'orange' icontype:'xyz' icon:'icon-class' ]][[ endkpi ]] 
{[ endkpis ]} 
```
3. Save the block
4. Inspect the page's HTML and notice that the icon CSS class for the KPI is `fa fa-fw icon-class` instead of `xyz fa-fw icon-class` like it should be

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.3 & 16.5

### Client Culture Setting

en-US

**Comment by chead4** [comment]
Fixed via migration ([line 46](https://github.com/SparkDevNetwork/Rock/commit/290feacc309442e7a043afb5c3a04b328440297f#diff-76d91ae9f37af1ebd31171b9930fb1d03ea75d04a789f1d7882bd74893fc664aR46)).
