### ISSUE TITLE
Google Map Shortcode Zoom Parameter

### ISSUE THREAD

**Issue by sheatipton** [SparkDevNetwork/Rock#5874]
### Description

When using the "Google Map" shortcode, I am unable to set a zoom level parameter when there are more than ONE markers

### Actual Behavior

using the following lava code below on a page produces a gray screen: 

```
{[ googlemap zoom:'10']}
    [[ marker location:'33.640705,-112.280198']][[ endmarker ]]
    [[ marker location:'33.52764, -112.262571']][[ endmarker ]]
    [[ marker location:'33.54764, -112.292571']][[ endmarker ]]
{[ endgooglemap ]}
```

<img width="1512" alt="Screenshot 2024-05-14 at 3 56 02 PM" src="https://github.com/SparkDevNetwork/Rock/assets/63987819/b30dbb3c-f3dd-480c-99c4-704e8516ec84">

### Expected Behavior

modifying the lava so there is only ONE marker solves the issue
```
{[ googlemap zoom:'10']}
    [[ marker location:'33.640705,-112.280198']][[ endmarker ]]
{[ endgooglemap ]}
```
<img width="1512" alt="Screenshot 2024-05-14 at 4 02 44 PM" src="https://github.com/SparkDevNetwork/Rock/assets/63987819/7b8d2506-1899-49bc-af08-2a007e27c6f4">

### Steps to Reproduce

-Create a page and add the lava shortcode to a block
-To replicate the issue, add a zoom parameter to a google map shortcode with multiple markers

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 15.1 (1.15.1.1)

### Client Culture Setting

en-US

**Comment by chead4** [comment]
Fixed via migration ([line 157](https://github.com/SparkDevNetwork/Rock/commit/290feacc309442e7a043afb5c3a04b328440297f#diff-76d91ae9f37af1ebd31171b9930fb1d03ea75d04a789f1d7882bd74893fc664aR157)).
