### ISSUE TITLE
Obsidian Registration Entry Block does not honor block setting for "Family Term"

### ISSUE THREAD

**Issue by treusch** [SparkDevNetwork/Rock#5876]
### Description

Obsidian Registration Entry Block does not honor block setting for "Family Term". The code ignores the attribute value and attribute default value and just has "immediate family" hard coded in the block.

### Actual Behavior

When updating the block setting for "Family Term" the block only displays "Registrant is in the same immediate family as" and does not use the block setting value in place of "immediate family". 

This also happens on the Review Registration section when the block attempts to confirm what family the registrar is in, if the registration template is set up as "Prompt for Registrar".

### Expected Behavior

The block would utilize the value in the block setting and replace "immediate family" with whatever text was used in the block setting on both the registrant message and the registration review section.

### Steps to Reproduce

1. Go to the external homepage part of the page tree and navigate to the page (or create one) that contains the Obsidian Registration Entry block.
2. Update the settings on the block so that the "Family Term" is something other than the default value of "immediate family".
![image](https://github.com/SparkDevNetwork/Rock/assets/38530809/5b2aef91-8d68-4d9e-a7db-8b6619f3ff0c)

3. Save the block settings.
4. Create a registration template
5. Set the Registrar Options under Details to "Prompt for Registrar".
6. Check the Allow Multiple Registrants check box.
7. Select "Ask" for the "Registrants in Same Family" option.
![image](https://github.com/SparkDevNetwork/Rock/assets/38530809/86f8dd7f-1429-4233-b87d-def4ddbf4f8b)

8. Create a registration instance for that template.
9. Log in to the external site (it also happens if you are not logged in)
10. Open the page with the obsidian registration entry block on it (from steps 1 & 2 above) and pass in the registration instance id to begin a registration using the new instance you created in step 5.
11. Choose to register more than one person.
12. You will see a page that looks like this
![image](https://github.com/SparkDevNetwork/Rock/assets/38530809/d976aaf9-20fb-457d-b444-dd8c026b699d)

13. "immediate family" should have been replaced with whatever text was updated in the block setting.
14. Continue the registration and add the additional person/people and when you get to the Review Registration section of the registration, you will see a page that looks like this and again, the "immediate family" family term should have gotten replaced with whatever text was put in the block setting but it will not be.
![image](https://github.com/SparkDevNetwork/Rock/assets/38530809/aba2f693-3fbd-4f88-af03-823494205a1e)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

14.3, 16.2, 16.3, 16.4

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/5d01c0c61c39e3415e94423be0409601de9a164a
