### ISSUE TITLE
Registration Removes Discounts

### ISSUE THREAD

**Issue by mijobryco** [SparkDevNetwork/Rock#5885]
### Description

Example: Summer Camp Registration. A person registers and makes a payment and receives a discount. They make an additional payment, but if an additional discount is applied than all other discounts are removed from the registration.  

### Actual Behavior

A person registers and makes an initial payment with a qualifying discount code.  The same person later makes an additional payment, and qualifies for an additional discount. If the Discount Code box is blank, and the 'Discount Amount (per Registrant)' has an amount entered, then the previous discount is replaced.

### Expected Behavior

The registrant would receive the pre-defined amount and the Custom Discount Amount added in the Discount Amount (per Registrant) box

### Steps to Reproduce

Create a Registration with Discount Codes (Camp $600)
Register for the event with a discount code (Early Bird $100) (Amount Owed $500)
Edit Registration Details and add an additional discount in the Discount Amount (per Registrant) field. 
Amount removes the pre-defined discount.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.4

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@mijobryco Thanks for submitting your first issue.  After reviewing, this is an enhancement to allow multiple discounts to be applied to a registration. At this time only one discount can be applied per registration instance. If multiple discounts are set up to automatically apply, and if the registration qualifies for all of them, then the first discount listed in the template will be applied. When a discount is automatically applied, it can be manually replaced with a single other code.

At this time, I will be closing this issue. We welcome you to share you feature/idea with us on the [Rock Community Ideas & Core Changes board](https://community.rockrms.com/ideas-changes).  This allows the full community to speak into it and help us determine it's priority.

Lastly, Rock is all about community. A key part of strengthening this bond is knowing who we're engaging with. Could I ask you to include your name, organization, and a photo on your GitHub profile? It's a simple way to put faces to names, fostering a more connected and personal community atmosphere.

**Comment by mijobryco** [comment]
Thanks for your response. I think maybe I didn't communicate the issue clearly. Last year, we were able to add multiple discounts manually, not automatically, and the additionally added discount did not replace the other discounts. This year, however, it does remove them.

**Comment by chead4** [comment]
@mijobryco Thanks for the clarification.  I reviewed the [release notes](https://www.rockrms.com/ReleaseNotes) and found that there was a fix for #4922 ([commit](https://github.com/SparkDevNetwork/Rock/commit/0d09a3282fc877d49269519fa4673f70876ed90e)) in v13.2.  This fix no longer allows multiple discounts to be added to a registration.  

I tested on v12.9 and was able to add multiple discounts to a registration internally on the Registration Details block.  I then tested on v13.8 and multiple discounts are no longer able to be added but a newly added discount now replaces the other discount.   

I hope this information helps.

**Comment by mijobryco** [comment]
@chead4 Thank you for your patience with me. I think this is different. When a person has a manual discount amount applied and the person makes a payment the manual discount is removed. I'll see if I can recreate it on the demo site.
<img width="2560" alt="Screenshot 2024-05-23 at 2 14 54 PM (2)" src="https://github.com/SparkDevNetwork/Rock/assets/22777157/debe998e-c37c-4879-8ffb-00348dda2f11">
<img width="2560" alt="Screenshot 2024-05-23 at 2 09 41 PM (2)" src="https://github.com/SparkDevNetwork/Rock/assets/22777157/22443bb2-2218-4be7-adfd-2b515eabf32e">

The total cost was $200 less a $20 discount which would make total cost $180. Payment of $10 and $170 = $180 but the second screen shot shows $20 Balance Due

**Comment by chead4** [comment]
@mijobryco Sorry for the confusion. I followed the steps within your last comment and registered for an event, applied a manual discount and then made a payment(s).  Each time the amount remaining is correct.  
It would be appreciated if you can recreate on the demo site (v16.5) and include a video of the issue as this would help in investigation and recreation.

**Comment by mijobryco** [comment]
Sorry its been so long. I'm including a video. 

https://github.com/SparkDevNetwork/Rock/assets/22777157/0a491dd5-2270-4fee-8fb2-2e30da3c0c20

**Comment by sparkdevnetwork-service** [comment]
@mijobryco Thank you for the video.  I have been able to recreate and have reopened this issue.
