### ISSUE TITLE
Pushing Enter On Email Wizard Reloads template

### ISSUE THREAD

**Issue by Jchinlcbc** [SparkDevNetwork/Rock#5890]
### Description

When people create emails, they usually spend a lot of time and effort into making it look right. If someone is using the email wizard and gets most of the way though an email, pushing enter can cause most of their work to disappear, causing frustration & demoralization.

https://github.com/SparkDevNetwork/Rock/assets/100871349/13202842-4026-4413-ad73-b07be92219ef

### Actual Behavior

When using the email wizard, if you were to hit enter when editing an option set of an element except a text block, it loads the blank template. It keeps your communications list & email summery (ei: to, from & subject)

https://github.com/SparkDevNetwork/Rock/assets/100871349/9ce016c9-e284-42f6-b21e-81399d12e695

### Expected Behavior

When pushing enter, it has the same effect as clicking complete.

### Steps to Reproduce

1.) Start a new communication
2.) Fill out all the necessary fields & Choose your template
3.) Create an image, video, divider, Button Or RSBP Button using the WYSIWYG editor
4.) Edit the options for your newly created element.
5.) If you hit enter on any field that lets you add text the template should reset

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.4

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
We've tracked this down to a change/bug in the Summernote library which we will not be using in our upcoming Next Gen Communication Entry Wizard block.   Therefore...

Similar to what was described in issue #5002:
>  We've change our process how how we process issues that are for external components that we are not able to update ourselves. I'm closing this because it is in a external component. That said we are currently working on a new Obsidian block to replace this one and we'll use a different component for that one.

So, we're closing this one too and have it labeled as "Will Fix In Next Gen".
