### ISSUE TITLE
Schedules - the "First" is not being honored and showing every week instead.

### ISSUE THREAD

**Issue by cjfountain** [SparkDevNetwork/Rock#5894]
### Description

I recorded a short video recreating this on the demo site. https://somup.com/cZ1h085SJU

Our schedule for the "First" Wed every month is now showing up every Wed after updating to v16.4. The description on the schedule also doesn't indicate "The 1st Wednesday...". It just says "The Wednesday...".
![Snip - Schedules Rock RMS - Google Chrome (4)](https://github.com/SparkDevNetwork/Rock/assets/105759806/5296f9fb-13a0-402e-8c4c-df97c969d675)

### Actual Behavior

The schedule is showing up every week instead of once on the first of each month.
![Snip - Group Scheduler - Obsidian Rock RMS - Google Chrome (2)](https://github.com/SparkDevNetwork/Rock/assets/105759806/7e6103e4-9eca-45b2-9c03-f831e85332bb)

### Expected Behavior

The schedule would only display the event once per month on the "first" Wed (or Sunday as in the Demo video).

### Steps to Reproduce

- Go to the demo site and create a schedule for the "first" Wednesday of the month and add some check-in start and end times so you can view it on the Group Scheduler and the Schedule Toolbox "Sign up for additional times".  Go to the Check-in Config and select the schedule with a group.
- Go to the Group Scheduler or Schedule Toolbox and see that the "first" shows up every week.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.3 (demo site) & v16.4 (our prod site)

### Client Culture Setting

en-US

**Comment by jdwrhodes** [comment]
We are also experiencing this issue on our system. We are on v16.4 and the en-US Culture Setting. This was also tested and confirmed to be present on the v17.0 pre-alpha server.
