### ISSUE TITLE
Some date fields not respecting culture setting (reversion since 16.2) 

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#5898]
### Description

Something has reverted in v16.3 onwards around date formatting.  Date formats and date picker are not respecting culture settings.  v 16.2 used on the demo site behaves correctly.

Version 16.5 16.5 (1.16.5.4), Client Culture Setting: en-NZ, Browser settings Language = English (New Zealand).
Data and culture settings on PC, browser, and server are all set to en-NZ.  No changes since previously successful versions of Rock.

For en-NZ dates should be in dd/MM/yyyy format, but in the Communication History pages dates are mixed, sometimes shown as MM/dd/yyyy, sometimes as dd/MM/yyyy.

View Communication History. Created Date Range is in MM/dd/yyyy format, but Details and Sent are in correct dd/MM/yyyy format.

![ComHist1](https://github.com/SparkDevNetwork/Rock/assets/4658177/c2b7db2a-a3e0-43ff-b9b1-4647bbf64410)

Recipient Details Note has date in incorrect format.

![ComHist2](https://github.com/SparkDevNetwork/Rock/assets/4658177/bd46185f-3cf3-4b5b-8ef6-98def2085a18)

Communication History filter date picker goes to wrong month based on date...

![ComHist3](https://github.com/SparkDevNetwork/Rock/assets/4658177/20c02933-a412-46c8-8028-81f0cee62105)

...and after selecting the right date, displays the date in the field in the wrong format (MM/dd/yyyy).

![ComHist4](https://github.com/SparkDevNetwork/Rock/assets/4658177/3aa403a3-59bf-4772-af6f-a87a9ef3f32f)

The filter results include comms based on US date format not en-NZ format.

Also affecting other pages, such as Batch list, date selector in Financial Batch Detail.

This impacts the searching for communications.  If the date picker is used, a different result set is selected than if the dates are manually entered.

The dates 2nd June 2024 / 8th June 2024 selected using the date picker gives a result:
![Search1](https://github.com/SparkDevNetwork/Rock/assets/4658177/b3907d5e-bb58-491d-89a9-2cb2c6f76458)

The date picker is not correctly applying the date according to the culture.

The dates 2nd June 2024 entered as '02/06/2024' / '08/06/2024' selected returns:
![Search2](https://github.com/SparkDevNetwork/Rock/assets/4658177/7532b941-7a3f-46c5-9066-773f94fd0b59)

Manually entering the date applies the data according to the culture.

### Actual Behavior

Dates displayed are not respecting culture setting.

### Expected Behavior

Date picker and date display range should respect culture setting.

### Steps to Reproduce

Use a Rock site running 16.5.  
View a list of Batches with transactions.  Note the date format.
I'm not sure if the global attribute Organization Country Code is relevant.
Change your browsers settings add the language English (New Zealand).  
Not sure if you need to change your PC's culture settings.
Review the list of Batches.  Date format still in M/dd/yyyy format.  
View transactions.  Date range will be in US format, dates on individual transactions will be M/dd/yyyy.

![Date6](https://github.com/SparkDevNetwork/Rock/assets/4658177/258271f6-f7ca-4726-aff7-7b2141de858a)

![Date7](https://github.com/SparkDevNetwork/Rock/assets/4658177/9e3779fb-1069-4398-9165-c2c252728e58)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Version 16.5 16.5 (1.16.5.4), 

### Client Culture Setting

Client Culture Setting: en-NZ, Browser settings Language = English (New Zealand).

**Comment by camattard** [comment]
We are also experiencing this for Person Attributes.
If we set an expiry date of 24th February 2025 using the date picker it won't save the date because it is entered as 02/24/2025.
All dates entered already prior to updating from v15 are in dd/MM/yyyy format still but dataview criteria doesn't work against them anymore and if we try update the date it goes back to USA formatting not server culture formatting.

![no-date-format-selected](https://github.com/SparkDevNetwork/Rock/assets/5058266/90696cb4-295f-43d0-ab4f-a2aae56544b2)
![rock-server-system-datetime](https://github.com/SparkDevNetwork/Rock/assets/5058266/366ff9a8-7dfb-428d-b970-7f70ae18ab8c)
![wont-save-date-due-to-format](https://github.com/SparkDevNetwork/Rock/assets/5058266/81b5879c-826d-4e1b-8208-c79d751bfb28)

**Comment by chead4** [comment]
@camattard Hi Cameron- I was able to recreate the issue in v16.5 and have added the details to our internal ticket.

**Comment by camattard** [comment]
@chead4 Thanks! Is there an ETA on when this could be fixed? Or a workaround for us, as this is causing issues for us right across Rock. It is also occurring for us in the schedule builder on all our groups.
![dates-schedulebuilder](https://github.com/SparkDevNetwork/Rock/assets/5058266/f18c2eee-887a-4f43-864e-298b5090f1f8)

**Comment by ElimAdmin** [comment]
@camattard - We changed our browser settings to US, but there are still places this acts inconsistently because the code behaves differently to the date picker.

**Comment by jasonhendee** [comment]
@ElimAdmin, @camattard all of the above examples should be corrected in v16.7 of Rock. Please let us know if you stumble into any more instances of incorrect date formatting. Thank you!

---

For future reference, the following commit also addressed this issue: https://github.com/SparkDevNetwork/Rock/commit/822e29469a9c4c7421dc9bd2ba4332ebbb407224
