### ISSUE TITLE
Transactions generated by Registration Details, Manual Payment not capturing all event details in comment

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#5900]
### Description

When an event registration is paid for using a credit/debit card at the time of registration, a transaction is generated that captures a full description of the event and registration to which the transaction applies.

![Regpay2](https://github.com/SparkDevNetwork/Rock/assets/4658177/06a3ae74-9eb0-4295-88ba-43f5549261f0)

This does not happen if the payment is later manually applied to the Registration Details, by viewing the Registration > Edit > Payments > [Process New Payment] or [Add Manual Payment].

![Regpay1](https://github.com/SparkDevNetwork/Rock/assets/4658177/fabba9ea-5171-4eb1-be12-ef3dbad5798a)

The same details should be captured for manual payments to aid in reconciliation and audit.

### Actual Behavior

A manual payment added to a registration event does not record on the transaction as much details as is recorded when the payment is made via an online payment gateway at the time of registration.

### Expected Behavior

The Comment on the transaction should record the same detail for all types of Registration event payments.

### Steps to Reproduce

Pay for a registration event at the time of registration.
Create a registration and do not pay.
Manually apply a payment.
Compare the transactions created and compare the comment details.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Version 16.5 16.5 (1.16.5.4), 

### Client Culture Setting

Client Culture Setting: en-NZ, Browser settings Language = English (New Zealand).

**Comment by sparkdevnetwork-service** [comment]
@ElimAdmin  Are you saying this behavior changed (meaning it used to work that way) or that you would like to request that Rock do this?  If it's the later, can you close this issue and re-open this as a Feature Request over at the [Ideas and Core Changes](https://community.rockrms.com/ideas-changes) page.

**Comment by ElimAdmin** [comment]
Yes, it's a change request.  Ok, thanks, will do.
