### ISSUE TITLE
Creating Financial Transaction Refund Causes Server Error (cannot update transaction state to refunded over Api)

### ISSUE THREAD

**Issue by localpath** [SparkDevNetwork/Rock#5902]
### Description

How do we correctly update a Financial Transaction to be refunded via the Api? This is an external transaction not processed via a gateway processor in Rock.

![image](https://github.com/SparkDevNetwork/Rock/assets/44937070/dc8f05e4-f24c-47e2-a623-af67efa79b0e)

### Actual Behavior

Creating a FinancialTransactionRefund causes a server error both via the REST documents and using an http client.

![image](https://github.com/SparkDevNetwork/Rock/assets/44937070/c688e36c-8e22-417c-a5e5-06a6a4a3de4a)

![image](https://github.com/SparkDevNetwork/Rock/assets/44937070/d51e7cdd-b7fb-4123-8291-ef457965c2e8)

### Expected Behavior

I can create a resource using the Api.

1. A contribution is created in our system
2. Our system creates a financial transaction in Rock via integration sync over REST Api
3. The contribution in our system is refunded
4. We sync this refund status/state to Rock via integration sync over REST Api
5. The contribution in Rock is in a refunded state

### Steps to Reproduce

- Go to ['...'](https://rock.rocksolidchurchdemo.com/api/docs/index#!/FinancialTransactionRefunds/POSTapi_FinancialTransactionRefunds)
- Click on Try it out\
- See error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.2 (1.16.2.1)

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@localpath Hi Garrick

Github is used solely for reporting new issues and we kindly ask that all new issues submitted are well-vetted with screenshots that clearly identify functionality that previously worked but is now broken  This request appears to be more of a question on using the refund api.

I'll be closing this issue, but would like to point you to some resources that can help you find the answers you need:

1. Check out the API Documentation section on our Developer Resources page at [community.rockrms.com](https://community.rockrms.com/developer). There's an Introduction to Rock API Concepts video that explains how Rock's API works.
2. You can also reach out to the community on Rocket Chat. They're a great resource in helping to answer questions in a timely manner.
