### ISSUE TITLE
Registration workflow exposes non-Public Registration Template attribute to public

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#5903]
### Description

My understanding is that the 'Public' setting of an attribute determines whether it should or should not be displayed on the public web site. If this is correct, then:
A **Registration Attribute** that is not ticked 'Public' should not display when the person registering is going through the Registration workflow.
Current behaviour is that even if the attribute is not ticked Public, the attribute is still displayed.  This means that Registration attributes cannot be used in private to manage the registration.

--------------------------------------------------------
**Registration attribute (entered on registration template)**
![RegoAtt0](https://github.com/SparkDevNetwork/Rock/assets/4658177/915af0a1-ab59-413f-a4f6-723a12ed2b70)

--------------------------------------------------------
**Registration attribute settings showing that the attribute is not public.**
![RegoAtt5](https://github.com/SparkDevNetwork/Rock/assets/4658177/26957d31-8b74-490f-a942-539e4f14aea3)

--------------------------------------------------------
**Screen shot of registration workflow showing the attribute being displayed on the public web site, user not logged in**.
![RegoAtt1](https://github.com/SparkDevNetwork/Rock/assets/4658177/c4853dc7-3368-41e5-8b15-8fd87272999b)

--------------------------------------------------------
**Attribute correctly displaying in the backend where I want to use it: on the Registration.**
![RegoAtt3](https://github.com/SparkDevNetwork/Rock/assets/4658177/7dbceeb9-f11c-45f1-8373-ed7672735f4d)
![RegoAtt4](https://github.com/SparkDevNetwork/Rock/assets/4658177/c51235d8-025e-4751-b186-8e2d5194d632)

### Actual Behavior

The Public status of a Registration attribute is not respected on the public website when going through the Registration Workflow.

### Expected Behavior

The Registration attribute NOT ticket Public, should not display in public.

### Steps to Reproduce

1. Go to demo site.
2. Go to Tools > Event Registration
3. Edit the template for Summer Camp
4. Add a Registration Attribute, set Public to NO (not ticked)
5. Change the end date of the Summer Camp instance to in the future to activate
6. Go to https://rock.rocksolidchurchdemo.com/Registration?RegistrationInstanceId=1
7. Enter registration details, and step through pages until you see... this:

![RegoAtt6](https://github.com/SparkDevNetwork/Rock/assets/4658177/2bbdec33-658e-4170-9d84-508e9103fa1e)

8. Verify that you see non Public Registration attribute in the public setting as part of the registration workflow. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Version 16.5 16.5 (1.16.5.4), 

### Client Culture Setting

Client Culture Setting: en-NZ, Browser settings Language = English (New Zealand).

**Comment by chead4** [comment]
@ElimAdmin Hi Ken - Please see the comment in [#5553](https://github.com/SparkDevNetwork/Rock/issues/5553#issuecomment-1724560641) for resolution of this issue.
