### ISSUE TITLE
Cannot recover from the entry of an email address with invalid characters in Family Add

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#5909]
### Description

Adding a family.  Entered email address as 
`First Name <firstname01@gmail.com>`

This results in a warning in the demo site.
In 16.5 it results in a never ending pulsing Rock processing ball.  Doesn't give error message and doesn't recover.
![EmailAdd1](https://github.com/SparkDevNetwork/Rock/assets/4658177/3066d031-c3f2-4419-98cf-ac316533884d)

### Actual Behavior

The error checking on the email field on Add Family has stopped functioning properly.  

### Expected Behavior

Error checking behaviour on 16.2 should be applied.

### Steps to Reproduce

Start with a Rock v 16.5 instance.
Add Family, enter email in above format.
See if you get an error message or if you get locked.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Version 16.5 16.5 (1.16.5.4), 

### Client Culture Setting

Client Culture Setting: en-NZ, Browser settings Language = English (New Zealand).

**Comment by luke-infoministry** [comment]
@ElimAdmin I was unable to reproduce this in demo or prealpha. 
I received a validation message about invalid characters, but was able to edit the field.

Are there characters beyond the `<` and `>` there?

**Comment by ElimAdmin** [comment]
The very first time I tried this today I did get the error message successfully on typing in the address and I couldn't progress to Submit. (Expected behaviour.)
I then cut and past the "First Last <firstlast@gmail.com>" email address from out of Thunderbird and pasted that into the field.
Submit did not give an error, it just locked.
I tried pasting the copied email address into Notepad, then copying and pasting it into the field - same result.
Every attempt since then has worked when entering "firstlast@gmail.com", but gets locked with "First Last <firstlast@gmail.com>".
I tried restarting Rock - same result.
I tried restarting MSSQLSERVER - same result.
I tried restarting the server - same result.
Maybe the first time I submitted the copied text from Thunderbird it errored and locked something somewhere?  But if I've restarted everything, I don't know where the lock would be.
You will see from the attached video that the validation on the field turns the Email icon red, but doesn't prevent Submit from going into the locked mode.

Confirming I'm on version  Rock McKinley 16.5 (1.16.5.4)

https://github.com/SparkDevNetwork/Rock/assets/4658177/f7ff6882-0d2a-4c5f-92de-180a772c6225

**Comment by ElimAdmin** [comment]
This is how I copied the email address out of Thunderbird, so it looks like there might have been code either side.
But when I paste into Notepad I don't see anything.

https://github.com/SparkDevNetwork/Rock/assets/4658177/8d98d94d-9376-4325-a211-431a5554dc63

**Comment by ElimAdmin** [comment]
If this helps:
![EmailAdd2](https://github.com/SparkDevNetwork/Rock/assets/4658177/3bd80ba6-0527-4f39-9664-cac41de9908a)

**Comment by chead4** [comment]
@ElimAdmin Hi Ken, So far we have been unable to recreate this issue.  It would be appreciated if you could forward the email that you have mentioned above to colleen@sparkdevnetwork.org so that I can try and reproduce with that exact email.

**Comment by ElimAdmin** [comment]
It will not be the email.  It will probably be what is copied from Thunderbird.  Closing this issue as you cannot reproduce it and it's an edge case.
