### ISSUE TITLE
Check Email SenderPersonAliasId and ReviewerPersonAliasId for system generated emails

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#5911]
### Description

I'm not sure what sets these fields on a Communication that is generated by the system (not a Communication sent through New Communication).  I have been sending manually trigger Registration Confirmation emails, and emails have been going out as event Registration Confirmations, Following Notices, Assessments are Ready to Take, Group Attendance Reminders - all with SenderPersonalAliasId and ReviewerPersonAliasId set to one of our staff unrelated to the comms.  

This changed for us around 12 June 2023, when these fields used to be set to 5451 (Porirua Elim Christian Centre, the business record).

This person does not show and is not set on any of the Home > Communications > System Communications templates.

These fields are correctly set for communications (emails) manually sent through the New Communication workflow.

Communication History - showing totally unrelated person:
![ComWho1](https://github.com/SparkDevNetwork/Rock/assets/4658177/83d241ee-3ebf-4456-be92-7e6ae612e83f)

Communication Records
![ComWho2](https://github.com/SparkDevNetwork/Rock/assets/4658177/013f2179-b4ca-4ce0-9782-3448e7b416d6)

### Actual Behavior

The SenderPersonAliasId and the ReviewerPersonAliasId are set to someone totally unrelated to the communication for system generated emails.

### Expected Behavior

The SenderPersonAliasId and the ReviewerPersonAliasId should be set to the person logged on if the communication has been manually triggered, or to a global setting (?? where) if it is a system email, or to NULL?  (I can't see this person set in any of our communication settings or global settings, but I have probably missed something?)

### Steps to Reproduce

Review these fields in Communication and check where they are set from?
`select Subject, CreatedDateTime, CreatedByPersonAliasId, SenderPersonAliasId, ReviewerPersonAliasId from Communication order by id desc;'

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Version 16.5 16.5 (1.16.5.4), 

### Client Culture Setting

Client Culture Setting: en-NZ, Browser settings Language = English (New Zealand).

**Comment by chead4** [comment]
@ElimAdmin Hi Ken
Thank you for submitting this issue. 
 
Each System Communication template has a From Address.  If the From Address is not entered it will use the ‘Organization Email’ Global Attribute Value when a communication is sent using the template.
![image](https://github.com/SparkDevNetwork/Rock/assets/134172019/c9aad7bb-d3fe-4753-a260-c2280111ac57)

 
I recommend reviewing your Global Attribute - Organization Email setting and see if it matches the person who is sending the emails.
 
![image](https://github.com/SparkDevNetwork/Rock/assets/134172019/cc912ea7-bc22-4c9c-949c-7acb362ab485)


Additionally, in the future, you may want to reach out to the community on Rocket Chat for help with configuration questions as the response may be quicker.  Let me know if this resolved the issue for you.

**Comment by ElimAdmin** [comment]
Thank you @chead4 .  

The Person selected, saved, and reported in the Communication table for system emails is the first Person that has an [Email] address matching the Global Attribute 'OrganizationEmail' :  

`SELECT TOP 1 [Id] FROM [Person] WHERE [Email] = OrganizationEmail ORDER BY [Id]'

So if a Person with an Id LOWER than the Person (or Business Person) who CURRENTLY has the Email = the OrganizationEmail is set to have the Organization Email, then THAT Person will subsequently be reported as the Person sending system emails.  

It is probably unlikely that the OrganizationEmail would normally be set on multiple Persons.  

For the team to consider: If a Person is going to be linked to the OrganizationEmail global attribute, then in the SETTING of this attribute, then maybe there should be a clear link to the Person who is being used as the sender of system emails to avoid this in the future.

This issue can be closed.
