### ISSUE TITLE
Lava Tag Behaves in Unexpected Ways

### ISSUE THREAD

**Issue by billdeitrick** [SparkDevNetwork/Rock#5913]
### Description

The `Lava` tag (https://community.rockrms.com/lava/tags/lava-tags) behaves in unexpected ways depending on both whitespace and the other contents of the field containing the Lava code. In certain cases, it will output the raw Lava rather than executing the Lava code and rendering the result.

### Actual Behavior

This first example behaves as expected:

Input:

```
{% lava echo "Hello World" %}
```

Output:
```
Hello World
```

This example doesn't behave as expected, outputting the Lava source rather than evalutating the code and rendering the result:

Input:

```
{% lava 
    echo "Hello World" %}
```

Output:

```
{% lava echo "Hello World" %}
```

If any other Lava is added to the Lava field, even if it has no effect, the Lava is executed and rendered:

Input:

```
{% lava 
    echo "Hello World" %}
{{ foo }}
```

Output:

```
Hello World
```

### Expected Behavior

The behavior and output of the `Lava` tag should be consistent regardless of the presence of other Lava code in the same field.

If the current behavior is intended, it might be helpful to have a note added to the documentation for the `Lava` tag.

### Steps to Reproduce

On Rock Solid demo, navigate to Intranet > Shared Documents. Edit the HTML block and replace the HTML markup with the following Lava:

![2024-06-14_10-05-13](https://github.com/SparkDevNetwork/Rock/assets/4174527/bf97d745-7649-4345-964f-d826c08791ef)

Observe that the Lava source is output to the page:

![2024-06-14_10-05-51](https://github.com/SparkDevNetwork/Rock/assets/4174527/625d3bff-2a2e-4c9e-9536-883e73bf755d)

This issue is present in both 16.5 and pre-alpha 1.17.0.21.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.5

### Client Culture Setting

en-US

**Comment by luke-infoministry** [comment]
@billdeitrick Is there a difference in the behavior between the .Liquid and fluid engine?

I recently saw a report where Lava that had worked where the opening and closing `{% %}` characters were split across newlines no longer worked after a Fluid engine update

**Comment by billdeitrick** [comment]
@luke-infoministry This command is v13+ Fluid only according to the docs.

It does seem related to the issue you're describing with the open/close tag delimiters, but the example in the docs explicitly shows this tag on multiple lines. So, I was very surprised when the difference between it working and not working when spread over multiple lines was whether or not there was another Lava tag or merge field present same Lava field.

I could be convinced that this is "working as expected" instead of a bug, but in that case I think a note in the documentation about this would be helpful.

**Comment by chead4** [comment]
@billdeitrick & @luke-infoministry Hi Bill and thanks Luke.  Luke is correct in that Lava can't be split over newlines in the Fluid engine.  I have submitted a request to update the Lava documentation and I will be closing this issue at this time.
