### ISSUE TITLE
Custom Columns on Group Attendance List block causes error.

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#5917]
### Description

The Group Attendance List block provides setting for Custom Grid Options and specifically the option to add Custom Columns, however you cannot use the 'Row' merge field as specified in the help text.

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/f79e2d87-5d54-4009-91c8-d7ee534248a3)

Column just returns following error:
_Liquid syntax error: Object 'RockWeb.Blocks.Groups.AttendanceListOccurrence' is invalid because it is neither a built-in type nor implements ILiquidizable_

![image](https://github.com/SparkDevNetwork/Rock/assets/548180/51ace8d6-9574-496c-ba8a-09a43c7ebe02)

### Actual Behavior

Actual Behavior

### Expected Behavior

Be able to use the 'Row' merge field like help text indicates.

### Steps to Reproduce

- Go to Group Attendance page
- Edit block settings for the Group Attendance List block on the page
- Click 'Custom Grid Options' 
- Add a custom column with "{{ Row.Id }}" as the lava template.
- Save changes
- Notice, that instead of the occurrence's id being displayed, a lava error is displayed

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.5

### Client Culture Setting

en-US

**Comment by MrUpsideDown** [comment]
Please note that because some of the rows in this list are 'virtual' (i.e. they do not yet exist in the database), the Id for these rows will have a value of 0 until someone actually creates an attendance record for that virtual occurrence.
