### ISSUE TITLE
Malformed iCal code when saving a Schedule by Day

### ISSUE THREAD

**Issue by joannnaburress** [SparkDevNetwork/Rock#5918]
### Description

When a Schedule runs Monthly and recurs on the First [Day of Week] of the month, the iCal code that is being generated is missing a '1' in front of the day of the week code. For this schedule:
![image](https://github.com/SparkDevNetwork/Rock/assets/71147867/ed3033e7-7d32-4bd8-8aca-f553b9aff6d0)

It is set to run on the 1st Tuesday of the month, but the malformed iCal code is registering as "The Tuesday of every month"
![image](https://github.com/SparkDevNetwork/Rock/assets/71147867/3f4b1405-8743-4ed7-8e56-231ff7e42d93)

When we preview the iCal code & upcoming dates, we see the schedule is calculating on EVERY Tuesday, not just the 1st
![image](https://github.com/SparkDevNetwork/Rock/assets/71147867/2e0c3ac6-76b9-443f-b61d-00624f12322a)

When the iCal code is being generated for the 1st day-of-week monthly occurrence, it is missing the **1** before _TU_ `RRULE:FREQ=MONTHLY;BYDAY=TU ` and should be outputting `RRULE:FREQ=MONTHLY;BYDAY=1TU`

### Actual Behavior

When the iCal code is being generated for the 1st day-of-week monthly occurrence, it is outputting `RRULE:FREQ=MONTHLY;BYDAY=TU` which is causing occurrences to be calculated for EVERY Tuesday, and is rendering in the Schedule description as "The Tuesday of every month"

### Expected Behavior

When iCal code is generated for the 1st day-of-week monthly occurrence, I would expect it to output `RRULE:FREQ=MONTHLY;BYDAY=1TU` which would calculate only first-Tuesday-of-the-month occurrences, and would render in the Schedule description as "The 1st Tuesday of every month"

### Steps to Reproduce

- Go to Admin Tools->Checkin->Schedules and create a new Schedule
- Click Edit Schedule
- Select Recurring, Monthly, The [**First**] day of [any weekday] (2nd, 3rd, 4th, 5th, and Last all work correctly)
- Save the schedule and new Schedule.
- See that the description does not include '1st [weekday]'
- Edit the Schedule and click Preview to see that the occurrences are every week on the selected weekday.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.2 (Demo site), 16.4

### Client Culture Setting

en-US

**Comment by chead4** [comment]
Hi Joanna

I will be closing this issue as it has been resolved by #5894, and the fix will be in v16.6. While the descriptions of the two issues differ slightly, the underlying problem is the same.
