### ISSUE TITLE
Obsidian Registration Entry Block Unable to Edit Saved Registration with Registrant Form Fields AND Registration Attributes 

### ISSUE THREAD

**Issue by Marissa-Eubanks** [SparkDevNetwork/Rock#5929]
### Description

Unable to edit the registrant form fields in a saved registration when the registration template also contains registration attributes. 
![Screen Shot 2024-07-03 at 10 45 22 AM](https://github.com/SparkDevNetwork/Rock/assets/115036501/953585a8-4b11-4e81-a20c-628d30447b6e)

### Actual Behavior

The 'Previous' button only allows for updating registration attributes when the registration template contains BOTH registrant form fields and registration attributes:

![PIC 3](https://github.com/SparkDevNetwork/Rock/assets/115036501/b8e6f5a4-6f09-4312-9166-67a0b3605071)
![Screen Shot 2024-07-03 at 10 46 33 AM](https://github.com/SparkDevNetwork/Rock/assets/115036501/0cdcda00-962f-4f64-b14c-68604b8f2774)

When the registration template only contains registrant form fields, they are accessible using the 'Previous' button and able to be edited:
![PIC 2](https://github.com/SparkDevNetwork/Rock/assets/115036501/2b437331-09e0-4d8f-8f66-862f15e1a739)
![Screen Shot 2024-07-03 at 10 49 37 AM](https://github.com/SparkDevNetwork/Rock/assets/115036501/c25946cb-df2e-468c-af59-531f2100f5f0)

### Expected Behavior

When accessing a saved registration, the 'Previous' button should take me back to edit the registration attributes. I should still see the 'Previous' button, allowing me to click again, to edit the registrant form fields included in the registration template.

### Steps to Reproduce

- Go to an event registration template.
- Add BOTH registrant form fields and registration attributes to the template.
- Ensure the 'Allow External Updates to Saved Registrations' box IS checked.
- Create a live instance and register someone for the event.
- View the registration while logged in as the person who was registered for the event.
- Click 'Previous'.

https://rocksolidchurchdemo.com/page/403?RegistrationTemplateId=3
https://www.rocksolidchurchdemo.com/Registration?RegistrationId=1

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.2, 14.3

### Client Culture Setting

en-US

**Comment by KarenRossi84** [comment]
I am doing some alpha testing on 16.6, wasn't sure if I should put in a new bug report or chime in here. In our camp registration we have several pages of forms. I am able to click on the registration to edit it and a previous button does appear but I can only click it once. After that one time the previous button disappears so you can not edit the registration in it's entirety. In my case this does seem to only effect the obsidian registration entry block not the original registration entry block. That one I can edit all the way through as I expect to.

**Comment by chead4** [comment]
@KarenRossi84 Thanks Karen for the additional details - I've added your comment to our internal ticket.
