### ISSUE TITLE
Group Schedule Confirmation Block Sends Multiple Emails When Declining a Schedule

### ISSUE THREAD

**Issue by asdf1nit** [SparkDevNetwork/Rock#5930]
### Description

If a volunteer is scheduled and declines the schedule and the group has the "Schedule Cancelation Person to Notify" setting set, the person who receives the decline response email is receiving 2 emails for each response. Note that this does NOT happen on the group-toolbox block, this bug only happens when a person uses the button in the email to decline.

![image](https://github.com/SparkDevNetwork/Rock/assets/18108765/831f9af3-dc4c-4a47-982c-ca5d30c775e3)

The issue is with the Group Schedule Confirmation block that is used by the group schedule confirmation email. If the email button is used the decline person will receive 2 emails for each decline.

![image](https://github.com/SparkDevNetwork/Rock/assets/18108765/e9300a8b-1098-4e76-b671-874e4c60f4a6)

Note: I was not able to reproduce this on the demo site as it does not send email. I was able to discuss and confirm this via rocket chat with Jason Hendee
### Actual Behavior

When a person declines a schedule two emails are sent to the notification person.

### Expected Behavior

Only one cancelation notification email should be sent to the cancelation notification person.

### Steps to Reproduce

- Set up a group for group scheduling, make sure to set a cancelation person to notify.
- Schedule a person to attend\serve and send the schedule confirmation email to them.
- On the schedule confirmation email click the decline button.
- Enter a reason if required and hit submit.
- Check the cancelation notification persons email and you will find two separate emails delivered for a single cancelation. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.5

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@asdf1nit  Hi Jonathan - I have not been able to recreate this issue.  It would be greatly appreciated if you could include screenshots for the blocks below for the Group Type and Group that you are experiencing the issue with as it would help me in reproducing.

1. General Settings/Group Type/Scheduling
2. People/Group Viewer/Group/Scheduling
3. External Site/Group Schedule Confirmation block settings (fields under template)

**Comment by asdf1nit** [comment]
Hi @chead4 - Here are the screenshots.

1. Group type settings for scheduling.
![image](https://github.com/SparkDevNetwork/Rock/assets/18108765/1fa1a8bf-b486-443e-9e38-e098edb861f8)

2. Group settings for scheduling 
![image](https://github.com/SparkDevNetwork/Rock/assets/18108765/9b7ac6c8-f80e-4945-a28b-2bef43ed7fd3)

3. Group Schedule Confirmation Block settings 
![image](https://github.com/SparkDevNetwork/Rock/assets/18108765/ccda05f1-ef50-4698-9c47-aa64d8a32685)

If anything else is needed please let me know!
