### ISSUE TITLE
All Attendance Records Showing

### ISSUE THREAD

**Issue by BraytonK** [SparkDevNetwork/Rock#5937]
### Description

When a user imports their calendar into Outlook (this likely also affects other email client/browser calendars) there is a discrepancy in which calendar events are created. Importing via .ics file will create calendar events for the all of the user's attendance records for all time, while importing from the calendar link will only create events from the current week's and onward attendance records.

Scenario: The user will have records that extend from well before the current week (1 year exactly, in this case) and attendance records for the current week and onward. 

### Actual Behavior

Copy Calendar Link
The user will then attempt to import their calendar via the link provided from the "Copy Calendar Link" button on the Schedule Toolbox, and it will only import the attendance records for the current week and onward. 

Add to Calendar
The user can then attempt to import their calendar from the .ics file provided from the "Add to Calendar" button on the Schedule Toolbox, and it will import all of their attendance records from all time.

### Expected Behavior

Importing from both methods should yield the same results. Ideally the imported attendance records should reflect what the user sees in their schedule toolbox.

### Steps to Reproduce

1. Place person in a group that allows scheduling.
![image](https://github.com/SparkDevNetwork/Rock/assets/19338221/f45e128f-dac2-4d8f-ad71-90025000caec)

2. As an example, schedule Alisha Admin for three attendance occurrences for the current week and at least one attendance occurrence for a year ago.
Note: To be able to reproduce the issue, we created an attendance record that occurred 1 year ago, via SQL.
![image](https://github.com/SparkDevNetwork/Rock/assets/19338221/b6e35747-030c-4151-847c-d3a55b21fb84)
![image](https://github.com/SparkDevNetwork/Rock/assets/19338221/119783b6-1ca2-4098-8603-70060987884e)
![image](https://github.com/SparkDevNetwork/Rock/assets/19338221/dfd970fc-946f-4a90-83e6-aea9b8270d84)

3. Select "Copy Calendar Link" on the Schedule Toolbox.
The calendar events created from the calendar link will encompass only the current week's and onward attendance records.
![image](https://github.com/SparkDevNetwork/Rock/assets/19338221/c4e68725-1959-4997-9bcd-1506ed13be71)

4. Select "Add to Calendar" button on the Schedule Toolbox.
The calendar events from the .ics file will encompass the person's attendance records from all time.
![image](https://github.com/SparkDevNetwork/Rock/assets/19338221/46590ba2-3387-431b-b904-7ca91fe2f0e9)
![image](https://github.com/SparkDevNetwork/Rock/assets/19338221/d1528589-e2b3-4970-873e-62630408405d)
![image](https://github.com/SparkDevNetwork/Rock/assets/19338221/70745bdf-7e3e-452c-a886-40e91de11d9b)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v17.0

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@BraytonK Hi Brayton - Thank you for the detailed write up for this issue. After reviewing, I was unable to recreate the issue on the pre-alpha site.  I have set up attendance records set up for Cindy Decker for 1/1/24, 7/9/24 and 7/13/24 and both the 'Add to Calendar' and 'Copy Calendar Link' options create events in my calendar for all three dates.

![image](https://github.com/SparkDevNetwork/Rock/assets/134172019/58aec2c7-110f-4a5a-b30a-0486bd85c42c)
![image](https://github.com/SparkDevNetwork/Rock/assets/134172019/e067feff-c7f4-4573-93e3-fa2df3881fc1)



I'm going to close this issue at this time.  If you're able to recreate on the pre-alpha site, please let me know and I'll reopen the issue.
