### ISSUE TITLE
Communication Entry Wizard

### ISSUE THREAD

**Issue by trfouger** [SparkDevNetwork/Rock#5938]
### Description

In v15.4, when going to the Communication Entry Wizard from a Group, the Recipient List was scrollable with the page limiter (50/500/5000) option available. This allows the NEXT button for the wizard to be accessible without having to scroll the page.  In version 16.4 and 16.5, the entire list of group members is displayed, and, in the case of large groups, the NEXT button cannot be seen without scrolling the page.  

### Actual Behavior

In v16.5 on the rocksolidchurchdemo site, navigate to People > Group Viewer > Section B > Marble Group.  This group has 13 members. Click on the communication bubble and the Recipient list is completely shown. All 13 members are displayed, and you must scroll the page to get to the NEXT button. 
![image](https://github.com/SparkDevNetwork/Rock/assets/11654018/99a60dac-12f8-476a-8737-977bc0b4bbc4)

### Expected Behavior

In V.15.4 on the rocksolidchurchdemo site, navigate to People > Group Viewer > Section B > Marble Group.  This group has 13 members. Click on the communication bubble and the Recipient list is only partially shown, but the grid has a scroll bar to see more of the member list. When scrolled down, the 50/500/5000 option is also shown. 
![image](https://github.com/SparkDevNetwork/Rock/assets/11654018/7f54ddd7-dd8c-43eb-9b25-92c7fbcc5944)

### Steps to Reproduce

See different behavior in v154. versus 16.5
- Go to 'People > Group Viewer > Section B > Marble Group'
- Click on 'the Communication bubble'

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v.16.5

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@trfouger Thanks for opening your first issue. I was able to recreate the issue.  However, I'll be closing this issue as the Communication Wizard is be rewritten into the Next Generation framework in v17.
