### ISSUE TITLE
File Uploads Don't Follow Preferred Format settings from BinaryFileType

### ISSUE THREAD

**Issue by nlBayside** [SparkDevNetwork/Rock#5939]
### Description

The Binary File Types allow for a Preferred Format to be set such as PDF, PNG, JPEG, etc. This property limits the files that can be uploaded to just that specific file type; however, it does not appear to work with the Azure Blob Storage provider, and upon further inspection on the demo site it doesn't appear to work with the Database provider either.

I've checked using Github Code Search to see where “Preferred Format” and only found it in 13 files.
![Github Code Search results](https://github.com/SparkDevNetwork/Rock/assets/85907597/499b7bdc-ab1c-4cff-adca-881a8bd4ec7f)
![Code Search Screenshot](https://github.com/SparkDevNetwork/Rock/assets/85907597/1b0e1b5d-fa54-4ccd-a8f8-2b2ede76ad1d)

As shown in the screenshot, these references are mostly declarations of properties in the class files or just references for the edit panel in BinaryFileTypeDetail block.
From the simple search, I see no references to “PreferredFormat” being used to validate the files uploaded.

There are also no references to “PreferredFormat” in FileUploader.ashx.cs but there are references to BinaryFileType, just not anything more than its Guid.
[FileUploader.ashx.cs](https://github.com/SparkDevNetwork/Rock/blob/67a2b3de3deb82a282048e4f2ff1940bbaeabf95/RockWeb/App_Code/FileUploader.ashx.cs)
![FileUploader.ahx.cs search](https://github.com/SparkDevNetwork/Rock/assets/85907597/21bd273c-58de-496f-ae4a-ad274ccdfed6)

We tested this on our own site using the Azure Blob Storage provider and found that it didn’t validate the files being uploaded in a Workflow.
We later tested this on the demo site with both a Workflow and a Person Attribute. These demo site tests failed to validate the file despite it being listed on the BinaryFileType.

## Binary File Type
![BinaryFileType Creation](https://github.com/SparkDevNetwork/Rock/assets/85907597/b1923723-0ceb-4695-a671-60dbdc769df5)

## Workflow
![Workflow Type Detail](https://github.com/SparkDevNetwork/Rock/assets/85907597/f792ede9-9a36-49ed-97f8-efeee7ad0ceb)
![Workflow File Attribute](https://github.com/SparkDevNetwork/Rock/assets/85907597/8edb2e90-5327-4660-a847-dbe88940e837)
![Workflow Form](https://github.com/SparkDevNetwork/Rock/assets/85907597/1f017cd2-f475-49a0-83ed-31a87a6be852)
![Workflow Entry Details](https://github.com/SparkDevNetwork/Rock/assets/85907597/cf2ac08a-ba19-4a14-88bc-30afd9104983)

## Person Attribute
![Person Attribute Detail](https://github.com/SparkDevNetwork/Rock/assets/85907597/1502a902-a173-4f92-a7b6-9fb74479db23)
![Person Attribute Upload](https://github.com/SparkDevNetwork/Rock/assets/85907597/793493bb-0f7a-42fd-a26d-a36fb48283d2)

### Actual Behavior

File uploads for Person Attribute and in Workflows are successful even if they don't follow the Preferred Format on the BinaryFileType.

### Expected Behavior

File uploads for Person Attribute and in Workflows should fail if they don't match the settings declared in the BinaryFileType. Initially this seemed like it might be a problem with just the Azure Blob Storage provider, but it appears to be with all files and stretching back all the way to v14.3.

I think a fix for this could either be included in the FileUploader.ashx.cs file or in the Field Type for File. Not sure where it should be included, but PreferredFormat is barely used in the codebase.

### Steps to Reproduce

1. Create a `BinaryFileType` with a PreferredFormat and Preferred Settings Required checked to true.
2. Create a `WorkflowType` with a File attribute that uses the newly created BinaryFileType.
    1. Persist the `Workflow`
3. Add a Form to the `WorkflowType`
    1. Make the File visible, editable, and required
4. Fill out the form with a file that is NOT the Preferred Format from the `BinaryFileType`.
5. The file upload is successful, despite not matching the Preferred Format.

OR

1. Create a `BinaryFileType` with a Preferred Format and Preferred Settings Required checked to true.
2. Create a `Person` Attribute with any `Category` so it is visible on the Person Profile.
3. Upload a file to the `Person` Attribute that doesn’t follow the Preferred Format from the `BinaryFileType`.
4. The file upload is successful, despite not matching the Preferred Format.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

14.3, 16.4, 16.5

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Hi @nlBayside , That old "Preferred Format" was only used by a now defunct, legacy windows application that was used to upload documents into Rock.  Regardless, we're looking into this to see if it's a feature we want to add to Rock core now.

**Comment by zackdutra** [comment]
Hey @nairdo, thank you for the explanation. It's disappointing that the setting isn't clearly documented in the block. I did just refer to the manual, and [according to the documentation](https://community.rockrms.com/documentation/bookcontent/9/303#addingdocumentsusingworkflows), the document needs to conform to the configuration, but it also notes that the file type setting may not work. Can you clarify which settings on this block we should expect to function? @nlBayside  thinks it's possible only the max file size is checked. 

The settings include:
Max File Size
Maximum Width
Maximum Height
Preferred Color Depth
Preferred Format
Preferred Resolution
Preferred Settings Required

Thank you for your help!

**Comment by nairdo** [comment]
@zackdutra Yes, those are exactly the items we're discussing -- which ones should it should possibly support, and if it is only a limited set, the tooltip for the **Preferred Settings Required** field would be updated to mention this.  

The documentation you reference is for the Workflow action for adding new documents, but this sentence might seem unclear about who is responsible (to ensure the document "you're trying to add needs to conform") but it currently means _you_, the workflow creator:
> Similarly, the document you’re trying to add needs to conform to the [File Type](https://community.rockrms.com/documentation/bookcontent/9/303#filetypes) configuration for the File Type that’s associated with the Document Type you’re using.

At the moment I would agree with @nlBayside that the FileUploader (file handler) is currently only looking at the **Max File Size** value for the binary file type (~[line 327](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/App_Code/FileUploader.ashx.cs#L327)).

I'll post an update once we've determined how we're going to proceed.

**Comment by nairdo** [comment]
To avoid future confusion, we are going to remove three of the preferred settings (Preferred Format, Preferred Resolution, Preferred Color Depth) from the BinaryFileTypeDetail block UI since these should have been removed when the Spark Document Scanner app was discontinued many years ago.  However we are going to add validation checking for Max Width and Max Height (for image files) when the **Preferred Settings Required** is enabled.

**Comment by zackdutra** [comment]
Appreciate the follow up @nairdo - for anyone in the future looking for a workaround for workflows, here's what we're doing now to validate our own files. 

- Workflow Attribute of Error Message 
- Lava Run to check for file type (or size) that stores the error message in the Error Message attribute 
- Action to return to the form if there is an error message present 
- Form Header that includes the error message if present 

The downside to this is that it can result in junk files in the database.   We may create an action to delete the rejected file as well. 

![Screenshot 2024-07-12 at 12 11 45 PM](https://github.com/user-attachments/assets/1be6c019-c4b5-4a86-87ed-2a261edec31c)
![Screenshot 2024-07-12 at 12 11 16 PM](https://github.com/user-attachments/assets/5980b10e-5058-431b-a7b9-e5e2834236f5)
![Screenshot 2024-07-12 at 12 11 03 PM](https://github.com/user-attachments/assets/9ab4e418-f5b0-47cf-b325-dfc643f9b996)
