### ISSUE TITLE
[1.16.6.1 Alpha] Breaks Mobile App Icons

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5941]
### Description

In testing v 16.6 alpha (1.16.6.1) we discovered that the tabbed menu icons in our mobile app are missing.

### Actual Behavior

Upgrading from 16.5 to 16.6 alpha breaks our mobile app icons. 

### Expected Behavior

Menu icons in mobile app would not disappear after upgrading Rock to v16.6 (1.16.6.1)

### Steps to Reproduce

1. Have a copy/instance of your production Rock at 16.5 listening at a different URL, but publicly-accessible. (For example, our production public website is https://thecrossing.church but our test copy of prod is at https://rocktest.wcrossing.org)

2. Using app switcher with the mobile app, point it at your test instance, keeping the same App Id and API key.

3. Log into mobile app and verify it looks normal. Change primary brand color and re-redeploy to verify you're pointing at the test instance.

4. Upgrade the test instance from 16.5 to 16.6alpha1 

5. Change primary color, redeploy app.

6. Use app switcher to Reset Data (clear cache) within the app, unload it and re-launch app.

7. You should be prompted to re-login, and observe that the menu icons are missing.

We stepped from a fresh copy of Production at 16.2 to 16.3, 16.4, 16.5, and finally 16.6 alpha, redeploying the app at each stage. ONLY at 16.6alpha do the mobile app icons break.

App pointing at v16.2 - 16.5:

![image](https://github.com/user-attachments/assets/ccb82724-beb5-47a9-988d-b93c2ddfcddc)

App pointing at 16.6alpha:

![image](https://github.com/user-attachments/assets/b4b2fb62-819c-4802-8d03-11130d160bf8)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.16.6.1

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Fixed in v16.6 alpha via https://github.com/SparkDevNetwork/Rock/commit/39ed1ee4367fea8006efb67e1d5846b0571fb1e7
