### ISSUE TITLE
[Alpha 1.16.6.2] No Enhanced Drop-down in Scheduled Job Detail Obsidian Block

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5942]
### Description

In the Webforms _Scheduled Job Detail_ block, the Job Type dropdown had the enhanced list functionality, allowing one to easily search for the job type they were looking for. 

In the new Obsidian _Scheduled Job Detail_ block, the Job Type dropdown is just a regular list you have to scroll through. 

v16.6 & v17.0 (Incorrect)
<img width="1722" alt="Screenshot 2024-07-15 at 20 23 35" src="https://github.com/user-attachments/assets/e38fa9c2-f20a-4439-9685-65d9f16f6888">

v16.5 (Correct)
<img width="1727" alt="Screenshot 2024-07-15 at 20 23 54" src="https://github.com/user-attachments/assets/02a0f9f7-2afd-4b5d-96a3-05e5ed30d878">

**ASLO**
This is also the case for other specific Job's settings. For example, the _Charge Future Transactions_ Job. Previously, the Receipt Email field would have the enhanced dropdown. It no longer does. There are other jobs as well that have this same behavior. 

### Actual Behavior

In the new Obsidian _Scheduled Job Detail_ block, the Job Type dropdown is just a regular list you have to scroll through to find the Job you want.

### Expected Behavior

The Job Type dropdown should be an enhanced drop down list to make searching quicker and easier.

### Steps to Reproduce

- In v16.6, go to the Jobs Administration page, and click to add a new job. 
- See the Job Type dropdown is not the nicer, enhanced type of dropdown.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6, v17.0

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@mikedotmundy 

Thanks to your incredible efforts in testing the Obsidian Scheduled Job Detail block, you've helped us identify a gap that has been solved in v16.7. As a result, we will not be chopping the block and the webform Scheduled Job Detail block will remain in v16.6.

I will be closing this issue and we will make sure to review this issue prior to releasing v16.7 for alpha testing.
