### ISSUE TITLE
[Alpha 1.16.6.2] Obsidian Scheduled Job Detail Block - Content Channel Item Self Update Issue

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5943]
### Description

This is only an issue in my v16.6 Alpha instance - it is not an issue in v17.0 on the pre-alpha site.

In the new Obsidian Scheduled Job Detail block, when selecting the Job Type _Content Channel Item Self Update_, the Content Channel field is a text field and has no option to select a Content Channel. 

<img width="1602" alt="Screenshot 2024-07-15 at 20 53 15" src="https://github.com/user-attachments/assets/9ad6a253-096f-4693-bbb8-e4ef68c87916">

### Actual Behavior

No way to select a Content Channel.

### Expected Behavior

Should be able to select a Content Channel.

### Steps to Reproduce

- Go to the Jobs Administration page and click to add a new Job.
- Select the Job Type _Content Channel Item Self Update_
- See that you cannot select a Content Channel.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@mikedotmundy 

Thanks to your incredible efforts in testing the Obsidian Scheduled Job Detail block, you've helped us identify a gap that has been solved in v16.7. As a result, we will not be chopping the block and the webform Scheduled Job Detail block will remain in v16.6.

I will be closing this issue and we will make sure to review this issue prior to releasing v16.7 for alpha testing.
