### ISSUE TITLE
[Alpha 1.16.6.2] Obsidian Scheduled Job Detail Block - Auto Open Locations Issue

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5945]
### Description

In the new Obsidian _Scheduled Job Details_ Block, when selecting the Job Type _Auto Open Locations_, you are greeted with an error `Uncaught Error Cannot read properties of undefined (reading 'value')` and the Parent Location field is missing. 

Obsidian Block:
![Screenshot 2024-07-16 at 13 09 12](https://github.com/user-attachments/assets/3e14c08c-5aa0-4a55-8f49-acfd96e8b6a3)

Webforms Block:
![Screenshot 2024-07-16 at 13 10 29](https://github.com/user-attachments/assets/7c73eefa-f6df-4cde-ab83-910d96193460)

### Actual Behavior

When selecting the Job Type _Auto Open Locations_, you are greeted with an error `Uncaught Error Cannot read properties of undefined (reading 'value')` and the Parent Location field is missing. 

### Expected Behavior

When selecting the Job Type _Auto Open Locations_, there should be no error and you should be able to select a Parent Location. 

### Steps to Reproduce

- Go to Jobs Administration
- Create a New Job
- Select the _Auto Open Locations_ Job Type
- See error and see that the Parent Location field is missing.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@mikedotmundy 

Thanks to your incredible efforts in testing the Obsidian Scheduled Job Detail block, you've helped us identify a gap that has been solved in v16.7. As a result, we will not be chopping the block and the webform Scheduled Job Detail block will remain in v16.6.

I will be closing this issue and we will make sure to review this issue prior to releasing v16.7 for alpha testing.
