### ISSUE TITLE
[Alpha 1.16.6.2] Obsidian Scheduled Job Detail Block does not Populate Name and Description

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5946]
### Description

The Obsidian _Scheduled Job Detail_ block does not auto-populate the Job Name and Description like it used to in the Webforms block. 

![Screenshot 2024-07-16 at 13 21 46](https://github.com/user-attachments/assets/3cb04168-3a2e-404e-8b93-654d7c643ce4)

### Actual Behavior

The Obsidian Scheduled Job Detail block does not auto-populate the Job Name and Description.

### Expected Behavior

The Obsidian Scheduled Job Detail block should auto-populate the Job Name and Description.

### Steps to Reproduce

- Go to Jobs Administration.
- Click '+' to add a new Job
- Select any Job Type - does not matter which.
- See the Name and Description are not auto-populated.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6, v17.0

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@mikedotmundy 

Thanks to your incredible efforts in testing the Obsidian Scheduled Job Detail block, you've helped us identify a gap that has been solved in v16.7. As a result, we will not be chopping the block and the webform Scheduled Job Detail block will remain in v16.6.

I will be closing this issue and we will make sure to review this issue prior to releasing v16.7 for alpha testing.
