### ISSUE TITLE
[Alpha 1.16.6.2] Obsidian Scheduled Job Detail Block - Charge Future Transactions Issues

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5947]
### Description

There are 3 issues with the _Charge Future Transactions_ Job in the new Obsidian _Scheduled Service Job_ Block.

1. The _Receipt Email_ field is not an enhanced dropdown. In Webforms it is.
2. The _Text to Give Failure Message_ field is a small text field. In Webforms it was a larger code-like field which allowed you to easily see the entire message.
3. The _Send SMS Response From_ field is a text field. In Webforms it allowed you to select from one of your SMS numbers in your system.

Obsidian Block:
![Screenshot 2024-07-16 at 13 36 41](https://github.com/user-attachments/assets/c8fc1363-a6ae-49f2-8fee-21420d520bef)

Webforms Block:
![Screenshot 2024-07-16 at 13 40 15](https://github.com/user-attachments/assets/3ba18b3b-dae8-4b83-ad5d-f66d191385fa)

### Actual Behavior

See above

### Expected Behavior

See above

### Steps to Reproduce

- Go to Jobs Administration
- Click '+' to add a new job
- Select the _Charge Future Transactions_ Job Type.
- See errors listed above.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6

### Client Culture Setting

en-US

**Comment by mikedotmundy** [comment]
I was incorrect with my first issue listed above. The field looks different from other "Enhanced" drop downs (the ones that have the magnifying glass on the right-hand side), however you are still able to search in the field.

**Comment by chead4** [comment]
@mikedotmundy 

Thanks to your incredible efforts in testing the Obsidian Scheduled Job Detail block, you've helped us identify a gap that has been solved in v16.7. As a result, we will not be chopping the block and the webform Scheduled Job Detail block will remain in v16.6.

I will be closing this issue and we will make sure to review this issue prior to releasing v16.7 for alpha testing.
