### ISSUE TITLE
[Alpha 1.16.6.2] Obsidian Scheduled Job Detail Block - Complete Workflows Issue

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5949]
### Description

For the _Complete Workflows_ Job Type in the Obsidian _Scheduled Job Detail_ block, you are unable to select a Workflow Type. It is just a text field.
![Screenshot 2024-07-16 at 13 53 55](https://github.com/user-attachments/assets/7e2d9607-db57-43d2-82d0-db88b2b22690)

### Actual Behavior

Cannot select a Workflow Type.

### Expected Behavior

Should be able to select a Workflow Type.

### Steps to Reproduce

- Go to Jobs Administration
- Click the '+' to add a new Job
- Select the _Complete Workflows_ Job Type
- See you cannot select a Workflow Type

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@mikedotmundy 

Thanks to your incredible efforts in testing the Obsidian Scheduled Job Detail block, you've helped us identify a gap that has been solved in v16.7. As a result, we will not be chopping the block and the webform Scheduled Job Detail block will remain in v16.6.

I will be closing this issue and we will make sure to review this issue prior to releasing v16.7 for alpha testing.
