### ISSUE TITLE
Minor Typo on Tooltip for Database Maintenance Job

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5950]
### Description

Minor typo on the tooltip for the  _Alert Email_ field for the Database Maintenance Job. This typo exists in both the Obsidian and Webform versions of this Block. 

Need to add the word "when".

![Screenshot 2024-07-16 at 14 11 24](https://github.com/user-attachments/assets/bbc15148-839d-40bd-bda9-4d97f5f1f41e)

### Actual Behavior

Alert Email Tooltip says "Email address to send alerts to errors occur..." 

### Expected Behavior

Alert Email Tooltip should say "Email address to send alerts to when errors occur..." 

### Steps to Reproduce

- Go to the Database Maintenance Job
- Hover over the Alert Email Tooltip
- See typo.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.5, v16.6, v17.0

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@mikedotmundy 

Thanks to your incredible efforts in testing the Obsidian Scheduled Job Detail block, you've helped us identify a gap that has been solved in v16.7. As a result, we will not be chopping the block and the webform Scheduled Job Detail block will remain in v16.6.

I will be closing this issue and we will make sure to review this issue prior to releasing v16.7 for alpha testing.
