### ISSUE TITLE
[Alpha 1.16.6.2] Obsidian Scheduled Job Detail Block - Data View To Workflow Issue

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5951]
### Description

In the Obsidian Scheduled Job Detail Block, for the _Data View To Workflow_ Job Type, you are unable to select a Data View. It is just a text field. 

![Screenshot 2024-07-16 at 14 16 58](https://github.com/user-attachments/assets/3d9ccbc8-73b5-4493-b542-84cda346695a)

### Actual Behavior

Cannot select a Data View

### Expected Behavior

Need to be able to select a Data View

### Steps to Reproduce

- Go to Jobs Administration
- Click the '+' to add a new job
- Select the _Data View to Workflow_ Job Type
- See you cannot select a Data View.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@mikedotmundy 

Thanks to your incredible efforts in testing the Obsidian Scheduled Job Detail block, you've helped us identify a gap that has been solved in v16.7. As a result, we will not be chopping the block and the webform Scheduled Job Detail block will remain in v16.6.

I will be closing this issue and we will make sure to review this issue prior to releasing v16.7 for alpha testing.
