### ISSUE TITLE
[Alpha 1.16.6.2] Obsidian Scheduled Job Detail Block - Group Attendance Reporting Issue

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5953]
### Description

In the Obsidian Scheduled Job Detail Block, for the Group Attendance Reporting Job Type, you are unable to select a Group Data View. It is just a text field.

![Screenshot 2024-07-16 at 14 55 32](https://github.com/user-attachments/assets/89609b89-5414-4e84-b9bf-b1cd988f8ed0)

### Actual Behavior

Cannot select a Data View

### Expected Behavior

Should be able to select a Data View 

### Steps to Reproduce

- Go to Jobs Administration
- Click the '+' to add a new job
- Select the Group Attendance Reporting Job Type
- See that you are unable to select a Group Data View

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@mikedotmundy 

Thanks to your incredible efforts in testing the Obsidian Scheduled Job Detail block, you've helped us identify a gap that has been solved in v16.7. As a result, we will not be chopping the block and the webform Scheduled Job Detail block will remain in v16.6.

I will be closing this issue and we will make sure to review this issue prior to releasing v16.7 for alpha testing.
