### ISSUE TITLE
[Alpha 1.16.6.2] Obsidian Scheduled Job Detail Block - Index Rock Site Issue

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5954]
### Description

In the Obsidian Scheduled Job Detail Block, for the Index Rock Site Job Type, you are unable to select a Site. It is just a text field.

![Screenshot 2024-07-16 at 15 27 19](https://github.com/user-attachments/assets/7626681a-b9e9-48d0-bbab-c1b9e3a8bd2a)

### Actual Behavior

Unable to select a site

### Expected Behavior

Should be able to select a site

### Steps to Reproduce

- Go to Jobs Administration
- Click the '+' to add a new Job
- Select the Index Rock Site Job Type
- See you are unable to select a Site

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@mikedotmundy 

Thanks to your incredible efforts in testing the Obsidian Scheduled Job Detail block, you've helped us identify a gap that has been solved in v16.7. As a result, we will not be chopping the block and the webform Scheduled Job Detail block will remain in v16.6.

I will be closing this issue and we will make sure to review this issue prior to releasing v16.7 for alpha testing.
