### ISSUE TITLE
[Alpha 1.16.6.2] Obsidian Scheduled Job Detail Block - Pbx Cdr Download Issue

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5955]
### Description

In the Obsidian Scheduled Job Detail Block, for the Pbx Cdr Download Job Type, you are unable to select a PBX Component. It is just a text field.

![Screenshot 2024-07-16 at 15 34 21](https://github.com/user-attachments/assets/13c2092f-56eb-4bf6-9fea-5339a39f2c93)

### Actual Behavior

Unable to select a PBX Component

### Expected Behavior

Should be able to select a PBX Component

### Steps to Reproduce

- Go to Jobs Administration
- Click the '+' to add a Job
- Select the _Pbx Cdr Download_ Job
- See that you are unable to select a PBX Component

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@mikedotmundy 

Thanks to your incredible efforts in testing the Obsidian Scheduled Job Detail block, you've helped us identify a gap that has been solved in v16.7. As a result, we will not be chopping the block and the webform Scheduled Job Detail block will remain in v16.6.

I will be closing this issue and we will make sure to review this issue prior to releasing v16.7 for alpha testing.
