### ISSUE TITLE
Weird Behavior For Content Channel View Block When On Same Page With Workflow Entry Block - Related to Captcha

### ISSUE THREAD

**Issue by stanalyst** [SparkDevNetwork/Rock#5957]
### Description

We have a page that has both a _Content Channel View_ block and a _Workflow Entry_ block. When Captcha is enabled for the _Workflow Entry_ block, after Captcha finishes verifying, the output of the _Content Channel View_ block **completely disappears from the page.**

![Captcha-1](https://github.com/user-attachments/assets/e6c8a4d9-779a-404d-8076-5de0c37dbda6)

![Captcha-2](https://github.com/user-attachments/assets/106e25c9-846c-483c-9454-b272e67f422b)

### Actual Behavior

Output from the Content Channel View block is displayed when the page initially loads, but disappears as soon as the Captcha for the Workflow Entry block finishes verifying.

### Expected Behavior

Output should NOT disappear.

### Steps to Reproduce

This is difficult to fully setup and describe - so here is a video showing the behavior.

[https://app.screencast.com/kZSItjyqjEOxv](https://app.screencast.com/kZSItjyqjEOxv)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.16.6.1

### Client Culture Setting

en-US

**Comment by cmronk** [comment]
We're seeing where it's enabled, our "Submit" buttons don't render.  I'm thinking this might be related?
