### ISSUE TITLE
Obsidian Blocks Dropdown Click-to-Select Issue with Specific Drop-down Fields

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5961]
### Description

This is a relatively minor issue - but as I have been using some of the new Obsidian blocks, it has slowed my workflow down a bit. 

Just today, I noticed this in 2 Obsidian blocks (Pledge Detail and Page Route Detail), but I have experienced it in others also. 

When an Obsidian block has a field that is a drop-down type, specifically the type where you select a Group, Financial Account, Page, etc., you cannot click-to-select like you used to in Webforms blocks. You must click what you want, then click 'Select'. 

Here is a video example of how these fields work in Webforms blocks. As you can see, I did not have to click 'Select': 
https://github.com/user-attachments/assets/12aca6dd-1460-4c06-8a9c-52d4f00f8e14

Here is a video example of how these files work in Obsidian blocks. As you can see, I did have to click 'Select':
https://github.com/user-attachments/assets/8ae2b83d-b7e7-49bd-8705-d8442a20ef27

### Actual Behavior

You can no longer click-to-select in these specific type of dropdown fields.

### Expected Behavior

It would be great if we could still click-to-select in these specific types of dropdown fields.

### Steps to Reproduce

See steps above.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6, v17.0

### Client Culture Setting

en-US

**Comment by mikedotmundy** [comment]
If you would like me to open this as an Idea, I can do that - but I wanted to put it here first since it is different from the Webform functionality.

**Comment by zackdutra** [comment]
It seems that in the webforms blocks, any of these tree style drop downs that is meant to be a single select just auto-selects and closes when you click on it, while the multi-selects don't close until you click select.
