### ISSUE TITLE
Header Buttons not Working

### ISSUE THREAD

**Issue by Brett-McCalla** [SparkDevNetwork/Rock#5965]
### Description

When I go to CMS Configuration - pages -click on a page (on our website homepage) - edit - page attribute values and click on the plus next to header buttons, it takes me back to the top of the main page before. I could not replicate on the demo site since I could not find a page that had the same options.

![button](https://github.com/user-attachments/assets/f23aa38f-7253-468a-8c92-6073d9acff48)

### Actual Behavior

When I click on the plus button next to header buttons, it takes me back to the initial page I had clicked on

### Expected Behavior

I would expect it to allow me to add a button

### Steps to Reproduce

- Go to CMS Configurations
- Click on Pages
- Click on any page that would allow a button to be placed (We were adding a button to our website)
- Click on edit
- Scroll Down to Page Attribute Values
- Click on Page Attribute Values
- Scroll Down to Header Buttons
- Click the plus button to the right to add a header button
- See error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.4 (1.16.4.4)

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@Brett-McCalla Hi Brett, To help us with our investigation, it would be helpful if you could provide full screenshots of the following: 
1.	CMS/Site: Select the site you are attempting to add the button to and select ‘Edit’
2.	Page Attributes:  select the edit pencil for each Page Attribute

**Comment by chead4** [comment]
@Brett-McCalla HI Brett I'll be closing this issue at this time as we're unable to move forward in our investigation.  Once we have more information, we can reopen the issue.
