### ISSUE TITLE
The Page Load Time option displays wrong load times for blocks

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#5968]
### Description

When using the Page Load Times to view what blocks are taking a long time to load, the load time and graph displayed for a block, is actually the time that the previous block took to load. For example, in this screenshot it is actually the "Test Block" that took 5 seconds to load and not the "DotLiquid Warning" block:

![image](https://github.com/user-attachments/assets/24968d15-9728-4cd6-a0c5-d874d68b56a9)

### Actual Behavior

Time displayed for block to load is actually the time it took for previous block to load

### Expected Behavior

Time and chart accurately reflect the correct block

### Steps to Reproduce

- Go to Home Page
- Add HTML Block above the 'DotLiquid Warning' block on the home page
- Set the HTML Contents of the block to the following (Also make sure you enable the SQL lava command for the block)
```
{% sql %}
WAITFOR DELAY '00:00:05'
SELECT 'Done'
{% endsql %}
```
- Save Changes
- Refresh Page
- Click the 'Page Load Time' button in the admin tool bar
- Notice that the test block shows fast load time, but the next block shows load time of 5+ seconds

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.2

### Client Culture Setting

en-US

**Comment by zackdutra** [comment]
We are experiencing the same issue. It's been an issue for several years, we just haven't had time to report it.  We're currently on 16.4, though it was present in 14 and 15 also.
