### ISSUE TITLE
Rock Default Contribution Statement Template has deprecated CurrencySymbol Lava

### ISSUE THREAD

**Issue by bmurphy-dev** [SparkDevNetwork/Rock#5969]
### Description

The Rock Default statement template is still using the deprecated `CurrencySymbol` and not using the current `| FormatAsCurrency` filter. Most churches use this Rock Default template as a basis for their initial custom templates by copy/pasting the code here as a starting point.
[Here is the initial migration](https://github.com/SparkDevNetwork/Rock/blob/b455f334f4162c360cbdb45f65ed8bd37e01a45c/Rock.Migrations/Migrations/Version%2012.0/Version%201.12.4/202105280103566_StatementGenerator_RockDefaultTemplate.lava#L193) that inserted this new statement template.
Correcting this Rock Default template will require a new migration with these code changes --> [Here is a diff of the code needed in the migration](https://www.diffchecker.com/fS5UvqJM/)
What's kind of odd is that this was being deprecated the same time this new template system was being issue in v12.4 on the move to v13 according to the [Technical Release Notes Changelog](https://community.rockrms.com/developer/changelog#m12.4).
> Currency - 4/15/2021
> A new "OrganizationStandardCurrencyCode" global attribute has been implemented (and is used by the FormatAsCurrency Lava filter, as such usage of the older "CurrencySymbol" global attribute is now deprecated starting with v13.
> Use the CurrencyBox.Value property when setting the value of a currency (not the .Text property). It will also handle formatting the currency symbol as needed.

### Actual Behavior

The amount fields rendered in the statements do not format correctly with `,` thousands separators.
Example of fields missing the separators: 
![image](https://github.com/user-attachments/assets/9ec13c83-6ae2-4017-8912-53a18a78d398)

### Expected Behavior

The lava in this Rock Default template be up to current standards and display currency values in a sensible manner.

### Steps to Reproduce

- Go to Finance - Financial Settings - **Contribution Templates**
- Click on the **Rock Default** template row and then the **Edit** button
- Scroll down to the **Report Template** field
- See deprecated lava. Correcting this Rock Default template lava will require a new migration with these code changes --> [Here is a diff of the code needed in the migration](https://www.diffchecker.com/fS5UvqJM/)
- [https://www.rocksolidchurchdemo.com/finance/settings/contribution-templates/1](https://www.rocksolidchurchdemo.com/finance/settings/contribution-templates/1)
- [https://prealpha.rocksolidchurchdemo.com/finance/settings/contribution-templates/1](https://prealpha.rocksolidchurchdemo.com/finance/settings/contribution-templates/1)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v13.0 and up

### Client Culture Setting

en-US

**Comment by bmurphy-dev** [comment]
I'm sure this also affects the actual currency symbol depending on an instance's culture settings but someone else would have to test that.

**Comment by PraveenMathew92** [comment]
We have updated the template in v16.7 of Rock. The link to the commit that resolves this issue will be posted here tomorrow. Closing the issue for now.
