### ISSUE TITLE
First Name Validation Does Not Work

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5971]
### Description

I'm not sure if this is a bug, or if it was a planned feature that was never implemented, but according to [this idea](https://community.rockrms.com/ideas/1681/first-name-validation), validation to prevent `&` and `and` from being entered into the First Name field of several blocks was implemented, all the way back in v14. This does not appear to work in current or future Rock versions.

### Actual Behavior

On blocks like _AccountEntry_ or _Group Registration_, I am still able to enter things like `Jack & Jill` or `Jack and Jill` into the First Name field, contrary to what the Idea Complete note says.

### Expected Behavior

Trying to determine if this is buggy behavior, or if the statement that it was being implemented in v14 never actually happened... but I'd expect to not be able to enter `and` and `&` on pretty much any block that solicits a First Name field.

I did not check every block stated to have been updated in that Idea, but I assume it's not implemented anywhere based on the couple of tests I did, and does not seem to be implemented in any of the new Obsidian blocks.

### Steps to Reproduce

1. On https://prealpha.rocksolidchurchdemo.com go to the public site
2. Go to Group Connect | Small Groups and search for any group and click Register.
3. Enter `Jack & Jill` in the First Name field, fill out the rest of the form
4. Submit it and observe no validation error was presented and the person is now in the db.
5. Same thing with going to https://prealpha.rocksolidchurchdemo.com/NewAccount and submitting the form with `&` or `and` in the First Name. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.5, 17.0

### Client Culture Setting

en-US

**Comment by kfrazier13** [comment]
I can confirm this is also an issue in 15.4 on the Transaction Entry (V2) Block

**Comment by karenn-ccbc** [comment]
I am wondering if this change is what has affected the Search by first name option in Name Search? After updating from v16.6 to 16.8 I have found that you can no longer search a Name by first name using ", Karen". Searching in the Universal Search option does allow you to search by first name ( without the comma before it). Just wondering if this was an intended change?

**Comment by JimMichael** [comment]
@karenn-ccbc Thanks for pointing this out! I hadn't noticed yet, but our **,firstname** style searches are indeed broken in 16.8. Should probably be entered as a new issue.
