### ISSUE TITLE
Simple Editor Exposes ALL System Phone Number To Users That Have Rights to NO Phone Numbers

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5973]
### Description

We noticed a major problem with the New Communication | _Use Simple Editor_ functionality. If a person with access to Internal Rock (e.g. Staff Worker or Staff Like Worker) HAS rights to any (at least one) SMS Phone Number, they will ONLY see the phone number(s) they have View rights to in the _From_ drop-down when sending a SMS communication (via the Simple Editor). This is the expected behavior.

However, if they happen to have NO View rights to ANY SMS Phone number, instead of seeing "nothing" (no number to choose) in the _From_ drop-down, they see  **every SMS phone number in the system.**

### Actual Behavior

Simple Editor exposes *all system phone numbers* to users that otherwise have no View rights to *any* phone numbers.

### Expected Behavior

Rock would hide phone numbers from users that don't have any rights to them. 

### Steps to Reproduce

I have duped this in Prealpha:

1. Add a new System Phone number called _Secured to Staff_ and set its rights to Staff workers View, Rock admin View, then All Users Deny.

2. Edit default _Test SMS_ phone number and set its View rights to Rock Admin View then All Users Deny. (thus making this number only visible to Rock admins.)

3. Give Frank Decker Staff Workers role.

4. Log in as Frank Decker and go to People | New Communication | Use Simple Editor.

5. Click SMS tab and observe that the only number he sees is the _Secured to Staff_ one, as that's the only number he currently has View rights to. This is the correct expected behavior.

6. Now go remove Staff Workers from the _Secured To Staff_ phone number (leaving Rock Admin View  and All Users Deny.)

7. Repeat steps 4-5 and observe that instead of seeing NO phone number to choose (because you don't have View rights to any SMS number), you instead see BOTH the _Secured to Staff_ and _Test SMS_ numbers, both of which should only be visible to Rock Admins at this point.

8. Scream.

![image](https://github.com/user-attachments/assets/d9c3f58d-7ef9-450f-8f7c-b0f56f48c790)

![image](https://github.com/user-attachments/assets/84feb306-0bb8-4d76-a476-ec909c7d2e17)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.2+

### Client Culture Setting

en-US

**Comment by JimMichael** [comment]
For anyone reading this that wants/needs a workaround in your environment, we just added a fake/unusable SMS Phone number with this name, secured to Staff Workers role. This makes the rights "work" as everyone has View right to at least one number again.
![image](https://github.com/user-attachments/assets/eab7c3c4-b54f-4ac9-bf0e-8ff0f0a476b4)

**Comment by chead4** [comment]
@JimMichael Hi Jim - Thanks for reporting this issue. I was able to recreate the issue. However, I'll be closing this issue as the Communication Entry block is being rewritten into the Next Generation framework in v17.

**Comment by chead4** [comment]
@JimMichael Hey Jim - I just wanted to provide an update that we have confirmed that this issue is resolved on the Communication Entry Obsidian block on the new framework.
