### ISSUE TITLE
Group Type Attribute View Security

### ISSUE THREAD

**Issue by aaronjones8** [SparkDevNetwork/Rock#5974]
### Description

When creating a group type attribute and setting the view security permissions to deny attribute is still visible on the Group Viewer. A church wanted to create an internal notes attribute for the group type that is only visible to Rock Admin and Staff Worker 

### Actual Behavior

Attribute is visible when logged in to an account that is not in the required role

### Expected Behavior

Attribute should not be visible

### Steps to Reproduce

- Create Group Attribute on Group Type and set the view security
![image](https://github.com/user-attachments/assets/75277613-0798-49c2-97c4-32611ff24522)

- view group with user in RSR - Staff Like Worker role
![image](https://github.com/user-attachments/assets/b43ed013-6e85-421c-b988-766978628552)

- Internal Notes attribute is visible

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.5

### Client Culture Setting

en-US

**Comment by aaronjones8** [comment]
@jacksojourn

**Comment by chead4** [comment]
@aaronjones8 For Group Types, the Group View Lava Template under Display Options is used by the Group Details block when viewing a group.  Once you have set security for Group Attributes, update the Group View Lava Template to use the HasRightsTo filter. This filter will check the security of the model passed.  (You can find more details on that filter [here](https://community.rockrms.com/lava/filters/other-filters#hasrightsto).

Update the Group View Lava Template to include the following (which can be seen in lines 51 to 59 of the screenshot), which will check security before displaying the Group Attributes on the Group Details block. 

```Liquid
        <dl>
        {% for attribute in Group.AttributeValues %}
            {% assign viewAuth = attribute.AttributeId | HasRightsTo:'View','Rock.Model.Attribute' %}
            {% if attribute.ValueFormatted != '' and viewAuth %}
                <dt>{{ attribute.AttributeName }}</dt>
                <dd>{{ attribute.ValueFormatted }}</dd>
            {% endif %}
        {% endfor %}
        </dl>      
```
![chrome_ldGr1pIARd](https://github.com/user-attachments/assets/10ed9a16-8773-430b-97e6-76e1d59a2246)

Thank you for reporting this, I'll be closing this issue and we will be also be updating the Rock Your Groups documentation.
