### ISSUE TITLE
Marital Status Defaults to Married

### ISSUE THREAD

**Issue by jasminevchacko** [SparkDevNetwork/Rock#5976]
### Description

When using Person Entry on a form in a workflow, the Marital Status field defaults to 'Married' when you **do not** choose the option to autofill the current person. 

### Actual Behavior

The Marital Status field defaults to 'Married' instead of blank when you do not select the option to autofill the current person. I created a test workflow on the demo site [here](https://rock.rocksolidchurchdemo.com/page/136?WorkflowTypeId=26). 

![Screenshot 2024-07-31 at 5 15 27 PM](https://github.com/user-attachments/assets/57ce5685-104d-47ac-9131-35f8eb06a5d1)
![Screenshot 2024-07-31 at 5 15 44 PM](https://github.com/user-attachments/assets/ae9e1089-436f-4bd8-bee4-d26be1e20619)

### Expected Behavior

The Marital Status field should default to blank rather than a specific value. 

### Steps to Reproduce

- Navigate to Workflow Configuration and create a new workflow. 
- Add a Form action to the workflow. 
- Enable Person Entry. 
- Uncheck 'Autofill Current Person' 
- Choose 'Optional' for Marital Status. 
- Create a person attribute and set it to the 'Person' field in the Form action. 
- Save the Workflow. 
- Hit the Play button to navigate to the workflow entry page. 
- The Marital Status field will default to 'Married'. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.5

### Client Culture Setting

en-US

**Comment by asdf1nit** [comment]
I have been investigating an issue and just found this. We are seeing thi issue in v18.2 I can duplicate this on the demo server(18.2.4) as well. We were on 17.6 prior to our update and have records that indicate that this was heppening pre v18.

@chead4, @nairdo   should I open a new issue or can this one be reopened?

**Comment by jonedmiston** [comment]
@asdf1nit can you please open a new issue.
