### ISSUE TITLE
RSVP Detail UI Bug

### ISSUE THREAD

**Issue by zackdutra** [SparkDevNetwork/Rock#5978]
### Description

When saving a Location in the Group RSVP block, the location will save, but the UI Location attribute will not reflect the change, it stays blank when viewed again to edit.  Reproduced on both demo site (16.2) and our own (16.4). 

### Actual Behavior

The Location selector is not showing the saved Location value. 
<img width="480" alt="Screenshot 2024-08-02 at 10 25 07 AM" src="https://github.com/user-attachments/assets/58edfa32-20c1-4e12-a5d4-7c3eeaa9bf35">
<img width="977" alt="Screenshot 2024-08-02 at 10 26 02 AM" src="https://github.com/user-attachments/assets/e5d6b9b9-ab10-435b-a261-a44e21c1eeef">

### Expected Behavior

The Location selector should show the currently saved Location. 

### Steps to Reproduce

- Go to the demo site and enable the RSVP feature on a group type. In this case I enabled it on the General Group group type. 
- Create a Group of that type
- Click on the RSVP button to add an RSVP occurrence 
- Fill in details, including location. 
- Save and then come back to the edit page. 
- See that Location value is not showing when editing, even though before clicking edit you can see its value. You can also see its value by checking the AttendanceOccurrence using SQL. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.2,16.4

### Client Culture Setting

en-US

**Comment by zackdutra** [comment]
As a side note, I could swear this was happening with Schedule also on our instance. I had to save it twice for it to stay. I could not reproduce that.

**Comment by nairdo** [comment]
We ran into this recently and this was fixed in v16.7 via https://github.com/SparkDevNetwork/Rock/commit/e4dbd6310735745d5071f5a48e004da391424622

**Comment by zackdutra** [comment]
Thanks @nairdo !
