### ISSUE TITLE
1st of Schedule Preference Auto-Scheduling Issues

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5980]
### Description

Auto-scheduling individuals with a 1st of schedule preference (i.e. first Sunday) will incorrectly auto-scheduled after the 7th day in each calendar month. Instead of not being scheduled, individuals with a 1st of scheduling preference will be scheduled in the first remaining day (i.e. Sunday) available.

### Actual Behavior

Individuals are auto-scheduled on days outside their preference.

### Expected Behavior

Individuals are only scheduled on days matching their preference.

### Steps to Reproduce

On the demo site complete the following after the first Sunday of the month but before the second Sunday passes:
1) Update Ted Deckers Preference to 1st and 3rd Week
![image](https://github.com/user-attachments/assets/46f18cb4-7e9f-40c3-86b0-f0510078944f)
2) Navigate to a page with the new obsidian group scheduler with the [following settings](https://rock.rocksolidchurchdemo.com/page/1554?GroupIds=110&LocationIds=&ScheduleIds=3&RangeType=Next&TimeUnit=Week&TimeValue=6&LowerDate=&UpperDate=)
![image](https://github.com/user-attachments/assets/73eea289-dcf8-49cf-9609-e8d9ebfe3efc)
![image](https://github.com/user-attachments/assets/b0b4eac7-1d73-4a4d-a2db-dbd706d50f0d)
Note: Our schedule is currently blank with no volunteers scheduled
3) Press the auto schedule button and see issue
![image](https://github.com/user-attachments/assets/90c50bbb-09ab-413c-8682-ff60a2e6a105)
Note: Ted Decker was scheduled for the second and third Sunday of August. He should have only have been scheduled for the third Sunday in August. Months after August are being scheduled correctly.
 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.5

### Client Culture Setting

en-US

**Comment by dataCollegechurch** [comment]
In my personal system I have also seen individual with other schedule preferences i.e. (just 3rd or 4th Sunday) scheduled outside their preference when there is an open slot in first active week of a month.

**Comment by dataCollegechurch** [comment]
Grateful for you @jasonhendee, thank you for the thoroughness as you evaluated the underlying issue and thought through how to build a fix that wouldn't break other existing features

**Comment by jasonhendee** [comment]
Thank you for the kind words, Tony! This issue (and the other open iCalendar issue: [Calendar Event Recurrences "by Specific Date" fail to Export](https://github.com/SparkDevNetwork/Rock/issues/5150)) are certainly challenging us to think outside the box, especially since active development of [iCal.NET](https://github.com/rianjs/ical.net) - which Rock uses under the hood - appears to have stalled out in the last few years.

Thanks also for bringing this issue to our attention, and for providing an easily-reproducible example!
