### ISSUE TITLE
Connection Request Badge Bar Disappears on Page Refresh/Reload

### ISSUE THREAD

**Issue by treusch** [SparkDevNetwork/Rock#5983]
### Description

When viewing a connection request that contains only one badge based on Entity Type "Person" and Badge Type "Steps" in the badge bar, if you refresh the page or if you launch a workflow from the available workflow buttons and the page refreshes when the workflow finishes, the badges that are displayed disappear. (If you include any other badge too, for example Connection Status badge, the badge bar does not disappear on refresh.)

On initial page load of the Connection Request, you can see the badge bar in the red box in the screenshot below:
![image](https://github.com/user-attachments/assets/2e0ecc8a-88c2-4b2d-9a83-f2e21b1dbdbd)

Simply refreshing the page causes the badge bar to disappear as seen in the screenshot below:
![image](https://github.com/user-attachments/assets/d91fba57-c4da-4866-a8cb-dc5d1c53c170)

### Actual Behavior

Badges disappear when the connection request page is refreshed/reloaded if the only badge being displayed is a Person/Steps badge.

### Expected Behavior

Badges would not disappear on refresh/reload of the page no matter which badges were chosen to be displayed. The Badges would stay the same if no data had changed or would update if information had changed since the page was initially loaded.

### Steps to Reproduce

1. Create a badge that is based on Person as the entity and Steps as the Badge Type. Pick an existing Step Program
![image](https://github.com/user-attachments/assets/57145d87-7df4-4987-b971-dd6a4a484153)

2.  Edit the block settings in the Connection Request Board Block on the Connection Board page (demo site page: https://rocksolidchurchdemo.com/page/2635?ConnectionOpportunityId=3) to include only the new badge you created in step 1.
![image](https://github.com/user-attachments/assets/c64f32b4-7b2a-4f0c-aad6-090a6a1625e9)

3. Click on one of the cards in the board and see that the badge displays for the person.
![image](https://github.com/user-attachments/assets/64d717d0-c429-4b19-8a20-8cb889fa19d4)

![image](https://github.com/user-attachments/assets/91c61bb3-9314-425a-815a-aa0aa26b571f)

4. Refresh the page and the badge disappears.

![image](https://github.com/user-attachments/assets/f507f210-cbbd-49f2-963b-1668de0fa7d1)

5. Close the modal form that contains the connection request and click on the card again and the badge reappears.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.5

### Client Culture Setting

en-US

**Comment by treusch** [comment]
Not sure if these additional screenshots would be helpful. Feel free to delete them if they are not. :)

![image](https://github.com/user-attachments/assets/e182166e-495c-4cdb-9d5a-460b72425e24)

![image](https://github.com/user-attachments/assets/b941c6e2-050a-478d-bc98-b21b0555f90b)

**Comment by chead4** [comment]
@treusch  Thank you for providing these screentshots. I will add them to our internal ticket as they may assist dev with our investigation.
