### ISSUE TITLE
Transaction Entry v2 Block Date Picker

### ISSUE THREAD

**Issue by JustBenjamin** [SparkDevNetwork/Rock#5984]
### Description

In the Transaction Entry V2 block, the Date Picker field is currently assigned as text type `<input type="text">` instead of date type `<input type="date">` . As a result, the date selection on mobile is happening with a web style calendar control instead of a more streamlined mobile date control.

### Actual Behavior

Actual Behavior

<img width="524" alt="Screenshot 2024-08-12 at 11 59 14 AM" src="https://github.com/user-attachments/assets/0c5c567c-2107-4b84-babc-3d9f9ee0f212">

<img width="316" alt="Screenshot 2024-08-12 at 11 58 06 AM" src="https://github.com/user-attachments/assets/1a2e3866-7d59-4b30-b859-98a96ab61e2a"> 

### Expected Behavior

Expected Behavior
<img width="626" alt="Screenshot 2024-08-12 at 12 15 35 PM" src="https://github.com/user-attachments/assets/1cdae6c6-b1a4-4687-8499-c3471d03bd5e">

<img width="201" alt="Screenshot 2024-08-12 at 12 14 56 PM" src="https://github.com/user-attachments/assets/64a312b7-ef46-4941-8633-3cbc1dbf5907">

### Steps to Reproduce

- Go to a page with the Transaction Entry V2 block (a gateway may be needed in the environment in order to view the page with the block).
- Click on the date picker
- Inspect the element

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.5 (1.16.5.4)

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@JustBenjamin That be an issue for us to implement.  Currently our datePicker controls use the input `type="text"` and build their own date picker UI.  If we were to try to use `type="date"` the browsers would take over and try to do their own thing as seen here:

<img src="https://github.com/user-attachments/assets/d9fdb1c7-35cf-451a-a72c-5b822db014a0" width="250" />

Can you describe what issue you're wanting to fix with our custom datePicker control?

**Comment by edwerd** [comment]
@nairdo I think the concern here is that the support for the custom datePicker is fairly weak on a mobile device. The calendar often gets cut off or is hard to press on mobile devices. I understand you used the custom date picker for a larger range of supported browsers however in 2024 this far less of an issue. On a block that is responsible for a church's primary giving, I worry that not using the native datepicker is reducing the overall user experience and to some degree the total giving itself.
