### ISSUE TITLE
Person report with a 'Photo' select field causes exception

### ISSUE THREAD

**Issue by mkinyon** [SparkDevNetwork/Rock#5985]
### Description

Viewing a person report that includes a photo select field causes the following exception:

```
There was a problem with one of the filters for this report's dataview.
Property 'System.String Html' is not defined for type 'Rock.Model.Person'
```

The exception says that the issue is with the data view, but this can happen with or without a data view attached to the report. 

### Actual Behavior

Exception occurs.

### Expected Behavior

The report to load.

### Steps to Reproduce

- Go to Tools > Reports and create a new report.
- Set 'Applies To' to Person
- Add a Photo field
- Save report and see exception.

Here is an existing example in the prealpha environment:
https://prealpha.rocksolidchurchdemo.com/reporting/reports/5

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16, prealpha

### Client Culture Setting

en-US

**Comment by jonrob08** [comment]
Closing this issue with the following commit for future reference - https://github.com/SparkDevNetwork/Rock/commit/b1f6fd5260e3c335b3ba67b39158f7ed24c65ba3
