### ISSUE TITLE
LocationTypeValueId not populated or incorrect when expanding from Group

### ISSUE THREAD

**Issue by jimmyhogoboom** [SparkDevNetwork/Rock#5988]
### Description

Hello! I'm seeing some strange behavior which might be a bug. I hope I'm reporting this correctly and with enough information. Please let me know if I can provide any further details!

I noticed that `LocationTypeValueId` is missing or incorrect when queried via the /Groups endpoint. When querying via /GroupLocations directly, the `GroupLocationTypeValueId` is the expected value, and the correct value is also shown in the Rock UI.

### Actual Behavior

Querying the /Groups endpoint using `$expand` of "GroupLocations/Location" and `$select` of "GroupLocations/Location" returns all address information, except the `LocationTypeValueId` is always `null`. Strangely enough, in my development installation, this value is actually always `19` ("Home" address) even when the address shows in Rock as "Previous".

### When querying via /Groups
<img width="459" alt="Screenshot 2024-08-20 at 4 02 41 PM" src="https://github.com/user-attachments/assets/1352921f-6d73-49ca-bb28-f219fb242fac">

### When querying via /GroupsLocations
<img width="452" alt="Screenshot 2024-08-20 at 4 02 56 PM" src="https://github.com/user-attachments/assets/f260c705-3ce4-47cc-8992-3732e12797a2">

### Expected Behavior

Expected the `LocationTypeValueId` to match the address type shown in Rock or when querying via the /GroupLocations endpoint. 

### Steps to Reproduce

- Go to https://rock.rocksolidchurchdemo.com/
- In the search bar, type "Ted Decker"
- Click the first person result 
<img width="462" alt="Screenshot 2024-08-20 at 4 14 52 PM" src="https://github.com/user-attachments/assets/95f89bfb-1068-4e1e-8d2b-46bdba765c84">

- Scroll down and click the Edit button (pencil) on the "Decker Family" 
<img width="327" alt="Screenshot 2024-08-20 at 4 18 56 PM" src="https://github.com/user-attachments/assets/25722fbb-b5d6-438f-bb86-cb996a6db8cc">

- Scroll down, add a new address with Type of "Previous" if it doesn't already exist
<img width="798" alt="Screenshot 2024-08-20 at 4 20 02 PM" src="https://github.com/user-attachments/assets/22b20231-ec44-4ac3-8a41-cfba2c7bd137">

- Go to the Groups endpoint on the API page at https://rock.rocksolidchurchdemo.com/api/docs/index#!/Groups/GETapi_Groups
- Query with `$expand` and `$select` values of "GroupLocations/Location" and `$filter` value of "Id eq 68" 
<img width="451" alt="Screenshot 2024-08-20 at 4 25 00 PM" src="https://github.com/user-attachments/assets/a8d1028d-86b6-4ac6-a76b-2c0f305d1350">

- Note that the value of "LocationTypeValueId" for both Locations is `null`.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.6 (1.16.6.9)

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@jimmyhogoboom Thanks for reaching out. I believe the value you’re looking for is the GroupLocationTypeValueId, which is included in the API results.
 
The UI currently is displaying the GroupLocationTypeValueId which is associated with the family’s GroupLocation. This ID is always populated when a Group is involved (e.g., Family, Small Group, etc.) with a Location (a GroupLocation).
 
On the other hand, only Named Locations such as Campuses, Buildings, and Rooms will have a value in the Locations LocationTypeValueId field.

**Comment by jimmyhogoboom** [comment]
Thank you for taking the time to look at this @chead4, I really appreciate it!

I apologize for my misunderstanding but especially for my hubris. I could have used the time I spent on this issue more deeply exploring the possibility of an error in my own code 😅
