### ISSUE TITLE
Auto Watch Note Sending Notifications for Original Note Text to Authors

### ISSUE THREAD

**Issue by zackdutra** [SparkDevNetwork/Rock#5994]
### Description

Notes created through the Person Note Add workflow action are causing the Send Note Notifications job to send notifications for notes with no replies.  

### Actual Behavior

Notes created through the Person Note Add workflow action are causing the Send Note Notifications job to send notifications for notes with no replies.    The resulting email is just showing the author's original note text, not replies. 

### Expected Behavior

Expected behavior is that only notes with replies are included on the email from the Send Note Notifications job. 

### Steps to Reproduce

This cannot be reproduced on demo due to email not being configured there. 

1. Configure the General note type to Allow Watching, Auto-Watch Authors, and Allow Replies. 
2. Create a workflow that includes a Person Note Add step.  In our case we have it as a a Person action so the workflow is triggered from the actions menu on the person profile. The action has Author set to the Current Person and Alert set to no. 
3. Configure the person bio block to display this workflow as an option in the actions menu. 
4. Ensure that the Send Note Notifications job is enabled.
5. Using the normal TimeLine block from the Person page, add a General note. 
6. Run the Send Note Notifications job. No email is sent because that note had no replies. 
7. Using the person actions menu, trigger the workflow that adds a note to the profile.  
8. Run the Send Note Notifications job. An email is sent even though there are no replies. 

There is a visual difference on the timeline between the two notes. The ones created from the workflow action show the eye symbol to indicate that they are being watched, whereas the ones from the timeline do not.  This could be related to [issue 5790](https://github.com/SparkDevNetwork/Rock/issues/5790) but it says fixed in 16.6, and we are on 16.6. 

I'm having difficulty narrowing down exactly what the issue is here, but at the end of the day it might just be that auto-watched notes are sending notifications for the author's original note. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6

### Client Culture Setting

en-US

**Comment by nlabarbera** [comment]
Got it, thanks for the heads up! 💪🏽 We’re taking a look and will keep you in the loop.

**Comment by zackdutra** [comment]
Hey @nlabarbera or @chead4 would you be able to provide an update on this one? I have a user who receives notifications for every note she puts in, and she leads call campaigns so she's getting way too many.

**Comment by chead4** [comment]
@zackdutra Hi Zack This issue is in our dev pipeline to be fixed. I'll discuss it with Nathan when he returns on Wednesday and share an update afterward.

**Comment by chead4** [comment]
@zackdutra Hi Zack  This issue will be resolved in our next release v16.7.
