### ISSUE TITLE
Office365 Login Button Not Appearing

### ISSUE THREAD

**Issue by mstjulio** [SparkDevNetwork/Rock#5995]
### Description

The Office365 Login Button is not appearing after upgrade to v16.6

### Actual Behavior

<img width="1348" alt="Screenshot 2024-09-01 at 9 32 10 AM" src="https://github.com/user-attachments/assets/c9694719-ed45-42b1-98bc-c5398b2f83be">

The Office 365 Login Button is missing.

### Expected Behavior

The Office 365 Button Should be Visible.

The button should be clickable and redirect to the Office365 login

### Steps to Reproduce

Enter the Internal Database to Login.

Missing Office365 Login button.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6

### Client Culture Setting

en-US

**Comment by mstjulio** [comment]
Found the issue after diving into the Obsidian Blocks.

**Comment by nlabarbera** [comment]
@mstjulio Nice work  - glad you were able to locate it 💪🏽
