### ISSUE TITLE
Registration Wait List Transition Email: Grammar Issue

### ISSUE THREAD

**Issue by trfouger** [SparkDevNetwork/Rock#5996]
### Description

The defaulted text in the Wait List Transition Email of a Registration template, has a small grammatical issue.  It indicates that the registrant has been moved to a 'full **person**' as opposed to a 'full **registration**'.  The variable used in the defaulted code is using the templates {{ RegistrationInstance.RegistrationTemplate.**RegistrantTerm** }} and should be using the {{ RegistrationInstance.RegistrationTemplate.**RegistrationTerm** }} instead. 

### Actual Behavior

When mom "Sarah" got her email that son Benjamin had been moved from the Wait List, the statement reads as follows:  "Sarah, the following individuals have been moved from the Kids TIME | Bentonville Fall 2024 PM wait list to a full person. 
![WaitListTransitionEmail](https://github.com/user-attachments/assets/fec61f51-c7c8-42c2-8b0b-1313002bf328)

### Expected Behavior

The email should read as follows: "Sarah, the following individuals have been moved from the Kids TIME | Bentonville Fall 2024 PM wait list to a full **registration**. 

### Steps to Reproduce

Go to **Registration Template** and create a new Template with the Wait List Option selected. Before even saving this new template, scroll down and click on the **Show Communication Settings** checkbox, and then scroll down and expand the **Wait List Transition Email** section. The default code is as follows, with the term in question highlighted. 

It is on line 8 of the defaulted Email Template. The code should reflect 
{{ RegistrationInstance.RegistrationTemplate.**RegistrationTerm** | Downcase }} instead. 

![WaitListCodeDefault](https://github.com/user-attachments/assets/2d599af9-b674-4705-841b-0b856809bff9)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.4 for sure, but I believe it may have been this way for a while. 

### Client Culture Setting

en-US

**Comment by sparkdevnetwork-service** [comment]
@trfouger Thanks for sending over this enhancement request. At this time, we're focusing on many high priority features and bug fixes, so we will not be moving forward with this request.  

In the meantime, in an Event Registration in the Term/Text section you will find the Registrant Term (Person) and a Registration Term (Registration).  

In the Wait List Confirmation message on line 8 if you update RegistrantTerm to RegistrationTerm the wording in the email will be updated from full person to full registraton.
Line 8 current: {{ RegistrationInstance.RegistrationTemplate.RegistrantTerm | Downcase }}.
Line 8 update: {{ RegistrationInstance.RegistrationTemplate.RegistrationTerm | Downcase }}.

![chrome_gj3FA26AYg](https://github.com/user-attachments/assets/1f370d4a-d10c-4552-bd27-c2d152763f9a)

![image](https://github.com/user-attachments/assets/934194b6-b9bf-4ff4-a92a-abad27380ceb)


**Next Steps:** This issue will be closed but we encourage you to submit an idea on the Rock Community Ideas board at https://community.rockrms.com/ideas-changes. This allows the full community to speak into the idea and help us determine its priority.

Thank you again for the submission and for helping to make Rock better.
