### ISSUE TITLE
Obsidian event registration cost validation error with $1000+ cost

### ISSUE THREAD

**Issue by andypullen** [SparkDevNetwork/Rock#5997]
### Description

When an event costs more than $1000 and the Minimum Initial Payment field is populated, the payment validation presents the error "Amount To Pay Today must not be more than $1". This is an issue on 16.6 and the prealpha (17) server at least.

The validation function looks to be given a `currencyInfo` object that outputs the string "$1,000" for a $1000 event registration, which then gets reformatted as `1`.

![Screen Shot 2024-09-04 at 11 09 13@2x](https://github.com/user-attachments/assets/ae6f37cb-586a-4d38-9202-422bdcbe8bbc)
![Screen Shot 2024-09-03 at 14 54 49](https://github.com/user-attachments/assets/e5ebcef0-b524-4c5d-9cf8-595fd4f425b8)

### Actual Behavior

The payment validation gets thrown off by the comma in the thousands separator.

### Expected Behavior

The payment validation function should be given a number instead of a string so that it doesn't include a dollar sign or thousands separator.

### Steps to Reproduce

- Create an event with a cost of $1000 or more
- Set the Minimum Initial Payment so that the payment validation is enabled
- Try registering and paying for the event

An example event has been set up with this issue at https://prealpha.rocksolidchurchdemo.com/Registration?RegistrationInstanceId=6.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6+

### Client Culture Setting

en-US

**Comment by atodd66** [comment]
I just posted this same issue, only in my example, it will not accept less than $2. I've discovered that it is based on the total amount. Ex: $1,000 = $1, $2,000 = $2, $3,000 = $3, etc.

**Comment by andypullen** [comment]
> I just posted this same issue, only in my example, it will not accept less than $2. I've discovered that it is based on the total amount. Ex: $1,000 = $1, $2,000 = $2, $3,000 = $3, etc.

Yep— it looks to me like it translates the string it's given into a number, taking whatever is to the left of the comma.

**Comment by atodd66** [comment]
I posted this as an update in the Troubleshooting channel. Registration payment ARE working if you switch back to the legacy Registration Entry block. Confirmed working on the demo site.

**Comment by zackdutra** [comment]
Just confirming we’re seeing this also, but it is not an issue when the minimum payment is not set / requiring the full amount upfront.

**Comment by chead4** [comment]
@zackdutra Thank you for the additional details Zack.
