### ISSUE TITLE
Registration payment validation fails if a percentage discount is applied to a partial dollar amount

### ISSUE THREAD

**Issue by RufenachtPW** [SparkDevNetwork/Rock#5999]
### Description

If you have a registration cost or fee that is a partial dollar amount, ex. $9.99, and you apply a discount that is a percentage, ex 50%. On the registration this cost becomes $5. When you go to add a payment of $5, I am using the process manual payment for testing, the validation fails saying the payment amount is greater than the amount due. The issue on the RegistrationDetails block is on line 1057 even though the fix probably should be on the Balance Due function. What is happening is the the Balance Due function is returning $4.999 as in the above example. The block show $5 which is correct but the validation uses the $4.999 as validation on line 1057. Therefore $5 is greater than $4.999 so they payment is not allowed.

https://github.com/SparkDevNetwork/Rock/blob/b7b861e62607d275b655f66668c402c3d88386a1/RockWeb/Blocks/Event/RegistrationDetail.ascx.cs#L1057

### Actual Behavior

Payment amount validation fails because the round amount ($5) is greater than the actual balance due.

### Expected Behavior

The balance due should be rounded up to the nearest 2 decimal places. 

### Steps to Reproduce

Go to the summer camp registration on the demo site. 
Change a t-shirt cost from $10 to $9.99
Add a registration with the discount code that has a percentage discount. On the site this shows as 50% discount. 
Add a registrant with the $9.99 t-shirt fee. 
Note the cost of the registration shows as $5
Try to add a manual payment for $5 and see the validation error. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.5

### Client Culture Setting

en-US

**Comment by nlabarbera** [comment]
Thanks for the heads up - looking into this.
