### ISSUE TITLE
Communication Wizard Doesn’t Provide a Method For Switching from Asset to File for Images

### ISSUE THREAD

**Issue by FrankGrand** [SparkDevNetwork/Rock#6002]
### Description

When using the communication wizard, adding an image block to a message, and then setting that image to
an asset doesn’t provide any means to unset the asset and change to some other image from an uploaded file
if so desired. Trying to do so results in unexpected behavior where the editor may show the asset or the
uploaded file but if any image is sent, it will be the asset.

### Actual Behavior

The asset can’t be removed.

### Expected Behavior

It should be possible to remove an asset image after it has been selected.

### Steps to Reproduce

Begin a communication from the people menu.
In the editor make sure there is an image area at the top, like this:
![image](https://github.com/user-attachments/assets/9a36e94f-7f37-41bf-9f3c-1eadbf638c5a)
If the image is set to an uploaded file, the red x in the lower right corner of the box where the image was set
allows for removing the file.
![image](https://github.com/user-attachments/assets/24eecdb5-9c0e-4551-bd73-c61e27c9d79e)
Adding an image via the Asset tab will add one but there is no way to remove it. It is possible to switch to
another asset but not to remove the asset without putting another in its place.
![image](https://github.com/user-attachments/assets/fdf83904-ad4b-4e5d-9dae-2da78088d24c)
Switching back to the Image tab and uploading a file will make it look like the asset has been replaced by the
uploaded file. The below screenshot is the same communication as the others previously.
![image](https://github.com/user-attachments/assets/35f1c38b-afa1-419f-900e-78745d17e550)
Clicking preview – the preview shows the uploaded image, it’s possible to see in the background that the
editor has reverted to showing the last asset.
![image](https://github.com/user-attachments/assets/87775563-60ef-4f90-b9b7-3523b627ff3d)
It’s clear when the preview is closed that the uploaded image is still there but not showing in the message.
When the message is sent it will arrive showing the asset.
![image](https://github.com/user-attachments/assets/f4a89962-ec73-48e8-bf11-d2256d456bdf)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.16.6.6, 1.16.6.9,1.17.0.26

### Client Culture Setting

en-US

**Comment by joshuahenninger** [comment]
@FrankGrand Thank you for bringing this issue to our attention. We have made updates to the Communication Entry Wizard block to address the problem. You will now be able to seamlessly switch between an asset and an uploaded file, with the image displayed and sent accurately reflecting the selection in the editor.

This fix will be included in the upcoming v16.7 release.
