### ISSUE TITLE
Content Channel Security

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#6007]
### Description

Content Channels do not seem to default with 'Rock Admin' as the top security role allowed. They inherit their security from Content Channel Types... but we don't seem to have access to update Content Channel Type security in our UI.

### Actual Behavior

In the attachments, you can see that when you build a new content channel, the channel inherit's permissions from the content channel type. But you will also see in the second screen shot that there is no ability to update the content channel type security.

![Content Channel](https://github.com/user-attachments/assets/7fd52357-6522-4607-bb72-9cc1172b23b2)

![Content Channel Type](https://github.com/user-attachments/assets/d15aeab7-050b-4042-b492-dbf3ce23076e)

### Expected Behavior

I would expect to be able to update the security settings of a content channel type.

### Steps to Reproduce

- Go to Admin Tools
- Click on CMS Configuration
- Click on Content Channel Types
- Notice that you can not update the security of each type.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.5

### Client Culture Setting

en-US

**Comment by shauncummings** [comment]
@jcjones37 individual Content Channel Types do not have security settings in Rock.  Instead, what you're seeing here are the permissions inherited from the Entity Type, which you can edit from Security > Entity Administration.

<img width="1043" alt="image" src="https://github.com/user-attachments/assets/9984a53c-a53e-4f69-b8d5-2325db259dc9">

I understand your confusion on this, but if the security privileges are inherited from a specific entity (e.g., a specific Content Channel Type) its name would be present in the section you highlighted in purple.

Please be aware that any edits you make at the Entity Type level will apply to all Content Channels of all Content Channel Types.
