### ISSUE TITLE
Fluid Shortcodes are limited to at most one parameter set to a variable value

### ISSUE THREAD

**Issue by jamrphy-bwd** [SparkDevNetwork/Rock#6008]
### Description

Consider 

```liquid
{% assign var1 = '123' %}
{% assign var2 = '456' %}

{[ someshortcode a:var1 b:var2 ]}
{[ someshortcode b:var2 a:var1 ]}
```
On Fluid, only the first of the above parameters is set per call to the shortcode.

### Actual Behavior

In Rock.Lava/Core/Shortcodes/DynamicShortcode.cs, the method SetParametersFromElementAttributes successfully parses each variable, but breaks on the first success:

```C#
private void SetParametersFromElementAttributes( Dictionary<string, object> parameters, string elementAttributesMarkup, ILavaRenderContext context )
        {
            // Resolve any Lava merge fields in the element attributes markup.
            var resolvedMarkup = _engine.RenderTemplate( elementAttributesMarkup, LavaRenderParameters.WithContext( context ) );

            //... skipping lines setting literal params ...

            var variableTokens = Regex.Matches( resolvedMarkup.Text, @"\w*:\w+" )
                .Cast<Match>()
                .Select( m => m.Value )
                .ToList();
            
            foreach ( var item in variableTokens )
            {
                var itemParts = item.Trim().Split( new char[] { ':' }, 2 );
                if ( itemParts.Length > 1 )
                {
                    var scopeKey = itemParts[1].Trim();
            
                    var scopeObject = context.GetMergeField( scopeKey, null );
            
                    if ( scopeObject != null )
                    {
                        parameters.AddOrReplace( itemParts[0].Trim().ToLower(), scopeObject );
                        break; //<-- Why this break?
                    }
                }
            }
        }
```

Removing the break sets all variables properly.

... is there some reason for this break?

### Expected Behavior

Every variable param should be set.

### Steps to Reproduce

- Create a shortcode that displays the value of at least 2 passed parameters
- In Lava Tester, create two variables. Use those variables as the value of parameters passed to the created shortcode.
- See only the first parameter has a value within the shortcode's context.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.5

### Client Culture Setting

en-US

**Comment by stanalyst** [comment]
I can confirm this issue ... posted a question about it in the Lava channel (just didn't have a chance to post the bug here) ... https://chat.rockrms.com/channel/lava?msg=Zjgp4hhwJ4JZcJ7Z7

**Comment by chead4** [comment]
@jamrphy-bwd After taking another look, I realized I had missed adding the {[ end test ]} tag to my lava test initially. Once added, I am not able to recreate the issue on the prealpha site. Could you provide a bit more detail and check if you're able to recreate it on the prealpha site? 

**Input:**
```
{% assign var11 = '123' %}
{% assign var21 = '456' %}
 
{[ test a:var1 b:var2 ]}{[ endtest ]} <br>
{[ test b:var2 a:var1 ]}{[ endtest ]}
```
**Output:**
var1: 123 var2: 456
var1: 123 var2: 456

**Comment by stanalyst** [comment]
I was just able to reproduce this in prealpha.

Created a new shortcode called - 'testmultiple' -> https://prealpha.rocksolidchurchdemo.com/admin/cms/lava-shortcodes/21

used lava tester to call it and verify behavior...  (Person was set to Ted Decker and CurrentPerson was Alisha Admin)
```
{% assign firstObject = Person %}
{% assign secondObject = CurrentPerson %}
 
{[ testmultiple objecta:firstObject objectb:secondObject ]}
{[ endtestmultiple ]}
```
objecta showed the Person entity that was passed - but objectb was an empty string

then flipped the order of the parameters in the call ...
```
{% assign firstObject = Person %}
{% assign secondObject = CurrentPerson %}
 
{[ testmultiple objectb:secondObject objecta:firstObject ]}
{[ endtestmultiple ]}
```
and now objecta is an empty string and objectb is the CurrentPerson entity that was passed

**Comment by chead4** [comment]
@jamrphy-bwd Thank you for taking the time to recreate on prealpha.  It was a great help to us.
