### ISSUE TITLE
CurrentPerson merge field not available in Group Finder block

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#6011]
### Description

This _feels_ like a bug to me, but I could be wrong. Letting you all decide. :shrug

When using Lava in the Formatted Output block setting for the Group Finder block, the Current Person merge field is not available.

Use case: we have created our own "Northside U" Course Finder (I know LMS is coming, timelines just didn't work). We are showing upcoming courses where registration hasn't opened yet. I am using reminders to allow someone to add a reminder so they get notified when registration opens. I want to change the icon / tooltip on the reminder itself if someone has a reminder set for that specific registration. The only way I can access someone's existing reminders is if the block knows who the Current Person is.

### Actual Behavior

The `CurrentPerson` merge field is not available in the lava template of the Group Finder block

### Expected Behavior

I would expect to have access to the `CurrentPerson` merge field in the Group Finder lava template.

### Steps to Reproduce

- On the demo site, go to the [Small Groups page](https://rock.rocksolidchurchdemo.com/page/236)
- Edit the block
- Scroll down and expand the Lava section
- Check the _"Show Formatted Output"_ box
- In the Lava Template box, use the following code:
```
<div class="alert alert-info">
    {{ CurrentPerson.FullName }} is actually empty :(
</div>
```
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/1bd15f66-dc5d-4660-a1f1-d888f73b08f4">

- Notice how the CurrentPerson merge field is not available and outputting as expected
<img width="1397" alt="image" src="https://github.com/user-attachments/assets/91af0b58-b0c8-4182-a05c-5865bcc9c5ce">

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.6 (1.16.6.9)

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@leahjennings Hi Leah.  Thanks for reaching out. After checking the Lava Debug Info (`{{ 'Global' | Debug }}`), on the Group Finder block, I noticed that the CurrentPerson merge field isn't available on this block.  

I'll go ahead and close this issue, but feel free to reach out if you have any questions.

**Comment by leahjennings** [comment]
@chead4 I confirmed that as well. Does that mean this is considered an enhancement instead of a bug? I am fine if that's the answer, just looking for clarity.

I will say, I do believe as a Lava developer it's become very common to expect CurrentPerson to be available. If this is considered an enhancement, it would be great if the Lava template tooltip or documentation could be updated with that information.

Thank you!

**Comment by chead4** [comment]
@leahjennings Hi Leah - Yes, this would be considered an enhancement.  I suggest submitting an idea on the Rock Community Ideas board via https://community.rockrms.com/ideas-changes.

**Comment by chead4** [comment]
@leahjennings Hi Leah - We revisited this issue this morning and have reopened it.  We'll have this fixed in an upcoming release.
