### ISSUE TITLE
Dates in steps not respecting culture settings

### ISSUE THREAD

**Issue by camattard** [SparkDevNetwork/Rock#6012]
### Description

![step-culturesettings-versionnumber](https://github.com/user-attachments/assets/87f848b4-d8bb-47c5-b861-952967c20f6d)

The date formatting on the step when hovering over the step respects the culture settings of the browser.
![step-hover](https://github.com/user-attachments/assets/f17ab679-4e46-41d2-bbed-43d40a87869e)

However when not hovering over the step the date shown does not respect the culture settings of the browser.
![step-nohover](https://github.com/user-attachments/assets/2d4d1399-ba6b-4e87-b4bd-f46606d05ee3)

### Actual Behavior

The date on the step when not hovering over the step does not show the date in format as per Client Culture Settings.

### Expected Behavior

The step date should respect the client culture settings.

### Steps to Reproduce

- Go to 'Steps' on a person's profile
- Scroll to steps and not hover over the step.
- Date is formatted incorrectly, not respecting culture settings.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.6 (1.16.6.9)

### Client Culture Setting

en-AU

**Comment by kylehenning** [comment]
Hi Cameron,

Thank you for reporting this issue! We’ve addressed it in version 16.7 by updating the default Lava card template to use the "sd" date format, which automatically returns the standard shortened date format for the user’s culture.

Additionally, if you need to customize the format further, you can manually update the Lava template in the "Card Content Lava Template" section [documented here](https://community.rockrms.com/documentation/bookcontent/39/297#editingsteptypes:~:text=With%20Workflows%20manual.-,Advanced%20Settings,-The%20Advanced%20Settings).
