### ISSUE TITLE
Ask Chip not working for me

### ISSUE THREAD

**Issue by Brett-McCalla** [SparkDevNetwork/Rock#6014]
### Description

It gives me the error widget.getcody.ai sent an invalid response

![{D6CAA828-92F2-4904-A4FD-A26349E76B1B}](https://github.com/user-attachments/assets/da5d08da-52d5-42e3-9147-f614ac5056ec)

### Actual Behavior

It gives me the error widget.getcody.ai sent an invalid response

![{D6CAA828-92F2-4904-A4FD-A26349E76B1B}](https://github.com/user-attachments/assets/6ccc9eea-e0f2-4225-9fc0-8761119eb634)

### Expected Behavior

I should be able to ask chip a question and get a response

### Steps to Reproduce

- Go to https://community.rockrms.com/askchip
- see error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.4 (1.16.4.4)

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@Brett-McCalla Hi Brett - I haven't been able to recreate the error in Ask Chip.  I'll be closing this issue for now, but if you continue to experience an error, feel free to reach out.

**Comment by Brett-McCalla** [comment]
Hello Colleen,

I am still not able to access ask chip. My security software says that the widget.getcody.ai is phishing.

Is there a url that goes with the plugin that I could whitelist to allow it through our system?

Thanks!

Brett McCalla<http://www.prairielakeschurch.org/>
IT Coordinator
Central Services
Prairie Lakes Church<http://www.prairielakeschurch.org/>
Office: 319.266.2655
Extension: 319-305-0822
Cell: 319-464-7255

**Comment by chead4** [comment]
@Brett-McCalla Hi Brett - I will get back to you shortly.

**Comment by chead4** [comment]
@Brett-McCalla Hi Brett - Please try adding *.getcode.ai to your security software and see if it helps resolve the issue.

**Comment by Brett-McCalla** [comment]
I am not sure if you did something on your end of things but it is now working on our end and we did not have to enter the *.getcode.ai to our software.

Thank you!

Brett McCalla<http://www.prairielakeschurch.org/>
IT Coordinator
Central Services
Prairie Lakes Church<http://www.prairielakeschurch.org/>
Office: 319.266.2655
Extension: 319-305-0822
Cell: 319-464-7255

**Comment by chead4** [comment]
@Brett-McCalla Thanks for getting back to me, I am happy to hear it is working for you now.
