### ISSUE TITLE
Issue with registering a person via the Event Calendar Item Personalized Registration block

### ISSUE THREAD

**Issue by mkinyon** [SparkDevNetwork/Rock#6015]
### Description

(Submitted on behalf of CCV)

Staff at CCV use the **Event Calendar Item Personalized Registration** block to register people on their behalf for various events such as starting point.
![image](https://github.com/user-attachments/assets/5cf1b3d9-311b-4971-ab2b-b93de55668fd)

After upgrading to v16.6, they now get a null reference exception when they click on `Start Registration`.
![image](https://github.com/user-attachments/assets/f25255a8-5a6c-416c-b620-ee6c8d456763)

I dug into this and what happens is the registration context returns null because the person who started the registration (the staff member/current user) is not the same as the registrar (the person they are signing up). 

https://github.com/SparkDevNetwork/Rock/blob/9884673d81347dd125f5de8cbc0c70021ba37efd/Rock.Blocks/Event/RegistrationEntry.cs#L3537-L3541

https://github.com/SparkDevNetwork/Rock/blob/9884673d81347dd125f5de8cbc0c70021ba37efd/Rock/Model/Event/Registration/RegistrationService.cs#L182-L187

### Actual Behavior

The following exception is thrown:

> at Rock.Blocks.Event.RegistrationEntry.GetInitializationBox(RockContext rockContext) in \Rock.Blocks\Event\RegistrationEntry.cs:line 3307
>    at Rock.Blocks.Event.RegistrationEntry.GetObsidianBlockInitialization() in \Rock.Blocks\Event\RegistrationEntry.cs:line 213
>    at Rock.Blocks.RockBlockType.GetObsidianBlockInitializationAsync() in \Rock\Blocks\RockBlockType.cs:line 206
>    at Rock.Blocks.RockBlockType.GetBlockInitializationAsync(RockClientType clientType) in \Rock\Blocks\RockBlockType.cs:line 177
>    at Rock.Blocks.RockBlockType.d__52.MoveNext() in \Rock\Blocks\RockBlockType.cs:line 491
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Rock.Blocks.RockBlockType.d__50.MoveNext() in \Rock\Blocks\RockBlockType.cs:line 431
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Rock.Web.UI.RockBlockTypeWrapper.<>c__DisplayClass6_0.<b__0>d.MoveNext() in \Rock\Web\UI\RockBlockTypeWrapper.cs:line 73
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Web.UI.PageAsyncTaskManager.d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Web.UI.Page.d__554.MoveNext()

### Expected Behavior

Hopefully to be able to register someone on their behalf.  Either that, or we need to update the **Event Calendar Item Personalized Registration** block to make the Current User the registrar.

### Steps to Reproduce

To hopefully save some time, I created a page on pre-alpha:
https://prealpha.rocksolidchurchdemo.com/page/829?PersonGuid=8fedc6ee-8630-41ed-9fc5-c7157fd1eaa4&EventItemId=7

1) Create a new page and add the **Event Calendar Item Personalized Registration** block
2) Edit the block settings and configure the Registration Page setting.
3) load the page by passing in a Person Guid and an Event Item Id (Note: the personguid needs to be someone different than the current user)
4) Click Start Registration.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6, pre-alpha

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@mkinyon Hi Mason Unfortunately, prealpha was just updated with a new version and the page you created is no longer there.  I haven't been able to recreate the issue on the demo site (v16.6) and may have missed a step or configuration.  Can you include a  screenshot of the Event Calendar Item Personalized Registration block settings?

**Comment by mkinyon** [comment]
Hi @chead4 ! Here is new link you can use on prealpha:
https://prealpha.rocksolidchurchdemo.com/page/817?PersonGuid=8fedc6ee-8630-41ed-9fc5-c7157fd1eaa4&EventItemId=2

The PersonGuid in this case is [Ted Decker](https://prealpha.rocksolidchurchdemo.com/Person/4) and the [Event Item Id](https://prealpha.rocksolidchurchdemo.com/web/calendars/2/event/2) is for the example car show event/registration. 

Once you open the link, all you need to do is click on the Start Registration button:
![image](https://github.com/user-attachments/assets/a06d9aec-8d41-42c0-b8e3-5014705f0ac6)


Also, here is a screenshot of the block settings.  Everything is set to default except for the registration page which is configured to point to the default external registration (obsidian) page:
![image](https://github.com/user-attachments/assets/812bba64-fe7f-48c8-a13a-55feb29d0a88)

Let me know if you have any questions.

**Comment by sparkdevnetwork-service** [comment]
@mkinyon Thanks for getting back to me.  The screenshot helped as I had my block setting for Registration Page set differently.
