### ISSUE TITLE
iPad Check In App Not Prompting Location

### ISSUE THREAD

**Issue by zackdutra** [SparkDevNetwork/Rock#6023]
### Description

The Check-In block properties have a setting to Enable Location Sharing.  From a web browser on my laptop, this triggers the tryGeoLocation function from Admin.ascx https://github.com/SparkDevNetwork/Rock/blob/68ec5a15bba4b540bb94f229741a56a5ad8852bf/RockWeb/Blocks/CheckIn/Admin.ascx.cs#L423 

On an iPad however, nothing happens. Instead, I get a blank screen with "Check In Options" at the top, and a Retry button that does nothing. 

### Actual Behavior

The app never prompts for allowing location access. 

### Expected Behavior

I would expect to get a prompt requesting location access. 

### Steps to Reproduce

- Go to CMS Configuration  > Pages > Check-In > Admin
- Open the check in block properties 
- Scroll down to Enable Location Sharing and set it to Yes. 
- Save the new setting. 
- From a web browser, visit the check in page and you will be prompted to enable location services if not already enabled. After which, you will see it check your location and redirect you to a welcome page. 
- From an iPad, reload the check in app (or re-install it for a fresh install). After loading the admin screen, you will be shown a blank Check-in Options screen. No location is requested. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6

### Client Culture Setting

en-US

**Comment by zackdutra** [comment]
The two location options in settings for this app are Never and When I Share. However, that is a much shorter list than other apps on the iPad that allow you to use Always or While Using the App. On investigating, that appears to be something the developer has to set up.

**Comment by cabal95** [comment]
@zackdutra This has been fixed and will be in the next release of the iPad check-in app. I don't have an exact ETA on this as there is some check-in v2 related testing that needs to happen before we release. I believe the iPad app version will be 1.11.0, but don't make me swear to it. :)

**Comment by zackdutra** [comment]
Thanks @cabal95 !

**Comment by zackdutra** [comment]
Hey @cabal95 just checking if you know of the release date yet on this one? Thanks!

**Comment by cabal95** [comment]
Not a specific date, but it is currently in testing alongside Rock 16.7. It should go out roughly the same time as 16.7 if no issues are found.

**Comment by cabal95** [comment]
@zackdutra We have released this version of the check-in app. It is version 1.11.0 in the App Store.
