### ISSUE TITLE
Attendance Analysis display individual days w/in date range?

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#603]
I checked in today with a  couple of groups that had the 4:30 test schedule and 6:30 schedule. The attendance analysis shows the date as 10-26 whereas the database has it logged as 10-24. I know they are group by week, month and year options but is it possible to add one for days within the date range? If not, we can always use reports. I'm just thinking about activities that go on throughout the week and even VBS week.

**Comment by cabal95** [comment]
@edmistj Is this even possible with the attendance analytics block to add an option to "group" by day in addition to week, month and year?

**Comment by edmistj** [comment]
It gets complex as a lot of attendance is looked at from a Sunday date perspective. We've had another request for day though so it's being considered and matched against other priorities.

**Comment by edmistj** [comment]
➤ Jon Edmiston commented:

Test

**Comment by jonedmiston** [comment]
@BEGamache if this is still desired can you add it as an Idea where people can vote on it to help us prioritize it.
