### ISSUE TITLE
Signature Document page takes a long time to load or times out.

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#6034]
### Description

Reported on behalf of The Father's House

The Father's House has 30 Signature Document Types and 9,471 Signature Documents. When trying to view the Signature Document page under Admin Tools > General Settings, the page consistently times out or takes over a minute to load. 

After debugging code, the timeout appears to be due to how block is currently getting the number of signature documents for each signature document type. 

We temporarily modified the block with following change and the page then loaded instantly. 

![image](https://github.com/user-attachments/assets/3f2d9963-6235-4ee5-8fc1-b9cf13d60ef2)
(also added using statement for System.Data.Entity)

These are page load times before and after that change (the change was made at 12:20)

![image](https://github.com/user-attachments/assets/5ba16454-3177-4a2c-a93e-34960f471029)

### Actual Behavior

Signature Document page fails to load due to timeout.

![image](https://github.com/user-attachments/assets/add4e774-917e-4ada-aee6-70617f62551f)

### Expected Behavior

Signature Document should not timeout.

### Steps to Reproduce

Hard to reproduce on new system as it appear to only manifest if there are thousands of signature documents.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.4

### Client Culture Setting

en-US

**Comment by azturner** [comment]
After submitting, realized this may have already been addressed here:
https://github.com/SparkDevNetwork/Rock/commit/930288f873448cb95fa3a3c5ca20cd2aadf3cf70

**Comment by azturner** [comment]
I confirmed that the fix made here: https://github.com/SparkDevNetwork/Rock/commit/930288f873448cb95fa3a3c5ca20cd2aadf3cf70 does fix The Father's House issue. 

This issue can be closed.

**Comment by chead4** [comment]
@azturner Thanks David.  I will close the issue.
