### ISSUE TITLE
Create New Account-Disable Duplicate Checking for the Following Protection Profiles Setting Not Enforced

### ISSUE THREAD

**Issue by kimlongcr** [SparkDevNetwork/Rock#6036]
### Description

On the new Account Creation obsidian block, there are two items not working correctly.
1 - In Security Settings, the Disable Duplicate Checking for the Following Protection Profiles is not being enforced. We have Extreme checked for this setting and it is still prompting for a duplicate when I create a new account. 
2 - When it does find the duplicate the informatiion displayed on the duplicate screen is not enough information for ANYONE to confirm if that is them or not. It's just a masked first name and the last name. 
<img width="946" alt="OLD ONE" src="https://github.com/user-attachments/assets/b0cfae5b-abd1-4d8e-825e-bff264459949">
<img width="727" alt="NEW ONE" src="https://github.com/user-attachments/assets/87cb02d1-ae07-4d27-ba04-15111fa1aff4">

### Actual Behavior

When I try to create a new account for person in Rock who is a Rock admin, it is prompting me and asking if I am the same person as the person with Rock admin security role (extreme protection profile). 

### Expected Behavior

I would expect that it would just create a new account in pending status in Rock until the person confirms their email address. 

### Steps to Reproduce

- Go to 'Security Settings and set the Disable Duplicate Checking for the Following Protection Profiles set to Extreme (check it). Save it.
- Make sure you have a user account that has an Extreme security role (Rock Admin security role is an easy one). 
- Go to the new obsidian block account creation screen
- Enter a new user id but an existing first name, last name and email address
- Click on Create ---> it will display the user that exists and ask if you are the same person or not

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.6 (1.16.6.9)

### Client Culture Setting

en-US

**Comment by PraveenMathew92** [comment]
Fixed as part of https://github.com/sparkdevnetwork/rock/commit/85a1f5e8deca42957ce82bd4f30fceadaf7f1c4a

**Comment by chead4** [comment]
@kimlongcr Hi Kim Thank you for submitting this request! After reviewing, I recommend submitting an idea for issue 2 to add options that make it easier to identify a potential duplicate account on the New Account block. 

Please submit an idea on the Rock Community Ideas board at [Rock Community Ideas](https://community.rockrms.com/ideas-changes). This enables the whole community to weigh in and helps us prioritize it effectively.
