### ISSUE TITLE
RSVP Groups have stopped allowing me to update/change my GroupMemberStatus

### ISSUE THREAD

**Issue by sheatipton** [SparkDevNetwork/Rock#6037]
### Description

I am only able to fill out an RSVP response form one time to update my group member status.
example: I accepted the RSVP to join this group, but when filling it out a second time to Decline, my GroupMemberStatus stayed active.

<br><img width="1512" alt="Screenshot 2024-10-14 at 2 57 10 PM" src="https://github.com/user-attachments/assets/981307c4-3501-4896-bd02-5feea43dc8b2"><br>

However, the actual RSVP response DID change correctly to Decline inside the RSVP Occurrence, but is just not matching up with the GroupMemberStatus.

<br><img width="1512" alt="Screenshot 2024-10-14 at 2 57 03 PM" src="https://github.com/user-attachments/assets/6cdd2075-23d0-4e1e-aa03-f2fdddd3b186"><br>

Note: This issue is happening both ways. Declining first will keep my GroupMemberStatus Inactive, even if I go back and Accept the RSVP response.

### Actual Behavior

Actual Behavior: When I re-fill out an RSVP form, my RSVP detail response updates accordingly, but my GroupMemberStatus **_stays the same_**.

### Expected Behavior

Expected Behavior: When I re-fill out an RSVP form, my RSVP detail response **_+ my GroupMemberStatus_** updates accordingly

### Steps to Reproduce

-Create a test RSVP group [here](https://rock.rocksolidchurchdemo.com/people/groups?GroupId=41&ExpandedIds=41).
-Generate the RSVP link and Decline.
-Check your GroupMemberStatus (should be Inactive).
-Fill out the RSVP link again, but Accept.
Check your GroupMemberStatus (stays inactive, but should be active).

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.5 (1.16.5.4) + the ROCK demo site.

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@sheatipton Hi Shea - After reviewing, I found that when a member declines an RSVP, their group membership status isn't automatically updated. The decline simply means they won't be attending the event, but their overall group status remains unaffected unless an admin updates it manually or through a separate workflow. 

At this time, I will be closing this issue. We welcome you to share your feature/idea with us on the [Rock Community Ideas & Core Changes board](https://community.rockrms.com/ideas-changes). This allows the full community to speak into it and help us determine it's priority.
