### ISSUE TITLE
Changing Group Type settings in Check-in Configuration deletes Inherited Group Type setting

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#6039]
### Description

When a Group Type has an "Inherited Group Type" setting, that setting is deleted if the Group Type is edited on the Check-in Configuration page. 

We have created a parent group type with a bunch of group attributes that get inherited to a few child group types. We have "lost" that inheritance multiple times without changing the group type explicitly. We finally nailed down the issue to when you change the group type in the Check-in configuration page.

### Actual Behavior

When editing a Group Type from the Check-in Configuration page, the Inherited Group Type is deleted. 

### Expected Behavior

I would expect to be able to edit a Group Type on the Check-in configuration page without it affecting what is set in the Inherited Group Type field.

### Steps to Reproduce

- On the demo server, navigate to Admin Tools > General Settings, then click on Group Types
- Click the + to create a new Group Type
- Set the Inherited Group Type to `Serving Team`, then click `Save`
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/43e83ae9-5b55-4a20-a16e-198c8609bd00">

- Back on the list of Group Types, click to edit **Volunteer Check-In**
- Add the new Group Type as an Allowed Child Group Types, then Save
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/027e5571-b304-4ef5-a9d6-a9b4610f9641">

- Go to Admin Tools > Check-In, then click on the Volunteeer Check-In area
- In the Areas and Groups section, click on the newly added Group Type (in this example, it's `Inherits Serving Team`
- Change the Check-in rule to **Already Belongs** then Save
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/97ccddf4-b689-49d0-9f6f-2ddaa50b9cde">

- Navigate back to Admin Tools > General Settings, then click on Group Types
- Click on the new group type (`Inherits Serving Team` in this example)
- Expand **General**
- Notice how the **Inherited Group Type** setting is now empty
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/8a73238c-e85d-4aa6-953c-22a31309ea96">

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.6 (1.16.6.9), Rock McKinley 16.4 (1.16.4.4)

### Client Culture Setting

en-US

**Comment by nlabarbera** [comment]
Hey @leahjennings - thanks for reporting this!
