### ISSUE TITLE
One Click Unsubscribe not triggering when clicked from email 

### ISSUE THREAD

**Issue by Adam-BEMA** [SparkDevNetwork/Rock#6040]
### Description

When the "Unsubscribe" button is clicked, navigation occurs to the email preferences page, instead of the One Click Unsubscribe. This is a compliance risk. This behavior happened from Outlook as well as in a client's Mailtrap.
![image](https://github.com/user-attachments/assets/5b3a04d8-96f1-4172-89dc-1a0be35b7b68)
![image](https://github.com/user-attachments/assets/0551c63f-3762-460a-9b6b-4ee1edb37042)

### Actual Behavior

When a user clicks the Unsubscribe button in an email, they are being taken to the email preferences page.

### Expected Behavior

When a user clicks the Unsubscribe button in an email they are unsubscribed from communications without additional feedback required.

### Steps to Reproduce

This is difficult to reproduce on the demo site, as the emails are locked down. However, on a fresh install of v16.6 with a valid SMTP provider configured:
1. Navigate to Admin ->Communications ->Communication Mediums
2. Inspect the Email settings.
3. Confirm "Enable One-Click Unsubscribe" is set to "Yes"
4. Create a simple communication that uses a template with the Unsubscribe Option. 
5. Target a user with an accessible email address.
6. Ensure that Bulk Communication is selected
7. Send the Communication
8. Upon receipt of the communication, click the unsubscribe button from your email handler of choice.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@Adam-BEMA Hi Adam - After taking a look, it seems the unsubscribe link that you are mentioning is in the footer of the email.  

Just to clarify a couple of things about the unsubscribe link: 
1. The unsubscribe link in the footer follows an older method, which directs recipients to the Rock Unsubscribe page on the external site.
2. The one-click unsubscribe button is shown near the subject line in most email clients, and is displayed/hidden according to the rules of each email client. 

Can you confirm that there is an unsubscribe link near the subject line and when selected unsubscribes the person?

**Comment by nlabarbera** [comment]
Hey @Adam-BEMA - looking into this a little more, the 'Unsubscribe' option in the footer is different than 'One-Click Unsubscribe'.  This was updated due to the way `Get` and `Post` requests were handled. Looks like we will need to update our Documentation from when this change was made in June. 

For reference: https://github.com/SparkDevNetwork/Rock/issues/5770#issuecomment-2146106629

**Comment by Adam-BEMA** [comment]
Understood, thank you for your attention to this report. :)

**Comment by chead4** [comment]
@Adam-BEMA Thanks for your understanding.  I'll be closing this issue at this time and have created an internal task to update our documentation.
