### ISSUE TITLE
Obsidian Dynamic data, when sorted by column is duplicating rows

### ISSUE THREAD

**Issue by kwishard88** [SparkDevNetwork/Rock#6043]
### Description

When using the Obsidian Dynamic data block, when you go to use any column to sort the rows it ends up duplicating the row instead, when you refresh the page it goes back to the original list view without the duplicates. 

### Actual Behavior

When you hit to sort button it will sort the rows of data but will also duplicate some rows. 

### Expected Behavior

When you sort the list it should sort in order of the column, but not add any new rows into the list. 

### Steps to Reproduce

1. Create a page with the obsidian Dynamic data block. 
2. I added this SQL into the List to pull a list of giving.

`SELECT
    p.Id,
    FORMAT(ft.[TransactionDateTime], 'yyyy-MM-dd', 'en-US') AS "Transaction Date",
    ftd.Amount AS "Gift Amount",
    fa.[Name] AS "Account Name"
FROM
    FinancialTransactionDetail ftd
JOIN 
    FinancialTransaction AS ft ON ft.Id = ftd.TransactionId
JOIN 
    PersonAlias AS pa ON pa.Id = ft.AuthorizedPersonAliasId
JOIN 
    Person AS p ON p.Id = pa.[PersonId]
JOIN 
    FinancialAccount AS fa ON fa.Id = ftd.[AccountId]
`
3. Save the Page settings. 
4. Go to sort the list by "Gift Amount". 
5. You can see that it starts to duplicate the rows. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@kwishard88 I wasn't able to reproduce duplicate rows displaying when sorting the Gift Amount column on the demo site (v16.6) or on prealpha. I confirmed the number of rows that should return by running the same SQL through the SQL Editor. However, I did notice that the sorting of the 'Gift Amount' column on the obsidian Dynamic Data block isn't working correctly.

It would be greatly appreciated if you could include screenshots of the duplicate rows that are returned and confirm if you can recreate the issue on the demo site.

**Comment by kwishard88** [comment]
@chead4 If you go to this page on the Prealpha site. 

https://prealpha.rocksolidchurchdemo.com/page/833

This is where I made the test page. 

When I sort the gift amount and hit the sort button about 3-4 times you can start to see the UI Will Duplicate in the table. 

You can see this when you need to scroll down your page to see them. 

I'll add a screen shot
![Screenshot 2024-10-22 at 12 33 19 PM](https://github.com/user-attachments/assets/71adb774-da60-406f-aa51-36bbcece0f10)

**Comment by chead4** [comment]
@kwishard88 Thanks so much.  That is very helpful.

**Comment by kwishard88** [comment]
@kylehenning thanks for fixing this!
