### ISSUE TITLE
Workflow Person Entry Form overwrites current values if field left blank.

### ISSUE THREAD

**Issue by cjfountain** [SparkDevNetwork/Rock#6044]
### Description

When _Enable Person Entry_ option is selected on the Form Builder or Workflow Action Type "Form", an existing value for mobile phone or email will be overwritten if the field is optional and left blank when the form is submitted.

### Actual Behavior

Actual Behavior

A person profile with both mobile phone and email.

![Snip - Person Entry overrides attributes to blank - Google Chrome](https://github.com/user-attachments/assets/e50dc7d3-6d2e-4e22-9079-1d87d61b7d0a)

A person entry form with one field optional

![Snip - Person Entry overrides attributes to blank - Google Chrome (2)](https://github.com/user-attachments/assets/9c2a94df-73e7-42d7-935b-7387f61e9cc9)

The updated person profile after form submitted with the optional field left blank.

![Snip - Person Entry overrides attributes to blank - Google Chrome (3)](https://github.com/user-attachments/assets/1c636bd8-5156-4d8d-801a-c43c8bb4dbd1)

### Expected Behavior

Expected Behavior

I believe that when a person submits the form without entering a new phone number or email, their existing information should remain intact and not be overwritten.

Upon further investigation, I see a couple of potential solutions. We could make the fields mandatory for users who are not logged in, which would prevent this issue. Alternatively, we could require users to log in before accessing the form, allowing us to pre-fill the fields with their current information, which they could then update as needed.

However, this problem initially arose within the Person Entry section of the Form Builder. The primary aim of the Form Builder is to empower non-technical staff to create simple data collection forms. I’m concerned that implementing this workaround may not be intuitive for all users. If they accidentally remove existing data by leaving the fields optional, we risk undermining the very purpose of the tool.

### Steps to Reproduce

see this 8 minute video link for recreating this issue from both the Form Builder and Workflow Action Type "Form"
https://mycenterpoint.screencasthost.com/watch/cZ6b0FVWHNQ

![Person Entry Form-1](https://github.com/user-attachments/assets/dc10718b-b0d9-4af2-9b20-5cd573aff025)

![Person Entry Form-2](https://github.com/user-attachments/assets/0c157b44-c777-40f6-8f4d-52fac484e0dc)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6

### Client Culture Setting

en-US

**Comment by cjfountain** [comment]
@chead4 It seems that any field may be overwritten - I tested the birthdate today too.

**Comment by dataCollegechurch** [comment]
@PraveenMathew92 - can you help me understand how forms will behave after this fix?

**Comment by chead4** [comment]
@dataCollegechurch Hi Tony  When the Enable Person Entry option is selected on the Form Builder or Workflow Action Type "Form", an existing value for certain optional fields were be overwritten if left blank upon form is submitted.  

This issue applied to these fields: Email, Mobile Phone, Race, Ethnicity, Marital Status and Birth Date.  We’ve resolved this issue so that if these optional fields are left blank during form submission, the original values will now remain unchanged.
