### ISSUE TITLE
SortByAttribute on date type group attribute does not sort groups properly

### ISSUE THREAD

**Issue by kellygcastillo19** [SparkDevNetwork/Rock#6045]
### Description

Typically, the group finder will sort groups alphabetically. We wanted our groups to be sorted by a Date type group attribute that we created called Trip Start Date. We placed this line of code into our Group Finder Lava template: `{% assign sortedGroups = Groups | SortByAttribute:'TripStartDate'%}` followed by the for loop that cycles through the groups `{%- for group in sortedGroups -%}`. Without the sorting line of code, the groups will sort correctly in alphabetical order. Adding that sorting line of code will rearrange the groups, but it will not order them by date. 

### Actual Behavior

The groups are being rearranged into an order that is not based on the Date type group attribute.
![Screenshot 2024-10-22 112410](https://github.com/user-attachments/assets/2fa51c5f-8144-4bca-87d9-a1d2d46046e6)
![Screenshot 2024-10-22 112622](https://github.com/user-attachments/assets/4d1b7d2f-c75c-489a-a18f-bebb658e2b25)

### Expected Behavior

The groups are sorted based on the Date type group attribute called Trip Start Date, ascending. 

### Steps to Reproduce

- Go to Admin Tools > General Settings > Group Types > Fundraising Opportunity > Group Attributes
- Add a new Group Attribute called Trip Start Date
![Screenshot 2024-10-22 113101](https://github.com/user-attachments/assets/90b67f96-03a3-4903-a354-9bde8dfa4131)
- Go to Group Viewer. You need groups that of group type Fundraising Opportunity.
- Edit a group of that type. Ensure the following:
- [ ] Group Name is filled
- [ ] Group is Active and Public
- [ ] Group Attribute Values > Opportunity Type: Trip
- [ ] Group Attribute Values > Enable Commenting: No
- [ ] Group Attribute Values > Allow Individual Disabling of Contribution Requests: No
- [ ] Group Attribute Values > Allow Individual Editing of Fundraising Goal: No
- [ ] Group Attribute Values > Cap Fundraising Amount: No
- [ ] Group Attribute Values > Show Public: Yes
- [ ] Group Attribute Values > Participation Type: Individual
- [ ] Group Attribute Values > Trip Start Date: pick the start date of the trip using the date picker
- [ ] Group Attribute Values > Make sure Opportunity Title, Opportunity Date Range, and Opportunity Location are filled
- Go to Admin Tools > CMS Configuration > Pages
- Create a new page and add the Group Finder block
![Screenshot 2024-10-22 114714](https://github.com/user-attachments/assets/777980d3-ef93-4b81-a00e-3f989fd91857)
- Go into the Lava section of the Group Finder block
- Select the checkbox for Show Formatted Output
- Add this to the Lava template (I shortened the code for the sake of this form; also make sure that the GroupTypeId is set the whatever you Fundraising Opportunity group type id)
[GroupFinderLavaTemplate.txt](https://github.com/user-attachments/files/17480961/GroupFinderLavaTemplate.txt)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 15.5 (1.15.5.1)

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@kellygcastillo19 Hi Kelly Thank you for the detailed write up for this issue. After reviewing, I wasn't able to recreate the problem on the pre-alpha site. I’ve set up multiple Fundraising Opportunities, and they are showing up in ascending order by Trip Start Date on this [page](https://prealpha.rocksolidchurchdemo.com/page/835).

Could you please check and confirm that it's working as expected on your end?

**Comment by kellygcastillo19** [comment]
I tried it out on this [page](https://rock.rocksolidchurchdemo.com/page/2768) but it didn't sort out properly. I have the full code in there. I shortened it in the description above, but the full code contains more if statements that look at more group ids. Could that be a possible reason for it to not sort properly?

**Comment by chead4** [comment]
@kellygcastillo19 I was able to recreate the issue on prealpha Kelly.  Thanks for responding.
