### ISSUE TITLE
v16.6 Registration Waitlist & Total Cost

### ISSUE THREAD

**Issue by MatthewKyle22** [SparkDevNetwork/Rock#6048]
### Description

Registrations with a cost does not persist the total cost when waitlisted when using the Obsidian block. 

![PaymentScreen](https://github.com/user-attachments/assets/5dbe1971-8ecb-4679-b3fc-90cd2b27c097)

On the payment screen above. I would expect to not see a payment screen as I'm being waitlisted, or just show what the amount will be if moved from waitlist.

![waitlisted](https://github.com/user-attachments/assets/41f5351b-f363-4212-8cc6-0b54df83f8d0)

The initial Registrant "Matt Stevens" has a Total Cost of 0.00 because I used a discount code to fill the first spot.
The top registrant should have a total cost of $200.00 as per the registrant instance, even when waitlisted.

![movedFromWaitlist](https://github.com/user-attachments/assets/ec0f7d13-1113-446f-a376-e9bd7f7bf6e2)

After being moved from the waitlist, the total cost is still zero.

### Actual Behavior

Actual Behavior

### Expected Behavior

On the payment screen, I would expect to not see a payment screen as I'm being waitlisted, or just show what the amount will be if moved from waitlist.

For the admin registration list I would expect to see the cost of 200.00 in my case to show in the "Total Cost" field, and 0.00 in the "Balance Due" field if they are still waitlisted, and 200.00 if they have been moved over from the waitlist.

### Steps to Reproduce

-Create registration template with waitlist enabled.
-Create registration instance with cost and set a maximum attendee value.
-Add registrants until max count is exceeded using the obsidian block "Registration Entry".
-Note that any registrant on the waitlist has a total cost of zero.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6 (1.16.6.9)

### Client Culture Setting

en-US

**Comment by KarenRossi84** [comment]
Any possibility this could be added to 16.7? We are having to change costs via SQL as just changing it on the registrant is not an option as we have required fields that those on the waitlist have not filled out yet.

**Comment by chead4** [comment]
@KarenRossi84 Hi Karen - thanks for reaching out.  This fix is now included in v16.7.

**Comment by KarenRossi84** [comment]
@chead4 thank you so much!

**Comment by CherylHugh** [comment]
Hi team, looks like the issue with waitlist is still occurring.  Our version of Rock is 17.8 and it is not saving the cost associated with the registration for the waitlist individuals.
