### ISSUE TITLE
Event Registration Template Security is not honored

### ISSUE THREAD

**Issue by TheCoreyHall** [SparkDevNetwork/Rock#6049]
### Description

Rock allows you to set security on each event registration template, but through testing I have not gotten it to actually change any security. Instead, templates seem to draw their security rules from the Page security. Additionally, based on existing Rock behavior, I would have expected templates to inherit their security from their categories, but they do not.

This came about when I was trying to set a template to be viewable but not editable by all except Rock Admin and was unable to do so without editing Page security.

### Actual Behavior

Event Registration Template security is defined by the page level security, not security on the template.

### Expected Behavior

Security on the template would determine View/Edit/Access and page level security would determine who can view the page at all. Also that templates would inherit security from categories

### Steps to Reproduce

- Go to https://rock.rocksolidchurchdemo.com/web/event-registrations?RegistrationTemplateId=3&ExpandedIds=C173 on Rock admin logged in as Alisha Admin
- Click on the security button on the template and note that Edit access is locked down to Rock Admin only 
![image](https://github.com/user-attachments/assets/53a6705e-1937-4da4-850c-3a0263c9005f)
- Also note that the security is being inherited from Global Default instead of the Category security above it.
- Click on page security at the bottom and note that Event Registration Admin has Edit Access
![image](https://github.com/user-attachments/assets/01ace3de-0277-47bc-a86d-0a665e511c6d)
- Log in as Ted Decker who has Staff Worker and Event Registration Admin but not Rock Admin 
- Navigate to the template and see that Ted can edit it, despite only Rock admin being defined on the template

If this is intended behavior, I would like some clarity on how to set security per template. Thank you.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6

### Client Culture Setting

en-us

**Comment by TheCoreyHall** [comment]
@shauncummings Thank you for the explanation. I will see what I can do to work with that.

On your last comment about categories, that is not universal. Dataviews and Reports inherit security from their category, so it can be confusing what does and doesnt.

**Comment by shauncummings** [comment]
@TheCoreyHall You're not wrong.  It can be a little confusing.  Rock entities can inherit security from two sources, which are called "ParentAuthority" and "ParentAuthorityPre" in the code.  Typically, it's just the ParentAuthority, but some special cases use both (Groups, for example, inherit [from their parent Group](https://github.com/SparkDevNetwork/Rock/blob/53e2d48572d8e60ac4eb0b9199489ab7fc79117c/Rock/Model/Group/Group/Group.Logic.cs#L53), if there is one, and [from the GroupType](https://github.com/SparkDevNetwork/Rock/blob/53e2d48572d8e60ac4eb0b9199489ab7fc79117c/Rock/Model/Group/Group/Group.Logic.cs#L65)).

The following entity types use Category for inheriting permissions (please note that this list may not be exhaustive and is certainly open to change in the future):
- [Category](https://github.com/SparkDevNetwork/Rock/blob/53e2d48572d8e60ac4eb0b9199489ab7fc79117c/Rock/Model/Core/Category/Category.Logic.cs#L64) (parent category, if it exists)
- [DataView](https://github.com/SparkDevNetwork/Rock/blob/53e2d48572d8e60ac4eb0b9199489ab7fc79117c/Rock/Model/Reporting/DataView/DataView.Logic.cs#L48)
- [CommunicationTemplate](https://github.com/SparkDevNetwork/Rock/blob/53e2d48572d8e60ac4eb0b9199489ab7fc79117c/Rock/Model/Communication/CommunicationTemplate/CommunicationTemplate.Logic.cs#L142)
- [Report](https://github.com/SparkDevNetwork/Rock/blob/53e2d48572d8e60ac4eb0b9199489ab7fc79117c/Rock/Model/Reporting/Report/Report.Logic.cs#L45)
- [Tag](https://github.com/SparkDevNetwork/Rock/blob/53e2d48572d8e60ac4eb0b9199489ab7fc79117c/Rock/Model/Core/Tag/Tag.Logic.cs#L43)

These will also pass the inheritance through to elements that may inherit from them (e.g., [a Communication may inherit from CommunicationTemplate](https://github.com/SparkDevNetwork/Rock/blob/53e2d48572d8e60ac4eb0b9199489ab7fc79117c/Rock/Model/Communication/Communication/Communication.Logic.cs#L82), so it would also inherit from the CommunicationTemplate's Category.).

The general rule is that security is inherited from parent objects or from types that define the record (e.g., Groups from GroupTypes, Workflows from WorkflowTypes, DefinedValues from DefinedTypes, and so on), but as you've noticed that won't always be true.  The only way to tell for sure would be to look at the code or check within Rock (i.e., /admin/security/inspect).  When the inherited values are displayed in Rock, if it's from a specific entity (i.e., a specific Category or the Parent group) the name will appear outside of the parentheses, while inheritance from an entity type (or global default) will appear inside parentheses.
