### ISSUE TITLE
Sign-Up Finder 🎉 block doesn't let you change the page title

### ISSUE THREAD

**Issue by Jchinlcbc** [SparkDevNetwork/Rock#6051]
### Description

On the sign ups page, we wanted to have Christmas/Easter sign ups on the same page. We tried to change the page title based off of weather or not it's past June, but it didn't  work.
![image](https://github.com/user-attachments/assets/dcc40aff-3508-4eba-aad6-f30940fb0771)
![image](https://github.com/user-attachments/assets/8b45439d-b2a7-41b5-b3c5-60368a56157d)
![image](https://github.com/user-attachments/assets/e626c4b5-0b1f-462b-9d1b-887302057c61)

### Actual Behavior

In the Sign-Up Finder block, if you try to change the page title with the SetPageTitle lava filter, it doesn't change the page title. It will change the browser title on first save, but after that it no longer works. It's to be noted that you can add an HTML block to the page and run the same code and it works. My running theory is that it runs the code after the content loads.
![image](https://github.com/user-attachments/assets/dcc40aff-3508-4eba-aad6-f30940fb0771)
![image](https://github.com/user-attachments/assets/8b45439d-b2a7-41b5-b3c5-60368a56157d)
![image](https://github.com/user-attachments/assets/e626c4b5-0b1f-462b-9d1b-887302057c61)

### Expected Behavior

I would assume that the page/browser title would change from LCBC Bug Testing (see screenshots above) to "This Should Be The New Page Title" when you have the code {{ "This Should Be The New Page Title" | SetPageTitle }} anywhere in the block

### Steps to Reproduce

1.) Create a blank Page. Name it anything
2.) Add a Sign-Up Finder 🎉 block anywhere on the page
3.) Edit the Sign-Up Finder 🎉 block properties and enter the Advanced Settings
4.) add the lava print code {{ "This Text Should be the Page Title" | SetPageTitle }} where the quotes can be anything
5.) Save & Refresh the page.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6

### Client Culture Setting

en-US

**Comment by kylehenning** [comment]
Hi @Jchinlcbc I’ll be closing this issue since the Page Title isn’t designed to be updated from the Pre-HTML or Post-HTML areas in both Webforms and Obsidian Blocks. I would also like to confirm that, as you identified, you can update the Page Title from the content section of the HTML Content Block. Thank you!
