### ISSUE TITLE
[1.16.7.2 Alpha] Nextgen Checkin Missing Critical "Prioritize Grade" Feature

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#6054]
### Description

The existing ("legacy") check-in has a core-supported feature that "prioritizes grade" for a child checking-in who has an _age_ that would quality them for one room, but a _grade_ that would qualify them for another. This feature appears to be missing in Nextgen Check-in.

### Actual Behavior

Nextgen check-in presents both areas to choose, because it seems to have no "prioritize grade" option, which (in legacy check-in) is a supported via an alternate _FilterGroupsByGradeAndAge_ Workflow action detailed here in the check-in documentation https://community.rockrms.com/documentation/bookcontent/10/307#filtergroupsbygradeandage

This is what legacy check-in looks like for a child that qualifies for PreK _and_ Kindergarten, using the _FilteGroupsByGradeAndAge_ action with _Prioritize Grade_ option set to Yes:
![image](https://github.com/user-attachments/assets/56006323-fe50-4f11-bc06-aa00f34c7c0b)

This is what Nextgen Check-in does for the same child, because there is no similar "prioritze grade" option (at least not that I could find in either block settings or checkin config panels)
![image](https://github.com/user-attachments/assets/f2f2bc7c-362d-422d-8958-1eee75bbbbc7)

### Expected Behavior

There would be a mechanism in Nextgen Check-in to prioritize grade when a person meets criteria for different areas based on their age _and_ grade.

### Steps to Reproduce

Configure Nextgen check-in and look for an option to "prioritize grade", but you can't find it (unless I'm blind!) This would have to be implemented as either a block setting in the new _Checkin Kiosk_ block, or in Check-In configuration itself, because (obviously) there is no longer a workflow driving Nextgen, which is where this alternate action currently lives.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.16.7.2

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@JimMichael As we're sorting out the logic in that workflow action, we have a nuanced question about your usage of that action that can be easily answered via a screenshot.  Can you attach a screenshot showing your configuration of the replacement FilteGroupsByGradeAndAge workflow action (just like one shown in the documentation):

![image](https://github.com/user-attachments/assets/72bd3bad-ada7-4069-a584-f299dc365e47)

**Comment by JimMichael** [comment]
Here ya go!
![image](https://github.com/user-attachments/assets/cc0f890c-42cb-46e1-9d19-6297f5e65734)

**Comment by adamhann** [comment]
I can confirm this issue as well. It was one of the first things we checked!

**Comment by jonedmiston** [comment]
This is being worked on now and the fix will be in the beta for v16.7.

**Comment by nairdo** [comment]
@JimMichael We're in the final stages of updating the new Next-Gen Check-in manual, but this particular feature is [documented like this at the moment](https://community.rockrms.com/documentation/bookcontent/42/348#gradeandagematchingbehavior):

![image](https://github.com/user-attachments/assets/f723e5a9-8871-4ade-97aa-c2503e68980b)

**Comment by adamhann** [comment]
@nairdo @jonedmiston We just tested the update that now allows you to prioritize grade over age. Thank you! I like the intentionality that you put into that setting. One note, if you select a config to prioritize grade over age, it now completely removed any groups that are check-in by data view as well. Is that intentional? It seems that Check-in by data view groups should be excluded by this setting. I can open up another issue, I just wanted to make sure it wasn't intentional.

**Comment by cabal95** [comment]
Hi @adamhann. That was intentional so that it matches with the old "legacy" check-in behavior.  The logic it used was that, when enabled, if you matched a group by grade, it would remove _all_ other groups that were not matched by grade; even if they were filtered by something other than grade and age.

If that feels like it would be undesired behavior please let us know!

**Comment by JimMichael** [comment]
@nairdo I only just saw this, thanks for the link! (For some reason Github is no longer sending me emails for some issues).

Anyway, it looks good to me! I did notice a tiny typo, if someone wants to fix it 
![image](https://github.com/user-attachments/assets/c749718a-0add-45e3-862e-be562110666c)

**Comment by nairdo** [comment]
@adamhann  Daniel was able to isolate your particular edge-case so that 4518f1a commit is his fix for that.  This will also be in in the upcoming `1.16.7.3` alpha release.

**Comment by adamhann** [comment]
Thank you guys! @nairdo
