### ISSUE TITLE
[1.16.7.2 Alpha] Nextgen Check-In Does Not Honor "Prevent Duplicate Checkin"

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#6055]
### Description

In any Area configured to _Prevent Duplicate Checkin_, Nextgen seems to ignore this setting and let the person check in again.
![image](https://github.com/user-attachments/assets/021a938f-4657-434c-93fd-2675df1f58fc)

### Actual Behavior

NextGen lets a person check-in repeatedly, without error, even when _Prevent Duplicate Checkin_ is enabled on the checkin area.

### Expected Behavior

Person would be presented with an error/message similar to legacy checkin, instead of being checked-in (and another label print, etc) again.
![image](https://github.com/user-attachments/assets/f962b0a2-90cb-479c-ac98-c5b6f5367ef9)

### Steps to Reproduce

1. Configure Nextgen checkin
2. Configure an Area to _Prevent Duplicate Checkin_
3. Check in to that area with Nextgen
4. Observe that you can check in again without any error message.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.16.7.2

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Hi @JimMichael , with Next-Gen Check-in (v16.7 alpha; temporarily setup on the demo site this morning), if someone is already checked in (and that setting is enabled) you will see a message on the person select screen like this:

![image](https://github.com/user-attachments/assets/311a3ac1-c374-414c-b583-4b2cb2be329f)

In this case, I had previously checked Noah in and then went to try to check him in a second time.

Can you share your check-in configuration and selected schedules (and maybe the Next-Gen person select screen).

**Comment by JimMichael** [comment]
Thanks @nairdo I verified that IF I enable "Prevent Duplicate Check-in" per above, it works as expected

![image](https://github.com/user-attachments/assets/321b68e3-cab2-45d6-b851-4c11fc57fcd1)

However, as you noted, we're using the documented "per area" _Prevent Duplicate Checkin_ per https://community.rockrms.com/documentation/bookcontent/10/307#appendixadvancedoptions

We've been using that feature pretty much since day 1 with Rock, and it seems like Nextgen was not coded to take this feature into account. Is that intentional, or an oversight?

**Comment by cabal95** [comment]
I forgot to tag this issue in the commit that resolved this: https://github.com/SparkDevNetwork/Rock/commit/d73b2096c662ec06d59542b98b87228749e5a288

Please note that the way to configure this is slightly different than it was in v1 in order to make this feature more accessible. We are working on the documentation for this now.
