### ISSUE TITLE
Group Scheduler (Obsidian) Viewing Filters Limitation 

### ISSUE THREAD

**Issue by tpeera** [SparkDevNetwork/Rock#6058]
### Description

When using the new Group Scheduler (Obsidian) block on a mobile device, the filter options for **Groups** extend beyond the visible screen area, making it difficult to select your desired choices. This is especially difficult when you might have a multilevel group hierarchy for multiple campuses or ministries. _(or if you have multiple groups already selected)_

![image](https://github.com/user-attachments/assets/198d2297-6e85-4583-a7b9-4713d674c752)

### Actual Behavior

The Groups filter is not user-friendly, as it extends beyond the visible screen and does not allow scrolling. This limits the viewing capability.
![image](https://github.com/user-attachments/assets/7c479127-5d68-4c0d-9bf9-f7b91b9b5e78)

### Expected Behavior

It is expected to function like the group viewer, where you have the ability to see all available selections within the viewable area.

### Steps to Reproduce

- First go to CMS Configuration and create a copy page of Group Scheduler but change the Group Scheduling block to the obsidian version.
- Next, make sure you are on a mobile device.
- Go to People > Manage > Group Scheduling > "the new page with the block you setup"
- Click on 'Filters', then the **Groups** filter
- See error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6

### Client Culture Setting

en-US

**Comment by joezimjs** [comment]
Fixed with [#22f94e2](https://github.com/SparkDevNetwork/Rock/commit/22f94e23049cb693f2c4efb3e3d9f460d1964ba5)
