### ISSUE TITLE
[1.16.7.2 Alpha] Mobile Application Detail block - Several Issues related to Interface & Application Colors (i.e. Palette Colors for Mobile)

### ISSUE THREAD

**Issue by stanalyst** [SparkDevNetwork/Rock#6063]
### Description

It appears that the Mobile Application Detail block was updated with v16.7 to support the Maui update for mobile. Now we are seeing several issues related to the Interface Colors and Application Colors fields on the Styles tab of this block.

**Issue 1:** All of these color settings are supposed to be available for use in the Mobile App - as documented in the mobile docs [Palette Color page](https://mobiledocs.rockrms.com/essentials/controls/xaml-extensions/palette-color). Of the 12 colors listed on this doc - only Text-Color, Heading-Color, & Background-Color are actually set to the values we set using this block. The other 9 colors (whose names all start with App-) do NOT match what we set in the block - and actually appear to be hard-coded to some default values. See screen shots...

**Issue 2:** For the 5 fields under Interface Colors header - the panel will allow them to be updated and saved. But when you reload the page - the values for all 5 fields are gone (i.e. blank).

![MobileApplicationDetail-Styles](https://github.com/user-attachments/assets/8c951e78-45de-4504-9ea7-dcac14aefcf1)
![MobileApp-RockPaletteColors](https://github.com/user-attachments/assets/3822df81-c69e-4e50-9506-187f8c7037bc)

### Actual Behavior

Issue 1 - the colors available using {Rock:PaletteColor App-Primary) for any ones that start with App- in their name DO NOT match what we set them to on the Mobile Application Detail block.

Issue 2 - the colors we set for the Interface Colors fields are not being loaded back into the panel when reloading the page.

### Expected Behavior

All the colors should be available using {Rock:PaletteColor ...} and the colors entered and saved should be shown when the page is reloaded.

### Steps to Reproduce

Issue 1...
1. go to the page that has the Mobile Application Detail block
2. update the Application Colors fields
3. setup a mobile app page that tries to use those colors using {Rock:PaletteColor ...}
4. view the mobile app page and note difference is colors

Issue 2...
1. go to the page that has the Mobile Application Detail block
2. update the Interface Colors fields and save
3. reload the page
4. note that the Interface Colors fields are now blank

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.16.7.2

### Client Culture Setting

en-US

**Comment by mikedotmundy** [comment]
I am experiencing similar behavior - If I refresh the page, the colors are gone. However, if I save and then navigate to a the 'Application' page, and then Deploy, the colors save properly.

**Comment by mikedotmundy** [comment]
I am seeing other issues as well, for example, I have no Navigation Bar Image even though I have a file uploaded.

**Comment by bradencohen** [comment]
I was able to reproduce and get issues 1 & 2 fixed, which will be available to test in the pre-alpha this Friday (version 1.16.6.10 I believe).

@mikedotmundy that seems like a separate mobile issue. I'm going to close this and follow up with you on Rocket Chat.

**Comment by JimMichael** [comment]
This definitely needs to get into 1.16.7 (currently in alpha), otherwise we don't be able to upgrade to it as it breaks the mobile app badly.

**Comment by bradencohen** [comment]
@JimMichael this will be in 16.7 👍.
