### ISSUE TITLE
[Alpha 1.16.7.2] Error When Viewing NextGenCheckin Theme

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#6065]
### Description

I was not able to duplicate this on [rockrmslatest.com](rockrmslatest.com), however in my fresh v1.16.7.2 install (just updated this morning), I cannot view the NextGenCheckIn Theme. All other themes work properly. This is the screen I see: 
<img width="2193" alt="Screenshot 2024-11-13 at 10 01 35" src="https://github.com/user-attachments/assets/b1c0dbd3-a9bc-4ce1-a46e-bf07c76b2307">

There are no exceptions created, but here is what I see in the console:
<img width="1613" alt="Screenshot 2024-11-13 at 10 05 37" src="https://github.com/user-attachments/assets/ec6c59ee-ef04-4868-977d-26d7d263c05c">

### Actual Behavior

Error is shown and I cannot view the NextGenCheckin Theme.

### Expected Behavior

Should be able to view/edit the NextGenCheckin Theme.

### Steps to Reproduce

- Unsure, as I was unable to duplicate it on the demo site. (I only checked the reproduced option below because it is required in order to submit this issue).

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v1.16.7.2 Alpha

### Client Culture Setting

en-US

**Comment by JimMichael** [comment]
I'm unable to dupe this on 1.16.7.2 and this is what I see when looking at the Nextgen theme
![image](https://github.com/user-attachments/assets/3f747e73-4a47-4d83-b2bf-2f85271c5726)

(clicking Edit also works as expected and lets me edit the theme).

That said, I had NOT looked at this theme until now, so I wonder if this is one of those "you have old JS in your browser cache" things, because you DID look at the theme via 1.16.7.1?

**Comment by mikedotmundy** [comment]
Thanks @JimMichael Interestingly, even though I admit I could be wrong, I do not recall viewing this theme in 1.16.7.1. But you were correct - clearing the cache in my browser fixed the issue and I was able to view/edit/save the theme successfully.
