### ISSUE TITLE
Obsidian Notes Block Shows "Pending Approval" Label for Note Types with Enabled Approvals Turned Off

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#6066]
### Description

We're currently in the process of updating our Rock instance from 17.0.27 to 17.0.31. During our QA process, we noticed that the Obsidian Notes block on person profile pages is showing labels that state "Pending Approval" even though we have Enabled Approvals disabled for the corresponding note type(s) (General Note, Event Registration Note, etc).

It seems like [this is the conditional](https://github.com/SparkDevNetwork/Rock/blob/pre-alpha-release/RockWeb/Assets/Lava/NoteViewItem.lava#L85) the handles whether the label is rendered or not, and it's odd that it does not appear to take into account the note type "Enabled Approvals" setting.

<img width="1683" alt="image" src="https://github.com/user-attachments/assets/4c672112-3fe3-4890-91b2-ad8c47c9a107">

### Actual Behavior

Notes that are of a note type that has "Enabled Approvals" disabled currently display the "pending approval" label in the new obsidian Notes block on person profile pages.

### Expected Behavior

Notes that are of a note type that has "Enabled Approvals" disabled should not display the "pending approval" label in the new obsidian Notes block on person profile pages.

### Steps to Reproduce

See the personal note at the top of Ted Decker's profile here:  https://rockrmslatest.com/person/4
Enable Approvals is set to false for the Personal Note note type.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

17.0.31

### Client Culture Setting

en-US

**Comment by shauncummings** [comment]
Note approval was removed in https://github.com/SparkDevNetwork/Rock/commit/255295e19a3b1b76511801cf4407e38fc3577d08
