### ISSUE TITLE
[Alpha 1.16.7.2] TV Apps Pages - UI Issues

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#6069]
### Description

Per the release notes, v16.7 adds support for Roku TV Apps. The settings under CMS Configuration are slightly confusing however. 

**Issue 1** 
As you can see in this screenshot, there are now 2 buttons. I am not sure if this was intentional or not in v16.7, with the future plan to combine them in v17, but if the plan is to keep them both in v16.7, then read on to the next 2 issues.
<img width="2077" alt="Screenshot 2024-11-13 at 11 48 01" src="https://github.com/user-attachments/assets/14f78b13-7334-4816-948a-5bf5f572853d">

**Issue 2** 
Let's say I add a Roku app. On the TV Apps page, here is what it looks like: 
<img width="2083" alt="Screenshot 2024-11-13 at 11 52 56" src="https://github.com/user-attachments/assets/bfbb77ea-1543-41dc-ae2c-d1705082ad3e">

Now, I navigate to the Apple TV Apps page. Here is what it looks like:
<img width="2080" alt="Screenshot 2024-11-13 at 11 53 57" src="https://github.com/user-attachments/assets/d5ded5b3-e245-434d-871e-bc54c21bbaef">

If the intention in v16.7  is that we keep both TV Apps and Apple TV Apps pages, then the Roku app should not appear on the Apple TV Apps page.

**Issue 3**
On the Apple TV Apps page, if I select my Roku application, Edit it, and then Save it. It has now been strangely "converted" into an Apple TV App. You can see this back on the TV Apps page, where it is now listed as an Apple TV app:
<img width="2085" alt="Screenshot 2024-11-13 at 11 56 49" src="https://github.com/user-attachments/assets/46373a54-a454-437f-83f7-5fdf46029546">

### Actual Behavior

See above description - there is some strange functionality with the TV Apps and Apple TV Apps pages.

### Expected Behavior

**Issue 1**
Possibly consider removing Apple TV Apps page in v16.7, since they now exist on the TV Apps page.

**Issue 2**
If the desire is to keep both pages in v16.7, then the Roku App should not appear on the Apple TV Apps page.

**Issue 3** 
If the desire is to keep both pages in v16.7, then a Roku App should not be able to be strangely _converted_ into an Apple TV App.

### Steps to Reproduce

See above.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v1.16.7.2

### Client Culture Setting

en-US

**Comment by bradencohen** [comment]
This is resolved in 16.7, we're removing the "Apple TV Apps" page.

Note, that we changed this entirely in v17, and you will now go to the "TV Apps" parent page. 
![image](https://github.com/user-attachments/assets/e54c8913-e57f-46a6-9530-b0b5b00ffe79)

There is still a pending change to swap out the block in v17 to be the dual-purpose Roku and Apple TV Application list.
