### ISSUE TITLE
[Alpha 1.16.7.2] Checkin-No ability to view, edit or delete Saved Configurations

### ISSUE THREAD

**Issue by kimlongcr** [SparkDevNetwork/Rock#6074]
### Description

After creating a custom configuration, there is no ability to view, edit or delete them. 

### Actual Behavior

Go to the checkin kiosk and create a custom configuration. Once you save it, there is no going back - no way to view, edit or delete the configuration you just created. 

### Expected Behavior

Ability to view, edit or delete a configuration after it is saved. 

### Steps to Reproduce

1. Navigate to nextgen-checkin/setup
2. Choose a campus and a kiosk
3. Select Custom Configuration button
4. Select a template
5. Select a few areas
6. Select Save New Configuration
Saves into list but there is no way to see any of what you just saved or to edit them. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.7 (1.16.7.2)

### Client Culture Setting

en-US

**Comment by cabal95** [comment]
@kimlongcr This was caught internally after the last alpha and has already been fixed for the next alpha/beta release. If you have EDIT permissions to the Kiosk Setup block then you will be able to edit or delete saved configurations from that screen and not have to go into the Defined Values as @adamhann mentioned.

![image](https://github.com/user-attachments/assets/f4dd9604-5cfc-43e3-9daa-b5e495b5a84f)

**Comment by kimlongcr** [comment]
@cabal95 Before I enter more defects, how would I have known that? I searched GitHub and didn't see anything. Is there something I am missing?

**Comment by chead4** [comment]
@kimlongcr Hi Kim There’s no way you could have known about an internal fix. Please continue submitting issues as you find them. If something is resolved on our end, we’ll add an update in the comments to keep you and others informed.

Thanks for reaching out and your attention to detail!
