### ISSUE TITLE
[Alpha 1.16.7.2]-NextGen Checkin-Non rock Admin user can't run a kiosk

### ISSUE THREAD

**Issue by kimlongcr** [SparkDevNetwork/Rock#6082]
### Description

We have a shared user name and password that we user on our kiosks at each site with a Checkin Administrator security role. The purpose of this is so that volunteers can know this login and password but literally only have access to the kiosk and all of it's functionality. However, if they tried to login to rock.crossroads.net with it, they wouldn't have any permissions. this user is not able to run a kiosk.

### Actual Behavior

I added the security role of checkin administrator to the block settings. In 16.6 they only needed view permissions and not edit or administrate. I have tried adding this security role to all levels of the page (which then inherits it to the block) and it still won't work.
![Screenshot 2024-11-15 at 7 39 14 AM](https://github.com/user-attachments/assets/4b49102f-49eb-4ac2-a548-a5748391d694)
![Screenshot 2024-11-15 at 7 39 14 AM](https://github.com/user-attachments/assets/84bf36ac-91fe-4aa6-881a-f246205e9c1d)

As a rock admin right now, I see this for checkin:
![Screenshot 2024-11-15 at 7 42 50 AM](https://github.com/user-attachments/assets/6058085d-b2f5-4a45-9afa-d0a2b5772343)

As this user with view, edit and administrate permissions I see this:
<img width="1158" alt="Screenshot 2024-11-15 at 7 43 38 AM" src="https://github.com/user-attachments/assets/47b09432-c116-4fde-86f3-8ef22e19a1aa">

If I open a schedule, a rock admin sees this:
![Screenshot 2024-11-15 at 7 45 06 AM](https://github.com/user-attachments/assets/0f5dd86e-9e52-447c-b0d9-a21708c96253)

While the other user sees this:
<img width="1155" alt="Screenshot 2024-11-15 at 7 45 41 AM" src="https://github.com/user-attachments/assets/b8346756-6244-46a1-94f7-f3a91a50a332">

### Expected Behavior

The user permissions on the block and page for check=in kiosk allow a non rock admin user to login and run all functionality on the kiosk.

### Steps to Reproduce

1. Go to checkin (https://rockalpha.crossroads.net/nextgen-checkin/setup)
2. Login as kcoakley@crossroads.net / AbbaFather (user with Checkin Administrator security role)
3. Click on a configuration (Normal Kids Club) ---> a plan welcome screen is displayed

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.7 (1.16.7.2)

### Client Culture Setting

en-US

**Comment by cabal95** [comment]
@kimlongcr The new Check-in Kiosk makes heavy use of API calls to perform all the check-in work - which gives us a massive performance boost. You will need to add that custom security role to VIEW and EDIT permissions for the `Rock.Rest.v2.CheckInController` REST controller as seen here: https://prealpha.rocksolidchurchdemo.com/admin/security/rest (though do this on your site of course).

![image](https://github.com/user-attachments/assets/184d5515-40f3-4e5c-8b40-42f204ea047c)

![image](https://github.com/user-attachments/assets/a066a31c-f902-4c37-8d16-607302bc38d2)
