### ISSUE TITLE
[Alpha 1.16.7.2] Next Gen Check-in - Saved Configurations Disappear When Hovering

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#6087]
### Description

I have only noticed this issue in Google Chrome. Saved Configurations disappear when hovering over them.

https://github.com/user-attachments/assets/d2352631-7c45-46b7-8013-3f3ce0059960

### Actual Behavior

Saved Configurations disappear when hovering over them.

### Expected Behavior

Saved Configurations should not disappear when hovering over them.

### Steps to Reproduce

- In Google Chrome, go to [https://rockrmslatest.com/nextgen-checkin/setup](https://rockrmslatest.com/nextgen-checkin/setup). 
- Make sure you have some saved configurations
- See they disappear

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v1.16.7.2 Alpha

### Client Culture Setting

en-US

**Comment by mikedotmundy** [comment]
Slight correction here - this is actually happening for all buttons throughout the check-in process while using Chrome. Not just the Saved Configurations.

<img width="2031" alt="Screenshot 2024-11-15 at 15 45 22" src="https://github.com/user-attachments/assets/dfff259c-02d6-4a39-be2a-2191be3cc627">

**Comment by nairdo** [comment]
@mikedotmundy  That sounds very similar to a problem we were seeing last week when testing on older iPads.  I'm also using Chrome here but not able to reproduce what you're seeing yet.  Is anyone else able to reproduce this bug?

**Comment by mikedotmundy** [comment]
Well, I just checked for updates to Chrome, updated it to Version 131.0.6778.70, and this is no longer an issue.

**Comment by cabal95** [comment]
@mikedotmundy Thanks for reporting back. This was related to a CSS issue with older browsers. So updating your browser fixing it does make sense - but we also updated the CSS to be more backwards compatible.

**Comment by nairdo** [comment]
I did find the two commits for that similar issue, and they were made after we packaged `1.16.7.2` so that fix will be in the next alpha release:
* https://github.com/SparkDevNetwork/Rock/commit/40694de9b08985d81bf26dac51f350f505163727#diff-77573e1732781ad8d502408ec06fc994fb67a002fa8cd3c2d75c2e8e1fee602dR369
* https://github.com/SparkDevNetwork/Rock/commit/19d709b269da999767873de8425d06198a0048e2
