### ISSUE TITLE
[Alpha 1.16.7.2]-NextGen Checkin-Room selected not staying

### ISSUE THREAD

**Issue by kimlongcr** [SparkDevNetwork/Rock#6094]
### Description

In Room Manager when you select the room, it is blanking out the selection from the drop down which then impacts the Room Settings screen as well. 

### Actual Behavior

In Room Manager when you select the room, it is blanking out the selection after you do it. Then if you go to Room Settings, again, the screen doesn't tell you what room you are on. If you select the room again, it again blanks out the selection. 

### Expected Behavior

It should display the room in the drop down, then pass it and retain it on the Room Settings page as well. 
![Screenshot 2024-11-19 at 8 04 14 AM](https://github.com/user-attachments/assets/3e2f8b65-ef5e-4177-9af0-79dfb30eea01)
![Screenshot 2024-11-19 at 8 04 22 AM](https://github.com/user-attachments/assets/cd1f4702-8a6c-4610-bf0b-a2acb77fc691)

### Steps to Reproduce

- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.7 (1.16.7.2)

### Client Culture Setting

en-US

**Comment by kimlongcr** [comment]
@shivambareria @Panha-Sim I just installed 16.7 into our test environment and this issue is back.

**Comment by chead4** [comment]
@kimlongcr Hi Kim, just a quick note to let you know that this issue has been resolved in version v.16.10. It wasn't included in the release of version v16.7.
