### ISSUE TITLE
Schedule Toolbox Calendar Export Includes Events in the Past that were Accepted but not Attended

### ISSUE THREAD

**Issue by nharmonCOTH** [SparkDevNetwork/Rock#6103]
### Description

When a person accepted a scheduled occurrence but did not attend, the event is still included in the ics calendar file for past events.

It appears that these events will forever be included in the calendar file with no easy way to resolve it.

### Actual Behavior

Events in the past are included in the calendar file.

### Expected Behavior

Events in the past should not be included in the calendar file.

### Steps to Reproduce

1. Enable Scheduling on the Serving Team group type
2. Make the logged-in person a member of a Serving Team group
3. Go to the [Schedule Toolbox](https://rockrmslatest.com/ScheduleToolbox) and Sign Up for Additional Times. Add an occurrence in the near future.
4. Go to the group and add an attendance in the recent past.
5. In SQL, find the past attendance record to modify, and edit and run the below script to mark it as "did not attend, but the person was scheduled and accepted" (this makes the record identical to an attendance record in the future that has been accepted).
6. On the Schedule Toolbox click the "Add to Calendar" button and download the calendar file. Open it in a text editor or add it to your calendar and note that the event in the past is present and added to your calendar.

UPDATE [Attendance]
    SET [RSVP] = 1
    ,[DidAttend] = 0
    ,[ScheduledToAttend] = 1
    ,[RequestedToAttend] = 1
    ,[RSVPDateTime] = '11/21/2024 4:07 PM'
    ,[ScheduleByPersonAliasId] = 10
WHERE [Id] = xxx

![Screen Shot 2024-11-21 at 9 42 55 AM](https://github.com/user-attachments/assets/9f2aa64c-46d0-432f-9f3a-e137b31afe9f)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6, prealpha 1.17.0.32

### Client Culture Setting

en-US

**Comment by tpeera** [comment]
@Kwame-Agyei is v16.10 the correct version?
