### ISSUE TITLE
[Alpha 1.16.7.2]-NextGen Checkin-One iPad-first button won't appear until you click on the screen

### ISSUE THREAD

**Issue by kimlongcr** [SparkDevNetwork/Rock#6104]
### Description

On one ipad we are seeing that the first button on pages with more than one button in checkin is not displaying until you click on the page. 

### Actual Behavior

Attached is a video. When you see the list of family members display, notice that the first person you can see their picture but nothing else until I actually click on the screen. The same thing occurs with the Check Out and Check In options. 

[Video can be viewed](https://drive.google.com/file/d/1L9g9ehzJ3mn2igfsUVJ7XUXAKn9kz9Mi/view?usp=sharing) here (too large to upload):  

### Expected Behavior

Buttons appear without issue.

### Steps to Reproduce

Just do a normal checkin with a family that has two or more people.
Then try to check them out. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.7 (1.16.7.2)

### Client Culture Setting

en-US

**Comment by Panha-Sim** [comment]
Hello, @kimlongcr, the issue will be fixed in 1.16.7.3.
