### ISSUE TITLE
[Prealpha] Obsidian Suggestion Detail Block Has Missing Settings

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#6105]
### Description

In the Obsidian version of the Suggestion Detail block, all of the settings are missing when you have the _Suggestion Type_ set to _In Followed Group_.

Here is the Webforms block in v16.6:
<img width="2056" alt="Screenshot 2024-11-22 at 11 17 46" src="https://github.com/user-attachments/assets/ac85caba-17a4-4e61-aa3d-fca48cf7a51a">

Here is the Obsidian block in v1.17.0.32:
<img width="2053" alt="Screenshot 2024-11-22 at 11 12 56" src="https://github.com/user-attachments/assets/3fbf9fa7-51c8-4c83-aeef-52e6372f7989">
<br><br>
Then, when you change the _Suggestion Type_ to _In Group Together_, the Obsidian Block is missing the Auto-Follow setting.

Here is the Webforms block in v16.6:
<img width="2053" alt="Screenshot 2024-11-22 at 11 22 50" src="https://github.com/user-attachments/assets/ce0b3966-b6bf-40c6-a3b9-34ffc66dacd5">

Here is the Obsidian block in v1.17.0.32:
<img width="2056" alt="Screenshot 2024-11-22 at 11 23 00" src="https://github.com/user-attachments/assets/cccd938c-c647-438f-b207-cba2fba8df28">

### Actual Behavior

1. All of the settings are missing when you have the _Suggestion Type_ set to _In Followed Group_. 
2. The Auto-Follow setting is missing when you have the _Suggestion Type_ set to _In Group Together_

### Expected Behavior

1. The settings should not be missing when you have the _Suggestion Type_ set to _In Followed Group_. 
2. The Auto-Follow setting should not be missing when you have the _Suggestion Type_ set to _In Group Together_

### Steps to Reproduce

- Go to [https://rockrmslatest.com/admin/system/following-suggestions](https://rockrmslatest.com/admin/system/following-suggestions)
- Click '+' to add a new Following Suggestion
- For the _Suggestion Type_, select _In Followed Group_.
- See that you are missing the settings for Group Type, Auto-Follow, Group Role (optional), and Role.
- Then, change the _Suggestion Type_ to _In Group Together_
- See you are missing the Auto-Follow setting.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v1.17.0.32

### Client Culture Setting

en-US

**Comment by mikedotmundy** [comment]
I don't have a local copy of v17 - just doing some testing on the pre-alpha site with blocks that have been updated to Obsidian.

**Comment by shauncummings** [comment]
Thanks, @mikedotmundy. We have confirmed the issue on another local pre-alpha database, so we're still investigating.
