### ISSUE TITLE
[Prealpha] Grid Actions Dropdown for Obsidian List Blocks is Hiding Behind Header

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#6106]
### Description

In v1.17.0.32, for Obsidian List Blocks, the Grid Actions Dropdown is hiding behind the header. I tested this with several different browsers and with several different Grid blocks, all of which are doing the same thing. The screenshot below is from the Batch List Block. This is not an issue in v16.6 or v16.7.2 (Alpha).

<img width="2056" alt="Screenshot 2024-11-22 at 11 52 18" src="https://github.com/user-attachments/assets/4e9ae598-db3a-49f7-8024-be2318ed61a7">

### Actual Behavior

Grid Actions Dropdown is hidden behind the Header in Obsidian List Blocks.

### Expected Behavior

Grid Actions Dropdown should not be hidden behind the Header in Obsidian List Blocks.

### Steps to Reproduce

- Go to an Obsidian List block, like this one here: [https://rockrmslatest.com/finance/batches](https://rockrmslatest.com/finance/batches)
- Click the `fa-ellipsis` icon on the top right of the block.
- See the dropdown is playing hide-and-go-seek, but not doing a very good job, as it is only partially hidden. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v1.17.0.32

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@mikedotmundy Hi Mike This has been resolved in v16.7 (1.16.7.3) and develop with [commit](https://github.com/SparkDevNetwork/Rock/commit/417231976d749cbf87669dc97855e5b451f6ba30).
