### ISSUE TITLE
[Prealpha] Device Detail Block - Geo-fence Issue

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#6118]
### Description

In the Obsidian Device Detail Block, the Geo-fence picker is not working.

<img width="1950" alt="Screenshot 2024-12-03 at 10 23 41" src="https://github.com/user-attachments/assets/d4fe792b-7dd6-425e-9d8e-d461bd882a0f">

I am not sure if this is related to #6111 or not.

### Actual Behavior

Geo-fence picker is not working.

### Expected Behavior

Geo-fence picker should be working.

### Steps to Reproduce

- Go to [https://rockrmslatest.com/admin/general/devices
](https://rockrmslatest.com/admin/general/devices)
- Add a device
- See the Geo-fence picker is not working.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v1.17.0.32

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@mikedotmundy This might be an issue with the Google API key  (under Global Attributes) that it was using.  I put in a new temporary one (which I just generated) and it's working again.  Are you able to confirm this issue exists on your system using your Google API key?

**Comment by mikedotmundy** [comment]
Thanks @nairdo That fixed it! I do not have a local copy of v17 - I'm just testing Obsidian blocks on the prealpha site. Looks like that also fixed #6111.
