### ISSUE TITLE
Group Detail Lava block displays "Inactive Reason" and "Inactive Note" when editing a group if "Hide the Active Group checkbox" is set to Yes and the Group Type has Inactive Reason enabled.

### ISSUE THREAD

**Issue by KennySnow-BEMA** [SparkDevNetwork/Rock#6120]
### Description

When a Group Type has Inactive Reason enabled and the Group Detail Lava block (Group Toolbox) has "Hide the Active Group checkbox" set to "Yes", "Inactive Reason" and "Inactive Note" displays when editing the group whether the group is set to active or not. This is especially problematic if the Group Type has Inactive Reason set as required, as the Group Toolbox user will have to record an Inactive Reason even if the group is Active.
![image](https://github.com/user-attachments/assets/557cb1bd-2c94-4238-ae4d-b4ace7f5aa8c)

### Actual Behavior

When a Group Type has Inactive Reason enabled and the Group Detail Lava block (Group Toolbox) has "Hide the Active Group checkbox" set to "Yes", "Inactive Reason" and "Inactive Note" displays when editing the group whether the group is set to active or not. This is especially problematic if the Group Type has Inactive Reason set as required, as the Group Toolbox user will have to record an Inactive Reason even if the group is Active.

### Expected Behavior

When "Hide the Active Group checkbox" is set to "Yes" the Inactive Reason and Inactive Note should also be hidden, as the end user has no way of setting the group to Active or Inactive.

### Steps to Reproduce

- Set a Group Type Inactive Reason as Enabled
- Configure the Group Toolbox Group Detail Lava block to Hide the Active Group checkbox
- As a Group Leader edit the Group in the Group Toolbox

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6

### Client Culture Setting

en-Us

**Comment by sparkdevnetwork-service** [comment]
@KennySnow-BEMA Hi Kenny - Thanks for reporting the issue. I was able to successfully recreate the issue in v16.6. However, I was unable to recreate on the prealpha site (v17.0). I will be closing this issue as it has been resolved. Please reach out if you are able to recreate on prealpha and I can reopen.
