### ISSUE TITLE
[Prealpha] Document Type List Block - Headers do not Properly Align with Columns

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#6126]
### Description

In the new Obsidian Document Type List Block, the column headers do not properly align with the information below the header in each column.

<img width="2156" alt="Screenshot 2024-12-11 at 15 25 24" src="https://github.com/user-attachments/assets/0868e97e-0fc4-475c-b827-f179c36df6f8" />

### Actual Behavior

Column headers do not properly align with columns.

### Expected Behavior

Column headers should properly align with columns.

### Steps to Reproduce

See above.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v1.17.0.33

### Client Culture Setting

en-US

**Comment by joezimjs** [comment]
Fixed with https://github.com/SparkDevNetwork/Rock/commit/9046c81c66315c9e5dab246bcd173a57ce6a9c03
