### ISSUE TITLE
[Prealpha] Account Detail Block - Campus Option Missing

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#6127]
### Description

For the new Obsidian Financial Account Detail Block, the option to select a Campus for the Financial Account is missing.

Webforms Block:
<img width="2052" alt="Screenshot 2024-12-11 at 19 37 12" src="https://github.com/user-attachments/assets/8b296ff5-6544-4c10-8f47-5a32a9c15428" />

Obsidian Block:
<img width="2054" alt="Screenshot 2024-12-11 at 19 37 50" src="https://github.com/user-attachments/assets/2517dffa-081c-4e92-8623-b2f68152b513" />

### Actual Behavior

There is no Campus option for the Financial Account.

### Expected Behavior

There should be a Campus option for the Financial Account.

### Steps to Reproduce

See above.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v1.17.0.33

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@mikedotmundy  Can you verify that you have multiple campuses defined (and active) on that test system.  Most parts of Rock will hide the campus picker if the system has only one campus.

**Comment by mikedotmundy** [comment]
Ah I completely forgot to check that. My apologies @nairdo!
