### ISSUE TITLE
Unable to Choose Email Preference Entry Block from Page Zones Modal

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#6129]
### Description

I'm not sure exactly which version this happened in, but we are on v16.6, and so is the demo site. So it could have started at v16.6.

This is an issue in v16.6 and v16.7.3. This is not an issue in v17.0.33.

The Email Preference Entry Block (Obsidian) exists but it is not selectable from the Page Zones Modal. Here is a screenshot from [this](https://rock.rocksolidchurchdemo.com/page/276) page on the demo site, currently running v16.6. This shows that the block does exist (this is correct).
<img width="2036" alt="Screenshot 2024-12-14 at 13 46 07" src="https://github.com/user-attachments/assets/6ebf1364-a2a0-43ac-8f6b-fa62efb408b4" />

Also, from the Block Type Detail page, you can see the block does exist and it will show you what page it exists on (this is correct):
<img width="2048" alt="Screenshot 2024-12-14 at 13 51 07" src="https://github.com/user-attachments/assets/8a729426-0fce-429f-a273-2b3e6dbce0ac" />

However, here is what it looks like when I try to add the block to the page from the same Page Zones Modal:
<img width="2045" alt="Screenshot 2024-12-14 at 13 47 03" src="https://github.com/user-attachments/assets/91bd98bd-c3ff-4319-b3c4-389154505248" />

Also, I am able to generate an error message if I try to click on the Email Preference Entry block that _currently_ exists on the page:
<img width="2044" alt="Screenshot 2024-12-14 at 13 41 38" src="https://github.com/user-attachments/assets/31e5f4d6-9096-4014-8700-165061b0e97f" />

Here is a screen recording to show exactly how I got that error to appear:
https://github.com/user-attachments/assets/0228ae00-d8e0-47dd-abf6-ee45bcfcb60d

Here is the exception with stack trace:
<img width="1914" alt="Screenshot 2024-12-14 at 13 50 50" src="https://github.com/user-attachments/assets/78e6c385-5b56-4ba8-8263-7bdde3820806" />

### Actual Behavior

1. You cannot select the Email Preference Entry Block from the Page Zones modal.
2. From the Page Zones modal, if you try to click on the Email Preference Entry block on `/page/276`, you will be greeted with an error message and an exception is logged.

### Expected Behavior

1. You should be able to select the Email Preference Entry Block from the Page Zones modal.
2. No error should be shown by clicking on the existing Email Preference Entry block in the Page Zones modal.

### Steps to Reproduce

- Ensure you are on v16.6 or v16.7 (possibly an issue in earlier versions - I am unsure).
- Go to `/page/276`
- In the bottom admin bar, click the Page Zones button
- Try to add the Email Preference Entry block
- See it is not selectable
- Also try to click on the already existing block
- See error message

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.6, v16.7

### Client Culture Setting

en-US

**Comment by mikedotmundy** [comment]
Thanks @chead4 - I have v1.16.7.3 (the last Alpha round) installed on our dev server and it is an issue there.

**Comment by mikedotmundy** [comment]
Also, I realize this is fixed in v17.0 - but if it does prove to be an issue in v16.7, I wasn't sure if it could be worked into that version somehow. It will be quite a while before we have v17 installed in production. Thanks!

**Comment by JimMichael** [comment]
I am able to dupe this on 1.16.7.3 ALPHA. I wonder if it's fixed in 16.7.3 BETA? (They've been known to sneak un-announced changes into betas...)
![image](https://github.com/user-attachments/assets/8155df40-0fb4-4e6d-8a0c-6ec53f64f9db)

**Comment by chead4** [comment]
Thank you all for jumping in and confirming this issue.  We will fix this in v16.7.

**Comment by chead4** [comment]
This is resolved in v16.7 with [commit](https://github.com/SparkDevNetwork/Rock/commit/90cc93ed1aa1d76db43ee66eddb4f1cc1b58a9b6).

**Comment by tpeera** [comment]
I am on 1.16.7.4 and this still seems to be an issue. I cannot select it, and where it is selected I get the same error. However, I assume this is fixed with that commit and will be in the actual release (I am on beta)

**Comment by mikedotmundy** [comment]
@tpeera I could be wrong, but I believe this was an issue in v16.7.4 (beta). I discovered it in our v16.6 Production environment and then again in our v16.7.3 Alpha instance after v16.7.4 had been released to Beta.

**Comment by chead4** [comment]
@tpeera & @mikedotmundy Apologies for the delayed response! This issue is present in v16.7.4 and has been resolved in v16.7.5.
