### ISSUE TITLE
Obsidian Registration Entry - Fees with cost of $0.00 still shows the ($0.00) in the drop down

### ISSUE THREAD

**Issue by treusch** [SparkDevNetwork/Rock#6131]
### Description

In the original Registration Entry block, optional fees on registrations did not show the ($0.00) cost in the drop down list for fees that did not have a cost associated.

In the Obsidian Registration Entry block, however, these $0.00 fees still appear.

The original block code was written in such a way that the options for the list were created without including the "($0.00)" in the text if the fee was 0. 

The new block uses a new function that will return an empty string for that part of the display if the value passed in is NULL, but if the value passed in is 0, it builds the formatted string including the $0.00.

### Actual Behavior

In the original Registration Entry block, the $0.00 fee is not in the list. (Desired outcome)
![image](https://github.com/user-attachments/assets/01b5419f-d859-4253-a9df-73bf657255ee)

In the Obsidian Block the options include the ($0.00)  (Not the desired outcome)
![image](https://github.com/user-attachments/assets/20b28ed1-7ea1-47f2-8e0f-2412cc928546)
/
/

### Expected Behavior

Expected Behavior - that the Obsidian Block would display the fees (or not display them) the same way the original block did OR give the user the option when setting up the fees as to whether they want the ($0.00) to appear in the list or not, since not showing them was the default behavior of the original block.

To be certain I am being clear, it's the display of "($0.00)" not the display of the fee itself that is the concern.

### Steps to Reproduce

- Add fees to any registration template with a $0.00 cost.
- Add a registration instance using that template.
- Attempt to register for the event using the instance created and the original block and you will see that the fee name and how many remain available will appear, but not the $0.00 cost.
- Do the same thing but using the Obsidian Registration Entry Block and you will see that the drop down includes the fee name, the $0.00 cost and the remaining available

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6

### Client Culture Setting

en-US

**Comment by chead4** [comment]
Hi Tina - Thanks for reporting the issue.  I am happy to share that this issue has been resolved in v16.7 with commit [b85fde4](https://github.com/SparkDevNetwork/Rock/commit/b85fde4e8d39d81026a7f70dae30402ac97a5227).

**Comment by chead4** [comment]
@treusch No worries at all, Tina. This fix wasn’t included in our release notes, but I really appreciate you taking the time to check!
