### ISSUE TITLE
Saved ACH accounts are usable for Event Registrations when Use Allow ACH processing for Events is disabled

### ISSUE THREAD

**Issue by andypullen** [SparkDevNetwork/Rock#6133]
### Description & Actual Behavior

On the Obsidian Event Registration block, a users' saved ACH payment profile is selectable even when the "Allow ACH processing for Events" option is disabled in the Financial Gateway settings.

### Expected Behavior

Saved ACH accounts should not be selectable when ACH is disabled at the Financial Gateway settings.

### Steps to Reproduce

- Use an ACH account to give and save the account for future use (or create the payment profile by any other method)
- Go to Admin Tools > System Settings > Financial Gateways and select No under "Allow ACH processing for Events"
- Create an event registration using the edited financial gateway
- Register for the event while logged in
- The saved ACH account will be a usable payment method for the event registration

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@andypullen Hi Andy - To assist us in investigating the issue, please include screenshots of the issue you're experiencing.

**Comment by chead4** [comment]
@andypullen Hi Andy - Sorry for any confusion.  We will have a fix for this issue in an upcoming version of Rock.

**Comment by chead4** [comment]
@andypullen Hi Andy  To address a change in direction from the original solution to issue #6133, we’re in the process of updating the Obsidian Registration Entry block. Could you let us know which financial gateway you’re using?

**Comment by nairdo** [comment]
We've made some additional changes ([abc123](https://github.com/SparkDevNetwork/Rock/commit/621a60f6faaa0620a314e39449be0459151ce0b7) and [b65d35b](https://github.com/SparkDevNetwork/Rock/commit/b65d35bfb19e4044ce4e9e12765987b86809befb)) in v17.1 and added options to the Obsidian Registration Entry block, allowing Rock administrators to enable or disable ACH and credit card payments for registrations -- however, to be clear, the selected payment gateway must also support the HostedPaymentInfoControlOptions in order for the EnableACH and/or EnableCreditCard settings to be respected.
