### ISSUE TITLE
Add 'Days to Birthday' and 'Days to Anniversary' to Data View and Report Person fields - enhancement

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#662]
In Communication there is a merge field 'Days to Birthday' - this is really useful.

![bday1](https://cloud.githubusercontent.com/assets/4658177/5063203/bc69a44a-6e41-11e4-8f48-2103ace1524e.jpg)

Can 'Days to Birthday' be added to the selection fields available for Person Data View and Reports?
And 'Days to Anniversary'?

This will allow the easy running of reports to list those whose birthday or anniversary is coming up in the next 14 days.  (I can't see any other way to do this?)

![bday2](https://cloud.githubusercontent.com/assets/4658177/5063237/e673c6d4-6e42-11e4-9f15-438609635f7c.jpg)

**Comment by arranf** [comment]
`Days to Birthday` is implemented, `Days to Anniversary` isn't.

**Comment by cabal95** [comment]
So I didn't notice @garrettjohnson's PR initially, but I went the same route he did initially and it didn't show up as a DataView option (which I realized was because it wasn't a database column). His code changes take care of the C# side of things and I believe mine takes care of the DataView / Database side of things, so both might be necessary for a full addressing of this.

**Comment by garrettjohnson** [comment]
@cabal95 I did something wrong on my PR because the CI build failed on me. 🙃I'll try to revisit it tomorrow.

**Comment by cabal95** [comment]
Sorry to stomp on your PR. I saw you marked it "in progress" on feb 11, but my brain registered that as "feb 11 2017". And I somehow completely missed that you had already submitted a PR related to it.

Trying to knock the last of those 2014 issues out of the park.

**Comment by garrettjohnson** [comment]
@cabal95 No worries at all! I botched the PR so badly I ended up just closing it... Forgot to remove the in progress tag. Sorry!
