### ISSUE TITLE
page and block settings, and photo uploads from phone not browser-width responsive.

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#677]
There are times when I have tried to access or edit a block's settings or page's security settings from my iPhone and all I can see and manipulate is the center of the settings screen--can't see the save or cancel buttons either. 

I had the same issue when I tried to upload a photo from my phone (going through the photo request workflow). I was able to select the photo from my photo library. When the crop or adjust screen came up the left half of the image was off the screen and I couldn't scroll to the left to adjust the selection tool. Didn't have access to the save or upload button either.

First screenshot is in portrait position
![img_0083](https://cloud.githubusercontent.com/assets/5738650/5115153/64b4974a-7004-11e4-851f-0aa706b289e1.PNG)

Landscape position
![img_0084](https://cloud.githubusercontent.com/assets/5738650/5115157/6805a132-7004-11e4-994c-69bed103e444.PNG)

**Comment by mikepetersonccv** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/2f320e427da16dc2aec74c5f5fd8e2a69b5b3366
