### ISSUE TITLE
Add IDE settings to Solution Items folder?

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#691]
It would be helpful if one of the development team could add their VS settings to the Solution Items folder in the form of a settings export file.

For example:
1. Select "Tools/Options/Tools/Import and Export Settings.../Export selected environment settings"
2. Select settings for "All Settings/Options/Text Editor/C# Editor"
3. Save to "rock_vs2012.vssettings".

This would help new developers configure their environment with the same code formatting options as the rest of the team by simply importing the vssettings file into their own environment.

If the team also use Resharper, it would be helpful to have a similar "team-shared" DotSettings file to standardise code-formatting/cleanup options. Among other things, this could include the standard Copyright header.

**Comment by arranf** [comment]
@nairdo If this is a quick 5 minute job this would be really helpful!

**Comment by arranf** [comment]
@MrUpsideDown This is done in part now.

**Comment by edmistj** [comment]
Sweet!

**Comment by MrUpsideDown** [comment]
@arranf, I completely missed your recent updates to this issue, sorry. Thanks for taking the time to put this settings file together, it will be very helpful if we can get a standard dev environment happening.
