### ISSUE TITLE
Broken default communications template on new install

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#740]
As [described here](http://www.rockrms.com/page/278?question=291) by Jim Michael
![image](https://cloud.githubusercontent.com/assets/383807/5428473/3eff8eb0-8382-11e4-93d6-251ef33ce5d6.png)

**Comment by ccofnow** [comment]
After installing v2.0 I note that the global attributes email header and email footer are still corrupted as shown in Jim's post.
