### ISSUE TITLE
Email footer display not user friendly on tablet

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#742]
Email footer looks like this on samsung galaxy Note 8.  In portrait mode the words are bunched up in the far right column which is one character wide.  Turning the tablet to landscape mode displays the contact information inside the grey box.  Turning the tablet back to portrait now shows the contact information, but to the right of and outside the grey box.   (I've had some inconsistent results in testing this.)
![screenshot_2014-12-17-22-27-18](https://cloud.githubusercontent.com/assets/4658177/5451249/71ddce08-8573-11e4-9d12-230bcc72b81e.png)

**Comment by edmistj** [comment]
Closing. Will re-open if others have the same issue.
