### ISSUE TITLE
Select Photo link does nothing on tablet  

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#743]
The Select Photo link on the /PhotoRequest/Upload/.... page does not do anything on a Samsung Galaxy Note 8, using the default browser.  (Linked to this page from the Email app.)
(I'm just going to add a comment to the page that 'if you are having problems doing this on your tablet then please use a PC.)

**Comment by sheck** [comment]
This should resolve the issue for newer versions of Android.
