### ISSUE TITLE
Group Attendance Data View Filter Doesn't Keep Specified Weeks

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#744]
I tried creating a Data View where it finds Persons with the connection status 1st Time and who have recently attended the group 10:30 AM Worship (at least once within the past four weeks).  I attempted this with the Recent Attendance filter but couldn't get it to work and noticed that it didn't save weeks at 4 but used the default 16.

"INFO: There was a problem with one or more of the filters for this data view...

Attended '8:45 AM Worship' Greater Than Or Equal To 1 times in the last 16 week(s): 'Attendances' is not a member of type 'Rock.Model.Person'"

**Comment by BEGamache** [comment]
This issue is still present in Rock 2.0. The last part "Attendances is not a member of type Rock.Model.Person" is fixed but the weeks issue hasn't been fixed in 2.0. I can manually change the weeks option in the database but once I go back into the Data View to make some changes to the other filters, once I click Save it gets reset to 16 again.

**Comment by mikepetersonccv** [comment]
How about creating a new Issue instead.  That way we can track that the Attendances part of the issue was fixed, but that the Weeks issue isn't. :)

**Comment by BEGamache** [comment]
Ok. Thank you
