### ISSUE TITLE
Exception thrown: Financial Manager cannot add an account to finances->administration->accounts

### ISSUE THREAD

**Issue by ccofnow** [SparkDevNetwork/Rock#754]
Our Finance Manager (security groups: Staff Users, Finance Administrators) tried to add all of our accounts into the Accounts List today, but when she clicks the (+) button, an exception is thrown. So it appears I alone (as the initial Rock Administrator user created upon installation) can presently add accounts.

The exception list shows:
System.Web.HttpUnhandledException System.Web Exception of type 'System.Web.HttpUnhandledException' was thrown. 
and
System.NullReferenceException System.Web Object reference not set to an instance of an object. 

Let me know if there is other information I can provide.

**Comment by azturner** [comment]
@ccofnow , this has been fixed for the next release.  In the mean time, you can also "fix" this now in your installation by doing the following:

1. Under `Admin Tool` > `Entity Administration` find the row for *Rock.Model.FinancialAccount* and click the security icon.
2. Click the **Edit** tab, and add the *Finance Administrators* role with *Allow*
