### ISSUE TITLE
Address Verification: Melissa Data

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#761]
Using the Melissa Data verification service I edited an address to be deliberately wrong and then pressed the globe verification button. No exception was produced, the orange rock loading bar image was shown however there was no change to address. Using their [Address Check](http://www.melissadata.com/lookups/AddressCheck.asp) tool there should have been a change in address.

Looking at their web panel Rock appears to be using the Melissa Data API once per day when the Location Services job runs.

The same response occurred on the Rock demo server using a US address.

**Comment by azturner** [comment]
@arranf How are your verification services configured? Which ones are active and in what order?

**Comment by MrUpsideDown** [comment]
I have a similar problem to the first part of this question - when verifying an address using Bing, there is no feedback to indicate the result of the verification. The loading image is displayed briefly, and that is all. It is only by checking the database table that I can discover that the verification failed.
It would be very useful to display the last verification result beneath the address so the user can tell if the address is verified or not.

**Comment by arranf** [comment]
Hey David,
My two reported issues were with just one service activated at a time.
I was testing both Bing and Melissa Data out separately.

Arran

**Comment by arranf** [comment]
@edmistj Could I ask why this is tagged as an enhancement rather than a bug? 

I'm seeing two issues. One from @MrUpsideDown about the loading screen (an enhancement), and the original issue I raised about Melissa Data not appearing to verify addresses which I believe is a bug.

If this is not reproducible on your end I'm happy to let you use my key for testing purposes or to attempt to get you some more data. I'm asking the question just to flag up that on my end this isn't working as expected.

**Comment by edmistj** [comment]
@arranf It was the lack of feedback that was listed as an enhancement. Didn't realize you were still getting an exception. If you email me the key and some sample addresses that cause an exception we'll take a look at it.

**Comment by arranf** [comment]
@edmistj Just thought I'd update you. This may be an issue on my end. I've tried calling their API via Postman with my API key and I'm getting error codes but that may be due to  ill formatted queries.

Testing this further is on my to do list and I'll update here and email you when I've done that.

**Comment by edmistj** [comment]
@arranf OK, keep us posted.

**Comment by azturner** [comment]
@arranf Any updates on this?

**Comment by arranf** [comment]
I put this on the back burner and I didn't get a chance to look at this.
Our trial key has expired and we've moved onto using Ideal Postcodes
instead. There may well still be an issue here but I can't confirm it.
