### ISSUE TITLE
Address Verification: Bing (International Addresses)

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#762]
Using the Bing verification service addresses are being changed however the edit is appearing differently in two locations and postcodes are being truncated. I'm not sure addresses are being fed correctly.

If input the address:
![screenshot_2](https://cloud.githubusercontent.com/assets/8703222/5612423/ba609cec-94cc-11e4-9575-72cec3419ea5.png)
8 Princewood Road
Corby Northamptonshire
United Kingdom

It is displayed as
![screenshot_1](https://cloud.githubusercontent.com/assets/8703222/5612422/ba4751c4-94cc-11e4-8b3f-2138a292e7ee.png)
Editing it appears as
![screenshot_3](https://cloud.githubusercontent.com/assets/8703222/5612540/9df4a42a-94ce-11e4-83de-d01378952370.png)

The postcode that it should be is NN17 4AP.

**Comment by azturner** [comment]
@arranf, I can't reproduce the unformatted vs edit mode showing two different values.  Once Bing standardizes this address, both the display and edit views show the same thing for me.  However the "8 Princewood Road Corby Northamptonshire United Kingdom" does appear to be standardized by Bing as "8 Princewood Road, Earlstrees Industrial Estate, NN17 4"...

![image](https://cloud.githubusercontent.com/assets/548180/5655011/75816802-9686-11e4-91e2-1d17969ab2ba.png)

Do you see it being standardized by Bing (outside of Rock) differently?

**Comment by arranf** [comment]
@azturner 
The truncated postcodes seems to be standard for Bing, which is very unusual. That's definitely not a Rock issue -- sorry for flagging it as one.

I'll test out the display and edit mode issue again and if I can't reproduce I'll close this myself.

**Comment by arranf** [comment]
After testing again I can't reproduce this.
