### ISSUE TITLE
"State" Address Field Truncated

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#763]
![screenshot_2](https://cloud.githubusercontent.com/assets/8703222/5612423/ba609cec-94cc-11e4-9575-72cec3419ea5.png)

**Comment by edmistj** [comment]
The truncation here is from the responsive nature of Bootstrap. The grid will expand/contract to fill the space.  Sometimes this means the value won't fully fit in the dropdown. We do have plans for enhancing the family edit page in the future that should help with giving the address area a bit more space. Closing for now...
