### ISSUE TITLE
AttributeValue.ValueAsDateTime returns null for some types of Dates

### ISSUE THREAD

**Issue by mikepetersonccv** [SparkDevNetwork/Rock#764]
If a date is stored as a non-ISO-8601, it should be nice and convert that to a date even though they should be stored as ISO-8601.  Also, if it is in a short form of ISO-8601 for example '2015-01-02T00:00:00', it isn't converting it.

**Comment by mikepetersonccv** [comment]
updated the comments in https://github.com/SparkDevNetwork/Rock/commit/3253aa0cda0e3636ff7b4ec22bc983b6eee0c7de, and just needs a migration now

**Comment by azturner** [comment]
Migration Added here: https://github.com/SparkDevNetwork/Rock/commit/ec5dc8b0b03d397ddc9e79f6ad357cd696799935
