### ISSUE TITLE
Empty Forgot Username Email

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#765]
When users request their username it shows most of the email correctly, just not the username.

**Comment by azturner** [comment]
@BelAirIT, the 2.0 update should have updated the "Forgot Username" system email with some updated merge fields.  Can you share what your system email looks like?

**Comment by BelAirIT** [comment]
![image](https://cloud.githubusercontent.com/assets/7409839/5649717/f4af6500-964c-11e4-852f-044b62d3d9fc.png)

**Comment by azturner** [comment]
Actually meant the template source under `Admin Tools` > `Communication Settings` > `System Emails` > `Forgot Usernames`. For example, it should look like this...

	{{ GlobalAttribute.EmailHeader }}

	Below are your current usernames at {{ GlobalAttribute.OrganizationName }}<br/>

	{% for Result in Results %}
		<br/>
		For {{ Result.Person.NickName }} {{ Result.Person.LastName }},<br/><br/>
		{% for User in Result.Users %}
			 <table style="width: 100%"><tr><td style="font-weight: normal; font-family: Helvetica, Arial, sans-serif; font-size: 14px;">
					 <strong>Username:</strong> {{ User.UserName }}</td><td>
						 <table class="tiny-button button reset-password" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100px; overflow: hidden; padding: 0;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: center; display: block; width: auto !important; color: #ffffff; background: #2795b6; padding: 5px 0 4px; border: 1px solid #2284a1;" align="center" bgcolor="#00acee" valign="top">
									  <a href="{{ ConfirmAccountUrl }}?cc={{ User.ConfirmationCodeEncoded }}&action=reset" style="color: #ffffff; text-decoration: none; font-weight: normal; font-family: Helvetica, Arial, sans-serif; font-size: 12px;">Reset Password</a>
									</td>
								  </tr>
			 </table></td></tr></table>
		{% endfor %}
		<br/>
	{% endfor %}

	{{ GlobalAttribute.EmailFooter }}

And am just wondering how your's differs.

**Comment by BelAirIT** [comment]
{{ GlobalAttribute.EmailHeader }}

Below are your current usernames at {{ GlobalAttribute.OrganizationName }}<br/>

{% for Result in Results %}
	<br/>
	For {{ Result.Person.NickName }} {{ Result.Person.LastName }},<br/><br/>
	{% for User in Result.Users %}
		 <table style="width: 100%"><tr><td style="font-weight: normal; font-family: Helvetica, Arial, sans-serif; font-size: 14px;">
                 <strong>Username:</strong> {{ User.UserName }}</td><td>
                     <table class="tiny-button button reset-password" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100px; overflow: hidden; padding: 0;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: center; display: block; width: auto !important; color: #ffffff; background: #2795b6; padding: 5px 0 4px; border: 1px solid #2284a1;" align="center" bgcolor="#00acee" valign="top">
                                  <a href="{{ ConfirmAccountUrl }}?cc={{ User.ConfirmationCodeEncoded }}&action=reset" style="color: #ffffff; text-decoration: none; font-weight: normal; font-family: Helvetica, Arial, sans-serif; font-size: 12px;">Reset Password</a>
                                </td>
                              </tr>
		 </table></td></tr></table>
	{% endfor %}
	<br/>
{% endfor %}

{{ GlobalAttribute.EmailFooter }}

**Comment by BelAirIT** [comment]
![image](https://cloud.githubusercontent.com/assets/7409839/5650081/e85c66d8-964f-11e4-9f49-e1e8e358c69a.png)

**Comment by azturner** [comment]
Ok, sorry, it's not the template. Looks like it might actually be an issue just for Active Directory usernames.  Database usernames seem to work fine. Is your login an Active Directory login?

**Comment by BelAirIT** [comment]
Yes, it is.
