### ISSUE TITLE
"Last Save Date" report

### ISSUE THREAD

**Issue by ccofnow** [SparkDevNetwork/Rock#769]
This seems like a pretty basic configuration, so even though I haven't asked the forum I have to assume this is a bug.

I've created a new Data View, called "Updated People". It applies to "Person", and the only filter is of type "Person Fields", specifying that "Last Save Date" is "Greater Than" "12/10/2014". (the date was selected by picking a date in the date picker).

But I get an empty list. We've been making changes like crazy, you can imagine. Updates as well as new people. There should definitely be something in that box...

**Comment by azturner** [comment]
"Last Save Date" is actually a person attribute for when the person last took a DISC test.  This should be renamed to be more descriptive, and the "Modified Date Time" property needs to be exposed to report filters.

**Comment by ccofnow** [comment]
Guess that's what I get for not asking around, lol. Thanks for the info.

**Comment by azturner** [comment]
This was updated here: https://github.com/SparkDevNetwork/Rock/commit/cb1c28931b1d07720aa2af62350ecb7c88ef4e43
