### ISSUE TITLE
Family Members List on Person Page - Sort Order is unpredictable.

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#772]
The sort order of people in the list of other Family Members does not follow a predictable pattern.
For the same Person record, it can vary from one record access to the next.

Suggest that the sort be modified to provide more predictable results - something like:
1. Role (Adult > Child)
2. DOB.
3. First Name.

**Comment by azturner** [comment]
@MrUpsideDown , are you referring to this display...

![image](https://cloud.githubusercontent.com/assets/548180/5695184/0a6fa910-9952-11e4-9e1d-78ef71824e31.png)

If so, that should already be sorted like so:
1. Role & Gender ( Adult Male > Adult Female > Child )
2. Age Descending ( DOB )

For example [Ted Decker's family](http://rock.rocksolidchurchdemo.com/Person/23) on demo site will always display in this order: Ted, Cindy, Noah, Alex.

Are you not seeing that behavior?

**Comment by MrUpsideDown** [comment]
Ok, I might need to retract the comment about the order being random - I think it might have been caused by another user updating the birth dates of some family members while I was viewing/refreshing the record - sorry!

With regard to the sort order though, I have a situation which is somewhat confusing. When viewing the father's record for a family that has a male child of adult age and a mother, the male child is listed before the mother in the sort order.

The male child has been given the role of Adult in the family because he is of adult age, which seems sensible. However, it seems the "Adult" family role is only actually expected to be assigned to the parents in this case - is that correct?

Removing Gender from the sort order would fix this, but is the intention that I should not ever assign the role of "Adult" to family members other than the parents in a family?

**Comment by azturner** [comment]
Most the organizations we work with will remove children from their parent's family when that child becomes an "adult" and place them into their own new family. Then also add an "Adult child of" relationship back to their parents. In the future we actually hope to make that process much easier (either a single click, or a job that does it based on a child's age). So even though they may still reside at the same address, we would consider them two different families. This makes it much easier to determine the structure of families.

**Comment by MrUpsideDown** [comment]
Thanks, that sounds like a workable solution given the existence of the "Adult child of" relationship to provide a link back to the parents.

The only thing that becomes a little more difficult with this approach is identifying adult singles that still live with their parents. Perhaps it might be a useful enhancement to the Family Detail block to also show links to other people living at the same address (flagged accordingly)?

**Comment by arranf** [comment]
I also have an interesting case. I live at the same address as another
family. Should I be grouped with that family or is living at the same
address enough record wise?

What about housemates?

**Comment by MrUpsideDown** [comment]
@arranf - using the strategy suggested by @azturner, you would be in a separate family at the same address, as would each housemate. I think Family <> Household in this case - it seems to strictly define the relationship between partners and dependent children. Everything else is defined by Known Relationships. At least, that's my understanding of what @azturner is saying.

**Comment by MrUpsideDown** [comment]
@azturner: To try and further clarify this issue (for me at least!), would it be fair to say that the "Adult" and "Child" relationships in a family are actually intended to reflect the dependency status of the family members? So a "Parent" is any member of the Family who can be considered legally responsible for other members of that same Family (ie, a guardian), and a "Child" is any member who is dependent on another member of the same family for their care (ie. a dependent)? So rather than being about age, this Role actually indicates responsibility?

**Comment by azturner** [comment]
It's really up to each organization to define exactly what their definition of parent/child relationships is, and their processes around that. At CCV, we do use it strictly for a actual parents and children of those parents. If for example, a family was caring for a friend or relative's child in their home ( even as a legal guardian), we would most likely still keep that child as their own family with known-relationships created that describe the relationship between them and the host family.

I'm going to go ahead and close this as an issue.

**Comment by MrUpsideDown** [comment]
Ok thanks for the clarification. FYI, we have renamed the "Child" role as "Dependent", and follow the rule that the "Adult" in a family is responsible (in some way) for all of the Dependents. We found the role of "Child" was a bit confusing in the situation where children of adult age are living at home and are therefore still considered (by us) to be members of the Household/Family group.
