### ISSUE TITLE
Rock Administrators aren't Communication Administrators

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#773]
I'm on Rock McKinley 2.0.  Just having my user as a Rock Administrator does not allow it to Approve a Website Ad (the Status section is blank in the Content Details).  Once I put myself in the Communication Administrators role, the Status section now appeared and I can approve.  I think it's a bug because in my Content Channel Items security, Rock Administrators have inherited rights to Administrate.  Thanks!

**Comment by edmistj** [comment]
Added migration to add 'Rock Administrators' to be able to 'Approve' content channels. Note that the 'Administrate' action is different than 'Approve'.
