### ISSUE TITLE
Date Format in Attribute Values Block does not respect System Date Settings

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#775]
Date Fields displayed in the Attribute Values Block show MM-DD-YYYY dates even if the system settings are set to DD-MM-YYYY.

**Comment by arranf** [comment]
See https://github.com/SparkDevNetwork/Rock/issues/545
Rock culture is set via browser culture rather than server culture.

Date Fields displayed in the Attribute Values Block show MM-DD-YYYY dates
even if the system settings are set to DD-MM-YYYY.

—
Reply to this email directly or view it on GitHub
<https://github.com/SparkDevNetwork/Rock/issues/775>.

**Comment by MrUpsideDown** [comment]
Yep, that's the problem alright. Thanks for providing the workaround.

I'm not sure how difficult this is to fix, but it is an inconsistent user experience to have some dates shown in the server culture and others with the browser culture...
and as you pointed out on the other thread, this is bound to cause confusion for users.
Can this be tagged as an Enhancement?

**Comment by azturner** [comment]
If there are dates being displayed in browser that don't honor the browser's culture setting, that would be an issue. Can you identify where you are seeing those?

On Jan 15, 2015, at 3:01 PM, MrUpsideDown <notifications@github.com<mailto:notifications@github.com>> wrote:


Yep, that's the problem alright. Thanks for providing the workaround.

I'm not sure how difficult this is to fix, but it is an inconsistent user experience to have some dates shown in the server culture and others with the browser culture...
and as you pointed out on the other thread, this is bound to cause confusion for users.
Can this be tagged as an Enhancement?

-

**Comment by azturner** [comment]
@MrUpsideDown, Any feedback on which dates aren't being formatted according to browser's culture setting?

**Comment by MrUpsideDown** [comment]
Sorry, I must have missed your previous comment. As per @arranf 's comment above, it seems that the issue is actually caused by the fact that dates in this block *do* honor the browser's culture setting, but other page elements use the server culture settings. 

The end result is that if the browser culture is set differently to the server culture, the page displays  two different date formats, which is confusing for the user. My request for an enhancement was to see if it would it be possible to render *all* dates displayed on a page using the browser culture only?
