### ISSUE TITLE
Person Attribute "Baptized Here" should be tri-state not Boolean?

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#776]
This field should default to a Null or "Unknown" state indicating that the question is unanswered.
The default to "False" is misleading because it indicates the question has been answered in the negative.

**Comment by azturner** [comment]
Other organizations (ours) use that attribute in conjunction with the Baptism Date attribute to know whether an individual really has or hasn't been baptized, but you can easily change it in your installation to have an "unknown" (or blank) value...

![image](https://cloud.githubusercontent.com/assets/548180/5695278/8309287a-9956-11e4-9329-85dfde301cf3.png)

**Comment by MrUpsideDown** [comment]
Thanks, I have changed this for our install - I was suggesting that maybe this should be the default for new databases also, because of the confusion it may cause for others?
