### ISSUE TITLE
Unexpected behavior when setting Device Location(s)

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#783]
This seems to be more of a data validation issue than a usability issue since I can't find anything that's broken by it (yet). 

If you change the location on Main Campus: Central Kiosk to Bldg 1 (or anything else), the code doesn't assign the LocationId correctly.

I would expect the Device.LocationId to point to Bldg1's LocationId but it doesn't.  Instead it creates a new Location with no data and assigns the Device.LocationId to that:
![screenshot 2015-01-15 12 40 12](https://cloud.githubusercontent.com/assets/1210933/5763049/d77c30c6-9cb4-11e4-88c2-faaed8c4f75b.png)

The problem appears to be with L151:
https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Core/DeviceDetail.ascx.cs#L151

In debug mode, Device.Location is never set, but Device.Locations can have multiple items.  Maybe a 
if ( Locations.Count ==  1) { Device.Location = Device.Locations.FirstOrDefault() } would work?
![screenshot 2015-01-15 12 36 27](https://cloud.githubusercontent.com/assets/1210933/5763086/4335d010-9cb5-11e4-9304-7cf636925337.png)

Related, data migration issue?
On a fresh build, Device.LocationId is NULL in the database for Central Kiosk, but if you visit DeviceDetail, Main Campus is already in the list.

It's also entirely possible @mikepetersonccv is doing some magic behind the scenes that I don't understand :)

**Comment by mikepetersonccv** [comment]
Yep, Device.Location vs Device.Locations is a little confusing.  The comments in Device.cs try to explain it a bit.  To clarify, Device.Location is the "physical" location (GeoPoint/GeoFence) of the device independent of it's logical locations (the campus, building, etc).  A Device.Location of NULL (or a Device.Location that has no GeoFence or GeoPoint) is OK.  It would mean that nobody bothered or needed to set the physical location of the device.  You probably want Device.Locations (logical) in your situation. Does that help?

**Comment by dcs619** [comment]
Clarified, closing issue.  I haven't found a simple way to get a device/kiosk's corresponding Campus.

**Comment by azturner** [comment]
@dcs619 , Not sure if this helps or not, but the KioskDevice's Read method calls LoadKioskLocations() for each of the locations associated with a device.  That method will evaluate each of those locations, and travel their parent heirarchy looking for any location that is also a campus location. If it finds a campus in the heirarchy, it will set the CampusId property on the KioskLocation object that is created. That is how we determine campus for the unattended check-in.

**Comment by dcs619** [comment]
@azturner Yes, that helps.  Our checkin devices are centralized so their Location is set to the campus level.  However, I have to traverse to Kiosk..KioskGroupTypes..KioskGroups..KioskLocation to get CampusId.

Is there an easier or simpler way to write this query?

var kioskCampusId = CurrentCheckInState.Kiosk.KioskGroupTypes
.Where( gt => gt.KioskGroups.Any( g => g.KioskLocations.Any( l => l.CampusId != null ) ) )
.SelectMany( gt => gt.KioskGroups.SelectMany( g => g.KioskLocations.Select( l => l.CampusId ) ) )
.FirstOrDefault();
