### ISSUE TITLE
Edit Attribute Screen: Label incorrect for Field Type "Single-Select"

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#785]
When the "Single-Select" field type is chosen, the additional settings fields are labelled "Values" and "Field Type". The "Field Type" label should be changed to "Selection Type" to avoid confusion.

**Comment by azturner** [comment]
Updated label to  'Control Type', and help text to The type of control to use for selecting a single value from the list.'

**Comment by MrUpsideDown** [comment]
Excellent, thanks... and my apologies if the suggested fix in my original comment sounded more like a command!
