### ISSUE TITLE
Content "Pending/All Items" toggle could auto set items filter 

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#787]
I expected the toggle "Pending/All Items" to also set the Status filter on the Content page.
It seems like a double up to also have to set the 'Status' filter to limit items displayed to only those pending.  If the workflow is to come to this page for the purpose of approving those items that are pending, it would be easy to set the toggle to 'Pending' and for the item list to then also only show pending items.
![content1](https://cloud.githubusercontent.com/assets/4658177/5815433/761f6830-a0fa-11e4-82b1-3eb8b3afb504.JPG)

**Comment by edmistj** [comment]
We agree this block was confusing as written. We reorganized the layout a bit to make it more intuitive. The channel items still show as originally written. We felt it might be confusing to 'auto-filter' based on the selection of pending, but with the new layout we hope to have made it more intuitive.
