### ISSUE TITLE
DISC Personality Assessment Results badge not displaying results

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#792]
Rock McKinley 2.0
Have done the profile twice, but nothing is showing for the badge.  The badge is turned on.
Any suggestions?

**Comment by ElimAdmin** [comment]
Doesn't seem that the results were saved.  I've added a page to use the DISC results block, but it shows no results.  (I was unsure, when the results displayed after I did the profile, if I needed to do anything else to save them.  Maybe a clear comment on the final results page ["Your results have been saved."] would be reassuring.)

![disc1](https://cloud.githubusercontent.com/assets/4658177/5885849/68ac809c-a3df-11e4-820e-345024f72086.JPG)

**Comment by tcavaletto** [comment]
It may be that the attributes that DISC uses were not saved to the database on update. Go ahead and run this query on your database, and paste a screenshot of the results.

	SELECT [Key], [Id]
	  FROM [Attribute]
	  where [Key] in ('LastSaveDate', 'AdaptiveD', 'AdaptiveI', 'AdaptiveS', 'AdaptiveC', 'NaturalD', 'NaturalI', 'NaturalS', 'NaturalC', 'PersonalityType')

 
	Select Count(1)
	from [AttributeValue]
	Where [AttributeId] in (SELECT [Id]
	  FROM [Attribute]
	  where [Key] in ('LastSaveDate', 'AdaptiveD', 'AdaptiveI', 'AdaptiveS', 'AdaptiveC', 'NaturalD', 'NaturalI', 'NaturalS', 'NaturalC', 'PersonalityType'))
	  and [Value]  <>''

**Comment by ElimAdmin** [comment]
![disc2](https://cloud.githubusercontent.com/assets/4658177/5926938/c5d1e446-a6d3-11e4-934a-7d1f0d8802c9.jpg)

I noticed LastSaveDate was not in Attribute, so I manually added it...
![disc7](https://cloud.githubusercontent.com/assets/4658177/5927960/ad225f18-a6db-11e4-822b-89f9969ee817.jpg)

... and re-did the test.
If I look at all the Attributevalues for me, I see the Adaptives and the Naturals - but with no saved values, and there is no LastSavedDate AttributeValue for me; PersonalityType is there but with no saved value.

![disc3](https://cloud.githubusercontent.com/assets/4658177/5927899/ee26beb0-a6da-11e4-8470-797dc887b059.jpg)
![disc4](https://cloud.githubusercontent.com/assets/4658177/5927897/ee1fcbf0-a6da-11e4-8f89-50405ce6b2bf.jpg)
![disc5](https://cloud.githubusercontent.com/assets/4658177/5927898/ee21c126-a6da-11e4-927c-0ee2ec4e8663.jpg)

If it's relevant, I already had the Adapative and the Natural attributes set up.  I created these manually a while back prior to the DISC adding upgrade.  I checked these attributes, and it looks like the upgrade has updated the description of these values:

![disc6](https://cloud.githubusercontent.com/assets/4658177/5927940/5bfbf964-a6db-11e4-92cc-bc83714da8e6.jpg)

**Comment by ElimAdmin** [comment]
@tcavaletto This occured because I renamed the category of DISC attributes from 'DISC' to 'DISC and Strengths'. (I'm also keeping some other strengths attributes in the same category.)

But the following line in DiscService.cs only looks for 'DISC'.

 var discAttributes = person.Attributes.Values.Where( a => a.Categories.Any( c => c.Name == "DISC" ) ).Select( a => a.Key );

The bars now display, so this resolves my issue.  Up to you if this has implications for any changes that you might like to make to cater for this scenario in future.

**Comment by ElimAdmin** [comment]
The fact that the LastSaveDate attribute was missing might also suggest that 'DISC' is used during the v2.0 upgrade?  But if it wasn't found, then maybe it didn't write the new DISC attributes?

**Comment by nairdo** [comment]
Yep, that's a bug.  The DiscService should not use the Name property to find anything.  It should use a well known Guid.
