### ISSUE TITLE
External Inquiry Sample Workflow Mis-Configured

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#793]
I found that the External Inquiry Workflow's logic tests like "Test for General Inquiry" use the condition "Equal To" rather than "Starts With".

**Comment by edmistj** [comment]
I think this might be correct as the key for "General Inquiry" is "General". Ran a test workflow and it confirms to match correctly. Let me know if I'm missing something otherwise I'll close.

**Comment by treyhendon** [comment]
Interesting.  I turned in this bug after opening a workflow and it not assigning a worker.  I did also add a space after the colon so now it reads "General: General Inquiry" before testing.  Could that affect my results?

**Comment by treyhendon** [comment]
Oh, additionally, I copied the sample External Inquiry Workflow to a new workflow and was testing in the copy.

**Comment by edmistj** [comment]
The match is done on the Single Select's values key. The default for General Inquiry is 'General^General Inquiry,' where the 'General' before the ^ is the key. If this was changed then the match would stop working. You can see this by view the workflow's Topic attribute.

**Comment by edmistj** [comment]
OK, have more info. This is related to a previous fix we made post v2.0 release. See this Q&A topic for the details. http://www.rockrms.com/page/278?question=386

Closing now that this is solved.
