### ISSUE TITLE
Context isn't set when clicking add Security Group from person profile

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#795]
I created a New Person and gave him the new.user login.  However, clicking the '+' on Security Roles section goes to the /SecurityRoles page and doesn't remember the person context.

![screenshot 2015-01-21 12 52 32](https://cloud.githubusercontent.com/assets/1210933/5841694/d4bbf3b4-a16c-11e4-9874-36cbd5891a50.png)

I'd expect that the '+' would remember the person's context, while the Manage Security Roles link loads the roles for all users.

**Comment by mikepetersonccv** [comment]
This just ended up being a bug in GroupList.  There shouldn't be an Add button showing in the Person Profiles Security Roles grid, but it was appearing if there was a postback on the person profiles page.
