### ISSUE TITLE
History table has inconsistent cell widths and rows that are off the screen

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#797]
V2.0.
For some people the History for a person is displaying with every second row extended way off the screen to the right.  This is not consistent - some people's History shows correctly.

![hist1](https://cloud.githubusercontent.com/assets/4658177/5853110/e0776418-a284-11e4-8c09-77dc00df3f85.JPG)

![hist2](https://cloud.githubusercontent.com/assets/4658177/5853131/0330e902-a285-11e4-9136-21289b077b14.JPG)

Possibly due to History Did columns that contain text like:

![hist4](https://cloud.githubusercontent.com/assets/4658177/5853230/43b371e2-a286-11e4-96d8-313e2b4397f8.JPG)

Might need to work out how to split those long logged on to URLs over two lines.

**Comment by edmistj** [comment]
This has been fixed with the new responsive table in v3.0.
