### ISSUE TITLE
Suggestion: Rock Forums thread auto-watch

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#799]
It would be very useful if any time a user contributed to a post in the forum (either answer or comment), the thread was automatically set to "Watched" status.

I have a few instances where people have responded to my comments, and the response goes unnoticed because I forgot to mark the thread as watched.

**Comment by mkinyon** [comment]
Not a bad idea.  You should post it here though (http://www.rockrms.com/Rock/Ideas) since github is used more for bug tracking.

**Comment by arranf** [comment]
I'm not really contributing much to the discussion but @MrUpsideDown I'd recommend configuring your account to send emails from the forums you're interested in and then setting a filter on your mail client. 

I get probably between 0-10 emails a day (that skip my inbox) so it's digestible and I don't have to visit the forums unless I'm either asking or responding.

**Comment by nairdo** [comment]
Since this functionality is actually part of the Spark Development Network Q & A plugin, [this  enhancement](https://github.com/SparkDevNetwork/Rock-SparkSite/commit/93f71f156efd4077f409f03d9b5de62dc42d419e) should be [deployed on Monday](http://www.rockrms.com/page/470?Item=102) to the forums on our server.

**Comment by arranf** [comment]
@nairdo that link 404s

**Comment by nairdo** [comment]
It's probably also worth mentioning here that you can also control which forums you "watch" on the RockRMS site by going to your My Account > Edit Profile > [Notification Settings](http://www.rockrms.com/page/504).

**Comment by MrUpsideDown** [comment]
Excellent, thanks! This will make it much easier to keep track of relevant threads, especially as the forum activity continues to increase.
