### ISSUE TITLE
'Missing' State Defined Values Trigger Exception when Editing a Family

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#800]
As discussed here: http://www.rockrms.com/page/278?question=370

The following exception is caused by the Bing verify autocorrecting the address in a strange fashion. 

![image](https://cloud.githubusercontent.com/assets/8703222/5893607/b70a04a4-a4e2-11e4-9001-da86a4bfc804.png)

The 'State' field was autocorrected to a value not listed as a defined value triggering the error when trying to edit or add the address of a family.

**Comment by arranf** [comment]
Hey Mike.

Some extra details that may be of interest. I was using MK 2.0, with international addresses on, and with one "state" defined type.

Arran

**Comment by mikepetersonccv** [comment]
@arranf ok, now I can reproduce it.  The issue was that the Organization Address global attribute has a Province code that wasn't listed in the defined type values.  We'll fix that.  In the meantime, the workaround would be to update your Organization Address to have a valid province
