### ISSUE TITLE
Deleting block via delete button in Slide-out-bar causes: not found error

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#804]
This is reproducible but only seems to happen when the block has content (such as an HTML editor block with data in it).  
![deleteblock](https://cloud.githubusercontent.com/assets/383807/5927076/61c7a87e-a62d-11e4-82cb-2b727d30d90d.png)
![error](https://cloud.githubusercontent.com/assets/383807/5927080/66df8e58-a62d-11e4-886b-cf2205174118.png)
The block is apparently deleted however.  I suspect the delete api is getting called twice:
![networkconsole](https://cloud.githubusercontent.com/assets/383807/5927113/b21ff6dc-a62d-11e4-82bf-8f25c4c598d2.png)

**Comment by arranf** [comment]
I just wanted to add that I'm seeing similar behaviour when deleting a attribute value block on the person profile page.

The "Are you sure you want to delete this block?" dialog appears twice. 
![image](https://cloud.githubusercontent.com/assets/8703222/6210666/c73869fe-b5c9-11e4-8a17-ac4cca0fa72e.png)

The second "Ok" produces the same error [Not found]:
![image](https://cloud.githubusercontent.com/assets/8703222/6210682/f03046f6-b5c9-11e4-9181-d3ae56d1e564.png)
