### ISSUE TITLE
Exception: NullReferenceException in App_Web_kmenb551 every 15 minutes

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#809]
I'm getting the following exception error every fifteen minutes.  Do I need to fix something?  How can I find the cause?

----

An exception has occurred. Details of this error can be found below: 
An error occurred on the Rock site on page: 
http://elimrms.org:80/Webhooks/Mandrill.ashx
NullReferenceException in App_Web_kmenb551
Message
Object reference not set to an instance of an object.
Stack Trace
at Mandrill.ProcessRequest(HttpContext context)
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

-----

Here's my Exception log history:
![except1](https://cloud.githubusercontent.com/assets/4658177/5966622/f73205fa-a86a-11e4-8b89-2b836406dbd1.jpg)

----
and exception graph:
![except2](https://cloud.githubusercontent.com/assets/4658177/5966647/35ccc05c-a86b-11e4-9c01-9e27fcba0466.jpg)

---
Here's my communication history. No communications sent on the 26th when the exceptions started to increase.  (Unless the graph date uses local date, and the history uses the server date - remembering the difference between US and NZ time zones.)

![except3](https://cloud.githubusercontent.com/assets/4658177/5966756/f451d06c-a86b-11e4-8531-9b70afb431a4.jpg)

**Comment by edmistj** [comment]
@ElimAdmin If you click through the exception log you should be able to see the 'Show Server Variables' button. Could you send me the full query string that's causing the error? That would help me be able to recreate it.  Thanks!

**Comment by ElimAdmin** [comment]
@edmistj  Pictures first.  Text copied below if you need to cut and paste. I'm not sure which is the full query string.  Let me know if I can do anything else to help.

![sv1](https://cloud.githubusercontent.com/assets/4658177/6165956/f389d378-b310-11e4-80d7-b7554f6869a3.jpg)
![sv2](https://cloud.githubusercontent.com/assets/4658177/6165955/f386f90a-b310-11e4-840a-dd80906736c4.jpg)
![sv3](https://cloud.githubusercontent.com/assets/4658177/6165957/f38cd960-b310-11e4-96ce-ee9aca91d977.jpg)


-----
Summary

Site
Page
Exception Date
    08/02/2015 18:38

Server Variables
ALL_HTTP	HTTP_CONTENT_LENGTH:2594 HTTP_CONTENT_TYPE:application/x-www-form-urlencoded HTTP_ACCEPT:*/* HTTP_HOST:elimrms.org HTTP_USER_AGENT:Mandrill-Webhook/1.0 HTTP_X_MANDRILL_SIGNATURE:bOKYM+HChuPwkiUKiCjYt2rPlHI=
ALL_RAW	Content-Length: 2594 Content-Type: application/x-www-form-urlencoded Accept: */* Host: elimrms.org User-Agent: Mandrill-Webhook/1.0 X-Mandrill-Signature: bOKYM+HChuPwkiUKiCjYt2rPlHI=
APPL_MD_PATH	/LM/W3SVC/771/ROOT
APPL_PHYSICAL_PATH	E:\HostingSpaces\elimrms\elimrms.org\wwwroot\
AUTH_TYPE	
AUTH_USER	
AUTH_PASSWORD	
LOGON_USER	
REMOTE_USER	
CERT_COOKIE	
CERT_FLAGS	
CERT_ISSUER	
CERT_KEYSIZE	
CERT_SECRETKEYSIZE	
CERT_SERIALNUMBER	
CERT_SERVER_ISSUER	
CERT_SERVER_SUBJECT	
CERT_SUBJECT	
CONTENT_LENGTH	2594
CONTENT_TYPE	application/x-www-form-urlencoded
GATEWAY_INTERFACE	CGI/1.1
HTTPS	off
HTTPS_KEYSIZE	
HTTPS_SECRETKEYSIZE	
HTTPS_SERVER_ISSUER	
HTTPS_SERVER_SUBJECT	
INSTANCE_ID	771
INSTANCE_META_PATH	/LM/W3SVC/771
LOCAL_ADDR	23.91.123.116
PATH_INFO	/Webhooks/Mandrill.ashx
PATH_TRANSLATED	E:\HostingSpaces\elimrms\elimrms.org\wwwroot\Webhooks\Mandrill.ashx
QUERY_STRING	
REMOTE_ADDR	54.185.119.227
REMOTE_HOST	54.185.119.227
REMOTE_PORT	32511
REQUEST_METHOD	POST
SCRIPT_NAME	/Webhooks/Mandrill.ashx
SERVER_NAME	elimrms.org
SERVER_PORT	80
SERVER_PORT_SECURE	0
SERVER_PROTOCOL	HTTP/1.1
SERVER_SOFTWARE	Microsoft-IIS/8.5
URL	/Webhooks/Mandrill.ashx
HTTP_CONTENT_LENGTH	2594
HTTP_CONTENT_TYPE	application/x-www-form-urlencoded
HTTP_ACCEPT	*/*
HTTP_HOST	elimrms.org
HTTP_USER_AGENT	Mandrill-Webhook/1.0
HTTP_X_MANDRILL_SIGNATURE	bOKYM+HChuPwkiUKiCjYt2rPlHI=
Details

**Comment by edmistj** [comment]
@ElimAdmin This is helpful as it confirms that the request is coming from Mandrill, but since it's a POST request the specifics of the request are not provided. Can you look for more details of the failed request in your Mandrill logs. You can see this in Mandrill under 'Settings > API Logs'.  

Thanks for your assistance in helping with this.

**Comment by ElimAdmin** [comment]
@edmistj Looks like I've left it too late to get back to the last time this happened in the Mandrill logs.  The Mandrill logs now don't got back far enough to include the date of the last occurence (Feb 8), unless there is some way for me to view more events in the log?  We've not sent out bulk main for a while.  I'll keep watching.

**Comment by ElimAdmin** [comment]
I'm closing this.  No longer happening.
