### ISSUE TITLE
Administrative editing within dialogs impossible on mobile devices

### ISSUE THREAD

**Issue by ccofnow** [SparkDevNetwork/Rock#812]
Bootstrap does a great job for the most part of making all of Rock accessible no matter what size of device you're using. But there are a number of dialogs that are simply too wide to be usable on a phone - which is sometimes necessary.

Editing a block is the place I run into the most - admittedly a very administrative task that's not ideal on a phone, but sometimes it's necessary.
I know there are other more "normal" tasks with this issue as well (maybe a specific person editing dialog?) as well, though I can't think of them at the moment. I'll update here as I come across them.

**Comment by edmistj** [comment]
We've switched out the modals in v3 to be responsive. Think you'll like them.

**Comment by ccofnow** [comment]
Wonderful - can't wait! Thanks a lot.
________________________________
