### ISSUE TITLE
Recurring Schedule on Selected Dates Picker Broken

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#815]
Tested on my install and Rock demo site using the latest Chrome browser.

Steps to Reproduce:

1. Visit Home / Check-In Settings / Schedule Builder
2. Add a new schedule item or edit an existing one
3. Select recurring event - > specific dates
4. Select a date
5. Press okay

Result:
The okay button has no fucntion and the date is not saved.

**Comment by mikepetersonccv** [comment]
fixed in https://github.com/SparkDevNetwork/Rock/commit/dde2227e762b9a671064b344e6f5c9d950fcea9a
