### ISSUE TITLE
DISC Assessment Date showing 01/01/0001

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#828]
On the DISC results page (361), the Assessment Date is showing as 01/01/0001, despite being saved in the data.  This may be unique to me because I had to manually create this attribute and may have the wrong date format?

I also wonder if 'LastSaveDate' might be better named 'DISCLastSavedDate' - I can just see someone trying to use this generic attribute name for some other purpose.

![discassessmentdate](https://cloud.githubusercontent.com/assets/4658177/6051879/eca07a84-ad30-11e4-97b5-902f239b0fa6.jpg)

![discassessmentdateattvalue](https://cloud.githubusercontent.com/assets/4658177/6051958/f158ed6c-ad31-11e4-95dd-2addfb58e14c.jpg)

**Comment by mkinyon** [comment]
I ran into the same issue when inserting a date attribute in SQL. It seems that the format needs to look like this (yyyy-mm-ddThh:mm:ss.mmm) for it to work correctly.  I have used the below SQL to format my dates in that format:

SELECT convert(varchar, <yourdatevalue>, 126)

**Comment by arranf** [comment]
Per "I also wonder if 'LastSaveDate' might be better named 'DISCLastSavedDate' - I can just see someone trying to use this generic attribute name for some other purpose." that was suggested in #769

**Comment by ElimAdmin** [comment]
Thanks @mkinyon. 
Here are the attribute values as they have been saved by the DISC assessment workflow:

![discassessmentdateattvalue2](https://cloud.githubusercontent.com/assets/4658177/6076618/d9fcfe64-ae4a-11e4-8bc1-abea444aa9f4.jpg)

I manually edited the date format for me to "2015-01-31" - this now displays correctly on the DISC profile page (and on the extended attributes page).
All other dates show as 01/01/0001 (and do NOT display on the extended attribute page correctly).
Note that the last save date is being written in two DIFFERENT formats (month/day/year time PM / day/month/year/time p.m.) by the DISC workflow process.

I think the DISC workflow should be writing the LastSaveDate in the YYYY-MM-DD format but isn't.

**Comment by nairdo** [comment]
We've renamed that attribute "DISC Last Save Date".  We've also found the problem [where the the DiscService](https://github.com/SparkDevNetwork/Rock/blob/master/Rock/Model/DiscService.cs#L360) is not formatting the date string in the ISO 8601 format.  We'll fix that too.

**Comment by ElimAdmin** [comment]
@nairdo Great, thanks Nick.
