### ISSUE TITLE
Check Scanner utility- MIRC attribute order

### ISSUE THREAD

**Issue by ccofnow** [SparkDevNetwork/Rock#838]
There seems to be a bug in the check scanner external software.

We've got a new Canon CR-50, which is interfacing with the Rock software via the Ranger API, as noted in the documentation.

A good number (and increasing) number of checks are returning an "Invalid Account Information" error and not scanning however.

Now, I think I've found the pattern, probably the root cause, but the financial world is over my head so bear with me if I make bad assumptions.

When I run a problematic check through the Ranger software directly (not going through Rock), the MICR codes returned look like: (I've replaced the digits with X)
cXXXXXXc dXXXXXXXXXd XXXXXXXXXc

A check which was read correctly by Rock, on the other hand, looks like
dXXXXXXXXXd XXXXXXXXXXc XXXXX

In the Rock scanner, it identifies the first grouping as the routing number, the second grouping as the account number and the third number as the check number. But in the problematic check, you can see that the bank has ordered ordered the attributes as check number, routing number and then account number.

So it seems like Rock is hard-coded to take the first grouping as routing, the second as account, and the third as check. But it's my understanding that the flanking and trailing characters indicate their function, rather than their order. So the digits wrapped by 'd' characters are the routing number, the digits with a trailing 'c' are the account number, and the remaining group is the check number.

Again, I could be wrong about the particulars, but I believe that there's a system like that that allows for automated interpertation of the MIRC data regardless of order. And it seems like Rock isn't using that system.

**Comment by mikepetersonccv** [comment]
It looks like this was fixed with #639 (in commit https://github.com/SparkDevNetwork/Rock/commit/1b111711162c9404dfd6fd4940abcf4c332cce9c).  So it should be fixed in the 1.2.0 version of checkscanner.exe.  Can you confirm which version you used?

**Comment by ccofnow** [comment]
If the file version of the .exe file is accurate, it looks like we're using 1.0.14.0 (built 9/29/2014)
I hadn't realized it had been updated- we'll see about getting the new version, thank you. Any way that an administrator task could be added prompting us to update when the external apps are updated?

**Comment by ccofnow** [comment]
Confirmed that updating the check scanner utility fixed the issue, thank you.
