### ISSUE TITLE
Check Scanner Utility not storing check numbers?

### ISSUE THREAD

**Issue by ccofnow** [SparkDevNetwork/Rock#839]
When we use the check scanner utility and match transactions, the check number (which is correctly shown at scan-time) does not appear to be recorded anywhere. I've gone through the [TransactionListDetails] table as well as the [TransactionList] table, and I see that the "Transaction Code" column in the [TransactionList] table lists the check numbers for any checks manually inputted, but remains blank for scanned checks. I don't see any other data in the details table that appears to be check numbers, either.

It looks like the original MICR string is captured, but encryped and hashed...which obviously not going to do ME any good when it comes time for statements to be generated where we're going to need to list the check numbers.

If this is confirmed to be a bug, is there any way you will be able to go back through our past scanned transactions and extract the check numbers from the encrypted data so we don't lose out on being able to show checks which were scanned prior to the fix?

**Comment by azturner** [comment]
We're update scanning of checks to save the check number just like it would if entered manually, and will add migration to update existing transactions.  We've added the idea of including it on statements to our enhancement list.

**Comment by ccofnow** [comment]
Thanks so much =) Sounds perfect

**Comment by mikepetersonccv** [comment]
fixed in https://github.com/SparkDevNetwork/Rock/commit/363c8809c6f426baeb66f2a27e07b778bdfe0ffd
