### ISSUE TITLE
Custom date person attribute "potentially dangerous" in a report?

### ISSUE THREAD

**Issue by ccofnow** [SparkDevNetwork/Rock#854]
We've created a person attribute (date type, called "Joining God's Family Class") to note when someone has taken a class. Pretty typical. It's working well except that we just tried to create a report of people who have taken a specific class lately, and the client gets a 500 error - the exception calls it a "potentially dangerous Request.Form value".

The Data View filters for people who have their class attribute set to "after" a specific date (is it known that in the summary that shows up as "after ''"?). The list view works. Then we create a report based on that list view, add last name, nick name and the "Joining God's Family Class" attribute (so we can see WHEN they took the class). The report works and displays if we just show last name and nick name, but when we edit it to add the "Joining God's Family Class" attribute, it gives a 500 error.

The exception e-mail I receive:

An error occurred on the Rock RMS site on page: 
 ~/page/149?ReportId=20&ExpandedIds=140

HttpRequestValidationException in System.Web

Message
 A potentially dangerous Request.Form value was detected from the client (ctl00$main$ctl33$bid_202$ctl11$ctl00$reportFieldWidget_d38fb2d882d34f279eacc109e4486468$_hfTitle="...oining God's Family class").

Stack Trace
 at System.Web.HttpRequest.ValidateString(String value, String collectionKey, RequestValidationSource requestCollection)
 at System.Web.HttpValueCollection.Get(String name)
 at System.Web.UI.WebControls.HiddenField.LoadPostData(String postDataKey, NameValueCollection postCollection)
 at System.Web.UI.Page.ProcessPostData(NameValueCollection postData, Boolean fBeforeLoad)
 at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
 at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
 at System.Web.UI.Page.ProcessRequest()
 at System.Web.UI.Page.ProcessRequest(HttpContext context)
 at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
 at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by azturner** [comment]
@ccofnow , The 'potentially dangerous request' exception is due to HTML content being included in field that it is not expected in and the framework preventing possible possible cross-site scripting attacks.  What is the 'Column Label' value that you are using for this field when you add it to the report?

**Comment by ccofnow** [comment]
Just "Joining God's Family class"
________________________________

**Comment by azturner** [comment]
@ccofnow , trying to reproduce this, but unable to, unless HTML ( e.g. angle brackets ) is included in the column name ( you can see a [working example on the demo site](http://rock.rocksolidchurchdemo.com/page/149?ReportId=1003) ).  Does this report on the demo site differ from yours in any way?

**Comment by ccofnow** [comment]
Since I never can tell what might be the issue, I tried to match your demo to my situation as closely as possible:

renamed the attribute to Joining God's Family class (instead of just Joining God's Family)
renamed the attribute key to JoiningGodsFamilyClassDate (note you had an apostrophe in the key, I don't, so I got rid of it and added ClassDate to the end of the key you had)
Put the attribute in a custom Attribute Category called "Pathway Classes" to match mine.
Added "Pathway Classes" Attribute Values block to profile page, showing "Pathway Classes" attribute category
Added dates for that attribute to each person listed in the sample report you created.
Created a new Data View in the same hierarchy as my own
Renamed and updated which Data View the report uses
Added Phone number (mobile) to the Report

So now it matches as precisely as I can figure to my own report ... and yours still works.

I do note that your attribute title in the report has a ` instead of an ' in "God's", and I have no idea where that's coming from.

Is there anything else I can trace out in my installation to figure out where the error is coming from?

**Comment by azturner** [comment]
Was able to reproduce this.  The key is to not collapse that field before saving. When the field is first selected, it sets a hidden field to the title, but uses an HTML escaped value for the single quote (`&#39;`).  Once you collapse the field, it replaces the escaped quote with an actual single quote which is fine.  So the work-around is to just collapse the field first before saving.  Also, if you edit the report again, you'd have to expand/collapse that field again or you'll get a 500 error then too.  An even easier work-around for now also, is to just remove the single quote from the field label.  We'll get this fixed, but not sure it will make it in time for the 3.0 update.

**Comment by ccofnow** [comment]
Wow- rigorous investigation! Thanks for figuring that out- the workaround did indeed work perfectly.

**Comment by azturner** [comment]
This has already been fixed here: https://github.com/SparkDevNetwork/Rock/commit/4d8380199744c9d5fa13ec4664d03982ea433a75
