### ISSUE TITLE
Hide "Unknown" Marital Status in Bio Block?

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#855]
When Marital Status is set to "Unknown" the Bio block displays the word "Unknown" without any context. This looks strange - I think it is less confusing to display nothing at all.

Here is a change I have implemented and tested for our site:

In RockWeb.Blocks.Crm.PersonalDetail.Bio.OnLoad(EventArgs e)

Old:
```
lMaritalStatus.Text = Person.MaritalStatusValueId.DefinedValue();
```

New:
```
if (Person.MaritalStatusValueId.HasValue)
{
    var dvMaritalStatus = Rock.Web.Cache.DefinedValueCache.Read(Person.MaritalStatusValueId.Value);

    if (dvMaritalStatus != null &&
        !dvMaritalStatus.Guid.Equals(Rock.SystemGuid.DefinedValue.PERSON_MARITAL_STATUS_UNKNOWN.AsGuid()))
            lMaritalStatus.Text = dvMaritalStatus.Value;
}
```

Also, I think the Defined Value "Marital Status/Unknown" should probably be marked as a system-defined value? Currently, this Defined Value can be deleted, whereas "Married" and "Single" cannot.

**Comment by MrUpsideDown** [comment]
Also with regard to the "Unknown" Marital Status, I think the caption on the New Family page "The adults in this family are" might make more sense if it just read "Marital Status of Adults".

**Comment by azturner** [comment]
We're actually removing the 'Unknown' value from the marital status defined value list, since that's essentially the same thing as no value.

**Comment by MrUpsideDown** [comment]
Exactly! That's an even better solution - I guess the "Add Family" block will no longer have Marital Status as a required field then?

**Comment by azturner** [comment]
Correct, but it can now also be configured to force users to confirm entering a blank (unknown) marital status when they are adding new adults.

**Comment by MrUpsideDown** [comment]
All bases covered then - great work!
