### ISSUE TITLE
Queued up delete prompts in Prayer Requests

### ISSUE THREAD

**Issue by jhawkzz** [SparkDevNetwork/Rock#858]
If you have keyboard focus on the delete button, and use the keyboard to press enter, a new delete confirmation dialog will appear for each press of the enter key during the animation.

Additionally, clicking "OK" on each dialog box deletes an additional prayer request from the table.

**Comment by nairdo** [comment]
I'm no longer seeing this systemic problem and I'm not able to reproduce it in the latest of the develop branch.  Feel free to re-open if you see this behavior again and have instructions for how to reproduce it.
