### ISSUE TITLE
Add Family Page: Default Campus to empty if more than one entry in list?

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#862]
The Add Family page Campus field currently defaults to the first item in the list.
For a multi-campus church, this can be a problem because new People may be assigned to the wrong campus by accident.
Can the default for this field be set to empty if there is more than one Campus to choose from?

**Comment by azturner** [comment]
Fixed: https://github.com/SparkDevNetwork/Rock/commit/51071b9af175f3aa7b851446ed86f2467a6baa2f
