### ISSUE TITLE
Time Field Type Doesn't Accept 24HR Time

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#865]
Typing 19:30 into the time field doesn't convert it to 07:30 PM.

**Comment by arranf** [comment]
Additional Issue:
If you open the Group Attribute Values drop down on the  Group Viewer page then the time resets to 12AM

**Comment by mikepetersonccv** [comment]
@arranf I'm not quite sure what you mean on the '...time resets to 12:30 AM' issue.  Does the group have Time Group Attribute, for example "Meeting Time"?  If so, I'm unable to reproduce that.  Or maybe you meant something else.

**Comment by arranf** [comment]
Hey Mike,

The Meeting Time attribute is exactly what I'm referring to. I'm able to
reproduce this on the Rock demo server using my Chromebook.

On 2 March 2015 at 20:40, Mike Peterson <notifications@github.com> wrote:

> @arranf <https://github.com/arranf> I'm not quite sure what you mean on
> the '...time resets to 12:30 AM' issue. Does the group have Time Group
> Attribute, for example "Meeting Time"? If so, I'm unable to reproduce that.
> Or maybe you meant something else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkDevNetwork/Rock/issues/865#issuecomment-76815139>
> .
>



-- 
*​​Arran France*
​​
Communications, Youth Work, and Administration
​
*​T.* 07425 159471​

​
*​Hope Church Corby*
Registered
​ UK​
 Charity
​ ​
251549​
*​*
The Hope Centre
8 Princewood Road
Corby
NN17
​4
AP

**Comment by mikepetersonccv** [comment]
@arranf If you can still reproduce the 'changing time' issue, please create a new issue for that, and we'll keep this (#825) issue just for 24h timepicker issue.

**Comment by arranf** [comment]
Conversation for second issue continue in #873

**Comment by arranf** [comment]
@azturner I just tested this on 3.2 and I'm still experiencing the same behaviour.

**Comment by mikepetersonccv** [comment]
@arranf Oops, this actually isn't fixed until 4.0
