### ISSUE TITLE
Personal Tag Not Being Removed

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#868]
*Steps to Reproduce:*
1. Visit a profile page and create a new personal tag by labelling someone
2. Click the 'x'
3. Refresh the page
4. The tag is still there

You can delete the tag through the tag management page but it can't be removed from the profile page

**Comment by azturner** [comment]
@arranf , I'm not able to reproduce this on the demo site. What browser/OS are you using?

**Comment by arranf** [comment]
This was using ChromeOS but on Chrome on Windows 7 I can't reproduce this either. Will close.
