### ISSUE TITLE
& in username causes exception

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#871]
I just had a user sign up that used an & in their username and they can't log in:

>An error occurred on the Rock site on page: 
https://my.newpointe.org:443/api/userlogins/available/Adam&Leah
HttpException in System.Web
Message
A potentially dangerous Request.Path value was detected from the client (&).
Stack Trace
at System.Web.HttpRequest.ValidateInputIfRequiredByConfig()
at System.Web.HttpApplication.PipelineStepManager.ValidateHelper(HttpContext context)

We should probably just restrict those characters from being allowed in usernames?

**Comment by nairdo** [comment]
What do you think of something like this, where you can configure/change a regular expression and description that is used to validate the username: https://gist.github.com/nairdo/3431820b3bf9c76561ad

![image](https://cloud.githubusercontent.com/assets/383807/7169721/fcc6f3d4-e37c-11e4-8095-35f663953139.png)

**Comment by bwitting** [comment]
Makes sense to me!

**Comment by nairdo** [comment]
I ended up switching the two new attributes to Global Attributes just in case other blocks/REST API calls want to use it too.
