### ISSUE TITLE
Changing a Group's Parent Group can change its Group Type

### ISSUE THREAD

**Issue by mikepetersonccv** [SparkDevNetwork/Rock#872]
When editing a group, you can't edit the Group Type, but you can change the Parent Group.  If you happen to change a Parent Group that doesn't allow the current group type, the Group Type will change.

It should probably prevent you from changing to a Parent Group that doesn't allow that Group Type.

**Comment by nairdo** [comment]
I believe David fixed this via 29ebf31d13452325e1cd132619fe8a073f353602
