### ISSUE TITLE
Meeting Time Resetting on Edit

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#873]
Steps to Reproduce:
1. Edit an existing group
2. Expand the Group Attributes Values Drop Down
3. The Meeting Time resets

I've confirmed this on my own installation and on the Rock demo server.
Interestingly on the Rock demo server this does not work on Alisha Marble’s Group but does work on the Decker Group.

I've tested this on Chrome OS and on a regular Chrome Installation on Windows 7. I'm using the en-GB browser culture.

**Comment by mikepetersonccv** [comment]
ok, thanks!  It turns out that en-GB was the thing that helped reproduce it, and only if the time was 1pm or later.

**Comment by arranf** [comment]
It shows that more detailed info saves everyone a lot of time!

On 3 March 2015 at 15:57, Mike Peterson <notifications@github.com> wrote:

> ok, thanks! It turns out that en-GB was the thing that helped reproduce
> it, and only if the time was 1pm or later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkDevNetwork/Rock/issues/873#issuecomment-76972727>
> .
>



-- 
*​​Arran France*
​​
Communications, Youth Work, and Administration
​
*​T.* 07425 159471​

​
*​Hope Church Corby*
Registered
​ UK​
 Charity
​ ​
251549​
*​*
The Hope Centre
8 Princewood Road
Corby
NN17
​4
AP
