### ISSUE TITLE
Issue with saving Binary Files

### ISSUE THREAD

**Issue by edmistj** [SparkDevNetwork/Rock#874]
From this Q&A: http://www.rockrms.com/page/278?question=448
More details are on this post.

This may be a bug or it may be specific to my setup. Is anyone else having trouble uploading pdf's of previous background checks? To clarify the pdf will actually upload without a problem but it refuses to let me save the block once its finished. It will let me update the information under the background check block and save but never when there's a pdf involved. Is there a size limit that i'm missing?

**Comment by saconger** [comment]
I think we have this fixed.  It's a deadlock issue.  I'll do a pull request.
