### ISSUE TITLE
Possible Enhancement for Workflows?

### ISSUE THREAD

**Issue by demersus** [SparkDevNetwork/Rock#875]
Hi, I am working on building out a workflow with Rock. I am seeing the need to specify multiple criteria for running an action.  Currently there is only one conditional criteria that can be specified (Run if).  It would be nice to specify a little bit more complex logic such as:  Run if condition, and condition.  Or Run if condition or other condition...

Any plans to have this on the roadmap for workflows?  Is this a feature you would agree is needed?  I wouldn't want to work on a pull request if it is something that doesn't make sense in your vision.  Is there a better way to handle complex conditions?

**Comment by edmistj** [comment]
Hi Demersus! Think you have a solid need. Today you might consider placing your conditional logic in Lava using the 'Set Attribute Value' action. This allows you to have robust logic (lava in the text field) that returns a single value to an attribute that you can then filter on.

While not perfect we hope it meets your current need. We may extend the filtering capability in the future once we get more use cases under the belt. Doing so now would be difficult and possibly make the UI confusing.

**Comment by demersus** [comment]
Great, thank you.  I didn't know it was possible to use lava when setting attributes.  That should work great.
