### ISSUE TITLE
Check-In Scheduling Inaccurate

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#878]
Chrome with en-GB client culture.

Confirmed on local install and Rock demo site.

I have a created a check-in configuration and set the schedule as appropriate for our church. The schedule is set for next Sunday at 10:30am but the welcome screen countdown is 150 days and 20 hours.

My test config is still on the Rock demo site.

**Comment by arranf** [comment]
It's because the date format is being interpreted as a US date format so 08/03/2015 is 3 August (150 days away) rather than 8 March (Sunday).

**Comment by arranf** [comment]
The date format seems to be affecting more than just the countdown. I set a schedule for now and check in doesn't seem to recognise that check-in should be open now.

**Comment by nairdo** [comment]
@arranf I believe I've found the source of the problem.  I made a small change to the demo system to test, but I'm not certain about your test schedule.  Can you tell me if it appears to have fixed the issue for you on the demo system?

**Comment by arranf** [comment]
Hey Nick,
Your change seems to have worked. The welcome screen is now accurately
counting down to when we'd have the Sunday service. Is that a change I
could make on our production system? It would save me using the two test
schedules for this Sunday's check in.

I've set up a second schedule called "Now" which is set configured for the
current time to trigger the check in website to open up check in now but
it's still seeing the check in scheduled for Sunday.

Is that a separate bug?

On 6 March 2015 at 16:47, Nick Airdo <notifications@github.com> wrote:

> @arranf <https://github.com/arranf> I believe I've found the source of
> the problem. I made a small change to the demo system to test, but I'm not
> certain about your test schedule. Can you tell me if it appears to have
> fixed the issue for you on the demo system?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkDevNetwork/Rock/issues/878#issuecomment-77591624>
> .
>



-- 
*​​Arran France*
​​
Communications, Youth Work, and Administration
​
*​T.* 07425 159471​

​
*​Hope Church Corby*
Registered
​ UK​
 Charity
​ ​
251549​
*​*
The Hope Centre
8 Princewood Road
Corby
NN17
​4
AP

**Comment by nairdo** [comment]
@arranf With that fixed, I also see the issue on the demo server (v2.0) with the countdown stopping at 00:00:00 where it seemingly sits there stuck. I'm not able to replicate that issue with v3.0.  I'll try to replicate in a local 2.0 to be sure.

**Comment by nairdo** [comment]
> Is that a separate bug?

It may be. Let me attempt to repro that on my system using a "One Time" configuration.

**Comment by nairdo** [comment]
Yes, it's another bug.  The EffectiveEndDate is defaulting to 12:00AM but it should be set to the start date and time plus the duration.  I'll close this one and then open a new issue.
