### ISSUE TITLE
AttributeValues block to render a file uploader when editing values of field type 'binary file'

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#879]
Currently, it appears to be rendering a list of all other files that are of the same BinaryFileType that are currently stored in the system.  The current scenario may be correct for certain situations, but when attempting to attach a new document to a person's record it looks like we'll need another option.

Screenshot:
![attributevaluesblockwithbinfile_fieldtype](https://cloud.githubusercontent.com/assets/383807/6517188/d7e09382-c355-11e4-80ce-26464d8ac022.png)

**Comment by azturner** [comment]
@nairdo , There's also a 'File' ( vs. 'BinaryFile' ) field type that renders a file uploader control. Does that now work for what you would need?

**Comment by nairdo** [comment]
Sounds like it might. I'll check it out and then change how I'm importing all my document type data. I think Taylor's also using BinaryFile types on the Document Scanner... We may need to adjust our plans.

On Mar 5, 2015 4:49 PM, David Turner <notifications@github.com> wrote:

@nairdo<https://github.com/nairdo> , There's also a 'File' ( vs. 'BinaryFile' ) field type that renders a file uploader control. Does that now work for what you would need?

-

**Comment by azturner** [comment]
@nairdo , closing this issue for now since the 'File' field type should accomplish what you need. If not, feel free to re-open.
