### ISSUE TITLE
Inactive People in Check-in when in a Known Relationship 

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#881]
If a person's record is set to inactive, they do not appear in check-in; however, if they are in a known relationship with a person, they still appear when searching by that person's phone number, even if they are set to inactive.

**Comment by azturner** [comment]
@bwitting , we actually want inactive people to show up in both cases. If a person we've marked as inactive shows up on a weekend, we still want them to be able to check-in.  The exception to this is if they are marked deceased. In this case they shouldn't show up in either case (with family or as part of relationship to another family). In my testing this seems to be working correctly. On the demo site, I set up Jenny Michaels to be able to check in Noah Decker.  When he was inactive (without being deceased), both his family and Jenny could check him in, but when he's marked deceased (sorry Noah), neither his family or Jenny could check him in.  Are you seeing different behavior?

**Comment by bwitting** [comment]
Sorry, you're right - it is working exactly as you described.  

I understand your intended use case, but is there any way to have someone removed from the check-in list besides marking them deceased? We have families get confused because there are so many families that show up when they search, and some of those families we know have moved, etc.

Another thing we might to do help with that is change our instructions - we are having people search by only their last four digits right now, but having them search by 7 or 10 should greatly reduce the results.

**Comment by azturner** [comment]
Yeah, we would lean towards encouraging people to enter more numbers vs. trying to hide inactive members. Sooner or later one of those people that moved away are going to come back and visit and wonder why they can't check-in.
