### ISSUE TITLE
Check-In Manager Not Displaying Multiple Campuses Correctly

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#882]
This is a bit of a vague issue as I'm seeing a similar but not identical issue on the demo site and on my installation.

On the demo site I have set up a second configuration which shares groups for two campuses. I have two kiosks set up -- one for each campus.

On the demo site I am unable to select any of the campuses in that configuration in the check in manager. (I have selected the correct configuration!)
![screenshot 2015-03-06 at 19 17 27](https://cloud.githubusercontent.com/assets/8703222/6532028/7b3fdc9c-c435-11e4-96bf-26fc87c2127b.png)

Last night I was having a similar issue on my production installation where I was able to view one campus perfectly and able to select the second campus but not able to view any of the groups.

Currently I am able to select the second campus and view most of the groups but I have a group missing!

en-GB culture MK 2.0

**Comment by nairdo** [comment]
@arranf A few things to verify/check:

* Did you add the new campuses via the [Campuses page](http://rock.rocksolidchurchdemo.com/page/85)?   Doing it this way should allow the campus to show up in the Campus Context Setter block. 

![image](https://cloud.githubusercontent.com/assets/383807/6547403/0d845a2e-c594-11e4-89c4-4bb5024acb96.png)

* You might consider setting up a Building for each campus and then add rooms under those.
* I've found there _is_ some odd behavior if you try to go bounce between different campues that don't share the same check-in type configurations on the [Campus Manager page](http://rock.rocksolidchurchdemo.com/page/300).  Instead, always start on the [Check-in Type](http://rock.rocksolidchurchdemo.com/page/299) page.  (This odd behavior will be investigated further to try to find a better solution.)

If you do this you should see things as you expect.  Can you confirm?

**Comment by arranf** [comment]
I think you've hit the nail on the head. It appears to be to do with having the groups with just a top level location specified. If you break them down into specific rooms then the groups display properly.

**Comment by arranf** [comment]
@nairdo I'm not seeing this behaviour anymore. I think this is closeable. What do you think?

**Comment by azturner** [comment]
I think this would happen if you switched campuses while viewing a location ( vs a group type ). If so, that will be fixed in 4.0
