### ISSUE TITLE
Check-in OneTime Schedule Not Working

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#883]
Related to #878, when setting up a check-in schedule using a "One Time", the EffectiveEndDate is defaulting to 12:00AM so it isn't passing this if check on line 362 in the [Schedule's GetNextCheckInStartTime](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/Schedule.cs#L362) method.

I believe the EffectiveEndDate should be set to the start date and time plus the duration.

**Comment by azturner** [comment]
Fixed here: https://github.com/SparkDevNetwork/Rock/commit/2d4726042c8a0f9b134a0fdd18a157518937c37d
