### ISSUE TITLE
Person Birth Dates Not Being Displayed: Person.BirthDate NULL

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#885]
en-GB, MK 2.0

After using Excavator to import a small number of records I noticed that not every person that was imported had a birthdate. The BirthDay, BirthMonth, and BirthYear were populated in the Person table for every record but the BirthDate column was NULL for some.

I rolled back our DB to pre-import and after a quick check I noticed  three records that were manually entered are also experiencing this same problem. If I use edit individual to edit their birthday the BirthDay, BirthMonth, and BirthYear values are in the DB but their BirthDate column value remains NULL.

I tried changing the values in the table to NULL and then setting the person's birthdate using edit individual but that didn't trigger the BirthDate to be calculated.

**Comment by arranf** [comment]
I've ran the following query:

SELECT [Id]
      ,[BirthDay]
      ,[BirthMonth]
      ,[BirthYear]
      ,[BirthDate]
  FROM [rock].[dbo].[Person]
  where [BirthDate] is NULL
  and BirthDay is not NULL
  and BirthMonth is not NULL
  and BirthYear is not NULL

And my results are:
Id	BirthDay	BirthMonth	BirthYear	BirthDate
2	21	9	1994	NULL
3	24	1	1947	NULL
4	19	1	1945	NULL

**Comment by azturner** [comment]
@arranf , BirthDate is a SQL Computed Field ( It's not a value that is stored in the table ). It's value is computed on every query using the following sql statement:

    (case when isdate((((isnull(CONVERT([varchar],[BirthYear]),'0001')+'-')+CONVERT([varchar],[BirthMonth]))+'-')+CONVERT([varchar],[BirthDay]))>(0) then CONVERT([date],(((isnull(CONVERT([varchar],[BirthYear]),'0001')+'-')+CONVERT([varchar],[BirthMonth]))+'-')+CONVERT([varchar],[BirthDay]))  end)

Not sure why those dates won't compute correctly for you.  What are the results of these SQL queries in your environment:

    SELECT ISDATE('1994-9-21')
    SELECT CONVERT([date],'1994-9-21')

**Comment by arranf** [comment]
(No column name)
--------
1994-09-21
1994-09-21
1994-09-21
1994-09-21
1994-09-21

**Comment by azturner** [comment]
@arranf , If you just run this sql statement: `SELECT ISDATE('1994-9-21')` do you get a 1 (true) or a 0 (false) returned.

**Comment by arranf** [comment]
Hey David
Sorry I was running
```
SELECT ISDATE('1994-9-21')
from [dbo].[Person]
```
Running `SELECT ISDATE('1994-9-21')`
I get a 0 returned.

On 9 March 2015 at 15:18, David Turner <notifications@github.com> wrote:

> @arranf <https://github.com/arranf> , If you just run this sql statement: SELECT
> ISDATE('1994-9-21') do you get a 1 (true) or a 0 (false) returned.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkDevNetwork/Rock/issues/885#issuecomment-77873166>
> .
>



-- 
*​​Arran France*
​​
Communications, Youth Work, and Administration
​
*​T.* 07425 159471​

​
*​Hope Church Corby*
Registered
​ UK​
 Charity
​ ​
251549​
*​*
The Hope Centre
8 Princewood Road
Corby
NN17
​4
AP

**Comment by azturner** [comment]
Looks like the SQL ISDATE() function doesn't think a date in 'yyyy-mm-dd' is a valid date format when using the gb language setting.

Can you run this query on your db to update the birthdate computed column and then test your results again to see if birthdate is getting calculated correctly.

	ALTER TABLE [dbo].[Person] DROP COLUMN [BirthDate]
	ALTER TABLE [dbo].[Person] ADD [BirthDate] AS CASE WHEN ISDATE(
		RIGHT('0000' + CAST([birthyear] as varchar(4)), 4) + RIGHT('00' + CAST([birthmonth] as varchar(2)), 2) + RIGHT('00' + CAST([birthday] as varchar(2)), 2)
		) = 1 THEN CONVERT( [date],
		RIGHT('0000' + CAST([birthyear] as varchar(4)), 4) + RIGHT('00' + CAST([birthmonth] as varchar(2)), 2) + RIGHT('00' + CAST([birthday] as varchar(2)), 2)
		) ELSE null END

**Comment by arranf** [comment]
@azturner 
That worked perfectly!
