### ISSUE TITLE
Lowercase "SMS" on Communicate Template Page

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#891]
![image](https://cloud.githubusercontent.com/assets/8703222/6583590/01ccd90c-c75d-11e4-8ba3-bbcc3c96f152.png)

**Comment by nairdo** [comment]
@arranf There are a few other places where you'll see the "Sms" too.  in the mean time you might consider changing the friendly name of the SMS component entity to be all uppercase (while we discuss what we plan to do.)

    UPDATE [EntityType] SET [FriendlyName] = 'SMS' WHERE [Guid] = '4BC02764-512A-4A10-ACDE-586F71D8A8BD'

**Comment by arranf** [comment]
Okay! This was one I tried to fix. Glad it's not as straightforward as I
thought!
