### ISSUE TITLE
Include Question Title in Subject of Forum Notification Emails?

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#898]
I have subscribed to receive all notifications from the Rock forums, so I have a lot of emails in my Inbox with subjects like "New Q&A Comment On A Question".
It would be much easier to pick out the ones I am really interested in if the email Subject included the Question Title, similar to GitHub notifications (eg. "[RockQA] Can't login because I have forgotten my password").

**Comment by arranf** [comment]
@MrUpsideDown This can be closed now!

**Comment by MrUpsideDown** [comment]
This issue has been addressed by the most recent Q&A forum updates.
@arranf - thanks for the reminder.
