### ISSUE TITLE
Closing Rooms by Schedule

### ISSUE THREAD

**Issue by FrankGrand** [SparkDevNetwork/Rock#901]
Not sure if this would be a feature request, but currently I can't figure out how to close rooms by named schedules in the checkin manager.  Am I missing something, or is this the intended functionality?

A use case would be we have two evening services, so volunteer children check in for both services at the same time.  We have certain rooms closed during our 1st evening service (light attendance) that are open for the 2nd.

**Comment by edmistj** [comment]
Would using the Check-in Manager interface work? http://www.rockrms.com/Rock/BookContent/10#checkinmanager

**Comment by FrankGrand** [comment]
I'm using the Check-In Manager, but right now it seems that the room is either open or closed for all schedules.  I'm wondering if I can close a room just for one particular schedule.

**Comment by edmistj** [comment]
@FrankGrand Does the 'Schedule Locations' on the new Device Manager screens solve this?  See: http://www.rockrms.com/Rock/BookContent/10/68#devicemanager

**Comment by FrankGrand** [comment]
@edmistj is the only difference that through the device manager you would only see the locations configured to that kiosk?

**Comment by edmistj** [comment]
@FrankGrand Yes

**Comment by FrankGrand** [comment]
Hey @edmistj between just adjusting the schedules and with this upgrade, we can definitely make this work!  Thanks!
