### ISSUE TITLE
Rock Administrators set to Pending or Inactive still have Administrator Privileges 

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#905]
If you change a person's existing Rock Administrator security role to inactive or pending they still retain administrator privileges.

**Comment by tcavaletto** [comment]
For the security authentication, the group member status is not used, as Rock determines security permissions solely based on whether they're in the security role group. While this is unlikely to change in Rock McKinley, hiding this status may be something that is explored in future updates.

**Comment by cabal95** [comment]
@arranf While testing for a new (UI) bug, I believe this has changed and is fixed. On the Rock Demo site I created a new person and added them to the RSR - Rock Administration security role as "Inactive" and received the rock Access Denied page after logging in.
