### ISSUE TITLE
Incorrect currency symbol for total when adding new transaction

### ISSUE THREAD

**Issue by jezhailwood** [SparkDevNetwork/Rock#907]
When adding a new transaction, the fund form input uses the currency symbol set in Global Attributes, but the total displays USD.

**Comment by edmistj** [comment]
Sorry, there's a few places where this is an issue. We'll go through Rock and update these. Since v3 is out of dev it will need to be in the next release.

**Comment by jezhailwood** [comment]
No problem at all!
