### ISSUE TITLE
Timeout on large communication

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#909]
On McKinley 2.0

We are trying to send a communication to the results of a Report of about 13,000 people (using the New Communication button at the bottom of the grid) - but I am getting a timeout exception.

Is there another way to do this to avoid the long processing time?

OR - how can I increase the timeout period?

Thanks!

**Comment by dcs619** [comment]
Starred ^.  We typically send an email to everyone in our system (minus unsubscribes) 2x a year at Christmas and Easter.

**Comment by mikepetersonccv** [comment]
This is fixed with #847.

**Comment by tcavaletto** [comment]
We're encountering the same issue in 1.4.1 when clicking the New Communication button on a DataView of 9k people, where we're getting a timeout exception. Can anyone else confirm?

**Comment by bwitting** [comment]
@tcavaletto I just tested it with a list that size. It took forever, but it worked. Maybe try changing your timeout settings in SQL Server: https://msdn.microsoft.com/en-us/library/ms189040.aspx
