### ISSUE TITLE
Alias ID instead of Person Alias ID

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#917]
We're seeing that SMS replies are going to the Person who's PersonAlias.Id (not PersonAlias.AliasPersonId) = the PersonId who created the communication.

**Comment by treyhendon** [comment]
Possibly line 71 on: Rock/Rock/Communication/Medium/Sms.cs

**Comment by arranf** [comment]
Treyhendon,
Just to clarify. SMS messages are going to the SMS communication creator rather than the response recipient?

**Comment by treyhendon** [comment]
Sorry, no.   Just the reply text messages are going to the wrong recipient.  So, here's how/what is happening.

We use a staff member's login (who is also set as the "Response Recipient") to create a new SMS.

We sent that SMS to one recipient (another staff member).

When the recipient replies, in Communications History we see that the recipient of that response text is not the person set as the "Response Recipient".  Rather, it is someone who happens to have PersonAlias.Id the same as the Response Recipient's Person.Id (instead of PersonAlias.PersonId = Person.Id OR PersonAlias.AliasPersonId = Person.Id - whichever is correct matching logic).

Hope that makes more sense now.

**Comment by azturner** [comment]
@treyhendon , This is how Rock would determine the person to send the replies to.  Can you take a look at these queries, run them, and let me know where they break down (select the wrong person), and what the results are:

	-- Find the defined value who's value matches the phone number that Twilio is sending to
	DECLARE @DefinedValueId int = ( 
		SELECT TOP 1 V.[Id] 
		FROM [DefinedValue] V
		INNER JOIN [DefinedType] T
			ON T.[Id] = V.[DefinedTypeId]
		WHERE T.[Name] = 'SMS From Values'
		-- AND V.[Value] = '--- The reply number ---'
	)

	-- Get that defined value's person alias guid value
	DECLARE @PersonAliasGuid varchar(50) = (
		SELECT TOP 1 AV.[Value]
		FROM [AttributeValue] AV
		INNER JOIN [Attribute] A
			ON A.[Id] = AV.[AttributeId]
			AND A.[Guid] = 'E9E82709-5506-4339-8F6A-C2259329A71F' -- Constant for 'Response Recipient' attribute
		WHERE AV.[EntityId] = @DefinedValueId
	) 

	-- Get the person id for the saved person alias guid
	DECLARE @PersonId int = (
		SELECT TOP 1 [PersonId]
		FROM [PersonAlias] 
		WHERE [Guid] = CAST(@PersonAliasGuid AS uniqueidentifier)
	)

	-- Get the person
	SELECT [NickName], [LastName]
	FROM [Person]
	WHERE [Id] = @PersonId

**Comment by treyhendon** [comment]
Hey David,

The logic through all of those SQL statements checks out.

The thing we're seeing is that @PersonId 639 is set as the Response Recipient.  However, when a reply text comes in, we see that it is set to be sent to PersonId 641 (who happens to have PersonAlias.Id = 639, PersonAlias.PersonId = 641).  That's what's leading me to guess it's a column mis-match somewhere.

Trey

**Comment by azturner** [comment]
@treyhendon , Not sure what you mean by "@PersonID 639 is set as the Response Recipient", since the Response Recipient attribute stores the guid for a PersonAlias record.  Can you share the results of those queries? Is there an actual Person record with an id of 639, or could that person record have been merged into person record with id of 641?  

Results of these two query would be helpful too...

    SELECT * FROM [PersonAlias] WHERE [PersonId] IN (639,641)
    SELECT * FROM [Person] WHERE [Id] IN (639,641)

**Comment by treyhendon** [comment]
Sorry David,

I meant to say that the person who is set as the Response Recipient has a PersonId of 639.  Since this is live data, I'll email you the results to protect folks' privacy.

Thanks!
-Trey

**Comment by azturner** [comment]
https://github.com/SparkDevNetwork/Rock/commit/b38aaf68fc82fd56a4ffbb18fb73fd9a5907b805
