### ISSUE TITLE
Report might not show Address for some People even though they have an Address

### ISSUE THREAD

**Issue by mikepetersonccv** [SparkDevNetwork/Rock#923]
If any parts of the Address are null (street1, street2, etc), the full address will be null

**Comment by bwitting** [comment]
Hey @mikepetersonccv, I'm still having an issue with this in 3.1:

![2015-04-07 13_24_55-reports _ rock rms](https://cloud.githubusercontent.com/assets/1859094/7029172/86839528-dd29-11e4-9efc-e68086a764f9.png)

Is there any other info I can give you to help look into this?

**Comment by MrUpsideDown** [comment]
@bwitting: I found that the Person.Address Report field only shows an address if the "Mailing" flag is checked for that address. Not sure if this is the cause of the behavior you are seeing, but it's worth looking into. See here for a discussion about this issue:
http://www.rockrms.com/Rock/Ask/Troubleshooting/Questions/472

**Comment by mikepetersonccv** [comment]
Sorry, it didn't actually make it into 3.1 yet
