### ISSUE TITLE
Space in account number on check causes the Check Scanner App to think it's invalid

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#924]
On McKinley 3.0:

We have a local bank that puts spaces in the account number that is printed in the MICR data on the bottom of the check.  The check scanner won't read this check.  Here's what it looks like:

![check](https://cloud.githubusercontent.com/assets/1859094/6967437/39a0bc72-d92d-11e4-91ab-8868cd680c12.png)

![scan](https://cloud.githubusercontent.com/assets/1859094/6967442/42275586-d92d-11e4-96d6-47d2fcf3195d.png)

**Comment by flaretechcc** [comment]
This is a problem I can confirm on previous versions of Rock as well. We're using the ranger software with a CR-50 scanner.

**Comment by FrankGrand** [comment]
I've been testing the check scan app and have a related comment.  It would be great if the image of the check could still be saved even if it can't be fully read.  For us we have our campuses scan checks and then we handle the matching, etc centrally.

**Comment by bwitting** [comment]
Forgot to mention - we are using CR-50 and CR-80 scanners.  I'll test to see if this happens on the MagTek scanner.

**Comment by bwitting** [comment]
@mikepetersonccv Is there any other data I can get you guys to help with this?

**Comment by nairdo** [comment]
@bwitting , @FrankGrand , Here's our proposed solution... we'd like your feedback on it:  We'd slow check scanning down to confirm a good scan before reading the next check, however if it was unable to read the MICR it will stop and highlight the issue, and then ask you if you want to 're-try/re-scan' or 'accept & continue' (which would keep the scanned image in the batch but without the MICR).

**Comment by FrankGrand** [comment]
@nairdo That would be great for us!

**Comment by bwitting** [comment]
@nairdo Sounds good to us. Thanks!

**Comment by bwitting** [comment]
I've got an addition to this.  For some reason, it seems like our local banks like to do weird stuff with checking account numbers: 

![check](https://cloud.githubusercontent.com/assets/1859094/7481642/910420b8-f33f-11e4-9763-dd205f4b7cd4.jpg)

That symbol is a dash (http://www.troygroup.com/support/documents/50-70300-001_CMICRBasicsHandbook_000.pdf), and it was working with version 2.0 of the check scanning app.  Now in 3+ it won't scan.  (I got this image from a successful transaction in Rock) 

It looks like we need to account for dashes along with spaces in the MICR text too.  Thanks!

**Comment by bwitting** [comment]
Hey @nairdo, any update on this?  Some staff have been coming at me with pitchforks...  Thanks!

**Comment by nairdo** [comment]
Sorry guys, I don't have any newer news on this issue.  We did discuss it as a team and decided that this would be our proposed solution. 

> Is there any other data I can get you guys to help with this?

@bwitting, One thing we just discussed yesterday was about trying to obtain an actual voided check from one of the offender banks so we could test our solution with it.  I know it's a big ask, but do you think one of your people would be willing to contribute a voided blank check for us to test?

**Comment by FrankGrand** [comment]
@nairdo not sure if it helps, but we are finding that any "e-bill pay" check from BB&T Bank is not scanning correctly, the account number is never being read in.

**Comment by bwitting** [comment]
@nairdo I should have a check for you on Tuesday!  Please shoot me an email and tell me where you want me to send it

**Comment by bwitting** [comment]
@mikepetersonccv - did you receive the check I sent in the mail?  Thanks!

**Comment by mikepetersonccv** [comment]
@bwitting - oops, didn't notice this message until now.  Yep, I got it and it was a tremendous help.  Thank you!

**Comment by mikepetersonccv** [comment]
fixed in https://github.com/SparkDevNetwork/Rock/commit/8600b99150e14df3b6f06b10faea4b09c109a2e7
