### ISSUE TITLE
403 Error on Document Upload

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#929]
On McKinley 3.0/3.1:

When uploading a document as a user *with any role besides Rock Administrator*, I get a 403 error:

![2015-04-07 13_14_37-sarah witting _ rock rms](https://cloud.githubusercontent.com/assets/1859094/7029069/8b5ea7a0-dd28-11e4-8b77-0703dc577075.png)

Here's the edit permissions for that attribute:

![2015-04-07 13_16_13-person attributes _ rock rms](https://cloud.githubusercontent.com/assets/1859094/7029095/c0909870-dd28-11e4-9103-5e75e9c21050.png)

This is happening on any attributes that use a document upload, not just the one I picutred.  (for example, this is happening to Background Check documents even if the person is in the Safety and Security Role)

**Comment by mikepetersonccv** [comment]
Could you look at Home > General Settings > File Types, and see what the EDIT security is for the File Type for that document?  Note that Uploading requires EDIT security even though "Require View Security" is false.

**Comment by bwitting** [comment]
Thanks Mike, that was it.  Only the Administrator Role had edit permissions on those file types.  I gave other roles edit permissions and it is working as expected.

**Comment by nairdo** [comment]
Before we close this we need to consider whether or not we need a data migration to "resolve" this for everyone too.

**Comment by bwitting** [comment]
@nairdo I think this changed with the Rock 3.0 update.  I think we may still be having some permissions trouble on file types (see #932)

**Comment by arranf** [comment]
Is definitely fixed as of 1.5.2
