### ISSUE TITLE
Closing </div> tag no longer generated on Dynamic Data Block

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#931]
As of McKinley 3.0, there seems to be a missing </div> tag on the end of the Dynamic Data Block.  Here is a page with a bunch of Dynamic Data Blocks:

![2015-04-07 15_24_22-weekly reporting _ rock rms](https://cloud.githubusercontent.com/assets/1859094/7031551/65704cf8-dd3a-11e4-8642-e25d98a2e73a.png)

This didn't happen before the 3.0 update. It can be fixed manually by adding `</div>` in the Block Properties > Advanced Settings > Post-HTML

**Comment by edmistj** [comment]
Remedy found.
