### ISSUE TITLE
Issues Sending Email via Mandrill (System.FormatException)

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#932]
On McKinley 3.0:

I've gotten a few reports of trouble sending email via Mandrill.  When this happens, on the Communication screen all emails fail with the note: `SMTP Exception: Failure sending mail`

If I look at the exception log, I see:

`System.Exception: Exception in Global.DrainTransactionQueue(): SendCommunicationTransaction` (with no stack trace) 

and

`System.FormatException: The specified string is not in the form required for an e-mail address.`  
Stack Trace: `at System.Net.Mail.MailAddressParser.ParseAddress(String data, Boolean expectMultipleAddresses, Int32& index)
   at System.Net.Mail.MailAddress..ctor(String address, String displayName, Encoding displayNameEncoding)
   at Rock.Communication.Transport.SMTPComponent.Send(Communication communication)
   at Rock.Communication.Medium.Email.Send(Communication communication)
   at RockWeb.Global.DrainTransactionQueue() in c:\inetpub\wwwroot\App_Code\Global.asax.cs:line 796`

The problem is that I'm not exactly sure how to reproduce this.  I sent an email to just myself with an attachment and received this error.  Then I copied the communication, removed the attachment, and it sent just fine.  However, the few other times where this is happening, the user didn't add an attachment at all and got the same error.

**Comment by bwitting** [comment]
Also, I wanted to mention that we've already sent over 12,000 emails this month via Rock/Mandrill, so by and large Mandrill is working.

**Comment by bwitting** [comment]
Did some more testing this morning, and this error always happens when there is an attachment.  And it rarely happens when there isn't.  I'm still trying to find the common denominator of what is happening when I get this error with no attachment.

**Comment by edmistj** [comment]
Think we found the problem though it should only effect emails with attachments. Fix is being worked on as we speak.

**Comment by bwitting** [comment]
@edmistj I also have some staff saying they are having trouble even adding an attachment to an email (they get a 403 page). 

![firefoxscreensnapz005](https://cloud.githubusercontent.com/assets/1859094/7052702/373f224a-ddfe-11e4-99c8-df2f7437dde8.png)


Is this related? Or perhaps related to #929 ?  I'm not sure what File Type email attachments get uploaded as.

**Comment by bwitting** [comment]
Confirmed emails with attachments are now working with the new 3.1 update from @azturner.
