### ISSUE TITLE
Record Status Reason is not visible for Inactive Person

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#934]
If a Person has Record Status = Inactive, and no Record Status Reason is selected, the Record Status Reason drop-down is not visible on the Edit Person page.
The drop-down becomes visible by changing the status to Active and then back to Inactive, but it seems to me that it should be visible on first entry to the page.

**Comment by edmistj** [comment]
Open to community fixing

**Comment by arranf** [comment]
I'll claim this one. @mrupsidedown
