### ISSUE TITLE
Report Export to Excel contains Guid instead of Value for Defined Type

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#935]
When the "Export To Excel" function is used for a report that contains a Defined Type field, the export file contains the Guid value of the Defined Type rather than the Value.

It would be great if the Defined Type Report Field also included the "Display Descriptions" option, just like the Person Attribute Defined Type does in 3.0

**Comment by arranf** [comment]
Pretty sure I saw a commit for this recently.

On 10 April 2015 at 09:03, MrUpsideDown <notifications@github.com> wrote:

> When the "Export To Excel" function is used for a report that contains a
> Defined Type field, the export file contains the Guid value of the Defined
> Type rather than the Value.
>
> It would be great if the Defined Type Report Field also included the
> "Display Descriptions" option, just like the Person Attribute Defined Type
> does in 3.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkDevNetwork/Rock/issues/935>.
>



-- 
*​​Arran France*
​​
Communications, Youth Work, and Administration
​
*​T.* 07425 159471​

​
*​Hope Church Corby*
Registered
​ UK​
 Charity
​ ​
251549​
*​*
The Hope Centre
8 Princewood Road
Corby
NN17
​4
AP

**Comment by MrUpsideDown** [comment]
I can't find anything related to this... can you point me to it?

**Comment by arranf** [comment]
I had a look through recent commits and couldn't find it but I did find this, "Updated the grid export to resolve defined value ids with their values when exporting to Excel.", in the 3.0 release notes.

Based off our conversations I assume you're running 3.0?

**Comment by MrUpsideDown** [comment]
Yes, this is still an issue in 3.0

**Comment by azturner** [comment]
If the defined value field is an actual property on the entity (i.e. Connection Status) it shows correctly in Excel. However if the field is a defined value attribute, it is still displaying the guid.

**Comment by MrUpsideDown** [comment]
Thanks @azturner, that confirms the behavior I am seeing.
