### ISSUE TITLE
Previous Church Description Text Accidentally A Word

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#939]
"The church or denomination that person attended prior to visiting here"

"The church or denomination that **this** person attended prior to visiting here"

**Comment by dcs619** [comment]
You know your issue is "missing" a word right? :)

**Comment by arranf** [comment]
That was somewhat intentional ;)

**Comment by tcavaletto** [comment]
Fixed in https://github.com/SparkDevNetwork/Rock/commit/02c69c289dd08303fe9ffa151ca09348a67eea6c.
