### ISSUE TITLE
New Family Screen shows "Cell Phone" instead of the Defined Type Value

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#941]
In the New Family Screen (Page 2) when entering contact information for family members, the "Home Phone" and "Cell Phone" field labels do not show the correct values from the Defined Type "Phone Type". The labels seem to be hard-coded to "Home Phone" and "Cell Phone".

**Comment by arranf** [comment]
I'm working on this. Confused one of our staff members today!
