### ISSUE TITLE
Inconsistency in Buttons

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#943]
Both the calendar and time selects have a text input field, a grey icon, and a pop-up select

The difference is for the time select (used in scheduling) you can click on the grey icon in order to bring up the select but for the calendar clicking the grey icon does nothing.

I noticed trialing Rock with our staff that this inconsistency caused a lot of confusion.

**Comment by arranf** [comment]
Dupe of #1189 which is way more articulate.

**Comment by edmistj** [comment]
Thanks for cleaning up!
