### ISSUE TITLE
Alt+E Shortcut Doesn't Edit Individual

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#947]
I understand this may be by design as edit family and edit individual are both on the person profile page.

**Comment by edmistj** [comment]
A page can only have one event tied to a key. We could add:

Alt-I to edit the individual
Alt-F to edit the family 

to this screen.

**Comment by edmistj** [comment]
Ugh... can't use F.  Maybe O since it's right next to I?

**Comment by nairdo** [comment]
Jon fixed this via https://github.com/SparkDevNetwork/Rock/commit/b68211b756141e3514aa73689eea5e4ddcba8a21 which is now in [alpha testing](http://www.rockrms.com/page/473?Item=51).
