### ISSUE TITLE
Metric Schedules Never Run

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#950]
Setting a schedule for SQL or DataView in Metrics never runs.  I've tried using One Time and Recurring but neither seem to work.

**Comment by FrankGrand** [comment]
@BelAirIT I had to go to the jobs admin page, and add a job.  One of the Job Types is Rock.Jobs.CalculateMetrics

**Comment by BelAirIT** [comment]
I don't see that as an option:

![image](https://cloud.githubusercontent.com/assets/7409839/7163566/99e45f2c-e34f-11e4-9663-6dfe428170d6.png)

**Comment by FrankGrand** [comment]
Hmmm, here is what mine looks like, our Rock instance may be pointed to the develop branch and not the release
![screenshot 2015-04-15 at 12 18 07 pm](https://cloud.githubusercontent.com/assets/6911214/7163720/811bc79a-e369-11e4-96af-26845328ac64.png)

**Comment by arranf** [comment]
I'm not seeing that job either.

**Comment by edmistj** [comment]
Yes, this job is added in v4.0. We realized it was missing during our CCV roll-out.
