### ISSUE TITLE
Post-Delete Triggers never fire

### ISSUE THREAD

**Issue by benwiley** [SparkDevNetwork/Rock#953]
In addition post-save triggers fire on delete instead of the post-delete triggers.  Please watch this video for a better explanation (https://www.youtube.com/watch?v=L4dj_at0Fxk).  The video was shot using the develop branch of Rock.

The solution could be to change the if statement condition to be "deleted" OR "detached".  However, my theory is that the "deleted" state can never occur in RockPostSave so just changing the if condition to "detached" should suffice.

**Comment by dcs619** [comment]
Closed with https://github.com/SparkDevNetwork/Rock/pull/954
