### ISSUE TITLE
Duplicate Emails (via Mandrill) on Large Communications

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#955]
On McKinley 3.1 - (and it happened on 3.0 too)

Twice now, we've sent a large email blast (one was around 900, one around 1100) and everyone gets 2 emails.  It even shows up in Mandrill that way:

![2015-04-16 16_04_36-outbound activity _ mandrill](https://cloud.githubusercontent.com/assets/1859094/7190760/59bb2450-e456-11e4-8f78-3710a7b4df43.png)

But in the Rock communication, everyone is listed on the Communication To list only once, and each email in the history is listed only once:

![2015-04-16 16_36_41-communication 517 _ rock rms](https://cloud.githubusercontent.com/assets/1859094/7190839/f0db7038-e456-11e4-8270-b9597b9894e7.png)

We initially thought this happened because a husband and wife might both have the same address on their record.  When that happened, that address got 4 emails.

In the picture above, you can see that the email had 967 recipients, but Mandrill shows double that (plus extra from the other emails sent today)

![2015-04-16 16_37_27-outbound activity _ mandrill](https://cloud.githubusercontent.com/assets/1859094/7190854/11e2bbf6-e457-11e4-9716-cf8574600861.png)

Both of these large emails where this happened were made from a grid of results from a Data View.  I tested with a very small list of staff from a Data View, and they only got one email each.  This only time this seems to be a problem is with a very large amount of recipients.

On the duplicates, the we used a Lava Merge Field for the Nickname, and it was correct on both emails that people received, so it seems like Rock is passing the email off twice to Mandrill

![email](https://cloud.githubusercontent.com/assets/1859094/7190927/a7354c00-e457-11e4-9475-ba5744f216f0.png)

**Comment by azturner** [comment]
@bwitting , what is the value of your Communication Entry block's "Send When Approved" setting?

**Comment by bwitting** [comment]
@azturner Send When Approved is Yes, Maximum Recipients is at 1500.

The first time the duplicates happened, the email was sent by a campus ministry staff person and someone from the Communications department approved it.  The second time it happened, the email was sent from a person on my team who is a Rock admin, so it just went out (I guess it gets auto-approved if a person with approval rights tries to send?

**Comment by azturner** [comment]
This is due to Rock not being able to finish sending the communication to all recipients prior to the communication starting to send to the same remaining recipients. We'll get a fix for this in 3.2. In the meantime, you can set the 'Send When Approved' setting on that block to false which will then defer all sending of emails to the send communication Job (in which case you could also change the job's 'Delay' setting to 0).

**Comment by bwitting** [comment]
Great, thanks David. I made those changes.

**Comment by azturner** [comment]
Fixed for 3.2: https://github.com/SparkDevNetwork/Rock/commit/d7d7526ba1cae72749cb75a50f0c5a05bd098a03

**Comment by hims2017** [comment]
@azturner  actually, we are also facing same issues. Based on the earlier posts in this thread, we were trying to figure out how we could update to version 3.2 but the api doc (https://mandrillapp.com/api/docs/) show 1.0 as the version (https://mandrillapp.com/api/1.0/). Please advise what we would need to update to version 3.2.

**Comment by edmistj** [comment]
@hims2017 We no longer support Mandrill due to their licensing change. There is still one large church using it though, so the Rock side of the integration should still work. That's about all the help we can provide though.

**Comment by arranf** [comment]
@hims2017 I just wanted to chip in and say that the 3.2 previously mentioned is Rock 3.2

**Comment by hims2017** [comment]
Thanks @arranf @edmistj . I realized that the discussion is for Rock only after posting the issue.
