### ISSUE TITLE
Extended attributes not showing up

### ISSUE THREAD

**Issue by ccofnow** [SparkDevNetwork/Rock#957]
We upgraded to 3.0 and immediately to 3.1 on Wednesday, so I don't know which of these upgrades induced this glitch. But when a person's "Extended Attributes" profile page is viewed, several of the attribute values blocks display only a colon (:) in their bodies. If I choose to edit [i]any[/i] attribute values block on the page, they all populate correctly again. Once I hit cancel (or save) on that edit operation, they stay visible, but only until the page is reloaded.

While typing this up, I noticed for the first time that the troublesome attribute values blocks are all in page zone B1. Finding that interesting, I added an identical Attribute Values block to page zone B2 and pointed it at the same attribute category as one of the blocks in zone B1. Sure enough, once I reload the page, all of the blocks in zone B1 show only a colon, but the duplicate block in B2 is correctly populated. Maybe an AJAX or JavaScript is failing to fire on zone B1?

**Comment by azturner** [comment]
@ccofnow , I'm not able to reproduce this. Wondering if you could include a screen shot ( or if it's sensitive data you can email it to me )

**Comment by azturner** [comment]
@ccofnow , Took a look at your site, and this was due to the script you had on that page for doing some special processing for the 'Benevolence' attribute. I updated it to handle a change that 3.0 made to the block's wraping DIV elements.
