### ISSUE TITLE
Adding people to groups using bulk update broken 3.1

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#958]
Rock McKinley 3.1  (Yeah! Thank you, thank you, thank you! Group Attendance - thank you!)

Selecting people from Data Viewer, then selecting Bulk Update (Truck icon) says that the people are added to the group, but the link is not made.

![addgroup1](https://cloud.githubusercontent.com/assets/4658177/7212727/e1c89444-e5bf-11e4-8f3f-693d7fbd3f5d.jpg)

![addgroup2](https://cloud.githubusercontent.com/assets/4658177/7212728/e1cb7a24-e5bf-11e4-9e76-8f6cf0b23037.jpg)

But when returning to view the members in the group they have not been linked:

![addgroup3](https://cloud.githubusercontent.com/assets/4658177/7212730/e1d1a21e-e5bf-11e4-8c60-1977bcb2a417.jpg)

**Comment by arranf** [comment]
I've just tested this on our production install which is running 3.1 and I'm not seeing this behaviour. 
I ran a data view, used bulk update (without using a checkbox) and added all the people from that to an empty group (of the small group type) and they all have been added.

**Comment by ElimAdmin** [comment]
Thanks Arran.  I can't reproduce this now.  I'll do some more testing.

**Comment by ElimAdmin** [comment]
I can't reproduce this.  Closing the issue.
