### ISSUE TITLE
Statement Generator prints StartDate - StartDate

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#962]
The top right of the statement printed by the Statement Generator prints the date range as the Start Date - Start Date.  But on the form it has the field EndDate.  Looks like the EndDate is not being supplied correctly.

Is it possible to have EmailAddress as a field on the statement?  This will make it easier to email out large numbers of statements.

![stat1](https://cloud.githubusercontent.com/assets/4658177/7228809/1b6e0f10-e7b1-11e4-8095-8c770ca96eff.jpg)

**Comment by mikepetersonccv** [comment]
It looks like it is showing StartDate - EndDate, but they just happen to have the same month and day (but different year)

**Comment by mikepetersonccv** [comment]
If you are still wanting the Email feature, go ahead and open a new issue for that :)
