### ISSUE TITLE
Admin Toolbar Behind Page Zones

### ISSUE THREAD

**Issue by matthewmeekins** [SparkDevNetwork/Rock#963]
When you click on "Page Zones" to configure which blocks are in a zone, the admin toolbar goes behind the zones so that you can't click on the buttons. I don't think it did this before 3.0. 

The first image is before, and the second image is after I click on the "Page Zones" button. Let me know if you need clarification

![screen shot 2015-04-20 at 12 54 16 pm](https://cloud.githubusercontent.com/assets/10676326/7235507/956a888e-e75c-11e4-8f15-68f5cacb23fe.png)
![screen shot 2015-04-20 at 12 53 54 pm](https://cloud.githubusercontent.com/assets/10676326/7235510/9bfcd29c-e75c-11e4-83d6-190161589795.png)

**Comment by arranf** [comment]
I can confirm I've experienced this.
