### ISSUE TITLE
Issues with Site Domains/Routes

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#967]
**Edit:**
Issue: I have a new site with a login page with the route logon. This site is on a single domain newsite.domain.org. 

If I visit the site from internalsite.domain.org/logon then I see a different page to if I visit newsite.domain.org/logon.

If I make a change to Rock (such as activating an authentication provider or changing a user's security settings) then the changes are immediately visible on internalsite.domain.org/logon but not on newsite.domain.org/logon.

After a period of time the changes are visible on the newsite page.

**Original Text:**
I've set up a microsite specifically for a subgroup of Rock users. I've secured it by creating a new security role group leader and made it so all pages on the site are viewable by this security role.

Today, to test it I added the group leader security role to a person with no other security roles and attempted to login as them. They were redirected to the login screen, successfully logged in, and then were redirected to an error page.

I then attempted to login as a user who had both the staff and group leader security role (added yesterday) and logged in as that user successfully. I then removed the staff security role and successfully logged in as them again. I removed the group leader security role -- and could log in successfully.

From this test I presume there is some level of caching going on. I would expect the new user to be able to log in once they were a part of the security group and the second user to not be able to log in once they weren't but based off of the behaviour I'm seeing the changes aren't instantaneous.

**Comment by arranf** [comment]
This doesn't appear to affect the internal site which makes me wonder if it's a configuration issue with the login route or the login block as opposed to an issue with Rock.

**Comment by arranf** [comment]
I think I've pinned it down a bit more. I appear to have two distinct logon pages 
internal.domain.org/loginroute and microsite.domain.org/loginroute.

Logging in to the microsite seems to be using old security roles whereas the internal logon page uses the correct security roles.

**Comment by arranf** [comment]
As an update I was able to log on using the microsite domain later in the evening.

**Comment by azturner** [comment]
@arranf , Is your new site just a new logical site in Rock ( i.e. it's not using a different IIS website application )?

**Comment by arranf** [comment]
Yes.

On 22 April 2015 at 12:46, David Turner <notifications@github.com> wrote:

> @arranf <https://github.com/arranf> , Is your new site just a new logical
> site in Rock ( i.e. it's not using a different IIS website application )?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkDevNetwork/Rock/issues/967#issuecomment-95147009>
> .
>



-- 
*Arran France*
Communications, Youth Work, and Administration
*T*. 07425 159471

*Hope Church Corby*
Registered UK Charity 251549
The Hope Centre
8 Princewood Road
Corby
NN174AP

**Comment by arranf** [comment]
Appears fixed in 1.3.4
