### ISSUE TITLE
Prayers Not Displayed For Prayer Team

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#969]
When a prayer request block is not set to auto-approve and an admin goes into Rock to approve it, it doesn't show up for anyone on the prayer team.  Looking at the SQL entry for that prayer request shows a missing expiration date.  Once an admin goes into that prayer request and manually saves it again, the expiration date is stamped and it can be seen by the prayer team.

**Comment by azturner** [comment]
@BelAirIT , thanks for troubleshooting this.
