### ISSUE TITLE
Routes failing for Sites with Multiple Domains

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#970]
Visiting internal.hopecorby.org/logon (internal site)  and domain1.hopecorby.org/logon (primary domain) works but visiting domain2.hopecorby.org/logon (secondary domain) produces a page not found error.

**Comment by edmistj** [comment]
@arranf I'm not able to reproduce this.  As verification (though this is a v.4 alpha site)

http://www.sparkdevnetwork.com/rx2015
http://admin.sparkdevnetwork.org/rx2015
http://www.rockrms.com/rx2015

**Comment by arranf** [comment]
I'm seeing those redirect to the right place. I'll set up a test to reproduce this using our production environment and report back after the DNS has propagated to see if I'm going crazy.

**Comment by arranf** [comment]
I've tried to reproduce this and can't.
