### ISSUE TITLE
Cannot locate RockRMS Version 2.1

### ISSUE THREAD

**Issue by bacsrlette** [SparkDevNetwork/Rock#971]
Hi, what is the link to download earlier versions of Rock RMS? 

We are using the Excavator tool to import data and learned that this import tool works with an earlier version (Rock RMS v2.1).

Please advise. Thank!

**Comment by arranf** [comment]
​If you download the Rock installer you should be able to update to 2.0 and
then import to that version.
There is no 2.1 in terms of available stable releases.​

On 22 April 2015 at 20:07, bacsrlette <notifications@github.com> wrote:

> Hi, what is the link to download earlier versions of Rock RMS?
>
> We are using the Excavator tool to import data and learned that this
> import tool works with an earlier version (Rock RMS v2.1).
>
> Please advise. Thank!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkDevNetwork/Rock/issues/971>.
>



-- 
*Arran France*
Communications, Youth Work, and Administration
*T*. 07425 159471

*Hope Church Corby*
Registered UK Charity 251549
The Hope Centre
8 Princewood Road
Corby
NN174AP

**Comment by bacsrlette** [comment]
@arranf - Thanks for the quick response. We have 3.1 installed now, so I am assuming that we uninstall 3.1 and then do a fresh install of 2.0?

**Comment by arranf** [comment]
@bacsrlette I've never tried downgrading Rock so my answer would be yes

**Comment by dcs619** [comment]
@bacsrlette If you're just looking to get data into your Rock install, I have a version of Excavator in develop that will work with 3.1.  I don't want to release it to the community until I do a full test import on our instance though.   https://github.com/NewSpring/Excavator/blob/develop/Excavator.zip

**Comment by bacsrlette** [comment]
@dcs619 - Yes, all we need is to get our data into 3.1 so we'll give this version a try today and let you know how it goes.

**Comment by dcs619** [comment]
@bacsrlette Any updates?  I'm testing/releasing the update to 3.1 this week.

**Comment by bacsrlette** [comment]
@dcs619 - Hi David, thanks for touching base. We were able to use the development version to successfully import our records in 3.1. However, during the data load our server locked up and we had to restart it. We were not able to capture the error in the logs but right before it locked up, Excavator was loading Organization information. When we rebooted the sever we did not have to reload because all of the records were there and in tact.

**Comment by bacsrlette** [comment]
Question - Where can we find the release schedule for RockRMS? Also, is 3.1 the most up to date version?

**Comment by dcs619** [comment]
I believe 3.2 is the most up to date version (just released yesterday).

David Stevens

*Web Developer*NewSpring Church
www.newspring.cc
864-965-9540

**Comment by arranf** [comment]
David is right 3.2 is the most up to date. This [Trello board](https://trello.com/b/C8gulcfu/roadmap) is the roadmap. There isn't really a release schedule per say.  I'd listen to the [February Video Podcast](http://www.rockrms.com/page/470?Item=105) for a better overview of how the Rock team operates (the content is referring to the 3.0 update so that side of things is out of date)
