### ISSUE TITLE
Data View with First Contribution Date filter takes very long time to load

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#972]
In McKinley 3.1 - 

We have a data view using the First Contribution Date filter, and it takes over 3 minutes to load (in this case, we are using 4/1/15 - 4/30/15 as the date range, and it returns 91 rows).  When we make a report with this data view, it is timing out (the block timeout setting is at 180, I'll increase it) Here's how the data view is set up:

![2015-04-22 15_47_48-data views _ rock rms](https://cloud.githubusercontent.com/assets/1859094/7283790/f88ba122-e906-11e4-863f-518b04a6a059.png)

Thanks!

**Comment by bwitting** [comment]
Hey @mikepetersonccv, we are on 3.3 and still having this issue.  The dataview still takes a very long time to load, and is still timing out with the block timeout settings at 240.

**Comment by mikepetersonccv** [comment]
Oh man, sorry! I can't believe I didn't notice my mistake before. I was able to reproduce it being slow still(1:40 seconds for my test database).  Changing it to use a MAX clause sped it up to just a few seconds.  Hopefully this will fix it for you as well.  If this fixes it, this will also speed up your report.

**Comment by bwitting** [comment]
Thanks!
