### ISSUE TITLE
Persisting Workflow Failing

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#974]
When using the Automatically Persist checkbox, workflows do not persist. Only by manually adding the Persist Workflow action does it function properly.

**Comment by azturner** [comment]
@BelAirIT , I wasn't able to reproduce this. I [created a new workflow type](http://rock.rocksolidchurchdemo.com/page/136?workflowTypeId=2018&ExpandedIds=1150) on the demo site that had the Automatically Persisted checkbox checked and everything [appears to be working](http://rock.rocksolidchurchdemo.com/page/288?WorkflowTypeId=2018).

Are you able to reproduce this on the demo site (which is running 3.1)?
