### ISSUE TITLE
Schedule.EffectiveStartDate in Liquid returning empty

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#981]
As of McKinley 3.0, `{{ Schedule.EffectiveStartDate }}` is returning empty. 

(We are using it to get the start time of a service for check-in name tags: `{% for group in GroupType.Groups %}{% for location in group.Locations %}{% for schedule in location.Schedules %}{{ Schedule.EffectiveStartDate | Date:'htt' }}{% endfor %}{% endfor %}{% endfor %}`)

**Comment by azturner** [comment]
Unfortunately, in 3.0, the EffectiveStartDate field is no longer being used ( and will eventually be removed ). The schedule has a StartTime field that has the same value, but unfortunately, it's currently not available to Lava. We've fixed that for 3.2, so you'll want to update your mergefield value to be this instead...

    {% for group in GroupType.Groups %}{% for location in group.Locations %}{% for schedule in location.Schedules %}{{ schedule.StartTime | Date:'htt' }}{% endfor %}{% endfor %}{% endfor %}
