### ISSUE TITLE
Update the Rock project header text

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#982]
The "about project" text sounds like a mashup between the old ChMS description and the current description: 
![screenshot 2015-04-23 12 57 27](https://cloud.githubusercontent.com/assets/1210933/7302573/539308ce-e9b8-11e4-8e45-a0d54a69fd61.png)

Recommended text instead (stolen from @MrUpsideDown) 
An open source CMS, Relationship Management System (RMS), composable application framework, and more.

**Comment by nairdo** [comment]
Perhaps we can just add ... CMS, ChMS, ... to catch any searchers for church management systems.

**Comment by arranf** [comment]
I'll throw in my converted $0.02, I was heavily searching for open source
ChMS but only came across it via
https://church.io/open-source-church-software/.

Mentioning ChMS might make discovering you guys via search easier.

On 23 April 2015 at 19:41, Nick Airdo <notifications@github.com> wrote:

> Perhaps we can just add ... CMS, ChMS, ... to catch any searchers for
> church management systems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkDevNetwork/Rock/issues/982#issuecomment-95680630>
> .
>



-- 
*Arran France*
Communications, Youth Work, and Administration
*T*. 07425 159471

*Hope Church Corby*
Registered UK Charity 251549
The Hope Centre
8 Princewood Road
Corby
NN174AP

**Comment by nairdo** [comment]
Thanks @arranf I think that's why I added that 'In fact...ChMS' mash up a little while back. I agree we should keep the term in there since it's used by others.

**Comment by nairdo** [comment]
landed on "An open source CMS, Relationship Management System (RMS), Church Management System (ChMS), and composable application framework."
