### ISSUE TITLE
Duplicate Person Created Through Facebook Not Correctly Identified

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#983]
A user with an existing person profile logged in using Facebook. A duplicate person was created with the same email address, first name, and last name. Using the data integrity tools, the person is listed as a pending person but the duplicate finder couldn't find a match.

**Comment by MrUpsideDown** [comment]
Hey Arran, did you check to see if the "Calculate Person Duplicates" job has actually completed? It might be obvious, but I made this mistake the other day - I thought the Duplicate Finder had failed to find a match, but the job hadn't actually run yet.

**Comment by arranf** [comment]
@MrUpsideDown You're completely right. No issue with the Rock duplicate finder but I think line 352 of Facebook.cs is meant to be matching based off name and email and it doesn't look like it worked this time around but I may be misunderstanding what's going on there.

**Comment by azturner** [comment]
yeah, looks like we're missing a "!". Nice catch. we'll get a fix for that into 3.2.
