### ISSUE TITLE
Rock Duplicate Finder Still Recognising Duplicates Following Merge

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#985]
Rock found two records that were duplicates, I then used person merge (from that page) to merge the two records. After merging the two records are still listed as possible duplicates.

**Comment by matthewmeekins** [comment]
I've seen this happen as well. I'm also have an issue in the Duplicate Finder that once I mark certain records as not duplicates those same records will come back as duplicates when the job runs again.
