### ISSUE TITLE
Address search broken in 3.1 (and 3.0?)

### ISSUE THREAD

**Issue by ccofnow** [SparkDevNetwork/Rock#994]
The auto-complete when selected search type is "Address" in the quick search box does not work. Pressing enter after a query takes me to a functional search page as expected, but the auto-complete is nice for finding people quickly, and it still works with the other search types. I disabled the "address" search service and re-enabled it, to no avail.

**Comment by arranf** [comment]
Can confirm this has been broken since 3.0.
