### ISSUE TITLE
Group Details Security

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#995]
When navigating to a group's details, nothing displays.  Only when logged in do the details show up.  Currently, each group has to have its security manually updated before it will show up.

Example: http://www.rocksolidchurchdemo.com/page/4324?GroupId=3110

![image](https://cloud.githubusercontent.com/assets/7409839/7356576/ef26780c-ecdd-11e4-8c8e-20253590a809.png)

**Comment by arranf** [comment]
I can reproduce this as of 1.5.2

**Comment by nairdo** [comment]
Group details are not automatically view-able by _All Users_, however the [Group Finder block](http://www.rockrms.com/Rock/BookContent/7/75#groupfinder) uses the "Is Public" flag of a group to determine whether or not to display it on the map.
