### ISSUE TITLE
Facebook Auth Setting Typo

### ISSUE THREAD

**Issue by kcirgjd** [SparkDevNetwork/Rock#997]
![facebookauth](https://cloud.githubusercontent.com/assets/7595345/7377383/0bc16144-edb4-11e4-8256-4b8ee3b3ee72.png)

**Comment by mikepetersonccv** [comment]
You have a tpyo in the github title :)

**Comment by MrUpsideDown** [comment]
Should we open a new issue to fix the typo in this issue? ;-)

**Comment by kcirgjd** [comment]
I tend to be good at finding typos with how many I make.
